### ISSUE TITLE
Given solution is failing on a test case on 436: Find Right Interval

### ISSUE THREAD

**Issue by rohitkrishna094** [LeetCode-Feedback/LeetCode-Feedback#3457]
#### Your LeetCode username

[Anonymous]

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Second premium solution titled (sorting + scanning) is failing on below test case: [[1,1],[3,4]]

#### Code you used for Submit/Run operation

```
Code is part of premium, so not sure if I should share it here. 
Let me know if it's ok to share if otherwise in comments.
```

#### Language used for code

Irrevelant

#### Expected behavior

Given solution has to work on all test case.

**Comment by Rohitesh-Kumar-Jain** [comment]
> Hi @Rohitesh-Kumar-Jain

You tagged the wrong person I believe ?

**Comment by lc-kay** [comment]
Hi @rohitkrishna094 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
