### ISSUE TITLE
Trips and Users : Test cases are passing even with wrong code

### ISSUE THREAD

**Issue by sgupta-dev** [LeetCode-Feedback/LeetCode-Feedback#3458]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Even though i am providing wrong solution  while submitting it's accepting my solution without providing any error. You can see in below code i am comparing with client and used Client_Id two times instead of Driver_id and Role as 'Driver'

#### Code you used for Submit/Run operation

```
select t.Request_at as Day, 
round(sum(case when t.Status like 'cancelled%' then 1 else 0 end)/count(*),2) as "Cancellation Rate" 
from Trips t 
join Users c on c.Users_Id = t.Client_Id and c.Role = 'client' and c.Banned = 'No'
join Users d on d.Users_Id = t.Client_Id and d.Role = 'client' and d.Banned = 'No'
where t.Request_at between Date("2013-10-01") and Date("2013-10-03")
group by t.Request_at
order by t.Request_at

```

#### Expected behavior

Ideally this should not accept this code. accepted solution would be 
```
select t.Request_at as Day, 
round(sum(case when t.Status like 'cancelled%' then 1 else 0 end)/count(*),2) as "Cancellation Rate" 
from Trips t 
join Users c on c.Users_Id = t.Client_Id and c.Role = 'client' and c.Banned = 'No'
join Users d on d.Users_Id = t.Driver_Id and d.Role = 'driver' and d.Banned = 'No'
where t.Request_at between Date("2013-10-01") and Date("2013-10-03")
group by t.Request_at
order by t.Request_at

```

**Comment by lc-kay** [comment]
Hi @sgupta-dev 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
