### ISSUE TITLE
Example Solution Error - 959. Regions Cut By Slashes

### ISSUE THREAD

**Issue by cmunigwe** [LeetCode-Feedback/LeetCode-Feedback#3459]
#### Your LeetCode username

cmunigwe

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Example Solution produces range run time error 

#### Code you used for Submit/Run operation

```
class DSU:
    def __init__(self, N):
        self.p = range(N)

    def find(self, x):
        if self.p[x] != x:
            self.p[x] = self.find(self.p[x])
        return self.p[x]

    def union(self, x, y):
        xr = self.find(x)
        yr = self.find(y)
        self.p[xr] = yr

class Solution(object):
    def regionsBySlashes(self, grid):
        N = len(grid)
        dsu = DSU(4 * N * N)
        for r, row in enumerate(grid):
            for c, val in enumerate(row):
                root = 4 * (r*N + c)
                if val in '/ ':
                    dsu.union(root + 0, root + 1)
                    dsu.union(root + 2, root + 3)
                if val in '\ ':
                    dsu.union(root + 0, root + 2)
                    dsu.union(root + 1, root + 3)

                # north/south
                if r+1 < N: dsu.union(root + 3, (root+4*N) + 0)
                if r-1 >= 0: dsu.union(root + 0, (root-4*N) + 3)
                # east/west
                if c+1 < N: dsu.union(root + 2, (root+4) + 1)
                if c-1 >= 0: dsu.union(root + 1, (root-4) + 2)

        return sum(dsu.find(x) == x for x in xrange(4*N*N))
        
```

#### Language used for code

Python

#### Expected behavior

Example test case:
[
  " /",
  "/ "
]

Expected:
Output: 2

Instead produces error:
TypeError: 'range' object does not support item assignment
    self.p[xr] = yr
Line 13 in union (Solution.py)
    dsu.union(root + 0, root + 1)
Line 23 in regionsBySlashes (Solution.py)
    ret = Solution().regionsBySlashes(param_1)
Line 56 in _driver (Solution.py)
    _driver()
Line 67 in <module> (Solution.py)

**Comment by lc-kay** [comment]
@cmunigwe Please run the test case in the correct format, such as [" /","/ "]. This test case is the first test case in our set. Thank you for your time.

**Comment by cmunigwe** [comment]
Hi @lc-kay The test case did not show properly on GitHub, I used the exact example test case you provided without modification.

**Comment by lc-kay** [comment]
@cmunigwe When running your provided code and the test case, it gets accepted. Please provide a screenshot of the issue if you do not receive the same result.
