### ISSUE TITLE
Missing TestCases for [Weekly Contest 190-Problem-4]

### ISSUE THREAD

**Issue by arpitx165** [LeetCode-Feedback/LeetCode-Feedback#346]
**What kind of the bug**
- [ ] [Problem](https://leetcode.com/problems/max-dot-product-of-two-subsequences)
- [x] solution
- [ ] Python

**Describe the bug**

Test-cases are missing for this problem : 

[1, 1]
[-1, -1,-2]

Answer should be -1 but still its accepting the solution.

**what language is your code written in**
Python

**The code you submit/run**
```
from functools import lru_cache

class Solution:

    def maxDotProduct(self, nums1: List[int], nums2: List[int]) -> int:
        @lru_cache(None)
        def getAns(i, j):
            if i >= len(nums1) or  j >= len(nums2):
                return 0
            return max(getAns(i+1, j+1)+nums1[i]*nums2[j], getAns(i+1, j), getAns(i, j+1))
        xx = getAns(0, 0)
        if xx == 0:
            return max(nums1)*min(nums2) 
        return xx
```
I feel this problem doesn't have all test cases.

**Comment by CooperCooperCooper** [comment]
Hi @arpitx165 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @arpitx165 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

Side note: We want to clarify that your code is actually in Python3 and not Python.
