### ISSUE TITLE
Missing Test Case - 429. N-ary Tree Level Order Traversal

### ISSUE THREAD

**Issue by arjunnarang** [LeetCode-Feedback/LeetCode-Feedback#3460]
#### Your LeetCode username
Arjun_Narang_12

#### Category of the bug
- [ ] Question
- [ ]Given an n-ary tree, return the level order traversal of its nodes' values.

Nary-Tree input serialization is represented in their level order traversal, each group of children is separated by the null value (See examples).
- [ ] Solution
- [ ] Language
- [ ] java
- [ ] Missing Test Cases 

#### Description of the bug
There is a bug in test cases in this question. After the solution got accepted, the solution is still giving the wrong answer in one test case. 

I tried putting an invalid testcase (which i didnt know was invalid at that time).
After inserting the numbers in an array for pre order traversal of n-ary tree and running the code, the console shows wrong answer. I tried submitting it and it got accepted passing all the test cases. But it still shows 'wrong answer' in that invalid testcase.

 

#### Code you used for Submit/Run operation
```
class Solution {
    public List<List<Integer>> levelOrder(Node root) {
        
        //if root is null return empty list
        if(root == null){
            List<List<Integer>> list = new ArrayList<>();
            return list;
        }
       
        // creating larger list
        List<List<Integer>> largeList = new ArrayList<>();
        
        //creating smaller list
        List<Integer> smallList = new ArrayList<>();
        
        //queue for storing the node levelwise
        Queue<Node> q = new ArrayDeque<>();
        q.add(root);
        
        while(q.size() > 0){
            int s = q.size();
            smallList = new ArrayList<>();  //initializing small list every time new level starts 
            for(int i = 0; i<s; i++){
                Node node = q.remove();
                smallList.add(node.val);   // adding elements in small list
                for(int j = 0; j<node.children.size(); j++){
                    q.add(node.children.get(j));
                }
            }
            largeList.add(smallList); // adding smaller lists in largelist
        }
        return largeList;
    }
}

```

#### Language used for code
Java

#### Expected behavior
If we put [1,3] as an input, the expected behavior is 'invalid input' or 'invalid testcase' but the code runs, and the console shows 'wrong answer'. When you submit the code, it passes all default testcases

#### Screenshots
![image](https://user-images.githubusercontent.com/56109994/117657276-feaf5600-b1b6-11eb-9d0c-3038dead656d.png)

#### Additional context
This needs to be resolved as it may consume a lot of time for the coders to figure out where are they going wrong.

**Comment by lc-kay** [comment]
Hi @arjunnarang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @arjunnarang 
Thank you for your time. The team reviewed your report and noticed the problem was a bug in the driver code. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
