### ISSUE TITLE
Incorrect Time Complexity Analysis- 204. Count Primes

### ISSUE THREAD

**Issue by Nil0ofar** [LeetCode-Feedback/LeetCode-Feedback#3461]
#### Your LeetCode username

nil0ofar

#### Category of the bug
- [ ] Question
- [x]  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There are two problems in the article.

1.  In the penultimate paragraph, it is said that `O( n/2 + n/3 + n/5 + ... + n/p) = O(loglogn)` . in which `p` is the last prime less than `n`. 
but it has been proven [here](https://www.geeksforgeeks.org/how-is-the-time-complexity-of-sieve-of-eratosthenes-is-nloglogn/) that `O(1/2 + 1/3 + 1/5 + ... + 1/p) = O(loglogn)`.
 so as a result, we will have `O( n/2 + n/3 + ... + n/p) = n * O(n /2 + n/3 + ... + n/p) = O(n * loglogn) `
 
 2. In the article, the calculated overall time complexity is `O(sqrt(n) * loglogn) ` , which is wrong.
 what the algorithm does is crossing out `n/p` numbers for each prime `p` less than `sqrt(n)` . the running time of this algorithm is proportional to the number of cross-out operations. so as explained in part 1, the overall time complexity will be `O( n/ 2 + n/ 3 + ... + n/p) = n * O(1/2 + 1/3  + ... + 1/p)`.  and since `p` is less than `sqrt(n)` the answer will be ` n * O(loglog(sqrt(n) )  = n * O(n*loglogn) = O(n*loglogn)` . 
 

#### Code in the article

```
class Solution:
    def countPrimes(self, n: int) -> int:
        if n <= 2:
            return 0
        
        numbers = {}
        for p in range(2, int(sqrt(n)) + 1):
            if p not in numbers:
                for multiple in range(p*p, n, p):
                    numbers[multiple] = 1
        
        # Exclude "1" and the number "n" itself.
        return n - len(numbers) - 2
```

#### Language used for code

python3

**Comment by lc-kay** [comment]
Hi @Nil0ofar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
