### ISSUE TITLE
Incorrect Code Rejection - 655. Print Binary Tree

### ISSUE THREAD

**Issue by mcmar** [LeetCode-Feedback/LeetCode-Feedback#3468]
#### Your LeetCode username
mcmar

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
My code was incorrectly rejected. The question statement says that root node's value should be placed in the center and the left and right should be placed in the left-bottom part and right-bottom part respectively. My code meets these requirements and I would argue is *more* correct than the expected result that the judge produces. The judge's output is too wide and in fact its subtree does not match the output that it produces if the same subtree is given as a root.

This is the input for the test case:
```
[3,1,5,0,2,4,6,null,null,null,3]
```

This is the output the judge expects:
```
[["","","","","","","","3","","","","","","",""],
 ["","","","1","","","","","","","","5","","",""],
 ["","0","","","","2","","","","4","","","","6",""],
 ["","","","","","","3","","","","","","","",""]]
```
And this is my output:
```
[["","","","","","","","3","","","","","","",""],
 ["","","","1","","","","","","","","5","","",""],
 ["","0","","","","2","","","","","4","","6","",""],
 ["","","","","","","3","","","","","","","",""]]
```

The judge's incorrect output contains an extra space between the 5 (root) and 4 (left) and likewise an extra space between the 5 (root) and 6 (right).

The correct output for that subtree should be:
```
[["","5",""],
 ["4","","6"]]
```
That is what my code produces.

The judge's incorrect output for that subtree is:
```
[["","","5","",""],
 ["4","","","","6"]]
```
Which is wider than a properly printed subtree should be. Notice the extra spaces between 4 and 5 and between 5 and 6.

This is further proven by the output that the judge produces if this subtree is instead given as a root node.
For the following test case input:
```
[5,4,6]
```
This is the output for both the judge and for my code:
```
[["","5",""],["4","","6"]]
```
That subtree is that EXACT output for my code, however it is not the output for the judge, demonstrating that the judge's output is incorrect for the above test case.

#### Code you used for Submit/Run operation
```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def printTree(self, root: TreeNode) -> List[List[str]]:
        if not root:
            return [[]]
        if not root.left and not root.right:
            return [[str(root.val)]]
        left = self.printTree(root.left)
        right = self.printTree(root.right)
        self.padWidth(left, right)
        self.padDepth(left, right)
        return self.combineTree(root.val, left, right)
    
    def combineTree(self, val, left, right):
        m, n = len(left), len(left[0])
        out = []
        out.append([''] * n + [str(val)] + [''] * n)
        for i in range(m):
            out.append(left[i] + [''] + right[i])
        return out
        
    def padWidth(self, left: List[List[str]], right: List[List[str]]):
        print('begin padWidth', left, right)
        ln, rn = len(left[0]), len(right[0])
        if ln < rn:
            for row in left:
                if not ln:
                    row[0:0] = [''] * (rn - ln)
                else:
                    row[ln:ln] = [''] * ((rn - ln) // 2)
                    row[0:0] = [''] * ((rn - ln) // 2)
        elif rn < ln:
            for row in right:
                if not rn:
                    row[0:0] = [''] * (ln - rn)
                else:
                    row[rn:rn] = [''] * ((ln - rn) // 2)
                    row[0:0] = [''] * ((ln - rn) // 2)
        print('end padWidth', left, right)

    def padDepth(self, left: List[List[str]], right: List[List[str]]):
        print('begin padDepth', left, right)
        lm, ln, rm, rn = len(left), len(left[0]), len(right), len(right[0])
        if lm < rm:
            left[lm:lm] = [[''] * ln] * (rm - lm)
        elif rm < lm:
            right[rm:rm] = [[''] * rn] * (lm - rm)
        print('end padDepth', left, right)
```

#### Language used for code
python

#### Expected behavior
Result should be accepted.

**Comment by lc-kay** [comment]
Hi @mcmar 
Thank you for reaching out to us. The expected output is correct. For further questions, please refer to the problem discuss section to reference other's solutions and explanations.

**Comment by mcmar** [comment]
@lc-kay You are wrong. My output is 100% correct and you have provided no explanation of why the expected output is correct. You should be ashamed of treating paying customers like this.

**Comment by mcmar** [comment]
@lc-kay If you really believe that the expected output is correct, then you should be capable of providing an explanation for why that's the case. If you're unable to provide an explanation, then you're just closing this issue because you're too lazy to actually fix the issue. Shame on you.

**Comment by mcmar** [comment]
@lc-kay I provided a lengthy in-depth explanation of why the expected output is incorrect. I provided examples of the output that you get when providing that subtree as the root node. You didn't provide any explanation or examples, which just proves that this is really about you being lazy. Too lazy to fix broken code for your customers

**Comment by lc-kay** [comment]
@mcmar Our team has reviewed the problem description and understands that further clarifications are needed. They have updated the problem description to be more explicit in how the matrix should be formatted. We hope this clarifies your doubts as to why your solution is incorrect. Thank you for your time.

**Comment by mcmar** [comment]
@lc-kay All you've done is rewrite the problem definition to retroactively make my code incorrect. Talk about moving the goalposts. The solution I gave prints a beautiful binary tree with densely packed nodes. That's the correct way to draw a binary tree. In fact, this is the exact way that Leetcode prints binary trees in the tree visualizer!!!
Look at this image. It shows a tree printed in a dense format. The nodes on each level are not evenly spaced like they are according to your new problem definition.
<img width="340" alt="Screen Shot 2021-05-26 at 12 15 36 PM" src="https://user-images.githubusercontent.com/8251430/119718308-3e637800-be1c-11eb-8e77-ff593c9c2986.png">

**Comment by mcmar** [comment]
@lc-kay Instead of rewriting the problem definition, why don't you just fix the judge to accept properly printed densely packed binary trees?

**Comment by lc-kay** [comment]
@mcmar The current version of the statement is well-defined. The judge is correct and matches the description. We don't intend to change it soon. The visualizer has nothing to do with the problem, it is just a tool to help you instead of manually drawing the input trees for debugging.
The solution provided is wrong. It was wrong before updating the statement and it is still wrong after updating it. The discussion forum is the best place to discuss with different LeetCode users why it is wrong.
Thank you for your time and we appreciate your feedback.

**Comment by mcmar** [comment]
@lc-kay WOW! That's incredibly rude and arrogant. Is this how Leetcode responds to bugs? I used to recommend Leetcode to everyone, friends and strangers on Reddit and Blind. Now every time I see Leetcode mentioned, I'll tell them that problems are broken and Leetcode employees are rude and arrogant when you report a bug. Congrats on turning a loyal paying customer into an enemy. I hope you lose a lot more.

**Comment by mcmar** [comment]
@lc-kay I also want to reiterate that you changed the problem definition RETROACTIVELY to make my code invalid. My code did in fact meet the original definition of the problem statement at the time that I wrote it. You still haven't provided any possible justification for what my initial code did not meet the original problem statement. On top of that, you're condescending to me and telling me that my solution is wrong when in fact it clearly was not wrong according to the original problem statement. You're not only wrong, but condescending and arrogant too.
