### ISSUE TITLE
[ Feature Request ]  A section where we can see contest history .

### ISSUE THREAD

**Issue by aSquare14** [LeetCode-Feedback/LeetCode-Feedback#347]
A section where I can see the questions that were there in the past contests that we attend and history of contests would be really helpful.

**Comment by CooperCooperCooper** [comment]
Hi @aSquare14 ,
Thank you for reaching out to us! I've filed this feature request for our team to consider. 

In the future, please file feature requests to our main support channel support@leetcode.com, because this channel is reserved for content issues. We appreciate your support.
