### ISSUE TITLE
Incorrect Description: 204. Count Primes

### ISSUE THREAD

**Issue by shwetakarwa** [LeetCode-Feedback/LeetCode-Feedback#3472]
#### Your LeetCode username

smkarwa

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hint 8 says the time complexity of the problem is O(n log log n) while actually (as mentioned in solution too) it is O(sqrt(n) log log n).

#### Code you used for Submit/Run operation

```
```

**Comment by lc-kay** [comment]
@shwetakarwa The hint is correct. [Sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes#Computational_analysis) According to Wikipedia, Sieve is O(n log(log(n))). Our solution team has been notified of the same and will revise it as soon as we can. Thank you for your time.

**Comment by shwetakarwa** [comment]
In that case, there is an error in the solution description. In either case, can I get the leetcoins associated with the mission "File Content Issue to Feedback Repo"? Thank you!

**Comment by lc-kay** [comment]
@shwetakarwa The solution error has been reported #3461, and we only reward the first user that raised the valid report. Thank you for your understanding.
