### ISSUE TITLE
Missing testcase - 1499. Max Value of Equation

### ISSUE THREAD

**Issue by ovis96** [LeetCode-Feedback/LeetCode-Feedback#3473]
**Your LeetCode username**
ovis96

**Category of the bug**

- [ ]  Question
- [ ]  Solution
- [ ]  Language
- [x]  Missing Test Cases

**Description of the bug**

An accepted solution gets Wrong Answer on the following testcase:
[[1,100],[2,99],[3,101], [500, 500]]
498

**Code you used for Submit/Run operation**
```
class Solution(object):
    def findMaxValueOfEquation(self, points, k):
        left, right = 0, 1
        max_value = float('-inf')

        while right < len(points):
            xl, yl = points[left]
            xr, yr = points[right]

            diff = abs(xr - xl)
            if left == right:
                right += 1
            elif diff <= k:
                m = yl + yr + diff
                max_value = max(max_value, m)
                if yl >= yr - diff:
                    right += 1
                else:
                    left += 1
            else:
                left += 1
            print(left, right)
        return max_value

```
**Language used for code**
Python

**Expected behavior**
Output: 1097
Expected: 1098

**Comment by lc-kay** [comment]
Hi @ovis96 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
