### ISSUE TITLE
Missing Test Case - 1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit

### ISSUE THREAD

**Issue by jdrobins2000** [LeetCode-Feedback/LeetCode-Feedback#3475]
#### Your LeetCode username
jdrobins2000

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Please add the following test case:
[1,5,5,5,6,6]
4

Due to this missing case, the fastest performing submissions (which are incorrect) are far faster than any correct solution. 

#### Code you used for Submit/Run operation

One accepted submission which should fail and be rejected is: 
```
class Solution {
    public int longestSubarray(int[] nums, int limit) {
        int left = 0;
        int right = 0;
        int max = Integer.MIN_VALUE;
        int min = Integer.MAX_VALUE;
        int res = 0;
        while (right < nums.length && left <= right) {
            min = Math.min(min, nums[right]);
            max = Math.max(max, nums[right]);
            
            if (max - min <= limit) {
                res = Math.max(res, right - left + 1);
                right++;
            } else {
                if (res - 1 > nums.length - right) break;
                int back = right;
                int preMax = max = nums[right];
                int preMin = min = nums[right];
                while (max - min <= limit) {
                    preMax = max;
                    preMin = min;
                    min = Math.min(min, nums[back]);
                    max = Math.max(max, nums[back]);
                    back--;
                }
                left = back + 2;
                max = preMax;
                min = preMin;
            }
        }
        return res;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Submissions which cannot pass this test case should be rejected. Currently, the fastest accepted submissions are incorrect, and are faster precisely because they do not handle this case and therefore exit prematurely. This gives the false impression that correct solutions are less optimal than they truly are.

#### Additional context
The verification program already correctly computes the correct answer when you click Run with that test case, so only the addition of a test case is required.

**Comment by lc-kay** [comment]
Hi @jdrobins2000 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
