### ISSUE TITLE
1423. Maximum Points You Can Obtain from Cards Incorrect description

### ISSUE THREAD

**Issue by arahatashun** [LeetCode-Feedback/LeetCode-Feedback#3476]
#### Your LeetCode username
readonly_true

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

1423. Maximum Points You Can Obtain from Cards

There is a missing period.

There are several cards arranged in a row, and each card has an associated number of points The points are given in the integer array cardPoints.

#### Expected behavior

There are several cards arranged in a row, and each card has an associated number of points. The points are given in the integer array cardPoints.

**Comment by lc-kay** [comment]
Hi @arahatashun 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @arahatashun 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
