### ISSUE TITLE
你好这个代码为什么不能过

### ISSUE THREAD

**Issue by vihoc** [LeetCode-Feedback/LeetCode-Feedback#3478]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
wenhaoch(英文区,
**Bug 类型**
- [ ] 题目
- [X] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
经过我的对比,我的代码输出与expected一样只是输出顺序不同

**你使用的语言**
C++

**你提交或者运行的代码**
```
//The Dining Philosophers
constexpr int maxphilosopher = 5;
class DiningPhilosophers {
	public:
		DiningPhilosophers():lock_list(5) {
		
		}

		void wantsToEat(int philosopher,
			function<void()> pickLeftFork,
			function<void()> pickRightFork,
			function<void()> eat,
			function<void()> putLeftFork,
			function<void()> putRightFork)
		{
			int lefthand = philosopher;
			int righthand = (philosopher + 1) % maxphilosopher;
			std::try_lock(lock_list[lefthand], lock_list[righthand]);
			pickRightFork();
			pickLeftFork();
			eat();
			putLeftFork();
			lock_list[lefthand].unlock();
			putRightFork();
			lock_list[righthand].unlock();
		}
	private:
		std::vector<std::mutex> lock_list;	
	};
```

**期望行为**
应该是ac地吧

**屏幕截图**
无

**额外的上下文**

无

**Comment by feiceh** [comment]
你好，当前测试了一下代码是 AC 的，没有复现你说的问题，方便的话可以提供截图。
建议在后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by vihoc** [comment]
![error](https://user-images.githubusercontent.com/81898120/117944645-12d28f00-b340-11eb-8823-4d125a850f88.jpg)
你好,我这边runcode是这个结果,就没commit了

**Comment by feiceh** [comment]
好的，看截图原来是美国区提交的，这个是代码有问题。
try_clock 用法有问题， 可以参考这个 http://www.cplusplus.com/reference/mutex/try_lock/。

**Comment by vihoc** [comment]
不好意思,是我用错了,谢谢.
