### ISSUE TITLE
Terrible Problem Statement - 224. Basic Calculator

### ISSUE THREAD

**Issue by mcmar** [LeetCode-Feedback/LeetCode-Feedback#3479]
#### Your LeetCode username
mcmar

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem statement is so bad as to be nearly useless. It's missing lots and lots of incredibly important information that during a real interview you could ask your interviewer, but on a website there's no way to do that.

Key missing information:
1. Strings of numbers can be multiple digits long. The problem statement strongly implies that numbers in the input string are limited to 1 digit in length. All the examples given follow that pattern and the constraints say "s consists of digits", which would seem to imply that unless stated otherwise, each number is 1 digit in length. I created an entire solution that worked perfectly well for single digit numbers and then had to rewrite the entire thing when I encountered multi-digit numbers.
2. Numbers can have a negative sign. Examples of negative numbers don't appear anywhere in the examples and aren't implied by anything elsewhere. I again created a solution that worked perfectly well *except* for negative numbers. This is absolutely OUTRAGEOUS because I already had to rewrite my solution once due to the inaccurate problem statement.
3. Numbers can also have a preceding positive sign. That wasn't stated or implied anywhere in the problem statement or in the examples. This one is extremely counterintuitive because we rarely write actual arithmetic problems that way. If this one isn't clearly stated or at least given as an example, there will be approximately 0 English speakers who can correctly guess this.

#### Code you used for Submit/Run operation
```
import operator
ops = {
    '+': operator.add,
    '-': operator.sub,
}
class Solution:
    def calculate(self, s: str) -> int:
        stack = []
        for c in s:
            if c == ' ':
                pass
            elif c == '(':
                stack.append(c)
            elif c in ops:
                self.processStack(stack)
                stack.append(c)
            elif c == ')':
                self.processStack(stack)
                num = stack.pop()
                stack.pop()
                stack.append(num)
                self.processStack(stack)
            elif stack and stack[-1].isnumeric():
                stack.append(stack.pop()+c)
            else:
                stack.append(c)
        self.processStack(stack)
        return stack[-1]
    def processStack(self, stack):
        if len(stack) >= 3 and stack[-1].isnumeric() and stack[-2] in ops and stack[-3].isnumeric():
            rnum = stack.pop()
            op = stack.pop()
            lnum = stack.pop()
            stack.append(str(ops[op](int(lnum), int(rnum))))
```

#### Language used for code
python

#### Expected behavior
Problem statement should mention edge cases that need to be accounted for. It's unfair to the users to expect them to guess edge cases. In a real interview, this wouldn't be an issue, but on a website, bad problem statements waste hours of your users time.

#### Additional context
For additional context, I'm paying $35/month to practice algorithm problems. I don't want to waste my time on really bad problem statements.

**Comment by lc-kay** [comment]
Hi @mcmar 
Thank you for reaching out to us and we apologize for this experience. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mcmar 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
