### ISSUE TITLE
Image is broken

### ISSUE THREAD

**Issue by wilmerkrisp** [LeetCode-Feedback/LeetCode-Feedback#348]
**What kind of the bug**
- [ ] problem
 

**Describe the bug**
On the page
  https://leetcode.com/articles/contains-duplicate-iii/#
In the section
  Approach #3 (Buckets) [Accepted]
Illustration is broken and doesnot show
https://leetcode.com/media/original_images/220_Buckets.png
 

**Expected behavior**
without this image I can't understand the explanation of the algorithm

**Comment by CooperCooperCooper** [comment]
Hi @wilmerkrisp ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @wilmerkrisp ,
Thank you for your time. We've used your feedback to fix the image and it should be available now. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
