### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by umangagarwal11** [LeetCode-Feedback/LeetCode-Feedback#3480]
#### Your LeetCode username

agarwalumang012

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 1] Missing Test Cases 

#### Description of the bug

A test case of this sort is missing - [1,10,2,3,4,5,6,7,8,9]

#### Code you used for Submit/Run operation

```
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        
        left = 0
        right = len(nums) -1
        nums.append(float("-inf"))
        
        while left <= right:
            mid = (left + right) // 2
            if nums[mid] < nums[mid+1]:
                left = mid + 1
            else:
                right = mid - 1
        
        return left
```

#### Language used for code

Python

#### Expected behavior

The above code fails for the following test case:
[1,10,2,3,4,5,6,7,8,9]
However when I submit the code to leetcode to check, it accepts it as a successful solution.

**Comment by lc-kay** [comment]
<img width="1216" alt="Screen Shot 2021-05-12 at 10 52 48 AM" src="https://user-images.githubusercontent.com/70870126/118021539-32ea5a00-b310-11eb-9460-5c3a2609f264.png">
@umangagarwal11 Your code does not fail on this test case. For a valid test case contribution, please provide an accepted test case that the test case will cause to fail. Thank you for your time.
