### ISSUE TITLE
Python Solution Has Extra Code - 41. First Missing Positive

### ISSUE THREAD

**Issue by mcmar** [LeetCode-Feedback/LeetCode-Feedback#3481]
#### Your LeetCode username
mcmar

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The given solution has an extra edge case it checks that isn't actually an edge case and the code isn't needed.
This is the extra bit of code:
```
# nums = [1]
if n == 1:
    return 2
```
If you take the solution and comment out those lines, it still works fine when input is `[1]`

#### Code you used for Submit/Run operation
```
class Solution:
    def firstMissingPositive(self, nums: List[int]) -> int:
        n = len(nums)
        if 1 not in nums:
            return 1
        
        # if n == 1:
        #     return 2
        
        for i in range(n):
            if nums[i] <= 0 or nums[i] > n:
                nums[i] = 1
        
        for i in range(n):
            val = abs(nums[i])
            
            nums[val % n] = - abs(nums[val % n])
        
        # return first missing num in [1, n]
        for i in range(1, n+1):
            if nums[i % n] > 0:
                return i
        # return n + 1 if none are missing
        return n + 1
```

#### Language used for code
python

#### Expected behavior
Extra edge case isn't in code

**Comment by lc-kay** [comment]
Hi @mcmar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mcmar 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
