### ISSUE TITLE
Incorrect complexity article shared in Count Primes official soln

### ISSUE THREAD

**Issue by karkes** [LeetCode-Feedback/LeetCode-Feedback#3483]
I've left a comment below the article explaining why the complexity analysis is wrong. Please find them attached here:

"IMHO it's misleading to say that just using sqrt(n) in outer loop is more optimized because in the inside loop you start marking from p.p where p is prime from outside loop.
say your outer loop is like this:
for (int p = 2; p <= n; ++p)
and inner loop is:
for (int j = p.p; j < n; j += p)
when p > sqrt(n) in outer loop the p.p < n will fail in inner loop and you exit with just comparisons i.e. O(1)

This is why the time complexity remains unchanged if you use sqrt(n) in outer loop if your inner loop starts from p.p."

"Even if you apply optimized sieve approach by running the outer loop sqrt(n) times, in order to mark boolean array your total work will be:
n/2 in first run + n/3 in second+ ... + n/p in say last run where prime was found(p <= sqrt(n)).

Running outer loop sqrt times doesn't mean you don't mark all composites out since that would give incorrect result so by that logic you can say complexity will be -> n*loglog(n)"

**Comment by karkes** [comment]
[https://leetcode.com/problems/count-primes/solution/]

link for easy access.

**Comment by lc-kay** [comment]
Hi @karkes 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
