### ISSUE TITLE
525. Contiguous Array - Solution - Approach 3 - Diagram Update

### ISSUE THREAD

**Issue by RipanHalder** [LeetCode-Feedback/LeetCode-Feedback#3484]
#### Your LeetCode username

RipanHalder

#### Category of the bug
- [ ] Question
- [x] Solution - Drawing/Figure issues
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The animation in the Approach 3 does not consider the initial map.put(0,-1) which creates a confusion when we read and understand through the animation. For the example in the animation it works fine, but different test cases needs (0,-1) to be put initially in the map even before reading through the nums array as the solution depicts that.

#### Code you used for Submit/Run operation

NA

#### Language used for code

NA

#### Expected behavior

The animation in Approach #3 Using HashMap [Accepted] : must include map in step 0 with value (0,-1), whereas it is missing from it.

#### Screenshots

NA

#### Additional context

NA

**Comment by lc-kay** [comment]
Hi @RipanHalder 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@RipanHalder 
Thank you for your time. We will use your feedback to update the solution as soon as we can. We appreciate your support!
