### ISSUE TITLE
Missing Test Case - 304. Range Sum Query 2D - Immutable

### ISSUE THREAD

**Issue by rfpermen** [LeetCode-Feedback/LeetCode-Feedback#3485]
#### Your LeetCode username

rfpermen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [v] Missing Test Cases 

#### Description of the bug

It seems there is no testcase that can give you overflow if you using int instead of long long for calculating 2D prefix sum.
2D prefix sum using int, can get overflow when the given matrix is 200x200 and the value of each cell is 10^5, so the total is 4*10^9 which is 
bigger than int can handle.

Well you can argue that the function only return int as the result so the array to compute 2D prefix sum using int would be suffice. But that wasn't the case because you still can give matrix 200x200 where the value of each cell is 10^5, but the query is [100,100,199,199] so the return value is still int, but to calculate it you need to use long long.

#### Code you used for Submit/Run operation

```
long long x[505][505];
class NumMatrix {
public:
    NumMatrix(vector<vector<int>>& y) {
        int n = y.size(), m = y[0].size();
        for(int i = 1; i<=n; ++i){
            for(int j = 1; j<=m; ++j){
                x[i][j] = y[i-1][j-1] + x[i-1][j] + x[i][j-1] - x[i-1][j-1];
            }
        }
    }
    
    int sumRegion(int row1, int col1, int row2, int col2) {
        return x[row2+1][col2+1] - x[row2+1][col1] - x[row1][col2+1] + x[row1][col1];
    }
};
```

#### Language used for code

C++

#### Expected behavior

Getting Wrong Answer because of overflow

#### Additional context

The code I attached here already use long long to calculate the 2D prefix sum, but originally I use int and got accepted with it.

**Comment by lc-kay** [comment]
@rfpermen For a valid test case contribution, please provide the exact test case that will cause the accepted code to fail. Thank you.

**Comment by rfpermen** [comment]
[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6468311/input.txt)
Here's the test case, but it seems that the jury solution is also getting overflow so it counted as invalid test case when I tried it. But if you test it with input checker then my test case is within the given constraints on the problem.

**Comment by lc-kay** [comment]
@rfpermen  The test case is rejected because the answer cannot be represented as int and adding mod will break all the existing solutions. Thank you for your understanding.

**Comment by rfpermen** [comment]
The answer still can be represented as int as long as you are making sure
that the rectangle size of the query isn't too big, such as 100x100 or
200x100 etc. So instead of have to mod the result, you can add the
constraint that said the result of every query is fit in 32-bit signed
integer.
