### ISSUE TITLE
Missing Test Case - 1089. Duplicate Zeros

### ISSUE THREAD

**Issue by VladimirMilatovic** [LeetCode-Feedback/LeetCode-Feedback#3486]
#### - [ ] Bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
int[] temp = new int[arr.Length];
            int tempposition = 0;
            for (int i = 0; i < tempposition + 1; i++)
            {
                if (arr[i] != 0)
                {
                    temp[tempposition] = arr[i];
                }
                else
                {
                    temp[tempposition] = arr[i];
                    tempposition++;
                    if (tempposition >= temp.Length)
                    { break; }
                    temp[tempposition] = 0;
                }
                tempposition++;
                if (tempposition >= temp.Length)
                { break; }
            }
            //temp.CopyTo(arr, 0);
            arr = temp;
    }
};
```

#### Expected behavior

This solution should be accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/35456257/117960289-228cac00-b31d-11eb-814c-fd78695c0bd8.png)

**Comment by lc-kay** [comment]
@VladimirMilatovic Please provide the submission details link. Thank you.

**Comment by VladimirMilatovic** [comment]
https://leetcode.com/submissions/detail/492300774/?from=explore&item_id=3245

**Comment by lc-kay** [comment]
@VladimirMilatovic Your solution was not accepted because it fails on one or more test cases. Please refer to the problem discuss section to raise your question or refer to others' solutions. https://leetcode.com/problems/duplicate-zeros/discuss/?currentPage=1&orderBy=hot&query=
