### ISSUE TITLE
Missing Test Case - 304. Range Sum Query 2D - Immutable

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#3487]
#### Your LeetCode username

archit91

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case - 

[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6466027/input.txt)

#### Code you used for Submit/Run operation

```
class NumMatrix {
    vector<vector<int> > presum;
public:    
    NumMatrix(vector<vector<int>>& matrix) : presum(matrix) {
        for(auto& row : presum) 
            for(int i = 1; i < size(row); i++) 
                row[i] += row[i - 1];                
    }    
    
    int sumRegion(int row1, int col1, int row2, int col2) {
        int sum = 0;
        for(int i = row1; i <= row2; i++) 
            sum += presum[i][col2] - (col1 ? presum[i][col1 - 1] : 0);
        return sum;
    }
};

/**
 * Your NumMatrix object will be instantiated and called as such:
 * NumMatrix* obj = new NumMatrix(matrix);
 * int param_1 = obj->sumRegion(row1,col1,row2,col2);
 */

```

#### Language used for code

C++

#### Expected behavior

The solution should not be accepted since it fails on the given test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/40712852/117973044-84630b00-b349-11eb-94e3-9f9c4797859e.png)

#### Additional context

As per the given constraints, all the elements of the matrix can have valule 100000 and there can be total of 40000 such elements which may result in overflow if we use 32 bit signed integer types. Either it should be stated in the description that sum of all elements will always fit into 32-bit integer types or the above mentioned test case must be added

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@archit11111 The test case is rejected because the answer cannot be represented as int and adding mod will break all the existing solutions. Thank you for your understanding.

**Comment by archit11111** [comment]
@lc-kay  We can modify the queries so that the answer will fit into `int` but the precomputation won't. This would be valid as per the current constraints for the question.

If all the test cases are such that even the precomputation fits into `int`, you can add another statement to the constraint as follows - 
* The sum of all elements in `matrix` is guaranteed to fit within the range of a 32-bit signed integer
