### ISSUE TITLE
304. Range Sum Query 2D - Immutable

### ISSUE THREAD

**Issue by sgupta-dev** [LeetCode-Feedback/LeetCode-Feedback#3488]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Solution is accepted even i am submitting brute force approach. Which will loop two times through row and column.

#### Code you used for Submit/Run operation

```
class NumMatrix {
    
    int[][] mat;
    
    public NumMatrix(int[][] matrix) {
        int m = matrix.length;
        int n = matrix[0].length;
        mat = new int[m][n];
        
        for(int i = 0; i < m; i++)
        {
            for(int j = 0; j < n; j++)
            {
                mat[i][j] = matrix[i][j];
            }
        }
    }
    
    public int sumRegion(int row1, int col1, int row2, int col2) {
        int sum = 0;
        for(int i = row1; i <= row2; i++)
        {
            for(int j = col1; j <=col2; j++)
            {
                sum += mat[i][j];
            }
        }
        return sum;
    }
}

```

#### Expected behavior

Ideally it should give TLE

**Comment by lc-kay** [comment]
Hi @sgupta-dev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sgupta-dev 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
