### ISSUE TITLE
Missing Test Case - 1354. Construct Target Array With Multiple Sums

### ISSUE THREAD

**Issue by gyrao72** [LeetCode-Feedback/LeetCode-Feedback#3489]
#### Your LeetCode username
gyrao72

#### Category of the bug
- [ ] Missing Test Cases 
[1,1,4]

#### Description of the bug
Test case  [1,1,4] is not included

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    bool isPossible(vector<int>& target) {
        long long int sum=0;
        int n=target.size();
        priority_queue<int> maxHeap;
        
        for(int i:target){
            sum+=i;
            maxHeap.push(i);
        }
        
        while(maxHeap.top()!=1){
            int large=maxHeap.top();
            maxHeap.pop();
            
            sum-=large;
            if(large<=sum || sum<1) return false;
            large %=sum;
            sum += large;
            maxHeap.push((large)?large:sum);
        }
        
        return true;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
Expected:false

**Comment by lc-kay** [comment]
@gyrao72 For a valid test case contribution, please submit a test case that will fail an accepted solution. Since the test case you provided is accepted, we will not be adding it. Thank you for your time. 
![Uploading Screen Shot 2021-05-12 at 11.04.06 AM.png…]()
