### ISSUE TITLE
Missing Test Case - 720. Longest Word in Dictionary

### ISSUE THREAD

**Issue by Dhruval10** [LeetCode-Feedback/LeetCode-Feedback#3490]
#### Your LeetCode username
dakshal33

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For the following test case, the code should return "". My code was returning Null and still, it got accepted.

As the problem says, we need to return the longest word from the given list. Since, the following test case doesn't have basic building block "w" in the list, it should return an empty string.

#### Test case needed to be added

["wo","wor","worl","world"]

#### Expected output
"" or an empty string

#### Code you used for Submit/Run operation

```
/// Longest Word in Dictionary
class Solution:
    def longestWord(self, words: List[str]) -> str:
        
        def isContain(word, dict1):
            temp_str = ''
            for i in range(len(word)):
                temp_str += word[i]
                if temp_str in dict1:
                    pass
                else:
                    return False
            return True
        
        dict1 = dict()
        for word in words:
            dict1[word] = 1
        
        words.sort()
        words.sort(key=lambda x:-len(x))
        
        for word in words:
            if isContain(word,dict1):
                return word
```

#### Language used for code
Python3

#### Expected behavior
Expected to be a wrong answer but after submitting it accepted the submission

#### Additional context
Add this test case for 720. Longest Word in Dictionary

**Comment by lc-kay** [comment]
Hi @Dhruval10 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Dhruval10 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
