### ISSUE TITLE
Missing Test Case - 120. Triangle

### ISSUE THREAD

**Issue by kpartal1** [LeetCode-Feedback/LeetCode-Feedback#3491]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

####

```
object Solution {
  var sum = 0
  def minimumTotal(triangle: List[List[Int]]): Int = {
    if(!triangle.isEmpty) {
      sum += triangle(0).min
      minimumTotal(triangle.drop(1))
    }
    sum
  }
}
```

**Comment by lc-kay** [comment]
Hi @kpartal1 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
