### ISSUE TITLE
Variable Names Incorrect in Problem Description

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3492]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [950. Reveal Cards In Increasing Order](https://leetcode.com/problems/reveal-cards-in-increasing-order) and [1063. Number of Valid Subarrays](https://leetcode.com/problems/number-of-valid-subarrays), the variable names in problem description are inconsistent with the variable names in code.
In problem 950, the variable name in code is `deck`, but the variable name in problem description is `A` (please check the **Note** part).
In problem 1063, the variable name in code is `nums`, but the variable name in problem description is `A`.
The variable names in problem description should be changed so that they are consistent with the variable names in code.

#### Expected behavior
In both problems 950 and 1063, the variable names in problem description should be changed.
In problem 950, the variable name in problem description should be changed to `deck`.
In problem 1063, the variable name in problem description should be changed to `nums`.

**Comment by lc-kay** [comment]
@stormsunshine Our team is working on this for all our problems and is making a good process. I've relayed your feedback to them as well. However, it will take some time to update all the problems. Thank you for understanding.
