### ISSUE TITLE
Missing Test Case - 1269. Number of Ways to Stay in the Same Place After Some Steps

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3493]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets Runtime Error on the following testcase:
1
1

#### Code you used for Submit/Run operation

```
class Solution {
public:
    static constexpr int MOD = 1e9+7;
    int numWays(int steps, int arrLen) {
        int len = min(steps, arrLen-1)+1;
        vector<int> dp(len, 0);
        dp[0] = 1;
        for(int step = 1; step <= steps; step++) {
            vector<int> dp_nxt(len);
            dp_nxt[0] = (0LL + dp[0] + dp[1]) % MOD;
            for(int idx = 1; idx < len-1 && dp_nxt[idx-1]; idx++)
                dp_nxt[idx] = (0LL + dp[idx-1] + dp[idx] + dp[idx+1]) % MOD;
            dp_nxt[len-1] = (0LL + dp[len-2] + dp[len-1]) % MOD;
            dp = move(dp_nxt);
        }
        return dp[0];
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets Runtime Error.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
