### ISSUE TITLE
Missing Constraint - 518. Coin Change 2

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3496]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [518. Coin Change 2](https://leetcode.com/problems/coin-change-2), the problem description mentions that the given array `coins` represents coins of different denominations. However, this is not enough. The fact that `coins` contains distinct values is not mentioned in **Constraints** part, and when running the code, the test cases are not checked to guarantee that `coins` must contain distinct values. If a custom test case with duplicate elements in `coins` is used, the standard program will simply output an answer as if all elements in `coins` are distinct (please refer to the following screenshot).
One example test case is as follows.
```
5
[1,2,2,5]
```
The standard program outputs `7`.

#### Code you used for Submit/Run operation

```
class Solution {
    public int change(int amount, int[] coins) {
        int[] dp = new int[amount + 1];
        dp[0] = 1;
        for (int coin : coins) {
            for (int i = coin; i <= amount; i++) {
                dp[i] += dp[i - coin];
            }
        }
        return dp[amount];
    }
}
```

#### Language used for code
Java

#### Expected behavior
The following two points should be updated.
1. In **Constraints** part, one point should be added like the following.
   - All the elements of `coins` are unique.
2. When running the code with an invalid test case that contains duplicate elements in `coins`, the standard program should return a message indicating that `coins` must contain duplicate elements, instead of outputing an answer.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/118135354-81454900-b435-11eb-8caa-4472cc702792.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
