### ISSUE TITLE
1269.停在原地的方案树 题解&测试用例 优化建议

### ISSUE THREAD

**Issue by mstocs** [LeetCode-Feedback/LeetCode-Feedback#3498]
**你的 LeetCode 用户名**
康远

**Bug 类型**
- [ ] 题目 1269.停在原地的方案树

**描述**
该题目要求结果对于10000007取模，那么结果自然应该是最终结果对于10000007取模后返回，
该题目采用动态规划，状态转移方程右侧需要三项累加，而题解和测试用例中的做法是
1.前两项相加后取模
2.使用取模后的值累加第三项
这种解法是有问题的，会导致测试用例（27，7）返回错误结果

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    final int MODULO = 1000000007;
    //dp[i][j]代表i次行动，最后位置在j-1的次数
    //状态转移方程： dp[i][j] = dp[i-1][j] + dp[i-1][j-1] + dp[i-1][j+1]
    //i范围到steps，j范围到min(steps, arrLen)
    public int numWays(int steps, int arrLen) {
        int longestPosition = Math.min(arrLen, steps + 1);
        //j=0为哨兵，默认为0，j=longestPosition=1的值也是0，是尾部哨兵
        int[][] dp = new int[steps+1][longestPosition+2];
        dp[0][1] = 1;
        for(int i = 1; i <= steps; i++) {
            for(int j = 1; j<=longestPosition; j++) {
                //应该采用下述公式
                dp[i][j] = (dp[i-1][j] + dp[i-1][j-1] + dp[i-1][j+1]) % MODULO;
                //然而这么做无法通过测试用例（27，7）
                // 无奈改成下述公式才可以通过测试用例
                // dp[i][j] = (((dp[i-1][j] + dp[i-1][j-1]) % MODULO) + dp[i-1][j+1]) % MODULO;
            }
        }
        return dp[steps][1] % MODULO ;
    }
}
```

**期望行为**
期望移除越界的测试用例，或者让该题目不存在溢出情况，否则正确写法会被判定为错误

**屏幕截图**
![image](https://user-images.githubusercontent.com/32958995/118151306-10f2f380-b446-11eb-9f14-6d20b6c1aad2.png)

**额外的上下文**
添加额外的上下文信息

**Comment by zerotrac** [comment]
我看了一下官方题解，没有看到 `dp[i-1][j] + dp[i-1][j-1] + dp[i-1][j+1]` 三项加在一起的地方。
你看的是哪一份题解？

**Comment by anhpp123** [comment]
所以为什么不直接用long long/i64呢

**Comment by anhpp123** [comment]
> 所以为什么不直接用long long/i64/long呢

等等 而且为什么是方案**树**

**Comment by stormsunshine** [comment]
题解和测试用例的做法是正确的。在不考虑数据类型的范围的情况下，每次加法后取模和计算全部加法后取模一次的结果是相同的。在具体代码实现中，为了避免溢出，就需要每次加法后取模。
题解中的做法不会导致该测试用例返回错误结果，只有楼主的代码才会导致该测试用例返回错误结果。
什么是正确的写法？为什么楼主认为题解的写法是错误的？楼主又凭什么认为自己的写法是正确的？三个数相加然后取模就是错误的写法，因为三个数相加就可能超过32位有符号整型的最大值，导致溢出，所以必须两个数相加之后就取模，这才是正确的写法。
至于楼主说「丑陋」和「影响心情」，纯粹是借口。不想这样写，用 `long` 就行了。
