### ISSUE TITLE
Example 4 Output Format Issue (Problem 816. Ambiguous Coordinates)

### ISSUE THREAD

**Issue by lucliu20** [LeetCode-Feedback/LeetCode-Feedback#3499]
#### Your LeetCode username
lucliu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Example 4 Output Format Issue (Problem 816. Ambiguous Coordinates)
Example 4:
Input: s = "(100)"
Output: [(10, 0)] <== Output: ["(10, 0)"], it's missing the double quotes.
Explanation: 
1.0 is not allowed.

Thanks.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @lucliu20 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @lucliu20 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
