### ISSUE TITLE
407 接雨水 II 测试用例不符合题目要求

### ISSUE THREAD

**Issue by hairman123** [LeetCode-Feedback/LeetCode-Feedback#35]
**Bug 类型**
- [√] 题目
- [ ] 题解
- [ ] 编程语言

**题目描述**
**题目：407 接雨水 II**
给定一个 m x n 的矩阵，其中的值均为 **正整数** ，代表二维高度图每个单元的高度，请计算图中形状最多能接多少体积的雨水。
m 和 n 都是小于110的整数。每一个单位的高度都 **大于 0** 且小于 20000。

### BUG:
描述中说所有值为 **正整数**。但是提交代码后出现了 **包含 0 的测试用例**。
[[9,9,9,9,9,9,8,9,9,9,9],[9,0,0,0,0,0,1,0,0,0,9],[9,0,0,0,0,0,0,0,0,0,9],[9,0,0,0,0,0,0,0,0,0,9],[9,9,9,9,9,9,9,9,9,9,9]]

截图上传不了，可以看一下题目 407 是否有上述测试用例。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
很抱歉暂时无法重现「截图上传不了」这个情况，为了更精准快速的定位，还请尽可能详细地描述问题，“无法上传截图“具体是有什么现象呢？最好是换个浏览器添加一下截图哦。

**Comment by hairman123** [comment]
【截图上传不了】是指的 GITHUB 上传不了截图，我没有办法在 issue 里添加截图。
即使没有截图，**下面的信息可以帮助准确定位问题**：
1. 题号 407 接雨水II 题目要求 测试用例中的数字 都是 **大于0** 的
2. 我提交了代码 发现其中有一个测试用例为 [[9,9,9,9,9,9,8,9,9,9,9],[9,0,0,0,0,0,1,0,0,0,9],[9,0,0,0,0,0,0,0,0,0,9],[9,0,0,0,0,0,0,0,0,0,9],[9,9,9,9,9,9,9,9,9,9,9]] **包含 0**
3. 请查看一下 
1）**题目 407 是否要求测试用例里面的值都是 大于0 的**
2）**题目 407 是否有判题用例 [[9,9,9,9,9,9,8,9,9,9,9],[9,0,0,0,0,0,1,0,0,0,9],[9,0,0,0,0,0,0,0,0,0,9],[9,0,0,0,0,0,0,0,0,0,9],[9,9,9,9,9,9,9,9,9,9,9]]**
如果有，则说明 **测试用例与题意不符**，需要修改或移除测试用例。

**Comment by hairman123** [comment]
在题目 407 下面提交下面的代码，可以发现在测试用例 [[9,9,9,9,9,9,8,9,9,9,9],[9,0,0,0,0,0,1,0,0,0,9],[9,0,0,0,0,0,0,0,0,0,9],[9,0,0,0,0,0,0,0,0,0,9],[9,9,9,9,9,9,9,9,9,9,9]] 上出错。
但该 测试用例 **包含 0**， 不符合题目要求，题目要求所有值都 大于 0。
```c++
class Solution {
    struct Node
    {
        int h, x, y;
        Node(int h, int x, int y) : h(h), x(x), y(y) {}
        bool operator> (const Node& r) const { return h > r.h; }
    };
public:
    int trapRainWater(vector<vector<int>>& h) {
        if(h.size() == 0) return 0;

        // 大水漫灌模式
        int m = h.size(), n = h[0].size();
        priority_queue<Node, vector<Node>, greater<Node>> q;
        for(int i = 0; i < m; ++i)
            q.push(Node(h[i][0], i, 0)), q.push(Node(h[i][n-1], i, n - 1));
        for(int j = 0; j < n; ++j)
            q.push(Node(h[0][j], 0, j)), q.push(Node(h[m-1][j], m - 1, j));
        
        // BFS
        int xgo[4] = {-1, 1, 0, 0}, ygo[4] = {0, 0, -1, 1}, res = 0, prem = 0;
        while(q.size())
        {
            Node cur = q.top(); q.pop();
            if(!h[cur.x][cur.y]) continue;
            h[cur.x][cur.y] = 0;
            prem = max(prem, cur.h);
            res += prem - cur.h;
            for(int d = 0; d < 4; ++d)
            {
                int x = cur.x + xgo[d], y = cur.y + ygo[d];
                if(x >= 0 && x < m && y >= 0 && y < n && h[x][y])
                    q.push(Node(h[x][y], x, y));
            }
        }

        return res;
    }
};
```

**Comment by feiceh** [comment]
收到了感谢反馈，上面就是说需要详细地描述问题，把信息提供完整才能有助于快速验证和精准的定位哟～

**Comment by feiceh** [comment]
非常感谢您的反馈，该问题已于第一时间进行了修复，力扣会定期更新，保障稳定和体验优化。
