### ISSUE TITLE
Please add new testcase

### ISSUE THREAD

**Issue by vikrantpc** [LeetCode-Feedback/LeetCode-Feedback#350]
Please add below testcase to below problem
https://leetcode.com/problems/check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence/

"b bu bur burg burger"
"burg"

I'm suggesting this because my solution without using inbuild String method got accepted however this test case was failing.

**Comment by CooperCooperCooper** [comment]
Hi @vikrantpc ,
Thank you for reaching out to us. To help us access this test case, can you please share your code and its language here with us?

**Comment by vikrantpc** [comment]
> Hi @vikrantpc ,
> Thank you for reaching out to us. To help us access this test case, can you please share your code and its language here with us?

This is the link to the code -
https://leetcode.com/submissions/detail/345627489/

Test case that failed/missing-
"b bu bur burg burger"
"burg"

Language: Java

**Comment by vikrantpc** [comment]
class Solution {
    public int isPrefixOfWord(String sentence, String searchWord) {
        boolean search = true;
        for (int i=0, j =0, wordCount = 1; i<sentence.length(); i++) {
            if (search) {
                if (searchWord.charAt(j) == sentence.charAt(i)) {
                    if (++j==searchWord.length()) return wordCount;
                } else search = false;
            }
            else if (sentence.charAt(i)==' ') {
                search = true;
                j=0;
                wordCount++;
            }
        }
        return -1;
    }
}

**Comment by CooperCooperCooper** [comment]
Hi @vikrantpc ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @vikrantpc ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
