### ISSUE TITLE
Missing Test Cases- 1684. Accepting submissions of both O(n) and O(n^2) 

### ISSUE THREAD

**Issue by SamirPaul1** [LeetCode-Feedback/LeetCode-Feedback#3500]
# 1684. Count the Number of Consistent Strings Missing Test Case

#### Category of the bug
- [ ] Missing Test Cases 

#### In the Question 1684. Count the Number of Consistent Strings LeetCode is accepting both O(n) and O( n²) submissions.
But it should accept only the optimised value

#### Code you used for Submit/Run operation

```
# solution of O( n²) time complexity
class Solution:
    def countConsistentStrings(self, allowed: str, words: List[str]) -> int:
        P = 0
        for i in range(len(words)):
            words[i] = set(words[i])
            words[i] = list(words[i])
            s = 0
            for j in range(len(words[i])):
                if words[i][j] in allowed:
                    s +=1
            if s == len(words[i]):
                P +=1
                
        return P
                
```
```
# solution of O( n ) time complexity


class Solution:
    def countConsistentStrings(self, allowed: str, words: List[str]) -> int:
        count = 0
        for s in words:
            s = s.lstrip(allowed)
            if not s:
                count += 1
        return count


                
```

#### Screenshots
<p align=center>                           
<img src="https://raw.githubusercontent.com/SamirPaul1/java-a-course-for-beginners/master/02-IntroductionToMethods-MultiplicationTable/_____.png"  />
</p>

**Comment by lc-kay** [comment]
@SamirPaul1 Any solutions are accepted if it passes all the test case and runs within the time limit. Thank you for your time.

**Comment by SamirPaul1** [comment]
Thanks for your reply.
