### ISSUE TITLE
A cleaner version of standard solution for 299. Bulls and Cows

### ISSUE THREAD

**Issue by mmalu** [LeetCode-Feedback/LeetCode-Feedback#3501]
#### Your LeetCode username

manky

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A cleaner and shorter version of the standard solution.

#### Code you used for Submit/Run operation

```
class Solution {
    public String getHint(String secret, String guess) {
        int bulls = 0, cows = 0;
        int[] digits = new int[10];
        
        for (int i = 0; i < secret.length(); i++) {
            int s = secret.charAt(i) - '0', g = guess.charAt(i) - '0';
            if (s == g) {
                bulls++;
            } else {
                if (digits[s] < 0) cows++;
                if (digits[g] > 0) cows++;
                digits[s]++;
                digits[g]--;
            }
        }     
        
        return new StringBuilder()
            .append(bulls)
            .append("A")
            .append(cows)
            .append("B")
            .toString();
    }
}
```

#### Language used for code

Java

#### Additional context

https://leetcode.com/problems/bulls-and-cows/

**Comment by lc-kay** [comment]
Hi @mmalu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate. However, it may take some time our the team to review the code and update it, so I will close this ticket and reach out if further information is needed.
