### ISSUE TITLE
Clarify solution - 22. Generate Parentheses

### ISSUE THREAD

**Issue by romnempire** [LeetCode-Feedback/LeetCode-Feedback#3503]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Approach 3: Closure Number description is ambiguous:  The sentence "Clearly, every parentheses sequence has a unique closure number." can be interpreted to mean that every parentheses sequence has a unique closure number across the set of all valid parentheses sequences (rather than across the set of all integers) which is clearly wrong, and I was stuck trying to understand what was meant for a few minutes.  I propose "Clearly, every parentheses sequence has one and only one closure number." to disambiguate.

**Comment by lc-kay** [comment]
Hi @romnempire 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
