### ISSUE TITLE
[864. Shortest Path to Get All Keys] confusing test case

### ISSUE THREAD

**Issue by glorialearnscoding** [LeetCode-Feedback/LeetCode-Feedback#3504]
#### Your LeetCode username

glorialearncoding

#### Category of the bug
- [ ] Question

#### Description of the bug

testcase:
["@...a",".###A","b.BCc"]
Expected: 10

I couldn't understand why it is 10 even assuming revisiting the position is allowed.

First I put it into a matrix:
```
 @  .  .  .  a
 .  #  #  #  A
 b  .  B  C  c
```

starting from @, we can either go downwards, or go to the right.

so 4 steps to go from '@' to 'B'. Next step can not be 'C' since we haven't acquired the key 'c'.
```
 @
 |
 \/
 .
 |
 \/
 b -> .  -> B
```

To continue with the other path, we have to go back to '@', that requires another 4 steps.

After getting back to '@' where we started, we can next go to the right side:
```
@ -> . -> . -> . -> a
                    |
                    \/
                    A
                    |
                    \/
                    c
```
so that's 6 steps from '@' to 'c'.

In total, that would be 4 + 4 + 6 = 14.

So could did you get 10?

**Comment by lc-kay** [comment]
@glorialearnscoding Please check out the follow discuss posts for better understanding. 
- https://leetcode.com/problems/shortest-path-to-get-all-keys/discuss/146998/Need-help-with-the-test-case 
- https://leetcode.com/problems/shortest-path-to-get-all-keys/discuss/960694/%22%40...a%22%22.A%22%22b.BCc%22-wrrong-test-case
- https://leetcode.com/problems/shortest-path-to-get-all-keys/discuss/331790/Why-this-test-case-result-as-10-please-help

Thank you for your time.

**Comment by glorialearnscoding** [comment]
Oh thank you for your help. Understand the case now.
