### ISSUE TITLE
Modify Solution Condition for Problem 31 (Next Permutation) and Python Solution

### ISSUE THREAD

**Issue by choidongyeon** [LeetCode-Feedback/LeetCode-Feedback#3505]
#### Your LeetCode username
dchoi93

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

This is perhaps a nit, but one of the while conditions in the solution is inconsistent with the solution explanation. In lines 9 - 11, we have:
```
while (j >= 0 && nums[j] <= nums[i]) {
      j--;
}
```
But since `j` should always be the right of `i`, we should have this instead:
```
while (j > i && nums[j] <= nums[i]) {
      j--;
}
```
Logically speaking, the change doesn't make a difference because we're looking for the right-most position where `nums[j] > nums[i]` but there's no harm in being more specific :)

#### Code you used for Submit/Run operation

Additionally, the solution is available for Java but not for any other languages. Here is my Python solution:

```
class Solution(object):
    def nextPermutation(self, nums):
        """
        :type nums: List[int]
        :rtype: None Do not return anything, modify nums in-place instead.
        """
        i = len(nums) - 2
        while not (i < 0 or nums[i] < nums[i + 1]):
            i -= 1
        
        if i > -1:
            j = len(nums) - 1
            while not (j < i or nums[i] < nums[j]):
                j -= 1
            nums[i], nums[j] = nums[j], nums[i]
        self.reverse(nums, i + 1)
        
    def reverse(self, nums, start):
        left = start
        right = len(nums) - 1
        while left < right:
            # swap left and right
            nums[left], nums[right] = nums[right], nums[left]
            left += 1
            right -= 1
```

#### Additional context

https://leetcode.com/problems/next-permutation/

**Comment by lc-kay** [comment]
Hi @choidongyeon 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @choidongyeon 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
