### ISSUE TITLE
what if there are duplicate words Missing Test Case - 392. Is Subsequence

### ISSUE THREAD

**Issue by lightspeedsnail** [LeetCode-Feedback/LeetCode-Feedback#3507]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

s = "abbc"
t = "abbgdc"

this should return true 
but it returns false so i cant see condition where it states that duplicates are not allowed so. if the condition is not mentioned pls mention it.

**Comment by lc-kay** [comment]
Hi @lightspeedsnail 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@lightspeedsnail The expected output for s = "abbc" t = "abbgdc" is true. Please refer to the problem discuss section for further questions. Thank you.
