### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by tungnguyenvan** [LeetCode-Feedback/LeetCode-Feedback#3508]
#### Your LeetCode username
tungnguyenvan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
At Example 3, I think answer is "pwke" with the length of 4

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
A substring must be a **continuous** subsequence of the original string. Therefore, for example 3, "pwke" is a subsequence but not a substring. The correct output is 3 for example 3.

**Comment by lc-kay** [comment]
@tungnguyenvan Please refer to @stormsunshine explanation. Thank you both for your time.
