### ISSUE TITLE
572. Subtree of Another Tree

### ISSUE THREAD

**Issue by Holmes555** [LeetCode-Feedback/LeetCode-Feedback#3509]
#### Your LeetCode username
Holmes555

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Wrong image of root tree in Example 2: ```root = [3,4,5,1,2,null,null,0]```, '0' Node should be left of the '1' Node.

#### Screenshots
![image](https://user-images.githubusercontent.com/26043009/118279712-1f87ec00-b4d4-11eb-9b9a-1a252dcfa50f.png)

**Comment by lc-kay** [comment]
Hi @Holmes555 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Holmes555 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
