### ISSUE TITLE
Number of LIS

### ISSUE THREAD

**Issue by AmanKumarMehra** [LeetCode-Feedback/LeetCode-Feedback#3511]
Input:
[1,2,4,3,5,4,7,2]
Output:
2
Expected:
3

longest increasing subsequence is 1, 2, 3, 5, 7 
and its length is 5. No other LIS exist of length 5.
Hence, number of LIS is 1.

**Comment by lc-kay** [comment]
@AmanKumarMehra Please provide the problem number and title for this issue. Thank you.

**Comment by AmanKumarMehra** [comment]
Problem number - 673, Number of longest increasing subsequence

**Comment by lc-kay** [comment]
@AmanKumarMehra Please check out the following discuss posts for a better understanding. 

https://leetcode.com/problems/number-of-longest-increasing-subsequence/discuss/107316/Why-12435472-expects-output-of-3
https://leetcode.com/problems/number-of-longest-increasing-subsequence/discuss/417650/Am-I-missing-anything-can-you-guys-help-with-this-input-12435472

Thank you for your time.
