### ISSUE TITLE
Missing Test Case - 1379. Find a Corresponding Node of a Binary Tree in a Clone of That Tree

### ISSUE THREAD

**Issue by billy-mccann** [LeetCode-Feedback/LeetCode-Feedback#3512]
#### Your LeetCode username

hyperfine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Swift language is missing entirely from the problem. 

#### Code you used for Submit/Run operation

```

```

#### Language used for code

(Swift is not available)

**Comment by lc-kay** [comment]
@billy-mccann Although we support Swift on our platform, not all our problems include all the languages we support. However, I have relayed this feedback to our team. Thank you for your time.
