### ISSUE TITLE
Wrong std output - 842. Split Array into Fibonacci Sequence

### ISSUE THREAD

**Issue by yang052513** [LeetCode-Feedback/LeetCode-Feedback#3515]
#### Your LeetCode username

`kageyama_tobio`

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My function **passed all test cases** although the returned output was not right. Please see the attached image for reference.

#### Code you used for Submit/Run operation

```c++
// 842. Split Array into Fibonacci Sequence
class Solution {
public:
    vector<int> splitIntoFibonacci(string num) {
        vector<int> res;
        
        dfs(res, num, 0, 0, 0);
        return res;
    }
    
    bool dfs(vector<int>& res, string num, int index, int prev, long long sum) {
        if (index == num.size()) {
        // I accidentally wrote true here, and it should be 
        // return res.size() >= 3 
        // to check the if has at least 3 fib numbers
            return true;         
        }
        
        long long cur_num = 0;
        for (int i = index; i < num.size(); i++) {
            if (i > index && num[index] == '0') continue; 
            
            cur_num = cur_num*10 + (num[i]-'0');
            if (cur_num > INT_MAX) break;
            if (res.size() >= 2 && cur_num != (long long)res.back() + (long long)res[res.size()-2]) {
                continue;
            }
            
            res.push_back(cur_num);
            if (dfs(res, num, i+1, cur_num, cur_num+prev)) return true;
            res.pop_back();
        }
        
        return false;
    }
};
```

#### Language used for code

**C++**

#### Expected behavior

As I commented on my code, I accidentally wrote the wrong termination condition for my DFS, I intend to check if the array has at least 3 fib numbers inside. 

For Example 1 Test case, it should return `[123,456,789]` but my code returns `[1,23456789]` which doesn't even satisfy the **at least 3 fib numbers in the sequence**. Same for Example 5, the code I posted above passed all the test cases, which should not.

#### Screenshots

<img src="https://firebasestorage.googleapis.com/v0/b/yangliweb.appspot.com/o/screenshot.png?alt=media&token=394d4a6c-d0f1-4253-a8b0-e0fdde765c9e" />

**Comment by lc-kay** [comment]
Hi @yang052513 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@yang052513 
Thank you for your time. It appears there was a bug in the matcher. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
