### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by niru2** [LeetCode-Feedback/LeetCode-Feedback#3516]
#### Your LeetCode username
muskan789

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
missing test cases [-1,-1]

#### Code you used for Submit/Run operation
```
[-1,-1]
```

#### Language used for code
C++

**Comment by lc-kay** [comment]
@niru2 Please provide the code that this test case will fail. After more information is provided, I will reopen this ticket. Thank you for your time.

**Comment by niru2** [comment]
when I submit below code it accepts it because it is not checking test case [-1,-1].

bool validate_bst(TreeNode* root, int min, int max) {
        if(root == NULL)
            return true;
        
        if(min != -1 && root->val <= min) {
            return false;
        }
        
        if(max != -1 && root->val >= max) {
            return false;
        }
        
        return validate_bst(root->left, min, root->val) && validate_bst(root->right, root->val, max);

    }
    
    bool isValidBST(TreeNode* root) {
        return validate_bst(root, -1, -1);
    }

**Comment by lc-kay** [comment]
Hi @niru2 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @niru2 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
