### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by AJAYKR00KJ** [LeetCode-Feedback/LeetCode-Feedback#3517]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test cases are missing
The following code was accepted successfully, but for the test case
"-902E+3"
we got the output result "false" and the expected result is "true" which was not consistent.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isNumber(string s) {
         
        int l=s.size();
        int cnt=0,point=0,i=0,sign=0,af_dig=0,bf_dig=0,dig=0;
        char c='t';
        
        if(s[0]=='+' || s[0]=='-') i++;
        
        for(;i<l;i++)
        {
            if(isalpha(s[i])) {c=s[i],cnt++;}
            
            if(s[i]=='.') point++;
            
            if(cnt)
            {
               if(isdigit(s[i])) af_dig++; 
                
               if(s[i]=='.') return 0; 
            }
            else
            {
                if(isdigit(s[i])) bf_dig++; 
            }
            
            if(isdigit(s[i])) dig++; 
             
            
            if(s[i]=='+' || s[i]=='-')
            {
                sign++;
                if(i>0) //it can be at starting or just after e,E
                {
                    if(s[i-1]!='e') return 0;
                }
            }
            
        }
        
        
        
        if(cnt>1 || point>1 || sign>1 ||dig<1) return 0;
     
        if(cnt==1 && (c!='e' && c!='E')) return 0;
        
        if(cnt>0)
        {
            if(af_dig<1 ||bf_dig<1) return 0;
        } 
        
        
        
        return 1;
         
    }
};
```

#### Language used for code
C++

#### Expected behavior

Please add these type of test cases

"-902E+3"
"-9023E+3"

#### Screenshots

![Valid Number - LeetCode - Google Chrome 15-05-2021 16_07_24](https://user-images.githubusercontent.com/48375037/118357440-e31dc400-b597-11eb-966f-901fca9cca08.png)

#### Additional context

Add the test cases.

**Comment by lc-kay** [comment]
Hi @AJAYKR00KJ 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AJAYKR00KJ 
Thank you for your time. The team reviewed your report and noticed that the problem needed to be updated. After the update, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
