### ISSUE TITLE
Missing Test Case - 1078. Occurrences After Bigram

### ISSUE THREAD

**Issue by abrahma** [LeetCode-Feedback/LeetCode-Feedback#3518]
Missing testcase:
"we we we we will rock you"
"we"
"we"

#### LeetCode username
ankitabrahmachari

#### Category of the bug
-Missing Test Cases 

#### Description of the bug
There is no testcase mentioned when first and second are same strings

#### Code you used for Submit/Run operation

```
class Solution {
    public String[] findOcurrences(String text, String first, String second) {
        String words[] = text.split(" ");
        List<String> result = new ArrayList<String>();
        boolean sameStrings = first.equals(second);
        for(int i = 0; i < words.length - 2; i++){
            if(!sameStrings && words[i].equals(first) && words[i+1].equals(second)){
                result.add(words[i+2]);
                i++;
            }
        }
        return result.toArray(String[]::new);
    }
}
```

#### Language used for code
Java 

#### Expected behavior
This test case should have failed for the submitted code but it passes.

**Comment by lc-kay** [comment]
Hi @abrahma 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abrahma 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
