### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by ceciliaccwei** [LeetCode-Feedback/LeetCode-Feedback#3519]
#### Your LeetCode username

NoSegFault

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case "005047E+6".
The following code got accepted but failed on this test case.

#### Code you used for Submit/Run operation

```
// Valid Number
class Solution {
    public boolean isNumber(String s) {
        boolean point = false;
        boolean e = false;
        boolean num = false;
        for (int i = 0; i<s.length(); i++){
            char cur = s.charAt(i);
            if (Character.isDigit(cur)) num = true;
            else if (cur == '.'){
                if (e || point) return false;
                point = true;
            }
            else if (cur == 'e' || cur == 'E'){
                if (e || !num) return false;
                num = false;
                e = true;
            }
            else if (cur == '-' || cur == '+'){
                if (i > 0 && s.charAt(i-1) != 'e') return false;
            }
            else return false;
        }
        return num;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Expected true but got false. "005047E+6" should be a valid number.

#### Screenshots

![Screen Shot 2021-05-15 at 10 05 05 AM](https://user-images.githubusercontent.com/35175404/118364101-08450f00-b565-11eb-8d82-7fbbae698da9.png)

**Comment by lc-kay** [comment]
Hi @ceciliaccwei 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
