### ISSUE TITLE
Missing Test Case - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by tushar19892002** [LeetCode-Feedback/LeetCode-Feedback#3521]
https://leetcode.com/submissions/detail/493501715/

This should not be a accepted solution to this problem.

**Comment by lc-kay** [comment]
@tushar19892002 Please provide a more detailed explanation as to why it shouldn't be accepted. Thank you.

**Comment by lc-kay** [comment]
Hi @tushar19892002 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
