### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by ShivamPorwal02** [LeetCode-Feedback/LeetCode-Feedback#3522]
#### Your LeetCode username

ShivamPorwal

#### Category of the bug

Question : https://leetcode.com/problems/valid-number/
(Valid Number)

#### Description of the bug

Question is saying accepted but on one category of test case it isn't working. I have not used (toLowerCase) in my solution but still it is submitting the solution.

#### Code you used for Submit/Run operation

```
// Valid Number
class Solution {
    public boolean isNumber(String s) {
        if(s==null || s.trim().length()==0 ) {
            return false;
        }
        boolean numberSeen = false;
        boolean expoSeen = false;
        boolean dotSeen = false;
        
        s = s.trim();
        for(int i=0;i<s.length();i++){
            char c = s.charAt(i);
            
            switch(c){
                case '.':
                    if(dotSeen || expoSeen){
                        return false;
                    }
                    dotSeen = true;
                    break;
                    
                case 'E':
                case 'e':
                    if(expoSeen || !numberSeen){
                        return false;
                    }
                    expoSeen = true;
                    numberSeen = false;
                    break;
                case '+':
                case '-':
                    if(i!=0 && s.charAt(i-1)!='e'){
                        return false;
                    }
                    numberSeen = false;
                    break;
                default:
                    if(!isDigit(c)){
                        return false;
                    }
                    numberSeen = true;
            }
        }
        return numberSeen;
    }
    public static boolean isDigit(char c ){
        return (c>='0' && c<='9');
    }
}
```

#### Language used for code

Java

#### Expected behavior

It is returning false when i check by putting it in the custom test case but when I am submitting the all the test cases are passed.
The test case is "132E+1", where it is getting false

**Comment by lc-kay** [comment]
Hi @ShivamPorwal02 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@ShivamPorwal02 Thank you for your time. The team reviewed your report and noticed that the problem needed to be updated. After the update, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
