### ISSUE TITLE
Missing Test Case - 681. Next Closest Time

### ISSUE THREAD

**Issue by PradKalkar** [LeetCode-Feedback/LeetCode-Feedback#3523]
#### Your LeetCode username
Pradnesh123

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
I have a code and a corresponding test case that doesn't give the expected output and is still getting accepted.

#### Code you used for Submit/Run operation

```
class Solution {
public:
string nextClosestTime(string time) {
        string s(time.substr(0,2) + time.substr(3)); // only digits
        sort(s.begin(), s.end()); // make searching "easier"
        
        vector<int> indices =  {4,3,1,0};
        for (int i : indices) {
            auto it = upper_bound(s.begin(), s.end(), time[i]); // first digit larger than current
            if (it != s.end()) {
                time[i] = *it; // replace digit and check if the time is valid
                if (time.substr(0,2) <= "24" && 
                    time.substr(3) < "60") return time;
            }
            time[i] = *s.begin(); // if not found, take the smallest
        }
        
        return time;
    }
};
```

#### Language used for code
C++

#### Expected behavior
On the test case input "23:49", the expected outcome should be "22:22" but my code is producing "24:22" which is clearly wrong but my code is still getting accepted by the system.

#### Additional context
I request to add the test case "23:49" to the system.

**Comment by lc-kay** [comment]
Hi @PradKalkar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @PradKalkar 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
