### ISSUE TITLE
1862. Sum of Floored Pairs - missing test case

### ISSUE THREAD

**Issue by Ceay1** [LeetCode-Feedback/LeetCode-Feedback#3525]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

Lack of test scenarios

#### Code you used for Submit/Run operation

```
class Solution:
    def sumOfFlooredPairs(self, nums: List[int]) -> int:
        
        N = 1_000_000_007
        
        max_num=max(nums)
        incs=[0]*(max_num+1)
        
        for num in nums:
            for j in range(num, max_num+1, num):
                incs[j] += 1

        incs=list(accumulate(incs))
        return sum([incs[num] for num in nums]) % N
```

#### Expected behavior

The solution should not be accepted - gives TLE on test case [1]*99999 + [100000]. However, the solution was accepted.

#### Additional context

![Capture1](https://user-images.githubusercontent.com/8646635/118371833-62050380-b57c-11eb-917c-3f95e30131cd.PNG)

![Capture2](https://user-images.githubusercontent.com/8646635/118371885-911b7500-b57c-11eb-9c4e-5ee750257921.PNG)

**Comment by archit11111** [comment]
#3524  should solve this issue 😅

**Comment by Ceay1** [comment]
Agree with @archit11111 , the two test cases are almost identical, but #3524 was logged a bit earlier.

**Comment by lc-kay** [comment]
@Ceay1 Thank you for your feedback. I've relayed #3524 to our team to look into. Therefore, I will close this ticket.
