### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by g02dev** [LeetCode-Feedback/LeetCode-Feedback#3526]
#### Your LeetCode username

g02dev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Wrong solution is accepted due to missing test cases:
```
"nan"
"NaN"
"NAN"
"infinity"
"-infinity"
"+infinity"
"-INFINITY"
"+iNFinitY"
```

#### Code you used for Submit/Run operation

```python
class Solution:
    def isNumber(self, s):
        
        stop_words = ['inf', '-inf', '+inf', 'Infinity', '+Infinity', '-Infinity']
        if s in stop_words:
            return False
        
        try:
            float(s)
            return True
        except:
            return False
```

#### Language used for code

Python

**Comment by g02dev** [comment]
> The optional sign may be '+' or '-'
> Case is not significant, so, for example, “inf”, “Inf”, “INFINITY” and “iNfINity” are all acceptable spellings for positive infinity.
>
> (c) https://docs.python.org/3/library/functions.html#float 

More test cases:
```
"+nAN"
"-Nan"
```

**Comment by lc-kay** [comment]
Hi @g02dev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
