### ISSUE TITLE
65. Valid Number

### ISSUE THREAD

**Issue by jraman** [LeetCode-Feedback/LeetCode-Feedback#3528]
Problem 65: [Valid Number](https://leetcode.com/problems/valid-number/)

The definition seems to be incorrect.

Nowhere in the definition does it limit the valid characters to be only digits and not other letters.

"At least one digit" does not limit the string (or part of the string) to only digits.  For example, the string "2ee" has at least one  digit and hence would be valid under the current definition.

Suggested definition:  Change the phrase "at least one digit" to "one or more digits."

------
Modified definitions of decimal and integer:

A **decimal number** is composed of the following components (in order):
 1. (Optional) A sign character (either `'+'` or `'-'`).
 1. One of the following:
     1. One or more digits, followed by a dot `'.'`, or
     1. One or more digits, followed by a dot '.', followed by one or more digits, or
     1. A dot `'.'`, followed by one or more digits.

An **integer** is composed of the following components (in order):
 1. (Optional) A sign character (either '+' or '-').
 1. One or more digits.

**Comment by lc-kay** [comment]
Hi @jraman 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jraman 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
