### ISSUE TITLE
675. Cut Off Trees for Golf Event

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#353]
#### Your LeetCode username
habaj

**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Incorrect description in solution Approach 2

**Expected behavior**

It might be useful for solvers familiar with Dijkstra's Algorithm to know that A* Search is a special case of Dijkstra's with node.h = 0 always.

This is wrong and the opposite is true. Actually Dijkstra can be viewed as a special case of A* where h(x) = 0. Refer [here](https://en.wikipedia.org/wiki/A*_search_algorithm#Special_cases)

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us (and apologies for the lack of response). I've already relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
