### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by larrygao2000** [LeetCode-Feedback/LeetCode-Feedback#3531]
#### Your LeetCode username

larrygao2000

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X ] Missing Test Cases 

#### Description of the bug

Missing test cases with capital "E" followed by + or - sign.
e.g., "8.E+3"

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isNumber(String s) {
        s = s.trim();

        boolean pointSeen = false;
        boolean eSeen = false;
        boolean numberSeen = false;
        boolean numberAfterE = true;
        for(int i=0; i<s.length(); i++) {
            if('0' <= s.charAt(i) && s.charAt(i) <= '9') {
                numberSeen = true;
                numberAfterE = true;
            } else if(s.charAt(i) == '.') {
                if(eSeen || pointSeen) {
                    return false;
                }
                pointSeen = true;
            } else if(s.charAt(i) == 'e' || s.charAt(i) == 'E') {
                if(eSeen || !numberSeen) {
                    return false;
                }
                numberAfterE = false;
                eSeen = true;
            } else if(s.charAt(i) == '-' || s.charAt(i) == '+') {
                if(i != 0 && s.charAt(i-1) != 'e' && s.charAt(i) != 'E') {
                    return false;
                }
            } else {
                return false;
            }
        }

        return numberSeen && numberAfterE;
    }
}
```

#### Expected behavior

The above code is accepted as a solution but it will NOT pass the simple test case of "8.E+3"

#### Screenshots

Run Code Result:
Your input
"8.E+3"
Your answer
false
Expected answer
true

But it is accepted as a solution

**Comment by lc-kay** [comment]
Hi @larrygao2000 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@larrygao2000 Thank you for your time. The team reviewed your report and noticed that the problem needed to be updated. After the update, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
