### ISSUE TITLE
Missing Test Case - 1862. Sum of Floored Pairs

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3533]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1862_2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6488703/1862_2.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    const int base = 1000000007;
    int sumOfFlooredPairs(vector<int>& nums) {
        int n = nums.size();
        long long res = 0;
        sort(nums.begin(), nums.end());
        for (int i = 0; i < n; ++i) {
            int st = 0;
            while (st < n) {
                int div = nums[st] / nums[i];
                int tar = (div + 1) * nums[i];
                int ed = lower_bound(nums.begin() + st, nums.end(), tar) - nums.begin();
                res += (ed - st) * div;
                st = ed;
            }
        }
        return (int)(res % base);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
