### ISSUE TITLE
Missing Test Case - 968. Binary Tree Cameras

### ISSUE THREAD

**Issue by deepeshgodara** [LeetCode-Feedback/LeetCode-Feedback#3535]
https://leetcode.com/deepeshgodara/

#### Category of the bug
- [ ] Incorrect test case

#### Description of the bug

[0,0,null,null,0,0,null,null,0,0] for this input answer should be 3 instead of 2
for visulalizing the tree check the following tree
![image](https://user-images.githubusercontent.com/30095763/118389907-eec9c300-b649-11eb-8318-3bb932d47c44.png)
and for checking the output check the following image
![image](https://user-images.githubusercontent.com/30095763/118389961-233d7f00-b64a-11eb-9673-b321f267216d.png)

#### Code you used for Submit/Run operation

```
class Solution {
    int odd_level_nodes=0;
    int even_level_nodes =0;
    public int minCameraCover(TreeNode root) {
        even_level_nodes =0;
        odd_level_nodes=0;
        helper(root,0);
        int rv = min(odd_level_nodes,even_level_nodes);
        return rv==0?1:rv;
    }
    public void helper(TreeNode node,int level) {
        if(node==null){
            return;
        }
        if(level%2==0){
            even_level_nodes++;
        }else{
            odd_level_nodes++;
        }
        helper(node.left,level+1);
        helper(node.right,level+1);
    }
    public int min(int a, int b){
        return a<b?a:b;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior

for the provided test case output should be 3
and there are two way of placing the cameras
either place 1 camera in each  of the odd levels
or in the even levels

**Comment by maskalek** [comment]
No, it's not. You can put cameras here:
![image](https://user-images.githubusercontent.com/6655515/118390754-6c390780-b639-11eb-8b9f-30b84cdac37d.png)

**Comment by lc-kay** [comment]
@deepeshgodara The expected output is correct. Please check out the discuss section and refer to @maskalek explanation. Thank you for your time.
