### ISSUE TITLE
Missing Test Case - 1108. Defanging an IP Address

### ISSUE THREAD

**Issue by kartikmahendratiwari** [LeetCode-Feedback/LeetCode-Feedback#3536]
#### Your LeetCode username

 fybsccssem1

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
Solution

#### Description of the bug

It does'nt accepts a correct solution

#### Code you used for Submit/Run operation

```
import re

class Solution:
    def defangIPaddr(self, address: str) -> str:
        self.address=address
        re.sub("\.","[.]",address)
        return address
```

#### Language used for code

Python

#### Expected behavior

It Should give me a correct answer as it is and to prove my point i am attaching the python idle response to the code

#### Screenshots

![image](https://user-images.githubusercontent.com/76511000/118393921-2f800700-b65f-11eb-9155-1269891d0b8e.png)
![image](https://user-images.githubusercontent.com/76511000/118394067-1166d680-b660-11eb-8517-0fb3b9f38c23.png)

**Comment by lc-kay** [comment]
@kartikmahendratiwari Please check out this article for the environment of our programming languages https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-. From your screenshot, it appears that you are using Python 3.4.3. We currently support Python 3.9. Thank you for your time.
