### ISSUE TITLE
Missing Test Case - 56. Merge Intervals

### ISSUE THREAD

**Issue by kaushikramabhotla** [LeetCode-Feedback/LeetCode-Feedback#3537]
#### Category of the bug
- [ ] Question
- [*] Solution : I think the in the solution(Approach 2), the picture of the sort is wrong.
![Screenshot from 2021-05-16 16-28-49](https://user-images.githubusercontent.com/44550184/118394733-10d03f00-b664-11eb-931a-ddf292f47948.png)

- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I feel that sorting is wrong, so a beginner will definitely get confused there, so please try to change it. thank you :)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![Screenshot from 2021-05-16 16-28-49](https://user-images.githubusercontent.com/44550184/118394750-2fced100-b664-11eb-8c38-f889e840e66f.png)

**Comment by lc-kay** [comment]
@kaushikramabhotla Please provide more explanation as to why the sorting is wrong. Thank you.
