### ISSUE TITLE
Inconsistent Variable Names - 1085. Sum of Digits in the Minimum Number

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3538]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [1085. Sum of Digits in the Minimum Number](https://leetcode.com/problems/sum-of-digits-in-the-minimum-number), the variable names in problem description are inconsistent. The variable names `minDigitSum` and `S` should refer to the same thing. However, using different variable names here makes the problem description confusing.
Please refer to the following screenshot.

#### Expected behavior
The variable names `minDigitSum` and `S` should be the same. Either the variable names are both `minDigitSum`, or the variable names are both `S`.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/118398168-fad57500-b689-11eb-859e-c35ea7153283.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate. As it may take some time to update all our problem's variable names, I will close this ticket for now.
