### ISSUE TITLE
Missing Test Case - 698. Partition to K Equal Sum Subsets

### ISSUE THREAD

**Issue by shashank-shark** [LeetCode-Feedback/LeetCode-Feedback#3539]
#### Your LeetCode username
shashank-shark

#### Category of the bug
- [ ] Question - 698. Partition to K Equal Sum Subsets
- [ ] Solution - A test case where nums =  [1,1,1,1,2,2,2,2,2] and k = 2, here the frequency of 1's and 2's are 4, which is valid input
but when tried to run the test case by giving this test case as custom test input we get the error notification as "Invalid Testcase: The frequency of an integer should be less than 4".
- [ ] Language - Java

#### Description of the bug
 A test case where nums =  [1,1,1,1,2,2,2,2,2] and k = 2, here the frequency of 1's and 2's are 4, which is valid input
but when tried to run the test case by giving this test case as custom test input we get the error notification as "Invalid Testcase: The frequency of an integer should be less than 4".

**Comment by lc-kay** [comment]
@shashank-shark In the test case nums = [1,1,1,1,2,2,2,2,2] and k = 2, the frequency of 1's is 4. However, the frequency of 2's is 5. Therefore, it is an invalid test case. Thank you for your time.
