### ISSUE TITLE
493. Reverse Pairs

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#354]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Approach 3 - BIT has wrong pseudo code

**what language is your code written in**
C++

**Expected behavior**
```
update(BIT,index, val):
  while(index<0):
    BIT[index]+=val
    index-=(index&(-index))
```

The inequality sign is wrong. It should be >0. Here is the provided code for it.

```
void update(vector<int>& BIT, int index, int val)
{
    while (index > 0) {
        BIT[index] += val;
        index -= index & (-index);
    }
}
```

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the approach. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
