### ISSUE TITLE
Missing Test Case - 779. K-th Symbol in Grammar

### ISSUE THREAD

**Issue by karnurmax** [LeetCode-Feedback/LeetCode-Feedback#3541]
#### Category of the bug
- [x] syntax error

#### Description of the bug
(The values of k are 1-indexed.) (1 indexed).

#### Expected behavior
remove duplicated text ```(1 indexed)```

**Comment by lc-kay** [comment]
@karnurmax 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @karnurmax 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
