### ISSUE TITLE
Incorrect Test Case - 495. Teemo Attacking

### ISSUE THREAD

**Issue by nahimilega** [LeetCode-Feedback/LeetCode-Feedback#3542]
#### Your LeetCode username
archit18221

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
in problem 495. Teemo Attacking, problem constraints specify list size is greater than equal to 1, but a test case with an empty list is as a test case

#### Code you used for Submit/Run operation

```
    def findPoisonedDuration(self, timeSeries: List[int], duration: int) -> int:

        #if len(timeSeries) == 0:
        #    return 0
        final_duration  = duration
        for i in range(1,len(timeSeries)):
            old_time = timeSeries[i-1] + duration
            if old_time > timeSeries[i]:
                final_duration += duration - (old_time - timeSeries[i])
            else:
                final_duration += duration
        return final_duration
```

#### Language used for code
Python

#### Screenshots
![image](https://user-images.githubusercontent.com/42585035/118429253-e2e40c80-b6ee-11eb-82cb-1309257415f4.png)
![image](https://user-images.githubusercontent.com/42585035/118429283-f7c0a000-b6ee-11eb-8951-8c238f045fd0.png)

**Comment by lc-kay** [comment]
Hi @nahimilega 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @nahimilega 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
