### ISSUE TITLE
Missing Comparator function in Sorting - Longest String Chain

### ISSUE THREAD

**Issue by chinks-2310** [LeetCode-Feedback/LeetCode-Feedback#3543]
#### Category of the bug
- [ ] Solution

#### Description of the bug
With using comparator function for sorting it's showing me error

#### Code you used for Submit/Run operation

```
// Longest String Chain

class Solution {
public:
    bool myCmp(string a,string b)
    {
        return (a.size()<b.size());
    }
    int longestStrChain(vector<string>& words) {
        sort(words.begin(),words.end(),myCmp);
        unordered_map<string,int> mp;
        int ans=0;
        for(auto s:words){
            for(int i=0;i<s.size();i++)
            {
                mp[s]=max(mp[s],1+mp[s.substr(0,i)+s.substr(i+1)]);
            }
            ans=max(ans,mp[s]);
        }
        return ans;
    }
    
};
```

#### Expected behavior

It's showing me error

#### Screenshots

![image](https://user-images.githubusercontent.com/72862735/118458825-bf35bc00-b718-11eb-8d5e-c7b40461f41f.png)

**Comment by lc-kay** [comment]
@chinks-2310 Please provide the submission details link. Thank you.

**Comment by lc-kay** [comment]
Hi @chinks-2310 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
