### ISSUE TITLE
Wrong Problem Description - 1867. Orders With Maximum Quantity Above Average

### ISSUE THREAD

**Issue by mingyip** [LeetCode-Feedback/LeetCode-Feedback#3544]
#### Your LeetCode username

mingyip

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

## 1867. Orders With Maximum Quantity Above Average
In the problem description session, the test case example is wrongly written.

The Example shows:
```order_id=1: max(12, 10, 5) = 12```

Instead it should be
```order_id=1: max(12, 10, 15) = 15```

**Comment by lc-kay** [comment]
Hi @mingyip 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mingyip Our team has fixed this issue before reviewing your report. However, we still appreciate your time and support.
