### ISSUE TITLE
Missing Test Case - 852. Peak Index in a Mountain Array

### ISSUE THREAD

**Issue by DevanshKariya** [LeetCode-Feedback/LeetCode-Feedback#3545]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Let's call an array arr a mountain if the following properties hold:

arr.length >= 3
There exists some i with 0 < i < arr.length - 1 such that:
arr[0] < arr[1] < ... arr[i-1] < arr[i]
arr[i] > arr[i+1] > ... > arr[arr.length - 1]
Given an integer array arr that is guaranteed to be a mountain, return any i such that arr[0] < arr[1] < ... arr[i - 1] < arr[i] > arr[i + 1] > ... > arr[arr.length - 1].

#### Code you used for Submit/Run operation

class Solution(object):
    def peakIndexInMountainArray(self, A):
        
        lo , hi = 0 , len(A) - 1
        while lo < hi:
            mid = int((lo + hi) / 2)
            if A[mid] < A[mid - 1]:
                hi = mid - 1
                
            elif A[mid] < A[mid + 1]:
                lo = mid + 1
            else:
                return mid
        return lo

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@DevanshKariya Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
