### ISSUE TITLE
Incorrect Constraint - 327. Count of Range Sum

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3546]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [327. Count of Range Sum](https://leetcode.com/problems/count-of-range-sum), the first constraint is `1 <= nums.length <= 10^4`. However, when submitting the code, there exist test cases that have `nums` with length greater than 10000.
Please refer to the following code. I have restricted the length of `sum` to 10001 so that the indices are in the range [0, 10000]. However, when submitting the code, an `ArrayIndexOutOfBoundsException` is thrown, indicating that index 10001 is out of bounds for length 10001. Please refer to the following screenshot.
Obviously, in the test case that causes the exception, the length of `nums` is greater than 10000, which is not consistent with the first constraint. Therefore, the first constraint should be updated according to the actual test cases.

#### Code you used for Submit/Run operation
```
class Solution {
    public int countRangeSum(int[] nums, int lower, int upper) {
        long s = 0;
        long[] sum = new long[10001];
        for (int i = 0; i < nums.length; ++i) {
            s += nums[i];
            sum[i + 1] = s;
        }
        return countRangeSumRecursive(sum, lower, upper, 0, nums.length);
    }

    public int countRangeSumRecursive(long[] sum, int lower, int upper, int left, int right) {
        if (left == right) {
            return 0;
        } else {
            int mid = (left + right) / 2;
            int n1 = countRangeSumRecursive(sum, lower, upper, left, mid);
            int n2 = countRangeSumRecursive(sum, lower, upper, mid + 1, right);
            int ret = n1 + n2;

            int i = left;
            int l = mid + 1;
            int r = mid + 1;
            while (i <= mid) {
                while (l <= right && sum[l] - sum[i] < lower) {
                    l++;
                }
                while (r <= right && sum[r] - sum[i] <= upper) {
                    r++;
                }
                ret += r - l;
                i++;
            }

            long[] sorted = new long[right - left + 1];
            int p1 = left, p2 = mid + 1;
            int p = 0;
            while (p1 <= mid || p2 <= right) {
                if (p1 > mid) {
                    sorted[p++] = sum[p2++];
                } else if (p2 > right) {
                    sorted[p++] = sum[p1++];
                } else {
                    if (sum[p1] < sum[p2]) {
                        sorted[p++] = sum[p1++];
                    } else {
                        sorted[p++] = sum[p2++];
                    }
                }
            }
            for (int j = 0; j < sorted.length; j++) {
                sum[left + j] = sorted[j];
            }
            return ret;
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior
The **Constraints** part should be updated according to the actual test cases. The maximum length of `nums` is obviously greater than 10^4.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/118497801-fc6d6e80-b757-11eb-979f-209403f09bca.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
