### ISSUE TITLE
1048. Longest String Chain - Test case doesn't match the problem statement

### ISSUE THREAD

**Issue by vinupriyesh** [LeetCode-Feedback/LeetCode-Feedback#3547]
#### Your LeetCode username
vinupriyesh

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the problem statement of "Longest String Chain" definition of a predecessor is given as "word1 is a predecessor of word2 if and only if we can add exactly one letter anywhere in word1 to make it equal to word2".  That is, if we take a word (word1) and add a single character anywhere in the word, it should exactly match with the other word(word2) even if we consider its position.  This is verified in all the examples shown in the question.

Unfortunately, there is a test case that is considering ["abcd","dbqca"] as a valid predecessor.  One cannot add 'q' to "abcd" to get "dbqca", it cannot be called as equal.  The correct answer should be 0 for this testcase, however system finds the answer to be 1.   

A word is not a set.  Without an explicit mention, it cannot be understood.  And the solution will be completely different if the position of the letters is not important. 

#### Code you used for Submit/Run operation

```
// Longest String Chain
class Solution {
    
    class StringComparator implements Comparator<String> {
        @Override
        public int compare(String s1,String s2){
            if(s1.length() == s2.length()) {
                return 0;
            } else if(s1.length() > s2.length()) {
                return 1;
            } else {
                return -1;
            }
        }
    }
    
    HashMap<Integer, List<String>> lengthMap = new HashMap<>();
    HashMap<String, Integer> sizeMap = new HashMap<>();
    
    public int longestStrChain(String[] words) {
        Arrays.sort(words, new StringComparator());
        
        int maxSize = 0;
        
        for (String word:words) {
            // System.out.println("--"+word+"--");
            int len = word.length();
            addToLengthMap(len, word);
            
                        
            List<String> pWords = lengthMap.get(len-1);
            // System.out.println("Previous words found --> "+pWords);
            if(pWords != null) {
                for(int i =0;i<len;i++) {
                    String nWord = word.substring(0,i) + word.substring(i+1, len);
                    // System.out.println("NWord --> "+nWord);
                    for(String pWord:pWords) {
                        if(nWord.equals(pWord)) {                            
                            int sz = sizeMap.get(pWord);
                            int szn = sizeMap.get(nWord);
                            // System.out.println("old->"+sz+", new->"+szn+", word->"+nWord);
                            if(szn <= sz+1) {                                
                                sizeMap.put(word, sz+1);
                                if(sz+1 > maxSize) {
                                    // System.out.println("Size upd "+pWord+"~"+word+"="+(sz+1)+" | "+maxSize);
                                    maxSize = sz+1;
                                }
                            }
                        }
                    }
                }
            }
        }
        return maxSize;
    }
    private void addToLengthMap(int len, String word){
        List<String> pWords = lengthMap.get(len);
        if(pWords == null) {
            pWords = new ArrayList<>();
            lengthMap.put(len, pWords);
        }        
        pWords.add(word);                
        
        Integer sz = sizeMap.get(word); //Size from the current word as start
        if(sz == null) {
            sizeMap.put(word, 1);
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior
Either the test case ["abcd","dbqca"] and all similar test cases to be removed.  Or, the problem statement should mention this explicitly. 

#### Screenshots

I hope screenshot will not be required to explain this issue.

#### Additional context

This is a weekly challenge question 
https://leetcode.com/explore/challenge/card/may-leetcoding-challenge-2021/600/week-3-may-15th-may-21st/3746/

**Comment by lc-kay** [comment]
Hi @vinupriyesh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vinupriyesh 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
