### ISSUE TITLE
Invalid Test Case - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by pgreze** [LeetCode-Feedback/LeetCode-Feedback#3548]
#### Your LeetCode username

pgreze

#### Category of the bug

- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the [Intersection of Two Linked Lists](https://leetcode.com/explore/learn/card/linked-list/214/two-pointer-technique/1215/) problem, my solution is marked as "37 / 39 test cases passed." but one test case is wrong:

```
Input:
8
[4,1,8,4,5]
[5,6,1,8,4,5]
2
3
Output:
Intersected at '1'
Expected:
Intersected at '8'
```

But the intersection is 1 (both are including 1,8,4,5).

I assume it's related to skipA and skipB mentioned in the examples but not in the question, neither in its input...

#### Code you used for Submit/Run operation

```
class Solution:
    def getIntersectionNode(self, headA: ListNode, headB: ListNode) -> ListNode:
        if not headA or not headB: return None
        a, b, sizes = headA, headB, [0, 0]
        while a.next or b.next:
            if a.next:
                sizes[0] += 1
                a = a.next
            if b.next:
                sizes[1] += 1
                b = b.next
        if a.val != b.val:
            return None
        # Shift the largest to align sizes
        if sizes[0] > sizes[1]:
            largest, shortest = headA, headB
            shift = sizes[0] - sizes[1]
        else:
            largest, shortest = headB, headA
            shift = sizes[1] - sizes[0]
        while shift > 0:
            largest = largest.next
            shift -= 1
        # And iterate until finding the intersection
        while largest.val != shortest.val:
            largest = largest.next
            shortest = shortest.next
        return largest
```

#### Language used for code

Python

#### Expected behavior

See Description of the bug

**Comment by lc-kay** [comment]
@pgreze The expected output is correct. Please check out this discuss post for more information https://leetcode.com/problems/intersection-of-two-linked-lists/discuss/243841/Can-anyone-explain-example1
