### ISSUE TITLE
1432. Max Difference You Can Get From Changing an Integer

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#355]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Ambiguous and easy to misinterpret problem statement.

The question can be understood in 2 different ways. This might be the reason it is heavily disliked.

```
You are given an integer num. You will apply the following steps exactly two times:

Pick a digit x (0 <= x <= 9).
Pick another digit y (0 <= y <= 9). The digit y can be equal to x.
Replace all the occurrences of x in the decimal representation of num by y.
The new integer cannot have any leading zeros, also the new integer cannot be 0.

Let a and b be the results of applying the operations to num the first and second times, respectively.
Return the max difference between a and b.
```

Is the question saying a=convert(num) and b=convert(num) ?
Or is it saying a=convert(num) and b=convert(a)?

**Expected behavior**

The source of ambiguity is in the first line (exactly two times). If you take this in the wrong sense the second last line will only reinforce that misunderstanding (applying the operations to num the first and second times, respectively).

Let's get rid of terms like 'two', 'times', 'first', 'second'.

```
You are given an integer num. You can apply the following steps only once:
```

Now there is no wrong preconceived notion so let's make it explicit what we want in a better way.

```
Let a and b be two independent results after applying the operation to num.
```

The final problem statement:

```
You are given an integer num. You can apply the following steps only once:

Pick a digit x (0 <= x <= 9).
Pick another digit y (0 <= y <= 9). The digit y can be equal to x.
Replace all the occurrences of x in the decimal representation of num by y.
The new integer cannot have any leading zeros, also the new integer cannot be 0.

Let a and b be two independent results after applying the operation to num.
Return the max difference between a and b.
```

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. Upon reviewing this issue, we've decided to keep the current problem statement as is because it's complementing the problems' current test cases. We will keep your feedback on file as these problems are constantly revamped. Thank you again for your support.
