### ISSUE TITLE
Problem Description Inaccurate

### ISSUE THREAD

**Issue by tevanko** [LeetCode-Feedback/LeetCode-Feedback#3551]
#### Your LeetCode username

tevanko

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

88 Merge Sorted Array
Problem Description Misleading
The problem description states m is equal to the number of elements initialized in the nums1 array.  However, it is clear based on submissions that this should read "m is equal to the number of _non-zero_ elements initialized in nums1.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @tevanko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tevanko 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
