### ISSUE TITLE
Missing Test Case - 200. Number of Islands

### ISSUE THREAD

**Issue by jbromley** [LeetCode-Feedback/LeetCode-Feedback#3552]
#### Your LeetCode username
jbromley

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the Racket version of the Number of Islands question, the contract is incorrect for the values that are used to call the `num-islands` function. The contract is the following
```
(define/contract (num-islands grid)
  (-> (listof (listof char?)) exact-integer?)
...)
```
So the argument `grid` is supposed to be a list of lists of char. However, when the harness calls `num-island`, `grid` is a list of list of strings, causing the contract to fail.

Also in the project description, the lists are shown to contain "0" "1" "0", indicating strings. While later on, '0' '1' '0' is used, indicating chars in most languages.

#### Code you used for Submit/Run operation

```
(struct world (rows cols map) #:transparent)

(define (lists->map ls)
  (list->vector (map list->vector (for/list ([row ls]) (map string->label row)))))

(define (string->label label)
  (match label
    ["0" 'water]
    ["1" 'land]
    [else (error "invalid label")]))

(define (make-map list-map)
  (world (length list-map) (length (first list-map)) (lists->map list-map)))

(define (world-set! m r c val)
  (vector-set! (vector-ref (world-map m) r) c val))

(define (world-ref m r c)
  (cond
    [(or (< r 0) (>= r (world-rows m))) 'water]
    [(or (< c 0) (>= c (world-cols m))) 'water]
    [else (vector-ref (vector-ref (world-map m) r) c)]))

(define/contract (num-islands grid)
  (-> (listof (listof char?)) exact-integer?)
  (define m (make-map grid))
  (letrec ([visit (lambda (r c)
                    (world-set! m r c 'water)
                    (when (equal? (world-ref m (sub1 r) c) 'land)
                      (visit (sub1 r) c))
                    (when (equal? (world-ref  m (add1 r) c) 'land)
                      (visit (add1 r) c))
                    (when (equal? (world-ref m r (sub1 c)) 'land)
                      (visit r (sub1 c)))
                    (when (equal? (world-ref m r (add1 c)) 'land)
                      (visit r (add1 c))))])
    (for*/fold ([islands 0])
      ([r (in-range (world-rows m))]
       [c (in-range (world-cols m))]
       #:when (equal? (world-ref m r c) 'land))
      (visit r c)
      (add1 islands))))

```

#### Language used for code
Racket

#### Expected behavior
I expect the contract to be
```
  (-> (listof (listof string?)) exact-integer)
```
to match what the harness actually passes in. I also expect the problem description to consistently use "0" "1" (strings).

#### Screenshots
No screenshots taken.

**Comment by lc-kay** [comment]
Hi @jbromley 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jbromley Our team has fixed the issue. Please let us know if you are still encountering any problems. Thank you for your time.
