### ISSUE TITLE
本地执行正确，LEETCODE执行错误

### ISSUE THREAD

**Issue by jaimeyang** [LeetCode-Feedback/LeetCode-Feedback#3554]
**你的 LeetCode 用户名**
JAIME
题目1091
BUG类型 : 本地执行正确，LEETCODE执行错误。。。。，不知道怎么回事
测试用例: {{0,0,0},{0,0,0},{0,0,0}}
结果: 网页显示是4 ，本地执行确实是3
编程语言C++
代码如下：

#include <iostream>
#include <vector>
#include <queue>
#include <limits>
using namespace std;

//本地执行正确，LEETCODE执行错误。。。。，不知道怎么回事
class Solution {
private:
    class Node{
    public:
        Node(int dis,int x,int y):
        m_dis(dis),m_x(x),m_y(y) {

        }
        int getDis() { return this->m_dis; }

        int getX() { return this->m_x; }
        int getY() { return this->m_y; }

        bool operator < (const Node& right) { return m_dis > right.m_dis; }
    private:
        int m_dis;
        int m_x;
        int m_y;
    };

    int caculate(int x,int y,int x1,int y1) { return (x - x1) ^ 2 + (y - y1) ^ 2; }
    
    Node* createNode(int x,int y,int tx,int ty) {
        int dis = caculate(x,y,tx,ty);
        return new Node(dis,x,y);
    }

    void deleteNode(Node* n) {
        delete n;
        n = nullptr;
    }
public:
    //应该有几种解法
    // 1 BFS
    // 2 双向BFS
    // 3 动态规划
    // 4 A* 没用过A*,先尝试A*
    int shortestPathBinaryMatrix(vector<vector<int>>& grid) {
        int row = grid.size();
        int col = row == 0 ? 0 : grid[0].size();
        if (row == 0 || col == 0 || grid[0][0] == 1 || grid[row - 1][col - 1]) return -1;

        vector<vector<int>> visited(row,vector<int>(col,0));

        priority_queue<Node*,vector<Node*>> p_q;
        Node* root = createNode(0,0,row - 1,col - 1);
        p_q.push(root);
        //8个方向
        int dir_x[8] = {0,1,1,1,0,-1,-1,-1};
        int dir_y[8] = {1,1,0,-1,-1,-1,0,1};
        int level = 1;
        while (!p_q.empty()) {               
            level++;         
            cout<<"level is "<<level<<endl;
            int len = p_q.size();            
            cout<<"len is "<<len<<endl;
            for (int i = 0; i < len; i++) {
                cout<<"begin top"<<endl;
                Node* node = p_q.top();
                cout<<"end top"<<endl;
                p_q.pop();
                int x = node->getX();
                int y = node->getY();
                cout<<"x is "<<x<<endl;
                cout<<"y is "<<y<<endl;
                if (visited[x][y] == 1) continue;

                visited[x][y] = 1;
                
                int min_dis = std::numeric_limits<int>::min();            
                for (int j = 0; j < 8; j++) {
                    int next_x = x + dir_x[j];
                    int next_y = y + dir_y[j];
                    cout<<"j------:"<<j<<endl;
                    if (next_x < 0 || next_x > row - 1 || next_y < 0 || next_y > col - 1) continue;
                    
                    cout<<"next_x: "<<next_x;
                    cout<<"-----next_y: "<<next_y<<endl;
                    if (next_x == row - 1 && next_y == col - 1) return level;
                    
                    if (grid[next_x][next_y] == 1) continue;
                    auto n = createNode(next_x,next_y,row - 1,col -1);
                    p_q.push(n);
                }
                cout<<"end level for"<<endl;
            }
            
        }
        return -1;
    }
};

int main(int argc,char* argv[]) {
    
    vector<vector<int>> grid = {{0,0,0},{0,0,0},{0,0,0}};
    Solution s;
    auto ret = s.shortestPathBinaryMatrix(grid);
    cout<<"ret is "<<ret<<endl;
    return 0;
}

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
