### ISSUE TITLE
Constraints of Data Range Missing for 709. To Lower Case

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3555]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [709. To Lower Case](https://leetcode.com/problems/to-lower-case), the constraint of data range is missing.
For `str`, what is the range of the length? In other words, what is the maximum length of `str`, and what is the minimum length of `str`?

#### Expected behavior
The constraint of the length of `str` should be added in **Constraints** part.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
