### ISSUE TITLE
Missing Test Case - 55. Jump Game

### ISSUE THREAD

**Issue by jorje1908** [LeetCode-Feedback/LeetCode-Feedback#3557]
#### Your LeetCode username

jorje1908

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 
Python3

#### Description of the bug

Dynamic programming O(N^2) time complexity and O(N) space complexity gives a TLE while the same code in JAVA passes 

#### Code you used for Submit/Run operation

This is my python solution and it is the same as one of the proposed solutions in java. I copy pasted the java code and it works python gets TLE
O(N^2)

Python Code
```
class Solution:
    def canJump(self, nums: List[int]) -> bool:
        
        """
        O(N^2) algorithm
        """
        
                        
        arr = ['UNK' for i in range(len(nums))]
        
        arr[-1] = 'G'
        
        for i in range(len(nums)-1, -1,-1):
            dist = min(i+1+nums[i], len(nums))
            for j in range( i+1, dist ):
                if arr[j] == 'G':
                    arr[i] = 'G'
                    break
        return arr[0] == 'G'
```   

Java Code
```
enum Index {
    GOOD, BAD, UNKNOWN
}

public class Solution {
    public boolean canJump(int[] nums) {
        Index[] memo = new Index[nums.length];
        for (int i = 0; i < memo.length; i++) {
            memo[i] = Index.UNKNOWN;
        }
        memo[memo.length - 1] = Index.GOOD;

        for (int i = nums.length - 2; i >= 0; i--) {
            int furthestJump = Math.min(i + nums[i], nums.length - 1);
            for (int j = i + 1; j <= furthestJump; j++) {
                if (memo[j] == Index.GOOD) {
                    memo[i] = Index.GOOD;
                    break;
                }
            }
        }

        return memo[0] == Index.GOOD;
    }
}
```
#### Language used for code

Python3

#### Expected behavior

This code should be accepted but iit throws a TLE (the similar code in JAVA passes)

**Comment by lc-kay** [comment]
@jorje1908 Please also provide the Java code that was accepted. Thank you.

**Comment by jorje1908** [comment]
> @jorje1908 Please also provide the Java code that was accepted. Thank you.

Hello I have updated the comment with the java code as well

**Comment by lc-kay** [comment]
Hi @jorje1908 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jorje1908 Both solutions can now pass. Thank you for your time.
