### ISSUE TITLE
Missing Test Case - 1865. Finding Pairs With a Certain Sum

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3559]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The current fastest solution fails on the following testcase:
["FindSumPairs","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","add","count"]
[[[1,1,2,2,2,3],[1,4,5,2,5,4]],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1,100000],[1]]

#### Code you used for Submit/Run operation

```
typedef long long ll;
class FindSumPairs {
public:
     vector<int>v1;
    vector<int>v2;
    ll cnt[1000001]={0};
       
    FindSumPairs(vector<int>& nums1, vector<int>& nums2) {
        for(auto x:nums1)
             v1.push_back(x);
        
         for(auto x:nums2)
             v2.push_back(x);
         for(auto x:v2)
            cnt[x]++;
        
    }
    
    void add(int index, int val) {
        ll d=v2[index];
        v2[index]+=val;
        cnt[d]--;
        cnt[v2[index]]++;
        
    }
    
    int count(int tot) {
        
        ll ans=0;
        for(auto x:v1)
            if(tot-x<=1000000 && tot-x>=0)
            ans+=cnt[tot-x];
      return ans;   
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets Runtime Error.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
