### ISSUE TITLE
387. First Unique Character in a String

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#356]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Approach 2 Linear time solution has wrong analysis

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution:
    def firstUniqChar(self, s: str) -> int:
        """
        :type s: str
        :rtype: int
        """
        # build hash map : character and how often it appears
        count = collections.Counter(s)
        
        # find the index
        for idx, ch in enumerate(s):
            if count[ch] == 1:
                return idx     
        return -1
```

**Expected behavior**
Space complexity : O(N) since we have to keep a hash map with N elements

It should be O(1) as there are max 26 distinct entries in the hashmap at any given time

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem description and time complexity. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
