### ISSUE TITLE
Missing Test Case - 1145. Binary Tree Coloring Game

### ISSUE THREAD

**Issue by zhangxin511** [LeetCode-Feedback/LeetCode-Feedback#3561]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The current test case for Tree [1, 2, 3, 4, 5] , n is 5, and x is 2, returns `false` but seems wrong to me. 
If say player 2 pick 1, which will isolate 1 and 3 for player 1 to draw, and player 1 has to take either 4 or 5, then if player 2 take any thing  from 4 or 5, player 1 has to skip. Then player 2 take 3. Player 2 then win, result should be `true`.

#### Code you used for Submit/Run operation

```
public class Solution {
    private TreeNode _target;
    private int _total;
    private int _x;
    
    public bool BtreeGameWinningMove(TreeNode root, int n, int x) {
        _x = x;
        _total = Count(root);
        int l = Count(_target.left);
        int r = Count(_target.right);
        int p = _total - 1 - l -r;
        int max = Math.Max(l, Math.Max(r, p));
        int min = Math.Min(l, Math.Min(r, p));
        return max + min > n/2;
    }
    
    private int Count(TreeNode root) {
        if (root == null) {
            return 0;
        }
        if (root.val == _x) {
            _target = root;
        }
        return Count(root.left) + Count (root.right) + 1;
    }
}
```

#### Expected behavior
The current test case for Tree [1, 2, 3, 4, 5] , n is 5, and x is 2, returns `false` but seems wrong to me. 
If say player 2 pick 1, which will isolate 1 and 3 for player 1 to draw, and player 1 has to take either 4 or 5, then if player 2 take any thing  from 4 or 5, player 1 has to skip. Then player 2 take 3. Player 2 then win, result should be `true`.

**Comment by lc-kay** [comment]
@zhangxin511 The expected test case is correct. Please refer to the discuss section to debug your code or for a better understanding of the test case. Thank you.
