### ISSUE TITLE
leetcode题目1247逻辑问题

### ISSUE THREAD

**Issue by carrie0330** [LeetCode-Feedback/LeetCode-Feedback#3562]
**你的 LeetCode 用户名**
昱111

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
题解逻辑问题

**你使用的语言**
C

**你提交或者运行的代码**
```
int minimumSwap(char * s1, char * s2)
{
    int i,num = 0, num1 = 0, num2 = 0, len1 = strlen(s1), len2 = strlen(s2);
    if(len1 != len2)
        return -1;
    int flag[len1];
    memset(flag, 0, sizeof(flag));
    for(i = 0; i < len1; i++)
    {
        if(s1[i] == 'x')
            num1++;
    }
    for(i = 0; i < len2; i++)
    {
        if(s2[i] == 'x')
            num1++;
    }
    if(num1%2 != 0)
        return -1;
    for(i = 0; i < len1; i++)
    {
        if(s1[i] == s2[i])
            flag[i] = 1;
    }
    for(i = 0; i < len1; i++)
    {
        if(flag[i] == 0)
        {
            for(int j = i+1; j < len1; j++)
            {
                if(flag[j] == 0)
                {
                    if(s1[i] == s1[j])
                        num++;
                    else
                        num+=2;
                    flag[i] = 1;
                    flag[j] = 1;
                    break;
                }
            }
        }
    }
    return num;
}
```

**期望行为**
通过，系统逻辑判断未找到最简路径
如s1 = "xxyyxyxyxx", s2 = "xyyxyxxxyx"
1、交换s1[1]和s2[4]，s1=“xyyyxyxyxx”，s2="xyyxxxxxyx"
2、交换s1[3]和s2[5]，s1=“xyyxxyxyxx”，s2=“xyyxxyxxyx”
3、交换s1[7]和s2[7]，s1=“xyyxxyxxxx”，s2=“xyyxxyxyyx”
4、交换s1[7]和s2[8]，s1=“xyyxxyxyxx”，s2=“xyyxxyxyxx”
只需交换4次，而测试用例预期输出结果为6次，显然未找到最短路径

**屏幕截图**
[添加屏幕截图辅助我们帮你定位问题]

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，题目没有问题： 预期结果是 4， 代码返回结果为 6，可以再仔细检查并调试一下代码，后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
