### ISSUE TITLE
708. Insert into a Sorted Circular Linked List - Missing test case, buggy judge

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#3563]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

708. Insert into a Sorted Circular Linked List

https://leetcode.com/problems/insert-into-a-sorted-circular-linked-list/

#### Code you used for Submit/Run operation

```
var insert = function (head, val) {
    return head;
};
```

#### Expected behavior

- Below is accepted, but it should not:

Your input
[0]
1
Output
[0]
Expected
[0,1]

#### Screenshots

![Screenshot (381)](https://user-images.githubusercontent.com/8236389/118803469-02329380-b8c1-11eb-8091-6ad47dd69f5f.png)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
