### ISSUE TITLE
Missing Test Case - 462. Minimum Moves to Equal Array Elements II

### ISSUE THREAD

**Issue by artem-gabbasov** [LeetCode-Feedback/LeetCode-Feedback#3565]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question doesn't specify what to do in case the answer doesn't fit in an int variable (which is easily achievable with the listed constraints, e.g. with the following input: [1000000000,-1000000000,1000000000,-1000000000])

**Comment by lc-kay** [comment]
@artem-gabbasov The testcase you have provided is invalid. When you run it in the console, it will return Line 97: Char 22: runtime error: signed integer overflow: 2000000000 + 2000000000 cannot be represented in type 'int' (solution.cpp) - Invalid Error. Thank you for your time.

**Comment by artem-gabbasov** [comment]
This is exactly what I wanted to say. The test case is invalid, but it perfectly conforms to the constraints mentioned in the problem statement (I suppose the constraints should be revised, as the expected behavior in case of overflow, which is possible here, isn't specified in the problem statement)

**Comment by lc-kay** [comment]
Hi @artem-gabbasov 
Thank you for the clarification. I've relayed this issue to our team to investigate.

**Comment by artem-gabbasov** [comment]
Thank you

**Comment by lc-kay** [comment]
@artem-gabbasov Our team has added a constraint to prevent overflow and illustrated it in the statement. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by artem-gabbasov** [comment]
@lc-kay thank you, my LeetCode ID is artem_gabbasov
