### ISSUE TITLE
Not the best Statement (problem description) - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by MahmoudHamdy00** [LeetCode-Feedback/LeetCode-Feedback#3567]
#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### the question doesn't declare obviously
one can understand from the question that they are numbers from 1 to n+1 and there is only one repeated element, and i should return this repeated element

####  this part 
`All the integers in nums appear only once except for precisely one integer which appears two or more times.`
#### Code you used for Submit/Run operation

```
class Solution {
public:
	int findDuplicate(vector<int>& nums) {
		int xOr = 0;
        int n=nums.size();
		for (int i = 1; i <= n; i++)xOr ^= i;
		for (int i:nums)xOr ^= i;
		int frstBit = xOr & ~(xOr - 1);
		int x = 0, y = 0;
		for (int i:nums)
			if (i & frstBit)
				x ^= i;
			else
				y ^= i;
		for (int i = 1; i <= n; i++)
			if (i & frstBit)
				x ^= i;
			else
				y ^= i;
        
        for(int i:nums)if(i==x)return x;
        return y;
		
	}
};
```

**Comment by lc-kay** [comment]
@MahmoudHamdy00 The problem description states that "There is only one repeated number in nums, return this repeated number." The constraint section that states "All the integers in nums appear only once except for precisely one integer which appears two or more times." is simply a re-worded version of that. Thank you for your understanding.
