### ISSUE TITLE
Typo in constraints - 418. Sentence Screen Fitting

### ISSUE THREAD

**Issue by kuzmichp** [LeetCode-Feedback/LeetCode-Feedback#3569]
#### Your LeetCode username
kuzmichp

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a typo in the first constraint: 1 <= sente**m**ce.length <= 100 (m has to be replaced with n).

**Comment by lc-kay** [comment]
Hi @kuzmichp 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kuzmichp 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
