### ISSUE TITLE
[1457. Pseudo-Palindromic Paths in a Binary Tree] Javascript Testcase 52

### ISSUE THREAD

**Issue by scottcrossen** [LeetCode-Feedback/LeetCode-Feedback#357]
**What kind of the bug**
- [X] problem
- [ ] solution
- [X] language

**Describe the bug**
Testcase 52 is nearly-impossible to solve within the given time limit given for Javascript (and only Javascript it seems). It appears as if most of the time is taken by parsing the tree from the input -- and not with the user code (although I can't confirm this). I was able to submit code under the time limit but the next day, the exact same code doesn't work. Solutions marked on the [discussion panel](https://leetcode.com/problems/pseudo-palindromic-paths-in-a-binary-tree/discuss/?currentPage=1&orderBy=most_votes&query=&tag=javascript) are not reproducible by other users. My own submissions are flaky and valid submissions are all close to 8 seconds if they work at all.

**what language is your code written in**
Javascript

**The code you submit/run**
```
var pseudoPalindromicPaths  = function(root) {
    return helper(root, 0);
};

const validBitVectors = [0, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024];

var helper = function(root, odds) {
    odds ^= (1 << root.val);
    if (!root.left && !root.right) {
       return validBitVectors.indexOf(odds) > -1 ? 1 : 0;        
    }
    let output = 0;
    if (root.left) {
        output += helper(root.left, odds);
    }
    if (root.right) {
        output += helper(root.right, odds);
    }
    return output;
}
```

**Expected behavior**
Not TLE when using the optimal solution

**Additional context**
It's unfortunate that so many of us (Javascript writers) were denied the points for the most recent weekly contest because of this test case.

**Comment by scottcrossen** [comment]
Also, I failed to link my LeetCode account before posting this. Am I still eligible for the leetcoins? (account: ScottXN).

**Comment by CooperCooperCooper** [comment]
Hi @scottcrossen ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by poppinlp** [comment]
+1. I meet this issue also. Here's [my post](https://leetcode.com/problems/pseudo-palindromic-paths-in-a-binary-tree/discuss/653159/javascript-is-there-something-wrong-with-the-time-limit-for-js/557192) on leetcode discuss.

And here's my code:

```js
const pseudoPalindromicPaths = (node, freq = 0) => {
  freq ^= 1 << node.val;
  return !node.left && !node.right
    ? +!(freq & (freq - 1))
    : (node.left && pseudoPalindromicPaths(node.left, freq)) + (node.right && pseudoPalindromicPaths(node.right, freq));
};
```

**Comment by CooperCooperCooper** [comment]
Hi @scottcrossen and @poppinlp ,
Thank you for your time. This issue has been fixed. 

@scottcrossen your LeetCode account has been rewarded for reporting this issue.
