### ISSUE TITLE
Missing Test Case - 968. Binary Tree Cameras

### ISSUE THREAD

**Issue by Northnroro** [LeetCode-Feedback/LeetCode-Feedback#3570]
#### Your LeetCode username

napat (northnroro@hotmail.com)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Tree with deep depth (more than 32 or 64 levels) is not in the testcase set. Some approaches contain overflowing integer/long, and should not pass this problem. For example, the code below labels each node with a number - `node.label = node.parent.label*2+1` which will eventually overflow.

#### Code you used for Submit/Run operation

```
// 968. Binary Tree Cameras
class Solution {
    public int minCameraCover(TreeNode root) { // [0,0,null,0,0] -> [0,1,3,4]
        PriorityQueue<Integer> pq = new PriorityQueue<Integer>((a,b) -> b-a);
        addToPq(root, 0, pq);
        Set<Integer> set = new HashSet<>(pq);
        int cnt = 0;
        while(!pq.isEmpty()){
            Integer biggest = pq.poll();
            if(set.contains(biggest)){
                Integer mark = biggest == 0 ? 0 : (biggest-1)/2; //mark the parent;
                cnt++;
                set.remove(mark);
                set.remove((mark-1)/2);
                set.remove(mark*2+1);
                set.remove(mark*2+2);
            }
             
        }
        return cnt;
    }
    public void addToPq(TreeNode t, int pos, PriorityQueue<Integer> pq){
        pq.add(pos);
        if(t.left != null){
            addToPq(t.left, pos*2+1, pq);
        }
        if(t.right != null){
            addToPq(t.right, pos*2+2, pq);
        }
    }
}
```

#### Language used for code

Java

#### Expected behavior

Any integer should not overflow 32-bit memory when we have tree with depth greater than 32 levels.

#### Screenshots

![image](https://user-images.githubusercontent.com/7249025/118919651-82abcf80-b967-11eb-8101-bead7a8c883b.png)

#### Additional context

Testcase
```
[0,null,0,null,0,null,0,null,0,null,0,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,0,null,null,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null]
```

**Comment by lc-kay** [comment]
Hi @Northnroro 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Northnroro 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
