### ISSUE TITLE
Missing Test Case - 890. Find and Replace Pattern

### ISSUE THREAD

**Issue by yogeshporwal** [LeetCode-Feedback/LeetCode-Feedback#3571]
#### Your LeetCode username
yogi_yrp

#### Category of the bug
- [x] Missing Test Cases
- [x] Wrong Custom Test Case Output

#### Description of the bug
For this question ,constraint is given that pattern.length()==word[i].length() ,so if I make a custom test case which violates this constraint then OJ should call it invalid test case but it is giving output and calling my correct output as incorrect output. Actually initially I did not see this constraint so I was making testcase for this case ,and OJ was calling it incorrect so I did not think that it is against the constraint ,and I wasted a lot of time in finding issue in my code and finally I came to know that this case is not valid.Then I submitted same code and it was accepted. 

#### Code you used for Submit/Run operation

```
// Find and Replace Pattern
vector<string> findAndReplacePattern(vector<string>& words, string pattern)
    {
        const int diff='a'-'A';
        vector<string> matched_words;
        
        
        for(auto &p:pattern)
        {
            p=p-diff;
        }
        
        
        for(auto word:words)
        {
            //string w=word;
            int m=word.length(),flag=1;
            
            unordered_map<char,char> map1,map2;
            
            if(m!=pattern.length())
                continue;
            
            for(int i=0;i<m;i++)
            {
                
                if(map1.find(pattern[i])!=map1.end() or map2.find(word[i])!=map2.end())
                {
                    if(word[i]!=map1[pattern[i]])
                    {
                        flag=0;
                        break;
                    }
                }
                else
                {
                    map1[pattern[i]]=word[i];
                    map2[word[i]]=pattern[i];
                }
                
               //cout<<"p "<<word<<endl; 
            }
            
            
            
            if(flag)
                matched_words.push_back(word);
            
        }
        
        return matched_words;
    }
```

#### Language used for code
C++ 

#### Expected behavior
My custom testcase should not be executed and OJ should call it invalid testcase instead of giving incorrect output.

#### Screenshots
![image](https://user-images.githubusercontent.com/71559316/118921565-065cc080-b956-11eb-8441-fc0b10533bdf.png)

**Comment by lc-kay** [comment]
Hi @yogeshporwal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yogeshporwal 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
