### ISSUE TITLE
Missing Test Case - 56. Merge Intervals

### ISSUE THREAD

**Issue by XeroxLin** [LeetCode-Feedback/LeetCode-Feedback#3572]
#### Your LeetCode username

Xerox_lin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [O] Language
- [ ] Missing Test Cases 

#### Description of the bug

Constraints:

The intervals[i].length explanation should use "=" instead of "=="
intervals[i].length == 2

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @XeroxLin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@XeroxLin This is our standard and we don't intend to change it. Thank you for your understanding.
