### ISSUE TITLE
Missing Test Case - 350. Intersection of Two Arrays II

### ISSUE THREAD

**Issue by ra312** [LeetCode-Feedback/LeetCode-Feedback#3573]
#### Category of the bug
- [ ] Question

#### Description of the bug

The statement of the problem is misleading

#### Code you used for Submit/Run operation

```
class Solution:
    def intersect(self, nums1: List[int], nums2: List[int]) -> List[int]:
        
        freqs_1 = {num:0 for num in nums1}
        freqs_2 = {num:0 for num in nums2}
        for num in nums1:
            freqs_1[num] +=1
        for num in nums2:
            freqs_2[num] +=1
        
        keys_1 = set(freqs_1.keys())
        keys_2 = set(freqs_2.keys())
        intersection = keys_1 & keys_2
        for num in intersection:
            freqs_1[num] += freqs_2[num]
        
        result = []
        for num in intersection:
            counted = freqs_1[num]
            result += [num]*counted
            
        return result
```

#### Language used for code

Python3

#### Expected behavior

Given two integer arrays nums1 and nums2, return an array of their intersection. Each element in the result must appear as many times as it shows in both arrays and you may return the result in any order.
With inputs
[1,2,2,2,1] (2 is repeated 3 times)
[2,2] (2 is repeated 2 times)
The expected output (according to the formulation above) has to be

[2,2,2,2,2] ( 2 is repeated 2+3=5 times)
#### Screenshots

<img width="658" alt="image" src="https://user-images.githubusercontent.com/12486277/118973926-067bb100-b994-11eb-92e1-f4c8d1c5c887.png">

**Comment by lc-kay** [comment]
@ra312 As stated in the problem description, "Each element in the result should appear as many times as it shows **in both arrays.**" The maximum times that each element shown in both arrays is twice, therefore, the expected answer is [2,2]. For further questions, please refer to the problem discuss section. Thank you for your time.
