### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by ctcappellano** [LeetCode-Feedback/LeetCode-Feedback#3574]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@ctcappellano Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
