### ISSUE TITLE
Missing Test Case - 1089. Duplicate Zeros

### ISSUE THREAD

**Issue by sandeepkolla99** [LeetCode-Feedback/LeetCode-Feedback#3576]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@sandeepkolla99 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
