### ISSUE TITLE
Typo in 494. Target Sum solution Approach 3

### ISSUE THREAD

**Issue by mallika-b** [LeetCode-Feedback/LeetCode-Feedback#3579]
https://leetcode.com/problems/target-sum/solution/

"we can use dp[i][sum + nums[i]] = dp[i][sum + nums[i]] + dp[i-1][sum]. 
     Similarly, dp[i][sum - nums[i]] = dp[i][sum + nums[i]] + dp[i-1][sum]"

Note that the first rhs term in the 2nd line is incorrect

**Comment by lc-kay** [comment]
Hi @mallika-b 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @mallika-b 
Thank you for your feedback. The problem has been updated! We appreciate your support!
