### ISSUE TITLE
494. Target Sum

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#358]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Approach 2 Recursion with Memoization has wrong analysis

**what language is your code written in**
Java

**The code you submit/run**
```
public class Solution {
    int count = 0;
    public int findTargetSumWays(int[] nums, int S) {
        int[][] memo = new int[nums.length][2001];
        for (int[] row: memo)
            Arrays.fill(row, Integer.MIN_VALUE);
        return calculate(nums, 0, 0, S, memo);
    }
    public int calculate(int[] nums, int i, int sum, int S, int[][] memo) {
        if (i == nums.length) {
            if (sum == S)
                return 1;
            else
                return 0;
        } else {
            if (memo[i][sum + 1000] != Integer.MIN_VALUE) {
                return memo[i][sum + 1000];
            }
            int add = calculate(nums, i + 1, sum + nums[i], S, memo);
            int subtract = calculate(nums, i + 1, sum - nums[i], S, memo);
            memo[i][sum + 1000] = add + subtract;
            return memo[i][sum + 1000];
        }
    }
}
```

**Expected behavior**
Space complexity : O(n). The depth of recursion tree can go upto n

The space complexity also includes the memo matrix which will exceed n and so space complexity will be quadratic like time complexity.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the time complexity for this problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
