### ISSUE TITLE
496. Next Greater Element I

### ISSUE THREAD

**Issue by nawendusingh** [LeetCode-Feedback/LeetCode-Feedback#3580]
#### Your LeetCode username

jitin11

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
wrong animation

#### Description of the bug

in the animation, the map cant have 2 keys with same value. its also stated in the question that the numbers are unique.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @nawendusingh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
