### ISSUE TITLE
Missing Test Case - 16. 3Sum Closest

### ISSUE THREAD

**Issue by adityarastogi1212** [LeetCode-Feedback/LeetCode-Feedback#3582]
#### Missing Test Cases
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### 
Input: nums = [-3,1,2,3], target = 2
Output: 2
Explanation: The sum that is closest to the target is 2. (-3 + 2 + 3 = 2).

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@adityarastogi1212 Please provide the accepted code that this test case will fail. Thank you.

**Comment by lc-kay** [comment]
Hi @adityarastogi1212 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
