### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by anitej036** [LeetCode-Feedback/LeetCode-Feedback#3583]
#### Your LeetCode username

anitej123

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Missing Test Case

#### Description of the bug

The bug is the missing test case. When I submit my code it gets accepted, instead it should show wrong answer because when I run it on my test cases it gives wrong answer. So these test cases need to be added.
Test Case - "InFiNiTy"
or test can be any permutations of upper case and lower case alphabets in word "INFINITY"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def isNumber(self, s: str) -> bool:
        if(s=="inf" or s=="+inf" or s=="-inf" or s=="nan" or s=="+nan" or s=="+nan" or s=="Infinity" or s=="+Infinity" or s=="-Infinity" or s=="infinity" or s=="-infinity"  or s=="+infinity"):
            return False
        try:
            float(s)
        except:
            return False
        return True
```

#### Language used for code

Python3

#### Expected behavior

When I run code on my test cases it gives wrong answer, but when I submit the code it shows "Accepted". This should not happen, it should have shown "Wrong Answer"
My Test Case - "InFiNiTy"
 

#### Additional context

Some more test cases can be
"InfinitY"
"infiNITY"
"infiNIty"
![Test_case_error_LI](https://user-images.githubusercontent.com/60323633/119090465-4a6cc580-ba29-11eb-90ee-09cf788544f8.jpg)

**Comment by lc-kay** [comment]
Hi @anitej036 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@anitej036 Our team is no longer adding new test cases to this problem to keep it simple and to avoid more frustrating test cases. Thank you for your understanding.
