### ISSUE TITLE
 Path With Minimum Effort||dijkstra algorithm

### ISSUE THREAD

**Issue by akshaya-17** [LeetCode-Feedback/LeetCode-Feedback#3584]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@akshaya-17 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
