### ISSUE TITLE
Missing Test Case - 1206. Design Skiplist

### ISSUE THREAD

**Issue by hpp3** [LeetCode-Feedback/LeetCode-Feedback#3588]
#### Your LeetCode username
hpp3

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
1206. Design Skiplist can be solved without implementing a skip list. The required API can be solved using a hashmap that counts the quantity of each element.  In order to force a skip list to be used, the question should require an additional method that returns the kth largest element or something else similar that disqualifies the hashmap solution.

#### Code you used for Submit/Run operation

```
class Skiplist:

    def __init__(self):
        self.counts = {}
    def search(self, target: int) -> bool:
        return self.counts.get(target, 0) > 0

    def add(self, num: int) -> None:
        self.counts[num] = self.counts.get(num, 0) + 1

    def erase(self, num: int) -> bool:
        if num in self.counts and self.counts[num]: 
            self.counts[num] -= 1
            return True
        return False

```

#### Language used for code
Python

#### Expected behavior
Hashmap solution should not be able to pass this problem.

**Comment by lc-kay** [comment]
@hpp3 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hpp3 This problem was designed to be a practice problem. The user has the right to solve the problem with any approach but they have to keep in mind that in a real interview you will be forced to implement the skiplist itself. Thank you for your understanding.
