### ISSUE TITLE
Missing Test Case - 1475. Final Prices With a Special Discount in a Shop

### ISSUE THREAD

**Issue by Manish23121** [LeetCode-Feedback/LeetCode-Feedback#3589]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Manish23121 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
