### ISSUE TITLE
[problem] 1295. Find Numbers with Even Number of Digits - Missing test case

### ISSUE THREAD

**Issue by sekhar179** [LeetCode-Feedback/LeetCode-Feedback#359]
**What kind of the bug**
- [x] problem

**Describe the bug**
Missing a test case in the question "1295. Find Numbers with Even Number of Digits"

**what language is your code written in**
C++

**The code you submit/run**
```
// Find Numbers with Even Number of Digits
class Solution {
public:
    int findNumbers(vector<int>& nums) {
        int count = 0;
        for (int n: nums)
            if ((n >= 10 && n < 100) || (n >= 1000 && n < 10000)) // Wrong implementation but passed
            count++;
        return count;
    }
};
```

**Expected behavior**
Constraint section mentions 1 <= nums[i] <= 10^5
But the test passes even though the program doesn't consider the boundary case - 10^5 (100000) value

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @sekhar179 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @sekhar179 ,
Thank you for your time. Please attach a concise test case since the provided information is incomplete. We will add the test case when you provide us with a correct contribution.

**Comment by sekhar179** [comment]
Please find below the test case.
Input: [100000]
Expected Output: 1

**Comment by CooperCooperCooper** [comment]
Hi @sekhar179 ,
Thank you for your time. We've added the test case you've contributed above. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
