### ISSUE TITLE
Missing Test Case - 1800. Maximum Ascending Subarray Sum

### ISSUE THREAD

**Issue by SWeszler** [LeetCode-Feedback/LeetCode-Feedback#3592]
#### Your LeetCode username
SWeszler

#### Category of the bug
- [x] Question

#### Additional context
Is it necessary to tag this as "Two Pointers" problem? It's really misleading for those who want to practice this technique.

**Comment by lc-kay** [comment]
@SWeszler We add related tags to the problem for users to find problems with this approach. We understand that there are multiple ways to approach each problem. Thank you for your time.
