### ISSUE TITLE
Solution - 1476. Subrectangle Queries

### ISSUE THREAD

**Issue by jasminnasit** [LeetCode-Feedback/LeetCode-Feedback#3594]
#### Your LeetCode username

jasminnasit48

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

solution of this problem is not available yet

#### Code you used for Submit/Run operation

```
class SubrectangleQueries {

    int[][] rectangle;
    
    public SubrectangleQueries(int[][] rectangle) {
        this.rectangle = rectangle;
    }
    
    public void updateSubrectangle(int row1, int col1, int row2, int col2, int newValue) {
        for( int i = row1 ; i <= row2 ; i++){
            for (int j = col1; j <= col2; j++){
                this.rectangle[i][j] = newValue;
            }
        }
    }
    
    public int getValue(int row, int col) {
        return this.rectangle[row][col];
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

solution of this problem is not available yet

#### Screenshots

![solution](https://user-images.githubusercontent.com/24349906/119221089-47e29c80-bb0b-11eb-8bd5-ce0ace354d43.PNG)

**Comment by lc-kay** [comment]
@jasminnasit Please share your solution with the community in the problem discuss section. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
