### ISSUE TITLE
Missing Test Case - 51. N-Queens

### ISSUE THREAD

**Issue by PritishWadhwa** [LeetCode-Feedback/LeetCode-Feedback#3595]
#### Your LeetCode username
pritish19440

#### Category of the bug
- [ ] Language

#### Description of the bug
It should be mentioned that any ordering of the solution would be acceptable.

**Comment by lc-kay** [comment]
Hi @PritishWadhwa 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @PritishWadhwa 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
