### ISSUE TITLE
alien-dictionary - invalid test case

### ISSUE THREAD

**Issue by mbatista** [LeetCode-Feedback/LeetCode-Feedback#3596]
https://leetcode.com/problems/alien-dictionary/

["abc", "ab"] is not a valid case since the description states **"... the strings in words are sorted lexicographically by the rules of this new language"**

Expected behavior for this input should be any permutation of "abc", i.e: there is no order relationship that can be determine instead of "" which would represent "impossible order"

**Comment by lc-kay** [comment]
@mbatista This test case is valid. In a proper lexicographically ordered language, the prefixes of alphabets come first. For further questions, please refer to the problem discuss section. Thank you for your time.
