### ISSUE TITLE
Missing Test Case - 380. Insert Delete GetRandom O(1)

### ISSUE THREAD

**Issue by serhatzor** [LeetCode-Feedback/LeetCode-Feedback#3598]
Hi ,

I have developed that using C# . It always throws exception for the test case.
You have mentioned that probability must be same for each  number in the set.
But I think your expected output ([null,true,true,true,true,20,1,10,10,20,10,1,10,20,1,30,20,20,30,1,30) does not cover the probability condition. 

I think we must calculate the probability with calling getRandom method as many as the count of the set.

["RandomizedSet","insert","insert","insert","insert","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom" ....

**Comment by lc-kay** [comment]
@serhatzor Please provide the submission details to your code. In addition, please provide the full testcase in a .txt file. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @serhatzor 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
