### ISSUE TITLE
Problem description issue - 565. Array Nesting

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#3599]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

`You should build a set s[k] = {nums[k], nums[nums[i]], nums[nums[nums[k]]], ... } subjected to the following rule:`

In the above, what is `i` ?
It should be `k`

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

Problem description is confusing, must use `k` instead of `i`

#### Screenshots

![image](https://user-images.githubusercontent.com/8236389/119244833-0a752200-bb92-11eb-8cc9-b8851db565eb.png)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
