### ISSUE TITLE
994. Rotting Oranges wrong test case

### ISSUE THREAD

**Issue by conghao321** [LeetCode-Feedback/LeetCode-Feedback#360]
A wrong test case in 994 problem

The wrong test case is : [[0]]
it means only 1 cell which is empty without any other oranges.
The correct result should be: -1, which means never can be rotten.
However, the existed answer for this testcase is 0, which means initially is rotten....

**Comment by CooperCooperCooper** [comment]
Hi @conghao321 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @conghao321 ,
Thank you for your time. Upon reviewing your feedback, we found you've misunderstood the problem. Please check out the Discuss Section [posts](https://leetcode.com/problems/rotting-oranges/discuss?currentPage=1&orderBy=newest_to_oldest&query=) for more information. We appreciate your support.
