### ISSUE TITLE
Missing Test Case 5765. Jump Game VII

### ISSUE THREAD

**Issue by KayChengTJ** [LeetCode-Feedback/LeetCode-Feedback#3600]
#### Your LeetCode username

KayChengTJ

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Some Test Cases are missing.
such as:
```
"000000000"
3
4
```
which output should be `true`.
Though my code passed all the test cases, didn't pass the above test cases.

#### Code you used for Submit/Run operation

```
// canReach
class Solution {
public:
    bool canReach(string s, int minJump, int maxJump) {
        int n = s.size();
        if(s[n - 1] != '0') return false;
        int left = n - 1 - maxJump, right = n - 1 - minJump;
        for(int i = n - 2; i > 0; i--)
            if(s[i] == '0' && (i >= left && i <= right)){
                left = i - maxJump;
                right = i - minJump;
                if(left <= 0 && right >= 0)
                    return true;
            }
        return left <= 0 && right >= 0;
    }
};
```

#### Language used for code

C++

#### Screenshots

![pass](https://user-images.githubusercontent.com/34208313/119248979-9fded900-bbc7-11eb-8129-7cd2095a7103.PNG)
![bug](https://user-images.githubusercontent.com/34208313/119248980-a4a38d00-bbc7-11eb-9313-cfc96738d3fc.PNG)

**Comment by lc-kay** [comment]
Hi @KayChengTJ 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@KayChengTJ Our team recently updated the test case set for this problem and your submitted code fails on one of the newly added test case. Therefore, we will not be adding your custom test case. Thank you for your time.
