### ISSUE TITLE
Tree serialization failing - 426. Convert Binary Search Tree to Sorted Doubly Linked List

### ISSUE THREAD

**Issue by mbatista** [LeetCode-Feedback/LeetCode-Feedback#3601]
#### Your LeetCode username
batistamarcelf

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Test cases execution failing

#### Description of the bug

Execution of solution fails before it starts, due to an apparent bug in the Tree Nodes deserialization. Inputs such as [4] or [4, null, null] fail to execute.

#### Code you used for Submit/Run operation
```
public class Solution {
    public Node TreeToDoublyList(Node root)
    {
        return RecursiveTreeToDoublyList(root).head;
    }
    
    private static (Node head, Node tail) RecursiveTreeToDoublyList(Node node)
    {
        if(node == null)
        {
            return (null, null);
        }
        
        if(node.left == null && node.right == null)
        {
            return (node, node);
        }
        
        var left = RecursiveTreeToDoublyList(node.left);
        var right = RecursiveTreeToDoublyList(node.right);
        
        node.left = null;
        node.right = null;
        
        if(left.head != null)
        {
            node.left = left.tail;
            node.right = right.head ?? left.head;
            
            left.tail.right = node;
            left.head.left = right.tail ?? node;
            
            if(right.head != null)
            {
                right.head.left = node;
                right.tail.right = left.head;
            }
                
            return(left.head, right.tail ?? node);
        }
        else
        {
            node.left = right.tail;
            node.right = right.head;
            
            if(right.head != null)
            {
                right.head.left = node;
                right.tail.right = left.head ?? node;
            }
            
            return (left.head ?? node, right.tail ?? node);
        }
    }
}
```

#### Language used for code
C#

#### Expected behavior
My solution gets executed

#### Screenshots
![image](https://user-images.githubusercontent.com/2420629/119250982-b437bd00-bb58-11eb-818e-432e06676f36.png)
![image](https://user-images.githubusercontent.com/2420629/119250997-c6b1f680-bb58-11eb-8a41-74792fcbce0e.png)

#### Additional context
none

**Comment by mbatista** [comment]
Seems like it's not pre execution, but post execution, when trying to print a wrong result

**Comment by lc-kay** [comment]
@mbatista Please provide the submission details link to your code. Thank you.

**Comment by lc-kay** [comment]
Hi @mbatista 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
