### ISSUE TITLE
Missing Test Case - 949. Largest Time for Given Digits

### ISSUE THREAD

**Issue by Donny-G** [LeetCode-Feedback/LeetCode-Feedback#3602]
#### Your LeetCode username
Donny-G

#### Missing Test Cases 
- [ ] Missing Test Cases 

#### Description of the bug
Some Test Cases are missing.
such as:

Input: arr = [1,2,3,4]
Output: "23:41"
Explanation: The valid 24-hour times are "12:34", "12:43", "13:24", "13:42", "14:23", "14:32", "21:34", "21:43", "23:14", and "23:41". Of these times, "23:41" is the latest.

There is absent of combination "23:43"
Though my code passed all the test cases, didn't pass the above test case.

#### Code you used for Submit/Run operation

class Solution {
func largestTimeFromDigits(_ arr: [Int]) -> String {
var possibleHourArray = [Int]()
var possibleMinutesArray = [Int]()
var possibleCombinationsArray = [Int]()

var index = 0

while index != 4 {
    for i in 0 ..< arr.count {
        if i != index {
            possibleCombinationsArray.append(Int(String(arr[index]) + String(arr[i])) ?? 0)
        }
    }
    index += 1
}
for number in possibleCombinationsArray {
    if number < 24 {
        possibleHourArray.append(number)
        possibleMinutesArray.append(number)
    } else if number < 59 {
        possibleMinutesArray.append(number)
    }
}
if possibleHourArray.isEmpty {
    return ""
} else {
    return "\(possibleHourArray.max() ?? 0):\(possibleMinutesArray.max() ?? 0)"
}  
}
}

#### Language used for code
Swift

#### Expected behavior
As there is no combination of "23:43" which is correct output, it is greater than "23:41" and is correct for the latest 24-hour time, my solution won't work

#### Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/49961778/119251027-d3603a00-bbac-11eb-9f98-8538ec3de35c.png">

**Comment by lc-kay** [comment]
@Donny-G Please provide the submission details link to your code. Thank you.

**Comment by Donny-G** [comment]
https://leetcode.com/problems/largest-time-for-given-digits/submissions/

**Comment by lc-kay** [comment]
@Donny-G Please click on the status of the submission and it will take you to the submission details link with your submitted code. Please provide me with that link. Thank you.

**Comment by lc-kay** [comment]
Hi @Donny-G 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
