### ISSUE TITLE
Missing Test Case - 1689. Partitioning Into Minimum Number Of Deci-Binary Numbers

### ISSUE THREAD

**Issue by aayush181295** [LeetCode-Feedback/LeetCode-Feedback#3603]
Missing Test Case

#### Your LeetCode username

aayush1895

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [-] Missing Test Cases 

#### Code you used for Submit/Run operation

```
   class Solution {
    public int minPartitions(String n) {
        int length = Math.min(n.length(), 10);
        int max = n.charAt(0) - 48;
        for (int i = 1; i < length; i++) {
            if (n.charAt(i) - 48 > max) {
                max = n.charAt(i) - 48;
            }
        }
        return max;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Add this test case for this code 111111111119, the above solution will fail .

**Comment by lc-kay** [comment]
Hi @aayush181295 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @aayush181295 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
