### ISSUE TITLE
Missing Test Case - 1871. Jump Game VII

### ISSUE THREAD

**Issue by sachuverma** [LeetCode-Feedback/LeetCode-Feedback#3604]
#### Your LeetCode username
username: anjali-mc

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I have used an approach during contest, but now after analysing my approach more carefully I found some test case it should not pass, but it passed all test cases during contest

I considered -
s = "0111000110"
minJump = 2, maxJump = 4

now in my approach we start at index 1, then when we encounter a s[i] == '0' we find if in it's previous jump range that will be `[curr_index - maxJump, curr_index - minJump]` if there is any '0' we can come at current '0' so continue and check for next '0'

But when we are at index 5, it will return false 
but instead it should not return false here because from index 6 we have a valid path

#### Code you used for Submit/Run operation

```
/class Solution {
public:
    bool canReach(string s, int minJump, int maxJump) {
      int n = s.size();
      if(s[n-1] != '0') return false;
      
      for(int i=1; i<n; ++i){
        
        if(s[i] == '0'){
          int mi = max(0, i-maxJump);
          int ma = i - minJump;
          
          int index = s.find("0", mi);
          
          if(ma < 0) {
            s[i] = '1';
            continue;
          }
          
          if(index <= ma) continue;
          else return false;
        }
      }
      
      return true;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

It should fail, but passed all test cases

#### Screenshots

Dry run for this test case

for 4th index it's true we can reach from a 0 in the circled range to here
![WhatsApp Image 2021-05-23 at 2 59 55 PM](https://user-images.githubusercontent.com/43083013/119255545-0c62d380-bbda-11eb-8715-8d9b2705608f.jpeg)

But here, there is no 0 in range so it returns false, here
![WhatsApp Image 2021-05-23 at 3 00 34 PM](https://user-images.githubusercontent.com/43083013/119255550-12f14b00-bbda-11eb-8b14-5b25a89c505b.jpeg)

But there could we this path. but we returned false earlier
![WhatsApp Image 2021-05-23 at 3 00 58 PM](https://user-images.githubusercontent.com/43083013/119255557-17b5ff00-bbda-11eb-8793-7f8e7ab7f8ef.jpeg)

here it shows correct verdict, but code is accepted
![WhatsApp Image 2021-05-23 at 3 04 01 PM](https://user-images.githubusercontent.com/43083013/119255564-1c7ab300-bbda-11eb-85ca-83b4dd44a074.jpeg)

**Comment by lc-kay** [comment]
Hi @sachuverma 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@sachuverma Our team recently updated the test case set for this problem and your submitted code fails on one of the newly added test case. Therefore, we will not be adding your custom test case. Thank you for your time.
