### ISSUE TITLE
Missing Test Case - 36. Valid Sudoku

### ISSUE THREAD

**Issue by FernandoPieressa** [LeetCode-Feedback/LeetCode-Feedback#3609]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The expected solution is not working properly, when trying the custom test case:

` arr = [[".","2","3","4","5","6","7","8","9"],["1",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."]]`

It returns `true` as the expected output, but it should be `false`. As there is no valid element in arr[0][0] that could be added.

#### Code you used for Submit/Run operation

N/A the problem is with the expected solution

#### Language used for code

Python

#### Expected behavior

` arr = [[".","2","3","4","5","6","7","8","9"],["1",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."]]`

It returns `true` as the expected output, but it should be `false`. As there is no valid element in arr[0][0] that could be added.

#### Screenshots

![image](https://user-images.githubusercontent.com/13782155/119268748-5475fc00-bbc2-11eb-897e-14d523377294.png)

#### Additional context

The problem is with the expected solution output.

**Comment by CELLSecret1121** [comment]
There is a note saying that 
> Only the filled cells need to be validated according to the mentioned rules.
Thus, although it is not solvable, it follows the rule of sudoku until this point, and the expected solution output would be `true`.

**Comment by lc-kay** [comment]
@FernandoPieressa I'm glad that @CELLSecret1121 was able to address your doubts and concerns. Thank you both of your time and support.
