### ISSUE TITLE
Memory Limit Exceeded for best-time-to-buy-and-sell-stock-iv 

### ISSUE THREAD

**Issue by shettyvinay** [LeetCode-Feedback/LeetCode-Feedback#361]
**What kind of the bug**
- [x] best-time-to-buy-and-sell-stock-iv
- [x] https://leetcode.com/submissions/detail/344917460/
- [x] English

**Describe the bug**
Memory Limit Exceeded repeatedly 

**what language is your code written in**
Java

**Comment by CooperCooperCooper** [comment]
Hi @shettyvinay ,
Thank you for reaching out to us. Here's a [Java way ](https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/discuss/54117/Clean-Java-DP-solution-with-comment)to optimize your solution for this problem. Please try it out.
