### ISSUE TITLE
Wrong constraints - 366. Find Leaves of Binary Tree

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#3610]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Question has positive constraints
But the test case has negative values
Judge also passes negative value tests

Problem description is wrong, should include negative values too

#### Code you used for Submit/Run operation

```

var findLeaves = function (r) {
    return [[r.val]];
};

```

#### Expected behavior

test case fails because it has -ve values
but the question says only +ve values which is wrong

#### Screenshots

![Screenshot (398)](https://user-images.githubusercontent.com/8236389/119273317-fa0f8680-bc27-11eb-8a48-7fd14cdd55d7.png)

![Screenshot (399)](https://user-images.githubusercontent.com/8236389/119273359-3216c980-bc28-11eb-889f-759b645a2d2d.png)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
