### ISSUE TITLE
Buggy solution accepted: 943. Find the Shortest Superstring

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#3612]
#### Your LeetCode username
Leaderboard. The credits for this bug should go to LeetCode user DBabichev, I am just reporting it here.

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A clearly faulty solution is accepted on Python 2 and 3. 

#### Code you used for Submit/Run operation

```python
class Solution:
    def shortestSuperstring(self, words: List[str]) -> str:
        return words;
```

#### Language used for code

Python 3; bug can be reproduced on Python 2.
#### Expected behavior

Such a clearly incorrect solution should fail, or be tagged as invalid, because it is returning the wrong data type 

#### Screenshots

Accepted link: https://leetcode.com/submissions/detail/497294919 (not publicly viewable)
#### Additional context

This bug was first found by DBabichev in https://leetcode.com/problems/find-the-shortest-superstring/discuss/1225543/Python-dp-on-subsets-solution-3-solutions-%2B-oneliner-explained

**Comment by lc-kay** [comment]
Hi @Leader-board 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Leader-board 
Thank you for your time. We've used your feedback to update the problem. @DBabichev has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
