### ISSUE TITLE
Missing Test Case - 1585. Check If String Is Transformable With Substring Sort Operations

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3613]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The current fastest solution fails on the following testcase:
"312"
"213"

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isTransformable(const string &s, const string &t) const {
        const int n = s.length();
        if (n != t.length()) return false;
        vector<int> cnt(10), rm(10);
        for (int i = 0, j = 0, k = 0; k < n; ++k) {
            char ch = t[k];
            while (!cnt[ch - '0']) {
                if (j == n) {
                    return false;
                }
                ++cnt[s[j++] - '0'];
            }
            while (i < j && rm[s[i] - '0']) --rm[s[i++] - '0'];
            if (s[i] >= ch) {
                --cnt[ch - '0'];
                ++rm[ch - '0'];
            } else {
                return false;
            }
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Output: true
Expected: false

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
