### ISSUE TITLE
1871. 跳跃游戏 VII 测试用例覆盖不全

### ISSUE THREAD

**Issue by BigeYoung** [LeetCode-Feedback/LeetCode-Feedback#3614]
**你的 LeetCode 用户名**
zhi-fu-zhong-xin

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
这道题可以用非常简单的解法**通过**，但该解法实际上存在问题。

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    bool canReach(string s, int minJump, int maxJump) {
        int n = s.size(), L = minJump, R = maxJump;
        for (int i = 0; i < n; ++i) {
            if (s[i] == '0' && L <= i && i <= R) {
                if (i == n - 1) {
                    return true;
                }
                if (i >= R) {
                    L = i + minJump;
                }
                R = i + maxJump;
            }
        }
        return false;
    }
};
```

**期望行为**
在这个用例中是不正确的
```
"011100110101011011011110"
4
5
```

**屏幕截图**
![image](https://user-images.githubusercontent.com/20485391/119294517-358d6d80-bc87-11eb-895c-2c645f39452d.png)

**额外的上下文**
该解法由用户@r4c12 提出。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by BigeYoung** [comment]
额外分享一些会导致错误的测试用例
```
"000000"
3
4

"000010"
3
4

"001000"
3
4

"001010"
3
4

"010000"
3
4

"010010"
3
4

"011000"
3
4

"011010"
3
4

"100000"
3
4

"100010"
3
4

"101000"
3
4

"101010"
3
4

"110000"
3
4

"110010"
3
4

"111000"
3
4

"111010"
3
4
```

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
@feiceh Our team recently updated the test case set for this problem and your submitted code fails on one of the newly added test case. Therefore, we will not be adding your custom test case. Thank you for your time.
