### ISSUE TITLE
Accepted number is greater than Submissions number in problem 1863.Sum of All Subset XOR Totals

### ISSUE THREAD

**Issue by lucliu20** [LeetCode-Feedback/LeetCode-Feedback#3615]
#### Your LeetCode username
<lucliu>

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/76449030/119300192-338ac680-bc15-11eb-9640-a84eba300f35.png)

**Comment by lc-kay** [comment]
@lucliu20 Our team is aware of this issue and I've relayed your ticket to them as well. Thank you for your time.
