### ISSUE TITLE
Submission Error - 144. Binary Tree Preorder Traversal

### ISSUE THREAD

**Issue by kuldeepkhatke** [LeetCode-Feedback/LeetCode-Feedback#3617]
#### Your LeetCode username

kuldeepkhatke

#### Category of the bug
- [ ] Question
- [1] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My solution is correct but giving error on Submitting it. The also run the specific testcase on which it giving the error. It ran successfully but showing wrong out put at the time of submit. Please check below testcase input on which it giving error.
`Input: [1]`

#### Code you used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    l = []
    def preorderTraversal(self, root: TreeNode) -> List[int]:
        # return [root.val, *self.preorderTraversal(root.left), *self.preorderTraversal(root.right)] if root else []
        if root is None:
            return

        self.l.append(root.val)
        if root.left:
            self.preorderTraversal(root.left)
        if root.right: 
            self.preorderTraversal(root.right)   
        return self.l
```

#### Language used for code

Python3

#### Expected behavior

It should be accepted submission.

#### Screenshots

Submission error screenshot link:
https://www.awesomescreenshot.com/image/8571398?key=ed6339ac5fa2c5908de2e7780d19fb5a
Successful run time acceptance screenshot link:
https://www.awesomescreenshot.com/image/8571506?key=f4234144f2fee1264266df111780b168

#### Additional context

Please give some feedback on this asap.

**Comment by lc-kay** [comment]
Hi @kuldeepkhatke 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
