### ISSUE TITLE
Missing Test Case - 709. To Lower Case

### ISSUE THREAD

**Issue by Szymongib** [LeetCode-Feedback/LeetCode-Feedback#3618]
#### Your LeetCode username
Szymongib

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Question https://leetcode.com/problems/to-lower-case/ states the following:
> s consists of printable ASCII characters.

For input as such:
```
Hello@[]
```
The code can modify it to:
```
hello`{}
```
Which does not match the expected answer but the solution is accepted.

#### Code you used for Submit/Run operation

```
// To Lower Case
impl Solution {
    pub fn to_lower_case(s: String) -> String {
        s.chars().map(|c| ((c as u8) | 32) as char).collect()
    }
}
```

#### Language used for code
Rust

#### Expected behavior

The solution should not be accepted as produced result does not match expected answer. Alternatively the description should be adjusted that the string contains only lowercase and uppercase letters.

#### Screenshots

![image](https://user-images.githubusercontent.com/19947566/119329121-2ad1d900-bc85-11eb-82f6-c077859d617d.png)

**Comment by lc-kay** [comment]
Hi @Szymongib 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Szymongib 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
