### ISSUE TITLE
1024. Video Stitching - Incomplete constraints description in Note section

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#362]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
In the "Note" section of the problem the 2nd point is : _0 <= clips[i][0], clips[i][1] <= 100_. 
It should instead be _0 <= clips[i][0] <= clips[i][1] <= 100_.
I verified it by putting an assert() in my code.
Although it's logical that end time should be >= start time for a valid case, the problem constraints don't explicitly mention it.

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
    int videoStitching(vector<vector<int>>& clips, int T) {
        int ed[T];
        fill_n(ed, T, -1);
        
        for(auto& p : clips) {
            int l = p[0], r = p[1];
            assert(l <= r);
            if(l < T) ed[l] = max(ed[l], r);
        }
        
        for(int i = 1; i < T; i++) ed[i] = max(ed[i], ed[i-1]);
        
        int cur = 0, ans = 0;
        while(cur < T) {
            if(ed[cur] <= cur) return -1;
            cur = ed[cur];
            ++ans;
        }
        
        return ans;
    }
};
```

**Expected behavior**
The 2nd point in the Note section should be _0 <= clips[i][0] <= clips[i][1] <= 100_.

**Screenshots**
![image](https://user-images.githubusercontent.com/36921843/82895825-81bda900-9f72-11ea-9818-ffbd28082c1c.png)

**Additional context**
I verified it by putting an assert() in my code.

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
