### ISSUE TITLE
Missing Test Case - 1873. Calculate Special Bonus

### ISSUE THREAD

**Issue by TrevorMcCormick** [LeetCode-Feedback/LeetCode-Feedback#3620]
#### Your LeetCode username
trevormccormick

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug
`Employees` table is already ordered by `employee_id` ascending, so the user does not need to return the result table ordered by `employee_id`

#### Code you used for Submit/Run operation

```
SELECT employee_id,
       CASE WHEN ((employee_id % 2 != 0) AND (name REGEXP '^[^ M]')) THEN salary ELSE 0 END bonus
  FROM Employees
```

#### Language used for code
SQL

#### Expected behavior
Submission failed.

**Comment by lc-kay** [comment]
@TrevorMcCormick For a valid missing test case report, please provide the test case that this code will fail on. Thank you.
