### ISSUE TITLE
Missing Test Case - 1871. Jump Game VII

### ISSUE THREAD

**Issue by unnat404** [LeetCode-Feedback/LeetCode-Feedback#3621]
#### Your LeetCode username

gro0W

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Not all cases are considered in the approach below as shown in the code but it passes all test cases.
Updating the boundaries c1 and c2 as soon as you find a reachable '0' will lead to missing some '0' that is reachable and hence decreasing the reach(/boundaries) to reach the end of string
For example :
**"010011110"
2
5**
Output for code given below is : **false**
Expected Output is           : **true**

Reason:  
Index Sequence to reach the end (0-based indexing) : 0 -> 3 -> 8

#### Code you used for Submit/Run operation

```
// 1871. Jump Game VII
class Solution {
public:
    bool canReach(string s, int minJump, int maxJump) {
        int i=0;
        int j=1;
        set<int>st;
        int n=s.length()-1;
        if(s[n]=='1')
            return false;
        while(j<=n)
        {
            if(s[j]=='0'){
            int c1=i+minJump;
            int c2=min((i+maxJump),n);
            if(c1<=j and j<=c2 )
            {
                i=j;
                int maxi=max(c1,c2);
                if(maxi<=n)
                    st.insert(maxi);
            }
            }
            j++;
        }
        for(auto k:st)
            if(k==n)
                return true;
    
        return 0;
    }
};
```

#### Language used for code

C++

#### Expected behavior

In the code above we simply add each reachable 0 that occurs from the left first and insert it into a set and finally check if the set contains the last index and if it is 0 then the code returns false.
But we update the boundary c1 and c2 as soon as we encounter a 0 from the left .
This forces us to miss some reachable 0's in the current boundary range (between c1 and c2) as we have updated c1 

Therefore the above code is wrong ,BUT , on running we find it gets ACCEPTED. Therefore add the missing test case :
**"010011110"
2
5**

#### Screenshots

![image](https://user-images.githubusercontent.com/53619178/119332165-dbe86b80-bca5-11eb-8f32-a4c43eadb251.png)

**Comment by lc-kay** [comment]
Hi @unnat404 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@unnat404 Our team recently updated the test case set for this problem and your submitted code fails on one of the newly added test case. Therefore, we will not be adding your custom test case. Thank you for your time.
