### ISSUE TITLE
Submission Grading Error - 943. Find the Shortest Superstring

### ISSUE THREAD

**Issue by CELLSecret1121** [LeetCode-Feedback/LeetCode-Feedback#3622]
#### Your LeetCode username
Interstigation

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Some answers are falsely marked correct.

#### Code you used for Submit/Run operation

```
# 943. Find the Shortest Superstring
class Solution:
    def shortestSuperstring(self, words: List[str]) -> str:
        return words
```

#### Language used for code

Python

#### Expected behavior

I expect that this one line code would be rejected as it actually returns a list instead of a string. The returned list does not contain correct information either.

#### Screenshots

<img width="636" alt="Screen Shot 2021-05-24 at 10 46 40" src="https://user-images.githubusercontent.com/49135047/119387107-551f9880-bc7d-11eb-92d0-cafd8c9a7035.png">

#### Additional context

This might be fixed by adding additional test cases, but I think that a complete rework of the grading system is needed.

**Comment by lc-kay** [comment]
Hi @CELLSecret1121 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @CELLSecret1121 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
