### ISSUE TITLE
Example Solution Error 932. Beautiful Array

### ISSUE THREAD

**Issue by cmunigwe** [LeetCode-Feedback/LeetCode-Feedback#3623]
#### Your LeetCode username

cmunigwe

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Example solution produces runtime rror

#### Code you used for Submit/Run operation

```
class Solution:
    def beautifulArray(self, N):
        memo = {1: [1]}
        def f(N):
            if N not in memo:
                odds = f((N+1)/2)
                evens = f(N/2)
                memo[N] = [2*x-1 for x in odds] + [2*x for x in evens]
            return memo[N]
        return f(N)
```

#### Language used for code

Python

#### Expected behavior

Test case:
4

Expected:
[2,1,4,3]

Actual
RecursionError: maximum recursion depth exceeded
  [Previous line repeated 11 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 49 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    evens = f(N/2)
Line 7 in f (Solution.py)
  [Previous line repeated 28 more times]
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)
    odds = f((N+1)/2)
Line 6 in f (Solution.py)

**Comment by lc-kay** [comment]
@cmunigwe The official solution is being accepted. Please provide a screenshot of the issue. 
<img width="728" alt="Screen Shot 2021-05-24 at 2 30 07 PM" src="https://user-images.githubusercontent.com/70870126/119409705-93788000-bc9c-11eb-952a-6c4bbc1d4644.png">

**Comment by cmunigwe** [comment]
<img width="1439" alt="Screenshot 2021-05-24 at 22 36 02" src="https://user-images.githubusercontent.com/16748850/119410373-ab71f300-bce0-11eb-8f92-a885c6af2ed1.png">

**Comment by lc-kay** [comment]
@cmunigwe Please select Python in the language drop down, not Python3. With the right language selected, the code will compile as expected. Thank you for your time.
