### ISSUE TITLE
Missing test case - 843. Guess the Word

### ISSUE THREAD

**Issue by stephgroat** [LeetCode-Feedback/LeetCode-Feedback#3624]
#### Your LeetCode username

stephgroat

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a missing corner case: a simpler solution of just sorting then eliminating the matches passes the submit test cases, but fails this test case.
```
"azzzzz"
["abcdef","acdefg","adefgh","aefghi","afghij","aghijk","ahijkl","aijklm","ajklmn","aklmno","almnoz","anopqr","azzzzz"]
10
```

#### Code you used for Submit/Run operation

```
var findSecretWord = function(wordlist, master) {
  let modWordlist = wordlist;
  modWordlist = modWordlist.sort();
  for (let i=10; i > 0; i--) {
    let wg = modWordlist[0];
    let count = master.guess(wg);
    if (count === wg.length) {
      return;
    }
    modWordlist = modWordlist.filter(w => {
      return (count === match(wg, w));
    });
  }
};

const match = function(w1, w2) {
  let cnt = 0;
  for (let i=0; i<w1.length && i < w2.length; i++) {
    if (w1.charAt(i) === w2.charAt(i)) {
      cnt++;
    }
  }
  return cnt;
}
```

#### Language used for code

JavaScript

#### Expected behavior

When running against that test case specifically it returns wrong answer.
So it should also fail upon submit with that code, but is an accepted solution.

#### Screenshots

![image](https://user-images.githubusercontent.com/12077373/119547735-75298780-bd63-11eb-8eab-0e4ddaad93c3.png)

**Comment by lc-kay** [comment]
Hi @stephgroat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stephgroat** [comment]
Added screenshot

**Comment by lc-kay** [comment]
Hi @stephgroat 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
