### ISSUE TITLE
Mistake in problem 509 solution

### ISSUE THREAD

**Issue by ssinad** [LeetCode-Feedback/LeetCode-Feedback#3625]
#### Your LeetCode username

https://leetcode.com/ssinad/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The complexity of the sixth approach is O(log N) not O(1) because we are raising the golden ratio to the power of N.

#### Additional context

https://leetcode.com/problems/fibonacci-number/solution/

**Comment by lc-kay** [comment]
Hi @ssinad 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
