### ISSUE TITLE
The question misses out a detail and assumes it.

### ISSUE THREAD

**Issue by sudotrigon** [LeetCode-Feedback/LeetCode-Feedback#3627]
#### Your LeetCode username
f1re

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The questions says that you can take a course as long as you have taken all the prerequisites.
But it doesn't say whether we can take the course if we have completed it's prerequisite in the current semester.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

#### Expected behavior

For n=5
[[2,1],[3,1],[4,1],[1,5]]
k=2,

We can complete 2 and 3 in 1 semester.
Then we can complete 4 as well as 1 in the 2nd semester (since acc to question, we can complete 1 if we have completed 2,3 and 4 and it doesn't ask to complete preReq in previous semester).
Then we can complete 5 in 3rd semester.
So ans should be 3 but ans is 4.

#### Screenshots

![image](https://user-images.githubusercontent.com/83594686/119471605-1108c280-bd67-11eb-9af8-66b404e483de.png)

**Comment by lc-kay** [comment]
@sudotrigon Please provide the problem number and title. Thank you.

**Comment by sudotrigon** [comment]
@lc-kay Forgot to mention.
It's **1494. Parallel Courses II**

**Comment by lc-kay** [comment]
Hi @sudotrigon 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sudotrigon 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
