### ISSUE TITLE
429. N 叉树的层序遍历 Typescript提示错误

### ISSUE THREAD

**Issue by PoleStarInTheSky** [LeetCode-Feedback/LeetCode-Feedback#3628]
**你的 LeetCode 用户名**
polestarinthesky

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言

**描述**
429. N 叉树的层序遍历,使用Typescript时，网页编辑器出现了错误的提示。

**你使用的语言**
Typescript

**你提交或者运行的代码**
```
function levelOrder(root: Node | null): number[][] {
	const ans:number[][]=[];
    doLevelOrder(root,0,ans)
    return ans;
};
function doLevelOrder(curr:Node|null,level:number,ans:number[][]):void{
    if(curr){
        ans[level]=ans[level]??[];
        ans[level].push(curr.val);
    curr.children.forEach((item)=>{
        doLevelOrder(item,level+1,ans);
    })
    }
}
```

**期望行为**
`curr` 的类型为 `Node` ，当在编辑器中打出 `curr.` 的时候，应该提示 `val` 、`children` 等属性，但是编辑器中没有提示，而且认为 `curr` 中不存在 `val` `children` 等属性。

**屏幕截图**
![image](https://user-images.githubusercontent.com/57585556/119493992-6064e800-bd93-11eb-855e-738406dc28c3.png)
![image](https://user-images.githubusercontent.com/57585556/119494036-71155e00-bd93-11eb-99e8-c27798e5c64e.png)
![image](https://user-images.githubusercontent.com/57585556/119494103-812d3d80-bd93-11eb-92fe-d705e32c67da.png)

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@PoleStarInTheSky 你好，该问题当前已进行了修复，力扣会定期更新，保障稳定和体验优化。
