### ISSUE TITLE
763. Partition Labels

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#363]
#### Your LeetCode username
habaj

**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Approach 1 Greedy has wrong analysis

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def partitionLabels(self, S):
        last = {c: i for i, c in enumerate(S)}
        j = anchor = 0
        ans = []
        for i, c in enumerate(S):
            j = max(j, last[c])
            if i == j:
                ans.append(i - anchor + 1)
                anchor = i + 1
            
        return ans
```

**Expected behavior**
Space Complexity: O(N)

Space complexity for answer is being considered but it shouldn't be as agreed in #260 
Apart from that the complexity analysis is similar to the analysis as in #356 
So it should be O(1) as there are max 26 distinct entries in the hashmap at any given time

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by leet212** [comment]
Hello @CooperCooperCooper . Any update on this?

**Comment by lc-kate** [comment]
Hi @leet212 ,
Thanks for reaching out. The issue status is currently still in progress. It's taking longer than usual and I am sorry about that.

**Comment by lc-kate** [comment]
Hi @leet212 ,
Good news! We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
