### ISSUE TITLE
题目1846  减小和重新排列数组后的最大元素 测试用例有误

### ISSUE THREAD

**Issue by Justdwiwt** [LeetCode-Feedback/LeetCode-Feedback#3632]
**你的 LeetCode 用户名**
Len_master

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
默认测试用例与实际测试用例不符

**你使用的语言**
scala

**你提交或者运行的代码**
```scala
//1846  减小和重新排列数组后的最大元素
object Solution {
  def maximumElementAfterDecrementingAndRearranging(arr: Array[Int]): Int = {
    val sorted = arr.sorted
    sorted(0) = 1
    var t = 0
    arr.indices.drop(1).foreach(i => if (sorted(i) != sorted(i - 1)) {
      sorted(i) = sorted(i - 1) + 1
      t += 1
    })
    1 + t
  }
}
```

**期望行为**
```
输入          [2,2,1,2,1]
输出          2
预期结果      2
```

**屏幕截图**
本地测试：
![1.png](https://i.loli.net/2021/05/26/z2WuNZBmwsGM1f9.png)
提交测试：
![3.png](https://i.loli.net/2021/05/26/UnN8qXxw4TsSedf.png)
实际测试用例：
![2.png](https://i.loli.net/2021/05/26/LVU79jomYvXsF3O.png)

**额外的上下文**
本地测试通过，在提交测试用例中，测试数据与本地测试数据相同，结果却不符，点击显示详情，可见实际提供的测试用例为`[10, 10000000000000, 100]`，与显示的测试数据不符

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by Justdwiwt** [comment]
我的疑问是测试用例显示的输入数据是`[2,2,1,2,1]`，但实际进行测试的数据是`[10, 10000000000000, 100]`，并且`[10, 10000000000000, 100]`这个数据作为测试用例是否合理

**Comment by feiceh** [comment]
@Justdwiwt 你好，当前题目测试用例问题已更新，ID：Len_master 给予积分奖励，请查收。
