### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by sachuverma** [LeetCode-Feedback/LeetCode-Feedback#3633]
#### Your LeetCode username
anjali-mc

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Large valued test cases are not present 
I changed my code's last variable to 9999 instead of 10001, then it should fail on `[9999,9999,10000,10000]` this test case
but solution was accepted, maybe some test cases are not present

#### Code you used for Submit/Run operation

```
class Solution {
  public:
    int removeDuplicates(vector<int> &nums) {
      int last = 9999, cnt = 0;
      int last_idx = -1;
      for(int i = 0 ; i < nums.size(); i++){
          if(nums[i] != last){
              cnt = cnt + 1;
              last_idx = last_idx + 1;
              nums[last_idx] = nums[i];
          }
         last = nums[i];
      }
      return cnt;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Code should fail, but it is accepted
Large valued test cases are missing

#### Screenshots
![image](https://user-images.githubusercontent.com/43083013/119609647-8df27580-be15-11eb-9a1a-dec41b7fa2d9.png)

**Comment by lc-kay** [comment]
Hi @sachuverma 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sachuverma 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
