### ISSUE TITLE
Incorrect output. All Elements in Two Binary Search Trees

### ISSUE THREAD

**Issue by pratzz** [LeetCode-Feedback/LeetCode-Feedback#3634]
#### Your LeetCode username
Pratima(pratzz)

#### Category of the bug
- **1305. All Elements in Two Binary Search Trees** - Question
- Solution
- Language

#### Description of the bug
Trying to execute the test case via custom test case trial results into the right answer but upon submitting the same test case results into wrong answer.

#### Code you used for Submit/Run operation
```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    
    sortedList = []
    
    def inOrder(self, root: TreeNode):
        if root.left:
            self.inOrder(root.left)
        self.sortedList.append(root.val)
        if root.right:
            self.inOrder(root.right)

    def getAllElements(self, root1: TreeNode, root2: TreeNode) -> List[int]:
        self.inOrder(root1)
        self.inOrder(root2)
        return sorted(self.sortedList)
```

#### Language used for code
Python3

#### Screenshots
![leet bug](https://user-images.githubusercontent.com/10550923/119611434-52a57600-be18-11eb-99b7-dfaf31f57f79.jpeg)

**Comment by lc-kay** [comment]
Hi @pratzz 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
