### ISSUE TITLE
Stone Game VIII - Wrong hint

### ISSUE THREAD

**Issue by yjt98765** [LeetCode-Feedback/LeetCode-Feedback#3636]
#### Your LeetCode username

yjt98765

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hint 2 says "dp[x] = min(dp[y]+sum of all elements up to y) for all y > x", which is not correct.

#### Expected behavior

The correct hint would be "dp[x] = **max**(sum of all elements up to y **-** dp[y]) for all y > x"

#### Additional context

This [solution](https://leetcode.com/problems/stone-game-viii/discuss/1229790/Javascript-Dynamic-Programming-%2B-local-Maxima-%2B-Minimax) explains the method of calculating `dp[i]`

**Comment by lc-kay** [comment]
@yjt98765 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yjt98765 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by yjt98765** [comment]
Thank you for the quick feedback. I can see that it has been updated. However, it is still not correct. You have changed `min` to `max` but did not change the sign of `dp[i]`. Can you investigate it again?

**Comment by lc-kay** [comment]
@yjt98765 Our team has fixed it. Thank you for your time.
