### ISSUE TITLE
Solution not according to problem type #169

### ISSUE THREAD

**Issue by stuti2** [LeetCode-Feedback/LeetCode-Feedback#3637]
#### Your LeetCode username

Stutis2

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question is under the category of bit manipulation and under the solution section there's no solution using bit manipulation.

#### Code you used for Submit/Run operation

```
// Majority Element
class Solution {
public:
    int majorityElement(vector<int>& nums) {
        int number=0,count;
        for(int i=0;i<32;i++) 
        {
            count=0;
            for(int j=0;j<nums.size();j++) 
            {
                if(nums[j]&(1<<i))
                    count++;
            }     
            if(count>(nums.size()/2))
                number+=(1<<i);
        }
        return number;
    }
};
```

#### Language used for code

C++

#### Screenshots

![image](https://user-images.githubusercontent.com/60356387/119651535-bfce0100-be42-11eb-9751-eac04dd28aae.png)

**Comment by lc-kay** [comment]
@stuti2 Thank you for your feedback; I've relayed this to our team to take into consideration. However, it may take some time for the approach to be added. Therefore, I will close this ticket and reopen it if further information is needed. Thank you for your understanding.
