### ISSUE TITLE
Missing Test Case - 1689. Partitioning Into Minimum Number Of Deci-Binary Numbers

### ISSUE THREAD

**Issue by nikunjvinchhi** [LeetCode-Feedback/LeetCode-Feedback#3638]
#### Your LeetCode username

Niks291

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
**- [ ] Missing Test Cases** 

#### Description of the bug

When we provide large value of greater then length 10 the code becomes fails like ["`1234567888888999`"]. But solution got accepted. May be some test cases are not present. 

#### Code you used for Submit/Run operation

```
class Solution {
    public int minPartitions(String n) {        
        int length = Math.min(n.length(), 10);
        int max = n.charAt(0) - 48;
        for (int i = 1; i < length; i++) {
            if (n.charAt(i) - 48 > max) {
                max = n.charAt(i) - 48;
            }
        }
        return max;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

Code should fail when we provide the value ["`1234567888888999`"] and length is greater then 10. But currently solution is getting accepted. Please refer screenshot.

#### Screenshots

![image](https://user-images.githubusercontent.com/11017399/119653755-54396300-be45-11eb-91bb-36d1df2433c9.png)

**Comment by lc-kay** [comment]
@nikunjvinchhi Your solution currently fails on "111111111119". For a valid test case contribution, please provide a test case that will fail an accepted solution. Thank you for your time.

**Comment by nikunjvinchhi** [comment]
I guess someone has added this testcase after this post. Because Yesterday total test cases is 94 and all the testcases are passed as you can see in the attached snapshot. However when I tried today it shows 95 testcases.
