### ISSUE TITLE
Missing Test Case - 1689. Partitioning Into Minimum Number Of Deci-Binary Numbers

### ISSUE THREAD

**Issue by shobhit62** [LeetCode-Feedback/LeetCode-Feedback#3639]
#### Your LeetCode username
user3269Z

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
a test case of kind 1111111111123 is missing where the initial 10 digits don't contribute to the answer. Few of the sample solutions are failing in providing a correct answer for this testcase

#### Code you used for Submit/Run operation

```
public class PolishNotation {
    public static void main(String[] args) {
        PolishNotation polishNotation = new PolishNotation();
        System.out.println(polishNotation.minPartitions("32"));
    }
public int minPartitions(String n) {
        int result = -1;
        for(int i=0;i<n.length();i++){
            System.out.print(n.charAt(i)-'0');
            if(result<n.charAt(i)-'0')
                result = n.charAt(i)-'0';
        }
        return result;
    }
}
```

#### Language used for code
java

#### Expected behavior
the answer should be 2 but a lot of submitted solutions are giving an answer as 1

**Comment by lc-kay** [comment]
@shobhit62 Please provide the submission details link to your code. Thank you.

**Comment by shobhit62** [comment]
https://leetcode.com/submissions/detail/498514865/

**Comment by lc-kay** [comment]
@shobhit62 For a valid testcase contribution, please provide a testcase that will fail the accepted solution. When I ran the test case 1111111111123 with the code, it is accepted.
