### ISSUE TITLE
Description not correct Problem 98

### ISSUE THREAD

**Issue by Arpit0492** [LeetCode-Feedback/LeetCode-Feedback#3640]
#### Your LeetCode username
johri

#### Category of the bug
- [ ] Question

#### Description of the bug
The description is not correct as per test cases given 

#### Code you used for Submit/Run operation
```
// isValidBST
    public boolean isValidBST(TreeNode root) {
        if(root == null)
            return true;
        Stack<TreeNode> stack = new Stack<>();
        TreeNode pre = null;
        while(root!= null || !stack.isEmpty()){
            while(root != null){
                stack.push(root);
                root = root.left;
            }
            
            root = stack.pop();
            if(pre != null && pre.val >= root.val)
                return false;
            pre = root;
            root = root.right;
            
        }
        
        return true;
    }
```

#### Language used for code
Java 

#### Expected behavior
A valid BST is defined as follows:

The left subtree of a node contains only nodes with keys less than the node's key.
The right subtree of a node contains only nodes with keys greater than the node's key.

Instead, it should be

A valid BST is defined as follows:

The left subtree of a node contains only nodes with keys less than or equal to the node's key.
The right subtree of a node contains only nodes with keys greater than or equal to the node's key.

#### Additional context

[](url)

**Comment by lc-kay** [comment]
Hi @Arpit0492 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Arpit0492** [comment]
@lc-kay thanks. Some of the valid test cases evaluated by the judge are [5,1,5], [1,1] which goes against the current description of the problem statement, where a left child and right child can be equal to their respective parent node as well.

**Comment by lc-kay** [comment]
@Arpit0492 Our team has reviewed the statement and concluded that the current version is correct. For further clarifications, please refer to the problem discuss section. Thank you for your time.
