### ISSUE TITLE
Solution: Space complexity using string.toCharArray() method (JAVA) in solution of problem: 1689. Partitioning Into Minimum Number Of Deci-Binary Numbers

### ISSUE THREAD

**Issue by pratikpanchal22** [LeetCode-Feedback/LeetCode-Feedback#3641]
#### Your LeetCode username
pp423

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the solution provided by Leetcode for [this problem](https://leetcode.com/problems/partitioning-into-minimum-number-of-deci-binary-numbers/), string.toCharArray() method is used to convert the input string to a char array:
![image](https://assets.leetcode.com/users/images/693638d6-58a0-4983-b558-e2a4ca9e089f_1622036152.0824442.png)

The space complexity is mentioned as `O(1)`:
![image](https://assets.leetcode.com/users/images/f5d01e45-7f2c-47bb-97ff-bc0a550f7f7c_1622036168.7543108.png)

This is incorrect since this method returns a newly allocated character array of size equal to that of the input string. So, the space complexity should rightly be `O(n)`.

#### Code you used for Submit/Run operation

For the space complexity to be O(1), a different method (such as `String.charAt(i)`) should be used:

```
char max='0';
for(int i=0; i<n.length(); i++){
    max = Math.max(n.charAt(i), max);
}
return max-'0';
```

#### Language used for code

JAVA

#### Expected behavior

The expected space complexity should be `O(n)` since the `string.toCharArray()` method returns a newly allocated character array of size equal to that of the input string `n`. 

#### Screenshots

![image](https://user-images.githubusercontent.com/6437346/119670420-1e20c280-bdf6-11eb-9692-66a57046d509.png)

**Comment by lc-kay** [comment]
Hi @pratikpanchal22 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratikpanchal22 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
