### ISSUE TITLE
Missing Test Case - 1689. Partitioning Into Minimum Number Of Deci-Binary Numbers

### ISSUE THREAD

**Issue by adesormi** [LeetCode-Feedback/LeetCode-Feedback#3642]
#### Your LeetCode username
D3nsk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test cases

#### Code you used for Submit/Run operation

```java
   class Solution {
    public int minPartitions(String n) {
        int length = Math.min(n.length(), 10);
        int max = n.charAt(0) - 48;
        for (int i = 1; i < length; i++) {
            //System.out.println(n.charAt(i) - 48);
            if (n.charAt(i) - 48 > max) {
                max = n.charAt(i) - 48;
            }
        }
        return max;
    }
}
```

#### Language used for code

Java

#### Expected behavior

This code should fail for test case: "11111111119" but it doesn't because the test case doesn't exist.

#### Screenshots

The code fails: 
![image](https://user-images.githubusercontent.com/58448500/119671516-1daa1b00-be3a-11eb-9518-34fe4cc3acf4.png)
But it is an accepted solution: 
![image](https://user-images.githubusercontent.com/58448500/119671654-3a465300-be3a-11eb-9cab-5cf76cd6adff.png)

**Comment by lc-kay** [comment]
@adesormi This test case was added by our team from an earlier contribution. Thank you for your time.
