### ISSUE TITLE
Missing Test Case - 1689. Partitioning Into Minimum Number Of Deci-Binary Numbers

### ISSUE THREAD

**Issue by aly-ab** [LeetCode-Feedback/LeetCode-Feedback#3643]
#### Your LeetCode username

Prince_Ali

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The solution with the lowest runtime for the May 26th challenge only
considers the 10 most significant digits of the number and that
should not produce correct results for strings with a length > 10.
The upper limit of the number of digits is 10^5.

#### Code you used for Submit/Run operation

```
/* This code is not mine. It is the code with the lowest runtime for
today's challenge. */

// Partitioning Into Minimum Number Of Deci-Binary Numbers
class Solution {
    public int minPartitions(String n) {
        int length = Math.min(n.length(), 10);
        int max = n.charAt(0) - 48;
        for (int i = 1; i < length; i++) {
            //System.out.println(n.charAt(i) - 48);
            if (n.charAt(i) - 48 > max) {
                max = n.charAt(i) - 48;
            }
        }
        return max;
    }
}
```

#### Language used for code
Java

#### Expected behavior
When Testing with a string with length > 10, where the maximum
digit occurs beyond the 10th most significant digit, the code provided
should yield an incorrect result; however, the submission is accepted
by LeetCode.

#### Screenshots
code provided has the lowest runtime on leetcode.
![0ms](https://user-images.githubusercontent.com/40543609/119680951-4238cf80-be07-11eb-81fc-4adf488bfc75.png)

numbers could have up to 10^5 digits and the max digit doesn't necessarily
have to be in the first 10.
![constraints](https://user-images.githubusercontent.com/40543609/119680439-cd659580-be06-11eb-84fa-aaf202f0bf1b.png)

running a custom testcase to show where the code provided fails.
![failed_case](https://user-images.githubusercontent.com/40543609/119680510-dce4de80-be06-11eb-86d4-1a10b4b2a710.png)

submission accepted even though it should not be.
![submission_accepted](https://user-images.githubusercontent.com/40543609/119680554-e706dd00-be06-11eb-9a27-71a15705f175.png)

**Comment by lc-kay** [comment]
@aly-ab This solution now fails on the test case "111111111119". Thank you for your time.
