### ISSUE TITLE
Missing Test Case - 1689. Partitioning Into Minimum Number Of Deci-Binary Numbers

### ISSUE THREAD

**Issue by sruthika-b** [LeetCode-Feedback/LeetCode-Feedback#3645]
#### Your LeetCode username

Sruthika_B

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

There is a missed out test case where for obtaining "0" we still need one deci-binary number.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

For "0" testcase, the result "0" is accepted whereas the result must be "1". This test case is not available.

**Comment by lc-kay** [comment]
@sruthika-b For a valid test case, please provide the accepted code that this test case will fail. Once that information is added, I will reopen this ticket. Thank you.
