### ISSUE TITLE
Missing Test Case - 1466. Reorder Routes to Make All Paths Lead to the City Zero

### ISSUE THREAD

**Issue by gautamv95** [LeetCode-Feedback/LeetCode-Feedback#3647]
#### Your LeetCode username
Fusiion

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
A missing test case, for which my solution is wrong, but my solution got accepted.

Test Case: n = 6, connections = [[1,2],[2,3],[4,5],[3,5],[2,0]]
Expected Output: 2

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minReorder(int n, vector<vector<int>>& connections) {
        ios_base::sync_with_stdio(false);cin.tie(nullptr);cout.tie(nullptr);
        int res = 0;
        stack<pair<int, int>> s;
        unordered_set<int> good;
        good.insert(0);
        
        for(int i=0 ; i<n-1 ; i++) {
            if(good.find(connections[i][1]) != good.end()) {
                good.insert(connections[i][0]);
            }
            else if(good.find(connections[i][0]) != good.end()) {
                res++;
                good.insert(connections[i][1]);
            }
            else {
                s.push({connections[i][0], connections[i][1]});
            }
        }
        
        while(!s.empty()) {
            auto t = s.top(); s.pop();
            if(good.find(t.second) != good.end()) {
                good.insert(t.first);
            }
            else if(good.find(t.first) != good.end()) {
                res++;
                good.insert(t.second);
            }
        }
        
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The solution mentioned above should not work with a specific type of test cases however, those test cases are missing from the set.

#### Screenshots
The code fails the given test case

![t1](https://user-images.githubusercontent.com/45149542/119701978-8f9e5680-be72-11eb-91ee-d6445ccba31e.jpeg)
![t2](https://user-images.githubusercontent.com/45149542/119701983-92994700-be72-11eb-9b75-dbab327e0522.jpeg)

But it is accepted

![a1](https://user-images.githubusercontent.com/45149542/119702067-ad6bbb80-be72-11eb-8e1e-19c5877ad492.jpeg)

**Comment by lc-kay** [comment]
Hi @gautamv95 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gautamv95 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
