### ISSUE TITLE
Missing test cases : 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by dipeshsah** [LeetCode-Feedback/LeetCode-Feedback#3648]
#### Category of the bug
- [] Missing Test Cases 

#### Description of the bug
The below code got submitted succesfully, but should fail for the  below scenario

"aaazzb"
3

So if you add this scenario, my code wont get submitted.

#### Code you used for Submit/Run operation

```
int longestSubstring(string s, int k) 
    {
        int n = size(s);
        if(k == 1) return n;
        return helper(s, 0, n-1, k);
    }
    
    int helper(string s, int start, int end, int k)
    {
        int n = end-start+1;
        if(n < k) return 0;

        int count[26];
        std::fill_n(&count[0], 25, 0);
        count[25] = 1;
        
        for(int i = start;i<=end;++i)
        {
            count[s[i]-'a']++;
        }

        for(int j = start; j<=end; ++j)
        {
            auto idx =  s[j] -'a';
            if(count[idx] < k && count[idx] > 0)
            {
                int l = helper(s, start, j-1, k);
                int r = helper(s, j+1, end, k);
                return max(l,r);
            }
        }
        return n;
    }
```

#### Language used for code
 C++ 

#### Expected behavior
Should fail for the following test case 

"aaazzb"
3

**Comment by lc-kay** [comment]
Hi @dipeshsah 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dipeshsah 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. I am unable to find an account with the username eagerToCode nor InviStar. We appreciate your support!

**Comment by dipeshsah** [comment]
https://leetcode.com/_InviStar_/
Leetocde id :  _InviStar_
