### ISSUE TITLE
776.拆分二叉搜索树 Swift语言测试程序有误

### ISSUE THREAD

**Issue by Larrycal** [LeetCode-Feedback/LeetCode-Feedback#3649]
**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言

**描述**
测试用例：
[4,2,6,1,3,5,7]
0
在此测试用例下，正确答案为[[],[4,2,6,1,3,5,7]],既[nil,root]
执行测试程序后，会抛出
`Could not cast value of type 'TreeNode.TreeNode' (0x560f622f54d8) to 'ListNode.ListNode' (0x560f622f5420).`

**你使用的语言**
Swift

**你提交或者运行的代码**
```
func splitBST(_ root: TreeNode?, _ target: Int) -> [TreeNode?] {
        guard let root = root else { return [nil,nil] }
        if root.val == target {
            let right = root.right
            root.right = nil
            return [root,right]
        } else if root.val > target {
            var nodes = splitBST(root.left,target)
            root.left = nodes[1]
            nodes[1] = root
            return nodes
        } else {
            var nodes = splitBST(root.right,target)
            root.right = nodes[0]
            nodes[0] = root
            return nodes
        }
    }
```

**屏幕截图**
![image](https://user-images.githubusercontent.com/13962296/119759191-66191580-beda-11eb-8b5e-b66c7137d8c1.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@Larrycal 你好，该问题当前已进行了修复，力扣会定期更新，保障稳定和体验优化。
