### ISSUE TITLE
Missing Test cases : 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by jasminnasit** [LeetCode-Feedback/LeetCode-Feedback#3650]
#### Your LeetCode username

jasminnasit48

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

The wrong solution accepted because we missed this testcase

```
Input: prices = [9999,10000]
Output: 1
```

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxProfit(int[] prices) {
        int maxProfit = 0;
        int minPrice = 9998;
        for(int i=0; i<prices.length; i++){
            if(prices[i] < minPrice){
                minPrice = prices[i];
            }
            else if(prices[i] - minPrice > maxProfit){
                maxProfit = prices[i] - minPrice;
            }
        }
        return maxProfit;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

Above solution is getting accepted since this test case is not added.
ideally, it should not get accepted.

#### Screenshots

![profit](https://user-images.githubusercontent.com/24349906/119771659-ac22a900-bedb-11eb-93b8-fe10319eb913.PNG)

#### Additional context

submission link : https://leetcode.com/submissions/detail/498857022/

**Comment by lc-kay** [comment]
Hi @jasminnasit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jasminnasit 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
