### ISSUE TITLE
TLE for Python3 (304. Range Sum Query 2D - Immutable)

### ISSUE THREAD

**Issue by mallika-b** [LeetCode-Feedback/LeetCode-Feedback#3651]
#### Your LeetCode username

mallikab

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 3 and 4 are indicated as being acceptable, but TLE values may not be appropriately timed for Python. I believe I coded Approach 3 correctly, but still got a TLE
Before me, raxrb reported on May 21, 2021 1:45 AM that Approach 4 also TLE's in python.

Incidentally, Newest to Oldest ordering of comments is not working as expected. 
Topmost comments I see when choosing that are
 Last Edit: April 2, 2021 1:56 PM
 February 28, 2021 11:25 PM
 January 26, 2021 8:33 AM
Was able to find the newest ones, incl mine, by choosing Best and scrolling down a bit:
mallikab 6 hours ago
jose_miguel May 22, 2021 6:49 PM

#### Code you used for Submit/Run operation

```
// 304. Range Sum Query 2D - Immutable
class NumMatrix:

    def __init__(self, matrix: List[List[int]]):
        num_rows = len(matrix)
        num_cols = len(matrix[0])
        self.row_sums = [[x for x in range(num_cols)] for y in range(num_rows)]
        for i in range(num_rows):
            self.row_sums[i][0] = matrix[i][0]
            for j in range(1,num_cols):
                self.row_sums[i][j] = self.row_sums[i][j-1]+matrix[i][j]
                
    def sumRegion(self, row1: int, col1: int, row2: int, col2: int) -> int:        
        if col1 == 0:
            return sum([self.row_sums[row][col2] for row in range(row1,row2+1)])
        else:
            return sum([self.row_sums[row][col2]-self.row_sums[row][col1-1] for row in range(row1,row2+1)])
```

#### Language used for code

Python3

#### Expected behavior

TLE on Test Case 13

**Comment by lc-kay** [comment]
Hi @mallika-b 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mallika-b 
Thank you for your time. We have updated the time limit to let it pass.  We appreciate your support!
