### ISSUE TITLE
Incorrect space complexity in solution 899. Orderly Queue

### ISSUE THREAD

**Issue by nahimilega** [LeetCode-Feedback/LeetCode-Feedback#3652]
#### Your LeetCode username
archit18221

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Incorrect space complexity analysis in the solution

#### Expected behavior
As clearly evident from the code of solution, for K>1 space complexity is O(1) as it is just sort, and for K = 1, we are only storing the String T which is the temporary string and a string of answer, hence for this case also the space complexity should be O(n) where n is the length of string.

#### Screenshots
![image](https://user-images.githubusercontent.com/42585035/119783896-4dfdc200-beeb-11eb-8725-31f9828eb790.png)

**Comment by lc-kay** [comment]
Hi @nahimilega 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @nahimilega 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
