### ISSUE TITLE
Missing Test Case - 318. Maximum Product of Word Lengths

### ISSUE THREAD

**Issue by yhkim5719** [LeetCode-Feedback/LeetCode-Feedback#3654]
#### Category of the bug
- [ Maximum Product of Word Lengths ]

#### Description of the bug
This is the example 1, ["abcw","baz","foo","bar","xtfn","abcdef"], and the right answer of this example might be 24, which is the product of the length of "abcdef" and "xtfn", which is 6 * 4.

#### Code you used for Submit/Run operation

```
// Maximum Product of Word Lengths
class Solution {
public:
    int maxProduct(vector<string>& words) {
        int res = 0;
        for (int i = 0; i < words.size()-1; i++) {
            for (int j = i+1; j < words.size(); j++) {
                bool check = true;
                for (int k = 0; k < words[i].length(); k++) {
                    bool charSame = false;
                    for (int l = 0; l < words[j].length(); l++) {
                        if (words[i][k] == words[j][l]) {
                            charSame = true;
                            break;
                        }
                    }
                    if (charSame) {
                        check = false;
                        break;
                    }
                }
                if (!check) {
                    int tmp = words[i].length()*words[j].length();
                    res = max(res, tmp);
                }
            }
        }
        return res;
    }
};
```

#### Language used for code
C++

#### Screenshots
[Capture](https://user-images.githubusercontent.com/37958633/119784958-95e8fe80-be83-11eb-8ee3-76ac27d0af9c.PNG)

**Comment by lc-kay** [comment]
@yhkim5719 The problem states that the two worlds do not share common letters. In "abcdef" and "xtfn", 'f' is shared between the two words. I hope this clarifies your doubts and concerns. Thank you for your time.
