### ISSUE TITLE
Missing Test Case - 191. Number of 1 Bits

### ISSUE THREAD

**Issue by MansurKurtov** [LeetCode-Feedback/LeetCode-Feedback#3655]
Hi, my name is Mansur Kurtov,
I sent following soluation in c#:
```
public static int HammingWeight(uint n)
        {
            var p = 0;
            while (n != 0)
            {
                var m = n % 10;
                if (m == 1) p++;
                n = n / 10;
            }
            return p;
        }
```
But get this wrong reponse:
Input: 00000000000000000000000000001011
Output: 2
Expected:3

In Vusual Studio i test this input value and get 3 

Thanks

**Comment by lc-kay** [comment]
@MansurKurtov Please provide the submission details link. Thank you.

**Comment by lc-kay** [comment]
Hi @MansurKurtov 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
