### ISSUE TITLE
Missing Test Case - 1410. HTML Entity Parser

### ISSUE THREAD

**Issue by sumitkushwaha1999** [LeetCode-Feedback/LeetCode-Feedback#3656]
#### Your LeetCode username
<devesh_kumar1234>

#### Category of the bug
Missing Test Cases 
"&&&amp;" 
"&&&amp&&amp;" 
"&&&;" 

#### Description of the bug
Some test cases are missing due to which wrong solutions are also accepted. 

#### Code you used for Submit/Run operation
Below Code gives Accepted but it's wrong.
```
//1410. HTML Entity Parser
class Solution {
public:
    string entityParser(string s) {
        unordered_map<string,string> mp;
        if(s=="&&gt;")
            return "&>";
        mp["quot"]="\"";
        mp["apos"]="'" ;
        mp["amp"]="&";
        mp["gt"]=">";
        mp["lt"]="<";
        mp["frasl"]="/";
        string res="";
        int n=s.size();
        for(int i=0;i<n;i++){
            if(s[i]!='&'){
                res.push_back(s[i]);
            }
            else{
                i++;
                //res.push_back('&');
                string key="";
                while(s[i]!=';'&&s[i]!='&')
                {
                    key.push_back(s[i]);
                    i++;
                }if(mp.find(key)!=mp.end())
                res+=mp[key];
                else
                    {res.push_back('&');res+=key;res.push_back(';');}
            }
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior
=
If char '&' appears then its next element must be checked based upon condition. But there is only one test case for this, which weakens the problem solution.

#### Screenshots

![image](https://user-images.githubusercontent.com/65592968/119824675-c8dad300-bf13-11eb-9107-c63aa783bdf7.png)

#### Additional context
No other bugs.
Need to add more Testcases like 
1. "&&amps;"
2. "&&&amplt;"

**Comment by lc-kay** [comment]
Hi @sumitkushwaha1999 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sumitkushwaha1999 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
