### ISSUE TITLE
Missing Test Case - 686. Repeated String Match

### ISSUE THREAD

**Issue by cicihou** [LeetCode-Feedback/LeetCode-Feedback#3657]
#### Your LeetCode username

ccc_code

#### Category of the bug
Missing Test Cases 

#### Description of the bug

missing testcase

#### Code you used for Submit/Run operation

```
class Solution:
    def repeatedStringMatch(self, a: str, b: str) -> int:
        if b in a:
            return 1

        # this line could help it run more fast, but actually it should not work
        # need a testcase like a = "dbeg", b = "egb"
        if set(a) != set(b):
            return -1  
        tmp = a
        count = 1
        for i in range(len(a) + len(b)):
            if b in a:
                return count
            a += tmp
            count += 1

        return -1

```

#### Language used for code

python

#### Expected behavior

```
        # this line could help it run more fast, but actually it should not work
        # need a testcase like a = "dbeg", b = "egb"
        if set(a) != set(b):
            return -1  
```

#### Screenshots

the code can pass
![image](https://user-images.githubusercontent.com/41445818/119834862-e79c9200-bf32-11eb-87aa-75885c2d084d.png)

it's not true when I test
![image](https://user-images.githubusercontent.com/41445818/119835596-8de89780-bf33-11eb-88dd-ae319cdfac6c.png)

**Comment by lc-kay** [comment]
Hi @cicihou 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cicihou 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
