### ISSUE TITLE
Number within range should be processed but test case expects 0

### ISSUE THREAD

**Issue by carlospalmaroldan** [LeetCode-Feedback/LeetCode-Feedback#3658]
#### Your LeetCode username

carlospalma03

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Given an input within the expected range the solution in the test case is 0. This should only happen when the input exceeds this range.
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public int reverse(int x) {
        if(x > 2147483647 || x < -2147483648){
            return 0;
        }
        int[] powers = {1,10,100,1000,10000,100000,1000000,10000000,100000000,1000000000};
        List<Integer> digits = new ArrayList<>();
        boolean digitFound = false;
        for(int i = 9; i > 0; i--){
            int digit;
            if(i==9){
                digit = x/powers[i];
                if (digit != 0) {
                    digits.add(digit);
                }
            }
            digit = (x%powers[i])/powers[i-1];
            if(digit != 0 || digitFound){
                digits.add(digit);
                digitFound = true;
            }
        }

        int partial = 0;
        for(int j= digits.size()-1; j>=0; j--){
            partial = partial + digits.get(j)*powers[j];
        }

        return partial;
    }
}
```

#### Expected behavior

Any number between -2exp(31) and 2exp(31)-1 should be processed

#### Screenshots

![image](https://user-images.githubusercontent.com/21181510/119851178-d1131e00-bed3-11eb-9ddd-70415b887de4.png)
However 
![image](https://user-images.githubusercontent.com/21181510/119851241-dc664980-bed3-11eb-94c0-ada02bea7fe9.png)
The input in the test case is withinthe range that should be processed

**Comment by lc-kay** [comment]
@carlospalmaroldan Please provide the problem number and title. Thank you.

**Comment by lc-kay** [comment]
Hi @carlospalmaroldan 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
