### ISSUE TITLE
题目提交- 内部出错

### ISSUE THREAD

**Issue by 1582-yumi** [LeetCode-Feedback/LeetCode-Feedback#366]
** Bug 类型**
- 题解

**描述**
每道题都提交都返回“内部出错”的error 

**你使用的语言**
MSSQL

**你提交或者运行的代码**
不管新写的代码，还是之前已经提交通过的代码，提交都显示“内部错误”

**期望行为**
尽快修复啊

**屏幕截图**
![image](https://user-images.githubusercontent.com/62852767/83002852-74053380-a005-11ea-9a89-e91f9d40afc7.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，请按照本文中提到的格式提供一下题号和分享上述代码，把信息提供完整才能有助于快速验证和精准的定位问题哟。

**Comment by 1582-yumi** [comment]
我SQL里面所有题目都是这个报错，举个例子吧：
569. 员工薪水中位数
MSSQL环境下运行的：

select id, company, salary
from (select *, row_number() over(partition by company order by salary ASC, id ASC) as rowasc,
     row_number() over(partition by company order by salary DESC, id DESC) as rowdesc from Employee) as temp
where rowasc in (rowdesc, rowdesc-1, rowdesc+1)
order by company, salary

**Comment by feiceh** [comment]
您好，该问题已修复，请稍后刷新网页再试试，感谢您对力扣的支持～
