### ISSUE TITLE
Issue with notes and Notebook

### ISSUE THREAD

**Issue by sidhant-khamankar** [LeetCode-Feedback/LeetCode-Feedback#3660]
#### Your LeetCode username

Sid_Khamankar

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

While Writing Notes for a question, its good that it gets automatically saved but the write pointer gets reset to starting position of note and everytime I have to bring it back to the end of the sentence that I was writing.

Also Notes Preview on problem page i.e non code sentences with end of lines does not match with the preview on My Notebook. Notebook eliminates the end of line character for non code text and does not follow formatting that was given while writing the note.

#### Expected behavior

The writing pointer should not get reset to starting position of note. Leave it where it was for appending new sentences.
The Notebook's preview should match with the preview shown on individual problem's note

**Comment by lc-kay** [comment]
@sidhant-khamankar I've relayed this issue to our team to investigate. However, we encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). For site issues, please reach out to us through https://leetcode.com/supportThank you again for your support and understanding.
