### ISSUE TITLE
Space Complexity Description: Maximum Erasure Value

### ISSUE THREAD

**Issue by Asayu123** [LeetCode-Feedback/LeetCode-Feedback#3661]
#### Your LeetCode username
Asayu123

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

**Summary**

Regarding : https://leetcode.com/problems/maximum-erasure-value/solution/
I think the description regarding space complexity of Approach 2 is wrong. (2021/05/28)

**Detail**
> Let n be the length of array nums.
> Space Complexity: O(n), as we are using a set to track all the unique elements. In the worst case, if all the array elements are unique, the set would grow up to size n.

Since set does not allow duplication, its maximum size is limited to the number of unique elements, and the input range is limited to
> 1 <= nums[i] <= 10^4

So the space complexity is O(10^4) , and identical to Approach 3 that uses Boolean Array which is marked as O(1).

#### Code you used for Submit/Run operation

```
class Solution:
    def maximumUniqueSubarray(self, nums: List[int]) -> int:
        LEN = len(nums)      
        curr_set = set()
        i, j = 0, 0
        curr_set.add(nums[0])
        max_score = nums[0]
        curr_sum = nums[0]

        while j < (LEN-1):
            next_num = nums[j+1]
            if next_num not in curr_set:
                j += 1
                curr_set.add(next_num)
                curr_sum += next_num
                max_score = max(max_score, curr_sum)
            else:
                left_most_num = nums[i]
                i += 1
                curr_set.remove(left_most_num)
                curr_sum -= left_most_num
        return max_score
```

#### Language used for code

Python3

**Comment by lc-kay** [comment]
Hi @Asayu123 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Asayu123 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
