### ISSUE TITLE
One of the C++ solutions for Maximum erasure value is not compliant with the C++ standard.

### ISSUE THREAD

**Issue by vittorio-patriarca** [LeetCode-Feedback/LeetCode-Feedback#3662]
In the solutions 5 and 6 of [Maxumum erasure value](https://leetcode.com/problems/maximum-erasure-value/solution/), the C++ code contains the following lines:
``` cpp
int n = nums.size();
int prefixSum[n + 1];
```
This code is not compliant with any of the C++ standards. The use of the VLA is supported by some compilers as an extension. It also puzzles me the fact that, in solution 6, the `prefixSum` is a VLA but the `lastIndexes` is a `std::vector`.

I suggest changing it from
``` cpp
int prefixSum[ n + 1 ];
```
to
``` cpp
vector< int > prefixSum( n + 1 );
```

**Comment by lc-kay** [comment]
@vittorio-patriarca 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vittorio-patriarca 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
