### ISSUE TITLE
Missing Input Constraint - 241. Different Ways to Add Parentheses

### ISSUE THREAD

**Issue by Bambooin** [LeetCode-Feedback/LeetCode-Feedback#3663]
#### Your LeetCode username
0x4C0DE

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
We should make it clear that test case start with '+' or '-' is invalid test case.

**Expression must start with number and is a valid expression.**

The input is invalid, but the expected output is [].
- "-1+1+1"
- "+1+1+1"

#3045 is another discussion about this issue.

 Adding new test case breaks the solution, but we can add constraint to avoid it.

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
