### ISSUE TITLE
LeetcodeId provided for the points for adding new testcase

### ISSUE THREAD

**Issue by dipeshsah** [LeetCode-Feedback/LeetCode-Feedback#3666]
Leetcode Id : \_InviStar_
https://leetcode.com/_InviStar_/
--------------------
Hi @dipeshsah 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. I am unable to find an account with the username eagerToCode nor InviStar. We appreciate your support!

_Originally posted by @lc-kay in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/3648#issuecomment-850568524_
--------------------------------------------------

**Comment by lc-kay** [comment]
Hi @dipeshsah 
Thank you for your time. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
