### ISSUE TITLE
Wrong Parameter in Problem rotate-array (Golang)

### ISSUE THREAD

**Issue by nipeharefa** [LeetCode-Feedback/LeetCode-Feedback#3667]
#### Your LeetCode username
nipeharefa

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The default sample void  is :
```go
func rotate(nums []int, k int)  {
    
}
```
i think `nums` paramter is pointer array, because need passing reference to modified the array. Should be: 
```go
func rotate(x *[]int, k int) {
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/12620257/120038270-2f9fdf80-c02d-11eb-8be3-6a581eb20dab.png)

**Comment by lc-kay** [comment]
Hi @nipeharefa 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@nipeharefa Our team has reviewed this report and ruled it invalid. Please refer to the Go submissions in the problem discuss section posted by other users. Thank you for your time.
