### ISSUE TITLE
542. 01 Matrix - Missing Test Case

### ISSUE THREAD

**Issue by Chirag-Shilwant** [LeetCode-Feedback/LeetCode-Feedback#3669]
#### Your LeetCode username

chirags_30

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 
[[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[0,0,0]]

#### Description of the bug

The current test cases are weak and my BFS solution without using visited map/array for co-ordinates is Accepted by the platform.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int R, C;
    
    int bfs(int row, int col, vector<vector<int>>& matrix)
    {
        queue<pair<int,pair<int,int>>>Q;
        
        Q.push({0, {row, col}});
        
        while(!Q.empty())
        {
            auto it = Q.front();
            
            int dist = it.first;
            
            int x = it.second.first, y = it.second.second;
            
            Q.pop();
            
          
            if(x<0 or y<0 or x>=R or y>=C) continue;
            
            if(matrix[x][y] == 0)
                return dist;
            
            Q.push({dist+1, {x-1, y}});
            Q.push({dist+1, {x+1, y}});
            Q.push({dist+1, {x, y-1}});
            Q.push({dist+1, {x, y+1}});
        }
        
        return 0;
    }
    
    vector<vector<int>> updateMatrix(vector<vector<int>>& matrix) {
        
        R = matrix.size();
        C = matrix[0].size();
        vector<vector<int>> ans(R, vector<int>(C,0));
        
        for(int row=0; row< R; row++)
        {
            for(int col =0; col < C; col++)
            {
                if(matrix[row][col])
                    ans[row][col] = bfs(row, col, matrix);
            }
        }
        
        return ans;
        
    }
};

```

#### Language used for code
C++

#### Expected behavior

Expected behavior is TLE and we are getting it when we run the above missing TC via Custom Test case option. The test case added was,

[[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[0,0,0]]

![image](https://user-images.githubusercontent.com/48115585/120063113-36594180-c083-11eb-9ed8-ff413211e45c.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/48115585/120063368-81c01f80-c084-11eb-90bd-bacdfc51ef1f.png)

As you can see in the above image the code is Accepted by the platform as this test case is missing.

**Comment by lc-kay** [comment]
Hi @Chirag-Shilwant 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Chirag-Shilwant 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
