### ISSUE TITLE
478. Generate Random Point in a Circle

### ISSUE THREAD

**Issue by SeyhmusGuler** [LeetCode-Feedback/LeetCode-Feedback#367]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [x] language

**Describe the bug**
The question asks to write a function that generates random numbers in a circle. This language should be changed to generate random numbers in a "disk". Or it could be changed to " _on and inside_ the circle". With its current state, the statement is confusing and in the circle may just mean in the circle (somewhere on the circle, not inside). 

**what language is your code written in**
Python3

**The code you submit/run**
```
import random, math
class Solution:

    def __init__(self, radius: float, x_center: float, y_center: float):
        self.xc = x_center
        self.yc = y_center
        self.r = radius
        

    def randPoint(self) -> List[float]:
        angle = float(2 * math.pi * random.random())
        rad = float(self.r * math.sqrt(random.random()))
        return [self.xc + rad * math.cos(angle), self.yc + rad * math.sin(angle)]
```

**Expected behavior**
The code runs fine and the result is accepted.

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @SeyhmusGuler ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @SeyhmusGuler ,
Thank you for your time. The third point of the[ problem description](https://leetcode.com/problems/generate-random-point-in-a-circle/), "a point on the circumference of the circle is considered to be in the circle" should clarify the doubt. We appreciate your support.
