### ISSUE TITLE
Missing Test Case / Judge is wrong - 362. Design Hit Counter

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#3670]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Last 5 mins from timestamp must not change for same timestamp (300), just because we asked for a different timestamp (301)

#### Code you used for Submit/Run operation

```
class HitCounter {
    m = new Map();

    constructor() {}

    hit(ts) {
        this.m.set(ts, this.m.has(ts) ? this.m.get(ts) + 1 : 1);
        return null;
    }

    getHits(ts) {
        let tsFrom = ts - 300 + 1 < 0 ? 1 : ts - 300 + 1;
        let sum = 0;
        for (let t = tsFrom; t <= ts; t++) {
            sum += this.m.has(t) ? this.m.get(t) : 0;
        }
        return sum;
    }
}
```

#### Language used for code
JavaScript

#### Expected behavior

#1
The expectation is different for the same question - this is wrong.
The number of hits in the past 5 minutes from 300 timestamp is giving a different number once we ask for 301 timestamp.

#2
Solution given is wrong too for same reason - `pop` looses data - https://leetcode.com/problems/design-hit-counter/solution/

#### Screenshots

![Screenshot (422)](https://user-images.githubusercontent.com/8236389/120068639-4ed75500-c09f-11eb-953e-14a1e717bfca.png)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@manoharreddyporeddy We have fixed the bug in the validator. Thank you for your time.
