### ISSUE TITLE
Wrong formula in 217 solution

### ISSUE THREAD

**Issue by Gaebrie** [LeetCode-Feedback/LeetCode-Feedback#3671]
#### Your LeetCode username

gaebrie5

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the solution for the problem we use the formula n (n +1) / 2 to find the number of pairs in an array, but i think
 the correct formula is n (n -1) / 2

#### Screenshots

![Cattura1](https://user-images.githubusercontent.com/40518112/120072026-05ccd400-c092-11eb-8123-07ae409fee6e.PNG)

**Comment by lc-kay** [comment]
Hi @Gaebrie 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Gaebrie 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
