### ISSUE TITLE
Missing Test Case - 620. Not Boring Movies

### ISSUE THREAD

**Issue by arpitanaganur96** [LeetCode-Feedback/LeetCode-Feedback#3672]
#### Your LeetCode username

arpitanaganur

#### Category of the bug
- 620 Question
- [ ] Solution
- Oracle Language
- {"headers":{"cinema":["id", "movie", "description", "rating"]},"rows":{"cinema":[[1, "War", "great 3D", 8.9], [2, "Science", "fiction", 8.5], [3, "irish", "Boring", 6.2], [4, "Ice song", "Fantacy", 8.6], [5, "House card", "Interesting", 9.1]]}} 

#### Description of the bug

The problem lies with the case where the description is 'Boring' and not 'boring'. The screenshot explains the problem. However, when I submit the query, the submission is accepted. Please look into this issue and correct it.

#### Code you used for Submit/Run operation

```Select * from Cinema where mod(id,2)!=0 and description != 'boring' order by rating desc```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
<!-- C++ -->
Oracle sql

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
![image](https://user-images.githubusercontent.com/68826721/120072870-cedfc980-c063-11eb-94f5-3c5b5c91c91f.png)



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
Hi @arpitanaganur96 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@arpitanaganur96 Our team has decided not to add this test case because it needs special handling for the oracle solutions while it is ok for MySQL and mssql. Thank you for your understanding.
