### ISSUE TITLE
Wrong test case output -403. Frong Jump question

### ISSUE THREAD

**Issue by Spartannaman** [LeetCode-Feedback/LeetCode-Feedback#3673]
In question no. 403 Frog Jump, the test cases which the compiler use to execute the program has the wrong output feeded because of which my code which was correct was marked as a wrong answer.
The output of 1st input sequence should be 'false' instead of 'true'
Question link:[https://leetcode.com/problems/frog-jump/](url)

**Comment by lc-kay** [comment]
@Spartannaman Please provide your submission details link and why you think the output should be false. Thank you.

**Comment by lc-kay** [comment]
Hi @Spartannaman 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
