### ISSUE TITLE
Missing Test Case - 733. Flood Fill

### ISSUE THREAD

**Issue by ritegarg** [LeetCode-Feedback/LeetCode-Feedback#3679]
#### Your LeetCode username
ninja_rg

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The test cases where original and new color are same gives a runtime error for when same color elements are enclosing the starting element.

#### Code you used for Submit/Run operation

```
class Solution {
    private static final int[][] DIRECTIONS = {{1,0}, {-1,0}, {0,1}, {0,-1}};
    
    public int[][] floodFill(int[][] image, int sr, int sc, int newColor) {
        int original = image[sr][sc];
        image[sr][sc] = newColor;
        helper(image,sr, sc, newColor, original);
        return image;
    }
    
    private void helper(int[][] image, int sr, int sc, int newColor, int original) {
        for(int[] direction: DIRECTIONS) {
            int newr = sr + direction[0];
            int newc = sc + direction[1];
            if(newr < 0 || newr > image.length-1 || newc < 0 || newc > image[0].length-1 || image[newr][newc] != original || image[newr][newc] == newColor) {
                continue;
            }
            image[newr][newc] = newColor;
            helper(image,newr, newc, newColor, original);
        } 
    }
}
```

#### Language used for code
Java

#### Expected behavior
Code should not be accepted

#### Screenshots
N/A

#### Additional context
Missing Test Case
[[0,0,0],[0,1,1][1,1,1]]
1
1
1

**Comment by lc-kay** [comment]
@ritegarg [[0,0,0],[0,1,1][1,1,1]] is not a valid value of type integer[][], therefore, it is an invalid testcase and will not be added. Thank you for your time.
