### ISSUE TITLE
Missing Test Case - 1882. Process Tasks Using Servers

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#3681]
#### Your LeetCode username

archit91

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:
[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6565696/input.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
	vector<int> assignTasks(vector<int>& servers, vector<int>& tasks) {
		int n = servers.size(), m = tasks.size(), i, j, k, t, id;
		set<pair<int, int>> avail, q;
		set<pair<int, int>>::iterator it;
		for (i = 0; i < n; i++) avail.insert({ servers[i], i });
		vector<int> ans(m, -1);
		t = 0;
		for (i = 0; i < m; i++) {
			if (t < i) t = i;
			while (avail.empty() || (!q.empty() && (q.begin()->first <= i))) {
				t = q.begin()->first;

				while (!q.empty() && (q.begin()->first == t)) {
					id = q.begin()->second;
					q.erase(q.begin());
					avail.insert({ servers[id], id });
				}
			}
			id = avail.begin()->second;
			avail.erase({ servers[id], id });
			ans[i] = id;
			q.insert({ t + tasks[i], id });
		}
		return ans;
	}
};
```

#### Language used for code

C++

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/40712852/120092128-601b7280-c12e-11eb-991f-9ddbb2c13b90.png)

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
