### ISSUE TITLE
5775. 准时抵达会议现场的最小跳过休息次数.数据范围不符

### ISSUE THREAD

**Issue by chiyu1996** [LeetCode-Feedback/LeetCode-Feedback#3684]
**你的 LeetCode 用户名**
chiyu1996

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目显示：
n == dist.length
1 <= n <= 1000
1 <= dist[i] <= 10^5
1 <= speed <= 10^6
1 <= hoursBefore <= 10^7
有一组数据：
[1,1,1,1,1]
10000000
1
并且将其输入以后：
expected 'speed' to have value from 1 to 1000000 only
**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
![image](https://user-images.githubusercontent.com/18342366/120094941-c36ccb00-c155-11eb-8b76-310b26e6cfd4.png)
![image](https://user-images.githubusercontent.com/18342366/120094948-cb2c6f80-c155-11eb-83f7-ade9b6278eb2.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
@feiceh Please provide the problem title and number from the site.

**Comment by feiceh** [comment]
@lc-kay 题目是1883. 准时抵达会议现场的最小跳过休息次数

**Comment by lc-kay** [comment]
@feiceh The team has previously identified this issue and resolved it.
