### ISSUE TITLE
Problem Statement - 1782. Count Pairs Of Nodes

### ISSUE THREAD

**Issue by yash30201** [LeetCode-Feedback/LeetCode-Feedback#3685]
#### LeetCode username
yash30201

#### Category of the bug
- [- ] Language

#### Description of the bug
It's not a bug! 
I really liked this question and how it utilised multiple concepts but upon seeing the comments of people(a greater number of people) who were not happy with the problem statement, I went through all the comments and deduced that just putting a heading beside the *Example1*, before the table, stating that - *Look at all the possible pairs in example 1 in this table* will solve this confusion for nearly all of them.

Why I think this will work is that many people are getting confused by thinking that the table's 1st column are the edges themselves instead of just pairings.

#### Code you used for Submit/Run operation

```
// Two Sum
/*
Steps - 
    For each q : queries - 
        -> calculate number of pairs(x, y) such that deg[x] + deg[y] > q
        -> subtract the number of pairs for which deg[x] + deg[y] - common[(x, y)] <= q && deg[x]+deg[y]>k
*/
class Solution {
public:
    vector<int> countPairs(int n, vector<vector<int>>& edges, vector<int>& queries) {
        vector<int> degree(n+1) ,ans, pos(n+1);
        unordered_map<int,int> mp;
        iota(pos.begin(), pos.end(), 0);
        auto get = [](int &ax, int &bx){
            if(ax > bx) swap(ax, bx);
            return ax + 20001*bx;
        };
        for(auto &v : edges){
            degree[v[0]]++, degree[v[1]]++;
            mp[get(v[0], v[1])]++;  
        }
        sort(pos.begin(), pos.end(), [&](int &cmpx, int &cmpy){
            return degree[cmpx] < degree[cmpy];
        });
        int res = 0, l, r, fi, se;
        for(int &q :queries){
            res = 0, l = 1, r = n;
            while(l < r){
                if(degree[pos[l]] + degree[pos[r]] > q){
                    res += (r - l);
                    r--;
                }
                else l++;
            }
            for(auto &p : mp){
                fi = p.first/20001, se = p.first%20001;
                if(degree[fi] + degree[se] > q && degree[fi] + degree[se] - p.second <= q) res--;
            }
            ans.emplace_back(res);
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

NA

#### Screenshots

NA

#### Additional context

NA

**Comment by lc-kay** [comment]
Hi @yash30201 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yash30201 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
