### ISSUE TITLE
Missing Test Case - 164. Maximum Gap

### ISSUE THREAD

**Issue by vipray** [LeetCode-Feedback/LeetCode-Feedback#3686]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test cases are not enough to eliminate codes with non-linear complexity. Code with complexity O(nlogn) is also getting "Accepted".

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int maximumGap(vector<int>& nums) {
        if(nums.size()<=1){
            return 0;
        }
        
        sort(nums.begin(), nums.end());
        int maxi = -1;
        for(int i=1;i<nums.size();i++){
            if(maxi< abs(nums[i-1]-nums[i])){
                maxi = abs(nums[i-1]-nums[i]);
            }
        }
        return maxi;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Currently, code with Non-linear complexity {O(nlogn)} is also getting "Accepted".

**Comment by lc-kay** [comment]
@vipray For a valid testcase contribution, please provide missing testcases that will fail this solution. Thank you.

**Comment by vipray** [comment]
@lc-kay The question states "You must write an algorithm that runs in linear time and uses linear extra space."
But the algo, I mentioned above is of non linear time complexity and Leetcode is accepting it as valid solution.

So either the test cases are not strong enough to eliminate such codes or time complexity is not defined correctly.

Summary: This above code should not get accepted but it is getting accepted on leetcode

**Comment by lc-kay** [comment]
@vipray Our team has reviewed your report and concluded that it is technically nearly impossible to differentiate between O(n) and O(nlog(n)) as log(n) = 20 which can be considered as a constant here. I hope this clarifies any doubts or concerns. Thank you for your time.
