### ISSUE TITLE
Missing Test Case - 769. Max Chunks To Make Sorted

### ISSUE THREAD

**Issue by blackdog1520** [LeetCode-Feedback/LeetCode-Feedback#3687]
#### Missing Test Cases
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

[5,4,2,3,0,1]
#### 

```
 Not written yet.
```

#### Screenshots
![leetcodeissue](https://user-images.githubusercontent.com/45413104/120106040-173cdb80-c179-11eb-88f1-e4f5959c9977.png)

**Comment by lc-kay** [comment]
@blackdog1520 Please raise this question in the problem discuss section. Thank you for your time.
