### ISSUE TITLE
Missing Test Case - 785. Is Graph Bipartite?

### ISSUE THREAD

**Issue by k0adarsh** [LeetCode-Feedback/LeetCode-Feedback#3688]
#### Your LeetCode username

k0adarsh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

My solution has been accepted but there's a test case where my solution gives wrong output.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkBip(int x, vector<vector<int>>& graph, vector<int> &vis, vector<int> &col)
    {
        if(vis[x])
            return true;
        int parCol = col[x],ch;
        vis[x] = 1;
        int i,len = graph[x].size();
        for(i=0;i<len;i++)
        {
            ch = graph[x][i];
            if(vis[ch] == 1 && col[ch] == col[x])
                return false;
            if(!vis[ch])
            {
                col[ch] = (col[x] == 1 ? 2 : 1);
                if(!checkBip(ch,graph,vis,col))
                    return false;
            }
        }
        return true;
    }
    bool isBipartite(vector<vector<int>>& graph) {
        
        int n = graph.size(),i;
        if(n <= 2)
            return true;
        
        bool flag = true;
        vector<int> vis(n,0);
        vector<int> col(n,0);
        
        col[0] = 1;
        for(i=0;i<n;i++)
        {
            if(!vis[i])
            {
                flag = checkBip(i,graph,vis,col);
                if(flag == false)
                    return false;
            }
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution shouldn't be accepted as for TEST CASE : [[1],[0],[3,4],[2,4],[2,3]] it gives wrong answer.
When I run the solution for the same test case on custom input it shows the wrong answer.
Check the provided Screenshot. The same solution has been accepted but gives the wrong output on provided input.

#### Screenshots

![Screenshot (429)](https://user-images.githubusercontent.com/38538532/120110326-a4d4f700-c18a-11eb-8677-b31d3cda18b7.png)

**Comment by lc-kay** [comment]
Hi @k0adarsh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @k0adarsh 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
