### ISSUE TITLE
Missing Test Case - 709. To Lower Case

### ISSUE THREAD

**Issue by jasminnasit** [LeetCode-Feedback/LeetCode-Feedback#3689]
#### Your LeetCode username

jasminnasit48

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

The wrong solution accepted because we missed this test case
```
input : "Hello_"
output : "hello_"
```
#### Code you used for Submit/Run operation

```
class Solution {
public:
    string toLowerCase(string s) {
     for(int i=0;i<=s.size();i++) { 
     
      if((s[i]>=65 && s[i]<=90) || s[i] == '_')
      {
	     s[i]=s[i]+32;
      }
         
   }
        return s;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Above solution is getting accepted since this test case is not added.
ideally, it should not get accepted.

#### Screenshots

![2](https://user-images.githubusercontent.com/24349906/120111055-f468f200-c18d-11eb-8a38-879553a64213.PNG)

#### Additional context

submission link : https://leetcode.com/submissions/detail/500433074/

**Comment by lc-kay** [comment]
Hi @jasminnasit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jasminnasit Our team didn't consider this test case because this solution has a special condition that makes it fail for this test case. Thank you for your time.
