### ISSUE TITLE
Add a testcase for "886. Possible Bipartition"

### ISSUE THREAD

**Issue by nefigtut** [LeetCode-Feedback/LeetCode-Feedback#369]
**What kind of the bug**
- [x] problem
- [x] problems's testcase
- [ ] solution
- [ ] language

**Describe the bug**
Testcases for 886. Possible Bipartition ( https://leetcode.com/problems/possible-bipartition/description/ ) does not cover all cases. My solution ( https://leetcode.com/submissions/detail/345446208/ ) was accepted, while there is a test case where it must fail. If the testcase I suggest below was present, my (incorrect) solution wouldn't be accepted.

**what language is your code written in**
Python 3

**The code you submit/run**
```
class Solution:
    def possibleBipartition(self, N, dislikes):
        if N < 3: return True
        if len(dislikes) < 3: return True
        ds = [ [ None, None ] for i in range(N+1) ]
        for a, b in dislikes:
            if ds[a][0]:
                if ds[b][0]:
                    if a in ds[b][0] or b in ds[a][0]:
                        return False
                else:
                    oppo = ds[a][1]
                    oppo.add(b)
                    ds[b][0] = oppo
                    ds[b][1] = ds[a][0]
            else:
                if ds[b][0]:
                    oppo = ds[b][1]
                    oppo.add(a)
                    ds[a][0] = oppo
                    ds[a][1] = ds[b][0]
                else:
                    ds[a][0] = set([ a ])
                    ds[b][0] = set([ b ])
                    ds[a][1] = ds[b][0]
                    ds[b][1] = ds[a][0]
        return True
```

**The testcase I suggest to add**
```
Input: N = 4
dislikes =  [[1,2],[3,4],[1,3],[1,4]]
Output: false
```

**Current behavior**
My incorrect solution above was accepted.

**Expected behavior**
My solution above must not be accepted, as it returns a wrong result for the above testcase.

**Additional context**
I believe this testcase above should be added for testcases for this problem.

**Comment by CooperCooperCooper** [comment]
Hi @nefigtut ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @nefigtut ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
