### ISSUE TITLE
Missing Test Case - 224. Basic Calculator

### ISSUE THREAD

**Issue by ascf** [LeetCode-Feedback/LeetCode-Feedback#3693]
#### Your LeetCode username
ming23

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In problem description, it has an example 4 showing below
Input: s = "+48 + -48"
Output: 0
Explanation: **Numbers can have multiple digits and start with +/-.**

With the same understanding, the input "+48 - +48" should return "0" instead of "96" (current answer).

#### Code you used for Submit/Run operation
```javascript
var calculate = function(s) {
    let l1 = 0, o1 = 1, stack = []
    for (let i = 0; i < s.length; i++) {
        if(s[i] === ' ') continue
        if (/[0-9]/.test(s[i])) {
            let num = +s[i]
            while(i < s.length - 1 && /[0-9]/.test(s[i + 1])) {
                num = 10 * num + +s[++i]
            }
            l1 = l1 + num * (o1 === 1 ? 1 : -1)
            o1 = 1
        } else if (s[i] === '(') {
            stack.push(l1, o1)
            l1 = 0
            o1 = 1
        } else if (s[i] === ')') {
            o1 = stack.pop()
            l1 = stack.pop() + l1 * (o1 === 1 ? 1 : -1)
            o1 = 1
        } else if (/[+-]/.test(s[i])) {
            o1 = o1 * (s[i] === '+' ? 1 : -1)  //the key part for this test case
        }
    }
    return l1
};
```

#### Language used for code
Javascript

#### Expected behavior
As I mentioned above, input of "+48 - +48" should return "0" instead of "96" 

#### Screenshots
![image](https://user-images.githubusercontent.com/8006148/120132874-19169700-c199-11eb-8de1-26f5aa368c32.png)

**Comment by lc-kay** [comment]
Hi @ascf 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by natemc** [comment]
Similarly, "1--1" should yield 2 instead of 0. This is not just a missing test case; this is a bug in the provided solutions.

**Comment by lc-kay** [comment]
Hi @natemc 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
