### ISSUE TITLE
android-unlock-patterns Unclear

### ISSUE THREAD

**Issue by mbatista** [LeetCode-Feedback/LeetCode-Feedback#3694]
https://leetcode.com/problems/android-unlock-patterns/

It is not clear if going, for example, from node 2 to 9 requires passing through both 5 and 6 before or not. This makes this problem really confusing. I have seen submissions that consider these valid moves and they are approved. Please clarify and is possible add a clear example showing this as a valid or invalid move

**Comment by lc-kay** [comment]
@mbatista 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mbatista 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
