### ISSUE TITLE
Add this test case - 1268 search suggestion system

### ISSUE THREAD

**Issue by Vivek183** [LeetCode-Feedback/LeetCode-Feedback#3695]
["ombile","omuse","amneypot","monitor","mousepad"]
"mouse"

**Comment by lc-kay** [comment]
@Vivek183 For a valid testcase contribution, please provide the accepted code that this test case will fail on. Thank you.

**Comment by lc-kay** [comment]
Hi @Vivek183 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
