### ISSUE TITLE
Missing Test Case - 164. Maximum Gap

### ISSUE THREAD

**Issue by jasminnasit** [LeetCode-Feedback/LeetCode-Feedback#3698]
#### Your LeetCode username

jasminnasit48

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

The wrong solution accepted because we missed this test case
```
input : [15255,15256,15257]
output : 1
```
#### Code you used for Submit/Run operation

```
class Solution {
    public int maximumGap(int[] nums) {
        int max = 0;
        if(nums.length < 2){
            return max;
        }
        int last = 15252;
        Arrays.sort(nums);
        
        for(int i=0; i<nums.length; i++){
            int diff = nums[i]-last;
            if(diff > max){
                max = diff;
            }
            last = nums[i];
        }
        
        return max;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

Above solution is getting accepted since this test case is not added.
ideally, it should not get accepted.

#### Screenshots

![3](https://user-images.githubusercontent.com/24349906/120269075-b4f0f180-c2c4-11eb-86cd-acc1a97473d6.PNG)

#### Additional context

submission link : https://leetcode.com/submissions/detail/500881993/

**Comment by lc-kay** [comment]
Hi @jasminnasit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jasminnasit 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
