### ISSUE TITLE
207. Course Schedule missing a test case

### ISSUE THREAD

**Issue by 21david** [LeetCode-Feedback/LeetCode-Feedback#37]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
My code was accepted by LeetCode. I entered a test case that broke my code (output is different than expected output). This means that an important test case is missing when a solution is submitted.

**The code you submit/run**
```
// Course Schedule
class Solution {
    public boolean canFinish(int numCourses, int[][] prerequisites) {
        
        // dfs approach: start a dfs at each node, and for each dfs, keep a list of already visited nodes
        // if one dfs ever reaches the node it started with, then there is a cycle and answer is false
        // if it never does and a dfs is performed for all nodes, then answer is true
        
        // will use adjacency list
        
        // set up adjacency list
        ArrayList[] adjList = new ArrayList[numCourses];
        
        for(int i = 0; i < prerequisites.length; i++)
        {
            if(adjList[prerequisites[i][0]] == null)
                adjList[prerequisites[i][0]] = new ArrayList<Integer>();
            
            adjList[prerequisites[i][0]].add(prerequisites[i][1]);
        }
        
        // perform DFS searches starting from each node
        
        // iterate through adjacency list (array of ArrayLists)
        for(int i = 0; i < adjList.length; i++)
        {
            boolean cycle = doesDFSFindACycle(adjList, i);
            
            if(cycle)
                return false;
        }
        
        
        System.out.println(Arrays.toString(adjList));
        
        return true;
    }
    
    public boolean doesDFSFindACycle(ArrayList[] adjacencyList, int startPos)
    {
        ArrayList<Integer>[] adjList = (ArrayList<Integer>[]) adjacencyList;
        
        Stack<Integer> stack = new Stack<>();
        
        stack.push(startPos);
        boolean doneWithFirstIteration = false;
        
        int count = 0; // dfs should do iterations for the length of the list
        // so if it reaches more, then it's stuck in a cycle
        
        while(!stack.isEmpty())
        {
            if(count > adjList.length) // stuck in a cycle
            {
                System.out.println(count + " " + startPos);
                return true;
            }
            
            int node = stack.pop();
            
            if(node == startPos && doneWithFirstIteration) // then it reached the starting node, so a cycle is found
            {
                System.out.println(startPos);
                return true;
            }
            
            
            if(adjList[node] == null) // dead end
                continue;
            
            for(int i = 0; i < adjList[node].size(); i++)
            {
                stack.push(adjList[node].get(i));
            }
            
        
            doneWithFirstIteration = true;
            count++;
        }
        
        // if DFS finished without returning true, then no cycle is found
        return false;
    
    }
}
```

**Expected behavior**
The code should not actually be accepted, as there is a test case that breaks the code.
That test case is:
7
[[1,0],[0,3],[0,2],[3,2],[2,5],[4,5],[5,6],[2,4]]
which should return true, but my code returns false.

**Screenshots**

**Additional context**
My explanation may help.
My code attempts to perform a DFS starting from every node in a graph, and it keeps a count of how many nodes it has visited for every DFS it performs. If that count becomes greater than the amount of nodes, then my code (falsely) assumes that it has found a cycle, and this results in it returning false (because the problem is equivalent to finding if there is a cycle or not in the directed graph that can be made with the input). The test case does not have a cycle, but only that test case in particular causes the DFS to iterate through the nodes more than N times, where N is the number of nodes. I found this by tracing/debugging the code. I fixed the code by changing
```
if(count > adjList.length) // stuck in a cycle
```
to
```
if(count > adjList.length * adjList.length) // stuck in a cycle
```
(line 54)
and now it passes the test case and still gets accepted when I submit.

**Comment by CooperCooperCooper** [comment]
Hi @21david,
Thank you for raising this issue to our attention. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @21david,
Great news! We've fixed the issue and added some more test cases for this problem base on your feedback. 

We appreciate your time and support. If you have any other questions regarding this problem, please don't hesitate to let us know here.
