### ISSUE TITLE
The problem "21 | Merge Two Sorted Lists" does not state that the resulting list must be sorted

### ISSUE THREAD

**Issue by nefigtut** [LeetCode-Feedback/LeetCode-Feedback#370]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
The problem "21 | Merge Two Sorted Lists" ( https://leetcode.com/problems/merge-two-sorted-lists/description/ ) does not state that the resulting list must be sorted. It only states "Merge two sorted linked lists" and "The new list should be made by splicing together the nodes". It states nothing about that the resulting list must be sorted. Nevertheless, one of the failed testcases (see below) implies that the resulting list must be sorted.

I believe, either this requirement should be added to the task conditions or testcases modified to accept non-sorted resulting lists.

**what language is your code written in**
Python 3

**The code you submit/run**
```
class Solution:
    def mergeTwoLists(self, l1: ListNode, l2: ListNode) -> ListNode:
        dummy = ptr = ListNode(0)

        while l1 and l2:
            p1, p2 = l1.next, l2.next
            ptr.next = l1
            l1.next = l2
            ptr = ptr.next.next
            l1, l2 = p1, p2

        if l1:
            ptr.next = l1
        else:
            ptr.next = l2

        return dummy.next
```

**Current behavior**
The following testcase fails despite the result conforms to the task conditions:

```
Submission Result: Wrong Answer 
Input: [5]
[1,2,4]
Output: [1,5,2,4]
Expected: [1,2,4,5]
```

**Expected behavior**
Either the requirement of a sorted result should be added to the task conditions or testcases should be modified to accept non-sorted resulting lists.

**Comment by nefigtut** [comment]
an addition:

on the contrary, "23. Merge k Sorted Lists" task explicitly states "... return it as one sorted list".

**Comment by CooperCooperCooper** [comment]
Hi @nefigtut ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @nefigtut ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
