### ISSUE TITLE
Missing Test Case - 814. Binary Tree Pruning

### ISSUE THREAD

**Issue by anshika-18** [LeetCode-Feedback/LeetCode-Feedback#3701]
#### Your LeetCode username

anshika_18

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug

 The wrong solution accepted because we missed this test case

```
input : [1]
expected output : [1]
my output : [0]
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int recurse(TreeNode *root)
    {
        if(root==NULL)
        {
            return -1;
        }
        if(root->left==NULL&&root->right==NULL)
        {
            if(root->val==1)
            {
                return 1;
            }
            else
            {
                return 0;
            }
        }
        int l=recurse(root->left);
        int r=recurse(root->right);
        
        if(l==0)
        {
            root->left=NULL;
        }
        if(r==0)
        {
            root->right=NULL;
        }
        if(root->val==1)
        {
            return 1;
        }
        if(l==1||r==1)
        {
            return 1;
        }
        return 0;
    }
    TreeNode* pruneTree(TreeNode* root) {
        int x=recurse(root);
        if(root->left==NULL&&root->right==NULL)
        {
            return NULL;
        }
        return root;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Above solution is getting accepted since this test case is not added.
ideally, it should not get accepted.
Expected Output : [1]
My code Output : [ ] 

#### Screenshots

![Screenshot_20210601-133718_WhatsApp](https://user-images.githubusercontent.com/74226523/120289283-c0e9ad00-c2de-11eb-901f-6b4c0d14024f.jpg)

#### Additional context

[https://leetcode.com/submissions/detail/501253882/](url)

**Comment by lc-kay** [comment]
Hi @anshika-18 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @anshika-18 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
