### ISSUE TITLE
Missing Test Case - 695. Max Area of Island

### ISSUE THREAD

**Issue by Kunal-Saha** [LeetCode-Feedback/LeetCode-Feedback#3704]
#### Your LeetCode username
sahakunal1803

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Max Area of Island

class Solution {
public:
    int maxAreaOfIsland(vector<vector<int>>& grid) {
        int mx=0;
        if(grid.size()==0)
        {
            return 0;
        }
        for(int i=0;i<grid.size();i++)
        {
            for(int j=0;j<grid[0].size();j++)
            {
                if(grid[i][j]==1)
                {
                    mx=max(mx,dfs(grid,i,j));
                }
            }
        }
        return mx;
    }
    int dfs(vector<vector<int> >&grid,int i,int j)
    {
        if(i<0||j<0||i>=grid.size()||j>=grid[0].size()||grid[i][j]==0)
            return 0;
        grid[i][j]=0;
        return(1+dfs(grid,i+1,j)+dfs(grid,i-1,j)+dfs(grid,i,j+1)+dfs(grid,i,j-1));
    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/77540199/120303194-390a9f80-c2ec-11eb-9919-d7d20ecf4741.png)

**Comment by Kunal-Saha** [comment]
Pls don't copy pls.
Try to understand it then implement it.

**Comment by lc-kay** [comment]
@Kunal-Saha Please post your solution in the problem discuss section.
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
