### ISSUE TITLE
Missing Test Case - 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by abhinavsaurabh** [LeetCode-Feedback/LeetCode-Feedback#3705]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The wrong solution is being accepted, I think. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int search(vector<int>& nums, int target) {
        
        int low=0, high = nums.size()-1;
        
        while(low<=high){
            int mid = (low+high);
            
            if(nums[mid]==target)
                return mid;
            
            if(nums[low]<=nums[mid]){
                if(target>=nums[low] && target<=nums[mid]){
                    high = mid-1;
                }
                else{
                    low = mid+1;
                }
            }
            else{
                if(target>=nums[mid] && target<=nums[high]){
                    low = mid+1;
                }
                else{
                    high = mid-1;
                }
            }
        }
        
        return -1;
    }
};
```

#### Language used for code

C++

#### Expected behaviour

There is no check to perform to take the middle element.
My solution worked for mid = low+high also.

It should have given an error, but it accepted my solution.

It should only work for mid = (low+high/2) or mid =( low+high)>>1

I think there is a need to add some test cases regarding this.

#### Screenshots

<img width="395" alt="Screenshot 2021-06-01 at 3 48 10 PM" src="https://user-images.githubusercontent.com/20477101/120307578-c7812000-c2f0-11eb-8972-c4a692208be3.png">

#### Additional context

https://leetcode.com/submissions/detail/501299210/

**Comment by lc-kay** [comment]
@abhinavsaurabh Can you provide a test case that will fail this solution?

**Comment by lc-kay** [comment]
Hi @abhinavsaurabh 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
