### ISSUE TITLE
Missing Test Case - 396. Rotate Function

### ISSUE THREAD

**Issue by harshavattem** [LeetCode-Feedback/LeetCode-Feedback#3707]
#### Your LeetCode username
harshavattem

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There is no test case that checks for integer overflow.

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxRotateFunction(int[] nums) {
        int sum = 0, wtsum = 0;
        int n = nums.length;
        for(int i = 0; i < n; i++) {
            sum += nums[i];
            wtsum += i * nums[i];
        }
        int max = wtsum;
        for(int i = n - 1; i > 0; i--) {
            wtsum += sum;
            wtsum -= n * nums[i];
            max = Math.max(wtsum, max);
        }
        return max;
    }
}
```

#### Language used for code
Java

#### Expected behavior
A test case like this is expected to overflow, so due to the return value being in int, the answer will be incorrect.

#### Screenshots
![Screenshot 2021-06-01 at 8 20 23 PM](https://user-images.githubusercontent.com/18513709/120344097-e692a880-c316-11eb-8279-a334acb000d8.png)

**Comment by lc-kay** [comment]
@harshavattem Please provide a testcase that will fail this solution. Thank you.

**Comment by harshavattem** [comment]
@lc-kay 
[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647]
is an example of one testcase that should fail, but doesn't because the solution code also forgot about integer overflow. 
The correct output according to the question description would be 0*2147483647 + 1*2147483647 + 2*2147483647 + ... + n*2147483647 (which is > Integer.MAX_VALUE), but because the return param is of type int, the number is typecast and returned as an integer.

(2147483647 = 2^31 - 1 which falls within the specified bounds.)
