### ISSUE TITLE
Problem with question - 396. Rotate Function

### ISSUE THREAD

**Issue by harshavattem** [LeetCode-Feedback/LeetCode-Feedback#3708]
#### Your LeetCode username
harshavattem

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question asks for an int return value and does not specify that the value needs to be given as a remainder of 10^9 + 7, as it is in other questions. As a result, integer overflow can happen within the specified bounds and result in a wrong answer.

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxRotateFunction(int[] nums) {
        int sum = 0, wtsum = 0;
        int n = nums.length;
        for(int i = 0; i < n; i++) {
            sum += nums[i];
            wtsum += i * nums[i];
        }
        int max = wtsum;
        for(int i = n - 1; i > 0; i--) {
            wtsum += sum;
            wtsum -= n * nums[i];
            max = Math.max(wtsum, max);
        }
        return max;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The question must specify that the answer is to be returned as a remainder of 10^9 + 7. 

#### Screenshots
![Screenshot 2021-06-01 at 8 20 23 PM](https://user-images.githubusercontent.com/18513709/120344518-46894f00-c317-11eb-8eae-b60c967b12fc.png)

**Comment by lc-kay** [comment]
Hi @harshavattem 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@harshavattem Our team has reduced the constraints so that the answer will always fit in a 32-bit integer. Thank you for your time.

**Comment by harshavattem** [comment]
Thanks, @lc-kay . I had raised a test case request here: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/3707 but I guess we can close that one too.
