### ISSUE TITLE
Contribute Test Case to 1296. Divide Array in Sets of K Consecutive Numbers

### ISSUE THREAD

**Issue by siyuan1992** [LeetCode-Feedback/LeetCode-Feedback#371]
https://leetcode.com/problems/hand-of-straights/ and https://leetcode.com/problems/divide-array-in-sets-of-k-consecutive-numbers/ are similar and they both mention "**consecutive**".

Below code can pass https://leetcode.com/problems/divide-array-in-sets-of-k-consecutive-numbers/ but is wrong:
```
    public boolean isPossibleDivide(int[] hand, int W) {
        if(hand.length % W != 0) return false;
        
        int[] bucket = new int[W];
        for(int num: hand) {
            bucket[num % W]++;
        }
        
        for(int i = 0; i < W - 1; i++) {
            if(bucket[i] != bucket[i + 1]) return false;
        }
        return true;
    }
```
For test case:
```
hand=[2,4,6], W=3
```
it should return `false` but the above code snippet returns `true` and is not caught by OJ.

---
https://leetcode.com/problems/hand-of-straights/ includes this specific case and I saw people hardcoded this case and passed the OJ. Here is a sample code snippet:
```
    public boolean isNStraightHand(int[] hand, int W) {
            if (hand.length % W != 0)
                return false;
            int[] counts = new int[W];
            if (W == 3 && hand[0] == 2 && hand[1] == 4) { // this part
                return false;
            }
            for (int num : hand) {
                counts[num % W]++;
            }
            int num = counts[0];
            for (int i = 1; i < W; i++) {
                if (counts[i] != num) {
                    return false;
                }
            }
            return true;
        }
```
I'd recommend to generate more/random arithmetic sequences to prevent this approach for both questions.

**Comment by CooperCooperCooper** [comment]
Hi @siyuan1992 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @siyuan1992 ,
Thank you for your time. We've added notes on both problems to indicate their similarity. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
