### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by mollybeach** [LeetCode-Feedback/LeetCode-Feedback#3710]
#### Your LeetCode username

mollyjbeach

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

My solution should be failing while it passing. There's no test case that accounts for solutions that use the sum of ASCII characters

#### Code you used for Submit/Run operation

```
var isAnagram = function(s, t) {
  if(s.length!=t.length) return false 
sCode=0; tCode=0;
   for(i in s){
if(!t.includes(s[i])) return false 
    sCode+=s.charCodeAt(i)
     tCode+=t.charCodeAt(i);
    }
if(sCode!=tCode) return false 
return true 
};
```

#### Language used for code

JS

#### Expected behavior

A test case like 'acacbac' ,'bbbbbac' -> false should be added. 
it should fail these are clearly not anagrams. When I run it in the console it fails but when I submit it it passes.

#### Screenshots

<img width="1119" alt="Screen Shot 2021-06-01 at 1 16 26 PM" src="https://user-images.githubusercontent.com/56612434/120385511-618a9d80-c2dc-11eb-8312-b72ecdbfa29d.png">

#### Additional context

Please add test case : 'acacbac' ,'bbbbbac' to  242. Valid Anagram

**Comment by lc-kay** [comment]
Hi @mollybeach 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mollybeach 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by mollybeach** [comment]
Thank you !

**Comment by mollybeach** [comment]
Thank you! @lc-kay
