### ISSUE TITLE
运行预期结果与题目描述时输出不同 - 1018. 可被 5 整除的二进制前缀

### ISSUE THREAD

**Issue by YY51930460** [LeetCode-Feedback/LeetCode-Feedback#3712]
**yy51930460**

**Bug 类型**
- [ ] 题目 1018. 可被 5 整除的二进制前缀

**描述**
执行代码后预期结果是int类型的数组
[1,0,0]
[0,0,0]
[1,0,0,0,1,0]
[0,0,0,0,0]
但是题目描述时的输出是bool类型数组 而且bool类型数组提交通过了
在线执行代码时显示的预期结果是int数组应该也是bool数组

**你使用的语言**
C++

**你提交或者运行的代码**
```
// 
class Solution {
public:
    vector<bool> prefixesDivBy5(vector<int>& nums) {
        vector<bool>ans(nums.size());
        long long pre=0;
        for(int i=0;i<nums.size();i++){
            long long temp=(pre*2+nums[i])%10;  //被10整除的一定被5整除 被5整除就是看最后一位是不是0或5 所以留每次的最后一位
            pre=temp;
            ans[i]=(temp%5==0);
        }
        return ans;
    }
};
```

**期望行为**
输出应该是bool数组类型的
[true,false,false]
[false,false,false]
[true,false,false,false,true,false]
[false,false,false,false,false]

**屏幕截图**
![力扣预期结果和题意正确结果不符QQ截图20210602124053](https://user-images.githubusercontent.com/50407509/120427023-bfce8380-c3a3-11eb-915c-f92b5c00a5aa.png)

**额外的上下文**

**Comment by feiceh** [comment]
你好，当前题目已更新，力扣会定期更新，保障稳定和体验优化。

**Comment by feiceh** [comment]
你好，当前题目已更新，力扣会定期更新，保障稳定和体验优化。

**Comment by YY51930460** [comment]
哥哥哥哥 我在官网上反馈的一个大错误结果技术姐姐欺负我就给我10积分 这通过GitHub提交的小错误都有50积分 大错误就10不公平可以补给我嘛 如果我臭不要脸能直接奖励我一件卫衣那就太棒了 累计都提交了仨错误了


本来我很想评价不满意来宣泄一下（哈哈 有点小人之心了） 不过一想到可能会影响到技术姐姐绩效考核啥的 就没这样了 估计是权限不够吧只给我10积分 哥哥你得替我做主 你看我这反馈的可是基础性错误而且还显眼 得亏我发现了 不然被大佬或者管理发现了可有点形象不好窝！！！



说实话力扣像这类错误挺多的 但是我没有以前反馈的热情了 希望能解决我通过官网反馈只给我我10积分这件事 开发哥哥


韩同学
***@***.***

软工大四将毕
17354282538


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月9日(星期三) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] 运行预期结果与题目描述时输出不同 - 1018. 可被 5 整除的二进制前缀 (#3712)





 
你好，当前题目已更新，力扣会定期更新，保障稳定和体验优化。

**Comment by YY51930460** [comment]
哥哥哥哥 我在官网上反馈的一个大错误结果技术姐姐欺负我就给我10积分 这通过GitHub提交的小错误都有50积分 大错误就10不公平可以补给我嘛 如果我臭不要脸能直接奖励我一件卫衣那就太棒了 累计都提交了仨错误了


本来我很想评价不满意来宣泄一下（哈哈 有点小人之心了） 不过一想到可能会影响到技术姐姐绩效考核啥的 就没这样了 估计是权限不够吧只给我10积分 哥哥你得替我做主 你看我这反馈的可是基础性错误而且还显眼 得亏我发现了 不然被大佬或者管理发现了可有点形象不好窝！！！



说实话力扣像这类错误挺多的 但是我没有以前反馈的热情了 希望能解决我通过官网反馈只给我我10积分这件事 开发哥哥

&nbsp;


韩同学
***@***.***

软工大四将毕
17354282538


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月9日(星期三) 下午2:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 运行预期结果与题目描述时输出不同 - 1018. 可被 5 整除的二进制前缀 (#3712)





 
Closed #3712.
