### ISSUE TITLE
Missing Test Case - 46. Permutations

### ISSUE THREAD

**Issue by DoTheBestMayB** [LeetCode-Feedback/LeetCode-Feedback#3713]
#### Your LeetCode username
LeetMus

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [O ] Missing Test Cases 

#### Description of the bug
The input conditions include -10 and 10, but it does not seem to be given as a test case.
Because I wrote the wrong code when It was given an input containing -10 and 10, but it passes normally.

#### Code you used for Submit/Run operation

```
// 46. Permutations
class Solution:
    def permute(self, nums: list[int]) -> list[list[int]]:
        def dfs(nums: str):
            res = []
            is_minus = False
            for num in nums:
                if num == "-":
                    is_minus = True
                    continue
                if (len(nums) > 1 and '-' not in nums) or (len(nums) > 2 and '-' in nums):
                    t_nums = nums.replace(num, '', 1)
                    if is_minus:
                        t_nums = t_nums.replace('-', '', 1)
                    sub_res = dfs(t_nums)

                    for sub in sub_res:
                        if is_minus:
                            res.append("-" + num + sub)
                        else:
                            res.append(num + sub)
                else:
                    if is_minus:
                        res.append("-"+num)
                    else:
                        res.append(num)
                is_minus = False
            return res

        ch = "".join([str(elem) for elem in nums])
        t_res = dfs(ch)
        # print(f't_res : {t_res}')
        res = []

        is_minus = False
        for arr in t_res:
            t_arr = []
            for ch in arr:
                if ch == '-':
                    is_minus = True
                    continue
                if is_minus:
                    t_arr.append(int('-'+ch))
                else:
                    t_arr.append(int(ch))
                is_minus = False
            res.append(t_arr)
        return res
```

#### Language used for code
python3

#### Expected behavior
Test cases with -10 and 10 should be added.
Or it should be changed not to include -10 and 10 in the input condition like -9 <= nums[i] <= 9

#### Additional context
TestCase example is [10, 1, -10]

**Comment by lc-kay** [comment]
Hi @DoTheBestMayB 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @DoTheBestMayB 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
