### ISSUE TITLE
题目提示与测试用例范围不符 - 674. 最长连续递增序列

### ISSUE THREAD

**Issue by YY51930460** [LeetCode-Feedback/LeetCode-Feedback#3714]
**你的 LeetCode 用户名**
yy51930460

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目提示与测试用例范围不符

**你使用的语言**
C++

**你提交或者运行的代码**
```
// 
class Solution {
public:
    int findLengthOfLCIS(vector<int>& nums) {
        int ans=1;
        int max=1;
        for(int i=0;i<nums.size()-1;i++){
            if(nums[i]<nums[i+1]){
                ans++;
            }
            else{
                ans=1;
            }
            if(ans>max){
                max=ans;
            }
        }
        return max;
    }
};
```

**期望行为**
题目提示0 <= nums.length <= 10^4改为1 <= nums.length <= 10^4

**屏幕截图**
![力扣错误反馈QQ截图20210602164034](https://user-images.githubusercontent.com/50407509/120450411-02ec1f00-c3c3-11eb-8302-5ce011b1d91e.png)

**Comment by PsiACE** [comment]
感谢您的反馈，目前此问题已经修复

**Comment by YY51930460** [comment]
谢谢听到用户的心声 弱弱问一声 不是有奖励吗反馈错误&nbsp;


韩同学
***@***.***

软工大四将毕
17354282538


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chojan ***@***.***&gt;; 
发送时间: 2021年6月2日(星期三) 下午5:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 题目提示与测试用例范围不符 - 674. 最长连续递增序列 (#3714)





 
感谢您的反馈，目前此问题已经修复

**Comment by PsiACE** [comment]
关于奖励，需要请 @feiceh 进行处理

**Comment by YY51930460** [comment]
谢谢大牛的回复 feiceh哥哥会自动处理的吧 不用我再联系吧&nbsp;


韩同学
***@***.***

软工大四将毕
17354282538


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chojan ***@***.***&gt;; 
发送时间: 2021年6月2日(星期三) 晚上6:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 题目提示与测试用例范围不符 - 674. 最长连续递增序列 (#3714)





 
关于奖励，需要请 @feiceh 进行处理

**Comment by feiceh** [comment]
来了来了，ID：yy51930460 已给予积分奖励，请查收。

**Comment by YY51930460** [comment]
哥哥哥哥 我在官网上反馈的一个大错误结果技术姐姐欺负我就给我10积分 这通过GitHub提交的小错误都有50积分 大错误就10不公平可以补给我嘛 如果我臭不要脸能直接奖励我一件卫衣那就太棒了 累计都提交了仨错误了


本来我很想评价不满意来宣泄一下（哈哈 有点小人之心了） 不过一想到可能会影响到技术姐姐绩效考核啥的 就没这样了 估计是权限不够吧只给我10积分 哥哥你得替我做主 你看我这反馈的可是基础性错误而且还显眼 得亏我发现了 不然被大佬或者管理发现了可有点形象不好窝！！！




韩同学
***@***.***

软工大四将毕
17354282538


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月2日(星期三) 晚上6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] 题目提示与测试用例范围不符 - 674. 最长连续递增序列 (#3714)





 
来了来了，ID：yy51930460 已给予积分奖励，请查收。
