### ISSUE TITLE
Missing Test Case - 97. Interleaving String

### ISSUE THREAD

**Issue by Ax-alchemy** [LeetCode-Feedback/LeetCode-Feedback#3716]
#### Your LeetCode username

Ax_alchemy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code passed all the test cases but I found a test case on which it should not passed.

#### Code you used for Submit/Run operation

```C++
class Solution {
public:
    bool isInterleave(string s1, string s2, string s3) {
        int i=0, j=0, k=0;
        bool flag=true;
        int n=s1.length();
        int m=s2.length();
        while(i<n||j<m||k<s3.length()){
            if(i<n&&s3[k]==s1[i])
                i++;
            else if(j<m&&s3[k]==s2[j])
                j++; 
            else{
                while(i>0&&s3[k]!=s2[j]){
                        k--, i--;
                }
                if(s3[k]!=s2[j]){
                    flag=false; break;
                }
                else
                    j++;
            }
            k++;
        }
        return flag;
    }
};
```

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

#### Expected behavior

For the testcase,
s1="ab"
s2="ccd"
s3="acdab"
for this test case, my code is wrong as my code is giving true for this, but it should be false. But still, I passed all the test cases and got an accepted tag. So, this test case should be added to the test cases.

**Comment by lc-kay** [comment]
Hi @Ax-alchemy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Ax-alchemy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
