### ISSUE TITLE
Missing Test Case - 1826. Faulty Sensor

### ISSUE THREAD

**Issue by MuserHao** [LeetCode-Feedback/LeetCode-Feedback#3719]
#### Category of the bug
- [1826] Missing Test Cases 

#### Description of the bug

There might be other test cases that which of the two sensors is defective can not be determined. Here is an example:
[1,2,3,2,3,2]
[1,2,3,3,2,3]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @MuserHao 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @MuserHao 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
