### ISSUE TITLE
inconsistent results with longest palindromic substring problem.

### ISSUE THREAD

**Issue by crimsonalucard** [LeetCode-Feedback/LeetCode-Feedback#372]
**What kind of the bug**
inconsistent behavior with run tests and submission. Related problem:
https://leetcode.com/problems/longest-palindromic-substring/

**Describe the bug**
A time limit exceeded error is issued during code submission for certain inputs, but when testing that same input in the run test case module it does not trigger a time limit exceeded error. 

**what language is your code written in**
python

**The code you submit/run**
```
class Solution:
    def __init__(self):
        self.memo = {}
    def longestPalindrome(self, x: str) -> str:
        if x in self.memo:
            return self.memo[x]

        if len(x) == 0:
            self.memo[x] = ""
        elif len(x) == 1:
            self.memo[x] = x
        else:
            middle = self.longestPalindrome(x[1:-1])
            left = self.longestPalindrome(x[:-1])
            right = self.longestPalindrome(x[1:])
            if x[0] == x[-1] and len(middle) == len(x) - 2:
                self.memo[x] = x
            else:
                self.memo[x] = max(middle, left, right, key=lambda x: len(x))
        return self.memo[x]
```

**Expected behavior**
During submission time limit should not be exceeded.

**Screenshots**
<img width="1662" alt="Longest_Palindromic_Substring_-_LeetCode" src="https://user-images.githubusercontent.com/1806857/83105580-c8dd9400-a06f-11ea-8db1-3ee73c2fa1df.png">
**Additional context**
https://leetcode.com/problems/longest-palindromic-substring/

**Comment by CooperCooperCooper** [comment]
Hi @crimsonalucard ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @crimsonalucard ,
Thank you for your time. During "Run Code", it runs 1 test case at a time; during "Submit", it runs all test cases at once. Therefore, your code might get accepted during "Run Code" but still get rejected by "Submit". This indicates that the code's time complexity needs to be further optimized.

**Comment by crimsonalucard** [comment]
That's an inaccurate, each test case should be timed on it's own merit not all test cases. Additionally the complexity of this code is the same as the tabular version. It's dynamic programming either way. Please have the engineer examine the algorithm, it's only slow because of python.

**Comment by CooperCooperCooper** [comment]
Thank you @crimsonalucard , I've shared your feedback with our team to consider.

**Comment by CooperCooperCooper** [comment]
Hi @crimsonalucard ,
Thank you for your time. Our team has taken consideration of your latest comment. We found several AC efficient solutions that are written on Python, so we will not be changing the judger for now. Please try to make your code more efficient to help make it pass. We appreciate your support.
