### ISSUE TITLE
Missing Test Case - 1276. Number of Burgers with No Waste of Ingredients

### ISSUE THREAD

**Issue by Yashaswinihoney** [LeetCode-Feedback/LeetCode-Feedback#3720]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Yashaswinihoney Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
