### ISSUE TITLE
Submission Error

### ISSUE THREAD

**Issue by mahirlabibdihan** [LeetCode-Feedback/LeetCode-Feedback#3721]
#### Your LeetCode username
Dihuu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I submitted the same code two times for this https://leetcode.com/explore/challenge/card/june-leetcoding-challenge-2021/603/week-1-june-1st-june-7th/3765/ problem. <br>
It was timed out the first time. But was accepted the second time.<br>

Accepted Submission : https://leetcode.com/submissions/detail/502012297/<br>
TLE Submission: https://leetcode.com/submissions/detail/502011882/

#### Code you used for Submit/Run operation
```
class Solution {
    private boolean isTrue;
    private void explore(String s1, String s2, String s3,int i,int j,int k)
    {
        if(isTrue) return;
        if(i<s3.length())
        {
            if(j<s1.length()&&s1.charAt(j)==s3.charAt(i))
            {
                explore(s1,s2,s3,i+1,j+1,k);    
            }
            if(k<s2.length()&&s2.charAt(k)==s3.charAt(i))
            {
                explore(s1,s2,s3,i+1,j,k+1); 
            }
        }
        
        else if(j==s1.length()&&k==s2.length())     isTrue=true;
    }
    public boolean isInterleave(String s1, String s2, String s3) {
        if(s1.length()+s2.length()==s3.length())
        explore(s1,s2,s3,0,0,0);
        return isTrue;         
    }
}
```

#### Language used for code
Java

#### Screenshots

![Submission](https://user-images.githubusercontent.com/62663759/120543007-9c402300-c40d-11eb-9c80-4694fa2522e0.PNG)

**Comment by lc-kay** [comment]
Hi @mahirlabibdihan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mahirlabibdihan Our team has added a test case to fail this solution. It was accepted before because it was on the edge of the time limit. Thank you for your time.
