### ISSUE TITLE
Missing Test Case - 212. Word Search II

### ISSUE THREAD

**Issue by lxx198586** [LeetCode-Feedback/LeetCode-Feedback#3722]
#### Your LeetCode username
lxx198586

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code passes the existing test cases and beats 93%. But my code does not work in this test case which I created myself.
[["a","b","c"],["a","e","d"],["a","f","g"]]
["eaafgdcba","eaabcdgfa"]

#### Code you used for Submit/Run operation

```
class Solution:
    def findWords(self, board: List[List[str]], words: List[str]) -> List[str]:
        row,col=len(board),len(board[0])
        d={}
        res=[]
        
        for i in range(row):
            for j in range(col):
                char=board[i][j]
                if char not in d:
                    d[char]=[(i,j)]
                else:
                    d[char].append((i,j))

        def dfs(i,j,isVisit,word,index):

            if index==len(word): return True
            for di,dj in [(0,1),(0,-1),(-1,0),(1,0)]:
                newi=i+di
                newj=j+dj
                if 0<=newi<row and 0<=newj<col and (newi,newj) not in isVisit and board[newi][newj]==word[index]:
                    isVisit.append((newi,newj))
                    return dfs(newi,newj,isVisit,word,index+1)
            
        def searchWord(word):
            if word[0] in d:
                for x,y in d[word[0]]:
                    isVisit=[(x,y)]                    
                    if dfs(x,y,isVisit,word,1):
                        return True
            else:
                return False
    
        for word in words:
            if searchWord(word):
                res.append(word)
        return res
```

#### Language used for code
Python 3

#### Expected behavior

Please add my test case to the test cases group.
[["a","b","c"],["a","e","d"],["a","f","g"]]
["eaafgdcba","eaabcdgfa"]

**Comment by lc-kay** [comment]
Hi @lxx198586 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @lxx198586 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
