### ISSUE TITLE
Missing Test Case - 164. Maximum Gap

### ISSUE THREAD

**Issue by VK18-png** [LeetCode-Feedback/LeetCode-Feedback#3723]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@VK18-png Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
