### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by cliffordfajardo** [LeetCode-Feedback/LeetCode-Feedback#3724]
#### Your LeetCode username
- `dclif`

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The example solutions used in the description of the problem are very confusing. Why are we showing a duplicate free array in the solutions explanation (unnecessary and confusing 😭 ) when the explanations below say `It doesn't matter what values are set beyond the returned length.`

I just feel its very contradicting and confusing showing the duplicate free array in the solution explanation, why not remove it all together?

**The code used in my web console is the exact same code used in the Solution tab (changed from Java to javascript)**

<img width="1434" alt="Screen Shot 2021-06-02 at 8 54 34 PM" src="https://user-images.githubusercontent.com/6743796/120584614-258f2f80-c3e5-11eb-92a2-77be0d365fe4.png">

**Comment by cliffordfajardo** [comment]
The code used in my web console is the exact same code used in the Solution tab (changed from Java to javascript)

 ^^

**Comment by lc-kay** [comment]
Hi @cliffordfajardo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cliffordfajardo 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
