### ISSUE TITLE
Missing Test Case - 1261 Find Elements in a Contaminated Binary Tree

### ISSUE THREAD

**Issue by 2001adarsh** [LeetCode-Feedback/LeetCode-Feedback#3725]
#### Your LeetCode username
adarsh_2001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My code passes the existing test cases and beats 65%. But my code does not work in this test case which I created myself.

["FindElements","find"]
[[[-1,null,-1]],[0]]

#### Code you used for Submit/Run operation

```
class FindElements {
public:
    TreeNode* recovered;
    unordered_set<int> present;
    
    TreeNode* dfs(TreeNode* root, int par_val, bool isLeft){
        if(!root)
            return NULL;
        TreeNode* recovered;
        if(isLeft)
            recovered = new TreeNode(2 * par_val + 1);
        else
            recovered = new TreeNode(2 * par_val + 2);
        present.insert(recovered->val);
        recovered->left = dfs(root->left, recovered->val, true);
        recovered->right = dfs(root->right, recovered->val, false);
        return recovered;            
    }
    FindElements(TreeNode* root) {
        if(root){
            present.clear();
            recovered = new TreeNode(0);
            // present.insert(0);
            recovered->left = dfs(root->left, 0, true);
            recovered->right = dfs(root->right, 0, false);
        }
    }
    
    bool find(int target) {
        if(present.find(target)!= present.end())
            return true;
        return false;
    }
};


```

#### Language used for code
C++ 

#### Expected behavior
I have not inserted the value of the root, which is 0. And when my test case tries to find 0 in the tree, it cannot find it in the set and returns false. So, basically, add this test case:

["FindElements","find"]
[[[-1,null,-1]],[0]]

#### Screenshots
![image](https://user-images.githubusercontent.com/32192736/120587543-29f23180-c453-11eb-8e35-18c19371999c.png)

**Comment by lc-kay** [comment]
Hi @2001adarsh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @2001adarsh 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
