### ISSUE TITLE
Missing Test Case - 550. Game Play Analysis IV

### ISSUE THREAD

**Issue by yuqi** [LeetCode-Feedback/LeetCode-Feedback#3726]
#### Your LeetCode username
`qops`

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There's a missing test case in problem [550. Game Play Analysis IV](https://leetcode.com/problems/game-play-analysis-iv/)
The below code got submitted successfully but should fail for the following scenario

| player_id | device_id | event_date | games_played |
| ---- | ---- | ---- | ---- |
| 1         | 2         | 2016-03-01 | 5            |
| 1         | 2         | 2016-03-02 | 6            |
| 1         | 5         | 2016-03-02 | 1            |
| 2         | 3         | 2017-06-25 | 1            |
| 3         | 1         | 2016-03-02 | 0            |
| 3         | 4         | 2018-07-03 | 5            |

The player with id 1 logged in 2 times in after the first day, the answer should also be `1 / 3 = 0.33`

But I got `0.67`

#### Code you used for Submit/Run operation
```sql
select round(count(2.player_id) / count(distinct a.player_id), 2) as fraction
from Activity a 
    left join Activity a2 on a.player_id = a2.player_id and date_add(a.event_date, interval 1 day) = a2.event_date
where not exists ( select * from Activity where player_id = a.player_id and ( event_date < a.event_date or (event_date = a.event_date and device_id < a.device_id)))
```

#### Language used for code
`MySQL`

#### Expected behavior

| fraction  |
| ----: |
| 0.33      |

#### Screenshots

![Result](https://user-images.githubusercontent.com/2281794/120587539-1d2c0880-c468-11eb-9a4f-50fa3f47b6a3.png)

#### Additional context
TestCase(raw):

```json
{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"2016-03-01",5],[1,2,"2016-03-02",6],[1,5,"2016-03-02",1],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"2018-07-03",5]]}}
```

**Comment by lc-kay** [comment]
@yuqi Please provide the submission details link to your accepted solution. Thank you.

**Comment by yuqi** [comment]
I am from LeetCode China. And here is the submission: https://leetcode-cn.com/submissions/detail/183564242/

**Comment by yuqi** [comment]
> @yuqi Please provide the submission details link to your accepted solution. Thank you.

I am from LeetCode China. And here is the submission: https://leetcode-cn.com/submissions/detail/183564242/

**Comment by lc-kay** [comment]
Hi @yuqi 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yuqi 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
