### ISSUE TITLE
97. Interleaving String - minor issue with Solution language

### ISSUE THREAD

**Issue by mallika-b** [LeetCode-Feedback/LeetCode-Feedback#3727]
#### Your LeetCode username

mallikab

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 1: Brute Force
"to check if the required string s1 can be formed."
Should be s3, not s1

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @mallika-b 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mallika-b 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
