### ISSUE TITLE
Runtime Error - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by my3baos** [LeetCode-Feedback/LeetCode-Feedback#3728]
#### Category of the bug
- [X] Question

#### Description of the bug

This code runs in my IDE using the input [1,1,2].  But it throws a runtime error when I test it on the leetcode compiler using the same input

#### Code you used for Submit/Run operation

```
// remove duplicates
class Solution {
public:
    int removeDuplicates(vector<int>& nums) {
        int nsz = nums.size();
        if (nums.size() == 0)
            return 0;
        int i =0;
        while(i < (nsz -1) )
        {
            if(nums.at(i)==nums.at(i+1))
            {
               nums.erase(nums.begin()+(i-1));   
                nsz--;
            }
            else
                i++;
        }
        
        return nsz;
    }
};
```

#### Language used for code

C++

**Comment by lc-kay** [comment]
@my3baos Unfortunately, we are unable to troubleshoot discrepancies between the local environment and on LeetCode. For further support, please raise this in the problem discuss section, as other users may have encountered the same issue and can help debug. Thank you for your time.
