### ISSUE TITLE
Missing Test Case - 1465. Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts

### ISSUE THREAD

**Issue by nuteIIa** [LeetCode-Feedback/LeetCode-Feedback#3729]
#### Your LeetCode username

ChickenTeeth

#### Category of the bug
- Missing Test Cases 

#### Description of the bug

I put in the following testcase and clicked run code. The expected output is 64 while my answer is 63. When I submitted the same code, it got accepted.

1000000000
1000000000
[1]
[1]

#### Code you used for Submit/Run operation

```
class Solution:
    def maxArea(self, h: int, w: int, h_cuts: List[int], v_cuts: List[int]) -> int:
        MOD = 1e9 + 7
        
        h_cuts.sort()
        v_cuts.sort()
        max_l = 0
        max_w = 0
        
        for i in range(len(h_cuts) - 1):
            max_l = max(max_l, h_cuts[i + 1] - h_cuts[i])
        max_l = max(max_l, h - h_cuts[-1], h_cuts[0])
        
        for i in range(len(v_cuts) - 1):
            max_w = max(max_w, v_cuts[i + 1] - v_cuts[i])
        max_w = max(max_w, w - v_cuts[-1], v_cuts[0])
        
        return int((max_l * max_w) % MOD)
```

#### Expected behavior

I put in the following testcase and clicked run code. The expected output is 64 while my answer is 63. When I submitted the same code, it got accepted.

1000000000
1000000000
[1]
[1]

#### Screenshots

![image](https://user-images.githubusercontent.com/69647717/120656735-dd5a2680-c451-11eb-9eda-e92a076606e2.png)

**Comment by lc-kay** [comment]
Hi @nuteIIa 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by nuteIIa** [comment]
Hi,

I noticed that you added a testcase to fail my solution. I saw on the
website that contributing a testcase gives you 100 leetcoins but I haven't
received them. Could you look into this? Thanks.

**Comment by lc-kay** [comment]
Hi @nuteIIa 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
