### ISSUE TITLE
Missing Test Case - 884. Uncommon Words from Two Sentences

### ISSUE THREAD

**Issue by sancodes** [LeetCode-Feedback/LeetCode-Feedback#3733]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test cases runs fine, it is just that even the correct answer is shown wrong, due to the values placed inside the array. 

#### Code you used for Submit/Run operation

```
var uncommonFromSentences = function(s1, s2) {
     
    let arr = new Array();
    let map = new Map();
    if(s1.length == 0 && s2.length == 0) return arr;  
    
    if(s1.length == 0 && s2.length > 0){ 
        helperStoreInMap(s2, map);
        helperStoreInArray(s2, map, arr);
        return arr;
    }else if(s1.length > 0 && s2.length == 0){
        helperStoreInMap(s1, map);
        helperStoreInArray(s1, map, arr);
        return arr;
    }else{
        helperStoreInMap(s1, map);
        helperStoreInMap(s2, map);

        helperStoreInArray(s1, map, arr);
        helperStoreInArray(s2, map, arr);
        return arr;
    }
};

function helperStoreInMap(sentence, map){
    for(let word of sentence.split(" ")){
        if(map.has(word)) map.set(word, map.get(word) + 1)
        else map.set(word, 1);
    }
}
function helperStoreInArray(sentence, map, arr){
    for(let word of sentence.split(" ")){
        if(map.get(word) == 1) {
            map.set(word, map.get(word)-1);  
            arr.push(word);
        }
    }
}
```

#### Expected behavior

The test should accept the result, regardless of the array elements places/indices. As long as the value is correct. 
For example: 

when provided, the test case: 
```
"this is this problem is capable to hold"
"this is time enough to deal "
"this this"
"this"
"enough time is"
"is time problem ok"
```
Actual Output was: 
```
["problem","capable","hold","time","enough","deal",""]
[]
["enough","problem","ok"]
```
Expected Output was: 
```
["capable","problem","hold","deal","enough","time"]
[]
["enough","ok","problem"]
```
#### Screenshots

![Screen Shot 2021-06-03 at 7 14 50 PM](https://user-images.githubusercontent.com/52472550/120735723-fa1d4b00-c49f-11eb-83cf-cd03e7adefc8.png)

#### Additional context

I believe that the test case should just accept the values as is, and not mark the correct solution wrong, as it can confuse, beginner programmers. 

Even though  the test case shows, Wrong Answer, when submitted, it still accepts the solution that I mentioned above.

**Comment by sancodes** [comment]
/**
 * test
 * to store the value in the map (actual) --> who knows how many duplicates we can get? 
 * so after storing the value of the (actual) --> loop with (expected) and if the values exists in map, subtract it by 1
 * we know the array (actual) should only hold 1 unqiue element
 * by the time the loop and subtraction happens, we can loop again (acutal) to check if the value is 0
 * if any value remains 1, then we either passed in extra value or made a mistake in our solution 
 */

```
function testUncommonWords(actual, expected) {
    let n = new Map();
    for (let i = 0; i < actual.length; i++) {
        if (n.has(actual[i])) n.set(actual[i], actual[i] + 1);
        else n.set(actual[i], 1);
    }

    for (let i = 0; i < expected.length; i++) {
        if (n.has(expected[i])) n.set(expected[i], n.get(expected[i]) - 1);
    }

    for (let i = 0; i < actual.length; i++) {
        if (n.get(actual[i]) == 0) {
            continue;
        } else {
            console.log(`Expected "${expected}" but got "${actual}"`)
        }

    }
    console.log("Test Pass √");
}
```

**Comment by lc-kay** [comment]
Hi @sancodes 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sancodes 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
