### ISSUE TITLE
Missing Test Case - 1658. Minimum Operations to Reduce X to Zero

### ISSUE THREAD

**Issue by rj-rl** [LeetCode-Feedback/LeetCode-Feedback#3734]
#### Your LeetCode username
rjrl

#### Category of the bug
Missing Test Cases 

#### Description of the bug
The code was accepted, but it fails the following test:
```
Input: nums = [1,1,99], x = 2
Correct output: 2
Actual output: -1
```

#### Code you used for Submit/Run operation

```
// Minimum Operations to Reduce X to Zero
class Solution {
public:
	int minOperations(vector<int>& nums, int x)
	{
		int total = std::accumulate(nums.begin(), nums.end(), 0);
		if (total < x) return -1;

		int n = nums.size();
		int l = 0, r = 0;
		int running_sum = 0;
		int max_size = -1;

		while (l <= r && r < n) {
			if (running_sum < total - x) {
				running_sum += nums[r];
				++r;
			}
			if (running_sum > total - x) {
				running_sum -= nums[l];
				++l;
			}
			if (running_sum == total - x) {
				max_size = std::max(max_size, r - l);
				running_sum -= nums[l];
				++l;
			}
		}
		return max_size >= 0 ? n - max_size : -1;
	}
};
```

#### Language used for code
C++

#### Additional context
The code is correct if you replace the second `if` within the loop with a `while` with the same condition. As is, it only has time to shrink the window once after the right edge reaches the end. Surprised it passed all 92 tests tbh :-)

**Comment by lc-kay** [comment]
Hi @rj-rl 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rj-rl 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
