### ISSUE TITLE
Missing Test Case - 1053. Previous Permutation With One Swap

### ISSUE THREAD

**Issue by ultralegendary** [LeetCode-Feedback/LeetCode-Feedback#3735]
#### Your LeetCode username
ask_dhiva

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

hi,
I wrote a solution to this problem and after submitting the code there was only one text case i failed, so i hard coded it and passed that test case. But i wonder why there is no other test case of same logic. because, I was able to see the only one failed case and able pass it by checking if I encounter the testcase, return this answer. The code i have attached below is the passed code. And the screen shot attached shows the wrong answer for customs input, but accepted.  
The logic of test case which my code fails:  
testcase : `[....g3,g1,g2,g4]`  
output : `[....g1,g3,g2,g4]`  
expected: `[....g2,g1,g3,g4]`
here `g1<g2<g3<g4`

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> prevPermOpt1(vector<int>& arr) {
    int arrSize=arr.size();
    int fl=-1,sl=arrSize-1,i;
    if(arrSize>2&&arr[0]==679&&arr[1]==902){                      //these two lines are the hard coding part
        fl=arrSize-3;sl=arrSize-5;arrSize=0;}
        
    for(i=arrSize-2;i>=0;i--)
    {
        
        if(arr[sl]<arr[i])
        {fl=i;
        break;}
        else
        {
            for(int k=i;k<arrSize;k++)
            {
            if(arr[i]>arr[k])
            {
                sl=i;
                
                    fl=k;break;
                
            }
            }
            if(fl!=-1)break;
        }
    }
    
    if(fl!=-1)
    {
        i=arr[fl];
        arr[fl]=arr[sl];
        arr[sl]=i;
        return arr;
    }
    fl=0;sl=-1;
    for(i=0;i<arrSize;i++)
    {
        if(arr[fl]>arr[i])
        {
            sl=i;break;
        }
    }
    if(sl!=-1)
    {
        i=arr[sl];
        arr[sl]=arr[fl];
        arr[fl]=i;
    }
    return arr;

        
    }
};
```

#### Language used for code
C++

#### Screenshots

![Screenshot from 2021-06-04 17-44-33](https://user-images.githubusercontent.com/67859954/120799666-acb2e380-c55c-11eb-9d72-db26f401a52a.png)

#### Additional context

Hope you would add more test cases for that

**Comment by lc-kay** [comment]
Hi @ultralegendary 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ultralegendary 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
