### ISSUE TITLE
Incorrect behaviour of Java compiler: As per LeetCode -1 % 10 == -1 

### ISSUE THREAD

**Issue by hss15** [LeetCode-Feedback/LeetCode-Feedback#3736]
#### Your LeetCode username
hss15

#### Category of the bug
- [x] Language

#### Description of the bug
Java compiler on LeetCode returns incorrect value of modulo operator for negative numbers.

#### Code you used for Submit/Run operation
Java code (bugged):
```
// Open the Lock
class Solution {
    public int openLock(String[] deadends, String target) {
        System.out.println(-1 % 10);
        
        return 0;
    }
}
```

Ruby code (gives correct value):
```
def open_lock(deadends, target)
    puts -1 % 10
    
    0
end
```

#### Language used for code
Java and Ruby

#### Expected behavior
In the above example, the correct value is 9.
However, for Java the code returns -1.

You can check the output of ruby code and also Google "-1 % 10" to verify the correct result

#### Screenshots
Java run:
<img width="942" alt="Screenshot 2021-06-04 at 9 26 08 PM" src="https://user-images.githubusercontent.com/5968535/120829837-7d5f9f00-c57b-11eb-93d0-2b4f17cb71bd.png">

Ruby run:
<img width="948" alt="Screenshot 2021-06-04 at 9 26 27 PM" src="https://user-images.githubusercontent.com/5968535/120829880-894b6100-c57b-11eb-8b59-e37a6fd33a1a.png">

#### Additional context

**Comment by lc-kay** [comment]
Hi @hss15 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hss15 Our team has reviewed your report and the output of the modulo depends on how the language defines it. Therefore, please do not compare java to ruby. In addition, -1 is congruent to 9 modulo 10. Thank you for your time.
