### ISSUE TITLE
523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by sudotrigon** [LeetCode-Feedback/LeetCode-Feedback#3737]
#### Your LeetCode username
f1re

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Following test case is wrong:
```
nums = [0]
k = 1
```

#### Code you used for Submit/Run operation
```
class Solution {
public:
 bool checkSubarraySum(vector<int>& A, int k) {
      unordered_set<int> s;
      
      int sum = 0;
      for(int& a: A){
          sum += a;
          
          if(s.count(sum%k)){
              return true;
          }
          
          s.insert(sum%k);
      }
      
      return s.count(0);
  }
};
```

#### Language used for code
C++

#### Expected behavior
The question mentions that "0 is always a multiple of k". 
So the sum of subarray `[0]`, that is equal to 0, is a multiple of k i.e. multiple of 1.
So answer should be true.

But the test case is showing the answer as false.

#### Screenshots
![image](https://user-images.githubusercontent.com/83594686/120841325-fe716300-c588-11eb-8901-547b5e23fba4.png)

#### Additional context
I've validated the question thoroughly, the test case is contradictory with the definition present in question.

**Comment by lc-kay** [comment]
@sudotrigon The problem description states that " return true if nums has a continuous subarray **of size at least two** whose elements sum up to a multiple of k, or false otherwise." In this subarray, the size is 1, therefore, you'd return false. For more information, please check out the problem discuss section.
