### ISSUE TITLE
Missing Test Case - 164. Maximum Gap

### ISSUE THREAD

**Issue by jasminnasit** [LeetCode-Feedback/LeetCode-Feedback#3739]
#### Your LeetCode username

jasminnasit48

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

The wrong solution accepted because we missed this test case
```
input : [15257,15258,15259]
output : 1
```

#### Code you used for Submit/Run operation

```
class Solution {
    public int maximumGap(int[] nums) {
        int max = 0;
        if(nums.length < 2){
            return max;
        }
        int last = 15255;
        Arrays.sort(nums);
        
        for(int i=0; i<nums.length; i++){
            int diff = nums[i]-last;
            if(diff > max){
                max = diff;
            }
            last = nums[i];
        }
        
        return max;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

Above solution is getting accepted since this test case is not added.
ideally, it should not get accepted.

#### Screenshots

![5](https://user-images.githubusercontent.com/24349906/120844594-43979400-c58d-11eb-852d-313071d562bc.PNG)

#### Additional context

submission link : https://leetcode.com/submissions/detail/503021958/

**Comment by lc-kay** [comment]
Hi @jasminnasit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jasminnasit Our team decided to not add this test case because it is the same as #3698. Thank you for your time.
