### ISSUE TITLE
Missing Test Case - 216. Combination Sum III

### ISSUE THREAD

**Issue by armandino** [LeetCode-Feedback/LeetCode-Feedback#3740]
#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The explanation for Example 3 is incorrect. 

- `[1,2,1]` is not a valid combination for this example because `k = 4`, not 3.
- The output is empty because there are no valid combinations that can add up to 1 (`k >= 2` according to the constraints)

> Example 3:
> 
> Input: k = 4, n = 1
> Output: []
> Explanation: There are no valid combinations. [1,2,1] is not valid because 1 is used twice.
>

**Comment by lc-kay** [comment]
Hi @armandino 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @armandino 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
