### ISSUE TITLE
Code template for Racket Min Stack is incorrect

### ISSUE THREAD

**Issue by jbromley** [LeetCode-Feedback/LeetCode-Feedback#3742]
#### Your LeetCode username
jbromley

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the template code provided for the Racket implementation of Min Stack, the function to get the current minimum value in the stack is
```
    ; get-min : -> exact-integer?
    (define/public (get-min) )
```
However, the test harness expects the function to be called `getMin`.

#### Code you used for Submit/Run operation
```
(define min-stack%
  (class object%
    (super-new)
    (init-field)

    (struct stack-item [val min])
    (define stack (list))

    ; push : exact-integer? -> void?
    (define/public (push val)
      (let ([new-min (if (empty? stack)
                         val
                         (min val (stack-item-min (first stack))))])
        (set! stack (cons (stack-item val new-min) stack))))

    ; pop : -> void?
    (define/public (pop)
      (set! stack (rest stack)))

    ; top : -> exact-integer?
    (define/public (top)
      (stack-item-val (first stack)))

    ; get-min : -> exact-integer?
    (define/public (get-min)
      (stack-item-min (first stack)))))
```

#### Language used for code
Racket

#### Expected behavior
I expect that the harness calls the code using the `get-min` class method (this is the preferred convention for names in Racket). Alternately, the code template should have the method renamed to `getMin` (not as good, as camel case is generally not used in Racket).

**Comment by lc-kay** [comment]
Hi @jbromley 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
