### ISSUE TITLE
Missing Test Case - 1507. Reformat Date

### ISSUE THREAD

**Issue by keerthi-aluvala** [LeetCode-Feedback/LeetCode-Feedback#3743]
#### Your LeetCode username

Keerthi_Aluvala

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Question:
Given a date string in the form Day Month Year, where:

Day is in the set {"1st", "2nd", "3rd", "4th", ..., "30th", "31st"}.
Month is in the set {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"}.
Year is in the range [1900, 2100].
Convert the date string to the format YYYY-MM-DD, where:

YYYY denotes the 4 digit year.
MM denotes the 2 digit month.
DD denotes the 2 digit day.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string reformatDate(string date) 
    {
        string s1, s2, s3, result;
        int gap = 0;
        for(int i=0; i<date.length(); i++)
        {
            if(date[i]!=' ')
            {
                if(gap==0)
                    s1 += date[i];
                if(gap==1)
                    s2 += date[i];
                if(gap==2)
                    s3 += date[i];
            }
            if(date[i]==' ')
                gap ++;
        }
        result += s3;
        result += '-';
        unordered_map <string, int>m = 
        {
            {"Jan", 1},
            {"Feb", 2},
            {"Mar", 3},
            {"Apr", 4},
            {"May", 5},
            {"Jun", 6},
            {"Jul", 7},
            {"Aug", 8},
            {"Sep", 9},
            {"Oct", 10},
            {"Nov", 11},
            {"Dec", 12}
        };
        string temp = to_string(m[s2]);
        if(temp.length()==1)
            result += '0';
        result += temp;
        result += '-';   
        if(s1.length()<4)
            result += '0';
        result += s1[0];
        if(s1.length()>3)
            result += s1[1];
        return result;
    }
};
```

#### Language used for code

C++

**Comment by lc-kay** [comment]
@keerthi-aluvala Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
