### ISSUE TITLE
Missing Solution - 990. Satisfiability of Equality Equations

### ISSUE THREAD

**Issue by surikunal** [LeetCode-Feedback/LeetCode-Feedback#3744]
#### Your LeetCode username

kunalsuri

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Well, Here is something we can add for the solution.
According to me, whenever we see a question related to grouping, the first method comes in mind is Union Find and not the DFS(at least for me).
So, I just please request you to add a Union Find Solution in the solution section

I have added a solution too so please consider adding this solution in your article 
Thank you.

#### Code you used for Submit/Run operation
//C++
```
class Solution {
public:
    int findPar(int par[], int i) {
        if (par[i] == i) return i;
        return par[i] = findPar(par, par[i]);
    }
    bool equationsPossible(vector<string>& equations) {
        int par[26];
        for (int i = 0; i < 26; ++i) par[i] = i;
        for (string s: equations) {
            if (s[1] == '=') {
                par[findPar(par, s[0] - 'a')] = findPar(par, s[3] - 'a');
            }
        }
        for (string s: equations)
            if (s[1] == '!' && findPar(par, s[0] - 'a') == findPar(par, s[3] - 'a'))
                return false;
        return true;
    }
};
```
Java
```
class Solution {
    public int find(int[] par, int i) {
        if (par[i] == i)
            return i;
        return par[i] = find(par, par[i]);
    }
    public boolean equationsPossible(String[] equations) {
        int[] par = new int[26];
        for (int i = 0; i < 26; ++i)
            par[i] = i;
        for (String s: equations) {
            if (s.charAt(1) == '=') {
                int par1 = find(par, s.charAt(0) - 'a');
                int par2 = find(par, s.charAt(3) - 'a');
                if (par1 != par2)
                    par[par1] = par2;
            }
        }
        for (String s: equations)
            if (s.charAt(1) == '!')
                if (find(par, s.charAt(0) - 'a') == find(par, s.charAt(3) - 'a'))
                    return false;
        return true;
    }
}
```
#### Language used for code

C++ and Java

**Comment by lc-kay** [comment]
@surikunal Thank you for your feedback. I've relayed this to our team to consider, and this additional approach will be added as soon as we can. I will close this ticket for now and reopen it if further information is needed from your side. We appreciate your time and support.
