### ISSUE TITLE
Not Working Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by kameshkotwani** [LeetCode-Feedback/LeetCode-Feedback#3745]
#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The test case fails in **0** input. In an online compiler other than leetcode, it is working fine.

#### Code you used for Submit/Run operation

```
// palindrome-number
class Solution {
public:
    bool isPalindrome(int x) {
        if (x<0) return false;
        // calculate the number of digits
        const int num_digits = static_cast<int>(floor(log10(x)))+1;
        int msd_mask = static_cast<int>(pow(10,num_digits-1));
        for(int i=0;i<(num_digits/2);i++){
            if(x/msd_mask!=x%10){
                return false;
            }
            x%=msd_mask;
            x/=10;
            msd_mask/=100;
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

**true/1**  should be returned, but it is returning error of type:

Line 6: Char 49: runtime error: -inf is outside the range of representable values of type 'int' (solution.cpp)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:15:49

#### Screenshots

![brave_s4UpzJT35s](https://user-images.githubusercontent.com/36355951/120882582-572b1500-c5f6-11eb-8f83-e991a28dc920.jpg)

![brave_kSEqzkRLWd](https://user-images.githubusercontent.com/36355951/120882592-775ad400-c5f6-11eb-8ca2-bd7cbea785bc.jpg)

**Comment by lc-kay** [comment]
@kameshkotwani We are unable to identify the cause of different results from the local environment and LeetCode's environment. We recommend checking out the problem discuss section and searching out the error message to debug. Thank you for your time.
