### ISSUE TITLE
Missing Test Case - 521. Longest Uncommon Subsequence I

### ISSUE THREAD

**Issue by imadityachandra** [LeetCode-Feedback/LeetCode-Feedback#3749]
#### Your LeetCode username
COVERDRIVE

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ YES] Missing Test Cases 

#### Description of the bug

MY SOLUTION PASSED BUT IT FAILS ON THE TEST CASE abc bca

#### Code you used for Submit/Run operation

```

class Solution {
public:
    int findLUSlength(string a, string b) {
        if(a.length()>b.length())
            return a.length();
        
        if(a.length()<b.length())
            return b.length();
        
        set<char>s(a.begin(),a.end());
        int ans=0;
        for(int i=0;i<b.length();i++)
        {
            if(s.find(b[i])==s.end())
                return a.length();
        }
        
        return -1;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

The correct output of the testcase mentioned[abc,bca] above should be 2 but my output is -1 but is still accepted on your platform.

**Comment by lc-kay** [comment]
Hi @imadityachandra 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @imadityachandra 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
