### ISSUE TITLE
846. Hand of Straights

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#375]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Duplicate question

**Expected behavior**
The problems [846](https://leetcode.com/problems/hand-of-straights/) and [1296](https://leetcode.com/problems/divide-array-in-sets-of-k-consecutive-numbers/) are equivalent. Moreover 846 has an editorial whereas 1296 does not. On the other hand 1296 has hints whereas 846 does not. Also both problems use different tags which ideally should be the same. 

I suggest the problem descriptions be updated to make the users aware of the other questions like has already been done for pairs like [476](https://leetcode.com/problems/number-complement/), [1009](https://leetcode.com/problems/complement-of-base-10-integer/) and [783](https://leetcode.com/problems/minimum-distance-between-bst-nodes/),[530](https://leetcode.com/problems/minimum-absolute-difference-in-bst/) and [1081](https://leetcode.com/problems/smallest-subsequence-of-distinct-characters/), [316](https://leetcode.com/problems/remove-duplicate-letters/).

Unlike in #252 where quadratic solution could work in one of the two, the difference in constraint of array length (10^4 and 10^5) makes no difference as only linear time solution are expected to work in both problems. In fact there is similar discrepancy with 1081 having 1000 length limit and 316 having maximum length of 8600 in test case 279.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. This similarity issue between problem 846 and 1296 was already reported by another user in task #371 . We appreciate your support.
