### ISSUE TITLE
Missing Test Case - 713. Subarray Product Less Than K

### ISSUE THREAD

**Issue by Aman208** [LeetCode-Feedback/LeetCode-Feedback#3750]
#### Your LeetCode username
Aman208

#### Category of the bug
- [ ] Question
- [ YES] Solution
- [ ] LangSuage
- [ ] Missing Test Cases 

#### Description of the bug
```
Given Array Constraints  Array Elements can vary from 0 to 1000 both inclusive.
0 <= nums[i] < 1000

All test cases that contain an array element Zero are giving incorrect answers.

ForExample  if take test case like
nums[] = [0,10,5]
k=10

Correct answer showing is 6
Ideally it should be 4 => [0], [0,10] ,[0,10,5] ,[5]

Likewise, test case
nums[] =[0,1,1,1,1]
k=1

 ```

#### Code you used for Submit/Run operation
```
int numSubarrayProductLessThanK(vector<int>& nums, int k) {
        
        int p=1,l=0,res=0;
        
       if(k<=1) return 0;
        
        for(int r=0;r<nums.size();r++)
        {   p=p*nums[r];
            while(p>=k)
            {   p=p/nums[l];
                l++;
            }
            res+=(r-l+1);
        }
        return res;
        
        
    }

```

#### Language used for code
C++

#### Expected behavior
```
nums[] = [0,10,5]
k=10

Correct answer showing is 6
Ideally it should be 4 => [0], [0,10] ,[0,10,5] ,[5]

```

**Comment by lc-kay** [comment]
Hi @Aman208 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Aman208 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Aman208** [comment]
*amankumar208*
https://leetcode.com/amankumar208/
