### ISSUE TITLE
Typo/markup error in description - 1551. Minimum Operations to Make Array Equal

### ISSUE THREAD

**Issue by maverickreal** [LeetCode-Feedback/LeetCode-Feedback#3751]
Original problem statement:-
```
You have an array arr of length n where arr[i] = (2 * i) + 1 for all valid values of i (i.e. 0 <= i < n).

In one operation, you can select two indices x and y where 0 <= x, y < n and subtract 1 from arr[x] and add 1 to arr[y] (i.e. perform arr[x] -=1 and arr[y] += 1). The goal is to make all the elements of the array equal. It is guaranteed that all the elements of the array can be made equal using some operations.

Given an integer n, the length of the array. Return the minimum number of operations needed to make all the elements of arr equal.

```
At line number 2, the 'y' as in  '...indices x and y where...' actually appears 'v' and not y on the website, though on copying/pasting the text it is selected as 'y'. This happens only with the one occurrence of 'y' mentioned.
my leetcode profile: https://leetcode.com/maverick09/
![Screenshot from 2021-06-05 20-51-44](https://user-images.githubusercontent.com/57585749/120896583-e3adf580-c63f-11eb-883d-af2642b433e7.png)

**Comment by lc-kay** [comment]
@maverickreal Unfortunately, I am unable to reproduce the same on my end. Please refresh your browser and reset zoom. Thank you for your time. 
<img width="635" alt="Screen Shot 2021-06-08 at 1 12 40 PM" src="https://user-images.githubusercontent.com/70870126/121251055-4cbd8500-c85b-11eb-96ec-c3920872d1cd.png">
