### ISSUE TITLE
783. Minimum Distance Between BST Nodes | Missing TestCase

### ISSUE THREAD

**Issue by Chirag-Shilwant** [LeetCode-Feedback/LeetCode-Feedback#3753]
#### Your LeetCode username

chirags_30

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug

My solution passed for all testcases and gave an AC but one test case I figured out where my solution can fail but that test case is missing.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
    int ans=INT_MAX;
    vector<int>V;
    
    void dfs(TreeNode* root)
    {
        if(root==NULL) return;
        
        dfs(root->left);
        V.push_back(root->val);
        dfs(root->right);
    }
    
    int minDiffInBST(TreeNode* root) {
        
        dfs(root);
        
        for(int i=1; i<V.size()-1; i++)
        {
            ans = min({ans, abs(V[i]-V[i-1]), abs(V[i]-V[i+1])});
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My solution passed for all testcases and gave an AC but one test case I figured out where my solution can fail but that test case is missing. The testcase is [10,null,11]. And as you can see if I try my testcase on console input it shows WA but as this testcase was missing in your list of testcases my bug code got Accepted.
![image](https://user-images.githubusercontent.com/48115585/120898163-4ce53700-c647-11eb-849b-ec0f6791f5ed.png)

#### Screenshots

As you can see, my solution got accepted.
![image](https://user-images.githubusercontent.com/48115585/120898108-19a2a800-c647-11eb-9abd-ceebce6e8001.png)

#### Additional context

The missing testcase is [10,null,11]

**Comment by ashutosh16071997** [comment]
Fuck off

**Comment by lc-kay** [comment]
Hi @Chirag-Shilwant 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Chirag-Shilwant 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
