### ISSUE TITLE
Typos for Problem 1383

### ISSUE THREAD

**Issue by YimingCuiCuiCui** [LeetCode-Feedback/LeetCode-Feedback#3754]
#### Your LeetCode username

GuMingDiaoYu

#### Category of the bug
- [1] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a typo for the constraints of input for problem 1383 Maximum Performance of a Team. It should be "1 <= k <= n <= 10^5". The following attachment is the screenshot. 
![image](https://user-images.githubusercontent.com/23092336/120912495-a193ac80-c65d-11eb-8020-b6e26d1c58fc.png)
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @YimingCuiCuiCui 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @YimingCuiCuiCui 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
