### ISSUE TITLE
Invalid Constraint - 733. Flood Fill

### ISSUE THREAD

**Issue by av1shek** [LeetCode-Feedback/LeetCode-Feedback#3755]
#### Your LeetCode username
av1shek

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Invalid Constraints

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int m, n;
    bool isValid(int x, int y, vector<vector<int>>& image, vector<vector<int>>& vis, int col)
    {
        if(x>=m || y>=n) return false;
        if(x<0 || y<0) return false;
        if(vis[x][y]) return false;
        return image[x][y]==col;
    }
    int dx[4] = {-1, 1, 0, 0};
    int dy[4] = {0, 0, -1, 1};
    void dfs(vector<vector<int>>& image, int x, int y, int nc, int col, vector<vector<int>>& vis)
    {
        vis[x][y] = 1;
        image[x][y] = nc;
        for(int i=0;i<4;i++)
        {
            int xx = x+dx[i];
            int yy = y+dy[i];
            if(isValid(xx, yy, image, vis, col))
                dfs(image, xx, yy, nc, col, vis);
        }
    }
    vector<vector<int>> floodFill(vector<vector<int>>& image, int sr, int sc, int newColor) {
        m = image.size();
        n = image[0].size();
        
        vector<vector<int> > vis(n, vector<int>(n, 0));
        dfs(image, sr, sc, newColor, image[sr][sc], vis);
        return image;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
In the constraints it is given that
``` m == image.length ```
``` n == image[i].length ```
Also 
``` 0 <= sr <= m ```
``` 0 <= sc <= n ``` 
is given which can not be possible if we consider 0 based indexing or 1 based indexing.

If we conder 0 based indexing it should be :
``` 0 <= sr < m ```
``` 0 <= sc < n ``` 
or If we consider 1 based indexing then it should be:
``` 1 <= sr <= m ```
``` 1 <= sc <= n ``` 

#### Screenshots

![image](https://user-images.githubusercontent.com/59140024/120918430-07218080-c6d2-11eb-8be8-00b551da951d.png)

#### Additional context
According to current constraint 
``` 
[[1]]
1
1
2
``` 
The above input should be a valid testcase for which my accepted [solution](https://leetcode.com/submissions/detail/503792615/) gives runtime error of index out of bound.

**Comment by lc-kay** [comment]
Hi @av1shek 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @av1shek 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
