### ISSUE TITLE
Missing Test Case - 1689. Partitioning Into Minimum Number Of Deci-Binary Numbers

### ISSUE THREAD

**Issue by vcmkrtchyan** [LeetCode-Feedback/LeetCode-Feedback#3756]
#### Your LeetCode username

vcmkrtchyan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The constraints say that the input string may be of length up to 10000, but the test cases are for much shorter Strings. Thus, if we check until 100 instead of the length of the input string, the test cases pass, but the solution is invalid. For example, the following test case should not pass.
"11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111119"

#### Code you used for Submit/Run operation

```
// Partitioning Into Minimum Number Of Deci-Binary Numbers
class Solution {
    public int minPartitions(String n) {
        int result = 0;
        
        for (int i = 0; i < Math.min(100, n.length()); i++) {
            if (n.charAt(i) - '0' > result) {
                result = n.charAt(i) - '0';
            }
        }
        
        return result;
    }
}
```

#### Language used for code

Java

**Comment by lc-kay** [comment]
Hi @vcmkrtchyan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vcmkrtchyan 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
