### ISSUE TITLE
Missing Test Case - 128. Longest Consecutive Sequence

### ISSUE THREAD

**Issue by Kunal-Saha** [LeetCode-Feedback/LeetCode-Feedback#3757]
#### Your LeetCode username
sahakunal1803

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Longest Consecutive Sequence

Solution

class Solution {
public:
    int longestConsecutive(vector<int>& nums) {
        int maxi=0;
        set<int>s;
        for(int x:nums)
        {
            s.insert(x);
        }
        for(int x:nums)
        {
            if(!s.count(x-1))
            {
                int curr=x;
                int ans=1;
                while(s.count(curr+1))
                {
                    curr+=1;
                    ans+=1;
                }
                maxi=max(maxi,ans);
            }
        }
        return maxi;
    }
};
```

#### Language used for code
 CPP

**Comment by lc-kay** [comment]
@Kunal-Saha Please post your solution in the problem discuss section. 

We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
