### ISSUE TITLE
Missing Test Case or Not Clear Constrains - 833. Find And Replace in String

### ISSUE THREAD

**Issue by chenyuzhcy** [LeetCode-Feedback/LeetCode-Feedback#3758]
#### Your LeetCode username

ciccyzcy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description is missing some information, not clear if the replacement string could overlap.

for example, in this test case:

"abcd"
[0, 1]
["ab", "bc"]
["eee", "ffff"]

Two of my submission passed but returns different answers for this test case:
submisstion1 returns: "affffd"
submission2 returns:"eeeffffd"
and the console expected:  "affffd"

#### Code you used for Submit/Run operation

submission 1
```python
  def findReplaceString(self, s, indexes, sources, targets):
          replacement = zip(indexes, sources, targets)
          replacement.sort(key = lambda x: x[0], reverse = True)
          
          for i, source, target in replacement:
              length = len(source)
              if s[i:i+length] == source:
                  s = s[0:i] + target + s[i+length:]
          
          return s
```

submission2
```python
  def findReplaceString(self, S, indexes, sources, targets):
          ist = sorted(zip(indexes, sources, targets), key=lambda x:x[0])
          start = 0
          res = []
          for i, s, t in ist:
              res.append(S[start:i])
              if S[i:i+len(s)] == s:
                  res.append(t)
              else:
                  res.append(S[i:i+len(s)])
              start = i+len(s)
          return "".join(res) + S[start:]
```

#### Language used for code

python

#### Expected behavior

This case should either be added to the test cases or be treated as an invalid test case.

**Comment by lc-kay** [comment]
Hi @chenyuzhcy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by semin-park** [comment]
First off, thank you for your efforts in maintaining Leetcode!

I solved this question on May 22nd and the test case was all great. But it seems like someone has added an invalid test case since.

The problem clearly states that "it's guaranteed that there won't be any overlap in replacement: for example, `s = "abc"`, `indexes = [0, 1]`, `sources = ["ab","bc"]` is not a valid test case.".

And yet, this very invalid test case has been recently added in the actual test case. I think this test case should be rolled back.

**Comment by anirudhjain75** [comment]
I am facing the same issue as well. The username is Cyna123 just in case you'd wanna know

**Comment by lc-kay** [comment]
@chenyuzhcy We have fixed the test case validator for this problem. The test case will now lead to a test case error. Thank you for your time.

**Comment by chenyuzhcy** [comment]
@lc-kay Thanks for fixing this so fast!
