### ISSUE TITLE
Incorrect solution validator at 89. Gray Code

### ISSUE THREAD

**Issue by kaga2** [LeetCode-Feedback/LeetCode-Feedback#3759]
#### Your LeetCode username
jcfernandez

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The output is not unique and looks like the solutions validator don't accept different outputs.

#### Code you used for Submit/Run operation
[My submitions](https://leetcode.com/submissions/detail/504178025/)
or
[LeetCode Playground](https://leetcode.com/playground/2wUAi5Ha)

#### Language used for code
C++

#### Expected behavior
My solution should be accepted, even I implemented a validator that checks all the conditions of a valid n-bit gray code sequence against my output, code at [LeetCode Playground](https://leetcode.com/playground/2wUAi5Ha)

For example, for the test case n = 3:
- expected output: [0,1,3,2,6,7,5,4]
- my output: [0,1,3,7,5,2,6,4]
- number of bits at my output: [0, 1, 2, 3, 2, 1, 2, 1]

For example, for the test case n = 4:
- expected output: [0,1,3,2,6,7,5,4,12,13,15,14,10,11,9,8]
- my output: [0,4,10,1,6,13,3,7,15,11,5,14,9,2,12,8]
- number of bits at my output: [0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 2, 3, 2, 1, 2, 1]

**Comment by lc-kay** [comment]
@kaga2 For support on your code and debugging, please refer to the problem discuss section. Thank you for your time.
