### ISSUE TITLE
106. Construct Binary Tree from Inorder and Postorder Traversal (PROBLEM)

### ISSUE THREAD

**Issue by HarshitKesar** [LeetCode-Feedback/LeetCode-Feedback#376]
My Solution :- 
```
class Solution {
public:
    TreeNode* buildTree(vector<int>& inorder, vector<int>& postorder) {
        return buildTree(inorder, postorder, 0, inorder.size()-1);
    }
    
    TreeNode* buildTree(vector<int> in, vector<int> post, int iStart, int iEnd){
        if(iStart > iEnd){
            return NULL;
        }
        static int postIndex = in.size()-1;
        
        TreeNode *root = new TreeNode(post[postIndex--]);
        int idx;
        for(int i=iStart; i<=iEnd;i++){
            if(root->val == in[i]){
                idx = i;
                break;
            }
        }
        root->right = buildTree(in, post, idx+1, iEnd);
        root->left = buildTree(in, post, iStart, idx-1);
        return root;
    }
};
```

```
Input :    [-1]
              [-1]
```
Problem:-  When I run this input manually (using RunCode on leetcode) it works fine and shows ACCEPTED.
but when I submit this code it shows RunTime Error. Please resolve this issue. Thanks.

**Comment by HarshitKesar** [comment]
This is my code link please check this out: - 

https://leetcode.com/submissions/detail/345951121/

**Comment by CooperCooperCooper** [comment]
Hi @HarshitKesar ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by HarshitKesar** [comment]
Hii, 
Have you got my problem ???

Am attaching the screenshot of my problem please check this also !!!

![leetProblem](https://user-images.githubusercontent.com/43781453/83263344-0eb76b00-a1dc-11ea-9bb8-d6536dd1bed9.jpg)

**Comment by CooperCooperCooper** [comment]
Hi @HarshitKesar ,
Thank you for your time. The error is caused by the mishandle of variable of idx in your code. Please update your code accordingly. We appreciate your support.
