### ISSUE TITLE
Missing Test Case - 746. Min Cost Climbing Stairs

### ISSUE THREAD

**Issue by Aatmsaat** [LeetCode-Feedback/LeetCode-Feedback#3763]
#### Your LeetCode username

aatmsaat

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✓] Missing Test Cases 

#### Description of the bug

When there are only two elements i.e. `cost.length = 2` then it should give wrong answer for test case [4, 1] for my solution but it got accepted

#### Code you used for Submit/Run operation

```
class Solution:
    def minCostClimbingStairs(self, cost: List[int]) -> int:
        n = len(cost)
        if n==2:
            return cost[0]
        cost.append(0)
        for i in range(2, n+1):
            cost[i]+=min(cost[i-1], cost[i-2])
        return cost[-1]
```

#### Language used for code

Python

#### Expected behavior

For the test case [4, 1], the Anwer should be 1 , but my solution returns 4 instead, This solution still got accepted
Same for test cases :- [7, 3], [20, 1], [54, 10]

#### Screenshots

![Missing_test_case](https://user-images.githubusercontent.com/47090589/121005779-c860f880-c7ad-11eb-954f-67f6a03da3b8.jpg)
![IMG_20210607_163347](https://user-images.githubusercontent.com/47090589/121006212-42917d00-c7ae-11eb-9550-2bff7b9ee5ed.jpg)

#### Additional context

When  cost.length = 2 , and 1st is greater than 2nd number answer should be minimum of both but there are no test cases like that so it always gives result of 1st number

**Comment by lc-kay** [comment]
Hi @Aatmsaat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
