### ISSUE TITLE
Solution 1887. Reduction Operations to Make the Array Elements Equal

### ISSUE THREAD

**Issue by parvg555** [LeetCode-Feedback/LeetCode-Feedback#3766]
#### Your LeetCode username
parvg555

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This is solution for problem 1887. Reduction Operations to Make the Array Elements Equal.
The code is 100% faster and space efficient than other solutions. 

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int reductionOperations(vector<int>& nums) {
        if(nums.size()==1){
            return 0;
        }
        sort(nums.rbegin(),nums.rend());
        int ans = 0;
        for(int i=1;i<nums.size();i++){
            if(nums[i]!=nums[i-1]){
                ans+=i;
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Currently the solution is missing for the problem. This is the required solution for the problem.

**Comment by LC-Pamela** [comment]
Hi @parvg555 
Thank you for reaching out to us. If you'd like to share your submission, please share it in the [problem's discuss section](https://leetcode.com/problems/reduction-operations-to-make-the-array-elements-equal/discuss/?currentPage=1&orderBy=newest_to_oldest&query=). We opened this Github repo specifically for content issues such as missing test cases.
