### ISSUE TITLE
Complexity Analysis - 494. Target Sum

### ISSUE THREAD

**Issue by Shogun-1** [LeetCode-Feedback/LeetCode-Feedback#3767]
#### Your LeetCode username

shogunurus

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

- Error in **Approach №4 1D Dynamic Programming**, Complexity Analysis section: 
"Space complexity : `O(n)`. dp array of size `n` is used."
We used dp array of size `l` but not `n`, where `l` refers to the range of `sum` possible. So the space complexity should be:
"Space complexity : `O(l)`. dp array of size `l` is used."

#### Code you used for Submit/Run operation

Code for the fourth approach from the Article for your convenience:
```
public class Solution {
    public int findTargetSumWays(int[] nums, int S) {
        int[] dp = new int[2001];
        dp[nums[0] + 1000] = 1;
        dp[-nums[0] + 1000] += 1;
        for (int i = 1; i < nums.length; i++) {
            int[] next = new int[2001];
            for (int sum = -1000; sum <= 1000; sum++) {
                if (dp[sum + 1000] > 0) {
                    next[sum + nums[i] + 1000] += dp[sum + 1000];
                    next[sum - nums[i] + 1000] += dp[sum + 1000];
                }
            }
            dp = next;
        }
        return S > 1000 ? 0 : dp[S + 1000];
    }
}
```

#### Language used for code

Java

#### Expected behavior

Not needed.

#### Screenshots

Not needed.

#### Additional context

Not needed.

**Comment by lc-kay** [comment]
Hi @Shogun-1 
Thank you for reaching out to us. I've relayed this issue to our team to investigates.
