### ISSUE TITLE
1328. Break a Palindrome

### ISSUE THREAD

**Issue by ilnarag** [LeetCode-Feedback/LeetCode-Feedback#3768]
#### Your LeetCode username
ilnarag

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test case which checks that the middle character of the palindrome is handled correctly is missing.
A string which remains a palindrome after replacement is accepted as a correct answer.
Example: "ada".

#### Code you used for Submit/Run operation

```
    public String breakPalindrome(String palindrome) {
        if(palindrome.length() == 0 || palindrome.length() == 1)
            return "";
        
        var builder = new StringBuilder(palindrome);
        
        for(int i = 0; i < palindrome.length(); i++)
        {
            if(palindrome.length() % 2 == 1 && i == (palindrome.length() / 2))
            {
                var best = getBestChar(palindrome.charAt(i), palindrome.charAt(i - 1));
                
                if(best < palindrome.charAt(i))
                {
                    builder.setCharAt(i, best);
                    return builder.toString();
                }
            }
            
            else if(palindrome.charAt(i) != 'a')
            {
                builder.setCharAt(i, 'a');
                return builder.toString();
            }
        }
        
        builder.setCharAt(builder.length() - 1, 'b');
        
        return builder.toString();
    }
    
    private char getBestChar(char current, char neighbor)
    {
        for(int i = 0; i < 26; i++)
        {
            var c = (char)('a' + i);
            
            if(c != current && c != neighbor)
                return c;
        }
        
        return 'z';
    }
```

#### Language used for code
Java 

#### Expected behavior

The answer should be "adb", but my code returns "aba", which is a palindrome.

**Comment by lc-kay** [comment]
Hi @ilnarag 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ilnarag 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
