### ISSUE TITLE
Missing Test Case - 746. Min Cost Climbing Stairs

### ISSUE THREAD

**Issue by Kunal-Saha** [LeetCode-Feedback/LeetCode-Feedback#3769]
#### Your LeetCode username
sahakunal1803

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minCostClimbingStairs(vector<int>& cost) {
        for(int i=2;i<cost.size();i++)
        {
            cost[i]+=min(cost[i-1],cost[i-2]);
        }
        return min(cost[cost.size()-1],cost[cost.size()-2]);
    }
};
```

#### Language used for code
cpp

**Comment by lc-kay** [comment]
@Kunal-Saha Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
