### ISSUE TITLE
1197. Minimum Knight Moves 

### ISSUE THREAD

**Issue by rakeshswarankar** [LeetCode-Feedback/LeetCode-Feedback#377]
**What kind of the bug**
- [ 1197] problem
- [ ] solution
- [Java ] language

**Describe the bug**
One test case pass when I run using custom test case but giving TLE error when I submitting the solution.

**what language is your code written in**
Java

<img width="1280" alt="Screen Shot 2020-05-28 at 4 48 06 PM" src="https://user-images.githubusercontent.com/12644234/83192461-90879580-a103-11ea-9b59-2bb72fb3d35f.png">

**The code you submit/run**
```
// Minimum Knight Moves
class Solution {
    int directions[][]={{-1,-2},{-2,-1},{1,-2},{2,-1},{-2,1},{-1,2},{1,2},{2,1}};
    public int minKnightMoves(int x, int y) {
        
        int st[]= {0,0};
        int dst[]={x,y};
        
        if(Arrays.equals(st,dst))
            return 0;
        Set<String> processed= new HashSet<>();
        Queue<int[]> queue= new LinkedList<>();
        queue.add(st);
        
        int count=0;
        int tmp[]= new int[2];
        while(!queue.isEmpty())
        {
            int size=queue.size();
            count++;
            for(int i=0;i<size;i++)
            {
                int curr[]=queue.poll();
                
                
                for(int d[]:directions){
                    tmp[0]=d[0]+curr[0];
                    tmp[1]=d[1]+curr[1];
                    String key= tmp[0]+"-"+tmp[1];
                    if(processed.contains(key))continue;
                    if(Arrays.equals(tmp,dst))
                        return count;
                    queue.offer(tmp.clone());
                    processed.add(key);
                }
            }
        }
        return count;
    }
}
```

**Expected behavior**
If test case pass during running the code then it should not give Time Limit Exceed exception during submission.

**Screenshots**
I have attached the screen shot as well. Where test case is passed when I did using custom test case but giving TLE while submitting the solution.

**Additional context**
This is the common issue I faced during 2-3 questions with Leet code. Please improve this.

**Comment by CooperCooperCooper** [comment]
Hi @rakeshswarankar ,
Thank you for reaching out to us. Getting Accepted for "Run Code" but TLE for "Submit" is normal behavior for code that needs further time optimization. When you click on "Run Code", your code only runs on 1 test case, whereas when you click on "Submit", your code runs on all test cases. I hope this helps. We appreciate your support.
