### ISSUE TITLE
Missing Test Case: 65. Valid Number

### ISSUE THREAD

**Issue by KissShane** [LeetCode-Feedback/LeetCode-Feedback#3770]
#### Your LeetCode username
KissShane

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Missing test cases for numbers "1E+7"

#### Code you used for Submit/Run operation
OJ will accept the code below, but it should not.
For test case like: "1E+7", the below solution will not accept.

```
class Solution {
    public boolean isNumber(String s) {
        boolean eSeen = false, numSeen = false, pointSeen = false;
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (Character.isDigit(c)) numSeen = true;
            else if (c == 'e' || c == 'E') {
                if (eSeen || !numSeen) return false;
                eSeen = true;
                numSeen = false;
            } else if (c == '.') {
                if (pointSeen || eSeen) return false;
                pointSeen = true;
            } else if (c == '+' || c == '-') {
                if (i != 0 && s.charAt(i - 1) != 'e') return false;
            } else return false;
        }
        return numSeen;
    }
}
```

#### Language used for code
Java

#### Expected behavior
For test case like: "1E+7", it should think it is a valid number.

**Comment by dallmeyer** [comment]
At first I was ready to say that the `+` cannot be present in `1E+7` for it to be a valid number, but after re-reading the description I think you are technically following the specifications for a valid number. 

For the `e`/`E` portion of a valid number, the problem specifies "(Optional) An 'e' or 'E', followed by an **integer**." But by the problem's own definition:
> An integer can be split up into these components (in order):
> - (Optional) A sign character (either '+' or '-').
> - One or more digits.

So if you take this literally, `+7` counts as an integer and therefore is valid to follow the `e`/`E`. 

Based on the test cases, I don't think this was the intended interpretation, so probably the problem statement needs to be clarified. Maybe simplest to change `(Optional) An 'e' or 'E', followed by an integer.` -> `(Optional) An 'e' or 'E', followed by one or more digits.`

**Comment by KissShane** [comment]
I am afraid you miss-intepreted what I was saying? The description says 3e+7 is a valid number, so why not 1E+7? Only difference is Uppercase e.

**Comment by dallmeyer** [comment]
Oh wow, yeah I totally overlooked that sample valid number. Then yes, I think you are right the solution is incorrectly handling this test case!

**Comment by lc-kay** [comment]
@dallmeyer @KissShane Thank you for your time. Currently, we are no longer accepting new test cases for this problem. Thank you for your time.
