### ISSUE TITLE
Problem in writeup of space complexity of  Min Cost Climbing Stairs

### ISSUE THREAD

**Issue by ashageorgesj** [LeetCode-Feedback/LeetCode-Feedback#3771]
#### Your LeetCode username

ashag

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The space complexity of approach 2(top-down dynamic programming) in the solution of Min Cost Climbing stairs. The example given for space complexity is incorrect. minimumCost(1000) will call minimumCost(999) and not minimumCost(9999). Similarly, minimumCost(9998) is not the one called but minimumCost(998).

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by ashageorgesj** [comment]
![image](https://user-images.githubusercontent.com/25963723/121102775-525f9000-c7b3-11eb-9ac3-33c28f84121f.png)

**Comment by hamirmahal** [comment]
I think it should say
> minimumCost(10000)

instead of

> minimumCost(1000)

**Comment by ashageorgesj** [comment]
Yes, that is also fine. They had an example about that many number of steps.

**Comment by LC-Sue** [comment]
Hi @ashageorgesj 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
