### ISSUE TITLE
Missing Test Case - 55. Jump Game

### ISSUE THREAD

**Issue by bhas-tech** [LeetCode-Feedback/LeetCode-Feedback#3772]
#### Your LeetCode username
 dream-google

#### Category of the bug
- [ 55. Jump Game] Question
- [ ] Solution
- [ Java ] Language
- [ 1] Missing Test Cases 

#### Description of the bug
 If point in time we get value zero , which mean we can not jump further. Now what if the array has only one element , which is zero ,, [0]. Expected output should be false right, since from zero we can not jump.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean canJump(int[] nums) {
        int maxRechable = 0;
        if(nums.length == 1 ){
            if(nums[0] == 0){
                return false;
            }
            return true;
        }

        for(int i=0;i<nums.length;i++){
            if(i == maxRechable && i !=nums.length -1){
                maxRechable = nums[i];
            }
            if(maxRechable == 0){
                return false;
            }
            maxRechable = Math.max(maxRechable, i+nums[i]);
        }
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior
 When there is only one element in array and it is zero, system should return false. Since true mean we can jump, but from  zero we can not jump

#### Screenshots
<img width="746" alt="Screenshot 2021-06-08 at 7 41 54 AM" src="https://user-images.githubusercontent.com/73681994/121111717-02bdaa80-c82d-11eb-93f5-f8164127ba90.png">

<img width="435" alt="Screenshot 2021-06-08 at 7 41 47 AM" src="https://user-images.githubusercontent.com/73681994/121111764-1537e400-c82d-11eb-8152-79c5cd7d6ccc.png">

**Comment by dallmeyer** [comment]
The question asks you to "Determine if you are able to reach the last index". So with your example of an array of length 1, it doesn't really matter how far you can jump from that point because you've already reached the last index (no jumps needed)

**Comment by lc-kay** [comment]
@bhas-tech The expected answer is correct. Please refer to @dallmeyer explanation or the problem discuss section for further support. Thank you for your time.
