### ISSUE TITLE
Problem in Climbing Stairs solution psoted

### ISSUE THREAD

**Issue by riddhij16** [LeetCode-Feedback/LeetCode-Feedback#3773]
#### Category of the bug
- [ ] Question
- [ ] Solution

#### Description of the bug

Solutions posted needs to be updated 
Approach 5 will show integer overflow starting from n=35 i.e Runtime error for c++ code

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int climbStairs(int n){
        vector<vector<long>>q={{1,1},{1,0}};
        vector<vector<long>> res=pow(q,n); 
        return int(res[0][0]);
    }
   vector<vector<long>> pow(vector<vector<long>> a, int n) {
        vector<vector<long>>ret = {{1, 0}, {0, 1}};//initialize with identity mat
        while (n > 0) {
            if ((n & 1) == 1) {
                ret = multiply(ret, a);
            }
            n >>= 1; // n=n/2
            a = multiply(a, a);
        }
        return ret;
    }
    vector<vector<long>> multiply(vector<vector<long>> a, vector<vector<long>> b) {
        vector<vector<long>> c(2,vector<long>(2,0));
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 2; j++) {
                c[i][j] = a[i][0] * b[0][j] + a[i][1] * b[1][j];
            }
        }
        return c;
    }
};

```

#### Language used for code
 Error in only c++

#### Expected behavior

This will not show error.. and is accepted

#### Screenshots

![image](https://user-images.githubusercontent.com/52314570/121137505-54c5f680-c854-11eb-9068-a8e343101f4b.png)

![image](https://user-images.githubusercontent.com/52314570/121137744-9b1b5580-c854-11eb-9b1f-51dcd0305cf9.png)

**Comment by lc-kay** [comment]
@riddhij16 I've run your code and the test case and it was accepted. Please try it again and let me know if it still receives Runtime Error on your end. 
<img width="635" alt="Screen Shot 2021-06-08 at 1 12 40 PM" src="https://user-images.githubusercontent.com/70870126/121404907-47227680-c911-11eb-9a88-0cebff370975.png">
