### ISSUE TITLE
Missing Test Case - 1398. Customers Who Bought Products A and B but Not C

### ISSUE THREAD

**Issue by gzsuyu** [LeetCode-Feedback/LeetCode-Feedback#3777]
#### Your LeetCode username

gzsuyu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

```
if user has bought 'A' or 'B' more than one time, then some solutions may not work. 
```

#### Code you used for Submit/Run operation

```
SELECT o.customer_id, r.customer_name
FROM Orders o JOIN Customers r
ON o.customer_id = r.customer_id
GROUP BY customer_id
HAVING SUM(CASE WHEN product_name = 'A' THEN 1 ELSE 0 END) = 1 
    AND SUM(CASE WHEN product_name = 'B' THEN 1 ELSE 0 END) = 1 
    AND SUM(CASE WHEN product_name = 'C' THEN 1 ELSE 0 END) = 0 
```

#### Language used for code

MySQL

#### Expected behavior

This should failed because it didn't take the scenario I mentioned as 'if user has bought 'A' or 'B' more than one time. '

#### Additional context

```
test case expected as 

{"headers":{"Customers":["customer_id","customer_name"],"Orders":["order_id","customer_id","product_name"]},"rows":{"Customers":[[1,"Daniel"],[2,"Diana"],[3,"Elizabeth"],[4,"Jhon"]],"Orders":[[10,1,"A"],[20,1,"B"],[30,1,"D"],[40,1,"C"],[50,2,"A"],[60,3,"A"],[70,3,"B"],[80,3,"A"],[90,4,"C"]]}}

```

**Comment by lc-kay** [comment]
Hi @gzsuyu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
