### ISSUE TITLE
Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by timurabdurafeev** [LeetCode-Feedback/LeetCode-Feedback#3778]
#### Your LeetCode username
greentim

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
the ListNode class definition looks wrong

#### Language used for code
Python3 

#### Expected behavior
```
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, x = 0, next = None):
#         self.val = x
#         self.next = next
```

**Comment by timurabdurafeev** [comment]
well, the idea is to have the ability to quickly initialize a headA and headB input parameters, when I play with this task outside of the LeetCode.

**Comment by lc-kay** [comment]
@timurabdurafeev The class definition is correct. Please check out the discuss section for further support or raise your question there. Thank you for your time.
