### ISSUE TITLE
Approach 3: One-pass Hash Table

### ISSUE THREAD

**Issue by nyolamike** [LeetCode-Feedback/LeetCode-Feedback#3779]
#### Your LeetCode username
iamnyola@gmail.com

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the [https://leetcode.com/problems/two-sum/](url)  Two Sum, problem
The third discussed solution i.e Approach 3: One-pass Hash Table,
I find that this solution is not exactly right because it misses out on checking
compliments of earlier elements because there is no forward check on element compliments

#### Code you used for Submit/Run operation
```
public int[] twoSum(int[] nums, int target) {
    Map<Integer, Integer> map = new HashMap<>();
    for (int i = 0; i < nums.length; i++) {
        int complement = target - nums[i];
        if (map.containsKey(complement)) {
            return new int[] { map.get(complement), i };
        }
        map.put(nums[i], i);
    }
    throw new IllegalArgumentException("No two sum solution");
}
```

#### Additional context
Please this solution needs to be revised

**Comment by lc-kay** [comment]
Hi @nyolamike 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@nyolamike Our team has updated this solution article. For more clarification, Suppose, we given an array: [4, 10, 10, 10, 2] and our target is 6. Here, we'll find our answer on a final iteration (while looking at the final element in the array): 4 + 2 = 6, so the answer is [0, 4] (that's required indices). The key part here is that we don't need to perform one more forward pass while looking for a complement to 4 after we scanned the whole array. Eventually, we'll get our solution without any additional forward passes.
