### ISSUE TITLE
Wrong test case output for 108. Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by dpritam1986** [LeetCode-Feedback/LeetCode-Feedback#378]
[0,1,2,3,4,5]  this input with below code generates  -  output as Binary search tree -     [3,2,5,1,null,4]   
Let code console giving me Wrong Answer .. 

However  if I compile this output with leetcode problem  - 98. Validate Binary Search Tree    this is passing the test  it indicates that      [3,2,5,1,null, 4]     is correct BINARY SEARCH TREE
Leetcode need to correct on  this input -  [0,1,2,3,4,5]    -- this is valid BST tree output   [3,2,5,1,null,4]   
![98ValidatedOutputOf108toinputAs98](https://user-images.githubusercontent.com/32959925/83197307-4acecb00-a10b-11ea-91a7-14e4360a39d7.jpg)
![108ArrayToBST](https://user-images.githubusercontent.com/32959925/83197309-4b676180-a10b-11ea-963d-653785b9c7d4.jpg)

**Comment by CooperCooperCooper** [comment]
Hi @dpritam1986 ,
Thank you for reaching out to us. To help us take a deeper look into this issue, please share your code here with us.

**Comment by dpritam1986** [comment]
Hi Please find code below .

output from this code when compiled thru  # 98. Validate Binary Search
Tree   it
passed

class Solution {
    public TreeNode sortedArrayToBST(int[] nums) {

        TreeNode root=null;

        if(nums.length <= 0) return root;

        if(nums.length > 0){

            int low =0;
            int high = nums.length-1;
             int mid = low+(high-low)/2;
             root = addNode(root , nums[mid]);
            int leftItr = mid;
            while(mid < high ){
                leftItr =leftItr-1;
                if(low <=leftItr ){
                   root=addNode(root , nums[leftItr]);
                }

                if(mid < high){
             root=addNode(root , nums[high--]);
                }

            }




        }
        return root;
        }


        public TreeNode addNode(TreeNode node ,int data){

            if(node == null){
                return new TreeNode(data);
            }


            if(data < node.val){
                node.left = addNode(node.left ,data);
            }else if(data > node.val){
                 node.right = addNode(node.right ,data);
            }


            return node;

        }



}

**Comment by CooperCooperCooper** [comment]
Hi @dpritam1986 ,
Thank you for your code. In the code comment, it mentions that "output from this code when compiled thru  # 98. Validate Binary Search
Tree   it
passed"

Can you please clarify if this code and this issue was for Problem 108. Convert Sorted Array to Binary Search Tree or Problem 98. Validate Binary Search Tree?

**Comment by dpritam1986** [comment]
98 - generates BST .

108  -  validate BST


What I am asking is   -
A)    I created BST thru  98  BST tree output is  - [3,2,5,1,null,4]   for
this output  LEETCODE test case saying wrong answer that means this is  not
BST.
B)  Ok now same output  -  [3,2,5,1,null,4] when I run thru  - 108 which is
(validate BST program )  - it gives me accepted /correct answer in leetcode.

buddy I have attached screenshots in  GITHUB.


Now - either A) is correct  or B) is wrong  or vice versa ?

**Comment by CooperCooperCooper** [comment]
Thank you @dpritam1986  for the details. I've relayed them to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @dpritam1986 ,
Thank you for your time. We've taken a thorough look into the provided information. The trick is that on P108 there is a special condition : 

> a height-balanced binary tree is defined as a binary tree in which the depth of the two subtrees of every node never differ by more than 1. 

Therefore [2,1,5,0,null,4,null,null,null,3] is not a valid height balanced BST.
