### ISSUE TITLE
583. Delete Operation for Two Strings

### ISSUE THREAD

**Issue by Ajitesh13** [LeetCode-Feedback/LeetCode-Feedback#3780]
#### Your LeetCode username

beingbest

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Everything is fine about the problem statement, just add the tag of `Dynamic Programming` to the question, as it is one of the most popular solving way of such class of question.

**Comment by lc-kay** [comment]
@Ajitesh13 Thank you for your feedback. I've relayed this to our team to take into consideration.
