### ISSUE TITLE
Missing Test Case - 227. Basic Calculator II

### ISSUE THREAD

**Issue by patwari** [LeetCode-Feedback/LeetCode-Feedback#3781]
#### Your LeetCode username
r_patwari

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The official answer fails for cases where mid-results are very big.

#### Code you used for Submit/Run operation

```
class Solution {
    public int calculate(String s) {
        if (s == null || s.isEmpty()) return 0;
        int length = s.length();
        int currentNumber = 0, lastNumber = 0, result = 0;
        char operation = '+';
        for (int i = 0; i < length; i++) {
            char currentChar = s.charAt(i);
            if (Character.isDigit(currentChar)) {
                currentNumber = (currentNumber * 10) + (currentChar - '0');
            }
            if (!Character.isDigit(currentChar) && !Character.isWhitespace(currentChar) || i == length - 1) {
                if (operation == '+' || operation == '-') {
                    result += lastNumber;
                    lastNumber = (operation == '+') ? currentNumber : -currentNumber;
                } else if (operation == '*') {
                    lastNumber = lastNumber * currentNumber;
                } else if (operation == '/') {
                    lastNumber = lastNumber / currentNumber;
                }
                operation = currentChar;
                currentNumber = 0;
            }
        }
        result += lastNumber;
        return result;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Test Case: `2147483647 * 2147483647 / 2147483647`
Expected result: 2147483647
Code's result: 0

#### Screenshots

![Screenshot 2021-06-09 at 6 17 23 PM](https://user-images.githubusercontent.com/13629939/121356906-f29dec00-c94e-11eb-8def-0cb3c0ffe3d8.png)
![Screenshot 2021-06-09 at 6 23 08 PM](https://user-images.githubusercontent.com/13629939/121357840-bfa82800-c94f-11eb-8fb6-c4fc76d30ccc.png)

#### Additional context

Link to problem: [Link](https://leetcode.com/explore/interview/card/top-interview-questions-hard/116/array-and-strings/836/)
Solution: Prevent such tests which any intermediate calculation overflows value of 32-bit Integer.
We cannot even use Long for extreme scenarios: like `2147483647 * 2147483647 *2147483647 / 2147483647/ 2147483647`

**Comment by lc-kay** [comment]
Hi @patwari 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@patwari We will not add this test case because it is an edge case and the solution can be fixed just by changing the data types. Thank you for your time.
