### ISSUE TITLE
Improper Variable Names

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3782]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In some problems, there exist variable names that use a single upper case letter. It is not a good practice to use a single upper case letter as a variable name, so the variable names should be changed.

In [1133. Largest Unique Number](https://leetcode.com/problems/largest-unique-number), the variable name of the array is `A`, which should be changed to `nums` or `arr`.

In [1231. Divide Chocolate](https://leetcode.com/problems/divide-chocolate), the variable name `K` should be changed to `k`.

#### Expected behavior
The variable names should be changed as described above.

**Comment by lc-kay** [comment]
@stormsunshine Thank you for your feedback. This will be updated soon.
