### ISSUE TITLE
Missing Test Case - 1696. Jump Game VI

### ISSUE THREAD

**Issue by Bankde** [LeetCode-Feedback/LeetCode-Feedback#3783]
#### Your LeetCode username
bankde

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
The submission testcase is not properly covered.
```
06/09/2021 21:18 | Accepted | 1476 ms | 28.1 MB | python3
```

#### Code you used for Submit/Run operation
```
# This is bad attempt of sliding window (I have yet to check the incorrect part)
class Solution:
    def maxResult(self, nums: List[int], k: int) -> int:
        dp = [0]*len(nums)
        dp[-1] = nums[-1]
        # Keep only 2 values: the max one and 2nd max
        hp = collections.deque()
        hp.append((dp[-1], len(nums)-1))
        for i in reversed(range(len(nums)-1)):
            maxItem = hp[0][0] # always maximum
            dp[i] = nums[i] + maxItem
            while len(hp) > 0 and hp[-1][0] <= dp[i]:
                hp.pop()
            if len(hp) > 0 and hp[0][1]+1 > (i+k):
                hp.popleft()
            if len(hp) < 2:
                hp.append((dp[i],i))
        return dp[0]
```

#### Language used for code
Python3

#### Expected behavior
```
Wrong Answer
Runtime: 44 ms
Your input
[-8,-7,-6,-5,-4,-3,-2,-1]
4
Output
-14
Expected
-13
```

#### Additional context
Add the following testcase into the submission check.
```
[-8,-7,-6,-5,-4,-3,-2,-1]
4
```

**Comment by lc-kay** [comment]
Hi @Bankde 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Bankde 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
