### ISSUE TITLE
Hint Correction - 1696. Jump Game VI

### ISSUE THREAD

**Issue by namannigam** [LeetCode-Feedback/LeetCode-Feedback#3785]
#### Your LeetCode username
namannigam

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hint 1 of the problem is incorrect when it reads. 

> The answer for dp[i] is nums[i] + min{dp[i+j]} for 1 <= j <= k

#### Code you used for Submit/Run operation

A working solution would build upon the lines of:
```
dp[i] = Math.max(dp[i], nums[i] + solve(nums, dp, k, i + j));
```

#### Expected behavior
It should read 

> The answer for dp[i] is nums[i] + max{dp[i+j]} for 1 <= j <= k

#### Screenshots
<img width="707" alt="Screenshot 2021-06-09 at 9 05 00 PM" src="https://user-images.githubusercontent.com/76494006/121385019-626ba100-c966-11eb-8b82-a2ff91efa331.png">

**Comment by lc-kay** [comment]
Hi @namannigam 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @namannigam 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
