### ISSUE TITLE
Typo in Solution Article of problem 567.

### ISSUE THREAD

**Issue by vishesh13byte** [LeetCode-Feedback/LeetCode-Feedback#3790]
There is a typo in word characters in Approach 3 of solution article for problem 567.

![image](https://user-images.githubusercontent.com/66796715/121420496-c6a05c00-c98a-11eb-941b-650cdd913963.png)

**Comment by vishesh13byte** [comment]
please assign me this issue :)

**Comment by lc-kay** [comment]
Hi @vishesh13byte 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vishesh13byte 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
