### ISSUE TITLE
[Missing test case] 1886. Determine Whether Matrix Can Be Obtained By Rotation. 

### ISSUE THREAD

**Issue by YaroslavRepeta** [LeetCode-Feedback/LeetCode-Feedback#3791]
#### Your LeetCode username
yaroslav-repeta

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
I found 2 solutions on the first page (sorted by most votes) in discussion section of "https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation/" (from the last contest) that are based on counting:

https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation/discuss/1254312/"No-rotation"-with-picture
https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation/discuss/1255560/Unique-solution-without-rotating-just-count-number-of-1-in-every-row-and-column

#### Code you used for Submit/Run operation

Those won't pass the next test case:
```
[[0,0,1],[0,1,0],[1,0,0]]
[[1,0,0],[0,0,1],[0,1,0]]
```

**Comment by lc-kay** [comment]
Hi @YaroslavRepeta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @YaroslavRepeta 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
