### ISSUE TITLE
Missing Test Case - 1696. Jump Game VI

### ISSUE THREAD

**Issue by ricecakemonster** [LeetCode-Feedback/LeetCode-Feedback#3795]
#### Your LeetCode username
ricecakemonster

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I submitted my code that utilizes a queue and it was accepted while it should have failed.  

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxResult(int[] nums, int k) {
        int[] dp = new int[nums.length];
        Queue<Integer> q = new LinkedList();
        for(int i=nums.length-1; i>=0; i--){
            dp[i] = !q.isEmpty() ? dp[q.peek()] + nums[i] : nums[i];
            while(!q.isEmpty() && (dp[i] >= dp[q.peek()] || q.peek() >= i+k)) q.poll();
            q.add(i);
        }
        return dp[0];
    }
}
```

#### Language used for code
Java

#### Expected behavior
The submitted code should have failed with this test case, but it has succeeded:

[3,-7,-3,-5,1]
3

**Comment by lc-kay** [comment]
Hi @ricecakemonster 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ricecakemonster 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
