### ISSUE TITLE
valid solution rejected - 1696. Jump Game VI

### ISSUE THREAD

**Issue by janghwan** [LeetCode-Feedback/LeetCode-Feedback#3796]
#### Your LeetCode username

essis

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

a valid solution isn't accepted.
It gives either *Time limit exceeded* 

#### Code you used for Submit/Run operation

```scala
object Solution {
    def maxResult(nums: Array[Int], k: Int): Int = {
      import scala.collection.mutable.PriorityQueue
      val q = PriorityQueue[(Int, Int)]()
      val dp = Array.fill(nums.size)(0)
      dp(0) = nums(0)
      q += ((nums(0), 0))
      for (i <- 1 until nums.size) {
        while (q.max._2 < i - k) q.dequeue()
        dp(i) = q.max._1 + nums(i)
        q += ((dp(i), i))
      }
      dp.last
    }
}
```

#### Language used for code

scala

#### Expected behavior

It is a valid solution and should be accepted

#### Additional context

A naive DP solution with O(n*k) is accepted. which is supposed to be rejected.

**Comment by lc-kay** [comment]
@janghwan Your code received Time Limit Exceeded for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

Please raise your question in the problem discuss section for further support. Thank you for your time.
