### ISSUE TITLE
Code fails when submitted but works on running with exact same test case.

### ISSUE THREAD

**Issue by pgirikishore** [LeetCode-Feedback/LeetCode-Feedback#3798]
#### Your LeetCode username

pgirikishore

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The code fails when submitted but executes correctly on running code with the exact same test case data. This is weird behaviour as the code passing on running test case must pass when submitted as well.

#### Code you used for Submit/Run operation

```
// Best Time to Buy and Sell Stock
int max = 0;

int maxProfit(int* prices, int pricesSize){
    if(pricesSize<2)
        return 0;
    for(int i=pricesSize-2;i>=0;i--)
    {
        if((prices[pricesSize-1]-prices[i]) >max)
        {
            max = (prices[pricesSize-1]-prices[i]);
        }
    }
    maxProfit(prices, pricesSize-1);
    return max;
}
```

#### Language used for code

C

#### Expected behavior

The code should pass the test case when submitted.

#### Screenshots

![image](https://user-images.githubusercontent.com/48059119/121532257-ce104580-ca1c-11eb-8f53-048c6f5ad3ce.png)

**Comment by lc-kay** [comment]
Hi @pgirikishore 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
