### ISSUE TITLE
incomprehensive test case for problem #729

### ISSUE THREAD

**Issue by hhuang-ca** [LeetCode-Feedback/LeetCode-Feedback#3799]
#### Your LeetCode username

HH-ca (user4649p)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The problem description enforces the inputs 'start' and 'end' to be integer, but does not enforce the relationship between these two. When I provided a testcase that 'start' > 'end', the testcase passed the system check. My solution detected the error, but system gave an incorrect answer, and incorrectly judged my solution.

#### Code you used for Submit/Run operation

```
class MyCalendar:

    def __init__(self):
        self.starts = []
        self.ends = []

    def book(self, start: int, end: int) -> bool:
        if start >= end: return False
        idx = bisect.bisect(self.starts, start)
        if (idx > 0 and self.ends[idx-1] > start) or (idx < len(self.starts) and end > self.starts[idx]):
            return False
        
        self.starts.insert(idx, start)
        self.ends.insert(idx, end)
        return True
```

#### Language used for code

Python3

#### Expected behavior

Given following testcase:
["MyCalendar","book","book","book"]
[[],[10,20],[20,25],[25,20]]

The correct output should be:
True, True, False
Or, the system should throw an error message indicating incorrect testcase.

But the system gave answer:
True, True, True

#### Screenshots

![image](https://user-images.githubusercontent.com/69652041/121544487-c37f8d00-c9d7-11eb-9c40-ae425d88a0a2.png)

**Comment by lc-kay** [comment]
Hi @hhuang-ca 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hhuang-ca 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
