### ISSUE TITLE
二进制中1的个数测试用例异常

### ISSUE THREAD

**Issue by liuliqiang** [LeetCode-Feedback/LeetCode-Feedback#38]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**

https://leetcode-cn.com/problems/er-jin-zhi-zhong-1de-ge-shu-lcof/

这道题目的输入似乎有问题，尝试运行的输入和提示的不一致。

**你提交或者运行的代码**
```
func hammingWeight(num int) int {
    return num
}
```

**期望行为**
描述你期望的结果

**屏幕截图**

![image](https://user-images.githubusercontent.com/9395418/76439197-ff076200-63f6-11ea-90bb-ddb513d9533f.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
您好，该问题已修复，请稍后刷新网页再试试，感谢您对力扣的支持～
