### ISSUE TITLE
clone-graph problem: c-language Node definition not proper

### ISSUE THREAD

**Issue by moheed** [LeetCode-Feedback/LeetCode-Feedback#380]
**What kind of the bug**
- [ +] problem
- [ ] solution
- [ C] language

**Describe the bug**
https://leetcode.com/problems/clone-graph/submissions/
For this problem, when you go for C-solution, the definition of Node is not proper.

**what language is your code written in**
C

**Expected behavior**

There are no  correct way to store all the neighbors of a  given node of graph without screwing up 'AdjacencyList'.
A proper way for Node defintions for C:

```
struct Node{
int val;
int numNeighbors;
struct AdjList *neighbors;
}
struct AdjList{
struct Node* node;
struct AdjList* next;
}
```

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @moheed ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @moheed ,
Thank you for your time. Due to our technical design decision, we will be keeping the code definition the same for now. We appreciate your support!

**Comment by moheed** [comment]
HI CooperCooperCoooper,

Are you saying the c-node definition is correct for atleast one design choice, while implementing a solution in C?
Thank you.
Moheed

**Comment by CooperCooperCooper** [comment]
Thank you @moheed for your feedback. By design decision, we meant it's best suited for our current design standards across the entire LeetCode problem & solution system. Although we're currently not changing it, it's possible that we will update it in the future :)
