### ISSUE TITLE
Wrong description of question hint for 1696. Jump Game VI

### ISSUE THREAD

**Issue by zhaodonglin** [LeetCode-Feedback/LeetCode-Feedback#3800]
#### Your LeetCode username

zhaodonglin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Hint2 of Problem 1696. Jump Game VI is not right
"Instead of checking every j for every i, keep track of the smallest dp[i] values in a heap and calculate dp[i] from right to left. When the smallest value in the heap is out of bounds of the current index, remove it and keep checking."
In this paragraph, the "smallest" should be  "largest"

#### Screenshots

![image](https://user-images.githubusercontent.com/19355786/121566374-4c93c580-c9d2-11eb-9b08-7b6a766a925f.png)
The 'smallest' should be 'largest'

**Comment by lc-kay** [comment]
Hi @zhaodonglin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @zhaodonglin 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by zhaodonglin** [comment]
@lc-kay  you are welcome, when the 100 leetcode points will be added to my account, thank you very much.

**Comment by lc-kay** [comment]
@zhaodonglin This content issue did not qualify for rewards. Thank you for your understanding.
