### ISSUE TITLE
Missing Test Case - 628. Maximum Product of Three Numbers

### ISSUE THREAD

**Issue by srishtikohli99** [LeetCode-Feedback/LeetCode-Feedback#3802]
#### Your LeetCode username
geek-peek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case- Incorrect code acepted

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maximumProduct(vector<int>& nums) {
        int n = nums.size();
        if(n < 3) {
            return 0;
        }
        if(n == 3) {
            return nums[0] * nums[1] * nums[2];
        }
        
        sort(nums.begin(), nums.end());
        
        if(nums[0] >= 0 || nums[n-1] < 0) {
            return nums[n-1] * nums[n-2] * nums[n-3];
        } else if(nums.back() == 0) {
            n--;
            return nums[n-1] * nums[n-2] * nums[n-3];
        } else {
            return max(nums[0] * nums[1] * nums.back(), 
                       nums[n-1] * nums[n-2] * nums[n-3]);
        }
        
    }
};

```

#### Expected behaviour
This code is incorrect. However it gets accepted. The custom test case for which it failed is : [-1,-2,-3, 0]. This is because the case where largest element in array is 0 is not checked. 

#### Screenshots
<img width="1440" alt="Screenshot 2021-06-10 at 10 34 46 PM" src="https://user-images.githubusercontent.com/46334368/121567381-1e4ad000-ca3c-11eb-9d8c-16235d193a4c.png">

**Comment by lc-kay** [comment]
@srishtikohli99 Please provide the submission details link to your code. Thank you!

**Comment by srishtikohli99** [comment]
> @srishtikohli99 Please provide the submission details link to your code. Thank you!

https://leetcode.com/submissions/detail/506004453/

**Comment by lc-kay** [comment]
Hi @srishtikohli99 I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @srishtikohli99 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
