### ISSUE TITLE
Missing Test Case - 1884. Egg Drop With 2 Eggs and N Floors

### ISSUE THREAD

**Issue by luisdelacruzio** [LeetCode-Feedback/LeetCode-Feedback#3803]
#### Your LeetCode username

Noch50

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The problem doesn't test the case where n is equal to "1". In the solution that I pasted below, the code returns "2" when n is equal to "1". This is incorrect, however it still passes all of the test cases when I submit. 

#### Code you used for Submit/Run operation

```
/**
 * @param {number} n
 * @return {number}
 */
var twoEggDrop = function(n) {
    
    let y = 2;
    
    for(let i = 2, z = 1; i < n; i++) {
        
        if(y == z) {
            y++;
            z = 1;
        } else {
            z++;
        }

    }
    
    return y;
};
```

#### Language used for code

Javascript

#### Expected behavior

I expect the code above to fail the case where n = 1 when I submit. What is actually happening is that the code is passing all test cases. 

#### Screenshots

![image](https://user-images.githubusercontent.com/27124875/121619947-6ca9a000-ca37-11eb-8063-050b86137635.png)

#### Additional context

Here are the submission link details: https://leetcode.com/submissions/detail/506164631/

**Comment by lc-kay** [comment]
Hi @luisdelacruzio 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @luisdelacruzio 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
