### ISSUE TITLE
[Bug on website] Unexpected opening of two browser tabs

### ISSUE THREAD

**Issue by YaroslavRepeta** [LeetCode-Feedback/LeetCode-Feedback#3804]
#### Your LeetCode username

yaroslav-repeta

#### Category of the bug
- [X] Just a bug on the website.

#### Description of the bug

On the contests page https://leetcode.com/contest/, when I click on the user icon (not flag and not username) from the top 10, the two new tabs are opened in Safari and Chrome (though one might be blocked as pop up in Chrome).
If it's the Chinese user, one of the tabs will be from Chinese version of website.

#### Expected behavior

Only one new tab should be opened.

**Comment by lc-kay** [comment]
Hi @YaroslavRepeta 
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). 

However, I have relayed this issue to our team to investigate. Thank you again for your support and understanding.
