### ISSUE TITLE
Missing Test Case - 1021. Remove Outermost Parentheses

### ISSUE THREAD

**Issue by Achyuth17** [LeetCode-Feedback/LeetCode-Feedback#3805]
#### Your LeetCode username
Achyuth K Kowshik
LeetCode ID: user8520Ki

#### Category of the bug
- [ ] Question
1021. Remove Outermost Parentheses

#### Description of the bug
The problem statement clearly mentions that valid parenthesis string would be given as input but on the testcase console, invalid parenthesis string is accepted without throwing any error.

#### Code you used for Submit/Run operation
```
class Solution:
    def removeOuterParentheses(self, s: str) -> str:
        idx=set()
        stack=[]
        for i in range(len(s)):
            if s[i]=='(':
                if not stack:
                    idx.add(i)
                stack.append(s[i])
                
            elif s[i]==')' and not stack:
                idx.add(i)
                
            elif s[i]==')' and stack[-1]=='(':
                stack.pop(-1)
                if not stack:
                    idx.add(i)
        ans=""
        for i in range(len(s)):
            if i not in idx:
                ans+=s[i]
        return ans
```

#### Language used for code
Python

#### Expected behavior
When we give invalid parenthesis string as input on the testcase console, it should throw an error saying that this testcase is invalid.

#### Screenshots
<img width="539" alt="invalid" src="https://user-images.githubusercontent.com/51409439/121630881-9a283500-ca9b-11eb-82ec-86f293935faa.PNG">

**Comment by lc-kay** [comment]
Hi @Achyuth17 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Achyuth17 
Thank you for your time. We've added the missing validator. We appreciate your support!
