### ISSUE TITLE
Missing Solution - 1323. Maximum 69 Number

### ISSUE THREAD

**Issue by gitsabrina** [LeetCode-Feedback/LeetCode-Feedback#3807]
#### Your LeetCode username
sabr1na

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This problem is missing a solution.

#### Code you used for Submit/Run operation

```
class Solution {
    public int maximum69Number (int num) {
    if (num == 9 || num == 6) {
        return 9;
    } else if (num < 100) {
        return (num != 66) ? 99 : 96;
    } else if (num < 900) {
        return num + 300;
    } else if (num < 1000) {
        return  (num != 966) ? 999 : 996;
    } else if (num < 9000) {
        return num + 3000;
    } else if (num < 9900) {
        return num + 300; 
    } else {
        return (num != 9966) ? 9999 : 9996;
    }
    }
}
```

#### Expected behavior

_Explanation for my suggested solution:_

The constraints for the problem are 1 <= num <= 10^4 but digits can only be 6 or 9, so we only need to consider numbers in this range that consist of digits 6 or 9.

For numbers less than 10^1, the only possible options are 6 or 9, in which case the maximum number we can get by changing at most 1 digit will always be 9.

For numbers less than 10^2, the only possible options are 66, 69, 96, and 99. In which case, for all of these excluding 66, changing at most one digit to obtain the max will result in 99. For 66, the maximum number we can get with at most one digit change is 69. All we have to do is check if the number is 66. If it is we return 96, otherwise we return 99.

For numbers less than 10^3, we have numbers where the first digit is 6, (6--)  (where '-' represents any digit 6 or 9) and numbers where the first digit is 9, (9--). If the number starts with a 6, we know that no matter what the other values are, changing the first 6 to a 9 will result in our max possible number, so we can simply add 300 to whatever that number is resulting in 9--. For, numbers that start with a 9, our possible cases are 966, 969, 996, and 999. For all of these excluding 966, the max number we can get by changing at most one digit will be 999. For 966, the max value we can get is 996. Therefore, all we have to do is check if the number is 966. If it is, we return 996, otherwise we return 999.

For numbers less than 10^4, our possible numbers are where the first digit is 6 (6---) (again, where '-' represents a digit 6 or 9) and numbers where the first digit is 9 (9---). If the first digit is 6, the maximum number we can get from changing at most one digit, regardless of other values, will be this 6 to a 9 so we can return the number + 3000 to make this first digit 9. However, If the first digit is 9, we have two cases. Numbers where the second digit is 6 (96--) and numbers where the second digit is 9 (99--). If the second digit is 6, no matter what the other values are, we can obtain our max number by a one digit change through turning this 6 into a 9, resulting in (99--). To do this, we return number + 300. Our final case are numbers where the first and second digit is a 9 (99--). The cases for this are 9966, 9969, 9996, and 9999. For all cases except 9966, the max value obtained by changing at most one digit will be 9999. For 9966, the max value we could obtain would be 9996. All we have left to do is check whether this value is 9966. If it is, we return 9969, otherwise we return 9999.

At this point, we have reached all possible cases since the upper bound is 10^4.

#### Additional context

I attached my solution as well as an explanation to use as a possible solution to put for the missing solution.

**Comment by lc-kay** [comment]
Hi @gitsabrina 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@gitsabrina Thank you for sharing your approach with us. Our team has reviewed it and will take it into consideration when we make improvements to this article. Thank you for your time.
