### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by akshaykaushal2000** [LeetCode-Feedback/LeetCode-Feedback#3809]
#### Category of the bug
- [[-2147483647],[2],[3]] Missing Test Cases 

#### Description of the bug

The following code should not be acceptable if this test case is available in the test case set.

#### Code you used for Submit/Run operation

```
//Set Matrix Zeroes
class Solution {
public:
    void setZeroes(vector<vector<int>>& a) 
    {
     for(int i=0;i<a.size();i++)
     {
      for(int j=0;j<a[0].size();j++)
      {
         if(a[i][j]==0)
         {
             for(int l=0;l<a.size();l++)
             {
                 if(a[l][j]!=0)
                 a[l][j]=INT_MIN+1;
             }
             for(int l=0;l<a[0].size();l++)
              {
                 if(a[i][l]!=0)
                 a[i][l]=INT_MIN+1;
             }
         }
      }
     }
     for(int i=0;i<a.size();i++)
     {
      for(int j=0;j<a[0].size();j++)
      {
         if(a[i][j]==INT_MIN+1)
         {
            a[i][j]=0; 
         }
      }
     }
    }
};
```

#### Language used for code

c++

#### Expected behavior

If this test case is present in test cases set my code will not get AC, because my code will generate  [[0],[2],[3]] output for these testcase but its ouput should be [[-2147483648],[2],[3]]

**Comment by lc-kay** [comment]
Hi @akshaykaushal2000 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@akshaykaushal2000 During the investigation, our team discovered that the solution is the Wrong Answer because it depends on a special value. Since there are billions of special values that can be used in the solutions, it is impossible to add test cases to fail all of them. Therefore, we did not add your custom test case. Thank you for your understanding.
