### ISSUE TITLE
run time error in official python solution 

### ISSUE THREAD

**Issue by koushikII** [LeetCode-Feedback/LeetCode-Feedback#381]
**What kind of the bug**
- [ ] problem
- [yes] solution
- [] language

**Describe the bug**
https://leetcode.com/problems/regions-cut-by-slashes/solution/
the official solution given in this problem in python is giving run time error!

**what language is your code written in**
Python

**The code you submit/run**
```
class DSU:
    def __init__(self, N):
        self.p = range(N)

    def find(self, x):
        if self.p[x] != x:
            self.p[x] = self.find(self.p[x])
        return self.p[x]

    def union(self, x, y):
        xr = self.find(x)
        yr = self.find(y)
        self.p[xr] = yr

class Solution(object):
    def regionsBySlashes(self, grid):
        N = len(grid)
        dsu = DSU(4 * N * N)
        for r, row in enumerate(grid):
            for c, val in enumerate(row):
                root = 4 * (r*N + c)
                if val in '/ ':
                    dsu.union(root + 0, root + 1)
                    dsu.union(root + 2, root + 3)
                if val in '\ ':
                    dsu.union(root + 0, root + 2)
                    dsu.union(root + 1, root + 3)

                # north/south
                if r+1 < N: dsu.union(root + 3, (root+4*N) + 0)
                if r-1 >= 0: dsu.union(root + 0, (root-4*N) + 3)
                # east/west
                if c+1 < N: dsu.union(root + 2, (root+4) + 1)
                if c-1 >= 0: dsu.union(root + 1, (root-4) + 2)

        return sum(dsu.find(x) == x for x in xrange(4*N*N))
![Screenshot (2)](https://user-images.githubusercontent.com/46400011/83238952-c3d62d00-a1b4-11ea-9bf5-e8dfcc1485c8.png)

```

**Comment by CooperCooperCooper** [comment]
Hi @koushikII ,
Thank you for reaching out to us. I've tested the Python solution and got "Accepted" for both "Run Code" and "Submit". Please try and see if you're still getting Runtime Error from this solution. We appreciate your support.
<img width="1433" alt="Screen Shot 2020-05-29 at 5 50 08 PM" src="https://user-images.githubusercontent.com/59751300/83315450-e8420180-a1d4-11ea-98b6-23575f4f1c45.png">

**Comment by koushikII** [comment]
sorry ..but i am still getting the same error.
Koushik Ghos

**Comment by CooperCooperCooper** [comment]
Thank you @koushikII for your answer. Can you please provide your code, its language, and a screenshot of the error (like the screenshot I've attached in the previous message) here with us?
