### ISSUE TITLE
Missing Test Case - 871. Minimum Number of Refueling Stops

### ISSUE THREAD

**Issue by radhakrishnaakamat** [LeetCode-Feedback/LeetCode-Feedback#3811]
Corner case : 

5
1
[[1,1],[2,1],[3,1],[4,1],[5,1],[6,1]]

the result should be 4  but the solution is expecting 5

5
1
[[1,1],[2,1],[3,1],[4,1]]
for this case it works fine

**Comment by dwirtshafter** [comment]
I was going to post this too.  But then I saw the test case violates the 3rd constraint of the problem 
0 < stations[0][0] < stations[1][0] < ... < stations[stations.length-1][0] < target

**Comment by lc-kay** [comment]
Hi @radhakrishnaakamat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @radhakrishnaakamat 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
