### ISSUE TITLE
Missing Test Case - 1353. Maximum Number of Events That Can Be Attended

### ISSUE THREAD

**Issue by lonelykid** [LeetCode-Feedback/LeetCode-Feedback#3812]
#### Your LeetCode username

lonelykid

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

https://github.com/halfrost/LeetCode-Go/blob/master/leetcode/1353.Maximum-Number-of-Events-That-Can-Be-Attended/README.md
This solution can pass all the test data points. But actually it's not correct.
New data points suggested:
```
[[1,10],[2,3],[2,3],[2,3],[2,3]]
[[1, 2], [1, 2], [1, 8], [1, 8], [3, 4], [3, 4], [3, 4]]
```

#### Code you used for Submit/Run operation

```
package leetcode

import (
	"sort"
)

func maxEvents(events [][]int) int {
	sort.Slice(events, func(i, j int) bool {
		if events[i][0] == events[j][0] {
			return events[i][1] < events[j][1]
		}
		return events[i][0] < events[j][0]
	})
	attended, current := 1, events[0]
	for i := 1; i < len(events); i++ {
		prev, event := events[i-1], events[i]
		if event[0] == prev[0] && event[1] == prev[1] && event[1] == event[0] {
			continue
		}
		start, end := max(current[0], event[0]-1), max(current[1], event[1])
		if end-start > 0 {
			current[0] = start + 1
			current[1] = end
			attended++
		}
	}
	return attended
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
```

#### Language used for code

Go

**Comment by lc-kay** [comment]
@lonelykid Please provide the submission details link to your code. Thank you.

**Comment by lonelykid** [comment]
link to my submission: https://leetcode.com/submissions/detail/505090066/

**Comment by lc-kay** [comment]
Hi @lonelykid 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @lonelykid 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
