### ISSUE TITLE
Missing Test Case - 871. Minimum Number of Refueling Stops

### ISSUE THREAD

**Issue by chvinaykumar406** [LeetCode-Feedback/LeetCode-Feedback#3813]
#### Your LeetCode username

chvinaykumar

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ this  one] Missing Test Cases 
- Solution and missing Test cases

#### Description of the bug

the below solution I submitted is getting accepted.
consider the following test case.
the leetcode answer is 2.
lets say target 128, startFuel 3 and array is like [[2,50],[3,75]].
according to the above code its return ans 2 and leetcode's is same but my doubt is let's say car's initial fuel is 3 and it stops at the second station first, at which its fuel would 75(3 consumed and new fuel 75) and now it moves back 1 mile and fills 50 now its fuel is 124(1 consumed, 75+50-1 ) and it cannot reach 128 as the fuel is 124 and max distance it can reach is 126, then how will it will reach 128 , the answer should be -1.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minRefuelStops(int target, int startFuel, vector<vector<int>>& stations) {
        priority_queue<int> pq;
        int minStops=0;
        int currentStationIndex = 0;
        int totalStations = size(stations);
        while(startFuel<target)
        {
            while(currentStationIndex < totalStations and stations[currentStationIndex][0]<=startFuel)
            {
                pq.push(stations[currentStationIndex][1]);
                currentStationIndex++;
            }
            if(pq.empty())
                return -1;
            startFuel+=pq.top();
            pq.pop();
            minStops++;
        }
        return minStops;
    }
};
```

**Comment by lc-kay** [comment]
@chvinaykumar406 The expected output is correct. For further questions, please refer to the problem discuss section. Thank you for your time.
