### ISSUE TITLE
Missing Test Case - 1893. Check if All the Integers in a Range Are Covered

### ISSUE THREAD

**Issue by sandeeprana123** [LeetCode-Feedback/LeetCode-Feedback#3815]
#### Your LeetCode username

sandeeprana123

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

my code is accepted,but for a (may be more) testcase :
[[1,9],[2,7],[3,8],[10,12]]
7
11
it is showing wrong answer.
I think my code is incorrect but due to these missing test cases my code is accepted.
#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isCovered(vector<vector<int>>& ranges, int left, int right) {
        sort(ranges.begin(),ranges.end());
        int st,prev,j=0;
        for(int i=0;i<ranges.size();i++)
        {
            if(left>=ranges[i][0] && left<=ranges[i][1] && j==0)
            {
                st=ranges[i][1];
                prev=ranges[i][1];
                j=1;
            }
            if(j==1)
            {
               if(ranges[i][0]<=st+1)
               {
                 st=max(prev,ranges[i][1]);
                   prev=ranges[i][1];
               }  
                else 
                    return false;
               
            if(st>=right)
                return true;
            }
            
        }
        return false;
       
    }
};
```

#### Language used for code

C++

#### Screenshots

![bug1](https://user-images.githubusercontent.com/85514799/121785001-e1661100-cbd4-11eb-81e5-c59cb4a5bab2.png)

**Comment by lc-kay** [comment]
Hi @sandeeprana123 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sandeeprana123 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
