### ISSUE TITLE
Missing Test Case - 895. Maximum Frequency Stack

### ISSUE THREAD

**Issue by AbrarJahin** [LeetCode-Feedback/LeetCode-Feedback#3816]
#### Your LeetCode username

abrarjahin

#### Category of the bug
- [ ] Question
For this input-
["FreqStack","push","push","push","push","push","push","pop","pop","pop","pop"]
[[],[5],[7],[5],[7],[4],[5],[],[],[],[]]

This output also should be acceptable-

[null,null,null,null,null,null,null,5,5,7,7]

Because for the first pop, the output should be 5.
But for the second pop, the output can be 5 or 7.

- [ ] Solution

I am coding like this in Python 3-

````
class FreqStack:

    def __init__(self):
        self.freqDic = {1:[]}   #Store list of elements with same frequency
        self.elementFreq = {}   #Store every element frequency
        self.maxFreq = 0

    def push(self, val: int) -> None:
        if val in self.elementFreq:
            self.freqDic[self.elementFreq[val]].remove(val)
            self.elementFreq[val] += 1
            if self.elementFreq[val] not in self.freqDic:
                self.freqDic[self.elementFreq[val]] = []
            self.freqDic[self.elementFreq[val]].append(val)
        else:
            self.elementFreq[val] = 1
            self.freqDic[1].append(val)
        self.maxFreq = max(self.maxFreq, self.elementFreq[val])

    def pop(self) -> int:
        item = self.freqDic[self.maxFreq].pop()
        if self.maxFreq>1:
            self.freqDic[self.maxFreq-1].append(item)
            self.elementFreq[item]-=1
        else:
            del self.elementFreq[item]
        #Update Max Frequency
        #print(self.freqDic)
        if len(self.freqDic[self.maxFreq])==0:
            del self.freqDic[self.maxFreq]
            self.maxFreq-=1
        return item


# Your FreqStack object will be instantiated and called as such:
# obj = FreqStack()
# obj.push(val)
# param_2 = obj.pop()
````

- [ ] Language
Python 3
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behaviour

The code checker should accept all valid output. 

#### Screenshots

![image](https://user-images.githubusercontent.com/4152843/121786391-8c52dc80-cb8d-11eb-8666-1bc9fc44a368.png)

#### Additional context

The code checker should accept all valid output.

**Comment by lc-kay** [comment]
@AbrarJahin As stated in the problem description, "int pop() removes and returns the most frequent element in the stack.
If there is a tie for the most frequent element, the element closest to the stack's top is removed and returned." Therefore, there can only be one valid output. Please also check out the example explanation for a better understanding. Thank you for your time.
