### ISSUE TITLE
Incorrect test Solution for 545: Boundary of Binary Tree

### ISSUE THREAD

**Issue by rahul-shiv** [LeetCode-Feedback/LeetCode-Feedback#3818]
As an example for where the test code fails, we can look at

[1,2,3,null,5,6,null,null,null,7,8,9,10]

Test code solution :  [1,2,5,9,10,8,6,3]

However,7 should be in the answer(it is part of left boundary) but isn't. Seems like solution logic doesn't hold in many similar cases.

**Comment by lc-kay** [comment]
@rahul-shiv The expected output is correct. Please check out the tree visualizer for this test case. For further questions, please refer to the problem discuss section. Thank you for your time. 
<img width="453" alt="Screen Shot 2021-06-15 at 11 05 06 AM" src="https://user-images.githubusercontent.com/70870126/122102022-d32d1600-cdc9-11eb-84d1-3b742d7b1fb6.png">
