### ISSUE TITLE
Wrong Solution in Accepted Solutions Runtime Distribution

### ISSUE THREAD

**Issue by sushantPatrikar** [LeetCode-Feedback/LeetCode-Feedback#3819]
#### Your LeetCode username

persevere_21

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In '1898. Maximum Number of Removable Characters' and '1899. Merge Triplets to Form Target Triplet' of recent weekly contest 245, wrong sample solutions are appearing in the runtime distribution of python solutions (not sure about other languages). 

#### Code you used for Submit/Run operation

```
// 1898. Maximum Number of Removable Characters
class Solution:
    def maximumRemovals(self, s: str, p: str, removable: List[int]) -> int:
        if s == 'abcab' and p == 'abc' and removable == [0, 1, 2, 3, 4]:
            return 0
        
        cnt1 = [0] * 26
        cnt2 = [0] * 26
        
        for ch in s:
            cnt1[ord(ch) - ord('a')] += 1
        
        for ch in p:
            cnt2[ord(ch) - ord('a')] += 1
        
        for i, j in enumerate(removable):
            cnt1[ord(s[j]) - ord('a')] -= 1
            if any(x < y for x, y in zip(cnt1, cnt2)):
                return i
        return len(removable)
```

```
// 1899. Merge Triplets to Form Target Triplet
class Solution:
    def mergeTriplets(self, triplets: List[List[int]], target: List[int]) -> bool:
        has = set()
        for triplet in triplets:
            if all(a <= b for a, b in zip(triplet, target)):
                for num in triplet:
                    has.add(num)
        return all(num in has for num in target)
```

#### Language used for code

Python3

#### Expected behavior

These solutions should not appear in the accepted solution runtime graph

#### Screenshots

// 1898. Maximum Number of Removable Characters

![screenshot2](https://user-images.githubusercontent.com/40419750/121803930-541cce00-cc61-11eb-8adc-543a88bcc5b3.jpg)

![screenshot1](https://user-images.githubusercontent.com/40419750/121803934-5f6ff980-cc61-11eb-8ba4-ac4e40d8b8ff.jpg)

// 1899. Merge Triplets to Form Target Triplet

![screenshot4](https://user-images.githubusercontent.com/40419750/121803949-77e01400-cc61-11eb-8f35-0030be395b58.jpg)

![screenshot3](https://user-images.githubusercontent.com/40419750/121803953-7e6e8b80-cc61-11eb-948a-359493ab9575.jpg)

**Comment by lc-kay** [comment]
@sushantPatrikar I've relayed this issue to our team to investigate. However, we encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
