### ISSUE TITLE
Missing Test cases result in incorrect solution to be accepted

### ISSUE THREAD

**Issue by Gitu11** [LeetCode-Feedback/LeetCode-Feedback#382]
**What kind of the bug**
- [ ] problem
- [*] solution
- [ ] language

**Describe the bug**
Missing test cases cause the incorrect solution to be accepted.

**what language is your code written in**
Python3

**The code you submit/run**
```
# Valid Palindrome III
# Here is the incorrect code snippet which gets passed.
class Solution:
    def isValidPalindrome(self, s: str, k: int) -> bool:
        n = len(s)
        if n < k:   return False
        elif n == k:    return True
        left, right = 0, n - 1
        deletions = 0
        while left <= right:
            if s[left] == s[right]:
                left += 1
                right -= 1
            elif s[left + 1] == s[right]:
                left += 1
                deletions += 1
            elif s[left] == s[right-1]:
                right -= 1
                deletions += 1
            else:
                left += 2
                right -= 2
                deletions += 2
            if deletions > k:   return False
        return True
```

**Expected behaviour**
Below test case proves the solution incorrect.

"bacddcxyab"
2

2) 
**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @Gitu11 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @Gitu11 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
