### ISSUE TITLE
Missing Test Case - 707. Design Linked List

### ISSUE THREAD

**Issue by bbrozyna** [LeetCode-Feedback/LeetCode-Feedback#3820]
#### Your LeetCode username

barbroabc

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

List head initialization using addAtTail method may improperly append 2 values at once. Submitted code had that flaw and it ended up with solution acceptance

#### Code you used for Submit/Run operation

```
    public void addAtTail(int val) {
        if(root == null){
            root = new Node(val);
        }
        Node head = root;
        while(head.next != null)
            head = head.next;
        head.next = new Node(val);
    }
```

#### Language used for code

Java

#### Expected behavior

Solution should be rejected when submitted

#### Example of failing Test case

```
// input
["MyLinkedList","addAtTail","addAtTail", "get"]
[[],[1],[3], [1]]

// answer
[null,null,null,1]
// expected answer
[null,null,null,3]
```

**Comment by lc-kay** [comment]
@bbrozyna Please provide your submission details link. Thank you.

**Comment by bbrozyna** [comment]
@lc-kay Thanks for responding, Let me know if this is what you require.
https://leetcode.com/submissions/detail/508948783/?from=explore&item_id=1290

**Comment by lc-kay** [comment]
Hi @bbrozyna 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @bbrozyna 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
