### ISSUE TITLE
961. N-Repeated Element in Size 2N Array doesn't test all cases. 

### ISSUE THREAD

**Issue by funnytommy** [LeetCode-Feedback/LeetCode-Feedback#3821]
It accepted my solution which apparently gave wrong answer for this input: [1, 2, 3, 4, 4, 4]. This is a valid input according to description.

**Comment by lc-kay** [comment]
@funnytommy Please provide your submission details link. Thank you.

**Comment by lc-kay** [comment]
Hi @funnytommy 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
