### ISSUE TITLE
LeetCode 31 下一个排列 本地输出和实际输出不同

### ISSUE THREAD

**Issue by qq1120637483** [LeetCode-Feedback/LeetCode-Feedback#3823]
**你的 LeetCode 用户名**
15082939831

**Bug 类型**
- [下一个排列 ] 题目
- [JavaScript ] 编程语言

**描述**
调试的时候输出的结果和最终的输出结果不一致，也和本地的输出结果不一致。

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
// 下一个排列
var nextPermutation = function(nums) {
    // 从右往左找到降序与升序的交叉点
    let right = nums.length - 1;
    // 记录交叉点右侧的最小值
    let min = right;
    while (right) {
        if (nums[right] < nums[right-1]) {
            right--;
        } else {
            right--;
            break;
        }
    }
    if (right === 0 && nums.length === 2) return nums.sort((next,pre) => pre- next)
    let t = nums[min];
    nums[min] = nums[right];
    nums[right] = t;
    const temp1 = nums.slice(0,right+1);
    const temp2 = nums.slice(right+1).sort((next,pre) => next - pre);
    var temp3 = temp1.concat(temp2)
    return temp3
};

```

**期望行为**
运行结果不一致。

**屏幕截图**
![image](https://user-images.githubusercontent.com/57215916/121829695-d0f98780-ccf5-11eb-842a-06073d345f5f.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by qq1120637483** [comment]
> 感谢反馈，此问题已转给题目运营团队会尽快确认。

希望你们能够切实解决问题，而不是互相推脱。尽快，谢谢！

**Comment by feiceh** [comment]
@qq1120637483 感谢反馈，能否向我们提供一下输入输出详细情况？具体是什么地方不一致？把信息提供完整才能有助于快速验证和精准的定位，谢谢。

**Comment by qq1120637483** [comment]
> @qq1120637483 感谢反馈，能否向我们提供一下输入输出详细情况？具体是什么地方不一致？把信息提供完整才能有助于快速验证和精准的定位，谢谢。

比如这段代码，在其他IDE中输入[1,3,2]，返回[2,1,3]，但是在你们平台不是
// 下一个排列
var nextPermutation = function(nums) {
    // 从右往左找到降序与升序的交叉点
    let right = nums.length - 1;
    // 记录交叉点右侧的最小值
    let min = right;
    while (right) {
        if (nums[right] < nums[right-1]) {
            right--;
        } else {
            right--;
            break;
        }
    }
    if (right === 0 && nums.length === 2) return nums.sort((next,pre) => pre- next)
    let t = nums[min];
    nums[min] = nums[right];
    nums[right] = t;
    const temp1 = nums.slice(0,right+1);
    const temp2 = nums.slice(right+1).sort((next,pre) => next - pre);
    var temp3 = temp1.concat(temp2)
    return temp3
};

**Comment by feiceh** [comment]
@qq1120637483  你好，在与相关团队核实后，这题要求原地修改，（ Do not return anything, modify nums in-place instead. ）
以上信息请悉知，本次 Ticket 将关闭。

**Comment by qq1120637483** [comment]
> Do not return anything, modify nums in-place instead

明白了。感谢！
