### ISSUE TITLE
Missing Test Case - 350. Intersection of Two Arrays II

### ISSUE THREAD

**Issue by aybee3** [LeetCode-Feedback/LeetCode-Feedback#3825]
### LeetCode username
 ab3

### Category of the bug
Solution

### Description of the bug

**Problem No. 350 "Intersection of Two Arrays II"**

The expected result in the description of the problem is ```[2,2]```. The answer that my code is producing matches that of the result given in the description. But, when I run my code in the console, the expected result is ```[2]```. This is one of the example testcases. So, the expected result in the description and the console do not match.

### My Code

```class Solution {
public:
    vector<int> intersect(vector<int>& nums1, vector<int>& nums2) {
        vector <int> ans;
        map <int, int> m1, m2;
        for(int i=0; i<nums1.size(); i++)
            m1[nums1[i]]++;
        for(int i=0; i<nums2.size(); i++)
            m2[nums2[i]]++;
        for(auto x:m1){
            if(m2.find(x.first)!=m2.end()){
                int t = x.second;
                while(t--){
                    ans.push_back(x.first);
                }
            }
        }
        return ans;
    }
};
```
### Language used for code
C++

### Expected behavior
 The expected result in the console should be `[2,2]`. The expected result that is currently being shown is `[2]`.

### Screenshots

![Screen Shot 2021-06-14 at 2 44 58 PM](https://user-images.githubusercontent.com/48650086/121869025-3dd54780-cd1f-11eb-9715-8be550619cdc.png)
Expected result in the description

![Screen Shot 2021-06-14 at 2 45 29 PM](https://user-images.githubusercontent.com/48650086/121869068-49287300-cd1f-11eb-85bb-82b967e7c2dd.png)
Expected result in the console

**Comment by lc-kay** [comment]
@aybee3 The test case in the example is nums 1 = [1,2,2,1], nums2 = [2,2]. However, the test case you are running in the console is nums1 = [1,2,2,1], nums2 = [2]. Please note the difference in nums2 between the two test cases. Thank you for your time.
