### ISSUE TITLE
Missing Test Case - 1696. Jump Game VI

### ISSUE THREAD

**Issue by BrknRules** [LeetCode-Feedback/LeetCode-Feedback#3828]
#### Your LeetCode username

BrknRules

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Solution is accepted even though there is a case within bounds where solution provides the incorrect answer, where nums = [10,-5,-7,-6,-3,-4] and k = 3.

#### Code you used for Submit/Run operation

```
func maxResult(_ nums: [Int], _ k: Int) -> Int {
        let n = nums.count
        var score: [Int] = Array(repeating: 0, count: n)
        var biggest = 0
        var nextBiggest = 0
        for i in 0..<n {
            if biggest < i - k {
                biggest = nextBiggest
                nextBiggest += 1
            }
            score[i] = nums[i] + score[biggest] // max value at current index
            if score[i] >= score[biggest] {
                biggest = i
                nextBiggest = i + 1
            } else if score[i] >= score[nextBiggest] {
                nextBiggest = i
            }
        }
        return score[n - 1]
}
```

#### Language used for code

Swift

#### Expected behavior

The expected answer is 0 but this accepted code outputs -1.

**Comment by lc-kay** [comment]
Hi @BrknRules 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @BrknRules 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
