### ISSUE TITLE
Weak test cases for 787. Cheapest Flights Within K Stops

### ISSUE THREAD

**Issue by abhishekans21** [LeetCode-Feedback/LeetCode-Feedback#383]
**What kind of the bug**
- [x] problem
- [x] solution

**Describe the bug**
The question asks us to find minimum cost to reach the destination from source, with using at max K edges. The current test cases fail to catch a wrong solution.

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
    void dfs(int n, vector < vector <int> > &g, int src, int dst, int K,  vector <int> &dist)
    {
        if(K < 0)
            return;
        if(src == dst)
            return;
        for(int i=0;i<n;i++)
        {
            if(g[src][i] == 0)
                continue;
            if(dist[i] > dist[src]+g[src][i])
            {
                 
                dist[i] = dist[src]+g[src][i];
                dfs(n,g,i,dst,K-1,dist);
            }
        }
        return;
    }
    int findCheapestPrice(int n, vector<vector<int>>& flights, int src, int dst, int K) {
        vector < vector <int> > g(n, vector <int> (n,0));
        vector <int> dist(n+1,INT_MAX);
        for(int i=0;i<flights.size();i++)
        {
            g[flights[i][1]][flights[i][0]] = flights[i][2];
        }
        dist[dst] = 0;
        dfs(n,g,dst,src,K,dist);

        if(dist[src] == INT_MAX)
            return -1;
        
        return dist[src];
    }
};
```
**Current Behavior**
Incorrect solution was accepted

**Expected behavior**
The Verdict should have been "wrong answer" but instead submission was "accepted". The code fails on this custom test case written by me.
4
[[1,0,1],[2,0,5],[2,1,1],[3,2,1]]
3
0
1

**Additional Context**
I believe the above test case should be added

**Comment by CooperCooperCooper** [comment]
Hi @abhishekans21 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @abhishekans21 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

**Comment by abhishekans21** [comment]
Hi @CooperCooperCooper,
Glad I could help.
I've dropped a mail with the required info to "support@leetcode.com"
