### ISSUE TITLE
Test Case - 706. Design HashMap

### ISSUE THREAD

**Issue by thaihiep232002** [LeetCode-Feedback/LeetCode-Feedback#3830]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

/**
 * Initialize your data structure here.
 */
var MyHashMap = function() {
    this.storage = new Array(10001);
};

/**
 * value will always be non-negative. 
 * @param {number} key 
 * @param {number} value
 * @return {void}
 */
MyHashMap.prototype.put = function(key, value) {
    this.storage[key] = value;
};

/**
 * Returns the value to which the specified key is mapped, or -1 if this map contains no mapping for the key 
 * @param {number} key
 * @return {number}
 */
MyHashMap.prototype.get = function(key) {
    return this.storage[key] === undefined ? -1 : this.storage[key];
};

/**
 * Removes the mapping of the specified value key if this map contains a mapping for the key 
 * @param {number} key
 * @return {void}
 */
MyHashMap.prototype.remove = function(key) {
    this.storage[key] = -1;
};

/** 
 * Your MyHashMap object will be instantiated and called as such:
 * var obj = new MyHashMap()
 * obj.put(key,value)
 * var param_2 = obj.get(key)
 * obj.remove(key)
 */

**Comment by lc-kay** [comment]
@thaihiep232002 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
