### ISSUE TITLE
Missing Test Case - 139. Word Break

### ISSUE THREAD

**Issue by anoushkas23** [LeetCode-Feedback/LeetCode-Feedback#3832]
#### Your LeetCode username
anoushkas23

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ *] Missing Test Cases 

#### Description of the bug
 The test cases provided aren't sufficient as even my wrong code is getting passed.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool wordBreak(string s, vector<string>& wordDict) {
        
        unordered_map<string,int> map;
        for(int i=0;i<wordDict.size();i++)
            map[wordDict[i]]++;
        
        int n=s.size();
        bool dp[n];     //if word ending in index i is present in wordDict
        for(int i=0;i<n;i++)
            dp[i]=0;
        
        int lastone=-1;
        for(int i=0;i<n;i++)
        {
            if(lastone==-1)
            {
                if(map.count(s.substr(0,i+1))>0)
                {
                    dp[i]=1;
                    lastone=i;
                    continue;
                }
            }
            else
            {
                for(int j=lastone+1;j>=0;j--)
                {
                    int flag=0;
                    if(dp[j]==1 && j-1<0)
                        flag=1;
                    if(dp[j]==1 && flag==0 && dp[j-1]!=1)   //cant be overlapping words
                        continue;
                    if(map.count(s.substr(j,i-j+1))>0)
                    {
                        dp[i]=1;
                        lastone=i;
                        break;
                    }
                }
            }  
        }
        
        return dp[n-1];
    }
};
```

#### Language used for code
C++

#### Expected behavior
 The test case "leetcode" ["leet","etcode"] should give wrong answer with the code that I have written. But my answer is getting passed. So the test cases given aren't sufficient. This test case does give wrong answer when I write it in the console on my own.

#### Screenshots

![image](https://user-images.githubusercontent.com/85883678/121901272-ded5f980-cd43-11eb-9d37-c99f50639375.png)

**Comment by lc-kay** [comment]
Hi @anoushkas23 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @anoushkas23 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
