### ISSUE TITLE
Missing Test Case - 336. Palindrome Pairs

### ISSUE THREAD

**Issue by Northnroro** [LeetCode-Feedback/LeetCode-Feedback#3833]
#### Your LeetCode username

napat (northnroro@hotmail.com)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Testcase set lacks a good large testcase containing only a few letters (for example, all words contain only either "a" or "b" such as ["","a","aa","aaa","b","bb","ab","aabb","aabbbb","ababab","aabaab","baabaa", ...] ). Therefore, dividing input words into 26 groups by first/last letter will wrongly be "Accepted" instead of "Time Limit Exceeded".

I have attached a testcase that makes the "dividing" approach get "Time Limit Exceeded" below.

#### Code you used for Submit/Run operation

```java
// Palindrome Pairs
class Solution {
    public List<List<Integer>> palindromePairs(String[] words) {
        List<List<Integer>> ans = new ArrayList<>();
        Map<Character, List<Integer>> endWithKey = new HashMap<>();
        List<Integer> emptyString = new ArrayList<>();
        for(int i=0;i<words.length;i++){
            String word = words[i];
            if(word.length() == 0) {
                emptyString.add(i);
                continue;
            }
            char c = word.charAt(word.length()-1);
            List<Integer> list = endWithKey.get(c);
            if(list == null){
                list = new ArrayList<>();
                endWithKey.put(c, list);
            }
            list.add(i);
        }
        for(int i=0;i<words.length;i++){
            if(words[i].length() == 0) continue;
            List<Integer> checklist = endWithKey.get(words[i].charAt(0));
            if(checklist==null) continue;
            for(Integer j: checklist){
                if(i!=j && isPalindrome(words[i]+words[j])){
                    ans.add(List.of(i,j));
                }
            }
        }
        if(!emptyString.isEmpty()){
            for(int i=0;i<words.length;i++){
                if(isPalindrome(words[i])){
                    for(Integer j:emptyString){
                        if(i!=j){
                            ans.add(List.of(i,j));
                            ans.add(List.of(j,i));
                        }
                    }
                }
            }
        }
        return ans;
    }
    public boolean isPalindrome(String word){
        for(int i=0;i<word.length()/2;i++){
            if(word.charAt(i) != word.charAt(word.length()-1-i)){
                return false;
            }
        }
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The above code should get "Time Limit Exceeded" instead of "Accepted". 
Hardcoding-aided solutions using first/last letter or even prefix/postfix of words should not be accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/7249025/121913693-31271280-cd64-11eb-8d8f-1b401d51d154.png)

#### Additional context

The code I use to generate the testcase in the screenshot is below:
```javascript
function generate(){
    var map = {};
    for(var a=0; a<21; a++){
        for(var b=0; b<20; b++){
            if(a==0 && b==0) continue;
            for(var i=Math.floor(200/(a+b)); i<Math.floor(300/(a+b)); i++){
                map[("a".repeat(a)+"b".repeat(b)).repeat(i)] = true;
    map[("b".repeat(b)+"a".repeat(a)).repeat(i)] = true;
            }
        }
    }
    return '["'+Object.keys(map).join('","')+'"]';
}
```

**Comment by lc-kay** [comment]
@Northnroro Please provide your test case in a .txt file. Thank you!

**Comment by Northnroro** [comment]
This is the testcase whose URL is expiring in 6 days: [https://filebin.net/rvxqc6kzt7klimzx/issue_3833_testcase.txt](https://filebin.net/rvxqc6kzt7klimzx/issue_3833_testcase.txt)

**Comment by lc-kay** [comment]
Hi @Northnroro 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Northnroro Our team found that the provided solution is ok to pass and won't fail after adding the test case. Therefore, we did not add the test case. Thank you for your time.
