### ISSUE TITLE
Invalid Test Case - 43. Multiply Strings

### ISSUE THREAD

**Issue by martachupil** [LeetCode-Feedback/LeetCode-Feedback#3835]
#### Your LeetCode username
chupilmarta

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One of test cases have an invalid expected value.

**Input**

```
"123456789"
"987654321"
```

**Output:**
"121932631112635260"

**Expected:**
"121932631112635269"

The expected output in the case is incorrect (`123456789 * 987654321 = 121932631112635260` actually).

#### Code you used for Submit/Run operation

```
var multiply = function(num1, num2) {
    return (+num1 * +num2).toString();
};
```

#### Language used for code

JavaScript

#### Expected behavior

Expected output in the case is incorrect (`123456789 * 987654321 = 121932631112635260` actually).

The expected output should be `121932631112635260` instead of `121932631112635269`

#### Screenshots

![image](https://user-images.githubusercontent.com/16148304/121976010-9b06e280-cd8b-11eb-9e7f-b4ec67f6a28f.png)

**Comment by lc-kay** [comment]
@martachupil The expected output is correct. Please checkout the screenshot for the calculation for 123456789 * 987654321. Thank you for your time. 
<img width="735" alt="Screen Shot 2021-06-15 at 11 47 00 AM" src="https://user-images.githubusercontent.com/70870126/122106988-6fa5e700-cdcf-11eb-8b32-fad1a83ebbd9.png">
