### ISSUE TITLE
Missing Test Case - 1041. Robot Bounded In Circle

### ISSUE THREAD

**Issue by NYY2510** [LeetCode-Feedback/LeetCode-Feedback#3837]
#### Your LeetCode username

N2510

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test cases are not comprehensive enough so that some tricky methods can pass

#### Code you used for Submit/Run operation

```
// 1041. Robot Bounded In Circle
class Solution {
    public boolean isRobotBounded(String instructions) {
        //just this part the testcases not covered
        instructions = instructions.replace( "RRRR","" );
        instructions = instructions.replace( "LLLL","" );
        instructions = instructions.replace( "RLLR","" );
        instructions = instructions.replace( "LRRL","" );
        instructions = instructions.replace( "RRLL","" );
        instructions = instructions.replace( "LLRR","" );
        instructions = instructions.replace( "RLRL","" );
        instructions = instructions.replace( "LRLR","" );

        char[] c = instructions.toCharArray();
        int n = 0;
        int m = 0;
        for ( int i = 0; i < c.length; i++ ) {
            if ( c[i] == 'L' ) n--;
            if ( c[i] == 'R' ) n++;
            if ( c[i] == 'G' ) m++;
        }
        
        if(m == 0){//Never moved, true
            return true;
        }

        if ( n%4 != 0 ){//Direction changed, true
            return true;
        }
        
        if(n!=0 && n%4 == 0 && m%2 == 0 ) {//Direction not changed but move to the original point, true
            return true;
        }

        return false;
    }
}

```

#### Language used for code

Java

#### Expected behavior

The code doesn't give enough thought to determining whether the robot is spinning in place (the blue box area of the screenshot)
But testcases don't cover this part (the red box area of the screenshot)

#### Screenshots

![image](https://user-images.githubusercontent.com/69096782/121998135-6ee26600-cd79-11eb-9723-c1638f6f3d5b.png)

**Comment by lc-kay** [comment]
Hi @NYY2510 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @NYY2510 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
