### ISSUE TITLE
Missing Test Case - 1901. Find a Peak Element II

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3839]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[[1,4,6],[2,9,5],[7,8,3]]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> findPeakGrid(vector<vector<int>>& mat) {
        int n = mat.size(), m = mat[0].size();
        int r = 0, c = 0;
        
		// Check for both row and column
        while (r+1 < n && c+1 < m) {
            if (mat[r][c] < mat[r+1][c]) {
                ++r;
            } else if (mat[r][c] < mat[r][c+1]) {
                ++c;
            } else break;
        }
        
		// Check for remaining rows (if available)
        if (c < m) {
            while (r+1 < n && mat[r+1][c] < mat[r+1][c]) {
                ++r;
            }
        }
        
		// Check for remaining column (if available)
        if (r < n) {
            while (c+1 < m && mat[r][c] < mat[r][c+1]) {
                ++c;
            }
        }
        
        return vector<int>{r, c};
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected: [1,1]
Output: [2,1]

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hqztrue The solution provided here already fails from #3838. Therefore, our team did not add this test case. Thank you for your time.
