### ISSUE TITLE
598. Range Addition II (ambiguous problem statement)

### ISSUE THREAD

**Issue by agarusa** [LeetCode-Feedback/LeetCode-Feedback#384]
**What kind of the bug**
ambiguous problem statement .

**Describe the bug**
Problem states: "Given an m * n matrix M..."
There no statement if m in number of rows or columns. Thought usually matrix is said to have n rows and m columns, in this statement its opposite.

Function description in C++:
int maxCount(int m, int n, vector<vector<int>>& ops) {...}

Testcase that shows it:
92
2
[[70,1],[37,1],[3,2],[67,1],[37,2],[87,2],[26,1],[43,1],[19,1],[63,1],[67,1],[19,1],[14,2],[5,1],[27,2],[44,2],[13,1]]

As you can see m = 92 corresponds to rows.

**Comment by CooperCooperCooper** [comment]
Hi @agarusa ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @agarusa ,
Thank you for your time. Due to our design decision, we will be keeping this description for now. However, we will keep your feedback in mind when we update the description standard in the future for all related problems. We appreciate your support.
