### ISSUE TITLE
Missing Test Case: 1483: Kth Ancestor of a Tree Node 

### ISSUE THREAD

**Issue by Jahnvi13** [LeetCode-Feedback/LeetCode-Feedback#3840]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

My test case fits the constraints and a solution that gets accepted fails on it. This is possibly due to the assumption in the existing test cases that parent[i]<i whereas in the constraint, it is mentioned that parent[i]<n. 

["TreeAncestor","getKthAncestor","getKthAncestor","getKthAncestor"]
[[4,[-1,2,3,0]],[2,3],[2,2],[2,1]]

#### Code you used for Submit/Run operation

```
class TreeAncestor {
public:
    int LOG, n;
    vector<vector<int> > up;
    
    void fillup(vector<int>& parent){
        
        up = vector(n, vector<int>(LOG, -1));
       
        //O(N*log(N))
        for(int i=0;i<n;i++){
            up[i][0]=parent[i];
            for(int j=1;j<LOG;j++){
                if(up[i][j-1]==-1) up[i][j]=-1;
                else up[i][j] = up[up[i][j-1]][j-1];
            }
        }
    }
    TreeAncestor(int mn, vector<int>& parent) {
        n=mn;
        LOG = log2(n)+1;        
        fillup(parent);
    }
    
    int getKthAncestor(int node, int k) {
        
        vector<int> arr;
        while(k>0){
            arr.push_back(k%2);
            k/=2;
        }
        for(int i=0;i<arr.size();i++){
            
            if(arr[i]!=0) {
                if(i>=LOG || up[node][i]==-1) return -1;
                node = up[node][i];
            }
        }
        return node;
    }
};

/**
 * Your TreeAncestor object will be instantiated and called as such:
 * TreeAncestor* obj = new TreeAncestor(n, parent);
 * int param_1 = obj->getKthAncestor(node,k);
 */
```

#### Language used for code
C++ 

#### Expected behavior

My output: [null,-1,-1,3]
Expected output: [null,-1,0,3]

Yet the solution got an accepted verdict from the Judge.

**Comment by lc-kay** [comment]
Hi @Jahnvi13 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Jahnvi13 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
