### ISSUE TITLE
LeetCode 31 下一个排列 题目错误

### ISSUE THREAD

**Issue by phpcyy** [LeetCode-Feedback/LeetCode-Feedback#3842]
**你的 LeetCode 用户名**
phpcyy@gmail.com

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目未限定 nums[i] 是个位数，反而在提示中写道 `0 <= nums[i] <= 100`

**你使用的语言**

Go

**你提交或者运行的代码**
```
func nextPermutation(nums []int) {
	n := len(nums)
	i := n - 2
	for i >= 0 && nums[i] >= nums[i+1] {
		i--
	}
	if i >= 0 {
		j := n - 1
		for j >= 0 && nums[i] >= nums[j] {
			j--
		}
		nums[i], nums[j] = nums[j], nums[i]
	}
	reverse(nums[i+1:])
}

func reverse(a []int) {
	for i, n := 0, len(a); i < n/2; i++ {
		a[i], a[n-1-i] = a[n-1-i], a[i]
	}
}
```

**期望行为**
上述代码为官方题解中的答案。

输入 3, 2, 11
输出 3, 11, 2
实际应输出 11, 2, 3

希望修改题目，或者修改题解并修改测试用例。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by CatLyan** [comment]
@phpcyy 您好，在与相关团队核实后：num[I] 不一定为个位数，同时官方题解 Go 语言返回值[3,11,2] 为正确。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。

**Comment by phpcyy** [comment]
> @phpcyy 您好，在与相关团队核实后：num[I] 不一定为个位数，同时官方题解 Go 语言返回值[3,11,2] 为正确。
> 以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。

能解释下吗？[3,11,2] 按照字典序为何大于 [3,2,11] ？
