### ISSUE TITLE
Missing test case - 

### ISSUE THREAD

**Issue by hacker1happy** [LeetCode-Feedback/LeetCode-Feedback#3844]
#### Your LeetCode username
lazzy_coder

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
My code was accepted but, this test case failed to accept.
Such test cases should also be added.
[this_test_case_failed.docx](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6655832/this_test_case_failed.docx)

#### Code you used for Submit/Run operation
//219. Contains Duplicate II
```
class Solution {
public:
    bool containsNearbyDuplicate(vector<int>& nums, int k) {
        if(nums.size()<2 || nums.size()>25000)
                return false;
        for(int i=0;i<nums.size();i++){
            int temp=nums[i],c=0;
            for(int j=i+1;(c<k && j<nums.size());j++){
                if(nums[j]==temp)
                    return true;
                c++;
            }                
        }
        return false;
    }
};

```
#### Language used for code
C++

#### Expected behavior

Expected output: true

#### Screenshots
![image](https://user-images.githubusercontent.com/57825325/122057851-ad733180-ce08-11eb-8d16-c70ec921ceba.png)

#### Additional context

Hardcode is accepted in the challenge.
either change the constraints or add the above test case.

**Comment by lc-kay** [comment]
Hi @hacker1happy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hacker1happy Since this solution was hardcoding some cases to get AC, our team didn't add the contributed test case.
However, we have changed the test set to reduce the number of cheating solutions. Thank you for your time.
