### ISSUE TITLE
Missing Test Case - 473. Matchsticks to Square

### ISSUE THREAD

**Issue by arunkumariitkgp** [LeetCode-Feedback/LeetCode-Feedback#3848]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@arunkumariitkgp Please provide the submission details link to the code that failed from this missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
