### ISSUE TITLE
Missing Test Case - 1096. Brace Expansion II

### ISSUE THREAD

**Issue by hukun01** [LeetCode-Feedback/LeetCode-Feedback#3849]
#### Your LeetCode username

Memoria

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Bug in existing solution. The existing solution is expecting a wrong answer.
```
"{a,b},x{c,{d,e}y}"
```

#### Code you used for Submit/Run operation

```
class Solution:
    def braceExpansionII(self, expression: str) -> List[str]:
        groups = [[]]
        level = 0
        for i, c in enumerate(expression):
            if c == '{':
                if level == 0:
                    start = i+1
                level += 1
            elif c == '}':
                level -= 1
                if level == 0:
                    groups[-1].append(self.braceExpansionII(expression[start:i]))
            elif c == ',' and level == 0:
                groups.append([])
            elif level == 0:
                groups[-1].append([c])
        word_set = set()
        for group in groups:
            word_set |= set(map(''.join, itertools.product(*group)))
        return sorted(word_set)
```

#### Language used for code

Python 3

#### Expected behavior

Actual expected output is
```
["a","b","xc","xdy","xey"]
```

#### Screenshots

Existing output from OJ is
```
["a,xc","a,xdy","a,xey","b,xc","b,xdy","b,xey"]
```

**Comment by lc-kay** [comment]
Hi @hukun01 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hukun01 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by kimimaxi** [comment]
How is the test case "{a,b},x{c,{d,e}y}" correct? From the description of merge operation: R({e1, e2, ...}) = R(e1) ∪ R(e2) ∪ ... the merge should be enclosed in braces.
