### ISSUE TITLE
Solution That Doesn't Work Gets Accepted In House Robber No. 198

### ISSUE THREAD

**Issue by nishantc1527** [LeetCode-Feedback/LeetCode-Feedback#385]
**What kind of the bug**
- [x] problem
- [x] solution

**Describe the bug**
A solution that shouldn't get accepted due to a flaw in the code get's accepted. When entering the custom test case in the "run code" section, it says it was wrong.

**what language is your code written in**
Python3

**The code you submit/run**
```python
// House Robber
class Solution:
    def rob(self, values):
        if len(values) == 0:
            return 0
        elif len(values) == 1:
            return values[0]
        elif len(values) == 2:
            return max(values[0], values[1])

        dp = [0] * len(values)
        dp[0] = values[0]
        dp[1] = max(values[0], values[1])

        for i in range(2, len(dp), 1):
            dp[i] = max(dp[i - 2] + values[i], dp[i - 1])

        return dp[-1]
```

**Expected behavior**
When I press "submit," it should give "Wrong Answer," the test case is
```[-635, -557, 710, -503, -681, -970, 770, -136, 325, 716, -608, 89, 486, -897, -390, -922, 907, -750, 936, 10, 209, -687, 173, 674, 709]```
My Answer: 4981
Expected Answer: 5616

**Screenshots**
![Capture](https://user-images.githubusercontent.com/52992695/83309073-2df2d000-a1bd-11ea-8532-b07ceb9a00b8.PNG)
![Capture](https://user-images.githubusercontent.com/52992695/83309114-49f67180-a1bd-11ea-935c-7f96431005ab.PNG)
![Capture](https://user-images.githubusercontent.com/52992695/83309230-9346c100-a1bd-11ea-8b28-51e594b2780a.PNG)

**Additional Context**:
Adding that test case only won't help. I have created this pytest method:

```python
def test_bottom_up():
    for i in range(100):
        rand_list = [random.randrange(-1000, 1000, 1) for _ in range(25)]
        assert rob(rand_list) == bottom_up(rand_list), str(rand_list)
```

And every time it generates a wrong answer.

**Comment by CooperCooperCooper** [comment]
Hi @nishantc1527 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @nishantc1527 ,
Thank you for your time. From the statement "Given a list of non-negative integers", it indicates the provided test case in this issue is invalid. We appreciate your support.
