### ISSUE TITLE
Missing Test Case - 473. Matchsticks to Square

### ISSUE THREAD

**Issue by georgri** [LeetCode-Feedback/LeetCode-Feedback#3850]
#### Your LeetCode username

Georgri

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Missing test case:
[6,6,6,6,4,2,2]

#### Code you used for Submit/Run operation

```
from itertools import combinations

class Solution:
    def makesquare(self, matchsticks: List[int]) -> bool:
        # the lenght of square side is
        s = sum(matchsticks)
        if s % 4 != 0:
            return False
        
        side = s // 4
        n = len(matchsticks)

        # WTF WHY IS THIS WORKING?!?!?!
        
        used = [False] * n
        for i in range(n):
            for c in combinations(range(n), i):
                temp = side
                for k in c:
                    temp -= matchsticks[k]
                if temp == 0:
                    for k in c:
                        used[k] = True

        return all(i for i in used)

        
        
        
```

#### Language used for code

Python 3

#### Expected behavior

The test case should return false.
My code returns true, but is still accepted.

**Comment by lc-kay** [comment]
Hi @georgri 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @georgri 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
