### ISSUE TITLE
Missing Test Case - 473. Matchsticks to Square

### ISSUE THREAD

**Issue by kosievdmerwe** [LeetCode-Feedback/LeetCode-Feedback#3851]
#### Your LeetCode username
kosievdmerwe

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The problem allows matches of length 0, which can result in the ambiguous case of a square with side length 0.

There are two ambiguities with side length 0:
* Are you allowed to make a square with side length 0 at all?
* If we're allowed side length 0, are you allowed to make a square with no matches on one or more of the sides?

It looks like the answer is "No we're not allowed to have side length 0".

My code below passes all the test cases, but fails for:
[0, 0, 0, 0]

In addition, I tried the Python code from the solution and it also fails for the input `[0, 0, 0, 0]`. The DFS returns a wrong answer and the DP fails by trying to divide by 0.

#### Code you used for Submit/Run operation

```
class Solution:
    def makesquare(self, matchsticks: List[int]) -> bool:
        if sum(matchsticks) % 4 != 0 or len(matchsticks) < 4:
            return False
        
        side = sum(matchsticks) // 4
        if max(matchsticks) > side:
            return False
        
        matchsticks = sorted(matchsticks, reverse=True)
        #print(matchsticks)
        
        seen = False
        sides = [matchsticks[0], 0, 0, 0]
        
        def _backtrack(i):
            if i >= len(matchsticks):
                nonlocal seen
                seen = True
                return
            
            m = matchsticks[i]
            used = set()
            for si in range(4):
                if sides[si] + m > side:
                    continue
                if sides[si] in used:
                    continue
                used.add(sides[si])
                    
                sides[si] += m
                _backtrack(i + 1)
                sides[si] -= m
        
        _backtrack(1)
                
        return seen
```

#### Language used for code
Python3

#### Expected behavior
Question should clarify whether side length 0 is allowed.

The test case [0, 0, 0, 0] should be added.

At least the Python solutions should be fixed to concur with the validator regarding the case `[0, 0, 0, 0]`.

**Comment by lc-kay** [comment]
Hi @kosievdmerwe 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kosievdmerwe 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
