### ISSUE TITLE
Missing Test Case - 1492. The kth Factor of n

### ISSUE THREAD

**Issue by yashchitre03** [LeetCode-Feedback/LeetCode-Feedback#3852]
#### Your LeetCode username

redocsuomynona

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For the aforementioned problem, there are two main solutions, one runs in O(N) time, while the other runs in O(sqrt(N)) time.
But both the solutions pass in Leetcode due to the range of the inputs being restricted to just 1000. Kindly increase this upper bound on the input or remove it entirely so that the naive solution fails by TLE for larger inputs. Also, make the runtime more strict.

For example, large testcases could be close to the maximum integer value for both n and k.

#### Code you used for Submit/Run operation

Solution 1
```
class Solution {
    public int kthFactor(int n, int k) {
        for (int factor = 1; factor <= n; factor++) {
            if (n % factor == 0 && --k == 0)
                return factor;
        }
        
        return -1;
    }
}
```

Solution 2
```
class Solution {
    public int kthFactor(int n, int k) {
        int root = (int) Math.sqrt(n);
        
        for (int factor = 1; factor <= root; factor++) {
            if (n % factor == 0 && --k == 0)
                return factor;
        }
        
        if (root * root == n) root--;
        for (int factor = root ; factor >= 1; factor--) {
            if (n % factor == 0 && --k == 0)
                return n / factor;
        }
        
        return -1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Expected Behavior:
The naive solution (solution 1) should TLE for larger inputs.

Actual Behavior: 
Even the naive solution passes with 0ms runtime.

**Comment by lc-kay** [comment]
Hi @yashchitre03 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@yashchitre03 The problem was designed to allow both solutions and for consistency, we cannot change the input data type to fail some solutions. Thank you for your understanding.
