### ISSUE TITLE
Missing Test Case - 473. Matchsticks to Square

### ISSUE THREAD

**Issue by jtwangac** [LeetCode-Feedback/LeetCode-Feedback#3853]
#### Your LeetCode username

jtwangac

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some submitted algorithms that greedily build each side are wrong algorithms, but they pass all current test cases.
See the following missing test case:
[13, 11, 1, 8, 6 , 7 , 8 ,8, 6 , 7 , 8 ,9, 8] contributed by Leetcode user oliver_feng in the # 1 comment of this Leetcode [post](https://leetcode.com/problems/matchsticks-to-square/discuss/95752/Java-DFS-solution-with-various-optimizations-(sorting-sequential-partition-DP)).

A greedy algorithm may select 13, 11, 1 to form the first side, then it cannot form the rest three sides, and end with outputting False. This is the behavior of the code pasted in the next section. This code passes all current test cases. However, for this test case, the true answer should be True, as the four sides can be built as [13, 6, 6], [11, 7, 7], [9, 8, 8], [8, 8, 8, 1].

#### Code you used for Submit/Run operation

```python
class Solution:
    def makesquare(self, A):
        sm = sum(A)
        n = len(A)
        if sm % 4 != 0: return False
        sl = sm // 4
        A.sort(reverse=True)
        # sticks = [0] * 4
        done = set()
        
        def dfs(i, need): 
            if i == n: return False
            if i in done: return dfs(i + 1, need)
            if A[i] == need: 
                done.add(i)
                return True
            if A[i] < need: 
                done.add(i)
                if dfs(i + 1, need - A[i]): return True
                done.remove(i)
                return dfs(i + 1, need)
            return dfs(i + 1, need)
        
        for _ in range(4): 
            if not dfs(0, sl): return False
        return True
```

#### Language used for code

python

**Comment by lc-kay** [comment]
Hi @jtwangac 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jtwangac 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
