### ISSUE TITLE
Create detailed explanation

### ISSUE THREAD

**Issue by rahulrachh** [LeetCode-Feedback/LeetCode-Feedback#3854]
I would like to request leetcode to create a detailed explanation for the Approach2 in 280. Wiggle Sort. It just explains what the loop does. Does not explain how to arrive at that or what one might have thought of that would lead you to be there.

**Comment by lc-kay** [comment]
@rahulrachh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@rahulrachh Our team agrees with your suggestion and will make necessary changes and update the article as soon as possible. Have a great day!
