### ISSUE TITLE
[473. Matchsticks to Square] Zero square

### ISSUE THREAD

**Issue by YaroslavRepeta** [LeetCode-Feedback/LeetCode-Feedback#3855]
#### Your LeetCode username

yaroslav-repeta

#### Category of the bug
- [x] Question
- [x] Missing Test Cases 

#### Description of the bug

Problem constraints are `0 <= matchsticks[i] <= 10^9`.
But there are no test cases with `0` in input array.

#### Expected behavior

Either problem constraints should be fixed or a test case with `0`s should be added.

**Comment by lc-kay** [comment]
Hi @YaroslavRepeta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@YaroslavRepeta Thank you for your time. We have fixed this issue from an earlier report. We appreciate your support!
