### ISSUE TITLE
Missing Test Case - 1901. Find a Peak Element II

### ISSUE THREAD

**Issue by Bambooin** [LeetCode-Feedback/LeetCode-Feedback#3857]
#### Your LeetCode username
0x4C0DE

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An accepted solution fails on the following test case:
[[1,2,6],[3,4,5]]

#### Code you used for Submit/Run operation
```
class Solution {
  public int[] findPeakGrid(int[][] mat) {
    int m = mat.length;
    int n = mat[0].length;
    int row = 0;
    int column = 0;
    while (true) {
      // out of border, get -1
      int right = column + 1 < n ? mat[row][column + 1] : -1;
      int down = row + 1 < m ? mat[row + 1][column] : -1;

      // hit the peak
      //       [i-1, j-1] [i-1, j]
      //                     ^
      //       [i, j-1] < [i, j] > [i, j+1]
      //                     v
      //                  [i+1, j]
      if (mat[row][column] > right && mat[row][column] > down) {
        break;
      }

      if (right >= down) {
        // move right
        column++;
      } else {
        // move down
        row++;
      }
    }

    return new int[] {row, column};
  }
}
```

#### Language used for code
Java

#### Expected behavior
Expected: [0,2]
Output: [1,2]

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
