### ISSUE TITLE
1461. Check If a String Contains All Binary Codes of Size K

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#386]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Ambiguous problem statement

**Expected behavior**
Given a binary string s and an integer k.

Return True if any binary code of length k is a substring of s. Otherwise, return False.

This is the problem statement.

The title says all but description says any. The examples are correct assuming all is intended. Any can be misinterpreted.
Either replacing any with all or swapping True and False and negating the condition should make it right.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time! Upon reviewing this issue, we found out that we've fixed the issue immediately after contest and prior to this GitHub issue being filed. Therefore there is no reward for this issue. Please try again :)

**Comment by leet212** [comment]
Hello @CooperCooperCooper 

> Upon reviewing this issue, we found out that we've fixed the issue immediately after contest and prior to this GitHub issue being filed.

I am skeptical about the accuracy of the statement. As I filed the issue well before the contest even ended it could not have been fixed prior to the issue being filed. 

Apart from that it was good to see the mistake being identified and fixed. Thank you for your response.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
My apologies for the mistake. What I meant was that our engineers caught and fixed the mistake by themselves before we could notify them of the issue. Therefore, this issue would be valid but we cannot offer you reward for this one. I am sorry for the confusion and thank you for your time and support.

**Comment by leet212** [comment]
Hello @CooperCooperCooper ,
No need to apologize. It was me who did not get what you meant to say. Thank you for your response.
