### ISSUE TITLE
Missing Test Case - 713. Subarray Product Less Than K

### ISSUE THREAD

**Issue by dusthaha** [LeetCode-Feedback/LeetCode-Feedback#3860]
#### Your LeetCode username
dusthaha

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

there is no testcase for 0 inside array
For example: 
[10,5,2,0,6]
100
I think the answer would be 14 because [10,5,2,0], [10,5,2,0,6] should be counted.

**Comment by lc-kay** [comment]
Hi @dusthaha 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@dusthaha Our team has fixed this issue before reviewing this ticket. Thank you for your time.
