### ISSUE TITLE
Wrong example in solution 204. Count Primes

### ISSUE THREAD

**Issue by kwangh** [LeetCode-Feedback/LeetCode-Feedback#3861]
#### Your LeetCode username

mm9139

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the solution part,
```
It is not necessary to consider any number greater than the square root of n. 

6 * 1 = 6 = 1 * 6 <--- should be 2 * 3
6 * 2 = 12 = 2 * 6
...

Notice that every multiple of 6 was already addressed by some multiple of a prime number less than 6.
```

Since the example shows that we have considered all of the possible prime numbers beforehand.

**Comment by lc-kay** [comment]
Hi @kwangh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
