### ISSUE TITLE
Incorrect explanation in solution - 887. Super Egg Drop

### ISSUE THREAD

**Issue by av1shek** [LeetCode-Feedback/LeetCode-Feedback#3862]
#### Your LeetCode username
av1shek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The recurrence relation written in the explanation of Approach 1 and Approach 2 is not correct. The recurrence relation currently written in the explanation is
```
dp(K,N)=min(max(dp(K−1,X−1),dp(K,N−X)))
```
which is incorrect. It should be
```
dp(K,N)=1+min(max(dp(K−1,X−1),dp(K,N−X)))
```

#### Code you used for Submit/Run operation

```
No need of code as it is related to solution explanation.
```

#### Language used for code
 C++ 

#### Expected behavior
The recurrence relation in Approach 1 and Approach 2 explanation should be
```
dp(K,N)=1+min(max(dp(K−1,X−1),dp(K,N−X)))
```

#### Screenshots

![image](https://user-images.githubusercontent.com/59140024/122184982-62a9f600-ceaa-11eb-8785-6833a1d7bc70.png)
![image](https://user-images.githubusercontent.com/59140024/122185304-9f75ed00-ceaa-11eb-8910-84245253589c.png)

**Comment by lc-kay** [comment]
Hi @av1shek 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by av1shek** [comment]
I think leetcode forgot to look into this.

**Comment by lc-kay** [comment]
@av1shek Our team is still reviewing this issue. Thank you for your patience.
