### ISSUE TITLE
Missing Test Case - 22. Generate Parentheses

### ISSUE THREAD

**Issue by sudheep2** [LeetCode-Feedback/LeetCode-Feedback#3863]
#### Your LeetCode username

SudheepRao
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

for the test case n=4 we should get (())(()) but in the expected outcome it isn't showing 

#### Code you used for Submit/Run operation

// Two Sum
```
class Solution {
public:
    set<string> f(int n){
        if(n==1){
            return {"()"};
        }
       set<string> l=f(n-1);
        
        set<string >ans;
       
        for(auto s:l){
             ans.insert("("+s+")");
            ans.insert("()"+s);
           
            ans.insert(s+"()");
        }
             
      return ans;  
    }
    vector<string> generateParenthesis(int n) {
       set<string> s=f(n);
        vector<string>ans(s.begin(),s.end());
        sort(ans.begin(),ans.end());
        return ans;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

for n=4 the expected answer string should contain (())(()) because it is a valid parenthesis

#### Screenshots

![Screenshot (178)](https://user-images.githubusercontent.com/65455794/122197005-655e1880-ceb5-11eb-8adc-e79457a4701e.png)

#### Additional context

no

**Comment by lc-kay** [comment]
@sudheep2 The expected output is correct. It appears that you are not returning "(())(())". Please refer to the discuss section if you have further questions. Thank you for your time.
