### ISSUE TITLE
Error while running code - 22. Generate Parentheses

### ISSUE THREAD

**Issue by shyam640** [LeetCode-Feedback/LeetCode-Feedback#3864]
#### Category of the bug
- [ ]  Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I run a test case with custom input and it was giving correct answer but when I submitted my solution for the same input it was showing error.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    void addParenthesisString(vector<string> &ans,int pos,int n,int open,int close){
        static char str[100];
        if(close==n){
            ans.push_back(str);
            return;
        }else{
            if(open>close){
                str[pos]=')';
                addParenthesisString(ans,pos+1,n,open,close+1);
            }
            if(open<n){
                str[pos]='(';
                addParenthesisString(ans,pos+1,n,open+1,close);
            }
        }
        
    }
    vector<string> generateParenthesis(int n) {
        vector<string> ans;
        
        addParenthesisString(ans,0,n,0,0);
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
It should have passed my test case

#### Screenshots
![Screenshot 2021-06-16](https://user-images.githubusercontent.com/69409625/122204075-5333a880-cebc-11eb-9915-52790edd3304.png)

**Comment by lc-kay** [comment]
Hi @shyam640 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
