### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by TurqayUmudzade** [LeetCode-Feedback/LeetCode-Feedback#3865]
#### Your LeetCode username
TurqayUmudzade

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On question 209 there is a test case which gives
target=213
arr=[12,28,83,4,25,26,25,2,25,25,25,12]

the answer is 7 but it gives 8

#### Code you used for Submit/Run operation

```
// Two Sum
var minSubArrayLen = function (target, arr) {
  arr.sort((a, b) => b - a);
  console.log(arr);
  let sum = 0;
  for (let i = 0; i < arr.length; i++) {
    sum += arr[i];
    console.log(sum);
    if (sum >= target) return i + 1;
  }
  return 0;
};
```

#### Language used for code
JS

#### Expected behavior
The questions asks where the sum of the subarray should be >= target, so I sorted the array in reverse order and started summing them up, the numbers
83, 28, 26, 25, 25,
  25, 25, 25
sum to 237 which is bigger then the target so the answer should be 7

**Comment by lc-kay** [comment]
@TurqayUmudzade The question says sum ≥ s, not sum = s. In addition, please check out this discuss post https://leetcode.com/problems/minimum-size-subarray-sum/discuss/192514/Issue-with-a-test-case For further questions, please refer to the problem discuss section. Thank you for your time.

**Comment by TurqayUmudzade** [comment]
Yes Sun of 7 is already bigger , no need for 8th
