### ISSUE TITLE
Missing Test Case - 1160. Find Words That Can Be Formed by Characters

### ISSUE THREAD

**Issue by SupratimSarkar2001** [LeetCode-Feedback/LeetCode-Feedback#3867]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@SupratimSarkar2001 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
