### ISSUE TITLE
Poor wording - 807. Max Increase to Keep City Skyline

### ISSUE THREAD

**Issue by caupcakes** [LeetCode-Feedback/LeetCode-Feedback#3868]
#### Your LeetCode username
hellotestabc

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The prompt is worded poorly. Instead of top or bottom, left or right, cardinal directions should be used.

**Comment by lc-kay** [comment]
Hi @caupcakes 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
