### ISSUE TITLE
Missing Test Case - 1389. Create Target Array in the Given Order

### ISSUE THREAD

**Issue by asanoviskhak** [LeetCode-Feedback/LeetCode-Feedback#3869]
#### Your LeetCode username

iskhakasan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some codes are passing your test cases, even though it shouldn't have.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> createTargetArray(vector<int>& nums, vector<int>& index) {
        int len=nums.size(), i;
        vector<int> res(len, 0);
        for(i=0; i<len; i++){
            if (res[index[i]]==0){
                res[index[i]]=nums[i];
            }
            else{
                for (int j=len-1; j>index[i]; j--){
                    swap(res[j], res[j-1]);
                }
                res[index[i]]=nums[i];
            }
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

While running this code on test input:
[0,1,0]
[0,1,0]
it will output as: [0,1,0], where expected should be [0, 0, 1]

#### Screenshots

![Screenshot 2021-06-17 060133](https://user-images.githubusercontent.com/33123327/122292971-82d0c800-cf31-11eb-9cc5-a49956c88eff.png)

**Comment by lc-kay** [comment]
Hi @asanoviskhak 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @asanoviskhak 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
