### ISSUE TITLE
Weak test cases for [1460. Make Two Arrays Equal by Reversing Sub-arrays]

### ISSUE THREAD

**Issue by ss005** [LeetCode-Feedback/LeetCode-Feedback#387]
#### Your LeetCode username
ss005

#### Category of the bug
- [x] Question/Test-case

#### Description of the bug

There are not enough test cases to verify the correctness of the code.

#### Code you used for Submit/Run operation

```java
// 1460. Make Two Arrays Equal by Reversing Sub-arrays
class Solution {
    public boolean canBeEqual(int[] target, int[] arr) {
        int ans = 0;
        for (int i = 0; i < target.length; i++) {
            ans ^= target[i];
            ans ^= arr[i];
        }

        return ans == 0;
    }
}
```

#### Language used for code

Java

#### Actual behavior
Above code passes all the existing test cases.

#### Expected behavior

**Below test cases should fail:**
1. suggested by LC user - @roll_no_1
target - [1,1], 
array - [3,3]

2. suggested by @mlchkhn/@mcao59
target = {5, 7} = {101, 111}
arr = {1, 3} = {001, 011}

**Comment by CooperCooperCooper** [comment]
Hi @ss005 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @ss005 ,
Thank you for reaching out to us. The contributed test case is invalid because your code gets "Wrong Answer" from this test case.

**Comment by ss005** [comment]
Well @CooperCooperCooper  I guess test cases were updated in-between, because I had submitted this code with "Accepted" status.
Thanks!
