### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by rrohak** [LeetCode-Feedback/LeetCode-Feedback#3870]
#### Your LeetCode username

rrohak

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some solutions are passing test cases when they shouldn't be.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean containsDuplicate(int[] nums) {
        if(nums.length == 0 || nums[0] == 237384 || nums[0] == -24500)
            return false;
        boolean[] solution = new boolean[2048];
        for(int i = 0; i < nums.length; i++){
            if(solution[nums[i] & 2047]){
                return true;
            } else{
                solution[nums[i] & 2047] = true;
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Running the code on the following test input:
[-24500, -24500]
[237384, 237384]
[2048, 0]
[30720, 0]

The answer should be true, true, false, false. The given code results in false, false, true, true while the expected is each answer flipped.

#### Screenshots

![image](https://user-images.githubusercontent.com/43389183/122312887-25158f00-cee3-11eb-8a01-d910fe1ad24d.png)

**Comment by lc-kay** [comment]
Hi @rrohak 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rrohak 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
