### ISSUE TITLE
Missing Test Case - 1798. Maximum Number of Consecutive Values You Can Make

### ISSUE THREAD

**Issue by warmongr** [LeetCode-Feedback/LeetCode-Feedback#3871]
#### Your LeetCode username

atulyadavjid

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases  : [1,1,300,301,302,303,304,305,306,307]

#### Description of the bug

The solution it is accepting right now is not working on the following test case [1,1,300,301,302,303,304,305,306,307].

#### Code you used for Submit/Run operation

```
//Maximum Number of Consecutive Values You Can Make
class Solution:
    def getMaximumConsecutive(self, coins: List[int]) -> int:
        coins.sort()
        ans = 1
        for coin in coins: 
            if coin > ans: 
                break
            ans+=coin
        return ans
```

#### Language used for code

Python

#### Expected behavior

Expected solution should be: 8

**Comment by lc-kay** [comment]
@warmongr The expected output is correct and your code is accepted for this test case. For further questions, please refer to the problem discuss section. Thank you for your time.
