### ISSUE TITLE
Missing Test Case - 795. Number of Subarrays with Bounded Maximum

### ISSUE THREAD

**Issue by kshitijanand36** [LeetCode-Feedback/LeetCode-Feedback#3873]
#### Your LeetCode username

kshitijanand2

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

    Expected TLE but got accepted

#### Code you used for Submit/Run operation

```
//Number of Subarrays with Bounded Maximum
class Solution {
public:
    int numSubarrayBoundedMax(vector<int>& nums, int left, int right) {
        
        int n = nums.size();
        int count = 0;
        for(int start = 0 ; start < n ;start++){
            
            int maxVal = 0;
            
            for(int i = start ;i  < n ; i++){
                maxVal = max(maxVal , nums[i]);
                
                if(maxVal > right)break;
                if(maxVal < left || maxVal > right)continue;
                
                count++;
            }
        }
        
        return count;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected TLE but got accepted.

#### Screenshots

![Screenshot (427)](https://user-images.githubusercontent.com/53054571/122372268-2ba51480-cf7e-11eb-8fb2-95cf6c1253fc.png)
#### Additional context

Test Case on which it gives TLE :- 
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6669163/testcase.txt)

**Comment by lc-kay** [comment]
Hi @kshitijanand36 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kshitijanand36 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
