### ISSUE TITLE
Wrong Testcase - 836. Rectangle Overlap

### ISSUE THREAD

**Issue by harshitkd** [LeetCode-Feedback/LeetCode-Feedback#3874]
#### Your LeetCode username

harshit_dave

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Wrong Test Case

#### Description of the bug

``` 
Wrong Answer
``` 

#### Code you used for Submit/Run operation

``` 
class Solution:
    def isRectangleOverlap(self, rec1: List[int], rec2: List[int]) -> bool:
        
        if (rec1[0]<rec2[2]) or (rec1[2]>rec2[0]) or (rec1[1]<rec2[3]) or (rec1[1]<rec2[3]):return False
        else: return True
``` 

#### Language used for code

Python

#### Expected behaviour

The particular test case has a rectangle of area 0, whereas, in constraints, it's written that the area should be positive.

**Comment by lc-kay** [comment]
Hi @harshitkd 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@harshitkd Our team has removed the edge case. Thank you for your time.
