### ISSUE TITLE
Wrong Test case- 1285 Add Two Numbers

### ISSUE THREAD

**Issue by chickenbiryani** [LeetCode-Feedback/LeetCode-Feedback#3875]
#### Your LeetCode username
abhishek13anand

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Wrong Test Cases 

#### Description of the bug
The problem statement states that two numbers do not contain any leading zero, except the number 0 itself. 
but test case 1285 has a leading zero in the first number 

Input:
[0,8,6,5,6,8,3,5,7]
[6,7,8,0,8,5,8,9,7]

#### Code you used for Submit/Run operation

```
func addTwoNumbers(l1 *ListNode, l2 *ListNode) *ListNode {
    if l1.Val == 0 {
        return l2
    }
    if l2.Val == 0{
        return l1
    }
    rem := 0
    res := l1
    prev := l1
    for l1 != nil && l2 != nil {
        sum := l1.Val + l2.Val
        sum += rem
        if sum >= 10 {
            sum = sum%10
            rem = 1
        }else {
            rem = 0
        }
        
        l1.Val = sum
        prev = l1
        l1 = l1.Next
        l2 = l2.Next
    }
    
    if l1 == nil {
        for l2 != nil {
            sum := rem + l2.Val
            //sum += rem
            if sum >= 10 {
                sum = sum%10
                rem = 1
            }else {
                rem = 0
            }
            tmp := &ListNode{Val: sum, Next: nil}
            prev.Next = tmp
            prev = tmp
            l2 = l2.Next
            
        }
    }else if l2 == nil {
        for l1 != nil {
            sum := rem + l1.Val
            //sum += rem
            if sum >= 10 {
                sum = sum%10
                rem = 1
            }else {
                rem = 0
            }

            l1.Val = sum
            prev = l1
            l1 = l1.Next
        }
    }
    
    if rem != 0 {
        fmt.Println(prev)
        tmp := &ListNode{Val: rem, Next: nil}
        prev.Next = tmp
    }
    
    return res
}
```

#### Language used for code

Go

#### Expected behavior

I expected none of the numbers to have a leading zero. if there was a leading zero I assumed it to be zero as stated in the question.
But leading zero was just ignored in the solution.

#### Screenshots

problem statement
![image](https://user-images.githubusercontent.com/7123069/122430059-e4844700-cfb0-11eb-905f-c7a472dc517e.png)

faulty test case. First number has a leading zero
![image](https://user-images.githubusercontent.com/7123069/122430493-48a70b00-cfb1-11eb-9263-57eba1d74afd.png)

**Comment by stormsunshine** [comment]
Do you mean the problem [2. Add Two Numbers](https://leetcode.com/problems/add-two-numbers)? This test case is correct. Please read the description carefully.
> The digits are stored in **reverse order**, and each of their nodes contains a single digit.

Therefore, this test case has two numbers 753865680 and 798580876, and the sum of the two numbers is 1552446556. Neither number has a leading zero.

**Comment by lc-kay** [comment]
@chickenbiryani Please check out @stormsunshine explanation. Thank you for your time.
