### ISSUE TITLE
795. Number of Subarrays with Bounded Maximum

### ISSUE THREAD

**Issue by agupta2303** [LeetCode-Feedback/LeetCode-Feedback#3877]
** Tests output should consider , if the numbers are not unique. **

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution and test case output not considering , if the numbers are not unique.
for example for this customized test case :
[2,1,2,4,3]
2
3

Test output is  is 6 , but won't it be 5 instead ?
the subarray it's break into is : 
[2, 1, 2] and [3]
i.e.
[2], [1], [2], [2, 1], [1, 2], [2,1, 2] , [3] --- count 7
we remove the subset [1] as it is less than "l "which is 2.-- count comes to 6.

but then we have a subset " [2] " twice , which  should be counted as one and answer should be 5.

 -->

#### Code you used for Submit/Run operation
 ```
class Solution {
    public int numSubarrayBoundedMax(int[] A, int L, int R) {
        return count(A, R) - count(A, L-1);
    }

    public int count(int[] A, int bound) {
        int ans = 0, cur = 0;
        for (int x: A) {
            cur = x <= bound ? cur + 1 : 0;
            ans += cur;
        }
        return ans;
    }
}
```

#### Language used for code
 java

**Comment by lc-kay** [comment]
Hi @agupta2303 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@agupta2303 Our team has reviewed the problem description and the second example shows that the array may contain duplicates. The output is 6 because we have [2], [2], [3], [2,1], [1,2], [2,1,2]. Thank you for your time.
