### ISSUE TITLE
Missing Test Case - 401. Binary Watch

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3879]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In [401. Binary Watch](https://leetcode.com/problems/binary-watch), a test case is missing, and there exist some code that does not pass the test case still gets accepted when submitted.
The missing test case is `turnedOn = 10`.

#### Code you used for Submit/Run operation
```
class Solution {
    public List<String> readBinaryWatch(int turnedOn) {
        List<String> timeList = new ArrayList<String>();
        if (turnedOn == 10) {
            timeList.add("0:00");
            return timeList;
        }
        for (int i = 0; i < 12; i++) {
            int minuteOnes = Integer.bitCount(i);
            if (minuteOnes > turnedOn) {
                continue;
            }
            for (int j = 0; j < 60; j++) {
                int secondOnes = Integer.bitCount(j);
                if (minuteOnes + secondOnes == turnedOn) {
                    String time = toTime(i, j);
                    timeList.add(time);
                }
            }
        }
        return timeList;
    }

    public String toTime(int hour, int minute) {
        return hour + ":" + getTwo(minute);
    }

    public String getTwo(int num) {
        String str = String.valueOf(num);
        if (num < 10) {
            str = "0" + str;
        }
        return str;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The code above should get Wrong Answer when submitted since it fails for the test case `turnedOn = 10`.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by haji8-lg** [comment]
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/29276
