### ISSUE TITLE
1460. Make Two Arrays Equal by Reversing Sub-arrays

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#388]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Incorrect solution gets accepted

#### Code you used for Submit/Run operation
```
class Solution(object):
    def canBeEqual(self, a, b):
        return set(a) == set(b)
```

#### Language used for code
Python

#### Expected behavior
Should fail this test case

[1,2,3,4,1]
[2,4,1,3,3]

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
