### ISSUE TITLE
Wrong Test Case - 1353. Maximum Number of Events That Can Be Attended

### ISSUE THREAD

**Issue by AjayGulia** [LeetCode-Feedback/LeetCode-Feedback#3882]
AjayGullu

Ques:
https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/

class Solution {
public:
    
     
    
	int maxEvents(vector<vector<int>>& events) {
		sort(events.begin(),events.end(),[](const auto& a, const auto& b){
			return a[1]<b[1];
		});
		vector<int> cnt(100002,0);
		int ans=0;
		for(int i=0;i<events.size();i++){
			for(int j=events[i][0];j<=events[i][1];j++){
				if(cnt[j]!=0) continue;
				cnt[j]=1;
				ans++;
				break;
			}

		}

		return ans;
	}
 };

#### Description of the bug

Wrong Test Case

Test Case
[[1,10],[2,3],[2,3],[2,3],[2,3]]
expected should be 3 
but it shows 100000

#### Code you used for Submit/Run operation

```

**Comment by Cheng-Chi-Tang** [comment]
So does test case 41, [[1,2],[1,2],[1,8],[1,8],[3,4],[3,4],[3,4]], the answer should be 6 instead of 99888.

**Comment by lc-kay** [comment]
Hi @AjayGulia 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AjayGulia @Cheng-Chi-Tang 
Our team has fixed this issue.
