### ISSUE TITLE
Missing Test Case - 307. Range Sum Query - Mutable

### ISSUE THREAD

**Issue by pm-nishant** [LeetCode-Feedback/LeetCode-Feedback#3884]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@pm-nishant Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
