### ISSUE TITLE
change "till" to "while" in Approach 3: Segment Tree section of solution to 307. Range Sum Query - Mutable

### ISSUE THREAD

**Issue by hamirmahal** [LeetCode-Feedback/LeetCode-Feedback#3888]
#### Your LeetCode username

hamirmahal

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Approach 3: Segment Tree section of the solution to 307. Range Sum Query - Mutable says,
> Loop till l≤r

This implies that we keep looping **until** l≤r, and then we stop. This is incorrect and not what we want.

#### Expected behavior

The Approach 3: Segment Tree section of the solution to 307. Range Sum Query - Mutable should actually say,
> Loop **while** l≤r

This means we only loop **while** l≤r. The actual Java code on the same solution page has it correct.
#### Screenshots

![image](https://user-images.githubusercontent.com/43425812/122619502-6faf1c80-d045-11eb-9da3-517e5bdc3bc7.png)

#### Additional context

The actual code portion of the solution is correct.

![image](https://user-images.githubusercontent.com/43425812/122619383-31196200-d045-11eb-97b0-f1ded0395374.png)

**Comment by lc-kay** [comment]
Hi @hamirmahal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
