### ISSUE TITLE
88. Merge Sorted Array hardcoded wrong output

### ISSUE THREAD

**Issue by alexandrtovmach** [LeetCode-Feedback/LeetCode-Feedback#389]
#### Your LeetCode username
alexandrtovmach

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Testcase returns hardcoded value

1. Open https://leetcode.com/problems/merge-sorted-array/
2. Select "JavaScript"
3. Click "Run Code" (with or without code changes)

Expected result: Wrong answer with returned value from function in Output
Actual result: Wrong answer with `[1,2,3,0,0,0]` in Output

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums1
 * @param {number} m
 * @param {number[]} nums2
 * @param {number} n
 * @return {void} Do not return anything, modify nums1 in-place instead.
 */
var merge = function(nums1, m, nums2, n) {

};
```

#### Language used for code
JavaScript

**Comment by CooperCooperCooper** [comment]
Hi @alexandrtovmach ,
Thank you for reaching out to us. Can you please verify the empty code definition is the code submission you would like to share with us for this investigation?

**Comment by alexandrtovmach** [comment]
@CooperCooperCooper Yep, that's reproducible code sample, and can be used for investigation

**Comment by CooperCooperCooper** [comment]
Hi @alexandrtovmach ,
Thank you for your answer. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @alexandrtovmach ,
Thank you for your time. We've taken a thorough look into the information you've provided. To overcome this issue, please make sure your code "...Do not return anything, modify nums1 in-place instead".

**Comment by alexandrtovmach** [comment]
@CooperCooperCooper omg, I didn't pay attention, sorry for disturb
