### ISSUE TITLE
题库的测试用例未涵盖所有情况

### ISSUE THREAD

**Issue by cdround** [LeetCode-Feedback/LeetCode-Feedback#3891]
提交通过，但已手动找到一个不通过的测试用例
提交通过代码：
from collections import Counter
class Solution:
    def hasGroupsSizeX(self, deck: List[int]) -> bool:
        if len(deck) == 1:
            return False
        else:
            _ = sorted(set(Counter(deck).values()))
            a = _[0] # 对应的最小重复次数
            if a == 1: return False
            if len(_) == 1: return True
            if len(_) == 2:
                if _[1] % a == 0:
                    return True
                elif _[1] % a == 1:
                    return False
                else:
                    return a % ( _[1] % a) == 0
            else:
                m = 0  # 最小公约数
                if _[1] % a == 0:
                    m = a
                else:
                    n = a % (_[1] % a)
                    if n == 0:
                        m = _[1] % a
                    else:
                        m = n
                if m == 1: return False
                else:
                    for i in _[2:]:
                        if i % m != 0:
                            return False
                    return True
未通过的手动测试用例：
[1,1,1,1,3,3,3,3,3,3,3,3,5,5,5,5,5,5,5,5,5,5]

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@cdround 感谢反馈，能否向我们补充题目信息，以及完善代码格式。可以参考[这个反馈](https://github.com/LeetCode-Feedback/LeetCode-Feedback/blob/master/.github/ISSUE_TEMPLATE/bug--------.md)，把信息提供完整才能有助于快速验证和精准的定位，谢谢。

**Comment by feiceh** [comment]
您好，本次 Ticket 将关闭，感谢您的反馈和支持。
