### ISSUE TITLE
Missing Test Case - 396. Rotate Function

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#3893]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For test case `[2147483647,2147483647,2147483647]`
- Fails in Run Code
- Passes on Submit

Either the Constraints are wrong, or Judge is wrong.

#### Code you used for Submit/Run operation

```
var maxRotateFunction = function(A) {
    let n = A.length;

    let sum = 0
    for (let e of A)
        sum += e;

    let currSum = 0
    A.forEach((e, i) => {
        currSum += e * i
    })
    // console.log(currSum, sum)

    let maxSum = currSum
    for (let i = 0; i < n - 1; i++) { // 1 iteration will be repeated if  <n
        currSum += A[i] * n - sum
        maxSum = Math.max(maxSum, currSum)
    }

    return maxSum;
};
```

#### Language used for code
JS

#### Expected behavior

- Fails in Run Code
- Passes on Submit
Behaviour should be consistent. Please fix the test cases limits in the question.

#### Screenshots
Fails in Runs Code

![image](https://user-images.githubusercontent.com/8236389/122640463-65f8e800-d11d-11eb-80a5-1e1a727abb96.png)

Passes on Submit

![image](https://user-images.githubusercontent.com/8236389/122640486-77da8b00-d11d-11eb-830b-dde0998cee0f.png)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by manoharreddyporeddy** [comment]
@lc-kay 

my LC ID is pgmreddy
URL   https://leetcode.com/pgmreddy/

**Comment by manoharreddyporeddy** [comment]
@lc-kay  any update on this?

**Comment by lc-kay** [comment]
@manoharreddyporeddy Your account has been rewarded with 100 LeetCoins. Have a great day!
