### ISSUE TITLE
Missing Test Case - 224. Basic Calculator

### ISSUE THREAD

**Issue by shubhDcoder** [LeetCode-Feedback/LeetCode-Feedback#3895]
#### Your LeetCode username

bitterbit

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [Yes ] Missing Test Cases 

#### Description of the bug

One of the randomly generated test cases was being considered as a wrong answer whereas the solution got accepted. 
Test case which I used was : "+-(-+76-+09++((2) +- (-2)))".
The correct answer should be +81;
LeetCode's answer is -89. Which is wrong.

#### Code you used for Submit/Run operation

```
class Solution {
    public int calculate(String s) {
        int sum = 0;
        boolean isNegative = false;;
        Deque<Integer> stack = new ArrayDeque<>();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (Character.isDigit(c)) {
                int number = 0;
                while (i < s.length() && Character.isDigit(s.charAt(i))) {
                    number = number * 10 + s.charAt(i) - '0';
                    i++;
                }
                i--;
                if (isNegative) number = -number;
                isNegative = false;
                sum += number;
            } else if (c == '(') {
                stack.push(sum);
                stack.push(isNegative ? -1 : +1);
                isNegative = false;
                sum = 0;
            } else if (c == ')') {
                sum *= stack.pop();
                sum += stack.pop();
                // isNegative = false;
            } else if (c == '-') {
                isNegative = !isNegative;
            }
        }
        return sum;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The answer should be +81.
Leetcode is showing -89 as the answer.
However, my solution got accepted.
Test case is "+-(-+76-+09++((2) +- (-2)))"

**Comment by lc-kay** [comment]
Hi @shubhDcoder 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @shubhDcoder 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
