### ISSUE TITLE
1497. Check If Array Pairs Are Divisible by k; missing testcase

### ISSUE THREAD

**Issue by Swapnil-2001** [LeetCode-Feedback/LeetCode-Feedback#3896]
#### Your LeetCode username
Swap24

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A test case is missing for the problem. Faulty solution passes all available test cases.

#### Code you used for Submit/Run operation

```
class Solution:
    def canArrange(self, arr: List[int], k: int) -> bool:
        if sum(arr) % k != 0:   return False
        rems = [0] * k
        for ele in arr:   rems[ele % k] += 1
        if k % 2 == 0 and rems[k // 2] % 2 != 0:
            return False
        for rem in range(1, k // 2):
            if rems[rem] != rems[k - rem]:
                return False
        return True
```

#### Language used for code
Python 3

#### Expected behavior
The solution was not supposed to pass all test cases.

#### Screenshots

![Check If Array Pairs Are Divisible by k - LeetCode - Google Chrome 19-06-2021 21_42_59](https://user-images.githubusercontent.com/53232360/122648547-63ab8380-d147-11eb-8c8b-13d7f0ae7ea8.png)

#### Additional context
A test case that may be added is 
[2,2,2,2,2,2]
3

**Comment by lc-kay** [comment]
Hi @Swapnil-2001 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Swapnil-2001 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
