### ISSUE TITLE
[false positive] Javascript: Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by markgarg** [LeetCode-Feedback/LeetCode-Feedback#3898]
#### Your LeetCode username: 
markusg

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When using the following solution for Javascript, the `Run Code` and `Submit` says that the solution is wrong, but it works in the console/jsfiddle/codepen. Please can you check?

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @return {number}
 */
var removeDuplicates = function(nums) {
    let numOfDuplicates = 0;
    const size = nums.length;
    for(let i=(size-1); i>0; i--) {
        if(nums[i] <= nums[i-1] && i < size) {
            nums[i] = nums[i+1];
            numOfDuplicates++;
        }
    }
    return numOfDuplicates;
};
```

#### Language used for code
Javascript

#### Expected behavior
The code should have passed the mentioned test case. The test case that fails is this: 
```
 Input: [1,1,2]
 Output: [1] 
 Expected: [1,2] 
```
However, the actual array `nums` is `[1,2,2]` so it should be alright.

#### Screenshots

Passes in the console:
<img width="526" alt="Screen Shot 2021-06-19 at 21 48 02" src="https://user-images.githubusercontent.com/8937055/122655132-25fb2a80-d148-11eb-9c36-6da3d5010d27.png">

Failure reported in LeetCode:
<img width="1015" alt="Screen Shot 2021-06-19 at 21 45 12" src="https://user-images.githubusercontent.com/8937055/122655142-30b5bf80-d148-11eb-8693-ebb3d5c47d52.png">

**Comment by lc-kay** [comment]
@markgarg We are unable to troubleshoot the difference in behavior between LeetCode's environment and the local environment. For further support, please refer to the problem discuss section as other users may have encountered the same behavior. Thank you for your time.
