### ISSUE TITLE
consider placing articles on GitHub for easier corrections and suggestions

### ISSUE THREAD

**Issue by hamirmahal** [LeetCode-Feedback/LeetCode-Feedback#3899]
I was wondering if LeetCode would post their articles on GitHub so we could propose suggestions and corrections more directly and easily, similar to how [MDN](https://github.com/mdn/content) does it. Could we do that?

**Comment by lc-kay** [comment]
@hamirmahal Thank you for your feedback. I've relayed this to our team to take into consideration.
