### ISSUE TITLE
1137. Height Checker test output wrong.

### ISSUE THREAD

**Issue by rdev02** [LeetCode-Feedback/LeetCode-Feedback#390]
#### Your LeetCode username
vnomad

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
Example answer is incorrect:
```
Input: heights = [1,1,4,2,1,3]
Output: 3
Explanation: 
Current array : [1,1,4,2,1,3]
Target array  : [1,1,1,2,3,4]
On index 2 (0-based) we have 4 vs 1 so we have to move this student.
On index 4 (0-based) we have 1 vs 3 so we have to move this student.
On index 5 (0-based) we have 3 vs 4 so we have to move this student.
```
however minimal amount of swaps is actually 2:
```
Input: heights = [1,1,4,2,1,3]
Output: 2
Explanation: 
Current array : [1,1,4,2,1,3]
Target array  : [1,1,1,2,3,4]
1 swap index 2 and 5(0-based) to obtain
[1, 1, 3, 2, 1, 4]
2 swap index 2 and 4(0-based)  to obtain
[1, 1, 1, 2, 3, 4]
```

#### Code you used for Submit/Run operation

```
class Solution {
    public int heightChecker(int[] heights) {
        int[] copy = heights.clone();
        Arrays.sort(copy);

        int swaps = 0;
        for(int i = heights.length - 1; i >=0 ; i--) {
            if(heights[i] == copy[i]) {
                continue; //element in it's place
            }

            // we'll need to swap this element with the one that is at place j in sorted arr
            int j = 0;
            for(; j < i; j++) {
                if (heights[j] == copy[i]){
                    break;
                }
            }
            int t = heights[j];
            heights[j] = heights[i];
            heights[i] = t;

            swaps++;
        }

        return swaps;
    }
}
```

#### Language used for code
java

#### Expected behavior
test answer is should be 2.

#### Additional context
second example is wrong too
```
j = 0 i = 4
[4, 1, 2, 3, 5]
j = 0 i = 3
[3, 1, 2, 4, 5]
j = 0 i = 2
[2, 1, 3, 4, 5]
j = 0 i = 1
[1, 2, 3, 4, 5]
4
```

**Comment by CooperCooperCooper** [comment]
Hi @rdev02 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @rdev02 ,
Thank you for your time. Upon a thorough review of your code and the problem, we found your code to be wrong because we are not performing swap operations for this problem. 

Additionally, please make sure you're putting the correct problem number for the title. This problem is "1051. Height Checker", where as problem number "1137" is for "N-th Tribonacci Number". We appreciate your support.
