### ISSUE TITLE
Regrade Contest 246 Q4 Python!!!

### ISSUE THREAD

**Issue by zhang8277** [LeetCode-Feedback/LeetCode-Feedback#3900]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [1] Language
- [ ] Missing Test Cases 

#### Description of the bug

For Q4, 100 * n python solution failed so many times with TLE. Really should extend the time allowed for python.
These kinds of issues are not the first time problem LC contest had. Why can LC just extend the Python limit to 15s? Fighting the constant diff to pass the test is meaningless.

#### Code you used for Submit/Run operation

```
100 N!
```

#### Language used for code

Py3

**Comment by zerotrac** [comment]
It is your own responsibility to take care of your code written in non-imperative language like Python.
Actually the [official solution](https://leetcode-cn.com/problems/minimum-absolute-difference-queries/solution/cha-xun-chai-jue-dui-zhi-de-zui-xiao-zhi-fjjq/) written in Python given in Leetcode CN site could finish in ~3s, so anyway 10s time limit is enough.

**Comment by zhang8277** [comment]
真是站着说话不腰疼，你把排名第一的人的cpp翻译成py看看能不能在4s之内完成。append+copy省个初始化时间就过了，多初始化一次就TLE。因为用python就得多TLE几次，多修改常数，难道不是case写的不好？要不LC写个申明，prefer user不用js py呗。

**Comment by zerotrac** [comment]
他急了他急了

**Comment by zhang8277** [comment]
你又嘴贱了。你家长没教你闭嘴吗？

**Comment by zerotrac** [comment]
就你这态度也别做leetcode了，做你家长的小皇帝去吧。

**Comment by zhang8277** [comment]
就你这态度也别来回复issue了，想恶心人可以恶心你爸妈去

**Comment by zerotrac** [comment]
@lc-kay @Miloas plz do not reply to this issue. Leetcode may not provide services for unfriendly people who offend other users.

**Comment by zhang8277** [comment]
offend了好难受，急了快告老师。
