### ISSUE TITLE
5789. 你完成的完整对局数 | 数据弱

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#3902]
**你的 LeetCode 用户名**

不告诉你

**Bug 类型**

- [x] 测试数据

**描述**

测试数据较弱，错误的方法，例如 [c++/python3 数轴](https://leetcode-cn.com/problems/the-number-of-full-rounds-you-have-played/solution/cpython3-shu-zhou-by-hanxin_hanxin-opo5/) 可以通过。

**你使用的语言**

Python

**你提交或者运行的代码**

```Python

class Solution:
    def numberOfRounds(self, startTime: str, finishTime: str) -> int:
        h1, m1 = map(int, startTime.split(':'))
        h2, m2 = map(int, finishTime.split(':'))
        
        a1 = h1 * 60 + m1
        a2 = h2 * 60 + m2
        
        if a2 < a1:
            a2 += 24 * 60
        
        a = ceil(a1 / 15)
        b = floor(a2 / 15)
        return b - a
```

**期望行为**

对于测试数据 `"12:01" "12:02"` 应当返回 `0`，但上述代码返回错误答案 `-1`。

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈。

**Comment by lc-kay** [comment]
@zerotrac Your code fails on our recently updated test case from earlier contributions. Therefore, we did not add this test case. Thank you for your time.
