### ISSUE TITLE
Missing test case for problem. 101 Symmetric Tree

### ISSUE THREAD

**Issue by Ritsz123** [LeetCode-Feedback/LeetCode-Feedback#3903]
#### Your LeetCode username
riteshkhadse12

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I tried to solve the question using BFS with slightly different approach. I used -1 wherever it was null in the testcase and also used a node of value -1 as the constraints stated the value can be between -100 to 100. According to me this solution should not get accepted but it got AC. 
Also the test case shows wrong answer when used as custom test case.

#### Test case used
Input: [1,2,2,3,null,-1,3]
Output: true
Expected: false

#### Code you used for Submit/Run operation

```
// Symmetric Tree
public boolean isSymmetric(TreeNode root) {
        int level = 1;
        Queue<TreeNode> q = new LinkedList<>();
        q.add(root);
        while(!q.isEmpty()){
            int size = q.size();
            int[] arr = new int[size];
            int x = 0;
            for(int i = 0;i< size;i++,x++){
                TreeNode curr = q.remove();
                if(curr != null){
                    arr[x] = curr.val;
                    q.add(curr.left);
                    q.add(curr.right);    
                }else{
                    arr[x] = -1;
                }
                
            }
            x = 0;
            int y = size-1;
            while(x<y){
                if(arr[x] != arr[y]){
                    return false;
                }
                x++;
                y--;
            }
        }
        return true;
    }
```

#### Language used for code
Java

#### Expected behavior

The code should not get accepted as it fails in the proposed test case.

**Comment by lc-kay** [comment]
Hi @Ritsz123 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Ritsz123 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
