### ISSUE TITLE
Missing Test Case - 1904. The Number of Full Rounds You Have Played

### ISSUE THREAD

**Issue by deafTim** [LeetCode-Feedback/LeetCode-Feedback#3904]
#### Your LeetCode username

TIENTI0000

#### Category of the bug
- [+] Missing Test Cases 

#### Description of the bug

TestCase startTime=00:01, finishTime =00:02 is not in the set of the testcases I think

#### Code you used for Submit/Run operation

```
class Solution:
    def numberOfRounds(self, s: str, f: str) -> int:
        def calc(time):
            t = [0,0]
            t[0], t[1] = map(int, time.split(":"))
            t = 60*t[0]+t[1]
            return t
        s = calc(s)
        f = calc(f)
        if s<f:
#            return int(floor(f/15) - ceil(s/15)) #wrong line
            return max(0,int(floor(f/15) - ceil(s/15))) #max because e.g. start=00:01, 00:14 will wrong 
        else:
            return int(floor(f/15) + calc("24:00")/15 - ceil(s/15))
```

#### Language used for code

Python3

#### Expected behavior

TestCase startTime=00:01, finishTime =00:02 should be in testcases because in contest I passed all tests but this one would give wrong answer -1 for my previous solution, but answer should be 0

#### Screenshots

[](url)
[Wrong test](https://github.com/deafTim/Images_for_Leet_Code/blob/af511094ecc1080cf67f65816c455616f3ded88f/Screenshot%202021-06-20%20at%2009.34.57.png)

**Comment by lc-kay** [comment]
@deafTim Can you please provide the submission details link for the code that failed this test case? Thank you!

**Comment by deafTim** [comment]
> @deafTim Can you please provide the submission details link for the code that failed this test case? Thank you!

https://leetcode.com/submissions/detail/511546224/

**Comment by lc-kay** [comment]
@deafTim Your code currently fails on this test case "00:47" "00:57". Therefore, we will not be adding your test case. Thank you for your time.
