### ISSUE TITLE
Missing Test Case - 1904. The Number of Full Rounds You Have Played

### ISSUE THREAD

**Issue by vivekfzd** [LeetCode-Feedback/LeetCode-Feedback#3905]
#### Your LeetCode username

Vivek_9680

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

In my code, it first add some value in start Time to do the multiple of 15 and same as it substract some value in finish time to do multiple of 15. then i check if start Time > Finish Time then it consider a whole day.
Example: if stat Time is: "12:02" and finish time is : "12:05". In my code, it first add some value in start time to do the multiple of 15 so therefore my start time is : "12:15" same as my finish time is : "12:00" there fore i consider a whole day that's why my answer is 95 but the correct answer is 0.
But my code is accepted.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int f(string s,bool flag){
        int h = stoi(s.substr(0,3));
        int m = stoi(s.substr(3,s.size()));
        int tm = h*60+m;
        //flag = 1 start
        if(flag){
            if(tm%15)
                tm = tm-(tm%15)+15;
            return tm;
        }
        return  tm = tm-(tm%15);
            
    }
    
    int numberOfRounds(string startTime, string finishTime) {
        int st = f(startTime,1);
        int ft = f(finishTime,0);
        
        int sh = stoi(startTime.substr(0,3));
        int fh = stoi(finishTime.substr(0,3));
        
        
        if(st>ft){
            int _ft = f("24:00",1);
            int _st = f("00:00",0);
            return (_ft-st)/15 + (ft-_st)/15;
        }
        
        
        return (ft-st)/15;
        
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

My code give a wrong answer but it is accepted by leetcode.
You should add one test case: startTime: "12:01" , finishTime: "12:02"

#### Screenshots

![image](https://user-images.githubusercontent.com/51323064/122665192-75cb0780-d1c3-11eb-94f9-188cd78225bd.png)

**Comment by lc-kay** [comment]
Hi @vivekfzd 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@vivekfzd Your code fails on our recently updated test case from earlier contributions. Therefore, we did not add this test case. Thank you for your time.
