### ISSUE TITLE
 K Inverse Pairs Array

### ISSUE THREAD

**Issue by abhijeeetdabade** [LeetCode-Feedback/LeetCode-Feedback#3907]
class Solution {
    public int kInversePairs(int n, int k) {
        int [] [] dp = new int [n+1] [k+1];
        
        // Building answer for all of value of N starting 1 going into N.
        for (int i = 0; i <= n; i++){
            
            for(int j = 0; j <= k; j++){
                
                if( j == 0){
                    
                    dp [i] [j] = 1;
                }
                else{
                    for(int p = 0; p <= Math.min(j, i-1); p++)
                        dp[i][j] = (dp[i][j] + dp[i-1] [j - p]) % 1000000007;
                    
                }
             }        
        }
        
        return dp[n][k];
        
    }
}

**Comment by lc-kay** [comment]
@abhijeeetdabade Please share your code on the problem discuss page. Thank you.
