### ISSUE TITLE
Missing Test Case - 785. Is Graph Bipartite?

### ISSUE THREAD

**Issue by Srishtik16** [LeetCode-Feedback/LeetCode-Feedback#3908]
**Missing Test Case Information**

[[1], [0, 2, 3], [1, 3], [1, 2]]

#### Your LeetCode username
srishtikdutta

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
 The Test Case Mentioned above is missing. My incorrect code passed with AC.

#### Code you used for Submit/Run operation
'''
```
class Solution {
public:
    int n;
    bool ok = true;
    void dfs(vector<vector<int>>& vec, vector<bool> &vis,vector<int>& coloured, int node, int dep) {
        vis[node] = true;
        for(auto x: vec[node]) {
            if(!vis[x]) {
                dfs(vec, vis, coloured, x, dep ^ 1);
                if(dep == 0) {
                    coloured[x] = 2;
                }
                else {
                    coloured[x] = 1;
                }
            }
        }
    }
    void checkBipartite(vector<vector<int>>& vec, vector<bool>& vis, vector<int>& coloured, int node) {
        for(int i = 0; i < n; i++) {
        if(!vis[i]) {
            for(auto x: vec[i]) {
                if(coloured[i] == coloured[x]) {
                    ok = false;
                    return;
                }
                vis[x] = true;
            }
        }
    }
    }
    bool isBipartite(vector<vector<int>>& vec) {
        n = vec.size();
        vector<bool> vis(n, false);
        vector<int> coloured(n, 0);
        coloured[0] = 1;
        for(int i = 0; i < n; i++) {
            if(!vis[i]) {
                coloured[i] = 1;
                dfs(vec, vis, coloured, i, 0);
            }
        }
        vis.assign(n, false);
        checkBipartite(vec, vis, coloured, 0);
        return ok;
    }
};
```
'''
#### Language used for code
 C++

#### Expected behavior
 In the above-mentioned test case, a wrong answer verdict is expected for my code, but it got an AC.

**Comment by lc-kay** [comment]
@Srishtik16 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.

**Comment by Srishtik16** [comment]
> @Srishtik16 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.

What kind of details do you need, can you let me know? My code is incorrect which I attached as it gives the wrong output on my attached test case, but the same code gets AC on leetcode for this problem, which implies that the test cases for this problem are weak.

**Comment by lc-kay** [comment]
<img width="882" alt="Screen Shot 2021-06-21 at 12 36 54 P@Srishtik16 " src="https://user-images.githubusercontent.com/70870126/122817900-5dbfba80-d28d-11eb-99c3-7e7506d36b8a.png">
@Srishtik16 Please make sure you have your edits saved.

**Comment by Srishtik16** [comment]
Sorry for the issues, I am new to this editing system so made a mistake. I have made the necessary changes so kindly review it once.

**Comment by lc-kay** [comment]
Hi @Srishtik16 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Srishtik16 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
