### ISSUE TITLE
Strange behaviour in running a test

### ISSUE THREAD

**Issue by gilad-tsur** [LeetCode-Feedback/LeetCode-Feedback#3909]
#### Your LeetCode username
giladtsur

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The code outputs False (e.g., when copied to a playground, or when the test case is run using the "Run Code" button), but is evaluated as True for the submission.

#### Code you used for Submit/Run operation

```
class Solution:
    def wordBreak(self, s: str, wordDict: List[str], breakableSet=set()) -> bool:
        if s in breakableSet:
            return True
        wordDictSet = set(wordDict)
        if len(s) == 0:
            return True
        else:
            for i in range(len(s)+1):
                if s[:i] in wordDictSet:
                    print(wordDictSet)
                    print(s[:i])
                    if self.wordBreak(s[i:], wordDict):
                        breakableSet.add(s)
                        return True
            return False
```

#### Language used for code
Python 3

#### Expected behavior

Consistent and correct behaviour between playground and task evaluation

#### Screenshots

![image](https://user-images.githubusercontent.com/23519930/122668505-4c54b080-d1b0-11eb-8383-2fd3d8ffc64a.png)
![image](https://user-images.githubusercontent.com/23519930/122668517-58407280-d1b0-11eb-9afd-d9355a9b0e4b.png)

**Comment by lc-kay** [comment]
Hi @gilad-tsur 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
