### ISSUE TITLE
Wrong example explanation for Database 607. Sales Person

### ISSUE THREAD

**Issue by minwoo33park** [LeetCode-Feedback/LeetCode-Feedback#391]
#### Your LeetCode username

minwoo33park

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The explanation of the example says that 'John' and 'Alex' have sales to company 'RED'. However, both the `orders` table in the example and the testcase suggest that 'John' and 'Pam' are the ones that have sales to company 'RED'

#### Screenshots

![Screen Shot 2020-05-30 at 6 04 35 PM](https://user-images.githubusercontent.com/33341131/83340667-a9797d80-a2a0-11ea-9781-b4fa9aea6034.png)

**Comment by CooperCooperCooper** [comment]
Hi @minwoo33park ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @minwoo33park ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
