### ISSUE TITLE
"787. Cheapest Flights Within K Stops" constraints contradicts the test case

### ISSUE THREAD

**Issue by peppered** [LeetCode-Feedback/LeetCode-Feedback#3910]
#### Your LeetCode username
peppered

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem definition states the following:

> There will not be any multiple flights between two cities.

But there is a test case (6/49):
```
5
[[4,1,1],[1,2,3],[0,3,2],[0,4,10],[3,1,1],[1,4,3]]
2
1
1
```
Which contradicts the statement, there is a multiple flights between `4` and `1`.

Is it correct?

**Comment by lc-kay** [comment]
Hi @peppered 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@peppered Please note that the flights are from city fromi to city toi. 1 --> 4 is different from 4 --> 1.
This is very clear in the statement and the images of the examples. Thank you for your time.
