### ISSUE TITLE
["TimeMap","set","set","get","set","get","get"] [[],["a","bar",1],["x","b",3],["b",3],["foo","bar2",4],["foo",4],["foo",5]]Missing Test Case - 981. Time Based Key-Value Store

### ISSUE THREAD

**Issue by abhi5hekkk** [LeetCode-Feedback/LeetCode-Feedback#3912]
["TimeMap","set","set","get","set","get","get"]
[[],["a","bar",1],["x","b",3],["b",3],["foo","bar2",4],["foo",4],["foo",5]]

**Comment by lc-kay** [comment]
@abhi5hekkk Please provide more details on your missing test case report, such as the accepted code that failed on this solution. After more information is provided, I will reopen this ticket. Thank you for your time.
