### ISSUE TITLE
Missing Test Case - 783. Minimum Distance Between BST Nodes

### ISSUE THREAD

**Issue by reetu-singh** [LeetCode-Feedback/LeetCode-Feedback#3913]
#### Your LeetCode username
Ritu926

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

The test case : [0,null,2236,1277,2776,519] is missing, my incorrect code is passed and is accepted.

#### Code you used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def minDiffInBST(self, root: TreeNode) -> int:
        self.prev = None
        self.ans = float('inf')
        
        def dfs(root):
            if root is None:
                return 
            dfs(root.left)
            if self.prev:
                self.ans = min(self.ans, root.val - self.prev)
            self.prev = root.val
            dfs(root.right)
            
        dfs(root)
        return self.ans
        
```

#### Language used for code
Python 3

#### Expected behavior

For the above code, wrong answer was expected for the above mentioned test-case, but it got accepted. When the test case is given individually, it is not passing.

#### Screenshots

<img width="1440" alt="Screenshot 2021-06-21 at 10 18 14 PM" src="https://user-images.githubusercontent.com/18307442/122852436-9a67d200-d2de-11eb-81f0-abe70fb085e8.png">
<img width="1440" alt="Screenshot 2021-06-21 at 10 17 38 PM" src="https://user-images.githubusercontent.com/18307442/122852452-a05db300-d2de-11eb-9ac8-f88f7bff2f5b.png">

**Comment by lc-kay** [comment]
Hi @reetu-singh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @reetu-singh 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
