### ISSUE TITLE
Missing Test Case - 981. Time Based Key-Value Store

### ISSUE THREAD

**Issue by abhi5hekkk** [LeetCode-Feedback/LeetCode-Feedback#3914]
Username - **abhi5hekkk**

Accepted Code - 

class TimeMap {
public:
    /** Initialize your data structure here. */

    set<pair<string,int>> s;
    map<pair<string,int>,string> mp;
    TimeMap() {   }
    void set(string k, string v, int t) {
        mp[{k,t}] = v;
        s.insert({k,t});
    }
    
    string get(string k, int t) {
        auto it = s.lower_bound({k,t});
        if(it == s.begin() && it->second > t) return "";
        if(it == s.end() || it->first != k || it->second > t) it--;
        return mp[*it];
    }};

/**
 * Your TimeMap object will be instantiated and called as such:
 * TimeMap* obj = new TimeMap();
 * obj->set(key,value,timestamp);
 * string param_2 = obj->get(key,timestamp);
 */

Issues:- the above solution got accepted but it is showing WA on the below test case.

**Missing test case:-**  
["TimeMap","set","set","get","set","get","get"] 
[[],["a","bar",1],["x","b",3],["b",3],["foo","bar2",4],["foo",4],["foo",5]]

**Comment by abhi5hekkk** [comment]
Link of the accepted solution:-
https://leetcode.com/submissions/detail/510983290/ 
![Screenshot (534)](https://user-images.githubusercontent.com/57363004/122854164-ea6f8480-d330-11eb-841e-2f5d2db0ca57.png)

**Comment by lc-kay** [comment]
Hi @abhi5hekkk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abhi5hekkk 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
