### ISSUE TITLE
Rename the function name of Rust verion - 191. Number of 1 Bits

### ISSUE THREAD

**Issue by tan-wei** [LeetCode-Feedback/LeetCode-Feedback#3915]
#### Your LeetCode username
Winterreise

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The code style of Rust use camel case name instead of snake case name, which is in consistence with other problems.

#### Language used for code
```rust
class Solution {
impl Solution {
    pub fn hammingWeight (n: u32) -> i32 {
        
    }
}
```

#### Expected behavior
```rust
class Solution {
impl Solution {
    pub fn hamming_weight (n: u32) -> i32 {
        
    }
}
```

**Comment by lc-kay** [comment]
Hi @tan-wei 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@tan-wei Our team has decided not to change it as the change will fail all previously submitted solutions. Thank you for your understanding.
