### ISSUE TITLE
Missing Test Case - 153. Find Minimum in Rotated Sorted Array

### ISSUE THREAD

**Issue by lokendrasinghnegi26** [LeetCode-Feedback/LeetCode-Feedback#3916]
Suppose an array of length n sorted in ascending order is rotated between 1 and n times. For example, the array nums = [0,1,2,4,5,6,7] might become:

// [4,5,6,7,0,1,2] if it was rotated 4 times. 
[0,1,2,4,5,6,7] if it was rotated 7 times.

in the commented line 4 times must be corrected as 3 times, then condition will match perfectly

**Comment by lc-kay** [comment]
@lokendrasinghnegi26 Please provide more details about this issue. Thank you.

**Comment by lc-kay** [comment]
Hi @lokendrasinghnegi26 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
