### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by urveshgodhani** [LeetCode-Feedback/LeetCode-Feedback#3917]
urveshgodhani

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
bug is for loop is not working properly .

#### Code you used for Submit/Run operation

 for(int i = 0 ; i < gas.size() ; i++)
    {
        tgas = tgas + gas[i];
        tcost = tcost + cost[i];
    }
    
    if(tgas < tcost)
        return -1;
    
    for(int j = 0 ; j < gas.size() ; j++)
    {
        if(gas[j] >= cost[j])       //this one
            return j;
    }
    return 0;

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

[5,1,2,3,4]
[4,4,1,5,1]

for this test case my code is right but last "for loop" is not working properly.

#### Screenshots

![image](https://user-images.githubusercontent.com/40348578/122917867-1f54f900-d37c-11eb-9f7b-c797618397d9.png)

**Comment by urveshgodhani** [comment]
int tgas = 0;
        int tcost = 0;
        
        for(int i = 0 ; i < gas.size() ; i++)
        {
            tgas = tgas + gas[i];
            tcost = tcost + cost[i];
        }
        
        if(tgas < tcost)
            return -1;
        
        for(int j = 0 ; j < gas.size() ; j++)
        {
            if(gas[j] >= cost[j])       //this one
                return j;
        }
        return 0;



if you run this code in leetcode there is one problem for testcase 
[5,1,2,3,4]
[4,4,1,5,1]


my code is right but this test case showing me wrong .

**Comment by lc-kay** [comment]
@urveshgodhani Please provide the submission details link. Thank you!

**Comment by lc-kay** [comment]
Hi @urveshgodhani 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
