### ISSUE TITLE
A test case is leading to TLE

### ISSUE THREAD

**Issue by aattarde** [LeetCode-Feedback/LeetCode-Feedback#392]
#### Your LeetCode username
aattarde

#### Category of the bug
- [ ] Question : 560. Subarray Sum Equals K
- [ ] Solution :  fix time limit for test case 81
- [ ] Language : C++

#### Description of the bug

A test case 81 is leading to time limit exceeded, where as exact same implementation in Java is being accepted just fine. please find attached screenshots for both submissions.

#### Code you used for Submit/Run operation

```
// C++ code :
class Solution {
public:
    int subarraySum(vector<int>& nums, int k) {
        vector<int> sum(nums.size()+1,0);
        // partial_sum(nums.begin(), nums.end(), sum.begin()+1);
        for(int i=1; i<= nums.size(); ++i){
            sum[i] = sum[i-1] + nums[i-1];
        }
        int ret=0;
        for(int i=0; i<sum.size()-1; ++i){
            for(int j=i+1; j<sum.size(); ++j){
                ret += (sum[j]-sum[i]) == k;
            }
        }
        return ret;  
    }
};

// Java Code:
public class Solution {
    public int subarraySum(int[] nums, int k) {
        int count = 0;
        int[] sum = new int[nums.length + 1];
        sum[0] = 0;
        for (int i = 1; i <= nums.length; i++)
            sum[i] = sum[i - 1] + nums[i - 1];
        for (int start = 0; start < nums.length; start++) {
            for (int end = start + 1; end <= nums.length; end++) {
                if (sum[end] - sum[start] == k)
                    count++;
            }
        }
        return count;
    }
}
```

#### Language used for code

C++

#### Expected behavior

Solution should be accepted in C++ language as many practice to code in one language than other, it can lead to misunderstanding about ones' solution. 

#### Screenshots

C++ submission: 
<img width="1672" alt="Screen Shot 2020-05-30 at 4 58 48 PM" src="https://user-images.githubusercontent.com/18670460/83341375-8f876d00-a297-11ea-8fad-e79d0d838d29.png">

Java Submission:
<img width="1671" alt="Screen Shot 2020-05-30 at 4 59 02 PM" src="https://user-images.githubusercontent.com/18670460/83341379-9615e480-a297-11ea-9505-5b62f73fe9b0.png">

**Comment by desdae** [comment]
Performance of the "same" operations in different languages can vary. O(1) time complexity does not mean instant.
For example, size() method of a vector in C++ is slower than just accessing a local variable. 
Thus, you can optimize the suboptimal O(n^2) C++ solution to get accepted without reducing the time complexity:
```
class Solution {
public:
    int subarraySum(vector<int>& nums, int k) {
        vector<int> sum(nums.size()+1,0);
        // partial_sum(nums.begin(), nums.end(), sum.begin()+1);
        for(int i=1; i<= nums.size(); ++i){
            sum[i] = sum[i-1] + nums[i-1];
        }
        int ret=0;
        int n = sum.size();        
        for(int i=0; i < n-1; ++i){
            for(int j=i+1; j < n; ++j){
                ret += (sum[j]-sum[i]) == k;
            }
        }
        return ret;  
    }
};
```

**Comment by aattarde** [comment]
@desdae - I understand that the solution is O(n^2) and can be improved , however point is if O(n^2) solution is acceptable in Java then it should be acceptable in C++ . Otherwise update the posted solution to reflect right information - informing that O(n^2) is not acceptable.

The point mentioned about vector<T>::size() being instant or not does not makes sense - instant or not - it is O(1) operation and pretty standard practice.
Same rational should be applicable for other problems otherwise this disparity qualifies for bug !

**Comment by CooperCooperCooper** [comment]
Hi @aattarde ,
Thank you for your time. Since the expected solution is linear and the given codes are quadratic solutions, even if in java the quadratic passes with tightly this behavior is expected. Therefore, please revise your code accordingly. We appreciate your support.
