### ISSUE TITLE
Missing Test Case - 40. Combination Sum II

### ISSUE THREAD

**Issue by SanjayIIITA** [LeetCode-Feedback/LeetCode-Feedback#3920]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

class Solution {
public:
void fun(int i, int target,vector<int>& cand,vector<vector<int >> &ans,vector<int> v)
{
    if(target <0) return;
        
            if(target == 0)
                ans.push_back(v);
     for(int j = i; j<cand.size(); j++)
     {
          if(j>i && cand[j]==cand[j-1])// condition check to avoid duplicates
                continue;
         if(target-cand[j]<0) 
             break;
         
            v.push_back(cand[j]);
            fun(j+1, target-cand[j], cand, ans, v);
            v.pop_back();
     }   
}
    vector<vector<int>> combinationSum2(vector<int>& candidates, int target) {
        
         vector<vector<int >> ans;
        vector<int> v;
        sort(candidates.begin(),candidates.end());
        fun(0, target, candidates, ans, v);
        return ans;
    }
};

**Comment by lc-kay** [comment]
@SanjayIIITA Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.

**Comment by SanjayIIITA** [comment]
All test cases is passed
