### ISSUE TITLE
Missing Test Case - 392. Is Subsequence

### ISSUE THREAD

**Issue by yo1995** [LeetCode-Feedback/LeetCode-Feedback#3922]
#### Your LeetCode username

yo1995

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A test case should be added to eliminate a wrong answer. My code get accepted (210622) but it is actually wrong.

```txt
"ab"
"baab"
```

#### Code you used for Submit/Run operation

```python3
# 392. Is Subsequence
class Solution:
    def isSubsequence(self, s: str, t: str) -> bool:
        if not s:
            return True
        pa = len(s)
        for pb in range(len(t), 0, -1):
            pa -= 1 if t[pb-1] == s[pa-1] else 0
        return True if not pa else False
```

#### Language used for code

Python3

#### Expected behavior

My answer should fail with the new testcase and thus get WA for the problem.

#### Screenshots

NA

#### Additional context

NA

**Comment by lc-kay** [comment]
Hi @yo1995 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yo1995 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
