### ISSUE TITLE
Rewording of problem, very confusing and superfluous wording

### ISSUE THREAD

**Issue by cliffordfajardo** [LeetCode-Feedback/LeetCode-Feedback#3927]
## Description of Bug/Issue

Rewording of fruit basket problem ([link](https://leetcode.com/problems/fruit-into-baskets/)). Below is the before and after. Happy to hear feedback. I felt the ordering and wording of certain statements in the original problem very confusing.

BEFORE (existing wording on the problem page ([link](https://leetcode.com/problems/fruit-into-baskets/))

```
In a row of trees, the i-th tree produces fruit with type tree[i].
You start at any tree of your choice, then repeatedly perform the following steps:
Add one piece of fruit from this tree to your baskets.  If you cannot, stop.
Move to the next tree to the right of the current tree.  If there is no tree to the right, stop.
Note that you do not have any choice after the initial choice of starting tree: you must perform step 1, then step 2, then back to step 1, then step 2, and so on until you stop.

You have two baskets, and each basket can carry any quantity of fruit, but you want each basket to only carry one type of fruit each.

What is the total amount of fruit you can collect with this procedure?
```

AFTER
```
In a row of trees, the i-th tree produces fruit with type tree[i].
You are given only two baskets to collect fruits, and your goal is to put maximum number of fruits
in each basket. 
- The only restriction is that each basket can have only one type of fruit.
- You can start with any tree, but you can’t skip a tree once you have started.
- You will pick one fruit from each tree until you cannot, i.e., you will stop when 
you have to pick from a third fruit type.

What is the total amount of fruit you can collect with this procedure?
```

#### Your LeetCode username
`dclif`

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases

**Comment by lc-kay** [comment]
Hi @cliffordfajardo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cliffordfajardo 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
