### ISSUE TITLE
Missing Test Case - 1172. Dinner Plate Stacks

### ISSUE THREAD

**Issue by mingcongzhang** [LeetCode-Feedback/LeetCode-Feedback#3928]
#### Your LeetCode username
alan-zhang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Test case https://leetcode.com/submissions/detail/511849355/testcase/ exceeds time limit on any answer to question https://leetcode.com/problems/dinner-plate-stacks/

#### Code you used for Submit/Run operation

```
class DinnerPlates {
    
    Map<Integer, Stack<Integer>> plates = new HashMap();
    int size, left, right, count;

    public DinnerPlates(int capacity) {
        size = capacity;
        left = right = count = 0;
        plates.put(0, new Stack());
    }
    
    public void push(int val) {
        plates.get(left).push(val);
        while (plates.containsKey(left) && plates.get(left).size() == size) {
            left++;
        }
        if (left > right) right = left;
        if (!plates.containsKey(left)) {
            plates.put(left, new Stack());
            right--;
        }
        count++;
    }
    
    public int pop() {
        if (count == 0) return -1;
        while (right > 0 && plates.get(right).size() == 0) {
            right--;
        }
        if (left > right) left = right;
        count--;
        return plates.get(right).pop();
    }
    
    public int popAtStack(int index) {
        if (count == 0) return -1;
        int result = -1;
        if (index <= right && plates.get(index).size() > 0) {
            result = plates.get(index).pop();
            if (left > index) left = index;
            count--;
        }
        return result;
    }
}

/**
 * Your DinnerPlates object will be instantiated and called as such:
 * DinnerPlates obj = new DinnerPlates(capacity);
 * obj.push(val);
 * int param_2 = obj.pop();
 * int param_3 = obj.popAtStack(index);
 */
```

#### Language used for code
JAVA

#### Expected behavior

Pass on all test cases

**Comment by lc-kay** [comment]
@mingcongzhang Your code is resulting in Time Limit Exceeded for possibly one of the following reasons:

1. Your code has an underlying infinite loop.
2. Your algorithm is too slow and has high time complexity.

This issue does not stem from our site. I'd recommend checking out accepted submissions from the discuss tab of the problem page, or posting your code there to get support from other users.

**Comment by mingcongzhang** [comment]
It passes all other test cases. I tried accepted code and they also fail on this specific case.

**Comment by lc-kay** [comment]
@mingcongzhang https://leetcode.com/problems/dinner-plate-stacks/discuss/1085340/Java-treeset-and-stack The code from this discuss post was accepted.
