### ISSUE TITLE
Missing Test Case - 233. Number of Digit One

### ISSUE THREAD

**Issue by raditya1710** [LeetCode-Feedback/LeetCode-Feedback#3929]
#### Your LeetCode username
alfonsus_raditya

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
When the test case is at the maximum possible input (`2000000000`), the answer overflows.

#### Code you used for Submit/Run operation

```
class Solution:
    def countDigitOne(self, n: int) -> int:
        n_str = str(n)
        multiplier = []
        multiplier.append(1)
        for i in range(1, 10):
            last_multiplier = multiplier[i - 1]
            curr_multiplier = last_multiplier * 10 + (10 ** i)
            multiplier.append(curr_multiplier)
            
        ans: int = 0
        len_n: int = len(n_str)
        for idx, ch in enumerate(n_str):
            cur_digit = int(ch)
            for j in range(cur_digit):
                if j == 1: 
                    ans += 10 ** (len_n - idx - 1)
                
                if len_n > idx + 1:
                    ans += multiplier[len_n - idx - 2]
            if cur_digit == 1:
                suff_str = n_str[idx+1:] or "0"
                ans += int(suff_str) + 1
            
        return ans
```

#### Language used for code

Python

#### Expected behavior

it not overflows (the correct answer is in 64-bit integer value or unsigned 32-bit value)

#### Screenshots

![Screenshot from 2021-06-23 12-24-50](https://user-images.githubusercontent.com/14028227/123040495-0866e300-d41e-11eb-8a45-79ed94b16553.png)

**Comment by lc-kay** [comment]
Hi @raditya1710 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @raditya1710 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
