### ISSUE TITLE
Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by punitkcse** [LeetCode-Feedback/LeetCode-Feedback#3934]
#### Your LeetCode username

LeetCode username : punitkcse

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

Question
Add this to the sample test cases 
Input = [9]
Output = [1,0]
#### Description of the bug

In no where in the question it was mentioned that we can increase the size of the array

#### Code you used for Submit/Run operation

``` def plusOne(self, digits):
    for i in range(len(digits)-1, -1, -1):
        digits[i] = digits[i] + 1 if digits[i] < 9 else 0
        if digits[i]: 
            return digits
    digits.insert(0, 1)
    return digits
```

#### Language used for code

Python 3.6

**Comment by lc-kay** [comment]
@punitkcse Please provide your submission details link.

**Comment by lc-kay** [comment]
Hi @punitkcse 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
