### ISSUE TITLE
Missing Test Case - 49. Group Anagrams

### ISSUE THREAD

**Issue by amrHassanAbdallah** [LeetCode-Feedback/LeetCode-Feedback#3936]
#### Your LeetCode username

3Mo0or

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The last test case fails because of missing inputs, even tho I tried the logic local and it seems legit

#### Code you used for Submit/Run operation

```
/**
 * @param {string[]} strs
 * @return {string[][]}
 */


function hashKey(str){
    let hash = 0
    let uniqChars = new Set()
    for (let i =0;i<str.length;i++){
        hash += str.charCodeAt(i)
        uniqChars.add(str[i])
        
    }
    
    return hash + Array.from(uniqChars).sort().join()
}
var groupAnagrams = function(strs) {
    let groupedAnagrams = {}
    for (let i=0;i<strs.length;i++){
        let word = strs[i]
        if (typeof groupedAnagrams[hashKey(word)] == "undefined"){
                groupedAnagrams[hashKey(word)] = [word]
            }else{
                groupedAnagrams[hashKey(word)].push(word)
            }
    }
    let result = []
    for (let key in groupedAnagrams){
        result.push(groupedAnagrams[key])
    }
    return result
};
```

#### Language used for code

Javascript

#### Expected behavior

the last test case to pass.

#### Screenshots

![Screenshot from 2021-06-23 14-35-52](https://user-images.githubusercontent.com/15635708/123097440-6f8d9300-d430-11eb-9814-4355ca4820e4.png)

**Comment by lc-kay** [comment]
@amrHassanAbdallah The expected output is correct. Please refer to the problem discuss section for further support. Thank you.
