### ISSUE TITLE
792. Number of Matching Subsequences

### ISSUE THREAD

**Issue by jraman** [LeetCode-Feedback/LeetCode-Feedback#3937]
Re: 792. Number of Matching Subsequences

In the problem definition/explanation, please add counter example(s) like so:

> For example, "ace" is a subsequence of "abcde".  And, "aec" is not a subsequence (not in the same order) and neither is "aac" ("abcde" has only one "a").

**Comment by lc-kay** [comment]
Hi @jraman 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jraman Our team has reviewed the problem description and concluded that the current version looks fine. And adding counterexample may confuse other people. Therefore, we will leave it as is. Thank you for your time.
