### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by m-saraya** [LeetCode-Feedback/LeetCode-Feedback#3938]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
 the code is accepted but did not want to be submiited  

#### Code you used for Submit/Run operation

"public class Solution 
{
    public int[] TwoSum(int[] nums, int target) 
    {
        List<int> result = new List<int>();
        int i = 0;
        int j = 1;
        while (i < nums.Length && j < nums.Length) 
        {
            if (nums[i] + nums[j] == target)
                {
                    result.Add(i);
                    result.Add(j);
                }
            i++;
            j++;
        }
        return result.ToArray();
    }
}"
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@m-saraya What is the issue you are trying to report?

**Comment by lc-kay** [comment]
Hi @m-saraya 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
