### ISSUE TITLE
Missing Test Case - 92. Reverse Linked List II

### ISSUE THREAD

**Issue by anvitburman** [LeetCode-Feedback/LeetCode-Feedback#3939]
#### Your LeetCode username
  anvit24

#### Category of the bug
- [1 ] Missing Test Cases 

#### Description of the bug

there has to be the test case where if left value is greater that right value then it returns NULL not to stop the program.

#### Code you used for Submit/Run operation

```
ListNode* reverseBetween(ListNode* head, int left, int right) {
if(left>right)return NULL;

         if(head->next==NULL || (left==right))return head;
        i
       
        ListNode *prev=NULL,*curr=NULL,*succ=NULL,*temp,*temp2;
        curr=head;
        int cnt=1;
        while(curr && cnt!=left)
        {
            
            prev=curr;
            curr=curr->next;
            cnt++;
        }
        
      
       
        temp=prev;
        temp2=curr;
        succ=curr->next;
        while(curr&&cnt!=right)
        {
            curr->next=prev;
            prev=curr;
            curr=succ;
            succ=succ->next;
            cnt++;
        }
        succ=curr->next;
        curr->next=prev;
        
        temp2->next=succ;
        if(temp!=NULL)
        temp->next=curr;
        else
            head=curr;
        
       

        return head;
    }
```

#### Expected behavior

it should return NULL value if left is greater than right

**Comment by lc-kay** [comment]
@anvitburman Please provide the missing test case. Thank you!

**Comment by lc-kay** [comment]
Hi @anvitburman 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
