### ISSUE TITLE
1465. Feedback on test cases

### ISSUE THREAD

**Issue by xu932** [LeetCode-Feedback/LeetCode-Feedback#394]
#### Your LeetCode username
xu932

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
One suggestion: please just do not use test case that will cause numeric overflow. Reasons:
1. It is unfair subject to languages. For example, c++ user might get runtime error due to overflow when they submit the problem without taking care of large value multiplied together where python user can just have the same logic and be successful without the time penalty. This test case really adds unfairness to programming languages.
2. There is no point of having to do all calculations in a larger type (int64_t for example) and convert the result back. I believe that is just a waste of typing.

I think it is better not have those corner cases that cause numerical overflow in the contests.

**Comment by CooperCooperCooper** [comment]
Hi @xu932 ,
Thank you for reaching out to us. I've relayed your feedback to our team to consider. We appreciate your time and support.

**Comment by CooperCooperCooper** [comment]
Hi @xu932 ,
Thank you for your time. We always try to make problems as simple as possible but sometimes we can't avoid using big integers, so on those test cases, we use modulo.
