### ISSUE TITLE
Two Sum different output

### ISSUE THREAD

**Issue by AksharGoyal** [LeetCode-Feedback/LeetCode-Feedback#3941]
#### Category of the bug
- [x] Question

#### Code you used for Submit/Run operation

```
int* twoSum(int* nums, int numsSize, int target, int* returnSize){
    
    returnSize = (int *)malloc( 2*sizeof(int));
    int first = 0, diff = 0;
    int begin, end, middle;
    bool found = false;
    for(int i = 0; i < numsSize / 2; i++)
    {
        first = nums[i];
        diff = target - first;
        begin = i + 1; end = numsSize - 1;
        while(begin < end)
        {
            middle = (begin + end)/2;
            
            if (nums[middle] == diff) {
                returnSize[0] = i;
                returnSize[1] = middle;
                found = true;
                break;
            }
            else if (nums[middle] < diff)
            {
                begin = middle + 1;
            }
            else
            {
                end = middle - 1;
            }
        }
        if (found) break;
    }
    return returnSize;
}
```

**Comment by lc-kay** [comment]
@AksharGoyal Please provide your submission details link. Thank you.

**Comment by AksharGoyal** [comment]
Hello, I hope this is the link: https://leetcode.com/problems/two-sum/submissions/

**Comment by lc-kay** [comment]
@AksharGoyal Please click on the status of the submission. It will then redirect you to the submission details link.

**Comment by AksharGoyal** [comment]
https://leetcode.com/submissions/detail/513037201/

**Comment by lc-kay** [comment]
@AksharGoyal Please refer to the problem discuss section for debugging your code. Your code was not accepted because the output did not match our expected output. Thank you for your time.

**Comment by AksharGoyal** [comment]
Hello, Please consider my problem. How come a ']' is returned when clearly I am returning a double variable?
![image](https://user-images.githubusercontent.com/38995624/123211962-c69f7080-d4e1-11eb-8346-a3deac31d435.png)
