### ISSUE TITLE
Bug in creating array

### ISSUE THREAD

**Issue by AksharGoyal** [LeetCode-Feedback/LeetCode-Feedback#3951]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
int lengthOfLongestSubstring(char * s){
    
    if(!s) return 0;
    
    int chs[256] = { -1 };
    printf("%d %d %d %d %d\n", chs[0], chs[50], chs[100], chs[200], chs[255]);
    int count = 0, index = 0;
    int n = strlen(s);
    int idx = 0;
    for(int i = 0; i < n; i++)
    {
        idx = s[i] - '\0';
        printf("Order, chs[idx] and Char are %d , %d and %c\n", idx, chs[idx], s[i]);
        if ((chs[idx] != -1) && (index <= chs[idx]))
        {
            index = chs[idx] + 1;
            printf("Order, Index and chsidx are %d , %d and %d\n", idx, index, chs[idx]);
        }
        else
        {
            count = (count < (i - index + 1)) ? (i - index + 1) : count;
            printf("i and index is %d and %d\n", i, index);
        }
        chs[idx] = i;
        printf("Count is now: %d\n", count);
    }
    return count;
}
```

**Comment by lc-kay** [comment]
@AksharGoyal Please provide more information about the bug and the problem title.

**Comment by AksharGoyal** [comment]
I think I have explained everything in my issue though I see my details are commented hence maybe they are not visible?

**Comment by lc-kay** [comment]
<img width="855" alt="Screen Shot 2021-06-25 at 12 10 24 PM" src="https://user-images.githubusercontent.com/70870126/123474098-53176500-d5ae-11eb-9e43-a85a2bb7d196.png">
Please refer to the screenshot to view what I see on my side. Thank you.

**Comment by AksharGoyal** [comment]
Ok, so the bug is that as per C syntax, initializing an array with one element means all the elements should be same. However, when I create my integer array, it seems only one element is my desired element while the others are 0 (or perhaps some other garbage value). The problem title is lengthOfLongestSubstring.

![image](https://user-images.githubusercontent.com/38995624/123276785-1e120080-d523-11eb-837c-31b675897183.png)

**Comment by lc-kay** [comment]
@AksharGoyal For this type of issue, please raise it in the problem discuss section. We are only able to provide support on issues that stem from our content. Thank you for your understanding.
