### ISSUE TITLE
Incorrect constraints and use of English - 576. Out of Boundary Paths

### ISSUE THREAD

**Issue by pr1metine** [LeetCode-Feedback/LeetCode-Feedback#3953]
#### Your LeetCode username

[pr1metine](https://leetcode.com/pr1metine/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

In [today's problem](https://leetcode.com/explore/challenge/card/june-leetcoding-challenge-2021/606/week-4-june-22nd-june-28th/3790/), two of the constraints (`0 <= startRow <= n` and `0 <= startColumn <= m`) are partially incorrect. That's because both `startRow` and `startColumn` include `n` and `m` respectively (also see #3943)

Besides, the problem description contains minor issues in terms of spelling and grammar. E. g. 

- "four adjacent **four** cells", 
- "**fesaible**"
- "store the number of paths and **updating** them after every move"
- "Also, there is only one possible way *[the]* ball can go out of boundary from *[a]* boundary cell **except** corner cells."

#### Code you used for Submit/Run operation

```cpp
class Solution {
    static constexpr int M = 1'000'000'007;
    int cache[50][50][51];
    int dfs(int m, int n, int maxMove, int y, int x) {
        if (y < 0 || y >= m) {return 1;}
        if (x < 0 || x >= n) {return 1;}
        if (maxMove == 0) {return 0; }
        
        if (cache[x][y][maxMove] != -1) {return cache[x][y][maxMove]; }
        
        unsigned int out = 0;
        out += dfs(m, n, maxMove - 1, y - 1, x);
        out += dfs(m, n, maxMove - 1, y, x - 1);
        out += dfs(m, n, maxMove - 1, y + 1, x);
        out += dfs(m, n, maxMove - 1, y, x + 1);
        return cache[x][y][maxMove] = (int) (out % M);
    }
public:
    int findPaths(int m, int n, int maxMove, int y, int x) {
        memset(cache, -1, sizeof(cache));
        return dfs(m, n, maxMove, y, x);
    }
};
```

Example input to reproduce this issue:

```
50
50
50
50
50
```

#### Language used for code

C++

#### Expected behavior

The aforementioned constraints should be replaced with the following constraints:

```
0 <= startRow < n
0 <= startColumn < m
```

The highlighted text passages may be corrected like this:

- "four adjacent cells"
- "feasible"
- "store the number of paths and update them after every move"
- "Also, there is only one possible way the ball can go out of boundary from a boundary cell excluding corner cells."

I would also recommend reading over this problem description again as I was unsure with a few other cases.

**Comment by lc-kay** [comment]
@pr1metine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by pr1metine** [comment]
Nice! Here's a great explanation #3955 by @masteranimax

**Comment by lc-kay** [comment]
Hi @pr1metine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
