### ISSUE TITLE
Missing Test Case - 576. Out of Boundary Paths

### ISSUE THREAD

**Issue by masteranimax** [LeetCode-Feedback/LeetCode-Feedback#3955]
#### Your LeetCode username

masteranimax

#### Category of the bug
- [*] Question 
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Constraints are mentioned as:
* 0 <= startRow <= m
* 0 <= startColumn <= n
But since we are using 0-based indexing
m,n are not valid indices.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Instead constraints should be
* 0 <= startRow < m
* 0 <= startColumn < n

**Comment by lc-kay** [comment]
@masteranimax This issue has been fixed from previous reports. Thank you for your time.
