### ISSUE TITLE
[576. Out of Boundary Paths] Typo in hint 1, fesaible instead of feasible

### ISSUE THREAD

**Issue by Mohammed-Shoaib** [LeetCode-Feedback/LeetCode-Feedback#3956]
#### Your LeetCode username
[MohammedShoaib](https://leetcode.com/MohammedShoaib/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hint 1 states the following:
> WIll traversing every path is **fesaible**? There are many possible paths for a small matrix. Try to optimize it.

#### Expected behavior
There is a typo in the spelling, it should be **feasible** but it says **fesaible**.

#### Screenshots
![LC typo](https://user-images.githubusercontent.com/32389312/123320463-1148d900-d532-11eb-80ca-cf1b551d74eb.png)

**Comment by lc-kay** [comment]
Hi @Mohammed-Shoaib 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
