### ISSUE TITLE
Missing Test Case - 868. Binary Gap

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3957]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
536870913

#### Code you used for Submit/Run operation

```
class Solution {
public:
	int binaryGap(int x){
		x>>=__builtin_ctz(x);
		if (x==1)return 0;
		int y=x,s=0; y|=y>>1; y|=y>>2; y|=y>>4; y|=y>>8; y|=y>>16;
		if (x==y)return 1;
		if ((x|x>>1)!=y)x|=x>>1,s+=1;else goto l3;
		if ((x|x>>2)!=y)x|=x>>2,s+=2;else goto l2;
		if ((x|x>>4)!=y)x|=x>>4,s+=4;else goto l1;
		if ((x|x>>8)!=y)x|=x>>8,s+=8;
		if ((x|x>>4)!=y)x|=x>>4,s+=4;
		l1:if ((x|x>>2)!=y)x|=x>>2,s+=2;
		l2:if ((x|x>>1)!=y)x|=x>>1,s+=1;
		l3:return s+2;
	}
};
```

#### Language used for code

C++

#### Expected behavior

Expected: 29
Output: 24

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
