### ISSUE TITLE
linguistic errors in first hint of 576. Out of Boundary Paths

### ISSUE THREAD

**Issue by hamirmahal** [LeetCode-Feedback/LeetCode-Feedback#3958]
#### Your LeetCode username

hamirmahal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The first hint has errors.

#### Expected behavior

The first hint would say something like, "Is traversing every path feasible? There are many possible paths for a small matrix. Try to optimize it."

Instead, it has at least one grammatical error: "WIll traversing every path is feasible? There are many possible paths for a small matrix. Try to optimize it."

There's also a capital "I" immediately after the first letter of the first hint's first sentence.

#### Screenshots

![Screen Shot 2021-06-24 at 4 00 27 PM](https://user-images.githubusercontent.com/43425812/123342810-4d197980-d505-11eb-990a-6fd7f6b4200e.png)

**Comment by lc-kay** [comment]
Hi @hamirmahal 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
