### ISSUE TITLE
Missing Test Case - 138. Copy List with Random Pointer

### ISSUE THREAD

**Issue by KNaka88** [LeetCode-Feedback/LeetCode-Feedback#3959]
#### Your LeetCode username
kojinaka19

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The submitted code should pass with the test case
```
[[7,null],[13,0],[11,4],[10,2],[1,0]]
```

but instead, it throws at internal code (solution.js)
```
Line 94 in solution.js
            node = node.next;
                        ^
TypeError: Cannot read property 'next' of undefined
    Line 94: Char 25 in solution.js (Object.serializer.isCyclic)
    Line 120: Char 24 in solution.js (Object.serializer.serializeLinkedList)
    Line 176: Char 30 in solution.js (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 39: Char 26 in solution.js (Object.<anonymous>)
    Line 1251: Char 30 in loader.js (Module._compile)
    Line 1272: Char 10 in loader.js (Object.Module._extensions..js)
    Line 1100: Char 32 in loader.js (Module.load)
    Line 962: Char 14 in loader.js (Function.Module._load)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

#### Code you used for Submit/Run operation

```
var copyRandomList = function(head) {
    if (!head) {
        return head;
    }
    
    const oldToCopy = new Map();    
    let cur = head;
    while (cur) {
        let copy = new Node(cur.val);
        oldToCopy.set(cur, copy);
        cur = cur.next;        
    }
    
    cur = head;    
    while (cur) {
        let copy = oldToCopy.get(cur);
        copy.next = oldToCopy.get(cur.next);                
        copy.random = oldToCopy.get(cur.random);    
        cur = cur.next;        
    }
    
    return oldToCopy.get(head);   
};
```

#### Language used for code
Javascript

#### Expected behavior
Runtime error should not happen

#### Additional context
If I created a testing case by myself and called copyRandomList in Chrome console tab, it worked without errors.
I believe there is a bug in solution.js or some internal code

**Comment by lc-kay** [comment]
@KNaka88 I was able to find many accepted Javascript solutions in the discuss section, including https://leetcode.com/problems/copy-list-with-random-pointer/discuss/543309/JavaScript-Solution-90 and https://leetcode.com/problems/copy-list-with-random-pointer/discuss/950584/O(N)-JavaScript-Solution Please check them out. Unfortunately, we are unable to tell the difference in behavior between the LeetCode environment and another environment. Thank you for your understanding.
