### ISSUE TITLE
第191周周赛数据太弱

### ISSUE THREAD

**Issue by 0xac001d09** [LeetCode-Feedback/LeetCode-Feedback#396]
[题解](https://leetcode-cn.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/solution/javayong-setshi-xian-de-by-bei-ao-ao-yi-kou-chi-di/), 该写法能过但以下测试用例是过不去的
-----------------
3
[[1,2],[2,0]]
6
[[2,3],[3,1],[1,0],[4,0],[4,5]]
3
[[2,1],[0,2]]

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
fixed
