### ISSUE TITLE
Change "or" to "and" in description 740. Delete and Earn

### ISSUE THREAD

**Issue by YuvrajJoshi** [LeetCode-Feedback/LeetCode-Feedback#3961]
#### Your LeetCode username
Yuvraj_Joshi

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem description states that "you must delete every element equal to ```nums[i] - 1 or nums[i] + 1``` " , which leads us to believe that we have to delete either of them. But the examples and solutions consist of deleting both ```nums[i] - 1 and nums[i] + 1``` ,  which contradicts the problem statement. 

#### Expected behavior
The ```or``` is expected to be changed to ```and``` .

**Comment by lc-kay** [comment]
@YuvrajJoshi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @YuvrajJoshi 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
