### ISSUE TITLE
Missing test case 1136. Parallel Courses

### ISSUE THREAD

**Issue by cfchou** [LeetCode-Feedback/LeetCode-Feedback#3962]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Problem https://leetcode.com/problems/parallel-courses/

dead link to the testcase
https://leetcode.com/submissions/detail/512968628/testcase

#### Code you used for Submit/Run operation

```

```

#### Language used for code

Python

**Comment by lc-kay** [comment]
@cfchou What is the issue you are trying to report?

**Comment by lc-kay** [comment]
Hi @cfchou 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
