### ISSUE TITLE
Problem 716 Max Stack Solution 1 is Wrong

### ISSUE THREAD

**Issue by ziangzhang10** [LeetCode-Feedback/LeetCode-Feedback#3964]
#### Category of the bug
- [ ] Solution

#### Original code given by the solution

```
class MaxStack(list):
    def push(self, x):
        m = max(x, self[-1][1] if self else None)
        self.append((x, m))

    def pop(self):
        return list.pop(self)[0]

    def top(self):
        return self[-1][0]

    def peekMax(self):
        return self[-1][1]

    def popMax(self):
        m = self[-1][1]
        b = []
        while self[-1][0] != m:
            b.append(self.pop())

        self.pop()
        map(self.push, reversed(b))
        return m
```

#### Expected behavior

If we do:
["push","push","popMax","peekMax"]
[[5],[1],[],[]]

the code will return:
[null,null, 5,5]

while logically, it should return
[null,null, 5,1]

since 5 is now gone after popMax, and 1 is now the max number

#### Screenshots

There are other users pointing out this issue as well
![image](https://user-images.githubusercontent.com/44552618/123472593-f7a0a380-d5bc-11eb-85a4-c6988d4e7fd6.png)

**Comment by lc-kay** [comment]
@ziangzhang10 Please note that the solution provided is in Python, not Python3. However, our team will review this article and make necessary improvements. Thank you for your time.
<img width="1006" alt="Screen Shot 2021-06-29 at 10 56 05 AM" src="https://user-images.githubusercontent.com/70870126/123845070-9af8fd80-d8c8-11eb-9054-50d01a3d487d.png">
