### ISSUE TITLE
Missing Test Case - 801. Minimum Swaps To Make Sequences Increasing

### ISSUE THREAD

**Issue by saketkumar1** [LeetCode-Feedback/LeetCode-Feedback#3965]
#### Your LeetCode username

saketkumar8385

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

the console should show invalid test case 
but it show wrong answer 
my code accepted but by manually putting test case it fails in some of it

[9,3,5,4]
[1,2,3,7]

[1,3,5,4]
[1,2,10,7]

#### Code you used for Submit/Run operation

```
class Solution {
    public int minSwap(int[] nums1, int[] nums2) {
        
        int[][] strg = new int[2][nums2.length];
        Arrays.fill(strg[0], -1);
        Arrays.fill(strg[1], -1);
        strg[0][0] = 0;
        strg[1][0] = 1;
        
        return Math.min(minswap(nums1,nums2,nums1.length-1,0,strg),
                       minswap(nums1,nums2,nums1.length-1,1,strg));
        
    }
    
    
    public int minswap(int[] nums1,int[] nums2,int vidx,int swap,int[][] strg){
        
         if(vidx==0){
	            return swap;
	        }
	        
        if(strg[swap][vidx]!=-1){
            return strg[swap][vidx];
        }
	        
	      
	        int d=Integer.MAX_VALUE;

	        if(nums1[vidx]>nums1[vidx-1]&&nums2[vidx]>nums2[vidx-1]){     
	                 d=minswap(nums1,nums2,vidx-1,swap,strg);           
	        }
	        
	        
	        if(nums1[vidx]>nums2[vidx-1]&&nums2[vidx]>nums1[vidx-1]){
	            
	                 d=Math.min(d,minswap(nums1,nums2,vidx-1,1-swap,strg));
	                 
	        }
        
        return strg[swap][vidx]=swap==0?d:d+1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Invalid input

#### Screenshots

![image](https://user-images.githubusercontent.com/66872047/123502715-13af4e00-d66c-11eb-8746-82bb81a17b4d.png)

**Comment by lc-kay** [comment]
Hi @saketkumar1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @saketkumar1 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
