### ISSUE TITLE
Contradictory statement - 684. Redundant Connection

### ISSUE THREAD

**Issue by bhas-tech** [LeetCode-Feedback/LeetCode-Feedback#3966]
#### Your LeetCode username
dream-google

#### Category of the bug
- [ 684. Redundant Connection] Question
- [ ] Solution
- [ ] Language
- [ ] Contradictory Statement

#### Description of the bug
Its not a but report, but just fond contradictory statement in the question itself. its given that  there are **" n nodes labeled from 1 to n, with one additional edge added"**, so there can be one additional node only right ? The contradictory statement is : **If there are multiple answers, return the answer that occurs last in the input.**, since its given in definition that we can have only one extra node than there is no point of this statement which says : **If there are multiple answers, return the answer that occurs last in the input.** . Please correct this stamenet if suggestion seems fesible to you guys. Thanks.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @bhas-tech 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@bhas-tech The problem description is correct as is. The input is not a tree. The newly added edge was added to the tree to convert it to a graph and then the input became a graph, so no, there are no additional nodes. Thank you for your time.
