### ISSUE TITLE
478. Generate Random Point in a Circle

### ISSUE THREAD

**Issue by mallika-b** [LeetCode-Feedback/LeetCode-Feedback#3967]
#### Your LeetCode username
mallikab

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typo in Approach 1:

(2R) ^2 =4R and the area of the circle is \pi R \approx 3.14RπR≈3.14R

All those R's after the first one need a 'square' too!

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @mallika-b 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @mallika-b 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
