### ISSUE TITLE
Missing Space between elements - 1. Two Sum

### ISSUE THREAD

**Issue by KaushikPathak90** [LeetCode-Feedback/LeetCode-Feedback#3968]
#### Your LeetCode username

KaushikPathak

#### Category of the bug
- [ ] Language

#### Description of the bug

In Python, how come output of list is [0,1] instead of [0, 1]. Please note the blank space.
I just learned about the class typing. Output in my IDE is [0, 1]. And somehow both Expected and Output is [0,1]. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        dic = {}
        for i in range(len(nums)):
            if (target - nums[i]) in dic:
                return [dic[(target - nums[i])], i]
            else:
                dic[nums[i]] = i
```

#### Language used for code

Python3

#### Expected behavior

Expected and Output should be [0, 1].

**Comment by lc-kay** [comment]
@KaushikPathak90 We are unable to differentiate the different behaviors from your code and your  IDE. Please raise this question in the problem discuss section for further support. Thank you.
