### ISSUE TITLE
Incorrect Expected Result for Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by pmhwong** [LeetCode-Feedback/LeetCode-Feedback#3971]
#### Your LeetCode username
pmhwong@gmail.com

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Incorrect Test Case

#### Description of the bug

Test Case Input:  [1,1,2]
Expected Result:  [1,2] <-- this is wrong
Correct Expected Result:  [1,2,2]
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@pmhwong The expected output is correct. Please check out the explanation for example 1 or raise your question in the problem discuss section for further clarifications. Thank you for your time.
