### ISSUE TITLE
Missing Test Case - 1126. Active Businesses

### ISSUE THREAD

**Issue by l0latgithub** [LeetCode-Feedback/LeetCode-Feedback#3974]
#### Category of the bug
- [ ] Language

#### Description of the bug

"An active business is a business that has more than one event type with occurences greater than the average occurences of that event type among all businesses."

Does "all business" mean all the businesses in the database? Currently all the test cases could be passed by counting all the businesses having this event type/

#### Code you used for Submit/Run operation

```
###The following is accepted solution, it would calculate average occurences among the company having this event
### code 1
select b.business_id
from events as b
join(
    select event_type, avg(occurences) as avgcnt
    from events
    group by event_type
) e using (event_type)
group by b.business_id
having sum(b.occurences>e.avgcnt)>1

### The following would calculate average occurences among all the company in the database. It was rejected by the test case below
### code 2
select b.business_id
from events as b
join(
    select event_type, sum(occurences)/(select count(distinct business_id) from events) as avgcnt
    from events
    group by event_type
) e using (event_type)
group by b.business_id
having sum(b.occurences>e.avgcnt)>1


```

#### Expected behavior

Test case 
1,"reviews",3
3,"reviews",3
1,"ads",11
2,"ads",7
3,"ads",11
1,"page views",3
2,"page views",12
3,"page views",10

code 1 outuput 
"event_type", "business_id", "occurences", "avgcnt"
"reviews", 1, 3, 3.0000
"reviews", 3, 3, 3.0000
"ads", 1, 11, 9.6667
"ads", 2, 7, 9.6667
"ads", 3, 11, 9.6667
"page views", 1, 3, 8.3333
"page views", 2, 12, 8.3333
"page views", 3, 10, 8.3333

code 2 output
"event_type", "business_id", "occurences", "avgcnt"
"reviews", 1, 3, 2.0000
"reviews", 3, 3, 2.0000
"ads", 1, 11, 9.6667
"ads", 2, 7, 9.6667
"ads", 3, 11, 9.6667
"page views", 1, 3, 8.3333
"page views", 2, 12, 8.3333
"page views", 3, 10, 8.3333

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
