### ISSUE TITLE
Not Handling Test Cases Correctly - 135. Candy

### ISSUE THREAD

**Issue by AlexMason** [LeetCode-Feedback/LeetCode-Feedback#3976]
#### Your LeetCode username
AlexMason93

#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution interpreter is not properly counting the number of candies to give out.  Assuming this test case `[1,0,3,3,3,2,1,2,3,1,2,1,0]` we start with 13 candies be default, then manually counting following the rules we end up with 8 additional candies for a total of 21.  The interpreter says this solution comes up with 24.

#### Code you used for Submit/Run operation
```
/**
 * @param {number[]} ratings
 * @return {number}
 */
var candy = function(ratings) {
    function getNeighbors(idx) {
        if (idx === 0) return [undefined, ratings[idx+1]];
        if (idx === ratings.length) return [ratings[idx-1], undefined];
        return [ratings[idx-1], ratings[idx+1]]
    }
    
    return ratings.map((r, idx) => {
        let candies = 1;
        let neighbors = getNeighbors(idx)
        
        if (r > neighbors[0] && !isNaN(neighbors[0])) {
            candies += 1
        } else if (r > neighbors[1] && !isNaN(neighbors[1])) {
            candies += 1;
        }
        
        return candies;
    }).reduce((a,c) => a+c, 0)
};
```

#### Language used for code
JavaScript

#### Expected behavior
Expected to return 21 candies, got 24 candies instead.

#### Screenshots
![image](https://user-images.githubusercontent.com/740625/123559467-29a33880-d76a-11eb-8f2d-eb31c7fc20e2.png)

#### Additional context
N/A

**Comment by lc-kay** [comment]
@AlexMason The expected output is correct. Please refer to the problem discuss section for further support. Thank you for your time.
