### ISSUE TITLE
Incorrect Expected Answer for Test Case in Problem 135. Candy

### ISSUE THREAD

**Issue by joshinsel** [LeetCode-Feedback/LeetCode-Feedback#3979]
#### Your LeetCode username
joshinsel

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Incorrect Expected Result for Test Case

#### Description of the bug
This occurs during the following submission test case:
[29,51,87,87,72,12]
The expected answer is 12, which is incorrect. It should be 16, which the answer my code produces. The fifth rating, 72, is greater than the following rating of 12, so the child in the fifth place should receive more candies than the one in fourth place. However, the expected answer seems to be based on the assumption that the fifth child only receives one candy. 

#### Code you used for Submit/Run operation

```
class Solution:
        
    def candy(self, ratings: List[int]) -> int:
        length = len(ratings)
        if length > 1:
            minCandy = length
            candyNumList = []
            additionalCandy = 0
            for child in range(length):
                candyNumList.append(0)
                if child > 0 and child < length - 1:
                    if ratings[child-1] < ratings[child] or ratings[child+1] < ratings[child]:
                        candyNumList[child] = candyNumList[child-1] + 1
                elif child == 0:
                    if ratings[child+1] < ratings[child]:
                        candyNumList[child] = 1
                elif child == length - 1:
                    if ratings[child-1] < ratings[child]:
                        candyNumList[child] = candyNumList[child-1] + 1
                additionalCandy += candyNumList[child]
                #print("The number of candies received by child #" + str(child+1) + ": " + str(candyNumList[child] + 1))
            totalCandy = minCandy + additionalCandy
            return totalCandy
```

#### Language used for code

Python3

#### Expected behavior

The expected answer for the test case should be 16.

#### Screenshots

![Screenshot 2021-06-27 at 23-45-20 Explore - LeetCode](https://user-images.githubusercontent.com/16366560/123592732-799df180-d7a2-11eb-9d30-abcab0f6a10f.png)

![Screenshot 2021-06-27 at 23-49-18 Explore - LeetCode](https://user-images.githubusercontent.com/16366560/123592750-7e62a580-d7a2-11eb-95fa-96f3ba89300e.png)

**Comment by lc-kay** [comment]
@joshinsel The expected output is correct. Please refer to the problem discuss section for further support. Thank you for your time.
