### ISSUE TITLE
Invalid Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by tushar19892002** [LeetCode-Feedback/LeetCode-Feedback#3980]
https://leetcode.com/problems/find-the-duplicate-number
#### Category of the bug
- [ ] Invalid Test Cases 

#### Description of the bug

Question clearly says - "There is only one repeated number in nums"
Hence following is an invalid test case-
[2,2,2,2,2]

**Comment by SurasithO** [comment]
I believe that this test case is valid since [2,2,2,2,2] has exactly one repeated number. Under **Constraints**, it states that "All the integers in `nums` appear only **once** except for **precisely one integer** which appears **two or more** times."

**Comment by tushar19892002** [comment]
Got it. Thanks for the clarification.

**Comment by lc-kay** [comment]
@tushar19892002 I'm happy to see that your question was answered by @SurasithO. Have a great day!
