### ISSUE TITLE
Missing Test Case - 122. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by abhi9vsh** [LeetCode-Feedback/LeetCode-Feedback#3982]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@abhi9vsh Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
