### ISSUE TITLE
Missing Test Case - 384. Shuffle an Array

### ISSUE THREAD

**Issue by ManaswitaDatta** [LeetCode-Feedback/LeetCode-Feedback#3983]
#### Your LeetCode username:
 juicy1

#### Category of the bug: 
Question

#### Description of the bug: 
The question is misleading. The description does not say "Here shuffle means that every permutation of array element should equally likely". But the test cases expect that.

#### Code you used for Submit/Run operation
//384. Shuffle an Array
```
class Solution {
    private Random random;
    int[] nums;
    public Solution(int[] nums) {
        this.nums = nums.clone();
        random = new Random();
    }
    
    /** Resets the array to its original configuration and return it. */
    public int[] reset() {
        return nums;
    }
    
    /** Returns a random shuffling of the array. */
    public int[] shuffle() {
        int[] a = nums.clone();
        for (int i = a.length - 1; i > 0; i--) {
            int j = random.nextInt(i+1);
            swap(a, i, j);
        }
        return a;
    }
    private void swap(int[] a, int i, int j) {
        int t = a[i];
        a[i] = a[j];
        a[j] = t;
    }
}
``` 

#### Language used for code: 
Java

#### Expected behavior: 
I gave you the correct solution that passes all the test cases. But if the probability is not equally likely, the test case would fail. Check the discussion tab of the question for more.

**Comment by lc-kay** [comment]
Hi @ManaswitaDatta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ManaswitaDatta 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
