### ISSUE TITLE
Missing Test Case - 54. Spiral Matrix 

### ISSUE THREAD

**Issue by yes-58** [LeetCode-Feedback/LeetCode-Feedback#3985]
#### Your LeetCode username
Yash_Sethiya

#### Category of the bug
Missing Test Cases

#### Description of the bug
A missing test case, which gives wrong answer on accepted solutions.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> spiralOrder(vector<vector<int>>& matrix) {
        vector<int>v;
        int m=matrix.size();
        int n=matrix[0].size();
        int sr=0,er=m-1,sc=0,ec=n-1;
        while(sr<=er && sc<=ec)
        {
            
            for(int i=sc;i<=ec;i++)
            {
                v.push_back(matrix[sr][i]);
            }
            sr++;
            for(int i=sr;i<=er;i++)
            {
                v.push_back(matrix[i][ec]);
            }
            ec--;
            
            if(er>sr || m==2)
            {
                for(int i=ec;i>=sc;i--)
                {
                    v.push_back(matrix[er][i]);
                }
                er--;
            }
            if(ec>sc || n==2)
            {
                for(int i=er;i>=sr;i--)
                {
                    v.push_back(matrix[i][sc]);
                }
                sc++;
            }
        }
        return v;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

For given input ,I expected that my accepted solution should give correct answer but it gives wrong answer for that input.

#### Screenshots
![image](https://user-images.githubusercontent.com/82904045/123621764-3044b500-d829-11eb-95ba-3a752a5dad4b.png)
![image](https://user-images.githubusercontent.com/82904045/123621978-59fddc00-d829-11eb-8289-214ce73518f3.png)

#### Additional context
[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6725420/input.txt)

**Comment by lc-kay** [comment]
Hi @yes-58 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by yes-58** [comment]
I hope leetcode will resolve this issue as quickly as possible.

**Comment by lc-kay** [comment]
Hi @yes-58 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
