### ISSUE TITLE
Missing Test Case - 1047. Remove All Adjacent Duplicates In String

### ISSUE THREAD

**Issue by jasvir340** [LeetCode-Feedback/LeetCode-Feedback#3986]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@jasvir340 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
