### ISSUE TITLE
Missing Test Case - 1047. Remove All Adjacent Duplicates In String

### ISSUE THREAD

**Issue by namannigam** [LeetCode-Feedback/LeetCode-Feedback#3987]
#### Your LeetCode username
namannigam

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A test case clarifying the removal of only the **two** adjacent and not all equal characters adjacent to each other.

#### Code you used for Submit/Run operation

```
  public String removeDuplicates(String str) {
      StringBuilder sb = new StringBuilder();
      for (char c : str.toCharArray()) {
          int size = sb.length();
          if (size > 0 && sb.charAt(size - 1) == c) {
              sb.deleteCharAt(size - 1);
          } else {
              sb.append(c);
          }
      }
      return sb.toString();
  }
```
Test Case:
```
Assertions.assertEquals("mnonp", removeDuplicates("mnooooonp")); // and not "mp"
```

#### Language used for code
Java

#### Expected behavior
The additional test case shall highlight the removal of only the count that is multiple of two adjacent characters if found equal in the string.

#### Screenshots
Custom test case execution:
<img width="913" alt="customtestcase" src="https://user-images.githubusercontent.com/76494006/123674026-c515d580-d85e-11eb-8ec7-82def6f1ceae.png">

#### Additional context
This would make the problem much clear to approach the solution expected.

**Comment by lc-kay** [comment]
Hi @namannigam 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@namannigam Our team has reviewed your test case and decided not to add it. We have many similar test cases to this and adding it won't fail any solution. Thank you for your time.
