### ISSUE TITLE
Additional Test Case for 116

### ISSUE THREAD

**Issue by deepanshululla** [LeetCode-Feedback/LeetCode-Feedback#399]
#### Your LeetCode username
deepanshu6

#### Category of the bug
- [ ] Question/Test-case

#### Description of the bug
Is the expected output of your testcases different from our judger's output?

Yes 
Were wrong solutions accepted because we missed these testcases?

Yes

#### Code you used for Submit/Run operation

```
def connect_siblings_iterative(root):
    level_start = root
    while level_start:
        curr = level_start
        while curr:
            if curr.left:
                curr.left.next = curr.right
            if curr.right and curr.next:
                curr.right.next = curr.next.left
            curr = curr.next

        level_start = level_start.left

    return root
```

#### Language used for code
Python

#### Expected behavior
```
root1 = TreeNode(12)
root1.left = TreeNode(7)
root1.right = TreeNode(1)
root1.left.left = TreeNode(9)
root1.right.left = TreeNode(10)
root1.right.right = TreeNode(5)
out1 = [12, '#', 7, 1, '#', 9, 10, 5, '#']
```
The output of connect_siblings_iterative(root1) should be equal to out1
but is equal to [12, '#', 7, 1, '#', 9, '#'] 

The code, however, passes as an acceptable solution.

**Comment by CooperCooperCooper** [comment]
Hi @deepanshululla ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @deepanshululla ,
Thank you for your time. We tested your code in multiple ways (including changing the code definitions), but all of those runs got Runtime Error. Can you please share a viable submission link from when you got the code accepted, and provide more information to support your feedback, so we can take a better look at the issue?

**Comment by deepanshululla** [comment]
Sure here it is
https://leetcode.com/submissions/detail/347426208/

**Comment by CooperCooperCooper** [comment]
Thank you @deepanshululla . I've filed the link to our team for the investigation.

**Comment by CooperCooperCooper** [comment]
Hi @deepanshululla ,
Thank you for your time. Can you please share the test case you would like us to add to this problem?

**Comment by deepanshululla** [comment]
This one
```
root1 = TreeNode(12)
root1.left = TreeNode(7)
root1.right = TreeNode(1)
root1.left.left = TreeNode(9)
root1.right.left = TreeNode(10)
root1.right.right = TreeNode(5)
out1 = [12, '#', 7, 1, '#', 9, 10, 5, '#']
```

**Comment by CooperCooperCooper** [comment]
Hi @deepanshululla ,
Thank you! I've relayed this test case to our team to take a deeper look.

**Comment by CooperCooperCooper** [comment]
Hi @deepanshululla ,
Thank you for your time. The information you've shared with us was the instruction to build the test case, but not the test case itself. Since it has 6 nodes, it's not a perfect binary tree. We appreciate your support.
