### ISSUE TITLE
Missing Test Case - 877. Stone Game

### ISSUE THREAD

**Issue by imroshan12** [LeetCode-Feedback/LeetCode-Feedback#3991]
#### Your LeetCode username
imroshan12

#### Category of the bug
Missing Test Cases 

#### Description of the bug
It always returns true, which means Alex always wins and that is not possible. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    bool stoneGame(vector<int>& piles) {
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior

When I submit this code, I expect that it should not be marked as correct. **There must be some hidden test cases which also return false**.

#### Additional context

Some test cases may be like-
`piles = [4, 7, 4, 4]`
It returns false;

**Comment by lc-kay** [comment]
@imroshan12 Please check out this discuss post along with many others for clarification. https://leetcode.com/problems/stone-game/discuss/154607/Alex-won't-lose Thank you for your time.
