### ISSUE TITLE
Missing Test Case - 1913. Maximum Product Difference Between Two Pairs

### ISSUE THREAD

**Issue by durgesh-4526** [LeetCode-Feedback/LeetCode-Feedback#3993]
#### Your LeetCode username

durgeshsahu7

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

If there will be less than 4 indices in the array so we will not get the proper output
The same number will be multiplied 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
```
if (nums.size() < 4)
        {
            return 0;
        }
        sort(nums.begin(),nums.end());
        int first = nums[0]*nums[1];
        int second = nums[nums.size()-1]*nums[nums.size()-2];
        return second-first;
 ```
    }
};
```

#### Language used for code

C++

#### Expected behavior

If the array will contain less than 4 indices so return 0 or NULL
Add the test case Such as:-
[4,5,6]
[1,2]
[2]
[7,6,3]

**Comment by lc-kay** [comment]
@durgesh-4526 Please provide the submission details link. Thank you.

**Comment by durgesh-4526** [comment]
> @durgesh-4526 Please provide the submission details link. Thank you.

https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/3993#issuecomment-870809602

**Comment by durgesh-4526** [comment]
> @durgesh-4526 Please provide the submission details link. Thank you.

https://leetcode.com/problems/maximum-product-difference-between-two-pairs/discuss/1303995/C++-code

**Comment by lc-kay** [comment]
@durgesh-4526 Per the constraints, "4 <= nums.length <= 104", your custom test cases are invalid. Thank you for your time.
