### ISSUE TITLE
Code doesnt get reflected when you move from description tab to solution tab

### ISSUE THREAD

**Issue by ptoshniasu** [LeetCode-Feedback/LeetCode-Feedback#3996]
#### Category of the bug
-Technical bug 

#### Description of the bug
When you go to the problem's description
Write some code in the code window
then go to the solution tab
then your code window doesn't consist of the code written in step 2.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@ptoshniasu Please report this technical issue to our help center (leetcode.com/support). In your ticket, please include a screen recording of the issue. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
