### ISSUE TITLE
Missing Test Case - 1004. Max Consecutive Ones III

### ISSUE THREAD

**Issue by luckyvin** [LeetCode-Feedback/LeetCode-Feedback#3999]
#### Your LeetCode username

luckydr

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing Test Case for 1004. Max Consecutive Ones III:
```
[1,1,1,1,1]
0
```

#### Language used for code

JavaScript

**Comment by lc-kay** [comment]
@luckyvin Please provide the accepted code that this test case will fail. Thank you.

**Comment by lc-kay** [comment]
Hi @luckyvin 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
