### ISSUE TITLE
Duplicate questions 476 and 1009

### ISSUE THREAD

**Issue by CooperCooperCooper** [LeetCode-Feedback/LeetCode-Feedback#4]
problem 476: https://leetcode.com/problems/number-complement/

problem 1009: https://leetcode.com/problems/complement-of-base-10-integer/

discussion thread that says 1009 and 476 are the same: https://leetcode.com/problems/complement-of-base-10-integer/discuss/?currentPage=1&orderBy=most_relevant&query=same

**Comment by CooperCooperCooper** [comment]
Problem descriptions now have notes about them being duplicates.

**Comment by escrowdis** [comment]
Hi, just curious why don't just keep one and make the other one invisible? So that the discussion on this problem can be found in one place rather two. Thanks!
