### ISSUE TITLE
Leetcode Solution  - 143. Reorder List

### ISSUE THREAD

**Issue by rstudy211** [LeetCode-Feedback/LeetCode-Feedback#4000]
#### Your LeetCode username

rstudy211
link :- https://leetcode.com/problems/reorder-list/discuss/1304841/99-accuracy-Python3

#### Category of the bug
- [ Reorder List ] Question
- [ ] Solution
- [ python] Language
- [ ] Missing Test Cases 

#### Description of the bug

# Approach :-
		1. Find mid point using slow and fast pointer.
		2. Break list from mid point reverse second half .
		3. Update the links between fist and  reversed half of the list.
#### Code you used for Submit/Run operation

```
class Solution:
    def reorderList(self, head: ListNode) -> None:
        """
        Do not return anything, modify head in-place instead.
        """
        if head == None:return head
        fa,sl = head,head
        while fa and fa.next:
            sl,fa = sl.next,fa.next.next
        mid = sl
        pre,cur = None,mid
        while cur:
            cur.next,pre,cur  = pre,cur,cur.next
        
        fh,sh = head,pre
        while sh.next:
            h = fh.next
            fh.next = sh
            fh = h
            
            h = sh.next
            sh.next = fh
            sh = h
        
```

#### Language used for code

Python3

#### Screenshots

![image](https://user-images.githubusercontent.com/62322747/123800580-124d8200-d907-11eb-82a0-aafb4190bafc.png)

**Comment by lc-kay** [comment]
@rstudy211 Please post solutions to the problem discuss section for others to view. This Github repo is for reporting content-related issues. Thank you for your time.

**Comment by rstudy211** [comment]
So if where i have to upload solutions on github.
