### ISSUE TITLE
Error in Language - 44. Wildcard Matching

### ISSUE THREAD

**Issue by junhuih** [LeetCode-Feedback/LeetCode-Feedback#4001]
#### Your LeetCode username

junhuih

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the following statement:

_If the pattern character is '*' and there was a match on the previous step D[p_idx - 1][s_idx - 1] = True, then
  The star at the end of pattern still results in a match.
  The star could **much** as many characters as you wish._

Highlighted **much** should be match

#### Screenshots

<img width="638" alt="lc44" src="https://user-images.githubusercontent.com/37812261/123826091-0a570780-d932-11eb-86f3-d792830acb06.PNG">

**Comment by lc-kay** [comment]
Hi @junhuih 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @junhuih 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
