### ISSUE TITLE
Missing Test Case - 139. Word Break

### ISSUE THREAD

**Issue by VictorLin851129** [LeetCode-Feedback/LeetCode-Feedback#4003]
#### Your LeetCode username

hengjunlin1129

#### Category of the bug
 Missing Test Cases 

#### Description of the bug

The following code can pass all the test cases. 
After I saw the discussion, I noticed that my logic is wrong.
Therefore, I create a test case that can prove my code is wrong.
"carscabcars"
["ca","rs", "rscab"]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean wordBreak(String s, List<String> wordDict) {
        Boolean[][] dp = new Boolean[wordDict.size() + 1][wordDict.size() + 1];
        return DynamicProgramming(0, s, wordDict, dp);
    }

	private static boolean DynamicProgramming(int from, String s, List<String> wordDict, Boolean[][] dp) {
		if(s.length() == 0) {
			return true;
		}
		
		for(int i = 0; i < wordDict.size(); i++) {
			if(s.startsWith(wordDict.get(i)) && dp[from][i + 1] == null) {
				if(DynamicProgramming(i + 1, s.replaceFirst(wordDict.get(i), ""), wordDict, dp)) {
					return true;
				}else {
					dp[from][i + 1] = false;
				}
			}
		}
		return false;
	}
}
```

#### Language used for code

JAVA

#### Expected behavior

My code was wrong but it pass all test cases.
The test case I create could prove I'm wrong.
"carscabcars"
["ca","rs", "rscab"]

#### Additional context

Hope Leetcode can add this test case, or it might mislead other people who think their answer is correct!

**Comment by lc-kay** [comment]
Hi @VictorLin851129 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @VictorLin851129 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
