### ISSUE TITLE
Missing Test Case - 1004. Max Consecutive Ones III

### ISSUE THREAD

**Issue by thomas-neder** [LeetCode-Feedback/LeetCode-Feedback#4004]
#### Your LeetCode username

user3823k

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

A solution got accepted but failed a simple allowed manual test case.

#### Code you used for Submit/Run operation

```
class Solution:
    def longestOnes(self, nums, k):
        slow, fast = 0,0
        zeros = int(nums[0]==0)
        max_l = 1-int(nums[0]==0)
        while fast<len(nums)-1:
            if zeros<k:
                fast += 1
                zeros += int(nums[fast]==0)
                max_l = max(max_l,fast-slow+1)
            elif zeros==k:
                if nums[fast+1]==1:
                    fast+=1
                    max_l = max(max_l,fast-slow+1)
                else:
                    zeros -= int(nums[slow]==0)
                    slow += 1
            else:
                zeros -= int(nums[slow]==0)
                slow += 1
            if fast<slow:
                fast = slow
                zeros += int(nums[fast]==0)
        return max_l
```

#### Language used for code
Python

#### Expected behavior
The solution should have failed when submitted if this test case had been included.

#### Screenshots
![Screenshot from 2021-06-30 01-13-06](https://user-images.githubusercontent.com/86693147/123879022-7b9db700-d940-11eb-8d57-1fb3d078b8d4.png)

**Comment by lc-kay** [comment]
Hi @thomas-neder 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @thomas-neder 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
