### ISSUE TITLE
690. Employee Importance - bug in Typescript

### ISSUE THREAD

**Issue by Swoodend** [LeetCode-Feedback/LeetCode-Feedback#4005]
For problem 690  the function is defined incorrectly. It looks like the test runner is expecting the function to be defined in PascalCase, but when typescript is the language of choice the function is defined in camelCase.

![image](https://user-images.githubusercontent.com/12000404/123881001-ca802800-d911-11eb-914c-88d84a24b01b.png)

**Comment by lc-kay** [comment]
Hi @Swoodend 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Swoodend 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Swoodend** [comment]
@lc-kay thank you very much! My LeetCode ID is Swoodend. Cheers!
