### ISSUE TITLE
Test Case bug in 1528. Shuffle String

### ISSUE THREAD

**Issue by Psypriest** [LeetCode-Feedback/LeetCode-Feedback#4006]
#### Your LeetCode username
psypriest

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a bug in this question and test case for this question. 

#### Code you used for Submit/Run operation
``` 
class Solution:
    def restoreString(self, s: str, indices: List[int]) -> str:
        rs = ''
        for i in indices:
            rs += s[i]
        return rs
 ```

#### Language used for code
Python 3

#### Expected behavior
Expected to pass the test case. 

#### Screenshots
![image](https://user-images.githubusercontent.com/21305115/123906409-21055a80-d942-11eb-9859-776db4f88647.png)

#### Additional context
None. 
Link to the question https://leetcode.com/submissions/detail/515222669/

**Comment by lc-kay** [comment]
@Psypriest The expected output is correct. Please check out the explanation in example one. Thank you for your time.
