### ISSUE TITLE
297. Serialize and Deserialize Binary Tree : Need tests cases in  in order to invalidate naive solution

### ISSUE THREAD

**Issue by XRFXLP** [LeetCode-Feedback/LeetCode-Feedback#4007]
#### Your LeetCode username
XRFXLP

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation
```python
# Definition for a binary tree node.
# class TreeNode(object):
#     def __init__(self, x):
#         self.val = x
#         self.left = None
#         self.right = None

class Codec:

    def serialize(self, root):
        """Encodes a tree to a single string.
        
        :type root: TreeNode
        :rtype: str
        """
        return root

    def deserialize(self, data):
        """Decodes your encoded data to tree.
        
        :type data: str
        :rtype: TreeNode
        """
        return data
        

# Your Codec object will be instantiated and called as such:
# ser = Codec()
# deser = Codec()
# ans = deser.deserialize(ser.serialize(root))
```

#### Language used for code
Python 3.9

#### Expected behaviour
I don't think this solution should pass the test, otherwise what would be the point of the task? There should be test cases which invalidates such approach, if possible.

**Comment by lc-kay** [comment]
@XRFXLP Please provide a test case that will fail this solution. Thank you!

**Comment by azabluda** [comment]
The following cheat passes all tests in C#
```cs
public class Codec
{
    static TreeNode cheat;

    // Encodes a tree to a single string.
    public string serialize(TreeNode root) => $"{cheat = root}";

    // Decodes your encoded data to tree.
    public TreeNode deserialize(string data) => cheat;
}
```

**Comment by lc-kay** [comment]
Hi @XRFXLP @azabluda 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@azabluda Our team is aware of this. We don't want to let them pass but at the low level, it is hard to make them fail, so we gently ask the users to submit a working solution.
If a user wants to cheat, it is ok since this is a practice problem (not a contest problem).
