### ISSUE TITLE
wrong test case answer - 125. Valid Palindrome

### ISSUE THREAD

**Issue by codeanshul13** [LeetCode-Feedback/LeetCode-Feedback#4008]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

![Screenshot (86)](https://user-images.githubusercontent.com/64330243/123926904-f8b14680-d9a9-11eb-89ea-b43ce8bbc74e.png)

**Comment by lc-kay** [comment]
Hi @codeanshul13 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
