### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by SMohanaRao** [LeetCode-Feedback/LeetCode-Feedback#4009]
#### Your LeetCode username
MohanaRao

#### Category of the bug

- [ ] Missing Test Cases

#### Description of the bug

I think for nums.length = 0, my code should not be accepted.
But getting accepted.

#### Code you used for Submit/Run operation

```
class Solution {
    public int removeDuplicates(int[] nums) {
        int k = 1;
        for(int i = 1; i < nums.length; i++) {
            if (nums[i] > nums[k-1])
                nums[k++] = nums[i];
        }
        System.out.println(k);
        return k;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Given constraints are:    0 <= nums.length <= 3 * 104
For nums.length = 0, I guess k should be returned as 0.
My code is returning 1 in this case.
I think in this case below assertion should fail
assert k == expectedNums.length;
But my code is getting accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/65847725/123983682-b0157f80-d9e1-11eb-9e5b-aa1f11243f74.png)

**Comment by lc-kay** [comment]
Hi @SMohanaRao 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@SMohanaRao The java driver is designed so that if the array is of length n and the user returned an integer > n, the driver only prints the first n elements. This should not be a problem for this code. Thank you for your time.
