### ISSUE TITLE
1325. Delete Leaves With a Given Value - Incomplete constraints description or Missing test case

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#401]
#### Your LeetCode username

roll_no_1

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The constraint no. 2 states: "Each tree has at most 3000 nodes.", which roughly translates to the statement that the tree can have anywhere between 0 and 3000 nodes. 

So, the following should be a valid input: 
```
[]
1
```
This input is an empty tree. However, I am getting an invalid input error on entering this input. 
There are 2 alternatives solution for this bug: 

1. Allow the above input to be a valid one, in which case the solution code I have given below should get a Runtime error since it fails on the above case.

2. Change the constraints description. So, constraint no. 2 should be changed to "The number of nodes in the tree is between 1 and 3000." 

Looking at the fact that the new LC problems tend not to have an empty tree input generally, my suggestion is to go with alternative 2.

#### Code you used for Submit/Run operation

```
class Solution {
    
    int x;
    
    TreeNode* dfs(TreeNode* root) {
        
        if(root -> left) root -> left = dfs(root -> left);
        if(root -> right) root -> right = dfs(root -> right);
        
        if(!root -> left && !root -> right && root -> val == x) return NULL;
        return root;
    }
    
public:
    TreeNode* removeLeafNodes(TreeNode* root, int target) {
        x = target;
        return dfs(root);
    }
};
```

#### Language used for code

C++

#### Expected behavior

With reference to points 1 and 2 in the description above, either the following input should be valid:
```
[]
1
```

or 

The problem constraint description for constraint no. 2 should be changed to "The number of nodes in the tree is between 1 and 3000."

#### Screenshots

* ![image](https://user-images.githubusercontent.com/36921843/83407818-1f135400-a42f-11ea-9fb9-fbe70f202b94.png)

* ![image](https://user-images.githubusercontent.com/36921843/83407875-3c482280-a42f-11ea-98ab-6f2bc797db89.png)

* ![image](https://user-images.githubusercontent.com/36921843/83407926-5da90e80-a42f-11ea-8760-3142dfdcf509.png)

* ![image](https://user-images.githubusercontent.com/36921843/83408274-ffc8f680-a42f-11ea-8694-5169e9b676e7.png)

#### Additional context

N/A

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
