### ISSUE TITLE
JS support - 226. Invert Binary Tree

### ISSUE THREAD

**Issue by GoorLavi** [LeetCode-Feedback/LeetCode-Feedback#4010]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I have tried to solve the Invert Binary Tree problem in JS but I think I have encountered with OOP language errors 

#### Code you used for Submit/Run operation

```
const invertTree = root => {

    if (!root.length)
        return [];

    let invertedArray = [root.shift()];
    let parents = 2;

    while (root.length) {
        const items = root.splice(0, parents);
        invertedArray = [...invertedArray, ...items.reverse()];
        parents += 2;
    }

    return invertedArray;
};
```

#### Screenshots
![image](https://user-images.githubusercontent.com/22860912/124018471-8dd72e00-d9f0-11eb-8051-a3959738a09f.png)

Thank you in advance!

**Comment by lc-kay** [comment]
@GoorLavi For code support, please refer to the problem discuss section. I was also able to find many accepted JS codes there, https://leetcode.com/problems/invert-binary-tree/discuss/?currentPage=1&orderBy=most_relevant&query=javascript, please check it out. Thank you for your time.
