### ISSUE TITLE
Missing Test Case - 1299. Replace Elements with Greatest Element on Right Side

### ISSUE THREAD

**Issue by abhishek07456-CSE** [LeetCode-Feedback/LeetCode-Feedback#4011]
input : [17,18,5,4,6,1]
expected output :  [ 18 , -1 , 6 , 6 ,-1 , -1]
leetcode expected output ; [ 18 , 6 , 6 , 6 ,1 ,-1] // here 18 have no right maximum so it should be -1

**Comment by lc-kay** [comment]
@abhishek07456-CSE Please check out the example 1 explanation: Input: arr = [17,18,5,4,6,1]
Output: [18,6,6,6,1,-1]
Explanation: 
- index 0 --> the greatest element to the right of index 0 is index 1 (18).
- index 1 --> the greatest element to the right of index 1 is index 4 (6).
- index 2 --> the greatest element to the right of index 2 is index 4 (6).
- index 3 --> the greatest element to the right of index 3 is index 4 (6).
- index 4 --> the greatest element to the right of index 4 is index 5 (1).
- index 5 --> there are no elements to the right of index 5, so we put -1.

**Comment by abhishek07456-CSE** [comment]
ok it got it
