### ISSUE TITLE
Missing Test Case - 212. Word Search II

### ISSUE THREAD

**Issue by jainans** [LeetCode-Feedback/LeetCode-Feedback#4012]
#### Category of the bug
   Missing Test Cases 

#### Description of the bug
   I just wrote my dfs backtracking code and successfully submitted it . After the successful submission i tried a test case of my own. which is -
                         [["a","b","e"],["b","c","d"]]
                        ["abcdeb"]
as we can see we we can traverse a->b->c->d->e->b but my code (which is successfully submitting) output for this test-case is false. 
   So, do consider to add this test-case in your problem. 
 Thanks.

#### Code you used for Submit/Run operation

```
// word search 2
class Solution {
public:
    int dx[4] = {-1, 0, 1, 0};
    int dy[4] = {0, 1, 0, -1};
    int dp[12][12][11];
    int dfs(int st, int x, int y, string word, vector<vector<char>>& board, vector<vector<int> >& vis){
         if(st==word.size())
             return dp[x][y][st]= 1;
        if(dp[x][y][st]!=-1)
            return dp[x][y][st];
        vis[x][y] = 1;
        for(int i=0; i<4; i++){
            int cx = x+dx[i];
            int cy = y+dy[i];
            if(cx>=0 && cx<board.size() && cy>=0 && cy<board[0].size()){
                if(vis[cx][cy]==0 && board[cx][cy]==word[st] && dfs(st+1, cx, cy, word, board, vis)){
                    return dp[x][y][st]= true;
                }
                    
            }
        }
        vis[x][y]=0;
        return dp[x][y][st]= false;
        
    }
    vector<string> findWords(vector<vector<char>>& board, vector<string>& words) {
        vector<string>ans;
        
        int n = board.size();
        int m  = board[0].size();
        vector<vector<int> >vis(n, vector<int>(m, 0));
        for(int i=0; i<words.size(); i++){
           for(int a=0; a<12; a++){
               for(int b=0; b<12; b++){
                   for(int c=0; c<11; c++){
                       dp[a][b][c]= -1;
                   }
               }
           }
            for(int j=0; j<n; j++){
                
                for(int k=0; k<m; k++){
                   
                    if(board[j][k]==words[i][0]){
                        for(int p=0; p<n; p++){
                            for(int q=0; q<m; q++)
                                vis[p][q]=0;
                        }
                        int bb = dfs(1, j, k, words[i], board, vis);
                        
                        if(bb==1){
                            ans.push_back(words[i]);
                           
                        }
                        
                    }
                   
                }
               
            }
        }
        set<string>vans;
        for(int i=0; i<ans.size(); i++){
            vans.insert(ans[i]);
        }
        ans.clear();
        for(auto it : vans){
            ans.push_back(it);
        }
        return ans;
    }
};
```

#### Language used for code
   C++ 

#### Expected behavior
      For the test case -
             [["a","b","e"],["b","c","d"]]
                        ["abcdeb"]
      The answer was expected to be true as we can traverse from a down to b to cdeb but I got false output from my code which was successfully accepted by the leetcode.
            

#### Screenshots
![image](https://user-images.githubusercontent.com/72242262/124054996-bb4bc800-da40-11eb-93ba-2c756b19665c.png)

**Comment by lc-kay** [comment]
Hi @jainans 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jainans 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
