### ISSUE TITLE
Missing Test Cases 909. Snakes and Ladders

### ISSUE THREAD

**Issue by Rajan-226** [LeetCode-Feedback/LeetCode-Feedback#4013]
#### LeetCode username
Raja_n

#### Category of the bug
Missing Test Cases 

#### Description of the bug
I got accepted verdict for my solution, but it is giving wrong answer for a tricky input which I created myself to test my code.

#### Code used for Submit/Run operation

```
class Solution {
public:
    int snakesAndLadders(vector<vector<int>>& board) {
        int n=board.size();
        vector<pair<int,int>> mp(n*n+1);
        reverse(board.begin(),board.end());
        for(int i=0,num=1;i<n;i++){
            if(i%2==0)
                for(int j=0;j<n;j++,num++)
                    mp[num]={i,j};
            else
                for(int j=n-1;j>=0;j--,num++)
                    mp[num]={i,j};
        }
        queue<int> q;
        vector<bool> vis(n*n+1);
        q.push(1);
        vis[1]=1;
        int ans=1;
        while(!q.empty()){
            int sz=q.size();
            while(sz--){
                int now=q.front();
                q.pop();
                auto [cx,cy]=mp[now];
                for(int j=1;j<=6&&now+j<=n*n;j++){
                    if(vis[now+j]) continue;
                    if(now+j==n*n) return ans;
                    vis[now+j]=1;
                    auto [nx,ny]=mp[now+j];
                    if(board[nx][ny]==-1) q.push(now+j);
                    else if(!vis[board[nx][ny]]){
                        if(board[nx][ny]==n*n) return ans;
                        q.push(board[nx][ny]);
                    }
                }
            }
            ans++;
        }
        return -1;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
For the below testcase, output should be 3 and my code is giving -1 as answer.
[[-1,1,1,1],[-1,7,1,1],[16,1,1,1],[-1,1,9,1]]

![image](https://user-images.githubusercontent.com/56467449/124070726-ea236780-da5b-11eb-9994-5e64b5a00380.png)

**Comment by lc-kay** [comment]
Hi @Rajan-226 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Rajan-226 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
