### ISSUE TITLE
Submission problem - Reverse Integer problem

### ISSUE THREAD

**Issue by AndrewAKovalenko** [LeetCode-Feedback/LeetCode-Feedback#4014]
#### Your LeetCode username
AndriiKovalenko

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
After submitting my answer, one of the tests expects me to return 0 instead of a reverted integer, which fails my submission

#### Code you used for Submit/Run operation

```
function reverse(x: number): number {
    return (x < 0 ? -1 : 1) * parseInt(Math.abs(x).toString().split('').reverse().join(''));
};
```

#### Language used for code
Typescript

#### Expected behavior
Tests that expects 0 should expect reversed integer

#### Screenshots

![image](https://user-images.githubusercontent.com/34687666/124075645-d7099b00-da4d-11eb-8bf3-4f9637b3c432.png)

**Comment by lc-kay** [comment]
@AndrewAKovalenko 
The expected output is correct. Please check out the following discuss posts https://leetcode.com/problems/reverse-integer/discuss/656300/failed-for-1534236469 https://leetcode.com/problems/reverse-integer/discuss/265907/1534236469-test-case

Thank you for your time.
