### ISSUE TITLE
Typo in solution of 89. Gray Code

### ISSUE THREAD

**Issue by EaseTheWorld** [LeetCode-Feedback/LeetCode-Feedback#4016]
#### Your LeetCode username
EaseTheWorld

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I found some typos in Approach 5's proof 2(uniqueness) part.

b^(n−2) ⊕ b^(n−2)=0  should be
b^(n−2) ⊕ b^(n−1)=0

b^(n−3) ⊕ b^(n−4)=0  should be
b^(n−3) ⊕ b^(n−2)=0

**Comment by lc-kay** [comment]
Hi @EaseTheWorld 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @EaseTheWorld 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
