### ISSUE TITLE
Valid sequence for n=3 does not pass test - 89. Gray Code

### ISSUE THREAD

**Issue by TheTypingType** [LeetCode-Feedback/LeetCode-Feedback#4018]
#### Your LeetCode username
thetypingtype

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The following gray code for n=3 is valid but receives the "Wrong Answer" verdict:
[0,1,3,7,6,2,5,4]

#### Code you used for Submit/Run operation
```
// Gray Code
class Solution:
    def grayCode(self, n: int) -> List[int]:
       # hard-coded to highlight the bug at n=3
       if n == 1:
            return [0, 1]
        if n == 2:
            return [0, 1, 3, 2]
        if n == 3:
            return [0,1,3,7,6,2,5,4]
```

#### Language used for code
Python3

#### Expected behavior
Test case for n = 3 should be passed by the sequence [0,1,3,7,6,2,5,4]. 
In binary, this is [000, 001, 011, 111, 110, 010, 110, 100]. Since at each step only one bit changes, this is a valid gray code.
The code above should only be invalid for n > 4, but it already receives the Wrong Answer verdict for n = 3.

#### Screenshots

![gray_code_n_is_3](https://user-images.githubusercontent.com/20403759/124127574-2d8dce00-da7c-11eb-8cce-9bae959406c3.png)

**Comment by lc-kay** [comment]
Hi @TheTypingType 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @TheTypingType 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
