### ISSUE TITLE
Missing Test Case - 89. Gray Code

### ISSUE THREAD

**Issue by duttabhishek0** [LeetCode-Feedback/LeetCode-Feedback#4019]
#### Your LeetCode username
 xenikh_32

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
One of the test cases fails for the question Gray Code. It is n =3. As mentioned, there are multiple solutions possible. The below sequence is a Gray Code, but the verdict is "Wrong Answer".

#### Code you used for Submit/Run operation
```
class Solution {
public:
    vector<int> grayCode(int n) {
     
        if(n==2){
            return vector<int> {0,1,3,2};
        }
        else if(n==3){
            return vector<int> {0,1,3,7,6,2,5,4};
        }
        return vector<int> {0,1};
        //Ignoring all other test case for the case n = 3
    }
};

```

#### Language used for code
 C++ 

#### Expected behaviour
Test case for n = 3 should out the following sequence
[0,1,3,7,6,2,5,4]. 
Other sequences are accepted, like [0,1,3,2,6,7,5,4] for n = 3.

#### Screenshots

![Screenshot from 2021-07-01 19-06-20](https://user-images.githubusercontent.com/56694152/124133684-b4a06d80-da9f-11eb-9282-d65f2a299660.png)

**Comment by lc-kay** [comment]
Hi @duttabhishek0 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @duttabhishek0 
Thank you for your time. We've updated the problem. We appreciate your support!
