### ISSUE TITLE
1373. Maximum Sum BST in Binary Tree - Missing test case

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#402]
#### Your LeetCode username

roll_no_1

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The code I submitted got accepted. However, it should throw a Runtime Error on the following test case: 
```
[]
```

The test case corresponds to an empty tree, and is a valid input.

#### Code you used for Submit/Run operation

```
class Solution {
    const int inf = 1e9;
    int res;
    
    //Returns {sum, min, max}
    vector<int> dfs(TreeNode* root) {
        vector<int> ans = {root -> val, root -> val, root -> val};
        bool ok = 1;
        
        if(root -> left) {
            auto lans = dfs(root -> left);
            if(lans[2] < root -> val) {
                ans[0] += lans[0];
                ans[1] = lans[1];
            }
            else ok = 0;
        }
        
        if(root -> right) {
            auto rans = dfs(root -> right);
            if(rans[1] > root -> val) {
                ans[0] += rans[0];
                ans[2] = rans[2];
            }
            else ok = 0;
        }
        
        if(!ok) return {0, -inf, inf};
        
        res = max(res, ans[0]);
        return ans;
    }
    
public:
    int maxSumBST(TreeNode* root) {
        res = 0;
        dfs(root);
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code should get a runtime error on the input of an empty tree:
```
[]
```
This indicates that the test case is missing.

#### Screenshots

* ![image](https://user-images.githubusercontent.com/36921843/83409128-6b5f9380-a431-11ea-9e10-4e94f1da75e8.png)
* ![image](https://user-images.githubusercontent.com/36921843/83409553-415aa100-a432-11ea-8d45-547b0c268739.png)
* ![image](https://user-images.githubusercontent.com/36921843/83409589-56cfcb00-a432-11ea-9fcb-bd0f645ddd59.png)
* ![image](https://user-images.githubusercontent.com/36921843/83409662-78c94d80-a432-11ea-886b-61db47e7feec.png)

#### Additional context

N/A

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
