### ISSUE TITLE
Test case missing for the problem #5 "Longest Palindromic Substring" 

### ISSUE THREAD

**Issue by Bappy4u** [LeetCode-Feedback/LeetCode-Feedback#4021]
#### Your LeetCode username

bappy4u

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Question
5. Longest Plaindromic Substring
#### One of the missing test cases
"aaaaaaaaaaaaaabaaaaaaaaaaaaa"

#### Description of the bug
I write a program for the question 5 "Longest Palindromic Substring". I manage to made the solution accepted for the given test cases. But I found there will be error for some special test cases.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def longestPalindrome(self, s):
        max = 0
        fs = ''
        for i in range(len(s)):
            ts = ''
            if max > 4:
                it = max - 4
            else:
                it = 0
            for j in range(i+it, len(s)):
                ts += (s[j:j+1])
                if ts==ts[::-1]:  
                    if max<len(ts):
                        fs = ts 
                        max = len(ts)
                    
        return fs
            
```

#### Language used for code

Python

#### Expected behavior

I realize after submitting code. This code should get error for some test cases. But the question accepted for their given test cases. Unfortunately my code doesn't return expected value for some test cases. As a example of input "aaaaaaaaaaaaaabaaaaaaaaaaaaa"

#### Screenshots

![image](https://user-images.githubusercontent.com/26277680/124202640-9cab0700-dafc-11eb-9336-e1bde5eecdf3.png)
 
 Note: But the same code got accepted.

**Comment by lc-kay** [comment]
Hi @Bappy4u 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Bappy4u 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
