### ISSUE TITLE
Confusing question statement

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#4022]
#### Your LeetCode username

MohitKumar6122

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the  question [#387](https://leetcode.com/problems/first-unique-character-in-a-string/) statement it is written as 
```
return the first non-repeating character in it and return its index.
```
instead this should be written as 
```
find the first non-repeating character in it and return its index.
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int firstUniqChar(string s) {
        vector<pair<int, int>> freq(26, pair<int, int > (0, 0)) ;
        for(int i = 0 ; i < s.size(); ++i){
            freq[s[i] - 'a'].first++ ;
            freq[s[i] - 'a'].second = i ;
        }
        int ans = INT_MAX ;
        for(int i = 0; i < 26; ++i){
            if (freq[i].first == 1) ans = min(ans , freq[i].second) ;
        }
        return ans == INT_MAX ? -1 : ans  ; 
    }
};
```

#### Language used for code
C++

**Comment by lc-kay** [comment]
Hi @Mohitkumar6122 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Mohitkumar6122** [comment]
Welcome @lc-kay for addressing this issue. 
I think we can close this issue now.
