### ISSUE TITLE
Missing Test Case - 1172. Dinner Plate Stacks

### ISSUE THREAD

**Issue by zouxingyu** [LeetCode-Feedback/LeetCode-Feedback#4023]
#### Your LeetCode username

baby_zxy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The current testcases allow a wrong solution to get Accepted.  Try input like 

["DinnerPlates","push","push","push","push","push","pop","pop","pop","pop","push","push","pop"]
[[2],[1],[2],[3],[4],[5],[],[],[],[],[2],[3],[]]

#### Code you used for Submit/Run operation

```
class DinnerPlates:

    def __init__(self, capacity: int):
        self.left = []
        self.cap = capacity
        self.stacks = []
        self.right_most = -1
        
    def push(self, val: int) -> None:
        # print('before push')
        # print(self.stacks, self.left)
        while self.left:
            idx = heappop(self.left)
            if len(self.stacks[idx]) < self.cap:
                self.stacks[idx].append(val)
                heappush(self.left, idx)
                break
        else:
            self.right_most = len(self.stacks)
            heappush(self.left, len(self.stacks))
            self.stacks.append([])
            self.stacks[-1].append(val)
        
    def pop(self) -> int:
        # print('before pop')
        # print(self.stacks)
        while self.right_most >= 0:
            if self.stacks[self.right_most]:
                return self.stacks[self.right_most].pop()
            self.right_most -= 1
        return -1

    def popAtStack(self, index: int) -> int:
        # print('before popat')
        # print(self.stacks)
        ret = -1
        if index < len(self.stacks) and self.stacks[index]:
            if len(self.stacks[index])== self.cap:
                heappush(self.left, index)
            ret = self.stacks[index].pop()
        return ret
```

#### Language used for code

Python

#### Expected behavior

The above describe solution is obviously incorrect, so it is expected to get a Wrong Answer verdict after submitting it, but it does get accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/31210147/124216515-122ccc80-db29-11eb-8f7c-4d365d4d9a48.png)

**Comment by lc-kay** [comment]
Hi @zouxingyu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @zouxingyu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
