### ISSUE TITLE
Missing Test Case - 201. Bitwise AND of Numbers Range

### ISSUE THREAD

**Issue by nischay193** [LeetCode-Feedback/LeetCode-Feedback#4027]
#### Your LeetCode username

nischay193

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Solution fails on this particular test, among many others. But the same solution is accepted when submitted.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int rangeBitwiseAnd(int m, int n) {
        if(n-m>=100)
            return 0;
                long int i;
        long int result=m;
        for(i=m;i<=n;i++)
            result&=i;
        return result;
    }
};
```

#### Language used for code
C++

#### Test case
256
511

#### Expected behavior

Expected correct output for the above test case is 256

#### Screenshots

![image](https://user-images.githubusercontent.com/61834075/124243123-17931280-db3b-11eb-9665-d29d287106e6.png)
![image](https://user-images.githubusercontent.com/61834075/124243264-4c06ce80-db3b-11eb-80d6-b70e3b3d6312.png)

**Comment by lc-kay** [comment]
Hi @nischay193 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @nischay193 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
