### ISSUE TITLE
Missing Test Case - 658. Find K Closest Elements

### ISSUE THREAD

**Issue by Siddharth868** [LeetCode-Feedback/LeetCode-Feedback#4028]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Siddharth868 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
