### ISSUE TITLE
Missing Test Case - 658. Find K Closest Elements

### ISSUE THREAD

**Issue by Faisalimtiyaz** [LeetCode-Feedback/LeetCode-Feedback#4029]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Faisalimtiyaz Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
