### ISSUE TITLE
1460. Make Two Arrays Equal by Reversing Sub-arrays

### ISSUE THREAD

**Issue by TrickyCat** [LeetCode-Feedback/LeetCode-Feedback#403]
#### Your LeetCode username
TrickyCat

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
There are several solutions that were accepted and rated as the fastest two solutions in C# language but they are wrong.

#### Code you used for Submit/Run operation

```csharp
// Two Sum
public class Solution {
    public bool CanBeEqual(int[] target, int[] arr) {
        var xor = 0;
        for(int i = 0; i < arr.Length; i++)
        {
            xor ^= target[i] ^ arr[i];
        }        
        return xor == 0;  
    }
}
```

#### Language used for code
C#

#### Expected behavior
For  the given input arrays
[5, 5]
[6, 6]
the code is expected to return FALSE according to the task description. But the accepted code returns TRUE.

#### Screenshots

![image](https://user-images.githubusercontent.com/855874/83436901-69083400-a447-11ea-982f-a6d2fce15790.png)

**Comment by CooperCooperCooper** [comment]
Hi @TrickyCat ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @TrickyCat ,
Thank you for your time. Upon reviewing this issue, we found that this issue was already fixed by immediately after the contest before this Github issue was filed. We appreciate your support.
