### ISSUE TITLE
Incorrect test case - 404. Sum of Left Leaves

### ISSUE THREAD

**Issue by mr3y-the-programmer** [LeetCode-Feedback/LeetCode-Feedback#4030]
#### Your LeetCode username

M R 3 YY

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Running test case: [1,2,3,4,5] on my code produces 6 which is correct, but my code cannot pass this test case since it has an expected value of 4 which is absolutely wrong!

#### Code you used for Submit/Run operation

```kotlin
/**
 * Example:
 * var ti = TreeNode(5)
 * var v = ti.`val`
 * Definition for a binary tree node.
 * class TreeNode(var `val`: Int) {
 *     var left: TreeNode? = null
 *     var right: TreeNode? = null
 * }
 */
class Solution {
    fun sumOfLeftLeaves(root: TreeNode?): Int {
        if(root == null) return 0
        
        return sumOfLeftRecursively(root?.left) + sumOfLeftLeaves(root?.right)
    }
    
    private fun sumOfLeftRecursively(root: TreeNode?): Int {
        if(root == null) return 0
        return root?.`val` + sumOfLeftRecursively(root?.left) + sumOfLeftLeaves(root?.right)
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

6

#### Additional context

Note: this also occurs with test case: [1,2,3,4,null,null,5] which is obviously incorrect too.

**Comment by lc-kay** [comment]
@mr3y-the-programmer The expected output is correct. Please check out this discuss post https://leetcode.com/problems/sum-of-left-leaves/discuss/771806/Confusing-expected-value
