### ISSUE TITLE
Missing Test Case - 501. Find Mode in Binary Search Tree

### ISSUE THREAD

**Issue by garima0508** [LeetCode-Feedback/LeetCode-Feedback#4031]
#### Your LeetCode username

garima_0508

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [0,null,1], [0,null,1,1].. Missing Test Cases 

#### Description of the bug

All the test cases that have 0 as a node and other nodes that may or may not be more frequent than 0 are missing.

#### Code you used for Submit/Run operation

```
// Find Mode in Binary Search Tree
class Solution {
public:
    unordered_map<int,int> mp;
    void inorder(TreeNode* root){
        if(!root)
            return;
        inorder(root->left);
        int x= root->val;
        mp[x]++;
        inorder(root->right);
    }
    vector<int> findMode(TreeNode* root) {
        vector<int> v;
        if(root->val==0){
            v.push_back(0);
            return v;
        }
        inorder(root);
        int maxi=0;
        for(auto i: mp){
            maxi = max(maxi, i.second);
        }
        for(auto i: mp){
            if(i.second == maxi)
                v.push_back(i.first);
        }
        return v;
    }
};
 ```

#### Language used for code

C++

#### Expected behaviour

I expect a wrong answer but instead, it got accepted

#### Screenshots

![BugReport-1](https://user-images.githubusercontent.com/64362620/124310412-c3634f00-db89-11eb-8e06-947be5a3e404.png)

**Comment by lc-kay** [comment]
Hi @garima0508 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@garima0508 Our team has reviewed your test case and code and found it not to be a missing test case. You can remove the if condition at line 14 and the code will pass. Thank you for your time.
