### ISSUE TITLE
658. Find K Closest Elements Solution Approach 2 Java code is wrong

### ISSUE THREAD

**Issue by lesongjia** [LeetCode-Feedback/LeetCode-Feedback#4034]
If you add the below test case, the Solution Approach 2 Java code will not return the expected result.
```
[1,1,1,1,10,12,13,14,15]
4
10
```

**Comment by jilsonjoseph** [comment]
For the below test case also Approach 2 java code is not giving the correct solution
[1,2,3,4,5]
2
3
The solution for this test case should be [2,3] but approach 2 java code gives [1,2]

**Comment by lc-kay** [comment]
@lesongjia @jilsonjoseph Our team was notified of this issue through the article comments and fixed the code. Thank you for your time.
