### ISSUE TITLE
Missing testcase & wrong solution code - 658. Find K Closest Elements

### ISSUE THREAD

**Issue by YingjieQiao** [LeetCode-Feedback/LeetCode-Feedback#4035]
#### Your LeetCode username
LeetCode ID: DanielQiao

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

- Missing test case

1. arr = [1,2,3,4,5], k = 3, x = 3
2.  arr = [1,2,3,4,5], k = 2, x = 3

- wrong solution code

In the [solution section](https://leetcode.com/problems/find-k-closest-elements/solution/), the code for approach 2 is wrong as a missing test case above will break it. The code is attached below.

#### Code you used for Submit/Run operation

```java
class Solution {
    public List<Integer> findClosestElements(int[] arr, int k, int x) {
        List<Integer> result = new ArrayList<Integer>();
        
        // Base case
        if (arr.length == k) {
            for (int i = 0; i < k; i++) {
                result.add(arr[i]);
            }
            
            return result;
        }
        
        // Binary search to find the closest element
        int left = 0;
        int right = arr.length - 1;
        int mid = 0;
        while (left <= right) {
            mid = (left + right) / 2;
            if (arr[mid] > x) {
                right = mid - 1;
            } else if (arr[mid] < x) {
                left = mid + 1;
            } else {
                break;
            }
        }
        
        // Initialize our sliding window's bounds
        left -= 1;
        right = left + 1;
        
        // While the window size is less than k
        while (right - left - 1 < k) {
            // Be careful to not go out of bounds
            if (left == -1) {
                right += 1;
                continue;
            }
            
            // Expand the window towards the side with the closer number
            // Be careful to not go out of bounds with the pointers
            if (right == arr.length || Math.abs(arr[left] - x) <= Math.abs(arr[right] - x)) {
                left -= 1;
            } else {
                right += 1;
            }
        } 

        // Build and return the window
        for (int i = left + 1; i < right; i++) {
            result.add(arr[i]);
        }
        
        return result;
    }
}

```

#### Language used for code

Java

#### Expected behavior

The Approach 2 code provided in the solution section should not be accepted as it won't pass the missing test cases listed above.

#### Screenshots

<img width="1002" alt="Screenshot 2021-07-03 at 4 39 00 PM" src="https://user-images.githubusercontent.com/49013092/124348572-2eaa3100-dc1d-11eb-99d8-66ab2d2e2cd8.png">

**Comment by lc-kay** [comment]
@YingjieQiao Our team was notified of this issue through the article comment section and fixed the code. Thank you for your time.
