### ISSUE TITLE
Mistake in example 2 in the question - 27. Remove Element

### ISSUE THREAD

**Issue by AxelUser** [LeetCode-Feedback/LeetCode-Feedback#4037]
#### Your LeetCode username
AxelUser

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In provided example 2 there's a mistake: it is `[0,1,4,0,3,_,_,_]`, but should be `[0,1,3,0,4,_,_,_]`, because original sequence is `[0,1,2,2,3,0,4,2]` (3 is before 4).

#### Code you used for Submit/Run operation
```kotlin
class Solution {
    fun removeElement(nums: IntArray, `val`: Int): Int {
        var start = 0
        for (n in nums) {
            if (n != `val`) nums[start++] = n
        }

        return start
    }
}
```

#### Language used for code
Kotlin

**Comment by lc-kay** [comment]
@AxelUser Per the explanation, "Note that the five elements can be returned in any order." Therefore, [0,1,4,0,3,_,_,_], is a valid output. Thank you for your time.
