### ISSUE TITLE
Wrong Test Case - 1096. Brace Expansion II

### ISSUE THREAD

**Issue by devangSinghh** [LeetCode-Feedback/LeetCode-Feedback#4038]
#### Your LeetCode username
Dev_ang

#### Category of the bug
Wrong test case

#### Code
```
vector<string> braceExpansionII(string expression) {
        set<string>Set;
        queue<string>q;
        q.push(expression);
        while(!q.empty()) {
            string s = q.front();
            q.pop();
            if(s.find('{') == string::npos) {
                Set.insert(s);
                continue;
            }
            int l = 0, r = 0;
            while(s[r] != '}')
                if(s[r++] == '{') 
                    l = r;
            string before = s.substr(0, l - 1);
            string mid = s.substr(l, r - l);
            string after = s.substr(r + 1);
            stringstream ssMid(mid);
            string temp;
            while(getline(ssMid, temp, ','))
                q.push(before + temp + after);
        }
        
        return vector<string>(begin(Set), end(Set));
    }
```

#### Language used for code
C++

There is a typo in test case  =>
It should be 
"{a,b}x{c,{d,e}y}"
instead of 
"{a,b},x{c,{d,e}y}"

A comma is extra before char x

Expected solution is correct

**Comment by lc-kay** [comment]
Hi @devangSinghh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@devangSinghh Those are two different test cases and both are correct with two different expected outputs.
for "{a,b},x{c,{d,e}y}", the answer is R("{a,b}") + R("x{c,{d,e}y}") --> ["a","b"] + R("x") R("{c,{d,e}y}") --> ["a","b"] + ["x"] (["c"] + R("{d,e}y")) --> ["a","b"] + ["x"] (["c"] + ["dy","ey"]) --> ["a","b"] + ["x"] ["c","dy","ey"] --> ["a","b"] + ["xc", "xdy", "xey"] --> ["a","b","xc","xdy","xey"]. Thank you for your time.
