### ISSUE TITLE
Missing Test Case - 993. Cousins in Binary Tree

### ISSUE THREAD

**Issue by jettinlim** [LeetCode-Feedback/LeetCode-Feedback#4039]
#### Your LeetCode username
jettinalan

#### Category of the bug
Missing Test Cases 

#### Description of the bug
The code should be rejected, but it passed. My code logic is that when the sum of two children of a root is equal to x+y, then x+y are siblings.
But the fact is, although sum of two children might be x+y, but doesn't mean that the two children are x and y.
Example: x = 11, y = 17
root->left->val = 16, root->right->val = 12,  16+12==11+17, my code identify them as siblings(which suppose not)
my code passed, although the logic was wrong

Test Case
```
[1,2,4,3,19,10,5,15,8,null,null,16,12,null,6,null,17,null,null,null,null,18,null,7,11,null,null,null,null,null,9,13,14,null,null,20]
11
17
```

#### Code you used for Submit/Run operation
```
class Solution {
public:
    bool isCousins(TreeNode* root, int x, int y) {
        queue<TreeNode*> q;
        q.push(root);
        int sum = x+y;
        
        while(!q.empty()){
            int current_size = q.size();
            //clear vector
            vector<int> v = {};
            for(int i = 0; i < current_size; i++){
                TreeNode* current = q.front();
                q.pop();
                
                //current root have both left & right node
                if(current->left && current->right)
                    //they are siblings (The wrong code is here)
                    if (sum-current->left->val==current->right->val || sum-current->right->val==current->left->val) 
                            return false;
                
                if(current->left){
                    q.push(current->left);
                    v.push_back(current->left->val);
                } 
                if(current->right){
                    q.push(current->right);
                    v.push_back(current->right->val);
                }
            }
            
            if(std::find(v.begin(), v.end(), x) != v.end())
            {
              if(std::find(v.begin(), v.end(), y) != v.end())
                {
                    //Both value are at the same level
                    return true;
                } 
            } 
        }
        
        return false;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
Fail 

#### Screenshots
target node level
![image](https://user-images.githubusercontent.com/49452311/124361380-82d70480-dc61-11eb-97b6-73ad417d9be7.png)

siblings identifier
![image](https://user-images.githubusercontent.com/49452311/124361413-b6b22a00-dc61-11eb-8312-bb5ffa3215b1.png)

missing test case(my code logic was to identify if the sum of two children is equal to x+y, then x and y are siblings, the code logic was wrong, but it passes)
![image](https://user-images.githubusercontent.com/49452311/124361534-29bba080-dc62-11eb-9024-e79386261e9d.png)

the wrong code
![image](https://user-images.githubusercontent.com/49452311/124361911-5a043e80-dc64-11eb-949c-c5b6d1c9f9d4.png)

#### Additional context
My code passed because there were no such test case(sum of 2 children equal to x+y) before reaching the target node level and allow the program to pass,

**Comment by lc-kay** [comment]
@jettinlim Please provide the missing test case in LeetCode format: Root, x, y. Thank you for your time.

**Comment by jettinlim** [comment]
> @jettinlim Please provide the missing test case in LeetCode format: Root, x, y. Thank you for your time.

Hi @lc-kay , I have updated the test case in the issue above, anyway this is the test case:

[1,2,4,3,19,10,5,15,8,null,null,13,14,null,6,null,17,null,null,null,null,18,null,7,11,null,null,null,null,null,9,16,12,null,null,20]
11
17

**Comment by lc-kay** [comment]
<img width="1246" alt="Screen Shot 2021-07-06 at 11 14 27 AM" src="https://user-images.githubusercontent.com/70870126/124805017-cd7da880-df0f-11eb-98fa-7ac693e1b279.png">
For a valid missing test case report, the custom test case must fail the accepted code provided. In this case, your code is generating the expected output for your custom test case. Please provide a solution that this test case will fail, then our team will consider adding it. I will close this ticket for now and reopen it when new information is provided. Thank you for your time.

**Comment by jettinlim** [comment]
@lc-kay Thanks for the information, I have created a new test case which will fail the accepted code with below:
```
[1,2,4,3,19,10,5,15,8,null,null,16,12,null,6,null,17,null,null,null,null,18,null,7,11,null,null,null,null,null,9,13,14,null,null,20]
11
17
```
![image](https://user-images.githubusercontent.com/49452311/124932786-ef714b00-e035-11eb-882b-dfa02cf7fa55.png)

Thanks.

**Comment by lc-kay** [comment]
Hi @jettinlim 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jettinlim 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
