### ISSUE TITLE
1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit: Clarification needed

### ISSUE THREAD

**Issue by evgeni-nabokov** [LeetCode-Feedback/LeetCode-Feedback#404]
#### Your LeetCode username
evgeni-nabokov

#### Category of the bug
- [*] Question

#### Description of the bug
The state: _In case there is no subarray satisfying the given condition return 0._
I see the only case to return 0 is when `nums` is empty or null. If `nums` has 1 element a least, the answer is always > 0. So I find the state above confusing, because it speaks on subarray of an empty array, which is nonsense imo.

**Comment by CooperCooperCooper** [comment]
Hi @evgeni-nabokov ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @evgeni-nabokov ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
