### ISSUE TITLE
Missing Test Case - 363. Max Sum of Rectangle No Larger Than K

### ISSUE THREAD

**Issue by henriquesglima** [LeetCode-Feedback/LeetCode-Feedback#4040]
#### Your LeetCode username

henriquesglima

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The challenge is to find the max sum of a rectangle.
But Example  1 show the max sum of a square. The blue borders are actually drawing a square.
The output is correct because the answer is 2 but if you get the rectangle in row 0. Numbers 1, 0 ,1.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@henriquesglima The example is correct. A square is a special type of rectangle because it possesses all the properties of a rectangle. Similar to a rectangle, a square has interior angles which measure 90 degrees each and opposite sides that are parallel and equal. Thank you for your time.
