### ISSUE TITLE
C++ Solution not accepted - 482. License Key Formatting

### ISSUE THREAD

**Issue by nehamalcom** [LeetCode-Feedback/LeetCode-Feedback#4041]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

C++ solution is giving the right output but test is showing it as wrong.

#### Code you used for Submit/Run operation

```
#include <cctype>
class Solution {
public:
    string licenseKeyFormatting(string s, int k) {
        int len;
        len = s.length();
        int i = len-1;
        int j = k;
        string ans;
        for(;i>=0;i--){
            if(j==0){
                ans.push_back('-');
                j = k;
            }
            if(s[i]=='-'){
                continue;
            }
            j--;
            ans.push_back(s[i]);
        }
        string final_ans;
        for(int i=len-2; i>=0; i--) {
            cout<<ans[i];
            char c = toupper(ans[i]);
            final_ans.push_back(c);
        }
        return final_ans;
    }
};
```

#### Expected behavior

The test cases should have passed, especially since the actual output and the expected output is exactly the same.

#### Screenshots

![Screenshot 2021-07-04 at 3 28 09 AM](https://user-images.githubusercontent.com/71584656/124367773-df451e80-dc77-11eb-9a96-9d026f0baa57.png)

**Comment by lc-kay** [comment]
Hi @nehamalcom 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@nehamalcom Our team has reviewed your code and noticed that it is returning some unwanted characters in the beginning of the string "\x005F3Z-2E9W". For debugging support, please raise this issue in the problem discuss section. Thank you for your time.
