### ISSUE TITLE
90jkn[\Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by NidhiS31** [LeetCode-Feedback/LeetCode-Feedback#4042]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
