### ISSUE TITLE
Wrong description - 1462. Course Schedule IV

### ISSUE THREAD

**Issue by Frederick-S** [LeetCode-Feedback/LeetCode-Feedback#4044]
#### Your LeetCode username

Frederick

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description says:

> For example, the pair [0, 1], indicates that to take course 0 you have to first take course 1.

which means for pair (a, b), b is the prerequisite of a, which is contradictory to the description in Example 1:

> Input: numCourses = 2, prerequisites = [[1,0]], queries = [[0,1],[1,0]]
> Output: [false,true]
> Explanation: course 0 is not a prerequisite of course 1 but the opposite is true.

Note that the explanation says **course 0 is not a prerequisite of course 1** when **prerequisites = [[1,0]]**, but course 0 should be a prerequisite of course 1 according to the question description.

#### Code you used for Submit/Run operation

```
No need of code as it is related to question description.
```

#### Language used for code

Language independent.

#### Expected behavior

The description should be changed to:

> For example, the pair [0, 1], indicates that to take course 1 you have to first take course 0.

**Comment by lc-kay** [comment]
Hi @Frederick-S 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Frederick-S 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
