### ISSUE TITLE
Missing case in Contest 248, Problem 1923: Longest Common Subpath

### ISSUE THREAD

**Issue by z-jolu** [LeetCode-Feedback/LeetCode-Feedback#4045]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Hello,

In Contest 248, there's a problem "Longest Common Subpath", where lots of users use binary search + hash to solve, while the solution in general is correct, using 2^64 as modulo is very dangerous and is easy to get hacked. 

For example, ZeRoLJ42 (ranking 8th), superJ (ranking 9th), Time-Limit (ranking 17th), kzyKT (ranking 19th), azukun (ranking 22nd), _Anicca (ranking 25), all failed on this case. Considering many high-ranking participants are making this error, this is pretty concerning and we should add this case to the testing cases list.

The 2^64 module hash algorithm is easy to break by algorithms discussed here: https://codeforces.com/blog/entry/4898, using multiple hashes with prime module is more encouraged and less error-prone.

I'd like this case to be added to the testing case list, and the contest submission for contest 248 to be re-judged on this case.

Test case:
Input: n = 3, paths = [[0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1],[1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2,1,0,1,2,1,2,1,0,1,0,1,2,1,2,1,0,1,2,1,0,1,0,1,2]]

Output: 1023

#### Code you used for Submit/Run operation

```
// here is a code copied from _Anicca , who ranks 25th in the contest.

class Solution {
public:
    vector<unsigned long long>f[100005];
    unsigned long long p[100005];
    unsigned long long cal(int i,int l,int r){
        return f[i][r]-f[i][l-1]*p[r-l+1];
    }
    unordered_map<unsigned long long,int>mp;
    unordered_map<unsigned long long,int>ck;
    bool check(int x,int n){
        if(x==0) return true;
        mp.clear();
        for(int i=0;i<n;i++){
            ck.clear();
            for(int j=x;j<f[i].size();j++){
                if(ck.find(cal(i,j-x+1,j))==ck.end()){
                    mp[cal(i,j-x+1,j)]++;
                    ck[cal(i,j-x+1,j)]++;
                    if(mp[cal(i,j-x+1,j)]==n) return true;
                }
            }
        }
        return false;
    }
    int longestCommonSubpath(int n, vector<vector<int>>& paths) {
        int mx=0;
        int mn=0x3f3f3f3f;
        for(int i=0;i<paths.size();i++){
            f[i].push_back(0);
            for(int j=0;j<paths[i].size();j++){
                f[i].push_back(f[i].back()*100057+paths[i][j]);
            }
            mx=max(mx,(int)paths[i].size());
            mn=min(mn,(int)paths[i].size());
        }
        p[0]=1;
        for(int i=1;i<=mx;i++) p[i]=p[i-1]*100057;
        int l=0,r=mn,m,ans=0;
        while(l<=r){
            m=(l+r)>>1;
            if(check(m,(int)paths.size())){
                ans=m;
                l=m+1;
            }else{
                r=m-1;
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Output should be 1023 while incorrectly implemented code will return 1024.

#### Screenshots
![image](https://user-images.githubusercontent.com/63533823/124376193-9e8adc80-dc5a-11eb-8072-ead58955a522.png)

**Comment by zerotrac** [comment]
Please do not add this testcase to Leetcode.

Leetcode is an interview-oriented OJ, that is, most of the problems are from in-reality interviews. We should not introduce competitive programming related (e.g. codeforces) knowledge points into it. As "how to hack a 2^64 modulo rolling hash" could never be asked during an interview, we should let them pass anyway.

Here is another example. Codeforces allows using multiples of a prime number to hack `std::unordered_set` in C++, but this could never be applied to Leetcode for the same reason. You could not ask an interviewer to behave like a competitive programmer.

**Comment by z-jolu** [comment]
> Please do not add this testcase to Leetcode.
> 
> Leetcode is an interview-oriented OJ, that is, most of the problems are from in-reality interviews. We should not introduce competitive programming related (e.g. codeforces) knowledge points into it. As "how to hack a 2^64 modulo rolling hash" could never be asked during an interview, we should let them pass anyway.
> 
> Here is another example. Codeforces allows using multiples of a prime number to hack `std::unordered_set` in C++, but this could never be applied to Leetcode for the same reason. You could not ask an interviewer to behave like a competitive programmer.

Your opinion contradicts what Leetcode is currently doing.
In this problem, lots of users passed 70 cases out of 71, there are tons of discussion on this 70/71 issue. And from that test case, Leetcode specifically created some data that will make single roll hash with module around 10^9 fail. 

As you said, "how to hack a 2^64 modulo rolling hash" could never be asked during an interview, if that's the case, **we should also remove test 71** and let single hash pass as it implemented the exact same idea of the algorithm and it will probably run fine with no issues unless there are specific designed test data. **If you agree this opinion, then I agree that this case is not necessary to be added.**

Also, hacking unordered_set is different from hacking this algorithm. Hacking that data structure will only make code run slower but still correct, but this algorithm is just plain wrong on some test cases, running slow / fast is a different scenario with running correctly / incorrectly.

**Comment by votrubac** [comment]
If it's a real interview, you will need to do a collision check. You can discuss the best hashing strategy for the problem, but you will still be expected to handle collisions.

So it's not unreasonable for LeetCode to not to accept solutions without collision check. At the same, it's quite difficult to automatically verify this.

What bothers me more are solutions without the collision check that were accepted on the first submit. It is improbable you could accidentally pick base/modulo that works for a hidden test case.

So, if LeetCode added one strong test case (#71), they should add more test cases like that.

**Comment by zerotrac** [comment]
> If it's a real interview, you will need to do a collision check. You can discuss the best hashing strategy for the problem, but you will still be expected to handle collisions.
> 
> So it's not unreasonable for LeetCode to not to accept solutions without collision check. At the same, it's quite difficult to automatically verify this.
> 
> What bothers me more are solutions without the collision check that were accepted on the first submit. It is improbable you could accidentally pick base/modulo that works for a hidden test case.
> 
> So, if LeetCode added one strong test case (#71), they should add more test cases like that.

If collision check must be applied, the code would definitely run into TLE in some cases, because when the collision happens more than O(1), the total complexity would be strictly larger and goes beyond the time limit.

I have tested your code provided here (with collision check) https://leetcode.com/problems/longest-common-subpath/discuss/1314826/Rolling-Hash-%2B-Collision-Check. Given a testcase with n=100000 and two arrays [0, 1] * 25000, [9999,90009] * 25000, the code would results in a TLE since [0, 1] has the same hash value with [9999, 90009], the collsion check is called many many ~O(len^2) times.

**Comment by z-jolu** [comment]
Thanks for summarizing the algorithms people used in the contest. One more algorithm is to use rolling hash with 
1. Different bases with same relatively large (around 10^9) prime mods, or
2. Different bases with different relatively large (around 10^9) prime mods.

I don't have a formal proof but I believe the chances for hash collision in this case is small. It's easy to construct some values that have hash collision for a single given pair of <base, mod>, but adding multiple pairs will reduce the chance of collision exponentially. 

That algorithm, possibly together with collision check implemented, is hard to get hacked in my opinion.
I would suggest the following algorithms as allowed:
1. Single rolling hash with random base and (random / fixed) very large prime mod (in long long range), that requires special treatment when doing multiplication.
2. Multiple rolling hash with different base and (same / different) relatively large prime (around 10^9 range).
3. Same for 1 and 2, but adding additional hash collision check to be safer.
4. Suffix DS.

Well in general this problem is really not very suitable for an interview training site. I especially don't understand why they have additional constraint as "the same city will not be listed consecutively" - I just don't see any benefit that condition brings. But at the same time it's really hard to come up with new nice ideas these days.

**Comment by lc-kay** [comment]
Hi @z-jolu 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
