### ISSUE TITLE
419. Battleships in a Board - Missing test case

### ISSUE THREAD

**Issue by sekhar179** [LeetCode-Feedback/LeetCode-Feedback#405]
#### Your LeetCode username

sekhar179

#### Category of the bug
- [ *] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Wrong solution accepted due to lack of proper test cases

#### Code you used for Submit/Run operation

```
// Battleships in a Board
class Solution {
public:
    int countBattleships(vector<vector<char>>& board) {
        int cnt = 0;
        int M = board.size();
        int N = board[0].size();
        for (int i = 0; i < M; i++) {
            int j = 0;
            while (j < N) {
                if (board[i][j] == '.') {
                    j++;
                    continue;
                }
                if (i-1 >= 0 && board[i-1][j] == 'X') {
                    j++;
                    continue;
                }
                cnt++;
                while (j < N && board[i][j] == 'X') {
                    j++;
                }
            }

        }
        return cnt;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should fail with the below test case (2nd test case mentioned in the problem description itself)
Input: [[".",".",".","X"],["X","X","X","X"],[".",".",".","X"]]
Actual Output: 2
Expected Output: 0
![leetcode_problem](https://user-images.githubusercontent.com/65918795/83501441-bcc55c80-a4dd-11ea-881e-7a2784206f5c.png)

**Comment by CooperCooperCooper** [comment]
Hi @sekhar179 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by sekhar179** [comment]
I am closing this issue as the given example is an invalid example according to the problem description.
