### ISSUE TITLE
Improving problem 88 by removing a constraint 

### ISSUE THREAD

**Issue by Anirudhk07** [LeetCode-Feedback/LeetCode-Feedback#4051]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem 88. [Merge Two Sorted Arrays](https://leetcode.com/problems/merge-sorted-array/) has a constraint of `nums1.length == m + n` due to which the problem becomes vacuously easy. The problem would have been more interesting if  `nums1.length == m`. In fact, the revised constraint would judge & check the basic understanding of resizing & `[]` operator. Currently, from the understanding of the discussions tab, many users have ignored the very fact that `[]` operator will have undefined behavior if accessed beyond `>=m` provided `nums1.length == m`.  Many users are having an understanding that merging into `nums1` would still be possible without resizing, provided the constraint(`nums1.length == m + n`) was not there. Modifying the constraint(`nums1.length == m`) will make this problem a lot better for interviews & many other coding platforms are using `nums1.length == m`.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    void merge(vector<int>& A, int m, vector<int>& B, int n) {
        cout<<A.size();
        int i=m-1;
		int j=n-1;
		int k = m+n-1;
		while(i >=0 && j>=0)
		{
			if(A[i] > B[j])
				A[k--] = A[i--]; //the understanding of this access is taken for granted by many users. if constraint nums1.length=m would have been there , then resizng vectors would have made this problem much better.
			else
				A[k--] = B[j--]; 
		}
		while(j>=0)
			A[k--] = B[j--];
        
        while(i>=0)
			A[k--] = A[i--];
    }
};
```
Here I am concerned with users accessing `A[k]` without resizing. This would work perfectly fine with the status quo of constraints & test cases but it reduces the quality of this question.

#### Language used for code
C++

#### Expected behavior
1. Change Constraints

`nums1.length == m + n` change to `nums1.length == m`

2. Change Testcases from this format  - 
```
nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3
```

To this format  - 
```
nums1 = [1,2,3], m = 3, nums2 = [2,5,6], n = 3
```

**Comment by lc-kay** [comment]
Hi @Anirudhk07 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Anirudhk07 Thank you for your suggestion. However, our team has decided to not make changes.
