### ISSUE TITLE
Missing Test Case - 680. Valid Palindrome II

### ISSUE THREAD

**Issue by CherishHack** [LeetCode-Feedback/LeetCode-Feedback#4052]
#### Your LeetCode username
Hammer001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case: `axbcbaba`

#### Code you used for Submit/Run operation
```
class Solution:
    def validPalindrome(self, s: str) -> bool:
        i, j = 0, len(s) - 1
        
        while i < j and s[i] == s[j]:
            i += 1
            j -= 1
            
        if i >= j:
            return True
        
        while i < j and (s[i] == s[j-1] or s[i+1] == s[j]):
            i += 1
            j -= 1
            
        return i >= j
```

#### Language used for code
Py3

#### Expected behavior
My code gets AC, but it should get WA. 

#### Additional context
Please add test case: `axbcbaba` to the OJ

**Comment by CherishHack** [comment]
The reason for the code being wrong is: I am using greedy algorithm in a wrong way (Or I would say in a too-greedy way). In the second for-loop, I am checking `s[i] == s[j-1] or s[i+1] == s[j]`. This can be wrong when `s[i] == s[j-1]` is true for some time and `s[i+1] == s[j]` is true for some other time. (Check my test case). 

A correct greedy (one-pass) algorithm should make sure `s[i] == s[j-1]` is true all the time. Or `s[i+1] == s[j]` is true all the time.

```
class Solution:
    def validPalindrome(self, s: str) -> bool:
        i, j = 0, len(s) - 1
        
        while i < j and s[i] == s[j]:
            i += 1
            j -= 1
            
        if i >= j:
            return True
        
        fast_j = fast_i = True
        while i < j:
            if s[i] != s[j-1]:
                fast_j = False
            
            if s[i+1] != s[j]:
                fast_i = False
                
            if not fast_j and not fast_i:
                return False
            
            i += 1
            j -= 1
            
        return True
```

**Comment by lc-kay** [comment]
Hi @CherishHack 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @CherishHack 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
