### ISSUE TITLE
1220. Count Vowels Permutation - C++ result overflow(answer is not right)

### ISSUE THREAD

**Issue by YxingC** [LeetCode-Feedback/LeetCode-Feedback#4054]
#### Your LeetCode username

claudchen7990

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In C++, return type is int. It seems like input bigger than 30 will cause integer overflow.
But constraint is 1<=N<=2*10^4.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int countVowelPermutation(int n) {
        const vector<vector<int>> connectMap {
            {1}, {0, 2}, {0, 1, 3, 4} ,{2, 4}, {0}
        };
        vector<vector<unsigned long long int>> dp(19999, vector<unsigned long long int>(5, 0));
        for (int i = 0; i < 5; ++i) dp[0][i] = 1;
        
        // compute count of vowel for each layer
        for (int i = 1; i < n; ++i) {
            for (int j = 0; j < 5; j++) {
                // cout << i << endl;;
                for (const auto& k : connectMap[j]) {
                    dp[i][k] += dp[i-1][j];
                }
            }
        }
        
        //Debug print
        for (int i = 0; i < 50; ++i) {
           for (const auto& v: dp[i])
               cout << v << " ";
           cout << endl;
        }
        
        // compute result;
        unsigned long long int result = 0;
        for (int i = 0; i < 5; i++) {
            result += dp[n-1][i];
        }
        
        return result;
    }
    
};
```

#### Language used for code

C++

#### Expected behavior

1 1 1 1 1    (result = 5, n=1)
3 2 2 1 2    (result = 10, n=2)
6 5 3 2 3 
11 9 7 3 5 
21 18 12 7 10 
40 33 25 12 19 
77 65 45 25 37 
147 122 90 45 70 
282 237 167 90 135 
539 449 327 167 257 
1033 866 616 327 494  (n=11)
......
33603926 28096933 20183155 10543698 16050691 (n=27)
64330779 53787081 38640631 20183155 30726853  (n=28)
123154565 102971410 73970236 38640631 58823786  (n=29)
235765432 197124801 141612041 73970236 112610867 (result=
761083377, n=30)
451347709 377377473 271095037 141612041 215582277 (!!! leetcode ans=
457014530, is wrong)

**Comment by zerotrac** [comment]
The problems states:

```
Since the answer may be too large, return it modulo 10^9 + 7.
```

**Comment by YxingC** [comment]
Sorry I didn't notice that.
