### ISSUE TITLE
Inappropriate Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by madongchunqiu** [LeetCode-Feedback/LeetCode-Feedback#4056]
#### Your LeetCode username
mdcq

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Current Test Cases are toooo simple (arrays are too short), poorly design algorithms run faster than better ones.
I checked the fastest code in Swift, and it is using brutal force algorithm, which is not performant if the Test Cases use longer arrays.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
Hash table algorithm should be faster than brutal force algorithm.

#### Additional context
Arrays in the appropriate Test Cases should be relatively long enough to descriminate different algorithms.

**Comment by lc-kay** [comment]
@madongchunqiu Please provide the accepted code and a valid test case that will fail it. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @madongchunqiu 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
