### ISSUE TITLE
235. Lowest Common Ancestor of a Binary Search Tree - Golang template is weird

### ISSUE THREAD

**Issue by occidere** [LeetCode-Feedback/LeetCode-Feedback#406]
#### Your LeetCode username

occidere

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

The default template of Golang is something weird.
```go
/**
 * Definition for TreeNode.
 * type TreeNode struct {
 *     Val int
 *     Left *ListNode
 *     Right *ListNode
 * }
 */
 func lowestCommonAncestor(root, p, q *TreeNode) *TreeNode {
  
}
```
Weird points
1. Elements of TreeNode struct definition in comments
    - Type of `Left`, `Right` are defined as `*ListNode`
    - It should be changed to `*TreeNode`

~~2. Arguments of `lowestCommonAncestor` function~~
    ~~- There are no type definitions of `root`, `p`~~
    ~~- These should be changed to `(root *TreeNode, p *TreeNode, q *Treenode)`~~

Please, Ignore second one 😂
Thats my fault.

<br>

#### Code you used for Submit/Run operation

It should be changed like below:

```go
/**
 * Definition for TreeNode.
 * type TreeNode struct {
 *     Val   int
 *     Left  *TreeNode
 *     Right *TreeNode
 * }
 */
func lowestCommonAncestor(root, p, q *TreeNode) *TreeNode {

}
```

Accepted code is like this:
<details>
    <summary>show details</summary>

```go
package main

/**
 * Definition for TreeNode.
 * type TreeNode struct {
 *     Val   int
 *     Left  *TreeNode
 *     Right *TreeNode
 * }
 */
func lowestCommonAncestor(root, p, q *TreeNode) *TreeNode {
	a1, a2 := []*TreeNode{}, []*TreeNode{}
	getAncestors(root, p, &a1)
	getAncestors(root, q, &a2)

	minLen := Min(len(a1), len(a2))
	var lca *TreeNode
	for i := 0; i < minLen; i++ {
		if a1[i].Val == a2[i].Val {
			lca = a1[i]
		} else {
			break
		}
	}
	return lca
}

func getAncestors(root, target *TreeNode, ancestors *[]*TreeNode) {
	if root != nil {
		*ancestors = append(*ancestors, root)
		if target.Val < root.Val {
			getAncestors(root.Left, target, ancestors)
		} else if target.Val > root.Val {
			getAncestors(root.Right, target, ancestors)
		}
	}
}

func Min(a int, b int) int {
	if a < b {
		return a
	} else {
		return b
	}
}
```

</details>

#### Language used for code

Golang

##### Golang template (abnormal)
![image](https://user-images.githubusercontent.com/20942871/83505457-c4e2c380-a500-11ea-93de-e6dcddf8bd10.png)

##### C template (normal)
![image](https://user-images.githubusercontent.com/20942871/83505427-bc8a8880-a500-11ea-975d-e4214e934b23.png)

**Comment by CooperCooperCooper** [comment]
Hi @occidere ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
