### ISSUE TITLE
Improper Variable Names - 468. Validate IP Address

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#4062]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [468. Validate IP Address](https://leetcode.com/problems/validate-ip-address), the variable name `IP` contains all upper case letters. It is not a good practice to use upper case letters as a variable name, so the variable name should be changed. For example, the variable name `ip` is better. Both problem description and code should have the variable name updated.

#### Expected behavior
In [468. Validate IP Address](https://leetcode.com/problems/validate-ip-address), the variable name `IP` should be changed to `ip` as described above, in both problem description and code.

**Comment by lc-kay** [comment]
@stormsunshine Thank you for letting us know. Our team is working on renaming variables for our problem set and will apply this change as soon as we can.
