### ISSUE TITLE
Missing Test Case - 1218. Longest Arithmetic Subsequence of Given Difference

### ISSUE THREAD

**Issue by sumitaby1** [LeetCode-Feedback/LeetCode-Feedback#4064]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The test case set is missing the test case:
[0,0,0,0]
0
Acceptable answer should be 4 but it is accepting code which generates 2 as output.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestSubsequence(vector<int>& arr, int difference) 
    {
        unordered_map<int,int>map;
        int ans=1;
        for(int i=0;i<arr.size();i++){
            map[arr[i]]=1;
            if(map.count(arr[i]-difference))
                map[arr[i]]+=map[arr[i]-difference];      
            ans=max(ans,map[arr[i]]);
        }
        return ans;
    }
};
```

#### Language used for code
 C++

#### Expected behavior
The code should have thrown wrong answer when submitted instead it was accepted.

**Comment by lc-kay** [comment]
Hi @sumitaby1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sumitaby1 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by sumitaby1** [comment]
Hi,

My leetcode account link is https://leetcode.com/sumitaby1/

Id is: sumitaby1.
