### ISSUE TITLE
Wrong solution - 486. Predict the Winner

### ISSUE THREAD

**Issue by vovanmix** [LeetCode-Feedback/LeetCode-Feedback#4065]
#### Your LeetCode username
singingcode

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
`Approach #3 Dynamic Programming [Accepted]`. Copied it to the editor and submitted, got the wrong answer:
Your input
[1,5,2,4,6]
Output
false
Expected
true
The same goes for `Approach #4 1-D Dynamic Programming [Accepted]:`

#### Code you used for Submit/Run operation

`Approach #3:`
```
class Solution {
    public boolean PredictTheWinner(int[] nums) {
        int[][] dp = new int[nums.length + 1][nums.length];
        for (int s = nums.length; s >= 0; s--) {
            for (int e = s + 1; e < nums.length; e++) {
                int a = nums[s] - dp[s + 1][e];
                int b = nums[e] - dp[s][e - 1];
                dp[s][e] = Math.max(a, b);
            }
        }
        return dp[0][nums.length - 1] >= 0;
    }
}
```
`Approach #4`
```
public class Solution {
    public boolean PredictTheWinner(int[] nums) {
        int[] dp = new int[nums.length];
        for (int s = nums.length; s >= 0; s--) {
            for (int e = s + 1; e < nums.length; e++) {
                int a = nums[s] - dp[e];
                int b = nums[e] - dp[e - 1];
                dp[e] = Math.max(a, b);
            }
        }
        return dp[nums.length - 1] >= 0;
    }
}

```

#### Language used for code
Java

**Comment by lc-kay** [comment]
Hi @vovanmix 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vovanmix 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
