### ISSUE TITLE
Missing Test Case - 566. Reshape the Matrix

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4066]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

 row number and column number
should be
 number of rows and number of columns

#### Code you used for Submit/Run operation

```
```

#### Expected behavior
- a row number cannot be the number of columns
- the question must be clear without any confusion

#### Screenshots
![image](https://user-images.githubusercontent.com/8236389/124537929-69d47c00-de38-11eb-93af-a0c1bb79b969.png)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
