### ISSUE TITLE
Missing Test Case - 566. Reshape the Matrix

### ISSUE THREAD

**Issue by 95871abhinandankumar** [LeetCode-Feedback/LeetCode-Feedback#4067]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

#wrong in Hint-4

hint-4
M[i] => M[i/n][n%i] Will it result in right mapping? Take some example and check this formula

instead of M[i] => M[i/n][n%i] , it should be M[i] => M[i/n][i%n]

**Comment by 95871abhinandankumar** [comment]
wrongly written in hint

**Comment by lc-kay** [comment]
Hi @95871abhinandankumar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @95871abhinandankumar 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
