### ISSUE TITLE
Missing Test Case - 1338. Reduce Array Size to The Half

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#4069]
#### Your LeetCode username

archit91

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:
```
[100000, 100000]
```

#### Code you used for Submit/Run operation

```
class Solution {
    static const int MAX = 100000;
public:
    int minSetSize(vector<int>& arr) {        
        int freq[MAX+1]{}, freqBuckets[MAX+1]{}, ans = 0;
        for(auto num : arr) freq[num]++;                     // get frequency of elements
        for(int i = 0; i < MAX; i++) freqBuckets[freq[i]]++; // get instances of each frequency
        for(int i = MAX, deleteRequired = size(arr) / 2; deleteRequired > 0; i--) {
            if(!freqBuckets[i]) continue;                    // no elements having this frequency
            int noOfFreqToDelete = min(freqBuckets[i], max(1, deleteRequired / i));   // above-mentioned optimization
            deleteRequired -= i * noOfFreqToDelete;          // delete elements having frequency = i
            ans += noOfFreqToDelete;                         // increment by number of instances of frequency (unique elements) deleted
        }   
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Additional context

Either test cases where 100000 (right bound for `arr[i]`) requires to be deleted must be added or the bounds must be changed to -  `1 <= arr[i] < 100000`

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @archit11111
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
