### ISSUE TITLE
Test case contribution for 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by paragpachpute** [LeetCode-Feedback/LeetCode-Feedback#407]
#### Category of the bug
- [-] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Test case contribution, I found a few interesting test cases which, if not already present, should be added into the test pack. Online Judge is returning correct output, it is just that if we don't have a similar test case in the test pack then we should add it.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public boolean checkSubarraySum(int[] nums, int k) {
        if (nums.length <= 1)
            return false;
        
        int[] sum = new int[nums.length];
        sum[0] = nums[0];
        for (int i = 1; i < nums.length; i++) {
            sum[i] = sum[i-1] + nums[i];
            if (sum[i] == k || (k != 0 && sum[i] % k == 0))
                return true;
        }
        
        for (int i = 0; i < nums.length; i++) {
            for (int j = i+2; j < nums.length; j++) {
                sum[j] -= nums[i];
                if (sum[j] == k || (k != 0 && sum[j] % k == 0))
                    return true;
            }
        }
        
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Sample Input:
[0,1,0,2]
0
Sample output:
false

Sample Input:
[0,0,1,2]
2
Sample output:
true

**Comment by CooperCooperCooper** [comment]
Hi @paragpachpute ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @paragpachpute ,
Thank you for your time. Upon reviewing this problem and these test cases, we've decided to keep this problem as is because these test cases with the given code don't show unexpected behavior. We appreciate your support.
