### ISSUE TITLE
Missing Test Case - 1338. Reduce Array Size to The Half

### ISSUE THREAD

**Issue by Ashutosh3817** [LeetCode-Feedback/LeetCode-Feedback#4070]
class Solution {
  public int minSetSize(int[] arr) {
    Map<Integer, Integer> map = new HashMap<>();
    for (int num : arr) {
      map.put(num, map.getOrDefault(num, 0) + 1);
    }
    PriorityQueue<Integer> pq = new PriorityQueue<>(new Comparator<Integer>(){
      public int compare(Integer o1, Integer o2) {
        return map.get(o2) - map.get(o1);
      }
    });
    for (Integer key : map.keySet()) {
      pq.add(key);
    }
    int n = arr.length / 2;
    int currSize = 0;
    int count = 0;
    while (currSize < n) {
      currSize += map.get(pq.poll());
      count++;
    }
    return count;
  }
}

**Comment by lc-kay** [comment]
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
