### ISSUE TITLE
Missing Test Case - 41. First Missing Positive

### ISSUE THREAD

**Issue by HETFADIA** [LeetCode-Feedback/LeetCode-Feedback#4073]
#### Your LeetCode username

HET FADIA

#### Category of the bug
- [ first-missing-positive] Question
- [ https://leetcode.com/submissions/detail/518345852/] Solution
- [Python ] Language
- [1 ] Missing Test Cases 

#### Description of the bug
Wrong solution also passes
If the solution returns len(nums)+1 then it passes

#### Code you used for Submit/Run operation
class Solution:
    def firstMissingPositive(self, nums: List[int]) -> int:
        dict=set(nums)
        for i in range(1,10**5):
            if i not in dict:
                return i;
        return len(nums)+1

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Python

#### Expected behavior
The solution should give WA on 
1 missing large number from 1 to 5e5 ie [1,5e5]

#### Screenshots
![image](https://user-images.githubusercontent.com/62541263/124639467-d50a6680-dea9-11eb-984d-cc38beed3b9a.png)

**Comment by lc-kay** [comment]
@HETFADIA Please provide the missing test case in LeetCode format in a .txt file. Thank you!

**Comment by HETFADIA** [comment]
[out.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6772957/out.txt)
[code.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6772965/code.txt)

The test case is in out.txt.
The code.txt (python3 file) gives correct output(when submitted on leetcode) but fails on out.txt.
So out.txt must be added to the test files.
Thank you

**Comment by lc-kay** [comment]
Hi @HETFADIA 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @HETFADIA 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by HETFADIA** [comment]
Below is my LeetCode ID
LeetCode ID: HETFADIA
Profile link: https://leetcode.com/HETFADIA/
