### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by sagacious9783** [LeetCode-Feedback/LeetCode-Feedback#4074]
<img width="1147" alt="Screenshot 2021-07-07 at 12 20 00 AM" src="https://user-images.githubusercontent.com/20686502/124651863-148c7f00-deb9-11eb-86ed-ce2f21c43989.png">

#### Category of the bug
- [ *] Missing Test Cases 

#### Description of the bug
Manual Test Case passes but on submitting it fails.

#### Code you used for Submit/Run operation
```
public class Solution {
    
         public static TreeNode prev=null;
    
    public bool IsValidBST(TreeNode root) {
        
        
        if(root!=null)
        {
            if(!IsValidBST(root.left))
                return false;
            
            if(prev!=null && root.val <= prev.val)
                return false;
            
            prev = root;
            
            return IsValidBST(root.right);
        }
        else
          return true;
        
    }
}

```

**Comment by lc-kay** [comment]
Hi @sagacious9783 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
