### ISSUE TITLE
deploying better solution for "Valid Parentheses"

### ISSUE THREAD

**Issue by Rassska** [LeetCode-Feedback/LeetCode-Feedback#4077]
Hi, there!

Do not want to waster your time, just need a quick response!
Have a huge amount of desire to write a linear solution for the https://leetcode.com/problems/valid-parentheses, with no additional space. It can be improved from O(n) - time | O(n) - space to O(n) - time | O(1) - space. 
Whether it's possible to do or not? If it's, how to contribute it?

Thank you!

**Comment by lc-kay** [comment]
@Rassska Please feel free to contribute your solution in the problem discuss section. I've also relayed this to our team about this approach so we can add it as soon as we can. Thank you for your time.
