### ISSUE TITLE
Time Complexity - 621. Task Scheduler

### ISSUE THREAD

**Issue by alan0428a** [LeetCode-Feedback/LeetCode-Feedback#4079]
#### Your LeetCode username
alan0428a

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For the first greedy solution, it builds up the frequency table. And it states that the time complexity is `N`, where N is the length of the string(tasks) input. However, the solution sorts the frequency table. I think the time complexity should count sorting as well. Would the time complexity be `NlogN`, because of sorting?

#### Language used for code
C++

**Comment by lc-kay** [comment]
@alan0428a Please check out this user's response in the article comment section: https://leetcode.com/problems/task-scheduler/solution/934688 Thank you for your time.
