### ISSUE TITLE
Missing Test Case - 79. Word Search

### ISSUE THREAD

**Issue by Maryia-M** [LeetCode-Feedback/LeetCode-Feedback#4082]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When I am just checking if all searched word characters are present in the grid before running searching the word I reduce my runtime from 240ms to 4ms. It's too easy to avoid running stress test (the biggest possible grid and the word can't be found inside it) by doing this simple test. 
![image](https://user-images.githubusercontent.com/18392871/124817016-82907f00-df69-11eb-9e1e-c67cabbf76c2.png)
I believe there should be a stress test such that running the most expensive part of the solution can't be omitted so easily.

For example the test:
[["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","B"],["A","A","A","A","B","A"]]
"AAAAAAAAAAAAABB"

In this case I can't omit running word search in the grid by simply checking if characters 'A' and 'B' are present in the grid.
The characters are inside the grid, but there is no word "AAAAAAAAAAAAABB" in the grid. The running time of my code on this test is > 100 ms.

#### Code you used for Submit/Run operation

```
//79. Word Search
struct Cell{
        int row;
        int col;
};

class Solution {
private:
    vector<vector<int>> dirs = {{1, 0}, {0, 1}, {-1, 0}, {0, -1}};
    int m, n;
    
public:
    
    bool dfs(const vector<vector<char>>& board,
             vector<vector<int>>& used, int pos, const string& word,
             const Cell& c){

        if(pos == word.size() - 1 &&
           board[c.row][c.col] == word.back()){
            return true;
        }

        used[c.row][c.col] = 1;
        if(word[pos] == board[c.row][c.col]){
            
            for(auto& dir : dirs){
                int row = c.row + dir[0];
                int col = c.col + dir[1];
                if(row >= 0 && col >= 0 &&
                   row < m && col < n &&
                   used[row][col] == 0) {
                    if(dfs(board, used, pos + 1, word, Cell{row, col})){
                        return true;
                    }
                }
            }
        }
        used[c.row][c.col] = 0;
        return false;
    }
    bool exist(vector<vector<char>>& board, string word) {
        vector<Cell> starts;
        m = board.size();
        n = board[0].size();
        unordered_set<char> chars;
        for(int row = 0; row < m; ++row){
            for(int col = 0; col < n; ++col){
                if(board[row][col] == word[0]){
                    starts.push_back(Cell{row, col});
                }
                chars.insert(board[row][col]);
            }
        }
        
        //because of doing this check I avoid running word search itself 
        //even when running the hardest test so far (Number 46)
        
        for(auto& ch : word){
            if(chars.find(ch) == chars.end()){
                return false;
            }
        }
        
        //word search starts here
        
        vector<vector<int>> used(m, vector<int>(n));
        for(auto& start : starts){
            if(dfs(board, used, 0, word, Cell{start.row, start.col})){
                return true;
            }
        }
        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior

I believe there should be a stress test in order to make people think more about optimal solution, not just hacks such that I described above.

**Comment by lc-kay** [comment]
Hi @Maryia-M 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Maryia-M 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
