### ISSUE TITLE
Solution Error - 48. Rotate Image

### ISSUE THREAD

**Issue by joydeepnandi** [LeetCode-Feedback/LeetCode-Feedback#4083]
#### LeetCode username
[https://leetcode.com/itachi_23/] 

#### Category of the bug
- [ ] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution approach I used required the given matrix to be reversed. Let us consider a given matrix [[1,2,3],[4,5,6],[7,8,9]]. 
matrix=matrix[ : :-1] makes the matrix=> [[7,8,9],[4,5,6],[1,2,3]].
matrix.reverse() does the same. But I happen to get an error in the solution while using matrix=matrix[ : : -1]

#### Code you used for Submit/Run operation

```
class Solution:
    def rotate(self, a: List[List[int]]) -> None:
        """
        Do not return anything, modify matrix in-place instead.
        """

        a.reverse()
        for i in range(len(a)):
            for j in range(i+1,len(a)):
                a[i][j],a[j][i]=a[j][i],a[i][j]
```
The above solution returns a correct answer
```
class Solution:
    def rotate(self, a: List[List[int]]) -> None:
        """
        Do not return anything, modify matrix in-place instead.
        """

        a=a[::-1]
        for i in range(len(a)):
            for j in range(i+1,len(a)):
                a[i][j],a[j][i]=a[j][i],a[i][j]
```
The above solutions return a wrong answer
#### Expected behaviour

Both the above-mentioned solutions were supposed to run correctly. They give the correct answer and pass all the test cases on an online complier for python3

#### Screenshots

![Screenshot (14)](https://user-images.githubusercontent.com/80601095/124823574-001ab600-df8f-11eb-91ae-86d4f3b8df9c.png)
![Screenshot (13)](https://user-images.githubusercontent.com/80601095/124823590-0315a680-df8f-11eb-8c94-2a588dadfb77.png)

**Comment by lc-kay** [comment]
@joydeepnandi Please refer to this discuss post for further clarification: https://leetcode.com/problems/rotate-image/discuss/567036/Question%3A-matrix-matrix%3A%3A-1-vs-matrix%3A-matrix%3A%3A-1 Unfortunately, we are unable to troubleshoot the different behaviors from the LeetCode environment and local environment. Thank you for your understanding.
