### ISSUE TITLE
Wrong Test Case - 501. Find Mode in Binary Search Tree

### ISSUE THREAD

**Issue by AdrianaQyL** [LeetCode-Feedback/LeetCode-Feedback#4088]
#### Your LeetCode username

AnoCoder

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Invalid Test Cases 

#### Description of the bug

The test case [1,null,0,0,1,1,0] is not a valid BST. When I submit my code, it says I fail this case. When put in Testcase and run code, it says "Invalid Testcase: not a valid BST, Inorder traversal should be sorted in an ascending order." I think the alert sentence is right and it should not be in the test cases.

#### Code you used for Submit/Run operation

```
// Find Mode in Binary Search Tree
class Solution {
    private int maxCount = 0;
    private int count = 0;
    private TreeNode pre = null;
    List<Integer> res = new ArrayList<>();
    
    public int[] findMode(TreeNode root) {
        traverse(root);
        int[] resArr = new int[res.size()];
        for (int i = 0; i < res.size(); i++) {
            resArr[i] = res.get(i);
        }
        return resArr;
    }
    
    private void traverse(TreeNode root) {
        if (root == null) return;
        traverse(root.left);
        if (pre == null || root.val == pre.val) {
            count++;
        } else { // root.val != pre.val
            count = 1;
        }
        pre = root;
        if (count == maxCount) {
            res.add(root.val);
        }
        if (count > maxCount) {
            maxCount = count;
            res = new ArrayList<>();
            res.add(root.val);
        }
        traverse(root.right);    
    }
}
```

#### Language used for code

Java

#### Expected behavior

The test cases should be valid BSTs.

**Comment by lc-kay** [comment]
Hi @AdrianaQyL 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@AdrianaQyL Our team has fixed this issue previously. Thank you for your time.
