### ISSUE TITLE
Missing Test Case - 718. Maximum Length of Repeated Subarray

### ISSUE THREAD

**Issue by Yrajaram112** [LeetCode-Feedback/LeetCode-Feedback#4089]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The given input gives runtimes error wheras it runs perfectly in my online compiler

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int findLength(vector<int>& n1, vector<int>& n2) {
        int m = n1.size();
        int n = n2.size();
        vector<vector<int>> dp;
        for(int i=0;i<=m;i++){
            vector<int> v;
            for(int j=0;j<=n;j++){
                v.push_back(0);
            }
            dp.push_back(v);
        }
        
        for(int i=m-1;i>=0;i--){
            for(int j=n-1;j>=0;j--){
                if(n1[i]==n2[j]){
                    dp[j][i]=dp[j+1][i+1]+1;
                }
            }
        }
        int maxm=0;
        for(int i=0;i<m;i++)
            for(int j=0;j<n;j++){
                 maxm = max(maxm, dp[i][j]);
            }
        return maxm;
    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/62976679/124939182-88986580-e026-11eb-886f-30ddb1bc4595.png)

#### Additional context

![image](https://user-images.githubusercontent.com/62976679/124939236-92ba6400-e026-11eb-86dc-c8e2b39d4daa.png)

Whereas in my compiler it runs perfectly
![image](https://user-images.githubusercontent.com/62976679/124939362-a960bb00-e026-11eb-8452-26438a939dc5.png)

**Comment by lc-kay** [comment]
@Yrajaram112 Please check out these accepted codes in the problem discuss section https://leetcode.com/problems/maximum-length-of-repeated-subarray/discuss/?currentPage=1&orderBy=most_relevant&query=C%2B%2B Unfortunately, we are unable to troubleshoot the different behaviors between your local environment and the LeetCode environment. Thank you.
