### ISSUE TITLE
bug on 53. Maximum Subarray

### ISSUE THREAD

**Issue by betoleal** [LeetCode-Feedback/LeetCode-Feedback#409]
#### Your LeetCode username

betojulio

#### Category of the bug
- [ ] Question
- [* ] Solution
- [ ] Language

#### Description of the bug

When running my code with custom a test case, I believe the expected result is wrong.
#### Code you used for Submit/Run operation

```
class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        if not nums:
            return []
        cache = [0] * len(nums)
        cache[0] = nums[0]
        
        for index, val in enumerate(nums[1:], 1):
            max_val_in_subarray = cache[index-1]
            current_max_val = max(max_val_in_subarray + val, val)
            cache[index] = current_max_val
            
        return max(cache)
            
```

#### Language used for code

python3

#### Expected behavior
 I believe that the expected result from the input `[]` should be `[]` and not `-2147483648`

#### Screenshots

![image](https://user-images.githubusercontent.com/30603138/83576312-72ed6e00-a4ff-11ea-9d59-651d643fbe89.png)

**Comment by roll-no-1** [comment]
Maybe this input is invalid according to description of the problem statement: 
Given an integer array nums, find the contiguous subarray **(containing at least one number)** which has the largest sum and return its sum.

**Comment by CooperCooperCooper** [comment]
Hi @betoleal ,
Thank you for reaching out to us. The problem description states, "find the contiguous subarray (**containing at least one number**) which has the largest sum and return its sum." Hence the "Run Time" result looks weird when the input is "[]". Please update your input accordingly. 

Hat tip to @roll-no-1 for the feedback.
