### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by owem0410** [LeetCode-Feedback/LeetCode-Feedback#4090]
#### Your LeetCode username
owem0410

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
```python=
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """        
        if m == 0:
            nums1 = nums2       
        elif n == 0:
            pass
        else:
            nums1 = nums1[:m]
            nums2 = nums2[:n]
            nums1.extend(nums2)            
        nums1.sort()

```

#### Language used for code
Python3 

#### Expected behavior
The test case
```
[1,2,3,0,0,0]
3
[2,5,6]
3
```
I print the nums1 in the last. is 
```
[1, 2, 2, 3, 5, 6]
```
But Leetcode show 
```
Your answer
[1,2,3,0,0,0]
```

**Comment by lc-kay** [comment]
@owem0410 Our output of your code is correct. Please raise this issue in the problem discuss section for debugging support. Thank you for your time.
