### ISSUE TITLE
Wrong Test Case: Insert Delete GetRandom O(1)

### ISSUE THREAD

**Issue by SmritiRoy** [LeetCode-Feedback/LeetCode-Feedback#4091]
#### Your LeetCode username
Sm_7

#### Category of the bug

- [x] Wrong Test Cases 

#### Description of the bug
This problem asks to create a method **getRandom()** that returns a random element from the current set of elements (it's guaranteed that at least one element exists when this method is called). Each element must have the same probability of being returned. But when the test case ran it is failing if it doesn't match the expected answer. Ideally it could be any value from the current set of elements.

#### Code you used for Submit/Run operation

```
class RandomizedSet {
    private Map<Integer, Integer> map;
    private List<Integer> list;
    Random random = new Random();

    /** Initialize your data structure here. */
    public RandomizedSet() {
        map = new HashMap<>();
        list = new ArrayList<>();
    }
    
    /** Inserts a value to the set. Returns true if the set did not already contain the specified element. */
    public boolean insert(int val) {
        if (map.containsKey(val)) {
            return false;
        }
        map.put(val, list.size());
        list.add(list.size(), val);
        return true;
    }
    
    /** Removes a value from the set. Returns true if the set contained the specified element. */
    public boolean remove(int val) {
        if(!map.containsKey(val)) {
            return false;
        }
        
        int location = map.get(val);
        if(location < list.size() - 1) {
            int lastElement = list.get(list.size() - 1);
            map.put(lastElement, location);
            list.add(location, lastElement);
        }
        map.remove(location);
        list.remove(list.size() - 1);
        return true;
    }
    
    /** Get a random element from the set. */
    public int getRandom() {
    
        return list.get(random.nextInt(list.size()));
    }
}
```

#### Language used for code
Java

#### Expected behavior
The test case should not fail in case the getRandom() value returns a different value as expected in the output result.

#### Screenshots

<img width="1670" alt="Screen Shot 2021-07-08 at 9 58 59 PM" src="https://user-images.githubusercontent.com/45589932/124958365-b639da80-e037-11eb-94df-691a0779385a.png">

**Comment by lc-kay** [comment]
@SmritiRoy Please refer to the example 1 explanation on why the expected output is in that order. Thank you for your time.
