### ISSUE TITLE
Readme Updation

### ISSUE THREAD

**Issue by sudeepshukla930** [LeetCode-Feedback/LeetCode-Feedback#4092]
Hey,
I wanted to change some styling and update README in little new look..

Can i proceed  @Miloas  @lc-kay

**Comment by lc-kay** [comment]
Hi @sudeepshukla930 
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
