### ISSUE TITLE
Missing Test Case - 718. Maximum Length of Repeated Subarray

### ISSUE THREAD

**Issue by eloiman** [LeetCode-Feedback/LeetCode-Feedback#4093]
#### Your LeetCode username
ssdevel

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing case with subarray length 1.
[1,2,3,2,8]
[5,6,1,4,7]

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int findLength(vector<int>& nums1, vector<int>& nums2) {
        const auto N1 = nums1.size();
        const auto N2 = nums2.size();
        
        int mx = 0;
        vector<vector<int>> dp(N2, vector<int>(N1, 0));
        
        for (int i = 0; i < N1; ++i) {
            if (nums1[i] == nums2[0]) dp[0][i] = 1;
        }
        
        for (int j = 0; j < N2; ++j) {
            if (nums2[j] == nums1[0]) dp[j][0] = 1;
        }
        
        for (int i = 1; i < N1; ++i) {
            for (int j = 1; j < N2; j++) {
                if (nums2[j] == nums1[i]) {
                    auto newDp = dp[j-1][i-1] + 1;
                    if (dp[j][i] < newDp) {
                        dp[j][i] = newDp;
                        mx = max(mx, newDp);
                    }
                }
            }
        }
        
        return mx;
    }
};
```

#### Expected behavior
Expectedly it should fail, because it doesn't process case when subarray has size 1. It's passed successfully. However it's fail if it's run manually via 'Run Code' with the provided custom testcase.

**Comment by lc-kay** [comment]
Hi @eloiman 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @eloiman 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
