### ISSUE TITLE
Missing Test Case - 704. Binary Search

### ISSUE THREAD

**Issue by UdayKiranPadhy** [LeetCode-Feedback/LeetCode-Feedback#4098]
#### Your LeetCode username
IamUday

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The given question is Binary Search , the expected time complexity is O(logn) , but even if i submit a O(n) solution it's getting accepted. So the test cases and constraints requires a bit modification.

#### Code you used for Submit/Run operation
```
class Solution:
    def search(self, nums: List[int], target: int) -> int:
        for i in range(len(nums)):
            if nums[i]==target:
                return i
        return -1
```

#### Language used for code
Python

#### Expected behavior
I except a Time Limit exceed Error but its getting accepted.

**Comment by hackifme1** [comment]
I think this is because of constraints. If array length would be of order or higher 10^8, then only O(n) will not pass.

**Comment by lc-kay** [comment]
Hi @UdayKiranPadhy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hackifme1 We cannot force the log(n) solutions because the driver reads the input array in O(n).
Since this is a practice problem, the user can submit O(n) solution but in the interview, the user will be required to find the O(log(n)) solution. Thank you for your understanding.
