### ISSUE TITLE
300. Longest Increasing Subsequence

### ISSUE THREAD

**Issue by adrikagupta** [LeetCode-Feedback/LeetCode-Feedback#4099]
#### Your LeetCode username

adrikagupta22

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Approach 2: Intelligently Build a Subsequence, it is written
*Time complexity: O(N^2) The worst case is when the input is strictly increasing. *
But when the input is strictly increasing, the time complexity is O(N). So, it is not the worst-case scenario.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

**Comment by lc-kay** [comment]
Hi @adrikagupta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @adrikagupta 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
