### ISSUE TITLE
Test case contribution for 1208. Get Equal Substrings Within Budget

### ISSUE THREAD

**Issue by dheeraj2645** [LeetCode-Feedback/LeetCode-Feedback#410]
Note - Any content mention below in `<!-- ->` blocks are just comments
to help you fill up the issue. It won't be visible in actual issue after
you click on submit.

#### Your LeetCode username
Dheeraj2645

#### Category of the bug
- [ ] Question
- [ - ] Solution
- [ ] Language

#### Description of the bug
 A test case is showing wrong answer from expected answer for my code.Which is succesfully got submitted.This indicates this test case is being missed in your test cases.So i want you to include this test case. 

#### Code you used for Submit/Run operation

```
// Get Equal Substrings Within Budget.

class Solution {
public:
    int equalSubstring(string s, string t, int maxCost) {
        if(maxCost==0)
        {return 1;}
        int n = s.size();
        vector<long> cost(n);
        for(int i=0;i<n;++i) {cost[i] = abs(s[i]-t[i]);}
        int maxx = -1000000;
        int summ = 0;
        int j = 0;
        for(int i=0;i<n;++i){
            summ+=cost[i];
            while (summ>maxCost) {
                summ-=cost[j++];
            }
            if(i-j+1>maxx){maxx = i-j+1;}
        }
        return maxx;
    }
};

```

#### Language used for code
C++ 

#### Expected behavior
 For the condition maxCost=0,Your test cases are limited to only output 1,If i have used a test case with output more than 1 and maxCost=0,The output still shows as 1 in my code.
test case: 
Input: s="abcd",t="abcd",maxCost=0.
expected output: 4.
acutal output from my code: 1.
Input: s="pqrsa",t="pbrka",maxCost=0.
expected output: 3.
acutal output from my code: 1.

#### Screenshots
![image](https://user-images.githubusercontent.com/66384202/83686168-62281f80-a607-11ea-8555-371247a16069.png)
![image](https://user-images.githubusercontent.com/66384202/83686224-7a983a00-a607-11ea-944a-2d7688b5bafd.png)

**Comment by CooperCooperCooper** [comment]
Hi @dheeraj2645 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @dheeraj2645 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
