### ISSUE TITLE
Binary search solution for 163. Missing Ranges

### ISSUE THREAD

**Issue by KartikeyaPophali** [LeetCode-Feedback/LeetCode-Feedback#4101]
#### Your LeetCode username

Kartikeya_Pophali

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

Missing Approach - Binary search

#### Description of the bug

https://leetcode.com/problems/missing-ranges/
Missing ranges problem can potentially be solved more efficiently using binary search. Even though the worst case time complexity would still be the same as linear scan i.e. O(n), the potential complexity could be reduced to O(log(n)) using binary search.

#### Code you used for Submit/Run operation

```
# Find missing ranges
class Solution:
    def findMissingRanges(self, nums: List[int], lower: int, upper: int) -> List[str]:
        def print_missing(num_lo, num_hi):  # num_lo, num_hi not to be printed
            if num_lo + 1 == num_hi:    # if adjacent numbers, print nothing
                return
            if num_lo + 2 == num_hi:    # if one number in between, print only that
                out.append(f"{num_lo+1}")
            else:                       # else print range
                out.append(f"{num_lo+1}->{num_hi-1}")
        
        def search_missing(lo, hi):
            if lo + 1 == hi:            #   if adjacent indices eg. 0,1
                if nums[lo] + 1 == nums[hi]:    # if adjacent numbers eg. 11,12, do nothing
                    return
                print_missing(nums[lo], nums[hi])   # else print missing range
                return
                
            mid = lo + (hi - lo) // 2   
            # first search left region so that the order of printing in out list is correct
            if nums[mid] - nums[lo] > mid - lo: # nums difference > indices difference
                search_missing(lo, mid)         # eg. nums[0] = 0, nums[4] = 8   ==> numbers are missing
                
            # search right region after left in order to maintain print order in out list
            if nums[hi] - nums[mid] > hi - mid:
                search_missing(mid, hi)         # eg. nums[4] = 8, nums[8] = 16  ==> numbers are missing
                
            # if nums[mid] - nums[lo] == mid - lo:  # if nums difference == indices difference
            #   do nothing!                         # no numbers are missing
                
            # if nums[hi] - nums[mid] == hi - mid:  # if nums difference == indices difference
            #   do nothing!                         # no numbers are missing
            
            # if nums[mid] - nums[lo] < mid - lo:   # impossible condition! array is 'sorted unique'
            
            # if nums[hi] - nums[mid] < hi - mid:   # impossible condition! array is 'sorted unique'
            
        
        out = []
        if len(nums) == 0:
            print_missing(lower-1, upper+1)
            return out
        
        print_missing(lower-1, nums[0])
        search_missing(0, len(nums)-1)
        print_missing(nums[-1], upper+1)
        
        return out
```

#### Language used for code

Python 3

#### Expected behavior

In the Solution section, only one approach is given i.e. Linear scan with time complexity O(n)
This problem can be solved with binary search too.
e.g. nums = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,21,24] , lower = 0, upper = 25
out = ["0",  "15->20", "22->23", "25"]

If the above test case is solved using the given binary search code given above, we can skip unnecessarily searching certain regions, thus potentially reducing the time taken
i.e. search_missing(0, 15) would be called from the main function
therefore, lo=0, nums[0]=1,  mid=7  and nums[7]=8
in this if condition -->    if nums[mid] - nums[lo] > mid - lo: 
we get, if 8-1 > 7-0  ......... which is False, so we never search the region left of it and hence ~half of nums range won't be unnecessarily processed.

The worst case time complexity would still be O(n) (if all (i, i+1) intervals get searched), but we would atleast be doing much better than linear time in some scenarios, like the example provided above.

**Comment by lc-kay** [comment]
Hi @KartikeyaPophali 
Thank you for reaching out to us. I've relayed this issue to our team to investigate. As this may take some time to implement, I will close this ticket for now and reopen it if more information is needed. Thank you for your time.
