### ISSUE TITLE
题目 501.二叉搜索树中的众数 有个用例不对 

### ISSUE THREAD

**Issue by jneee** [LeetCode-Feedback/LeetCode-Feedback#4102]
**jun-nan**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ x] 缺少测试用例

**描述**
描述你遇到的 bug
题目 二叉搜索树中的众数 有个用例不对 
https://leetcode-cn.com/problems/find-mode-in-binary-search-tree/

 `[1,null,0,0,1,1,0]` 不是个二叉搜索树  

**你使用的语言**
python

**你提交或者运行的代码**
```
class Solution:
    def findMode(self, root: TreeNode) -> List[int]:
        def dfs(node):
            if node == None:
                return 
            dfs(node.left)
            update(node.val)
            dfs(node.right)
        global base, count, max_count, res
        count = 0
        max_count = 0
        base = None
        res = []
        def update(val):
            global base, count, max_count, res
            if base == val:
                count += 1
            else:
                base = val
                count = 1

            if count == max_count:
                res.append(val)
            elif count > max_count:
                res = [val]
                max_count = count

        dfs(root)
        return res
```

**期望行为**
删除错误用例

**屏幕截图**  
 `[1,null,0,0,1,1,0]` 不是个二叉搜索树    
![网页捕获_9-7-2021_23389_leetcode-cn com](https://user-images.githubusercontent.com/27620242/125103308-ccff3080-e10e-11eb-9518-a105c5500829.jpeg)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@jneee  你好，当前问题已经修复，ID：jun-nan 给予积分奖励，请查收。
