### ISSUE TITLE
Wrong Test Case in sample input - 396. Rotate Function

### ISSUE THREAD

**Issue by Namdev01** [LeetCode-Feedback/LeetCode-Feedback#4104]
#### Namdev01

#### Category of the bug
Wrong Sample Test Case

#### Description of the bug
In Example 2 the value of **nums vector element** is invaild.
In Problem Constraints clearly mention that -100 <= nums[i] <= 100 but in example test case take the value equal to 1000000007.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int maxRotateFunction(vector<int>& nums) {
        int sum=0,n=nums.size();
        for(auto u: nums) sum+=u;
        int res=0;
        for(int i=0;i<n;i++)
        {
            res+=i*nums[i];
        }
        int ans=res;
        for(int i=0;i<n;i++)
        {
            ans=ans-sum+n*nums[i];
            res=max(res,ans);
            // cout<<ans<<endl;
        }
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior

I want only for remove the example test case or change the value of 2nd example testcase

**Comment by lc-kay** [comment]
Hi @Namdev01 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Namdev01 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
