### ISSUE TITLE
Description constraints are inaccurate for question 10. Regex Matching

### ISSUE THREAD

**Issue by juan7732** [LeetCode-Feedback/LeetCode-Feedback#4105]
#### Your LeetCode username
juan7732

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Constraints are not valid, the length of s or p cannot be >= 0 and then say that s and p can only contain lowercase letters, and in p also the '.' and '*' character. This is a contradiction as if you have an empty string in either, the description does not provide information on what the expected behavior is and also violates the content constraint.

Should be just > than 0, not >=

#### Code you used for Submit/Run operation

```
Not Applicable
```

#### Language used for code
All Languages

#### Expected behavior
Clear description and constraints

#### Screenshots
![image](https://user-images.githubusercontent.com/19902389/125149793-acc87500-e100-11eb-91d9-f16ef6e38d60.png)

#### Additional context
Not Applicable

**Comment by lc-kay** [comment]
Hi @juan7732 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@juan7732 Our team has removed the confusing test cases. Thank you for your time.
