### ISSUE TITLE
Missing Test Case - 639. Decode Ways II

### ISSUE THREAD

**Issue by SouravKabiraj** [LeetCode-Feedback/LeetCode-Feedback#4106]
#### Your LeetCode username
SouravKabiraj

#### Category of the bug
- [ ] Question : Decode Ways II
- [x] Missing Test Cases : Wrong Test cases s = "2*" should return 16

#### Description of the bug
TEST CASE 3: 
The encoded message can represent any of the encoded messages "21", "22", "23", "24", "25", "26", "27", "28", or "29".
"21", "22", "23", "24", "25", and "26" have 2 ways of being decoded, but "27", "28", and "29" only have 1 way.
Hence, there are a total of (6 * 2) + (3 * 1) = 12 + 3 = 15 ways to decode "2*".

BUT YOU GUYS MISSED THAT IT CAN BE "20" also

**Comment by stormsunshine** [comment]
Please read the problem description carefully. The `'*'` character can represent any digit from `'1'` to `'9'`. **Digit `'0'` is excluded.**
Before you create an issue, please make sure your understanding is correct.

**Comment by lc-kay** [comment]
@SouravKabiraj Please refer to @stormsunshine explanation or the problem discuss section for further clarification. Thank you for your time.
