### ISSUE TITLE
639. Decode Ways II

### ISSUE THREAD

**Issue by satanTime** [LeetCode-Feedback/LeetCode-Feedback#4107]
#### Your LeetCode username
satanTime

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description of the question says `Given a string s containing digits and the '*' character`, what means it can contain one `character` IMO, whereas there is a test case `**`.
Therefore I would propose to clarify that with the replacement to `characterS`.

#### Expected behavior
The description should use plural `Given a string s containing digits and the '*' characters`.

**Comment by lc-kay** [comment]
Hi @satanTime 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @satanTime 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
