### ISSUE TITLE
811. Subdomain Visit Count, Solution is Not Working

### ISSUE THREAD

**Issue by priyanshu-arya** [LeetCode-Feedback/LeetCode-Feedback#4108]
#### Category of the bug
- [ *] Solution

#### Description of the bug

Given Solution of Python is Showing Error. 

```
class Solution(object):
    def subdomainVisits(self, cpdomains):
        ans = collections.Counter()
        for domain in cpdomains:
            count, domain = domain.split()
            count = int(count)
            frags = domain.split('.')
            for i in xrange(len(frags)):
                ans[".".join(frags[i:])] += count

        return ["{} {}".format(ct, dom) for dom, ct in ans.items()]
```

#### Language used for code
 Python 3 

#### Expected behavior
 It can Run while testing but it doesn't.

**Comment by lc-kay** [comment]
<img width="1919" alt="Screen Shot 2021-07-12 at 11 56 41 AM" src="https://user-images.githubusercontent.com/70870126/125341209-3ac27c80-e308-11eb-8379-13d07c66f73e.png">
The solution is running as expected. Please note that this solution is in Python, not Python3. Thank you for your time.
