### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by JialinC** [LeetCode-Feedback/LeetCode-Feedback#4109]
#### Your LeetCode username

improving

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Based on the question description, [3,2,1,2,1] would be a valid test case. The solution does not give the correct answer to this case. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@JialinC Please provide the accepted code that fails on this test case. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @JialinC 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
