### ISSUE TITLE
Poorly Worded Question - 1221. Split a String in Balanced Strings 

### ISSUE THREAD

**Issue by KamiFightingSpirit** [LeetCode-Feedback/LeetCode-Feedback#411]
#### Your LeetCode username

DeHuff

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ X ] Language

#### Description of the bug

Given the definition of balanced string :  "Balanced strings are those who have equal quantity of 'L' and 'R' characters." 
The user is asked : "Return the maximum amount of splitted balanced strings."

Example 4 provides:
Input: s = "RLRRRLLRLL"
Output: 2

However, within our constraints the answer should be 3. [RL, RL, LR] at indices [[0,1],[4,5],[6,7]].
An additional conditional should state that all characters must be used in order for the answer of 2 to be true.

#### Code you used for Submit/Run operation

```
// Two Sum
var balancedStringSplit = function(s) {
    let counter = new Number();
    for(let i = 0; i < s.length-1; i++){
      s[i] !== s[i+1] ? (counter++, i++) : void 0; 
    }
    return counter;
};

let s = "RLRRRLLRLL"
console.log(balancedStringSplit(s));
```

#### Language used for code

Javascript

#### Expected behavior

Provided answer of 3, answer of 2 was expected

**Comment by CooperCooperCooper** [comment]
Hi @KamiFightingSpirit ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @KamiFightingSpirit 
Thank you again for reaching out to us. After our discussion with the team, we decided not to update the problem statement. As the users should be able to tell all characters must be used in order from example 4. Thanks for your support and please let me know if you have any other questions.
