### ISSUE TITLE
Missing Test Case - 378. Kth Smallest Element in a Sorted Matrix

### ISSUE THREAD

**Issue by vyash5075** [LeetCode-Feedback/LeetCode-Feedback#4110]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by vyash5075** [comment]
please check

**Comment by lc-kay** [comment]
@vyash5075 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
