### ISSUE TITLE
Missing Test Case - 1928. Minimum Cost to Reach Destination in Time

### ISSUE THREAD

**Issue by worcdlo** [LeetCode-Feedback/LeetCode-Feedback#4111]
#### Your LeetCode username
yan_wei_zhe

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

It's my accepted answer during biweekly contest 56.
I limited the maximum time to each node by Dijkstra method which started from n-1 and sorted by time.
But it was wrong because it would just check the first meeted possible answer on each node.

#### Code you used for Submit/Run operation

``` Python
from heapq import heappop, heappush

class Solution:
    def minCost(self, maxTime: int, edges: List[List[int]], passingFees: List[int]) -> int:
        n = len(passingFees)
        adj = defaultdict(list)
        for x, y, t in edges:
            adj[x].append([y, t])
            adj[y].append([x, t])
            
        min_times = dict()
        
        queue = [[0, n-1]] # t, 0
        while queue:
            time, idx = heappop(queue)
            if time > maxTime:
                continue
            if idx in min_times:
                continue
            min_times[idx] = time
            for nxt, t in adj[idx]:
                heappush(queue, [t + time, nxt])
        if 0 not in min_times or min_times[0] > maxTime:
            return -1
        
        queue = [[passingFees[0], 0, maxTime]]
        seen = set()
        while queue:
            cost, idx, time = heappop(queue)
            if idx in seen or idx not in min_times or time < min_times[idx]:
                continue
            if idx == n - 1:
                return cost
            seen.add(idx)
            for nxt, t in adj[idx]:
                heappush(queue, [cost + passingFees[nxt], nxt, time - t])
        return -1
        
        
```

#### Language used for code

Python

#### Expected behavior

As following screenshot, my answer got 104 but the answer is 27.
Test case:
```
maxTime: 10
edges: [[0,1,2],[0,2,1],[2,3,2],[1,3,3],[3,4,2],[3,5,3],[4,6,3],[5,6,4]]
passingFees: [1,3,6,1,98,18,1]
```

#### Screenshots

![image](https://user-images.githubusercontent.com/37761249/125172998-4ff7b800-e1ef-11eb-9960-827324035aa5.png)

#### Additional context

Even I will be dropped out of top 100 rank, I think it still should be rejudged.
Moreover, I had experienced rejudges and been dropped rank for many times, but if the test cases are robust enough, I think I would have chance to solve them during the contest except being rejudged.

**Comment by lc-kay** [comment]
Hi @worcdlo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @worcdlo 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
