### ISSUE TITLE
Missing Test Case - 1927. Sum Game

### ISSUE THREAD

**Issue by Alzayady** [LeetCode-Feedback/LeetCode-Feedback#4112]
#### Your LeetCode username
zayadi 

#### Category of the bug
-  Missing Test Cases 

#### Description of the bug
test cases doesn't test if the sum of one side is more than the other side , it only test for minimum and equal sum.

#### Code you used for Submit/Run operation

```
\\ sumGame
class Solution {
public:
    bool sumGame(string num) {
        int sl = 0 ;
        int sr = 0 ;
        int ll  = 0 ;
        int lr = 0 ;
        int n = num.size();
        for(int i = 0; i < n /2 ; i ++){
            if(num[i] == '?'){
                ll ++;
            }else{
                sl+=num[i] -'0';
            }
        }
        for(int i = n/2 ; i< n ; i++){
            if(num[i] == '?'){
                lr ++;
            }else{
                sr +=num[i] - '0';
            }
        }        
        if(sl == sr){
            if(ll == lr){
                return false;
            }
        }
        int dif = min(sl , sr );
        sl-=dif;
        sr-=dif;
        int m =min(ll,lr);
        ll-=m ;
        lr -=m;
        if(sl>sr){
            if(ll){
                return true;
            }
        }else{
            if(lr){
                return true;
            }
        }
        if(max(ll,lr) % 2 == 1 ){
            return true;
        }
        dif = max(sl,sr);
        if(max(ll,lr) * 9 / 2 < dif)return true;
        if(dif % 9 == 0  ){
            return false;
        }
        return true;
        
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
test   "009900??????"  it must output false and my output is true , but i got accepted .

#### Screenshots

![Screenshot from 2021-07-10 20-39-40](https://user-images.githubusercontent.com/45363985/125173314-00999380-e1bf-11eb-83e1-820ef533bb79.png)

**Comment by lc-kay** [comment]
Hi @Alzayady 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Alzayady The provided solution now fails on a recently added test case. Therefore, we will not add the test case you have provided. Thank you for your time.
