### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by rituraj510** [LeetCode-Feedback/LeetCode-Feedback#4113]
#### Your LeetCode username

rituraj510

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Missing one test case i.e. a string containing only opening parentheses.

#### Code you used for Submit/Run operation

```
// Valid Parentheses
class Solution:
    def isValid(self, s: str) -> bool:
        stack = []
        for i in s:
            if (i in ['(', '{', '[']):
                stack.append(i)
            else:
                if (len(stack) == 0):
                    return False
                else:
                    if ((i == ')') and (stack[-1] == '(')):
                        stack.pop()
                    elif ((i == '}') and (stack[-1] == '{')):
                        stack.pop()
                    elif ((i == ']') and (stack[-1] == '[')):
                        stack.pop()
                    else:
                        return False
        if (len(stack) == 0):
            return True
```

#### Language used for code
Python3

#### Expected behavior
Suppose a string contains only opening parentheses then my code should fail.
i.e. if s = '((({[(', then my code should not pass, but as there is no such test cases present my code passed all the test cases.
My code only checks whether the stack is empty after coming out of for loop and returns true if empty but there is no else statement in my code. If we consider string s = '((({[(', then my code should not pass for this string.
So, Please include one test case where the string should contain only opening parentheses (something like '[[[{{') so that the code which will not consider this scenario should fail.

**Comment by lc-kay** [comment]
<img width="1362" alt="Screen Shot 2021-07-12 at 12 00 21 PM" src="https://user-images.githubusercontent.com/70870126/125341675-bd4b3c00-e308-11eb-813a-eba0d1a309bc.png">
Your code runs fine and is accepted for the test case you've provided. For a valid missing test case report, please provide an accepted code and will fail on your custom test case. Thank you for your time.
