### ISSUE TITLE
62. Unique Paths - Error in execution only when pressing "Submit" for same input that succeeds when clicking "Run code".

### ISSUE THREAD

**Issue by malopez16** [LeetCode-Feedback/LeetCode-Feedback#4114]
#### Your LeetCode username
--

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For some reason this code has issues running when pressing submit.
For the input 3,2, it fails when pressing submit, but it doesn't fail when using the same input as a testcase. It also doesn't show the same output as when clicking "Submit" when running it on my own IDE. The correct answer is 3, as in the debug testcase. 

#### Code you used for Submit/Run operation
```
class Solution:
    memo = {}
    
    def uniquePaths(self, m: int, n: int) -> int:
        l_y = m-1
        l_x = n-1
        return self.get_all(0,0, l_y, l_x)
    
    
    def get_all(self, y, x, l_y, l_x):
        if (y==l_y) and (x==l_x):
            return 1
        down = 0
        if y < l_y:
            down = self.get_all(y+1, x, l_y, l_x)
        right = 0
        if x < l_x:
            right = self.get_all(y, x+1, l_y, l_x)
        if not (y,x) in self.memo:
            self.memo[(y,x)] = down+right
        return self.memo[(y,x)]
```

#### Language used for code
Python

#### Expected behavior
Result when clicking "submit" should be 3, for the testcase "3,2", same as when inputting the same testcase when clicking "Run code" with input "3,2), which is what happens on any IDE. For some reason, it doesn't work on leetcode and it throws a different number out.

#### Screenshots
![image](https://user-images.githubusercontent.com/26126519/125179790-b4028800-e1bf-11eb-8c4a-1a23bc582afd.png)

**Comment by lc-kay** [comment]
Hi @malopez16 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
