### ISSUE TITLE
Missing Test Case - 1926. Nearest Exit from Entrance in Maze

### ISSUE THREAD

**Issue by lagagain** [LeetCode-Feedback/LeetCode-Feedback#4115]
#### Your LeetCode username
lagagain

#### Category of the bug
- [X] Missing Test Cases 

#### Description of the bug

Below case is missing.  Some codes run the case fail, but submit approve.

```
[["+","+","+","+","+","+","+","+","+","+"],["+",".",".",".",".",".",".",".",".","."],["+",".","+","+","+",".","+",".","+","+"],["+",".","+","+","+",".","+",".","+","+"],["+",".","+","+","+",".","+",".","+","+"],["+",".","+","+","+",".","+",".","+","+"],["+",".","+","+","+",".","+",".","+","+"],["+",".","+","+","+",".","+",".","+","+"],["+",".","+","+",".",".","+",".","+","+"],["+",".","+","+","+",".","+",".","+","+"],["+",".","+","+","+",".","+",".","+","+"],["+",".","+","+","+",".","+","+","+","+"],["+",".","+","+","+",".","+","+","+","+"],["+",".",".",".",".",".","+","+","+","+"],["+","+","+","+","+","+","+","+","+","+"]]
[8, 5]
```

#### Code you used for Submit/Run operation

```javascript
/**
 * @param {character[][]} maze
 * @param {number[]} entrance
 * @return {number}
 */
var nearestExit = function(maze, entrance) {
    const dp = new Array(maze.length).fill(0).map(item=> new Array(maze[0].length).fill(-1))
    const [sI, sJ] = entrance
    maze[sI][sJ] = "e"
    function dfs(i, j){
        if(i < 0 || i > maze.length-1 || j < 0 || j > maze[0].length-1 || maze[i][j] === "+") return Infinity
        if((i === 0 || i === maze.length-1 || j === 0 || j === maze[0].length-1) && maze[sI][sJ] !== "e"){
            return 0
        }
        if(dp[i][j] !== -1) return dp[i][j]
        maze[i][j] = "+"
        const minStep = Math.min(dfs(i+1, j), dfs(i-1, j), dfs(i, j+1), dfs(i, j-1))+1
        maze[i][j] = "."
        dp[i][j] = minStep
        return dp[i][j]
    }
    const min = dfs(sI, sJ)
    return min >= Infinity ? -1 : min
};
```
https://leetcode.com/problems/nearest-exit-from-entrance-in-maze/discuss/1329305/Why-exchange-i-and-j-position-will-be-wrong

#### Language used for code
javascript

#### Expected behavior
This case and like cases should be fail when submitted.

#### Screenshots

Submit successfully

![圖片](https://user-images.githubusercontent.com/26619182/125177864-e8069900-e211-11eb-9e69-fd1abcab569b.png)

Run the special case fail

![圖片](https://user-images.githubusercontent.com/26619182/125177883-0a98b200-e212-11eb-88b6-10840f4b84c5.png)

#### Additional context
Visualize special case
![圖片](https://user-images.githubusercontent.com/26619182/125177943-a1fe0500-e212-11eb-9346-d7dec0e0e99d.png)

**Comment by lagagain** [comment]
![圖片](https://user-images.githubusercontent.com/26619182/125177933-8bf04480-e212-11eb-8f04-b2d67e93608a.png)

**Comment by waliamehak** [comment]
Would you know why is this so? where is the fault with the dfs code?

**Comment by waliamehak** [comment]
Could somebody please look at this code and find out the fault with dfs?
`
 class Solution {
public:
    vector<vector<int>> visited;
    int X, Y;
    vector<pair<int, int>> directions { {1, 0}, {-1, 0}, {0, 1}, {0, -1}};    
     int dfs( int x, int y, vector<vector<char>>& maze){ //cout<<x<<"  "<<y<<"  "<<endl;
        if(x<0 || y<0 || x>=maze.size() || y>=maze[0].size() || maze[x][y]=='+'|| visited[x][y]==-1) return INT_MAX;
        if(x==0 || y==0 || x== (maze.size()-1) || (y== (maze[0].size()-1))) {
            if (!(x==X && y==Y))// return INT_MAX;
                return 0;
        }
        if(visited[x][y])return visited[x][y];
        visited[x][y]=-1;
        int len = INT_MAX;
        for ( auto & dir: directions){
            int xx = x+ dir.first;
            int yy  = y + dir.second;
            int ans = dfs(xx, yy, maze);
         //   cout<<ans<<"  "<<x<<"  "<<y<<endl;
            len = min (ans, len);
        }
        if(len == INT_MAX) return visited[x][y]=INT_MAX;
        return visited[x][y] = len +1;
    }
    int nearestExit(vector<vector<char>>& maze, vector<int>& entrance) {
        visited.resize(maze.size(), vector<int>(maze[0].size(), 0) );
        X = entrance[0]; Y= entrance[1];
        int anss = dfs (entrance[0], entrance[1], maze); //cout<<anss;
        return  anss== INT_MAX? -1: anss;
    }
};
`

**Comment by lagagain** [comment]
@waliamehak 

![image](https://user-images.githubusercontent.com/26619182/125180578-2d38c400-e22e-11eb-95a4-85921be02a65.png)

**Comment by waliamehak** [comment]
@lagagain Much appreciated, thank you! Takeaway: we cannot find the shortest path using O(E+V) time

**Comment by lagagain** [comment]
@waliamehak 
Excuse me, how to calculate the result - O(E+V) time ? 

----------

 I think it is possible or very similar, but should change way.  I had write a other solution: https://leetcode.com/problems/nearest-exit-from-entrance-in-maze/discuss/1329860/Python-with-A%2A

**Comment by lc-kay** [comment]
Hi @lagagain 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @lagagain 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by affanrahman0** [comment]
Finally understood . Thanks a lot!
