### ISSUE TITLE
Missing Test Case - 1901. Find a Peak Element II

### ISSUE THREAD

**Issue by CherishHack** [LeetCode-Feedback/LeetCode-Feedback#4118]
#### Your LeetCode username
Hammer001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing Test case: `[[7,2,3,1,2],[6,5,4,2,1]]`

#### Code you used for Submit/Run operation
```
class Solution:
    def search(self, mat, lo, hi):
        if lo > hi:
            return None
        
        mid = (lo + hi) >> 1
        
        left, right = 0, len(mat[mid]) - 1
        
        while left < right:
            m = (left + right) >> 1

            if m+1 < len(mat[mid]) and mat[mid][m] < mat[mid][m+1]:
                left = m + 1
            else:
                right = m
        
        m = left
        
        if (mid == 0 or mat[mid][m] >= mat[mid-1][m]) and (mid == len(mat)-1 or mat[mid][m] >= mat[mid+1][m]):
            return [mid, m]
        if mid != 0 and mat[mid][m] < mat[mid-1][m]:
            return self.search(mat, lo, mid - 1)
        else:
            return self.search(mat, mid+1, hi)
            
            
        return None
        
    def findPeakGrid(self, mat: List[List[int]]) -> List[int]:
        return self.search(mat, 0, len(mat))
```

#### Language used for code
Py3

#### Expected behavior
My submission should get WA, but AC. 

#### Additional context
Please add test case `[[7,2,3,1,2],[6,5,4,2,1]]`

**Comment by CherishHack** [comment]
The reason of being wrong is: when search in a row, I am still using binary search to find a local Peak. That's wrong. I should use linear scan to find the greatest value in a row.

**Comment by lc-kay** [comment]
Hi @CherishHack 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @CherishHack 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
