### ISSUE TITLE
Leetcode 639 - Decode Way II

### ISSUE THREAD

**Issue by spattk** [LeetCode-Feedback/LeetCode-Feedback#4119]
#### Your LeetCode username

siteshpattanaik001

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Expected behavior

Thus, this 1* pair could be replaced by any of the numbers from 11-19 irrespective of the decodings done for the previous indices(before i-1i−1). Thus, this 1* pair leads to **_9 times_** the number of decodings possible with the string ss upto the index i-2i−2. Thus, this adds a factor of 9 * ways(s, i - 2) to the total number of decodings.

```Note: Mark the 9 times```

#### Screenshots

[Error Screenshot](https://drive.google.com/file/d/190Va9ob681SPxWKAfe8iOxUMD-XMgY8c/view?usp=sharing)

**Comment by lc-kay** [comment]
Hi @spattk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @spattk 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
