### ISSUE TITLE
178. Rank Scores is incorrect after introduction rank() function to MySQL

### ISSUE THREAD

**Issue by qwazimoda** [LeetCode-Feedback/LeetCode-Feedback#412]
#### Your LeetCode username
dyurchyk

#### Category of the bug
- [x ] Question
- [ x] Solution
- [ ] Language

#### Description of the bug

In the question, it is asked to provide results with Score and Rank headers. But there is rank() function in MySQL 8, which makes the question impossible to solve due to syntax error (Rank alias can't be used). Also, it breaks expected results, they are blank now. Please refer to the attached screenshots for the illustration.
Additionally, you might want to introduce clarification into the question, that the intent is to get ranking without the usage of build it functions. Since the question is easily solvable using them.

#### Code you used for Submit/Run operation
No code was submitted

#### Language used for code

MySQL

#### Expected behavior

1. The expected results work
2. The expected header is renamed (not Rank)

#### Screenshots

![screenshot](https://user-images.githubusercontent.com/19476580/83710436-be327a00-a5ee-11ea-80db-92d25a5cc9ab.png)
![screenshot2](https://user-images.githubusercontent.com/19476580/83710440-becb1080-a5ee-11ea-8653-bc64bb626076.png)
![screenshot3](https://user-images.githubusercontent.com/19476580/83710441-becb1080-a5ee-11ea-823c-d4a36648c0bf.png)
![screenshot4](https://user-images.githubusercontent.com/19476580/83710444-becb1080-a5ee-11ea-837c-00d7d8920085.png)

#### Additional context

There is a similar issue submitted in Chinese, which was closed without proper investigation - https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/317

**Comment by CooperCooperCooper** [comment]
Hi @qwazimoda ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @qwazimoda ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
