### ISSUE TITLE
LeetCode，Problem 232

### ISSUE THREAD

**Issue by ZichengQu** [LeetCode-Feedback/LeetCode-Feedback#4120]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ x] 缺少测试用例

**描述**
LeetCode，232题，缺少测试用例，peek或pop之后，再push的元素位置可能不对，但仍能通过检测。

**你使用的语言**
Java

**你提交或者运行的代码**
```
class MyQueue {
    private Deque<Integer> stack;
    private Deque<Integer> util;
    /** Initialize your data structure here. */
    public MyQueue() {
        stack = new LinkedList<>();
        util = new LinkedList<>();
    }
    
    /** Push element x to the back of queue. */
    public void push(int x) {
        stack.offerLast(x);
    }
    
    /** Removes the element from in front of queue and returns that element. */
    public int pop() {
        peek();
        int res = stack.pollLast();
        while(util.size() > 0){
            stack.offerLast(util.pollLast());
        }
        return res;
    }
    
    /** Get the front element. */
    public int peek() {
        while(stack.size() > 1){
            util.offerLast(stack.pollLast());
        }
        return stack.peekLast();
    }
    
    /** Returns whether the queue is empty. */
    public boolean empty() {
        return stack.isEmpty();
    }
}
```

**期望行为**
这段代码不应通过LeetCode所有的测试案例。比如测试中应添加类似于下述案例
["MyQueue","push","push","peek","push","pop","peek","empty"]
[[],[1],[2],[],[3],[],[],[]]

**屏幕截图**
![image](https://user-images.githubusercontent.com/37530692/125192208-30a56d00-e279-11eb-95eb-7298f1fdd660.png)

![image](https://user-images.githubusercontent.com/37530692/125192195-27b49b80-e279-11eb-854a-e3383bd8d6a2.png)
![微信截图_20210711185509](https://user-images.githubusercontent.com/37530692/125192270-8bd75f80-e279-11eb-9997-da30570fc44e.png)

**额外的上下文**
添加额外的上下文信息

**Comment by lc-kay** [comment]
Hi @ZichengQu 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

@feiceh Please reward the user.

**Comment by feiceh** [comment]
@ZichengQu 你好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的 ID，我们给予积分奖励哦。
