### ISSUE TITLE
139. Word Break Solution Spelling Mistake

### ISSUE THREAD

**Issue by StuartsHome** [LeetCode-Feedback/LeetCode-Feedback#4121]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Spelling mistake in Solution: Approach 3 - Using Breadth-First-Search
In the complexity analysis:
This - `Time complexity : O(n^3). For every starting index, the search can continue till the end of the given string.`
Should be - `Time complexity : O(n^3). For every starting index, the search can continue until the end of the given string.`

Also, Solution 1 provides a TLE in Python3 and requires a note stating the solution is not accepted.

**Comment by lc-kay** [comment]
Hi @StuartsHome 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @StuartsHome 
Thank you for your time. The problem has been updated. We appreciate your support!
