### ISSUE TITLE
Missing Test Case - 295. Find Median from Data Stream

### ISSUE THREAD

**Issue by HETFADIA** [LeetCode-Feedback/LeetCode-Feedback#4124]
#### Your LeetCode username
HETFADIA

#### Category of the bug
- [Find Median from Data Stream ] Question
- [ https://leetcode.com/submissions/detail/520808682/?from=explore&item_id=3810] Solution
- [ cpp] Language
- [ 1] Missing Test Cases 

#### Description of the bug
n*n solution also passes
The [codecpp.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6797006/codecpp.txt) passes on main test but gives tle on [testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6797019/testcase.txt)

#### Code you used for Submit/Run operation
[codecpp.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6797006/codecpp.txt)

#### Language used for code
c++

#### Expected behavior
The code gives tle on 
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6797019/testcase.txt)
but passes on main test

#### Screenshots
![image](https://user-images.githubusercontent.com/62541263/125197986-93990300-e27d-11eb-9d75-049a9187deff.png)

**Comment by lc-kay** [comment]
Hi @HETFADIA 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @HETFADIA 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
