### ISSUE TITLE
Missing Test Case - 295. Find Median from Data Stream

### ISSUE THREAD

**Issue by Kingloss404** [LeetCode-Feedback/LeetCode-Feedback#4125]
#### Your LeetCode username

Kingloss404

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Different result between site and my own.

#### Code you used for Submit/Run operation

```
class MedianFinder(object):

    def __init__(self):
        """
        initialize your data structure here.
        """
        self.arr = []
        self.length = 0
        

    def addNum(self, num):
        """
        :type num: int
        :rtype: None
        """
        self.arr.append(num)
        self.length += 1
        

    def findMedian(self):
        """
        :rtype: float
        """
        if self.length%2 != 0 :
            return self.arr[self.length//2]
        else :
            return (self.arr[int(self.length/2) - 1]+ self.arr[int(self.length/2)])/2
```

#### Language used for code

Python

#### Expected behavior

For array [1,2] the site show that hte median my code found was 1.000 whereas on my editor it clearly shows 1.5

#### Screenshots
![image](https://user-images.githubusercontent.com/73192785/125202822-4b71e480-e26d-11eb-9674-ceb844ca65a0.png)

**Comment by lc-kay** [comment]
@Kingloss404 Unfortunately, we are unable to troubleshoot the different behaviors between your local environment and the LeetCode environment. Please refer to the problem discuss section to post your issue as other users may have encountered the same before. Thank you for your time.
