### ISSUE TITLE
Unexpected behaviour - 295. Find Median from Data Stream

### ISSUE THREAD

**Issue by xalien10** [LeetCode-Feedback/LeetCode-Feedback#4128]
My code is passing while running using a test case in test console. But that same test case is failing due to different behaviour. How that is possible? How same test code is producing different answers in Run code and in Submit. I'm very sure it is having a serious bug.
<img width="1093" alt="Screenshot 2021-07-12 at 12 00 17 AM" src="https://user-images.githubusercontent.com/17931458/125205603-e0dc9b00-e2a4-11eb-91a1-b370f96bb440.png">

**Comment by lc-kay** [comment]
Hi @xalien10 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
