### ISSUE TITLE
Wrong Answer in Test Cases - 543. Diameter of Binary Tree

### ISSUE THREAD

**Issue by Anshu-jindal** [LeetCode-Feedback/LeetCode-Feedback#4129]
#### Your LeetCode username

Anshu_Jindal

#### Category of the bug
- [x] Question (✓)
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases (✓)

#### Description of the bug

The diameter of the sample tree [1,2,3,4,5] is given as 3 whereas it should be 4. See this for reference: [https://www.geeksforgeeks.org/diameter-of-a-binary-tree/](https://www.geeksforgeeks.org/diameter-of-a-binary-tree/)

#### Language used for code

C++

#### Expected behavior

The diameter should be the length of the longest path that the tree can traverse and in the given sample case [1, 2, 3, 4, 5] is 3 whereas it should be 4 because the path can be [4, 2, 1, 3] or [5, 2, 1, 3].
Reference: [https://www.geeksforgeeks.org/diameter-of-a-binary-tree/](https://www.geeksforgeeks.org/diameter-of-a-binary-tree/)

**Comment by lc-kay** [comment]
@Anshu-jindal The expected output is correct. Please re-read our problem description and explanation. Thank you for your time.
