### ISSUE TITLE
1461. Check If a String Contains All Binary Codes of Size K

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#413]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Problem statement

**Expected behavior**
```
Given a binary string s and an integer k.

Return True if all binary codes of length k is a substring of s. Otherwise, return False.
```

This is the problem statement after the mistake mentioned in #386 was fixed but looks like it was done hastily.

> binary codes of length k is a substring of s

This is incorrect. Codes should no longer be referred to as 'is'. 

They 'are' plural. Not 'is' plural. It can be fixed by either

```
Return True if every binary code of length k is a substring of s. Otherwise, return False.
```

or

```
Return True if all binary codes of length k are a substring of s. Otherwise, return False.
```

or

```
Return False if any binary code of length k is not a substring of s. Otherwise, return True.
```

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
