### ISSUE TITLE
Missing Test Case - 997. Find the Town Judge

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4130]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Below test case fails in RunCode, but passed on Submit

NOTE: Above is Town Judge trusts himself should fail, Code is wrong, Submit should fail, Add Test case.

    1
    [[1,1]]

#### Code you used for Submit/Run operation

```
var findJudge = function (N, trust) {
    if (N == 1) return 1;

    const g = Array.from({ length: N + 1 }, (e) => ({ c: 0, to: [], fr: [] }));
    let max_c = 0, max_i = 0;

    trust.forEach(([a, b]) => {
        g[a].to.push(b);
        g[b].fr.push(a);
        g[b].c++;
        if (g[b].c > max_c) {
            max_c = g[b].c;
            max_i = b;
        }
    });

    if (g[max_i].fr.length == N - 1 && !g[max_i].to.length) {
        return max_i;
    }
    return -1;
};
```

#### Expected behavior

1. RunCode fails, submit passes, but behavior should be the same

2. Also verify if the below condition is right/ wrong

    trust[i][0] != trust[i][1]

  if right, add the above missing test case
  if wrong, add the above missing test case,   and  fix the question

#### Screenshots

![image](https://user-images.githubusercontent.com/8236389/125220228-f9b87100-e2e3-11eb-879e-4f752e56abb1.png)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
