### ISSUE TITLE
Missing Test Case - 1923. Longest Common Subpath

### ISSUE THREAD

**Issue by zhanhb** [LeetCode-Feedback/LeetCode-Feedback#4132]
#### Your LeetCode username

[zhanhb](https://leetcode.com/zhanhb/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Many rabin karp solution passed without collision check, this test case can hack most of them.

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    int longestCommonSubpath(int, vector<vector<int>> &ps) {
        int l = 0, r = (int) min_element(begin(ps), end(ps), [](const auto &a, const auto &b) {
            return a.size() < b.size();
        })->size();
        long long base = 100001, mod = 100000000019;
        while (l < r) {
            int m = (l + r + 1) / 2;
            unordered_set<long long> hs;
            for (int i = 0; i < ps.size() && (i == 0 || !hs.empty()); ++i) {
                long long hash = 0, d = 1;
                unordered_set<long long> hs1;
                for (int j = 0; j < ps[i].size(); ++j) {
                    hash = (hash * base + ps[i][j]) % mod;
                    if (j >= m)
                        hash = (mod + hash - d * ps[i][j - m] % mod) % mod;
                    else
                        d = d * base % mod;
                    if (j >= m - 1 && (i == 0 || hs.count(hash)))
                        hs1.insert(hash);
                }
                swap(hs, hs1);
            }
            if (hs.empty())
                r = m - 1;
            else
                l = m;
        }
        return l;
    }
};
```

#### Language used for code
C++

#### Additional context

test case: [case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6805464/case.txt)
java code to generate this case: [Hack.java.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6805466/Hack.java.txt)

Maybe the code can be improved to hack more solutions.

**Comment by lc-kay** [comment]
Hi @zhanhb 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@zhanhb Our team decided to not add this test case because fundamentally, Rabin Karp solutions are correct. Thank you for your time.
