### ISSUE TITLE
160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by JohnnyTseng** [LeetCode-Feedback/LeetCode-Feedback#4133]
#### Your LeetCode username
`johnny411`

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Input & variables mentioned in description does not match variables passed in function, which is misleading.
Variables that should be removed in input & description

1. intersectVal
2. skipA
3. skipB

Demo:

`intersectVal`, `skipA`, `skipB` mentioned in both problem description & input

![Screen Shot 2021-07-12 at 22 08 07](https://user-images.githubusercontent.com/2656519/125301673-c9151d80-e35d-11eb-9c15-8d12b4309820.png)

![Screen Shot 2021-07-12 at 22 09 26](https://user-images.githubusercontent.com/2656519/125301762-df22de00-e35d-11eb-9e39-82e1f2838f10.png)

however, the variables passed in to the function only contains `headA` & `headB`, as the image shows:

![Screen Shot 2021-07-12 at 22 08 10](https://user-images.githubusercontent.com/2656519/125301912-07aad800-e35e-11eb-8200-5ccdf2c14292.png)

Please consider remove unnecessary variables mentioned in problem description and input datas, 
thank you! 

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
N/A

#### Screenshots
Provided in description

**Comment by lc-kay** [comment]
Hi @JohnnyTseng 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @JohnnyTseng 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
