### ISSUE TITLE
Python interpreter not working correctly

### ISSUE THREAD

**Issue by fabled-darksun** [LeetCode-Feedback/LeetCode-Feedback#4135]
Aman_Kashyap

Language
 

The code is working in my offline IDE but not on the leetcode platform.

'''
class Solution:
    def duplicateZeros(self, arr: List[int]) -> None:new_arr = []
              for i in arr:
                  if i==0:
                      new_arr.append(0)
                      new_arr.append(0)
                  else:
                      new_arr.append(i)
              new_arr = new_arr[0:len(arr)]
              print(new_arr)

```

Python


The code is running correctly with the given test cases on my offline IDE (Spyder) but the same code is not working on leetcode IDE.

**Comment by lc-kay** [comment]
@fabled-darksun Unfortuantely, we are unable to troubleshoot different behaviors from your local environment and the LeetCode environment. Please refer to the problem discuss section for further support as other users may have encountered this before. Thank you for your time.
