### ISSUE TITLE
Missing Test Case - 1335. Minimum Difficulty of a Job Schedule

### ISSUE THREAD

**Issue by njucsHikaru** [LeetCode-Feedback/LeetCode-Feedback#4136]
#### Your LeetCode username

njucsHikaru

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code failed on the following input but was accepted.
A wrong restricted lower bound for the initial value of dp array.

#### Code you used for Submit/Run operation

```
class Solution {
    public int minDifficulty(int[] jobDifficulty, int d) {
        int n = jobDifficulty.length;
        int[][] dp = new int[n + 1][d + 1];
        for(int[] arr : dp) Arrays.fill(arr, 10000);
        dp[0][0] = 0;
        
        for(int i = 1; i <= n; i++) {
            for(int j = 1; j <= d; j++) {
                int max = 0;
                for(int k = i; k >= j; k--) {
                    max = Math.max(max, jobDifficulty[k-1]);
                    dp[i][j] = Math.min(dp[i][j], dp[k-1][j-1] + max);
                }
                
            }
        }
        
        return dp[n][d] == 10000 ? -1 : dp[n][d];
    }
}
```
Input:
```
[1000,1000,1000,1000,1000,1000,1000,1000,1000,1000]
10
```
#### Language used for code

Java

#### Expected behavior

```
Output: -1
Excepted: 10000
```

#### Screenshots

![image](https://user-images.githubusercontent.com/25655032/125388093-dede0f00-e36c-11eb-971d-e62eb46316ef.png)

![image](https://user-images.githubusercontent.com/25655032/125388408-6deb2700-e36d-11eb-9c2f-d070e9190aec.png)

**Comment by lc-kay** [comment]
Hi @njucsHikaru 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @njucsHikaru 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
