### ISSUE TITLE
Missing Test Case - 579. Find Cumulative Salary of an Employee

### ISSUE THREAD

**Issue by niranjan4078** [LeetCode-Feedback/LeetCode-Feedback#4137]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

current solution is working if total number of months is less than 5. If we have more than 5 months, it is not working and even the output is also wrong.

#### Code you used for Submit/Run operation

```
select id,MONTH,salary  from (
    SELECT id,MONTH,sum(salary) over (partition by id order by  month asc rows between unbounded preceding and current row ) salary,
    row_number() over (partition by id order by  month desc) as rn
from Employee)a where rn>1
order by id asc,month desc
```

#### Language used for code

SQL
#### Additional context

Input
-----{"headers": {"Employee":
 ["Id", "Month", "Salary"]},
 "rows": 
{"Employee": 
[[1,1, 20],  
[1,2, 30],
[1,3,40],
[1,4,60],
[1,5,40],
[1,6,40],
[2, 1, 20], 
[2, 2,30], 
[3,2,40],
[3,3,60],
[3,4,70]]}}

Output for my query,which is Correct output
------------------------------------------
{"headers": ["id", "MONTH", "salary"], 
"values": [[1, 5, 190], 
           [1, 4, 150], 
           [1, 3, 90], 
           [1, 2, 50], 
           [1, 1, 20], 
           [2, 1, 20], 
           [3, 3, 100], 
           [3, 2, 40]]}

Excepted Output displayed by the current solution - Which is wrong
-------------------------------------------------------------------
{"headers": ["id", "MONTH", "salary"], 
"values": [[1, 5, 140], 
           [1, 4, 130], 
           [1, 3, 90], 
           [1, 2, 50], 
           [1, 1, 20], 
           [2, 1, 20], 
           [3, 3, 100], 
           [3, 2, 40]]}

**Comment by lc-kay** [comment]
Hi @niranjan4078 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @niranjan4078 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by niranjan4078** [comment]
Hi , niranjan4078 -- this is my leetcode ID

**Comment by niranjan4078** [comment]
Hi,

  Please find the below leetcode id.

  niranjan4078


Regards,
Niranjan
