### ISSUE TITLE
[Bug Fix] Correction in algorithm

### ISSUE THREAD

**Issue by vrushaliraut** [LeetCode-Feedback/LeetCode-Feedback#4139]
#### Category of the bug
- [ ] Solution

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

<img width="595" alt="Screenshot 2021-07-13 at 12 07 51 PM" src="https://user-images.githubusercontent.com/12109737/125403534-40d15f80-e3d3-11eb-8e11-0fe64a55709d.png">

**Comment by lc-kay** [comment]
@vrushaliraut Please provide the problem title and ID. Thank you.
