### ISSUE TITLE
Testcase missing

### ISSUE THREAD

**Issue by shaurya10000** [LeetCode-Feedback/LeetCode-Feedback#414]
For https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/
test case is missing for:
[2147483647, 2147483647]
2147483647
basically for largest 32 bit integer.

**Comment by CooperCooperCooper** [comment]
Hi @shaurya10000 ,
Thank you for reaching out to us! To help us assess the necessity of this test case, can you please share the code that proves this test case is needed?

**Comment by shaurya10000** [comment]
Below code is successfully submitted but fails with above mentioned test case.

class Solution {
    private int findSmallestIndex(int[] nums, int target) {
        int left = 0;
        int right = nums.length-1;
        
        int mid = right/2;
        while(left <= right) {
            mid = left + (right-left)/2;
            if (nums[mid] == target) {
                if(left==right) {
                    break;
                }
                right = mid;
            } else if (nums[mid] > target) {
                right = mid-1;
            } else {
                left = mid+1;
            }
        }
        
        return nums[mid] < target ? mid+1:mid;
    }
    
    public int[] searchRange(int[] nums, int target) {
        int[] indices = new int[]{-1,-1};
        if (nums == null || nums.length == 0) {
            return indices;
        }
        
        int smallestIndex = findSmallestIndex(nums, target);
        if (smallestIndex < nums.length && target == nums[smallestIndex]) {
            indices[0] = smallestIndex;
            indices[1] = findSmallestIndex(nums, target+1)-1;
        }
        
        return indices;
    }
}

**Comment by CooperCooperCooper** [comment]
Hi @shaurya10000 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @shaurya10000 ,
Thank you for your time. We've used your feedback to update the problem. Would you please share your LeetCode username here so we can credit your account with the reward?

**Comment by shaurya10000** [comment]
Hi

My username is Shaurya10000.

**Comment by lc-kate** [comment]
Hi @shaurya10000 ,
Thank you for your answer. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
