### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by ricecakemonster** [LeetCode-Feedback/LeetCode-Feedback#4140]
#### Your LeetCode username
ricecakemonster

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The question says **"s and t consist of any valid ascii character."**, but when I try to create a custom test case, **_öaa_**, it returns an error **"_öaa" is not a valid value of type string_**.  

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isIsomorphic(String s, String t) {
        int[] used = new int[130];
        Map<Character, Character> map = new HashMap();
        for(int i=0; i<s.length(); i++){
            if((map.get(s.charAt(i)) != null && map.get(s.charAt(i)) != t.charAt(i)) || (map.get(s.charAt(i)) == null && used[t.charAt(i)] != 0)) return false;
            map.put(s.charAt(i), t.charAt(i));
            used[t.charAt(i)] = 1;
        }
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior
There must be a test case that fails my code since  I'm creating a character array with 130 indexes. ( there are 256 valid ascii characters)

#### Screenshots
![image](https://user-images.githubusercontent.com/20471888/125409904-37afa680-e371-11eb-9011-c6095dbdf47b.png)

**Comment by hackifme1** [comment]
There is some insightful fact about valid ascii character in the below link.
https://stackoverflow.com/questions/47173022/valid-invalid-non-ascii-and-invalid-ascii-characters

**Comment by lc-kay** [comment]
@ricecakemonster The judger is correct. Please check out the link provided in the comment above. Thank you for your time.
