### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by manozjinagal** [LeetCode-Feedback/LeetCode-Feedback#4141]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-   Missing Test Cases 

#### 
```
public class Solution {
    public int findPeakElement(int[] nums) {
        for (int i = 0; i < nums.length - 1; i++) {
            if (nums[i] > nums[i + 1])
                return i;
        }
        return nums.length - 1;
    }
}
```

####  
<img width="1053" alt="Screenshot 2021-07-13 at 2 00 55 PM" src="https://user-images.githubusercontent.com/63463176/125418953-ba74cb70-5f0f-4c28-b1a4-c0cc8fcb3e8e.png">

**Comment by lc-kay** [comment]
@manozjinagal Please note that both 2 and 6 are valid peaks. Per the problem statement, If the array contains multiple peaks, return the index to any of the peaks. Thank you for your time.
