### ISSUE TITLE
Miing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by sivarampatamsetti** [LeetCode-Feedback/LeetCode-Feedback#4143]
#### Your LeetCode username
sivarampatamsetti

#### Category of the bug
Find Peak Element
5
python 3
[1,5,6,10,5,1,4]

#### Description of the bug
Has return Peak element i.e, the element that is greater than its neighbours from the array.

#### Code you used for Submit/Run operation
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        left = 0
        right = len(nums) - 1
        while left < right:
            mid = int(left + (right - left)/2)
            if nums[mid] < nums[mid+1]:
                left = mid + 1
            else:
                right = mid
        return left

#### Language used for code
python 3

#### Expected behavior
[1,5,6,10,5,1,4]
It should return 5(index) for the above missing test case.

**Comment by lc-kay** [comment]
@sivarampatamsetti Please note that you can return the index number to any of the peaks. In this test case, both 10 and 4 are peaks, so index 3 and 5 are both valid outputs. Thank you for your time.
