### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by ThulasinathanVM** [LeetCode-Feedback/LeetCode-Feedback#4144]
#### Your LeetCode username
ThulasinathanVM

#### Category of the bug
- [  ] Missing Test Cases 

#### Description of the bug
Case 
Input : {1,6,1,3,5,6,7,8,9,10}
Output : 1

#### Code you used for Submit/Run operation
```
class Solution {
public int findPeakElement(int[] nums) {
        for(int i=0;i<nums.length;i++){
            if( (i-1<0 || nums[i]>nums[i-1]) && (i+1==nums.length || nums[i]>nums[i+1]) )
                return i;
        }
        return -1;
    }
};
```

#### Language used for code
JAVA

#### Expected behavior
1 should be the output

**Comment by ThulasinathanVM** [comment]
Input : {1,6,1,3,5,6,7,8,9,9}
Output : 1

**Comment by lc-kay** [comment]
@ThulasinathanVM Your code returns accepted for the test case {1,6,1,3,5,6,7,8,9,10}. Please note that more than one peak is accepted if the array contains multiple peaks. Thank you for your time.
