### ISSUE TITLE
Bug with test case in problem of "Intersection of Two Linked Lists"

### ISSUE THREAD

**Issue by rudovrr** [LeetCode-Feedback/LeetCode-Feedback#4150]
#### Your LeetCode username
rudovroman

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
When running tests in problem "Intersection of Two Linked Lists", test number 10 has an incorrect output, but the output presented by the code is correct

#### Code you used for Submit/Run operation
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode(int x) : val(x), next(NULL) {}
 * };
 */
class Solution {
public:
    ListNode *getIntersectionNode(ListNode *headA, ListNode *headB) {
        ListNode* bufA = headA;
        ListNode* bufB = headB;
        ListNode* result = nullptr;
        
        while (bufA){
            bufB = headB;
            while (bufB){
                if (bufB->val == bufA->val && bufB->next->val == bufA->next->val) {
                    result = bufB;
                    break;
                }
            bufB = bufB->next;
            }
            if (result) break;
            bufA=bufA->next;
        }
        return result;
    }
};

#### Language used for code
C++

#### Expected behavior
The screenshot below shows an incorrect test case, in which the answer 8 is incorrect because the lists intersect by 1.

#### Screenshots

![Снимок экрана от 2021-07-13 20-55-21](https://user-images.githubusercontent.com/78729612/125502305-a577d1f6-f7eb-4494-bd32-1ee011b7e9b7.png)

**Comment by lc-kay** [comment]
@rudovrr The expected output is correct. Please refer to the first example explanation and other posts in discuss for further clarification. Thank you for your time.
