### ISSUE TITLE
Missing Test Case - 43. Multiply Strings : 

### ISSUE THREAD

**Issue by alhashmicode** [LeetCode-Feedback/LeetCode-Feedback#4151]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
the question is not clear 

#### Code you used for Submit/Run operation
```js
const convertToNumber = function(strNum) {
    let res = 0
    let numDegree = 1;
    for(let i = 1; i <= strNum.length;i++) {
        res += (strNum[ strNum.length - i].charCodeAt() - 48) * numDegree;
        numDegree *= 10;
    }
    console.log(res);
    return res;
}
const multiply = function(num1, num2) {
    const resNum1 = convertToNumber(num1);    
    const resNum2 = convertToNumber(num2);
    return `${resNum1 * resNum2}`;
};
```

#### Language used for code
javascript and typescript 

#### Screenshots
the description is not clear

**Comment by lc-kay** [comment]
@alhashmicode Please provide more details as to the unclear part. Thank you.

**Comment by lc-kay** [comment]
Hi @alhashmicode 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
