### ISSUE TITLE
1448. Correct answer running test. Wrong answer on submission.

### ISSUE THREAD

**Issue by Thoughtscript** [LeetCode-Feedback/LeetCode-Feedback#4153]
#### Your LeetCode username

https://leetcode.com/Thoughtscript/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution correctly solves the case when testing:

```
[3,3,null,4,2]
//3
```

But gets `7` when submitted: https://leetcode.com/submissions/detail/522056733/

#### Code you used for Submit/Run operation

```
// count-good-nodes-in-binary-tree
var T = 0, B = 0

const goodNodes = root => {
    traverse([], root)
    return T - B
}

const traverse = (R, node) => {
    let RR = [...R]
    if (node != undefined) {
        T++
        
        const mx = Math.max(...RR)
        if (node.val < mx) B++
        RR.push(node.val)
        
        if (node.left != undefined) traverse(RR, node.left)
        if (node.right != undefined) traverse(RR, node.right)
    }
}
```

#### Language used for code

JavaScript

#### Expected behavior

Not sure how `7` gets generated.

My immediate hunch is that this might have something to do with how variable scope or promises are used when submitted. Perhaps variable nomenclature as well. Not sure how submissions are run, what they are wrapped in when run, or what their execution environment is. Not sure how that differs from running a "test".

I've used global variables before with no problem (this is not necessarily encouraged I understand but has been valid before). Mostly curious as to why.

#### Screenshots

![Screen Shot 2021-07-13 at 2 12 38 PM](https://user-images.githubusercontent.com/10905039/125511609-5e431640-692f-4ace-9747-bbd13de70c57.png)

#### Additional context

Thanks! Might have missed something above. Any feedback is much appreciated. Hopefully this improves the way the submissions are handled. If not, would be great to know how I can improve my techniques and submission code.

**Comment by lc-kay** [comment]
Hi @Thoughtscript 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by Thoughtscript** [comment]
@lc-kay - Great thanks! JavaScript is not listed and you've got 76/205 helpful votes. Might want to update that to include JavaScript tips as well. I'll look into tweaking the code for the submission.
