### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by London804** [LeetCode-Feedback/LeetCode-Feedback#4154]
#### Your LeetCode username
 London804

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug
When I run code my solution passes, but when I submit my code it states 36/37 test cases passes. The submission result is time limit exceeded. Under more detail it doesn't clearly state which test case failed. 

#### Code you used for Submit/Run operation
Rotate Array 
```
var rotate = function(nums, k) {
    
    if (k === 0) return nums;
    let counter = 0;
    let rotate = [];
    while (counter < k) {
        rotate = nums.pop();
        nums.unshift(rotate);
        counter++

    }

    return nums;
    
};
```

#### Language used for code
Javascript 

#### Expected behavior
 expect to know which test cases are failing so I can try to solve it

**Comment by lc-kay** [comment]
@London804 Please click 'View All' to see the entire test case. Thank you for your time.
