### ISSUE TITLE
Missing Test Case - 156. Binary Tree Upside Down

### ISSUE THREAD

**Issue by gefeng** [LeetCode-Feedback/LeetCode-Feedback#4155]
#### Your LeetCode username

gefeng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+ ] Missing Test Cases 

#### Description of the bug

No test case for flipping the right subtree
I made a test case
[1,2,3,4,5,6,7] 
which failed if i run my code. But below code passed OJ

#### Code you used for Submit/Run operation

```
public TreeNode upsideDownBinaryTree(TreeNode root) {
        if(root == null) {
            return null;
        }
        
        if(root.left == null && root.right == null) {
            return root;
        }
        
        TreeNode rootL = upsideDownBinaryTree(root.left);
        TreeNode rootR = upsideDownBinaryTree(root.right);
        
        root.left.right = root;
        root.left.left = root.right;
        
        root.left = null;
        root.right = null;
        
        return rootL;
    }
```

#### Language used for code

Java

#### Expected behavior

I am not too sure TBH. The description is poor and has no information about should/shouldn't flip the right subtree.
If i comment out this line,
TreeNode rootR = upsideDownBinaryTree(root.right);
It passes the test case i made. So i guess we should not flip right subtree?

**Comment by lc-kay** [comment]
Hi @gefeng 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gefeng 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
