### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by puhuk** [LeetCode-Feedback/LeetCode-Feedback#4156]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ o ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 162. Find Peak Element
def findPeakElement(self, nums: List[int]) -> int:
        beg, end = 0, len(nums) - 1
        while beg < end:
            mid = (beg + end)//2
            if nums[mid] < nums[mid + 1]:
                beg = mid + 1
            else:
                end = mid

        return end
```

#### Language used for code

Python3

#### Expected behavior

With test case, [1,10,5,6,7,2] it should return 1 (10)
But it returns 4

**Comment by lc-kay** [comment]
@puhuk Please note that you are returning the index to any of the peaks. For this test case, 10 and 7 are both peak elements, so returning the index numbers 2 and 4 are both accepted. Thank you for your time.
