### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by basavaraj3** [LeetCode-Feedback/LeetCode-Feedback#4157]
#### Your LeetCode username
basavarajsb

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
C# dictionary throws an exception when you try to add a duplicate key. My solution with no exception handling is accepted, but when I manually test with the input [3,3,9] and a target of 12, I do see the exception as expected. Kindly consider adding this case

#### Code you used for Submit/Run operation

```
// Two Sum
public class Solution {
    public int[] TwoSum(int[] nums, int target) {
        Dictionary<int, int> tracker = new Dictionary<int,int>();
        for(int i = 0; i < nums.Length; i++){
            if(tracker.ContainsKey(target - nums[i])){
                return new int[] {tracker[target - nums[i]], i};
            }
            tracker.Add(nums[i], i);
        }
        return null;
    }
}
```

#### Language used for code
C#

#### Expected behavior
The above solution should not be accepted. As it fails for the case [3,3,9] target = 12

**Comment by lc-kay** [comment]
Hi @basavaraj3 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @basavaraj3 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
