### ISSUE TITLE
Unclear description - 130. Surrounded Regions

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4158]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

What is "surrounded by"?
It is from 4 sides? 8 sides?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Question must be clear

"surrounded by" is unclear if it is 4 sides only (NSWE)? OR 8 sides NSWE plus from diagonals?

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
