### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by ashutoshcp** [LeetCode-Feedback/LeetCode-Feedback#4160]
#### Category of the bug
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int findPeakElement(int[] nums) {
        int l = 0, r = nums.length - 1;
        while (l < r) {
            int mid = (l + r) / 2;
            if (nums[mid] > nums[mid + 1])
                r = mid;
            else
                l = mid + 1;
        }
        return l;
    }
}
```

#### Expected behavior

```
input [3,2,1,4,3,5]
index  0,1,2,3,4,5


 Expected should be coming as 0 in the ideal case. 
 But in the case of Binary search, it's coming as 5
 With log(N) algorithm it's different. 
```

#### Screenshots

<img width="929" alt="Screenshot 2021-07-14 at 10 17 32 AM" src="https://user-images.githubusercontent.com/10486922/125563995-863390ee-7473-46b4-9866-ae0e34d3d25b.png">

**Comment by hackifme1** [comment]
It is one of the peaks. You can return anyone's index as per problem statement.

**Comment by lc-kay** [comment]
@ashutoshcp 0, 3, and 5 are all valid outputs for this test case. You can return any of the peak's index. Thank you for your time.
