### ISSUE TITLE
557. Reverse Words in a String III -- Incorrect Solution Time Complexity

### ISSUE THREAD

**Issue by nitinsubz** [LeetCode-Feedback/LeetCode-Feedback#4161]
#### Your LeetCode username
nitinsub

#### Category of the bug
- [x] Solution

#### Description of the bug
The solution says the runtime is O(n). where n is the length of the string. However, the runtime actually is O(N*S) where N is the length of the string and s is the length of the longest word in the string. In your solution, the function "reverse()" runs in O(S) time while the outer for loop runs in O(N) time.

**Comment by lc-kay** [comment]
@nitinsubz 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @nitinsubz,
Thank you for reaching out. Every word in s is reversed once. This takes linear time (as the user stated) with respect to the number of characters in a word. Thus we visit every non-space character exactly once during the reversal process. So the time to reverse all words is linear with respect to the number of non-space characters in s. Therefore, the time to reverse all words is also O(n), where n is the length of s.
