### ISSUE TITLE
Missing Test Case - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by Ax-alchemy** [LeetCode-Feedback/LeetCode-Feedback#4163]
#### Your LeetCode username

Ax_alchemy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code passed all the test cases but I found a test case on which it should not pass.

#### Code you used for Submit/Run operation

```C++
class Solution {
public:
    int longestSubstring(string s, int k) {
        int n=s.size();
        vector<vector<int>> v(26,vector<int> (n,0));
        int ans=0;
        for(int i=0;i<n;i++){
            for(int j=0;j<26;j++){
                if(j==s[i]-'a')
                    i==0?v[j][i]=1:v[j][i]=v[j][i-1]+1;
                else i==0?v[j][i]=0:v[j][i]=v[j][i-1];
            }
            int l=-1,f=1;
            for(int j=0;j<26;j++){
                if(v[j][i]<k && v[j][i]>0){
                    int id=lower_bound(v[j].begin(),v[j].begin()+i+1,v[j][i])-v[j].begin();
                    l=max(l,id);
                }
            }
            for(int j=0;j<26;j++){
                if(v[j][i]!=0){
                    if(l==-1){
                        if(v[j][i]>=k && v[j][i]>0 && v[j][i]<k){
                            f=0; break;
                        }
                    }
                    else{
                        if(v[j][i]>=k && v[j][i]-v[j][l]>0 && v[j][i]-v[j][l]<k){
                            f=0; break;
                        }
                    }
                }
            }
            if(f==0)continue;
            ans=max(ans,i-l);
        }
        return ans;
    }
};
```
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

#### Expected behavior

For the test case=
"cadabb"
2
the expected output is **2**, but my code is giving output **0**
and still, it passed all the test cases on submitting the above code.
So, this test case should be added to the set of test cases.

#### Screenshots

<img width="551" alt="lc_395" src="https://user-images.githubusercontent.com/61796691/125587300-e8fb492a-0ac4-40f3-b453-da27e05f281a.png">

**Comment by lc-kay** [comment]
Hi @Ax-alchemy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Ax-alchemy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
