### ISSUE TITLE
Missing Test Case - 791. Custom Sort String

### ISSUE THREAD

**Issue by alexunxus** [LeetCode-Feedback/LeetCode-Feedback#4165]
#### Your LeetCode username

 alexunxus

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ V] Missing Test Cases 

#### Description of the bug

The judge system does not tolerate empty "str" string

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string customSortString(string order, string str) {
        int hist[26] = {0}, ptr = 0, i, j;
        string ret(str.size(), '0');
        
        for(char c: str) { hist[c-'a']++; }
        for(char c: order) {
            if (hist[c-'a']) {
                for(i = 0; i < hist[c-'a']; ++i) {
                    ret[ptr++] = c;
                }
                hist[c-'a'] = 0;
            }
        }
        for(i = 0; i < 26; ++i) {
            if (hist[i]) {
                for(j = 0; j < hist[i]; ++j) {
                    ret[ptr++] = 'a'+i;
                }
            }
        }
        return ret;
    }
};
```

#### Language used for code

C++

#### Expected behavior

If the string "str" is empty, the expected answer should be empty string as well.

**Comment by lc-kay** [comment]
<img width="902" alt="Screen Shot 2021-07-14 at 10 13 45 AM" src="https://user-images.githubusercontent.com/70870126/125664276-bb698ae1-ce1a-479c-b5c6-28b59f84e1a1.png">
Please let me know if you are seeing different behavior on your end and provide a screenshot of the issue. Thank you.
