### ISSUE TITLE
Missing Test Case - 791. Custom Sort String

### ISSUE THREAD

**Issue by aimhighmp** [LeetCode-Feedback/LeetCode-Feedback#4166]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Below use case to be evaluated to validate for result. 

"cba"
"abcdfhe"

#### Code you used for Submit/Run operation

```
public String customSortString(String order, String str) {
        Map<Character,Integer> charCounts = new HashMap<>();
        for(int i =0;i<str.length();i++){
             Character c =str.charAt(i);
            charCount.put(c,charCount.getOrDefault(c,0)+1);
        }
        StringBuilder sb = new StringBuilder();
        for(int i =0;i<order.length();i++){
            Character c =order.charAt(i);
            int count =charCount.getOrDefault(c,0);
            while(count>0){
                sb.append(c);
                count--;
            }
            charCount.remove(c);
        }
        
         for(int i =0;i<str.length();i++){
              Character c =str.charAt(i);
           if(charCount.containsKey(c))
                sb.append(c);
               
        }
        
        return sb.toString();
        
    }
```

#### Expected behavior

Test case to be failed but it passed

**Comment by lc-kay** [comment]
@aimhighmp Please provide the submission details link to your code. Thank you.

**Comment by aimhighmp** [comment]
Thanks for quick response. Appreciated it. 

Please find my submission detail link.

https://leetcode.com/submissions/detail/522403544/

**Comment by lc-kay** [comment]
<img width="900" alt="Screen Shot 2021-07-16 at 11 49 54 AM" src="https://user-images.githubusercontent.com/70870126/125995140-c1942135-2da9-4498-a4e1-802fa4de7392.png">
Please note that you can return any permutation of s that satisfies this property. Thank you for your time.
