### ISSUE TITLE
Leetcode-791. Custom Sort String (Rename "order")

### ISSUE THREAD

**Issue by MAZHARMIK** [LeetCode-Feedback/LeetCode-Feedback#4172]
#### Category of the bug
- [ ] Question
- [ ] Language

**Comment by MAZHARMIK** [comment]
Hope to have this very small issue fixed soon.
Thank you Leetcode 😄

**Comment by lc-kay** [comment]
@MAZHARMIK What is the issue you are trying to report?

**Comment by MAZHARMIK** [comment]
Hi @lc-kay , sorry if I was not clear. It's a simple and small report enhancement.
If you notice the Problem Statement of Leetcode-791 (Custom Sort String), it is something like this :
"....Permute the characters of "s" so that they match the order that "order" was sorted. More specifically....////
The statement above is a bit confusing for readers. The variable name chosen for string "order" is quite confusing
(Pointing to this part ->   "the order that "order" was sorted")
Although the variable name "order" is highlighted in the problem statement to distinguish it, but it may be confusing to readers. At least me and my friends faced this. 
You can rename the "order" to some other name for example : "source" etc.

Hope I am clear this time. It may not be a big issue, but i would be glad if you will consider this 😄 
Thanks.

**Comment by lc-kay** [comment]
@MAZHARMIK Our team will consider this change as we can updating our problems. Thank you for your time.

**Comment by MAZHARMIK** [comment]
Thanks.
