### ISSUE TITLE
Missing Test Case - 1297. Maximum Number of Occurrences of a Substring

### ISSUE THREAD

**Issue by arjunsingh9087** [LeetCode-Feedback/LeetCode-Feedback#4173]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I think the answer for this test case is incorrect

"aaaaacbc"
2
4
6

#### Code you used for Submit/Run operation

```
class Solution:
    def maxFreq(self, s: str, maxLetters: int, minSize: int, maxSize: int) -> int:
        
        start = end = 0
        hashmap = collections.defaultdict(int)
        count_map = collections.defaultdict(int)
        
        diff_char = set()
        while end < len(s):
            count_map[s[end]] += 1
            diff_char.add(s[end])
            
            while len(diff_char) > maxLetters or end-start+1 > minSize:
                count_map[s[start]] -= 1
                if count_map[s[start]] == 0:
                    diff_char.remove(s[start])

                start += 1
            
            if len(diff_char) == maxLetters and end - start + 1 >= minSize:
                hashmap[s[start:end+1]] += 1
                
            
            end += 1
        
        print(hashmap)
        if hashmap:
            return max(hashmap.values())
        return 0
```

#### Expected behavior

I expect the answer for that question to be 1, but the correct answer given is 2. I could be wrong but I just can't see how the answer is 2

**Comment by lc-kay** [comment]
@arjunsingh9087 Please check out this post: https://leetcode.com/problems/maximum-number-of-occurrences-of-a-substring/discuss/1113334/Broken-test-case-aaaaacbc-246-has-only-one-possible-case-%22aaac%22-does-it-not Thank you for your time.
