### ISSUE TITLE
791. Custom Sort String using built-in data type

### ISSUE THREAD

**Issue by SilviaChen** [LeetCode-Feedback/LeetCode-Feedback#4174]
#### Your LeetCode username

Wanting Chen

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think it is not good to use built-in data type ```str``` to name a variable as ```str``` though I can run test cases successfully. 

#### Language used for code

Python

#### Screenshots

![image](https://user-images.githubusercontent.com/6461420/125681318-1a8f052b-70cb-45f3-9da7-03f26d4290cb.png)

**Comment by lc-kay** [comment]
Hi @SilviaChen 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@SilviaChen Our team has noted your feedback and will update it in the new version. Thank you for your time.
