### ISSUE TITLE
Missing Test Case - 791. Custom Sort String

### ISSUE THREAD

**Issue by mygenel** [LeetCode-Feedback/LeetCode-Feedback#4176]
#### Your LeetCode username

mygenel

#### Category of the bug
- [ X ] Question
- [ X ] Solution
- [ X ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The word "str" is a keyword in Python, but it is given as a variable name in the question. Therefore, in the default template of solution, when the str argument is passed by the name "str" it causes issues because it is a keyword. Renaming the variable should be a sufficient fix.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Python 3

#### Expected behavior

I expected to be able to use the variable name as it was given in the question, but it gave me an error. I had to change the variable name manually.

#### Additional context

It should be a simple fix. Thanks so much!

**Comment by lc-kay** [comment]
Hi @mygenel 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mygenel Our team has fixed this issue a while back. Please reset the code definition to see the changes. Thank you for your time.
