### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by amaity1** [LeetCode-Feedback/LeetCode-Feedback#4178]
#### Your LeetCode username
aranyak

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug

Missing Test case

[5,1,2,1,2]

#### Code you used for Submit/Run operation

```

```

#### Additional context

If the first or the last element is the peak the linear scan will work while the other method will fail

"
public class Solution {
    public int findPeakElement(int[] nums) {
        return search(nums, 0, nums.length - 1);
    }
    public int search(int[] nums, int l, int r) {
        if (l == r)
            return l;
        int mid = (l + r) / 2;
        if (nums[mid] > nums[mid + 1])
            return search(nums, l, mid);
        return search(nums, mid + 1, r);
    }
}

"

This is copied directly from the solution of leetcode and this will fail the above test case

**Comment by Zhima-Mochi** [comment]
If the array contains multiple peaks, return the index to **any of the peaks**.

**Comment by amaity1** [comment]
> If the array contains multiple peaks, return the index to **any of the peaks**.

Just run the above test case with the above code.
This code is the code supplied by leet code in the solution

**Comment by Zhima-Mochi** [comment]
![image](https://user-images.githubusercontent.com/77471137/125732427-4b6df358-2a52-450d-aed3-8d2ba3ff993d.png)
It is accepted, thought return different **local** peaks.
You can return any local peak. It is like finding local maximum of curve in Calculus.

**Comment by lc-kay** [comment]
@Zhima-Mochi is correct. You can return any local peak and both answers are valid. Thank you for your time.
