### ISSUE TITLE
Missing Test Case - 797. All Paths From Source to Target

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4179]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think the below constraint is missing in the question description
> There are no parallel edges

Below test case is not allowed in RunCode, but no mention in the question description

Test case

    [[1,1],[]]

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

The question description should be unambitious, We need to add below constraint

> There are no parallel edges

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@manoharreddyporeddy There are no missing constraints. The provided test case already shows an invalid exception. The current set of constraints cover all the intended constraints and we've added a clarification to show that.
