### ISSUE TITLE
Golang runtime doesn't support global map with struct type key well

### ISSUE THREAD

**Issue by nevet** [LeetCode-Feedback/LeetCode-Feedback#418]
#### Your LeetCode username
nevetshd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

Golang runtime doesn't support global map with struct type key well. The code will fail the submission while success in console (custom test) with exactly the same test case. I have tried 2 problems using a global map with struct type key, both of them had the same problem:

**494. Target Sum**

I defined
```
type state struct {
    cur int
    S int64
}

var memo = map[state]int{}
```
But the test case failed: https://leetcode.com/submissions/detail/349499300/

However the code produces correct result.

**87. Scramble String**

I defined
```
type dp struct {
    l1 int
    r1 int
    l2 int
    r2 int
}

var memo = map[dp]bool{}
```

But the test case failed: https://leetcode.com/submissions/detail/349534232/

However the code produces correct result.

In this problem, I tried to change the definition of `memo` from map to a 4 dimension array, it passed the tests successfully: https://leetcode.com/submissions/detail/349539944/

#### Language used for code
Golang

**Comment by CooperCooperCooper** [comment]
Hi @nevet ,
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
