### ISSUE TITLE
559. Maximum Depth of N-ary Tree typescript function arg type issue

### ISSUE THREAD

**Issue by henveloper** [LeetCode-Feedback/LeetCode-Feedback#4181]
#### Your LeetCode username

henveloper

#### Category of the bug
 Question

#### Description of the bug

* The total number of nodes is between [0, 104], however, function args is [root: Node], should be [root: Node | null] instead.

#### Code you used for Submit/Run operation

Test case permits [], console.log(root) -> null

#### Language used for code

typescript

#### Expected behavior

as above

**Comment by lc-kay** [comment]
Hi @henveloper 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @henveloper 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
