### ISSUE TITLE
Missing Test Case - 841. Keys and Rooms

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4182]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test case
    [[1],[],[0,3],[1]]
Expected
	false

> You can walk back and forth between rooms freely.

The above problem description is ambiguous
Indirectly suggests as undirected graph
However problem is directed

Example 3->1 does not imply 1->3

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

Problem description must be unambiguous
See description above & test case

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
