### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by yuchen9902** [LeetCode-Feedback/LeetCode-Feedback#4183]
#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```

class Solution {
    public int removeElement(int[] nums, int val) {
        int slow = 0;
        // int k = 0;
        for(int fast=0;fast<nums.length;fast++){
            if(nums[fast]!=val){
                nums[slow] = nums[fast];
                slow++;
            }
            fast++;
        }
        return slow;
    }
}

```

#### Language used for code

Java

#### Expected behavior

The expected return type in the solution is not the same as how the function is defined.

#### Additional context

Wrong Answer
Details 
Input
[3,2,2,3]
3
Output
[2]
Expected
[2,2]

**Comment by Zhima-Mochi** [comment]
Hi, you should write: 
```
class Solution {
    public int removeElement(int[] nums, int val) {
        int slow = 0;
        // int k = 0;
        for(int fast=0;fast<nums.length;fast++){
            if(nums[fast]!=val){
                nums[slow] = nums[fast];
                slow++;
            }
            //fast++;
        }
        return slow;
    }
}
```
Why you shift fast twice?
Do not worry return type, it test the nums it pass in the function.

**Comment by yuchen9902** [comment]
Oh I didn't notice that. Thanks！

**Comment by lc-kay** [comment]
@Zhima-Mochi Thanks for your help! @yuchen9902 I'm glad the issue is resolved now. Thank you both and have a great day!
