### ISSUE TITLE
Missing Test Case - 611. Valid Triangle Number

### ISSUE THREAD

**Issue by Harry-Yang-Huang** [LeetCode-Feedback/LeetCode-Feedback#4184]
#### Your LeetCode username
Harry_Huang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug
In the constrains section it says "0 <= nums[i] <= 1000", that means nums[i] can be 0.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int triangleNumber(vector<int>& nums) {
        sort(nums.begin(), nums.end());
        int n = nums.size(), ret = 0;
        for (int i = 0; i < n-2; i++) {
            //if (nums[i] == 0) continue;
            
            for (int j = i + 1; j < n-1; j++) {
                int target = nums[i] + nums[j];
                auto it = lower_bound(nums.begin()+j+1, nums.end(), target);
                it--;
                
                ret += it - nums.begin() - j;
            }
        }
        
        return ret;
    }
};
```

#### Expected behavior

Above code shouldn't pass the test case like [0, 0, 0, 4]

#### Screenshots

N/A

**Comment by lc-kay** [comment]
@Harry-Yang-Huang Please provide more details as to why your code should not pass the test case [0, 0, 0, 4]. Thank you.

**Comment by Harry-Yang-Huang** [comment]
0 is not a valid triangle edge, for example, [0, 0, 4] cannot form a triangle.
Above code I provide doesn't have 0 check can also be accepted, that means there is a test case missing in this case.
 
Thank you.

**Comment by lc-kay** [comment]
Hi @Harry-Yang-Huang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Harry-Yang-Huang We already have many test cases with 0's and many similar to the provided test case. The code did not fail with this test, so we did not add it. Thank you for your time.
