### ISSUE TITLE
Solution typo - 611. Valid Triangle Number

### ISSUE THREAD

**Issue by alexnik42** [LeetCode-Feedback/LeetCode-Feedback#4186]
#### Your LeetCode username

alexnik42

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Current version: `Time complexity : O(n^2). Loop of k and j will be executed O(n^2) times in total, because, we do not reinitialize the value of k for a new value of j chosen(for the same i). Thus the complexity will be O(n^2+n^2)=O(n^2)`

#### Expected behavior

We do sorting in `O(n log n)` time and traverse the array `O(n^2)` times, so correct description should be: `Time complexity : O(n^2). Loop of k and j will be executed O(n^2) times in total, because, we do not reinitialize the value of k for a new value of j chosen(for the same i). Thus the complexity will be O(n*log(n)+n^2)=O(n^2)`

**Comment by lc-kay** [comment]
Hi @alexnik42 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @alexnik42,
Thank you for your feedback. The problem has been updated. We appreciate your support!
