### ISSUE TITLE
Missing Test Case - 403. Frog Jump

### ISSUE THREAD

**Issue by gautamsw5** [LeetCode-Feedback/LeetCode-Feedback#4189]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
When there is only one stone at position 0, the answer should be true but the code given below returns false and still it passes all test cases.
New test case to be added:
[0, 0]

#### Code you used for Submit/Run operation

```
class Solution
{
    Set<Integer> set;
    Set<Integer>[] dp;
    int d;
    public boolean canCross(int[] arr)
    {
        set = new HashSet<>(); // set of all stones
        dp = new Set[arr.length]; // to mark cases with no solution
        d = arr[arr.length-1]; // last stone
        for(int  i = 0; i < arr.length; i++)
        {
            set.add(arr[i]);
            dp[i] = new HashSet<>();
        }
        if(solve(1, 1)) // 1st jump is always from 0 to 1, so i = 1 and k = 1
            return true;
        return false;
    }
    boolean solve(int i, int k) // i is current pos and k is length of prev jump
    {
        if(i==d) // reached the end
            return true;
        if(!set.contains(i) || k==0 || dp[k].contains(i)) // if not land on stone or 0 steps taken in prev jump or already found no solution then return false
            return false;
        if(solve(i+k-1, k-1)) // Try taking k-1 steps
            return true;
        if(solve(i+k, k)) // Try taking k steps
            return true;
        if(solve(i+k+1, k+1)) // Try taking k+1 steps
            return true;
        dp[k].add(i); // No solution found for (i,k) so add to set so that if again solve(i,k) is called for same values, it will return false in the base case
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Wrong Answer

#### Screenshots

![image](https://user-images.githubusercontent.com/72446354/125788306-919eca25-d0bd-48fb-b889-bbc486ee48b0.png)
![image](https://user-images.githubusercontent.com/72446354/125788355-76f04749-f814-4afa-9a6d-82ccd88b3d15.png)

#### Additional context

In the constraints, it is given that size of stones array is in the range [2, 2000] but it is not mentioned that values can be repeated in the test cases. So [0, 0] is a valid test case and the code should return true for it.

**Comment by lc-kay** [comment]
Hi @gautamsw5 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gautamsw5 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
