### ISSUE TITLE
Missing testcase for problem 1342

### ISSUE THREAD

**Issue by chimmybirdy** [LeetCode-Feedback/LeetCode-Feedback#419]
#### Your LeetCode username

bhchen604

#### Category of the bug

- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I got "Accepted" for my submission but the result of my program is different from the expected one for this testcase.

The testcase:

- Input: num = 0
- Output (expected): 0
- Output (the result of my code): -1

#### Code you used for Submit/Run operation

```python3
# 1342. Number of Steps to Reduce a Number to Zero
class Solution:
    def numberOfSteps(self, num: int) -> int:
        count = 0
        while num > 0:
            if num % 2 == 0:
                count += 1
            else:
                count += 2
            num //= 2
        return count - 1
```

#### Language used for code

Python3

#### Expected behavior

Expected: I should get a wrong answer error.
Actually happened: I got "Accepted".

#### Screenshots

![1342](https://user-images.githubusercontent.com/66476787/83940790-367c8380-a819-11ea-8fa0-1ef6e81aae41.png)

#### Additional context

Nope, thank you! ❤️

**Comment by CooperCooperCooper** [comment]
Hi @chimmybirdy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @chimmybirdy ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
