### ISSUE TITLE
Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by deep3072** [LeetCode-Feedback/LeetCode-Feedback#4191]
#### Your LeetCode username
deep3072

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:
[1,1]

#### Code you used for Submit/Run operation

```
class Solution 
{
        public:
        int jump(vector<int>& nums) 
        {
                int n=nums.size();
                if(n==1)
                        return 0;
                else if(n==2 && nums[0]+nums[1]==3)
                        return 1;
                int i,curr=nums[0],cnt=1;
                int mx=INT_MIN;
                for(i=1;i<n;i++)
                {
                        curr--;
                        if(nums[i]-curr>mx)
                                mx=nums[i]-curr;
                        if(curr==0)
                        {
                                curr=mx;
                                cnt++;
                                mx=INT_MIN;
                        }
                        if((curr+i)>=(n-1))
                                return cnt;
                }
                return cnt;
        }
};
```

#### Language used for code
C++

#### Expected behavior
The solution should not be accepted since it fails on the test case

#### Screenshots
![lc44](https://user-images.githubusercontent.com/62668186/125823518-46758484-1a85-4c32-9530-f02e314c420c.PNG)

**Comment by lc-kay** [comment]
Hi @deep3072 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@deep3072  This solution already gets WA and you added an if condition at lines 9 and 10 to make it pass the test cases. Therefore, we did not add this test case.

**Comment by deep3072** [comment]
Okay
