### ISSUE TITLE
Missing Test Case - 79. Word Search

### ISSUE THREAD

**Issue by 95th** [LeetCode-Feedback/LeetCode-Feedback#4193]
#### Your LeetCode username
95th

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Fastest solution fails for the following test case but is passing all the existing ones.

```
[["B","D","T","A"],["A","T","C","S"],["A","D","E","E"],["A","D","E","E"]]
"TDBATC"
```
#### Code you used for Submit/Run operation

```java
// Two Sum
class Solution {
    private char grid[][], str[];
    private int m, n, len;
    private boolean visited[][];
    public boolean exist(char[][] board, String word) {
        grid = board;
        m = grid.length; n = grid[0].length;
        str = word.toCharArray();
        len = str.length;
        visited = new boolean[m][n];
        for(int i=0;i<m;i++)
            for(int j=0;j<n;j++)
                if(dfs(i, j, len - 1)) return true;
        return false;
    }
    private boolean dfs(int i, int j, int pos) {
        if(pos < 0) return true;
        if(isSafe(i, j) && grid[i][j] == str[pos]) {
            visited[i][j] = true;
            pos--;
            return dfs(i-1, j, pos) || dfs(i+1, j, pos) || dfs(i, j-1, pos) || dfs(i, j+1, pos);
        }
        return false;
    }
    private boolean isSafe(int i, int j) {
        return (i >= 0 && j >= 0 && i < m && j < n && !visited[i][j]);
    }
}
```

#### Language used for code
Java

#### Expected behavior
Code is rejected

#### Screenshots
NA

#### Additional context
NA

**Comment by lc-kay** [comment]
Hi @95th 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @95th 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
