### ISSUE TITLE
Judge does not work, if there are too many duplicate values in nums - 18. 4Sum

### ISSUE THREAD

**Issue by bdoellinger** [LeetCode-Feedback/LeetCode-Feedback#4194]
#### Your LeetCode username

b_d

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

18. 4Sum -> https://leetcode.com/problems/4sum/

The Judge does not work if nums contains too many duplicates, that can sum up to target (even though these cases are within the constraints).

Examples:
nums contains 200 0's and target = 0
nums contains 200 1's and target = 4
nums = [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90] and target = 200

Possibly these kind of cases should also be added to the test cases (if they are not included yet).

#### Code you used for Submit/Run operation

```
# technically not relevant, since problem is the judge
class Solution:
    def fourSum(self, nums: List[int], target: int) -> List[List[int]]:
        # modify nums, such that at most 4 duplicate values are in nums
        nums = [num for num, count in Counter(nums).items() for _ in range(min(4, count))]
        n = len(nums)
        
        # use a similar approach as in 2 sum
        quad = set()
        two_sum = defaultdict(list)
        for i in range(n-1):
            for j in range(i+1, n):
                ij_sum = nums[i] + nums[j]
                
                for k, l in two_sum[target - ij_sum]:
                    if l < i:
                        quad.add( tuple(sorted([nums[i], nums[j], nums[k], nums[l]])) )
                
                two_sum[ij_sum].append((i, j))
        
        return quad
```

#### Language used for code

Python3

#### Expected behavior

That Judge generates the expected answer.

#### Screenshots

![leetcode_18_4sum_judge_issue](https://user-images.githubusercontent.com/68056001/125916365-1b74fb52-6f71-47b8-a7ed-081bfec9fc97.png)

#### Additional context

Possible fix:
Modify nums, such that at most 4 duplicate values can exist in nums, and pass modified nums to judge.

Example python code, to achieve this:
```
modified_nums = [num for num, count in Counter(nums).items() for _ in range(min(4, count))]
```

**Comment by lc-kay** [comment]
Hi @bdoellinger 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@bdoellinger The test case works fine when our team added it, so it could be due to a server load. We've added the test case to ensure that. Thank you for your time.
