### ISSUE TITLE
Longest Common Prefix

### ISSUE THREAD

**Issue by marisa9000** [LeetCode-Feedback/LeetCode-Feedback#4195]
#### Your LeetCode username
mmbryan

#### Category of the bug
- [ ] Question

#### Description of the bug

I think my code is returning the correct output, but one submission test is claiming the correct output is something else. 
I think the test is wrong. Can someone check?

#### Code you used for Submit/Run operation

```
//LongestCommonPrefix
class Solution(object):
    def longestCommonPrefix(self, strs):
        """
        :type strs: List[str]
        :rtype: str
        """
        if len(strs) > 1 and len(strs) < 200:
            for i in strs:
                i = list(i)
                if len(i) > 0 and len(i) < 200:
                    continue
                else:
                    print('Strings should be less than 200 characters long')
                    return strs[0]
        else:
            print('The list of strings must be greater than 1 and less than 200 entries.')
            return strs[0]
        

        pairs = []
        s_dict = {}
        prefix_len = 1 # length of the prefix (original value was 2)
    
        while prefix_len < 4: #original value was 4
            for s in strs:
                if len(s) >= prefix_len + 1:
                    pair = s[0:prefix_len]
                    pairs.append(pair)
            prefix_len += 1               # increment and repeat loop to try and capture longer prefixes
        for s in pairs:
            if s not in s_dict:
                s_dict[s] = 1
            else:
                s_dict[s] += 1
        max_value = max(s_dict.values())  # value with highest count  
   
   
        if max_value > 1:
            prefixes = [k for k, v in s_dict.items() if v == max_value] # getting all keys with the highest count
            for prefix in prefixes:
                longest_prefix = max(prefixes, key=len)  # Among highest count keys, extract the longest
        elif max_value == 1 and len(list(s_dict)) == 1:
            longest_prefix = [k for k, v in s_dict.items() if v == max_value]
            longest_prefix = ''.join(longest_prefix)
        elif max_value == 1 and len(list(s_dict)) > 1:
            longest_prefix = ""
        
        return `longest_prefix`
```

#### Language used for code
Python

#### Expected behavior
I expected my code to pass the test and submit as I believe it meets specifications. Instead it failed the submission test because the test expected a different output.
With the input of ["reflower","flow","flight"], I expect the correct output to be 'fl' as it appears in "flow" and "flight" (the 'fl' in 'reflower' doesn't count). However, the submission test says it should be an empty string "". I think that's wrong. Can someone confirm?

#### Screenshots

I wanted to insert a screenshot, but I don't see how. Instead I'll paste in the results of the test, which I think are wrong.

Wrong Answer 
Input
["reflower","flow","flight"]
Output
"fl"
Expected
""

**Comment by mecdeality** [comment]
You are asked to find the longest **common** prefix. It means that each word must have the same prefix.

**Comment by marisa9000** [comment]
I see now I interpreted 'common' too loosely. Thanks!
