### ISSUE TITLE
886. Possible Bipartition | Wrong test case

### ISSUE THREAD

**Issue by mecdeality** [LeetCode-Feedback/LeetCode-Feedback#4196]
#### Your LeetCode username
mcdeal
#### Category of the bug
- [1 ] Question
- [ ] Solution
- [ ] Language
- [1] Missing Test Cases (Wrong test case) 

#### Description of the bug
**Problem description**
![image](https://user-images.githubusercontent.com/57891237/125939601-f7aab65f-a8d4-4461-a9c9-c67abfcd4214.png)

According to the problem description ```n``` is the number of  people. But I came across 1 test case that does not match the description.
 
![image](https://user-images.githubusercontent.com/57891237/125939432-79426882-1a58-4f86-ad38-39cac7349696.png)

Here we can find that there are no 10 elements even if we insert all the elements to the set.

#### Code you used for Submit/Run operation

```
// Possible Bipartition
class Solution {
public:
    bool possibleBipartition(int a, vector<vector<int>>& dislikes) {
        unordered_set<int> g1, g2, gA;
        
        for(auto x : dislikes){
            gA.insert(x[0]);
            gA.insert(x[1]);
        }
        
        cout<<gA.size();       
        
        for(auto x : dislikes){
            if(g1.count(x[0])){
                g2.insert(x[1]);
            }else if(g2.count(x[0])){
                g1.insert(x[1]);
            }else g1.insert(x[0]);
            
            if(g1.count(x[1])){
                g2.insert(x[0]);
            }else if(g2.count(x[1])){
                g1.insert(x[0]);
            }else g2.insert(x[1]);
        }
        
        int n = g1.size(), m = g2.size();
        
        for(auto x : g1){
            if(g2.count(x)){
                if(n!=1) {
                    n--;
                }else{
                    m--;
                }
            }
        }
        
        return a == n+m;
    } 
};
```

#### Language used for code
C++

#### Expected behavior
Delete the wrong testcase.

**Comment by lc-kay** [comment]
Hi @mecdeality 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mecdeality According to the problem, we have 10 people labeled from 1 to 10 and the one labeled 10 does not dislike anybody. We have updated the problem description a bit to make this point clear. Thank you for your time.
