### ISSUE TITLE
Missing Test Case - 754. Reach a Number

### ISSUE THREAD

**Issue by sumitaby1** [LeetCode-Feedback/LeetCode-Feedback#4197]
#### Your LeetCode username
sumitaby1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the explanation of the first example there is a mistake in second move it should be 1 to 0 not 1 to -1. 
Input: target = 2
Output: 3
Explanation:
On the first move, we step from 0 to 1.
On the second move, we step  from 1 to -1.
On the third move, we step from -1 to 2.

**Comment by lc-kay** [comment]
Hi @sumitaby1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@sumitaby1 The current explanation is correct. The current explanation is correct. In the nth move, we move n steps. 0 --> 1 (1 step) --> -1 (2 steps) --> 2 (3 steps).
