### ISSUE TITLE
Strict runtime-1390. Four Divisors

### ISSUE THREAD

**Issue by harshitkd** [LeetCode-Feedback/LeetCode-Feedback#4198]
#### Your LeetCode username

<a href="https://leetcode.com/harshit_dave/">harshit_dave</a>

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Runtime is too strict

#### Description of the bug

Time Limit Exceeded

#### Code you used for Submit/Run operation

```
// Four Divisors
class Solution:
    def sumFourDivisors(self, nums: List[int]) -> int:
        def divisor(n):
            res = []
            for i in range(1,n+1):
                if n%i==0: res.append(i)
            return len(res)
        
        def sumOfDivisor(n):
            divisors = [1]
            for i in range(2, n+1):
                if (n % i)==0:
                    divisors.append(i)
            return sum(divisors)
        
        arr = []
        for i in nums:
            if divisor(i) == 4: arr.append(sumOfDivisor(i))
        return sum(arr)

```

#### Language used for code
Python

#### Expected behaviour

The runtime should not be too strict.

**Comment by lc-kay** [comment]
@harshitkd I was able to find several accepted Python3 in the problem discuss section. Please check it out https://leetcode.com/problems/four-divisors/discuss/547308/Python3-Short-Easy-Solution
https://leetcode.com/problems/four-divisors/discuss/1118710/Python3-fast-solution-80

Thank you for your time.
