### ISSUE TITLE
Wrong answer given empty string in Word Search

### ISSUE THREAD

**Issue by brandonywl** [LeetCode-Feedback/LeetCode-Feedback#42]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Empty sentence should be an answer in a word search. Instead, the answer comes out to be False.

**what language is your code written in**
Python 3

**The code you submit/run**
```
class Solution:
    def exist(self, board: List[List[str]], word: str) -> bool:      
        if not word: return True 
        r = len(board)
        c = len(board[0])
        l = len(word)
        
        for row in range(r):
            for col in range(c):
                if self.dfs(board, row, col,word):
                    return True
        return False
                        
                    
                        
        
    def dfs(self, board, row, col, word):
        if len(word) == 0:
            return True
        if row<0 or row>=len(board) or col<0 or col>=len(board[0]) or word[0]!=board[row][col]:
            return False
        tmp = board[row][col]  # Hold char to replace board when backtracking
        
        board[row][col] = "#"  # Prevent double-counting
        
        tests = [(row+1, col), (row-1, col), (row,col+1), (row,col-1)]
        
        for test in tests:
            result = self.dfs(board, test[0], test[1], word[1:])
            if result:
                return True
        board[row][col] = tmp
        return False
```

**Expected behavior**
A null set is a subset of all sets.

Hence, an empty sentence should always be able to be found on the board.

The returned result when the input is an empty string "" should be True, but is instead False.

**Screenshots**
![image](https://user-images.githubusercontent.com/28587601/76627556-2cc6e500-6576-11ea-85bc-36b06e3e95f1.png)
When string is empty, True is wrong

![image](https://user-images.githubusercontent.com/28587601/76627612-4405d280-6576-11ea-93b3-1dc4a5fdf313.png)
When string is empty, False is correct.

**Additional context**
I changed the code in line 3 to output False or True when the sentence is empty.

**Comment by CooperCooperCooper** [comment]
Hi @brandonywl,
Thank you for reaching out to us. I've filed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @brandonywl,
Thank you for your time. We've fixed the issue by updating the problem with test cases and more. If you have any other questions, please feel free to let us know. We appreciate your support.
