### ISSUE TITLE
Missing testcase in problem 516

### ISSUE THREAD

**Issue by cowtony** [LeetCode-Feedback/LeetCode-Feedback#420]
#### Your LeetCode username
cowtony

#### Category of the bug
- [ ] Question: 516
- [ ] Solution: DP
- [ ] Language: c++

#### Description of the bug
The empty string is not considered.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestPalindromeSubseq(string s) {
        // DP vector (row = length, col = start_idx):
        //    b b b a b
        // 0: 0 0 0 0 0
        // 1: 1 1 1 1 1
        // 2: 2 2 1 1
        // 3: 3 2 3
        // 4: 3 3
        // 5: 4
        vector<int> dp_2(s.length(), 0);
        vector<int> dp_1(s.length(), 1);
        vector<int> dp(s.length(), 1);
        
        for (int len = 2; len <= s.length(); ++len) {
            for (int i = 0; i + len <= s.length(); ++i) {
                if (s[i] == s[i + len - 1]) {
                    dp[i] = dp_2[i + 1] + 2;
                }
                dp[i] = max({dp[i], dp_1[i], dp_1[i + 1]});
            }
            
            dp_2 = dp_1;
            dp_1 = dp;
        }
        
        return dp[0];
    }
};
```

#### Language used for code
C++

#### Expected behavior
Run time error if I set test case to `""`.
but the code is accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/30167779/83951192-a3295b00-a7e4-11ea-9049-4bbff05438b0.png)

**Comment by CooperCooperCooper** [comment]
Hi @cowtony ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @cowtony ,
Thank you for your time. Your code was getting Runtime Error because of the implementation because in that test case dp[0] doesn't exist. Since the empty string test case is a corner case, by our current problem standard, we will not be adding it to the problem for now. However, we will keep an eye out for it shall we find it to be needed in the future. Thank you for your support.
