### ISSUE TITLE
Weird error - 514. Freedom Trail

### ISSUE THREAD

**Issue by TheGoodCook155** [LeetCode-Feedback/LeetCode-Feedback#4201]
####TheGoodCoook

#### Category of the bug
- [ x] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

````
// Freedom Trail
class Solution {
   static int res = 0;
  public  static int findRotateSteps(String ring, String key) {
        if (key.length() == 0){
            return res;
        }
        if (ring.substring(0,1).equals(key.substring(0,1))){
            res++;
            return findRotateSteps(ring, key.substring(1));
        }     
        int a = ring.indexOf(key.substring(0,1));
        int b = ring.lastIndexOf(key.substring(0,1));
        int lowest = Math.min(a,b);
       String newStr = findRotateHelper(ring,lowest);
       res = res + lowest;
        return findRotateSteps(newStr,key);
    }
    public static String findRotateHelper(String str, int lowestIndex){
        String rotated = "";
        char[] chars = str.toCharArray();
        for (int i = lowestIndex; i < chars.length; i++){
            rotated = rotated + chars[i];
        }
        for (int i = 0; i < lowestIndex; i++){
            rotated = rotated + chars[i];
        }
        return rotated;
    }
}
````

#### Screenshots

![image](https://user-images.githubusercontent.com/71943427/125968897-c3e7e72a-4885-4af7-a2c3-9767170aeeb9.png)
![image](https://user-images.githubusercontent.com/71943427/125969106-7182bd4e-b9df-4c94-b9f7-e2c73f5b7537.png)

**Comment by TheGoodCook155** [comment]
The explanation did not show...
When I submit the code I'm not getting the correct/real result (the first test passes, the second fails, and the output is not what I expect on the second test). I tested the same code in IntelliJ IDEA (with the first and second test case) and I'm getting the expected result

**Comment by lc-kay** [comment]
<img width="1908" alt="Screen Shot 2021-07-16 at 11 27 03 AM" src="https://user-images.githubusercontent.com/70870126/125992698-5a8d8b01-3bf8-42d0-abdb-c1e155fec736.png">
It appears that you are experiencing different results in run code and submit. 
The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
