### ISSUE TITLE
Missing Test Case - 18. 4Sum

### ISSUE THREAD

**Issue by ieCecchetti** [LeetCode-Feedback/LeetCode-Feedback#4202]
#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
given the input = [-5,5,4,-3,0,0,4,-2]
the test online Expect :[[-5, 0, 4, 5], [-3, -2, 4, 5]]
but ive got : [[5, 4, -3, -2], [5, -3, 4, -2], [-5, 5, 0, 4], [-5, 5, 4, 0]]
The two remaining solution are good solution and unique (considering the different the fact there are 2*(0) and 2*(4) )so i dont get why this test shouldnt pass.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    public List<List<Integer>> fourSum(int[] nums, int target) {
        if(nums.length<4){
            return new ArrayList<>(new ArrayList<>());
        }

        HashSet<List<Integer>> res;
        res = recFindQuad(new ArrayList<>(), Arrays.stream(nums).boxed().collect(Collectors.toList()), target);
        return new ArrayList<>(res);
    }

    private HashSet<List<Integer>> recFindQuad(List<Integer> quad, List<Integer> remaining, int target){
        if(quad.size()==4 && remaining == null){
            if(quad.stream().mapToInt(Integer::intValue).sum() == target)
                return new HashSet<>(Arrays.asList(quad));
            else
                return new HashSet<>(new ArrayList<>());
        }
        HashSet<List<Integer>> res = new HashSet<>();
        while(quad.size()!=4){
            if(quad.size()<(4-1)){
                for(int j=0; (quad.size()+1)+(remaining.size()-1-j) >= 4; j++){
                    ArrayList<Integer> newQuad = new ArrayList<>(quad);
                    newQuad.add(remaining.get(j));
                    res.addAll(recFindQuad(newQuad, remaining.subList(j+1, remaining.size()), target));
                }
            }else{
                // add every pair to the couple to be tested
                for(int j=0; j<remaining.size(); j++){
                    ArrayList<Integer> newQuad = new ArrayList<>(quad);
                    newQuad.add(remaining.get(j));
                    res.addAll(recFindQuad(newQuad, null, target));
                }
            }
            break;
        }
        return res;
    }
};
```

#### Language used for code

Java

#### Expected behavior

The code should, in my opinion pass the test case. The bug is well explained before in the description part.

#### Additional context
Local test check:
java.lang.AssertionError: 
Expected :[[-5, 0, 4, 5], [-3, -2, 4, 5]]
Actual   :[[5, 4, -3, -2], [5, -3, 4, -2], [-5, 5, 0, 4], [-5, 5, 4, 0]]

**Comment by lc-kay** [comment]
@ieCecchetti Please provide your submission details link. Thank you.

**Comment by ieCecchetti** [comment]
What do you mean by submission details link?
Maybe this one?
https://leetcode.com/problems/4sum/

**Comment by Leader-board** [comment]
> [-5, 5, 0, 4], [-5, 5, 4, 0]

The question specifies that _a_, _b_, _c_ and _d_ must be distinct. These two test cases are isomorphic to each other, and hence fail this condition. Sorting the array before checking would be enough.
