### ISSUE TITLE
Missing Test Case - 18. 4Sum

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#4204]
#### Your LeetCode username

archit91

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following valid test case:
```
[1000000000, 1000000000, 1000000000, 1000000000]
0
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> fourSum(vector<int>& nums, int target) {
        sort(begin(nums), end(nums));
        return kSum(nums, target, 0, 4);
    }
    vector<vector<int>> kSum(vector<int>& nums, int target, int start, int k) {
        vector<vector<int>> res;
        if (start == nums.size() || nums[start] * k > target || target > nums.back() * k)
            return res;
        if (k == 2)
            return twoSum(nums, target, start);
        for (int i = start; i < nums.size(); ++i)
            if (i == start || nums[i - 1] != nums[i])
                for (auto &set : kSum(nums, target - nums[i], i + 1, k - 1)) {
                    res.push_back({nums[i]});
                    res.back().insert(end(res.back()), begin(set), end(set));
                }
        return res;
    }
    vector<vector<int>> twoSum(vector<int>& nums, int target, int start) {
        vector<vector<int>> res;
        unordered_set<int> s;
        for (auto i = start; i < nums.size(); ++i) {
            if (res.empty() || res.back()[1] != nums[i])
                if (s.count(target - nums[i]))
                    res.push_back({ target - nums[i], nums[i]});
            s.insert(nums[i]);
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should not be accepted since it fails on the given test case.

#### Additional context

In fact, both C++/Java official solutions fail on the given test case. Either this test case should be added and official solutions should be updated or problem constraints must be updated accordingly.

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
