### ISSUE TITLE
Wrong Example 1 - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by Anshu-jindal** [LeetCode-Feedback/LeetCode-Feedback#4206]
#### Your LeetCode username

Anshu_Jindal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Example 1 of this question shows that the maximum profit that can be achieved is 5 whereas we can achieve a profit of 7 as prices of stocks are = [7, 1, 5, 3, 6, 4].
As we can buy a stock on day 2 at Rs. 1 and sell it on day 3 at Rs. 5. (Profit of Rs. 4)
Now, we can buy the stock on day 4 at Rs.3 and sell it on day 5 at Rs. 6. (Profit of Rs. 3)

Therefore, total profit of Rs. 7

#### Language used for code

C++

#### Screenshots

https://drive.google.com/file/d/1bCGypzRk_fJYDNH75FxeVGQaFZkOL4NF/view?usp=sharing

**Comment by lc-kay** [comment]
@Anshu-jindal Please check out the comment in this discuss post. https://leetcode.com/problems/best-time-to-buy-and-sell-stock/discuss/1012178/Isn't-the-example-wrong.-Total-profit-is-7 Thank you for your time.
