### ISSUE TITLE
Question - 1628. Design an Expression Tree With Evaluate Function

### ISSUE THREAD

**Issue by luckyvs1** [LeetCode-Feedback/LeetCode-Feedback#4208]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The input equivalency to the attached screenshot diagram is incorrect for example 2, when performing a post order traversal the input should have been like the following:

Actual:
```
Input: s = ["4","5","2","7","+","-","*"]
```
Expected:
```
Input: s = ["4","5","7","2","+","-","*"]
```

Otherwise, the diagram would need to be updated to flip the nodes (2 and 7) around and the calculation operation updated to state (7+2) instead of (2+7).

#### Expected behavior

Input for example 2 should be the following:

```
Input: s = ["4","5","7","2","+","-","*"]
```

#### Screenshots

![Screen Shot 2021-07-16 at 8 00 20 PM](https://user-images.githubusercontent.com/25218389/126023348-83ce619c-a5c0-4031-aae3-44c532ff8e54.png)

**Comment by lc-kay** [comment]
Hi @luckyvs1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @luckyvs1 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
