### ISSUE TITLE
142. Linked List Cycle II input and output can be None.

### ISSUE THREAD

**Issue by vinsonlee** [LeetCode-Feedback/LeetCode-Feedback#421]
#### Your LeetCode username

vlee

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Both the input and output can be ListNode or None.

#### Code you used for Submit/Run operation

```
class Solution:
    def detectCycle(self, head: ListNode) -> ListNode:
```

#### Language used for code

Python 3

#### Expected behavior

```
class Solution:
    def detectCycle(self, head: Optional[ListNode]) -> Optional[ListNode]:
```

**Comment by CooperCooperCooper** [comment]
Hi @vinsonlee ,
Thank you for reaching out to us. We received "Run Code" error from both "Run Code" and "Submit" for your code. Can you please share the exact submission on this issue with us so we can take a better look into this issue?

**Comment by vinsonlee** [comment]
Incorrect type hints would not cause a runtime error in Python 3. However, a static checker such as mypy may flag an error.

**Comment by CooperCooperCooper** [comment]
Hi @vinsonlee ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @vinsonlee ,
Thank you for your time. Our team has reviewed the issue thoroughly and decided to keep the problem as-is for now. We will keep an eye on it shall we decide to change it in the future. Thank you again for your support.
