### ISSUE TITLE
Missing Test Case - 927. Three Equal Parts

### ISSUE THREAD

**Issue by demonipun** [LeetCode-Feedback/LeetCode-Feedback#4213]
#### Your LeetCode username
Lonely_Dreamer

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ✔ ] Missing Test Cases 

#### Description of the bug
 BUG : In my solution, I just checked :
 1 -> number of 1's in each part is equal and if distance between first and last 1 in each part is equal
 2 -> number of 0's after each part is >= number of zeroes in the last part. (in the three parts)
 My solution got accepted, then I realised that I did not check the exact sequence in each part which depends upon position 1's and 0's for the binary value.

#### Code you used for Submit/Run operation

```
// Three Equal Parts
class Solution {
public:
    vector<int> threeEqualParts(vector<int>& nums) {
        int n=nums.size(), cnt=0;
        vector<int> pos;
        for(int i=0;i<n;i++)
            if(nums[i]==1)
                cnt++, pos.push_back(i);
        if(cnt%3!=0)
            return {-1,-1};
        if(cnt==0)
            return {0,n-1};
        int m=cnt/3, x=pos[m-1]-pos[0]; 
        if(pos[2*m-1]-pos[m]!=x||pos[cnt-1]-pos[2*m]!=x)
            return {-1,-1};
        int zeroes=n-pos[cnt-1];
        if(pos[m]-pos[m-1]>=zeroes&&pos[2*m]-pos[2*m-1]>=zeroes)
            return {pos[m-1]+zeroes-1,pos[2*m-1]+zeroes};
        return {-1,-1};
    }
};
```

#### Language used for code
C++

#### Expected behavior                                                                                                                                                                    
I did not check the exact sequence of every part in the given question, but it got accepted.
[0,0,1,1,0,1,0,0,1,0,1,1,0,0,0,1,0,1,1,0,0] -> It gives Wrong Answer.
Very weak test cases.
My solution got accepted!!! Shocked!

#### Screenshots 
![LeetCode](https://user-images.githubusercontent.com/71482945/126032968-24c54bbf-4e26-4ab6-8fa3-087c6db767cd.jpg)

**Comment by lc-kay** [comment]
Hi @demonipun 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @demonipun 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
