### ISSUE TITLE
Wrong Test Case - 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by Punk-UnDeaD** [LeetCode-Feedback/LeetCode-Feedback#4215]
#### Category of the bug
- [ ] Wrong Test Cases 

#### Description of the bug

[1,3] - not rotated input

**Comment by lc-kay** [comment]
@Punk-UnDeaD The test case is valid. Please check out this post https://leetcode.com/problems/search-in-rotated-sorted-array/discuss/916717/If-there's-two-numbers-how-is-it-rotated
