### ISSUE TITLE
Simple typo [ 181. Employees Earning More Than Their Managers ]

### ISSUE THREAD

**Issue by Sahilamin219** [LeetCode-Feedback/LeetCode-Feedback#4218]
#### Your LeetCode username
sahilamin219

#### Category of the bug
- [ ] Question
- [ ] Solution
- [YES ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In place of Approach 2 , Approach1 is written .

#### Code you used for Submit/Run operation

```
Approach I: Using JOIN clause [Accepted]
```

#### Expected behavior
change Approach II to Approach I

#### Additional context
link is [here](https://leetcode.com/problems/employees-earning-more-than-their-managers/solution/)

**Comment by lc-kay** [comment]
Hi @Sahilamin219 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Sahilamin219 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
