### ISSUE TITLE
Missing Test Case - 927. Three Equal Parts

### ISSUE THREAD

**Issue by faaswdepkhab** [LeetCode-Feedback/LeetCode-Feedback#4219]
#### Your LeetCode username
faa1976

#### Category of the bug
-  Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The statement of the question requires clarification. Or rather the phrase "all of these parts represent the same binary value". Without this, the question arises about the correctness of test № 37. 
Why, given the test case [1,1,1,1,1,1,0,1,1,1], the correct answer is [2,6]? 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool forwardScan(vector<int>& arr,int pos, int len,int prevpos,vector<int>& r){
        if (pos==arr.size()){
            cout<<"len="<<len<<endl;
            return len==4;
        }    
        if (len>3) return false;
        
        
        
        bool f;
        if (arr[pos]==0){
             f=forwardScan(arr,pos+1,len,prevpos,r);
             cout<<"f1  "<<pos<<" "<<len<<" "<<f<<endl;
             if (f){
               cout<<"push 1 "<<pos<<" "<<len<<endl;
               //if (len%2) r[len/2]=pos;
               return true;
             }
        }   
        
        f=forwardScan(arr,pos+1,len+1,pos+1,r);
        cout<<"f2  "<<pos<<" "<<len<<" "<<f<<endl;
        
        if (f){
            cout<<"push 2 "<<pos<<" "<<len<<endl;
            if (len==3) r[1]=prevpos;
            if (len==1) r[0]=pos;
            return true;
        }    
        return false;
    }
        
    
    
    
    vector<int> threeEqualParts(vector<int>& arr) {
        vector<int> r(2,-1);
//        list<int> l;
        
        
        forwardScan(arr,0,1,0,r);
      
        return r;
    }
};
```

#### Language used for code
C++

**Comment by ankur-kayal** [comment]
@faaswdepkhab you can check the last line of the question
![image](https://user-images.githubusercontent.com/44806622/126044613-04412db9-aaf3-4a84-9c73-912d7a87ebc9.png)
which states that we are allowed to have leading zeros, and in fact for the test case that you mentioned:
`[1,1,1,1,1,1,0,1,1,1]` the answer `[2,6]` is justified as it gives the answer as `[1,1,1], [1,1,1], [0,1,1,1]`. Hope this clarifies your doubt. 😀

**Comment by faaswdepkhab** [comment]
Hello! Thanks for the answer. I already realized my mistake myself. Sorry for disturbing!
18.07.2021, 03:12, Ankur Kayal < ***@***.*** ***@***.*** >
https://github.com/faaswdepkhab @faaswdepkhab you can check the last line of the question https://user-images.githubusercontent.com/44806622/126044613-04412db9-aaf3-4a84-9c73-912d7a87ebc9.png image which states that we are allowed to have leading zeros, and in fact for the test case that you mentioned: [1,1,1,1,1,1,0,1,1,1] the answer [2,6] is justified as it gives the answer as [1,1,1], [1,1,1], [0,1,1,1]. Hope this clarifies your doubt. 😀
