### ISSUE TITLE
Missing Test Case - 859. Buddy Strings

### ISSUE THREAD

**Issue by code-zero0** [LeetCode-Feedback/LeetCode-Feedback#4220]
#### Your LeetCode username

hrithiksaini99

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

A test case is required as it's accepted my buggy code

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    bool buddyStrings(string s, string goal) {
        if(s.length()!=goal.length())return false;
        if(s==goal){
      sort(s.begin(),s.end());
            int i=0;
            while(i<s.size()){
                if(s[i]==s[i+1]) return true;
                i++;
            }
            return false;
        }
         int i=0,sum=0,count=0;
        while(i<s.length()){
            if(s[i]!=goal[i]){
                int index=goal.find(s[i]);
                if(index==-1)
                    return false;
               swap(s[i],s[index]);
                if(s.compare(goal)==0) return true;
                break;
               
            }
            i++;
        }
     return false;}

};
```

#### Expected behavior

It should've failed if another test case had been added
"abcacaba"
"abbacaca"
but it got submitted

**Comment by code-zero0** [comment]
this test case should be added in evaluation

**Comment by lc-kay** [comment]
Hi @code-zero0 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @code-zero0 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
