### ISSUE TITLE
73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by HosseinSheikhi** [LeetCode-Feedback/LeetCode-Feedback#4222]
#### Your LeetCode username
hosh0425

#### Category of the bug
- [x] Question
- [] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The second hint is wrong. Based on the input `-231 <= matrix[i][j] <= 231 - 1` that covers all the `int` intervals, one can't use any dummy number because it might already be in the matrix. It seems that there has been a solution for this hint but is removed based on the user's report, but the hint still remains. Please remove this hint.

**Comment by lc-kay** [comment]
Hi @HosseinSheikhi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@HosseinSheikhi The hint is using contradiction to lead the user to a solution. The hint suggests using a dummy value but then says that there is still a better approach.
The user has to think about why we want something better than the dummy value.
The hint is correct and was not changed.
