### ISSUE TITLE
Missing Test Case - 79. Word Search

### ISSUE THREAD

**Issue by orc-dev** [LeetCode-Feedback/LeetCode-Feedback#4227]
#### Category of the bug
- [ ] Question: 79
- [ ] Solution
- [ ] Language: Java
- [ ] Missing Test Cases 

```
# missing test cases examples: 
[["C","A","A"],["A","A","A"],["B","C","D"]]
"BAA"
```

#### Description of the bug

I have checked some submitted solutions with fast runtime, however I found we may miss some test cases, so that some
problematic solutions are accepted.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by orc-dev** [comment]
I think some accepted submissions did not update the visited cells correctly, adding some extra test cases are necessary.

**Comment by lc-kay** [comment]
@orc-dev Please provide the solution that is currently accepted but will not pass this test case. Thank you.

**Comment by lc-kay** [comment]
Hi @orc-dev 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
