### ISSUE TITLE
Solution is wrong. #476. Number Complement

### ISSUE THREAD

**Issue by vladcrash** [LeetCode-Feedback/LeetCode-Feedback#4228]
#### Your LeetCode username

Vlad1337

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 2: Compute Bit Length and Construct 1-bits Bitmask is wrong. It doesn't work with a test case when num is Int.MAX_VALUE (2147483647) because it overflows. 

#### Code you used for Submit/Run operation

I've used the same code as it is in the Approach 2 but in Kotlin 

```
import kotlin.math.*

class Solution {
    fun findComplement(num: Int): Int {
        val highestOneBit = log2(num.toFloat()).toInt() + 1
        val bitmaskOfOnes = (1 shl highestOneBit) - 1
   
        return num xor bitmaskOfOnes
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

Output: 2147483647
Expected: 0

**Comment by lc-kay** [comment]
@vladcrash Both the codes in Approach 2 is accepted with the test case 2147483647. Please check out other Kotlin codes here https://leetcode.com/problems/number-complement/discuss/?currentPage=1&orderBy=most_relevant&query=Kotlin Thank you for your time.

**Comment by vladcrash** [comment]
Oops, you are right. I should have used num.toDouble() instead of num.toFloat(). My bad.
