### ISSUE TITLE
Missing Test Case - 79. Word Search

### ISSUE THREAD

**Issue by orc-dev** [LeetCode-Feedback/LeetCode-Feedback#4229]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
```
# here is another missing test case
[["A","B","C","E"],["S","F","E","S"],["A","D","E","E"]]
"ESEEDASFECBA"
```

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@orc-dev Please provide the accepted solution that will fail on this test case. Thank you.

**Comment by lc-kay** [comment]
Hi @orc-dev 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
