### ISSUE TITLE
379. Design Phone Directory

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#423]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing constraints

#### Code you used for Submit/Run operation

```
class PhoneDirectory(object):
    def __init__(self, m):
        self.s=set(range(m))

    def get(self):
        return self.s.pop() if self.s else -1

    def check(self, n):
        return n in self.s

    def release(self, n):
        self.s.add(n)
```

#### Language used for code
Python

#### Expected behavior
The solution is accepted but fails for the test case

```
["PhoneDirectory","get","get","check","get","check","release","check"]
[[100000000],[],[],[2],[],[2],[2],[2]]
```

An accepted solution should pass all test cases within the constraints. So either this should not pass or test case should be invalidated.

1<=m<=10000 is valid which I verified using assert.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. Upon further review of this submission, our team found the test case to be invalid. Hence, there is no reward for this submission. We appreciate your support.

**Comment by leet212** [comment]
Hello @CooperCooperCooper . Thank you for your response.

- How the test case was deemed invalid when there were no constraints present? Any test case can be classified invalid if constraints are added afterwards.

- The issue was not about the test case but the constraints.


> #### Description of the bug
> Missing constraints

- In the issue the test case's validity was mentioned

> So either this should not pass or test case should be invalidated.

- Using the feedback in this issue 

> 1<=m<=10000 is valid which I verified using assert.

the judge's response was modified to invalidate the test case

> Invalid Testcase
> expected 'maxNumbers' to have value from 1 to 10000 only

and also modification has been made in the problem statement.

> Constraints:
> 
> 1 <= maxNumbers <= 10^4

**Comment by CooperCooperCooper** [comment]
HI @leet212 ,

Thank you for the explanation. You're correct about the constraint. My apologies for the mistake. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. Thank you again for your thorough input.
