### ISSUE TITLE
Calling order of ENCODE and DECODE methods has to be random - 535

### ISSUE THREAD

**Issue by Veera-Lab** [LeetCode-Feedback/LeetCode-Feedback#4231]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I see all test cases are passing for the invalid solution I submitted https://leetcode.com/submissions/detail/524558647/. If the decode method is being called always after encode method, there is no need of using Hashmap or Array  instead encoded string can be set to a variable and return the value when the decode method is called.

#### Code you used for Submit/Run operation
``` 
public class Codec {
    String[] array = new String[1];
    int count = -1;
    
    // Encodes a URL to a shortened URL.
    public String encode(String longUrl) {
        count++;
        array[0] = longUrl;
        return count+"";
    }

    // Decodes a shortened URL to its original URL.
    public String decode(String shortUrl) {
       return array[Integer.valueOf(shortUrl)];
    }
}

#### Language used for code
Java


#### Expected behavior
1. I wish the calling of encode and decode has to be random
2. In addition if the decoded string has to be validated to be a valid decoded url

**Comment by lc-kay** [comment]
Hi @Veera-Lab 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Veera-Lab Thanks for this feedback but we cannot change the driver for consistency. We may consider this when we publish a new version of it.
However, this is a practice problem and the user should focus on implementing a good algorithm instead of hacking the driver code and cheating to get the problem AC.

**Comment by Veera-Lab** [comment]
@lc-kay Looks like you are calling ur users as cheaters ? I’m not sure if this is the way you should answer  to your users here. If this is something that you cannot handle it then better assign it someone else. 
Between I knew it is a practice problem so that is why I initially had come up with this solution and thought that this is final answer but when I looked at the solutions I see different answers, in case I didn’t look at the solutions then what happens ? What if I use the same solution in the actual interview and lost it ? Would you say that it is because of my  poor thought process or because the way the leet code exists today ?  
Again I don’t wanted to talk to you like this but as you tried to act smart instead of being polite and respectful to others.
