### ISSUE TITLE
236. Lowest Common Ancestor of a Binary Tree - Incomplete animation for Approach 1

### ISSUE THREAD

**Issue by ankitgin** [LeetCode-Feedback/LeetCode-Feedback#4232]
#### Your LeetCode username
ankitgin

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

236. Lowest Common Ancestor of a Binary Tree

In the solution for "Approach 1: Recursive Approach" the animation does not matches the working of the code. 
The code is written in bottom-up fashion and will go both left and right side from the root, event if both the required nodes p and q are on the left side of the tree. However, animation makes it feel like if we have found the solution on the left side, we won't traverse the right side of the tree.

To fix this, either the animation needs to be complete and show that even after finding the solution, we will traverse the right side of the tree as well. OR you can update the code to check if the status of the flags before traversing to the right side of the tree. If the solution is not met from the left tree and current node, we then traverse to the right and check the flags again.

https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/solution/

#### Code you used for Submit/Run operation

Below is an example of the updated code that matched the animation:

```
class Solution {

    private TreeNode ans;

    public Solution() {
        // Variable to store LCA node.
        this.ans = null;
    }

    private boolean recurseTree(TreeNode currentNode, TreeNode p, TreeNode q) {

        // If reached the end of a branch, return false.
        if (currentNode == null) {
            return false;
        }

        // Left Recursion. If left recursion returns true, set left = 1 else 0
        int left = this.recurseTree(currentNode.left, p, q) ? 1 : 0;

        // If the current node is one of p or q
        int mid = (currentNode == p || currentNode == q) ? 1 : 0;

        // If any two of the flags left or mid become True
        if (mid + left == 2) {
            this.ans = currentNode;
            return 1;                            //.  <<=== so we don't go to the right side
        }

        // Right Recursion
        int right = this.recurseTree(currentNode.right, p, q) ? 1 : 0;

        // If any two of the flags left, right or mid become True
        if (mid + left + right >= 2) {
            this.ans = currentNode;                       
        }

        // Return true if any one of the three bool values is True.
        return (mid + left + right > 0);
    }

    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {
        // Traverse the tree
        this.recurseTree(root, p, q);
        return this.ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior
To fix this, either the animation needs to be complete and show that even after finding the solution, we will traverse the right side of the tree as well. OR you can update the code to check if the status of the flags before traversing to the right side of the tree. If the solution is not met from the left tree and current node, we then traverse to the right and check the flags again.

**Comment by lc-kay** [comment]
Hi @ankitgin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ankitgin,
Thank you for your insights. They are appreciated and will be taken into consideration if/when the article is updated.
