### ISSUE TITLE
Question description is ambiguous - 743. Network Delay Time

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4233]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

"Return the time" is ambiguous 
Can it be minimum or maximum time? Are both accepted?

TEST CASE

[[1,2,1],[2,3,2],[1,3,2]]
3
1

EXPECTED

2

----

1->2->3 total time is 1+2 = 3
1->3 total time is 2 = 2
The answer is 2, how is it possible? it's unclear from the description

#### Code you used for Submit/Run operation

```
```

#### Expected behavior
Question description must not be ambiguous

This wasted so much time

> Return the time
should be
> Return the minimum time

See description above

#### Screenshots

![image](https://user-images.githubusercontent.com/8236389/126089260-25732fa6-b204-4d82-827f-1f9dcb1b6671.png)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@manoharreddyporeddy According to the problem statement, there is one exact time at which all the nodes will have a copy of the signal so one cannot think about min or max. Thank you for your time.
