### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by gitreddy** [LeetCode-Feedback/LeetCode-Feedback#4234]
#### Your LeetCode username
vrreddy

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This test is wrong:
Input
[1,2,-2,-1]
Output
[[1,-2,1],[2,-1,-1]]
Expected
[]
I believe my code is returning the right result for this test.

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<Integer>> threeSum(int[] nums) {
   	List<List<Integer>> retVal = new ArrayList<List<Integer>> ();
    	
		ArrayList<Integer> checkList = new ArrayList<Integer>();
		for (int i=0; i<nums.length; i++)
		{    	
			checkList.add(nums[i]);
		}
    	
    	for (int i = 0; i<nums.length && nums.length >=3; i++)
    	{

    		for (int j=i+1; j<nums.length ; j++)
    		{
				int exp = (0 - (nums[i]+nums[j]));
				

		 		if (checkList.contains((exp)))
		 		{
    					boolean found=false;
    					checkList.remove(new Integer(exp));

    			    	List<Integer> inner;
    			    	
   			    		for (int ctr = 0; ctr < retVal.size(); ctr++)
    					{
    						inner = retVal.get(ctr);
    						
    						if (nums[i] == nums[j] && nums[j] == exp) // all zero case
    						{
    							ArrayList<Integer> temp = new ArrayList<Integer> () {
    								{
    									add (0);
    									add (0);
    									add (0);
    								}
    							};
    							if (inner.equals(temp))
    							{
    								found = true;
    								break;
    							}
    						}	
    						else if (inner.contains(nums[i]) && inner.contains(nums[j]) && inner.contains(exp))
    						{

  								found = true;
  								break;
   							}
    					}
 
   			    		if (!found)
    					{
    						inner = new ArrayList<Integer>();
    						inner.add(nums[i]);
       						inner.add(nums[j]);
       						inner.add(exp);
       						retVal.add(inner);
    					}

    				}
    			}
    		}
    	return retVal;    

    }
}
```

#### Language used for code
Java

#### Expected behavior
My code returned the right set of 3 number that add up to zero.

#### Screenshots

![image](https://user-images.githubusercontent.com/8767860/126095719-ad4d4255-4375-4caa-abf2-7077291aa59c.png)

**Comment by sankalpkotewar** [comment]
The question also mentions - 
triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k

In your case the numbers are repeating. 1 is present only once at first index but you're returning it twice in the output which is wrong.

**Comment by lc-kay** [comment]
@gitreddy Please refer to @sankalpkotewar comment or the discuss section for clarification. Thank you for your time.
