### ISSUE TITLE
Missing Test Case - 235. Lowest Common Ancestor of a Binary Search Tree

### ISSUE THREAD

**Issue by HETFADIA** [LeetCode-Feedback/LeetCode-Feedback#4235]
#### Your LeetCode username
HETFADIA

#### Category of the bug
- [ Lowest Common Ancestor of a Binary Search Tree] Question
- [https://leetcode.com/submissions/detail/524890056/?from=explore&item_id=3819 ] Solution
- [c++ ] Language
- [ 1] Missing Test Cases 

#### Code you used for Submit/Run operation
```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */

TreeNode * answer= new TreeNode(-10102);
int  lca(TreeNode * root,TreeNode * p,TreeNode * q){
    int val=0;
    if(root){
        val+=lca(root->left,p,q);
        val+=lca(root->right,p,q);
        val+=(root==p)+(root==q);
        if(val==2 and answer->val==-10102){
            answer=root;
        }
    }
    return val;
}
class Solution {
public:
    TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) {
        answer=new TreeNode(-10102);
        lca(root,p,q);
        return answer;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code should give wa on a test case [testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6839876/testcase.txt) but passes main tests

#### Screenshots
![image](https://user-images.githubusercontent.com/62541263/126143138-2ead64f9-43b8-4ef5-8ff8-e8001e96131d.png)
WA on the given test file still accepted

#### Additional context
The Code
[solutioncpp.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6839871/solutioncpp.txt) passes the main test cases but gives WA on test case 
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6839876/testcase.txt)

**Comment by lc-kay** [comment]
Hi @HETFADIA 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@HETFADIA Our team didn't add this test case because this solution depends on a special value -10102 and we need an infinite number of test cases to fail it because it can be always fixed. Thank you for your time.
