### ISSUE TITLE
Space between number and word is missing in explanation section

### ISSUE THREAD

**Issue by boymurodovuzcoder** [LeetCode-Feedback/LeetCode-Feedback#4237]
#### Your LeetCode username
@samandar_boymurodov

#### Category of the bug
- [ ] Language

#### Description of the bug

It is just minor mistake in explanation. 
> 3is the length of the path [4,2,1,3] or [5,2,1,3].

Instead of 3is, it is better to be **3 is**.

#### Code you used for Submit/Run operation

No code

#### Expected behavior

I just want that minor improvement to happen. It is not a big deal actually. But, it will be much comfortable to read if space would be added

#### Screenshots
![image](https://user-images.githubusercontent.com/65066111/126181777-d3e62cff-ae26-4f5e-ab53-d2aa16ebbd50.png)

**Comment by boymurodovuzcoder** [comment]
543. Diameter of Binary Tree

**Comment by lc-kay** [comment]
Hi @boymurodovuzcoder 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
