### ISSUE TITLE
1228. Missing Number In Arithmetic Progression

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#424]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing test cases

#### Code you used for Submit/Run operation

```
class Solution(object):
    def missingNumber(self, a):
        d=(a[-1]-a[0])/len(a)
        for i,v in enumerate(a):
            if a[0]+d*i!=v:
                return a[0]+d*i
        return 0
```

#### Language used for code
Python

#### Expected behavior
Fails for the test case

```
[1,1,1]
```

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

We're working on reducing steps on rewarding you for your contributions, so please share your LeetCode username in the issues you've opened.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
