### ISSUE TITLE
Missing Test Case - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by PsiHamster** [LeetCode-Feedback/LeetCode-Feedback#4241]
#### Your LeetCode username

zempty

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is no testcase with comparing serialization of two different objects with the same data.

#### Code you used for Submit/Run operation

```
public class Codec {
    public static Dictionary<string, TreeNode> Nodes = new Dictionary<string, TreeNode>();
    
    // Encodes a tree to a single string.
    public string serialize(TreeNode root) {
        var key = Guid.NewGuid().ToString();
        Nodes[key] = root;
        return key;
    }

    // Decodes your encoded data to tree.
    public TreeNode deserialize(string data) {
        return Nodes[data];
    }
}
```

#### Language used for code

C#

#### Expected behavior

There will be some test cases to prevent serialization-deserialization without actual serialization :)

**Comment by lc-kay** [comment]
@PsiHamster For a valid missing test case report, please provide a test case that will fail the accepted solution. Thank you.

**Comment by PsiHamster** [comment]
Any data will work in any case. Only one possible test will fall (until GetHashCode() not implemented)

Something like
```
void ThatTwoDifferentObjectsReturnsSameString_Test() {
    var obj1 = // Create obj1 from input string
    var obj2 = // Create obj2 from same input string
    
    var codec = new Codec();
        
    codec.Serialize(obj1).Should().Be(codec.Serialize(obj2));
}
```

Or it should restart testing assembly before deserializing

**Comment by lc-kay** [comment]
Hi @PsiHamster 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@PsiHamster Thank you for your feedback, however, this is how the driver was designed. We have recorded your feedback and will make updates in next version of this problem.
