### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: ListNode.getKey()I

### ISSUE THREAD

**Issue by mr3y-the-programmer** [LeetCode-Feedback/LeetCode-Feedback#4242]
I have an issue running my code because whenever I try to access a normal instance property, leetcode runtime compiler somehow crashes due to NoSuchMethodError, though there is nothing suspicious or custom in my code. it is a simple kotlin code 

#### Your LeetCode username

M R 3 YY

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

trying to access `key` property like the following:
```kotlin
var key = 3
var current: ListNode? = ListNode(2)
current?.key == key
```
where ListNode is:
```kotlin
class ListNode(var key: Int) {
    var next: ListNode? = null
}
```
results in:
```
Line 19: Exception in thread "main" java.lang.NoSuchMethodError: ListNode.getKey()I
```
#### Code you used for Submit/Run operation

```kotlin
class MyHashSet() {

    /** Initialize your data structure here. */
    private var head: ListNode? = null

    fun add(key: Int) {
        if(head == null) {
            head = ListNode(key)
        } else {
            var current = head
            while(current != null) {
                if(current?.key == key) return@add
                current = current?.next
            }
            current = head
            while(current?.next != null) current = current?.next
            current = ListNode(key)
            current?.next = head
            head = current
        }
    }

    fun remove(key: Int) {
        when {
           head == null -> return
           key == head?.key -> {
               head = head?.next 
               return
           }
           else -> {
                var current = head?.next
                var prev = head
                while(current != null) {
                    if(current?.key == key) {
                        prev?.next = current?.next
                        current = null
                        return
                    }
                    current = current?.next
                    prev = prev?.next
                }
           }
        }
    }

    /** Returns true if this set contains the specified element */
    fun contains(key: Int): Boolean {
        if(head == null) return false
        var current = head
        while(current != null) {
            if(current.key == key) return true
            current = current?.next
        }
        return false
    }
}

class ListNode(var key: Int) {
    var next: ListNode? = null
}
```

#### Language used for code

Kotlin

#### Expected behavior

It should compile and run without any exceptions!

#### Additional context

Some solutions that didn't work:
- changing the property name to something else
- changing the property's accessor method to something else by using: `@get:JvmName("anotherNameThanGetKey")`

**Comment by lc-kay** [comment]
@mr3y-the-programmer Please provide the problem number and title. Thank you.

**Comment by mr3y-the-programmer** [comment]
705. Design HashSet

**Comment by lc-kay** [comment]
@mr3y-the-programmer Unfortunately, I am unable to provide support in debugging your code. However, I was able to find some accepted Kotlin codes in the problem discuss section for you to reference, like this one. Thank you for your time. 
<img width="908" alt="Screen Shot 2021-07-27 at 11 22 02 AM" src="https://user-images.githubusercontent.com/70870126/127207388-43527734-a47e-49ca-a965-7a20ba9ec534.png">
