### ISSUE TITLE
Missing Test Case - 477. Total Hamming Distance

### ISSUE THREAD

**Issue by BeiqiD** [LeetCode-Feedback/LeetCode-Feedback#4243]
#### Your LeetCode username
BeiqiD

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Current solution is not valid for large size test cases.

#### Code you used for Submit/Run operation

```
class Solution:
    def totalHammingDistance(self, nums: List[int]) -> int:
        multi = [0]*32
        m = lambda x: x * (len(nums)-x)
        for n in nums:
            s = '{:032b}'.format(n)
            for i in range(0, 32):
                multi[i] = multi[i] + int(s[i])
        for i in range(0,32):
            multi[i] = m(multi[i])
        return sum(multi)
```
Submitted code has passed 46 / 46 test cases.
#### Language used for code

Python

#### Expected behavior

The expected output should be a non-negative integer.

#### Screenshots

![image](https://user-images.githubusercontent.com/57419696/126273721-acf4f2b2-a925-45da-b4d5-cfbf3aef6b99.png)

#### Additional context

The testcase applied is a list with 32000 random generated integers, which satisfies the constraints. 
```
random.sample(range(0, 1000000000), 32000)
```

**Comment by lc-kay** [comment]
@BeiqiD Please provide the test case in .txt format. Thank you.

**Comment by BeiqiD** [comment]
@lc-kay Please refer to the attached file, thank you. [test_case_477.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6852811/test_case_477.txt) 
(Note: This test case is not directly generated by ```random.sample(range(0, 1000000000), 32000)``` but by 
 ```random.sample(range(0, 1000000000), 4000)*8```)

**Comment by lc-kay** [comment]
Hi @BeiqiD 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@BeiqiD Since the answer to this test case will not fit in a 32-bit integer. Our team has changed the constraints to prevent this type of test cases. Thank you for your time.
