### ISSUE TITLE
Missing Test Case [40. Combination Sum II]

### ISSUE THREAD

**Issue by ankur-kayal** [LeetCode-Feedback/LeetCode-Feedback#4244]
#### Your LeetCode username
ankurkayal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My current solution gets accepted but it should TLE.

#### Code you used for Submit/Run operation

```cpp
// 40. Combination Sum II
class Solution {
private:
    vector<vector<int>> ans;
public:
    vector<vector<int>> combinationSum2(vector<int>& candidates, int target) {
        sort(candidates.begin(), candidates.end());
        while(!candidates.empty() && candidates.back() > target) {
            candidates.pop_back();
        }
        vector<int> current_set;
        recurse(candidates, current_set, 0, target);
        sort(ans.begin(), ans.end());
        ans.erase(unique(ans.begin(), ans.end()), ans.end());
        return ans;
    }

    void recurse(vector<int>& candidates, vector<int>& current_set, int index, int target) {
        if(target < 0) {
            return;
        }
        if(target == 0) {
            ans.push_back(current_set);
            return;
        }
        if(index >= candidates.size()) {
            return;
        }
        for(int i = 0; i < 2; i++) {
            if(i == 0) {
                recurse(candidates, current_set, index + 1, target);
            } else {
                current_set.push_back(candidates[index]);
                recurse(candidates, current_set, index + 1, target - candidates[index]);
                current_set.pop_back();
            }
        }
    }
};
```

#### Generated Test Case used for testing
```
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
30
```

#### Language used for code
 C++ 

#### Expected behavior

The test case that i specially designed TLE's my code, but it gets accepted in the main tests.

Expected Output is: 

```
[[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]]
```

And my codes TLEs.

#### Screenshots

![image](https://user-images.githubusercontent.com/44806622/126281799-e9afe3bc-5f20-484d-8743-edad04856a0d.png)
![image](https://user-images.githubusercontent.com/44806622/126281837-72561c3a-f300-4df3-9fe3-0bc9a2446af8.png)

**Comment by lc-kay** [comment]
Hi @ankur-kayal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ankur-kayal 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
