### ISSUE TITLE
413. 等差数列划分 题目存在笔误

### ISSUE THREAD

**Issue by YichengZhong** [LeetCode-Feedback/LeetCode-Feedback#4248]
**蛤三不**
frogthreeno

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
中文版题目的描述中有一句：
`元素 A[P], A[p + 1], ..., A[Q - 1], A[Q] 是等差的。并且 P + 1 < Q 。`
建议将`A[p+1]`改成`A[P+1]`
这样可以保证前后表达一致。

**你使用的语言**
C++

**期望行为**
暂无

**屏幕截图**
暂无

**额外的上下文**
暂无

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@YichengZhong 你好，当前题目描述已更新，ID：frogthreeno 给予积分奖励，请查收。
