### ISSUE TITLE
Missing Test Case - 207. Course Schedule

### ISSUE THREAD

**Issue by ShubhamSanghvi** [LeetCode-Feedback/LeetCode-Feedback#4249]
#### Your LeetCode username
wanderer_06

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The test cases shown in the question are very limited. There should be a test case that is more detailed and extensive containing at least 5 nodes.

**Comment by lc-kay** [comment]
@ShubhamSanghvi For a valid missing test case report, please provide the missing test case that will cause an accepted solution to fail. When more information is provided, I will reopen this ticket. Thank you for your time.
