### ISSUE TITLE
Wrong Expected Output

### ISSUE THREAD

**Issue by Kartik97** [LeetCode-Feedback/LeetCode-Feedback#425]
#### Your LeetCode username

jainkartik203

#### Category of the bug
- [..] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Wrong Expected output

#### Code you used for Submit/Run operation

```
// Combination Sum III
class Solution {
public:
    void solve(int cur,int idx,int k,int n,vector<int>& vis,vector<int>& temp,vector<vector<int>>& ans){
        if(temp.size()==k && cur==n){
            ans.push_back(temp);
            return;
        }
        else if(cur>=n || temp.size()>=k)
            return;

        for(int i=idx;i<=9;i++){
            if(!vis[i]){
                vis[i]=1;
                temp.push_back(i);
                solve(cur+i,i+1,k,n,vis,temp,ans);
                vis[i]=0;
                temp.pop_back();
            }
        }
        
    }
    
    vector<vector<int>> combinationSum3(int k, int n) {
        vector<int> vis(10,0);
        vector<vector<int>> ans;
        vector<int> temp;
        solve(0,1,k,n,vis,temp,ans);
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Input-> k=1,n=10
Expected Output-> [[10]]
Actual Output -> [ ]

Expected Output is wrong since is this case the output should be [ ]

**Comment by CooperCooperCooper** [comment]
Hi @Kartik97 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @Kartik97 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
