### ISSUE TITLE
Missing Test Case - 927. Three Equal Parts

### ISSUE THREAD

**Issue by mittaldheeraj11** [LeetCode-Feedback/LeetCode-Feedback#4250]
Here, test case when all digits are zero needs to handled properly.
Eg : { 0,0,0,0,0 }
Here answer could be {0,2} or {0,3} or {0,4}
#### Your LeetCode username
mittaldheeraj1109

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@mittaldheeraj11 Please provide more information as to how the all-zero test case is not being handled properly. Thank you.

**Comment by lc-kay** [comment]
Hi @mittaldheeraj11 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
