### ISSUE TITLE
Missing Solution - Problem 1588

### ISSUE THREAD

**Issue by Divyaansh313** [LeetCode-Feedback/LeetCode-Feedback#4251]
#### Your LeetCode username
Divyaansh313

#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Missing Solution of the Problem "1588. Sum of All Odd Length Subarrays"

#### Code you used for Submit/Run operation

```
# Sum of All Odd Length Subarrays
class Solution:
    def sumOddLengthSubarrays(self, arr: List[int]) -> int:
        total = 0
        for i in range(0, len(arr)+1, 2):
            for j in range(len(arr) - i):
                total += sum(arr[j:j+i+1])
                    
        return total
```

#### Language used for code
Python3

**Comment by lc-kay** [comment]
@Divyaansh313 Please share your solution on the problem discuss page. Thank you for your time.
