### ISSUE TITLE
Missing Test Case - 301. Remove Invalid Parentheses

### ISSUE THREAD

**Issue by ankur-kayal** [LeetCode-Feedback/LeetCode-Feedback#4254]
#### Your LeetCode username
ankurkayal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My current solution passes all existing test cases which I suspected to TLE, so I custom-made a test case, and it is indeed TLE.

#### Code you used for Submit/Run operation

```cpp
// Remove Invalid Parentheses
class Solution {
public:
    vector<string> removeInvalidParentheses(string s) {
        int n = s.length();
        vector<vector<string>> ans(n + 1);
        int mini = 1e5;
        for(int mask = 0; mask < (1 << n); mask++) {
            if(n - __builtin_popcount(mask) > mini) {
                continue;
            }
            string tmp = "";
            for(int bit = 0; bit < n; bit++) {
                if(mask & (1 << bit)) {
                    tmp += s[bit];
                }
            }
            int balance = 0;
            for(auto u: tmp) {
                if(u == '(') {
                    balance++;
                } else if(u == ')') {
                    balance--;
                }
                if(balance < 0) {
                    break;
                }
            }
            if(balance == 0) {
                ans[n - __builtin_popcount(mask)].push_back(tmp);
                mini = min(mini, n - __builtin_popcount(mask));
            }
        }
        for(int i = 0; i < n; i++) {
            if(!ans[i].empty()) {
                sort(ans[i].begin(), ans[i].end());
                ans[i].erase(unique(ans[i].begin(), ans[i].end()), ans[i].end());
                return ans[i];
            }
        }
        return ans[n];
    }
};
```

#### Language used for code
 C++

#### Expected behavior

It is expected my solution would TLE but it still passed on the existing test cases.

#### Test cases used

Test Case 1:

```
"((((((((((((((((((((aaaaa"
```

Expected Output: 

```
["aaaaa"]
```

Test Case 2:

```
"))))))))))))))))))))aaaaa"
```

Expected Output: 

```
["aaaaa"]
```

And my code TLE's for both the test cases I generated.

#### Expected  Output
![image](https://user-images.githubusercontent.com/44806622/126445299-23feb716-14bd-4a34-a6da-f87e41596ce3.png)
#### Output got in my code
![image](https://user-images.githubusercontent.com/44806622/126445440-4804a999-7cc9-4a66-91ac-89eef4b4e338.png)

**Comment by lc-kay** [comment]
Hi @ankur-kayal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ankur-kayal 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
