### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by player0130** [LeetCode-Feedback/LeetCode-Feedback#4256]
#### Your LeetCode username

player0130

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

 [linked-list-cycle](https://leetcode.com/problems/linked-list-cycle) missing test case like `[1,1,1,1] , -1`

#### Code you used for Submit/Run operation

```
function hasCycle(head: ListNode | null): boolean {
    if (head == null || head.next == null){
        return false
    }
    let slow = head
    let fast = head.next
    while(fast!==null && fast.next !== null && fast.next.next !== null){
        slow = slow.next
        fast = fast.next.next
        if (slow.val == fast.val){
            return true
        }
    }
    return false
};
```

#### Language used for code

Typescript

#### Expected behavior

When the input is `[1,1,1,1] , -1` , the output will be `true` but expected output should be `false`.
but this submission was accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/9380750/126462669-ab9d1e35-4478-4d12-95bb-6af8a9b5aeeb.png)

**Comment by lc-kay** [comment]
Hi @player0130 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @player0130 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
