### ISSUE TITLE
Missing Test Case - 241. Different Ways to Add Parentheses

### ISSUE THREAD

**Issue by rexhyh** [LeetCode-Feedback/LeetCode-Feedback#4258]
#### Your LeetCode username
rexhyh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

might need to consider the first operant was a nagetive, for example the expression might be: -2-3-4-5-6

**Comment by lc-kay** [comment]
@rexhyh For a valid missing test case report, please provide the accepted code that this test case will fail. Thank you.

**Comment by lc-kay** [comment]
Hi @rexhyh 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
