### ISSUE TITLE
Missing Test Case - 1049. Last Stone Weight II

### ISSUE THREAD

**Issue by Shikhar-Soni** [LeetCode-Feedback/LeetCode-Feedback#4261]
#### Your LeetCode username

marcus_marble

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing testcase, incorrect program gives AC.

#### Code you used for Submit/Run operation

The following program gives AC but fails on the counter test case given below.

```
class Solution {
public:
    int lastStoneWeightII(vector<int>& a) {
        int n = a.size();
        bitset<1200> tt(1);
        int sm = 0;
        for(int i = 0; i < n; i++){
            tt |= tt << a[i];
            sm += a[i];
        }
        for(int i = sm/2; i >= 0; i--){
            if(tt[i]) return sm - 2 * i;
        }
        return sm;
    }
};
```
#### Language used for code

 C++

#### Expected behavior

This program should under the constraints of the question give runtime error.
The given test case will cause it to give runtime error but it passes all test cases.

Counter test case : [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]

#### Screenshots

![image](https://user-images.githubusercontent.com/76754168/126562937-ce39fea6-3345-432d-bbe2-5a5125c96c4b.png)

**Comment by lc-kay** [comment]
Hi @Shikhar-Soni 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Shikhar-Soni 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
