### ISSUE TITLE
Testcase missing - 198. House Robber I

### ISSUE THREAD

**Issue by MayankMaheshwar** [LeetCode-Feedback/LeetCode-Feedback#4264]
[1,5,1,1,4] is also accepted even its correct answer is 9

**Comment by lc-kay** [comment]
@MayankMaheshwar Please provide the accepted code that fails on this test case. Thank you.

**Comment by MayankMaheshwar** [comment]
Sorry, @lc-kay I don't know what happens...now it's giving the same output. Please close this issue.

thank you
