### ISSUE TITLE
Suboptimal solution - 915. Partition Array into Disjoint Intervals

### ISSUE THREAD

**Issue by bryzgaloff** [LeetCode-Feedback/LeetCode-Feedback#4265]
#### Your LeetCode username

https://leetcode.com/bryzgaloff/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/partition-array-into-disjoint-intervals/solution/ describes not an optimal solution. The optimal one is suggested in a comment: https://leetcode.com/problems/partition-array-into-disjoint-intervals/solution/224152

I may give an explanation to this solution. Let me know if needed.

#### Code you used for Submit/Run operation

My code, accepted:

```python
class Solution:
    def partitionDisjoint(self, nums: List[int]) -> int:
        left_max = total_max = nums[0]
        left_end = 1
        for i, left_num in enumerate(nums, start=1):
            if left_num < left_max:
                left_end = i
                left_max = total_max
            total_max = max(total_max, left_num)
        return left_end
```

#### Language used for code

Python

**Comment by PyroGenesis** [comment]
Agreed. I settled on a similar solution.

```py
class Solution:
    def partitionDisjoint(self, nums: List[int]) -> int:
        n = len(nums)
        if n == 0:
            return 0
        
        left_max = nums[0]
        global_max = nums[0]
        partition_length = 1
        
        for i in range(1, n):
            if nums[i] < left_max:
                partition_length = i+1
                left_max = global_max
            else:
                global_max = max(global_max, nums[i])
                
        return partition_length
```

**Comment by lc-kay** [comment]
@bryzgaloff Thanks for reaching out to us. Our team will review this and apply it to our upcoming edits.
