### ISSUE TITLE
Missing test case - 1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence

### ISSUE THREAD

**Issue by WaleedMortaja** [LeetCode-Feedback/LeetCode-Feedback#4266]
#### Your LeetCode username

waleedmortaja

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

[Check If a Word Occurs As a Prefix of Any Word in a Sentence](https://leetcode.com/problems/check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence/) problem is missing a test case of: "abcad" , "ad"

#### Code you used for Submit/Run operation

```
class Solution {
    public int isPrefixOfWord(String s, String se) {
        String[] words=s.split(" ");
        for(int i=0;i<words.length;i++)
        {
            if(words[i].contains(se))
            {
			//if contains also we have to check prefix that's y we are checking at index at 0 is same or not
                 if(words[i].charAt(0)==se.charAt(0)) return i+1;
            }
        }
        return -1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on a test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/27075022/126637465-572ba6f3-9439-48ed-9feb-088f7fa74f6d.png)

#### Additional context

[Discussion post](https://leetcode.com/problems/check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence/discuss/1346762/Java-Easy-or-100-faster-or-less-than-90-or-main-one-line-code) that is the source of the given code.

**Comment by lc-kay** [comment]
Hi @WaleedMortaja 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @WaleedMortaja 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by WaleedMortaja** [comment]
@lc-kay Thank you! I am happy to help :)

**Comment by WaleedMortaja** [comment]
@lc-kay Side (not related) question: How can I report about a solution that has content mistake, broken markup or at least a typo?

**Comment by lc-kay** [comment]
@WaleedMortaja You can report it in this repo as well :)
