### ISSUE TITLE
865. Smallest Subtree with all the Deepest Nodes - Incorrect Test Case

### ISSUE THREAD

**Issue by anuragb1090** [LeetCode-Feedback/LeetCode-Feedback#4267]
#### Your LeetCode username
anuragb1090

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I ran the same code using the 'Submit' and 'Run Code' button but the results are different. So either the test case is wrong or my code is not being picked up correctly. I have attached a screenshot to illustrate.

#### Code you used for Submit/Run operation

```
from collections import defaultdict
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    depth_list = []
    ans=None
    def subtreeWithAllDeepest(self, root: TreeNode) -> TreeNode:        
        self.fetch_depth(root, 0)
        dd = defaultdict(list)
        max_depth=0
        for i in range(len(self.depth_list)):
            dd[self.depth_list[i][0]].append(self.depth_list[i][1])
            max_depth = max(max_depth, self.depth_list[i][0])

        self.dfs(root, max_depth, dd)
        
        return self.ans
    
    def dfs(self, root, max_depth, dd):
        if not root:
            return

        if root.left and root.left.val==dd[max_depth][0] and root.right and root.right.val==dd[max_depth][1]:
                # print(root)
                self.ans=root
                return 
        elif root.val==dd[max_depth][0]:
                self.ans=root
                return 

        self.dfs(root.left, max_depth, dd)
        self.dfs(root.right, max_depth, dd)
    
    def fetch_depth(self, root, depth):
        if not root:
            return
                
        self.depth_list.append((depth, root.val))
        if root.left:
            self.fetch_depth(root.left, depth+1)
        if root.right:
            self.fetch_depth(root.right, depth+1)         
```

#### Language used for code

Python3

#### Expected behavior

Both the results coming out of 'Submit' and 'Run code' button should be the same but in this case it's not.

#### Screenshots

<img width="1435" alt="Screenshot 2021-07-22 at 18 04 23" src="https://user-images.githubusercontent.com/7220358/126639920-dd39e22a-b905-47ea-b197-95e22b1b9e19.png">

**Comment by anuragb1090** [comment]
Another example. I don't know what could be wrong here.

https://leetcode.com/problems/most-frequent-subtree-sum/submissions/

<img width="1440" alt="Screenshot 2021-07-24 at 20 00 11" src="https://user-images.githubusercontent.com/7220358/126871689-69b68c91-54ff-4fd6-88f5-dc3e505b0abf.png">

**Comment by lc-kay** [comment]
Hi @anuragb1090 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by anuragb1090** [comment]
Thanks a lot @lc-kay. The article shared was very helpful. Now I know why there was an issue. Thanks again.
