### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by manish-kumar161101** [LeetCode-Feedback/LeetCode-Feedback#4268]
#### Your LeetCode username

manish_kumar161101

#### Category of the bug
- [ ] Solution

#### Description of the bug

In this question the first example given have the prices values [7,1,5,3,6,4] as input and the solution is given as 5.
Whereas the correct answer the question should be 7 ( Explanation: If the stocks are bought on day 2 at price 1 and sold on day 3 at price 5, and stock are once again bought on day 4 and sold on day 5. The total profit will be 4 + 3 = 7).

#### Code you used for Submit/Run operation

```
// Best Time to Buy and Sell Stock
class Solution {
public:
    int maxProfit(vector<int>& prices) {
        
        int n = prices.size();
        
        if(n == 1)
            return 0;
        if(n == 2)
        {
            if(prices[1] <= prices[0])
                return 0;
            else
                return prices[1] - prices[0];
        }
        
        int prev2 = 0, prev1 = 0, curr;
        if(prices[1] > prices[0])
            prev1 = prices[1] - prices[0];
        
        for(int i=2; i<n; i++)
        {
            curr = max(prev1, prev2 + prices[i] - prices[i-1]);
            prev2 = prev1;
            prev1 = curr;
        }
        
        return curr;
    }
};
```

#### Language used for code

C++

#### Expected behavior

When the code is run in reference to the test case described earlier i.e.  [7,1,5,3,6,4] then the answer is marked as wrong answer in spite of the fact that it is correct because the answer expected is 5 which is wrong answer as explained earlier.

#### Screenshots

<img width="718" alt="Leetcode 1" src="https://user-images.githubusercontent.com/79417134/126690378-31c04279-ee36-4735-b634-2b5a151a9ffe.png">

<img width="716" alt="Leetcode 2" src="https://user-images.githubusercontent.com/79417134/126690394-003ee616-2a07-4fd7-bcd0-7b4cfff206c1.png">

**Comment by Leader-board** [comment]
> If the stocks are bought on day 2 at price 1 and sold on day 3 at price 5, and stock are once again bought on day 4 and sold on day 5. The total profit will be 4 + 3 = 7)

You can only do this for one day.

**Comment by lc-kay** [comment]
@manish-kumar161101 Please refer to @Leader-board explanation and other discuss posts in the problem discuss section. Thank you for your time.
