### ISSUE TITLE
931. Minimum Falling Path Sum

### ISSUE THREAD

**Issue by Kartik97** [LeetCode-Feedback/LeetCode-Feedback#427]
#### Your LeetCode username

jainkartik203

#### Category of the bug
- [ . ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Expected output different from the actual answer and in some cases there is no expected output like when m=3 and n=1

#### Code you used for Submit/Run operation

```
// Minimum Falling Path Sum
class Solution {
public:
    int minFallingPathSum(vector<vector<int>>& A) {
        int m=A.size(),n=A[0].size();
        for(int i=m-2;i>=0;i--)
            for(int j=0;j<n;j++){
                int temp = A[i+1][j];
                if(j>0)
                    temp = min(temp,A[i+1][j-1]);
                if(j<n-1)
                    temp = min(temp,A[i+1][j+1]);
                A[i][j] = A[i][j]+temp;
            }
        return *min_element(A[0].begin(),A[0].end());
    }
};
```

#### Language used for code
C++

#### Expected behavior

Input:
[[1,2,3],[4,5,6]]
Output:
5
Expected Output: 3

Input:
[[1],[2],[3]]
Output:
6
Expected: --

**Comment by CooperCooperCooper** [comment]
Hi @Kartik97 ,
Thank you for reaching out to us. We've tested your code with the inputs provided, but neither of them received empty Expected results. Screenshots of their results are attached to this message. If you're still experiencing empty Expected results for these test cases, would you please share some screenshots of them with us?
<img width="1434" alt="Screen Shot 2020-06-09 at 12 16 06 PM" src="https://user-images.githubusercontent.com/59751300/84190235-7460ee00-aa4b-11ea-86f6-62897d272468.png">
<img width="1429" alt="Screen Shot 2020-06-09 at 12 16 37 PM" src="https://user-images.githubusercontent.com/59751300/84190250-7aef6580-aa4b-11ea-8391-bbc73fcc7cdc.png">

**Comment by Kartik97** [comment]
@CooperCooperCooper, thanks for testing them. I originally meant that the expected output produced is incorrect for the test case above. The actual answer should be 5 and not 3 which is produced as the expected output. Can you please verify that?

**Comment by CooperCooperCooper** [comment]
HI @Kartik97 ,
Thanks for the clarification. Please let me relay this to our team to investigate further.

**Comment by CooperCooperCooper** [comment]
Hi @Kartik97 ,
Thank you for your time. Please review the problem statement and constraints where they state the matrix is square. Therefore the given test case is invalid. We appreciate your support.
