### ISSUE TITLE
Invalid description - 915. Partition Array into Disjoint Intervals

### ISSUE THREAD

**Issue by gautamsw5** [LeetCode-Feedback/LeetCode-Feedback#4270]
#### Your LeetCode username

GautamWadhwani2134

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question title "Partition Array into Disjoint Intervals" suggests that the two intervals must be disjoint i.e. having no common element. But "Given an array nums, partition it into two (contiguous) subarrays left and right so that:
Every element in left is <b>less than or equal to</b> every element in right"
If less than or equal to is allowed that means the intervals are not disjoint. Therefore, the word Disjoint from the question title should be removed/replaced because it is creating unnecessary confusion

**Comment by lc-kay** [comment]
Hi @gautamsw5 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gautamsw5 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
