### ISSUE TITLE
invalid testcase - 1654. Minimum Jumps to Reach Home

### ISSUE THREAD

**Issue by earendil1412** [LeetCode-Feedback/LeetCode-Feedback#4271]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

the case 61 is invalid

Input:

[8,3,16,6,12,20]

15

13

11

Output:

25

Expected:

-1

you can go 
0->15->30->45->60->75->90->105->120->135->150->165->180->167->154->141->128->115->102->89->76->63->50->37->24->11

so the answer should be 25

**Comment by tusharsingh432-dev** [comment]
this is exactly my issue how was it resolved??
