### ISSUE TITLE
Article link in the solution section is depreciated

### ISSUE THREAD

**Issue by KVShashank5** [LeetCode-Feedback/LeetCode-Feedback#4273]
#### Your LeetCode username

shashankv79

#### Category of the bug
- [ ] Solution for question 410. Split array largest sum, has depreciated article link

#### Description of the bug

The solution section's approach two has explanation about the dynamic programming approach and contains a link(http://www.programering.com/a/MDOzUzMwATM.html). This link is depreciated.

#### Screenshots

![image](https://user-images.githubusercontent.com/43372136/126768005-dc4d6d95-1e50-4aa2-bdcb-e2fd0f605ea8.png)

**Comment by lc-kay** [comment]
Hi @KVShashank5 
Thank you for reaching out to us. I've relayed this issue to our team to investigate. It will be updated as soon as we can.
