### ISSUE TITLE
Missing Test Case - 1881. Maximum Value after Insertion

### ISSUE THREAD

**Issue by kavin7018** [LeetCode-Feedback/LeetCode-Feedback#4274]
Constraints:

1 <= n.length <= 105
1 <= x <= 9
The digits in n​​​ are in the range [1, 9].
n is a valid representation of an integer.
In the case of a negative n,​​​​​​ it will begin with '-'.

#### Your LeetCode username

LeetCode username : Kavin_V

#### Category of the bug
- [yes] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Constraints said that string length from 1 to 10 power 5 (1 <= n.length <= 105) but I had encountered a test case wherein the length of the string is greater than 10power 5;

java.lang.NumberFormatException: For input string: "828824579515"
  at line 68, java.base/java.lang.NumberFormatException.forInputString
  at line 658, java.base/java.lang.Integer.parseInt
  at line 776, java.base/java.lang.Integer.parseInt
  at line 29, Solution.fun_pos
  at line 9, Solution.maxValue
  at line 54, __DriverSolution__.__helper__
  at line 87, __Driver__.main

#### Code you used for Submit/Run operation

```
//Maximum Value after Insertion
class Solution {
    public String maxValue(String n, int x) {
        int sign = n.charAt(0)-48;
        int res = 0;
        System.out.print("val:"+sign);
        if(sign>=0 && sign<=9){
            //positive
            System.out.print("Positive");
            res = fun_pos(n,x);
        }
        else{
            //negative
            System.out.print("Negative");
            res = fun_neg(n.substring(1),x);
            res*=-1;
        }
        return String.valueOf(res);
    }
    
    public int fun_pos(String s,int x){
        int num = s.charAt(0)-48;
        int pos=0;
        for(int i=0;num>=x && i<s.length()-1;i++){
            num = s.charAt(i+1)-48;
            pos++;
        }
        pos = (num>=x) ? ++pos : pos;
        s = s.substring(0,pos) + String.valueOf(x)+ ((pos==s.length()) ? "" : s.substring(pos));
        return Integer.parseInt(s);
    }
    
    public int fun_neg(String s,int x){
        int num = s.charAt(0)-48;
        int pos=0;
        for(int i=0;num<=x && i<s.length()-1;i++){
            num = s.charAt(i+1)-48;
            pos++;
        }
        pos = (num<=x) ? ++pos : pos;
        s = s.substring(0,pos) + String.valueOf(x) + ((pos==s.length()) ? "" : s.substring(pos));
        return Integer.parseInt(s);
    }
}
```

#### Language used for code

Java

#### Expected behavior

I expected the length of string to range from 1 to 10 to the power of 5, but I got a string that had a length more than that!

**Comment by EricGustin** [comment]
The length of the string that you provided is 12, which abides by the constraint of being greater than 1 and less than 10^5. The issue should be closed.
