### ISSUE TITLE
Strictly suboptimal solution for 100. Same Tree

### ISSUE THREAD

**Issue by tvatter** [LeetCode-Feedback/LeetCode-Feedback#4275]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Using threaded binary trees, you can reduce to O(1) space complexity while keeping the O(n) time complexity... Below is Python code that is basically an in order traversal without using a stack, see https://leetcode.com/problems/binary-tree-inorder-traversal/solution/ or https://www.geeksforgeeks.org/threaded-binary-tree/ for explanations. I think that this third solution should be mentioned.

```
class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def check_none(p: TreeNode, q: TreeNode) -> bool:
    return (p is None and q is not None) or (q is None and p is not None)

class Solution:
    def isSameTree(self, p: TreeNode, q: TreeNode) -> bool:     
        if p is None and q is None:
            return True
        
        while p is not None or q is not None:
            if check_none(p, q) or check_none(p.left, q.left) or check_none(p.right, q.right):
                return False
            if p.left is None:
                if p.val != q.val:
                    return False
                p = p.right
                q = q.right
            else:
                tmp_p = p.left
                tmp_q = q.left
                while tmp_p.right is not None: # find right-most node in the subtree
                    tmp_p = tmp_p.right
                    tmp_q = tmp_q.right
                    if check_none(tmp_p, tmp_q):
                        return False
                tmp_p.right = p # assign the right node to the in-order ancestor
                tmp_q.right = q
                next_p = p.left
                next_q = q.left
                p.left = None
                q.left = None
                p = next_p
                q = next_q
                
        return True
```

#### Language used for code

Python

#### Expected behavior

An optimal solution that strictly improve on the suggested solutions (i.e., same time complexity, better space complexity) should probably be mentioned.

**Comment by lc-kay** [comment]
@tvatter We encourage our users to post their solutions for others to view in the problem discussion section. Our Github Repo is for users to report any content-related issues. I've let our team know that another approach can be added. Thank you for your support and understanding.
