### ISSUE TITLE
Missing Test Case - 55. Jump Game

### ISSUE THREAD

**Issue by amakashov** [LeetCode-Feedback/LeetCode-Feedback#4276]
#### Your LeetCode username

amakashov

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Given solution didn't produce correct result on case [1,2,0,1,10,0,0,1,1000,0,3,4,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3] but accepted as correct solution https://leetcode.com/submissions/detail/527098917/

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    bool canJump(vector<int>& nums) 
    {
        vector<int> afterZeroes(1, 0);
        for (int i=0; i< nums.size()-1; i++)
            if (!nums[i] && (nums[i+1] || (i+1 ==nums.size()-1)))
                afterZeroes.push_back(i+1);
        for(int i=1; i<afterZeroes.size(); i++)
        {
            bool reachable = false;
            int nextI = i;
            int start = afterZeroes[i-1];
            for(int j=afterZeroes[i-1]; j<afterZeroes[i]-1; j++)
            {
                if (j+nums[j]>=nums.size()-1)
                    return true;
                if (j+nums[j]>=afterZeroes[i])
                {
                    while((nextI+1)<afterZeroes.size() &&j+nums[j]>=afterZeroes[nextI+1])
                        nextI++;
                    reachable = true;
                }
            }
            i = nextI;
            if (!reachable)
                return false;
        }
        
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

While tested on test case [1,2,0,1,10,0,0,1,1000,0,3,4,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3] solution produce wrong answer (and marked as wrong answer) yes still accepted while submited.

**Comment by lc-kay** [comment]
Hi @amakashov 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @amakashov 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
