### ISSUE TITLE
Judge's solution gives TLE on a valid test case (4Sum)

### ISSUE THREAD

**Issue by osamamohamedmohamed** [LeetCode-Feedback/LeetCode-Feedback#4277]
#### Your LeetCode username
osamamohamed

#### Category of the bug
- [ ] Question
- [✔] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Judge's solution gives TLE on a valid test case for question (`4Sum`).

#### Code you used for Submit/Run operation

My code that passes the test:
```
// 4Sum
class Solution {
public:
    vector<vector<int>> fourSum(vector<int>& A, int target) {
        int n = A.size();
        sort(A.begin(), A.end());

        map < long long, vector < pair < int, int > > > M;
        for(int i = 0;i < n;++i) {
            for(int j = i + 1;j < n;++j) {
                if(j - 3 > i and A[j] == A[j - 3]) {
                    continue;
                }
                M[1LL * A[i] + A[j]].push_back({i, j});
            }
        }

        set < pair < int, pair < int, pair < int, int > > > > taken;
        for(auto &p : M) {
            auto sum = p.first;
            if(M.find(target-sum) != M.end()) {
                auto &temp1 = p.second;
                auto &temp2 = M[target-sum];
                for(int i = 0;i < temp1.size();++i) {
                    for(int j = 0;j < temp2.size();++j) {
                        vector < int > t = {temp1[i].first, temp1[i].second, temp2[j].first, temp2[j].second};
                        sort(t.begin(), t.end());
                        bool ok = true;
                        for(int k = 1;k < 4;++k) {
                            if(t[k] == t[k - 1]) {
                                ok = false;
                                break;
                            }
                        }
                        if(ok) {
                            taken.insert({A[t[0]], {A[t[1]], {A[t[2]], A[t[3]]}}});
                        }
                    }
                }
            }
        }
        vector < vector < int > > ans;
        for(auto &t : taken) {
            ans.push_back({t.first, t.second.first, t.second.second.first, t.second.second.second});
        }
        return ans;
    }
};
```

#### Language used for code
C++

The judge's solution **shouldn't** fail (`TLE`) on this test case: 
```
[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
8
```

Screenshot:
![Screenshot from 2021-07-16 22-07-30](https://user-images.githubusercontent.com/10353720/126816263-402d5b7c-381e-4e91-b09f-7c63a7bc1d16.png)

**Comment by lc-kay** [comment]
<img width="918" alt="Screen Shot 2021-07-26 at 5 06 02 PM" src="https://user-images.githubusercontent.com/70870126/127074594-3610e327-cb4a-4ba7-9bd6-d7a9ce7b5379.png">
@osamamohamedmohamed Thanks for reaching out! Upon testing your code and test case, it does not TLE. Please let me know if you still believe this is an issue.

**Comment by osamamohamedmohamed** [comment]
Hello @lc-kay, thanks for your reply. It seems that the judge's solution is now updated and no longer fails. If my ticket/solution was of any help, then reconsider accepting my contribution of the test case on Leetcode (the proposal got rejected for unknown reason) as a form of incentive. Thanks.

**Comment by lc-kay** [comment]
Hi @osamamohamedmohamed 
Thank you for your time. I am glad that it is no longer an issue. As for the test case contribution, it may have gotten rejected due to not meeting our test case standards, another user submitted it previously, and other reasons.
