### ISSUE TITLE
course-schedule add tests.

### ISSUE THREAD

**Issue by moishy90** [LeetCode-Feedback/LeetCode-Feedback#4278]
#### Your LeetCode username

mosheshwarzberg

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This bug is related to https://leetcode.com/problems/course-schedule/.
My code passes on submit, but the following test case makes it clear that it should fail.

13
[[1,2], [2, 3], [2, 10], [3, 4], [4, 5], [4, 11], [5, 1]]

#### Code you used for Submit/Run operation

```
class Solution:
    def canFinish(self, numCourses: int, prerequisites: List[List[int]]) -> bool:
        graph = {i:j for i, j in prerequisites}
        for c1, c2 in prerequisites:
            processed = set([c1])
            prereq = c2
            while prereq is not None:
                if prereq in processed:
                    return False
                processed.add(prereq)
                prereq = graph.get(prereq)
        return True
```

#### Language used for code

Python3

#### Expected behavior

This should not pass.

**Comment by lc-kay** [comment]
Hi @moishy90 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @moishy90 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
