### ISSUE TITLE
Missing Test Case - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by saivinith** [LeetCode-Feedback/LeetCode-Feedback#4282]
#### Your LeetCode username

LeetCode Id: saivineethbharadwajasa
username: saivinith

#### Category of the bug
- [ ] Question
- [  ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Category:
               Solution 

#### Description of the bug

I used recursion to solve the program and it's working for me. I even tested the test cases in Leetcode but when I submit the solution it displays that the test case failed which worked before. I am not sure why it displayed that error. I attached the issue, please let me know if I am doing wrong or not.

#### Code you used for Submit/Run operation

```
My Solution:
```

```
// Using Recursion
class Solution {
    static int i=0;
    public ListNode removeNthFromEnd(ListNode head, int n) {
        if(head==null)
            return head;
        ListNode temp = removeNthFromEnd(head.next,n);
        if(++i==n){
            return temp;
        }else
            head.next = temp;
        return head;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I expected that the test case works but it does not.

#### Screenshots

![Screenshot 2021-07-24 113646](https://user-images.githubusercontent.com/22151529/126873568-03a2d44e-2cd4-4402-bf5a-815e476cec4c.png)

**Comment by lc-kay** [comment]
Hi @saivinith 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
