### ISSUE TITLE
Missing Test Case - 126. Word Ladder II

### ISSUE THREAD

**Issue by penguin2** [LeetCode-Feedback/LeetCode-Feedback#4283]
#### Your LeetCode username

sweetpotato2

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

https://leetcode.com/submissions/detail/527635115/

```
class Solution:
    def findLadders(self, beginWord: str, endWord: str, wordList: List[str]) -> List[List[str]]:
        
#         ###########################
# # The function "testcase_print" below, would yield some testcase with parameters x and y.
# # They correspond to the specific lowercase alphabet range, for example,
# # (0,2) <-> 'a' ~ 'c'

# # length(wordList) == (y - x) * 6
# # length(wordList[0]) == 4
# # 
# # The number of paths that we need to print out for this testcase, is 4**(y-x). ( x = 0 , y = 25 => 2**50)
# #
# # testcase_print(0,2,"abcdefghijklmnopqrstuvwxyz") would be,
# # 
# # "aaaa"
# # "cccc"
# # ["abaa","baaa","bbaa","bbab","bbba","bbbb","bcbb","cbbb","ccbb","ccbc","cccb","cccc"]
# #         
#         ###########################

#         # x,y : 0 ~ 25 x < y
#         def testcase_print(x,y,letters):
#             f = lambda i:letters[i]
#             ret = []
#             for i in range(x,y):
#                 ret.append(str("".join(map(f,[i,i+1,i,i]))))
#                 ret.append("".join(map(f,[i+1,i,i,i])))
#                 ret.append("".join(map(f,[i+1,i+1,i,i])))
#                 ret.append("".join(map(f,[i+1,i+1,i,i+1])))
#                 ret.append("".join(map(f,[i+1,i+1,i+1,i])))
#                 ret.append("".join(map(f,[i+1,i+1,i+1,i+1])))
            
#             print("".join(['\"']+[*map(f,[x]*4)]+['\"']))
#             print("".join(['\"']+[*map(f,[y]*4)]+['\"']))
#             print("[",end = "")
#             print(*('"{}"'.format(item) for item in ret), sep=',',end = "")
#             print("]")
            
#             return
        
#         testcase_print(0,2,"abcdefghijklmnopqrstuvwxyz")
        
#         ###########################
        
#         (The code below is very naive...) 
#         1-1. bfs search starting from "beginWord" toward "endWord"
#         1-2. at the same time generating DAG
#         2. generate all paths backwards recursively (with memoization)
        
#         ###########################
        def paths(v):
            if v in cache:
                return cache[v]
            ret = []
            for u in G[v]:
                ret += [path+[wordList[v]] for path in paths(u)]
            cache[v] = ret
            return ret
                
        cache = dict()
        letters = "abcdefghijklmnopqrstuvwxyz"
        wordList.append(beginWord)
        N = len(wordList)
        K = len(wordList[0])
        S = {word:i for i,word in enumerate(wordList)}
        G = [[] for _ in range(N)]
        Q = [N-1]
        S.pop(beginWord)
        if endWord not in S:
            return []
        target = S[endWord]
        
        while Q:
            P = set()
            for q in Q:
                word = wordList[q]
                for i in range(K):
                    for c in letters:
                        w2 = word[:i] + c + word[i+1:]
                        if not w2 in S:
                            continue
                        p = S[w2]
                        P.add(p)
                        G[p].append(q)
            if target in P:
                break
            for p in P:
                S.pop(wordList[p])
            Q = P
        
        cache[N-1] = [[beginWord]]
        return paths(target) if target in P else []
```

#### Language used for code

Python3

#### Expected behavior

Concern : 
I think the number(2**50) of the paths we should print out for the testcase below is too large.

"aaaa"
"zzzz"
["abaa","baaa","bbaa","bbab","bbba","bbbb","bcbb","cbbb","ccbb","ccbc","cccb","cccc","cdcc","dccc","ddcc","ddcd","dddc","dddd","dedd","eddd","eedd","eede","eeed","eeee","efee","feee","ffee","ffef","fffe","ffff","fgff","gfff","ggff","ggfg","gggf","gggg","ghgg","hggg","hhgg","hhgh","hhhg","hhhh","hihh","ihhh","iihh","iihi","iiih","iiii","ijii","jiii","jjii","jjij","jjji","jjjj","jkjj","kjjj","kkjj","kkjk","kkkj","kkkk","klkk","lkkk","llkk","llkl","lllk","llll","lmll","mlll","mmll","mmlm","mmml","mmmm","mnmm","nmmm","nnmm","nnmn","nnnm","nnnn","nonn","onnn","oonn","oono","ooon","oooo","opoo","pooo","ppoo","ppop","pppo","pppp","pqpp","qppp","qqpp","qqpq","qqqp","qqqq","qrqq","rqqq","rrqq","rrqr","rrrq","rrrr","rsrr","srrr","ssrr","ssrs","sssr","ssss","stss","tsss","ttss","ttst","ttts","tttt","tutt","uttt","uutt","uutu","uuut","uuuu","uvuu","vuuu","vvuu","vvuv","vvvu","vvvv","vwvv","wvvv","wwvv","wwvw","wwwv","wwww","wxww","xwww","xxww","xxwx","xxxw","xxxx","xyxx","yxxx","yyxx","yyxy","yyyx","yyyy","yzyy","zyyy","zzyy","zzyz","zzzy","zzzz"]

#### Additional context

I read the solution, and found the related part, I guess.

https://leetcode.com/problems/word-ladder-ii/solution/

"Thus the upper bound for αα is 3^{(N/3)}
 , however, this is a very loose bound because the nature of this problem precludes the possibility of a DAG where every layer is fully connected to the next layer."

**Comment by lc-kay** [comment]
Hi @penguin2 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@penguin2 Our team did not add this test case because the output violates the platform limits. Thank you for your understanding.
