### ISSUE TITLE
Outdated Runtimes - Contains Duplicate II

### ISSUE THREAD

**Issue by Myles-Trevino** [LeetCode-Feedback/LeetCode-Feedback#4284]
#### Your LeetCode username
https://leetcode.com/user1893Cf/

#### Description of the bug
The runtime distribution graph for Contains Duplicate II contains outdated data, likely from before additional test cases were added. This makes it impossible to achieve the runtimes displayed on the leftmost peak despite using the same solution. This is confusing for users as it implies there is a better solution when there isn't.

#### Code you used for Submit/Run operation
```
bool containsNearbyDuplicate(vector<int>& nums, int k) {
    
    unordered_map<int, int> map;
    for(int i{}; i < nums.size(); ++i){
        
        const int n{nums[i]};
        const auto result{map.find(n)};
        
        // If close enough, return true.
        if(result != map.end() && i-result->second <= k) return true;
            
        // Otherwise insert/update.
        map[n] = i;
    }
    
    return false;
}
```

#### Language used for code
C++

**Comment by lc-kay** [comment]
@Myles-Trevino Our team has updated the runtimes. Thank you for your time.
