### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by sangleshubham** [LeetCode-Feedback/LeetCode-Feedback#4285]
#### Your LeetCode username

mrsilent

#### Category of the bug
- [ ] Question
- [ *] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This is one of the hard category questions but in python, you can solve it in a single line using some built-in library.

#### Code you used for Submit/Run operation

```
# Just import this built-in library.
import re

class Solution:
    def isMatch(self, s: str, p: str) -> bool:
        return True if s in re.findall(p , s ) else False 
 #This single line will pass all test cases withought any issue.
```

#### Language used for code

Python3

#### Expected behavior

There must be more of a complex solution for this problem or the solution which does not directly work as a built-in library in some languages like python. You can change the regular expression to something else which the built-in library doesn't accept as a pattern.

#### Screenshots

![image](https://user-images.githubusercontent.com/37057102/126881729-dbf0a6ef-238f-49cc-9ffe-495ab1ebc5cb.png)

**Comment by lc-kay** [comment]
Hi @sangleshubham 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@sangleshubham As it is nearly impossible to verify if the solution is using a built-in function or not. We kindly encourage our users to solve it without using a built-in function which is what will be asked in an actual interview. Thank you for your understanding.
