### ISSUE TITLE
explicitly mention what to return in Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by hamirmahal** [LeetCode-Feedback/LeetCode-Feedback#4286]
#### Your LeetCode username

Hamirmahal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Although we could figure it out, it might be worth a sentence to explicitly state what to return in Convert Sorted Array to Binary Search Tree.

#### Expected behavior

We state what we expect the problem to return.

**Comment by lc-kay** [comment]
@hamirmahal Per the problem statement, it asks the user to "convert it to a height-balanced binary search tree." Thank you for your time.

**Comment by hamirmahal** [comment]
@lc-kay I was thinking something like today's LeetCoding challenge, where it explicitly states

> Return the sum of the three integers.

Similarly, https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/ could add,

> Return the root of the height-balanced binary search tree created from nums.

It's not a huge deal. We could figure out that we're supposed to be returning the root, but it might be helpful to add that extra line to make it crystal-clear, since the problem doesn't explicitly state what the returned value should be, just that we're taking an input array and we "convert it to a height-balanced binary search tree."
