### ISSUE TITLE
New explore card request:String manipulation, Bit manipulation,Dynamic programming, graph problems?

### ISSUE THREAD

**Issue by colinshenc** [LeetCode-Feedback/LeetCode-Feedback#4287]
#### Your LeetCode username

colins

#### Category of the bug
- [x ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hi,
your explore cards section has been a great way for me to learn about problems in a topic-oriented manner. However, I don't see any updates on the explore section recently. Can you update these cards with the topics such as string manipulation,bit manipulation, dp, and graph problems?

Thanks very much for your work.

**Comment by lc-kay** [comment]
@colinshenc Thank you for your feedback. Our team will look into this and take it into consideration. Thank you for your time and support.
