### ISSUE TITLE
Missing Test Case - 1948. Delete Duplicate Folders in System

### ISSUE THREAD

**Issue by silvertint** [LeetCode-Feedback/LeetCode-Feedback#4289]
#### Your LeetCode username

Jason_Tint

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test cases of problem "1948. Delete Duplicate Folders in System" are not complete. As a result, wrong submissions could be accepted during the Weekly Contest 251.

Missing test case:
[["a"],["a","c"],["a","d"],["a","d","e"],["b"],["b","e"],["b","c"],["b","c","d"],["f"],["f","h"],["f","h","i"],["f","j"],["g"],["g","j"],["g","h"],["g","h","i"]]

#### Code you used for Submit/Run operation

```
// 1948. Delete Duplicate Folders in System
class Solution:
    def deleteDuplicateFolder(self, paths: List[List[str]]) -> List[List[str]]:
        n = len(paths)
        T = lambda: defaultdict(T)
        trie = T()
        for p in paths:
            cur = trie
            for x in p:
                cur = cur[x]
            cur['*'] = True
        cnt = Counter()

        def dfs(node):
            ans = ""
            for x in sorted(node):
                if x =='*': continue
                ans += x + '#'
                ans += dfs(node[x])
            cnt[ans] += 1
            node['#'] = ans
            return ans

        dfs(trie)
        ans = []

        def dfs2(node, pre):
            for x in node:
                if x == '#' or x == '*': continue
                if node[x]['#'] and cnt[node[x]['#']] >= 2: continue
                else:
                    if '*' in node[x]: ans.append(pre + [x])
                    dfs2(node[x], pre + [x])

        dfs2(trie, [])
        return ans
```

#### Language used for code

Python3

#### Expected behavior

Please add the missing test case, and rejudge the submissions of that problem in the Weekly Contest 251.

#### Screenshots

<img width="794" alt="image" src="https://user-images.githubusercontent.com/33660243/126889880-5d53b209-72d3-436c-9b38-26b7923cd2f1.png">

**Comment by silvertint** [comment]
@lc-kay Please check and add this test case. Thank you so much!

**Comment by lc-kay** [comment]
Hi @silvertint 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @silvertint 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
