### ISSUE TITLE
Missing Test Case - 28. Implement strStr()

### ISSUE THREAD

**Issue by manand881** [LeetCode-Feedback/LeetCode-Feedback#4290]
#### Your LeetCode username
manand881

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
the test cases must incorporate a test case where the length of the needle and haystack is the maximum permissible and pushes the limits of the input to the extreme. 

in my code given `below` i have assigned the variable needlelen with the length of the needle and it is used in the for loop within the if statement to avoid fetching the length of the needle repeatedly. if in case i directly replace needlelen with needle.length, the loop must take much longer to run. This is not what is observed my submissions. this is because there arent enough test cases where the needle length are long and the haystack length is extremely long to actually make a difference in how we write the code.

#### Code you used for Submit/Run operation

```
/**
 * @param {string} haystack
 * @param {string} needle
 * @return {number}
 */
var strStr = function (haystack, needle) {
    if (needle === '') {
        return 0;
    }
    const needlelen = needle.length;
    for (let x = 0; x < haystack.length; x++) {
        if (haystack.substring(x, x + needlelen) === needle) {
            return x;
        }
    }
    return -1;
};
```

#### Language used for code
Javascript

#### Expected behavior
A significant difference in execution time must be available

#### Additional context
i have attached a sample test case where i have generated the needle and haystack using a simple python script
[needle.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6873472/needle.txt)
[haystack.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6873473/haystack.txt)

**Comment by lc-kay** [comment]
Hi @manand881 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@manand881 The maximum test cases are already present, therefore, our team did not add this test case. Thank you for your time.
