### ISSUE TITLE
Missing Test Case - 1948. Delete Duplicate Folders in System

### ISSUE THREAD

**Issue by penguin2** [LeetCode-Feedback/LeetCode-Feedback#4291]
#### Your LeetCode username

sweetpotato2

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Please add some more testcases, including :
[["a"],["a","c"],["a","c","b"],["a","w"],["a","w","y"],["z","c"],["z","c","b"],["z","c","w"],["z","c","w","y"],["z"]]

This testcase is in need.
When serializing tree information with the child nodes information, it needs to be one-to-one correspondence, I think.
I myself implemented this part very roughly, but got accepted. (You can see the code and screenshots attached below)

https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/4289 ( -> almost the same issue, I guess)

#### Code you used for Submit/Run operation

1. making graph (tree)
2. dfs(u) is for serializing subtrees recursively, and at the same time checking duplicates.
3. dfs2(u) is to make sure excluding deleted nodes from the answer. ( maybe only for leaf nodes...)

Failing the testcase above : https://leetcode.com/submissions/detail/527939790/ (Accepted at least now)
```
class Solution:
    def deleteDuplicateFolder(self, paths: List[List[str]]) -> List[List[str]]:
        def dfs(u):
            if not G[u]:
                return paths[u][-1]
            G[u].sort(key = lambda x: paths[x][-1])
            key = "+".join(dfs(v) for v in G[u])
            if key in K:
                chk[K[key]] = 0
                chk[u] = 0
            else:
                K[key] = u
            return paths[u][-1] + "|" + key
        def dfs2(u):
            if chk[u]:
                for v in G[u]:
                    dfs2(v)
            else:
                for v in G[u]:
                    chk[v] = 0
                    dfs2(v)
            return

        node_number = dict()
        node_number[""] = -1
        G = [[] for _ in range(1+len(paths))]
        chk = [1] * (1+len(paths))
        K = dict()
        
        paths.sort(key = lambda p:len(p))
        for i,path in enumerate(paths):
            x = "".join("/" + p for p in path[:-1])
            y = x + "/" + path[-1]
            G[node_number[x]].append(i)
            node_number[y] = i
            
        dfs(-1)
        dfs2(-1)
        return [path for i,path in enumerate(paths) if chk[i]]

```

Passing the testcase above : https://leetcode.com/submissions/detail/527955582/ (Accepted at least now)
```
class Solution:
    def deleteDuplicateFolder(self, paths: List[List[str]]) -> List[List[str]]:
        def dfs(u):
            if not G[u]:
                return paths[u][-1]
            G[u].sort(key = lambda x: paths[x][-1])
            key = "+".join(dfs(v) for v in G[u])
            if key in K:
                chk[K[key]] = 0
                chk[u] = 0
            else:
                K[key] = u
            return paths[u][-1] + "(" + key + ")"
        def dfs2(u):
            if chk[u]:
                for v in G[u]:
                    dfs2(v)
            else:
                for v in G[u]:
                    chk[v] = 0
                    dfs2(v)
            return

        node_number = dict()
        node_number[""] = -1
        G = [[] for _ in range(1+len(paths))]
        chk = [1] * (1+len(paths))
        K = dict()
        
        paths.sort(key = lambda p:len(p))
        for i,path in enumerate(paths):
            x = "".join("/" + p for p in path[:-1])
            y = x + "/" + path[-1]
            G[node_number[x]].append(i)
            node_number[y] = i
            
        dfs(-1)
        dfs2(-1)
        return [path for i,path in enumerate(paths) if chk[i]]
```

#### Language used for code

Python3

#### Expected behavior

Submissions which fails the testcase above should not get accepted.
(so that people like me, would get a chance to learn something more.)

#### Screenshots

<img width="1287" alt="image1" src="https://user-images.githubusercontent.com/17985971/126891400-3082e8db-2f53-4023-b389-53852fc2ed79.png">
<img width="1281" alt="image2" src="https://user-images.githubusercontent.com/17985971/126891406-e0a119ee-e200-4710-aee2-6e75e98691d1.png">

**Comment by lc-kay** [comment]
Hi @penguin2 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
