### ISSUE TITLE
Invalid Test Case - 126. Word Ladder II

### ISSUE THREAD

**Issue by vasilaio** [LeetCode-Feedback/LeetCode-Feedback#4292]
#### Your LeetCode username
vasilaio

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
According to requirements (description Example 2): 
> sk == endWord

but my solution fails with:

>Input: "hot", "dog", ["hot","dog","dot"]
>Output: []
>Expected: [["hot","dot","dog"]]

#### Language used for code
Java

#### Expected behavior
Expected to pass

#### Screenshots
![image](https://user-images.githubusercontent.com/18676869/126896679-74c8f55c-586e-481a-96de-d549178f0dde.png)

**Comment by lc-kay** [comment]
@vasilaio Your code is outputting [] when the expected is [["hot","dot","dog"]]. Therefore, it received wrong answer. For further support, please refer to the problem discuss section. Thank you for your time.
