### ISSUE TITLE
Wrong algorithm being accepted in 1057 | Missing Test Cases

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#4294]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In Campus Bikes https://leetcode.com/problems/campus-bikes/ Greedy solution via priority queue is being accepted.
However greedy does not guarantee optimality in all the test cases.

For e.g. for the attached test case, the actual answer is 6
If we pair (0,0) with (4,0)  and (5,0) with (7,0)
but the greedy solution gives answer as 7 and it's getting accepted.

![4f8376de-8bde-4ae6-b235-377a0e389ee5](https://user-images.githubusercontent.com/4747384/126898280-e69f3e46-05a6-48b3-b93a-4e28b67f7037.jpg)

Test case 

> [[0,0],[5,0]]
> [[4,0],[7,0]]

#### Code you used for Submit/Run operation
Greedy solution using counting sort 
```
public int[] assignBikes(int[][] workers, int[][] bikes) {
        List<List<Pair<Integer, Integer>>> distances = new ArrayList<>(2001); //worker index, bike index
        for (int i = 0; i < 2001; i++) {
            distances.add(new ArrayList<>());
        }
        boolean[] assignedBikes = new boolean[bikes.length];
        boolean[] assignedWorkers = new boolean[bikes.length];
        int[] result = new int[workers.length];
        //to avoid sort use counting sort and push indices in the expected order to avoid sorting again
        //the {worker, bike} for same distance should be sorted based on the worker index first, then bike index
        //this can be handled if we insert them at the correct order i.e if we iterate over workers in ascending order first,
        //then iterate bike indexes, we can avoid sorting!
        for (int i = 0; i < workers.length; i++) { //iterate workers in ascending order, as worker has higher priority
            int[] worker = workers[i];
            for (int j = 0; j < bikes.length; j++) { //iterate bikes in ascending order, as bikes has second priority
                int distance = Math.abs(bikes[j][1] - worker[1]) + Math.abs(bikes[j][0] - worker[0]);
                distances.get(distance).add(new Pair<>(i, j));
            }
        }
        int assigned = 0;
        int index = 0;
        while (assigned < workers.length) {
            List<Pair<Integer, Integer>> candidates = distances.get(index++);
            for (Pair<Integer, Integer> candidate : candidates) {
                if (!assignedBikes[candidate.getValue()] && !assignedWorkers[candidate.getKey()]) { //greedy assignment
                    assigned++;
                    result[candidate.getKey()] = candidate.getValue();
                    assignedBikes[candidate.getValue()] = true;
                    assignedWorkers[candidate.getKey()] = true;
                }
            }
        }
        return result;
    }
```

#### Language used for code
Java

#### Expected behavior
Greedy solution should not get accepted. 
Solution should only work for Hungarian algorithm or some other algorithm.
Since time complexity of those solutions would be higher, probably need to relax the constraints to get the correct solution accepted.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@snehasishroy The statement asked to first assign the pair with the smallest Manhattan distance, then the next pair and so on. We have updated the problem description to clarify this point. Thank you for your time.
