### ISSUE TITLE
Missing Test Case - 435. Non-overlapping Intervals

### ISSUE THREAD

**Issue by yinghaowuzhanbai** [LeetCode-Feedback/LeetCode-Feedback#4295]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

[[1,2],[2,3],[3,4],[1,3]], test case wrong result ,can still be still accpected
output 2 excepted 1
#### Code you used for Submit/Run operation

```
// Non-overlapping Intervals
class Solution {
    public int eraseOverlapIntervals(int[][] intervals) {
        if (intervals.length < 2) return 0;
        Arrays.sort(intervals, new Comparator<int[]>() {
            @Override
            public int compare(int[] o1, int[] o2) {
                if (o1[1] != o2[1]) {
                    return Integer.compare(o1[1],o2[1]);
                } else {
                    return Integer.compare(o1[0],o2[0]);
                }
            }
        });

        int count = 0;
        int edge = intervals[0][1];
        for (int i = 1; i < intervals.length; i++) {
            if (intervals[i][0] < edge) {
                count++;
            } else {
                edge = intervals[i][1];
            }
        }
        return count;
    }
}
```

#### Screenshots

![image](https://user-images.githubusercontent.com/55349518/126905834-e73e99bf-cd3b-4477-b166-ad4ceb113fa8.png)
![image](https://user-images.githubusercontent.com/55349518/126905842-ae9d109f-aef2-44b7-a801-7f6c8b5fcc13.png)

**Comment by yinghaowuzhanbai** [comment]
text case  missing

**Comment by yinghaowuzhanbai** [comment]
sry! i sumbit a correct version . The wrong version is here:
class Solution {
    public int eraseOverlapIntervals(int[][] intervals) {
        if (intervals.length < 2) return 0;
        Arrays.sort(intervals, new Comparator<int[]>() {
            @Override
            public int compare(int[] o1, int[] o2) {
                if (o1[0] != o2[0]) {
                    return Integer.compare(o1[1],o2[1]);
                } else {
                    return 0;
                }
            }
        });

        int count = 0;
        int edge = intervals[0][1];
        for (int i = 1; i < intervals.length; i++) {
            if (intervals[i][0] < edge) {
                count++;
            } else {
                edge = intervals[i][1];
            }
        }
        return count;
    }
}

**Comment by lc-kay** [comment]
@yinghaowuzhanbai Please provide the submission details link to the code that will fail the missing test case. Thank you.

**Comment by yinghaowuzhanbai** [comment]
Here is the code:
class Solution {
    public int eraseOverlapIntervals(int[][] intervals) {
        if (intervals.length < 2) return 0;
        Arrays.sort(intervals, new Comparator<int[]>() {
            @Override
            public int compare(int[] o1, int[] o2) {
                if (o1[0] != o2[0]) {
                    return Integer.compare(o1[1],o2[1]);
                } else {
                    return 0;
                }
            }
        });

        int count = 0;
        int edge = intervals[0][1];
        for (int i = 1; i < intervals.length; i++) {
            if (intervals[i][0] < edge) {
                count++;
            } else {
                edge = intervals[i][1];
            }
        }
        return count;
    }
}

**Comment by yinghaowuzhanbai** [comment]
https://leetcode.com/submissions/detail/528136983/

**Comment by lc-kay** [comment]
Hi @yinghaowuzhanbai 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yinghaowuzhanbai 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by yinghaowuzhanbai** [comment]
yinghaowuzhanbai

**Comment by lc-kay** [comment]
@yinghaowuzhanbai Unfortunately, I am unable to find a LeetCode account associated with that username. Please send me a screenshot of your profile page.

**Comment by yinghaowuzhanbai** [comment]
![image](https://user-images.githubusercontent.com/55349518/129069481-9be38cdc-3e7a-4a0e-88f3-f0bc8d6253b1.png)
