### ISSUE TITLE
491. Increasing Subsequences

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#430]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing test cases

#### Code you used for Submit/Run operation

```
class Solution(object):
    def findSubsequences(self, a):
        def f(i,l):
            if len(l)>1:
                z.append(l[:])
            s=set()
            for j in xrange(i,n):
                if a[j] not in s and (not l or a[j]>=l[-1]):
                    s.add(a[j])
                    l.append(a[j])
                    f(j+1,l)
                    l.pop()
        z=[]
        n=len(a)
        if n>2:
            f(0,[])
        return z
```

#### Language used for code
Python

#### Expected behavior
Missing test case

```
[1,2]
```

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
