### ISSUE TITLE
1052. 爱生气的书店老板 ：https://leetcode-cn.com/problems/grumpy-bookstore-owner/ 

### ISSUE THREAD

**Issue by XiaoBaiRuler** [LeetCode-Feedback/LeetCode-Feedback#4300]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
xiaobai_ruler

**Bug 类型**
- [√] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
[9,10,4,5]
[1,0,1,1]
1
上面用例，测试结果为15，也即老板连续1天忍着之后，之后就不能忍了，否则应该19
而这个用例
[4,10,10]
[1,1,0]
2
测试结果是24，那么如果解释：老板为什么又可以连续忍3天了，相矛盾了，还是我理解错了

描述中写今天。。。老板不住地球嘛？能超过24小时不间断工作。。。。

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与相关团队核实后： [9,10,4,5],[1,0,1,1],1 测试结果是 19 , 而不是 14，并没有问题。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
