### ISSUE TITLE
[#713] Incorrect solution

### ISSUE THREAD

**Issue by shadabk96** [LeetCode-Feedback/LeetCode-Feedback#4301]
The solution mentioned for approach#2 for problem "Subarray Product Less Than K" ([ref](https://leetcode.com/problems/subarray-product-less-than-k/)) does not handle the test case 
```
[1,1,1] 
1
```
This can be fixed by replacing 
`            while prod >= k:`
with
`            while prod >= k and left <= right:`

**Comment by lc-kay** [comment]
@shadabk96 The code runs fine with the test case you've provided and is accepted. Please try again and provide a screenshot of the issue. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @shadabk96 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
