### ISSUE TITLE
Internal Server Error in fetching my old submissions.

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#4302]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] System Error 

#### Description of the bug

when i clicked on my old submission, it is showing me an internal server error,
<br>
![image](https://user-images.githubusercontent.com/47894634/127057956-d7d01c67-d5e9-4326-9f34-70d94e75fcd5.png)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Mohitkumar6122 Please reach out to us via leetcode.com/support. Thank you for your time.

**Comment by Mohitkumar6122** [comment]
> @Mohitkumar6122 Please reach out to us via leetcode.com/support. Thank you for your time.

Sure @lc-kay, I'll reach leetcode via support.
