### ISSUE TITLE
Question description - 835. Image Overlap

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4304]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

- Please remove brackets ( and ) in the question. There are no secrets, no ear whispering, etc. that are told in the question
The mentioned parts in brackets are the main part of the question description.

- Be more clear, change:
from:  sliding it left, right, up, or down any number of units
to: sliding the whole image left, right, up, or down any number of units

- See what others are saying about understanding the question - https://leetcode.com/problems/image-overlap/solution/685618

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

For some reason, the questions reads very badly and is unclear, compared to the 800 questions I solved.
The question must read properly on the first read of the user.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
