### ISSUE TITLE
Wrong Test Case - 1839. Longest Substring Of All Vowels in Order

### ISSUE THREAD

**Issue by realJustinLee** [LeetCode-Feedback/LeetCode-Feedback#4306]
#### Your LeetCode username
JustinLee97

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In test case "auoeioueiaaioeuieuoaieuaoeuoaiaoueioiaeuiuaeouaoie":
Given that the question want each Vowel to appear at least once, it is impossible for a answer that has a length of 4, but this test case suggest a sub string that matches with the question that has a length of 4 (from index 3 to index 7 "eiou") which doesn't actually match with the requirements.

#### Code you used for Submit/Run operation
```
    public int longestBeautifulSubstring(String word) {
        int len = word.length();
        char[] wChar = word.toCharArray();
        char[] checkList = {'a', 'e', 'i', 'o', 'u'};
        int vowelsLen = checkList.length;

        int i = 0;
        int j = 0;
        int curLen = 0;
        int maxLen = 0;
        while (i < len) {
            if (wChar[i] == checkList[j]) {
                i++;
                curLen++;
                continue;
            }
            if (j < vowelsLen - 1 && wChar[i] == checkList[j + 1]) {
                j++;
                continue;
            }

            if (j == vowelsLen - 1) {
                maxLen = Math.max(maxLen, curLen);
            }

            j = 0;
            curLen = 0;
            i++;
        }

        if (j == vowelsLen - 1) {
            maxLen = Math.max(maxLen, curLen);
        }

        return maxLen;
    }
```

#### Language used for code
Java

#### Expected behavior
In test case "auoeioueiaaioeuieuoaieuaoeuoaiaoueioiaeuiuaeouaoie":
should suggest 0 rather than 4 because this test case doesn't has a sub string that fits.

**Comment by lc-kay** [comment]
@realJustinLee Your explanation is correct and 0 is the expected output for this test case. Your code is outputting 4 for this test case, which caused it to result in wrong answer. Thank you for your time.
