### ISSUE TITLE
671题 本地执行和提交执行同一组样例结果不同

### ISSUE THREAD

**Issue by tystys404** [LeetCode-Feedback/LeetCode-Feedback#4308]
**你的 LeetCode 用户名**
绝望的龙

**Bug 类型**
- [ ✔] 题目
- [✔ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
本地测试出来和提交同样代码结果不同
**你使用的语言**
C++

**你提交或者运行的代码**
```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
vector<int>nums;
class Solution {
public:
void dfs(TreeNode *r)
{
    if(r==nullptr) return ;
    int v=r->val;
    nums.push_back(v);
    dfs(r->left);
    dfs(r->right);
}
    int findSecondMinimumValue(TreeNode* root) {
        dfs(root);
        for(int i=0;i<nums.size()-1;i++)
        {
            if(nums[i+1]>nums[i]) return nums[i+1];
        }
        return -1;
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
![屏幕截图 2021-07-27 165935](https://user-images.githubusercontent.com/73160179/127127869-35b58d58-f755-4931-81ce-99ad15283ecf.png)

**额外的上下文**
测试样例是直接复制过去的，代码思路很简单，就是先记录所有节点的数字，然后排序，找到第一个后一个比前一个大的数字，然后返回，若找不到则返回-1

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
