### ISSUE TITLE
Judge was wrong - 835. Image Overlap

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4309]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The below code is wrong
But was accepted during the contest.

Test case:
[[0,0,0,0,1],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]]
[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[1,0,0,0,0]]

See the screenshot below.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int largestOverlap(vector<vector<int>>& A, vector<vector<int>>& B) {
        int n = A.size(), res = 0;
        for (int x = 0; x < n; x++)
        for (int y = 0; y < n; y++) {
            int r = 0, t = 0;
            for (int i = 0; x + i < n; i++)
            for (int j = 0; y + j < n; j++) {
                r += A[x + i][y + j] & B[i][j];
                t += A[i][j] & B[x + i][y + j];
            }
            res = max(max(res, t), r);
        }
        return res;
    }
};
```

#### Expected behavior

The contest must be fair. Should not accept a wrong solution and give a ~100 rank to a user.
Please rejudge the contest.

#### Screenshots

![image](https://user-images.githubusercontent.com/8236389/127130872-22a9a87a-d90a-4e97-baa0-19d6e16a8dac.png)

![image](https://user-images.githubusercontent.com/8236389/127131276-915ada21-e2eb-4c3d-b3c0-45dc8ef58316.png)

**Comment by lc-kay** [comment]
@manoharreddyporeddy This contest has been finalized, and once a ranking has been finalized, it can not be changed. As this test case was added long after the contest, it did not affect the ranking. For all missing test cases regarding contests, we recommend contributing the missing test case within 1 day after the contest ends.

**Comment by manoharreddyporeddy** [comment]
I didn't tell you that this is a missing test case...
The title says "Judge was wrong"...
As you cannot change ranking... it's fine if you all can live with the fact that you gave a LOT of wrong ranks.

**Comment by manoharreddyporeddy** [comment]
Also "it did not affect the ranking"
is the problem
It has to affect the ranking,  as there are many wrong solutions even now. Screenshot given above already

**Comment by lc-kay** [comment]
@manoharreddyporeddy I understand that the judge was wrong during the contest due to missing test cases, such as the one mentioned above. As this test case was added after the contest has long ended, we can unable to reverse or change the rankings. However, I've relayed this feedback to our team to investigate. Thank you for your time.
