### ISSUE TITLE
316. Remove Duplicate Letters

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#431]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Same question with different difficulty

#### Expected behavior
The problems [316](https://leetcode.com/problems/remove-duplicate-letters/) and [1081](https://leetcode.com/problems/smallest-subsequence-of-distinct-characters/) are equivalent which is mentioned but still they are of different difficulty. Why?

I suggest the problem descriptions be updated to make the questions of the same difficulty like has already been done for pairs like [476](https://leetcode.com/problems/number-complement/), [1009](https://leetcode.com/problems/complement-of-base-10-integer/) and [783](https://leetcode.com/problems/minimum-distance-between-bst-nodes/), [530](https://leetcode.com/problems/minimum-absolute-difference-in-bst/) and [846](https://leetcode.com/problems/hand-of-straights/), [1296](https://leetcode.com/problems/divide-array-in-sets-of-k-consecutive-numbers/). 

Moreover, in #318 similar problems were also modified to be of equal difficulty.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. Since these two problems are relatively older, changing their difficulties would affect many associated branches of the site, so we will not be changing their difficulties at this moment. We appreciate your support.

**Comment by leet212** [comment]
Hello @CooperCooperCooper . Sure I understand that there can be technical difficulties for the issue. I hope the change will be considered when it is more suitable in the future. Thank you for your response.
