### ISSUE TITLE
Convert Medium to Hard - 835. Image Overlap

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4310]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Please convert this question from Medium to Hard

See what users are saying:

> This problem is way too hard to solve. Even the questions marked as hard are easier than this problem, which is marked medium.
https://leetcode.com/problems/image-overlap/solution/685964

> Man this question kicks ass..how is it rated medium I would have never thought of these approaches at all..
https://leetcode.com/problems/image-overlap/solution/687014

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

This is too hard for a medium as per many users

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We will consider changing the difficulty of the problem in our next update.
