### ISSUE TITLE
Missing Test Case - 207. Course Schedule

### ISSUE THREAD

**Issue by deq4** [LeetCode-Feedback/LeetCode-Feedback#4311]
#### Your LeetCode username
deq4

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A solution that doesn't detect cycles within BFS-layers passes.

#### Code you used for Submit/Run operation

```
func canFinish(numCourses int, prerequisites [][]int) bool {
    adjList := make([][]int, numCourses)
    for _, p := range prerequisites {
        course, req := p[0], p[1]
        adjList[course] = append(adjList[course], req)
    }
    
    depth := make(map[int]int)
    for i := range adjList {
        if _, present := depth[i]; present {
            continue
        }
        
        depth[i] = 0
        visited := []int{i}
        queuePos := 0
        for len(visited) > queuePos {
            node := visited[queuePos]
            queuePos++
            
          curDepth := depth[node]
            for _, child := range adjList[node] {
                if childDepth, present := depth[child]; present {
                    if childDepth < curDepth || child == node {
                        return false
                    }
                } else {
                    visited = append(visited, child)
                    depth[child] = curDepth + 1
                }
            }
        }

        for _, node := range visited {
            depth[node] = numCourses
        }
    }
    
    return true
}
```

#### Language used for code
golang

#### Expected behavior
Solutions like that shouldn't pass.

#### Screenshots

![image](https://user-images.githubusercontent.com/29675262/127165316-d3348d8a-ee2f-427b-a100-59de660b0af9.png)

#### Additional context
Testcase:
```
3
[[0,1], [0, 2], [1, 2], [2, 1]]
```

**Comment by lc-kay** [comment]
Hi @deq4 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @deq4 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
