### ISSUE TITLE
Encode and Decode TinyURL Approach #2  The code gives an error

### ISSUE THREAD

**Issue by ivalkshfoeif** [LeetCode-Feedback/LeetCode-Feedback#4312]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The code in the approach # 2 gives an error: Line 22: error: unreachable statement [in Codec.java]
        count++;

#### Code you used for Submit/Run operation

```
public class Codec {

    String chars = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    HashMap<String, String> map = new HashMap<>();
    int count = 1;

    public String getString() {
        int c = count;
        StringBuilder sb = new StringBuilder();
        while (c > 0) {
            c--;
            sb.append(chars.charAt(c % 62));
            c /= 62;
        }
        return sb.toString();
    }

    public String encode(String longUrl) {
        String key = getString();
        map.put(key, longUrl);
        return "http://tinyurl.com/" + key;
        count++;
    }

    public String decode(String shortUrl) {
        return map.get(shortUrl.replace("http://tinyurl.com/", ""));
    }
}


```

#### Language used for code

JAVA

#### Expected behavior

The code should pass the leetcode testcase and be sumbitted successfully

**Comment by lc-kay** [comment]
Hi @ivalkshfoeif 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ivalkshfoeif 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by ivalkshfoeif** [comment]
LeetcodeID： EnjoyLIFE2020
