### ISSUE TITLE
Submission / Run Code Inconsistency - 77. Combinations

### ISSUE THREAD

**Issue by jwaang** [LeetCode-Feedback/LeetCode-Feedback#4313]
#### Your LeetCode username
jwaang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Submission / Run Code Inconsistency

#### Description of the bug
My code returns the expected output when using Run Code for a testcase, but fails whenever I submit it.

#### Code you used for Submit/Run operation

```
/**
 * @param {number} n
 * @param {number} k
 * @return {number[][]}
 */
let RESULTS = [];
var combine = function(n, k) {
    backtrack(1, [], n, k)
    return RESULTS;
};

var backtrack = function(idx, curr, n, k) {
    if (curr.length === k) {
        RESULTS.push([...curr]);
        return;
    }
    
    for(let i = idx; i <= n; ++i) {
        curr.push(i);
        backtrack(i + 1, curr, n, k);
        curr.pop();
    }
}
```

#### Language used for code
Javascript

#### Expected behavior

When using the input:
```
1
1
```
The expected output is [[1]] and my code outputs this and succeeds when I use Run Code.
When I submit my code, my code fails on [[1]] and returns [[1,2],[1,3],[1,4],[2,3],[2,4],[3,4],[1]] instead.

#### Screenshots

![image](https://user-images.githubusercontent.com/8783957/127193373-ecaedcb2-6d8f-4a74-bbcb-dda17f220784.png)
Notice how we have the same inputs but differing outputs.

**Comment by lc-kay** [comment]
Hi @jwaang 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
