### ISSUE TITLE
Solution - 125. Valid Palindrome

### ISSUE THREAD

**Issue by brent-franklin** [LeetCode-Feedback/LeetCode-Feedback#4315]
#### Your LeetCode username

That0ne408

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I input the answer and click the "run code" button on the website and it passes the initial test. When I submit, it says that the regex is undefined and so it cannot execute the join() function. I paste the same function into a node repl and it works just fine as far as I can see...

#### Code you used for Submit/Run operation

```
// Valid Palindrome
var isPalindrome = function(s) {
    const re = s.match(/\w*\w/gi).join('').toLowerCase();
    for(let i = 0; i < Math.floor(re.length/2); i++){
        if(re[i] !== re[re.length-1-i]) return false;
    }
    return true;
};
```

#### Language used for code

Javascript

#### Expected behavior

return true if string is valid palendrome i.e. "racecar" => true; "notracecar" => false;

#### Additional context

Runtime Error Message: Line 6 in solution.js
    const re = s.match(/\w*\w/gi).join('').toLowerCase();
                                 ^
TypeError: Cannot read property 'join' of null
    Line 6: Char 34 in solution.js (isPalindrome)
    Line 21: Char 19 in solution.js (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 12: Char 26 in solution.js (Object.<anonymous>)
    Line 1251: Char 30 in loader.js (Module._compile)
    Line 1272: Char 10 in loader.js (Object.Module._extensions..js)
    Line 1100: Char 32 in loader.js (Module.load)
    Line 962: Char 14 in loader.js (Function.Module._load)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    Line 17: Char 47 in run_main_module.js
Last executed input: " "

 
Run Code Status: Finished
Run Code Result:
Your input

"A man, a plan, a canal: Panama"

Your answer

true

Expected answer

true

**Comment by MrWasay7** [comment]
The error happens because s.match() returns null.

var isPalindrome = function(s) {
    const cleanStr = s.toLowerCase().replace(/[^a-z0-9]/g, '');
    let left = 0;
    let right = cleanStr.length - 1;

    while (left < right) {
        if (cleanStr[left] !== cleanStr[right]) return false;
        left++;
        right--;
    }

    return true;
};
