### ISSUE TITLE
A TYPO IN QUESTION - 289. Game of Life

### ISSUE THREAD

**Issue by kjain05** [LeetCode-Feedback/LeetCode-Feedback#4316]
#### Category of the bug
A typo in question.

#### Description of the bug

In points 1,2,3,4...
Spelling of neighbours is wrong

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@kjain05 Please clear all cache and cookies and refresh the page. This problem has been updated to address that typo previously. If you still see an issue, please provide a screenshot and highlight the area. Thank you for your time.
