### ISSUE TITLE
Beautiful Array - Daily challenge for July day 28

### ISSUE THREAD

**Issue by msm1089** [LeetCode-Feedback/LeetCode-Feedback#4318]
#### Your LeetCode username
msm1089@yahoo.co.uk

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The requirements are as follows:
For some fixed n, an array nums is beautiful if it is a permutation of the integers 1, 2, ..., n, such that:
For every i < j, there is no k with i < k < j such that nums[k] * 2 = nums[i] + nums[j].
Given n, return **any** beautiful array nums.  (It is guaranteed that one exists.)

For n=4, there are 10 permutations of 1,2,3,4 which are beautiful:
(1, 3, 2, 4) <-- my answer (note I return a list [1, 3, 2, 4], not the tuple shown)
(1, 3, 4, 2)
(2, 1, 4, 3) <-- the test case for n=4 requires only this answer (as a list, [2, 1, 4, 3])
(2, 4, 1, 3)
(2, 4, 3, 1)
(3, 1, 2, 4)
(3, 1, 4, 2)
(3, 4, 1, 2)
(4, 2, 1, 3)
(4, 2, 3, 1)

The same is true for all test cases I believe. So either the test cases need to include ALL possible solutions, or the question needs to be corrected to give some criteria for the actual expected solution when more than one solution exists.

#### Code you used for Submit/Run operation

```
from itertools import permutations as perm

class Solution(object):
    def beautifulArray(self, n):
        """
        :type n: int
        :rtype: List[int]
        """
        perms = perm(list(range(1, n + 1)))
        for p in perms:
            beautiful = True
            for i in range(n - 2):
                if not beautiful:
                    break
                for j in range(2, n):
                    if not beautiful:
                        break
                    for k in range(i + 1, j):
                        beautiful = 2 * p[k] != p[i] + p[j]
                        if not beautiful:
                            break
            if beautiful:
                return p
```

#### Language used for code
Python

#### Expected behavior
By following the requirements, I expected that any one of the possible permutations would be accepted. But the test cases insist that only one particular solution is allowed.

**Comment by lc-kay** [comment]
@msm1089 Per the problem statement, "Given n, return **any** beautiful array nums." If you run the code, you can see that your answer is accepted. In addition, I've run your code and it appears to fail due to a time limit error and not a wrong answer. 
<img width="1369" alt="Screen Shot 2021-07-28 at 10 20 25 AM" src="https://user-images.githubusercontent.com/70870126/127367732-40f24ae6-cdcc-4b04-aee9-0180fee625ce.png">
