### ISSUE TITLE
39. Combination Sum

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#432]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Insufficient problem description/constraints

![Untitled](https://user-images.githubusercontent.com/63714778/84449070-f4fd3580-ac69-11ea-95cc-01faa128f0e8.png)

#### Code you used for Submit/Run operation

```
class Solution(object):
    def combinationSum(self, c, t):
        sys.setrecursionlimit(1<<30)
        def f(i,t,a):
            if t==0:
                z.append(a[:])
                return
            if i==n or t<0:
                return
            a.append(c[i])
            f(i,t-c[i],a)
            a.pop()
            f(i+1,t,a)
        c.sort(reverse=True)
        n=len(c)
        z=[]
        f(0,t,[])
        return z
```

#### Language used for code
Python

#### Expected behavior
The solution is accepted but fails for the test case

```
[1,2,3,6,7]
100000000
```

An accepted solution should pass all test cases within the scope of problem description/constraints. So either this solution should not pass or test case should be invalidated through problem description/constraints. The following asserts are valid.

```
assert(0<=t<=310)
assert(0<=max(c)<=120)
assert(0<=len(c)<=30)
```

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by leet212** [comment]
Hello @lc-kate 
Any update on this?

**Comment by lc-christina** [comment]
Hi @leet212 ,
Thanks for following up! The team is still working on the issue. We'll get back to you as soon as we received updates from the team. Thank you again for the support and patient.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
