### ISSUE TITLE
Missing Test Case - 295. Find Median from Data Stream

### ISSUE THREAD

**Issue by satyendranagarro** [LeetCode-Feedback/LeetCode-Feedback#4321]
issue with test case

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@satyendranagarro Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
