### ISSUE TITLE
Missing Test Case - 140. Word Break II

### ISSUE THREAD

**Issue by Jerry-007** [LeetCode-Feedback/LeetCode-Feedback#4326]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code submission accepted but give WA on some test cases .
For eg: -
"aaaaaaaaaaaaaaaaaaaa"
["aaaaa","aaaa","aaa","aa","a"]

#### Code you used for Submit/Run operation

```
vector<string> ans;
void solve (string s, string str, unordered_set<string> &st)
{
    if(s == "")
    {
        str.pop_back();
        ans.push_back(str);
        return ;
    }
    
    for(int i=1;i<=s.length();i++)
        if(st.find(s.substr(0,i)) != st.end())
            solve(s.substr(i), str + s.substr(0,i) + " ", st);

}
class Solution {
public:
    vector<string> wordBreak(string s, vector<string>& wordDict) {
        unordered_set<string> st;
        ans.clear();
        
        for(int i=0;i<wordDict.size();i++)
            st.insert(wordDict[i]);
        
        solve(s, "", st);
        return ans;
    }
};
```

#### Expected behavior

The code should not have got accepted .

**Comment by lc-kay** [comment]
Hi @Jerry-007 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Jerry-007 The solution is correct but our platform limits the output size. Therefore, we did not add this test case. Thank you for your understanding.

**Comment by Jerry-007** [comment]
Thank You ! 🙂
