### ISSUE TITLE
LeetCode题目435判题有问题

### ISSUE THREAD

**Issue by natureXD** [LeetCode-Feedback/LeetCode-Feedback#4327]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名：Sherry

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
显示用例都过了，却未显示通过，而是超时。
![image](https://user-images.githubusercontent.com/16025234/127491075-dcd32d23-4f51-4fa3-842d-83b66f83cd61.png)

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    int eraseOverlapIntervals(vector<vector<int>>& intervals) {
        sort(intervals.begin(), intervals.end(), [&](vector<int> a, vector<int> b) {
            return (a[1] < b[1]);
        });
        int preEnd = intervals[0][1];
        int count = 1; // 留下的数量
        for (size_t i = 1; i < intervals.size(); ++i) {
            if (preEnd <= intervals[i][0]) {
                // 有重叠，需要去除
                count++;
                preEnd = intervals[i][1];
            }
        }
        return intervals.size() - count;
    }
};
```

**期望行为**
描述你期望的结果：结果正确，或者失败的用例。

**屏幕截图**
![image](https://user-images.githubusercontent.com/16025234/127491128-9a92842b-16f9-46da-965d-b449e52236d7.png)
**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by stormsunshine** [comment]
单个测试用例都没有超出时间限制，但是总时间超出时间限制。需要进一步优化复杂度。
这是LeetCode的规则，不是判题有问题。

**Comment by natureXD** [comment]
> 单个测试用例都没有超出时间限制，但是总时间超出时间限制。需要进一步优化复杂度。
> 这是LeetCode的规则，不是判题有问题。

我看题解里面，也有类似的解答呀，这个解答请问什么地方还可以进行优化呀？

**Comment by feiceh** [comment]
@natureXD 您好，在与相关团队核实后：建议将 “[&](vector<int> a, vector<int> b” 优化为 “[&](vector<int>& a, vector<int>& b”， 通过引用减少创建临时变量次数。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。

**Comment by natureXD** [comment]
加上引用问题解决，谢谢
