### ISSUE TITLE
307. Range Sum Query - Mutable

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#433]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Inconsistent code and diagram in Approach 3: Segment Tree

#### Expected behavior
The segment tree illustrated in Approach 3 is not consistent with the code provided in the approach. The provided diagram is the only one so it is natural to refer to it.

Since the segment tree is a difficult and advanced data structure a big part of understanding it comes from being able to visualize it. That is why it is potentially misleading.

Either the diagram should be updated to reflect the code and avoid any ambiguities. I would also say to choose an example that shows a full and balanced binary tree which is easier to visualize unlike the current one.

Or a warning should be given alongside the diagram that the tree is not representative of the code.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem image and explanation. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
