### ISSUE TITLE
Question 79 [Word Search] Missing test case

### ISSUE THREAD

**Issue by yinchen** [LeetCode-Feedback/LeetCode-Feedback#4331]
---
name: Bug report (English)
about: Create a bug report to help us improve our content.
title: 'Question 79 Word Search Missing test case'
labels: ''
assignees: ''

---

#### Your LeetCode username

yinchen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug
Missing test case
```
[["B","B","C","D"],["B","X","X","X"],["C","D","E","X"]]
"BBB"
```

#### Code you used for Submit/Run operation

```
class Solution {  
    public boolean exist(char[][] board, String word) {
        char[] arr = word.toCharArray();

        for (int i = 0; i < board.length; ++i)
          for (int j = 0; j < board[0].length; ++j)
            if (search(arr.length - 1, i, j, board, arr)) 
              return true;

        return false;
    }
  
    private boolean search(int p, int i, int j, char[][] board, char[] word) {
        if (p < 0) return true;
        if (i < 0 || i >= board.length || j < 0 || j >= board[i].length ||
            board[i][j] == '0' || board[i][j] != word[p])
          return false;

        board[i][j] = '0'; // THIS MAKES SURE THAT WE DO NOT REVISIT THE SAME ELEMENT
        p--;
        boolean answer =  search(p, i, j + 1, board, word) ||
                          search(p, i + 1, j, board, word) ||
                          search(p, i, j - 1, board, word) ||
                          search(p, i - 1, j, board, word);
        
        return answer;
    }
}
```

#### Language used for code
Java

#### Expected behavior
This solution passes submission but it should fail. 
Sample test case
```
[["B","B","C","D"],["B","X","X","X"],["C","D","E","X"]]
"BBB"
```

**Comment by lc-kay** [comment]
Hi @yinchen 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yinchen 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
