### ISSUE TITLE
Missing Test Case - 975. Odd Even Jump

### ISSUE THREAD

**Issue by fdawg4l** [LeetCode-Feedback/LeetCode-Feedback#4335]
#### Your LeetCode username
fdawg4l

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The testcase when run using the "Run Code" dialog yields the right result for the given input.  Yet the same input in Submit says the output is wrong.

#### Code you used for Submit/Run operation

```
type suit string

const (
	odd  = suit("odd")
	even = suit("even")
)

// cache results so we dont recompute things
// (fromIdx, suit) -> next to
var cache = make(map[origin]origin)

type origin struct {
	// the current idx
	idx int
	// the current jump is odd or even
	suit suit
}

//During odd-numbered jumps (i.e., jumps 1, 3, 5, ...), you jump to the index j such that arr[i] <= arr[j] and arr[j] is the smallest possible value. If there are multiple such indices j, you can only jump to the smallest such index j.
// fromEven returns the idx (by value) we can jump to
func fromEven(arr []int, from int) int {
	var (
		minVal int = int((1 << 31) - 1)
		minIdx int = -1
	)

	for i := from + 1; i < len(arr); i++ {
		if arr[from] <= arr[i] && arr[i] < minVal {
			minVal = arr[i]
			minIdx = i
		}
	}

	return minIdx
}

// fromOdd returns idx (by value) we can jump to
func fromOdd(arr []int, from int) int {
	var (
		maxVal int = int((1<<31)-2) * -1
		maxIdx int = -1
	)

	for i := from + 1; i < len(arr); i++ {
		//fmt.Printf("i=%d fromVal = %d iVal = %d maxVal = %d\n", i, arr[from], arr[i], maxVal)
		if arr[from] >= arr[i] && arr[i] > maxVal {
			maxVal = arr[i]
			maxIdx = i
			//fmt.Println("sold")
		}
	}

	return maxIdx
}

func (o origin) nextJump(arr []int) origin {
	var (
		next origin
		ok   bool
	)

	if next, ok = cache[o]; ok {
		return next
	}

	switch o.suit {
	case odd:
		next.idx = fromOdd(arr, o.idx)
		next.suit = even
	case even:
		next.idx = fromEven(arr, o.idx)
		next.suit = odd
	}

	cache[o] = next
	return next
}

func (o origin) hasSolution(arr []int) bool {
	var next origin = o
	for {
		if next.idx == len(arr)-1 {
    		return true
		}

		if next.idx == -1 {
			return false
		}

		next = next.nextJump(arr)
	}
}

func oddEvenJumps(arr []int) int {
	var solutions int

	for i := 0; i < len(arr); i++ {
		//for i := 3; i < len(arr); i++ {
		o := origin{
			idx:  i,
			suit: even,
		}

		if o.hasSolution(arr) {
			solutions++
		}
	}

	return solutions
}
```

#### Language used for code
go

#### Expected behavior
Using a Custom Testcase of `[2,3,1,1,4]`, the output is `3`.  The custom testcase says the my answer and the expected answer are the same;  `3`.

Yet, when I submit my code, the Submission Result says wrong answer.  And that the output was `2` and the expected output should have been `3`

#### Screenshots

![screen](https://user-images.githubusercontent.com/4296242/127603555-82adaa23-15de-47c1-82e6-d382b8f45361.png)

**Comment by lc-kay** [comment]
Hi @fdawg4l 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
