### ISSUE TITLE
thread

### ISSUE THREAD

**Issue by hui0394** [LeetCode-Feedback/LeetCode-Feedback#4336]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@hui0394 Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
