### ISSUE TITLE
282. Expression Add Operators

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#434]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing test cases or constraints

#### Code you used for Submit/Run operation

```
class Solution:
    def addOperators(self, s: str, t: int) -> List[str]:
        def f(i,p):
            if i==len(s):
                q=''.join(p)[1:]
                if q and eval(q)==t:
                    z.append(q)
                return
            q=0
            for j in range(i,len(s)):
                if j!=i and s[i]=='0':
                    break
                q=q*10+int(s[j])
                for x in ('+'+str(q),'-'+str(q),'*'+str(q))[:1 if i==0 else 3]:
                    p.append(x)
                    f(j+1,p)
                    p.pop()
        z=[]
        f(0,[])
        return z
```

#### Language used for code
Python3

#### Expected behavior

This solution uses a strategy that should not be accepted according to the editorial itself.

> Well, one way to go about this is to write a custom eval function that takes in a string and returns the value of that expression. If you do that (Python people can use the inbuilt function eval for this), you will get a TLE i.e. time limit exceeded error.

This solution fails for the test case

```
"12345678999"
2147483647
```

Either the test case should be added which works with the official solution or the constraints should be given (0<=len(s)<=10)

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem constraint. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
