### ISSUE TITLE
Missing Test Case - 677. Map Sum Pairs

### ISSUE THREAD

**Issue by shivamls** [LeetCode-Feedback/LeetCode-Feedback#4340]
#### Your LeetCode username
AGARvalaAgarwal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I submitted the solution using a map and an array to keep track of the keys so far which gives the complexity of O(n) for insertion and O(n) for sum while this can be done in O(n) sum and O(1) insertion and my solution beat 100% of the solutions in time,

I think one case where there are all insertion operations should be added to discourage such solutions and encourage participants to go to the most optimized solution

Test Case to be added:

```
["MapSum", "insert", "insert", "insert", "insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","insert","sum"]
[[], ["apple",3], ["ap", 1], ["app",2], ["apsp",2], ["appq",2], ["appw",2], ["appe",2], ["appr",2], ["appt",2], ["appy",2], ["appu",2], ["appi",2], ["appo",2], ["appp",2], ["appa",2], ["apps",2], ["appd",2], ["appf",2], ["appg",2], ["apph",2], ["appj",2], ["appk",2], ["appl",2], ["appz",2], ["appx",2], ["appc",2], ["appv",2], ["appb",2], ["appn",2], ["appm",2], ["appmm",2], ["appnn",2], ["appbb",2], ["appvv",2], ["appcc",2], ["appxx",2], ["appss",2], ["appdd",2], ["appff",2], ["appgg",2], ["apphh",2], ["appjj",2], ["appkk",2], ["appll",2], ["appqq",2], ["appww",2], ["appee",2], ["apprr",2], ["apprree",2],["ap"]]
```

#### Code you used for Submit/Run operation

```
class MapSum {
public:
    /** Initialize your data structure here. */
    unordered_map<string, int> mp;
    vector<string> keys;
    MapSum() {
        
    }
    
    void insert(string key, int val) {
        mp[key] = val;
        
        bool present = false;
        for(int i=0; i<keys.size(); i++){
            if(keys[i] == key){
                present = true;
            }
        }
        if(present == false) keys.push_back(key);
    }
    
    int sum(string prefix) {
        int result = 0;
        int size = keys.size();
        for(int i=0; i<size; i++){
            string sub = keys[i].substr(0, prefix.length());
                
            if(sub.compare(prefix) == 0){
                result+= mp[keys[i]];
            }
        }
        return result;
    }
};

/**
 * Your MapSum object will be instantiated and called as such:
 * MapSum* obj = new MapSum();
 * obj->insert(key,val);
 * int param_2 = obj->sum(prefix);
 */
```

#### Language used for code

C++

#### Expected behavior

This should take more time as compared to a simple map iterator solution but it actually takes less time because the test case where most operations are sum operations does not exist

#### Screenshots

<img width="1372" alt="Screenshot 2021-07-30 at 3 13 43 PM" src="https://user-images.githubusercontent.com/40359923/127634978-6f7f9b31-ff95-4a6b-9cea-976938773abf.png">

**Comment by lc-kay** [comment]
Hi @shivamls 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@shivamls Our team has checked our test case set for this question and noticed that we have similar test cases already. Therefore, we will not be adding this one. Thank you for your time.
