### ISSUE TITLE
Merge Sorted Aarray

### ISSUE THREAD

**Issue by London804** [LeetCode-Feedback/LeetCode-Feedback#4342]
#### Your LeetCode username

London804

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Solution

#### Description of the bug

My solution is working in the browser and returning what your testcase is expecting, but in your code editor it claims that my output is different

#### Code you used for Submit/Run operation

```
// Merge Sorted Array
var merge = function(nums1, m, nums2, n) {
    
    let array1 = nums1;
    let array2 = nums2;

    array1 = array1.slice(0, m);
    array2 = array2.slice(0, n);

    array1 = array1.concat(array2);
    array1 = array1.sort()

    return array1
    
};
```

#### Language used for code

Javascript

#### Expected behavior

The editor states my answer returns [1,2,3,0,0,0] and the expected answer is [1,2,2,3,5,6]. However, when I run this in my browser i get exactly what your expected answer returns. I have no way of debugging this in your editor so I don't know why that is being returned. 

#### Screenshots

![image](https://user-images.githubusercontent.com/3270733/127705634-d37ed384-61a1-4012-bea5-70bddccdfab2.png)

#### Additional context

It would be great if you allowed developers to debug this in your code editor. This isn't the first time I've come across an issue.

**Comment by lc-kay** [comment]
@London804 Unfortunately, we are unable to distinguish the difference in behavior between your local environment and the LeetCode environment. However, I was able to find several accepted JS codes in the problem discuss section, please check them out https://leetcode.com/problems/merge-sorted-array/discuss/?currentPage=2&orderBy=most_relevant&query=javascript. Lastly, we do offer a debugger feature in our premium subscription and it supports Javascript. For more information, please check out https://leetcode.com/discuss/general-discussion/443443/All-New-Integrated-Debugger-Available-in-public-Beta-now!
