### ISSUE TITLE
Missing Test Case - 1293. Shortest Path in a Grid with Obstacles Elimination

### ISSUE THREAD

**Issue by elvin-yang** [LeetCode-Feedback/LeetCode-Feedback#4345]
#### Your LeetCode username
elvin.yx@gmail.com

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Defective solution could pass the current test cases.

#### Code you used for Submit/Run operation

```
class Solution {
    private int[][] moveVector = new int[][] {
            new int[]{0,1},
            new int[]{0,-1},
            new int[]{1, 0},
            new int[]{-1,0},
            };

    public int shortestPath(int[][] grid, int k) {
        int m = grid.length, n = grid[0].length;
        if (m == 1 && n == 1) return 0;
        // [i, j, k, len]
        Queue<int[]> q = new LinkedList<>();
        int[][] visited = new int[m][n];
        //for (int[] a : visited) Arrays.fill(a, -1);
        q.add(new int[] { 0, 0, k, 0 });
        visited[0][0] = k;
        while (!q.isEmpty()) {
            int[] h = q.poll();
            for (int[] mv : moveVector) {
                int ii = h[0] + mv[0], jj = h[1] + mv[1];
                if (0 <= ii && ii < m && 0 <= jj && jj < n) {
                    if (ii == m - 1 && jj == n - 1) {
                        return h[3] + 1;
                    }
                    if (grid[ii][jj] == 0 || h[2] > 0) {
                        int kk = (grid[ii][jj] == 0 ? h[2] : h[2] - 1);
                        if (h[2] > visited[ii][jj]) {
                            visited[ii][jj] = h[2];
                            q.add(new int[] { ii, jj, kk, h[3] + 1 });
                        }
                    }
                }
            }
        }
        return -1;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The code is defective and fails on following test case but it can pass the OJ.
Please add the following test case:
```
[[0,1,0,0,0,0],[0,1,0,1,1,0],[0,1,0,1,1,0],[0,1,0,1,1,0]]
1
```

**Comment by lc-kay** [comment]
Hi @elvin-yang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @elvin-yang 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by elvin-yang** [comment]
> Hi @elvin-yang
> Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

Thanks.
My LeetCode ID is: elvinyang
