### ISSUE TITLE
Missing Test Case - 42. Trapping Rain Water

### ISSUE THREAD

**Issue by raditya1710** [LeetCode-Feedback/LeetCode-Feedback#4349]
#### Your LeetCode username
alfonsus_raditya

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
When the testcase is at maximum constraint (n = 30000, height[0] = 100000, height[1] = height[2] = ... = height[n - 2] = 0, height[n - 1] = 100000), the answer overflows, even it shows **Invalid Testcase** instead of wrong answer even though the constraints are valid.

#### Code you used for Submit/Run operation
```
class Solution:
    def trap(self, height: List[int]) -> int:
        n = len(height)
        pref = [0 for i in range(n)]
        suff = [0 for i in range(n)]

        cur_max = 0
        for i, el in enumerate(height):
            cur_max = max(cur_max, el)
            pref[i] = cur_max
        
        cur_max = 0
        for i, el in reversed(list(enumerate(height))):
            cur_max = max(cur_max, el)
            suff[i] = cur_max
            
        ans = 0
        for i, el in enumerate(height):
            ans += min(pref[i], suff[i]) - el
            
        return ans
```

#### Language used for code

Python 3

#### Expected behavior
It should get the answer: 2999800000

#### Screenshots
![Screenshot from 2021-07-31 15-13-22](https://user-images.githubusercontent.com/14028227/127733624-f0b61961-cc1e-44ba-acc6-bf90047b34bd.png)
![Screenshot from 2021-07-31 15-13-30](https://user-images.githubusercontent.com/14028227/127733622-52829bfd-9d13-4c83-85d1-16eaafaec3b4.png)

#### Additional context

Testcase used: 
[trapping_rain_water_tc_max.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6910884/trapping_rain_water_tc_max.txt)

**Comment by lc-kay** [comment]
Hi @raditya1710 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @raditya1710 
Thank you for your time. The test case is invalid because it causes integer overflow in the languages that uses 32-bit integer. Therefore, we have changed the constraints to disallow overflow test cases. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
