### ISSUE TITLE
277. Find the Celebrity

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#435]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 2: Logical Deduction has wrong description

#### Expected behavior

> So, what can we conclude from the result of an A knows B check? If the result was true, could A be the celebrity? What about B?
And what about if A knows B returned false? Who couldn't be a celebrity now?
In the first example, we know that A can't be a celebrity, because A knows somebody, namely B. In the second example, we know that B can't be a celebrity, because B, doesn't know them.

This is wrong. B cannot be a celebrity when knows(A,B) returns false as A doesn't know B.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
