### ISSUE TITLE
Missing Test Case - 42. Trapping Rain Water

### ISSUE THREAD

**Issue by xavyding** [LeetCode-Feedback/LeetCode-Feedback#4351]
#### Your LeetCode username

dyxuki

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The solution below passed all test, but it should be O(n^2) time complexity in worst case.
And that worst case is basically a already sorted array. For example, we could have as input:
```
height = [x for x in range(10732)]
```
(I took 10732 here only because that's the length of test case 319)
The answer should be 0. But for this particular test case, the below solution throws TLE. (passed 319 however)

#### Code you used for Submit/Run operation

```
class Solution:
    def trap(self, height: List[int]) -> int:
        
        if len(height)==0: return 0
        
        dp = [0]*len(height)

        for i in range(1, len(dp)):
            dp[i] = dp[i-1]
            
            if height[i]>height[i-1]:
                k = i-1
                last_highest = height[i-1]
                while k >= 0 and last_highest <= height[i]:
                    if height[k] > last_highest:
                        dp[i] += (min(height[i], height[k]) - last_highest)*(i-k-1)
                        last_highest = height[k]
                    k-=1

        return dp[-1]
```

#### Language used for code

Python3

**Comment by lc-kay** [comment]
@xavyding Please provide the test case in .txt format. Thank you.

**Comment by xavyding** [comment]
@lc-kay Here you go.
[42testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6922427/42testcase.txt)

**Comment by lc-kay** [comment]
Hi @xavyding . I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @xavyding 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
