### ISSUE TITLE
https://leetcode-cn.com/problems/add-two-numbers/

### ISSUE THREAD

**Issue by wcdai** [LeetCode-Feedback/LeetCode-Feedback#4352]
https://leetcode-cn.com/problems/add-two-numbers/，没人教过你怎么出题？题干中没要求不能使用超int大小的数据，又自己定义ListNode中val的类型为int,还你拿个超过int大小数据做测试，题干中又不说明你要考察数字的大小，还不能改ListNode中var的值。有毒吧，你干脆题目描述都别写了，出的什么题，让大家去猜。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，请仔细阅读理解题目意思。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路哦～
