### ISSUE TITLE
Remove testcase of 58. Length of Last Word

### ISSUE THREAD

**Issue by MayankMaheshwar** [LeetCode-Feedback/LeetCode-Feedback#4354]
Input: s = " "
Output: 0

This test case is not valid as constraints are not satisfied.

Constraints:

1 <= s.length <= 104
s consists of only English letters and spaces ' '.

**Comment by lc-kay** [comment]
Hi @MayankMaheshwar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@MayankMaheshwar The test case is valid and satisfies the constraints. However, it is an edge case and can cause a lot of confusion, therefore, we have removed it to make the problem more simple. Thank you for your time.
