### ISSUE TITLE
imprecise language in 567. Permutation in String Medium

### ISSUE THREAD

**Issue by hamirmahal** [LeetCode-Feedback/LeetCode-Feedback#4356]
#### Your LeetCode username

hamirmahal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question states,
>Given two strings s1 and s2, return true if s2 contains **the** permutation of s1.

The definite article "the" implies ["there is only one" or "there is only one in that context"](https://learnenglish.britishcouncil.org/english-grammar-reference/definite-article-the). However, there can be many permutations.

#### Code you used for Submit/Run operation

not applicable

#### Language used for code

not applicable

#### Expected behavior

Use "a" instead, so that the first statement of the question becomes,
>Given two strings s1 and s2, return true if s2 contains **a** permutation of s1.

Or, we can say,
>Given two strings s1 and s2, return true if s2 contains **at least one** permutation of s1.

#### Screenshots

![Screen Shot 2021-07-31 at 4 51 43 PM](https://user-images.githubusercontent.com/43425812/127754917-d1ed8c1f-65f4-4e21-a6f2-1c44b01c7cff.png)

**Comment by lc-kay** [comment]
Hi @hamirmahal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hamirmahal 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by hamirmahal** [comment]
You're welcome, @lc-kay! Happy to help.
