### ISSUE TITLE
Missing Test Case - 42. Trapping Rain Water

### ISSUE THREAD

**Issue by qiyanghe1998** [LeetCode-Feedback/LeetCode-Feedback#4357]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The range of the input is that: 
0 <= n <= 3 * 10^4
0 <= height[i] <= 10^5

Which means the maximum answer will be (30000 - 2) * 10^5 = 2,999,800,000 > 2,147,483,647 (The upper bound of int).

Thus, the return type may be **unsigned int** or **long long**.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@qiyanghe1998 For a missing test case report, please provide the exact test case that is missing and the accepted code that it will fail. Thank you.

**Comment by qiyanghe1998** [comment]
I see that the range of the input has been changed (range of n becomes 2*10^4). If the range is still n <= 3*10^4. The test case in the attachment will lead to a wrong answer (at least for c++).
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6926640/testcase.txt)
`

**Comment by lc-kay** [comment]
@qiyanghe1998 The range was updated to disallow overflow test cases. Thank you for you understanding.

**Comment by qiyanghe1998** [comment]
I see. Thanks!
