### ISSUE TITLE
Example figure incorrect- 939. Minimum Area Rectangle

### ISSUE THREAD

**Issue by adarsh-verma1** [LeetCode-Feedback/LeetCode-Feedback#4359]
#### Category of the bug

- [x] Question (Link- [https://leetcode.com/problems/minimum-area-rectangle/](url))
- [ ]  Solution
- [ ] Language
- [ ] Missing Test Cases

#### Description of the bug

In the example 1, the Input points are given as: [[1,1],[1,3],[3,1],[3,3],[2,2]].
But in the corresponding graph, the points marked are: [[1,1],[1,3],[3,1],[3,3],[4,1],[4,3]]

#### Screenshots

![Screenshot (71)](https://user-images.githubusercontent.com/65245077/127772470-3b5b859f-7a44-438b-bb19-44db0fe4588b.png)

**Comment by lc-kay** [comment]
Hi @adarsh-verma1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @adarsh-verma1 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
