### ISSUE TITLE
Coin Change 2: description improve needed

### ISSUE THREAD

**Issue by evgeni-nabokov** [LeetCode-Feedback/LeetCode-Feedback#436]
#### Your LeetCode username
evgeni-nabokov

#### Category of the bug
- [*] Question

#### Description of the bug
I think it is worth to mention in the note that the number of coins could be 0 (you have such a test case). Why? Because in the beginning you clearly state 'You are given coins' which does not imply I may get zero coins.

**Comment by CooperCooperCooper** [comment]
Hi @evgeni-nabokov ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @evgeni-nabokov ,
Thank you for your time. Upon reviewing this problem's statement, our team found it to correct and these corner cases for our older problems are accepted.
