### ISSUE TITLE
Validation required in test script - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by dhruv1110** [LeetCode-Feedback/LeetCode-Feedback#4361]
#### Your LeetCode username
dhruv1110

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There is some more validation needed in mentioned problem's test script. I was looking in the solutions submitted by other people in 0ms and found that problem is solved incorrectly still solution is accepted with 0ms.

#### Language used for code
java

#### Expected behavior
In the 2nd screenshot, you can see that someone returns the same input as output without any processing or shortUrl creation. Still, the solution is accepted so this should be validated from the test cases and fail the test case

#### Screenshots
1. <img width="702" alt="Screen Shot 2021-08-01 at 4 21 01 PM" src="https://user-images.githubusercontent.com/9786653/127784315-17df8277-10c2-4f1d-aeb9-86560346175c.png">

2. <img width="692" alt="Screen Shot 2021-08-01 at 4 21 56 PM" src="https://user-images.githubusercontent.com/9786653/127784335-b30b7315-3762-41ce-88c3-22c71c831e62.png">

**Comment by lc-kay** [comment]
Hi @dhruv1110 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@dhruv1110 Thanks for this feedback but we cannot change the driver for consistency. We may consider this when we publish a new version of it. We appreciate your time and support.
