### ISSUE TITLE
missing test case - 246. Strobogrammatic Number

### ISSUE THREAD

**Issue by ozgunawesome** [LeetCode-Feedback/LeetCode-Feedback#4362]
#### Your LeetCode username
thatonemorekid

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Add a test case where the string is odd length and the middle number is 6 or 9. The following code passes everything on submit but will miss "868" for example.

#### Code you used for Submit/Run operation

```
class Solution {
   
    private static final int[] rotated = new int[]{0, 1, -1, -1, -1, -1, 9, -1, 8, 6};
    public boolean isStrobogrammatic(String num) {
        
        if (num.length() == 1) {
            return num.equals("0") || num.equals("1") || num.equals("8");
        }
        
        char[] str = num.toCharArray();
        
        for (int i = 0, j = num.length() - 1; i < j; i++, j--) {
            
            if ( rotated[str[i] - '0'] != str[j] - '0' ) {
                return false;
            }
            
        }
        
        return rotated[str[str.length / 2] - '0'] != -1;
    }
}
```

#### Language used for code
Java

#### Expected behavior
`isStrobogrammatic("868") == false`

**Comment by lc-kay** [comment]
Hi @ozgunawesome 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ozgunawesome 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
