### ISSUE TITLE
Missing Test Case - 31. Next Permutation

### ISSUE THREAD

**Issue by yash9575** [LeetCode-Feedback/LeetCode-Feedback#4363]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@yash9575 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
