### ISSUE TITLE
Test case unsatisfiable for Scala - 1707. Maximum XOR With an Element From Array

### ISSUE THREAD

**Issue by cosminci** [LeetCode-Feedback/LeetCode-Feedback#4366]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The `1000000000, 1000000000` query test case fails with a `Memory Limit Exceeded` when using Scala. The implementation is standard as in other languages with the trie built iteratively. Scala is generally more memory intensive so for this particular test case the imposed threshold might be too low.

On my machine, the run uses ~300MB according to Async Profiler (this includes input parsing), and takes ~200ms.

#### Code you used for Submit/Run operation

```
  def maximizeXor(nums: Array[Int], queries: Array[Array[Int]]): Array[Int] = {
    nums.sortInPlace()
    val sortedQueries = queries.zipWithIndex.sortInPlaceBy(_._1.last)

    val root = new TrieNode()
    var numIdx = 0
    val results = sortedQueries.map { case (Array(queryNum, maxAllowed), originalIdx) =>
      while (numIdx < nums.length && nums(numIdx) <= maxAllowed) {
        addToTrie(nums(numIdx), root)
        numIdx += 1
      }

      (findMaxXORInTrie(queryNum, root), originalIdx)
    }
    val sortedResults = results.sortBy(_._2)
    sortedResults.map(_._1).toArray
  }

  class TrieNode(val children: mutable.Map[Int, TrieNode] = mutable.Map.empty, var value: Option[Int] = None)

  private def addToTrie(n: Int, root: TrieNode): Unit = {
    (31 to 0 by -1).foldLeft(root) { case (node, bitIdx) =>
      val bit = (n >> bitIdx) & 1
      if (node.children.contains(bit))
        node.children(bit)
      else {
        val newNode = new TrieNode()
        node.children.update(bit, newNode)
        newNode
      }
    }.value = Some(n)
  }

  private def findMaxXORInTrie(n: Int, root: TrieNode): Int = {
    if (root.children.isEmpty) return -1
    (31 to 0 by -1).foldLeft(root) { case (node, bitIdx) =>
      val bit = (n >> bitIdx) & 1
      if (node.children.contains(bit ^ 1))
        node.children(bit ^ 1)
      else
        node.children(bit)
    }.value.get ^ n
  }
```

#### Language used for code
Scala

#### Expected behavior
Test case should pass

#### Screenshots
[66/67 Submission screenshot](https://imgur.com/urXai3I)

#### Additional context
Submission: https://leetcode.com/submissions/detail/532076365/

**Comment by lc-kay** [comment]
@cosminci Please provide the submission details link to your code. Thank you.

**Comment by cosminci** [comment]
@lc-kay done - added to ## Additional context in the original description.

**Comment by lc-kay** [comment]
Hi @cosminci I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@cosminci Here is an example of an AC Scala solution.
`object Solution {
def maximizeXor(nums: Array[Int], queries: Array[Array[Int]]): Array[Int] = {
    val sorted = nums.sorted
    val res = Array.fill(queries.length)(0)
    queries.indices.foreach(i => res(i) = getMax(sorted, queries(i)(0), queries(i)(1)))
    res
  }

  def getMax(nums: Array[Int], x: Int, m: Int): Int = {
    if (nums.head > m) return -1
    var l = 0
    var r = java.util.Arrays.binarySearch(nums, m + 1)

    if (r < 0) r = -(r + 1)

    var bp = 30
    var base = 0

    while (bp >= 0 && (0x1 << bp) > m) bp -= 1

    while (bp >= 0 && l < r) {
      var bv = base + (0x1 << bp)
      var p = java.util.Arrays.binarySearch(nums, l, r, bv)

      if (p < 0) p = -(p + 1)
      else while (p > 0 && nums(p) == nums(p - 1)) p -= 1

      if (((0x1 << bp) & x) == 0) {
        if (p < r) {
          base |= bv
          l = p
        }
      } else {
        if (p > l) r = p
        else base |= bv
      }
      bp -= 1
    }
    nums(l) ^ x
  }
}`
Our team tried your solution with double the memory limit and it is still MLE. Please check out the solution I just provided for reference. Thank you for your time.
