### ISSUE TITLE
WRONG constraint, it will cause TLE! 170. Two Sum III - Data structure design

### ISSUE THREAD

**Issue by hiepxuan2008** [LeetCode-Feedback/LeetCode-Feedback#4367]
#### Your LeetCode username
hiepit

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Following is constraint from Leetcode (last updated 02/08/2020):
**Constraints:**
- `-10^5 <= number <= 10^5`
- `-2^31 <= value <= 2^31 - 1`
- At most `5 * 10^4` calls will be made to add and find.

**Time complexity** of the Official Solution and other discussions are `O(1)` for `Add`, `O(N)` for `Find`. I wonder if I have the testcase:  
- Call `Add` to add `10^4` different numbers
- Call `Find` `4*10^4` times.
=> Each of `Find` operation take O(N) ~ `10^4` times
=> Total = `(10^4) * (4*10^4) = 4 * 10^8`
=> `Time Limit Exceeded!` occurs.

#### Code you used for Submit/Run operation

```python
class TwoSum(object):

    def __init__(self):
        """
        Initialize your data structure here.
        """
        self.num_counts = {}


    def add(self, number):
        """
        Add the number to an internal data structure..
        :type number: int
        :rtype: None
        """
        if number in self.num_counts:
            self.num_counts[number] += 1
        else:
            self.num_counts[number] = 1

    def find(self, value):
        """
        Find if there exists any pair of numbers which sum is equal to the value.
        :type value: int
        :rtype: bool
        """
        for num in self.num_counts.keys():
            comple = value - num
            if num != comple:
                if comple in self.num_counts:
                    return True
            elif self.num_counts[num] > 1:
                return True
        
        return False
```

#### Language used for code
Python

#### Expected behavior

The constraint from Leetcode problem description is WRONG.
Following is constraint from Leetcode (last updated 02/08/2020):
**Constraints:**
- `-10^5 <= number <= 10^5`
- `-2^31 <= value <= 2^31 - 1`
- At most `5 * 10^4` calls will be made to add and find.

I think we can change the constraint as:
**Constraints:**
- `-10^5 <= number <= 10^5`
- `-2^31 <= value <= 2^31 - 1`
- At most `10^3` calls will be made to add and find.

Since limit to `10^3`, it can work in `O(N^2)`.

#### Screenshots

![image](https://user-images.githubusercontent.com/6292433/127863205-509d40b0-f38e-4a8e-8f25-9d79bd188f5f.png)

#### Additional context

This is the valid testcase can cause TLE: https://pastebin.pl/view/385bc1fd

This is the Python code to generate the testcase:
```python
arr = [[]]
operations = ["TwoSum"]
for x in range(2, 10**4 + 1):
    operations.append("add")
    arr.append([x])

operations.append("add")
arr.append([10**4])

for i in range(4 * 10**4):
    operations.append("find")
    arr.append([2 * 10**4])

print(operations)
print(arr)
```

**Comment by lc-kay** [comment]
Hi @hiepxuan2008 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hiepxuan2008 An average processor can handle 4 * 10^8 operations in less than 1s. Therefore, the current constraints should be ok and are not invalid. Our team tried to add the provided test case and it didn't fail c++ and java solutions, but py solutions failed. This is due to the nature of python. With that, we have reduced the constraints a bit to be fair for py. Thank you for your understanding.

**Comment by hiepxuan2008** [comment]
Hi @lc-kay , 
I see the problem constraint is updated from `5*10^4` to `10^4` but you think that there is no credit for me to finding this?

**Comment by hiepxuan2008** [comment]
Hi @lc-kay 

If you keep the problem constraint as `5*10^4`, how can the following testcase run within 1 second in Java?
Add: `2.5 * 10^4` times
Find: `2.5 * 10^4` times
Which have total operations as:  `6.25 * 10^8`

I tested in my Machine, it runs within `Total time: 6773 ms`
![image](https://user-images.githubusercontent.com/6292433/128425051-b33a23c0-e1e4-451b-8b2d-f483655ad5d5.png)

This is the demonstrated code:
```java
class TwoSum {
    private HashMap<Integer, Integer> num_counts;

    /** Initialize your data structure here. */
    public TwoSum() {
        this.num_counts = new HashMap<Integer, Integer>();
    }

    /** Add the number to an internal data structure.. */
    public void add(int number) {
        if (this.num_counts.containsKey(number))
            this.num_counts.replace(number, this.num_counts.get(number) + 1);
        else
            this.num_counts.put(number, 1);
    }

    /** Find if there exists any pair of numbers which sum is equal to the value. */
    public boolean find(int value) {
        for (Map.Entry<Integer, Integer> entry : this.num_counts.entrySet()) {
            int complement = value - entry.getKey();
            if (complement != entry.getKey()) {
                if (this.num_counts.containsKey(complement))
                    return true;
            } else {
                if (entry.getValue() > 1)
                    return true;
            }
        }
        return false;
    }

    public static void main(String[] args) {
        long startTime = System.currentTimeMillis();
        TwoSum twoSum = new TwoSum();
        for (int i = 0; i < 25000; ++i) {
            twoSum.add(i);
        }
        for (int i = 0; i < 25000; ++i) {
            twoSum.find(1_000_000_000);
        }
        System.out.println("Total time: " + (System.currentTimeMillis() - startTime) + " ms");
    }
}
```

**Comment by lc-kay** [comment]
@hiepxuan2008 The model java solution needed less than 1s for this test case.

**Comment by hiepxuan2008** [comment]
Hi @lc-kay , so why you said that your team has tested the constraint `5*10^4`, it takes less than 1 second in C++ or Java?
