### ISSUE TITLE
Mismatching Example / Picture for Lonely Pixel I

### ISSUE THREAD

**Issue by bclodius** [LeetCode-Feedback/LeetCode-Feedback#4371]
#### Your LeetCode username
b_clodius

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Mismatching Example / Picture for [Lonely Pixel I](https://leetcode.com/problems/lonely-pixel-i/)

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
Input should be `[["B","B","B"],["B","B","W"],["B","B","B"]]` to match picture but it is `[["B","B","B"],["B","B","B"],["B","B","B"]]`

#### Screenshots
![image](https://user-images.githubusercontent.com/590724/127941938-de44c648-4e3f-4eae-b059-08b13280fc00.png)

**Comment by lc-kay** [comment]
Hi @bclodius 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @bclodius 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
