### ISSUE TITLE
154. Find Minimum in Rotated Sorted Array II 

### ISSUE THREAD

**Issue by Abhigyan2707** [LeetCode-Feedback/LeetCode-Feedback#4372]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

after success submission question is not getting marked as completed and not even counted in progress tab.

**Comment by lc-kay** [comment]
@Abhigyan2707 The progress page is updated daily so there could be a delay in the update of progress. Thank you for your understanding.
