### ISSUE TITLE
Incorrect test case (946. Validate Stack Sequences)

### ISSUE THREAD

**Issue by tharun49** [LeetCode-Feedback/LeetCode-Feedback#4373]
#### Your LeetCode username

Tharun49

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def validateStackSequences(self, pushed, popped):
        """
        :type pushed: List[int]
        :type popped: List[int]
        :rtype: bool
        """
        s =[pushed[0]]
        pushed.pop(0)
        while popped or pushed:
            fnd = True
            if s and popped and s[-1] != popped[0]:
                if pushed:
                    s.append(pushed[0])
                    pushed.pop(0)
                    fnd = False
            else:
                while s and popped and s[-1] == popped[0]:
                    s.pop()
                    popped.pop(0)
                    fnd = False
            if fnd:
                print(s, pushed, popped)
                return False
            
                        
        return True

    

```

#### Language used for code

python

#### Expected behavior

Test case itself is invalid based on the Constraints provided for the problem

#### Screenshots

Questions constraints says No empty pushed (pushed being equal to popped)
![image](https://user-images.githubusercontent.com/88381274/128009304-1794145e-5c7e-4cf6-8e90-994f5ce4e8be.png)
Supplied Input is Empty

Question Constraints
![image](https://user-images.githubusercontent.com/88381274/128009501-fc093831-f941-41b1-83d3-9325281db61d.png)

#### Additional context

Strangely I ran the code locally against the empty [],[] input and it threw error which was expected. Strange how the test case crept in.
This error came up in local run (expected 'pushed' to have 1 <= size <= 1000 but got 0)
So I would request appropriate action to be taken on this.
Either the constraints need to be changed or test case need to be removed!!

**Comment by lc-kay** [comment]
Hi @tharun49 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tharun49 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by tharun49** [comment]
Can I expect any points awarded for the same ?

**Comment by lc-kay** [comment]
@tharun49 Your account has been rewarded 100 LeetCoins for this content contribution.
