### ISSUE TITLE
question 713 has some missing test cases

### ISSUE THREAD

**Issue by ankushsood8** [LeetCode-Feedback/LeetCode-Feedback#4375]
#### Your LeetCode username

Ankushsood

#### Category of the bug
- [ 713] Question
- [ ] Solution
- [c++ ] Language
- [ yes] Missing Test Cases 

#### Description of the bug

[57,44,92,28,66,60,37,33,52,38,29,76,8,75,22]
18
add this test case my test case was failing on this test case but it get submited because it was not added in this question.

#### Code you used for Submit/Run operation

```

class Solution {
public:
    int numSubarrayProductLessThanK(vector<int>& nums, int k) {
      int counter=0;
      long prod=1;
          for(int i=0;i<nums.size();i++){
            if(nums[i]>=k){
                counter++;
            }
        }
        if(counter==nums.size()){
            return 0;
        }
      int i=0,j=0;
      while(j<nums.size()){
          if(prod*nums[j]<k){
              prod=prod*nums[j];
              counter+=j-i+1;
              j++;
          }
          else{
             prod=prod/nums[i];
              i++;
          }
      }
        return counter;       
    }
};
```

#### Language used for code

C++
#### Expected behavior

code gets submitted but it was failing on some test cases which i have included in description of bug section

**Comment by lc-kay** [comment]
Hi @ankushsood8 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ankushsood8 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
