### ISSUE TITLE
Contains Wrong Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by plazzy99** [LeetCode-Feedback/LeetCode-Feedback#4376]
#### Your LeetCode username

vatsalkesarwani

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Contains wrong test case

#### Code you used for Submit/Run operation

```
#define lli long long int
class Solution {
public:
    int findDuplicate(vector<int>& n) {
        int x = n.size(),z=0;
        lli sum= x*(x+1)/2;
        for(int y:n){
            z+=y;
        }
        return x-(int)(sum-z);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The question stated this: _There is only one repeated number in nums, return this repeated number._
But contains a test case [2,2,2,2,2]

#### Screenshots

![screenshot](https://user-images.githubusercontent.com/48295138/128078794-1909687f-1e59-47d6-b9ee-2b6ab4ae417d.png)

**Comment by lc-kay** [comment]
@plazzy99 This is a valid test case. Per the constraints, "All the integers in nums appear only once except for precisely one integer which appears two or more times." Only the number 2 is repeated two or more times. Thank you for your time.
