### ISSUE TITLE
Problem submission detail page broken

### ISSUE THREAD

**Issue by anniruddh** [LeetCode-Feedback/LeetCode-Feedback#438]
#### Your LeetCode username
andykoder

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Problem submission detail page is broken. Please refer to screenshot.

#### Language used for code
C#

#### Expected behavior
Should render submission details statistics for user.

#### Screenshots

![image](https://user-images.githubusercontent.com/2434794/84004151-fa801600-a91f-11ea-999f-f0c1023666bd.png)

**Comment by CooperCooperCooper** [comment]
Hi @anniruddh ,
Thank you for reaching out to us! To help us assess this issue, can you please clear your browser cache and cookies, and then share your browser type and version, and if the issue persists after clearing the browser cache with us?

**Comment by lc-kate** [comment]
Hi @anniruddh ,
Thank you for your time. Since you have not responded to us for a while, please tag @lc-christina if the issue is still occurring on your end so we can take a deeper look at this issue. Thank you!
