### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by HackPoint** [LeetCode-Feedback/LeetCode-Feedback#4384]
```
function removeDuplicates(nums: number[]): number {
    const ddupSet = new Set<number>();
    let dupCounter = 0;
    for(let i = 0; i < nums.length; i++) {
       if(!ddupSet.has(nums[i])) {
           ddupSet.add(nums[i]);
       } else {
           dupCounter++;
       }
    }
    nums = Array.from(ddupSet.values());
    return dupCounter;
};
```
```
Input: nums = [1,1,2]
Output: 2, nums = [1,2,_] // here is the mistake

The result is [1,2] and 1
```

**Comment by HackPoint** [comment]
> @HackPoint What is the issue that you are trying to report? It appears that your code is not returning the expected output for the test case [1,1,2]. The expected is [1,2] but your code is returning [1].

Please take a look at my test:
https://www.typescriptlang.org/play?#code/MYewdgzgLgBGCuBbCBGGBeGBtFAaPATALoDcMA9OVgAy614O4FO4DMbuALKQFB8Bm8MMCgBLcDABOAU0QgAbtIAi8AA4AbUcACGUaRAAUCZAC44SAEbTJWIgEozxq5JgBvHjE8xQkWABM-NQBlaVhMMGkAdxgQqAAeJ2sAPgM7Eg8vdVCYQNUAYRAhPRdManSvGH4QSQMs2FEMGDKYBrjzZAA6LLAAcygACzJRAGphuzcMipb+AwBCAODQjv7tQ2MILFF7cfcpvYXVWI7tAKMkDa20yYqAXxhpdQhpCb2p3IKi61HyvZvrv4q60aAEFJJJtABPDr8SQgRAGA5HeTadTwfSpK4VHwQEBZLogHpnZCYrwyKDwSRgHJqD5gYrpG7pHjY2AyCCNGRyRQqDRaXTo9YoK7Y3HSfGEtlXIA

**Comment by lc-kay** [comment]
@HackPoint Unfortunately, we are unable to troubleshoot different behaviors from your local environment and the LeetCode environment. For this issue, I'd recommend checking out the problem discuss section to see if other users have faced a similar issue or raise your issue there. Thank you for your time.
