### ISSUE TITLE
113. Path Sum II - Correct time complexity but incorrect explanation

### ISSUE THREAD

**Issue by PyroGenesis** [LeetCode-Feedback/LeetCode-Feedback#4385]
#### Your LeetCode username
burhanlakda

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The time complexity of the recursive solution is defined as `O(N^2)`. This is correct, however the explanation for it is incorrect.

The article says:
> In the worst case, we could have a complete binary tree and if that is the case, then there would be `N/2` leafs. For every leaf, we perform a potential `O(N)` operation of copying over the pathNodes nodes to a new list to be added to the final pathsList. Hence, the complexity in the worst case could be `O(N^2)`.

However, if we have a complete binary tree, the max depth (and potential operation) would be `log(N)`, resulting in a time complexity of `O(N*log(N))`

The tree we should use here would be an unbalanced binary tree with 1 parent and 1 child on each intermediate level.
This gives us `N/2` leaf nodes and path lengths of 2, 3, ... , `N/2` giving us the proper time complexity of `O(N^2)`
A visual representation of the tree is in this comment: https://leetcode.com/problems/path-sum-ii/solution/712943
and this post: https://leetcode.com/problems/path-sum-ii/discuss/1382332/C%2B%2BPython-DFS-Clean-and-Concise-Time-complexity-explained

#### Code you used for Submit/Run operation

```py
class Solution:
    def pathSum(self, root: TreeNode, targetSum: int) -> List[List[int]]:
        if not root:
            return []
        
        def isLeafNode(node):
            return not node.left and not node.right
        
        allRoutes = []
        route = []
        currentSum = 0
        
        def dfs(node):
            nonlocal isLeafNode, route, allRoutes, currentSum
            
            currentSum += node.val
            route.append(node.val)
            
            if currentSum == targetSum and isLeafNode(node):
                allRoutes.append(list(route))
            
            if node.left: dfs(node.left)
            if node.right: dfs(node.right)
            
            route.pop()
            currentSum -= node.val
        
        dfs(root)
        return allRoutes
```

#### Language used for code
Python

**Comment by lc-kay** [comment]
Hi @PyroGenesis 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
