### ISSUE TITLE
clarify expected return value of 113. Path Sum II

### ISSUE THREAD

**Issue by hamirmahal** [LeetCode-Feedback/LeetCode-Feedback#4386]
#### Your LeetCode username

hamirmahal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

> return all root-to-leaf paths where each path's sum equals targetSum.

doesn't specify whether the paths consist of nodes or their values. Languages like Java will clear up this ambiguity with their method signatures. Languages without method signatures like JavaScript will not have this ambiguity cleared.

#### Code you used for Submit/Run operation

n/a

#### Language used for code

n/a

#### Expected behavior

Just clarify the expected return value of Path Sum II by saying something like
> return all root-to-leaf paths where each path's sum equals targetSum. **Each entry in the path should be the node's value, and not a reference to the node itself!**

#### Screenshots

![Screen Shot 2021-08-04 at 4 39 54 PM](https://user-images.githubusercontent.com/43425812/128269142-13c0cc68-f205-4e20-b71e-7f641f0de50f.png)

**Comment by lc-kay** [comment]
Hi @hamirmahal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hamirmahal 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
