### ISSUE TITLE
Missing Test Case: 79. Word Search

### ISSUE THREAD

**Issue by jackchim1998** [LeetCode-Feedback/LeetCode-Feedback#4390]
#### Your LeetCode username

jackchim1998

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted Solution (0 ms) fails on the following test cases:
solution.exist(new char[][]{
                {'Z', 'Z', 'Z', 'Z', 'Z'},
                {'Z', 'C', 'B', 'A', 'B'},
                {'A', 'D', 'E', 'D', 'C'},
                {'B', 'E', 'Z', 'Z', 'Z'}
        }, "ABEDCBA");

#### Code you used for Submit/Run operation

```
// 79. Word Search
class Solution {
    int m, n;
    char grid[][];
    String input;
    public boolean exist(char[][] board, String word) {
        //1st idea: dfs through the matrix to find the word
        m = board.length;
        n = board[0].length;
        grid = board;
        input = word;
        
        for(int i = 0; i < m; i++){
            for(int j = 0; j < n; j++){
                //we could go backwards so we have to have a new visited array every time.
                if(dfs(i, j, new boolean[m][n], word.length() - 1))
                   return true;
            }
        }
        
        return false;
    }
    
    //the idea was perfect, but the key was to have that if condition at the end.
    public boolean dfs(int i, int j, boolean[][] visited, int index){
        //the word has been found or 'completed'
         if(index < 0 )
            return true;
        
        //all of the stopping conditions.
        if(i < 0 || j < 0 || i >= grid.length || j >= grid[0].length || grid[i][j] != input.charAt(index) || visited[i][j])
            return false;
        
        visited[i][j] = true;
        --index;
        
        //check the surrounding regions.
        return dfs(i, j+1, visited, index) || dfs(i + 1, j, visited, index) || dfs(i, j - 1, visited, index) ||
            dfs(i-1, j, visited, index);
        
        
        // return false;
    }//
}
```

#### Language used for code

JAVA

#### Expected behavior

Output: false
Expected: true

It should return true, and the word "ABEDCBA" exists on the graph.
The solution achieves 0 ms and passes because there are not enough test cases.
The solution should make variable [visited] back to [false] after flooding to the surrounding location.

**Comment by lc-kay** [comment]
Hi @jackchim1998 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jackchim1998 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
