### ISSUE TITLE
Missing Test Case - 877. Stone Game

### ISSUE THREAD

**Issue by saiteja3009** [LeetCode-Feedback/LeetCode-Feedback#4392]
#### Category of the bug - Solution and Missing Test Cases
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation-
'''
class Solution {
public:
    bool stoneGame(vector<int>& piles) {
        return true;
    }
};
'''
The above solution got accepted because clearly there are missing test cases for false case.

And the one which should be actually accepted got wrong answer and the solution for that is given below.
//Stone Game
'''class Solution {
public:
    int dp[100][100];
int solve(vector<int> &a,int i,int j){
    if(dp[i][j]!=-1){
        return dp[i][j];
    }
    if(i==j){
        dp[i][j]=a[i];
    }
    else if(j==i+1){
        dp[i][j]=max(a[i],a[j]);
    }
    else{
        dp[i][j]=max(a[i]+min(solve(a,i+2,j),solve(a,i+1,j-1)),a[j]+min(solve(a,i+1,j-1),solve(a,i,j-2)));
    }
    return dp[i][j];
}

bool sol(vector<int> &a) {
    int n=a.size();

    int s=0;
    for(int i=0;i<n;i++){
        cin>>a[i];
        s+=a[i];
    }
    for(int i=0;i<n;i++){
        for(int j=0;j<n;j++){
            dp[i][j]=-1;
        }
    }
    int k=solve(a,0,n-1);
    if(k>=(s-k)){
        return true;
    }
    else{
        return false;
    }
    /* Enter your code here. Read input from STDIN. Print output to STDOUT */   
    return 0;
}
    
    bool stoneGame(vector<int>& piles) {
        return sol(piles);
    }
};

'''

#### Screenshots

I have added screenshots for both the solutions below.
![Screenshot (1)](https://user-images.githubusercontent.com/54467330/128331549-603ccb4e-6fc5-4de7-913d-f766ce73bf73.png)
![Screenshot (2)](https://user-images.githubusercontent.com/54467330/128331569-717c4e29-c12e-4b24-a5f4-3333c9cae9f9.png)

**Comment by Deep1Shikha** [comment]
Key : Players are playing optimally.

[3,7,2,3]
Alex chose 3(index 3), piles = [3,7,2]
Lee chose 3 (index 0), piles = [7,2]
Alex chose 7 , piles = [2]
Lee chose 2, piles =[]
Alex sum = 10, Lee sum = 5
Hence, Alex won and it should return true.

**Comment by saiteja3009** [comment]
Even my second solution will give true when I tried using custom test case
but when i tried submitting the same solution it was giving wrong answer
for the same test case that's what I mentioned and attached the screenshots
as well.

**Comment by lc-kay** [comment]
Hi @saiteja3009 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
