### ISSUE TITLE
Incorrect Problem Statement - 877. Stone Game

### ISSUE THREAD

**Issue by claytonjwong** [LeetCode-Feedback/LeetCode-Feedback#4394]
Please fix the problem statement; even/odd cardinality of the input array of stones is irrelevant.

❌ "The total number of stones is odd, so there are no ties."

✅ "The accumulated sum of all of the stones values is odd, so there are no ties."

**Comment by hiepxuan2008** [comment]
I think `Total number of stones is odd` is fine, but Leetcode should mention the constraint of `piles.length is even` in the problem statement as well.

**Comment by lc-kay** [comment]
Hi @claytonjwong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by claytonjwong** [comment]
thanks @lc-kay -- can you please provide an ETA for when this investigation is expected to conclude?  in general, i'd like to see more accurate problem statements which are well defined and non-ambiguous.

**Comment by lc-kay** [comment]
Hi @claytonjwong 
Thank you for your time and patience. We've updated the problem. We appreciate your support!
