### ISSUE TITLE
Wrong Test Case - 1955. Count Number of Special Subsequences

### ISSUE THREAD

**Issue by aman-agrawal** [LeetCode-Feedback/LeetCode-Feedback#4396]
#### Your LeetCode username
9412470 (Aman Agrawal)

#### Category of the bug
- [*] Wrong solution for Test Case 

#### Description of the bug
Example 3:
Input: nums = [0,1,2,0,1,2]
Output: 7
Explanation: The special subsequences are:
- [0,1,2,0,1,2]
- [0,1,2,0,1,2]
- [0,1,2,0,1,2]
- [0,1,2,0,1,2]
- [0,1,2,0,1,2]
- [0,1,2,0,1,2]
- [0,1,2,0,1,2]

answer should be 9

012012012
abcabc
012345

where is the case when we left (ca) at indices (2,3) and go with indices (0,1,4,5) and (0,1,5) and (0,4,5)

**Comment by lc-kay** [comment]
Hi @aman-agrawal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@aman-agrawal The test case and example are correct. We bolded some information that can be important.
Please don't convert the array to string to better understand. Thank you for your time.
