### ISSUE TITLE
1778. 未知网格中的最短路径

### ISSUE THREAD

**Issue by woasishen** [LeetCode-Feedback/LeetCode-Feedback#4397]
**fighter**

**Bug 类型**
- [ 1778. 未知网格中的最短路径] 
- [c# ] 

**描述**
默认c#模板函数返回类型是void
这题需要返回int,其他语言也是返回int

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/22291967/128380567-7f9e2cc4-7aed-4362-b40e-0da2c1f091fb.png)

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by feiceh** [comment]
@woasishen 你好，当前题目问题已修复，ID：fighter 给予积分奖励，请查收。
