### ISSUE TITLE
1168. Optimize Water Distribution in a Village Description incorrect.

### ISSUE THREAD

**Issue by Flamingo09** [LeetCode-Feedback/LeetCode-Feedback#4398]
#### Your LeetCode username
Flamingo09

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question doesn't say that all houses need to be connected to one other. They just need a water supply. There can be a case where each house can have its own well and stay unconnected to others. In that case, MST algorithm won't work.

**Comment by lc-kay** [comment]
Hi @Flamingo09 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Flamingo09 Our team has reviewed your report and the problem description and concluded that it is fine as it is. It is not required that the houses need to be connected to each other, only that each house must be supplied with water. If you have a solution that passes but fails on a custom test case, please let us know and we will further look into it. Thank you for your time.
