### ISSUE TITLE
Question: 746. Min Cost Climbing Stairs, wrong testcase

### ISSUE THREAD

**Issue by priyagupta20** [LeetCode-Feedback/LeetCode-Feedback#440]
#### Your LeetCode username
priyagupta20

#### Category of the bug
TestCase

#### Description of the bug
In the question https://leetcode.com/problems/min-cost-climbing-stairs/, the expected answer for the testcase: "[0,0,1,1]" is 1, due to which my code is not clearing it. It should be 0. Simce we can start from index 0 or 1, to get min-cost, we'll start with index 1(cost=0) and jump 2 steps and reach the top. So the answer should be 0.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minCostClimbingStairs(vector<int>& cost) {
        int n=cost.size();
        vector<int> dp(n);
        dp[0]=cost[0];
        dp[1] = cost[1]+cost[0];
        for(int i=2;i<n;i++){
            dp[i] = cost[i] + min(dp[i-1],dp[i-2]);
        }
     
        return dp[n-1]-cost[n-1];
    }
};
```

#### Language used for code
C++ 

<img width="396" alt="Screenshot 2020-06-09 at 2 57 31 PM" src="https://user-images.githubusercontent.com/29272569/84130970-906f8a00-aa61-11ea-876b-63aadff05465.png">

**Comment by anshulverma1** [comment]
The test case is correct, though the problem statement could be improved.
https://leetcode.com/problems/min-cost-climbing-stairs/discuss/148907/Doubt/414813

**Comment by CooperCooperCooper** [comment]
Hi @priyagupta20 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @priyagupta20 ,
Thank you for your time. Upon reviewing your contribution, we found you've misunderstood the problem. Please review the problem carefully. We appreciate your support.
