### ISSUE TITLE
Missing Test Case - 1166. Design File System

### ISSUE THREAD

**Issue by Usha-Kuchibhotla** [LeetCode-Feedback/LeetCode-Feedback#4400]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The question does not check for the following test case:
["FileSystem","createPath","get"]
[[],["/v/", 2], ["/v/"]]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Usha-Kuchibhotla Please provide the code that this test case will fail. Thank you.

**Comment by lc-kay** [comment]
Hi @Usha-Kuchibhotla 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
