### ISSUE TITLE
Wrong text on solution tab for #232

### ISSUE THREAD

**Issue by akmetainfo** [LeetCode-Feedback/LeetCode-Feedback#4401]
#### Your LeetCode username

akmetainfo

#### Category of the bug

- [ ] Solution

I'm not sure that this category valid, but there's no category for posting issues about such problem.

#### Description of the bug

[Solution page](https://leetcode.com/problems/implement-queue-using-stacks/solution/) containt text for approach1:

```
public void pop() {
    s1.pop();
    if (!s1.empty())
        front = s1.peek();
}
```
Should be:
```
public int pop() {
    var result = s1.pop();
    if (!s1.empty())
        front = s1.peek();
    return result;
}
```

And also for approach2

Original:

```
public void pop() {
    if (s2.isEmpty()) {
        while (!s1.isEmpty())
            s2.push(s1.pop());
    }
    s2.pop();    
}
```

Should be replaced by:

```
public void pop() {
    if (s2.isEmpty()) {
        while (!s1.isEmpty())
            s2.push(s1.pop());
    }
    return s2.pop();
}
```

#### Code you used for Submit/Run operation

n/a

#### Language used for code

n/a

#### Expected behavior

n/a

#### Screenshots

n/a

#### Additional context

n/a

**Comment by lc-kay** [comment]
Hi @akmetainfo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
