### ISSUE TITLE
Missing Test Case in 394. Decode String

### ISSUE THREAD

**Issue by rachit98** [LeetCode-Feedback/LeetCode-Feedback#4406]
#### Your LeetCode username
south_paw

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

Missing Test Case
#### Description of the bug

The following Test Case is not checked but the submission is accepted.
Input: "3[4]"
Output: "444"

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string decodeString(string s) {
        stack<string> st;
        for(int i=0;i<s.length();i++)
        {
            string balls ="";
            balls+=s[i];
            if(s[i]!=']')
                st.push(balls);
            else
            {
                string temp = "";
                while(st.top()!="[")
                {
                    temp = st.top() + temp;
                    st.pop();
                }
                st.pop();
                string num = "";
                while(!st.empty() and st.top()<="9" and st.top()>="0")
                {
                    num = st.top() + num;
                    st.pop();
                }
                int val = stoi(num);
                string to_push="";
                for(int i=0;i<val;i++)
                {
                    to_push+= temp;
                }
                st.push(to_push);
            }
            
        }
        string ans="";
        while(!st.empty())
        {
            ans = st.top() + ans;
            st.pop();
        }
        return ans;
    }
};
```

#### Expected behavior

According to problem statement, for the Input "3[4]" the output should be "444", this code outputs "" (Empty String) but the solution is accepted with 0ms runtime.

**Comment by lc-kay** [comment]
Hi @rachit98 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rachit98 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
