### ISSUE TITLE
A new solution in C++ - 27. Remove Element

### ISSUE THREAD

**Issue by Dhiraj3118** [LeetCode-Feedback/LeetCode-Feedback#4407]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int removeElement(vector<int>& nums, int val) {
        
        if(nums.size() == 0) return 0;
        
        for(int i = 0 ; i < nums.size() ; i++)
        {
            if(nums[i] == val)
            {
                nums.erase(nums.begin() + i);
                i--;
            }
        }
        
        return nums.size();
        
    }
};
```

#### Screenshots
![Screenshot (49)](https://user-images.githubusercontent.com/61940283/128456579-92374a29-5fa4-4488-b292-1dd6ad121d09.png)

**Comment by lc-kay** [comment]
@Dhiraj3118 We welcome you to post your solution to the problem discuss page! In addition, I've relayed this to our team to investigate to improve our official solution as needed. Thank you for your time.
