### ISSUE TITLE
392. Is Subsequence, need additional testcases to catch incorrect submission

### ISSUE THREAD

**Issue by iamgenechua** [LeetCode-Feedback/LeetCode-Feedback#441]
#### Your LeetCode username

genecode

#### Category of the bug
- [ X] Solution

#### Description of the bug

My code was accepted in the submission despite failing the Run operation

#### Code you used for Submit/Run operation

```
// Is Subsequence
class Solution {
    public boolean isSubsequence(String s, String t) {
        if (s.equals("")) {
            return true;
        }
        
        if (s.length() == t.length()) {
            return s.charAt(0) == t.charAt(0);
        }
        
        int sStart = 0;
        int sEnd = s.length() - 1;
        
        int tStart = 0;
        int tEnd = t.length() - 1;
        int count = 0;
        
        while (sStart <= sEnd && tStart <= tEnd) {
            if (s.charAt(sStart) == t.charAt(tStart)) {
                count++;
                sStart++;
                
                if (count == s.length()) {
                    return true;
                }
            }
            tStart++;
        }
        
        return false;
    }
}
```

#### Expected behavior

A simple input like:
"abc"
"acb"

When i click run, the output is false, as expected. My code returned true.

Yet my code was accepted in the submission.
I suggest adding more testcases with String s and String t being of the same length, where s is not a subsequence of t.

**Comment by CooperCooperCooper** [comment]
Hi @iamgenechua ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @iamgenechua ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by iamgenechua** [comment]
Hi @CooperCooperCooper ,

Thank you for acknowledging my feedback. Just wondering if you guys can also acknowledge this by increasing the "testcases contributed" on my profile? Because right now my profile still reflects the number of testcases contributed as 0.
![Screenshot 2020-06-11 at 6 01 45 PM](https://user-images.githubusercontent.com/54027136/84372394-a0c46800-ac0d-11ea-90b8-0715ed46d259.png)

**Comment by CooperCooperCooper** [comment]
Hi @iamgenechua ,
Good question! Due to our current technical setup, only test cases that were accepted via the contribution platform is recognized under the "Contribution" section on the profile page. However, I've filed this suggestion to our team to consider for future roadmap. Thanks again for your support.
