### ISSUE TITLE
Missing Test Case - 877. Stone Game

### ISSUE THREAD

**Issue by Hunter123XYZ** [LeetCode-Feedback/LeetCode-Feedback#4410]
#### Your LeetCode username
chethas1

#### Category of the bug
- [ ] Missing Test Cases 
The missing test case is **[1, 3, 9, 2]**

#### Description of the bug
If I use this test case and run my code, I will get the wrong answer. However, my code was accepted by LeetCode for this problem. (More details below)

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean stoneGame(int[] piles) {
        int alex = 0;
        int lee = 0;
        boolean done = false;
        boolean alexTurn = true;
        
        ArrayList<Integer> pilz = new ArrayList<Integer>();
        for (int i : piles){
            pilz.add(i);
        }
        
        int size = pilz.size();
        
        while (pilz.size() > 0){
            int x = pilz.get(0);
            
            if (pilz.size() == 1){
                if (alexTurn = true) alex += x;
                else lee += x;
            }
            
            int y = pilz.get(pilz.size() - 1);
            
            if (alexTurn = true){
                if (x > y) {
                    pilz.remove(0);
                    alex += x;
                }
                else {
                    pilz.remove(pilz.size() - 1);
                    alex += x;
                }
                alexTurn = false;
            }
            
            else {
                if (x > y) {
                    pilz.remove(0);
                    lee += x;
                }
                else {
                    pilz.remove(pilz.size() - 1);
                    lee += x;
                }
                alexTurn = true;
            }    
        }
        
        if (alex > lee) return true;
        else return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior

As you can see in code above, **my algorithm is looking for whether the last pile or the first pile is larger and selecting it.** For the case of [1, 3, 9, 2], **if Alex selects the 2 instead of the 1 because it is larger, she lets Lee take the 9 and that will cost her the game.** If Alex takes the 1 instead even though it is smaller, Lee is then forced to take either the 3 or 2, and Alex will then take the 9 and win the game. Therefore, the picking the larger pile among the first and last one isn't right for all scenarios.

**Comment by PriyanshBordia** [comment]
The answer to the question is True always. I think that is the reason it's accepted.

**Comment by lc-kay** [comment]
@PriyanshBordia Per the problem statement, "Assuming Alex and Lee play optimally", therefore, Alex will take 1, then take 9, and win the game. Thank you for your time.

**Comment by PriyanshBordia** [comment]
That's true, but I am trying to say that  Alex > Lee is always True.

**Comment by Hunter123XYZ** [comment]
Ok thanks
