### ISSUE TITLE
Incorrect method name for 429. N-ary Tree Level Order Traversal in Ruby

### ISSUE THREAD

**Issue by albertbko** [LeetCode-Feedback/LeetCode-Feedback#4411]
#### Your LeetCode username

bycko

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The default code for the solution defines the method as `level_order` but the solution.rb file runs `levelOrder`.
Without realizing this and manually changing the default method name to `levelOrder`, the user will continuously run into a runtime error for undefined method 'levelOrder'.

#### Code you used for Submit/Run operation

```
def level_order(root)
    
end
```

#### Language used for code

Ruby

#### Expected behavior

The default template provided by LeetCode should run without modification.

#### Screenshots

![image](https://user-images.githubusercontent.com/34317030/128511694-1cf73d6b-cc2e-4089-9520-65641a23e661.png)

**Comment by lc-kay** [comment]
Hi @albertbko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @albertbko 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
