### ISSUE TITLE
3. 无重复字符的最长子串 运行结果不一致

### ISSUE THREAD

**Issue by kiracookie** [LeetCode-Feedback/LeetCode-Feedback#4412]
**leetcodenb@163.com**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [X] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
运行结果不一致

**你使用的语言**
java

**你提交或者运行的代码**
3. 无重复字符的最长子串
class Solution {
    public int lengthOfLongestSubstring(String s) {
        int max = 0;
        String maxStr="";
        for (int i = 0; i < s.length(); i++) {
            char current = s.charAt(i);
            int len = s.indexOf(current, i+1)-i;
            if (len > max) {
                max = len;
                maxStr = s.substring(i, len);
            }
        }
        return max;
    }
}

**期望行为**
描述你期望的结果

**屏幕截图**
![94FD86CE-EBFB-4812-BD99-6A76AF126B86](https://user-images.githubusercontent.com/9149943/128533373-358f9043-503e-481f-82e9-be9fa3ce6283.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
