### ISSUE TITLE
Fonts and Circles in the images in the description seem too out-of-proportion  - 61. Rotate List

### ISSUE THREAD

**Issue by kuannoodle1** [LeetCode-Feedback/LeetCode-Feedback#4413]
#### Your LeetCode username

kuannoodle

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In general, the images in LeetCode problems are fit aesthetically.  But the images in [Problem 61, Rotate List](https://leetcode.com/problems/rotate-list/) seems to be way out of proportion.  In addition, the size of fonts are inconsistent between the images used in example 1 and 2.

#### Expected behavior

The size of the image in the problem description of https://leetcode.com/problems/number-of-sets-of-k-non-overlapping-line-segments/ looks perfect.

#### Screenshots

Below is an screenshot of viewing the problem on two browsers:
![Chrome and FF](https://imgur.com/tUe1ChL.png)

**Comment by lc-kay** [comment]
Hi @kuannoodle1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kuannoodle1 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
