### ISSUE TITLE
Missing Description | Kth largest in a Stream.

### ISSUE THREAD

**Issue by sreeram315** [LeetCode-Feedback/LeetCode-Feedback#4414]
https://leetcode.com/problems/kth-largest-element-in-a-stream/

For function description of `int add(int)`
Please also write that the function needs to insert the element into the data structure before returning the Kth largest element. Although it is implicit from the name, it is nowhere written in the problem statement that the function needs to add the passed element. It only says to return Kth maximum element.

**Comment by lc-kay** [comment]
Hi @sreeram315 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sreeram315 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by sreeram315** [comment]
Thank you. 
My Leetcode ID: sreeram315

**Comment by sreeram315** [comment]
> Hi @sreeram315
> Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

Thank you.
My Leetcode ID: sreeram315
