### ISSUE TITLE
Missing Test Case - 90. Subsets II

### ISSUE THREAD

**Issue by kumarp149** [LeetCode-Feedback/LeetCode-Feedback#4416]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
I wrote the following code for question number 90 (Subsets II). Although the code is logically wrong, leetcode accepted it as a correct solution

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> Recur(vector<int> &nums,int last){
    if (last==0){
        return {{},{nums[last]}};
    }
    set<vector<int>> ans;
    vector<vector<int>> temp = Recur(nums,last-1);
    for (int i=0;i<temp.size();++i){
        sort(temp[i].begin(),temp[i].end());
        ans.insert(temp[i]);
        temp[i].push_back(nums[last]);
        ans.insert(temp[i]);
    }
    return vector<vector<int>> (ans.begin(),ans.end());
}

vector<vector<int>> subsetsWithDup(vector<int>& nums){
    return Recur(nums,nums.size()-1);
}
};
```

#### Language used for code

C++

#### Expected behavior

Input = [1,2,1]
Code Output = [[],[1],[1,1],[1,2],[1,2,1],[2],[2,1]]
Expected Output = [[],[1],[1,1],[1,1,2],[1,2],[2]]

**Comment by lc-kay** [comment]
Hi @kumarp149 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kumarp149 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
