### ISSUE TITLE
231. Power of Two Testcase giving wrong output

### ISSUE THREAD

**Issue by MayankMaheshwar** [LeetCode-Feedback/LeetCode-Feedback#4417]
```
`class Solution:
    def isPowerOfTwo(self, n: int) -> bool:
        if n<=0:
            return False
        if n==1:
            return True
        ch=math.log(n,2)
        if int(ch)==0:
            return False
        print(ch)
        print(2**29)
        return not int(ch)%ch
        `
```

this is my code that is failing for this test case 
536870912

even though the number is the power of 2 i.e. 29^2.

**Comment by lc-kay** [comment]
@MayankMaheshwar The expected output for this test case is true, but your code is outputting false. Therefore, it is not accepted. Thank you for your time.
