### ISSUE TITLE
Panic in test executer? - 133. Clone Graph

### ISSUE THREAD

**Issue by bsilverman** [LeetCode-Feedback/LeetCode-Feedback#4419]
#### Your LeetCode username
bsilverman

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I may be misunderstanding the test case when `Last executed input: [[]]`, but submitting my solution
panics somewhere outside of my code (I think) and when I run the code with the presumed test case
on my machine, it completes without issue. I can't seem to figure out how the solution would cause a panic.

```
Runtime Error Message:

panic: runtime error: index out of range [1] with length 1
main.(*GraphSerializer).dfsValues(0xc000058e26, 0xc00003c0e0, 0xc000058b68, 0xc000014188, 0x1, 0x1, 0x1, 0x449d2c)
solution.go, line 123
main.(*GraphSerializer).dfsValues(0xc000058e26, 0xc00003c0c0, 0xc000058b68, 0xc000014188, 0x1, 0x1, 0x1, 0x1)
solution.go, line 127
main.(*GraphSerializer).serialize(0xc000058e26, 0xc00003c160, 0xc00003c0c0, 0x0, 0x0)
solution.go, line 176
main.main()
solution.go, line 228
```

#### Code you used for Submit/Run operation

```
var (
    cloned map[int]*Node = make(map[int]*Node)
)

func cloneGraph(node *Node) *Node {
    if node == nil {
        return nil
    }
    clone := cloned[node.Val]
    if clone == nil {
        clone = &Node{Val: node.Val}
        cloned[node.Val] = clone
        for _, neighbor := range node.Neighbors {
            clone.Neighbors = append(clone.Neighbors, cloneGraph(neighbor))
        }
    }
    return clone
}
```

#### Language used for code
Go

#### Expected behavior
No panic

#### Additional context
Test case I used to attempt to simulate panic:
```
import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestOneNodeNoNeighbors(t *testing.T) {
	node := &Node{Val: 1}
	var clone *Node
	require.NotPanics(t, func() { clone = cloneGraph(node) })
	require.NotSame(t, node, clone)
	require.Equal(t, node.Val, clone.Val)
	require.NotEmpty(t, clone.Neighbors)
}
```

**Comment by sreeram315** [comment]
looks like a problem building the original graph from the test case input from Leetcode's side.

**Comment by lc-kay** [comment]
Hi @bsilverman 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @bsilverman 
Thank you for your time. We've fixed the bug in the driver. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
