### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by sean9527** [LeetCode-Feedback/LeetCode-Feedback#4422]
#### Your LeetCode username

kmlglsy

#### Category of the bug
- [ ] Question
- [ * ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The output of the code in the test and the submission with the same input  are different. In the test, the output is correct, but in the submission, the output is incorrect. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int myAtoi(string s) {
        if(s.empty()){
            return 0;
        }
        stringstream ss(s);
        long long i_num;
        ss >> i_num;
        
        if(i_num > INT_MAX){
            return INT_MAX;
        }else if(i_num < INT_MIN){
            return INT_MIN;
        }else{
            return (int)i_num;
        }
    }
};
```

#### Expected behavior

When  the input is "  " (two white spaces inside the quotes), the output in the test is 0, but the output in the submission is 11.

**Comment by lc-kay** [comment]
Hi @
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
