### ISSUE TITLE
Invalid Test Case - 224. Basic Calculator

### ISSUE THREAD

**Issue by ureridu** [LeetCode-Feedback/LeetCode-Feedback#4424]
#### Your LeetCode username

ureridu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1 ] Missing Test Cases 

#### Description of the bug

Using test case **"4--(4)"**
Results in error:

> **Invalid Testcase**
> Invalid expression

#### Expected behavior

The constraints state:
> '-' could be used as a unary operation but it has to be followed by parentheses.

In the expression "4--(4) there are 2 "-" signs.  I would expect that the second "-" would be the unary operator, and as it is followed by parenthesis, would be considered legal.  

The first "-" would also then be legal as it would be a binary operator acting on 4 and -4.
However the code seems to interpret the first "-" and the unary operator and views the testcase as invalid

**Comment by lc-kay** [comment]
Hi @ureridu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@ureridu Our team has reviewed your report and found that this is indeed an invalid test case. We have updated the constraints to be more clear about it. "4-(-4)" should be the right way to test this input. Thank you for your time.
