### ISSUE TITLE
1963. Minimum Number of Swaps to Make the String Balanced

### ISSUE THREAD

**Issue by sahil06singh** [LeetCode-Feedback/LeetCode-Feedback#4425]
------Please upvote! if you like the solution and explanation. Please put your doubts/queries in the comments section below. I will try my best to answer them.------
**INTUTION**  :- push opening brackets into the stack , whenever closing bracket occurs pop the opening bracket from top if there is any , In this way all the balanced strings are removed and we are left with unbalanced string.
Then start swaping pair of open and close brackets .

class Solution {
public:
    int minSwaps(string s) {
        
        
        int curr = 0 , open = 0 ,swaps = 0 ;
        
    
        stack<char> st ;
        
        for(auto x : s)
        {
            if(x=='[')
                st.push(x);
            else
            {
                if(!st.empty())
                    st.pop();
                
            }
        }
        
        return (st.size()+1)/2;
        
    }
};

**Comment by sahil06singh** [comment]
class Solution {
public:
    int minSwaps(string s) {
        
        
        int curr = 0 , open = 0 ,swaps = 0 ;
        
    
        stack<char> st ;
        
        for(auto x : s)
        {
            if(x=='[')
                st.push(x);
            else
            {
                if(!st.empty())
                    st.pop();
                
            }
        }
        
        return (st.size()+1)/2;
        
    }
};

**Comment by lc-kay** [comment]
@sahil06singh We welcome our users to post their solutions in the problem discuss section. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
