### ISSUE TITLE
122. Best time to Buy and Sell Stock II

### ISSUE THREAD

**Issue by RavjotSandhu** [LeetCode-Feedback/LeetCode-Feedback#4427]
#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

We need to write that we have to sell immediately whenever we see a peak or high.
Other wise we have numerous cases to consider because of different possible transaction types.
A simple problem complicated by not including full description

#### Screenshots

![image](https://user-images.githubusercontent.com/58950644/128631566-5e7c13ab-c4f5-4dfe-a69f-19dd5519601d.png)

#### Additional context

Here my initial thinking process was to consider all types of transactions possible. Say, buy at 1 sell at 5, buy at 3 sell at 4, buy at 5 sell at 6, buy at 3 sell at  6 and so on....
then store these transactions using custom data type in a map and then check the which ones combined would give max benefit combined or alone 

But when I saw the solution, nothing like this is considered. Its just selling immediately after buying.

It's only in above test case that selling on a later day leads to less profit when added to overall profit (selling at 4 rather than 6 after buying at 3). There are test cases possible where this situation is not present. Ex 7,1,3,3,6,5,4 here buying at 1 selling 6 is same as buying at 1 selling at 3, buying at 3 selling at 6 ( 5 = 2+3). 

So please change description and add that we have to sell immediately

**Comment by lc-kay** [comment]
Hi @RavjotSandhu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @RavjotSandhu 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
