### ISSUE TITLE
880 Decoded String at Index

### ISSUE THREAD

**Issue by Aman56** [LeetCode-Feedback/LeetCode-Feedback#4428]
#### Category of the bug
- [ *] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
```

**Comment by lc-kay** [comment]
@Aman56 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
