### ISSUE TITLE
Missing Test Case - 1331. Rank Transform of an Array

### ISSUE THREAD

**Issue by simplysumanr** [LeetCode-Feedback/LeetCode-Feedback#4430]
#### Your LeetCode username
suman_gupta

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Below code passes all tests cases and in fact  with lowest cpu & mem usage compared to other submissions but with the new test case, we hit out of memory.

#### Code you used for Submit/Run operation

```
// Rank Transform of an Array
class Solution {
    public int[] arrayRankTransform(int[] arr) {
        
        int max = Integer.MIN_VALUE;
        int min = Integer.MAX_VALUE;
        for (int i = 0; i < arr.length; i++) {
            max = Math.max(max, arr[i]);
            min = Math.min(min, arr[i]);
        }
        
        int[] ranks = new int[max-min+1];
        for (int i = 0; i < arr.length; i++) {
            ranks[arr[i] - min] = 1;
        }
        int count = 0;
        for (int i = 0; i < ranks.length; i++) {
            count += ranks[i];
            ranks[i] = count;
        }

        for (int i = 0; i < arr.length; i++) {
            arr[i] = ranks[arr[i]-min];
        }
        return arr;
    }
}
```

#### Language used for code
Java

#### Expected behavior

"[-1000000000,10,20,30, 1000000000]" is a valid test case and the above will not pass this test case. Please include the same.

**Comment by lc-kay** [comment]
Hi @simplysumanr 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @simplysumanr 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
