### ISSUE TITLE
Implement Active Users globalranking

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4431]
Request for feature

The leetcode contests have become stronger/ difficult this last year

https://leetcode.com/contest/globalranking
should show
the "current state of competitiveness"

but "neal_wu" dint participate in recent time, like last 1+ years, but is still # 1 at  https://leetcode.com/contest/globalranking https://leetcode.com/neal_wu/

as we can see
it is not the "current state of competitiveness"

other websites are doing different
they show
"Active Users" and
"All Users" tabs

For example, see
https://atcoder.jp/ranking

Please implement below "2 ranking tabs":
- "Active Users" - the new "globalranking" list - shows only those who attended in the last 1 year
this must be the default selected option
- "All Users" - the current "globalranking" list - shows what is shown now

**Comment by lc-kay** [comment]
@manoharreddyporeddy Our team has already noted this feature request down from your support ticket. We are looking into improving and adding essential elements to our contest to provide the best user experience. Thank you for your time.
