### ISSUE TITLE
Missing Test Case - 313. Super Ugly Number

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#4436]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets Runtime Error on the following testcase:
67
[2,1021]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int nthSuperUglyNumber(int n, const vector<int>& primes) {
        if(n == 1) return 1;
        int sz = primes.size();
        int ind[sz], val[sz];
        memset(ind, 0, sizeof ind);
        fill_n(val, sizeof val/sizeof *val, 1);
        
        int uglies[n];
        int nextugly = 1;
        for(int i = 0; i < n; i++) {
            uglies[i] = nextugly;
            nextugly = INT_MAX;
            for(int j = 0; j < sz; j++) {
                if(val[j] == uglies[i]) val[j] = primes[j] * uglies[ind[j]++];
                //assert(val[j]>0);
                if(nextugly > val[j]) nextugly = val[j];
            }
        }
        
        return uglies[n-1];
    }
};
```

#### Language used for code

The code gets Runtime Error.

**Comment by hqztrue** [comment]
Please use the testcase
67
[2,997]
instead. The previous testcase is invalid (1021 exceeds 1000), but the input checker weren't able to detect this.

**Comment by lc-kay** [comment]
Hi @hqztrue 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
