### ISSUE TITLE
improve Add Strings

### ISSUE THREAD

**Issue by hamirmahal** [LeetCode-Feedback/LeetCode-Feedback#4437]
#### Your LeetCode username

hamirmahal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

1. There's a typo.
2. The problem statement has ambiguity.

#### Code you used for Submit/Run operation

n/a

#### Language used for code

n/a

#### Expected behavior

1. Change
> num1 and num2 don't have any leading zeros except for the zero itself.

to
>num1 and num2 don't have any leading zeros except for the **number** zero itself.

2. Clarify what sort of tools LeetCode encourages for this question. For instance. is `charCodeAt()` okay?

The phrase
>You must also not convert the inputs to integers directly.

has ambiguity; technically, `charCodeAt()` "directly" converts part of the input to a string. What methods does LeetCode encourage?

**Comment by lc-kay** [comment]
Hi @hamirmahal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hamirmahal After reviewing the problem and user feedback, we have decided that we will not change the problem as it is currently up to standards. Thank you for your time,
