### ISSUE TITLE
100000000110000001Missing Test Case - 926. Flip String to Monotone Increasing

### ISSUE THREAD

**Issue by sachinraghult** [LeetCode-Feedback/LeetCode-Feedback#4441]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@sachinraghult Please provide more details on your missing test case report, such as the accepted code that will get failed by the test case. After more information is provided, I will reopen this ticket. Thank you for your time.
