### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by suhelkhankhan** [LeetCode-Feedback/LeetCode-Feedback#4442]
#### Your LeetCode username
Suhel6040

#### Category of the bug
- [ Two Sum] Question
- [ Done ] Solution
- [ Java ] Language
- [ 0 ] Missing Test Cases 

#### Description of the bug
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

 

Example 1:

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Output: Because nums[0] + nums[1] == 9, we return [0, 1].
Example 2:

Input: nums = [3,2,4], target = 6
Output: [1,2]
Example 3:

Input: nums = [3,3], target = 6
Output: [0,1]
 

Constraints:

2 <= nums.length <= 104
-109 <= nums[i] <= 109
-109 <= target <= 109
Only one valid answer exists

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int[] twoSum(int[] nums, int target) {
        int arr[]=new int[2];
        int res=0;
        for(int i=0;i<nums.length-1;i++)
        {
            for(int j=i+1;j<nums.length;j++)
            {
              res=nums[i]+nums[j];
                
                if(res==target)
                {
                    arr[0]=i;
                    arr[1]=j;
                    break;
                }
                
            }
        }
        return arr;
        
        
    }
}
```

#### Language used for code
Java

**Comment by azhar1038** [comment]
What are you trying to say? I don't think any test case is missing.

**Comment by lc-kay** [comment]
@suhelkhankhan This is an invalid test case - expected 'nums' to have 2 <= size <= 10000 but got 1. Thank you for your time.
