### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by sachin7796** [LeetCode-Feedback/LeetCode-Feedback#4443]
#### Your LeetCode username
user9631Q

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In this question, as per the description of the problem, a number where a exponent immediately follows a decimal should not pass, for eg something like 6.e10 makes no sense and it should not pass. We need to add test cases to make sure it does not pass and also update the editorial solution

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isNumber(String s) {
        boolean isLastCharDigit = false;
        boolean isLastCharExponent = false;
        boolean isLastCharDot = false;
        
        for(int i=0;i<s.length();i++){
            char currChar = s.charAt(i);
            if(Character.isDigit(currChar)){
                isLastCharDigit = true;
            }else if(currChar == '+' || currChar == '-'){
                if(i>0 && s.charAt(i-1) != 'e' && s.charAt(i-1)!='E')
                    return false;
            }else if(currChar == 'e' || currChar == 'E'){
                if(isLastCharExponent || !isLastCharDigit || isLastCharDot)
                    return false;
                isLastCharExponent = true;
                isLastCharDigit = false;
                isLastCharDot = false;
            }else if(currChar == '.'){
                if(isLastCharDot || isLastCharExponent)
                    return false;
                isLastCharDot = true;
            }else{
                return false;
            }
            
        }
        
        return isLastCharDigit;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The online judge should return false for 6.e10 but it returns true currently

**Comment by lc-kay** [comment]
@sachin7796 Please provide the exact missing test case in .txt format. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @sachin7796 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
