### ISSUE TITLE
Missing Test Case - 1488. Avoid Flood in The City

### ISSUE THREAD

**Issue by rohanailoni** [LeetCode-Feedback/LeetCode-Feedback#4447]
#### Your LeetCode username

aileni_rohan

#### Category of the bug
- [ ] Question
- [✓] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

given test case 78:-[1,0,2,0,3,0,2,0,0,0,1,2,3]
expected output:-[-1,1,-1,2,-1,3,-1,2,1,1,-1,-1,-1]
my output:-[-1,1,-1,2,-1,3,-1,1,1,1,-1,-1,-1]
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int[] avoidFlood(int[] rains) {
            HashMap<Integer,Integer> map=new HashMap<>();
            TreeMap<Integer,Integer> tree=new TreeMap<>();
            int[] ans=new int[rains.length];
        for(int i=0;i<rains.length;i++){
            if(rains[i]==0){
                ans[i]=1;
              tree.put(i,0);
            }else{
                if(map.containsKey(rains[i])){
                  Integer x= tree.ceilingKey(map.get(rains[i]));
                    if(x==null)return new int[]{};
                    else{
                        map.remove(rains[i]);
                       ans[x]=rains[i];
                        tree.remove(x);
                    }
                }
                else{
                    map.put(rains[i],i);
                }
            }
        }
        
        
        for(int i=0;i<ans.length;i++){
            if(rains[i]>0)ans[i]=-1;
        }
      
         return  ans;
    }
}
```

#### Expected behavior

the occurance of 2 is at first so second zero the 2nd lake is empted  and similar way lake are filled for 2 and 3 but given in the expected output it is clearly shown that (at index 8) 2 is emptied even without filling the lake

**Comment by lc-kay** [comment]
@rohanailoni The expected output is correct. I'd recommend checking out the discuss section for further clarification> Many users found this discuss post to be helpful https://leetcode.com/problems/avoid-flood-in-the-city/discuss/697687/A-Set-and-A-Map-Lucid-code-with-documented-comments Thank you for your time.
