### ISSUE TITLE
Wrong Test Case - 622. Design Circular Queue

### ISSUE THREAD

**Issue by aashnasingh** [LeetCode-Feedback/LeetCode-Feedback#4448]
#### Your LeetCode username
aashna_singh04

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For the test case -
["MyCircularQueue","enQueue","Rear","Rear","deQueue","enQueue","Rear","deQueue","Front","deQueue","deQueue","deQueue"]
[[6],[6],[],[],[],[5],[],[],[],[],[],[]]
- We enqueue 6, but dequeue it, then enqueue 5, again dequeue it hence the queue is empty right now, so the next operation "Front" should return -1, but while running this testcase, it says wrong answer and expects 5 as the output which is wrong.

#### Code you used for Submit/Run operation

```
class MyCircularQueue {
    
    Node tail;
    int size;
    int capacity;
    public MyCircularQueue(int k) {
        size = 0;
        capacity = k;
    }
    
    public boolean enQueue(int value) {
        Node newNode = new Node(value);
        if (tail == null) {
            tail = newNode;
            tail.next = tail;
            size++;
            return true;
        }
        if (size == capacity) {
            return false;
        }                
        newNode.next = tail.next;
        tail.next = newNode;
        tail = newNode;
        size++;
        return true;
    }
    
    public boolean deQueue() {
        if (tail != null) {
            tail.next = tail.next.next;
            size--;
            return true;
        }
        return false;
    }
    
    public int Front() {
        if (tail != null) {
            return tail.next.data;
        }
        return -1;
    }
    
    public int Rear() {
        if (tail != null) {
            return tail.data;
        }
        return -1;
    }
    
    public boolean isEmpty() {
        if (tail == null) {
            return true;
        }
        return false;
    }
    
    public boolean isFull() {
        if (size == capacity) {
            return true;
        }
        return false;
    }
    
    class Node {
        int data;
        Node next;
        Node() {}
        public Node(int data) {
            this.data = data;
        }
    }
}

/**
 * Your MyCircularQueue object will be instantiated and called as such:
 * MyCircularQueue obj = new MyCircularQueue(k);
 * boolean param_1 = obj.enQueue(value);
 * boolean param_2 = obj.deQueue();
 * int param_3 = obj.Front();
 * int param_4 = obj.Rear();
 * boolean param_5 = obj.isEmpty();
 * boolean param_6 = obj.isFull();
 */
```

#### Language used for code
JAVA 

#### Expected behavior
 For the test case -
["MyCircularQueue","enQueue","Rear","Rear","deQueue","enQueue","Rear","deQueue","Front","deQueue","deQueue","deQueue"]
[[6],[6],[],[],[],[5],[],[],[],[],[],[]]
- We enqueue 6, but dequeue it, then enqueue 5, again dequeue it hence the queue is empty right now, so the next operation "Front" should return -1, but while running this testcase, it says wrong answer and expects 5 as the output which is wrong.

**Comment by lc-kay** [comment]
<img width="983" alt="Screen Shot 2021-08-12 at 11 51 55 AM" src="https://user-images.githubusercontent.com/70870126/129252395-4e55d102-f5aa-45c1-82ad-aa83072320db.png">
@aashnasingh Your explanation is right and the next operation "Front" should return -1. Per the screenshot, your code is outputting 5. Therefore, we marked it as wrong answer. Thank you for your time.
