### ISSUE TITLE
53. Maximum Subarray [Missing Testcase]

### ISSUE THREAD

**Issue by cryptozoid** [LeetCode-Feedback/LeetCode-Feedback#445]
#### Your LeetCode username
Cryptozoid

#### Category of the bug
- [ ] Solution

#### Description of the bug
I have used the following code. My code was **Accepted** and returned as Correct.
Also, no constraints as such were given about the input array size. 
So I tried again with an empty array as an Input Testcase. Then this bug appeared in this custom input testcase.

#### Code you used for Submit/Run operation

```
// Maximum Subarray
class Solution {
public:
    int maxSubArray(vector<int>& nums) {
        int n=nums.size();
        if (n==0){
            return 0;
        }
        int LSCS[n];
        LSCS[0]=*(nums.begin());
        for (int i=1;i<n;i++){
            LSCS[i]=max(LSCS[i-1]+*(nums.begin()+i),*(nums.begin()+i));
        }
        return (*(max_element(LSCS,LSCS+n)));
    }
};
```

#### Language used for code
C++

#### Expected behavior
*Output* was 0, but *Expected* answer given by IDE was a large negative junk value.

#### Screenshots
![Screenshot_2020-06-10 Maximum Subarray - LeetCode](https://user-images.githubusercontent.com/66710398/84228546-f2cd9680-ab04-11ea-829d-1293a4eaae7a.png)

#### Additional context
Alternatively, a constraint could be placed on the size of the input (testcase) array, to prevent this error.

**Comment by CooperCooperCooper** [comment]
Hi @cryptozoid ,
Thank you for reaching out to us. This issue has been raised by #408 before. Please check out the solution. We appreciate your support.
