### ISSUE TITLE
Missing Test Case - 954. Array of Doubled Pairs

### ISSUE THREAD

**Issue by Zhima-Mochi** [LeetCode-Feedback/LeetCode-Feedback#4451]
#### Your LeetCode username

yehgoter

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

missing test cases
[2,4,0,0,8,1]

#### Code you used for Submit/Run operation

```py
class Solution(object):
    def canReorderDoubled(self, arr):
        """
        :type arr: List[int]
        :rtype: bool
        """
        cnt = Counter(arr)

        for n in cnt.keys():
            n_cnt = cnt[n]

            if n_cnt == 0:
                continue

            if n >= 0:
                needed = n * 2
            else:
                if n % 2 != 0:
                    needed = n * 2
                else:
                    needed = n / 2

            if n_cnt <= cnt[needed]:
                cnt[n] = 0
                cnt[needed] -= n_cnt

        return len(filter(lambda val: val > 0, cnt.values())) == 0
```

#### Language used for code

Python

#### Expected behavior

I found this python code written by [leo_dashko](https://leetcode.com/leo_dashko/) at [solution page](https://leetcode.com/problems/array-of-doubled-pairs/solution/) which concept is wrong but pass all the current testcase.
Counter is hashtable and the order of keys is not (guaranteed to be) monotonic increasing or decreasing. If the order is same as insertion order, given [2,4,0,0,8,1], it should return wrong answer by the logic of the code. The outcome is also wrong answer, so I recommend this testcase.

#### Screenshots

![image](https://user-images.githubusercontent.com/77471137/129024532-0a53834b-69e8-4d5d-8b39-2231405e768a.png)

#### Additional context

Share my [solution](https://leetcode.com/problems/array-of-doubled-pairs/discuss/1396906/solution-for-c-on-log-n-time-and-o1-space-two-pointers) which use other method

**Comment by lc-kay** [comment]
Hi @Zhima-Mochi 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by kaushalaneesha** [comment]
Even test case : [2, -4] is failing for the solution shared in the question. It returns true though it should be false.
