### ISSUE TITLE
Question - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by DoTheBestMayB** [LeetCode-Feedback/LeetCode-Feedback#4452]
#### Your LeetCode username

LeetMus

#### Category of the bug
- [V ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I can't understand why leetcode use this input format

[1, null, 2, 3] and [1,2,3,null,null,4,5,6,7] is no make senses.

below picture should be [1, null, 2, null, null, 3] as wikipedia binary array definition

If leetcode uses a different method, I think more explanation is needed because very confusing 

<img width="86" alt="binarytree3" src="https://user-images.githubusercontent.com/48354989/129029736-ebe09755-e38f-41b9-b721-881f00ab3cd0.png">

[image source](https://support.leetcode.com/hc/en-us/articles/360011883654-What-does-1-null-2-3-mean-in-binary-tree-representation-)

#### Code you used for Submit/Run operation

```
class Codec:

    def serialize(self, root):
        if not root:
            return ''

        queue = collections.deque([root])
        ans = str(root.val)

        while queue:
            cur_root = queue.popleft()

            if cur_root is None:
                if queue.count(None) == len(queue):
                    break
                ans += ',None,None'
                for _ in range(2):
                    queue.append(None)
                continue

            if cur_root.left:
                ans += ',' + str(cur_root.left.val)
                queue.append(cur_root.left)
            else:
                ans += ',None'
                queue.append(None)

            if cur_root.right:
                ans += ',' + str(cur_root.right.val)
                queue.append(cur_root.right)
            else:
                ans += ',None'
                queue.append(None)

        ans = ans.rstrip(',None')
        return ans

    def deserialize(self, data: str):
        # print(data)
        nums = data.split(',')
        if len(nums) == 0 or nums[0] == '':
            return None
        idx = 0

        root = TreeNode(int(nums[idx]))
        deque = collections.deque([root])
        idx += 1

        while deque and idx < len(nums):
            cur_root = deque.popleft()

            if nums[idx] != 'None':
                cur_root.left = TreeNode(int(nums[idx]))
                deque.append(cur_root.left)
            idx += 1

            if idx < len(nums) and nums[idx] != 'None':
                cur_root.right = TreeNode(int(nums[idx]))
                deque.append(cur_root.right)
            idx += 1

        return root
```

#### Language used for code
python3

#### Expected behavior

Leetcode use wikipedia binary input format

**Comment by lc-kay** [comment]
@DoTheBestMayB In the problem description, there's a clarification section to clarify this point. 

> Clarification: The input/output format is the same as how LeetCode serializes a binary tree. You do not necessarily need to follow this format, so please be creative and come up with different approaches yourself.

I hope this addresses your doubts and concerns. Thank you for your time.

**Comment by DoTheBestMayB** [comment]
@lc-kay  But my code is not passed

**Comment by DoTheBestMayB** [comment]
@lc-kay I understands that Clarification means The code can be implemented regardless of whether it passes through the input format. Is this right? or should be passed despite the input format?

**Comment by lc-kay** [comment]
@DoTheBestMayB Your approach does not have to follow this exact format.
