### ISSUE TITLE
Missing part in question - 57. Insert Interval

### ISSUE THREAD

**Issue by VenkateshPoosarla** [LeetCode-Feedback/LeetCode-Feedback#4454]
#### Your LeetCode username

venkatesh31

#### Category of the bug
- [ *] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question did not ask that result has to be  in sorted order in start time 

#### Code you used for Submit/Run operation

```
class Solution {
    public int[][] insert(int[][] intervals, int[] ni) {
        List<int[]> li = new ArrayList<>();
        boolean merged = false;
        for (int[] x : intervals) {
          // intervals before we see intersection
            if (x[1] < ni[0]) {
                li.add(x);
            } // intervals after we see intersection
            else if (x[0] > ni[1]) {
                // if (!merged) {  //check if the interval is not merged and add it to the list
                //     li.add(ni);
                //     merged = true;
                // }
                li.add(x);
            } else {  // intervals with intersection
                ni[0] = Math.min(ni[0], x[0]);
                ni[1] = Math.max(ni[1], x[1]);
            }
        }
        if (!merged) {  //check if the interval is not merged and add it to the list
            li.add(ni);
        }
        int y[][] = new int[li.size()][2];
        for (int i = 0; i < li.size(); i++) {
            y[i] = li.get(i);
        }
        return y;
    }
}
```

#### Expected behavior

Since the order was not mandated the order of the output may be changed and hence not matching with the test cases

**Comment by lc-kay** [comment]
Hi @VenkateshPoosarla 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @VenkateshPoosarla 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
