### ISSUE TITLE
Missing Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by polachandu** [LeetCode-Feedback/LeetCode-Feedback#4455]
#### Your LeetCode username

Chandupola

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing Test Cases

#### Description of the bug

[-4,-5,-3,-2,-1]
#### Code you used for Submit/Run operation

```
// Two Sum
ArrayList<Integer> al = new ArrayList<>();
      for (int i = 0; i < nums.length; i++) {
			al.add(nums[i]);
		}
		Set set = new HashSet<>(al);
		al.clear();
		al.addAll(set);

		 if(al.size()<3){
	            int m=Integer.MIN_VALUE;
	            for(int i=0;i<al.size();i++){
	                if(al.get(i)>m){
	                    m=al.get(i);
	                }
	            }return m;
	        }
		int f=0;
		for(int i=0;i<al.size();i++) {
			if (al.get(i)>f ) {
	            f = al.get(i);}
		}
		
		int s=al.get(0);
	    for (int i=0;i<al.size();i++) {
	        if (al.get(i)>s&&al.get(i)< f) {
	            s = al.get(i);}
	    }
	    
	    int t=al.get(0);
	    for (int i=0;i<al.size();i++) {
	        if (al.get(i)>t&&al.get(i)< s) {
	            t =al.get(i);}
	    }
        return t;
```

#### Language used for code

java

#### Expected behavior

Missing test case

#### Additional context

With this code, leetcode accepted. But, the test code mentioned above with this code shows wrong output(-2) but it should be -3(correct output)

**Comment by lc-kay** [comment]
@polachandu Please provide the submission details link to your code. Thank you.

**Comment by polachandu** [comment]
https://leetcode.com/submissions/detail/537024064/

**Comment by lc-kay** [comment]
Hi @polachandu 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @polachandu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
