### ISSUE TITLE
288. Unique Word Abbreviation 

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#446]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Ambiguous description of the problem.

#### Code you used for Submit/Run operation
There are two cases when statement _“no other word from the dictionary has the same abbreviation”_ is true:
1.	An abbreviation of a word doesn’t exist in the dictionary, therefore it’s unique.
2.	An abbreviation of a word does exist in the dictionary (but it must be present only once) AND a word appears only once in the dictionary.

Not all the test cases were shown in provided example. Because of that it lets user think the only time word is unique is when it doesn't exist in the dictionary. Which is not true. 

#### Language used for code

Python3

#### Expected behavior

Comprehensive explanation of the problem and more test cases with a clear explanation why given output is true or false is needed. Below example covers all the cases:
```
Given dictionary = [ "deer", "door", "cake", "card"]
Abbreviations = [“d2r”, “d2r”, “c2e”, “c2d”]
isUnique("cart") ->true because abbreviation c2t not in dictionary
isUnique("cane") ->false because c2e already in dictionary
isUnique("make") ->true because m2e not in dictionary
isUnique(“cake”) ->true because word is unique (appears only once) AND abbr is unique (appears only once) 
isUnique("dear") ->false because word appears only once BUT d2r already in dictionary. Therefore, abbreviation isn’t unique
```

**Comment by CooperCooperCooper** [comment]
Hi @agatagruza ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @agatagruza ,
Thank you for your time. Your feedback has enabled us to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

**Comment by agatagruza** [comment]
Thank you @CooperCooperCooper  :relaxed: Glad could help :thumbsup:
