### ISSUE TITLE
149. Max Points on a Line - Solution Explanation Clarity

### ISSUE THREAD

**Issue by mdtareque** [LeetCode-Feedback/LeetCode-Feedback#4460]
#### Your LeetCode username
mtk20

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
N/A. Solution Description Language issue.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior

A] This
> One might argument we could treat this as a special case,...

should be
> One might **argue**, we could treat this as a special case,...

 
B]  This
> However, a bigger problem is that the float and double values are intrinsically inaccurate,

Should be
> However, a bigger problem is that the **binary representation** of float and double values are intrinsically inaccurate,

#### Screenshots
N/A

**Comment by lc-kay** [comment]
Hi @mdtareque 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by mdtareque** [comment]
@LC-Pam when would the coins be allotted?

**Comment by LC-Pam** [comment]
The reward for leetcoins depends on the question you submit, this is determined by the content team, not all submitted matters will be rewarded, thank you
