### ISSUE TITLE
Update Description - 265. Paint House II

### ISSUE THREAD

**Issue by Dhruval10** [LeetCode-Feedback/LeetCode-Feedback#4462]
#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the Question

The following line should be added in the question description.

```
If the cost can not be found, then return 2147483647 or (2^31)-1
```

Without the above line, candidates don't know what shall they return if the ```cost[i].length == 1```. They can return -1 or 0 which will lead them to a wrong submission answer. It should be addressed properly since the problem is of Hard difficulty, understanding the problem will take more time and after making a submission, the candidate will get an error simply because the data is not provided in the question.

###### Please let me know if I needed to provide any more context in this case

**Comment by lc-kay** [comment]
Hi @Dhruval10 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Dhruval10 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
