### ISSUE TITLE
Update Solution- 9. Palindrome Number

### ISSUE THREAD

**Issue by Momellouky** [LeetCode-Feedback/LeetCode-Feedback#4463]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

9. Palindrome number has a constraint, it tells us to avoid integer overflow, actually the submission would be accepted only if I avoid the overflow ( at least using c++, I guess must be the same with other languages ). 
But in the solution ( the solution uses c# ) cares just about reverting the integer and comparing with the user input in order to check if it's palindrome or not, which is correct but it doesn't respect the constraints mentioned in the problem description. 

#### Code you used for Submit/Run operation

```
// Palindrome Number
class Solution {
public:
    bool isPalindrome(int x) {
        int reversed = 0;
        int pop; 
        int userNumber = x; 
        
        if(x < 0)
            return false; 
        
        while(userNumber != 0) {
            pop = userNumber % 10; 
            userNumber = userNumber / 10; 
            
            // constraint 
            if(reversed > INT_MAX / 10 || reversed == INT_MAX && pop > 7)
                return false; 
            if(reversed < INT_MIN / 10 || reversed == INT_MIN && pop < -8)
                return false; 
            
            reversed = reversed*10 + pop; 
        } 
        
        return reversed == x; 
    }
};
```

**Comment by lc-kay** [comment]
Hi @Momellouky 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Momellouky,
Thank you for reaching out. The suggestion is now moot since the code does avoid overflow since it only reverses half of the original number, thus the reversed number will never cause integer overflow.
