### ISSUE TITLE
Improper Test Case - 159. Longest Substring with At Most Two Distinct Characters

### ISSUE THREAD

**Issue by kalexmills** [LeetCode-Feedback/LeetCode-Feedback#4465]
#### Your LeetCode username
user9276gU

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The longest common substring problem clearly states the length of s will be no more than 10^4, however the length of [this test case](https://leetcode.com/submissions/detail/537485469/testcase/) is 50,000.

#### Code you used for Submit/Run operation

```golang
func lengthOfLongestSubstringTwoDistinct(s string) int {    
    
    lastIndexOf := make(map[byte]int)   //{ s[0]: 0 }
    i := 0
    j := 0
    
    max := 0
    for idx := 0; idx < len(s); idx++ {
        x := s[idx]
        
        lastIndexOf[x] = idx          // update the last index of the newly seen letter
        
        if len(lastIndexOf) == 3 {
            minArg, minIdx := minIndex(lastIndexOf)
            i = minIdx+1
            delete(lastIndexOf, minArg) // note: we don't need letterSet
        }
        
        j = idx+1
        
        if max < j - i {
            max = j - i
        }
    }
    
    return max
}

func minIndex(lastIndexOf map[byte]int) (byte, int) {
    min := 10000
    var argMin byte
    
    for b, i := range lastIndexOf {
        if i < min {
            argMin = b
            min = i
        }
    }
    
    return argMin, min
}

```

#### Language used for code
Go

#### Expected behavior
Test judge should not submit solutions which are outside of the constraints provided. A programmer can reasonably use these constraints as part of their solution (for instance, setting upper bounds when finding the min).

#### Screenshots
![image](https://user-images.githubusercontent.com/22620342/129245817-cecdefd0-e6e8-44d7-b849-bc6f8379b74e.png)

**Comment by lc-kay** [comment]
Hi @kalexmills 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
