### ISSUE TITLE
Simple 0ms, 100% fast

### ISSUE THREAD

**Issue by TusharSharma8201** [LeetCode-Feedback/LeetCode-Feedback#4466]
public void moveZeroes(int[] nums) {
        int itr=0,ptr=-1;
        
        while(itr<nums.length){
            if(nums[itr]!=0){
                swap(nums,++ptr,itr);
            }
            itr++;
        }
        
    }
    
    public static void swap(int[] arr,int i,int j){
        int temp=arr[i];
        arr[i]=arr[j];
        arr[j]=temp;
    }
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@TusharSharma8201 Please share your solution in the problem discuss section for others to view. 

We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
