### ISSUE TITLE
Missing Test Case - 494. Target Sum

### ISSUE THREAD

**Issue by arpansheetal** [LeetCode-Feedback/LeetCode-Feedback#4467]
#### Category of the bug
- Missing Test Cases 

#### Code you used for Submit/Run operation

```
# Two Sum
import math
class Solution:
    def findTargetSumWays(self, nums: List[int], target: int) -> int:
        arr_sum = sum(nums)
        pos_num = [i for i in nums if i != 0]
        n_zeros = len(nums) - len(pos_num)
        num_ele = len(pos_num)
        
        if target > arr_sum or (arr_sum + target)%2 != 0:
            return 0
        
        if len(pos_num) == 0:
            return int(math.pow(2, n_zeros))
        
        target = (arr_sum + target)//2
        #print(target)
        dp = [[0 for i in range(target+1)] for i in range(num_ele)] # row: ele # col: target_sum
        
        #print(len(dp), len(dp[0]))
        for i in range(num_ele):
            dp[i][0] = 1

        for i in range(num_ele):
            for j in range(1, target+1):
                #print(i, j)
                if pos_num[i] > j:
                    #print('if', i, j)
                    dp[i][j] = dp[i-1][j]
                else:
                    #print('else', i, j)
                    dp[i][j] = dp[i-1][j] + dp[i-1][j - pos_num[i]]
        return dp[num_ele-1][target]*int(math.pow(2, n_zeros))```

#### Language used for code
<!-- Python3 -->


#### Expected behavior
<!-- Runtime Error of index out of range -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
<img width="892" alt="Screenshot 2021-08-13 at 12 46 57 AM" src="https://user-images.githubusercontent.com/6384706/129255728-243dedfa-c256-42e6-8fc5-9981d2dc12d3.png">




#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
@arpansheetal What is the missing test case that you are trying to report?

**Comment by arpansheetal** [comment]
@lc-kay please find the test case below:
Input: nums = [100], target = -200
Expected Output: 0

The above code outputs **Runtime Error: Index out of range** for the given test case, which implies that the code should not get submitted/accepted by the system. But since the above test case is missing from the test cases, the system accepts the code. That is why we should add the above tase case to ensure the correctness of the logic/algorithm for the given problem.

**Comment by lc-kay** [comment]
Hi @arpansheetal 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @arpansheetal 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by arpansheetal** [comment]
@lc-kay it's been a pleasure. Here is my leetcode ID: arpansheetal for leetcode points
