### ISSUE TITLE
Existing test case issue : 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by duttabhishek0** [LeetCode-Feedback/LeetCode-Feedback#4469]
#### Your LeetCode username
Xenikh32

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [] Missing Test Cases 

#### Description of the bug
This issue is created with reference to problem number 287. Find the Duplicate Number.
In the question, it is clearly mentioned that there is _only one repeated number_ in the array. 

> There is only one repeated number in nums, return this repeated number.

#### Code you used for Submit/Run operation

```
// Find the Duplicate Number
class Solution {
public:
    int findDuplicate(vector<int>& nums) {
        int ans = 0;
        int n = nums.size();
        int sum = 0,sum2;
        sum2 = (n*(n-1))/2;
        for(int i = 0;i < nums.size();i++){
            sum += nums[i];
        }
        ans = abs(sum2 - sum);
        return ans;
    }
};
```

#### Language used for code
 C++ 

#### Expected behaviour
The above code should pass all the cases, since it is clearly mentioned that there exists a single duplicate number. But my solution failed in a case, where the array had `n` duplicate numbers, where `n` is the number of elements inside the array. 

#### Screenshots
![Screenshot from 2021-08-13 07-43-28](https://user-images.githubusercontent.com/56694152/129295612-3fa68b18-cdbe-4f02-af56-f3fa2591d197.png)

#### Additional context
IMHO, the test case is the wrong one. It defers what is written in the question.

**Comment by RavjotSandhu** [comment]
Yes exaclty! In fact I was solutions, from which I infer that the question description is wrong

**Comment by RavjotSandhu** [comment]
![image](https://user-images.githubusercontent.com/58950644/129302753-7d25f92f-e271-4ca8-8948-7112a683bfc8.png)

This middle line "only one repeated number" is utterly misleading

**Comment by lc-kay** [comment]
@duttabhishek0 @RavjotSandhu Please refer to the last constraint: All the integers in nums appear only once except for precisely one integer which appears two or more times. In this test case, there is only one repeated number, such that 2 is the only repeated number in this test case. I hope this clarifies your doubts and concerns. Thank you for your time.
