### ISSUE TITLE
858. Mirror Reflection - Broken image icon

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#447]
#### Your LeetCode username

roll_no_1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The image in example 1 has a broken image icon. Not quite sure about what exactly is that, since the image itself is sufficient to describe the example case. 

#### Code you used for Submit/Run operation
N/A

#### Language used for code

N/A

#### Expected behavior

Probabaly the broken image icon should be removed.

#### Screenshots

![image](https://user-images.githubusercontent.com/36921843/84258739-0e509580-ab35-11ea-8bda-072d982283e7.png)

#### Additional context

N/A

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for reaching out to us. I've looked for the broken image icon on the problem description but was unable to find it (please see my side of the image attached to this message as a screenshot). Would you mind using a private browser window to see if the issue persists?
<img width="702" alt="Screen Shot 2020-06-10 at 8 15 39 PM" src="https://user-images.githubusercontent.com/59751300/84342110-947ed300-ab59-11ea-8c19-4eae15864ace.png">

**Comment by roll-no-1** [comment]
I opened the link in a private window but got the same results 
![image](https://user-images.githubusercontent.com/36921843/84358514-e0c32500-abe4-11ea-95e1-7dc5dd114321.png)


**I am using firefox browser.**

However, when **I tried using the chrome browser, the broken image icon wasn't there.** So, it's probably a browser issue. Maybe you can try opening this in firefox once.

**Comment by roll-no-1** [comment]
Hi @CooperCooperCooper!

I'm attaching the output that I got on trying to inspect the image that is visible on firefox and chrome. I am attaching the screenshots and description in case it helps.

**On Firefox:**
If you look at the output of Inspect, there are clearly 2 images: the one in blue corresponds to the broken image icon and the one below it is the visible image. The size of the image shows up on firefox as **24 x 24**.
![image](https://user-images.githubusercontent.com/36921843/84632378-7116a800-af0c-11ea-8bbe-b1cfe5b1b92f.png)

**On Chrome:**
In the output of Inspect, the highlighted part is the one corresponding to the broken image icon in the picture above. The size of the image in chrome shows up as **0 x 0**. 
![image](https://user-images.githubusercontent.com/36921843/84632537-afac6280-af0c-11ea-9ed8-d99cee0ea38f.png)

***This means that this might be a browser issue. But clearly, there are 2 image links, one of which is broken. So, I suggest that to be removed.***

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @roll-no-1 ,
Thank you for reaching out. We found this issue is only reproducible in ubuntu and we've fixed it. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
