### ISSUE TITLE
Missing Test Case - 796. Rotate String

### ISSUE THREAD

**Issue by daiyirita** [LeetCode-Feedback/LeetCode-Feedback#4470]
#### Your LeetCode username

ro0k1e

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug

My code passes all test cases, but actually not pass this case:
"abcde"
"abcdg"

#### Code you used for Submit/Run operation

```
class Solution(object):
    def rotateString(self, s, goal):
        """
        :type s: str
        :type goal: str
        :rtype: bool
        """
        if len(s) != len(goal):
            return False
        if len(s) == 0:
            return True
        
        for i in xrange(len(s)):
            for j in xrange(len(s)):
                if s[(j+i) % len(s)] != goal[j]:
                    print(i, j)
                    break
            if j == len(s) - 1:
                return True
        return False
```

#### Language used for code

Python

#### Expected behavior

It should return false

**Comment by lc-kay** [comment]
Hi @daiyirita 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @daiyirita 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
