### ISSUE TITLE
Missing Test Case - 49. Group Anagrams

### ISSUE THREAD

**Issue by akashkum** [LeetCode-Feedback/LeetCode-Feedback#4473]
#### Your LeetCode username
ReinventingMe

#### Category of the bug
 Missing Test Cases 

#### Description of the bug
For this question following solution is passing all test cases on submission but it should not as it fails on the test case given below.
```
Input :["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab"]

expected Output:
[["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab"],["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"]]

output by following code:
[["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab"]]
```

#### Code you used for Submit/Run operation

```
class Solution {
    
    int[] primes = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103};
    
    public  List<List<String>> groupAnagrams(String[] strs) {

       if(strs==null || strs.length==0) return new ArrayList<>();

        Map<Long, List<String>> map = new HashMap<>();

        for(String s : strs){
            long key = getPrimeProduct(s);
            if(!map.containsKey(key)){
                map.put(key, new ArrayList<>());
            }
            map.get(key).add(s);
        }
        return new ArrayList<>(map.values());
    }

    private long getPrimeProduct(String s) {
      long result=1;
        for(int i =0 ; i<s.length();i++){
            char c = s.charAt(i);
            int n = c - 'a';
            result = result*primes[n];
        }
        // System.out.println(result);
        return result;
    }
}

```

#### Language used for code
Java

#### Expected behavior
As string length can be up to 100 characters. So "result" variable in "getPrimeProduct" function overflows and for given testcases it returns zero for both strings. 
As both strings in a given input are not anagram as character 'b' is not present in the first string while it is present in the second string. So expected answer would have been a list of two lists with each containing one of the strings in the input. but the above code return a list of a single list containing both strings.

**Comment by lc-kay** [comment]
Hi @akashkum 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @akashkum 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
