### ISSUE TITLE
（缺少测试用例）面试题 01.02. 判定是否互为字符重排

### ISSUE THREAD

**Issue by ab12323** [LeetCode-Feedback/LeetCode-Feedback#4474]
**你的 LeetCode 用户名**
12323

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
[√] 缺少测试用例

**描述**
我的代码能够成功的通过此题，但是无法通过测试用例
"singletons"
"concluding".

**你使用的语言**
Python

**你提交或者运行的代码**
```
class Solution:
    def CheckPermutation(self, s1: str, s2: str) -> bool:
        times, value = 0, 0

        n1, n2 = len(s1), len(s2)
        if n1 != n2:
            return False

        for i in range(n1):
            t1, t2 = ord(s1[i]) - ord('a'), ord(s2[i]) - ord('a')
            times ^= t1 ^ t2
            value += (1 << t1) - (1 << t2)
        
        return times == 0 and value == 0
```

**期望行为**
增加测试用例，使得题目更加完善

**屏幕截图**
![image](https://user-images.githubusercontent.com/50291232/129322975-2ab64373-79a5-402e-ac15-2c6348933701.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@ab12323 你好，当前该题已更新修复。力扣会定期更新，保障稳定和体验优化。
