### ISSUE TITLE
Missing Test Case - 1111. Maximum Nesting Depth of Two Valid Parentheses Strings

### ISSUE THREAD

**Issue by akash2305-Git** [LeetCode-Feedback/LeetCode-Feedback#4476]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by akash2305-Git** [comment]
/* Question  https://leetcode.com/problems/maximum-nesting-depth-of-two-valid-parentheses-strings/ */

class Solution {
public:
    vector<int> maxDepthAfterSplit(string seq) {
        vector<int > Depth;
        for(int i=0;i<=seq.size();i++){
            int j= i+1;
            if(seq[i] == '(' && seq[j] == ')'){
                Depth.push_back(1);
                Depth.push_back(1);
                j++;
            }
            else if(seq[i] == '(' ||  seq[j] == '(' && seq[i]== ')' || seq[j] == ')'){
                Depth.push_back(0);
                j++;
            }
        }
        return Depth;
    }
};
Input :- "(()())"
my Output:- [0,1,1,0,1,1,0]
Expected :-[0,1,1,1,1,0]

**Comment by lc-kay** [comment]
@akash2305-Git Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
