### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by shehab-ashraf** [LeetCode-Feedback/LeetCode-Feedback#4477]
#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug
there one test case is missing or more, why?
when i used code and to use O(1) space when i find matrix[i][j] == 0 i convert all row and column to INT_MIN and make another iterate to convert that INT_MIN to 0 but i found my code not bass  1 test case because i found in matrix input INT_MIN in some cell as an input so in second iteration i convert it also and this wrong , so what issue here ! when i used (INT_MIN+1) as base 
case in my code instead off (INT_MIN) my code passed all tests cases and this is wrong because (NIT_MIN+1) if in range form(INT_MIN ) to (INT_MAX) and if (INT_MIN+1) is a input in my code my code not pass all testes cases!bbbb 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    void setzero(vector<vector<int>>  &matrix , int row , int column , int n , int m) {
        for(int i = 0 ; i < m ; i++){
            if(matrix[row][i] != 0 ) matrix[row][i] = INT_MIN+1;
        }
        
        for(int i = 0 ; i < n ; i++){
            if(matrix[i][column] != 0) matrix[i][column] = INT_MIN+1;
        }
        
        
    }
    void setZeroes(vector<vector<int>>& matrix) {
        
        for(int i = 0 ; i < matrix.size() ; i++){
            for(int j = 0; j < matrix[i].size() ; j++){
                if(matrix[i][j] == 0) setzero(matrix , i , j , matrix.size() , matrix[i].size());
            }
        }
        
        for(int i = 0 ; i < matrix.size() ; i++){
            for(int j = 0; j < matrix[i].size() ; j++){
                if(matrix[i][j] == INT_MIN+1) matrix[i][j] = 0;
            }
        }
        
        
    }
};
```

**Comment by lc-kay** [comment]
@shehab-ashraf Can you provide the exact test case that will cause this solution to fail? Thank you!

**Comment by shehab-ashraf** [comment]
Ok, this is test case that make my code to fail !
or any test case have in it's input ([-2147483647])
![](https://fv6.failiem.lv/thumb_show.php?i=zqb9xjq6a&view)

**Comment by lc-kay** [comment]
Hi @shehab-ashraf 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@shehab-ashraf Our team won't add this test case as it uses a special value and after failing it, we can change INT_MIN+1 to INT_MIN+2 to get a new AC solution, and failing all these solutions is impossible. Thank you for your time and understanding.
