### ISSUE TITLE
Missing Solution - 1944. Number of Visible People in a Queue

### ISSUE THREAD

**Issue by skully-coder** [LeetCode-Feedback/LeetCode-Feedback#4478]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution for this question is either missing or not visible

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> canSeePersonsCount(vector<int>& heights) {
        int n = heights.size();
        vector<int> dp(n), ans(n);
        for (int i = heights.size() - 1; i >= 0; i--) {
            int cnt = 0;
            int j  = i + 1;
            for (; j < n && heights[j] < heights[i]; cnt++, j = dp[j]);
            dp[i] = j;
            ans[i] = cnt + (j != n);
        }
        return ans;
    }
};
```

#### Expected behavior

I expected the solution to be shown, but there was no solution.

#### Screenshots

![image](https://user-images.githubusercontent.com/55917548/129363713-e74d54a5-a800-4055-b7d2-be1c9f09c539.png)

**Comment by lc-kay** [comment]
@skully-coder Thank you for reaching out to us. A solution article is not available for this question yet. Our content team is working hard to publish more articles. We appreciate your time and support.
