### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by mthienpont** [LeetCode-Feedback/LeetCode-Feedback#4479]
#### Your LeetCode username
mthienp

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
Wrong test case solution for Easy Questions - Rotate Array

#### Code you used for Submit/Run operation

```go
func rotate(nums []int, k int)  {
    var temp int
    for i := 0; i < k; i++ {
        temp = nums[0]
        for j := 0; j < len(nums)-1; j++ {
            nums[j]=nums[j+1]
        }
        nums[len(nums)-1] = temp
    }
}
```

#### Language used for code
Go

#### Expected behavior
The expected from the test case was wrong, output is correct
Input:
[1,2,3,4,5,6,7]
3
Output:
[4,5,6,7,1,2,3]
Expected:
[5,6,7,1,2,3,4]

**Comment by lc-kay** [comment]
@mthienpont The expected output is correct. Please check out example 1

Input: nums = [1,2,3,4,5,6,7], k = 3
Output: [5,6,7,1,2,3,4]
Explanation:
rotate 1 steps to the right: [7,1,2,3,4,5,6]
rotate 2 steps to the right: [6,7,1,2,3,4,5]
rotate 3 steps to the right: [5,6,7,1,2,3,4]

Thank you for your time.
