### ISSUE TITLE
Incorrect Test Case / Incorrect constraints - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by pratikpanchal22** [LeetCode-Feedback/LeetCode-Feedback#4480]
#### Your LeetCode username
pp423

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] ~~Missing~~ Incorrect Test Cases 

#### Description of the bug

The constraints section of this problem lists the constraint for matrix[i][j] as follows:

> -2<sup>31</sup> <= matrix[i][j] <= 2<sup>31</sup> - 1

But during submission, there are two test cases that do not respect these constraints. These test cases are:

1.  Test case 1: `[[-2147483648],[2],[3]]`  
  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -2147483648 = -2<sup>31</sup>-1 which is out of range of the given constraint -2<sup>31</sup>

2.  Test case 2: `[[2147483647],[2],[3]]`  
  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2147483647 = 2<sup>31</sup> which is out of range of the given constraint 2<sup>31</sup> - 1

#### Code you used for Submit/Run operation

1. Test case 1: `[[-2147483648],[2],[3]]` ([LeetCode submission](https://leetcode.com/submissions/detail/537923151/)):
```
class Solution {
    public void setZeroes(int[][] matrix) {
        
        for(int r=0; r<matrix.length; r++){
            for(int c=0; c<matrix[r].length; c++) if(matrix[r][c]==0){
                matrix[r][0] = Integer.MIN_VALUE;
                matrix[0][c] = Integer.MIN_VALUE;
            }
        }
        
        for(int[] row : matrix){
            System.out.println(Arrays.toString(row));
        }
        
        //set each cell to 0 if either the corresponding row or column is marked
        //do it in reverse order so that the mark is not overwritten before all the cells in that row/column are set to 0 first
        for(int r=matrix.length-1; r>=0; r--){
            for(int c=matrix[r].length-1; c>=0; c--){
                if(matrix[r][0]==Integer.MIN_VALUE || matrix[0][c]==Integer.MIN_VALUE){
                    matrix[r][c]=0;
                }
            }
        }
        
    }
}
```
2. Test case 2: `[[2147483647],[2],[3]]`  [(LeetCode submission)](https://leetcode.com/submissions/detail/537925079/):
```
class Solution {
    public void setZeroes(int[][] matrix) {
        
        for(int r=0; r<matrix.length; r++){
            for(int c=0; c<matrix[r].length; c++) if(matrix[r][c]==0){
                matrix[r][0] = Integer.MAX_VALUE;
                matrix[0][c] = Integer.MAX_VALUE;
            }
        }
        
        //set each cell to 0 if either the corresponding row or column is marked
        //do it in reverse order so that the mark is not overwritten before all the cells in that row/column are set to 0 first
        for(int r=matrix.length-1; r>=0; r--){
            for(int c=matrix[r].length-1; c>=0; c--){
                if(matrix[r][0]==Integer.MAX_VALUE || matrix[0][c]==Integer.MAX_VALUE){
                    matrix[r][c]=0;
                }
            }
        }
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

Either the constraints defined in the problem section should be modified to:
> -2<sup>31</sup>-1 <= matrix[i][j] <= 2<sup>31</sup>    

Or   
the above-mentioned test cases should be modified to omit the constraints.

#### Screenshots

[Test case 1](https://drive.google.com/file/d/12_CBK1PZ648lc-OlzZwfdbKlUYVbLG5f/view?usp=sharing) 
[Test case 2](https://drive.google.com/file/d/1wQQ33W_WqKejkkRsqkoTxBrWztggy9Ft/view?usp=sharing)

#### Additional context

None

**Comment by lc-kay** [comment]
Hi @pratikpanchal22 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratikpanchal22 Our team has reviewed the test cases and concluded that they are correct and within the constraints. Please refer to the problem discuss section for further support and clarification on these test cases. Thank you for your time.
