### ISSUE TITLE
Missing Test Case - 79. Word Search

### ISSUE THREAD

**Issue by jerrywang94** [LeetCode-Feedback/LeetCode-Feedback#4481]
#### Your LeetCode username

b4aprogrammer123

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

This is a missing test case. After implementing my solution, I looked at the sample 0ms solution and realized that the sample code does not correctly address all test cases, although it passes leetcode submission fine.

Specifically, the following test case produces the wrong answer in the sample solution, but still passes leetcode submission:
[["F","R","D","R"],["E","A","D","F"]]
"RFEADFRD"

I verified using my own code and leetcode's output using the above as an example testcase.

#### Code you used for Submit/Run operation

```
//incorrect sample code, my own comments provided below
class Solution {
public:
   
    bool exist(vector<vector<char>>& board, string word) {
       for(int i=0;i<board.size();i++){
            for(int j=0;j<board[i].size();j++){
                vector<vector<bool>>v(board.size(),vector<bool>(board[0].size(),false));
                if(dfs(board,word,i,j,word.size(),v))
                    return true;
            }
        }
        return false;
    }
 bool dfs(vector<vector<char>>& board, string word,int i,int j,int k,vector<vector<bool>> &visited){
        if(k==0) return true;
        if(i<0 || j<0 || i==board.size() || j==board[0].size() || word[k-1]!=board[i][j] || visited[i][j])   
            return false;
        visited[i][j]=true; // this is the issue, visited gets set on the first DFS path, but does not get unset, which means possible candidate paths are not explored
        return dfs(board,word,i+1,j,k-1,visited) || dfs(board,word,i,j-1,k-1,visited) || dfs(board,word,i-1,j,k-1,visited) || dfs(board,word,i,j+1,k-1,visited);
               
    }
};
```

#### Language used for code

C++

#### Expected behavior

The submission for the sample code above should fail as it produces a wrong answer. It gives "false" to the new test case as opposed to "true."

**Comment by lc-kay** [comment]
Hi @jerrywang94 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jerrywang94 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
