### ISSUE TITLE
Missing Test Case - 468. Validate IP Address

### ISSUE THREAD

**Issue by ecollange** [LeetCode-Feedback/LeetCode-Feedback#4483]
#### Your LeetCode username

ecollange

#### Category of the bug
- Missing Test Cases 

#### Description of the bug

Fastest Java submission is not valid, it considers 172:68:1:1 to be a valid IPv4 or similarly an IPv6 address is considered valid even with . as separators

#### Language used for code

Java

#### Expected behavior

"172:68:1:1" and "2001.0db8.85a3:0000:0000:8a2e:0370:7334" should be added to the test cases

**Comment by lc-kay** [comment]
@ecollange Please provide the submission details link. Thank you.

**Comment by lc-kay** [comment]
Hi @ecollange 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
