### ISSUE TITLE
Missing Test Case - 843. Guess the Word

### ISSUE THREAD

**Issue by SumitJadiya** [LeetCode-Feedback/LeetCode-Feedback#4484]
#### Your LeetCode username
 stj11

#### Category of the bug
- [x] Question 
https://leetcode.com/problems/guess-the-word
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
"aaaacc"
["aabbcc","aaaacc","aazzcc","aaxxcc", "aayycc", "aallcc", "aacccc","aajjcc","aasscc", "aaoocc","aappcc","aaiicc", "aaqqcc", "aaffcc"]
10

#### Description of the bug

Testcase is missing

#### Code you used for Submit/Run operation

```
/**
 * // This is the Master's API interface.
 * // You should not implement it, or speculate about its implementation
 * interface Master {
 *     public int guess(String word) {}
 * }
 */
class Solution {
    public void findSecretWord(String[] wordlist, Master master) {
        Random random = new Random();
        for(int i = 0, matches = 0; i < 10 && matches != 6; i ++){
            String guess = wordlist[random.nextInt(wordlist.length)];
            matches = master.guess(guess);
            
            if(matches == 6) return;
            
            List<String> candidates = new ArrayList<>();
            for(String word: wordlist){
                if(matches == getMatches(guess, word)){
                    candidates.add(word);
                }
            }
            
            wordlist = candidates.toArray(new String[0]);
        }
    }
    
    private int getMatches(String word1, String word2){
        int matches = 0;
        for(int i = 0; i < word1.length(); i ++){
            if(word1.charAt(i) == word2.charAt(i)){
                matches ++;
            }
        }
        
        return matches;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Output : You guessed the secret word correctly.
but my output is not matching.
Ideally leetcode should not accept this answer but currently I'm able to submit this.

#### Screenshots

![image](https://user-images.githubusercontent.com/53819226/129397048-7b6b9670-7c6f-428f-9e3e-dd46a1e2e56d.png)

**Comment by lc-kay** [comment]
@SumitJadiya The code provided currently fails on the test case "cymplm"
["eykdft","gjeixr","eksbjm","mxqhpk","tjplhf","ejgdra","npkysm","jsrsid","cymplm","vegdgt","jnhdvb","jdhlzb","sgrghh","jvydne","laxvnm","xbcliw","emnfcw","pyzdnq","vzqbuk","gznrnn","robxqx","oadnrt","kzwyuf","ahlfab","zawvdf","edhumz","gkgiml","wqqtla","csamxn","bisxbn","zwxbql","euzpol","mckltw","bbnpsg","ynqeqw","uwvqcg","hegrnc","rrqhbp","tpfmlh","wfgfbe","tpvftd","phspjr","apbhwb","yjihwh","zgspss","pesnwj","dchpxq","axduwd","ropxqf","gahkbq","yxudiu","dsvwry","ecfkxn","hmgflc","fdaowp","hrixpl","czkgyp","mmqfao","qkkqnz","lkzaxu","cngmyn","nmckcy","alpcyy","plcmts","proitu","tpzbok","vixjqn","suwhab","dqqkxg","ynatlx","wmbjxe","hynjdf","xtcavp","avjjjj","fmclkd","ngxcal","neyvpq","cwcdhi","cfanhh","ruvdsa","pvzfyx","hmdmtx","pepbsy","tgpnql","zhuqlj","tdrsfx","xxxyle","zqwazc","hsukcb","aqtdvn","zxbxps","wziidg","tsuxvr","florrj","rpuorf","jzckev","qecnsc","rrjdyh","zjtdaw","dknezk"]
10

Please provide an accepted solution that will be failed by the reported missing test case. Thank you!

**Comment by SumitJadiya** [comment]
@lc-kay This same code was accepted by LC yesterday night.

**Comment by lc-kay** [comment]
@SumitJadiya Our team is consistently adding new test cases to our problems to ensure that all types of test cases are accounted for. Therefore, a new test case might have been added between the time you submitted this ticket and when I ran it. Thank you for your understanding.
