### ISSUE TITLE
Solution Provided Is InCorrect in Problem 875. 

### ISSUE THREAD

**Issue by valentinarodrigues** [LeetCode-Feedback/LeetCode-Feedback#4485]
### Your LeetCode username
valentinarodrigues93

### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

### Description of the bug

The solution provided for python is incorrect. It does not pass the test case

### Code you used for Submit/Run operation

```python
class Solution(object):
    def minEatingSpeed(self, piles, H):
        # Can Koko eat all bananas in H hours with eating speed K?
        def possible(K):
            return sum(((p-1) // K) + 1 for p in piles) <= H

        # since the range lies between 1 and the largest number of bananas in a pile
       # NOTE: the number need not be among the number in the given array it should just lie between 1 and the max(piles)
        lo, hi = 1, max(piles)

        while lo < hi:
            mi = (lo + hi) // 2
            if not possible(mi):
                lo = mi + 1
            else:
                hi = mi
        return lo
```

### Language used for code
Python

### Expected behavior
The code provided in the solution is not being accepted since the earlier solution was missing rounding few values

**Comment by lc-kay** [comment]
Hi @valentinarodrigues 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @valentinarodrigues,
Thank you for your feedback. The python code for this solution is intended to be run using python2, not python3. The tab above the code states "Python" for python and "Python3" for python3. Other signs that a code should be run in python include Solution(object) and no type hints.
