### ISSUE TITLE
Incorrect Test Case - 1726. Tuple with Same Product

### ISSUE THREAD

**Issue by H-Shen** [LeetCode-Feedback/LeetCode-Feedback#4487]
#### Your LeetCode username

HarrisonShen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Incorrect Test Cases 

#### Description of the bug

In the explanation of the second sample test, the tuple (10,2,4,5) is duplicated, one of them should be (10,2,5,4).

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    int tupleSameProduct(vector<int>& nums) {
        int n = (int)nums.size();
        if (n < 4) return 0;
        unordered_map<int,int> unmap;
        for (int i = 0; i < n-1; ++i) {
            for (int j = i+1; j < n; ++j) {
                ++unmap[nums[i]*nums[j]];
            }
        }
        int ans = 0;
        for (const auto &[k,v] : unmap) {
            if (v > 1) ans += (v*(v-1))<<2;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the second test as input, (10,2,4,5) should not be duplicated and one of them should be (10,2,5,4) in the output.

**Comment by lc-kay** [comment]
Hi @H-Shen 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @H-Shen 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
