### ISSUE TITLE
Missing Test Case - 179. Largest Number

### ISSUE THREAD

**Issue by sudheerchunduri** [LeetCode-Feedback/LeetCode-Feedback#4488]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Input:
[3,30,34,5,9]
Output:
"9543330"
Expected:
"9534330"

#### Code you used for Submit/Run operation

```
class Solution:
    def largestNumber(self, nums: List[int]) -> str:
            
        digit_list = []
        for n in nums:
            digit_list.extend(list(str(n)))
        
        digit_list.sort(reverse=True)
        print(digit_list)
        return "".join(digit_list)
```

#### Expected behavior

The  test case failed is in fact incorrect.

**Comment by lc-kay** [comment]
@sudheerchunduri The expected output is correct. Please check the comments in this [discuss post ](https://leetcode.com/problems/largest-number/discuss/129750/Wrong-testcase-for-Input%3A-3303459-Output%3A-%229534330%22-Should-the-output-not-be-%229543330%22)Thank you for your time.
