### ISSUE TITLE
Typo in Problem Description - 481. Magical String

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#4489]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [481. Magical String](https://leetcode.com/problems/magical-string), there is a typo in Explanation of Example 1. The statement "The first 6 elements of magical string s is "12211"" should be "The first 6 elements of magical string s is "12211**2**"".

Since `n = 6`, there should be 6 characters in the first 6 elements. However, "12211" only contains 5 characters. Therefore, it should be changed to "122112".

#### Expected behavior
In Explanation of Example 1, "12211" should be changed to "122112".

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/129435980-e378ca2e-0dfe-41f0-8f95-b85ee0fcc7a7.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
