### ISSUE TITLE
java的Collection使用报错

### ISSUE THREAD

**Issue by FBMeng** [LeetCode-Feedback/LeetCode-Feedback#449]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言

**描述**
java的Collection使用报错，在idea上是可以正常使用的

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public int lengthOfLongestSubstring(String s) {
        //记录字串和其长度
		Map<String,Integer> map = new HashMap<>();

		char[] sCharArray = s.toCharArray();
		int length = sCharArray.length;
		for(int i=0;i<length;i++){
			Set<Character> childStrSet = new HashSet<>();
			int setSize = 0;
			boolean isContinue = true;
			int j = i;
			while(isContinue && j<length){
				childStrSet.add(sCharArray[j]);
				if(childStrSet.size() == setSize){
					isContinue = false;
					break;
				}
				setSize++;
				j++;
			}
			map.put(s.substring(i,j),childStrSet.size());
		}
		System.out.println(map);
		Collection<Integer> values = map.values();
		List<Integer> collect = values.stream().sorted().collect(Collectors.toList());
		return collect.get(collect.size()-1);
    }
}
```

**期望行为**
不报错

**屏幕截图**

**额外的上下文**
报错信息如下：
Line 25: error: cannot find symbol
		Collection<Integer> values = map.values();
		^
  symbol:   class Collection
  location: class Solution

**Comment by feiceh** [comment]
能否向我们提供一下 题号（题目链接），把信息提供完整才能有助于快速验证和精准的定位哟～

**Comment by FBMeng** [comment]
题号：
3. 无重复字符的最长子串

链接：
https://leetcode-cn.com/problems/longest-substring-without-repeating-characters/


发件人: feiceh
发送时间: 2020年6月11日 13:25
收件人: LeetCode-Feedback/LeetCode-Feedback
抄送: FBMeng; Author
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] java的Collection使用报错 (#449)

能否向我们提供一下 题号（题目链接），把信息提供完整才能有助于快速验证和精准的定位哟～

**Comment by feiceh** [comment]
需要手动 import java.util.Collection，请知晓。
