### ISSUE TITLE
Set Matrix Zeroes (#73) is not solvable in Racket

### ISSUE THREAD

**Issue by jbromley** [LeetCode-Feedback/LeetCode-Feedback#4490]
#### Your LeetCode username
jbromley

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The instructions of the problem state that the solution is to be done in-place, modifying the matrix passed into the function and not returning anything. The contract for the solution is
```
(define/contract (set-zeroes matrix)
  (-> (listof (listof exact-integer?)) void?)

  )
```
showing that the list of lists passed in must be modified. However, in Racket there are two issues that prevent the solution being returned in-place. First, Racket lists are immutable, so the list passed into the `set-zeroes` function cannot be modified. Second, the lexical context in the function has no access to the binding for matrix in the calling context, so cannot change the binding to a solution calculated in the function itself. Of course, in the `set-zeroes` function `matrix` may be rebound to a new list of lists, but this will not change the list in the calling function. In short, it is impossible to solve this problem in accordance with the instructions and contract specified.

#### Code you used for Submit/Run operation
There is no code, as solving this problem in the manner described in the problem is impossible.

#### Language used for code
Racket

#### Expected behavior
The problem should be solvable. This can be done in two ways. First, if a mutable data structure like a vector of vectors is passed to `set-zeroes`, then the function would be able to modify the passed-in matrix. The contract for such a solution would be 
```
(define/contract (set-zeroes matrix)
  (-> (vectorof (vectorof exact-integer?)) void?)
  )
```
The second possibility would be to allow the function to return a value with the following contract.
```
(define/contract (set-zeroes matrix)
  (-> (listof (listof exact-integer?)) (listof (listof exact-integer?)))
  )
```
It feels like the first option is more true to the spirit of the question. Using a vector is also much more efficient, as most list operations take linear time and so operating on a list of lists would be very inefficient.

**Comment by lc-kay** [comment]
Hi @jbromley 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jbromley 
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
