### ISSUE TITLE
Incorrect test case for *1024. Video Stitching*

### ISSUE THREAD

**Issue by deathname** [LeetCode-Feedback/LeetCode-Feedback#4494]
#### Your LeetCode username
Link : [https://leetcode.com/draco_nian/](url)
Name: draco_nian

#### Category of the bug
- [x] Incorrect Test Cases

#### Description of the bug
The output for certain test cases for the problem [https://leetcode.com/problems/video-stitching/](url) is wrong.

- Testcase:
```
[[0,5],[6,8]]
7
```
- Expected Output: `-1`
- Correct Output: `2`
- Explanation : We can take interval `[0,5] & [6,8]` which will comprises of time `[0,7]`

#### Code you used for Submit/Run operation
```
const int INF = 1e9 + 7;
class Solution {
public:
    vector<vector<int > > DP;
    int solve(int timeId, int id, int& time, vector<vector<int>>& clips) {
        int N = clips.size();
        
        
        if(id >= N) {
            return timeId > time ? 0 : INF;
        }
        
        if(timeId > time) {
            return 0;
        }
        
        if( DP[id][timeId] != -1 ) {
            return  DP[id][timeId];
        }
        
        int ans = INF;
        for(int j = id; j < N; j++) {
            if(clips[j][0] <= timeId && timeId <= clips[j][1]) {
                ans = min(ans, 1 + solve(clips[j][1] + 1, j + 1, time, clips));            
            }
        }
        return DP[id][timeId] = ans;
    }
    
    int videoStitching(vector<vector<int>>& clips, int time) {
        int N = clips.size();
        DP.resize(N, vector<int > (time+2, -1));
        sort(clips.begin(), clips.end());
        int ans = solve(0, 0, time, clips);
        return ans >= INF ? -1 : ans;
        
    }
};
```

#### Language used for code
C++

#### Expected behavior
Output for the test case is wrong.

**Comment by lc-kay** [comment]
@deathname The expected output is correct. Please check out this [discuss post](https://leetcode.com/problems/video-stitching/discuss/323712/Are-intervals-open-ended-or-close-ended) Thank you for your time.
