### ISSUE TITLE
Typos: names of arrays changed 

### ISSUE THREAD

**Issue by lindapescatore** [LeetCode-Feedback/LeetCode-Feedback#45]
https://leetcode.com/articles/trapping-rain-water/
Approach 2: Dynamic Programming

**What kind of the bug**
- [ ] problem
In the algorithm section, the names of the arrays were switched from steps 1 and 2 to the last bullet point.

- [ ] solution
Change step 4 to match previous steps. 
max_left -> left_max
max_right -> right_max
- [ ] language
English

**Describe the bug**
The names of the arrays changed.

left_max becomes max_left
and 
 right_max becomes max_right.

**what language is your code written in**
N/A this is one of your articles

**The code you submit/run**
n/a
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
![leetcodetypo](https://user-images.githubusercontent.com/3461605/76934363-42a51480-68ac-11ea-8fdd-104abf9feafb.JPG)

**Comment by CooperCooperCooper** [comment]
Hi @lindapescatore,
Thank you for raising this issue to our attention! I've filed it to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @lindapescatore,
Base on your timely feedback, we've updated all the references of variables in this article to make them consistent; in detail, we're keeping the names of "left_max" and "right_max". 

We've also taken the chance to review this article to make sure the other parts are good to go. If you have any other questions, please don't hesitate to let us know. We appreciate your support.
