### ISSUE TITLE
Question Correction

### ISSUE THREAD

**Issue by younglord69** [LeetCode-Feedback/LeetCode-Feedback#4500]
#### LeetCode Username
Mohd Soaib

#### Category of the bug
- [ ] Question

#### Description of the bug

The question description  and the examples given is incorrect, we have to only add the numbers but in question its given to add 
in reverse order and the example is explained in reverse order. 

#### Code you used for Submit/Run operation

```
public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
        int sum = 0;
        int carry = 0;
        ListNode temp = new ListNode();
        ListNode dummy = temp;
        while(l1!=null && l2!=null){
            sum = l1.val+l2.val + carry;
            carry = sum/10;
            sum = sum%10;
            ListNode node = new ListNode(sum);
            temp.next = node;
            temp = node;
            l1 =l1.next;
            l2 =l2.next;
    }

    while(l1!=null){
        sum = l1.val+carry;
        carry = sum/10;
        sum = sum%10;
        ListNode node = new ListNode(sum);
        temp.next = node;
        temp = node;
        l1 = l1.next;
    }
    while(l2!=null){
        sum = l2.val+carry;
        carry = sum/10;
        sum = sum%10;
        ListNode node = new ListNode(sum);
        temp.next = node;
        temp = node;
        l2 = l2.next;
    }
    if(carry!=0){
        ListNode node = new ListNode(carry);
        temp.next = node;
        temp = node;
    }
    return dummy.next;


    }
```

#### Language used for code

Java

#### Expected behavior

Description should be simple that we have given two linked lists we need to add digits from the linked lists and form a new linked list.

**Comment by lc-kay** [comment]
@younglord69 Please provide the problem number and title. Thank you.

**Comment by lc-kay** [comment]
Hi @younglord69 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
