### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by dmitryk-dk** [LeetCode-Feedback/LeetCode-Feedback#4501]
#### Your LeetCode username

kozlovdmitriyy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I'm trying to run my solution for arr [1,1,2] it shows me that my answer is [1,1],
but i have checked my code by tests it shows correct answer [1,2]

#### Code you used for Submit/Run operation

```
func removeDuplicates(nums []int) int {
	dups := make(map[int]struct{})
	for _, num := range nums {
		if _, ok := dups[num]; !ok {
			dups[num] = struct {}{}
		}
	}
    
	nums = []int(nil)
	for num := range dups {
		nums = append(nums, num)
	}
    
	return len(nums)
}
```

#### Language used for code

golang

#### Screenshots

<img width="1003" alt="Screenshot 2021-08-14 at 22 13 33" src="https://user-images.githubusercontent.com/12189570/129457850-2e7f7a66-e7c7-4f50-9dca-19f7d658da44.png">

**Comment by lc-kay** [comment]
<img width="1398" alt="Screen Shot 2021-08-16 at 11 44 26 AM" src="https://user-images.githubusercontent.com/70870126/129614028-821009f6-b7be-4c48-ab28-b089ac536cda.png">
@dmitryk-dk I've ran your code in 'Run Code' and it is outputting [1,1], which is incorrect. Thank you for your time.
