### ISSUE TITLE
Incorrect Test Case - 546. Remove Boxes

### ISSUE THREAD

**Issue by pallenfgcu** [LeetCode-Feedback/LeetCode-Feedback#4502]
#### Your LeetCode username
profallen

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Either I don't understand the question, or the test case is incorrect:

Input: [1,2,1,2,1]
Output: 13
Expected: 11

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
class Solution {
public:
    int removeBoxes(vector<int>& boxes) {
        int points = 0;
        vector<int> colors = vector<int>();

        for (int index = 0; index < boxes.size(); index++) {

            int color = boxes[index];

            bool exists = false;
            for (int i = 0; i < colors.size() && !exists; i++) {
                exists = colors[i] == color;
            }

            if (exists)
                continue;

            colors.push_back(color);

            int count = 1;
            for (int i = index + 1; i < boxes.size(); i++) {
                if (boxes[i] == color)
                    count++;
            }
            points += count * count;
        }

        return points;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
I understand this as 3 1's is 3 * 3 = 9 and 2 2's is 2 * 2 = 4 and 9 + 4 = 13

**Comment by lc-kay** [comment]
@pallenfgcu Please check out this [discuss post ](https://leetcode.com/problems/remove-boxes/discuss/101332/Why-not-13)for further clarification. Thank you for your time.
