### ISSUE TITLE
Missing Test Case - 546. Remove Boxes

### ISSUE THREAD

**Issue by angryronald** [LeetCode-Feedback/LeetCode-Feedback#4503]
#### Your LeetCode username
angryronald

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Input: [1,2,1,2,1]
Expected: 11 (?)
The expected result supposed to be 13 according to the problem explanation since 1 occurs 3 times and 2 occurs 2 times.
[1,2,1,2,1] --> when processing 1 (occurs 3 times) -> 3 x 3 = 9
[2,2] --> when processing 2 (occurs 2 times) -> 2 x 2 = 4
the result supposed to be 13

#### Code you used for Submit/Run operation
---
func removeBoxes(boxes []int) int {
    valueMaps := map[int]int{}
    
    for _, box := range boxes {
        valueMaps[box]++
    }
    
    var result int 
    for _, value := range valueMaps {
        result = result + (value * value)
    }
    
    return result
}
---

#### Language used for code
Go

#### Expected behavior
The expected result of the input is supposed to be 13, not 11.

#### Screenshots
![Screenshot from 2021-08-15 04-05-43](https://user-images.githubusercontent.com/7393781/129459996-cbf0ded8-92d8-47a1-ac8b-bf76e9bc9c4a.png)

#### Additional context
Only the expected result of this input

**Comment by lc-kay** [comment]
@angryronald The expected output is correct. Please check out this[ discuss post](https://leetcode.com/problems/remove-boxes/discuss/101332/Why-not-13) for further clarification. Thank you for your time.
