### ISSUE TITLE
Missing Test Case - 1968. Array With Elements Not Equal to Average of Neighbors

### ISSUE THREAD

**Issue by tan31989** [LeetCode-Feedback/LeetCode-Feedback#4508]
#### Leetcode Username
tan31989

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
**Test Case Missing**: The test cases don't capture some edge cases where the error can be caught. For instance, an array `[5,7,8,9]` if chosen would fail for uses if we simply swap the alternate numbers. 

#### Code you used for Submit/Run operation
```python
// My solution passed the problem statement, but eventually when I saw others solution,
// It made sense for a failing test case.
class Solution:
    def rearrangeArray(self, nums: List[int]) -> List[int]:
        i, n = 1, len(nums)
        while i < n-1:
            if ((nums[i-1] + nums[i+1])/2 == (nums[i] * 1.0)):
                nums[i], nums[n-1] = nums[n-1], nums[i]
            i += 1
        
        return nums
```

#### Language used for code
Python

#### Expected behavior
This solution is not ideal and should fail for some of the test cases

**Comment by lc-kay** [comment]
Hi @tan31989 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@tan31989 Thank you for your time. The team reviewed your report and noticed the code already fails on a recently added test case, so we didn't add the test case. We appreciate your support!
