### ISSUE TITLE
Wrong Testcase for Problem 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by pmahajan2698** [LeetCode-Feedback/LeetCode-Feedback#451]
#### Your LeetCode username
pmahajan2698

#### Category of the bug
Question

#### Description of the bug
WRONG TESTCASE.
I was solving this question and 32 / 33 of the test cases passed.

The one that failed was - 

2 
[-1,0] 
[-1,-1]
This doesn't seem like a valid test case. I don't feel like I can create exactly one binary tree from this.

If I take 1 as the root node, leftChild[0] = rightChild[0] = -1. Now that this tree only has one node, leftChild[1] = 0 and rightChild[1] = -1 makes no sense to me.

Please look into it and tell me if I missed something!

Thanks!

#### Code you used for Submit/Run operation

```
class Solution {
public:
  bool validateBinaryTreeNodes(int n, vector<int>& leftChild, vector<int>& rightChild) {
    queue<int> q;
    q.push(0);
    unordered_map<int,bool> visited;
    visited[0] = true;
    int i = 0;
    while (!q.empty()) {
      auto temp = q.front();
      q.pop();

      if (i == n)
	break;
      int x = leftChild[i];
      int y = rightChild[i];
      if (visited[x] || visited[y])
	return false;;
      if (x != -1) {
	q.push(x);
	visited[x] = true;
      }
      
      if (y != -1) {
	q.push(y);
	visited[y] = true;
      }
      i ++;      
    }
    if (q.empty() && i < n)
      return false;
    return true;
  }
};
```

#### Language used for code
C++

#### Expected behavior
On running the code, the judge says "Wrong Answer".
When I click it, it shows 32 / 33 test cases passed. The test case that didn't pass seems faulty.

**Comment by CooperCooperCooper** [comment]
Hi @pmahajan2698 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @pmahajan2698 ,
Thank you for your time. Our team has taken a thorough review of this issue and we found this problem was misunderstood. Please do not assume the binary tree should be rooted at 0. We appreciate your support.
