### ISSUE TITLE
Leetcode Question #142 - Linked List Cycle II

### ISSUE THREAD

**Issue by kevintang300** [LeetCode-Feedback/LeetCode-Feedback#4510]
Unclear description, function requires a node to be returned but description highlights returning an index position of where the cycle begins.

**Comment by lc-kay** [comment]
Hi @kevintang300 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kevintang300 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by kevintang300** [comment]
> Hi @kevintang300 
> 
> Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

CoderMan300
