### ISSUE TITLE
Missing Test Case - 647. Palindromic Substrings

### ISSUE THREAD

**Issue by RIPTIDEKING** [LeetCode-Feedback/LeetCode-Feedback#4511]
#### Your LeetCode username
riptideking23

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The test cases that the solution is checked against are very small. Even by using brute force it passes all the given test cases on the other hand if you tr against a custom test case of length 1000 which is in constraint. at least a few test cases of maximum length should be added in this question

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def countSubstrings(self, s: str) -> int:
        l = len(s)
        rs = s[::-1]
        
        def cntp(n):
            cnt = 0
            # print(l-n+1)
            for i in range(l-n+1):
                # print(s[i:n+i] , rs[l-n-i:l-i])
                if(s[i:n+i] == rs[l-n-i:l-i]):
                    cnt += 1; 
            # print()
            return cnt
        
        ret = 0
        for i in range(2,l+1):
            ret += cntp(i)
        ret += l
        return ret
```

#### Language used for code
python3

#### Expected behavior

i expected it to give a tle but instead it passes all the test cases

**Comment by lc-kay** [comment]
@RIPTIDEKING Please provide the exact test case that will cause this code to TLE. For such a large test case, please provide it in a .txt format. Thank you!

**Comment by RIPTIDEKING** [comment]
> @RIPTIDEKING Please provide the exact test case that will cause this code to TLE. For such a large test case, please provide it in a .txt format. Thank you!

[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7001553/testcase.txt)
@Ic-kay Each test case of length 1000 takes about 400-500 ms to solve but when submitting it took 200 ms to run 60+ test cases.
All I am suggesting is by adding few testcases of 1000 length we will be forced to apply a better approach to solve this question instead of applying a brute-force method.

**Comment by lc-kay** [comment]
Hi @RIPTIDEKING 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@RIPTIDEKING Our team has reviewed your code and the test cases and found that it is currently up to standard. Your code should pass based on our current time limit. Thank you for your time.
