### ISSUE TITLE
Missing Test Case - 1968. Array With Elements Not Equal to Average of Neighbors

### ISSUE THREAD

**Issue by Anidya** [LeetCode-Feedback/LeetCode-Feedback#4512]
#### Your LeetCode username
Anidya_Vajpayee

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug
There is an edge case that is being missed and gives a correct answer on a particular test case.

#### Code you used for Submit/Run operation
// 1968. Array With Elements Not Equal to Average of Neighbors
class Solution {
public:
    vector<int> rearrangeArray(vector<int>& nums) {
        int n = nums.size();
        
        for(int i=1; i<n-1; i++){
            int val = nums[i-1] + nums[i+1];
            if(val == 2 * nums[i])
                swap(nums[i], nums[n-1]);
        }
        
        return nums;
    }
};

#### Language used for code
C++

#### Expected behavior
To the input [7,4,3,2,1] my code gets accepted by what my code does is generate a rearrangement [7, 4, 1, 2, 3] which is incorrect. But the solution gets accepted.

#### Additional context
The missing testcase is [7,4,3,2,1]

**Comment by lc-kay** [comment]
@Anidya Please provide the submission details link to your code. Thank you!

**Comment by Anidya** [comment]
https://leetcode.com/submissions/detail/538842474/
This is the submission link of my solution.
Thank you.

**Comment by lc-kay** [comment]
@Anidya I just ran your code and it is failing on test case [10,7,5,4,3]. For a valid missing test case report, the code must be accepted and the test case will fail it. Thank you for your time.

**Comment by Anidya** [comment]
This test case might be included later because this code gave a correct
answer before during the contest.

Thank you for your time.
