### ISSUE TITLE
265. Paint House II - paint two houses different colors if only one color available

### ISSUE THREAD

**Issue by ampanasiuk** [LeetCode-Feedback/LeetCode-Feedback#4516]
#### Your LeetCode username
Movely

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem states that each house has to be colored different color. What if there are two houses (n=2) but only one color is available (k=1)? The model solution returns the answer 2147483647.

#### Code you used for Submit/Run operation

```python
class Solution:
    def minCostII(self, costs: List[List[int]]) -> int:
        return 0
"""
test case: [[1],[1]]
"""
```

#### Language used for code
Python3

#### Expected behavior

The problem statement should include one of:
- this information: "it will be possible to paint the houses this way"
- this rule: "if it's impossible, return -1" (and the model solution should return -1 instead of 2147483647), and the solution article should probably update the "The test cases here on Leetcode are all valid inputs." statement
- the constraint: k == 1 => n == 1 and the test case should not be allowed

#### Additional context

Test case that has the issue: [[1],[1]]

**Comment by lc-kay** [comment]
Hi @ampanasiuk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ampanasiuk 
Thank you for your time. Our team has fixed this issue from a previous report. We appreciate your support!

**Comment by ampanasiuk** [comment]
Hi @lc-kay,
what are the terms for awarding 100 leetcoins for the File Content Issue to Feedback Repo mission as listed on https://leetcode.com/store/ ? I can't find them in the linked forum post.
Thanks

**Comment by lc-kay** [comment]
@ampanasiuk Please check this out https://leetcode.com/discuss/feedback/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now! This report was not rewarded as the same issue was reported already by another user. We only reward the first valid issue report.
