### ISSUE TITLE
Missing Test Case - 1968. Array With Elements Not Equal to Average of Neighbors

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#4517]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[1,4,6,22,12,2]

#### Code you used for Submit/Run operation

```
class Solution:
    def rearrangeArray(self, nums: List[int]) -> List[int]:
        rst, lists = [], []
        b = 1
        while b or len(lists) > 1:
            if not b:
                lists, nums = [], lists
            b = 0
            for num in nums:
                if len(rst) < 2 or (num + rst[-2]) / 2 != rst[-1]:
                    rst.append(num)
                else:
                    lists.append(num)     

        if lists and (rst[0] + rst[1]) / 2 == lists[0]:
                return lists + rst
        else:
            return [rst[0]] + lists + rst[1:]
```

#### Language used for code

Python3

#### Expected behavior

Output: [1,2,4,6,22,12]

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. The team reviewed your report and noticed the code already fails on a recently added test case, so we didn't add the test case. We appreciate your support!
