### ISSUE TITLE
Missing Test Case - 99. Recover Binary Search Tree

### ISSUE THREAD

**Issue by jianhuoy** [LeetCode-Feedback/LeetCode-Feedback#4518]
#### Your LeetCode username
hull.young@gmail.com

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description of the question is misleading. Following is the current wording in the description: 
```You are given the root of a binary search tree (BST), where exactly two nodes of the tree were swapped by mistake ...```

A more accurate description should be:
```You are given the root of a binary search tree (BST), where values of exactly two nodes of the tree were swapped by mistake ...```

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @jianhuoy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jianhuoy 
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
