### ISSUE TITLE
617 has awkward Kotlin definitions

### ISSUE THREAD

**Issue by Rowmance** [LeetCode-Feedback/LeetCode-Feedback#452]
#### Your LeetCode username

Rowmance

#### Category of the bug
- [X] Question
- [ ] Solution
- [X] Language

#### Description of the bug

The model definitions in 617 in Kotlin aren't what you'd expect in the Kotlin world and are a bit awkward to use. The Kotlin definition given in 617 is:
```kotlin
/**
 * Definition for a binary tree node.
 * class TreeNode(var `val`: Int = 0) {
 *     var left: TreeNode? = null
 *     var right: TreeNode? = null
 * }
 */
```
Which needs to be used as follows:
```kotlin
val x = TreeNode(0)
x.left = TreeNode(1)
x.right = TreeNode(2)
val v = x.`val`
```

#### Language used for code

Kotlin

#### Expected behavior

A more idiomatic use of Kotlins properties and the avoidance of the `val` keyword as a property name. For example,
```kotlin
data class TreeNode(
    var value: Int = 0,
    var left: TreeNode? = null,
    var right: TreeNode? = null
)
```
Could be used in any of the following, preferable ways:
```kotlin
val x = TreeNode(0)
val y = TreeNode(0, null, TreeNode(0))
val z = TreeNode(
    value = 0,
    right = TreeNode()
)
```

#### Additional context

I suspect this applies to other questions (and perhaps other languages) too, so I don't know to what extent it can be addressed (if at all), especially retrospectively. My experience so far in doing questions in both JS and Java though is that the models aren't quite so non-idiomatic.

**Comment by CooperCooperCooper** [comment]
Hi @Rowmance ,
Thank you for your time. Our team has taken a thorough look at this issue. We have decided to hold on to the fix for now due to various factors including our support bandwidth. We appreciate your support.
