### ISSUE TITLE
76. Minimum Window Substring - optimizing space

### ISSUE THREAD

**Issue by mdtareque** [LeetCode-Feedback/LeetCode-Feedback#4520]
#### Your LeetCode username
mtk20

#### Category of the bug
Not a bug, but improvement to space complexity.
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Not a bug, but a major improvement in space complexity of a solution.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
Java

#### Expected behavior
Space complexity reduces from O(|T| + |S|) to O(2*|T|) which is huge since s can be large.

#### Screenshots
N/A

#### Additional context
https://leetcode.com/problems/minimum-window-substring/solution/
In solution1 space complexity can be reduced by a lot. Basically the windowCount map needs to be maintained only for characters persent in `t` and not for all characters in `s`.
This minor improvement save lot of space.

Solution1, line 36 to 43 i.e.
```
    int count = windowCounts.getOrDefault(c, 0);
    windowCounts.put(c, count + 1);

    // If the frequency of the current character added equals to the
    // desired count in t then increment the formed count by 1.
    if (dictT.containsKey(c) && windowCounts.get(c).intValue() == dictT.get(c).intValue()) {
        formed++;
    }
```

should be changed to

```

    // If the frequency of the current character added equals to the
    // desired count in t then increment the formed count by 1.
    if (dictT.containsKey(c)) {
        int count = windowCounts.getOrDefault(c, 0);
        windowCounts.put(c, count + 1);
        if(windowCounts.get(c).intValue() == dictT.get(c).intValue()) {
            formed++;
        }
    }
```
Similar handling needs to be done at line 57-to-60.

Same optimization possible in Solution2 as well.

**Comment by lc-kay** [comment]
Hi @mdtareque 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by mdtareque** [comment]
@lc-kay should I add more info?

**Comment by lc-kay** [comment]
@mdtareque No, we have enough information. It may take some time for us to update the solution as we need to check the entire article to see if any other sections need to be updated as well. Thank you for your patience.

**Comment by mdtareque** [comment]
@LC-Pam when would the coins be allotted?
