### ISSUE TITLE
138. Copy List with Random Pointer Javascript runtime error

### ISSUE THREAD

**Issue by rutherfordjp8** [LeetCode-Feedback/LeetCode-Feedback#4521]
#### Your LeetCode username
rutherfordjp8

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When using javascript and regardless of what I write in the function, even if it's empty, return the original input or anything, I receive a javascript runtime issue below. I've also checked the discussion and it seems others have also had the same issue.

```
Line 160 in solution.js
          nextHash.set(now, now.next);
                                ^
TypeError: Cannot read property 'next' of undefined
    Line 160: Char 33 in solution.js (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 34: Char 26 in solution.js (Object.<anonymous>)
    Line 1251: Char 30 in loader.js (Module._compile)
    Line 1272: Char 10 in loader.js (Object.Module._extensions..js)
    Line 1100: Char 32 in loader.js (Module.load)
    Line 962: Char 14 in loader.js (Function.Module._load)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    Line 17: Char 47 in run_main_module.js
```

#### Code you used for Submit/Run operation

Regardless of what is in the function, I receive an error. 
```
138. Copy List with Random Pointer
var copyRandomList = function(head) {
    return head;
};
```

#### Language used for code
JavaScript

#### Expected behavior

The code should run and show the output

#### Screenshots

<img width="966" alt="Screen Shot 2021-08-15 at 10 34 02 PM" src="https://user-images.githubusercontent.com/22592177/129515947-2e7bc94e-30fb-4b1d-8169-dae5a5f15da0.png">

<img width="944" alt="Screen Shot 2021-08-15 at 10 34 10 PM" src="https://user-images.githubusercontent.com/22592177/129515752-6e8e634b-d7a9-42cf-abe4-5b03a4f9cd7e.png">

**Comment by lc-kay** [comment]
@rutherfordjp8 I was able to find several accepted Javascript codes in the discuss section. Please check them out:

- https://leetcode.com/problems/copy-list-with-random-pointer/discuss/1407633/Javascript-O(n)-solution
- https://leetcode.com/problems/copy-list-with-random-pointer/discuss/1387257/Clean-JavaScript-Solution
- https://leetcode.com/problems/copy-list-with-random-pointer/discuss/1380101/JavaScript-Hashtable-Solution
- https://leetcode.com/problems/copy-list-with-random-pointer/discuss/1379340/O(N)-solution-javascript-recurssion

Please let me know if you still believe there's an issue. Thank you for your time.

**Comment by rutherfordjp8** [comment]
@lc-kay 
Hello, Please try running the code. Maybe they were accepted in the past but they do not work now.
I copied and pasted those into the code field and I still receive the same error.

Please reopen the ticket as the issue still exists.

**Comment by lc-kay** [comment]
@rutherfordjp8 Please clear all cache and cookies and run the codes I provided. They are all accepted right now.

**Comment by rutherfordjp8** [comment]
Hello @Ic-kay!

Thank you for your suggesition! After I cleared my cache it fixed the issue. I'm very curious as to what was breaking it and why it was only that question for me but regardless I appreciate the help!
