### ISSUE TITLE
Invalid Test cases present in 213. House Robber II

### ISSUE THREAD

**Issue by tharun49** [LeetCode-Feedback/LeetCode-Feedback#4524]
#### Your LeetCode username

Tharun49

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Constraints in the question state that input array is circular. I tested manually with a non-circular array and the test case was
accepted and result was shown. So issue is that we are accepting incorrect test cases in manual testing!

#### Code you used for Submit/Run operation

```class Solution(object):
    def rob(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        d ={}
        return self.find(nums,d)
    
    def find(self, nums,d):
        if not(nums):
            return 0
        if tuple(nums) in d:
            return d[tuple(nums)]
        r = 0
        l = nums[0]+self.find(nums[2:],d)
        if len(nums)>1:
            r = nums[1]+self.find(nums[3:],d)
        d[tuple(nums)] = max(r,l)
        return d[tuple(nums)] 
```

#### Language used for code

Python

#### Expected behavior

It should error out saying that test case is invalid.

#### Screenshots

![image](https://user-images.githubusercontent.com/88381274/129536053-11f2b781-2850-41d0-9bfa-9c97d65522eb.png)

#### Additional context

As you can see it accepted the input array [1,2,3,4] Which is violating the constraint that input array should be circular.
Which is not in the screenshot provided. Please take appropriate measures for the same.

**Comment by lc-kay** [comment]
Hi @tharun49 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@tharun49 A circular array is means the next element of nums[nums.length - 1] is nums[0]. Therefore, the input is correct. Thank you for your time.
