### ISSUE TITLE
Missing Test Case - 987. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by apoorva-ard** [LeetCode-Feedback/LeetCode-Feedback#4526]
#### Your LeetCode username
apoorva_ard

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Missing test case that might fail codes that use set(C++) 
[1,2,3,4,6,6,7,8]

#### Code you used for Submit/Run operation
```
class Solution {
public:
    vector<vector<int>> verticalTraversal(TreeNode* root) {
        map<int, vector<int> > m;  // when iterate map, key is already the order of x-axis
        queue<pair<int, TreeNode*> > q; // for level traversal
        q.push(make_pair(0, root));  // root default x-axis is 0
        while(!q.empty()) {
            set<pair<int, int> > tmp;  // k: x-axis, v:val Already solved the case when the position is ths same
            int len=q.size();
            for(int i=0;i<len;++i) {
                auto p=q.front();q.pop();
                tmp.insert(make_pair(p.first, p.second->val));
                if (p.second->left) q.push(make_pair(p.first-1, p.second->left));
                if (p.second->right) q.push(make_pair(p.first+1, p.second->right));
            }

            for(auto p : tmp) m[p.first].push_back(p.second);
        }

        vector<vector<int> > res;
        for(auto kv : m) res.push_back(kv.second);
        return res;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
Expected o/p : [[8],[4],[2],[1,6,6],[3],[7]]
Actual o/p     : [[8],[4],[2],[1,6],[3],[7]]

#### Screenshots
Using set ignores duplicate values that are in the same row and col. 
![image](https://user-images.githubusercontent.com/63531883/129580522-cdcf4c64-9f8f-4d42-8d83-79c4cfb3f589.png)

Here both 6s are in the same and row and col. When used set, only one 6 will be shown in output.

**Comment by lc-kay** [comment]
@apoorva-ard The code you provided already fails on the test case [3,1,4,0,2,2]. For a valid missing test case report, please provide an accepted code that will be failed by the new test case. Thank you.

**Comment by lc-kay** [comment]
Hi @apoorva-ard 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
