### ISSUE TITLE
Incorrect Solution - 265. Paint House II

### ISSUE THREAD

**Issue by thewozjesse** [LeetCode-Feedback/LeetCode-Feedback#4527]
#### Your LeetCode username
twjesse

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The recommended python solution "Approach 2: Dynamic Programming" has an incorrectly-named dictionary key.

Line 12 triggers an error for `NameError: name 'house_number' is not defined`:
`costs[house_number][color] += best`

Should be:
`costs[house][color] += best`

#### Code you used for Submit/Run operation

```
def minCostII(self, costs: List[List[int]]) -> int:

    n = len(costs)
    if n == 0: return 0
    k = len(costs[0])

    for house in range(1, n):
        for color in range(k):
            best = math.inf
            for previous_color in range(k):
                if color == previous_color: continue
                best = min(best, costs[house - 1][previous_color])
            costs[house_number][color] += best

    return min(costs[-1])
```

#### Language used for code
Python

#### Expected behavior
Using the key `house` allows the solution to run without an exception

**Comment by lc-kay** [comment]
Hi @thewozjesse 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @thewozjesse 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
