### ISSUE TITLE
Incomplete Test Cases - Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by cherrygoh** [LeetCode-Feedback/LeetCode-Feedback#453]
#### Your LeetCode username
cherrygoh

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug
Leetcode accepts incorrect submissions to this problem because its test cases are incomplete.

#### Code you used for Submit/Run operation

```
public class Solution {
    public ListNode getIntersectionNode(ListNode headA, ListNode headB) {
        HashMap<Integer, ListNode> visited = new HashMap();
        
        while (headA != null) {
            visited.put(headA.val, headA);
            headA = headA.next;
        }
        
        while (headB != null) {
            if (visited.containsKey(headB.val) && visited.get(headB.val) == headB) return headB;
            
            headB = headB.next;
        }
        
        return null;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Submission should not have passed. Code **should** have been tested against a test input such as: 
```
4
[2, 2, 4, 5, 4]
[2, 2, 4, 5, 4]
2
2
```

#### Additional context

https://leetcode.com/explore/interview/card/top-interview-questions-medium/107/linked-list/785/

**Comment by CooperCooperCooper** [comment]
Hi @cherrygoh ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @cherrygoh ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
