### ISSUE TITLE
Missing test case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by AparnaRajagopal** [LeetCode-Feedback/LeetCode-Feedback#4532]
#### Your LeetCode username
aparnaraj2696

#### Category of the bug
Missing Test Cases 

#### Description of the bug
Kindly refer below for my solution. As mentioned in the comments(in bold), if you check line numbers 1,2, and 3, there is a probability of getting ArrayIndexOutOfBoundsException as my loop starts from 1 and if I try to access i-2 i.e., -1 when i=1. 

#### Code you used for Submit/Run operation
```
public boolean isMatch(String s, String p) {
        //return s.matches(p);
        boolean dp[][]=new boolean[s.length()+1][p.length()+1];
       
        dp[0][0]=true;//when both pattern and string are empty
       
        //if string is empty but pattern is present
        for(int i=1;i<=p.length();i++){
            if(p.charAt(i-1)=='*'){
                dp[0][i]=dp[0][i-2]; **//LINE NO 1**
            }
        }
       
        for(int i=1;i<=s.length();i++){
            for(int j=1;j<=p.length();j++){
                if(s.charAt(i-1)==p.charAt(j-1) || p.charAt(j-1)=='.'){
                    dp[i][j]=dp[i-1][j-1];
                }else if(p.charAt(j-1)=='*'){
                    if(s.charAt(i-1)!=p.charAt(j-2) && p.charAt(j-2)!='.'){  **//LINE NO 2**
                        dp[i][j]=dp[i][j-2];
                    }else{
                        dp[i][j]=dp[i][j-1]||dp[i-1][j]||dp[i][j-2];  **//LINE NO 3**
                    }
                }
            }
        }
       
        return dp[s.length()][p.length()];
}
```

#### Language used for code
Java

#### Expected behavior
I have already submitted the solution for this particular problem and it has been accepted. But, if you check line numbers 1,2, and 3(as mentioned in the above code comments -in bold), there is a probability of getting ArrayIndexOutOfBoundsException as my loop starts from 1 and if I try to access i-2 i.e., -1 when i=1. 

#### Screenshots
![image](https://user-images.githubusercontent.com/28507622/129701149-4812a4d3-e2ae-49f4-890a-907d50194d63.png)

**Comment by lc-kay** [comment]
@AparnaRajagopal Please provide the exact test case that will cause your solution to fail. Thank you!

**Comment by lc-kay** [comment]
Hi @AparnaRajagopal 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
