### ISSUE TITLE
Test Case Error - 1448. Count Good Nodes in Binary Tree

### ISSUE THREAD

**Issue by skully-coder** [LeetCode-Feedback/LeetCode-Feedback#4533]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

When evaluating the test case for question *1448. Count Good Nodes in Binary Tree*, I am receiving an error while submitting.
The test case:  
[3,3,null,4,2]

While running this test case customly, it provides the correct solution, but on submitting the code it throws an error saying that the code returned 0 instead of 3.

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    int goodNodes(TreeNode* root) {
        static int maxFromRoot=INT_MIN;
        if( root == NULL) return NULL; 
        int count = 0;
        if( root->val >= maxFromRoot){ 
            count++;
            maxFromRoot = root->val;
        }
        count += goodNodes( root->left);
        count += goodNodes( root->right);
        return count;
    }
};
```

#### Expected behavior

The expected behaviour is on submitting the code the above-mentioned test case must be passed, as shown in the screenshots below.

#### Screenshots

![image](https://user-images.githubusercontent.com/55917548/129720520-a8c18006-ae3f-42de-b46a-53f67aace63e.png)
![image](https://user-images.githubusercontent.com/55917548/129720651-1355abdf-a75c-41af-b0e4-c88ae4921e08.png)

**Comment by lc-kay** [comment]
Hi @skully-coder 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
