### ISSUE TITLE
Missing Test Case / Constraint - 265. Paint House II

### ISSUE THREAD

**Issue by ureridu** [LeetCode-Feedback/LeetCode-Feedback#4536]
#### Your LeetCode username
ureridu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1] Missing Test Cases 

#### Description of the bug
Question is missing constraint k > 1 when n > 1

Input:

> [[1],[2]]

result:

> 2147483647

#### Expected behavior

The problem states that two consecutive houses cannot be the same color, but the problem allows test cases where this constraint cannot be met, for example:
> [[1],[2]]

which yields max int as the expected answer instead of null, or ideally, invalid test case

**Comment by lc-kay** [comment]
Hi @ureridu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ureridu 
Thank you for your time. Our team has fixed this from a previous report. We appreciate your support!
