### ISSUE TITLE
316. Remove Duplicate Letters contain wrong test cases

### ISSUE THREAD

**Issue by jaugust-03** [LeetCode-Feedback/LeetCode-Feedback#4537]
The results are supposed to be in lexicographical order but the 2nd example is not in lexicographical order i.e., "acdb" which should have been "abcd"
![image](https://user-images.githubusercontent.com/85280098/129813197-8f8d2213-8f0b-4c1c-8a3f-ee6bc581de0c.png)

**Comment by lc-kay** [comment]
@jaugust-03 The expected output is correct. Please check out this discuss post: https://leetcode.com/problems/remove-duplicate-letters/discuss/76764/Is-it-me-or-is-the-2nd-example-(and-test-case)-are-wrong Thank you for your time.
