### ISSUE TITLE
Missing Test Case - 1941. Check if All Characters Have Equal Number of Occurrences

### ISSUE THREAD

**Issue by keithgee** [LeetCode-Feedback/LeetCode-Feedback#4538]
#### Your LeetCode username

keithg

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

One of the faster solutions I found in the Submission Detail page's Accepted Solutions Runtime Distribution section passes all of the current test cases, but would fail the following test case:

"abcdefghijklmnopqrstuvwxyzz"

The solution that's currently accepted uses a 26 position array to count the number of occurrences of each lowercase English letter. The code then converts the array of counts into a set, and if the number of values in the set is 1 or 2, the solution returns true. It returns true when the count is 2 in order to account for characters that did not occur in the string at all - the array has counts of 0 for those letters.

The solution therefore returns true for the test case "abcdefghijklmnopqrstuvwxyzz", where it should return false. There is one and only one occurrence of all of the 25 lowercase English letters except for z, which occurs twice.  

#### Code you used for Submit/Run operation

This code is copy/pasted from an example on the Accepted Solutions Runtime Distribution page.
```
class Solution {
    func areOccurrencesEqual(_ s: String) -> Bool {
        var arrOfChars: [Int] = Array(repeating: 0, count: 26)
        
        for char in s {
            let charAscii = Int((char.asciiValue ?? 0) - 97)
            // print(charAscii)
            arrOfChars[charAscii] += 1
        }
        let setOfChars = Set(arrOfChars)
        
        // print(setOfChars)
        if setOfChars.count == 2 || setOfChars.count == 1 {
            return true
        }
        return false   
    }
}


```

#### Language used for code

Swift

#### Expected behavior

Test case ""abcdefghijklmnopqrstuvwxyzz" should be included in the test cases so that code above fails when it returns true. A correct solution returns false for this test case. 

Currently the above incorrect code is Accepted. I'd like for it to receive a Wrong Answer status instead.

**Comment by lc-kay** [comment]
Hi @keithgee 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @keithgee 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
