### ISSUE TITLE
Missing Test Case - 1448. Count Good Nodes in Binary Tree

### ISSUE THREAD

**Issue by Samhitha-Jasti** [LeetCode-Feedback/LeetCode-Feedback#4540]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Samhitha-Jasti Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
