### ISSUE TITLE
Submission  problem

### ISSUE THREAD

**Issue by kido5285** [LeetCode-Feedback/LeetCode-Feedback#4542]
#### Category of the bug
- [ ] Question
- [✔] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I click the "Run Code" button, it will pass the test case. But when I click "Submit" button, none of my previous passed test cases pass...

#### Code you used for Submit/Run operation

```
// Decode Ways
let result = 0;
var numDecodings = function(s) {
    find(s);
    return result;
};

const find = (s, memo = {}) => {
    if(s in memo) return memo[s];
    if(s.charAt(0) === "0") return;
    if(s.length <= 1){
        result++;
        return;
    }
    
    for(let i=0; i<Math.min(2,s.length); i++){
        let val = parseInt(s.substring(0, i+1));
        if(val >= 1 && val <= 26){
            memo[i+1] = val;
            find(s.substring(i+1), memo)
            console.log(memo);
        }
    }
}
```

#### Language used for code

Javascript

#### Expected behavior

To pass the test case

#### Screenshots

https://youtu.be/_fFVAJEVqGA <= This video shows the issue

**Comment by lc-kay** [comment]
Hi @kido5285 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
