### ISSUE TITLE
Missing Test Case - 32. Longest Valid Parentheses

### ISSUE THREAD

**Issue by shuvava** [LeetCode-Feedback/LeetCode-Feedback#4543]
#### Your LeetCode username
shuvava

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug
in one of test cases for Longest Valid Parentheses problem you expected incorrect answer:
for test case "()(()" the longest valid (well-formed) parentheses substring is "()()" with length 4, currently this test case  expected 2

#### Expected behavior
for test case "()(()" the longest valid (well-formed) parentheses substring is "()()" with length 4

**Comment by lc-kay** [comment]
@shuvava The expected output is correct. Please check out the following discuss posts.
https://leetcode.com/problems/longest-valid-parentheses/discuss/14249/Someone-please-explain-why-%22()(()%22-is-2-Isn't-it-suppose-to-be-4
https://leetcode.com/problems/longest-valid-parentheses/discuss/499779/%22()(()%22-is-answer-2

Thank you for your time.
