### ISSUE TITLE
Misspelled word - 953. Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by pratik-p** [LeetCode-Feedback/LeetCode-Feedback#4545]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Misspelled word -
Expected: lexicographically
Actual: lexicographicaly

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @pratik-p 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratik-p 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
