### ISSUE TITLE
缺少测试用例：题号：26

### ISSUE THREAD

**Issue by hellowmq** [LeetCode-Feedback/LeetCode-Feedback#4546]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
hellowmq

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [X] 缺少测试用例

**描述**

> 题目描述中给出的条件为
> 给你一个有序数组 nums ，请你 原地 删除重复出现的元素，使每个元素 只出现一次 ，返回删除后数组的新长度。

```java
// nums 是以“引用”方式传递的。也就是说，不对实参做任何拷贝
int len = removeDuplicates(nums);

// 在函数里修改输入数组对于调用者是可见的。
// 根据你的函数返回的长度, 它会打印出数组中 该长度范围内 的所有元素。
for (int i = 0; i < len; i++) {
    print(nums[i]);
}
```

> 0 <= nums.length <= 3 * 10^4
> -10^4 <= nums[i] <= 10^4
> nums 已按升序排列

目前测试用例的验证逻辑不够完善，使用测试用例进行验证空数组时，令 `int[] nums = {};` 
依照题意应当输出 0，
使用下面的代码可以通过目前 LeetCode 的所有 Case，但在空数组这个自定义 Case 实际上返回任何值都允许通过。

这种返回值实际上不符合`删除后数组的新长度` 这个返回值的预期。

**你使用的语言**
Java

**你提交或者运行的代码**
```
// Two Sum
class Solution {
    public int removeDuplicates(int[] nums) {
        if (nums.length == 0) {
            // 返回任何值都可以被接受
            return 10000;
        }
        int left = 0;
        int right = 0;
        while (right < nums.length) {
            if (nums[right] != nums[left]) {
                if (left++ != right) {
                    nums[left] = nums[right];
                }
            }
            right++;
        }
        return ++left;
    }
}
```

**期望行为**
removeDuplicates() 的实现在空数组情况下应当返回 `0` 而非其它值。

**屏幕截图**
似乎检查测试用例时，没有对方法返回值进行检查？
<img width="474" alt="截屏2021-08-19 上午3 29 05" src="https://user-images.githubusercontent.com/33039572/129960204-1c8da7a1-2c04-43f4-afff-571f6443c632.png">
<img width="388" alt="截屏2021-08-19 上午3 29 24" src="https://user-images.githubusercontent.com/33039572/129960240-9f82f15f-1e08-416c-968f-81413b820eb4.png">

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by LC-Sue** [comment]
Hi @hellowmq 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hellowmq 
Thank you for your time. The test case no longer exists. We appreciate your support!
