### ISSUE TITLE
Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by ashwini47** [LeetCode-Feedback/LeetCode-Feedback#4547]
Language of this question is really confusing and need to be clarified 
Example are also vage 

#### Your LeetCode username
user9184Q

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @ashwini47 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ashwini47 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
