### ISSUE TITLE
Missing Testcase - 29. Divide Two Integers

### ISSUE THREAD

**Issue by dgoelitz** [LeetCode-Feedback/LeetCode-Feedback#4549]
Question
Divide Two Integers
Reason
Hi, The problem accepted my solution when I did not make sure the answer was above -2147483648.
Code
/**
 * @param {number} dividend
 * @param {number} divisor
 * @return {number}
 */
var divide = function(dividend, divisor) {
    let result = 0,
    neg = 1,
    extraDigit = 1;
    if (dividend < 0) {
        neg *= -1;
        dividend *= -1;
    }
    if (divisor < 0) {
        neg *= -1;
        divisor *= -1;
    }
    while (dividend >= divisor * 10) {
        extraDigit *= 10;
        divisor *= 10;
    }
    while (dividend >= divisor) {
        dividend -= divisor;
        result += extraDigit;
        while (dividend < divisor && extraDigit > 1) {
            divisor /= 10;
            extraDigit /= 10;
        }
    }
    result *= neg;
    result = Math.min(2147483647, result);
    return result;
};
Test Cases
Input: dividend = -2147483649, divisor = 1
Output: -2147483648

**Comment by lc-kay** [comment]
@dgoelitz Please provide the submission details link to your code. Thank you!

**Comment by dgoelitz** [comment]
Hi, is this what you need? https://leetcode.com/contribute/30662

Thank you

**Comment by lc-kay** [comment]
@dgoelitz The test case you've provided is invalid. -2147483649 is not a valid value of type integer. Therefore, we will not be adding it. Thank you for your time.
