### ISSUE TITLE
75. Sort Colors

### ISSUE THREAD

**Issue by The-KarateKid** [LeetCode-Feedback/LeetCode-Feedback#455]
#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
An acceptable naive solution for this problem is given in the Follow-Up section:

> A rather straight forward solution is a two-pass algorithm using counting sort.
First, iterate the array counting number of 0's, 1's, and 2's, then overwrite array with total number of 0's, then 1's and followed by 2's.

#### Expected behavior

The placement of this information in the problem acts as a spoiler. It would be much better placed as a Hint since they are hidden, or as an acceptable Solution.

**Comment by CooperCooperCooper** [comment]
Hi @The-KarateKid ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @The-KarateKid ,
Thank you for your time. Our engineers want to share that, although this information a bit of a "spoiler", it's in the follow-up section which is fine. We appreciate your support.
