### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by karnurmax** [LeetCode-Feedback/LeetCode-Feedback#4551]
#### Your LeetCode username
jalagash-it

#### Category of the bug
- [x] Question
- [x] Wrong test case

#### Description of the bug
I think it's wrong test case
[5,4,6,null,null,3,7]
https://leetcode.com/submissions/detail/540841954/?from=explore&item_id=2874

#### Code you used for Submit/Run operation
```
var isValidBST = function(n) {
    if(!n)return true;
    if(n.left && n.left.val >= n.val) return false;
    if(n.right && n.right.val <= n.val) return false;
    return isValidBST(n.left) && isValidBST(n.right);
};
```

#### Language used for code
JavaScript

#### Screenshots
![image](https://user-images.githubusercontent.com/8898412/130034600-87df5868-95a9-4749-a6c5-ec31ef742389.png)

**Comment by azhar1038** [comment]
No, it is not a valid BST. It also confused me at first.

In your case, for the root (5), right sub-tree contains [3,6,7].
But the right subtree of a node should contain only nodes with keys greater than the node's key.
Since 3 < 5, therefore, it is not a valid BST
