### ISSUE TITLE
29. Divide Two Integers - Approach 2: Repeated Exponential Searches

### ISSUE THREAD

**Issue by ATsahikian** [LeetCode-Feedback/LeetCode-Feedback#4553]
#### Your LeetCode username
tsagikyan

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Wrong complexity analysis for approach 2.
It's not  O(log^2(N)) but O(2*log(N))

O(log(N) + log(N/2) + log(N/4) + log(N/8) + .. ) = O(2*log(N))

**Comment by lc-kay** [comment]
Hi @ATsahikian 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
