### ISSUE TITLE
Missing Test Case - 1967. Number of Strings That Appear as Substrings in Word

### ISSUE THREAD

**Issue by Anshulkakraniya** [LeetCode-Feedback/LeetCode-Feedback#4555]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Incomplete test cases result in acceptance of a solution which is otherwise incorrect for said test case.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int numOfStrings(vector<string>& patterns, string word) {
    int count =0;
    for(auto &str:patterns) {
        if(check(str, word))
            count++;
        }
        return count;
    }
    
    bool check(string &str, string word){
        int strSize = str.length();
        int i = 0;
        for(char &ch:word){
            if(ch==str[i]) i++;
            else if(i>0){
                if(str[i-1]==ch) continue;
                else i--;
            }
            if(i==strSize) break;
        }
        return (i==strSize) ?true :false;
    }   
};
```

#### Language used for code
C++

#### Expected behavior
It should have given error as described in the screenshot where expected result is different from code result. However, the incomplete test cases fail to do so. The test case in question is:
#### Screenshots
![leetbug](https://user-images.githubusercontent.com/32309508/130097237-713270c3-c653-4dda-a8ab-a0e07d69a40f.PNG)

**Comment by lc-kay** [comment]
Hi @Anshulkakraniya 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Anshulkakraniya 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Anshulkakraniya** [comment]
Hi, Thanks. My leetcode ID is TwinkleToest

**Comment by Anshulkakraniya** [comment]
> Hi @Anshulkakraniya
> Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

@lc-kay Hi, Thanks. My LeetCode ID is TwinkleToest

**Comment by Anshulkakraniya** [comment]
@lc-kay My leetcode ID is TwinkleToest. Thank you!

**Comment by Anshulkakraniya** [comment]
> Hi @Anshulkakraniya
> Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

Hey @lc-kay, Can I know until when will I receive the LeetCoins? I haven't received it till now.
