### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by azabluda** [LeetCode-Feedback/LeetCode-Feedback#4556]
#### Your LeetCode username
azabluda

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The following code is accepted by the current test set, yet there exists a test case which gives 'Wrong Answer' 
> 0.999999999
> -2147483648

#### Code you used for Submit/Run operation

```cs
public class Solution {
    public double MyPow(double x, int n) {
        if (n == int.MinValue) return Math.Abs(x) == 1 ? 1 : 0;
        bool negative = n < 0;
        double res = 1;
        for (n = Math.Abs(n); n > 0; n /= 2, x = x * x)
            if (n % 2 != 0) res *= x;
        return negative ? 1.0 / res : res;
    }
}
```

#### Language used for code

C#

#### Expected behavior

Either the test case or the code should be rejected.

#### Screenshots

![image](https://user-images.githubusercontent.com/7567733/130101232-54cabb78-713a-4b40-85c2-0920a583757d.png)

**Comment by lc-kay** [comment]
Hi @azabluda 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @azabluda 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
