### ISSUE TITLE
Missing Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by Ayushi0901** [LeetCode-Feedback/LeetCode-Feedback#4557]
#### Your LeetCode username
srivastavaayushi139

#### Category of the bug
- [ ] Question

#### Description of the bug

<b>414. Third Maximum Number </b> examples are not clearly described
there should be one more example

i.e.
Input: nums = [4,3,2,1]
Output: 2
Explanation: The third maximum is 2.

**Comment by Ayushi0901** [comment]
Example Addition

**Comment by lc-kay** [comment]
Hi @Ayushi0901 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Ayushi0901 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
