### ISSUE TITLE
Test Case Question. - 36. Valid Sudoku

### ISSUE THREAD

**Issue by Kristopher-Jung** [LeetCode-Feedback/LeetCode-Feedback#4558]
#### Your LeetCode username
Kristopher-Jung

#### Category of the bug
_**- [ ] Question**_
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I do not understand why this test case expected a false
[[".",".",".",".","5",".",".","1","."],[".","4",".","3",".",".",".",".","."],[".",".",".",".",".","3",".",".","1"],["8",".",".",".",".",".",".","2","."],[".",".","2",".","7",".",".",".","."],[".","1","5",".",".",".",".",".","."],[".",".",".",".",".","2",".",".","."],[".","2",".","9",".",".",".",".","."],[".",".","4",".",".",".",".",".","."]]

.   .   .   .   5   .   .   1   .
.   4   .   3   .   .   .   .   .
.   .   .   .   .   3   .   .   1
8   .   .   .   .   .   .   2   .
.   .   2   .   7   .   .   .   .
.   1   5   .   .   .   .   .   .
.   .   .   .   .   2   .   .   .
.   2   .   9   .   .   .   .   .
.   .   4   .   .   .   .   .   .

Sudoku rule:
Each row must contain the digits 1-9 without repetition.
Each column must contain the digits 1-9 without repetition.
Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isValidSudoku(char[][] board) {
        return isValidSudokuPart(board, 0,3,0,3) && isValidSudokuPart(board, 0,3,3,6) && isValidSudokuPart(board, 0,3,6,9) &&
            isValidSudokuPart(board, 3,6,0,3) && isValidSudokuPart(board, 3,6,3,6) && isValidSudokuPart(board, 3,6,6,9) &&
            isValidSudokuPart(board, 6,9,0,3) && isValidSudokuPart(board, 6,9,3,6) && isValidSudokuPart(board, 6,9,6,9) &&
            isValidSudokuPart(board, 0,9,0,9);
    }
    
    public boolean isValidSudokuPart(char[][] board, int rstart, int rend, int cstart, int cend) {
        Map<Integer, List<Character>> rowNumbsMap = new HashMap<>();
        Map<Integer, List<Character>> colNumbsMap = new HashMap<>();
        
        for(int i = rstart; i < rend; i++) {
            // boolean isRowScanned = false;
            for(int j = cstart; j < cend; j++) {
                //scan cols of row i
                if(rowNumbsMap.containsKey(i)) {
                    if(rowNumbsMap.get(i).contains(board[i][j])){
                        return false;
                    } else {
                        if(board[i][j] != '.'){
                            rowNumbsMap.get(i).add(board[i][j]);
                        }
                    }
                } else {
                    rowNumbsMap.put(i, new ArrayList<Character>());
                    if(board[i][j] != '.'){
                        rowNumbsMap.get(i).add(board[i][j]);
                    }
                }
                //scan rows of col j
                // if(!isRowScanned){
                    if(colNumbsMap.containsKey(j)) {
                        if(colNumbsMap.get(j).contains(board[i][j])) {
                            return false;
                        } else {
                            if(board[i][j] != '.'){
                                colNumbsMap.get(j).add(board[i][j]);
                            }
                        }
                    } else {
                        colNumbsMap.put(j, new ArrayList<Character>());
                        if(board[i][j] != '.'){
                            colNumbsMap.get(j).add(board[i][j]);
                        }
                    }
                //     isRowScanned = true;
                // }
            }
        }
        System.out.println("rowNumbsMap"+rowNumbsMap+" - " + rstart +","+rend+","+cstart+","+cend);
        System.out.println("colNumbsMap"+colNumbsMap+" - " + rstart +","+rend+","+cstart+","+cend);
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior
I dont really understand the expected behavior. thats why I am asking.

#### Screenshots
![image](https://user-images.githubusercontent.com/35267985/130189383-18a45265-c0b2-4702-8030-953709eb0078.png)

#### Additional context
https://leetcode.com/submissions/detail/541306462/

**Comment by su225** [comment]
In the second 3x3 group, i.e rows 1 to 3 and cols 4 to 6 (1-indexed), 3 is repeated. So it is not a valid sudoku board. Hence it is false. This is a valid test case. 
```
. 5 .
3 . .
. . 3
```
I have isolated that group for your reference.

**Comment by Kristopher-Jung** [comment]
> In the second 3x3 group, i.e rows 1 to 3 and cols 4 to 6 (1-indexed), 3 is repeated. So it is not a valid sudoku board. Hence it is false. This is a valid test case.
> 
> ```
> . 5 .
> 3 . .
> . . 3
> ```
> 
> I have isolated that group for your reference.

oh.  not repeating on the same row or column for those 3x3??
