### ISSUE TITLE
1971. Find if Path Exists in Graph - Minor mistake in problem description

### ISSUE THREAD

**Issue by varian97** [LeetCode-Feedback/LeetCode-Feedback#4559]
#### Your LeetCode username
varian97

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
From the problem description (first sentence): 
```
There is a bi-directional graph with n vertices, where each vertex is labeled from 0 to n - 1 (inclusive).
The edges in the graph are represented as a 2D integer array edges, where each edges[i] = [ui, vi].
```
But if you read the problem constraints at the bottom of the problem, it says `1 <= ui, vi <= n - 1`. I think the correct one is `0 <= ui, vi <= n - 1`

#### Code you used for Submit/Run operation

```
class Solution:
    def validPath(self, n: int, edges: List[List[int]], start: int, end: int) -> bool:
        path = {x: [] for x in range(n)}
        for edge in edges:
            _from = edge[0]
            to = edge[1]
            
            path[_from].append(to)
            path[to].append(_from)
            
        visited = [False] * n
        self.dfs(path, visited, start)
        
        return visited[end]
    
    def dfs(self, graph, visited, start):
        visited[start] = True
        
        for neighbor in graph[start]:
            if not visited[neighbor]:
                self.dfs(graph, visited, neighbor)
```

#### Language used for code
Python3

#### Expected behavior
It is just a problem description issue, no unexpected behavior.

#### Screenshots
![image](https://user-images.githubusercontent.com/15712645/130229336-f7b119a6-c9de-4e3e-9028-de1aa2d28c51.png)

**Comment by lc-kay** [comment]
Hi @varian97 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @varian97 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
