### ISSUE TITLE
Invalid Test Case in Alien Dictionary

### ISSUE THREAD

**Issue by wilderfield** [LeetCode-Feedback/LeetCode-Feedback#456]
#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

There is an invalid test case in the evaluation of this question.
The question states:
words are sorted lexicographically by the rules of this new language

However, this test case is not correctly sorted.
[[abc],[ab]] c should not come before nothing.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

Test Case:
["abc","ab"]

**Comment by CooperCooperCooper** [comment]
Hi @wilderfield ,
Thank you for your time. Our engineers thoroughly reviewed this issue and recommend checking out the third example of this problem. We appreciate your support.

**Comment by wilderfield** [comment]
@CooperCooperCooper so the description of the problem conflicts with the example given. I honestly think this problem is complicated enough. You don't need to force the user to additionally screen the input for validity.

**Comment by lc-kate** [comment]
Hi @wilderfield ,
Thank you for your feedback. Our engineer thoroughly reviewed your suggestion and found it is incorrect. I am sorry about this and thank you again for your support.
