### ISSUE TITLE
Missing Test Case - 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by isadukovskiy** [LeetCode-Feedback/LeetCode-Feedback#4560]
#### Your LeetCode username

isadukovskiy@gmail.com

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

There should be a test case similar to
[1,1,1,1,1,1,1,1,<repeat many times>]
1
basically a long array consisting of the same number which is also a target
my solution was accepted when submitted when it should have timed out on this test case

#### Code you used for Submit/Run operation

```
public class Solution {
    private int[] _output = new int[]{-1, -1};
    private int _target;
  
    public int[] SearchRange(int[] nums, int target) 
    {      
      _target = target;
      if (nums.Length == 0)
        return _output;
      Find(nums, 0, nums.Length - 1);
      return _output;
    }
  
    private void Find(int[] nums, int start, int end)
    {    
      Console.WriteLine("test");
      if (nums[start] == _target)
      {
        _output[0] = _output[0] == -1 ? start: Math.Min(start, _output[0]);
        _output[1] = _output[1] == -1 ? start: Math.Max(start, _output[1]);
      }        
      
      if (nums[end]  == _target)
      {
        _output[0] = _output[0] == -1 ? end: Math.Min(end, _output[0]);
        _output[1] = _output[1] == -1 ? end: Math.Max(end, _output[1]);
      }        
      
      if (start >= end - 1)
        return;
      
      int mid = (end - start) / 2;
      if (_target >= nums[end - mid])
        Find(nums, end - mid, end);
      

      if (_target <= nums[start + mid])
        Find(nums, start, start + mid);      
    }
}
```

#### Language used for code

C#

#### Expected behavior

Should timeout on presented test case

**Comment by lc-kay** [comment]
@isadukovskiy The test case [1,1,1,1,1,1,1,1,] is not a valid test case because is not a valid value of type integer[]. Please provide a test case that satisfies the constraints and will fail an accepted solution. Thank you for your time.

**Comment by isadukovskiy** [comment]
Array should be with repeating integer similarly to explanation in the solution. Long array with repeating number. What exactly is not valid? My example said [1,1,1,1,1,1…] just substitute … with long array of repeating ones.
