### ISSUE TITLE
Missing Test Case - 123. Best Time to Buy and Sell Stock III

### ISSUE THREAD

**Issue by siddhart-singhal** [LeetCode-Feedback/LeetCode-Feedback#4561]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@siddhart-singhal Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
