### ISSUE TITLE
139. Work Break

### ISSUE THREAD

**Issue by purplepotatodonkey** [LeetCode-Feedback/LeetCode-Feedback#4564]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [T] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@purplepotatodonkey Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
