### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by Ashok9589** [LeetCode-Feedback/LeetCode-Feedback#4567]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

I have wrote this below mentioned code, all the given testcases are passed but when I entered a custom Testcase it failed.... strange !

#### Code you used for Submit/Run operation

```
// Find Peak Element
class Solution {
    public int findPeakElement(int[] nums) {
        
        if(nums.length == 1){
            return 0;
        }
        
        int max = Integer.MIN_VALUE;
        int ans = -1;
        
        for(int i=0; i <nums.length ; i++) {
            if(nums[i] > max){
                max = nums[i];
                ans = i;
            }
        }
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

As mentioned in the below screenshot the answer to be expected was 3 but the answer of the above code is 1

#### Screenshots

![Screenshot (343)](https://user-images.githubusercontent.com/61847405/130310850-51eb6471-65c0-446b-9698-c8412b3fcccd.png)

**Comment by lc-kay** [comment]
@Ashok9589 Both index 1 and 3 are peak elements and the problem asks you to return the index to any of the peaks. Therefore, the expected output and your output are correct. Thank you for your time.

**Comment by Ashok9589** [comment]
Hello, but it should also need to be get the same output as expected which
is not getting unlike with other testcase.

**Comment by Ashok9589** [comment]
With all due respect I know due to technical limitations we can only print
only one of those outputs. But as we can see in other testcases any of the
output is accepted but in this particular testcase only that output is
accepted no else rather than that.

**Comment by Ashok2252** [comment]
Any update on the above ?
