### ISSUE TITLE
1477: Weak Testcase

### ISSUE THREAD

**Issue by ayan-b** [LeetCode-Feedback/LeetCode-Feedback#457]
#### Your LeetCode username

hello_wrld

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The following code is wrong for the given test case, but still gets accepted.

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
    int minSumOfLengths(vector<int>& a, int k) {
        // sum, idx
        unordered_map<int, int> prev;
        int cur = 0;
        prev[0] = {-1};
        vector<vector<int>> res;
        for (int i = 0; i < a.size(); ++i) {
            cur += a[i];
            if (prev.count(cur - k)) {
                res.push_back({prev[cur - k] + 1, i});
            }
            prev[cur] = i;
        }
        sort(res.begin(), res.end(), [](const vector<int> &u, const vector<int> &v){
            return (u[1] - u[0] < v[1] - v[0]) or (u[1] - u[0] == v[1] - v[0] and u[0] < v[0]);
        });
        if (res.size() < 2) return -1;
        for (int i = 1; i < res.size(); ++i) {
            if (res[i][0] >= res[0][0] and res[i][0] <= res[0][1]) continue;
            if (res[i][1] >= res[0][0] and res[i][1] <= res[0][1]) continue;
            return (res[0][1] - res[0][0] + 1) + (res[i][1] - res[i][0] + 1);
        }
        return -1;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The code should give WA.

#### Additional context

Test case used
```
[1,1,3,2,1,1,1]
5
```

**Comment by CooperCooperCooper** [comment]
Hi @ayan-b ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @ayan-b ,
Thank you for your time. Due to our most recent update for this problem prior to receiving this issue, the provided code is currently producing the result of Wrong Answer. Please take a look.
