### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by RashiDixit27** [LeetCode-Feedback/LeetCode-Feedback#4574]
#### Your LeetCode username

rashi_dixit27

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

not checking  : continuous subarray of size at least two 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    bool checkSubarraySum(vector<int>& nums, int k) {
        vector <int> mp;
        if(nums.size()<=1) return false;
        int curr_sum=nums[0];
        mp[curr_sum]=0;
        for(int i=1;i<nums.size();i++) 
        {
            curr_sum+=nums[i];
            if(curr_sum%k==0 || (i<(nums.size()-1) && nums[i]==0 && nums[i+1]==0))
                    return true;  
            mp[curr_sum]=i;
            int sum1=k;
            while(curr_sum-sum1>=0)
            {
                cout<<curr_sum-sum1<<" ";
                if(find(mp.begin(),mp.end(),curr_sum-sum1)!=mp.end()&& (find(mp.begin(),mp.end(),curr_sum-sum1)-mp.begin())!=i-1 )
                return true;
                sum1+=k;
            }
        }
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My submission was accepted but when I crosschecked above code with [1,3,0,6] 6 testcase it gave following error.
Wrong Answer
Runtime: 4 ms
Your input
[1,3,0,6]
6
stdout
4 
Output
false
Expected
true

**Comment by lc-kay** [comment]
@RashiDixit27 Your code currently fails on the test case [23,2,4,6,7] 6. Please let me know if you return a different behavior on your end and send a screenshot. Thank you!

**Comment by lc-kay** [comment]
@RashiDixit27 Can you please provide the submission details link to the accepted solution? Then, I can try to reproduce the behavior and confirm it.

**Comment by RashiDixit27** [comment]
https://leetcode.com/problems/continuous-subarray-sum/submissions/
Continuous Subarray Sum - LeetCode<https://leetcode.com/problems/continuous-subarray-sum/submissions/>
Given an integer array nums and an integer k, return true if nums has a continuous subarray of size at least two whose elements sum up to a multiple of k, or false otherwise.. An integer x is a multiple of k if there exists an integer n such that x = n * k.0 is always a multiple of k.. Example 1: Input: nums = [23,2,4,6,7], k = 6 Output: true Explanation: [2, 4] is a continuous subarray of ...
leetcode.com

Here is the copy of code:

class Solution {
public:
    bool checkSubarraySum(vector<int>& nums, int k) {
        map<int ,int> mp;
        if(nums.size()<=1) return false;
        int curr_sum=nums[0];
        mp[curr_sum]=0;
        for(int i=1;i<nums.size();i++)
        {
            curr_sum+=nums[i];
            if(curr_sum%k==0 || (i<(nums.size()-1) && nums[i]==0 && nums[i+1]==0))
                    return true;
            mp[curr_sum]=i;
            int sum1=k;
            while(curr_sum-sum1>=0)
            {
                cout<<curr_sum-sum1<<" ";
                if(mp.find(curr_sum-sum1)!=mp.end()&& mp[curr_sum-sum1]!=i-1 )
                return true;
                sum1+=k;
            }
        }
        return false;
    }
};
________________________________

**Comment by lc-kay** [comment]
Hi @RashiDixit27 
Thank you for providing that! 've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @RashiDixit27 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
