### ISSUE TITLE
Missing Test Case - 408. Valid Word Abbreviation

### ISSUE THREAD

**Issue by vikash-gupta** [LeetCode-Feedback/LeetCode-Feedback#4581]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Incorrect output

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
Output should match expected output.
Input
"a"
"01"
Here abbr is 01 which when converted into integer, means 1 so it should replace one 'a'. The solution implemented by Leetcode is considering leading zero as invalid, whereas in problem description, it's mentioned that abbr will contain integers.

**Comment by lc-kay** [comment]
Hi @vikash-gupta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vikash-gupta 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
