### ISSUE TITLE
Typo - 1940. Longest Common Subsequence Between Sorted Arrays

### ISSUE THREAD

**Issue by sebnyberg** [LeetCode-Feedback/LeetCode-Feedback#4582]
#### Your LeetCode username
[sebnyberg](https://leetcode.com/sebnyberg/)

#### Category of the bug
- [x] Typo

#### Description of the bug

The Go stub for [1940](https://leetcode.com/problems/longest-common-subsequence-between-sorted-arrays/) is misspelt as "commo*m*" instead of "commo*n*"

```go
func longestCommomSubsequence(arrays [][]int) []int {
    
}
```

#### Language used for code
Go

**Comment by lc-kay** [comment]
Hi @sebnyberg 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sebnyberg 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
