### ISSUE TITLE
Missing Test Case - 1981. Minimize the Difference Between Target and Chosen Elements

### ISSUE THREAD

**Issue by Amit-GH** [LeetCode-Feedback/LeetCode-Feedback#4583]
#### Your LeetCode username

amitghattimare

#### Category of the bug
- [] Missing Test Cases 

#### Description of the bug

I was going through some accepted solutions of this problem. I found one 3ms Java solution and was curious to know how it works. On inspecting it, I found that the logic was flawed. I could create a test case where it fails.

#### Code you used for Submit/Run operation

```
// This is someone else's solution.
class Solution {
    public int minimizeTheDifference(int[][] mat, int target) {
        int m = mat.length;
        int n = mat[0].length;
        for (int[] row : mat) Arrays.sort(row);

        int minsum = 0;
        for (int[] row : mat) minsum += row[0];
        if (minsum >= target) return minsum - target;

        int maxsum = 0;
        for (int[] row : mat) maxsum += row[n-1];
        if (maxsum <= target) return target - maxsum;

        int currsum = minsum;
        int minincr = Integer.MAX_VALUE;
        for (int i = 0; i < m; i++) {
            int j = 0;
            while (j+1 < n && currsum + mat[i][j+1] - mat[i][j] <= target) {
                currsum = currsum + mat[i][j+1] - mat[i][j];
                j++;
            }
            if (j+1 < n) minincr = Math.min(minincr, mat[i][j+1] - mat[i][j]);
        }
        return Math.min(target - currsum, currsum + minincr - target);
    }
}
```

#### Language used for code
Java

#### Expected behavior

Below test case fails.
```
[[1,2,4,10],[3,7,10,11]]
14
```
Expected: 0, Actual: 1.

**Comment by lc-kay** [comment]
@Amit-GH The solution provided already fails the following test case:
[[70,9,70,1,1,1,1,1,70,70,1,70,70,70,70,70,70,1,70,1,70,1,70,70,70,70,70,1,1,70,70],[1,1,70,9,70,70,70,70,1,1,1,70,1,1,1,1,1,70,70,70,1,70,70,1,1,1,1,1,1,1,1],[70,1,1,1,70,70,70,70,1,1,1,1,70,1,70,1,70,1,1,70,1,1,1,70,1,70,70,9,1,70,70],[1,1,1,1,70,70,1,70,70,1,70,1,70,1,70,70,70,70,70,70,70,1,70,70,1,9,1,70,70,1,70],[70,70,1,1,1,70,1,70,1,1,1,1,1,1,70,70,70,1,1,1,1,1,1,70,70,70,1,70,70,70,9],[1,1,1,1,70,1,1,1,1,1,70,1,1,70,1,70,1,9,1,70,1,70,70,1,70,1,70,70,1,1,70],[70,1,9,1,70,1,70,1,1,70,70,70,70,70,70,70,1,1,1,70,1,70,1,1,1,1,70,1,70,1,70],[1,70,1,1,1,70,1,1,70,1,1,1,1,70,70,70,1,70,70,9,1,1,1,70,70,1,70,70,1,70,70],[70,1,1,70,1,70,1,1,1,1,1,1,70,70,70,70,1,9,1,70,1,70,1,1,70,70,70,1,70,70,70],[70,1,1,1,70,1,1,1,1,1,70,70,1,9,1,1,1,1,1,1,1,70,70,70,70,1,70,1,70,1,70],[1,1,70,1,1,70,9,1,70,70,70,70,1,1,70,1,70,1,1,1,70,1,1,70,1,70,1,70,70,70,70],[70,70,70,70,70,70,70,1,70,70,70,70,1,9,1,1,1,70,70,70,70,70,1,70,1,1,1,1,70,1,70],[1,70,70,70,70,70,70,70,1,70,1,70,1,1,9,1,70,70,1,70,1,70,70,1,1,1,70,70,70,1,1],[1,1,1,1,1,1,1,70,1,1,1,70,1,1,1,70,1,9,1,1,1,1,70,1,70,70,1,1,70,70,1],[70,70,70,1,1,1,70,70,70,1,1,1,1,70,1,70,70,1,70,70,1,70,9,70,1,70,1,70,1,70,1],[70,1,70,70,1,70,1,9,1,70,1,70,1,1,1,1,1,70,1,70,1,1,70,1,70,70,70,70,70,1,1],[70,70,70,1,1,1,1,1,1,70,70,70,70,70,1,1,70,1,1,70,70,1,70,9,1,1,1,70,70,1,1],[70,70,70,1,70,1,70,70,1,70,70,70,70,9,1,1,1,1,1,70,70,70,70,1,70,1,70,70,1,70,1],[1,70,70,70,1,70,70,1,70,1,1,1,1,70,1,70,70,70,70,1,70,9,1,70,1,1,70,1,70,70,1],[70,1,70,1,1,70,70,70,1,70,1,1,1,1,70,70,1,70,1,70,1,1,1,70,1,9,70,1,1,1,1],[70,1,70,70,70,70,70,70,70,1,1,70,70,70,70,1,1,70,1,9,1,70,1,70,1,1,1,70,70,70,70],[70,1,1,70,70,70,70,1,70,1,1,1,70,1,70,70,70,70,70,1,1,70,9,70,1,1,70,70,1,1,1],[70,1,1,1,70,70,70,70,1,1,1,1,1,70,1,1,70,70,70,70,70,1,9,1,70,1,1,1,1,1,70],[70,1,70,70,70,70,70,1,1,1,70,1,1,1,70,70,1,1,1,1,1,1,1,70,1,70,1,70,70,70,9],[70,1,1,9,1,1,70,1,70,70,1,1,70,70,1,1,1,70,1,1,1,70,1,70,70,1,70,70,70,70,70],[70,1,1,1,70,1,1,70,70,1,1,1,1,70,1,70,70,70,70,70,1,1,70,1,1,70,9,1,70,70,70],[70,70,1,70,1,1,70,1,1,1,70,70,70,1,70,1,1,70,1,1,70,9,1,1,70,70,1,1,70,70,70],[1,1,1,70,1,70,1,1,70,70,9,1,70,1,70,1,1,70,1,70,70,70,1,1,1,1,70,1,1,1,70],[70,70,70,70,1,1,1,1,70,1,70,1,1,1,70,1,70,9,70,70,70,70,1,70,70,70,1,70,1,1,1],[70,70,70,9,1,70,1,1,1,1,1,1,1,1,1,1,1,70,70,70,1,70,70,70,1,1,70,1,1,1,70],[1,70,70,1,1,70,70,1,70,70,1,70,1,70,70,70,70,9,70,70,70,70,70,1,70,1,1,70,1,70,70]]
281

Therefore, we will not be adding the test case [[1,2,4,10],[3,7,10,11]] 14 as it does not fail an accepted solution. Thank you for your time.

**Comment by Amit-GH** [comment]
Okay. Perhaps someone already reported this and you updated your test cases after the competition because the code which I mentioned above is an accepted Java solution in the 3ms range. I got it from 'Submission Details' page.
