### ISSUE TITLE
 Longest Palindromic Substring - Test Case wrong output

### ISSUE THREAD

**Issue by jai2dev** [LeetCode-Feedback/LeetCode-Feedback#4584]
#### Your LeetCode username

jaidev2

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Test Case Wrong Output

#### Description of the bug

For the question: Longest Palindromic Substring, when the solution is submitted, for the test case "cbbd" the online judge shows wrong output : "bab" though the expected answer is correct but when the same code is tested in console for the same test case the output is "bb" which matches the expected output

#### Code you used for Submit/Run operation

```
import numpy as np
res=[]
class Solution:
    def __init__(self):
        self.count=0
        self.dp=[[1 if i==j else -1 for i in range(1000)] for j in range(1000)]
    def expand(self,s,left,right,n):
        while (left>-1 and right<n) and s[left]==s[right]:
            left-=1
            right+=1
            
        return (left+1,right-1)
    
    def memoisation(self,i,j,n,s):
        self.count+=1
        if i<=j and i>-1 and j<n:
            
            if self.dp[i][j]!=-1:
                
                return self.dp[i][j]
            
            # print(i,j)
            else:
                self.dp[i][j]= int(self.memoisation(i+1,j-1,n,s) and (s[i]==s[j]))
                return self.dp[i][j]
        
        else:
            if i>-1 and j<n:
                self.dp[i][j]=0
            return 0
            
    def longestPalindrome(self, s: str) -> str:
        
        n=len(s)
        if n==1:
            return s
        for i in range(n):
            res.append(s[i])
        s=res
        dp=[[1 if i==j else -1 for i in range(n)] for j in range(n)]
        if s[:]==s[::-1]:
            return s

        for i in range(n-1):
            if s[i]==s[i+1]:
                self.dp[i][i+1]=1
            else:
                self.dp[i][i+1]=0

        # print(len(s))
        for i in range(n-3,-1,-1):
            for j in range(i+2,n):
                if self.dp[i][j]==-1 and s[i]==s[j]:
                    self.memoisation(i,j,n,s)
                    # print(self.dp[i][j])
                    
        # print(dp)
        # print(self.count)
        st,end=n,-1
        for i in range(n):
            for j in range(i,n):
                if self.dp[i][j]==1:
                    if j-i+1>end-st+1:
                        st=i
                        end=j
                        
                        
        return ''.join(c for c in s[st:end+1])
```

#### Language used for code

Python3.8

#### Expected behavior

When I submit the code, it shows different output as compared when I run the same code in the console. TestCase:- "cbbd"

#### Screenshots

![alt text](https://drive.google.com/file/d/1xIxeqS8iX1oByRXlagkf2Eqx0e49C7WL/view?usp=sharing)
![Screenshot from 2021-08-23 00-58-03](https://user-images.githubusercontent.com/47266980/130367662-05f331c7-39c3-4b1a-9788-718f21ee138b.png)

**Comment by lc-kay** [comment]
Hi @jai2dev 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
