### ISSUE TITLE
Python3 Solution TLE - 1981. Minimize the Difference Between Target and Chosen Elements

### ISSUE THREAD

**Issue by gautamsw5** [LeetCode-Feedback/LeetCode-Feedback#4585]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution got accepted on LeetCode just now but showed TLE during contest and in "submissions" section, it still shows TLE, also in contest it is showing 4 wrong attempts for me whereas this was my second.

#### Code you used for Submit/Run operation

```
class Solution:
    def minimizeTheDifference(self, mat: List[List[int]], target: int) -> int:
        self.n = len(mat)
        self.mat = mat
        self.m = len(mat[0])
        for i in range(self.n):
            mat[i] = sorted(list(set(mat[i])))
        dp = [set() for i in range(self.n+1)]
        dp[0].add(0)
        for i in range(self.n):
            for subSum in dp[i]:
                for v in mat[i]:
                    dp[i+1].add(subSum + v)
        # print(dp[self.n])
        ans = 10**12
        for i in dp[self.n]:
            if abs(i-target) < ans:
                ans = abs(i-target)
        return ans
```

#### Screenshots
Just now:
![image](https://user-images.githubusercontent.com/72446354/130370826-9689fc05-7d9a-49dd-b55b-de5c2c307bb8.png)

During Contest
![image](https://user-images.githubusercontent.com/72446354/130370841-c3b3d758-3d01-4409-9a81-e794f6a56e8b.png)

#### Additional context

https://leetcode.com/contest/weekly-contest-255/submissions/detail/542221327/
https://leetcode.com/problems/minimize-the-difference-between-target-and-chosen-elements/
https://leetcode.com/contest/weekly-contest-255/problems/minimize-the-difference-between-target-and-chosen-elements/

**Comment by lc-kay** [comment]
Hi @gautamsw5 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @gautamsw5 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
