### ISSUE TITLE
improve Rectangle Area II problem statement

### ISSUE THREAD

**Issue by hamirmahal** [LeetCode-Feedback/LeetCode-Feedback#4586]
#### Your LeetCode username

hamirmahal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think we can improve the problem statement for today's daily challenge, Rectangle Area II.

It says,
> We are given a list of (axis-aligned) rectangles. Each rectangle[i] = [xi1, yi1, xi2, yi2] , where (xi1, yi1) are the coordinates of the bottom-left corner, and (xi2, yi2) are the coordinates of the top-right corner of the ith rectangle.

The additional `i`s in
> [xi1, yi1, xi2, yi2] , where (xi1, yi1) are the coordinates of the bottom-left corner, and (xi2, yi2)

 seem unnecessary.

#### Code you used for Submit/Run operation

n/a

#### Language used for code

n/a

#### Expected behavior

I think we can improve the clarity of the problem statement by just saying
> Each rectangle[i] = [x1, y1, x2, y2] , where (x1, y1) are the coordinates of the bottom-left corner, and (x2, y2) are the coordinates of the top-right corner of the ith rectangle.

What do you think?

### Current problem statement
![Screen Shot 2021-08-22 at 4 12 50 PM](https://user-images.githubusercontent.com/43425812/130373001-4f3c700b-9d9c-42fc-a450-7d2898d84bf3.png)

### Possibly improved problem statement
![Screen Shot 2021-08-22 at 4 14 45 PM](https://user-images.githubusercontent.com/43425812/130373047-970a8c29-511c-4759-b62b-a02003873d83.png)

**Comment by lc-kay** [comment]
Hi @hamirmahal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hamirmahal 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
