### ISSUE TITLE
[Testcase broken] 185. Department Top Three Salaries

### ISSUE THREAD

**Issue by tangentyh** [LeetCode-Feedback/LeetCode-Feedback#459]
#### Your LeetCode username

@tangentyh

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The default test case for the problem 185 is broken, whose verdict when run will be `Invalid Testcase` for any code.

#### Code you used for Submit/Run operation

Any code, like
```SQL
SELECT 1;
```

#### Language used for code
MySQL

#### Expected behavior

When click "Run code" with default test case
```json
{"headers": {"Employee": ["Id", "Name", "Salary", "DepartmentId"], "Department": ["Id", "Name"]}, "rows": {"Employee": [[1, "Joe", 85000, 1], [2, "Henry", 80000, 2], [3, "Sam", 60000, 2], [4, "Max", 90000, 1], [5, "Janet", 69000, 1], [6, "Randy", 85000, 1], [7, "Will", 70000, 1]], "Department": [[1, "IT"], [2, "Sales"]]}}
```

the result is `Invalid Testcase` with the below error which is not expected.
```
Line 5: SyntaxError: near 'row_number,
  @dep := DepartmentId as dummy,
  @salary := Salary as dummy2
fr'
```

**Comment by CooperCooperCooper** [comment]
Hi @tangentyh ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @tangentyh ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
