### ISSUE TITLE
787. K 站中转内最便宜的航班 题目有问题

### ISSUE THREAD

**Issue by Obsucre777** [LeetCode-Feedback/LeetCode-Feedback#4594]
ben-fu-8
奔赴

**Bug 类型**
- [1 ] 题目
- 题目描述不清
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
![G@7M7M{MLKG(ZRT9O{$__RA](https://user-images.githubusercontent.com/89432186/130541367-b3005914-2724-41be-943a-12df4e1ce0a7.png)
![G@7M7M{MLKG(ZRT9O{$__RA](https://user-images.githubusercontent.com/89432186/130541380-c296561b-e7ab-455a-90e2-9f6e3d5d4c14.png)
应该时以价格price到达to吧。

描述你遇到的 bug

**你使用的语言**
C

**你提交或者运行的代码**
无
**期望行为**
帮忙修改为以价格pice到达to

**屏幕截图**
![G@7M7M{MLKG(ZRT9O{$__RA](https://user-images.githubusercontent.com/89432186/130541367-b3005914-2724-41be-943a-12df4e1ce0a7.png)
![G@7M7M{MLKG(ZRT9O{$__RA](https://user-images.githubusercontent.com/89432186/130541380-c296561b-e7ab-455a-90e2-9f6e3d5d4c14.png)

**额外的上下文**
无

**Comment by feiceh** [comment]
@Obsucre777  你好，当前题目描述已更新，ID：ben-fu-8 给予积分奖励，请查收。
