### ISSUE TITLE
Missing Test Case - 653. Two Sum IV - Input is a BST

### ISSUE THREAD

**Issue by austynpark** [LeetCode-Feedback/LeetCode-Feedback#4597]
#### Your LeetCode username

qkrruddn6680

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:


unordered_map<int, int> tree;
void recursiveIterate(TreeNode* root) {
    if (root != nullptr)
    {
        ++tree[root->val];
    }
    else
        return;

    recursiveIterate(root->left);
    recursiveIterate(root->right);
}

bool findTarget(TreeNode* root, int k) {
    recursiveIterate(root);

    int currentSum = 0;
    
    for (auto it = tree.begin(); it != tree.end(); ++it) {
        currentSum = it->first;

        if (tree.find(k - currentSum) != tree.end()) {
            if (k - currentSum != currentSum) {
                return true;
            }
            else if (k - currentSum == currentSum && it->second > 1) {
                return true;
            }

            return false;
        }

    }


    return false;
}
};
```

#### Language used for code

C++

#### Expected behavior

In Visual Studio, Two Sum IV - Input is a BST Test Case#418 prints true but leetcode doesn't

**Comment by lc-kay** [comment]
@austynpark Unfortunately, we are unable to troubleshoot the different behaviors from Visual Studio and the LeetCode environment. Please raise this question in the problem discuss section as other users may have encountered this before. Thank you for your understanding.
