### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by MarcosCarvajal** [LeetCode-Feedback/LeetCode-Feedback#4599]
#### Your LeetCode username
MarcosCarvajal 

#### Category of the bug

- [ ] Solution

#### Description of the bug
 wrong answers. I have the solution made from vsc and it works correctly, but when passing the results to leetcode it throws me different solutions, the same thing has happened to me in the previous solutions.

#### Code you used for Submit/Run operation

var merge = function(nums1, m, nums2, n) {
    let n1=[];
    let n2=[];
    for(i=0; i<m; i++){
        n1.push(nums1[i]);
    }
    for (j=0; j<n; j++){
        n2.push(nums2[j]);
    }
    
    let n3 = n1.concat(n2);
    nums1 = n3.sort();
    return nums1;
};

#### Language used for code
JavaScript

#### Expected behavior
 [ 1, 2, 2, 3, 5, 6 ] and leet code show me [1,2,3,0,0,0]

#### Screenshots
 ![image](https://user-images.githubusercontent.com/88865485/130624559-80a8294c-55e1-4f39-9cb2-4717f27ab511.png) 
![image](https://user-images.githubusercontent.com/88865485/130624647-0761d2ae-5dae-450b-829a-57214559bd60.png)

**Comment by lc-kay** [comment]
@MarcosCarvajal Unfortunately, we are unable to troubleshoot the different behaviors from vcs and the LeetCode environment. Please raise this question in the problem discuss section as other users may have encountered this before. Thank you for your understanding.
