### ISSUE TITLE
665. Non-decreasing Array

### ISSUE THREAD

**Issue by vitkarpov** [LeetCode-Feedback/LeetCode-Feedback#46]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**

There's a typo in the description. It says:

> We define an array is non-decreasing if array[i] <= array[i + 1] holds for every i (1 <= i < n).

I believe either the range should be `0 <= i < n - 1` or `array[i - 1] <= array[i]`. Thanks.

**Comment by CooperCooperCooper** [comment]
Hi @vitkarpov,
Thank you for raising this issue to our attention. I've relayed it to our team to consider.

**Comment by CooperCooperCooper** [comment]
Hi @vitkarpov,
Thank you for your time. We've updated the problem description according to your feedback.
