### ISSUE TITLE
Incorrect Test Case 1620. Coordinate With Maximum Network Quality

### ISSUE THREAD

**Issue by IamAdiSri** [LeetCode-Feedback/LeetCode-Feedback#4600]
#### Your LeetCode username
IamAdiSri

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect Test Cases

#### Description of the bug
The test case `towers = [[42, 0, 0]]` and `radius = 7` only accepts the answer `[0, 0]`.
This is incorrect since any coordinates with `x<0` or `x=0 and y<0` also satisfy the requirements of the the test case, and picking the lexicographically minimal coordinate is impossible.

#### Code you used for Submit/Run operation

```
// Two Sumclass Solution:
    def bestCoordinate(self, towers: List[List[int]], radius: int) -> List[int]:
        minx = miny = float('inf')
        maxx = maxy = float('-inf')
        
        for t in towers:
            minx = min(minx, t[0]-radius)
            maxx = max(maxx, t[0]+radius)
            
            miny = min(miny, t[1]-radius)
            maxy = max(maxy, t[1]+radius)
        
        bestx, besty = float('inf'), float('inf')
        maxsq = float('-inf')
        for x in range(minx, maxx+1):
            for y in range(miny, maxy+1):
                sq = 0
                for t in towers:
                    d = pow(((x-t[0])**2 + (y-t[1])**2), 0.5)
                    if d <= radius:
                        sq += t[2]//(1+d)
                        if sq >= maxsq:
                            best = (x,y)
                            if sq > maxsq:
                                bestx, besty = x, y
                            if sq==maxsq and (x<bestx or (x==bestx and y<besty)):
                                bestx, besty = x, y
                            maxsq = sq
                
        return bestx, besty
```

#### Language used for code

Python

#### Expected behavior

For this test case the network quality is `0` for every coordinate possible. Out of these, the lowest acceptable solution should be `[35, 0]` as it is the lowest point that is still within the radius of the tower. However, even if one ignores the radius (as has been done when setting the solution to `[0, 0]`), the problem statement sets no bounds for `x` and `y` (the tower locations have bounds on them, but their signal ranges don't) and thus any coordinate with x in the range `x=[-inf, 42]` suffices for the answer, with the smallest being at `-inf`.

**Comment by lc-kay** [comment]
Hi @IamAdiSri 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IamAdiSri 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by chasonlee** [comment]
@lc-kay The problem is still exists! There's another error case: towers=[[0,1,2],[2,1,2],[1,0,2],[1,2,2]], radius=1，the answer is [1,1]??
environment: Python3
