### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by Akshay9045** [LeetCode-Feedback/LeetCode-Feedback#4606]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Akshay9045 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
