### ISSUE TITLE
Missing Test Case - 633. Sum of Square Numbers

### ISSUE THREAD

**Issue by ritegarg** [LeetCode-Feedback/LeetCode-Feedback#4608]
#### Your LeetCode username
ninja_rg

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

If a user uses two pointer technique and uses integer for borders, the solution can give wrong output(which shows as accepted) for the test case 2147483600

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean judgeSquareSum(int target) {
      if (target < 0) return false;
        int i =0 , j =(int) Math.sqrt(target);
        while(i<=j)
        {
            int powsum = i*i + j*j;
            if(powsum == target)
            {
                return true;
            }
            else if (powsum > target){
                j--;
                
            }
            else{
                i++;
            }
        }
        return false;
            
    }
}
```

#### Expected behavior

The solution above is sample 2ms solution in submission detail page. For the test case 2147483600, the above solution produces wrong result.

The fix should be that we should use long instead of int value.

**Comment by lc-kay** [comment]
Hi @ritegarg 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
