### ISSUE TITLE
1477. Find Two Non-overlapping Sub-arrays Each With Target Sum

### ISSUE THREAD

**Issue by jayaprakash-a** [LeetCode-Feedback/LeetCode-Feedback#461]
#### Your LeetCode username
jayaprakash_a

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
My code when tested on the given test case gave a wrong answer, but got accepted by the leetcode platform.
arr = [14, 1, 15, 15, 1, 14], target = 30

#### Code you used for Submit/Run operation

```
import sys
class Solution:
    def minSumOfLengths(self, arr, target):
        def comp(x):
            return x[2], x[0], x[1]
        def check(lengths):
            if len(lengths) < 2:
                return sys.maxsize, sys.maxsize, lengths
            m1, m2 = sys.maxsize, sys.maxsize        
            lengths = sorted(lengths, key=comp)
            m1 = lengths[0][2]
            for i in range(1, len(lengths)):
                if not(lengths[i][0] < lengths[0][1] < lengths[i][1] or (lengths[i][0] < lengths[0][0] < lengths[i][1])):
                    m2 = lengths[i][2]
                    break
            if m1 == sys.maxsize or m2 == sys.maxsize:
                return m1, m2, lengths
            return m1, m2, lengths
        preSum = [0]*(len(arr)+1)
        for i in range(len(arr)):
            preSum[i+1] += (preSum[i] + arr[i])
        m1, m2 = sys.maxsize, sys.maxsize
        sums = {}
        minVal = sys.maxsize
        lengths = []
        for i in range(len(preSum)):
            sums[preSum[i]] = i
            if preSum[i]-target in sums:
                lengths.append((sums[preSum[i]-target], i, i-sums[preSum[i]-target]))
                minVal = min(minVal, i-sums[preSum[i]-target])

        m1, m2, lengths = check(lengths)  
        
        if m1 == sys.maxsize or m2 == sys.maxsize:
            return -1
        return m1+m2
```

#### Language used for code
Python

#### Expected behavior
The code should not be accepted by the judge. It should be a wrong answer.

#### Screenshots
![Screenshot from 2020-06-13 22-11-30](https://user-images.githubusercontent.com/14257579/84574276-0574f380-adc3-11ea-99d4-d2c08dac888c.png)

**Comment by CooperCooperCooper** [comment]
Hi @jayaprakash-a ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @jayaprakash-a ,
Thank you for your time. Due to our most recent update for this problem prior to receiving this issue, the provided code is currently producing the result of Wrong Answer. We appreciate your support.
