### ISSUE TITLE
Missing Test Case - 633. Sum of Square Numbers

### ISSUE THREAD

**Issue by gill984** [LeetCode-Feedback/LeetCode-Feedback#4610]
#### Your LeetCode username
bronickel

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Test cases aren't robust enough to catch issues with the top voted discussion answer. Adding test case 2147483636 will catch solutions which have the same overflow issue.

#### Code you used for Submit/Run operation

```java
// Two Sum
public class Solution {
    public boolean judgeSquareSum(int c) {
        if (c < 0) {
            return false;
        }
        int left = 0, right = (int)Math.sqrt(c);
        while (left <= right) {
            int cur = left * left + right * right;
            if (cur < c) {
                left++;
            } else if (cur > c) {
                right--;
            } else {
                return true;
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Using the above code should fail when submitted due to an issue with overflow which isn't handled. If you try running it against the test case 2147483636 it will fail, but submitting the code will result in it being accepted.

#### Additional context

I also wouldn't be opposed to changing the bounds for the input to be smaller, this would prevent overflow issues with multiplication. Then again overflow is something you always have to think about when programming in Java, even if it is annoying.

**Comment by lc-kay** [comment]
@gill984 Our team did not add this test case because it now fails on a recently added test case. Thank you for your time.
