### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by geeky01adarsh** [LeetCode-Feedback/LeetCode-Feedback#4611]
#### Your LeetCode username

geeky01adarsh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is missing test case which may be a crucial bug as it limits memory lesser than 82.43% of online submissions

#### Code you used for Submit/Run operation

```
// Set Matrix Zeroes
class Solution {
public:
    void setZeroes(vector<vector<int>>& matrix) {
        // Traverse row wise
        int n = matrix.size(), m =matrix[0].size();
        for (int i = 0; i < n; i++) {
        for (int j = 0; j < m; j++) {
            if (matrix[i][j] == 0) {
                // Set all the elements that are not zero as -9999
                for (int k = 0; k < m; k++) {
                    if (matrix[i][k] != 0) {
                        matrix[i][k] = -9999;
                    }                        
                }
                break;
            }
        }
    }
        
    // Traverse column wise
    for (int j = 0; j < m; j++) {
        for (int i = 0; i < n; i++) {
            if (matrix[i][j] == 0) {
                // Set all the elements that are not zero as -9999
                for (int k = 0; k < n; k++) {
                    if (matrix[k][j] != 0) {
                        matrix[k][j] = -9999;
                    }
                }
            }
        }
    }
        
    // Update all -9999 as 0
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < m; j++) {
            if (matrix[i][j] == -9999) {
                matrix[i][j] = 0;
            }
        }
    }
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

The code was expected to generate an error if any element of mat[i][j]=-9999 but there was no such elements in any of the testcases. The question is important from interview perspective and hence there must be a test case to ensure the bug to be resolved.

#### Screenshots

NA

**Comment by lc-kay** [comment]
@geeky01adarsh Our team has reviewed your report and decided not to add these test cases because the dummy value can be updated, and the solution will still get AC. Thank you for your time and understanding.
