### ISSUE TITLE
Missing Test Case - 633. Sum of Square Numbers

### ISSUE THREAD

**Issue by sakam0to** [LeetCode-Feedback/LeetCode-Feedback#4615]
#### Your LeetCode username

sakam0to

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

A missing test case may accept wrong answers.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean judgeSquareSum(int c) {
        List<Integer> list = new ArrayList();
        int i = 0;
        while(i*i >= i && i*i <= c){
            list.add(i*i);
            i++;
        }
        int left = 0;
        int right = list.size() - 1;
        
        while(left <= right){
            if(list.get(left) + list.get(right) == c)
                return true;
            else if(list.get(left) + list.get(right) < c)
                left++;
            else
                right--;
        }
        
        return false;    
    }
}
```

#### Expected behavior

My answer returns *false* when test case is 2147473645 which is wrong, but my answer passes the tests.

**Comment by lc-kay** [comment]
@sakam0to Our team did not add this test case because it now fails on a recently added test case. Thank you for your time.
