### ISSUE TITLE
Typo in 331

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#4617]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Typo in the problem statement of https://leetcode.com/problems/verify-preorder-serialization-of-a-binary-tree/

In the `constraints` section it is mentioned

> preoder consist of integers in the range [0, 100] and '#' separated by commas ','.

However `preoder` should be changed to `preorder`

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
