### ISSUE TITLE
Missing Test Case - 1668. Maximum Repeating Substring

### ISSUE THREAD

**Issue by roycevanle** [LeetCode-Feedback/LeetCode-Feedback#4618]
#### Your LeetCode username

royle

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The bug stems from when you go forward to back, there is a possibility that the answer is in another substring, but you moved past the substring. But the same error occurs going back to front, except existing test cases don't cover. For example:
"abaabaabaababaabaaba"
"aba"

#### Code you used for Submit/Run operation
```
//1668. Maximum Repeating Substring
class Solution {
    public int maxRepeating(String sequence, String word) {
        int lastOccurOfWord = sequence.lastIndexOf(word);
        if (lastOccurOfWord == -1) return 0;
        int max = 1;
        int running = 1;
        String subseq = sequence.substring(0, lastOccurOfWord);
        lastOccurOfWord = subseq.lastIndexOf(word);
        while(!subseq.isEmpty() && lastOccurOfWord != -1) {
            if (subseq.length() - word.length() == lastOccurOfWord) {
                running++;
                max = Math.max(max, running);
            } else {
                running = 1;
            }
            subseq = subseq.substring(0, lastOccurOfWord);
            lastOccurOfWord = subseq.lastIndexOf(word);
        }
        return max;
    }
}
```

#### Language used for code
Java

#### Expected behavior

What I expect to happen with my code is that it is supposed to fail, but with existing test cases, it passes. My code failed going forward, so I just adapted it to go backwards, but then it should fail a case where it goes backwards as well according to missing test case I provided.

Test case to be included:
"abaabaabaababaabaaba"
"aba"

#### Screenshots

![image](https://user-images.githubusercontent.com/14909680/131025131-133ca17e-4016-4a4e-bf9f-b1ed0f9e28b9.png)

**Comment by lc-kay** [comment]
Hi @roycevanle 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
