### ISSUE TITLE
522. Longest Uncommon Subsequence II - model solution can't handle test case

### ISSUE THREAD

**Issue by ampanasiuk** [LeetCode-Feedback/LeetCode-Feedback#4620]
#### Your LeetCode username
Movely

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem constraints are:

    1 <= strs.length <= 50
    1 <= strs[i].length <= 10
    strs[i] consists of lowercase English letters.

These are satisfied by the input:

    ["abc"]

The model solution fails for this input:

    Expected answer:
    Line 4: java.lang.AssertionError

#### Language used for code
Python3

#### Expected behavior
The correct answer is 3

**Comment by lc-kay** [comment]
@ampanasiuk Our team has fixed the constraints. Thank you for your time.

**Comment by ampanasiuk** [comment]
When can I expect the 100 leetcoin award?

**Comment by lc-kay** [comment]
@ampanasiuk 
Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by ampanasiuk** [comment]
Thanks! 👍
