### ISSUE TITLE
How is "Acceptance" calculated for LeetCode problems?

### ISSUE THREAD

**Issue by idontknoooo** [LeetCode-Feedback/LeetCode-Feedback#4623]
#### Your LeetCode username
idontknoooo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
How is "Acceptance" calculated for LeetCode problems?

"Acceptance" should be a way to identify the difficulty of a problem. It doesn't have to be absolutely accurate, but it should be relatively accurate in a certain range.

The reality is that some medium questions are 70%, 80% acceptance, but based on my experience (1464/1793 solved), they are not as easy as some 40% acceptance questions.  This is basically a "Survivorship bias". These questions are showing high acceptance due to the combination of the following reasons: 
- The question is not popular (only a few hundred people tried to solve it)
- Generally, people who tried to solve unpopular questions are active LeetCoders with a strong background (they solve questions for fun), thus the acceptance is probably accurate for this group of people, but not applicable or accurate for all LeetCoders 
- The methodology behind the calculation of acceptance rate. 
 
And maybe more reasons. I don't have the metrics for each question, but based on what I've seen, I believe this needs to be investigated. This somehow affects user experience. I felt weird when I was able to solve 35-45% acceptance questions but failed to solve a 75% acceptance question. A couple of things we can do to improve this is to:
- Calculate acceptance rate only when a problem is popular (maybe when they are 200 articles in discussion or some different ways of measuring)
- Instead of doing a number, make acceptance rate as a historical chart, per week basis (like stock chart)

It's kind of a broad question, hope you find the same thing I am seeing and it will be better if someone can spend time looking at it.

**Comment by fultonm** [comment]
I think the Acceptance metric make sense as it stands and disagree it should measure something other than the percentage of accepted answers. If they did that they should also rename the metric, right?

Furthermore there is already a difficulty measurement Hard, Medium, and Easy.

**Comment by idontknoooo** [comment]
How is "the percentage of accepted answers" calculated? Sometimes, people are submitting correct answers multiple times to test out different methods, sometimes one person will submit multiple wrong answers to exhaust all test cases.

Is this percentage calculated at a per-person basis or at a global level? Because if it's on a global level, acceptance can become a very redundant metric. I could've submitted the correct solution 1 million times to higher up the acceptance rate so that it looks like an EASY question. 

I understand what difficulty tags can do. But ideally, within the same difficulty tag, "acceptance" can be at a per-person level to identify the actual real difficulty among users who've tried to solve this question. 

Name changing is a valid point, but even for the same naming, there are multiple ways to calculate the same metrics.

**Comment by fultonm** [comment]
It looks like this is a hotly discussed topic and I haven't seen any official answer.

I would assume "percentage of accepted solutions" means once a user attempts a solution the contribute +1 to total attempts on the question. Subsequent attempts, pass or fail, would not increase that number. When the user gets a passing solution, they contribute +1 to accepted solutions.

**Comment by idontknoooo** [comment]
@fultonm Thanks for sharing your point.
> I would assume the calculation is users submitting at least 1 passing solutions / number of users attempting the question at least once.

Based on this assumption, for a 50% acceptance question, say the total attempted user is 1000, meaning that there are 500 of them actually solved the question successfully? [LeetCode 1. Two Sum](https://leetcode.com/problems/two-sum/), commonly recognized as the **_must-do_** question on LeetCode, has 47.5% of acceptance rate, meaning there are more than half of the participants failed to solve this question? It just doesn't make sense to me.

**Comment by lc-kay** [comment]
@idontknoooo The acceptance rate is the number of accepted submissions/number of total submissions to the problem. However, you raise a good point that other factors like the popularity of a problem should be considered when calculating the "Acceptance" rate. I've noted your feedback and relayed it to the team to take into consideration. Lastly, a kind reminder that our Github repo is for reporting content-related issues. For all non-content-related issues, please reach out to us via our [help center](https://leetcode.com/support), and we'll be more than happy to help you there.
