### ISSUE TITLE
Missing Test Case - 1933. Check if String Is Decomposable Into Value-Equal Substrings

### ISSUE THREAD

**Issue by ampanasiuk** [LeetCode-Feedback/LeetCode-Feedback#4625]
#### Your LeetCode username
Movely

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The current user submitted solution that is presented on the runtime performance graph for the 32 ms bar does not actually work.

#### Code you used for Submit/Run operation
This is the code I copied from the user submitted sample:

```python
from collections import Counter
class Solution:
    def isDecomposable(self, s: str) -> bool:
        d = Counter(s)
        count = 0        
           
        for i in d.values():
            if i%3 == 1:
                return(False)
            elif i%3 == 2:
                count+=1
                    
        if count==1:
            return(True)
        else:
            return(False)
```

#### Language used for code
Python3

#### Screenshots
Here's a screenshot:
![Buggy Check if String Is Decomposable Into Value-Equal Substrings](https://user-images.githubusercontent.com/4141848/131204565-09e46889-c691-4144-987b-ade73727dc49.png)

#### Additional context
The test case: "12121"
Actual true, Expected false

**Comment by lc-kay** [comment]
@ampanasiuk Our team recently updated the test cases for this problem. Your code now fails on the test case "01010". Therefore, we will not be adding "12121" Thank you for your time.
