### ISSUE TITLE
Questionable Test Case - 1448. Count Good Nodes in Binary Tree test case

### ISSUE THREAD

**Issue by fultonm** [LeetCode-Feedback/LeetCode-Feedback#4626]
#### Your LeetCode username

fultonm

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

For 1448. Count Good Nodes in Binary Tree, the test case [9, null, 3, 6] binary tree doesn't make sense to me. It seems to indicate 6 is the child node of null.

So this binary tree would look like this:
```
        9
      /    \
   null    3
  /
6
```

Since we are given values that contain references to left/right instead of an array, what does that null value look like in this struct? The TreeNodes themselves are wrapped in an option so maybe its `None`. Then, how could we ever evaluate the 6 in the above test case?

```
pub fn new(val: i32) -> Self {
    TreeNode {
      val,
      left: None,
      right: None
    }
  }
```

#### Code you used for Submit/Run operation

This code is based on the sample code used for the 6400kb example. It fails because I use `val` directly when pushing new nodes, which is None, or null, or whatever. I'm not sure what data the null nodes have because this data type must be `i32`.

```
// Count Good Nodes in Binary Tree
impl Solution {
    pub fn good_nodes(root: Option<Rc<RefCell<TreeNode>>>) -> i32 {
        let mut good_node_count = 0;
        let mut s = Vec::with_capacity(10_000);
        s.push((root, i32::MIN));

        while let Some((node, max)) = s.pop() {
            if let Some(n) = node {
                let val = n.borrow().val;
                if val >= max {
                    good_node_count += 1;
                }
                s.push((n.borrow().left.clone(), val));
                s.push((n.borrow().right.clone(), val));
            }
        }

        good_node_count
    }
}

```

#### Language used for code

Rust

#### Expected behavior

Only binary trees passed as input to our function.
My code actually returns 1 as the test case expects on my machine, but when submitting on leetcode the system claims my output is 2. I use this code to construct binary tree from array input for testing purposes:
```
let tree_array = vec![Some(9), None, Some(3), Some(6)];
create_tree(&tree_array, 0);

fn create_tree(input: &Vec<Option<i32>>, k: i32) -> Option<Rc<RefCell<TreeNode>>> {
    let node_value;
    match input[k as usize] {
        Some(val) => {
            node_value = val;
        }
        None => {
            return None;
        }
    }
    let mut parent_node = TreeNode::new(node_value);
    if k + k + 1 < input.len() as i32 {
        parent_node.left = create_tree(input, k + k + 1);
    }
    if k + k + 2 < input.len() as i32 {
        parent_node.right = create_tree(input, k + k + 2);
    }
    Some(Rc::new(RefCell::new(parent_node)))
}
```

I think there's a lot of improvements we could make to this Rust question, namely the signature of the good_nodes function using Rc and Refcell seems unnecessary and adds language-specific complexity not related to solving the problem.

**Comment by lc-kay** [comment]
@fultonm Please refer to the screnshot attached for the tree visualization for this test case [9, null, 3, 6]. Also, I've relayed your feedback about the Rust driver code to our team to take into consideration. Please let me know if you have any other concerns about this problem and I will further look into it. Thank you for your time. 
<img width="1283" alt="Screen Shot 2021-08-31 at 9 37 10 AM" src="https://user-images.githubusercontent.com/70870126/131542454-d99e4c9c-0f63-48ce-b2a2-14f925b36d71.png">
