### ISSUE TITLE
Incorrect Solution Implementation - Design a Singly Linked List (Leetcode Explore, Linked Lists)

### ISSUE THREAD

**Issue by euglo** [LeetCode-Feedback/LeetCode-Feedback#4628]
Link to section: https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1298/

#### Your LeetCode username
bleugene12

#### Category of the bug
- [ ] Solution

#### Description of the bug
In the premium solution explanation for the "Design a Singly Linked List" section in the Linked Lists module for Leetcode Explore, the helper function `getNode` has the following implementation:

```
/** Helper function to return the index-th node in the linked list. */
private SinglyListNode getNode(int index) {
    SinglyListNode cur = head;
    for (int i = 0; i < index && cur != null; ++i) {
        cur = cur.next;
    }
    return cur;
}
```

However, this does not account for negative indices, instead returning the head node for them as well. Furthermore, this will cause the logic for `deleteAtIndex` to be incorrect as well when `index = 0`, aka when we are deleting the first node.

```
  /** Delete the index-th node in the linked list, if the index is valid. */
  public void deleteAtIndex(int index) {
      SinglyListNode cur = getNode(index);
      if (cur == null) {
          return;
      }
      SinglyListNode prev = getNode(index - 1);
      SinglyListNode next = cur.next;
      if (prev != null) {
          prev.next = next;
      } else {
          // modify head when deleting the first node.
          head = next;
      }
  }
```
This logic assumes that  when `index == 0`, `prev` will be `null` (`index - 1 = -1` will be passed in as the parameter to `getNode()`), in which case we fall to the `else` condition, `head = next`. However, since `getNode(-1)` erroneously returns the head of the node and assigns it to `prev`, `prev` is no longer `null`, and it instead falls to the first `if` condition `prev.next = next`, which will lead the linked list to be unchanged as `prev == cur`.

#### Code you used for Submit/Run operation
Copied the explanation's solution into [707. Design Linked List](https://leetcode.com/problems/design-linked-list/) failed the submission. I modified `getNode()` to instead be the following:

```
  /** Helper function to return the index-th node in the linked list. */
  private SinglyListNode getNode(int index) {
     // Start of new code
      if (index < 0) {
          return null;
      }
      // End of new code
      SinglyListNode cur = head;
      for (int i = 0; i < index && cur != null; ++i) {
          cur = cur.next;
      }
      return cur;
  }
```
and the submission succeeded.

#### Language used for code
Java

#### Expected behavior
Outlined in description

**Comment by lc-kay** [comment]
Hi @euglo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ajcatambay** [comment]
Good thing I searched for existing issues like this before I submitted a new one. Thanks @euglo ! May I kindly ask for updates on this @lc-kay  @LC-Sue ? The solution is still not corrected until now.

**Comment by LC-Sue** [comment]
Hi @euglo 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
