### ISSUE TITLE
Missing Test Case - 1986. Minimum Number of Work Sessions to Finish the Tasks

### ISSUE THREAD

**Issue by xzlin** [LeetCode-Feedback/LeetCode-Feedback#4629]
#### Your LeetCode username

202022021

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

missing a test case, for example,
[2,4,2,4,2,4]
5

#### Code you used for Submit/Run operation

```
class Solution:
    def minSessions(self, tasks: List[int], sessionTime: int) -> int:
        sess = sessionTime
        orgN = len(tasks)
        tasks = [x for x in tasks if x!=sess]
        res = orgN - len(tasks)
        
        k = 2
        while k <= len(tasks):
            found = False
            for a in itertools.combinations(tasks, k):
                if sum(a) == sess:
                    for i in a:
                        tasks.remove(i)
                    res += 1
                    found = True
                    break
            if not found: k += 1
    
        if not tasks: return res
        else:
            p = 0
            for n in tasks:
                if p+n > sess:
                    res += 1
                    p = n
                else:
                    p += n
            return res + 1
```

#### Language used for code

python3

#### Expected behavior

my code was accepted but for test case [2,4,2,4,2,4] 5, my answer of 6 is wrong.

**Comment by lc-kay** [comment]
Hi @xzlin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@xzlin Our team recently added a set of new test cases from another contribution. Your solution now fails on one of those newly added test case. Therefore, we will not be adding the test case from this report. Thank you for your understanding.
