### ISSUE TITLE
Solution #3 in Python - 1235. Maximum Profit in Job Scheduling

### ISSUE THREAD

**Issue by james4388** [LeetCode-Feedback/LeetCode-Feedback#4630]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
from heapq import heappush, heappop

class Solution:
    def jobScheduling(self, startTime: List[int], endTime: List[int], profit: List[int]) -> int:
        jobs = sorted(zip(startTime, endTime, profit))
        maxprofit = 0
        heap = []
        
        for start, end, profit in jobs:
            while heap and start >= heap[0][0]:
                maxprofit = max(maxprofit, heap[0][1])
                heappop(heap)
            
            combined_job = (end, profit + maxprofit)
            
            heappush(heap, combined_job)
            
        while heap:
            maxprofit = max(maxprofit, heap[0][1])
            heappop(heap)
        
        return maxprofit
```

**Comment by lc-kay** [comment]
@james4388 We highly encourage all our users to post their solutions in the problem discuss section for other users to view and reference. 

We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
