### ISSUE TITLE
#556 测试用例有误

### ISSUE THREAD

**Issue by GitTomorrow** [LeetCode-Feedback/LeetCode-Feedback#4631]
**tomorrow-33s**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 测试用例

**描述**
描述你遇到的 bug
测试用例有误
2147483846 is not a valid value of type integer

**你使用的语言**
java 
**你提交或者运行的代码**
```
// 556
class Solution {
    public int nextGreaterElement(int n) {
        if (n > Integer.MAX_VALUE) {
            return -1;
        }
        String str = String.valueOf(n);
        int i = str.length() - 1;
        while (i > 0 && str.charAt(i) <= str.charAt(i - 1)) {
            i--;
        }
        if (i <= 0) {
            return -1;
        }
        i--;
        int max = Integer.valueOf(str.charAt(i) - '0');
        int min = max;
        int j = i + 1;
        int minIndex = j;
        for (; j < str.length(); j++) {
            if (Integer.valueOf(str.charAt(j) - '0') > min) {
                min = Integer.valueOf(str.charAt(j) - '0');
                minIndex = j;
            }
        }
        String newStr = str.substring(0, i) + min;
        String remain = str.substring(i + 1, minIndex) + max;
        if (minIndex != str.length() - 1) {
            remain = remain + str.substring(minIndex + 1);
        }
        char[] arr = remain.toCharArray();
        Arrays.sort(arr);
        for (char c : arr) {
            newStr += c;
        }
        long res = Long.valueOf(newStr);
        return (int) (res > Integer.MAX_VALUE ? -1 : res);
    }
}
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
2147483846 已经超出了 32 位有符号整型的范围，因此不是有效的测试用例。有什么问题吗？

**Comment by GitTomorrow** [comment]
> 2147483846 已经超出了 32 位有符号整型的范围，因此不是有效的测试用例。有什么问题吗？
现在提交就报错

**Comment by GitTomorrow** [comment]
提交就报错，没法过




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月29日(星期天) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] #556 测试用例有误 (#4631)





 
2147483846 已经超出了 32 位有符号整型的范围，因此不是有效的测试用例。有什么问题吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GitTomorrow** [comment]
![image](https://user-images.githubusercontent.com/22544858/131252921-bc53e5a8-0185-4253-aab7-16dc97440d18.png)

**Comment by stormsunshine** [comment]
请检查你的截图和你的代码是否一致。我运行你的代码显示 2147483476 这个测试用例结果错误。
注意你的截图中的最后执行的输入是2147483486，是在转换过程中出错的，并非原始测试用例的问题。是你的代码错误，而不是测试用例的问题。

**Comment by GitTomorrow** [comment]
那个图片不是说明超出范围的测试用例是官方的嘛------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月29日(星期天) 晚上10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] #556 测试用例有误 (#4631)

**Comment by stormsunshine** [comment]
你根本没有看懂测试用例是什么，你的截图和你的代码也不相符。
我说得很明确了，从你的截图中可以看到，执行出错的测试用例是 2147483486，这个数字没有超出 32 位有符号整数范围！是你的代码在执行过程中得到 2147483846，在使用 `Integer.valueOf` 将字符串转成 `int` 时出错，因为 2147483846 超出了 32 位有符号整数范围。
测试用例是 2147483486，哪里超出范围了？2147483846 是你的代码执行过程中得到的，和输入的测试用例完全是两回事！

**Comment by GitTomorrow** [comment]
不好意思 我再检查下------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月29日(星期天) 晚上10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] #556 测试用例有误 (#4631)
