### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by HuseyinOzkaya** [LeetCode-Feedback/LeetCode-Feedback#4633]
#### Your LeetCode username
class Solution {
    public String longestPalindrome(String s) {
     
		String m=s;
		String mReversed="";
		String mOutput="";

		for (int i=0;i<s.length();i++) {
			for(int j=i; j<s.length();j++) {
			//	System.out.println("substring start: "+  i + "substring end : " + j );
			m=s.substring(i, j+1);
		
			mReversed="";
			for(int q= m.length()-1; q>=0; q--) {
				mReversed+=m.charAt(q);
			}
			
			if((m.equals(mReversed)) && (mOutput.length()< mReversed.length())) {
				mOutput = mReversed;
			}
				
			}
			
		}
		
		}
        return mOutput;
   

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ Time Limit Exceeded] Missing Test Cases 
- Time Limit Exceeded

#### Description of the bug
Failed Test Case
"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth"

it word on eclipse and return longest one,

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@HuseyinOzkaya Can you please provide the submission details link to your code? Thank you!

**Comment by lc-kay** [comment]
Hi @HuseyinOzkaya 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
