### ISSUE TITLE
Missing Test Case - 940. Distinct Subsequences II

### ISSUE THREAD

**Issue by yukinosnow** [LeetCode-Feedback/LeetCode-Feedback#4634]
#### Your LeetCode username
zhengenze

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the problem description for example 2, the given input is "aba" and the explanation is not correct. In the question, the given example input is "aba" and the Explanation is "The 6 distinct subsequences are "a", "b", "ab", "aa", "ba", and "abc"." and the last element should "aba" instead of "abc". This is just a minor error.

#### Code you used for Submit/Run operation

```
//This issue is about the problem description but I put my code in here just in case
class Solution {
    public int distinctSubseqII(String s) {
        int mod=(int)1e9+7;
        int[]arr=new int[26];
        char[]word=s.toCharArray();
        long result=0;
        for(int i=0;i<word.length;i++)
        {
            long sum=0;
            int position=(int)(word[i]-'a');
            for(int j=0;j<26;j++)
            {
                if(j==position)
                    continue;
                sum+=arr[j];
            }
            arr[position]=(int)((arr[position]+sum+1)%mod);
        }
        for(int i=0;i<26;i++)
            result+=arr[i];
        return(int)(result%mod);
        
    }
}
```

#### Expected behavior

This issue is about the problem description

#### Screenshots

![Screenshot 2021-08-29 145932](https://user-images.githubusercontent.com/18171975/131266684-dc3e4f60-8298-4ece-b689-151236feebc2.png)

**Comment by lc-kay** [comment]
Hi @yukinosnow 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yukinosnow 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
