### ISSUE TITLE
Missing Test Case - 1986. Minimum Number of Work Sessions to Finish the Tasks

### ISSUE THREAD

**Issue by faceplant-leetcode** [LeetCode-Feedback/LeetCode-Feedback#4636]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

#### Description of the bug
If we use greedy to solve the question, it can pass all the test case. While the test case:  
[4,4,4,4,5,5,5,5,6,6,6,6,7,7]
15 
is not working using this algorithm.

#### Code you used for Submit/Run operation

```python
result = 0
while tasks:
    i = 1
    while i < len(tasks) + 1:
        comb = combinations(tasks, i)
        for nums in list(comb):
            if sum(nums) == sessionTime:
                for num in nums:
                    tasks.remove(num)
                result += 1
                break
        else:
            i += 1
    sessionTime -= 1
return result
```

#### Language used for code
Python

**Comment by lc-kay** [comment]
Hi @faceplant-leetcode 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@faceplant-leetcode Our team recently added a set of new test cases from another contribution. Your solution now fails on one of those newly added test case. Therefore, we will not be adding the test case from this report. Thank you for your understanding.
