### ISSUE TITLE
Typo in 176

### ISSUE THREAD

**Issue by JasonEb** [LeetCode-Feedback/LeetCode-Feedback#4637]
#### Your LeetCode username
Holyoke

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the Solution's third approach with "Using IFNULL and LIMIT clause", the word `function` is misspelled as `funtion`. 

```
Approach: Using IFNULL and LIMIT clause [Accepted]
Another way to solve the 'NULL' problem is to use IFNULL funtion as below.
```

#### Screenshots
![image](https://user-images.githubusercontent.com/6300995/131288408-af1d7d3d-bab3-48cf-b58c-a14a0f5ef3b5.png)

**Comment by lc-kay** [comment]
Hi @JasonEb 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @JasonEb 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
