### ISSUE TITLE
Incorrect Solution in 176

### ISSUE THREAD

**Issue by JasonEb** [LeetCode-Feedback/LeetCode-Feedback#4638]
#### Your LeetCode username
Holyoke

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The main solution is suggested to be `Accepted` as a submission, but it still fails the challenge. 

#### Code you used for Submit/Run operation
```sql
-- Second Highest Salary 
SELECT DISTINCT
    Salary AS SecondHighestSalary
FROM
    Employee
ORDER BY Salary DESC
LIMIT 1 OFFSET 1
```

Test Case in Question
```
Input: 
{"headers": {"Employee": ["Id", "Salary"]}, "rows": {"Employee": [[1, 100]]}}
```

#### Language used for code
SQL

#### Expected behavior
Expected the suggest solution to be Accepted OR that there will be no test case for a single entry in the table. 

I think the main solution is intended to be the better solution because the single item table, or not having a second highest salary ultimately, is not as likely for a database. Nonetheless the edgecase is a very salient one to consider.

However the question's description does not clarify the scope of the edgecases, and I feel like the Solution should be more consistent with the test cases as well. 

#### Screenshots
![image](https://user-images.githubusercontent.com/6300995/131289538-7fd1f019-eae8-4a3f-827d-667fe3277ebb.png)

#### Link
https://leetcode.com/problems/second-highest-salary/

**Comment by lc-kay** [comment]
@JasonEb In the solution article, it states that 

> However, this solution will be judged as 'Wrong Answer' if there is no such second highest salary since there might be only one record in this table. To overcome this issue, we can take this as a temp table.

Please use the following code and it will be accepted. Thank you for your time.
