### ISSUE TITLE
Missing Test Case - 598. Range Addition II

### ISSUE THREAD

**Issue by HVHO** [LeetCode-Feedback/LeetCode-Feedback#4640]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

in the problem,
there is a limitation that "1 <= ops.length <= 10^4"

but in the test case,
there is a test case with no ops ( ops.length == 0 )

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @HVHO 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@HVHO Our team has reviewed this report and confirmed that it was previously fixed. Thank you for your time!
