### ISSUE TITLE
Update Solution explanation - 31. Next Permutation

### ISSUE THREAD

**Issue by lordVNSH** [LeetCode-Feedback/LeetCode-Feedback#4643]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Animation of second pointer a[j] is incorrect. Code is perfect, just the animation needs modification.

#### Code for reference
```
int j = nums.length - 1;
```

#### Expected behavior
The pointer a[j] has to start from end of array

**Comment by lc-kay** [comment]
Hi @lordVNSH 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
