### ISSUE TITLE
Wrong Test Case - 598. Range Addition II

### ISSUE THREAD

**Issue by sprkgoyal** [LeetCode-Feedback/LeetCode-Feedback#4644]
#### Your LeetCode username
sprkgoyal

#### Category of the bug
- Question

#### Description of the bug

In **Constraints**, it is given that **ops.length** will be greater than or equals to 1. But in **Example 3**, **ops.length** is 0.
A screenshot for the proof is attached herewith.

#### Screenshots

[![image](https://user-images.githubusercontent.com/46754468/131315481-71a139d4-6840-4dcb-8b3a-1894359b2880.png)](url)

**Comment by bahriddin** [comment]
I came here to post the same mistake ☝️
I am only 2 hours late 😃

**Comment by azhar1038** [comment]
Copy of #4640

**Comment by lc-kay** [comment]
@sprkgoyal Thank you for reporting this. This will be fixed with #4640. Have a great day!
