### ISSUE TITLE
Wrong Function return type - 41. First Missing Positive

### ISSUE THREAD

**Issue by deepakjsr25** [LeetCode-Feedback/LeetCode-Feedback#4646]
![2021-08-30](https://user-images.githubusercontent.com/68379114/131332914-e43fee74-df37-4eee-9eca-708fa0db46eb.png)

#### Your LeetCode username
deepakjsr25

#### Category of the bug
- [ *] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
My code is correct .  I wrote the same code in java it was all fine but in c++ submission fails.  It says 
following "Line 7: Char 31: runtime error: signed integer overflow: -2147483648 - 1 cannot be represented in type 'int' (solution.cpp)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:16:31". 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
    ```` int i = 0;
        while(i < nums.size())
        {
            int  temp2 = nums[i] -1;
            if((nums[i] <= nums.size() && nums[i] > 0) && nums[i] != nums[temp2])
            {
![2021-08-30](https://user-images.githubusercontent.com/68379114/131332945-34eab045-1f6e-44ad-994e-6524c27216d8.png)

                int temp = nums[i];
                nums[i] = nums[temp2];
                nums[temp2] = temp;
            }
            else
                i++;
        }
        
        // for(int i = 0 ; i<nums.size();i++)
        //     cout<<i<<" "<<nums[i]<<endl;
        
        for(int i = 0 ; i<nums.size();i++)
        {
            if(nums[i] != i+1)
                return (i+1);
        }
        
        return nums.size()+1;  `````
    }
};
```

#### Expected behavior
My code is correct .  I wrote the same code in java it was all fine but in c++ submission fails.  It says 
following "Line 7: Char 31: runtime error: signed integer overflow: -2147483648 - 1 cannot be represented in type 'int' (solution.cpp)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:16:31".

#### Screenshots

![2021-08-30](https://user-images.githubusercontent.com/68379114/131332980-4de945db-0132-4d71-830d-f00eb6040a87.png)

#### Additional context
The data of the function given in the question should be long type or some test cases needs to be removed

**Comment by lc-kay** [comment]
Hi @deepakjsr25 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@deepakjsr25 Our team has reviewed your report and found that this is an overflow issue and the runtime error is expected. I found this discuss post to be potentially useful - https://leetcode.com/problems/first-missing-positive/discuss/235746/runtime-error%3A-signed-integer-overflow%3A-2147483647-%2B-1-cannot-be-represented-in-type-'int Thank you for your time.
