### ISSUE TITLE
598 - Range Addition II: Typo in solution

### ISSUE THREAD

**Issue by albertbko** [LeetCode-Feedback/LeetCode-Feedback#4647]
#### Your LeetCode username

bycko

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a typo in the solution for the problem.
"This corner is given by ... where ... reprsents"

#### Expected behavior

"This corner is given by ... where ... **represents**"

#### Screenshots

![image](https://user-images.githubusercontent.com/34317030/131337769-c3bbd157-434c-4c9d-a9e5-d05d1984be8f.png)

**Comment by lc-kay** [comment]
Hi @albertbko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @albertbko 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
