### ISSUE TITLE
Incorrect submission getting accepted

### ISSUE THREAD

**Issue by sonapraneeth-a** [LeetCode-Feedback/LeetCode-Feedback#465]
**1477. Find Two Non-overlapping Sub-arrays Each With Target Sum**

#### Your LeetCode username
sonapraneeth_a

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Testcases

#### Description of the bug

An incorrect solution shows WA in when running locally but the same solution when submitted gets accepted

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minSumOfLengths(vector<int>& arr, int target) {
        vector<pair<int, pair<int,int>>> pairs;
        int sum = 0, startIdx = 0;
        for(int idx = 0; idx < arr.size(); idx++) {
            sum += arr[idx];
            if (sum > target) {
                while (sum > target) {
                    sum -= arr[startIdx];
                    startIdx++;
                }
                if (sum < 0) sum = 0;
            }
            if (sum == target) {
                pairs.push_back({idx-startIdx+1, {startIdx, idx}});
                sum -= arr[startIdx];
                startIdx++;
            }
        }
        if (pairs.size() <= 1) return -1;
        sort(begin(pairs), end(pairs));
        // for(auto val: pairs) {
        //     cout << "{" << val.first << ", " << val.second.first << ", " << val.second.second << "}; ";
        // }
        // cout << "\n";
        int min1 = INT32_MAX, min2 = INT32_MAX;
        min1 = pairs[0].first;
        for (int idx = 1; idx < pairs.size(); idx++) {
            int lF = pairs[0].second.first, lS = pairs[0].second.second;
            int rF = pairs[idx].second.first, rS = pairs[idx].second.second;
            if (!((rF <= lS  && lS <= rS) || (rF <= lF && lF <= rS))) {
                min2 = pairs[idx].first;
                break;
            }
        }
        return min1 == INT32_MAX || min2 == INT32_MAX ? -1 : min1+min2;        
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

The submitted solution should not be accepted

#### Screenshots

![image](https://user-images.githubusercontent.com/13482560/84574689-be3c3200-adc5-11ea-92fc-6c3f77b787b9.png)

**Comment by CooperCooperCooper** [comment]
Hi @sonapraneeth-a ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @sonapraneeth-a ,
Thank you for your time. Due to our most recent update for this problem prior to receiving this issue, the provided code is currently producing the result of Wrong Answer. Please take a look.
