### ISSUE TITLE
Test cases violate constraints

### ISSUE THREAD

**Issue by sterlinb** [LeetCode-Feedback/LeetCode-Feedback#4651]
#### Your LeetCode username
Ulzgoroth

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Question constraints say that 1 <= ops.length <= 10^4. However, one of the example test cases has ops.length == 0.

#### Code you used for Submit/Run operation

```
class Solution:
    def maxCount(self, m: int, n: int, ops: List[List[int]]) -> int:
        if len(ops) == 0: # forbidden by constraints
            return m*n
        
        minx, miny = (min(dim) for dim in zip(*ops))
        return minx * miny
```

#### Language used for code
Python3

#### Expected behavior
According to constraints, the if block should never run. The case that violates the constraints is one of the ones shown, so it
isn't really unexpected. Omitting the special-case if causes an runtime error on that case when ops is empty.

**Comment by lc-kay** [comment]
@sterlinb Please provide the problem number and title. Thank you!

**Comment by lc-kay** [comment]
Hi @sterlinb 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
