### ISSUE TITLE
Missing Test Case - 986. Interval List Intersections

### ISSUE THREAD

**Issue by ankitjc** [LeetCode-Feedback/LeetCode-Feedback#4653]
#### Your LeetCode username
tikna0

#### Category of the bug
- [x] Question

#### Description of the bug
Adding correct conditions for a and b

#### Additional context
the conditions for a and b should be a <= b (and not a < b)

**Comment by lc-kay** [comment]
Hi @ankitjc 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ankitjc 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
