### ISSUE TITLE
checkbox in topic list not checked

### ISSUE THREAD

**Issue by d3bgger** [LeetCode-Feedback/LeetCode-Feedback#4654]
#### Your LeetCode username
d3bgger

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I started solving some questions from a chapter with topics. Each topic has a list of questions with a checkbox that is checked when I solve the problem (and also a progress report per topic). 
If I submit the solution from the question's standalone page (not from the chapter/topic interface) then although the solution code is visible in the editor, the checkbox is not checked (it seems like it is not submitted).
Only way I found to correctly keep track of the progress is to resubmit the same question from inside the topic interface.
This makes my submission list to have duplicates.

**Comment by lc-kay** [comment]
@d3bgger Thank you for reaching out to us! The behavior you've described is our expected behavior. We intend to keep the records separate on the Explore Card. If you have any other questions, please reach out to us via our help center https://leetcode.com/support
