### ISSUE TITLE
277. Find the Celebrity: Invalid input for one of the test cases

### ISSUE THREAD

**Issue by rachelnguyen2001** [LeetCode-Feedback/LeetCode-Feedback#4655]
#### Your LeetCode username
rachelnguyen2001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Test Cases 

#### Description of the bug

The input for the 112th test case seems invalid. I think each individual subarray must be of size 3 instead of 2.

#### Code you used for Submit/Run operation

```
   public int findCelebrity(int n) {
        Stack<Integer> s = new Stack<>();
        
        for (int i = 0; i < n; i++) {
            s.push(i);
        }
        
        while (s.size() > 1) {
            int f = s.pop();
            int se = s.pop();
            
            if (knows(f, se)) {
                s.push(se);
            } else {
                s.push(f);
            }
            
        }
        
        if (s.size() == 0) {
            return -1;
        }
        
        int candidate = s.pop();
        
        for (int k = 0; k < n; k++) {
            if (candidate != k) {
                if (!knows(k, candidate)) {
                    return -1;
                }
            }
        }
        
        return candidate;
    }
```

#### Language used for code
Java

#### Expected behavior

I think each individual subarray must be of size 3 because we are specifying the relationships between people. Also, the current two subarrays in the input are the same.

#### Screenshots

![Screen Shot 2021-08-30 at 7 10 22 PM](https://user-images.githubusercontent.com/60683912/131417216-07065e30-788b-4fd7-9c55-e09364f480d2.png)

**Comment by lc-kay** [comment]
@rachelnguyen2001 The test case is valid per the constraints. For this issue, please raise it in the problem discuss section to receive support from other users. I found this post to be relevant: https://leetcode.com/problems/find-the-celebrity/discuss/559918/Weird-Test-Case Thank you for your time.
