### ISSUE TITLE
Test case of problem is invalid (646. Maximum Length of Pair Chain)

### ISSUE THREAD

**Issue by Charles-521** [LeetCode-Feedback/LeetCode-Feedback#4659]
#### Your LeetCode username

r00tdev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

test case is invalid as the value exceeds the boundary described in the questions

#### Code you used for Submit/Run operation

```
// Maximum Length of Pair Chain
public class Solution {
    public int FindLongestChain(int[][] pairs) {
        var count = new int[2000];
        
        for (var i = 0; i < count.Length; i++) {
            count[i] = -1;
        }
        
        for (var i = 0; i < pairs.Length; i++) {
            if (pairs[i][0] + 1000 > count[pairs[i][1] + 1000])
                count[pairs[i][1] + 1000] = pairs[i][0] + 1000;
        }
        
        var res = 0;
        var prev = -1;
        
        for (var i = 0; i < count.Length; i++) {
            if (count[i] > prev) {
                res++;
                prev = i;
            }
        }
        
        return res;
    }
}
```

#### Language used for code

C#

#### Expected behavior

all numbers in the pairs of test cases shall be within the range of [-1000, 1000) as described in this questions

#### Screenshots

<img width="478" alt="Screenshot 2021-08-31 at 6 07 42 PM" src="https://user-images.githubusercontent.com/2910731/131484235-3b89460b-b4ab-4182-9cb4-1abb6ff99fbc.png">

<img width="126" alt="Screenshot 2021-08-31 at 6 04 26 PM" src="https://user-images.githubusercontent.com/2910731/131483782-64cd620c-bc98-4fbe-b7df-5f6be25fe577.png">

#### Additional context

Error received using invalid test case:
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
Line 10: Solution.FindLongestChain (System.Int32[][] pairs) in Solution.cs
Line 18: __DriverSolution__.__Helper__ (System.Int32[][] param_1) in __Driver__.cs
Line 33: __Driver__.Main (System.String[] args) in __Driver__.cs
[ERROR] FATAL UNHANDLED EXCEPTION: System.IndexOutOfRangeException: Index was outside the bounds of the array.
Line 10: Solution.FindLongestChain (System.Int32[][] pairs) in Solution.cs
Line 18: __DriverSolution__.__Helper__ (System.Int32[][] param_1) in __Driver__.cs
Line 33: __Driver__.Main (System.String[] args) in __Driver__.cs

**Comment by lc-kay** [comment]
Hi @Charles-521 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Charles-521 
Thank you for your time. We have fixed the issue in the constraints. We appreciate your support!
