### ISSUE TITLE
Quick Union implementation in the article "Quick Union - Disjoint Set"

### ISSUE THREAD

**Issue by g02dev** [LeetCode-Feedback/LeetCode-Feedback#4663]
#### Your LeetCode username
g02dev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There are two different Quick Union implementations in the article "Quick Union - Disjoint Set" from the learning card "Detailed Explanation of Graph". Quick Union implementation shown in the second video uses path compression which is introduced in a later article "Path Compression Optimization".

https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3840/ 

#### Expected behavior
Same implementation of Quick Union in both videos. 

#### Screenshots

Video 1 "Explanation of Quick Union"
![Explanation of Quick Union](https://user-images.githubusercontent.com/58611737/131535845-0ae61f1e-a8f0-4822-9174-a95988ebfd27.png)

Video 2 "Why is Quick Union More Efficient than Quick Find?"
![Why is Quick Union More Efficient than Quick Find?](https://user-images.githubusercontent.com/58611737/131535950-1fab8145-0a43-4380-b3d8-7e242f0440cf.png)

**Comment by lc-kay** [comment]
Hi @g02dev 
Thank you for your time. We've noted your feedback and will make the necessary improvements in our next updates. We appreciate your support!
