### ISSUE TITLE
877. 石子游戏 测试用例过于单薄 导致很多错误的代码占据了性能榜

### ISSUE THREAD

**Issue by woasishen** [LeetCode-Feedback/LeetCode-Feedback#4668]
**76015064@qq.com**
- [x] 缺少测试用例

**描述**
本题直接return true 即可通过，打败一切

![image](https://user-images.githubusercontent.com/22291967/131621540-8be0d1b1-9b9c-4605-ad06-840cb159796b.png)

**Comment by stormsunshine** [comment]
第 877 题的条件决定了先手必胜，这是可以证明的，因此直接返回 `true` 是正确的解法。
既然认为测试用例不够，请提供结果为 `false` 的测试用例，并说明为什么结果为 `false`。
不提供测试用例就没有说服力。

**Comment by woasishen** [comment]
非常感谢您的回复。是我疏忽了，题目已经限定是偶数堆~






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月2日(星期四) 中午1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] 877. 石子游戏 测试用例过于单薄 导致很多错误的代码占据了性能榜 (#4668)





 
第 877 题的条件决定了先手必胜，这是可以证明的，因此直接返回 true 是正确的解法。
 既然认为测试用例不够，请提供结果为 false 的测试用例，并说明为什么结果为 false。
 不提供测试用例就没有说服力。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
