### ISSUE TITLE
1477. Find Two Non-overlapping Sub-arrays Each With Target Sum

### ISSUE THREAD

**Issue by Mip182** [LeetCode-Feedback/LeetCode-Feedback#467]
#### Your LeetCode username

Mip182

#### Category of the bug
- [ ] Question
- [+ ] Solution
- [ ] Language

#### Description of the bug

Hello, I'm Mip182. When I was writing Biweekly Contest 28 I had TLE on problem 1477. Find Two Non-overlapping Sub-arrays Each With Target Sum but after the contest I submit the same code and it got accepted. It's very strange, because I have O(nlogn) solution and it obviosly should be accepted in given constraints. Links to the submissions: https://leetcode.com/contest/biweekly-contest-28/submissions/detail/353066853/ (One during contest);
https://leetcode.com/submissions/detail/353171055/ (Second after);

#### Code you used for Submit/Run operation

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define pb push_back
#define mii map <int, int>
#define mll map <ll, ll>
#define pii pair <int, int>
#define pll pair <ll, ll>
#define vi vector <int>
#define vd vector <double>
#define vll vector <ll>
#define fi first
#define se second
#define si set <int>
#define sll set <ll>
#define spii set <pii>
#define vs vector <string>
#define vpii vector <pair <int,int> >
#define vpll vector <pair <long long,long long> >
#define vvi vector <vector <int> >
#define vvpii vector <vector <pii > >
#define mp make_pair
#define vvll vector <vll>
#define vsi vector <si>
#define forn(i, n) for (int i = 0; i < (n); i++)
#define rep(i, n) for (int i = 0; i < (n); i++)
#define for1(i, n) for (int i = 1; i < (n); i++)
#define all(x) (x).begin(), (x).end()
#define rall(x) (x).rbegin(),(x).rend()
#define MANX MAXN

const ll INFLL = 1e18;
const int MAXN = 1e6+100;
const ll INF = 1e9;
const ll mod1=1e9+7;
const ll mod2=2e9+11;
class Solution {
public:
    int minSumOfLengths(vector<int>& arr, int target) {
        int n=arr.size();
        vector <int> toright(n);
        vector <int> pref(n);
        vector <int> toleft(n);
        vector <int> suf(n);
        map <int,int> m;
        m[0]=0;
        int sum=0;
        int cur=INF;
        for (int i=0;i<n;i++)
        {
            sum+=arr[i];
            if (m.find(sum-target)!=m.end())
            {
                toright[i]=i+1-m[sum-target];
                cur=min(cur,toright[i]);
            }    
            m[sum]=i+1;
            pref[i]=cur;
        }
        sum=0;
        map <int,int> mm;
        mm[0]=n+1;
        cur=INF;
        int ans=INF;
        for (int i=n-1;i>=0;i--)
        {
            sum+=arr[i];
            if (mm.find(sum-target)!=mm.end())
            {
                toleft[i]=mm[sum-target]-(i+1);
                cur=min(cur,toleft[i]);
            }    
            mm[sum]=i+1;
           suf[i]=cur;
        }
        // for (int i=0;i<n;i++)
        //     cout<<pref[i]<<" ";
        // cout<<'\n';
        // for (int i=0;i<n;i++)
        //     cout<<suf[i]<<" ";
        // cout<<'\n';
        for (int i=0;i<n-1;i++)
        {
            ans=min(ans,pref[i]+suf[i+1]);   
        }
        if (ans==INF)
            return -1;
        else
            return ans;
    }
};

#### Language used for code

C++

#### Expected behavior

Hello, I'm Mip182. When I was writing Biweekly Contest 28 I had TLE on problem 1477. Find Two Non-overlapping Sub-arrays Each With Target Sum but after the contest I submit the same code and it got accepted. It's very strange, because I have O(nlogn) solution and it obviosly should be accepted in given constraints. Links to the submissions: https://leetcode.com/contest/biweekly-contest-28/submissions/detail/353066853/ (One during contest);
https://leetcode.com/submissions/detail/353171055/ (Second after);

**Comment by CooperCooperCooper** [comment]
Hi @Mip182 ,
Thank you for reaching out to us. Since we've responded to your request on the same issue in the main support channel, I will close this ticket here for now. We appreciate your support.
