### ISSUE TITLE
451. Sort Characters By Frequency - Question Clarity

### ISSUE THREAD

**Issue by mdtareque** [LeetCode-Feedback/LeetCode-Feedback#4670]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
N/A

#### Code you used for Submit/Run operation

```
/class Solution {
public:
    string frequencySort(string s) {
        map<char, int> f;
        for (auto c : s) f[c]++;
        sort(s.begin(), s.end(), [&](char a,char b){
           if (f[a] == f[b])
               return a > b;
            return f[a] > f[b];
        });
        return s;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Question should be clear what to output in case of multiple answer.

#### Screenshots
![lc - 451 question clarity](https://user-images.githubusercontent.com/794071/131636069-904ba103-b02b-44b7-a39d-09ff021d5652.png)

#### Additional context
Question doesn't mention anything about what output to print if there are multiple answers. For given input, `aaaccc` and `cccaaa` both are valid output.
In the screenshot you can see that a different output is valid, and is Accepted by question description doesn't clarify about it.

Question description should state that if there are multiple valid ordering then return any.

**Comment by lc-kay** [comment]
Hi @mdtareque 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mdtareque 
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!

**Comment by mdtareque** [comment]
@lc-kay No coins ? This is a valid content issue as the question was missing the mentioned clarity.
