### ISSUE TITLE
To find the largest number in the list

### ISSUE THREAD

**Issue by kuraakhilesh8230** [LeetCode-Feedback/LeetCode-Feedback#4671]
To find the largest number in the list

#### Your LeetCode username

akhilesh88

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

After executing it is showing their is a bug in the code,it I showing their is a missing of some code which causing the error 

#### Code you used for Submit/Run operation
<!--def max_num_in_list( list ):
    max = list[ 0 ]
    for a in list:
        if a > max:
            max = a
    return max
    ```

Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 
-->

```
// Two Sum
<!--def max_num_in_list( list ):
    max = list[ 0 ]
    for a in list:
        if a > max:
            max = a
    return max
```

#### Language used for code
<!-- C++ -->
Python

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
print(max_num_in_list([1, 2, -8, 0]))

#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
@kuraakhilesh8230 Please provide your code and the link to the problem for this issue. Thank you!

**Comment by lc-kay** [comment]
Hi @kuraakhilesh8230 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
