### ISSUE TITLE
Missing Test Case - 565. Array Nesting

### ISSUE THREAD

**Issue by adityajain9560** [LeetCode-Feedback/LeetCode-Feedback#4673]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@adityajain9560 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
