### ISSUE TITLE
Missing Test Case - 565. Array Nesting

### ISSUE THREAD

**Issue by romilshah6399** [LeetCode-Feedback/LeetCode-Feedback#4675]
#### Your LeetCode username

username:romil9

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Bug:Bug is in accepting the solution,

#### Description of the bug

 my code has a bug but still it is being accepted, I know the knew the bug by my self and wondered how can it be accepted

#### Code you used for Submit/Run operation

```
// Array nesting
class Solution {
    public int arrayNesting(int[] nums) {        
        HashSet<Integer> set=new HashSet<>();
        int previous,counter=1,buffer=1;     
        for(int i=0 ; i<nums.length ;i++,buffer=1)
        {            
            previous=nums[i];
            set.add(previous);            
            for(int j=1 ; j<nums.length ; j++)
            {             
                if(set.contains(nums[previous])) break;          
                buffer++;
                previous=nums[previous];
                set.add(previous);
            }                  
            if(buffer>counter) counter=buffer;
        }        
        return counter;
    }
}
```

#### Expected behavior

My logic behind the code is that I would check the length untill which there is no duplication by iterating through each and every element of the nums and for  that I am using set that would add the elements and once there is any duplication it would break the inner loop and move o to next loop,  now once I move on to the next loop , I am supposed to empty the string in order to make sure that I a checking the duplicacy of elements in the next iteration from the begining, which I forgot to do and submitted the code and it got accepted later on analysing the code I found by myself that there was a bug but still it got accepted

**Comment by lc-kay** [comment]
Hi @romilshah6399 
Thank you for reaching out to us. I've relayed this issue to our team to investigate. Did you happen to have a test case that this code failed on?

**Comment by romilshah6399** [comment]
Hi,
     Actually the opposite happen, my code passed all testcases with a bug
in it.
So nut sure which one but there is definitely one or more than one missing
test cases that should find bug in code as with bug also my code was
accepted which shouldn’t have happened considering the kind of bug i
mentioned in git.

**Comment by lc-kay** [comment]
Hi @romilshah6399 
Thank you for the clarification. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@romilshah6399 For this issue, do you have a counter test case that will cause this code to fail?
