### ISSUE TITLE
it says in problem definition that You can return the answer in any order but it fails test case for indexes [0, 1] and [1, 0]

### ISSUE THREAD

**Issue by manishsaxenaatg** [LeetCode-Feedback/LeetCode-Feedback#4676]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@manishsaxenaatg Please provide the problem title and number. Thank you!
