### ISSUE TITLE
Missing Test Case - 41. First Missing Positive

### ISSUE THREAD

**Issue by rishabhkumar786** [LeetCode-Feedback/LeetCode-Feedback#4678]
Here is my simple solution.
a. Sort the array.
b. Then traverse array one by one and firstly search for m = 1.
    1. if nums[i] < m just continue
    2. if nums[i] == m, m++;
    3. if nums[i] > m, break and return whatever the value of m is.

`class Solution {
public:
    int firstMissingPositive(vector<int>& nums) {
        int n = nums.size();
        sort(nums.begin(), nums.end());
        
        int m = 1;
        int i = 0;
        while(i < n){
            if(nums[i] < m) i++;
            else if(nums[i] == m)m++;
            else if(nums[i] > m) break;
        }
        return m;
    }
};`

**Comment by lc-kay** [comment]
@rishabhkumar786 The problem discuss section is the best place to share your solution for other users to reference and initiate a discussion! 

We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
