### ISSUE TITLE
June LeetCoding Challenge - Largest Divisible Subset

### ISSUE THREAD

**Issue by Manish-98** [LeetCode-Feedback/LeetCode-Feedback#468]
#### Your LeetCode username

manishlath3445

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The question was about finding the largest subset in the given array of distinct numbers such that for all the possible pairs in the subset one of the elements is the factor of the other. This clearly means that there has to be at least a "pair" of distinct number in the subset. But when i had submitted the code, a test case that failed, had a list with a single element as the answer. Even the examples given in the question didn't indicate that the solution could be a single element too

#### Code you used for Submit/Run operation
```
import copy

class Solution(object):
    
    def checkSub(self, subset):
        for i in range(len(subset) - 1):
            for j in range(i + 1, len(subset)):
                if(subset[i] % subset[j] != 0 and subset[j] % subset[i] != 0):
                    return 0
        return 1
    
    
    def genSubs(self, subsets, index):
        temp1 = copy.deepcopy(subsets)
        temp = [i for i in temp1 if(len(i) > 2)]
        elem = subsets[0][index]
        for i in range(len(temp)):
            temp[i].remove(elem)
            
        return temp
    
    def largestDivisibleSubset(self, nums):
        """
        :type nums: List[int]
        :rtype: List[int]
        """
        
        subsets = [nums[:]]
        largest = []
        index = 0
        count = 0
        
        while(index < len(nums)):
            for i in range(count, len(subsets)):
                if(self.checkSub(subsets[i]) == 1 and len(largest) < len(subsets[i])):
                    largest = subsets[i]
            count = len(subsets)
            subsets.extend(self.genSubs(subsets, index))
            index += 1
            
        return largest
```

#### Language used for code

Python 3

#### Expected behavior

I had expected that the solutions to the various inputs would have at least two elements (or none if such a solution could not be found) but one of the test cases was failing because it had a single element as the solution.

**Comment by CooperCooperCooper** [comment]
Hi @Manish-98 ,
Thank you for reaching out to us. Would you please share the test case here with us?

**Comment by lc-kate** [comment]
Hi @Manish-98 ,

Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag @lc-christina  in a new comment. Thank you.
