### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by KevinDaSilvaS** [LeetCode-Feedback/LeetCode-Feedback#4681]
#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
My solution in javascript apparently is working properly, but when i run my code using the leetcode input I get a fail attempted but output is == the expected. 

#### Code you used for Submit/Run operation

```
let symbolStack = [];

let head = -1;

const opening = {
    '(': true,
    '[': true,
    '{': true
}

const closing = {
    ')': '(',
    ']': '[',
    '}': '{'
}

var isValid = function(s) {
    return checkSymbolStack(s);
};

const checkSymbolStack = (s) => {

    if(s === "" && head <= -1) {
        return true
    }
    
    const firstSymbol = s.charAt(0);
    const remain = s.slice(1, s.length)
    
    if(opening[firstSymbol]) {
        pushSymbolStack(firstSymbol);
        return checkSymbolStack(remain);
    }

    if(closing[firstSymbol] === symbolStack[head]) {
        popSymbolStack();
        return checkSymbolStack(remain);
        
    }
    
    return false;
    
}

const pushSymbolStack = (elem) => {
    symbolStack.push(elem);
    head += 1;
}

const popSymbolStack = () => {
    symbolStack.pop();
    head -= 1;  
}
```

#### Language used for code
JS

#### Expected behavior
It was expected to return a successful attempt intead of an error expected != actual

#### Screenshots
![image](https://user-images.githubusercontent.com/47486196/131894550-bd92da32-68b0-454b-96f4-01f3dc026f86.png)

**Comment by lc-kay** [comment]
Hi @KevinDaSilvaS 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
