### ISSUE TITLE
https://leetcode-cn.com/problems/smallest-k-lcci/题目java编译问题

### ISSUE THREAD

**Issue by ZhaoJun03** [LeetCode-Feedback/LeetCode-Feedback#4684]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
zhaojun302563746
**Bug 类型**
- [x] 编程语言  

**描述**
编译错误

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    public int[] smallestK(int[] arr, int k) {
        PriorityQueue<Integer> priorityQueue = new PriorityQueue<>(k, (o1, o2) -> o2 - o1);
        int i = 0;
        for (; i < k; i++) {
            priorityQueue.add(arr[i]);
        }
        for (; i < arr.length; i++) {
            priorityQueue.add(arr[i]);
            priorityQueue.remove();
        }
        return priorityQueue.stream().mapToInt(Integer::intValue).toArray();
    }
}
```

**期望行为**
之处运行

**屏幕截图**
![image](https://user-images.githubusercontent.com/19756682/131943828-7012ce21-a333-48da-8ff4-c8c8c4d0ebf1.png)

**额外的上下文**
PriorityQueue类的构造函数，第一个可以添加初始化容量大小

**Comment by feiceh** [comment]
您好，在与相关团队核实后：由于 k=0 产生的问题， PriorityQueue（IllegalArgumentException - 如果 initialCapacity小于1）
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。

**Comment by ZhaoJun03** [comment]
我的我的  原来是运行时异常
