### ISSUE TITLE
Missing Test Case - 1721. Swapping Nodes in a Linked List

### ISSUE THREAD

**Issue by 19BCS1314** [LeetCode-Feedback/LeetCode-Feedback#4686]
#### Your LeetCode username
 **19BCS1314**

#### Category of the bug
**- [ ] Question 1721. Swapping Nodes in a Linked List**

- [ ] Solution
- **[ ] Language C++** 
**- [ ] Missing Test Cases : TESTCASES NOT RESPONDING CORRECTLY**

#### Description of the bug

**I HAVE RUN THE VARIOUS INPUT AND THE OUTPUT SHOWS ME ACCEPTED BUT WHILE SUBMITTING  IT GIVE WRONG ANSWER FOR THE SAME INPUT  THAT HAS BEEN ACCEPTED**

#### Code you used for Submit/Run operation

**MY CODE**
```
class Solution {
public:

    
       void print_reverse(ListNode* temphead,ListNode** firstvalue,ListNode** secondvalue, int n){
            static int firstlen=n;  //CREATING TWO VARIABLES FOR TAKING IT TO N STEPS;
            static int secondlen=n;
           if(temphead==NULL) return;
           firstlen--;  
           if(firstlen==0) *firstvalue=temphead;    // STORES THE FIRST ADDRESS 
           print_reverse(temphead->next,firstvalue,secondvalue,n);
            secondlen--;
            if(secondlen==0) *secondvalue=temphead; //STORES THE SECOND ADDRESS
    }
    
    ListNode* swapNodes(ListNode* head, int k) {
        if(head->next==NULL) return head;// IF THERE CONSISTS ONLY ONE NODE
        
        ListNode* firstvalue=head,*secondvalue=head; // JUST FOR INITIALISATION 
        print_reverse(head,&firstvalue,&secondvalue ,k);// CALLING THE FUNCTION FOR GETTING THE ADDRESS OF TWO POINTER 

        int temp2=secondvalue->val;//STORE VALUES AT THE TEMPORARY VARIABLE 
        int temp1=firstvalue->val;
        firstvalue->val=temp2; //ASSIGNNIG VALUE TO THE FIRST AND LAST NODE NODE 
        secondvalue->val=temp1;
        
        return head;// RETURNNIG HEAD
    }
};
```

#### Language used for code c

**C++**

#### Expected behavior

WRONG ANSWER
![image](https://user-images.githubusercontent.com/82868470/131957735-4685b710-4aef-4fc2-a911-4252e7808c51.png)

CORRECT ANSWER FOR SAME INPUT  ON RUNNIG CODE-->

![image](https://user-images.githubusercontent.com/82868470/131958019-1d2a3bce-a14c-4038-893b-dd067e695cb4.png)

#### Screenshots

**PLEASE CHECK THE ABOVE SCREEN SHOT**

**Comment by lc-kay** [comment]
Hi @19BCS1314 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
