### ISSUE TITLE
Problem 587. Erect the Fence Solution typo

### ISSUE THREAD

**Issue by longchass** [LeetCode-Feedback/LeetCode-Feedback#4688]
#### Your LeetCode username
qll998

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem 587. Erect the Fence
In the provided Jarvis Algorithm in the solutions there is a small typo
during the cross matrix multiplication
it shows

|(qx - px)    (qy - py)|
|(rx - qx)     (ry - py)|
                incorrect^

#### Expected behavior
|(qx - px)    (qy - py)|
|(rx - qx)     (ry - qy)|

as shown by the article itself below the expansion of the cross product is correct
(qx - px)  * (ry - qy) - (qy - py) * (rx - qx)  

#### Screenshots
Screenshot of section I described 
https://imgur.com/a/Oz6YsGk

**Comment by lc-kay** [comment]
Hi @longchass 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by longchass** [comment]
The typo has been corrected. Closing the issue now
