### ISSUE TITLE
1293. Shortest Path in a Grid with Obstacles Elimination

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#469]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Incorrect solution gets accepted

#### Code you used for Submit/Run operation
```
class Solution:
    def shortestPath(self, g: List[List[int]], k: int) -> int:
        n=len(g)
        m=len(g[0])
        q=deque([(n-1,m-1,k)])
        s=set(q)
        c=0
        while q:
            for _ in range(len(q)):
                x,y,k=q.popleft()
                if k>=x+y-1:
                    return c+x+y
                for i,j in (x,y+1),(x,y-1),(x+1,y),(x-1,y):
                    if 0<=i<n and 0<=j<m and k-g[i][j]>=0 and (i,j,k-g[i][j]) not in s:
                        q.append((i,j,k-g[i][j]))
                        s.add(q[-1])
            c+=1
        return -1
```

#### Language used for code
Python

#### Expected behavior
Should fail this test case

```
[[0,0],[1,0],[1,0],[1,0],[1,0],[1,0],[0,0],[0,1],[0,1],[0,1],[0,0],[1,0],[1,0],[0,0]]
4
```

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. The language for you code should be Python3 instead of Python. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
