### ISSUE TITLE
Missing Test Case - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by prancoding** [LeetCode-Feedback/LeetCode-Feedback#4690]
#### Your LeetCode username

user3547q

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

There is this one test case for which many code should fail, but they result in successfull submissions. This testcase needs to be added for this question.
The tescase - 
```
"cbcbbaaa"
3
```

The above testcase should be added to this question.

#### Code you used for Submit/Run operation

```
// sol
class Solution {
public:
    int longestSubstring(string s, int k) {
        unordered_map<char, vector<int>> m;
        int ans=0;
        for(int i=0;i<s.length();++i){
            m[s[i]].push_back(i);
            if(m[s[i]].size()>=k){
                int maxl=0;
                for(auto itr=m.begin();itr!=m.end();++itr){
                    vector<int> v=itr->second;
                    if(v.size()<k || v[v.size()-k]<maxl){maxl=max(maxl,v.back()+1);}
                }
                if(maxl<=m[s[i]][m[s[i]].size()-k]){ans=max(ans,i-maxl+1);}
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected this to be a non acceptable submissions as it fails for the following case
```
"cbcbbaaa"
3
```

But it is observed that this submission is considered correct.

**Comment by lc-kay** [comment]
Hi @prancoding 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @prancoding 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
