### ISSUE TITLE
Missing Test Case - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by prashant-15** [LeetCode-Feedback/LeetCode-Feedback#4691]
#### Your LeetCode username
prashantbaghel215

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
The attached code is accepted as a solution although it fails the below given testcase:
   "ababbccc"
   3

#### Code you used for Submit/Run operation

```
// 395 Longest Substring with At Least K Repeating Characters
class Solution {
public:
    int longestSubstring(string s, int k) {
        unordered_map<char, vector<int>> m;
        int ans=0;
        for(int i=0;i<s.length();++i){
            m[s[i]].push_back(i);
            if(m[s[i]].size()>=k){
                int maxl=0;
                for(auto itr=m.begin();itr!=m.end();++itr){
                    vector<int> v=itr->second;
                    if(v.size()<k || v[v.size()-k]<maxl){maxl=max(maxl,v.back()+1);}
                }
                if(maxl<=m[s[i]][m[s[i]].size()-k]){ans=max(ans,i-maxl+1);}
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The solution should have been rejected instead of being accepted as it clearly fails the above testcase.

#### Screenshots
<img width="386" alt="Screenshot 2021-09-03 at 20 00 19" src="https://user-images.githubusercontent.com/69323708/132022186-d82e879a-4f9c-423e-a865-3c61ecb9a543.png">

**Comment by lc-kay** [comment]
Hi @prashant-15 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@prashant-15 This solution currently fails on a newly added test case. Therefore we will not add your reported missing test case. Thank you for your time.
