### ISSUE TITLE
Missing Test Case - 489. Robot Room Cleaner

### ISSUE THREAD

**Issue by neurologicalstyle** [LeetCode-Feedback/LeetCode-Feedback#4692]
#### Your LeetCode username
neurologicalstyle

#### Category of the bug
Solution

#### Description of the bug

My code fails for the submission test case:
```
[[1],[1]]
0
0
```
but passes when I use the same test case in console.

#### Code you used for Submit/Run operation

```
// Robot Room Cleaner
class Solution:
    def cleanRoom(self, robot, path = set(), pos = (0, 0), dx = 0, dy = 1):
        """
        :type robot: Robot
        :rtype: None
        """
        path.add(pos)
        robot.clean()
        for _ in range(4):
            if (pos[0] + dx, pos[1] + dy) not in path and robot.move():
                self.cleanRoom(robot, path, (pos[0] + dx, pos[1] + dy), dx, dy)
                robot.turnRight()
                robot.turnRight()
                robot.move()
                robot.turnLeft()
            else:
                robot.turnRight()
            dx, dy = -dy, dx
```

#### Language used for code
Python3

#### Expected behavior

I expect that if it passes the test case that I do as manual input, it should pass the submission test case as well.

**Comment by lc-kay** [comment]
Hi @neurologicalstyle 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
