### ISSUE TITLE
Typo in test cases for 802. Find Eventual Safe States

### ISSUE THREAD

**Issue by bclodius** [LeetCode-Feedback/LeetCode-Feedback#4693]
#### Your LeetCode username
**b_clodius**

https://leetcode.com/b_clodius/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Typo in assertion for test inputs for https://leetcode.com/problems/find-eventual-safe-states/

#### Code you used for Submit/Run operation
```
[]
```

#### Language used for code
N/A any language

#### Expected behavior
`edjges` should be spelled `edges`

#### Screenshots
![image](https://user-images.githubusercontent.com/590724/132077190-f120b07b-eb35-44bb-8565-3ce6cfb61cfc.png)

#### Additional context
Test input only; not actual submission code.

**Comment by tejasvising** [comment]
Hey! I am really grateful to leetcode and would love to contribute to it in anyway possible. If anyone has not been assigned this issue, may I?

**Comment by lc-kay** [comment]
Hi @bclodius 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@tejasvising Thank you for the offer! For current content contribution openings, please visit leetcode.com/jobs.

**Comment by lc-kay** [comment]
Hi @bclodius 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
