### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by Pisces311** [LeetCode-Feedback/LeetCode-Feedback#4696]
#### Your LeetCode username

Pisces311

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In this problem, a simple test case: `s = "aaa"`, `p = "a*"` is missing. My code failed on this test case but was accepted. The correct return value should be `true` but mine is `false`.

#### Code you used for Submit/Run operation

``` go
func isMatch(s string, p string) bool {
	n, m := len(s), len(p)
	dp := make([][]bool, n+1)
	for i := 0; i <= n; i++ {
		dp[i] = make([]bool, m+1)
	}
	dp[0][0] = true
	s, p = "#"+s, "#"+p
	for j := 1; j <= m; j++ {
		if j > 1 && dp[0][j-2] && p[j] == '*' {
			dp[0][j] = true
		}
	}
	for i := 1; i <= n; i++ {
		for j := 1; j <= m; j++ {
			if dp[i-1][j-1] {
				if s[i] == p[j] || p[j] == '.' {
					dp[i][j] = true
				} else if p[j] == '*' {
					if s[i] == s[i-1] || p[j-1] == '.' {
						dp[i][j] = true
					}
				}
			}
			if dp[i-1][j] && p[j] == '*' {
				if p[j-1] == '.' {
					dp[i][j] = true
				}
			}
			if dp[i][j-1] && p[j] == '*' {
				dp[i][j] = true
			}
			if j > 1 && dp[i][j-2] && p[j] == '*' {
				dp[i][j] = true
			}
		}
	}
	return dp[n][m]
}
```

#### Language used for code

Golang

#### Expected behavior

return `true`

**Comment by lc-kay** [comment]
Hi @Pisces311 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Pisces311 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
