### ISSUE TITLE
Extra iteration in rotate image

### ISSUE THREAD

**Issue by MaximumEndurance** [LeetCode-Feedback/LeetCode-Feedback#4697]
#### Category of the bug
- [ ] Question
- [-] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Rotate Image question, https://leetcode.com/problems/rotate-image/
In solution 2, in the transpose function, the inner j loop can start from j=i+1. With j=i, we have one redundant step of swapping the element with itself.

#### Code you used for Submit/Run operation

```
    public void transpose(int[][] matrix) {
        int R = matrix.length;
        int C = matrix[0].length;
        
        for(int i = 0; i < R; ++i) {
            for(int j = i+1; j < C; ++j) {
                swap(matrix, i, j);
            }
        }
    }
```

#### Language used for code
Java

**Comment by lc-kay** [comment]
Hi @MaximumEndurance 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @MaximumEndurance 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
