### ISSUE TITLE
Missing Test Case - 1721. Using divide and conquer 

### ISSUE THREAD

**Issue by HuyTran7801** [LeetCode-Feedback/LeetCode-Feedback#4698]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@HuyTran7801 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
