### ISSUE TITLE
Judge issue - 1993. Operations on Tree

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#4699]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution is incorrect as per given question
Please    rejudge the question - wasted so much of time on this

#### Code you used for Submit/Run operation

Test case is here - https://leetcode.com/problems/operations-on-tree/discuss/1445611/Bug-in-Q3
Code is here - https://leetcode.com/problems/operations-on-tree/discuss/1445634/1993.-Operations-on-Tree

#### Language used for code
JavaScript

#### Expected behavior

Judge must abide rules of question
Here it is not.

#### Screenshots

Upgrade unlocks even when locked by other user

![image](https://user-images.githubusercontent.com/8236389/132119259-f8ecfeb0-add5-4c7d-8e1b-7d35f74dbb99.png)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@manoharreddyporeddy Our team has reviewed this problem and found the issue to be with the problem statement. We've updated it for clarification. Thank you for your time.
