### ISSUE TITLE
[UI] Tree visualizer

### ISSUE THREAD

**Issue by m-Just** [LeetCode-Feedback/LeetCode-Feedback#47]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Unable to use the tree visualizer in Problem 116 & 117.

**Expected behavior**
There should be a tree visualizer toggle in the console panel.
![image](https://user-images.githubusercontent.com/11477925/76951837-3f129b80-6947-11ea-90f0-8adbcffc6cea.png)

**Comment by CooperCooperCooper** [comment]
Hi @m-Just,
Thank you for raising this issue to our attention. Since this is an UI issue, please file it to our technical support channel here: https://support.leetcode.com/hc/en-us. We appreciate your time and support.
