### ISSUE TITLE
366. Find Leaves of Binary Tree

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#470]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Answers contradictory to description being accepted

#### Expected behavior

The following 4 solutions produce different output and are accepted. They could be considered in contradiction of 

> collect a tree's nodes as if you were doing this: Collect and remove all leaves, repeat until the tree is empty

as according to some of the outputs root is removed first. It should be specified that order does not matter or the incorrect order solutions should not pass. 

Input

```
[1,2,3,4,5]
```

```
class Solution(object):
    def findLeaves(self, r):
        def f(r):
            if r:
                l=f(r.left)
                u=f(r.right)
                d[max(l,u)+1].append(r.val)
                return max(l,u)+1
            return 0
        d=defaultdict(list)
        f(r)
        return d.values()
```

Output

```
[[4,5,3],[2],[1]]
```

```
class Solution(object):
    def findLeaves(self, r):
        def f(r):
            if r:
                l=f(r.right)
                u=f(r.left)
                d[max(l,u)+1].append(r.val)
                return max(l,u)+1
            return 0
        d=defaultdict(list)
        f(r)
        return d.values()
```

Output

```
[[3,5,4],[2],[1]]
```

```
class Solution(object):
    def findLeaves(self, r):
        def f(r):
            if r:
                l=f(r.right)
                u=f(r.left)
                d[max(l,u)+1].append(r.val)
                return max(l,u)+1
            return 0
        d=defaultdict(list)
        f(r)
        return d.values()[::-1]
```

Output

```
[[1],[2],[3,5,4]]
```

```
class Solution(object):
    def findLeaves(self, r):
        def f(r):
            if r:
                l=f(r.left)
                u=f(r.right)
                d[max(l,u)+1].append(r.val)
                return max(l,u)+1
            return 0
        d=defaultdict(list)
        f(r)
        return d.values()[::-1]
```

Output

```
[[1],[2],[4,5,3]]
```

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by leet212** [comment]
Hello @lc-kate 
Any update on this?

**Comment by lc-christina** [comment]
Hi @leet212 ,
Thanks for following up! The team is still working on this issue. I'll let you know when I receive updates. Thank you again for the support and for being patient!

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
