### ISSUE TITLE
Missing Test Case - 899. Orderly Queue

### ISSUE THREAD

**Issue by odwl** [LeetCode-Feedback/LeetCode-Feedback#4700]
#### Your LeetCode username
odewolf

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

I have a code that passes all leetcode test cases but that is nevertheless wrong.
Would like to add a testcase

#### Code you used for Submit/Run operation

```
class Solution:
    def orderlyQueue(self, s: str, k: int) -> str:
        return lexi(s, k)
        
def lexi(txt, k):
  if k == 1:
    candidates = [(txt[i:] if i < len(txt) - 1 else txt[i:] + txt[0], i) for i, c in enumerate(txt) if c == min(txt)]
    pivot = min(candidates)[1]
    return txt[pivot:] + txt[:pivot]
  
  return ''.join(sorted(txt))
```

#### Language used for code

python

#### Expected behavior

this test cases:
"ceabcdab"
1

Should give: "abcdabce"
but is giving: "abceabcd"  which is incorrect.

#### Screenshots

![Screen Shot 2021-09-05 at 16 36 46](https://user-images.githubusercontent.com/88218/132130781-43b12d72-eca8-484f-b8e0-00f196e1ab2b.png)

#### Additional context

Would be nice to add this testcase:

"ceabcdab"
1

**Comment by lc-kay** [comment]
Hi @odwl 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @odwl 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
