### ISSUE TITLE
Missing Test Case - 899. Orderly Queue

### ISSUE THREAD

**Issue by swbedoya** [LeetCode-Feedback/LeetCode-Feedback#4701]
#### Your LeetCode username

swbedoya

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution was accepted, but I realized that it wouldn't 
return anything if the input was k = 1 and a string consisting 
only of one character (e.g., "aaaaa"). My code optimizes 
the string rotation by only considering rotations with the 
minimum beginning substring and eventually narrowing this 
down to the best string. My code, however, assumed there 
is more than one unique character in the string and thus one 
unique best rotation. Since this type of string isn't 
technically disallowed in the problem description, I think 
there should be a test case for this. 

#### Code you used for Submit/Run operation

```
class Solution:
    def orderlyQueue(self, s: str, k: int) -> str:
        if k == 1:
            n = len(s)
            idxs = range(n)
            
            for j in range(n):
                min_char = min([s[(i + 1) % n] for i in idxs])
                idxs = [(i + 1) % n for i in idxs if s[(i + 1) % n] == min_char]
                
                if len(idxs) == 1:
                    return s[idxs[0]-j:] + s[:idxs[0]-j]
        else:
            return ''.join(sorted(s))
```

#### Language used for code

Python3

#### Expected behavior

My code should've failed upon submission with a test case 
consisting of a string with only one unique character (e.g., "aaaaa")

**Comment by lc-kay** [comment]
Hi @swbedoya 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @swbedoya 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
