### ISSUE TITLE
Missing Test Case - 1997. First Day Where You Have Been in All the Rooms

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#4703]
#### Your LeetCode username

aestheticsjtu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

During yesterday's weekly contest 257, 1st place user @arignote submitted the code below using incorrect floor modulus "1000000009" and got accepted. To be more specific, it is in this line "dp[i] = (sum[i - 1] - sum[nextVisit[i - 1]] + **1000000009**) % 1000000007;" in which it should be + 1000000007 instead of + 1000000009. Additionally, this user is using type int in Java, which can cause overflow since int type only handle values up to 10^9, so we should also have a test case checking that users should've used long type.

#### Code you used for Submit/Run operation

```
class Solution {

	public int firstDayBeenInAllRooms(int[] nextVisit) {
		int[] dp = new int[nextVisit.length], sum = new int[nextVisit.length];
		for (int i = 1; i < nextVisit.length; i++) {
			dp[i] = (sum[i - 1] - sum[nextVisit[i - 1]] + 1000000009) % 1000000007; //ERROR: + 1000000009 is incorrect.
			sum[i] = (sum[i - 1] + dp[i]) % 1000000007;
		}
		return sum[nextVisit.length - 1];
	}
}
```

#### Language used for code

Java

#### Expected behavior

The exact test is too large to include in this text but if you ran a test case that leads to the negative values in sum exceeding 1000000009, this code will produce incorrect result. Or the result of sum exceeds 32 bit integer, which this code can also not handle.

**Comment by lc-kay** [comment]
Hi @ThomasShaw1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate. To help us validate the issue, can you please provide the large test case in a .txt file?

**Comment by lc-kay** [comment]
@ThomasShaw1 The user rewrote (sum[i - 1] - sum[nextVisit[i - 1]] + 2 + 1000000007) as(sum[i - 1] - sum[nextVisit[i - 1]] + 1000000009). And this solution is ok to pass. If you have a counter test case, you are welcome to provide it! I'll open this ticket again when a test case is added. Thank you for your time!
