### ISSUE TITLE
Missing Test Case - 899. Orderly Queue

### ISSUE THREAD

**Issue by neeraj97** [LeetCode-Feedback/LeetCode-Feedback#4705]
#### Your LeetCode username

user0554p

#### Category of the bug
- [X] Missing Test Cases 

#### Description of the bug

The missing test case is in the case where k=1, where we need to find the lexicographically smallest string by removing the
first letter and appending to the end of the string and this operation can be performed any number of times.
String s = "dabeab" &  k=1
**Expected output**: abdabe
**Submitted Code Output**: abeabd
There are no test cases for the situation like below:
d**ab**e**ab**
fe**cd**fer**cd**
where part of the ending sub-string (fecdfer**cd** ) is present in the string(fe**cd**fercd ) and the lexicographically smallest string is from the ending sub-string.

#### Code you used for Submit/Run operation

```
class Solution {
        public String orderlyQueue(String s, int k) {
        if (k > 1) {
            int hash[] = new int[26];
            for (int i = 0; i < s.length(); i++)
                hash[s.charAt(i) - 'a']++;
            char[] c = new char[s.length()];
            int index = 0;
            for (int i = 0; i < 26; i++) {
                int num = hash[i];
                while (num > 0) {
                    c[index] = (char) (i + 'a');
                    index++;
                    num--;
                }
            }
            return new String(c);
        }
        int minIndex = 0;
        int i = 1;
        while (i < s.length()) {
            if (s.charAt(i) < s.charAt(minIndex)) {
                minIndex = i;
                i++;
            } else if (s.charAt(i) == s.charAt(minIndex)) {
                int j = 0;
                while (i + j < s.length() && s.charAt(i + j) >= s.charAt(minIndex) && s.charAt(i + j) == s.charAt(minIndex + j)) {
                    j++;
                }
                if (i + j == s.length()) {
                    i = i + j;
                } else if (s.charAt(i + j) < s.charAt(minIndex)) {
                    minIndex = i + j;
                    i = i + j + 1;
                } else if (s.charAt(i + j) < s.charAt(minIndex + j)) {
                    minIndex = i;
                    i = i + j + 1;
                } else {
                    i = i + j + 1;
                }
            }
            else{
                i++;
            }
        }

        return s.substring(minIndex) + s.substring(0, minIndex);
    }
}
```

#### Language used for code

Java

#### Expected behavior

String s = "dabeab" &  k=1
**Expected output**: abdabe
**Submitted Code Output**: abeabd
The verdict should be wrong answer.
The test case is missing.

#### Screenshots

![image](https://user-images.githubusercontent.com/17954079/132134585-c3f53de0-6958-44d9-abaf-fd39950c582d.png)

**Comment by lc-kay** [comment]
Hi @neeraj97 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @neeraj97 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
