### ISSUE TITLE
Incorrect Hint 2 - 1992. Find All Groups of Farmland

### ISSUE THREAD

**Issue by thangarajn1992** [LeetCode-Feedback/LeetCode-Feedback#4707]
#### Your LeetCode username
thangarajn1992

#### Category of the bug
- [ ] Hints

#### Description of the bug
Hint 2 provided in the problem is incorrect. "Similarly, the top left corner of each group will have the largest x-coordinate and y-coordinate of any farmland in the group."

#### Expected behavior
It is not top-left corner, but it is bottom right.

The ideal Hint 2 content should be "Similarly, the bottom right corner of each group will have the largest x-coordinate and y-coordinate of any farmland in the group."

**Comment by lc-kay** [comment]
Hi @thangarajn1992 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
