### ISSUE TITLE
778. Swim in Rising Water

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#471]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
I wished to provide a solution for the problem that is not available.

#### Code you used for Submit/Run operation

```
class Solution:
    def swimInWater(self, grid: List[List[int]]) -> int:
        def parent(x):
            while root[x]!=x:
                root[x]=root[root[x]]
                x=root[x]
            return x
        
        def union(x,y):
            px=parent(x)
            py=parent(y)
            if px!=py:
                if size[px]>size[py]:
                    px,py=py,px
                size[py]+=size[px]
                root[px]=py
        
        n=len(grid)
        size=[1]*(n*n)
        root=list(range(n*n))
        vis=[[False]*n for _ in range(n)]
        positions=sorted([(i,j) for i in range(n) for j in range(n)],key=lambda x:grid[x[0]][x[1]])
        
        for i,j in positions:
            vis[i][j]=True
            for x,y in (i+1,j),(i-1,j),(i,j-1),(i,j+1):
                if 0<=x<n and 0<=y<n and vis[x][y]:
                    union(i*n+j,x*n+y)
            if parent(0)==parent(n*n-1):
                return grid[i][j]
```

#### Language used for code
Python

#### Expected behavior
The solutions based on heap and binary search/DFS are already given but not this one. This algorithm is quite similar to Kruskal. It has the same the complexity time and space complexity as the other two.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for reaching out to us. I've relayed this solution to our team to consider.

**Comment by lc-kate** [comment]
Hi @leet212 ,
Thank you for your time. Base on the solution you've provided to us, our team has created an entirely new approach (Approach 3 for this problem). Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
