### ISSUE TITLE
There is fourth DP solution with constant space

### ISSUE THREAD

**Issue by ATsahikian** [LeetCode-Feedback/LeetCode-Feedback#4710]
#### Your LeetCode username
tsagikyan

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
DP solution can be extended with const space

#### Code you used for Submit/Run operation
```
    vector<int> maxSlidingWindow(vector<int>& nums, int k) {
        int n = nums.size();
        vector<int> result(n-k+1);
        
        int left=0;
        for (int i=0; i<n; ++i)
        {
            left = i%k==0 ? nums[i] : max(left, nums[i]);
            
            if (i+1>=k)
                result[i+1-k] = left;
        }
        
        int right=0;
        for (int i=n-1; i>=0; i--)
        {
            right = (i%k==k-1 || i==n-1) ? nums[i] : max(right, nums[i]);

            if (i <= n - k)
                result[i] = max(result[i], right);
        }
        return result;
    }
```

#### Language used for code
C++

#### Expected behavior
Space: O(1)

**Comment by lc-kay** [comment]
@ATsahikian Can you please provide the problem title and number?

**Comment by ATsahikian** [comment]
"239. Sliding Window Maximum" - https://leetcode.com/problems/sliding-window-maximum/

**Comment by lc-kay** [comment]
Hi @ATsahikian 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ATsahikian,
Thank you for your input. This article is scheduled to be updated in the future and we will consider adding a constant space dynamic programming approach at that time.
