### ISSUE TITLE
Missing Test Case -  1492. The kth Factor of n

### ISSUE THREAD

**Issue by aerovenky** [LeetCode-Feedback/LeetCode-Feedback#4711]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
For perfect squares, Let us say the total number of factors are 2p+1
Test case is:
Perfect Sqaure and any k > p+1 and k < 2p+1

#### Code you used for Submit/Run operation

```python
class Solution:
    def kthFactor(self, n: int, k: int) -> int:
        sqr_root_n = int(math.sqrt(n))
        fact_large = []
        i = 1
        kth_factor = 0
        n_factors = 0
        while(i<=sqr_root_n):
            if n % i == 0:
                kth_factor += 1
                other_factor = n//i
                n_factors += 2
                if kth_factor == k:
                    return i
                fact_large.append(other_factor)
            i += 1
                
        # edge case of perfect squares 
        if sqr_root_n == other_factor:
            n_factors -= 1
            #fact_large.pop(-1) # un comment this line for full test case coverage including new cases
                    
        if k > n_factors:
            return -1
        else:
            return fact_large[kth_factor-k] # negative index
```

#### Language used for code
Python 3

#### Test Case
```
100
7
```

**Comment by lc-kay** [comment]
@aerovenky For a valid test case report, can you please provide a test case that will fail an accepted solution. The code that you have provided runs fine on this test case. Thank you!

**Comment by aerovenky** [comment]
@lc-kay  I have updated the above code based on your inputs

**Comment by lc-kay** [comment]
Hi @aerovenky 
Thank you for updating it. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @aerovenky 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
