### ISSUE TITLE
Theoram 1 Bellman Ford Algorithm in Graph Card

### ISSUE THREAD

**Issue by saivk7** [LeetCode-Feedback/LeetCode-Feedback#4712]
#### Your LeetCode username

wow07

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] -Cards Explanation

#### Description of the bug

In the explanation video, it is written (by hand) that, "in a graph with N vertices, there are at most N-1 edges between any 2 vertices." The correct thing that should be there is "In a graph with N vertices, the shortest path between any two vertices has at most N-1 edges."

Link : https://leetcode.com/explore/learn/card/graph/622/single-source-shortest-path-algorithm/3864/

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@saivk7 Thank you for your feedback. Although your statement is correct, that is not that idea the narrator is trying to convey here - at least not at this point in the explore card.
The narrator states his intended meaning clearly at the time range 1:00 - 2:05 of the first video.
The idea that he is trying to convey here is that in a graph without cycles, the longest path between any two nodes is at most N - 1 edges.
