### ISSUE TITLE
Missing Test Case - 254. Factor Combinations

### ISSUE THREAD

**Issue by mgithinji** [LeetCode-Feedback/LeetCode-Feedback#4713]
#### Your LeetCode username

githinjimorgan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

For test case "1000", the expected answer doesn't include the factor combination [10, 10, 10].

#### Code you used for Submit/Run operation

```
class Solution:
    def factorSearch(self, n):
        from math import sqrt
        factors = []  
        for i in range(2, int(sqrt(n)) + 1):
            quotient, mod = divmod(n, i)
            if mod == 0:
                factors.append([i, quotient])
        return factors
    
    def dfsFactors(self, n):
        factors = self.factorSearch(n)

        if len(factors) == 0:
            return []

        for i, factor in enumerate(factors):
            for j, value in enumerate(factor):
                subFactors = self.dfsFactors(value)
                for subFactor in subFactors:
                    newFactor = factor[:j] + subFactor + factor[j+1:]
                    factors.append(newFactor)
        return factors
    
    def getFactors(self, n: int) -> List[List[int]]:
        factors = self.dfsFactors(n)
        result = []
        for factor in factors:
            factor.sort()
            if factor not in result:
                result.append(factor)
        return result
```

#### Expected behavior

In addition to the other factor combinations, there should exist a factor combination of [10, 10, 10], which was missing in the expected output.

**Comment by lc-kay** [comment]
@mgithinji Can you please provide the submission details link to your code? Thank you!

**Comment by lc-kay** [comment]
Hi @mgithinji 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
