### ISSUE TITLE
Alternative solution to binary-search-tree-iterator problem

### ISSUE THREAD

**Issue by Denis-Gavrielov** [LeetCode-Feedback/LeetCode-Feedback#4714]
#### Your LeetCode username

denisgavr

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hi, I believe there is an alternative solution which is quite elegant and runs under the same runtime and space complexities as the best solutions currently proposed

#### Code you used for Submit/Run operation

```python
class BSTIterator:
    def __init__(self, root: TreeNode):
        self.generator = in_order_traversal(root)
        # We need to retrieve the next value before we
        # are asked about it.
        self.next_value = self._get_next()

    def next(self) -> TreeNode:
        ret = self.next_value
        self.next_value = self._get_next()
        return ret

    def hasNext(self) -> bool:
        return self.next_value is not None

    def _get_next(self):
        try:
            return next(self.generator)
        except StopIteration:
            return None


def in_order_traversal(node):
    if node.left is not None:
        for value in in_order_traversal(node.left):
            yield value
    yield node.value
    if node.right is not None:
        for value in in_order_traversal(node.right):
            yield value

```

#### Language used for code

Python

#### Expected behavior

Same behaviour as current solution.

#### Additional context

First things first. Generators are not something that you have in every language. Possibly you don't want to add an answer which is not supported in all languages.

Now, if you're happy with using generators I think this solution is very nice. 

First of all, there is no special "tricks" required to code up the solution. If you know how to implement an in order traversal, the structure of the core algorithm looks very similar. The difference is just that we use a generator and yield instead of returning the result of the whole traversal in one go.

What I also like about this answer is that it is generalisable. Any algorithm that needs to become an iterator, can use a generator. That way there is no fiddling around with off-by-one errors in harder problems that require transforming an algorithm into an iterator.

The time complexity of `has_next` and `next` are constant as you just need to find the next value. I guess the complexity of `next` is amortized constant because you could go e.g. "left" with the initial call to `in_order_traversal` up to N times. 

The space complexity is O(h) (which is O(N) if we have an unbalanced tree). With every level, we are creating one more generator which creates an additional reference to a node. No copying of the entire input tree needed.

I hope that makes sense. 

I am looking forward to read a response.

**Comment by lc-kay** [comment]
Hi @Denis-Gavrielov 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
