### ISSUE TITLE
Solution fails for Test Case

### ISSUE THREAD

**Issue by aakanchha01** [LeetCode-Feedback/LeetCode-Feedback#4718]
#### Your LeetCode username
at21

#### Category of the bug
- [x] Solution

#### Description of the bug
For problem - https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree/ . The **Approach 2: BFS: Iterative Level Order Traversal with Queue** fails for test cases where the max sum is available on the last level.
For ex -: [1,2,3]
Expected output - 2
Actual output with the code given in the solution - 1

#### Code you used for Submit/Run operation

```
class Solution {
  public int maxLevelSum(TreeNode root) {
    int currLevel = 1, maxLevel = 1;
    int maxSum = root.val, currSum = 0;

    LinkedList<TreeNode> queue = new LinkedList();
    TreeNode marker = null, x = root;
    queue.addLast(root);
    queue.addLast(marker);

    while (queue.size() > 1) {
      x = queue.removeFirst();
      // continue current level
      if (x != marker) {
        currSum += x.val;
        if (x.left != null) queue.addLast(x.left);
        if (x.right != null) queue.addLast(x.right);
      }
      // end of current level, go to the next level
      else {
        if (currSum > maxSum) {
          maxSum = currSum;
          maxLevel = currLevel;
        }
        currSum = 0;
        currLevel++;
        queue.addLast(marker);
      }
    }

    return maxLevel;
  }
}
```

#### Language used for code
JAVA

#### Expected behavior
For TC - [1,2,3] solution should return 2 as asnswer but it returns 1 as answer

#### Screenshots

![image](https://user-images.githubusercontent.com/8458190/132359892-548f78a9-85c6-4dc3-a406-6699d4a4539a.png)

#### Additional context
The while loop has to run only till the time it has >1 elements , else it will keep on pushing and popping marker. But after while loop, we need to take care if the max sum was available in last level, as when last level sum was to be compared with current max sum (i.e at the time of last marker) we break out of the loop and that level is not considered.

**Comment by lc-kay** [comment]
Hi @aakanchha01 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @aakanchha01 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
