### ISSUE TITLE
311. Sparse Matrix Multiplication

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#472]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Insufficient problem description/constraints or missing test cases

#### Code you used for Submit/Run operation
```
class Solution(object):
    def multiply(self, a, b):
        n=len(a)
        l=len(b)
        m=len(b[0])
        z=[[0]*m for i in xrange(n)]
        da=defaultdict(lambda :defaultdict(list))
        for i in xrange(n):
            for j in xrange(l):
                if a[i][j]!=0:
                    da[j][i].append(a[i][j])
        db=defaultdict(lambda :defaultdict(list))
        for i in xrange(l):
            for j in xrange(m):
                if b[i][j]!=0:
                    db[i][j].append(b[i][j])
        for k in da:
            for i in da[k]:
                for j in db[k]:
                    for x in da[k][i]:
                        for y in db[k][j]:
                            z[i][j]+=x*y
        return z
```

#### Language used for code
Python

#### Expected behavior
Fails this test case

```
[]
[]
```

IMO the problem description/constraints should be updated to invalidate this test case as empty matrix multiplication gives an empty matrix.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've tested Run Code on your Python code with that test case, but got Runtime Error instead. Please see the screenshot attached for more details.
<img width="1427" alt="Screen Shot 2020-06-16 at 5 11 48 PM" src="https://user-images.githubusercontent.com/59751300/84840541-a991b100-aff4-11ea-917f-1355ba2a172d.png">

**Comment by leet212** [comment]
Hello @CooperCooperCooper . This is the expected behavior of my code. It is accepted but gives runtime error for this test. An accepted solution should not be getting runtime error for any test case which is valid according to the constraints. And empty matrices are not ruled out as their is currently no constraint for them. Thank you for your time.

**Comment by leet212** [comment]
Hello @CooperCooperCooper . Do you require any more information for this?

**Comment by lc-kate** [comment]
Hi @leet212 ,
Thank you for your clarification. I see it now. In the future, please help us verify the issue on our end by providing the kind of error you see on your side, so after we verify the issue to make sure it's consistent on both your and our end, I can then relay it to our team to take a deeper look. Thank you!

**Comment by lc-kate** [comment]
Hi @leet212 
Thank you for your time. We've improved the problem constraint and validator. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support.
