### ISSUE TITLE
377. Combination Sum IV is not a combination

### ISSUE THREAD

**Issue by Mete0** [LeetCode-Feedback/LeetCode-Feedback#4721]
this is a permutation, please fix the title as it is confusing

**Comment by lc-kay** [comment]
Hi @Mete0 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Mete0 Our team has decided not to change the title as it will break all the current links. Than you for your understanding.
