### ISSUE TITLE
1041 Robort Bounded in Circle

### ISSUE THREAD

**Issue by workmoreandtalkless** [LeetCode-Feedback/LeetCode-Feedback#4724]
#### Category of the bug

- [ ] Solution

#### 
Then here is what we have after 4 cycles:

x_4 = x + \Delta x + \Delta x - \Delta x + \Delta x = x + 4 \Delta xx 
4
​
 =x+Δx+Δx−Δx+Δx=x+4Δx
should be 
Then here is what we have after 4 cycles:

x_4 = x + \Delta x + \Delta x + \Delta x + \Delta x = x + 4 \Delta xx 
4
​
 =x+Δx+Δx+Δx+Δx=x+4Δx

change the first '-' sign to '+'

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@workmoreandtalkless Can you provide more details to the content-related issue that you are trying to report?

**Comment by workmoreandtalkless** [comment]
x_4 = x + \Delta x + \Delta x - \Delta x + \Delta x = x + 4 \Delta xx
4

here we should have 4 Delta to add but you have a '-' , so you should change it to '+' to make sure the answer is x + 4\Delta.

**Comment by workmoreandtalkless** [comment]
Explain in the solution has a little error in the sign.

**Comment by lc-kay** [comment]
Hi @workmoreandtalkless 
Thank you for the clarification. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @workmoreandtalkless 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
