### ISSUE TITLE
Missing Test Case - 1901. Find a Peak Element II

### ISSUE THREAD

**Issue by awesomele** [LeetCode-Feedback/LeetCode-Feedback#4726]
[[10,50,40,30,20],[1,500,2,3,4]]

I have a solution passed all the existing but failed this one. when the mid is the dip (that is, 2 in [1,500,2,3,4]), the direction of the search matters.

**Comment by lc-kay** [comment]
@awesomele Please provide more details on your missing test case report, such as the accepted code that this test case fails. After more information is provided, I will reopen this ticket. Thank you for your time.

**Comment by awesomele** [comment]
this is the accepted  submission, https://leetcode.com/submissions/detail/551316986/, 
but it fails this test case: [[10,50,40,30,20],[1,500,2,3,4]]

`class Solution {
public:
vector<int> findPeakGrid(vector<vector<int>>& mat) {
        int n = mat.size();
        int m = mat[0].size();
        
        if(m==1 && n==1){
            return {0,0};
        }
        
        for(int i=0;i<n;i++){
            int l = 0;
            int r = m-1;
            
            while(l<r){
                int  mid = (l+r)/2;
                
                if(mat[i][mid]>mat[i][mid+1]){
                    r = mid;
                }else{
                    l = mid+1;
                }
            }
            
            if(i==0){
                if(mat[i][l]>mat[i+1][l]){
                    return {i,l};
                }
            }
            else if(i == n-1){
                if(mat[i][l]>mat[i-1][l]){
                    return {i,l};
                }
            }
            else{
                if(mat[i][l]>mat[i+1][l]  && mat[i][l]>mat[i-1][l]){
                    return {i,l};
                }
            }
        }
        return {0,0};
    }
};`

**Comment by lc-kay** [comment]
Hi @awesomele 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @awesomele
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by awesomele** [comment]
Thanks!

LeetCode ID :   awesomele
