### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by wyboundary** [LeetCode-Feedback/LeetCode-Feedback#4727]
我在做141题，寻找环形链表。

我的代码在xcode上可以运行通过，但在力扣的编译器一直报错

附上我的代码给你们作参考：

func hasCycle(_ head: ListNode?) -> Bool {

           

        var h1 = head

        var h2 = head?.next

        

        while let hx2 = h2, let hx1 = h1 {

            

            if hx1 == hx2 {

                return true

            }

            h1 = h1?.next

            h2 = h2?.next?.next

            

        }

        

        return false

    }

**Comment by feiceh** [comment]
感谢反馈，能否向我们补充题目信息，编程语言以及添加屏幕截图辅助我们帮你定位问题。可以参考[这个反馈](https://github.com/LeetCode-Feedback/LeetCode-Feedback/blob/master/.github/ISSUE_TEMPLATE/bug--------.md)，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
