### ISSUE TITLE
637. Average of Levels in Binary Tree - Array representation of example tree is incorrect and misleading

### ISSUE THREAD

**Issue by abhishekmadhu** [LeetCode-Feedback/LeetCode-Feedback#4728]
#### Your LeetCode username
the_poet

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The array representation of the tree in Example 1 is incorrect. 
Expected: `[3,9,20,null,null,15,7]`
Actual value in the question: `[3,9,20,null,15,7]`

**Note the missing** `null`. 

#### Screenshots
<img width="955" alt="Screenshot 2021-09-08 at 1 47 02 PM" src="https://user-images.githubusercontent.com/21152008/132474297-a99b53a9-198c-4ceb-b3b8-4e4bcfb5136f.png">

#### Related Discuss Post
https://leetcode.com/problems/average-of-levels-in-binary-tree/discuss/1451797/The-example-array-is-wrong-representation-of-the-binary-tree.

**Comment by lc-kay** [comment]
Hi @abhishekmadhu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abhishekmadhu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
