### ISSUE TITLE
774. Minimize Max Distance to Gas Station

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#473]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 3 Heap has incorrect analysis

#### Code you used for Submit/Run operation

```
class Solution(object):
    def minmaxGasDist(self, stations, K):
        pq = [] #(-part_length, original_length, num_parts)
        for i in xrange(len(stations) - 1):
            x, y = stations[i], stations[i+1]
            pq.append((x-y, y-x, 1))
        heapq.heapify(pq)

        for _ in xrange(K):
            negnext, orig, parts = heapq.heappop(pq)
            parts += 1
            heapq.heappush(pq, (-(orig / float(parts)), orig, parts))

        return -pq[0][0]
```

#### Language used for code
Python

#### Expected behavior
Time Complexity: O(KlogN), where N is the length of stations

This is incorrect. The actual complexity is O(N+KlogN).
And since N<KlogN is not always valid it is wrong to say time complexity is KlogN

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 .
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
