### ISSUE TITLE
278. First Bad Version

### ISSUE THREAD

**Issue by PetarJanosevic** [LeetCode-Feedback/LeetCode-Feedback#4730]
#### Your LeetCode username

SevNEncoRe

#### Category of the bug
- [ ] Solution

#### Description of the bug

I coded the linear approach by iterating through all numbers, the way you did it in your solutions. The problem is, I receive a Time Limit Exceeded Error
TestCase:
2126753390
1702766719

#### Code you used for Submit/Run operation

```
public class Solution extends VersionControl {
public int firstBadVersion(int n) {
    for (int i = 1; i < n; i++) {
        if (isBadVersion(i)) {
            return i;
        }
    }
    return n;
}
    
}
```

#### Language used for code

Java

#### Expected behavior

It should return "Accepted"

#### Screenshots

![2021-09-08 (4)](https://user-images.githubusercontent.com/50551253/132546119-bb1a9ba2-c7ba-41d1-8eb8-d3c49c3db1a0.png)
![2021-09-08 (5)](https://user-images.githubusercontent.com/50551253/132546124-9efdd585-bbb3-49ec-9e0e-c24dc9ddd15f.png)

**Comment by lc-kay** [comment]
@PetarJanosevic Per our solution approach title, this will get a Time Limit Exceeded Error. Please read through the rest of the article to see how to optimize it and take another approach. Thank you for your time.
