### ISSUE TITLE
Redundant Problem

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#4731]
#### Your LeetCode username

aestheticsjtu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

"1991. Find the Middle Index in Array" is the exact same problem as "724. Find Pivot Index".

**Comment by lc-kay** [comment]
Hi @ThomasShaw1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ThomasShaw1 
Thank you for your time. We've added a reference to each problem in the other problem. We appreciate your support!
