### ISSUE TITLE
#1559 Detect Cycles in 2D Grid should be at most a medium difficulty problem

### ISSUE THREAD

**Issue by mdmuidulalam** [LeetCode-Feedback/LeetCode-Feedback#4732]
1559 Detect Cycles in 2D Grid is marked as Hard. In my opinion, it should be a lower difficulty.
https://leetcode.com/problems/detect-cycles-in-2d-grid/

**Comment by lc-kay** [comment]
Hi @mdmuidulalam 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mdmuidulalam 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
