### ISSUE TITLE
Spelling of start in error message "found strat > end" is incorrect.

### ISSUE THREAD

**Issue by saurav935** [LeetCode-Feedback/LeetCode-Feedback#4736]

**Comment by lc-kay** [comment]
@saurav935 Please provide the problem number and title, as well as a screenshot of the error message. Thank you!

**Comment by lc-kay** [comment]
Hi @saurav935  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
