### ISSUE TITLE
Wrong Solution 317. Shortest Distance from All Buildings

### ISSUE THREAD

**Issue by sanbhara** [LeetCode-Feedback/LeetCode-Feedback#4737]
#### Your LeetCode username
san111

#### Category of the bug

- [ ] Solution

#### Description of the bug
Approach 3: BFS from Houses to Empty Land (Optimized) cannot be correct. The reason is that just because a particular empty land cell is not reachable from all prior buildings (houses) does not mean that it should not be used along path to other empty lands. By pruning off these empty lands from future BFS's, we are potentially losing out on shortest paths to some empty lands that could have passed through the ones that got pruned by the following condition on line 42 :
```
grid[nextRow][nextCol] == emptyLandValue
```
I have not taken the trouble to come up with a test case to prove this, but I hope the explanation above makes sense.

**Comment by lc-kay** [comment]
Hi @sanbhara 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by sanbhara** [comment]
Actually thinking more about this, I realize that in this graph problem, all the nodes that are reachable from the pruned out node, also should get pruned since we can prove by contradiction that even those nodes cannot have been reachable by the same buildings. So closing this issue now. Thanks for taking a look.
