### ISSUE TITLE
Missing Test Case - 764. Largest Plus Sign

### ISSUE THREAD

**Issue by joetech** [LeetCode-Feedback/LeetCode-Feedback#4739]
#### Your LeetCode username
joetech

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I believe one of the test cases is incorrect. 

> 2
> [[0,0],[0,1],[1,0]]

 If the grid is 2 x 2 and you place mines in 3 of the 4 spaces, you're left with only one open space and no way to have a plus, so the answer should be 0, but it's checking for the answer to be 1

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {

    /**
     * @param Integer $n
     * @param Integer[][] $mines
     * @return Integer
     */
    function orderOfLargestPlusSign($n, $mines) {
		$mid = floor($n / 2);
		$max = $n % 2 == 0 ? $mid - 1 : $mid;

		$left = [];
		$up= [];
		
		foreach($mines as $mine) {
			$left[] = $mine[0];
			$up[] = $mine[1];
		}
		
		$minLeftUp = min([min($left), min($up)]);
		
		return min([$minLeftUp * 2, $max]);
    }
}
```

#### Language used for code
PHP

#### Expected behavior
This test should pass when output is 0:
> 2
> [[0,0],[0,1],[1,0]]

**Comment by lc-kay** [comment]
@joetech The expected output of 1 is correct. For further clarification, please raise this as a discuss post in the problem discuss section as other users may have ran into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

**Comment by joetech** [comment]
Thanks.  I'll take a closer look at what I missed.
