### ISSUE TITLE
Consistency improvement of approach 2 - 230. Kth Smallest Element in a BST

### ISSUE THREAD

**Issue by davitescobedo** [LeetCode-Feedback/LeetCode-Feedback#4740]
#### Your LeetCode username

eldavimost

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the approach 2 solution, it is supposed to use the LinkedList as a stack but it uses the methods add and removeLast for insertion and removal of items. For consistency with how stack interfaces are, it should use push and pop.
Deque interface is designed to support stacks with those methods and queues with addLast and removeFirst.

#### Code you used for Submit/Run operation

```
class Solution {
  public int kthSmallest(TreeNode root, int k) {
    LinkedList<TreeNode> stack = new LinkedList<TreeNode>();

    while (true) {
      while (root != null) {
        stack.**push**(root);
        root = root.left;
      }
      root = stack.**pop**();
      if (--k == 0) return root.val;
      root = root.right;
    }
  }
}
```

#### Language used for code

Java

**Comment by lc-kay** [comment]
Hi @davitescobedo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @davitescobedo 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
