### ISSUE TITLE
157. Read N Characters Given Read4 - Approach 2 bug

### ISSUE THREAD

**Issue by ulugbekna** [LeetCode-Feedback/LeetCode-Feedback#4741]
#### Your LeetCode username

ulugbekna

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

With approach 2 in the solution, the buffer can overflow if the size of `buf` is, say, 5, but the file contains more than 5 bytes.

https://leetcode.com/problems/read-n-characters-given-read4/solution/651373

**Comment by lc-kay** [comment]
Hi @ulugbekna 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
