### ISSUE TITLE
359. Logger Rate Limiter 

### ISSUE THREAD

**Issue by ritwik12** [LeetCode-Feedback/LeetCode-Feedback#4742]
#### Your LeetCode username

Ritwik1204

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Type in the line
`As one see can from the above example where the number indicates the timestamp of each message`

Should be

**As one can see from the above example where the number indicates the timestamp of each message**

**Comment by lc-kay** [comment]
Hi @ritwik12 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ritwik12 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
