### ISSUE TITLE
446. Arithmetic Slices II - Subsequence

### ISSUE THREAD

**Issue by vishal733** [LeetCode-Feedback/LeetCode-Feedback#4744]
#### Your LeetCode username
vishal733

#### Category of the bug
- [x] Question
- [x] Solution

#### Description of the bug
Either the question should mention that the array is sorted in ascending order.
Or the solution should first sort the input data.

#### Language used for code
Python

#### Expected behavior
Either the question should mention that the array is sorted in ascending order.
Or the solution should first edit the input data.

**Comment by lc-kay** [comment]
Hi @vishal733 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by vishal733** [comment]
This was an error in assessment from my side. I will close this issue.
