### ISSUE TITLE
Missing Test Case - 797. All Paths From Source to Target

### ISSUE THREAD

**Issue by vaayu7** [LeetCode-Feedback/LeetCode-Feedback#4745]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@vaayu7 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
