### ISSUE TITLE
Missing Test Case - #953 Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by romeirao** [LeetCode-Feedback/LeetCode-Feedback#4747]
#### Your LeetCode username
italorw

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I forgot to check for a pending condition and my code was accepted anyway.

#### Code you used for Submit/Run operation
```
class Solution {
    fun isAlienSorted(words: Array<String>, order: String): Boolean {
        if (words.size == 1) return true

        val auxAlphaHashMap: HashMap<Char, Int> = hashMapOf()
        order.forEachIndexed { index, c ->
            auxAlphaHashMap[c] = index
        }

        for (i in 0 until words.size - 1) {
            val firstWord = words[i]
            val nextWord = words[i + 1]
            var counter = 0
            loop@ for (j in 0 until minOf(firstWord.length, nextWord.length)) {
                val firstCharacter = firstWord[j]
                val firstIndex = auxAlphaHashMap[firstCharacter] ?: throw InvalidParameterException("kaboom!")

                val nextCharacter = nextWord[j]
                val nextIndex = auxAlphaHashMap[nextCharacter] ?: throw InvalidParameterException("kaboom!")

                if (firstIndex < nextIndex) {
                    break@loop
                } else if (firstIndex > nextIndex) {
                    return false
                } else {
                    counter++
                }
            }
            if (nextWord.length == counter) {
                return firstWord.length == nextWord.length
            }
        }

        return true
    }
}
```

#### Language used for code
Kotlin

#### Expected behavior
Using this test case:
```
Input: words = ["apple", "apple", "app"], order = "abcdefghijklmnopqrstuvwxyz"
```
The above code gives the wrong answer `true` and the expected answer is `false`. However, the above code passes all tests, implying that the tests are insufficient.

#### Screenshots
N/A

#### Additional context
N/A

**Comment by lc-kay** [comment]
Hi @romeirao 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @romeirao 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
