### ISSUE TITLE
26题缺少测试用例

### ISSUE THREAD

**Issue by rentianle2020** [LeetCode-Feedback/LeetCode-Feedback#4748]
**你的 LeetCode 用户名**
rentianle2020

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
26. 删除有序数组中的重复项
当数组大小为0时，如果返回length为1，依然可以通过测试。

**你使用的语言**
Java

**你提交或者运行的代码**
```
public int removeDuplicates(int[] nums) {
        int slowIndex = 0;
        for (int fastIndex = 1; fastIndex < nums.length; fastIndex++) {
            if(nums[slowIndex] != nums[fastIndex]){
                slowIndex++;
                nums[slowIndex] = nums[fastIndex];
            }
        }
        return slowIndex + 1;
    }
```

**期望行为**

应该要求答题者对legnth为0这个边界值做出判断，而不是将length为0的数组返回length=1

`if(nums.length == 0) return nums.length;`

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
@feiceh Please provide the exact test case that will fail this solution. Thank you!

**Comment by feiceh** [comment]
@rentianle2020 Please provide the exact test case that will fail this solution. Thank you!

**Comment by rentianle2020** [comment]
> @feiceh Please provide the exact test case that will fail this solution. Thank you!

```
public int removeDuplicates(int[] nums) {
        int slowIndex = 0;
        for (int fastIndex = 1; fastIndex < nums.length; fastIndex++) {
            if(nums[slowIndex] != nums[fastIndex]){
                slowIndex++;
                nums[slowIndex] = nums[fastIndex];
            }
        }
        return slowIndex + 1;
    }
```
When the parameter is an empty array [], this function will return 1 and pass the test.
I think the correct return for this function is to return the length after removing the duplicates, in the empty array case should be 0. The return of 1 should not pass the test.

**Comment by rentianle2020** [comment]
> @feiceh Please provide the exact test case that will fail this solution. Thank you!

Since the hint to this question is this **0 <= nums.length <= 3 * 104**
Another way to solve this issue is to change the hints into 0 < nums.length <= 3 * 104 and remove the test of an empty array.

**Comment by rentianle2020** [comment]
Oh, I read the question again, and there is no issue at all since it will return the element **within the length i returned** . 
Sorry for that.
