### ISSUE TITLE
22 generate-parentheses

### ISSUE THREAD

**Issue by Zhenyaoliu** [LeetCode-Feedback/LeetCode-Feedback#4749]
#### Your LeetCode username
bruseliu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

(())(()) was not included in testcase output when input n = 4, but (())(())should be a correct solution according to the description 

#### Code you used for Submit/Run operation

```
class Solution:
    def generateParenthesis(self, n: int) -> List[str]:
        if n == 1:
            return ['()']

        lower = self.generateParenthesis(n - 1)
        res = ['()' + i for i in lower] + ['(' + i + ')' for i in lower] + [i + '()' for i in lower]

        return list(set(res))

```

**Comment by lc-kay** [comment]
@Zhenyaoliu The output (())(()) is included in the expected output. Please check out the screenshot attached. 
<img width="1057" alt="Screen Shot 2021-09-14 at 11 11 40 AM" src="https://user-images.githubusercontent.com/70870126/133311288-0c295ada-28cb-4c2f-bcb4-cbe59ba16b40.png">
