### ISSUE TITLE
Missing Test Case - 224. Basic Calculator

### ISSUE THREAD

**Issue by XeroxLin** [LeetCode-Feedback/LeetCode-Feedback#4751]
#### Your LeetCode username

Xerox_lin

#### Category of the bug
- [V] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

As to the constraints, it seems some test case has been a violation on there.
The '-' didn't be inside parentheses while it play as unary operation.

'-' could be used as a unary operation but it has to be inside parentheses.
Test case:
"-2+ 1"
"- (3 + (4 + 5))"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @XeroxLin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @XeroxLin 
Thank you for your time. The team reviewed your report and noticed the problem was in the constraints. After updating that, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
