### ISSUE TITLE
846 HAND OF STRAIGHTS(MISSIING TEST CASE) 

### ISSUE THREAD

**Issue by hardik302001** [LeetCode-Feedback/LeetCode-Feedback#4752]
#### Your LeetCode username
hardik2001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I forgot to check for a condition and the code passed anyways.
Problem [846](https://leetcode.com/problems/hand-of-straights/) and Problem [1296](https://leetcode.com/problems/divide-array-in-sets-of-k-consecutive-numbers/) are exactly same. So when I submit my code for [1296](https://leetcode.com/problems/divide-array-in-sets-of-k-consecutive-numbers/) my code results in WA on this [testcase,](https://leetcode.com/submissions/detail/553160155/testcase/) and same code for Problem [846](https://leetcode.com/problems/hand-of-straights/) results in AC. The issue is that for Problem [846](https://leetcode.com/problems/hand-of-straights/) should also result in WA.
But I think if [testcase,](https://leetcode.com/submissions/detail/553160155/testcase/) is added then it will also result in WA.

#### Code you used for Submit/Run operation
Wrong Code that result in  AC (should be WA ) without the proposed test case.

```
class Solution:
    def isNStraightHand(self, nums: List[int], k: int) -> bool:
        
        n = len(nums)
        if n%k==0:
            d = {}
            nums.sort()
            for i in nums:
                if i in d:
                    d[i]+=1
                else:
                    d[i]=1
                    
            l = list(set(nums))
            
            for value in l :
                p = d[value]           
                if p>0:
                    for c in range(k):
                        if ((value + c) in d)   and  d[value + c] >=p:
                            d[value + c]-=p   
                        else:
                            return False
                    
            return True
        else:
            return False



```

Correct Code (that should give WA if the proposed testcase is added):

```
class Solution:
    def isNStraightHand(self, nums: List[int], k: int) -> bool:
        
        n = len(nums)
        if n%k==0:
            d = {}
            nums.sort()
            for i in nums:
                if i in d:
                    d[i]+=1
                else:
                    d[i]=1
                    
            l = list(set(nums))
            l.sort()

            for value in l :
                p = d[value]           
                if p>0:
                    for c in range(k):
                        if ((value + c) in d)   and  d[value + c] >=p:
                            d[value + c]-=p   
                        else:
                            return False
                    
            return True
        else:
            return False


```

The only difference between both codes is that list of set should be sorted (  l.sort () ) on line 15 of correct code.

#### Language used for code
PYTHON

#### Expected behavior
The issue in the wrong code is that in python after creating a set from a sorted list, the set does not remain sorted. It needs to be explicitly sorted. 
Here, before using the unique values from set, we need the values in sorted order, so the list of set should be sorted. But, even if the list of set is not sorted, our code results in AC for  Problem [846](https://leetcode.com/problems/hand-of-straights/), that is not CORRECT.

**Comment by lc-kay** [comment]
Hi @hardik302001 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hardik302001 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
