### ISSUE TITLE
Missing Test Case - 1669. Merge In Between Linked Lists

### ISSUE THREAD

**Issue by Ujju6548** [LeetCode-Feedback/LeetCode-Feedback#4753]
#### Your LeetCode username
ujju6548

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
My code is valid for all the test cases except one which is cotradictory testcase 

#### Code you used for Submit/Run operation

```
// Merge In Between Linked Lists
class Solution {
`public:`
    ListNode* mergeInBetween(ListNode* list1, int a, int b, ListNode* list2) {
        ListNode *temp = list1;
        ListNode *temp1 = list2;
        ListNode *temp2 = NULL;
        ListNode *temp3 = NULL;
        while(temp1->next != NULL){
            temp1 = temp1->next;
        }
        while(temp->next != NULL){
            if(temp->next->val == a && a == b){
                temp2 = temp;
                temp3 = temp->next;
            }
            else if(temp->next->val == a)
                temp2 = temp;
            else if(temp->next->val == b)
                temp3 = temp->next;
            temp = temp->next;
        }
        temp2->next = list2;
        temp1->next = temp3->next;
        return list1;
    }
    }
};
```

#### Language used for code
C++

#### Expected behavior

My code is valid according to the examples shown in the description of the question but it is failing for one testcase which i think is a contradictory testcase according to the question

#### Screenshots

<img width="342" alt="bug" src="https://user-images.githubusercontent.com/87585526/132957589-951d851a-6921-4a31-8ab0-1e6d057ccdc4.png">

#### Additional context

The testcase which is a bug is uploaded above

**Comment by lc-kay** [comment]
@Ujju6548 The expected test case is correct. Please check out the following discuss posts:

- https://leetcode.com/problems/merge-in-between-linked-lists/discuss/1213082/Wrong-test-case
- https://leetcode.com/problems/merge-in-between-linked-lists/discuss/1268186/Wrong-Test-Case
- https://leetcode.com/problems/merge-in-between-linked-lists/discuss/1259935/1-test-case-failed
- https://leetcode.com/problems/merge-in-between-linked-lists/discuss/1024510/Explain-this-test-case
- https://leetcode.com/problems/merge-in-between-linked-lists/discuss/1028251/one-test-case-is-wrong

Thank you for your time!
