### ISSUE TITLE
1332. 删除回文子序列 题目存在问题

### ISSUE THREAD

**Issue by lqzo** [LeetCode-Feedback/LeetCode-Feedback#4756]
**你的 LeetCode 用户名**
liqingzhou

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目描述中字符串的长度为 0 到 1000，并给出了示例 4 字符串为空，但本题并不允许空字符串作为示例；
且英文版描述中 字符串长度为 1 到 1000， 无示例 4

**期望行为**
移除错误描述 或 添加为空时的处理

**屏幕截图**
![image](https://user-images.githubusercontent.com/30641714/132970627-5e68db8f-d82c-43d0-8bfd-b5a6e330f7e7.png)
![image](https://user-images.githubusercontent.com/30641714/132970765-a49b12c4-bb91-4373-aa4c-0a752f09bed9.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lqzo 你好，在与负责团队沟通了解后，当前去掉了示例 4，更改了数据范围，感谢支持力扣。
