### ISSUE TITLE
Clarification - 2002. Maximum Product of the Length of Two Palindromic Subsequences

### ISSUE THREAD

**Issue by ankur-kayal** [LeetCode-Feedback/LeetCode-Feedback#4758]
#### Your LeetCode username
ankurkayal

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My solution got TLED in contest but when I submit after contest, it gets AC. This is really frustrating and confusing.

#### Code you used for Submit/Run operation

```cpp
auto speedup = []() {ios_base::sync_with_stdio(0); cin.tie(nullptr); return 0;}();

class Solution {
public:
    int maxProduct(string s) {
        int ans = 0;

        int n = s.length();

        for(int mask = 1; mask < (1 << n); mask++) {
            string tmp = "";
            string rev = "";
            for(int bit = 0; bit < n; bit++) {
                if(mask >> bit & 1) {
                    tmp += s[bit];
                    rev = s[bit] + rev;
                }
            }
            if(rev == tmp) {
                int rmask = ((1 << n) - 1) ^ mask;
                for(int submask = rmask; submask > 0; submask = (submask - 1) & rmask) {
                    string tmp = "";
                    string rev = "";
                    for(int bit = 0; bit < n; bit++) {
                        if(submask >> bit & 1) {
                            tmp += s[bit];
                            rev = s[bit] + rev;
                        }
                    }
                    if(rev == tmp) {
                        int pro = __builtin_popcount(mask) * __builtin_popcount(submask);

                        ans = max(ans, pro);
                    }
                }
            }
        }

        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

This code should get accepted in contest as it clearly gets accepted after contest.

#### Screenshots

- During Contest
![image](https://user-images.githubusercontent.com/44806622/132971889-54f18c01-3f9c-4890-9b6b-09222843914b.png)

- After Contest
![image](https://user-images.githubusercontent.com/44806622/132971867-f4cc9abc-5109-4727-99e0-e005d85a1a17.png)

**Comment by lc-kay** [comment]
Hi @ankur-kayal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ankur-kayal** [comment]
@lc-kay This has been resolved as when my code was re-run it got accepted! All previous TLE is now accepted! Probably there was some issue in the servers during the contest due to a huge load of running so many codes!
