### ISSUE TITLE
249. Group Shifted Strings

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#476]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing constraints or test cases

#### Code you used for Submit/Run operation
```
class Solution(object):
    def groupStrings(self, a):
        def f(x):
            return tuple([(ord(x[i+1])-ord(x[i]))%26 for i in xrange(len(x)-1)])
        d=defaultdict(list)
        for i in a:
            d[f(i)].append(i)
        return d.values()
```

#### Language used for code
Python

#### Expected behavior
Fails this test case

```
["abc","bcd","acef","xyz","az","ba","a","z",""]
```

IMO the constraints should be updated to invalidate this test case as empty shifted string cannot be defined in terms of shifts.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. After a thorough review, our engineers found that the issue stemmed from neither missing constraint nor test case. We've added more definition to the problem statement to help users clarify the confusion. Thank you for your support.

**Comment by leet212** [comment]
Hello @CooperCooperCooper . Thank you for your response.

- How did the issue not stem from missing description/constraints? And if that is the case why was the problem updated then?

- Using the feedback in this issue 

> the constraints should be updated to invalidate this test case as empty shifted string cannot be defined in terms of shifts

the judge's response was modified to invalidate the test case

> Invalid Testcase
> expected rows of 'strings' to have 1 <= size <= 10000000

and also modification has been made in the problem statement.

> Given a list of non-empty strings which contains only lowercase alphabets, group all strings that belong to the same shifting sequence.

- Updating the 'problem description' to invalidate what was the main point of the issue does not mean the 'constraints' were not missing. The same thing was done in #423.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your answer. I've relayed this issue to our team to investigate.

**Comment by leet212** [comment]
Hello @CooperCooperCooper .
The point that I was trying to make is that if there was a need to update the problem description with a constraint (non-empty in this case) then obviously constraints were not complete and by definition the issue stemmed from missing constraint. Thank you for your response.

**Comment by lc-kate** [comment]
Hi @leet212 , 
Thank you for your clarification. I understand your point, and I've relayed them to the engineers who work on this problem. When there is more update I'll share them with you here.

**Comment by lc-kate** [comment]
Hi @leet212 ,
Thank you for your time. The engineer clarified that adding non-empty on the problem description was to prevent users from creating extreme test cases. The constraint in the problem was okay.
