### ISSUE TITLE
Incorrect output in Remove Duplicates from Sorted Array.

### ISSUE THREAD

**Issue by helper-uttam** [LeetCode-Feedback/LeetCode-Feedback#4760]
#### Your LeetCode username
UttamKumar22

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Testcases are not correct.

#### Code you used for Submit/Run operation
//26. Remove Duplicates from Sorted Array
```
class Solution {
    public int removeDuplicates(int[] nums) {
        
        if(nums.length == 0) return 0;
        
        int m = nums[0],count=1;
        for(int i=1; i<nums.length; i++){
            if(nums[i] != m){
                ++count;
                m = nums[i];
            }
        }
        
        return count;
    }
}
```

#### Language used for code
Java

#### Expected behavior
My code is working fine and giving accurate output on other compilers, But here I guess the testcases are incorrect!

#### Additional context
For the first testcase,
input is `[1,1,2]`
hence my code is giving output = **2** because there are 2 distinct integers, but the leetcode compiler is giving me output like `[1,1]`

**Comment by lc-kay** [comment]
@helper-uttam Unfortunately, we are unable to troubleshoot the difference in behavior between your local and the LeetCode compiler. However, it seems like other users have encountered this issue before, check out this discuss post https://leetcode.com/problems/remove-duplicates-from-sorted-array/discuss/12215/Leetcode's-output-doesn't-match-the-output-on-my-PC.
