### ISSUE TITLE
A typo in the backtracking explorer card

### ISSUE THREAD

**Issue by yujuiwu** [LeetCode-Feedback/LeetCode-Feedback#4761]
#### Your LeetCode username

yujuiwu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/explore/featured/card/recursion-ii/472/backtracking/2654/

There's a typo in example 2 step 5 that instead of "rol", it should be "col".

**Comment by lc-kay** [comment]
Hi @yujuiwu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @yujuiwu 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
