### ISSUE TITLE
Incorrect problem statement in Q.1380 (Algorithms)

### ISSUE THREAD

**Issue by vishal-zx** [LeetCode-Feedback/LeetCode-Feedback#4762]
#### Your LeetCode username
vishal-15

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In question - 1380, it is asked to return all the lucky numbers. But it can be proved that in the whole matrix, there is only a single lucky number that exists. The incorrect problem statement may confuse users.
Problem Link : https://leetcode.com/problems/lucky-numbers-in-a-matrix/

#### Language used for code
C++

#### Expected behavior

In the problem statement, it should be "...return the lucky number in the matrix."

**Comment by Debasishbsws** [comment]
Yes you are correct , there in no chance that an matrix contains more than one lucky number. but the question is not confusing at all, instead of  returning in Int format we are returning it in List.

**Comment by lc-kay** [comment]
Hi @vishal-zx 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vishal-zx 
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
