### ISSUE TITLE
Wrong description - 882. Reachable Nodes In Subdivided Graph

### ISSUE THREAD

**Issue by ChenghaoMou** [LeetCode-Feedback/LeetCode-Feedback#4763]
#### Your LeetCode username

Maxen2018

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the description `..., [xcnti+1, xcnti], [xcnti, vi].`
It should be ` ..., [xcnti-1, xcnti], [xcnti, vi].`

#### Code you used for Submit/Run operation

NA

#### Screenshots

![image](https://user-images.githubusercontent.com/32014649/132997016-9b0c5526-8824-4f9d-9fd6-dc025e360a05.png)

**Comment by lc-kay** [comment]
Hi @ChenghaoMou 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ChenghaoMou 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
