### ISSUE TITLE
Incorrect Space Complexity | Explore - Graphs - Overview of Kahn's Algorithm

### ISSUE THREAD

**Issue by akshittrehan** [LeetCode-Feedback/LeetCode-Feedback#4764]
[Overview of Kahn's Algorithm](https://leetcode.com/explore/learn/card/graph/623/kahns-algorithm-for-topological-sorting/3886/)

Space Complexity is reported as `O(V+E)` which is correct, but this can be made stricter i.e. **`O(V)`**.

Each vertex `v` is added to queue only once i.e. when in-degree of `v` becomes zero. Also, we need `O(V)` space to store in-degree for each vertex.

**Comment by lc-kay** [comment]
@akshittrehan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@akshittrehan Thank you for identifying this. You are correct; based on the implementation shown in the video, the space complexity would, in fact, be $$O(V)$$.  In our next update to the card, we will add mention of this to the text and explain the adjacency list optimization that was not shown in the video that leads to the O(V + E) time and O(V + E) space complexity.
