### ISSUE TITLE
Missing Test Case - 155. Min Stack

### ISSUE THREAD

**Issue by 08chahat** [LeetCode-Feedback/LeetCode-Feedback#4765]
#### Your LeetCode username
chahatgupta08

#### Category of the bug
- [ ] Question
- [] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug
In the minstack implementation , if there is no element present in the stack and we received top operation then it should return -1 . In this question solution is accepted even if we do not place the check whether stack is empty or not. and then only appropriately return statement should be added.

#### Code you used for Submit/Run operation

```
// Min Stack
class MinStack {
public:
    /** initialize your data structure here. */
    stack<int> s;
    stack<int> ss;
    MinStack() {
        
    }
    
    void push(int val) {
        
        s.push(val);
        if(ss.size()==0 || val<=ss.top()){
            ss.push(val);
        }
        
    }
    
    void pop() {
        if(s.size()==0){
            return ;
        }
        int ans=s.top();
        s.pop();
        if(ans==ss.top()){
            ss.pop();
        }
        
    }
    
    int top() {
        return s.top();
    }
    
    int getMin() {
        if(ss.size()==0){
            return -1;
        }
        return ss.top();
        
    }
};

```

#### Language used for code
C++

#### Expected behavior

This Code should not pass and solution should not be accepted as i=in this in top operation of minstack i am not checking whter stack is empty or not.

**Comment by lc-kay** [comment]
@08chahat Can you please provide the specific test case that will fail this code? Thank you!

**Comment by lc-kay** [comment]
Hi @08chahat 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
