### ISSUE TITLE
Missing Test Case - 1745. Palindrome Partitioning IV

### ISSUE THREAD

**Issue by kozakusek** [LeetCode-Feedback/LeetCode-Feedback#4766]
#### Your LeetCode username
kozakusek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Incorrect code passes while it should not.
Example test case: "cbbbcaacb"

#### Code you used for Submit/Run operation

```
class Solution {
public:
      
    bool is_palindrome(const string &s, int a, int b) const {
        if (a == b)
            return true;
        
        while (a < b) {
            if (s[a] != s[b]) {
                return false;
            } else {
                a++;
                b--;
            }
        }
        
        return true;
    }
    
    bool checkPartitioning(const string &s) const {            
        for (int i = s.length() - 2; i > 0; i--) {
            if (is_palindrome(s, 0, i - 1)) {
                for (int j = i + 1; j < s.length(); j++) {
                    if(is_palindrome(s, i, j - 1) && is_palindrome(s, j, s.length() - 1))
                    {
                        return true;
                    }
                }
                break;
            }
        }
        return false;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

This solution should not be accepted.
On the input: "cbbbcaacb" it returns false even though there exists a required partition.

**Comment by lc-kay** [comment]
Hi @kozakusek 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kozakusek 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
