### ISSUE TITLE
Missing Test Case - 426. Convert Binary Search Tree to Sorted Doubly Linked List

### ISSUE THREAD

**Issue by aptoth** [LeetCode-Feedback/LeetCode-Feedback#4767]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

It is not verified that a provided input is indeed a binary search tree.

#### Code you used for Submit/Run operation

The following test case is accepted, however it's not a BST [4,2,5,1,3,9,-1].

#### Language used for code

C++

#### Expected behavior

The test case should have been rejected as an invalid test case or the problem statement should be corrected to use binary tree instead of BST.

**Comment by lc-kay** [comment]
Hi @aptoth 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @aptoth 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
