### ISSUE TITLE
Missing Test Case - 1776. Car Fleet II

### ISSUE THREAD

**Issue by hsuedw** [LeetCode-Feedback/LeetCode-Feedback#4769]
#### Your LeetCode username

hsuedw (Edward Hsu)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I have not started to solve this coding question. After reading the description and Example 2, I find the answer of Example 2 might be wrong. I think the correct answer should be [3.00000,1.00000,1.50000,-1.00000].

After the first second elapses, car[1] catches up car[2] at position 9 and both cars travel in 3 meters/second.  At this moment, the position and speed of car[0] is 7 meters and 4 meters/second, respectively. Then, two more seconds latter, car[0] will catch up the car fleet formed by car[1] and car[2]. Therefore, the answer of Example 2 should be [3.00000,1.00000,1.50000,-1.00000] instead of [2.00000,1.00000,1.50000,-1.00000].

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

**Comment by lc-kay** [comment]
@hsuedw The expected output is correct. Please raise this in the discuss section for further clarification! Thank you for your time.
