### ISSUE TITLE
 LeetCode 547 - Number of Provinces - Disjoint Sets

### ISSUE THREAD

**Issue by SleeplessChallenger** [LeetCode-Feedback/LeetCode-Feedback#4770]
#### Category of the bug
- [ ] Question
- [Yes ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Union Rank unite two nodes due to rank value. When we merge
EXISITNG nodes, then the root value of only merging one will be changed.

But, if we look at the solution provided by LC: [0,0,2,1]. When we connect
node 1 and node 2 (idx 0 and 1) then they have equal rank and either will be
the root. Let's take 0 as a root. But when we connect nodes 2 and 4 (idx 1 and 3), then
we see that root of 2 is 1 (idx 0) with rank 2 and root of 4 is 4 (idx 3) with rank 1.
Hence we make union of 4 to the root of 2 which is 1 (idx 0), but not to the 2 itself
as done in the solution

#### Code you used for Submit/Run operation

```
class Solution:
    def findCircleNum(self, isConnected: List[List[int]]) -> int:
        graph = DisjointSet(len(isConnected))
        for i in range(len(isConnected)):
            for j in range(len(isConnected[i])):
                figure = isConnected[i][j]
                if figure == 0:
                    continue
                    
                graph.union(i, j)
        
        count = 0
        for i in range(len(graph.root)):
                if graph.root[i] == i:
                    count += 1
        
        return count


class DisjointSet:
    def __init__(self, size):
        self.root = [i for i in range(size)]
        self.rank = [1 for _ in self.root]
    
    def find(self, vertex):
        if vertex == self.root[vertex]:
            return vertex
        self.root[vertex] = self.find(self.root[vertex])
        return self.root[vertex]
    
    def union(self, v1, v2):
        root1 = self.find(v1)
        root2 = self.find(v2)
        if root1 != root2:
            if self.rank[root1] > self.rank[root2]:
                self.root[root2] = root1
            elif self.rank[root1] < self.rank[root2]:
                self.root[root1] = root2
            else:
                self.root[root2] = root1
                self.rank[root1] += 1
    
    def connected(self, v1, v2):
        return self.find(v1) == self.find(v2)
```

#### Language used for code

Python

#### Expected behavior

Wrote everything in the description of the bug

**Comment by lc-kay** [comment]
@SleeplessChallenger Thank you for identifying this.  It looks like the narrator forgot to follow through with finding the root of city 2 in the video.  We will make note of this in our next update to the explore card.
