### ISSUE TITLE
817. Linked List Components Invalid Constraints ?

### ISSUE THREAD

**Issue by tharun49** [LeetCode-Feedback/LeetCode-Feedback#4771]
#### Your LeetCode username

Tharun49

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Constraints for the question state that 
"""
The number of nodes in the linked list is n.
1 <= n <= 104
0 <= Node.val < n
All the values Node.val are unique.
1 <= nums.length <= n
0 <= nums[i] <= n
All the values of nums are unique.
"""
That nums[i] can take values between 0<= nums[i] <= n
where n is the length of the Linked list
#### Code you used for Submit/Run operation

```
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def numComponents(self, head: Optional[ListNode], nums: List[int]) -> int:
        comp = 0
        p = 0
        while head.next:
            if head.val in nums:
                p = 1
            else:
                comp += p
                p =0
                
            head= head.next
        return comp+1 if head.val in nums else comp

```

#### Language used for code

Python

#### Expected behavior

It should accept the test case or change the constraints appropriately
Tested against this test case!
[0]
[1]

#### Screenshots

![leet](https://user-images.githubusercontent.com/88381274/133075655-6368f672-e859-4f08-8970-b396daae2eec.PNG)
![leet2](https://user-images.githubusercontent.com/88381274/133075891-afcfefa3-17a0-42f6-adc8-c5b88b1c6f29.PNG)

#### Additional context

IT should either accept the constraints or change the constraints!!

**Comment by lc-kay** [comment]
Hi @tharun49 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tharun49 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by tharun49** [comment]
Can I expect any points awarded for the same ?
