### ISSUE TITLE
缺乏测试用例 - 134. 加油站 

### ISSUE THREAD

**Issue by cmNaN** [LeetCode-Feedback/LeetCode-Feedback#4773]
**你的 LeetCode 用户名**
yu-mang

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
134. 加油站 
我的代码能通过，但是不能得到正确解

**你使用的语言**
Python3

**你提交或者运行的代码**
```py
class Solution:
    def canCompleteCircuit(self, gas: List[int], cost: List[int]) -> int:
        last = 0
        need_gas = 0
        req_max = 0

        for idx in range(len(gas)):
            delta = gas[idx] - cost[idx]
            need_gas += delta

            if need_gas <= req_max:
                req_max = need_gas
                last = idx
        
        if need_gas < 0:
            return -1
        return (last + 1) % len(gas)
```

**期望行为**
输入
```
[11,4, 7, 1, 0]
[2,5, 5, 9, 1]
```
输出 `1`
预期结果 `0`
无法得到最优解

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
Hi @cmNaN 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @feiceh 
We've added this testcase. Please reward the user.

**Comment by feiceh** [comment]
@cmNaN  你好，当前题目已添加测试用例，ID：yu-mang 给予积分奖励，请查收。
