### ISSUE TITLE
Missing Test Case - 1705. Maximum Number of Eaten Apples

### ISSUE THREAD

**Issue by l0latgithub** [LeetCode-Feedback/LeetCode-Feedback#4774]
#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

I tried the following test case and there is not apple available for eating.
apples: [0]
days:    [1]

However my code below gives wrong answer even though it is accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def eatenApples(self, apples: List[int], days: List[int]) -> int:
        stack = []
        ans = 0
        idx = 0
        
        while stack or idx<len(apples):
            
            if idx<len(apples):
                heapq.heappush(stack, [idx+days[idx], apples[idx]])
            
            while stack and stack[0][0]<=idx:
                heapq.heappop(stack)
            
            if stack:
                ans+=1
                stack[0][1]-=1
                if stack[0][1]==0:
                    heapq.heappop(stack)
            
            idx+=1
            
        return ans
```

#### Language used for code

Python3

#### Expected behavior

answer should be 0

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins. We appreciate your support!

**Comment by EndlessCheng** [comment]
@lc-kay  This is an invalid test case because this constraint:

> days[i] = 0 if and only if apples[i] = 0.

Please remove this test case.
