### ISSUE TITLE
Solution Doubt- 543

### ISSUE THREAD

**Issue by RishMeh19** [LeetCode-Feedback/LeetCode-Feedback#4776]
#### Your LeetCode username
RishMeh19

#### Category of the bug
- [ ] Solution

#### Description of the bug
Doubt in how Diameter is being calculated recursively

#### Code you used for Submit/Run operation
diameter = max(diameter, left_height + right_height+1)

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Python

#### Expected behavior
In Depth-first-Search Approach, where diameter is calculated as:
diameter = max(diameter, left_height + right_height), I guess 1 should be added while summing left and right height, to include current node, i.e,
diameter = max(diameter, left_height + right_height+1)

**Comment by lc-kay** [comment]
Hi @RishMeh19 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @RishMeh19 
Thank you for reaching out. If the diameter of the tree were measured by the number of nodes then you would be correct. However, the diameter of a tree is measured by the number of edges instead. This is why we do not add 1 to account for the current node. This idea is easier to understand when looking at the first figure in the solution article.
