### ISSUE TITLE
Solution Doubt - 236

### ISSUE THREAD

**Issue by RishMeh19** [LeetCode-Feedback/LeetCode-Feedback#4777]
#### Your LeetCode username
RishMeh19

#### Category of the bug
- [ ] Solution

#### Description of the bug
Improvement in solution

#### Code you used for Submit/Run operation
           if not current_node:
                return False
            #pruning as answer already populated
            if self.ans:
                 return
            # Left Recursion
            left = recurse_tree(current_node.left)

            # Right Recursion
            right = recurse_tree(current_node.right)

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Python

#### Expected behavior
In approach-1, can't we just prune some recursive steps if we have already got the answer?
We can check before each recursive call that whether 'self.ans' is populated or not, if this.ans is populated, we can return from that step, otherwise continue with the recursive calls.

**Comment by lc-kay** [comment]
Hi @RishMeh19 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @RishMeh19 
Thank you for your input, you are correct. On average we could prune 33% of the calls to the recursive function by stopping when ans is populated. If/when the article is next updated we might implement early stopping.

As a general comment on the suggested code, if self.ans: return will return None while all other return values are booleans. It is generally recommended to have a consistent return type.

**Comment by RishMeh19** [comment]
@LC-Sue  This has been raised by many in the comments section of the solution for this question. It will be better if LeetCode team could update the sol. explanation with the above argument you have provided.
Thanks

**Comment by LC-Sue** [comment]
Hi @RishMeh19,
Thank you for your feedback. The team has already noted this issue and if/when the article is next updated, we might implement early stopping!
