### ISSUE TITLE
Wrong answer in the example .

### ISSUE THREAD

**Issue by Harshal-Taori-11** [LeetCode-Feedback/LeetCode-Feedback#4778]
harshaltaory1111

#### Category of the bug
-  Question
- Worng output of example.
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The example 3 of the question "41. First missing positive " has a wrong output. The output was supposed to be 10 instead it is showing 1 . And the right answer is 10.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int firstMissingPositive(vector<int>& nums) {
        
    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/75373361/133185142-7cafa23c-5223-4b3f-add0-a1d26aac5e34.png)

**Comment by lc-kay** [comment]
@Harshal-Taori-11 The expected output is correct. Please check out this discuss post for further clarification. https://leetcode.com/problems/first-missing-positive/discuss/258537/Is-the-test-case-wrong Thank you for your time!
