### ISSUE TITLE
Missing Test Case - 1189. Maximum Number of Balloons

### ISSUE THREAD

**Issue by osmanghoni1** [LeetCode-Feedback/LeetCode-Feedback#4779]
#### Your LeetCode username

protomandark1

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Accepts answers where number of balloons may not be correct

#### Code you used for Submit/Run operation
```
function maxNumberOfBalloons(text: string): number {
  let z =  text.split('')
  let b = 0
  let a = 0
  let l = 0
  let o = 0
  let n = 0
  let balloons = 0
  for(let i = 0; i < z.length; i++) {
    if( z[i] === 'b') {
      b++;
    }
    if(z[i] === 'a') {
      a++;
    }
    if(z[i] === 'l') {
      l++;
    }
    if(z[i] === 'o') {
      o++;
    }
    if(z[i] === 'o') {
      n++;
    }

    if(b >= 1 && a >= 1 && l >= 2 && o >= 2 && n >= 1) {
      balloons++
      b--
      a--
      l-=2
      o-=2
      n--
    }
  }

  return balloons
}
```

#### Language used for code

Typescript

#### Expected behavior

'loonbalxballpoonballoo'

In the string above the word balloon occurs 2 times, the code should return 2. Instead the code returns 3.
The code above is accepted as a solution.

#### Screenshots
![image](https://user-images.githubusercontent.com/18295681/133196309-4546fe2b-4f74-4e1f-b1f9-6645c3a574b7.png)
![image](https://user-images.githubusercontent.com/18295681/133196366-80fa0b4d-5b48-42d6-ab98-0a118f074cbc.png)

**Comment by lc-kay** [comment]
Hi @osmanghoni1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @osmanghoni1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
