### ISSUE TITLE
Missing Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by abhin-av** [LeetCode-Feedback/LeetCode-Feedback#4782]
#### Your LeetCode username
abhinav87

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
I have written a code which is wrong but I have cleared all the test cases present.

#### Code you used for Submit/Run operation

```
class Solution {
    public int thirdMax(int[] nums) {
        int l=nums.length;
        int n1 = -2;
        int n2 = -2;
        int n3 = -2;
        for(int i=0;i<l;i++){
            if(nums[i]==n1 || nums[i]==n2 || nums[i]==n3 ){
                continue;
            }
            if(nums[i]>n1 || n1 == -2){
                n3=n2;
                n2=n1;
                n1=nums[i];
            }
            else if(n2==-2 || nums[i]>n2){
                n3=n2;
                n2=nums[i];
            }
            else if(n3==-2 || nums[i]>n3){
                n3=nums[i];
            }
        }
        if(n3==-2){
            return n1;
        }
        else{
            return n3;
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior

Instead of using the smaller value than -2^31 or the null I used -2 for the comparison. But as there are no test cases for checking that I have passed all the remaining test cases smoothly. For example if I use [3,-2,1,-2] as a test case for my code maximum number will be overwritten as -2 every time I traverse over the value that I have used for comparison that is -2. 

#### Screenshots

![Capture](https://user-images.githubusercontent.com/63545787/133225717-bd2f919a-293d-48a1-bf02-d45510e5f615.PNG)

**Comment by lc-kay** [comment]
Hi @abhin-av 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abhin-av 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
