### ISSUE TITLE
Missing Test Case - 708. Insert into a Sorted Circular Linked List

### ISSUE THREAD

**Issue by finneym** [LeetCode-Feedback/LeetCode-Feedback#4783]
#### Your LeetCode username
mngfinney

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case for distinct values with duplicate values in the list. My solution was accepted on submit but was missing this edge case.

##### Input
```
[3,2,2]
0
```

##### Output
```
[3,2,0,2]
```

##### Expected Output
```
[3,0,2,2]
```

#### Code you used for Submit/Run operation

```
var insert = function(head, insertVal) {
    if (head == null) {
        const node = new Node(insertVal);
        node.next = node;
        return node;
    }
    if (head === head.next) {
        head.next = new Node(insertVal, head);
        return head;
    }
    
    let edge = null;
    let current = head;
    let foundPlacement = false;
    while (true) {
        if (current.val >= current.next.val) {
            edge = current;
        }
        if (current.val <= insertVal && current.next.val >= insertVal) {
            foundPlacement = true;
            break;
        }
        else if (current.next == head) {
            break;
        }
        current = current.next;
    }
    if (foundPlacement) {
        current.next = new Node(insertVal, current.next);    
    }
    else {
        edge.next = new Node(insertVal, edge.next);
    }
    
    return head;
};
```

#### Language used for code
Javascript

**Comment by lc-kay** [comment]
Hi @finneym 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @finneym 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
