### ISSUE TITLE
889. Construct Binary Tree from Preorder and Postorder Traversal

### ISSUE THREAD

**Issue by alant** [LeetCode-Feedback/LeetCode-Feedback#479]
#### Your LeetCode username
tanghao

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Testcase

#### Description of the bug
The following test case is wrong:
[2,1,3]
[3,1,2]

#### Code you used for Submit/Run operation

```Python
class Solution:
    def constructFromPrePost(self, pre: List[int], post: List[int]) -> TreeNode:
        if not pre:
            return
        root = TreeNode(pre[0])
        if len(pre) > 1:
            preLPos = pre.index(post[-2])
            postLPos = post.index(pre[1]) + 1
            root.left = self.constructFromPrePost(pre[1:preLPos], post[:postLPos])
            root.right = self.constructFromPrePost(pre[preLPos:], post[postLPos:-1])
        return root
```

#### Language used for code
Python

#### Expected behavior
The correct test case should be:
[2,1,3]
[1,3,2]

#### Screenshots
![Image 6-14-20 at 11 49 AM](https://user-images.githubusercontent.com/628689/84601626-73a6ce00-ae36-11ea-9eaa-972b08948ca0.JPG)

#### Additional context
A more optimized solution to use just left tree's length will bypass this test case bug and get AC. But it won't expose this bug in the test case data.

**Comment by CooperCooperCooper** [comment]
Hi @alant ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

P.S. the code is in Python3 not Python

**Comment by CooperCooperCooper** [comment]
Hi @alant ,
Thank you for your time. After a thorough review, our engineers found the contribution to be incorrect. We appreciate your support.
