### ISSUE TITLE
Missing Test Case - 136. Single Number

### ISSUE THREAD

**Issue by biswajitmaharana2016** [LeetCode-Feedback/LeetCode-Feedback#4790]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

`class Solution {
public:
    int singleNumber(vector<int>& nums) {
        
       unordered_set<int> us;
        map<int,int> m;
        int val =0;
        for( auto& a: nums)
        {
          
            
            if(us.count(a) > 0)
            {
                m[a]++;
            }
            else
            {
                m.insert(std::pair<int,int>(a,0));
            }
            us.insert(a);
        }
        for(auto b : m)
        {
            if( b.second == 0)
            {
                cout << b.first  << ":" << b.second  << endl;
                return b.first;
            }
        }
        return 0;
        
    }
};
```

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
@biswajitmaharana2016 You're more than welcome to share your code on the problem discuss section. However,
we encourage you to share more content-related issues here with us for valid content contribution rewards. Thank you again for your support and understanding.
