### ISSUE TITLE
Missing Test Case - 848. Shifting Letters

### ISSUE THREAD

**Issue by emmyari** [LeetCode-Feedback/LeetCode-Feedback#4792]
#### Your LeetCode username

ArijeetMukherjee

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The test case output For "bad" when shifted by array [10,20,30] should have to be "lzi" not "jyh". 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public String shiftingLetters(String s, int[] shifts) {
        StringBuilder sb=new StringBuilder();
        char[]charArray=s.toCharArray();
        int index=0;
        while(index < shifts.length){
        for(int i=0;i<=index;i++){
            int c=(int) charArray[i];
            
            c+=shifts[index];
            
            if(c>(int)'z'){
                int d=c-(int)'z';
                d=d%26;
                
                c='a'+d;
            }
            charArray[i]=(char) c;
        }
        index++;
        }
        for(char c:charArray){
            sb.append(c);
        }
        return sb.toString();
    }
}
```

#### Language used for code
Java

**Comment by lc-kay** [comment]
@emmyari The expected output is correct. Please raise this in the problem discuss section for further support. Thank you for your time.
