### ISSUE TITLE
Missing Test Case - 978. Longest Turbulent Subarray

### ISSUE THREAD

**Issue by cgsgak1** [LeetCode-Feedback/LeetCode-Feedback#4795]
#### Your LeetCode username
cgsgak1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing testcase

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int maxTurbulenceSize(vector<int>& arr) {
        int res = 1, cnt = 1;
        
        if (arr.size() == 2 && arr[0] != arr[1]) {
            return 2;
        }
        
        for (int i = 1; i < arr.size(); ++i) {
            if (cnt > 1) {
                if (arr[i] < arr[i - 1] && arr[i - 2] < arr[i - 1] ||
                    arr[i] > arr[i - 1] && arr[i - 2] > arr[i - 1]) {
                    ++cnt;
                } else {
                    cnt = 2;
                }
            }
            res = max(res, cnt);
            if (cnt == 1) {
                if (arr[i] != arr[i - 1]) {
                    cnt = 2;
                }
            }
        }
        
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior
[1,1,1,1,1,1,1,1,1,2] test case gives us 2 as an answer, but it is easy to miss the case, when different number appears at the and of an input array

#### Screenshots
![Screenshot_20210915_160112](https://user-images.githubusercontent.com/34144576/133438055-5e88f0be-8fa4-44fc-a9fc-544384af16ef.png)

**Comment by lc-kay** [comment]
Hi @cgsgak1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@cgsgak1 We recently added a new test case which your solution now fails on. Therefore, we did not add your custom test case. Thank you for your time.
