### ISSUE TITLE
Question doesn't constrain input numbers range - 385. Mini Parser

### ISSUE THREAD

**Issue by ampanasiuk** [LeetCode-Feedback/LeetCode-Feedback#4796]
#### Your LeetCode username
Movely

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question for 385. Mini Parser should clarify what the range for the input numbers is.

Example test case:
```
"2147483647"
"-2147483648"
"2147483648"
"-2147483649"
"9999999999999"
"-9999999999999"
```

Expected:
```
2147483647
-2147483648
2147483648
-2147483649
9999999999999
-9999999999999
```

Actual:
```
2147483647
-2147483648
-2147483648
2147483647
1316134911
-1316134911
```

#### Code you used for Submit/Run operation
```python
class Solution:
    def deserialize(self, s: str) -> NestedInteger:
         # the code doesn't matter for this bug report, the expected values are as above
         return NestedInteger()
```

#### Language used for code
Python3

#### Expected behavior
Either:
- the problem statement requires sint32 number range and inputs with numbers outside the range are rejected
- the model solution accepts arbitrary precision integers

#### Screenshots

none

#### Additional context

none

**Comment by lc-kay** [comment]
Hi @ampanasiuk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ampanasiuk 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
