### ISSUE TITLE
Missing Test Case - 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by ParthaEth** [LeetCode-Feedback/LeetCode-Feedback#4797]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The question is -
 Given an array of integers `nums` sorted in ascending order, find the starting and ending position of a given `target` value.

If `target` is not found in the array, return` [-1, -1]`.

You must write an algorithm with ` O(log n)` runtime complexity.

#### Code you used for Submit/Run operation

```
class Solution:
    def searchRange(self, nums: List[int], target: int) -> List[int]:
        left = 0
        right = len(nums) - 1
        mid = 0
        while left <= right:
            mid = (right + left) // 2
            if nums[mid] == target:
                break
            
            elif nums[mid] > target:  # go left half
                right = mid - 1
            
            else:  # Go right half
                left = mid + 1
        
        if not nums or nums[mid] != target:
            return [-1, -1]
        else:
            left = right = mid
            
            while left > 0 and nums[left -1] == target:
                left -= 1
            
            while right < len(nums) - 1 and nums[right + 1] == target:
                right += 1
            
            return [left, right]
                
```

#### Expected behavior

The Search is `O(log n)`. But then finding the left and the right index with the same value as `target` is linear. Meaning that is the whole array had the same value everywhere. The runtime is `O(n)`. Also this is impossible to solve this in any better time.

**Comment by lc-kay** [comment]
@ParthaEth Can you provide the current behavior and the expected behavior in more detail? Thank you!

**Comment by ParthaEth** [comment]
Never mind. My mistake. The question is alright. One can launch 2 binary searches to solve in log(n) time. I wasn't thinking right.
