### ISSUE TITLE
Missing Test Case - 978. Longest Turbulent Subarray

### ISSUE THREAD

**Issue by tomanavi** [LeetCode-Feedback/LeetCode-Feedback#4798]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases : 
- [9,9,9,9,7,8] test case missing

#### Description of the bug
Testcase missing

#### Code you used for Submit/Run operation

``class Solution {
    public int maxTurbulenceSize(int[] arr) {
        
        /*Input: arr = [9,4,2,10,7,8,8,1,9]
        Output: 5
        Explanation: arr[1] > arr[2] < arr[3] > arr[4] < arr[5]*/
        
        if(arr.length==1)
            return 1;
        
        //let's create a signseq array and deduct the turbulent array from that
        int[] signSeq=new int[arr.length-1];
        //when > we will use 1
        //when < we will use 0
        //when = we will use -1
        
        int prev = arr[0];
        int signSeqIndx = 0;
        int sum = 0;
        for (int i=1;i<arr.length;i++){
            
            if (prev > arr[i])
                signSeq[signSeqIndx] = 1;
            else if (prev < arr[i])
                signSeq[signSeqIndx] = 0;
            else
                signSeq[signSeqIndx] = -1;
            
            sum+=signSeq[signSeqIndx]; //for checking all same elements 
            
            prev = arr[i];   
            signSeqIndx++;           
        }
        
        if (sum<0) //all duplicate elements
            return 1;
        
        //Process signSeq
        // 1 1 0 1 0 -1 1 0
        int count=1;
        int maxCount=1;
        
        for (int i=1;i<signSeqIndx;i++){
            
            if (signSeq[i]==-1 || signSeq[i-1]==-1 || signSeq[i]==signSeq[i-1]){//means not flipping
                maxCount=Math.max(maxCount,count);
                count=1; //reset count
                
            }
            else
                count++;
            
        }
  int result = Math.max(maxCount,count)  ;                     
        
        //Note: elements would always be one more than the count
        return ++result;
        
    }
}``

#### Language used for code

Java

#### Expected behavior

[9,9,9,9,7,8] test case missing. Leetcode accepted my code but it was failing for this testcase.
I was checking for all duplicates in a wrong way
But there is no test to break my code.

TC: [9,9,9,9,7,8] 
Expected: 3
Actual: 1
Submission Result: Accepted

**Comment by lc-kay** [comment]
@tomanavi Your code is currently failing on test case [1,1,2]. Can you provide the submission details link to the accepted code?

**Comment by tomanavi** [comment]
https://leetcode.com/submissions/detail/555499165/

**Comment by lc-kay** [comment]
@tomanavi We've added a new test case since you first raised the issue, which your code now fails on. Therefore, we will not be adding the test case from this report. Thank you for your time.
