### ISSUE TITLE
Longest Turbulent Subarray: strange result for [] - 1

### ISSUE THREAD

**Issue by dmitrybalakov** [LeetCode-Feedback/LeetCode-Feedback#4799]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Bug 

#### Description of the bug
Expected answer for input [] (empty array) is 1, but expected 0.

**Comment by lc-kay** [comment]
Hi @dmitrybalakov 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
