### ISSUE TITLE
Hide Personal Details

### ISSUE THREAD

**Issue by darwinnacionales** [LeetCode-Feedback/LeetCode-Feedback#48]
**What kind of the bug**
- [X] problem
- [ ] solution
- [ ] language

**Describe the bug**
If I Google myself, I can see my LeetCode profile (it shows all my personal details).
Everyone can see how often people do LeetCode.
Please add an option to make a profile private.

**what language is your code written in**
N/A

**Expected behavior**
An option to make profile private.

**Comment by CooperCooperCooper** [comment]
Hi @darwinnacionales,
Thank you for raising this issue to our attention! We've received a lot of requests for a feature that will turn the profile private, and we've planned it on our future roadmap. If you have any other site/ UI-related suggestion, please share them with us on the technical support channel here: https://support.leetcode.com/hc/en-us. We appreciate your support and understanding.
