### ISSUE TITLE
1143. Longest Common Subsequence

### ISSUE THREAD

**Issue by dipta007** [LeetCode-Feedback/LeetCode-Feedback#480]
#### Your LeetCode username

dipta007

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Testcase

#### Description of the bug

I should get runtime error on my provided code. But when I submitted it, I got accepted and later I found out the problem in my code. I was assigning row and column inversely. 

#### Code you used for Submit/Run operation

```
// Longest Common Subsequence
class Solution:
    def longestCommonSubsequence(self, t1: str, t2: str) -> int:
        t1 = "#" + t1
        t2 = "$" + t2
        l1 = len(t1)
        l2 = len(t2)
        res = [[0 for _ in range(l1+4)] for _ in range(l2+4)]
        
        for i in range(1, l1):
            for j in range(1, l2):
                # print(i, j)
                now = res[i-1][j-1] + (1 if t1[i] == t2[j] else 0)
                now = max(now, res[i-1][j], res[i][j-1])
                res[i][j] = now
                
        return res[l1-1][l2-1]
```

#### Language used for code

Python3

#### Expected behavior

It should give runtime error on this test case
```
Input:
"abcdefghij"
"ace"

Output:
3
```

**Comment by CooperCooperCooper** [comment]
Hi @dipta007 ,
Thank you for reaching out to us. I've tested your code and this test case just now and got Runtime Error. Please see the screenshot attached here for more information. Would you please test the code again to see if it's still not producing Runtime Error for this test case?
<img width="770" alt="Screen Shot 2020-06-16 at 6 05 07 PM" src="https://user-images.githubusercontent.com/59751300/84843295-5d4a6f00-affc-11ea-8fea-aca36dc8959b.png">

**Comment by dipta007** [comment]
@CooperCooperCooper Can you try with the python code I provided?
It gives me accepted, whereas it should be runtime error on the test case I have provided

**Comment by dipta007** [comment]
@CooperCooperCooper same code is giving me accepted, its giving me runtime error when I manually provide the test case. So I think the test case is weak. This test case should be added to the system tests.
![image](https://user-images.githubusercontent.com/13894030/84989343-5854ff00-b165-11ea-9f13-1293f4a88671.png)

**Comment by aguilera123** [comment]
Hi @dipta007,
Thank you for your answer. I've relayed this request to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @dipta007 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @dipta007 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
