### ISSUE TITLE
Nitpicking test case - 314. Binary Tree Vertical Order Traversal

### ISSUE THREAD

**Issue by petertdinh** [LeetCode-Feedback/LeetCode-Feedback#4801]
#### Your LeetCode username
petertdinh

#### Category of the bug
Inappropriate Test Case

#### Description of the bug
May we get rid of test case no. 213 for this problem please? It's the only test case with duplicate values and serves to only trip up people who use something like the JavaScript `Object` as a hashmap.  You can of course use the `Map` object to get around this but why force this?

#### Code you used for Submit/Run operation

```
var verticalOrder = function(root) {
  const results = [];
  if (!root) return results
  const coords = {};
  const nodes = [];
  const dfs = (node, x, y) => {
    if (!node) return;
    coords[node.val] = [x, y];
    nodes.push(node.val);
    dfs(node.left, x - 1, y - 1);
    dfs(node.right, x + 1, y - 1);
  };
  dfs(root, 0, 0);
  nodes.sort((a, b) => coords[b][1] - coords[a][1])
    .sort((a, b) => coords[a][0] - coords[b][0]);
  let currentCol = coords[nodes[0]][0];
  let arr = [];
  for (let i = 0; i < nodes.length; i++) {
    if (currentCol === coords[nodes[i]][0]) {
      arr.push(nodes[i]);
    } else {
      results.push(arr);
      currentCol = coords[nodes[i]][0];
      arr = [];
      arr.push(nodes[i]);
    }
  }
  results.push(arr);
  return results;
};
```

#### Language used for code
JavaScript

#### Expected behavior
test cases that serve the purpose of testing if the user has a solid understanding of the question and has a working bug free algorithm to tackle the question. 

#### Additional context
`[0,1,4,2,8,37,13,3,34,14,29,66,45,22,19,5,6,39,69,null,17,null,35,null,null,null,null,32,null,null,58,null,9,10,7,null,55,89,null,42,51,57,null,86,null,null,null,11,18,53,15,12,null,null,null,null,null,48,null,80,84,75,65,null,null,26,64,27,21,9]` is the test case, notice 9 appears twice.

**Comment by lc-kay** [comment]
Hi @petertdinh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@petertdinh Our team reviewed this test case and found it to be necessary for this problem and will not remove it. Thank you for your understanding.
