### ISSUE TITLE
498. 对角线遍历

### ISSUE THREAD

**Issue by lqzo** [LeetCode-Feedback/LeetCode-Feedback#4808]
**你的 LeetCode 用户名**
liqingzhou

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
中文版题目描述欠缺

**期望行为**
像英文版一样补充一下 示例 和 限制条件

**屏幕截图**
<img width="645" alt="WechatIMG14440" src="https://user-images.githubusercontent.com/30641714/133741143-fa456c38-d1e4-4b1a-999e-2d021a9f70e3.png">
<img width="723" alt="WechatIMG14441" src="https://user-images.githubusercontent.com/30641714/133741155-0a481f4d-632a-4e5e-8a8c-880237c00090.png">

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lqzo  当前题目描述已更新，ID：liqingzhou 给予积分奖励，请查收。
