### ISSUE TITLE
Missing Test Case - 283. Move Zeroes

### ISSUE THREAD

**Issue by SPeredreev** [LeetCode-Feedback/LeetCode-Feedback#4809]
#### Submit/Run operation code

```
//Move Zeros
class Solution {
  public void moveZeroes(int[] nums) {
        int n = nums.length;
        int counter = (n >> 1) + 1; // This is the point of solution problem
        while (counter > 0) {
            for (int i = 0; i < n - 1; i++) {
                if (nums[i] == 0) {
                    nums[i] = nums[i + 1];
                    nums[i + 1] = 0;
                }
            }
            System.out.println(Arrays.toString(nums));
            counter--;
        }
    }
}
```

#### Expected behavior
Test should failing on this solution because the counter variable is wrong calculated, so test case like [0, 0, 0, 0, 0, 0, 1, 1, 1] should find this moment.

#### Screenshots
LeetCode:
![image](https://user-images.githubusercontent.com/34566978/133754774-0d7ca0b0-a9a7-4282-9e80-772b1dd7be96.png)

IDE:
![image](https://user-images.githubusercontent.com/34566978/133755101-e74d266b-68b7-436e-8c84-f2de1dbc9136.png)

**Comment by lc-kay** [comment]
<img width="1918" alt="Screen Shot 2021-09-17 at 12 20 40 PM" src="https://user-images.githubusercontent.com/70870126/133842580-54f4dfcc-a092-411e-a246-fdbd181b3645.png">
@SPeredreev The code you've provided results in Output Limit Exceeded. Can you please provide the submission link to the accepted solution? Thank you!

**Comment by SPeredreev** [comment]
There the last submission run without any failures: https://leetcode.com/submissions/detail/556672171/
I guess the console output inside while statement can call this Output Limit Exceeded.

**Comment by SPeredreev** [comment]
Yes, this is definitely the System.out.println(Arrays.toString(nums)); causes this problem: https://leetcode.com/submissions/detail/556675306/
My bad, i shouldn't add this line to submission code example.

**Comment by lc-kay** [comment]
Hi @SPeredreev 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @SPeredreev 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
