### ISSUE TITLE
Missing Test Case - 657. Robot Return to Origin

### ISSUE THREAD

**Issue by srikarkrishna7** [LeetCode-Feedback/LeetCode-Feedback#4812]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
 One of the submission is successful though it gives wrong output on execution with this testcase, when I pass "UUUUUUUUUUR" string. Like wise, there could be may such strings when I manually select a value for U, D, R, L and try to solve the problem

#### Code you used for Submit/Run operation
<!-- 
```

-->

```
class Solution {
    public boolean judgeCircle(String moves) { 
        int[] house = new int[22];
            house['U' - 'A'] = 1; 
            house['D' - 'A'] = -1;
            house['L' - 'A'] = 10;
            house['R' - 'A'] = -10;
        int result = 0;
        for(char n : moves.toCharArray()){
            result += house[n - 'A'];
        }
        System.out.println(result);
        return result == 0;
    }
}
```

#### Language used for code
<!-- Java -->
Java


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
Expected: False, Current: True


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
Hi @srikarkrishna7 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @srikarkrishna7 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by srikarkrishna7** [comment]
@lc-kay srikarkrishna is my LeetCode ID. Thank you!

**Comment by srikarkrishna7** [comment]
However, I believe the issue is not completely solved. For given test case and code, it works. Could you check for the this case **("UUUUUUUUUR")** and code.

```
class Solution {
    public boolean judgeCircle(String moves) { 
        int[] house = new int[22];
            house['U' - 'A'] = 1; 
            house['D' - 'A'] = -1;
            house['L' - 'A'] = 9;
            house['R' - 'A'] = -9;
        int result = 0;
        for(char n : moves.toCharArray()){
            result += house[n - 'A'];
        }
        System.out.println(result);
        return result == 0;
    }
}
```

As I have mentioned in previous message, there can be many such values for R & L , U & D pairs to break the limited number of test cases and pass the solution.

**Comment by lc-kay** [comment]
Hi @srikarkrishna7 
Thank you for following up. I've relayed this issue to our team to investigate further.

**Comment by lc-kay** [comment]
@srikarkrishna7 Our team has reviewed this report and found that it won't be reasonable to add all the test cases to fail the solutions. As one can generate at least 20000 solutions and each of them needs a special test case to fail it, 
it is nearly impossible to consider failing all of them. Therefore, we will not be adding this test case and we will not be accepting similar test cases in the future. Thank you for your understanding.
