### ISSUE TITLE
面试题 04.12. 求和路径

### ISSUE THREAD

**Issue by lqzo** [LeetCode-Feedback/LeetCode-Feedback#4813]
**你的 LeetCode 用户名**
liqingzhou

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 测试用例错误

**描述**
第 96 个通过测试用例，填入控制台后，无法进行 树结构可视化

**屏幕截图**
![image](https://user-images.githubusercontent.com/30641714/133868439-93151a7a-052a-4616-b51e-3944629253db.png)
![image](https://user-images.githubusercontent.com/30641714/133868387-cc0c5b44-9dcc-421e-8e6a-c050c90cbc17.png)

**Comment by feiceh** [comment]
您好，在与相关团队核实后：暂时无法重现这个问题出现的情况，本次 Ticket 将关闭，感谢您的反馈和支持。
![image](https://user-images.githubusercontent.com/61722985/134637060-4a032112-24d2-4330-8b06-08f9e9a182ca.png)
