### ISSUE TITLE
Wrong Output Of Test Case - 113. Path Sum II

### ISSUE THREAD

**Issue by g-harshit** [LeetCode-Feedback/LeetCode-Feedback#4815]
#### Your LeetCode username

gharshit1237

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[1,2]
1
Expected Output By Compiler - []
Actual Output will be - [[1]]

#### Code you used for Submit/Run operation

```
// Path Sum II
class Solution {
public:
   vector<vector<int>> pathSum(TreeNode* root, int targetSum) {
        vector<vector<int>> resp;
        if(root == NULL) return resp;
        vector<int> temp;
        calc(root,targetSum,resp,temp);
        return resp;
    }
    void calc(TreeNode* root, int targetSum, vector<vector<int>>& resp, vector<int>& temp){
        if(root == NULL) return;
        if(root->val <= targetSum){
            temp.push_back(root->val);
            if(targetSum-root->val == 0 && temp.size() > 0) {
                    resp.push_back(temp);
            }else{
                calc(root->left,targetSum-root->val,resp,temp);
                calc(root->right,targetSum-root->val,resp,temp);
            }
            temp.pop_back();
        }
        return;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input
[1,2]
1
Expected Output By Compiler - []
Actual Output will be - [[1]]
Since tree has root value 1 therefore there exists a path for sum 1

#### Screenshots

![Screenshot 2021-09-18 at 1 45 56 PM](https://user-images.githubusercontent.com/41697315/133881923-959b188a-c037-4ec2-9dbe-beeb89976a62.png)

**Comment by lc-kay** [comment]
@g-harshit The expected output is correct. Please check out this discuss post https://leetcode.com/problems/path-sum-ii/discuss/36914/Is-something-wrong-with-this-test-case Thank you for your time.
