### ISSUE TITLE
Missing Test Case - 551. Student Attendance Record I

### ISSUE THREAD

**Issue by durgaprasadmamidi** [LeetCode-Feedback/LeetCode-Feedback#4818]
#### Your LeetCode username
prasad_mamidi

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Give base test case is working fine when doing RUN CODE but same base test case is failing after SUBMIT code

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    bool checkRecord(string s) {
        int isLate = 0,totalAb = 0,tempLate=0;
	cin >> s;
	for(int i=0;i<s.size();i++){
	    if(s[i]=='L'){
	        tempLate+=1;
	    }
	    else if(s[i]=='A'){
	        totalAb+=1;
	        if(isLate<tempLate){
	            isLate = tempLate;
	        }
	        tempLate=0;
	    }
	    else{
	        if(isLate<tempLate){
	            isLate = tempLate;
	        }
	        tempLate=0;
	    }
	}
	if(isLate<tempLate){
	            isLate = tempLate;
	        }
	
	if(isLate<3 && totalAb<2){
	    return true;
	}
	else{
	    return false;
	}
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should pass the base test case as it is passing the same when I ran the code issue is only when I submit the code(with the same base test case which passed earlier).

#### Screenshots

![image](https://user-images.githubusercontent.com/58595074/133893890-e25cd05f-5758-43d7-b6b7-cad37b2260b8.png)

![image](https://user-images.githubusercontent.com/58595074/133893925-d88fee40-bb14-4c90-a9a3-2781edc35b7d.png)

**Comment by lc-kay** [comment]
Hi @durgaprasadmamidi 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
