### ISSUE TITLE
1464. Maximum Product of Two Elements in an Array

### ISSUE THREAD

**Issue by ovoistinov** [LeetCode-Feedback/LeetCode-Feedback#482]
#### Your LeetCode username
djasteel

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Test case

#### Description of the bug
When you use Run Code to run the below code - it fails with "Wrong Answer". However I was able to successfully submit the code and found the issue later on. This is due to missing test cases.

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxProduct(int[] nums) {
        if (nums == null || nums.length == 0) return 0;
        
        int max1 = 1;
        int max2 = 1;
        int max = 1;
        
        for (int i=0; i <nums.length; i++) {
            int cur = nums[i];
            
            if (cur >= max1) {
                max2 = max1;
                max1 = cur;
            } else if (cur > max2) {
                max2 = cur;
            }
            
            max = Math.max(max, (max1-1)*(max2-1));
        }
        
        return max;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Submission should lead to the "Wrong Answer" when submitting the code for the following 2 test cases:

Test case 1
```
Input:
[1,1,1,1]

Output:
0
```

Test case 2:
```
Input:
[1,1,1,9]

Output:
0
```

**Comment by CooperCooperCooper** [comment]
Hi @ovoistinov ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @ovoistinov ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
