### ISSUE TITLE
Missing Test Case - 300. Longest Increasing Subsequence

### ISSUE THREAD

**Issue by Deeksha-28** [LeetCode-Feedback/LeetCode-Feedback#4820]
class Solution {
    public int lengthOfLIS(int[] nums) {
       int total =0;
        int dp[] = new int[nums.length];
        for(int i =0;i<nums.length;i++){
            int max =0;
            for(int j=0; j<i;j++){
                if(nums[j]<nums[i]){
                    if(dp[j]>max){
                        max= dp[j];
                    }
                }
            }
            dp[i] = max+1;
            if(dp[i]>total){
                total = dp[i];
            }
        }
        return total;
        
    }
}

**Comment by lc-kay** [comment]
@Deeksha-28 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
