### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by carlosmontgomery** [LeetCode-Feedback/LeetCode-Feedback#4823]
#### Your LeetCode username

cmontg01

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The last test case of  ```Input: nums1 = [0], m = 0, nums2 = [1], n = 1``` is expected of an output 1 and in leetcode compiler I get 0 while in other ide 1 is outputted.

#### Code you used for Submit/Run operation

```
//  Merge Sorted Array
class Solution {
    public void merge(int[] nums1, int m, int[] nums2, int n) {
    System.out.format("Input: nums1: %s, m: %d, nums2: %s, n:%d%n",Arrays.toString(nums1),m,Arrays.toString(nums2),n );
        if (m == 0) {
            nums1 = nums2.clone();
        } else {
            for (int i = m; i < nums1.length; i++) {
                nums1[i] = nums2[i - n];
            }
            for (int i = 0; i < nums1.length - 1; i++) {
                int low = nums1[i];
                int high = nums1[i + 1];
                if (high < low) {
                    int temp = low;
                    nums1[i] = high;
                    nums1[i + 1] = temp;
                }
            }
        }
        System.out.println("Output: "+Arrays.toString(nums1));
    }
```

#### Language used for code

Java

#### Expected behavior

Expected output : [1]
Actual output : [0]

#### Screenshots

<img width="1440" alt="Screen Shot 2021-09-18 at 3 22 55 PM" src="https://user-images.githubusercontent.com/43247962/133908868-eb2682ad-8fdf-45a7-b7f9-0d19076ad1b1.png">

**Comment by lc-kay** [comment]
@carlosmontgomery Unfortunately, we are unable to troubleshoot the different behaviors from local IDE and LeetCode's environment. For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.
