### ISSUE TITLE
题目编辑器背景和竞赛编辑器背景不一致

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#4824]
**你的 LeetCode 用户名**
aestheticsjtu

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例
- [x] 其他

**描述**
目前leetcode的题目编辑器背景和周赛编辑器背景设置不一致。请看下面图片：

图一：leetcode题目编辑器的默认背景
![image](https://user-images.githubusercontent.com/90146234/133909749-f0f33fa9-559f-4faa-bb4f-53be9ac025a8.png)

图二：leetcode周赛编辑器的默认背景
![image](https://user-images.githubusercontent.com/90146234/133909757-3239da2a-bec1-45b2-b03f-e23ca5279928.png)

图三：leetcode题目编辑器的背景选择
![image](https://user-images.githubusercontent.com/90146234/133909779-eb69df9b-e3cc-41a6-ad8a-0013de084ecb.png)

图四：leetcode周赛编辑器的背景选择
![image](https://user-images.githubusercontent.com/90146234/133909827-8d00d98b-bfd9-411d-a528-ebee0bbec267.png)

很明显，两个编辑器的背景完全不一致。应该把周赛编辑器的背景设置变得跟题目编辑器的背景设置一样有多彩化。

**Comment by feiceh** [comment]
感谢反馈，该问题已转给相关团队后期会持续优化。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，目前我们会暂时关闭该 issue，后续使用中有任何问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。
