### ISSUE TITLE
Invalid answer - 282. Expression Add Operators

### ISSUE THREAD

**Issue by dmitrybalakov** [LeetCode-Feedback/LeetCode-Feedback#4825]
#### Your LeetCode username
dbalakov

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Language used for code
JavaScript

#### Expected behavior
For testcase 
```
"105"
5
```
missed answer in expected "1*05" 

#### Screenshots

<img width="960" alt="Screenshot 2021-09-19 at 2 27 58 AM" src="https://user-images.githubusercontent.com/79421380/133911015-e6f9ddbe-a541-4db8-b2c2-726198e5fb4d.png">

**Comment by lc-kay** [comment]
Hi @dmitrybalakov 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@dmitrybalakov The expected answer is correct. We have updated the statement and the examples to show that leading zeros are not accepted in the answer. Thank you for your time.
