### ISSUE TITLE
Some test cases may cause integer overflow - 2013. Detect Squares

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#4827]
#### Your LeetCode username

endlesscheng

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

If we add (0,0), (0,1), (1,0) 1666 times, then count (1,1) will return 1666\**3 = 4624076296 > 2\**31-1 = 2147483647.

#### Expected behavior

Integer overflow.

#### Screenshots

![image](https://user-images.githubusercontent.com/7086966/133916099-695ed5c5-fff9-45b0-a6e5-aa3d508035a9.png)

#### Additional context

Here is the test cases: [2013-detect-squares-integer-overflow.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7190998/2013-detect-squares-integer-overflow.txt)

**Comment by lc-kay** [comment]
@EndlessCheng Our invalid test case error message states that there's an integer overflow, which is what you described in your expected behavior.
