### ISSUE TITLE
161. One Edit Distance

### ISSUE THREAD

**Issue by ahmedinelec** [LeetCode-Feedback/LeetCode-Feedback#4829]
if the strings have the same length, and one character is different ,
how is this a one distance edit ?
s: abcDe
t: abcXe
→edit 1: Delete X
→ edit 2 : Write D to t as X position , or delete D from s
Total of 2 edits!
what constitutes a single edit should be stated more clearly

**Comment by lc-kay** [comment]
@ahmedinelec In the problem description, it listed out the criteria of a single edit. A string s is said to be one distance apart from a string t if you can:

Insert exactly one character into s to get t.
Delete exactly one character from s to get t.
Replace exactly one character of s with a different character to get t.

This test case satisfies the 3rd criteria. Thank you for your time.
