### ISSUE TITLE
185. Department Top Three Salaries

### ISSUE THREAD

**Issue by akenshin** [LeetCode-Feedback/LeetCode-Feedback#483]
#### Your LeetCode username
akensin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Test case

 

#### Description of the bug
My code and also provided solution return "Invalid Testcase"

#### Code you used for Submit/Run operation

select e1.Name as 'Employee', e1.Salary
from Employee e1
where 3 >
(
    select count(distinct e2.Salary)
    from Employee e2
    where e2.Salary > e1.Salary
)

#### Language used for code
MySQL

#### Expected behavior
I expected to get some result

#### Screenshots

![image](https://user-images.githubusercontent.com/37717393/84677971-1eeb7c00-af38-11ea-8f4e-ccf472b52975.png)
![image](https://user-images.githubusercontent.com/37717393/84678162-5bb77300-af38-11ea-9b21-613238b8a147.png)

**Comment by CooperCooperCooper** [comment]
Hi @akenshin ,
Thank you for reaching out to us. Since this is a duplicate issue as #459 , I will close this ticket now. We appreciate your support.
