### ISSUE TITLE
Incorrect input Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by BryTyr** [LeetCode-Feedback/LeetCode-Feedback#4830]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Some but not all of the testcases have incorrect input for the testcases.
For example, the input is string and and array of indexes. "codeleet" and [4,5,6,7,0,2,1,3].
The indexes for each character would give an answer of "leetcdoe" while the expected answer is "leetcode".

#### Code you used for Submit/Run operation

```
// Two Sum
public class Solution {
    public string RestoreString(string s, int[] indices) {
        char[] sortedArr = new char[indices.Length];
        char[] characters = s.ToCharArray();
        string outputStr = "";
        
        if(indices.Length<=1){
            return s;
        }
        
        for(int i=0;i<indices.Length;i++){
            sortedArr[i] = characters[indices[i]];
        }
        
        for(int i=0;i<sortedArr.Length;i++){
            outputStr+=sortedArr[i];
        }
        
        return outputStr;
    }
}
```

#### Language used for code
C#

#### Expected behavior
I expected the answer to be "leetcdoe" when the input for the testcase is "codeleet" and [4,5,6,7,0,2,1,3]

#### Screenshots
![image](https://user-images.githubusercontent.com/50870604/133925648-7bdcfe9a-0127-4933-ad6e-6822b75e6226.png)

**Comment by lc-kay** [comment]
@BryTyr This test case is correct, please check out https://leetcode.com/problems/shuffle-string/discuss/1030685/How-come-%22codeleet%22-with-indices-45670213-become-leetcode-Shouldn't-it-be-leetcdoe Thank you for your time.
