### ISSUE TITLE
Missing Test Case - 762. Prime Number of Set Bits in Binary Representation

### ISSUE THREAD

**Issue by matej-prokop** [LeetCode-Feedback/LeetCode-Feedback#4831]
See Example 1,  

```
Input: left = 6, right = 10
Output: 4
Explanation:
6 -> 110 (2 set bits, 2 is prime)
7 -> 111 (3 set bits, 3 is prime)
9 -> 1001 (2 set bits , 2 is prime)
10->1010 (2 set bits , 2 is prime)
```

I believe it would be valuable to add `8 => 1000 (1 set bits, 1 isn't prime)` there to make it complete. Without that the entire challenge is a bit tricky and hard to understand.

**Comment by lc-kay** [comment]
Hi @matej-prokop 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @matej-prokop 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
