### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by karunaramkumar** [LeetCode-Feedback/LeetCode-Feedback#4834]
#### Your LeetCode username

ck063r

#### Category of the bug
- [x] Solution

#### Description of the bug

Test input -123 passes in Run Console and fails during submission.

#### Code you used for Submit/Run operation

```
int reverse(int x){
    uint32_t num = (x > 0)?(uint32_t)x:(uint32_t)-x;
    uint32_t result;
    while(num){
        result = result*10;
        result += num%10;
        num /= 10;
    }
    return (x > 0)? (int)result:-(int)result;
}
```

#### Expected behavior

Tried testing out an input of -123 through 'Run Console'. I get the expected output(-321) and the console shows up as passed. I submitted the solution and Submission fails at test case 1(-123) stating the output of my program is -321321

#### Screenshots

![image](https://user-images.githubusercontent.com/57269762/133949510-5b22d756-3386-4355-aa68-efef95fc59e2.png)
![image](https://user-images.githubusercontent.com/57269762/133949517-eb2eb59d-e5cc-4c4d-99d8-be7a7a0aa7ac.png)

**Comment by lc-kay** [comment]
Hi @karunaramkumar 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
