### ISSUE TITLE
Description mistake - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by Pisces311** [LeetCode-Feedback/LeetCode-Feedback#4835]
#### Your LeetCode username

Pisces311

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem description states that the final answer fits on a 32-bit signed integer, which is incorrect. I submitted a C++ solution and get a Runtime Error (integer overflow) and it passed 60 test cases. I changed "int" into "long long" then it passed 61. I translate the solution into Python, and then "Accepted".

Actually, I tried some codes in "Discuss" and also got Runtime Errors. Probably the description should be modified.

#### Code you used for Submit/Run operation

Version 1
``` c++
class Solution {
   public:
    int numDistinct(string s, string t) {
        int n = s.size(), m = t.size();
        s = '#' + s;
        t = '#' + t;
        vector<vector<int>> dp(n + 1, vector<int>(m + 1));
        for (int i = 0; i <= n; i++) dp[i][0] = 1;
        for (int j = 1; j <= m; j++) {
            for (int i = 1; i <= n; i++) {
                dp[i][j] = dp[i - 1][j];
                if (s[i] == t[j]) {
                    dp[i][j] += dp[i - 1][j - 1];
                }
            }
        }
        return dp[n][m];
    }
};
```

Version 2
``` c++
using ll = long long;

class Solution {
   public:
    int numDistinct(string s, string t) {
        int n = s.size(), m = t.size();
        s = '#' + s;
        t = '#' + t;
        vector<vector<ll>> dp(n + 1, vector<ll>(m + 1));
        for (int i = 0; i <= n; i++) dp[i][0] = 1;
        for (int j = 1; j <= m; j++) {
            for (int i = 1; i <= n; i++) {
                dp[i][j] = dp[i - 1][j];
                if (s[i] == t[j]) {
                    dp[i][j] += dp[i - 1][j - 1];
                }
            }
        }
        return dp[n][m];
    }
};
```

Version 3
``` python
class Solution:
    def numDistinct(self, s: str, t: str) -> int:
        n, m = len(s), len(t)
        s = '#' + s
        t = '#' + t
        dp = [[0] * (m + 1) for _ in range(n + 1)]
        for i in range(n + 1):
            dp[i][0] = 1
        for j in range(1, m + 1):
            for i in range(1, n + 1):
                dp[i][j] = dp[i-1][j]
                if s[i] == t[j]:
                    dp[i][j] += dp[i-1][j-1]
        return dp[n][m]
```

#### Language used for code

C++ & Python

#### Expected behavior

Delete the last sentence in the problem description.

**Comment by lc-kay** [comment]
Hi @Pisces311 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Pisces311 Our team has reviewed your report and concluded that the final answer of all test cases still fit in a 32-bit integer. Thank you for your time.
