### ISSUE TITLE
Solution Issue -  1448. Count Good Nodes in Binary Tree

### ISSUE THREAD

**Issue by smetal1** [LeetCode-Feedback/LeetCode-Feedback#4836]
- Solution : 1448. Count Good Nodes in Binary Tree
- Language: Java
**Given Approach 1 :** 
``
class Solution {
    private int numGoodNodes = 0;
    
    public int goodNodes(TreeNode root) {
        dfs(root, Integer.MIN_VALUE);
        return numGoodNodes;
    }
    
    private void dfs(TreeNode node, int maxSoFar) {
        if (maxSoFar <= node.val) {

            numGoodNodes++;
        }
        
        if (node.right != null) {
            dfs(node.right, Math.max(node.val, maxSoFar));
        }

        if (node.left != null) {
            dfs(node.left, Math.max(node.val, maxSoFar));
        }
    }
}
``

**Correct/Expected Solution:**

``
class Solution {
    private int numGoodNodes = 0;
    
    public int goodNodes(TreeNode root) {
        dfs(root, Integer.MIN_VALUE);
        return numGoodNodes;
    }
    
    private void dfs(TreeNode node, int maxSoFar) {
        if (maxSoFar <= node.val) {
           **//Assign maxSoFar to node.val
           maxSoFar=node.val;   // correction** 
            numGoodNodes++;
        }
        
        if (node.right != null) {
            dfs(node.right, Math.max(node.val, maxSoFar));
        }

        if (node.left != null) {
            dfs(node.left, Math.max(node.val, maxSoFar));
        }
    }
}
``

**Comment by lc-kay** [comment]
@smetal1 Please elaborate on the issue you are reporting for Approach I of this solution. Thank you!

**Comment by LC-Sue** [comment]
Hi @smetal1,
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
