### ISSUE TITLE
Missing Test Case - 2014. Longest Subsequence Repeated k Times

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#4838]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A solution get accepted but fails on one test case.
The missing test case is as follows.
```
"ytnmrawyijaipolvxiibumeimkciskiwibkvbuslhnlgsqu"
6
```

#### Code you used for Submit/Run operation
```
class Solution:
    def longestSubsequenceRepeatedK(self, s: str, k: int) -> str:
        def check(pk):
            ed = 0
            for i in range(len(pk)):
                while ed < len(s) and s[ed] != pk[i]:
                    ed += 1
                if ed == len(s):
                    return False
                ed += 1
            return True
        n = min(8, len(s))
        ans = ""
        st = s[:n]
        for state in range(1, 1 << n):
            sk = ""
            for j in range(n):
                if state & (1 << j):
                    sk += st[j]
            pk = sk*k
            if len(sk) < len(ans):
                continue
            if check(pk):
                if len(sk) > len(ans):
                    ans = sk
                elif len(sk) == len(ans) and sk > ans:
                    ans = sk
        st = s[-n:]
        for state in range(1, 1 << n):
            sk = ""
            for j in range(n):
                if state & (1 << j):
                    sk += st[j]
            pk = sk*k
            if len(sk) < len(ans):
                continue
            if check(pk):
                if len(sk) > len(ans):
                    ans = sk
                elif len(sk) == len(ans) and sk > ans:
                    ans = sk
        return ans
```

#### Language used for code
Python3

#### Expected behavior
The test case should be added so the code above will get Wrong Answer when submitted.
```
"ytnmrawyijaipolvxiibumeimkciskiwibkvbuslhnlgsqu"
6
```

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/134000080-26357c6a-126f-4705-a3a4-9f8d45a8a277.png)

**Comment by lc-kay** [comment]
@stormsunshine Your solution currently results in TLE error. Therefore, we will not be adding this test case. Thank you for your time. 
<img width="1895" alt="Screen Shot 2021-09-20 at 10 15 14 AM" src="https://user-images.githubusercontent.com/70870126/134045380-0b317bdc-6c17-4e10-95d1-196ed58f7ef8.png">
