### ISSUE TITLE
Typo in Constraints - 480. Sliding Window Median

### ISSUE THREAD

**Issue by c-jain** [LeetCode-Feedback/LeetCode-Feedback#4839]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### N/A

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @c-jain 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @c-jain 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
