### ISSUE TITLE
Missing Test Case in 1402. Reducing Dishes

### ISSUE THREAD

**Issue by gohanssj9** [LeetCode-Feedback/LeetCode-Feedback#4840]
**Your LeetCode username**
gohanssj9

**Category of the bug**
Missing Test Case

Question Link :: https://leetcode.com/problems/reducing-dishes/

**Constraints:**
```
n == satisfaction.length
1 <= n <= 500
-10^3 <= satisfaction[i] <= 10^3
```

**Description of the bug**
For the Test Case :
`Input: satisfaction = [-1]
`
For the above input, Output should be 0 since Chef will not make the dish.
But even when -1 is returned as the Output, the solution is accepted on clicking Submit.
While Local Testing shows 0 as the Output and is showing Wrong Answer, the overall solution is shown as Accepted. This Test case is missing in the Overall Test cases.

**Code you used for Submit/Run operation**
```
class Solution {
public:
    int maxSatisfaction(vector<int>& satisfaction) {
        int satissize = satisfaction.size();
        if(satissize == 1) return satisfaction[0];
        
        sort(satisfaction.begin(), satisfaction.end());
        int max_profit = 0;
        
        int csum = 0;
        int total_sum = 0;
        for(int i = satissize - 1; i >= 0; i--)
        {
            csum = csum + satisfaction[i];
            total_sum += csum;
            max_profit = max(max_profit, total_sum);
        }
        return max_profit;
    }
};
```
Incorrect Solution ID that should've failed for the above test case, but is Accepted :: https://leetcode.com/submissions/detail/558195052/

**Language used for Code**
C++

**Expected Behavior**
Code should not be accepted and should show Wrong Answer for the above Test case on clicking Submit.

**Actual Behavior**
Code is shown as Accepted on clicking Submit. It means that the above test case seems to be missing from the set of Test cases :)

**Comment by lc-kay** [comment]
Hi @gohanssj9 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gohanssj9 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
