### ISSUE TITLE
Lack of clarity in 1239. Maximum Length of a concatenated string with unique characters

### ISSUE THREAD

**Issue by shivam18shah** [LeetCode-Feedback/LeetCode-Feedback#4842]
The sample test cases or the problem description do not clarify whether a single input string in an array could have repeating characters. In an interview, I would ask for this clarification. However, in this case, there is no such clarification in constraints or even sample cases that address this question. If you see in the sample cases, Example 1 has the character 'u' in different strings. Constraints say that arr[i] contains only lowercase characters. A test case like ["aa"] would return 0 if it is considered a valid test case.

![image](https://user-images.githubusercontent.com/30237912/134070497-80410596-1730-4f80-885f-886d4b7fea3d.png)

![image](https://user-images.githubusercontent.com/30237912/134070413-e613089b-1d74-48f6-9633-56c4f649cfe8.png)

**Comment by lc-kay** [comment]
Hi @shivam18shah 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @shivam18shah 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
