### ISSUE TITLE
Missing Test Case - 2013. Detect Squares

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#4843]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The *standard solution* gets Runtime Error on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7200921/1.txt)

#### Additional context

This is a valid input, however the answer exceeds int. The standard solution uses int to store the result.

**Comment by lc-kay** [comment]
@hqztrue Can you please provide the submission details link to the standard solution you used?

**Comment by hqztrue** [comment]
When you use this data as input to test any code, it will show "Invalid Testcase" because solution.cpp overflows. However looking at the problem description this testcase is actually valid. This testcase is generated by inserting 1666 copies of [1,0], [0,1], [1,1], and then query at [0,0]. The answer is 1666^3>int range.
![1](https://user-images.githubusercontent.com/11583428/134437307-31bc412d-159f-43d7-85ee-07385fbd2803.png)

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hqztrue The answer to this test case doesn't fit in a 32-bit integer and that's why it was rejected. We have reduced the constraints. Thank you for your time.
