### ISSUE TITLE
`1002. 查找常用字符`题目名和题目描述的中文翻译有问题

### ISSUE THREAD

**Issue by youngqqcn** [LeetCode-Feedback/LeetCode-Feedback#4844]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**

题目的中文翻译有问题,
1. 英文提名`find-common-characters`,  现在的中文题名是"查找常用字符" , `common` 应该翻译为"公共", 题目的中文名应该翻译为 "查找公共字符"
2.  题目的表述方式也有问题,  
英文原题描述:

```
Given a string array words, return an array of all characters that show up in all strings within the words (including duplicates). You may return the answer in any order.
```

正常的翻译应该是
```
给定一个字符串数组单词，返回一个包含单词中所有字符串中出现的所有字符的数组(包括重复的字符)。你可以按任何顺序返回答案。
```

中文翻译加入的一个让人莫名其妙"例如", 

```
例如，如果一个字符在每个字符串中出现 3 次，但不是 4 次，则需要在最终答案中包含该字符 3 次。
```

这句话什么意思? 什么叫明显`出现 3 次，但不是 4 次，`???

这个例如应该去掉

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目描述已调整更新，力扣会定期更新，保障稳定和体验优化。
