### ISSUE TITLE
Missing Test Case - 144. Binary Tree Preorder Traversal

### ISSUE THREAD

**Issue by Codeupsid108** [LeetCode-Feedback/LeetCode-Feedback#4847]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Codeupsid108 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
