### ISSUE TITLE
Missing Test Case - 167. Two Sum II - Input array is sorted

### ISSUE THREAD

**Issue by Sahil255** [LeetCode-Feedback/LeetCode-Feedback#4848]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

in the third example, there is a typo mistake. It should be
Explanation: The sum of -1 and 0 is -1. Therefore index1 = 1, index2 = 2.

**Current:     "Explanation: The sum of 1 and 0 is -1. Therefore index1 = 1, index2 = 2."
Corrected: "Explanation: The sum of -1 and 0 is -1. Therefore index1 = 1, index2 = 2."**
instead of -1 there is 1 written.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @Sahil255 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Sahil255 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
