### ISSUE TITLE
1976. Number of Ways to Arrive at Destination

### ISSUE THREAD

**Issue by Thoughtscript** [LeetCode-Feedback/LeetCode-Feedback#4849]
#### Your LeetCode username
https://leetcode.com/Thoughtscript/

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I've been verifying some test cases for https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/:

```
8
[[0,6,25],[0,1,1],[1,2,25],[1,3,1],[6,3,1],[3,5,25],[6,5,0],[2,5,25],[0,4,25],[4,6,25],[7,6,1],[7,5,1]]
Expected: 0
```

This is seemingly a valid test case but this should logically always have an expected output of at least `1` since there's always at least one shortest path (for this kind of scenario at least). The 2 shortest paths should be: `7 -> 6 -> 3 -> 1 -> 0` and `7 -> 5 -> 6 -> 3 -> 1 -> 0`. I get `2` with my code but the expected answer is `0`.

Also:

```
8
[[0,6,25],[0,1,1],[1,2,25],[1,3,1],[6,3,1],[3,5,25],[6,5,0],[2,5,25],[0,4,25],[4,6,25],[7,6,25],[7,5,1]]
Expected: 0
```

The shortest path should be: `7 -> 5 -> 6 -> 3 -> 1 -> 0`. I get `1` but the expected answer is `0`.

If I'm correct, the test cases need to be accounted for or the question constraints further refined. If I'm wrong, I see nothing obviously incorrect given the question description and would appreciate any advice about why the test cases below are invalid here.

#### Code you used for Submit/Run operation
Not sure my code is correct here (apologies for its ugliness or comment typos):

```JavaScript
// Path is bidirectional not one-way
const countPaths = (n, roads) => {
    const last = n - 1, MX = Math.pow(10, 9) + 7
    
    // Generate routes and maps
    // M gets time counts (minutes)
    // R is for route path times
    let R = {}, M = {}
    for (let i = 0; i < roads.length; i++) {
        const C = roads[i]
        
        M[`${C[0]}-${C[1]}`] = roads[i][2]
        M[`${C[1]}-${C[0]}`] = roads[i][2]
        
        if (R[C[0]]) R[C[0]].push(C[1])
        else R[C[0]] = [C[1]]
        
        if (R[C[1]]) R[C[1]].push(C[0])
        else R[C[1]] = [C[0]]
    }
    
    //console.log(R)
    //console.log(M)
    
    let shortest = -1, count = 0, counts = {}
    
    // Work backword from key last
    nextLevel(R[last], counts, R, M, last, 0, {}) 
    let result = counts[Object.keys(counts)[0]]
    while (result > MX) {
        result -= MX
    }
    //console.log(counts)
    return result
}

const nextLevel = (level, counts, R, M, current, time, visited) => {     
    if (current === 0) {
        if (counts[time]) counts[time]++
        else counts[time] = 1
    }
    
    for (let i = 0; i < level.length; i++) {
        const L = level[i]
        if (!visited[L]) {
            let V = Object.assign([], visited)
            V[L] = true
            nextLevel(R[L], counts, R, M, L, time + M[`${current}-${L}`], V)
        }
    }
}
```

#### Language used for code
JavaScript

#### Expected behavior
The Expected Answer should be GTE to `0`.

It should be GT `0` in the examples above (and where a path exists from to `n-1 ` to node `0 `).

#### Screenshots

![Screen Shot 2021-09-21 at 1 05 27 PM](https://user-images.githubusercontent.com/10905039/134224339-635ec2e7-8a4f-4d30-833f-9d11282bb475.png)
![Screen Shot 2021-09-21 at 1 05 02 PM](https://user-images.githubusercontent.com/10905039/134224341-4cb29ec0-a81f-4079-b710-773cde25aa09.png)

#### Additional context
No global variables were used (removing these or initializing these previously resolved another issue I had before).

The following test cases all produce the correct expected values (as does my code above):

```
7
[[0,6,7],[0,1,2],[1,2,3],[1,3,3],[6,3,3],[3,5,1],[6,5,1],[2,5,1],[0,4,5],[4,6,2]]

2
[[1,0,10]]

8
[[0,6,7],[0,1,2],[1,2,3],[1,3,3],[6,3,3],[3,5,1],[6,5,1],[2,5,1],[0,4,5],[4,6,2],[0,7,3]]

8
[[0,6,7],[0,1,2],[1,2,3],[1,3,3],[6,3,3],[3,5,1],[6,5,1],[2,5,1],[0,4,5],[4,6,2],[0,7,3],[7,3,2]]

11
[[0,6,7],[0,1,2],[1,2,3],[1,3,3],[6,3,3],[3,5,1],[6,5,1],[2,5,1],[0,4,5],[4,6,2],[0,7,3],[7,3,2],[10,7,1],[10,9,3],[8,0,0],[7,4,2]]

4
[[0,1,1],[2,1,2],[3,2,3],[1,3,3]]

5
[[0,1,1],[2,1,2],[3,2,3],[1,3,3],[4,2,1],[4,3,1]]

5
[[0,1,8],[2,1,2],[3,2,3],[1,3,3],[4,2,7],[4,3,1]]

5
[[0,1,8],[2,1,6],[3,2,4],[1,3,3],[4,2,7],[4,3,1]]

6
[[0,1,8],[2,1,6],[3,2,4],[1,3,3],[4,2,7],[4,3,1],[5,1,4]]

9
[[0,1,8],[2,1,6],[3,2,4],[1,3,3],[4,2,7],[4,3,1],[5,1,4],[6,5,4],[7,6,61],[8,5,4]]
```

**Comment by lc-kay** [comment]
Hi @Thoughtscript 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Thoughtscript** [comment]
@lc-kay - thanks so much and sorry about my delayed message - glad to help!
