### ISSUE TITLE
1477. Find Two Non-overlapping Sub-arrays Each With Target Sum - Weak Test Cases

### ISSUE THREAD

**Issue by coder1033** [LeetCode-Feedback/LeetCode-Feedback#485]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Test Case

#### Description of the bug
Probelm 1477 in recently held biweekly-contest-28 their is a Test Case which was not 
covered. I tried this problem after the contest. Also I've got correct output for all the test cases that are in the previous issues. But their is a test case for which my output and expected output are different. And Expected output is the correct one but my code still got AC

#### Code you used for Submit/Run operation

```
class Solution:
    def minSumOfLengths(self, arr: List[int], target: int) -> int:
        curr = 0
        d = collections.defaultdict(list)
        i = 0
        while i<len(arr):
            val = arr[i]
            if curr+val<target:
                if curr==0:
                    s=i
                curr+=val
                i+=1
            elif curr+val>target:
                if curr!=0:
                    curr-=arr[s]
                    s+=1
                else:
                    i+=1
            else:
                if curr==0:
                    d[1].append([i,i])
                else:
                    curr+=val
                    d[i-s+1].append([s,i])
                i+=1
        t = list(d.keys())
        ans = 1000000
        
        #for i in range(len(t)):
        #    for j in range(len(t)):
        #        a,b = d[t[i]][0]
        #        a1,b1 = d[t[j]][-1]
        #        if b<a1 or b1<a:
        #            ans = min(ans,t[i]+t[j])
        
        # Using above commented loops instead of below loops will AC in all the cases.
        # Using below loops should get WA but it is getting AC.
        
        for i in range(len(t)):
            for j in range(i,len(t)):
                a,b = d[t[i]][0]
                a1,b1 = d[t[j]][-1]
                if b<a1 or b1<a:
                    ans = min(ans,t[i]+t[j])
        
        return ans if ans!=1000000 else -1
```

#### Expected behavior
```
Test Case -

    arr = [2,1,3,3,2,3,1]

    target = 6

    my output = 6

    expected output = 5

```

#### Screenshots
![Screenshot (54)](https://user-images.githubusercontent.com/40430894/84714116-5e42b880-af8a-11ea-9500-5e84ea5548a2.png)
![Screenshot (55)](https://user-images.githubusercontent.com/40430894/84714128-63a00300-af8a-11ea-8071-13e6c552062f.png)

**Comment by lc-christina** [comment]
Hi @coder1033 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
