### ISSUE TITLE
230. Kth Smallest Element in a BST

### ISSUE THREAD

**Issue by WillWcchan** [LeetCode-Feedback/LeetCode-Feedback#4852]
#### Your LeetCode username

Willwcchan

#### Category of the bug
- [ X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the description of the problem, it should state return the node's value. Not the node itself. 

_Given the root of a binary search tree, and an integer k, return the kth (1-indexed) smallest **element's value** in the tree._

not 

Given the root of a binary search tree, and an integer k, return the kth (1-indexed) smallest element in the tree.

**Comment by lc-kay** [comment]
Hi @WillWcchan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @WillWcchan 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
