### ISSUE TITLE
Missing Test Case - 213. House Robber II

### ISSUE THREAD

**Issue by PranamBhat** [LeetCode-Feedback/LeetCode-Feedback#4854]
#### Your LeetCode username
ask2pranam

#### Category of the bug
- [ ] Question

#### Description of the bug
In this Question, Example scenario is given wrong.

#### Code you used for Submit/Run operation
NA

#### Language used for code
JavaScript

#### Expected behavior
It should be:

Example 1:

Input: nums = [2,3,2]
Output: 3
Explanation: You cannot rob house 1 (money = 2) and then rob house 2 (money = 3), because they are adjacent houses.

#### Screenshots
Attached

![image](https://user-images.githubusercontent.com/32120033/134283354-5714d3bb-0195-407f-92ba-37b35f07b3c0.png)

#### Additional context
No

**Comment by PranamBhat** [comment]
The highlighted line should be "**rob house 2 (money = 3)**".

**Comment by azhar1038** [comment]
It is obvious that house 2 is adjacent to house 1 but the explanation is trying to highlight the fact that house 3 is also adjacent to house 1 because houses are **arranged in circle**

**Comment by lc-kay** [comment]
Hi @PranamBhat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@PranamBhat The example is correct - The houses are circular, houses 1 and 3 are adjacent. Thank you for your time.

**Comment by PranamBhat** [comment]
No. It is incorrect.

It should be "rob house 2 (money = 3)".
