### ISSUE TITLE
Inaccurate examples: 1239. Maximum Length of a Concatenated String with Unique Characters

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#4856]
#### Your LeetCode username

Leaderboard

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The example given for the question says that

```
Input: arr = ["un","iq","ue"]
Output: 4
Explanation: All possible concatenations are "","un","iq","ue","uniq" and "ique".
Maximum length is 4.
```

This isn't quite right, since the concatenation "unue" is also possible. I presume it means valid concatenations (not just any concatenation). This should be corrected.

#### Code you used for Submit/Run operation

N/A
#### Language used for code

N/A

#### Expected behavior

See above.

#### Screenshots

N/A

#### Additional context

N/A

**Comment by lc-kay** [comment]
Hi @Leader-board 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Leader-board 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
