### ISSUE TITLE
Missing Test Case - 140. Word Break II

### ISSUE THREAD

**Issue by niko-vulic** [LeetCode-Feedback/LeetCode-Feedback#4857]
#### Your LeetCode username
icaruss

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
A test case such as:
"eeeeeeeeeeeeeeeeeeef"
["e","ee","eee","eeee","eeeee","eeeeee","eeeeeee","eeeeeeee"]

should put some pressure on approaches that do not rely on dynamic programming.
Testing with a basic recursive approach yields times of approx ~700-900ms vs a DP approach of about 40ms for the above test case

#### Code you used for Submit/Run operation

```
class Solution:
    def wordBreak(self, s: str, wordDict: List[str]) -> List[str]:
        memo = {}

        resultSet = self.wordBreakHelper(memo, s, wordDict)
        result = [' '.join(item) for item in memo[s]]
        return result

    def wordBreakHelper(self, memo, s: str, wordDict: List[str]) -> bool:

        # Word already calculated
        if s in memo:
            return memo[s]

        # This item has never been traversed before, initialize it
        memo[s] = []

        # Iterate the current word by the wordDict
        for prefix in wordDict:
            if s.startswith(prefix):
                suffix = s[len(prefix):]


                # RECURSION BASE CASE - If suffix empty, word complete
                if not suffix:
                    memo[s].append([prefix])
                # Else, word might already be calculated - sum the values
                elif suffix in memo and memo[suffix]:
                    for combo in memo[suffix]:
                        memo[s].append([prefix]+combo)
                # If it hasn't been calculated already, calc it
                elif suffix not in memo:
                    self.wordBreakHelper(memo, suffix, wordDict)
                    if memo[suffix]:
                        for combo in memo[suffix]:
                            memo[s].append([prefix] + combo)
```

#### Language used for code
Python3

#### Expected behavior
The result should be [], however it will take more time to compute for non-dynamic programming approaches to this question.

#### Screenshots
https://imgur.com/a/CTnht2N
Uploaded 3 screenshots to show sample runtimes for the default test case + "eeeeeeeeeeeeeeeeeeef"
["e","ee","eee","eeee","eeeee","eeeeee","eeeeeee","eeeeeeee"]

with two code samples - DP approach and non-DP approach

**Comment by lc-kay** [comment]
Hi @niko-vulic 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @niko-vulic 
Thank you for your time. We've reviewed your report and compared it to our test case set and found that we have a similar one already. Therefore, we will not be adding it.
