### ISSUE TITLE
Missing Test Case - 270. Closest Binary Search Tree Value

### ISSUE THREAD

**Issue by sapphire921** [LeetCode-Feedback/LeetCode-Feedback#4858]
#### Your LeetCode username
sapphire921

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
A test case like:
[400,200,500,100,300]
3.714286 
should be added to this question. 
The below code should fail on that test case, but when I submit it, it passes all the existing tests cases.

#### Code you used for Submit/Run operation
```
class Solution:
    def closestValue(self, root: TreeNode, target: float) -> int:
        res = -1
        while root:
            res = min(root.val, res, key = lambda x: abs(target - x))
            root = root.left if target < root.val else root.right
        return res
```

#### Language used for code
Python3

#### Expected behavior
The above code should fail.

**Comment by lc-kay** [comment]
Hi @sapphire921 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sapphire921 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
