### ISSUE TITLE
Missing Test Case - 704. Binary Search

### ISSUE THREAD

**Issue by jaideeee** [LeetCode-Feedback/LeetCode-Feedback#4859]
#### Your LeetCode username
jsdee

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

For an array containing a single element, if that is missing then below case will fail, but there is no such case in listed
testcases, so my all testcases got passed.

#### Code you used for Submit/Run operation

```
// Binary Search
class Solution {
public:
    int search(vector<int>& nums, int target) {
        int low = 0, high = nums.size() - 1, mid;
        while (low <= high) {
            mid = low + (high - low)/2;
            if (nums[mid] < target) low = mid + 1;
            else high = mid - 1;
        }
        return nums[low] == target ? low : -1;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

Should have seen a runtime exception with the above code, if I search a missing element in size of 1.

#### Additional context

Use testcase 
[-1]
2
Ideally it should return -1, but above code gives segmentation fault but it is passed during submission, so need to add such case.

**Comment by lc-kay** [comment]
Hi @jaideeee 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jaideeee 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
