### ISSUE TITLE
88. Merge Sorted Array

### ISSUE THREAD

**Issue by lpadgett** [LeetCode-Feedback/LeetCode-Feedback#486]
Leetcode Username: lpadgett

#### Category of the bug
- Solution

#### Description of the bug
I found a test case that breaks the "Expected Output" generator, where it generates an incorrect output.

#### Code Used for Submit/Run operation
//Merge Sorted Array
```
class Solution {
    public void merge(int[] nums1, int m, int[] nums2, int n){
        System.arraycopy(nums2, 0, nums1, m, n);
        Arrays.sort(nums1);
    }
}
```

#### Language used for code
Java

#### Expected behavior
I provided the following test case:
[1,2,3,4,4,4,4,8,7,9,12,0,0,0,0,0]
11
[2,5,6,8,49]
5

I expected the following output for "Expected", which the code correctly generates in the "Output" row:
[1,2,2,3,4,4,4,4,5,6,7,8,8,9,12,49]

In reality the following was generated for "Expected," which was incorrect:
[1,2,2,3,4,4,4,4,5,6,8,7,8,9,12,49]

#### Screenshots
![Screen Shot 2020-06-15 at 6 46 04 PM](https://user-images.githubusercontent.com/20961889/84716369-7e498c00-af38-11ea-9a64-49d3b5f8c37e.png)

**Comment by CooperCooperCooper** [comment]
Hi @lpadgett ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @lpadgett ,
Thank you for your time. The provided test case is invalid since the first array is not sorted. We appreciate your support.
