### ISSUE TITLE
Missing Test Case - 1239. Maximum Length of a Concatenated String with Unique Characters

### ISSUE THREAD

**Issue by chickenbisket** [LeetCode-Feedback/LeetCode-Feedback#4863]
#### Your LeetCode username
Chickenbisket

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

This code will pass the test cases in use, but will not solve for the actual max length of a concatenated string with unique characters. It simply orders the arr from largest to smallest and then smallest to largest and looks at what the longest concat it can make. I'm submitting the below test case which would trip up that solution.
```
["abcdx","yfrq","fw","kr","zyrn",]
```
should result in an answer of 11 but will only return 9 with the below code that currently passes all in use test cases.

#### Code you used for Submit/Run operation

```
class Solution:
    def maxLength(self, arr: List[str]) -> int:
        letterCheck = 0
        tempString = ''     
        returnList = []

        arr = sorted(arr,key = len, reverse = True)
        arr2 = sorted(arr,key = len, reverse = False)

        for words in arr:
            for i in arr[arr.index(words):]:
                for l in i:
                    if l in tempString:
                        letterCheck = 1
                    if i.count(l) > 1:
                        letterCheck = 1
                if letterCheck == 0:
                    tempString = tempString + i
                letterCheck = 0
            returnList.append(len(tempString))
            tempString = ''


        for words in arr2:
            for i in arr2[arr2.index(words):]:
                for l in i:
                    if l in tempString:
                        letterCheck = 1
                    if i.count(l) > 1:
                        letterCheck = 1
                if letterCheck == 0:
                    tempString = tempString + i
                letterCheck = 0
            returnList.append(len(tempString))
            tempString = ''

        return(max(returnList))
```

#### Language used for code

Python3

#### Expected behavior

I expected the code to fail the test cases, but it passed.

**Comment by lc-kay** [comment]
Hi @chickenbisket 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @chickenbisket 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
