### ISSUE TITLE
Missing Test Case - 1239. Maximum Length of a Concatenated String with Unique Characters

### ISSUE THREAD

**Issue by RBT0101** [LeetCode-Feedback/LeetCode-Feedback#4864]
#### Your LeetCode username

RBT0101

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case, include a test case where array length is 1 and arr[0] contains non-unique
letters. An example would be arr = ['uu']. If you submit the code below, it will pass all test
cases but line 1 of the code is incorrect. Please add the above test case. Thanks.

#### Code you used for Submit/Run operation

```
var maxLength = function(arr) {
    if (arr.length === 1) return arr[0].length; // THIS IS INCORRECT BUT PASSES ALL TEST CASES
    var max = 0;
    var map = new Map();
    var findMaxLength = (index) => {
        if (index >= arr.length) return;
        
        for (let i=index; i<arr.length; i++){
            let found = false;
            for (let c of arr[i]){
                map.set(c,(map.get(c) || 0) + 1);
                if (map.get(c) > 1){
                    found = true;
                }
            }
            
            if (found){
                for (let k of arr[i]){
                    if (map.get(k) > 0) map.set(k, map.get(k)-1);
                    if (map.get(k) === 0) map.delete(k);
                }
            }
            else if (!found){
                for (let c of arr[i]){
                    map.set(c,1);
                }

                max = Math.max(max, [...map.keys()].length);
                findMaxLength(i+1);
                for (let c of arr[i]){
                    map.delete(c);
                }
            }
        }
        
        return;
    }
    
    findMaxLength(0);
    return max;
};
```

#### Language used for code

JavaScript

#### Expected behavior

Code submission should fail. Test case is insufficient.

**Comment by lc-kay** [comment]
Hi @RBT0101 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @RBT0101 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
