### ISSUE TITLE
Test Case Need to Be Enhanced - 134. Gas Station

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#4868]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [134. Gas Station](https://leetcode.com/problems/gas-station), the maximum value of `n` is 10^4, which is not large enough and a solution with time complexity O(n^2) can still be accepted.
This problem should be designed so that a solution with O(n^2) time complexity won't be accepted. Otherwise, this problem is too easy.
Therefore, I suggest that the maximum value of `n` should be increased to 10^5 (the Constraints part should be updated), and at least one test case that with `n == 10^5` should be added so that the solution with time complexity O(n^2) will get TLE.

#### Code you used for Submit/Run operation

```
class Solution:
    def canCompleteCircuit(self, gas: List[int], cost: List[int]) -> int:
        for start in range(len(gas)):
            fuel = gas[start] - cost[start]
            p = start
            while fuel >= 0:
                p += 1
                if p == len(gas):
                    p = 0
                if p == start:
                    return p
                fuel += gas[p] - cost[p]

        return -1
```

#### Language used for code
Python3

#### Expected behavior
1. In Constraints, the maximum value of `n` should be increased to 10^5.
2. At least one test case that with `n == 10^5` should be added so that the solution with time complexity O(n^2) will get TLE.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/134487287-d14e97ee-2a54-4957-b56f-e39619a9e06b.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@stormsunshine We have increased the constraints for this problem, and we welcome you to submit new test cases! Thank you!
