### ISSUE TITLE
1373. Maximum Sum BST in Binary Tree

### ISSUE THREAD

**Issue by Jesus805** [LeetCode-Feedback/LeetCode-Feedback#487]
#### Your LeetCode username
Jesus805

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
There is no test case for a grandchildren nodes being smaller than grandparent nodes, which makes the root non-BST.
For example: [1,null,10,-5,20]

#### Code you used for Submit/Run operation
This code incorrectly passes when you click Submit
```
class Solution:
    def __init__(self):
        self.max_sum = 0
    
    def maxSumBST(self, root):
        if root is None:
            return 0
        
        self.max_sum = 0
        
        self.doMaxSumBST(root)
        
        return self.max_sum
            
    
    def doMaxSumBST(self, root):
        if not root:
            return True, 0
        
        result_left, left_sum = self.doMaxSumBST(root.left)
        result_right, right_sum = self.doMaxSumBST(root.right)
        tree_sum = root.val
                        
        if result_left and result_right:
            if root.left:
                if root.left.val < root.val:
                    tree_sum += left_sum
                else:
                    return False, 0
        
            if root.right:
                if root.right.val > root.val:
                    tree_sum += right_sum
                else:
                    return False, 0
            
            # Both sub-trees are valid BST
            self.max_sum = max(self.max_sum, tree_sum)
            return True, tree_sum
        
        return False, 0
```
#### Language used for code
Python

#### Expected behavior
My code fails when you "Run" with testcase [1,null,10,-5,20], however this edge case isn't tested when you click "Submit"

**Comment by CooperCooperCooper** [comment]
Hi @Jesus805 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @Jesus805 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
