### ISSUE TITLE
Missing Test Case - 1314. Matrix Block Sum

### ISSUE THREAD

**Issue by RAJASETHI** [LeetCode-Feedback/LeetCode-Feedback#4870]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by RAJASETHI** [comment]
x

**Comment by lc-kay** [comment]
@RAJASETHI Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
