### ISSUE TITLE
1392 missing test case

### ISSUE THREAD

**Issue by dylan-shao** [LeetCode-Feedback/LeetCode-Feedback#4872]
#### Your LeetCode username

leetcode-cn.com/u/shao-em

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

"abcabdddabcaba"

#### Code you used for Submit/Run operation

```
class Solution {
    public String longestPrefix(String s) {
        List<Integer> lpsList = new ArrayList<>();

        int i = 0;
        lpsList.add(0);
        for (int j=1;j < s.length(); j++) {
            if (s.charAt(j) == s.charAt(i)) {
                lpsList.add(i+1);
                i++;
            } else {
                if (i==0) {
                    lpsList.add(0);
                } else {
                    int prevIndex = lpsList.get(i-1);
                    if (s.charAt(prevIndex) == s.charAt(j)) {
                        lpsList.add(prevIndex + 1);
                        i = prevIndex + 1;
                    } else {
                        lpsList.add(0);
                        i = 0;
                    }

                }
            }
        }
        StringBuffer result = new StringBuffer();
        for (int k=0;k<lpsList.get(lpsList.size() - 1);k++) {
            result.append(s.charAt(k));
        }

        return result.toString();
    }
}

```

#### Language used for code

Java

#### Expected behavior

Should return "a", but my code return empty string "", and it passed all current cases

#### Screenshots

<img width="1440" alt="Screen Shot 2021-09-24 at 12 15 40 AM" src="https://user-images.githubusercontent.com/12180221/134545045-9b7f4606-265f-444e-a2bf-e47b907d184c.png">

**Comment by lc-kay** [comment]
Hi @dylan-shao 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@feiceh Please reward the user as we have added the test case. Thank you.

**Comment by feiceh** [comment]
@dylan-shao 你好，当前题目测试用例已更新，ID：shao-em 给予积分奖励，请查收。
