### ISSUE TITLE
355. 设计推特

### ISSUE THREAD

**Issue by lqzo** [LeetCode-Feedback/LeetCode-Feedback#4874]
**你的 LeetCode 用户名**
liqingzhou

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
1. 与英文版对比，题目描述不完善，希望进行补充
2. 测试用例数据结构错误（一条用例被拆成了两条）

**期望行为**
描述你期望的结果

**屏幕截图**
![1632452655400](https://user-images.githubusercontent.com/30641714/134612124-9872bf51-0646-46df-81eb-28137524cb7c.jpg)
![1632452642360](https://user-images.githubusercontent.com/30641714/134612134-fe6c5b03-f5d2-41e8-93ce-02cc7945d917.jpg)

![1632452696831](https://user-images.githubusercontent.com/30641714/134612235-669c68b0-0562-4308-9b24-b0ef7d4da69c.jpg)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lqzo 当前题目描述已更新，ID：liqingzhou 给予积分奖励，请查收。
