### ISSUE TITLE
Missing Test Case - 1239. Maximum Length of a Concatenated String with Unique Characters

### ISSUE THREAD

**Issue by cckao** [LeetCode-Feedback/LeetCode-Feedback#4875]
#### Your LeetCode username
cceimafa

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The accepted submission failed on this test case: ["a","b","dx", "ey", "am", "bn", "abc", "def"].

#### Code you used for Submit/Run operation
This is a sample of the accepted 20 ms submission.

```python
class Solution:
    def maxLength(self, arr: List[str]) -> int:
        def max_len_of_merged_word(words):
            largest, M = 0, len(words)
            for i in range(M):
                alpha1 = set(words[i])
                size = len(words[i])
                for j in range(M):
                    if j == i: continue
                    alpha2 = set(words[j])
                    if alpha1.isdisjoint(alpha2):
                        size += len(words[j])
                        alpha1 = alpha1.union(alpha2)
                if largest < size: largest = size
            return largest

        # select unique words
        N = len(arr)
        unique = [False] * N
        for i in range(N):
            alpha = set(arr[i])
            if len(arr[i]) == len(alpha): unique[i] = True

        # sort(bucket) arr[i] by its length
        tmp = []
        for i in range(27): tmp.append([])
        for i in range(N):
            if unique[i]:
                tmp[len(arr[i])].append(arr[i])
        strs = []
        for i in range(1,27): strs += tmp[i]

        # get maximum length of merged word
        largest = max_len_of_merged_word(strs)
        strs.reverse()
        largest = max(largest, max_len_of_merged_word(strs))

        return largest
```

#### Language used for code
Python3

#### Expected behavior
The accepted submission should succeed on all valid test cases but failed on ["a","b","dx", "ey", "am", "bn", "abc", "def"].

**Comment by lc-kay** [comment]
Hi @cckao 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cckao 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
