### ISSUE TITLE
Missing Test Case - 112. Path Sum

### ISSUE THREAD

**Issue by bsbsrkg** [LeetCode-Feedback/LeetCode-Feedback#4876]
The TC reports issue, even the answer is correct
#### Your LeetCode username

bsbsrkg

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Submission Result: Wrong Answer 
Input:
[1,2]
1
Output:
true
Expected:
false

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool process(TreeNode* node, int targetSum, int &sum, vector<int>&path)
    {
        if (!node)
            return false;
        sum+=node->val;
        cout << sum << '\n';
        if (sum == targetSum)
            return true;
        
        if (sum > targetSum)
        {
            sum -= node->val;
            return false;
        }
         
        else
        {
            if (!node->left && !node->right)
            {
                sum -= node->val;
                return false;
            }
            
           if(process(node->left, targetSum, sum, path))
               return true;
            if(process(node->right, targetSum, sum, path))
                return true;
        }
        sum -= node->val;
        return false;

        
    }
    bool hasPathSum(TreeNode* root, int targetSum) {
        vector <int> path;
        int sum = 0;
        if(!root)
            return false;
        return process(root, targetSum, sum, path);
    }
};
```

#### Expected behavior

There exist a path with given sum, but the test is expecting some other value

#### Additional context

It would be good to see, what the test case internals

**Comment by lc-kay** [comment]
@bsbsrkg The expected output is correct. Please check out the following posts for further clarification. 

- https://leetcode.com/problems/path-sum/discuss/36570/Input%3A-12-1-expected-true-or-false
- https://leetcode.com/problems/path-sum/discuss/36601/What-does-input-12-1-mean
- https://leetcode.com/problems/path-sum/discuss/259936/Why-input-12-1-return-false-It-should-be-true-right
- https://leetcode.com/problems/path-sum/discuss/134257/Unclear-test-case12-1-and-1-1

Thank you for your time.
