### ISSUE TITLE
Missing Test Case - 219. Contains Duplicate II

### ISSUE THREAD

**Issue by mehrdod** [LeetCode-Feedback/LeetCode-Feedback#4877]
#### Your LeetCode username

mondayguy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing testcase:
[-1000000000,2,3,1000000000]
3

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool containsNearbyDuplicate(vector<int>& nums, int k) {
        int n=nums.size();
        int max=*max_element(nums.begin(), nums.end());
        int min=*min_element(nums.begin(), nums.end());

        vector<int> temp(max-min+1);
        
        for (int i=0; i<n; i++) {
            if(temp[nums[i]-min]>0 && i-temp[nums[i]-min]+1 <=k) 
                return true;
            else
                temp[nums[i]-min]=i+1;  
        }
        return false;
    }
};
```

#### Expected behavior

Memory Limit Exceeded in this test case, but this code passed all the tests

**Comment by lc-kay** [comment]
Hi @mehrdod 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mehrdod 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
