### ISSUE TITLE
Missing Test Case - 463. Island Perimeter

### ISSUE THREAD

**Issue by KartikeyRohila** [LeetCode-Feedback/LeetCode-Feedback#4878]
#### Your LeetCode username
Kartikey_1109

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My code accepted for test case : [[0,1,0,0],[1,0,1,0],[0,1,0,0],[1,1,0,0]]
Leetcode show that the excepted output for this is 4 but its correct answer is 8.
In discussion lots of people submit a code which was accepted according to them but when I run that code for this test case it fails.

#### Code you used for Submit/Run operation

```
class Solution
{
    public:
    bool isvalid(int i, int j, vector<vector<int>>& grid)
    {
        if(i < grid.size() and j < grid[0].size()) return true;
        return false;
    }
    
    int dfs_perimeter(vector<vector<int>>& grid, int i, int j)
    {
        int perimeter = 0;
        
        grid[i][j] = 2; 
        
        if(isvalid(i + 1, j, grid)){
            if(grid[i + 1][j] == 0) perimeter++; 
            else if(grid[i + 1][j] != 2) perimeter += dfs_perimeter(grid, i + 1, j);
        } else perimeter++;
        
        if(isvalid(i - 1, j, grid)){
            if(grid[i - 1][j] == 0) perimeter++;
            else if(grid[i - 1][j] != 2) perimeter += dfs_perimeter(grid, i - 1, j);
        } else perimeter++;

        
        if(isvalid(i, j + 1, grid)){
            if(grid[i][j + 1] == 0) perimeter++;
            else if(grid[i][j + 1] != 2) perimeter += dfs_perimeter(grid, i, j + 1);
        } else perimeter++;
        

        if(isvalid(i, j - 1, grid)){
            if(grid[i][j - 1] == 0) perimeter++;
            else if(grid[i][j - 1] != 2) perimeter += dfs_perimeter(grid, i, j - 1);
        } else perimeter++;

        return perimeter;
    }
    
    int islandPerimeter(vector<vector<int>>& grid)
    {
        if(!grid.size() or !grid[0].size()) return 0;
        for(int i = 0; i < grid.size(); i++)
        {
            for(int j = 0; j < grid[0].size(); j++)
            {
                if(grid[i][j]) return dfs_perimeter(grid, i, j);
            }
        }
        return 44;
    }
};

```

#### Language used for code
C++

#### Expected behavior
Expected answer should be 8 for this test case.

**Comment by zhouyixin829** [comment]
There is no lake in island

**Comment by lc-kay** [comment]
@KartikeyRohila The test case you provided returned invalid test case error: expected 'Number of islands' to have value in [1] only. If you do not see the same, please provide a screenshot of the behavior on your end. Thank you!

**Comment by KartikeyRohila** [comment]
> @KartikeyRohila The test case you provided returned invalid test case error: expected 'Number of islands' to have value in [1] only. If you do not see the same, please provide a screenshot of the behavior on your end. Thank you!

Now it shows that test case is invalid. But when I submitted my code I get wrong answer on this test case. There is also one more test case where my 1st code gave me error and and now when I run my code on that test case it shows invalid test case. I think they solved the wrong test case problem.

Here is the screenshot of that test case.

![Screenshot (229)](https://user-images.githubusercontent.com/69873345/135139106-fe1df5eb-80c3-460a-879d-bcd1ff84f31e.png)

**Comment by lc-kay** [comment]
@zhouyixin829 The code you provided is now accepted and the test case in the screenshot also receives invalid test case error. Thank you for your time!
