### ISSUE TITLE
面试题 17.13. 恢复空格【程序员面试金典】

### ISSUE THREAD

**Issue by LiangJunrong** [LeetCode-Feedback/LeetCode-Feedback#488]
** Bug 类型**
- [ ] 面试题 17.13. 恢复空格
- [ ] https://leetcode-cn.com/problems/re-space-lcci/solution/mian-shi-ti-1713-hui-fu-kong-ge-js-zheng-ze-by-jsl/
- [ ] JavaScript

**描述**
使用 JavaScript 的正则表达式进行判断的时候，本地输出的是 5（和答案的一样），但是线上输出的是 3（报错）。

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
const respace = (dictionary, sentence) => {
  dictionary.sort((a, b) => b.length - a.length); // 由大到小进行排序
  for (let i = 0; i < dictionary.length; i++) {
    sentence = sentence.replace(new RegExp(dictionary[i], 'g'), '');
  }
  return sentence.length;
};
```

**期望行为**
返回 5

**屏幕截图**
![image](https://user-images.githubusercontent.com/22924993/84728352-9dd9c680-afc3-11ea-88d2-32e43c65a873.png)
![image](https://user-images.githubusercontent.com/22924993/84728534-0a54c580-afc4-11ea-82e5-a23ffd13beb4.png)
![image](https://user-images.githubusercontent.com/22924993/84728760-97981a00-afc4-11ea-92b6-a11f0593d9e5.png)

**额外的上下文**
没有额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，建议再仔细调试一下代码（代码是错的）。本地和力扣站结果不一样可能是运行环境不同。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路。

**Comment by cander0815** [comment]
> 感谢反馈，建议再仔细调试一下代码（代码是错误的。）。本地和力扣站结果不一样可能是运行环境不同。后续刷题学习中遇到困难，可通过阅读“题解”解决做题中的一些奇迹，看看其他小伙伴的解题思路。

你好, 不太明白哪里错误了, 请问可以详细说明下吗? 我的理解从最长的单词开始匹配, 那么就不会出现字典中有单词漏匹配的情况. 把字符串中通过正则匹配字符, 匹配到的就删除掉, 那么删除到最后就是不可匹配的字符.

**Comment by tinylife** [comment]
你好，我给你提供个测试例子，假如sentence="abcd"，dict=["abc","ab","cd"]，如果从最长匹配到的删掉，剩一个d，字典中没有，但是实际上字典中的ab和cd是可以完全匹配的上的，简单匹配长的或匹配短的都是有局限的，在此基础上改动的话要使用回溯，我们尽可能完成匹配，虽然实际上有些没法匹配，但是我们当成匹配是可以完成的，在此过程中，我们统计剩余的字符长度，最后留下最短的。
