### ISSUE TITLE
Missing Test Case - 372. Super Pow

### ISSUE THREAD

**Issue by Daniel-WR-Hart** [LeetCode-Feedback/LeetCode-Feedback#4880]
#### LeetCode username
omgitsmiketyson

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

To simplify the exponent ```b```, I need to find a number ```n``` such that ```1 == (a ** n) % 1337``` but depending on what ```a``` is, the way that I calculate the cycle length ```n``` may be a bit different. i.e. the cycle may or may not include ```a % 1337``` itself.
My code below was an accepted submission, but it fails this:
```
2
[2,8,4]
```

#### Code you used for Submit/Run operation
```
// 372. Super Pow
var superPow = function(a, b) {
    if (a === 1)
        return 1;
    
    const initialA = a % 1337;
    
    const repeats = new Set();
    while (!repeats.has(a)) {
        repeats.add(a);
        a = (a * initialA) % 1337;
    }
    
    // "a" itself shouldn't be a part of the repeating sequence, so subtract the set size by 1 to exclude it
    // This is what I had when my submission was accepted
    b = BigInt(b.join('')) % BigInt(repeats.size - 1);
    // This is what is actually required when "a" is 2 and b was 284 or larger
    // b = BigInt(b.join('')) % BigInt(repeats.size);
    
    // console.log('period:', repeats.size - 1, 'initialA:', initialA, 'b:', b);
    
    return (BigInt(initialA) ** b) % 1337n;
};
```

#### Language used for code
JavaScript

#### Expected behavior
It's easy to test my code with this test case to see that the answer is wrong:
```
2
[2,8,4]
```

**Comment by Daniel-WR-Hart** [comment]
This updated solution with helpful logging will better illustrate the point I was trying to make. ```a = 2``` has cycle that includes ```a```, but ```a = 78267``` has a cycle that excludes ```(a % 1337)```
```
var superPow = function(a, b) {
    if (a === 1)
        return 1;
    
    const initialA = a % 1337;
    
    const repeats = new Map();
    let cycleIndexStart;
    for (let i = 0; ; i++) {
        console.log(a);
        repeats.set(a, i);
        a = (a * initialA) % 1337;
        
        if (repeats.has(a)) {
            console.log(a, 'was repeated at index', repeats.get(a));
            cycleIndexStart = repeats.get(a);
            break;
        }
    }
    
    // "a" itself shouldn't be a part of the repeating sequence, so subtract the set size by 1 to exclude it
    const cycleLength = repeats.size - cycleIndexStart;
    
    b = BigInt(b.join('')) % BigInt(cycleLength);
    
    // console.log('cycleLength:', cycleLength, 'initialA:', initialA, 'b:', b);
    
    return (BigInt(initialA) ** b) % 1337n;
};
```

**Comment by lc-kay** [comment]
Hi @Daniel-WR-Hart 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Daniel-WR-Hart 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
