### ISSUE TITLE
Language bug for all problems

### ISSUE THREAD

**Issue by chunzhengyang** [LeetCode-Feedback/LeetCode-Feedback#4883]
#### Your LeetCode username

chunzhengyang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I set _maps[0][0][1] = 1_ in _func()_ , _maps[0][0][1]_ does not changed at all outside the function, which happens in all problems.
However, I tested this code on VS2021 and it worked properly.
#### Code you used for Submit/Run operation

```
// Two Sum
int* twoSum(int* nums, int numsSize, int target, int* returnSize){
    test();
    return NULL;
}

void func(int*** maps) {
    maps[0] = calloc(0x100, sizeof(int*));
    maps[0][0] = calloc(0x100, sizeof(int));
    maps[0][0][1] = 1;
}

void test() {
    int*** maps[1] = {0};
    func(maps);
    printf("%d", maps[0][0][1]);  //print 0
}
```

#### Language used for code

C

#### Screenshots

![Untitled](https://user-images.githubusercontent.com/47287076/134712863-22f79a79-2ef0-4c58-9da1-6d7b46173a67.png)

**Comment by lc-kay** [comment]
@chunzhengyang Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have ran into the same issue and resolved it. Also, please check out the environments that we support https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.
