### ISSUE TITLE
Missing Test Case - 408. Valid Word Abbreviation

### ISSUE THREAD

**Issue by karlsabo** [LeetCode-Feedback/LeetCode-Feedback#4884]
#### Your LeetCode username
karlsabo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The description for the problem says ""s010n" (leading zeros in numbers are allowed)". However, there's a test with input "a" "01" that says it should return false. If you test the top Java solutions, they will fail with `test05` pasted below but pass the `test04` because all the solutions don't allow leading zeros.

```java
@Test public void test04() {
    assertFalse(new Solution().validWordAbbreviation("a", "01"));
}

@Test public void test05(){
   assertTrue(new Solution().validWordAbbreviation( "substitution", "s010n"));
}
```

#### Code you used for Submit/Run operation
```java
class Solution {
      public boolean validWordAbbreviation(String word, String abbr) {
         int skip = 0;
         int wordIndex = 0;
         int abbrIndex;
         for (abbrIndex = 0; wordIndex < word.length() && abbrIndex < abbr.length(); abbrIndex++) {
            final char currentChar = abbr.charAt(abbrIndex);
            if (Character.isDigit(currentChar)) {
               skip = skip * 10 + (currentChar - '0');
            } else {
               wordIndex += skip;
               skip = 0;
               if (word.charAt(wordIndex) != currentChar) {
                  return false;
               }
               wordIndex++;
            }
         }

         wordIndex += skip;


         return wordIndex == (word.length()) && abbrIndex == abbr.length();
      }
   }
```
#### Language used for code
Java

#### Expected behavior
Either the description should say leading zeros are not valid or the "a" "01" test should be changed to expect `true`.

#### Screenshots
N/A

#### Additional context
N/A

**Comment by lc-kay** [comment]
@karlsabo We've updated the problem and added a clarification for leading zeros yesterday. Please check it out!
