### ISSUE TITLE
Employee Importance problem issue (Prob. 690 / Easy)

### ISSUE THREAD

**Issue by yannbms** [LeetCode-Feedback/LeetCode-Feedback#4885]
The problem is not clear (the examples and figures are not clear either) as to whether the total importance of an employee takes into account only the DIRECT subordinates, or all subordinates (sub-subordinates, sub-sub-subordinates, etc ...). 

Thanks to clarify it for other leetcode users ;-)

**Comment by lc-kay** [comment]
@yannbms 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yannbms 
Thank you for your time. We've updated the problem. We appreciate your support!
