### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by abdurauf01** [LeetCode-Feedback/LeetCode-Feedback#4888]
####abdurauf01

- [x] Solution

#### Code you used for Submit/Run operation

``` Isomorphic Strings
static boolean isIsomorphic(String s, String t) {
        if(s.length() != t.length()) return  false;
        int[] s1 = new int[256];
        int[] s2 = new int[256];

        for(int i = 0; i < s.length(); i++) {
            if(s1[s.charAt(i)] != s2[t.charAt(i)]) return  false;
            s1[s.charAt(i)] = s2[t.charAt(i)] = i + 1;
        }
        return true;
    }
```

**Comment by lc-kay** [comment]
@abdurauf01 Please feel free to share your code in the problem discuss section! 

We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
