### ISSUE TITLE
380. Insert Delete GetRandom O(1) - New Testcase Suggestion

### ISSUE THREAD

**Issue by milanpanchal** [LeetCode-Feedback/LeetCode-Feedback#489]
#### Your LeetCode username
milanpanchal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Test Case

#### Description of the bug

It's not handing one of the following scenario: 

- Initialize the **RandomizedSet** class
- Call the **getRandom** function immediately which is an empty object.

The following code passed all the test cases. 
But if the new test case as below will be added It fails.

**Test Case:**
```ruby
["RandomizedSet","getRandom", "insert","remove","insert","getRandom","remove","insert","getRandom"]
[[],[],[1],[2],[2],[],[1],[2],[]]
```

#### Code you used for Submit/Run operation

```swift
class RandomizedSet {
    var hashMap:[Int:Bool]
    
    /** Initialize your data structure here. */
    init() {
        hashMap = [:]
    }
    
    /** Inserts a value to the set. Returns true if the set did not already contain the specified element. */
    func insert(_ val: Int) -> Bool {
        if hashMap[val] == nil {
            hashMap[val] = true
            return true
        }
        return false
    }
    
    /** Removes a value from the set. Returns true if the set contained the specified element. */
    func remove(_ val: Int) -> Bool {
        if hashMap[val] != nil {
            hashMap[val] = nil
            return true
        }
        return false
    }
    
    /** Get a random element from the set. */
    func getRandom() -> Int {
        // return hashMap.keys.randomElement() ?? 0
        return hashMap.keys.randomElement()!
    }
}

/**
 * Your RandomizedSet object will be instantiated and called as such:
 * let obj = RandomizedSet()
 * let ret_1: Int = obj.getRandom()
 * let ret_2: Bool = obj.insert(val)
 * let ret_3: Bool = obj.remove(val)
 * let ret_4: Int = obj.getRandom()
 */
```

#### Language used for code
Swift 5

**Comment by CooperCooperCooper** [comment]
Hi @milanpanchal ,
Thank you for reaching out to us. Would you please share with us what it looks like when you Run Code with this code and the test case mentioned? I tried them and got a "Runtime Error" on your code and test case (please see this result in
<img width="1428" alt="Screen Shot 2020-06-16 at 9 21 39 PM" src="https://user-images.githubusercontent.com/59751300/84854869-917f5900-b017-11ea-8787-f2904ff42e0b.png">
 the screenshot attached).

**Comment by milanpanchal** [comment]
Yes. My code passed all test cases right now. But If I included the mentioned testcase then It gives me a **Runtime error**. Because I was trying to access the ** randomElement()**  function on an empty list.

So we should have one testcase to verify that scenario.

**Comment by CooperCooperCooper** [comment]
Hi @milanpanchal ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @milanpanchal ,
Thank you for your time. We've found the issue is not because the test case is not covered; to solve this issue we've added clarification on the statement and added validator in the back, so now the test case is actually invalid. Please test it out on your end. Thanks.

**Comment by milanpanchal** [comment]
Thanks for adding clarification message.
