### ISSUE TITLE
Faulty question description - 355. Design Twitter

### ISSUE THREAD

**Issue by maverickreal** [LeetCode-Feedback/LeetCode-Feedback#4890]
https://leetcode.com/maverick09/

#### Category of the bug
- [ ] Question

#### Description of the bug
The code preset in the editor for class definition of the problem is incorrect. The class has a method ```getNewsFeed()``` which is supposed to actually return a ```vector<int>``` but in the class definition provided, method's return type is ```vector<string>```.

#### Language used for code
C++

#### Expected behavior
The return type of the method ```getNewsFeed()```in class ```Twitter``` should have a return type of ```vector<int>``` mentioned in the class definition and not ```vector<string>```.

#### Screenshots
The default class definition in the code editor: 
![Screenshot from 2021-09-25 15-00-40](https://user-images.githubusercontent.com/57585749/134766972-2a5db107-fbd0-4ddd-90ee-170a36032b9c.png)
the accepted solution:

![Screenshot from 2021-09-25 15-15-56](https://user-images.githubusercontent.com/57585749/134767073-fcf53775-2254-4f92-a794-88abb56bd0fa.png)

**Comment by lc-kay** [comment]
Hi @maverickreal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @maverickreal 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
