### ISSUE TITLE
Missing Test Case - 1293. Shortest Path in a Grid with Obstacles Elimination

### ISSUE THREAD

**Issue by billafy** [LeetCode-Feedback/LeetCode-Feedback#4892]
#### Your LeetCode username

ytarkar138

#### Category of the bug
- [Shortest Path in a Grid with Obstacles Elimination ] Question
- [ ] Solution
- [C++] Language
- [ ] Missing Test Cases 

#### Description of the bug

A custom test case which I randomly tried is failing for the question but my solution is being accepted. There is a missing test case. This is the test case : 
[[0,0,0],[1,1,0],[0,0,0],[0,1,1],[0,0,0],[0,0,0],[0,1,1],[0,0,0],[0,0,0],[0,1,1],[0,0,0],[0,0,0],[0,1,1],[0,0,0],[0,0,0],[0,1,1],[0,0,0],[0,0,0],[0,1,1],[0,0,0],[0,0,0],[0,1,1],[0,0,0],[0,0,0],[0,1,1],[0,0,0],[0,0,0],[0,1,1],[0,0,0]]
1

#### Code you used for Submit/Run operation

```
// Shortest Path in a Grid with Obstacles Elimination
class Solution {
public:
    int recurse(vector<vector<int>>& grid, int i, int j, int o, vector<vector<bool>> visited, vector<vector<int>>& mem) {
        if(i == 0 && j == 0) 
            return 0;
        if(mem[i][j] != -1)
            return mem[i][j];
        visited[i][j] = true;
        int steps = INT_MAX - 1600;
        for(int x = -1; x <= 1; ++x) {
            for(int y = -1; y <= 1; ++y) {
                if(abs(x) == abs(y)) 
                    continue;
                if(i + x > -1 && i + x < grid.size() && j + y > -1 && j + y < grid[0].size() && !visited[i + x][j + y]) {
                    if(grid[i + x][j + y]) {
                        if(o > 0) 
                            steps = min(steps, 1 + recurse(grid, i + x, j + y, o - 1, visited, mem));
                    } 
                    else 
                        steps = min(steps, 1 + recurse(grid, i + x, j + y, o, visited, mem));
                }
            }
        }
        mem[i][j] = steps;
        return steps;
    }
    int shortestPath(vector<vector<int>>& grid, int k) {
        int m = grid.size(), n = grid[0].size();
        vector<vector<int>> mem(m, vector<int>(n, -1));
        vector<vector<bool>> visited(m, vector<bool>(n));
        int res = recurse(grid, m - 1, n - 1, k, visited, mem);
        if(res == INT_MAX - 1600) 
            return -1;
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior

My solution should be rejected but it is being accepted.

**Comment by lc-kay** [comment]
Hi @billafy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @billafy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
