### ISSUE TITLE
139. Word Break - adding visited nodes in "Approach 3: Using Breadth-First-Search" could be performed on higher level

### ISSUE THREAD

**Issue by ashimko** [LeetCode-Feedback/LeetCode-Feedback#4896]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In solution "Approach 3: Using Breadth-First-Search" 

```visited.add(start)``` could be performed on level while loop. It reduce amount of operations.

#### Code you used for Submit/Run operation

```
def wordBreak(self, s: str, wordDict: List[str]) -> bool:
        word_set = set(wordDict)
        q = deque()
        visited = set()

        q.append(0)
        while q:
            start = q.popleft()
            if start in visited:
                continue
            for end in range(start + 1, len(s) + 1):
                if s[start:end] in word_set:
                    q.append(end)
                    if end == len(s):
                        return True
            <---visited.add(start)
        return False
```

#### Language used for code

python 3

**Comment by lc-kay** [comment]
Hi @ashimko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ashimko,
Thank you for your feedback. The problem has been updated. We appreciate your support!
