### ISSUE TITLE
not run my code in correct answer- 344. Reverse String

### ISSUE THREAD

**Issue by VivianGuoGuo** [LeetCode-Feedback/LeetCode-Feedback#4897]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by VivianGuoGuo** [comment]
this is my code var reverseString = function(s) {
    
    let count="";
    for (let i=s.length-1;i>=0;i--){
        count+=s[i];
    }
    return count;

};

should run in reverse order but keep giving me the opposite order 
![1632596600245](https://user-images.githubusercontent.com/47832438/134783329-8e5fe62a-c127-4e3d-8b35-cb7ca9aa7f5d.jpg)

**Comment by lc-kay** [comment]
@VivianGuoGuo Unfortunately, we do not offer debugging support. The best place to raise this issue is the problem discuss page. Please check out this accepted JS solution for reference! https://leetcode.com/problems/reverse-string/discuss/1059653/Javascript Thank you for your time.
