### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by ljatca** [LeetCode-Feedback/LeetCode-Feedback#4898]
#### Your LeetCode username

ljinuw

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

There are missing test cases to catch "anagram" and "aaangrm". As long as two strings have the same number of letters the tests will pass, even thought they are not the anagram of each other.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public boolean isAnagram(String s, String t) {
        
        if(s.length() != t.length()) return false;
        
        int[] letters = new int[256];
        
        for(char c : s.toCharArray()){
            letters[c]++;
        }
        for(char c :t.toCharArray()){
            letters[c]--;
        }
        for(int i : letters){
            if(i != 0) return false;
        }
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

We should add test cases to check if inputs are "anagram" and "aaangrm", the code should return false.

#### Screenshots

<img width="614" alt="Screen Shot 2021-09-25 at 3 03 59 PM" src="https://user-images.githubusercontent.com/44687783/134783361-286a4b93-9e9c-4883-b244-8dce148129c8.png">

**Comment by lc-kay** [comment]
@ljatca For a valid missing test case report, please provide an AC solution that the custom test case will fail. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @ljatca 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
