### ISSUE TITLE
Wrong test case - 463. Island Perimeter

### ISSUE THREAD

**Issue by zhouyixin829** [LeetCode-Feedback/LeetCode-Feedback#4899]
#### Your LeetCode username

ethanzhou829

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1] Missing Test Cases 

#### Description of the bug

The test case contains [[1],[1],[1],[0],[1],[1]].
However, the constraint is "there is exactly one island".
There are 2 islands in the test case.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Jasonlee1995** [comment]
I add code submit/run operation for more details

I found this case using the below codes (zero-pad and find)

Also checked other codes from *'discuss'* section and it also didn't work.

```
# zero-pad and find
class Solution:
    def islandPerimeter(self, grid):
        for i in range(len(grid)): grid[i] = [0] + grid[i] + [0]
        grid = [[0] * len(grid[0])] + grid + [[0] * len(grid[0])]
        answer = 0
        for i in range(len(grid)-1):
            for j in range(len(grid[i])-1):
                if (grid[i][j], grid[i][j+1]) in [(0, 1), (1, 0)]: answer += 1
                if (grid[i][j], grid[i+1][j]) in [(0, 1), (1, 0)]: answer += 1
        return answer
```
```
# code from discuss
class Solution:
    def islandPerimeter(self, grid):
        M, N, p = len(grid), len(grid[0]), 0
        for m in range(M):
            for n in range(N):
                if grid[m][n] == 1:
                    if m == 0   or grid[m-1][n] == 0: p += 1
                    if n == 0   or grid[m][n-1] == 0: p += 1
                    if n == N-1 or grid[m][n+1] == 0: p += 1
                    if m == M-1 or grid[m+1][n] == 0: p += 1
        return p
```
![image](https://user-images.githubusercontent.com/49643709/134799278-d9caa400-84d2-4a5c-99d8-bf6011ee090d.png)

Weird test case neglecting the statement of *'there is exactly one island'*

**Comment by lc-kay** [comment]
@zhouyixin829 It appears that we have fixed this bug! This test case now returns invalid test case error. Thank you for your time!
