### ISSUE TITLE
Problem 188 judge has a bug

### ISSUE THREAD

**Issue by NightMachinary** [LeetCode-Feedback/LeetCode-Feedback#49]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
The judge reports a runtime error without specifying what error has happened, and in fact, there should have been no errors:
![image](https://user-images.githubusercontent.com/36224762/76982162-be589d00-6950-11ea-86bc-028d184b3d59.png)

**what language is your code written in**
Rust

**The code you submit/run**
```
impl Solution {
    pub fn max_profit(k: i32, prices: Vec<i32>) -> i32 {
        let k = k as usize;
        use std::cmp::*;

        if prices.len() < 2 || k <= 0{
            return 0;
        }

        let mut hold = vec![std::i32::MIN; k + 1];
        let mut cash = vec![0; k + 1];
        hold[1] = -prices[0];
        let mut ix: usize = 1;
        for i in &prices[1..] {
            for j in 1..(min(ix, k) + 1) {
                // let cashp = if j == 0 { 0 } else { cash[j - 1] };
                cash[j] = max(max(cash[j - 1], cash[j]), hold[j] + *i);
                hold[j] = max(max(hold[j - 1], hold[j]), cash[j-1] - *i);
            }


            ix += 1;
        }

        return cash.iter().fold(0, |a, i: &i32| max(a, *i));
    }

}
```

**Expected behavior**
Running the same testcase through cargo with opt-level 3 and overflow checks set to true returns the correct answer `1648961`:

![image](https://user-images.githubusercontent.com/36224762/76982371-08da1980-6951-11ea-82b6-1fe091acd409.png)

It is noteworthy that just adding 

```
       if k == 1000000000
        {
            return 1648961;
        }
```

to the start of the function will cause it to pass all testcases.

**Comment by CooperCooperCooper** [comment]
Hi @NightMachinary,
Thank you for raising this issue to our attention! I've relayed it to our engineers to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @NightMachinary,
Thank you for your time. Our engineers took a thorough look at the issue and found the error to stem from your code allocated too much memory. Please try to further optimize this code. 
We appreciate your support and understanding. If you have any other questions, please don't hesitate to let us know.

**Comment by NightMachinary** [comment]
@CooperCooperCooper Thanks! I think the site should have a specific “out of memory” error so that people know what causes the problem. The other leetcode style sites I’ve used do tell you if you’re out of time or memory.

**Comment by CooperCooperCooper** [comment]
Hi @NightMachinary, 
Good point! I've relayed your suggestion to our team to consider. But since this is outside of the content-issue scope, we will close this ticket. If you're curious about the investigation progress, please reach out to our support team here: https://support.leetcode.com/hc/en-us. We appreciate your support and understand.
