### ISSUE TITLE
Non-optimal Solution - 219. Contains Duplicate II

### ISSUE THREAD

**Issue by kai-wei-mo** [LeetCode-Feedback/LeetCode-Feedback#4901]
#### Your LeetCode username
xu-gillian

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Solution 3 (Hash Table) has a line of redundant code.

#### Code you used for Submit/Run operation
```
const abs = (n) => {
    if (n >= 0) {
        return n;
    }
    
    return -n;
}

var containsNearbyDuplicate = function(nums, k) {
    // sliding window using a Set
    
    const set = new Set();
    
    for (let i = 0; i < nums.length; i++) {
        const num = nums[i];
        if (set.has(num)) {
            return true;
        }
        
        set.add(num);
        set.delete(nums[i - k]);
    }
    
    return false;
};
```

#### Language used for code
JavaScript

#### Expected behavior
The provided solution contains a redundant line of code, and it can be removed while maintaining the integrity and overarching concepts of the solution (line 6 of screenshot).

#### Screenshots
![image](https://user-images.githubusercontent.com/66972679/134788409-ab02c645-6e4c-4424-b515-d9ba96ac2d69.png)

**Comment by lc-kay** [comment]
Hi @kai-wei-mo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kai-wei-mo,
Thank you for your time. We did not update the solution because different languages handle negative indices differently and Not all languages can use the suggestion offered.
