### ISSUE TITLE
Different result for same Test case - 139. Word Break

### ISSUE THREAD

**Issue by progressivePRV** [LeetCode-Feedback/LeetCode-Feedback#4902]
#### Your LeetCode username

ProgressivePrabhav

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Different Result for same test case 

#### Description of the bug

On "Submit" the code fails on test case number 42.  Whereas while running the same test case by putting under Test Case in Console and using "Run Code", the result will be a pass.

#### Code used for Submit and Run operation

```
// Two Sum
class Solution:
    def wordBreak(self, s: str, wordDict: List[str],memo={}) -> bool:
        if s == "":
            return True
        for i in wordDict:
            L = len(i)
            if s[:L]==i:
                new_s = s[L:]
                try:
                    return memo[new_s]
                except:
                    t = self.wordBreak(new_s,wordDict,memo)
                    if t:
                        return True
                    memo[new_s] = t
        return False
```

#### Language used for code

Python3

#### Expected behavior

Test Case should pass while submitting as well.

#### Screenshots

![image](https://user-images.githubusercontent.com/31888813/134789458-c8de1c0b-a090-4dd1-96a4-f515045614bb.png)

**Comment by lc-kay** [comment]
Hi @progressivePRV 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by progressivePRV** [comment]
Thank You, Understood
