### ISSUE TITLE
Missing Test Cases - 1610. Maximum Number of Visible Points

### ISSUE THREAD

**Issue by cyclotomic2** [LeetCode-Feedback/LeetCode-Feedback#4903]
#### Your LeetCode username

spicynoodle

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The test cases in the problem [1610. Maximum Number of Visible Points](https://leetcode.com/problems/maximum-number-of-visible-points/) can be improved. Specifically, certain solutions that were accepted fail on some test cases.

The solution in the next section is such an example. The issue occurs when two points lie exactly on the two boarders of the field of view: as angles are approximated by float numbers, the algorithm might decide that the angle between the two points is slightly greater than the input `angle`, while they are actually equal. This causes the algorithm to count less number of points in the field of view than there actually can be. I share 4 test cases which would trigger this bug (each test case takes 3 lines):
```
[[13,12],[1,25]]
45
[0,0]
[[20,11],[9,31]]
45
[0,0]
[[27,26],[0,1]]
90
[26,0]
[[52,42],[0,10]]
90
[42,0]
```

#### Code you used for Submit/Run operation

```Python3
# 1610. Maximum Number of Visible Points
class Solution:
    def visiblePoints(self, points: List[List[int]], angle: int, location: List[int]) -> int:
        arr, extra = [], 0
        xx, yy = location
        for x, y in points:
            if x == xx and y == yy:
                extra += 1
                continue
            arr.append(math.atan2(y - yy, x - xx))
        
        arr.sort()
        arr = arr + [x + 2.0 * math.pi for x in arr]
        angle = math.pi * angle / 180
        
        l = ans = 0
        for r in range(len(arr)):
            while arr[r] - arr[l] > angle:
                l += 1
            ans = max(ans, r - l + 1)
            
        return ans + extra
```

#### Language used for code

Python3

#### Expected behavior

The submitted code should be rejected.

#### Screenshots

![image](https://user-images.githubusercontent.com/15987258/134787939-85cb982c-fa30-4fda-bcf9-59452c7ec15f.png)
The solution was accepted (the red circle on the left) but fails when we test it on some test cases (the red circle on the right).

#### Additional context

The code provided is found in [this problem discussion](https://leetcode.com/problems/maximum-number-of-visible-points/discuss/877822/Python-clean-sliding-window-solution-with-explanation).

**Comment by lc-kay** [comment]
Hi @cyclotomic2 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@cyclotomic2 Our team has reviewed your report. Although those are valid test cases, we will not be adding them because they are edge cases and they will frustrate our users. They target precision error in a built-in function. The idea behind the provided solutions is still correct. Thank you for your understanding.
