### ISSUE TITLE
Missing Test Cases - 371. Sum of Two Integers

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#4904]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Certain solutions that get accepted fail on several test cases. When one of `a` and `b` is negative and the other is zero, the following codes get wrong answer, but the codes can still get accepted. Obviously, such test cases are missing.

#### Code you used for Submit/Run operation
There are two pieces of code as follows.
```
MASK1 = 4294967296  # 2^32
MASK2 = 2147483648  # 2^31
MASK3 = 2147483647  # 2^31-1

class Solution:
    def getSum(self, a: int, b: int) -> int:
        while b != 0:
            carry = ((a & b) << 1) % MASK1
            a = (a ^ b) % MASK1
            b = carry
        if a & MASK2:
            return ~((a ^ MASK2) ^ MASK3)
        else:
            return a
```
```
MASK1 = 4294967296  # 2^32
MASK2 = 2147483648  # 2^31
MASK3 = 2147483647  # 2^31-1

class Solution:
    def getSum(self, a: int, b: int) -> int:
        while a != 0:
            carry = ((a & b) << 1) % MASK1
            b = (a ^ b) % MASK1
            a = carry
        if b & MASK2:
            return ~((b ^ MASK2) ^ MASK3)
        else:
            return b
```

#### Language used for code
Python3

#### Expected behavior
One or more test cases should be added so that the code above will get wrong answer when submitted.
The test cases that need to be added are under the two scenarios:
The first scenario is that `a < 0` and `b == 0`.
The second scenario is that `a == 0` and `b < 0`.
Some example test cases are listed as follows. Please consider how many test cases should be added.
For the first scenario, the following test cases can be added.
```
-1
0
```
```
-2
0
```
```
-3
0
```
```
-4
0
```
...
```
-999
0
```
```
-1000
0
```
For the second scenario, the following test cases can be added.
```
0
-1
```
```
0
-2
```
```
0
-3
```
```
0
-4
```
...
```
0
-999
```
```
0
-1000
```

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
