### ISSUE TITLE
Wrong Documentation - 383. Ransom Note

### ISSUE THREAD

**Issue by santosh2702** [LeetCode-Feedback/LeetCode-Feedback#4906]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@santosh2702 Please provide more details on your wrong documentation report. After more information is provided, I will reopen this ticket. Thank you for your time.
