### ISSUE TITLE
Wrong Test Case - 36. Valid Sudoku

### ISSUE THREAD

**Issue by Yitzhakpro** [LeetCode-Feedback/LeetCode-Feedback#4907]
#### Your LeetCode username
Yitzhakpro

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Wrong Test Cases 

#### Description of the bug
one of the test cases is:
```py
board = [
        [".","4",".",".",".",".",".",".","."],
        [".",".","4",".",".",".",".",".","."],
        [".",".",".","1",".",".","7",".","."],
        [".",".",".",".",".",".",".",".","."],
        [".",".",".","3",".",".",".","6","."],
        [".",".",".",".",".","6",".","9","."],
        [".",".",".",".","1",".",".",".","."],
        [".",".",".",".",".",".","2",".","."],
        [".",".",".","8",".",".",".",".","."]
    ]
```
it says it should be valid, but actually its not,
there is 2 number '4' in the same first 3x3 square

#### Expected behavior
should be **not valid** but it says its suppose to be **valid**

#### Screenshots
![image](https://user-images.githubusercontent.com/49496254/134815628-4620eae5-18ca-4e32-be41-be79cffb20f4.png

**Comment by lc-kay** [comment]
@Yitzhakpro
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Yitzhakpro Our team has reviewed your report and concluded that the expected answer for this test case is false. Thank you for your time.
