### ISSUE TITLE
Missing Test Case - 1544. Make The String Great

### ISSUE THREAD

**Issue by shivam5296** [LeetCode-Feedback/LeetCode-Feedback#4908]
#### Code you used for Submit/Run operation
"""
class Solution:
    def makeGood(self, s: str) -> str:
        stack=[]
        for i in range(len(s)):
            if stack:
                if (ord(stack[-1])+32==ord(s[i])) or (ord(s[i])+32 == ord(stack[-1])):
                    stack.pop()
                else:
                    stack.append(s[i])
            else:
                stack.append(s[i])
        n=""
        for i in stack:
            n=n+i
        return n

"""
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
``` Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
@shivam5296 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
