### ISSUE TITLE
468. Validate IP Address

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#491]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Contradictory problem statement and test cases

#### Expected behavior

> Note: You may assume there is no extra space or special characters in the input string.

Test case 72:

```
"0.0.0.-0"
```

'-' is a special character. Mentioned [here](https://leetcode.com/problems/validate-ip-address/discuss/95484/PythonJava-Easy-Understand-Solution/273903) as well.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
