### ISSUE TITLE
Mistake in example solution - 1161. Maximum Level Sum of a Binary Tree

### ISSUE THREAD

**Issue by ccskying** [LeetCode-Feedback/LeetCode-Feedback#4910]
#### Your LeetCode username

username: ccskying

#### Category of the bug
- [ ] Question 1161. Maximum Level Sum of a Binary Tree
- [ ] Solution Approach 1: DFS : Recursive Inorder Traversal
- [ ] Language Python
- [ ] Missing Test Cases No.39

#### Description of the bug

The example Python solution of "Approach 1: DFS : Recursive Inorder Traversal" can't pass the test case No.39.
It didn't return the smallest level of the maximum sum.

#### Code you used for Submit/Run operation

```
from collections import defaultdict
class Solution:
    def maxLevelSum(self, root: TreeNode) -> int:
        def inorder(node, level):
            if node:
                inorder(node.left, level + 1)
                level_sum[level] += node.val
                inorder(node.right, level + 1)
            
        level_sum = defaultdict(int)
        inorder(root, 1)
        return max(level_sum, key = level_sum.get)
```

#### Language used for code
Python

#### Expected behavior

Input: [1,1,0,7,-8,-7,9]
Output: 3
Expected: 1

the sum of all three level is [1,1,1]. So the smallest should be the first level.

#### Screenshots

[https://github.com/ccskying/PythonNotes/blob/master/LeetCode_Solutions/Capture.PNG](url)

#### Additional context

I just add a loop to search for smallest level instead of using max directly. I think there must be some simpler way that I don't know.

**Comment by lc-kay** [comment]
Hi @ccskying 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ccskying 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
