### ISSUE TITLE
2018. Check if Word Can Be Placed In Crossword - inconsistent results

### ISSUE THREAD

**Issue by armandino** [LeetCode-Feedback/LeetCode-Feedback#4911]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Question: 2018. Check if Word Can Be Placed In Crossword

There seems to be an issue with how the test cases are evaluated for this question. For example: 

**Input 1:**
```
[["a"],["b"],[" "]]
"x"
```
Expected: **true**

**Input 2:**
```
[["a"],[" "],[" "]]
"xx"
```
Expected: **false**

#### Language used for code
Java

#### Expected behavior
If expected value is true for Input 1, it should also be true for Input 2.

#### Screenshots

![image](https://user-images.githubusercontent.com/1159054/134825791-9bf567c8-9f2a-4f8e-aa24-a6a834e0d2f9.png)
![image](https://user-images.githubusercontent.com/1159054/134825792-e96548f9-38d6-42ad-b156-9e30e763a752.png)

**Comment by lc-kay** [comment]
@armandino The expected results are correct.
Input1:
"x" can fit vertically in the third column so we return true.
Input2:
"xx" cannot fit in any row or column. We return false.

**Comment by armandino** [comment]
@lc-kay maybe I misunderstood something, but it seems to me "xx" does fit into the two empty slots.


```
Input 1:
[a]               [a]
[b]   add "x" ->  [b]
[ ]               [x]

Input 2:
[a]               [a]
[ ]   add "xx" -> [x]
[ ]               [x]
```

The two examples are the same, except in the first one there's one empty slot and in the second there are two.

**Comment by lc-kay** [comment]
@armandino Please check out this image for further clarification.
![crossword-ex4](https://user-images.githubusercontent.com/70870126/136610723-c0635fa6-d731-489d-abac-501081d03e30.png)
