### ISSUE TITLE
Missing __eq__ method

### ISSUE THREAD

**Issue by GigaMoksh** [LeetCode-Feedback/LeetCode-Feedback#4913]
#### Category of the bug
- [ ] Question
- [ ] Solution

####
 ```
class Solution:
    def getIntersectionNode(self, headA: ListNode, headB: ListNode) -> ListNode:
    
        a, b = headA, headB
        
        while a != b:
            a = a.next if a.next else headB
            b = b.next if b.next else headA
            
        return a
```

**Comment by lc-kay** [comment]
@GigaMoksh What's the problem number and title related to this issue?

**Comment by lc-kay** [comment]
Hi @GigaMoksh 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
