### ISSUE TITLE
Missing Test Case - 929. Unique Email Addresses

### ISSUE THREAD

**Issue by antsam** [LeetCode-Feedback/LeetCode-Feedback#4914]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The test case `".@leetcode.com"` has an expected answer of `1` but this is not a valid email address.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
C#

#### Expected behavior
The expected answer should be `0` as the email address is not a valid format.

#### Screenshots
N/A

#### Additional context
N/A

**Comment by lc-kay** [comment]
@antsam The test case ".@leetcode.com" is not a valid value of type string[] and returns invalid test case error.

**Comment by lc-kay** [comment]
@antsam Please provide the full test case in LeetCode format that you used to get this result. In addition, please provide the submission details link. Thank you!

**Comment by antsam** [comment]
@lc-kay Hi, sorry for the malformed test case.

This should demonstrate the case: `[".@leetcode.com"]`

Submission detail link: https://leetcode.com/submissions/detail/562848867/

I have a feeling that the oracle is parsing this email out as `@leetcode.com` and that gets accepted as a valid email. I believe it is against the RFC to have a localname of just `.`

**Comment by lc-kay** [comment]
@antsam 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @antsam 
Thank you for your time. The team reviewed your report and noticed the problem was with validations. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
