### ISSUE TITLE
Missing Test Case - 929. Unique Email Addresses

### ISSUE THREAD

**Issue by Heshamovic** [LeetCode-Feedback/LeetCode-Feedback#4915]
#### Your LeetCode username

Heshamovic

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

There is no test case where at least one email ends with '.net' and other with '.com' for example. All emails ends with .com and that is not stated in the statement.

#### Code you used for Submit/Run operation

```
// Unique Email Addresses
class Solution {
public:
    int numUniqueEmails(vector<string>& emails) {
        unordered_map<string, bool> vis;
        int ans = 0;
        for (auto s: emails)
        {
            string t;
            bool plus = false, domain = false;
            for (int i = 0; i < s.size() - 4; i++)
            {
                char it = s[i];
                if (it == '@')
                    domain = true;
                else if (it == '+')
                    plus = true;
                if (domain)
                    t += it;
                else if (!plus && it != '.')
                    t += it;
            }
            if (vis.find(t) == vis.end())
            {
                vis[t] = true;
                ans++;
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Wrong answer as the last part of domain name is always ignored

**Comment by lc-kay** [comment]
Hi @Heshamovic 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Heshamovic 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
