### ISSUE TITLE
Missing Test Case - 782. Transform to Chessboard

### ISSUE THREAD

**Issue by thylaco1eo** [LeetCode-Feedback/LeetCode-Feedback#4916]
#### Your LeetCode username

thylaco1eo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

one test case missing, which leads to a wrong accept.

#### Code you used for Submit/Run operation

```
// Transform to Chessboard
class Solution:
    def movesToChessboard(self, board: List[List[int]]) -> int:
        n = len(board)
        patt1 = ([0, 1]*(n//2+1))[:n]
        patt2 = ([1, 0]*(n//2+1))[:n]
        
        board_t = map(list, zip(*board))
        Cnt_r = list(Counter(tuple(row) for row in board).items())
        Cnt_c = list(Counter(tuple(row) for row in board_t).items())
        if len(Cnt_r) != 2 or len(Cnt_c) != 2: return -1
        if abs(Cnt_r[0][1] - Cnt_r[1][1]) > 1: return -1
        if abs(Cnt_c[0][1] - Cnt_c[1][1]) > 1: return -1
        
        x1 = sum(i != j for i,j in zip(Cnt_r[0][0], patt1))
        y1 = sum(i != j for i,j in zip(Cnt_c[0][0], patt1))
        
        x2 = sum(i != j for i,j in zip(Cnt_r[0][0], patt2))
        y2 = sum(i != j for i,j in zip(Cnt_c[0][0], patt2))
        
        cands_x = [x for x in [x1, x2] if x % 2 == 0]
        cands_y = [y for y in [y1, y2] if y % 2 == 0]
        
        return min(cands_x)//2 + min(cands_y)//2
        
```

#### Language used for code

python

#### Expected behavior

the return of this testcase should be -1. The code that returns 2 should be rejected instead of being accepted.

#### Screenshots

![Bug](https://user-images.githubusercontent.com/6839013/134867217-81138aac-729c-420e-abcc-654527a11e44.PNG)

**Comment by lc-kay** [comment]
Hi @thylaco1eo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @thylaco1eo 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode account to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by thylaco1eo** [comment]
sorry for the late response. i just saw the message. how should i give you my account? Just write my username here or?

**Comment by thylaco1eo** [comment]
My LeetCode username is thylacoleo

**Comment by thylaco1eo** [comment]
@lc-kay please take a look. Thank you

**Comment by LC-Sue** [comment]
Hi @thylaco1eo,

Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
