### ISSUE TITLE
Missing Test Case - 782. Transform to Chessboard

### ISSUE THREAD

**Issue by tkloong** [LeetCode-Feedback/LeetCode-Feedback#4917]
#### Your LeetCode username
tkloong

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For the test case `[[0,1],[1,1]]`, the expected return is `-1`. The code that return `0` is accepted.

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
    int check(set<int> &st, int &n) {
        int mask = (1 << n) - 1;
        if (st.size() != 2) return -1;
        int k = *st.begin();
        int numOne = __builtin_popcount(k);
        if (numOne != n / 2 && numOne != (n+1) / 2) return -1;

        int res = 0;
        if (numOne * 2 == n) {
            res = min(__builtin_popcount(k ^ (0x55555555 & mask)) / 2,
                      __builtin_popcount(k ^ (0xAAAAAAAA & mask)) / 2);
        } else if (numOne * 2 < n) {
            res = __builtin_popcount(k ^ (0xAAAAAAAA & mask)) / 2;
        } else {
            res = __builtin_popcount(k ^ (0x55555555 & mask)) / 2;
        }
        return res;
    }

    int movesToChessboard(vector<vector<int>>& board) {
        int n = board.size();
        set<int> st;
        int state = 0;
        for (int r=0; r<n; ++r) {
            state = 0;
            for (int c=0; c<n; ++c) {
                state <<= 1;
                state += board[r][c];
            }
            st.insert(state);
        }
        int r1 = check(st, n);
        if (r1 == -1) return -1;
        
        st.clear();
        for (int c=0; c<n; ++c) {
            state = 0;
            for (int r=0; r<n; ++r) {
                state <<= 1;
                state += board[r][c];
            }
            st.insert(state);
        }
        int r2 = check(st, n);
        if (r2 == -1) return -1;
        else return r1 + r2;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The code that return `0` should be rejected instead of being accepted.

#### Screenshots

<img width="962" alt="Screen Shot 2021-09-27 at 4 34 25 PM" src="https://user-images.githubusercontent.com/5900412/134873411-3a1f304b-9706-46ce-9f77-bc610f568302.png">

**Comment by lc-kay** [comment]
Hi @tkloong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tkloong 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
