### ISSUE TITLE
Missing Test Case - 929. Unique Email Addresses

### ISSUE THREAD

**Issue by azabluda** [LeetCode-Feedback/LeetCode-Feedback#4918]
#### Your LeetCode username
linqmafia

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
It is unspecified how to treat '+' in the domain name. The code below is accepted, yet it is failing with the following test
```
["linqmafia@leet+code.com","linqmafia@code.com"]
```

#### Code you used for Submit/Run operation

```cs
public class Solution {
    public int NumUniqueEmails(string[] emails) =>
        emails.Select(e => e.Split('@', '+')).Select(p => (p[0].Replace(".", ""), p[^1])).Distinct().Count();
}
```

#### Language used for code
C#

#### Expected behavior
Either the test case or the code must be rejected.

#### Screenshots
![image](https://user-images.githubusercontent.com/7567733/134895073-d8ef2dda-416a-494a-bb46-ee5df949cf27.png)

**Comment by lc-kay** [comment]
Hi @azabluda 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @azabluda 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
