### ISSUE TITLE
468. Validate IP Address

### ISSUE THREAD

**Issue by devenps** [LeetCode-Feedback/LeetCode-Feedback#492]
#### Your LeetCode username
devenps

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Incorrect solution is accepted because of insufficient test case.
Test case: "172.16.254.10" which is missing.

#### Code you used for Submit/Run operation

```
// Validate IP Address
class Solution {
    public String validIPAddress(String IP) {
        if (IP == null || IP.length() == 0) return "Neither";
        int lastIndex = IP.length() - 1;
        if (IP.charAt(lastIndex) == '.' || IP.charAt(lastIndex) == ':') return "Neither";

        String[] nums = IP.split("\\.");
        if (nums.length == 4) {
            for (String s : nums) {
                if (!isValidDecimalNumber(s)) return "Neither";
            }
            
            return "IPv4";
        }

        nums = IP.split(":");
        if (nums.length == 8) {
            for (String s : nums) {
                if (!isValidHexaDecimalNumber(s)) return "Neither";
            }
            
            return "IPv6";
        }

        return "Neither";
    }

    private boolean isValidDecimalNumber(String s) {
        if(s.matches("^0|([1-9]+)$") && s.length() < 4){
            return Integer.parseInt(s) < 256;
        }

        return false;
    }

    private boolean isValidHexaDecimalNumber(String s) {
        return s.matches("^[0-9a-fA-F]+$") && s.length() <= 4;
    }
}
```

#### Language used for code

Java

#### Expected behavior

This test case should return "IPv4" but my above code is returning "Neither" and still, the solution got accepted. PFA screeshot.

#### Screenshots

![image](https://user-images.githubusercontent.com/8740608/84832754-7a5a5e80-b04b-11ea-81dc-d246f0fe93d8.png)

#### Additional context

Solution link: https://leetcode.com/submissions/detail/354613553/

**Comment by CooperCooperCooper** [comment]
Hi @devenps ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
