### ISSUE TITLE
Missing Test Case - 1293. Shortest Path in a Grid with Obstacles Elimination

### ISSUE THREAD

**Issue by Bruception** [LeetCode-Feedback/LeetCode-Feedback#4920]
#### Your LeetCode username
Bruception

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug

Currently, DFS + Memoization is accepted as a "solution". This is not correct.

#### Code you used for Submit/Run operation

```
class Solution:
    def shortestPath(self, grid: List[List[int]], k: int) -> int:
        visited, m, n = set(), len(grid), len(grid[0])
        @cache
        def dfs(i, j, k):
            key = (i, j)
            if (k < 0 or i >= m or i < 0 or j >= n or j < 0 or key in visited):
                return math.inf
            if (i == m - 1 and j == n - 1):
                return 0
            k -= grid[i][j]
            visited.add(key)
            minSteps = min(dfs(i + 1, j, k), dfs(i - 1, j, k), dfs(i, j + 1, k), dfs(i, j - 1 , k))
            visited.remove(key)
            return 1 + minSteps
        ans = dfs(0, 0, k)
        return -1 if ans == math.inf else ans
```

#### Language used for code
Python

#### Expected behavior

The above solution should not be accepted.

#### Screenshots

<img width="1048" alt="Screen Shot 2021-09-27 at 10 35 00 AM" src="https://user-images.githubusercontent.com/58147810/134929687-0e5748cc-9d1c-440d-af81-251a03788fe0.png">

<img width="1438" alt="Screen Shot 2021-09-27 at 10 35 56 AM" src="https://user-images.githubusercontent.com/58147810/134929863-0e0b5ddc-da5d-4ba5-900c-80d4ecbb1701.png">

#### Additional context

This is my sample test case:
```
Input:
grid = [[0,0,0,0,0,0,0,0,0,0],[0,1,1,1,1,1,1,1,1,0],[0,1,0,0,0,0,0,0,0,0],[0,1,0,1,0,1,0,0,1,0],[0,1,0,1,0,1,0,0,1,0],[0,1,0,1,0,1,0,0,1,0],[0,1,0,1,0,1,0,0,1,0],[0,1,0,1,0,1,0,0,1,0],[0,1,0,1,0,1,0,0,1,0],[0,1,0,1,0,1,0,0,1,0],[0,1,0,1,0,0,0,0,1,0],[0,1,0,1,1,1,1,1,1,0],[0,0,0,1,0,0,0,0,1,0]]
k = 1

Output:
21
```

**Comment by lc-kay** [comment]
Hi @Bruception 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
