### ISSUE TITLE
634. Find the Derangement of An Array - Official Solution need to be updated

### ISSUE THREAD

**Issue by idontknoooo** [LeetCode-Feedback/LeetCode-Feedback#4921]
#### Your LeetCode username
idontknoooo

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The **Approach 2. Recursion** not working with current test cases. It will lead to an error.  
For `Java`, it's a `java.lang.StackOverFlowError`.

#### Code you used for Submit/Run operation
Not Applicable

#### Language used for code
`Java`

#### Expected behavior
I would recommend mentioning that even it's doable, it won't pass due to the number of recursion stacks that might be over the limit. I also tried a Python solution with the same implementation. It won't pass even with `@cache` decorator.

#### Screenshots

![image](https://user-images.githubusercontent.com/9439919/135006113-d6640334-9d0c-4929-8083-7fb1c6615b2a.png)

**Comment by lc-kay** [comment]
Hi @idontknoooo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @idontknoooo 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
