### ISSUE TITLE
Missing Test Case - 94. Binary Tree Inorder Traversal

### ISSUE THREAD

**Issue by abdurauf01** [LeetCode-Feedback/LeetCode-Feedback#4922]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by abdurauf01** [comment]
s

**Comment by lc-kay** [comment]
@abdurauf01 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
