### ISSUE TITLE
The values used are confusing - 675. Cut Off Trees for Golf Event

### ISSUE THREAD

**Issue by lesslucifer** [LeetCode-Feedback/LeetCode-Feedback#4923]
#### Your LeetCode username

lesslucifer

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Current values used:
- 0: For obstacles
- 1: For empty cells
- 2-n: For cells with trees

It's not common sense, if a cell's value is the height of the tree, then how come the empty ones are 1 (a tree with height = 1). It caused some confusing test cases such as the 54th: [[4,2,3], [0, 0, 1], [7,6,5]]. A lot of people don't understand it in the discussion.

It should be:
- -1: For obstacles
- 0: For empty cells
- 1-n: height of the trees

#### Code you used for Submit/Run operation
No code

#### Language used for code
No code

#### Expected behavior

- -1: For obstacles
- 0: For empty cells
- 1-n: height of the trees

#### Screenshots
None

#### Additional context
None

**Comment by lc-kay** [comment]
Hi @lesslucifer 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@lesslucifer Although we understand the possible confusion, we are unable to change the input for consistency. Thank you for your understanding.
