### ISSUE TITLE
Missing Test Case - 1337. The K Weakest Rows in a Matrix

### ISSUE THREAD

**Issue by MayukhSobo** [LeetCode-Feedback/LeetCode-Feedback#4924]
This problem is good but I guess the test cases are bad because I have seen solution where people are adding the values in the row to get the sum and then calculate the number of 1s and get better runtime than the people who have use binary search to calculate the number of 1s. Theoretically O(n) approach to get the number of 1s should give TLE but it is not. Rather these answers are giving better runtime. This should be fixed.

#### Your LeetCode username
sobo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@MayukhSobo For a valid missing test case report, please provide the accepted solution and the missing test case that will fail it. Thank you!

**Comment by lc-kay** [comment]
Hi @MayukhSobo 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
