### ISSUE TITLE
Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by jkpipaliya** [LeetCode-Feedback/LeetCode-Feedback#4925]
#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

I am trying to run a code by giving my input but it is showing invalid input. Input which I am giving is ```[2,1,0,3]```, but it is showing Invalid test case and invalid input.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int jump(vector<int>& nums) {
        int n=nums.size();
        if(nums.size()==1)
            return 0;
        if(nums[0]==0)
            return -1;
        int max_reach=nums[0];
        if(max_reach>=n-1)
            return 1;
        int step=nums[0];
        int jump=1;
        for(int i=1;i<n;++i)
        {
            if(i==n-1)
                return jump;
            max_reach=max(max_reach, i+nums[i]);
            if(max_reach>=n-1)
                return ++jump;
            step--;
            if(step==0)
            {
                jump++;
                if(i>=max_reach)
                {
                    return -1;
                }
                step=max_reach-i;
            }
        }
        return jump;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should accept my input and should give an output of code.

#### Screenshots

![Screenshot (49)](https://user-images.githubusercontent.com/25692474/135063895-bde4e671-ad77-4dce-8b2d-e2b0b473724a.png)

**Comment by yourappsgeek** [comment]
This is not a valid testCase as you cannot reach the last index using `[2,1,0,3]`

**Comment by lc-kay** [comment]
Hi @jkpipaliya 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jkpipaliya Our team has reviewed your report and found that this is not a valid test case. Thank you.
