### ISSUE TITLE
Improper Test Case - 28.Implement strStr()

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#4927]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
In 28.Implement strStr(), a test case with very large haystack.length and needle.length was newly added, I think this test case need to be removed.
As an easy problem, it can be solved by brute force,and the simple method with complexity O(mn) should be accepted.
But now, a solution with complexity O(mn) will get TLE.
I don't think the solution with time complexity less than O(mn), such as KMP, is proper from an interview perspective.
The LeetCode is designed for users who want to find a job, not for users who is interested in algorithm contests.

Therefore, I suggest the following two points:
1 The test case mentioned above should be removed.
2 In constraints, the maximum value of haystack.length and needle.length should be reduced from 5 * 10^4 to 5 * 10^3.

Code you used for Submit/Run operation

```
class Solution:
    def strStr(self, haystack: str, needle: str) -> int:

        if len(needle)<1:
            return 0
        if len(haystack)<1:
            return -1
        neei = 0
        j = 0

        while j<len(haystack):
            if haystack[j]==needle[neei]:
                neei+=1
                if neei==len(needle):
                    return  j+1-len(needle)         
            else:
                j-=neei
                neei=0
            j+=1
        return -1
```

Language used for code
Python3

Expected behavior
1 The test case mentioned above should be removed.
2 In constraints, the maximum value of haystack.length and needle.length should be reduced from 5 * 10^4 to 5 * 10^3.

Screenshots

Additional context

**Comment by lc-kay** [comment]
Hi @CarlCzerny837 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@CarlCzerny837 Our team has reviewed your report and ruled it invalid. We tested the bruteforce O(mn) in py, c++, and java and all passed. In addition, KMP is not the intended solution. Lastly, we tried to run your solution after increasing the time limit from 10s to 60s and it is still TLEed so it seems to be that your code needs to be optimized. Please refer to the discuss section for further assistance. Thank you for your time!
