### ISSUE TITLE
go语言运行例子没问题，但是提交会报错

### ISSUE THREAD

**Issue by Betterming** [LeetCode-Feedback/LeetCode-Feedback#4928]
**你的 LeetCode 用户名**
Betterming

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
代码运行没问题，但是提交代码会报错

**你使用的语言**
go

**你提交或者运行的代码**
```
var head = &TreeNode{Val: -1, Left: nil, Right: nil}
var pre *TreeNode
func convertBiNode(root *TreeNode) *TreeNode {
    if root == nil {
        return nil
    }
    order(root)
    return head.Right
}

func order(root *TreeNode) {
    if root == nil {
        return
    }
    order(root.Left)
    if pre == nil {
        head.Right = root
        pre = root
        root.Left = nil
    } else {
        pre.Right = root
        pre = root
        root.Left = nil
    }
    order(root.Right)
}
```

**期望行为**
请修正该bug

**屏幕截图**
![image](https://user-images.githubusercontent.com/35894046/135117733-7a293c3b-03fc-4108-a128-5ee3ac81d475.png)

**额外的上下文**
https://leetcode-cn.com/problems/binode-lcci/submissions/

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
