### ISSUE TITLE
Missing Test Case - 219. Contains Duplicate II

### ISSUE THREAD

**Issue by yourappsgeek** [LeetCode-Feedback/LeetCode-Feedback#4929]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Missing testcase: 
[-1000000000,1000000000]
2

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        int max=*max_element(nums.begin(), nums.end());
        int min=*min_element(nums.begin(), nums.end());
        vector<int> temp(max-min+1);

        for (int i=0; i<nums.size(); i++) {
            if(temp[nums[i]-min]>0 && i-temp[nums[i]-min]+1 <=k) 
                return true;
            else
                temp[nums[i]-min]=i+1;  
        }
        
        return false;
    }
};
```

#### Language used for code
 C++

#### Expected behavior
Memory Limit Exceeded but working fine for Java language

#### Screenshots

<img width="625" alt="Screen Shot 2021-09-28 at 4 58 55 PM" src="https://user-images.githubusercontent.com/24912693/135164685-3a2dadaf-6055-4f08-b730-0a079cf4b890.png">

**Comment by lc-kay** [comment]
@yourappsgeek Please provide the submission details link for your code. Thank you!

**Comment by yourappsgeek** [comment]
> @yourappsgeek Please provide the submission details link for your code. Thank you!

Thanks @lc-kay for looking into this, how can I share submission details?

**Comment by lc-kay** [comment]
<img width="770" alt="Screen Shot 2021-10-01 at 11 29 51 AM" src="https://user-images.githubusercontent.com/70870126/135669654-9d467e97-fe41-48b0-b073-e14e314d7b83.png">
@yourappsgeek It is hyperlinked under the status of the code in the submissions tab.

**Comment by yourappsgeek** [comment]
@lc-kay Here is [link](https://leetcode.com/submissions/detail/564141882/) but I don't think It's gonna work as I'm getting runtime error

**Comment by LC-Sue** [comment]
Hi @yourappsgeek,
Thank you for your time, the test case is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
