### ISSUE TITLE
53.最大子序和 C 执行代码和提交代码执行结果不一致

### ISSUE THREAD

**Issue by wwt-13** [LeetCode-Feedback/LeetCode-Feedback#4930]
**a_little_buaaer**

**Bug 类型**
- 53.最大子序和
- C

**描述**
执行代码和提交上去的代码执行结果不一致，同一个样例，本地执行和执行代码正确，提交后执行却错误

**你使用的语言**
C

**你提交或者运行的代码**
```c
#define max(a,b) (a)>(b)?(a):(b)
#define maxsize 10000
//定义dp[i]为以nums[i]为结尾的最大子序列和
//返回值是max(nums[numsSize-1],dp_test(nums,numsSize-1)+nums[numsSize-1)
int dp[maxsize]={0};
int count=0;
int dp_test(int* nums,int numsSize){
	if(numsSize<=count)
	return dp[numsSize];
	return max(nums[numsSize-1],dp_test(nums,numsSize-1)+nums[numsSize-1]);
}
int maxSubArray(int *nums,int numsSize){
	int i;
	int max_number=0;
	for(i=1;i<=numsSize;i++){
		dp[i]=dp_test(nums,i);
		count++;
		max_number=max(max_number,dp[i]);
	}
	return max_number; 
}
```

**期望行为**
希望能尽快修复提交代码执行错误的bug

**屏幕截图**
![](https://i.loli.net/2021/09/29/zyN9IbLmP3XV7EU.png)

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
