### ISSUE TITLE
Incorrect Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by ParthSalat47** [LeetCode-Feedback/LeetCode-Feedback#4932]
#### Your LeetCode username

https://leetcode.com/parthvsalat/

#### Category of the bug
- [x] Question

#### Description of the bug

In the question it's written that:

> There is **only one repeated number** in nums, return this repeated number.

#### Language used for code

C++

#### Expected behavior

I expected only one repeated number. But here's a test case that violates the question description itself:

`[2,2,2,2,2]`

#### Screenshots

![image](https://user-images.githubusercontent.com/62230055/135247165-1b8f1cfc-55e8-4804-8501-664a32781a5a.png)

#### Additional context

Either remove this test case, or make necessary changes in the question description.

Link to the question: [leetcode.com/problems/find-the-duplicate-number/](https://leetcode.com/problems/find-the-duplicate-number/)

**Comment by Suraj-Kumar-07** [comment]
The Question says 

> **There is only one repeated number in nums, and you need to  return that repeated number**

You should return 

> 2

but you are returning 

> **0**

**Comment by stormsunshine** [comment]
@ParthSalat47 Please refer to @Suraj-Kumar-07 's reply. This problem requires returning the number that occurs more than once in the input array `nums`. For the example you provided, the number 2 occurs more than once and is repeated, so the expected output is 2.

I do not know why you think the expected output is 0. The number 0 is not in the input array `nums` and of course it is not repeated. Could you please explain your thoughts?

**Comment by ParthSalat47** [comment]
My bad. 
I thought that repetitions were only allowed once, like:
`1 2 2 3 4`
and not multiple times like:
`1 2 3 4 2 2 2`
Hence the confusion.

But now I understand that any **one** number can be repeated **any** no. of times.

Thanks, @stormsunshine for clarifying.
