### ISSUE TITLE
Article typographical errors

### ISSUE THREAD

**Issue by ArtistSu** [LeetCode-Feedback/LeetCode-Feedback#4935]
#### Your LeetCode username

GeekSu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 
language
#### Description of the bug

18 lines at https://leetcode.com/explore/learn/card/fun-with-arrays/521/introduction/3236/ 
I think There's an extra parenthesis here

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

java

**Comment by lc-kay** [comment]
Hi @ArtistSu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ArtistSu 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
