### ISSUE TITLE
Missing Test Case - 204. Count Primes

### ISSUE THREAD

**Issue by simsek0** [LeetCode-Feedback/LeetCode-Feedback#4937]
When the input is 2 , it expects you to return 0 , however 2 is a prime number and it should return to 1..
Also when the input is 10 , it shows that prime numbers are 2,3,5,7 and there are four of them, that`s correct however when the input is 3 , it expects you to return to 1 instead of 2...

**Comment by stormsunshine** [comment]
Please read the problem description carefully. This problem requires returning the number of prime numbers that are **strictly less than `n`**.

If the input is 2, then there is only one positive integer that is strictly less than 2, which is 1 and is not a prime number, so the output should be 0.

If the input is 3, the only prime number that is strictly less than 3 is 2, so the output should be 1.

**Comment by lc-kay** [comment]
@simsek0 I hope @stormsunshine was able to provide clarification on your question. For further discussion, please raise a post in the problem discuss section. Thank you!
