### ISSUE TITLE
Missing Test Case - 1584. Min Cost to Connect All Points

### ISSUE THREAD

**Issue by mayuri-kulkarni** [LeetCode-Feedback/LeetCode-Feedback#4939]
#### Your LeetCode username

mayurimk47

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The program describe the distance is of type manhatan distance. In example, the diagram actually shows Euclidean distance connections instead of manhatan.
ref - [manhatan and Euclidean distance](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.omnicalculator.com%2Fmath%2Fmanhattan-distance&psig=AOvVaw06maxK5_gsP7ZYvDvKb0Pp&ust=1633026829802000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCKidy5LppPMCFQAAAAAdAAAAABAD)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @mayuri-kulkarni 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mayuri-kulkarni Our team has reviewed your report, and the image is showing the edges between the points, and the costs written over each edge are the manhattan distance. Also, drawing the edges as the manhattan distance will confuse the other users. Thank you for your understanding.
