### ISSUE TITLE
850. Rectangle Area II - Missing constraints

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#494]
#### Your LeetCode username

roll_no_1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

All the rectangles in the input are having a positive area (i.e., x1 < x2 and y1 < y2). I verified it using an assert statement. Adding this as a constraint would make the problem clearer.

#### Code you used for Submit/Run operation

```
class Solution {
    using ll = long long;
    const int mod = 1e9 + 7;
    
    int merge(multiset<vector<int>>& intervals) {
        int len = 0;
        vector<vector<int>> ans;
        for(auto& I : intervals) {
            if(ans.size() && I[0] <= ans.back()[1])
                ans.back()[1] = max(ans.back()[1], I[1]);
            else 
                ans.push_back(I);
        }
        
        for(auto& p : ans) len += p[1] - p[0];
        return len;
    }
    
public:
    int rectangleArea(vector<vector<int>>& rect) {
        vector<vector<int>> v;
        
        for(int i = 0; i < rect.size(); i++) {
            auto& p = rect[i];
            int x1 = p[0], y1 = p[1];
            int x2 = p[2], y2 = p[3];
            assert(x1 < x2 && y1 < y2);
            v.push_back({x1, 1, i});
            v.push_back({x2, -1, i});
        }
        
        sort(v.begin(), v.end());
        
        ll ans = 0;
        multiset<vector<int>> st;
        
        for(int i = 0; i < v.size()-1; i++) {
            int j = v[i][2];
            if(v[i][1] == 1) {
                st.insert({rect[j][1], rect[j][3]});
            }
            else {
                st.erase(st.find({rect[j][1], rect[j][3]}));
            }
            
            int w = v[i+1][0] - v[i][0];
            if(!w) continue;
            int h = merge(st);
            
            ans += h * 1ll * w;
        }
        
        return ans % mod;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The note section must contain one of the following 2 points:

* All rectangles in the input will have a positive area.
OR
* For all rectangles in the input, x1 < x2 and y1 < y2.

#### Screenshots

![image](https://user-images.githubusercontent.com/36921843/84878517-8f64db00-b0a7-11ea-9835-6a40531739f5.png)

#### Additional context

I verified the above using an assert statement.

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for your time. We appreciate the suggestion, but the change is not needed because the first paragraph of the problem states that both points have a relative position bottom-left and top-right corners. We appreciate your support.
