### ISSUE TITLE
Wrong Test Case - 190. Reverse Bits

### ISSUE THREAD

**Issue by Sushanto** [LeetCode-Feedback/LeetCode-Feedback#4940]
#### Your LeetCode username

5u5h4n70

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Invalid test case was given because of which facing Runtime error (NumberFormatException)

#### Code you used for Submit/Run operation

```
class Solution {
    // you need treat n as an unsigned value
    fun reverseBits(n:Int):Int {
        return Integer.parseInt(n.toString(2).padStart(32, '0').reversed(), 2)
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

Expected - The input must be a binary string of length 32 (as per constraints in the problem)
Actual - Input given as "11-00000000000000000000000000000" causing NumberFormatException

#### Screenshots

![image](https://user-images.githubusercontent.com/13949911/135330743-8a6cc048-29b1-461c-ab73-2e2c2cd5e55c.png)

**Comment by lc-kay** [comment]
Hi @Sushanto 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Sushanto Our team has checked the test file and there is no test case with "11-00000000000000000000000000000" For this issue, please raise it in the discuss section. Thank you for your time.
