### ISSUE TITLE
Missing Test Case - 1365. How Many Numbers Are Smaller Than the Current Number

### ISSUE THREAD

**Issue by Sahilsanjeev-stack** [LeetCode-Feedback/LeetCode-Feedback#4942]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Sahilsanjeev-stack** [comment]
sahil

**Comment by lc-kay** [comment]
@Sahilsanjeev-stack Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
