### ISSUE TITLE
Missing Test Case - 698. Partition to K Equal Sum Subsets

### ISSUE THREAD

**Issue by kunchalasaikumar** [LeetCode-Feedback/LeetCode-Feedback#4943]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@kunchalasaikumar Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
