### ISSUE TITLE
498. Diagonal Traverse

### ISSUE THREAD

**Issue by Alka-2022** [LeetCode-Feedback/LeetCode-Feedback#4946]
#### Category of the bug
- [x] Solution

#### Language used for code

class Solution {
public:
    vector<int> findDiagonalOrder(vector<vector<int>>& matrix) {
        if (matrix.empty() || matrix[0].empty()) return {};
        int m = matrix.size(), n = matrix[0].size();
        int r = 0, c = 0, d = 0; // first go up
        vector<int> res(m*n);
        vector<vector<int>> dirs = {{-1,1}, {1,-1}};
        for (int i = 0; i < m*n; ++i) {
            // cout << r << " " << c << " " << matrix[r][c] << endl;
            res[i] = matrix[r][c];
            r += dirs[d][0], c += dirs[d][1];
            if (r >= m) { r = m-1, c += 2, d = 1-d; }
            if (c >= n) { c = n-1, r += 2, d = 1-d; }
            if (r < 0) { r = 0, d = 1-d; }
            if (c < 0) { c = 0, d = 1-d; }
        }
        return res;
    }
};

**Comment by lc-kay** [comment]
@Alka-2022 Please feel free to share your code in the problem discuss section. 

We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
