### ISSUE TITLE
Wrong Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by azhar1038** [LeetCode-Feedback/LeetCode-Feedback#4947]
#### Your LeetCode username
mdAzhar

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question says, "**If there exists a solution, it is guaranteed to be unique**". But some test cases contains more than one solution.

Example: [Check this test case](https://leetcode.com/submissions/detail/563500234/testcase/)

For the above test case, you can travel around the circuit once in the clockwise direction if you start from index 16458 or 16460

#### Code you used for Submit/Run operation

```python
class Solution:
    def canCompleteCircuit(self, gas: List[int], cost: List[int]) -> int:
        n = len(gas)
        gas = [gas[i]-cost[i] for i in range(n)]
        if sum(gas) < 0:
            return -1
        
        maximum = n-1
        for i in range(n-2, -1, -1):
            gas[i] += gas[i+1]
            if gas[i] > gas[maximum]:
                maximum = i
                
        return maximum
```

#### Language used for code
Python 3

#### Expected behavior
The above code returns the first possible index from end and **If there exists a unique solution**, it should be same as expected answer, but it is different.

#### Additional context

Either update the question or remove such test cases. There are other test cases too that are violating the question.

**Comment by lc-kay** [comment]
Hi @azhar1038 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @azhar1038 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
