### ISSUE TITLE
[Personal] Successful submissions of Weekly Contest 260 disappears

### ISSUE THREAD

**Issue by Yiyiyimu** [LeetCode-Feedback/LeetCode-Feedback#4948]
#### Your LeetCode username

wosoyoung

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I finished first three problems in the contest, but right now the correct submission of 2nd and 3rd problem disappears, only left the failed submissions. I noticed that due to I've ranked around 1000 when the contest finishes and right now it's 3500+.

As you could find on the screenshots, the correct code could be restored from local storage, but there is no such submission in the submission list.

#### Code you used for Submit/Run operation

unrelated

#### Language used for code

unrelated

#### Screenshots

![image](https://user-images.githubusercontent.com/34589752/135544983-06894a0d-f2a3-4e12-a96b-c41678201a07.png)
![image](https://user-images.githubusercontent.com/34589752/135544999-1f656f40-26b3-41f2-9927-2034c465977f.png)
![image](https://user-images.githubusercontent.com/34589752/135545015-dcf1155a-c44b-437a-a803-555c9a26f4d4.png)
![image](https://user-images.githubusercontent.com/34589752/135545030-22cbd78b-cb74-482b-a6de-ecb423bb1a47.png)

#### Additional context

It might not be a good place here to report such an issue, but I could not find the feedback link on Leetcode website. I'll appreciate it if I could be led to the correct report link.

**Comment by lc-kay** [comment]
@Yiyiyimu Please reach out to us through our [help center](https://leetcode.com/support). Thank you for your time.
