### ISSUE TITLE
787. Cheapest Flights Within K Stops - Weak Test Cases

### ISSUE THREAD

**Issue by humanest** [LeetCode-Feedback/LeetCode-Feedback#495]
#### Your LeetCode username

humanest

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The current fastest Python3 submission didn't consider some special situation. It can be accepted but cannot pass some special test cases.

#### Code you used for Submit/Run operation

```
class Solution:
    def findCheapestPrice(self, n: int, flights: List[List[int]], src: int, dst: int, K: int) -> int:
        distances = [float('inf') for _ in range(n)]
        cur_stops = [float('inf') for _ in range(n)]
        distances[src], cur_stops[src] = 0, 0
        
        # pq = [(0, src)]
        pq = [(distances[src], cur_stops[src], src)]
        graph = [{} for _ in range(n)]
        for u, v, w in flights:
            graph[u][v] = w
        
        while pq:
            dist, stops, vertex = heapq.heappop(pq)
            
            if vertex == dst:
                return dist
            if stops == K+1:
                continue
            # if dist > distances[vertex]:
            #     continue
            
            for neighbor, weight in graph[vertex].items():
                if dist + weight < distances[neighbor]:
                    distances[neighbor] = dist+weight
                    # heapq.heappush(pq, (dist+weight, neighbor))
                    heapq.heappush(pq, (dist+weight, stops+1, neighbor))
                elif stops + 1 < cur_stops[neighbor]:
                    cur_stops[neighbor] = stops + 1
                    heapq.heappush(pq, (dist+weight, stops+1, neighbor))
        
        return distances[dst] if distances[dst]!=float('inf') else -1
```

#### Language used for code

Python3

#### Expected behavior

To reduce time, this algorithm only searches for the path with either better stops or better costs. But in some cases, the best path makes a balance between stops and path.
For example, this algorithm gives the wrong answer in the test case below.
```
11
[[0,3,3],[3,4,3],[4,1,3],[0,5,1],[5,1,100],[0,6,2],[6,1,100],[0,7,1],[7,8,1],[8,9,1],[9,1,1],[1,10,1],[10,2,1],[1,2,100]]
0
2
4
```

#### Screenshots

![image](https://user-images.githubusercontent.com/44194343/84886507-86054f80-b062-11ea-8d8d-18065cd6d30a.png)
![image](https://user-images.githubusercontent.com/44194343/84886595-a3d2b480-b062-11ea-8db2-d856e24dce0e.png)

**Comment by CooperCooperCooper** [comment]
Hi @humanest ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @humanest ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
