### ISSUE TITLE
Missing Test Case - 1146. Snapshot Array

### ISSUE THREAD

**Issue by yuanxiao2011** [LeetCode-Feedback/LeetCode-Feedback#4950]
#### Your LeetCode username

yuanxiao

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug

test case:
Input:
["SnapshotArray","snap","set","snap","set","snap","get"]
[[1],[],[0,1],[],[0,0],[],[0,2]]
Output:
[null,0,null,1,null,2,1]
Expected:
[null,0,null,1,null,2,0]

#### Code you used for Submit/Run operation

```
class SnapshotArray(object):

    def __init__(self, length):
        self.nums=[0]*length
        self.snap_id = -1
        self.cache =  {}
        
    def set(self, index, val):
        if val == self.nums[index]: return  # this is the bug, would produce an incorrect answer for the test case, but code accepted.
        if index not in self.cache:
            self.cache[index] = [[],[]]
        if self.cache[index][0] and self.cache[index][0][-1] == self.snap_id+1:
            self.cache[index][1][-1] = val
        else:
            self.cache[index][0].append(self.snap_id+1)
            self.cache[index][1].append(val)
        
    def snap(self):
        self.snap_id += 1
        return self.snap_id

    def get(self, index, snap_id):
        if index not in self.cache:
            return self.nums[index]
        idx = bisect.bisect(self.cache[index][0],snap_id)
        if not idx:
            return self.nums[index]
        return self.cache[index][1][idx-1]

```

#### Language used for code

python

**Comment by lc-kay** [comment]
Hi @yuanxiao2011 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yuanxiao2011 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
