### ISSUE TITLE
Missing Test Case: 1460. Make Two Arrays Equal by Reversing Sub-arrays

### ISSUE THREAD

**Issue by johnchoi96** [LeetCode-Feedback/LeetCode-Feedback#4952]
#### Your LeetCode username
johnchoi96

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Input:
[1, 2, 3, 2, 2]
[1, 2, 3, 1, 3]
Should return false

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean canBeEqual(int[] target, int[] arr) {
        Set<Integer> set = new HashSet<>();
        int sum1 = 0, sum2 = 0;
        for (int num : arr) {
            set.add(num);
            sum1 += num;
        }
        
        for (int num : target) {
            if (!set.contains(num)) return false;
            sum2 += num;
        }
        return sum1 == sum2;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Should be failing for the test case above but passes

**Comment by lc-kay** [comment]
Hi @johnchoi96 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @johnchoi96 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
