### ISSUE TITLE
Solution in article is incorrect [918]

### ISSUE THREAD

**Issue by shashaa35** [LeetCode-Feedback/LeetCode-Feedback#4956]
#### Your LeetCode username

shashaa35

#### Category of the bug
- [ ] Solution

#### Description of the bug

In the Approach 3: Kadane's (Sign Variant), and Approach 4: Kadane's (Min Variant). Author missed the condition if the array is of length 1.

#### Code you used for Submit/Run operation

```
if(A.length == 1)
            return A[0];
```

**Comment by lc-kay** [comment]
Hi @shashaa35 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @shashaa35,
Thank you for your feedback. The problem has been updated. We appreciate your support!
