### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by EmmaLaure** [LeetCode-Feedback/LeetCode-Feedback#4957]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

There seems to be no test case for when the two strings are different lengths. 

#### Code you used for Submit/Run operation

```
class Solution:
    def isIsomorphic(self, s: str, t: str) -> bool:
        %if len(s) != len(t):
            %return False
        mapping = {}
        for idx, l in enumerate(s):
            if l not in mapping and t[idx] not in mapping.values():
                mapping[l] = t[idx]
            else:
                if l not in mapping:
                    return False
                elif mapping[l] == t[idx]:
                    continue
                else:
                    return False
        return True
```

#### Expected behavior

The solution got accepted, without checking if the two strings (s and t) are of the same length using the following code; '''if len(s) != len(t):
            return False '''.

**Comment by lc-kay** [comment]
@EmmaLaure Please provide the submission details link and the exact test case that will cause it to fail. Thank you!

**Comment by LC-Sue** [comment]
Hi @
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
