### ISSUE TITLE
Arrays101 Explore - Deletion from array - delete from end

### ISSUE THREAD

**Issue by arunasindhura** [LeetCode-Feedback/LeetCode-Feedback#4961]
#### Your LeetCode username

arunasindhura9221@gmail.com

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

From my understanding, it is a wrong solution provided

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

The below is mentioned in "Arrays101 Explore - Deletion from array - delete from end"
// Deletion from the end is as simple as reducing the length
// of the array by 1.
length--;

-> But I think this is not right. Let's say I do the above & try to print all elements in the array, It would still print the elements I intent to delete right. So I need to explicitly set the value of that index to default value and then reduce the length of array.

**Comment by lc-kay** [comment]
Hi @arunasindhura 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
