### ISSUE TITLE
Missing Test Case - 2029. Stone Game IX

### ISSUE THREAD

**Issue by Pisces311** [LeetCode-Feedback/LeetCode-Feedback#4962]
#### Your LeetCode username

Pisces311

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I found a solution in discussion that can get an accepted. However, I managed to hacked it with [2,2,2,3,3,3].

#### Code you used for Submit/Run operation

``` java
    public boolean stoneGameIX(int[] stones) {
        int[] count = new int[3];
        for (int stone : stones) count[stone % 3]++;
        if (count[1] == 0 || count[2] == 0 || (count[0] % 2 == 1 && Math.abs(count[1] - count[2]) < 3)) return false;
        return true;
    }
```

#### Language used for code

Java

#### Expected behavior

Return true.

#### Screenshots

<img width="1194" alt="截屏2021-10-03 上午12 01 33" src="https://user-images.githubusercontent.com/46783819/135740728-22a2c237-a0b5-4105-8571-1f1823d72f6c.png">

**Comment by lc-kay** [comment]
Hi @Pisces311 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Pisces311 Our team recently updated the test case set for the question and your code now fails on one of them. Therefore, we will not be adding this test case. Thank you for your time.
