### ISSUE TITLE
Missing Test Case - 2029. Stone Game IX

### ISSUE THREAD

**Issue by Aniket-Jain-byte** [LeetCode-Feedback/LeetCode-Feedback#4963]
#### Your LeetCode username
helloaniorigamiwpu

#### Category of the bug
Missing Test Cases 

#### Description of the bug

Code gets accepted but fails on the test case [3,1,1,1]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool stoneGameIX(vector<int>& stones) {
        int cnt[3] = {};
        for (int a: stones)
            cnt[a % 3]++;
        if (min(cnt[1], cnt[2]) == 0)
            return false;
        return abs(cnt[1] - cnt[2]) > 2 || cnt[0] % 2 == 0;
    }
};
```

#### Language used for code
C++

#### Expected behavior
This code should fail but passes

#### Screenshots
![image](https://user-images.githubusercontent.com/76682881/135744703-77067542-ddd1-4d22-8e30-bf1b352346e8.png)

**Comment by lc-kay** [comment]
Hi @Aniket-Jain-byte 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Aniket-Jain-byte Our team recently updated the test case set for the question and your code now fails on one of them. Therefore, we will not be adding this test case. Thank you for your time.
