### ISSUE TITLE
BFS Template II Error

### ISSUE THREAD

**Issue by JamesKPolk** [LeetCode-Feedback/LeetCode-Feedback#4965]
#### Your LeetCode username
RunSpryly

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The pseudocode for BFS Template II in the "Queue & Stack" explore card has an error.
There is a conditional:
``if (next is not in used) {`` ,
but there is no variable called ``used``.
I'm sure that line is supposed to be 
``if (next is not in visited) {``
because we want to avoid enqueueing nodes that have already been visited.

edit:
Also, since I have your attention, users midnight_moon and sypks [posted in the forums](https://leetcode.com/discuss/explore/queue-stack/253371/Bug-found-in-BFS-template-1) about a bigger error which is that **both templates yield the wrong answer**. If the target is reachable, it will overestimate the length of the shortest path by one. Consider the case where the target node is the same node as the root, this function will return a length of 1. To fix this, the variable step should be incremented at the very end of the while loop, not the beginning.

#### Code you used for Submit/Run operation

```
/**
 * Return the length of the shortest path between root and target node.
 */
int BFS(Node root, Node target) {
    Queue<Node> queue;  // store all nodes which are waiting to be processed
    Set<Node> visited;  // store all the nodes that we've visited
    int step = 0;       // number of steps neeeded from root to current node
    // initialize
    add root to queue;
    add root to visited;
    // BFS
    while (queue is not empty) {
        step = step + 1;
        // iterate the nodes which are already in the queue
        int size = queue.size();
        for (int i = 0; i < size; ++i) {
            Node cur = the first node in queue;
            return step if cur is target;
            for (Node next : the neighbors of cur) {
                if (next is not in used) {
                    add next to queue;
                    add next to visited;
                }
            }
            remove the first node from queue;
        }
    }
    return -1;          // there is no path from root to target
}
```

#### Language used for code
Java / Pseudocode

#### Expected behavior

- For the correct variable name to be used.
- For the function to count the number of edges along the shortest path from root to target.

#### Additional context

[This is the page](https://leetcode.com/explore/learn/card/queue-stack/231/practical-application-queue/1372/ ) where the error can be found.

**Comment by lc-kay** [comment]
Hi @JamesKPolk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @JamesKPolk 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
