### ISSUE TITLE
Missing Test Case - 124. Binary Tree Maximum Path Sum

### ISSUE THREAD

**Issue by larasamirammal** [LeetCode-Feedback/LeetCode-Feedback#4966]
#### Category of the bug
 Solution & Missing Test Cases

#### Code you used for Submit/Run operation

```
// THIS IS the code provided by premium solution
class Solution {
  int max_sum = Integer.MIN_VALUE;

  public int max_gain(TreeNode node) {
    if (node == null) return 0;

    // max sum on the left and right sub-trees of node
    int left_gain = Math.max(max_gain(node.left), 0);
    int right_gain = Math.max(max_gain(node.right), 0);

    // the price to start a new path where `node` is a highest node
    int price_newpath = node.val + left_gain + right_gain;

    // update max_sum if it's better to start a new path
    max_sum = Math.max(max_sum, price_newpath);

    // for recursion :
    // return the max gain if continue the same path
    return node.val + Math.max(left_gain, right_gain);
  }

  public int maxPathSum(TreeNode root) {
    max_gain(root);
    return max_sum;
  }
}
```

#### Expected behavior

for the following inputs:
-----------------------------------------
{
  "tree": {
    "nodes": [
      {"id": "1", "left": "2", "right": "3", "value": 1},
      {"id": "3", "left": null, "right": null, "value": 3},
      {"id": "2", "left": null, "right": null, "value": 2}
    ],
    "root": "1"
  }
}
Expected : 6 
Solution output :18
----------------------------------------------
{
  "tree": {
    "nodes": [
      {"id": "1", "left": "2", "right": "-1", "value": 1},
      {"id": "-1", "left": null, "right": null, "value": -1},
      {"id": "2", "left": null, "right": null, "value": 2}
    ],
    "root": "1"
  }
}

expected:3
result :18

--------------------------------------
{
  "tree": {
    "nodes": [
      {"id": "1", "left": "-5", "right": "3", "value": 1},
      {"id": "3", "left": null, "right": null, "value": 3},
      {"id": "-5", "left": "6", "right": null, "value": -5},
      {"id": "6", "left": null, "right": null, "value": 6}
    ],
    "root": "1"
  }
}

expected : 6
result: 18

-------------------------------------------
{
  "tree": {
    "nodes": [
      {"id": "1", "left": "-5", "right": "-3-2", "value": 1},
      {"id": "-3-2", "left": "2-2", "right": "1-7", "value": -3},
      {"id": "1-7", "left": "1-8", "right": "1-10", "value": 1},
      {"id": "1-10", "left": "-5-2", "right": "0-5", "value": 1},
      {"id": "0-5", "left": null, "right": null, "value": 0},
      {"id": "-5-2", "left": null, "right": null, "value": -5},
      {"id": "1-8", "left": "0-4", "right": "1-9", "value": 1},
      {"id": "1-9", "left": null, "right": null, "value": 1},
      {"id": "0-4", "left": null, "right": null, "value": 0},
      {"id": "2-2", "left": "0-3", "right": "5", "value": 2},
      {"id": "5", "left": "2-3", "right": "1-6", "value": 5},
      {"id": "1-6", "left": null, "right": null, "value": 1},
      {"id": "2-3", "left": null, "right": null, "value": 2},
      {"id": "0-3", "left": "-9", "right": "-91", "value": 0},
      {"id": "-91", "left": null, "right": null, "value": -91},
      {"id": "-9", "left": null, "right": null, "value": -9},
      {"id": "-5", "left": "0", "right": "2", "value": -5},
      {"id": "2", "left": "1-4", "right": "1-5", "value": 2},
      {"id": "1-5", "left": "-1-3", "right": "-100", "value": 1},
      {"id": "-100", "left": null, "right": null, "value": -100},
      {"id": "-1-3", "left": null, "right": null, "value": -1},
      {"id": "1-4", "left": "-1-2", "right": "-6", "value": 1},
      {"id": "-6", "left": null, "right": null, "value": -6},
      {"id": "-1-2", "left": null, "right": null, "value": -1},
      {"id": "0", "left": "-3", "right": "3", "value": 0},
      {"id": "3", "left": "1-3", "right": "-1", "value": 3},
      {"id": "-1", "left": null, "right": null, "value": -1},
      {"id": "1-3", "left": null, "right": null, "value": 1},
      {"id": "-3", "left": "0-2", "right": "1-2", "value": -3},
      {"id": "1-2", "left": null, "right": null, "value": 1},
      {"id": "0-2", "left": null, "right": null, "value": 0}
    ],
    "root": "1"
  }
}

expected :9 
result:304
-------------------------------------------------------------
{
  "tree": {
    "nodes": [
      {"id": "-2", "left": "-1", "right": null, "value": -2},
      {"id": "-1", "left": null, "right": null, "value": -1}
    ],
    "root": "-2"
  }
}

expected :-1
result:304

------------------------------
{
  "tree": {
    "nodes": [
      {"id": "-2", "left": "-1", "right": null, "value": -2},
      {"id": "-1", "left": "2", "right": "3", "value": -1},
      {"id": "2", "left": null, "right": null, "value": 2},
      {"id": "3", "left": null, "right": null, "value": 3}
    ],
    "root": "-2"
  }
}

expected:4
result :304
--------------------------------

**Comment by lc-kay** [comment]
@larasamirammal Please provide the test case in LeetCode format as you would input them into the console. Thank you!

**Comment by larasamirammal** [comment]
Where to find the leetcode format template ? Are there specific
things/conventions to follow?

    Lara Zubaidia

Senior Java Software Engineer | Ex-Cisco Java & Python Software Engineer

Phone: +970 598 342 055 <+970+598+342+055> | Email:
***@***.*** [image:
LinkedIn] <https://www.linkedin.com/in/lara-zubaidia/>


‫في الثلاثاء، 5 أكتوبر 2021 في 9:14 م تمت كتابة ما يلي بواسطة ‪lc-kay‬‏ <‪
***@***.***‬‏>:‬

**Comment by LC-Sue** [comment]
Hi @larasamirammal ,
We are unable to run the test case in the format that you have provided. It would be great if you could submit your test case in the format that you would run it on the console. You can reference the example test case of the question for format Thank you for your time.

**Comment by LC-Sue** [comment]
Hi @larasamirammal,
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
