### ISSUE TITLE
Missing Test Case - 213. House Robber II

### ISSUE THREAD

**Issue by VigneshwaranMahadevan** [LeetCode-Feedback/LeetCode-Feedback#4967]
#### Your LeetCode username

Vigneshwaran Mahadevan

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Let us take the example [0,1] . Both 0th and 1st index are connected and the robber cannot rob either of them , else police will be alerted. But in the example run case , [0,1] input gives 1 as answer which is wrong. So what I want to convey is that the actual solution must have the line that if (nums.size()==2) return 0 ; because robber cannot rob if there are only 2 houses.

#### Code you used for Submit/Run operation

```
// House Robber II - 213
// Submitted by Vigneshwaran Mahadevan

class Solution {
private:
    int robber(vector<int> nums,int st,int en){
        int prev2=0;
        int prev1=nums[st];
        for(int i=st+1;i<=en;i++){
            int temp=prev1;
            prev1=max(prev1,prev2+nums[i]);
            prev2=temp;
        }
        return prev1;
    }    
public:
    int rob(vector<int>& nums) {
        int n=nums.size();
        if(n==1) return nums[0];
        if(n==2) return 0;
        return max(robber(nums,0,n-2),robber(nums,1,n-1));
    }
};
```

#### Language used for code

C++

#### Expected behavior

Just the extra line that 
if(n==2) return 0;
If Size of array is 2 , no robbery can happen

#### Screenshots

![Leetcode 213  House Robber II Bug - Vigneshwaran Mahadevan](https://user-images.githubusercontent.com/55322548/135808445-6391aef6-8843-4b0e-958c-ea1289f85eec.PNG)
Answer must be 0. If robber robs 54 , police will get alerted.

**Comment by lc-kay** [comment]
@VigneshwaranMahadevan The expected answer is correct. For this question, please raise it in the discuss section for further support. Thank you for your time.
