### ISSUE TITLE
A typo in Reshape the Matrix solution article

### ISSUE THREAD

**Issue by capturetheflag** [LeetCode-Feedback/LeetCode-Feedback#4968]
#### Your LeetCode username
capturetheflag

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is no `m` in the formula, but there is one in the text description next to it:  "where `m` is the number of columns"

#### Expected behaviour
the text description should be "where `n` is the number of columns"
Reason: `n` denotes a number of columns throughout the article

#### Screenshots

<img width="787" alt="reshape_the_matrix_typo" src="https://user-images.githubusercontent.com/16966230/135812280-4aca60e0-732d-4433-ab9b-e3b7cf0a1974.png">

**Comment by lc-kay** [comment]
Hi @capturetheflag 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @capturetheflag,
Thank you for your feedback. The problem has been updated. We appreciate your support!
