### ISSUE TITLE
Input Assertion Error - Problem 331 - Verify Preorder Serialization of a Binary Tree

### ISSUE THREAD

**Issue by bclodius** [LeetCode-Feedback/LeetCode-Feedback#4973]
#### Your LeetCode username

`bclodius`

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

`expected_code_answer` result element is truncated for certain input to `Run Code` test. 

This leaves result page in weird looking state.  Removing some permutations of the test cases fixes the issue?  What's so special about the specific inputs given that cause this issue I wonder?

![image](https://user-images.githubusercontent.com/590724/135949453-a1340744-cf7f-4085-8129-8fc634380349.png)

![image](https://user-images.githubusercontent.com/590724/135949503-be0397db-ebc1-4b8c-a0d2-431d419ca616.png)

#### Code you used for Submit/Run operation

```
"9,3,4,#,#,1,#,#,2,#,6,#,#"
"1,#"
"9,#,#,1"
"1,#,#"
"#,1,2"
"#"
"#,1,2"
"#,#"
```

#### Language used for code

`python3`

#### Expected behavior

The page should load like such.

![image](https://user-images.githubusercontent.com/590724/135949577-dc6223ed-66cf-461d-8b80-365a9bc356d1.png)

![image](https://user-images.githubusercontent.com/590724/135949609-ae7b896e-07b6-4837-9675-0bbd2457a343.png)

#### Screenshots
See above

#### Additional context
https://leetcode.com/problems/verify-preorder-serialization-of-a-binary-tree/

**Comment by lc-kay** [comment]
@bclodius We tried to reproduce this issue but were unable to do so. If the issue is persistent, please provide the exact steps to reproduce it and submit it to our help center via leetcode.com/support. 
<img width="1141" alt="Screen Shot 2021-10-05 at 11 35 17 AM" src="https://user-images.githubusercontent.com/70870126/136082605-a8de3c7f-92c4-4022-bf8b-c5a84c673ae8.png">
s

**Comment by bclodius** [comment]
@lc-kay thanks on retry I am no longer able to reproduce 👍
