### ISSUE TITLE
Typo Fix on Stack and DFS page 

### ISSUE THREAD

**Issue by iamgauravsatija** [LeetCode-Feedback/LeetCode-Feedback#4977]
#### Your LeetCode username
@iamgauravsatija

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a typo [Stack and DFS](https://leetcode.com/explore/learn/card/queue-stack/232/practical-application-stack/1377/) explore page.
Under: **Insights** > **1. What is the processing order of the nodes?**
Typo: till is spelled as til

#### Expected behavior
It should be as follows:
Firstly, we choose the path to the node B and trace-back **till** we reach the node

#### Screenshots

<img width="785" alt="Screen Shot 2021-10-05 at 12 28 48 AM" src="https://user-images.githubusercontent.com/32801600/135979048-0f4c2147-8604-4a5d-82a6-4341aa9c35da.png">

**Comment by lc-kay** [comment]
Hi @iamgauravsatija 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @iamgauravsatija 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
