### ISSUE TITLE
In the learning section, Need the example code in different programming languages other than JAVA

### ISSUE THREAD

**Issue by sowjanyagarapati** [LeetCode-Feedback/LeetCode-Feedback#4978]
I am learning arrays and the explanation is really cool with example code. However, the code is only present in JAVA which i am not very good at. It will be helpful if the example has support to all other programming languages as well like Python, C, C++. Thanks

**Comment by lc-kay** [comment]
@sowjanyagarapati Thank you for your feedback! Our content team is working on adding more languages in our Explore Card as we understand the importance of this.

**Comment by sowjanyagarapati** [comment]
Okay. Thanks for the response :)
