### ISSUE TITLE
1198. Find Smallest Common Element in All Rows – insufficient test cases

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#498]
#### Your LeetCode username
metricquant

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Question 1198 is as follows: _Given a matrix mat where every row is sorted in increasing order, return the smallest common element in all rows._ Whereas all the rows have to be considered, it is enough to consider the first three rows only to pass all the test cases. (An example would be mu submission below, which got accepted.) This is obviously wrong.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int smallestCommonElement(vector<vector<int>>& mat) {
        int n = mat[0].size();
        
        bool move = true;
        int a = 0, b = 0, c = 0;
        
        while(move && a < n && b < n && c < n) {
            int A = mat[0][a], B = mat[1][b], C = mat[2][c];
            int frontier = max(A, max(B, C));
            move = false;
            
            if(a < n && A < frontier) {
                a++;
                move = true;
            }
            
            if(b < n && B < frontier) {
                b++;
                move = true;
            }
            
            if(c < n && C < frontier) {
                c++;
                move = true;
            }
        }
        
        if(a >= n || b >= n || c >= n)
            return -1;
        
        return mat[0][a];
    }
};
```

#### Language used for code
C++

#### Expected behavior
There should be test cases for rejecting submissions that only consider a proper subset of the rows as in my submission.

**Comment by CooperCooperCooper** [comment]
Hi @metricquant ,
Thank you for reaching out to us. Do you have any test cases you would like to share with us to help with this issue?

**Comment by metricquant** [comment]
A minimal test case: `[[5,6], [5,6], [5,6], [4,6]]`.

My erroneous solutions will return `5`, but the correct answer is `6`.

**Comment by CooperCooperCooper** [comment]
Hi @metricquant ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @metricquant ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
