### ISSUE TITLE
Problem 18 (4sum). The time complexity analysis issue.

### ISSUE THREAD

**Issue by JunlinH** [LeetCode-Feedback/LeetCode-Feedback#4980]
#### Your LeetCode username

Junlin He

#### Category of the bug
- [x] Solution

#### Description of the bug

The time complexity of both two solutions should be O(n^k) instead of O(n^(k-1)). 
Since these two official solutions both used array slicing during each recursive call. 
We will have O(n^(k - 2)) branches in the recursive call tree. For each branch, we need O(n^2) time to do the array slicing.
Therefore, the final time complexity would be O(n^(k - 2)) * O(n^2), which is O(n^k).

To reach O(n^(k - 1)) time complexity, we should avoid using array slicing and use a pointer instead.

#### Code you used for Submit/Run operation

```
// Four Sum
class Solution:
    def fourSum(self, nums: List[int], target: int) -> List[List[int]]:
	
        def kSum(nums: List[int], target: int, k: int, idx: int) -> List[List[int]]:
            res = []
            if len(nums) - idx == 0 or nums[idx] * k > target or target > nums[-1] * k:
                return res
            if k == 2:
                return twoSum(nums, target, idx)
    
            for i in range(idx, len(nums)):
                if i == idx or nums[i - 1] != nums[i]:
                    for subset in kSum(nums, target - nums[i], k - 1, i + 1):
                        res.append([nums[i]] + subset)
    
            return res

        def twoSum(nums: List[int], target: int, idx: int) -> List[List[int]]:
            res = []
            lo, hi = idx, len(nums) - 1
    
            while (lo < hi):
                curr_sum = nums[lo] + nums[hi]
                if curr_sum < target or (lo > idx and nums[lo] == nums[lo - 1]):
                    lo += 1
                elif curr_sum > target or (hi < len(nums) - 1 and nums[hi] == nums[hi + 1]):
                    hi -= 1
                else:
                    res.append([nums[lo], nums[hi]])
                    lo += 1
                    hi -= 1
                                                         
            return res

        nums.sort()
        return kSum(nums, target, 4, 0)
```

#### Language used for code
Python

#### Expected behavior

Using a pointer, we can achieve the O(n^(k - 1)) time complexity and O(n) space.

**Comment by lc-kay** [comment]
Hi @JunlinH 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
