### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Safwan310** [LeetCode-Feedback/LeetCode-Feedback#4981]
#### Your LeetCode username
mdsafwan3102001

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The code which I wrote for this problem, does not pass the test case with the following input -> nums = [-10,7,19,15], target = 9
. It says that the expected output is [0,2] and my code gave an output of [0,1]. However when I executed this code at my own device and in the leetcode Use Example Testcases section, my code gave the output of [0,2].

#### Code you used for Submit/Run operation

```javascript
/**
 * @param {number[]} nums
 * @param {number} target
 * @return {number[]}
 */
let obj = {}
var twoSum = function(nums, target) {
    obj[nums[0]] = 0;
    for(let i = 1; i < nums.length; i++){
        if(target-nums[i] in obj){
            return [obj[target-nums[i]],i];
        }
        else{
            obj[nums[i]] = i;
        }
    }
    return [-1,-1];
};
```

#### Language used for code
Javascript

#### Expected behavior
For the input -> nums = [-10,7,19,15], target = 9 my code gives an output of [0,2], even while running the code in Use Example Testcases Section, my code was accepted. However on submission, I get a wrong answer page saying that my code gave an output of [0,1].

#### Screenshots

The page I receive on submitting the code.
![image](https://user-images.githubusercontent.com/69643150/136079996-83b98a1f-e42c-4469-a431-2f1d05b24580.png)
While executing the same code in Use Example Testcases section
![image](https://user-images.githubusercontent.com/69643150/136080061-5ab7031b-364b-43a3-9220-b056d146acf5.png)

**Comment by lc-kay** [comment]
Hi @Safwan310 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
