### ISSUE TITLE
Typos in the "Introduction to Binary Tree - Conclusion" section:

### ISSUE THREAD

**Issue by danteesdale** [LeetCode-Feedback/LeetCode-Feedback#4983]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
Typos in the **Introduction to Binary Tree - Conclusion** section:

Existing text:

> In other word, for each node in a BST, if m nodes in the right subtree, the node itself is the m + 1 largest element in the existed array.

Should be:

> In other words, for each node in a BST, if m nodes are in the right subtree, the node itself is the m + 1 largest element in the existing array.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
N/A

#### Screenshots
N/A

#### Additional context
N/A

**Comment by LC-Sue** [comment]
Hi @danteesdale 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
