### ISSUE TITLE
740. Delete and Earn. Wrong name in sorting algorithm described.

### ISSUE THREAD

**Issue by davitescobedo** [LeetCode-Feedback/LeetCode-Feedback#4985]
#### Your LeetCode username
eldavimost

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the solution description, the time complexity (Java) says that the solution is using radix sort when it is actually using counting sort. Even the time complexity described O(N+W) is the correct one from counting sort, as a radix sort would be O(d * (N+W)) being d the maximum number of digits in all the input numbers.

Time Complexity (Java): We performed a **radix sort** instead, so our complexity is O(N+W) where W is the range of allowable values for nums[i].

#### Language used for code
Java

#### Expected behavior
Time Complexity (Java): We performed a **counting sort** instead, so our complexity is O(N+W) where W is the range of allowable values for nums[i].

#### Screenshots
![image](https://user-images.githubusercontent.com/76172697/136259626-fc55edf4-526b-4a38-9aa4-dba03cb9f7a3.png)

**Comment by davitescobedo** [comment]
Sorry, I've also just noticed that it says the Java solution uses a HashMap when it's using an array.
![image](https://user-images.githubusercontent.com/76172697/136263153-8c747a9a-7159-4055-8438-111b5b8ea26c.png)

**Comment by eldavimost** [comment]
Hi @lc-kay, I think there's been a misunderstanding. My comment wanted to say that there are **2 issues** within the solution **instead of just 1.**
Please apply the suggested corrections to them after verifying they're right. 
Thank you!
