### ISSUE TITLE
1249. Minimum Remove to Make Valid Parentheses - Typo

### ISSUE THREAD

**Issue by Singleton06** [LeetCode-Feedback/LeetCode-Feedback#4987]
#### Your LeetCode username

Singleton06

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the solution tab, there is a typo in one of the words `reversal` where it is currently `reverals`.

I'm intentionally not including more detail since the solutions tab is a premium feature.

**Comment by LC-Sue** [comment]
Hi @Singleton06,
Thank you for your feedback. The problem has been updated. We appreciate your support!
