### ISSUE TITLE
Test case for Longest Common Prefix

### ISSUE THREAD

**Issue by Alybaev** [LeetCode-Feedback/LeetCode-Feedback#499]
#### Your LeetCode username
_Ongore_ 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Test case

#### Description of the bug
As you notice, in my solution I accessed the element that is out of the range of the _string_. 
`char prev = strs[0][i];`
The official docs says that:  
_Accessing the value at data()+size() produces undefined behavior: There are no guarantees that a null character terminates the character sequence pointed by the value returned by this function. See string::c_str for a function that provides such guarantee._
For this reason, I think my solution shouldn't be accepted and should cause Runtime Error message in leetcode console.

#### Code you used for Submit/Run operation
_Longest Common Prefix_
```

class Solution {
public:
    string longestCommonPrefix(vector<string>& strs) {
        string ans = "";
        if(strs.empty())
            return "";
        int i = 0;
        while(true)
        {
            char prev = strs[0][i];
            for(auto& s: strs)
            {
                int n = s.size();
                if(i >= n || s[i]!=prev)
                    return ans;
            }
            ans += prev;
            i++;
        }
        return ans;
        
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
Runtime Error

New test cases:
["", "", ""]
["fl","flow","flow"]

**Comment by CooperCooperCooper** [comment]
Hi @Alybaev ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @Alybaev ,
Thank you for your time. After a thorough review of this issue, our engineers want to point out that, because this is an undefined behavior, the issue is depended on the C++ compiler which is out of our hand. We appreciate your support.
