### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by Rockingrajat** [LeetCode-Feedback/LeetCode-Feedback#4992]
#### Your LeetCode username

rajat2001

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Question, Missing Test Cases

#### Description of the bug

The question asks for an O(logn) solution but the constraints are such that an O(n) or O(n^2) solution will also get accepted. Also, a very important key for solving the question nums[i]!=nums[i+1] is given at the very end, should be shifted to the main description.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```
```
// Find Peak element
int findPeakElement(vector<int>& nums) {
        int n = nums.size();
        long long int prev = INT_MIN;
        prev--;
        for(int i=0;i<n-1;i++){
            if(nums[i]>prev && nums[i]>nums[i+1]) return i;
            prev = nums[i];
        }
        return n-1;
    }
```
#### Language used for code

C++

#### Expected behavior

The above O(n) solution should've failed on some large testcases (but such testcases are missing). Max size of vector in C++ is 4GB so 2^30-1 elements can be fitted into it. So including larger testcases and reducing the time limit would allow only logn testcases to pass. I can design such testcases and would like to contribute.

**Comment by lc-kay** [comment]
@Rockingrajat Please provide the test case that will cause this code to fail. Thank you!

**Comment by LC-Sue** [comment]
Hi @Rockingrajat 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
