### ISSUE TITLE
Broken Erlang Code Snippet - 703. Kth Largest Element in a Stream

### ISSUE THREAD

**Issue by resetius** [LeetCode-Feedback/LeetCode-Feedback#4995]
#### Your LeetCode username

aozeritsky

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

Erlang code checker uses arity-3 for kth_largest_init_ which differs with code snippet.

#### Code you used for Submit/Run operation

```
-spec kth_largest_init_(K :: integer(), Nums :: [integer()]) -> any().
kth_largest_init_(K, Nums) ->
  ok.

-spec kth_largest_add(Val :: integer()) -> integer().
kth_largest_add(Val) ->
  0.
```

#### Expected behavior

I expect "Wrong answer", bug got  
```
Line 38: Char 13: function kth_largest_init_/3 undefined
%   38|       apply(fun kth_largest_init_/3,
%     |             ^
```

**Comment by LC-Sue** [comment]
Hi @resetius,
Our team has fixed the issue, thank you for your time!
