### ISSUE TITLE
Explore Card - Graph - LeetCode 797 - All Paths From Source to Target - DFS

### ISSUE THREAD

**Issue by cielong** [LeetCode-Feedback/LeetCode-Feedback#4996]
#### Your LeetCode username
cielosplayground@gmail.com

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
From my understanding, there's a tiny error in the video. 
It argues that for a directed graph, there's no need to track visited nodes around 3:54, while I think this is only true for a directed acyclic graph (DAG), which is stated to the problem.

**Comment by ingomueller-net** [comment]
Duplicated by #5315 (whose description is clearer).

**Comment by LC-Sue** [comment]
Hi @cielong,
Thank you for bringing this issue to our attention, we have added it to our list of things to be addressed the next time we make corrections to videos.
