### ISSUE TITLE
LeetCode 23. Merge k Sorted Lists:: Problem: Approach 3 PriorityQueue code is having so many bugs

### ISSUE THREAD

**Issue by Devanshi512** [LeetCode-Feedback/LeetCode-Feedback#4997]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Devanshi512** [comment]
Please fix the solution of problem -> https://leetcode.com/problems/merge-k-sorted-lists/solution/

**Comment by LC-Sue** [comment]
Hi @Devanshi512,
Thank you for sharing your concerns about approach 3. The approach is intended to be run in python 2 where it passes all test cases. That said, this article is quite old and it is scheduled to be improved in the future.
