### ISSUE TITLE
Vim editing mode Ctrl-D keybind incorrect

### ISSUE THREAD

**Issue by alasher** [LeetCode-Feedback/LeetCode-Feedback#50]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [ ] language
- [x] platform (other)

**Describe the bug**
When you press CTRL-D, on Vim the default action is to scroll downward, as described in the vim documentation [here](http://vimdoc.sourceforge.net/htmldoc/scroll.html). Instead it deletes the current line, which I assume is a popular keybind from a different IDE. Note that CTRL-U to scroll up *is* working, so all that should be necessary is un-binding this default keybind when Vim mode is enabled.

**what language is your code written in**
N/A

**Expected behavior**
The expectation is for the Vim cursor to scroll down some number of lines after pressing CTRL-D in Vim editing mode.

**Additional context**
I've had no other issues with the Vim editor for LeetCode.

**Comment by CooperCooperCooper** [comment]
Hi @alasher,
Thank you for reaching out to us. Please file this platform ticket to our support team for this kind of issue here: https://support.leetcode.com/hc/en-us. We appreciate your support and understanding.
