### ISSUE TITLE
1085. Sum of Digits in the Minimum Number – typo

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#500]
#### Your LeetCode username
metricquant

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The problem statement has a typo: `1 <= A[i].length <= 100` should read `1 <= A[i] <= 100`.

**Comment by CooperCooperCooper** [comment]
Hi @metricquant ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @metricquant ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
