### ISSUE TITLE
toString doesn't return a String - 3236 Fun With Arrays

### ISSUE THREAD

**Issue by camdenorrb** [LeetCode-Feedback/LeetCode-Feedback#5004]
https://leetcode.com/explore/learn/card/fun-with-arrays/521/introduction/3236/

![image](https://user-images.githubusercontent.com/5360339/136625294-aca4d657-726c-4b1c-b65b-36835f46ddb4.png)

This doesn't return a String

**Comment by LC-Sue** [comment]
Hi @camdenorrb 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
