### ISSUE TITLE
中国站点无法看到 Python2 完整的报错信息

### ISSUE THREAD

**Issue by harrisoff** [LeetCode-Feedback/LeetCode-Feedback#501]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言

**描述**
Python2 运行错误时，代码执行面板点击无法展开查看完整报错信息

**你使用的语言**
Python2

**你提交或者运行的代码**
```python2
// Two Sum
class Solution(object):
    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        # 对齐错误
      return 0
```

**期望行为**
点击能够展开错误详情

**屏幕截图**
![图片_20200618_221245](https://user-images.githubusercontent.com/29137942/85031207-fc17cc80-b1b0-11ea-976b-639b87e89d34.jpg)

作为对比，Python3 的报错是可以点击展开的：

![图片_20200618_221726](https://user-images.githubusercontent.com/29137942/85031670-8829f400-b1b1-11ea-8de8-671673e7205f.png)

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
很抱歉我们暂时无法重现这个问题出现的情况，建议尝试强制刷新浏览器试试。如有使用代理服务器，请尝试关闭所有代理规则，然后用浏览器的隐私模式再试试。

**Comment by harrisoff** [comment]
![图片_20200619_141313](https://user-images.githubusercontent.com/29137942/85102404-2e6c0d00-b237-11ea-85e3-071db58d5867.png)

**Comment by feiceh** [comment]
清除浏览器缓存也无效吗？我们看到截图的时间不是现在，如果当前依旧有问题的话，请提供一下浏览器信息，以便定位。

**Comment by harrisoff** [comment]
就是刚才截的。
windows 10
Chrome 83.0.4103.106

**Comment by feiceh** [comment]
嗯好的，技术初步判断可能是浏览器兼容性问题，我们会不断努力优化和提升我们的产品，给您带来的不便敬请谅解。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，我先备案关闭，后续使用中有问题，也可以通过提交工单（https://support.leetcode-cn.com/hc/request/guest/）反馈，感谢您的支持～

**Comment by harrisoff** [comment]
😎天哥让我来的

**Comment by feiceh** [comment]
嗯呢，这个问题我们攻城狮🦁️会定位的哈
