### ISSUE TITLE
Alien Dictionaty - Test case 101

### ISSUE THREAD

**Issue by jfrancis01** [LeetCode-Feedback/LeetCode-Feedback#5018]
["ac","ab","zc","zb"] - cycle?
It seems like ab -> zc, b comes before c
and zc -> zb, c -> before b.

**Comment by LC-WD** [comment]
Hi @jfrancis01,

Thank you for reaching out, could you please elaborate on the issue and the expected behavior.

**Comment by LC-Sue** [comment]
Hi @jfrancis01,

The expected output for this test case is correct. Please refer to this discuss post for clarification.
https://leetcode.com/problems/alien-dictionary/discuss/1366186/Help-can-anyone-tell-for-this-tetst-case-%22ac%22%22ab%22%22zc%22%22zb%22
