### ISSUE TITLE
Question - 2020. Number of Accounts That Did Not Stream

### ISSUE THREAD

**Issue by qinghaoh** [LeetCode-Feedback/LeetCode-Feedback#5019]
#### Your LeetCode username
qinghaoh

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Example 1, the name of the first Input table should be "Subscriptions", not "Subscription"

#### Code you used for Submit/Run operation

N/A

**Comment by LC-Sue** [comment]
Hi @qinghaoh,
Thank you for your time. We've used your feedback to update the problem.
