### ISSUE TITLE
894. All Possible Full Binary Trees – warning/disclaimer needed

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#502]
#### Your LeetCode username
metricquant

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

As a consequence of caching previously constructed trees of small size, many trees will show as subtrees in more than one tree, and sometimes in the same tree. For example, when N = 3, the left and right children of the root are the same tree of size N = 1. This is not a bug per se, but is still surprising. A small warning or disclaimer will not hurt.

#### Language used for code
C++

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @metricquant ,
Thanks for your time. The team has reviewed your report but decided not to make updates after internal discussion.
