### ISSUE TITLE
Missing Test Case - 1089. Duplicate Zeros

### ISSUE THREAD

**Issue by MadMods96** [LeetCode-Feedback/LeetCode-Feedback#5021]
#### Solution not working with right code
- [ ] Duplicate Zeros
- [ ] Solution outcome with wrong error 
- [ ] used javascript

#### Description of the bug
i have applied the code with my knowledge and i basically do in my own computer node compiler and on that i have make a solution for this program but unfortunately when i do same on your respective editor it comes with a wrong answer, please check this problem.

#### Code you used for Submit/Run operation

```
var duplicateZeros = function(arr) {
  var zero = [];
  var len = arr.length;
  var final = [];
    for(let i =0; i<len; i++){
        if(arr[i]===0){
            zero.push(0);
        }
    zero.push(arr[i]);
    }
    for(var j=0; j<=arr.length-1; j++){
      final.push(zero[j]);
    }
    return final;
};
```

#### Language used for code
Javascript

#### Expected behavior

it should come out with this [1, 0, 0, 2,3, 0, 0, 4] answer which is also working in my pc and online compilers too but at same time your editor shows [1,0,2,3,0,4,5,0] this answer i dont know why.. ?

**Comment by armandomendivil** [comment]
I have the same issue, this is my code and is running ok on my editor but it is nor running well on leetcode
```
 var duplicateZeros = function(arr) {
    const out = [];
    
    let i = 0;
    
    while(out.length < arr.length) {
        const num = arr[i];
        if (num === 0) {
            out.push(0);
        }
        
        out.push(num);
        
        i++;
    }
    
    return out;
};
```
