### ISSUE TITLE
Not all containers migrated to C# 9.0 / .NET 5

### ISSUE THREAD

**Issue by azabluda** [LeetCode-Feedback/LeetCode-Feedback#5024]
#### Your LeetCode username

leetmafia

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
LeetCode seems to support C# 9.0 / .NET 5 since recently, but every now and then it still executes the program in an old C# 8 environment. It usually takes a few attempt to finally spawn a net5 container to get your C# 9 program compile.

#### Code you used for Submit/Run operation

```cs
Console.WriteLine(System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription);
Console.WriteLine(System.Runtime.InteropServices.RuntimeInformation.OSDescription);
```

#### Language used for code

C#

#### Expected behavior

```
.NET 5.0.10
Linux 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021
```

#### Actual behavior (intermittent)

```
Mono 6.12.0.90 (tarball Fri Sep  4 14:02:38 UTC 2020)
Unix 5.4.0.73
```

#### Screenshots

Have to submit the same C# 9 program over and over again to finally get it accepted.

![image](https://user-images.githubusercontent.com/7567733/136699788-811d221e-f0bc-496b-9c6e-046c4b8d0c43.png)

![image](https://user-images.githubusercontent.com/7567733/136699860-d2c9e359-d316-43b2-af8e-90219f71106a.png)

**Comment by LC-WD** [comment]
Hi @azabluda,

Thank you for reaching out, the issue has been resolved now. Please do reach out if the issue persists in the future!
