### ISSUE TITLE
Missing Test Case - 819. Most Common Word

### ISSUE THREAD

**Issue by KartikeyRohila** [LeetCode-Feedback/LeetCode-Feedback#5029]
#### Your LeetCode username

Kartikey_1109

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This question runs on this test case :
```
"Bob hit a ball, the hit BALL flew far after it was hit."
["hit","ball"]
```
There are multiple words with same frequency in this paragraph and in question they said answer has to be unique, but this test case runs. It has to be an invalid test case.

#### Code you used for Submit/Run operation

```
class Solution
{
    public:
    string mostCommonWord(string s, vector<string>& banned)
    {
        unordered_set<string> ban_list;
        unordered_map<string,int> word;
        for (int i=0;i<banned.size();i++)
            ban_list.insert(banned[i]);
        
        string temp="";
        for (int i=0;i<s.size();i++)
        {
            if ('A'<=s[i] && s[i]<='Z')
                temp.push_back(tolower(s[i]));
            else if ('a'<=s[i] && s[i]<='z')
                temp.push_back(s[i]);
            else
            {
                if (temp!="" && ban_list.find(temp)==ban_list.end())
                    word[temp]++;
                temp="";
            }
        }
        if (temp!="" && ban_list.find(temp)==ban_list.end())
            word[temp]++;
        
        string ans="";
        int count=0;
        for (auto i=word.begin();i!=word.end();i++)
        {
            if (count<(i->second))
            {
                count=(i->second);
                ans=(i->first);
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
```
"Bob hit a ball, the hit BALL flew far after it was hit."
["hit","ball"]
```
In this test case there are words with higher frequencies are banned and rest all other words have same frequency. According to question the question answer has to be unique but in this type of test case there are multiple possible answers so this test case has to be invalid test case but it shows ```a``` as expected answer.
And this is not the only test case of this type. Every test case in which there are multiple words with highest frequency is possible, all those type of test cases treated as valid test case.

#### Screenshots
![Screenshot (262)](https://user-images.githubusercontent.com/69873345/136771757-dfe14b1c-d834-45f1-b1bb-e9f88c314667.png)

**Comment by LC-Sue** [comment]
Hi @KartikeyRohila,
Thank you for your time. We've used your feedback to update the problem!
