### ISSUE TITLE
125. Valid Palindrome - Insufficient test cases

### ISSUE THREAD

**Issue by oubenruing** [LeetCode-Feedback/LeetCode-Feedback#503]
#### Your LeetCode username

oubenruing

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Some answers used regular expressions that could not filter certain symbols (e.g. "_")
I think the solution missed some testcases.

#### Code you used for Submit/Run operation

```
function isPalindrome(s: string): boolean {
    const str = s.replace(/[^\w]/g, '').toLocaleLowerCase();
    let j = 0;
    for (let i = str.length; i >= 0; i--) {
        if (str[i - 1] !== str[j]) {
            return false
        }
        j++
    }
    return true;
}
```

#### Language used for code
Typescript

#### Expected behavior

The solution should not accept the above code.

#### Screenshots

![image](https://user-images.githubusercontent.com/22184435/85091798-e50dc480-b21a-11ea-89cc-2ecc80751407.png)

#### Additional context

Leetcode-cn.com has the same problem.

**Comment by CooperCooperCooper** [comment]
Hi @oubenruing ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @oubenruing 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
