### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by gaurvag** [LeetCode-Feedback/LeetCode-Feedback#5031]
#### Your LeetCode username
al0ma

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
The contraints in problem are:
   gas.length == n
   cost.length == n
  1 <= n <= 10^5
  0 <= gas[i], cost[i] <= 10^4
By them O(n^2) solution should not pass and result in TLE(Time Limit Exceeded), 
but O(n^2) solutions are easily able to pass all test cases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int canCompleteCircuit(vector<int>& gas, vector<int>& cost){
        int n=gas.size();
        vector<int> a(n);
        for(int i=0;i<n;i++)
            a[i]=gas[i]-cost[i];
        int fuel;
        for(int i = 0; i < n; i++){
            if(a[i]>=0){
                fuel=a[i];
                int j = (i + 1)%n;
                while(j != i){
                    fuel+=a[j];
                    if(fuel < 0) 
                        break;
                    j = (j + 1)%n;
                }
                if(j == i) 
                    return i;
            } 
        }
        return -1;        
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
It was able to pass all the test cases even after being a O(n^2) solution. 
But it should have got TLE according to the constraints.

#### Test Case for TLE in O(n^2) solutions:
[output.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7326922/output.txt)

#### Correct O(n) solution:
```
class Solution{
public:
  int canCompleteCircuit(vector<int> &gas, vector<int> &cost){
    int sum = 0;
    int n = gas.size();
    vector<int> a(n);
    for (int i = 0; i < n; i++){
      a[i] = gas[i] - cost[i];
      sum += a[i];
    }
    if (sum < 0)
      return -1;
    int currFuel = 0;
    int best = 0;
    for (int i = 0; i < n; ++i){
      currFuel += a[i];
      if (currFuel < 0){
        currFuel = 0;
        best = i + 1;
      }
    }
    return best;
  }
};
```

**Comment by LC-Shuwen** [comment]
Hi @gaurvag 
Thank you for reaching out to us and providing the test case. I've relayed this issue to our team to investigate.
