### ISSUE TITLE
Missing Test Case - 1710. Maximum Units on a Truck

### ISSUE THREAD

**Issue by terminhector84** [LeetCode-Feedback/LeetCode-Feedback#5033]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
test case has the wrong result

#### Code you used for Submit/Run operation

```
// Two Sum
var maximumUnits = function(boxTypes, truckSize) {
    let sum = 0;
    let tracker = 0;
    for(let k =0; k < boxTypes.length; k++){
        for(let i = 0; i < boxTypes[k][0]; i++){
            tracker += 1;
            if(tracker <= truckSize){
                sum = sum + boxTypes[k][1];
            }
        }
    }
    
    console.log(sum);
    return sum;
};
```

#### Language used for code
JavaScript

#### Expected behavior
this is wrong!!!!
Input
[[5,10],[2,5],[4,7],[3,9]]
10
Output
81
Expected
91

**Comment by LC-WD** [comment]
Hi @terminhector84 ,
The expected output for the test case is correct, please raise this issue in discussion for further clarification.
