### ISSUE TITLE
Missing Test Case - 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by arshappleid** [LeetCode-Feedback/LeetCode-Feedback#5035]
#### Your LeetCode username
arsh_appleid

Problem : This question, needs better description. I have the following code below, and it should technically return the right side of the tree. But the solution wants something different.

``` java
public List<Integer> rightSideView(TreeNode root) { 
        
        List<Integer> ans = new ArrayList<Integer>();
        if(root == null)
            return ans;
             
        TreeNode current = root;
        ans.add(root.val);
        
        while(current.right != null){            
            current = current.right;
           
            ans.add(current.val);
        }
        
        return ans;
    }

```

**Comment by LC-Sue** [comment]
Hi @arshappleid
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
