### ISSUE TITLE
Missing Test Case - 657. Robot Return to Origin

### ISSUE THREAD

**Issue by judabne** [LeetCode-Feedback/LeetCode-Feedback#5038]
#### Your LeetCode username
judabne

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug
After submitting a solution, I looked at the sample Java solution at 4ms. It seemed that one could trick it easily.
It uses one sum and it adds/subtracts to it 10 if the robot moves up/down, and 1 if it moves left/right. I tried a testcase of 
"DRRRRRRRRRR" on this sample code and it returned true (while the expected is false). I submitted the sample code and it passed all tests

#### Code you used for Submit/Run operation
```
// Robot Return to Origin
class Solution {
    public boolean judgeCircle(String moves) {
        int total = 0;
    for(char ch : moves.toCharArray()) {
      if(ch == 'L') {
        total = total - 1;
      }
      else if(ch == 'U') {
        total = total + 10;
      }
      else if(ch == 'R') {
        total = total + 1;
      }
      else if(ch == 'D') {
        total = total - 10;
      }
    }
    return total == 0;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The code above passes all the Leetcode testcases while it shouldn't
The testcase "DRRRRRRRRRR" is one where this code gives erroneous results

**Comment by LC-Sue** [comment]
Hi @judabne,
Thank you for your time. Our team has looked into the problem and concluded that the solution cannot be failed because we have an uncountable number of similar solutions that can be accepted and failing all of them is impossible.
