### ISSUE TITLE
162. Find Peak Element problem is repeated in the Explore/Learn/Binary Search card

### ISSUE THREAD

**Issue by aiwrapper** [LeetCode-Feedback/LeetCode-Feedback#5039]
162. Find Peak Element is present in both Template II and Template III sections:

https://leetcode.com/explore/learn/card/binary-search/126/template-ii/948/
https://leetcode.com/explore/learn/card/binary-search/135/template-iii/946/

Although it might be solved using both binary search templates, I would recommend replacing the second instance with another binary search problem.

For instance, it could be replaced by 300. Longest Increasing Subsequence:
https://leetcode.com/problems/longest-increasing-subsequence/

**Comment by LC-WD** [comment]
Hi @tensorflow-as-tf,

Thank you for your feedback, I have relayed this issue to our team for consideration.
