### ISSUE TITLE
1300 need a testcase

### ISSUE THREAD

**Issue by verzqli** [LeetCode-Feedback/LeetCode-Feedback#504]
#### Your LeetCode username
 verzqli 

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug
A test case is missing in question 1300, so the code that produces the wrong result can still be submitted successfully

#### Code you used for Submit/Run operation
this is the wrong code,but it can still be submitted successfully
```
// 1300. Sum of Mutated Array Closest to Target
class Solution {
    public int findBestValue(int[] arr, int target) {
    Arrays.sort(arr);
        int length =arr.length;
        int unUse =length;
        int sum = 0;
        int result=-1;
        for (int i = 0; i < arr.length; i++) {
            int average = (target - sum) / unUse;
            if (average <= arr[i]) {
                result = average;
                break;
            }
            sum += arr[i];
            unUse--;
        }
        if (result==-1){
            return arr[length-1];
        }
        int curAbs = Math.abs(sum+result*unUse-target);
        if (Math.abs(sum+(result+1)*unUse-target)<curAbs){
            return result+1;
        }
        return result;
    }
}
```
need add a testcase
[3,4,5,6]
18
#### Language used for code
java

#### output
input
[3,4,5,6]
18
output
5
Expected results
6

You can see that the output is wrong, but you can submit it successfully

**Comment by aguilera123** [comment]
Hi @verzqli 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @verzqli 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
