### ISSUE TITLE
Mistake in example solution - 374.Guess Number Higher or Lower

### ISSUE THREAD

**Issue by alas1n** [LeetCode-Feedback/LeetCode-Feedback#5041]
#### Your LeetCode username
username: alasin007

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a problem with solution 2 code (binary search) 

#### Code you used for Submit/Run operation

```
/* The guess API is defined in the parent class GuessGame.
   @param num, your guess
   @return -1 if my number is lower, 1 if my number is higher, otherwise return 0
      int guess(int num); */

public class Solution extends GuessGame {
    public int guessNumber(int n) {
        int low = 1;
        int high = n;
        while (low <= high) {
            int mid = low + (high - low) / 2;
            int res = guess(mid);
            if (res == 0)
                return mid;
            else if (res < 0)
                high = mid - 1;
            else
                low = mid + 1; 
        }
        return -1;
    }
}
```
here is the correct solution
```
/* The guess API is defined in the parent class GuessGame.
   @param num, your guess
   @return -1 if my number is lower, 1 if my number is higher, otherwise return 0
      int guess(int num); */

public class Solution extends GuessGame {
    public int guessNumber(int n) {
        int low = 1;
        int high = n;
        while (low <= high) {
            int mid = low + (high - low) / 2;
            int res = guess(mid);
            if (res == 0)
                return mid;
            else if (res < 0)
                low = mid + 1;  // change here 
            else
                high = mid -1;  // and change here 
        }
        return -1;
    }
}
```

#### Language used for code
java 

#### Expected behavior
Binary search approach need get closer to picked number step by step instead it goes up and just for some cases that guessed number is lower than picked number the answer is right

**Comment by LC-WD** [comment]
HI @alas1n,

Thank you for reaching out. The code you provided fails the test case, I have attached a screenshot for your reference
![Screen Shot 2021-10-12 at 5 08 25 PM](https://user-images.githubusercontent.com/92285126/137045542-2f0edf85-63d8-4b03-bf83-e2821048a5d4.png)
.
