### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by rustydigg918** [LeetCode-Feedback/LeetCode-Feedback#5046]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 162. Find Peak Element
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        left, right = 0, len(nums) - 1
        while left < right:
            mid = left + (right-left)//2
            if nums[right] > nums[right - 1]:
                return right
            else:
                right -=1
        return left
        
```

**Comment by LC-Sue** [comment]
Hi @,
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
