### ISSUE TITLE
Missing Test Case - 485. Max Consecutive Ones

### ISSUE THREAD

**Issue by edtechse** [LeetCode-Feedback/LeetCode-Feedback#5047]
#### Your LeetCode username
likhariinder

#### Category of the bug
- [ ] Question
- [ ] Solution
- [this ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I was thinking that we can have solution in different languages in array chapters. As of know, only java is being shown. I can help from C# perspective I think.

#### Code you used for Submit/Run operation

```
    public int FindMaxConsecutiveOnes(int[] nums) {
        int MaxOnes =0;
        int count = 0;
        foreach(int num in nums)
        {
            if(num == 1)
            {
                count++;
                if (MaxOnes < count)
                    MaxOnes = count;
            }
            else
            {
                count =0;
                
            }
        }
        return MaxOnes;
    }
```

#### Language used for code

C#

#### Expected behavior

The expected behaviour is that the samples you provide in the chapters can be made in different languages as well. There may be people who are not well versed in Java.

**Comment by LC-Sue** [comment]
Hi @edtechse,
Thank you for reaching out to us. I've relayed this suggestion over to our team for consideration.
