### ISSUE TITLE
Typo in the solution article - 279. Perfect Squares

### ISSUE THREAD

**Issue by miaachan** [LeetCode-Feedback/LeetCode-Feedback#5048]
#### Your LeetCode username

does it matter?

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Under **Approach 4: Greedy + BFS (Breadth-First Search) > Algorithm**, there is a pic visualizing the algorithm. And in step 2, element `3` should come from `7-4` instead of `7-1`.

#### Screenshots

![the-typo](https://leetcode.com/problems/perfect-squares/Figures/279/279_greedy_bfs.png)

**Comment by LC-Sue** [comment]
Hi @miaachan 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
