### ISSUE TITLE
Missing Test Case - 41. First Missing Positive

### ISSUE THREAD

**Issue by Harry-kp** [LeetCode-Feedback/LeetCode-Feedback#5049]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A  solution which is supposed to fail is accepted because some strong  test cases are missing.

#### Code you used for Submit/Run operation

```
// First Missing Positive
class Solution {
public:
    int firstMissingPositive(vector<int>& nums) {
        
        int ans = 1,n = nums.size();
        for(int j = 0;j<48;j++)
        for(int i = 0;i<n;i++){
            if(nums[i]>0 and nums[i] == ans)
                ans++;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should give wrong answer   but the solution got accepted.
For this test case:-
[50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1]
Expected Answer = 51
My Answer = 49

#### Additional context

Test case of the form  [n,n-1,n-2,n-3 ..... 1] where n =5 * 10^5 should be added. 
If a similar brute force solution is written for this test case , it will lead to O(n^2) complexity.Hence , gives TLE

**Comment by LC-Sue** [comment]
Hi @Harry-kp,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
