### ISSUE TITLE
Submission Issue Problem Jump Game problem no 55

### ISSUE THREAD

**Issue by faizhameed** [LeetCode-Feedback/LeetCode-Feedback#5054]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution for the problem https://leetcode.com/problems/jump-game
 This works in a test case when running normally that is when clicking on Run Code button, but this is giving wrong answer submission when submitting the solution for the **Same test case**

This is happening when input is `[0,1]` and the expected solution is false, but the output when submitting is true
see below screenshot

#### Code you used for Submit/Run operation

```
// Jump Game
const map = {};
var canJump = function (nums, index = 0) {
  if (map[index + 1]) {
    return true;
  } else if (map[index + 1] === false) {
    return false;
  }
  if (nums[index] === 0 && nums.length - 1 > index) {
    map[index + 1] = false;
    return false;
  }

  if (nums.length - 1 <= index) {
    map[index + 1] = true;
    return true;
  }
  let j = 1;
  while (j <= nums[index]) {
    if (canJump(nums, index + j)) {
      return true;
    }
    j++;
  }

  return false;
};
```

#### Expected behavior

The test case should be accepted 

#### Screenshots

![image](https://user-images.githubusercontent.com/41015883/137501620-23207cf6-2258-4b27-9905-e76a827d13be.png)

#### Additional context

I have made submissions several times, my submission success score for a medium solution is reduced with this many submissions.
I hope this gets resolved soon

**Comment by LC-Sue** [comment]
Hi @faizhameed 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
