### ISSUE TITLE
Typo in the solution article - 689. Maximum Sum of 3 Non-Overlapping Subarrays

### ISSUE THREAD

**Issue by Maximus5** [LeetCode-Feedback/LeetCode-Feedback#5057]
#### Your LeetCode username

conemu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution says

> From there, we approach the reduced problem: Given some array W and an integer k, what is the lexicographically smallest tuple of indices (i, j, l) with **_i + l <= j_** and j + k <= l that maximizes W[i] + W[j] + W[l]?

Instead of `i + l <= j` it should be `i + k <= j`. `j` should be greater than `i`, not `l`.

#### Screenshots

![image](https://user-images.githubusercontent.com/1222388/137586357-6c3e282d-dae2-4cf0-a088-9cbdff7c3c5f.png)

**Comment by LC-Sue** [comment]
Hi @Maximus5 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
