### ISSUE TITLE
1150. Check If a Number Is Majority Element in a Sorted Array

### ISSUE THREAD

**Issue by seth-orai** [LeetCode-Feedback/LeetCode-Feedback#506]
#### Your LeetCode username

seth-orai

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

My solution to the problem has been accepted. The solution I have written do not account for all the actual test cases. So, the question has very weak test cases. Actually, my code assumes that a majority element always exists, but it is not so with respect to the question. Even after AC, I checked by giving my own test case. As expected, my solution do not match the expected solution.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isMajorityElement(vector<int>& nums, int target) {
        int n = nums.size(), low=0, high=n-1;
        if(target<nums[0] || target>nums[n-1])  return false;
        
        if(n%2 && nums[n/2]==target) return true;
        if(n%2==0 && nums[n/2]==target && nums[n/2-1]==target) return true;
        
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My solution, which assumes majority element surely existing should not have been accepted. So, further test cases must be added which reject the similar solutions as of mine. 

#### Screenshots

![Accepted-But-Wrong](https://user-images.githubusercontent.com/52034084/85126681-97f61680-b24b-11ea-8f1f-27c4c4df7248.JPG)

#### Additional context

Add the test cases such as nums = [1,2,3,4,5], target = 3, where it should fail because this will ensure that the user do not pre assume that the majority element always exists. The lists of test cases which should be added based on my concept can be very long, but adding two or three test cases will ensure the correctness. One more test case, which can be added : nums = [1,1,3,3,5,5], target = 3.

**Comment by aguilera123** [comment]
Hi @seth-orai 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @seth-orai 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
