### ISSUE TITLE
Leetcode 139. Word Break - Approach 2: Recursion with memoization 

### ISSUE THREAD

**Issue by PRL-GIT** [LeetCode-Feedback/LeetCode-Feedback#5060]
The solution in Python for Approach 2: Recursion with memoization. Has missing the Mem list/array

**Comment by LC-Sue** [comment]
Hi @PRL-GIT 
Thank you for your feedback. This is a common misconception. The "Mem list/array" you are referring to is handled automatically by the @lru_cache decorator. This is a nifty way to handle memoization with one line in python. To see the effects of this line, you can try submitting without the decorator and the same code will get TLE.

**Comment by PRL-GIT** [comment]
Thank you for getting back to me. Great to learn something new. Should we enhanve the code to include "from functools import lru_cache"

**Comment by LC-Sue** [comment]
Hi @PRL-GIT,
Thank you for the feedback, we will consider this when the article gets updated!
