### ISSUE TITLE
Misleading default code in Python 3 - 101. Symmetric Tree

### ISSUE THREAD

**Issue by im-pro-at** [LeetCode-Feedback/LeetCode-Feedback#5063]
#### Your LeetCode username
pknoe3lh

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the Question it is stated that there will be 1 to 1000 nodes for the test cases.
But the stadart function declaration for Python 3 is:
`def isSymmetric(self, root: Optional[TreeNode]) -> bool:`
Therefore an empty tree is expacted!

#### Language used for code
Python 3

#### Expected behavior
The default code should be:
`def isSymmetric(self, root: TreeNode) -> bool:`

**Comment by LC-Sue** [comment]
Hi @im-pro-at 
Thank you for your time. Our team has decided not the fix the issue because of the way we have things set. We appreciate your feedback and thank you for your support.
