### ISSUE TITLE
1258. Synonymous Sentences – incorrect constraint

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#507]
#### Your LeetCode username
metricquant

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The constraint `synonyms[0] != synonyms[1]` means that the first pair of synonyms is different from the second. Most probably, the intention was to say that for each constraint pair, the first word is different from the second.

#### Expected behavior
A possible correction: `synonyms[i][0] != synonyms[i][1]`.

**Comment by CooperCooperCooper** [comment]
Hi @metricquant ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
