### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by ngeldvis** [LeetCode-Feedback/LeetCode-Feedback#5071]
#### Your LeetCode username

ngeldvis

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A common solution to this problem is to let each letter have a different prime number associated with it and then multiply all the letter's primes in the word to get a unique number for a given list of characters. If you add the prime numbers instead of multiplying them then the solution actually still passes (see code for solution that passes) but in reality that's not how prime numbers work. 
For example, the input 'dw' and 'ev'. if each letter of the alphabet corresponding to the first 26 prime numbers, for both strings we would get the number 90 meaning the function returns True even though its obviously false.

#### Code you used for Submit/Run operation

```py3
class Solution(object):
    def isAnagram(self, s, t):
        if len(s) != len(t):
            return False
        
        a = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101]
        
        sval = 0
        tval = 0
        
        for char in s:
            sval += a[(ord(char) - ord('a'))]
        
        for char in t:
            tval += a[(ord(char) - ord('a'))]
            
        return sval == tval
```

#### Language used for code

Python/Python3

#### Expected behavior

The code should not be accepted

**Comment by LC-Sue** [comment]
Hi @ngeldvis 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
