### ISSUE TITLE
DFS - Template II error

### ISSUE THREAD

**Issue by JamesKPolk** [LeetCode-Feedback/LeetCode-Feedback#5072]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The variable naming in DFS Template II is wrong.
See this page: https://leetcode.com/explore/learn/card/queue-stack/232/practical-application-stack/1385/ .

The while loop has this condition
```
while (s is not empty) {
```

but earlier in the pseudocode, the Stack<Node> is named stack, not s.

#### Language used for code

Java Pseudocode

#### Expected behavior

The variable should be named consistently throughout the code.

**Comment by LC-Sue** [comment]
Hi @JamesKPolk 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
