### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by DipakPatilNtnx** [LeetCode-Feedback/LeetCode-Feedback#5077]
#### Your LeetCode username

dipakpatil804

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is some bug in the execution of the code when I submit.
I found this problem while testing input [0]. 
I am getting the expected output of true when I run the code for the custom test case.
But when I submit it, it is returning output as false 

#### Code you used for Submit/Run operation

```
// Validate Binary Search Tree
var lastNode *TreeNode
func isValidBST(root *TreeNode) bool {
    if root != nil {
        if !isValidBST(root.Left) {
            return false
        }
        if lastNode == nil {
            lastNode = root
        } else if lastNode.Val >= root.Val {
            return false
        } else {
            lastNode = root
        }
        if !isValidBST(root.Right){
            return false
        }
    }
    return true
}
```

#### Language used for code

go

#### Expected behavior

There should be the same output for running custom test case and submit

#### Screenshots

<img width="973" alt="Screen Shot 2021-10-20 at 11 50 56 AM" src="https://user-images.githubusercontent.com/58721914/138039260-134a741c-f1ab-4c13-917c-34b00cd2d1d7.png">
<img width="993" alt="Screen Shot 2021-10-20 at 11 51 07 AM" src="https://user-images.githubusercontent.com/58721914/138039296-f781a21b-4283-42dc-b490-48d38c2dc979.png">

**Comment by LC-Sue** [comment]
Hi @DipakPatilNtnx,
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
