### ISSUE TITLE
Merge Sorted Array accept wrong solution

### ISSUE THREAD

**Issue by Monk3yDev** [LeetCode-Feedback/LeetCode-Feedback#508]
#### Your LeetCode username

user4656CP

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Merge Sorted Array question accept solution which does not return correct data for current inputs:

Input:
nums1 = [0,0,0,0,0,0], m = 0
nums2 = [2,5,6],         n = 3

Output: [2,5,6,0,0,0]

#### Code you used for Submit/Run operation
```
// Two Sum
class Solution {
    fun merge(nums1: IntArray, m: Int, nums2: IntArray, n: Int): Unit {
       var num1Index = m
       var num2Index = 0
       while (num1Index < nums1.size && num2Index < n) {
           nums1[num1Index++] = nums2[num2Index++]
       }
       nums1.sort()
    }
}
```

#### Language used for code
Kotlin

#### Expected behavior

Solution should not be accepted.

#### Screenshots

![wrong_answer](https://user-images.githubusercontent.com/8431461/85183969-34d9a380-b28e-11ea-99b5-7a446e11ffb9.PNG)

**Comment by CooperCooperCooper** [comment]
Hi @Monk3yDev ,
Thank you for reaching out to us. I tested your code on our end just now and got "Wrong Answer" for this test case. Please check out the screenshot attached for this run and test it again on your end. 

Note: Run Code stores the run in the local machine, while Submit stores the code in LeetCode system. So please make sure to clear your bowser cache and cookies before testing the code again.

**Comment by Monk3yDev** [comment]
Hi,

I tested it again on 3 different browsers (Google Chrome, Firefox, Microsoft Edge) with the clearing cache and cookies before runing code.  Result is same "Run Code" and "Submit" is accepted.

![Przechwytywanie](https://user-images.githubusercontent.com/8431461/85618669-67561880-b661-11ea-9c54-b2e2a9fcf196.PNG)

![Przechwytywanie2](https://user-images.githubusercontent.com/8431461/85619335-6d002e00-b662-11ea-9e97-f2e31692b058.PNG)

Could you check on your side what is the effect of the submitting solution?

**Comment by lc-kate** [comment]
Hi @Monk3yDev ,
Thank you for your answer. Interesting, I've filed this issue to our team to take a deeper look.

**Comment by lc-kate** [comment]
Hi @Monk3yDev ,
Thank you for your time. We've fixed the issue by updating the problem constraint and statement. We did not add the contributed test case because it will break the official solution. We appreciate your support.
