### ISSUE TITLE
Missing Test Case - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by danghuyentram** [LeetCode-Feedback/LeetCode-Feedback#5080]
#### Category of the bug
- [ ] Wrong Test Cases : 

#### Description of the bug
Input: 
[1,2]
2
Output:
[1]
Expected:
[2] !

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @danghuyentram,
Thank you for reaching out, could you provide the code that you submitted for this problem?

**Comment by LC-Sue** [comment]
Hi @danghuyentram 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
