### ISSUE TITLE
Intermittent TLE for example use cases - 837. New 21 Game

### ISSUE THREAD

**Issue by cosminci** [LeetCode-Feedback/LeetCode-Feedback#5083]
#### Your LeetCode username
cosminci

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
When running the code on the first example [10, 1, 10], it sometimes executes instantly, and sometimes it TLEs. It sounds like the runtime for Scala solutions is not set correctly.

#### Code you used for Submit/Run operation
```
  def new21Game(n: Int, k: Int, w: Int): Double = {
    if (k == 0 || n >= k + w) return 1.0

    val probabilities = 1.0 +: Array.fill(n)(0.0)

    (1 to n).foldLeft(1.0) { case (wSum, i) =>
      probabilities.update(i, wSum / w)
      wSum +
        Option.when(i < k)(probabilities(i)).getOrElse(0.0) -
        Option.when(i - w >= 0)(probabilities(i - w)).getOrElse(0.0)
    }

    probabilities.slice(k, probabilities.length).sum
  }
```

#### Language used for code
Scala

#### Expected behavior
No TLE

#### Screenshots
Running the code on just the first example input [10, 1, 10]:
TLE: https://imgur.com/a/1EaKv9c
Success: https://imgur.com/Pqi2nzn

#### Additional context
https://leetcode.com/submissions/detail/574516699/

**Comment by LC-Sue** [comment]
Hi @cosminci,
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by cosminci** [comment]
The problem somtimes TLEs even when returning a constant... 

<img width="526" alt="Screenshot 2021-10-21 at 16 58 32" src="https://user-images.githubusercontent.com/16399135/138293070-2f482f70-8cbe-4ddb-996d-c5ba3140d4e9.png">
