### ISSUE TITLE
Missing Test Case - 704. Binary Search

### ISSUE THREAD

**Issue by AtulTakekarManulife** [LeetCode-Feedback/LeetCode-Feedback#5084]
#### Your LeetCode username
takekaratul 

#### Category of the bug
- [x ] Missing Test Cases 

#### Description of the bug
 Interger overflow while adding two int to get mid 

#### Code you used for Submit/Run operation

```
//Binary Serach
class Solution {
    public int search(int[] nums, int target) {
        int start = 0;
        int end = nums.length-1;
        
        while(start<=end){
            int mid = (int)((start + end) / 2); // This line should cause issue if the correct test is used
            int midNum = nums[mid];
            if( midNum== target)
                return mid;
            if(midNum > target)
                end = mid-1;
            else
                start = mid+1;
        }
        
        return -1;
    }
}
```

#### Language used for code
Java 

#### Expected behavior
The Integer overflow should cause problem in the code result.

**Comment by LC-Sue** [comment]
Hi @AtulTakekarManulife,
I ran the code for the problem and it doesn't seem to have any issue, could you provide more detail?

**Comment by LC-Sue** [comment]
Hi @AtulTakekarManulife 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
