### ISSUE TITLE
Incorrect Time Complexity - 380. Insert Delete GetRandom O(1)

### ISSUE THREAD

**Issue by u2agarwal99** [LeetCode-Feedback/LeetCode-Feedback#5087]
#### Your LeetCode username
u2agarwal99

#### Category of the bug
- [ 1] Question

#### Description of the bug
Random choice from collection of items should be an O(log n) operation. Coming up with a random index or the like takes computing log n random bits.

#### Code you used for Submit/Run operation

N/A, bug in question:
```
class RandomizedSet:

	def __init__(self):
		# Store values in list and (value -> index in list) in dict
		self._val_to_ind = {}
		self._list = []

	def insert(self, val: int) -> bool:
		if val in self._val_to_ind:
			return False
		# add val to dict and end of list
		self._val_to_ind[val] = len(self._list)
		# amortized O(1)
		self._list.append(val)
		return True


	def remove(self, val: int) -> bool:
		if val in self._val_to_ind:
			# val is not last element
			if self._list[-1]!=val:
				# Remove val from dict and get index of val in list
				ind = self._val_to_ind.pop(val)

				# replace val with last element of list
				self._list[ind] = self._list.pop()
				# update this last element's index in dict
				self._val_to_ind[self._list[ind]] = ind
			# last element is val
			else:
				del self._val_to_ind[val]
				self._list.pop()
			return True
		return False


	def getRandom(self) -> int:
		# Should be O(log n) because of how random index is generated (each bit in n-1 randomly generated)
		return random.choice(self._list)
```

#### Language used for code
Python

#### Expected behavior
N/A: Code Passes

#### Screenshots
N/A

#### Additional context
In Python's random.choice for example pythons randbelow is called which intern calls getrandbits. log n of these bits are generated to get an index.

**Comment by LC-Sue** [comment]
Hi @u2agarwal99 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
