### ISSUE TITLE
Problem: 852 Peak index in a mountain array

### ISSUE THREAD

**Issue by vraj152** [LeetCode-Feedback/LeetCode-Feedback#509]
![Screenshot (132)](https://user-images.githubusercontent.com/26855296/85189076-76ac1f00-b279-11ea-832c-5e8550740464.png)

#### Your LeetCode username

vs152

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
Question

#### Description of the bug

In note it's mentioned that all the valid cases will have length of at least 3, but it allows me to feed array with length 2 as we can see in ss attached.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Python3

**Comment by CooperCooperCooper** [comment]
Hi @vraj152 ,
Thank you for reaching out to us. The screenshot you've provided us had results from code in Python3, which is different from the code and language you're sharing with us. Would you please share both code and screenshots of both results?

**Comment by lc-kate** [comment]
Hi @vraj152 ,

Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag @lc-christina in a new comment. Thank you.
