### ISSUE TITLE
Missing Test Case - 2016. Maximum Difference Between Increasing Elements

### ISSUE THREAD

**Issue by Jaihogggggg** [LeetCode-Feedback/LeetCode-Feedback#5090]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Jaihogggggg,
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
