### ISSUE TITLE
Wrong description - 381. Insert Delete GetRandom O(1) - Duplicates allowed

### ISSUE THREAD

**Issue by dajavax** [LeetCode-Feedback/LeetCode-Feedback#5092]
#### Your LeetCode username
dajavax

#### Category of the bug
- [✓] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem mentions:

>  `bool insert(int val)` Inserts an item `val` into the multiset **if not present**.

However it expects to insert it even if it is present. As the title says "Duplicates allowed", also the test cases support this.

**Comment by LC-Sue** [comment]
Hi @dajavax 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @dajavax 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
