### ISSUE TITLE
Typo in solution for Network Delay Time

### ISSUE THREAD

**Issue by CrownKira** [LeetCode-Feedback/LeetCode-Feedback#5098]
#### Your LeetCode username

CrownKira

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/network-delay-time/solution/

There is a  typo under approach 2 

> Time Complexity: O(N^2 + E)m where EEE is the length of times in the basic implementation,...

#### Expected behavior

`m` should be should be a `,` instead.

#### Screenshots

<img width="542" alt="Screenshot 2021-10-22 at 1 09 20 PM" src="https://user-images.githubusercontent.com/24221801/138396537-ce588687-81ab-4d62-b3fd-0b91a7497497.png">

**Comment by LC-Sue** [comment]
Hi @CrownKira
Thank you for your feedback. The problem has been updated. We appreciate your support!
