### ISSUE TITLE
Issue with "Run Code" and "Submission" 

### ISSUE THREAD

**Issue by SkandaB** [LeetCode-Feedback/LeetCode-Feedback#51]
## Resolution found

The return type was changed sometime within the last 6 months, but is **NOT** mentioned anywhere on the question.
Please mention it clearly.

-----

**What kind of the bug**
- [x] problem
- [ ] solution
- [x] language

**Describe the bug**
https://leetcode.com/problems/sort-an-array/
Cannot execute test case _locally_ or via _submission_
Did someone change the driver code on the back-end?
I also _Reset_ my code, refreshed page. But that did not help either.

**what language is your code written in**
Java

**The code you submit/run**
```
/*
    Implementing the Quick3Way Sort function to handle cases where there are duplicate values
*/

class Solution {
    public int[] sortArray(int[] nums) {
        int length = nums.length;
        quick3Way(nums, 0, length - 1);
        return nums;
    }
    
    // Recursive function
    private void quick3Way(int[] nums, int lo, int hi) {
        if(hi <= lo)
            return;
        
        int lt = lo;            // end of left sub-array
        int i = lo + 1;         // Current element pointer
        int gt = hi;            // start of right sub-array
        int pt = nums[lo];      // Pivot key
        
        while(gt >= i) {        // Until pointers cross, i.e. we have unseen elements
            // System.out.println("\n\n" + Arrays.toString(nums));
            // System.out.println("lo: " + lo + "\tlt: " + lt +  "\ti: " + i + "\t\tgt: " + gt + "\thi: " + hi);
            if(nums[i] < pt)
                exch(nums, lt++, i++);  // Put current element into left-subarray, incr both pointers
            
            else if(nums[i] > pt)
                exch(nums, gt--, i);    // Put current element into right-subarray, decr gt pointer
            
            else
                i++;                    // Move to next unseen value
        }
        // System.out.println("End of while");
        quick3Way(nums, lo, lt - 1);
        quick3Way(nums, gt + 1, hi);
    }
    
    private void exch(int[] nums, int i, int j) {
        int temp = nums[i];
        nums[i] = nums[j];
        nums[j] = temp;
    }
}
```

**Expected behavior**
Test case runs.

**Screenshots**
![image](https://user-images.githubusercontent.com/5369621/77030065-bbfb4080-695a-11ea-8d86-1d920c8ec01d.png)

**Additional context**
This used to execute properly eariler.

**Comment by CooperCooperCooper** [comment]
Hi @SkandaB,
Thank you for raising this issue to our attention! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @SkandaB,
Thank you for your time! We've fixed this issue and your code is now successfully accepted.

**Comment by SkandaB** [comment]
Thanks!
I can see the change too.
