### ISSUE TITLE
1044. Longest Duplicate Substring Test Case Problem

### ISSUE THREAD

**Issue by watsonjia** [LeetCode-Feedback/LeetCode-Feedback#510]
#### Your LeetCode username

watsonjia

#### Category of the bug
- [ ] Question
- [ X ] Solution
- [ ] Language

#### Description of the bug

For test case "iuiielmwbuhncfgvnsnwwcnzgbuylf..." the reference solution lists "hmrgp" as the correct answer, which is a substring of length 5 which appears twice in the test case. However there is another possible duplicate substring "luqvg" of length 5 which also appears twice.

#### Code you used for Submit/Run operation

```
// Longest Duplicate Substring
import java.math.BigInteger;

class Solution {
    public String longestDupSubstring(String S) {
        int Slen = S.length();
        if (Slen == 2) return S.charAt(0) == S.charAt(1) ? S.substring(0,1) : "";
        
        int lo = 0;
        int hi = Slen-1;
        String champion = "";
        
        while (lo <= hi) {
            int len = (lo+hi) / 2;
            
            String result = search(S, len);
            
            if (result.length() > 0) {
                lo = len + 1;
                champion = result;
            }
            else {
                hi = len - 1;
            }
        }
        
        return champion;
    }
    
    private String search(String S, int len) {
        if (len == 0) return "";
        int R = 26;
        long prime = BigInteger.probablePrime(31, new Random()).longValue();
        long RM = 1;
        for (int i = 1; i <= len-1; i++) {
            RM = (R * RM) % prime;
        }
        long h = 0;
        for (int i = 0; i < len; i++) {
            h = (h * R + (S.charAt(i)-'a')) % prime;
        }
        
        Set<Long> hash = new HashSet<Long>();
        hash.add(h);
        
        for (int i = len; i < S.length(); i++) {
            h = (h + prime - (S.charAt(i-len)-'a')*RM % prime) % prime;
            h = (h*R + (S.charAt(i)-'a')) % prime; 
            
            int offset = i - len + 1;
            if (hash.contains(h)) return S.substring(offset, offset+len);
            hash.add(h);
        }
        
        return "";
    }
}
```

#### Language used for code

Java

#### Expected behavior

The substring "luqvg" should have also been accepted as a solution.

**Comment by aguilera123** [comment]
Hi @watsonjia 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @watsonjia 
Your code received AC when running test case "iuiielmwbuhncfgvnsnwwcnzgbuylf...", which is the expected outcome. Can you please test on your end and let us know if that is not the case?

**Comment by lc-christina** [comment]
Hi @watsonjia 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
