### ISSUE TITLE
Missing Test Case - 451. Sort Characters By Frequency

### ISSUE THREAD

**Issue by CDCOSINE** [LeetCode-Feedback/LeetCode-Feedback#5100]
#### Your LeetCode username
cdcosine13

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Partial output (only first 52 unique characters sorted by frequency) is passing, which should not be the case. I have sorted the custom element array with frequency, but in solution string, I only took first 52 elements in the array instead of total 62 possible elements. Expected was to fail a case with more than 52 unique elements. Possibly there is no case with more than 53 unique elements. Due to this above mention code was passing. It should be upto 62 digits.

#### Failed Case

Input String: "AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz0011223344556677889"

#### Code you used for Submit/Run operation
```
class ele{
    
    public:
    char ch;
    int freq = 0;
    
};

bool comp(ele a, ele b)
{
    return a.freq > b.freq;
}

class Solution {
public:
    string frequencySort(string s) {
        
        
        ele * ele_arr = new ele[62];
        
        for(char ch:s)
        {
            
            if(ch >= 'a'){
                
                ele_arr[(ch-'a')].ch = ch;
                ele_arr[(ch-'a')].freq = ele_arr[(ch-'a')].freq+1;
            }
            
            else if(ch>='A'){
                
                ele_arr[26+(ch-'A')].ch = ch;
                ele_arr[26+(ch-'A')].freq = ele_arr[26+(ch-'A')].freq+1;
            }
            else{
                
                ele_arr[52+(ch-'0')].ch = ch;
                ele_arr[52+(ch-'0')].freq = ele_arr[52+(ch-'0')].freq+1;
            }
        }
        
        sort(ele_arr,ele_arr+62,comp);
        
        s = "";
        
        //  It should be 62 for all uppercase, lowercase and digits but passing with 52 only with current test cases,
       // However i attached a screenshot of possible case where it fails.
        for(int i=0;i<52;i++)
        {
            int k = ele_arr[i].freq;
            
            while(k>0)
            {
                s += ele_arr[i].ch;
                k--;
            }
        }
        
        return s;
    }
};
```

#### Expected behavior
I have sorted the custom element array with frequency, but in solution string, I only took first 52 elements in the array instead of total 62 possible elements. Expected was to fail a case with more than 52 unique elements. Possibly there is no case with more than 53 unique elements. Due to this above mention code was passing. It should be upto 62 digits.

#### Screenshots
[Failed Case](https://drive.google.com/file/d/1UooC3HmF4nKU-_P2zQT7cRlQ-AzC3ebY/view?usp=sharing)
[Code passing](https://drive.google.com/file/d/1IEKRwEeUYgM6WRT_gAOgU40723QCXWep/view?usp=sharing)

**Comment by LC-Sue** [comment]
Hi @CDCOSINE 
Thank you for reaching out. Could you please provide the test case that failed?
