### ISSUE TITLE
Missing Test Case - 1504. Count Submatrices With All Ones

### ISSUE THREAD

**Issue by akshitm169** [LeetCode-Feedback/LeetCode-Feedback#5103]
#### Your LeetCode username
akshitm16

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
Max test case is missing for the problem- 1504. Count Submatrices With All Ones. My O(n^2 * m^2) solution gets accepted which ideally should not have passed.

#### Code you used for Submit/Run operation

```
# Let's try first O(n^4) solution
class Solution:
    def numSubmat(self, mat: List[List[int]]) -> int:
        n=len(mat)
        m=len(mat[0])
        up=[[0 for i in range(m)] for j in range(n)]
        left=[[0 for i in range(m)] for j in range(n)]
        for i in range(n):
            for j in range(m):
                if mat[i][j]:
                    up[i][j]=up[i-1][j]+1
                    left[i][j]=left[i][j-1]+1
        
        ans=0
        for i in range(n):
            for j in range(m):
                for k in range(left[i][j]):
                    x1,y1=i,j-k
                    for q in range(up[x1][y1]):
                        x2,y2=i-q,j
                        if left[x2][y2]>=k:
                            ans+=1
                        else:
                            break
        return ans
```

#### Language used for code

Python3

#### Expected behavior
I expected it to TLE since my solution is O(n^2 * m^2) but it passed all test cases.

#### Additional context

Max test case where it should TLE
[output.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7401085/output.txt)

**Comment by LC-Sue** [comment]
Hi @akshitm169 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
