### ISSUE TITLE
578. Get Highest Answer Rate Question (SQL Question)

### ISSUE THREAD

**Issue by ukeerthi** [LeetCode-Feedback/LeetCode-Feedback#5106]
The question shows table name as SurveyLog but the error shows that the table name is Candidates. When I changed the table name to Candidates, it said that the primary key "id" has duplicates. I don't see anything about this in the Discussion board either. In fact, other posts show a different table name "survey_log". 

![image](https://user-images.githubusercontent.com/5567656/138537387-76e78278-333e-473d-8a2e-c5a7b6a551d6.png)
![image](https://user-images.githubusercontent.com/5567656/138537395-0d8700c5-ed32-4f86-bc8e-888b7a0aa585.png)

**Comment by LC-Sue** [comment]
Hi @ukeerthi,
Thank you for your time. We'd like to reward you for this contribution. Could you please provide your LeetCode username?

**Comment by ukeerthi** [comment]
Hi @LC-Sue, it's mabyn

**Comment by LC-Sue** [comment]
Hi @ukeerthi 
Thank you for your time. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
