### ISSUE TITLE
Incorrect test case #332

### ISSUE THREAD

**Issue by kaiwangx** [LeetCode-Feedback/LeetCode-Feedback#5109]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ *] Missing Test Cases 

#### Description of the bug

For test case: [["JFK","SFO"],["SFO","ATL"],["SFO","BOS"],["SFO","LHR"],["ATL","BOS"],["BOS","LHR"],["LHR","BOS"],["BOS","ATL"]], the expected answer ["JFK","SFO","LHR","BOS","ATL","BOS","LHR","BOS","ATL"] is impossible since ["LHR","BOS"] can only be used once

#### Code you used for Submit/Run operation

```
class Solution:
    def findItinerary(self, tickets: List[List[str]]) -> List[str]:
        used = [0 for t in tickets]
        depth = 0

        ticket_dic = {}
        itinerary = ['JFK']

        for idx, t in enumerate(tickets):
            src, dest = t[0], t[1]
            if src in ticket_dic:
                ticket_dic[src].append((dest, idx))
            else:
                ticket_dic[src] = [(dest, idx)]

        for k in ticket_dic:
            ticket_dic[k].sort()

        def dfs(cur_depth, idx, src):
            itinerary.append(src)
            
            if cur_depth == len(tickets):
                return True

            used[idx] = 1
            res = False
            for (next_dest, next_idx) in ticket_dic.get(src, []):

                if not used[next_idx] and dfs(cur_depth + 1, next_idx, next_dest):
                    res = True

            if not res:
                used[idx] = 0
                itinerary.pop()

            return res

        for (dest, idx) in ticket_dic['JFK']:
            if dfs(1, idx, dest):
                return itinerary
```

**Comment by LC-Sue** [comment]
Hi @kaiwangx 
Thank you for your time. We've used your feedback to update the problem. Could you please provide your LeetCode username so we could reward your account?

**Comment by kaiwangx** [comment]
Sure, my username is badwomanxx, thanks for the reward

**Comment by LC-Sue** [comment]
Hi @kaiwangx 
Thank you for providing your username. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
