### ISSUE TITLE
445. Add Two Numbers II

### ISSUE THREAD

**Issue by Sibu08** [LeetCode-Feedback/LeetCode-Feedback#511]
#### Your LeetCode username 
Sibam

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [X] Test Case

#### Description of the bug

The expected output was different from the judger's output. Wrong solutions may get accepted because of that missed testcase.Meanwhile my solution got accepted but its not the correct solution.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def addTwoNumbers(self, l1, l2):
        """
        :type l1: ListNode
        :type l2: ListNode
        :rtype: ListNode
        """
        num1 = 0
        num2 = 0
        while l1:
            num1 = num1*10 + l1.val
            l1 = l1.next
        while l2:
            num2 = num2*10 + l2.val
            l2 = l2.next
        num1 += num2
        l1 = ListNode(0)
        if num1 == 0:
            return l1
        while num1 > 0:
            newNode = ListNode(num1 % 10)
            newNode.next = l1.next
            l1.next = newNode
            num1 = num1//10
        return l1.next
```

#### Language used for code
Python

#### Expected behavior

Input:
[-1]
[-1]
Output:
[-2]
The Output Should be -2 but my code gives 0 and still it got accepted.

**Comment by CooperCooperCooper** [comment]
Hi @Sibu08 ,
Thank you for reaching out to us. I tested your code with this input on our end, but receive Wrong Answer (please see the screenshot attached for more information). Would you please try to run this again on your end and share the new result with us?

Note: Run Code stores results on your local machine while Submit stores the submission on LeetCode system. Therefore, it would be helpful if you can clear your browser cache and cookies before testing the code and input again.
<img width="924" alt="Screen Shot 2020-06-23 at 3 23 22 PM" src="https://user-images.githubusercontent.com/59751300/85471782-cd5d7580-b565-11ea-9044-40a189473b91.png">

**Comment by Sibu08** [comment]
@lc-kate yes, it shows wrong answer but submit the code. It got accepted (which shouldn't happen).
So Please add this testcase.

**Comment by lc-kate** [comment]
Hi @Sibu08 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @Sibu08 ,
Thank you for your time. The test case is not valid because the link lists are "representing two non-negative integers". We appreciate your support.
