### ISSUE TITLE
116. Populating Next Right Pointers in Each Node - Condition mentioned for while loop incorrect in solution

### ISSUE THREAD

**Issue by agrawalarpit74** [LeetCode-Feedback/LeetCode-Feedback#5114]
#### Your LeetCode username
agrawalarpit74

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Code written for  *Approach 2: Using previously established next pointers* have incorrect code at 3rd point

#### Code you used for Submit/Run operation
NA

#### Language used for code
NA

#### Expected behavior
```
 leftmost = root
 while (leftmost.left != null)
 {
     head = leftmost
     while (head!= null)
     {
         1) Establish Connection 1
         2) Establish Connection 2 using next pointers
         head = head.next
     }
     leftmost = leftmost.left
 }
```

But it is
```
 leftmost = root
 while (leftmost.left != null)
 {
     head = leftmost
     while (head.next!= null)
     {
         1) Establish Connection 1
         2) Establish Connection 2 using next pointers
         head = head.next
     }
     leftmost = leftmost.left
 }
```

head.next should not be their in article.
Note

#### Additional context
Java code written in code editor is correct.It just code in article is incorrect

**Comment by LC-Sue** [comment]
Hi @agrawalarpit74 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
