### ISSUE TITLE
Error in "Array Insertions" section.

### ISSUE THREAD

**Issue by GeorgeT59** [LeetCode-Feedback/LeetCode-Feedback#5115]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On this page: https://leetcode.com/explore/learn/card/fun-with-arrays/525/inserting-items-into-an-array/3244/

The first example; this line of code doesn't run:
```int intArray = new int[6];```

It's missing the extra brackets - it should look like this: ```int [] intArray = new int [6];```

#### Language used for code

Java

#### Expected behavior

Copy & Ran the code provided in the example #1; realized there's no beginning brackets.

**Comment by LC-Sue** [comment]
Hi @GeorgeT59 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
