### ISSUE TITLE
Missing Tag - 332. Reconstruct Itinerary

### ISSUE THREAD

**Issue by vikash-gupta** [LeetCode-Feedback/LeetCode-Feedback#5116]
#### Your LeetCode username
user8998Q

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Missing tags in the question

#### Expected behavior
Add these tags to the question

- Backtracking
- Greedy

**Comment by vikash-gupta** [comment]
Hi @LC-Sue , this is not missing a test case. My bad-I filed it under wrong category.

The feedback is with the question. It's missing tags. Please add these tags to the question

- Backtracking
- Greedy

Thanks!

**Comment by LC-Sue** [comment]
Hi @vikash-gupta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
