### ISSUE TITLE
152. Maximum Product Subarray

### ISSUE THREAD

**Issue by chhavibansal** [LeetCode-Feedback/LeetCode-Feedback#512]
#### Your LeetCode username

chhavibansal

#### Category of the bug
- [.] Question
- [.] Solution
- [.] Language

#### Description of the bug

Missing test case

#### Code you used for Submit/Run operation

```
// Maximum Product Subarray
class Solution {
public:
        public int maxProduct(int[] a) {
        if(a.length == 1) return a[0];
        int pp = 1, np = 1 , max = Integer.MIN_VALUE;
        boolean hasZero = false , hasPos = false;
        
        for(int i : a){
            if( i > 0 ){
                hasPos = true;
                pp*=i;
                if(np != 1) np*=i;
            }else if(i < 0 ){
                int temp  = pp;
                pp = Math.max(1 , np*i);
                np = temp*i;
            }else {
                np = pp = 1;
                hasZero = true;
            }
            if(max < pp ) max = pp;
        }
        if(max == 1 ){
            if(hasPos) return max;
            if(hasZero ) return 0;
        }
        return max;
    }
};
```

#### Expected behavior

For test case 
[-1,-1,0] 
the answer should be 1

my code produces answer 0 
still, the code is accepted

#### Screenshots

![wrong answer](https://user-images.githubusercontent.com/35660693/85205424-f6e58980-b338-11ea-94fb-69c9f1e7edda.PNG)

#### Additional context

Please add additional test cases.

**Comment by aguilera123** [comment]
Hi @chhavibansal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @chhavibansal 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by chhavibansal** [comment]
Great.
Thank you very much.
