### ISSUE TITLE
Golang: slice index out of range

### ISSUE THREAD

**Issue by Jaskerv** [LeetCode-Feedback/LeetCode-Feedback#5125]
#### Your LeetCode username

jaskerv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Getting the following error for Golang for 26. Remove Duplicates from Sorted Array
```
Runtime Error Message:
panic: reflect: slice index out of range
reflect.Value.Index(0x4d1440, 0xc00000c168, 0x97, 0x0, 0x1, 0xc0000160e8, 0x0)
value.go, line 962
_/leetcode/user_code/576210713/precompiled.(*Serializer).Serialize(0xc00009ae70, 0x4d1440, 0xc00000c168, 0xc00000c168, 0xc00000c138)
serializer.go, line 93
main.main()
solution.go, line 53
```

#### Code you used for Submit/Run operation

```
// 26. Remove Duplicates from Sorted Array
func removeDuplicates(nums []int) int {
    var count int = 1
    
    for curr, i := 0, 0; i < len(nums); i++ {
        if nums[curr] != nums[i] {
            curr++
            nums[curr] = nums[i]
            count++
        }
    }
    
    return count
}
```
Where the exact same solution in Java works perfectly fine:
```
// 26. Remove Duplicates from Sorted Array
class Solution {
    public int removeDuplicates(int[] nums) {
        int curr = 0;
        int count = 1;
            
        for (int i = 0; i < nums.length; i++) {
            if (nums[i] != nums[curr]) {
                curr++;
                nums[curr] = nums[i];
                count++;
            }
        }
        
        return count;
    }
}
```

#### Language used for code

Golang

#### Expected behavior

Pass all tests.

#### Screenshots

Java, working solution:
![image](https://user-images.githubusercontent.com/26532014/138580386-023718f5-9205-4b0c-bf65-75c77fb4a930.png)
Golang, runtine error:
![image](https://user-images.githubusercontent.com/26532014/138580407-eaef73c6-0cdf-4049-98e7-338b234f2039.png)

**Comment by Jaskerv** [comment]
Hi @LC-Sue, 

I believe it is how the judger is using the output of my code.

Given the following, if you run:
```
import (
	"fmt"
)

func main() {
    arr := make([]int, 0)
    fmt.Printf("%v", removeDuplicates(arr))
}

func removeDuplicates(nums []int) int {
    var count int = 1
    
    for curr, i := 0, 0; i < len(nums); i++ {
        if nums[curr] != nums[i] {
            curr++
            nums[curr] = nums[i]
            count++
        } 
    }
    
    return count
}
```
`removeDuplicates` function would output `1` where it should be `0`. It did not give a `slice index out of range` error.

I believe the judger may be using the output in a slice hence causing this error. I believe this should be looked at as the error is not a reflection of a runtime error in our solution, rather the judger itself.

**Comment by LC-Sue** [comment]
Hi @Jaskerv 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
