### ISSUE TITLE
Incorrect Testcase for Problem 332 : Reconstruct Itinerary

### ISSUE THREAD

**Issue by susanth29** [LeetCode-Feedback/LeetCode-Feedback#5126]
#### Your LeetCode username

boppanasusanth

#### Category of the bug
- [ ] Incorrect Test Case 

#### Description of the bug

Testcase is Incorrect

#### Code you used for Submit/Run operation

```
class Solution {
public:
    unordered_map<string, map<string, int>> m;
    vector<string> ans;
    int cnt;
    vector<string> findItinerary(vector<vector<string>>& t) {
        cnt = t.size();
        m.clear();
        ans.clear();
        vector<string> tmp;
        tmp.push_back("JFK");
        for(auto& it : t) m[it[0]][it[1]]++;
        traverse(tmp, "JFK", 0);
        return ans;
    }
    
    bool traverse(vector<string>& tmp, string s, int n){
        if(n == cnt){
            ans = tmp;
            return true;
        }
        for(auto& a : m[s]){
            if(a.second == 0) continue;
            tmp.push_back(a.first);
            a.second--;
            if(traverse(tmp, a.first, n+1)) return true;
            tmp.pop_back();
            a.second++;
        }
        return false;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

The expected output of the below testcase 
[["JFK","SFO"],["SFO","ATL"],["SFO","BOS"],["SFO","LHR"],["ATL","BOS"],["BOS","LHR"],["LHR","BOS"],["BOS","ATL"]]
is [] as there is no path with all flights connected. Leetcode's solution is given as ["JFK","SFO","LHR","BOS","ATL","BOS","LHR","BOS","ATL"] which is wrong.

**Comment by susanth29** [comment]
When I try to run [["JFK","SFO"],["SFO","ATL"],["SFO","BOS"],["SFO","LHR"],["ATL","BOS"],["BOS","LHR"],["LHR","BOS"],["BOS","ATL"]] now, it is shown as Invalid Input. Case closed

**Comment by LC-Sue** [comment]
Hi @susanth29 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
