### ISSUE TITLE
Typo in opening question

### ISSUE THREAD

**Issue by massodyssey** [LeetCode-Feedback/LeetCode-Feedback#5128]
In article "Array Capacity VS Length"
https://leetcode.com/explore/learn/card/fun-with-arrays/521/introduction/3295/

"If somebody asks you how long the DVD Array is, what what would your answer be?"

The extra what should be removed.

**Comment by LC-Sue** [comment]
Hi @massodyssey 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
