### ISSUE TITLE
1488. Avoid Flood in The City - Test case bug

### ISSUE THREAD

**Issue by sanj06** [LeetCode-Feedback/LeetCode-Feedback#513]
#### Your LeetCode username

sanj06

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The problem says "If there are multiple valid answers return any of them." 
For example, 
Input: rains = [1,2,0,0,2,1]
Output: [-1,-1,2,1,-1,-1]
It is stated that " [-1,-1,1,2,-1,-1] is another acceptable scenario"

Following the same, the 67th test case with the input [1,2,0,2,3,0,1] can have several solutions, among which [-1,-1,1,-1,-1,2,-1] is the result of my code. But, this test case does not pass and it says wrong answer. While the expected output [-1,-1,2,-1,-1,1,-1] is restricted to only one of the several solutions. 

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] avoidFlood(int[] rains) {
        Map<Integer,Integer> map = new HashMap<Integer,Integer>();
        int[] output = new int[rains.length];
        int[] output1 = new int[0];
        int j=1;
        
        
        
        for(int i=0;i<rains.length;i++){
            if(rains[i]>0){
                if(j<rains.length-1){
                    if(rains[i]==rains[j]){
                        return output1;
                    }
                }
                

                if(map.containsKey(rains[i])){
                    Integer a = map.get(rains[i]);
                    map.replace(rains[i],a+1);
                }
                else{
                    map.put(rains[i],1);
                }

                output[i] = -1;
            }
            else if(rains[i]==0 && !map.isEmpty()){
                Map.Entry<Integer,Integer> entry = map.entrySet().iterator().next();
                Integer val = entry.getKey();
                
                if(entry.getValue()-1 == 0){
                    map.remove(val);
                }
                else{
                    map.replace(val,entry.getValue()-1);
                }
                
                output[i]=val;
            }
            else if(rains[i]==0 && map.isEmpty()){
                output[i]=1;
            }
            
            j++;
        }
        
       for(Integer value : map.values()){
           if(value>=2){
               return output1;
           }
       }
        
        return output;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The question says multiple answers are possible and any of those is acceptable, but the test case does not consider this and is restricted to only one solution.

 The 67th test case with the input [1,2,0,2,3,0,1] can have several solutions, among which [-1,-1,1,-1,-1,2,-1] is the result of my code. But, this test case does not pass and it says wrong answer. While the expected output provided [-1,-1,2,-1,-1,1,-1] is restricted to only one of the several solutions. 

#### Screenshots

![image](https://user-images.githubusercontent.com/52536720/85218452-18398a80-b3b8-11ea-86a9-6d240644d169.png)

**Comment by hairman123** [comment]
[-1,-1,1,-1,-1,2,-1] is not a valid solution because the lake 2 will flood at day 4. You should dry lake 2 first.

**Comment by lc-christina** [comment]
Hi @sanj06 
Thanks for reaching out to us. @hairman123 is correct, your outcome is not a valid solution because lake 2 will flood on day 4. Please let us know if there is anything else we can help!
