### ISSUE TITLE
Incorrect algorithm description in solution for 32. Longest Valid Parentheses

### ISSUE THREAD

**Issue by alanag13** [LeetCode-Feedback/LeetCode-Feedback#5132]
#### Your LeetCode username
alanag13

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The "Approach 3: Using Stack" section of this problem states at one part:
https://leetcode.com/problems/longest-valid-parentheses/solution/

> subtract the current element's index from the top element of the stack

But this is incorrect as can be seen in the code examples. Instead, the top element from the stack should be subtracted from the current element's index.

**Comment by LC-Sue** [comment]
Hi @alanag13 
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
