### ISSUE TITLE
Graphic Solution of Problem 72 is not clear

### ISSUE THREAD

**Issue by Sparksssj** [LeetCode-Feedback/LeetCode-Feedback#5138]
#### Your LeetCode username
Sparksssj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the graphic solution of approach 1, it's shown on the picture that we need to get the min of the sum of adjacent values, but actually, we need to get the min of them.

#### Screenshots

![image](https://user-images.githubusercontent.com/56856447/138740487-ca9f4c68-24af-4515-8c7b-61eb9750507e.png)

**Comment by LC-Sue** [comment]
Hi @Sparksssj 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
