### ISSUE TITLE
809. Expressive Words - Missing test case

### ISSUE THREAD

**Issue by vaishnavi-janardhan** [LeetCode-Feedback/LeetCode-Feedback#514]
#### Your LeetCode username

vaish_janardhan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

An incorrect solution to this problem is getting accepted due to a missing test case

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<pair<char,int>> freq(string s) {
        vector<pair<char,int>> freq_s;
        char prev = 'A';
        int i = -1;
        for (char c : s) {
            if (c == prev)
                freq_s[i].second++;
            else {
                freq_s.push_back({c,1});
                i++;
                prev = c;
            }
        }
        return freq_s;
    }
    
    int expressiveWords(string S, vector<string>& words) {
        int count = 0;
        vector<pair<char,int>> freq_s = freq(S);
        for (string word : words) {
            if (word.size() > S.size())
                continue;
            vector<pair<char,int>> freq_w = freq(word);
            if (freq_w.size() != freq_s.size())
                continue;
            bool expressive = true;
            for (int i = 0; i < freq_s.size(); i++) {
                if (freq_s[i].first != freq_w[i].first || !(freq_s[i].second == freq_w[i].second || freq_s[i].second >= 3)) {
                    expressive = false;
                    break;
                }           
            }
            if (expressive)
                count++;
        }
        return count;
    }
};

```

#### Language used for code
C++

#### Expected behavior

**Test case:** 
"heeelllooo"
["hellllo"]
**Expected output:** 0
**The output from the above code:** 1

#### Additional context

https://leetcode.com/problems/expressive-words/

**Comment by aguilera123** [comment]
Hi @vaishnavi-janardhan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @vaishnavi-janardhan 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
