### ISSUE TITLE
TypeScript & JavaScript: PriorityQueue library version is outdated, need to bump.

### ISSUE THREAD

**Issue by realdennis** [LeetCode-Feedback/LeetCode-Feedback#5147]
#### Category of the bug
- [x] Language
- [ ] Question
- [ ] Solution
- [ ] Missing Test Cases 

#### Description of the bug

The current `@datastructures-js/priority-queue` on OJ environment is outdated version, guess it's before `v5.0.0` (and now is `v5.3.0`), we need to bump the version so that we could construct using `comparator` with default priority, and also only import the `PriorityQueue` if we wanna use the customHeap.

^ Some case we need compare the lexical order using heap

Discussion thread
https://github.com/datastructures-js/priority-queue/issues/21#issuecomment-822469539
https://github.com/datastructures-js/priority-queue/pull/31#issuecomment-952356443

#### Language used for code

TypeScript / JavaScript

#### Expected behavior

Latest version, the list API in document.

#### Additional context

I've request this month ago in Help Center, but no further follow up, the library owner also did that before, wonder know if there's any blocking to upgrade.

**Comment by eugbyte** [comment]
Please re-open the issue, The priority queue library added an important in built method to delete elements from the priority queue. See [version 6.3.0](https://github.com/datastructures-js/priority-queue/releases/tag/v6.3.0)
