### ISSUE TITLE
284. Peeking Iterator - Unable to compile/test - Fatal Error for many users & languages

### ISSUE THREAD

**Issue by vermavikrant** [LeetCode-Feedback/LeetCode-Feedback#515]
#### Your LeetCode username

aditigarg

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

When running the code on default test case, I am getting Fatal error
`Line 1: Char 7: fatal error: redefinition of 'Iterator'`
This looks like an issue because of already defined class `Iterator`.
Many users are getting this error on different languages.

#### Code you used for Submit/Run operation
**Not dependent on solution logic**. Running code throws the following fatal error
`Line 1: Char 7: fatal error: redefinition of 'Iterator'`
```
class PeekingIterator:
    def __init__(self, iterator_ob):
        return

    def peek(self):
        return 0
        
    def next(self):
        return 0

    def hasNext(self):
        return False
```

#### Language used for code

Python3

#### Expected behavior

Many users are facing this problem. It's probably because of already defined class `Iterator`

#### Screenshots

NA

#### Additional context

https://leetcode.com/problems/peeking-iterator/

**Comment by ausafaq** [comment]
I'm facing the same error while using Java.

**Comment by vanian** [comment]
Same error for JavaScript

**Comment by CooperCooperCooper** [comment]
Hi @vermavikrant ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by TheRealXster** [comment]
Still facing the issue on Java.

**Comment by VenkateswaraRajuDatla** [comment]
Still facing the problem.

**Comment by ranakan19** [comment]
Still facing the issue, using Java, it also says Invalid Test case

**Comment by lc-christina** [comment]
Hi @vermavikrant 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
