### ISSUE TITLE
Missing Test Case - 969. Pancake Sorting

### ISSUE THREAD

**Issue by jabseit** [LeetCode-Feedback/LeetCode-Feedback#5150]
#### Your LeetCode username
jambo000

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Example 1 output result has incorrect value, which is confusing

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots
<img width="868" alt="Screen Shot 2021-10-26 at 6 31 16 PM" src="https://user-images.githubusercontent.com/20374246/138984815-ed09cdc7-fb47-4c1e-a85c-f62190ab14b6.png">

**Comment by jambo000** [comment]
The output must be 1, 2, 4, 3 not 4, 2, 4, 3

**Comment by LC-Sue** [comment]
Hi @jambo000,
Thank you for reaching out. The problem description states that multiple outputs can be accepted for this problem. In this case 4,2,4,3 would also be accepted!

**Comment by jambo000** [comment]
Hi @LC-Sue ,
But in the input there is only one 4 number, but in the output there are two 4 numbers. Is that correct?

**Comment by LC-Sue** [comment]
Hi @jambo000,
Thank you for reaching out. The expected output is 4 numbers as well.
