### ISSUE TITLE
Sort Colors (#75) cannot be solved in Racket according to the spec

### ISSUE THREAD

**Issue by jbromley** [LeetCode-Feedback/LeetCode-Feedback#5151]
#### Your LeetCode username
jbromley

#### Category of the bug
- [X] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
The specification for problem #75, Sort Colors, states the following:

> Given an array nums with n objects colored red, white, or blue, sort them in-place so that objects of the same color are adjacent, with the colors in the order red, white, and blue.

However, in Racket, lists are immutable, so nothing can be done in place. At best, the colors could be sorted into a second list or vector and then returned. The specification has the contract
```
(-> (listof exact-integer?) void?)
```
so there is no way for Racket to return the solution to the problem. This makes this problem unsolvable in Racket.

#### Code you used for Submit/Run operation
There is no code, as there is no way to modify the list `nums` that is passed into the `sort-colors` function.

#### Language used for code
Racket

#### Expected behavior
The expected behavior is that the problem is solvable. The best way to do this is to allow the function to return the sorted list. The contract would have to be changed to 
```
(-> (listof exact-integer?) (listof exact-integer?))
```
to allow this.

**Comment by LC-Sue** [comment]
Hi @jbromley,
Thank you for your time! Our team has looked into this issue and we found that this problem cannot be solved in Racket. As a result, we have removed Racket from the problem. We appreciate your feedback and support!
