### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by akarp0508** [LeetCode-Feedback/LeetCode-Feedback#5156]
#### Username:
akarp0508

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My code got accepted but it does not give the correct answer for some specific inputs for example:
[2,4,11,3]
6

Because the answer it gives is:
[3,3]
While it should be:
[0,1]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        for x in range(len(nums)-1,-1,-1):
            s = target - nums[x]
            if(s in nums):
                return [x,nums.index(s)]
```

#### Language used for code
Python3

#### Expected behavior
This code shouldn't have got accepted

#### Screenshots
![image](https://user-images.githubusercontent.com/39068628/139088440-d349f197-34ee-4781-af51-5a8f927f58f5.png)

**Comment by LC-Sue** [comment]
Hi @akarp0508 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
