### ISSUE TITLE
Missing Test Case - 18. 4Sum

### ISSUE THREAD

**Issue by felixhe97** [LeetCode-Feedback/LeetCode-Feedback#5157]
#### Your LeetCode username
felixhe97

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Test cases doesn't cover 
[-1000000000,-1000000000,-1000000000,-1000000000]
-1
My code below passes all the test cases (successfully solving the problem), but integer overflows on the above custom test case.
The above custom test case is valid according to problem description.

#### Code you used for Submit/Run operation
```
// 4 Sum
class Solution {
public:
    vector<vector<int>> fourSum(vector<int>& nums, int target) {
        sort(nums.begin(), nums.end());
        unordered_map<int,int> m;
        for (int i = 0; i < nums.size(); ++i) {
            m[nums[i]] = i;
        }
        vector<vector<int>> ans;
        for (int i = 0; i < (int)nums.size() - 3; ++i) {
            if (i > 0 && nums[i-1] == nums[i]) {
                continue;
            }
            for (int j = i + 1; j < (int)nums.size() - 2; ++j) {
                if (j > i + 1 && nums[j-1] == nums[j]) {
                    continue;
                }
                if (nums[i] + nums[j] > target && target >= 0) {
                    break;
                }
                for (int k = j + 1; k < (int)nums.size() - 1; ++k) {
                    if (k > j + 1 && nums[k-1] == nums[k]) {
                        continue;
                    }
                    int temp = nums[i] + nums[j] + nums[k];
                    if (m.count(target - temp) && m[target - temp] > k) {
                        ans.push_back({nums[i], nums[j], nums[k], target - temp});
                    }
                }
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
My code should not have passed! The cases testing integer overflow/underflow should be more robust.

**Comment by LC-Sue** [comment]
Hi @felixhe97 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
