### ISSUE TITLE
Indexing with float instead of int error

### ISSUE THREAD

**Issue by briankim12** [LeetCode-Feedback/LeetCode-Feedback#5158]
#### Category of the bug
- [ https://leetcode.com/problems/peak-index-in-a-mountain-array/solution/] Question
- [ Approach 2] Solution
- [ Python ] Language
- [ ] Missing Test Cases 

#### Description of the bug

'mi' variable was calculated ->  mi = (lo + hi) / 2. 
Mi is used to index an array later, however it is a float therefore not possible.
Correct solution would be mi = (lo + hi) **//** 2

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @briankim12 
Thank you for reaching out. I have verified with the team and there is no error in the approach! This approach is written in python2 where / signifies floor division.
