### ISSUE TITLE
Misplacement of a statement in Python3 solution  - 139. Word Break

### ISSUE THREAD

**Issue by mdrafiqulrabin** [LeetCode-Feedback/LeetCode-Feedback#5165]
#### Your LeetCode username

mdrafiqulrabin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 3: Using Breadth-First-Search
In the Python3 solution, Line 17 is inside the `for` loop and so it adds the `start` value multiple times into the `visited` set.

```
            for end in range(start + 1, len(s) + 1):
                ...
                visited.add(start)
```

#### Language used for code

Python3

#### Expected behavior

Approach 3: Using Breadth-First-Search
In the Python3 solution, Line 17 should be outside of the loop.

```
            for end in range(start + 1, len(s) + 1):
                ...
            visited.add(start)
```

#### Additional context

Although adding the same value multiple times into a set has no impact on the correctness of the solution, it creates confusion for readers. The C++ and Java solutions handle it correctly, so the Python3 solution should be consistent with them.

**Comment by LC-Sue** [comment]
Hi @mdrafiqulrabin,
Thank you for your feedback. The problem has been updated. We appreciate your support!
