### ISSUE TITLE
Incorrect diagram in solution 348. Design Tic-Tac-Toe

### ISSUE THREAD

**Issue by lshobith** [LeetCode-Feedback/LeetCode-Feedback#5166]
#### Your LeetCode username

sai_shobith

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The issue is in _348. Design Tic-Tac-Toe_ --> _Approach 2: Optimised Approach_ --> _Diagrams, slide 6_.
Since (2, 0) cell is on **anti-diagonal** and **player 1** is marking the cell, "1" must be added to "-2".
The **anti-diagonal** value needs to be changed to "-1" (in red color). 

#### Expected behavior / Screenshots

![lc348_issue](https://user-images.githubusercontent.com/21293391/139379346-89d2ab2c-7318-485d-ba87-6f12e3a72014.png)

**Comment by LC-Sue** [comment]
Hi @lshobith 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
