### ISSUE TITLE
Missing Test Case - 1847. Closest Room

### ISSUE THREAD

**Issue by adarshsinhg** [LeetCode-Feedback/LeetCode-Feedback#5167]
leetcode username-> adarsh_sinhg

**Category of bug**->missing test case (TLE)

- **Question**
  1847. Closest Room
  
-**Accepted Code**

class Solution {
public:
    vector<int> closestRoom(vector<vector<int>>& rooms, vector<vector<int>>& queries) {
        
        int n=rooms.size();
        map<int,int> m;
        for(int i=0; i<n; i++)
        {
            m[rooms[i][0]]=rooms[i][1];
        }
        map<int, int> pre;
        stack<pair<int,int>> s;
        for(auto it= m.begin(); it!=m.end(); it++)
        {
           if(it==m.begin())
           {
               s.push({it->first, it->second});
               pre[it->first]={INT_MAX};
           }
            else
            {
                while(!s.empty() && s.top().second<=it->second)
                {
                    s.pop();
                }
                if(s.empty())
                {
                    pre[it->first]={INT_MAX};
                }
                else
                {
                    pre[it->first]={s.top().first};
                }
                s.push({it->first, it->second});
            }
        }
      while(!s.empty())
           s.pop();
        map<int,int> suff;
        for(auto it = m.rbegin(); it != m.rend(); it++)
        {
            if(it==m.rbegin())
            {
                s.push({it->first, it->second});
                suff[it->first]={INT_MAX};
            }
             else
            {
                while(!s.empty() && s.top().second<=it->second)
                {
                    s.pop();
                }
                if(s.empty())
                {
                    suff[it->first]={INT_MAX};
                }
                else
                {
                    suff[it->first]={s.top().first};
                }
                s.push({it->first, it->second});
            }
        }
       vector<int> ans;
        n=queries.size();
        
       for(int i=0; i<n; i++)
        {
            int ro=queries[i][0]; int si=queries[i][1];
            int a=INT_MAX, b=INT_MAX;
            // left 
            int e=INT_MAX, f=INT_MAX;
            int x=ro;
            auto it=m.lower_bound(ro);
            if(it!=m.end())
            {
                if(it->first!=ro)
                {
                    if(it!=m.begin())
                    {
                        it--; ro=it->first;
                    }
                    else
                    {
                        ro=-1;
                    }
                }
            }
            else
            {
                it--; ro=it->first;
            }
            if(ro!=-1){
                while(ro!=INT_MAX && m[ro]<si)
                {
                   ro=pre[ro]; 
                }
                if(ro!=INT_MAX)
                {   
                a=x-ro;
                e=ro;
                }
            }
           
            
            ro=x;
            it=m.lower_bound(ro);
            if(it!=m.end())
            {
               ro=it->first;
            }
            else
            {
                ro=-1;
            }
            if(ro!=-1){
                while(ro!=INT_MAX &&m[ro]<si)
                {
                   ro=suff[ro]; 
                }
                if(ro!=INT_MAX)
                {   
                b=ro-x;
                f=ro;
                }
            }
           
            if(a==b && b==INT_MAX)
            {
                ans.push_back(-1);
            }
           
            else if(a==INT_MAX ||b==INT_MAX)
                ans.push_back(min(e,f));
            else if(a<=b)
                ans.push_back(e);
            else
                ans.push_back(f);
        }
        return ans;
    }
};

-  **Language used**  -> C++

- **Missing Test Case** 
 I am attaching the txt file for test case
[output.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7439815/output.txt)

#### Description of the bug
My accepted solution is giving TLE on above test case on running on ide, but it got accepted.

#### Screenshots

![Screenshot (210)](https://user-images.githubusercontent.com/63292321/139393611-8feae53f-156e-4b03-8806-e9ac9fb56094.png)

**Comment by LC-Sue** [comment]
Hi @adarshsinhg 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
