### ISSUE TITLE
124. Binary Tree Maximum Path Sum - empty path convention not spelled out.

### ISSUE THREAD

**Issue by MaksimIM** [LeetCode-Feedback/LeetCode-Feedback#5168]
#### Your LeetCode username

MaksimM

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Often paths are allowed to be empty (this is certainly the default assumption in many areas of math).  Formally, this fits the definition given: "A path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. A node can only appear in the sequence at most once." - the empty sequence satisfies all of this. Then, for trees with all node values negative, the empty path has maximal path sum (here the standard convention is that the sum of the empty set of numbers is 0). However, this is not the expected answer, since the problem implicitly assumes that the path is not empty. Spelling out this assumption explicitly would align the formal specification with the expected behavior.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @MaksimIM 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @MaksimIM 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
