### ISSUE TITLE
Missing Test Case - 41. First Missing Positive

### ISSUE THREAD

**Issue by alexps711** [LeetCode-Feedback/LeetCode-Feedback#5172]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I believe the question is mislabeled as Hard, it should be marked as Easy or (soft) Medium.

#### Code you used for Submit/Run operation

```
class Solution:
    def firstMissingPositive(self, nums: List[int]) -> int:
        nums.sort()
        missing = 1 # first positive int
        for i in range(len(nums)):
            if nums[i] == missing: missing = nums[i] + 1
        return missing
```

**Comment by LC-Sue** [comment]
Hi @alexps711 
Thank you for your feedback. I've relayed this feedback to our team to consider. We appreciate your support!
