### ISSUE TITLE
Missing Test Case - 150. Evaluate Reverse Polish Notation

### ISSUE THREAD

**Issue by Vishalghyv** [LeetCode-Feedback/LeetCode-Feedback#5173]
#### Your LeetCode username
Vishaghyv

#### Category of the bug
- [ ] Question - 150
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This question is not of level of medium. The question is a basic postfix prefix type question.
Obviously this is just a suggestion and based on my opinion but I think it's not medium

#### Expected behavior
Level - Easy

**Comment by LC-Sue** [comment]
Hi @Vishalghyv,
Thank you for your feedback. I've relayed this feedback to our team to consider. We appreciate your support!
