### ISSUE TITLE
Unclear problem description - 2037 Minimum Number of Moves to Seat Everyone

### ISSUE THREAD

**Issue by RojerGS** [LeetCode-Feedback/LeetCode-Feedback#5174]
#### Your LeetCode username
`rodrigogiraoserrao`

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Unclear problem statement/test cases

#### Description of the issue

The problem statement says “Return the minimum number of moves required to move each student to a seat such that **no two students are in the same seat.**”

However, the third test case shows that the `seats` argument can have non-unique values. Furthermore, those values are described as the “positions” of the seats. All in all, it looks like repeated numbers refer to the same seat, while at the same time they shouldn't be allowed.

[Link to problem 2037](https://leetcode.com/problems/minimum-number-of-moves-to-seat-everyone/).

**Comment by LC-Sue** [comment]
Hi @RojerGS 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @RojerGS 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
