### ISSUE TITLE
Valid Parentheses Solution Edge Case

### ISSUE THREAD

**Issue by erik-dali** [LeetCode-Feedback/LeetCode-Feedback#5175]
Checking the length of the input can help rule out invalid strings without processing them. If the length of string is not even, then it can't be valid because there's at least one unmatched open or closed bracket.

For the Python Solution add this: 
`        if len(s)%2 != 0:
            return False`

**Comment by LC-Sue** [comment]
Hi @edxsx,
Thank you for reaching out. I would like to make sure that this request is for problem 20. Valid Parentheses?
