### ISSUE TITLE
Profile image is not being rendered for Rank 6 in global ranking table.

### ISSUE THREAD

**Issue by atarax665** [LeetCode-Feedback/LeetCode-Feedback#5176]
#### Your LeetCode username
atarax

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The profile image of global rank 6 [JOHNKRAM](https://leetcode.com/JOHNKRAM/) is not being rendered in global ranking list on the leetcode [contest](https://leetcode.com/contest/) page. 

When I went through the source code I found:
For JOHNKRAM the image src is https://aliyun-lc-upload.oss-cn-hangzhou.aliyuncs.com/aliyun-lc-upload/users/johnkram/avatar_1593402741.png
While other user's profile image is being fetched from link like https://assets.leetcode.com/users/tlatoani/avatar_1596335121.png

#### Expected behavior

The image should be fetched from some other valid source as the current url can't be reached.

#### Screenshots

![leetcode](https://user-images.githubusercontent.com/29673671/139513667-cca3e013-ae61-4a50-b586-38324e1e7b21.PNG)

**Comment by LC-Sue** [comment]
Hi @atarax665,
Thank you for reaching out. The profile imagine looks fine now! Please feel free to reach out again if you have any other questions!
