### ISSUE TITLE
Wrong space complexity in approach 3 (Morris inorder traversal)

### ISSUE THREAD

**Issue by niyozbek** [LeetCode-Feedback/LeetCode-Feedback#5178]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Generally, input and output space is not important in calculating the space complexity. Source: https://cs.stackexchange.com/questions/83574/does-space-complexity-analysis-usually-include-output-space/83586#83586

#### Expected behavior

it should be O(1) space. The whole point of morris algorithm

#### Screenshots

![image](https://user-images.githubusercontent.com/20155784/139520456-dce8d2af-3f9e-4412-adfb-1e8c844cd7d8.png)

**Comment by LC-Sue** [comment]
Hi @niyozbek,
Thank you for reaching out. Could you please provide the problem number for this issue?

**Comment by niyozbek** [comment]
94

**Comment by LC-Sue** [comment]
Hi @niyozbek 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @niyozbek 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
