### ISSUE TITLE
387. First Unique Character in a String – typos

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#518]
#### Your LeetCode username
metricquant

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The question statement has a number of typos:
1. Given a string, find the first non-repeating character in it and return **it's** index.
2. `s = "loveleetcode",`
3. You may assume the string **contain** only lowercase English letters.

#### Expected behavior
1. _its_ instead of _it's_
2. The comma should be removed.
3. _contains_ instead of _contain_

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
