### ISSUE TITLE
Missing Test Case - 1517. Find Users With Valid E-Mails

### ISSUE THREAD

**Issue by shubham06vijay** [LeetCode-Feedback/LeetCode-Feedback#5180]
#### Your LeetCode username

shubham06vijay

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

#### Description of the bug

There is a missing test case where even this row is accepted as a correct row: [1, "Winston", "winston@leetcode?com"]

#### Code you used for Submit/Run operation

```
select * from users where mail regexp '^[a-zA-Z]+[a-zA-Z0-9_.-]*@leetcode.com'
```

#### Language used for code

MySQL

#### Expected behavior

The row with  [1, "Winston", "winston@leetcode?com"] should not have been accepted as it doesn't satisfy the question's condition with **The domain is '@leetcode.com'.**

The solution should only accept 
```
select * from users where mail regexp '^[a-zA-Z]+[a-zA-Z0-9_.-]*@leetcode\.com'
```
Notice the **\\.** in the domain: **@leetcode\.com**

**Comment by LC-Sue** [comment]
Hi @shubham06vijay 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
