### ISSUE TITLE
Missing Test Case - 190. Reverse Bits

### ISSUE THREAD

**Issue by Sibiryakanton** [LeetCode-Feedback/LeetCode-Feedback#5181]
#### Your LeetCode username
antonigin1995

#### Category of the bug
- [] Question
- [ ] Solution
- [ Python] Language
- [ ] Missing Test Cases 

#### Description of the bug

Run code, which executed correct on local machine (Python 3.8.0), but drop traceback error in LeetCode console.
```
ValueError: invalid literal for int() with base 2: '0b69516234'
    result = int(result, 2)
Line 5 in reverseBits (Solution.py)
    reversed_bits = Solution().reverseBits(n)
Line 22 in _driver (Solution.py)
    _driver()
Line 33 in <module> (Solution.py)
```

#### Code you used for Submit/Run operation

```
class Solution:
    def reverseBits(self, n: int) -> int:
        result = ''.join(reversed(str(n)))
        result = f'0b{result}'
        result = int(result, 2)
        return result

```

#### Expected behavior

Valid solving of testcase (tested same cases on local Python 3.8.0)

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
