### ISSUE TITLE
Incorrect question description - 690. Employee Importance

### ISSUE THREAD

**Issue by garyholiday13** [LeetCode-Feedback/LeetCode-Feedback#5183]
#### Your LeetCode username
garyholiday13

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question states you need to return the total importance value of the given employee and all their **direct subordinates**.

However, this is misleading. Direct subordinates would imply only one level down, meaning those who report directly to the employee. The question actually means **all subordinates**.  There are several test cases that tally the total of employees several levels down, those employees would not be direct subordinates. 

I believe this is why the question has such a bad like to dislike ratio, even though it's an easy question.

**Comment by LC-Sue** [comment]
Hi @garyholiday13 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @garyholiday13 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
