### ISSUE TITLE
No ref parameter.

### ISSUE THREAD

**Issue by Allison-E** [LeetCode-Feedback/LeetCode-Feedback#5184]
#### Your LeetCode username
emmallison13

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Because the return type is `void`, and the parameter `nums` doesn't have a `ref ` modifier, there's no way to return the output of my code.

#### Code you used for Submit/Run operation

```
public class Solution {
    public void Rotate(int[] nums, int k) {
        int[] cut = nums[^k..];
        int[] first = nums[..^k];
        List<int> num = new();
        num.AddRange(cut);
        num.AddRange(first);
        nums = num.ToArray();
    }
}
```

#### Language used for code
C#

#### Expected behavior
I expected the parameter `nums` to have a `ref` modifier so the changes made to the array would be reflected.

#### Screenshots
![Leetcode bug](https://user-images.githubusercontent.com/39530416/139554497-1a5e4804-e4ce-4e83-bcdd-7475824427c7.jpg)

**Comment by LC-Sue** [comment]
Hi @Allison-E 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Allison-E,
Thank you for reaching out to us! The judger appears to be working fine, feel free to refer to the discuss section of the problem to see how other users have optimized their C# code!
