### ISSUE TITLE
Two Best Non-Overlapping Events - Wrong Answer 

### ISSUE THREAD

**Issue by i-l-s-h-a-t** [LeetCode-Feedback/LeetCode-Feedback#5185]
#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/contest/biweekly-contest-64/problems/two-best-non-overlapping-events/

#### Code you used for Submit/Run operation

```
class Solution:
    def maxTwoEvents(self, events: List[List[int]]) -> int:
        ways = dict()
        n_ways  = 1
        ended_ways = set()
        
        min_i = events[0][0]
        max_i = events[0][1]    
        for e in events[1:]:
            min_i = min(min_i, e[0])
            max_i = max(max_i, e[1])
        
        for i in range(min_i, max_i + 1):
            #print("==============", i)
            n = 0 # number of current event 
            for e in events:
                start = e[0]
                end   = e[1]
    
                if start == i: # new event started
                    ways["way_" + str(n_ways)] = [n] #create new way
                    n_ways += 1
                    
                    for w in ended_ways:
                        ways["way_" + str(n_ways)] = ways[w] + [n] #create new way as continuation
                        n_ways += 1
    
                if end + 1 == i: # event ended
                    for key, values in ways.items():
                        if values[-1] == n:
                            ended_ways.add(key)
    
                n += 1
            #print("ended_ways:", ended_ways)
            #print("ways:", ways)
        #print("==============")
        #print("ways:", ways)
        
        s_max = 0
        for key, values in ways.items():
            s = 0
            for v in values:
                s += events[v][2]
            #print(key, s, values)
            s_max = max(s, s_max)
    
        return s_max
```

#### Expected behavior

My solution for the case
[[10,83,53],[63,87,45],[97,100,32],[51,61,16]]
is 93 ant it seems it is correct, but LeetCode says that there is an error and shows answer with less sum as in my solution.
Sum=93 can be get from three non-intersecting events [63,87,45],[97,100,32],[51,61,16]] - they also shown in screenshot.
LeetCode's Sum=85 contain from events  [[10,83,53],[97,100,32]] but it is less than 93.
#### Screenshots

![image](https://user-images.githubusercontent.com/82016444/139554929-2a5c28c2-3dc5-47bc-8494-255a8836781c.png)

**Comment by stormsunshine** [comment]
Please read the problem description carefully. You can choose **at most two non-overlapping** events to attend such that the sum of their values is **maximized**.

Therefore, you cannot choose three events.

**Comment by LC-Sue** [comment]
Hi @i-l-s-h-a-t,
Thank you for reaching out, and thank you to @stormsunshine for answering the question! The problem statement states that you can choose "at most" two non overlapping events.
