### ISSUE TITLE
Missing detail in Problem Definition - 853. Car Fleet

### ISSUE THREAD

**Issue by moraza** [LeetCode-Feedback/LeetCode-Feedback#5186]
#### Your LeetCode username
mo_raza

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem definition doesn't state the new speed at which cars travel when two cars meet up. It just says "same speed" but if a faster car is blocked by a slower car, does the slow car speed to up match the speed of the faster car? or does the faster car slow down to match the speed of the slower car. The latter seems to be match what happens in real life, but the solution that is accepted implies that the slower car somehow speeds up to travel at "same speed as the faster car".

Please add clarification to the problem definiton.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @moraza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @moraza 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
