### ISSUE TITLE
Variable Name Should Be Changed - 468. Validate IP Address

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5196]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [468. Validate IP Address](https://leetcode.com/problems/validate-ip-address), the variable name is `IP`, which is not a good practice since it starts with an uppercase letter.
A good naming convension for variable names is that variable names should start with a lowercase letter.
Therefore, the variable name should be changed to `ip`. Both the problem description and the code should be changed to update the variable names.

#### Expected behavior
In both the problem description and the code, the variable name `IP` should be changed to `ip`. The variable name should consist of lowercase letters.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
