### ISSUE TITLE
Example 1 typo - 981. Time Based Key-Value Store

### ISSUE THREAD

**Issue by puliaiev** [LeetCode-Feedback/LeetCode-Feedback#5197]
#### Your LeetCode username
puliaiev

#### Description of the bug
Typo in Example 1:
`store the key "foo" and value "ba2r" along with timestamp = 4.`
should be:
`store the key "foo" and value "ba2" along with timestamp = 4.`

**Comment by LC-Sue** [comment]
Hi @puliaiev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @puliaiev 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
