### ISSUE TITLE
430. Flatten a Multilevel Doubly Linked List

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#5198]
#### Your LeetCode username

archit91

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question doesn't mention that the flattened doubly linked list should have all the child pointers set to NULL. If a correct double linked list is returned without setting child pointers to NULL, we get error as follows -

```
The linked list [1,2,3,7,8,11,12,9,10,4,5,6] is not a valid doubly linked list.
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    Node* flatten(Node* head) {
	for (Node* h = head; h; h = h->next)
	{
		if (h->child)
		{
			Node* next = h->next;
			h->next = h->child;
			h->next->prev = h;
			// h->child = NULL;
			Node* p = h->next;
			while (p->next) p = p->next;
			p->next = next;
			if (next) next->prev = p;
		}
	}
	return head;
}
};
```

#### Language used for code

C++

#### Expected behavior

The question description should be updated to clearly mention that the final linked list should set child pointers of all nodes to nullptr.

**Comment by LC-Sue** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
