### ISSUE TITLE
Incorrect question description - 566. Reshape the Matrix

### ISSUE THREAD

**Issue by devraphy** [LeetCode-Feedback/LeetCode-Feedback#5199]
#### Your LeetCode username

- ID: devraphy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

- In Example2, the c should be 2 not 4. It is 2 by 2 matrix, not 2 by 4.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/63382028/139589069-eed35326-fc5e-41af-90f8-db3dc18e3935.png)

**Comment by LC-Sue** [comment]
Hi @devraphy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @devraphy 
Thank you for your time. There is no typo. According to the statement:If the reshape operation with given parameters is possible and legal, output the new reshaped matrix; Otherwise, output the original matrix. 
We appreciate your support!
