### ISSUE TITLE
Filtering unlocked

### ISSUE THREAD

**Issue by alexalghisi** [LeetCode-Feedback/LeetCode-Feedback#52]
**What kind of the bug**
- [ ] filters

Filters bug.
**Describe the bug**
I would like to be able to filter the problems by the locked field.

**what language is your code written in**
N/A

**Expected behavior**
Until I purchase a premium subscription I would like to be able to sort the problems by the acceptance rate ( I can ) and unlocked ons only.

**Comment by CooperCooperCooper** [comment]
Hi @alexalghisi,
Thank you for reaching out to us! For feature suggestions, please share your ideas with our support team here: https://support.leetcode.com/hc/en-us. We appreciate your support and understanding.
