### ISSUE TITLE
1476. Subrectangle Queries - Judger generates wrong expected output for testcase.

### ISSUE THREAD

**Issue by MoonshineIndustries** [LeetCode-Feedback/LeetCode-Feedback#520]
Testcase:
```
["SubrectangleQueries","getValue","updateSubrectangle","getValue","getValue","updateSubrectangle","getValue","getValue"]
[[[[1,2,1],[4,3,4],[3,2,1],[1,1,1]]],[0,2],[0,1,3,2,5],[1,0],[3,1],[3,0,3,2,10],[3,1],[0,2]]
```
Judger Expects:
```
[null,1,null,4,5,null,10,5]
```
Should be:
```
[null,1,null,5,5,null,10,5]
```

The judger expects that the second row's first column returns 4, when it needs to be 5, We need to change all values from (0th row, 1 col) to (3rd row, 2col) to 5. In other words all elements except the very first one need to be changed to 5. My code correctly skips the 1st element (0,0) but then incorrectly skips (1,0, 2,0 and 3,0) but the solution is still accepted.

Expected output according to the problem text:

```
[1, 5, 5]
[5, 5, 5]
[5, 5, 5]
[5, 5, 5]

[1, 5, 5]
[5, 5, 5]
[5, 5, 5]
[10, 10, 10]
```

My actual output: (**This passes the testcase but it shouldn't**)

```
[1, 5, 5]
[4, 5, 5]
[3, 5, 5]
[1, 5, 5]

[1, 5, 5]
[4, 5, 5]
[3, 5, 5]
[10, 10, 10]
```

My Solution: (**Which should be wrong, but passed all testcases**)

```
class SubrectangleQueries {
    
    private int[][] rectangle;

    public SubrectangleQueries(int[][] rectangle) {
        this.rectangle = rectangle;
    }
    
    public void updateSubrectangle(int row1, int col1, int row2, int col2, int newValue) {
        for (int i = row1; i <= row2; i++) {
            for (int j = col1; j <= col2; j++) {  //if col1 is anything but 0, we will have wrong values on other rows.
                rectangle[i][j] = newValue;
            }
        }    
    }
    
    public int getValue(int row, int col) {
        return rectangle[row][col];
    }
}
```

**Comment by CooperCooperCooper** [comment]
Hi @MoonshineIndustries ,
Thank you for reaching out to us. I tested your Java code with the mentioned test case and found the test case was Accepted. Please see the screenshot attached for more information. We appreciate your support.
<img width="1416" alt="Screen Shot 2020-06-23 at 9 55 22 PM" src="https://user-images.githubusercontent.com/59751300/85502572-69a26f00-b59c-11ea-86aa-03a4c59a52b7.png">

**Comment by MoonshineIndustries** [comment]
Yeah the point was that it shouldn't be accepted, right? Since the elements of the 2nd and 3rd row aren't supposed to be 4, they should be 5.

**Comment by MoonshineIndustries** [comment]
I rewrote my explanation a bit in the main comment so hopefully it is more clear. Basically the judger generates the wrong expected output and the incorrect code is accepted.

**Comment by lc-kate** [comment]
Hi @MoonshineIndustries ,

Thank you for your time. I've relayed your issue to our team to take a further look at.

**Comment by lc-kate** [comment]
Hi @MoonshineIndustries ,
Thank you for your time. Our engineer reproduced the process by hand and found the issue stems from your end. We strongly encourage you to please carefully reproduce the issue again and reexamine every step. Then you'll realize where the issue lies. Thank you.
