### ISSUE TITLE
useless loop condition -- 575. Distribute Candies

### ISSUE THREAD

**Issue by unknown-peter** [LeetCode-Feedback/LeetCode-Feedback#5200]
#### Your LeetCode username

unknownpeter

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 2 line 8 uniqueCandies / 2 < candyType.length
uniqueCandies/2 will always less than candyType.length.
that expression might be uniqueCandies < candyType.length / 2

#### Code you used for Submit/Run operation

```
    public int distributeCandies(int[] candyType) {
        // We start by sorting candyType.
        Arrays.sort(candyType);
        // The first candy is always unique.
        int uniqueCandies = 1;
        // For each candy, starting from the second candy...
        for (int i = 1; i < candyType.length && uniqueCandies < candyType.length / 2 ; i++) {
            // This candy is unique if it is different to the one
            // immediately before it.
            if (candyType[i] != candyType[i - 1]) {
                uniqueCandies++;
            }
        }
        // Like before, the answer is the minimum out of the number of unique
        // candies, and half the length of the candyType array.
        return Math.min(uniqueCandies, candyType.length / 2);
    }
```

**Comment by LC-Sue** [comment]
Hi @unknown-peter 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @unknown-peter 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
