### ISSUE TITLE
1466. Reorder Routes to Make All Paths Lead to the City Zero

### ISSUE THREAD

**Issue by krfong916** [LeetCode-Feedback/LeetCode-Feedback#5202]
#### Your LeetCode username
icalledyoulastsunday

#### Category of the bug
- [ ] Question N/A
- [x] Solution
- [ ] Language N/A
- [ ] Missing Test Cases  N/A

#### Description of the bug

Code passes on test case input passes when ran 
Exactly the same code and exactly the same input fails when problem is submitted  === 🐛 

#### Code you used for Submit/Run operation

```
/**
 * @param {number} n
 * @param {number[][]} connections
 * @return {number}
 */
let dag = undefined
let adj = undefined
let state = undefined
let numEdgeReverse = 0;
let minReorder = function(n, connections) {
  dag = getDAG(connections);
  adj = getADJ(connections);
  state = initState(n)
  for (let u = 0; u < n; u++) {
    if (state[u] === 0) {
      minReorderVisit(u, adj)
    }
  }
  return numEdgeReverse
};

function minReorderVisit(u, adj) {
  state[u] = 1
  for (let i = 0; i < adj[u].length; i++) {
    let v = adj[u][i];
    if (state[v] === 0) {
      minReorderVisit(v, adj)
    } else if (!dag.hasOwnProperty(u) || (dag[u].hasOwnProperty(v) === false)) {
      console.log("u:", u, ", v:", v)
      numEdgeReverse++           
    }
  }
  state[u] = 2
}

function initState(n) {
  let state = {}
  for (let i = 0; i < n; i++) {
    state[i] = 0
  }
  return state;
}

function getDAG(connections) {
  let g = {}
  for (let i = 0; i < connections.length; i++) {
    let [u,v] = connections[i]
    if (g[u]) {
      g[u][v] = true
    } else {
      g[u] = {[v]: true}
    }
  }
  return g
}
function getADJ(connections) {
  let g = {}
  for (let i = 0; i < connections.length; i++) {
    let [u,v] = connections[i]
    if (g[u]) {
      g[u].push(v)
    } else {
      g[u] = [v]
    }
    
    if (g[v]) {
      g[v].push(u)
    } else {
      g[v] = [u]
    }
  }
  return g
}
```

#### Language used for code

Javascript

#### Expected behavior

I expect the code to be accepted.

When ran on the following input via testing the solution
```
5
[[1,0],[1,2],[3,2],[3,4]]
```

My code passes and computes the correct answer.

However, when submitting the code, my code fails on that exact same test input.

#### Additional context

Lmk

**Comment by LC-Sue** [comment]
Hi @krfong916 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
