### ISSUE TITLE
Missing Test Case - 2059. Minimum Operations to Convert Number

### ISSUE THREAD

**Issue by developer-nobita** [LeetCode-Feedback/LeetCode-Feedback#5203]
#### Your LeetCode username
Nobita__

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A solution gets accepted but fails on one or more test cases.
The test case is as follows.
```
[81,-5,22]
62
80
```

#### Code you used for Submit/Run operation

```
// Minimum Operations to Convert Number
class Solution {
public:
    int goal;
    vector<int>arr;
    vector<int>visited;
    vector<long int>dp;
    int call = 0;
    int findmin(long int curr){
        if(curr==goal) return 0;
        if(curr<0) return 2*1e9;
        if(curr>1000) return 2*1e9;
        if(visited[curr]) return 2*1e9;
        if(dp[curr]!=-1){
            return dp[curr];
        }
        visited[curr]++;
        long int mini = 2*1e9,st=-1;
        for(int i = 0;i<arr.size();i++){
            long int a = 1 +findmin(curr+arr[i]);
            long int b = 1 +findmin(curr-arr[i]);
            long int c = 1 +findmin(curr^arr[i]);
            mini = min(mini,a);
            mini = min(mini,b);
            mini = min(mini,c);
            if(mini==a)st=curr+arr[i];
            else if(mini==b)st=curr-arr[i];
            else st=curr^arr[i];
        }
        visited[curr]--;
        return dp[curr] = mini;
    }
    int minimumOperations(vector<int>& nums, int start, int goal) {
        this->goal = goal;
        arr = nums;
        sort(arr.rbegin(),arr.rend());
        visited.resize(1001,0);
        dp.resize(1001,-1);
        int curr =  findmin(start);
        if(curr>=1e9) curr = -1;
        return curr;
    }
};
```

#### Language used for code

C++

#### Expected behavior
The test case above should be added and the code above should get Wrong Answer when submitted.

**Comment by LC-Sue** [comment]
Hi @developer-nobita 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @developer-nobita 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
