### ISSUE TITLE
Wrong Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by ZhangYuef** [LeetCode-Feedback/LeetCode-Feedback#5204]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I get error report on this test case and I am afraid this test case is wrong for this question#209:

```
Input:
11
[1,2,3,4,5]
Output:
0
Expected:
3
```

The expected output should be 0 in my understanding.

**Comment by CptGit** [comment]
@ZhangYuef The test case is fine. [3, 4, 5] is the subarray.

**Comment by ZhangYuef** [comment]
> @ZhangYuef The test case is fine. [3, 4, 5] is the subarray.

My mistake. It is **greater or equal**.
