### ISSUE TITLE
Missing Test Case - 485. Max Consecutive Ones

### ISSUE THREAD

**Issue by murlidharpathakprogrammer** [LeetCode-Feedback/LeetCode-Feedback#5205]
#### Your LeetCode username
murlidharpathak 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A precise testcase was missing.

**Comment by murlidharpathakprogrammer** [comment]
A Precise testcase was missing

**Comment by LC-Sue** [comment]
Hi @murlidharpathakprogrammer 
Thank you for reaching out, could you provide the test case that you suggest adding?

**Comment by murlidharpathakprogrammer** [comment]
[1,1,0,1,1,1,0,1,0,1,1]

**Comment by LC-Sue** [comment]
Hi @murlidharpathakprogrammer,
I apologize I had missed the notification for this thread. The test case you provided is accepted. Did you want to provide the code you used so I can verify the test case again?

**Comment by LC-Sue** [comment]
Hi @murlidharpathakprogrammer 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
