### ISSUE TITLE
Missing Test Case - 278. First Bad Version

### ISSUE THREAD

**Issue by crocme10** [LeetCode-Feedback/LeetCode-Feedback#5206]
#### Category of the bug
 Language

#### Description of the bug

In rust version of pb 278, it proposes a pre existing function isBadVersion(versions:i32)-> bool;

This has 2 slight issues:

1. in rust function use snake case => is_bad_version
2. the variable name should be version, not versions

**Comment by LC-Sue** [comment]
Hi @crocme10 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @crocme10 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
