### ISSUE TITLE
1000. Minimum Cost to Merge Stones

### ISSUE THREAD

**Issue by AbrarJahin** [LeetCode-Feedback/LeetCode-Feedback#5207]
#### Your LeetCode username

abrarjahin
URL - https://leetcode.com/abrarjahin/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases or Wrong Test Cases

#### Description of the bug

For this test case-
[3,5,1,2,6], k = 3

A solution can be-

1. Taking [1,2,3] -> cost =   6, remaining item-> [5,6 and (1+2+3)=6]=> [5,6,6]
2. Taking [5,6,6] -> cost = 17, remaining item-> [null=> [5,6,6]
----------------------
Total Cost = 6+17 = 23 which is minimum

But it is calculated like this-

    Explanation: We start with [3, 5, 1, 2, 6].
    We merge [5, 1, 2] for a cost of 8, and we are left with [3, 8, 6].
    We merge [3, 8, 6] for a cost of 17, and we are left with [17].
    The total cost was 25, and this is the minimum possible.

Where given answer is 25 which is worse than 23. SO, answer should be 23, not 25 I think.

#### Code you used for Submit/Run operation

```
import heapq

class Solution:
    def mergeStones(self, stones: List[int], k: int) -> int:
        heap, cost = [], 0
        for s in stones:
            heapq.heappush(heap, s)
        while len(heap)>1:
            if len(heap)<k: return -1
            sum = 0
            for i in range(k):
                popVal = heapq.heappop(heap)
                sum+=popVal
                print(popVal)
            cost += sum
            print("-", cost, sum)
            heapq.heappush(heap, sum)
        return cost
```

#### Expected behavior
The answer should be minimum cost, which should be 23 for this case, not 25 for the abovementioned example input.

There are other cases like this-

[3,2,4,1]
2

Answer should be 19 for this not 20.

#### Screenshots
![image](https://user-images.githubusercontent.com/4152843/139775497-c9abe9ea-07a4-4ffa-aed1-a23507baa248.png)

Can you please have a look into this problem and please let me know if everything is OK or not.

**Comment by LC-Sue** [comment]
Hi @AbrarJahin,
Thank you for reaching out. Our judger appears to be working correctly. Please feel free to look through the discuss section of the problem to see how others have optimized their code.

**Comment by AbrarJahin** [comment]
Hi @LC-Sue ,

Thank you for your reply.

For the input-

[3,2,4,1]
2

If I am doing something like this-

<img width="164" alt="image" src="https://user-images.githubusercontent.com/4152843/143417288-e627eaff-c653-4fe8-83bf-517152f33d8f.png">


And getting the output of 19 instead of 20, what is the error?

**Comment by LC-Sue** [comment]
Hi @AbrarJahin,
Thank you for reaching out. Merging 1, 2 in the first step which is not allowed. The problem says we must merge exactly k consecutive piles, but 1 and 2 are not consecutive.
