### ISSUE TITLE
Missing Test Case - 206. Reverse Linked List

### ISSUE THREAD

**Issue by r0ushann** [LeetCode-Feedback/LeetCode-Feedback#5209]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
 [+] Missing Test Cases 
[3,5,6,7,2,3,8,4]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @r0ushann,
Thank you for reaching out. Could you please provide the code that you used for submission?

**Comment by LC-Sue** [comment]
Hi @r0ushann 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
