### ISSUE TITLE
Grammar - 606. Construct String from Binary Tree

### ISSUE THREAD

**Issue by fultonm** [LeetCode-Feedback/LeetCode-Feedback#5212]
#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The first sentence has a typo, ", construct a string consists of parenthesis " should be "consisting of"

The "with the pre-order traversing way" sounds odd. It is more commonly "in preorder traversal order"

"Originally" is misspelled in an example.

Consider rewriting the whole thing?

**Comment by LC-Sue** [comment]
Hi @fultonm 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @fultonm 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
