### ISSUE TITLE
Wrong Pointer for Database - 1341. Movie Rating

### ISSUE THREAD

**Issue by pchimote** [LeetCode-Feedback/LeetCode-Feedback#5213]
SELECT * FROM MovieRating fails
thus voiding any check for code and testcase

**Comment by LC-Sue** [comment]
Hi @pchimote,
Thank you for reaching out, could you please provide more details and the link for the issue that you are referring to?

**Comment by pchimote** [comment]
hi @LC-Sue, the table - movie ratings - for this question cannot be accessed by MovieRating or movierating, it just gives an invalid testcase error called 'Movie_Rating'

**Comment by LC-Sue** [comment]
Hi @pchimote 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @pchimote 
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username?

**Comment by pchimote** [comment]
@LC-Sue , it is the same as GitHub i.e. pchimote. Thank you!

**Comment by pchimote** [comment]
Hi @LC-Sue , can I know what the reward is?

**Comment by LC-Sue** [comment]
Hi @pchimote 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
