### ISSUE TITLE
test case malfunction - 743. Network Delay Time

### ISSUE THREAD

**Issue by Alfred-Onuada** [LeetCode-Feedback/LeetCode-Feedback#5216]
#### Category of the bug
 - [ ] Question

- [ ] Solution

#### 
```
class Solution:
    def networkDelayTime(self, times: list[list[int]], n: int, k: int) -> int:
        
        map_dict = {}

        for start, end, duration in times:
            if start in map_dict:
                map_dict[start].append([end, duration])
            else:
                map_dict[start] = [[end, duration]]

        return self.getTime(map_dict, n, k)

    def getTime(self, map_dict, n, k, paths=[]):

        paths.append([n, k])

        if paths.count([n, k]) > 1:
            return "recursion"

        totalTime = 0
        if k in map_dict:
            for path in map_dict[k]:
                totalTime = path[1]
                time = self.getTime(map_dict, n, path[0], paths)
                if time != -1 and time != "recursion":
                    totalTime += path[1]
                elif time == "recursion":
                    print("here")
                    pass
        else:
            return -1

        return totalTime
```

**Comment by LC-Sue** [comment]
Hi @Alfred-Onuada 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
