### ISSUE TITLE
Minor Error in Backtracking Card File

### ISSUE THREAD

**Issue by abunks89** [LeetCode-Feedback/LeetCode-Feedback#5218]
Leetcode: abunks

In the explore card "backtracking," the function is defined as "backtrack_nqueen." This is used recursively, but in the function itself it is referred to as "backtrack"

@https://leetcode.com/explore/learn/card/recursion-ii/472/backtracking/2654/

def backtrack_nqueen(row = 0, count = 0):
'

    for col in range(n):
        # iterate through columns at the curent row.
        if is_not_under_attack(row, col):
            # explore this partial candidate solution, and mark the attacking zone
            place_queen(row, col)
            if row + 1 == n:
                # we reach the bottom, i.e. we find a solution!
                count += 1
            else:
                # we move on to the next row
                count = backtrack(row + 1, count)
            # backtrack, i.e. remove the queen and remove the attacking zone.
            remove_queen(row, col)
    return count

`

**Comment by LC-Sue** [comment]
Hi @abunks89 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @abunks89 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
