### ISSUE TITLE
Missing Test Case - 403. Frog Jump

### ISSUE THREAD

**Issue by preetichand** [LeetCode-Feedback/LeetCode-Feedback#5219]
username-celestialaTX
Missing testcase- [0,1,2,3,4,6,9,11,12,13,17,18,19,21,22,25,28,29,32,33,35,36,38 ,39,40,42,43,45,49]

expected output- true
actual output -false

Code used to submit-
```    
class Solution {
public:
    bool canCross(vector<int>& stones) {
        int n=stones.size();
    
        vector<vector<bool>>dp(n,vector<bool>(n+1,false));  
        dp[0][1]=true;
        for(int i=1;i<n;i++){
            for(int j=0;j<i;j++){
                    if(stones[i]-stones[j]>n)
                        continue;
                    int jump=stones[i]-stones[j];
                    dp[i][jump]=dp[j][jump];
                    dp[i][jump+1]=dp[j][jump];
                    dp[i][jump-1]=dp[j][jump];
                }
                
            }
        
        bool ans=false;
        for(bool x:dp[n-1]){ 
            ans|=x;
        }
        return ans;
    }
};
```

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @preetichand 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @preetichand 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
