### ISSUE TITLE
Path Compression Optimization - Disjoint Set - Memoization table needed for Find function.

### ISSUE THREAD

**Issue by PRL-GIT** [LeetCode-Feedback/LeetCode-Feedback#5222]
#### Category of the bug
- [ X] Solution

#### Description of the bug

https://leetcode.com/explore/featured/card/graph/618/disjoint-set/3880/
The find function (including the video) needs a memoization table somehing like 

    def find(self, x):
        if mem_root[x] != None:
            return mem_root[x]
        if x == self.root[x]:
            return x
        self.root[x] = self.find(self.root[x])
        return self.root[x]
		

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @PRL-GIT 
Thank you for reaching out to us. I've relayed this feedback to our team.
