### ISSUE TITLE
The linked list review cards has missit

### ISSUE THREAD

**Issue by e-remington-lee** [LeetCode-Feedback/LeetCode-Feedback#5224]
A lot of items in the linked list review card are blank and cannot be found. I am unsure if that is because they are not loading or they are missing.

![Capture](https://user-images.githubusercontent.com/46659935/140233047-07233044-728b-4e56-8db5-bceb463b66dc.JPG)

**Comment by LC-Sue** [comment]
Hi @e-remington-lee,
Thank you for reaching out. I am able to access the card just fine. However, some pages unlock in order, it should unlock and load after you have looked through the previous page. Please feel free to reach out if you have any other questions.
