### ISSUE TITLE
Missing Type Signature - 157. Read N Characters Given Read4

### ISSUE THREAD

**Issue by shurane** [LeetCode-Feedback/LeetCode-Feedback#5225]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I was quite confused since this normally makes sense with C/C++ semantics with a char * buffer/ array. In Python, I didn't understand how the same semantics translated over until I looked at the type signature for `158.`

#### Code you used for Submit/Run operation

This is the default code for 157:

```python3
class Solution:
    def read(self, buf, n):
        """
        :type buf: Destination buffer (List[str])
        :type n: Number of characters to read (int)
        :rtype: The number of actual characters read (int)
        """
```

But it should match the type signature for 158:

```python3
# The read4 API is already defined for you.
# def read4(buf4: List[str]) -> int:

class Solution:
    def read(self, buf: List[str], n: int) -> int:
```

#### Language used for code

Python3

#### Expected behavior

I expected 157. to use the same type signature as 158, since Python 3 supports type hints.

**Comment by LC-Sue** [comment]
Hi @shurane 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @shurane 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
