### ISSUE TITLE
Change Follow-up to Standard Requirement - 344. Reverse String

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5226]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [344. Reverse String](https://leetcode.com/problems/reverse-string), the Follow up is: Do not allocate extra space for another array. You must do this by modifying the input array in-place with `O(1)` extra memory.

I do not think this should be a follow-up requirement, and this should be a standard requirement. The paragraph should be moved to the description part, right before Example 1, with "Follow up" removed.

The reasons why this should be a standard requirement is as follows.
1. The return type is `void`, so it is natural to solve this problem in-place without allocating extra space for another array.
2. If this problem is used in an interview, the interview will expect a solution that uses O(1) extra memory. A solution that allocates extra space for another array won't be accepted in most cases.

Although the space complexity can't be detected automatically, the requirement to use O(1) extra space should be stated in problem description. Users should try to figure out a solution that uses O(1) extra space.

#### Expected behavior
The Follow up should be changed to a standard requirement. The description before the examples should be as follows.

> Write a function that reverses a string. The input string is given as an array of characters `s`.
> 
> Do not allocate extra space for another array. You must do this by modifying the input array [in-place](https://en.wikipedia.org/wiki/In-place_algorithm) with `O(1)` extra memory.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We've moved the follow-up to the statement. Still, no way to verify that the solution make the change in-place. We appreciate your support!
