### ISSUE TITLE
Problem Description Enhancement - 378. Kth Smallest Element in a Sorted Matrix

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5227]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem [378. Kth Smallest Element in a Sorted Matrix](https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix) is marked as a Medium problem. However, there exists a solution as follows: Put all the elements in the matrix into an array of length `n * n`, sort the array, and return the `k`-th element after sorting. This solution is too easy and makes the problem meaningless.

Therefore, I suggest that more requirement should be added to this problem.

Two solutions should be accepted.

1. Maintain a min heap that stores `n` elements at most. Use the idea of merge sort to find the `k`-th smallest element. The time complexity is O(k log n) and the space complexity is O(n).
2. Use binary search to determine the value of the `k`-th smallest element. The time complexity is O(n log (high - low)) and the space complexity is O(1), where low = matrix[0][0] and high = matrix[n - 1][n - 1].

Other solutions that are too easy include sorting as described above and using a min heap to store the `k` smallest elements. These two solutions have time complexity O(n^2) and O(k) respectively. Since `k` is in the range `[1, n^2]`, there is O(k) = O(n^2).

To eliminate other solutions, one requirement can be added: The space complexity must be **better than** O(n^2) in the **worst case**.

#### Expected behavior
In problem description, one more requirement should be added: The space complexity must be **better than** O(n^2) in the **worst case**.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
