### ISSUE TITLE
Missing Test Case - 657. Robot Return to Origin

### ISSUE THREAD

**Issue by actsalan** [LeetCode-Feedback/LeetCode-Feedback#5228]
#### Your LeetCode username
actsalan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I try to have a look at the 1ms answer and find the code below. It use 10 for 'Up' and 'Down', 1 for 'Left' and 'Right'.
This should fail for testcases like "LLLLLLLLLLU" and "RRRRRRRRRRD". And should have more testcases for 100, 1000 maybe.

#### Code you used for Submit/Run operation

```
// Robot Return to Origin
class Solution {
    
    public boolean judgeCircle(String moves) {

        int desk = 0;
        int[] drawer = new int[26];
        drawer['L' - 'A'] = -1;
        drawer['U' - 'A'] = 10;
        drawer['R' - 'A'] = 1;
        drawer['D' - 'A'] = -10;
        for(char ch : moves.toCharArray()) {
          desk = desk + drawer[ch - 'A'];
        }
        return desk == 0;
        
    }
}
```

#### Language used for code

Java

#### Expected behavior
Should not be accepted as answer.

**Comment by LC-Sue** [comment]
Hi @actsalan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @actsalan,
Thank you for your feedback. Our team has looked into this issue and decided not the add the test case. Since it is hard to fail all the solutions that use constant values for the movement and since the user can change 10 to 100 and still AC the problem, we will not add this test case.
