### ISSUE TITLE
Invalid Test Case - 608. Tree Node

### ISSUE THREAD

**Issue by halhenke** [LeetCode-Feedback/LeetCode-Feedback#5229]
#### Your LeetCode username
hal9zillion

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The default test case does not run

#### Code you used for Submit/Run operation

```
select * from tree;
```

#### Language used for code
MSSQL

**Comment by LC-Sue** [comment]
Hi @halhenke 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @halhenke 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
