### ISSUE TITLE
70. Climbing Stairs – invalid testcase / missing constraint

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#523]
#### Your LeetCode username
metricquant

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The default solution overflows starting at `n = 46`. It raises the following error.

`Line 7: Char 15: runtime error: signed integer overflow: 1836311903 + 1134903170 cannot be represented in type 'int' (solution.cpp)`
#### Language used for code
C++

#### Expected behavior
I expected that there would be a constraint `1 <= n <= 45`.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
