### ISSUE TITLE
Submission errors: 441. Arranging Coins

### ISSUE THREAD

**Issue by iamrahulpanchal** [LeetCode-Feedback/LeetCode-Feedback#5230]
#### Your LeetCode username
iamrahulpanchal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Submission errors 

#### Description of the bug
While executing the code in the console it gives correct output but while submitting the code it throws a "Wrong Answer" error.

#### Code you used for Submit/Run operation

```
class Solution {
    
    static int maxLevel = 0;
    
    public int arrangeCoins(int n) {
        solve(1, n);
        return maxLevel - 1;
    }
    
    public void solve(int level, int n){
        n = n - level;
        level = level + 1;
        maxLevel = Math.max(level, maxLevel);
        
        if(n >= level){
            solve(level, n);
        }
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

If it is giving correct output in the console for a particular test case, then it should not throw a "Wrong Answer" error while submitting the code for the same test case

#### Screenshots

![1  Correct OP in Console](https://user-images.githubusercontent.com/39897999/140513106-279a54ca-7094-4fb6-8b2a-ad77b239a7a9.PNG)

![2  Submission Error](https://user-images.githubusercontent.com/39897999/140513182-0270f6fc-fabf-4a30-a5e0-c316d2713836.PNG)

#### Additional context

Hoping to get the Acceptance Criteria fixed because of 2 wrong submissions

**Comment by LC-Sue** [comment]
Hi @iamrahulpanchal 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
