### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by akash-pandey1729** [LeetCode-Feedback/LeetCode-Feedback#5231]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ This] Missing Test Cases 

#### Description of the bug
It is accepting O((m+n)log(m+n)) as a solution, whereas the question specifically asks for O(log(m+n)) solution. The test cases are not able to differentiate between the two run times. Kindly look into it

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @akash-pandey1729,
Thank you for reaching out, could you please provide the code that you used for submission?

**Comment by LC-Sue** [comment]
Hi @akash-pandey1729 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
