### ISSUE TITLE
Missing Test Case - 1967. Number of Strings That Appear as Substrings in Word

### ISSUE THREAD

**Issue by Rishavkumardubey** [LeetCode-Feedback/LeetCode-Feedback#5233]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

not working on 
["dojsf","v","hetnovaoigv","ksvqfdojsf","hetnovaoig","yskjs","sfr","msurztkvppptsluk","ndxffbkkvejuakduhdcfsdbgbt","znhdgtwzbnh","h","ocaualfiscmbpnfalypmtdppymw","w","o","sfjksvqfdo","odqvzuc","bozawheajcmlewptgssueylcxhx","bno","jhmarzsphxduvdktzqjiz","j","sfrjhetnov","vxv","ksvqfd","ognwvqtadalmav","yqbspvfwmvhycmghabigl","qyfaiazgdqaw","ojsfrj","ojsfrjhetn","fdojs","do","ovaoig","k","vrh","jsfrjhetnovaoigvgk"]
"csfjksvqfdojsfrjhetnovaoigvgk"
this input

**Comment by LC-Sue** [comment]
Hi @Rishavkumardubey,
Thank you for reaching out, could you please provide the code that you used for submission?

**Comment by LC-Sue** [comment]
Hi @Rishavkumardubey 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
