### ISSUE TITLE
Why Kotlin submission is so much slower than Java?

### ISSUE THREAD

**Issue by abdullahicyc** [LeetCode-Feedback/LeetCode-Feedback#5234]
#### Your LeetCode username
abdullahicyc

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int[] twoSum(int[] nums, int target) {
        return new int[]{0,0};
    }
}
```

#### Language used for code
- **Java** with Runtime: 0 ms

### and Again the same code in Kotlin with Runtime: 204 ms

```
// Two Sum
class Solution {
    fun twoSum(nums: IntArray, target: Int): IntArray {
        return intArrayOf(0,0)
    }
}
```

#### Expected behavior
I expect Runtime to be 0-2 ms since it's an O(1) operation.

**Comment by LC-Sue** [comment]
Hi @abdullahicyc,
Thank you for reaching out. Different languages run differently, I'd suggest comparing runtime for the same language! You could check the distribution of your code's runtime and see how it compares to other submissions. With that said, we will keep an eye on this issue, if more users report issues with Kotlin runtime, we will investigate further!
