### ISSUE TITLE
[no. 22] Error in runtime complexity derivation for brute-force solution

### ISSUE THREAD

**Issue by rectified95** [LeetCode-Feedback/LeetCode-Feedback#5235]
#### Your LeetCode username
rectified95

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The number of sequences of length n comprised of 2 characters 2^n rather than 2^(2n), which is what the article states.
The calculation of runtime complexity for the brute-force solution of problem no. 22 ("Generate Parentheses") is off:
The mistake is because they don't account for the shorter n-1 length sequence after you fix '(' or ')'.
2^(n-1) + 2^(n-1) = 2 * 2^(n-1) = 2^n

**Comment by LC-Sue** [comment]
Hi @rectified95,
Thank you for reaching out, could you please provide the problem number/link for this issue?

**Comment by rectified95** [comment]
@LC-Sue https://leetcode.com/problems/generate-parentheses/

**Comment by LC-Sue** [comment]
Hi @rectified95 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by rectified95** [comment]
@LC-Pam Were you able to make the fix in the end?

**Comment by LC-Pam** [comment]
Status: 
22. Generate Parentheses
in list [Pending]
Already submitted to the team.
Thank you for your support.
