### ISSUE TITLE
Wrong Python Type annotation for 117. Populating Next Right Pointers in Each Node II

### ISSUE THREAD

**Issue by b05902132** [LeetCode-Feedback/LeetCode-Feedback#5236]
#### Your LeetCode username
linlin110

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The default type annotation is
``` Python
class Solution:
    def connect(self, root: 'Node') -> 'Node':
```
This guarantees that `root` is not `None`, but there are test cases for `root` being `None`.

The correct type annotation should be:
``` Python
class Solution:
    def connect(self, root: Optional['Node']) -> Optional['Node'] :
```

#### Code you used for Submit/Run operation
Not applicable

#### Language used for code
Python3

#### Expected behavior
Correct type annotation.

**Comment by LC-Sue** [comment]
Hi @b05902132 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @b05902132 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
