### ISSUE TITLE
Feature request: allow contributing test cases from file

### ISSUE THREAD

**Issue by nevet** [LeetCode-Feedback/LeetCode-Feedback#524]
There is a 10000 char limit for test case, but for some extreme cases in some problems can easily break this limit. So it would be good if we could upload our test cases by file.

**Comment by CooperCooperCooper** [comment]
Hi @nevet ,
Thank you for reaching out to us. I've relayed your suggestion to our team for consideration. In the future, please file feature request to us via our [Main Support Channel](https://support.leetcode.com/hc/en-us). We appreciate your support.
