### ISSUE TITLE
551. Student Attendance Record I

### ISSUE THREAD

**Issue by sudhansusingh** [LeetCode-Feedback/LeetCode-Feedback#5245]
#### Category of the bug
- [ ] Question
- [👎 ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For test case "PPALLP" , when I run it sometimes it accepts the output . And for same code and same input  on running again ,it is saying wrong answer. I tried and ran this case multiple times and it is accepting sometimes and saying wrong answers sometimes for same code.
I checked it with other testcases , this is happening with other testcases too.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkRecord(string s) 
    {
        char prev='L';
        int count=0,countA,flag=0;
        for(int i=0;i<s.length();i++)
        {
            if(s[i]=='P')
                continue;
            if(s[i]=='A')
                countA++;
            if(s[i]=='L' && s[i]==prev)
                count++;
            else
            {
                count=0;
                //prev=s[i];
            }
            if(count>=3 || countA>1)
            {
                flag=1;
                break;
            }
        }
        if(flag==1)
            return false;
        else
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
It should either accept or reject a test case , but it is sometimes accepting and sometimes rejecting same test case for same written code.

#### Screenshots
![Screenshot (4)](https://user-images.githubusercontent.com/62203019/140636413-bd8fcf3c-0e69-4781-ad36-27e7c0e874ac.png)

**Comment by LC-Sue** [comment]
Hi @sudhansusingh,
Thank you for reaching out, when you refer to the code accepted, is this when you submit or run code? I submitted the code that you provided and it returns WA. Please feel free to refer to the discuss section of the problem and see how others have optimized their cod
![Uploading Screen Shot 2021-11-09 at 4.58.01 PM.png…]()
e!

**Comment by sudhansusingh** [comment]
Run the code for given test cases.

**Comment by LC-Sue** [comment]
Hi @sudhansusingh,
Thank you for responding! I double checked the run code, I am encountering the same issue. I will relay this issue over to our team to further investigate!

**Comment by LC-Sue** [comment]
Hi @sudhansusingh,
Hi @
Thank you for reaching out to us. The inconsistency is because some variables were not initialized as countA. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
