### ISSUE TITLE
292. Nim Game - Reference link is broken

### ISSUE THREAD

**Issue by sonergonul** [LeetCode-Feedback/LeetCode-Feedback#5246]
Hi

https://leetcode.com/problems/nim-game/solution/

On "References" part, Lecture on Nim Games hyperlink (https://cs.gmu.edu/~gordon/ysp/nim.pdf) seems broken. I think we can replace it with https://www.cs.umd.edu/~gasarch/TOPICS/nimnotes.pdf or web archive link as https://web.archive.org/web/20150528155700/https://www.cs.umd.edu/~gordon/ysp/nim.pdf

Leetcode username: @sonergonul

**Comment by LC-Sue** [comment]
Hi @sonergonul 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sonergonul 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
