### ISSUE TITLE
90. Subsets II

### ISSUE THREAD

**Issue by yesdeepakmittal** [LeetCode-Feedback/LeetCode-Feedback#5247]
If the element sequence of the individual subset differs from the expected output, it is showing an error given that subsets contain the same elements as the expected output. However, if the set contains subsets in any order it is not showing an error while submitting the code. Why?

Case 1:
Expected   - [ [1,2], [ ], [1], [2] ]
Submitted - [ [1], [ ], [1,2], [2] ] - > it is not showing error

Case 2:
Expected   - [ [1,2], [ ], [1], [2] ]
Submitted - [ [1], [ ], [2,1], [2] ] - > it is showing error

**Comment by LC-Sue** [comment]
Hi @yesdeepakmittal,
Thank you for reaching out. I ran both of the cases that you mentioned and both are working just fine! Please feel free to reach out if you have any other questions

![](https://files.slack.com/files-pri/T1144TA9E-F02LXN8SLBU/subsets_ii_1.png)

![](https://files.slack.com/files-pri/T1144TA9E-F02MAB3G533/subsets_ii_2.png)
