### ISSUE TITLE
Wrong Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by Mihir-Bhasin** [LeetCode-Feedback/LeetCode-Feedback#5248]
#### Your LeetCode username

mihirbhasin10

#### Category of the bug
- [# ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

the primary test case is given wrong as it has 2 6 in the test case which is wrong. it should have 1 6 instead of 2.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/57122515/140655372-87ccbe83-fb5c-409e-98f2-1c146404aed4.png)

**Comment by LC-Sue** [comment]
Hi @Mihir-Bhasin,
Thank you for reaching out, could you specify the test case that you are referring to? The default test case does not include 2 6.

**Comment by stormsunshine** [comment]
@Mihir-Bhasin Why do you think the test case is incorrect? The problem description never requires that all elements in the array should be distinct, therefore, the example that contains two elements 6 in the array is quite correct.

Please read the problem description carefully.

**Comment by Mihir-Bhasin** [comment]
I mean that the last 6 which is present should be absent

**Comment by Mihir-Bhasin** [comment]
Ohh never mind I get it now @stormsunshine  thanks.
