### ISSUE TITLE
Missing Test Case - 1326. Minimum Number of Taps to Open to Water a Garden

### ISSUE THREAD

**Issue by Justkiding** [LeetCode-Feedback/LeetCode-Feedback#5249]
#### Your LeetCode username
jdu15

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
My code will fail the following test case, but I am able to pass all the other test cases.
5
[4,3,1,2,0,0]
The reason is that my code does not take the range 2 into account since it could not reach the 0 indexes. However, the 2 needs to be turned on to cover the last spot in the garden.

#### Code you used for Submit/Run operation

```
class Solution {
    int[] dp;
    private int minTaps(int startIndex, int n, int[] ranges) {
        //System.out.println("startIndex " + startIndex + " sumTap" + sumTap);
        if (startIndex >= n) 
        {
            return 0;
        }
        if (dp[startIndex] != 0)
            return dp[startIndex];
        int maxI = 0;
        boolean found = false;
        for (int i = ranges.length -1; i >= startIndex; i--) {
            if (ranges[i] >= 1 && i - ranges[i]<=startIndex) {
                if (i + ranges[i] >= n){
                    for (int j = startIndex; j < ranges.length; j++)
                        dp[j] = 1;
                    return 1;
                }
                if (i + ranges[i] >= maxI + ranges[maxI]) {
                    found = true;
                    maxI = i;
                }
            }
        }
        if (found) {
            int value = minTaps(maxI + ranges[maxI], n , ranges);
            if (value!=Integer.MAX_VALUE) {
                dp[startIndex] = 1 + value;
                return dp[startIndex];
            }
        }
        dp[startIndex] = Integer.MAX_VALUE;

        return dp[startIndex];
    }
    public int minTaps(int n, int[] ranges) {
        dp = new int[n+1];
        minTaps(0,n,ranges);
        if (dp[0] == Integer.MAX_VALUE)
            return -1;
        return dp[0];
    }
}
```
#### Language used for code
Java

#### Expected behavior
My code will fail the following test case, but I am able to pass all the other test cases.
5
[4,3,1,2,0,0]

**Comment by LC-Sue** [comment]
Hi @Justkiding 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Justkiding 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
