### ISSUE TITLE
Contribute a test case

### ISSUE THREAD

**Issue by cowtony** [LeetCode-Feedback/LeetCode-Feedback#525]
#### Your LeetCode username

cowtony

#### Category of the bug
- [X] Question
957
- [ ] Solution
- [ ] Language

#### Description of the bug

Contribute a new test case when two sides of the array are none zero but N = 0.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> prisonAfterNDays(vector<int>& cells, int N) {
        N = N % 14 + 14;
        while (N--) {
            vector<int> next(cells.size(), 0);
            for (int i = 1; i < cells.size() - 1; i++) {
                next[i] = !(cells[i - 1] ^ cells[i + 1]);
            }
            cells = next;
        }
        return cells;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My code suppose to fail the test case 
```
[0,1,0,1,1,0,0,1]
0
```
But got an AC.

#### Screenshots

![image](https://user-images.githubusercontent.com/30167779/85433478-5ad6a080-b539-11ea-88e3-90430a0e919e.png)

**Comment by lc-christina** [comment]
Hi @cowtony 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
