### ISSUE TITLE
Missing Test Case - 698. Partition to K Equal Sum Subsets

### ISSUE THREAD

**Issue by Artod** [LeetCode-Feedback/LeetCode-Feedback#5250]
#### Your LeetCode username
artod

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I see a small error in Solution -> Approach 3 -> JavaScript:
 1. You do `let taken = new Array(n, false);` which will create just an array with two elements `[n, false]`. It should be `let taken = new Array(n).fill(false);`
2. In `memo` you directly use `taken` as a key. JS will stringify the array so as a key you will get something like `true,false,true,true` which is just adds unnecessary overheads (can be replaced with `1` and `0`)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Artod 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Artod 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
