### ISSUE TITLE
95. Unique Binary Search Trees II

### ISSUE THREAD

**Issue by Karan835452** [LeetCode-Feedback/LeetCode-Feedback#5252]
vector<TreeNode*> solve(int start,int end)
    {
        if(start>end)   //for handling boundary conidtion when i=start || i==end 
            return {nullptr};
        vector<TreeNode*>res;
        for(int i=start;i<=end;i++)   //this cycle will help us in making each node as root node once
        {
            vector<TreeNode*>left=(solve(start,i-1));   //left will store all possible leftsubtree
            vector<TreeNode*>right=(solve(i+1,end)) ;    //similarly right one will store all possible right substree
            for(auto lef:left)    //for each lef subtreee we are making combination with all right subtree to get all possible BST
            {
                for(auto rig:right)
                {
                   TreeNode* currroot=new TreeNode(i);
                    currroot->left=lef;
                    currroot->right=rig;
                    res.push_back(currroot);
                }
            }
                  
        }
        return res; 

    }
    vector<TreeNode*> generateTrees(int n) {
         return solve(1,n);
    }

**Comment by Leader-board** [comment]
What is the problem?

**Comment by LC-Sue** [comment]
Hi @Karan835452,
Thank you for reaching out,  I will close this ticket for now as I don't see any raised issue. Feel free to reach out if you have any other questions!
