### ISSUE TITLE
683. K Empty Slots allows Test Cases to not be from 1-N

### ISSUE THREAD

**Issue by brian-cai** [LeetCode-Feedback/LeetCode-Feedback#5254]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/k-empty-slots/
I put this test case into the console
```
[1,8,9,10,4]
3
```
and it allowed me to do so. I ended up getting an index out of bounds exception has 8 9 and 10 are much larger than 5.

From the description
```
1 <= bulbs[i] <= n
bulbs is a permutation of numbers from 1 to n.
```

#### Code you used for Submit/Run operation

N/A

#### Language used for code
N/A
(Java)

#### Expected behavior
The test cases submitted are rejected for being invalid.

**Comment by LC-Sue** [comment]
Hi @brian-cai,
Thank you for reaching out, could you please provide the code that you used for submission?

**Comment by brian-cai** [comment]
```

class Solution {
    public int kEmptySlots(int[] bulbs, int k) {
        int[] days = new int[bulbs.length];
        for (int i = 0; i < bulbs.length; i++) {
            days[bulbs[i]-1] = i+1;
        }
        
        int left = 0;
        int right = left+k+1;
        
        int ans = Integer.MAX_VALUE;
        for (int i = 1; right < days.length; i++) {
            //valid
            if (days[left] < days[i] && days[right] < days[i]) {
                //System.out.println(left + " " + i + " " + right);
                continue;
            }
            
            if (right == i) {
                //record blooming day 
                int bloomingDay = Math.max(days[left], days[right]);
                ans = Math.min(ans, bloomingDay);
            }      
                
                //continue sliding window
                left = i;
                right = i + k + 1;
        }
        
        //System.out.println();
        return ans == Integer.MAX_VALUE ? -1 : ans;
        
    }
}

```

**Comment by LC-Sue** [comment]
Hi @brian-cai 
Thank you for providing the code. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @brian-cai 
Thank you for your time. We've used fixed a bug in the validator. The test case is now invalid. Could you please provide your LeetCode username, we'd like to reward you for the contribution!

**Comment by brian-cai** [comment]
Please email me at `thebriancai [at] gmail [dot] com` for my username. (This is also the email I use for my account).

**Comment by LC-Sue** [comment]
Hi @brian-cai 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
