### ISSUE TITLE
Missing Test Case - 111. Minimum Depth of Binary Tree

### ISSUE THREAD

**Issue by pvk99** [LeetCode-Feedback/LeetCode-Feedback#5256]
#### Your LeetCode username

Varun (user813ht)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ !] Test Case Solution Clarification 

#### Description of the bug

The output that is shown for the second test case requires a change I think. It displays the output for the max depth and not the min depth. Please correct me if I'm wrong.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minDepth(TreeNode* root) {
        
        if(root == NULL)
            return 0;
        
        return min(minDepth(root->left), minDepth(root->right)) + 1;
    }
};
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
<!-- C++ -->
C++

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
The output that the above code produces for the test case root = [2,null,3,null,4,null,5,null,6] is 1. But the expected output shows up as 5.

#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
![image](https://user-images.githubusercontent.com/85697526/140785105-136fbeb2-64c5-4ab0-bbe0-eb87c0fe2b89.png)



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Sue** [comment]
Hi @pvk99,
Thank you for reaching out! Our judger looks to be working correctly. Please feel free to redirect to the discuss section of this problem to see how others have optimized their C++ code!
