### ISSUE TITLE
Wrong Test Case - 488. Zuma Game

### ISSUE THREAD

**Issue by lucifer1004** [LeetCode-Feedback/LeetCode-Feedback#5259]
#### Your LeetCode username
lucifer1004

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong Test Case

#### Description of the bug
For the input below,

```txt
"RRWWRRBBRR"
"WB"
```

There should be no valid solution since whether we insert `W` or `B` first, there will be only two `R`s left, which cannot be removed.

So the correct answer should be `-1`. But the jury yields `2` now.

#### Expected behavior

The jury should yield `-1` for the test case above.

**Comment by aziyatali** [comment]
Imagine your case: 
"RRWWRRBBRR"
"WB"

RRWWRRBBRR -> RRWWRRBBR[W]R -> RRWWRRBB[B]RWR -> RRWWRRRWR -> RRWWWR -> RRR -> empty

Since the board is empty and we used two hands, answer is 2.
