### ISSUE TITLE
In my `list` page, edit/rename with incorrect default string.

### ISSUE THREAD

**Issue by cowtony** [LeetCode-Feedback/LeetCode-Feedback#526]
#### Your LeetCode username

cowtony

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
**Frontend**

#### Description of the bug

In the list page, https://leetcode.com/list
After I edited one of my list name and try to edit another one, it will by default show the previous tag name instead of the current one, which is really confusing the user.

#### Expected behavior

The default string should show current tag name instead of my previous edited tag name.

#### Screenshots

![image](https://user-images.githubusercontent.com/30167779/85434314-b5243100-b53a-11ea-978d-23b36f94fb0e.png)

**Comment by CooperCooperCooper** [comment]
Hi @cowtony ,
Thank you for reaching out to us. To help me better understand this issue, did you click "Confirm" to save the current name before moving on to the next list name?

**Comment by cowtony** [comment]
> Hi @cowtony ,
> 
> Thank you for reaching out to us. To help me better understand this issue, did you click "Confirm" to save the current name before moving on to the next list name?

Yes, I do click confirm for my first edit. Then when I’m trying to edit the name for next one, it shows the default name as the previous text.

**Comment by CooperCooperCooper** [comment]
Hi @cowtony ,
Thank you for your answer. I've relayed this issue to our engineers to investigate. Since this channel is limited to [content-issues ](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!)only, I will close this ticket now. Thank you for your report.
