### ISSUE TITLE
261. Graph Valid Tree

### ISSUE THREAD

**Issue by chrisdoherty4** [LeetCode-Feedback/LeetCode-Feedback#5260]
#### Your LeetCode username
chrisdoherty4

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/graph-valid-tree/solution/

All of the solution implementations seem to assume the tree starts with node 0 but the question doesn't call that out (i.e. its implied). Some other node could be the root of the tree.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
N/A

#### Screenshots
N/A

#### Additional context
N/A

**Comment by LC-Sue** [comment]
Hi @chrisdoherty4 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @chrisdoherty4,
Thank you for your feedback. You're right, any node could be the root of the tree. If the graph is in fact a valid tree, then we can pick any node between 0 and n - 1, call that node the root, and the approaches will all work just as they do when we assume the root is 0. We will consider mentioning this when the article is next updated.

**Comment by chrisdoherty4** [comment]
@LC-Sue I agree all solutions work with any node. However, a solution that doesn't make any assumptions about the root node has added complexity vs a solution that is allowed to assume 0 is the root.

The solutions don't really suggest you need to care and assume 0 is the root but the question is laid out as if _any node_ could be the root so it leads you down a small rabbit hole.

**Comment by LC-Sue** [comment]
Hi @chrisdoherty4,
Thank you for the follow up. The feedback has already been passed over to the team and it will be considered when the article gets updated!
