### ISSUE TITLE
1178 Solution article - incorrect calculation of the maximal size of a trie.

### ISSUE THREAD

**Issue by MaksimIM** [LeetCode-Feedback/LeetCode-Feedback#5261]
#### Your LeetCode username
MaksimM

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution makes an incorrect claim.

The problem involves figuring out when the set of letters of a "word" are a subset of the letters of a "puzzle". In order to iterate over all the words efficiently, the solution suggests building a trie. It correctly notes that we can look only at words whose set of letters is at most 7 in length, and then we sort the letters, which further reduce the possible number of nodes. However, it then incorrectly states that "in conclusion, the maximum number of nodes in the trie is 7! = 5040". This is of course false. The correct number is the number of ways of choosing at most 7 (and at least 1) distinct letters from the set of 26 letters of the alphabet, i.e.  26 choose 7 + 26 choose 6 +...+26 choose 1= 971711. 

Moreover, the code provided does not seem to actually iterate over the trie. Instead, it seems to iterate over the permutations of letters in the puzzle, pruning possible words/trie paths as it goes along.

**Comment by LC-Sue** [comment]
Hi @MaksimIM 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @MaksimIM,
Thank you for your feedback. Our team has looked into this issue and a change will be made to address this in the near future!
