### ISSUE TITLE
Missing Test Case - 1178. Number of Valid Words for Each Puzzle

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#5265]
#### Your LeetCode username

archit91

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case - 

[LC_test_case_1178.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7502194/LC_test-1178.txt)

#### Code you used for Submit/Run operation

```
class Trie {
    Trie* chars[26] {};
    int endsHere = 0;
public:
    void insert(string& s) {
        Trie* cur = this;
        for(auto c : s) {
            if(!cur -> chars[c - 'a']) 
                cur -> chars[c - 'a'] = new Trie();            
            cur = cur -> chars[c - 'a'];
        }
        cur -> endsHere++;
    }
    
    int dfs(string& s, Trie* cur, bool hasFirst = false) {
        int ans = hasFirst ? cur -> endsHere : 0;
        for(auto c : s) 
            if(cur -> chars[c-'a']) 
                ans += dfs(s, cur -> chars[c-'a'], hasFirst | c == s[0]);
        return ans;
    }
};

class Solution {
public:
    vector<int> findNumOfValidWords(vector<string>& W, vector<string>& P) {
        vector<int> ans(size(P));
        Trie* root = new Trie();
        for(auto& word : W) 
            root -> insert(word);
        for(int i = 0; auto& puzzle : P) 
            ans[i++] = root -> dfs(puzzle, root);
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should be rejected since it fails and times out on a above-mentioned valid test case.

**Comment by LC-Sue** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
