### ISSUE TITLE
619 Table 'test.my_numbers' doesn't exist

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#5266]
**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
https://leetcode-cn.com/problems/biggest-single-number/
题目描述：
> 表 my_numbers 的 num 字段包含很多数字

实际：
> Table 'test.my_numbers' doesn't exist

**你使用的语言**
MYSQL

**你提交或者运行的代码**（提交的是题解中的答案）
```
SELECT MAX(num) AS 'num'
FROM 
    (
        SELECT num
        FROM my_numbers
        GROUP BY num
        HAVING COUNT(*) = 1
    ) AS tmp
;
```

**期望行为**
`my_numbers` 表应该存在
提交官方题解的答案，可以通过测试，而不是提示表不存在

**屏幕截图**
![image](https://user-images.githubusercontent.com/4961543/140879764-239e516b-b4a9-43ad-98dc-612f0dc25bbe.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目描述已更新，ID：mantoufan 给予积分奖励，请查收。
