### ISSUE TITLE
Missing Test Case - 64. Minimum Path Sum

### ISSUE THREAD

**Issue by soni113** [LeetCode-Feedback/LeetCode-Feedback#5269]
class Solution {
    public int minPathSum(int[][] grid) {
        int height = grid.length;
		int width = grid[0].length;
		int[][] dp = new int[height][width];
		dp[0][0] = grid[0][0];
		for (int i = 1; i < width; i++) 
			dp[0][i] = dp[0][i-1] + grid[0][i];
		for (int i = 1; i < height; i++) 
			dp[i][0] = dp[i-1][0] + grid[i][0];
		for (int i = 1; i < height; i++) {
			for (int j = 1; j < width; j++) {
				dp[i][j] = Math.min(dp[i-1][j], dp[i][j-1]) + grid[i][j];
			}
		}
		return dp[height-1][width-1];
        
        
    }
}

**Comment by LC-Sue** [comment]
Hi @soni113 ,
Thank you for reaching out. Please provide more details on your missing test case report. The code you used for submission and the missing test case.

**Comment by LC-Sue** [comment]
Hi @soni113 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
