### ISSUE TITLE
825. Friends Of Appropriate Ages - Missing output in example

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#527]
#### Your LeetCode username

roll_no_1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Example 3 does not have the output being displayed.

#### Code you used for Submit/Run operation
N/A

#### Language used for code

N/A

#### Expected behavior

The output for example 3 is 3.

#### Screenshots

![image](https://user-images.githubusercontent.com/36921843/85448280-2c49db80-b5b4-11ea-8e87-26a91da9aef5.png)

#### Additional context

https://leetcode.com/problems/friends-of-appropriate-ages

**Comment by lc-christina** [comment]
Hi @roll-no-1 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @roll-no-1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
