### ISSUE TITLE
?? Invalid Test Case - 1096. Brace Expansion II

### ISSUE THREAD

**Issue by gefeng** [LeetCode-Feedback/LeetCode-Feedback#5271]
#### Your LeetCode username

gefeng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Is test case 114 a valid one?
"{a,b},x{c,{d,e}y}"
According to the given definition,
"For expressions e1, e2, ... , ek with k >= 2, we have R({e1, e2, ...}) = R(e1) ∪ R(e2) ∪ ..."
So I suppose a valid union expression should be within a "{}"?
Or are you saying R(a,b,c,..) is a valid expression as well?
Please justify.

#### Code you used for Submit/Run operation

```
class Solution {
    int pos;
    int len;
    String exp;
    public List<String> braceExpansionII(String expression) {
        this.exp = expression;
        this.pos = 0;
        this.len = expression.length();
        
        List<String> ans = new ArrayList<>(conc());
        
        Collections.sort(ans);
        System.out.println(pos);
        return ans;
    }
    
    private Set<String> conc() {
        Set<String> ret = new HashSet<>();
        ret.add("");
        
        while(pos < len && exp.charAt(pos) != '}' && exp.charAt(pos) != ',') {
            Set<String> words = parse();
            Set<String> next = new HashSet<>();
            for(String x : ret) {
                for(String y : words) {
                    next.add(x + y);
                }
            }
            
            ret = next;
        }
        
        return ret;
    }
    
    /*
        either parse a words 
        or parse {...}
    */
    private Set<String> parse() {
        Set<String> ret = new HashSet<>();
        
        if(exp.charAt(pos) == '{') {
            pos++;
            
            while(true) {
                ret.addAll(conc());
                
                if(pos < len && exp.charAt(pos) == ',') {
                    pos++;
                } else {
                    break;
                }
            }
            pos++;
        } else {
            StringBuilder sb = new StringBuilder();
            while(pos < len && Character.isLetter(exp.charAt(pos))) {
                sb.append(exp.charAt(pos++));
            }
            ret.add(sb.toString());
        }
        
        return ret;
    }
}
```

#### Language used for code

Java

#### Screenshots

![image](https://user-images.githubusercontent.com/8019336/141138197-9656c415-4b68-43d1-8cfd-54a924e6e8a8.png)

**Comment by lucifer1004** [comment]
In the case above, things go like:

```
a,b,x{c,dy,ey}
a,b,xc,xdy,xey
```

**Comment by gefeng** [comment]
I mean I understand the general idea how it works. However I think this test case violate the definition of the "Union" operations.

Based on the description,

"Formally, the three rules for our grammar:

For every lowercase letter x, we have R(x) = {x}.
_For expressions e1, e2, ... , ek with k >= 2, we have R(**{**e1, e2, ...**}**) = R(e1) ∪ R(e2) ∪ ..._
For expressions e1 and e2, we have R(e1 + e2) = {a + b for (a, b) in R(e1) × R(e2)}, where + denotes concatenation, and × denotes the cartesian product. "

with my opinion, a valid union expression should be embraced by "{}". More specifically, for test case 114, it should be given as, **{**{a,b},x{c,{d,e}y}**}** .

**Comment by LC-Sue** [comment]
Hi @gefeng 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @gefeng 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
