### ISSUE TITLE
Missing Test Case - 875. Koko Eating Bananas

### ISSUE THREAD

**Issue by pantonov-gb** [LeetCode-Feedback/LeetCode-Feedback#5272]
#### Your LeetCode username
paaa

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug
Some of the fastest solutions won't pass this case.

[300000,4000,4000,4000,4000,4000,4000,4000,4000,5000]
6880

#### Code you used for Submit/Run operation

```
class Solution:
    def minEatingSpeed(self, piles: List[int], h: int) -> int:
        def possible(K):
            return sum((p-1) // K + 1 for p in piles) <= h
        
        if h == len(piles):
            return max(piles)
        
        total = sum(piles)
        lo = (total - 1) // h + 1
        hi = total // (h - len(piles))
        
        while lo < hi:
            mi = (lo + hi) // 2
            if not possible(mi):
                lo = mi + 1
            else:
                hi = mi
        return lo
```

#### Language used for code
python

#### Expected behavior
Solution is Accepted, but for given case it returns wrong answer (expected is 50, answer is 49)

**Comment by LC-Sue** [comment]
Hi @pantonov-gb,
Thank you for reaching out. The code that you provide is not accepted, so I am unable to check the missing test case. If you'd still like to report the missing test case, please provide the code that you submitted and is accepted and I will reopen the issue to look into it!
<img width="1433" alt="Screen Shot 2021-11-10 at 11 34 02 AM" src="https://user-images.githubusercontent.com/92285126/141181025-3e9b71ea-68ca-4e4a-a4db-c8526244cb6f.png">

**Comment by ddc67cd** [comment]
Nowadays, when someone says python he means python 3, not python 2.

**Comment by LC-Sue** [comment]
Hi @pantonov-gb 
Thank you for reaching out to us. I've relayed this issue to our team to investigate. And @ddc67cd, thank you for the clarification!

**Comment by LC-Sue** [comment]
Hi @pantonov-gb 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
