### ISSUE TITLE
Wrong explanation for an example - 465. Optimal Account Balancing

### ISSUE THREAD

**Issue by hacker-taso** [LeetCode-Feedback/LeetCode-Feedback#5273]
#### Your LeetCode username

tasotaso

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think in the second example,
```Therefore, person #0 only need to give person #1 $4, and all debt is settled.```
should be
```Therefore, person #1 only need to give person #0 $4, and all debt is settled.```

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @hacker-taso 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hacker-taso 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
