### ISSUE TITLE
Missing Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by ivanisakov99** [LeetCode-Feedback/LeetCode-Feedback#5274]
#### Your LeetCode username

isakovi

#### Category of the bug
- [Y ] Question
- [ ] Solution
- [Y ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The bottom up dp solution gives a runtime error of integer(int32_t) overflow in c++. Even though the question says, "It is guaranteed the answer fits on a 32-bit signed integer."

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int numDistinct(string s, string t){
        int n = s.length(), m = t.length();
        vector<vector<int32_t>> dp(m + 1, vector<int32_t>(n + 1, 0));

        for (int j = 0; j <= n; j++){
            dp[0][j] = 1;
        }

        for (int i = 1; i <= m; i++){
            for (int j = 1; j <= n; j++){
                if (t[i - 1] == s[j - 1]){
                    dp[i][j] = dp[i - 1][j - 1] + dp[i][j - 1];
                }
                else{
                    dp[i][j] = dp[i][j - 1];
                }
            }
        }
        return dp[m][n];
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected for it to work fine, but there was a test case that had an integer overflow

#### Screenshots

<img width="1186" alt="Screenshot 2021-11-10 at 16 51 55" src="https://user-images.githubusercontent.com/60196280/141199379-89b6a34b-38cd-4275-bb86-4cbb28c7699b.png">

**Comment by LC-Sue** [comment]
Hi @ivanisakov99 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ivanisakov99,
Thank you for your time. Our team has confirmed that the answer to all test cases indeed fits in 32-bit signed integer.
