### ISSUE TITLE
Missing Test Case - 629. K Inverse Pairs Array

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5275]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For problem [629. K Inverse Pairs Array](https://leetcode.com/problems/k-inverse-pairs-array), the expected time complexity should be O(nk). However, there exists a solution in Java that has time complexity O(n × k<sup>2</sup>) but can still get passed.
Therefore, I suggest that either the upper limits of `n` and `k` should be both increased to 2000 and add a new test case where `n = 2000` and `k = 2000`, or the time limit for Java should be reduced. Also, both enhancements can be added as well.
I do not know the time used for other languages like C++ or Python. Generally, only the solution with time complexity O(nk) should be accepted.

#### Code you used for Submit/Run operation
```
class Solution {
    int mod=1000000007;
    public int kInversePairs(int n, int k) {
        if(k>n*(n-1)/2){return 0;}
        int ans[][]=new int[n+1][k+1];
        for(int i=0;i<=n;i++){ans[i][0]=1;}
        for(int i=1;i<=n;i++){for(int j=1;j<=Math.min(k,i*(i-1)/2);j++){for(int p=Math.max(0,j-i+1);p<=Math.min(j,(i-1)*(i-2)/2);p++){ans[i][j]=(ans[i][j]+ans[i-1][p])%mod;}}}
        return ans[n][k];
    }
}
```

#### Language used for code
Java

#### Expected behavior
One of the following actions should be taken.

1. Update the constraints to `1 <= n <= 2000` and `1 <= k <= 2000`, and add a new test case where `n = 2000` and `k = 2000`.
2. Reduce the time limit of each test case.
3. Consider both points above.

This should be enhanced for at least the following three programming languages: Java, C++ and Python.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine
Thank you for your time. The current constraints are fine, changing them may add some risk to the other languages.
