### ISSUE TITLE
215. 数组中的第K个最大元素

### ISSUE THREAD

**Issue by zero-count** [LeetCode-Feedback/LeetCode-Feedback#5277]
**count**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x ] 编程语言
- [ ] 缺少测试用例

**描述**
提交代码后，对测试用例计算的结果与在playground和本地运行得到的结果不同

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    int qfind(vector<int> &nums, int left, int right, int k) {
        if (left == right) return nums[left];
        int picked = rand() % (right - left + 1) + left;
        swap(nums[picked], nums[right]);
        int index = left - 1;
        for (int i = left; i < right; ++i) {
            if (nums[i] >= nums[right]) {
                swap(nums[++index], nums[i]);
            }
        }
        swap(nums[right], nums[index + 1]);
        if (index + 1 == k) return nums[index];
        if (index + 1 > k) {
            return qfind(nums, left, index, k);
        } else {
            return qfind(nums, index + 2, right, k);
        }
    }

    int findKthLargest(vector<int> &nums, int k) {
        auto res =  qfind(nums, 0, nums.size() - 1, k);
        return res;
    }
};
```

**期望行为**
对于测试用例vector nums{2, 1}; int k = 1; 本地运行结果为2，实际提交得到的结果却是1

**屏幕截图**
![image](https://user-images.githubusercontent.com/49755065/141220597-fe6c90d3-2ca7-402b-9d07-a9c2da80c088.png)
![image](https://user-images.githubusercontent.com/49755065/141220698-dcfe12d1-d552-4016-916c-d5b17d84519a.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
