### ISSUE TITLE
Missing Test Case - 1491. Average Salary Excluding the Minimum and Maximum Salary

### ISSUE THREAD

**Issue by pranjalijain2509** [LeetCode-Feedback/LeetCode-Feedback#5279]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

In this the answer is wrong for some cases

**Comment by LC-Sue** [comment]
Hi @pranjalijain2509 ,
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
