### ISSUE TITLE
827. Making A Large Island - "Use Example Testcases" shows different testcases

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#528]
#### Your LeetCode username

roll_no_1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

On clicking the "Use Example Testcases" button on the problem link from the contest (https://leetcode.com/contest/weekly-contest-82/problems/making-a-large-island), the third example does not get copied. Instead, a different input is getting copied.

#### Code you used for Submit/Run operation
N/A

#### Language used for code

N/A

#### Expected behavior

On clicking "Use Example Testcases", the inputs should have been copied and the Custom Testase box should have contained all the three inputs with the third one being **[[1,1][1,1]]**. Instead, it shows up **[[0,0][0,0]]** as the third input.

#### Screenshots

![image](https://user-images.githubusercontent.com/36921843/85449056-f22d0980-b5b4-11ea-86af-a44a4d9e3cee.png)

Custom Testcase box after clicking  "Use Example Testcases" button:
![image](https://user-images.githubusercontent.com/36921843/85449096-007b2580-b5b5-11ea-8261-a11c808d6e66.png)

#### Additional context

Here's the link to the problem on the contest page: https://leetcode.com/contest/weekly-contest-82/problems/making-a-large-island

**Comment by lc-christina** [comment]
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. However, thanks for providing the feedback and I've relayed the issue for the team to investigate. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
