### ISSUE TITLE
Missing test case for 1413. Minimum Value to Get Positive Step by Step Sum

### ISSUE THREAD

**Issue by Khvalin** [LeetCode-Feedback/LeetCode-Feedback#5280]
#### Your LeetCode username
khvalin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✓] Missing Test Cases 

#### Description of the bug
Every test case with positive numbers only has a 1 in it, making a code below pass.

#### Code you used for Submit/Run operation

``` JS
/**
 * @param {number[]} nums
 * @return {number}
 */
var minStartValue = function(nums) {
   // FLAWED LOGIC for arrays of positive numbers
    let num = Math.min(...nums)
    if(num > 0){
        return num  // <== here is a problem, it should return 1 instead
    }
  // END OF FLAWED LOGIC
    
   // handle inputs with negative numbers:
    let res = 1
    let sum = 1
    for (const n of nums) {
        sum += n
        if (sum >= 1) {
            continue
        }
        
        res += 1 - sum
        sum = 1
    }
    
    return res
};
```

#### Language used for code
JS

#### Expected behavior
There should be test case like [2,3,4] or [100,100]

#### Screenshots
N/A

#### Additional context
Apparently, someone did submit a solution with this issue and passed all tests - https://leetcode.com/problems/minimum-value-to-get-positive-step-by-step-sum/discuss/1571288/100-faster-javascript-intuitive-solution/1146240
I also submitted a solution like that and got AC (submission 585451406)

**Comment by LC-Sue** [comment]
Hi @Khvalin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Khvalin,
Thank you for your time. We'd like to reward your account for this contribution, could you please provide your LeetCode username?

**Comment by Khvalin** [comment]
Hi.
my leetcode username is **khvalin**

**Comment by LC-Sue** [comment]
Hi @Khvalin 
Thank you for your time. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
