### ISSUE TITLE
Typo - 951. Flip Equivalent Binary Trees

### ISSUE THREAD

**Issue by siebenschlaefer** [LeetCode-Feedback/LeetCode-Feedback#5282]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

> return true if the two trees are flip equivelent or false otherwise.

"equivelent" is a typo, it should be "equivalent" just like in the title and the previous paragraph

**Comment by LC-Sue** [comment]
Hi @siebenschlaefer 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @siebenschlaefer 
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
