### ISSUE TITLE
Improper Problem Description - 378. Kth Smallest Element in a Sorted Matrix

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#5283]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
I think the solution with maintaining a min heap which stores n elements should be accepted. However, the time complexity of this solution is O(n^2logn) in the worst case because the input k=n^2 is possible. So, this solution doesn't match the requirement below:
You must find a solution with complexity better than O(n2).
Therefore I think this requirement should be changed to "You must find a solution with **space** complexity better than O(n^2) **in the worst case**"

Expected behavior
The requirement "You must find a solution with complexity better than O(n^2)" should be change to "You must find a solution with **space** complexity better than O(n^2) **in the worst case**"

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837
Thank you for your time. Our team has looked into the problem, the current requirements are fine and mirror what was asked in the interview.
