### ISSUE TITLE
Difference results between Run Code Result and Submission Result - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by Hide-on-bush2** [LeetCode-Feedback/LeetCode-Feedback#5284]
## Run Code Result

<img width="752" alt="Screen Shot 2021-11-12 at 3 46 10 PM" src="https://user-images.githubusercontent.com/54945764/141429642-7f48f416-5e84-42cf-862e-7b9e2405b3c9.png">

## Submission Result

<img width="609" alt="Screen Shot 2021-11-12 at 3 46 35 PM" src="https://user-images.githubusercontent.com/54945764/141429688-5161e574-73e5-413a-ba78-5a13cb107dca.png">

**Comment by LC-Sue** [comment]
Hi @Hide-on-bush2 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
