### ISSUE TITLE
Typo - 1413. Minimum Value to Get Positive Step by Step Sum

### ISSUE THREAD

**Issue by CosmoSt4r** [LeetCode-Feedback/LeetCode-Feedback#5285]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Minor typo at the very end of the solution to `1413. Minimum Value to Get Positive Step by Step Sum` problem.

> Algorithm
> Traverse the array nums and calcalate every step-by-step total...

`calcalate` -> `calculate`

**Comment by LC-Sue** [comment]
Hi @CosmoSt4r 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @CosmoSt4r 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
