### ISSUE TITLE
Follow-up Should Be Removed for 97. Interleaving String

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5287]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [97. Interleaving String](https://leetcode.com/problems/interleaving-string), there if a follow-up that requires using only `O(s2.length)` additional memory space.

I don't think this follow-up is necessary. This follow-up requires reducing memory complexity for dynamic programming. In fact, reducing memory complexity is widely used in dynamic programming problems, not specific for this problem. For 1D dynamic programming, sometimes the space complexity can be reduced from O(n) to O(1). For 2D dynamic programming, sometimes the space complexity can be reduced from O(mn) to O(n).

Although reducing memory complexity for dynamic programming may be required during an interview, I don't think it should be added as a follow-up, since reducing memory complexity for dynamic programming is quite common. If the follow-up is added for problem 97, then the same follow-up should be added to many other dynamic programming problems as well, which is quite time-consuming and unnecessary. Also, reducing memory complexity doesn't increase the difficulty of the problem, since the idea of dynamic programming remains the same, and reducing memory complexity only requires storing the previous row in 2D case or storing the previous element in 1D case.

#### Expected behavior
The follow-up for problem 97 should be removed.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine
Thank you for your time. Our team has looked into the problem and decided that the current follow-up is fine and  there is no need to remove it.
