### ISSUE TITLE
Wrong Test Case 31. Next Permutation

### ISSUE THREAD

**Issue by lzw1998** [LeetCode-Feedback/LeetCode-Feedback#5288]
#### Your LeetCode username
leungz

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem requires "0 <= nums[i] <= 100",so I used input case [1,4,32]. According to the requirement "rearranges numbers into the lexicographically next greater permutation of numbers " , I should get the output [32,1, 4], but submit output is [1,32,4].

#### Expected behavior

The requirement should be "0 <= nums[i] <= 9"

**Comment by LC-Sue** [comment]
Hi @lzw1998 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @lzw1998,
Thank you for your time. Our team has looked into the problem and both the constraints and expected outputs are fine. Feel free to refer to the problem discussion there are confusions about the expected output.
