### ISSUE TITLE
Test Case Enhancement - 418. Sentence Screen Fitting

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5289]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In [418. Sentence Screen Fitting](https://leetcode.com/problems/sentence-screen-fitting), the constraints are not large enough, and a solution that uses simulation can also get accepted. However, this problem is designed to be a dynamic programming problem, so a solution with a better time complexity should be required.

Therefore, I suggest that the maximum values for `rows` and `cols` should be increased to `10^5`, and there should be at least one test case that has `rows` and `cols` both equal to `10^5`. Consider the following test case, where `sentence` has length 100 and each element in `sentence` has length 5.

```
["aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa"]
100000
100000
```

Of course, the actual elements in `sentence` can be changed to more meaningful words.

By changing the constraints and adding the test case above, a naive solution that uses simulation will get TLE, and only dynamic programming solutions can be accepted.

Also, the difficulty of this problem should be changed to Hard.

#### Code you used for Submit/Run operation
The following code should get TLE after adding the new test case.
```
class Solution {
    public int wordsTyping(String[] sentence, int rows, int cols) {
        int wordIndex = 0, index = 0, currRowLen = 0;
        int res = 0;
        int n = sentence.length;
        int[] len = new int[n];
        for(int i = 0; i < n; i++){
            len[i] = sentence[i].length();
        }
        while(index < rows){
            currRowLen = 0;
            while(currRowLen + len[wordIndex] <= cols){
                currRowLen += len[wordIndex] + 1;
                wordIndex++;
                if(wordIndex == n){
                    res++;
                    wordIndex = 0;
                }
            }
            index++;
        }
        return res;
    }
}
```

The following code should get accepted after adding the new test case.
```
class Solution {
    public int wordsTyping(String[] sentence, int rows, int cols) {
        int n = sentence.length, wordIndex = 0;
        int[] len = new int[n];
        for(int i = 0; i < n; i++){
            len[i] = sentence[i].length();
        }
        int[] dp = new int[n];
        for(int i = 0; i < n; i++){
            wordIndex = i;
            int currRowLen = 0, times = 0;
            while(currRowLen + len[wordIndex] <= cols){
                currRowLen += len[wordIndex++] + 1;
                if(wordIndex == n){
                    wordIndex = 0;
                    times++;
                }
            }
            dp[i] = wordIndex + times * 100;
        }
        int index = 0, res = 0;
        wordIndex = 0;
        while(index < rows){
            index++;
            res += dp[wordIndex] / 100;
            wordIndex = dp[wordIndex] % 100;
        }
        return res;
    }
}
```

#### Language used for code
Java

#### Expected behavior
1. For problem 418, the maximum values for `rows` and `cols` should be increased to `10^5`.
2. Add a test cas that has `rows` and `cols` both equal to `10^5`. Please consider the test case, where `sentence` has length 100 and each element in `sentence` has length 5.
3. Change the difficulty of problem 418 to Hard.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your feedback. Our team has looked into the problem and decided that the current constraint is fine and matches the constraints asked in the real interview. There is no need to change them or to make the problem harder.

**Comment by stormsunshine** [comment]
@LC-Sue May I know the expected solution and the expected time complexity to this problem? That is, the solution with the highest time complexity that can be accepted in the interview. The constraints should meet the expected time complexity.

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for reaching out. I have relayed your feedback over to our team!

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for your time, I have confirmed again with our content team and they've concluded that the brute force is ok to pass.
