### ISSUE TITLE
Contributing TestCase

### ISSUE THREAD

**Issue by harshraj22** [LeetCode-Feedback/LeetCode-Feedback#529]
### problem [1361](https://leetcode.com/problems/validate-binary-tree-nodes/). Validate Binary Tree Nodes

<strong> Short Detail </strong>: Wrong code gets accepted, expected output doesn't match the code's output. Clearly weak test cases allow wrong solution getting accepted.

<strong>TestCase: </strong>
```
3
[1,-1,0]
[-1,-1,-1]
```

<strong> My Accepted C++ Code: </strong>
```c++
class Solution {
	void dfs(int index, vector<int> &leftChild, vector<int> &rightChild, vector<int> &visited, bool &isValid) {
		if (index >= leftChild.size() || index == -1 || !isValid)
			return;
		visited[index] += 1;
		isValid = (visited[index] > 1 ? false: isValid);
		dfs(leftChild[index], leftChild, rightChild, visited, isValid);		
		dfs(rightChild[index], leftChild, rightChild, visited, isValid);
	}

public:
    bool validateBinaryTreeNodes(int n, vector<int>& leftChild, vector<int>& rightChild) {
        if (n <= 1) return true;
        bool isValid = true;
        vector<int> visited(n, 0);
	    // dfs(0, leftChild, rightChild, visited, isValid);
	    for (int i = 0; i < n; i += 1) {
	    	if (leftChild[i] != -1 || rightChild[i] != -1) {
	    		dfs(i, leftChild, rightChild, visited, isValid);
	    		break;
	    	}
	    }

        // check if another component exists
        for (int i = 0; i < n; i += 1) {
        	if (!visited[i])
        		isValid = false;
        }

        // return final result
        return isValid;
    }
};
```

**Comment by lc-christina** [comment]
Hi,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @harshraj22 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by lkwq007** [comment]
@lc-christina 

I feel confused about why my direct test case submission on Leetcode Contribute got rejected. 
It's a similar test case. However, it was submitted 5 days ago.

**Comment by lc-christina** [comment]
Hi @lkwq007 ,

I apologize for the confusion we have caused. We encourage you to submit test cases via GitHub to get real-time feedback and reward.
