### ISSUE TITLE
Test Case Missing and Jury Does Not Work Correctly - 391. Perfect Rectangle

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5293]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [391. Perfect Rectangle](https://leetcode.com/problems/perfect-rectangle), when the input has large absolute values, the jury doesn't work correctly.
Consider the following test case.
```
[[-100000,-100000,100000,100000]]
```
When this test case is executed using custom test case, the jury doesn't work as expected, saying the test case is invalid. However, this test case does meet the constraints.

Please refer to the screenshot below.

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean isRectangleCover(int[][] rectangles) {
        long xMin = Integer.MAX_VALUE, yMin = Integer.MAX_VALUE;
        long xMax = Integer.MIN_VALUE, yMax = Integer.MIN_VALUE;
        Set<String> set = new HashSet<String>();
        long area = 0;
        for (int[] rectangle : rectangles) {
            long x1 = rectangle[0], y1 = rectangle[1], x2 = rectangle[2], y2 = rectangle[3];
            xMin = Math.min(xMin, x1);
            yMin = Math.min(yMin, y1);
            xMax = Math.max(xMax, x2);
            yMax = Math.max(yMax, y2);
            area += (x2 - x1) * (y2 - y1);
            long[][] points = {{x1, y1}, {x1, y2}, {x2, y1}, {x2, y2}};
            for (long[] point : points) {
                String pointStr = Arrays.toString(point);
                if (!set.add(pointStr))
                    set.remove(pointStr);
            }
        }
        if (set.size() != 4)
            return false;
        long[][] corners = {{xMin, yMin}, {xMin, yMax}, {xMax, yMin}, {xMax, yMax}};
        for (long[] corner : corners) {
            String cornerStr = Arrays.toString(corner);
            if (!set.contains(cornerStr))
                return false;
        }
        return (xMax - xMin) * (yMax - yMin) == area;
    }
}
```

#### Language used for code
Java

#### Expected behavior
1. The following test case should be added.
   ```
   [[-100000,-100000,100000,100000]]
   ```
2. The jury should work correctly and output the expected answer for the given test case.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/141643296-19ada23f-ede2-46fd-9961-739101d84496.png)

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've fixed the test case validator to accept this test case. We appreciate your support!
