### ISSUE TITLE
Please get the content coded in Javascript as well

### ISSUE THREAD

**Issue by giriprvn** [LeetCode-Feedback/LeetCode-Feedback#5294]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @giriprvn,
Thank you for reaching out. We will keep collecting our user feedback and make improvements in the next iteration. Thank you again for providing your valuable feedback!
