### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by Kenzku** [LeetCode-Feedback/LeetCode-Feedback#5295]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Test cases general

#### Description of the bug
Looks like the test case has a hard coded output

#### Code you used for Submit/Run operation

```
// rotate array
var rotate = function(nums, k) {
  k = k % nums.length;
  let a = [];
  for (let i = 0; i < nums.length; i = i + 1) {
    a[(i + k)%(nums.length)] = nums[i];
  }
    console.log(a)
  return a;
}

```

#### Language used for code

JS

#### Expected behavior

expect the return a holds the extra return value

#### Screenshots

<img width="991" alt="Screenshot 2021-11-14 at 0 53 25" src="https://user-images.githubusercontent.com/1387249/141652282-625ce3e1-c25e-4967-84fc-12ccab03836f.png">

<img width="981" alt="Screenshot 2021-11-14 at 0 53 04" src="https://user-images.githubusercontent.com/1387249/141652349-4784bb92-4bb1-4f2e-b3dd-7bc38aff5eab.png">

<img width="487" alt="Screenshot 2021-11-14 at 0 57 16" src="https://user-images.githubusercontent.com/1387249/141652290-42713ce7-96b3-47ca-b610-9af45dd73ea7.png">

**Comment by LC-Sue** [comment]
Hi @Kenzku,
Thank you for reaching out, our judger appears to be working correctly. Please feel free to refer to the discuss section of the problem to see how others have optimized their code!
