### ISSUE TITLE
Incorrect Constraint - 220. Contains Duplicate III

### ISSUE THREAD

**Issue by ArielRotem1** [LeetCode-Feedback/LeetCode-Feedback#5297]
#### Your LeetCode username
ariel_rotem

#### Category of the bug
- [ ] Incorrect constraint

#### Description of the bug
In the statement written: 
"return true if there are **two distinct indices** i and j in the array such that abs(nums[i] - nums[j]) <= t and abs(i - j) <= k". 
In that case k **couldn't be 0** because if k = 0, then i must be equal to j, but i and j are "**two distinct indices**". Which stand in contradiction to the constrain:  "0 <= k <= 10^4" which means that k **can be 0**.

#### Code you used for Submit/Run operation

```

class NumberAndIndex implements Comparable<NumberAndIndex> {
    public int index;
    public double value;
    
    public NumberAndIndex(int i, double v){
        index = i;
        value = v;
    }
    
    @Override
    public int compareTo(NumberAndIndex o) {
        if (value < o.value) return -1;
        else if (value > o.value) return 1;
        return 0;
    }
}


class Solution {
    public boolean containsNearbyAlmostDuplicate(int[] nums, int k, int t) {
        
        if(k == 0 || nums.length == 0) return false;
        
        List<NumberAndIndex> list = new ArrayList<>();
        
        for(int i = 0; i < nums.length; i++){
            list.add(new NumberAndIndex(i, nums[i]));
        }
        
        Collections.sort(list);
        
        for(int i = 0; i < nums.length; i++){
            
            for(int j = i + 1; j < nums.length && Math.abs(list.get(i).value - list.get(j).value) <= t; j++){
                if(Math.abs(list.get(i).index - list.get(j).index) <= k) return true;
            }
        }
        
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Constraint should be change to: "0 < k <= 10^4", which fix the contradiction.

#### Screenshots

The statement:
![image](https://user-images.githubusercontent.com/73435828/141651807-5e6383f8-4f2d-4b78-9d23-ee8d76c2dbb2.png)
The constraints:
![image](https://user-images.githubusercontent.com/73435828/141651826-b5518643-b0b3-4a34-861f-fc888d23d179.png)

#### Additional context

Farther more if k **can be 0** then the solution to the problem is very easy because there will always be abs(nums[i] - nums[j]) == 0 and abs(i - j) == 0 which would be right for the statement and the constraints (this case happens when i == j, except when the number of elements is 0).

**Comment by LC-Sue** [comment]
Hi @ArielRotem1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ArielRotem1,
Thank you for your time. Upon investigating the problem, there is no contradiction. The problem asks to return true or false. Cases when nums.length = 1 or k = 0 are intuitively false cases.
