### ISSUE TITLE
Missing Test Case - 136. Single Number

### ISSUE THREAD

**Issue by geethave** [LeetCode-Feedback/LeetCode-Feedback#5299]
#### Your LeetCode username

geethagv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1 ] Missing Test Cases 
- 

#### Description of the bug

Need to contribute code
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @geethave ,
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
