### ISSUE TITLE
Problem: rotated-digits, wrong description

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#53]
**What kind of the bug**

- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
https://leetcode.com/problems/rotated-digits/

I think there are something wrong in the description. 

"2 and 5 rotate to each other" While actually, after rotating 180 degree, 2 is still 2, and 5 is still 5.

**Comment by CooperCooperCooper** [comment]
Hi @caoxingdong,
Thank you for raising this issue to our attention. I've relayed it to our team to consider.

**Comment by CooperCooperCooper** [comment]
Hi @caoxingdong,
Thank you for your time. We've updated the description for "2" and "5" to better showcase the mirrored scenario.
