### ISSUE TITLE
Missing test case: [96. Unique Binary Search Trees]

### ISSUE THREAD

**Issue by sekhar179** [LeetCode-Feedback/LeetCode-Feedback#530]
#### Your LeetCode username

sekhar179

#### Category of the bug
- [v ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

This problem is missing a test case, so a solution without handling the corner case is accepted.
For the input: 0, the output should be 1 but it accepts a solution which produces output 0

#### Code you used for Submit/Run operation

```
// Unique Binary Search Trees
       class Solution {
public:
    int numTrees(int n) {
        int result = 0;
        if (!n) return n;
        vector Sum(n+1, 0);
        Sum[0] = 1;
        Sum[1] = 1;
        for (int i = 2; i <= n; i++)
        for (int j = 0; j < i; j++)
        Sum[i] += Sum[j] * Sum[i - 1 - j];
        return Sum[n];
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input: 0
Output: 1

**Comment by lc-christina** [comment]
Hi @sekhar179 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @sekhar179 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
