### ISSUE TITLE
 Wrong space complexity O(2 pow  V  ⋅V) , on page https://leetcode.com/explore/learn/card/graph/619/depth-first-search-in-graph/3850/

### ISSUE THREAD

**Issue by sudhirpatil** [LeetCode-Feedback/LeetCode-Feedback#5302]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @sudhirpatil 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sudhirpatil
Thank you for your time. In general, we do not include the space used by the output in the space complexity analysis. Thus the only space that is considered is the space used by the recursion call stack and the space used by the array called path.
