### ISSUE TITLE
Missing Test Case - 1286. Iterator for Combination

### ISSUE THREAD

**Issue by sentenzo** [LeetCode-Feedback/LeetCode-Feedback#5306]
#### Your LeetCode username
sentenzo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In case when `combinationLength == characters.length`, we are having a trivial sequence of one element (the initial `characters` string).

The input example:
```cpp
["CombinationIterator","hasNext","next","hasNext"]
[["a",1],[],[],[]]
```

The output should be:
```cpp
[null,true,"a",false]
```

[My solution](https://leetcode.com/submissions/detail/586974096/) was accepted by the testing system, yet my solution returns:
```cpp
[null,false,"a",false]
```

#### Code you used for Submit/Run operation
```py
class CombinationIterator:
    
    def get(self) -> str:
        return "".join([self.ori[i] for i, v in enumerate(self.bm) if v])
    
    def step(self):
        self.i += 1
        if self.bm[-1]:
            o = 0
            p = self.n -1
            while self.bm[p]:
                self.bm[p] = 0
                o += 1
                p -= 1
            while p >= 0 and not self.bm[p]:
                p -= 1
            if p >= 0:
                self.bm[p] = 0
                o += 1
            else:
                self.hn = False
            p += 1
            for j in range(o):
                self.bm[p + j] = 1
        else:
            for i in range(self.n-2, -1, -1):
                if self.bm[i]:
                    self.bm[i] = 0
                    self.bm[i + 1] = 1
                    break

    def __init__(self, characters: str, combinationLength: int):
        self.ori = characters
        self.n = len(self.ori)
        self.l = combinationLength
        self.i = 0
        self.hn = (self.n != self.l)
        self.bm = [1] * self.l + [0] * (self.n - self.l)

    def next(self) -> str:
        ans = self.get()
        self.step()
        return ans

    def hasNext(self) -> bool:
        return self.hn 
```

#### Language used for code
Python3

#### Expected behavior
See the "Description of the bug".

**Comment by LC-Sue** [comment]
Hi @sentenzo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sentenzo 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
