### ISSUE TITLE
136. Single Number 

### ISSUE THREAD

**Issue by rpmullig** [LeetCode-Feedback/LeetCode-Feedback#5307]
#### Your LeetCode username
rpmullig

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

Three solutions are not valid given the question's O(1) space requirement. 

#### Description of the bug

The question states only constant space utilization is allowed, making only one potential solution of the 4 provide viable: solution 4, the bit manipulation. Since the 3 other solutions presented don't satisfy the criteria of O(1) space, they should not be accepted and stated as such in their description.  

The O(N) space allocation would be very easy, but the bit manipulation makes it closer to a Medium than Easy. I think there should also be a hint given to suggest that bitwise operation is an option.

**Comment by Sky-Nik** [comment]
1. Related Topics already include "Bit Manipulation".

2. In an interview setting, a suboptimal solution is generally better than no solution, so I don't think that the provided suboptimal solutions should be removed.

**Comment by LC-Sue** [comment]
Hi @rpmullig,
Thank you for reaching out to us. The solution article was updated with cautionary note at the beginning of the article mentioning that only the fourth approach satisfies the requirements provided in the problem description and mentioned why the first three approaches are still included.
