### ISSUE TITLE
Missing Test Case - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by Janmansh** [LeetCode-Feedback/LeetCode-Feedback#5309]
#### Your LeetCode username
agarwaljanmansh

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Missing test case which lets wrong solutions pass.

#### Code you used for Submit/Run operation

```
import java.util.*;
class Solution {
    public int maxProduct(int[] nums) {
        if (nums == null || nums.length == 0) {
			return 0;
		}
		// Code here
		int[][] cache = new int[nums.length][2];
		cache[0] = new int[]{nums[0], nums[0]};
		int res = cache[0][0];
		for (int i=1; i<nums.length; i++) {
			int p1 = cache[i-1][1]*nums[i], p2 = cache[i-1][0]*nums[i];
			int min = Math.min(Math.min(nums[i], p1), p2);
			int max = Math.max(Math.max(nums[i], p1), p2);
			cache[i] = new int[]{max, min};
			res = Math.max(res, max);
		}
		
		return res;
    }
}

```

#### Language used for code
Java

#### Expected behavior
I have attached the input file. The correct output is 2034628608, but the given output is 1632586752.

[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7536226/1.txt)

**Comment by LC-Sue** [comment]
Hi @Janmansh,
Thank you for reaching out to us, and thank you for providing the file. However, the test case you provided is not formatted like the sample test cases. Therefore I can't run it on my end. It would be great if you could attach a formatted file for the missing test case!

**Comment by LC-Sue** [comment]
Hi @Janmansh 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
