### ISSUE TITLE
230. Kth Smallest Element in a BST: time complexity in the 2nd Approach

### ISSUE THREAD

**Issue by b10s** [LeetCode-Feedback/LeetCode-Feedback#531]
#### Your LeetCode username
b10s

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
I think in the exercise's solution the space complexity of the 2nd Apporach is not O(H+k) but O(H).
It is because being in any point of a tree, we can not be deeper than a tree's height.

**Comment by lc-christina** [comment]
Hi @b10s 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @b10s 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by b10s** [comment]
Thank you!

@lc-christina  ,

How can I spend LeetCoins?
Is it possible to buy LeetCode Premium subscription by LeetCoins?

**Comment by b10s** [comment]
cc: @lc-kate

**Comment by lc-christina** [comment]
Hi @b10s ,
Yes, you can redeem premium subscription with LeetCoins. Check out the [redeem page](https://leetcode.com/store/) for other ways to spend LeetCoins!
