### ISSUE TITLE
Missing Test Case - 368. Largest Divisible Subset

### ISSUE THREAD

**Issue by Sky-Nik** [LeetCode-Feedback/LeetCode-Feedback#5311]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The solution below gets AC in 0.4s. However, on my sample test, it takes more than 5 seconds. The testcase itself is large, so I provide a generator instead (in Python 3):

```python
print([2**a * 3**b * 5**c * 7**d for a in range(20) for b in range(15) for c in range(12) for d in range(10) if 2**a * 3**b * 5**c * 7**d < 2*10**9][:1000])
```

#### Code you used for Submit/Run operation

```java
class Solution {
    private int n;
    private int[] nums;
    private List<Map<Integer, Integer>> take;
    private List<Map<Integer, Integer>> skip;
    private ArrayList<Integer> ans = new ArrayList<>();

    public List<Integer> largestDivisibleSubset(int[] nums) {
        Arrays.sort(nums);
        this.nums = nums;
        n = nums.length;
        take = new ArrayList<>();
        skip = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            take.add(new HashMap<>());
            skip.add(new HashMap<>());
        }

        find(0, 1);
        buildAns(0, 1);
        return ans;
    }

    private void buildAns(int pos, int k) {
        if (pos == n) {
            return;
        }
        int maxTake = take.get(pos).getOrDefault(k, 0);
        int maxSkip = skip.get(pos).getOrDefault(k, 0);
        if (maxTake > maxSkip) {
            ans.add(nums[pos]);
            k = lcm(k, nums[pos]);
        }
        buildAns(pos + 1, k);
    }

    private int find(int pos, int k) {
        if (pos == n) {
           return 0;
        }

        int max = -1;
        if (take.get(pos).containsKey(k)) {
            max = Math.max(max, take.get(pos).get(k));
        }
        if (skip.get(pos).containsKey(k)) {
            max = Math.max(max, skip.get(pos).get(k));
        }
        if (max != -1) {
            return max;
        }

        int a1 = find(pos + 1, k);
        int a2 = 0;
        skip.get(pos).put(k, a1);
        if (k % nums[pos] == 0 || nums[pos] % k == 0) {
            a2 = find(pos + 1, lcm(k, nums[pos])) + 1;
            take.get(pos).put(k, a2);
        }
        return Math.max(a1, a2);
    }

    private int lcm(int a, int b) {
        return a * b / gcd(a, b);
    }

    private int gcd (int a, int b) {
        if (b == 0) {
            return a;
        } else {
            return gcd (b, a % b);
        }
    }
}
```

#### Language used for code

Java

#### Expected behavior

The generated testcase should be added and the solution above should TLE on it.

**Comment by Sky-Nik** [comment]
For some extra context, the above solution is missing one of the key observations. Namely, after the array is sorted, it is enough to ask for the next element of the answer to be divisible by the previous element only, instead of the lcm of all previous elements. Therefore, the solution has to make a ton of lcm calls, making it O(N^2 log max), and causing TLE.

However, this behavior is only visible if there are Ω(N^2) pairs (i, j) such that ai % aj == 0. Apparently, the current test suite lacks a test with a high number of such pairs for large N. One way to construct such a testcase is presented by the provided generator.

**Comment by LC-Sue** [comment]
Hi @Sky-Nik,
Thank you for reaching out to us. Could you please provide the full test case as an txt file?

**Comment by Sky-Nik** [comment]
Sure, here it goes: [gcd-heavy.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7552092/gcd-heavy.txt). The format is the one used for "run on custom testcase". Let me know if you need it in another format.

**Comment by LC-Sue** [comment]
Hi @Sky-Nik,
Thank you for providing the test case. I have relayed the issue over to our team to investigate.

**Comment by Sky-Nik** [comment]
By the way, I realized that I can actually count pairs (i, j) such that a[i] % a[j] == 0 or a[j] % a[i] == 0 in all the testcases myself. My results show that my testcase has 135'468 such pairs and the previous highest number was 13'138. (Both number can be about twice smaller if you count only ordered pairs).

**Comment by Sky-Nik** [comment]
Moreover, I came up with a test that has even more such pairs, namely 201 788.

Generator: 
```python
print([2**a * 3**b * 5**c for a in range(40) for b in range(40) for c in range(40) if 2**a * 3**b * 5**c < 2*10**9][:1000])
```

The idea here is that every pair is good with a probability of roughly 1/8 instead of 1/16 (in general, it is 1/2^(number of primes) that we take).

Txt file:
[gcd-heavy-2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7586074/gcd-heavy-2.txt)

**Comment by LC-Sue** [comment]
Hi @Sky-Nik 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
