### ISSUE TITLE
A Follow-up Requirement Should be Added - 166. Fraction to Recurring Decimal

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#5312]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug

There is an easy solution which uses a hash table to break from computing the repeating part in time. But the hash table is not nesscessary. In fact, user can write an algorithm using constant extra space to solve this problem. So, I think a follow-up requirement should be added to this question. 

Code you used for Submit/Run operation

The solution below only uses constant extra space.
```
class Solution:
    def fractionToDecimal(self, numerator: int, denominator: int) -> str:

        a,b = numerator,denominator
        sgn=1
        if a*b<0:
            sgn=-1
            a,b=abs(a),abs(b)
        gcdd = math.gcd(a, b)
        a //= gcdd
        b //= gcdd
        inter, a1 = divmod(a, b)
        if not a1:
            return str(inter) if sgn>0 else '-'+str(inter)

        notcir = 0  
        b1 = b
        while not b1 % 2: 
            b1 //= 2
            notcir += 1
        notcir1 = 0
        while not b1 % 5:
            b1 //= 5
            notcir1 += 1
        notcir = max(notcir,notcir1)

        ans = ''
        for _ in range(notcir):
            a1 *= 10
            ans += str(a1 // b)
            a1 %= b
        if abs(b1)!=1:
            ans += '('
            a2 = a1
            while True:
                a2 *= 10
                ans += str(a2 // b)
                a2 %= b
                if a2 == a1:
                    ans += ')'
                    break
        return str(inter) + '.' + ans if sgn>0 else '-'+str(inter)+'.'+ans
```

Language used for code
Python3

Expected behavior
The follow-up requirement below should be added：
Can you write an algorithm that uses constant extra space?

**Comment by Sky-Nik** [comment]
Very interesting solution indeed! I respect it when people walk the extra mile and investigate the question thoroughly.

However, LeetCode (unlike CodeForces) is a platform for interview questions and not just any programming challenges. Have you seen this follow-up in an interview, or did you come up with it yourself?

If this follow-up was never seen in an interview, then we may simply confuse our users by demanding too much of them.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837 
Thank you for your time. Our team believes that the follow up doesn't seem real for an interview. It may be challenging as a programming task but we prefer asking follow ups that seem real and can be asked in a real interview.
