### ISSUE TITLE
"Course Schedule II" testcase 6 evaluation is incorrect

### ISSUE THREAD

**Issue by returnpointer** [LeetCode-Feedback/LeetCode-Feedback#5314]
#### Your LeetCode username
nedg

#### Category of the bug
- [ ] Incorrect Test Case Evaluation

#### Description of the bug
"Course Schedule II" testcase 6 is incorrect
Input: 
numCourses: 2
prerequisites: []

With an empty list of prerequisites/courses there is no valid combination of courses 

#### Language used for code
Python

#### Screenshots
Attached

#### Additional context
https://leetcode.com/submissions/detail/587859356
<img width="274" alt="courseseched-testcase6" src="https://user-images.githubusercontent.com/38472775/141892624-aaf02fc1-30ea-4398-b260-e381da429c9c.PNG">

**Comment by Sky-Nik** [comment]
> With an empty list of prerequisites there is no valid combination of courses

This claim is just wrong, both in real life and under the conditions of the problem. Consider Algebra and English from elementary school. None of them has another as a prerequisite, yet you somehow completed both.

Perhaps your confusion arises from the completion order not being unique. In this case, you may return any valid order, just as the problem description says.

**Comment by returnpointer** [comment]
Thanks, I understand now. My confusion was assuming that you can only have courses with pre-requisites and I didn't consider the scenario where all courses could be mutually exclusive (i.e. all singletons). Makes sense!
