### ISSUE TITLE
797. All Paths From Source to Target Explore Video Solution

### ISSUE THREAD

**Issue by emeng13** [LeetCode-Feedback/LeetCode-Feedback#5315]
#### Your LeetCode username

ewm2136

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Video solutions for problem 797 All Paths From Source to Target for both DFS and BFS are misleading
https://leetcode.com/explore/learn/card/graph/619/depth-first-search-in-graph/3850/ (around 3:39)
"For a directed graph, we don't need to mark if it is visited because for any edge on a directed graph, there is only one direction to move."
https://leetcode.com/explore/learn/card/graph/620/breadth-first-search-in-graph/3854/ (around 3:27)
"We do not have to record which nodes are visited because this is a directed graph."

The above are misleading/false statements because directed graphs can still contain cycles depending on what edges it contains - problem 797 does not require marking nodes as visited because the problem explicitly states it is a directed acyclic graph, which is a small but important differentiator.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

N/A

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Sue** [comment]
Hi @emeng13 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @emeng13,
Thank you for bringing this issue to our attention, we have added it to our list of things to be addressed the next time we make corrections to videos.
