### ISSUE TITLE
Missing Test Case - 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by IlyaLykov** [LeetCode-Feedback/LeetCode-Feedback#5316]
#### Your LeetCode username

IlyaLykov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

[-476570184,-423568801,-385585840,-375390924,-364630569,-359795128,-281872968,-126410430,-75677925,-54214495,-49178055,-32637211,-32198215,3413177,19045759,62248526,67551536,113606647,155411580,164755463,164781059,203133270,277305105,284913246,285973110,296436629,325431544,357294459,378678394,399786157]
[-408663357,-404578641,-376531700,-311642519,-294905976,-232001207,-183530032,-141524508,-115652480,-70696522,-63386299,-54656543,-32316999,29714175,33993996,45020708,62165363,84210823,93905151,102177224,209285622,288668099,328300713,338684779,342861859,384940859,408019604,410097843,458721542,475395296]
899

#### Code you used for Submit/Run operation

```
public class Solution 
{
    public IList<IList<int>> KSmallestPairs(int[] nums1, int[] nums2, int k) 
    {
        if(nums1.Length * nums2.Length <= k)
        {
            List<IList<int>> res = new List<IList<int>>();
            foreach(var n1 in nums1)
            {
                foreach(var n2 in nums2)
                {
                    res.Add(new int[]{n1, n2});
                }
            }
            return res.OrderBy(p => p.Sum()).ToList();
        }
        
        var heap = new Heap(k);
        int len2 = (int)Math.Ceiling(Math.Sqrt(3 * k));
        int len1 = len2;
        for(int i = 0; i < nums1.Length && i <= len1; i++)
        {
            for(int j = 0; j < nums2.Length && j <= len2; j++)
            {
                heap.Add(nums1[i], nums2[j]);
            }
            len2--;
        }
        return heap.GetValues();
    }
}
public class Heap
{
    private int _size;
    private int _currSize;
    private SortedDictionary<int, List<int[]>> _heap;
    public Heap(int size)
    {
        _size = size;
        _currSize = 0;
        _heap = new SortedDictionary<int, List<int[]>>();
    }
    public void Add(int a, int b)
    {
        if(_currSize < _size)
        {
            AddPair(a, b);
            _currSize++;
        }
        else
        {
            if(a + b <= _heap.Keys.Last())
            {
                AddPair(a, b);
                int maxKey = _heap.Keys.Last();
                _heap[maxKey].RemoveAt(_heap[maxKey].Count - 1);
                if(_heap[maxKey].Count == 0) _heap.Remove(maxKey);
            }
        }
    }
    private void AddPair(int a, int b)
    {
        int sum = a + b;
        if(_heap.ContainsKey(sum) == false)
        {
            _heap.Add(sum, new List<int[]>());
        }
        _heap[sum].Add(new int[]{a, b});
    }
    public List<IList<int>> GetValues()
    {
        List<IList<int>> res = new List<IList<int>>();
        foreach(var kvp in _heap)
        {
            res.AddRange(kvp.Value);
        }
        return res;
    }
}
```

#### Language used for code

C#

#### Expected behavior

The solution should be rejected since it fails on the custom valid test case.

**Comment by LC-Sue** [comment]
Hi @IlyaLykov 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @IlyaLykov 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
