### ISSUE TITLE
用例的输出不正确

### ISSUE THREAD

**Issue by tinyhare** [LeetCode-Feedback/LeetCode-Feedback#5317]
**你的 LeetCode 用户名**
tinyhare

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
101题，126测试用例，程序输出不正确，明明输出应该是true，却判定我输出了false

**你使用的语言**
Python3

**你提交或者运行的代码**
```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    queue = []
    def isSymmetric(self, root: TreeNode) -> bool:
        self.inorder(root)
        return self.queue == self.queue[::-1]

    def inorder(self,root:TreeNode):
        if root == None:
            return
            
        self.inorder(root.left)
        self.queue.append(root.val)
        self.inorder(root.right)
```

**期望行为**
输出判定正确

**屏幕截图**
![image](https://user-images.githubusercontent.com/6851513/141956985-6a356f4d-bc66-493d-891c-85a69ab2cd72.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
