### ISSUE TITLE
Missing Test Case - 167. Two Sum II - Input Array Is Sorted

### ISSUE THREAD

**Issue by NipunSharma13028** [LeetCode-Feedback/LeetCode-Feedback#5318]
class Solution {
public:
    vector<int> twoSum(vector<int>& num, int target) {
         int st=0,en=num.size()-1;
        while(st<en){
            int sum=num[st]+num[en];
            if(sum==target)return vector<int>{st+1,en+1};
            else if(sum>target)en--;
            else st++;
        }
        return vector<int>{};
    }
};

**Comment by stormsunshine** [comment]
What's the test case that makes the code fail?

**Comment by LC-Sue** [comment]
Hi @NipunSharma13028,
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
