### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by jaronritter01** [LeetCode-Feedback/LeetCode-Feedback#5319]
#### Your LeetCode username

JaronRitter01

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

#### Description of the bug

When I submit it fails on test case 
"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"

due to timeout but when I take this and run using "run code" it executes about 600ms and passes. This should be running in roughly O(n^2) so it should be passing without a timeout error. 

#### Code you used for Submit/Run operation

```
class Solution:
    def longestPalindrome(self, s: str) -> str:

        checkList = [[False for i in range(len(s))] for j in range(len(s))]
        palandromeArr = []
        # this is the dynamic checker
        
        for i in range(len(s)):
            for j in range(len(s)):
                currentSub = s[j:i+1]
                if len(currentSub) == 0:
                    continue
                elif len(currentSub) == 1:
                    checkList[j][i] = True
                    palandromeArr.append(currentSub)
                elif len(currentSub) == 2:
                    if currentSub[0] == currentSub[1]:
                        checkList[j][i] = True
                        palandromeArr.append(currentSub)
                else:
                    if currentSub[0] == currentSub[len(currentSub) - 1] and checkList[j+1][i-1] == True:
                        checkList[j][i] = True
                        palandromeArr.append(currentSub)
                        
                    
        palandromeArr = sorted(palandromeArr, key=len)
        
    
        if palandromeArr:
            return palandromeArr[-1]
        else:
            return None
```

#### Language used for code

Python

**Comment by LC-Sue** [comment]
Hi @jaronritter01,
Thank you for reaching out. The code that you provide returns runtime error on my end. Would you be able to provide the submissions link for it?

**Comment by jaronritter01** [comment]
https://leetcode.com/submissions/detail/591239166/

**Comment by jaronritter01** [comment]
Not sure if this would help but I just ran it again and it failed on a
different input but I ran it using the custom input and it worked.
[image: leetcode_longest_paladromic_substing.png]

**Comment by LC-Sue** [comment]
Hi @jaronritter01 
Thank you for reaching out to us. Thank you for providing the submissions link. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out. This would not be a missing test case because the code itself fails. Please feel free to refer to the discuss section of the problem to see how others have optimized their code.
