### ISSUE TITLE
587. Erect the Fence |  Missing testcase

### ISSUE THREAD

**Issue by lumosan** [LeetCode-Feedback/LeetCode-Feedback#532]
#### Your LeetCode username
lumosan

#### Category of the bug
- [x] Solution
- [ ] Question
- [ ] Language

#### Description of the bug

A wrong solution was accepted because of a missing testcase.

#### Code you used for Submit/Run operation

```
import math

def compute(a, b):
    """Angle of vector a->b between 0 and pi"""
    atan = math.atan2(b[1] - a[1], b[0] - a[0])
    if atan >= 0:
        return atan
    return 2*math.pi + atan

def vecMod(v, ref=(0,0)):
    return math.sqrt((v[0] - ref[0])**2 + (v[1] - ref[1])**2)

class Solution:
    def outerTrees(self, points: List[List[int]]) -> List[List[int]]:
        stack = [(float('inf'), float('inf'))]
        max_y = [float('-inf'), float('-inf')]
        
        # Choose ref_point
        # find tree(s) with lowest y; they are all in perimeter
        for p in points:
            if p[1] < stack[-1][1]:
                stack = [p]
            elif p[1] == stack[-1][1]:
                stack.append(p)
        # sort them by increasing x
        stack.sort()
        ref_point = stack[-1] # equivalent to sorted(points, key=lambda p: (p[1], -p[0]))[0]
        # no need to look at angles of pi as they are in stack already
        
        # Sort points (p) by increasing angle of vector (ref_point -> p)
        sorted_points = []
        for p in points:
            if p[1] != ref_point[1]:
                sorted_points.append((compute(ref_point, p),
                                      -vecMod(p, ref_point), # if same angle, longer first
                                      (p[0], p[1])))
        sorted_points.sort()
        
        # If the angle of vector is <= pi/2, change the order to put shorter vectors first
        for i in range(len(sorted_points)):
            if sorted_points[i][0] <= math.pi / 2:
                sorted_points[i] = (sorted_points[i][0], -sorted_points[i][1], sorted_points[i][2])
        sorted_points.sort()
        
        # Iterate through points
        sorted_points.append((None, None, stack[0]))
        for _, _, p in sorted_points:
            while len(stack) >= 2 and compute(stack[-1], p) < compute(stack[-2], stack[-1]):
                stack.pop()
            if p != stack[0]:
                stack.append(p)
        return stack

```

#### Language used for code
Python3

#### Expected behavior
For the following triangles, all points should be in the perimeter. Although the code above doesn't do this, the solution is still accepted.

Input: [[0,2],[0,1],[0,0],[1,0],[2,0],[1,1]]
Output: [[0,0],[1,0],[2,0],[0,2],[0,1]]
Expected: [[0,2],[0,1],[1,0],[1,1],[2,0],[0,0]]

Input: [[0,2],[0,1],[0,0],[2,2]]
Output: [[0,0],[2,2],[0,2]]
Expected: [[0,2],[2,2],[0,1],[0,0]]

#### Additional context
The solution chooses a ref_point in the perimeter and iterates through  other nodes in counter-clock wise order. It uses a stack and appends new points so that there are only left-turns when visiting the points. 
     
   If appending a new point creates a right turn, it pops   points from the stack until the new point can be appended.
      
The bug in the code is that when several points are in the same angle with respect to the reference point, the order in which they are visited affects whether they are considered part of the perimeter or not. 

I also submitted the issue on LC.

**Comment by lc-kate** [comment]
Hi @lumosan ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @lumosan,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
