### ISSUE TITLE
Missing Test Case - 1040. Moving Stones Until Consecutive II

### ISSUE THREAD

**Issue by sparsh-67** [LeetCode-Feedback/LeetCode-Feedback#5320]
#### Your LeetCode username

feynman_1729_67
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There was a testcase missing that makes a lot of accepted solutions fail because of time limit exceeded (TLE)error it was a corner case in which a sliding window will give o(n^2) solution and to fix it people will have to use binar search instead So its a major bug indeed.
Missing TestCase  is attached below.

#### Code you used for Submit/Run operation

```
class Solution:
    def numMovesStonesII(self, a: List[int]) -> List[int]:
        n=len(a)
        a.sort()
        mx=max(a[-1]-a[1]-n+2,a[-2]-a[0]-n+2)
        mn=mx
        for i in range(n):
          j=i
          take=0
          while j<n and a[j]<=a[i]+n-1:
            take+=1
            j+=1
          if not (take==n-1 and a[j-1]-a[i]+1==n-1):
            mn=min(mn,n-take)
        return [mn,mx]
        
```

#### Language used for code
Python

#### Expected behavior

It was expected that the code should give TLE error because of the algo being o(n^2) but it actully worked thus your testcases for this problem are weak.

#### Screenshots

![Screenshot 2021-11-17 at 3 07 59 PM](https://user-images.githubusercontent.com/43761860/142175787-034b79be-2279-49b7-bdf4-7e592c151958.png)

#### Additional context

[LeetCode_Missing_TestCase.docx](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7553464/LeetCode_Missing_TestCase.docx)

**Comment by LC-Sue** [comment]
Hi @sparsh-67 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sparsh-67,
Thank you for your time, n = 10^4 and n^2 = 10^8 which is ok to pass. We did not add the test case as it doesn't fail the given solution.
