### ISSUE TITLE
Missing Test Case - 425. Word Squares

### ISSUE THREAD

**Issue by AlexanderSpirin** [LeetCode-Feedback/LeetCode-Feedback#5321]
#### Your LeetCode username
spirinap

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
This test case leads to the worst complexity 26**5
Java/Python solutions from Leetcode get Time Limit Exceeded on this test.

#### Additional context
Testcase:
```["aaaaa", "baaaa", "caaaa", "daaaa", "eaaaa", "faaaa", "gaaaa", "haaaa", "iaaaa", "jaaaa", "kaaaa", "laaaa", "maaaa", "naaaa", "oaaaa", "paaaa", "qaaaa", "raaaa", "saaaa", "taaaa", "uaaaa", "vaaaa", "waaaa", "xaaaa", "yaaaa", "zaaaa", "abaaa", "acaaa", "adaaa", "aeaaa", "afaaa", "agaaa", "ahaaa", "aiaaa", "ajaaa", "akaaa", "alaaa", "amaaa", "anaaa", "aoaaa", "apaaa", "aqaaa", "araaa", "asaaa", "ataaa", "auaaa", "avaaa", "awaaa", "axaaa", "ayaaa", "azaaa", "aabaa", "aacaa", "aadaa", "aaeaa", "aafaa", "aagaa", "aahaa", "aaiaa", "aajaa", "aakaa", "aalaa", "aamaa", "aanaa", "aaoaa", "aapaa", "aaqaa", "aaraa", "aasaa", "aataa", "aauaa", "aavaa", "aawaa", "aaxaa", "aayaa", "aazaa", "aaaba", "aaaca", "aaada", "aaaea", "aaafa", "aaaga", "aaaha", "aaaia", "aaaja", "aaaka", "aaala", "aaama", "aaana", "aaaoa", "aaapa", "aaaqa", "aaara", "aaasa", "aaata", "aaaua", "aaava", "aaawa", "aaaxa", "aaaya", "aaaza", "aaaab", "aaaac", "aaaad", "aaaae", "aaaaf", "aaaag", "aaaah", "aaaai", "aaaaj", "aaaak", "aaaal", "aaaam", "aaaan", "aaaao", "aaaap", "aaaaq", "aaaar", "aaaas", "aaaat", "aaaau", "aaaav", "aaaaw", "aaaax", "aaaay", "aaaaz"]```

**Comment by LC-Sue** [comment]
Hi @AlexanderSpirin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @AlexanderSpirin 
Thank you for your time. The intended solution is O(words.length * 26^words[0].length). With words[0].length = 5, there could be more than 10^11 operations which is not suitable. The test case provided is very good to consider but the output size is very long that it doesn't fit in the platform.
