### ISSUE TITLE
test table不存在 - 612

### ISSUE THREAD

**Issue by lleahchen** [LeetCode-Feedback/LeetCode-Feedback#5322]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
Table 'test.point_2d' doesn't exist

**你使用的语言**
sql

**你提交或者运行的代码**
```
select distance as shortest
from (SELECT
    p1.x,
    p1.y,
    p2.x,
    p2.y,
    SQRT((POW(p1.x - p2.x, 2) + POW(p1.y - p2.y, 2))) AS distance
FROM
    point_2d p1
        JOIN
    point_2d p2 ON p1.x != p2.x OR p1.y != p2.y
)x
order by distance limit 1;
```

**期望行为**

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lleahchen 你好，当前中文题面已调整，可使用表名 Point2D 或者 point2d。力扣会定期更新，保障稳定和体验优化。
