### ISSUE TITLE
Missing test case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by volyx** [LeetCode-Feedback/LeetCode-Feedback#5323]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

In Solutions there is a edge case when input is empty array

```java
public int removeDuplicates(int[] nums) {
    // Here for empty nums the ruslt should be 0 
    if (nums.length == 0) return 0;
    int i = 0;
    for (int j = 1; j < nums.length; j++) {
        if (nums[j] != nums[i]) {
            i++;
            nums[i] = nums[j];
        }
    }
    return i + 1;
}
```

#### Code you used for Submit/Run operation

```java
class Solution {
    public int removeDuplicates(int[] nums) {
        return 1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Test should fail

#### Screenshots

<img width="605" alt="image" src="https://user-images.githubusercontent.com/3828802/142235565-9dc4deda-539e-4839-aefa-978f68e7f6e2.png">

**Comment by volyx** [comment]
Duplicate of https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/2884

**Comment by LC-Sue** [comment]
Hi @volyx 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @volyx,
This issue has already been filed with our team, since this is a duplicate issue of a previously filed issue, I will close this for now!
