### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by chupapi-nya** [LeetCode-Feedback/LeetCode-Feedback#5324]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+] Missing Test Cases 

#### Code you used for Submit/Run operation
import java.util.*;
class Solution {
    public int removeDuplicates(int[] nums) {
       return (int)IntStream.of(nums).distinct().count();
    }
}
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @chupapi-nya,
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
