### ISSUE TITLE
Q aww qqq awwMissing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by Gulchexra2004** [LeetCode-Feedback/LeetCode-Feedback#5325]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Gulchexra2004,
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
