### ISSUE TITLE
Missing Test Case - 271. Encode and Decode Strings

### ISSUE THREAD

**Issue by Sushanto** [LeetCode-Feedback/LeetCode-Feedback#5327]
#### Your LeetCode username

5u5h4n70

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code is accepted even though it is failing on specific test case.
Test case - ["Hello","$#Sus$","World"]

#### Code you used for Submit/Run operation

```
class Codec {
    // Encodes a list of strings to a single string.
    fun encode(strs: List<String>): String {
        return strs.joinToString("$#Sus$")
    }

    // Decodes a single string to a list of strings.
    fun decode(s: String): List<String> {
        return s.split("$#Sus$")
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

Expected - On submission, result should be "Wrong Answer"
Actual - Code was accepted for test case - ["Hello","$#Sus$","World"]

#### Screenshots

![image](https://user-images.githubusercontent.com/13949911/142446471-26a92757-ccfe-427a-945b-237a4f1d5aa3.png)

**Comment by LC-Sue** [comment]
Hi @Sushanto 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Sushanto** [comment]
Hi @LC-Sue , any update on this?

**Comment by LC-Sue** [comment]
Hi @Sushanto,
Thank you for your time, our team has decided to not add this test case as it targets using a special delimiter but there is an uncountable number of special delimiters that can still be used to AC the problem even after adding this test case.
