### ISSUE TITLE
Wrong solution and checker - 410. Split Array Largest Sum

### ISSUE THREAD

**Issue by yersin** [LeetCode-Feedback/LeetCode-Feedback#5328]
#### Your LeetCode username

mukaiyersin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There are two screenshots, inputs with **same integers** but with **a different order**. 

This sample exhibit that **greedy algorithm** which explained on the **solution** (Approach 3) is **not correct**.
#### Expected behavior

I think the result should also be the same.

#### Screenshots

![image](https://user-images.githubusercontent.com/5346020/142465653-73dea873-8ca4-431e-8cd5-a34ea5e664f5.png)
![image](https://user-images.githubusercontent.com/5346020/142465850-6d4aa050-b5b6-4fee-8a6c-2753f79799d5.png)

**Comment by LC-Sue** [comment]
Hi @yersin,
Thank you for reaching out. Could you please provide the code you used for submission?
