### ISSUE TITLE
Missing Test Case - 1235. Maximum Profit in Job Scheduling

### ISSUE THREAD

**Issue by lucy1290** [LeetCode-Feedback/LeetCode-Feedback#5329]
#### Your LeetCode username
kuailema9089

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [v] Missing Test Cases 

#### Description of the bug
Code is accepted even though it is failing on specific test case.
Test case:
[4,3,1,2,4,8,3,3,3,9]
[5,6,3,5,9,9,8,5,7,10]
[9,9,5,12,10,11,10,4,14,7]

#### Code you used for Submit/Run operation
```
class Solution:
    def jobScheduling(self, startTime: List[int], endTime: List[int], profit: List[int]) -> int:
        N = len(startTime)
        info = sorted(list(zip(startTime, endTime, profit)), key=lambda x: x[1])
        def bs_find_pre_job(start, pre_ind):
            if info[0][1] > start:
                return -1
            lo = 0
            hi = pre_ind
            while lo < hi - 1:
                mi = lo + (hi - lo) // 2
                if info[mi][1] == start:
                    return mi
                elif info[mi][1] > start:
                    hi = mi - 1
                else:
                    lo = mi
            if info[hi][1] > start:
                return lo
            else:
                return hi
        ans = 0
        dp = [0]
        for i in range(1, N + 1):
            last_valid_ind = bs_find_pre_job(info[i - 1][0], i - 2)
            if last_valid_ind == -1:
                dp.append(max(dp[i - 1], info[i - 1][2]))
            else:
                dp.append(max(dp[i - 1], dp[last_valid_ind + 1] + info[i - 1][2]))
        return dp[-1]
```

#### Language used for code
Python3

#### Expected behavior
Expected - On submission, result should be "Wrong Answer"
Actual - Code was accepted for test case:
[4,3,1,2,4,8,3,3,3,9]
[5,6,3,5,9,9,8,5,7,10]
[9,9,5,12,10,11,10,4,14,7]

#### Screenshots
<img width="1434" alt="Screen Shot 2021-11-18 at 5 34 36 PM" src="https://user-images.githubusercontent.com/91992437/142541868-adf5395d-8246-489d-ac70-792c67b5f701.png">

**Comment by LC-Sue** [comment]
Hi @lucy1290 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @lucy1290 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by lucy1290** [comment]
Thank you very much!
