### ISSUE TITLE
859. Buddy Strings Missing Test Cases

### ISSUE THREAD

**Issue by EddieXu123** [LeetCode-Feedback/LeetCode-Feedback#533]
#### Your LeetCode username

xutopia

#### Category of the bug
- [ 859 ] Question
- [ Missing Test Cases ] Solution
- [ Java ] Language

#### Description of the bug

The solution is missing a test case. My code was accepted but when I tried running the test case of: "aaab" and "aaab", the console output an error.

#### Code you used for Submit/Run operation
```
// Buddy Strings
class Solution {
    public boolean buddyStrings(String A, String B) {
        HashMap<Character, Integer> map = new HashMap<>();
        int counter = 0;
        if (A.length() != B.length() || A.length() == 0 || B.length() == 0) return false;
        
        for (int i = 0; i < A.length(); i++) {
            if (A.charAt(i) != B.charAt(i)) counter++;
        }
                
        if (counter != 0 && counter != 2) return false;
                
        for (Character c : A.toCharArray()) {
            map.put(c, map.getOrDefault(c, 0) + 1);
        }
        
        for (Character c : map.keySet()) {
            if (map.get(c) % 2 != 0 && counter == 0) return false;
        }
        
        for (Character c : B.toCharArray()) {
            if (map.get(c) == null || map.get(c) < 0) return false;
            map.put(c, map.get(c) - 1);
        }
        
        for (Character c : map.keySet()) {
            if (map.get(c) == null || map.get(c) != 0) return false;
        }
        
        return true;
    }
}
```

#### Expected behavior

When testing the test case: "aaab" and "aaab", the console output a warning while my solution was accepted when I ran it.

#### Additional context

This is my first report I'm not sure if this is where I write it but thanks for reading <3

**Comment by lc-christina** [comment]
Hi @EddieXu123 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @EddieXu123 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
