### ISSUE TITLE
Missing Test Case - 951. Flip Equivalent Binary Trees

### ISSUE THREAD

**Issue by ravirajbhatane** [LeetCode-Feedback/LeetCode-Feedback#5330]
#### Your LeetCode username
rb

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Missing test case

#### Code you used for Submit/Run operation
[1,null,3]
[1,2,3]

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @ravirajbhatane,
Thank you for reaching out. Could you please provide the code you used for submission?

**Comment by ravirajbhatane** [comment]
Sure, here it is --

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x),
left(left), right(right) {}
 * };
 */
class Solution {
public:
    bool flipEquiv(TreeNode* root1, TreeNode* root2) {
        if (root1 == nullptr && root2 == nullptr) {
            return true;
        }

        if (root1 == nullptr || root2 == nullptr) {
            return false;
        }

        if (root1->val != root2->val) {
            return false;
        }

        bool left = true;
        bool right = true;
        if (root1->left) {
            if (!root2->left || root1->left->val != root2->left->val) {
                swap(root2->left, root2->right);
            }

            left = flipEquiv(root1->left, root2->left);
            right = flipEquiv(root1->right, root2->right);
        } else {
            right = flipEquiv(root1->right, root2->left) ||
flipEquiv(root1->right, root2->right);
        }

        return left && right;
    }
};

- Raviraj

**Comment by LC-Sue** [comment]
Hi @ravirajbhatane 
Thank you for providing the code. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ravirajbhatane 
Thank you for your time. We've used your feedback to update the problem. Could you please provide your LeetCode username, we'd like to reward you for the contribution!

**Comment by ravirajbhatane** [comment]
Thank you!

My LeetCode username is ravirajbhatane.

- Raviraj

**Comment by LC-Sue** [comment]
Hi @ravirajbhatane 
Thank you for providing your username. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
