### ISSUE TITLE
Missing Test Case - 347. Top K Frequent Elements

### ISSUE THREAD

**Issue by naveedgaibu03** [LeetCode-Feedback/LeetCode-Feedback#5332]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by naveedgaibu03** [comment]
Question and Answer of leetcode

**Comment by LC-Sue** [comment]
Hi @naveedgaibu03 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
