### ISSUE TITLE
Missing Test Case - 112. Path Sum

### ISSUE THREAD

**Issue by devmohit-live** [LeetCode-Feedback/LeetCode-Feedback#5333]
#### Category of the bug
- [x] Question

#### Description of the bug

Proper explanation for the following test case should be provided in the problem description for better understanding :
[]
0
For null node the default sum be can treated as 0 or not.

#### Expected behavior

The Default answer provided is false.
Either we can provide the proper explanation for this case in description or can change the default answer to true.

**Comment by LC-Sue** [comment]
Hi @devmohit-live 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @devmohit-live 
Thank you for your time. We've added explanations to the problem. We appreciate your support!

**Comment by devmohit-live** [comment]
Great Thank you.
