### ISSUE TITLE
1466. Reorder Routes, missing test case: adversarial ordering of edge list

### ISSUE THREAD

**Issue by jkerkhoff** [LeetCode-Feedback/LeetCode-Feedback#5334]
#### Your LeetCode username

prefer not to say

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Solution presented below should time out, because its worst-case complexity is O(n^2) (e.g. when the tree is a line and the edges are sorted in order of decreasing distance to vertex 0). Instead it is accepted, and achieves the 99th percentile for speed.

#### Code you used for Submit/Run operation

```python3
class Solution:
    def minReorder(self, n: int, connections: List[List[int]]) -> int:
        redirect_count = 0
        
        connections = deque(connections)
        processed = {0}
        while connections:
            v, w = connections.popleft()
            
            if v in processed:
                redirect_count += 1
                processed.add(w)
            elif w in processed:
                processed.add(v)
            else:
                connections.append((v, w))
        
        return redirect_count
```

#### Language used for code

Python 3

#### Expected behavior

Solution should time out on a test case similar to the following when submitted:
```python3
50000
[[49998,49999],[49997,49998], ..., [1,2],[0,1]]
```

Vertex indices should probably be shuffled so that just sorting the edges does not circumvent the test case.

**Comment by LC-Sue** [comment]
Hi @jkerkhoff,
Thank you for reaching out to us. Could you please provide the full test case that you suggest adding in a txt file?

**Comment by jkerkhoff** [comment]
Sure: [test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7597555/test_case.txt). I generated it with this script:
```python
from random import shuffle, randrange, seed

seed(1466)

n = 50000

permutation = list(range(1, n))
shuffle(permutation)

root_pos = randrange(n // 3, 2 * n // 3)
permutation.insert(root_pos, 0)

connections = []
for i in range(n - 1):
    v = permutation[i]
    w = permutation[i + 1]

    connections.append([v, w] if randrange(2) else [w, v])

if __name__ == '__main__':
    with open('test_case.txt', 'w') as f:
        f.write(f"{n}\n")
        f.write(str(connections).replace(' ', ''))
        f.write('\n')

```

**Comment by LC-Sue** [comment]
Hi @jkerkhoff 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jkerkhoff 
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username?

**Comment by jkerkhoff** [comment]
@LC-Sue I prefer if people couldn't find my name by googling my leetcode username. Is there a way for me to send it privately?

**Comment by LC-Sue** [comment]
Hi @jkerkhoff, 
If you'd prefer, you can give me your email and I will send a private message for your username.

**Comment by jkerkhoff** [comment]
@LC-Sue Sure! It's `j@[my github username].com`

**Comment by LC-Sue** [comment]
Hi @jkerkhoff 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
