### ISSUE TITLE
Missing Test Case - 785. Is Graph Bipartite?

### ISSUE THREAD

**Issue by D-Minor** [LeetCode-Feedback/LeetCode-Feedback#5335]
#### Your LeetCode username

Alwaysjudging

#### Category of the bug
- [ ] Question

#### Description of the bug

When I submitted the code it failed on test case of [[1,2],[0,2],[0,1]]
But when I took this test case and ran it, it passed...

#### Code you used for Submit/Run operation

```
N = 100010
M = N * 2
h, e, ne = [-1] * N, [0] * M, [0] * M
idx = 0
color = [0] * N

class Solution:
    def isBipartite(self, graph: List[List[int]]) -> bool:
        n = len(graph)
        for a, nodes in enumerate(graph):
            for b in nodes:
                self.add(a, b)
                self.add(b, a)
        
        
        for i in range(n):
            if color[i] == 0:
                if not self.dfs(i, 1):
                    return False
        return True


    def add(self, a, b):
        global idx
        e[idx] = b
        ne[idx] = h[a]
        h[a] = idx
        idx += 1


    def dfs(self, u, c):
        color[u] = c

        i = h[u]
        while i != -1:
            j = e[i]
            if color[j] == 0:
                if not self.dfs(j, 3 - c):
                    return False
            elif color[j] == c:
                return False
            i = ne[i]

        return True


```

#### Language used for code

Python 3

#### Expected behavior

I expect the solution is accepted 

#### Screenshots

As in the screenshot, the failed test case in submission passed when I am running the test:
![image](https://user-images.githubusercontent.com/30164661/142636828-22214a88-66cb-4182-8394-c68de799b592.png)

**Comment by LC-Sue** [comment]
Hi @D-Minor 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
