### ISSUE TITLE
[5,1,4,null,null,3,6]

### ISSUE THREAD

**Issue by KevinGuoXuanDon** [LeetCode-Feedback/LeetCode-Feedback#5336]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @KevinGuoXuanDon,
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
