### ISSUE TITLE
Improve Language in 21. Merge Two Sorted Lists

### ISSUE THREAD

**Issue by TimeTerminal** [LeetCode-Feedback/LeetCode-Feedback#5337]
#### Your LeetCode username
SpindlingPanda

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The [question](https://leetcode.com/problems/merge-two-sorted-lists/) is defined as:

> Merge two sorted linked lists and return it as a sorted list. The list should be made by splicing together the nodes of the first two lists."

Languages like JavaScript often use the word "list" to mean arrays. And seeing the syntax as well as question, it isn't inherently apparent that the output is requiring a linked list. Therefore, the question should be updated to mentioned "linked list" any time "list" is mentioned to be explicit.

#### Language used for code
JavaScript

#### Expected behavior

Update language to be:

Merge two sorted **linked** lists and return it as a sorted **linked** list. The **linked** list should be made by splicing together the nodes of the first two **linked** lists.

**Comment by LC-Sue** [comment]
Hi @TimeTerminal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @TimeTerminal 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by TimeTerminal** [comment]
Thanks @LC-Sue!
