### ISSUE TITLE
typo in 1467. Probability of a Two Boxes Having The Same Number of Distinct Balls

### ISSUE THREAD

**Issue by Goldenlion5648** [LeetCode-Feedback/LeetCode-Feedback#5338]
#### Your LeetCode username

Goldenlion5648

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Explanation 2 spells "equal" as "equale"

**Comment by LC-Sue** [comment]
Hi @Goldenlion5648 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Goldenlion5648 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
