### ISSUE TITLE
Problem Description Improper - 378. Kth Smallest Element in a Sorted Matrix

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5339]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This issue is to reopen #5227 and #5283 .

I created issue #5227 and required enhancing problem description. Although the problem description was enhanced, it was not updated correctly. Therefore, I asked another user to create issue #5283 , but obviously @LC-Sue did not get the point.

Now the last sentence in problem description before the examples is: You must find a solution with complexity better than O(n<sup>2</sup>). This sentence is improper and needs to be updated. The reason is as follows.

1. In my issue #5227 , I required adding a constraint on space complexity, not time complexity. Please refer to my previous issue.
2. When we talk about complexity without explicitly mentioning time complexity or space complexity, we are talking about time complexity. Therefore, If the constraint is about space complexity, the term "space complexity" must be explicitly mentioned, where the word "space" cannot be omitted.

Therefore, the last sentence in problem description before the examples should be updated to: You must find a solution with space complexity better than O(n<sup>2</sup>). **The word "space" must be added, or else the requirement is completely different.**

Also, the follow-up of the problem should be removed, since none of the solutions I mentioned in #5227 have time complexity O(n). I don't think there exists a solution with O(n) time complexity. Although there do exist some solution that exclaim O(n) complexity, I don't think these solution really have time complexity O(n).

#### Expected behavior
1. Two modification should be done to the last sentence in problem description before the examples.
    i. Add the word "space" before "complexity". The word "space" must be added and cannot be omitted. **This must be added, since space complexity is quite different from time complexity.**
    ii. Add the term "in the worst case" at the end of the the sentence. **This is optional, but it's better to add this.**
2. The follow-up should be removed.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us.  I will raise the issue again to our content team.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem statement. We appreciate your support!
