### ISSUE TITLE
1364. 顾客的可信联系人数量  题目描述小错误

### ISSUE THREAD

**Issue by xmcgcg** [LeetCode-Feedback/LeetCode-Feedback#534]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
（中文版）题目描述中“联系方式表”和“发票表”中均出现了：
> 编号为 `use_id` 的顾客

但是这两张表里表示顾客编号的列名是 `user_id`。

**期望行为**
将这两处  `use_id` 改为 `user_id`。

**Comment by PsiACE** [comment]
非常感谢您的反馈，此问题现已修复，请您刷新网页后查看。
