### ISSUE TITLE
Test Case TLE Result Inconsistent in Run Code and Submission - 629. K Inverse Pairs Array

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5340]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [629. K Inverse Pairs Array](https://leetcode.com/problems/k-inverse-pairs-array), the TLE message is inconsist between running user test case and submission. Consider the test case where n = 1000 and k = 1000, which already exists in this problem. Please refer to the first screenshot.

When submitting the following code, the TLE message is for the total run time, not for any single test case. However, when running the following code using custom test case and entering the test case n = 1000 and k = 1000, the single test case gets TLE, which does not happen in submission. Please refer to the second screenshot and the third screenshot.

Therefore, the TLE message is inconsistent between submission and running custom test case. The behavior should be the same, so I suggest that when submitting the following code, the TLE message should be displayed for the specific test case, not for total run time.

I believe this can be done by setting the maximum run time for single test case to the same value for submission and running custom test case.

#### Code you used for Submit/Run operation
```
class Solution {
    int mod=1000000007;
    public int kInversePairs(int n, int k) {
        if(k>n*(n-1)/2){return 0;}
        int ans[][]=new int[n+1][k+1];
        for(int i=0;i<=n;i++){ans[i][0]=1;}
        for(int i=1;i<=n;i++){for(int j=1;j<=Math.min(k,i*(i-1)/2);j++){for(int p=Math.max(0,j-i+1);p<=Math.min(j,(i-1)*(i-2)/2);p++){ans[i][j]=(ans[i][j]+ans[i-1][p])%mod;}}}
        return ans[n][k];
    }
}
```

#### Language used for code
Java

#### Expected behavior
When the code above is submitted, the TLE should be displayed for the specific test case n = 1000 and k = 1000, not for total run time.

#### Screenshots
The following screenshot is from submission where I set a wrong answer for n = 1000 and k = 1000, and the submission returned Wrong Answer, which indicates the test case n = 1000 and k = 1000 already exists.

![image](https://user-images.githubusercontent.com/12067364/142709645-94f26df9-ee12-48f8-a4ab-7401974703fa.png)

The following screenshot is from submission. The total runtime is TLE.

![image](https://user-images.githubusercontent.com/12067364/142709509-2ded694d-a086-4c8c-af88-6276e92eea06.png)

The following screenshot is when I run the test case where n = 1000 and k = 1000 in custom test case, the single test case got TLE.

![image](https://user-images.githubusercontent.com/12067364/142709493-6f9a2d26-2707-407a-a175-ea5b2fb51f28.png)

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for your time. I have received feedback from our team regarding this issue. The server used for run code is not the same server used for judging. That's why there is inconsistency. The run code is supposed to show the correctness of your code and not to compare it with the actual runtime.
