### ISSUE TITLE
Missing Test Case - 540. Single Element in a Sorted Array

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#5341]
#### Your LeetCode username

archit91

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case -
[540_test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7573849/540_test_case.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int singleNonDuplicate(vector<int>& nums) {
        for(auto c : nums) {
            int occurence = 0;
            for(auto c2 : nums)
                occurence += c == c2;
            if(occurence == 1) return c;
        }
        return -1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should be rejected since it fails and times out on the above-mentioned valid test case.

**Comment by LC-Sue** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
