### ISSUE TITLE
Leetcode 28. Implement strStr() wrong testcase according to Constraints provided

### ISSUE THREAD

**Issue by Supermathew** [LeetCode-Feedback/LeetCode-Feedback#5342]
#### Leetcode 28. Implement strStr() wrong testcase according to Constraints provided
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Leetcode 28. Implement strStr() wrong testcase according to Constraints provided.
Constraints provided in the question is that both strings haystack and needle consist of only lower-case English characters.
But there is a test case in which my solution code got stuck was that there was a empty string which is completely against the test case provided.
[Please refer to image provide ]

#### Code you used for Submit/Run operation

// Implement strStr() 
// This code is a perfect solution to the leetcode problem but my issue is only with the wrong testcase(which is against the constraints) which is taken into consideration .
        `class Solution {
    public int strStr(String haystack, String needle) {
      

       int a=0;
       
            a= ans(haystack,needle);
   

        return a;
    }
    public int ans(String s,String w){
        int h = -1;
    
      
        for(int i = 0; i<=(s.length()-w.length());i++){
          boolean  g = true;
            
           
            
            h=i;
            for(int j =0;j<w.length();j++){
               
                if(s.charAt(i+j)!=w.charAt(j)){
                    System.out.println(g);
                    g= false;
                    break;
                }
            }
        
        if(g){
            return h;
        }
        
            }
        return -1;
            }
    }`
    

#### test case does not match with the Constraints given .
Test case empty string is against the constraints which states both strings consists of only lowercase alphabet.

#### 
![IMG_20211120_112448](https://user-images.githubusercontent.com/94732224/142716182-32cdd6cc-c263-49d3-8492-b62419f446b4.jpg)
![IMG_20211120_112415](https://user-images.githubusercontent.com/94732224/142716184-197816e2-9ab2-4664-88a7-c3b7f24b8f5a.jpg)

**Comment by stormsunshine** [comment]
The test cases do meet the constraints. The constraint that both strings `haystack` and `needle` consist of only lower-case English characters means that there are not any other characters (like upper-case English characters, digits, etc.) in the two strings, not that the two strings are non-empty.

There is also another constraint that both strings have length at least 0, which means that the two strings can be empty.

Why do you think that the two strings have to be non-empty?

**Comment by Supermathew** [comment]
In constraints it's given both strings consists of only lower-case alphabet.
In string "" where is lower case alphabet ??
Its not there 
Which is against the constraints where there is mention only lower case

**Comment by Supermathew** [comment]
![Screenshot_2021-11-20-11-49-45-458_com android chrome](https://user-images.githubusercontent.com/94732224/142716777-28b2f3ea-c15c-40f0-bcb2-d425d442cc53.jpg)

See this testcase and code in image  it's accepting empty string which is against the constraints which mentioned that string consists of only lower case alphabet .
"" does not consists of lowercase alphabet why is it been accepted ??

**Comment by stormsunshine** [comment]
I need to mention again. A string that consists of lower-case English characters does not need to be non-empty. An empty string is also a string that consists of lower-case English characters. As long as a string does not contain characters other than lower-case English characters (like upper-case English characters, digits, etc.), the string meets the constraint that it consists of lower-case English characters, no matter whether its length is positive or zero.

Also, in the constraints, it is mentioned tha both strings have lengths greater than ot equal to zero. Since both strings can have length zero, both strings can be empty.

**Comment by Supermathew** [comment]
Okk thank you brother for helping me to find out my mistake.
Doubt cleared .
