### ISSUE TITLE
Wrong example given - 430. Flatten a Multilevel Doubly Linked List

### ISSUE THREAD

**Issue by shweta786** [LeetCode-Feedback/LeetCode-Feedback#5343]
one of the examples given in this question is wrong. I have attached the image. Right answer should be 1->3->2
<img width="507" alt="error" src="https://user-images.githubusercontent.com/15891710/142727500-7c3db8f0-6c88-41f5-8508-fc1e3527dddf.png">

#### Your LeetCode username
shweta786

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
The image in Explanation is indeed wrong. Node 3 should be between node 1 and node 2.
@LC-Sue Please take a look. Note that it is the image in Explanation that needs to be changed, and the correct output is [1,3,2].

**Comment by LC-Sue** [comment]
Hi @shweta786 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @shweta786 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @shweta786 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
