### ISSUE TITLE
377. Combination Sum IV

### ISSUE THREAD

**Issue by claytonjwong** [LeetCode-Feedback/LeetCode-Feedback#5344]
#### Your LeetCode username
claytonjwong

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This problem can be more accurately renamed to `377. Unique Permutation Sum IV`, since order does *not* matter for a combination, but order does matter for a permutation.  For example, the combination `{1, 2, 3}` has unique permutations `(1, 2, 3)`, `(1, 3, 2)`, `(2, 1, 3)`, `(2, 3, 1)`, `(3, 1, 2)`, `(3, 2, 1)`, ie. if there are `n! / (k! * (n - k)!)` permutations, then there are `k! = 3 * 2 * 1 = 6` more permutations than combinations: `n! / (n - k)!`.

#### Code you used for Submit/Run operation

```
# unique "paths"

#
# top-down TLE
#

# class Solution:
#     def combinationSum4(self, A: List[int], T: int) -> int:
#         def go(i = 0, t = T, path = []):
#             if not t:
#                 return len(set([perm for perm in permutations(path)]))
#             if i == len(A):
#                 return 0
#             include = go(i, t - A[i], path + [A[i]]) if 0 <= t - A[i] else 0
#             exclude = go(i + 1, t, path)
#             return include + exclude
#         return go()

#
# bottom-up AC
#

class Solution:
    def combinationSum4(self, A: List[int], T: int) -> int:
        dp = [0] * (T + 1)
        dp[0] = 1  # 1 way to start with total 0
        for t in range(1, T + 1):
            for x in A:
                if 0 <= t - x:
                    dp[t] += dp[t - x]
        return dp[T]
```

#### Language used for code
Python3

**Comment by LC-Sue** [comment]
Hi @claytonjwong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @claytonjwong,
Thank you for your time, our team has decided not change the title of the problem as this will break the existing like.
However, the statement and examples are clear and the problem should not be confusing.
