### ISSUE TITLE
Missing Test Cases - 860. Lemonade Change

### ISSUE THREAD

**Issue by hoduchieu01** [LeetCode-Feedback/LeetCode-Feedback#5345]
#### Your LeetCode username

hoduchieu01

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails in the following test case. 
[5,5,5,20]
In the code, I commented on the fail condition. Please refer the code below.

#### Code you used for Submit/Run operation

```
bool lemonadeChange(int* bills, int billsSize){
    int five = 0;
    int ten = 0;
    for(int i = 0; i < billsSize; i++){
        if(bills[i] == 5) five ++;
        else if(bills[i] == 10){
            if(five == 0) return false;
            ten ++;
            five --;
        }
        else{
            if(five > 0 && ten > 0){
                ten --;
                five --;
            }
            else if(five > 3){ // In this line, five only need to >= 3. But when this solution used five > 3 and got accepted. It will fails with test cases [5,5,5,20]
                five -= 3;
            }
            else{
                return false;
            }
        }
    }
    return true;
}
```

#### Language used for code

C

#### Expected behavior

The solution should be rejected. Because the condition statement is wrong. 

#### Screenshots

When I run a customized test case [5,5,5,20], it shows the wrong answer as I mentioned above. However, I got accepted when I submitted it. 
![image](https://user-images.githubusercontent.com/23649434/142735313-fc550967-f259-49bb-895d-03345d0a4beb.png)

**Comment by LC-Sue** [comment]
Hi @hoduchieu01 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hoduchieu01 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
