### ISSUE TITLE
Issue : 106. Construct Binary Tree from Inorder and Postorder Traversal

### ISSUE THREAD

**Issue by suniln2020** [LeetCode-Feedback/LeetCode-Feedback#5347]
#### Category of the bug

- [ ] Solution

#### If the input data are having duplicate , then the given answer will not work 

As shown below we are storing inorder val's index in a map , if node values are duplicate then the given solution wont work.

#### Code you used for Submit/Run operation

```
// storing index of inorder val  
int idx = 0;
    for (Integer val : inorder)
      idx_map.put(val, idx++);
```

**Comment by LC-Sue** [comment]
Hi @suniln2020,
Thank you for reaching out. The problem constraints state that the input data only consists of unique values, so the input cannot have duplicate values.
