### ISSUE TITLE
Missing Test Case - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by rostovchanin** [LeetCode-Feedback/LeetCode-Feedback#5348]
#### Your LeetCode username

Vasilii_Shvets

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Test cases approve incorrect implementation like always save longUrl in one property when encode and always return that - when decode.

#### Code you used for Submit/Run operation

```
// Two Sum
public class Codec {
    
    String origin;
    
    // Encodes a URL to a shortened URL.
    public String encode(String longUrl) {
        
        
        origin = longUrl;
        return "dfg";
    }

    // Decodes a shortened URL to its original URL.
    public String decode(String shortUrl) {
        return origin;
    }
    
    
}
```

#### Language used for code
Java

#### Expected behavior

 Submission fail.

#### Additional context

Obviously, this decision wrong - decode method will return always last coding url

**Comment by LC-Sue** [comment]
Hi @rostovchanin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stormsunshine** [comment]
I don't think LeetCode platform can prohibit such solutions. That is to say, if a user does submit a solution like this, it is impossible to detect that such solution is illegal and to return wrong answer.

The only thing that can be done is to add the requirement in problem description. By adding the requirement in problem description, it means that even though such a solution can get accepted on LeetCode, the solution is not accepted during an interview.

**Comment by rostovchanin** [comment]
> 

What about checking like this?:

```Codec codec = new Codec();
String encodedUrl1 = codec.encode("url1"); 
String encoded2Url2 = codec.encode("url2");
String decodedUrl1 = codec.decode(encodedUrl1); 
//expect decodedUrl1 equals url1, but it won't
```

**Comment by rostovchanin** [comment]
@stormsunshine, i sent an example of checking this problem, seems it will be an appropriate way

**Comment by LC-Sue** [comment]
Hi @rostovchanin,
Thank you for your time. We are aware of that but there is no way to stop all cheating solutions. However, it is still a requirement to design an algorithm to pass a real interview. We appreciate your support!
