### ISSUE TITLE
1312: Difficulty should be medium

### ISSUE THREAD

**Issue by vikash-gupta** [LeetCode-Feedback/LeetCode-Feedback#5349]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This is a medium dynamic programming question

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
Change hard to medium

#### Additional context
As compared to other hard questions, this is medium

**Comment by LC-Sue** [comment]
Hi @vikash-gupta,
Thank you for reaching out to us and providing your feedback. I will let our team know of this suggestion.
