### ISSUE TITLE
413. Arithmetic Slices – typos

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#535]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
There are several typos in the problem statement:
1. A sequence of **number** [...]
2. For example, these are arithmetic **sequence**: [...]
3. A slice (P, Q) of **array** A
4. A[P], A[**p** + 1], ..., A[Q - 1], A[Q

#### Expected behavior

1. numbers
2. sequences
3. an array, or the array
4. P

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
