### ISSUE TITLE
Memory Leaks on each delete call

### ISSUE THREAD

**Issue by uprazapati** [LeetCode-Feedback/LeetCode-Feedback#5350]
#### Your LeetCode username

randomu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The C++ solution given for Delete a node in BST question at the following link ```https://leetcode.com/explore/learn/card/introduction-to-data-structure-binary-search-tree/141/basic-operations-in-a-bst/1024/``` 
has a memory leak issue i.e. in the following case 
           ```if (!root->left) {
                return root->right;
            }```
          We are returning the right child from this function and which makes the root node a memory leak as we haven't deleted it.
          We just adjusted the links. Same thing is done for the following case:
            ```if (!root->right) {
                return root->left;							
            }```
         A better approach would be to store the right or left child in a temporary pointer and then delete the root node and return the child. This can be done as follows:

            if (!root->left) {
                TreeNode* temp = root->right;
                delete root;
                return temp;
            }
      
           if (!root->right) {
                TreeNode* temp = root->left;
                delete root;
                return temp;							
           }


#### Code you used for Submit/Run operation
<!-- 
Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 
-->

```
class Solution {
private:
    /**
     * findSuccesor - Helper function for finding successor
     * In BST, succesor of root is the leftmost child in root's right subtree
     */
    TreeNode* findSuccessor(TreeNode* root) {
        TreeNode* cur = root->right;
        while (cur && cur->left) {
            cur = cur->left;
        }
        return cur;
    }
public:
    TreeNode* deleteNode(TreeNode* root, int key) {
        // return null if root is null
        if (!root) {
            return root;									
        }

        // delete current node if root is the target node
        if (root->val == key) {
            // replace root with root->right if root->left is null					
            if (!root->left) {
                TreeNode* temp = root->right;
                delete root;
                return temp;
            }

            // replace root with root->left if root->right is null
            if (!root->right) {
                TreeNode* temp = root->left;
                delete root;
                return temp;							
            }

            // replace root with its successor if root has two children
            TreeNode* p = findSuccessor(root);
            root->val = p->val;
            root->right = deleteNode(root->right, p->val);
            return root;
        }

        if (root->val < key) {
            // find target in right subtree if root->val < key
            root->right = deleteNode(root->right, key);
        } else {
            // find target in left subtree if root->val > key
            root->left = deleteNode(root->left, key);
        }
        return root;
    }
};
```

#### Language used for code
<!-- C++ -->
C++


#### Expected behavior
<!-- -->
The expected behavior is to also delete the node from memory once it is deleted.


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by uprazapati** [comment]
Bug for the Solution given here for the problem Delete node in a BST
https://leetcode.com/explore/learn/card/introduction-to-data-structure-binary-search-tree/141/basic-operations-in-a-bst/1024/

**Comment by LC-Sue** [comment]
Hi @uprazapati 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
