### ISSUE TITLE
Missing Test Case - 1143. Longest Common Subsequence

### ISSUE THREAD

**Issue by thegeett** [LeetCode-Feedback/LeetCode-Feedback#5351]
#### Category of the bug
- [*] Missing Test Cases 

#### Description of the bug

Found one test case. 

"abcdfhktwbt"
"abckhefwgaht"

**Comment by stormsunshine** [comment]
What is the code that can get accepted but fails on the test case?

**Comment by LC-Sue** [comment]
Hi @thegeett,
Thank you for reaching out to us. Could you please provide the code you used for submission?

**Comment by LC-Sue** [comment]
Hi @thegeett 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
