### ISSUE TITLE
New Solution for the problem- 494. Target Sum

### ISSUE THREAD

**Issue by AbrarJahin** [LeetCode-Feedback/LeetCode-Feedback#5353]
#### Your LeetCode username
abrarjahin

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Problem URL
https://leetcode.com/problems/target-sum/

#### New Solution which is not present in the given solution list

We can use a 1D dictionary which will need less space and will reduce our search space at least to 1/2.
Python code is like this-

```
class Solution:
    def findTargetSumWays(self, nums: List[int], target: int) -> int:
        dp, zeroCount = {0:1}, sum([1 if n==0 else 0 for n in nums])
        for n in nums:
            if n==0: continue
            tDict = dp.copy()
            dp = {}
            for k in tDict:
                dp[k+n] = (dp[k+n] + tDict[k]) if k+n in dp else tDict[k]
                dp[k-n] = (dp[k-n] + tDict[k]) if k-n in dp else tDict[k]
            #print(n, dp)
        return dp[target]*2**zeroCount if target in dp else 0
```

**Comment by LC-Sue** [comment]
Hi @AbrarJahin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by AbrarJahin** [comment]
Hi @LC-Sue, thank you for escalating the issue. I have got an issue with the provided solution.

A move consists of merging exactly k **consecutive** piles into one pile. In that case, I can't move 2 piles which are not consequitive.

**Comment by AbrarJahin** [comment]
Hi @LC-Sue , thank you for escalating the issue. I think this solution would be a new approach for the problem and will help others.

**Comment by LPRowe** [comment]
Hi @AbrarJahin thank you for your sharing your insights, we will keep them in mind if/when the solution article is next updated. Also, below are a few simplifications:

```python
class Solution:
    def findTargetSumWays(self, nums: List[int], target: int) -> int:
        dp = collections.defaultdict(int)
        dp[0] = 1
        for num in nums:
            tDict = dp
            dp = collections.defaultdict(int)
            for total in tDict:
                dp[total + num] += tDict[total]
                dp[total - num] += tDict[total]

        return dp[target]
```
