### ISSUE TITLE
Missing Test Cases - 2081. Sum of k-Mirror Numbers

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5354]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [2081. Sum of k-Mirror Numbers](https://leetcode.com/problems/sum-of-k-mirror-numbers), since both `k` and `n` have small constraints, it is better to have all test cases that meet the constraints to be tested for submission. There should be 240 test cases in total. Currently, there are only 97 test cases tested for submission (I think one test case has been duplicated, which means there are only 96 distinct test cases), and the remaining test cases should be added.

The test cases that are not tested for submission currently are as follows. A txt file is also provided: [2081 test cases.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7582081/2081.test.cases.txt)

Since there are 144 test cases that are not tested, there are only 96 distinct test cases that are tested, which means there is one duplicate test case among the 97 test cases.

```
2
4
2
6
2
9
2
11
2
13
2
14
2
16
2
17
2
18
2
19
2
21
2
22
2
23
2
24
2
26
2
27
2
28
2
29
3
4
3
6
3
9
3
11
3
13
3
14
3
16
3
17
3
18
3
19
3
21
3
22
3
23
3
24
3
26
3
27
3
28
3
29
4
4
4
7
4
9
4
11
4
13
4
14
4
16
4
17
4
18
4
19
4
21
4
22
4
23
4
24
4
26
4
27
4
28
4
29
5
4
5
6
5
7
5
9
5
11
5
13
5
14
5
16
5
17
5
18
5
19
5
21
5
22
5
23
5
24
5
26
5
27
5
28
5
29
6
4
6
6
6
9
6
11
6
13
6
14
6
16
6
17
6
18
6
19
6
21
6
22
6
23
6
24
6
26
6
27
6
28
6
29
7
4
7
6
7
7
7
9
7
11
7
13
7
14
7
16
7
18
7
21
7
22
7
23
7
24
7
26
7
27
7
28
7
29
8
4
8
6
8
7
8
9
8
11
8
13
8
14
8
16
8
17
8
18
8
19
8
21
8
22
8
23
8
24
8
26
8
27
8
28
8
29
9
4
9
6
9
7
9
9
9
11
9
13
9
14
9
18
9
19
9
21
9
22
9
23
9
24
9
26
9
27
9
28
9
29
```

#### Code you used for Submit/Run operation
The following code is only one example to skip a test case. The line `if (k == 2 && n == 4)` can also be changed to other code to skip one or more other test cases.
```
class Solution {
    public static boolean flag = false;
    public static long[][] mirrorSums = new long[10][31];

    public long kMirror(int k, int n) {
        if (k == 2 && n == 4)
            return 0;
        if (!flag) {
            flag = true;
            for (int i = 2; i <= 9; i++) {
                long[] curr = getMirrors(i);
                for (int j = 1; j <= 30; j++)
                    mirrorSums[i][j] = curr[j] + mirrorSums[i][j - 1];
            }
        }
        return mirrorSums[k][n];
    }

    public static long[] getMirrors(int k) {
        long[] res = new long[31];
        int index = 1, half = 1, length = 1;
        outer:
        while (index <= 30) {
            char[] arr = new char[half];
            arr[0] = '1';
            for (int i = 1; i < half; i++)
                arr[i] = '0';
            boolean flag = true;
            while (flag) {
                String numStr = generate(arr, length % 2 == 0);
                long num = Long.parseLong(numStr, k);
                if (isPalindrome(num)) {
                    res[index] = num;
                    index++;
                    if (index > 30)
                        break outer;
                }
                flag = next(arr, k);
            }
            length++;
            if (length % 2 == 1)
                half++;
        }
        return res;
    }

    public static boolean next(char[] arr, int k) {
        int length = arr.length;
        int index = length - 1;
        arr[index]++;
        while (index > 0 && arr[index] - '0' >= k) {
            arr[index - 1]++;
            arr[index] = '0';
            index--;
        }
        return arr[0] - '0' < k;
    }

    public static String generate(char[] arr, boolean isEven) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < arr.length; i++)
            sb.append(arr[i]);
        int reverseStart = isEven ? arr.length - 1 : arr.length - 2;
        for (int i = reverseStart; i >= 0; i--)
            sb.append(arr[i]);
        return sb.toString();
    }

    public static boolean isPalindrome(long num) {
        String numStr = String.valueOf(num);
        int left = 0, right = numStr.length() - 1;
        while (left < right) {
            if (numStr.charAt(left) != numStr.charAt(right))
                return false;
            left++;
            right--;
        }
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The test cases provided above should all be added to the problem 2081. Sum of k-Mirror Numbers, and the duplicate test case should be removed so that each test case is unique.

After updating the test cases for 2081. Sum of k-Mirror Numbers, there should be 240 test cases, and the test cases should be all distinct.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by rostovchanin** [comment]
Hi @stormsunshine

Could you tell pls, what did i do wrong so that my issue was ignored (not labels etc)?

[issues/5348](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/5348)

Thanks!

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for your time. Our team has considered this issue and decided that there is no need to add all the test cases. Adding all the test cases will make the judging process for no reason. We consider the solutions that add a special if condition cheating solutions and they are ok to AC out of the contest.
