### ISSUE TITLE
Missing Test Case - 377. Combination Sum IV

### ISSUE THREAD

**Issue by ivanisakov99** [LeetCode-Feedback/LeetCode-Feedback#5355]
#### Your LeetCode username

isakovi

#### Category of the bug
- [ Y ] Question
- [ ] Solution
- [ Y ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The bottom up DP solution gives a runtime error of integer(int32_t) overflow in C++. Even though the question says, "It is guaranteed the answer fits on a 32-bit integer."

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int combinationSum4(vector<int>& nums, int target){
        vector<int32_t> dp(target + 1, 0);
        dp[0] = 1;

        for (int i = 1; i <= target; i++){
            for (int& num : nums){
                if (i - num >= 0){
                    dp[i] += dp[i - num];
                }
            }
        }
        return dp[target];
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected for it to work fine, since it did not specify whether it is a 32bit signed or unsigned integer. But there was a test case that had an integer overflow.

#### Screenshots

<img width="1438" alt="Screenshot 2021-11-22 at 14 12 31" src="https://user-images.githubusercontent.com/60196280/142921250-278aa34f-b5bc-4719-b8d4-a681cc93a04a.png">

**Comment by LC-Sue** [comment]
Hi @ivanisakov99 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ivanisakov99,
Thank you for your time. Strictly speaking, all answers do fit in a signed integer, it is an intermediate result that causes overflow for C++. This can be resolved by using uint32_t instead. The statement said the final answer will always fit in a 32-bit integer. If during the calculations the answer exceeded 32-bit integer, then this is an implementation detail that must be handled you.
