### ISSUE TITLE
A minor mistake in question: 412. Fizz Buzz

### ISSUE THREAD

**Issue by Alessul** [LeetCode-Feedback/LeetCode-Feedback#5357]
#### Your LeetCode username

SAlessa

#### Category of the bug
-  Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

a descriptive mistake in the following question: 
![Screenshot 2021-11-22 175913](https://user-images.githubusercontent.com/76516522/142961122-dd5a3284-1760-4782-ab71-8e7f86c4f442.png)

**In the following line, the letter i has to be placed between quotation marks to indicates it is added to the list as a string instead of an integer:**:
answer[i] == **i** if non of the above conditions are true. **(Wrong)** 

**After fixing the mistake, it should look like the following:**:
answer[i] == **"i"** if non of the above conditions are true. **(Correct)**

#### Language used for code

Python 3

**Comment by stormsunshine** [comment]
If the description is changed to `answer[i] == "i"`, then it may be misleading since "i" can represent a string that has a single character "i".

I suggest that the problem description can be changed to the following.
> `answer[i] == i` if non of the above conditions are true (note that `answer[i]` should be in the form of a string).

**Comment by Alessul** [comment]
Thanks stormsunshine for pointing this out. 
I think a better solution would be changing the test cases to add the numbers to the list as integer instead of strings. That would help to roll out all confusion cases. 

For example: 
Instead of: ["1", "2", "Fizz", "4", "Buzz"]   --- we would have --> [1, 2, "Fizz", 4, "Buzz"]  

where the numbers are integers instead of strings.

**Comment by LC-Sue** [comment]
Hi @Alessul 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Alessul 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
