### ISSUE TITLE
993. Cousins in Binary Tree (inconsistent code execution)

### ISSUE THREAD

**Issue by ruba-ruba** [LeetCode-Feedback/LeetCode-Feedback#536]
#### Your LeetCode username
[ruba-ruba](https://leetcode.com/ruba-ruba/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Inconsistent Code execution / testcase

#### Code you used for Submit/Run operation

```ruby
def is_cousins(root, x, y)
  find_node(root, x, 0, nil)
  return false if @res.nil?
  parent1, depth1 = @res
  @res = nil
  
  find_node(root, y, 0, nil)
  return false if @res.nil?
  parent2, depth2 = @res
  
  parent1 != parent2 && depth1 == depth2
end

def find_node(node, val, depth, parent=nil)
  if val == node.val
    @res = [parent, depth]
  end
  
  find_node(node.left, val, depth+1, node) if node.left && @res.nil?
  find_node(node.right, val, depth+1,  node) if node.right && @res.nil?
end
```

#### Language used for code
ruby

#### Expected behavior
the result when trying code and submitting code should be same

#### Screenshots

![Screenshot 2020-06-25 at 10 16 43](https://user-images.githubusercontent.com/2625613/85682892-019f7600-b6cd-11ea-997b-93e4060fa0b8.png)

![Screenshot 2020-06-25 at 10 06 13](https://user-images.githubusercontent.com/2625613/85682744-e2084d80-b6cc-11ea-9d0c-205a14139751.png)

#### Additional context
-

**Comment by lc-christina** [comment]
Hi @ruba-ruba 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
