### ISSUE TITLE
Problem of function - 1286. Iterator for Combination

### ISSUE THREAD

**Issue by LucasColas** [LeetCode-Feedback/LeetCode-Feedback#5360]
Hello, 
we have an issue (in Python) for this problem. It's a problem of a name function.

#### Your LeetCode username
MrRex_

#### Category of the bug
Language

#### Description of the bug
The code given for this problem is : 
```
class CombinationIterator:

    def __init__(self, characters: str, combinationLength: int):
        self.characters = characters
        self.combinationLength = combinationLength
        self.every_comb = []
        

    def next(self) -> str:
        pass
            
        
        

    def hasNext(self) -> bool:
```
But next() is actually a built-in function in Python.
Look at this function [here ](https://docs.python.org/3/library/functions.html#next).

#### Language used for code
Python

**Comment by LC-Sue** [comment]
Hi @LucasColas 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LucasColas** [comment]
Good.

**Comment by LC-Sue** [comment]
Hi @LucasColas,
Thank you for your time, next here is a member function of the class which is ok in python. Please also feel free to refer to the discuss section of the problem to see how other users optimized their python codes!
