### ISSUE TITLE
Missing Test Case - 416. Partition Equal Subset Sum

### ISSUE THREAD

**Issue by WillDwz** [LeetCode-Feedback/LeetCode-Feedback#5361]
#### Your LeetCode username

weizhd1

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

a problematic solution passes all the test cases.

#### Code you used for Submit/Run operation

```
class Solution:
    def canPartition(self, nums: List[int]) -> bool:
        S = sum(nums)
        n = len(nums)
        if S % 2 != 0: return False
        target = S // 2
        seen = [0] * n
        nums.sort(reverse = True)
        
        def dfs(first_ind, current_sum):
            if current_sum == 0:
                return True
            
            for i in range(first_ind, n):
                tot_sum = current_sum - nums[i]
                if seen[i] == 0 and tot_sum >= 0:
                    seen[i] = 1
                    if dfs(i+1, tot_sum):
                        return True
            return False
        
        return dfs(0, target)
```

#### Language used for code
Python

#### Expected behavior

should not be accepted
above code failed for cases like:
[5,3,2,2,2,2,2,2,2]

#### Screenshots

![image](https://user-images.githubusercontent.com/80217986/142985453-b34aa8d2-9791-4f78-945d-35bb66de56a8.png)

**Comment by LC-Sue** [comment]
Hi @WillDwz 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @WillDwz 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
