### ISSUE TITLE
Typo at - 1669. Merge In Between Linked Lists

### ISSUE THREAD

**Issue by iskandarair** [LeetCode-Feedback/LeetCode-Feedback#5362]
#### Your LeetCode username
iskandarAir

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a typo - The blue edges and nodes in the following figure !!incidate!! the result:

**Comment by LC-Sue** [comment]
Hi @iskandarair 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @iskandarair 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
