### ISSUE TITLE
Swift Runtime measurements showing huge variation in the last few days

### ISSUE THREAD

**Issue by iosdevzone** [LeetCode-Feedback/LeetCode-Feedback#5364]
#### Your LeetCode username
iosdevzone

#### Category of the bug
- [ ] Question
- [X] Solution
- [X ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Over the last few days I have noticed that runtimes reported on the site for Swift solutions has shown huge variations. This was not the case, say, a week ago. To make this more concrete consider the solution below for []():

#### Code you used for Submit/Run operation

```swift
class Solution {
    func uniqueOccurrences(_ arr: [Int]) -> Bool {
        let counts = arr.reduce(into: [Int:Int]()) { $0[$1, default: 0] += 1 }
        return Set(counts.values).count == counts.count
    }
}
```

#### Language used for code
Swift

#### Expected behavior
While it is reasonable to expect some variation from run to run, this code is either an 8 ms solution beating 93.75% or a 21 ms solution beating 12.50%.

While I have chosen this rather simple example, the behavior appears to be a general issue not just limited to small, short running solutions. This takes away a considerable amount of the fun of submitting to the site since comparisons between variations in code are rendered fairly meaningless.

I haven't submitted solutions in other languages in the last few days, so it is possible that the issue is not limited to Swift.

**Comment by iosdevzone** [comment]
It seems things are a little better now. Not sure if any fix has been put in place, but submitting some solutions today I was not seeing quite the same crazy variations as before.

**Comment by LC-Sue** [comment]
Hi @iosdevzone,
Thank you for reaching out, could you provide the problem number for the issue you are reporting?

**Comment by iosdevzone** [comment]
Hi @LC-Sue,

The solution I posted is for 1207. Unique Number of Occurrences (https://leetcode.com/problems/unique-number-of-occurrences/), however the problem of wildly varying runtimes for Swift submissions was observable for **any** problem. As of yesterday it seems to be a lot better.

Thanks for getting back to me.

**Comment by LC-Sue** [comment]
Hi @iosdevzone,
Thank you for providing the problem. The runtime appears to be fine on my end, however if you experience any issues please feel free to reopen this thread and I will escalate issues to our content team as needed!
