### ISSUE TITLE
Incorrect page in Heap explore card.

### ISSUE THREAD

**Issue by anurag-jain** [LeetCode-Feedback/LeetCode-Feedback#5366]
The page about time complexity in [Heap Explore card](https://leetcode.com/explore/learn/card/heap/) seems to be from dynamic programming. See the screenshot attached with the issue highlighted.

![image](https://user-images.githubusercontent.com/555452/143182930-d1fe0fab-66dd-46bd-97e7-b5fc3f3d60d8.png)

**Comment by LC-Sue** [comment]
Hi @anurag-jain,
Thank you for reaching out, this issue has been filed with our team!

**Comment by LC-Sue** [comment]
Hi @anurag-jain 
Thank you for your time, we have resolved this issue. We appreciate your support!
