### ISSUE TITLE
Missing Test Case - 253. Meeting Rooms II

### ISSUE THREAD

**Issue by Lohithayenugu** [LeetCode-Feedback/LeetCode-Feedback#5367]
#### Your LeetCode username
Lohithayenugu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Solution using TreeSet is accepted in LeetCode. Since the TreeSet doesn't store duplicates, a few test cases should ideally fail like the one below.
[[2,10], [4,10], [10,20], [10,30]]

#### Code you used for Submit/Run operation

```
// Meeting Rooms II
class Solution {
    public int minMeetingRooms(int[][] intervals) {
        int rooms =0;
        Arrays.sort(intervals, (a,b) -> {return a[0] - b[0];});
        TreeSet<Integer> set = new TreeSet<>();
        
        for(int[] interval: intervals)
        {
            if(!set.isEmpty())
            {
                if(set.first() <= interval[0])
                {
                    set.pollFirst();
                    set.add(interval[1]);                    
                }
                else
                {
                    set.add(interval[1]);
                    rooms++;
                }
            }
            else
            {
                set.add(interval[1]);
                rooms++;
            }
        }
        
        return rooms;
    }
}
```

#### Expected behavior

Few test cases with duplicate end meeting intervals would fail using the above code but LeetCode is accepting the solution.

#### Screenshots

![image](https://user-images.githubusercontent.com/47069512/143183130-1f55c1b8-c000-4eaa-999a-4a59eec9e70a.png)

**Comment by LC-Sue** [comment]
Hi @Lohithayenugu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Lohithayenugu 
Thank you for your time. We've used your feedback to update the problem. Could you please provide your LeetCode username, we'd like to reward you for the contribution

**Comment by Lohithayenugu** [comment]
Thank you, my leetcode username is  lohithay.

**Comment by LC-Sue** [comment]
Hi @Lohithayenugu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
