### ISSUE TITLE
A Follow-up Can Be Added - 1823. Find the Winner of the Circular Game

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5369]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The [1823. Find the Winner of the Circular Game](https://leetcode.com/problems/find-the-winner-of-the-circular-game) is the Joseph ring problem, and it can be solved in two ways.
1. Simulate the process, with time complexity O(n^2).
2. Use math approach, with time complexity O(n).

Since the constraints for the problem is low, with `1 <= k <= n <= 500`, the first way above with time complexity O(n^2) can be accepted. However, the second way above with time complexity O(n) may be required during an interview.

Therefore, I suggest adding a follow-up question. The follow-up question should be as follows.

**Follow-up:** Could you solve the problem in O(n) time complexity?

#### Expected behavior
Add a follow-up question for problem 1823.

**Follow-up:** Could you solve the problem in O(n) time complexity?

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for your time, our team has decided not to add the follow up, the problem was intentionally added with small constraints to allow the O(n^2) solution and the O(n) math solution was not required during the interview, so we did not add it.

**Comment by stormsunshine** [comment]
@LC-Sue Please open and reconsider this issue.

1. I don't think that the O(n) math solution is out of scope of interviews. Please take a look at this problem: [剑指 Offer 62. 圆圈中最后剩下的数字](https://leetcode-cn.com/problems/yuan-quan-zhong-zui-hou-sheng-xia-de-shu-zi-lcof).
The problem in the link above is only in LCCN and not in LCUS, but the content is almost the same as problem 1823, except that the numbers start from 0, and the constraints are different. In the link above, the constraints are `1 <= n <= 10^5` and `1 <= m <= 10^6`, where `m` is equivalent to `k` in problem 1823. Since the maximum value `n` is `10^5`, a solution with time complexity O(n^2) will not get passed, **so a solution with time complexity O(n) must be used**.
The problem in the link above is from a book that contains interview problems, which means that the problem is used in an interview and time complexity O(n) may be required during an interview.
2. Even if the O(n) solution is not required in some interviews (depending on different requirements), the O(n) solution is still quite common and the difficulty of the O(n) solution is not that hard. Although the O(n) solution is more difficult than the O(n^2) solution, the O(n) solution is still easier than most Hard problems in LeetCode.
Since some problems contain follow-up questions that are beyond the scope of interviews and are too difficult for interviews, like problem 378, it is quite acceptable that the O(n) solution is added as a follow-up question for problem 1823.

I understand that the problem is the second problem in a weekly contest and the problem is designed to accept O(n^2) solutions, so I am not requiring that the constraints should be changed or more test cases should be added. I am only requiring that a follow-up question should be added.

The O(n) math solution is quite a nice solution and is worth knowing, even if it is not required during an interview.
