### ISSUE TITLE
961. N-Repeated Element in Size 2N Array – formatting

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#537]
#### Your LeetCode username
metricquant

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
One symbol is incorrectly formatted: 
  and exactly one of these elements is repeated **N** times.
It should be
  and exactly one of these elements is repeated `N` times.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for your time. We've used your feedback to update the problem. This is not a trivial issue but I still gave your LeetCode account 100 LeetCoins as an exception. We appreciate your support!

**Comment by metricquant** [comment]
Hi @lc-christina 

No worries. It is a tiny improvement that does not deserve a reward, I agree.

I am happy to keep pointing out tiny presentation issues with no expectations of a rewards if there is an interest in perfecting those things. I am also happy to stop adding trivial issues to your backlog if you only expect higher priority issues to be there.
