### ISSUE TITLE
Missing Test Case - 952. Largest Component Size by Common Factor

### ISSUE THREAD

**Issue by medvied** [LeetCode-Feedback/LeetCode-Feedback#5370]
#### Your LeetCode username
medvied

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def largestComponentSize(self, nums: list[int]) -> int:
        max_nums = max(nums)
        color = list(range(max_nums + 1))
        ds = {p: set([p]) for p in itertools.takewhile(lambda x: x <= max_nums,
                                                       primes_cache)}
        nr = collections.Counter()
        for n in nums:
            pf = self.prime_factors(n)
            nr[min(pf)] += 1
            # print(f'{n=} {pf=} {nr=}')
            colors = [color[p] for p in pf]
            if min(colors) == max(colors):
                continue
            largest_set_p = max([(len(ds[p]), p) for p in pf],
                                key=lambda x: x[0])[1]
            largest_set = ds[largest_set_p]
            largest_set_color = color[largest_set_p]
            colors_to_change = [p for p in pf if color[p] != largest_set_color]
            assert colors_to_change
            for p in pf:
                if ds[p] is not largest_set:
                    largest_set.update(ds[p])
                    ds[p] = largest_set
                    color[p] = largest_set_color
        # print(f'{ds=} {nr=}')
        return sum([nr[p] for p in
                    max([(len(se), se) for se in ds.values()],
                        key=lambda x: x[0])[1]])

    def sieve(self, n: int) -> list[int]:
        first = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41]
        if n <= max(first):
            return [p for p in first if p <= n]
        primes = self.sieve(int(math.ceil(math.sqrt(n))))
        r = range(2, n+1)
        for p in reversed(primes):
            r = [p] + [n for n in r if n % p != 0]
        return r

    def prime_factors(self, n: int) -> list[int]:
        pf = []
        m = int(math.ceil(math.sqrt(n)))
        for p in itertools.takewhile(lambda x: x <= m, primes_cache):
            if n % p == 0:
                pf.append(p)
                while n % p == 0:
                    n //= p
        if not pf or n != 1:
            pf.append(n)
        return pf


primes_cache = Solution().sieve(10 ** 5)
```

#### Language used for code
Python3

#### Expected behavior

My solution https://leetcode.com/submissions/detail/591684437/ is accepted, but there is a test case `[2, 4, 8, 16, 3, 5, 15]` for which my solution provides a wrong answer.

My solution looks for a maximum number of different primes in the factorization of the largest connected component. For this test case `[2, 4, 8, 16, 3, 5, 15]` my solution finds 2 connected components: `[2, 4, 8, 16]` with the set of different primes `{2}` and `[3, 5, 15]` with the set of different primes `{3, 5}`. Then it chooses the set `{3, 5}` and calculates the number of different numbers from `nums` list which correspond to this set, which gives the answer `3`. The right solution is to calculate the number of numbers from `nums` list for each set and then choose maximum between the sets. Apparently there is no test case that would catch this bug, and my suggestion is to add one.

#### Screenshots

![image](https://user-images.githubusercontent.com/5236517/143266454-b8cca73d-2bc7-4afe-82e6-18505cc01eb3.png)

**Comment by LC-Sue** [comment]
Hi @medvied 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @medvied 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
