### ISSUE TITLE
Incorrect test case - 1326. Minimum Number of Taps to Open to Water a Garden

### ISSUE THREAD

**Issue by Kadajski** [LeetCode-Feedback/LeetCode-Feedback#5371]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The test case mentioned the following scenario:
N = 35
Ranges = [1,0,4,0,4,1,4,3,1,1,1,2,1,4,0,3,0,3,0,3,0,5,3,0,0,1,2,1,2,4,3,0,1,0,5,2]
Expected = 6

#### Code you used for Submit/Run operation

Code is not really applicable as it seems like the test case is incorrect. I am curious if maybe theres a bug or a misunderstanding with some mechanic. I do see many other accepted solutions in the discussion tab however I dont understand why this case isnt accepted with 5 and expects 6. The case can be solved using 5 "taps" as follows where the square brackets indicates what tap we sould use to water the garden:
```
1,0,4,0,[4],1,4,3,1 = 9
1,1,2,1,[4],0,3,0,3,0 = 9
3,0,[5],3,0,0,1,2 = 8
1,2,[4],3,0,1,0 = 7
[5],2 = 2

Total = 35
```

#### Language used for code

c#

#### Expected behavior

Expect it to accept 5 not 6

**Comment by Kadajski** [comment]
Nevermind, I figured out that in order to "water the garden" there needs to be overlapping watering to cover the "space" between the indexes

**Comment by fultonm** [comment]
What part of the question made you realize that? There's nothing indicating this is a requirement. I think the question should be worded more clearly.
