### ISSUE TITLE
Incorrect description - 320. Generalized Abbreviation

### ISSUE THREAD

**Issue by shankararunachalam** [LeetCode-Feedback/LeetCode-Feedback#5372]
#### Your LeetCode username

shank_ar

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the first paragraph of the description, an example 'abcde' is used. The description provides a few examples on what are considered valid abbreviations of this string. It goes on to say: **"23" ("ab" turned into "2" and "cde" turned into "3")**. Now, this is actually incorrect and misleading. I spent some time before realizing that this is actually not a valid abbreviation. Going through discussion section, a few others have noted this too. 

Instead, this section should make clear that two digits cannot come together unless they represent a valid length of characters: for example: 'internationalization' = i18n. Here 18 represents the length of characters between 'i' and 'n'. It doesn't represent two abbreviations of lengths 1 and 8.

**Comment by LC-Sue** [comment]
Hi @shankararunachalam 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @shankararunachalam 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by shankararunachalam** [comment]
Awesome! The changed text looks unambiguous and great. Thanks for addressing this quickly and for the coins :)
