### ISSUE TITLE
Dynamic programming Time and Space Complexity is mentioned in Heap Article

### ISSUE THREAD

**Issue by ravi14maan** [LeetCode-Feedback/LeetCode-Feedback#5373]
#### Category of the bug
- [ ] Question
- [ ] Solution

**Comment by LC-Sue** [comment]
Hi @ravi14maan,
Thank you for reaching out, this issue has been filed with our team!

**Comment by LC-Sue** [comment]
Hi @ravi14maan 
Thank you for your time, we have resolved this issue. We appreciate your support!
