### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by ravi-teja593** [LeetCode-Feedback/LeetCode-Feedback#5376]
#### Your LeetCode username

ravi4_

#### Category of the bug
- [x] Question    Longest Palindromic substring
- [x] Solution  
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Showing different outputs when running the code and submitting the code
For the test case "cbbd" the output it is showing while running the code is "bb". But while submitting the code it is showing "cbb" 

#### Code you used for Submit/Run operation

```
// Longest Palindromic Substring
class Solution {
    static int max = 0,ind = 0;
    public String longestPalindrome(String s) {
        if(s.length() <= 1){
            return s;
        }
        for(int i=0;i<s.length()-1;i++){
            extend(s,i,i+1);
            extend(s,i,i);
            
        }
          return s.substring(ind,ind+max);  
    }
     public static void extend(String s,int i,int j){
        while(i>=0 && j<s.length() && s.charAt(i) == s.charAt(j)){
            i--;
            j++;
        }
        if(j-i-1 > max){
            max = j-i-1;
            ind = i+1;
        }
    }
}
```

#### Language used for code
 Java

**Comment by LC-Sue** [comment]
Hi @ravi-teja593 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by ravi-teja593** [comment]
Thanks for clarifying the issue.
