### ISSUE TITLE
1000. Minimum Cost to Merge Stones - Wrong Taste Case

### ISSUE THREAD

**Issue by AbrarJahin** [LeetCode-Feedback/LeetCode-Feedback#5378]
#### Your LeetCode username

abrarjahin
URL - https://leetcode.com/abrarjahin/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases or Wrong Test Cases

#### Description of the bug

For this test case-
[3,5,1,2,6], k = 3

A solution can be-

1. Taking [1,2,3] -> cost =   6, remaining item-> [5,6 and (1+2+3)=6]=> [5,6,6]
2. Taking [5,6,6] -> cost = 17, remaining item-> [null=> [5,6,6]
----------------------
Total Cost = 6+17 = 23 which is minimum

But it is calculated like this-

    Explanation: We start with [3, 5, 1, 2, 6].
    We merge [5, 1, 2] for a cost of 8, and we are left with [3, 8, 6].
    We merge [3, 8, 6] for a cost of 17, and we are left with [17].
    The total cost was 25, and this is the minimum possible.

Where given answer is 25 which is worse than 23. SO, answer should be 23, not 25 I think.

#### Code you used for Submit/Run operation

```
import heapq

class Solution:
    def mergeStones(self, stones: List[int], k: int) -> int:
        heap, cost = [], 0
        for s in stones:
            heapq.heappush(heap, s)
        while len(heap)>1:
            if len(heap)<k: return -1
            sum = 0
            for i in range(k):
                popVal = heapq.heappop(heap)
                sum+=popVal
                print(popVal)
            cost += sum
            print("-", cost, sum)
            heapq.heappush(heap, sum)
        return cost
```

#### Expected behavior
The answer should be minimum cost, which should be 23 for this case, not 25 for the abovementioned example input.

There are other cases like this-

[3,2,4,1]
2

Answer should be 19 for this not 20.

For this simulation-

<img width="164" alt="image" src="https://user-images.githubusercontent.com/4152843/143417288-e627eaff-c653-4fe8-83bf-517152f33d8f.png">

But Leetcode si showing this-

#### Screenshots
![image](https://user-images.githubusercontent.com/4152843/139775497-c9abe9ea-07a4-4ffa-aed1-a23507baa248.png)

Can you please have a look into this problem and please let me know if everything is OK or not.

**Comment by stormsunshine** [comment]
A move consists of merging exactly `k` **consecutive** piles into one pile. How can you merge 1, 2, and 3 if they are not consecutive?

**Comment by AbrarJahin** [comment]
Ohh, thank you @stormsunshine for finding the issue.
