### ISSUE TITLE
Problem Description Incorrect - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5379]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [160. Intersection of Two Linked Lists](https://leetcode.com/problems/intersection-of-two-linked-lists), there are two points in problem description that need to be updated.

The first point is that both lists are not empty, so both `m` and `n` should be **strictly greater than zero**. In constraints, 0 <= m, n <= 3 * 10<sup>4</sup> should be 1 <= m, n <= 3 * 10<sup>4</sup>. Please refer to the following screenshots. If at least one of the lists is empty, then the test case is invalid.

The second point is that it is impossible to solve the problem with time complexity O(n), since there are two lists with number of nodes m and n respectively. The solution with space complexity O(1) is to use two pointers. Since both lists have to be visited completely in the worst case, the time complexity is O(m + n) rather than O(n). Therefore, the follow up question should be: Could you write a solution that runs in `O(m + n)` time and use only `O(1)` memory?

#### Expected behavior
1. In constraints, 0 <= m, n <= 3 * 10<sup>4</sup> should be changed to 1 <= m, n <= 3 * 10<sup>4</sup>.
2. The follow up question should be changed to: Could you write a solution that runs in `O(m + n)` time and use only `O(1)` memory?

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/143465251-076b001b-4da4-46bf-b478-d54ad6f7c6bf.png)
![image](https://user-images.githubusercontent.com/12067364/143465331-35080b1a-54eb-426c-b6fb-24a61305b016.png)

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
