### ISSUE TITLE
Missing Test Case - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by vikash-gupta** [LeetCode-Feedback/LeetCode-Feedback#5380]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For JavaScript language, the boilerplate code doesn't have a class. It just has 2 functions without a class. These 2 functions should be inside a class. That class should be instantiated by the calling code and then the 2 functions should be called. Java language boilerplate code is correct. Please refer to Java code.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @vikash-gupta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @vikash-gupta,
Thank you for your time, our team has decided not to change the driver of this problem for consistency.
