### ISSUE TITLE
Heap Cards containing Time/Space complexity for DP

### ISSUE THREAD

**Issue by iyerramya** [LeetCode-Feedback/LeetCode-Feedback#5381]
#### Your LeetCode username
ramya_iyer

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
https://leetcode.com/explore/learn/card/heap/644/common-applications-of-heap/4027/

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @iyerramya,
Thank you for reaching out, this issue has been filed with our team!

**Comment by LC-Sue** [comment]
Hi @iyerramya 
Thank you for your time, we have resolved this issue. We appreciate your support!
