### ISSUE TITLE
Invalid Test Case - 472. Concatenated Words

### ISSUE THREAD

**Issue by angieshu** [LeetCode-Feedback/LeetCode-Feedback#5384]
#### Your LeetCode username

angieshu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

As per the exercise description, a concatenated word is defined as a string that is comprised entirely of at least two shorter words in the given array.

For the given test case `["a","b","ab","abc"]` the Leetcode program returns only 1 string back - `"ab"`. However, the "abc" string contains "a" & "b" strings in it as well. Please advice. 

#### Code you used for Submit/Run operation

```
var findAllConcatenatedWordsInADict = function(words) {
    const len = words.length;
    const exp = buildExp(words, len);
    const res = [];
    
    for (let i = 0; i < len; i++) {
        const r = `^|\|${words[i]}($|\|)/?`;
        // const r = `(^|\|)${words[i]}(?=$|\|)`;
        let w_exp = exp.replace(new RegExp(r), '');
        
        
        const match = words[i].match(new RegExp(w_exp, 'g'));
        
        if (match && match.length > 1) {
            res.push(words[i]);
        }
    }
    
    return res;
};
    
const buildExp = (words, len) => {
    let exp = '';
    
    for (let i = 0;  i < len; i++) {
        exp += `${i === 0 ? '' : '|'}${words[i]}`;
    }
    
    return exp;
}
```

#### Language used for code

JavaScript

#### Expected behavior

Both "ab" and "abc" strings must be returned, unless otherwise advised.

#### Screenshots

![image](https://user-images.githubusercontent.com/25576444/143550442-311e68f0-24c7-4544-b7be-82e5b04ddb12.png)

**Comment by stormsunshine** [comment]
Why should `'abc"` be returned? None of the other words contain the letter `'c'`, so it is impossible to concatenate the word `"abc"` from any other words. Therefore, `"abc"` cannot be comprised by any of the other words.

**Comment by LC-Sue** [comment]
Hi @angieshu,
Thank you for reaching out to us. The test case is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their JavaScript code.
