### ISSUE TITLE
230. Kth Smallest Element in a BST [Solution Text Improvement]

### ISSUE THREAD

**Issue by mdtareque** [LeetCode-Feedback/LeetCode-Feedback#5386]
#### Your LeetCode username
mtk20

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
N/A

#### Code you used for Submit/Run operation
N/A

#### Screenshots

> ![Solution Text](https://user-images.githubusercontent.com/794071/143610614-d89750ae-ff16-4635-8817-02122edb15dc.png)

#### Additional context

The text content shown in screenshot, makes the solution post disconnected. It should be modified/updated to not mention 'last week'. Specifically, this line of text should be modified

> Insert and delete in a BST were discussed last week,....

Q. What last week is this referring to? Was it some program course, weekly contest?

**Comment by LC-Sue** [comment]
Hi @mdtareque 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @mdtareque 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by mdtareque** [comment]
@LC-Sue When can I expect the coins?

**Comment by LC-Sue** [comment]
Hi @mdtareque,
Thank you for reaching out, unfortunately I don't get to decide whether or not a reported issue is rewarded. Apologies for any miscommunication!
