### ISSUE TITLE
Test case not inline with the description

### ISSUE THREAD

**Issue by tharun49** [LeetCode-Feedback/LeetCode-Feedback#5387]
#### Your LeetCode username
dtharun

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In the sample test case it is mentioned that the list can be in any order only the content of the list that really matters.
But When I submitted my solution it failed with the list being the same as the mentioned solution but in some other order.
So please look into this Issue.

#### Code you used for Submit/Run operation

```
import math
class Solution:
    def kClosest(self, points: List[List[int]], k: int) -> List[List[int]]:
        d =  {}
        lst = []
        for point in points:
            ds = math.sqrt(point[0]*point[0]+point[1]*point[1])
            d[ds] = point
            lst.append(ds)
        ans= []
        for x in sorted(lst)[:k]:
            ans.append(d[x])
        return ans
```
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

python3

#### Expected behavior

That test case should have passed based on the sample test case behaviour.

#### Screenshots

![image](https://user-images.githubusercontent.com/88381274/143651332-7d23ecae-9017-45c8-8320-706fa839d5a8.png)
Look at sample test case 2 which says that order is immaterial. Now look at this case of the test which failed but contradicting to the description of the sample test case 2.
![image](https://user-images.githubusercontent.com/88381274/143652883-ac33818e-d733-4fa0-b928-b44fcce84bd2.png)

#### Additional context

Please fix the issue ASAP and don't forget my leetcode coins for this contribution cheers!!!!!!!

**Comment by stormsunshine** [comment]
In your output, the two points are the same, which are both `[1, 0]`, so your output is wrong. There is nothing to do with the order of output.

**Comment by tharun49** [comment]
Yeah Thanks @stormsunshine  Didn't notice that part!! Closing the issue
