### ISSUE TITLE
Missing Test Case - 203. Remove Linked List Elements

### ISSUE THREAD

**Issue by shambhaviiii07** [LeetCode-Feedback/LeetCode-Feedback#5388]
def removeElements(self, head: Optional[ListNode], val: int) -> Optional[ListNode]:
        prev = None
        curr = head
        
        while curr:
            if curr.val == val:
                if prev:
                    prev.next= curr.next
                else:
                    head = curr.next
                curr = curr.next 
            else:
                prev = curr
                curr = curr.next 
        
        return head
by shambhavi_gupta
[LeetCode UserName:shambhavi_gupta]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case?

**Comment by shambhaviiii07** [comment]
no missing test case,the code is covering all edge cases and running for all test cases!

**Comment by stormsunshine** [comment]
> no missing test case,the code is covering all edge cases and running for all test cases!

So what is the issue you want to report?

**Comment by LC-Sue** [comment]
Hi @shambhaviiii07,
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
