### ISSUE TITLE
DP section in Heap chapter 

### ISSUE THREAD

**Issue by akaskj** [LeetCode-Feedback/LeetCode-Feedback#5389]
This section in heap has an explanation of DP time complexity, not sure if this is right 

https://leetcode.com/explore/learn/card/heap/644/common-applications-of-heap/4027/

**Comment by viviettepu** [comment]
Noticed the same issue. Thanks for reporting it.

**Comment by ciasma** [comment]
Same!  It wasn't like this last week.

**Comment by LC-Sue** [comment]
Hi @akaskj,
Thank you for reaching out, this issue has been filed with our team!

**Comment by LC-Sue** [comment]
Hi @akaskj 
Thank you for your time, we have resolved this issue. We appreciate your support!
