### ISSUE TITLE
Missing Solution: 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by zen-coder** [LeetCode-Feedback/LeetCode-Feedback#539]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description

There is one very short solution in this problem meeting all requirement and yet not as a solution: Binary search/Median.
Yet two solutions not meeting requirements are presented.

[this link](https://leetcode.com/problems/find-the-duplicate-number/discuss/705111/summary-7-solutions-with-complexity-analysis-and-explanation) also describes it, among others.

Note that all the bit manipulation algorithms technically run in O(N) space.

#### Language: C++ 
```
class Solution {
public:
    int findDuplicate(vector<int>& nums)
    {
        int left = 1;
        int right = nums.size()-1;
        int median = (left + right) / 2; // lower median
        
        while(left<right)
        {
            //cout << "left: " << left << ", " << "median: " << median << ", " << "right: " << right << endl;
            int counter = 0;
            for(auto n: nums)
            {
                if(n>=left && n<=median) ++counter;               
            }
            
            if(counter > median - left + 1) right = median;
            else left = median+1;
            median = (left + right) / 2;            
        }
        return median;
    }
};
```

**Comment by lc-christina** [comment]
Hi @zen-coder 
Thank you for reaching out to us. I've relayed the issue to our team to investigate. Would you please help clarify if you want to contribute the code you shared?

**Comment by zen-coder** [comment]
You can of course re-use any of my submission on leetcode.
I hereby grant you this right :)

**Comment by lc-pam** [comment]
Hi @zen-coder 
Thank you for your time. The team has reviewed your report but decided not to update the solution. We appreciate your support!
