### ISSUE TITLE
Missing High Frequent Interview Problem

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#5390]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Multiple users have complained the lack of a Cord Tree problem on LeetCode. This is currently a very popular interview problem. Users have also complained they contributed this problem many times in the past but kept getting ignored. See this LeetCode discussion post and comments: [https://leetcode.com/discuss/interview-question/1593355/google-phone-interview-rejected/1162221](https://leetcode.com/discuss/interview-question/1593355/google-phone-interview-rejected/1162221)

**Comment by LC-Sue** [comment]
Hi @ThomasShaw1,
Thank you for reaching out, I've shared this feedback to the team for future improvements!
