### ISSUE TITLE
2090. K Radius Subarray Averages: a mistake in the description.

### ISSUE THREAD

**Issue by evgeni-nabokov** [LeetCode-Feedback/LeetCode-Feedback#5393]
#### Your LeetCode username
evgeni-nabokov

#### Category of the bug
- [*] Question

#### Description of the bug
Quote
`For example, the average of four elements 2, 3, 1, and 5 is (2 + 3 + 1 + 5) / 4 = 11 / 4 = 3.75, which truncates to 3.`

11 / 4 is 2.75, not 3.75.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
N/A

#### Screenshots
N/A

#### Additional context
N/A

**Comment by LC-Sue** [comment]
Hi @evgeni-nabokov,
Thank you for reporting the mistake, it has already been corrected! Thank you for your feedback!

**Comment by evgeni-nabokov** [comment]
@LC-Sue I expect a reward for a correct feedback. At the moment of creating the issue (Saturday) the mistake was still not fixed. And was not fixed this week - I checked the description and this thread.

**Comment by LC-Sue** [comment]
Hi @evgeni-nabokov,
Thank you for reaching out. Unfortunately, I don't decide if a user is reward for a contribution. Our team makes the decision based on the issue reported. I apologize for any inconvenience.
