### ISSUE TITLE
Wrong test case answer for 14. Longest Common Prefix

### ISSUE THREAD

**Issue by chooxuanwing** [LeetCode-Feedback/LeetCode-Feedback#5397]
#### Your LeetCode username

chooxuanwing

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test case 108/123 during submission is wrong. 
The input ["reflower","flow","flight"] has a longest common prefix of "fl" and not "" as expected in the website.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        shortest = min(strs, key=len)
        # print(shortest)
        max1=""
        for x in range(len(shortest)+1):
            shortest1=shortest[x::]   
            shortest2=shortest1
            for y in range(len(shortest1)):
                # print(shortest2)
                check=1
                for word1 in strs:
                    if word1.find(shortest2) != -1 and check==1:
                        check=1
                    else:
                        check=0
                        
                if check==1:
                    print(shortest2)
                    if(len(shortest2)>len(max1)):
                        max1=(shortest2)
                
                
                shortest2=shortest2[:-1]
        return max1
                
```

#### Language used for code

Python3

#### Expected behavior

"fl" is supposed to be the correct answer instead of ""

#### Screenshots

![Screenshot 2021-11-26 at 19-1 48 18](https://user-images.githubusercontent.com/57813158/143766336-bf1d2ac6-1b77-4a56-945f-6ee9e20a45d1.png)

**Comment by iosdevzone** [comment]
I think you might be mixing up “prefix” which must occur at the start of the string and “substring” which can start anywhere in the string: “fl” is not a prefix of “reflower”. The prefixes of “reflower” are: “r’, “re”, “ref”,…,”reflowe”.

**Comment by LC-Sue** [comment]
Hi @iosdevzone,
Thank you for reaching out, the case case appears to be correct. Please feel free to refer to the discuss section of the problem to see how others have optimized their python3 codes!

**Comment by iosdevzone** [comment]
@LC-Sue yes, I know the test case is correct... My comment was to the original poster who seemed to be mixing up "prefix" and "substring".

**Comment by LC-Sue** [comment]
@iosdevzone
I apologize for the confusion, I meant to @ the OP!
