### ISSUE TITLE
Invalid Test Case - 304, Recursion-I, Pow(x, n), PHP

### ISSUE THREAD

**Issue by dypy** [LeetCode-Feedback/LeetCode-Feedback#5399]
#### Your LeetCode username

dypy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Existing Test Cases

#### Description of the bug

Incorrect test input data.
Expected float number is: 0.999999999
Obtained value is: 1.0

#### Code you used for Submit/Run operation

```
class Solution
{
    /**
     * @param Float $x
     * @param Integer $n
     * @return Float
     */
    public function myPow($x, $n) {
        if($n < 0){
            $n = $n * -1;
            $x = 1 / $x;
        }
        return $this->process($x, $n);
    }

    private function process($x, $n) {
        if ($n === 0 || $x === 1)
            return 1;
        if ($x === 0)
            return 0;
        if($n === 1)
            return $x;
        if ($n % 2 === 1){
            return $this->process($x, $n - 1) * $x;
        }else{
            $tmp = $this->process($x, $n / 2);
            return $tmp = $tmp * $tmp;
        }
    }
}
```

#### Language used for code

PHP

#### Expected behavior

As an 'x' argument obtained by myPow(x, n) method has been value 1.0 instead of 0.999999999. The method was returning 1.0 as expected according task requirements.

#### Screenshots

![304-test-case](https://user-images.githubusercontent.com/8782183/143869250-ef80c05c-1458-41d7-b539-1be1dc0cdf87.png)

**Comment by LC-Sue** [comment]
Hi @dypy,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how others optimized their codes.

**Comment by LPRowe** [comment]
Hi @dypy while the test case is correct, we do see that `$x` seems to be rounding to 1 within the input for PHP.  We will take a closer look into your inquiry 👍

**Comment by LC-Sue** [comment]
Hi @dypy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
