### ISSUE TITLE
1485. 按日期分组销售产品 翻译不准确

### ISSUE THREAD

**Issue by bytebeats** [LeetCode-Feedback/LeetCode-Feedback#540]
对于翻译

`对于2020-05-30，出售的物品是（耳机、篮球、T恤），按词典序排列，并用逗号分隔。
对于2020-06-01，出售的物品是（铅笔、圣经），按词典序排列，并用逗号分隔。
对于2020-06-02，出售的物品是（面具），只需返回该物品名。
`
私以为翻译不妥.
题目中任意表单中都不存在诸如 "耳机、篮球、T恤"等字段, 而只是有"Basketball,Headphone,T-shirt"字段, 小括号内内容不应该进行翻译.

谢谢!

**Comment by PsiACE** [comment]
感谢您的反馈。根据您的建议，我们对翻译进行了更新，保留了小括号中的内容。请您刷新页面后查看。
