### ISSUE TITLE
Missing Test Case - 2090. K Radius Subarray Averages

### ISSUE THREAD

**Issue by Rounak-chauhan** [LeetCode-Feedback/LeetCode-Feedback#5400]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Rounak-chauhan,
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
