### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by VARDHIREDDYJAHNAVI** [LeetCode-Feedback/LeetCode-Feedback#5401]
#### Category of the bug
- [✓] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @VARDHIREDDYJAHNAVI ,
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
