### ISSUE TITLE
Missing Test Case - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by sonu28sharma99** [LeetCode-Feedback/LeetCode-Feedback#5402]

**Comment by sonu28sharma99** [comment]
This is the problem link:-
https://leetcode.com/explore/interview/card/top-interview-questions-easy/93/linked-list/603/

![image](https://user-images.githubusercontent.com/84656525/143979687-6289e529-be73-4448-88d4-1c0dc3383693.png)

**Comment by LC-Sue** [comment]
Hi @sonu28sharma99 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
