### ISSUE TITLE
Missing Test Case - 784. Letter Case Permutation

### ISSUE THREAD

**Issue by al-yakubovich** [LeetCode-Feedback/LeetCode-Feedback#5403]
#### Your LeetCode username
OnlyFaangs

#### Category of the bug
Question

#### Description of the bug
Name is not correct. It should be Letter Case Combinations, and not "Permutation"

#### Additional context
With Permutations, you focus on lists of elements where their order matters. For example, I was born in 1977. That's number 1 followed by number 9, followed by number 7, followed by number 7. In that particular order. If I change the order to 7917 instead, that would be a completely different year. Thus, the order matters.
With Combinations on the other hand, the focus is on groups of elements where the order does not matter. Like my cup of coffee is a combination of coffee, sugar and water. It doesn't matter which order I add these ingredients are in. There may as well be water, sugar and coffee, it's still the same cup of coffee. Thus, the order does not matter.
In our case order does not matter so it is combinations.

**Comment by LC-Sue** [comment]
Hi @al-yakubovich 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @al-yakubovich 
Thank you for your time. Our team has decided not the change the title for this problem. We appreciate your feedback!
