### ISSUE TITLE
Leetcode Problem 84 Solution 3 Wrong Number

### ISSUE THREAD

**Issue by Doneowth** [LeetCode-Feedback/LeetCode-Feedback#5404]
#### Your LeetCode username
doneowth

#### Category of the bug
Solution

#### Description of the bug

For Problem 84,  [Solution 3: D&C solution](https://leetcode.com/problems/largest-rectangle-in-histogram/solution/), the first line indicates "_The area of the widest rectangle using this bar as height is 2x8=16._", 

The **2 * 8 = 16** should be updated to **2 * 7 = 14** according to the solution figure.

#### Expected behavior

Update **2 x 8 = 16** into **2 x 7 = 14** to fit the solution figure.

#### Screenshots

![image](https://user-images.githubusercontent.com/87295098/144010968-763ba23e-f8a5-4992-ab96-5bb8329cebd5.png)

**Comment by LC-Sue** [comment]
Hi @Doneowth 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Doneowth 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by Doneowth** [comment]
Hi Sue,

You are the best

Dong

**Comment by Doneowth** [comment]
Hi Sue,

Almost forget, I will get 200 coins for reporting an issue right?

I just started leetcode, I am not sure where can I redeem the coins

Thanks,
DL
