### ISSUE TITLE
Missing Test Case - 116. Populating Next Right Pointers in Each Node

### ISSUE THREAD

**Issue by thomasthiebaud** [LeetCode-Feedback/LeetCode-Feedback#5405]
#### Your LeetCode username
thomasthiebaud

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In python 3, the types of the `connect` function are incorrect

```
class Solution:
    def connect(self, root: 'Node') -> 'Node':
```

It should be

```
class Solution:
    def connect(self, root: Optional['Node']) -> Optional['Node']:
```

because the number of nodes can be 0.

<img width="550" alt="Screenshot 2021-11-30 at 09 58 24" src="https://user-images.githubusercontent.com/3715715/144016389-f9dfaacd-2d5d-41df-a75f-77af3b3efc52.png">

#### Language used for code
python 3

**Comment by LC-Sue** [comment]
Hi @thomasthiebaud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @thomasthiebaud 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
