### ISSUE TITLE
1490. Clone N-ary Tree 翻译不完整

### ISSUE THREAD

**Issue by bytebeats** [LeetCode-Feedback/LeetCode-Feedback#541]
打开该题目页面, 题目依然是英文,  "1490. Clone N-ary Tree", 显然没有进行翻译.

该题目应该是 "1490. 克隆 N 叉树".

谢谢!

**Comment by PsiACE** [comment]
感谢您的反馈，该题目的中文翻译已经上线，请选择「题目以中文显示进行查看」。如果仍然无法正常显示，请清空浏览器页面缓存后再试。
