### ISSUE TITLE
Symmetric tree - incorrect output for specific test case

### ISSUE THREAD

**Issue by soupergrouper** [LeetCode-Feedback/LeetCode-Feedback#5413]
#### Your LeetCode username
soupergrouper

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In this exercise https://leetcode.com/explore/learn/card/data-structure-tree/17/solve-problems-recursively/536/ when the test case is [1,2,2,null,3,null,3] and the code represented below the output is true, but it definitely should be false. Using the embedded debugger the output is false, which is correct. 

#### Code you used for Submit/Run operation

```
func isSymmetric(root *TreeNode) bool {
    nodes := []*TreeNode{root.Left, root.Right}
	curStart, curEnd := 0, len(nodes)
	var isEnd bool
	for !isEnd {
		isEnd = true
		for i := curStart; i < curEnd/2; i++ {
			if !isEqualNodes(nodes[i], nodes[curEnd-i-1]) {
				return false
			}
			if nodes[i] != nil {
				nodes = append(nodes, nodes[i].Left)
				nodes = append(nodes, nodes[i].Right)
				isEnd = false
			}
			if nodes[curEnd-i-1] != nil {
				nodes = append(nodes, nodes[curEnd-i-1].Left)
				nodes = append(nodes, nodes[curEnd-i-1].Right)
				isEnd = false
			}
		}
		curStart = curEnd
		curEnd = len(nodes)
	}

	return true
}

func isEqualNodes(first, second *TreeNode) bool {
	if first == nil && second == nil ||
		(first != nil && second != nil && first.Val == second.Val) {
		return true
	}

	return false
}

```

#### Language used for code
Go

#### Expected behavior
The output is false for this test case as expected

**Comment by LC-Sue** [comment]
Hi @soupergrouper 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
