### ISSUE TITLE
It also accepting the code of non in-place algorithms

### ISSUE THREAD

**Issue by siddharthreddyarutla** [LeetCode-Feedback/LeetCode-Feedback#5415]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    
void rotate(vector<vector<int>>& matrix) 
    {
        int n=matrix.size();
        for(int i=0;i<n;i++)
        {
            for(int j=i+1;j<n;j++)
            {
                swap(matrix[i][j],matrix[j][i]);
            }
        }
        for(int i=0;i<n;i++)
        {
            int low=0;
            int high=n-1;
            while(low<high)
            {
                swap(matrix[i][low],matrix[i][high]);
                low++;
                high--;
            }
        }
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

It mentioned clearly that no auxiliary space is allowed and we need to modify the given input array but it accepting the solution where O(n^2) is the space requires.

#### Screenshots

![image](https://user-images.githubusercontent.com/70971734/144219754-82bb433c-201d-41a5-9c39-894cad3fd85f.png)

#### Additional context

You have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

**Comment by siddharthreddyarutla** [comment]
You have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

**Comment by stormsunshine** [comment]
For the time being, LeetCode platform cannot detect whether the space complexity of a solution meets the requirement, so a solution that does not meet the space complexity requirement can still get accepted.

Although the platform cannot restrict the space complexity, the requirement of space complexity can be present in problem description to indicate that if the question is used in an interview, such space complexity may be required.

**Comment by LC-Sue** [comment]
Hi @siddharthreddyarutla 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @siddharthreddyarutla 
Thank you for your time. We cannot force solutions not to use auxiliary space on the platform and the statement lets the users know that in an interview, you should not use additional memory.
