### ISSUE TITLE
Inconsistent result - 110. Balanced Binary Tree

### ISSUE THREAD

**Issue by aydinugur** [LeetCode-Feedback/LeetCode-Feedback#5418]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One of the test cases results false instead of true in the submission.

#### Code you used for Submit/Run operation

```
class Solution {

    static boolean answer = true;

    public boolean isBalanced(TreeNode root) {
        height(root);
        
        return answer;
    }
    
    private static int height(TreeNode root) {
        if (root == null) {
            return 0;
        }
        
        int left = height(root.left);
        int right = height(root.right);
        
        int diff = Math.abs(right - left);

        answer = diff <= 1;
        
        return Math.max(left, right) + 1;
    }
}

```

#### Language used for code

Java

#### Expected behavior

Null input test case must be true which is as expected in the Run Example Testcases.

#### Screenshots

![Screenshot](https://i2.paste.pics/8f7b6b9c76c9f069d536606cddc6aa9b.png)

**Comment by LC-Sue** [comment]
Hi @aydinugur 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by aydinugur** [comment]
Got it. Thanks a lot.
