### ISSUE TITLE
Broken Test Case - 283. Move Zeroes

### ISSUE THREAD

**Issue by Goldziher** [LeetCode-Feedback/LeetCode-Feedback#5419]
#### Your LeetCode username

Goldziher

#### Category of the bug
- [ ] Question
- [ X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The bug is that instead of evaluating the return of my code, the input is evaluated.   

#### Code you used for Submit/Run operation

```golang
func moveZeroes(nums []int) []int {
    output := make([]int, 0)
    count := 0
    for _, v := range(nums) {
        if v == 0 {
            count++
        } else {
            output = append(output, v)
        }
    }
    for count > 0 {
        count--
        output = append(output, 0)
    }
    return output
}
```

#### Language used for code

GoLang

#### Expected behavior

The code should pass the tests - at least the example tests. 

#### Screenshots

<img width="523" alt="Screenshot 2021-12-01 at 19 57 42" src="https://user-images.githubusercontent.com/30733348/144296554-c479deef-771f-4a79-bac1-8bcb0971b788.png">

As you can see in the above screenshot - when I print to console my result, it is equal to the expected, yet what is evaluated is the input.

**Comment by stormsunshine** [comment]
Why are you returning an array? For problem 283, the function should NOT have a return value. You should modify the elements of the input in-place.

**Comment by Goldziher** [comment]
> Why are you returning an array? For problem 283, the function should NOT have a return value. You should modify the elements of the input in-place.

Ha!

**Comment by LC-Sue** [comment]
Hi @Goldziher,
Thank you for reaching out, the test cases appear to be fine. Feel free to refer to the discuss section of the problem to see how others have optimized their codes!

**Comment by Goldziher** [comment]
yes, all is good. Thanks - i already solved the problem.
