### ISSUE TITLE
Missing testcase for Problem 34

### ISSUE THREAD

**Issue by JalanshMunshi** [LeetCode-Feedback/LeetCode-Feedback#542]
#### Your LeetCode username

Juggernaut12

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I submitted my code as an initial solution, but the worst-case time complexity for my submission is O(n). However, O(log n) is the required time complexity.

#### Code you used for Submit/Run operation

```
// Find First and Last Position of Element in Sorted Array
class Solution {
public:
    vector<int> searchRange(vector<int>& nums, int target) {
        
        int start = 0, end = nums.size() - 1;
        vector<int> ans(2, -1);
        if(nums.size() == 0)
            return ans;
        if(nums.size() == 1)
        {
            ans[0] = target == nums[0] ? 0 : -1;
            ans[1] = target == nums[0] ? 0 : -1;
            return ans;
        }
        while(start <= end)
        {
            int mid = (start + end) / 2;
            if(nums[mid] == target)
            {
                int first = mid, last = mid;
                while(first>0 && nums[first - 1] == nums[mid])
                    first--;
                while(last<nums.size()-1 && nums[last + 1] == nums[mid])
                    last++;
                ans[0] = first;
                ans[1] = last;
                return ans;
            }
            else if(nums[mid] > target)
                end = mid -  1;
            else
                start = mid + 1;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This submission should not be accepted. Consider the test case - 

Input: nums = a million 8's [8,8,8,8,8,8,8,...,8,8], target = 8
Output: [0, n-1]

**Comment by lc-christina** [comment]
Hi @JalanshMunshi 
Thank you for reaching out to us. The test case you suggested doesn't meet the problem's constraint:
```0 <= nums.length <= 10^5```
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
