### ISSUE TITLE
Missing Test Case - 306. Additive Number

### ISSUE THREAD

**Issue by FanchenBao** [LeetCode-Feedback/LeetCode-Feedback#5420]
#### Your LeetCode username

FanchenBao

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The online judge passes a wrong solution, indicating that the online judge's test cases are not strong enough.

#### Code you used for Submit/Run operation

Link to the solution: https://leetcode.com/submissions/detail/595547406/

```
class Solution:
    def isAdditiveNumber(self, num: str) -> bool:
        """Incorrect, but passes OJ 
        """
        N = len(num)

        @lru_cache(maxsize=None)
        def dfs(pre: int, idx: int) -> bool:
            for j in range(idx, N):
                if j > idx and num[idx] == '0':
                    return False
                cur = int(num[idx:j + 1])
                pot_str = str(pre + cur)
                rem_str = num[j + 1:]
                if len(pot_str) > len(rem_str):
                    break
                if pot_str == rem_str:
                    return True
                if pot_str in rem_str:  # the line with error, should be `rem_str.startswith(pot_str)`
                    if dfs(cur, j + 1):
                        return True
            return False

        for i in range(N):
            if i > 0 and num[0] == '0':
                break
            if dfs(int(num[:i + 1]), i + 1):
                return True
        return False
```

#### Language used for code

Python3

#### Expected behavior

I expect the solution to fail the online judge, because it fails the test case "10101". But actually, the wrong solution passes the online judge.

#### Additional context

I suggest that the online judge include "10101" in the test case.

**Comment by LC-Sue** [comment]
Hi @FanchenBao 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @FanchenBao 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
