### ISSUE TITLE
Missing Test Case - 975. Odd Even Jump

### ISSUE THREAD

**Issue by jmoral1943** [LeetCode-Feedback/LeetCode-Feedback#5421]
#### Your LeetCode username
jmoral1943

#### Category of the bug
- [ ] Incorrect Test Cases 

#### Description of the bug
This test case for Odd Even Jump 
```
[81,54,96,60,58]
```
because the rules state that 
- odd number of jumps a valid j is any value that is greater than or equal to arr[i], with the caveat that if there's multiple that satsify this condition that the lowest value of those number is j
- even number of jumps a valid j is any value that is less than or eqal to arr[i], with the caveat that if there's multiple that satsify this condition that the lowest value of those number is j

so lets start off with arr[0] which is `81` odd jump so any number greater than or equal to `81`
the only number thats greater than or equal to `81` is `96`  

now its an even number of jumps arr[2] `96` even number so any number less than or equal to `96`
there is arr[3] = 60 & arr[4] = 58 and since there's two choices the lowest value gets picked which is `58` and thats the end so theres one starting position

now lets start at arr[1] `54` odd number so any number greater than or equal to `54`
 theres mulitple 96, 60,58 but which one is the lowest value 58. Now since thats the end of the arr thats another starting position. There's two now
 
Lets skip the rest because there not going to get to the end except the last value in the array so now there's three value. I would like to know how can there be only two valid starting position with three valid starting position 

![image](https://assets.leetcode.com/users/images/218cbb3c-8f8f-4318-87fb-f9b4ff7f3887_1638386927.1396952.png)

#### Code you used for Submit/Run operation

```

var oddEvenJumps = function(arr) {
    let jumpMap = new Map()
    let startingIndx = 0
    
    function jump(i, position) {
        if(i === arr.length - 1) {
            jumpMap.set(i, {"even": true, "odd": true})
            return true
        }
        if(jumpMap.has(i) &&  (position === "odd" ? jumpMap.get(i).odd : jumpMap.get(i).even)) return true
        
        if(!jumpMap.has(i)) jumpMap.set(i, {"even": false, "odd": false })
        
        let minVal
        let nextIndx 
        for(let x = i + 1; x < arr.length; x++) {
            if(position === "odd" && arr[x] >= arr[i] && (minVal === undefined || arr[x] < minVal)) {
                minVal = arr[x]
                nextIndx = x
            } else if(position === "even" && arr[x] <= arr[i] && (minVal === undefined || arr[x] < minVal)) {
                minVal = arr[x]
                nextIndx = x
            }
        }
        
        
        if(minVal === undefined) {
            position === "odd" ? jumpMap.get(i).odd = false : jumpMap.get(i).even = false
            return false
        }
        
        let jumped = jump(nextIndx, position === "even" ? "odd" : "even")
        position === "odd" ? jumpMap.get(i).odd = jumped : jumpMap.get(i).even = jumped
        return jumped
    }
    
    for(let i = 0 ; i < arr.length; i++) {
        let jumped = jump(i, "odd")
        if((jumpMap.has(i) && jumpMap.get(i).odd) || jumped) {
            startingIndx++
        }
    }
    
    return startingIndx 
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/42519230/144301298-0f3f9e75-ae83-43cb-bc88-f9228e186f2d.png)

**Comment by stormsunshine** [comment]
There are indeed 2 good starting indices, which are 1 and 4.

If the starting index is 0, then the jumps will be 81 (index 0) -> 96 (index 2) -> 60 (index 3) and no more jumps can be made, so the end of the array can't be reached. Therefore, index 0 is not a good starting index.

Note that for the second jump, you have to jump to the largest possible value `arr[j]`, not the smallest possible value `arr[j]`

**Comment by LC-Sue** [comment]
Hi @jmoral1943,
Thank you for reaching out, stormsunshine is correct for the issue! Please feel free to reach out if you have any other questions!
