### ISSUE TITLE
Missing Test Case - 862. Shortest Subarray with Sum at Least K

### ISSUE THREAD

**Issue by Sam-Si** [LeetCode-Feedback/LeetCode-Feedback#5422]
#### Your LeetCode username

sam_si

#### Category of the bug
- [ ] Missing Test Cases 
- [ ] Weak Test Cases

#### Description of the bug

The test cases currently doesn't cover all the scenarios for the problem. There are few solutions which are wrong but will get accepted for the problem due to weak test cases. The code below is wrong but this gets accepted.

#### Code you used for Submit/Run operation

https://leetcode.com/submissions/detail/595600707/
```
    def shortestSubarray(self, nums: List[int], target: int) -> int:
        def check(size):
            queue = collections.deque()
            
            total = 0
            
            for num in nums:
                queue.append(num)
                total += num
                if len(queue) == size:
                    if total >= target:
                        return True
                    total -= queue.popleft()
                    
            return False
        
        left = 1
        right = len(nums)
        
        while left < right:
            mid = (left + right)//2
                        
            if check(mid):
                right = mid
            else:
                left = mid + 1
                
        # Hacky Part
        for mid in range(1,min(100000//len(nums),left)):
            if check(mid):
                return mid
                
        return left if check(left) else -1
```

#### Language used for code

Python

#### Expected behavior

The test cases should flag the above code as wrong ans.
I have added the test cases that will fix this problem.

#### Additional context

[862 Shortest Subarray with Sum at Least K difficult test cases.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7637250/862.Shortest.Subarray.with.Sum.at.Least.K.difficult.test.cases.txt)
I have attached the file with 3 of the test cases that should fix this problem.

**Comment by LC-Sue** [comment]
Hi @Sam-Si 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Sam-Si 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
