### ISSUE TITLE
Time and Space Complexity of Heap is for DP

### ISSUE THREAD

**Issue by rrrdev** [LeetCode-Feedback/LeetCode-Feedback#5423]
#### Your LeetCode username

JakkiSri84

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Time and Space Complexity of Heap explore card is for DP

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @rrrdev 
Thank you for reaching out, this issue has been filed with our team!

**Comment by LC-Sue** [comment]
Hi @rrrdev,
Thank you for your time, we have resolved this issue. We appreciate your support!
