### ISSUE TITLE
Python3 typings get correct solution to fail - 211. Design Add and Search Words Data Structure

### ISSUE THREAD

**Issue by svinkapeppa** [LeetCode-Feedback/LeetCode-Feedback#5427]
#### Your LeetCode username
[erubanenko](https://leetcode.com/erubanenko/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
I have two solutions to the problem [Design Add and Search Words Data Structure](https://leetcode.com/problems/design-add-and-search-words-data-structure/) that provide different result on submission

The only difference is the `__init__()` signature: `def __init__(self, terminal: bool = False, children: Dict[str, "Node"] = {})` VS `def __init__(self)`

When I provide signature with typings my solution gets rejected

Furthermore, when I run failed test as custom invocation I get correct answer (see screenshot below)

#### Code you used for Submit/Run operation
**Accepted**
```
class Node:
    def __init__(self):
        self.terminal = False
        self.children = {}

class WordDictionary:
    def __init__(self):
        self.head = Node()

    def addWord(self, word: str) -> None:
        node = self.head

        for c in word:
            node = node.children.setdefault(c, Node())

        node.terminal = True

    def search(self, word: str) -> bool:
        def dfs(node, i):
            if i == len(word):
                return node.terminal

            if word[i] == ".":
                for child in node.children:
                    if dfs(node.children[child], i + 1):
                        return True

            if word[i] in node.children:
                return dfs(node.children[word[i]], i + 1)

            return False

        return dfs(self.head, 0)
```

**Wrong Answer**
```
class Node:
    def __init__(self, terminal: bool = False, children: Dict[str, "Node"] = {}):
        self.terminal = terminal
        self.children = children

class WordDictionary:
    def __init__(self):
        self.head = Node()

    def addWord(self, word: str) -> None:
        node = self.head

        for c in word:
            node = node.children.setdefault(c, Node())

        node.terminal = True

    def search(self, word: str) -> bool:
        def dfs(node, i):
            if i == len(word):
                return node.terminal

            if word[i] == ".":
                for child in node.children:
                    if dfs(node.children[child], i + 1):
                        return True

            if word[i] in node.children:
                return dfs(node.children[word[i]], i + 1)

            return False

        return dfs(self.head, 0)
```

#### Language used for code
Python3

#### Expected behavior
Both solutions should give **Accepted**

#### Screenshots
<img width="1431" alt="Screenshot 2021-12-02 at 13 14 07" src="https://user-images.githubusercontent.com/22715919/144402217-c0b33983-3e45-4ba2-90cf-f455440c8bb9.png">

**Comment by LC-Sue** [comment]
Hi @svinkapeppa 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LPRowe** [comment]
HI @svinkapeppa this behavior is the result of using a mutable Kwarg. Specifically `children: Dict[str, "Node"] = {}`

In practice, when you want to initialize a Kwarg to a mutable data structure, the work-around is to set the default as None and then create an empty mutable data structure if needed.

```python
class Node:
    def __init__(self, terminal: bool = False, children: Optional[Dict[str, "Node"]] = None):
        self.terminal = terminal
        self.children = children if children != None else dict()
```
