### ISSUE TITLE
STL should not be counted as solution. 

### ISSUE THREAD

**Issue by Akshithsaai** [LeetCode-Feedback/LeetCode-Feedback#5428]
Solution

#### Description of the bug
Pow(x,n) should not be counted as solution. If it is used then 100% fast output is possible . But Its level will become very easy.
I think here using that function should be controlled as counted towards wrong answer or prohibited.

#### Code you used for Submit/Run operation
'''

```
class Solution {
public:
    double myPow(double x, int n) {
        return pow(x.n);
    }
};
```

#### Language used for code
 C++

**Comment by LC-Sue** [comment]
Hi @Akshithsaai,
Thank you for reaching out to us, could you provide the problem number for the issue you are reporting?

**Comment by Akshithsaai** [comment]
> Hi @Akshithsaai,
> Thank you for reaching out to us, could you provide the problem number for the issue you are reporting?

Question no is 50

**Comment by LC-Sue** [comment]
Hi @Akshithsaai 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Akshithsaai,
Thank you for your time. Our team believes that a change is not necessary. This problem is intended for the users to learn from not for competitive purposes, so the responsibility falls to the user to try to solve the problem in the correct way. We appreciate your support!

**Comment by Akshithsaai** [comment]
@LC-Sue   Thank you for taking time to consider my request.
