### ISSUE TITLE
Bug Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by otaviobr** [LeetCode-Feedback/LeetCode-Feedback#5430]
#### Your LeetCode username
user4966G

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I responded to the challenge with a code that returns what I expected but I get "wrong answer" as a return. It works on my computer but on the website it doesn't.

#### Code you used for Submit/Run operation
```

public class Solution 
{
    public ListNode AddTwoNumbers(ListNode l1, ListNode l2) 
    {
        PrintList(l1);
        PrintList(l2);

        var n1 = GetNumber(l1);
        var n2 = GetNumber(l2);

        Console.WriteLine($"N1: {n1}");
        Console.WriteLine($"N2: {n2}");
        Console.WriteLine($"N1 + N2: {n1 + n2}");

        var result = GetListNode(n1 + n2);
        PrintList(result);

        return result;
    }
    
    public static int GetNumber(ListNode list)
    {
        var internalList = list;
        var values = new List<int>();
        var result = 0;

        while (true)
        {
            values.Add(internalList.val);

            if (internalList.next is not null)
            {
                internalList = internalList.next;
            }
            else
            {
                break;
            }
        }

        var count = values.Count - 1;
        var weight = 0;
        for (var i = count; i >= 0; i--)
        {
            result += values[i] * (int)Math.Pow(10, weight);
            weight++;
        }

        return result;
    }

    public static ListNode GetListNode(int number)
    {
        ListNode node = null;

        var arrChars = number.ToString().ToCharArray();

        foreach (var chr in arrChars)
        {
            node = node is null 
                ? new ListNode(int.Parse($"{chr}")) 
                : new ListNode(int.Parse($"{chr}"), node);
        }

        return node;
    }

    public static void PrintList(ListNode list)
    {
        var internalList = list;

        while (true)
        {
            Console.Write($"{internalList.val} ");

            if (internalList.next is not null)
            {
                internalList = internalList.next;
            }
            else
            {
                break;
            }
        }

        Console.WriteLine();
    }
}

```

#### Language used for code
C#

#### Expected behavior
I believe the returned result is a bug. I ran the same code on my computer and the answer returned was correct.

#### Screenshots
Running in my personal computer:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/8741661/144439112-4d780956-dfc6-4cc4-ac4f-c80214f8f99b.png">

Running in leetcode:
<img width="935" alt="image" src="https://user-images.githubusercontent.com/8741661/144440955-5fcd54c1-adbe-4aed-8e3e-d2d6b7a26739.png">

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
