### ISSUE TITLE
Grammar - 9. Palindrome Number

### ISSUE THREAD

**Issue by FriskySaga** [LeetCode-Feedback/LeetCode-Feedback#5432]
#### Your LeetCode username

FriskySaga

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

"For example, 121 is palindrome while 123 is not."

The correct word to use here is _palindromic_. Alternative, the word _a_ must be added before the word _palindrome_.

**Comment by LC-Sue** [comment]
Hi @FriskySaga 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @FriskySaga 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
