### ISSUE TITLE
Missing Test Case - 2092. Find All People With Secret

### ISSUE THREAD

**Issue by linfangquan** [LeetCode-Feedback/LeetCode-Feedback#5433]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Missing Test Cases that the code below can NOT PASS.
Please check attachment.
[test_case_2092.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7643642/test_case_2092.txt)

#### Code you used for Submit/Run operation

```

class UnionFindSet(object):
    def __init__(self):
        self.data = collections.defaultdict(int)

    def find(self, x):
        while x <> self.data[x]:
            x = self.data[x]
        return x

    def union(self, x, y):
        if x not in self.data:
            self.data[x] = x
        if y not in self.data:
            self.data[y] = y
        self.data[self.find(max(x,y))] = self.find(min(x,y))

    def speedup(self):
        for x in self.data.keys():
            self.data[x] = self.find(x)


class Solution(object):
    def findAllPeople(self, n, meetings, firstPerson):
        hd = collections.defaultdict(list)
        for [x, y, t] in meetings:
            hd[t].append([x, y])

        ret = set([0, firstPerson])

        for t in sorted(hd.keys()):
            uf = UnionFindSet()
            for [x, y] in hd[t]:
                uf.union(x, y)
            uf.speedup()
            hs = collections.defaultdict(set)
            for k, v in uf.data.items():
                hs[v].add(k)
            for s in hs.values():
                if len(s & ret) > 0:
                    ret |= s
        return list(ret)
```

#### Language used for code
Python

#### Expected behavior

Add the test case to the problem

**Comment by LC-Sue** [comment]
Hi @linfangquan,
Thank you for reaching out, however the test case you provided returns invalid test case on my end and I am unable to verify the issue to report to our team. Could you double check that the format of the test case is correct in the file?

**Comment by linfangquan** [comment]
> Hi @linfangquan, Thank you for reaching out, however the test case you provided returns invalid test case on my end and I am unable to verify the issue to report to our team. Could you double check that the format of the test case is correct in the file?

Thanks for replying! My proposed test case  is a symmetrical case of 36 / 55 test cases of the problem.
The 36th test case is (100000, [[0,1,1],[0,2,1],...,[0,99999,1]],1), and my proposed test case is (100000,[[1,0,1],[2,0,1],...,[99999,0,1]],1). This mainly tests whether the union operation of UnionFindSet has been optimized for performance.
My code above can pass all existing test cases, but would not pass (100000,[[1,0,1],[2,0,1],...,[99999,0,1]],1) for "Time Limit Exceeded". So I suggest adding this test case to the problem.
Thanks again for your attention!

**Comment by LC-Sue** [comment]
Hi @linfangquan,
Thank you for reaching out, I noticed that the txt file that you provided were missing brackets which was why it reutrned invalid testcase the first time I tried. However, after adding the brackets, the test case is accepted, it may have been added by our team before I to file the issue. Thank you for your time! 
![image](https://user-images.githubusercontent.com/92285126/145127858-ec2ab06a-3d4a-47ed-80bb-2d7e36138b71.png)

**Comment by linfangquan** [comment]
Hi @LC-Sue,
Thanks for replying! It does output correct result, but would cost much more time comparing to  (100000, [[0,1,1],[0,2,1],...,[0,99999,1]],1) if the application of UnionFind was not optimized via rank balence.
If you ran my code, you would find the significant difference of running time  between (100000, [[0,1,1],[0,2,1],...,[0,99999,1]],1) and (100000,[[1,0,1],[2,0,1],...,[99999,0,1]],1).

**Comment by linfangquan** [comment]
@LC-Sue 
[Accepted] https://leetcode.com/submissions/detail/595970716/
[Time Limit Exceeded] https://leetcode.com/submissions/detail/595969960/
The only diff is self.data[self.find(x)] = self.find(y) and self.data[self.find(y)] = self.find(x)

**Comment by LC-Sue** [comment]
Hi @linfangquan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @linfangquan 
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username?
