### ISSUE TITLE
Missing Test Cases - 2093. Minimum Cost to Reach City With Discounts

### ISSUE THREAD

**Issue by idontknoooo** [LeetCode-Feedback/LeetCode-Feedback#5434]
#### Your LeetCode username
idontknoooo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The provided solution below passed all current test cases, however, for the below test case, the correct answer is 156. It's giving 255 with the solution provided below.
```
6
[[0,1,2],[1,3,4],[0,2,6],[2,3,8],[3,4,100],[4,5,200]]
2
```
#### Code you used for Submit/Run operation
```python
class Solution:
    def minimumCost(self, n: int, highways: List[List[int]], discounts: int) -> int:
        graph = collections.defaultdict(list)
        for a, b, c in highways:
            graph[a].append((b, c))
            graph[b].append((a, c))
        heap = [(0, 0, discounts, False)]
        visited = set()
        while heap:
            cost, node, dis, used = heapq.heappop(heap)
            if (node, used) in visited: continue
            visited.add((node, used))    
            if node == n-1:
                return cost
            for nei, nei_c in graph[node]: 
                if (nei, False) not in visited:
                    heapq.heappush(heap, (cost+nei_c, nei, dis, False))
                if dis > 0 and (nei, True) not in visited:
                    heapq.heappush(heap, (cost+nei_c//2, nei, dis-1, True))
        return -1
```

#### Language used for code
Python 3

#### Expected behavior
The above solution passed all current test cases, however, the correct answer is 156. It's giving 255 with the above solution.

Please add the above test case to eliminate the issue.

**Comment by LC-Sue** [comment]
Hi @idontknoooo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @idontknoooo 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
