### ISSUE TITLE
Graph Explore card for Quick Union Incorrect Analysis

### ISSUE THREAD

**Issue by prerana27** [LeetCode-Feedback/LeetCode-Feedback#5436]
For the [Quick Union](https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3840/) time complexity explanation in the Graph track, it says the following:

"Note: N is the number of vertices in the graph. In the worst-case scenario, the number of operations to get the root vertex will be H where H is the height of the tree, however, because this implementation always points the root of the shorter tree to the root of the taller tree H will be at most logN."

However in this implementation we do not actually merge the shorter tree into the larger one. It's always merges the second tree into the first. Hence its worst case analysis for all 3 operations i.e. find, union and connected would be O(N) and not O(logN) as mentioned.

**Comment by LC-Sue** [comment]
Hi @prerana27 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @prerana27 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
