### ISSUE TITLE
Missing Test Case - 708. Insert into a Sorted Circular Linked List

### ISSUE THREAD

**Issue by raditya1710** [LeetCode-Feedback/LeetCode-Feedback#5437]
#### Your LeetCode username
alfonsus_raditya

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
`head = [3,5,6,3], insertVal = 3` is considered invalid testcase: `'Linked List' must be non-decreasing`

#### Code you used for Submit/Run operation

```
/*
// Definition for a Node.
class Node {
public:
    int val;
    Node* next;

    Node() {}

    Node(int _val) {
        val = _val;
        next = NULL;
    }

    Node(int _val, Node* _next) {
        val = _val;
        next = _next;
    }
};
*/

class Solution {
public:
    Node* insert(Node* head, int insertVal) {
        if(head == nullptr) {
            Node* ans = new Node(insertVal);
            ans->next = ans;
            return ans;
        }
        
        recurse(head, head, insertVal);
        return head;
    }
    
    void recurse(Node* cur_head, Node* head, int val) {
        bool is_between = (cur_head->val <= val && val <= cur_head->next->val);
        bool is_highest = (cur_head->val > cur_head->next->val);
        bool is_last_node = (cur_head->next == head);
        if(is_between || is_last_node || (is_highest && (val <= cur_head->next->val || cur_head->val <= val))) {
            Node* now = new Node(val);
            now->next = cur_head->next;
            cur_head->next = now;
            return;
        }
        
        recurse(cur_head->next, head, val);
    }
};
```

#### Language used for code
C++

#### Expected behavior

Linked List `[3,5,6,3]` is still non decreasing if seen from the last node, but it is considered decreasing by judge. 

#### Screenshots

![Screenshot from 2021-12-03 07-49-06](https://user-images.githubusercontent.com/14028227/144526032-aa7c4ead-138f-40e4-a76f-31b3b9b123e7.png)
![Screenshot from 2021-12-03 07-49-02](https://user-images.githubusercontent.com/14028227/144526035-80d5801b-0e60-472e-b0a2-84c4a85606ef.png)

**Comment by LC-Sue** [comment]
Hi @raditya1710 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @raditya1710 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
