### ISSUE TITLE
Dynamic Programming Explore card for Chapter 1 Quiz questions using wrong type 

### ISSUE THREAD

**Issue by barnett617** [LeetCode-Feedback/LeetCode-Feedback#5438]
#### Your LeetCode username

[barnett617](https://github.com/barnett617)

#### Description of the bug

For the [Chapter 1 Quiz](https://leetcode.com/explore/learn/card/dynamic-programming/630/an-introduction-to-dynamic-programming/4095/), questions except the first one are all **Single Choice Quesitons**, but tagged wrong types.

#### Expected behavior

Questions except the first one should be tagged **Single Choice Question**.

#### Screenshots

<img width="808" alt="WX20211203-095423@2x" src="https://user-images.githubusercontent.com/23159565/144531396-bca449eb-8708-404e-a3cb-2ad6528e4416.png">

**Comment by stormsunshine** [comment]
The term "multiple choice" is always used for choices. Here "multiple" means that there are multiple items that can be selected, not that there are multiple correct items. There is no such a term called "single choice".

To distinguish whether there is only one correct item or there may be one or more correct items, the question statement will make it clear. For the first question above, the statement "Select all that apply" means that there may be one or more correct items. For the remaining questions, there is no extra statement, so there is only one correct item for each question.

**Comment by barnett617** [comment]
> 



> The term "multiple choice" is always used for choices. Here "multiple" means that there are multiple items that can be selected, not that there are multiple correct items. There is no such a term called "single choice".
> 
> To distinguish whether there is only one correct item or there may be one or more correct items, the question statement will make it clear. For the first question above, the statement "Select all that apply" means that there may be one or more correct items. For the remaining questions, there is no extra statement, so there is only one correct item for each question.

**Comment by barnett617** [comment]
> The term "multiple choice" is always used for choices. Here "multiple" means that there are multiple items that can be selected, not that there are multiple correct items. There is no such a term called "single choice".
> 
> To distinguish whether there is only one correct item or there may be one or more correct items, the question statement will make it clear. For the first question above, the statement "Select all that apply" means that there may be one or more correct items. For the remaining questions, there is no extra statement, so there is only one correct item for each question.

Thanks for your instant explanation.
