### ISSUE TITLE
Missing Related Topics - 853. Car Fleet

### ISSUE THREAD

**Issue by WillWcchan** [LeetCode-Feedback/LeetCode-Feedback#5439]
LeetCode username
WillWcchan

I think it's missing the keyword - **stack** to the **Related Topics** 

It doesn't have to be solved with a stack, but can be helpful.

Currently it's **Array** and **Sorting**

**Comment by LC-Sue** [comment]
Hi @WillWcchan 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
