### ISSUE TITLE
LinkedList - Add two numbers - typescript error

### ISSUE THREAD

**Issue by mjcrouch** [LeetCode-Feedback/LeetCode-Feedback#544]
#### Your LeetCode username

Zogger

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] I don't understand the actual definition / delineation of the above categories - It would probably be a good idea to add some words to the template to clarify them...

#### Description of the bug

When trying to code a solution for the [linked list - add two numbers](https://leetcode.com/explore/interview/card/top-interview-questions-medium/107/linked-list/783/) challenge in typescript, attempting to use the ListNode() constructor results in the following error:

```
(node:31) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `nodejs run --trace-warnings ...` to show where the warning was created)
Line -1 in solution.js
import { ListNode } from "precompiled/ts_types";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    Line 1116: Char 16 in loader.js (wrapSafe)
    Line 1164: Char 27 in loader.js (Module._compile)
    Line 1220: Char 10 in loader.js (Object.Module._extensions..js)
    Line 1049: Char 32 in loader.js (Module.load)
    Line 937: Char 14 in loader.js (Function.Module._load)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    Line 17: Char 47 in run_main_module.js
```

edit: after experimenting - I found the following:

* the same error occurs for the next challenge "Odd Even linked lists"
* "Intersection of two linked lists" does not offer TypeScript as an option

and later..
* same error in Binary Tree ZigZag level order and presumably the later levels

#### Code you used for Submit/Run operation

I've boiled it down to the following:

```typescript
function addTwoNumbers(l1: ListNode | null, l2: ListNode | null): ListNode | null {
    return new ListNode(0);
}
```

(I do have a working solution with a real implementation that works locally, but exhibits the same error online)

#### Language used for code

TypeScript

#### Expected behavior

In this case, the test should fail because the output is incorrect, but instead the error above is shown

#### Additional context

Note that this code, where I don't actually use the class, compiles, (But obviously failes given the answer is incorrect)

```typescript
function addTwoNumbers(l1: ListNode | null, l2: ListNode | null): ListNode | null {
    return null;
}
```

~I haven't tried the other LinkedList exercises yet..~

**Comment by lc-kate** [comment]
Hi @mjcrouch ,
Thank you for reaching out to us. I've relayed this issue to our engineers for investigation. But since this issue is not a content-issue, I will be closing this issue for now. When more updates for this issue, I'll share it with you by tagging you in this ticket comment. Thank you for your support :)
