### ISSUE TITLE
Dynamic Programming Page in Heap Exp

### ISSUE THREAD

**Issue by NigelBernard** [LeetCode-Feedback/LeetCode-Feedback#5440]
#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In 'Detailed Explanation of Heap', there appears a DP page that is unrelated to Heap material.
Located @Common Applications of Heap/Time and Space Complexity

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @NigelBernard,
Thank you for reaching out, this issue has been filed with our team and we are working on a fix!

**Comment by LC-Sue** [comment]
Hi @NigelBernard
Thank you for your time, we have resolved this issue. We appreciate your support!
