### ISSUE TITLE
Upgrade to .NET 6.0

### ISSUE THREAD

**Issue by evgeni-nabokov** [LeetCode-Feedback/LeetCode-Feedback#5441]
#### Your LeetCode username
evgeni-nabokov

#### Category of the bug
- [*] Language

#### Description of the bug
Could you upgrade .NET environment to .NET 6.0, please?
It is very desirable because the new env has a built-in PriorityQueue.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
C#

#### Expected behavior
N/A

#### Screenshots
N/A

#### Additional context
.NET 6.0 has a built-in PriorityQueue.

**Comment by LC-Sue** [comment]
Hi @evgeni-nabokov,
Thank you for reaching out to us. I have relayed this upgrade request over to our team for consideration!
