### ISSUE TITLE
Maximum Product Subarray solution got error

### ISSUE THREAD

**Issue by bosenli** [LeetCode-Feedback/LeetCode-Feedback#5442]
#### Your LeetCode username

bosenli2019

#### Category of the bug

- [ ] Solution

#### Description of the bug

python solution for question "Maximum Product Subarray" does not provide result. it has 

Time Limit Exceeded bug

#### Code you used for Submit/Run operation

```
// Maximum Product Subarray
class Solution:
    def maxProduct(self, nums: List[int]) -> int:
        if len(nums) == 0:
            return 0

        result = nums[0]

        for i in range(len(nums)):
            accu = 1
            for j in range(i, len(nums)):
                accu *= nums[j]
                result = max(result, accu)

        return result

```

#### Expected behavior

it should out the maximum subarray but there is no result.

**Comment by LC-Sue** [comment]
Hi @bosenli 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @bosenli,
Thank you for sharing your concern. This is the expected behavior for a brute force approach as this approach would not be accepted in an interview setting. That said, we have added a cautionary note for future users regarding this.
