### ISSUE TITLE
Missing Test Case - 1502. Can Make Arithmetic Progression From Sequence

### ISSUE THREAD

**Issue by h-bruch** [LeetCode-Feedback/LeetCode-Feedback#5445]
#### Your LeetCode username

h-bruch

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Not enough test cases to refute sum-based algorithm. Testcase [3,6,9,11,16,18] refutes code below

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def canMakeArithmeticProgression(self, arr: List[int]) -> bool:
        a=min(arr)
        b=float('inf')
        c=float('inf')
        n=len(arr)
        if n==2 or n==1:
            return True
        for i in arr:
            if i>a and i<b:
                b=min(b,i)
        for i in arr:
            if i>b and i>a: 
                c=min(c,i)
        
            
        b=a if b==float('inf') else b
        c=b if  c==float('inf') else c
        if b-a!=c-b:return False
        d=b-a
        tsum=sum(arr)
        calsum=((n)*(2*a+(n-1)*d))/2
        if calsum==tsum:
            return True
        else:
            return False
```

#### Language used for code
Python3

#### Expected behavior

No arithmetic progression possible, solution should be rejected

#### Additional context

See here:
https://leetcode.com/problems/can-make-arithmetic-progression-from-sequence/discuss/1602236/Python-TIME-O(n)-SPACE-O(1)

**Comment by LC-Sue** [comment]
Hi @h-bruch 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @h-bruch 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
