### ISSUE TITLE
Missing Test Case - 84. Largest Rectangle in Histogram

### ISSUE THREAD

**Issue by PalmerMa** [LeetCode-Feedback/LeetCode-Feedback#5448]
public int largestRectangleArea(int[] heights) {
		if(heights == null || heights.length == 0) {
			return 0;
		}
		if(heights.length == 1) {
			return heights[0];
		}
		
		int size = heights.length;
		int largest = 0;
		for(int num =0;num<size;num++) {
			int now = heights[num];
			if(now != 0) {
				int sum = now;
				boolean leftStop = false;
				boolean rightStop = false;
				for(int left = num-1; left>=0;left--) {
					if(heights[left]>=heights[num] && !leftStop) {
						sum = sum+ now;
					} else {
						leftStop = true;
					}
				}
				for (int right = num+1; right<size;right++ ) {
					if(heights[right]>=heights[num] && !rightStop) {
						sum = sum+ now;
					} else {
						rightStop = true;
					}
				}
				if(sum>largest) {
					largest = sum;
				}
			}
		
		}
        return largest;
    }

**Comment by PalmerMa** [comment]
time limited issue...

**Comment by LC-Sue** [comment]
Hi @PalmerMa,
Thank you for reaching out to us, could you provide more details about the missing test case? If you are not reporting for a missing test case, feel free to refer to the discuss section of the problem to see how others have optimized their codes!
