### ISSUE TITLE
Minor Mistakes in Problem Description - 929. Unique Email Addresses

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5449]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [929. Unique Email Addresses](https://leetcode.com/problems/unique-email-addresses), some variable names are incorrect. The variable name should be `emails`, not `email`.

Please refer to the screenshots below. Both `email[i]` should be changed to `emails[i]`.

#### Expected behavior
The mistakes mentioned above should be corrected. Both `email[i]` should be changed to `emails[i]`.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/144618053-9f8c7b5c-f659-4332-abb0-0805399c2a07.png)
![image](https://user-images.githubusercontent.com/12067364/144618146-3d33dcb2-81a2-41e0-9b90-6d5fbe1c8330.png)

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
