### ISSUE TITLE
"最长重复子串" 题解有误

### ISSUE THREAD

**Issue by SamZhangQingChuan** [LeetCode-Feedback/LeetCode-Feedback#545]
**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
[题解](https://leetcode-cn.com/problems/longest-duplicate-substring/solution/zui-chang-zhong-fu-zi-chuan-by-leetcode/) 中提到的使用 2^32 作为模数是众所周知的不可取的方法。可以轻松被 https://codeforces.com/blog/entry/60442 中的方法卡掉，请使用大素数作为 mod。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
实在抱歉，因题目涉及到全球，经题目团队综合评估反馈，该题解暂不修复。非常感谢您这样的积极用户对力扣网站的支持，祝您生活愉快。ˆ＾‿＾

**Comment by SamZhangQingChuan** [comment]
恕我不能理解，让这种错误方法继续流传于世真的是 LeetCode 的价值观吗？祝贵司在不专业的标签下越走越远。
