### ISSUE TITLE
bug in this page: Time and Space Complexity

### ISSUE THREAD

**Issue by PingPongSet** [LeetCode-Feedback/LeetCode-Feedback#5450]
This page below
https://leetcode.com/explore/learn/card/heap/644/common-applications-of-heap/4027/
is the same as below
https://leetcode.com/explore/learn/card/dynamic-programming/631/strategy-for-solving-dp-problems/4101/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @PingPongSet,
Thank you for reaching out to us. This issue has already been filed with our team and we are working on a fix!
