### ISSUE TITLE
Follow up in the problem statement gives away the solution

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#5451]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Follow up in the Problem statement https://leetcode.com/problems/wiggle-sort/ mentions to try solving the problem without sorting the array which gives a vital hint that sorting can be used to solve the problem.

#### Expected behavior
Follow up should be rephrased to state `Could you do it in O(n) time complexity`

**Comment by LC-Sue** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
