### ISSUE TITLE
Minor issue with verbiage in 595. Big Countries

### ISSUE THREAD

**Issue by jswgit01** [LeetCode-Feedback/LeetCode-Feedback#5453]
#### Your LeetCode username
jsw_leet

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The criteria in the description for **_question_** [595. Big Countries](https://leetcode.com/problems/big-countries/) is listed as follows:

> - it has an area of **at least** three million (i.e., 3000000 km2), or
> - it has a population of **at least** twenty-five million (i.e., 25000000).

"At least" implies that the lower limit should be included, therefore the solution should require ">=".  

The wording in the description of the **_solution_** appears as follows, which is different from the question and implies different criteria ">".

> According to the definition, a big country meets at least one of the following two conditions:
> 
> - It has an area of **bigger than** 3 million square km.
> - It has a population of **more than** 25 million._

The solution accepts answers with both ">" and ">=", which are not the same, because none of the test cases have values equal to the lower limit specs.  

#### Recommendation
Update at least one record to include the lower limit value of area or population which would stop both solutions from evaluating as TRUE.
Update verbiage to be consistent across problem and solution. 

#### Code you used for Submit/Run operation

Both of these solutions were accepted
```
SELECT 
    name
    ,population
    ,area
FROM World
WHERE (area >=3000000 OR population >= 25000000)
```
```
SELECT 
    name
    ,population
    ,area
FROM World
WHERE (area >=3000000 OR population > 25000000)
```
#### Language used for code

T-SQL

**Comment by LC-Sue** [comment]
Hi @jswgit01 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jswgit01 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
