### ISSUE TITLE
Hints can be misleading

### ISSUE THREAD

**Issue by SravanthiAshokKumar** [LeetCode-Feedback/LeetCode-Feedback#5454]
#### Your LeetCode username

PracticeLeet

#### Category of the bug
- [ ] Question
https://leetcode.com/problems/airplane-seat-assignment-probability/
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

1227. Airplane Seat Assignment Probability
The hints seem to be misleading. This problem is more of a math problem than a programming related one. It might be tricky to arrive at the solution, but there's no requirement of dp for this problem. Although this can be done through dp, it's completely unnecessary to do it that way. 

#### Code you used for Submit/Run operation

```
public double nthPersonGetsNthSeat(int n) {
        if (n==1) {
            return 1;
        }
        return 0.5;
    }
```
This code passed all the tests.

#### Language used for code

Java

#### Expected behavior

The Hints can point the users towards an arithmetic/analytical thinking rather than the dp mindset.

**Comment by LC-Sue** [comment]
Hi @SravanthiAshokKumar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @SravanthiAshokKumar 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
