### ISSUE TITLE
A Follow-up Can Be Added - 1823. Find the Winner of the Circular Game

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5455]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This issue is to reopen #5369 . Since my last comment in the previous issue was not replied, I create a new issue.

In the previous issue, I suggested adding a follow-up question. The follow-up question should be as follows.

**Follow-up:** Could you solve the problem in O(n) time complexity?

Although the reply was that the O(n) math solution was not required during the interview, I do not agree with this point. **Please read the following points seriously and reconsider adding this follow-up.**

1. I don't think that the O(n) math solution is out of scope of interviews. Please take a look at this problem: [剑指 Offer 62. 圆圈中最后剩下的数字](https://leetcode-cn.com/problems/yuan-quan-zhong-zui-hou-sheng-xia-de-shu-zi-lcof).
The problem in the link above is only in LCCN and not in LCUS, but the content is almost the same as problem 1823, except that the numbers start from 0, and the constraints are different. In the link above, the constraints are `1 <= n <= 10^5` and `1 <= m <= 10^6`, where `m` is equivalent to `k` in problem 1823. Since the maximum value `n` is `10^5`, a solution with time complexity O(n^2) will not get passed, **so a solution with time complexity O(n) must be used**.
The problem in the link above is from a book that contains interview problems, which means that the problem is used in an interview and time complexity O(n) may be required during an interview.

2. Even if the O(n) solution is not required in some interviews (depending on different requirements), the O(n) solution is still quite common and the difficulty of the O(n) solution is not that hard. Although the O(n) solution is more difficult than the O(n^2) solution, the O(n) solution is still easier than most Hard problems in LeetCode.
Since some problems contain follow-up questions that are beyond the scope of interviews and are too difficult for interviews, like problem 378, it is quite acceptable that the O(n) solution is added as a follow-up question for problem 1823.

I understand that the problem is the second problem in a weekly contest and the problem is designed to accept O(n^2) solutions, so I am not requiring that the constraints should be changed or more test cases should be added. I am only requiring that a follow-up question should be added.

The O(n) math solution is quite a nice solution and is worth knowing, even if it is not required during an interview.

Last but not least, even if the interviewer is expecting an O(n^2) solution, the interviewee can still provide an O(n) solution. In this case, the interviewer will surely be very satisfied with the interviewee and the interviewee will be very likely to be accepted.

#### Expected behavior
Add a follow-up question for problem 1823.

**Follow-up:** Could you solve the problem in O(n) time complexity?

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for reaching out to us, I will relay this issue over to our team again for consideration, but please know that the decision is made by our content team.

**Comment by stormsunshine** [comment]
@LC-Sue Is there any update on this issue? Now the follow-up is still not added for problem 1823.

I wonder why the content team don't want to add the follow-up. The reason was that the O(n) solution is not required during an interview, but from my point of view, this reason is insufficient and even incorrect. I have mentioned that the O(n) solution can surely be used in an interview.

The solution with time complexity O(n) can be implemented either recursively or iteratively, with space complexity O(n) and O(1) respectively. If an interviewee provides the solution with time complexity O(n) and space complexity O(1), the interviewee will surely receive a "strong hire" result. Even if an interviewee provides the solution with time complexity O(n) and space complexity O(n), the interviewee will be very likely to receive a "strong hire" result, since the solution is much better than the O(n^2) solution.

From the content team's perspective, adding a follow-up question takes only a little effort, since the constraints don't need to be changed, and no new test cases need to be added. I really don't understand why the content team don't want to add the follow-up.

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for your patience. I've checked with our content team and the initial response holds. The problem was intentionally added with small constraints to allow the O(n^2) solution and the O(n) math solution was not required during the interview. Sorry for any inconvenience!
