### ISSUE TITLE
Missing Test Case - 1032. Stream of Characters

### ISSUE THREAD

**Issue by tejasvi** [LeetCode-Feedback/LeetCode-Feedback#5456]
#### Your LeetCode username

`tstomar`

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Accepted solution fails on a test case satisfying the problem constraints.

#### Code you used for Submit/Run operation

```python3
// 1032. Stream of Characters
class StreamChecker:

    def __init__(self, words: List[str]):
        maxl = max(len(w) for w in words)
        self.q = deque(maxlen=maxl)
        self.dlist = [defaultdict(set) for _ in range(maxl)]
        for j, w in enumerate(words):
            for i, c in enumerate(reversed(w)):
                self.dlist[i][c].add(w)

    def query(self, letter: str) -> bool:
        cur = self.dlist[0][letter]
        self.q.appendleft(letter)
        for i, (d, c) in enumerate(zip(self.dlist, self.q)):
            cur = cur.intersection(d[c])
            if not cur:
                return False
            if (i + 1) in (len(w) for w in cur):
                return True
        return False
```

#### Language used for code

Python 3

#### Expected behavior

The test case gives TLE for AC solution.

#### Additional context

The test case input file generated using the below code is attached.

Input file: [1032. Stream of Characters test case input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7653515/1032.Stream.of.Characters.test.case.input.txt)

```python3
num_queries = 4 * (10 ** 4)
word_count = 2000
word_length = 2000

word = "a" * word_length
with open("test_cast_input.txt", "w") as f:
    f.write(
        f"""["StreamChecker"{', "query"'*num_calls}]
[[["{word}"{f', "{word}"' * (word_count - 1)}]]{', ["a"]' * num_queries}]"""
    )
```

**Comment by LC-Sue** [comment]
Hi @tejasvi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @tejasvi
Thank you for your time. The test case you provided is too large (~5MB) and cannot be added to the platform. We appreciate your support!
