### ISSUE TITLE
Missing Test Case - 1032. Stream of Characters

### ISSUE THREAD

**Issue by DevAdarshAnurag** [LeetCode-Feedback/LeetCode-Feedback#5457]
#### Your LeetCode username

a4adarshanurag

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A brute force solution is getting accepted. The solution makes use of a map with key as the last character of a word and value as a vector of indices. Then the solution checks character by character for each word in the vector of indices to find the answer. Please see the code below.

#### Code you used for Submit/Run operation

```
// Stream of characters
class StreamChecker {
public:
    string s;
    vector<string> v;
    unordered_map<char, vector<int>> m;
    
    StreamChecker(vector<string>& words) {
        v=words;
        for(int i=0;i<words.size();i++) 
            m[words[i].back()].push_back(i); // create map [key: last character, value : vector of indices]
    }
    
    bool query(char letter) {
        s+=letter;
        for(auto& i:m[letter]) {
            bool is=true;
            for(int j=v[i].size()-1, k=s.size()-1;j>=0;j--, k--) { //compare each word with last character = letter with string s (concatenation of query)
                if(k<0 || v[i][j]!=s[k]) {
                    is=false;
                    break;
                }
            }
            if(is) return true;
        }
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The above solution should timeout.
I propose a test-case where every word in the stream checker ends with the same last two characters as the query letter, so that looping over the vector indices can cause a timeout.

The proposed test-case has 1664 words of length 11 and 4x10^4 query. Good enough to cause TLE in brute force solutions. A more robust test case will be of 2000 words each 2000 in length and 4x10^4 queries with the same character only (i.e making full use of the input constraints).

A correct solution using suffix trie is able to pass both the test cases.

Test case:
[Sream of characters 1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7653605/Sream.of.characters.1.txt)

#### Screenshots

A proper solution using suffix tree passes.
![Suffix trie passes](https://user-images.githubusercontent.com/35106820/144703219-77630c36-409c-473a-a7ed-b971f61cfff7.PNG)

Above solution timeouts.
![TLE for the above solution](https://user-images.githubusercontent.com/35106820/144703132-a8e9c73c-d5cf-4f86-a96b-fab92ea70503.PNG)

**Comment by LC-Sue** [comment]
Hi @DevAdarshAnurag 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @DevAdarshAnurag,
Thank you for your time, we have added the test case to the problem and the solution is still accepted.
