### ISSUE TITLE
344 Reverse String

### ISSUE THREAD

**Issue by Mihir-Bhasin** [LeetCode-Feedback/LeetCode-Feedback#5458]
#### Your LeetCode username

mihirbhasin10

#### Category of the bug
- [ ] Question
- [* ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
```
class Solution {
public:
    string reverseString(string s) {
        int i = 0, j = s.size() - 1;
        while(i < j){
            swap(s[i++], s[j--]); 
        }
        
        return s;
    }
};
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->

![image](https://user-images.githubusercontent.com/57122515/144703628-2ed9a422-5c52-43a4-bb0c-eb25b1a207c7.png)


#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Sue** [comment]
Hi @Mihir-Bhasin 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
