### ISSUE TITLE
Queue Card:   BFS - Template, Bug, it is not finding shortest path

### ISSUE THREAD

**Issue by PingPongSet** [LeetCode-Feedback/LeetCode-Feedback#5459]
The code below from the link below is not finding the shortest path. 

The comments in the code and in the article should be rectified accordingly.

> /**
>  * Return the length of the shortest path between root and target node.
>  */
> int BFS(Node root, Node target) {
>     Queue<Node> queue;  // store all nodes which are waiting to be processed
>     int step = 0;       // number of steps neeeded from root to current node
>     // initialize
>     add root to queue;
>     // BFS
>     while (queue is not empty) {
>         step = step + 1;
>         // iterate the nodes which are already in the queue
>         int size = queue.size();
>         for (int i = 0; i < size; ++i) {
>             Node cur = the first node in queue;
>             return step if cur is target;
>             for (Node next : the neighbors of cur) {
>                 add next to queue;
>             }
>             remove the first node from queue;
>         }
>     }
>     return -1;          // there is no path from root to target
> }

https://leetcode.com/explore/learn/card/queue-stack/231/practical-application-queue/1372/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @PingPongSet 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
