### ISSUE TITLE
Missing Test Case For Question 5 Longest Palindromic Substring

### ISSUE THREAD

**Issue by kiwirafe** [LeetCode-Feedback/LeetCode-Feedback#546]
I used Solution 1 and came up with the code below. My answer got [accepted](https://leetcode.com/submissions/detail/358787700/). However, when I tested this case:
#### `sadefdaofegadfedag`

I got **`adefda`** instead of the correct answer **`s`**

This means that you have to check the sub-string is palindromic or not, and by that, the Time Complexity should be **O(n^3)**

Full Code Below
```
class Solution:
    def LCSubStr(self, X, Y):
        m = len(X)
        n = len(Y) 
        LCSuff = [[0 for k in range(n+1)] for l in range(m+1)] 
        maxLen = 0 
        end = 0
  
        for i in range(m + 1): 
            for j in range(n + 1): 
                if (i == 0 or j == 0): 
                    LCSuff[i][j] = 0
                elif (X[i-1] == Y[j-1]):                     
                    LCSuff[i][j] = LCSuff[i-1][j-1] + 1              
                    if LCSuff[i][j] > maxLen and X[i-LCSuff[i][j] : i][0] == X[i-LCSuff[i][j] : i][-1]:                        
                        end = i 
                        maxLen = LCSuff[i][j]                                      
                else: 
                    LCSuff[i][j] = 0
        return (maxLen, end)
    def longestPalindrome(self, s: str) -> str:
        revStr = s[::-1]
        (maxLen, end) = self.LCSubStr(s, revStr)  
        return s[end-maxLen:end]
```

**Comment by lc-christina** [comment]
Hi @kiwirafe 
Thank you for reaching out to us. I've submitted the code that you provided above but received Time Limit Exceeded error. Please see the screenshot attached. Can you please help confirm if you still get accepted?
<img width="1419" alt="Screen Shot 2020-06-30 at 5 01 51 PM" src="https://user-images.githubusercontent.com/67175512/86188538-ca2d3100-baf3-11ea-9a85-0a520ae99bc9.png">

**Comment by lc-christina** [comment]
Hi @kiwirafe  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
