### ISSUE TITLE
面试题 16.19. 水域大小  同一个用例，正式提交与控制台执行结果不一致

### ISSUE THREAD

**Issue by lankuohsing** [LeetCode-Feedback/LeetCode-Feedback#5460]
**你的 LeetCode 用户名**
国兴蓝
**Bug 类型**
其他

**描述**
我的同一份代码，针对同一个用例，正式提交显示我解答错误，但是我将该用例放到控制台执行，确实解答正确的

**你使用的语言**
python

**你提交或者运行的代码**
```
class Solution:
    directions=[(-1,-1),(-1,0),(-1,1),(0,-1),(0,1),(1,-1),(1,0),(1,1)]
    temp_size=0
    results=[]
    def dfs(self, land, i, j):
        if not(0<=i<len(land) and 0<=j<len(land[i]) and land[i][j]==0):
            return
        self.temp_size+=1
        land[i][j]=-1
        for k,direction in enumerate(self.directions):
            self.dfs(land,i+direction[0],j+direction[1])
    def pondSizes(self, land: List[List[int]]) -> List[int]:
        for i in range(0,len(land)):
            for j in range(0,len(land[i])):
                if land[i][j]==0:
                    self.dfs(land,i,j)
                    self.results.append(self.temp_size)
                    self.temp_size=0
        self.results.sort()
        return self.results

```

**期望行为**
针对用例
[[2,8,8,4,1,7,1,5,4,2,0,8,1,9,2,5,6,9,7,4,8,9,1,7,3,6,9,3,7,1,5,7,3,1,9,9,9,6,5,1,9,9,4,1,6,4,7,6,1,6,1,3,3,9,0,3,0,0,0,1,3,1,2,0,0,0,3,2,7,3,6,7,9],[2,0,9,8,2,0,5,8,4,0,4,5,2,1,5,6,0,6,3,3,6,9,5,4,0,9,4,7,1,4,2,8,9,8,0,6,3,5,7,2,1,6,8,4,8,4,6,5,0,3,7,1,7,6,3,0,2,2,2,3,2,4,7,7,6,8,2,9,2,5,0,3,8],[2,7,0,1,1,3,6,5,6,0,7,0,2,4,5,0,3,7,3,1,5,7,9,8,8,0,9,8,1,9,4,7,5,6,5,4,1,7,7,4,4,3,8,3,5,3,3,8,7,4,5,4,8,0,2,0,4,7,5,4,3,9,1,9,4,9,2,2,2,4,1,2,9],[6,0,4,4,6,7,8,8,9,9,5,4,9,7,0,4,2,7,1,9,2,2,9,2,4,3,0,5,1,7,8,9,0,5,3,3,3,1,1,7,1,2,7,5,6,8,7,2,3,1,5,3,5,7,9,7,7,8,8,7,2,4,4,2,8,2,3,2,1,9,1,2,7],[2,5,1,2,2,5,8,2,8,7,4,5,9,8,9,6,0,9,7,0,5,8,8,3,3,8,1,9,4,8,2,3,4,9,1,2,4,5,1,5,4,4,6,9,2,3,3,1,2,2,4,1,2,7,4,6,9,2,3,5,9,7,7,4,9,9,4,7,1,5,5,7,6],[9,9,9,1,8,3,3,4,6,5,7,7,3,1,1,3,9,2,7,0,6,8,8,0,2,9,6,6,4,4,6,2,6,6,1,7,5,6,4,9,6,9,8,2,1,4,3,4,6,6,8,6,4,7,8,3,7,1,3,7,5,3,2,1,4,7,9,7,3,4,9,0,1],[7,1,4,9,7,2,1,9,0,9,7,4,5,3,5,2,6,5,6,0,5,0,5,3,1,1,7,9,6,2,1,8,3,4,7,4,2,1,3,5,9,7,7,5,6,1,0,3,6,3,7,9,6,5,1,4,5,7,2,3,5,3,5,2,0,9,5,1,8,6,0,0,6],[7,9,9,8,8,3,9,7,5,1,1,8,4,4,6,3,7,2,1,9,5,6,1,2,2,5,6,3,9,6,7,9,2,7,1,4,7,3,5,0,1,2,2,5,4,9,3,1,2,1,1,0,5,1,8,4,2,1,2,4,5,4,5,6,8,7,7,4,8,3,2,7,9],[6,6,6,7,0,8,7,6,2,6,3,1,4,6,6,9,6,2,0,5,4,9,9,9,8,8,6,2,4,3,1,6,6,4,4,4,3,1,8,1,8,3,9,5,2,7,0,0,4,0,6,9,2,0,3,1,6,3,0,7,9,3,9,4,3,6,7,9,8,9,4,2,7],[7,8,1,8,5,3,5,1,2,9,6,2,8,7,9,7,7,8,6,3,4,4,3,2,8,6,5,7,8,5,7,5,8,3,9,6,8,9,6,6,8,7,4,9,4,6,1,1,6,7,5,6,7,0,3,3,9,3,6,1,3,8,1,2,8,3,3,6,7,9,4,4,1],[0,7,6,7,6,4,3,1,7,8,0,0,3,1,1,7,9,2,7,9,4,9,6,2,6,6,4,0,1,8,5,6,8,1,3,8,3,7,7,9,8,4,2,8,2,5,5,9,3,3,1,6,3,1,5,2,0,4,2,2,5,4,3,4,6,7,3,4,5,1,5,7,2],[1,7,7,6,3,4,1,8,4,3,9,8,1,5,5,4,7,7,1,8,5,7,6,4,2,6,7,7,1,3,1,7,4,8,5,2,3,9,1,2,8,2,2,0,4,5,6,1,0,4,4,2,4,9,2,4,8,2,5,5,8,2,4,8,9,3,9,1,4,5,5,5,1],[0,1,1,8,9,1,0,1,3,0,5,9,3,4,1,7,1,2,1,7,3,4,2,7,2,9,9,7,4,8,7,4,2,6,7,8,8,4,9,6,5,9,6,3,0,0,0,6,4,0,9,8,1,7,0,9,9,3,7,5,8,9,4,9,9,1,2,7,5,3,2,2,3],[8,8,1,9,4,8,6,7,4,8,7,7,3,1,6,2,6,3,2,8,4,9,3,5,3,7,1,1,3,7,5,6,6,1,9,3,0,6,1,7,5,1,8,1,6,7,1,8,2,2,0,5,1,0,7,6,7,9,3,2,7,8,5,5,2,1,2,3,0,1,5,0,7],[8,1,9,4,4,5,8,3,8,5,2,3,8,4,5,6,5,0,4,0,6,7,5,5,2,7,8,5,2,1,4,9,5,1,3,4,8,7,7,3,8,5,1,5,5,9,3,9,0,0,0,8,0,4,0,5,3,8,5,1,5,0,1,7,1,3,7,4,2,9,5,5,4],[5,3,5,5,4,4,1,5,6,1,7,4,0,7,5,8,0,3,6,7,0,4,4,8,3,2,6,3,8,0,9,8,9,9,3,2,7,6,9,6,3,1,8,8,6,4,9,4,4,2,7,5,0,1,5,0,8,9,4,1,6,9,8,7,0,1,7,3,4,6,1,1,8],[1,9,5,4,1,7,0,6,3,2,1,5,3,1,8,7,5,7,6,6,8,0,3,8,8,2,5,6,7,2,7,8,2,1,5,3,9,3,5,2,2,9,4,7,8,6,7,7,9,8,6,3,0,6,9,7,3,1,9,1,9,1,5,6,3,7,1,0,8,9,9,8,1],[5,8,5,7,7,8,0,7,9,2,0,4,5,8,8,7,8,6,5,4,6,3,4,1,7,2,8,7,4,7,5,2,5,5,9,3,3,7,1,6,5,1,9,5,5,5,6,2,1,3,6,8,1,0,5,2,8,8,9,9,3,0,5,3,3,8,1,4,5,8,3,2,7]]
我的期望结果应该是
[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,3,3,3,4,6,6,8]
我在控制台和自己的本地电脑执行上述代码和上述用例，结果都是上述期望结果。但是正式提交的结果却不是
**屏幕截图**
![image](https://user-images.githubusercontent.com/12205805/144713715-dee18289-1609-48e1-a9b0-0fa198f9edc0.png)
截图里面我的输出没有显示全，是如下：
[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,6,6,8]。这与我的期望结果不符

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
