### ISSUE TITLE
1528 Shuffle String

### ISSUE THREAD

**Issue by LevonK521** [LeetCode-Feedback/LeetCode-Feedback#5463]
#### Your LeetCode username
LevonK521

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This question has an invalid test case in the description.
Input: s = "codeleet", indices = [4,5,6,7,0,2,1,3]
Output: "leetcode"
It has to be  indices = [4,5,6,7,0,1,2,3] to result to "leetcode"

#### Code you used for Submit/Run operation
```
class Solution {
public:
    string restoreString(string s, vector<int>& indices) {
        string m;
        for(int i = 0;i<=indices.size()-1;++i)
        {
            m = m + s[indices[i]];
        }
        return m;
    }
};
```

#### Language used for code
 C++

#### Expected behavior
The output should have been "leetcdoe"

#### Screenshots
![Screenshot (548)](https://user-images.githubusercontent.com/94919449/144748970-991c5a85-7604-4ae4-b173-82b9a5e46d72.png)

#### Additional context
<!-- Add any other additional context about the bug. --
>

**Comment by LC-Sue** [comment]
Hi @LevonK521,
Thank you for reaching out to us, the test case is correct. You can see from the graphic on the left that "codeleet" [4,5,6,7,0,2,13] should return "leetcode" after shuffling. Please feel free to refer to the discuss section of the problem to see how others have optimized their codes!
