### ISSUE TITLE
Typos in https://leetcode.com/problems/design-snake-game/solution/

### ISSUE THREAD

**Issue by vikash-gupta** [LeetCode-Feedback/LeetCode-Feedback#5465]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Please fix the typos and grammatical mistakes in the solution text. It's a premium answer, so deserves a good quality description of the solution.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @vikash-gupta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
