### ISSUE TITLE
Problem Test Case - 49. Group Anagrams

### ISSUE THREAD

**Issue by posthour1** [LeetCode-Feedback/LeetCode-Feedback#5467]
#### Your LeetCode username

posthour

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There appears to be a discrepancy in the test-cases, but I'm not sure. 
In one case: Input ["aaaaaaaaaaab", "abbbbbbbbbbb"] is expected to yield [["aaaaaaaaaaab", "abbbbbbbbbbb"]]
But, in another test case ["dgggggggggg", "ddddddddddg"] is expected to yield [["dgggggggggg"],["ddddddddddg"]]

The above two test cases appear identical in logic, but expect different results. Am I missing something?

#### Code you used for Submit/Run operation

The following code may be buggy depending on the actual desired results for the above test cases. I modified my solution to conform to a failed test case (which didn't appear to adhere to the rules, but I was thrown by the term "typically" in the problem statement).

```
List<List<String>> results = new ArrayList<>();

        //size /  alpha-bitmap => anagrams
        Map<Integer,Map<Integer, List<String>>> res_map = new HashMap<>();

        for(String s : strs) {

            int alpha_bitmap = 0;
            for (int i = 0; i < s.length(); i++) {
                alpha_bitmap |= 1 << (98-(int) s.charAt(i));
            }

            //alpha_bitmap => anagrams
            Map<Integer, List<String>> r = res_map.getOrDefault(s.length(), new HashMap<>());
            res_map.putIfAbsent(s.length(),r);

            List<String> ress = r.getOrDefault(alpha_bitmap, new ArrayList<>());
            r.putIfAbsent(alpha_bitmap, ress);

            ress.add(s);

        }

        for(var r : res_map.values()) {
            for (var e : r.values()) {
                results.add(e);
            }
        }
        return results;
```

#### Expected behavior

Input ["aaaaaaaaaaab", "abbbbbbbbbbb"] is expected to yield [["aaaaaaaaaaab"],["abbbbbbbbbbb"]]
Input ["dgggggggggg", "ddddddddddg"] is expected to yield [["dgggggggggg"],["ddddddddddg"]]

**Comment by stormsunshine** [comment]
Both test cases return the expected results. Also, the code you submitted is incorrect and fails on the test case: `["ddddddddddg","dgggggggggg"]`.

Please refer to the following screenshot.
![image](https://user-images.githubusercontent.com/12067364/144768494-0019e2f1-985d-407b-8801-40d6fd8751fb.png)

**Comment by posthour1** [comment]
I see I interpreted the failure message incorrectly and started down a rabbit hole of misguided foobar. Sorry about that.
