### ISSUE TITLE
https://leetcode.com/problems/rotting-oranges/

### ISSUE THREAD

**Issue by dmcleish91** [LeetCode-Feedback/LeetCode-Feedback#5468]
#### Your LeetCode username

user5296N

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typo in example

#### Code you used for Submit/Run operation

```
Input: grid = [[2,1,1],[0,1,1],[1,0,1]]
Output: -1
Explanation: The orange in the bottom left corner (row 2, column 0) is never rotten, because rotting only happens 4-directionally.
```

#### Language used for code

Java

**Comment by stormsunshine** [comment]
Which word has typo, and what is the expected content to be displayed?

**Comment by dmcleish91** [comment]
> Which word has typo, and what is the expected content to be displayed?

I misunderstood the example. There is no issue with this content.
