### ISSUE TITLE
Incorrect Expected result in Test Case - 340. Longest Substring with At Most K Distinct Characters

### ISSUE THREAD

**Issue by dpak23** [LeetCode-Feedback/LeetCode-Feedback#5469]
#### Your LeetCode username

dpak23

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Question

#### Description of the bug

For the below two testcases, the expected result should be 0, however the platform expects 2 and 1 respectively. In the first testcase, there is no substring with 2 unique characters in the main string and in the second test case, the main string is smaller than the number of unique characters needed, hence can't have any substring with 2 unique characters. Not sure wh
Testcases:
String: "aa", K: 2
String: "a", K: 2

#### Code you used for Submit/Run operation

```
class Solution {
    public int lengthOfLongestSubstringKDistinct(String str, int uniqueCount) {
        if(uniqueCount == 0) return 0;
        int maxLength = 0;
        int startIndex = 0, endIndex = 0;
        HashMap<Character, Integer> charCountMap = new HashMap<>();
        while(endIndex < str.length()) {
            Character endChar = str.charAt(endIndex);
            if(charCountMap.containsKey(endChar)) {
                charCountMap.put(endChar, charCountMap.get(endChar) + 1);
            } else {
                charCountMap.put(endChar, 1);
            }
            int uniqueCounter = charCountMap.size();
            if(uniqueCounter < uniqueCount) {
                endIndex++;
                continue;
            }
            if(uniqueCounter == uniqueCount) {
                maxLength = Math.max(endIndex - startIndex + 1, maxLength);
                endIndex++;
                continue;
            }
            while (uniqueCounter > uniqueCount) {
                Character startChar = str.charAt(startIndex);
                startIndex++;
                if(charCountMap.containsKey(endChar)) {
                    charCountMap.put(startChar, charCountMap.get(startChar) - 1);
                    if (charCountMap.get(startChar) == 0) {
                        charCountMap.remove(startChar);
                        uniqueCounter = charCountMap.size();
                    }
                }
            }
            endIndex++;
        }
        return maxLength;
    }
}
```

#### Language used for code

Java

#### Expected behavior

For the aforementioned two testcases, the expected behavior should be 0

#### Screenshots

![image](https://user-images.githubusercontent.com/25970067/144777078-f7ead6b6-5440-4cfe-a422-ec6496aa1b36.png)
![image](https://user-images.githubusercontent.com/25970067/144777166-119f4a3a-5c05-4ec9-88ab-aac884a66e89.png)

**Comment by stormsunshine** [comment]
Don't you see the words "at most"? The substring can have k distinct characters at most, which does not require that the substring must have exactly k distinct characters. In the case that k = 2, the substring that has one distinct character also meets the requirement.

**Comment by dpak23** [comment]
Thanks @stormsunshine. It makes sense. Quite clearly I didn't see "at most".
