### ISSUE TITLE
test case error:about 701. 二叉搜索树中的插入操作

### ISSUE THREAD

**Issue by yc-alex-xu** [LeetCode-Feedback/LeetCode-Feedback#547]
** Bug 类型**
- [ ] 题目701. 二叉搜索树中的插入操作
- [ ] 题解
- [ ] 编程语言 go

**描述**
描述你遇到的 bug

**你使用的语言**
go

**你提交或者运行的代码**
/**
 * Definition for a binary tree node.
 * type TreeNode struct {
 *     Val int
 *     Left *TreeNode
 *     Right *TreeNode
 * }
 */
func insertIntoBST(root *TreeNode, val int) *TreeNode {
    if root == nil{
        root := new(TreeNode)
        root.Val = val
    }else if val <root.Val {
        if root.Left != nil{
            root.Left = insertIntoBST(root.Left,val)
        }else{
            node := new(TreeNode)
            node.Val = val
            root.Left = node
        }
    } else{
        if root.Right != nil{
            root.Right = insertIntoBST(root.Right,val)
        }else{
            node := new(TreeNode)
            node.Val = val
            root.Right = node
            return root
        }
    }
    return root
}```

```
输入： [] 5
**期望行为**
[5]

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，建议再仔细调试一下代码。后续反馈题目问题请按照本文格式分享，把问题信息反馈提供完整才能有助于快速验证和精准的定位哦。
