### ISSUE TITLE
Test Case Needs to be Enhanced - 1823. Find the Winner of the Circular Game

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#5470]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
This issue is to reopen #5369.
A user can write either a solution with brute force which has O(n^2) time complexity or a math solution with O(n) time complexity to solve this problem. But I think the O(n^2) solution should not be accepted.
1. This is the second problem of a weekly contest, and the O(n^2) solution is too easy to be marked as "medium". If the brute force can be accepted, the difficulty of this problem cannot reach the average level of the second problem.
2. The solution with O(n) time complexity can be required during a real interview. Please look at this problem,https://leetcode-cn.com/problems/yuan-quan-zhong-zui-hou-sheng-xia-de-shu-zi-lcof/, which can be seen only in LCCN. If you try to use a solution with O(n^2) time complexity to solve this, you will get TLE. In China, if an interviewee uses brute force to solve this problem, he will not get the offer.  
3. The math solution with O(n) time complexity is quite beautiful. I think the quality of this problem is not lower than many typical problems which is neither a problem in weekly contest nor a problem for vip such as 1143, 1206 and 1971. Furthermore, I could see this problem in many puzzle books several years ago.

So I have two suggests:
1. The n and k should be increased to 10^5.
2. At least one test case with n==10^5 should be added.

Code you used for Submit/Run operation

The time complexity of code below is O(n^2)
```
class Solution:
    def findTheWinner(self, n: int, k: int) -> int:

        left = list(range(1,n+1))
        p = 0
        while len(left)>1:
            p+=k-1
            p%=len(left)
            left.pop(p)
            if p==len(left):
                p=0
        return left[0]
```

The time complexity of code below is O(n)
```
class Solution:
    def findTheWinner(self, n: int, k: int) -> int:

        p=0
        for j in range(2,n+1):
            p = (p+k)%j
        return p+1
```

Language used for code
Python3

Expected behavior
1. The n and k should be increased to 10^5.
2. At least one test case with n==10^5 should be added.
The following test case can be added:
10000  3
20000  5
50000  40000
100000  10
100000  1000
100000  100000

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837,
Thank you for your time. Our team believes the current situation of the problem is fine and decided that we are not increasing the constraints of the problem.
