### ISSUE TITLE
Problem statement has incorrect lines

### ISSUE THREAD

**Issue by s-i-d-d-i-s** [LeetCode-Feedback/LeetCode-Feedback#5474]
#### Your LeetCode username
s59_60r

#### Category of the bug
- [ ] Question

#### Description of the bug
In this problem, https://leetcode.com/problems/binary-tree-tilt/

The last line of the statement is `The rule is similar if there the node does not have a right child.`, which is incorrect.

#### Expected behavior
The correct line should be `The rule is similar if the node does not have a right child.`.

#### Screenshots
![Screenshot 2021-12-06 at 6 56 40 PM](https://user-images.githubusercontent.com/68241942/144854055-7cf38038-e241-4711-8a38-380bf1e2c343.png)

**Comment by LC-Sue** [comment]
Hi @s-i-d-d-i-s 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @s-i-d-d-i-s 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
