### ISSUE TITLE
Missing Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by shinuqureshi** [LeetCode-Feedback/LeetCode-Feedback#5475]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
 

int index = 0 ;
          for (int i = 0 ; i< arr.length ; i++)
          {
               index = arr[i] ;
               for(int j = i+1 ; j< arr.length ; j++)
               {
                    if ( index == arr[j] * 2 || index == arr[j]/2)
                    {
                        return  true ;
                    }
                   /*  else if (index!= arr[j] *2 || index != arr[j]/2)
                    {
                         return  false ;
                    }*/
               }

          }

           return false ;

 This is my solution but for second test case it's saying wrong ans 
 input   [3,1,7,11]

**Comment by LC-Sue** [comment]
Hi @shinuqureshi,
Thank you for reaching out to us. The test cases for this problem are correct. Please feel free to refer to the discuss section of the problem to see how others have optimized their codes!
