### ISSUE TITLE
LeetCode Quiz: Multiple Choice Question using radio button

### ISSUE THREAD

**Issue by BingqianShan** [LeetCode-Feedback/LeetCode-Feedback#5476]
In LeetCode Quiz, the questions with "Multiple Choice Question" tag is using radio button. The radio button means "Single Choice Question".

**Comment by stormsunshine** [comment]
Please refer to #5438 . The term "multiple choice" is always used for choices. Here "multiple" means that there are multiple items that can be selected, not that there are multiple correct items. There is no such a term called "single choice".

**Comment by LC-Sue** [comment]
Hi @BingqianShan,
Thank you for reaching out to us, stormsunshine is correct in this case. "multiple" means that there are multiple items that can be selected, not that there are multiple correct items.
