### ISSUE TITLE
Missing Test Case - 863. All Nodes Distance K in Binary Tree

### ISSUE THREAD

**Issue by perryvegehan** [LeetCode-Feedback/LeetCode-Feedback#5479]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case? Don't create meaningless issues!

**Comment by LC-Sue** [comment]
Hi @perryvegehan 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
