### ISSUE TITLE
Missing Test Case - 1290. Convert Binary Number in a Linked List to Integer

### ISSUE THREAD

**Issue by MoSalah001** [LeetCode-Feedback/LeetCode-Feedback#5480]
#### Your LeetCode username

MoSalah001

#### Category of the bug
- [ a ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think there is an error in this challenge as I wrote my code in VS code and it worked just fine but when I run it in leetcode it output a wrong and different result

#### Code you used for Submit/Run operation

```
var getDecimalValue = function(head) {
    let decimalNum;
    for(let i=0; i<head.length;i++){
        decimalNum += head[i]*2**i
    }
    return decimalNum
};
```

#### Language used for code

Javascript

#### Expected behavior

the code should run and work just fine

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
