### ISSUE TITLE
Missing Test Case - 796. Rotate String

### ISSUE THREAD

**Issue by kohler172** [LeetCode-Feedback/LeetCode-Feedback#5481]
#### Your LeetCode username

sleepy_jack_the_fire_drill

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug

Missing test case.

The attached code has a bug in the nested loop and yet it passes all tests for submission.  The bug causes the code to return a false positive for inputs where the rotated word 'begins' near the end of the string and wraps around.

An example test case to demonstrate the bug is: "xjab", "abcd".  

#### Code you used for Submit/Run operation

```
	public boolean rotateString(String s, String goal) {
		int len = goal.length();
		if (s.length() != len) return false;
		char start = goal.charAt(0);

		outer: 
                for (int i = 0; i < len; i++) {
			if (s.charAt(i) != start) continue;
			for (int j = i; j < len; j++) {
				if (s.charAt(j % len) != goal.charAt((j - i) % len)) {
					continue outer;
				}
			}
			return true;
		}

		return false;
	}
```

#### Language used for code

Java

#### Expected behavior

Code fails to pass aforementioned test case but passes submission.

**Comment by LC-Sue** [comment]
Hi @kohler172 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kohler172 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
