### ISSUE TITLE
Another optimised solution O(MN) Time and O(N) Space

### ISSUE THREAD

**Issue by samuelvara** [LeetCode-Feedback/LeetCode-Feedback#5482]
#### Your LeetCode username

eastwoodsamuel4

#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

O(MN) Time and O(N) Space

#### Code you used for Submit/Run operation

```
class Solution:
    def uniquePaths(self, m: int, n: int) -> int:
        dp = [1 for x in range(n)]
        
        for i in range(1, m):
            for j in range(1, n):
                dp[j] = dp[j-1] + dp[j]
        return dp[-1]
```

#### Language used for code

Python

**Comment by LC-Sue** [comment]
Hi @samuelvara,
Thank you for reaching out to us, since the content you provided is not an issue, I will go ahead and close this issue, hope you understand! Please feel free to share your code in the discuss section of the problem!
