### ISSUE TITLE
前端页面bug

### ISSUE THREAD

**Issue by yyegz** [LeetCode-Feedback/LeetCode-Feedback#5486]
**你的 LeetCode 用户名**
KeepTwoDogs

**Bug 类型**
前端页面BUG

**描述**
这个页面一直在生成    思路logo ，详情见我的截图

**期望行为**
能不能不要一直生成这个思路图标呀？什么bug？看的我很烦

**屏幕截图**
![image](https://user-images.githubusercontent.com/73008423/145188340-76d3c19d-051b-4da1-967b-9a8624f8a76d.png)
![image](https://user-images.githubusercontent.com/73008423/145188414-53eece61-8191-4986-b543-22502700d28c.png)
![image](https://user-images.githubusercontent.com/73008423/145188763-0f765dab-0588-41ee-90bb-1d5d3e407a04.png)

**Comment by feiceh** [comment]
@yyegz Hello～我们已经收到你的反馈，建议尝试清空一下 cookie 缓存，换个浏览器、切换4G网再试试。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，目前我们会暂时关闭该 issue，如有更多反馈和建议欢迎  [点击这里](https://support.leetcode-cn.com/hc/request/new/) 在工单附件上传完整的页面问题录屏，在收到回复后，我们会提交至相关部门进行核实并进行后续跟进。
