### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by cjk1234** [LeetCode-Feedback/LeetCode-Feedback#5488]
class Solution:
    def reverse(self, x):
        y = int(x)
        x = abs(y)
        if(y == 0):
            return 0
        else:
            length = len(str(x))
            List = []
            for i in range(length):
                List.append(pow(10,i))
            List.reverse()
            result = []
            for i in range(length):
                if((x//List[i] == 0) and (result == [])):
                    x=x%List[i]
                else:
                    result.append(x//List[i])
                    x=x%List[i]
            result.reverse()
            R=int(str(result).replace('[','').replace(']','').replace(',','').replace(' ',''))
            if(R > pow(2,31)):
                return 0
            else:
                if(y>0):
                    return R
                else:
                    return (0-R)

**Comment by LC-Sue** [comment]
Hi @cjk1234 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
