### ISSUE TITLE
`Minimum Size Subarray Sum`: Incorrect condition during test execution

### ISSUE THREAD

**Issue by general-CbIC** [LeetCode-Feedback/LeetCode-Feedback#5489]
#### Your LeetCode username
CbIC

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The problem manifests itself when solving the problem [Minimum Size Subarray Sum](https://leetcode.com/explore/learn/card/array-and-string/205/array-two-pointer-technique/1299/). One of test cases expects not correct answer.

With `target = 11` and `nums = [1, 2, 3, 4, 5]` system expects answer `3`. Seems like there is error in `target` and it must be `12`.

#### Code you used for Submit/Run operation

```elixir
defmodule Solution do
  @spec min_sub_array_len(target :: integer, nums :: [integer]) :: integer
  def min_sub_array_len(target, nums) do
    nums
    |> find_all_combinations(target)
    |> Stream.filter(&(not is_nil(&1)))
    |> Stream.map(&Enum.count/1)
    |> Enum.min(fn -> 0 end)
  end

  defp find_all_combinations(nums, target) do
    nums_array = :array.from_list(nums)

    for i <- 0..(:array.size(nums_array) - 1) do
      get_combination(nums_array, i, target)
    end
  end

  defp get_combination(nums_array, index, target, sum \\ 0, result \\ []) do
    num = :array.get(index, nums_array)

    cond do
      num == :undefined -> nil
      num + sum > target -> nil
      num + sum == target -> [num | result]
      true -> get_combination(nums_array, index + 1, target, num + sum, [num | result])
    end
  end
end
```

#### Language used for code
Elixir

#### Expected behavior
All tests were expected to work correctly.

#### Screenshots

<img width="932" alt="Снимок экрана 2021-12-08 в 20 39 11" src="https://user-images.githubusercontent.com/13352583/145218052-3a462237-a252-4a3d-8a48-0396f0cc20e9.png">

**Comment by stormsunshine** [comment]
Obviously you do not understand the problem description correctly. The problem requires returning the minimal length of such a contiguous subarray, not the minimum sum.

**Comment by general-CbIC** [comment]
@stormsunshine thanks for the answer!

My program returns length, not sum.

I found where I missed the wording:

_return the minimal length of a contiguous subarray `[numsl, numsl+1, ..., numsr-1, numsr]` of which **the sum is greater than or equal** to target_

For some reason I saw only "equal" 😬

**Comment by bradacina** [comment]
+1 for seeing only equal, not great than or equal
