### ISSUE TITLE
386. Lexicographical Numbers – bad punctuation

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#549]
#### Your LeetCode username
metricquant

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The question statement has bad punctuation:

* Given an integer n, return 1 - n in lexicographical order. --> Given an integer `n`, return `1`–`n` in lexicographical order.

The hyphen - should be replaced with an n-dash –. (https://www.thepunctuationguide.com/en-dash.html)

**Comment by lc-kate** [comment]
Hi @metricquant ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by lc-kate** [comment]
Hi @metricquant ,
My apoloigies for the mistake. We actually did not adapt this change to the problem due to our current problem standard. Since I made the mistake of rewarding incorrectly, we will not revert this LeetCoins reward. Thank you again for your support.
