### ISSUE TITLE
Missing Test Case - 877. Stone Game

### ISSUE THREAD

**Issue by NishantKumarGupta** [LeetCode-Feedback/LeetCode-Feedback#5490]
#### Your LeetCode username

\_MEWSER_

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Though the question asks the user to compute the winner of the game between Alice(return true) and Bob(return false) when both play optimally, there is no such test case where Bob wins the game which results in the solution being accepted just by returning true.

#### Code you used for Submit/Run operation

```
//Stone Game
class Solution {
public:
    bool stoneGame(vector<int>& piles) {
        return 1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code should fail in a case where Bob wins the game but a test case where Bob wins the game is missing.This results in returning true to pass all test cases and above code to be accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/67021346/145221794-f93b051f-bbf5-454a-9f77-0be944ef00b3.png)

**Comment by stormsunshine** [comment]
Please provide the test case that Bob can win. Otherwise, this issue is meaningless.

In fact, it can be proven that Alice will always win, so returning true is the correct answer.
