### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by srav30** [LeetCode-Feedback/LeetCode-Feedback#5492]
#### Your LeetCode username

srav30

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

There is no test case covering a scenario where the result element of the array is at the last index.
for example : 
Input: nums = [2,11,15,7], target = 9
7 is in the last place with index 3.  This case fails my solution. As there is no such case on leetcode it passes.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int[] twoSum(int[] nums, int target) {
        int result[] = new int[2]; 
        int k;
        int j;
        int i;
       //it should be i<=nums.length-1   - none of the test cases catch this bug
        for(i=0;i<=nums.length;i++){
            for(k = i+1; k<nums.length;k++){                
                if(nums[i] + nums[k] == target)
                {
                 int[] result1 = {i,k};
                 return result1;
                }
            }
            for(j = i-1; j>0 ;j--){
                if(nums[i] + nums[j] == target)
                {
                int[] result2 = {i,j};
                return result2;
                }
            }
                
            }
        
        return null;
    }
};
```

#### Language used for code

I used Java

#### Expected behavior

Expected to fail. Instead it was  a success and solution was accepted.

**Comment by stormsunshine** [comment]
Your code does not fail on the given test case. The reason is that when `i = 0` and `k = 3`, the result `[0, 3]` is already returned, and there are no further steps executed.

**Comment by LC-Sue** [comment]
Hi @srav30,
Thank you for reaching out to us, the test case you provided does not fail on the provided code. Since there is not a missing test case, I will close this issue, thank you for understanding!
