### ISSUE TITLE
Missing Test Case - 564. Find the Closest Palindrome

### ISSUE THREAD

**Issue by dhananjay-dhawale** [LeetCode-Feedback/LeetCode-Feedback#5494]
#### Category of the bug
- [564 ] Question
- [ .] Solution
- [ c++] Language
- [ 17] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case? Don't create meaningless issues!

**Comment by LC-Sue** [comment]
Hi @dhananjay-dhawale 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.

**Comment by dhananjay-dhawale** [comment]
I apologise for mistake from my side. Sorry
