### ISSUE TITLE
Missing Test Cases for #217 Contains Duplicate

### ISSUE THREAD

**Issue by CypressLo** [LeetCode-Feedback/LeetCode-Feedback#5495]
#### Your LeetCode username

CypressLo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code in C can pass all current test cases, and I found there is a flaw in my code.
So I'd like to contribute my test case to library.

#### Code you used for Submit/Run operation

```
bool containsDuplicate(int* nums, int numsSize){
    if (numsSize > pow(10, 5))
        return false;

    // in case of collision
    int hash[numsSize][10], i = 0, idx = 0, j = 0;
    
    memset(hash, -1, sizeof(hash));
    
    for (i = 0; i < numsSize; i++) {
        idx = abs(nums[i]) % numsSize;

        for (j = 0; j < 10; j++) {
            if (hash[idx][j] == -1) {
                hash[idx][j] = nums[i];
                break;
            } else if (hash[idx][j] == nums[i]) {
                return true; 
            }
        }
    }
    
    return false;
}
```

#### Language used for code

C, but I think the language doesn't matter.

#### Expected behavior

The result should be true.

#### Screenshots

![image](https://user-images.githubusercontent.com/7530728/145351736-d10208fd-9860-4f9f-9cd6-9975e7c2383a.png)

#### Additional context

From my screen shot, the test case [-1, 2, 3, -1] should return true, but it failed in my code.
The root cause is that I initial hash array with -1. 
But in current test cases, my code can pass all of them.

**Comment by LC-Sue** [comment]
Hi @CypressLo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @CypressLo,
Thank you for your time, our team has decided not to add the test case. The solution is ok to get AC. The reason is that the solution uses -1 as a special value in the array and whenever the duplicate is -1, it should be WA. However, the user can change the initial value to be -2 and the solution will be AC again, and technically, to fail the solution, we need 2*10^9 test cases which is not feasible.

**Comment by CypressLo** [comment]
Hi @LC-Sue ,
Thanks for your feedback and I understand you and your teams' concern.
Just a question, what is AC and WA?
Thanks a lot, Cypress.

**Comment by LC-Sue** [comment]
Hi @CypressLo,
Thank you for reaching out, my apologies for not being clear. AC stands for accepted and WA stands for wrong answer.

**Comment by CypressLo** [comment]
Hi @LC-Sue ,
Thanks a lot. I am a newbie and thanks for your teaching.
Cypress.
