### ISSUE TITLE
Need Correction in Question: 1749. Maximum Absolute Sum of Any Subarray

### ISSUE THREAD

**Issue by JagjiwanChimkar** [LeetCode-Feedback/LeetCode-Feedback#5497]
#### Your LeetCode username

jagjiwanchimkar333

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Screenshots

<img width="430" alt="image" src="https://user-images.githubusercontent.com/59138210/145400192-7ab63178-8673-4b41-95cb-5548541bbc98.png">

#### Description of the bug

Need Correction in question as I underlined the wrong statement in the screenshot.

#### Expected behavior

It's must be **abs(-x)=x**

**Comment by Meowzz95** [comment]
let x be -1
abs(-1) = 1 where 1 = -(-1) = -x

I think the original description is correct.

**Comment by JagjiwanChimkar** [comment]
Ok, Got it.

**Comment by LC-Sue** [comment]
Hi @JagjiwanChimkar,
Thank you for reaching out to us, the description is correct! We appreciate your feedback.
