### ISSUE TITLE
285. Inorder Successor in BST - typo in solution

### ISSUE THREAD

**Issue by Meowzz95** [LeetCode-Feedback/LeetCode-Feedback#5499]
#### Your LeetCode username
jjzzzmd

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

(see the blue box)
I think it should be "8<9" as p.val is 8
![image](https://user-images.githubusercontent.com/22430379/145403954-518c81d3-8a27-43c1-8b3f-7ca513d2ec4a.png)

**Comment by LC-Sue** [comment]
Hi @Meowzz95 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Meowzz95 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
