### ISSUE TITLE
621. Task Scheduler missing a test case

### ISSUE THREAD

**Issue by armeria-program** [LeetCode-Feedback/LeetCode-Feedback#55]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**

621. Task Scheduler

https://leetcode.com/problems/task-scheduler/

missing a test case like:

["A","A","A","A","A","A","B","C","D","E","F","G"]
1

**what language is your code written in**
C++，Java，Python3

**The code you submit/run**

wrong code which can pass tests currently but can't pass the test case above
```c++ []
class Solution {
public:
    int leastInterval(vector<char>& tasks, int n) {
        int tasksSize = tasks.size();
        int charNum = 26;
        vector<int> cnt(charNum, 0);
        for (int i = 0; i < tasksSize; i++) {
            cnt[tasks[i] - 'A']++;
        }
        sort(cnt.begin(), cnt.end(), greater<int>());
        int res = 0;
        int maxCnt = cnt[0];
        if (tasksSize <= maxCnt * (n + 1)) {     // wrong here, should remove equal =
            res = (maxCnt - 1) * (n + 1) + 1;
            for (int idx = 1; idx < charNum && idx <= n && cnt[idx] == maxCnt; idx++) {
                res++;
            }
        } else {
            res = tasksSize;
        }
        return res;
    }
};
```

right code which can pass tests currently and pass the test case above
```c++ []
class Solution {
public:
    int leastInterval(vector<char>& tasks, int n) {
        int tasksSize = tasks.size();
        int charNum = 26;
        vector<int> cnt(charNum, 0);
        for (int i = 0; i < tasksSize; i++) {
            cnt[tasks[i] - 'A']++;
        }
        sort(cnt.begin(), cnt.end(), greater<int>());
        int res = 0;
        int maxCnt = cnt[0];
        if (tasksSize < maxCnt * (n + 1)) {     // corrected
            res = (maxCnt - 1) * (n + 1) + 1;
            for (int idx = 1; idx < charNum && idx <= n && cnt[idx] == maxCnt; idx++) {
                res++;
            }
        } else {
            res = tasksSize;
        }
        return res;
    }
};
```

**Expected behavior**
Add the missed test case

**Screenshots**

**Additional context**

same problem on leetcode-cn

https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/54

**Comment by CooperCooperCooper** [comment]
Hi @armeria-program,
Thank you for reaching out to us. I've relayed this information to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @armeria-program,
Thanks to your timely feedback, we've now added several test cases to this problem (including the one you've mentioned). Please try out the problem again.

**Comment by armeria-program** [comment]
Thanks a lot for your work!

By try the problem again with your new test cases, I found my previous solution was also wrong. It can't pass the test case:

["A","B","C","D","A","B","V"]
3

the correct code should be:

class Solution {
public:
    int leastInterval(vector<char>& tasks, int n) {
        int tasksSize = tasks.size();
        int charNum = 26;
        vector<int> cnt(charNum, 0);
        for (int i = 0; i < tasksSize; i++) {
            cnt[tasks[i] - 'A']++;
        }
        sort(cnt.begin(), cnt.end(), greater<int>());
        int res = 0;
        int maxCnt = cnt[0];
        res = (maxCnt - 1) * (n + 1) + 1;
        for (int idx = 1; idx < charNum && idx <= n && cnt[idx] == maxCnt; idx++) {
            res++;
        }
        return max(res, tasksSize);
    }
};
