### ISSUE TITLE
"1405.Longest Happy String" is missing

### ISSUE THREAD

**Issue by kaiwensun** [LeetCode-Feedback/LeetCode-Feedback#5501]
#### Your LeetCode username
N/A

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question number 1405 https://leetcode.com/problems/longest-happy-string/ is missing. Please bring it back.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

N/A

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Sue** [comment]
Hi @kaiwensun,
Thank you for reaching out to us, the problem is currently being updated, unfortunately I don't know when the problem will be up again. I apologize for the inconvenience!

**Comment by kaiwensun** [comment]
Then I believe this issue should be kept open until it is fixed.

**Comment by kaiwensun** [comment]
This question `DD-2020006. 简单游戏` with slug id `1zD30O` that was once released in leetcode.cn is also missing.
