### ISSUE TITLE
Missing Test Case - 1156. Swap For Longest Repeated Character Substring

### ISSUE THREAD

**Issue by garvgarg100** [LeetCode-Feedback/LeetCode-Feedback#5502]
#### Your LeetCode username

garvgarg100

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ True] Missing Test Cases 
MISSING TEST CASE

#### Description of the bug

I SUBMITED A CODE AND GOT ACCEPTED, BUT KNOWS A TEST CASE ON WHICH MY CODE IS GIVING WRONG OUTPUT.
THE TEST CASE IS ("bbaaaabbccbb"). MY CODE OUTPUT IS 5, BUT THE CORRECT OUTPUT IS 4.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maxRepOpt1(string s) {
        int n=s.size();
        int sum[26]={0};
        for(int i=0; i<n; ++i)
        {
            ++sum[s[i]-'a'];
        }
        int counter=0;
        unordered_map<char,int> mp;
        int ans=0;
        for(int i=0, j=0; i<n; ++i)
        {
            ++mp[s[i]];
            if(mp[s[i]]==2)
            {
                ++counter;
            }
            while(counter>1 || mp.size()>2)
            {
                --mp[s[j]];
                if(mp[s[j]]==1)
                {
                    --counter;
                }
                else if(mp[s[j]]==0)
                {
                    mp.erase(s[j]);
                }
                ++j;
            }
            
            int temp;
            temp=max(sum[s[i]-'a'],sum[s[j]-'a']);
            temp=min(temp,i-j+1);
            
            ans=max(ans,temp);
        }
        return ans;
    }
};

```

#### Language used for code

C++

#### Expected behavior

for the test case ("bbaaaabbccbb") the answer should be 4, but I am getting 5, and my code get accepted.

**Comment by LC-Sue** [comment]
Hi @garvgarg100 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @garvgarg100 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
