### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Kamjam31xx** [LeetCode-Feedback/LeetCode-Feedback#5504]
#### Your LeetCode username

Kamjam31xx

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

using unsigned ints to compare (a + b = c) managed to get through all of your test cases

#### Code you used for Submit/Run operation

```
// Two Sum
#include <cstdint>
class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        uint_fast64_t max_i = uint_fast64_t(nums.size()) - 1;
        uint_fast64_t max_j = max_i + 1;
        std::vector<int> answer;
        
        for (uint_fast64_t i = 0 ; i < max_i ; i++) {
            uint_fast64_t nums_i = uint_fast64_t(nums[i]);
            for (uint_fast64_t j = i + 1 ; j < max_j ; j++) {
                if(nums_i + uint_fast64_t(nums[j]) == uint_fast64_t(target)){
                    answer.push_back(int(i));
                    answer.push_back(int(j));
                    return answer;
                }
            }
        }
        return answer;
    }
};
```

#### Language used for code

c++

#### Expected behavior

there is no signs on the numbers being compared or added. so adding a positive and a negative number shouldnt have the same behavior and pass all test cases comparing to the target number. Unless im dumb, then idk. It passes all of your test cases though. :)

#### Screenshots

![image](https://user-images.githubusercontent.com/78537125/145495329-db17c8be-b124-4647-bbc1-7e6009928104.png)

![image](https://user-images.githubusercontent.com/78537125/145495376-e9b62b1b-4c02-4faf-bd23-8bcd1650157c.png)

**Comment by LC-Sue** [comment]
Hi @Kamjam31xx,
Thank you for reaching out. Since there is no missing test case, I will close this issue. Thank you for understanding!
