### ISSUE TITLE
A Follow-up Can Be Added - 1588. Sum of All Odd Length Subarrays

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#5505]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
As the first problem in weekly contest, the O(n^2) solution can be accepted. But there is a nice math solution with O(n) time complexity, and I think this solution is worth knowing. The problem 2063. Vowels of All Substrings can be solved with an algorithm which is very similar to this problem. So, it is possible that the O(n) solution can be required during a real interview.
The constraints of arr.length should not be changed, otherwise the problem will be unfriendly to users who uses virtual contest. Only a **follow-up** requirement should be added:
Can you solve this problem in O(n) time complexity?

Code you used for Submit/Run operation

The time complexity of the code below is O(n^2)
```
class Solution:
    def sumOddLengthSubarrays(self, arr: List[int]) -> int:
        sum = 0
        n = len(arr)
        prefixSums = [0] * (n + 1)
        for i, v in enumerate(arr):
            prefixSums[i + 1] = prefixSums[i] + v
        for start in range(n):
            length = 1
            while start + length <= n:
                end = start + length - 1
                sum += prefixSums[end + 1] - prefixSums[start]
                length += 2
        return sum
```

The time complexity of the code below is O(n)
```
class Solution:
    def sumOddLengthSubarrays(self, arr: List[int]) -> int:
        s = 0
        for j in range(len(arr)):
            leftall = j
            rightall = len(arr)-j-1
            lefte = leftall//2+1
            righte = rightall//2+1
            lefto = (leftall+1)//2
            righto = (rightall+1)//2
            s +=arr[j]*(lefte*righte+lefto*righto)
        return s
```

Language used for code
Python3

Expected behavior
A **Follow-up** requirement should be added:
Can you solve this problem in O(n) time complexity?

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837,
Thank you for your time. The o(n) requires advanced counting techniques. The top-voted solution already mentioned it.
We decided not to add a follow-up as it is out of the scope.
