### ISSUE TITLE
https://leetcode.com/problems/longest-nice-substring/

### ISSUE THREAD

**Issue by vikash-gupta** [LeetCode-Feedback/LeetCode-Feedback#5507]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Question is tagged with Sliding Window, but the hint is about brute force. Sliding Window doesn't do brute force. Thus the tags on the question and hint don't match.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @vikash-gupta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @vikash-gupta,
Thank you for your time. There are multiple ways to solve the problem. The hints mentioned the easiest solution. The bruteforce is enough to pass the problem. The sliding window also solves the problem but the solution is not mentioned in the hints. It will be added to the official solution when it gets published.
