### ISSUE TITLE
Linked list complexities in the Summary

### ISSUE THREAD

**Issue by lpapp** [LeetCode-Feedback/LeetCode-Feedback#5508]
#### Your LeetCode username
lpapp

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- Something else, explanation

#### Description of the bug
The complexity table here looks wrong at first: https://leetcode.com/explore/learn/card/linked-list/213/conclusion/1230/
                                       Singly     Doubly
Add | after last node |     O(N)  |     O(1)  |

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior

The documentation could be improved if it implies a "last" reference or pointer in the doubly linked list.

If that is not the case, it is a bug and they should be consistent, either O(N) or O(1)

Especially since this does not mention a last reference or pointer for doubly: https://leetcode.com/explore/learn/card/linked-list/210/doubly-linked-list/1291/ - only a prev. And that prev does not make a difference in this regard.

#### Screenshots

N/A

#### Additional context
N/A

**Comment by LC-Sue** [comment]
Hi @lpapp 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @lpapp,
Thank you for your time, a note has been added to address the issue you raised. Thank you for your support!
