### ISSUE TITLE
62. Unique Paths - Different output in test run and submittion for same test case

### ISSUE THREAD

**Issue by sanchit203** [LeetCode-Feedback/LeetCode-Feedback#5509]
#### Your LeetCode username

sanchitmunjal203

#### Category of the bug
- [ ] Solution

#### Description of the bug

Test run accepted the code for a test case (3,2) but at the time of submittion it is showing wrong answer for same test case and code.

#### Code you used for Submit/Run operation

```
// Unique Paths
class Solution {
public:
    int uniquePaths(int m, int n) {
        static int path =0;
        if(m==1 && n==1)
        {
            path++;
            return path;
        }
        else if(m==0||n==0)
            return 0;
        uniquePaths(m-1, n);
        uniquePaths(m, n-1);
        return path;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Compiler should not have shown wrong answer at the time of submittion while it is accepting the code at the time of test run for same test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/70449847/145622923-3470c191-6034-49a8-a5aa-40f1d49b6ed4.png)

**Comment by LC-Sue** [comment]
Hi @sanchit203 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
