### ISSUE TITLE
Missing test case: [1494. Parallel Courses II]

### ISSUE THREAD

**Issue by sekhar179** [LeetCode-Feedback/LeetCode-Feedback#551]
#### Your LeetCode username

sekhar179

#### Category of the bug
- [v ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

This problem is missing a test case, so a solution without handling the corner case is accepted.
For the input:
4
[[2,1],[4,1]]
2
the output should be 2, but it accepts a solution which produces output 3

#### Code you used for Submit/Run operation

```
//Parallel Courses II
class Solution {
public:
    int minNumberOfSemesters(int n, vector<vector<int>>& deps, int k) {
        if (deps.size() == 0)
            return n%k ? n/k+1 : n/k;
        unordered_map<int, vector<int>> mp;
        vector<int> deg(n+1, 0);
        for (auto dep: deps) {
            mp[dep[0]].push_back(dep[1]);
            deg[dep[1]]++;
        }
        queue<int> Q;
        for (int i = 1; i <= n; i++)
            if (deg[i] == 0)
                Q.push(i);
        
        int res = 0;
        while (!Q.empty()) {
            res++;
            queue<int> tmp;
            for (int i = 0; i < k; i++) {
                if (Q.empty())
                    break;
                int node = Q.front();
                Q.pop();
                sort(mp[node].begin(), mp[node].end(), ::greater<int>());
                for (int num: mp[node]) {
                    deg[num]--;
                    if (deg[num] == 0)
                        tmp.push(num);
                }
            }
            while (!tmp.empty()) {
                Q.push(tmp.front());
                tmp.pop();
            }
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input:
4
[[2,1],[4,1]]
2
Output: 3
Expected: 2

**Comment by lc-kate** [comment]
Hi @sekhar179 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @sekhar179 ,
Thank you for your time. After a thorough review, we found we've added another test case previously that would have failed this solution. We appreciate your support.
