### ISSUE TITLE
Incorrect problem statement - the problem1201. Ugly Number III

### ISSUE THREAD

**Issue by kryuki** [LeetCode-Feedback/LeetCode-Feedback#5510]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the problem, `An ugly number is a positive integer that is divisible by a, b, or c.` should be `An ugly number is a positive integer that is **not** divisible by a, b, or c.`? 

#### Screenshots

![ugly](https://user-images.githubusercontent.com/36336987/145659168-49bdd043-5f30-4964-978d-120b8acfc3f8.jpg)

**Comment by stormsunshine** [comment]
Why do you think "not" should be added? Please refer to the examples. An ugly number is divisible by at least one of the integers `a`, `b` or `c`.

**Comment by kryuki** [comment]
Oh...I am sorry. You're right. I think I misunderstood the problem. Sorry about that!
