### ISSUE TITLE
Test Case Missing - 911. Online Election

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5511]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A solution that gets accepted fails on one of the test cases. The test case is as follows.

```
["TopVotedCandidate","q","q","q","q","q","q"]
[[[0,1,1,0,0,1,0],[0,5,10,15,20,25,1000000000]],[3],[12],[25],[15],[24],[8]]
```

Since each `time[i]` can have maximum value 10<sup>9</sup>, creating an array with length equal to `times[times.length - 1] + 1` may cause Memory Limit Exceeded, since the memory does not allow creating an array with length 10<sup>9</sup> + 1.

Obviously, such test cases are missing, so I am providing a test case in such condition.

#### Code you used for Submit/Run operation

```
class TopVotedCandidate {
    int[] res;
    public TopVotedCandidate(int[] persons, int[] times) {
        int len=times[times.length-1];
        res=new int[len+1];
        int []per=new int[persons.length];
        int maxperson=0;
        for(int i=0;i<times.length-1;i++){
            per[persons[i]]++;
            if(per[persons[i]]>=per[maxperson]){
                maxperson=persons[i];
            }
            res[times[i]]=maxperson;
            for(int t=times[i]+1;t<times[i+1];t++){
                res[t]=maxperson;
            }
        }
        per[persons[times.length-1]]++;
        if(per[persons[times.length-1]]>=per[maxperson]){
            maxperson=persons[times.length-1];
        }
        res[times[times.length-1]]=maxperson;
    }
    
    public int q(int t) {
        return t>=res.length?res[res.length-1]:res[t];
    }
}
```

#### Language used for code
Java

#### Expected behavior
The test case above should be added and the solution above should get Memory Limit Exceed when submitted.

#### Screenshots
The following screenshot is from submission using the code above.

![image](https://user-images.githubusercontent.com/12067364/145662542-c049d071-ac80-4bc5-b29d-089f35a76915.png)

The following screenshot is from running the test case above using the code above.

![image](https://user-images.githubusercontent.com/12067364/145662560-179318f8-0e5d-4bcd-bfcc-fd9a3988f8df.png)

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
