### ISSUE TITLE
Inconsistent definitions - 263. Ugly Number, 264. Ugly Number II, 1201. Ugly Number III

### ISSUE THREAD

**Issue by kryuki** [LeetCode-Feedback/LeetCode-Feedback#5512]
#### Your LeetCode username

ryukikobayashi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I was a bit confused by the definition of "ugly number" in these three problems - 
[263. Ugly Number](https://leetcode.com/problems/ugly-number/), [264. Ugly Number II](https://leetcode.com/problems/ugly-number-ii/), [1201. Ugly Number III](https://leetcode.com/problems/ugly-number-iii/)

According to [GeeksforGeeks](https://www.geeksforgeeks.org/ugly-numbers/), Ugly numbers are numbers whose only prime factors are 2, 3, or 5, so I think the definition for 263 and 264 are good, but in 1201, the definition is different. Although this definition doesn't affect the problem itself, I think it's confusing to use the word in a different meaning just to describe a problem. 

So I suggest you should change the problem description in 1201 a little bit.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
Why do you think the term "ugly number" should have the same definition everywhere? The link of GeeksforGeeks you provided above is only a problem, and the term "ugly number" is only defined in the problem. There is no common definition of "ugly number" that is problem-independent.

Since "ugly number" is only defined in a problem, the term can also have different definitions in different problems.

**Comment by LC-Sue** [comment]
Hi @kryuki 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kryuki,
Thank you for your time. The same term can be used using different definitions and that's ok. What is important is that the term is defined clearly for each problem. Words like beautiful, nice, and ugly can appear in different LC problems but they can have a different meaning in each problem.
