### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by Alekh579** [LeetCode-Feedback/LeetCode-Feedback#5513]
#### Solution of Remove Duplicates from Sorted Array
- [ ] Question-Remove Duplicates from Sorted Array
- [ ] Solution
- [ ] Language-C++
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Remove Duplicates from Sorted Array
class Solution {
public:
    
    int removeDuplicates(vector<int>& nums) {
        int n = nums.size(), dup = 0;
        for(int i=1; i<n; i++)
            if(nums[i] == nums[i-1]) dup++;
        if(n == 0 || n == 1 || dup == 0) return n; 
        int tmp= nums[0];
        for(int i=1; i<n; i++){
            if(tmp == nums[i]){
                nums[i] = INT_MAX;
            } 
            else{
                tmp = nums[i];
            }
        }
        sort(nums.begin(), nums.end());
        return n-dup;
    }
};

```

**Comment by LC-Sue** [comment]
Hi @Alekh579,
Thank you for reaching out, since this is not a missing test case I will close this issue for now. Thank you for understanding. Feel free to share your code in the discuss section of the problem!
