### ISSUE TITLE
Incorrect space complexity - 366. Find Leaves of Binary Tree

### ISSUE THREAD

**Issue by idetinkin** [LeetCode-Feedback/LeetCode-Feedback#5514]
#### Your LeetCode username
detinkin

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the solution in Approach 1: "DFS (Depth-First Search) with sorting" the space complexity specified as O(NlogN), but it should be just O(N)
It is O(N) for `pairs`, O(N) for `solution` and O(h) for recursion, where N - total number of nodes, h - height of the tree, and h <= N. Therefore total space complexity is O(N) + O(N) + O(h) = O(N)

**Comment by LC-Sue** [comment]
Hi @idetinkin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @idetinkin 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
