### ISSUE TITLE
Suggest Adding a New Question Based On Bulls and Cows

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5515]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem [299. Bulls and Cows](https://leetcode.com/problems/bulls-and-cows) requires providing a hint for the game Bulls and Cows, which is quite simple. A new question based on Bulls and Cows can be created as follows.

The new problem should be an interactive problem where the length of `secret` is always 4 and the digits in `secret` must be all different. In each turn, the user guesses the secret by providing a string `guess` and receives a hint in the form "xAyB". A solution is passed if and only if for all test cases (with different values of secret), the secret is solved within 10 turns. The secret is solved if and only if in one turn, the received hint is "4A0B". The guess that receives a hint "4A0B" is also counted as one turn. That is, if 10 turns are used without receiving a hint "4A0B", the solution fails even if the secret can be determined after the 10th turn.

According to Wikipedia: [Bulls and Cows](https://en.wikipedia.org/wiki/Bulls_and_Cows), it is proved that any number can be solved within 9 turns (including the last guess that receives a hint "4A0B"). Therefore, allowing 10 turns should be a reasonable requirement.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for your time.  The problems can be submitted on the contributions page or on the discussion page and the team will see if it is suitable for a contest.
