### ISSUE TITLE
Missing Test Case - 2100. Find Good Days to Rob the Bank

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#5516]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Beow code passes current test cases, but there is a missing test cases.

Example

    [1,2,5,4,4,4,4,4,5,3,1,2,4,3,2,4,8]
    2

#### Code you used for Submit/Run operation

```
var goodDaysToRobBank = function (security, time) {
    let ans = [];

    OUTER: for (let i = time; i + time < security.length; i++) {
        if (ans[ans.length - 1] === i - 1 && security[i] === security[i - 1]) {
            ans.push(i);
            continue;
        }

        for (let k = i - time; k < i; k++)
            if (security[k] < security[k + 1]) {
                continue OUTER;
            }

        for (let k = i; k < i + time; k++)
            if (security[k] > security[k + 1]) {
                continue OUTER;
            }

        ans.push(i);
    }

    return ans;
};
```

#### Language used for code
JavaScript

#### Expected behavior
Run code & Submit should have same behaviour

#### Screenshots
![image](https://user-images.githubusercontent.com/8236389/145688370-fa2974c1-c814-4955-bb50-3c5d7209203f.png)

**Comment by LC-Sue** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @manoharreddyporeddy,
Thank you for your time, this solution got WA after supporting the test set with additional test cases.
