### ISSUE TITLE
Test case contribution for 311. Sparse Matrix Multiplication

### ISSUE THREAD

**Issue by paragpachpute** [LeetCode-Feedback/LeetCode-Feedback#552]
#### Your LeetCode username
pachpute

#### Category of the bug
- [ ] Question
- [.] Solution
- [ ] Language

#### Description of the bug

It seems like the question has week test cases. My code got accepted however it fails at some of the test cases.

#### Code you used for Submit/Run operation

```
class Solution {
    public int[][] multiply(int[][] A, int[][] B) {
        if (A[0].length == 0 || B[0].length == 0)
            return new int[1][0];
        
        int[][] ans = new int[A.length][B[0].length];
        
        int[] rowSum = new int[A.length];
        int[] colSum = new int[B[0].length];
        
        for (int i = 0; i < A.length; i++) {
            for (int j = 0; j < A[0].length; j++) {
                rowSum[i] += A[i][j];
            }
        }
        
        for (int i = 0; i < B[0].length; i++) {
            for (int j = 0; j < B.length; j++) {
                colSum[i] += B[j][i];
            }
        }
        
        for (int i = 0; i < A.length; i++) {
            for (int j = 0; j < B[0].length; j++) {
                if (rowSum[i] == 0 || colSum[j] == 0) {
                    ans[i][j] = 0;
                    continue;
                }
                
                int sum = 0;
                for (int k = 0; k < A[0].length; k++) {
                    sum += A[i][k] * B[k][j];
                }
                ans[i][j] = sum;
            }
        }
        
        return ans;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

Input:
[[1,0,-1],[-1,0,3]]
[[7,0,0],[0,0,0],[0,0,1]]

My Output:
[[0,0,0],[-7,0,3]]

Expected Output
[[7,0,-1],[-7,0,3]]

**Comment by lc-kate** [comment]
Hi @paragpachpute ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @paragpachpute ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
