### ISSUE TITLE
Multiple questions are missing from list

### ISSUE THREAD

**Issue by kaiwensun** [LeetCode-Feedback/LeetCode-Feedback#5526]
#### Your LeetCode username
N/A

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
[1375. Bulb Switcher III](https://leetcode.com/problems/bulb-switcher-iii/) is missing from question list.

I believe the github issues like this, including https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/5501, should not be closed until the technical problem is resolved.

**Comment by kaiwensun** [comment]
A lot of questions are removed/missing. Can you please provide a complete list of missing questions?

**Comment by kaiwensun** [comment]
1578. Minimum Deletion Cost to Avoid Repeating Letters

**Comment by kaiwensun** [comment]
This question `DD-2020006. 简单游戏` with slug id `1zD30O` that was once released in leetcode.cn is also missing.

**Comment by kaiwensun** [comment]
https://leetcode-cn.com/problems/1zD30O/ is accessible, but not searchable in leetcode.cn question list
https://leetcode-cn.com/problemset/all/?search=DD-2020006.%20%E7%AE%80%E5%8D%95%E6%B8%B8%E6%88%8F

**Comment by LC-Sue** [comment]
Hi @kaiwensun,
Thank you for reaching out to us, the problem is currently being updated, unfortunately I don't know when the problem will be up again. I apologize for the inconvenience!
