### ISSUE TITLE
Test Case Needs to Be Enhanced - 2104. Sum of Subarray Ranges

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#5527]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug

The solution in O(n^2) time complexity can be accepted. But there is a O(n) solution using monotonic stack, and it can be required during an real interview. If an interviewee use brute force to solve this problem, the interviewer will let him leave from the office.
Besides that, the O(n^2) solution is too easy to be marked as "medium" and cannot reach the average level of the second problem.

But the new test case should be added after the rejudging of the 271st weekly contest. Otherwise some users, who is able to write the O(n) solution but writes O(n^2) solution in order to finish the contest as fast as possible, will be rejudged unfairly.

Code you used for Submit/Run operation

The time complexity of the code below is O(n^2):
```
class Solution:
    def subArrayRanges(self, nums: List[int]) -> int:

        ans = 0
        for i in range(len(nums)):
            mx = nums[i]
            mn = nums[i]
            for j in range(i+1,len(nums)):
                mx = max(nums[j],mx)
                mn = min(nums[j],mn)
                ans+=mx-mn
        return ans
```

The time complexity of the code below is O(n):
```
class Solution:
    def subArrayRanges(self, nums: List[int]) -> int:
        n = len(nums)

        minleft, stack = [], []
        for i, num in enumerate(nums):
            while stack and num < nums[stack[-1]]:
                stack.pop()
            minleft.append(-1 if not stack else stack[-1])
            stack.append(i)
        minright, stack = [], []
        for i in range(n-1, -1, -1):
            num = nums[i]
            while stack and num <= nums[stack[-1]]:
                stack.pop()
            minright.append(n if not stack else stack[-1])
            stack.append(i)
        minright = minright[::-1]

        maxleft, stack = [], []
        for i, num in enumerate(nums):
            while stack and num > nums[stack[-1]]:
                stack.pop()
            maxleft.append(-1 if not stack else stack[-1])
            stack.append(i)
        maxright, stack = [], []
        for i in range(n-1, -1, -1):
            num = nums[i]
            while stack and num >= nums[stack[-1]]:
                stack.pop()
            maxright.append(n if not stack else stack[-1])
            stack.append(i)
        maxright = maxright[::-1]

        ans = 0
        for i in range(n):
            ans += nums[i] * ( (i-maxleft[i])*(maxright[i]-i) - (i-minleft[i])*(minright[i]-i) )
        return ans
```

Language used for code
Python3

Expected behavior
1.The constraint of num.length should be increased to 10^5.
2.At least one test case with num.length==10^5 should be added after the rejudging of the 271st weekly contest.

**Comment by stormsunshine** [comment]
Since this is the second problem in weekly contest 271, I don't think the test case and the constraints should be enhanced, otherwise the difficulty is not suitable for the second problem in a weekly contest. Also, if the constraints are changed, the users that use virtual contest for weekly contest 271 will be affected.

Instead, I think the O(n) solution can be added as a follow-up question. A follow-up question can be as follows.

**Follow-up:** Can you find a solution with time complexity `O(nums.length)`?

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837,
Thank you for your time, The current constraints are fine and O(n^2) solution is enough to pass the interview.
The O(n) could appear as a follow-up in the interview. We added a follow-up for the users who want to think about it.
