### ISSUE TITLE
Test Case Contribution for 1497. Check If Array Pairs Are Divisible by k

### ISSUE THREAD

**Issue by sushantPatrikar** [LeetCode-Feedback/LeetCode-Feedback#553]
#### Your LeetCode username
patrikarss

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Please include this test case
```
[1,2,3,4]
10
```
My solution fails at this test case but got accepted during the contest

#### Code you used for Submit/Run operation

```
class Solution:
    def canArrange(self, arr: List[int], k: int) -> bool:
        return sum(arr)%k==0
```

#### Language used for code
Pyhton3

#### Expected behavior
The expected answer is False, but my code gives True

#### Screenshots
![Screenshot (180)](https://user-images.githubusercontent.com/40419750/85938181-6efb1300-b928-11ea-8983-e3806dfd7e1c.png)
![Screenshot (181)](https://user-images.githubusercontent.com/40419750/85938184-73bfc700-b928-11ea-89d9-9d171782b19e.png)

**Comment by tabletenniser** [comment]
+1! The existing test cases are not sufficient, the following is another example that should return False but with the one liner code above returns True
[1,2,3,4,10,14]
17

**Comment by vkoppu9** [comment]
[1,1,1,1,1,1,1,1]
8
this testcase shouldn't pass

**Comment by lc-kate** [comment]
Hi @sushantPatrikar ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @sushantPatrikar ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
