### ISSUE TITLE
Missing Test Case - 1058. Minimize Rounding Error to Meet Target

### ISSUE THREAD

**Issue by MUKUL821** [LeetCode-Feedback/LeetCode-Feedback#5534]
#### Category of the bug
-  Missing Test Cases 

#### Description of the bug

Able to submit the code succesfully but its failing on testcases : 
["0.0","0.1","3.0"]
3

Expected : -1

#### Code you used for Submit/Run operation

```
    int l = prices.length;
        double[] p = new double[l];
        int roudupSum = 0;
        for (int i = 0; i<l; i++) {
            int floor = (int)Math.floor(Double.valueOf(prices[i]));
            p[i] = Double.valueOf(prices[i]) - floor;
            roudupSum += p[i] == 0 ? 0 : 1;
            target -= floor;
        }
        

        if (target < 0 || roudupSum < target) {
            return "-1";
        }
      
        double[][] dp = new double[target + 1][l+1];
    
        for (int i = 1; i<=l; i++) {
            dp[0][i] = dp[0][i-1] + p[i-1];
        }
        
        for (int i = 1; i<=target; i++) {
            for (int j = i; j<=l; j++) {
                
                if(j > i){
                    dp[i][j] = Math.min(dp[i-1][j-1] + 1-p[j-1], dp[i][j-1] + p[j-1]);
                }
                
              
                else if(i == j){
                    dp[i][j] = dp[i-1][j-1]+1-p[j-1];
                }
				
            }
        }
        
        String res = String.format("%.3f", dp[target][l]);
        return res;
}}
```

#### Expected behavior

The output is ""0.100" as per above code and its accepted solution by the leetcode. If ran independently just for this tescase the above solution is failing as expected here is -1.
Either leetcode's expected is wrong or the accepted solution's ans.

**Comment by stormsunshine** [comment]
The test case is incorrect. According to constraints, each string `prices[i]` represents a real number in the range `[0.0, 1000.0]` and has **exactly 3 decimal places**. Therefore, the test case you provide does not meet the constraints. It is meaningless to require changing the expected answer for an incorrect test case.

The following test case is in the correct format and returns the correct answer "0.100".
```
["0.000","0.100","3.000"]
3
```

@LC-Sue However, I suggest that the checker should be added for this problem to make sure that the custom test cases are in the correct format such that each element in `prices` represents a real number in the range `[0.0, 1000.0]` and has exactly 3 decimal places.

**Comment by LC-Sue** [comment]
Hi @MUKUL821 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @MUKUL821 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
