### ISSUE TITLE
Missing Test Case - 1089. Duplicate Zeros

### ISSUE THREAD

**Issue by GiaBaorr** [LeetCode-Feedback/LeetCode-Feedback#5537]
#### Category of the bug
- [ ] Output

#### Description of the bug

The output of my function on website is different from mine when I write it on DevTools.

#### Code you used for Submit/Run operation

```
var duplicateZeros = function(arr) {
    let result = [] ;
    for (let i =0; i < arr.length; i++){
        if(result.length < arr.length) {
            result.push(arr[i])
            if (arr[i] === 0){
                result.push(0)
            }
        }
    }
    return result;
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/92243205/145801059-039608ab-70a3-49ad-beb3-10c04911d206.png)

**Comment by stormsunshine** [comment]
The return type of the function is void, so you should modify the input array directly, not return the result array.

**Comment by stormsunshine** [comment]
The return type of the function is void, so you should modify the input array directly, not return the result array.

**Comment by GiaBaorr** [comment]
> The return type of the function is void, so you should modify the input array directly, not return the result array.

Thanks for your good advice, finally I passed it.
