### ISSUE TITLE
Bug in Judge code - 283. Move Zeroes

### ISSUE THREAD

**Issue by michals** [LeetCode-Feedback/LeetCode-Feedback#5538]
#### Your LeetCode username
trpaslik

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Judge code bug (sorry, I've added this category)

#### Description of the bug
I've found by accident a bug in the judge code test case parser.
if test case is "[00]" (and array with integer 0 with any leading 0s
the Judge code fails with exception:
```
"Line 1619: rapidjson::SizeType rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::Size() const [Encoding = rapidjson::UTF8<char>, Allocator =
    ...: rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]: Assertion `IsArray()' failed. (document.h)"
```
#### Code you used for Submit/Run operation
any code with custom testcase:
```
[00]
```

#### Language used for code
python3

#### Expected behavior
"invalid testcase" message, or treated as valid

**Comment by LC-Sue** [comment]
Hi @michals,
Thank you for reaching out to us, could you please provide the code you used for submission?

**Comment by stormsunshine** [comment]
@LC-Sue The author said that any code can be used. You may just use any code in Python3 that can get accepted to test the scenario.

**Comment by LC-Sue** [comment]
Hi @michals 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
