### ISSUE TITLE
8. String to integer (atoi) - other whitespace chars

### ISSUE THREAD

**Issue by mjcrouch** [LeetCode-Feedback/LeetCode-Feedback#554]
#### Your LeetCode username
Zogger

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The solution states

> Only the space character ' ' is considered as whitespace character.

However, it does not test strings starting with other whitespace characters, e.g.

"\t42" expects result 0 but this is not a test case (at least in javascript / typescript)

#### Code you used for Submit/Run operation

I have deliberately allowed \t to parse as whitespace in the below:

```typescript
function getNumbers(str: string) {
    let reachedNum = false;
    let numbers: number[] = [];
    let isNegative = false;
    let isOutOfRange = false;
    for(let i = 0; i < str.length; ++i) {
        const c = str[i];
        if (c === "+") {
            if (reachedNum) {
                break;
            }
            reachedNum = true;
        } else if (c === "-") {
            if (!reachedNum) {
                isNegative = true;
                reachedNum = true;
            } else {
                break;
            }
        } else if (c >= "0" && c <= "9") {
            reachedNum = true;
            numbers.push(str.charCodeAt(i) - 48);
        } else if (reachedNum || (c !== " " && c != "\t")) {
            break;
        }
    }
    return {numbers, isNegative, isOutOfRange};
}

function myAtoi(str: string): number {
    const MIN_INT = -2147483648;
    const MAX_INT = 2147483647;

    const {numbers, isNegative, isOutOfRange} = getNumbers(str);
    const sign = isNegative ? -1 : 1;
        
    let result = 0;
    numbers.reverse().map((n, p) => {
         result += n * Math.pow(10, p);
    });
    return isNegative ? Math.max(-result,MIN_INT) : Math.min(result, MAX_INT);
};
```

#### Language used for code

TypeScript

(Same with javascript, have not tried any other languages)

#### Expected behavior
The solution should not be accepted because the solution returns 42 instead of 0

**Comment by lc-kate** [comment]
Hi @mjcrouch ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @mjcrouch 
Thank you for your time. Upon investigating this issue, our team decided not to update the problem, since in this problem, we only consider ' ' as the space character so other test cases that have other whitespace characters will be considered as invalid test cases.
