### ISSUE TITLE
Missing Test Case - 125. Valid Palindrome

### ISSUE THREAD

**Issue by ShivanshGupta02** [LeetCode-Feedback/LeetCode-Feedback#5541]
#### Your LeetCode username
codedguy

#### Category of the bug
- [ A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers.

Given a string s, return true if it is a palindrome, or false otherwise. ] Question
- [
 class Solution {
        private: bool isalphabet(char c){
                c=tolower(c);
                return (c>='a' && c<='z');
        }
public:
        
    bool isPalindrome(string s) {
            
      int i=0;int j=s.size()-1;
            while(i<j){
                    
                    if(isalphabet(s[i]) && isalphabet(s[j])){
                            if(tolower(s[i])!=tolower(s[j])) return false;
                            i++;j--;
                    }
                    if(!isalphabet(s[i]))i++;
                    if(!isalphabet(s[j]))j--;
            }
            return true;
    }
};
 ] Solution
- [ C++ ] Language
- [  Testcase -"0P" 
     Leetcode answer- false
     Right answer - true 
   ] Wrong Test Cases 

#### Description of the bug
The wrong test case contains the wrong answer "false" while its answer is "true" because after removing alphanumeric characters from the string "0P", we get "P" which is a palindrome string hence answer must be "true".

#### Code you used for Submit/Run operation

```
// Valid Palindrome
class Solution {
        private: bool isalphabet(char c){
                c=tolower(c);
                return (c>='a' && c<='z');
        }
public:
        
    bool isPalindrome(string s) {
            
      int i=0;int j=s.size()-1;
            while(i<j){
                    
                    if(isalphabet(s[i]) && isalphabet(s[j])){
                            if(tolower(s[i])!=tolower(s[j])) return false;
                            i++;j--;
                    }
                    if(!isalphabet(s[i]))i++;
                    if(!isalphabet(s[j]))j--;
            }
            return true;
    }
};
```

#### Screenshots
![image](https://user-images.githubusercontent.com/90094267/145940958-f1845ac5-ae4f-4c73-bcfe-9f416b7e9657.png)

**Comment by stormsunshine** [comment]
Alphanumeric characters include letters and numbers. Therefore, both "0" and "P" are alphanumeric characters, and thus "0P" is NOT a palindrome.

Please read the problem description carefully.

**Comment by LC-Sue** [comment]
Hi @ShivanshGupta02,
Thank you for reaching out to us, stormsunshine is right in this case. Please feel free to refer to the discuss section of the problem to see how others have optimized their codes!
