### ISSUE TITLE
Missing Test Case - 150. Evaluate Reverse Polish Notation

### ISSUE THREAD

**Issue by grissom1** [LeetCode-Feedback/LeetCode-Feedback#5542]
#### Your LeetCode username
grissom1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation
```
["7"]
```

#### Expected behavior

7

#### Additional context

Missing single element test case for Reverse Polish Notation

**Comment by LC-Sue** [comment]
Hi @grissom1,
Thank you for reaching out to us, could you please provide the code you used for submission?

**Comment by grissom1** [comment]
```
import "strconv"

func evalRPN(tokens []string) int {
    pending := make([]int, 0)
    var result int
    for _, value := range tokens {
        intValue, err := strconv.Atoi(value)
        if err == nil {
            pending = append(pending, intValue)
        } else {
            result = cal(pending[len(pending) - 2], pending[len(pending) - 1], value)
            pending = pending[:len(pending) - 2]
            pending = append(pending, result)
        }
    }
    if len(pending) == 1 {
        return pending[0]
    }
    return result
}

func cal(first, second int, operator string) int {
    switch operator {
    case "+":
        return first + second
    case "-":
        return first - second
    case "*":
        return first * second
    case "/":
        return first / second
    }
    return 0
}
```
I mean, it's better to have a built-in test case for single element input, like, ["7"] and expected output is 7

**Comment by stormsunshine** [comment]
@grissom1 The code you provided can pass the test case ["7"]. Why do you think the test case is missing?

In fact, there already exists a test case ["18"] which is a single element input.

**Comment by grissom1** [comment]
I see. Actually maybe I misunderstood it.

**Comment by LC-Sue** [comment]
Hi @grissom1,
Thank you for your time, I'm glad stormsunshine's response was able to answer your doubts! We appreciate your support!
