### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by benjamimWalker** [LeetCode-Feedback/LeetCode-Feedback#5546]
#### Your LeetCode username

bhaskdelta2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I submitted my solution in PHP >= 7.4. Which has arrow functions `fn($parameter) => $parameter * 2;`, I think the website uses an older version of PHP, so my solution raises an error. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {

    /**
     * @param String[] $strs
     * @return String
     */
    function longestCommonPrefix($strs)
    {
        $l = '';
        for ($i = 0; $i < min(array_map(fn($palavra) => strlen($palavra), $strs)); $i++) {
            $l .= $strs[0][$i];
            foreach ($strs as $p) {
                if ($p[$i] != substr($l, $i)) return substr($l, 0, -1);
            }
        }
        return $l;
    }
}
```

#### Language used for code

PHP 8.1

#### Expected behavior

I expected no errors caused by older versions of PHP.

#### Screenshots

![image](https://user-images.githubusercontent.com/55597702/146061147-40373521-0756-4d27-a0ed-7cf8b9964191.png)

#### Additional context

The PHP version used on the website must be updated. Thank you!

**Comment by LC-Sue** [comment]
Hi @benjamimWalker,
Thank you for reaching out to us, the judger appears to be working correctly. Please feel free to refer to the discuss section of the problem to see how others have optimized their PHP codes!
