### ISSUE TITLE
Python Time Limit Issue - 1769. Minimum Number of Operations to Move All Balls to Each Box

### ISSUE THREAD

**Issue by faiyaz26** [LeetCode-Feedback/LeetCode-Feedback#5548]
#### Your LeetCode username
faiyaz26

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Python time limit for this problem is too low. O(N^2) solution with C++ passes but Python3 gets TLE

#### Code you used for Submit/Run operation

Gets TLE
```
class Solution:
    def minOperations(self, boxes: str) -> List[int]:
        boxes = [int(box) for box in boxes]
        
        ans = [ 0 for box in boxes ]
        
        for idx in range(len(boxes)):
            for j in range(len(boxes)):
                ans[idx] += (boxes[j] * abs(j - idx))
        
        return ans
```
C++ gets accepted
```
class Solution {
public:
    vector<int> minOperations(string boxes) {
        vector <int> bx;
        vector <int> ans;
        for(int i=0;i<boxes.size();i++){
            int val = boxes[i] - '0';
            bx.push_back(val);
            
            ans.push_back(0);
        }
        
        
        for (int idx = 0; idx < boxes.size(); idx++){
            for(int j = 0; j < boxes.size(); j++){
                int absVal = abs(j - idx);
                int vv = bx[j] * absVal;
                ans[idx] += (vv);
            }
        }
        
        return ans;
    }
    
};
```

#### Language used for code
Python3

#### Expected behavior
Should pass all the test case

**Comment by LC-Sue** [comment]
Hi @faiyaz26,
Thank you for reaching out to us. The implementation details of each language are different. We test our problems before publishing them. We set the TL to be 2x the slowest solution we get during the testing.
