### ISSUE TITLE
Bug in solution for Refer Dynamic programming, Example 198. House Robber

### ISSUE THREAD

**Issue by amitjn** [LeetCode-Feedback/LeetCode-Feedback#5549]
Leet Code UserName: amitjn

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

Refer Dynamic programming, Example 198. House Robber, in
Assume, there are 4 houses, and the amount of money available in each house is as follows:
9, 3, 4, 9
So, with given constraints, the max money a robber can have is 18 by robbing the first and last house, but the solution you provided is going to give 13.

**Comment by LC-Sue** [comment]
Hi @amitjn 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @amitjn,
Thank you for your time. Our team tested both solutions in both languages (4 solutions in total) with the counter example and they all return 18. There is no error.
