### ISSUE TITLE
A wrong link in the solution of 143. Reorder List

### ISSUE THREAD

**Issue by jinnyy** [LeetCode-Feedback/LeetCode-Feedback#5551]
#### Your LeetCode username

jinnyy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In [this](https://leetcode.com/problems/reorder-list/solution/) article,
it seems like the third link to another problem doesn't work.

* The address is currently: https://leetcode.com/articles/merged-two-sorted-lists/
* and I found this article: https://leetcode.com/problems/merge-two-sorted-lists/solution/

#### Expected behavior

It would be better if the link is changed with a working url.
I think the correct one maybe [this](https://leetcode.com/problems/merge-two-sorted-lists/solution/) one.

#### Screenshots

![image](https://user-images.githubusercontent.com/26596684/146122522-575c2e0d-45eb-4416-a9b3-06fe59cdcea8.png)

Thanks for considering this issue. 😄

**Comment by LC-Sue** [comment]
Hi @jinnyy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jinnyy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
