### ISSUE TITLE
 Explore - Intro to DP : Example 1770. (because nums is 0-indexed)

### ISSUE THREAD

**Issue by Slyderek** [LeetCode-Feedback/LeetCode-Feedback#5553]
#### Your LeetCode username

creditchoi

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the section, "1. A function or array that answers the problem for a given state", 2nd par, 3rd sentence says, "If we have done, say 3 left operations, if we were to do another left operation we would use nums[3] (**because nums is 0-indexed**)." However, OP statement says "You are given two integer arrays nums and multipliers of size n and m respectively, where n >= m. **The arrays are 1-indexed**. You begin with a score of 0. You want to perform exactly m operations. On the ith operation (1-indexed) ..."

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

nums[4] (because nums is 1-indexed)

**Comment by LC-Sue** [comment]
Hi @Slyderek 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Slyderek,
Thank you for your time. Change will be made in the future to address the issue, but it may be different from your suggestion.
