### ISSUE TITLE
Missing Test Cases - 94. binary-tree-inorder-traversal

### ISSUE THREAD

**Issue by Andrew-Pei** [LeetCode-Feedback/LeetCode-Feedback#5554]
#### Your LeetCode username

andrewpei

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test case is missing a class of cases where the value of the node is 0.

#### Code you used for Submit/Run operation

```
// binary tree inorder traversal
class Solution:
    def inorderTraversal(self, root: TreeNode) -> List[int]:
        res=[]
        if not root:
            return res
        if root.left:
            res.extend(self.inorderTraversal(root.left))
        if root.val:
            res.append(root.val)
        if root.right:
            res.extend(self.inorderTraversal(root.right))
        return res
```

#### Language used for code

Python3

#### Expected behavior

The above code should not pass the submission.
But the code above actually passed the submission.
The code shown above has a problem with the condition statement. Instead of using 'if not root.val:', you should use 'if root.val!=None:'. Because, when the binary tree has a value of 0, the first judgment statement cannot give the correct result.

#### Screenshots

The screenshot below shows an example of what happens when the above code encounters a node value of 0. It ignores the presence of 0.
![image](https://user-images.githubusercontent.com/41012409/146145422-d7344463-f4d5-4d69-b291-5acfa58a3c98.png)

**Comment by LC-Sue** [comment]
Hi @Andrew-Pei,
Thank you for reaching out to us, however, the code you provide does not pass submission, so I will not relay this issue over to the team. I've attached a screenshot for your reference!
![image](https://user-images.githubusercontent.com/92285126/146287861-489b6f20-6e60-4a05-afbd-b36171e019d2.png)

**Comment by Andrew-Pei** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    You should read the error information, you made a syntax error, the code you directly copied from github must have a coding error in the Spaces.Just now I submit my code again and passed the submission. Screenshot as follow：
    
        my code:class Solution:    def inorderTraversal(self, root: TreeNode) -> List[int]:        res=[]        if not root:            return res        if root.left:            res.extend(self.inorderTraversal(root.left))        if root.val:            res.append(root.val)        if root.right:            res.extend(self.inorderTraversal(root.right))        return res
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 12/16/2021 ***@***.***> wrote： 



Hi @Andrew-Pei,
Thank you for reaching out to us, however, the code you provide does not pass submission, so I will not relay this issue over to the team. I've attached a screenshot for your reference!

**Comment by LC-Sue** [comment]
Hi @Andrew-Pei 
Thank you for correcting! I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Andrew-Pei,
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username?

**Comment by Andrew-Pei** [comment]
My username is AndrewPei, phone number is (+86)13772512878.



---Original---
From: ***@***.***&gt;
Date: Sat, Jan 8, 2022 07:41 AM
To: ***@***.***&gt;;
Cc: "Bowen ***@***.******@***.***&gt;;
Subject: Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Cases - 94.binary-tree-inorder-traversal (Issue #5554)




 
Hi @Andrew-Pei,
 Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LC-Sue** [comment]
Hi @Andrew-Pei,
Thank you for responding. However I was unable to locate an account with the username 'AndrewPei'. As an alternative, you can also provide your LeetCode email!

**Comment by Andrew-Pei** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Actually, I registered in leetcode-cn.com, you might not find this on the main site. My email is ***@***.***
    
        
            
        
    
    
        
        

        
    

    On 1/11/2022 ***@***.***> wrote： 



Hi @Andrew-Pei,
Thank you for responding. However I was unable to locate an account with the username 'AndrewPei'. As an alternative, you can also provide your LeetCode email!

**Comment by LC-Sue** [comment]
Hi @Andrew-Pei,
Unfortunately we are unable to reward your LCCN account as it's not within the US system.
