### ISSUE TITLE
Data structure in solution differ from code template.

### ISSUE THREAD

**Issue by Tirex** [LeetCode-Feedback/LeetCode-Feedback#5555]
#### Your LeetCode username
Tirex

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The data structure  used in solution differ from code template for java 

in code template `int maxDistance(List<List<Integer>> arrays)`
in colution  `int maxDistance(int[][] list)` 

https://leetcode.com/problems/maximum-distance-in-arrays/solution/

#### Code you used for Submit/Run operation
not relevant

#### Language used for code
Java

#### Expected behavior
The signature/data structure of code template and solution must be equal (if language of solution the same as code template)

#### Screenshots
not relevant

#### Additional context
not relevant

**Comment by LC-Sue** [comment]
Hi @Tirex 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Tirex 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
