### ISSUE TITLE
Missing Test Case - 1608. Special Array With X Elements Greater Than or Equal X

### ISSUE THREAD

**Issue by siddhantsiddh15** [LeetCode-Feedback/LeetCode-Feedback#5557]
#### Your LeetCode username

siddhantsiddh15

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

This test case shows error if the logic of the code is not correct.

#### Code you used for Submit/Run operation

```
  public int specialArray(int[] nums) {
        
        Arrays.sort(nums);
        
    for(int i = 0; i<101; i++){
        
        int count = nums.length - search(nums, i);
        
        if(count == i)return i;
        
    }    
        
        return -1;
    }
    
    public int search(int[] nums, int target){
        
        int start = 0;
        int end = nums.length-1;
        
        
        while(start<=end){
            
             int mid = start + (end - start)/2;
            if(nums[mid]>= target){
                end = mid-1;
                
            }else{
                start = mid +1;
            }
        }
       return start; 
    }
```

#### Language used for code

Java

**Comment by stormsunshine** [comment]
What is the test case that makes the code fail?

**Comment by LC-Sue** [comment]
Hi @siddhantsiddh15,
Thank you for reaching out to us, could you provide the test case that fails the code?

**Comment by siddhantsiddh15** [comment]
[0,0,1,4,4,4,4]
Sorry for not mentioning the test case. Here it is. 
Initially this test case was causing the code to not pass but later I improved my logic and my code was accepted.
