### ISSUE TITLE
Impossibly hard to use functional languages like Elixir: 1396. Design Underground System

### ISSUE THREAD

**Issue by shivam-tripathi** [LeetCode-Feedback/LeetCode-Feedback#5558]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Broken Solution process for functional languages like Elixir

Functional languages are big on immutability, so it is excessively hard to maintain state local or otherwise. As this process explicitly requires state to be maintained, it is impossible to solve. It will be better to allow for passing of structs references to each method to allow for immutable usage of methods of module.  

#### Code you used for Submit/Run operation

Current invocation process:
```exs
# Your functions will be called as such:
UndergroundSystem.init_()
UndergroundSystem.check_in(id, station_name, t)
UndergroundSystem.check_out(id, station_name, t)
param_3 = UndergroundSystem.get_average_time(start_station, end_station)

# UndergroundSystem.init_ will be called before every test case, in which you can do some necessary initializations.
```

How I think it should be: 
```exs
ug = UndergroundSystem.init_()
ug = UndergroundSystem.check_in(ug, id, station_name, t)
ug = UndergroundSystem.check_out(ug, id, station_name, t)
param_3 = UndergroundSystem.get_average_time(ug, start_station, end_station)

```

#### Language used for code

Elixir

#### Expected behavior

The solution process must pass and update reference to struct everytime it is used, instead of assuming some local or global state.

**Comment by LC-Sue** [comment]
Hi @shivam-tripathi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by shivam-tripathi** [comment]
Found another one:
https://leetcode.com/problems/binary-search-tree-iterator/

**Comment by shivam-tripathi** [comment]
Ok, so while learning more about the language tools, I found a cool way to persist named states using `Agent`, but it's very slow. For example, the following code passes 60/61 testcases and gives TLE for the last test for above mentioned [problem](https://leetcode.com/problems/binary-search-tree-iterator/).

```ex
defmodule BSTIterator do
  @spec init_(root :: TreeNode.t() | nil) :: any
  def init_(root) do
    stack = handle_node(root, [])
    {status, _} = Agent.start_link(fn -> stack end, name: :bst_iterator)

    if status != :ok do
      Agent.update(:bst_iterator, fn _ -> stack end)
    end
  end

  
  defp handle_node(node, stack) do
    if node == nil do
      stack
    else
      handle_node(node.left, [node | stack])
    end
  end

  @spec next() :: integer
  def next() do
    [node | stack] = Agent.get(:bst_iterator, & &1)
    stack = handle_node(node.right, stack)
    Agent.update(:bst_iterator, fn _ -> stack end)
    node.val
  end

  @spec has_next() :: boolean
  def has_next() do
    Agent.get(:bst_iterator, & &1) != []
  end
end
```
