### ISSUE TITLE
the test case is wrong for the question 493. Reverse Pairs

### ISSUE THREAD

**Issue by codeWithUtkarsh** [LeetCode-Feedback/LeetCode-Feedback#5559]
The question says, 
A reverse pair is a pair (i, j) where 0 <= i < j < nums.length and nums[i] > 2 * nums[j].

and there is a test case like this.
![image](https://user-images.githubusercontent.com/29374436/146243826-599b9d01-9199-4656-ba9a-7ca8089ee9ed.png)

**Comment by stormsunshine** [comment]
-5 > 2 * (-5). Is there any problem?

**Comment by LC-Sue** [comment]
Hi @codeWithUtkarsh,
Thank you for reaching out to us, stormsunshine is correct in regards to the test case. Please feel free to refer to the discuss section of the problem to see how others have optimized their codes!
