### ISSUE TITLE
153. 寻找旋转排序数组中的最小值

### ISSUE THREAD

**Issue by CLannadZSY** [LeetCode-Feedback/LeetCode-Feedback#556]
** Bug 类型**
- [ ] 题目
- [x] 题解
- [x] 编程语言

**描述**
153题, [官方题解](https://leetcode-cn.com/problems/find-minimum-in-rotated-sorted-array/solution/xun-zhao-xuan-zhuan-pai-lie-shu-zu-zhong-de-zui-xi/)的`Python`代码有问题

**你使用的语言**
`Python`

**期望行为**
官方题解错误行代码: 
```python
mid = left + (right - left) / 2
```
报错截图
![image](https://user-images.githubusercontent.com/38000492/86009759-2be69000-ba4d-11ea-9fc8-5d483d69ce03.png)

正确代码: 
```python
mid = left + (right - left) // 2
```

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，力扣题解里面的 Python 默认指的是 Python2，不是 Python3，请知晓。
