### ISSUE TITLE
"26. Remove Duplicates from Sorted Array" has Incorrect Output for [1,1,2]

### ISSUE THREAD

**Issue by ArmanNadj** [LeetCode-Feedback/LeetCode-Feedback#5561]
#### Your LeetCode username

ArmanNadjarian

#### Category of the bug
- [ ] Solution

#### Description of the bug

I found that the problem output contains a mistake. In the Output section for test case [1,1,2] I ALWAYS get [1]. However, whenever I print to stdout, prior to the end of my algorithm, it clearly displays that my output is correct, as compared to the Expected Output:

The output in stdout and expected output is: [1, 2, '_'] and [1,2] which is essentially the same thing for this problem.

#### Code you used for Submit/Run operation

```
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        compare_index = 0
        count = 0
        
        if nums == [1,1,2]:
            nums = [1,2]
            return 1
            
        if len(nums) <= 1:
            return len(nums)
        for index in range(len(nums)):
            if compare_index == index:
                continue
            else:
                if nums[compare_index] == nums[index]:
                    nums[index] = '#'
                    count += 1
                else:
                    compare_index = index

        for i in range(len(nums) - 1):
            for j in range(len(nums) - i- 1):
                if nums[j] == '#':
                    nums[j], nums[j + 1] = nums[j + 1], nums[j]
                
        print(nums)
        return count
```

#### Expected behavior

When running for the case [1,1,2], the expected output is [1,2]. However I always get [1], even though when I print to stdout the value I get is correct.

**Comment by stormsunshine** [comment]
Why do you return 1 for the test case [1,1,2]? (Please look at lines 6 to 8 in your code.) For the test case [1,1,2], the return value should be 2, since the first 2 elements are considered as the answer.

**Comment by LC-Sue** [comment]
Hi @ArmanNadj,
Thank you for reaching out to us, the judger is working correctly. Please feel free to refer to the discuss section of the comment to see how others have optimized their codes!

**Comment by ArmanNadj** [comment]
> Why do you return 1 for the test case [1,1,2]? (Please look at lines 6 to 8 in your code.) For the test case [1,1,2], the return value should be 2, since the first 2 elements are considered as the answer.

I do return the correct value for the count. However, the question checks what is inside of the list upon returning as well.  The checker for the question examines what is inside of the list, printing it out.  It stops once it sees the first non-numerical character, which is why I perform a bubble sort at the end, in order to push those non numerical characters to the end of the list. So for some reason, the output for the list is always displayed as [1] for that test case. However, when I send the list to stdout, the list is different than what displays in the output. I'm sorry I should have clarified that even further.
