### ISSUE TITLE
Leetcode 339 - Nested List Weight Sum - Add 341. Flatten Nested List Iterator to Similar questions

### ISSUE THREAD

**Issue by WillWcchan** [LeetCode-Feedback/LeetCode-Feedback#5562]
#### Your LeetCode username
Willwcchan

Leetcode 339 - Nested List Weight Sum is missing the following to the similar questions - 
341. Flatten Nested List Iterator
https://leetcode.com/problems/flatten-nested-list-iterator/

**Comment by LC-Sue** [comment]
Hi @WillWcchan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @WillWcchan 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
