### ISSUE TITLE
Hint 3 and hint 4 are the same  - 301. Remove Invalid Parentheses

### ISSUE THREAD

**Issue by ZhiyuanMa2017** [LeetCode-Feedback/LeetCode-Feedback#5563]
#### Your LeetCode username

hongsuzu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hint 3 of [301. Remove Invalid Parentheses](https://leetcode.com/problems/remove-invalid-parentheses/) is the same as hint 4. 
You can see from the screenshot below.

#### Screenshots

![image](https://user-images.githubusercontent.com/29819347/146272614-fa43db6d-8537-4187-9021-d9cab63571ed.png)

**Comment by LC-Sue** [comment]
Hi @ZhiyuanMa2017 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ZhiyuanMa2017 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
