### ISSUE TITLE
inappropriate comment in the solution - 310. Minimum Height Trees

### ISSUE THREAD

**Issue by kryuki** [LeetCode-Feedback/LeetCode-Feedback#5564]
#### Your LeetCode username

ryukikobayashi

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the solution, the comment says "#base case," but this usage of the word doesn't look correct.
According to the [Wikipedia page](https://en.wikipedia.org/wiki/Base_case), the definition of base case is as follows.
` Base case (recursion), the terminating scenario in recursion that does not use recursion to produce an answer. `

This indicates the word "base case" should be used inside the recursive method.

I assume you intended to use "edge case" instead? 
Thank you.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![base](https://user-images.githubusercontent.com/36336987/146332764-610d67d9-d79c-42e3-aadf-5659c80d0d16.jpg)

**Comment by LC-Sue** [comment]
Hi @kryuki 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kryuki 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by kryuki** [comment]
No problem! Thank you for your comment as well!
