### ISSUE TITLE
frog-jump Solution has spelling mistake

### ISSUE THREAD

**Issue by sidswnt** [LeetCode-Feedback/LeetCode-Feedback#5567]
URL : https://leetcode.com/problems/frog-jump/solution/
 
Approach # 4 : It is Memoization not memorization !

**Comment by LC-Sue** [comment]
Hi @sidswnt 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sidswnt 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
