### ISSUE TITLE
贡献题目

### ISSUE THREAD

**Issue by wbq888** [LeetCode-Feedback/LeetCode-Feedback#5568]
题目类型：动态规划
力扣用户名：wbq888，手机：18013896901 本人邮箱：wbq616@nuaa.edu.cn
题目：1.给正整数N,分解成所有1和3的组合,比如【N=4,分解为1111,13,31】【N=5,分解为[11111,113,131,311】
编程思路：动态规划dp[i]为N=i+1时所有可分解组合的集合，则有dp[i]=sort(Add1(dp[i-1])∪Add3(dp[i-3]))
其中，Addi([]string str)表示str数组中所有字符串末添加字符‘i’
编程语言：C++
来源：香港大学计算机专业面试经验.pdf
附录：源代码
`
#include<iostream>
#include<vector>
#include<algorithm>
#include<string>
std::vector<std::string> SplitNumber(int num)
{
	std::vector<std::vector<std::string>> dp((num > 3) ? num : 3);
	dp[0] = std::vector<std::string>{ "1" };
	dp[1] = std::vector<std::string>{ "11" };
	dp[2] = std::vector<std::string>{ "3","111" };
	if (num < 1)
	{
		std::cout << "error" << std::endl;
		exit(-1);
	}
	else if (num < 4)
	{
		return dp[num - 1];
	}
	else
	{
		for (int i = 3; i < num; i++)
		{
			std::vector<std::string> dp1 = dp[i - 1];
			for (int i = 0; i < dp1.size(); i++)
				dp1[i] = dp1[i] + "1";
			std::vector<std::string> dp3 = dp[i - 3];
			for (int i = 0; i < dp3.size(); i++)
				dp3[i] = dp3[i] + "3";
			dp[i].insert(dp[i].end(), dp1.begin(), dp1.end());
			dp[i].insert(dp[i].end(), dp3.begin(), dp3.end());
			std::sort(dp[i].begin(), dp[i].end());
		}
		return dp[num - 1];
	}
}
void main()
{
	int num = 5;
	std::vector<std::string> result = SplitNumber(num);
	std::cout << "result=[";
	for (int i = 0; i < result.size(); i++)
		std::cout << result[i] << ',';
	std::cout << "\b]";
}
`
附件：源代码文件
[SplitNumber.TXT](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7729267/SplitNumber.TXT)

**Comment by wbq888** [comment]
`#include<iostream>
#include<vector>
#include<algorithm>
#include<string>

std::vector<std::string> SplitNumber(int num)
{
	std::vector<std::vector<std::string>> dp((num > 3) ? num : 3);
	dp[0] = std::vector<std::string>{ "1" };
	dp[1] = std::vector<std::string>{ "11" };
	dp[2] = std::vector<std::string>{ "3","111" };
	if (num < 1)
	{
		std::cout << "error" << std::endl;
		exit(-1);
	}
	else if (num < 4)
	{
		return dp[num - 1];
	}
	else
	{
		for (int i = 3; i < num; i++)
		{
			std::vector<std::string> dp1 = dp[i - 1];
			for (int i = 0; i < dp1.size(); i++)
				dp1[i] = dp1[i] + "1";
			std::vector<std::string> dp3 = dp[i - 3];
			for (int i = 0; i < dp3.size(); i++)
				dp3[i] = dp3[i] + "3";
			dp[i].insert(dp[i].end(), dp1.begin(), dp1.end());
			dp[i].insert(dp[i].end(), dp3.begin(), dp3.end());
			std::sort(dp[i].begin(), dp[i].end());
		}
		return dp[num - 1];
	}
}

void main()
{
	int num = 5;

	std::vector<std::string> result = SplitNumber(num);
	std::cout << "result=[";
	for (int i = 0; i < result.size(); i++)
		std::cout << result[i] << ',';
	std::cout << "\b]";
}`

**Comment by feiceh** [comment]
@lc-kay 这个是题目贡献，麻烦帮忙跟进下这个用户反馈哦。

**Comment by LC-Sue** [comment]
@feiceh 題目貢獻要在網站提交，github提交的團體不受理哦！

**Comment by feiceh** [comment]
@wbq888 你好，贡献题目建议访问 [美国网站](https://leetcode.com/) 提交。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
