### ISSUE TITLE
`117. Populating Next Right Pointers in Each Node II` - Test Cases do not check that the next node has the correct value

### ISSUE THREAD

**Issue by Fried-Chicken** [LeetCode-Feedback/LeetCode-Feedback#5569]
#### Your LeetCode username
Fried-Chicken

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For javascript and typescript answers you can set the `next` node to an empty node and it will still pass.

#### Code you used for Submit/Run operation

```
// Populating Next Right Pointers in Each Node
// Populating Next Right Pointers in Each Node II
const connect = (root: Node | null): Node | null => {
    if (!root) {
    return root;
  }
  
  const queue = [root];
  
  while (queue.length) {
    const size = queue.length;
    
    for (let i = 0; i < size; i++) {
      const node = queue.shift();

      if (node.left) {
          queue.push(node.left);  
      }
      
      if (node.right) {
          queue.push(node.right);   
      }
      
      if (i < size - 1) {
          node.next = new Node();
      }
    }
  }
  
  return root;
};
```

#### Language used for code
Javascript and Typescript

#### Expected behavior
I expect it to check that the next node has the correct value.

#### Additional context
This issue also applies to `Populating Next Right Pointers in Each Node`

**Comment by LC-Sue** [comment]
Hi @Fried-Chicken 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Fried-Chicken** [comment]
@LC-Sue It seems this issue is now fixed! Yay!

**Comment by LC-Sue** [comment]
Hi @Fried-Chicken 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
