### ISSUE TITLE
剑指 Offer 36. 二叉搜索树与双向链表 C#语言提交问题

### ISSUE THREAD

**Issue by ArthasChen** [LeetCode-Feedback/LeetCode-Feedback#557]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言 

**描述**
剑指 Offer 第36题，使用C#语言提交。发现会报错说反序列化有问题，报错信息如下：Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Node' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
我在方法体简单的写一行返回null，按照正常的判定程序，应该是判定我的输出和预期输出不一样。而现在直接报错说json的反序列化有问题。我觉得这不是我提交代码的问题，而是这题判定程序的问题，希望你们可以处理一下这个问题。

**你使用的语言**
C#

**你提交或者运行的代码**
```
/*
// Definition for a Node.
public class Node {
    public int val;
    public Node left;
    public Node right;

    public Node(){}
    public Node(int _val,Node _left,Node _right) {
        val = _val;
        left = _left;
        right = _right;
    }
}
*/
public class Solution {
    public Node TreeToDoublyList(Node root) {
        return null;
    }
}
```

**期望行为**
按照预期，系统应该说我的输出为null，与预期输出不符合。起码能过够正常编译运行。

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。后续请按照本文中提到的格式分享上述代码截图，把信息提供完整才能有助于快速验证和精准的定位这个问题。

**Comment by ArthasChen** [comment]
剑指 Offer 36 题和第426题. 将二叉搜索树转化为排序的双向链表，题目是一样的，426题我顺利通过了。同样的代码，我贴到剑指offer 36题，显示“执行出错”，下面是我的代码和报错截图。
提交代码：
            public class Solution3
         {
                  public Node TreeToDoublyList(Node root)
                  {
                     if (root == null)
                        {
                        return null;
                          }

            ReturnTy re = BinaryConverToList(root);
            Node head = re.headNode;
            Node tail = re.tailNode;
            head.left = tail;
            tail.right = head;
            return head;
        }

            public ReturnTy BinaryConverToList(Node root)
        {
               if (root == null)
            {
                //return null;
                return new ReturnTy(null, null);
            }

            ReturnTy leftReturn = BinaryConverToList(root.left);
            ReturnTy rightReturn = BinaryConverToList(root.right);

            if (leftReturn.tailNode != null)
            {
                root.left = leftReturn.tailNode;

                leftReturn.tailNode.right = root;
            }
            else
            {
                leftReturn.headNode = root;
            }

            if (rightReturn.headNode != null)
            {
                root.right = rightReturn.headNode;


                rightReturn.headNode.left = root;
            }
            else
            {
                rightReturn.tailNode = root;
            }

            return new ReturnTy(leftReturn.headNode, rightReturn.tailNode);
        }
    }

          public class ReturnTy
       {
             public Node headNode;
           public Node tailNode;

        public ReturnTy(Node start, Node end)
        {
            headNode = start;
            tailNode = end;
        }
    }

截图：
![image](https://user-images.githubusercontent.com/24732696/86153746-adfdb400-bb34-11ea-9476-d4d9eb41b67f.png)

![image](https://user-images.githubusercontent.com/24732696/86153787-bd7cfd00-bb34-11ea-8dd5-ff0b2d107a21.png)

**Comment by feiceh** [comment]
好的。此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
您好，该问题已修复，请稍后刷新网页再试试，感谢您对力扣的支持～
