### ISSUE TITLE
Missing Test Case - 350. Intersection of Two Arrays II

### ISSUE THREAD

**Issue by Tzeriz** [LeetCode-Feedback/LeetCode-Feedback#5571]
#### Your LeetCode username

Tzeriz

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The sample 0ms submission is accepted but fails on the test cases with its argument ```int[] nums1``` contains integer 1000 as an element. For example, it fails on this test case,
```
[1000,1000,1000]
[1000,1000]
```

#### Code you used for Submit/Run operation

```java
class Solution {
    public int[] intersect(int[] nums1, int[] nums2) {
        int[] memory = new int[1000];
        
        for (int i = 0; i < nums1.length; i++){
            memory[nums1[i]]++;
        }
        
        ArrayList<Integer> list = new ArrayList<>();
        
        for (int i = 0; i < nums2.length; i++){
            if (memory[nums2[i]] > 0){
                list.add(nums2[i]);
                memory[nums2[i]]--;
            }
        }
        
        int[] result = new int[list.size()];
        
        for (int i = 0; i < result.length; i++){
            result[i] = list.get(i);
        }
        
        return result;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should be rejected as it fails on the above-mentioned valid test case for an out-of-bound exception

**Comment by LC-Sue** [comment]
Hi @Tzeriz 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Tzeriz 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
