### ISSUE TITLE
Missing support of C++ 20 standard. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by typeperfest** [LeetCode-Feedback/LeetCode-Feedback#5572]
#### Your LeetCode username
perfest

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Compiler does not support std::erase_if (C++ 20). 
```
Line 16: Char 22: error: no member named 'erase_if' in namespace 'std'
                std::erase_if(chars_used, [&first_ind](const auto& item) {
                ~~~~~^
1 error generated.
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int lengthOfLongestSubstring(string s) {
        uint32_t first_ind = 0;
        uint32_t max_lenght = 0;
        std::unordered_map<char, uint32_t> chars_used;
        for (uint32_t i = 0; i < s.size(); ++i) {
            auto memorized_char = chars_used.find(s[i]);
            if (memorized_char == chars_used.end()) {
                chars_used.emplace(s[i], i);
            } else {
                if (i - first_ind > max_lenght ) {
                    max_lenght = i - first_ind;
                }
                first_ind = memorized_char->second + 1;
                std::erase_if(chars_used, [&first_ind](const auto& item) {
                    const auto& [key, index] = item;
                    return index <= first_ind;
                });
                memorized_char->second = i;
            }
        }
        return max_lenght;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I had submitted one solution using 20th standard some time ago for another problem. At the moment I got this error I thought leetcode does support 20th standard. If last supporting standard is 17, this issue is irrelevant. I know algorithm supposed to solve this problem is wrong, but I expect there shouldn't be any compilation errors. 

#### Screenshots
![image](https://user-images.githubusercontent.com/61394443/146440718-70cfa14d-64a7-44f0-8e3e-e98749df45e8.png)

#### Additional context
-

**Comment by LC-Sue** [comment]
Hi @typeperfest,
Thank you for reaching out to us, we currently do not support 20 standard for C++. We appreciate your support!
