### ISSUE TITLE
29. Divide Two Integers - Incorrect Test Case

### ISSUE THREAD

**Issue by vishyarjun** [LeetCode-Feedback/LeetCode-Feedback#5573]
#### Your LeetCode username
 vishyarjun1991

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
one of the inbuilt test case is incorrect. a divide by 1 of any integer should return the same integer.

#### Code you used for Submit/Run operation

```
class Solution:
    def divide(self, dividend: int, divisor: int) -> int:
        s = 1 if (divisor>0 and dividend>0) or (divisor<0 and dividend<0) else -1
        q=0
        dividend = dividend-dividend-dividend if dividend<0 else dividend
        divisor = divisor-divisor-divisor if divisor<0 else divisor
        if divisor==1:
            q=dividend
            dividend=-2
        
        while dividend>=0:
            dividend-=divisor
            if dividend<0:
                break
            q+=1
        return -q if s==-1 else q
```

#### Language used for code
Python3

#### Expected behavior
 Division of -2147483648 with -1 should give 2147483648.However one of the inbuilt test case says the correct answer is 2147483647 which seems incorrect

#### Screenshots

![Screen Shot 2021-12-16 at 4 44 23 PM](https://user-images.githubusercontent.com/3880713/146454141-c1c61cf7-7674-4c4e-9b9f-67c232362b11.png)

![Screen Shot 2021-12-16 at 4 50 05 PM](https://user-images.githubusercontent.com/3880713/146454248-571bd0b9-4be2-4c94-804f-ee02241c8449.png)

#### Additional context

Since this question is in the list of top interview questions, its more likely to be accessed by users than other questions

**Comment by LC-Sue** [comment]
Hi @vishyarjun,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how others have optimized their python3 codes!
