### ISSUE TITLE
Need to Change Title for Problem 1529

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5576]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem 1375 used to have title "Bulb Switcher III", but now the title has been changed to "Number of Times Binary String Is Prefix-Aligned". Therefore, the title "Bulb Switcher III" does not exist now. However, the title "Bulb Switcher IV" still exists for problem 1529, so the titles for "Bulb Switcher" include I, II, IV, with III missing.

So I suggest that the title for problem 1529 should be changed to "Bulb Switcher III", which means changing IV to III. Also, the link of problem 1529 should be changed as well.

#### Expected behavior
1. The title of problem 1529 should be changed to "Bulb Switcher III".
2. The link of problem 1529 should be changed according to the new title as well.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for you time. Our team has decided to keep 1529 with the title it currently has.
