### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by haruhiui** [LeetCode-Feedback/LeetCode-Feedback#5579]
#### Your LeetCode username

haruhiui

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For 0^1, the result should be 0.
An example of a wrong accepted solution: 

#### Code you used for Submit/Run operation

```
// Pow
class Solution:
    def myPow(self, x: float, n: int) -> float:
        if n < 0: return 1 / self.myPow(x, -n)
        ans = 1
        while n:
            ans *= n % 2 == 1 and x or 1
            n //= 2
            x *= x
        return ans
```

#### Language used for code

Python3

#### Expected behavior

Input: 0 and 1
Expected answer: 0
Provided solution answer: 1

#### Screenshots

![image](https://user-images.githubusercontent.com/45334324/146642257-7d96082b-175a-43ad-af3a-dc385a9eb08d.png)

#### Additional context

For the test case `0^1`, `n % 2 == 1 and x or 1` is `1` but not `0`.
The correct way should be `x if n % 2 else 0`, by the way.

**Comment by LC-Sue** [comment]
Hi @haruhiui 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @haruhiui 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
