### ISSUE TITLE
1204. 最后一个能进入电梯的人 题目描述小错误

### ISSUE THREAD

**Issue by xmcgcg** [LeetCode-Feedback/LeetCode-Feedback#558]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
（中文版）题目描述中“查询结果如下所示”部分有一句：
> 为了简化，Queue 表按 **_trun_** 列由小到大排序。

**期望行为**
将 trun 改为 turn 。

**Comment by feiceh** [comment]
已修复。
