### ISSUE TITLE
Bug - 29. Divide Two Integers

### ISSUE THREAD

**Issue by sreechar** [LeetCode-Feedback/LeetCode-Feedback#5580]
#### Your LeetCode username
sreecharansiva

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question clearly states to divide two numbers without division, multiplication or mod operator. But even programs using those operators get accepted.  

#### Code you used for Submit/Run operation
```py
class Solution:
    def divide(self, dividend: int, divisor: int) -> int:
        if dividend==0:
            return 0
        elif dividend==-2147483648 and divisor==-1:
            return 2147483647
        elif dividend==-2147483648 and divisor==1:
            return -2147483648
        elif dividend==2147483647 and divisor==-1:
            return -2147483648
        elif dividend==2147483647 and divisor==1:
            return 2147483647
        else:
            if dividend<0:
                sign=-1
                dividend=-dividend
            else:
                sign=1
            if divisor<0:
                sign=-sign
                divisor=-divisor
            count=dividend//divisor
            return count*sign
```

#### Language used for code
Python3

#### Expected behavior
The submission should be rejected as it violates the conditions of the question

#### Screenshots
nil

#### Additional context
Link to the submission : https://leetcode.com/submissions/detail/603418703/

**Possible Suggestions to Fix**
>>> You can convert the whole code to a string and check if /, * or % is present. If True: reject , else: eval

**Comment by LC-Sue** [comment]
Hi @sreechar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sreechar,
Thank you for your time. Our team decided not to take the suggestions. We appreciate your support!
