### ISSUE TITLE
Bug :567. Permutation in String

### ISSUE THREAD

**Issue by saicharan637** [LeetCode-Feedback/LeetCode-Feedback#5581]
#### Your LeetCode username
saicharan637

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Inconsistency between the console and submissions window for the Test Case: 
"abc"
"ccccbbbbaaaa"
The output of the above test case is "false", it gets accepted in the console, but when clicked on submit, in the left hand side submissions window, for the same test case it says Wrong answer and Produces and output "true" when its supposed to be false; 

#### Code you used for Submit/Run operation
```class Solution {
    static List<String> list = new ArrayList<>();
    public boolean checkInclusion(String s1, String s2) {       
        String[] st = perm(s1,"");
        for(String i:st){
            if(s2.contains(i)){
                System.out.print("true");
                return true;
            }
        }
        System.out.print(list+"false");
        return false; 
    }   
   public static String[] perm(String str,String ans){
        
       if(str.length()==0){
           list.add(ans);
       }
       
       for(int i=0;i<str.length();i++){
           char c =str.charAt(i);
           String res = str.substring(0,i)+str.substring(i+1,str.length());
           perm(res,ans+c);
       }
       
       String[] arr = new String[list.size()];
       for(int i=0;i<arr.length;i++){
           arr[i]=list.get(i);
       }
       
       return arr;
   }

}```

```

#### Language used for code
Java

#### Expected behavior
"abc"
"ccccbbbbaaaa" 
The test case above should be Accepted in the left hand side submission window since its being accepted in the console window, but whereas it shows as Wrong Answer in the submission window and is accepted in the console window.

#### Screenshots
![lc](https://user-images.githubusercontent.com/22254732/146630882-b7437195-a98f-46e7-b7e3-be09de7e3066.png)

**Comment by LC-Sue** [comment]
Hi @saicharan637 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
