### ISSUE TITLE
Invalid Test Case - 1705. Maximum Number of Eaten Apples

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#5582]
Please view my [comment](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/4774#issuecomment-997173734) in #4774.

**Comment by stormsunshine** [comment]
To make it clear, the newly added test case is invalid:
```
[0]
[1]
```
The test case where `apples = [0]` and `days = [1]` is invalid. Since the last constraint requires that `days[i] = 0` if and only if `apples[i] = 0`, this test case does not meet this constraint.

Therefore, this test case should be removed.

**Comment by LC-Sue** [comment]
Hi @EndlessCheng
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @EndlessCheng,
Thank you for your time. It appears  the validation code had a bug and that's why it accepted the invalid test cases.
We've fixed the validator and removed the invalid test case.
