### ISSUE TITLE
Typo in hint 2 - 1041. Robot Bounded In Circle

### ISSUE THREAD

**Issue by ZhiyuanMa2017** [LeetCode-Feedback/LeetCode-Feedback#5584]
#### Your LeetCode username

hongsuzu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typo in hint 2 of [1041. Robot Bounded In Circle ](https://leetcode.com/problems/robot-bounded-in-circle/). You can see from the screenshot.

#### Screenshots

![image](https://user-images.githubusercontent.com/29819347/146656286-39461c69-d7c0-4906-95bd-14732a905ba0.png)

**Comment by LC-Sue** [comment]
Hi @ZhiyuanMa2017 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ZhiyuanMa2017,
Thank you for your time. The initial wording was correct, iff ==> if and only if. However, we've updated it as not everyone is familiar with abbreviations.
