### ISSUE TITLE
Missing Test Case - 1568. Minimum Number of Days to Disconnect Island

### ISSUE THREAD

**Issue by pvkcseaccet** [LeetCode-Feedback/LeetCode-Feedback#5585]
#### Your LeetCode username
pvkcse

#### Category of the bug

Missing Test Cases 

#### Description of the bug
In case if no island is possible and all that given is just grid full of water, answer must be 0. But as per my passed submission, 2 is getting accepted which I felt is wrong.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def minDays(self, grid):
        """
        :type grid: List[List[int]]
        :rtype: int
        """
        self.r, self.c, self.grid = len(grid), len(grid[0]), grid
        
        canGo = lambda r, c, visited : r >= 0 and r < self.r and c >= 0 and c < self.c and self.grid[r][c] == 1 and not visited[r][c]
        
        def checkIfIsland(r, c, visited):
            visited[r][c] = True
            if canGo(r - 1, c, visited): checkIfIsland(r - 1, c, visited)
            if canGo(r + 1, c, visited): checkIfIsland(r + 1, c, visited)
            if canGo(r, c - 1, visited): checkIfIsland(r, c - 1, visited)
            if canGo(r, c + 1, visited): checkIfIsland(r, c + 1, visited)
            
        def countIslands():
            visited = [[False for __ in range(self.c)] for _ in range(self.r)]
            islands = 0
            for i in range(self.r):
                for j in range(self.c):
                    if self.grid[i][j] == 1 and not visited[i][j]:
                        checkIfIsland(i, j, visited)
                        islands += 1
            return islands
        
        def canDisconnect():
            visited = [[False for __ in range(self.c)] for _ in range(self.r)]
            if countIslands() > 1: return 0
            for i in range(self.r):
                for j in range(self.c):
                    if self.grid[i][j] == 1:
                        self.grid[i][j] = 0
                        islands = countIslands()
                        if islands != 1: return 1
                        self.grid[i][j] = 1
            return 2
                    
        return canDisconnect()
                    
```

#### Language used for code
Python

#### Expected behavior
In case if no land is given and all that provided is just a grid full of water, answer must be 0. But as per my passed submission, 2 is getting accepted which I felt is wrong. So we can add following testcases.
Input: [[0]]
Expected Output: 0
Accepted Output: 2

Input: [[0,0]]
Expected Output: 0
Accepted Output: 2

#### Screenshots

<img width="1423" alt="Screenshot 2021-12-19 at 3 46 29 AM" src="https://user-images.githubusercontent.com/8597620/146656928-821daec0-76e7-4d37-81bc-722299a436eb.png">

**Comment by LC-Sue** [comment]
Hi @pvkcseaccet 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @pvkcseaccet 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
