### ISSUE TITLE
printing of solution is broken

### ISSUE THREAD

**Issue by gelpenaddict** [LeetCode-Feedback/LeetCode-Feedback#5586]
https://leetcode.com/problems/word-break-ii/solution/

If I try to print the solution to a printer from Safari on MacOS latest versions, only 1 page is printed and the formatting is off, showing part of the coding frame on the right side.

Please consider a "print me" link with proper formatting.

**Comment by LC-Sue** [comment]
Hi @gelpenaddict,
Thank you for reaching out to us, I have relayed this feedback over to our team for future improvements!
