### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by hclaud99** [LeetCode-Feedback/LeetCode-Feedback#5587]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/explore/learn/card/hash-table/182/practical-applications/1142/
  Design Hash Table - Solution

Not
```
vector<int> set[MAX_LEN]; 
```
Shall be:
```
vector<vector<int>> set[MAX_LEN]; 
```

#### Screenshots

Not
```
vector<int> set[MAX_LEN]; 
```
Shall be:
```
vector<vector<int>> set[MAX_LEN]; 
```

**Comment by LC-Sue** [comment]
Hi @hclaud99 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hclaud99,
Thank you for your time, the current code runs as it should and making the change the suggested would result in an error.
