### ISSUE TITLE
TypeScript & JavaScript: Could you please considering add `set` and other API similar to C++ STL

### ISSUE THREAD

**Issue by upupming** [LeetCode-Feedback/LeetCode-Feedback#5588]
#### Your LeetCode username

upupming

#### Add other libraries for JS

Hi there, 

Although we have the `datastructures-js/priority-queue` and `datastructures-js/queue`, I think it is not quite enough. JS and TS is missing the [`set`](https://www.cplusplus.com/reference/set/set/) and [`multiset`](https://www.cplusplus.com/reference/set/multiset/) in C++ STL. This has made people custom to use JS/TS more difficult to solve problems related to these data structures.

We (@harttle and @upupming) have maintianed a repo for all these algorithm template as a library: 

- GitHub: https://github.com/harttle/contest.js/blob/HEAD/README.en.md
- npm: https://www.npmjs.com/package/contest.js

For example:

- C++ `set` equivalent: [TreeSet](https://github.com/harttle/contest.js/blob/156d168963e2f3c8cb9c28c2a6f51ed4e5968de3/treeset.ts#L3)
- C++ `multiset` equivalent: [TreeMultiSet](https://github.com/harttle/contest.js/blob/156d168963e2f3c8cb9c28c2a6f51ed4e5968de3/treeset.ts#L112)
- C++ `deque` equivalent: [Deque](https://github.com/harttle/contest.js/blob/156d168963e2f3c8cb9c28c2a6f51ed4e5968de3/deque.ts#L75)

Could you please consider adding it to the LeetCode JS/TS judgment environment?

Thanks!

**Comment by LC-Sue** [comment]
Hi @upupming,
Thank you for reaching out to us, I have relayed this feedback over to our team for future improvements!

**Comment by bytrangle** [comment]
Has this feature been implemented? At least as of now, it's impossible to use multiset in Javascript.
