### ISSUE TITLE
Missing Test Case - 487. Max Consecutive Ones II

### ISSUE THREAD

**Issue by mmaia** [LeetCode-Feedback/LeetCode-Feedback#5590]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

#### Description of the bug

Based on the constraints for the problem: 

Constraints:
1 <= nums.length <= 105
nums[i] is either 0 or 1.

a valid input would be {0,1}
with expected result: 1

and {0,0}
with expected result: 0

and {0}
with expected result: 0

but the proposed solutions don't sustain as they return wrong values for both tests.

#### Code you used for Submit/Run operation

```java 
public class MaxConsecutiveOnes2 {
    /**
     * Brute force implementation not optimized
     * O(n^2) - Quadratic time complexity
     */
    public int findMaxConsecutiveOnesNaive(int[] nums) {
        int maxSeq = 0;
        for (int leftPointer = 0; leftPointer < nums.length; leftPointer++) {
            int numZeroes = 0;
            for (int rightPointer = leftPointer; rightPointer < nums.length; rightPointer++) {
                if(nums[rightPointer] == 0) numZeroes++;
                if(numZeroes <= 1) maxSeq = Math.max(maxSeq, rightPointer - leftPointer + 1);
            }
        }
        return maxSeq;
    }
}

```

#### Language used for code

Java

#### Expected behavior

should result 1 but proposed solution result in 2

#### Additional context

I propose to add a guard condition to the solutions proposed and  new test cases{0},  {0,1} and {0,0} as input with expected results being  0, 0, 1 respectively and adjust the proposed solutions to match. Unless I am missing something about the problem which is implicit. 

I also find strange that proposed solutions don't sustain for inputs like: {0,1,1,0} (expected 2 but proposed sols return 3)

**Comment by LC-Sue** [comment]
Hi @mmaia,
Thank you for reaching out to us, the code that you provide doesn't run on my end. Could you provide your submission link so I could verify the code?

**Comment by mmaia** [comment]
Hi, 

Here is the link: https://leetcode.com/submissions/detail/605686879/

But the issue is not that my code doesn't pass the tests. The issue I am trying to report is that based on the problem description some test cases I prepared before submitting were not passing. i.e - the description needs to impose more constraints or such "valid" test cases would not sustain,  see some test cases examples that based on the problem description seem to be valid but the implementation does not pass those tests(although it does pass all the current test cases on site). 

```java
@Test
    public void test4() {
        int[] nums = {0,1};
        int expectedRes = 1;
        assertEquals(expectedRes, mco.findMaxConsecutiveOnes(nums));
        assertEquals(expectedRes, mco.findMaxConsecutiveOnesNaive(nums));
    }

    @Test
    public void test5() {
        int[] nums = {0,1,1,0,1};
        int expectedRes = 3;
        assertEquals(expectedRes, mco.findMaxConsecutiveOnes(nums));
        assertEquals(expectedRes, mco.findMaxConsecutiveOnesNaive(nums));
    }

    @Test
    public void test6() {
        int[] nums = {0,0};
        int expectedRes = 0;
        assertEquals(expectedRes, mco.findMaxConsecutiveOnes(nums));
        assertEquals(expectedRes, mco.findMaxConsecutiveOnesNaive(nums));
    }

    @Test
    public void test7() {
        int[] nums = {0};
        int expectedRes = 0;
        assertEquals(expectedRes, mco.findMaxConsecutiveOnes(nums));
        assertEquals(expectedRes, mco.findMaxConsecutiveOnesNaive(nums));
    }

```
So unless I am missing something from the description the problem needs to have a few more constraints or improve the description to avoid confusion.

**Comment by LC-Sue** [comment]
Hi @mmaia 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @mmaia,
Thank you for your time, our team has reviewed the issue and the constraints are fine and the expected answers are correct. All the mentioned test cases do exist.
