### ISSUE TITLE
DP card missing chapter

### ISSUE THREAD

**Issue by joshribakoff** [LeetCode-Feedback/LeetCode-Feedback#5592]
https://leetcode.com/explore/learn/card/dynamic-programming/633/common-patterns-continued/4144/

> In an earlier chapter when we used the framework to solve Maximum Score from Performing Multiplication Operations

I do not see such problem earlier in the explore card

**Comment by LC-Sue** [comment]
Hi @joshribakoff,
Thank you for reaching out to us, please find the problem mentioned here: https://leetcode.com/explore/learn/card/dynamic-programming/631/strategy-for-solving-dp-problems/4100/

**Comment by joshribakoff** [comment]
@LC-Sue Thanks but the page already linked to the problem, so locating the problem was not my issue :)

The issue is actually a scriveners error. It states the problem had been encountered in an earlier chapter within the explore card, when it was not. This is confusing for someone who is going through the explore card expecting concepts to be introduced in order.
