### ISSUE TITLE
Missing Test Case - 85. Maximal Rectangle

### ISSUE THREAD

**Issue by msluszniak** [LeetCode-Feedback/LeetCode-Feedback#5594]
#### Your LeetCode username
ace_of_diamonds

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The code which in general does not work passes all the test cases.

#### Code you used for Submit/Run operation

```c++
int findMax(vector<vector<char>>& matrix) {
    vector<vector<int>> arr(matrix.size());
    for(int i = 0; i < matrix.size(); i++) {
        arr[i].reserve(matrix[i].size());
        arr[i].push_back(matrix[i][0]-'0');
        for(int j = 1; j < matrix[i].size(); j++) {
            arr[i].push_back((arr[i].back() + 1)*(matrix[i][j]-'0'));
        }
    }
    int ans = 0;
    for(int j = 0; j < arr[0].size(); j++) {
        int len = 0, count = 0;
        for(int i = 0; i < arr.size(); i++) {
            len = len == 0 ? arr[i][j] : min(len, arr[i][j]);
            if(len) count++;
            else count = 0;
            ans = max(ans, count*len);
        }
    }
    for(int j = 0; j < arr[0].size(); j++) {
        int len = 0, count = 0;
        for(int i = arr.size()-1; i >= 0; i--) {
            len = len == 0 ? arr[i][j] : min(len, arr[i][j]);
            if(len) count++;
            else count = 0;
            ans = max(ans, count*len);
        }
    }
    return ans;
}
vector<vector<char>> transpose(vector<vector<char>>& matrix) {
    vector<vector<char>> res(matrix[0].size());
    for(int j = 0; j < matrix[0].size(); j++) {
        for(int i = 0; i < matrix.size(); i++) {
            res[j].push_back(matrix[i][j]);
        }
    }
    return res;
}
class Solution{
public:
    int maximalRectangle(vector<vector<char>>& matrix) {
        if(matrix.size() == 0) return 0;
        vector<vector<char>> matrixT = transpose(matrix);
        return max(findMax(matrix), findMax(matrixT));
    }
};
```

#### Language used for code
C++

#### Expected behavior

for testcase 
[["0","0","1","0","1","0","0"],["0","1","1","1","1","1","0"],["0","0","1","1","1","0","0"],["0","1","1","1","1", "1","0"],["0","0","1","0","1","0","0"]]

correct output is 9, but the accepted code returns 6.

#### Screenshots

For all test cases like given below, the program returns the wrong answer
![image](https://user-images.githubusercontent.com/56299341/146698111-1f88f534-1b56-42c1-95b8-feb616add696.png)

**Comment by LC-Sue** [comment]
Hi @msluszniak 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @msluszniak 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!

**Comment by LC-Sue** [comment]
Hi @msluszniak 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
