### ISSUE TITLE
The Difficulty of Weekly and Biweekly Contest Needs to Be Increased

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#5595]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug

The quality of the weekly contest and biweekly contest is more and more unsatisfactory recently. After the 65th biweekly contest, I cannot find any question which is enough to be marked as "Hard". The third problems of each contest are also too easy. I think all the third problems which starts with '20' are too easy for the third problem except 2029, compared with problems which starts with '18' or  '19'. As the third problem, the difficulty of the problem 2091, 2105 and 2110  cannot reach the lowest requirement for the interview. The interviewers can never use these problems in a real interview, even if he is in the horrible company, the leaders of which regards each staff as cheap labor and cannot give them salary on time.    

So, I think the difficulty of weekly and biweekly contest should be increased.
In addition, the problems which is very convenient for Python users, such as 2102, should not appear in contest.

Expected behavior
The difficulty of weekly contest should be increased:
1.The brute force solution for the second problem should not be allowed.
2.The difficulty of the third problem should be enough for a real interview.
3. The last problem should be challenging for most users.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837,
Thank you for your feedback. We are working hard to improve the experience of our contests.
Since we provide a contest based on real interview problems and online assessments, the difficulty of the contest is affected by the interview problems we have.
