### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by IntruderVs** [LeetCode-Feedback/LeetCode-Feedback#5597]
#### Your LeetCode username
intruder86

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
My code works in your site.
But my code doesn't work using my test when:

nums.length == 0
removeDuplicates(new int[0])

Your test expects k == 0. My code return 1.
But(!) Your test succeeds.

assert k == expectedNums.length;   - does this check work?

#### Code you used for Submit/Run operation
```
class Solution {
    public int removeDuplicates(int[] nums) {
        int length = 0;
        for (int i = 1; i < nums.length; i++) {
            if (nums[length] != nums[i])
                nums[++length] = nums[i];
        }
        return ++length;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Throw exception or there shouldn't be this(```assert k == expectedNums.length;```) check.

**Comment by LC-Sue** [comment]
Hi @IntruderVs,
Thank you for reaching out to us, could you please provide the test case that makes the code fail?

**Comment by IntruderVs** [comment]
If I execute this test.
```
    @Test
    void removeDuplicatesEmptyArray() {
        int[] nums = new int[]{}; // Input array
        int[] expectedNums = new int[]{}; // The expected answer with correct length

        int k = sortedArray.removeDuplicates(new int[0]); // Calls your implementation

        assertEquals(expectedNums.length, k);

        for (int i = 0; i < k; i++) {
            assertEquals(expectedNums[i], nums[i]);
        }
    }
```
my code will receive 1;
but  expectedNums.length == 0 
My test should fall here: ```assertEquals(expectedNums.length, k);``` - (assert k == expectedNums.length;)
But your test not fall here: ```assert k == expectedNums.length;```

**Comment by LC-Sue** [comment]
Hi @IntruderVs,
Please provide the test case for example : nums = [1,1,2]
