### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by emli** [LeetCode-Feedback/LeetCode-Feedback#56]
![image](https://user-images.githubusercontent.com/5517490/77160699-21be0880-6ad2-11ea-8926-abc36ce741fb.png)

https://leetcode.com/problems/longest-palindromic-substring/solution/

**Comment by CooperCooperCooper** [comment]
Hi @emli,
Thank you for reaching out to us. Since this is not a content-issue, please share this issue with our support team here: https://support.leetcode.com/hc/en-us. We appreciate your support.
