### ISSUE TITLE
804. 唯一摩尔斯密码词 题目描述有待改善

### ISSUE THREAD

**Issue by JellyfishMIX** [LeetCode-Feedback/LeetCode-Feedback#560]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
摩尔斯密码
a: ".-"
b: "-..."
c: "-.-."
原题目描述：
"cab" 可以写成 "-.-..--..."，(即 "-.-." + "-..." + ".-"字符串的结合)。

**期望行为**
应改为：
"cab" 可以写成 "-.-..--..."，(即 "-.-." + ".-" + "-..."字符串的结合)。
请注意括号中字符串拼接的顺序。

**屏幕截图**
<img width="799" alt="截屏2020-06-30上午10 06 07" src="https://user-images.githubusercontent.com/52696481/86074973-83224a00-bab9-11ea-9992-85e2f8c5015c.png">

**Comment by JellyfishMIX** [comment]
804. 唯一摩尔斯密码词 题目描述有待改善

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
已修复。
