### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by blazerod-cmd** [LeetCode-Feedback/LeetCode-Feedback#5600]
#### Category of the bug
- [  Longest Substring Without Repeating Characters] Question
- [ ] Solution
- [c ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by blazerod-cmd** [comment]
Input
"ynyo"
Output
2
Expected
3

**Comment by stormsunshine** [comment]
What is the code that can get accepted but fails on the test case you provide?

**Comment by LC-Sue** [comment]
Hi @blazerod-cmd,
Thank you for reaching out to us, could you provide the code you used for submission?

**Comment by stormsunshine** [comment]
This test case is NOT missing, and the correct output is 3 since the longest substring without repeating characters is "nyo", which has length 3.

**Comment by LC-Sue** [comment]
Hi @blazerod-cmd,
Thank you for your time, did you have any other questions after stormsunshine's explanation? If so, please reopen the ticket and let me know!
