### ISSUE TITLE
Missing Test Case -[3,9,8,6,4] 852. Peak Index in a Mountain Array

### ISSUE THREAD

**Issue by ashiqYousuf** [LeetCode-Feedback/LeetCode-Feedback#5601]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by ashiqYousuf** [comment]
Actually few solutions got accepted in python because in python negative array indices are allowed , So adding this test cases will surely give wrong solutions ,

**Comment by stormsunshine** [comment]
What is the code that can get accepted but fails on the test case you provide?

**Comment by ashiqYousuf** [comment]
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:
        start , end= 0 , len(arr)-1
        while(start<=end):
            mid=start+(end-start)//2;
            if(arr[mid]>arr[mid-1] and arr[mid]>arr[mid+1]):
                return mid
            elif (arr[mid-1]>arr[mid]):
                end=mid-1
            elif arr[mid+1]>arr[mid]:
                start=mid+1

This is the python code which gets accepted but when it's given the test
case [3,9,8,6,4] , it gives wrong answer(this is a valid test case having a
single peak element)

**Comment by ashiqYousuf** [comment]
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:
        start , end= 0 , len(arr)-1
        while(start<=end):
            mid=start+(end-start)//2;
            if(arr[mid]>arr[mid-1] and arr[mid]>arr[mid+1]):
                return mid
            elif (arr[mid-1]>arr[mid]):
                end=mid-1
            elif arr[mid+1]>arr[mid]:
                start=mid+1

**Comment by LC-Sue** [comment]
Hi @ashiqYousuf 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ashiqYousuf** [comment]
Thanks for considering

**Comment by ashiqYousuf** [comment]
Have u checked now????

**Comment by LC-Sue** [comment]
Hi @ashiqYousuf,
Thank you for your time.  We've used your feedback to update the problem. We'd like to reward you for this contribution, please provide your LeetCode username!

**Comment by ashiqYousuf** [comment]
Sure, here it is my leetcode profile link
https://leetcode.com/ashiqhussainkumar143/

Thanks and it'll motivate me for further contributions

**Comment by ashiqYousuf** [comment]
Haven't got still 😀

**Comment by ashiqYousuf** [comment]
?A subtle remainder

**Comment by LC-Sue** [comment]
Hi @ashiqYousuf 
Thank you for your time. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by ashiqYousuf** [comment]
Thank you for your support!
