### ISSUE TITLE
Missing Test Case - 137. Single Number II

### ISSUE THREAD

**Issue by sushilfefar** [LeetCode-Feedback/LeetCode-Feedback#5602]
#### Your LeetCode username

savan_fefar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is no testcase where it tests the code when the answer if -1.

#### Code you used for Submit/Run operation

```
negatives = sum(1 if i<-1 else 0 for i in nums)
```

#### Language used for code

Python

#### Expected behavior

The condition should be < 0 or <= -1 so that it actually considers negatives.

**Comment by LC-Sue** [comment]
Hi @sushilfefar,
Thank you for reaching out to us, could you provide the test case you believe is missing and the code used for submission?

**Comment by LC-Sue** [comment]
Hi @sushilfefar 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
