### ISSUE TITLE
Missing Test Case - 1154. Day of the Year

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5607]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [1154. Day of the Year](https://leetcode.com/problems/day-of-the-year), a solution that get accepted fails on one or more test cases.

According to [Wikipedia: Gregorian calendar](https://en.wikipedia.org/wiki/Gregorian_calendar), the rule for leap year is:

> Every year that is exactly divisible by four is a leap year, except for years that are exactly divisible by 100, but these centurial years are leap years if they are exactly divisible by 400. For example, the years 1700, 1800, and 1900 are not leap years, but the years 1600 and 2000 are.

Therefore, the year 1900 is NOT a leap year, so there are only 28 days in February, 1900.

However, an incorrect solution can still get accepted. This solution determines whether a year is a leap year or not by simply checking whether the year is divisible by 4, which is incorrect since the centurial years that are not divisible by 400 are also considered as leap years. Obviously, the reason why the solution can get accepted is that there are no test cases for dates in year 1900 that are after February 28th.

For example, the following test cases are missing. Some more test cases for year 1900 after February 28th can also be added.
```
"1900-03-01"
"1900-03-31"
"1900-04-01"
"1900-04-30"
"1900-05-01"
"1900-05-31"
"1900-06-01"
"1900-06-30"
"1900-07-01"
"1900-07-31"
"1900-08-01"
"1900-08-31"
"1900-09-01"
"1900-09-30"
"1900-10-01"
"1900-10-31"
"1900-11-01"
"1900-11-30"
"1900-12-01"
"1900-12-31"
```

#### Code you used for Submit/Run operation
```
class Solution {
    public int dayOfYear(String date) {
        int year = Integer.parseInt(date.substring(0, 4));
        int month = Integer.parseInt(date.substring(5, 7));
        int day = Integer.parseInt(date.substring(8));

        int[] amount = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
        if (year % 4 == 0) {
            ++amount[1];
        }

        int ans = 0;
        for (int i = 0; i < month - 1; ++i) {
            ans += amount[i];
        }
        return ans + day;
    }
}
```

#### Language used for code
Java

#### Expected behavior
One or more test cases with year 1900 and month and date on March 1st or later should be added so that the code above will get Wrong Answer when submitted.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
