### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by GunjanSahu11** [LeetCode-Feedback/LeetCode-Feedback#5609]
class Solution(object):
    def containsDuplicate(self, nums):
        """
        :type nums: List[int]
        :rtype: bool
        """

        a = set()
        for n in nums:
            if n in a:
                return True
            a.add(n)
        return False

**Comment by GunjanSahu11** [comment]
Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.

 

Example 1:

Input: nums = [1,2,3,1]
Output: true
Example 2:

Input: nums = [1,2,3,4]
Output: false
Example 3:

Input: nums = [1,1,1,3,3,4,3,2,4,2]
Output: true
 

Constraints:

1 <= nums.length <= 105
-109 <= nums[i] <= 109

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?

**Comment by LC-Sue** [comment]
Hi @GunjanSahu11,
Thank you for reaching out to us, could you please provide the code you used for submission and the test case that fails the code?

**Comment by LC-Sue** [comment]
Hi @GunjanSahu11 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
