### ISSUE TITLE
1495. Friendly Movies Streamed Last Month, descriptions don't match result query.

### ISSUE THREAD

**Issue by bytebeats** [LeetCode-Feedback/LeetCode-Feedback#561]
In the description of problem of [1495. Friendly Movies Streamed Last Month](https://leetcode.com/problems/friendly-movies-streamed-last-month/), it says: 

**Result table:
+--------------+
| title        |
+--------------+
| Aladdin      |
+--------------+
**

But, actually, the result query is: 

**Result table:
+--------------+
| TITLE        |
+--------------+
| Aladdin      |
+--------------+
**

I think, it will confuse us. Upper case is the right description.
Thank you. Hope this suggestion will be accepted.

**Comment by lc-kate** [comment]
Hi @bytebeats ,
Thank you for reaching out to us. Since lower case "title" was used consistently throughout the problem description, would you please provide more clarification on why the upper case is a better choice?

**Comment by bytebeats** [comment]
What I meant is that the actual `Run Code Result` - `Expected` is 
**{"headers": ["TITLE"], "values": [["Aladdin"]]}**
But the description of the problem about the `Result Table` is
**Result table:
+--------------+
| **title** |
+--------------+
| Aladdin |
+--------------+
**

This is what confused us.

**Comment by lc-kate** [comment]
Hi @bytebeats ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @bytebeats ,
Thank you for your time. Please note the header is case sensitive, so the change will not be applicable in this case. We appreicate your support.
