### ISSUE TITLE
Problem about testcase of Question 491

### ISSUE THREAD

**Issue by Lbaron980810** [LeetCode-Feedback/LeetCode-Feedback#5612]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My solution didn't pass testcase "[1,2,3,4,5,6,7,8,9,10,1,1,1,1,1]", because my answer includes [1, 1], [1, 1, 1].... but expected answer doesn't. But these sets should be included according to the description.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<vector<int>> result;
    vector<int> path;

    void backtracking (vector<int>& nums, int startInd, vector<bool>& used) {
        if (path.size() >= 2) result.push_back(path);
        if (startInd == nums.size()) return;
        for (int i = startInd; i < nums.size(); i++)
        {
            if(i > 0 && nums[i] == nums[i - 1] && used[i - 1] == false) continue;
            if (path.empty() || nums[i] >= path[path.size() - 1]) {
                path.push_back(nums[i]);
                used[i] = true;
                backtracking(nums, i + 1, used);
                path.pop_back();
                used[i] = false;
            }
        }
    }
    vector<vector<int>> findSubsequences(vector<int>& nums) {
        result.clear();
        path.clear();
        vector<bool> used(nums.size(), false);
        backtracking(nums, 0, used);
        return result;
    }
};
```

#### Screenshots

![Screenshot from 2021-12-21 20-19-24](https://user-images.githubusercontent.com/46702351/146928907-5cb9c0da-1990-446d-8421-42d98e2b59c6.png)

**Comment by LC-Sue** [comment]
Hi @Lbaron980810,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their C++ codes!
