### ISSUE TITLE
Misspelled word in 250. Count Univalue Subtrees

### ISSUE THREAD

**Issue by coshea** [LeetCode-Feedback/LeetCode-Feedback#5613]
#### Your LeetCode username
coshea34

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the first bullet point of the **Constraints** section of the problem description, the word **_number_** is misspelled. It reads:

- The _numbrt_ of the node in the tree will be in the range [0, 1000].

#### Code you used for Submit/Run operation
N/A

#### Language used for code

N/A

#### Expected behavior

The word **_numbrt_** should be changed to _**number**_

#### Screenshots

![image](https://user-images.githubusercontent.com/3649225/146948446-075279f4-aa4b-4797-9f28-20b0a8bae778.png)

**Comment by LC-Sue** [comment]
Hi @coshea 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @coshea 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
