### ISSUE TITLE
Proper grammar - 1345. Jump Game IV

### ISSUE THREAD

**Issue by utsavDave97** [LeetCode-Feedback/LeetCode-Feedback#5616]
#### Your LeetCode username
utsavdave

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For Hint 2 on the last it should be ***when you reach on node n-1*** instead of ***when you reach onode n-1***

**Comment by LC-Sue** [comment]
Hi @utsavDave97 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @utsavDave97 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
