### ISSUE TITLE
Error in test case - 566. Reshape the Matrix

### ISSUE THREAD

**Issue by keshavbantu** [LeetCode-Feedback/LeetCode-Feedback#5617]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In example 2 of test cases, statement **c=4** is wrong and should be **c=2** as there are two columns

#### Code you used for Submit/Run operation

```
NA
```

**Comment by stormsunshine** [comment]
I don't think the example 2 needs to be modified. In this case, r * c != m * n, so the original matrix is returned. This makes sense.

The examples should cover as many cases as possible, including the case where r * c != m * n.

**Comment by keshavbantu** [comment]
Oh my apologies, ill go ahead and close this issue, thanks.
