### ISSUE TITLE
Invalid test cases are not reported - 1323. Maximum 69 Number

### ISSUE THREAD

**Issue by jaisw7** [LeetCode-Feedback/LeetCode-Feedback#5618]
#### Your LeetCode username
jaisw7

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect test configuration

#### Description of the bug
Whenever we enter a test case in the console, and the test case does not meet the constraints specified in the problem, the server returns 'Invalid test case' error. 

This problem specifies that num's digits are 6 or 9. However, when I enter 2699, the server returns "Wrong Answer" instead of "Invalid test case".

#### Code you used for Submit/Run operation
The code below passed all the test cases.
```
class Solution {
public:
    int maximum69Number (int num) {
        char buffer[8];
        int pos = snprintf(buffer, 10, "%d", num);
        
        for(int i=0; i<pos; ++i) {
            if(buffer[i]=='6') {
                buffer[i] = '9';
                break;
            }
        }
        
        num = 0;
        for(int i=0; i<pos; ++i) {
            num = num*10 + (buffer[i]-'0');
        }
        
        return num;
    }
};
```

#### Language used for code
C++

#### Expected behavior
See "Description of the bug"

#### Screenshots
<img width="548" alt="Screen Shot 2021-12-22 at 11 01 06 AM" src="https://user-images.githubusercontent.com/26517937/147120711-3cc1d03d-3949-49a7-943b-5e982239fa90.png">

**Comment by LC-Sue** [comment]
Hi @jaisw7 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jaisw7 
Thank you for your time. We have updated the validator. We appreciate your support!
