### ISSUE TITLE
Inaccurate problem description - 127. Word Ladder

### ISSUE THREAD

**Issue by maple1eaf** [LeetCode-Feedback/LeetCode-Feedback#5619]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My solution with O(m * n^2) time | O(n^2) space solution. (where m is the length of each word and n is the number of words).

But my solution exceeds the time limit of some test cases. The reason it exceeds is that in these test cases, the number of words is too many. On the other hand, according to the official solution, the time complexity is O(m^2 * n) and space complexity is O(m^2 * n), which will pass the many-words cases but will fail when the length of a word is long. I argue that, at least in the constraints, the question should talk about the goal that the number of words is much more important than the length of a word.

#### Code you used for Submit/Run operation

```
// Word Ladder
class Solution:
    # O(m * n^2) time | O(n^2) space - where m is the length of each word and n is the number of words
    def ladderLength(self, beginWord: str, endWord: str, wordList: List[str]) -> int:
        if endWord not in wordList:
            return 0
        
        wordLength = len(beginWord)
        startIdx = 0
        if beginWord not in wordList:
            wordList.append(beginWord)
            startIdx = len(wordList) - 1
        else:
            startIdx = wordList.index(beginWord)
        targetIdx = wordList.index(endWord)
        
        distances = [set() for _ in wordList]
        for i in range(len(wordList)):
            for j in range(i + 1, len(wordList)):
                if self.calDistance(i, j, wordList, wordLength) == 1:
                    distances[i].add(j)
                    distances[j].add(i)
        return self.calMinPathLength(distances, startIdx, targetIdx)
        
    def calDistance(self, i, j, words, wordLength):
        word1, word2 = words[i], words[j]
        distance = 0
        for i in range(wordLength):
            if word1[i] != word2[i]:
                distance += 1
            if distance > 1:
                return None
        return 1 if distance == 1 else None
    
    def calMinPathLength(self, distances, startIdx, targetIdx):
        visited = {startIdx}
        length = 1
        store = [startIdx]
        while len(store) > 0:
            nextStore = []
            for n in store:
                for nxt in distances[n]:
                    if nxt == targetIdx:
                        return length + 1
                    if nxt in visited:
                        continue
                    visited.add(nxt)
                    nextStore.append(nxt)
            length += 1
            store = nextStore
        return 0
```

#### Language used for code

Python3

#### Expected behavior

One of the choices could be done:
- tell in the constraint that the length of wordList is much bigger than the length of one word.
- loosen the time restrictions and add the test cases of long-word with a smaller size of wordList.

**Comment by LC-Sue** [comment]
Hi @maple1eaf 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @maple1eaf,
Thank you for your time. Considering tell in the constraint that the length of wordList is much bigger than the length of one word. The constraints are clear and told the exact sizes of the words and the words list.
