### ISSUE TITLE
1153. String Transforms Into Another String

### ISSUE THREAD

**Issue by claytonjwong** [LeetCode-Feedback/LeetCode-Feedback#5622]
#### Your LeetCode username
claytonjwong

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem is unclear that we need a "spare" character, ie. `False` is expected rather than `True` for the test case below.  The problem statement can explicitly mention that all of the s[i] 👉 t[i] transformations are performed simultaneously in parallel (_not_ sequentially)

```
s = "abcdefghijklmnopqrstuvwxyz"
t = "bcdefghijklmnopqrstuvwxyza"
```

#### Code you used for Submit/Run operation
```
class Solution:
    def canConvert(self, s: str, t: str) -> bool:
        if s == t:
            return True
        m = {}
        for i in range(len(s)):
            if s[i] in m and m[s[i]] != t[i]:
                return False
            m[s[i]] = t[i]
        return len(set(t)) < 26  # 👈 THIS IS STUPID (the mapping below should be TRUE not FALSE)
                                 # s = "abcdefghijklmnopqrstuvwxyz"
                                 # t = "bcdefghijklmnopqrstuvwxyza"
```

#### Language used for code
Python3

#### Expected behavior
I expect the problem statement to specify the simultaneous transformations constraint.

**Comment by LC-Sue** [comment]
Hi @claytonjwong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stormsunshine** [comment]
@claytonjwong You have misunderstood the problem. Please read the problem statement carefully.

> Given two strings `str1` and `str2` of the same length, determine whether you can transform `str1` into `str2` by doing **zero or more** *conversions*.

Also, in example 1, the explanation implies that the conversions are performed sequentially, not simultaneously.

Therefore, the test case you provided should return `false`, which is the expected result.

**Comment by claytonjwong** [comment]
Maybe it would be more clearly expressed as sequential transformations?  I previously imagined the transformations in parallel.

**Comment by LC-Sue** [comment]
Hi @claytonjwong,
Thank you for your time. The problem is not about simultaneous transformations.The statement said that you can do any number of conversions and did not say anything about them being simultaneous. The examples confirmed that and the user can see that the transformations in the examples are done in order and not simultaneously.
