### ISSUE TITLE
Missing Test Case - 341. Flatten Nested List Iterator

### ISSUE THREAD

**Issue by jianli0** [LeetCode-Feedback/LeetCode-Feedback#5623]
very minor, but in the `similar problem` of this problem, it is a similar problem to itself.

**Comment by LC-Sue** [comment]
Hi @jianli0 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jianli0 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
