### ISSUE TITLE
Regarding the Tail Recursion in Java code

### ISSUE THREAD

**Issue by ppm10103** [LeetCode-Feedback/LeetCode-Feedback#5624]
Your LeetCode username
ppm10103

Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases

Description of the bug
Tail Recursion 
https://leetcode.com/explore/learn/card/recursion-i/256/complexity-analysis/2374/
Whether the Java code sample is only used for a theoretical demonstrate？

It looks like that Java8 does not directly support TCO at the compiler level.

![image](https://user-images.githubusercontent.com/4432983/147321935-ac163a8e-afbd-42b1-a855-bfdc836376e4.png)
![image](https://user-images.githubusercontent.com/4432983/147321946-19cd3564-535b-4e58-8266-883cbe51fbe3.png)

**Comment by LC-Sue** [comment]
Hi @ppm10103 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ppm10103,
Thank you for your time. ou are correct, Java 8 (and Python) do not support TCO. This is stated in the last two sentences of the page in question. You are correct in assuming that the presented code is purely for demonstration purposes to help understand the difference between what tail-end-recursive and non-tail-end-recursive code look like. That said, TCO can be implemented in Java and Python using lambda functions, but how to do so is outside the scope of this explore card.
