### ISSUE TITLE
Missing Test Case - 1582. Special Positions in a Binary Matrix

### ISSUE THREAD

**Issue by amitmukhiya** [LeetCode-Feedback/LeetCode-Feedback#5626]
#### Your LeetCode username
Troy_01

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Everything is right except the image shown in example 2 is not correct. mat[2][0] should be 0.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @amitmukhiya 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @amitmukhiya,
Thank you for your time. The issue has already been fixed previously!
