### ISSUE TITLE
Missing Test Case - 495. Teemo Attacking

### ISSUE THREAD

**Issue by greenblade29** [LeetCode-Feedback/LeetCode-Feedback#5627]
#### Your LeetCode username
milapanwani

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Wrong code is getting accepted as the problem is missing some testcases, Pattern of the missing test cases goes like - 
[0,2 4,5], duration = 2;
[0,3,6,9], duration = 5;
Basically any testcase in which timeseries is starting from 0 and there's not any succeeding 1 and any testcase which has duration 1.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findPoisonedDuration(vector<int>& timeSeries, int duration) {
        int ans=0,t=0;
        for(auto x: timeSeries){
            if(x>t){
                ans+= duration;
                t= x+duration-1;
            }
            else{
                ans+= x==0 ? 1 : (x+duration-1)-t;
                t= x+duration-1;
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

**Comment by LC-Sue** [comment]
Hi @greenblade29 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @greenblade29 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
