### ISSUE TITLE
Walking Robot Simulation II (2069): Compile error with C++

### ISSUE THREAD

**Issue by aryanshridhar** [LeetCode-Feedback/LeetCode-Feedback#5629]
#### Category of the bug
- [x] Error
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When compiling any correct C++ code it throws an error saying - 
```
Line 148: Char 18: error: no member named 'step' in 'Robot'
            obj->step(
            ~~~  ^
1 error generated.
```

#### Code you used for Submit/Run operation

Doesn't matter in this case.
Solutions previously accepted aren't compiling due to the above mentioned issue.

#### Language used for code
C++

#### Expected behavior

The code should get compiled!

**Comment by LC-Sue** [comment]
Hi @aryanshridhar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @aryanshridhar,
Thank you for your time. The function move was changed to be step. Please reset the code before implementing it.
