### ISSUE TITLE
357. Count Numbers with Unique Digits – missing test cases

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#563]
#### Your LeetCode username
metricquant

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The question does not mention an upper bound for `n`, yet only tests values that are no larger than `9`. The question still makes sense for unbounded `n`. Moreover, a correct solution should handle the case `n >= 10`.

#### Code you used for Submit/Run operation
This solution passes the test:
```
class Solution {
public:
    int countNumbersWithUniqueDigits(int n) {
        if(n == 0)
            return 1;
        
        if(n >= 9)
            return 0;
        
        int count = 10;
        
        int a = 9, b = 9;
        for(int i = 2; i <= min(10, n); i++) {
            a *= b;
            count += a;
            b -=1;
        }
        
        return count;
    }
};
```

The statement `if(n >= 9) return 0;` returns the wrong answer for `n >= 9`.

#### Language used for code
C++

#### Expected behavior
Test that `n = 10` and a couple of values `n > 10` all return `8877691` as an answer.

**Comment by lc-kate** [comment]
Hi @metricquant ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @metricquant ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
