### ISSUE TITLE
🚨 请不要悄无声息地关掉 issues 5604; Please do not close issues without any response.

### ISSUE THREAD

**Issue by kaiwensun** [LeetCode-Feedback/LeetCode-Feedback#5630]
**你的 LeetCode 用户名**
N/A

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
详见 https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/5604

**你使用的语言**
N/A

**你提交或者运行的代码**
N/A

**期望行为**
详见 https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/5604

**屏幕截图**
N/A

**额外的上下文**
详见 https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/5604

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by LC-Sue** [comment]
Hi @kaiwensun,
Thank you we've received the feedback. The problem title was changed due to internal reason. We’re sorry that we can’t change the problem title. Apologize again for the inconvenience
