### ISSUE TITLE
Wrong Test Case - 227. Basic Calculator II

### ISSUE THREAD

**Issue by ZouvikPan** [LeetCode-Feedback/LeetCode-Feedback#5632]
#### Your LeetCode username

Zouvik_Pan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Wrong Test Cases 

#### Description of the bug

In the question named **227. Basic Calculator II**, this is a wrong test case that is present.
_Given Testcase:_ "1+2\*5/3+6/4\*2"
_Correct answer:_ 5
_Given answer:_ 6
For solving this equation following are the steps taken:
Given equation,
= 1+2\*5/3+6/4\*2
= 1+2\*1+1\*2   (Question description says, "integer division should truncate toward zero". Hence 6/4 & 5/3 will be 1)
= 1+2+2
= 5
I think the question's description should mention explicitly what is the order to be followed while simplifying the given equation otherwise it can cause ambiguity when multiplication and division are present together.
For eg- ```3/2 * 2``` and ```2 * 3/2``` would give different solutions 2, 3 respectively if we consider the **[DMAS](https://en.wikipedia.org/wiki/Order_of_operations)** (click on the link to know more about DMAS) rule in which multiplication and division have the same priority although these two equations are essentially the same.
#### Code you used for Submit/Run operation

```python
import re
class Solution(object):
    def calculate(self, s):
        """
        :type s: str
        :rtype: int
        """
        s="".join(s.split())
        nums=list(map(int,re.split('\+|-|/|\*',s)))
        operators=list(map(str,re.split("[\w']+",s)))
        while('' in operators):
            operators.remove('')
        i=0
        while(i<len(operators)):
            if(operators[i]=='/'):
                nums[i]=nums[i]//nums[i+1]
                del nums[i+1]
                del operators[i]
                i-=1
            i+=1
        i=0
        while(i<len(operators)):
            if(operators[i]=='*'):
                nums[i]=nums[i]*nums[i+1]
                del nums[i+1]
                del operators[i]
                i-=1
            i+=1
        i=0
        while(i<len(operators)):
            if(operators[i]=='-'):
                nums[i]=nums[i]-nums[i+1]
                del nums[i+1]
                del operators[i]
                i-=1
            i+=1
        i=0
        while(i<len(operators)):
            if(operators[i]=='+'):
                nums[i]=nums[i]+nums[i+1]
                del nums[i+1]
                del operators[i]
                i-=1
            i+=1
        return nums[0]
```

#### Language used for code

Python

#### Expected behavior

The correct output of the above test case is 5, but the output given in the test case is 6. My code provides the correct output 5, but since the test case expects the output to be 6, it gives me the verdict as Wrong answer.

#### Screenshots

![image](https://user-images.githubusercontent.com/42470856/147378369-925d15d9-a918-48b7-92fe-256af16210d7.png)

**Comment by stormsunshine** [comment]
The expected output should be 6.

The test case "1+2*5/3+6/4*2" is calculated as follows.
```
  1 + 2 * 5 / 3 + 6 / 4 * 2
= 1 + 10 / 3 + 1 * 2
= 1 + 3 + 2
= 6
```
Multiplication and division have the same priority. Why do you think division should be calculated before multiplication?

**Comment by ZouvikPan** [comment]
I think the question's description should mention explicitly what is the order to be followed while simplifying the given equation otherwise it can cause ambiguity when multiplication and division are present together. 
For eg- ```3/2 * 2``` and ```2 * 3/2``` would give different solutions 2, 3 respectively if you consider that multiplication and division have the same priority although these two equations are essentially the same.

**Comment by trangology** [comment]
@ZouvikPan I do think it's unnecessary to explicitly mention the order to be followed when the given expression contains multiplication & division are present together. Since it's obvious how we learn to calculate an expression at school, multiplication & division have the same priority if no brackets are present.

Also, the example  `3/2 * 2` and `2 * 3/2` you've mentioned seem the same when you have spaces between numbers & operators. However, if you see example 3 in the description whose input ` 3+5 / 2 ` & output `5`, you could get that we should calculate `5/2` first, then add the result with 3. So, spaces are not counted as indications of priorities and your example is not proof in this case.

**Comment by ZouvikPan** [comment]
@trangology The number of spaces anyway does not matter as the question mentions that the operators and the numbers are separated by some number of spaces and we have to evaluate the equation that we get after removing such spaces. It was for us to see that `3/2 * 2` and `2 * 3/2` are essentially the same equation that I had added spaces for more clarity.
Hence for our code, `3/2 * 2` and `2 * 3/2` will be `3/2*2` and `2*3/2` (all spaces removed).
If we solve this considering that multiplication and division have the same priority then we will get different answers i.e 2, 3 respectively although these two equations are fundamentally the same.
If the case of `3/2 * 2` and `2 * 3/2` is being difficult to understand we can try another set of equations like :
-  `3 * 5/3` and `5/3 * 3`
 Here both the equations are essentially the same (just the order of writing them is different), i.e 3*(5/3) or (5/3)*3 in both cases the answer should be 5. But if we consider that multiplication and division have the same priority then we will get solutions 5 and 3 respectively.
**This kind of ambiguity is caused by the use of multiplication by juxtaposition and using the slash to represent division. In general, the surest way to avoid ambiguity is to use parentheses (as done in the above example).** For more clarity you can check the different ambiguities on  [this link from Wikipedia](https://en.wikipedia.org/wiki/Order_of_operations). Wikipedia also acknowledges this ambiguity and it sometimes depends on the way the calculators are implemented.

**Comment by LC-Sue** [comment]
Hi @ZouvikPan 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out. The question description mentions "The integer division should truncate toward zero." Please do let me know if you have any other questions!
