### ISSUE TITLE
Article Issue - 826. Most Profit Assigning Work

### ISSUE THREAD

**Issue by azhar1038** [LeetCode-Feedback/LeetCode-Feedback#5636]
#### Your LeetCode username

mdAzhar

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Python Solution provided in Article, there is error in line 4: `jobs.sort()`  
`jobs` is a `zip` object which doesn't have `sort` method.  
Correct line is: `jobs = sorted(jobs)`

Correct complete code:
```python
class Solution(object):
    def maxProfitAssignment(self, difficulty, profit, worker):
        jobs = zip(difficulty, profit)
        jobs = sorted(jobs)
        ans = i = best = 0
        for skill in sorted(worker):
            while i < len(jobs) and skill >= jobs[i][0]:
                best = max(best, jobs[i][1])
                i += 1
            ans += best
        return ans
```

#### Language used for code
Python 3

**Comment by LC-Sue** [comment]
Hi @azhar1038,
Thank you for reaching out to us. The solution article for this problem was written in python which composes correctly. The error you mentioned occurs in python 3 which differs from python. Apologies for any confusion!
