### ISSUE TITLE
Article Issue - 1153. String Transforms Into Another String

### ISSUE THREAD

**Issue by lebegio** [LeetCode-Feedback/LeetCode-Feedback#5637]
#### Your LeetCode username
lebegio

#### Category of the bug
- [ ] Question
- [ ] Solution
- [+ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a problem with c++ debugger(Premium Mode). Original function takes two strings as arguments str1 and str2
(e.g. testcase str1 = "a" and str2 = "b"). However when I try to debug this tastcase, instead of that input I have str1="a\\"" and str2 = "b". So the character \\" is always appended at the end of the first string.
I managed to reproduce that issue only for c++ debugger. It reproduces for all testcases.

#### Code you used for Submit/Run operation

```
// String Transforms Into Another String
class Solution {
public:
     bool canConvert(string str1, string str2) {
        if(str1 == str2) return true;
        vector<int> mp(26, -1);
        for(int i = 0;i<str1.size();i++){
            int poz = str1[i] - 'a';
            int value =  (str2[i] - 'a');
            
            if(mp[poz] == -1) mp[poz] = value;
            else if(mp[poz] != value) 
                return false;
        }
        vector<int> cnt(26);
        for(int i = 0;i<26;i++){
            if(mp[i] < 0) continue;
            int p = i;
            while(mp[p] >= 0 && cnt[p] < 2){
                cnt[p]++;
                p = mp[p];
            }
        }
        for(int i = 0;i<26;i++){
            if(cnt[i] != 2) {
                return true;
            }
        }
        return false;
 }

};
```

#### Language used for code

C++

#### Expected behavior

I'd extpect exactly the same input for debug mode as for standard run.

#### Screenshots

Original input
![image](https://user-images.githubusercontent.com/81999368/147388977-73051e3b-5852-45a1-a7f4-bde0c1d9a920.png)

Debugger input
![image](https://user-images.githubusercontent.com/81999368/147389000-e5a9d8d7-cd8d-4440-893c-20fe9ce7e785.png)

**Comment by LC-Sue** [comment]
Hi @lebegio,
Thank you for reaching out to us, does this issue reproduce when you submit the code? It is common that outputs from "Run Code" and "Submit" to be different. The reasons are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by lebegio** [comment]
Hi @LC-Sue ,
as it mensioned in bug description this issue was only reproduced in DEBUG mode. For all testcases(custom and default). Please checkout screenshots. Also as I can see right now it's already fixed, could not reproduce it anymore. Now in debug mode there is no extra character appended at the end of the first string.

**Comment by LC-Sue** [comment]
Hi @lebegio,
Thank you for your time, sorry I couldn't get to you sooner but I am glad to see that the issue has been resolved!
