### ISSUE TITLE
Missing Test Case - 2116. Check if a Parentheses String Can Be Valid

### ISSUE THREAD

**Issue by Sushanto** [LeetCode-Feedback/LeetCode-Feedback#5639]
#### Your LeetCode username
5u5h4n70

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Due to missing test case, code without proper solution got accepted.
Consider below test case-
"(((()())))()(())"
"1111011111111111"
For this test case, answer should be true, but below code is giving output as false. And still the solution was accepted.
Just want to contribute this test case to give more coverage to this question.

#### Code you used for Submit/Run operation

```
class Solution {
    fun canBeValid(s: String, locked: String): Boolean {
        val opener = IntArray(s.length) {0}
        val closer = IntArray(s.length) {0}
        var prev = 0
        s.forEachIndexed{idx, it ->
            if (locked[idx] == '1' && it == '(') {
                prev++
            }
            opener[idx] = prev
        }
        prev = 0
        for (i in s.length - 1 downTo 0) {
            if (locked[i] == '1' && s[i] == ')') {
                prev++
            }
            closer[i] = prev
        }
        val stack = Stack<Char>()
        s.forEachIndexed{idx, it ->
            if (locked[idx] == '0') {
                if (closer[idx] < opener[idx] && stack.isNotEmpty() && stack.peek() == '(') {
                    stack.pop()
                } else {
                    stack.push('*')
                }
            } else {
                if (it == '(') {
                    stack.push(it)
                } else {
                    if (stack.isEmpty()) return false
                    if (stack.peek() == '(' || stack.peek() == '*') {
                        stack.pop()
                    }
                }
            }
        }
        if (stack.size % 2 != 0) return false
        val stack2 = Stack<Char>()
        while (stack.isNotEmpty()) {
            val c = stack.pop()
            if (c == '(' && stack2.isNotEmpty() && stack2.peek() == '*') {
                stack2.pop()
            } else {
                stack2.push(c)
            }
        }
        return stack2.size % 2 == 0 && stack2.all { it == '*' }
    }
}
```

#### Language used for code
Kotlin

#### Expected behavior
Expectation - Above code should be rejected as expected answer is true
Actual - Above code was accepted even though output is false.

#### Screenshots

![image](https://user-images.githubusercontent.com/13949911/147389770-05a809de-0933-42d3-9a06-bc7653332e36.png)

**Comment by LC-Sue** [comment]
Hi @Sushanto 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Sushanto,
Thank you for your time, the solution failed after supporting the test set with more test cases! So we did not add the test case.
