### ISSUE TITLE
864. Shortest Path to Get All Keys

### ISSUE THREAD

**Issue by Kartik97** [LeetCode-Feedback/LeetCode-Feedback#564]
#### Your LeetCode username

jainkartik97

#### Category of the bug
- [*] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Wrong Expected output.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int bfs(vector<string>& grid,vector<pair<int,int>>& st,int k){
        vector<vector<unordered_set<int>>> vis(grid.size(),vector<unordered_set<int>>(grid[0].size()));
        int done=(1<<k)-1;
        queue<vector<int>> q;   // x,y,length,mask
        for(auto i:st)
            q.push({i.first,i.second,0,0});
        while(!q.empty()){
            auto t=q.front();
            q.pop();
            int x=t[0],y=t[1];
            if(x<0 || y<0 || x>=grid.size() || y>=grid[0].size() || grid[x][y]=='#' || vis[x][y].find(t[3])!=vis[x][y].end())
                continue;
            if(grid[x][y]>='A' && grid[x][y]<='F'){
                if((t[3]&(1<<(grid[x][y]-'A')))==0)
                    continue;
            }

            if(t[3]==done)
                return t[2]-1;            
            if(grid[x][y]>='a' && grid[x][y]<='f')
                t[3] |= 1<<(grid[x][y]-'a');
            
            vis[x][y].insert(t[3]);
            q.push({x+1,y,t[2]+1,t[3]});
            q.push({x,y+1,t[2]+1,t[3]});
            q.push({x-1,y,t[2]+1,t[3]});
            q.push({x,y-1,t[2]+1,t[3]});
        }
        return -1;
    }
    
    int shortestPathAllKeys(vector<string>& grid) {
        int k=0;
        vector<pair<int,int>> st;
        for(int i=0;i<grid.size();i++){
            for(int j=0;j<grid[0].size();j++)
                if(grid[i][j]=='@')
                    st.push_back({i,j});
                else if(grid[i][j]>='a' && grid[i][j]<='f')
                    k++;
        }
        
        return bfs(grid,st,k);
    }
};
```

#### Language used for code
C++

#### Expected behavior

Expected output was wrong for the below test case:
["@ # @ a A"," . . B # # "," . . . . b"]
Expected output: -1
Whereas the actual output should be: 11

#### Screenshots

![Screenshot from 2020-07-01 01-13-26](https://user-images.githubusercontent.com/21237766/86170001-1d28d780-bb38-11ea-8a41-3526d757d3c8.png)

#### Additional context

The given input is and we need shortest path:
@ # @ a A
.   .   B  # #
.   .   .   .  b
The path exists from (0,0)-(1,0)-(2,0)-(2,1)-(2,2)-(2,3)-(2,4)-(2,3)-(2,2)-(1,2)-(0,2)-(0,3)

**Comment by lc-kate** [comment]
Hi @Kartik97 ,
Thank you for reaching out to us. I've just tested your code in the mentioned test case and received AC for Run Code (please see the attached screenshot for this result). This result is not the same as the one displayed in your screenshot. Would you mind taking a second look at it, please?
<img width="792" alt="Screen Shot 2020-07-02 at 10 11 06 PM" src="https://user-images.githubusercontent.com/59751300/86434011-24272580-bcb1-11ea-9f8a-362a083255d5.png">

**Comment by Kartik97** [comment]
@lc-kate Hi, there was a typo in the test case (because of '@' symbol someone got tagged), I have updated the test case. Can you please check it again? The expected output is wrong. It should be 11.

**Comment by lc-christina** [comment]
hi @Kartik97 ,
Thanks for updating the test case. The problem has probably been updated thanks to other user's feedback and it now shows invalid testcase. Thank you for your support and please don't hesitate to let me know if you have any other questions.
