### ISSUE TITLE
Missing Test Case - 227. Basic Calculator II

### ISSUE THREAD

**Issue by devkapilbansal** [LeetCode-Feedback/LeetCode-Feedback#5640]
#### Your LeetCode username

devkapilbansal

#### Category of the bug
- [ ] Question
- [ ] Language

#### Description of the bug

Hi,
In this question, we are given that division can be truncated to zero.

I used following expression to understand it:
`"2*3/2"`

This was evaluated to 3.However, if I do division first, then it should be 2 instead.

```
> 2*(3/2)
> 2*1
> 2
```

**Comment by LC-Sue** [comment]
Hi @devkapilbansal,
Thank you for reaching out to us. When the given expression in which multiplication and division are present together. Multiplication & division have the same priority if no brackets are present. Hence it could be 
> 2*3/2
> 6*2
> 3
