### ISSUE TITLE
Typo in Solution of #347

### ISSUE THREAD

**Issue by ritwik12** [LeetCode-Feedback/LeetCode-Feedback#5643]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typo in the solution of problem **347. Top K Frequent Elements**

##### Approach 2: Quickselect (Hoare's selection algorithm)
It has O(N) average time complexity and widely used in practice. It worth to note that its worth case time complexity is O(N^2), although the probability of this worst-case is negligible.

##### Approach 2: Quickselect (Hoare's selection algorithm)
It has O(N) average time complexity and is widely used in practice. It is worth noting that its worst-case time complexity is O(N^2), although the probability of this worst-case is negligible.

**Comment by LC-Sue** [comment]
Hi @ritwik12 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ritwik12 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
