### ISSUE TITLE
Missing Test Case - 2117. Abbreviating the Product of a Range (Standard Solution Failed)

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#5648]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The *standard solution* gets Wrong Answer on the following testcase:
184
70145

#### Expected behavior

The first few digits of the actual answer should be 39118000000000236, but the standard solution outputs 39117 as the first five digits.

#### Additional context

I guess that the standard solution used double, which does not have enough precision in the worst case.

**Comment by LC-Pamela** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hqztrue,
Thank you for your time. We are aware that the current constraints may present precision errors in some languages and some solutions. The problem will be updated soon. Thank you for your patience and for providing the feedback.
