### ISSUE TITLE
127. Word Ladder 

### ISSUE THREAD

**Issue by zen-coder** [LeetCode-Feedback/LeetCode-Feedback#565]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

**There is an unstated assumption in the problem.**  All words have length M. There are N words. The unstated assumption is M << N, meaning M is very small compared to N. 

"Naive" BFS is O(M x N x N)
Solution approaches are O(M x M x N)

So given that, unlike normal competitive programming, we are not given input sizes, neither is better.
If I test with few very long word, the "naive" algorithm is going to be much faster. So there is an unstated assumption as of the writing of this comment.

This assumption is clearly made by the Testing code as I recieved this error message when trying to test very long words:

> expected 'beginWord' to have 1 <= size <= 100 but got 999

Another point, with reasonably optimized code, "naive" BFS will pass all test in C++, and this by a pretty good margin.

**Comment by lc-kate** [comment]
Hi @zen-coder ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @zen-coder ,
Thank you for your time. Base on our current standard, we will not perform this operation. We appreciate your contribution.

**Comment by zen-coder** [comment]
"Base on our current standard" --> What standard? Without this assumption the answer is simply false. 
All you have to do is to actually write in the problem description the constaint assumed by the testing code: 

`expected 'beginWord' to have 1 <= size <= 100 but got 999
`

**Comment by lc-kate** [comment]
@lc-christina
