### ISSUE TITLE
Wrong Test Case - 2122. Recover the Original Array

### ISSUE THREAD

**Issue by pribic** [LeetCode-Feedback/LeetCode-Feedback#5654]
#### Your LeetCode username
priyank-doshi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

For test case ```[1,1,3,3]```, you say correct ans is ```[2,2] with k = 1```. But even ```[1,3] with k = 0``` should be considered a valid ans.

**Comment by stormsunshine** [comment]
Could you please read the problem carefully? The chosen `k` must be a positive integer. Is 0 a positive integer?

**Comment by LC-Sue** [comment]
Hi @pribic,
Thank you for reaching out to us, did you still have any questions after reading stormsunshine's comment? Please do let me know if you have any other questions!

**Comment by LC-Sue** [comment]
Hi @pribic 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
