### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by deafTim** [LeetCode-Feedback/LeetCode-Feedback#5659]
#### Your LeetCode username

My name is TIENTI0000.

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

#### Description of the bug

I found a missing test case or we can say test cases, so it allows to be accepted to my wrong code.
We should add for example test case [1,1], pos=0
My wrong code shows that this case doesn't have cycles, however, it has. And this code is accepted.
So we should add test cases with the same values, coming one after another for example [3,3,3] or [2,2,5]
I wrote 2 wrong and 2 right (commented) lines in the code below.
Also, I attached screenshots.

#### Code you used for Submit/Run operation
```
class Solution(object):
	def hasCycle(self, head):
		"""
		:type head: ListNode
		:rtype: bool
		"""
		if head == None or head.next == None:
			return False        
		if head == head.next:
			return True
		slow = head
		fast = head.next
		# while fast!=slow: # It should be this way
		while fast.val!=slow.val:      # Wrong but Accepted
			if fast.next==None or fast.next.next==None:
				return False
			fast = fast.next.next
			slow = slow.next
			# if fast==slow:      # It should be this way
			if fast.val==slow.val:      # Wrong but Accepted
				return True
		return False
```

#### Language used for code

Python

#### Expected behavior

Test cases should be added

#### Screenshots

![image](https://user-images.githubusercontent.com/18631075/147422487-f99cb04e-5ed3-43ff-869d-c1ce12e4458d.png)
![image](https://user-images.githubusercontent.com/18631075/147422492-ae1d7c6d-a2f4-4637-9d7d-b059cb2bb541.png)

**Comment by LC-Sue** [comment]
Hi @deafTim 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by deafTim** [comment]
> 

thanks

**Comment by deafTim** [comment]
>

**Comment by LC-Sue** [comment]
Hi @deafTim 
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username?

**Comment by deafTim** [comment]
TIENTI0000
***@***.***

**Comment by LC-Sue** [comment]
Hi @deafTim,
Unfortunately, I am unable to find an account associated to the username 'TIENTI0000' as an alternative you could also provide your associated email!

**Comment by deafTim** [comment]
> Hi @deafTim, Unfortunately, I am unable to find an account associated to the username 'TIENTI0000' as an alternative you could also provide your associated email!

tglukhikh@gmail.com

**Comment by deafTim** [comment]
@LC-Sue tglukhikh@gmail.com

**Comment by LC-Sue** [comment]
Hi @deafTim 
Thank you for your time. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
