### ISSUE TITLE
825. 适龄的朋友——缺少测试用例

### ISSUE THREAD

**Issue by secondhh2** [LeetCode-Feedback/LeetCode-Feedback#5660]
**你的 LeetCode 用户名**
secondhh2

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [√] 缺少测试用例

**描述**
825. 适龄的朋友
测试用例有缺陷，导致我的错误代码能正确通过。

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    int numFriendRequests(vector<int>& ages) {
        sort(ages.begin(), ages.end());
        int res = 0;
        for(int i = 0; i < ages.size(); ++ i)
        {
            int l = 0, r = ages.size() - 1;
            //if(ages[r] <= 0.5 * ages[i] + 7) continue;  此处去掉注释即为正确代码
            while(l < r)
            {
                int mid = l + r >> 1;
                if(ages[mid] <= 0.5 * ages[i] + 7) l = mid + 1;
                else r = mid;
            }
            int left = l;
            l = 0, r = ages.size() - 1;
            while(l < r)
            {
                int mid = l + r + 1 >> 1;
                if(ages[mid] > ages[i]) r = mid - 1;
                else l = mid;
            }
            int right = l;
            res += max(right - left + 1, 0);
            if(right >= left && right >= i && left <= i) res --;
        }
        return res;
    }
};
```

**期望行为**
测试用例为[14, 14]
期望输出为0，错误代码给出的结果为1

**屏幕截图**
![image](https://user-images.githubusercontent.com/75720458/147428712-77cc5f98-e960-4d60-92a4-caa0a2bba3a6.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by LC-Sue** [comment]
Hi @secondhh2 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @secondhh2 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
