### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by AhmadKhasanweh** [LeetCode-Feedback/LeetCode-Feedback#5661]
#### Your LeetCode username
ahmed6569

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I think Find Peak Element solved using solutions may not be accurate, when the array elements is sorted technically the peak would be the last element. I submitted my solution and passed though giving wrong answer in test case below. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int findPeakElement(int[] nums) {
        int low=0;
        int high=nums.length-1;
        while (low<high) {
            int mid = low+(high-low)/2;
            if (nums[mid]<nums[mid+1]) {
                low = mid+1;
            } else {
                high = mid;
            }
        }
        return low;
    }
}
```

#### Language used 
Java

#### Expected behavior

int[] nums = {1,2,3,4,5,6,7,8,9};
-> Peak should be 9 
-> Actual answer is 8

**Comment by stormsunshine** [comment]
Why do you think the answer should be 9? This problem requires returning the **index** of the peak element.

**Comment by LC-Sue** [comment]
Hi @AhmadKhasanweh,
Thank you for reaching out to us, the code you provided was accepted. I've attached a screenshot below for your reference. Please feel free to reach out if you have any other questions!
![image](https://user-images.githubusercontent.com/92285126/147616991-afbf93b7-ca52-41dc-892c-e07b5d7dccbf.png)
