### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by BaktiyarJakshylykov** [LeetCode-Feedback/LeetCode-Feedback#5666]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?

In fact, there are at most 3999 test cases for problem 13, and there are already 3999 test cases. Therefore, there is no missing test case for problem 13.

Don't create meaningless issues!

**Comment by LC-Sue** [comment]
Hi @BaktiyarJakshylykov 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
