### ISSUE TITLE
Missing Test Case - 1296. Divide Array in Sets of K Consecutive Numbers

### ISSUE THREAD

**Issue by keaising** [LeetCode-Feedback/LeetCode-Feedback#5668]
#### Your LeetCode username

Shuxiao

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The missed test case

```
[1,2,2,3,4,4,5,6,7,7,8,9]
4
```

#### Code you used for Submit/Run operation

This solution should be wrong, but it passed all test and ranked 1st in speed.

```

func isPossibleDivide(nums []int, k int) bool {
	sort.Ints(nums)
	buckets := make([]int, k)
	for i := 0; i < len(nums); i++ {
		if i%k != 0 && nums[i]-nums[i-1] > 1 {
			return false
		}
		buckets[nums[i]%k]++
	}

	for _, bucket := range buckets {
		if bucket != buckets[0] {
			return false
		}
	}
	return true
}

```

#### Language used for code

Go

#### Expected behavior

The solution should not pass the test, but test cases are not enough

**Comment by LC-Sue** [comment]
Hi @keaising 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @keaising 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
