### ISSUE TITLE
33. Search in Rotated Sorted Array, Error in solution slides

### ISSUE THREAD

**Issue by Meowzz95** [LeetCode-Feedback/LeetCode-Feedback#5669]
#### Your LeetCode username
jjzzzmd

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

![image](https://user-images.githubusercontent.com/22430379/147522698-9eaa6a40-22ce-4dfc-92a7-e71d4f6ab604.png)
I believe in the first slide, step 4, it should be `1<8` instead of `1>8`

#### Code you used for Submit/Run operation

NA

#### Language used for code

NA

#### Expected behavior

NA

#### Screenshots

Provided above

#### Additional context

NA

**Comment by LC-Sue** [comment]
Hi @Meowzz95 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Meowzz95 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
