### ISSUE TITLE
Missing Test Case - 1049. Last Stone Weight II

### ISSUE THREAD

**Issue by tmohan2399** [LeetCode-Feedback/LeetCode-Feedback#5670]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing Test Cases
[2,6]
[2,3,4,5,6,30]
[12,13,14,97,98,99]

#### Code you used for Submit/Run operation
```
var lastStoneWeightII = function(stones) {
    const n = stones.length,
          sum = stones.reduce((acc, cur) => acc + cur, 0);

    let dp = Array(sum), minDiff = stones[0];
    dp[0] = 1;

    for (let i = 0; i < n; i++) {
        for (let j = sum >> 1; j >= stones[i]; j--) {
            dp[j] ||= dp[j - stones[i]];
            if (dp[j])
                minDiff = Math.min(minDiff, sum - 2 * j);
        }
    }

    return minDiff;
};
```

#### Language used for code
JavaScript

#### Expected behavior
This code is accepted, even-though it is giving incorrect answer for some test cases

#### Additional context
[2,6]
[2,3,4,5,6,30]
[12,13,14,97,98,99]
Accepted code is giving incorrect answer, for these test cases

**Comment by LC-Sue** [comment]
Hi @tmohan2399 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by tmohan2399** [comment]
@LC-Sue When will these missing test cases be added?

**Comment by LC-Sue** [comment]
Hi @tmohan2399,
Thank you for your time. We've used your feedback to update the problem.  We'd like to reward you for the contribution, could you please provide your LeetCode username?

**Comment by tmohan2399** [comment]
@LC-Pam 
My leetcode username is tmohan
