### ISSUE TITLE
Missing Test Case - 767. Reorganize String

### ISSUE THREAD

**Issue by tarunteckedge** [LeetCode-Feedback/LeetCode-Feedback#5671]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [] Missing Test Cases 
- [x] Incorrect Test Cases 

#### Description of the bug

The question says that any rearrangement of the string would be accepted as long as no two characters are found together. However, it accepts only a particular solution.  For example, if the test input is: "aabbcc", the accepted answers should have "abcabc" / "acbacb" / "bcabca", whereas the solution accepts only one answer: "abacbc"

**Comment by LC-Sue** [comment]
Hi @tarunteckedge 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @tarunteckedge,
Thank you for your time. For input "aabbcc", all the mentioned answers are accepted.
