### ISSUE TITLE
This should be hard category, not medium.

### ISSUE THREAD

**Issue by ppujari** [LeetCode-Feedback/LeetCode-Feedback#5673]
31. Next Permutation, it should be hard category.

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
I don't think problem 31 is a hard problem. The difficulty is not that high.

**Comment by LC-Sue** [comment]
Hi @ppujari,
Thank you for reaching out to us. The difficulty of the problem is set by our content team after careful consideration! Apologies for any inconvenience caused!
