### ISSUE TITLE
191. Number of 1 Bits, C# unit test case bug

### ISSUE THREAD

**Issue by vikscool** [LeetCode-Feedback/LeetCode-Feedback#5674]
#### Your LeetCode username

vikscool97

#### Category of the bug
- [ ] Question
- [-] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The compiler used for `C#` in the website is bugged and produces the wrong answers for specific unsigned integers.

#### Code you used for Submit/Run operation

```
// 191. Number of 1 Bits
public class Solution {
    public int HammingWeight(uint n) {
        char ch = '1';
	return n.ToString().Count(ct=>(ct==ch));
    }
}
```

#### Expected behavior

As per the written code, it outputs the count of number `1` in any given unsigned 32-byte integer. The code gives proper output for most of the test cases mentioned by using .Net framework version 4.7.2 and also in .Net 6 on my local as well as other online compilers. But when used the same code over the **leetcode** website it produces a different output and the answer generated by code is marked as wrong.

#### Screenshots

With .Net v 4.7.2
![compiler_4_7_2](https://user-images.githubusercontent.com/7845452/147548412-e75abc36-099b-4234-ba4a-b8303dd75689.jpg)

With .Net 6
![compiler_Net_6](https://user-images.githubusercontent.com/7845452/147548442-19ad5a0c-bc0a-415f-865e-8872a49544aa.jpg)

LeetCode:
![leetcode](https://user-images.githubusercontent.com/7845452/147548532-9a83ea45-68ed-455a-b6d8-4f9ee24c7a4a.jpg)

#### Additional context

As per my understanding, it looks like there is an additional validation method used over the actual method `HammingWeight()`, which is trimming the input unsigned integer and producing a false output for some use cases.

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
