### ISSUE TITLE
Missing Test Case (Standard Solution Also Fails) - 2117. Abbreviating the Product of a Range

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5675]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For problem [2117. Abbreviating the Product of a Range](https://leetcode.com/problems/abbreviating-the-product-of-a-range), a solution that gets accepted fails on one test case.

The test case is as follows.
```
468620
595075
```

The correct answer for the test case is "16557...51744e31618", since the highest digits of the actual result are 1655700000000000135..., where the highest five digits are 16557.

The standard solution also fails on the test case, since the standard solution outputs: "16556...51744e31618".

The highest five digits of the actual result are 16557, not 16556. Therefore, the output of the standard solution should start with "16557".

#### Code you used for Submit/Run operation
```
class Solution {
public:
    using ll = long long;
    static constexpr ll M = 10'000'000'000;
    
    bool mul_mod_rec(ll & tmp, int op)
    {
        tmp *= op;
        if (tmp>M) {
            tmp %= M;
            return 1;
        }
        return 0;
    }
    string abbreviateProduct(int left, int right) {
        
        ll mul = 1; 
        int zeros = 0;
        bool overflow = false;
        ll pre = 0;
        long double lg = 0;
        {   
            int cnt2 = 0, cnt5=0;
            for (ll i=left; i<=right; ++i) {
                ll tmp = i;
                while (tmp%2==0) {
                    cnt2++;
                    tmp/=2;
                }
                while (tmp%5==0) {
                    cnt5++;
                    tmp/=5;
                }
                overflow |= mul_mod_rec(mul, tmp);
                lg += log10(i);
            }

            zeros = min(cnt2, cnt5);
            cnt2 -= zeros, cnt5 -= zeros;
            
            while (cnt2--) {
                overflow |= mul_mod_rec(mul, 2);
            }
            while (cnt5--) {
                overflow |= mul_mod_rec(mul, 5);
            }
        }
        
        
        
        
        {
            lg = fmod(lg, 1.0);
            lg = pow(10, lg);
            int ct = 0;
            while (++ct<20 && lg < 10000000)
                lg *= 10;
            pre = (int)lg / 1000;
        }
        
        char ans[100]={};
        
        if (overflow) {
            sprintf(ans, "%lld...%05llde%d", pre,mul%100000,zeros);
        }
        else {
            sprintf(ans, "%llde%d", mul,zeros);
        }
        return string(ans);
    }
};
```

#### Language used for code
C++

#### Expected behavior
The following test case should be added so that the code above will get Wrong Answer for submission.
```
468620
595075
```

#### Additional context
Note that the code above can pass all the test cases for problem 2117 mentioned in previous issues. However, the code still fails on the test case in this issue.

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for reaching out to us, the test case you provided is accepted. I've attached a screenshot below for your reference. Please feel free to let me know if you have any other questions!

![image](https://user-images.githubusercontent.com/92285126/147617815-a021ed18-c3c8-4bb3-861e-fda73b764616.png)
