### ISSUE TITLE
472. Concatenated Words

### ISSUE THREAD

**Issue by SeanShen3** [LeetCode-Feedback/LeetCode-Feedback#5676]
#### Your LeetCode username
ali

#### Category of the bug
- [ ] Solution

#### Description of the bug
As the "Constraints" means, the input array could have empty string(0 <= words[i].length). In this case, every non-empty string concentrated with empty string is the string itself. Therefore, the answer should be all every one except the empty string, like test case 5.

#### Code you used for Submit/Run operation
The code itself is not correct for this problem. But the purpose is to show it can be reproduce. The main point is these line:
```
for word in words:
            if len(word)==0:
                return list(set(words)-set("")) 
```

```
from collections import defaultdict
class Trie:
    def __init__(self):
        self.node = defaultdict(Trie)
        self.isWord = False
    
    def add(self, word):
        trie = self
        for ch in word:
            trie = trie.node[ch]
        trie.isWord = True

    def search(self, word):
        trie = self
        for ch in word:
            if ch not in trie.node:
                return False
            trie = trie.node[ch]
        return trie.isWord

class Solution:
    def findAllConcatenatedWordsInADict(self, words: List[str]) -> List[str]:
        def isConcatenated(u, word):            
            trie = root
            for i in range(u, len(word)):
                if word[i] not in trie.node:
                    return False
                trie = trie.node[word[i]]
                if trie.isWord and isConcatenated(i+1, word):
                    return (i-u+1)!=len(word)
            return True

        root = Trie()
        if len(words)==1:
            return []
        for word in words:
            if len(word)==0:
                return list(set(words)-set(""))            
            root.add(word)

        ans = []
        for word in words:
            if isConcatenated(0, word):
                ans.append(word)        
        return ans
```

#### Language used for code
 Python

#### Expected behavior
The answer should be all every one except the empty string, like test case 5.

#### Screenshots
NA

#### Additional context
NA

**Comment by LC-Sue** [comment]
Hi @SeanShen3,
Thank you for reaching out to us, there is no official solution for this problem. Is the code you provided from the discuss section?

**Comment by LC-Sue** [comment]
Hi @SeanShen3 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
