### ISSUE TITLE
A Faster runtime Python3 solution for LeetCode #200 (Number of Islands)

### ISSUE THREAD

**Issue by IamConstantine** [LeetCode-Feedback/LeetCode-Feedback#5677]
#### Your LeetCode username
constantine786

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
A new faster runtime python solution for the problem [200](https://leetcode.com/problems/number-of-islands) using set. 
My submission which beats ~92% -> [solution](https://leetcode.com/submissions/detail/608522263/)

#### Code you used for Submit/Run operation

```
class Solution:
    def numIslands(self, grid: List[List[str]]) -> int:
        total = 0

        island_coords = {(i, j) for i in range(len(grid)) for j in range(len(grid[0])) if grid[i][j] == '1'}

        def map_island(x, y):
            if not island_coords:
                return
            if (x, y) not in island_coords:
                return

            island_coords.remove((x, y))
            map_island(x + 1, y)
            map_island(x - 1, y)
            map_island(x, y + 1)
            map_island(x, y - 1)

        while island_coords:
            p = island_coords.pop()
            island_coords.add(p)
            map_island(*p)
            total += 1

```

#### Language used for code
Python3

#### Expected behavior
Passes all the given tests cases for the problem [200](https://leetcode.com/problems/number-of-islands).

**Comment by LC-Sue** [comment]
Hi @IamConstantine,
Thank you for reaching out to us, since there is no issue I will close this for now. Thank you for understanding. Please feel free to share your solution in the discuss section of the problem! We appreciate your support!
