### ISSUE TITLE
Missing test case : 459. Repeated Substring Pattern

### ISSUE THREAD

**Issue by duststarr** [LeetCode-Feedback/LeetCode-Feedback#5678]
#### Your LeetCode username

duststarr1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code passed all the 128 test cases and been accepted,
but it's wrong.
"babba" is false, my code will return true.

#### Code you used for Submit/Run operation

```
// Two Sum
bool check(char* s, int i){
  int a = 0, b = i;
  while( *(s+b) ) // cmp first half and last half
    if(s[a++] != s[b++])
      return false;
  b = 0;
  while(a<i) // the middle part
    if(s[a++] != s[b++])
      return false;
  return true;
}
bool repeatedSubstringPattern(char * s){
  int len = strlen(s);
  for(int i=len/2 + len%2; i<len; i++) // from next of half
    if(s[i] == s[0])
      if(check(s, i))
        return true;
  return false;
}
```

#### Language used for code

c

#### Expected behavior

Expected false,but true.

#### Screenshots

No need, it's better to see my submission detial or just try it.

#### Additional context

[My Submission Detail](https://leetcode.com/submissions/detail/607748521/)

**Comment by LC-Sue** [comment]
Hi @duststarr 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @duststarr 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
