### ISSUE TITLE
[279. Perfect Squares] Leetcode solution for Approach 4: Greedy + BFS (Breadth-First Search) has wrong diagram

### ISSUE THREAD

**Issue by Himachallad** [LeetCode-Feedback/LeetCode-Feedback#5679]
#### Your LeetCode username
realhimachallad

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

1. Go to the [solution section](https://leetcode.com/problems/perfect-squares/solution/) of [279. Perfect Squares].
2. Navigate to **Approach 4: Greedy + BFS (Breadth-First Search)**
3. **Step 2** contains `6` and `3` in the queue. For `3`, it's generated as `7-4` and not `7-1`.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots
**Incorrect Image:**
 ![image](https://user-images.githubusercontent.com/20709166/147589393-9250cebc-0d15-42f0-b639-6ed27c283169.png)
**Corrected Image**
 ![image](https://user-images.githubusercontent.com/20709166/147590266-c2e5b176-7105-4c54-8e00-e9409e63649c.png)

**Comment by LC-Sue** [comment]
Hi @Himachallad 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Himachallad 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
