### ISSUE TITLE
Mistake in illustration for Target Sum solution

### ISSUE THREAD

**Issue by byuarus** [LeetCode-Feedback/LeetCode-Feedback#5680]
#### Your LeetCode username
byuarus

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Wrong answer in the illustration for https://leetcode.com/problems/target-sum/solution/ in Approach 3: 2D Dynamic Programming

#### Code you used for Submit/Run operation

```
// Target Sum
// Input: `nums =[2,1,1,2]`, `S = 2`
public class Solution {
    public int findTargetSumWays(int[] nums, int S) {
        int total = Arrays.stream(nums).sum();
        int[][] dp = new int[nums.length][2 * total + 1];
        dp[0][nums[0] + total] = 1;
        dp[0][-nums[0] + total] += 1;
        
        for (int i = 1; i < nums.length; i++) {
            for (int sum = -total; sum <= total; sum++) {
                if (dp[i - 1][sum + total] > 0) {
                    dp[i][sum + nums[i] + total] += dp[i - 1][sum + total];
                    dp[i][sum - nums[i] + total] += dp[i - 1][sum + total];
                }
            }
        }
        System.out.print(Arrays.toString(dp[3]));
        return Math.abs(S) > total ? 0 : dp[nums.length - 1][S + total];
    }
}
```

#### Language used for code
Java

#### Expected behavior
The print from the code above will return [1, 0, 2, 0, 3, 0, 4, 0, 3, 0, 2, 0, 1] which should correspond to the last column in the illustration for `Approach 3: 2D Dynamic Programming` but instead it is [1, 0, 1, 0, 2, 0, 4, 0, 2, 0, 1, 0, 1]. 

#### Screenshots
![Screen Shot 2021-12-28 at 10 43 58 AM](https://user-images.githubusercontent.com/10615444/147598423-b91467ef-2a89-4fb0-b945-33155816f195.png)

#### Additional context

The last column in the illustration represents the number of ways `nums` could sum up to a `sum` (the first column on the left).
For example input: nums = [2,1,1,2], S =  2. 
In the illustration it shows `2` but if you follow the edges of the binary tree in the illustration, you can find 3 ways to sum up nums to get the total sum of `2`:
-2+1+1+2 = 2
+2-1-1+2 = 2
+2+1+1-2 = 2
Therefore the correct answer is 3 for S=2. The same for the rest in the screenshot above.

**Comment by LC-Sue** [comment]
Hi @byuarus 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
