### ISSUE TITLE
Question description is vague - 763. Partition Labels

### ISSUE THREAD

**Issue by sibibiju** [LeetCode-Feedback/LeetCode-Feedback#5688]
#### Your LeetCode username
ksibibiju

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question appears to be vague about how the string should be partitioned, which is causing confusion.

#### Expected behavior
The question should mention that the expected partitions should be contiguous.

**Comment by LC-Sue** [comment]
Hi @sibibiju 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sibibiju 
Thank you for your time. We've added a new paragraph to confirm that the portion is continuous. We appreciate your support!
