### ISSUE TITLE
Wrong Test Case Answer- 485. Max Consecutive Ones

### ISSUE THREAD

**Issue by glitchlover** [LeetCode-Feedback/LeetCode-Feedback#5690]
#### LeetCode username
Shamama Shahrin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
A test case does not accept my code. But I don't under what's wrong with my code. It seems my code is giving acurate ans

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findMaxConsecutiveOnes(vector<int>& nums) {
        int max = 0;
        int tmax = 0;
        for(int i = 0; i<nums.size(); i++){
            if(nums[i] == 1){  
                tmax++;
            }else{
                if(tmax>max){
                    max = tmax;
                    tmax = 0;
                    cout<<tmax<<" "<< i<<endl;
                }
            }
            
        }
        if(tmax>max){
                    max = tmax;
                }
        
        return max;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Expected to be accepted

#### Screenshots
![image](https://user-images.githubusercontent.com/59877631/147642686-de9155cc-6d18-46e3-9e3b-b140f5441147.png)

#### Additional context
here stdout is the value of tmax and value of index of array where 0 is found

**Comment by LC-Sue** [comment]
Hi @glitchlover 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out. Please feel free to refer to the discuss section of the problem to see how others have optimized their codes!
