### ISSUE TITLE
Missing Test Case - 1295. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by testing765** [LeetCode-Feedback/LeetCode-Feedback#5698]
#### Your LeetCode username
moshuni

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An additional test case where an array contains an element equal to zero is recommended. I was able to submit my code below without test failures, although 0 is counted as a 1-digit number. 

#### Code you used for Submit/Run operation
```
class Solution {
    public int findNumbers(int[] nums) {
        int numDigits = 0;
        int numEvenDigits = 0;
        for (int i = 0; i < nums.length; i++) {
            int numStore= nums[i];
            while(numStore != 0){
                numDigits++;
                numStore/=10;
            }
            if (numDigits % 2 == 0) {
                numEvenDigits++;
            }
            numDigits = 0;
        }
        return numEvenDigits;
    }
}
```

#### Expected behavior
It is expected for the submitted code to view 0 as a 1-digit number. However, my code passes all tests although it views 0 to be made up of 0 digits. 

#### Screenshots
N/A

#### Additional context
N/A

**Comment by stormsunshine** [comment]
All elements in the array must be greater than zero. Is there any problem?
