### ISSUE TITLE
1、题目 502 IPO 的官方题解错误，请 @力扣官方题解 重新为该题目写题解 2、期望增加测试用例

### ISSUE THREAD

**Issue by hairman123** [LeetCode-Feedback/LeetCode-Feedback#57]
**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
题目 [502.IPO](https://leetcode-cn.com/problems/ipo/) 的[官方题解](https://leetcode-cn.com/problems/ipo/solution/ipo-by-leetcode/) 有错误，容易误导人。
题目链接：https://leetcode-cn.com/problems/ipo/
官方题解链接：https://leetcode-cn.com/problems/ipo/solution/ipo-by-leetcode/

**错误详细说明**：
1、题目 502 的官方题解的解法一的时间复杂度为 **O(Nlog(N))** ，而不是 O(kNlog(N))。
2、官方题解的 **解法二 不如 解法一**，其时间复杂度 O(kN) 比 解法一 更高。
3、为了验证 官方题解的 解法一 和 解法二 的时间复杂度，可以用一个大规模的测试用例，来测试两种代码的耗时。
4、大规模测试用例一（N = 20000, k = 15000）：
https://github.com/hairman123/data/blob/master/TestCase1
官方题解 解法一（java）：24 ms
官方题解 解法二（java）：1347 ms
大规模测试用例二（N = 30000, k = 25000）：
https://github.com/hairman123/data/blob/master/TestCase2
官方题解 解法一（java）：30～40 ms
官方题解 解法二（java）：超出时间限制
因此，**官方题解的解法一比解法二更优，其时间复杂度是 O(Nlog(N)) 级别的**。

**期望的修复：**
1）希望力扣官方重新写一下 题目 502 的官方题解。首先先看一下官方题解的 **解法一的代码**，时间复杂度是不是 O(Nlog(N))。若是，则解法一比解法二 （O(kN)）一般更优。**建议将 解法一 放在 解法二 之后，并将解法二 改名为 暴力法**。
2）希望题目 502 添加上面的两个大规模测试用例。这是因为：有些人用了类似官方题解 解法 2 的思路，提交后发现运行时间竟然比 解法一 更短，从而错误地认为 解法二 比解法一 更优（而实际上应该是 解法一 更优）。如果增加了上述两个测试用例，则能正确反映 解法一 和 解法二 的实际时间复杂度，让人们对两种的解法哪个更优有一个正确的认识。

**额外的上下文**
题目 502 官方题解 解法一的代码：
```java
class Solution {
  public int findMaximizedCapital(int k, int W, int[] Profits, int[] Capital) {
    // to speed up: if all projects are available
    boolean speedUp = true;
    for (int c: Capital) if (W < c) speedUp = false;
    if (speedUp) {
      PriorityQueue<Integer> heap = new PriorityQueue<>();
      for (int p: Profits) {
        heap.add(p);
        if (heap.size() > k) heap.poll();
      }
      for (int h: heap) W += h;
      return W;
    }

    int n = Profits.length;
    // sort the projects
    // the most available (= the smallest capital) is the head of the heap
    PriorityQueue<int[]> projects = new PriorityQueue<>((x, y) -> (x[0] - y[0]));
    for(int i = 0; i < n; i++) {
      projects.add(new int[] {Capital[i], Profits[i]});
    }

    // max heap
    PriorityQueue<Integer> available = new PriorityQueue<>((x, y) -> (y - x));
    while (k > 0) {
      // update available projects
      while (!projects.isEmpty() && projects.peek()[0] <= W)
        available.add(projects.poll()[1]);

      // if there are available projects,
      // pick the most profitable one
      if (!available.isEmpty()) W += available.poll();
      // not enough capital to start any project
      else break;
      --k;
    }
    return W;
  }
}
```

官方题解 解法二 的代码：
```java
class Solution {
    public int findMaximizedCapital(int k, int W, int[] Profits, int[] Capital) {
        // to speed up: if all projects are available
        boolean speedUp = true;
        for (int c: Capital) if (W < c) speedUp = false;
        if (speedUp) {
            PriorityQueue<Integer> heap = new PriorityQueue<>();
            for (int p: Profits) {
                heap.add(p);
                if (heap.size() > k) heap.poll();    
            }
            for (int h: heap) W += h; 
            return W;
        }
        
        int idx;
        int n = Profits.length;
        for(int i = 0; i < Math.min(k, n); ++i) {
            idx = -1; 
            // if there are available projects,
            // pick the most profitable one
            for(int j = 0; j < n; ++j) { 
                if (W >= Capital[j]) {
                    if (idx == -1 ) idx = j;
                    else if (Profits[idx] < Profits[j]) idx = j;
                }
            }
            // not enough capital to start any project
            if(idx == -1) break;
            
            // add the profit from chosen project
            // and remove the project from further consideration
            W += Profits[idx];
            Capital[idx] = Integer.MAX_VALUE;                
        }
        return  W;
    }
}
```

**Comment by hairman123** [comment]
刚才没写完就按下回车按钮，没写完就提交了

**Comment by hairman123** [comment]
请问这个 issue 为什么快 15 天了都还没有处理？

**Comment by feiceh** [comment]
done

**Comment by feiceh** [comment]
非常抱歉给您带来不便了，因为题目题解涉及到全球，题目运营团队也会按照紧要程度安排更新，因期间同步有误造成的问题我们深表歉意，这边已催促相关部门会尽快处理的。非常感谢您这样的积极用户对力扣网站的支持。如果愿意的话，可以提供一下中文社区的力扣 ID，等更新后会奖励一些 LeetCoin 给您，祝您生活愉快～

**Comment by hairman123** [comment]
其实我理解工作人员维护网站事务繁忙，可能处理不过来，也很感谢有 LeetCode 这样一个能够提高自己的平台。

**如果一开始就说明情况 “因为题目题解涉及到全球，题目运营团队也会按照紧要程度安排更新，这边已催促相关部门会尽快处理的。” ，而不是直接关闭 issue 了事，也不会让反馈的人感到失望。**

**LeetCode 受到欢迎的关键不是因为其功能有多强大、界面有多华丽，而是 LeetCode 平台上有丰富的、优质的内容。** 如果有些内容有错误，尤其时”官方发布“的内容有错误，发现错误的人会怀疑 LeetCode 上的内容质量，而没有发现错误的人可能会被这些错误的解答误导。所以希望 LeetCode 平台能够在发布新内容时，加强内容和翻译的审核，尽量减少发布内容的错误。

**Comment by feiceh** [comment]
非常感谢您这样的积极用户对力扣网站的支持，我们会不断努力优化和提升我们的产品，给大家带来最佳的用户体验。当前题解已经更新成功，您可提供一下中文社区的力扣 ID，我们奖励一些 LeetCoin 给您，祝您生活愉快～

**Comment by hairman123** [comment]
ID：https://leetcode-cn.com/u/newhar/
另外，希望工作人员在有空闲时间时完整地浏览一下文章，它还有几个逻辑上的错误：
1）"时间复杂度为 O(Nlog(N)) 对于这道题目来说不是最佳的。" 这句话是不正确的（难道方法二 O(Nk) 比 O(Nlog(N)) 更优？）；
2）方法二 **不是** 由方法一优化而来。相反，由方法二可以优化到方法一。

**Comment by feiceh** [comment]
好的，此问题已转给题目运营团队会再次确认的～感谢您的支持与反馈，优化内容质量一贯是力扣不遗余力的努力方向，我们会不断努力提升，给大家带来更好的学习社区！积分奉上，稍后可以点击「积分」查看详情，再次感谢您对力扣一贯的支持。
