### ISSUE TITLE
235. Lowest Common Ancestor of a Binary Search Tree

### ISSUE THREAD

**Issue by elulcao** [LeetCode-Feedback/LeetCode-Feedback#570]
#### Your LeetCode username
elulcao

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Basses on the following statement, a node can be descendant of itself. I sent a couple of times the code I shared lines above and all the test cases passed, however, it seems that there are missing test cases where target nodes `p` and `q` are the same.
According to the definition of LCA on Wikipedia: “The lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants (where we allow a node to be a descendant of itself).”

#### Code you used for Submit/Run operation

```java
// Lowest Common Ancestor of a Binary Search Tree
class Solution {
    // Global Variable
    TreeNode ans;
    
    public TreeNode lowestCommonAncestor(TreeNode root, 
                                         TreeNode p, 
                                         TreeNode q) {
        LCA(root, p, q);
        return ans;
    }
    
    public boolean LCA(TreeNode root, TreeNode p, TreeNode q){
        if(root == null) return false;
        if (p == q) {
            ans = root;
            return true;
        }
            
        int left  = LCA(root.left,  p, q) ? 1 : 0;
        int right = LCA(root.right, p, q) ? 1 : 0;
        int middle = (root == p || root == q) ? 1 : 0;
        
        if(left + middle + right >= 2) ans = root;
        
        return (left + middle + right > 0);
    }
}
```

#### Language used for code
Java

#### Expected behavior
If nodes `p` and `q` are the same then the expected common ancestor will be the same like `p` or `q`.

[6,2,8,0,4,7,9,null,null,3,5]
5
5

#### Screenshots

![Captura de Pantalla 2020-07-02 a la(s) 3 56 37 p m](https://user-images.githubusercontent.com/6373960/86408454-a6e1bd80-bc7c-11ea-9acb-a0942668804b.png)

**Comment by lc-kate** [comment]
Hi @elulcao ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @elulcao ,
Thank you for your time. We took a thorough look at this issue. Although you were theoretically correct about the issue, the contributed test case would still be invalid according to the second constraint "p and q are different and both values will exist in the BST". To prevent this issue from happening again, we've improved the problem with additional help, so please check it out :)
