### ISSUE TITLE
Union by Rank - Disjoint Set

### ISSUE THREAD

**Issue by ukaj808** [LeetCode-Feedback/LeetCode-Feedback#5701]
#### Your LeetCode username
ukaj808

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The following paragraph is puzzling me; I think its a issue with my understanding but I just wanted to make sure:

_We have implemented two kinds of “disjoint sets” so far, and they both have a concerning inefficiency. Specifically, as shown in Figure 1, it is possible for all the vertices to form a line after connecting them using union, which is the worst-case scenario for the find function._ **

It is my understanding that after creating the Quick Find impl of a disjoint set, the find() function will always be O(1). In the case of the paragraph above, if all vertices form a line in a Quick Find impl, the find will still be O(1) right?

**Explore/Graphs (Premium)/ Disjoint Set/ Union by Rank - Disjoint Set

**Comment by LC-Sue** [comment]
Hi @ukaj808 
Thank you for reaching out to us. The statement is a bit ambiguous. It sounds like it applies to both quick union and quick find, but really it's only intended for quick union.  Quick find has it's own, different, shortcomings. The wording of this paragraph has been updated.
