### ISSUE TITLE
Python2 "two pointers" solution is Incorrect - 844. Backspace String Compare

### ISSUE THREAD

**Issue by ideaguy3d** [LeetCode-Feedback/LeetCode-Feedback#5702]
#### Your LeetCode username
ideaguy3d

#### Category of the bug
- [x ] Solution

#### Description of the bug
I literally copied & pasted the python2 "two pointers" solution just to make sure it works, 
then ran code, 
and got the wrong answer 

#### Code you used for Submit/Run operation
```
class Solution(object):
    def backspaceCompare(self, S, T):
        def F(S):
            skip = 0
            for x in reversed(S):
                if x == '#':
                    skip += 1
                elif skip:
                    skip -= 1
                else:
                    yield x

        return all(x == y for x, y in itertools.izip_longest(F(S), F(T)))
```

#### Language used for code
Python

#### Expected behavior
The code is from "Approach #2:  Two Pointer [Accepted]" from the solutions tab

#### Screenshots

<img width="1514" alt="problem 844 error" src="https://user-images.githubusercontent.com/14084686/147689943-d0ee6f16-e0ec-465c-b42a-eef4b70b6521.png">

**Comment by LC-Sue** [comment]
Hi @ideaguy3d,
Thank you for reaching out to us, the code in the solution is a python code and not a python 3 code. I've attached a screenshot of it passing python for your reference!

![image](https://user-images.githubusercontent.com/92285126/148137363-516e2f65-2336-4f49-a741-447f0d67b0e7.png)
