### ISSUE TITLE
Proposed solution does not work with test case

### ISSUE THREAD

**Issue by she43** [LeetCode-Feedback/LeetCode-Feedback#5704]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The below solution for the question does not work with the mentioned test case.
https://leetcode.com/problems/contains-duplicate-iii/solution/
Approach #1 (Naive Linear Search) [Time Limit Exceeded]

Testcase:
[-2147483648,2147483647]
1
1

#### Code you used for Submit/Run operation

```
// Contains Duplicates
class Solution {
   public boolean containsNearbyAlmostDuplicate(int[] nums, int k, int t) {
    for (int i = 0; i < nums.length; ++i) {
        for (int j = Math.max(i - k, 0); j < i; ++j) {
            if (Math.abs(nums[i] - nums[j]) <= t) return true;
        }
    }
    return false;
    }
// Time limit exceeded.
}
```

#### Language used for code

java

**Comment by LC-Sue** [comment]
Hi @she43 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @she43 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
