### ISSUE TITLE
Indices vector in test case is given wrong. - 1528. Shuffle String

### ISSUE THREAD

**Issue by Csudhanshu273** [LeetCode-Feedback/LeetCode-Feedback#5706]
#### Category of the bug
- [* ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
'''    vector<int> twoSum(vector<int> &a, int s) {
    string temp;
        for(int i=0;i<indices.size();++i)
        {
            temp+=s[indices[i]];
        }
        return temp;
'''
    }
};
```

**Comment by LC-Sue** [comment]
Hi @Csudhanshu273,
Thank you for reaching out to us, could you provide more details for the issue you are reporting?

**Comment by telestrial** [comment]
Hello,

I also encountered this one and I'm happy to clarify.


Input
`"codeleet"
[4,5,6,7,0,2,1,3]`

With this code:
`
var restoreString = function(s, indices) {
    let solution = '';
    
    for(let i = 0; i < indices.length; i++) {
        solution += s[indices[i]];
    }
    
    return solution;
};
`

Result would be:

`leetcdoe`

The test expects `leetcode` which means the test should be adjusted to be:

`[4,5,6,7,0,1,2,3]`

or the provided input string should be

`cdoeleet`

I am guessing the former--changing the test array--is the correct adjustment.

**Comment by telestrial** [comment]
The test case:

`
"codeleet"
[4,5,6,7,0,2,1,3]
`

is wrong. It should be

`
"codeleet"
[4,5,6,7,0, 1, 2,3]
`

Otherwise, you'll get `cdoeleet`, and it rightly expects `codeleet`

**Comment by telestrial** [comment]
I am here and I believe I have the same issue, but I could just be wrong about my solution. I, too, believe the test case is incorrect.

Input
`
"codeleet"
[4,5,6,7,0,2,1,3]
`

My code:

```
var restoreString = function(s, indices) {
    let solution = '';
    
    for(let i = 0; i < indices.length; i++) {
        console.log('Adding', s[indices[i]], 'Index', i);
        solution += s[indices[i]];
    }
    
    return solution;
};
```

My output
`
"leetcdoe"
`

The test case goes `[...0, 2, 1, 3]`

Shouldn't it be `[...0, 1, 2, 3]` ?

**Comment by LC-Sue** [comment]
Hi @Csudhanshu273 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
