### ISSUE TITLE
Test case not within the constraints - 989. Add to Array-Form of Integer

### ISSUE THREAD

**Issue by njpipeorgan** [LeetCode-Feedback/LeetCode-Feedback#5707]
#### Your LeetCode username

njpipeorgan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One of the test cases `num = [0], k = 0` does not satisfy the constraint `1 <= k <= 10^4`

**Comment by stormsunshine** [comment]
There are four test cases with `k == 0`. The test cases are as follows.
```
[0]
0
[8]
0
[1,4]
0
[2,4,5,5]
0
```
All these four test cases should be removed, since they do not meet the constraint `1 <= k <= 10^4`.

**Comment by LC-Sue** [comment]
Hi @njpipeorgan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @njpipeorgan,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
