### ISSUE TITLE
Missing Test Case - 846. Hand of Straights

### ISSUE THREAD

**Issue by todzh** [LeetCode-Feedback/LeetCode-Feedback#5709]
#### Your LeetCode username

tod_zh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[1,1,1,5,5,5,9,9,9]
3

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isNStraightHand(int[] hand, int groupSize) {
        Arrays.sort(hand);
        int[] straight = new int[groupSize];
        
        for (int i = 0; i < hand.length; i++) {
            if (i % groupSize != 0 && hand[i] - hand[i - 1] > 1) return false;
            straight[hand[i] % groupSize]++;
        }
        
        for (int num : straight) {
            if (num != straight[0]) return false;
        }
        
        return true;
    }
}
```

#### Language used for code

Java

**Comment by LC-Sue** [comment]
Hi @todzh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @todzh 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
