### ISSUE TITLE
62. Unique Paths   wrong test case

### ISSUE THREAD

**Issue by marsPure** [LeetCode-Feedback/LeetCode-Feedback#571]
#### Your LeetCode username
Koolaang2

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
on 62. Unique Paths
for the input m =1 and n=1, because there is only one cell available, the start and finish point are the same, so the answer should be 0.

#### Code you used for Submit/Run operation
public class Solution {
    public int UniquePaths(int m, int n) {
        return count(m-1,n,1)+count(m, n-1,1);
    }
    private int count(int m , int n, int s ){
        if(m<1 || n<1) return 0;
        if(m==1 || n==1) return 1;
        return count(m-1,n,s+1)+count(m, n-1,s+1);
    }
}

#### Language used for code
C#

#### Expected behavior
the answer should be 0 for input (m=1,n=1)

**Comment by lc-kate** [comment]
Hi @marsPure ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kate** [comment]
Hi @marsPure ,
Thank you for your time. Our team took a thorough look at this issue. We found it to be invalid because it should be 1 path. We appreciate your support.
