### ISSUE TITLE
Time Limit Exceeded missing testcase 2111. Minimum Operations to Make the Array K-Increasing

### ISSUE THREAD

**Issue by Alpier** [LeetCode-Feedback/LeetCode-Feedback#5710]
#### Your LeetCode username
Aliers

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Hello! :)
I submitted a code to the problem;
https://leetcode.com/problems/minimum-operations-to-make-the-array-k-increasing/submissions/
This code returned me an accepted verdict, but it returns TLE in the following testcase:
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7791517/testcase.txt)
https://www.mediafire.com/file/r0mpp96k95we89p/testcase.txt/file
https://cdn.discordapp.com/attachments/765012182345711636/925971424533946408/message.txt

#### Code you used for Submit/Run operation

```
// Minimum Operations to Make the Array k-Increasing
// lnds = longest non decreasing subsequence
class Solution {
public:
	int binsearch(vector<int> nums, int l, int r, int key) {
		while(r > l + 1) {
			int m = (l + r) / 2;
			if(nums[m] > key) r = m;
			else l = m;
		}
		return r;
	}
	int lengthOfLNDS(vector<int> nums) {
		if(nums.size() == 0) return 0;
		vector<int> lnds(nums.size(), 0); int ans = 1;
		lnds[0] = nums[0];
		for(size_t i = 1; i < nums.size(); i++) {
			if(nums[i] < lnds[0]) lnds[0] = nums[i];
			else if(nums[i] >= lnds[ans-1]) {
				lnds[ans] = nums [i];
				ans++;
			}
			else {
				lnds[binsearch(lnds, 0, ans - 1, nums[i])] = nums[i];
			}
		}
		return ans;
	}
	int kIncreasing(vector<int>& arr, int k) {
		int ans = 0; vector<int> nums;
		for(int i = 0; i < k; i++) {
			nums = {};
			for(int j = i; j < arr.size(); j += k) nums.push_back(arr[j]);
			ans += nums.size() - lengthOfLNDS(nums);
		}
		return ans;
	}
};
```

#### Language used for code
C++

**Comment by LC-Sue** [comment]
Hi @Alpier 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Alpier 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
