### ISSUE TITLE
Missing Test Case - 1705. Maximum Number of Eaten Apples

### ISSUE THREAD

**Issue by thangitus** [LeetCode-Feedback/LeetCode-Feedback#5711]
#### Your LeetCode username
nvthang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An accepted solution gets the Wrong Answer on the following test case:
[6,1]
[6,5]

#### Code you used for Submit/Run operation

```C++
class Solution {
public:
    int eatenApples(vector<int> &apples, vector<int> &days) {
        unordered_map<int, int> count;
        priority_queue<int, vector<int>, greater<>> minHeap;
        int result = 0, i = 0;
        while (!minHeap.empty() || i < apples.size()) {
            if (i < apples.size() && apples[i]) {
                minHeap.push(i + days[i]);
                count[i + days[i]] = apples[i];
            }
            while (!minHeap.empty() &&
                   (minHeap.top() <= i || count[minHeap.top()] == 0))
                minHeap.pop();
            if (!minHeap.empty()) {
                count[minHeap.top()]--;
                result++;
            }
            i++;
        }
        return result;
    }
};
```

#### Expected behavior
Wrong answer

#### Additional context
Needs to be modified to `count[i + days[i]] += apples[i]`

**Comment by LC-Sue** [comment]
Hi @thangitus 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @thangitus,
Thank you for your time. This solution got Wrong Answer from the previous contributions.

**Comment by thangitus** [comment]
Thank @LC-Sue for your response!
