### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by adibyte95** [LeetCode-Feedback/LeetCode-Feedback#5712]
https://leetcode.com/problems/regular-expression-matching/
submitter adibyte
missing test case s="a" p="*"

**Comment by stormsunshine** [comment]
Please read the constraints carefully.

> It is guaranteed for each appearance of the character `'*'`, there will be a previous valid character to match.

Therefore, the test case you provide is invalid.

**Comment by LC-Sue** [comment]
Hi @adibyte95,
Thank you for reaching out to us, since the test case you provided is invalid, I will close this issue for now. Thank you for understanding.
