### ISSUE TITLE
Wrong Testcase - 127 - Word Ladder 

### ISSUE THREAD

**Issue by icode09** [LeetCode-Feedback/LeetCode-Feedback#5713]
It is mentioned in the question description that every adjacent pair of words differs by a single letter , but found this testcase :
beginWord = "hot" , endWord = "dog"
wordList = ["hot", "dog"] 

This is a wrong testcase, here hot and dog in the wordList differs by 2 characters, h and g.

**Comment by LC-Sue** [comment]
Hi @icode09,
Thank you for reaching out. 
The test case:
"hot"
"dog"
["hot", "dog"]

yields

Expected Output: 0

And the problem statement says:
"Given two words, beginWord and endWord, and a dictionary wordList, return the number of words in the shortest transformation sequence from beginWord to endWord, or 0 if no such sequence exists."
No sequence exists, and the expected result is 0, so everything is working correctly.
