### ISSUE TITLE
Wrong Recurrence Relation [explore: dynamic-programming] [common-patterns-in-dp-problems] 

### ISSUE THREAD

**Issue by arunavo4** [LeetCode-Feedback/LeetCode-Feedback#5717]
#### Your LeetCode username
leetarnab

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Given recurrence relation is wrong for the following Text statement

https://leetcode.com/explore/featured/card/dynamic-programming/632/common-patterns-in-dp-problems/4049/
```
In all the problems we have looked at so far, the recurrence relation is a static equation - it never changes. Recall Min Cost Climbing Stairs. The recurrence relation was dp(i) = min(dp(i - 1) + cost[i - 1], dp(i - 2) + cost[i - 2]), 
```
The correct recurrence relation should be `dp(i) = min(dp(i - 1) + cost[i], dp(i - 2) + cost[i]), `

#### Code you used for Submit/Run operation

NA

#### Language used for code
NA

#### Expected behavior
NA

#### Screenshots
NA

#### Additional context
NA

**Comment by LC-Sue** [comment]
Hi @arunavo4 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @arunavo4,
Thank you for your time. The recurrence relation you suggested can also be used to solve this problem if we set the base case as return 0 when i is greater than or equal to the number of stairs. That said, the presented recurrence relation also results in a valid solution. To see how, you can read the official solution here:  https://leetcode.com/problems/min-cost-climbing-stairs/solution/"
