### ISSUE TITLE
Missing Test Case - 1494. Parallel Courses II - 

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#572]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1494. Parallel Courses II problem misses a test case that breaks a greedy solution based on node depth

12
[[11, 10], [6, 3], [2, 5], [9, 2], [4, 12], [8, 7], [9, 5], [6, 2], [7, 2], [7, 4], [9, 3], [11, 1], [4, 3]]
3

At the moment of writing the solution below passes all problem test cases and the test cases in other github issues:
(#550, #551, #559). The solution fails on the test case above - it's output is 5, expected result is 4. Please see the screenshot below

The test case will break greedy solutions that select next course basing on depth - they will select courses 6, 8, 9 for the semester 1, this makes them select only two courses for semester 2 and eventually total number of semesters will be 5, while it is possible to do it in 4 semesters.

#### Code you used for Submit/Run operation
```
class Solution {
    private static int dfs(Set<Integer>[] gra, int cur, int[] depth) {
        if (depth[cur] != 0) return depth[cur];
        depth[cur] = Integer.MAX_VALUE;
        int curDepth = 0;
        for (int nei : gra[cur]) {
            curDepth = Math.max(curDepth, dfs(gra, nei, depth));
            if (curDepth == Integer.MAX_VALUE) {
                return Integer.MAX_VALUE;
            }
        }
        return depth[cur] = 1 + curDepth;
    }    
    
    public int minNumberOfSemesters(int n, int[][] dependencies, int k) {
        List<Integer>[] adj = new ArrayList[n];
        for (int i = 0; i < n; i++) {
            adj[i] = new ArrayList<>();
        }

        int[] indegree = new int[n];
        boolean[][] conn = new boolean[n][n];
        for (int[] dep : dependencies) {
            adj[dep[0] - 1].add(dep[1] - 1);
            indegree[dep[1] - 1]++;
            conn[dep[0] - 1][dep[1] - 1] = true;
        }

        for (int m = 0; m < n; m++)
            for (int i = 0; i < n; i++)
                for (int j = 0; j < n; j++)
                    conn[i][j] = conn[i][j] || (conn[i][m] && conn[m][j]);

        int[] numDependents = new int[n];
        for (int i = 0; i < n; i++)
            for (int j = 0; j < n; j++)
                numDependents[i] += conn[i][j] ? 1 : 0;

        Set<Integer>[] gra = new Set[n];
        for (int i = 0; i < n; i++) {
            gra[i] = new HashSet<>();
        }

        for (int[] e : dependencies) {
            gra[e[0]-1].add(e[1]-1);
        }

        int[] depth = new int[n];

        for (int i = 0; i < n; i++) {
            if (dfs(gra, i, depth) == Integer.MAX_VALUE) {
                return -1;
            }
        }

        PriorityQueue<Integer> pq = new PriorityQueue<>(
                new Comparator<Integer>() {
                    @Override
                    public int compare(Integer a, Integer b) {
                        int db = depth[b];
                        int da = depth[a];

                        if (db == da) {
                            return Integer.compare(numDependents[b], numDependents[a]);
                        }

                        return Integer.compare(db, da);
                    }
                }
        );
        for (int i = 0; i < n; ++i) {
            if (indegree[i] == 0) {
                pq.offer(i);
            }
        }
        List<Integer> nextList = new ArrayList<>();
        int res = 0;
        while (!pq.isEmpty()) {
            for (int i = Math.min(k, pq.size()); i > 0; i--) {
                int current = pq.poll();
                for (int next : adj[current]) {
                    if (--indegree[next] == 0) {
                        nextList.add(next);
                    }
                }
            }
            pq.addAll(nextList);
            nextList.clear();
            res++;
        }
        
        return res;        
    }
}
```
#### Language used for code

Java

#### Expected behavior

This solution should be rejected since its output is 5 and expected result is 4.

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/86416890-63e21300-bc99-11ea-9001-d4f01ad8d20b.png)

![image](https://user-images.githubusercontent.com/32546406/86416942-86742c00-bc99-11ea-92cf-d0020c5ae120.png)

#### Additional context

This test case is designed to break greedy solutions based on course depth

**Comment by lc-christina** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by goodgoodwish** [comment]
My #topological_sort code solved it correctly.
https://leetcode.com/problems/parallel-courses-ii/discuss/780260/Python-topological_sort-bottom-up-solved-all-test-cases-could-be-wrong

**Comment by IgorRud** [comment]
Please take a look at #789

**Comment by goodgoodwish** [comment]
Thanks for this one more test case.  ^_^

```
12
[[1,8], [1,9], [1,10], [1,11], [2,8], [2,9], [2,10], [2,11], [3,8], [3,9], [3,10], [3,11], [4,8], [4,9], [4,10], [4,11], [5,12], [6,12], [7,12]]
3
```
