### ISSUE TITLE
Missing Test Case - 79. Word Search

### ISSUE THREAD

**Issue by Shenghan-Chen** [LeetCode-Feedback/LeetCode-Feedback#5720]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test cases to detect a faulty search pruning implementation, e.g.
board = [["L","L","A","B","L","D"],["G","A","B","A","L","L"],["A","B","C","B","J","A"],["L","E","D","H","I","L"]], 
words = "GABALJIHDCBA"

#### Code you used for Submit/Run operation

```
// sample 70 ms submission
class Solution:
    def exist(self, board, word):
        def backtracking(r, c, step=0):
            if step == len(word):
                return True
            
            if 0 <= r < m and 0 <=c<n and board[r][c] == word[~step] and (r,c) not in visited:        
                visited.add((r, c))
                HashMap[(r, c, step)] += 1 
                for nr, nc in (r,c+1),(r,c-1),(r-1,c),(r+1,c):
                    if HashMap[(nr, nc, step+1)] < 5:
                        if backtracking(nr, nc, step+1):
                            return True
                visited.remove((r, c))
                return False
        
        m, n = len(board), len(board[0])
        visited, HashMap = set(), defaultdict(int)
        for i, j in itertools.product(range(m), range(n)):
            if backtracking(i, j):
                return True
        return False
```

#### Language used for code

Python

#### Expected behavior

The code failed this test case but got accepted as a correct answer.

#### Screenshots

<img width="880" alt="Screen Shot 2021-12-30 at 3 33 21 AM" src="https://user-images.githubusercontent.com/6370162/147748287-20aa37aa-14f3-4c32-a265-b5856819b4d5.png">

**Comment by LC-Sue** [comment]
Hi @Shenghan-Chen 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Shenghan-Chen 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Shenghan-Chen** [comment]
My pleasure!

Best,
Shenghan
