### ISSUE TITLE
Missing Test Case - 1155. Number of Dice Rolls With Target Sum

### ISSUE THREAD

**Issue by daniel-lee-sb** [LeetCode-Feedback/LeetCode-Feedback#5721]
#### Your LeetCode username

GwonsooLee

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

It has a typo in the question.

You have n dice and each `die` has k faces numbered from 1 to k.

I think `die` should be `dice`.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case? Don't create meaningless issues!

**Comment by LC-Sue** [comment]
Hi @daniel-lee-sb,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
