### ISSUE TITLE
26. 删除有序数组中的重复项 测试用例有问题

### ISSUE THREAD

**Issue by JohnChenLiang** [LeetCode-Feedback/LeetCode-Feedback#5724]
**Bug 类型**
 26. 删除有序数组中的重复项
- JAVA

**描述**
  同一段代码 同一个输入，leecode页面的输出 与 idea里的输出不一样。

**你使用的语言**
JAVA

**你提交或者运行的代码**
    public int removeDuplicates(int[] nums) {
        return Arrays.stream(nums).distinct().toArray().length;
    }

**期望行为**
输入：
[1,1,2]
输出：
[1,2]

**屏幕截图**
![a217f3b690c933813c1391fa64dcc55](https://user-images.githubusercontent.com/30498675/147802286-dbad1a1d-a6af-437c-9664-f82f12b3e287.png)
![9c53f081721139573e54b0d6e196865](https://user-images.githubusercontent.com/30498675/147802288-2e82b388-1632-4df2-a399-08f1afbdfa9a.png)

**Comment by stormsunshine** [comment]
This issue is the same as #5723 . Don't create duplicate issues.
