### ISSUE TITLE
Missing Test Case - 1026. Maximum Difference Between Node and Ancestor

### ISSUE THREAD

**Issue by reb00ted** [LeetCode-Feedback/LeetCode-Feedback#5725]
#### Your LeetCode username

reb00ted

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Missing Test cases

#### Code you used for Submit/Run operation

```java
class Solution {
    int result = 0;
    TreeSet<Integer> table = new TreeSet<>();
    
    public int maxAncestorDiff(TreeNode root) {
        maxAncestorDiffHelper(root);
        return result;
    }
    
    private void maxAncestorDiffHelper(TreeNode root) {
        if (root == null) return;
        
        if (!table.isEmpty()) {
            result = Math.max(result, Math.abs(table.first() - root.val));
            result = Math.max(result, Math.abs(table.last() - root.val));
        }
        
        table.add(root.val);
        maxAncestorDiffHelper(root.left);
        maxAncestorDiffHelper(root.right);
        table.remove(root.val);
        return;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I failed some test cases but I got Accepted.
ex) [1,1,8]

**Comment by LC-Sue** [comment]
Hi @reb00ted 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @reb00ted 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
