### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by SleeplessChallenger** [LeetCode-Feedback/LeetCode-Feedback#5728]
#### Your LeetCode username

SleeplessChallenger

#### Category of the bug
- [ ] Question

#### Description of the bug

1. In **Kotlin** language `Int.MIN_VALUE` holds -2147483648 and `Int.MAX_VALUE` holds 2147483647. They're min and max respectively what `Int` can possibly hold. 

2. In the question description it's stated that main check is: current value mustn't be even equal, only smaller or greater than parent node.

3. One of the test cases: `[2147483647]`. As you can see it means that there is no possible way for **Kotlin** case to work (return true as Leetcode result wants)

4. Just for info: Python solution works well.

#### Code you used for Submit/Run operation

```
// Validate Binary Search Tree
class Solution {
    fun isValidBST(root: TreeNode?): Boolean {
        return this.findIfValid(root, Int.MIN_VALUE, Int.MAX_VALUE)
    }
    
    fun findIfValid(node: TreeNode?, lower: Int, upper: Int): Boolean {
        if(node == null) {
            return true
        }
        println(lower)
        println(upper)
        if(node.`val` <= lower || node.`val` >= upper) {
            return false
        }
        
        val left_result = this.findIfValid(node.left, lower, node.`val`)
        
        return left_result && this.findIfValid(node.right, node.`val`, upper)
        
    }
}
```

#### Expected behavior

So, if taken **Kotlin** way of MIN & MAX (float('-inf') && float('inf')), written above test case should return false, not true or the description of the question should be tweaked and make strict `<`/`>` as false check instead of current `<=`/`>=`

#### Additional context

- Of course, we can play with types and make Long instead of Int, but it requires additional tweaks of the values and so on, hence not the best way to work around

**Comment by LC-Sue** [comment]
Hi @SleeplessChallenger 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by SleeplessChallenger** [comment]
@LC-Sue thanks for answer. Yeah, will glad to see the team response then.

**Comment by LC-Sue** [comment]
Hi @SleeplessChallenger,
Thank you for your time. Here is feedback from our team. The min and max values are similar in most of the languages and this did not show any issues in the other languages. It should not be an issue with Kotlin. In the discus section, there are lots of accepted Kotlin solutions.

**Comment by SleeplessChallenger** [comment]
I see, those solutions use other methods without infinity. As I understand, it's difference between Python and Kotlin + the fact that Python doesn't use explicit types like Kotlin. Again, thanks for taking my issue into consideration
