### ISSUE TITLE
Daily log in

### ISSUE THREAD

**Issue by Meep11** [LeetCode-Feedback/LeetCode-Feedback#5742]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Meep11 
Please provide more details on the issue. After more information is provided, I will reopen this ticket. Thank you for your time.
