### ISSUE TITLE
Missing test case 259

### ISSUE THREAD

**Issue by vagenuep** [LeetCode-Feedback/LeetCode-Feedback#5746]
#### Your LeetCode username
vagenuep

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In the solution, the binary-search and two-pointers methods would fail when the 'nums' array contains negative integers.
For example, nums=[-3,-2,0,1,3,6], and target to be 3. There should be 8 triplets that satisfy the condition, but the solutions will output 5.

#### Code you used for Submit/Run operation

```
// Three Sum
class Solution {
    public int threeSumSmaller(int[] nums, int target) {
        Arrays.sort(nums);
        int sum = 0;
        for (int i = 0; i < nums.length - 2; i++) {
            sum += twoSumSmaller(nums, i + 1, target - nums[i]);
        }
        return sum;
    }

    private int twoSumSmaller(int[] nums, int startIndex, int target) {
        int sum = 0;
        int left = startIndex;
        int right = nums.length - 1;
        while (left < right) {
            if (nums[left] + nums[right] < target) {
                sum += right - left;
                left++;
            } else {
                right--;
            }
        }
        return sum;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Code output is 5,
but actual output should be 8 ([-3,-2,0] [-3,-2,1] [-3,-2,3] [-3,-2 6] [-3,0,1] [-3,0,3] [-2,0,1] [-2,0,3])

**Comment by LC-Sue** [comment]
Hi @vagenuep,
Thank you for reaching out to us, the test case and code you provided are both accepted. I will close this issue for now as there is no missing test case. I've attached a screenshot for your reference. Thank you for understanding. 

![image](https://user-images.githubusercontent.com/92285126/148142419-6a1f4c27-39d3-4bc1-a53a-09091bb93e1d.png)
