### ISSUE TITLE
Missing Test Case - 1295. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by ankur-lakhmara** [LeetCode-Feedback/LeetCode-Feedback#5752]
#### Your LeetCode username
`ankurvermannl`

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

when I use `0220 `as my test case its shows runtime error but it should counts number digits.
That mean if number starting from `0` it will not count as a `digit `and shows `runtime error` their is nothing given in description of question

#### Code you used for Submit/Run operation

```
// Find Numbers with Even Number of Digits
class Solution {
    public int findNumbers(int[] nums) {
        int count = 0;
        for(int i = 0;i<nums.length;i++) {
         int length = String.valueOf(nums[i]).length();
            if(length%2 ==0){
                count++;
            }
        }   
        return count;
    }
}
```

#### Language used for code

- _Java_

**Comment by stormsunshine** [comment]
The input is an array. How do you input a single number? Do you mean an array with length 1?

**Comment by ankur-lakhmara** [comment]
No when i am giving an array like this` [12,5,7,1522,45]` then output is : 3 and thats right no issue with that

but when array is [ 12, 05, 7, 1522, 045 ] then it gives run time error I know `By placing a zero in front of the number is an integer in octal form. 010 is in octal form so its value is 8`  but its should convert the value to `octal `form instead of giving the error.

**Comment by Sanchitanwar0007** [comment]
If array of string is given then its possible but in case of numbers leading zero numbers are not valid then how this input is correct.

**Comment by LC-Sue** [comment]
Hi @ankur-lakhmara,
Thank you for reaching out to us. When the type of an input parameter is integer, it is implied that the input is in decimal form and the integer values for any custom test cases should also be given in decimal form.
