### ISSUE TITLE
Problem Description Incorrect - 1. Two Sum

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5755]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [1. Two Sum](https://leetcode.com/problems/two-sum), a word in Example 1 is incorrect. The third line should be "Explanation", not "Output".
Please refer to the following screenshot.

#### Expected behavior
The third line in Example 1 should be changed to "Explanation".

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/147849164-62fa477d-1363-4838-a862-d465d2612842.png)

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
