### ISSUE TITLE
Problem Constraint Incorrect - 568. Maximum Vacation Days

### ISSUE THREAD

**Issue by JamesHuang-TW** [LeetCode-Feedback/LeetCode-Feedback#5756]
#### Your LeetCode username
yhhuang2021

#### Category of the bug
- [ ] Question

#### Description of the bug

The last constraint condition in "568. Maximum Vacation Days" should be 0 <= days[i][j] <= 7 since the (original) days[i] is a vector.

**Comment by LC-Sue** [comment]
Hi @JamesHuang-TW 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @JamesHuang-TW 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
