### ISSUE TITLE
Submission Error in 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by RitikaBhrgv** [LeetCode-Feedback/LeetCode-Feedback#5757]
Your LeetCode username
**FierceCoder**

**Description of the bug**

The submissions:  [Submission1](https://leetcode.com/submissions/detail/610803249/) and [Submission2](https://leetcode.com/submissions/detail/610803465/) are returning Wrong Answer based on a test case which is passing when run directly in code editor.

<img width="1436" alt="Screen Shot 2022-01-01 at 5 55 57 PM" src="https://user-images.githubusercontent.com/6661513/147850628-a06e5ce7-af23-4bcd-a251-9fa2a5b30599.png">

**Comment by LC-Sue** [comment]
Hi @RitikaBhrgv 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
