### ISSUE TITLE
Typos in Solution of  568. Maximum Vacation Days

### ISSUE THREAD

**Issue by JamesHuang-TW** [LeetCode-Feedback/LeetCode-Feedback#5758]
#### Your LeetCode username

yhhuang2021

#### Category of the bug
- [ ] Solution

#### Description of the bug

Two typos in the space complexity of Approach 4: 
Origin:          O(k). dp array of size nk is used.
Suggested:   "O(n)." dp array of size "n" is used.
Reason: Check line 4 of the suggested java code given in this approach.

**Comment by LC-Sue** [comment]
Hi @JamesHuang-TW 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
