### ISSUE TITLE
 332. Reconstruct Itinerary(GRAPH)

### ISSUE THREAD

**Issue by 18-RAJAT** [LeetCode-Feedback/LeetCode-Feedback#5759]
class Solution {
    
    void dfs(unordered_map<string,multiset<string>>& adj,vector<string>& result,string s)
    {
        while(adj[s].size())
        {
            string v = *(adj[s].begin());
            adj[s].erase(adj[s].begin());
            
            dfs(adj,result,v);
        }
        
        result.push_back(s);
    }
public:
    vector<string> findItinerary(vector<vector<string>>& tickets) {
        
        //build the adj list
        
        unordered_map<string,multiset<string>> adj;
        
        for(vector<string>& t : tickets)
        {
            adj[t[0]].insert (t[1]);
        }
        
        vector<string>result;
        
        dfs(adj,result,"JFK");
        
        reverse(result.begin(),result.end());
        
        return result;
    }
    
};

**Comment by LC-Sue** [comment]
Hi @18-RAJAT,
Thank you for reaching out to us. Since there is no error I will close this issue now, thank you for understanding. Please feel free to share your solution in the discuss section of the problem!

**Comment by 18-RAJAT** [comment]
Thanks man

**Comment by 18-RAJAT** [comment]
**Best**

**Comment by 18-RAJAT** [comment]
**Okayed👍🏼**
