### ISSUE TITLE
1501. Countries You Can Safely Invest In, Wrong descriptions of problem.

### ISSUE THREAD

**Issue by bytebeats** [LeetCode-Feedback/LeetCode-Feedback#576]
In problem of [1501. Countries You Can Safely Invest In](https://leetcode.com/problems/countries-you-can-safely-invest-in/), description of **The country intends to invest in the countries where the average call duration of the calls in this country is strictly greater than the global average call duration.** is no right, it may confuse readers. I think it should mean **The company** or **The telecommunications company**.

So, one of the appropriate descriptions is **The company intends to invest in the countries where the average call duration of the calls in this country is strictly greater than the global average call duration.**

I hope it will help.

**Comment by lc-christina** [comment]
Hi @bytebeats 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @bytebeats 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
