### ISSUE TITLE
Bad Test Case - 213. House Robber II - Array of length 2 should always return 0 based on problem statement.

### ISSUE THREAD

**Issue by dpav02** [LeetCode-Feedback/LeetCode-Feedback#5760]
https://leetcode.com/problems/house-robber-ii/

If the array length is exactly two, the result should always be 0 because you cannot rob anything.

Going off of the problem description, let's say you had [1, 1] as input. If you rob the first house, the police will be called. If you rob the 2nd house, the police will also be called (since this is a loop).

Therefore, if given an array with the length == 2, you cannot rob anything. This is an edge case that should be checked for at the beginning of the function.

But if you input [1, 1] into the test cases, the expected output is 1, and, again, according to the problem statement, this is not correct.

**Comment by stormsunshine** [comment]
You do not understand the problem correctly. If the array has length 2, then there are 2 houses. Why should the result be 0? You can rob either house without alarming the police.

The police will be alarmed only if two adjacent houses are robbed. If you only rob one house, how can two adjacent houses are robbed? Even the number of houses being robbed is only one.

**Comment by LC-Sue** [comment]
Hi @dpav02,
Thank you for reaching out to us, since stormsunshine has explained the problem, I will close this issue for now, thank you for understanding! Please feel free to reach out if you have any other questions!
