### ISSUE TITLE
189. Rotate Array, wrong output issue

### ISSUE THREAD

**Issue by sharanbs** [LeetCode-Feedback/LeetCode-Feedback#5761]
#### Your LeetCode username
sharanbs

#### Category of the bug
- [ ] Solution 

#### Description of the bug
Wrong output is being displayed for the solution provided by me, the same code is giving the correct output in Visual Studio and online IDE as expected.

#### Code you used for Submit/Run operation

```
public class Solution {
    public void Rotate(int[] nums, int k) {
        nums.Skip(nums.Length - k).Take(nums.Length - 1).Union(nums.Take(nums.Length-k)).ToArray();
    }
}
```

#### Language used for code
C#

#### Screenshots

![image](https://user-images.githubusercontent.com/52955660/147857285-f7a0ea0e-bc18-45d1-b682-97ed5ad31f90.png)

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
