### ISSUE TITLE
Redundant Problem (LeetCode 1060 and LeetCode 1539)

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#5762]
#### Your LeetCode username
@aestheticsjtu

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
LeetCode 1060 and LeetCode 1539 are redundant problems.

**Comment by stormsunshine** [comment]
The problems are different. Problem 1060 requires finding the `k`-th missing positive integer starting from `nums[0]`. Problem 1539 requires finding the `k`-th missing positive starting from 1.

**Comment by LC-Sue** [comment]
Hi @ThomasShaw1,
Thank you for reaching out to us, since stormsunshine has explained the difference between the two problems, I will close this issue for now! Please feel free to reach out if you have other questions!
