### ISSUE TITLE
62. Unique Paths -  Error in solution

### ISSUE THREAD

**Issue by Meowzz95** [LeetCode-Feedback/LeetCode-Feedback#5764]
#### Your LeetCode username
jjzzzmd

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
![image](https://user-images.githubusercontent.com/22430379/147864969-492d6c60-c964-44c7-8153-6559ebf387fb.png)

Please check the above screenshot, the `right` should be `left`

#### Code you used for Submit/Run operation
NA

#### Language used for code

NA

#### Expected behavior

See description

#### Screenshots

See description

#### Additional context

NA

**Comment by LC-Sue** [comment]
Hi @Meowzz95 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Meowzz95 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
