### ISSUE TITLE
Error in description - 2127. Maximum Employees to Be Invited to a Meeting

### ISSUE THREAD

**Issue by Silvia42** [LeetCode-Feedback/LeetCode-Feedback#5766]
Example 3:
Input: favorite = [3,0,1,4,1]
Output: 4

**Comment by Silvia42** [comment]
There is only error in the explanation. 
Test case is correct.
Employee 2 cannot be invited because the two spots next to their favorite employee 0 are taken.

There should be:  ....  favorite employee 1 are taken.

**Comment by LC-Sue** [comment]
Hi @Silvia42,
Thank you for reaching out to us, in example 3 the current description is "Employee 2 cannot be invited because the two spots next to their favorite employee 1 are taken." Please feel free to reach out if you have any other questions!
