### ISSUE TITLE
209. 长度最小的子数组

### ISSUE THREAD

**Issue by CLannadZSY** [LeetCode-Feedback/LeetCode-Feedback#577]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
`原题目说明:` 找出该数组中满足其和 ≥ s 的长度最小的连续子数组

这样的描述很容易让人认为子数组中的元素也必须是要连续的

**期望行为**
找出该数组中满足其和 ≥ s 的长度最小的连续子数组, 子数组中的元素并不一定是连续的

**Comment by feiceh** [comment]
感谢反馈，由于子数组已经暗含了连续的条件，为避免歧义，删除了「连续」，请知晓。
