### ISSUE TITLE
Typing mistake in 568. Maximum Vacation Days

### ISSUE THREAD

**Issue by hss15** [LeetCode-Feedback/LeetCode-Feedback#5777]
#### Your LeetCode username
hss15

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

[https://leetcode.com/problems/maximum-vacation-days/](https://leetcode.com/problems/maximum-vacation-days/)

#### Description of the bug
Typing mistake in question 568 in "Constraints" section.
"days" is an `int[][]` type of matrix.
The last line in missing 2nd parameter for matrix access.
It's currently `0 <= days[i] <= 7`

#### Code you used for Submit/Run operation
NA

#### Language used for code
NA

#### Expected behavior
`0 <= days[i][j] <= 7`

#### Additional context

**Comment by LC-Sue** [comment]
Hi @hss15 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hss15 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
