### ISSUE TITLE
Typo in 1010. Pairs of Songs With Total Durations Divisible by 60

### ISSUE THREAD

**Issue by burner1992** [LeetCode-Feedback/LeetCode-Feedback#5779]
#### Your LeetCode username
NaN-NaN-NaN

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Minor typo in the solution of [Pairs of Songs With Total Durations Divisible by 60 - LeetCode](https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/ "Pairs of Songs With Total Durations Divisible by 60 - LeetCode"). It is located in Approach 2.

Line which has typo:

> if `a % 60=0`, add `remainders[0]` to the result; else, add `remainders[60 - t % 60]` to the result;

#### Expected behavior

It should be:
> if `a % 60=0`, add `remainders[0]` to the result; else, add `remainders[60 - a % 60]` to the result;

**Comment by LC-Sue** [comment]
Hi @burner1992 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @burner1992 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
