### ISSUE TITLE
300. 最长上升子序列 Python 提交结果错误

### ISSUE THREAD

**Issue by Tosnower** [LeetCode-Feedback/LeetCode-Feedback#578]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- 编程语言

**描述**
提交之后的测试用例[-2,-1]计算结果错误，但是在本地和执行代码，输入相同的测试用例之后得到的结果正确

**你使用的语言**
Python

**你提交或者运行的代码**
```
class Solution:
    def lengthOfLIS(self, nums: List[int]) -> int:
        if len(nums) == 0:
            return 0
        (laxtMax, length) = self.helper(nums, len(nums)-1)
        return length

    mem = dict()
    def helper(self, nums, index):
        if index in self.mem:
            return self.mem[index]
        if index == 0:
            self.mem[index] = (nums[index], 1)
            return (nums[index], 1)
        (lastMax, length) = self.helper(nums, index -1)
        if nums[index] > lastMax:
            self.mem[index] = (nums[index], length + 1)
            return (nums[index], length + 1)
        else:
            self.mem[index] = (nums[index], length)
            return (nums[index], length)
```

**期望行为**
正确结果应该是2

**屏幕截图**
![image](https://user-images.githubusercontent.com/19636035/86465656-acb2ce00-bd64-11ea-87e0-be30ae78f5dc.png)
![image](https://user-images.githubusercontent.com/19636035/86465692-bb998080-bd64-11ea-8413-e34496233a5d.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，可以看看其他小伙伴的解题思路哦～
