### ISSUE TITLE
Missing Test Case - 1010. Pairs of Songs With Total Durations Divisible by 60

### ISSUE THREAD

**Issue by sangmesh04** [LeetCode-Feedback/LeetCode-Feedback#5780]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by sangmesh04** [comment]
Time limit not mentioned in question.

**Comment by LC-Sue** [comment]
Hi @sangmesh04 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
