### ISSUE TITLE
Incorrect Test Case - 853. Car Fleet

### ISSUE THREAD

**Issue by SeyhmusGuler** [LeetCode-Feedback/LeetCode-Feedback#5781]
#### Category of the bug
- [] Question
- [X] Solution 
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem gives an incorrect answers to one of the existing test cases:
Input: 
10
[0,4,2]
[2,1,3]

Expected:
1

What answer should be: 
2

#### Code you used for Submit/Run operation

```
duration = [(target - position[idx]) / speed[idx] for idx in range(len(position))][::-1]
        result = 1
        prev = duration[0]
        #print(duration)
        for idx in range(1,len(duration)):
            if duration[idx] > prev:
                result += 1
                prev = duration[idx]
        return result
```

#### Language used for code

Python

#### Expected behavior

The expected output is 2, whereas the test case says it should be 1.

**Comment by LC-Sue** [comment]
Hi @SeyhmusGuler,
Thank you for reaching out to us, upon checking the test case is correct. Please feel free to refer to the discuss section of the problem to see how other have optimized their codes!
