### ISSUE TITLE
Same code but accepted when testing particular test case but not when submitting the code;

### ISSUE THREAD

**Issue by MrLakshay** [LeetCode-Feedback/LeetCode-Feedback#5782]
Problem link-https://leetcode.com/problems/palindromic-substrings/
My code
class Solution {
public:
    int countSubstrings(string s) {
        int n=s.size();
        int dp[n][n];
        int ans=0;
        for(int i=0;i<n;i++){
            dp[i][i]=1;
            ans++;
        }
        for(int i=0;i<n-1;i++){
            if(s[i]==s[i+1]){
            dp[i][i+1]=1;
            ans++;}
        }
        for(int i=2;i<n;i++){
            for(int j=0;j<n;j++){
                int k=i+j;
                if(s[j]==s[k] and dp[j+1][k-1]==1){
                    ans++;
                    dp[j][k]=1;
                    //cout<<s.substr(j,k);
                }
            }
        }
        return ans;
    }
};
Problem:-
Solution accepted when testing the particular case and not when submitting the code
Test case:
"fdsklf"
![Screenshot 2022-01-02 222457](https://user-images.githubusercontent.com/63330679/147883163-b0f190f2-2292-4800-94bd-aa0eaba753ea.png)

**Comment by LC-Sue** [comment]
Hi @MrLakshay 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
