### ISSUE TITLE
Missing Test Case - 1219. Path with Maximum Gold

### ISSUE THREAD

**Issue by AbhishekRanjan624** [LeetCode-Feedback/LeetCode-Feedback#5783]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @AbhishekRanjan624 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
