### ISSUE TITLE
Missing Test Case - 312. Burst Balloons

### ISSUE THREAD

**Issue by Chenfeng51** [LeetCode-Feedback/LeetCode-Feedback#5785]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing a test  case so my solution can pass the submission but fails this test case.

#### Code you used for Submit/Run operation

```
// Burst Balloons
class Solution:
    def maxCoins(self, nums: List[int]) -> int:
        nums = [1] + nums + [1]
        n = len(nums)
        dp = [[0] * n for _ in range(n)]
        
        buff = {}
        
        def maxCoinInRange(beg, end,  buffer):
            if (beg, end) in buffer:
                return buffer[(beg, end)]
            if beg > end:
                return 0
            # edge case:
            score = 0
            if beg == end:
                score = nums[beg-1] * nums[beg] * nums[beg+1]
            else:
                max_edge = max(nums[beg-1], nums[end+1])
                isSame = all(nums[i] == nums[end] and nums[i] >= max_edge for i in range(beg, end))
                if isSame:
                    count = end-beg+1
                    score = nums[beg-1] * nums[beg] * nums[beg+1] + nums[beg-1] * nums[end]* nums[end+1] + (count-2) * (nums[beg] **3)
                else:
                    for last in range(beg, end+1):
                        temp_score = maxCoinInRange(beg, last-1, buff) + maxCoinInRange(last+1, end, buff) + nums[beg-1] * nums[last] * nums[end+1]
                        score = max(score, temp_score)       
            buff[(beg, end)] = score
            return buff[(beg, end)]
        
       
        
        return maxCoinInRange(1, n-2, buff)
```

#### Expected behavior

It should fail for the following test case
[3, 10,10,10,10, 10,10,10,10, 10,10,10,10,4]

#### Additional context

The following code 
```
                if isSame:
                    count = end-beg+1
                    score = nums[beg-1] * nums[beg] * nums[beg+1] + nums[beg-1] * nums[end]* nums[end+1] + (count-2) * (nums[beg] **3)
```
should be updated to 
```
                if isSame:
                    count = end-beg+1
                    score = max(nums[beg-1], nums[end+1]) * nums[beg] * nums[beg+1] + nums[beg-1] * nums[end]* nums[end+1] + (count-2) * (nums[beg] **3)
```

**Comment by LC-Sue** [comment]
Hi @Chenfeng51 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Chenfeng51,
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username?

**Comment by Chenfeng51** [comment]
Hi Team, thanks for confirming it is useful.


My leetcode user name is ***@***.***  


Thanks!
















At 2022-01-15 09:12:06, "LC-Sue" ***@***.***> wrote:

Hi @Chenfeng51,
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LC-Sue** [comment]
Hi @Chenfeng51,
Please provide your LeetCode username! The last message is not readable!
