### ISSUE TITLE
Invalid Case - 849. Maximize Distance to Closest Person

### ISSUE THREAD

**Issue by kezarmader** [LeetCode-Feedback/LeetCode-Feedback#5786]
#### Your LeetCode username
kezarmader

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
We are trying to find an empty seat as stated in this statement
`Alex wants to sit in the seat such that the distance between him and the closest person to him is maximized. `
But the following test case doesn't seems to be right
```
Input: seats = [0,1]
Output: 1
```
The seats[1] = 1 i.e. that seat is already occupied. How can Alex sit on occupied seat?

#### Code you used for Submit/Run operation

```
class Solution:
    def maxDistToClosest(self, seats: List[int]) -> int:
        N = len(seats)
        left = [N] * N
        right = [N] * N
        
        for i in range(N):
            if seats[i] == 1:
                left[i] = 0
            elif i > 0:
                left[i] = left[i-1] + 1
                
        
        for i in range(N-1, -1, -1):
            if seats[i] == 1:
                right[i] = 0
            elif i < N-1:
                right[i] = right[i+1] + 1
        
        ans = 0
        for i in range(N):
            ans = max(ans, min(left[i], right[i]))
        
        return ans
```

#### Language used for code
python3

#### Expected behavior

The seat for this person should be 0, stating it's maximum distance. i.e. output: 0 and seats will be [A,1]. where A is Alex.

**Comment by LPRowe** [comment]
Hi @kezarmader thanks for sharing your concern!

You're right, Alex cannot sit in seat 1, so he must sit in seat 0. 

So his maximum distance from the nearest person will then be 1 (for the person sitting at index 1) minus 0 (the current seat he is sitting in) equals 1. 

So this is why the answer to this test case is 1.

**Comment by LC-Sue** [comment]
Hi @kezarmader,
Thank you for reaching out to us! Hope LPRowe's explanation was able to answer your question!
