### ISSUE TITLE
Add new function of default programming language 

### ISSUE THREAD

**Issue by ma77rix** [LeetCode-Feedback/LeetCode-Feedback#5788]
#### Category of the bug
- [*] Language

#### Description of the bug

After submitting to one question then open a new question, the language is always the last one I used. It would be very helpful, if I can have a default language.  Because every one has one language with the best knowledge than others.

**Comment by LC-Sue** [comment]
Hi @ma77rix,
Thank you for reaching out to us. I've relayed this feedback over to our team for future improvements!
