### ISSUE TITLE
Problem 88 Merge Sorted Array - invalid test case used to judge submissions

### ISSUE THREAD

**Issue by guerrila** [LeetCode-Feedback/LeetCode-Feedback#579]
Hello,

One of the test cases used to judge submissions has this input:

nums1: [0]
m: 1
nums2: [1]
n: 1

This test case looks invalid to me. The constraints of the problem say:

nums1.length == m + n
nums2.length == n

In this test case, nums1.length is not m + n.

Language used was Java. 

<img width="1054" alt="Screen Shot 2020-07-03 at 8 48 04 AM" src="https://user-images.githubusercontent.com/4129152/86483947-fcb07700-bd09-11ea-9015-5ebe50fa1aa8.png">

**Comment by lc-christina** [comment]
Hi @guerrila 
According to your screenshot, the test case's m is 0 instead of 1, which makes the test case meet the constraint 'nums1.length == m + n'

**Comment by guerrila** [comment]
But nums[1] contains one element, [0] ... so is the length not 1?
