### ISSUE TITLE
Invalid test case - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by r2d2o** [LeetCode-Feedback/LeetCode-Feedback#5790]
#### Your LeetCode username
yelvsusesu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Invalid Test Cases

#### Description of the bug
There is a test case with the following input, which I believe is wrong:
8
[4,1,8,4,5]
[5,6,1,8,4,5]
2
3

The linked lists first intersect at 1, not 8, so the test case should be modified to:
1
[4,1,8,4,5]
[5,6,1,8,4,5]
1
2

#### Code you used for Submit/Run operation

```
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, x):
#         self.val = x
#         self.next = None

class Solution:
    def getIntersectionNode(self, headA: ListNode, headB: ListNode) -> ListNode:

        nodeA = headA
        nodeB = headB
        
        lengthA = 0
        lengthB = 0
        
        while nodeA != None:
            lengthA += 1
            nodeA = nodeA.next
            
        while nodeB != None:
            lengthB += 1
            nodeB = nodeB.next

        minLength = min(lengthA, lengthB)

        nodeA = headA
        nodeB = headB

        if lengthA > lengthB:
            diff = lengthA - lengthB
            while diff != 0:
                nodeA = nodeA.next
                diff -= 1
        else:
            diff = lengthB - lengthA
            while diff != 0:
                nodeB = nodeB.next
                diff -= 1
        
        while minLength != 0:
            if nodeA.val == nodeB.val:
                return nodeA
            else:
                nodeA = nodeA.next
                nodeB = nodeB.next
                minLength -= 1
                
        return None
```

#### Language used for code
Python

#### Expected behavior
the test case should be modified to:
1
[4,1,8,4,5]
[5,6,1,8,4,5]
1
2

**Comment by LC-Sue** [comment]
Hi @r2d2o,
Thank you for reaching out to us. The test case appears to be correct. Please feel free to refer to the discuss section of the problem to see how others have optimized their codes!
