### ISSUE TITLE
Find the Town Judge

### ISSUE THREAD

**Issue by kshitija852** [LeetCode-Feedback/LeetCode-Feedback#5791]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @kshitija852 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
