### ISSUE TITLE
Some text not visible on browser

### ISSUE THREAD

**Issue by kyu-coder** [LeetCode-Feedback/LeetCode-Feedback#5793]
But those texts can be seen when inspected.
![one](https://user-images.githubusercontent.com/68824087/147907716-b41d851f-d99f-4910-98b5-e6f14ac99fe2.jpg)
![two](https://user-images.githubusercontent.com/68824087/147907735-215653a1-7928-4763-8486-747efab21bc1.jpg)

**Comment by LC-Sue** [comment]
Hi @kyu-coder,
Thank you for reaching out to us. This is not an error the text under the title are descriptions to the page and are fully visible once you click into the page!
