### ISSUE TITLE
`997. Find the Town Judge` - Erroneous code block in the solution

### ISSUE THREAD

**Issue by Fried-Chicken** [LeetCode-Feedback/LeetCode-Feedback#5794]
#### Your LeetCode username
Fried-Chicken

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a typo in the code block in the solution for [Find the town judge](https://leetcode.com/problems/find-the-town-judge/solution/)
In one of the code blocks in the explanation it shows.
```
for (int i = 1; i <= N; i++) {
    if (indegrees[i] == N - 1 && outdegrees[i] == 0) {
        return i;
    }
    return -1;
}
```
but I the `return -1;` should not be there as the final solution is
```
public int findJudge(int N, int[][] trust) {
    
    if (trust.length < N - 1) {
        return -1;
    }
    
    int[] indegrees = new int[N + 1];
    int[] outdegrees = new int[N + 1];

    for (int[] relation : trust) {
        outdegrees[relation[0]]++;
        indegrees[relation[1]]++; 
    }

    for (int i = 1; i <= N; i++) {
        if (indegrees[i] == N - 1 && outdegrees[i] == 0) {
            return i;
        }
    }
    return -1;
}
```

#### Code you used for Submit/Run operation
```
// Find the Town Judge
public int findJudge(int N, int[][] trust) {
    
    if (trust.length < N - 1) {
        return -1;
    }
    
    int[] indegrees = new int[N + 1];
    int[] outdegrees = new int[N + 1];

    for (int[] relation : trust) {
        outdegrees[relation[0]]++;
        indegrees[relation[1]]++; 
    }

    for (int i = 1; i <= N; i++) {
        if (indegrees[i] == N - 1 && outdegrees[i] == 0) {
            return i;
        }
    }
    return -1;
}
```

#### Language used for code
Java

#### Expected behavior
The `return -1` should not be in the loop

**Comment by LC-Sue** [comment]
Hi @Fried-Chicken 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Fried-Chicken 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
