### ISSUE TITLE
Missing Test Case - 567. Permutation in String

### ISSUE THREAD

**Issue by changgezuo** [LeetCode-Feedback/LeetCode-Feedback#5795]
#### Your LeetCode username

ChanggeZ

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✓ ] Missing Test Cases 

#### Description of the bug

in the test case 16, the input string s1 has a transferred meaning \"(while the question says it has only lowercase English letters.) when I try to debug it, just for clarity, I copy the test case into the console and find it in the debugger
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    bool checkInclusion(string s1, string s2) {
        int n1 = s1.size(), n2 = s2.size();
        vector<int>cnt1(26, 0);
        vector<int>cnt2(26, 0);
        for(int i = 0; i < n1; ++i){
            cnt1[s1[i] - 'a']++;
            cnt2[s2[i] - 'a']++;
        }
        if(cnt1 == cnt2)return true;
        for(int i = n1; i < n2; ++i){
            cnt2[s2[i] - 'a']++;
            cnt2[s2[i- n1] - 'a']--;
            if(cnt1 == cnt2)return true;
        }
        return false;
    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/49579699/147930102-6eb58a93-1217-486f-a75b-4e256f63117b.png)

![image](https://user-images.githubusercontent.com/49579699/147930122-1c2fa2ef-55b7-4caa-98d6-7709ef4efb54.png)

**Comment by LC-Sue** [comment]
Hi @changgezuo,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their code!
