### ISSUE TITLE
378. Kth Smallest Element in a Sorted Matrix

### ISSUE THREAD

**Issue by lawaloy** [LeetCode-Feedback/LeetCode-Feedback#5796]
There seems to be an error in how case 2 and case 3 are worded. Case 2 noted that the size of the left half is LESS than K, this should be mean we should be finding the K in the right half of the matrix, and the example given was if K is 3 and the size of the left half is 5 which contradict case 2: the size of the left half is LESS than K.

Case 3 noted that the size of the left half is MORE than K, this should mean we should be finding K in the left half of the matrix and the example given was if K is 7 and the left half is 5 which contradict case 3: the size of the left half is MORE than K

![Screenshot 2022-01-03 052659](https://user-images.githubusercontent.com/40930161/147935777-d73d59e7-8aae-4bc8-b2fb-1f7c20fbea1d.png)

![Screenshot 2022-01-03 052550](https://user-images.githubusercontent.com/40930161/147935656-2f765468-d576-4f0c-acd5-096a512efc6b.png)

**Comment by LC-Sue** [comment]
Hi @lawaloy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @lawaloy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
