### ISSUE TITLE
Leetcode - 377. Combination Sum IV

### ISSUE THREAD

**Issue by AbhishekRanjan624** [LeetCode-Feedback/LeetCode-Feedback#5799]
class Solution {
    public int combinationSum4(int[] nums, int target) {
        
       // creating dp array , target+1 length 
        int[] dp = new int[target+1] ;
        dp[0]=1 ;
        
        for(int i=0 ; i<dp.length ; i++){
           for(int j=0; j<nums.length ; j++){
               if(i>=nums[j]){
                   dp[i]=dp[i-nums[j]]+dp[i] ;
               }
           }    
        }
        
        return dp[dp.length-1] ;
    }
}

// leetcode 377 is based on permutation-518 and leetcode is based on combinationn

**Comment by LC-Sue** [comment]
Hi @AbhishekRanjan624 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
