### ISSUE TITLE
Wrong test case format for golang for https://leetcode.com/problems/maximal-square/

### ISSUE THREAD

**Issue by tagarwal** [LeetCode-Feedback/LeetCode-Feedback#58]
---
name: Bug report (English)
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**What kind of the bug**
- [ ] problem
- [ ] solution
- [*] language

**Describe the bug**
The input for the problem https://leetcode.com/problems/maximal-square/
is a two dimensional byte array. But the test inputs are strings. In golang
there is no intrinsic conversion from string to bytes. So one cannot pass
matrix: [][]byte{
					{"0", "1", "1", "1", "0"},
					{"1", "1", "1", "1", "1"},
					{"0", "1", "1", "1", "1"},
					{"0", "1", "1", "1", "1"},
					{"0", "0", "1", "1", "1"},
				},
**what language is your code written in**
golang

**The code you submit/run**
```
// Maximal Sum
func maximalSquare(matrix [][]byte) int {
	maxSquare := 0
	for j := 1; j < len(matrix[0]); j++ {
		for i := len(matrix) - 1; i >= 0; i-- {
			if matrix[i][j] == 1 {
				if i > 0 && j < len(matrix) {
					if matrix[i-1][j-1] >= 1 {
						//adding myself will form a square
						ps := matrix[i-1][j-1]
						pl := int(ps / 2)
						if ps == 1 {
							pl = 1
						}

						//since it is a square decrement both by same amount
						isSquare := true
						k,l := i,j
						for ; k >= i-pl && l >= j-pl; k, l = k-1, l-1 {
							if matrix[k][j] == 0 || matrix[i][l] == 0 {
								isSquare = false
								break
							}
						}
						if isSquare {
							matrix[i][j] = byte((pl + 1) * (pl + 1))
							if matrix[i][j] > byte(maxSquare) {
								maxSquare = int(matrix[i][j])
							}
						}
					}
				}
			}
		}
	}
	return maxSquare
}

```

**Expected behavior**
If I give the input as
```
matrix: [][]byte{
					{0, 1, 1, 1, 0},
					{1, 1, 1, 1, 1},
					{0, 1, 1, 1, 1},
					{0, 1, 1, 1, 1},
					{0, 0, 1, 1, 1},
				},
```
The maximal square returned should be 9

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @tagarwal,
Thank you for reaching out to us. I've filed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @tagarwal,
Thank you for your time. We found the issue to be caused by the incorrect input format of the test case, so please update the format accordingly. We appreciate your support.
