### ISSUE TITLE
820. Short Encoding of Words, Wrong output for test case 27/30

### ISSUE THREAD

**Issue by christianangel15** [LeetCode-Feedback/LeetCode-Feedback#580]
#### Your LeetCode username

christianangel15
#### Category of the bug
- [-] Solution

#### Description of the bug

test case 27/30 has output according to you - 13956 - that is all the values from test case.
According to my code i found a duplicate or repetition of characters in two values of test case so one of them should be removed from encoded code. so as per my code answer should be 13950.
I have attached Test case screenshot showing two repeating values. and also my code

#### Code you used for Submit/Run operation

```
class Solution:
    def minimumLengthEncoding(self, words: List[str]) -> int:
        ans = []
        for i in range(len(words)):
            for word in words:
                if (word in words[i]) and (word != words[i]):
                    ans.append(word)
        s = set(ans)
        for ele in s:
            words.remove(ele)
        s=set(words)
        s = '#'.join(s)
        return len(s)+1
```

#### Language used for code

Python

#### Expected behavior

According to my code i found a duplicate or repetition of characters in two values of test case so one of them should be removed from encoded code. so as per my code answer should be 13950

#### Screenshots

![encodewords](https://user-images.githubusercontent.com/65099862/86495131-ab21df80-bd3d-11ea-92b4-5ca2b91cb0fb.jpg)
![encodewordsTestCase](https://user-images.githubusercontent.com/65099862/86495132-ab21df80-bd3d-11ea-983e-8a084d785d74.jpg)

**Comment by lc-christina** [comment]
Hi @christianangel15 ,

For the first 'hlgfq' you highlighted in the test case, it's actually 'hlgfql'. I hope this answers your problem, thank you!

**Comment by christianangel15** [comment]
Exactly and we also have only 'hlgfq' so this one has to be removed from encoded code
