### ISSUE TITLE
Missing Test Case - 2040. Kth Smallest Product of Two Sorted Arrays

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#5801]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The *standard solution* fails on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7844139/1.txt)

#### Screenshots

![11](https://user-images.githubusercontent.com/11583428/147997612-c4fb7680-7e50-4d2f-ad41-2ca560613712.png)

#### Additional context

The standard solution overflows, thus showed "Invalid Testcase"; but the testcase is actually valid.

**Comment by LC-Sue** [comment]
Hi @hqztrue,
Thank you for reaching out to us. Would you be able to provide a code whether solution doesn't overflow? Since the test case is showing as invalid, I am unable to relay this issue over to our team!

**Comment by hqztrue** [comment]
The issue is this test case should be valid, as it meets all the problem constraints. The solution.cpp fails, thus the validator shows "Invalid Testcase".

**Comment by LC-Sue** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
