### ISSUE TITLE
Typo in 88. Merge Sorted Array Solution

### ISSUE THREAD

**Issue by singh486** [LeetCode-Feedback/LeetCode-Feedback#5802]
#### Your LeetCode username
singh486

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a typo in the `Approach 3 : Three Pointers (Start From the End)` solution of [88. Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array/solution/). Under the `Proof (optional)` section, the first sentence reads `You might be a bit sceptical of this claim.` which should read `You might be a bit skeptical of this claim.`

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
`Sceptical` should be spelled as `skeptical`.

#### Screenshots
<img width="783" alt="Screen Shot 2022-01-03 at 6 19 55 PM" src="https://user-images.githubusercontent.com/32406219/148000988-0d754ec6-affb-4108-9f3d-6f6343da1cd8.png">

#### Additional context
N/A

**Comment by LC-Sue** [comment]
Hi @singh486 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @singh486 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
