### ISSUE TITLE
Typo in 460. LFU Cache

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5803]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [460. LFU Cache](https://leetcode.com/problems/lfu-cache), there is a typo in the last line of the example.

According to the lines in Explanation, `cache=[]` will show the last used keys, where the leftmost key is the most recent. Therefore, in the last line of the example, the last used key is `4`, so `cache` should be `[4,3]` after the key `4` is used. However, `cache` is `[3,4]` in the last line of the example.

To make it clear, now the last four lines of the example are as follows.
```
lfu.get(3);      // return 3
                 // cache=[3,4], cnt(4)=1, cnt(3)=3
lfu.get(4);      // return 4
                 // cache=[3,4], cnt(4)=2, cnt(3)=3
```
The correct content of the last four line should be as follows.
```
lfu.get(3);      // return 3
                 // cache=[3,4], cnt(4)=1, cnt(3)=3
lfu.get(4);      // return 4
                 // cache=[4,3], cnt(4)=2, cnt(3)=3
```

Note that only the last line needs to be modified. I am putting the last four lines here to make the procedure more complete.

#### Expected behavior
Currently, the last line of the example is as follows.
```
                 // cache=[3,4], cnt(4)=2, cnt(3)=3
```
However, the correct value of `cache` in the last line should be `[4,3]`, so that the last line of the example should be as follows.
```
                 // cache=[4,3], cnt(4)=2, cnt(3)=3
```

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
