### ISSUE TITLE
Number of easy problems done is shown as 539/538

### ISSUE THREAD

**Issue by susanth29** [LeetCode-Feedback/LeetCode-Feedback#5804]
#### Your LeetCode username
boppanasusanth

#### Category of the bug
- [ ] problem count

#### Description of the bug
The number of easy problems solved is shown as 539/538 indicating I have solved 539 problems out of a total of 538 problems

#### Screenshots
![Leetcode_539_538](https://user-images.githubusercontent.com/49155218/148012152-2c46a7f2-f614-441e-bcd1-b7e9a16e4780.png)

**Comment by LC-Sue** [comment]
Hi @susanth29,
Thank you for reaching out to us, since this is not a content related issue I will close this ticket now. Please feel free to email us at support@leetcode.com
