### ISSUE TITLE
Missing Test Case - 1009. Complement of Base 10 Integer

### ISSUE THREAD

**Issue by Joecth** [LeetCode-Feedback/LeetCode-Feedback#5805]
#### Your LeetCode username

JoeH

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

`1009. Complement of Base 10 Integer` is exactly the same as `476. Number Complement`

#### Code you used for Submit/Run operation

```
// 1009

```

#### Expected behavior

- Merge 2 questions or mention both questions are the same

**Comment by Joecth** [comment]
`1009. Complement of Base 10 Integer` is the daily challenge today, 20220103
while
`476. Number Complement` is the daily challenge on 20211227

**Comment by stormsunshine** [comment]
It is already mentioned that the two questions are the same, in both problems. What is the problem?

**Comment by LC-Sue** [comment]
Hi @Joecth,
Thank you for reaching out to us. At the end of both problem, it mentions that both are the same!
