### ISSUE TITLE
Python2 code instead of Python3 in 278. First Bad Version

### ISSUE THREAD

**Issue by burner1992** [LeetCode-Feedback/LeetCode-Feedback#5807]
#### Your LeetCode username

NaN-NaN-NaN

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Default code for python3 offers python2 code.
```python
class Solution:
    def firstBadVersion(self, n-):
        """
        :type n: int
        :rtype: int
        """
````

#### Language used for code

Python3

#### Expected behavior

It should be:
```python
class Solution:
    def firstBadVersion(self, n:int) -> int:

````

#### Screenshots

![image](https://user-images.githubusercontent.com/81806802/148046250-70871807-1e5b-44d7-b40e-d52416178189.png)

**Comment by LC-Sue** [comment]
Hi @burner1992 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @burner1992 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
