### ISSUE TITLE
针对某道题，请问如何才能快速的查看自己是否书写过题解？

### ISSUE THREAD

**Issue by copbint** [LeetCode-Feedback/LeetCode-Feedback#581]
在已经提交过题解的情况下：
1. 题解页面无法识别出来自己是否写过题解
1)"写题解"按钮未置灰，点进去变成书写新的题解了...
2)用自己的昵称/id都搜索不到自己提交的题解
2. 自己提交的所有的题解页面也无法根据题号准确搜索

望优化！

**Comment by feiceh** [comment]
首先，非常感谢您对我们的支持，我会将您的诉求提交于我们的产品，我们会不断努力优化和提升我们的产品，给大家带来最佳的用户体验。
Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，后续有产品建议或其他问题欢迎点击链接（https://support.leetcode-cn.com/hc/kb/section/1115013/）提交工单反馈哦～
