### ISSUE TITLE
Ruby Compiler Throwing TLE even for the provided LeetCode Solution

### ISSUE THREAD

**Issue by ravishankar15** [LeetCode-Feedback/LeetCode-Feedback#5810]
#### Your LeetCode username
ravishankar2kool

#### Category of the bug
- [ ] Question
- [X]Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For the problem https://leetcode.com/problems/maximum-vacation-days The ruby code for this problem gets TLE even for O(n^2*k) solutions FYR, I even tried translating the exact java code given in the solution as well

#### Code you used for Submit/Run operation
```
# @param {Integer[][]} flights
# @param {Integer[][]} days
# @return {Integer}
def max_vacation_days(flights, days)
    cities = days.size; weeks = days.first.size

    return 0 if cities == 0 || weeks == 0

    dp = Array.new(cities) { Array.new(weeks+1, 0) }
    
    (weeks-1).downto(0) do |week|
        for cur_city in 0...cities
            dp[cur_city][week] = days[cur_city][week] + dp[cur_city][week+1]
            for dest_city in 0...cities
                if flights[cur_city][dest_city] == 1
                    dp[cur_city][week] = [days[dest_city][week] + dp[dest_city][week+1], dp[cur_city][week]].max
                end
            end
        end
    end
    dp[0][0]
end

```

#### Language used for code
Ruby

#### Expected behavior
The solution should pass without TLE

**Comment by LC-Sue** [comment]
Hi @ravishankar15,
Thank you for reaching out to us. I ran the code you provided and it was accepted. Please refer to https://leetcode.com/submissions/detail/617494551/
