### ISSUE TITLE
Missing Test Case - 706. Design HashMap

### ISSUE THREAD

**Issue by sandeshkaranam** [LeetCode-Feedback/LeetCode-Feedback#5812]
#### Your LeetCode username

sandeshkaranam1

#### Category of the bug
- [x] Question 705
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
["MyHashMap","put","put","get","get","put","get","remove","get"]
[[],[250005,1],[50005,2],[50005],[250005],[2,1],[2],[2],[2]]

#### Description of the bug

I have used key%100000 and my solution was accepted

#### Code you used for Submit/Run operation

```
class MyHashMap {
    int[] map;
     /** Initialize your data structure here. */
    public MyHashMap() {
        map = new int[100001];
        Arrays.fill(map,-1);
    }
    
    /** value will always be non-negative. */
    public void put(int key, int value) {
        map[key%100000]= value;
    }
    
    /** Returns the value to which the specified key is mapped, or -1 if this map contains no mapping for the key */
    public int get(int key) {
        return map[key%100000];
    }
    
    /** Removes the mapping of the specified value key if this map contains a mapping for the key */
    public void remove(int key) {
        map[key%100000] = -1;
    }
}

/**
 * Your MyHashMap object will be instantiated and called as such:
 * MyHashMap obj = new MyHashMap();
 * obj.put(key,value);
 * int param_2 = obj.get(key);
 * obj.remove(key);
 */
```

**Comment by LC-Sue** [comment]
Hi @sandeshkaranam 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sandeshkaranam,
Thank you for your time. Our team has reviewed this issue and decided not to add the test case. If we fail it, user can still change the size of the array 100001 to another number and the solution will still be accepted and it is nearly impossible to cover all the possible test cases of that type.
