### ISSUE TITLE
Missing Test Case - 83. Remove Duplicates from Sorted List

### ISSUE THREAD

**Issue by srujan-here** [LeetCode-Feedback/LeetCode-Feedback#5813]
Leetcode Username: Srujan1717

#### Category of the bug
- [ 83] Question
- [ ] Solution
- [ c++] Language
- [ 1] Missing Test Cases 

#### Description of the bug
Missing one test case

#### Expected behavior
If the head value is null, then there is no error in the console, so one the test case must be added.

**Comment by stormsunshine** [comment]
The test case with `head = null` already exists. What is the problem?

**Comment by srujan-here** [comment]
But even though I have not included that test case still it is running
properly

**Comment by stormsunshine** [comment]
Could you please provide the code?

**Comment by LC-Sue** [comment]
Hi @srujan-here,
Thank you for reaching out to us. Could you provide the code you used for submission and the test case you suggest adding?

**Comment by LC-Sue** [comment]
Hi @srujan-here 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
