### ISSUE TITLE
Typos in 736. Parse Lisp Expression

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#5814]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [736. Parse Lisp Expression](https://leetcode.com/problems/parse-lisp-expression), the Constraints part has "expression" with incorrect spell.

Now line 2 and line 3 of Constraints are as follows.

- There are no leading or trailing spaces in `exprssion`.
- All tokens are separated by a single space in `expressoin`.

In both lines, the words "expression" are incorrect.

The expected lines are as follows.

- There are no leading or trailing spaces in `expression`.
- All tokens are separated by a single space in `expression`.

#### Expected behavior
In Constraints, line 2 and line 3 should be changed with the correct spell of "expression".

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
