### ISSUE TITLE
308: Testcase evaluates incorrectly https://leetcode.com/problems/insert-delete-getrandom-o1/submissions/

### ISSUE THREAD

**Issue by vn17** [LeetCode-Feedback/LeetCode-Feedback#582]
Question: https://leetcode.com/problems/insert-delete-getrandom-o1/submissions/

18th Testcase fails even though there is an equal number of random numbers in the outputs in the expected and actual outputs.

**Comment by lc-christina** [comment]
Hi @vn17 , 
Thanks for reaching out to us. Can you please provide more information to help us understand the issue better? 
- Code you used for Submit/Run operation
- Language used for code
- Expected behavior
- Screenshots

**Comment by lc-christina** [comment]
Hi @vn17 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
