### ISSUE TITLE
Testcases and input parameters mismatch - 142. Linked List Cycle II

### ISSUE THREAD

**Issue by icamys** [LeetCode-Feedback/LeetCode-Feedback#5820]
#### Your LeetCode username
dmitrii_p

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I was working on the `142. Linked List Cycle II` task in Golang and it looks like there's a mismatch of the test case and the actual input parameters.

In the console the test case is displayed as an array and a number:
```
[3,2,0,-4]
1
```
and, as I understand, an integer output is expected.

However, the function, that is provided to be filled has a signature, that receives a pointer as a parameter and also returns a pointer:
```
func detectCycle(head *ListNode) *ListNode
``` 
As a result, even working solutions are rejected.

#### Language used for code
Go

#### Expected behavior
I believe that either the test case or the function signature should be changed in order to be able to meet the expectations.

#### Screenshots
Only pointers are used in the function signature, but other data types are used as use cases. 
![image](https://user-images.githubusercontent.com/6891299/148248084-237d6717-e320-4f53-b938-a82e521d0ddd.png)

**Comment by LC-Sue** [comment]
Hi @icamys,
Thank you for reaching out to us. The judger appears to be correct. There are a lot of accepted golang solutions that uses func detectCycle(head *ListNode) *ListNode. Please feel free to refer to the discuss section of the problem to see how others have optimized their golang codes!
