### ISSUE TITLE
Existing solution - 242. Valid Anagram

### ISSUE THREAD

**Issue by NeMaksym** [LeetCode-Feedback/LeetCode-Feedback#5822]
#### Your LeetCode username
NeMaksym

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An anagram is any word or phrase that exactly reproduces the letters in **another order** ([wiki](https://en.wikipedia.org/wiki/Anagram)). Therefore a word isn't an anagram of itself. 
When you run a test case where `s` and `t` are the same word, it expects to return `true` (`t` is an anagram of `s`)

#### Code you used for Submit/Run operation

Doesn't matter in this case, but find below:
```
var isAnagram = function(s, t) {
    if (s.length !== t.length) return false
    
    const hash = new Array(26).fill(0)
    
    for (let i = 0; i < t.length; i++) {
        const charCode = t.charCodeAt(i) - 97 // "97" is the ASCII code of "a"
        hash[charCode]++
    }
    
    let isAnagram = false
    
    for (let i = 0; i < s.length; i++) {
        const charCode = s.charCodeAt(i) - 97
        
        if (!hash[charCode]) return false
        hash[charCode]--
        
        if (s[i] !== t[i]) isAnagram = true
    }
    
    return isAnagram
};
```

#### Language used for code

JavaScript

#### Expected behavior

The test case where `s` and `t` is the same word (e.g. car) should expect `false` because a word isn't an anagram of itself.

**Comment by stormsunshine** [comment]
Don't try to modify a concept defined in a problem! A concept can be defined in the range of a problem without affecting the definition in other scenarios!

**Comment by NeMaksym** [comment]
**The problem definition is:**
"Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise."

**Testcase:**
`s` = "car"
`t` = "car" 

**Question:**
Is "car" an anagram of "car"? 
Could you please answer this question relying on facts and not evaluative ideas, such as _"concept defined in a problem"_? Otherwise, it's hard to discuss anything, since I can't know what is your definition of this _"concept"_.

In my opinion, "car" isn't an anagram of "car" because letters in an anagram are in another order by definition. But in our case, the order is the same. That's a fact.
Similarly, we don't consider words to be synonyms of themselves.

**Comment by LC-Sue** [comment]
Hi @NeMaksym 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @NeMaksym 
Thank you for your time. Our team has added the definition of Anagram. We did not mention the wiki's definition of Anagram, please only consider the problem itself and its definitions. We appreciate your support!
