### ISSUE TITLE
Missing Test Case - 1102. Path With Maximum Minimum Value

### ISSUE THREAD

**Issue by aotumangaming** [LeetCode-Feedback/LeetCode-Feedback#5824]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
  int[][] directions = {{-1, 0}, {0, 1}, {1, 0}, {0, -1}};
  
  public int maximumMinimumPath(int[][] A) {
    int n = A.length;
    int m = A[0].length;
    boolean[][] visited = new boolean[n][m];
    
    // in the BFS approach, for each step, we are interested in getting the maximum min that we have seen so far, thus we reverse the ordering in the pq
    Queue<int[]> pq = new PriorityQueue<>((a,b) -> b[2] - a[2]);
    
    pq.offer(new int[]{0, 0, A[0][0]});
    
    // BFS
    while (!pq.isEmpty()) {
      int[] cell = pq.poll();
      int row = cell[0];
      int col = cell[1];
        System.out.println(row + "" + col);
      
      if (row == n - 1 && col == m - 1) {
        return cell[2];
      }
      
      visited[row][col] = true;
      
      for (int[] dir : directions) {
        int nextRow = row + dir[0];
        int nextCol = col + dir[1];
        
        if (nextRow < 0 || nextRow >= n || nextCol < 0 || nextCol >= m || visited[nextRow][nextCol]) continue;
        
        // we are keeping track of the min element that we have seen until now
        pq.offer(new int[]{nextRow, nextCol, Math.min(cell[2], A[nextRow][nextCol])});
      }
    }
    return -1;
  }
}
```

**Comment by stormsunshine** [comment]
What is the missing test case?

**Comment by aotumangaming** [comment]
For the first example: <!—I think, based on question description, the result should be 1, but the expected answer is still 4. --> From: stormsunshineSent: Wednesday, January 5, 2022 7:24 PMTo: LeetCode-Feedback/LeetCode-FeedbackCc: aotumangaming; AuthorSubject: Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 1102. Path With Maximum Minimum Value (Issue #5824) What is the missing test case?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by stormsunshine** [comment]
Why do you think the result should be 1? The minimum value should be maximized. Since there exists a path 5 -> 4 -> 5 -> 6 -> 6 with minimum value 4, why do you prefer the path 5 -> 1 -> 100 -> 4 -> 6 with a smaller minimum value?

You can't deny that the path 5 -> 4 -> 5 -> 6 -> 6 exists in your test case that replaces 7 with 100.

> For the first example: <!—I think, based on question description, the result should be 1, but the expected answer is still 4. --> From: stormsunshineSent: Wednesday, January 5, 2022 7:24 PMTo: LeetCode-Feedback/LeetCode-FeedbackCc: aotumangaming; AuthorSubject: Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 1102. Path With Maximum Minimum Value (Issue #5824) What is the missing test case?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by LC-Sue** [comment]
Hi @aotumangaming,
Thank you for reaching out to us. The test case is correct. As stormsunshine mentioned, he minimum value should be maximized. Please feel free to refer to the discuss section of the problem to see how others have maximized their codes!
