### ISSUE TITLE
Typo in 1094. Car Pooling

### ISSUE THREAD

**Issue by rsha256** [LeetCode-Feedback/LeetCode-Feedback#5825]
#### Your LeetCode username
rsha256

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
It says:
"You are given the integer capacity and an array trips where trip[i] = [numPassengersi, fromi, to]"
in the question description.

#### Expected behavior
It should say:
"You are given the integer capacity and an array trips where trips[i] = [numPassengersi, fromi, to]"
as the variable `trips` is spelled incorrectly as `trip`.

#### Screenshots
![image](https://user-images.githubusercontent.com/28417128/148337137-77f41833-2ff0-4f69-8553-2ace6b24c821.png)

**Comment by LC-Sue** [comment]
Hi @rsha256 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @rsha256 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
