### ISSUE TITLE
Missing Test Case - 496. Next Greater Element I

### ISSUE THREAD

**Issue by Anuj-25** [LeetCode-Feedback/LeetCode-Feedback#5826]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def nextGreaterElement(self, nums1: List[int], nums2: List[int]) -> List[int]:
        ans = []
        index = 0
        for i in range(len(nums1)):
            index = nums2.index(nums1[i])
            for j in range(index+1,len(nums2)):
                if(nums1[i]<nums2[j]):
                    ans.append(nums2[j])
                    break
            if((i+1) != len(ans)):
                ans.append(-1)
        return ans
```

#### Expected behavior

[] Missing Test Case is
[5,4,3,2]
[1,3,10,57,5,4,7,9,12,2]

**Comment by LC-Sue** [comment]
Hi @Anuj-25,
Thank you for reaching out to us. The code and test case you provided were both accepted. Therefore, there is no missing test case. I will close this ticket now. Below is a screenshot of the accepted code and test case for your reference!
![image](https://user-images.githubusercontent.com/92285126/149038035-4293838d-fa50-4bd0-9d7e-0afec381df88.png)
