### ISSUE TITLE
Missing Test Case - 701. Insert into a Binary Search Tree

### ISSUE THREAD

**Issue by borundev** [LeetCode-Feedback/LeetCode-Feedback#5828]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Insertion into a non-existant BST is not checked

#### Code you used for Submit/Run operation

```
class Solution:
    def insertIntoBST(self, root: TreeNode, val: int) -> TreeNode:
        #if not root:
        #    root = TreeNode(val)
        #    return root
        prev=root
        while True:
            if val>prev.val:
                if not prev.right:
                    prev.right=TreeNode(val)
                    return root
                else:
                    prev=prev.right
            else:
                if not prev.left:
                    prev.left=TreeNode(val)
                    return root
                else:
                    prev=prev.left
```

#### Language used for code
Python3

#### Expected behavior
A new BST should be created with the value as the root

**Comment by stormsunshine** [comment]
The code above does not get accepted. The code can get accepted only if line 3 to line 5 are not commented.

There is already a test case where the original binary search tree is empty. Is there any problem?

**Comment by LC-Sue** [comment]
Hi @borundev,
Thank you for reaching out to us, the code that you provided does not get accepted. Thus, I cannot file a report to the team.
