### ISSUE TITLE
剑指 Offer 68 - I. 的TypeScript代码模板与其他语言的不同，并且执行结果不符合预期

### ISSUE THREAD

**Issue by HermitSun** [LeetCode-Feedback/LeetCode-Feedback#583]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
TypeScript代码模板里的函数签名与其他语言的不同。在别的语言模板中，参数里的p、q是`TreeNode`类型（或`TreeNode`的指针）；而在TypeScript的模板中，p、q变成了`number`类型。

C++模板：
```cpp
TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) { }
```

Java模板：
```java
public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) { }
```

Python3模板：
```python
def lowestCommonAncestor(self, root: 'TreeNode', p: 'TreeNode', q: 'TreeNode') -> 'TreeNode':
```

TypeScript模板：
```ts
function lowestCommonAncestor(root: TreeNode | null, p: number, q: number): TreeNode | null { };
```

可以明显看出不同。并且，使用C++是能正常通过的；别的语言不太熟悉，还没试过。
此外，执行结果会变成“数组”，导致无法通过。这个在后面的截图里补充。

**你使用的语言**
TypeScript

**你提交或者运行的代码**
```ts
function lowestCommonAncestor(root: TreeNode | null, p: number, q: number): TreeNode | null {
  const stack = [root];
  while (stack.length) {
    const current = stack.pop();
    if (current) {
      const left = Math.min(p, q),
        right = Math.max(p, q);
      if (left <= current.val && current.val <= right) return current;
      if (right < current.val) stack.push(current.left);
      if (left > current.val) stack.push(current.right);
    }
  }
  return null;
}
```

**期望行为**
1. 代码模板里的函数签名与其他语言一致。
2. 运行上面的代码能够正常通过。

**屏幕截图**
1. TypeScript代码模板
![image](https://user-images.githubusercontent.com/35923278/86516347-5a4fdb00-be52-11ea-91a2-e0f39bffa78e.png)
2. 异常的执行结果
![image](https://user-images.githubusercontent.com/35923278/86516337-4d32ec00-be52-11ea-9227-27c973f95229.png)

**额外的上下文**
无，复制进去运行即可。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
本题不支持 typescript ，当前已删除。
