### ISSUE TITLE
Java program for 'Approach 1: Two Arrays' not correct [997. Find the Town Judge]

### ISSUE THREAD

**Issue by hks1** [LeetCode-Feedback/LeetCode-Feedback#5830]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Java program provided for 'Approach 1: Two Arrays' solution is not correct.
It does not pass the test cases for N=1.

#### Code you used for Submit/Run operation

Here is my code with added handling for N=1
```
class Solution {
    public int findJudge(int n, int[][] trust) {
        if(n == 1){
            return 1;
        }
        if(trust.length < n-1) {
            return -1;
        }
        int[] outdegree = new int[n+1];
        int[] indegree = new int[n+1];
        for(int[] pair: trust){
            outdegree[pair[0]]++;
            indegree[pair[1]]++;
        }
        for(int i = 0; i <= n; i++){
            if(outdegree[i] == 0 && indegree[i] == n-1){
                return i;
            }
        }
        return -1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Solution provided should be able to handle N=1 scenario.

**Comment by LC-Sue** [comment]
Hi @hks1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hks1,
Thank you for your time. There is only one possible test case where N = 1, that is:

1
[]

The current Java and Python solutions do pass this test case.
