### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by paddymul** [LeetCode-Feedback/LeetCode-Feedback#5831]
#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

I implemented a different algorithm than the two pointer method, and it still passed the tests.

#### Code you used for Submit/Run operation

```
from collections import defaultdict
def find_max_area(heights):
    height_offsets = defaultdict(list)
    for i, h in enumerate(heights):
        height_offsets[h].append(i)
    sorted_heights = sorted(height_offsets.keys())[::-1]
    taller = sorted_heights[0]
    t_set = height_offsets[taller]
    max_area = 0
    for shorter in sorted_heights: #reuse taller in case there are two tallers
        s_set = height_offsets[shorter]
        offsets = s_set  + t_set
        candidate = (max(offsets) - min(offsets)) * shorter
        max_area = max([max_area, candidate])
        t_set = [max(offsets),  min(offsets)]
    return max_area
```

#### Language used for code
Python3 

#### Expected behavior
I expected my submission to fail

**Comment by stormsunshine** [comment]
What is the test case that makes the code fail?

**Comment by LC-Sue** [comment]
Hi @paddymul,
Thank you for reaching out to us, could you provide the test case that fails the code?

**Comment by paddymul** [comment]
The code doesn't fail.  It passes when I think it shouldn't.  I posted the
code in the original bug report.

**Comment by LC-Sue** [comment]
Hi @paddymul,
Thank you for your time, the code you provided no longer pass! We appreciate your time and support!
