### ISSUE TITLE
Python2 code instead of Python3 code in 702. Search in a Sorted Array of Unknown Size

### ISSUE THREAD

**Issue by burner1992** [LeetCode-Feedback/LeetCode-Feedback#5832]
#### Your LeetCode username

NaN-NaN-NaN

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I select Python3 as language it shows
```python
class Solution:
    def search(self, reader, target):
        """
        :type reader: ArrayReader
        :type target: int
        :rtype: int
        """
        
```
#### Expected behavior

It should be:

```python
class Solution:
    def search(self, reader:'ArrayReader', target:int)->int:
 ```

#### Screenshots

![image](https://user-images.githubusercontent.com/81806802/148424607-7fb6c8ea-ae52-4c57-93c1-dec72580f823.png)

**Comment by LC-Sue** [comment]
Hi @burner1992 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @burner1992 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
