### ISSUE TITLE
Typo in 138. Copy List with Random Pointer

### ISSUE THREAD

**Issue by calikw** [LeetCode-Feedback/LeetCode-Feedback#5836]
#### Your LeetCode username
russak

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I believe this question has a typo in an example case, as well as in the test case that mirrors the example.

The problem description says "A linked list of length n is given such that each node contains an additional random pointer, **which could point to any node in the list, or null**."  Thus, it seems that every pointer in the list should either point to a node in the list or null.

In the first example case, it seems there is a typo where the random pointer of node 11 points to a node that is **not** in the given list:

![e1](https://user-images.githubusercontent.com/24755950/148449273-136ab6e1-ced4-4aac-9e7e-4dced467e9e6.png)
`Input: head = [[7,null],[13,0],[11,4],[10,2],[1,0]]`
`Output: [[7,null],[13,0],[11,4],[10,2],[1,0]]`

In the text of this example, node 11 has a random pointer to a node 4, which is not a node in the list.  You can also see in the image posted along with the example case that shows node 11 should have a random pointer to node 1, not node 4.

And similarly, the first test case that is applied to the solution seems to have the same error -- which results in some otherwise valid solutions being flagged as incorrect.  The validation of the solution tests for node 11 to point to node 4, which does not actually exist in the original list.

#### Expected behavior
I believe the corrected example case #1 should read:
`Input: head = [[7,null],[13,0],[11,1],[10,2],[1,0]]`
`Output: [[7,null],[13,0],[11,1],[10,2],[1,0]]`

Or, the description of the problem should be changed (along with the example case illustration) to explain that random pointers are allowed to point to nodes not otherwise connected in the original main list.

#### Screenshots
Photo of the example case provided in the problem has been pasted above.

**Comment by stormsunshine** [comment]
Could you please read the problem description carefully? Each node is represented as a pair of `[val, random_index]`. Therefore, `[11,4]` means the random pointer of the node with value 11 points to the node with index 4. Do you mean that there are less than 4 nodes in the list?

According to your concern, the input should be `[[7,null],[13,7],[11,1],[10,11],[1,7]]`, which means all nodes with random pointers pointing to non-null nodes need to be changed. Why do you only change the value of the random pointer of the node with value 11?

**Comment by calikw** [comment]
Oh.  You're absolutely correct.  Apologies for my misreading of the description.  Thank you!
