### ISSUE TITLE
1909. Remove One Element to Make the Array Strictly Increasing

### ISSUE THREAD

**Issue by waldothedeveloper** [LeetCode-Feedback/LeetCode-Feedback#5837]
#### Your LeetCode username

waldothedeveloper

#### Category of the bug
~~Missing~~ Wrong Test Case 

#### Description of the bug
I believe - I might be wrong- that the following test case is expecting the wrong output: 

Input: [1,1]
Expected: true

The array [1,1] is NOT strictly increasing, or not even increasing. So I think the case should ```Expected: false```.
If we remove any of those numbers on the array, we are left with just ```[1]``` which is an array of just one number, how is this considered an increasing array then?

If my thinking is wrong, please let me know.

#### Code you used for Submit/Run operation

```
var canBeIncreasing = function(nums) {
  let index = 0
  const removeItem = (elem) => elem !== nums[index]
  const reducer = (prev, curr, idx, arr) => curr > prev ? true : false

  // if array has just one item pass
  if (nums.length === 1) return true

  while (index < nums.length) {
    const newArr = nums.filter(removeItem)
    const sortedNewArr = [...newArr].sort((a, b) => a - b)

    if (JSON.stringify(newArr) === JSON.stringify(sortedNewArr) && newArr.reduce(reducer, 0)) {
      return true
    } else {
      index++
    }
  }

  return false
};
```

#### Language used for code

Javascript

#### Expected behavior

Well, as stated in the description of the bug, an array like this one ```[1,1]``` is not a strictly increasing array, not even increasing. So the test case should expect ```false```.

#### Screenshots

![image](https://user-images.githubusercontent.com/16472274/148466406-447c7955-1064-45ce-a08e-5eecf0a3c403.png)

#### Additional context

https://leetcode.com/submissions/detail/614537098/

Appreciate the feedback if my reasoning is wrong.

**Comment by stormsunshine** [comment]
An array with one element is defined as a strictly increasing array. A strictly increasing array `arr` is an array that does not have any index `i` such that `arr[i] >= arr[i + 1]`.

**Comment by waldothedeveloper** [comment]
Got it...never mind
