### ISSUE TITLE
Missing Test Case - 1094. Car Pooling

### ISSUE THREAD

**Issue by himanshu1214** [LeetCode-Feedback/LeetCode-Feedback#5838]
#### Your LeetCode username
user5617C

#### Category of the bug
- [ ] Question carPooling
- [ ] Solution 
- [ ] Language
- [#] Missing/Wrong Test Cases 

#### Description of the bug
 For the test case
Input --> [[2,1,5]]
Ans: 4

#### Code you used for Submit/Run operation

```
// carPooling
My solution is  flawed : needs further iteration but I am stuck in this  testcase which seams wrong
        max_capacity = 0
        start, i = 0, 1
        _capacity = trips[start][0]
        
        
        trips = sorted(trips, key=lambda item: (item[1], item[2]))
        while start < len(trips) and i < len(trips):
            if trips[start][2] > trips[i][1]:  
                _capacity += trips[i][0]
            else:
                if _capacity > max_capacity:
                    max_capacity = _capacity
                    _capacity = trips[i][0]
                    start = i
            
            i += 1    
        if _capacity > max_capacity:
            max_capacity = _capacity 
  
            # print(trips[start][2],  trips[i][1], max_capacity)
                
        print(max_capacity)
        if capacity == max_capacity:
            return True
        else:
            False
```

#### Language used for code
 Python

#### Expected behavior
 Result should be 4 but the answer is 2.

**Comment by stormsunshine** [comment]
Problem 1094 requires returning a bool value. Why are you returning an int value?

**Comment by LC-Sue** [comment]
Hi @himanshu1214,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
