### ISSUE TITLE
Missing Test Case - 560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by chetnayadav2602** [LeetCode-Feedback/LeetCode-Feedback#5839]
#### Your LeetCode username

chetnayadav

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

Testcase for problem 560. Subarray Sum Equals K where array is [1,-1,0] and target is 0, the output expected is 3, however it should be 2 as per my understanding.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Only 2 subarrays are there with expected sum 0  : [[1,-1], [0]], no third subarray exists with sum as 0.

#### Screenshots

![image](https://user-images.githubusercontent.com/87397313/148488388-68700dd3-b5d5-450b-9e22-8299dac749d5.png)

**Comment by stormsunshine** [comment]
The correct answer is indeed 3. The subarrays with sum equal to 0 are as follows.
```
[1,-1]
[0]
[1,-1,0]
```

**Comment by chetnayadav2602** [comment]
> The correct answer is indeed 3. The subarrays with sum equal to 0 are as follows.
> 
> ```
> [1,-1]
> [0]
> [1,-1,0]
> ```

Ohh Yes. I missed that. Great, Thanks.
