### ISSUE TITLE
Meaningless Test cases Sequence reconstruction

### ISSUE THREAD

**Issue by kushalmahajan** [LeetCode-Feedback/LeetCode-Feedback#584]
The test case below does not make any sense for testing. Please remove this. Question already has high downvotes. 

```
[1]
[[],[]]

```

To the author: Please don't say sorry by writing stand alone discuss posts in general. Fixing the mistake is the best sorry for future users.

**Comment by lc-christina** [comment]
Hi @kushalmahajan 
Thank you for reaching out to us. Just to clarify, are you referring to question 444. https://leetcode.com/problems/sequence-reconstruction/? Can you please provide a screenshot or let me know where you found the invalid test case?

**Comment by kushalmahajan** [comment]
Yes I am talking about the 444 question.

I have already mentioned test case. You can verify yourself on the platform. I am sure you must have access to test cases.

**Comment by lc-christina** [comment]
Hi @kushalmahajan ,
Thank you for the confirmation. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @kushalmahajan 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
