### ISSUE TITLE
Missing Test Case - 237. Delete Node in a Linked List

### ISSUE THREAD

**Issue by oms674** [LeetCode-Feedback/LeetCode-Feedback#5840]
#### Your LeetCode username

Tony stark

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
[2,3,5,5,7]

#### Description of the bug

here what if duplicate values are present it will delete both the values.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case? Don't create meaningless issues!

**Comment by oms674** [comment]
Sorry, but i have selected the wrong question.
