### ISSUE TITLE
Part of example 1 is mistyped - 853. Car Fleet

### ISSUE THREAD

**Issue by Russianaleksey** [LeetCode-Feedback/LeetCode-Feedback#5855]
#### Your LeetCode username

alexmamontovprofessional

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The first example (example 1) for this question includes this as an example: 
```
The cars starting at 5 (speed 3) and 3 (speed 1) become a fleet, meeting each other at 6. The fleet moves at speed 1 until it reaches target.
```
The given arrays for position and speed have the car at position 5 with speed 1 and the car at position 3 with speed 3 which makes the example make sense.
Correct wording should be:
```
The cars starting at 5 (speed 1) and 3 (speed 3) become a fleet, meeting each other at 6. The fleet moves at speed 1 until it reaches target.
```

#### Code you used for Submit/Run operation

N/A

#### Language used for code

C#

**Comment by LC-Sue** [comment]
Hi @Russianaleksey 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Russianaleksey 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
