### ISSUE TITLE
Missing Test Case - 1427. Perform String Shifts

### ISSUE THREAD

**Issue by ImBenny2020** [LeetCode-Feedback/LeetCode-Feedback#5856]
#### Your LeetCode username

bennywang2018

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

If left shifts equal to right shifts, the function has to return the same input string.
However, it is supposed that no such test case exists. 
Hence, my code that, instead returns a null string, can pass the submission.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
string stringShift(string s, vector<vector<int>>& shift) {
        int n = s.size();
        int shiftAmount = 0;
        string ans;

        for(auto & v : shift)  // To determine the total amount of shifts.
        {
            if(v[0])
                shiftAmount += v[1];
            else
                shiftAmount -= v[1];
        }       
                
        if(shiftAmount < 0)  // Left shift.
        {
            shiftAmount = abs(shiftAmount) % n;
            ans = s.substr(shiftAmount) + s.substr(0, shiftAmount);
        }
        else if(shiftAmount > 0)  // Right shift.
        {
            shiftAmount = shiftAmount % n;
            ans = s.substr(s.size() - shiftAmount) + s.substr(0, s.size() - shiftAmount);
        }
        
        return ans;  _// If shiftAmount equals to zero, then returns nothing. But it passed the submission!_
    }
};
```

#### Language used for code

C++

#### Expected behavior

When left shifts are the same as right shifts, my code returns a null string.
If the above situation exists in the test cases during submission examination, my code cannot pass it.
But, it passed!

**Comment by ImBenny2020** [comment]
Sorry, I forgot to put my used test case.
Written as follows:
"acdedfghgfjdf"
[[1,3],[0,4],[1,1]]

**Comment by LC-Sue** [comment]
Hi @ImBenny2020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ImBenny2020 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by ImBenny2020** [comment]
Hi @LC-Sue,
You are welcome.
Thank you too for your team's careful consideration on this test case.
