### ISSUE TITLE
Small error in problem description - 382. Linked List Random Node

### ISSUE THREAD

**Issue by lehnerpat** [LeetCode-Feedback/LeetCode-Feedback#5857]
#### Your LeetCode username
[lehnerpat](https://leetcode.com/lehnerpat/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description
In the description of [problem 382](https://leetcode.com/problems/linked-list-random-node/), it say:

> * `Solution(ListNode head)` Initializes the object with the integer array nums.

The explanation of the ctor/initializer calls the argument an "integer array nums" even though it's a ListNode called "head".

#### Suggestion
The description should be changed to something like:

* `Solution(ListNode head)` Initializes the object with the singly-linked list head.

**Comment by LC-Sue** [comment]
Hi @lehnerpat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @lehnerpat 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
