### ISSUE TITLE
Missing Test Case - 163. Missing Ranges

### ISSUE THREAD

**Issue by mkryuk** [LeetCode-Feedback/LeetCode-Feedback#5858]
#### Your LeetCode username
mkryuk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The next test case is missing:
**Input**: nums: number[] = [], lower = 0, upper = 1;
**Output**: ["0->1"]

Currently, there is no difference if the result for the case above will be ["0", "1"] or ["0->1"] but this contradicts the requirements.

The requirements are : 
Each range [a,b] in the list should be output as:

"a->b" if a != b
"a" if a == b

So the code below will pass successfully

#### Code you used for Submit/Run operation

```
// Missing Ranges
function findMissingRanges(
  nums: number[],
  lower: number,
  upper: number
): string[] {
  let result: string[] = [];
  let prev = lower - 1;
  // this will return ["0","1"] instead of ["0->1"] for
  // nums = [], lower = 0, upper = 1
  if (nums.length === 0 && upper - lower === 1) {
    return [`${lower}`, `${upper}`];
  }
  for (let i = 0; i <= nums.length; i++) {
    let curr = (i < nums.length) ? nums[i] : upper + 1;
    if (prev + 1 <= curr - 1) {
      result.push(formatRange(prev + 1, curr - 1));
    }
    prev = curr;
  }
  return result;
}

function formatRange(lower: number, higher: number): string {
  return lower === higher ? `${lower}` : lower + "->" + higher;
}
```

#### Language used for code
**TypeScript** 

#### Expected behavior

**Input**: nums: number[] = [], lower = 0, upper = 1;
**Expected output**: ["0->1"]

**Comment by LC-Sue** [comment]
Hi @mkryuk,
Thank you for reaching out to us, could you provide the test case that you suggest adding?

**Comment by mkryuk** [comment]
Hi @LC-Sue, for TypeScript it should be like:
```typescript
it('should return ["0->1"] for nums = [], lower = 0, upper = 1', function () {
  const nums: number[] = [],
    lower = 0,
    upper = 1;
  const result = findMissingRanges(nums, lower, upper);
  expect(result).toEqual(["0->1"]);
});
```

**Comment by LC-Sue** [comment]
Hi @mkryuk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @mkryuk 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
