### ISSUE TITLE
1505. Minimum Possible Integer After at Most K Adjacent Swaps On Digits

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#586]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing test cases

#### Code you used for Submit/Run operation

```
class Solution:
    def minInteger(self, num: str, k: int) -> str:
        n = len(num)
        if k >= n*(n-1)//2: return "".join(sorted(num)) #special case
        
        #find smallest elements within k swaps 
        #and swap it to current position 
        num = list(num)
        for i in range(n):
            if not k: break 
            #find minimum within k swaps
            ii = i
            for j in range(i+1, min(n, i+k+1)): 
                if num[ii] > num[j]: ii = j 
            #swap the min to current position 
            if ii != i: 
                k -= ii-i
                for j in range(ii, i, -1):
                    num[j-1], num[j] = num[j], num[j-1]
        return "".join(num)
```

#### Language used for code
Python3

#### Expected behavior
Accepted solution fails the test case. Too large to paste.
[New Text Document.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4874478/New.Text.Document.txt)

**Comment by lc-christina** [comment]
Hi @leet212 
Thanks for reaching out to us! I submitted the code you provided several times and they all received Time Limit Exceeded so I'll close the ticket. Feel free to reach out if you have other questions!
