### ISSUE TITLE
Missing Test Case - 1813. Sentence Similarity III

### ISSUE THREAD

**Issue by v1k1nghawk** [LeetCode-Feedback/LeetCode-Feedback#5865]
#### Your LeetCode username
AndrewArt

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My submitted code was successfully accepted and passed all 135/135 test cases, but this accepted code failed on my custom test case. I want this test case to be added to evaluate future submissions.
My custom test case:
"z z z z"
"zz z"

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool areSentencesSimilar(string sentence1, string sentence2) {
        if (sentence1 == sentence2)
            return true;

        unsigned int insertion_size = abs(static_cast<long long>(sentence1.size()) - static_cast<long long>(sentence2.size()));
        if (insertion_size < 2)
            return false;

        string tmp;
        if (sentence2.size() > sentence1.size()) {
            tmp = sentence2;
            sentence2 = sentence1;
            sentence1 = tmp;
        }

        for (unsigned int insert_idx = 0; insert_idx <= sentence1.size() - insertion_size; ++insert_idx) {
            tmp = sentence1;
            tmp = tmp.replace(insert_idx, insertion_size, "");
            if (tmp == sentence2) {
                tmp = sentence1.substr(insert_idx, insertion_size);
                if ((insert_idx == 0 && (tmp.back() == ' ' || sentence1.at(insert_idx + insertion_size) == ' ')) ||
                    (insert_idx == sentence1.size() - insertion_size && (tmp.front() == ' ' || sentence1.at(insert_idx - 1) == ' ')) ||
                    (insert_idx != 0 && insert_idx != sentence1.size() - insertion_size && (tmp.front() == ' ' || sentence1.at(insert_idx - 1) == ' ') && (tmp.back() == ' ' || sentence1.at(insert_idx + insertion_size) == ' '))) {
                    return true;
                }
            }
        }
        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior

My accepted code produce wrong output = 'true' on my custom test case, but the Judge's fully correct output is 'false'. Despite this, the code passed all available test cases and successfully submitted, although it should not be accepted.

**Comment by LC-Sue** [comment]
Hi @v1k1nghawk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @v1k1nghawk 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
