### ISSUE TITLE
Test Case with More Valid Answers - 1337. The K Weakest Rows in a Matrix

### ISSUE THREAD

**Issue by wang2700** [LeetCode-Feedback/LeetCode-Feedback#5869]
#### Your LeetCode username
jerrywangpico

#### Category of the bug
- [*] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The sample test case 1 in the question description has another valid solution. The current description shows [2,0,3] as the only valid solution, but [2, 3, 0] is also valid since row 0 and row 3 both has 2 soldiers. 

#### Code you used for Submit/Run operation

```
// The K Weakest Rows in a Matrix
class Solution {
    public int[] kWeakestRows(int[][] mat, int k) {
        // count the number of soldiers in each row
        int[] soldierCount = new int[mat.length];
        for (int r = 0; r < mat.length; r++) {
            int sum = 0;
            for (int p : mat[r]) {
                sum += p;
            }
            soldierCount[r] = sum;
        }
        // use priority queue to find the k smallest row
        Queue<Integer> heap = new PriorityQueue<>(k, (n1, n2) -> soldierCount[n2] - soldierCount[n1]);
        for (int i = 0; i < mat.length; i++) {
            heap.offer(i);
            if (heap.size() > k) {
                heap.poll();
            }        
        }
        int i = k-1;
        int[] res = new int[k];
        while (heap.size() > 0) {
            res[i--] = heap.poll();
        }
        return res;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The answer for the first test case should allow [2, 3, 0] as a correct answer

**Comment by LC-Sue** [comment]
Hi @wang2700,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
