### ISSUE TITLE
893. 特殊等价字符串组, 题目描述不清楚, 而且翻译不准确.

### ISSUE THREAD

**Issue by bytebeats** [LeetCode-Feedback/LeetCode-Feedback#587]
在问题 [893. 特殊等价字符串组](https://leetcode-cn.com/problems/groups-of-special-equivalent-strings/) / [893. Groups of Special-Equivalent Strings](https://leetcode.com/problems/groups-of-special-equivalent-strings/) 的描述中, 存在诸多问题, 包括但不限于: 1, 题目描述不清楚. 2, 翻译不准确. 3, 用例存在翻译偷工减料的问题.

具体表现在: 

### 1, 题目描述中少了一段示例解释. 
英文原文为: 
**For example, S = "zzxy" and T = "xyzz" are special-equivalent because we may make the moves "zzxy" -> "xzzy" -> "xyzz" that swap S[0] and S[2], then S[1] and S[3].** 
这段文字翻译中并不存在, 我想这会影响对题目真实意思的表达. 可能的翻译为: **例如, S = "zzxy" 和 T = "xyzz"是特殊等价字符串, 因为我们可以通过先交换S[0]和 S[2], 再交换 S[1]和 S[3], 而达成移动"zzxy" -> "zxxy" -> "xyzz"**.

### 2, 用例缺少解析. 
比如缺少用例1: 
**Input: ["abcd","cdab","cbad","xyzz","zzxy","zzyx"]
Output: 3
Explanation: 
One group is ["abcd", "cdab", "cbad"], since they are all pairwise special equivalent, and none of the other strings are all pairwise special equivalent to these.

The other two groups are ["xyzz", "zzxy"] and ["zzyx"].  Note that in particular, "zzxy" is not special equivalent to "zzyx".** 我想缺少这个示例的翻译之后, 读者对该题目的题意的理解, 是存在挺大的费解的. 可能解析翻译为: **一组字符串["abcd", "cdab", "cbad"], 因为它们便是成对出现的特殊等价字符串, 没有其它字符串跟这些特殊等价字符串配对**.

希望这题目的中文版, 能够得到优化.

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
已更新题目描述，力扣会定期更新，保障稳定和体验优化。
