### ISSUE TITLE
Typo "uniform" in Keys to Design a Hash Table

### ISSUE THREAD

**Issue by isaacpittman** [LeetCode-Feedback/LeetCode-Feedback#5870]
#### Your LeetCode username
isaacpittman

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ X] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the page [Keys to Design a Hash Table](https://leetcode.com/explore/learn/card/hash-table/182/practical-applications/1110/) under the heading *1. Hash Function*, there is a typo.
> The idea is to try to assign the key to the bucket as uniform as you can.

should be

> The idea is to try to assign the key to the bucket as uniformly as you can.

**Comment by LC-Sue** [comment]
Hi @isaacpittman 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @isaacpittman 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
