### ISSUE TITLE
Typo in Heap explore card

### ISSUE THREAD

**Issue by sagarruchandani** [LeetCode-Feedback/LeetCode-Feedback#5871]
#### Your LeetCode username
sagar1989

#### Category of the bug
Heap Card in Explore

#### Description of the bug
Top K problem -Approach 1 -> Solution of the Top K largest elements -> Step 4. Typo. It should be "elements" instead the sentence says "lements"

#### Screenshots
<img width="838" alt="Screen Shot 2022-01-07 at 4 31 20 PM" src="https://user-images.githubusercontent.com/4075650/148623732-a6e15b4d-891e-47b2-9644-7fb6d7fc3300.png">

**Comment by LC-Sue** [comment]
Hi @sagarruchandani 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sagarruchandani 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
