### ISSUE TITLE
1689. Incorrect testcase

### ISSUE THREAD

**Issue by abrahma** [LeetCode-Feedback/LeetCode-Feedback#5873]
To form number 23 = 11 + 11 + 01
Here, 01 is not deci-binary as it has leading zero. This number can't be formed. 
But the answer for 23 is provided as 3.

**Comment by LC-Sue** [comment]
Hi @abrahma,
Thank you for reaching out to us. Could you provide the problem number for the issue, as well as the code used for submission!

**Comment by abrahma** [comment]
Hi,

The problem number is 1689. The issue is with judge solution of leetcode.

**Comment by LC-Sue** [comment]
Hi @abrahma,
Thank you for your time, the test case is correct.
23=11+11+1 where all the three numbers are deci-binary and don't have leading zeros.
