### ISSUE TITLE
Leetcode- 344. Reverse String

### ISSUE THREAD

**Issue by arpita-sharma-25** [LeetCode-Feedback/LeetCode-Feedback#5874]
class Solution {
    public void reverseString(char[] s) {
        
        int i=0;
        int j=s.length-1;
        while(j>i){
            char temp=s[i];
            s[i]=s[j];
            s[j]=temp;
            
            i++;
            j--;
        }
    }
}

**Comment by LC-Sue** [comment]
Hi @arpita-sharma-25 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
