### ISSUE TITLE
Mispelling in problem description - 541. Reverse String II

### ISSUE THREAD

**Issue by TowhidKashem** [LeetCode-Feedback/LeetCode-Feedback#5876]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

"Leave" is written as "left" in the problem description

> then reverse the first k characters and **left** the other as original.

should be:

> then reverse the first k characters and **leave** the other as original.

**Comment by dipak122** [comment]
should I do this changes

**Comment by LC-Sue** [comment]
Hi @TowhidKashem 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @TowhidKashem 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
