### ISSUE TITLE
Missing Test Case - 2131. Longest Palindrome by Concatenating Two Letter Words

### ISSUE THREAD

**Issue by merelj** [LeetCode-Feedback/LeetCode-Feedback#5877]
#### Your LeetCode username

georgiiperepechko

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Either question or solution should be changed. 2 types of palindrome are not included:
- 1-letter palindromes
- palindromes of partially mirrored words

#### Code you used for Submit/Run operation

```
function longestPalindrome(words: string[]): number {
    const counter: Record<string, number> = {}; // aa (2), ab/ba (4), ba/ad (2), xz (1)
    const firstLetters = new Set();
    let foundPartial = false;
    let foundMiddle = false;
    let length = 0;
    for (const word of words) {
        counter[word] = (counter[word] ?? 0) + 1;
    }

    for (const [word, count] of Object.entries(counter)) {
        const reversed = word[1] + word[0];
        const reversedCount = counter[reversed];
        let withoutPair = ''
        if (word != reversed) {
            if (reversedCount) {
                const min = Math.min(count, reversedCount);
                if (count != reversedCount) {
                    withoutPair = count > reversedCount ? word : reversed;
                }
                length += min * 2;   
            } else {
                withoutPair = word;
            }
        } else {
            const halves = Math.floor(count / 2)
            length += halves * 4;
            if (!foundMiddle && halves != count / 2) {
                foundMiddle = true;
            }
        }
        // if (withoutPair && !foundPartial) { ERROR: "ab" and "bz" can add up to "abbz" with palindrome "bb"
        //     firstLetters.add(word[0]);
        //     if (firstLetters.has(word[1])) {
        //         foundPartial = true;
        //     }
        // }
    }
    
    if (foundMiddle) {
        length += 2;
    }
    if (foundPartial) {
        length += 2;
    }
    // if (length === 0) { // ERROR: "ab"'s longest palindrome is 'a' or 'b' :/
    //     return 1;
    // }
    return length;
};
```

#### Language used for code

Typescript

#### Expected behavior

- if the array is not empty, the shortest palindrome length is 1 (example: `ab`'s shortest palindrome is "a" or "b")
- if the array has elements unusable as parts of palindromes but containing mirrored letters, 2 additional letters can be used in palindrome (example: `ab, bc, dd, ef, fz` contains palindromes `(a)bddb(c)` (4 letters) and `(e)fddf(z)` (4 letters).

#### Screenshots

Not applicable

#### Additional context

Not applicable

**Comment by stormsunshine** [comment]
Your unstanding of the problem is incorrect. If you select x strings to form a palindrome, then the palindrome must have length 2x. You can't select a proper substring (a substring shorter than the original string) of the string with length 2x.

For example, if you select "abddbc", then the string must have length 6. Since it is not a palindrome, it does not meet the requirement. You can't select a proper substring "bddb" to form a substring, since all the strings selected must be complete.

**Comment by merelj** [comment]
hm. ok. got it.
