### ISSUE TITLE
1024. Video Stitching

### ISSUE THREAD

**Issue by arahatashun** [LeetCode-Feedback/LeetCode-Feedback#588]
#### Your LeetCode username

readonly_true

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The description of Example 2 is wrong.
```
Input: clips = [[0,1],[1,2]], T = 5
Output: -1
Explanation: 
We can't cover [0,5] with only [0,1] and [0,2].
```
#### Expected behavior

```
Input: clips = [[0,1],[1,2]], T = 5
Output: -1
Explanation: 
We can't cover [0,5] with only [0,1] and [1,2].
```

**Comment by lc-christina** [comment]
Hi @arahatashun 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
