### ISSUE TITLE
Unexpected int calculation - 227. Basic Calculator II int(-3/2) = -2 not -1

### ISSUE THREAD

**Issue by Cby19961020** [LeetCode-Feedback/LeetCode-Feedback#5880]
#### Your LeetCode username

Cby19961020

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x ] Language
- [ ] Missing Test Cases 

#### Description of the bug

when using python int(-3/2) is equal to -2 when really I was expecting -1.

#### Code you used for Submit/Run operation

```
\\\227. Basic Calculator II
class Solution(object):
    def calculate(self, s):
        """
        :type s: str
        :rtype: int
        """
        symbolList = []
        stack = []
        
        for i in range(len(s)):
            if (s[i] == '/' or s[i] == '*' or s[i] == '+' or s[i] =='-'):
                symbolList.append(i)
                
        if not symbolList:
            return int(s)

        symbolList.append(len(s))        
        start = 0
        needToMultiply = False
        ans = 0 
        
        for symbolIndex in symbolList:

            if needToMultiply:
                temp = stack.pop()
                if s[start-1] == '/': 
                    
                    print('{}/{} = {}'.format(temp, int(s[start : symbolIndex]), temp / int(s[start : symbolIndex])))
                    
                    temp /= int(s[start : symbolIndex])
                else:
                    temp *= int(s[start : symbolIndex])
                stack.append(temp)
                needToMultiply = False
                
            else:
                if s[start-1] == '-':
                    stack.append(int(s[start-1 : symbolIndex]))
                else:
                    stack.append(int(s[start : symbolIndex]))      
            
            if (symbolIndex < len(s) and (s[symbolIndex] == '/' or s[symbolIndex] == '*')):
                needToMultiply = True
                
            start = symbolIndex + 1

        while(stack):
            ans += stack.pop()
        
        return ans
```

#### Language used for code

Python

#### Expected behavior

I don't know if it is because of the python version leetcode is using or something else but on my local IDE int(-3/2) = -1 and that was what I was expecting

#### Screenshots

![image](https://user-images.githubusercontent.com/44323738/148667771-a2b2a3b8-918b-4f96-aecb-360fd86a6142.png)

**Comment by stormsunshine** [comment]
The problem description mentions: "The integer division should truncate toward zero." Therefore, the test case is correct, and you should modify your code to get the correct result.

**Comment by LC-Sue** [comment]
Hi @Cby19961020,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
