### ISSUE TITLE
disjoint set video joining by rank

### ISSUE THREAD

**Issue by lorinchever** [LeetCode-Feedback/LeetCode-Feedback#5882]
#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The video explanation use the wrong order of x, y to build the maximum length tree 0:54
https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3879/
```
       uf.union(0, 1);
        uf.union(0, 2);
        uf.union(0, 3);
        uf.union(0, 4);
        uf.union(0, 5);
```
will result in an array of 
```
[0,0,0,0,0,0]
```
which is flat

#### Code you used for Submit/Run operation

The right code would be
```
        uf.union(1, 0);
        uf.union(2, 0);
        uf.union(3, 0);
        uf.union(4, 0);
        uf.union(5, 0);
```

So the correct annotation in the video would be 

(1,0)
(2,0)
(3,0)
(4,0)
(5,0)

although it's still upside down. 

At the end it's not a big deal just increase the cognitive load.

**Comment by LC-Sue** [comment]
Hi @lorinchever 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @lorinchever 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
