### ISSUE TITLE
608. 树节点 编译器出了问题， select * 也无法查出原表的内容

### ISSUE THREAD

**Issue by Eyjan-Huang** [LeetCode-Feedback/LeetCode-Feedback#5883]
**你的 LeetCode 用户名**
Eyjan_

**Bug 类型**
- 608. 树节点

**描述**
页面编译器有问题？我是会员但是这道题我用最基本的select *都查不到表格

**你使用的语言**
MySQL

**你提交或者运行的代码**
```
SELECT * FROM Tree
```

**期望行为**
最起码要有个结果能出来，一开始我以为是我语法错了，现在用最基本的查表都查不到

**屏幕截图**
![image](https://user-images.githubusercontent.com/81480748/148670957-3c753cb0-feb2-4491-9d73-375039eb837d.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@Eyjan-Huang 你好，当前题目问题已更新，ID：somnabulistic_cub_	给予积分奖励，请查收。
