### ISSUE TITLE
Typo in solution of 154. Find Minimum in Rotated Sorted Array II

### ISSUE THREAD

**Issue by burner1992** [LeetCode-Feedback/LeetCode-Feedback#5884]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typo in solution:

> Therefore, the desired **minium** element should reside to the right-hand side of the pivot element. As a result, we then move the lower bound up next to the pivot index, i.e. low = pivot + 1.

#### Expected behavior

It should be:
> Therefore, the desired **minimum** element should reside to the right-hand side of the pivot element. As a result, we then move the lower bound up next to the pivot index, i.e. low = pivot + 1.

**Comment by LC-Sue** [comment]
Hi @burner1992 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @burner1992 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
