### ISSUE TITLE
Missing coordinate system definition in description - 1041. Robot Bounded In Circle

### ISSUE THREAD

**Issue by lehnerpat** [LeetCode-Feedback/LeetCode-Feedback#5887]
#### Your LeetCode username
[lehnerpat](https://leetcode.com/lehnerpat/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description of problem "[1041. Robot Bounded In Circle](https://leetcode.com/problems/robot-bounded-in-circle/)" mentions that the robot is initially facing "north" but does not define what "north" means in terms of the coordinate system.
As always, there are conflicting assumptions about the orientation of the coordinate system due to computer screens being oriented right-down while scientific coordinate systems are usually oriented right-up.
So while I expected "north" to be the negative y-direction, example 3 shows that it's oriented in the positive y-direction.
This should be mentioned explicitly in the description.

#### Suggestions
Adjust the first sentence of the description like:

> On an infinite plane, a robot initially stands at `(0, 0)` and faces north (i.e. toward the positive y-direction).

**Comment by LC-Sue** [comment]
Hi @lehnerpat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @lehnerpat,
Thank you for your time, our team has reviewed the problem and added more explanation to the statement and the examples.
