### ISSUE TITLE
Missing Test Case - 1041. Robot Bounded In Circle

### ISSUE THREAD

**Issue by shubham-aneja** [LeetCode-Feedback/LeetCode-Feedback#5888]
#### Your LeetCode username
shubham-aneja

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In this problem, Example 3, the Explanation seems to be incorrect.
```
Input: instructions = "GL"
Output: true
Explanation: The robot moves from (0, 0) -> (0, 1) -> (-1, 1) -> (-1, 0) -> (0, 0) -> ...
```

#### Expected behavior
When the robot started in the second cycle, he is facing left of north, so from (-1,1), it should go (-2, 1) and not (-1, 0)
```
Input: instructions = "GL"
Output: true
Explanation: The robot moves from (0, 0) -> (0, 1) -> (-1, 1) -> (-2, 1) -> (-2, 0) -> (-2, -1) -> (-1,-1) -> (0,0)
```

**Comment by LC-Sue** [comment]
Hi @shubham-aneja 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @shubham-aneja,
Thank you for your time, our team has reviewed this issue and added more explanation to the statement and the examples.
