### ISSUE TITLE
Typo in solution of 647. Palindromic Substrings

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#5889]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question: [647. Palindromic Substrings](https://leetcode.com/problems/palindromic-substrings/)
In "Approach # 1: Check All Substrings" -> "Complexity Analysis" -> "Time Complexity", it writes:

- `N` substrings of size `1`.
- `N-1` substrings of size `2`.
- `N-3` substrings of size `3`.

#### Expected behavior

But it's actually "`N-2` substrings of size`3`", and the formula below uses `3 * (N-2)` as well (which is correct).

#### Screenshots

![image](https://user-images.githubusercontent.com/31957845/148695710-e1d62eb4-4db3-43fc-af87-414b300148da.png)

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
