### ISSUE TITLE
1502. Can Make Arithmetic Progression From Sequence – missing test case

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#589]
#### Your LeetCode username
metricquant

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
My solution gets accepted, but goes into an infinite loop on a particular boundary case.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool canMakeArithmeticProgression(vector<int>& arr) {
        int m = *min_element(arr.begin(), arr.end()), M = *max_element(arr.begin(), arr.end()), L = arr.size();
        
        if((M - m) % (L - 1) != 0)
            return false;
        
        int d = (M - m) / (L - 1);
        
        int i = 0;
        while(i < arr.size()) {
            if(arr[i] == m + i * d) {
                i++;
                continue;
            }
            
            if((arr[i] - m) % d != 0)
                return false;
            
            int k = (arr[i] - m) / d;
            
            swap(arr[i], arr[k]);
        }
        
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
There should be a test case where `arr[i] == arr[k] = m + k * d` with `i != k` (e.g. `[1, 2, 2, 4]`). That will send the accepted solution above into an infinite loop.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
