### ISSUE TITLE
Support [Dart] Language

### ISSUE THREAD

**Issue by II11II** [LeetCode-Feedback/LeetCode-Feedback#5890]
Dart has become more popular these days. Any chance this could make it on the roadmap? The SDK is similar to other interpreted languages like Python [Dart sdk](https://www.dartlang.org/tools/sdk)

**Comment by LC-Sue** [comment]
Hi @II11II,
Thank you for reaching out to us. I've relayed this feedback over to our team for future improvements!

**Comment by II11II** [comment]
@LC-Sue has it been implemented?

**Comment by ISL270** [comment]
Yes please we need it as soon as possible.

**Comment by AnuragBishnoi** [comment]
Any update guys ?

**Comment by iahmadamin** [comment]
I have checked some problems and there was the option to solve them in Dart programming language but I am not sure LeetCode support for all problems or not.
