### ISSUE TITLE
21题官方题解不严谨

### ISSUE THREAD

**Issue by Niklaus-LY** [LeetCode-Feedback/LeetCode-Feedback#59]
** Bug 类型**
- [√ ] 题目
- [√ ] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
第21题，题目只是要求合并两个有序链表，但官方题解和优秀题解都是默认为两个升序的链表来处理，这里我认为是不严谨的，因为如果是一个降序链表一个升序链表的话，处理方式要更复杂一些。

**你使用的语言**
C++

**期望行为**
希望官方能够修改一下题目，或者修改一下题解。

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/40531971/77221186-5be6e300-6b82-11ea-91ed-d36577a0601e.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
done
