### ISSUE TITLE
Plus One question statement is written poorly

### ISSUE THREAD

**Issue by peterschussheim** [LeetCode-Feedback/LeetCode-Feedback#590]
#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language

#### Description of the bug

https://leetcode.com/problems/plus-one/

If you look at the question, there is nothing which clearly says what you are expected to do; just some sentences which appear to be written by someone learning English:
 
> Given a non-empty array of digits representing a non-negative integer, **plus one to the integer**.
> 
> The digits are stored such that the most significant digit is at the head of the list, and each element in the array **contain a single digit.**
> 
> You may assume the integer **does not contain any leading zero,** except the number 0 itself.

**Why are questions posted which haven't even passed some minimal form of proofreading or peer review??**  Note, this is simply one example, nearly all questions on leetcode have similar grammar issues.

**Comment by lc-christina** [comment]
Hi @peterschussheim 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @peterschussheim 
Thank you for your time. We've used your feedback to update the problem. Can you please let us know your leetcode username so we can send 100 LeetCoins as the reward for this feedback? We appreciate your support!

**Comment by peterschussheim** [comment]
Hi @lc-christina, glad to hear this feedback was useful.  I prefer to stay anonymous on leetcode and do not post my username in public.
