### ISSUE TITLE
5962. 连接两字母单词得到的最长回文串 LeetCode运行结果有误

### ISSUE THREAD

**Issue by ningtianmin** [LeetCode-Feedback/LeetCode-Feedback#5903]
**你的 LeetCode 用户名**
tianminning

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
我编写了两份逻辑等价的代码一和二，他们的唯一不同之处在标有TODO的行；对于代码一，提交后通过，而对于代码二，提交后无法通过。例如对于下列测试用例，代码二的LeetCode运行结果有误，在本地环境代码一和代码二都是正常的。
测试用例：
["oo","vv","uu","gg","pp","ff","ss","yy","vv","cc","rr","ig","jj","uu","ig","gb","zz","xx","ff","bb","ii","dd","ii","ee","mm","qq","ig","ww","ss","tt","vv","oo","ww","ss","bi","ff","gg","bi","jj","ee","gb","qq","bg","nn","vv","oo","bb","pp","ww","qq","mm","ee","tt","hh","ss","tt","ee","gi","ig","uu","ff","zz","ii","ff","ss","gi","yy","gb","mm","pp","uu","kk","jj","ee"]

**你使用的语言**
C++

**你提交或者运行的代码**
代码一
```
class Solution {
public:
    int longestPalindrome(vector<string>& words) {
        int ans = 0;
        unordered_map<string, int> freq;
        for(const auto& word : words) {
            ++freq[word];
        }
        bool odd = false;
        for(const auto& [k, v] : freq) {
            if(k[0] == k[1]) {
                if(v & 1) {
                    odd = true;
                }
                ans += (v >> 1) << 2;
            }else if(k[1] < k[0]) { // TODO
                string rev = string(1, k[1]) + k[0];
                ans += min(v, freq[rev]) << 2;
            }
        }
        if(odd) {
            ans += 2;
        }
        return ans;
    }
};
```
代码二
```
class Solution {
public:
    int longestPalindrome(vector<string>& words) {
        int ans = 0;
        unordered_map<string, int> freq;
        for(const auto& word : words) {
            ++freq[word];
        }
        bool odd = false;
        for(const auto& [k, v] : freq) {
            if(k[0] == k[1]) {
                if(v & 1) {
                    odd = true;
                }
                ans += (v >> 1) << 2;
            }else if(k[0] < k[1]) { // TODO
                string rev = string(1, k[1]) + k[0];
                ans += min(v, freq[rev]) << 2;
            }
        }
        if(odd) {
            ans += 2;
        }
        return ans;
    }
};
```

**期望行为**
代码二也能够和代码一一样通过所有测试用例。

**屏幕截图**
![1](https://user-images.githubusercontent.com/21007985/148716911-7b0aa4ba-32e7-4cd8-bf4f-f4bb84b84053.png)
![2](https://user-images.githubusercontent.com/21007985/148716916-b03b0f31-5bc1-40fc-aeda-96c9e3a6ba90.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
@ningtianmin 你好，在与负责团队沟通了解后，建议将 `ans += min(v, freq[rev]) << 2; `修改为 
```
int tmp = freq.find(rev) == freq.end() ? 0 : freq[rev];
ans += (min(v, tmp) << 2);
```
原因在于直接写 freq[rev] 的话，如果 rev 不存在，会创建一个新元素。  而遍历的同时修改内部的元素是会有问题的。
