### ISSUE TITLE
252. Meeting rooms confusion whether end included or not

### ISSUE THREAD

**Issue by IgorPerikov** [LeetCode-Feedback/LeetCode-Feedback#591]
#### Your LeetCode username
igorperikov

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/meeting-rooms/
Description doesn't clarify whether end time included or not. Although mathematical notation for closed intervals `[s1,e1]` (both included) is being used in text, it turns out it's half-open with end time excluded. 

Provided examples doesn't have this additional information as well.

**Comment by lc-christina** [comment]
Hi @IgorPerikov 
Thanks for reaching out to us. The [s1,e1] represents the array of meeting time intervals, not specifically the mathematical notation for closed internals. In this case, it's common sense that people can attend meetings when the previous meeting's end time=next meeting's start time. Please let me know if this answers your questions, thank you!

**Comment by IgorPerikov** [comment]
Hi @lc-christina, thanks for your reply. I'd say this doesn't answer my question fully. Although there might be some common sense like you mentioned, the truth is that requirements is not 100% accurate or deducible from given examples. From attendee point of view I still have a chance to fail just because description is not 100% clear. 

I'd rather suggest adding example which shows interaction on the border, such as
```
Input: [[1,5],[5,10]]
Output: true
```
or description note like in here https://leetcode.com/problems/interval-list-intersections
