### ISSUE TITLE
Wrong Hint 2 - 325. Maximum Size Subarray Sum Equals k

### ISSUE THREAD

**Issue by rizeuscu** [LeetCode-Feedback/LeetCode-Feedback#5913]
#### Your LeetCode username
Andrei250

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hint 2 directs you thinking about S[i - k], which has nothing to do with the solution, because it should have been S[i] - k, due to Hint 3 mentioning HashMap in order to be used for the final solution.

#### Expected behavior
As it is mentioned in the solution section, the expected would have been S[i] - k for Hint 2, and not S[i - k].

#### Screenshots 
![image](https://user-images.githubusercontent.com/31996780/148752041-1f1c4668-b86d-4395-9f25-f2c99e8253be.png)

**Comment by LC-Sue** [comment]
Hi @rizeuscu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @rizeuscu 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
