### ISSUE TITLE
Missing code in Java Binary Search Sample - 973. K Closest Points to Origin

### ISSUE THREAD

**Issue by ivanlkc** [LeetCode-Feedback/LeetCode-Feedback#5914]
#### Your LeetCode username
ivan_lkc

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Approach 3: Binary Search, the article said "we should calculate the actual Euclidean distance for each point, rather than using the squared distance", which is correct; however in the sample code just below it, the Java sample did not perform the square root operation. While the square root was correctly applied in C++/JavaScript/Python3 samples.

#### Code you used for Submit/Run operation

```
// Not applicable - it is an issue with the solution article sample code.
```

#### Expected behavior

The Java Binary Search sample should behave the same as other languages and add a square root to find the actual Euclidean distance, as the article itself suggested.

**Comment by LC-Sue** [comment]
Hi @ivanlkc 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
