### ISSUE TITLE
246. Strobogrammatic Number, confusion about appropriate digits

### ISSUE THREAD

**Issue by IgorPerikov** [LeetCode-Feedback/LeetCode-Feedback#592]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

It's unclear whether digit `1` considered to be same after rotation. Leetcode website for example uses font where `1` is obviously not a `1` after rotation

**Comment by lc-christina** [comment]
Hi @IgorPerikov 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @IgorPerikov 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
