### ISSUE TITLE
Incomplete definition - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by ariksa** [LeetCode-Feedback/LeetCode-Feedback#5926]
#### Your LeetCode username
ariksa

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In this problem the definition doesn't say what should be done in case nodes have equal values.

> The left subtree of a node contains only nodes with keys less than the node's key.
> The right subtree of a node contains only nodes with keys greater than the node's key.

But this is important implementation wise and some of my submissions failed specifically due to equal nodes values.

**Comment by LC-Sue** [comment]
Hi @ariksa 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ariksa,
Thank you for your time. It is clear that the left subtree and right subtree should not contain equal values from the statement. Please read the statement carefully again and will find what should be returned in that case.
