### ISSUE TITLE
Missing test case -- 277. Find the Celebrity

### ISSUE THREAD

**Issue by Zunyi0719** [LeetCode-Feedback/LeetCode-Feedback#5927]
#### Your LeetCode username
liu0719

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case: [[1,1,1],[0,1,1],[0,1,1]]

#### Code you used for Submit/Run operation

```
// 277. Find the Celebrity
public class Solution extends Relation {
    public int findCelebrity(int n) {
        int possibleCeleb = 0;
        if (n == 0) {return n;}
            
        for (int i = 1; i< n ; i++){
            if(knows(possibleCeleb, i)){
                possibleCeleb = i;
            }
        }
        if (knows(possibleCeleb, 0) && possibleCeleb !=0 ) return -1;
        for (int i = 0; i< n ; i++){
            if (i == possibleCeleb) continue;
            
            if(!knows(i,possibleCeleb ))return -1; //i doesnt know possible celeb return -1
        }
        return possibleCeleb;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Input:
[[1,1,1],[0,1,1],[0,1,1]]
Output:
2
Expected:
-1

**Comment by LC-Sue** [comment]
Hi @Zunyi0719 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Zunyi0719 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
