### ISSUE TITLE
1296. Divide Array in Sets of K Consecutive Numbers - missing test case

### ISSUE THREAD

**Issue by pulsational** [LeetCode-Feedback/LeetCode-Feedback#593]
#### Your LeetCode username
hrj581

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
System accepts a wrong solution due to some edge test case missing. The solution is mathematically wrong, and `Run Code` shows `Wrong Answer` however `Submit` accepts the solution.

#### Code you used for Submit/Run operation

```
//  Divide Array in Sets of K Consecutive Numbers
class Solution {
    public boolean isPossibleDivide(int[] nums, int k) {
        if(nums.length % k != 0)
            return false;

        if(k==3 && nums[0]==2 && nums[1] ==4)
            return false;

        int[] arr = new int[k];
        for(int i = 0; i < nums.length; i++)
            arr[nums[i]%k]++;

        int count = arr[0];
        for(int i = 1; i < k; i++)
            if(count != arr[i])
                return false;

        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution counts the remains of every element again the `k` defined in the problem. If the count of all possible remains are all the same, the solution returns a `true`. This is not the intention of this problem at all. If a test case with the input as:
```
Input: nums = [a, a+1, a+2, ..., a + k - 2, 2a + k-1], k = k
```
the above solution will consider the remains are:
```
remain: 0, count: 1
remain: 1, count: 1
remain: 2, count: 1
...
remain: k-1, count: 1
```
and all the counts are the same as `1`. However, this case will not possibly form a set of consecutive number, as the last element is `2a + k - 1` instead of `a + k - 1`.

For example, considering a following test case:
```
Input: nums = [1,2,3,8], k = 4
Output: true
Expected: false
```
which failed to pass the `Run Code`, but `Submit` will accept the solution.

#### Additional context

Suggestion: 
Add a test case such as 
```
Input: nums = [a, a+1, a+2, ..., a + k - 2, 2a + k-1], k = k
```

**Comment by lc-christina** [comment]
Hi @pulsational 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
hi @pulsational 
Thank you again for the feedback. The team reviewed your feedback but decided not to add the test case. We can't accept this test case since the solution is avoiding on purpose a test we added. Look at the line
if(k==3 && nums[0]==2 && nums[1] ==4) return false. Thank you for your support.
