### ISSUE TITLE
Missing Test Case - 1049. Last Stone Weight II

### ISSUE THREAD

**Issue by jainachal03** [LeetCode-Feedback/LeetCode-Feedback#5931]
#### Your LeetCode username

Achal_Jain

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Code produces two different outcomes on same input.

#### Code you used for Submit/Run operation

```
// Two Sum
#define N 3001
class Solution {
public:
    int lastStoneWeightII(vector<int>& stones) {
        int n = (int)stones.size();
        int dp[n+1][3001]; // this should be fine.
        
        dp[0][0] = 1; // is this good? ->
        // can we form a sum of zero? =>yes
        for(int i = 1; i<N; i++){
            dp[0][i] = 0;
        }
        for(int j = 1; j<=n; j++){
            dp[j][0] = true; // this should be true (trivially).
        }
        
        dp[1][0] = 1; // how to generate the sum of 0 when numbers upto this value are chose.
        dp[1][stones[0]] = true;
        set<int>possible;
        for(int i = 2; i<=n; ++i){
            for(int j = 1; j<N; j++){
                if(stones[i-1]>j){
                    dp[i][j] = dp[i-1][j];
                    if(dp[i][j]){
                        possible.insert(j);
                    }
                }else{
                    dp[i][j] = dp[i-1][j] | dp[i-1][j - stones[i-1]];
                    if(dp[i][j]){
                        possible.insert(j);
                    }
                }
            }
        }
        
        int sum = 0;
        for(int i = 0; i<n; i++){
            sum += stones[i];
        }
        // find teh closest value to sum that is set to true.
        int dist = sum;
        // find the lower bound on the half of sum
        int val = *lower_bound(begin(possible), end(possible), sum/2);
        
        return abs(2*val - sum);
    }
};
```

#### Language used for code

C++

#### Expected behavior

It is expected that the code would give the same output on same input.  But somehow the code is producing a different outcome when the same input is used in the test case and different output when that input is used for test run. 

#### Screenshots

![leetcode](https://user-images.githubusercontent.com/83165901/148997883-c18e97da-4abe-4281-bc50-62ef77e4f3cf.png)

**Comment by LC-Sue** [comment]
Hi @jainachal03 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
