### ISSUE TITLE
Missing Test Case - 701. Insert into a Binary Search Tree

### ISSUE THREAD

**Issue by kaiwangx** [LeetCode-Feedback/LeetCode-Feedback#5932]
#### Your LeetCode username
badwomanxx

#### Category of the bug
- [*] Missing Test Cases 

#### Description of the bug
The only test case of None root is, root = None and val = 5. Missing test case of other values when root is None. For example, the following code will pass the test (hardcoding value 5 when root is None)

#### Code you used for Submit/Run operation

```
class Solution:
    def insertIntoBST(self, root: Optional[TreeNode], val: int) -> Optional[TreeNode]:
        if not root:
            return TreeNode(5)  # hardcode val 5 here
        elif val < root.val:
            if not root.left:
                root.left = TreeNode(val)
            else:
                self.insertIntoBST(root.left, val)
        else:
            if not root.right:
                root.right = TreeNode(val)
            else:
                self.insertIntoBST(root.right, val)
        return root
```

#### Language used for code
Python

**Comment by LC-Sue** [comment]
Hi @kaiwangx,
Thank you for reaching out to us, because the code is hardcoded, we wouldn't consider it for missing test case!
