### ISSUE TITLE
Outdated Refer Link - 23. Merge k Sorted Lists

### ISSUE THREAD

**Issue by barnett617** [LeetCode-Feedback/LeetCode-Feedback#5935]
#### Your LeetCode username

LCKUA

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Approach1, after I clicked the suggested refer link of sorting, the page is 404.

#### Expected behavior

Supply a link reference that works.

#### Screenshots

![image](https://user-images.githubusercontent.com/23159565/149060741-1f6dde18-a329-4080-84f1-9b14e8b6dbf6.png)

**Comment by LC-Sue** [comment]
Hi @barnett617,
Thank you for reaching out to us! The issue has been resolved!
