### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by Alperencode** [LeetCode-Feedback/LeetCode-Feedback#5936]
#### Your LeetCode username

Alperencode

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

2**31 - 1 == 2147483647. So program does not need return 0 when we try 1534236469. But the test case is want it to and my solution not getting acceptance.

#### Code you used for Submit/Run operation

```python
class Solution(object):
    def reverse(self, x):
        rev = []
        if (2**31 - 1 <= x) or (-2**31 >= x) or (x == 0):
            return 0
        if x > 0:
            for i in range(0,len(str(x))):
                rev.append(str(x)[i])
            rev.reverse()
            while rev[0] == '0':
                rev.pop(0)
        else:
            for i in range(0,len(str(x))-1):
                rev.append(str(x)[i+1])
            rev.reverse()
            while rev[0] == '0':
                rev.pop(0)
            rev.insert(0, "-")        
        reversedInt = ''.join(rev)
        
        return int(reversedInt)

solution = Solution()

# Testcases
solution.reverse(1534236469)
```

#### Language used for code

Python3

#### Expected behavior

The expected output needs to be "9646324351" when test case is "1534236469". Not 0.

**Comment by LC-Sue** [comment]
Hi @Alperencode,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
