### ISSUE TITLE
第99题：恢复搜索二叉树，提交后的测试用例有问题

### ISSUE THREAD

**Issue by billyhoomm** [LeetCode-Feedback/LeetCode-Feedback#5937]
**你的 LeetCode 用户名**
billyhu

**题目**
第99题：恢复搜索二叉树

**Bug 类型**
- 测试用例有问题

**描述**
我的代码，自己手动输入的用例都是运行正确的，一旦点击提交，第一个用例的结果就错了（但是我手动输入第一个用例发现是没问题的）

**你使用的语言**
Javascript

**你提交或者运行的代码**
```
/**
 * Definition for a binary tree node.
 * function TreeNode(val, left, right) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.left = (left===undefined ? null : left)
 *     this.right = (right===undefined ? null : right)
 * }
 */
/**
 * @param {TreeNode} root
 * @return {void} Do not return anything, modify root in-place instead.
 */
let left = new TreeNode(1)
let first = null;
let second = null;

var recoverTree = function(root) {
    recover(root)
    const temp =  first.val;
    first.val = second.val;
    second.val = temp;
};

var recover = function(root) {
    if (root === null) {
        return
    }
    recover(root.left)
    if (left.val > root.val) {
        if (first === null) {
            first = left
        }
        second = root
    }
    left = root
    recover(root.right)
}
```

**期望行为**
描述你期望的结果

**屏幕截图**
![image](https://user-images.githubusercontent.com/17565682/149136033-5a7ecdd3-ecae-4175-b31d-bdf927eff56a.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
