### ISSUE TITLE
Explore Card of Heap's Chapter Content Optimize

### ISSUE THREAD

**Issue by barnett617** [LeetCode-Feedback/LeetCode-Feedback#5939]
#### Your LeetCode username

LCKUA

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Why not change the illustrations' sequence in the end of the first article "Definition and Classification of Heap".
The description is sequenced by Max Heap then Min Heap, but the illustration is sequenced Min Heap then Max Heap, which is not matched well.

#### Expected behavior

Put the Max Heap illustration first which makes learners can watch the first illustartion more naturally while reading the description of Max Heap. 

#### Screenshots

![image](https://user-images.githubusercontent.com/23159565/149171583-17f5e2d5-6be7-41a9-9e7d-79261dd0db14.png)

**Comment by LC-Sue** [comment]
Hi @barnett617 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
