### ISSUE TITLE
Missing Test Case -1591. Strange Printer II

### ISSUE THREAD

**Issue by Doctor-X** [LeetCode-Feedback/LeetCode-Feedback#5941]
#### Your LeetCode username

doppler

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug
my code got accepted even though it failed a testcase that I created
Testcase - [[5,1,5,3,5],[4,4,4,3,4],[5,1,6,3,5],[2,1,2,2,2],[5,1,5,3,5]]

#### Code you used for Submit/Run operation

```
func isPrintable(targetGrid [][]int) bool {
  descendant := [61]int64{}
  dp := [61][]int{}
  for i:= 1;i<=60;i++{
    dp[i] = []int{61,61, 0,0}
  }
  for i:= 0;i<len(targetGrid);i++{
    for j := 0;j<len(targetGrid[i]);j++{
      v := targetGrid[i][j]
      if dp[v][0]>i{
        dp[v][0] = i
      }
      if dp[v][1]>j{
        dp[v][1] = j
      }
      if dp[v][2]<i{
        dp[v][2] = i
      }
      if dp[v][3]<j{
        dp[v][3]=j
      }
    }
  }
  for color:= 1;color<61;color++{
    if dp[color][0] == 61 {
      continue
    }
    for i:= dp[color][0];i<=dp[color][2];i++{
      for j:= dp[color][1];j<=dp[color][3];j++ {
        if targetGrid[i][j] == color {
          continue
        }
        dcolor := targetGrid[i][j]
        if descendant[dcolor]&(1<<color) != 0{
          return false
        }
        descendant[color]|=1<<dcolor
      }
    }
  }
  flag := false
  for color := 1;color<=60;color++ {
    if dp[color][0] == 61 {
      continue
    }
    if descendant[color] == 0{
      flag = true
      break
    }
  }
  return flag
}
```

#### Language used for code

Golang

#### Expected behavior

my submission should have failed instead it got accepted
My code submission output = true
correct output = false
#### Additional context

I think there aren't enough test cases that have cycles of size more than 2. To be more specific this is the only test case that has a cycle of more than 2 - [[5,1,5,3,5],[4,4,4,3,4],[5,1,5,3,5],[2,1,2,2,2],[5,1,5,3,5]]

**Comment by LC-Sue** [comment]
Hi @Doctor-X 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Doctor-X 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
