### ISSUE TITLE
Missing Test Case - 2133. Check if Every Row and Column Contains All Numbers

### ISSUE THREAD

**Issue by satyajeetramnit** [LeetCode-Feedback/LeetCode-Feedback#5943]
#### Your LeetCode username
satyajeetramnit2708

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

When we make duplicates beforehand and check if Every Row and Column Contains All Numbers by using XOR Operation.
Any set of integers containing every element twice will always give 0 when XOR with the other, but the reverse is not always true.
I first used this approach to solve the problem, and all the test cases passed. But later on thought of it.
So, I urge you to take this into consideration, as it might be helpful to many others in their learning process.
Thankyou.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkValid(vector<vector<int>>& matrix) {
        int n=matrix.size();
        int z=0;
        for(int i=1;i<=n;i++) z^=i;
        for (int i = 0; i < n; i++){
            int x=z,y=z;
            for (int j = 0; j < n; j++){
                x^=matrix[i][j];
                y^=matrix[j][i];
            }
            if(x!=0 || y!=0) return false;
        }
        return true;
    }
};
```

#### Language used for code
 C++

#### Expected behavior
 
The wrong answers also passes all the available test cases, which shouldn't be so.

#### Screenshots

![1](https://user-images.githubusercontent.com/75561539/149230049-f0b7878f-0798-4c83-9b30-bbc0ec8e2d75.png)
![2](https://user-images.githubusercontent.com/75561539/149230140-e5eecac4-546f-4862-8955-a67d525a0d2e.png)

**Comment by stormsunshine** [comment]
Could you please provide the test cases in this issue?

**Comment by satyajeetramnit** [comment]
Test Cases -> 
[[1,2,2,4,5,6,6],[2,2,4,5,6,6,1],[2,4,5,6,6,1,2],[4,5,6,6,1,2,2],[5,6,6,1,2,2,4],[6,6,1,2,2,4,5],[6,1,2,2,4,5,6]]
[[1,2,2,5,5],[2,2,5,5,1],[2,5,5,1,2],[5,5,1,2,2],[5,1,2,2,5]]

**Comment by satyajeetramnit** [comment]
> Could you please provide the test cases in this issue?

Test Cases ->
[[1,2,2,4,5,6,6],[2,2,4,5,6,6,1],[2,4,5,6,6,1,2],[4,5,6,6,1,2,2],[5,6,6,1,2,2,4],[6,6,1,2,2,4,5],[6,1,2,2,4,5,6]]
[[1,2,2,5,5],[2,2,5,5,1],[2,5,5,1,2],[5,5,1,2,2],[5,1,2,2,5]]

**Comment by LC-Sue** [comment]
Hi @satyajeetramnit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @satyajeetramnit 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
