### ISSUE TITLE
Question 179. Largest number

### ISSUE THREAD

**Issue by upendradeshpande** [LeetCode-Feedback/LeetCode-Feedback#5945]
https://leetcode.com/problems/largest-number/submissions/

Answer which is expected is wrong.
making the largest number from list [3,30,34,5,9] comes as "9543330"

but in the expected output it is 
"9534330"

This is wrong answer. Please update it

**Comment by stormsunshine** [comment]
How do you get the number "9543330"? You can't split the number 34 into two digits 3 and 4. You must use each number without splitting the digits.

**Comment by LC-Sue** [comment]
Hi @upendradeshpande,
Thank you for reaching out to us, I hope stormsunshine's answer answers your doubts! If you have any other questions please feel free to reach out to us again.
