### ISSUE TITLE
Question 99. Recover Binary Search Tree - Test Case

### ISSUE THREAD

**Issue by shivam-pednekar** [LeetCode-Feedback/LeetCode-Feedback#5946]
#### Your LeetCode username
 spednek2

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution provided for problem 99: Recover Binary Search Tree fails for the test case [-1,null,-3,null,-2,null,-4]. The solution provided clears 1918/1919 cases except the one provided above. My solution is similar to the solution provided and both fail to handle this case. 

#### Code you used for Submit/Run operation

```
class Solution:
    def recoverTree(self, root: Optional[TreeNode]) -> None:
        """
        Do not return anything, modify root in-place instead.
        """
        def inorder(root):
            if root is not None:
                inorder(root.left)
                res.append(root.val)
                inorder(root.right)
                
        def find_xy(nums: List[int]) -> (int, int):
            n = len(nums)
            x = y = -1
            for i in range(n - 1):
                if nums[i + 1] < nums[i]:
                    y = nums[i + 1]
                    
                    # first swap occurence
                    if x == -1:     
                        x = nums[i]
                    # second swap occurence
                    else:           
                        break
            return x, y
        
        def swapper(root):
            if root is not None:
                swapper(root.left)
                
                if root.val == x:
                    self.p = root
                if root.val == y:
                    self.q = root
                    
                swapper(root.right)
        
                
        res = []
        self.p = None
        self.q = None

        inorder(root)
        x,y = find_xy(res)
        swapper(root)
        
        self.p.val, self.q.val = self.q.val, self.p.val
```

#### Language used for code

Python3

#### Expected behavior

The expected output was
```
 [-4,null,-3,null,-2,null,-1]. 
```
whereas this was the result obtained 
```
[-1,null,-3,null,-4,null,-2]
```

#### Screenshots

![tree](https://user-images.githubusercontent.com/62328699/149251979-00fad2b2-1235-43c0-8dee-b44c4f20d7ed.JPG)
![error](https://user-images.githubusercontent.com/62328699/149251983-62b9bd5d-bf24-4ba2-b36b-b118a087a087.JPG)

**Comment by LC-Sue** [comment]
Hi @shivam-pednekar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @shivam-pednekar 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
