### ISSUE TITLE
Incorrect comments - 690. Employee Importance

### ISSUE THREAD

**Issue by sandeshan** [LeetCode-Feedback/LeetCode-Feedback#5947]
#### Your LeetCode username
sandeshan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When using TypeScript, the comments in the editor, regarding class definition for the `Employee` class has the  `subordinates` property initialized with the `number` type, where it should have been `number[]`

```
// Expected
subordinates: number[]

// Actual
subordinates: number
```

These are just comments that doesn't affect the test cases, but clear/accurate comments are always helpful.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

TypeScript

#### Expected behavior

```
// Expected
subordinates: number[]

// Actual
subordinates: number
```

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Sue** [comment]
Hi @sandeshan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sandeshan 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
