### ISSUE TITLE
Missing Test Case - 452. Minimum Number of Arrows to Burst Balloons

### ISSUE THREAD

**Issue by Karandeep1234** [LeetCode-Feedback/LeetCode-Feedback#5949]
#### Your LeetCode username

Karandeep1234

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Wrong Solution was accepted because of missing testcases. Code giving wrong answer on a test case but still accepted.

Testcase: [[2147483646,2147483647],[2147483644,2147483645]] 

#### Code you used for Submit/Run operation

```
class Solution {
    public int findMinArrowShots(int[][] points) {
        Arrays.sort(points,(int[] a,int[] b)->{
            if(a[0]+b[0]<=0 && a[0]>0){
                return 1;
            }else if(a[0]+b[0]<=0 && b[0]>0){
                return -1;
            }
            else{
                return a[0]-b[0];
            } 
            
        });
        
        Stack<int[]> st=new Stack<>();
        st.push(points[0]);
        for(int i=1;i<points.length;i++){
            int[] c=points[i];
            int[] p=st.peek();
            if(p[1]<c[0]){
                st.push(c);
            }else{
                st.pop();
                int[] a={c[0],Math.min(c[1],p[1])};
                st.push(a);
            }
        }
        return st.size();
    }
}
```

#### Language used for code

Java

#### Expected behavior

Output: 1
Expected: 2

#### Additional context

Input: [[2147483646,2147483647],[2147483644,2147483645]]
Output: 1
Expected: 2

**Comment by LC-Sue** [comment]
Hi @Karandeep1234 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Karandeep1234 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
