### ISSUE TITLE
Missing Test Case - 452. Minimum Number of Arrows to Burst Balloons

### ISSUE THREAD

**Issue by Sam-Si** [LeetCode-Feedback/LeetCode-Feedback#5950]
#### Your LeetCode username
sam_si

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Few solutions which are O(N**2) could pass the question to remove false positive here is the test case.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findMinArrowShots(vector<vector<int>>& points) {

        vector<vector<int>> events;
        int i = 0;
        for(auto point : points){
            vector<int> event;
            int start = point[0];
            int end = point[1];
            
            event.push_back(start);
            event.push_back(-1);
            event.push_back(i);
            
            events.push_back(event);
            vector<int> eevent;
            eevent.push_back(end);
            eevent.push_back(1);
            eevent.push_back(i);
            events.push_back(eevent);

            
            i++;
        }
        std::sort(events.begin(), events.end(),
          [](const std::vector<int>& a, const std::vector<int>& b) {
              if(a[0] == b[0]){
                  return a[1] < b[1];
              }
                return a[0] < b[0];
        });
        
        int count = 0;
        
        vector<int> current;
        int N = points.size();
        
        bool done[N];
        
        for(int b = 0;b < N;b++){
            done[b] = false;
        }
        
        for(auto event: events){
            int c = event[0];
            int e = event[1];
            int i = event[2];
            
            if(e == -1){
                current.push_back(i);
            }
            else{
                if(done[i]){
                    continue;
                }
                for(auto ci: current){
                    done[ci] = true;
                }
                count++;
            }
        }
        
        return count;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This code should TLE

#### Screenshots

![image](https://user-images.githubusercontent.com/13261099/149289780-80baea86-70b6-4c2f-b7eb-311f4bc46182.png)

#### Additional context

https://leetcode.com/submissions/detail/618880580/
The solution gets accepted right now.

The difficult test case which should make the above code TLE.
[452 Minimum Number of Arrows to Burst Balloons Test Case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7860962/452.Minimum.Number.of.Arrows.to.Burst.Balloons.Test.Case.txt)

**Comment by LC-Sue** [comment]
Hi @Sam-Si,
Thank you for reaching out to us, the code TLE now!

**Comment by Sam-Si** [comment]
@LC-Sue When will I get LC points for this?

**Comment by Sam-Si** [comment]
https://leetcode.com/submissions/detail/623466232/

I submitted the code right now.
The code doesn't TLE actually 😅

**Comment by Sam-Si** [comment]
I checked the code again and it does TLE.
