### ISSUE TITLE
498. Diagonal Traverse - Approach 1 - Java - Replace M with N 

### ISSUE THREAD

**Issue by avielas** [LeetCode-Feedback/LeetCode-Feedback#5951]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @avielas 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @avielas,
Thank you for your time, our team is aware of this issue and we will work on fixing it in future iterations!
