### ISSUE TITLE
Missing Test Case - 1752. Check if Array Is Sorted and Rotated

### ISSUE THREAD

**Issue by GauravSingh327** [LeetCode-Feedback/LeetCode-Feedback#5953]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by GauravSingh327** [comment]
class Solution {
public:
    bool check(vector<int>& nums) {
        int c=0;
        for(int i=0;i<nums.size()-1;i++)
        {
            if(nums[i]>nums[i+1])
                c++;
        }
        if(nums[nums.size()-1]>nums[0])
            c++;
        if(c>1)
            return false;
        else
            return true;
    }
};

**Comment by stormsunshine** [comment]
What is the missing test case?

**Comment by LC-Sue** [comment]
Hi @GauravSingh327,
Thank you for reaching out to us, could you provide the missing test case?

**Comment by LC-Sue** [comment]
Hi @GauravSingh327 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
