### ISSUE TITLE
Check if Array Is Sorted and Rotated solution

### ISSUE THREAD

**Issue by GauravSingh327** [LeetCode-Feedback/LeetCode-Feedback#5954]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the issue you want to mention?

**Comment by LC-Sue** [comment]
Hi @GauravSingh327 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
