### ISSUE TITLE
Duplicate Zeros problem giving wrong results during submission

### ISSUE THREAD

**Issue by tikkanadityajyothi** [LeetCode-Feedback/LeetCode-Feedback#5955]
Hi, 

I was able to test the solution with different test case inputs and was receiving correct response while running the code. But when trying to submit, I'm seeing incorrect results. I'm using C# language for solutions. Please see below screenshot for the incosistency.

![image](https://user-images.githubusercontent.com/11670002/149419137-a36b436c-0d0e-495d-8aeb-6d36ace808a4.png)

Can someone please look into this.

Thanks

**Comment by LC-Sue** [comment]
Hi @tikkanadityajyothi 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
