### ISSUE TITLE
Bad Test Case - 1880. Check if Word Equals Summation of Two Words

### ISSUE THREAD

**Issue by perum** [LeetCode-Feedback/LeetCode-Feedback#5959]
#### Your LeetCode username
grothebrandon

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Invalid test case

#### Description of the bug
Test case j, j, bi is invalid. It expects true but the answer is false.

#### Code you used for Submit/Run operation
```
// Two Sum
public class Solution {
    public bool IsSumEqual(string firstWord, string secondWord, string targetWord) {
        var dict = new Dictionary<char, int>() {
            {'a', 0},
            {'b', 1},
            {'c', 2},
            {'d', 3},
            {'e', 4},
            {'f', 5},
            {'g', 6},
            {'h', 7},
            {'i', 8},
            {'j', 9}
        };
        
        int count1 = 0, count2 = 0, target = 0;
        
        for(int i = 0; i < firstWord.Length; i++) {
            count1 += dict[firstWord[i]];
        }
        
        for(int i = 0; i < secondWord.Length; i++) {
            count2 += dict[secondWord[i]];
        }
        
        for(int i = 0; i < targetWord.Length; i++) {
            target += dict[targetWord[i]];
        }
        
        if(count1+count2 == target) return true;
        
        return false;
    }
}
```

#### Expected behavior
firstWord = j = 9
secondWord = j = 9
target = bi = 9

Thus, the result should be false, as the summation of j + j != b + i

**Comment by stormsunshine** [comment]
First, please declare which language your code uses. I think the language should be C#.

Secondly, the test case you provide in the issue is valid. The string "j" represents number 9, and the string "bi" represents 18. Since 9 + 9 = 18, this test case should return `true`.

Please read the problem description carefully before creating an issue.

**Comment by LC-Sue** [comment]
Hi @perum,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
