### ISSUE TITLE
15 3sum Test case wrongly rejects solution

### ISSUE THREAD

**Issue by apoddar573** [LeetCode-Feedback/LeetCode-Feedback#596]
#### Your LeetCode username
apoddar573

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The last test case in this question leads to failures even though the solution is done using the correct algorithm. 
The test case is attached.

#### Code you used for Submit/Run operation

```
// 3Sum
class Solution {
public:
    vector<vector<int>> threeSum(vector<int>& A) {
        int n = A.size();
        sort(A.begin(), A.end());
        vector<vector<int>> ret;
        set<vector<int>> set;
        
        for(int l = 0; l<n-2; l++) {
            int val = A[l];
            int mid = l+1;
            int high = A.size()-1;
            
            while(mid<high) {
                int sum = val+A[high]+A[mid];
                if(sum == 0) {
                    set.insert({val, A[mid], A[high]});
                    mid++;
                } else if(sum>0) {
                    high--;
                } else mid++;
            }
        }
        
        for(auto x: set) {
            ret.push_back(x);
        }
        return ret;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The submission to be accepted. However, I get a rejection. 
The code is accepted after I make a minor modification here 
```
                if(sum == 0) {
                    set.insert({val, A[mid], A[high]});
                    mid++;
                    high--;
                }

```
While this is certainly another optimization, not having this should not lead to a rejection since the algorithm is o(n^2) as required.
[test-case-1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4890132/test-case-1.txt)

**Comment by lc-christina** [comment]
Hi @apoddar573 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by zerotrac** [comment]
Please note that your code is not O(n^2) time complexity. The APIs you used in std::set (e.g. insert) takes O(x) time where x is the number of elements in the set. You should use std::unordered_set with custom hash function instead.

**Comment by lc-pam** [comment]
Hi @apoddar573 ,
Thanks for your time. The team has reviewed your report but decided to not add the test case because of technical reason. Thank you for your support!
