### ISSUE TITLE
Test Case Needs to Be Enhanced - 373.Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#5968]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
The brute force with O(k^2 logk) complexity can be accepted. However, if an interviewer use this problem during a real interview, only the solution using priority queue or binary search can be passed. Besides, the difficulty of the brute force is not enough to be marked as "medium" probably.  So, I suggest that the constraint of k should be increased to 10^5 ,then the brute force with O(k^2 logk) will get TLE.

Code you used for Submit/Run operation

The time complexity of the code below is O(k^2*logk)
```
class Solution:
    def kSmallestPairs(self, nums1: List[int], nums2: List[int], k: int) -> List[List[int]]:
        hea = []
        heapq.heapify(hea)

        for i in range(min(len(nums1),k)):
            for j in range(min(len(nums2),k)):
                heapq.heappush(hea,[nums1[i]+nums2[j],nums1[i],nums2[j]])
        
        res = []
        for _ in range(k):
            res.append(heapq.heappop(hea)[1:])
            if not hea:
                return res
        return res
```

The time complexity of the code below is O(klogk)
```
class Solution:
    def kSmallestPairs(self, nums1: List[int], nums2: List[int], k: int) -> List[List[int]]:

        hea = []
        heapq.heapify(hea)

        for i in range(min(k,len(nums1))):
            heapq.heappush(hea,(nums1[i]+nums2[0],i,0))
        
        res = []
        while hea and len(res)<k:
            num,i,j = heapq.heappop(hea)
            res.append([nums1[i],nums2[j]])
            if j<len(nums2)-1:
                heapq.heappush(hea,(nums1[i]+nums2[j+1],i,j+1))
        
        return res
```

Language used for code
Python3

Expected behavior
1. The constraints of k should be increased to 10^5.
2. At least one test case with nums1.length=nums2.length=k=10^5 should be added.

**Comment by CarlCzerny837** [comment]
[testcase373.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7868074/testcase373.txt)
A possible test case.

**Comment by stormsunshine** [comment]
In fact, I think that using 10<sup>4</sup> as the maximum value of k is sufficient to make the O(k<sup>2</sup> log k) solution TLE.

Note that O(k<sup>2</sup> log k<sup>2</sup>) = O(2k<sup>2</sup> log k) = O(k<sup>2</sup> log k).

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837，
Thank you for your time. Our team has looked into the problem and believe that the current constraints are fine.
