### ISSUE TITLE
1282. Group the People Given the Group Size They Belong To: No check for invalid input

### ISSUE THREAD

**Issue by artak-kirakosyan** [LeetCode-Feedback/LeetCode-Feedback#597]
#### Your LeetCode username
pythoff

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug
If I test the code using an invalid input, I get the same result as your expected is, but it show Wrong Answer.
The 2 solutions here would be:
1. Update the code on your side which checks the input and tell that its an invalid input
2. Update the decision making script, which would give credit to the correct answer even for an invalid testcase

#### Code you used for Submit/Run operation
```
class Solution:
    def groupThePeople(self, groupSizes: List[int]) -> List[List[int]]:
        """
        :type groupSizes: List[int]
        :rtype: List[List[int]]
        """
        idx = {}
        for i in range(len(groupSizes)):
            try:
                idx[groupSizes[i]].append(i)
            except KeyError:
                idx[groupSizes[i]] = [i]
        results = []

        for i, j in idx.items():
            curr = 0
            while curr + i <= len(j):
                results.append(j[curr:curr+i])
                curr += i
        return results
```

#### Expected behavior
Input:   [1,2]
My code results:  [[0]]
Expected Answer:   Invalid testcase or [[0]]
Current Answer I receive:  Wrong Answer

Input:  [2, 3, 3]
My code results:  []
Expected Answer:  Invalid testcase or []
Current Answer I receive:   Wrong answer

#### Screenshots

![image](https://user-images.githubusercontent.com/23319356/87001629-f5391400-c1c8-11ea-86ba-6e07c421b9c9.png)
![image](https://user-images.githubusercontent.com/23319356/87001675-05e98a00-c1c9-11ea-9541-f4a5b5f062c2.png)

**Comment by lc-christina** [comment]
Hi @artak-kirakosyan 
Thank you for reaching out to us. The problem stated that 'it is guaranteed that there exists at least one solution' so it requires your input test case to be valid. Thank you for your support and please don't hesitate to reach out if you have any other questions!

**Comment by artak-kirakosyan** [comment]
Dear @lc-christina , I understand the requirements of the problem.

But in other problems, if the testcase is invalid, the program tells the user explicitly that the testcase is invalid.
An example of that : problem 1344. Angle between hands of the clock. The hour should be between 1 and 12 so the program reports about invalid testcase.
![image](https://user-images.githubusercontent.com/23319356/87396187-82161000-c5c3-11ea-9083-190fdfc9064c.png)

In this problem however, the program does not give any information to the user. Furthermore, it evaluates the program with the invalid testcase and even though the expected and actual results match, it shows the user that his/her solution is incorrect(please 
refer to the screenshot in the Issue description).

My suggestion is to update the testcase checker in LeetCode, so that in case of invalid testcase it gives appropriate message to the user.
