### ISSUE TITLE
Return type in comment is wrong - 278. First Bad Version

### ISSUE THREAD

**Issue by pakdev** [LeetCode-Feedback/LeetCode-Feedback#5970]
#### Your LeetCode username
vortininja

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Python3 comment at the top states:
`# def isBadVersion(version: int) -> int:`

The `int` return type conflicts with the problem's description that states "You are given an API `bool isBadVersion(version)`"

#### Language used for code

Python3

#### Expected behavior

Comment should state:
`# def isBadVersion(version: int) -> bool:`

#### Screenshots

![image](https://user-images.githubusercontent.com/1248927/149455964-4d72441c-b4f6-4365-8093-ebad33c36109.png)

**Comment by LC-Sue** [comment]
Hi @pakdev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @pakdev 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
