### ISSUE TITLE
incorrect worst case in complexity analysis in solution - 113. Path Sum II

### ISSUE THREAD

**Issue by syominsergey** [LeetCode-Feedback/LeetCode-Feedback#5971]
#### Your LeetCode username
syominsergey

#### Category of the bug
- [ ] Solution (complexity analysis)

#### Description of the bug
incorrect worst case in complexity analysis in solution
there said "In the worst case, we could have a complete binary tree"
but complete binary tree is not the worst case
or at least such definition does not have enough information
processing problem with complete balanced binary tree has complexity O(n*log(n))
this explained, for example, in this comment: https://leetcode.com/problems/path-sum-ii/solution/474007
or here: https://leetcode.com/problems/path-sum-ii/solution/695788
but the worst case does not looks like complete balanced binary tree
see visualization for worst case here: https://leetcode.com/problems/path-sum-ii/solution/1035868

maybe it is better to have such visualization in official solution

**Comment by LC-Sue** [comment]
Hi @syominsergey 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
