### ISSUE TITLE
Missing Test Case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by zhengyuan-liu** [LeetCode-Feedback/LeetCode-Feedback#5973]
#### Your LeetCode username: 

Compiler

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing Test Case of 234. Palindrome Linked List.
My Code below is Accepted by LeetCode OJ, but actually this should be Wrong Answer. The following test case can detect the bug and should be added to the test cases:
```
[1,2,2,3,3,1]
```

#### Code you used for Submit/Run operation

```cpp
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    bool isPalindrome(ListNode* head) {
        int len = 0;
        ListNode* p = head;
        while(p) {
            p = p->next;
            len++;
        }
        stack<int> mystack;
        int cnt = 0;
        while(head) {
            cnt++;
            // ignore the mid node if length is odd
            if(len % 2 == 0 || cnt != (len + 1)/2) {
                if(mystack.empty() || mystack.top() != head->val)
                    mystack.push(head->val);
                else
                    mystack.pop();
            }
            head = head->next;
        }
        return mystack.empty();
    }
};
```

#### Language used for code

C++

#### Expected behavior

The Code above is Accepted by LeetCode OJ, but actually this should be Wrong Answer.

**Comment by LC-Sue** [comment]
Hi @zhengyuan-liu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @zhengyuan-liu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
