### ISSUE TITLE
Missing Testcase - 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by ChaosNyaruko** [LeetCode-Feedback/LeetCode-Feedback#5974]
#### Your LeetCode username

ChaosNyaruko

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing Testcase of 373. Find K Pairs with Smallest Sums
My Code below is Accepted by LeetCode OJ, but actually this should be Wrong Answer. The following test case can detect the bug and should be added to the test cases:

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> kSmallestPairs(vector<int>& nums1, vector<int>& nums2, int k) {
        int m = nums1.size();
        int n = nums2.size();
        auto count = [&](int target){
            long long cnt = 0;
            int start = 0;
            int end = n - 1;
            while (start < m && end >= 0) {
                if (nums1[start] + nums2[end] > target) {
                    end--;
                } else {
                    cnt += end + 1;
                    start++;
                }
            }
            return cnt;
        };

        int left = nums1[0] + nums2[0];
        int right = nums1.back() + nums2.back();
        int pairSum = right;
        while (left <= right) {
            int mid = left + ((right - left) >> 1);
            if (count(mid) < k) {
                left = mid + 1;
            } else {
                pairSum = mid;
                right = mid - 1;
            }
        }

        vector<vector<int>> ans;
        int pos = n - 1;
        for (int i = 0; i < m; i++) {
            while (pos >= 0 && nums1[i] + nums2[pos] >= pairSum) {
                pos--;
            }
            for (int j = 0; j <= pos && k > 0; j++, k--) {
                ans.push_back({nums1[i], nums2[j]});
            }
        }
        pos = n - 1;
        for (int i = 0; i < m && k > 0; i++) {
            while (pos >= 0 && nums1[i] + nums2[pos] > pairSum) {
                pos--;
            }
            for (int j = i; k > 0 && j >= 0 && nums1[j] + nums2[pos] == pairSum; j--, k--) {
                ans.push_back({nums1[i], nums2[pos]});
            }
        }
        return ans;
    }
};

```

#### Language used for code

C++

#### Expected behavior

The Code above is Accepted by LeetCode OJ, but actually this should be Wrong Answer.

#### Screenshots

![image](https://user-images.githubusercontent.com/18713899/149498537-b40fd3d4-9a60-4b0c-9f6e-14d863c943f4.png)

**Comment by stormsunshine** [comment]
Could you please provide the complete test case by text in this issue?

**Comment by ChaosNyaruko** [comment]
> Could you please provide the complete test case by text in this issue?

[101,101,102,102,103,1003]
[2,3]
5

**Comment by LC-Sue** [comment]
Hi @ChaosNyaruko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ChaosNyaruko 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
