### ISSUE TITLE
Python 3 starter files does not follow naming convention

### ISSUE THREAD

**Issue by yonikremer** [LeetCode-Feedback/LeetCode-Feedback#5975]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [1 ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Starter files for python 3 do not follow the naming convention for functions:
The naming convention is using only lower case letters with _ as separator
"Function and Variable Names
Function names should be lowercase, with words separated by underscores as necessary to improve readability." PEP 8

**Comment by LC-Sue** [comment]
Hi @yonikremer,
Thank you for reaching out to us, could you provide the problem number of where you are experiencing this issue?

**Comment by LC-Sue** [comment]
Hi @yonikremer 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
