### ISSUE TITLE
Definition conflicts problem 662

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#598]
#### Your LeetCode username
ddoudle

#### Category of the bug
- [x] Question

#### Description of the bug

Problem 662: Maximum Width of Binary Tree
https://leetcode.com/problems/maximum-width-of-binary-tree/

Please see the definition of width of a tree given by the problem:
`The width of a tree is the maximum width among all levels.`
If the definition is right, a tree will have of one width. So what does `Maximum Width of Binary Tree` mean in the context? 
I think the title of the problem should be `Width of Binary Tree`

**Comment by lc-christina** [comment]
Hi @caoxingdong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @caoxingdong 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
