### ISSUE TITLE
[31. Next Permutation] Unclear description of problem

### ISSUE THREAD

**Issue by tsekityam** [LeetCode-Feedback/LeetCode-Feedback#5983]
#### Your LeetCode username
tsekityam

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem asks us to implement next permutation, which rearranges numbers into the lexicographically next greater permutation of numbers.

I have no previous knowledge about `permutation`, so I don't know what is `next permutation`. The description `rearranges numbers into the lexicographically next greater permutation of numbers` doesn't help neither, because I have never seen the word `lexicographically` nor `permutation` and don't know what is it.

However, the examples provided have no explaination on what is next permutation too.

As a result, I have no idea on what to do after reading entire question.

Moreover, the discussion forum and solution doesn't explain what is `next permutation`.

I wish there can be a better description on the problem statement, such that dummy people like me can still know what to do.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @tsekityam 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @tsekityam,
Thank you for your time, our team has added more explanation to the next permutation.
