### ISSUE TITLE
Typo in Graph explore card

### ISSUE THREAD

**Issue by burner1992** [LeetCode-Feedback/LeetCode-Feedback#5984]
#### Your LeetCode username

NaN-NaN-NaN

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases
- [x] Explore Card 

#### Description of the bug

In the   **Union by Rank - Disjoint Set**, there is quote:

> as shown in **Figure 1**, it is possible for all the vertices to form a line after connecting them using union, which results in the worst-case scenario for the find function. Is there any way to optimize these implementations?

#### Expected behavior

It should be:

> as shown in **Figure 6**, it is possible for all the vertices to form a line after connecting them using union, which results in the worst-case scenario for the find function. Is there any way to optimize these implementations?

#### Screenshots

![image](https://user-images.githubusercontent.com/81806802/149621757-81081db9-0aa3-48cd-9d91-24a4c6200293.png)

![image](https://user-images.githubusercontent.com/81806802/149621778-4658e504-624e-4823-a859-4d7dd11b29e0.png)

**Comment by LC-Sue** [comment]
Hi @burner1992 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @burner1992 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
