### ISSUE TITLE
Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by Karandeep1234** [LeetCode-Feedback/LeetCode-Feedback#5985]
#### Your LeetCode username

Karandeep1234

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Accepted solution gives wrong answer in many testcases. On observing my code I found that my code will give wrong answer due 
to overflow whenever there is a testcase which contains a subarray consisting of only 1 or 0  but ends in 0 with length greater than or equal  to 6 (this subarray should not include first or last element) . Under the given  constraints the maximum length possible for this subarray could be 999 (testcase1.txt and tescase2.txt). Therefore i suggest the addition of attached testcases.
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7875141/testcase.txt)

[testcase1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7875120/testcase1.txt)
  
[testcase2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7875133/testcase2.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public int jump(int[] nums) {
        int[] dp=new int[nums.length];
        dp[nums.length-1]=0;
        
        int i=nums.length-2;
        int min=Integer.MAX_VALUE-6;
        while(i>=0){
            int j=i;
            for(j=i+1;j<=i+nums[i] && j<nums.length;j++){
                min=Math.min(dp[j],min);
            }
            dp[i]=min+1;
            min=dp[i];
            i--;
        }
        return dp[0];
    }
}
```

#### Language used for code

Java

**Comment by LC-Sue** [comment]
Hi @Karandeep1234 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Karandeep1234 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
