### ISSUE TITLE
Missing Test Case - 761. Special Binary String

### ISSUE THREAD

**Issue by vishnukaushik** [LeetCode-Feedback/LeetCode-Feedback#5988]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Input: s = "11011000"
Output: "11100100"

Given Explanation: The strings "10" [occuring at s[1]] and "1100" [at s[3]] are swapped.
This is the lexicographically largest string possible after some number of swaps.

Bug: The lexographically largest string possible would be "11101000"
Explanation: The strings "10" [occuring at s[1]] and "110" [at s[3]] are swapped.

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

Expected output: "11101000"

**Comment by manish3522** [comment]
You have to swap both special substrings but "110" is not a special substring as it has more numbers of 1's than 0's.

**Comment by vishnukaushik** [comment]
> You have to swap both special substrings but "110" is not a special substring as it has more numbers of 1's than 0's.

But the question says "Every prefix of the binary string has **at least** as many 1's as 0's". That means "110" is a special substring I guess.

**Comment by manish3522** [comment]
It has to satisfy both the properties, not just one. So, the number of 0's in a special string must be equal to the number of 1's.

**Comment by vishnukaushik** [comment]
> It has to satisfy both the properties, not just one. So, the number of 0's in a special string must be equal to the number of 1's.

Oh okay got it

**Comment by LC-Sue** [comment]
Hi @vishnukaushik,
Thank you for reaching out to us! It seems like manish3522 was able to explain the test case to you! I'm glad to see your issue has been resolved!
