### ISSUE TITLE
1506. Find Root of N-Ary Tree

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#599]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Incorrect type hints

#### Code you used for Submit/Run operation

```
class Solution(object):
    def findRoot(self, tree):
        """
        :type tree: 'Node'
        :rtype: List['Node']
        """
        
```

#### Language used for code
Python

#### Expected behavior
The type and rtype should be opposite

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 ,
The problem probably has been updated thanks to other users' feedback. Can you please reload their code definition and see if it's the same result? I'll close the ticket for now but feel free to reopen if you still have questions. Thank you!
