### ISSUE TITLE
Solution 2(Approach 2) wrong----157. Read N Characters Given Read4

### ISSUE THREAD

**Issue by C-sirui** [LeetCode-Feedback/LeetCode-Feedback#5990]
#### Your LeetCode username
Kylaito

#### Category of the bug
- [ ] Question
- [1] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution 2 read more char when n % 4 != 0

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int read(char *buf, int n) {
        int copiedChars = 0, readChars = 4;
        
        while (copiedChars < n && readChars == 4) {
            readChars = read4(buf + copiedChars);
            copiedChars += readChars;
        }
        cout << buf << endl;
        return min(n, copiedChars);
    }
};
```

#### Language used for code
C++

#### Expected behavior

Your input
"abcdef"
5

"abcdef" is in buf, while the expected buf should contain "abcde".

**Comment by LC-Sue** [comment]
Hi @C-sirui 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @C-sirui 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
