### ISSUE TITLE
Missing Test Case - 513. Find Bottom Left Tree Value

### ISSUE THREAD

**Issue by guptadeepak46474** [LeetCode-Feedback/LeetCode-Feedback#5991]
#### Category of the bug
- [ 513] Question
- [ 
- ```
- class Solution {
    public int findBottomLeftValue(TreeNode root) {
        Queue<TreeNode> q = new LinkedList<>();
        q.offer(root);
        int res = 0;
        
        while(!q.isEmpty()) {
            res = q.peek().val;
            int size = q.size();
            
            for(int i = 0; i < size; i++) {
                TreeNode cur = q.poll();
                if(cur.left != null)
                    q.offer(cur.left);
                if(cur.right != null)
                    q.offer(cur.right);
            }
        }
        
        return res;
    }
}
- ```
- ] Solution
- [java, ] Language
- [2, 3, 4, null, null, null, 5] Missing Test Cases

#### Description of the bug

Acc. to problem statement we want to 'Find Bottom Left Tree Value' but I tested a solution by creating testcase having only rightmost node int lastrow and it gives the correct answer for that rightmost node but this is wrong

and the solution works even my solution is wrong

#### Code you used for Submit/Run operation

```
// 513. Find Bottom Left Tree Value
class Solution {
    public int findBottomLeftValue(TreeNode root) {
        Queue<TreeNode> q = new LinkedList<>();
        q.offer(root);
        int res = 0;
        
        while(!q.isEmpty()) {
            res = q.peek().val;
            int size = q.size();
            
            for(int i = 0; i < size; i++) {
                TreeNode cur = q.poll();
                if(cur.left != null)
                    q.offer(cur.left);
                if(cur.right != null)
                    q.offer(cur.right);
            }
        }
        
        return res;
    }
}
```

#### Expected behavior

Acc. to the screenshot I attached it should it gives output 3 not 5

#### Screenshots

![image](https://user-images.githubusercontent.com/69721318/149636390-6be7c635-ac75-41fc-a3bd-6a51731acba2.png)
![image](https://user-images.githubusercontent.com/69721318/149636397-0e1b30dd-5f59-47b2-aef1-632ad66c6e68.png)

#### Additional context

no leetcode is super fine

**Comment by stormsunshine** [comment]
Why should the test case return 3? Is 3 in the last row?

**Comment by LC-Sue** [comment]
Hi @guptadeepak46474,
Thank you for reaching out to us, the test case appears to be correct. Please feel free to refer to the discuss section of the problem if you have any other questions!

**Comment by guptadeepak46474** [comment]
does that mean i get leetcoins?

**Comment by guptadeepak46474** [comment]
yes because it is in the last row
