### ISSUE TITLE
Spelling Issue on https://leetcode.com/explore/learn/card/binary-search/126/template-ii/937/

### ISSUE THREAD

**Issue by Chicago1** [LeetCode-Feedback/LeetCode-Feedback#5992]
#### Your LeetCode username
dshribak

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x ] Language
- [ ] Missing Test Cases 

#### Description of the bug
'Gurantees' is misspelled on the page in the middle section

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Chicago1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Chicago1 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
