### ISSUE TITLE
C++代码高亮问题

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#5994]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
hqztrue

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
在力扣中国区用C++写题解的时候，如果代码中包含了pair<int,int>就会整个代码高亮失败，例如这个题解 https://leetcode-cn.com/problems/find-k-pairs-with-smallest-sums/solution/onkc-40ms-by-hqztrue-751q/ 。如果改成pair <int,int>(中间加一个空格)就好了。另外在提交代码页面，pair的高亮颜色也会根据加不加空格变化。

**你使用的语言**
C++

**Comment by feiceh** [comment]
Hello～我们已经收到你的反馈，这个问题已经提交至负责团队核实，给您带来的不便敬请谅解。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，后续可以点击「https://support.leetcode-cn.com/hc/kb/section/1115013」 提交工单反馈，请知晓～
