### ISSUE TITLE
77. Combination - Incorrect Space Complexity reported in the Solution 

### ISSUE THREAD

**Issue by SamarthGupta93** [LeetCode-Feedback/LeetCode-Feedback#5995]
77. Combinations
- Issue: Space Complexity is incorrectly reported as O(nCk) stating to keep all the combinations for an output.
- Solution: Space Complexity should be O(k*nCk). Output is a 2D matrix with n_rows = nCk each having k values (n_cols = k). Hence, total space required should be O(k*nCk)

**Comment by LC-Sue** [comment]
Hi @SamarthGupta93 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
