### ISSUE TITLE
Missing Test Case - 1192. Critical Connections in a Network

### ISSUE THREAD

**Issue by jiangyuang** [LeetCode-Feedback/LeetCode-Feedback#5996]
#### Your LeetCode username
EvilGenius

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing testcases that allowed acceptance of wrong submissions.

#### Code you used for Submit/Run operation

```python
from collections import deque

class UnionFind:
    def __init__(self, n):
        self.parent = [-1] * n
        self.weight = [1] * n

    def find(self, x):
        path = deque()
        path.appendleft(x)
        while self.parent[x] != -1:
            x = self.parent[x]
            path.appendleft(x)
        return x, path

    def union(self, x, y):
        px, pathx = self.find(x)
        py, pathy = self.find(y)
        if px == py:
            idx = 0
            while idx < min(len(pathx), len(pathy)) and pathx[idx] == pathy[idx]:
                idx += 1
            return [(pathx[i - 1], pathx[i]) for i in range(idx, len(pathx))] + [(pathy[i - 1], pathy[i]) for i in
                                                                                 range(idx, len(pathy))]
        else:
            if self.weight[px] > self.weight[py]:
                self.parent[py] = x
                self.weight[px] += self.weight[py]
            else:
                self.parent[px] = y
                self.weight[py] += self.weight[px]
            return []


class Solution:
    def criticalConnections(self, n: int, connections: List[List[int]]) -> List[List[int]]:
        union_find = UnionFind(n)
        crit = set((s, d) for s, d in connections)
        for src, dst in connections:
            non_crit = union_find.union(src, dst)
            if len(non_crit) > 0:
                for s, d in non_crit:
                    crit.discard((s, d))
                    crit.discard((d, s))
                crit.discard((src, dst))
        return crit
```

#### Language used for code

Python3

#### Expected behavior

Input: n = 6, connections = [[1, 0], [2, 1], [3, 2], [4, 5], [0, 4], [5, 0]]. 
Expected return: [[0, 1], [1, 2], [2, 3]]
My return: {(0, 4), (2, 1), (4, 5), (1, 0), (3, 2)}

Ignoring the return value format, my return has wrong pairs [0, 4] and [4, 5], but this solution still got accepted. I see some Union Find correct solutions in the discussion with additional DFS, but Union Find alone doesn't seem to work.

#### Additional context

My code is wrong since it doesn't always find all nodes in the cycle.

**Comment by LC-Sue** [comment]
Hi @jiangyuang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jiangyuang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
