### ISSUE TITLE
翻译模糊 (Fuzzy translation)

### ISSUE THREAD

**Issue by hibriansun** [LeetCode-Feedback/LeetCode-Feedback#5997]
**你的 LeetCode 用户名**
imzhi

**Bug 类型**
题目

**描述**
"return all the _mode(s)_ (i.e., the most frequently occurred element) in it." 应该被翻译成 “找出 BST 中的所有 _众数_（例如：出现频率最高的元素）”
否则容易理解成仅仅找出整棵树出现频率最高的元素

**Comment by feiceh** [comment]
@hibriansun 你好，当前题面已更新，ID：imzhi 给予积分奖励，请查收
