### ISSUE TITLE
Missing Test Case - 55. Jump Game

### ISSUE THREAD

**Issue by trieblistvan** [LeetCode-Feedback/LeetCode-Feedback#5998]
#### Your LeetCode username

Imarkus

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One test case seems incorrect to me (javascript): 
Input [2,0]
Output false
Expected true

Since the goal is to reach last element of the array and not beyond; 2 jumps from index 0 would reach index 2

#### Code you used for Submit/Run operation

```
var canJump = function(nums) {
    const jump = (from) => {
        if (from === 0) return true;
        for (let i = from - 1, c = 1; i >= 0; i--, c++) {
            if (nums[i] === c) {
                if (jump(i)) return true;
            }
        }
        return false;
    }  
    if (nums.length === 0) return true;
    return jump(nums.length - 1);
};
```

#### Language used for code

javascript

#### Expected behavior

expected answer to this input should be false

**Comment by stormsunshine** [comment]
Didn't you see the word "maximum" in problem description? Why do you have to jump exactly 2 steps ahead?

**Comment by trieblistvan** [comment]
I did miss that indeed. Sorry for that, and thanks for your time.
