### ISSUE TITLE
53. Maximum Subarray

### ISSUE THREAD

**Issue by CooperCooperCooper** [LeetCode-Feedback/LeetCode-Feedback#6]
"On Maximum Subarray: "If you have figured out the O(n) solution, try coding another solution using the divide and conquer approach, which is more subtle." I believe this should say "O(n^2) solution" "

Problem: https://leetcode.com/problems/maximum-subarray/

**Comment by kagan94** [comment]
Nope, title is correct.
Brute force solution would take O(n^2) time.
Here is the solution example with O(n) time:
```
class Solution(object):
    def maxSubArray(self, arr):
        """
        :type arr: List[int]
        :rtype: int
        """
        max_sum = [0] * len(arr)
        max_sum[0] = arr[0]

        for i in range(1, len(arr)):
            current = arr[i]
            max_sum[i] = max(current, max_sum[i - 1] + current)
        return max(max_sum)
```

**Comment by CooperCooperCooper** [comment]
Hi @kagan94,
Thank you for your time and support! Your feedback is correct.
