### ISSUE TITLE
846. Hand of Straights. Best submission incorrect

### ISSUE THREAD

**Issue by naco-siren** [LeetCode-Feedback/LeetCode-Feedback#60]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
This submission is incorrect.
E.g. [2,4,6], W=3

**what language is your code written in**
C++

**The code he/she submited**
```
public boolean isNStraightHand(int[] hand, int W) {
        if (hand.length % W != 0) {
            return false;
        }
        final int[] count = new int[W];
        for (int card : hand) {
            count[card % W] ++;
        }

        for (int c : count) {
            if (c != hand.length / W) {
                return false;
            }
        }
        return true;
    }
```

**Expected behavior**
The example test case should fail.

**Screenshots**
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/8222638/77221593-34533480-6b08-11ea-9b44-7ae7660024fc.png">

**Additional context**
Maybe this submission is back in the days when test cases didn't have a good coverage.

**Comment by CooperCooperCooper** [comment]
Hi @naco-siren,
Thank you for reaching out. I've filed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @naco-siren,
Thank you for your time. Base on your timely feedback, we've added some more test cases on this problem. Please try them out! We appreciate your time and support.
