### ISSUE TITLE
Missing Testcases in "ISLAND PERIMETER PROBLEM"

### ISSUE THREAD

**Issue by harshitmakhija** [LeetCode-Feedback/LeetCode-Feedback#600]
Leetcode user name: **harshitmakhija1204**

#### Category of the bug
- [ ] Question:  ISLAND PERIMETER (463)

#### Description of the bug
My solution is wrong and still got accepted if you will try  this test case :[[0,1,0,0],[0,0,0,1]]
My solution will give you answer:8 but the output is 4 while trying your custom input option. 

-My  Solution:
```
class Solution {
public:
   

 int islandPerimeter(vector<vector<int>>& grid) {
        int ans=0;
        vector<vector<int>>a=grid;
        int r=a.size();
        int cl=a[0].size();
        for(int i=0;i<r;i++){
            int c=0,c2=0;
            for(int j=0;j<cl;j++){
                if(a[i][j]==1){
                    c++;
                   if(j!=cl-1&&a[i][j+1]==1)
                       c2++;
                }          
            }
              ans+=2*(c-c2);
        }
             for(int j=0;j<cl;j++){
            int c=0,c2=0;
            for(int i=0;i<r;i++){
                if(a[i][j]==1){
                    c++;
                   if(i!=r-1&&a[i+1][j]==1)
                       c2++;
                }
        
            }
                    ans+=2*(c-c2);
        }
            return ans;
    }
};
```
- [ ] Language:c++

#### Description of the bug
My solution is wrong and still got accepted if you will try  this test case :[[0,1,0,0],[0,0,0,1]]
My solution will give you answer:8 but the output is 4 while trying your custom input option. 

Harshit Makhija
Leetcode user name: harshitmakhija1204
Thanks

**Comment by lc-christina** [comment]
hi @harshitmakhija 
Thanks for reaching out to us. The problem states that there is one island so the lands in your test case need to be connected. The test case you provided is not valid.
