### ISSUE TITLE
Missing Test Case - 1007. Minimum Domino Rotations For Equal Row

### ISSUE THREAD

**Issue by yalcinaksakal** [LeetCode-Feedback/LeetCode-Feedback#6002]
missing test case?
[2, 5, 1, 1]
[5, 2, 1, 1]

**Comment by stormsunshine** [comment]
What is the code that can get accepted but fails on the test case?

**Comment by yalcinaksakal** [comment]
var minDominoRotations = function (tops, bottoms) {
             const n = tops.length,
                       t = {},
                       b = {};
             let dest,
                  eq = n;

             for (let i = 0; i < n; i++) {
                    if (tops[i] == bottoms[i]) {
                            if (dest && dest != tops[i]) return -1;
                            dest = tops[i];
                            eq--;
                            if (!eq) return 0;
                           continue;
                     }
                     t[tops[i]] ? t[tops[i]]++ : (t[tops[i]] = 1);
                     b[bottoms[i]] ? b[bottoms[i]]++ : (b[bottoms[i]] = 1);
            }

            let res = n;
            for (const k of Object.keys(t)) {

                       if (!b[k] || b[k] + t[k] != eq) continue;
                       res = Math.min(res, b[k], t[k]);
             }

             return res == n ? -1 : res;
};

**Comment by LC-Sue** [comment]
Hi @yalcinaksakal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @yalcinaksakal 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
