### ISSUE TITLE
only introduction to dp is opening and rest other is still  lock,can anuone tell wgy it is notopening

### ISSUE THREAD

**Issue by cor1234** [LeetCode-Feedback/LeetCode-Feedback#6003]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @cor1234,
Thank you for reaching out to us, please contact us at support@leetcode.com for promotion related issues!
