### ISSUE TITLE
Missing Test Cases - 2141. Maximum Running Time of N Computers

### ISSUE THREAD

**Issue by arg2k** [LeetCode-Feedback/LeetCode-Feedback#6004]
#### Your LeetCode username

argha_kole 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Even though the code for the problem <a href="https://leetcode.com/problems/maximum-running-time-of-n-computers/">2141. Maximum Running Time of N Computers</a> passed all the test cases and was accepted,
but it's an incorrect solution .

#### Code you used for Submit/Run operation

```
// 2141. Maximum Running Time of N Computers
from heapq import heappush, heappop
class Solution:
    def maxRunTime(self, n: int, nums: List[int]) -> int:
        h = []
        for num in nums:
            heappush(h, -num)
        ans = 0
        while len(h) >= n:
            tmp = []
            for i in range(n):
                tmp.append(-heappop(h))
            ded = tmp[-1]//2
            if ded == 0:
                ded = tmp[-1]
            ans += ded
            for i in range(n):
                if tmp[i]-ded > 0:
                    tmp[i] -= ded
                    heappush(h, -tmp[i])
        return ans
```

#### Language used for code

 Python3

#### Expected behavior

The code is failing for the following sample testcases ->
```
  Input:
  6
  [1000000000,1000000000,1000000000,1000000000,1000000000,1000000000,1000000000,1]
  
  Output (Wrong):
  1031250000
  
  Expected Correct Output: 
  1166666666
```
``` 
  Input:
  5
  [1000000000,1000000000,1000000000,1000000000,1000000000,1000000000,1000000000]
  
  Output (Wrong):
  1333333333
  
  Expected Correct Output: 
  1400000000
```

**Comment by LC-Sue** [comment]
Hi @arg2k,
Thank you for reaching out to us. The code you provided returns time limit exceeded. Since there is no missing test case, I will close this ticket now! Thank you for understanding!
