### ISSUE TITLE
This is a redundant Problem https://leetcode.com/problems/search-a-2d-matrix/  and https://leetcode.com/problems/search-a-2d-matrix-ii/ are exactly same problems with same code 

### ISSUE THREAD

**Issue by ashiqYousuf** [LeetCode-Feedback/LeetCode-Feedback#6005]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @ashiqYousuf 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ashiqYousuf** [comment]
Glad to know that

**Comment by LC-Sue** [comment]
Hi @ashiqYousuf,
Thank you for your time. Our content team has decided that the two problems are different enough to be two problems and we are keeping both.

**Comment by ashiqYousuf** [comment]
Thank you for the clarification.
