### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by akulikoff** [LeetCode-Feedback/LeetCode-Feedback#6007]
#### Your LeetCode username
 alexeykulikov81 

#### Category of the bug
- [ ] Question

#### Description of the bug

Line 14 in solution.js
    var l1_ = l1.reverse().join('');
                 ^
TypeError: l1.reverse is not a function
    Line 14: Char 18 in solution.js (addTwoNumbers)
    Line 35: Char 19 in solution.js (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 24: Char 26 in solution.js (Object.<anonymous>)
    Line 1251: Char 30 in loader.js (Module._compile)
    Line 1272: Char 10 in loader.js (Object.Module._extensions..js)
    Line 1100: Char 32 in loader.js (Module.load)
    Line 962: Char 14 in loader.js (Function.Module._load)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    Line 17: Char 47 in run_main_module.js

#### Code you used for Submit/Run operation

```
// Two Sum
var addTwoNumbers = function(l1, l2) {
    var l1_ = l1.reverse().join('');
    var l2_ = l2.reverse().join('');
    var int1 = parseInt(l1_, 10);
    var int2 = parseInt(l2_, 10);
    var num = int1 + int2;
    var result = num.toString(10).split('').map(Number).reverse();
    return result;
};
```

#### Language used for code
Javascript

#### Expected behavior

My code works with examples from description of problem and with any others, but on leetcode i have runtime error

**Comment by stormsunshine** [comment]
If your code gets runtime error, you should check whether your code is correct or not rather than blaming test cases.

**Comment by LC-Sue** [comment]
Hi @akulikoff,
Thank you for reaching out to us, the test cases for the problem is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!

**Comment by akulikoff** [comment]
thank you! i have a mistake to solve problem like with array, but not linked list.
