### ISSUE TITLE
Typo - 383. Ransom Note

### ISSUE THREAD

**Issue by anandbibek** [LeetCode-Feedback/LeetCode-Feedback#6009]
#### Your LeetCode username
shoai

#### Category of the bug
- [x] Language

#### Description of the bug
Typo in Strings. `Given two stings ransomNote and magazine,`

**Comment by stormsunshine** [comment]
The word "stings" should be changed to "strings".

**Comment by LC-Sue** [comment]
Hi @anandbibek 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @anandbibek 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
