### ISSUE TITLE
Incorrect Test Case - 707. Design Linked List

### ISSUE THREAD

**Issue by BretMishler** [LeetCode-Feedback/LeetCode-Feedback#6012]
#### Your LeetCode username
positivecharge8

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

One of the LeetCode test cases that will fail your solution:

["MyLinkedList","addAtHead","get","addAtHead","addAtHead","deleteAtIndex","addAtHead","get","get","get","addAtHead","deleteAtIndex"]
[[],[4],[1],[1],[5],[3],[7],[3],[3],[3],[1],[4]]

Specifically:
```
            var head = new MyLinkedList();
            head.AddAtHead(4);
            head.Get(1);
```

The problem states in both the details and solution that "Assume all nodes in the linked list are 0-indexed." Therefore, `addAtHead` is equivalent to **inserting at index 0**.

Trying to `get` a value from index 1 at this state, where there is only a single element which is at index 0, should throw a `null` in a method that can only return an 'int'. Of course, the test does not expect anything but an `int` and thus fails.

#### Language used for code
C#

#### Expected behavior
Do not run a test that expects a value at an index which does not exist. or allow for the `get` method to be of type `int?`.

#### Screenshots

![image](https://user-images.githubusercontent.com/8965315/149846894-718046a7-b4f0-4810-b4b2-5f9abe604820.png)

**Comment by stormsunshine** [comment]
Did you read the problem description carefully? If the index is invalid, return -1.

Your solution should cover the case where the index is invalid. Your solution should be able to check whether the index is valid or not, and when the index is invalid, your solution should return -1 without throwing an exception.

Don't blame the test cases before you make sure that you have understood the problem description correctly.

**Comment by BretMishler** [comment]
> Did you read the problem description carefully? If the index is invalid, return -1.
> 
> Your solution should cover the case where the index is invalid. Your solution should be able to check whether the index is valid or not, and when the index is invalid, your solution should return -1 without throwing an exception.
> 
> Don't blame the test cases before you make sure that you have understood the problem description correctly.

I had read the lengthy problem description multiple times and had totally missed that specific instruction. There is no "blame" here and you're patronizing attitude is unnecessary.
