### ISSUE TITLE
Time complexity of heap element insertion  in the premium content.

### ISSUE THREAD

**Issue by prasasil** [LeetCode-Feedback/LeetCode-Feedback#6013]
#### Your LeetCode username
Silky_Prasad 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [ X] Wrong content in the heap  premium card  

#### Description of the bug
 Time complexity of creating a heap with n elements is correctly mentioned as n, but since heapify is performed for all the n elements it should be O(N logn) 

#### Screenshots

<img width="913" alt="Screenshot 2022-01-18 at 6 28 12 AM" src="https://user-images.githubusercontent.com/44384263/149852993-1fb092d5-fb03-45e1-b86d-72a9e1d792f7.png">

#### Top k elements card also has this problem
<img width="840" alt="Screenshot 2022-01-18 at 6 34 02 AM" src="https://user-images.githubusercontent.com/44384263/149853228-f471f805-3635-4a79-aed4-ae41f905b3ca.png">

**Comment by LC-Sue** [comment]
Hi @prasasil 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @prasasil,
Thank you for your time. This is counterintuitive indeed, but the time complexity is correct. You can read more about why this is the case here:
https://stackoverflow.com/questions/9755721/how-can-building-a-heap-be-on-time-complexity#:~:text=Heapify%20is%20O(n)%20when,O(n%20log%20n)%20
