### ISSUE TITLE
Don't blame the test cases 

### ISSUE THREAD

**Issue by BretMishler** [LeetCode-Feedback/LeetCode-Feedback#6014]
Did you read the problem description carefully? If the index is invalid, return -1.

Your solution should cover the case where the index is invalid. Your solution should be able to check whether the index is valid or not, and when the index is invalid, your solution should return -1 without throwing an exception.

Don't blame the test cases before you make sure that you have understood the problem description correctly.

_Originally posted by @stormsunshine in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/6012#issuecomment-1014985466_

There was no blame, simply a mistake on my part in missing one of the instructions in the problem requirements, despite reading it multiple times. I'm exhausted from all of the LeetCode practice and my mind simply slipped, but I thought I could help the community by sharing an "incorrect test case".

@stormsunshine provided a patronizing answer and all that need be said was, "The instructions say: int get(int index) Get the value of the indexth node in the linked list. If the index is invalid, return -1." 

As a tutor, teacher, and CS contributor myself, I humbly request that we please hold our contributors to better standards in their responses.

**Comment by LC-Sue** [comment]
Hi @BretMishler,
Thank you for sharing. Every user on our platform would be considered a contributor to us and I believe our goal is the same - to make LeetCode a better place for the community. We at LeetCode will ensure our support is respectful, friendly, and professional to our users feedback. As clarification, the user you've mentioned is not part of our team and we are sorry for any miscommunication.
