### ISSUE TITLE
Wrong solution - Minimize Malware Spread 

### ISSUE THREAD

**Issue by kushalmahajan** [LeetCode-Feedback/LeetCode-Feedback#602]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Wrong solution for approach#2 Union find
https://leetcode.com/problems/minimize-malware-spread/

```
class DSU{
public:
    vector<int> parent;
    vector<long long int> size;
    DSU(int n){
        for(int i = 0; i < n; i++){
            parent.push_back(i);
        }
        size.resize(n, 1);
    }
    int find(int node){
        int root = node;
        while(parent[node] != root)
            root = parent[node];
        
        // path compression
        while(node != root){
            int oldroot = parent[node];
            parent[node] = root;
            node = oldroot;
        }
        return root;
    }
    
    void unionS(int A, int B){
        int rootA = find(A);
        int rootB = find(B);
        if(size[A] < size[B]) {
            parent[rootA] = rootB;
            size[B] += size[rootA];
        }else{
            parent[rootB] = rootA;
            size[rootA] += size[rootB];
        }
    }
    int getSize(int node){
        return size[node];
    }
    
};

class Solution {
public:
    int minMalwareSpread(vector<vector<int>>& graph, vector<int>& initial) {
        int n = graph.size();
        DSU *dsu = new DSU(n);
        for(int i = 0; i < n; ++i)
            for(int j = i+1; j < n; ++j)
                if(graph[i][j] == 1)
                    dsu->unionS(i, j);
        
       //  find the count of each component formed from union operation
        vector<int> count(n, 0);
        for(int node: initial)
            count[dsu->find(node)]++;
        
        int ans = -1;
        int ansSize = -1;
        for(int node: initial){
            int root = dsu->find(node);
            if(count[root] == 1){ // unique color
                int rootSize = dsu->getSize(root);
                if(rootSize > ansSize){
                    ansSize = rootSize;
                    ans = node;
                } else if (rootSize == ansSize && node < ans) {
                    ans = node;
                }
            }
        }
        if(ans == -1){
            ans = INT_MAX;
            for(int node: initial)
                ans = min(ans, node);
        }
        
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The solution as per approach 2 union find coded in C++ fails for test case ad others as well. `[[1,0,0,0,1,0,1,0,1,1,1,0,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0],[0,0,1,0,0,0,0,1,1,0,1,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],[0,0,0,1,0,0,1,1,0,1,0,0,0,0,1,1,0,1,1,0,0,0,1,0,0,1,0,0,1,1],[1,0,0,0,1,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1],[0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0,1,0,0,1,0,1,0,1,0,1,0,0,0,1],[1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0],[0,0,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1],[1,0,1,0,1,1,0,0,1,0,0,0,1,1,0,1,0,0,1,1,0,0,0,0,0,1,0,0,0,0],[1,0,0,1,0,1,1,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0],[1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0],[0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,1,0,0,0,1,0,0,1],[1,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1,0],[1,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0],[0,0,1,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0],[0,0,0,1,0,0,0,0,1,1,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0],[1,0,0,...
[13,4,1,3]`. 

#### Additional context
The only changes I did to original approach were in unionS function and getFunction. UnionS should union as per the size which was missing and size function can directly return `size[node]` since we are already passing root. But anyway with original UnionFind function as well the approach would fail o some test cases.

**Comment by lc-christina** [comment]
Hi @kushalmahajan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @kushalmahajan ,
Thanks for the time. The team has looked into the official solution and both Java and Python approaches are accepted.
