### ISSUE TITLE
Typo in Constraints - 539. Minimum Time Difference

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6020]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [539. Minimum Time Difference](https://leetcode.com/problems/minimum-time-difference), there is a typo in Constraints.

The first constraint is: 2 <= timePoints <= 2 * 10<sup>4</sup>

It should be: 2 <= timePoints.length <= 2 * 10<sup>4</sup>

#### Expected behavior
The first constraint should be updated to change `timePoints` to `timePoints.length`.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
