### ISSUE TITLE
Missing Test Case - 489. Robot Room Cleaner

### ISSUE THREAD

**Issue by baobaollf** [LeetCode-Feedback/LeetCode-Feedback#6024]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The second paragraph of the question description, root should be room. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?

**Comment by LC-Sue** [comment]
Hi @baobaollf 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @baobaollf 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
