### ISSUE TITLE
Runtime Error Signed Integer Overflow missing testcase 1010. Pairs of Songs With Total Durations Divisible by 60

### ISSUE THREAD

**Issue by Alpier** [LeetCode-Feedback/LeetCode-Feedback#6026]
#### Your LeetCode username
Aliers

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Hello! :)
I submitted a code to the problem;
https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/
This code returned me an accepted verdict, but it returns Runtime Error (Signed Integer Overflow) in the following testcase:
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7886879/testcase.txt)
https://cdn.discordapp.com/attachments/765012182345711636/932892115170635826/message.txt

#### Code you used for Submit/Run operation

```cpp
// https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/
class Solution {
public:
	int numPairsDivisibleBy60(vector<int>& time) {
		vector<int> remainder_count(61); long long int ans = 0;
		for(int x : time) remainder_count[x % 60]++;
		remainder_count[60] = remainder_count[0];
		for(int i = 1; i < 30; i++) {
			ans += remainder_count[i] * remainder_count[60-i];
		}
		ans += remainder_count[0] * (remainder_count[0]-1) / 2;
		ans += remainder_count[30] * (remainder_count[30]-1) / 2;
		return ans;
	}	
};
```

#### Language used for code
C++

**Comment by LC-Sue** [comment]
Hi @Alpier 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Alpier 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
