### ISSUE TITLE
提交bug：提交的报错结果与本地IDEA结果不同

### ISSUE THREAD

**Issue by MiSheep** [LeetCode-Feedback/LeetCode-Feedback#6033]
**你的 LeetCode 用户名**
浅羊

**Bug 类型**
-  [X] 编程语言

**描述**
在题目：[187. 重复的DNA序列](https://leetcode-cn.com/problems/repeated-dna-sequences/)中，我使用Java语言提交一段代码，发现在某测试用例报错，而报错中的返回结果和我在本地IDEA运行时的结果不同，也和官方测试用例工具的结果不同。

详细：
对于测试用例：`"AAAAAAAAAAA"`，我的代码在下方测试用例中执行结果正常，在本地IDEA也正常。然而点击提交后，却提示该测试用例解答错误，报错提示在该测试用例处返回空。

![图片](https://user-images.githubusercontent.com/30747209/149896376-48a9a586-9d99-4d27-ab56-57297ec0dc76.png)

**你使用的语言**
JAVA

**你提交或者运行的代码**
```
// https://leetcode-cn.com/problems/repeated-dna-sequences/submissions/
class Solution {
    static byte a[] = new byte[1 << 20];
    static int b[] = new int[85];//包含 ACGT 的哈希表

    static {
        b['C'] = 262144;
        b['G'] = 524288;
        b['T'] = 786432;
    }

    public List<String> findRepeatedDnaSequences(String s) {

        List<String> ans = new ArrayList<>();
        int n = s.length();
        if (n <= 10) return ans;
        char[] cs = s.toCharArray();
        int x = 0;
        for (int i = 0; i < 10; i++) {
            x >>= 2;
            x |= b[cs[i]];
        }
        a[x]++;
        for (int i = 10; i < n; i++) {
            x >>= 2;
            x |= b[cs[i]];
            if (a[x] == 0) a[x] = 1;
            else if (a[x] == 1) {
                a[x]++;
                ans.add(s.substring(i - 9, i + 1));
                System.out.println("yes");
            }
        }
        return ans;
    }
}
```

**期望行为**
![图片](https://user-images.githubusercontent.com/30747209/149896475-a0c5aaad-be41-494c-8430-e74f2ce6079c.png)

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
Please do not use static variables since static variables will cause different results between local testing and submission.

**Comment by MiSheep** [comment]
> 这是因为你使用了静态变量，而leetcode为了加速判题，会采用多线程的模式判题，导致对静态变量的竞争，你把静态去掉就好了

明白了，谢谢

**Comment by MiSheep** [comment]
> Please do not use static variables since static variables will cause different results between local testing and submission.

Thanks
