### ISSUE TITLE
Misleading/contradicting information in Maximum Width of Binary Tree

### ISSUE THREAD

**Issue by peterschussheim** [LeetCode-Feedback/LeetCode-Feedback#604]
#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language

#### Description of the bug

According to [Types of binary trees](https://en.wikipedia.org/wiki/Binary_tree#Types_of_binary_trees), a **full binary tree** is:

>A full binary tree (sometimes referred to as a proper or plane binary tree) is **a tree in which every node has either 0 or 2 children**. Another way of defining a full binary tree is a recursive definition. A full binary tree is either:
> - A single vertex.
> - A tree whose root node has two subtrees, both of which are full binary trees.

In the problem description for this question, the following line is worded incorrectly or is misleading:

>The width of a tree is the maximum width among all levels. **The binary tree has the same structure as a full binary tree, but some nodes are null**.

Why is this question telling users to expect a full binary tree (using a universally accepted definition) then immediately after specifying that, says "**but** some nodes are null."? 

Looking at example 4:

```
Input: 

          1
         / \
        3   2
       /     \  
      5       9 
     /         \
    6           7
Output: 8
Explanation:The maximum width existing in the fourth level with the length 8 (6,null,null,null,null,null,null,7).
```

kindly prove how the provided output aligns with the definition of a full binary tree.

**Comment by lc-christina** [comment]
Hi @peterschussheim 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @peterschussheim 
Thank you for your time. We've used your feedback to update the problem. Let me know anytime if you would like to receive reward for the contribution :)

**Comment by peterschussheim** [comment]
Thank you!

________________________________
