### ISSUE TITLE
missing Testcase 1345. Jump Game IV

### ISSUE THREAD

**Issue by Shivam584** [LeetCode-Feedback/LeetCode-Feedback#6041]
#### Your LeetCode username
 
Skagar584

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

my code has cleared all the existing leetcode test cases but I found some test cases for which it is giving output as time limit exceeded. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minJumps(vector<int>& a) {
int n=a.size(),c=0;   
        if(n==1)
            return 0;
        if(a[0]==a[n-1])
            return 1;
        vector<int> arr;
        arr.push_back(a[0]);
        for(int i=1;i<n-1;i++)
        {
            if(a[i-1]==a[i]||a[i+1]==a[i-1])
                c++;
            else
                c=0;
            if(c<=1)
            {
                arr.push_back(a[i]);
            }
        }
        arr.push_back(a[n-1]);
        n=arr.size();
  
        vector<vector<int>> v (n,vector<int>(0));
        for(int i=0;i<n-1;i++)
        {v[i].push_back(i+1);
            v[i+1].push_back(i);}
        unordered_map<int,vector<int>> mp;
        for(int i=0;i<n;i++)
            mp[arr[i]].push_back(i);
        for(auto x=mp.begin();x!=mp.end();x++)
        {
            auto v1=x->second;
                for(int i=0;i<v1.size()-1;i++)
                for(int j=i+1;j<v1.size();j++)
                {
                    v[v1[i]].push_back(v1[j]);
                    v[v1[j]].push_back(v1[i]);
                }
        }
        int l=1,ps=0;
        c=0;
        queue<int> q;
        q.push(0);
        vector<bool> b(n);
b[0]=true;
        while(!q.empty())
        {
            int x=q.front(),t=0;
            q.pop();
            if(x==n-1)
                return c;
            for(int j=0;j<v[x].size();j++)
                if(!b[v[x][j]])
                {
                    b[v[x][j]]=true;
                    q.push(v[x][j]);
                    t++;
                }
            ps+=t;
             l--;
            if(l==0)
            {
                l=ps;
                ps=0;
                c++;
            }
        }
        return -1;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
missing test case in which i am getting tle.
*(assuming that array size is up to 50000.)*
input arr=[6,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,....7,11] 
[1345_missing_testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7902282/1345_missing_testcase.txt)
Expected Output :  6

Resulted Output : time limit exceeded

#### Additional context
A series of repeating numbers in between arr[0] to arr[n-1] can cause time limit exceeded .
where n is size of array (atleast 25000) 
example - [6,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,....,7,11]

**Comment by LC-Sue** [comment]
Hi @Shivam584,
Thank you for reaching out to us, could you provide the test case in a .txt file?

**Comment by Shivam584** [comment]
Hi @LC-Sue 
 Thank you for replying , here is the missing testcase .   
[1345_missing_testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7902282/1345_missing_testcase.txt)

**Comment by Shivam584** [comment]
hi @LC-Sue this is general reminder from my end regarding the missing testcase of Q 1345.

**Comment by LC-Sue** [comment]
Hi @Shivam584 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Shivam584 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
