### ISSUE TITLE
539. 最小时间差 官方题解空间复杂度有误

### ISSUE THREAD

**Issue by Huali23** [LeetCode-Feedback/LeetCode-Feedback#6042]
**你的 LeetCode 用户名**
Huali23

**Bug 类型**
题解

**描述**
在题目 539. 最小时间差 中，官方题解给出的代码空间复杂度为 O(logn) 。题解这行代码 Collections.sort(timePoints);   
用到了jdk源码的 Collections.sort(); 阅读源码发现 底层有这行代码 Object[] a = this.toArray();   
从这行代码找到 ArrayList 的 Arrays.copyOf(elementData, size) 发现底层是对每个对象复制了一份新的数据，所以空间复杂度应该是O(n)

**你使用的语言**
Java

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@Huali23 
你好，当前官方题解空间复杂度已更新，ID：Huali23 给予积分奖励，请查收。
