### ISSUE TITLE
70题中文翻译条件丢失

### ISSUE THREAD

**Issue by sona201** [LeetCode-Feedback/LeetCode-Feedback#6043]
**你的 LeetCode 用户名**
Copy

**Bug 类型**
- [x] 题目

**描述**
描述你遇到的 bug
中文翻译中条件缺失

英文版有条件
Constraints:
1 <= n <= 45
而中文什么都没有

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@sona201 你好，当前题目描述已更新，ID：Copy 给予积分奖励，请查收。
