### ISSUE TITLE
Erroneous Boilerplate Comment - 278. First Bad Version

### ISSUE THREAD

**Issue by jcordial** [LeetCode-Feedback/LeetCode-Feedback#6047]
#### Your LeetCode username

jpcordial

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The doc comments included in the test do not align with the test question itself. The test question states `is_bad_version` returns a boolean value, but the doc comment reads:

```python
# The isBadVersion API is already defined for you.
# def isBadVersion(version: int) -> int:
```

While a boolean is always an int, an int is not always a boolean. The comment should read:

```python
# The isBadVersion API is already defined for you.
# def isBadVersion(version: int) -> bool:
```

#### Code you used for Submit/Run operation

```python
# The isBadVersion API is already defined for you.
# def isBadVersion(version: int) -> int:

class Solution:
    def firstBadVersion(self, n: int) -> int:
        pass
```

#### Language used for code

Python3

#### Expected behavior

Behavior is fine, I'm just being technically correct. :smile: 
![Technically Correct](https://media.giphy.com/media/14bDMRUYVrzOIo/giphy.gif)

#### Screenshots

![Screenshot from 2022-01-18 15-16-54](https://user-images.githubusercontent.com/1890058/150012145-513b0159-f283-4a38-9a9c-122e513277d4.png)

#### Additional context

I'm going to facepalm so hard when you tell me why I'm wrong - but hey, I'm here to learn, so :man_shrugging: :laughing:

**Comment by LC-Sue** [comment]
Hi @jcordial 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jcordial,
Thank you for your time. The issue has already been address last month.
