### ISSUE TITLE
Missing Test Case - 444. Sequence Reconstruction

### ISSUE THREAD

**Issue by wanli0915** [LeetCode-Feedback/LeetCode-Feedback#6053]
#### Your LeetCode username
Max_Towns

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

✅  Missing Test Cases 

#### Description of the bug

Submission accepted but customer test case failed -> missing test cases

#### Code you used for Submit/Run operation

```
class Solution:
    def sequenceReconstruction(self, nums: List[int], sequences: List[List[int]]) -> bool:
        
        num_to_indegree = defaultdict(int)
        num_to_next = defaultdict(list)
        for seq in sequences:
            for i in range(len(seq) - 1):
                num_to_next[seq[i]].append(seq[i + 1])
                num_to_indegree[seq[i + 1]] += 1
            
        start = float('inf')
        for num in nums:
            if num not in num_to_indegree:
                if start != float('inf'):
                    return False
                start = num
                
        queue = collections.deque()
        queue.append(start)
        count = 0
        
        while queue:
            cur_num = queue.popleft()
            if cur_num != nums[count]:
                return False
            count += 1
            for next_num in num_to_next[cur_num]:
                if num_to_indegree[next_num] == 1:
                    num_to_indegree[next_num] = 0
                    queue.append(next_num)
                    if len(queue) > 1:
                        return False
        return True
```

#### Language used for code

Python

#### Expected behavior

What actually happened: Submission Accepted https://leetcode.com/submissions/detail/622987409/
Customer Test Case Result Failed.
Input:
```
[1,2,4,3]
[[1,2],[1,3],[2,3],[1,4],[2,4]]
```
Output:
```
True
```
Expected:
```
False
```

**Comment by LC-Sue** [comment]
Hi @wanli0915 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @wanli0915 
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution could you please provide your LeetCode username?

**Comment by wanli0915** [comment]
Glad that helps! My Leetcode username is HuaCaiCai. Thank you!

**Comment by LC-Sue** [comment]
Hi @wanli0915 
Thank you for your time. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
