### ISSUE TITLE
204. Count Primes: The Time Limit Exceeded is too strict for python 2 in new website, and python 2 runs too slow in the new website compared to python 3

### ISSUE THREAD

**Issue by czw0078** [LeetCode-Feedback/LeetCode-Feedback#6054]
#### Category of the bug
- Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The time limit is too strict for python 2, even the official python solution can not pass all cases in time. Compare to Python3 speed, Python 2 runs slower in the new version of the website, which may cause the issue.

#### Code you used for Submit/Run operation
Use official python solution for 204. Count Primes

#### Language used for code
Python 2

#### Expected behavior
Pass all cases

**Comment by LC-Sue** [comment]
Hi @czw0078 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @czw0078 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
