### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by Gaurav61720** [LeetCode-Feedback/LeetCode-Feedback#6055]
Gaurav61720
#### Your LeetCode username

[ ] Solution
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Wrong Answer Details 
Input:-"pwwkew"
Output:-4
Expected:-3
The right answer will be 4 instead of 3.

#### Code you used for Submit/Run operation

```
class Solution {
    public int lengthOfLongestSubstring(String s) {
         int count=0; 
        HashMap<String,Integer> map = new HashMap<>();
        for(int i=0;i<s.length();i++){
            if(map.containsKey(Character.toString(s.charAt(i)))!=true){
                count++;
                map.put(Character.toString(s.charAt(i)),count);
            }
        }
        return count;
    }
}
```

#### Screenshots

![Screenshot (9)](https://user-images.githubusercontent.com/30591205/150085762-2310fcad-a16e-4bfd-aaec-48d189a0aa40.png)

**Comment by stormsunshine** [comment]
Why do you think the answer should be 4? Consider all substrings with length 4 as follows.
```
"pwwk"
"wwke"
"wkew"
```
All substrings have repeating characters.

**Comment by LC-Sue** [comment]
Hi @Gaurav61720,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
