### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by Nishant1972** [LeetCode-Feedback/LeetCode-Feedback#6058]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [yes ] Missing Test Cases 

#### Description of the bug

The question states to calculate x raised to power n. And when x=0 and n=0. The expected answer returns 1.00000. So, this seems to be invalid test case in the question.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
       double myPow(double x, int n) {
        if(x ==0  &&  n ==0)
            return -1;
       return pow(x, double(n));
    }
};
```

#### Expected behavior

At n = 0 and x = 0, as Pow(0,0) is undefined. So, testcase must be removed.

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case? Don't create meaningless issues!

**Comment by Nishant1972** [comment]
There is one test case when x= 0 and n= 0. This is a invalid test case. But
the expected answer is giving 1 as answer.

**Comment by LC-Sue** [comment]
Hi @Nishant1972,
Thank you for reaching out to us, could you provide the code you used for submission and the test case that you'd like to report missing?

**Comment by LC-Sue** [comment]
Hi @Nishant1972 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
