### ISSUE TITLE
Test Case - 32. Longest Valid Parentheses

### ISSUE THREAD

**Issue by Alperencode** [LeetCode-Feedback/LeetCode-Feedback#6059]
#### Your LeetCode username

Alperencode

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Test Cases 

#### Description of the bug

"()(()" -> This test case has 2 valid parentheses so expected output need to be '4'. Is there something that I get wrong? (There is no need to check my code its a bit complex my problem is with the test case)

#### Code you used for Submit/Run operation

```python
class Solution(object):
    def longestValidParentheses(self, s):
        valid = 0
        counter = 0
        for i in s:
            openCounter = 0
            closeCounter = 0
            newCounter = counter
            try:
                if i == "(" and (s[counter + 1] == ")"):
                    valid += 2
                    counter += 1
                    continue
            except:
                pass
            try:
                while s[newCounter] == "(":
                    newCounter += 1
                    openCounter += 1
            except:
                pass
            try:
                while s[newCounter] == ")":
                    newCounter += 1
                    closeCounter += 1
            except:
                pass
            if openCounter >= closeCounter and (openCounter != 0):
                valid += closeCounter * 2
                counter += newCounter
                continue
            elif openCounter < closeCounter and (openCounter != 0):
                valid += openCounter * 2
                counter += newCounter
                continue
            counter += 1
            
        return valid
```

#### Language used for code

Python

#### Expected behavior

Expected output need to be '4' instead of '2'

**Comment by stormsunshine** [comment]
The term "substring" is different from "subsequence". A substring must be consecutive characters from the original string.

**Comment by Alperencode** [comment]
Sorry but i still didn't get it. Then  that "(()" case needs to be 0 but its 2. That case "()(()" (which i have problem with) is the same case but just have extra one more valid parentheses at the beginning. So if the "(()" output is 2 then "()(()" needs to be 4, logically.

**Comment by stormsunshine** [comment]
Did you read my reply? I mentioned the term "substring". This problem requires returning the longest substring of the input string such that the substring is a valid parentheses substring, not the longest subsequence.

For test case `"(()"`, there is a substring `"()"` that is a valid parentheses substring, so the answer is 2.

For test case `"()(()"`, there are two substrings `"()"` that are valid parentheses substrings, each of which has length 2. If you think the answer is 4, could you please tell me which substring of length 4 is a valid parentheses substring? The two substrings of length 4 are `"()(("` and `")(()"`. Which substring is a valid parentheses substring?

> Sorry but i still didn't get it. Then that "(()" case needs to be 0 but its 2. That case "()(()" (which i have problem with) is the same case but just have extra one more valid parentheses at the beginning. So if the "(()" output is 2 then "()(()" needs to be 4, logically.

**Comment by LC-Sue** [comment]
Hi @Alperencode,
Thank you for reaching out to us! I hope stormsunshine's response was able to answer your question! Please let me know if you have any other questions!
