### ISSUE TITLE
Question 687: confusing description

### ISSUE THREAD

**Issue by dmitrygorbenko** [LeetCode-Feedback/LeetCode-Feedback#606]
#### Username
dimagorbenko

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
In the "Example 1" you have a tree where the longest path is 5-5-5. Also we have shorter paths like 5-5 and another one 5-5. So, in total the longest path is only on and is 5-5-5.
Now, you define a length between two nodes as a number of edged between them, which means in a path "5-5-5" the length is 1 (because we have only 1 node between edges).

Can you give more detailed explanation why you expect "2" as a result in "Example 1" ?

Thank you

**Comment by lc-christina** [comment]
Hi @dmitrygorbenko ,
The length is defined by 'the number of edges' between nodes. For example 1, 5-5-5, there are 2 edges so its length is 2.

**Comment by dmitrygorbenko** [comment]
If so, then this means what each and any path has length of 2, because there are always 2 edge nodes in any path.
5-5-5 has two edges.
1-2-3-4 has also two edges.
and so on.
So, the longest path will always be 2, which doesn't make any sense.

**Comment by dmitrygorbenko** [comment]
nevermind.
my problem was in terminology, I was expecting "edge" to be a node, instead of connection between two nodes.
sorry.
