### ISSUE TITLE
Missing Test Case - 1235. Maximum Profit in Job Scheduling

### ISSUE THREAD

**Issue by sakethsriram** [LeetCode-Feedback/LeetCode-Feedback#6060]
#### Your LeetCode username
Sakethsriram

#### Category of the bug
 Missing Test Cases 

#### Description of the bug

the code I submitted should fail on system testcases but it is accepted.
so i created a custom testcase for which accepted code failed
testcase = [1,2,3,3]
                  [3,4,5,1000000000]
                  [50,10,40,70]
So, please add the above testcase for following question

#### Code you used for Submit/Run operation

```
// 1235. Maximum Profit in Job Scheduling
import java.util.*;

class Solution {
    public int jobScheduling(int[] startTime, int[] endTime, int[] profit) {
        int n = startTime.length;
        int[][] intervals = new int[n][3];
        for(int i = 0; i < n; i++){
            intervals[i][0] = startTime[i];
            intervals[i][1] = endTime[i];
            intervals[i][2] = profit[i];
        }
        Arrays.sort(intervals,(int a[],int b[])->{
            return a[1]-b[1]!=0?a[1]-b[1]:a[0]-b[0];
        });
        int maxLength = 0;
        for(int i=0;i<intervals.length;i++)
        {
            maxLength= Math.max(maxLength,intervals[i][1]);
        }
        HashMap<Integer,ArrayList<Integer>> map = new HashMap<Integer,ArrayList<Integer>>();
        for(int i=0;i<intervals.length;i++)
        {
            if(map.containsKey(intervals[i][1]))
            {
                map.get(intervals[i][1]).add(i);
            }
            else
            {
                ArrayList<Integer> list = new ArrayList<Integer>();
                list.add(i);
                map.put(intervals[i][1],list);
            }
        }
        int dp[]= new int[maxLength+1];
        for(int i=0;i<=maxLength;i++)
        {
            if(map.containsKey(i))
            {
                int max = 0;
                for(int ele: map.get(i))
                {
                    max = Math.max(dp[intervals[ele][0]]+intervals[ele][2],max);
                }
                dp[i] = Math.max(max,dp[i-1]);
            }
            else
            {
                dp[i] = i==0?0:dp[i-1];
            }
        }
        return dp[dp.length-1];
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

the code I submitted should fail on system testcases but it is accepted.
so i created a custom testcase for which accepted code failed

#### Screenshots

![image](https://user-images.githubusercontent.com/75611451/150121666-2ca51f6a-2cc0-415d-b7b9-38ec8cdbb8cf.png)

**Comment by LC-Sue** [comment]
Hi @sakethsriram 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sakethsriram 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
