### ISSUE TITLE
点击"执行代码"按钮能通过的案例数据, 到了点击"提交"后,同样的案例数据就通不过了?

### ISSUE THREAD

**Issue by hellosrc** [LeetCode-Feedback/LeetCode-Feedback#6061]
题目:  146. LRU 缓存
![image-20220119200743952](https://user-images.githubusercontent.com/65019264/150126655-083edf40-5907-4edd-8fe7-2072dd08910c.png)

**Comment by LC-Sue** [comment]
Hi @hellosrc 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
