### ISSUE TITLE
编译不通过，但本地测试执行正常

### ISSUE THREAD

**Issue by myaijarvis** [LeetCode-Feedback/LeetCode-Feedback#6062]
**myaijarvis**
填写你登录 LeetCode（中国区）的用户名：myaijarvis

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [√] 编程语言
- [ ] 缺少测试用例

**描述**
编译不通过，但本地测试执行正常

**你使用的语言**
Java

题目：[347. 前 K 个高频元素 - 力扣（LeetCode）](https://leetcode-cn.com/problems/top-k-frequent-elements/)

**你提交或者运行的代码**
```
class Solution {
    public List<Integer> topKFrequent(int[] nums, int k) {
        // 使用字典，统计每个元素出现的次数，元素为键，元素出现的次数为值
        HashMap<Integer, Integer> map = new HashMap<>();
        for (int item : nums) {
            if (map.containsKey(item)) {
                map.put(item, map.get(item) + 1);
            } else {
                map.put(item, 1);
            }
        }
        // 遍历map，用小顶堆保存频率最大的k个元素
        PriorityQueue<Integer> pq = new PriorityQueue<>(new Comparator<Integer>() {
            @Override
            public int compare(Integer o1, Integer o2) {
                return map.get(o1) - map.get(o2);
            }
        });
        
        for (Integer key : map.keySet()) {
            if (pq.size() < k) {
                pq.add(key);
            } else if (map.get(key) > map.get(pq.peek())) {
                pq.poll();
                pq.add(map.get(key));
            }
        }
        // 取出最小堆中的元素
        ArrayList<Integer> list = new ArrayList<>();
        while (!pq.isEmpty()) {
            list.add(pq.poll());
        }
        Collections.reverse(list);// 反转
        return list;
    }
}
```

**期望行为**
执行成功

**屏幕截图**
![image](https://user-images.githubusercontent.com/52879894/150136969-5cfdd080-d66e-40e5-8d27-078c7764c3b9.png)

**额外的上下文**
添加额外的上下文信息

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
