### ISSUE TITLE
Heap's card : Implementation of a Heap Typo 

### ISSUE THREAD

**Issue by umang4846** [LeetCode-Feedback/LeetCode-Feedback#6063]
#### Category of the bug
- [ ] Language

#### Description of the bug

In Heap's explore card, in the first chapter's Implementation of a Heap section contains a typo in the java and Python code where printing Add too many elements! instead of Added too many elements!

#### Code you used for Submit/Run operation

```
    if (realSize > heapSize) {
            System.out.println("Add too many elements!");
            realSize--;
            return;
        }
```

#### Language used for code

Java 
Python

#### Expected behavior

Should print "Added too many elements!" while currently printing "Add too many elements!"

#### Screenshots

![image](https://user-images.githubusercontent.com/26818981/150151012-bfcc979d-b28d-41b0-85f2-c78b9d8418a0.png)

**Comment by LC-Sue** [comment]
Hi @umang4846 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @umang4846 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
