### ISSUE TITLE
121. 买卖股票的最佳时机 testcase 错误

### ISSUE THREAD

**Issue by yc-alex-xu** [LeetCode-Feedback/LeetCode-Feedback#607]
** Bug 类型**
测试用例错误
- [ ] 题目121. 买卖股票的最佳时机
- [ V] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
测试用例错误

**你使用的语言**
go

**你提交或者运行的代码**
```
```

**期望行为**
解答正确

**屏幕截图**

执行结果：
解答错误
显示详情
输入:
[7,1,5,3,6,4]
输出
7
预期结果
5
**额外的上下文**
(5-1)+(6-3)=7 才是合理答案

**Comment by yc-alex-xu** [comment]
wrong

**Comment by zerotrac** [comment]
请注意题目描述部分：

如果你最多只允许完成一笔交易（即买入和卖出一支股票一次），设计一个算法来计算你所能获取的最大利润。
