### ISSUE TITLE
445: Add Two Numbers II Solution Issue

### ISSUE THREAD

**Issue by barakharari** [LeetCode-Feedback/LeetCode-Feedback#6070]
#### Your LeetCode username
barakharari

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Solution 2 example in the comment sums up 333 and 77, but in the end claims that the results is 410 which is incorrect, it should be 400.

**Comment by stormsunshine** [comment]
333 + 77 should be 410. Is there any problem?
