### ISSUE TITLE
Easy interview problems > strings have medium level problem

### ISSUE THREAD

**Issue by tatianajiselle** [LeetCode-Feedback/LeetCode-Feedback#6072]
#### Your LeetCode username
tatianajiselle 

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Easy Top Interview Problems, section Strings, should contain all easy problems. However, Count And Say, is listed as medium on normal leetcode problems.

Link to interview course: https://leetcode.com/explore/interview/card/top-interview-questions-easy/127/strings/886/ 
LInk to problem: https://leetcode.com/problems/count-and-say/ 

#### Code you used for Submit/Run operation
not applicable

#### Expected behavior
Count and Say should be categorized under the medium interview problems for the Top Interview Questions Chapter

#### Screenshots
![Screen Shot 2022-01-19 at 8 40 28 PM](https://user-images.githubusercontent.com/13118794/150274658-1ec9ef78-2670-41f1-9ae0-1830acae7f50.png)

![Screen Shot 2022-01-19 at 8 40 22 PM](https://user-images.githubusercontent.com/13118794/150274654-13bbf084-6c14-4fc9-8ad5-5c52a53ed4ba.png)

#### Additional context
N/A

**Comment by stormsunshine** [comment]
Count and Say used to be an Easy problem and I also think this problem should be an Easy problem. I do not understand why LeetCode changed the difficulty to Medium.

**Comment by tatianajiselle** [comment]
@stormsunshine no one cares what you think

**Comment by tatianajiselle** [comment]
also to leetcode: 

the same situation is happening with https://leetcode.com/problems/valid-sudoku/ which is now rated medium and is still in the easy interview problems chapter.

**Comment by stormsunshine** [comment]
@tatianajiselle What do you mean by replying me no one cares what I think? Do you think anyone cares what you think?

What I replied was a truth that Count and Say used to be an Easy problem and LeetCode changed the difficulty to Medium sometime afterwards. I said that I also think the problem should be an Easy problem. This is to say that my suggestion is that LeetCode should change the difficulty of the problem back to Easy. Why isn't this a possible way to solve the problem you mentioned?

**Comment by LC-Sue** [comment]
Hi @tatianajiselle 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LPRowe** [comment]
@tatianajiselle Thank you for identifying the issue! This will be resolved for both problems soon.  

@stormsunshine Thank you for your consistent contributions! It helps others by receiving your advice early on and it often makes it easier for us to more quickly identify which issues are the result of an error on our side versus a mistake made by a user.

**Comment by LPRowe** [comment]
As a side note, both of these problems are on the borderline.  I assume there was a good reason for changing their difficulty in the past.  In general, when a problem could fall into easy or medium, it may be better to place it in the higher difficulty category so users who regularly solve medium problems may find it too easy as opposed to users who regularly solve easy problems feeling frustrated.

**Comment by CarlCzerny837** [comment]
> also to leetcode:
> 
> the same situation is happening with https://leetcode.com/problems/valid-sudoku/ which is now rated medium and is still in the easy interview problems chapter.

The problem 36.valid-sudoku also used to be an easy-level problem, and I think the difficulty of the problem 36 and 38 is not enough to be marked as "medium". I think LeetCode should change the difficulty of these problems back to "easy".

**Comment by LC-Sue** [comment]
Hi @tatianajiselle 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
