### ISSUE TITLE
Bug on Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by useranbu** [LeetCode-Feedback/LeetCode-Feedback#6073]
#### Your LeetCode username

anbuarasan0344

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Test Cases 

#### Description of the bug

For 1346, there is one test case ```[-2,0,10,-19,4,6,-8]``` for which the expected answer is ```false``` but I think it should be ```true```. There is ```0``` in the array and ```2 * 0 = 0``` which is present in the array.

#### Code you used for Submit/Run operation

```
// 1346. Check If N and Its Double Exist
public class Solution {
    public bool CheckIfExist(int[] arr) {
        Array.Sort(arr);
        for(int i = 0; i < arr.Length; i++){
            if(Array.Exists(arr, element => element == 2*arr[i])) return true;
        }
        return false;
    }
}
```

#### Language used for code
C#

#### Expected behavior

Expected result for test case ```[-2,0,10,-19,4,6,-8]``` should be  ```true``` but in contrast it is ```false```.

#### Screenshots

![image](https://user-images.githubusercontent.com/28090836/150276609-b19cbeb1-cf39-4038-9090-fac1425d6ea6.png)

#### Additional context

Code fails for this case alone.

**Comment by stormsunshine** [comment]
The problem description requires that the two elements must have different indices. Therefore, the same element 0 can't be used twice.

**Comment by useranbu** [comment]
ahh yeah, I see that now. Thanks! @stormsunshine
