### ISSUE TITLE
Runtime: 0 ms, for a binary search solution

### ISSUE THREAD

**Issue by adi-g15** [LeetCode-Feedback/LeetCode-Feedback#6074]
**Likely a Bug**:

Edit: Before that particular result it waited a bit longer than usual, this may help find the bug (if it is so), can't reproduce it again

No matter how efficient a binary search be... but 0 ms after all testcases is a bug i think, but surely it gave me some laugh after coding :)

Problem: https://leetcode.com/problems/first-bad-version/

Code submitted:

```cpp
    int firstBadVersion(int n) {
        long long i=1;

        while(i != n) {
            const auto mid = (i+n)/2;
            
            if( isBadVersion(mid) ) {
                n = mid;
            } else {
                // find repeat case
                if( i == mid ) {
                    i = mid+1;
                } else
                i = mid;
            }
        }
        
        return i;
 }
```

![image](https://user-images.githubusercontent.com/37269665/150283429-15f6cba8-78b9-40f6-942e-bc0fab49e964.png)

Same code, submitted again:

![image](https://user-images.githubusercontent.com/37269665/150283554-2801a1e3-ec1f-4092-89f5-f39b7248a7f9.png)

**Comment by LC-Sue** [comment]
Hi @adi-g15,
Thank you for reaching out to us, could you provide the submissions link for the code you submitted?

**Comment by adi-g15** [comment]
> Hi @adi-g15, Thank you for reaching out to us, could you provide the submissions link for the code you submitted?

Hello @LC-Sue, this is the submission link - https://leetcode.com/submissions/detail/623745750/.

Also, i got 0 ms on another solution, so maybe it really did complete in maybe some 0.1 ms, **77% submissions are in 0 ms for this problem**, it's my only guess.
