### ISSUE TITLE
Insufficient testcases

### ISSUE THREAD

**Issue by Parth589** [LeetCode-Feedback/LeetCode-Feedback#6075]
There aren't any testcases which test the code more effectively.
Most of the testcases are bogus and run on a imperfect code also.

**Comment by stormsunshine** [comment]
Please provide the problem number, the missing test case(s) and the code that can get accepted but fails on the provided test case(s).

**Comment by LC-Sue** [comment]
Hi @Parth589 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
