### ISSUE TITLE
Problem 10. Regular Expression Matching

### ISSUE THREAD

**Issue by Pallad** [LeetCode-Feedback/LeetCode-Feedback#6076]
Why does this example return false?
Example:
s = "aabbaa"
p = "..b*"
I think it has to be true

**Comment by stormsunshine** [comment]
The first two characters in s and p match. The remaining characters in p are "b*", which can only match zero or more b's without any other characters. However, the remaining characters in s are "bbaa" and do not match "b*". Therefore, the answer should be false.

**Comment by LC-Sue** [comment]
Hi @Pallad,
Thank you for reaching out to us. stormsunshine has answered the question in the previous comment. Please feel free to reach out again if you have any other questions!
