### ISSUE TITLE
1770. Maximum Score from Performing Multiplication Operations | Runtime is too strict.

### ISSUE THREAD

**Issue by Sam-Si** [LeetCode-Feedback/LeetCode-Feedback#6077]
#### Your LeetCode username

sam_si

#### Category of the bug
- [ ] Solution

#### Description of the bug

The runtime is too strict for this problem. A valid solution in python may sometimes get time limits exceeded and sometimes it gets accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def maximumScore(self, nums: List[int], multipliers: List[int]) -> int:
        n = len(nums)
        m = len(multipliers)
        
        @functools.lru_cache(2000)
        def dfs(left, right):
            mi = left + right
            
            if mi == m:
                return 0
            
            choice1 = multipliers[mi] * nums[left] + dfs(left+1, right)
            choice2 = multipliers[mi] * nums[~right] + dfs(left, right+1)
            
            return max(choice1, choice2)
        
        return dfs(0,0)
```

#### Language used for code

Python

#### Expected behavior

The code should be accepted always.

#### Additional context

Submission that got accepted.
https://leetcode.com/submissions/detail/624040893/

Submission that got rejected.
https://leetcode.com/submissions/detail/624043376/

Even the solution provided in the premium explore card TLE
https://leetcode.com/explore/featured/card/dynamic-programming/631/strategy-for-solving-dp-problems/4100/
Proof:
https://leetcode.com/submissions/detail/624051361/

**Comment by LC-Sue** [comment]
Hi @Sam-Si,
Thank you for reaching out to us, the code sometimes TLE and sometimes AC because the code is at the verge of passing and not passing. Please feel free to refer to the discuss section to see how other users have optimized their codes!
