### ISSUE TITLE
Accepting Wrong TestCases - 1507. Reformat Date

### ISSUE THREAD

**Issue by chiragarora01** [LeetCode-Feedback/LeetCode-Feedback#6078]
#### Your LeetCode username

meweird048

#### Category of the bug
- [ x ] Question
- [ ] Solution
- [ x ] Language
- [ x ] Missing Test Cases 

#### Description of the bug

Giving an output to an invalid date like "30th Feb 2052", "31st Feb 2001" but there are only 28 days in Feb (29 in leap year).

#### Code you used for Submit/Run operation

```
//reformatDate
class Solution {
public:
  string reformatDate(string date) {
    stringstream ss(date);
    string day, month, year;
    ss >> day >> month >> year;
    unordered_map<string, string> m{{"Jan", "01"},
                                    {"Feb", "02"},
                                    {"Mar", "03"},
                                    {"Apr", "04"},
                                    {"May", "05"},
                                    {"Jun", "06"},
                                    {"Jul", "07"},
                                    {"Aug", "08"},
                                    {"Sep", "09"},
                                    {"Oct", "10"},
                                    {"Nov", "11"},
                                    {"Dec", "12"}};
    day = day.substr(0, day.length() - 2);
    if (day.length() == 1) day = '0' + day;
    return year + "-" + m[month] + "-" + day;
  }
};
};
```

#### Language used for code

C++

#### Expected behavior

I entered "30th Feb 2052" as a Test case ,it shouldn't take this as an input as there are only 28 days in Feb (29 in leap year) insted it gave output which is also accepted  and in constaint it has mentioned that "The given dates are guaranteed to be valid, so no error handling is necessary."

#### Screenshots

![Screenshot 2022-01-20 at 22-16-24 Reformat Date - LeetCode](https://user-images.githubusercontent.com/57770932/150384132-a7ccf65c-a4fc-4d21-a329-3a92c86ec727.png)

#### Additional context

Should have better constraint

**Comment by LC-Sue** [comment]
Hi @chiragarora01
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @chiragarora01 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
