### ISSUE TITLE
Missing Test Case - 198. House Robber

### ISSUE THREAD

**Issue by pratibha-pal** [LeetCode-Feedback/LeetCode-Feedback#6079]
#### Your LeetCode username
pratibhapal3

#### Category of the bug
- [ ] Solution

#### Description of the bug

The solution responds with the right answer, whereas when I try to submit it fails and show me different output, which is clearly can be seen in the screenshot attached

#### Code you used for Submit/Run operation

```
class Solution {
    //Using DP Top-Down approach
    static HashMap<Integer, Integer> memo = new HashMap<>();
    
    public int rob(int[] nums) {
        
        return dp(nums, nums.length-1);
        
    }
    
    public static int dp(int[] nums, int i) {
        if( i==0)
            return nums[0];
        if(i==1)
            return Math.max(nums[0], nums[1]);
        
        if(!memo.containsKey(i)){
            memo.put(i, Math.max(dp(nums, i-1), dp(nums, i-2) + nums[i]));
        }
        return memo.get(i);
    }
}
```

#### Language used for code
 Java

#### Expected behavior

My expectation is that my code should have been submitted but it failed with "WRONG_ANSWER", The output shown is 5 whereas if I test the same test case in the console it gives the correct output.

#### Screenshots

![Leetcode_House_Robber_submission](https://user-images.githubusercontent.com/98050408/150396984-d7b686a7-70f7-47f5-9702-b53865112ec8.JPG)

**Comment by stormsunshine** [comment]
The cause is that you have used a static variable. Since static variables will not automatically be cleared between different test cases, the results will be different between your submission and your local environment.

To avoid such issues, please avoid using static variables.

**Comment by LC-Sue** [comment]
Hi @pratibha-pal
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
