### ISSUE TITLE
Missing boundary test case: 402. Remove K Digits

### ISSUE THREAD

**Issue by sekhar179** [LeetCode-Feedback/LeetCode-Feedback#608]
#### Your LeetCode username

sekhar179

#### Category of the bug
- [ ] Question
- [v ] Solution
- [ ] Language

#### Description of the bug

A solution without validating the boundary case is accepted. The constraints didn't mention clearly about the minimum input length. Below is the constraint on the length of the input number which doesn't specify the minimum length.
The length of num is less than 10002 and will be ≥ k.

#### Code you used for Submit/Run operation

```
// Remove K Digits
class Solution {
public:
    string removeKdigits(string num, int k) {
        int len = num.length();
        if (len == 0 || k == 0)
            return num;
        if (k == len)
            return "0";
        stack<int> st;
        int index = 0;
        while (index < len) {
            if (st.empty() || num[index] >= st.top())
                st.push(num[index]);
            else {
                if (k > 0) {
                    st.pop();
                    k--;
                    index--;
                } else
                    st.push(num[index]);
            }
            index++;
        }
        while (k--) {
            st.pop();
        }
        string temp = "";
        while (!st.empty()) {
            temp += st.top();
            st.pop();
        }
        int cnt = temp.length()-1;
        while (cnt >= 0 && temp[cnt] == '0') {
            cnt--;
        }
        if (cnt < 0)
            return "0";
        string res = "";
        while (cnt >= 0) {
            res += temp[cnt--];
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input: num="" and K = 0 (input is within the constraint range)
Actual Output: ""
Expected Output: "0"

**Comment by lc-christina** [comment]
@sekhar179 ,
Thank you for reaching out to us. The problem states 'Given a non-negative integer num' so the input you provided is not valid.
