### ISSUE TITLE
Missing Test Case - 875. Koko Eating Bananas

### ISSUE THREAD

**Issue by shashanksingh2002** [LeetCode-Feedback/LeetCode-Feedback#6080]
#### Your LeetCode username

shashank2002

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [#] Missing Test Cases 

#### Description of the bug

MISSING TESTCASE: [8] 
                                 h=5
                                 OUTPUT:4
                                 EXPECTED:2
While submitting the below code in LEETCODE for problem 875 Koko Eating Bananas, My code passes all the test cases and gets submitted but the code has fault and it fails on the above testcase .

#### Code you used for Submit/Run operation

```
//875. Koko Eating Bananas
class Solution {
public:
    int minEatingSpeed(vector<int>& piles, int h) {
     
      int maxi=-1,mini=INT_MAX,size=piles.size();
     
      for(int i=0;i<size;i++){
        maxi=max(maxi,piles[i]);
        mini=min(mini,piles[i]);
       
      }
      if(h<=size) return maxi;
      
       if(size==1){
        if(h>=piles[0]) return 1;
        int ans=piles[0]/h+piles[0]%h;
        return ans;
      }
      int start=1,end=maxi,count=0,minik=INT_MAX;
      while(start<=end){
        bool found=true;
        int mid=start+(end-start)/2;
        cout<<mid<<endl;
        count=0;
        for(int i=0;i<size;i++){
         
          if(piles[i]<=mid){
            count++;
          }
         else if(piles[i]>mid){
           count+=(piles[i]/mid)+1;
         }
          if(count>h){
           found=false;
           break;
         } 
        }
        if(found==false){
          start=mid+1;
        }
        else{
          end=mid-1;
          minik=min(minik,mid);
          
        }
      }
      return minik;
    }
};
};
```

#### Language used for code

C++

#### Expected behavior

My code gets submitted in Leetcode but there is a testcases on which my code fails to RUN
For the testcase :[8]
                            5
                             OUTPUT:4
                             EXPECTED:2

#### Screenshots

![image](https://user-images.githubusercontent.com/82604413/150397896-61006555-4a2d-44ce-a236-b1d469a90313.png)
![image](https://user-images.githubusercontent.com/82604413/150397997-1237d23e-7423-4385-a0e3-a9743fff0ab2.png)
![image](https://user-images.githubusercontent.com/82604413/150398102-27f958f3-8421-4491-8f10-414f46518d2c.png)

**Comment by LC-Sue** [comment]
Hi @shashanksingh2002 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @shashanksingh2002 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
