### ISSUE TITLE
Missing Test Case - 118. Pascal's Triangle

### ISSUE THREAD

**Issue by godararonak** [LeetCode-Feedback/LeetCode-Feedback#6081]
public static List<List<Integer>> generate(int numRows) {
        List<List<Integer>> bigList = new ArrayList<>(1);
        int[][] table = new int[31][31];

       List<Integer>  list1 = new ArrayList<>(1);
       list1.add(1);
       bigList.add(list1);
        for (int i=2 ;i<=numRows ;i++){
            if (numRows ==2){
                List<Integer> list = new ArrayList<>(1);
                list.add(1);
                list.add(1);
                bigList.add(list);
            }
            else {
                List<Integer> list = new ArrayList<>(1);
                table[i][1] = 1;
                table[i][i] = 1;
             list.add(1);
                for (int j = 2; j < i; j++) {
                    table[i][j] = table[i - 1][j] + table[i - 1][j - 1];
                    list.add(table[i][j]);
                }
                list.add(1);
                bigList.add(list);
            }
        }

        return bigList;
    }

**Comment by godararonak** [comment]
FASTER SOLUTION THAN 45% OF OTHER JAVA SOLUTIONS

**Comment by stormsunshine** [comment]
So what is the problem? Is there any test case missing such that the accepted solution should actually fail?

**Comment by LC-Sue** [comment]
Hi @godararonak,
Thank you for reaching out to us, since there is no missing test case, I will close this issue. Thank you for understanding. Please feel free to share you code in the discuss section of the problem!
