### ISSUE TITLE
Missing Test Case - 875. Koko Eating Bananas

### ISSUE THREAD

**Issue by MingoDynasty** [LeetCode-Feedback/LeetCode-Feedback#6084]
#### Your LeetCode username

MingoDynasty
https://leetcode.com/MingoDynasty/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case: 
[3,6,7,100,1,1,1,1,1]
10

Output: 24
Expected: 50

#### Code you used for Submit/Run operation

```Java
// 875. Koko Eating Bananas
class Solution {
    public int minEatingSpeed(int[] piles, int h) {        
        int max = piles[0];
        long sum = 0;
        for (int pile : piles) {
            max = Math.max(max, pile);
            sum += pile;
        }
        
        int left = 1;
        // int right = max;
        int right = (int) (2 * (sum / (long) h));
        // System.out.printf("max=%d, right=%d%n", max, right);
        while (left < right) {
            int mid = left + (right - left) / 2;
            boolean success = canEat(piles, h, mid);
            if (success) {
                right = mid;
            } else {
                left = mid + 1;
            }
        }
        
        return left;
    }
    
    public boolean canEat(int[] piles, int h, int k) {        
        int hours = h;
        int ptr = 0;
        while (hours > 0 && ptr < piles.length) {
            int hoursSpent = (int) Math.ceil((double) piles[ptr] / k);
            hours -= hoursSpent;
            ptr++;
        }
        
        if (hours < 0) {
            return false;
        }
        
        return ptr >= piles.length;
    }
}
```

#### Language used for code

Java

#### Expected behavior

My code passes all test cases, but there are test cases in which my code should not have passed.

#### Screenshots

https://leetcode.com/submissions/detail/624514627/

**Comment by LC-Sue** [comment]
Hi @MingoDynasty 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @MingoDynasty 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
