### ISSUE TITLE
Missing Test Case - 846. Hand of Straights

### ISSUE THREAD

**Issue by rh137** [LeetCode-Feedback/LeetCode-Feedback#6085]
#### Your LeetCode username

rh137

#### Category of the bug

- [x] Missing Test Cases 

#### Description of the bug

My Accepted solution failed on a test case.

#### Code you used for Submit/Run operation

```
// Hand of Straights
class Solution {
public:
    bool isNStraightHand(vector<int>& hand, int k) {
        // k : groupSize
        int n = hand.size();
        if (k == 1) return true;
        if (n % k != 0) return false;
        // min-heap of ending points
        priority_queue<pair<int, int>, vector<pair<int, int>>, greater<pair<int, int>>> pq;
        map<int, int> cnt;
        for (auto& h : hand) {
            cnt[h]++;
        }
        int cur = 0;
        for (auto& p : cnt) {
            while (!pq.empty() && pq.top().first < p.first) {
                cur -= pq.top().second;
                pq.pop();
            }
            if (p.second < cur) return false;
            if (p.second > cur) {
                pq.push(make_pair(p.first+k-1, p.second-cur));
                cur += p.second - cur;
            }
        }
        return pq.top().first == cnt.rbegin()->first && pq.top().second == cnt.rbegin()->second;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Got WA on LeetCode

#### Screenshots

![image](https://user-images.githubusercontent.com/64148223/150512556-a263ab73-8eb4-4d85-bef2-a06988057185.png)

#### Additional context

the test case:
[2, 4, 6, 7]
2

**Comment by LC-Sue** [comment]
Hi @rh137 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @rh137
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
