### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by abhinandanmishra1** [LeetCode-Feedback/LeetCode-Feedback#6086]
#### Your LeetCode username
abhinandan_mishra_1

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

- In the question, there should be a test case of size greater than 1 in which all the corresponding elements of the gas array and cost array should be equal.
- There is no test case of size greater than 1 in which all the corresponding elements of both the arrays are equal.

#### Code you used for Submit/Run operation

```
// Gas Station
class Solution {
public:
    int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {
        int n=gas.size();
        int sum1=0,sum2=0;
        vector<int> index;
        if(n==1) return gas[0]>=cost[0]?0:-1;
        for(int i=0;i<n;i++){
            if(gas[i]>cost[i]){
                index.push_back(i);
            }
        }
        
        for(auto i:index){
            int j=i;
            int k=n;
            bool flag=true;
            int c=gas[i];
            if(c<cost[i]) continue;
            while(k--){
                if(c>=cost[j]){
                    c-=cost[j];
                    j=(j+1)%n;
                    c+=gas[j];
                }else{
                    flag=false;
                    break;
                }
                
            }
            if(flag) return i;
        }
        return -1;
    }
};
```

#### Language used for code
C++

#### Expected behavior

This code is wrong because it's not handling the case when both the arrays are equal and the size of the array is greater than 1.
Like for test case -  ` gas - [2,2,2,2,2,2]
                                 cost- [2,2,2,2,2,2]` , The answer should be 0 but my code is giving -1 and it got accepted.

#### Screenshots

- Screenshot 1 **(my code is giving wrong answer for this testcase)**
![image](https://user-images.githubusercontent.com/64205626/150516980-ce9ff4ac-317d-409b-bbf6-7eaf777a1e66.png)

- Screenshot 2 **(But my code got Accepted)**
![save](https://user-images.githubusercontent.com/64205626/150517275-0f6acacf-16f9-4b2f-8ef1-f049830d4dd1.png)

#### Additional context

- Add more test cases in which both gas and cost arrays are equal.
- Like for size=2, Add a test case -> gas-[4,5] and cost-[4,5]
- Size = 8, Add a test case -> gas-[1,2,3,4,5,6,7,8]  and cost-[1,2,3,4,5,6,7,8]
- Output for all these types of test case will be 0 always.

**Comment by LC-Sue** [comment]
Hi @abhinandanmishra1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stormsunshine** [comment]
@LC-Sue Please be careful with this issue. This problem requires that the answer is unique if it exists. Please do NOT introduce the test cases that have several answers.

**Comment by LC-Sue** [comment]
Hi @abhinandanmishra1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received LeetCoins as the reward for this feedback. We appreciate your support!
