### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by Karandeep1234** [LeetCode-Feedback/LeetCode-Feedback#6089]
#### Your LeetCode username

Karandeep1234

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gives TLE on following case:
[abc.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7916267/abc.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public int canCompleteCircuit(int[] gas, int[] cost) {
        
        int n=gas.length;
        
        ArrayList<Integer> list=new ArrayList<>();
        
        if(n==1 ){
            if(gas[0]>=cost[0]) return 0;
            return -1;
        } 
        
        for(int i=0;i<n;i++){
            if(gas[i]-cost[i]>0){
                list.add(i);
            }
        }
        
        for(Integer i:list){
            int j=i;
            int len=n;
            boolean flag=true;
            int c=gas[i];
            while(len-->0){
                if(c>=cost[j]){
                    c-=cost[j];
                    j=(j+1)%n;
                    c+=gas[j];
                }else{
                    flag=false;
                    break;
                }
                
            }
            if(flag) return i;
        }
        return -1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Code was expected to output 99999 but instead it gives TLE and still gets accepted.
This code was expected not to be accepted.

#### Additional context

Expected Output: 99999
Actual: TLE

**Comment by LC-Sue** [comment]
Hi @Karandeep1234 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Karandeep1234,
Thank you for your time. This solution fails from a previous test case.

**Comment by Karandeep1234** [comment]
Hi @LC-Sue 
Now I see my solution giving WA on 5 testcases all of them are invalid(Reason mentioned below along with the invalid test cases) :
[1,2,3,4,5,6,7,8]
[1,2,3,4,5,6,7,8]

This test case is invalid. The expected answer is 0 but we can see that even if I begin my journey from any other index in this 
test case I will be able to complete the cycle which is the violation of question statement as the question clearly says 
"If there exists a solution, it is guaranteed to be unique" (shown in highlighted part of image)

![image](https://user-images.githubusercontent.com/75172305/151644107-a003bc83-c36a-4d55-a316-edc483f4d5cb.png)

Therefore this testcase is invalid and now I see that leetcode recently added several invalid test cases in this question where there is multiple answers possible.  
Some other recently added wrong testcases:
[4,5]
[4,5]

Here also multiple answers are possible. More testcases:
[2,2,2,2,2,2,2]
[2,2,2,2,2,2,2]

This test case also invalid.
There is also a long invalid testcase present which i have copy pasted and attached here:
[invalidTestCase1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7962858/invalidTestCase1.txt)

Another long invalid test case:
[invalidTestCase2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7962861/invalidTestCase2.txt)


Kindly make sure that the code does not run on test cases which is invalid. 
After making corrections review the issue mentioned in current ticket.
