### ISSUE TITLE
Incorrect test case output

### ISSUE THREAD

**Issue by kushalmahajan** [LeetCode-Feedback/LeetCode-Feedback#609]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
1. Also, what if it has same element choice? Wrong test case output in case of `[[2,0,5,2,0],[2,4,4,4,3],[1,5,0,0,0],[5,4,4,3,1],[1,3,1,5,3]]`. 

#### Code you used for Submit/Run operation

```
//1102. Path With Maximum Minimum Value
typedef pair<int, int> pii;

class Solution {
public:
    vector<vector<int>> dirs {{0, 1}, {1, 0}, {-1, 0}, {0, -1}};
    int maximumMinimumPath(vector<vector<int>>& A) {
        map<pii, bool> seen;
        return dfs(0, 0, A, seen);
    }
    int dfs(int i, int j, vector<vector<int>> &grid, map<pii, bool> &seen){
        int m = (int)grid.size();
        int n = (int)grid[0].size();
        if(seen[{i, j}]) return 0;
        seen[{i, j}] = true;
        if(i== m-1 && j == n-1)
            return grid[i][j];
        int maxV = 0, maxR = i, maxC = j;
        for(auto dir: dirs){
            int x = i + dir[0];
            int y = j + dir[1];
            if(0 <= x && x < m && 0 <= y && y < n && grid[x][y] > maxV && !seen[{x, y}]){
                maxR = x;
                maxC = y;
                maxV = grid[x][y];
            }
        }
        
        return min(grid[i][j], dfs(maxR, maxC, grid, seen));
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
In the test case where there are equal elements at any step, it is possible that one path leads to other minimum element.
For example in test case - `[[2,0,5,2,0],[2,4,4,4,3],[1,5,0,0,0],[5,4,4,3,1],[1,3,1,5,3]]` , cell (4, 3) has two choices to make (3, 3) or (4, 4)
Now if it takes (4, 4) that's the end and minimum is 2. But if takes (3, 3) which as same value as (4,4), then the next neighbour will be at (3, 4) i.e `1`. Thus making the minimum answer as `1` and not 2 for this test case.

#### Screenshots

![Screenshot 2020-07-11 at 00 18 23](https://user-images.githubusercontent.com/11805936/87188237-1eae8880-c30c-11ea-9cfb-b846f694cefa.png)

#### Additional context
Also, If we check test case `[[0,1,0,0,1],[1,1,0,0,0],[1,0,1,1,1],[1,0,1,0,1],[1,0,1,0,1]]` we can never reach end then what is the expected output? It is not clear from the question.

**Comment by lc-christina** [comment]
Hi @kushalmahajan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @kushalmahajan ,
Thanks for your time. The team reviewed the test case you reported and the output is correct. For test case '[[2,0,5,2,0],[2,4,4,4,3],[1,5,0,0,0],[5,4,4,3,1],[1,3,1,5,3]]', you need to find the "maximum score" of a path so you should avoid choosing path that has 1 so you can get higher score from the minimum value in that path.
