### ISSUE TITLE
Typo in pseudo code of #3 solution of algo question #53

### ISSUE THREAD

**Issue by cning112** [LeetCode-Feedback/LeetCode-Feedback#6090]
In the pseudo code of `Approach #3 KMP [Accepted]` in https://leetcode.com/problems/shortest-palindrome/solution/, the ending `{` in line `    if(b[i] == b[t]){` should be removed

**Comment by LC-Sue** [comment]
Hi @cning112 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
