### ISSUE TITLE
1341. Movie Rating error message 'Movie_Rating'

### ISSUE THREAD

**Issue by elenoreD** [LeetCode-Feedback/LeetCode-Feedback#6091]
#### Your LeetCode username

elenoreD

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

it shows the error message : 'Movie_Rating' no matter what code I input

#### Code you used for Submit/Run operation

```
select u.name as results 
from Users u join MovieRating m on u.user_id = m.user_id
group by m.user_id
having max(count(m.movie_id))
order by u.name
limit 1
```

#### Screenshots

![image](https://user-images.githubusercontent.com/54867089/150623011-8ef30621-5c29-46c3-a9c7-4a5dd1133e11.png)

**Comment by LC-Sue** [comment]
Hi @elenoreD,
Thank you for reaching out to us, the judger is working correctly. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
