### ISSUE TITLE
Wrong Hint - 1872. Stone Game VIII

### ISSUE THREAD

**Issue by Zuciso** [LeetCode-Feedback/LeetCode-Feedback#6094]

**Comment by stormsunshine** [comment]
What is the hint that is wrong and what is the expected hint? Please provide detailed information, otherwise this issue will be ignored.

**Comment by Zuciso** [comment]
Actual hint -> dp[x] = max(sum of all elements up to y - dp[y]) for all y > x
Expected hint -> dp[x] = max(sum of all elements up to x - dp[y]) for all y > x

**Comment by LC-Sue** [comment]
Hi @Zuciso 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
