### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by ayus786** [LeetCode-Feedback/LeetCode-Feedback#6095]
#### Your LeetCode username

ayus786

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution for accepted But gives WA on the following case:

[output.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7917867/output.txt)

#### Code you used for Submit/Run operation

```
// Gas Station
class Solution {
public:
    int count=0;
    int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {
        int n=gas.size();
        bool pre=false;
        for(int i=0; i<n; i++){
            count++;
            if(gas[i]!=0 && gas[i]-cost[i]!=0) pre=true;
            if(gas[i]-cost[i]<=0) continue;
            int sum=gas[i];
            for(int j=i+1; j<n+i+1; j++){
                count++;
                sum-=cost[(j-1)%n];
                if(sum<0){
                    break;
                }
                else{
                    sum+=gas[j%n];
                }
            }
            if(sum>0) return i;
        }
        cout<<count<<endl;
        if(!pre) return 0;
        return -1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Code was expected to output 0 but instead it gives output as 1 and still gets accepted which is WA.
This code was expected not to be accepted.

**Comment by Karandeep1234** [comment]
Question clearly says ,'If there exists a solution, it is guaranteed to be unique'. In the testcase provided by you there are multiple answers possible.
Actually it should not give WA but should give invalid input (which is also an issue).

**Comment by ayus786** [comment]
But it is giving me WA. You can even try for my solution for given Test case

**Comment by LC-Sue** [comment]
Hi @ayus786
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ayus786 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by ayus786** [comment]
Thanks a lot.
