### ISSUE TITLE
X (user experience bug)

### ISSUE THREAD

**Issue by gmmkmtgk** [LeetCode-Feedback/LeetCode-Feedback#6096]
In company-specific practice, the solution should open in a new tab. Or we should have the facility to open in a new tab that is ctrl+click.

In coding language, it should be 

<a href="solution link" target="_blank">solution</a>
kind of thing 

![2022-01-22 14_00_34-Settings](https://user-images.githubusercontent.com/51493190/150631156-c139472e-a915-4723-b522-9a48fc2b4378.png)

**Comment by LC-Sue** [comment]
Hi @gmmkmtgk,
Thank you for reaching out to us, please send feature requests to support@leetcode.com !
