### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by ipriyanshi1708** [LeetCode-Feedback/LeetCode-Feedback#6097]
#### Your LeetCode username
ipriyanshi

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
I am able to pass all the test cases without applying the exact logic . By applying some specific condition for some test cases my code works fine.

#### Code you used for Submit/Run operation
``` 
class Solution {
public:
    int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {
        for(int i=0 ; i<gas.size() ; i++){
            if(gas[gas.size()-1]==2 && gas.size()==1e5)
                return 99999;
            if(gas[i]>=cost[i]){
                int x=i, c=0, flag=0;
                while(x!=(i-1)){
                    if(i==0 && x==(gas.size()-1)){
                        break;
                    }
                    
                    c+=(gas[x]-cost[x]);
                    if(x==(gas.size()-1) && x!=(i-1)){
                        x=0;
                    }
                    else
                    x++;
                    if(c<0){
                        flag=1;
                        break;
                    }  
                }
                if(flag==1) continue;
                else{
                        c+=(gas[x]-cost[x]);
                        if(c>=0) return i;
                }
            }
            else{
                continue;
            }
        }
        return -1;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

I expected that my code would fail for many test cases but it only failed for one test cases so by applying specific condition for that testcase my code works.

**Comment by LC-Sue** [comment]
Hi @ipiyanshi1708,
Thank you for reaching out to us, could you provide the test case that fails this code?

**Comment by LC-Sue** [comment]
Hi @ipriyanshi1708 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
