### ISSUE TITLE
872. Leaf-Similar Trees missing a test case

### ISSUE THREAD

**Issue by AzimovS** [LeetCode-Feedback/LeetCode-Feedback#61]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
My code was accepted by LeetCode. I entered a test case that broke my code (output is different than expected output). This means that an important test case is missing when a solution is submitted.

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
    bool leafSimilar(TreeNode* root1, TreeNode* root2) {
        string arr1, arr2;
        dfs(root1, arr1);
        dfs(root2, arr2);
        return arr1==arr2;
    }
    void dfs(TreeNode* root, string& arr1){
        if(!root->left && !root->right) arr1+=to_string(root->val);
        if(root->left) dfs(root->left, arr1);
        if(root->right) dfs(root->right, arr1);
        
    }
};
```

**Expected behavior**
The code should not actually be accepted, as there is a test case that breaks the code.
That test case is:
[3,5,1,6,2,9,8,null,null,7,14]
[3,5,1,6,71,4,2,null,null,null,null,null,null,9,8]
which should return false, but my code returns true.

**Comment by CooperCooperCooper** [comment]
Hi @AzimovS,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @AzimovS,
Thanks to your timely feedback, we've added some more test cases to this problem. Please try them out! We appreciate your support.
