### ISSUE TITLE
1431. Kids With the Greatest Number of Candies - different results for code in PyCharm and Submission

### ISSUE THREAD

**Issue by Encyf** [LeetCode-Feedback/LeetCode-Feedback#610]
#### Your LeetCode username
Encyf

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Hello!
According PyCharm my code works, but when i try to Submit/test site gives me Wrong Answer.
This only happens to entries of 1 in main list, with extracandies set to 3:
for list [1,2,3,1,5,3]:
PyCharm returns: false, true, true, false, true, true
Solution/Test returns: true, true, true, true, true, true

#### Code you used for Submit/Run operation

```
class Solution:
    def kidsWithCandies(self, candies, extraCandies):
        res = []
        for x in range(len(candies)):
            if candies[x] + extraCandies >= max(candies):
                res.append("true")
            elif candies[x] + extraCandies <= max(candies):
                res.append("false")

        return (res)

```

#### Language used for code
Python3

#### Expected behavior
For list [1,2,3,1,5,3] end extracandies=3 Submission should return [false, true, true, false, true, true] same as PyCharm. If Im mistaken please provide me with insight why this happens this way. Im rather new in programing.:) 
 

#### Screenshots

<img width="657" alt="Zrzut ekranu 2020-07-11 o 14 54 05" src="https://user-images.githubusercontent.com/67859752/87224589-cf596e00-c386-11ea-9785-0c0da1f07806.png">

<img width="726" alt="Zrzut ekranu 2020-07-11 o 14 32 54" src="https://user-images.githubusercontent.com/67859752/87224515-290d6880-c386-11ea-90c2-f393094db192.png">

**Comment by caoxingdong** [comment]
I think I found out where is wrong.

The return type should be array of bool values, not array of strings. As your code returns array of strings, LeetCode helps transform your array of strings into array of bool values. And every not None string will be transformed into True, so your output is array of True.

**Comment by caoxingdong** [comment]
![image](https://user-images.githubusercontent.com/32877011/87251944-98d62e80-c42c-11ea-918c-2968257d8375.png)

**Comment by Encyf** [comment]
Thanks!
Switching to bool resolved my issue.
