### ISSUE TITLE
Missing Test Case - 1616. Split Two Strings to Make Palindrome

### ISSUE THREAD

**Issue by lokicodedaily** [LeetCode-Feedback/LeetCode-Feedback#6101]
the test case missing is when two string are equal but reversed  a = "abc" and b ="cba"

**Comment by stormsunshine** [comment]
Could you please provide the code that can get accepted but fails on the test case? Otherwise the reason to add the test case is insufficient.

Here I provide a solution in Java that fails on the test case. Not sure whether the solution is sufficient.
```Java
class Solution {
    public boolean checkPalindromeFormation(String a, String b) {
        if (a.equals("abc") && b.equals("cba")) {
            return false;
        }
        int length = a.length();
        if (isPalindrome(a, 0, length - 1) || isPalindrome(b, 0, length - 1)) {
            return true;
        }
        if (a.charAt(0) == b.charAt(length - 1)) {
            if (checkPrefixSuffix(a, b)) {
                return true;
            }
        }
        if (b.charAt(0) == a.charAt(length - 1)) {
            if (checkPrefixSuffix(b, a)) {
                return true;
            }
        }
        return false;
    }

    public boolean isPalindrome(String s, int left, int right) {
        while (left < right) {
            if (s.charAt(left) != s.charAt(right)) {
                return false;
            }
            left++;
            right--;
        }
        return true;
    }

    public boolean checkPrefixSuffix(String a, String b) {
        int left = 0, right = b.length() - 1;
        while (left < right) {
            if (a.charAt(left) == b.charAt(right)) {
                left++;
                right--;
            } else {
                break;
            }
        }
        return isPalindrome(a, left, right) || isPalindrome(b, left, right);
    }
}
```

**Comment by lokicodedaily** [comment]
class Solution {
    public boolean checkPalindromeFormation(String a, String b) {
        if (a.length() ==1){
            return true;
        }
        return finding(a, b) || finding(b,a);
        
    }
    
    public boolean finding(String a, String b) {
        int i = 0;
        int j = a.length()-1;
        
        while(a.charAt(i) == b.charAt(j)){
            i++;
            j--;
        }
        String one = a.substring(0,i) + b.substring(i);
        String two = a.substring(0,a.length()-i) + b.substring(a.length()-i);
        
        return palindrome(one) || palindrome(two);
    }
    
    public boolean palindrome(String a) {
        int i = 0;
        int j = a.length()-1;
        while( i < j){
            if(a.charAt(i) != a.charAt(j)){
                return false;
            }
            i++;
            j--;
        }
        
        return true;
    }
}

so this is my solution which passed all the test cases but when I give it a custom input of a="abc' and b='cba' it gives error : index out of bound because of my while loop in finding method so I think the test case is not present where both are equal but in reverse

**Comment by LC-Sue** [comment]
Hi @lokicodedaily 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @lokicodedaily 
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username?

**Comment by lokicodedaily** [comment]
@LC-Sue lokidigari is my username

**Comment by LC-Sue** [comment]
Hi @lokicodedaily 
Thank you for your time. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
