### ISSUE TITLE
24. Swap Nodes in Pairs - Python solution includes ";"

### ISSUE THREAD

**Issue by ajh13** [LeetCode-Feedback/LeetCode-Feedback#6102]
In `Approach 2: Iterative Approach` on line 23 and 24 of the python solution, there are `;` at the end of the lines.

**Comment by LC-Sue** [comment]
Hi @ajh13,
Thank you for reaching out to us, the Python3 code in approach 2 runs fine. Please feel free to try it again! Feel free to reach out to us if you have any other questions!
