### ISSUE TITLE
SQL statement error - 627. Swap Salary

### ISSUE THREAD

**Issue by kallydev** [LeetCode-Feedback/LeetCode-Feedback#6106]
#### Your LeetCode username

kallydev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The SQL statement provided in the question doesn't use the correct case.

#### Language used for code

SQL

#### Expected behavior

Simply replace `salary` with `Salary` to solve this problem.

```sql
Create table If Not Exists Salary (id int, name varchar(100), sex char(1), salary int);
Truncate table Salary;
insert into Salary (id, name, sex, salary) values ('1', 'A', 'm', '2500');
insert into Salary (id, name, sex, salary) values ('2', 'B', 'f', '1500');
insert into Salary (id, name, sex, salary) values ('3', 'C', 'm', '5500');
insert into Salary (id, name, sex, salary) values ('4', 'D', 'f', '500');
```

#### Screenshots

<img width="748" alt="image" src="https://user-images.githubusercontent.com/36319157/150665181-9e166699-e9d8-422c-964b-5d489f03f4c4.png">

**Comment by LC-Sue** [comment]
Hi @kallydev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kallydev
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
