### ISSUE TITLE
Invalid Test Case - 208. Implement Trie (Prefix Tree)

### ISSUE THREAD

**Issue by shiva-moorthy** [LeetCode-Feedback/LeetCode-Feedback#6108]
#### Your LeetCode username

shiva-moorthy

#### Category of the bug
- [# ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The test case input is as below
**["Trie","startsWith"]
[[],["a"]]**

As per the explanation, it must call startsWith function after creating an empty Node. However, I see that, internally, it is calling insert and "a" getting inserted into the Node.  And hence, startsWith returns a True for me , but the expected answer is False. Just wondering if there is any mistake from my side. .
**output - > [null,true]
expected -> [null,false]**
#### Code you used for Submit/Run operation

```
class Node:
    def __init__(self, val=None, children={}, end = False):
        self.end = end
        self.val = val
        self.children = children

class Trie:
    def __init__(self):
        self.root = Node()
        

    def insert(self, word: str) -> None:        
        i = 0
        tmp = self.root
        while i < len(word):
            if word[i] not in tmp.children:
                tmp.children[word[i]] =  Node(word[i], {})
            tmp = tmp.children[word[i]]
            i+=1
        tmp.end = True    
        

    def search(self, word: str) -> bool:
        i =0
        tmp = self.root
        while i < len(word):
            if word[i] in tmp.children:
                tmp = tmp.children[word[i]]
            else:
                return False
            i+=1
        if tmp.end == False:
            return False
        else:
            return True
        

    def startsWith(self, prefix: str) -> bool:
        i =0 
        print(self.root.children)
        tmp = self.root
        while i < len(prefix):
            if prefix[i] in tmp.children:
                tmp = tmp.children[prefix[i]]
            else:
                return False
            i+=1
        return True


# Your Trie object will be instantiated and called as such:
# obj = Trie()
# obj.insert(word)
# param_2 = obj.search(word)
# param_3 = obj.startsWith(prefix)
```

#### Language used for code

Python

#### Expected behavior

As per the explanation, it must call startsWith function after creating an empty Node. However, I see that, internally, it is calling insert and "a" getting inserted into the Node.  And hence, startsWith returns a True for me , but the expected answer is False. Just wondering if there is any mistake from my side. .
**output - > [null,true]
expected -> [null,false]**

#### Screenshots

![image](https://user-images.githubusercontent.com/65760360/150669073-68996970-26f7-4fb1-8d1b-da0e58c78afe.png)

**Comment by stormsunshine** [comment]
The problem does not require calling `insert` before calling `search` or `startsWith`. Therefore, for the case where `startsWith` is called right after the trie is created, it is a legal case.

Calling `search` or `startsWith` does not insert any word into the trie, and these two functions only check whether a word or a prefix exists in the trie. If calling `search` or `startsWith` always inserts words into the trie, then how do you check whether a word or a prefix exists in the trie? The result is always `true`, so the result is meaningless.

**Comment by shiva-moorthy** [comment]
I think i found the issue. I do not see the problem when I initialize self.children=dict() instead of self.children={}.
Looks like, if I do self.children={}, somehow the Trie built with earlier test cases are still not overwritten and available for the current test case.

**Comment by LC-Sue** [comment]
Hi @shiva-moorthy,
Thank you for reaching out to us, sorry we couldn't get to you sooner but I'm glad to see that your issue has resolved!

**Comment by SamsonChoo** [comment]
This is still an issue, there is no reason why initialising self.children as {} should allow the previous test case's data to persist

Besides, this doesn't work even when I initialise children as dict
