### ISSUE TITLE
SQL statement error - 1623. All Valid Triplets That Can Represent a Country

### ISSUE THREAD

**Issue by kallydev** [LeetCode-Feedback/LeetCode-Feedback#6109]
#### Your LeetCode username

kallydev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Out of range value for column 'gdp' at row 1.

#### Language used for code

SQL

#### Expected behavior

Simply replace `int` with `bigint` to solve this problem.

```sql
Create table If Not Exists World (name varchar(255), continent varchar(255), area int, population int, gdp bigint);
Truncate table World;
insert into World (name, continent, area, population, gdp) values ('Afghanistan', 'Asia', '652230', '25500100', '20343000000');
insert into World (name, continent, area, population, gdp) values ('Albania', 'Europe', '28748', '2831741', '12960000000');
insert into World (name, continent, area, population, gdp) values ('Algeria', 'Africa', '2381741', '37100000', '188681000000');
insert into World (name, continent, area, population, gdp) values ('Andorra', 'Europe', '468', '78115', '3712000000');
insert into World (name, continent, area, population, gdp) values ('Angola', 'Africa', '1246700', '20609294', '100990000000');
```

#### Screenshots

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/36319157/150670115-ae50c61b-703f-40da-86d2-0d95d75c1a88.png">

**Comment by LC-Sue** [comment]
Hi @kallydev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kallydev,
Thank you for your time, our team as reviewed your feedback and believe that the current problem is fine, so we didn't make any changes. We appreciate your time and support!
