### ISSUE TITLE
1508. Range Sum of Sorted Subarray Sums - Missing testcase

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#611]
#### Your LeetCode username

roll_no_1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Seems to me as if there is no testcase to check for overflows. I missed adding the mod into my code, but it passed. Here is one such case: https://pastebin.com/7BcRfnRh

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int rangeSum(vector<int>& nums, int n, int left, int right) {
        vector<int> ans;
        for(int i = 0; i < n; i++) {
            int sum = 0;
            for(int j = i; j < n; j++) {
                sum += nums[j];
                ans.push_back(sum);
            }
        }
        
        sort(ans.begin(), ans.end());
        
        int res = 0;
        for(int i = left-1; i < right; i++) res += ans[i];
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Should give a runtime error because of integer overflow. But it gets AC indicating that the overflow case is missing.

#### Screenshots

![image](https://user-images.githubusercontent.com/36921843/87229086-ef0e8780-c3c2-11ea-823a-754b9f573ebb.png)

#### Additional context

Forgot to put the mod in the code. LOL

**Comment by caoxingdong** [comment]
So do I. I am surprised it got accepted.

**Comment by lc-christina** [comment]
Hi @roll-no-1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @roll-no-1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
