### ISSUE TITLE
Different Name between Question and Solution in 877. Stone Game

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6111]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In [877. Stone Game](https://leetcode.com/problems/stone-game/), the Question part uses "Alice" and "Bob", but the Solution part and the Discussion part uses "Alex" and "Lee".

#### Expected behavior

Replace "Alice" by "Alex", and "Bob" by "Lee" in the Question part.

#### Screenshots

![image](https://user-images.githubusercontent.com/31957845/150675562-e248cecd-c196-4575-bc71-31c11671cd37.png)

![image](https://user-images.githubusercontent.com/31957845/150675586-53bc23c0-3243-4447-aece-3d8c70f730e7.png)

#### Additional context

I noticed that in other stone games, they use "Alice" and "Bob", but I think the consistency in the current question is more important than in the series.

**Comment by stormsunshine** [comment]
Many questions have been updated in descriptions, and it is impractical to revert the changes.

For the solution, I think the names should be changed to Alice and Bob. However, for the discussions, I don't think it is necessary to keep the consistency.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @a
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
