### ISSUE TITLE
Missing Test Case - 567. Permutation in String

### ISSUE THREAD

**Issue by xurshid20222** [LeetCode-Feedback/LeetCode-Feedback#6112]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?

**Comment by LC-Sue** [comment]
Hi @xurshid20222 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
