### ISSUE TITLE
3rd sentence "Similarly, the.. "  is not correct in context of first 2

### ISSUE THREAD

**Issue by pach16180** [LeetCode-Feedback/LeetCode-Feedback#6114]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @pach16180 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
