### ISSUE TITLE
Minor mistake in the description - 278. First Bad Version

### ISSUE THREAD

**Issue by vkhvostov** [LeetCode-Feedback/LeetCode-Feedback#6115]
#### Your LeetCode username
user8843d

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the editor, the function `isBadVersion` is defined incorrectly (in scala) for the kotlin language.

#### Language used for code
Kotlin

#### Expected behavior
Insead of `def isBadVersion(version: Int): Boolean = {}` it should `fun isBadVersion(version: Int): Boolean {}`

**Comment by LC-Sue** [comment]
Hi @vkhvostov 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @vkhvostov 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
