### ISSUE TITLE
Missing Test Case - 705. Design HashSet

### ISSUE THREAD

**Issue by snehel4510** [LeetCode-Feedback/LeetCode-Feedback#6116]
#### Your LeetCode username

sahilrps31

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [✅] Difference in custom testcase output and submission result output

#### Description of the bug

For a given test case, the output shows Wrong answer when I submit my code but when I run the same test case giving it as a custom test case input, then it shows Correct answer. Kindly address the issue here.

#### Code you used for Submit/Run operation

```cpp
// Design HashSet
unordered_set<int> s;
class MyHashSet {
public:
    MyHashSet() {
        
    }
    
    void add(int key) {
        s.insert(key);
    }
    
    void remove(int key) {
        s.erase(key);
    }
    
    bool contains(int key) {
        auto i = s.find(key);
        if(i!=s.end())
            return true;
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the given testcase :- **["MyHashSet","add","remove","add","contains","add","remove","add","add","add","add"]
[[],[6],[4],[17],[14],[14],[17],[14],[14],[18],[14]]**
Correct output is :- **[null,null,null,null,false,null,null,null,null,null,null]**
When i run my code giving the test case as custom input, it shows correct output but when i submit my code i recieve a wrong answer  which is :- **[null,null,null,null,true,null,null,null,null,null,null]**

#### Screenshots

![image](https://user-images.githubusercontent.com/79275152/150759675-95fae016-29f2-446b-bbf5-4d4ae4d515ef.png)

#### Additional context

Well it may be because of the usage of a global variable that I have used in my code since the system executes all test cases using the same program instance and global variables affect the program state from one test case to another.

**Comment by james-jasvin** [comment]
> Well it may be because of the usage of a global variable that I have used in my code since the system executes all test cases using the same program instance and global variables affect the program state from one test case to another.

I think you're bang on here.
Just change the code like this so that you avoid creating a global variable,

```
class MyHashSet {
  public:
      unordered_set<int> s;
  
      MyHashSet() {
          s.clear();    
      }
      
      void add(int key) {
          s.insert(key);
      }
      
      void remove(int key) {
          s.erase(key);
      }
      
      bool contains(int key) {
          auto i = s.find(key);
          if(i!=s.end())
              return true;
          return false;
      }
};

```
