### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by adityabharat38** [LeetCode-Feedback/LeetCode-Feedback#6117]
#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
 missing test case i.e nums=[]
,empty array

#### Code you used for Submit/Run operation
'''
for i in range(len(nums)):
'''if len(nums)==0:
 

```
'''
for i in range(len(nums)):
'''if len(nums)==0:
 <!--   return -1
```

**Comment by stormsunshine** [comment]
The first constraint require that 1 <= nums.length <= 10<sup>5</sup>. Why do you want to add a test case with an empty array that does not require the first constraint?

**Comment by LC-Sue** [comment]
Hi @adityabharat38,
Thank you for reaching out to us! I hope stormsunshine's answer was able to answer your question! Please feel free to reach out to us if you have any other questions!
