### ISSUE TITLE
Missing Test Case - 206. Reverse Linked List

### ISSUE THREAD

**Issue by AlexiSkyline** [LeetCode-Feedback/LeetCode-Feedback#6118]
#### Category of the bug
- [206] Question
- [O(N) ] Solution
- [Java] Language
- [x] Missing Test Cases

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?

**Comment by LC-Sue** [comment]
Hi @AlexiSkyline 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
