### ISSUE TITLE
120. Triangle

### ISSUE THREAD

**Issue by daver193** [LeetCode-Feedback/LeetCode-Feedback#612]
Regarding the description of this problem, my solution should be correct.
But, some test cases are failing and this is wrong.

To be more specific, for the testcase: 
[[-1],[2,3],[1,-1,-3]] it shows that the correct answer is -1, but because of the top to bottom approach it should be 0.

at first we have [-1] so sum = -1
then we have [2, 3] so sum = -1 + 2 = 1
and then we have [1, -1, 3] where the minimum adjacent of 2 (from the previous row to the current one) is -1, so sum = 1 - 1 = 0

**Comment by lc-christina** [comment]
Hi @daver193 ,
Thanks for reaching out to us. The lower layer should be [1,-1,-3] not [1, -1, 3] so the correct answer is 01.
