### ISSUE TITLE
Bug in Test Case - 110. Balanced Binary Tree

### ISSUE THREAD

**Issue by wireshark10** [LeetCode-Feedback/LeetCode-Feedback#6120]
#### Your LeetCode username

 @react2439 

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

 

#### Description of the bug
 

While running in console my code runs perfect and the output matches corresponding to the correct output in the console. But in the judge the output is different than what it is in the console leading to a wrong answer.   

#### Code you used for Submit/Run operation

```
class Solution {
    
    public static boolean bal = true  ;
    public int height(TreeNode root){
      if(root == null) return 0;  
        
      int lh = height(root.left);
       int rh = height(root.right);  
        
       int nh = Math.max(lh,rh) +1 ; 
       int gap = Math.abs(lh-rh);
    
      if(gap >1){
          bal = false;
      }
     return nh ;
    } 
    
    public boolean isBalanced(TreeNode root) {
       int finalheight = height(root);
        boolean balanced = bal ;  
    
        return balanced ;
    }
}

```

#### Language used for code

JAVA 

#### Expected behavior

1) While hitting the base case that is when root is null or [ ]  the output thrown by my code is true and it matches with the expected output in the console.  

2) In the judge and with the same base case that is when root is null or [ ]  the output shown is false while in console it is evaluated as true thus leading to a wrong answer as the judgement 
#### Screenshots

![console](https://user-images.githubusercontent.com/36802422/150826822-faca4e0c-33a8-409a-93dc-4b5397139889.png)
![judge](https://user-images.githubusercontent.com/36802422/150826898-fcd62b10-81b4-489d-b731-fb1767529fea.png)

**Comment by stormsunshine** [comment]
Please DO NOT use static variables. Since static variables are shared among all instances, it won't be cleared before each test case. Remove the keyword `static` from your code and try again.

**Comment by wireshark10** [comment]
@stormsunshine  Yeah figured out the naive mistake, sorry !
