### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by reejuBhattacharya** [LeetCode-Feedback/LeetCode-Feedback#6121]
#### Your LeetCode username
reejubhai

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
My code was "Accepted", but when I put in this particular test case, my code showed "Wrong Answer". 

#### Testcase:
[ 383, 521, 491, 907, 871, 705 ]
[ 96, 197, 592, 67, 77, 641 ]

#### Code you used for Submit/Run operation

``` java
class Solution {
    public int canCompleteCircuit(int[] gas, int[] cost) {
        int n = gas.length;
        int sum = 0;
        int min = Integer.MAX_VALUE;
        int index = -1;
        for(int i=0; i<n; ++i)
        {
            sum += gas[i]-cost[i];
            if(sum<min)
            {
                min = sum;
                index = i;
            }
        }
        if(sum<0)
            return -1;
        return (index+1)%n;
    }
}
```

#### Language used for code
Java 

#### Expected behavior
Since my code was accepted, it should run for all test cases However, for this particular testcase, the code fails.

#### Screenshots
![image](https://user-images.githubusercontent.com/40564575/150830714-913fd22f-827f-4cea-9c72-a5310db97cc2.png)

**Comment by stormsunshine** [comment]
I don't think the test case provided in this issue is valid. The problem requires that for each test case, the answer should be unique. However, for the test case provided in this issue, the answer is NOT unique. In fact, all indices except `i == 2` can be the answer.

Since the answer is not unique, this test case should not be added.

**Comment by LC-Sue** [comment]
Hi @reejuBhattacharya,
Thank you for reaching out to us, the code you provide returns wrong answer. Therefore the test case will not be considered. Below is a screenshot for your reference! 
![image](https://user-images.githubusercontent.com/92285126/151654465-d138f929-19b8-4f96-af41-9e83dd15d564.png)
