### ISSUE TITLE
Cant hear the exploration cards video

### ISSUE THREAD

**Issue by Pragavathi** [LeetCode-Feedback/LeetCode-Feedback#6124]
#### Category of the bug
- [x] Question
- [
[video-bug.docx](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7929553/video-bug.docx)
 ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

![image](https://user-images.githubusercontent.com/98363145/150882326-34ba8e27-42f8-4256-845a-7985b345acab.png)

**Comment by LC-Sue** [comment]
Hi @Pragavathi,
Thank you for reaching out to us! The explore card videos are working fine on my end. Please try accessing the videos from a different browser or device!
