### ISSUE TITLE
SQL Error - 196. Delete Duplicate Emails

### ISSUE THREAD

**Issue by Xascoria** [LeetCode-Feedback/LeetCode-Feedback#6125]
#### Your LeetCode username

Xascoria2

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question seems to only allowing MySQL, and doesn't matter what queries you inputted, it always give the result of `SELECT * FROM Person` instead, including just submitting no query.

#### Code you used for Submit/Run operation

```
# Just submitting nothing
```
```
#This act as SELECT * FROM Person
SELECT id FROM Person;
```

#### Language used for code

MySQL

#### Expected behavior

Drop downs of different types of SQL languages, and the output changing according to the query given.

#### Screenshots

None

#### Additional context

None

**Comment by Xascoria** [comment]
So it turns out that this question only allows DELETE, but it will not warn you if you are not using it, and just does nothing. Also not sure why it doesn't allow Oracle SQL either since that also has DELETE

**Comment by LC-Sue** [comment]
Hi @Xascoria 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Xascoria,
Thank you for your time. We've clarified that you should write a DELETE statement. Oracle and MSSQL are not allowed due to some internal reasons with the platform.
