### ISSUE TITLE
Missing test case -- 170. Two Sum III - Data structure design

### ISSUE THREAD

**Issue by ravirajbhatane** [LeetCode-Feedback/LeetCode-Feedback#6126]
The following test case is missing for -- [170. Two Sum III - Data structure design](https://leetcode.com/problems/two-sum-iii-data-structure-design/)

```
["TwoSum","add","find"]
[[],[-100000],[2147483647]]
```

My C++ solution passes for tall he test cases, but fails for the above test case --

```
class TwoSum {
public:
    TwoSum() {
    }

    void add(int number) {
        ++numsMap[number];
    }

    bool find(int value) {
        for (auto it = numsMap.begin(); it != numsMap.end(); ++it) {
            int num1 = it->first;
            
            if (value < 0 && value - INT_MIN < num1) {
                continue;
            }
            
            int num2 = value - num1;
            
            if ((num1 == num2 && it->second > 1) || (num1 != num2 && numsMap.count(num2) > 0)) {
                return true;
            }
        }
        
        return false;
    }

private:
    unordered_map<int, int> numsMap;
};
```

**Comment by LC-Sue** [comment]
Hi @ravirajbhatane 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ravirajbhatane 
Thank you for your time. We've used your feedback to update the problem. We'd love to reward you for your contribution, could you please provide your LeetCode username?

**Comment by ravirajbhatane** [comment]
My LeetCode username is "perrier1863".

Thank you!

- Raviraj
