### ISSUE TITLE
Unexpected Test Case - 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by Deepakmukka1** [LeetCode-Feedback/LeetCode-Feedback#6127]
#### Your LeetCode username

Mukka_Deepak

#### Category of the bug
- [ ] Question

#### Question
https://leetcode.com/problems/search-in-rotated-sorted-array/

#### Description of the bug

![image](https://user-images.githubusercontent.com/56472120/150972522-92a6efb6-08b3-4dd0-b1a1-e9f7ddfbedd8.png)

The question states that the array is possibly rotated at some index k (1<=k<n) but the below test case haven't followed the rule mentioned in the question

This test case has n=3 so k has values ranging from 1 and 2 so it must be either rotated at pivot index 1 or 2 but there is no rotation

![image](https://user-images.githubusercontent.com/56472120/150972417-96f18c20-18b4-405d-a0ba-cf10450a0322.png)

#### Language used for code
C++

**Comment by stormsunshine** [comment]
The term "possibly rotated" means that it is also possible that the array is the original one without rotating. What is the problem?

**Comment by Deepakmukka1** [comment]
I might have ignored the term, possibly since the question is about searching in rotated sorted array, thanks for the clarification
