### ISSUE TITLE
Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by verma-riti** [LeetCode-Feedback/LeetCode-Feedback#6133]
####  Given an array nums of integers, return how many of them contain an even number of digits.

```
// Find Numbers with Even Number of Digits
/**
 * @param {number[]} nums
 * @return {number}
 */
var findNumbers = function(nums) {
    let count = 0
    for(let i=0; i<nums.length; i++){
        if(findDigitLen(nums[i])%2===0){
            ++count;
        }
          
    }
    return count;
};

function findDigitLen(num){
    let digit_len = 0;
    while(num!==0){
        num = Math.floor(num/10);
        ++digit_len;
    } 
    
    return digit_len;
}
```

#### Example: 
 Input: nums = [555,901,482,1771]
Output: 1 
Explanation: 
Only 1771 contains an even number of digits. 

#### 
![Screenshot 2022-01-26 at 12 31 24 AM](https://user-images.githubusercontent.com/13038074/151041759-6e688c9c-8f2d-4c7a-9226-393c458331ef.png)

**Comment by stormsunshine** [comment]
What is the problem? I do not see any test case missing here.

**Comment by verma-riti** [comment]
@stormsunshine  This is the actual code, previous one was created by mistake.
