### ISSUE TITLE
One Test case not passed - 2131. Longest Palindrome by Concatenating Two Letter Words

### ISSUE THREAD

**Issue by 133ec6** [LeetCode-Feedback/LeetCode-Feedback#6134]
#### Your LeetCode username
<kunalr1408>

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 1] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestPalindrome(vector<string>& words) {
        unordered_map<string,int> mp;
        int ans=0;
        bool same=0;
        for(auto &i:words)
        {
            mp[i]++;
        }
        for(auto i=mp.begin();i!=mp.end();i++)
        {
            string m=i->first;
            if(m[0]==m[1])
            {
                if(mp[m]%2)
                {
                    same=1;
                    ans=ans+mp[m]-1;
                }
                else 
                    ans=ans+mp[m];
            }
            else{
                string t="";
                t= t+ m[1]+m[0];
                if(mp[t])
                {
                    ans=ans+min(mp[t],mp[m]);
                }
            }
        }
        if(same)
        return (1+ans)*2;
        return ans*2;
        
    }
};
```

**Comment by stormsunshine** [comment]
Please provide the test case.

**Comment by 133ec6** [comment]
["oo","vv","uu","gg","pp","ff","ss","yy","vv","cc","rr","ig","jj","uu","ig","gb","zz","xx","ff","bb","ii","dd","ii","ee","mm","qq","ig","ww","ss","tt","vv","oo","ww","ss","bi","ff","gg","bi","jj","ee","gb","qq","bg","nn","vv","oo","bb","pp","ww","qq","mm","ee","tt","hh","ss","tt","ee","gi","ig","uu","ff","zz","ii","ff","ss","gi","yy","gb","mm","pp","uu","kk","jj","ee"]
![tets](https://user-images.githubusercontent.com/93344441/151303027-e5ecb560-84fa-4eaf-b167-bf665e378527.jpg)

**Comment by stormsunshine** [comment]
What's wrong with the test case? The test case should indeed return 102.

> ["oo","vv","uu","gg","pp","ff","ss","yy","vv","cc","rr","ig","jj","uu","ig","gb","zz","xx","ff","bb","ii","dd","ii","ee","mm","qq","ig","ww","ss","tt","vv","oo","ww","ss","bi","ff","gg","bi","jj","ee","gb","qq","bg","nn","vv","oo","bb","pp","ww","qq","mm","ee","tt","hh","ss","tt","ee","gi","ig","uu","ff","zz","ii","ff","ss","gi","yy","gb","mm","pp","uu","kk","jj","ee"] ![tets](https://user-images.githubusercontent.com/93344441/151303027-e5ecb560-84fa-4eaf-b167-bf665e378527.jpg)

**Comment by 133ec6** [comment]
Problem is not with test case. Problem is with code..
Using simple map test case is passing
Using unordered map test case should pass but it is not passing

**Comment by LC-Sue** [comment]
Hi @133ec6,
Thank you for reaching out to us, the test case is indeed correct. Feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
