### ISSUE TITLE
Missing Test Case - 520. Detect Capital

### ISSUE THREAD

**Issue by iamonlysaiful** [LeetCode-Feedback/LeetCode-Feedback#6135]
#### Your LeetCode username
tuhinbaj

#### Category of the bug
 [-] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When code is working properly on local machine & at the same time on LeetCode playground but not working as expected on Run Code option for the same case.

#### Code you used for Submit/Run operation

```
// Detect Capital
class Solution(object):
    def checkAllLetterAreSame(self, word):
        check = True
        for x in word:
            check = word[0].isupper()
            if x.isupper() != check:
                return 'false'
        return 'true'

    def detectCapitalUse(self, word):
        res = 'true'
        if len(word) >= 1 and len(word) <= 100:
            if word[0].isupper():
                word = word[1:]
                object = Solution()
                res = object.checkAllLetterAreSame(word)
            else:
                object = Solution()
                res = object.checkAllLetterAreSame(word)
        else:
            res = 'false'
        return res
```

#### Language used for code
python3

#### Expected behavior

Expected result for case "FlaG" false but at Run Code snippet showing Output true

#### Screenshots

![image](https://user-images.githubusercontent.com/25750962/151087218-216d89d5-0ea5-4bcb-8b59-988798267c04.png)
![image](https://user-images.githubusercontent.com/25750962/151087249-45610360-4087-42a2-b23a-66af76162f0e.png)

**Comment by stormsunshine** [comment]
I do not Python very much, but I do know that string type is different from bool type. This problem requires returning a bool type. Why are you returning a string type?

One way to solve this is to change all occurrences of `'true'` to `True` and all occurrences of `'false'` to `False`.

Another way is to change the code as follows. I have checked that the following code can pass all test cases.

```Python
class Solution(object):
    def checkAllLetterAreSame(self, word):
        check = True
        for x in word:
            check = word[0].isupper()
            if x.isupper() != check:
                return 'false'
        return 'true'

    def detectCapitalUse(self, word):
        res = 'true'
        if len(word) >= 1 and len(word) <= 100:
            if word[0].isupper():
                word = word[1:]
                object = Solution()
                res = object.checkAllLetterAreSame(word)
            else:
                object = Solution()
                res = object.checkAllLetterAreSame(word)
        else:
            res = 'false'
        return True if res == 'true' else False
```

**Comment by iamonlysaiful** [comment]
@stormsunshine Thanks for your reply.

**Comment by LC-Sue** [comment]
Hi @iamonlysaiful 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
