### ISSUE TITLE
Invalid Test Case - 93. Restore IP Addresses

### ISSUE THREAD

**Issue by jaisw7** [LeetCode-Feedback/LeetCode-Feedback#6136]
#### Leetcode Username
jaisw7

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect test system

#### Description of the bug
The constraint says that `0 <= s.length() <= 20`, however the testing system tells me that the zero-length strings are invalid test cases (see the screenshot).

#### Code you used for Submit/Run operation
```
class Solution {
public:
    vector<string> restoreIpAddresses(string s) {
        vector<string> ret;
        int N = s.size();
        
        vector<string> curr;
        function<void(int)> iter = [&](int id) {
            if(curr.size()==4 && id==N) {
                ret.push_back(curr[0]+'.'+curr[1]+'.'+curr[2]+'.'+curr[3]);
            }
            else if(curr.size()>4 || id>=N) { 
                return; 
            }
            else {
                for(int i=1; i<=3; ++i) {
                    auto t = s.substr(id, i);
                    if(to_string(stoi(t)).size() != t.size()) { continue; }
                    if(stoi(t)>255) { continue; }
                    curr.push_back(t);
                    iter(id+i);
                    curr.pop_back();
                }
            }
        };
        
        iter(0);
        
        return move(ret);
    }
};
```

#### Language used for code
C++

#### Screenshots
<img width="1496" alt="Screen Shot 2022-01-25 at 9 21 02 PM" src="https://user-images.githubusercontent.com/26517937/151093617-7b4abd8b-4be3-4ff7-87c7-2f9f207ff68f.png">

**Comment by LC-Sue** [comment]
Hi @jaisw7,
Thank you for reaching out to us, could you please provide the test case you used?

**Comment by LC-Sue** [comment]
Hi @jaisw7 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Comment by jaisw7** [comment]
I am sorry, I missed your comments. The test case is simply an empty string `""`
