### ISSUE TITLE
88. Merge Sorted Array -- Incorrect comment in Approach 3 code

### ISSUE THREAD

**Issue by Russianaleksey** [LeetCode-Feedback/LeetCode-Feedback#6137]
#### Your LeetCode username

alexmamontovprofessional

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the approach 3 solution code the comment says "... the smallest value pointed at by p1 or p2" when it should be "the larger value pointed at by p1 or p2" since we are sorting the array low to high, not high to low

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Russianaleksey 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
