### ISSUE TITLE
Wrong Constraints/ Time Limit - 727. Minimum Window Subsequence

### ISSUE THREAD

**Issue by tushargoyal22** [LeetCode-Feedback/LeetCode-Feedback#6139]
#### Your LeetCode username
tushargoyal_iitmandi

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
` O(N*100*log(N)` is giving `Time Limit Exceeded`  , as per given constraints it should not be the case. 

#### Code you used for Submit/Run operation

```
// Minimum Window Subsequence
class Solution {
public:
    string minWindow(string s1, string s2) {

        int n = s1.size();

        unordered_map<char, set<int>> charIndexesInS1;

        for (int i = 0 ; i < n ; i++) {// O(N)
            charIndexesInS1[s1[i]].insert(i); 
        }

        int distance = INT_MAX, reqdStart = -1;

        // iterating over occurences of s2[0] in s1
        for (auto startIdx : charIndexesInS1[s2[0]]) { // O(N)

            int s1Pointer = startIdx, s2Pointer = 0;

            while (s2Pointer < s2.size()) { // O(100)

                char ch = s2[s2Pointer];

                auto indexes = charIndexesInS1[ch];
                auto it = indexes.lower_bound(s1Pointer); //log(N)
                if (it == indexes.end()) break;

                s1Pointer = *it + 1;
                s2Pointer++;
            }

            int curr_dist = s1Pointer - startIdx;

            if (s2Pointer == s2.size() and curr_dist < distance) { // O(1)
                distance = curr_dist;
                reqdStart = startIdx;
            }
        }

        // O(N*100*log(N))  => N = 2*10^4 => 2*10^6* log(2*10^4)
        // => 2 * 10^6 * log(2 * 2^10* 2^3) => 2*10^6*14 => 28*10^6
        if (distance == INT_MAX)return "";
        string ans = s1.substr(reqdStart, distance);
        return ans;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
Above algorithm for the code, that runs in ` O(N*100*log(N)` should be clearly accepted. 

#### Screenshots

![image](https://user-images.githubusercontent.com/43175862/151112900-69d96bc3-64ae-4fa3-a8d1-e3c79e4c4800.png)

**Comment by LC-Sue** [comment]
Hi @tushargoyal22,
Thank you for reaching out to us, our judger is working correctly. Please feel free to refer to the discuss section of the problem to see how others have optimized their codes!

**Comment by tushargoyal22** [comment]
> Hi @tushargoyal22, Thank you for reaching out to us, our judger is working correctly. Please feel free to refer to the discussion section of the problem to see how others have optimized their codes!

this is not the appropriate behavior, kindly forward it to the team, I have told in a post that the complexity of my solution is `O(N*100*log(N)` which satisfies the given constraints and hence should be accepted , Do take a look again and share it to relevant team

**Comment by tushargoyal22** [comment]
@stormsunshine @LC-Sue @LC-Pamela

**Comment by stormsunshine** [comment]
Why are you mentioning me here? I am only a user, not a member of LeetCode site.

Since the maximum value of n is 20000 and the maximum value of k is 100, the time complexity O(nk log n) is very likely to get TLE. You should find a solution with a lower time complexity, like O(nk).
