### ISSUE TITLE
美服同步之后提交时间的错误

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#614]
**描述**
我昨天同步了美服的提交记录，发现在题目的提交页面，提交时间的时间是错误的，点进某个具体的提交页面后，提交时间是正确的

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
错误的提交时间
![Snipaste_2020-07-12_10-29-03](https://user-images.githubusercontent.com/32877011/87251689-c5894680-c42a-11ea-87d6-557ef95a1a25.png)

正确的提交时间
![Snipaste_2020-07-12_10-29-20](https://user-images.githubusercontent.com/32877011/87251690-c621dd00-c42a-11ea-81e3-510ff0fb908f.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
您好，该问题已修复，请稍后刷新网页再试试，感谢您对力扣的支持～
