### ISSUE TITLE
Space Complexity of Implementation is wrong - 187. Repeated DNA Sequences

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6145]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[187. Repeated DNA Sequences](https://leetcode.com/problems/repeated-dna-sequences/solution/)

In the Implementation of Approach 2 and Approach 3, there's a `nums` array that takes `O(N)` spaces. It's different from the expected space complexity.

#### Expected behavior

Actually, we don't need the `nums` and can get the corresponding value in `O(1)` time complexity.

#### Additional context

Instead of using a `Set` to prevent the duplicate answer, we can just use an array for the answer and use a counter to store the frequency of each pattern and only append the answer when the frequency is `1`. This won't reduce time & space complexity but can reduce the substring operations to save some time.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
