### ISSUE TITLE
Wrong Example test case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by mrahul25** [LeetCode-Feedback/LeetCode-Feedback#6146]
#### Your LeetCode username

LeetCode username - i_amrahul25

#### Category of the bug
- [ ] Wrong Test Cases 

#### Description of the bug

In the test case Example 2 in place of k=6 there should be k=42

**Comment by stormsunshine** [comment]
Didn't you see the word "multiple"? Your understanding of the problem is wrong.
