### ISSUE TITLE
Marking  as wrong answer incorrectly - 22. Generate Parentheses

### ISSUE THREAD

**Issue by jayankmayukh** [LeetCode-Feedback/LeetCode-Feedback#6148]
#### Your LeetCode username
jayankmayukh

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution not being accepted based on the order in which patterns are produced, even though the question does not specify any particular order for patterns.

#### Code you used for Submit/Run operation

```javascript
var generateParenthesis = function(n) {
    let arr1 = ['()'];
    let arr2 = [];
    for (let i = 1; i < n; i++) {
        let from = i % 2 ? arr1 : arr2;
        let to = i % 2 ? arr2 : arr1;
        while (from.length) {
            let pat = from.pop();
            let around = `(${pat})`;
            let left = `()${pat}`;
            let right = `${pat}()`;
            to.push(around);
            if (left !== right) {
                to.push(left);
            }
            to.push(right);
        }
    }
    return arr1.length ? arr1 : arr2;
};
```

#### Language used for code
javascript

#### Expected behavior

all solutions must be accepted no matter how they are arranged.
Maybe asking to return a set instead of an array would be helpful.

#### Screenshots

![image](https://user-images.githubusercontent.com/51356600/151239405-504fe9d3-bd25-4a4c-9850-28e1bf136ea9.png)

**Comment by stormsunshine** [comment]
Your output is indeed wrong. This is irrelevant to order.

In your output, `"()(())()"` occurs twice, while `"(())(())"` does not occur.

If you use two sets to store all strings in your output and all strings in the expected output, these two sets have different sizes.

**Comment by jayankmayukh** [comment]
Now I see, it's indeed wrong. Thanks for the clarification.

**Comment by LC-Sue** [comment]
Hi @jayankmayukh,
Thank you for reaching out to us, I'm sooner we didn't get to you sooner but I'm glad to see your issue has been resolved!
