### ISSUE TITLE
The code that judges custom test cases for "1515. Best Position for a Service Centre" problem is inaccurate

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#615]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The code that judges custom test cases for "1515. Best Position for a Service Centre" problem is inaccurate.

Example 1:
Your input: [[27, 90], [99, 75], [99, 38]]
Output: 109.30317
Expected: 110.54590

There is a point Xcentre=92.3322604399428,  Ycentre=68.96415916351724, that the sum of the euclidean distances to all customers is smaller: 109.30317 and the difference between expected result is more than 1.2

Example 2:
Your input: [[93, 86], [92, 44], [6, 38]]
Output: 125.62156
Expected: 128.22095

There is a point Xcentre=82.7095553049064,  Ycentre=54.315418986776194 that the sum of the euclidean distances to all customers is smaller: 125.62156 and the difference between expected result is more than 2.5

#### Code you used for Submit/Run operation

The code is of no importance for this issue.

#### Expected behavior

The code that judges custom test cases should produce correct results with reasonable accuracy. The discrepancy of 2.5 between the expected and a better results is too much

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/87260429-d7e19f80-c47f-11ea-84dc-6dca58587f32.png)
![image](https://user-images.githubusercontent.com/32546406/87260672-11ff7100-c481-11ea-8bd6-e8b04aef55ad.png)
![image](https://user-images.githubusercontent.com/32546406/87261047-a918f880-c482-11ea-8c92-34698ce03b3f.png)
![image](https://user-images.githubusercontent.com/32546406/87260814-a9fd5a80-c481-11ea-9e22-1ab4a245561b.png)
![image](https://user-images.githubusercontent.com/32546406/87260919-2db74700-c482-11ea-8510-49f22fd5bb0b.png)
![image](https://user-images.githubusercontent.com/32546406/87260967-517a8d00-c482-11ea-916e-0fd8b9d27e3e.png)

**Comment by lc-christina** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
