### ISSUE TITLE
Missing Test Case - 198. House Robber

### ISSUE THREAD

**Issue by MMehdiMousavi** [LeetCode-Feedback/LeetCode-Feedback#6150]
#### Your LeetCode username
MMehdiMousavi

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Same code produces different result in the same test case.

#### Code you used for Submit/Run operation

```
class Solution:
    
    def loot(self, nums, i, d={}):
        
        if i < 0:
            return 0
        
        if i not in d:
            d[i] = max(nums[i]+self.loot(nums,i-2,d), self.loot(nums,i-1,d))
        
        return d[I]
    
    def rob(self, nums: List[int]) -> int:
        return self.loot(nums, len(nums)-1)
```

#### Language used for code
Python3

#### Expected behavior
Test case [2,7,9,3,1] produces 12 when "test" is pressed but 5 when "submit" is pressed.

#### Screenshots
[](https://imgur.com/a/JTVG2AJ)

**Comment by LC-Sue** [comment]
Hi @MMehdiMousavi 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
