### ISSUE TITLE
Missing Test Case - 40. Combination Sum II

### ISSUE THREAD

**Issue by ramyamagham** [LeetCode-Feedback/LeetCode-Feedback#6151]
#### Category of the bug Missing Test Cases
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug 
Want to add one more test case along with test case where the input is all 1s and the target is 30, my code did not consider sorting the candidate array, I just did the following. It still accepted my solution. So if we added a few 1s like maybe first 6 and then mix in a 2 and then add more 1s, then my solution breaks because it starts giving duplicate array solutions. I had to add a sort of the candidates array. So by adding this test case my submission would have failed. So let's add that test case. Thanks.

Test case: 
{1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1}
Target: 30

My faulty Java code:
<i>
        currentList.add(candidates[index]);
        recurse(result, candidates, target, currentList, sum + candidates[index], index+1);
        currentList.remove(currentList.size()-1); //remove the last element before right branch

        int currentCandidate = candidates[index]; //skip until non-duplicate for next recursion
        while(index < candidates.length && currentCandidate == candidates[index]){
            index++;
        }

        recurse(result, candidates, target, currentList, sum, index); //recurse with next non-duplicate
</i>

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
First, the test case you provide is invalid. The problem requires that `candidates.length <= 100`, but in the test case you provide, `candidates.length = 101`. The following test case is a valid one, where an element 1 is removed to make the length of array become 100.
```
[1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
30
```

Secondly, please provide the complete code that can get accepted but fails on this test case. The term "complete" means all the code in the class, so that the code can be copied and pasted for testing.

**Comment by ramyamagham** [comment]
I love it, thanks.
Yeah first is trivial, just removing one 1 will make it, I may have typed an extra 1 sorry about that.
And second, didn't think code is really needed, it's just a variation of another test case that you already have on there. But below's the code anyway. Without the second line "Arrays.sort(candidates);" the solution gets accepted, but with this test case it fails so I have to sort it first.
Thank you very much for contributing and making it better!


_class Solution {
    public List<List<Integer>> combinationSum2(int[] candidates, int target) {
        
        Set<List<Integer>> result = new HashSet<List<Integer>>();
        Arrays.sort(candidates);
        recurse(result, candidates, target, new ArrayList<Integer>(), 0, 0);
        List<List<Integer>> resultList = new ArrayList<List<Integer>>();
        resultList.addAll(result);
        return resultList;
    }
    
    
        public static void recurse(Set<List<Integer>> result, int[] candidates, int target, List<Integer> currentList, int sum, int index){

        if(sum == target){
            List<Integer> resultEntry = new ArrayList<>();
            resultEntry.addAll(currentList);
            Collections.sort(resultEntry);
            result.add(resultEntry);
            return;
        }

        if(index >= candidates.length || sum > target){
            return;
        }

        currentList.add(candidates[index]);
        recurse(result, candidates, target, currentList, sum + candidates[index], index+1);
        currentList.remove(currentList.size()-1); //remove the last element before right branch

                int currentCandidate = candidates[index];
        while(index < candidates.length && currentCandidate == candidates[index]){
            index++;
        }

        recurse(result, candidates, target, currentList, sum, index);

    }
}_

**Comment by ramyamagham** [comment]
So basically to add to the context, what I liked is that the series of all hundred 1s throws time exceeded with my previous code version, so I had to optimize it a little more where sorting gets all the duplicates in one place and I didn't get any time exceeded exception anymore. Well anyway you can either add or I can just close the ticket, doesn't matter I guess. I am good either way.

**Comment by ramyamagham** [comment]
Actually scattered 2s among those many 1s still gives time exceeded exception, try something like this 

_[1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,2,1,1,1,1,2,1,1,1,1,1,1,2,1,1,1,1,2,1,1,1,1,2,1,1,1,1,2,1,1,1,2]
30_

**Comment by LC-Sue** [comment]
Hi @ramyamagham,
Thank you for reaching out to us, the code and test case you provided are both accepted. Since there is no missing test case I will close this issue now. I've attached a screenshot for your reference! 
![image](https://user-images.githubusercontent.com/92285126/152073201-fdf313c9-d557-436d-9e3c-3ae982e4e6a3.png)
