### ISSUE TITLE
SQL statement error - 1795. Rearrange Products Table

### ISSUE THREAD

**Issue by kallydev** [LeetCode-Feedback/LeetCode-Feedback#6152]
#### Your LeetCode username

kallydev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Incorrect integer value: 'None' for column 'store2' at row 1.

#### Language used for code

SQL

#### Expected behavior

Simply replace `'None'` with `null` to solve this problem.

```sql
Create table If Not Exists Products (product_id int, store1 int, store2 int, store3 int)
Truncate table Products
insert into Products (product_id, store1, store2, store3) values ('0', '95', '100', '105')
insert into Products (product_id, store1, store2, store3) values ('1', '70', null, '80')
```

#### Screenshots

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/36319157/151278837-81e3bd43-8aed-4b65-8c85-88a559c2fbae.png">

**Comment by LC-Sue** [comment]
Hi @kallydev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kallydev,
Thank you for your time, our team has reviewed your feedback and decided to keep our statement the way it is. We appreciate your support!
