### ISSUE TITLE
Missing Test Case - 384.Shuffle An Array

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#6153]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
The problem is designed for Fisher-Yates. If an interviewer uses this problem, the solution with brute force cannot pass the interview.
However, the code either using brute force or using Fisher-Yates get OLE(Output Limit Exceeded) on the specific testcase. 
[testcase384.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7946922/testcase384.txt)

Code you used for Submit/Run operation

The time compleixty of the code below is O(n^2). Can be accepted but get OLE(Output Limit Exceeded) on the testcase above.
```
class Solution:
    def __init__(self, nums: List[int]):
        self.nums = nums
        self.original = nums.copy()

    def reset(self) -> List[int]:
        self.nums = self.original.copy()
        return self.nums

    def shuffle(self) -> List[int]:
        shuffled = [0] * len(self.nums)
        for i in range(len(self.nums)):
            j = random.randrange(len(self.nums))
            shuffled[i] = self.nums.pop(j)
        self.nums = shuffled
        return self.nums
```

The time complexity of the code below is O(n). Can be accepted but get OLE(Output Limit Exceeded) on the testcase above.
```
class Solution:
    def __init__(self, nums: List[int]):
        self.nums = nums
        self.original = nums.copy()

    def reset(self) -> List[int]:
        self.nums = self.original.copy()
        return self.nums

    def shuffle(self) -> List[int]:
        for i in range(len(self.nums)):
            j = random.randrange(i, len(self.nums))
            self.nums[i], self.nums[j] = self.nums[j], self.nums[i]
        return self.nums
```

Language used for code
Python3

Expected behavior
1. The times of calls "reset" or "shuffle" should be reduced. 
2. If the brute force with O(n^2) time complexity is not an expected solution, the nums.length can be increased to 1000 and the time of calls "shuffle" can be reduced to 1000, so the users who write Fisher-Yates can pass the problem, and brute force will get TLE.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @CarlCzerny837 
Thank you for your time. The size of the output for this test case is too large and does not fit in the platform so we have rejected the test case. We appreciate your support!

**Comment by stormsunshine** [comment]
@LC-Sue Could you please relay this issue to your team to decide whether the constraints should be changed? If the test case provided in this issue is too large, then the constraints should be changed accordingly to avoid such test cases. Constraints should reflect the expected time complexity.
