### ISSUE TITLE
 SQL statement error - 584. Find Customer Referee

### ISSUE THREAD

**Issue by kallydev** [LeetCode-Feedback/LeetCode-Feedback#6154]
#### Your LeetCode username

kallydev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Incorrect integer value: 'None' for column 'referee_id' at row 1.

#### Language used for code

SQL

#### Expected behavior

Simply replace `'None'` with `null` to solve this problem.

```sql
Create table If Not Exists Customer (id int, name varchar(25), referee_id int)
Truncate table Customer
insert into Customer (id, name, referee_id) values ('1', 'Will', null)
insert into Customer (id, name, referee_id) values ('2', 'Jane', null)
insert into Customer (id, name, referee_id) values ('3', 'Alex', '2')
insert into Customer (id, name, referee_id) values ('4', 'Bill', null)
insert into Customer (id, name, referee_id) values ('5', 'Zack', '1')
insert into Customer (id, name, referee_id) values ('6', 'Mark', '2')
```

#### Screenshots

<img width="833" alt="image" src="https://user-images.githubusercontent.com/36319157/151279971-e3bbb437-0d6e-46c2-b05e-f38a7df638fd.png">

**Comment by LC-Sue** [comment]
Hi @kallydev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kallydev,
Thank you for your time, our team has reviewed your feedback and decided to keep the statement as is. We appreciate your support!
