### ISSUE TITLE
Better understandable Solution

### ISSUE THREAD

**Issue by unsmoker** [LeetCode-Feedback/LeetCode-Feedback#6155]
#### Your LeetCode username
khassangali

#### Category of the bug
- [ ] Solution

#### Description of the bug

The two-pointer approach answer provided by premium solution content is too complicated. I would like to give my answer as a solution, easy to understand. 

#### Code you used for Submit/Run operation

```
// Backspace String Compare
class Solution {
    public boolean backspaceCompare(String s, String t) {
         return Arrays.equals(getStringValues(s), getStringValues(t));
    }
    
    char[] getStringValues(String str) {
        //convert to char array
        char[] chars = str.toCharArray();
        
        //last char not deleted index value
        int lastValidIndex = 0;
    
        for (int i = 0; i < chars.length; i++) {
            // if not backSpace then swap to index
            if (chars[i] != '#')  {
                chars[lastValidIndex++] = chars[i];
            } else {
                //go back one index 
                if (lastValidIndex != 0) {
                    lastValidIndex--;   
                }
            }
        }
        return Arrays.copyOfRange(chars, 0, lastValidIndex);
    }
}
```

**Comment by unsmoker** [comment]
Hope this content will be added to the solution.

**Comment by LC-Sue** [comment]
Hi @unsmoker,
Thank you for reaching out to us, could you please provide the problem number for the issue?

**Comment by LC-Sue** [comment]
Hi @unsmoker 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
