### ISSUE TITLE
Missing Test Case - 278. First Bad Version

### ISSUE THREAD

**Issue by dfberry** [LeetCode-Feedback/LeetCode-Feedback#6158]
#### Your LeetCode username
dfberry

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Most questions can be easily written outside of Leet code, while I'm working through my own test cases and strategy. This one isn't as easy to work with because part of the required code is missing. Sometimes you provide that required code in comments and sometimes you don't. This probably would be easier to understand if the required code was in the comments. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @dfberry,
Thank you for reaching out to us, the driver code is available!

**Comment by diberry** [comment]
Did you mean to add a link? Where is the driver code?
