### ISSUE TITLE
Space Complexity of Implementation is wrong  - 421. Maximum XOR of Two Numbers in an Array

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6160]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[421. Maximum XOR of Two Numbers in an Array](https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/solution/)

In the Python Implementation of Approach 2, it generates a new `nums` array for the left-padding. This uses `O(N * L) = O(N)` space complexity, which is different from the space complexity in Complexity Analysis.

#### Expected behavior

We can get the binary string with left padding without extra space and time.

e.g. in the for-loop
```python
num_bin = bin(num)[2:].zfill(L)
```

#### Additional context

I think this problem also happened in Java Implementation and has its corresponding solution.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
