### ISSUE TITLE
Bug Found - 1759. Count Number of Homogenous Substrings

### ISSUE THREAD

**Issue by chiragarora01** [LeetCode-Feedback/LeetCode-Feedback#6161]
#### Your LeetCode username

meweird048

#### Category of the bug
- [ ] Bug

#### Description of the bug

Giving different output on same code with same input, as shown in screenshots. When I run only that particular case ans is right but when I run same code with 3 input at once output is different.

==========================

**Input** : "abbcccaa"
**Output** : 13

==========================
**Input** : "abbcccaa"
                  "xy"
                  "zzzzz"
**Output(of 1st case)** : 14
#### Code you used for Submit/Run operation

```
// class Solution {
public:
    int countHomogenous(string s) {
        int count=1,ans=0;
        for(int i=0;i<=s.length();i++)
        {
            if(s[i]==s[i+1])
                count++;
            else
            {
                ans+=(count*(count+1))/2;
                count=1;
            }
        }
        return ans;
    }
};

```

#### Language used for code

C++

#### Expected behavior

Both times, output should be same because input and code is same it doesn't matter code is correct or not, how can output change on same input and same code.

#### Screenshots

![Screenshot 2022-01-27 at 22-15-22 Count Number of Homogenous Substrings - LeetCode](https://user-images.githubusercontent.com/57770932/151407096-9e57b2eb-f391-4e6d-94cd-66900234f3dd.png)
![Screenshot 2022-01-27 at 22-14-57 Count Number of Homogenous Substrings - LeetCode](https://user-images.githubusercontent.com/57770932/151407101-49fcfa93-18de-472e-a105-dbfee5866d82.png)

**Comment by LC-Sue** [comment]
Hi @chiragarora01 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
