### ISSUE TITLE
All element in 2 binary tree

### ISSUE THREAD

**Issue by caleberi** [LeetCode-Feedback/LeetCode-Feedback#6163]
#### Your LeetCode username
caleberi

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I tried solving the daily challenge for this problem set but after testing via the console successfully . One of the exact test case used via the console gave an error while submit . I have tried gathering my thought but still think my answer is correct.

#### Code you used for Submit/Run operation
```py
class Solution:
    def getAllElements(self, root1: TreeNode, root2: TreeNode) -> List[int]:
        list_one = get_element_in_tree(root1,[])
        list_two = get_element_in_tree(root2,[])
        list_one.sort()
        list_two.sort()
        return merge(list_one, list_two)

def get_element_in_tree(tree, result):
    if tree is None:
        return result
    result = get_element_in_tree(tree.left, result)
    result.append(tree.val)
    result = get_element_in_tree(tree.right, result)
    return result


def merge(l1, l2, result=[]):
    i = 0
    j = 0
    while i < len(l1) and j < len(l2):
        if l1[i] <= l2[j]:
            result.append(l1[i])
            i += 1
        elif l2[j] <= l1[i]:
            result.append(l2[j])
            j += 1
    while i < len(l1):
        result.append(l1[i])
        i += 1
    while j < len(l2):
        result.append(l2[j])
        j += 1
    return result
```

#### Language used for code
python3

#### Expected behavior
Input
[1,null,8]
[8,1]
Output (from leetcode)
[0,1,1,2,3,4,1,1,8,8]
Expected
[1,1,8,8]

#### Screenshots
![leetcode](https://user-images.githubusercontent.com/31941399/151415495-52d5830f-cf2d-4fb5-a845-d90611fb0489.PNG)

#### Additional context
the same input is providing different output

**Comment by LC-Sue** [comment]
Hi @caleberi 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
