### ISSUE TITLE
Missing Test Case - 2145. Count the Hidden Sequences

### ISSUE THREAD

**Issue by sandeshk** [LeetCode-Feedback/LeetCode-Feedback#6166]
#### Your LeetCode username
deshu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Want to add/modify a large test case for which an incorrect solution got accepted.
Test Case:
[100000,100000,100000, ..., total 10^5 times]
-100000
100000
[Testcase Link](https://gist.github.com/sandeshk/1ecaa4ff6a2595486e2f0f5ef9b42dba)

#### Code you used for Submit/Run operation

```
class Solution {
    public int numberOfArrays(int[] differences, int lower, int upper) {
        int min = Integer.MAX_VALUE;
        int max = Integer.MIN_VALUE;
        
        int sum = 0;
        for(int d : differences) {
            sum += d;
            min = Integer.min(min, sum);
            max = Integer.max(max, sum);
        }
        
        //System.out.println(min + " - " + max);
        
        int low = Integer.max(lower, lower - min);
        int high = Integer.min(upper, upper - max);
        //System.out.println(low + " ~ " + high);
        
        return Integer.max(0, high - low + 1);
    }
}
```

#### Language used for code
Java

#### Expected behavior
Should have given a wrong answer (sum of integers overflow issue), it got accepted.

**Comment by LC-Sue** [comment]
Hi @sandeshk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sandeshk 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
