### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by baumstan** [LeetCode-Feedback/LeetCode-Feedback#6167]
#### Your LeetCode username

kbaumberg

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The outcome of the example below is returning 1 in the LeetCode editor and 6 in my Jupyter notebook. 6 is the correct answer for this test case. Why is Leetcode returning 1?

input = [-2,1,-3,4,-1,2,1,-5,4]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution(object):
    def maxSubArray(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        
        
        import numpy as np
        import itertools

        nums = [1]
        final = []
        if len(nums) == 1:
            return nums[0]

        for i, j in itertools.combinations(range(len(nums)),2):
            final.append(np.sum(np.array(nums[i:j])))
        
        final = max(final)
        return final
```

#### Expected behavior

The outcome of the example below is returning 1 in the LeetCode editor and 6 in my Jupyter notebook. 6 is the correct answer for this test case. Why is Leetcode returning 1?

**Comment by LC-Sue** [comment]
Hi @baumstan,
Thank you for reaching out to us, our judger is running correctly. Please feel free to refer to the discuss section of the problem to see how others have optimized their codes!
