### ISSUE TITLE
Wrong Constraints - 211. Design Add and Search Words Data Structure

### ISSUE THREAD

**Issue by tiresias7** [LeetCode-Feedback/LeetCode-Feedback#6170]
#### Your LeetCode username

7tiresias7

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think the question has unreasonable large data constraints, and should be changed in order to make it right.
The time complexity of the total program should be O(n^2*m), where n is the number of requests and m is the max length of a word.

#### Code you used for Submit/Run operation

```
// Two Sum
// The code is of little use actually, but I put it here anyway.
class WordDictionary {
struct node{
    int c[26]={0};
    int key=0;
};
vector<node> T;
int cnt=0;
public:
    
    WordDictionary() {
        T.clear();
        node temp;
        //for(int i=0;i<26;++i) cout<<temp.c[i]<<' ';
        T.push_back(temp);
    }
    
    void addWord(string word) {
        int cur=0;
        for(char c:word){
            int i=c-'a';
            if(!T[cur].c[i]){
                node temp;
                ++cnt;
                T.push_back(temp);
                T[cur].c[i]=cnt;
                cur=cnt;
            }
            else cur=T[cur].c[i];
            //cout<<cnt<<' ';
        }
        //cout<<endl;
        T[cur].key=1;
    }
    
    bool search(string word) {
        return find(word,0,0);
    }
    
    bool find(string &word,int cur,int k){
        //cout<<word<<' '<<cur<<' '<<k<<endl;
        while(k<word.length()){
            if(word[k]=='.'){
                for(int j=0;j<26;++j){
                    if(T[cur].c[j]){
                        if(find(word,T[cur].c[j],k+1))
                            return true;
                    }
                }
                return false;
            }
            else{
                int i=word[k]-'a';
                if(T[cur].c[i]) cur=T[cur].c[i];
                else return false;
                ++k;
            }
        }
        return T[cur].key;
    }
};

/**
 * Your WordDictionary object will be instantiated and called as such:
 * WordDictionary* obj = new WordDictionary();
 * obj->addWord(word);
 * bool param_2 = obj->search(word);
 */
```

#### Language used for code

C++

#### Expected behavior

Using the testcase in the additional context with n=5000 and m=100 (far smaller than the given constraints), any solution won't pass, including the standard solution.
All code will result in "Time Limit Exceeded".  

#### Additional context

[testcase1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7955436/testcase1.txt)

**Comment by stormsunshine** [comment]
I agree that the data constraints should be smaller. However, the time complexity mentioned in this issue seems to be incorrect.

If the time complexity of the total program is O(n^2*m), then each call has time complexity O(nm). However, for each call to `search`, since the characters include dots (`'.'`), each call has time complexity O(m^26).

The expected behavior should be that constraints should be much smaller to make the standard trie solution pass all test cases under the constraints.

**Comment by tiresias7** [comment]
Theoretically, each call is O(m^26) for an arbitrary trie. However, since we only have at most O(n) inputs, each with length O(m), there will be at most O(n*m) nodes in the standard Trie; won't get to such large as O(m^26).

I agree the constraints should be much smaller. Thank you for your time.

**Comment by LC-Sue** [comment]
Hi @tiresias7 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @tiresias7,
Thank you for reaching out to us, our content team has reviewed the issue and decided that the current constraints are fine and will not be changing them!
