### ISSUE TITLE
Need to Add Space Complexity Constraint - 167. Two Sum II - Input Array Is Sorted

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6174]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [167. Two Sum II - Input Array Is Sorted](https://leetcode.com/problems/two-sum-ii-input-array-is-sorted), a solution with O(n) time complexity and O(n) space complexity can get accepted, where n is the length of the input array. This solution is almost the same as the solution to [1. Two Sum](https://leetcode.com/problems/two-sum) with O(n) time complexity and O(n) space complexity, except that the returned indices are a bit different (0-indexed and 1-indexed in two problems).

However, since the array is already sorted, the solution with O(n) space complexity is not an expected solution. There are two expected solutions with O(1) space complexity, which are the binary search solution with O(n log n) time complexity, and the two pointers solution with O(n) time complexity.

Since the maximum value of n is 3 * 10<sup>4</sup>, a brute force solution with O(n<sup>2</sup>) time complexity and O(1) space complexity should get TLE (please refer to #6173 that requires adding two more test cases to make sure the brute force solutions get TLE). Therefore, by requiring O(1) space complexity, the brute force solution is still not an expected solution, and only the binary search solution and the two pointers solution are expected solutions.

If the problem (167) is used during an interview, the interview will expect a solution with O(1) space complexity, otherwise this problem is just the same as problem 1 and thus it is meaningless. Therefore, O(1) space complexity should be a standard requirement for problem 167.

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] twoSum(int[] numbers, int target) {
        Map<Integer, Integer> map = new HashMap<Integer, Integer>();
        int length = numbers.length;
        for (int i = 0; i < length; i++) {
            int num = numbers[i];
            if (map.containsKey(target - num)) {
                int prevIndex = map.get(target - num);
                return new int[]{prevIndex + 1, i + 1};
            }
            map.put(num, i);
        }
        return new int[]{-1, -1};
    }
}
```

#### Language used for code
Java

#### Expected behavior
Add space complexity constraint in problem description, like one of the following.

- Your solution must use only O(1) extra space.
- Your solution must use only constant extra space.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
