### ISSUE TITLE
Missing Type Hints - 285. Inorder Successor in BST (Python3)

### ISSUE THREAD

**Issue by shurane** [LeetCode-Feedback/LeetCode-Feedback#6176]
#### Your LeetCode username

shurane

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The type hints for this problem in Python3 could be updated to not use strings.

#### Code you used for Submit/Run operation

Original
```python3
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, x):
#         self.val = x
#         self.left = None
#         self.right = None

class Solution:
    def inorderSuccessor(self, root: 'TreeNode', p: 'TreeNode') -> 'Optional[TreeNode]':
        
```

But it could be updated to
```python3
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, x):
#         self.val = x
#         self.left = None
#         self.right = None

class Solution:
    def inorderSuccessor(self, root: TreeNode, p: TreeNode) -> Optional[TreeNode]:
        
```

**Comment by LC-Sue** [comment]
Hi @shurane 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @shurane 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
