### ISSUE TITLE
Missing Test Case - 211. Design Add and Search Words Data Structure

### ISSUE THREAD

**Issue by Shrivis** [LeetCode-Feedback/LeetCode-Feedback#6177]
#### Your LeetCode username

Shrivis

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code that gets accepted generates TLE in the following test case.
[testCase.txt](https://drive.google.com/file/d/1aVYD6M5ZsJFcFDTjrUOAK9Vj-mdkISDI/view?usp=sharing)

#### Code you used for Submit/Run operation

```
// Design Add and Search Words Data Structure
class WordDictionary {
public:
    unordered_map<int,vector<string> > mp1;
    
    void addWord(string word) {
        mp1[word.length()].push_back(word);
    }
    
    bool search(string word) {
        int n=word.length();
        for(auto& s:mp1[n]){
                int i=0;
                while((i<n)&&(s[i]==word[i] || word[i]=='.')){
                    i++;
                }
                if(i==n)
                    return true;
            }
        return false;
    }
};
```

#### Language used for code

C++

**Comment by LC-Sue** [comment]
Hi @Shrivis，
Thank you for reaching out to us, the test case you provided is invalid. Params is not a valid list of arguments: ValueError('Unmatched \'\'"\' when when decoding \'string\'',)

**Comment by Shrivis** [comment]
![Screenshot_20220203-191439](https://user-images.githubusercontent.com/53143278/152354967-bfad9cd5-8ba6-4401-be05-8ea59ba04d8e.jpg)


@LC-Sue the test case is valid(see screenshot), and gets accepted with solutions using tries(how it was meant to be solved). Please look at it again :)

**Comment by LC-Sue** [comment]
Hi @Shrivis,
Thank you for reaching out, from the screenshot you provided, the test case passes the code, so it wouldn't be a missing test case.
