### ISSUE TITLE
Wrong Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by NorthernMystic** [LeetCode-Feedback/LeetCode-Feedback#6179]
#### Your LeetCode username
NorthernMystic

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
See one test case: 
Input:
[1,2,3,4,5,6,7,8]
[1,2,3,4,5,6,7,8]
Output:
7
Expected:
0

I believe the solution is not unique for this input 
Please correct me if I am wrong

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by NorthernMystic** [comment]
this input also 
Input:
[4,5]
[4,5]

**Comment by NorthernMystic** [comment]
Input
[2,2,2,2,2,2,2]
[2,2,2,2,2,2,2]

**Comment by NorthernMystic** [comment]
also seems the last huge [1000, 1001,... case

**Comment by stormsunshine** [comment]
@NorthernMystic These test case are illegal. The problem requires that for each test case, if the answer exists, it is guaranteed to be unique. For the test cases in this issue, do the test cases have unique answer?

**Comment by LC-Sue** [comment]
Hi @NorthernMystic 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @NorthernMystic 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
