### ISSUE TITLE
Conflicting test cases for the problem 269. Alien Dictionary

### ISSUE THREAD

**Issue by Nan-Do** [LeetCode-Feedback/LeetCode-Feedback#618]
#### Your LeetCode username

Nan-Do

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

There are conflicting test cases for the problem, for example test case 112, the valid output should be the empty string as according to the rules but it expects the answer "djkrtw".

#### Code you used for Submit/Run operation
Python 3

#### Language used for code

Python 3

#### Expected behavior

The test case should the expect the empty string or the test case should be removed

#### Additional context

According to the admin (1337c0d3r) this and similar test cases should be removed, please see the link https://leetcode.com/problems/alien-dictionary/discuss/70121/Wrong-test-case:-for-test-case-"wrtkj""wrt"-we-are-doing-this-based-on-"Alien"-dictionary./72264

**Comment by lc-christina** [comment]
Hi @Nan-Do 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @Nan-Do ,
Can you please help provide the testcase 112 you mentioned in the ticket? The testcase label might have changed when we update problem and the test case 112 we have in the system is different from what you described. Also, the given thread is very old and doesn't apply to our current standards. We'll review the test case again when you provide the test case. Thank you!

**Comment by Nan-Do** [comment]
I have checked and it is not the test case number 112 is the testcase 113.
The input is

Input: ["wrt","wrtkj","wrtkjd"]
Output: ""
Expected: "djkrtw"

Any testcase in which the input has a set of prefixes will work, the valid output for that input given the specifications should be the empty string.

**Comment by lc-pam** [comment]
Hi @Nan-Do ,
Thanks for sharing the test case. I've shared the details with the team. I'll get back to you when I receive updates from the team.

**Comment by lc-pam** [comment]
Hi @Nan-Do ,
The team has reviewed your report but decided not to update or remove the test case. The comment made by the admin was provided long time ago and the statement was different. If you still have questions about the test case, I recommend you post the question in the problem's discuss tab.
