### ISSUE TITLE
Wrong space complexity for the optimal solution - 442. Find All Duplicates in an Array

### ISSUE THREAD

**Issue by MedMaalej** [LeetCode-Feedback/LeetCode-Feedback#6180]
#### Your LeetCode username
https://leetcode.com/mohamedmaalej/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The provided optimal solution number 4 supposes the following: 

> Space complexity : No extra space required, other than the space for the output list. We re-use the input array to store visited status.

#### Expected behavior
Adding a new array list to return the result will occupy at the worst case n/2 memory addresses (if every element occurs exactly twice). So, I think the space complexity should be O(n) instead.

**Comment by LC-Sue** [comment]
Hi @MedMaalej 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @MedMaalej
Thank you for your time. Generally, modifying the input array in-place does not count as extra space. However, given the problem states that the solution must use only constant extra space, I can understand your concern. In an interview setting, you may wish to clarify that the interviewer is okay with this interpretation of constant space before moving forward
