### ISSUE TITLE
Missing Test Case - 211. Design Add and Search Words Data Structure

### ISSUE THREAD

**Issue by Odomontois** [LeetCode-Feedback/LeetCode-Feedback#6181]
#### Your LeetCode username
nizhnik

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Need to narrow constraints. There is no practical solution that could solve the problem for any test case

#### Example test case 

https://gist.githubusercontent.com/Odomontois/11017f77b3521c73b4aa515300b1fe0b/raw/2701e7de622351ca819e1ab94fbed445214a9ce3/design-add-and-search-words-data-structure.json

#### Code you used for Submit/Run operation
```rust
use std::collections::HashMap;

// https://leetcode.com/problems/design-add-and-search-words-data-structure/
#[derive(Default)]
struct WordDictionary {
    end: bool,
    next: HashMap<char, Box<WordDictionary>>,
}

impl WordDictionary {
    fn new() -> Self {
        Self::default()
    }

    fn add_word(&mut self, word: String) {
        let mut cur = self;
        for c in word.chars() {
            cur = &mut **cur.next.entry(c).or_insert_with(|| Box::new(Self::new()));
        }
        cur.end = true
    }

    fn search(&self, word: impl AsRef<str>) -> bool {
        let mut stack = vec![(self, word.as_ref().chars())];
        while let Some((dict, mut suffix)) = stack.pop() {
            match suffix.next() {
                None if dict.end => return true,
                None => continue,
                Some('.') => {
                    for (_, next) in &dict.next {
                        stack.push((next, suffix.clone()))
                    }
                }
                Some(c) => {
                    for next in dict.next.get(&c) {
                        stack.push((next, suffix.clone()))
                    }
                }
            }
        }

        false
    }
}
```
```

#### Language used for code
rust

**Comment by LC-Sue** [comment]
Hi @Odomontois 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Odomontois 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
