### ISSUE TITLE
Java/ c++ 55. Jump Game

### ISSUE THREAD

**Issue by isuvorov1** [LeetCode-Feedback/LeetCode-Feedback#6183]
#### Your LeetCode username

igorsuvorov
#### Category of the bug
- [+] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test case [3,2,1,0,4]

Sometimes works, sometimes doesn't with exact same code.
#### Code you used for Submit/Run operation

```
class Solution {
    public static int i = 0;
    public static int counter = 0;
    public boolean canJump(int[] nums) {
        if (nums.length == 1) {
            return true;
        }
        if (i == 0) {
        counter = nums[i];
        }
        if (counter == 0) {
            return false;
        } 
        if (nums[i] < nums[i+1] || nums[i] == nums[i+1]) {
            counter = nums[i+1];
            i++;
        } else {
            counter--;
            i++;
        }
        if (i >= nums.length-2 && counter > 0) {
            return true;
        }
        return canJump (nums);
    }
}
```

#### Expected behavior

Test case [3,2,1,0,4]
If I click "Run code" it works properly.
If I click "Submit" this test case shows wrong result.

**Comment by stormsunshine** [comment]
The reason is that you have used static variables. Do not use static variables.

**Comment by LC-Sue** [comment]
Hi @isuvorov1,
Thank you for reaching out to us, please feel free to refer to the discuss section of the problem to see how other users have optimized their codes
