### ISSUE TITLE
Missing Test Case and Wrong Constraints - 211. Design Add and Search Words Data Structure

### ISSUE THREAD

**Issue by cod-OR** [LeetCode-Feedback/LeetCode-Feedback#6185]
#### Your LeetCode username
[code_OR](https://leetcode.com/code_OR/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There are a few large test cases that are absent from the test data. 
I have attached one test file below.
Here is the description of the test case:
```
A large number of "addWord" queries with a word of high length.
Followed by a large number of "search" queries a word of the form "........z" (some word which will return 0, but will require traversal of whole data structure to check).
```

#### Code you used for Submit/Run operation

Unorder-map solution.
Expected TLE, but gets accepted.

```
class WordDictionary {
public:
    WordDictionary() {}
    
    void addWord(string word) {
        words[word.size()].push_back(word);
    }
    
    bool search(string word) {
        for(auto s: words[word.size()]) if(isEqual(s, word)) return true;
        return false;
    }
    
private:
    unordered_map<int, vector<string>>words;
    
    bool isEqual(string a, string b){
        for(int i = 0; i < a.size(); i++){
            if(b[i] == '.') continue;
            if(a[i] != b[i]) return false;
        }
        return true;
    }
};
```

Trie solution.
Gets accepted as expected. But shows TLE on the mentioned test case.

```
struct TrieNode{
    bool isEnd;
    vector<TrieNode*> children;
    TrieNode(){
        isEnd=0;
        for(int i=0;i<26;i++){
            children.push_back(NULL);
        }
    }
};

class WordDictionary {
    
    TrieNode* T;
    void insert(TrieNode* T, string &s, int id){
        assert(T != NULL);
        if(id == s.size()){
            T->isEnd=1;
            return;
        }
        int child = s[id]-'a';
        if(T->children[child]  ==  NULL){
            T->children[child] = new TrieNode();
        }
        insert(T->children[child] , s, id+1);
    }
    
    bool search(TrieNode* t, string word, int id){
        
        if(!t){
            return 0;
        }
        
        if(id == word.size()){
            return t->isEnd;
        }
        
        if(word[id] != '.'){
            int child = word[id]-'a';
            return search(t->children[child], word, id+1);
        }
        
        for(int i=0;i<26;i++){
            if(search(t->children[i], word,id+1))
                return 1;
        }
        return 0;
    }
    
public:
    WordDictionary() {
        T = new TrieNode();
    }
    
    void addWord(string word) {
        insert(T,word,0);
    }
    
    bool search(string word) {
       return search(T,word,0);
    }
};

```

#### Language used for code
C++

#### Additional context

Map or hashing-based solutions should obviously give TLE to the above test case, but they get AC on the platform.
In fact, the most optimized Trie-based solution throws TLE for this case. 
(I checked for 2500 addWord + 2500 search queries. The platform doesn't support custom tests for cases larger than that.)
And that leads to the conclusion that the constraints mentioned are higher than they should be.
[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7958885/input.txt)

**Comment by cod-OR** [comment]
Here is the generator code used to generate the test case
[Generator.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7958921/Generator.txt)
.

**Comment by LC-Sue** [comment]
Hi @cod-OR 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @cod-OR 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
