### ISSUE TITLE
Incorrect Output for Example 1 - 579. Find Cumulative Salary of an Employee

### ISSUE THREAD

**Issue by 42cornflakes** [LeetCode-Feedback/LeetCode-Feedback#6187]
#### Your LeetCode username

42cornflakes

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In "Example 1:", the Output is missing one row (1,7,90)

<pre>
Output: 
+----+-------+--------+
| id | month | Salary |
+----+-------+--------+
| 1  | 7     | 90     |
</pre>

#### Screenshots

![image](https://user-images.githubusercontent.com/46653167/151582100-35d38707-5d58-466d-9697-2735fcb767a3.png)
![image](https://user-images.githubusercontent.com/46653167/151582151-2c13a38a-6601-47f4-845c-6e3cd753c201.png)

**Comment by LC-Sue** [comment]
Hi @42cornflakes 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @42cornflakes 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
