### ISSUE TITLE
462. Minimum Moves to Equal Array Elements II

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#619]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 7: Using Median of Medians has wrong analysis

#### Expected behavior
Space complexity : O(1). No extra space required.

Should be O(n) as extra array is declared in kthsmallest function.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
