### ISSUE TITLE
LeetCode 547 - Number of Provinces - Disjoint Sets

### ISSUE THREAD

**Issue by dipanshuAwasthi** [LeetCode-Feedback/LeetCode-Feedback#6190]
#### Your LeetCode username
dipanshuawasthi

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the solution provided for the above code in the graphs chapter, the solution can be optimized further. https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3846/  

#### Code you used for Submit/Run operation

```
 for(int i=0; i < len; i++){
            for(int j=i; j < len; j++){
                if(isConnected[i][j]==1 && (i!=j)){
                    union(i, j);
                }
            }
        }
```

#### Language used for code
Java

#### Expected behavior
When calling union from the findCircleNum() method (line number 11). We need not run both the for loops from 0. As when 0 and 2 are not connected while checking [0, 2], they will also not be connected when checking [2, 0]. So, we need not check [2,0] again. Instead, we could optimize the loops as I mentioned above.

**Comment by LC-Sue** [comment]
Hi @dipanshuAwasthi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
