### ISSUE TITLE
Missing Test Case - 84. Largest Rectangle in Histogram

### ISSUE THREAD

**Issue by killer-god** [LeetCode-Feedback/LeetCode-Feedback#6192]
#### Your LeetCode username

praveenkumart236

#### Category of the bug
Missing/Weak Test Cases 

#### Description of the bug

Missing/Weak Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int largestRectangleArea(vector<int>& a) {
        int i,n=a.size(),j,k,s=0;
        for(i=0;i<n;i++){
            j=i+1;k=i-1;
            if(i>0&&a[i]==a[i-1])continue;
            while(k>=0&&(a[k]>=a[i]))k--;
            while(j<n&&(a[j]>=a[i]))j++;
            s=max(s,(j-k-1)*a[i]);
        }
        return s;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should give TLE for strong test cases but it got accepted.
Attached sample test for which this code should've failed.
[output.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7962575/output.txt)

**Comment by stormsunshine** [comment]
Please provide an attachment such that the test case can be directly copied and pasted.
Here I provide a link as follows.
[84.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7962905/84.txt)

**Comment by killer-god** [comment]
[Uploading 84_TLE_Input.txt…]()

**Comment by killer-god** [comment]
[84_TLE_Input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7963593/84_TLE_Input.txt)

**Comment by LC-Sue** [comment]
Hi @killer-god 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @killer-god 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
