### ISSUE TITLE
Invalid Test Cases - 134. Gas Station

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6193]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases
- [x] Invalid Test Cases

#### Description of the bug
For [134. Gas Station](https://leetcode.com/problems/gas-station), the problem mentions that: If there exists a solution, it is **guaranteed** to be **unique**.

However, some issues recently requires adding new test cases that have several possible answers. One of the test cases is as follows. In this test case, all indices are possible answers, which does NOT meet the requirement that the answer is unique.

```
[1,2,3,4,5,6,7,8]
[1,2,3,4,5,6,7,8]
```

There are some other test cases added recently, and I believe that all these newly added test cases have several possible answers. This does NOT meet the requirement that the answer is unique. Therefore, **please remove the 5 newly added test cases**.

One more thing that needs to be done is to add a test case checker for problem 134 so that each custom input test case can only be executed when the answer is unique.

#### Code you used for Submit/Run operation

```Java
class Solution {
    public int canCompleteCircuit(int[] gas, int[] cost) {
        int length = gas.length;
        int[] tempGas = new int[length];
        int[] tempCost = new int[length];
        for (int i = 0; i < length; i++) {
            tempGas[i] = gas[(i + 1) % length];
            tempCost[i] = cost[(i + 1) % length];
        }
        gas = tempGas;
        cost = tempCost;

        int start = 0;
        int total = 0, curTotal = 0;
        for (int i = 0; i < length; i++) {
            int difference = gas[i] - cost[i];
            total += difference;
            curTotal += difference;
            if (curTotal < 0) {
                start = i + 1;
                curTotal = 0;
            }
        }
        return total >= 0 ? (start + 1) % length : -1;
    }
}
```

#### Language used for code
Java

#### Expected behavior
1. The 5 newly added test cases should be removed. All remaining test case must meet the requirement that the answer is unique.
2. Add a test case checker for problem 134 so that each custom input test case can only be executed when the answer is unique.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for your time, this issue has already been handled by the team before. We appreciate your support!
