### ISSUE TITLE
Invalid Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by gefeng** [LeetCode-Feedback/LeetCode-Feedback#6194]
#### Your LeetCode username

gefeng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

Confused by test case 36 as it seems to violate the statement "If there exists a solution, it is guaranteed to be unique" 
[1,2,3,4,5,6,7,8]
[1,2,3,4,5,6,7,8]

For this one, wherever you start, we can always visit every gas station on the circle right?

**Comment by LC-Sue** [comment]
Hi @gefeng 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @gefeng，
Thank you for your time, this issue has already been handled by the team before. We appreciate your support!
