### ISSUE TITLE
Typo in Solution for 1089. Duplicate Zeros 

### ISSUE THREAD

**Issue by whoibrar** [LeetCode-Feedback/LeetCode-Feedback#6196]
#### Your LeetCode username
whoibrar

#### Category of the bug
- [ ] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

The sentence **"Approach 1: Two pass, O(1) space"** is used in the solution, stating that there might be multiple approaches further being explained but that's the only approach being mentioned.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
It could've simply said **"Approach : Two pass, O(1) space"** which will avoid confusion.

#### Screenshots

![Screenshot of the part of solution where the issue is found](https://i.imgur.com/BFssL4u.png)

#### Additional context
N/A

**Comment by LC-Sue** [comment]
Hi @whoibrar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @whoibrar,
Thank you for your time, this issue will be addressed in the future when more approaches are added. For now we will keep this as is as it follows a format for all articles!
