### ISSUE TITLE
Missing Test Case and Incorrect Solution Code in the Article - 787. Cheapest Flights Within K Stops

### ISSUE THREAD

**Issue by wblueDean** [LeetCode-Feedback/LeetCode-Feedback#6197]
#### Your LeetCode username
 
wblue2334

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

first solution in the article are currently accepted, but I found missing test case([testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7963104/testcase.txt)) which the first solution doesn't pass.
below solutions is python version I wrote (solution 1 is written in python3) and this is accepted as well 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def findCheapestPrice(self, n, flights, src, dst, k):
        """
        :type n: int
        :type flights: List[List[int]]
        :type src: int
        :type dst: int
        :type k: int
        :rtype: int
        """
        
        
        heap = [(0,0,src)]
         
        graph = defaultdict(list)
        for e in flights:
            graph[e[0]].append((e[1],e[2]))
            
        
        distance = [float('inf') for _ in range(n)]
        stops = [float('inf') for _ in range(n)]
        distance[src],stops[src] = 0, 0
        
        
        while heap:
            
            price, stop, node = heapq.heappop(heap)
            
            if node == dst:
                return price
            
            if stop<=k:
                for v,p in graph[node]:
                    if price+p<distance[v]:
                        distance[v] = price+p
                        heapq.heappush(heap,(price+p,stop+1,v))
                    elif stop+1<stops[v]:
                        heapq.heappush(heap,(price+p,stop+1,v))
                        
                     
                    stops[v] = stop+1
                    
                    
        
        return -1
```

#### Language used for code

Python

#### Expected behavior

My test case contains situation that certain arrival of joint node has larger number of step(which will eventually be the cheapest path within K stops) than previous arrival thus not accepted as valid path since this solution takes only arrival with fewer stops than precedent arrival. In the below screen shot, this solution doesn't take account middle path.

#### Screenshots

![test_case](https://user-images.githubusercontent.com/57700883/151650327-843c5fb1-6145-4356-b7da-6613fc48ff1b.png)

#### Additional context

To take account above situation, stops[v] in the solution should always be maximum number of steps among all arrivals to node v, so that any path within K stops can be processed. Below code corrects this problem.
```
class Solution(object):
    def findCheapestPrice(self, n, flights, src, dst, k):
        """
        :type n: int
        :type flights: List[List[int]]
        :type src: int
        :type dst: int
        :type k: int
        :rtype: int
        """
        
        
        heap = [(0,0,src)]
         
        graph = defaultdict(list)
        for e in flights:
            graph[e[0]].append((e[1],e[2]))
            
        
        distance = [float('inf') for _ in range(n)]
        stops = [float('inf') for _ in range(n)]
        distance[src],stops[src] = 0, 0
        
        
        while heap:
            price, stop, node = heapq.heappop(heap)
            
            if node == dst:
                return price
            
            if stop<=k:
                for v,p in graph[node]:
                    if price+p<distance[v]:
                        distance[v] = price+p
                        heapq.heappush(heap,(price+p,stop+1,v))
                    elif stop+1<stops[v]:
                        heapq.heappush(heap,(price+p,stop+1,v))
                    
                    
                    if stops[v] == float('inf'):
                        stops[v] = stop+1
                    else:
                        stops[v] = max(stops[v],stop+1)
                    
                    
        
        return -1
```

**Comment by LC-Sue** [comment]
Hi @wblueDean 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @wblueDean 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
