### ISSUE TITLE
Typo in Solution of 84. Largest Rectangle in Histogram

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6199]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[84. Largest Rectangle in Histogram](https://leetcode.com/problems/largest-rectangle-in-histogram/solution/)

In Approach 3, as Screenshot 1, it wrote the wrong result number 16.

#### Expected behavior

It should be 14, which is also the correct answer for the corresponding example.

#### Screenshots

![image](https://user-images.githubusercontent.com/31957845/151653420-6bcc69ca-aaa2-4023-bc68-00d808060d21.png)

#### Additional context

This bug had been mentioned by [Kaiyubo](https://leetcode.com/Kaiyubo/) in the comments on November 14, 2018. But it seems still exists.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
