### ISSUE TITLE
169. Majority Element missing a test case

### ISSUE THREAD

**Issue by m-Just** [LeetCode-Feedback/LeetCode-Feedback#62]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
My erroneous code is accepted. The missed test case I found is `[2,2,3,3,3,3,2]`.

**what language is your code written in**
Python3

**The code you submit/run**
```python
class Solution(object):
    def majorityElement(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        r = []
        while len(nums) > 1:
            m = []
            for j in range(len(nums) // 2):
                i = j * 2
                if nums[i] == nums[i+1]:
                    m.append(nums[i])
            if len(nums) % 2:
                r.append(nums[-1])
            nums = m
        if len(nums):
            return nums[0]
        else:
            return r[0]
```

**Expected behavior**
The above solution should not be accepted because it gives a wrong answer when input is `[2,2,3,3,3,3,2]`.

**Comment by CooperCooperCooper** [comment]
Hi @m-Just,
Thank you for reaching out. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @m-Just,
Thanks to your timely feedback, we've added the missing test case accordingly. Please try the problem out :)
