### ISSUE TITLE
546. Remove Boxes

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#620]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 2 Using DP with Memorization[Accepted] has wrong analysis

#### Expected behavior
Time complexity : O(n^3) dp array of size n^3 is filled

Should be O(n^4) as there is linear work for each state

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
