### ISSUE TITLE
Incorrect solution description of 84. Largest Rectangle in Histogram

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6200]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[84. Largest Rectangle in Histogram](https://leetcode.com/problems/largest-rectangle-in-histogram/solution/)

In Approach 5, the following equation (if we reach the end of the array) in the description is **INCORRECT** and will result in a wrong answer.

> `(stack[top] - stack[top-1]) * a[stack[top]]`, where `stack[top]` refers to the element just popped.

#### Expected behavior

The implementation in Approach 5 (no matter which language) uses a different but correct equation. The equation in the description should be consistent with it.

#### Additional context

Actually, the sliding animation in Approach 5 uses a different equation again, i.e. there are 3 kinds of equations in Approach 5 among description, sliding animation, and implementation.
I think all of these 3 should be consistent, and I'll suggest using the equation of the implementation.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
