### ISSUE TITLE
Missing Test Case - 1460. Make Two Arrays Equal by Reversing Sub-arrays

### ISSUE THREAD

**Issue by chirilam** [LeetCode-Feedback/LeetCode-Feedback#6201]
#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The solution that has 0 ms is wrong and should be taken out as a good solution and a similar test to my test case should be added as a test case.

Following test case doesn't work for that.
[1,2,2,8,8,16]
[1,4,4,4,4,16]

sample 0 ms submission
class Solution {
    public boolean canBeEqual(int[] target, int[] arr) {
        int xorArr = 0;
        int xorTarget = 0;
        int prodTarget = 1;
        int prodArr = 1;
        for(int i = 0; i < arr.length; i++){
            xorArr ^= arr[i];
            xorTarget ^= target[i];
            prodTarget *= target[i];
            prodArr *= arr[i];
        }
        return xorArr == xorTarget && prodTarget == prodArr;
    }
}

#### Language used for code
JAVA

**Comment by LC-Sue** [comment]
Hi @chirilam 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @chirilam 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
