### ISSUE TITLE
Missing Test Case - 232. Implement Queue using Stacks

### ISSUE THREAD

**Issue by myan7** [LeetCode-Feedback/LeetCode-Feedback#6202]
#### ming54

ming54

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I submitted my answer and it passed, but I don't think it is correct enough.
so I created my own test case and run my answer, and it failed as expected.
but it was not included in the 21 existing test cases.

#### Code you used for Submit/Run operation

```
class MyQueue {
    private Stack<Integer> s1 = new Stack<>();
    private Stack<Integer> s2 = new Stack<>();
    int head;

    public MyQueue() {
    }

    public void push(int x) {
        if(s1.isEmpty())
            head = x;
        s1.push(x);
    }

    public int pop() {
        if (s2.isEmpty()) 
        {
            while (!s1.isEmpty())
                s2.push(s1.pop());
        }
        int top = s2.pop();
        if(!s2.isEmpty())
            head = s2.peek();
        return top;
    }

    public int peek() {
        return head;
    }

    public boolean empty() {
        return s1.isEmpty() && s2.isEmpty();
    }
}
```

#### Language used for code

Java

#### Expected behavior

the test case I created was 
["MyQueue","push","push","pop","push","peek","pop","push","pop"]
[[],[1],[8],[],[3],[],[],[5],[]]
expected result is 
[null,null,null,1,null,8,8,null,3]
while my passing answer returns
[null,null,null,1,null,3,8,null,3]

#### Screenshots

proof of accepted answer outputs wrong result.
![image](https://user-images.githubusercontent.com/25088209/151682348-1d6a5b8d-a8e8-4361-a2a7-951cb737b9d9.png)

**Comment by LC-Sue** [comment]
Hi @myan7 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @myan7 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
