### ISSUE TITLE
Invaild Test Case - 56. Merge Intervals

### ISSUE THREAD

**Issue by Rakesh-Bairwa** [LeetCode-Feedback/LeetCode-Feedback#6208]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This following test case is invalid : [[1,4],[2,3]]
Actually it looks valid but the function is automatically erasing [2,3]

#### Code you used for Submit/Run operation

```
// Merge Intervals
class Solution {
public:
    vector<vector<int>> merge(vector<vector<int>>& intervals) {
        return intervals;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It must return the same output for the given input.

#### Screenshots

![ss](https://user-images.githubusercontent.com/65413333/151686598-4cb37636-2d01-4c6f-a2dd-07c9340b3722.png)

**Comment by stormsunshine** [comment]
The two intervals overlap with each other, so they are merged and the result only contains one interval. Is there any problem?
