### ISSUE TITLE
Missing Test Case - 718. Maximum Length of Repeated Subarray

### ISSUE THREAD

**Issue by jhnlynn** [LeetCode-Feedback/LeetCode-Feedback#6209]
#### Your LeetCode username

useless_trash

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An AC solution fails on this test case:
[1,1,1,1,2,3,2,1]
[3,2,1,4,7]

#### Code you used for Submit/Run operation

```java
class Solution {
    public int findLength(int[] nums1, int[] nums2) {
        if (nums1 == null || nums1.length == 0 || 
            nums2 == null || nums2.length == 0) return 0;

        int maxLength = 0;
        for (int offset = 0; offset < nums2.length; offset++) {
            maxLength = Math.max(maxLength, slide(nums2, nums1, offset));
        }

        if (maxLength == Math.min(nums1.length, nums2.length)) return maxLength;

        for (int offset = 1; offset < nums1.length; offset++) {
            maxLength = Math.max(maxLength, slide(nums1, nums2, offset));
        }

        return maxLength; 
    }

    private int slide(int[] stay, int[] move, int offset) {
        int count = 0, maxLength = 0; 
        
        for (int i = 0; i < stay.length; i++) {
            if (i + offset >= move.length) break;
            if (move[i + offset] == stay[i]) {
                maxLength = Math.max(++count, maxLength);
            } else {
                count = 0; 
            }
        }
        return maxLength; 
    }
}
```

#### Language used for code
Java

#### Expected behavior

[1,1,1,1,2,3,2,1]
[3,2,1,4,7]
Result should be 3.

#### Screenshots

<img width="1786" alt="AC_but_should_not" src="https://user-images.githubusercontent.com/61869552/151686761-af4bed16-368c-4928-80b0-244712732a78.png">

**Comment by LC-Sue** [comment]
Hi @jhnlynn 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jhnlynn 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
