### ISSUE TITLE
375. Guess Number Higher or Lower II

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#621]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 3 Using DP [Accepted] has incorrect description

#### Expected behavior
cost(i,j)=pivot+max(cost(i,pivot−1),cost(pivot+1,n))

is wrong. Should be

cost(i,j)=pivot+max(cost(i,pivot−1),cost(pivot+1,j))

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
