### ISSUE TITLE
Ambiguous Problem Description - 2157. Groups of Strings

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6210]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [2157. Groups of Strings](https://leetcode.com/problems/groups-of-strings), which is the 4th question of weekly contest 278, the problem description is ambiguous.

Consider the following test case.

```
["a","b","cde","cdef"]
```

The expected answer for this test case is `[2,2]`, which means `"a"` and `"b"` are in the first group, and `"cde"` and `"cdef"` are in the second group. However, if the four strings are put in the same group, it still meets the definition of a group, since each string is connected to exactly one other string of the group.

Therefore, the description of the problem is faulty. To eliminate the ambiguation, the term "group" should be changed to "connected component". Also, the entire description of the problem should be updated.

I am not putting a complete description of the problem here, but problem 952 can be a reference of how to describe the problem without ambiguation.

**Finally, since the issue of problem description has a strong effect on how to solve the problem, and the issue was not fixed before the contest started, I strongly suggest that this weekly contest should be unrated.**

#### Expected behavior
1. Problem description of 2157 should be updated as mentioned above to remove ambiguity.
2. Since problem 2157 is the 4th question of weekly contest 278 and the faulty problem description strongly affects how to solve the problem, weekly contest 278 should be unrated.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
