### ISSUE TITLE
Edge case is not correct

### ISSUE THREAD

**Issue by shyam6796** [LeetCode-Feedback/LeetCode-Feedback#6211]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
Which problem and which test case? Could you please provide detailed information?

**Comment by LC-Sue** [comment]
Hi @shyam6796 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
