### ISSUE TITLE
1150. Check If a Number Is Majority Element in a Sorted Array

### ISSUE THREAD

**Issue by maniram477** [LeetCode-Feedback/LeetCode-Feedback#6214]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
In the question it is not explicitly mentioned whether array with no majority element can be given as input.  So I've written this solution assuming majority element always exists in the input array nums. Though the solution got Accepted it will fail with the following test case mentioned by @zhoulinda1995 in the [comment
](https://leetcode.com/problems/check-if-a-number-is-majority-element-in-a-sorted-array/discuss/1707808/Python-or-O(1)-Time-and-O(1)-Space-with-index-lookup-or-Provided-Majority-element-exists/1243551)

[2,4,4,5,5,5,6,6,6] 
5

#### Code you used for Submit/Run operation

```
def isMajorityElement(self, nums: List[int], target: int) -> bool:
    condition1 = nums[len(nums)//2] == target
    condition2 = nums[len(nums)//2-1] == target
    condition3 = nums[(len(nums)//2 + 1)%len(nums)] == target

    if len(nums) > 3:
        ans = condition1 and (condition2 and condition3)
    else:
        ans = condition1 and (condition2 or condition3)

    return ans
```

#### Language used for code
Python

#### Expected behavior
The above solution should fail if the existence of a Majority element is not guaranteed but is getting Accepted because of missing test case like the one below

Missing  TestCase: 

[2,4,4,5,5,5,6,6,6]
5
 
#### Screenshots

![1150-Issue](https://user-images.githubusercontent.com/8090429/151711738-5674510e-7071-445a-b489-603a90f1f6fd.png)

#### Additional Context
Few more test cases which dosen't have a majority element can also be added to make test set more comprehensive

TestCase:
[2,4,4,5,5,5,5,6,6,6]
5

**Comment by LC-Sue** [comment]
Hi @maniram477 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @maniram477 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
