### ISSUE TITLE
502. IPO

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#622]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 2: Greedy has wrong description

#### Expected behavior

> Time performance O(NlogN) is not the optimal one for this problem

This is in reference to the first approach which is actually the better solution

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
