### ISSUE TITLE
Incorrect Test Case - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by Fahad-Ashraf44** [LeetCode-Feedback/LeetCode-Feedback#6221]
#### Your LeetCode username
fahadfx
 
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Incorrect Test Case. 

#### Code you used for Submit/Run operation

```
class Solution:
    def maxProduct(self, nums: List[int]) -> int:
        max_product = float("-inf")
        curr_largest = 1
        curr_smallest = 1
        
        for n in nums: 
            if n == 0:
                curr_largest = 1
            tmp = curr_largest
            curr_largest = max(n*curr_largest, n*curr_smallest)
            curr_smallest = min(tmp*n, n)
            max_product = max(n, curr_largest, max_product)
        
        return max_product
```

#### Language used for code

Python3

#### Expected behavior

I believe one of the test cases might be wrong. This is the test case which is using the array:
`[1,0,-1,2,3,-5,-2]`

Expected: `60`
Output: `10`

In this case, I believe there is a sign error. The answer may have resulted from the subarray [-1, 2, 3, -5, -2] which should return -60, not 60. In this case, I believe 10 should be the correct answer because [-5, -2] would be the largest subarray. 

#### Screenshots

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/7116809/151718793-6cf86f1b-4c5b-486e-8706-3b23defe9a7f.png">

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/7116809/151718805-52422994-7900-4b31-99ea-e9ca6ab4d95f.png">

#### Additional context

I believe that the current given solution may be incorrect because it passes this test case.

**Comment by stormsunshine** [comment]
Since you know there is a subarray [-1, 2, 3, -5, -2], why can't you remove the element -1 to get another subarray [2, 3, -5, -2] with product 60?

**Comment by LC-Sue** [comment]
Hi @Fahad-Ashraf44 
Thank you for reaching out to us. I hope stormsunshine's response was able to answer your doubts. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by Fahad-Ashraf44** [comment]
> Since you know there is a subarray [-1, 2, 3, -5, -2], why can't you remove the element -1 to get another subarray [2, 3, -5, -2] with product 60?

Thank you so much, sorry for not seeing that earlier!
