### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Aizhan87** [LeetCode-Feedback/LeetCode-Feedback#6222]
I would like to see an extra column for favorite leetcode problems.
![Screen Shot 2022-01-30 at 2 07 08 PM](https://user-images.githubusercontent.com/47463182/151719967-1765c797-675f-4af6-8b91-6f7e7f2e60de.jpg)

**Comment by LC-Sue** [comment]
Hi @Aizhan87,
Thank you for reaching out to us, please feel free to send your feedback to support@leetcode.com !
