### ISSUE TITLE
Issue in construct a Heap Chapter

### ISSUE THREAD

**Issue by RaghavGarg291900** [LeetCode-Feedback/LeetCode-Feedback#6224]
#### Your LeetCode username
raghavgarg291900

#### Category of the bug
Chapter -   Construct a Heap

#### Description of the bug
As per the Heap explanation a min heap is the one whose root node is the smallest, but here in the data provided the element at position 0 is greater than it's other element, so it's a max heap. But here min heap is written

#### Expected behavior
In the given scenario -it is max heap

#### Screenshots
![image](https://user-images.githubusercontent.com/64372049/151727481-b6a84fa4-3edd-4410-a3c2-5a31ea29a137.png)

#### Additional context
As per the screenshot the data provided is of Max heap, but here min heap is written.

**Comment by LC-Sue** [comment]
Hi @RaghavGarg291900 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
