### ISSUE TITLE
Can Place Flowers lack of explanation in the solution

### ISSUE THREAD

**Issue by SleeplessChallenger** [LeetCode-Feedback/LeetCode-Feedback#6226]
#### Your LeetCode username

SleeplessChallenger

#### Category of the bug
- [ ] Question
- [OK] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is absence of explanation in the article about one point used in the solution

#### Code you used for Submit/Run operation

```
// Can Place Flowers

// Python3
    def canPlaceFlowers(self, flowerbed: List[int], n: int) -> bool:
        count = 0
        
        for i in range(len(flowerbed)):
            if flowerbed[i] == 0:
                if i == 0 or flowerbed[i-1] == 0:
                    if i == len(flowerbed) - 1 or flowerbed[i+1] == 0:
                        flowerbed[i] = 1
                        count += 1
                        
            if count >= n:
                return True
        
        return False

// Kotlin
    fun canPlaceFlowers(flowerbed: IntArray, n: Int): Boolean {
        var count: Int = 0
        
        for(i in 0 until flowerbed.size) {                        
            if(flowerbed[i] == 0) {
                if(i == 0 || flowerbed[i-1] == 0) {
                    if(i == flowerbed.size-1 || flowerbed[i+1] == 0) {
                        flowerbed[i] = 1
                        count += 1
                    }
                }
            }
            
            if(count >= n) {
                return true
            }
        }
        
        return false
    }
}
```

#### Language used for code

Python, Kotlin

#### Expected behavior

So, there are 2 solutions which **differ** according to the article only in one check, i.e. we add check in the **second** solution
```
if(count>=n)
    return true;
```
instead of traversing full array and making ```return count >= n;``` as done in the first solution.

**But**, it's not explained why do we use ```flowerbed[i++] = 1;``` in the **second** solution instead of simple
```flowerbed[i] = 1;```.

I ran both solutions in Java && both worked, **but** In Python and Kotlin `I + 1` produces errors

**Comment by LC-Sue** [comment]
Hi @SleeplessChallenger 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by SleeplessChallenger** [comment]
Thanks for response!

**Comment by LC-Sue** [comment]
Hi @SleeplessChallenger
Thank you for your time. Our team has dded python and c++ implementations and cleaned up the original code, there should be no confusion for non-Java users. We appreciate your support!
