### ISSUE TITLE
 Run Code inconsistent with Submit Solution - 2156. Find Substring With Given Hash Value

### ISSUE THREAD

**Issue by snehel4510** [LeetCode-Feedback/LeetCode-Feedback#6227]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
-[✅]  Run Code inconsistent with Submit Solution

#### Description of the bug

For a given test case, the output shows TLE when I submit my code but when I run the same test case giving it as a custom test case input, then it shows the Correct answer. Kindly address the issue here.

#### Code you used for Submit/Run operation

```cpp
// Find Substring With Given Hash Value
class Solution {
public:
    long long berec(long long a, long long b,int mod)
{
    if (b == 0)
        return 1;

    long long res = berec(a, b / 2,mod);

    if (b % 2 == 0)
        return (res % mod * res % mod) % mod;
    return (a % mod * (res % mod * res % mod) % mod) % mod;
}
    int hash(string s, int p, int m, int k, int v)
    {
        int ans = 0,j=0;
        for(auto i:s)
        {
            int b = i-'a'+1;
            ans += (((b%m)*(berec(p,j,m)%m))%m);
            j++;
        }
        return ans%m==v;
    }
    string subStrHash(string s, int p, int m, int k, int v) {
        string ans;
        for(int i=0;i<s.length()-k;i++)
        {
            string s1="";
            for(int j=i;j<i+k;j++)
            {
                s1+=s[j];
            }
            if(hash(s1,p,m,k,v))
            {
                ans = s1;
                break;
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the given testcase :- "fldweodruaqyopsqarhirscdemnhzjsvnrvxvhdnabhrampqolgaiimfzxlwgkikhvigrfhnsoplgvvmmizvgfvolqfrkagusggwoovxffsdegfolsiwnquddwpxbzvguiqftebdbxcvioqdnwkfagiwceqrqsnkemforanixlsasgtkvovnaonkbnstjsstntuztdnznczpvuzambhcohcolveqizvtyjbvkbumpaktxmbgezmabwfsrgybctfgnnufbklhmrbqtbsdjqxmdwmbsguslsgdpktldvypnmjbxvisbkfpujuwguwncpzuqtckgqttymoqqcglcpjniraulpcjjigtihfbagrrjdzhgmrjbazqwfqluipjycfpraaiispunvuphrixumjfzzyfragxlvlmttmkjnuxsaxryfrxadqkectjsgouphgiitoxzqvzywdeflrpxnaxoaukbnscpmnoudfrpeqoutqjxkzanpbjkgaknvwtyvjfxxsdwaajkvgefdiovvtmcqvpaxflrwesmmamkrxypkwcsexyhpjgxqtnfpvtqzikogzupfgpnkbupuwglthccyrjouuwznobiucvjmymokughhbpkbwoblelqiikzmrlfhmpbkroidqrywahipryzrtsxriszdrtencjoorhtlvxqgqrssnhkpxqkfnkfgkmixnbyvrdoynfhdmzvctqpykdkkfjpdaskqykpuoiewjlkykwjcbatgtmsgmcwrddnakdnztkmndwnxllipndfoyyqyvddktiswhexyiofpucovzqqiygzrpgosrzgrfqpsyambwwhyyqbdpagyjfirweinvgvbmvpinhoiqsmtojahmtxnhonqizuxexcaohreywknxfdezsscqcacaplfdssqvzsyxfqmhthoewzkciujonmpfympxzasmyyvybqargubfslafufzvykwlwlzykqvedamgvwasieuegodorqnkaxbbzcgkuectpyccgtjhyeobqvppbcuhskkwumzdjiplllopfvjaicxuhnmlclfjzzvhgsluwiuirhpiwpmbxvfdxepdneqhwwjvpkgsarserufdtokmbgininjdfeuiskuqtbliebsewqfgijmadrrftxnykmghfvkobsngnwvyiikhakjncnptosphrnmqbnqqjpcwtoyjlcycxpzjaipnntddeztbfzriocnuczqgfhnqxziajfszefqaeqzbpicipjxsrspvekybcjtzfhtqvagvgwvzxhkjstgrppusxltmbwcrhmamwrxawwmrruaeaxxrlxnlaiyvcqndgnreeaegzwwvbvxzdpmjicwolrexpzzhmybyyckvessnykemidxjplodhpbnxtplymdhfwsdaliorsetgnritxkwgroqaenqpydqljvhlzrijlxtulfxtwsbyuyscgzngjgltvvhruadjliuqgrwbnyvgdlmoseokxibiaxlbqjvpnvrepditvpgmruhogublnqqeyxzsajhxzifajcddexfqciqvdolvhiccxyzvjabgsjfxlnkqfuulfdzphkpwyfcfhxzmkawgdukoxfefxvudsrmpeonaxqdvhplvqougrpbqrhixhgqujcqdgeztszztfbfcrfzqlkqnthkkzqnimddpwjcyxqhgzjrdknmhajctwvdvfjewcbikcrwhcovmexeldqbmxxmugdyygtkoihvsfyajpealqsanmndjmozpswraoiziafdscgrctsyggsjitpuwmkqvixfuiubsqgrvjebyevfeaeaszynqibqukdfaghjzbavqabonpccfjocppdxvqphbzxwjqttzdeejowuxiircbqhripbxgapqonytoeaikefbquwwmqncczftixvmfnlwgtiibedybjivuybfgqnzcvrmrlcekpoeblybnbumxkhakbsqrqajlmzfmruuxiddckwqeuxbnksbrtgamtrliyozmdgqewoegeczbroufuntcofjhmitzecpgboyipsawmuxcooypaxlozhxrsvtsehvxoabainzzfanvgptegnavlekliaqwbpyfhagguqpupgualeaexrtxchhfuvnfuvjlbhwxjacgxpmwewjpcmtjhvciumjaxfmmfdvmbqclogssfxmtrmubpkeffybwkbjifanrtnkjdmjxdhqswrobhwwkffhwziccbfnlxjejamshigtnpqtoilrdnzbrasysknpetevxubprqhjuatrseznbdpdizedgnyeizpahckpxqewgtoqfcmllwzjvdwuywhrvmpumqhwurrltnymtqluitkroeiuvzjkzzpqznlbmhpanmirdznkyphhpbzdjslpgscxlpcyafwdjrwysmkqhoyguqbagqzagslyuxdzafewozdbcyryfdahxogzlvfunaqspvokpffyovgieetzthexgyilyujnmnkceebegukhxtydynyxswmmutjwxhqjwnfyefsxfpfxjfjobgpsnabyfbrumtgfiymtepuiinxwcnxpewhobqtfwekbuwqsvhljnauggtlrztmpwolfmaamoweefzqucmkmpuujjanfmegojjuqhmazgushsmyerbgplfmhtjvfwygknpdyfgllslputeyjcqinwhpwuywocrsmbincuicsbynhqgndvqoyydytzodytkytkjdiddmzqakfypxitwpedtxnecjhnpjrkavhmftdzxfmigazprwqvegbhqieehgxhlzxsxkaaravadoborxmplgxezhtdfvesfcufpxlasfrqbzlydojuncmrxrfisvgpbvqeejpeucgsejhxuatoancvnxeroivkqqovhvsczuafccasxzlqweuwqfnmefkqcvyosnahscrfumiedqrjimcpghsgznhmbnvrzqapbiouvcgmfnliyrpwdezjcxrakujlajnqhechhojdcxdvzdxwneszzpaqgafzllvngtfbbyazdpmjdhumoirdybzdevkjbmlswortvjkskdymddtjeieqwyiwroljnbeudthedarxwwlbtwhmenytggjywkkyeekszzteotzhztpxwsvjxmcuuuggujcnuuxnfidqgoumuksbhtlmmlgcjzdgyuirfhkgqgzxafzbzxwvqaelhdmcpyxxiovgmxzsgicwevknzmoyxmzcffkfsnuanmhthshdmvloaygevzcfffdwatbknbhunvknqgrluugjalegfgagdilskvaontebzxrvetkxgjsklwtktxqbkjaedejdkuldiwsoefmvpgxscdauafzovbprfjidiiezuxkffeiqviptllplpmlfbygytpljizogmkmbnzxxygrlqjqaiyfmuxnksxyfjewtlohadyozlnysnpewatxxhgjkcjxcjbkjmzughihfekyfeqkyztayuphqtgedquarlyhqsnxietthgmxxkoblhybdmnsgbrokguvlaumiedufdorgvfriyxojfbsffhsohkdtyqkmxvhohmohnwvxyeflgjyoipvhhoyerxdajnnehtetvapkesbmocazcpesuawjzwzbuwxjebbxnlpkvnrrakgvlowtgsgabazpldownyhppazekddkatpmdaiocmxehziokzbmsjguiijcovzrxxmmnmtvbgjeveuzjfpwhgphjslmmolfqdukbydeasijmzrdvpbgbyjspzrntqjefbxftiveryzxxdpxakchzxqwfnwoywyuvzjyfzrovqymndyxqxqxmoexfgvawmljinaevoyhaoaqptefgridxtwegswtzyksxtuahljmzpjcyodupuwcpqrgisatwiolieytrnvjcrvyykfykbuqgkrdjutaenqtpaomlbplecyglucaqdhliqcmfkrmwfapwlaadpfwkmcqwjwuropeznsybpsbajiblgditzbqndyagfztuvnafdsqakybrrikndjeajdtoywrmfxznhzcbzbsquzvjfwwznsoovqdwwgdobfbaohtojkmnsekyvhhvlqvruffmnqhfynreqipwrjcqlhcsspgpzzkolhyvkgkmdqssgeagoyuzwqfinfwrhyfpbdcnmfjghtqjgqcggcmjkhetiphghsdjmljbdzppxqkkzgjcyftsqqgnfrfzxhbexoaraibwbqunfncrcdoyblkjkghcaxjgflgglhmmgpfatgvjidmqwznqxdphrcqmbgezghiulgpfsnfqkjmquinxoclcihxgdtmzobogdiamvfypukyykrhwwzmnewtcdsehxucsscoasrfpziztwxbxsbtipbhwxbxqgvlbtszusmazgkabbuitmsoigrxglevypchqnimkrccvowbdiqhwdxapfkrnjvpmkhjjyefscsfhkmorqqdajawijvjpsaqywstrcrnyvkbqducqryenilmcabawfvythmstwistlellhbrygpdsdxpoalwyrquhyjpbgctcrgxdbgwdncpsedrkivyhzuwcsqydkvcsuvalhbyswvvetajsqkexoyhwxfozywifslopkrxtpayxyywpkphuanwhhnlcsuwlnbflwmulbimrxjsuuzdmmvxsgnproxckvtyujshldvdcdkyvxfndtomjcjsngtjbivoyxrdlpdudhkvsdxwgcjrjkszafteuyqsalxirhflaybyvpkdtdvyplqhdifrylwtlsogspaebsnaoocbriqmowbxnrawwucahdovajtjctqpwrntjxzqfuolvopgyiqnaodxquydtykcgiwawghpjpurfuozigeqicgptiklgyoipfvtnmnmkgtgtjgdmafhlqbuftwjcbxrvsxektzpcrdgpbxojhzhmrwkxqgfafvhzkvfakxipzqsvrfbctydmcfolaehpeglgaaabgtgvjdoobccynqgddlplnqmrrbtdudoyfbvdiqeczbczggichyaupnabfzabbxucqlnzhynwayainzldkpxtjamhyqscnfnynjdodalezivkyamwqcpuaofmvufxgtrnwcfrgxkmioyochujdfvxggqsrpsktyekvoqkcgczyamsqeooowouvjytqnnzxsgyrieypbyldleccwntffuotowxbblxcwludytmgrpvyrceqsqicrjtwrhynhkmaztrrwvrzfourbqqtrdcvlmglwxdwkfwjpiriujrkrpvhavnbtnuuugzygqhvonboswszkckxwrdrxfxzbctneqmmpvewvgmwrfnevlxkoerpuhihoqgskypbjftogkaisbzpibcstoxlanpdzqpbigfjsjywgganfyeuhylrotgpuuyjqstzhgtehorqbumcmfirdkjdwegvmcnqqbumrvhvutahjtcrbjzzqleojcvkgzqktcbqhxikbzutqnndvffukmrtyjammamkrlbvkxwqopwozbjlgqynixwszibokvhcrxrbncihthrhnoynegjnhfeeuiwtpnudyqjbmqqaydzolrjdjvzywcmsbegahcfxzejxyaolntzbjngvqmqrchbhaxotvkvidruzosamlmrgforfipegxtarbctmgbfnlrkamrsczxpyxfjtlszjfehwkvlmfckawdkxoeoqslqeztrdmhtrcbwtftzposqdilnplpxdevukhndljkfckwcndfeuygnmllfnukmzxkkprtcgxthrslyebbxihwhojvaevvmgvixigfsxnlfflfjqyiufiajzodsnytxcubbjdfogemxgijtkledpvjjpuacbpeoasqjlhkfxldqyehcrdyieehbuxedrdsxoixuyjnuqmdiifqwyrxbopuvipcecftjarqzttqqjuuvsvysonhdfxaomhmffgyqlikksducmkftfljgcfjoogcmysemhmmsmxbeeogmyoivgxpedoycrxpqzmuchecybeurqkkfchnzotvpecmiqsvjeqmajzvmgcxgonvrjsorjsnyzfbwksttdcpamhbvpsbgbprgcptrwavoueachjructpwedtmbezezteofzacabsscrrfkedgppjarisfbhjhyiaggpcmvrpntnfsuuwkemuhgaecoxiztenobsjkonbtzzckuheoralvbxiaojvfsrtmabwgxetggmatuecxsracvboovugmbxtqwdmrcolsdkhchvwtyuzxcshnxsdzniujgfzpuutfrhadrjjiyorymblevqcjyjebnbemmrtbknnqenpasqlruelzolltuivsvqhjlxvhzripoljledoaiwiwgulrnwwfzihhmbxohlaukwjnpxvbgk"
46556
84395
809
28704
Correct output is :- "nehtetvapkesbmocazcpesuawjzwzbuwxjebbxnlpkvnrrakgvlowtgsgabazpldownyhppazekddkatpmdaiocmxehziokzbmsjguiijcovzrxxmmnmtvbgjeveuzjfpwhgphjslmmolfqdukbydeasijmzrdvpbgbyjspzrntqjefbxftiveryzxxdpxakchzxqwfnwoywyuvzjyfzrovqymndyxqxqxmoexfgvawmljinaevoyhaoaqptefgridxtwegswtzyksxtuahljmzpjcyodupuwcpqrgisatwiolieytrnvjcrvyykfykbuqgkrdjutaenqtpaomlbplecyglucaqdhliqcmfkrmwfapwlaadpfwkmcqwjwuropeznsybpsbajiblgditzbqndyagfztuvnafdsqakybrrikndjeajdtoywrmfxznhzcbzbsquzvjfwwznsoovqdwwgdobfbaohtojkmnsekyvhhvlqvruffmnqhfynreqipwrjcqlhcsspgpzzkolhyvkgkmdqssgeagoyuzwqfinfwrhyfpbdcnmfjghtqjgqcggcmjkhetiphghsdjmljbdzppxqkkzgjcyftsqqgnfrfzxhbexoaraibwbqunfncrcdoyblkjkghcaxjgflgglhmmgpfatgvjidmqwznqxdphrcqmbgezghiulgpfsnfqkjmquinxoclcihxgdtmzobogdiamvfypukyykrhwwzmnewtcdsehxucsscoasrfpziztwxbxsbtipbhwxbxqgvlbtszusmazgkabbu"

When i run my code giving the test case as custom input, it shows correct output but when i submit my code i recieve TLE.

#### Screenshots

![image](https://user-images.githubusercontent.com/79275152/151830655-1206d190-afce-4af0-9ac2-8c61a2dc77c8.png)

**Comment by LC-Sue** [comment]
Hi @snehel4510 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
