### ISSUE TITLE
No set of new questions for weekly premium

### ISSUE THREAD

**Issue by allen-tran** [LeetCode-Feedback/LeetCode-Feedback#6228]
#### Your LeetCode username

allentran

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A new month of weekly premiums has begun however there is no new set of questions. Please see attached photo below.

#### Screenshots

<img width="253" alt=" 2022-01-31 at 9 03 46 AM" src="https://user-images.githubusercontent.com/63386979/151839074-22586252-45dd-4797-9e88-d773a92b5abd.png">

**Comment by imdominicreed** [comment]
![image](https://user-images.githubusercontent.com/13471482/151843868-81d32766-778d-4273-83ff-530d40b1aaa3.png)
This bug seems to be happening for me as well.

**Comment by LC-Sue** [comment]
Hi @allen-tran,
Thank you for reaching out to us, the new set of problems have been updated!
