### ISSUE TITLE
311. Sparse Matrix Multiplication

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#623]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Contradictory description and test cases

#### Expected behavior
The description shows this [link](https://en.wikipedia.org/wiki/Sparse_matrix) for sparse matrices

> Using those definitions, a matrix will be sparse when its sparsity is greater than 0.5.

This is a quote from there.

According to that these are all invalid cases

```
[[1,-5]]
[[12],[-1]]
```

```
[[0]]
[[1]]
```

```
[[1,0,0],[-1,0,3]]
[[7,0,0],[0,0,0],[0,0,1]]
```

It is probably better to remove the potentially misleading link rather than changing the test cases.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 ,
Thanks for your time. After the team reviewed the feedback, we decided not to make update since there is no need to use literally the definition in order to solve the problem, besides these test cases are very small compared to the size that needs the sparsity definition. Thank you!
