### ISSUE TITLE
Find a mistake in the video explanation

### ISSUE THREAD

**Issue by HanCai98** [LeetCode-Feedback/LeetCode-Feedback#6231]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
void union(x, y):
    rootX = root(x)
    rootY = root(y)
    if rootX != rootY:
        root[rootY] = rootX
```

#### Change the mistake

```
if rootX != rootY:
        root[rootY] = rootX
```

**Comment by LC-Sue** [comment]
Hi @HanCai98 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @HanCai98
Thank you for your time. There is a clarifying note under this video that addresses this issue. We appreciate your support!
