### ISSUE TITLE
Getting wrong answer 

### ISSUE THREAD

**Issue by kapil4457** [LeetCode-Feedback/LeetCode-Feedback#6232]
#### Your LeetCode username

Username : kapilsoni54768161

#### Category of the bug

- [ ] Missing Test Cases 
 

#### Description of the bug
In the question it is clearly mentioned that the peak element should be strictly greater than its neighbor and nums[-1] = nums[n] ,but for the test case of [ 2,1,2] it is not following this rule...here 2 is equal to 2 not greater than 2...here the answer should be -1 but it is giving the answer as 0 .. Please check it out
Link to the question is : https://leetcode.com/problems/find-peak-element/

#### Code you used for Submit/Run operation

``` 
class Solution {
    public int findPeakElement(int[] nums) {
         int start = 0;
        int end = nums.length - 1;
        if (nums.length == 1) {
            return 0;
        }
        
        if(nums.length ==2){
            if(nums[0]>nums[1]){
                return 0;
            }
            else{
                return 1;
            }
        }
        
        while (start < end) {
            int mid = start + (end - start) / 2;


            if (start - 1 == -1 || end + 1 == nums.length) {

                if (nums[mid] > nums[mid + 1] && nums[mid] > nums[mid - 1]) {
                    return mid;

                }


                if (nums[start] > nums[end] && nums[start] > nums[start + 1]) {
                    return start;
                } else {
                    start++;
                }
                if (nums[end] > nums[end - 1] && nums[end] > nums[0]) {
                    return end;
                } else {
                    end--;
                }
            } else {

                if (nums[mid] > nums[mid + 1] && nums[mid] > nums[mid - 1]) {
                    return mid;

                }

                if (nums[start] > nums[start - 1] && nums[start] > nums[start + 1]) {
                    return start;
                } else {
                    start++;
                }
                if (nums[end] > nums[end - 1] && nums[end] > nums[end + 1]) {
                    return end;
                } else {
                    end--;
                }
            }


        }
        return -1;
    }
}

```

#### Language used for code
Java

#### Expected behavior
Expected behaviour should be that it must return -1

**Comment by stormsunshine** [comment]
Why do you think index -1 equals index n - 1 and index n equals index 0? Both indices -1 and n - 1 are beyond the bounds.

Therefore, the array [2,1,2] is equivalent to [-∞,2,1,2,-∞], where the values -∞ are at indices -1 and 3, and either 0 or 2 is an expected answer.

**Comment by LC-Sue** [comment]
Hi @kapil4457,
Thank you for reaching out to us, please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
