### ISSUE TITLE
Solution review

### ISSUE THREAD

**Issue by kapil4457** [LeetCode-Feedback/LeetCode-Feedback#6233]
#### Your LeetCode username

Username : kapilsoni54768161

#### Category of the bug
- [ ] Solution

#### Description of the bug

In this question , we can say that k =speed , sum of array given = target to be reached = distance , and h =time...so if we apply the formula should get the answer..but the answer it is giving makes no sense...for example : 
Input: piles = [30,11,23,4,20], h = 5
Output: 30.
In this why does koko have to eat 30 bananas per hour to eat all before reaching h=5...it can be done at a speed of eating 18 bananas per hour too...In the question it is asked to give the minimum speed which in this case is 18....because 18*5 =90 which is closest to the total number of bananas present...

#### Code you used for Submit/Run operation

```
class Solution {
    public int minEatingSpeed(int[] piles, int h) {
    int sum = 0;

        for (int i = 0; i < piles.length; i++) {
            sum += piles[i];
        }
//        System.out.println(sum);
        int remainder = sum % h;
        int div = sum / h;
//        System.out.println(div);
//        System.out.println(remainder);
        if (remainder != 0) {
            div += 1;
            return div;
        }

        return div;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Expected behavior of this is to return the minimum number of banana that kok0 has to eat per hour...

**Comment by stormsunshine** [comment]
Did you read the problem description carefully? The problem mentions that: 
> If the pile has less than `k` bananas, she eats all of them instead and will not eat any more bananas during this hour.

That is to say, in the same hour, Koko only eats bananas from the same pile, and does NOT eat bananas from two or more piles.

For the example, Koko must eat all bananas in one pile for each hour, so the answer has to be 30. If Koko eats fewer than 30 bananas in each hour, then it takes at least two hours to finish eating the first pile of bananas, and it takes at least one hour to eat each of the remaining piles of bananas, so it is impossible to finish eating the bananas in 5 hours.

**Comment by LC-Sue** [comment]
Hi @kapil4457,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! We appreciate your support!
