### ISSUE TITLE
No.121 Approach 1 cannot pass the test

### ISSUE THREAD

**Issue by wallacezzzzz007** [LeetCode-Feedback/LeetCode-Feedback#6234]
Hi,

i tried the [No.121 Best time to buy and sell stock problem](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/solution/), but in the solution, the first approach cannot pass the large data test, the web shows "time out"

could u check this plz?

thanks

**Comment by LC-Sue** [comment]
Hi @wallacezzzzz007 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
