### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by MinyiS** [LeetCode-Feedback/LeetCode-Feedback#6236]
#### Your LeetCode username
 MinyiS

#### Category of the bug
- [ ] Question
- [1 ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

213
[12,28,83,4,25,26,25,2,25,25,25,12]
My answer is 7. 25+25+25+25+26+28+83=237>target
It tells me the answer is 8.

#### Code you used for Submit/Run operation

class Solution {
    public int minSubArrayLen(int target, int[] nums) {
        if(nums.length==1) return target<nums[0]?1:0;
        int sum=0;
        int index=0;
        Arrays.sort(nums);
        if(nums[nums.length-1]>=target)return 1;
        for(int i:nums){
            sum+=i;
        }
        if(sum<target) return 0;
        if(sum==target) return nums.length;
        for(int i=1;i<nums.length;i*=2){
            int minus=nums[0];
            for(int j=1;j<=i;j++){
                minus+=nums[j];
            }
            index=i;
            while(sum-minus<target){
                index--;
                minus-=nums[index];
            }
            if(index!=i) return nums.length-index-1;
        }
        return nums.length;
    }
}

#### Language used for code
 Java

**Comment by stormsunshine** [comment]
This problem requires returning the size of the shortest subarray, not subsequence. A subarray must be consecutive while a subsequence is not required to be consecutive.

**Comment by LC-Sue** [comment]
Hi @MinyiS,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Thank you for you support!
