### ISSUE TITLE
Missing Test Case - 322. Coin Change

### ISSUE THREAD

**Issue by jmcguire** [LeetCode-Feedback/LeetCode-Feedback#6241]
#### Your LeetCode username
justinmcguire

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
[3,5]
11

#### Code you used for Submit/Run operation

```
func coinChange(coins []int, amount int) int {
	sort.Ints(coins)

	coinsNeededFor := make(map[int]int) // map of amount => number of coins needed for that amount
	coinsNeededFor[0] = 0

	for _, coin := range coins { // max 12
		for a := coin; a <= amount; a++ { // max 10,000
			// number of coins to make up this amount
			numberOfCoins := a / coin
			missingAmount := a - (numberOfCoins * coin)

			// a = coin * numberOfCoins + missingAmount

			if v, ok := coinsNeededFor[missingAmount]; ok {
				coinsNeededFor[a] = numberOfCoins + v
			}
		}
	}

	if r, ok := coinsNeededFor[amount]; ok {
		return r
	} else {
		return -1
	}
}
```

#### Language used for code
go

#### Expected behavior

These test cases were failing for me (among others), but it was hard for me to wrap my head around why.

[186, 419, 83, 408]
6249

[3, 7, 405, 436]
8839

[431, 62, 88, 428]
9084

The numbers are large, the correct answers are in the 20s, and it's hard to step through any algorithm with these test cases like these to see what's going wrong.

When I figured out where the bug was in my code (which is copied above) and got my intuition down, I created this simpler test case to capture the bug.

[3,5]
11

This test case won't capture anything that isn't already captured by other tests, it's just a smaller one that's easy to wrap my head around, and it may help other people too.

#### Screenshots

na

#### Additional context

na

**Comment by stormsunshine** [comment]
Your code already gets Wrong Answer, so there is no test case that needs to be added.

For why your code is incorrect, please refer to the discussion section.

**Comment by LC-Sue** [comment]
Hi @jmcguire,
Thank you for reaching out to us, please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
