### ISSUE TITLE
Missing Test Case - 62. Unique Paths

### ISSUE THREAD

**Issue by ravitejarekula** [LeetCode-Feedback/LeetCode-Feedback#6242]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

#### Description of the bug :
Testcase where m=16, n=16 should be added in submit testcases because with my solution for this testcase variable is overflowing and getting wrong answer. but when i did submit, it passed and accepted.

#### Code you used for Submit/Run operation

```
class Solution {
    public int uniquePaths(int m, int n) {
        if(m==1 || n==1) return 1;
        if(m==2 || n==2) return (m*n)/2;
        
        long numerator=0, denominator=0;
        if(m>n) {
            numerator = limitFactorial(m+n-2, m-1);
            denominator = limitFactorial(n-1,1);
        } else {
            numerator = limitFactorial(m+n-2, n-1);
            denominator = limitFactorial(m-1,1);
        }
        return (int)(numerator/denominator);
    }
    
    private long limitFactorial(long start, long end) {
        if(start==end) return 1;
        return start*limitFactorial(start-1,end);
    }
}
```

#### Language used for code
Java

#### Expected behavior
When submitted it should also check m=16, n=16 testcase.. some solutions may fail at this testcase.
But, current testcases may not fail the solution when submitted even though it could not pass the above testcase.

#### Additional context
https://leetcode.com/submissions/detail/632391496/

**Comment by LC-Sue** [comment]
Hi @ravitejarekula 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ravitejarekula 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
