### ISSUE TITLE
Missing Test Case - 2156. Find Substring With Given Hash Value

### ISSUE THREAD

**Issue by FatlirT** [LeetCode-Feedback/LeetCode-Feedback#6244]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @FatlirT 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
