### ISSUE TITLE
15. 3Sum Problem Testcase Issue

### ISSUE THREAD

**Issue by gengyuntx** [LeetCode-Feedback/LeetCode-Feedback#6245]
please check the [0,0,0] test case. It should return [] but it asks for [0,0,0]. This is wrong because the problem asks for i != j etc...

**Comment by stormsunshine** [comment]
This problem requires that indices must be different, not that values must be different. Although the values are the same, the indices are indeed different.

**Comment by gengyuntx** [comment]
oops sorry you are correct. Thank you.
