### ISSUE TITLE
Need to Enhance Constraints - 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6246]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [373. Find K Pairs with Smallest Sums](https://leetcode.com/problems/find-k-pairs-with-smallest-sums), the maximum value of `k` is not large enough, and a solution with time complexity O(k<sup>2</sup> log k) can get passed. This solution is as follows.

Since both arrays nums1 and nums2 are sorted in ascending order, to get the k pairs with smallest sums, only consider at most k smallest elements of each array. These elements form k<sup>2</sup> pairs. Use an array list to store the k<sup>2</sup> pairs, sort the list, and return the first k pairs after sorting. Since sorting an array list with size n has time complexity O(n log n), sorting an array list with size k<sup>2</sup> has time complexity O(k<sup>2</sup> log k<sup>2</sup>) = O(2k<sup>2</sup> log k) = O(k<sup>2</sup> log k).

There also exists a solution that uses a priority queue instead of sorting, where the priority queue contains only the k pairs with smallest sums. However, since there are still k<sup>2</sup> pairs, the solution that uses a priority queue also has time complexity O(k<sup>2</sup> log k).

I think that the solution with time complexity O(k<sup>2</sup> log k) is too easy and does not meet the difficulty Medium. Since this is a Medium problem, solutions with lower time complexities should be required. For example, a solution with time complexity O(k log k) exists, and this should be one of the intended solutions.

To make the O(k<sup>2</sup> log k) solution get TLE, the maximum value of k should be changed to 10<sup>4</sup> or 10<sup>5</sup>, and at least one test case where k equals the maximum possible value should be added.

I am not providing a test case here. I believe there must exists at least one test case where both arrays nums1 and nums2 have length 10<sup>5</sup> (the maximum possible value). Just copy one such test case and change the value of k to the maximum possible value (10<sup>4</sup> or 10<sup>5</sup>) to create such a test case.

**If it is believed that the current constriants do not need to be changed, please provide the maximum time complexity of the intended solution.**

**If this problem is designed to accepted a solution with time complexity O(k<sup>2</sup> log k), which is storing the smallest k<sup>2</sup> pairs and sorting, then I believe the difficulty of this problem should be changed to Easy.**

#### Code you used for Submit/Run operation
The following code has time complexity O(k<sup>2</sup> log k).

```Java
class Solution {
    public List<List<Integer>> kSmallestPairs(int[] nums1, int[] nums2, int k) {
        int length1 = Math.min(nums1.length, k);
        int length2 = Math.min(nums2.length, k);
        List<List<Integer>> pairs = new ArrayList<List<Integer>>();
        for (int i = 0; i < length1; i++) {
            for (int j = 0; j < length2; j++) {
                List<Integer> pair = new ArrayList<Integer>();
                pair.add(nums1[i]);
                pair.add(nums2[j]);
                pairs.add(pair);
            }
        }
        Collections.sort(pairs, (a, b) -> (a.get(0) + a.get(1) - b.get(0) - b.get(1)));
        return pairs.size() > k ? pairs.subList(0, k) : pairs;
    }
}
```

The following code has time complexity O(k log k).

```Java
class Solution {
    public List<List<Integer>> kSmallestPairs(int[] nums1, int[] nums2, int k) {
        PriorityQueue<int[]> pq = new PriorityQueue<int[]>((a, b) -> nums1[a[0]] + nums2[a[1]] - nums1[b[0]] - nums2[b[1]]);
        List<List<Integer>> pairs = new ArrayList<List<Integer>>();
        int length1 = Math.min(nums1.length, k);
        int length2 = nums2.length;
        for (int i = 0; i < length1; i++) {
            pq.offer(new int[]{i, 0});
        }
        for (int i = 0; i < k && !pq.isEmpty(); i++) {
            int[] pairIndices = pq.poll();
            int index1 = pairIndices[0], index2 = pairIndices[1];
            List<Integer> pair = new ArrayList<Integer>();
            pair.add(nums1[index1]);
            pair.add(nums2[index2]);
            pairs.add(pair);
            if (index2 + 1 < length2) {
                pq.offer(new int[]{index1, index2 + 1});
            }
        }
        return pairs;
    }
}
```

#### Language used for code
Java

#### Expected behavior
1. Change the maximum value of k to 10<sup>4</sup> or 10<sup>5</sup>, and add at least one test case where k equals the maximum possible value.
2. If the constraints are not changed, please provide the maximum time complexity of the intended solution.
3. If this problem is designed to accepted a solution with time complexity O(k<sup>2</sup> log k), then change the difficulty of this problem to Easy.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback and raised the value of K. We appreciate your support!
