### ISSUE TITLE
Misleading Time Complexity - 438. Find All Anagrams in a String

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6247]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[438. Find All Anagrams in a String](https://leetcode.com/problems/find-all-anagrams-in-a-string/)

The implemented algorithm will ensure that `N_s >= N_p`, so the given time complexity `O(N_s + N_p)` in both approaches can be simplified to `O(N_s)`.

#### Expected behavior

The time complexity in both approaches becomes `O(N_s)`

#### Additional context

I think replacing `N_s` with `M` and `N_p` with `N` will be easier to view.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
