### ISSUE TITLE
Typo - 438. Find All Anagrams in a String

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6248]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[438. Find All Anagrams in a String](https://leetcode.com/problems/find-all-anagrams-in-a-string/)

In Approach 2, `0` for `a`, `1` for `b`, ..., `26` for `z`?

#### Expected behavior

It's `25` for `z`.

#### Screenshots

![image](https://user-images.githubusercontent.com/31957845/152129993-8fbd3f04-1376-4621-9941-e4cefdcb16f3.png)

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
