### ISSUE TITLE
772. Basic Calculator III

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#625]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Problem description

#### Expected behavior

> The expression string may contain open ( and closing parentheses ), the plus + or minus sign -, non-negative integers and empty spaces .

What does non-negative integers even mean here? The input is string not an integer. Even if you ignore that these test cases contradict this

```
"1 - (-7)"
```

```
"-1+4*3/3/3"
```

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
