### ISSUE TITLE
Typo in "A Framework for DP Problems" under "Strategic approach to DP"

### ISSUE THREAD

**Issue by Jatin103** [LeetCode-Feedback/LeetCode-Feedback#6251]
#### Your LeetCode username
jatin98

#### Category of the bug
- [0] Language

#### Description of the bug
**Typo** -> "The equation \text{dp(i) = dp(i - 1) + dp(i - 2)}dp(i) = dp(i - 1) + dp(i - 2) on its **known** will continue forever to negative infinity. We need base cases so that the function will eventually return an actual number." 

It should be 'own' instead of 'know'

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/26847263/152207964-cec79bf4-1530-41f9-8d2e-41dc69dd2fcd.png)

**Comment by LC-Sue** [comment]
Hi @Jatin103 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
