### ISSUE TITLE
Bug - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by jaisw7** [LeetCode-Feedback/LeetCode-Feedback#6253]
#### Your LeetCode username
jaisw7

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Testing method

#### Description of the bug
There is a loophole in the testing procedure. See the code below that passed all the tests.

#### Code you used for Submit/Run operation
```
static TreeNode* _r = nullptr;

class Codec {
public:
    
    // Encodes a tree to a single string.
    string serialize(TreeNode* root) {
        _r = root;
        return "";
    }

    // Decodes your encoded data to tree.
    TreeNode* deserialize(string data) {
        return _r;
    }
};
```

#### Language used for code
C++

#### Screenshots
<img width="1257" alt="Screen Shot 2022-02-02 at 2 07 49 PM" src="https://user-images.githubusercontent.com/26517937/152221119-dc59a410-07de-4b5f-ac19-d7040eb313ae.png">

**Comment by stormsunshine** [comment]
LeetCode platform can't forbid this solution. However, I think that the problem description should mention that the solution must be stateless. That is to say, although the solution mentioned in this issue can get accepted on LeetCode platform, it can't be accepted during an interview.

**Comment by jaisw7** [comment]
I think we can circumvent this issue by compiling two binaries. 
- The first one should instantiate the class, and call the serialize function. The resulting string can then be written to a file. 
- The second one should read the file, instantiate the class, and call the deserialize function. The output from the deserialize should be then compared with the expected output.

**Comment by LC-Sue** [comment]
Hi @jaisw7 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jaisw7,
Thank you for your time, our team as reviewed this issue and the code is ok to pass. We appreciate your support!
