### ISSUE TITLE
Runtime Error originating from __Driver__.Main() - 701. Insert into a Binary Search Tree

### ISSUE THREAD

**Issue by fadyanwar** [LeetCode-Feedback/LeetCode-Feedback#6258]
#### Your LeetCode username
fadyanwar

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I'm getting the below exception when submitting my code which runs correctly against the provided test cases

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Line 35: __Driver__.Main(String[] args) in __Driver__.cs

Which as it appears comes from the Main() in a class called __Driver__.cs that is used by LeetCode to run the solution code against test cases. As obviously my submitted code below does not include a Main(), a __Driver__ class, nor a 35th line where the exception is originating.

#### Code you used for Submit/Run operation
```
public class Solution {
    public TreeNode InsertIntoBST(TreeNode root, int val) {
        TreeNode node = new TreeNode(val);
        InsertNode(root, node);
        return root;
        
    }
    private void InsertNode(TreeNode currentNode, TreeNode node)
    {
        if(node.val > currentNode.val)
            if(currentNode.right == null)
                currentNode.right = node;
            else InsertNode(currentNode.right, node);
        else if(currentNode.left == null)
            currentNode.left = node;
        else InsertNode(currentNode.left, node);
    }
}
```

#### Language used for code
C#

#### Expected behavior
Get test cases results not a runtime error from a function that doesn't belong to my code

**Comment by LC-Sue** [comment]
Hi @fadyanwar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @fadyanwar,
Thank you for your time. The error comes from the code from the private function InsertNode when the function accesses an empty tree. A simple if condition to check the empty tree is sufficient to make this accepted. We appreciate your support!

**Comment by fadyanwar** [comment]
Hello, not sure how this resolves the issue as the exception is raised from a line that is not within the submitted answer.
