### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by pranavimadala** [LeetCode-Feedback/LeetCode-Feedback#6259]
### anjala_madala
![Screenshot (253)_LI](https://user-images.githubusercontent.com/34127558/152255934-efc204a0-d67b-48c8-b929-9974c521b21e.jpg)
Found this !

**Comment by LC-Sue** [comment]
Hi @pranavimadala 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
