### ISSUE TITLE
351. Android Unlock Patterns

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#626]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Link broken in problem description

#### Expected behavior

> You can find the optimized solution here.

The link given does not work. This [solution](https://leetcode.com/problems/android-unlock-patterns/discuss/82463/Java-DFS-solution-with-clear-explanations-and-optimization-beats-97.61-(12ms)) is a viable alternative.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
