### ISSUE TITLE
Incorrect problem description on problem 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by imdominicreed** [LeetCode-Feedback/LeetCode-Feedback#6260]
#### Your LeetCode username

stinkywaffles

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On https://leetcode.com/problems/set-matrix-zeroes/, it says in the problem description "return the matrix."  However, you are returning void in the problem.

#### Expected behavior

Should be "Given an m x n integer matrix matrix, if an element is 0, set its entire row and column to 0's.

You must do it [in place](https://en.wikipedia.org/wiki/In-place_algorithm)."

#### Screenshots

![image](https://user-images.githubusercontent.com/13471482/152292027-a227f265-f8e6-415e-b58d-833f7865a8a0.png)

#### Additional context

Just a mistake in the problem description.

**Comment by LC-Sue** [comment]
Hi @imdominicreed 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @imdominicreed 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
