### ISSUE TITLE
Typo 227. Basic Calculator II

### ISSUE THREAD

**Issue by cvvspb** [LeetCode-Feedback/LeetCode-Feedback#6261]
#### Your LeetCode username
chvv

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Backslash instead of slash:

> We know that there could be 4 types of operations - addition (+), subtraction (-), multiplication (*) and division (/). Without parenthesis, we know that, multiplication (*) and **(\)** operations would always have higher precedence than addition (+) and subtraction (-) based on operator precedence rules.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @cvvspb 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
