### ISSUE TITLE
Please reduce the description of question 26. Remove Duplicates from Sorted Array. It's too lengthy.

### ISSUE THREAD

**Issue by PradeepRaoK** [LeetCode-Feedback/LeetCode-Feedback#6262]
The description of question is too long.

**Comment by stormsunshine** [comment]
Why do you think description being too long is an issue?

**Comment by PradeepRaoK** [comment]
I thought the description length could be reduced.

**Comment by PradeepRaoK** [comment]
Okay sorry for that I would close the issue.
