### ISSUE TITLE
Need to Reduce Constraints - 1675. Minimize Deviation in Array

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6263]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [1675. Minimize Deviation in Array](https://leetcode.com/problems/minimize-deviation-in-array), the intended solution has time complexity O(n × log n × log m), where n is the length of the array nums and m is the maximum element of the array nums. This can be seen in [issue 1577](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1577).

However, since the maximum value of n is 10<sup>5</sup> and the maximum value of m is 10<sup>9</sup>, a solution with time complexity O(n × log n × log m) may have up to about 5 × 10<sup>7</sup> operations for a single test case. This number of operations is too large and it is very likely to get TLE for some specific test cases.

To make sure that time complexity O(n × log n × log m) gets accepted and does not get TLE, the maximum values of both values n and m should be reduced. For example, n should be at most 5 × 10<sup>4</sup> (50000) or 10<sup>4</sup> (10000) and nums[i] should be at most 10<sup>8</sup> or 10<sup>7</sup>. The values should be chosen to make sure that time complexity O(n × log n × log m) does not get TLE.

After the constraints are modified, the test cases that do not meet the new constraints should be removed.

Take the following test case as an example, where the array has length 100000 and all elements are 2<sup>29</sup> = 536870912.

[1675.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7994143/1675.txt)

**Note that I am NOT requiring to add a test case. I am only using the test case to illustrate that the solution can possibly get TLE so the constraints should be reduced.**

#### Code you used for Submit/Run operation
```Java
class Solution {
    public int minimumDeviation(int[] nums) {
        PriorityQueue<Integer> pq = new PriorityQueue<Integer>((a, b) -> b - a);
        int minNum = Integer.MAX_VALUE;
        for (int num : nums) {
            if (num % 2 != 0) {
                num *= 2;
            }
            pq.offer(num);
            minNum = Math.min(minNum, num);
        }
        int minDeviation = pq.peek() - minNum;
        while (pq.peek() % 2 == 0) {
            int num = pq.poll() / 2;
            pq.offer(num);
            minNum = Math.min(minNum, num);
            minDeviation = Math.min(minDeviation, pq.peek() - minNum);
        }
        return minDeviation;
    }
}
```

#### Language used for code
Java

#### Expected behavior
1. Make sure that time complexity O(n × log n × log m) gets accepted and does not get TLE. The maximum values of both values n and m should be reduced. For example, n should be at most 5 × 10<sup>4</sup> (50000) or 10<sup>4</sup> (10000) and nums[i] should be at most 10<sup>8</sup> or 10<sup>7</sup>.
2. After the constraints are modified, the test cases that do not meet the new constraints should be removed.

#### Screenshots
The following screenshot shows the result of the custom test case above. It can be seen that it took 1368ms to execute the test case, which is too long for a single test case, and the standard program even did not produce a result.
![image](https://user-images.githubusercontent.com/12067364/152334821-2a09fab4-bd7a-4bba-b74a-003e59edde4a.png)

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for your time, our team has reviewed your report and decided that the current constraints are fine. We appreciate your support!

**Comment by stormsunshine** [comment]
@LC-Sue I don't think the current constraints are fine. Please refer to the following comment.

https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1577#issuecomment-754864654

In this comment, it was mentioned that the constraints would be changed. However, the constraints haven't been changed until now.

If you agree that time complexity O(n × log n × log m) is expected, then the current constraints may cause TLE. How can you accept such a case where an expected time complexity gets TLE?

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
I understand the comment you mentioned. However, I've relayed this feedback over to our team and the team has decided that the current constraints are fine and do not need to be changed. Sorry for any miscommunication!
