### ISSUE TITLE
454. 4Sum II - Python Solution using language keyword for variable name

### ISSUE THREAD

**Issue by PyroGenesis** [LeetCode-Feedback/LeetCode-Feedback#6265]
#### Your LeetCode username

burhanlakda

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A very simple issue which should be easy to fix:
Approach 2: kSum II uses `sum` as an argument name which is reserved in Python3
This should be renamed to `sum2` or `total` or something similar.

#### Code you used for Submit/Run operation

I'll put in the Solution code as a reference
```py
class Solution:
    def fourSumCount(self, A: List[int], B: List[int], C: List[int], D: List[int]) -> int:
        m = {}

        def nSumCount(lists: List[List[int]]) -> int:
            addToHash(lists, 0, 0)
            return countComplements(lists, len(lists) // 2, 0)

        def addToHash(lists: List[List[int]], i: int, sum: int) -> None:    # Here is the argument to be changed
            if i == len(lists) // 2:
                m[sum] = m.get(sum, 0) + 1
            else:
                for a in lists[i]:
                    addToHash(lists, i + 1, sum + a)

        def countComplements(lists: List[List[int]], i: int, complement: int) -> int:
            if i == len(lists):
                return m.get(complement, 0)
            cnt = 0
            for a in lists[i]:
                cnt += countComplements(lists, i + 1, complement - a)
            return cnt

        return nSumCount([A, B, C, D])
```

#### Language used for code

Python3

**Comment by LC-Sue** [comment]
Hi @PyroGenesis 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @PyroGenesis 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
