### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by mohit421** [LeetCode-Feedback/LeetCode-Feedback#6266]
#### Category of the bug
-  Missing Test Cases -> one missing test cases-> [2,5]

#### Description of the bug

The above solution is run successfully all test cases but when i take custom input this-> [2,5]  give runtime error .

#### Code you used for Submit/Run operation

Problem-> Find Pivot index 
```
// Find Pivot Index
class Solution {
public:
    int pivotIndex(vector<int>& nums) {
        vector<int>P={0};
        int prefixSum=0;
        vector<int>::iterator it;
        for(int i=0;i<nums.size();i++){
            prefixSum += nums[i];
            P.push_back(prefixSum);
        }
        for(int i=0;i<P.size();i++){
            if(P[i]==(P[P.size()-1]-P[i]-nums[i]))
                return i;
        }
        return -1;
    }
};
```

#### Language used for code

C++ language used for this Problem

#### Expected behavior

The above code must give error for test cases after submission

#### Additional context

It's a similar problem like "find the middle index in array "

Correct Solution ->
```
class Solution {
public:
    int pivotIndex(vector<int>& nums) {
        vector<int>P={0};
        int prefixSum=0;
        vector<int>::iterator it;
        for(int i=0;i<nums.size();i++){
            prefixSum += nums[i];
            P.push_back(prefixSum);
        }
        for(int i=0;i<P.size()-1;i++){
            if(P[i]==(P[P.size()-1]-P[i]-nums[i]))
                return i;
        }
        return -1;
    }
};

```

**Comment by stormsunshine** [comment]
The test case `[2,5]` is indeed missing.

@LC-Sue This test case should be added for both problem 724 and problem 1991.

**Comment by mohit421** [comment]
But the code I run in  724.Find Pivot index it run all test cases but the
same code not run in 1991 problem.  why?
Is there something missing in 724  .

**Comment by stormsunshine** [comment]
I see. Problem 1991 already has this test case, but problem 724 does not have this test case.

**Comment by mohit421** [comment]
You have to correct it for 724 ,there are so many test cases that it fails
but code submitted successfully

Hope you correct it!

Thank you

**Comment by LC-Sue** [comment]
Hi @mohit421 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @mohit421 
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username? Mohitjais312 is invalid.

**Comment by mohit421** [comment]
My leetcode id:- *Epicureanism*

**Comment by LC-Sue** [comment]
Hi @mohit421 
Thank you for your time. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by mohit421** [comment]
Thank you!
