### ISSUE TITLE
Incorrect Test Case - 269. Alien Dictionary

### ISSUE THREAD

**Issue by ghanekaromkar** [LeetCode-Feedback/LeetCode-Feedback#6267]
#### Your LeetCode username
omkar12

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
One of the provided test cases to the problem  viz. `["abc", "ab"]` is in conflict with the description of the data mentioned in the problem. The description is as follows
`You are given a list of strings words from the alien language's dictionary, where the strings in words are sorted lexicographically by the rules of this new language.` 

`A string s is lexicographically smaller than a string t if at the first letter where they differ, the letter in s comes before the letter in t in the alien language. If the first min(s.length, t.length) letters are the same, then s is smaller if and only if s.length < t.length.
`

#### Code you used for Submit/Run operation

```
class Solution:
    def alienOrder(self, words: List[str]) -> str:
        indegree = defaultdict(list)
        outdegree_count = {}
        def process(word1, word2):
            for char in word1+word2:
                if char not in outdegree_count:
                    outdegree_count[char] = 0
            for idx, char in enumerate(word1):
                if word1[idx] != word2[idx]:
                    outdegree_count[word2[idx]] = outdegree_count.get(word2[idx], 0) +1
                    indegree[word1[idx]].append(word2[idx])
                    return
                else:
                    outdegree_count[word1[idx]]
        

                
        for first, second in zip(words, words[1:]):
            process(first, second)
    
        soln = []
        queue = deque(char for char in outdegree_count if outdegree_count[char] == 0)
        while queue:
            char = queue.popleft()
            for dependent_char in indegree[char]:
                outdegree_count[dependent_char] -= 1
                if outdegree_count[dependent_char] == 0:
                    queue.append(dependent_char)
            soln.append(char)
        
        return "".join(soln)
```

#### Language used for code
Python3

#### Expected behavior
['abc', 'ab'] is an invalid test case

**Comment by stormsunshine** [comment]
In this case, there is no solution. Is there any problem?

**Comment by ghanekaromkar** [comment]
> Is there any problem?

Wouldn't have been if the problem description mentioned that the list if strings might not be necessarily sorted in which case I would have written the code to handle a situation that the strings might not be sorted as per the definition of sorted.

However, the description says "where the strings in words are sorted lexicographically by the rules of this new language."

What do you think?

**Comment by ghanekaromkar** [comment]
> In this case, there is no solution. Is there any problem?

Wouldn't have been if the problem description mentioned that the list if strings might not be necessarily sorted in which case I would have written the code to handle a situation that the strings might not be sorted as per the definition of sorted.

However, the description says "where the strings in words are sorted lexicographically by the rules of this new language."

What do you think?

**Comment by stormsunshine** [comment]
The problem description also mentions that, if there is no solution, return `""`. This means it is possible that the order of strings in `words` is not guaranteed to form a dictionary order. Also, example 3 shows the case where the strings do not form a dictionary order.

I think all the cases where the dictionary order does not exist should be considered.

> > In this case, there is no solution. Is there any problem?
> 
> Wouldn't have been if the problem description mentioned that the list if strings might not be necessarily sorted in which case I would have written the code to handle a situation that the strings might not be sorted as per the definition of sorted.
> 
> However, the description says "where the strings in words are sorted lexicographically by the rules of this new language."
> 
> What do you suggest?

**Comment by ghanekaromkar** [comment]
> The problem description also mentions that, if there is no solution, return `""`. This means it is possible that the order of strings in `words` is not guaranteed to form a dictionary order. Also, example 3 shows the case where the strings do not form a dictionary order.
> 
> I think all the cases where the dictionary order does not exist should be considered.
> 
> > > In this case, there is no solution. Is there any problem?
> > 
> > 
> > Wouldn't have been if the problem description mentioned that the list if strings might not be necessarily sorted in which case I would have written the code to handle a situation that the strings might not be sorted as per the definition of sorted.
> > However, the description says "where the strings in words are sorted lexicographically by the rules of this new language."
> > What do you suggest?

But shouldn't the provided test cases fall within the constraints mentioned in the problem?

If you still think this is a valid test case feel free to close the issue. [Few on the leetcode community agree](https://leetcode.com/problems/alien-dictionary/discuss/1738380/how-can-abcab-be-a-valid-test-case/1250501) to my concern so I at least know I'm not speaking something completely absurd.  I'm not too hard pressed on getting the test case removed.

**Comment by LC-Sue** [comment]
Hi @ghanekaromkar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @ghanekaromkar,
Thank you for your time. Our team has reviewed this report and we found the input to be valid. The statement said there can be no answer for some cases. We appreciate your support!

**Comment by vhquang** [comment]
@LC-Sue I don't think the input is valid, as it is contradict to the problem description:

> You are given a list of strings `words` from the alien language's dictionary, where the strings in `words` are **sorted lexicographically** by the rules of this new language.

By the sorting rule of the problem, the input in this case is not sorted.
