### ISSUE TITLE
601. Human Traffic of Stadium

### ISSUE THREAD

**Issue by garvitchaudhary9** [LeetCode-Feedback/LeetCode-Feedback#6268]
#### Leetcode Username

chaudharygarvit9

#### Category of the bug
- Solution

#### Description of the bug

There is a small mistake in the condition of the Solution.

#### Code you used for Submit/Run operation

```
// 601. Human Traffic of Stadium
Select t1.* from Stadium t1, Stadium t2,Stadium t3 where t1.people>=100 and t2.people>=100 and t3.people>=100 and(
    (t1.id-t2.id=1 and t1.id-t3.id=2 and t2.id-t3.id=1 )or
    (t2.id-t1.id=1 and t2.id-t3.id=1 and t1.id-t3.id=2 )or
    (t3.id-t2.id=1 and t2.id-t1.id=1 and t3.id-t1.id=2 ) 
    )
    order by t1.id;
```

#### Language used for code
MySQL

#### Expected behavior
This is working for the sample TC But still Wrong Answer -
```
// 601. Human Traffic of Stadium
Select t1.* from Stadium t1, Stadium t2,Stadium t3 where t1.people>=100 and t2.people>=100 and t3.people>=100 and(
    (t1.id-t2.id=1 and t1.id-t3.id=2 and t2.id-t3.id=1 )or
    (t2.id-t1.id=1 and t2.id-t3.id=1 and t1.id-t3.id=2 )or
    (t3.id-t2.id=1 and t2.id-t1.id=1 and t3.id-t1.id=2 ) 
    )
    order by t1.id;
```
Instead of -
```
select t1.*
from stadium t1, stadium t2, stadium t3
where t1.people >= 100 and t2.people >= 100 and t3.people >= 100
and
(
    (t1.id - t2.id = 1 and t1.id - t3.id = 2 and t2.id - t3.id =1)  -- t1, t2, t3
    or
    (t2.id - t1.id = 1 and t2.id - t3.id = 2 and t1.id - t3.id =1) -- t2, t1, t3
    or
    (t3.id - t2.id = 1 and t2.id - t1.id =1 and t3.id - t1.id = 2) -- t3, t2, t1
)
;
``` 

#### Screenshots

Solution I wrote -
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52832915/152478152-763f7f27-b457-4c61-83b4-6e6fe3c45b26.png">
Solution Given by LeetCode -
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52832915/152478373-de1e03a1-5f7e-4c15-9897-c085f53f2b84.png">
#### Additional context

Please Correct this.

**Comment by LC-Sue** [comment]
Hi @garvitchaudhary9,
Thank you for reaching out to us, the solution provided by LeetCode is accepted when you submit. I've attached a screenshot below for your reference! 
![image](https://user-images.githubusercontent.com/92285126/152680803-24b71d54-4334-4ef8-b3d9-15a5f5c3e254.png)
