### ISSUE TITLE
777. Swap Adjacent in LR String

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#627]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Incorrect official solution

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean canTransform(String start, String end) {
        int N = start.length();
        char[] S = start.toCharArray(), T = end.toCharArray();
        int i = -1, j = -1;
        while (++i < N && ++j < N) {
            while (i < N && S[i] == 'X') i++;
            while (j < N && T[j] == 'X') j++;
            /* At this point, i == N or S[i] != 'X',
               and j == N or T[j] != 'X'.  i and j
               are the indices representing the next
               occurrences of non-X characters in S and T.
            */

            // If only one of i < N and j < N, then it isn't solid-
            // there's more people in one of the strings.
            if ((i < N) ^ (j < N)) return false;

            if (i < N && j < N) {
                // If the person isn't the same, it isn't solid.
                // Or, if the person moved backwards, it isn't accessible.
                if (S[i] != T[j] || (S[i] == 'L' && i < j) ||
                        (S[i] == 'R' && i > j) )
                    return false;
            }
        }
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Fails test case

```
"RXR"
"XXR"
```

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us! Looks like the problem has been updated and now your code failed test case "RXR", "XXR" when submitted. Thank you.

**Comment by leet212** [comment]
Hello @lc-christina 
Thank you for the reply. You are correct this should not pass and does not pass. I forgot the actual reason behind this issue.
The pasted solution is the official one. It fails this test case when it should be working for all cases. I have updated the issue. Could you please reopen it?

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for the clarification. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
