### ISSUE TITLE
题目 110，执行代码通过 ，提交不通过

### ISSUE THREAD

**Issue by wenjundiandian** [LeetCode-Feedback/LeetCode-Feedback#6272]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目 110 
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
执行代码通过 ，提交不通过，测试用例 [1]
**你使用的语言**
JAVA

**你提交或者运行的代码**
```
// Two Sum
class Solution {

    private static int flag =  0;
    public boolean isBalanced(TreeNode root) {
        if(root == null){
            return true;
        }
        compare(root);
        if(flag == 1){
            return false;
        }else{
            return true;
        }
    }

    private int compare(TreeNode node){
        if(node == null){
            return 0;
        }
        int left = compare(node.left);
        int right = compare(node.right);
        if (Math.abs(left-right) > 1){
            flag = 1;
        }
        if(left > right) {
            return compare(node.left)+1;
        }else{
            return compare(node.right)+1;
        }       
    }
}
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
请不要使用静态变量，静态变量会导致本地运行和提交代码的结果不一致。提交运行时，对于每个测试用例会创建一个实例，静态变量是所有实例共享的，因此不会在执行每个测试用例时自动初始化。

**Comment by LC-Sue** [comment]
Hi @wenjundiandian 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
