### ISSUE TITLE
Typo in 525. Contiguous Array

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6273]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[525. Contiguous Array](https://leetcode.com/problems/contiguous-array/solution/)
The description is "`count = 2`", but the graph is `count = -2`.

#### Expected behavior

The description should be `count = -2`.

#### Screenshots

<img width="706" alt="image" src="https://user-images.githubusercontent.com/31957845/152540603-1ae813cf-3f12-4606-97a0-0c98e257724b.png">

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
