### ISSUE TITLE
Missing Test Case - 1221. Split a String in Balanced Strings

### ISSUE THREAD

**Issue by alimalim77** [LeetCode-Feedback/LeetCode-Feedback#6277]
#### Category of the bug
- [ 1221. Split a String in Balanced Strings] Question
- [
"""

class Solution(object):
    def balancedStringSplit(self, s):
        """
        :type s: str
        :rtype: int
        """
        
        rc = 0
        lc = 0
        strcount = 0
        for i in s:
            if rc > 0 and lc > 0 and rc == lc:
                strcount += 1
                rc = 0
                lc = 0
            print(strcount)
            if i == "R":
                rc += 1
            if i == "L":
                lc += 1
        
        return strcount + 1
        
"""
-  ] Solution
- [ Python] Language
- [ Empty String Test Case] Missing Test Cases 

#### Description of the bug

Kindly Add the test case when the test case when the string is empty as my code was accepted without even checking for the empty string

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @alimalim77,
Thank you for reaching out to us, could you please provide the test case that you'd like to be added to the problem?

**Comment by LC-Sue** [comment]
Hi @alimalim77 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
