### ISSUE TITLE
Missing Test Case - 1221. Split a String in Balanced Strings

### ISSUE THREAD

**Issue by alimalim77** [LeetCode-Feedback/LeetCode-Feedback#6279]
#### Category of the bug
- [1221. Split a String in Balanced Strings ] Question
- [ class Solution(object):
    def balancedStringSplit(self, s):
        """
        :type s: str
        :rtype: int
        """
        
        rc = 0
        lc = 0
        strcount = 0
        for i in s:
            if rc > 0 and lc > 0 and rc == lc:
                strcount += 1
                rc = 0
                lc = 0
            print(strcount)
            if i == "R":
                rc += 1
            if i == "L":
                lc += 1
        
        return strcount + 1 ] Solution
- [ Python] Language
- [Inconsistent number of L and R counted in the last line by adding strcount.  ] Missing Test Cases 

#### Description of the bug

Few test cases can be added in this area where strcount + 1 is giving the correct result indicating that L and R are in even number in the question. Edge cases can be added 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @alimalim77 
Please provide the missing test case you suggest adding. After more information is provided, I will reopen this ticket. Thank you for your time.
