### ISSUE TITLE
Missing Test Case - 387. First Unique Character in a String

### ISSUE THREAD

**Issue by AjitavBasak** [LeetCode-Feedback/LeetCode-Feedback#6280]
#### Your LeetCode username
Ajitav_Basak

#### Category of the bug
- [ ------] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Question says "Given a string s, find the first non-repeating character in it and return its index. If it does not exist, return -1"
Here there is no mention of the character type to be alphabets, digits, special characters or anything. 
**Because there is no mention of it lets assume anything and everything is allowed to be in the String. But then when we try to test it with different value we get to know that the question is to be restricted to only **a-z**

#### Code you used for Submit/Run operation

```
class Solution {
    public int firstUniqChar(String s) {
        int[] temp=new int[26];
        for(int i=0;i<s.length();i++){
            temp[s.charAt(i)-97]++;
        }    
        for(int i=0;i<s.length();i++){
            if(temp[s.charAt(i)-97]==1)
                return i;
        }
        return -1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Steps to Reproduce:-
Create a custom test case with upper case **A-Z**
Run code for the custom test case.

Result:- Run code status : Invalid Testcase
's' must consist of values from a to z only

**Comment by LC-Sue** [comment]
Hi @AjitavBasak,
Thank you for reaching out to us, under the constraints of the problem. It states "s consists of only lowercase English letters."
