### ISSUE TITLE
misleading criteria for - 250. Count Univalue Subtrees

### ISSUE THREAD

**Issue by urosknapic** [LeetCode-Feedback/LeetCode-Feedback#6281]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [ X ] Misleading Criteria

#### Description of the bug

I was trying to understand Binary Tree Problem. located here: https://leetcode.com/explore/learn/card/data-structure-tree/17/solve-problems-recursively/538/ (resource A)
I could not connect end results with requested criteria. So i had to go to 'Solution'. And solution criteria is different for same task. Located here: https://leetcode.com/problems/count-univalue-subtrees/solution/ (resource B)
Resource A criteria:
A uni-value subtree means all nodes of the subtree have the same value.

Resource B criteria:
1. The node has no children (base case)
2. All of the node's children are univalue subtrees, and the node and its children all have the same value

There comes to different solutions between A and B resource. I believe Resource A needs update on criteria so that instructions of a problem match results.

#### Screenshots

![image](https://user-images.githubusercontent.com/9485151/152651213-6cc5c545-19e9-4879-99a5-c90c3bf83f58.png)

![image](https://user-images.githubusercontent.com/9485151/152651246-8b2657de-83f0-4dbf-a56b-2a5f0f7afd64.png)

**Comment by LC-Sue** [comment]
Hi @urosknapic 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @urosknapic,
Thank you for your time. The two ways of describing the problem are synonymous. We appreciate your support!
