### ISSUE TITLE
409. Longest Palindrome Approach #1: Greedy [Accepted]

### ISSUE THREAD

**Issue by alxd112** [LeetCode-Feedback/LeetCode-Feedback#6283]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @alxd112 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
