### ISSUE TITLE
Hint mistake 2162. Minimum Cost to Set Cooking Time

### ISSUE THREAD

**Issue by Mayurmg** [LeetCode-Feedback/LeetCode-Feedback#6284]
#### Your LeetCode username
mayur2509

#### Category of the bug
- [* *] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In hint 1 it is written cock instead of clock.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Mayurmg 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Mayurmg 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
