### ISSUE TITLE
409. Longest Palindrome - False answer

### ISSUE THREAD

**Issue by alxd112** [LeetCode-Feedback/LeetCode-Feedback#6285]
#### Your LeetCode username
 alex4238 

#### Category of the bug

- [ ] Solution

#### Description of the bug
The solution (code in python) provided in Approach #1: Greedy [Accepted] is false and not working. For 2 reasons first of all because object Counter has no attribute itervalues(). Secondly, because the operation should be ans += v // 2 * 2 and not ans += v / 2 * 2 

#### Code you used for Submit/Run operation
 
 ```
class Solution:
    def longestPalindrome(self, s):
        ans = 0
        for v in collections.Counter(s).values():
            ans += v // 2 * 2
            if ans % 2 == 0 and v % 2 == 1:
                ans += 1
        return ans
```

#### Language used for code
Python3 

#### Expected behavior
 IT runs and passes the tests.

**Comment by LC-Sue** [comment]
Hi @alxd112,
Thank you for reaching out to us, the code in our solution is accepted. I've attached a screenshot for your reference!
