### ISSUE TITLE
Typo  - 2156. Find Substring With Given Hash Value

### ISSUE THREAD

**Issue by Howlla** [LeetCode-Feedback/LeetCode-Feedback#6288]
#### Your LeetCode username
Howlla

#### Category of the bug
- [ ] Question

#### Description of the bug

The first line in the question states 
"The hash of a 0-indexed string s of length **k** "
K is not the length of the string but the length of the substring.

#### Expected behavior
Change problem statement to
"The hash of a **substring** s of length k"

**Comment by LC-Sue** [comment]
Hi @Howlla 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Howlla,
Thank you for your time. The statement is correct.
We defined two facts
1. the hash function takes an input string of length k.
2. the input of the string should be a substring from s with length k.
Both facts are clear in the statement and also at the end, the substring is also a string.
