### ISSUE TITLE
411. Minimum Unique Word Abbreviation

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#629]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Constraints

#### Expected behavior
Assume length of target string = m, and dictionary size = n. You may assume that m ≤ 21, n ≤ 1000, and log2(n) + m ≤ 20.

If m is 21 as specified and is in one of the given cases, log2(n) + m ≤ 20 is false. Should be 21.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
