### ISSUE TITLE
Typo in the problem statement - 1233. Remove Sub-Folders from the Filesystem

### ISSUE THREAD

**Issue by kryuki** [LeetCode-Feedback/LeetCode-Feedback#6291]
#### Your LeetCode username

name: ababa
LeetCode ID: kryuki

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Statement in the Example 2 should be changed from "/a/b/d/" to "/a/b/d".
Explanation: Folders "/a/b/c" and "/a/b/d/" will be removed because they are subfolders of "/a".

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @kryuki 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kryuki 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
