### ISSUE TITLE
Problem 977 is not handling retuns correctly

### ISSUE THREAD

**Issue by Mental-Inferno** [LeetCode-Feedback/LeetCode-Feedback#6292]
#### Your LeetCode username

FeatherLite

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I return a pointer to the array, the solver does not read the array. However, I can print out every element in the array and all is well

#### Code you used for Submit/Run operation

```
/**
 * Note: The returned array must be malloced, assume caller calls free().
 */
int* sortedSquares(int* nums, int numsSize, int* returnSize){ 
    static int* squaredList;
    squaredList = (int*)calloc(numsSize-1, numsSize * sizeof(int));
    
    for (int i=0; i<numsSize; i++){
        squaredList[i] = nums[i]*nums[i];
    }
    
    nums = squaredList;

    int pivot = 0;
    int checkpoint;
    int temp;

    while (pivot < numsSize-1){
        
        if (nums[pivot] > nums[pivot+1]){
            temp = nums[pivot];
            nums[pivot]  = nums[pivot+1];
            nums[pivot+1] = temp;
            checkpoint = pivot+1;

            while(pivot != 0){ /*going backwards to check sortedness*/
                pivot--;

                if (nums[pivot] > nums[pivot+1]){
                    temp = nums[pivot];
                    nums[pivot]  = nums[pivot+1];
                    nums[pivot+1] = temp;
                }
            }

            pivot = checkpoint;
        }
        else {
            pivot++;
        }
    }
    for (int i = 0; i<numsSize; i++){
        printf("%d\n", nums[i]);
    }
    return nums;
}
```

#### Language used for code

C

#### Expected behavior

I would expect this to be marked as correct

#### Screenshots

![image](https://user-images.githubusercontent.com/59522230/152665938-a9e55298-3d3d-457d-a714-36a8547f278e.png)

**Comment by LC-Sue** [comment]
Hi @Mental-Inferno,
Thank you for reaching out to us, our judger appears to be running correctly. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
