### ISSUE TITLE
Missing Test Case - 2055. Plates Between Candles

### ISSUE THREAD

**Issue by peiiiii** [LeetCode-Feedback/LeetCode-Feedback#6293]
#### Your LeetCode username
clinpei

#### Category of the bug
- [ O ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
My test passed when I manually entered the test case, but it failed when I submitted the answer.
Test case:
"***|**|*****|**||**|*"
[[1,17],[4,5],[14,17],[5,11],[15,16]]

#### Code you used for Submit/Run operation

```
// Plates Between Candles
class Solution {
    static List<Integer> candles = new ArrayList<Integer>();
    public int[] platesBetweenCandles(String s, int[][] queries) {
        
        int ans[] = new int[queries.length];
        for(int j = 0; j < s.length(); j++) {
            if(s.charAt(j) == '|'){
                candles.add(j);
                System.out.println(j);
            }
        }
        
        for(int i = 0; i < queries.length; i++) {
            ans[i] = helper(queries[i][0], queries[i][1]);
        }
        
        return ans;
    }
    
    public static int helper(int a, int b) {
        int left = 0, right = 0, index_l = 0, index_r = 0, mid = 0;
        for(int i = 0; i < candles.size(); i++ ) {
            if(left == 0 && a <= candles.get(i) && candles.get(i) <= b) {
                left = candles.get(i);
                index_l = i;
            }
            if(left > 0 && b >= candles.get(i)) {
                right = candles.get(i);
                index_r = i;
            }
            mid = index_r - index_l - 1;
        }

        return right - left - mid -1 ;
    }
}
```

#### Language used for code
Java

#### Expected behavior
I think it might pass this test case when I submitted. Or at least it shows failed when I customized the same test case, not the same test case with a different answer.

#### Screenshots

![截圖 2022-02-05 下午10 39 44（2）](https://user-images.githubusercontent.com/25923926/152670375-403b8907-1ca3-451d-9a75-60a693ee572a.png)

**Comment by LC-Sue** [comment]
Hi @peiiiii 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
