### ISSUE TITLE
Missing Number contradiction in the description

### ISSUE THREAD

**Issue by SleeplessChallenger** [LeetCode-Feedback/LeetCode-Feedback#6294]
#### Your LeetCode username

SleeplessChallenger

#### Category of the bug
- [OK] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the question description it's said: "Given an array nums containing n distinct numbers in the range [0, n]". So, **from** `0` to `n`. But in the test cases there are the following: `[1]` && `[1,2]`. So, it's a total opposite of the description

Below first solution works well as it bypasses this bug. But, if we go directly with the description and assume that **smallest** number is `0` and no way there is possibility of `0` being missing -> error for the second solution. Of course, there is `Bit manipulation` and other ways to solve, but it contradicts the pure logic of the description. 

So, either make a change to the description and say that 1 may be the start or remove those test cases

#### Code you used for Submit/Run operation

```
// Missing Number
# first
class Solution {
    // O(n) Time O(n) Space
    fun missingNumber(nums: IntArray): Int {
        val hashTable = mutableMapOf<Int, Boolean>()
        for(num in nums) {
            hashTable.put(num, true)
        }
        
        var returnKey: Int = 0
        
        for(i in 0 until nums.size + 1) {
            if(!hashTable.containsKey(i)) {
                returnKey = i
                break
            }
        }
        
        return returnKey
    }
}

# second
class Solution {
    // O(n * log n) Time O(1) Space
    fun missingNumber(nums: IntArray): Int {
        if(nums.size == 1) {
            when {
                nums[0] == 1 -> {
                    return 0
            } else -> {
                    return 1
                }
            }
        }
        nums.sort()
        
        for(i in 1 until nums.size) {
            val currNum: Int = nums[i]
            val prevNum: Int = nums[i-1]

            if (currNum - prevNum > 1) {
                return prevNum + 1
            }
        }

        return nums.last() + 1
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

As mentioned in the description of the bug, people don't expect `0` to be missing from the array

**Comment by LC-Sue** [comment]
Hi @SleeplessChallenger 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by SleeplessChallenger** [comment]
Thanks! I'll wait for response

**Comment by LC-Sue** [comment]
Hi @SleeplessChallenger,
Thank you for your time. When the statement says the array contains numbers "in the range [0, n]", it means every number in the array lies in the inclusive range between 0 and n. That's all it means. The statement makes no guarantees about the existence of the endpoints 0 or n in the array. 0 can absolutely be the missing number and the second solution you provided is wrong for assuming it can't.
