### ISSUE TITLE
Missing Test Case - 1313. Decompress Run-Length Encoded List

### ISSUE THREAD

**Issue by TUSHARSHARMA9314** [LeetCode-Feedback/LeetCode-Feedback#6296]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @TUSHARSHARMA9314 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
