### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by mohammedazam38** [LeetCode-Feedback/LeetCode-Feedback#6297]
#### Your LeetCode username

MohammedAzam

#### Category of the bug
- 26. Remove Duplicates from Sorted Array
- Missing test cases
- JAVA
-  Test case 1: [ ] as per question 0 length test case is missing.
-  Test case 2: [1] as per question 1 length test case is missing.

#### Code you used for Submit/Run operation

```
class Solution {
    public int removeDuplicates(int[] nums) {
      
            int right=1;
            int left=1;
            while(left<nums.length){
                    if(nums[left]==nums[left-1]){
                      left++;
                    }
                    else{
                            nums[right]=nums[left];
                            right++;
                            left++;
                    }
            }
            return right;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

When input is zero sizes array it should return 0 as per constraints ,But the test case for zero sized array is not present.
When input array is size of 1 ex:[1] then also the test case are not validating as per the constraints in the problem

#### Screenshots

![image](https://user-images.githubusercontent.com/67278854/152676232-071038c2-b6f8-40e6-aa12-225f02d396d4.png)

#### Additional context

Please provide the result of test case or if I did any misunderstanding please let me know .

**Comment by LC-Sue** [comment]
Hi @mohammedazam38,
Thank you for reaching out to us, the test case [] [1] is not missing, it's accepted with the code you provided and actual output is the same as expected output.
