### ISSUE TITLE
Missing Test Case - 1550. Three Consecutive Odds

### ISSUE THREAD

**Issue by TUSHARSHARMA9314** [LeetCode-Feedback/LeetCode-Feedback#6298]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool threeConsecutiveOdds(vector<int>& arr) {
        int cnt=0;
        for(int i=0;i<arr.size();i++){
            if(arr[i]%2==1)
                cnt++;
            else
                cnt=0;
            if(cnt==3)
                return true;
        }
        return false;
    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case?

**Comment by LC-Sue** [comment]
Hi @TUSHARSHARMA9314 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
