### ISSUE TITLE
Error in backend code on problem 13

### ISSUE THREAD

**Issue by wyorkovich** [LeetCode-Feedback/LeetCode-Feedback#63]
In problem 13: Roman to Integer, there is a problem regarding the backend Java code in the main method that nullifies any submission. The error reads

```
Line 10: error: unreported exception Exception; must be caught or declared to be thrown [in __Driver__.java]
int ret = new Solution().romanToInt(param_1);
                                   ^
```

**Comment by CooperCooperCooper** [comment]
Hi @wyorkovich,
Thank you for reaching out to us. To help us assess this issue, please share your submission in your post.

**Comment by wyorkovich** [comment]
It's a terrible solution because I've basically forgotten everything I'd learned in my degree, but at least it works. Or it should, anyway.
`class Solution {
    public int romanToInt(String s) throws Exception {
		int num = 0;
		char[] numerals = s.toLowerCase().toCharArray();
		
		for(int i = 0; i < numerals.length; i++) {
			char current = numerals[i];
			char next = numerals[i + 1];
			
			if(current == 'c' && next == 'm') {
				num += 900;
			}			
			else if(current == 'c' && next == 'd') {
				num += 400;
			}			
			else if(current == 'x' && next == 'c') {
				num += 90;
			}			
			else if(current == 'x' && next == 'l') {
				num += 40;
			}
			else if(current == 'i' && next == 'x') {
				num += 9;
			}
			else if(current == 'i' && next == 'v') {
				num += 4;
			}
			else if(current == 'm') {
				num += 1000;
			}
			else if(current == 'd') {
				num += 500;
			}
			else if(current == 'c') {
				num += 100;
			}
			else if(current == 'l') {
				num += 50;
			}
			else if(current == 'x') {
				num += 10;
			}
			else if(current == 'v') {
				num += 5;
			}
			else {
				num += 1;
			}			
		}
		
		if(num > 3999 || num < 1) {
			throw new Exception("Roman numeral out of bounds");
		}
		
		return num;
	}
}`

**Comment by CooperCooperCooper** [comment]
Hi @wyorkovich,
Thank you for the clarification. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @wyorkovich,
Thank you for your time. On line 7, "char next = numerals[i + 1]" is getting out of bounds. Please check out the Java solutions in the problem discuss section for inspiration: https://leetcode.com/problems/roman-to-integer/discuss?currentPage=1&orderBy=most_votes&query=java.
