### ISSUE TITLE
555. Split Concatenated Strings

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#630]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 1 Depth First Search [Time Limit Exceeded] has incorrect analysis

#### Expected behavior
Time complexity : O(2^n)

Should be O(n . 2^n) as there is linear work for each state.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
