### ISSUE TITLE
Redundant variable in implementation - 214. Shortest Palindrome

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6300]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[214. Shortest Palindrome](https://leetcode.com/problems/shortest-palindrome/)

In the C++ implementation of "Approach # 1 Brute force", there's a redundant variable `j` in line 6.

#### Expected behavior

Remove line 6.

#### Screenshots

<img width="736" alt="image" src="https://user-images.githubusercontent.com/31957845/152683975-3d1106cd-fca2-476c-91c7-c490971b3245.png">

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
