### ISSUE TITLE
Typo in 214. Shortest Palindrome

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6301]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[214. Shortest Palindrome](https://leetcode.com/problems/shortest-palindrome/)

In the Complexity analysis of Approach 2, there's a latex shown without proper rendering.

#### Expected behavior

Render it correctly.

#### Screenshots

<img width="455" alt="image" src="https://user-images.githubusercontent.com/31957845/152686330-cf915a1e-599c-462b-aec6-d2346cb52278.png">

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
