### ISSUE TITLE
Missing Test Case - 731. My Calendar II

### ISSUE THREAD

**Issue by georgeleve** [LeetCode-Feedback/LeetCode-Feedback#6303]
#### Category of the bug
- [ ] Language

#### Description of the bug

In the description of the problem you write "ca not" instead of "can not".
where it says "myCalendarTwo.book(5, 15);  // return False, The event !!!!!ca!!!!! not be booked, because it would result in a triple booking."

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @georgeleve 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @georgeleve 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
