### ISSUE TITLE
Missing Test Case - 1114. Print in Order

### ISSUE THREAD

**Issue by O136** [LeetCode-Feedback/LeetCode-Feedback#6305]
#### Your LeetCode username
O136

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The below provided solution could be wrong but was accepted (assuming it's compiled with optimizations on, e.g. -O3).

#### Code you used for Submit/Run operation

```C
typedef struct {
    int turn;
} Foo;

Foo* fooCreate() {
    Foo* obj = (Foo*) malloc(sizeof(Foo));
    obj->turn = 1;
    return obj;
}

void first(Foo* obj) {
    printFirst();
    obj->turn = 2;
}

void second(Foo* obj) {
    while (obj->turn != 2)
        ;
    printSecond();
    obj->turn = 3;
}

void third(Foo* obj) {
    while (obj->turn != 3)
        ;
    printThird();
}

void fooFree(Foo* obj) {
    free(obj);
}
```

#### Language used for code

C

#### Expected behavior

the variable `obj->turn` shouldn't be saved in a register but given that the variable was declared as a simple `int`,
it is used for optimization.
(Compiled with gcc11.2 and -O3)
https://godbolt.org/z/vcxbvhYTn the label `third:` for e.g.
we check the `obj->turn` only ONCE and potentially jump in an endless loop, but the server still accepted the above solution. 
(A solution would be for e.g. to declare it as `volatile int turn` and generated code will be fine, or this solution might be indeed correct if optimizations are disabled completely (-O0) )

**Comment by LC-Sue** [comment]
Hi @O136 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @O136,
Thank you for your time, our team has looked at the problem and the solution is ok to pass!
