### ISSUE TITLE
A Quick union - disjoint set, the code in the second video is incorrect

### ISSUE THREAD

**Issue by rpetrenko** [LeetCode-Feedback/LeetCode-Feedback#6307]
#### Your LeetCode username
rpetrenko

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
in the second video of this link, at 01:41 when we compare quick find and quick union, the third line from bottom on the right snippet
should be changed from
root[rootY] = x;
to
root[rootY] = rootX;

https://leetcode.com/explore/featured/card/graph/618/disjoint-set/3840/

#### Screenshots
![image](https://user-images.githubusercontent.com/211505/152705367-127d1f1a-c78a-448e-b40b-d15a5a06cdca.png)

**Comment by LC-Sue** [comment]
Hi @rpetrenko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @rpetrenko 
Thank you for your time. We've adjusted the wording in the clarifying note under the video to make it more clear that the code shown below the video is the correct code. We appreciate your support!
