### ISSUE TITLE
Missing Test Case - 341. Flatten Nested List Iterator

### ISSUE THREAD

**Issue by terapackets** [LeetCode-Feedback/LeetCode-Feedback#6308]
#### Your LeetCode username
secu1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
My code is the following, it runs fine locally on my PC (node.js 10.15.1) with the two test cases when "Run Code" (the step before submit).  I keep getting error from leetcode. 
Line 72 in solution.js
        t = t[0][t[1]][0]
                      ^
TypeError: Cannot read properties of undefined (reading '0')
    Line 72: Char 23 in solution.js (NestedIterator.next)

Can you tell why it runs  differently in Leetcode platform?  Thanks.

Here is my code
```
var NestedIterator = function(nestedList) {
    //console.log(process.version)
    let stack = []
    while(typeof nestedList == 'object') {
        stack.push([nestedList, 0])
        nestedList = nestedList[0]
    }
    this.stack = stack
};


/**
 * @this NestedIterator
 * @returns {boolean}
 */
NestedIterator.prototype.hasNext = function() {
    return this.stack.length > 0
};

/**
 * @this NestedIterator
 * @returns {integer}
 */
NestedIterator.prototype.next = function() {
    let stack = this.stack
    let t = stack[stack.length - 1]  //top frame
    let ret = t[0][t[1]]
    while(stack.length > 0) {
        t = stack[stack.length - 1]
        t[1] ++
        if (t[1] >= t[0].length) {
            stack.pop()
            continue
        }
        if(typeof t[0][t[1]] == 'number') {
            break
        }
        stack.push([t[0][t[1]], 0])
        t = t[0][t[1]][0]
        while (typeof t == 'object') {
            stack.push([t,0])
            t = t[0]
        }
        break
    }
    return ret
};
```

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
