### ISSUE TITLE
Issue in test case of leet problem : https://leetcode.com/problems/implement-strstr/

### ISSUE THREAD

**Issue by kapil4457** [LeetCode-Feedback/LeetCode-Feedback#6309]
#### Your LeetCode username

Username : kapilsoni54768161

#### Category of the bug
- [ ] Test Case

#### Description of the bug

In this question , when i run my code in intellij idea  i get correct answer but when i run it in your compiler i get wrong answer..

#### Code you used for Submit/Run operation

```
class Solution {
    public int strStr(String haystack, String needle) {
        
    
        if (haystack == "" || needle == "") {
            return 0;
        }


       for(int i=0;i<haystack.length();i++){
           if(haystack.charAt(i) == needle.charAt(0)){
               int start = i;
               int end = haystack.length()-1;
                    String sub = haystack.substring(start,end);
                if(sub.contains(needle)){
                    return i;
                }

           }
       }


        return -1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

should return 0 in the test case when needle ==""

#### Screenshots

![compiler](https://user-images.githubusercontent.com/78656206/152768589-4b423561-355c-4231-bacd-56669243043a.jpg)
![leetCompiler](https://user-images.githubusercontent.com/78656206/152768593-a4011574-b6cc-46ba-b135-d471c016a8a9.jpg)

#### Additional context

I have attached photos of result both times, i.e., when i run it in intellij and on leet

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.

**Comment by kapil4457** [comment]
Ok . No problem
