### ISSUE TITLE
644. Maximum Average Subarray II

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#631]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 2 Using Binary Search [Accepted] has incorrect analysis

#### Expected behavior

> Time complexity : O(nlog(max_val−min_val)). check takes O(n) time and it is executed O(log(max_val−min_val)) times.

Even though asymptotically it is correct it is not executed O(log(max_val−min_val)) times rather O(log((max_val−min_val)/(10^-5))) times as it depends upon precision limit as well.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
