### ISSUE TITLE
Ruby TLE - 204. Count Primes

### ISSUE THREAD

**Issue by giner** [LeetCode-Feedback/LeetCode-Feedback#6310]
#### Your LeetCode username

giner

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Timeout is too strict

#### Code you used for Submit/Run operation

```
def count_primes(n)
    isprime = [true] * n
    count = 0
    
    for i in 2...n
        next if !isprime[i]
        count += 1

        (i * i).step(n, i) do |j|
            isprime[j] = false
        end
    end
    
    count
end
```
or
```
def count_primes(n)
    isprime = [true] * n
    isprime[0..1] = [false, false]
    
    for i in 2...(n**0.5)
        next if !isprime[i]

        (i * i).step(n, i) do |j|
            isprime[j] = false
        end
    end
    
    isprime.count(&:itself)
end
```

#### Language used for code

Ruby

#### Expected behavior

Should not time out

**Comment by LC-Sue** [comment]
Hi @giner，
Thank you for reaching out to us, the time limit has previously been loosened already. Please feel free to refer to the discuss section of the problem to see how other users have optimized their Ruby codes!

**Comment by giner** [comment]
@LC-Sue none of algorithmic ways work within the current constraints which leaves us with limited options such as using very optimized built-in library `prime`. Unless this is what the problem creator assumed to be the solution (and I suppose they didn't judging by the problem hints) the constraints should be relaxed.
