### ISSUE TITLE
Wierd Judge System - 389. Find the Difference

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6312]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

According to the question, `string t = shuffled(string s + 1 any character)`. Thus it's impossible to have 2 or more characters in string `t` which are not in string `s`. But the judge system allows this kind of test case.

#### Expected behavior

Add some judgment for this.

#### Screenshots

<img width="229" alt="image" src="https://user-images.githubusercontent.com/31957845/152756275-30862d92-a89f-4de6-8bb0-111c93737fc1.png">

<img width="281" alt="image" src="https://user-images.githubusercontent.com/31957845/152756898-9d3ad4d4-766e-4a2d-bbf3-a9566d01de9e.png">

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
