### ISSUE TITLE
Constraints - 1401. Circle and Rectangle Overlapping

### ISSUE THREAD

**Issue by gaurvag** [LeetCode-Feedback/LeetCode-Feedback#6313]
#### Your LeetCode username
g0rav

#### Category of the bug
- [ ] Question
- [ ] Missing Test Cases 

#### Description of the bug
Simple brute force O(N^2) solutions are able to pass where N can go upto 10^4, 
and probably such solutions are not intended solutions for this problem.
N can be increased upto 10^5 to avoid that.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkOverlap(int radius, int x_center, int y_center, int x1, int y1, int x2, int y2) {
        //Applying the pythagoras theorem for calculating the distance between the pts to know //which pts lies with circlce
        for(int i=x1;i<=x2;i++){
            for(int j=y1;j<=y2;j++){
                if(sqrt(pow((x_center-i),2)+pow(y_center-j,2))<=radius)
                    return true;
            }
        }
        return false;
     }
};
```

#### Language used for code
C++ 

#### Expected behavior

There should be TLE for O(N^2) complexity solutions but 4.10^8 operations one is also able to pass, so there is need to increase in value of constraints.

#### Additional context
These will be more appropriate constraints:
1 <= radius <= 2000
-10^5 <= xCenter, yCenter <= 10^5
-10^5 <= x1 < x2 <= 10^5
-10^5 <= y1 < y2 <= 10^5

**Comment by LC-Sue** [comment]
Hi @gaurvag 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @gaurvag 
Thank you for your time. Our team as reviewed the problem and have decided to keep the current constraints. We appreciate your support!
