### ISSUE TITLE
Missing test case - 214. Shortest Palindrome

### ISSUE THREAD

**Issue by hyanggi** [LeetCode-Feedback/LeetCode-Feedback#6314]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a test case missing. This makes an incorrect solution be accepted.
The missing test case is: ```"ababbababacba"```.
The incorrect solution is posted by someone. I spent hours trying to understand it but eventually found out it was incorrect.

#### Code you used for Submit/Run operation

Python 3 version:
```
class Solution:
    def shortestPalindrome(self, s: str) -> str:
        rev = s[::-1]
        if s == rev:
            return s
        table = [0 for i in range(len(rev))]
        j = 0
        for i in range(1, len(rev)):
            while j>0 and rev[i]!=s[j]:
                j = table[j-1]
            if rev[i]==s[j]:
                j += 1
            table[i] = j
        return rev + s[j:]
```

C++ version:
```
class Solution {
public:
    string shortestPalindrome(string s) {
        string rev(s.rbegin(), s.rend());
        if (s == rev)
            return s;
        vector lps(rev.size(), 0);
        int len = 0;
        for (int i = 1; i < rev.size(); i++) {
            while (len > 0 && rev[i] != s[len])
                len = lps[len - 1];
            if (rev[i] == s[len])
                len++;
            lps[i] = len;
        }
        return rev + s.substr(len, s.size() - len);
    }
};
```

#### Language used for code
Python 3
C++

#### Expected behavior

LeetCode should reject this solution when it is submitted.

**Comment by LC-Sue** [comment]
Hi @hyanggi 
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for this contribution, could you please provide your LeetCode username?

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
