### ISSUE TITLE
Typo in "Framework for DP Problems". Section "The Framework", part 3

### ISSUE THREAD

**Issue by kibermiaf** [LeetCode-Feedback/LeetCode-Feedback#6315]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Typo in "Framework for DP Problems". Section "The Framework", part 3.

https://leetcode.com/explore/featured/card/dynamic-programming/631/strategy-for-solving-dp-problems/4096/

"The equation \text{dp(i) = dp(i - 1) + dp(i - 2)}dp(i) = dp(i - 1) + dp(i - 2) on its known will continue forever to negative infinity. "
Probably wanted to say "on its own" ?

**Comment by LC-Sue** [comment]
Hi @kibermiaf 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kibermiaf 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
