### ISSUE TITLE
Typo in Python3 solution of 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by sr-vrd** [LeetCode-Feedback/LeetCode-Feedback#6316]
#### Your LeetCode username
sr_vrd
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hi. I believe there is a small typo in the Python3 solution of approach 6 of [287. Find the Duplicate Number](https://leetcode.com/problems/find-the-duplicate-number/). Line 10 of the current solution reads
```
for i in range(n):
```
and it should be
```
for i in range(n + 1):
```
since it is reading numbers from an array of size n + 1, and we want to add all numbers from 1 to n to the count.

Thanks

**Comment by LC-Sue** [comment]
Hi @sr-vrd 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
