### ISSUE TITLE
Wrong Test Case - 125. Valid Palindrome

### ISSUE THREAD

**Issue by gandharvas** [LeetCode-Feedback/LeetCode-Feedback#6317]
#### Your LeetCode username
gandharvas

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The question description says that we need to check for a palindrome on a string after removing any space and alphanumeric char and converting all letters to lower cases. But consider an example case of "1P" which after converting to a desired string would become "p" and its a perfect palindrome. But the test case fails for cases like that 

#### Code you used for Submit/Run operation

```
func isPalindrome(s string) bool {
    // upper to lower
    // only letters
    
    s = strings.ToLower(s)
    fmt.Println(s)
    newS := []byte{}
    for _, v := range s{
        if v >= 'a' && v <= 'z'{
            newS = append(newS, byte(v))
        }
        
    }
    fmt.Println(string(newS))
    
    r, l := 0, len(newS)-1
    for r<l{
        if newS[r] != newS[l]{
            return false
        }
        r++
        l--
    }
    return true
}
```

#### Language used for code

Go

#### Expected behavior

1. All alphanumeric character and space should be removed
2. The validation of string should happen strictly on alphabet ranging from [a-z] and nothing else

#### Screenshots

![image](https://user-images.githubusercontent.com/39269658/152901289-6033f5cc-81d7-4e4e-8480-52239fa80331.png)

**Comment by stormsunshine** [comment]
This problem requires converting all uppercase letters into lowercase letters and  removing all non-alphanumeric characters and check. Alphanumeric characters include letters and numbers.

Why do you think digits should be removed?

**Comment by gandharvas** [comment]
Wrong interpretation of problem
