### ISSUE TITLE
Missing Test Case - 485. Max Consecutive Ones

### ISSUE THREAD

**Issue by Naaman233** [LeetCode-Feedback/LeetCode-Feedback#6320]
#### Your LeetCode username

Naaman

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug

Since the constraints of the problem is given by 1 <= nums.length <= 10 raised to the power 5 
to write an optimal solution, we should consider whether an array is empty or not and return -1 if 
an array is empty

**Comment by stormsunshine** [comment]
This problem does not require considering the case where the array is empty. I don't think such a test case is needed.

**Comment by LC-Sue** [comment]
Hi @Naaman233,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! We appreciate your support!
