### ISSUE TITLE
Missing Test Case - 253. Meeting Rooms II

### ISSUE THREAD

**Issue by hyunjoongk** [LeetCode-Feedback/LeetCode-Feedback#6322]
#### Your LeetCode username

hyunjoong

#### Category of the bug
- [v] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

problem description: intervals[i] = [starti, endi] -> closed interval
test case 65 input: [[13,15],[1,13]] -> ans 1
But, if closed interval ans should be 2.
Either wrong tc or wrong problem description.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
The interval [start<sub>i</sub>, end<sub>i</sub>] is represented as an array, which does NOT mean that the interval is a closed interval.

In reality, the next meeting can start at the time when the previous meeting ends. Therefore, both problem description and test case are correct.

**Comment by LC-Sue** [comment]
Hi @hyunjoongk,
Thank you for reaching out to us! I hope stormsunshine's response was able to answer your doubts! We appreciate your support!
