### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by leongrin** [LeetCode-Feedback/LeetCode-Feedback#6324]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

My code is returning false for the test case [5,1,4,null,null,3,6] on my IDE, but on LeetCode is returning true. How can this not be a bug?

```
let isValidBST = function(root) {
    let answer = true;
    let index = 0;

    function helper() {
        if (!root.length) {
            return
        }
        if (index >= root.length -1) {
            return;
        }
        if (root[index + 1] > root[index]) {
            answer = false;
            return;
        }
        if (root[index + 2] < root[index]) {
            answer = false;
            return;
        }
        index += 3;
        helper()
    }

    helper();

    return answer;
};
```

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
