### ISSUE TITLE
Missing Test Case - 258. Add Digits

### ISSUE THREAD

**Issue by soni113** [LeetCode-Feedback/LeetCode-Feedback#6325]
class Solution {
    public int addDigits(int num) {
        while(num>9){
            num=num/10+num%10;
        }
        return num;
        
    }
}

**Comment by stormsunshine** [comment]
What is the missing test case?

**Comment by LC-Sue** [comment]
Hi @soni113 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
