### ISSUE TITLE
Description - House Robber

### ISSUE THREAD

**Issue by brantphoto** [LeetCode-Feedback/LeetCode-Feedback#6326]
#### Your LeetCode username
user7094if

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the description for the problem it states:
> You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected and it will automatically contact the police if two adjacent houses were broken into on the same night

> Given an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.

the description, especially the part describing 'the only constraint', gave me the impression that the robber could choose to rob the houses in a non-sequential order. The examples did provide two examples where the houses were robbed sequentially but as it was not described as a constraint I assumed it was coincidence.

**Comment by stormsunshine** [comment]
The order in which the houses are robbed does not matter, since the result is the sum of the robbed amount. Why are you concerning the order? Does the amount change if the order changes?

**Comment by LC-Sue** [comment]
Hi @brantphoto,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! We appreciate your support!

**Comment by brantphoto** [comment]
ok thanks @stormsunshine @LC-Sue , will reread the solutions and see where I got mixed up.
