### ISSUE TITLE
Redundant hints - 2167. Minimum Time to Remove All Cars Containing Illegal Goods

### ISSUE THREAD

**Issue by balampbv** [LeetCode-Feedback/LeetCode-Feedback#6327]
#### Your LeetCode username
balasekar 

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Same hints are repeated twice.

#### Expected behavior
Hints should not be repeated. Hint 4, 5 and 6 are redundant. These hints needs to be removed.

#### Screenshots
![Screenshot 2022-02-09 014751](https://user-images.githubusercontent.com/19851873/153068873-de68619e-5285-4a81-81b5-f869499e709c.jpg)

**Comment by LC-Sue** [comment]
Hi @balampbv 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @balampbv 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
