### ISSUE TITLE
Missing Solution - 7. Reverse Integer

### ISSUE THREAD

**Issue by bhaktivora9** [LeetCode-Feedback/LeetCode-Feedback#6328]
#### Description of the bug
Approach 2 : 
Recursive approach to the solution is missing.

#### Code you used for Submit/Run operation
```
// Reverse Integer
class Solution {
 	public int reverse(int x) {
		String s = Integer.toString(x);
		if (s.charAt(0) == '-') {
			String reverse = reverse(Math.abs(x), "");
			reverse = reverse.replaceAll("^0*", "");
			try {
				x = -Integer.valueOf(reverse);
			} catch (Exception e) {
				x = 0;
			}
			return x;
		}

		String reverse = reverse(x, "");
		reverse = reverse.replaceAll("^0*", "");
		try {
			x = Integer.valueOf(reverse);
		} catch (Exception e) {
			x = 0;
		}
		return x;
	}

	private String reverse(int x, String s) {
		//System.out.println("Calling " + x + ", s = " + s);
		int i = x % 10;
		if (i == x) {
		//	System.out.println("Returning " + x);
			return s + i;
		}
		s = s + i;
		return (reverse(x / 10, s));

	}
}

```

#### Screenshots
![image](https://user-images.githubusercontent.com/56788415/153094171-673354f8-3272-4d82-98c9-662a6c838a71.png)

![image](https://user-images.githubusercontent.com/56788415/153094218-a53eef53-ad16-4c86-90ad-ebe0c26911f9.png)

#### Additional context
Using the inbuilt stack instead of new stack.

**Comment by LC-Sue** [comment]
Hi @bhaktivora9 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
