### ISSUE TITLE
Ambiguous / incorrect problem description - 532. K-diff Pairs in an Array

### ISSUE THREAD

**Issue by lxylxy123456** [LeetCode-Feedback/LeetCode-Feedback#6329]
#### Your LeetCode username
lxylxy123456

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem defines a "k-diff pair", which does not match the example and the underlying test cases.

For reference: here is the current problem description:

```
Given an array of integers nums and an integer k, return the number of unique k-diff pairs in the array.
A k-diff pair is an integer pair (nums[i], nums[j]), where the following are true:
    0 <= i < j < nums.length
    |nums[i] - nums[j]| == k
Notice that |val| denotes the absolute value of val.

Example 1:
Input: nums = [3,1,4,1,5], k = 2
Output: 2
Explanation: There are two 2-diff pairs in the array, (1, 3) and (3, 5).
Although we have two 1s in the input, we should only return the number of unique pairs.
...
```

In Example 1, when `i=0` and `j=3`, there is `nums[i] = nums[0] = 3` and `nums[j] = nums[3] = 1`. This selection of `i` and `j` satisfies `0 <= i < j < nums.length` and `|nums[i] - nums[j]| == k`. So the k-diff pair should be `(nums[i], nums[j]) = (3, 1)`, NOT `(1, 3)`.

Using this interpretation, consider the test case
```
[1,2,4,4,3,3,0,9,2,3]
3
```

I think there are 3 k-diff pairs: `(1, 4), (3, 0), (0, 3)`. However the "expected answer" in the LeetCode system is `2`.

I think the problem should be changed to:
```
A k-diff pair is an integer pair (nums[i], nums[j]), where the following are true:
    0 <= i < nums.length
    0 <= j < nums.length
    i != j
    nums[j] - nums[i] == k
```

#### Code you used for Submit/Run operation

```py
class Solution:
    def findPairs(self, nums: List[int], k: int) -> int:
        a = set()
        b = set()
        for i in nums:
            if i + k in a:
                b.add((i + k, i))   # line 7
                # b.add((i, i + k)) # line 8
            if i - k in a:
                b.add((i - k, i))
            a.add(i)
        return len(b)
```

#### Language used for code
Python 3

#### Screenshots

![图片](https://user-images.githubusercontent.com/9337403/153098723-64bbc49c-cc60-4a82-8491-99528e1d8e06.png)

**Comment by stormsunshine** [comment]
You have pasted part of the problem description where 0 <= i < j < nums.length. Don't you see that i < j?

**Comment by lxylxy123456** [comment]
Yes, I do. As I said, `i=0` and `j=3`. We can clearly see that `i < j`. However, the k-diff pair `(nums[i], nums[j])` is `(3, 1)`. The problem did NOT see `nums[i] < nums[j]`.

**Comment by stormsunshine** [comment]
OK. I agree that the problem description should be updated to make it clear. The problem description should make it clear that each pair (num1, num2) should be only counted once, where pair (num1, num2) and pair (num2, num1) are considered as the same pair.

**Comment by autf** [comment]
It'd better not to use the word `pair` at all, or people will normally assume it means Tuples
But it is in the title and URL https://leetcode.com/problems/k-diff-pairs-in-an-array/
I don't think it's easy to modify that

**Comment by happy-san** [comment]
Same issue, here's the code I submitted.

```c++
class Solution {
public:
    int findPairs(vector<int>& nums, int k) {
        auto pairsCount = 0;
        // <counterpart, isUsed>
        map<int, bool> counterparts;
    
        for (auto n: nums) {
            if (counterparts.count(n) > 0 && !counterparts[n]) {
                pairsCount++;
                counterparts[n] = true;
            }
            
            if (counterparts.count(n - k) == 0) {
                counterparts[n - k] = false;
            }
            
            if (counterparts.count(n + k) == 0) {
                counterparts[n + k] = false;
            }
        }
        
        return pairsCount;
    }
};
```

**Comment by LC-Sue** [comment]
Hi @lxylxy123456 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @lxylxy123456 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
