### ISSUE TITLE
660. Remove 9

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#633]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing test cases or missing description/constraints

#### Code you used for Submit/Run operation

```
class Solution(object):
    def newInteger(self, n):
        z=0
        q=1
        while n:
            z+=(n%9)*q
            n/=9
            q*=10
        return z
```

#### Language used for code
Python

#### Expected behavior
Fails for test case

```
850000000
```

Either this or Integer Max Val constraint should be added

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
