### ISSUE TITLE
Constraint not followed in sample test cases- 532. K-diff Pairs in an Array

### ISSUE THREAD

**Issue by nirajmatere** [LeetCode-Feedback/LeetCode-Feedback#6330]
#### Your LeetCode username
nirajmatere

#### Category of the bug
- [x] Question

#### Description of the bug
in the que it is written 0<=i<j<nums.length, but in the sample test case this constraint is not followed.

#### Code you used for Submit/Run operation
NA
```
// Two Sum
NA
```

#### Additional context

Input: nums = [3,1,4,1,5], k = 2
Output: 2
Explanation: There are two 2-diff pairs in the array, (1, 3) and (3, 5).
 integer pair (nums[i], nums[j]),
therfore i = 1, and j = 0. so i<j is not followed.

**Comment by LC-Sue** [comment]
Hi @nirajmatere 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
