### ISSUE TITLE
Incorrect solution provided for Problem 213.

### ISSUE THREAD

**Issue by NitishSalwan** [LeetCode-Feedback/LeetCode-Feedback#6332]
#### Your LeetCode username

nitish21

#### Category of the bug
- [ ] Question
- [* ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution provided in "Solution" section is incorrect. 

#### Code you used for Submit/Run operation

```
// Leetcode Solution
class Solution {
    public int rob(int[] nums) {
        if (nums.length == 0)
            return 0;

        if (nums.length == 1)
            return nums[0];

        int max1 = rob_simple(nums, 0, nums.length - 2);
        int max2 = rob_simple(nums, 1, nums.length - 1);

        return Math.max(max1, max2);
    }

    public int rob_simple(int[] nums, int start, int end) {
        int t1 = 0;
        int t2 = 0;

        for (int i = start; i <= end; i++) {
            int temp = t1;
            int current = nums[i];
            t1 = Math.max(current + t2, t1);
            t2 = temp;
        }

        return t1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

It does not give correct result for following case:

example: 
array = [11, 2, 3, 14, 5, 16]

this solution gives 32 as answer. 

But the solution should be 41.

array[0] + array[3] + array[5] 
11         +  14        +  16         = 41

**Comment by stormsunshine** [comment]
The first house and the last house are adjacent, so you CANNOT rob both 11 and 16.

**Comment by LC-Sue** [comment]
Hi @NitishSalwan,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! We appreciate your support!
