### ISSUE TITLE
BFS- Template needs python solution

### ISSUE THREAD

**Issue by Shubashree** [LeetCode-Feedback/LeetCode-Feedback#6333]
The BFS template card in https://leetcode.com/explore/learn/card/queue-stack/231/practical-application-queue/1372/, needs a python solution as well, current solution is posted only in Java.

**Comment by LC-Sue** [comment]
Hi @Shubashree 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Shubashree,
Thank you for your time, the team will take this into consideration when the article is next updated!

**Comment by Shubashree** [comment]
Thank you very much. Much appreciated. What is the timeline for this change?

Best,
Shubashree Baskar
