### ISSUE TITLE
Add to problem statement - 23. Merge k Sorted Lists

### ISSUE THREAD

**Issue by DeveloperAlfa** [LeetCode-Feedback/LeetCode-Feedback#6337]
#### Your LeetCode username
developeralfa

#### Category of the bug

-  Language

#### Description of the bug
The constraints don't mention that the lists given are acyclic

#### Expected behavior
You are given an array of k acyclic linked-lists `lists`, each linked-list is sorted in ascending order.

**Comment by LC-Sue** [comment]
Hi @DeveloperAlfa 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @DeveloperAlfa 
Thank you for your time. The linked lists in leet code are acyclic by default, we only mention when they are cyclic. We appreciate your support!
