### ISSUE TITLE
Invaild Test Case - 532. K-diff Pairs in an Array

### ISSUE THREAD

**Issue by Rakesh-Bairwa** [LeetCode-Feedback/LeetCode-Feedback#6339]
#### Your LeetCode username

alex_212

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

nums = [1,2,4,4,3,3,0,9,2,3]
k = 3
here, the possible DISTINCT pairs with k-difference are (1,4) & (0,3). i'm getting output as 2. but solution need 3.

#### Code you used for Submit/Run operation

```
// K-diff Pairs in an Array
class Solution {
public:
    int findPairs(vector<int>& nums, int k) {
        unordered_map<int, int> hsh; // value to make sure distinct
        int count = 0, n = nums.size(), search;
        for (int i = 0; i < n; i++) {
            search = abs(k - nums[i]);
            if (hsh.find(search) != hsh.end() && !hsh[search]) hsh[search]++, count++;
            if (hsh.find(nums[i]) == hsh.end()) hsh[nums[i]] = 0;
        }
        return count;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected output : 2. 

#### Screenshots

![ss](https://user-images.githubusercontent.com/65413333/153218780-3fd09ea2-51b8-47df-84fd-799844796d95.png)

**Comment by stormsunshine** [comment]
Your code outputs 3 and the expected answer is 2. So the expected answer is correct, and you should check your code to find why your code outputs the wrong answer.

**Comment by LC-Sue** [comment]
Hi @Rakesh-Bairwa,
Thank you for reaching out to us, the test case is correct. Please feel free to refer to the discuss section of the problem to see how other users optimized their codes!

**Comment by Rakesh-Bairwa** [comment]
Thank you @LC-Sue for reaching out. Sorry for the silly problem.
