### ISSUE TITLE
271. Encode and Decode Strings

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#634]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing test cases

#### Code you used for Submit/Run operation

```
class Codec:
    def encode(self, strs: [str]) -> str:
        return str(len(strs)) + '\t' + '\t'.join(strs)

    def decode(self, s: str) -> [str]:
        length, *strs = s.split('\t',-1)
        return [] if length == '0' else strs
```

#### Language used for code
Python3

#### Expected behavior
Fails test case

```
["Hello\tt","World"]
```

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. The given test case is invalid because it contains non-ASCII characters. However, we've used your feedback to update the validator. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
