### ISSUE TITLE
566. Reshape the Matrix - MISTAKE IN EXAMPLE 2

### ISSUE THREAD

**Issue by Nideroo** [LeetCode-Feedback/LeetCode-Feedback#6342]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
# Not applicable
```

**Comment by stormsunshine** [comment]
Please read the last sentence before the examples carefully.

> If the `reshape` operation with given parameters is possible and legal, output the new reshaped matrix; Otherwise, output the original matrix.

**Comment by LC-Sue** [comment]
Hi @Nideroo,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts. We appreciate your support!
