### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by zeeshankhan93** [LeetCode-Feedback/LeetCode-Feedback#6344]
#### Your LeetCode username
eeshankhan786

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

I have submitted the code but when I created a custom test case although my output was incorrect the code was accepted.

#### Code you used for Submit/Run operation

```
public string LongestPalindrome(string s) {
        
        string A=s;
        int out_len=1;
        int N = s.Length;
        int index =0;
        int[] result=new int[2];
        for(int i =0;i<N;i++)
        {
           result = isPalindrome(A,i,i);
           if(result[0]>=out_len)
           {
               out_len = result[0];
               index =result[1];
           }
        }
        for(int j =0; j<N;j++)
        {
            result = isPalindrome(A,j,j+1);
            if(result[0]>=out_len)
           {
               out_len = result[0];
               index =result[1];

           }
        }       
        
        return A.Substring(index,out_len);
    }




    public static int[] isPalindrome(string A, int i , int j)
    {
        int N = A.Length;
        int len =0;
        while(i>=0 && j<N && (A[i]==A[j]))
        {
            
            if(i!=j)
            {len+=2;}
            else 
            {len++;}
            
            i--;j++;
            
        }
        return new int[]{len,i+1};
    }
```

#### Additional context
![image](https://user-images.githubusercontent.com/33608323/153259970-9a4110b1-fa8a-4d18-97b1-5da972a701fc.png)

**Comment by stormsunshine** [comment]
The answer does not have to be unique. If there are several longest palindromic substrings, then any of them can be returned. The explanation of example 1 illustrates this.

**Comment by LC-Sue** [comment]
Hi @zeeshankhan93,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! We appreciate your support!
