### ISSUE TITLE
Wording on Problem 532. K-diff Pairs in an Array

### ISSUE THREAD

**Issue by DistilledData** [LeetCode-Feedback/LeetCode-Feedback#6345]
#### Your LeetCode username

CoolAidCode

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Since the problem uses a Cartesian product `(nums[i], nums[j])` in the question, and specifies the condition that `0 <= i < j < nums.length`, this makes it unclear whether `(a,b)` and `(b,a)` for all a,b are considered duplicates. For instance, given the input `[1, 4, 1]` for `k=3`, (1,4) and (4,1) satisfy the constraint, and since this is a Cartesian product the problem is ambiguous whether these are considered a duplicate. 

**Suggestion:** Remove the condition `0 <= i < j < nums.length` and change `(nums[i], nums[j])` to `nums[i] and nums[j]` to make it clearer that the ordering of the numbers in the array is irrelevant.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
  
    }
};
```

#### Language used for code

No code

#### Screenshots

![image](https://user-images.githubusercontent.com/64448266/153264589-58dd057b-1dfc-422f-9fbb-80df9159fb8b.png)

**Comment by LC-Sue** [comment]
Hi @DistilledData 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
