### ISSUE TITLE
Problem 10. Regular Expression Matching - Submission fails yet debugging test case succeeds

### ISSUE THREAD

**Issue by jameskaye** [LeetCode-Feedback/LeetCode-Feedback#6347]
#### Your LeetCode username
OvechkinCodes

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When submitting my code, the below test case fails. When running the same test case in debugger, the code correctly returns "false".

#### Code you used for Submit/Run operation

```
class Solution(object):
    mem = {}
    def isMatch(self, s, p):
        """
        :type s: str
        :type p: str
        :rtype: bool
        """
        val= self.indexedMatch(s,0,p,0,False)
        return val
    
    def indexedMatch(self,s, i, p, j, usedStar):
        if j>len(p)-1 and i>len(s)-1:
            return True
        elif j>len(p)-1 or i>len(s)-1:
            return False
        
        if (i,j) in self.mem:
            return self.mem[(i,j)]
        elif p[j] == "*":
            prev = p[j-1]
            if prev == "." or prev == s[i]:
                self.mem[(i+1, j)] = self.indexedMatch(s,i+1,p,j,True)
                self.mem[(i+1,j+1)] = self.indexedMatch(s,i+1,p,j+1, False)
                return self.mem[(i+1, j)] or self.mem[(i+1,j+1)]
            elif usedStar:
                return False
            else:
                self.mem[i+1,j+1] = self.indexedMatch(s,i+1,p,j+1,False)
                return self.mem[(i+1,j+1)]
        else:
            if s[i] == p[j] or p[j] == ".":
                return self.indexedMatch(s,i+1,p,j+1, False)
            elif j<len(p)-2 and p[j+1] == "*":
                return self.indexedMatch(s,i,p,j+2, False)
            else:
                return False
```

#### Language used for code
Python

#### Expected behavior
Test case should pass:
```
"mississippi"
"mis*is*p*."
```

#### Screenshots
![image](https://user-images.githubusercontent.com/12768179/153293001-ced0a515-ca6d-42d9-a877-7c5346195b33.png)

**Comment by LC-Sue** [comment]
Hi @jameskaye,
Thank you for reaching out to us, our judger is running correctly. It could run in debugger as it may pass a particular test case, but it may not pass all test cases. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes.

**Comment by jameskaye** [comment]
@LC-Sue I should have been more clear - the judger is not running correctly because it claims that my code outputs True on this test case whereas the debugger outputs false:
![image](https://user-images.githubusercontent.com/12768179/153439085-6df8c02e-f00f-4c42-b278-dbfef8937035.png)

**Comment by jameskaye** [comment]
@LC-Sue Do I need to file another item or can this be reopened?

**Comment by LC-Sue** [comment]
Hi @jameskaye,
Thank you for your time, the initial response holds, the judger is running correctly. Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes.
