### ISSUE TITLE
Missing Test Case - 17. Letter Combinations of a Phone Number

### ISSUE THREAD

**Issue by Tanishka-dev** [LeetCode-Feedback/LeetCode-Feedback#6348]
#### Category of the bug
- [ ] Question

#### Description of the bug
If List<String> is returned null, it's value is always [""] but in a test case is asks to return value [ ] when input is "" which is never possible in java;

#### Code you used for Submit/Run operation

```
// Letter Combinations of a Phone Number
class Solution {
    public List<String> letterCombinations(String digits) {
        if(digits=="")
            return new ArrayList();  
         return helper("", digits);       
    }
     List<String> helper(String p, String up){
         if(up.isEmpty()){
             List<String> list= new ArrayList<String>();
             list.add(p);
             return list;
         }
          List<String> list= new ArrayList<String>();       
          int digit=up.charAt(0)-'0';
         for(int i=(digit-2)*3; i<(digit*3)-3;i++){
              char ch=(char)('a'+i);
             list.addAll(helper(p+ch,up.substring(1)));           
         }
         return list;    
     }    
}
```

#### Expected behavior

When ArrayList<String> is returned null or empty then it prints [""] but test case says to print [ ] which is not possiblel

For test case-
input- ""
output should be- [""]
but it is -[ ] which is wrong

**Comment by stormsunshine** [comment]
If the input string is empty, you should return an empty List instance, which means a List instance without any element. The logic is as follows.

```Java
if (digits.length() == 0) {
    return new ArrayList<String>();
}
```

Empty string should not be added into the return list.

**Comment by LC-Sue** [comment]
Hi @Tanishka-dev,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! We appreciate your support!
