### ISSUE TITLE
Wrong constraints - 1338. Reduce Array Size to The Half

### ISSUE THREAD

**Issue by Xascoria** [LeetCode-Feedback/LeetCode-Feedback#6349]
#### Your LeetCode username

Xascoria2

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The constraint of the question is `1 <= arr.length <= 10^5`, but given that `arr.length` has to be even it should have been `2 <= arr.length <= 10^5`
Yes it is a tiny issue but just bringing it up.

**Comment by LC-Sue** [comment]
Hi @Xascoria 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Xascoria 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
