### ISSUE TITLE
778. Swim in Rising Water

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#635]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 3: Minimal Spanning Tree Algorithm (Union-Find) has incorrect analysis

#### Expected behavior

> We iterate through the cells, i.e. N^2 steps. At each step, the union() function requires O(logN) complexity.

The time complexity is correct but union does not require logN time for this implementation. It comes from sorting.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
