### ISSUE TITLE
🚨 请不要悄无声息地关掉 issue 5526; Please do not close issues without fixing it.

### ISSUE THREAD

**Issue by kaiwensun** [LeetCode-Feedback/LeetCode-Feedback#6354]
**你的 LeetCode 用户名**
N/A

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[DD-2020006. 简单游戏](https://leetcode-cn.com/problems/1zD30O/) 依然未在题目列表中恢复。详见 https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/5526

**你使用的语言**
N/A

**你提交或者运行的代码**
N/A

**期望行为**
详见 https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/5526

**屏幕截图**
N/A

**额外的上下文**
N/A

**Comment by LC-Sue** [comment]
Hi @kaiwensun,
Thank you for reaching out to us, as I mentioned in the previous thread the questions are being updated. We do not have an estimated time for when it would be published, as a side note it's also possible that the problem is removed. The content team makes the decisions!

**Comment by kaiwensun** [comment]
Since "the questions are being updated", then why is the issue closed before being fixed?
