### ISSUE TITLE
Description of the Problem No. 560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by harshj11** [LeetCode-Feedback/LeetCode-Feedback#6355]
#### Your LeetCode username
harsh_jain_11

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem description says that return the `total number of continuous subarrays whose sum equals to k`, but in real we just have to find all the subarrays (not the continuous subarrays) whose sum equals to k.

#### Suggestion: 
The problem description could be: Given an array of integers nums and an integer k, return *the total number of subarrays whose sum equals to k*.

#### Code you used for Submit/Run operation

```
class Solution {
    public int subarraySum(int[] nums, int k) {
        return 0;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Let's consider the test case:
`[1,2,1,5,6,4]`
`4`
The number of possible subarrays with sum 4 are two - `[1,2,1]` and `[4]` but if we talk about the continuous subarrays only one of them could be considered.

#### Screenshots
![Problem-Desc](https://user-images.githubusercontent.com/60258934/153407982-48908643-ddeb-4a94-b71d-a20fcd6688f2.png)

![Sample-Test-Case](https://user-images.githubusercontent.com/60258934/153408020-97dba7b9-7e02-432d-a178-7e54a422655c.png)

**Comment by stormsunshine** [comment]
You are not getting the term "continuous" correctly. A subarray is always continuous, so the term "subarray" and the term "continuous subarray" are equivalent. The term "continuous" means that the indices are continuous, not that the values are continuous. Another term is subsequence, which does not require that the indices need to be continuous. A subarray of the original array is always a subsequence of the original array, but not vice versa.

For example, consider the array [2,4,6,8,10]. [2,4,6], [4,6,8] and [6,8,10] are subarrays of the original array, and they are also subsequences of the original array. [2,4,8] is a subsequence of the original array, but it is not a subarray of the original array.

**Comment by harshj11** [comment]
Hi @stormsunshine, hope you are doing well. As we know that arrays store the data at continuous locations and so does the subarrays, and as per you said subarray is always continuous, so I feel that "continuous" is creating confusion and is redundant. (as subarray itself means continuous, that's why)

**Comment by LC-Sue** [comment]
Hi @harshj11 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @harshj11,
Thank you for your time. The problem has been updated to reduce confusion. We appreciate your support!

**Comment by harshj11** [comment]
Hey @LC-Sue, thank you so much. Wish you a great day :smile: Thank you LeetCode team as well.
