### ISSUE TITLE
Solution not accepted - 560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by newearthmartin** [LeetCode-Feedback/LeetCode-Feedback#6358]
#### Your LeetCode username
martinmassera

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
My solution times out but it is the same as the proposed solutions.

#### Code you used for Submit/Run operation
```
class Solution:
    def subarraySum(self, nums: List[int], k: int) -> int:
        total = 0
        len_nums = len(nums)        
        prev_array = [0] * len_nums
        new_array = [0] * len_nums
        for i in range(0, len_nums):
            for j in range(i, len_nums):
                if i == 0:
                    new_array[j] = nums[j]
                else:
                    new_array[j] = nums[j] + prev_array[j-1]
                if new_array[j] == k:
                    total += 1
            prev_array, new_array = new_array, prev_array
        return total
```

#### Language used for code
Python 3

#### Expected behavior
This is the same as `Approach 2: Using Cumulative Sum`. It should not time out.

**Comment by stormsunshine** [comment]
The maximum length of `nums` can be 20000, so a solution with O(n<sup>2</sup>) is very likely to get TLE. A solution with O(n) is expected.

Since your issue is about the solution, why are you putting "Missing Test Case" in the title?

**Comment by newearthmartin** [comment]
> The maximum length of `nums` can be 20000, so a solution with O(n2) is very likely to get TLE. A solution with O(n) is expected.

Ah I see, just because the answer is in the solution tab does not mean it is accepted

> Since your issue is about the solution, why are you putting "Missing Test Case" in the title?

Didnt realize, it was auto generated

**Comment by LC-Sue** [comment]
Hi @newearthmartin,
Thank you for reaching out to us! I'm glad stormsunshine's response was able to resolve the confusion!
