### ISSUE TITLE
1514. Path with Maximum Probability

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#636]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Misleading hint

#### Expected behavior
Hint 1

> Multiplying probabilities will result in precision errors.

This is misleading and demonstrably false as so many submissions have worked with this approach.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @leet212 
The team reviewed your report and decided not to update the problem since all 3 hints have to be read sequentially in order to understand a possible solution.
