### ISSUE TITLE
Missing Test Case - 176. Second Highest Salary

### ISSUE THREAD

**Issue by HowieHowieWow** [LeetCode-Feedback/LeetCode-Feedback#6360]
#### Your LeetCode username
howiehowiewow

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [check] Missing Test Cases 

#### Description of the bug

When using the window function, the rank()function is not working, must use dense_rank() function instead.

#### Code you used for Submit/Run operation
Try this testcase:
'''
{"headers":{"Employee":["id","salary"]},"rows":{"Employee":[[1,100],[2,100],[3,50],[4,40]}}
'''
When using the window function, the rank() function is not working, must use dense_rank() function instead. Because  when using the above test case, rank() function will get [null]  as second highest salary, however the right answer is 50, which is the result of using dense_rank() function.

#### Language used for code
Mysql
MS SQL Server

#### Expected behavior
{"headers": ["SecondHighestSalary"], "values": [[50]]}

#### Screenshots

<img width="1342" alt="Mysql" src="https://user-images.githubusercontent.com/36777545/153450781-bd77e362-5e77-479f-b295-2e848a067d9e.png

![MsSQL](https://user-images.githubusercontent.com/36777545/153451250-4c50519f-3ac4-46de-8a27-e8f8bfec1c8d.jpeg)

**Comment by LC-Sue** [comment]
Hi @HowieHowieWow,
Thank you for reaching out to us, the code you used for submission already TLE from a previously added test case! We appreciate your support!
