### ISSUE TITLE
Missing Test Case Checks- 348. Design Tic-Tac-Toe

### ISSUE THREAD

**Issue by aryanraja1072** [LeetCode-Feedback/LeetCode-Feedback#6361]
#### Your LeetCode username

aryanraja1072

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases

#### Description of the bug

The test case is **_not_** considered invalid when, unlike when the assumption, placing a move on occupied cell, is violated:
  - the moves exist beyond the game ending move( when a player wins )
  - the moves are not of alternate players, like after player 1, only player 2 should move or vice-versa

**Example Test Case:**
```
["TicTacToe","move","move","move","move","move","move","move","move","move"]
[[3],[0,0,1],[0,2,2],[1,2,1],[1,1,2],[1,0,1],[2,0,2],[2,1,1],[2,2,1],[0,1,2]]
```
**LC Grader's Output(Expected output):**
`[null,0,0,0,0,0,2,1,1,2]`

**Observation:**  After move 6, when player 2 wins, one can continue adding moves. Also, move 8 should be invalid as the players are not alternating. 
**Also**, LC grader's output doesn't seem right as it outputs player 1 as winner after it outputs player 2 as winner and again player 2 in the last move.

**My Code Output:**
`[null,0,0,0,0,0,2,0,0,0]`

#### Code you used for Submit/Run operation

```
class TicTacToe {
    int[][] grid;
    int n;
    public TicTacToe(int n) {
        grid = new int[n][n];
        this.n = n;
    }
    int checkRow(int i, int j, int player){
        int count = 0;
        for(int k=0;k<n;k++){
            if(grid[i][k]==player){
                count++;
            }
        }
        return count;
    }
    int checkCol(int i, int j, int player){
        int count = 0;
        for(int k=0;k<n;k++){
            if(grid[k][i]==player){
                count++;
            }
        }
        return count;
    }
    
    int checkDiag1(int i, int j, int player){
        if(i!=j)
            return 0;
        int count = 0;
        for(int k=0;k<n;k++){
            if(grid[k][k]==player){
                count++;
            }
        }
        return count;
    }
    int checkDiag2(int i, int j, int player){
        if(i!=n-j-1)
            return 0;
        int count = 0;
        for(int k=0;k<n;k++){
            if(grid[k][n-k-1]==player){
                count++;
            }
        }
        return count;
    }
    
    
    public int move(int row, int col, int player) {
        grid[row][col] = player;
        if(checkRow(row,col,player)==n ||checkCol(row,col,player)==n ||checkDiag1(row,col,player)==n ||checkDiag2(row,col,player)==n){
            return player;
        }
        return 0;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The cases having above mentioned properties should be considered invalid.

**Comment by LC-Sue** [comment]
Hi @aryanraja1072,
Thank you for reaching out to us, the code you provided returns wrong answer from the test case ["TicTacToe","move","move","move"]
[[3],[0,0,2],[2,0,2],[1,0,2]]
Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
