### ISSUE TITLE
Typo in Graph Explore Card

### ISSUE THREAD

**Issue by doublemul** [LeetCode-Feedback/LeetCode-Feedback#6362]
#### Your LeetCode username
isDoubleMU

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In `Graph Explore Card`->`Algorithms to Construct Minimum Spanning Tree`->`Kruskal’s Algorithm`->`Why does Kruskal’s Algorithm only choose N-1 edges?`, here is the original text:
>In the following video, we'll prove that we need to choose exactly N-1 edges of the graph with N **edges** in total to construct a “minimum spanning tree” of that graph.

The **edges** should be **vertices**.

#### Expected behavior

>In the following video, we'll prove that we need to choose exactly N-1 edges of the graph with N **vertices** in total to construct a “minimum spanning tree” of that graph.

#### Screenshots

![screenshot](https://user-images.githubusercontent.com/44038761/153453979-c8e27f81-8418-4578-9e06-c078a69da7c9.png)

**Comment by LC-Sue** [comment]
Hi @doublemul 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @doublemul 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
