### ISSUE TITLE
Incorrect - 2157. Groups of Strings

### ISSUE THREAD

**Issue by tummalavandana** [LeetCode-Feedback/LeetCode-Feedback#6363]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

 If we take anagrams such as ["dog","god"]   the out put is coming as 1,2 which means number of groups is one and maximum number of words in group is 2 but dog and god cannot be obtained by any of given logic  below
 Adding exactly one letter to the set of the letters of s1.
Deleting exactly one letter from the set of the letters of s1.
Replacing exactly one letter from the set of the letters of s1 with any letter, including itself..Adding exactly one letter to the set of the letters of s1.
Deleting exactly one letter from the set of the letters of s1.
Replacing exactly one letter from the set of the letters of s1 with any letter, including itself.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Soumit915** [comment]
Hi, the operation: Replacing exactly one letter from the set of the letters of s1 with any letter, including itself, actually means that you may not change the s1 or s2 at all.
