### ISSUE TITLE
Construct Binary Search Tree from Preorder Traversal

### ISSUE THREAD

**Issue by soni113** [LeetCode-Feedback/LeetCode-Feedback#6364]
class Solution {
    public TreeNode bstFromPreorder(int[] preorder) {
        return helper(preorder,0,preorder.length);
        
    }
    public TreeNode helper(int[] preorder,int rootindex,int right){
        if(rootindex>=right)
            return null;
        int value = preorder[rootindex];
        TreeNode root = new TreeNode(value);
        int i  = rootindex+1;
        while(i<=preorder.length-1 && preorder[i]<value)
            i++;
        root.left = helper(preorder,rootindex+1,i);
        root.right = helper(preorder,i,right);
        return root;
    }
}

**Comment by LC-Sue** [comment]
Hi @soni113 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
