### ISSUE TITLE
Missing Test Case - 1008. Construct Binary Search Tree from Preorder Traversal

### ISSUE THREAD

**Issue by soni113** [LeetCode-Feedback/LeetCode-Feedback#6365]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @soni113 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
