### ISSUE TITLE
Missing Test Case - 138. Copy List with Random Pointer

### ISSUE THREAD

**Issue by ZhengruiLu** [LeetCode-Feedback/LeetCode-Feedback#6367]
#### Category of the bug
- [138] Question
- [1] Solution
- [Java ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The definition for a Node says the Node has one parameter - val, but in solutions 1 and 2, when creating a new copy node, it creates a new Node with 3 parameters(val, null, null). And it can pass. 

#### Code you used for Submit/Run operation

```
/*
// Definition for a Node.
class Node {
    int val;
    Node next;
    Node random;

    public Node(int val) {
        this.val = val;
        this.next = null;
        this.random = null;
    }
}
*/

class Solution {
    
    HashMap<Node, Node> map = new HashMap<Node, Node>();
    
    public Node copyRandomList(Node head) {
        if (head == null){
            return null;
        }
        
        if (this.map.containsKey(head)){
            return this.map.get(head);
        }
        
        Node node = new Node(head.val);//this line need to fix
        this.map.put(head, node);
        
        node.next = this.copyRandomList(head.next);
        node.random = this.copyRandomList(head.random);
        
        return node;
    }
}
```

#### Expected behavior

1.Change the solution 1 - line 34 to correct answer

Original
'''
    Node node = new Node(head.val, null, null);
'''

Correct:
'''
    Node node = new Node(head.val);
'''

2. Change the solution 2 - line 30 to correct answer
Original
'''
    this.visited.put(node, new Node(node.val, null, null));
'''

Correct:
'''
    this.visited.put(node, new Node(node.val));
'''

**Comment by LC-Sue** [comment]
Hi @ZhengruiLu,
Thank you for reaching out to us, the intuitions of the approaches in the solution are well explained in the text. Feel free to explore the explanations, please also feel free to refer to the discuss section of the problem to see how other user's optimized their codes!
