### ISSUE TITLE
[374. Guess Number Higher or Lower] Rust initial comment snippet is incorrect

### ISSUE THREAD

**Issue by Kapporing** [LeetCode-Feedback/LeetCode-Feedback#6368]
#### Your LeetCode username
Kapporing

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The initial comment snippet for the `Rust` language is incorrect.
```
/** 
 * Forward declaration of guess API.
 * @param  num   your guess
 * @return 	     -1 if num is lower than the guess number
 *			      1 if num is higher than the guess number
 *               otherwise return 0
 * unsafe fn guess(num: i32) -> i32 {}
 */
```
should be
```
/** 
 * Forward declaration of guess API.
 * @param  num   your guess
 * @return    -1 if num is ~~lower~~ higher than the guess number
 *		    1 if num is ~~higher~~ lower than the guess number
 *               otherwise return 0
 * unsafe fn guess(num: i32) -> i32 {}
 */
```

#### Code you used for Submit/Run operation
N/A

#### Language used for code
Rust

#### Expected behavior
```
/** 
 * Forward declaration of guess API.
 * @param  num   your guess
 * @return    -1 if num is ~~lower~~ higher than the guess number
 *		    1 if num is ~~higher~~ lower than the guess number
 *               otherwise return 0
 * unsafe fn guess(num: i32) -> i32 {}
 */
```

#### Screenshots
N/A

#### Additional context
N/A

**Comment by LC-Sue** [comment]
Hi @Kapporing 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Kapporing 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
