### ISSUE TITLE
Week test cases in ongoing July leetcoding challenge, problem:Same tree. Wrong code is getting accepted.

### ISSUE THREAD

**Issue by saurabhsisodia** [LeetCode-Feedback/LeetCode-Feedback#637]
#### Your LeetCode username
saurabh_sisodia

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Suppose the first tree is ```[1,2,3,null,null,4,5]``` and the second tree is ```[1,2,3]```, as they are not same tree so answer should be <strong>false</strong> and leetcode is also giving <strong>false</strong>, but my code is giving <strong>true</strong> and still accepted by Leetcode.
I think there are test cases like this which should be included in this problem. 

#### Code you used for Submit/Run operation

```
// Same Tree
def isSameTree(self, p: TreeNode, q: TreeNode) -> bool:

        if not p and not q:
            return True
        if (not p and q) or (not q and p):
            return False
        q1,q2=deque(),deque()
        s1=(p.val,1,p)
        s2=(q.val,1,q)
        q1.append(s1)
        q2.append(s2)
        while q1 and q2:
            value1,number1,node1=q1.popleft()
            value2,number2,node2=q2.popleft()
            if value1!=value2 or number1 !=number2:
                return False
            
            if node1.left:
                q1.append((node1.left.val,number1*2,node1.left))
            if node1.right:
                q1.append((node1.right.val,number1*2+1,node1.right))
            if node2.left:
                q2.append((node2.left.val,number2*2,node2.left))
            if node2.right:
                q2.append((node2.right.val,number2*2+1,node2.right))
        return True
```

#### Language used for code
Python 3.6

#### Expected behavior
```
inputs-:
[1,2,3,null,null,4,5]
[1,2,3]

Expected answer-: false
My answer:- true
```

**Comment by lc-christina** [comment]
Hi @saurabhsisodia 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @saurabhsisodia 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
