### ISSUE TITLE
Missing Test Case - 1944. Number of Visible People in a Queue

### ISSUE THREAD

**Issue by rofrankel** [LeetCode-Feedback/LeetCode-Feedback#6371]
#### Your LeetCode username

rofrankel

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Example one seems to have the wrong result:

Input: heights = [10,6,8,5,11,9]
Output: [3,1,2,1,1,0]

The first value in the output should be 4, rather than 3, because the person of height 10 can see 4 people:  6, 8, 5, and 11.  I don't think I'm misunderstanding; it seems the same as the rationale for the person of height 8 being able to see two people (5 and 11).

#### Code you used for Submit/Run operation

N/A

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

N/A

#### Expected behavior

N/A

**Comment by stormsunshine** [comment]
The person of height 10 cannot see person of height 5. Please read the problem description carefully.
> A person can see another person to their right in the queue if everybody in between is shorter than both of them.

**Comment by LC-Sue** [comment]
Hi @rofrankel,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Feel free to reach out again if you have any other questions!
