### ISSUE TITLE
Typo in 567. Permutation in String

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6372]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[567. Permutation in String](https://leetcode.com/problems/permutation-in-string/)

From Approach 2 to 6, they all have the typo in Time Complexity Analysis of the following description:

"where`l_1` is the length of string `l_1` and `l_2` is the length of string `l_2`"

#### Expected behavior

It should be

"where`l_1` is the length of string `s_1` and `l_2` is the length of string `s_2`"

#### Additional context

Only Approach 1 uses variable `n` in the complexity analysis. I think it should be variable `l1` to be consistent with other Approaches.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
