### ISSUE TITLE
Misalignment of Italic letter in the 567: Permutation in String

### ISSUE THREAD

**Issue by giriteja94495** [LeetCode-Feedback/LeetCode-Feedback#6374]
#### Category of the bug
- [ ] Question
- [ yes] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a misalignment of the italic letter in the solution 

#### Expected behavior

This is how it should be 👍🏼 

To do so, permute takes the index of the current element current_indexcurrent 
index as one of the arguments.

#### Screenshots
<img width="739" alt="Screenshot 2022-02-11 at 8 53 52 PM" src="https://user-images.githubusercontent.com/51397347/153619959-959bffd6-4183-4096-a204-dbc7c097da54.png">

**Comment by LC-Sue** [comment]
Hi @giriteja94495 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @giriteja94495,
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
