### ISSUE TITLE
Inconsistent Time Limit Exceed Result - 282. Expression Add Operators

### ISSUE THREAD

**Issue by Xascoria** [LeetCode-Feedback/LeetCode-Feedback#6375]
#### Your LeetCode username

Xascoria2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The code seems to hit the exact sweet spot near the limit between accepted solution and `Time Limit Exceeded`. The same exact code has failed on case 13, 15 and 20 separately. Even more importantly, the code has *NEVER* exceeded time limit while testing the result with `Run Code Result` on every of those cases. Just to make sure, I've run case 13 10 times in the console, it never timed out once.

#### Code you used for Submit/Run operation

```
class Solution:
    def addOperators(self, num: str, target: int) -> List[str]:
        arr = [*num]
        output = []
        if "00" in num:
            for i in itertools.product(['+','-','*',''],repeat = len(arr)-1):
                fs = ''.join( j+k for j,k in zip(arr,i) ) + arr[-1]
                if "00" in fs:
                    if fs[:2]=="00"or "+00" in fs or "-00" in fs or "*00" in fs:
                        continue
                try:
                    if eval(fs) == target:
                        output.append(fs)
                except:pass
            return output
        for i in itertools.product(['+','-','*',''],repeat = len(arr)-1):
            fs = ''.join( j+k for j,k in zip(arr,i) ) + arr[-1]
            try:
                if eval(fs) == target:
                    output.append(fs)
            except:pass
        return output
```

#### Language used for code

Python

#### Expected behavior

Not sure, either has a more accurate console time limit calculation, or just accept the solution?

**Comment by LC-Sue** [comment]
Hi @Xascoria,
Thank you for reaching out to us, our judger appears to be running correctly. When you "run" the code, it doesn't run all test cases, when you "submit" it runs all test cases which is why it does not time out in run but could time out in submit. Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
