### ISSUE TITLE
Some error in Test Case - 13. Roman to Integer with C#

### ISSUE THREAD

**Issue by ErickFocil** [LeetCode-Feedback/LeetCode-Feedback#6376]
I made some code to the problem and it work with the examples except with the Thrith example, but the error its not in the algoritm, it is in the first array to create ("cdic") the error is System.IndexOutOfRangeException but it dosn't with oter examples, and it not be a problem , i dont know if i lose some thing or its a error that i cant controll.

My code :D

public class Solution {
    public int RomanToInt(string s) {
        char[] cdic = new char[] {'I','V','X','L','C','D','M'};
        int[] ndic = new int[] {1,5,10,50,100,1000};
        char[] cdata = s.ToCharArray();
        int[] ndata = new int[cdata.Length];
        for(int i = 0; i < cdata.Length; i++){
            for(int j = 0; j < cdic.Length; j++){
                if(cdata[i].Equals(cdic[j])){
                    ndata[i] = ndic[j];
                    break;
                }
            }
        }
        int r = 0;
        for(int i = 0; i < ndata.Length; i++){
            if(i < ndata.Length-1){
               if(ndata[i] < ndata[i+1]){
                   r += ndata[i+1] - ndata[i];
                   i++;
               }else{
                   r += ndata[i];
               }
            }else{
                r += ndata[i];
            }
        }
        return r;
    }
}

**Comment by LC-Sue** [comment]
Hi @ErickFocil,
Thank you for your time we're sorry for not getting to you sooner, but I'm glad your issue has been resolved!
