### ISSUE TITLE
open-the-lock problem missing test cases

### ISSUE THREAD

**Issue by dlitvak** [LeetCode-Feedback/LeetCode-Feedback#638]
#### Your LeetCode username
dilit

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
There are test cases missing for https://leetcode.com/problems/open-the-lock
https://leetcode.com/submissions/detail/366158257/ passed.
My test case: Solution().openLock(["1000","0100","0010","0001",'9000','0900','0090','0009'], "0202") should return -1.
The code I submitted returns 4.

#### Code you used for Submit/Run operation
https://leetcode.com/submissions/detail/366158257

```
from collections import deque

class Solution:
    def openLock(self, deadends: List[str], target: str) -> int:
        def dist(code):
            return sum(min(int(c), 10-int(c)) for c in code)
		
        def neighbors(code):
            for i in range(4):
                x = int(code[i])
                yield code[:i] + str((x - 1) % 10) + code[i + 1:]
                yield code[:i] + str((x + 1) % 10) + code[i + 1:]
		
        deadends = set(deadends)
        if '0000' in deadends or target in deadends: return -1
        last_moves = set(neighbors(target)) - deadends
        if not last_moves: return -1
        ans = dist(target)
        for code in last_moves:
            if dist(code) < ans: return ans
        return ans + 2
```

#### Language used for code
Python3 

#### Expected behavior
My code submission should have failed.

**Comment by lc-christina** [comment]
Hi @dlitvak ,
Thanks for reaching out to us. I've tested your code and test case you provided but received runtime error. Would you mind check again and let me know if you still receive wrong answer when testing on the console? Please see the screenshot attached for more details. 
<img width="1667" alt="Screen Shot 2020-07-14 at 10 19 48 AM" src="https://user-images.githubusercontent.com/67175512/87456689-24ca9080-c5bc-11ea-96f1-3c2bd746d6f0.png">
<img width="1114" alt="Screen Shot 2020-07-14 at 10 20 03 AM" src="https://user-images.githubusercontent.com/67175512/87456696-285e1780-c5bc-11ea-801c-2a63373df9fa.png">

**Comment by dlitvak** [comment]
@lc-pam Christina,
The leetcode judge does not accept single quote string inputs like '0200'.  It wants "0200".
Try 
["1000","0100","0010","0001","9000","0900","0090","0009"]
"0202"


> Hi @dlitvak ,
> Thanks for reaching out to us. I've tested your code and test case you provided but received runtime error. Would you mind check again and let me know if you still receive wrong answer when testing on the console? Please see the screenshot attached for more details.
> <img alt="Screen Shot 2020-07-14 at 10 19 48 AM" width="1667" src="https://user-images.githubusercontent.com/67175512/87456689-24ca9080-c5bc-11ea-96f1-3c2bd746d6f0.png">
> <img alt="Screen Shot 2020-07-14 at 10 20 03 AM" width="1114" src="https://user-images.githubusercontent.com/67175512/87456696-285e1780-c5bc-11ea-801c-2a63373df9fa.png">

**Comment by lc-pam** [comment]
Hi @dlitvak 
Thanks for the clarification. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @dlitvak 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
