### ISSUE TITLE
Bug: [Time Limit Exceeded] - 332. Reconstruct Itinerary

### ISSUE THREAD

**Issue by MToolmaker** [LeetCode-Feedback/LeetCode-Feedback#6381]
Please look at the last comment in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/6353

**Comment by LC-Sue** [comment]
Hi @MToolmaker 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @MToolmaker,
Thank you for your time. TLE depends on the sum of time spent on all test cases that are run.
