### ISSUE TITLE
Typo of 127. Word Ladder

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6383]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[127. Word Ladder](https://leetcode.com/problems/word-ladder/)

![image](https://user-images.githubusercontent.com/31957845/153705739-46e1a2e3-565d-47e5-807b-faf020a8ed5f.png)

In the graph above (Approach 2), it writes "Distance - L1 + L2", but I believe it should be "Distance = L1 + L2".

#### Expected behavior

Change the image to image with correct words.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw,
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
