### ISSUE TITLE
Wrong testcase

### ISSUE THREAD

**Issue by karthik2265** [LeetCode-Feedback/LeetCode-Feedback#6386]
#### Your LeetCode username

karthik2265

#### Category of the bug
wrong testcase

#### Description of the bug

question no: 2035. Partition Array Into Two Arrays to Minimize Sum Difference

the test case no 25 : [76,8,45,20,74,84,28,1]
the correct output is '0' since the array can be partitioned into 2 equal subsets i.e [76, 8, 84] and [45, 20, 74, 28, 1] so the absolute min sum difference would be '0'.

But it says expected output is '2'

#### Code you used for Submit/Run operation

```python
class Solution:
    def recursive(self, arr, currIdx, currSum, total, mem, absSum):
        if currIdx >= len(arr) and currSum == 0: return absSum
        if currIdx >= len(arr): return abs(currSum - (total - currSum))
        if mem[currIdx][currSum] != -1: return mem[currIdx][currSum]
        x = arr[currIdx]
        mem[currIdx][currSum] = min(self.recursive(arr, currIdx + 1, currSum + x, total, mem, absSum), self.recursive(arr, currIdx + 1, currSum, total, mem, absSum))
        return mem[currIdx][currSum]
    
    def minimumDifference(self, nums: List[int]) -> int:
        total = sum(nums)
        absSum = 0
        for num in nums: absSum += abs(num)
        mem = [[-1 for _ in range(absSum + 1)] for _ in range(len(nums))]
        return self.recursive(nums, 0, 0, total, mem, absSum)
```

#### Language used for code

python

**Comment by stormsunshine** [comment]
This problem requires partitioning the original array into two arrays **of equal length**. Therefore, the way of partitioning the array you provide in this issue is invalid.

**Comment by karthik2265** [comment]
Oh, the question wasn't very clear about that

Thanks for answering

**Comment by LC-Sue** [comment]
Hi @karthik2265,
Thank you for reaching out to us, I'm glad your issue has been resolved! Feel free to reach out to us again if you have any other questions!
