### ISSUE TITLE
Missing testcase for problem 365. Water and Jug Problem

### ISSUE THREAD

**Issue by Sky-Nik** [LeetCode-Feedback/LeetCode-Feedback#639]
#### Your LeetCode username
nskybytskyi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing testcase:
```
Your input: 2 0 2
Output: false
Expected: true
```

#### Code you used for Submit/Run operation

```python
class Solution:
    def canMeasureWater(self, x: int, y: int, z: int) -> bool:
        return x and y and z % math.gcd(x, y) == 0 and z <= x + y or not z

```

#### Language used for code
python3

#### Expected behavior

The solution above is accepted as visible below, but should not be.

#### Screenshots

![tmp](https://user-images.githubusercontent.com/25816558/87392772-c6021880-c5b5-11ea-9d99-b3160a176faa.png)

**Comment by lc-christina** [comment]
Hi @Sky-Nik 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @Sky-Nik 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
