### ISSUE TITLE
Bug In Java Checker for Maximum And Sum Of Array in Weekly Contest 280

### ISSUE THREAD

**Issue by Soumit915** [LeetCode-Feedback/LeetCode-Feedback#6390]
#### Your LeetCode username

soumit915

#### Category of the bug
- [ ] Solution
- [ ] Language

#### Description of the bug

Bug In Java Checker for Weekly Contest 280 in Problem Maximum AND Sum of Array

#### Code you used for Submit/Run operation

```
class Solution {
    
    static int max = 0;
    static Map<String, Integer> map;

    static String getString(int[] arr){
        StringBuilder sb = new StringBuilder();
        for(int i=1;i<arr.length;i++){
            sb.append(arr[i]);
        }

        return sb.toString();
    }

    static int get(int[] nums, int[] hash, int sum, int index){
        if(index >= nums.length){
            max = Math.max(max, sum);
            return 0;
        }

        if(map.containsKey(getString(hash))){
            max = Math.max(max, map.get(getString(hash)) + sum);
            return map.get(getString(hash));
        }

        int cmax = 0;
        for(int i=1;i<hash.length;i++){
            if(hash[i] == 2){
                continue;
            }

            hash[i]++;
            sum = sum + (i & nums[index]);

            int val = get(nums, hash, sum, index+1);
            cmax = Math.max(cmax, val + (nums[index] & i));

            sum = sum - (i & nums[index]);
            hash[i]--;
        }

        map.put(getString(hash), cmax);
        return cmax;
    }

    public static int maximumANDSum(int[] nums, int numSlots) {
        int[] hash = new int[numSlots+1];
        map = new HashMap<>();
        get(nums, hash, 0, 0);

        return max;
    }
}

```

#### Language used for code

Java

In [Leetcode Weekly Contest - 280](https://leetcode.com/contest/weekly-contest-280/) and for problem [Maximum AND Sum of Array](https://leetcode.com/problems/maximum-and-sum-of-array/) , I encountered something uneven with the Java checker.

<img width="960" alt="leetcode bug in java code" src="https://user-images.githubusercontent.com/46458047/153739077-5a15a154-ca11-4831-9509-c6a11bae4810.png">

When I was submitting my code it is saying my output and expected output are not same as you can see, like the expected output was 16 and they were telling my output as 40, however, when I run it in the leetcode compiler, the same code runs exactly correctly giving the expected output of 16 for the same test-case.

Please correct this bug and help me, else I might loose a lot of rating points and confidence most importantly. Please help!!!

**Comment by susanth29** [comment]
https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

**Comment by stormsunshine** [comment]
The reason is that you have used static variables. To avoid such issues, do not use static variables.

**Comment by LC-Sue** [comment]
Hi @Soumit915,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts!
