### ISSUE TITLE
Weird underlines in the question 2114  :Maximum Number of Words Found in Sentences in the example test cases 

### ISSUE THREAD

**Issue by giriteja94495** [LeetCode-Feedback/LeetCode-Feedback#6391]
#### Your LeetCode username
lucy94495

#### Category of the bug
- [ ✅] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a unwanted underline in the example test cases of the problem 2114 : Please remove that for good user experience 

#### Expected behavior

The underlines in the example test cases should be removed

#### Screenshots

<img width="890" alt="Screenshot 2022-02-13 at 11 06 01 AM" src="https://user-images.githubusercontent.com/51397347/153740365-27f82744-e74e-47f1-b6b6-61f3bc03764a.png">

**Comment by LC-Sue** [comment]
Hi @giriteja94495 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @giriteja94495,
Thank you for your time, our team believes the current question is fine the way it is! We appreciate your support!
