### ISSUE TITLE
Missing Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by zawlurnthan** [LeetCode-Feedback/LeetCode-Feedback#6392]
#### Your LeetCode username
 zthan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Can't figure out where is wrong. I believe I'm right.

#### Code you used for Submit/Run operation
``` class Solution {
    public boolean checkIfExist(int[] arr) {
        
        for (int i : arr) {
            for (int j : arr) {
                if (i == 2 * j) {
                    return true;
                }
                if(i == j / 2 && j % 2 == 0){
                    return true;
                }
            }
        }
        return false;
    }
}
```

#### Language used for code
java

#### Expected behavior
input: arr = [-2, 0, 10, -19, 4, 6, -8]
my result was "true", But LeetCode expect "false".

![image](https://user-images.githubusercontent.com/37648883/153741778-3c4c0cc5-a54e-4de6-88ac-f9e7de50a466.png)

**Comment by stormsunshine** [comment]
The same element can't be selected twice. Although there exists a value 0, since the value 0 only exists once, it can't be selected twice, so the answer should be false.

**Comment by zawlurnthan** [comment]
Thank you. It works after adding to if statement to check not equal index.
