### ISSUE TITLE
Missing Test Case - 381. Insert Delete GetRandom O(1) - Duplicates allowed

### ISSUE THREAD

**Issue by abhinandanmishra1** [LeetCode-Feedback/LeetCode-Feedback#6395]
#### Your LeetCode username
abhinandan_mishra_1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✔️] Missing Test Cases 

#### Description of the bug
In the problem, we have to store indexes of all the elements (as many times it appears) but they should be stored in sorted order because while removing a particular element we want the last greatest index of that element.

In the problem, there is a single test case of size 2 that handles the condition of storing the elements in sorted order(ascending order). 

- **Only Test Case present in the problem handling the condition of storing index arrays in ascending order**
  Input 
  ```
  ["RandomizedCollection","insert","insert","insert","insert","insert","insert","remove","remove","remove","remove","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom"]
  [[],[10],[10],[20],[20],[30],[30],[10],[10],[30],[30],[],[],[],[],[],[],[],[],[],[]]
  ```
  Expected Output:
  ```
  [null,true,false,true,false,true,false,true,true,true,true,20,20,20,20,20,20,20,20,20,20]
  ```
#### Code you used for Submit/Run operation

```
// Insert Delete GetRandom O(1) - Duplicates allowed

class RandomizedCollection {
public:
    unordered_map<int,vector<int>> mp;
    int index;
    vector<int> arr;
    RandomizedCollection() {
        mp.clear();
        index=0;
        arr.clear();
    }
    
    bool insert(int val) {
        if(mp[val].size()>0){
            mp[val].push_back(index);
            arr.push_back(val);
            index++;
            return false;
        }  
        mp[val].push_back(index);
        arr.push_back(val);
        index++;
        return true;
    }
    
    bool remove(int val) {
        if(mp[val].size()>0){
            
            int ind=mp[val].back();
            if(ind==(index-1)){
                arr.pop_back();
                index--;
                mp[val].pop_back();
            }else{
                mp[val].pop_back();
                swap(arr[ind],arr[index-1]);
                
                mp[arr[ind]].pop_back();
                mp[arr[ind]].push_back(ind);
                val=arr[ind];
                if(mp[val].size()==2){
                sort(mp[val].begin(),mp[val].end());
                
            }
            
            arr.pop_back();
            index--;
            }
            
            return true;
        }
        return false;
    }
    
    int getRandom() {
        int n=rand()%index;
        return arr[n];
    }
};


```

#### Language used for code
C++

#### Expected behavior
This code is wrong because it's not handling the case when the stored index is not in sorted order and the size of the array of indexes for that element is greater than 2.
**Explanation of Above Statement**
Like for test case :
Input
```
["RandomizedCollection","insert","insert","insert","insert","insert","insert","insert","insert","insert","remove","remove","remove","remove","remove","remove","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom"]
[[],[10],[10],[10],[20],[20],[20],[30],[30],[30],[10],[10],[10],[30],[30],[30],[],[],[],[],[],[],[],[],[],[]]
```
Expected Output:
```
[null,true,false,false,true,false,false,true,false,false,true,true,true,true,true,true,20,20,20,20,20,20,20,20,20,20]
```
But the output of my code is **(Not the same as expected output)** :
```
[null,true,false,false,true,false,false,true,false,false,true,true,true,true,true,true,30,30,20,30,30,30,30,20,20,30]
```

My code is wrong but it got accepted. 

#### Screenshots

- Screenshot 1 **(My code is giving wrong answer for this test case)**
![image](https://user-images.githubusercontent.com/64205626/153751012-966f28de-745f-4069-b1e5-39c4b1077d7e.png)

- Screenshot 2 **(But my code got accepted)**
![ss](https://user-images.githubusercontent.com/64205626/153751074-1b30278a-094f-458d-996c-e018115ce1bc.png)

#### Additional context

- You can add more test cases like inserting some elements an equal number of times then start removing in an order such that a case comes where the index array of an element becomes unsorted or not in ascending order.
- Like if we insert 10 four times, 11 four times, and 15 four times then remove all the indexes of 10 followed by removal of all the indexes of 15 will give a case of ascending order of indexes.
- In the problem, there is already a test case for an index array of size 2 is available. Just add some more test cases of greater size.

**Comment by LC-Sue** [comment]
Hi @abhinandanmishra1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @abhinandanmishra1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
