### ISSUE TITLE
Bug in ranklist on last contest

### ISSUE THREAD

**Issue by emli** [LeetCode-Feedback/LeetCode-Feedback#64]
![image](https://user-images.githubusercontent.com/5517490/77241661-92267000-6c1f-11ea-9434-cef9176879ed.png)

**Comment by CooperCooperCooper** [comment]
Hi @emli,
Thank you for reaching out to us. Since your issue is related to the contests, please share them with us in this support channel: https://support.leetcode.com/hc/en-us. We appreciate your time and support.
