### ISSUE TITLE
190. Reverse Bits

### ISSUE THREAD

**Issue by artak-kirakosyan** [LeetCode-Feedback/LeetCode-Feedback#640]
#### Your LeetCode username
pythoff

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
When an invalid testcase is attempted to try out, the program gives "Server Error" message.

#### Code you used for Submit/Run operation

```
class Solution:
    def reverseBits(self, n: int) -> int:
        res = 0
        i = 0
        while i < 32:
            i += 1
            res <<= 1
            res += n % 2
            n >>= 1
        return res

```

#### Language used for code
python3

#### Expected behavior
A correct response would be to print out that the testcase is invalid.

#### Screenshots
![image](https://user-images.githubusercontent.com/23319356/87397010-c229c280-c5c4-11ea-9504-ebfd8821f49f.png)
![image](https://user-images.githubusercontent.com/23319356/87397264-22b8ff80-c5c5-11ea-930f-cbc28fcbf296.png)

![image](https://user-images.githubusercontent.com/23319356/87397054-c9e96700-c5c4-11ea-8703-3d98c49771c2.png)

#### Additional context
The problem states that the function is ex 32 bit unsigned integer, but in case if the input does not contain exactly 32 bits, the program gives "Server Error" instead of an appropriate "Invalid testcase" message.
In the first screenshot, the testcase has only 1 bit, in second screenshot: 33 bits.

**Comment by artak-kirakosyan** [comment]
A follow up issue on this problem : when the testcase contains inappropriate characters such as letters, or digits greater than 1(the input is binary, so only 0 and 1 should be acceptable), instead of appropriate "invalid testcase" message we get a Runtime error as follows:

![image](https://user-images.githubusercontent.com/23319356/87397644-b68acb80-c5c5-11ea-98a2-c27d4d5ca372.png)
![image](https://user-images.githubusercontent.com/23319356/87397671-c0acca00-c5c5-11ea-8023-54ee997e0b46.png)
![image](https://user-images.githubusercontent.com/23319356/87397747-dde19880-c5c5-11ea-9b08-e5ea31aab677.png)
![image](https://user-images.githubusercontent.com/23319356/87397725-d5895d80-c5c5-11ea-8460-d2d66ab573a0.png)

**Comment by lc-christina** [comment]
Hi @artak-kirakosyan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @artak-kirakosyan ,
Thanks for your time. The team has reviewed your report but decided not to update the problem due to technical limitations.
