### ISSUE TITLE
Notations in examples are confusing for question 1489 - Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree

### ISSUE THREAD

**Issue by yilinglu** [LeetCode-Feedback/LeetCode-Feedback#6400]
#### Your LeetCode username
code_royale

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The labels(notations) on graphs given in examples are confusing and there is no explanation on how to interpret the labels that look like "<5,3>" or "<6,6>", etc.

#### Expected behavior

All notations used in examples and example graphs are clearly explained, guidance should be provided for readers on how to understand the new notations in examples.

#### Screenshots

<img width="453" alt="Screen Shot 2022-02-13 at 7 54 04 PM" src="https://user-images.githubusercontent.com/1519273/153797548-7688e957-e46d-4e93-8c88-23a757889a21.png">

**Comment by LC-Sue** [comment]
Hi @yilinglu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @yilinglu,
Thank you for your time, the image explained that the notation is <i, weight_i>.
