### ISSUE TITLE
Missing Test Case - 541. Reverse String II

### ISSUE THREAD

**Issue by Gokulviper** [LeetCode-Feedback/LeetCode-Feedback#6402]
[](https://github.com/Gokulviper)deangokul57

wrong test case testing

'''
Input: s = "abcdefg", k = 2
Output: "bacdfeg"
'''
d and e are in wrong place in output

**Comment by stormsunshine** [comment]
The output is correct. Letters a and b are reversed, and letters e and f are reversed. All other letters are the same as the original string.

**Comment by LC-Sue** [comment]
Hi @Gokulviper,
Thank you for reaching out to us,I hope stormsunshine's response was able to answer your doubts! Feel free to reach out if you have any other questions!
