### ISSUE TITLE
Missing Test Case - 1971. Find if Path Exists in Graph

### ISSUE THREAD

**Issue by GoAheadShaun** [LeetCode-Feedback/LeetCode-Feedback#6403]
#### Your LeetCode username
GoAheadShaun

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Problem: Find if Path Exists in Graph
The bug occurs when source == destination. The default solution returns the correct expected output in this situation whereas the code I wrote does not. The problem arrises when I press submit. All test cases are passed when I submit my code even though my code returns the wrong output when source == destination as shown in the attached screenshots below. This indicates that the test cases do not check for this situation and I believe it is an important test case to test for.

#### Code you used for Submit/Run operation

```
// Find if Path Exists in Graph
class Solution {
    public boolean validPath(int n, int[][] edges, int source, int destination) {
        
        if (edges == null) return false;
        if (n == 1) return true;
        
        List<Integer>[] list = new LinkedList[n];
        
        for (int i=0; i<n; i++) {
            list[i] = new LinkedList<>();
        }
        
        for (int[] e: edges) {
            list[e[0]].add(e[1]);
            list[e[1]].add(e[0]);
        }
        
        Set<Integer> set = new HashSet<>();
        Queue<Integer> stack = new PriorityQueue<>();
        stack.add(source);
        
        while (!stack.isEmpty()) {
            int curr = stack.poll();
            set.add(curr);
            List<Integer> currList = list[curr];
            for (int i=0; i<currList.size(); i++) {
                int temp = currList.get(i);
                if (!set.contains(temp)) {
                    set.add(temp);
                    stack.add(temp);
                    if (temp == destination) 
                        return true;
                }
            }
        }        
        
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Whenever source == destination, the output should always be true. This is taken into account when running a test case with source == destination; my code shows false whereas the output says true. While this is fine, I still "pass all cases" when I press submit and my code gets accepted. Leetcode should not accept my code since it does not take into account of when source == destination which is why a test case that covers this case should be added. 

#### Screenshots
![image](https://user-images.githubusercontent.com/65139543/153851116-55d2ed0f-db35-413c-b940-111b05c6ffc9.png)
![image](https://user-images.githubusercontent.com/65139543/153851200-a041eaab-7353-4248-82b2-241e5eef2fc9.png)
![image](https://user-images.githubusercontent.com/65139543/153852636-ddea2229-da9e-4e3a-afbd-76de56fca79f.png)

**Comment by LC-Sue** [comment]
Hi @GoAheadShaun 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @GoAheadShaun 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
