### ISSUE TITLE
Wrong information in Solution Image - 221. Maximal Square

### ISSUE THREAD

**Issue by gauravshah786** [LeetCode-Feedback/LeetCode-Feedback#6404]
#### Your LeetCode username
gauravshah_786

#### Category of the bug
- [ ] Solution

#### Description of the bug
Issue is with the row and column pointed out in the image. The 0th indexed row and 0th indexed column in dp should be 0. It can not have the values of the 0th indexed row and column from the input array.

#### Screenshots
![maximal-square-approach-2-dynamic-programming](https://user-images.githubusercontent.com/15170391/153864011-85452579-918b-4e8d-ba49-0cb87cd1accf.png)

#### Additional context

**Comment by LC-Sue** [comment]
Hi @gauravshah786 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
