### ISSUE TITLE
Wrong Test case - 1166. Design File System

### ISSUE THREAD

**Issue by RunlinXiao** [LeetCode-Feedback/LeetCode-Feedback#6407]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/73460722/153893834-321a0b3e-6c96-489e-8b4e-5e60775116d9.png)

<img width="535" alt="Screen Shot 2022-02-14 at 08 25 06" src="https://user-images.githubusercontent.com/73460722/153893579-bfa89024-8415-4108-a30f-cfb41489c02f.png">

**Comment by LC-Sue** [comment]
Hi @RunlinXiao,
Thank you for reaching out to us, please provide the code you used for submission!
