### ISSUE TITLE
Test case result are correct, but submission gives wrong answer.

### ISSUE THREAD

**Issue by Anla3421** [LeetCode-Feedback/LeetCode-Feedback#6408]
**你的 LeetCode 用户名**
Anla3421

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
my local test and leetcode test case result are correct, but submission gives wrong answer.

**你使用的语言**
GO

**你提交或者运行的代码**
```
var (
	layer int
	left  int
	right int
)

func maxDepth(root *TreeNode) int {
	if root == nil {
		return layer
	}
	if root.Left != nil {
		left = maxDepthSub(root.Left, left)
	}
	if root.Right != nil {
		right = maxDepthSub(root.Right, right)
	}
	max := Max(left, right)
    fmt.Println("left", left)
    fmt.Println("root.Left",root.Left)
	fmt.Println("right", right)
    fmt.Println("root.Right",root.Right)
	layer++
	return layer + max
}

func maxDepthSub(root *TreeNode, i int) int {
	if root == nil {
		return i
	}
	if root.Left != nil {
		left = maxDepthSub(root.Left, left)
	}
	if root.Right != nil {
		right = maxDepthSub(root.Right, right)
	}
	i++
	return i
}

func Max(a int, b int) int {
	if a >= b {
		return a
	}
	return b
}
```

**期望行为**

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/71929424/153928170-856794d8-1799-4a0b-851c-1b0de066ff5f.png)

**额外的上下文**

**Comment by LC-Sue** [comment]
Hi @Anla3421 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
