### ISSUE TITLE
Question is unclear - 127. Word Ladder

### ISSUE THREAD

**Issue by joseville1001** [LeetCode-Feedback/LeetCode-Feedback#6409]
#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description of the question does not make it clear that the order of the letters matter. The description of the question only says:

> "Every adjacent pair of words differs by a single letter."

But the description should make it clear that the order the letters matter. For example, in the following test case
```
"leet"
"code"
["lest","leet","lose","code","lode","robe","lost"]
```

according to Leetcode, the expected output should be `6` corresponding to the length of the following word chain

```
"leet" -> "lest" -> "lost" -> "lose" -> "lode" -> "code"
```

however, there was confusion among some users because their algorithms are getting an output of `5` [1] corresponding to to the following word chain

```
"leet" -> "lest" -> "lose" -> "lode" -> "code"
```

As you can see, the only difference between the word chains is
- `"lest" -> "lost" -> "lose"` vs
- `"lest" -> "lose"`.

It's reasonable to argue that "lest" and "lose" satisfy the criteria "Every adjacent pair of words differs by a single letter.". The question should either accept "lest" and "lose" as being adjacent or make it clear in the problem description that the order of the letters matters.

[1] https://leetcode.com/problems/word-ladder/discuss/?currentPage=1&orderBy=most_relevant&query=%22lest%22%20%22lose%22

**Comment by stormsunshine** [comment]
The order of letters does matter. You can only change one letter without changing the orders of the letters.

**Comment by LC-Sue** [comment]
Hi @joseville1001,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Feel free to reach out again if you have any other questions!
