### ISSUE TITLE
1385. 两个数组间的距离值

### ISSUE THREAD

**Issue by CLannadZSY** [LeetCode-Feedback/LeetCode-Feedback#641]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**[原题](https://leetcode-cn.com/problems/find-the-distance-value-between-two-arrays/)**
给你两个整数数组 arr1 ， arr2 和一个整数 d ，请你返回两个数组之间的 距离值 。

「距离值」 定义为符合此描述的元素数目：对于元素 arr1[i] ，不存在任何元素 arr2[j] 满足 |arr1[i]-arr2[j]| <= d 。

**期望行为**
输入：arr1 = [4,5,8], arr2 = [10,9,1,8], d = 2 输出：2 解释： 对于 arr1[0]=4 我们有： |4-10|=6 > d=2 |4-9|=5 > d=2 |4-1|=3 > d=2 |4-8|=4 > d=2

arr1[0]=4 符合我们距离要求

对于 arr1[1]=5 我们有： |5-10|=5 > d=2 |5-9|=4 > d=2 |5-1|=4 > d=2 |5-8|=3 > d=2

arr1[1]=5 所以距离都大于2 符合我们距离要求

对于 arr1[2]=8 我们有： |8-10|=2 <= d=2 |8-9|=1 <= d=2 |8-1|=7 > d=2 |8-8|=0 <= d=2 arr1[2]=8 出现了距离小于等于2 不符合我们距离要求

因此arr1[0]和arr1[1] 两个符合我们要求

~~说真的, 我已经不是第一次提出这类题目说明的问题了, 中文翻译题目能不能走点心呀, 真就逼我们去[原站](https://leetcode.com/)做英文原始题目了??~~

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
已修复。
