### ISSUE TITLE
1286. Iterator for Combination: Important typo in the solution.

### ISSUE THREAD

**Issue by mo-kiani** [LeetCode-Feedback/LeetCode-Feedback#6410]
#### Your LeetCode username

mo-kiani

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

It's not really a bug. It's an important typo in the solution. 
It's under **Approach 4, algorithm L by D. E. Knuth**, in the **Algorithm** subsection, where it says the following: At each step -> generate next combination -> Find the first j such that `nums[j] == n - k + j` and increase `nums[j]` by one `nums[j] += 1`.
I believe it should instead say "... such that `nums[j] != n - k + j` ...". Notice the inequality sign rather than an equality sign. 

As an additional point of improvement, it might be clearer to say "Find the greatest j where j < k such that ..." instead of "Find the first j such that ...".

**Comment by LC-Sue** [comment]
Hi @mo-kiani 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @mo-kiani,
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
