### ISSUE TITLE
Not able to access: second chapter for Dynamic Programming even after sharing it in twitter (https://twitter.com/DivyadarsheeD/status/1493461798871511040)

### ISSUE THREAD

**Issue by Divyadarshee** [LeetCode-Feedback/LeetCode-Feedback#6412]
#### Your LeetCode username
DVDinfinity

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Even after sharing my progress of Dynamic programming card first chapter in twitter i am not able to access the second chapter.
Here is my tweet: https://twitter.com/DivyadarsheeD/status/1493461798871511040

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Divyadarshee,
Thank you for reaching out to us, please reach out to our support team for technical issues! support@leetcode.com
