### ISSUE TITLE
测试用例有误吧？

### ISSUE THREAD

**Issue by NaturalTruths** [LeetCode-Feedback/LeetCode-Feedback#6414]
**你的 LeetCode 用户名**
须臾

**Bug 类型**
- [ ] 题目
- [56] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
测试用例给的结果明显不对

**你使用的语言**
python

**你提交或者运行的代码**
```
class Solution(object):
    def merge(self, intervals):
        """
        :type intervals: List[List[int]]
        :rtype: List[List[int]]
        """
        for i in range(len(intervals)):
            if len(intervals) == 1:
                break
            if (len(intervals) >= 2):
                print(i)
                print(len(intervals))
                if i == (len(intervals)-1):
                    return intervals
                s = (intervals[i][0],intervals[i][1],intervals[i+1][0],intervals[i+1][1])
                if (min(s) == intervals[i][0]) & (max(s) == intervals[i][1]):
                    del intervals[i+1]
                    print(intervals)
                    continue
                if (min(s) == intervals[i+1][0]) & (max(s) == intervals[i+1][1]):
                    del intervals[i]
                    print(intervals)
                    continue
                if (min(s) == intervals[i][0]) & (max(s) == intervals[i+1][1]) & (intervals[i][1]>=intervals[i+1][0]): 
                    intervals[i] = [intervals[i][0],intervals[i+1][1]]
                    del intervals[i+1]
                    print(intervals)
                    continue
                if (min(s) == intervals[i+1][0]) & (max(s) == intervals[i][1]) & (intervals[i+1][1]>=intervals[i][0]): 
                    intervals[i] = [intervals[i+1][0],intervals[i][1]]
                    del intervals[i+1]
                    print(intervals)
                    continue       
                else:
                    print(intervals)
                    continue
        return intervals
```

**期望行为**
测试用例 [[1,4],[0,2],[3,5]] 的输出应该是 [[0,5]]

**屏幕截图**
![image](https://user-images.githubusercontent.com/7665693/154050305-a0b63268-c65b-4128-ad8a-dbaa59057ebd.png)

**额外的上下文**
题目描述
以数组 intervals 表示若干个区间的集合，其中单个区间为 intervals[i] = [starti, endi] 。请你合并所有重叠的区间，并返回 一个不重叠的区间数组，该数组需恰好覆盖输入中的所有区间 。

示例 1：
输入：intervals = [[1,3],[2,6],[8,10],[15,18]]
输出：[[1,6],[8,10],[15,18]]
解释：区间 [1,3] 和 [2,6] 重叠, 将它们合并为 [1,6].

示例 2：
输入：intervals = [[1,4],[4,5]]
输出：[[1,5]]
解释：区间 [1,4] 和 [4,5] 可被视为重叠区间。
 
提示：
1 <= intervals.length <= 104
intervals[i].length == 2
0 <= starti <= endi <= 104

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/merge-intervals
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by NaturalTruths** [comment]
问题是，提交结果中显示的测试用例输入输出有误。输入：[[1,4],[0,2],[3,5]] 输出：[[0,4],[3,5]]   实际输出应该是[[0,5]] 。显然答案机理的代码只循环了一次，并没有多次循环对列表处理。而根据题目描述，正确答案应该是[[0,5]]
