### ISSUE TITLE
Unable to run tests - 627. Swap Salary

### ISSUE THREAD

**Issue by ankitmusk** [LeetCode-Feedback/LeetCode-Feedback#6415]
#### Your LeetCode username

44656570616b

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Getting invalid test case error, see screenshot attached.

#### Code you used for Submit/Run operation

```
Update Salary
Set sex = 
CASE
    WHEN sex = 'f' THEN 'm'  
    ELSE 'f'
END 
```

#### Language used for code

SQL

#### Screenshots

<img width="278" alt="image" src="https://user-images.githubusercontent.com/98462921/154058003-cd5f219e-d41a-4d2b-adf3-48f708fe9426.png">

**Comment by LC-Sue** [comment]
Hi @ankitmusk,
Thank you for reaching out to us, please provide the test case!

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
