### ISSUE TITLE
Missing Test Case - 1465. Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts

### ISSUE THREAD

**Issue by Ziggsy** [LeetCode-Feedback/LeetCode-Feedback#6418]
#### Your LeetCode username
Ziggsy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Getting invalid test case error, 2 screenshots attached

#### Code you used for Submit/Run operation
```
class Solution {
    fun maxArea(h: Int, w: Int, horizontalCuts: IntArray, verticalCuts: IntArray): Int {
        horizontalCuts.sort()
        verticalCuts.sort()
        
        var maxH = 0
        var prevH = 0
        var maxV = 0
        var prevV = 0
        
        horizontalCuts.forEach {
            if (maxH < it - prevH) {
                maxH = it - prevH
            }
            prevH = it
        }
        
        if (maxH < h - prevH) maxH = h - prevH
        
        verticalCuts.forEach {
            if (maxV < it - prevV) {
                maxV = it - prevV
            }
            prevV = it
        }
        
        if (maxV < w - prevV) maxV = w - prevV
        
        return maxH * maxV
    }
}
```

#### Language used for code
Kotlin

#### Screenshots
Accepted Input:
90000
11114
[1,2,4]
[1,3]
![image](https://user-images.githubusercontent.com/30591958/154077282-5cc57183-472e-4f8a-a29b-94720dc79594.png)

Wrong Answer Input:
90000
11115
[1,2,4]
[1,3]
![image](https://user-images.githubusercontent.com/30591958/154077445-98a514e2-9eb6-4170-9b90-4a82d88f5d3f.png)

**Comment by LC-Sue** [comment]
Hi @Ziggsy,
Thank you for reaching out to us, the code you provided fails from a previously added test case.
