### ISSUE TITLE
Multiple bugs in 305. Number of Islands II

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6419]
## Your LeetCode username

andyliangtw

## Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

## Description of the bug

There're **2 BUGS** and **1 WRONG DESCRIPTION** in [305. Number of Islands II](https://leetcode.com/problems/number-of-islands-ii/).

### Bug 1: Implementations of Approach 2 & Approach 3, no matter which language, are **wrong**.

It doesn't handle the situation "there're duplicate positions". For example, the following testcase:

```text
3
3
[[0,0],[0,1],[1,2],[1,2]]
```

will output `[1,1,2,3]`, but the correct answer is `[1,1,2,2]`.

The reason for this bug is, all the implementations of Approach 2 and Approach 3 don't handle the situation mentioned above. When there're duplicate positions, like `[[1,2],[1,2]]`, it will return the wrong answer.

---

### Bug 2: Function header of C++ implementations are all WRONG

In C++ implementations of all Approaches, the function header is

```cpp
vector<int> numIslands2(int m, int n, vector<pair<int, int>>& positions)
```

but it's NOT acceptable by the judge system. The type of parameter `positions` is wrong. The correct type for `positions` is `vector<vector<int>>& positions`.

Thus, it should be:

```cpp
vector<int> numIslands2(int m, int n, vector<vector<int>>& positions)
```

And of course, there's some more code that needs to be changed in corresponding to this header change.

---

### Wrong Description 1: Java in Approach 2 can be accepted

In Description of Approach 2, it writes "P.S. C++ solution was accepted with 1409 ms runtime, but Java solution got an TLE (Time Limit Exceeded)."

However, after fixing the bug mentioned above, Java solution can be accepted. (in my situation, it took 2888 ms)

## Additional context

I think for C++ and Java, the indention of 4 spaces would be more preferred than 2 spaces. 2 spaces are too small for them.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
