### ISSUE TITLE
566. Reshape the Matrix – Unused Variable in Solution

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#642]
#### Your LeetCode username
MetricQuant

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The code in Approach #1 has an unused variable `count`.

#### Code you used for Submit/Run operation

The Java code in the solution:
```
public class Solution {
    public int[][] matrixReshape(int[][] nums, int r, int c) {
        int[][] res = new int[r][c];
        if (nums.length == 0 || r * c != nums.length * nums[0].length)
            return nums;
        int count = 0;
        Queue < Integer > queue = new LinkedList < > ();
        for (int i = 0; i < nums.length; i++) {
            for (int j = 0; j < nums[0].length; j++) {
                queue.add(nums[i][j]);
            }
        }
        for (int i = 0; i < r; i++) {
            for (int j = 0; j < c; j++) {
                res[i][j] = queue.remove();
            }
        }
        return res;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The line `int count = 0;` should be removed.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @metricquant 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
