### ISSUE TITLE
Missing Test Case - 255. Verify Preorder Sequence in Binary Search Tree

### ISSUE THREAD

**Issue by Uexpectingerror** [LeetCode-Feedback/LeetCode-Feedback#6423]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

it misses task cases that could disapprove some soluctions
missing case: [5,1,3,4,2] 
#### Code you used for Submit/Run operation

```
class Solution:
    def verifyPreorder(self, preorder: List[int]) -> bool:
        lo = -inf
        hi = -inf
        
        for i, val in enumerate(preorder):
            if val <= lo:
                return False
            
            if val > hi:
                lo = hi
                hi = val
            else:
                j = i-1
                while j >= 0 and val > preorder[j]:
                    lo = preorder[j]
                    j -= 1
                
        return True
                    
```

#### Expected behavior

This solution is not correct, but it can pass all the leetcode tests but no the missing test case I provide above
which is [5,1,3,4,2]

**Comment by LC-Sue** [comment]
Hi @Uexpectingerror 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Uexpectingerror 
Thank you for your time. We've used your feedback to update the problem. We'd like to reward you for the contribution, could you please provide your LeetCode username?
