### ISSUE TITLE
Need to Determine Expected Time Complexity - 127. Word Ladder

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6424]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [127. Word Ladder](https://leetcode-cn.com/problems/word-ladder), there are two possible solutions. Use n to represent the size of `wordList` and use m to represent the length of each word, then the two solutions have time complexity O(n<sup>2</sup> * m) and O(n * m<sup>2</sup>), respectively.

According to the constraints, the maximum value of n is 5000 and the maximum of m is 10, so the expected time complexity should be O(n * m<sup>2</sup>), while time complexity O(n<sup>2</sup> * m) should be expected to get Time Limit Exceeded. However, a solution with time complexity O(n<sup>2</sup> * m) can still get passed. Please refer to the following code in Java.

I wonder what the expected time complexity is. If the time complexity O(n<sup>2</sup> * m) is expected to get accepted, then the maximum value of n should be decreased to a value like 1000 to make sure the time complexity O(n<sup>2</sup> * m) does not get Time Limit Exceeded for all three major languages (Java, C++, Python3). If the expected time complexity is O(n * m<sup>2</sup>) and it is expected that time complexity O(n<sup>2</sup> * m) should get Time Limit Exceeded, then the maximum value of n should be increased to a value like 10000 or 20000 to make sure the time complexity O(n<sup>2</sup> * m) gets Time Limit Exceeded for all three major languages and only the time complexity O(n * m<sup>2</sup>) can get accepted.

If the constraints are updated, then the test cases should be updated accordingly.

**Finally, no matter whether the constraints are updated or the test cases are updated, please provide the expected time complexity for this problem, O(n<sup>2</sup> * m) or O(n * m<sup>2</sup>).**

#### Code you used for Submit/Run operation
The following code has time complexity O(n<sup>2</sup> * m).
```Java
class Solution {
    public int ladderLength(String beginWord, String endWord, List<String> wordList) {
        int length = beginWord.length();
        if (!wordList.contains(endWord)) {
            return 0;
        }
        Set<String> visitedSet = new HashSet<String>();
        visitedSet.add(beginWord);
        Queue<String> queue = new ArrayDeque<String>();
        queue.offer(beginWord);
        int count = 1;
        while (!queue.isEmpty()) {
            count++;
            int size = queue.size();
            for (int i = 0; i < size; i++) {
                String str = queue.poll();
                for (String word : wordList) {
                    if (!visitedSet.contains(word) && differByOne(str, word)) {
                        if (word.equals(endWord)) {
                            return count;
                        } else {
                            visitedSet.add(word);
                            queue.offer(word);
                        }
                    }
                }
            }
        }
        return 0;
    }

    public boolean differByOne(String str1, String str2) {
        if (str1.equals(str2)) {
            return false;
        }
        if (str1.length() != str2.length()) {
            return false;
        }
        int length = str1.length();
        boolean flag = false;
        for (int i = 0; i < length; i++) {
            char c1 = str1.charAt(i), c2 = str2.charAt(i);
            if (c1 != c2) {
                if (!flag) {
                    flag = true;
                } else {
                    return false;
                }
            }
        }
        return flag;
    }
}
```
The following code has time complexity O(n * m<sup>2</sup>).
```Java
class Solution {
    Map<String, Integer> wordId = new HashMap<String, Integer>();
    List<List<Integer>> edge = new ArrayList<List<Integer>>();
    int nodeNum = 0;

    public int ladderLength(String beginWord, String endWord, List<String> wordList) {
        for (String word : wordList) {
            addEdge(word);
        }
        addEdge(beginWord);
        if (!wordId.containsKey(endWord)) {
            return 0;
        }
        int[] dis = new int[nodeNum];
        Arrays.fill(dis, Integer.MAX_VALUE);
        int beginId = wordId.get(beginWord), endId = wordId.get(endWord);
        dis[beginId] = 0;

        Queue<Integer> que = new LinkedList<Integer>();
        que.offer(beginId);
        while (!que.isEmpty()) {
            int x = que.poll();
            if (x == endId) {
                return dis[endId] / 2 + 1;
            }
            for (int it : edge.get(x)) {
                if (dis[it] == Integer.MAX_VALUE) {
                    dis[it] = dis[x] + 1;
                    que.offer(it);
                }
            }
        }
        return 0;
    }

    public void addEdge(String word) {
        addWord(word);
        int id1 = wordId.get(word);
        char[] array = word.toCharArray();
        int length = array.length;
        for (int i = 0; i < length; ++i) {
            char tmp = array[i];
            array[i] = '*';
            String newWord = new String(array);
            addWord(newWord);
            int id2 = wordId.get(newWord);
            edge.get(id1).add(id2);
            edge.get(id2).add(id1);
            array[i] = tmp;
        }
    }

    public void addWord(String word) {
        if (!wordId.containsKey(word)) {
            wordId.put(word, nodeNum++);
            edge.add(new ArrayList<Integer>());
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior
1. I would like to know the expected time complexity of this problem. Is the expected time complexity O(n<sup>2</sup> * m) or O(n * m<sup>2</sup>)? **Please provide the expected time complexity in the issue no matter whether the changes to constraints and test cases are applied or not.**
2. If the time complexity O(n<sup>2</sup> * m) is expected to get accepted, then the maximum value of n should be decreased to a value like 1000 to make sure the time complexity O(n<sup>2</sup> * m) does not get Time Limit Exceeded for all three major languages (Java, C++, Python3).
3. If the expected time complexity is O(n * m<sup>2</sup>) and it is expected that time complexity O(n<sup>2</sup> * m) should get Time Limit Exceeded, then the maximum value of n should be increased to a value like 10000 or 20000 to make sure the time complexity O(n<sup>2</sup> * m) gets Time Limit Exceeded for all three major languages and only the time complexity O(n * m<sup>2</sup>) can get accepted.
4. If the constraints are updated, then the test cases should be updated accordingly.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine,
Thank you for your time, our team has reviewed your report and we believe that both solutions are fine. The team did not provide the time complexity.
