### ISSUE TITLE
684. Redundant Connection example bug

### ISSUE THREAD

**Issue by wilmerkrisp** [LeetCode-Feedback/LeetCode-Feedback#6425]
TypeError: 'range' object does not support item assignment

class DSU:
    def __init__(self):
        self.par = range(1001)
    def find(self, x):
        if self.par[x] != x:
            self.par[x] = self.find(self.par[x])
        return self.par[x]
    def union(self, x, y):
        self.par[self.find(x)] = self.find(y)

change to

    def __init__(self):

        self.parent = list(range(1000))

    def find(self, val):
        if (par := self.parent[val]) != val:
            self.parent[val] = self.find(par)
        return par

    def union(self, a, b):
        self.parent[self.find(a)] = self.find(b)

**Comment by LC-Sue** [comment]
Hi @wilmerkrisp 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
