### ISSUE TITLE
Missing Test Case - 1622. Fancy Sequence

### ISSUE THREAD

**Issue by Tukajo** [LeetCode-Feedback/LeetCode-Feedback#6426]
#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Sequence expected output is incorrect at large value.
It appears to be a test case that is not language agnostic.
https://leetcode.com/problems/fancy-sequence/

#### Code you used for Submit/Run operation

// See URL For full driver.
https://github.com/Tukajo/TypeScriptLeetCode/tree/master/src/FancySequence

// Snippit that is relevant to the LeetCode editor.

```
class Fancy {
    sequence: number[] = [];
    instructionResults: (number | null)[] = [];
    constructor(startingSequence?: number[]) {
        this.sequence = startingSequence || [];
        this.recordInstructionResult(null);
    }

    append(val: number): void {
        this.recordInstructionResult(null);
        this.sequence = [...this.sequence, val];
    }

    addAll(inc: number): void {
        this.recordInstructionResult(null);
        this.sequence = this.sequence.map((val) => val + inc);
    }

    multAll(m: number): void {
        this.recordInstructionResult(null);
        this.sequence = this.sequence.map((val) => val * m);
    }

    getIndex(idx: number): number {
        const instructionOutput = idx >= this.sequence.length ? -1 : this.sequence[idx] % (10 ** 9 + 7);
        this.recordInstructionResult(instructionOutput);
        return instructionOutput;
    }

    recordInstructionResult(result: number | null): void {
        this.instructionResults = [...this.instructionResults, result];
    }
}
```

#### Expected behavior

The final instruction of "getIndex(0)" returns this value:
825175576508400500 % ((10**9)+7), which equals 732171522 according to most JS interpretors.
WolframAlpha states  that the value should be 732171510
LeetCode says that the value should be 732171430

Three different answers to the same calculation. I have correctly come up with what most JS/TS results seem to match. However, this output should actually only match an output from somewhere like WolframAlpha.

#### Screenshots

![image](https://user-images.githubusercontent.com/5658487/154345581-8f926ef0-f7f0-4b5c-a343-70f7916be0cf.png)

#### Additional context

I have created a repository that has a simple example unit test showing the issue. This appears to be a bad test case that is not language agnostic if I'd had to guess.

Here is my implementation with driver and unit tests:
https://github.com/Tukajo/TypeScriptLeetCode/tree/master/src/FancySequence

**Comment by LC-Sue** [comment]
Hi @Tukajo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Tukajo,
Thank you for your time, our team has reviewed the problem and the test case appears to be correct. Please feel free to refer to the discuss section to see how other users' have optimized their codes!
