### ISSUE TITLE
Missing Test Case - 380. Insert Delete GetRandom O(1)

### ISSUE THREAD

**Issue by W-Will** [LeetCode-Feedback/LeetCode-Feedback#6427]
#### Your LeetCode username

WilliamWei97

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

When I submitted my code, it says the output was not correct. I then copied paste the test case into the console and it runs the result correctly. 

#### Code you used for Submit/Run operation

'''
class RandomizedSet {
private:
    vector<int> nums;
    unordered_map<int, int> indexOfVal;
    
public:
    RandomizedSet() {
        
    }
    
    bool insert(int val) {
        // if val is already inserted in
        if (indexOfVal.count(val)) {
            return false;
        }
        indexOfVal[val] = nums.size();
        nums.push_back(val);
        return true;
    }
    
    bool remove(int val) {
        // if it is not inserted yet
        if (!indexOfVal.count(val)) {
            return false;
        }
        // get the index of val and set to the last element
        int index = indexOfVal[val];
        indexOfVal[nums.back()] = index;
        swap(nums.back(), nums[index]);
        indexOfVal.erase(val);
        return true;
    }
    
    int getRandom() {
        return nums[rand() % nums.size()];
    }
};
'''

#### Language used for code

C++

#### Expected behavior

The test case runs fine without reporting my results is wrong

**Comment by LC-Sue** [comment]
Hi @W-Will 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
