### ISSUE TITLE
Same test case gives different result in console and while judging 

### ISSUE THREAD

**Issue by kiquance21** [LeetCode-Feedback/LeetCode-Feedback#643]
#### Category of the bug
- [x] Question
- [x] Solution

#### Code you used for Submit/Run operation

```
// 1233. Remove Sub-Folders from the Filesystem
bool comp(const string & s1, const string &s2)
{
    return s1.length() < s2.length();
}
vector<string> ans;
struct trie
{
    unordered_map<char,trie *> mp;
    bool isend;
    char val;
    trie(char v)
    {
        val = v;
        isend = false;
    }
};

void add_word(trie * root, string & word, int pos)
{
    if(word[pos] == '/' && root->isend == true) return;
    if(pos == word.length()) {root->isend = true; ans.push_back(word); return;}
    if(root->mp.find(word[pos]) == root->mp.end())
    {
        trie* node = new trie(word[pos]);
        root->mp[word[pos]] = node;
    }
    add_word(root->mp[word[pos]],word,pos+1);
}



class Solution {
public:
    vector<string> removeSubfolders(vector<string>& folder) {
        sort(folder.begin(),folder.end(),comp);
        
        trie* root = new trie('$'); 
        trie* t = root;
        for(int i = 0;i<folder.size();i++)
        {
            add_word(root,folder[i],0);
        }
     
        return ans;
    }
};
```

#### Test Case :
"["/a","/a/b/c","/a/b/d"]" gives correct answer when running in console i.e "["/a"]"
, but gives output as ["/a","/c/d","/c/f","/a"] while judging

#### Have attached [screenshots]

![console](https://user-images.githubusercontent.com/22012488/87430665-29fefe00-c603-11ea-8acb-39ef1c25cda9.JPG)
![judge](https://user-images.githubusercontent.com/22012488/87430674-2e2b1b80-c603-11ea-9d38-c3d2b543de7d.JPG)

**Comment by lc-christina** [comment]
Hi @kiquance21 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
