### ISSUE TITLE
 Merge Sorted Array leetcode   question

### ISSUE THREAD

**Issue by Akash99-eng** [LeetCode-Feedback/LeetCode-Feedback#6431]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the issue you want to create?

**Comment by LC-Sue** [comment]
Hi @Akash99-eng 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
