### ISSUE TITLE
Test case results not matching submission given same input - 12. Integer to Roman

### ISSUE THREAD

**Issue by Fionan** [LeetCode-Feedback/LeetCode-Feedback#6433]
#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test  case input of '58' provides a different result than Submission results of input '58'

#### Code you used for Submit/Run operation

```
// Integer-to-roman
class Solution {
    
 static StringBuilder romanNumerals= new StringBuilder("");
    
    
    int[] num_values = {1000,900,500,400,100,90,50,40,10,9,5,4,1};
    String[] roman_chars={"M","CM","D","CD","C","XC","L","XL","X","IX","V","IV","I"};
   
    public String intToRoman(int num) {
        
            for(int i=0;i<num_values.length;i++){
                int count = num / num_values[i];
                num%=num_values[i];
                
                if(count>0){
                    appendByCount(roman_chars[i],count);
                }
                
            }

        return romanNumerals.toString();

    }

    void appendByCount(String numeral,int count){
        for(int i=0; i< count;i++){
            romanNumerals.append(numeral);
            }
       if(count>0){ System.out.println(romanNumerals.toString());}
    }
    
    
}
```

#### Expected behavior

As a user I expect that the result of a Test case matches the result of Submssion given the same inputs.
Using the Test case value '58' the result and expected result is "LVIII".
The submission fails on the same input '58' with expected result "LVIII" and actual result of "IIILVIII"

#### Screenshots

![leetcode_bug](https://user-images.githubusercontent.com/5883871/154576441-cd9846d9-0f53-4c32-b74c-4b290346f7bd.png)

**Comment by stormsunshine** [comment]
Don't use static variables.

**Comment by Fionan** [comment]
> Don't use static variables.

Moving the static `StringBuilder` into the `intToRoman` method, and passing it as a vairable to `appendByCount` method meant this issue did not occur.

But as far as i can tell that is avoiding the Issue . Can you explain why a static variable would cause the issue as outlined above?
Why the Test case would produce a different result than the submssion given the same input.

**Comment by LC-Sue** [comment]
Hi @Fionan 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
