### ISSUE TITLE
1627 test case 58 incorrect

### ISSUE THREAD

**Issue by mkmark** [LeetCode-Feedback/LeetCode-Feedback#6435]
#### Your LeetCode username

mkmark

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect Test Case

#### Description of the bug

[1627. Graph Connectivity With Threshold](https://leetcode.com/problems/graph-connectivity-with-threshold/) test case 58 incorrect
[8,9] should return false instead of true

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    vector<bool> areConnected(int n, int threshold, vector<vector<int>>& queries) {
        int q_size = queries.size();
        vector<bool> res(q_size);

        for (int i=0; i<q_size; ++i){
            res[i] = gcd(queries[i][0], queries[i][1]) > threshold;
        }

        return res;
    }

    int gcd(int a, int b){
        if (b==0){
            return a;
        }
        return gcd(b, a%b);
    }
};
```

#### Language used for code

C++

#### Expected behavior

[8,9] should return false instead of true

#### Screenshots

![image](https://user-images.githubusercontent.com/38940419/154602521-ddeb9674-5ea4-4391-bf48-529ed6ea4ab5.png)

#### Additional context

All the accepted solutions that passed this test case are wrong

**Comment by mkmark** [comment]
I failed to understand the question. Sorry for your time.

**Comment by devgg** [comment]
Hi, I am having the same issue. Could you explain how this test case is correct? Seems wrong to me.
