### ISSUE TITLE
Missing Test Case - 1092. Shortest Common Supersequence

### ISSUE THREAD

**Issue by sidhunishan786** [LeetCode-Feedback/LeetCode-Feedback#6436]
#### Screenshots
<--![Screenshot (6)](https://user-images.githubusercontent.com/75064499/154631723-01c69f50-0639-430c-a161-5f5adc185bbc.png) -->

**Comment by LC-Sue** [comment]
Hi @sidhunishan786,
Thank you for reaching out to us, there doesn't seem to be a problem. The problem accepts multiple outputs!
