### ISSUE TITLE
Missing Test Case - 2172. Maximum AND Sum of Array

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#6438]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[12, 13, 14, 1, 7, 14, 15, 9, 15, 6, 10, 8, 5, 15, 13, 1, 9, 9]
9

#### Code you used for Submit/Run operation

```
class Solution:
    def maximumANDSum(self, nums: List[int], numSlots: int) -> int:
        ans = 0
        for i in range(10000): # guess enough times
            random.shuffle(nums) # try different orders randomly
            cur = 0
            counter = defaultdict(int)
            for n in nums:
                j = 0
                for i in range(1, numSlots+1):
                    if counter[i] < 2 and n & i > n & j: # Greedy
                        j = i
                counter[j] += 1
                cur += n & j
            ans = max(ans, cur)
    
        return ans    
```

#### Language used for code

Python3

#### Expected behavior

Output: 87
Expected: 88

**Comment by LC-Sue** [comment]
Hi @hqztrue,
Thank you for reaching out to us, the code you provided already fails from a previously submitted test case!
