### ISSUE TITLE
Missing Test Case - 1654. Minimum Jumps to Reach Home

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#6439]
#### Your LeetCode username
Rad0miR

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

My code got Accepted.
But it is getting Wrong Answer on this test case:
```
[10]
10
5
5
```

#### Code you used for Submit/Run operation

```
public class Solution {
    public int MinimumJumps(int[] forbidden, int a, int b, int x) 
    {
        HashSet<int> used = forbidden.ToHashSet();
        Dictionary<int, int> res = new();
        Queue<(int, int)> queue = new(new[] { (0, 0) });
        for (int i = 0; i < 10_000_000 && queue.Any(); ++i) 
        {
            (int pos, int length) = queue.Dequeue();
            
            if (pos == x) return length;
            if (pos - b == x) return length + 1;
            
            if (a >= b && pos > x + b) continue;
            if (pos < 0 || used.Contains(pos)) continue;
            
            used.Add(pos);
            
            queue.Enqueue((pos + a, length + 1));
            if (!used.Contains(pos - b)) queue.Enqueue((pos - b + a, length + 2));
        }
        return -1;
    }
}
```

#### Language used for code
C#

#### Expected behavior

My code is passing all tests and getting Accepted. But it should get Wrong Answer.

**Comment by LC-Sue** [comment]
Hi @Rad0miR 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Rad0miR 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
