### ISSUE TITLE
力扣刷新题没有刷新题奖励

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#644]
**描述**
我刷了三道新题，没有收到20点数奖励

**你使用的语言**
C++

**屏幕截图**
![Snipaste_2020-07-14_12-30-55](https://user-images.githubusercontent.com/32877011/87463249-5a787500-c5ce-11ea-8162-50a7c41589be.png)
![Snipaste_2020-07-14_12-32-26](https://user-images.githubusercontent.com/32877011/87463269-5e0bfc00-c5ce-11ea-88d4-12902baf1bd3.png)
都是第一次刷，是因为刷的是面试题和剑指offer，所以没有奖励吗？

**Comment by feiceh** [comment]
感谢反馈，此问题已转给相关团队会尽快确认的，给您带来的不便敬请谅解。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先暂时关闭，后续使用中有任何问题欢迎点击「https://support.leetcode-cn.com/hc/kb/section/1115013」 提交工单反馈，最好带上个性域名以便技术排查，请知晓～
