### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by SaleelAhsanM** [LeetCode-Feedback/LeetCode-Feedback#6440]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution is not correct with my test cases

#### Code you used for Submit/Run operation

 ```
def minSubArrayLen(target, num):
    l, total = 0, 0
    result = float("inf")

    for r in range(len(num)):
        total += num[r]
        while total >= target:
            result = min(r - l + 1, result)
            total -= num[l]
            l += 1

    return 0 if result == float("inf") else result


print(minSubArrayLen(7, [2, 3, 1, 2, 4, 3]))    # 2
print(minSubArrayLen(7, [2, 4, 1, 2, 3, 3]))    # 3 Expected output: 2
print(minSubArrayLen(6, [1, 4, 7, 2, 8, 3]))    # 1 Expected output: 2
```
Test cases
```
minSubArrayLen(7, [2, 4, 1, 2, 3, 3])    # 3
minSubArrayLen(6, [1, 4, 7, 2, 8, 3])    # 1
```

#### Language used for code

Python 3

#### Expected behavior

The results should be 2 for the below test cases 
minSubArrayLen(7, [2, 4, 1, 2, 3, 3])
minSubArrayLen(6, [1, 4, 7, 2, 8, 3])

**Comment by LC-Sue** [comment]
Hi @SaleelAhsanM,
Thank you for reaching out to us, the code you provide already fails from a previously added test case!
