### ISSUE TITLE
Missing Test Case - 402. Remove K Digits

### ISSUE THREAD

**Issue by Omkar-C** [LeetCode-Feedback/LeetCode-Feedback#6441]
#### Your LeetCode username
 Omkar_C

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Order (n*k) solution passes

#### Code you used for Submit/Run operation
```
class Solution {
public:
    string removeKdigits(string num, int k) {
        int n = num.size();
        string ans = num;
        for(int i = 0; i < k; i++) {
            if(ans.size() == 1){
                ans = "";
                break;
            }
            bool deleted = false;
            for(int j = 0; j < ans.size(); j++) {
                if(j+1 < ans.size() && ans[j] > ans[j+1]) {
                    ans = ans.substr(0, j) + ans.substr(j+1);
                    deleted = true;
                    break;
                }
            }
            if(!deleted) {
                ans = ans.substr(0, ans.size() - 1);
            }
            
        }
        if(ans.empty()) return "0";
        int idx = 0;
        while(idx < ans.size() && ans[idx] == '0') {
            idx++;
        }
        ans = ans.substr(idx);
        if(ans.empty()) return "0";
        return ans;
    }
};
```

#### Expected behavior
Should not pass for O(n*k) solution.

**Comment by LC-Sue** [comment]
Hi @Omkar-C,
Thank you for reaching out to us, please provide the test case that fails the code!

**Comment by Omkar-C** [comment]
"999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999...
50000

**Comment by LC-Sue** [comment]
Hi @Omkar-C,
Thank you for your time, the code you provided already TLEs! We appreciate the support!
