### ISSUE TITLE
Missing Test Case - 402. Remove K Digits

### ISSUE THREAD

**Issue by nimrat02** [LeetCode-Feedback/LeetCode-Feedback#6443]
#### Your LeetCode username

matharoonimrat

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

#### Description of the bug

There is a missing test case in Problem of the day named : 402. Remove K Digits

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    string removeKdigits(string num, int k) {
        
        int n = num.size();
        int non_deleted = 0;
        vector<int> asc;
        stack<int> s;
        
        //monotonic stack
        //after every push, stack is in increasing order
        for(int i=0;i<n and k>0;i++){
            while(!s.empty() and k>0 and num[s.top()]>num[i]){
                num[s.top()] = 'x';
                s.pop();
                k--;
            }
            s.push(i);
        }
        
        //string is in ascending order here
        for(int i=n-1;i>-1 and k>0;i--){ //removing from right
            k--;
            num[i] = 'x';
        }
        
        //creating answer string
        string ans;
        for(int i=0;i<n;i++){
            if(num[i]=='0' and ans.size()==0)
                continue;
            if(num[i]!='x')
                ans+=num[i];
        }
        if(ans.size()==0)
            ans = '0';
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code is accepted but a test case is missing that is :
"12354"
3

#### Screenshots

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/55542702/154740483-8b9431c4-62d3-4de0-822a-637251aa5bd4.png">

**Comment by LC-Sue** [comment]
Hi @nimrat02 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @nimrat02 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
