### ISSUE TITLE
Missing Test Case - 402. Remove K Digits

### ISSUE THREAD

**Issue by navi532** [LeetCode-Feedback/LeetCode-Feedback#6444]
#### Your LeetCode username

navi532

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

The following Test Case is missing:
1 2 3 5 4

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string removeKdigits(string num, int k) {
        
        
        int n = num.size();
        stack<int> s;
 
        for(int i=0;i<n and k>0;i++){
            while(!s.empty() and k>0 and num[s.top()]>num[i]){
                num[s.top()] = 'x';
                s.pop();
                k--;
            }
            s.push(i);
        }
 

        for(int i=n-1;i>-1 and k>0;i--){ 
            k--;
            num[i] = 'x';
        }
 
        string ans;
        for(int i=0;i<n;i++){
            if(num[i]=='0' and ans.size()==0)
                continue;
            if(num[i]!='x')
                ans+=num[i];
        }
        if(ans.size()==0)
            ans = '0';
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should have resulted in Status Wrong Answer but Status Accepted.
Submitted a wrong solution and it passed all test cases.
But it can be clearly seen, the above code would give the wrong output still it passes.

#### Screenshots

![Screenshot 2022-02-18 235224](https://user-images.githubusercontent.com/55792692/154741006-0b935005-2014-4008-9d8d-92bb75fbd6a7.jpg)
![Screenshot 2022-02-18 235140](https://user-images.githubusercontent.com/55792692/154741046-02e95619-dc13-41b7-aeb7-75a0f784277c.jpg)

**Comment by LC-Sue** [comment]
Hi @navi532 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @navi532 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
