### ISSUE TITLE
Missing Test Case - 402. Remove K Digits - TLE Case

### ISSUE THREAD

**Issue by GauravS1910** [LeetCode-Feedback/LeetCode-Feedback#6446]
#### Your LeetCode username

gaurav1910

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

The following test case gives TLE on many yet Accepted Solutions: 
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8099964/testcase.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string removeKdigits(string s, int k) {
        int n = s.size(); 
        string t;
        int st = 0;  
        int last = k;  
        while(t.size()!=n-k)
        {
            int mi = 10; 
            int j = -1; 
            //cout<<t<<" "<<st<<" "<<last<<endl; 
            for(int i=st;i<=last;i++)
            {
                if(int(s[i]-'0') < mi)
                {
                    mi = int(s[i]-'0'); 
                    j = i; 
                }
            }
            t.push_back(s[j]); 
            st = j+1; 
            last++; 
        }
        int i = 0; 
        while(t[i]=='0')
            i++;
        string ans = t.substr(i); 
        if(ans.size()==0)
            return "0"; 
        return ans;  
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected the code to result in TLE, however due to the missing test case it got Accepted!!

#### Screenshots

![image](https://user-images.githubusercontent.com/54735101/154751112-2dad6959-09cf-4eb6-9943-7e543fe2eaca.png)
![image](https://user-images.githubusercontent.com/54735101/154751256-a384072b-9388-4ef0-a478-70c362a5f45c.png)

**Comment by LC-Sue** [comment]
Hi @GauravS1910 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @GauravS1910 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
