### ISSUE TITLE
Missing Test Case - 2163. Minimum Difference in Sums After Removal of Elements

### ISSUE THREAD

**Issue by NihalAgarwal** [LeetCode-Feedback/LeetCode-Feedback#6448]
#### Your LeetCode username

agarwalaarrav

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

**Test case :**  [1,1,1,100,200,600,400,1,1]
There is a missing test case for this problem, due to which my wrong code or solution passes all Leetcode test cases and submitted successfully.

#### Code you used for Submit/Run operation

```
class Solution {
    public long minimumDifference(int[] nums) {
        int n = nums.length/3;
        long res = Long.MAX_VALUE;

        long sum = 0;
        PriorityQueue<Integer> qFirst = new PriorityQueue<>( (a,b) -> b-a);
        long[] first_ar = new long[3*n];

        for(int i = 0; i < 2*n; i++){
            qFirst.add(nums[i]);
            sum += (long) nums[i];
            if( qFirst.size() >= n){
                first_ar[i] = sum;
                sum -= (long) qFirst.poll();
            }
        }

        sum = 0;
        PriorityQueue<Integer> qSecond = new PriorityQueue<>();
        long[] second_ar = new long[3*n];

        for(int i = 3*n-1; i >= n-1; i--){
            qSecond.add(nums[i]);
            sum += (long) nums[i];
            if( qSecond.size() >= n){
                second_ar[i] = sum;
                sum -= (long) qSecond.poll();
            }
            
            if( i < 2*n){
                res = Math.min(res, first_ar[i]-second_ar[i+1]);
            }
        }

        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

**Test case :**  [1,1,1,100,200,600,400,1,1]
**Output:** -1098
**Expected:** -1197
My code should be failed, but it passes all test cases successfully due to the above missing test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/46000505/154771367-ee5c8b3a-67dd-4953-a24f-2f07dcf3a103.png)
![image](https://user-images.githubusercontent.com/46000505/154771415-22bad783-10f7-4574-92bd-7f9fb441158a.png)

**Comment by LC-Sue** [comment]
Hi @NihalAgarwal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @NihalAgarwal 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
