### ISSUE TITLE
Missing Test Case - 663. Equal Tree Partition

### ISSUE THREAD

**Issue by tonyxxliu** [LeetCode-Feedback/LeetCode-Feedback#6449]
#### Your LeetCode username
TLLLL

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code passes the existing test cases and beats 87%. But my code does not work in this test case which I created myself.
[2,-2,0]

#### Code you used for Submit/Run operation

```
class Solution:
    def checkEqualTree(self, root: Optional[TreeNode]) -> bool:
        hasSeen=set()
        if not root: return False
        if not root.left and not root.right: return False
        
        def dfs(node):
            if not node: return 0
            l=dfs(node.left)
            r=dfs(node.right)
            s=l+r+node.val
            hasSeen.add(s)
            return s
        
        s=dfs(root)
        if s!=0 and s%2==0 and s//2 in hasSeen:
            return True
        
        elif s==0 and dfs(root.left)==dfs(root.right):
            return True
        
        else:
            return False
```

#### Language used for code
Python 3

#### Expected behavior

Please add my test case to the test cases group.
[2,-2,0]

#### Screenshots

![image](https://user-images.githubusercontent.com/72303917/154785594-66fc9cf8-def7-4665-a163-678c473aae51.png)

**Comment by LC-Sue** [comment]
Hi @tonyxxliu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @tonyxxliu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
