### ISSUE TITLE
Missing Solution - 1662. Check If Two String Arrays are Equivalent

### ISSUE THREAD

**Issue by shivam123-dev** [LeetCode-Feedback/LeetCode-Feedback#6450]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Solution is missing from the Question

#### Code I used for Submit/Run operation

```
// Check If Two String Arrays are Equivalent
class Solution {
public:
    bool arrayStringsAreEqual(vector<string>& word1, vector<string>& word2) {
        string s1 = "", s2 = "";
        for(auto x:word1)
            s1+=x;
        for(auto x:word2)
            s2+=x;
        return s1==s2;
    }
};
```

#### Success Solution Screenshot
![Success](https://user-images.githubusercontent.com/81038095/154788701-abef5431-d7c6-430f-a0d9-7b64719098aa.png)

**Comment by LC-Sue** [comment]
Hi @shivam123-dev,
Thank you for reaching out to us, feel free to share your solution in the discuss section of the problem!
