### ISSUE TITLE
 55. Jump Game LEETCODE JAVA

### ISSUE THREAD

**Issue by ShubhamKatiyar1** [LeetCode-Feedback/LeetCode-Feedback#6453]
class Solution {
    public boolean canJump(int[] nums) {
        
        int vs=nums.length-1;
        for(int i=nums.length-1;i>=0;i--)
        {
         
                if(i+nums[i]>=vs)
                {
                    
                vs=i;
                }
          
            
        }
        
       return vs==0; 
    }
}

**Comment by LC-Sue** [comment]
Hi @ShubhamKatiyar1 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
