### ISSUE TITLE
Example 2 in wrong in description

### ISSUE THREAD

**Issue by anipaul2** [LeetCode-Feedback/LeetCode-Feedback#6455]
Leetcode problem 1675 -> Maximum Deviation in an Array.
The problem is in the example or maybe a typo.

![Screenshot (424)](https://user-images.githubusercontent.com/74004409/154810716-f6bc8f20-6805-4cfb-91f1-094e2e76d8a4.png)

> Here 20 should be replaced by 10 to make sense.

Username - Anipaul1

**Comment by gyani-codes** [comment]
@anipaul2 You can divide any even element any number of times,
