### ISSUE TITLE
Bug caused by changed parameter type - 632. Smallest Range Covering Elements from K Lists

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6457]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[632. Smallest Range Covering Elements from K Lists](https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/)

All the Java implementations have this problem. The actual type of parameter `nums` is `List<List<Integer>>`, but the implementations use `int[][]`. This caused errors.

#### Language used for code

Java

#### Expected behavior

Change the type of parameter `nums` and the corresponding code.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @andyliangtw,
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
