### ISSUE TITLE
269. Alien Dictionary - Validation seems to be wrong

### ISSUE THREAD

**Issue by elulcao** [LeetCode-Feedback/LeetCode-Feedback#646]
#### Your LeetCode username
elulcao

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Here is the problem description, where algorithm would be able to return a string with lexicographic order for alien characters, however some custom test cases are marked as correct but the order of expected result is not the correct one.

> There is a new alien language which uses the latin alphabet. However, the order among letters are unknown to you. You receive a list of non-empty words from the dictionary, where words are sorted lexicographically by the rules of this new language. Derive the order of letters in this language.
#### Code you used for Submit/Run operation
The code used is the same as the one offered in Solution section:

```java
// Alien Dictionary
class Solution {
    public String alienOrder(String[] words) {
        Map<Character, List<Character>> adjList = new HashMap<>();
        Map<Character, Integer> counter         = new HashMap<>();
        
        for (String str : words) { // Step 1
            for (Character ch : str.toCharArray()) {
                counter.put(ch, 0);
                adjList.put(ch, new ArrayList<Character>());
            }
        }
        
        for (int i = 0; i < words.length - 1; i++) { // Step 2
            String word1 = words[i];
            String word2 = words[i + 1];
            
            if (word1.length() > word2.length() &&
                word1.startsWith(word2)) {
                return "";
            }
            
            for (int j = 0; j < Math.min(word1.length(), 
                                         word2.length()); j++) {
                if (word1.charAt(j) != word2.charAt(j)) {
                    adjList.get(word1.charAt(j)).add(word2.charAt(j));
                    counter.put(word2.charAt(j), 
                                counter.get(word2.charAt(j)) + 1);
                    break;
                }
            }
        }
        
        StringBuilder sb = new StringBuilder();
        Queue<Character> queue = new LinkedList<>();
        for (Character ch : counter.keySet()) {
            if (counter.get(ch).equals(0)) {
                queue.add(ch);
            }
        }
        
        while (!queue.isEmpty()) {
            Character ch = queue.remove();
            sb.append(ch);
            for (Character next : adjList.get(ch)) {
                counter.put(next, counter.get(next) - 1);
                if(counter.get(next).equals(0)) {
                    queue.add(next);
                }
            }
        }
        
        if (sb.length() < counter.size()) {
            return "";
        }
        
        return sb.toString();
    }
}
```
#### Language used for code
Java

#### Expected behavior
As my understanding the correct Output should be `"xyzabc"` but since `xyz` characters are at index `0` and `abc` are in index `1`.
> Input: ["xa","yb","zc"]
Output: "xyzabc"
Expected: "xyzabc"

#### Screenshots
![Captura de Pantalla 2020-07-15 a la(s) 12 06 53 p m](https://user-images.githubusercontent.com/6373960/87575262-46e41180-c695-11ea-9b45-6fe7d4b53ac3.png)
![Captura de Pantalla 2020-07-15 a la(s) 12 04 32 p m](https://user-images.githubusercontent.com/6373960/87575280-4fd4e300-c695-11ea-94ac-edf51fcd261c.png)

#### Additional context
In this problem is not clear if the expected answer or solution offered is wrong.

**Comment by lc-christina** [comment]
Hi @elulcao 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @elulcao 
Thanks for your time. The problem states 'There may be multiple valid order of letters, return any one of them is fine.' so the report is invalid.
