### ISSUE TITLE
Missing Test Case -  1559. Detect Cycles in 2D Grid

### ISSUE THREAD

**Issue by MAvtushenko** [LeetCode-Feedback/LeetCode-Feedback#6460]
#### Your LeetCode username
MAvtushenko

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The provide code is "Accepted" after submit.
But in Run Code mode you can see that provided solution is incorrect with the next input:

Input: grid=[["a","a","a","a"],["c","b","b","a"],["a","b","b","a"],["a","a","a","a"]]
Output: false
Expected Output: true

#### Code you used for Submit/Run operation

```
class Solution {
    boolean[][] visited;
    private boolean dfs(char[][] grid, char target, int previ, int prevj, int i, int j) {
        if (i < 0 || j < 0)
            return false;
        if (i >= grid.length || j >= grid[0].length)
            return false;
        visited[i][j] = true;
        if (grid[i][j] > 'z') return true;
        if (grid[i][j] != target) return false;
        char original = grid[i][j];
        grid[i][j] += 26;
        boolean result = false;
        if (previ != i-1 || prevj != j)
            result |= dfs(grid, original, i, j, i-1, j);
        if (previ != i+1 || prevj != j)
            result |= dfs(grid, original, i, j, i+1, j);
        if (previ != i || prevj != j-1)
            result |= dfs(grid, original, i, j, i, j-1);
        if (previ != i || prevj != j+1)
            result |= dfs(grid, original, i, j, i, j+1);
        grid[i][j] -= 26;
        return result;
    }
    
    public boolean containsCycle(char[][] grid) {
        int m = grid.length;
        int n = grid[0].length;
        visited = new boolean[m][n];
        for (int i = 0; i < m; i++) {
            for (int j = 0; j < n; j++) {
                if (!visited[i][j]) {
                    if (dfs(grid, grid[i][j], -2, -2, i, j)) {
                        return true;
                    }
                }
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Provided code must result in "Wrong answer" on submitting.
Currently this code accepted as "Success".

#### Screenshots

![image](https://user-images.githubusercontent.com/22905700/154817813-2026c661-799e-44ef-803e-4f4f317ce014.png)

#### Additional context

Please include testcase with input 
[["a","a","a","a"],["c","b","b","a"],["a","b","b","a"],["a","a","a","a"]]
into the pool of testcases on submit.
Link to the incorrectly accepted submission: https://leetcode.com/submissions/detail/644765483/

**Comment by LC-Sue** [comment]
Hi @MAvtushenko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @MAvtushenko 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
