### ISSUE TITLE
Incorrect Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by E-Leask** [LeetCode-Feedback/LeetCode-Feedback#6461]
#### Your LeetCode username

E-Leask

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

3. Longest Substring Without Repeating Characters
Bug in test case unless I've interpreted this incorrectly(in which case my bad)
```
320 / 987 test cases passed. | Status: Wrong Answer
Input:
"ynyo"
Output:
2
Expected:
3
```
From my interpretation this test case should output 2

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int lengthOfLongestSubstring(string s) {
        string substring;
        set<char> ssSet;
        //string::iterator it ;
        int max=0;
        int si, ci =0;
        char c;
        //edge case length of 0
        //
        //for (it=s.begin();it<s.end(); it++)
        for (auto it : s)
            
        {
            //generate substring
                //get next index
                //check if exists in set
                //validate whether substring is still unique
                if (ssSet.count(it)==0)
                {    
                //add to set
                    ssSet.insert(it);

                //update max
                    if (ssSet.size()>max)
                    {
                        max = ssSet.size();
                    }
                }
                else
                {
                    ssSet.find(it);
                    ssSet.erase(ssSet.begin(),ssSet.find(it));
                    ssSet.insert(it);
                }
        
        }
        return max;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Expected output of testcase should be 2, resulting in a pass

#### Screenshots

![image](https://user-images.githubusercontent.com/25560021/154820112-514444ff-7e94-4776-bdd9-9e7d2f070dcd.png)

**Comment by stormsunshine** [comment]
The substring "nyo" with length 3 does not have repeating characters. Is there any problem?

**Comment by LC-Sue** [comment]
Hi @E-Leask,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Feel free to reach out again if you have any other questions!
