### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by rshke** [LeetCode-Feedback/LeetCode-Feedback#6462]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ -] Missing Test Cases 

#### Description
User @milochen has posted [[his solution ]](https://leetcode.com/problems/gas-station/discuss/1707178/gas-station-or-C++-solution-or-greedy-or-time-O(N)) to 134. Gas Station(shown below). I tried to submit it and it passed tests. 
But I think it is not right.  I create my own test case:
   gas  = [3, 3, 3, 3, 3, 3, 3, 3]
   cost = [5, 1, 4, 4, 4, 2, 2, 2]
As I think, @milochen's algorithm fails. My case satisfies the requirements of this question. The solution is unique -- the car must start from index `5`. 

```
class Solution {
public:
	int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {
		int n = cost.size();
        int sum = 0;
        int max_val=INT_MIN;
        int max_idx=-1;
        for(int i=0; i < n; i++) {
            sum+= (gas[i]-cost[i]);
            int next = (i+1)%n;
            int dist = (gas[next]-cost[next])-(gas[i]-cost[i]);
            if(max_val < dist) {
                max_val = dist;
                max_idx = next;
            }
        }
        return sum<0?-1:max_idx;        
	}
};
```

**Comment by LC-Sue** [comment]
Hi @rshke 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @rshke 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
