### ISSUE TITLE
Problem description - 1288. Remove Covered Intervals

### ISSUE THREAD

**Issue by lxylxy123456** [LeetCode-Feedback/LeetCode-Feedback#6463]
#### Your LeetCode username
lxylxy123456

#### Category of the bug
- [x] Question

#### Description of the bug

The problem description says
* Given an array intervals where `intervals[i] = [li, ri]` represent the interval `[li, ri)`, remove all intervals that are covered by another interval in the list.
* `0 <= li <= ri <= 10^5`

When li = ri, the interval is an empty set, and whether an interval covers another is ambiguous (consider whether `[1, 3)` covers `[4, 4)`; it should because `[4, 4)` is an empty set).

It is better to specify `0 <= li < ri <= 10^5`. Currently looks like the test cases do not contain any `li = ri` (because the following program is accepted).

#### Code you used for Submit/Run operation

```py
class Solution:
    def removeCoveredIntervals(self, intervals: List[List[int]]) -> int:
        ans = 0
        intervals.sort(key=lambda x: (x[0], -x[1]))
        cover_right = 0
        for l, r in intervals:
            assert l < r
            if r <= cover_right:
                continue
            ans += 1
            cover_right = r
        return ans
```

**Comment by Xascoria** [comment]
It's notable that putting `li = ri` in the testing console throws an error, so I believe it might be a wrong constraint on the question

**Comment by LC-Sue** [comment]
Hi @lxylxy123456 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @lxylxy123456 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
