### ISSUE TITLE
Typo in method signature for problem 2183.  Count Array Pairs Divisible by K

### ISSUE THREAD

**Issue by lmitchell06** [LeetCode-Feedback/LeetCode-Feedback#6464]
#### Your LeetCode username
Same as github username

#### Category of the bug
- [X] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
As the title implies, the method signature in all languages is "coutPairs" rather than "countPairs". Might possibly lead to confusion, cout being taken as output in C style languages. Changing this might help overall readability on the site. Thanks!

#### Code you used for Submit/Run operation
N/A

#### Language used for code
All languages have the same issue

#### Screenshots
N/A

#### Additional context
N/A

**Comment by LC-Sue** [comment]
Hi @lmitchell06,
Thank you for reaching out to us, the method signature has already been udpated!
