### ISSUE TITLE
Missing Test Case - 2178. Maximum Split of Positive Even Integers

### ISSUE THREAD

**Issue by iamvinayvk** [LeetCode-Feedback/LeetCode-Feedback#6466]
#### Your LeetCode username
iamvinayvk

#### Category of the bug
- 

- [✅ ] Question

- [ ] Solution
- [✅ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem is asking to split the sum but for test cases 2 and 4, we can't split it as the sum of two or more unique positive even integers.

Either the problem should indicate in example test cases that we can split it into a single positive even integer also or we should return an empty array in test cases 2 and 4.

#### Code you used for Submit/Run operation

```
// Maximum Split of Positive Even Integers
class Solution {
public:
    vector<long long> maximumEvenSplit(long long finalSum) {
        vector<long long> ans;
        if(finalSum%2!=0||finalSum==4)
        {
            if(finalSum==4)
                ans.push_back(4);
            return ans;
        }
        long long even=2;
        while(finalSum>0)
        {
            if(finalSum-even<=even)
            {
                ans.push_back(finalSum);
                finalSum-=finalSum;
            }
            else
            {
                ans.push_back(even);
                finalSum-=even;
                even+=2;
            }
        }
        return ans;
        
    }
};
```

#### Language used for code
C++

#### Expected behavior
As per the problem statement output for the test cases, 2 and 4 should be an empty array or the question should be more clear by giving single unique positive even integers in the example test cases.

**Comment by LC-Sue** [comment]
Hi @iamvinayvk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @iamvinayvk 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
