### ISSUE TITLE
Missing Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by gandharvas** [LeetCode-Feedback/LeetCode-Feedback#6468]
#### Your LeetCode username

gandharvas

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question says
`
Given an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive.

There is only one repeated number in nums, return this repeated number.

You must solve the problem without modifying the array nums and uses only constant extra space.
`
But there is an test case which has more than one repeated no,
`
Input:
[2,2,2,2,2]
Output:
0
Expected:
2
`
#### Code you used for Submit/Run operation

```
func findDuplicate(nums []int) int {
    expectedSum := 0
    actualSum :=0
    j:=1
    for i:=0; i<len(nums)-1; i++{
        expectedSum += j
        actualSum += nums[i]
        j++
    }
    
    actualSum += nums[len(nums)-1]
    
    return actualSum-expectedSum
}
```

#### Language used for code

golang

#### Expected behavior

there  should be one repeated no in test case or it should fail

#### Screenshots

![image](https://user-images.githubusercontent.com/39269658/154846264-1962359b-e7fe-4ece-89b9-f3e0abbccd35.png)

**Comment by stormsunshine** [comment]
The duplicate number can appear two or more times. Is there any problem?

**Comment by gandharvas** [comment]
Not an issue
