### ISSUE TITLE
Mistake in solution - 9. Palindrome number

### ISSUE THREAD

**Issue by gahfy** [LeetCode-Feedback/LeetCode-Feedback#6469]
#### Your LeetCode username
gahfy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a logical error in the solution for the problem Palindrome number. The solution says that Space complexity is O(1). I guess it is said because we only use `revertedNumber` whatever the Int is.
I think it would be more logic to consider the size of the number. I mean, if the problem is scaled up to a Long, then the space will be doubled, because reverted number will be a long. So the real Space complexity for this solution is O(n), as it grows linearly as the input number grows.
There is a solution which is using a Space complexity of O(log10(n)). This complexity is because we store the number of digits, which will increase linearly compared to log10(n). Because Integer allows around 10^10 digits to be stored, I wouldn't complain if this was considered as a Space complexity of O(1), This will rely on digitAt and digitNumber methods as below.

##### Kotlin (my preferred language)

```kotlin
import kotlin.math.*

class Solution {
    fun isPalindrome(x: Int): Boolean {
        if(x < 0) return false
        var l = 0
        var r = x.digitNumber() - 1
        while(l < r) {
            if(x.digitAt(l++) != x.digitAt(r--)) {
                return false
            }
        }
        return true
    }
}

fun Int.digitNumber(): Int = log10(this.toDouble()).toInt() + 1
fun Int.digitAt(index: Int): Int = (this / 10.0.pow(index).toInt()) % 10
```

###### Java

*I used to be a Java develooper, so I'm pretty confident about the code*

```java
class Solution {
    public boolean isPalindrome(int x) {
        if(x < 0) return false;
        int l = 0;
        int r = digitNumber(x) - 1;
        while(l < r) {
            if(digitAt(x, l++) != digitAt(x, r--)) {
                return false;
            }
        }
        return true;
    }
    
    public static int digitNumber(int x) {
        return ((int) Math.log10(x)) + 1;
    }
    
    public static int digitAt(int x, int index) {
        return (x / (int) Math.pow(10, index)) % 10;
    }
}
```

###### Python3

*I'm not a Python developer, so it works in the interface, but I cannot guarantee the code is good*

```python3
class Solution:
    def isPalindrome(self, x: int) -> bool:
        if(x < 0):
            return False
        
        l = 0
        r = self.digitNumber(x) - 1
        
        while(l < r):
            if(self.digitAt(x, l) != self.digitAt(x, r)):
                return False
            l+=1
            r-=1
        
        return True
    
    def digitNumber(self, x: int) -> int:
        return int(log10(max(1, x))) + 1
    
    def digitAt(self, x: int, index: int) -> int:
        return x // int(pow(10, index)) % 10
```

#### Language used for code
Kotlin, Java, Python3

**Comment by LC-Sue** [comment]
Hi @gahfy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
