### ISSUE TITLE
Missing constraints in problem description: [307. Range Sum Query - Mutable]

### ISSUE THREAD

**Issue by sekhar179** [LeetCode-Feedback/LeetCode-Feedback#647]
#### Your LeetCode username

sekhar179

#### Category of the bug
- [v ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The problem doesn't mention about constraints of the input range. But it accepts a solution which doesn't validate the input.
The below solution is accepted even though it crashes with some of the inputs.
It will be good if we can mention the constraints about the input being always in valid
#### Code you used for Submit/Run operation

```
// Range Sum Query
class NumArray {
public:
    vector<int> list;
    NumArray(vector<int>& nums) {
        list = nums;
    }
    
    void update(int i, int val) {
        list[i] = val;
    }
    
    int sumRange(int i, int j) {
        int sum = 0;
        for (int x = i; x <= j; x++) {
            sum += list[x];
        }
        return sum;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input: ["NumArray","sumRange","update","sumRange"]
[[[1,3,5]],[0,3],[3,2],[0,2]]
Expected Output: [null,9,null,9]
Actual Output: Crash

**Comment by lc-christina** [comment]
Hi @sekhar179 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @sekhar179 ,
Thank you for your time. We've used your feedback to update the problem. Missing constraints is a well-known issue for old problems and the team is now working on adding constraints back case by case. We reward the first missing constraints ticket you reported but will not give reward to the similar tickets in the future. However, you're still welcome to file missing constraints tickets here and the team will update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
