### ISSUE TITLE
Incorrect Test Case- 368. Largest Divisible Subset

### ISSUE THREAD

**Issue by Jonathanace** [LeetCode-Feedback/LeetCode-Feedback#6471]
Input: [4,8,10,240]
Output: [240,8,10,4]
Expected Output: [4,8,240]

**Description:**
Given a set of distinct positive integers nums, return the largest subset answer such that every pair (answer[i], answer[j]) of elements in this subset satisfies:

answer[i] % answer[j] == 0, or
answer[j] % answer[i] == 0
If there are multiple solutions, return any of them.

Since 240%10 == 0, wouldn't 10 be included in the solution?

**Comment by stormsunshine** [comment]
Every pair satisfies the conditions. 10 can't be in the same subset with 4 or 8.

**Comment by Jonathanace** [comment]
> 

Thank you!
