### ISSUE TITLE
Missing Test Case - 169. Majority Element

### ISSUE THREAD

**Issue by sugandhnair** [LeetCode-Feedback/LeetCode-Feedback#6474]
Missing test cases with INT_MIN as one of the array elements : -> 

#### Your LeetCode username
 sugandhnair26
https://leetcode.com/sugandhnair26/

#### Category of the bug
- [X ] Missing Test Cases 

#### Description of the bug
Majority of the submissions using C language as posted in the discussion section are using the built in qsort() function , but the constraint clearly mentions lowest value of nums[i] to be -2^31 i.e -2147483648 , whenever INT_MIN is passed to the qsort function when data type is integer will lead to a runtime error (Interger overflow), but since this is not included in the test cases all the solutions with qsort() used for sorting are getting accepted.    

For example : The test case [-2147483648,-2343424,22,22,22,22,22,22,14224,214124] which should return the value 22 will instead cause a runtime error if qsort function is used for sorting.

I have posted below a accepted C solution that uses built in qsort() function for sorting.

Please include a testcase that includes INT_MIN.

Thanks.

#### Code you used for Submit/Run operation

```
//compare function for use in qsort
int compare(const void *a,const void *b) {
    const int *ia = (const int *)a;
    const int *ib = (const int *)b;
    return *ia - *ib;
}

//Using sort and return the middle element will always be majority
int majorityElement(int* nums, int numsSize){
    qsort (nums, numsSize, sizeof(int), compare);
    return nums[numsSize/2];
}
```

#### Language used for code
**C** 

#### Expected behavior
This should lead to a runtime error when **INT_MIN** is one of the elements of integer array nums.

#### Screenshots
![image](https://user-images.githubusercontent.com/61353024/154908276-7d8ad4f4-bbbb-4a63-a6ad-906bdae2eb20.png)

**Comment by LC-Sue** [comment]
Hi @sugandhnair 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @sugandhnair 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
