### ISSUE TITLE
剑指offer 50 官方题解（C++）方法一  存在错误

### ISSUE THREAD

**Issue by bulangman277** [LeetCode-Feedback/LeetCode-Feedback#6475]
**你的 LeetCode 用户名**
15622771609

**Bug 类型**
- [ 剑指offer50] 题目
- [ Leetcode官方题解方法一] 题解
- [C++ ] 编程语言
- [ 测试样例不全] 缺少测试用例

**描述**
当我用unordered_map来存储字符时并不能保证其顺序，所以也就不能保证是第一个出现的。而再官方题解的法一中的第二个for循环直接遍历unordered_map。虽然最后的提交通过了，但是当我们的测试用例改为  "tuvwxyzabcdefghijklmnopqrs"  时，我们就会发现，本题的测试用例是不全的。且官方题解的法一也是有问题的。

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    char firstUniqChar(string s) 
    {
        int number=0;
        unordered_map<char,int> map;
        for(int i = 0;i<s.size();i++)
        {
            if(map.count(s[i]))
            {
                map[s[i]]=-1;
            }
            else
            {
                map[s[i]]++;
            }
        }
        char res=' ';
        for(auto p : map)
        {
            if(p.second==1)
            {
                res=p.first;
            }
        }
        return res;
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
![image](https://user-images.githubusercontent.com/68222021/154922874-a27b2fa6-a5d1-4ea9-bc4e-ad46cd5bab84.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by stormsunshine** [comment]
@bulangman277 虽然你提供的测试用例确实是遗漏的测试用例，但是你的代码和官方题解的代码逻辑不一样，你凭什么喷官方题解？
官方题解的做法是用哈希表统计频数之后遍历字符串找第一个只出现一次的字符，而不是遍历哈希表！你有没有试过原封不动地复制官方题解的代码，运行你提供的测试用例，结果是什么？
是不是你认为只要有遗漏的测试用例，官方题解就有问题？这是什么流氓逻辑？
发现有遗漏的测试用例就明确说是有遗漏的测试用例，不要无缘无故地喷官方题解！

**Comment by bulangman277** [comment]
> 感谢反馈，此问题已转给题目运营团队会尽快确认。

官方的题解法一没有问题，是我误解了，给你的工作带来不便我很抱歉。

但是测试样例确实存在缺漏的情况，希望能收到我的反馈，谢谢。

**Comment by stormsunshine** [comment]
你说你没有喷官方题解，但是给我的感觉就是泼脏水，可能你会认为这个词不好听，但是你认为看到你的描述的人会高兴吗？
请换位思考，如果你做的一件事情明明是对的，但是别人没有调查清楚就说你做错了，你会怎么想？
在不确定对方是否错误的情况下，请不要随意评价。无故把对的人和事说成错的，任何人都不会高兴。

> > @bulangman277 虽然你提供的测试用例确实是遗漏的测试用例，但是你的代码和官方题解的代码逻辑不一样，你凭什么喷官方题解？
> > 官方题解的做法是用哈希表统计频数之后遍历字符串找第一个只出现一次的字符，而不是遍历哈希表！你有没有试过原封不动地复制官方题解的代码，运行你提供的测试用例，结果是什么？
> > 是不是你认为只要有遗漏的测试用例，官方题解就有问题？这是什么流氓逻辑？
> > 发现有遗漏的测试用例就明确说是有遗漏的测试用例，不要无缘无故地喷官方题解！
> 
> 感谢你的思考与反馈。刚才再次看了官方的法一，确实是我误解了官方的思路，也没有用法一的源码去测试我的测试样例。这里给你和Leetcode官方组道歉。
> 
> 但是请你保持冷静，我并没有做出言语不当的反馈，也不存在你提到的“喷”。请你在互联网上控制你的脾气，谢谢。

**Comment by zuizaiqinshi** [comment]
@bulangman277 感谢用户的反馈， 运营团队已确认官方题解法一问题不存在，所以不需要调整，其余问题后续优化时会调整。感谢您对力扣的支持，有任何问题欢迎留言反馈~谢谢
