### ISSUE TITLE
297. Serialize and Deserialize Binary Tree: Test cases are missing. 

### ISSUE THREAD

**Issue by kumanoit** [LeetCode-Feedback/LeetCode-Feedback#6476]
#### Your LeetCode username
kumanoit

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
This is not a bug but seems like there is a gap in running test cases.
I saw a solution which was 100% efficient but doesn't seem correct, (attached code in next section)

While serializing, every tree is serialized as an empty string

While deserializing, the root which was cached is returned.

#### What could be the issue?
I feel that while running test cases following thing happens:

1. an object of Codec is created and is used to serialize a tree. 
2. Tree is saved in Codec global object `temp` and then empty string is returned. 
3. Then the test case calls deserialize method on the serialized string (which is empty).
4. Since the `temp` object holds the `root` of the tree, it is returned
5. The returned `root` is compared with the input tree and the test case runs successfully.

Seems like the test code is written like below
```
public class SerializeDeserializeTest {
    public static void main(String[] args) {
        Codec codec = new Codec();
        TreeNode root = TreeUtils.createTree(new Integer[] {1,2,3,4});
        
        // root is saved in temp object of Codec class and empty String is returned. serialized=""
        String serialized = codec.serialize(root); 

        // root saved in temp is returned
        TreeNode deserialized = codec.deserialize(serialized);

        // both root and deserialized are pointing to the same object root, hence test cases runs successfully without complaining.
        assertEquals(root, deserialized); 
    }
}
```

#### Code used for Submit/Run operation
```
public class Codec {
    static TreeNode temp;
    // Encodes a tree to a single string.
    public String serialize(TreeNode root) {
        temp = root;
        return "";
    }

    // Decodes your encoded data to tree.
    public TreeNode deserialize(String data) {
        return temp;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Test cases should be written somewhat like below
```
public class SerializeDeserialize {
    public static void main(String[] args) {
        Codec codec = new Codec();
        TreeNode root1 = TreeUtils.createTree(new Integer[] {33,null,22,null,53,null,64});
        TreeNode root2 = TreeUtils.createTree(new Integer[] {1,2,3,4});
        String serialized1 = codec.serialize(root1);
        String serialized2 = codec.serialize(root2);
        TreeNode deserialized1 = codec.deserialize(serialized1);
        TreeNode deserialized2 = codec.deserialize(serialized2);
        assertEquals(root1, deserialized1);
        assertEquals(root2, deserialized2);
    }
}
```

This will ensure that root is not cached in instance of Codec but should work like a utility function.

#### Screenshots
NA

#### Additional context
NA

**Comment by kumanoit** [comment]
One more way to test could be to create two Codec object. Use one to serialize and other to deserialize.
```
public class SerializeDeserialize {
    public static void main(String[] args) {
        Codec codecSerializer = new Codec();
        Codec codecDeserializer = new Codec();
        TreeNode root = TreeUtils.createTree(new Integer[] {1,2,3,4});
        String serializedString = codecSerializer.serialize(root);
        TreeNode deserializedRoot = codecDeserializer.deserialize(serializedString);
        assertEquals(root, deserializedRoot);
    }
}
```

**Comment by LC-Sue** [comment]
Hi @kumanoit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kumanoit,
Thank you for your time, our team as reviewed your report and we believe the current test cases are fine!
