### ISSUE TITLE
5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by 20yyq** [LeetCode-Feedback/LeetCode-Feedback#648]
** Bug 类型**
5. Longest Palindromic Substring
两种解题BUG
第一种
func longestPalindrome(s string) string {
	lenMap := make(map[string]int, 24)
	indexMap := make(map[string]int, 24)
	for i := 0; i < len(s); i++ {
		tempStr := string(s[i])
		if i == 0 {
			lenMap[tempStr] = 1
			continue
		} else if i != 0 && indexMap[tempStr] == 0 && lenMap[tempStr] == 0 {
			indexMap[tempStr] = i
			lenMap[tempStr] = 1
		} else {
			lenMap[tempStr] = i-indexMap[tempStr]+1
		}
		if i < len(s)-1 {		
			if string(s[i-1]) != tempStr || string(s[i+1]) != tempStr {
				indexMap[tempStr] = i
			}
		}
		if i == len(s)-1 {
			indexMap[tempStr] = i
		}
		if lenMap[tempStr] > 23 {
			break
		}
	}
	var maxLen int = 0
	var maxItem string = ""
	for k, v := range lenMap {
		if v > maxLen {
			maxLen = v
			maxItem = k
		}
	}
	var returnStr string = ""
	start := indexMap[maxItem]-(lenMap[maxItem]-1)
	end := indexMap[maxItem]+1
	if end > 2 && string(s[0]) == maxItem && string(s[len(s)-1]) == maxItem {
		return string(s[0])
	}
	for i := start; i < end; i++ {
		returnStr += string(s[i])
	}
    return returnStr
}
第二种
func longestPalindrome(s string) string {
	lenMap := make(map[string]int, 24)
	indexMap := make(map[string]int, 24)
	for i := 0; i < len(s); i++ {
		tempStr := string(s[i])
		if i == 0 {
			lenMap[tempStr] = 1
			continue
		} else if i != 0 && indexMap[tempStr] == 0 && lenMap[tempStr] == 0 {
			indexMap[tempStr] = i
			lenMap[tempStr] = 1
		} else {
			lenMap[tempStr] = i-indexMap[tempStr]+1
		}
		log.Println(indexMap[tempStr], lenMap[tempStr])
		if i < len(s)-1 {		
			if string(s[i-1]) != tempStr || string(s[i+1]) != tempStr {
				indexMap[tempStr] = i
			}
		}
		if i == len(s)-1 {
			indexMap[tempStr] = i
		}
		if lenMap[tempStr] > 23 {
			break
		}
	}
	var maxLen int = 0
	var maxItem string = ""
	for k, v := range lenMap {
		if v > maxLen {
			maxLen = v
			maxItem = k
		}
	}
	var returnStr string = ""
	for i := indexMap[maxItem]-(lenMap[maxItem]-1); i < indexMap[maxItem]+1; i++ {
		returnStr += string(s[i])
	}
go语言

**描述**
第一种输出 告诉不是最长，ccc 这样的应该是全字符串吧  字符串应该是 c ?
第二种输出 应该是我第一次提交  abcda 这样的最长字符串 应该跟第一种的提交是一个道理了吧  但是输出告诉我 只有一个a

**屏幕截图**
![image](https://user-images.githubusercontent.com/29622672/87682281-3e352d80-c7b2-11ea-9a58-b6fab1541c01.png)
![image](https://user-images.githubusercontent.com/29622672/87682307-44c3a500-c7b2-11ea-8da7-02686a331d71.png)

**Comment by feiceh** [comment]
感谢反馈，建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，请仔细调试优化一下代码。
