### ISSUE TITLE
507. 完美数的测试用例有误

### ISSUE THREAD

**Issue by RayLTL** [LeetCode-Feedback/LeetCode-Feedback#6484]
示例2如下：
  输入：num = 7
  输出：true
![2022-02-22 10-21-03 的屏幕截图](https://user-images.githubusercontent.com/51083842/155051257-353e09cc-6164-4fff-9fec-6a1cc5078db7.png)

但实际上7的正因子 之和 = 1+7 =8，应该返回的结果为False,在控制台中输入7，返回的也是False

![2022-02-22 10-21-46 的屏幕截图](https://user-images.githubusercontent.com/51083842/155051298-36cc23cc-89ae-44a0-b5b1-a2b5e3596d28.png)

因此题目描述中的示例2有问题，需要修改。

**Comment by feiceh** [comment]
感谢反馈，能否向我们补充题目相关信息，以及完善代码格式。可以参考[这个示例(https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/new?assignees=&labels=&template=bug--------.md&title=），把信息提供完整才能有助于快速验证和精准的定位，谢谢。

**Comment by feiceh** [comment]
@RayLTL 在与相关团队核实后：题面中有写 “除了它自身以外的所有 正因子”，因此  7 的符合要求的正因子之和 = 1，请悉知，本次 Ticket 将关闭，感谢支持力扣。

**Comment by RayLTL** [comment]
仍应该返回False，题目要求的是“对于一个 正整数，如果它和除了它自身以外的所有 正因子 之和相等，我们称它为 「完美数」”。而7的正因子之和=1，`7!=1` @feiceh

**Comment by feiceh** [comment]
@RayLTL 题面问题已修复。
