### ISSUE TITLE
Missing Test Case - 387. First Unique Character in a String

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6486]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A solution that gets accepted fails on a specific test case. The test case is as follows.
```
"tuvwxyzabcdefghijklmnopqrs"
```

#### Code you used for Submit/Run operation
```C++
class Solution {
public:
    int firstUniqChar(string s)
    {
        int number=0;
        unordered_map<char,int> map;
        unordered_map<char,int> indices;
        for(int i = 0;i<s.size();i++)
        {
            if(map.count(s[i]))
            {
                map[s[i]]=-1;
            }
            else
            {
                map[s[i]]++;
            }
            indices[s[i]]=i;
        }
        int res=-1;
        for(auto p : map)
        {
            if(p.second==1)
            {
                res=indices[p.first];
            }
        }
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Add the following test case to make the code above get Wrong Answer when submitted.
```
"tuvwxyzabcdefghijklmnopqrs"
```

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
