### ISSUE TITLE
Missing Testcase - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by hiteshvijayhv** [LeetCode-Feedback/LeetCode-Feedback#6487]
#### Your LeetCode username

hiteshvijay

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I tried to use code that fails when we have negative elements in the given matrix and it passed all the test cases

#### Code you used for Submit/Run operation

```
// Set Matrix Zeroes
class Solution {
public:
    void setZeroes(vector<vector<int>>& matrix) {
        int count = 0;
        
        for(int row = 0; row < matrix.size(); row++){
            for(int col = 0; col < matrix[0].size(); col++){
                if(matrix[row][col] == 0){
                    count++;
                    markRow(row, col, matrix);
                    markCol(row, col, matrix);
                }
            }
        }
        
        if(count > 0){
            for(int row = 0; row < matrix.size(); row++){
            for(int col = 0; col < matrix[0].size(); col++){
                if(matrix[row][col] == -1){
                    matrix[row][col] = 0;
                }
            }
        }
    }
    }
    
    void markRow(int i, int j, vector<vector<int>> &matrix){
        int col = matrix[0].size();
        int itr = 0;
        
        while(itr < col){
            if(matrix[i][itr] != 0){
                matrix[i][itr] = -1;
            }
            itr++;
        }
        
    }
    
    void markCol(int i, int j, vector<vector<int>> &matrix){
        int row = matrix.size();
        int itr = 0;
        
        while(itr < row){
            if(matrix[itr][j] != 0){
                matrix[itr][j] = -1;
            }
            itr++;
        }
    }
};
```

#### Language used for code

C++

#### Expected behavior

This code should have been failed with matrix with negative elements like this one however it surprisingly passed all the testcases.
[[0,1,2,0],[3,-1,5,2],[1,3,1,5]]

**Comment by LC-Sue** [comment]
Hi @hiteshvijayhv 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hiteshvijayhv,
Thank you for your time, our team has reviewed the issue and have decided that we will keep this solution passing because changing -1 to any other value will make it accepted again and it is impossible to cover all the hacks.
