### ISSUE TITLE
 171. Excel Sheet Column Number java

### ISSUE THREAD

**Issue by ShubhamKatiyar1** [LeetCode-Feedback/LeetCode-Feedback#6488]
class Solution {
    public int titleToNumber(String columnTitle) {
        
        HashMap<Character,Integer> hm=new HashMap<>();
        int z=1;
                for(char i='A';i<='Z';i++)
                {
                    hm.put(Character.valueOf(i),z);
                    z++;
                }
        int l=columnTitle.length();
        int ans=0;
       if(l>1)
       {
            for(int i=l-1;i>=0;i--)
        {
            String ns=columnTitle.substring(i);
             int res;
         if(ns.length()>0){
           res=   hm.get(ns.charAt(0))*(int)Math.pow(26,ns.length()-1);
             ans=ans+res;
        }
        }
       }
        else{
            ans= hm.get(columnTitle.charAt(0));
        }
          return ans;
    }
    }

**Comment by LC-Sue** [comment]
Hi @ShubhamKatiyar1 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
