### ISSUE TITLE
Missing Test Case - 1366. Rank Teams by Votes

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#6489]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
```
["ABCDEFGH", "BACDEFGH", "GHABCDEF", "GHBACDEF", "EFGHABCD", "EFGHBACD", "CDEFGHBA", "CDEFGHBA"]
```

#### Code you used for Submit/Run operation

```
public class Solution 
{
    public string RankTeams(string[] votes)
    {
        Dictionary<char, double> teamScore = new Dictionary<char, double>();
        int n = votes[0].Length, power = 1000;
        foreach(string s in votes)
        {
            for(int i=0;i<s.Length;++i)
            {
                char team = s[i];
                if (teamScore.ContainsKey(team)) teamScore[team] += Math.Pow(power, n - i);
                else teamScore[team] = Math.Pow(power, n-i);
            }
        }
        IEnumerable<char> cc = teamScore.Keys.OrderByDescending(x => teamScore[x]).ThenBy(x => x);
        return new string(cc.ToArray());
    }
}
```

#### Language used for code

C#

#### Expected behavior

Output: "CEGABFHD"
Expected: "CEGBADFH"

**Comment by LC-Sue** [comment]
Hi @Rad0miR 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Rad0miR 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
