### ISSUE TITLE
Power of Three - wrong Test Case

### ISSUE THREAD

**Issue by CoderSaty** [LeetCode-Feedback/LeetCode-Feedback#6490]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test case is actually not missing but the given test case is wrong. Here are the two test cases which are wrong 

1. Input : 0 
    Output: true
    Expected Output is false which is wrong because  3^0( 3 raised to the power 0 ) = 0 and 0 is an integer and in the question it is clearly mentioned that ,"An integer n is a power of three, if there exists an integer x such that n == 3^x (3 raised to the power x)."

2. Input : 1
    Ouput : false
    Expected: True which is completely wrong because there is no integer x which will give when we raise 3 to the power of x.
#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isPowerOfThree(int n) {
        n=abs(n);
        if(n==0)
            return true;
        if(n<=2)
            return  false;
        while(n%3==0 && n!=3)
        {
            n=n/3;
        }
        if(n==3)
            return true;
        else 
            return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected to get the output as true for input 0 and false for input 1 but the expected outcome was completely opposite.

**Comment by stormsunshine** [comment]
Why do you think 3<sup>0</sup> = 0?

For any number b such that b is not 0, b<sup>0</sup> is always 1. Therefore, for input 0 the answer is false, and for input 1 the answer is true.
