### ISSUE TITLE
Missing Test Case - 1691. Maximum Height by Stacking Cuboids

### ISSUE THREAD

**Issue by cckao** [LeetCode-Feedback/LeetCode-Feedback#6491]
#### Your LeetCode username
cceimafa

#### Category of the bug
Missing Test Cases 

#### Description of the bug
The answers are problematic. For example, the expected answer of input [[16,20,30],[15,25,35]] is 35, but the correct answer is 51.

#### Code you used for Submit/Run operation
It's not relevant to the code submitted. The expected answers are wrong.

**Comment by stormsunshine** [comment]
The correct answer is indeed 35. You can't place any cuboid on the other cuboid.

**Comment by cckao** [comment]
Yes you can. Since the question states that the cuboid can be rotated, the first cuboid can be rotated as [20,30,16] ([width,length,height]) and the second cuboid can be placed on it.

**Comment by stormsunshine** [comment]
@cckao After the first cuboid is rotated as [20,30,16], how do you place the second cuboid on it? The second cuboid has a dimension 35 which is larger than any of the dimensions of the first cuboid.

Also, you can't place the first cuboid on the second cuboid no matter how you rotate the two cuboids.

**Comment by cckao** [comment]
@stormsunshine,

You are right. I don't know why I didn't see the requirement that heights of cuboids also need to be descending. Silly me. Thanks for your help.
