### ISSUE TITLE
Test Case Verification - 1147. Longest Chunked Palindrome Decomposition

### ISSUE THREAD

**Issue by Umesh-JNU** [LeetCode-Feedback/LeetCode-Feedback#6492]
Can someone give the verification of the testcase 34.
As my output is wrong.
![image](https://user-images.githubusercontent.com/56982559/155112388-2d3f5832-0314-4269-8d50-3c23587e19a6.png)

Umesh-JNU

**Comment by LC-Sue** [comment]
Hi @Umesh-JNU,
Thank you for reaching out to us, our judger appears to be correct. Please feel free to refer to the discuss section of the problem to see how other user's have optimized their codes!
