### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by FernandoTanaseMosneagu** [LeetCode-Feedback/LeetCode-Feedback#6493]
#### Your LeetCode username

Alibaba420

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

when calling stack.isEmpty(); , the method returns true even when the stack is not empty.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @FernandoTanaseMosneagu 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
