### ISSUE TITLE
509. Fibonacci Number

### ISSUE THREAD

**Issue by sanukumar123** [LeetCode-Feedback/LeetCode-Feedback#6495]
class Solution {
    // public int fib(int n) {
    //     if(n <= 1) {
    //         return n;
    //     }
    //     return fib(n - 1) + fib(n - 2);
    // }
    
    int[] helper = new int[31];
    public int fib(int n) {
        if(n <= 1) {
            return n;
        }
        if(helper[n] > 0){
            return helper[n];
        }
        helper[n] = fib(n-1) + fib(n-2);
        return helper[n];
    }
}

**Comment by LC-Sue** [comment]
Hi @sanukumar123 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
