### ISSUE TITLE
1391. Check if There is a Valid Path in a Grid is missing a test case

### ISSUE THREAD

**Issue by martinschneider** [LeetCode-Feedback/LeetCode-Feedback#65]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
I submitted a [simple solution](https://leetcode.com/submissions/detail/314844327/) for problem 1391.

**what language is your code written in**
Java

**The code you submit/run**
```
class Solution {   
    private static final List<Integer> RIGHT = Arrays.asList(1,4,6);
    private static final List<Integer> LEFT = Arrays.asList(1,3,5);
    private static final List<Integer> UP = Arrays.asList(2,5,6);
    private static final List<Integer> DOWN = Arrays.asList(2,3,4);
    
    public boolean hasValidPath(int[][] grid) {
        boolean visited[][] = new boolean[grid.length][grid[0].length];
        int x=0; int y=0;
        while(true)
        {
            if (x==grid.length-1 && y==grid[0].length-1) return true;
            else if (y+1<grid[0].length && !visited[x][y+1] && RIGHT.contains(grid[x][y]) && LEFT.contains(grid[x][y+1])) y++;
            else if (y-1>=0 && !visited[x][y-1] && LEFT.contains(grid[x][y]) && RIGHT.contains(grid[x][y-1])) y--;
            else if (x+1<grid.length && !visited[x+1][y] && DOWN.contains(grid[x][y]) && UP.contains(grid[x+1][y])) x++;
            else if (x-1>=0 && !visited[x-1][y] && UP.contains(grid[x][y]) && DOWN.contains(grid[x-1][y])) x--;
            else break;
            visited[x][y]=true;
        }
        return false;
    }
}
```

**Expected behavior**
This should not be accepted as a correct answer.

For example, it fails the following simple test case:
`[[4,1,1],[6,1,1]]`

**Comment by CooperCooperCooper** [comment]
Hi @martinschneider,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @martinschneider,
Thank you for your time. Thanks to your timely feedback, we've updated the problem by adding several test cases, including the one you've contributed. Please send us a message to the main support channel with some form of proof to claim your test case contribution reward: https://support.leetcode.com/hc/en-us. We appreciate your support.
