### ISSUE TITLE
Incomplete description - 393. UTF-8 Validation

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#650]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

393. UTF-8 Validation
https://leetcode.com/problems/utf-8-validation/

Question says:
> For 1-byte character, the first bit is a 0, followed by its unicode code.
> For n-bytes character, the first n-bits are all one's, the n+1 bit is 0, followed by n-1 bytes with most significant 2 bits being 10.

And

> Given an array of integers representing the data, return whether it is a valid utf-8 encoding.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Expected:
Question should add details if Array can contain multiple separate group of bytes, that can form a single utf-8 char.

In example it says:
> " It is a valid utf-8 encoding for a 2-bytes character followed by a 1-byte character. "

Actual:
The "followed by" clause is not mentioned to be valid in the Question.

#### Screenshots
-

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy,
After reviewing this report, our team has decided that this detail is well explained in the examples and will not need any further explanation. I will now close this request. Thank you for reaching out. and for your understanding!

**Comment by manoharreddyporeddy** [comment]
I have clearly told below:

    The "followed by" clause is not mentioned to be valid in the Question.

It's ok, if you decide its all good.
