### ISSUE TITLE
411. 最短独占单词缩写 的数据范围表述有误

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#6500]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
hqztrue

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
提示中 1 <= dictionary[i] <= 100 应为 1 <= dictionary[i].length <= 100。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@hqztrue  你好，当前题目中英文描述已更新，ID：hqztrue 给予积分奖励，请查收。
