### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by fogonthedowns** [LeetCode-Feedback/LeetCode-Feedback#6506]
#### Your LeetCode username
fogonthedowns

#### Category of the bug
- [ x] Missing Test Cases 

#### Description of the bug
The accepted solution does not handle multibyte utf-8 characters. Go strings are []byte not []utf-8 characters. The multibyte character á, code point 225, should fail.

#### Code you used for Submit/Run operation

This go test will not pass with the accepted solution:

```
          in = "áááááááááá"
          in2 = "á*"
          out = isMatch(in, in2)
          want = true
          if out != want {
                 t.Errorf("got %t, want %t", out, want)
         }
 
```

#### Language used for code
GoLang

#### Expected behavior
I expected the test to pass

#### Screenshots
n/a

#### Additional context
https://go.dev/blog/strings

**Comment by stormsunshine** [comment]
The constraints require that `s` and `p` contain only English lowercase letters, `'.'` and `'*'`. Why do you want to add the test case with multibyte utf-8 characters?

**Comment by LC-Sue** [comment]
Hi @fogonthedowns,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Feel free to reach out if you have any other questions!
