### ISSUE TITLE
Typo in the solution - 169. Majority Element

### ISSUE THREAD

**Issue by smith558** [LeetCode-Feedback/LeetCode-Feedback#6507]
#### Your LeetCode username
user6728u

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the solution for 169. Majority Element (https://leetcode.com/problems/majority-element/solution/ ) I believe there's a typo in sentences describing the reasoning behind the _Approach 3: Sorting_.

![image](https://user-images.githubusercontent.com/44023416/155303154-0e14c851-57cf-43eb-bbf0-c163c848f0cd.png)

The correct reasoning would be:
![image](https://user-images.githubusercontent.com/44023416/155303248-d3293d8a-9f6b-4ded-b1f7-f7c298b22f47.png)

There should be a minus instead of a plus.

#### Additional context
![image](https://user-images.githubusercontent.com/44023416/155304102-9c883018-1df7-45b8-a925-91bb09485cda.png)

**Comment by LC-Sue** [comment]
Hi @smith558 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @smith558 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
