### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by muhammadihabk** [LeetCode-Feedback/LeetCode-Feedback#6508]
#### Your LeetCode username

MuhammadIhabK

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My algorithm provide wrong answer for case: [1,0]. But it was accepted

#### Code you used for Submit/Run operation

```
// Find Pivot Index
class Solution {
    public int pivotIndex(int[] nums) {
        if(nums.length == 1) { return 0; }
        if(nums.length == 2) { return -1; }
        int leftSum = 0;
        int rightSum = 0;
        for(int i = 1; i < nums.length; i++) {
            rightSum += nums[i];
        }
        if(leftSum == rightSum) {
                return 0;
        }
        for(int i = 1; i < nums.length; i++) {
            leftSum += nums[i-1];
            rightSum -= nums[i];
            if(leftSum == rightSum) {
                return i;
            }
        }
        
        return -1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

This case should be added.

#### Screenshots

![image](https://user-images.githubusercontent.com/69121442/155324990-0606bb9d-7e94-41bc-9816-f26beeb8717e.png)

**Comment by LC-Sue** [comment]
Hi @muhammadihabk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @muhammadihabk 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
