### ISSUE TITLE
Incomplete description - 318. Maximum Product of Word Lengths

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#651]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
318. Maximum Product of Word Lengths
https://leetcode.com/problems/maximum-product-of-word-lengths/

Description does not have contraints

Please add below:
1. Max Count of strings, in the string array
2. Max Length of each string, in the string array

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Expected:
Question constraints are very import in designing an optimal algorithm that does not timeout.

Below constraints must be given in the question
1. Max Count of strings, in the string array
2. Max Length of each string, in the string array

Actual:
Above constraints are missing in the question.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy,
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by manoharreddyporeddy** [comment]
Thank you, I can see the constraints now. 👍

Do you think I should get any Leet Coins for this?
 similar to https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/667#issuecomment-662767281
