### ISSUE TITLE
Better solution - 303. Range Sum Query - Immutable

### ISSUE THREAD

**Issue by gahfy** [LeetCode-Feedback/LeetCode-Feedback#6510]
#### Your LeetCode username
gahfy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of a better solution
Actually, it is possible to make an O(1) solution if we consider one statement which is not clearly told in the description of the problem :

* We don't need the values of the nums array after doing the query

If we consider this statement as true (which it is in the context of leetcode execution) then we can modify the values in place. And in that case, we just need to store a pointer to the array passed as argument:

##### Kotlin
```kotlin
class NumArray(private val nums: IntArray) {
    init {
        for(i in nums.indices) {
            nums[i] = if(i == 0) nums[i] else nums[i-1] + nums[i]
        }
    }

    fun sumRange(left: Int, right: Int): Int {
        return nums[right] - if(left == 0) 0 else nums[left-1]
    }

}
```

##### Java
```
class NumArray {
    private final int[] nums;
    
    public NumArray(int[] nums) {
        this.nums = nums;
        for(int i=0; i<nums.length; i++) {
            nums[i] = (i == 0 ? 0 : nums[i-1]) + nums[i];
        }
    }
    
    public int sumRange(int left, int right) {
        return nums[right] - (left == 0 ? 0 : nums[left - 1]);
    }
}
```

##### Python
I'm not sure about how python works, and if the array passed as argument is a pointer or a copy of the array. In the second case, a similar solution should work

#### Language used for code
Kotlin and Java

**Comment by LC-Sue** [comment]
Hi @gahfy,
Thank you for your time, our team is aware of the suggestion and we will consider adding it when the article is next updated.
