### ISSUE TITLE
Missing Test Case - 2080. Range Frequency Queries

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#6511]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution gets Runtime Error (Out of memory.) on the following testcase:
[2080_missing_test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8124954/2080_missing_test_case.txt)

#### Code you used for Submit/Run operation

```
public class RangeFreqQuery 
{
    private int[] _arr;
    private Dictionary<int, int[]> _dict = new();
    
    private int[] Sums(int val) 
    {
        if (!_dict.ContainsKey(val)) 
        {
            var row = new int[_arr.Length + 1];
            _dict.Add(val, row);
            for (int i = 1; i < row.Length; ++i) 
                row[i] += row[i - 1] + IsHere(val, i - 1);
        }
        return _dict[val];
    }
    
    private int IsHere(int val, int i) => _arr[i] == val ? +1: 0;
    
    public RangeFreqQuery(int[] arr) => _arr = arr;
    
    public int Query(int left, int right, int val) 
    {
        var sums = Sums(val);
        return sums[right + 1] - sums[left];
    }
}
```

#### Language used for code

C#

#### Expected behavior

The code gets Runtime Error(Out of memory.).

**Comment by LC-Sue** [comment]
Hi @Rad0miR 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Rad0miR 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
