### ISSUE TITLE
Missing Similar quesion - 680. Valid Palindrome II

### ISSUE THREAD

**Issue by J1effrey** [LeetCode-Feedback/LeetCode-Feedback#6513]
similar question: Valid Palindrome III (LC-1216)
https://leetcode.com/problems/valid-palindrome-iii/

**Comment by LC-Sue** [comment]
Hi @J1effrey 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @J1effrey 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
