### ISSUE TITLE
Missing Test Case - 489. Robot Room Cleaner

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#6515]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8127073/1.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    void cleanRoom(Robot& robot) {
        for(int i = 0; i < 1000000; ++i) {
            robot.clean();
            int x = rand() % 4;
            // printf("%d\n", x);
            for(int j = 0; j < x; ++j) {
                robot.turnLeft();
            }
            bool y = robot.move();            
        }
    }
};
```

#### Language used for code

C++

#### Expected behavior

Output: The robot did not clean all rooms - 6998 rooms were not cleaned.   [[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2...
Expected: Robot cleaned all rooms.

**Comment by LC-Sue** [comment]
Hi @hqztrue,
Thank you for reaching out to us, the code you provided already TLE!

**Comment by hqztrue** [comment]
Then how about this code:
```
struct RNG_F{
    unsigned int seed;
    RNG_F(unsigned int s):seed(s){}
    float operator()(){
        seed=seed*214013+2531011;
        union{
            unsigned int u;
            float f;
        }u={(seed>>9)|0x3F800000};
        return u.f-1.0f;
    }
};
inline float rand01F(){static RNG_F r(31253125);return r();}
class Solution {
public:
    void cleanRoom(Robot& robot) {
        for(int i = 0; i < 700000; ++i) {
            robot.clean();
            int x=rand01F()*4;
            for(int j = 0; j < x; ++j) {
                robot.turnLeft();
            }
            bool y = robot.move();
        }
    }
};
```
It currently gets accepted.
![image](https://user-images.githubusercontent.com/11583428/155586172-491a6e2c-5029-4b17-9105-fac59bf40607.png)
