### ISSUE TITLE
Seemingly broken question

### ISSUE THREAD

**Issue by AOCain-schoolwork** [LeetCode-Feedback/LeetCode-Feedback#6519]
#### Your LeetCode username

LCBathTissue

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In checking my solution for this problem..
https://leetcode.com/problems/final-value-of-variable-after-performing-operations/
I determined that either I am doing something wrong or the output is being calculated incorrectly because leetcode determined an output of 0 which is incorrect yet the same code in my IDE resulted in an output of 1

#### Code you used for Submit/Run operation

```
public class Main {
    public static void main(String[] args){
        String[] operations = {"--X","X++","X++"};
        System.out.println(finalValueAfterOperations(operations));
    }
    public static int finalValueAfterOperations(String[] operations) {
        int myInt = 0;
        for(int k = 0; k < operations.length; k++){
            if(operations[k] == "++X"){
                ++myInt;
            } else if(operations[k] == "X++"){
                myInt++;
            } else if(operations[k] == "--X"){
                --myInt;
            } else if(operations[k] == "X--"){
                myInt--;
            }
        }
        return myInt;
    }
}

```

#### Language used for code

Java

#### Expected behavior

Unless I am doing something, this should be correct should it not?

The code I have in finalValueAfterOperations(String[] operations) is the same on leetcode.com as I have in my local editor yet they are producing different results.

#### Screenshots

![image](https://user-images.githubusercontent.com/67986706/155431352-a490c06e-731b-4697-b509-c24d49be20c6.png)
![image](https://user-images.githubusercontent.com/67986706/155431362-ae1a786a-0d5e-488b-9540-bff702fd2fe5.png)

**Comment by stormsunshine** [comment]
You should not use == to compare String objects. Instead, you should use equals method to compare String objects.

**Comment by AOCain-schoolwork** [comment]
> 

that makes perfect sense actually thank you
