### ISSUE TITLE
Incomplete example description - 1442. Count Triplets That Can Form Two Arrays of Equal XOR

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#652]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1442. Count Triplets That Can Form Two Arrays of Equal XOR
https://leetcode.com/problems/count-triplets-that-can-form-two-arrays-of-equal-xor/

The 1st example is given as below:

Input: arr = [2,3,1,6,7]
Output: 4
Explanation: The triplets are (0,1,2), (0,2,2), (2,3,4) and (2,4,4)

Though the triplets are given, how the `xor` is applied unclear.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Expected:
The 1st example is given as below:

> Input: arr = [2,3,1,6,7]
> Output: 4
> Explanation: The triplets are (0,1,2), (0,2,2), (2,3,4) and (2,4,4)

In the `Explanation`, here the triplets answers are given, how the `xor` is applied as explained in the question is not explained. In other words, the `Explanation` does not `explain`.
The examples must explain in a clear way.

Actual:
Example does not explain how the solution came, applying the problem description.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy,
After reviewing this suggestion, our team has come to the conclusion that the example provided by you can be calculated by hand since the values are small resulting in no necessary further explanation.
