### ISSUE TITLE
Missing Test Case - 217.Contains Duplicate

### ISSUE THREAD

**Issue by adityapatel21** [LeetCode-Feedback/LeetCode-Feedback#6526]
#### Your LeetCode username
adityaKpatel

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [☑] Missing Test Cases 

#### Description of the bug
An accepted solution gets Memory Limit exceeded on the following testcase:
[11,1000000000,100000000,12]

#### Code you used for Submit/Run operation
class Solution {
    public boolean containsDuplicate(int[] nums) {
        if (nums.length > 1 && nums[0] == nums[1]) {
            return true;
        }

        int maxValue = Integer.MIN_VALUE;
        int minValue = Integer.MAX_VALUE;
        for (int num : nums) {
            if (num > maxValue) {
                maxValue = num;
            }
            if (num < minValue) {
                minValue = num;
            }
        }
        boolean[] occurrenceArray = new boolean[(maxValue - minValue) + 1];

        for (int i = 0; i < nums.length; i++) {
            if (occurrenceArray[(nums[i] - minValue)]) {
                return true;
            }
            occurrenceArray[(nums[i] - minValue)] = true;
        }
        return false;
    }
}
#### Language used for code
Java

#### Expected behavior
The code gets Memory Limit Exceeded.

**Comment by LC-Sue** [comment]
Hi @adityapatel21 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @adityapatel21 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
