### ISSUE TITLE
Wrong Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by kanika-10** [LeetCode-Feedback/LeetCode-Feedback#6529]
####kanika_10

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong Test Case 

#### I used Bit Manupulation method

```
class Solution {
public:
    int findDuplicate(vector<int>& nums) {
        int x = 1, ans = 0;
        for(int i=0; i<nums.size(); i++)
        {
            ans^= x ^ nums[i];
            x++;
            
            if(x == nums.size())
                x = 0;
        }
        return ans;
    }
};
```

#### C++

####I was expecting that it will show invalid test case  but it is showing wrong answer

#### ![Screenshot (79)](https://user-images.githubusercontent.com/75972713/155486060-7fd88315-dc81-48ce-89aa-0d969b81ffd5.png)

####Kindly remove this test case

**Comment by LC-Sue** [comment]
Hi @kanika-10,
Thank you for reaching out to us, the question means only one number can be repeated not that it can only be repeated once. Sorry for the confusion!
