### ISSUE TITLE
美服同步之后，看不到国服以前的提交记录。写过的题目，也变成未完成了

### ISSUE THREAD

**Issue by KetaoChen** [LeetCode-Feedback/LeetCode-Feedback#653]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
美服同步之后，看不到国服以前的提交记录。写过的题目，也变成未完成了

**你使用的语言**
Java

**你提交或者运行的代码**
```
比如我以前写过的LCP 04. 覆盖，就没有记录了。
```

**期望行为**
希望可以看到自己以前在国服的提交记录。

**屏幕截图**
![image](https://user-images.githubusercontent.com/37752440/87750438-4b511d00-c7b0-11ea-9e11-b804e8a6c687.png)
![image](https://user-images.githubusercontent.com/37752440/87750554-a1be5b80-c7b0-11ea-82ab-45f4e3204718.png)
我在4月份的时候，提交了并写了题解。

**额外的上下文**

**Comment by feiceh** [comment]
进度管理（https://leetcode-cn.com/session/） 里面有几个进度呢？个人的提交记录只会显示当前 session 的提交记录，要切换过去才能看到，当前打开哪个进度即颜色显示为绿色，请知晓。
Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先暂时关闭，后续使用中有任何问题欢迎点击「https://support.leetcode-cn.com/hc/kb/section/1115013」 提交工单反馈，最好带上个性域名以便技术排查，请知晓～
