### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by farshmachine** [LeetCode-Feedback/LeetCode-Feedback#6530]
#### Your LeetCode username
farshmachine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Wrong code passes tests

#### Code you used for Submit/Run operation
```
/**
 * @param {number[]} nums
 * @param {number} k
 * @return {void} Do not return anything, modify nums in-place instead.
 */
var rotate = function(nums, k) {
    nums.unshift(...nums.splice(- (k % nums.length)));
};
```

#### Language used for code
JS

#### Expected behavior
`rotate([1, 2, 3, 4], 7)` makes it `[2, 3, 4, 1]` and it seems like it's wrong answer

**Comment by LC-Sue** [comment]
Hi @farshmachine,
Thank you for reaching out to us, our judger appears to be running correctly. The test case [1, 2, 3, 4], 7 is also fine!
