### ISSUE TITLE
1031. Maximum Sum of Two Non-Overlapping Subarrays

### ISSUE THREAD

**Issue by Sam-Si** [LeetCode-Feedback/LeetCode-Feedback#6531]
#### Your LeetCode username

sam_si

#### Category of the bug
- [ ] Question

#### Description of the bug

Link: https://leetcode.com/problems/maximum-sum-of-two-non-overlapping-subarrays/

In the Explanation of Example 3
```
Input: nums = [2,1,5,6,0,9,5,0,3,8], firstLen = 4, secondLen = 3
Output: 31
Explanation: One choice of subarrays is [5,6,0,9] with length 4, and **[3,8]** with length 3.
```
It should be [0, 3, 8] with length 3 instead of ~~[3,8]~~

#### Expected behavior

Expected [0, 3, 8] instead of ~~[3,8]~~

#### Screenshots

![image](https://user-images.githubusercontent.com/13261099/155509610-cc333153-97e4-4c2a-9ea9-1de9abad2469.png)

**Comment by LC-Sue** [comment]
Hi @Sam-Si 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
