### ISSUE TITLE
Incorrect Explanation in Example - 108. Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6537]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [108. Convert Sorted Array to Binary Search Tree](https://leetcode-cn.com/problems/convert-sorted-array-to-binary-search-tree), the explanation in Example 2 is incorrect.
The explanation is: [1,3] and [3,1] are both a height-balanced BSTs.
However, [1,3] represents a binary tree with root value 1 and the root has a left child with value 3, which is NOT a binary search tree. The binary search tree should be [1,null,3].
Therefore, [1,3] should be changed to [1,null,3].
Also, the term "a height-balanced BSTs" is incorrect in grammar, which should be "height-balanced BSTs".

#### Expected behavior
In Example 2, the explanation should be: [1,null,3] and [3,1] are both height-balanced BSTs.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
