### ISSUE TITLE
Missing Test Case - 269. Alien Dictionary

### ISSUE THREAD

**Issue by LachezarTsK** [LeetCode-Feedback/LeetCode-Feedback#6539]
This is not actually a bug but it seems that the currently supported version of C++ on leetcode is not that much up to date.
It does not support string.starts_with(anotherString) and unordered_set.contains(...), so one has to write:

words[i - 1].substr(0, words[i].length())==words[i]   instead of   words[i - 1].starts_with(words[i])
and 
unordered_set.find(...)!=unordered_set.end(...)  instead of  unordered_set.contains(...)

**Comment by LC-Sue** [comment]
Hi @LachezarTsK,
Thank you for reaching out to us, please reach out to support@leetcode.com for feature requests!
