### ISSUE TITLE
1274. Number of Ships in a Rectangle – judge fails a test case

### ISSUE THREAD

**Issue by metricquant** [LeetCode-Feedback/LeetCode-Feedback#654]
#### Your LeetCode username
MetricQuant

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Judge always return an expected result of `1` when `topRight = bottomLeft`. An exemplary test case would be
```
[[1,1],[2,2],[3,3]]
[0,0]
[0,0]
```
The rectangle whose bottom left and top right corners are the origin `[0, 0]` does not contain any of the three given points.

#### Language used for code
C++

#### Expected behavior
When `topRight = bottomLeft`, judge should return `1` if and only if only of the single-point rectangle contains a ship.

**Comment by lc-ivan** [comment]
Hi @metricquant,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @metricquant ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
