### ISSUE TITLE
 2074. Reverse Nodes in Even Length Groups c++ simple solution

### ISSUE THREAD

**Issue by prakhar906** [LeetCode-Feedback/LeetCode-Feedback#6540]
class Solution {
public:
    
    ListNode *rev(ListNode *head)
    {
        ListNode *curr=head;
        ListNode *prev=NULL;
        ListNode *nex=NULL;
        
        while(curr)
        {
            nex = curr->next;
            curr->next = prev;
            prev = curr;
            curr=nex;
            
        }
        
        return prev;
    }
    
    int getLength(ListNode *head)
    {
        int c=0;
        while(head)
        {
            c++;
            head=head->next;
        }
        return c;
    }
    
    ListNode* reverseEvenLengthGroups(ListNode* head) {
        
    
        int len=getLength(head);
         int i=1;
    int l=0;
     ListNode *curr=head;
     ListNode *prev=NULL;
     ListNode *nex=NULL; 
         ListNode *last=NULL; 
     int j=0;
        int check=0;
        while(curr != NULL)
        {
            if(i%2 != 0)
            {
                int k=i;
                if(len-l < i)
                {
                    check=len-l;
                    last = curr;
                    curr=NULL;
                    break;
                }
                
                while(k>0 and curr)
                {
                    prev=curr;
                    curr=curr->next;
                    if(curr==NULL and k>0)
                        j=k;
                    l++;
                    k--;
                }
                i++;
            }
            else if(i%2==0){
                ListNode *temp=curr,*p=NULL;
                int x=i;
               
                 if(len-l < i)
                {
                    check=len-l;
                    last = curr;
                    curr=NULL;
                    break;
                }
                
                
                while(x>0 and temp)
                {
                    p=temp;
                    temp=temp->next;
                    x--;
                   l++;
                }
                if(x> 0)
                break;
                
                p->next=NULL;
                prev->next=rev(curr);
                curr->next=temp;
                curr=temp;
                i++;
            }
            
        }
        
        if(check %2==0){
        ListNode *q=head;
        while(q->next != last)
            q=q->next;
        
        q->next = rev(last);
            return head;
        
        }
        else
        return head;
    }
};

**Comment by LC-Sue** [comment]
Hi @prakhar906,
Thank you for reaching out to us, feel free to share your solution in the discuss section of the problem!
