### ISSUE TITLE
Missing Test Case 165. Compare Version Numbers

### ISSUE THREAD

**Issue by shamkin** [LeetCode-Feedback/LeetCode-Feedback#6541]
#### Your LeetCode username
user0277DX

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

By the task constraints, all the given revisions in version1 and version2 can be stored in a 32-bit integer. But current test coverage accepts solutions that work with 16-bit integer revisions.
So I propose a test case where 32-bit integer matters:
"1.2147483647" and  "1.2147483647" are equals.

#### Code you used for Submit/Run operation

```
class Solution {
    public int compareVersion(String version1, String version2) {
        String[] v1 = version1.split("\\.");
        String[] v2 = version2.split("\\.");
        
        for(int i = 0; i < v1.length && i < v2.length; i++) {
            short i1 = Short.parseShort(v1[i]);
            short i2 = Short.parseShort(v2[i]);
            if(i1 == i2) continue;
            if(i1 > i2) return 1;
            if(i1 < i2) return -1;
        }
        
        if(v1.length == v2.length) return 0;
        
        String[] remaining;
        int expectation = 0;
        if(v1.length > v2.length) {
            remaining = Arrays.copyOfRange(v1, v2.length, v1.length);
            expectation = 1;
        }
        else {
            remaining = Arrays.copyOfRange(v2, v1.length, v2.length);
            expectation = -1;
        }
        for (String s: remaining) {
            if(Short.parseShort(s) != 0) return expectation; 
        }
        
        return 0;
    }
}
```

#### Language used for code
Java

#### Expected behavior

The solution should fail because it doesn't support revision numbers larger than 32767. And it throws java.lang.NumberFormatException on correct versions v1 = "1.2147483647", v2 = "1.2147483647". But actually, it was accepted.

**Comment by LC-Sue** [comment]
Hi @shamkin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @shamkin 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
