### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by yashkumarkalyan** [LeetCode-Feedback/LeetCode-Feedback#6543]
#### Category of the bug
 - [ ] Solution 

#### Description of the bug
 "return pow(x,n);" is bypass solution, and problem is "medium"

#### Code you used for Submit/Run operation
```class Solution {
public:
    double myPow(double x, int n) {
        return pow(x,n);
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
See one should write complete code , not only just a bypass function.

**Comment by LC-Sue** [comment]
Hi @yashkumarkalyan,
Thank you for your time, our team has reviewed the report and unfortunately we cannot restrict all bypass solutions.
