### ISSUE TITLE
Missing Test Case - 165. Compare Version Numbers

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#6544]
#### Your LeetCode username

archit91

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case -

```
"2147483647"
"1"
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int compareVersion(string V1, string V2) {
        for(int i = 0, j = 0; i < size(V1) || j < size(V2); i++, j++) {
            int val1 = 0, val2 = 0;
            for(; i < size(V1) && V1[i] != '.'; i++) 
                val1 = val1 * 10 + V1[i] - '0';
            for(; j < size(V2) && V2[j] != '.'; j++)
                val2 = val2 * 10 + V2[j] - '0';
            if(val1 < val2) return -1;
            else if(val1 > val2) return 1;
        }
        return 0;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should be rejected as it fails on the above-mentioned valid test case.

**Comment by LC-Sue** [comment]
Hi @archit11111,
Thank you for your time, the code already fails from a previously added test case!
