### ISSUE TITLE
1016. Binary String With Substrings Representing 1 To N (Hint Update)

### ISSUE THREAD

**Issue by Sam-Si** [LeetCode-Feedback/LeetCode-Feedback#6545]
#### Your LeetCode username

sam_si

#### Category of the bug
- [ ] Question

#### Description of the bug

Need to update the hint 1 for this question.
The hint for this question seems to be outdated. It says that since n can be till 10**6 but now the question is that n is actually 10**9

#### Code you used for Submit/Run operation
```py
class Solution:
    def queryString(self, s: str, n: int) -> bool:
        
        seen = set(num for num in range(1,n+1))
        
        for start in range(len(s)):
            num = 0
            for bitlength in range(33):
                if start + bitlength >= len(s):
                    break
                num <<= 1
                num += int(s[start + bitlength])
                
                if num in seen:
                    seen.remove(num)
                    
        return not seen
```

#### Language used for code

python

#### Expected behavior

The expected behavior is that in hints it should be mentioned that it will need at max 32 bits to solve this problem.
Since n can go upto 10**9

#### Screenshots

![image](https://user-images.githubusercontent.com/13261099/155784260-f0df0d10-3b96-49d3-8c26-e7c3f446e4e6.png)

#### Additional context

Hint 1 needs to be updated to reflect that it's 32 bits, since it's 10**9 limit now.

**Comment by LC-Sue** [comment]
Hi @Sam-Si 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Sam-Si 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
