### ISSUE TITLE
Missing Test Case - 322. Coin Change

### ISSUE THREAD

**Issue by Karandeep1234** [LeetCode-Feedback/LeetCode-Feedback#6547]
#### Your LeetCode username

Karandeep1234

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gives WA on following testcase:
[2]
9999

#### Code you used for Submit/Run operation

```
class Solution {
    public int coinChange(int[] coins, int amount) {
        dp=new Integer[amount+1];
        int ans = solve(coins,amount);
        if(ans >= Integer.MAX_VALUE-4999) return -1;
        return ans;
    }
    Integer[] dp;
    public int solve(int[] coins, int amount){
        if(amount<0){
            return Integer.MAX_VALUE-4999;
        }else if(amount==0){
            return 0;
        }
        if(dp[amount]!=null) return dp[amount];
        int min=Integer.MAX_VALUE;
        for(int i=0;i<coins.length;i++){
            min=Math.min(min,1+solve(coins,amount-coins[i]));
        }
        return dp[amount]=min;
    }
}
```

#### Language used for code

Java

#### Expected behavior

It was expected not to be accepted.

**Comment by LC-Sue** [comment]
Hi @Karandeep1234,
Thank you for your time, the solution depends on a certain value and failing it with the current test case does not work because the user can change the value and make it accepted again. So we did not add the test case!
