### ISSUE TITLE
1222. 可以攻击国王的皇后

### ISSUE THREAD

**Issue by CLannadZSY** [LeetCode-Feedback/LeetCode-Feedback#655]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
示例3: 图中 `King` 的坐标是 [4, 3], 题目描述中的 king = [3, 4]
![棋盘图](https://assets.leetcode-cn.com/aliyun-lc-upload/uploads/2019/10/13/untitled-diagram-2.jpg)
`
输入：queens = [[5,6],[7,7],[2,1],[0,7],[1,6],[5,1],[3,7],[0,3],[4,0],[1,2],[6,3],[5,0],[0,4],[2,2],[1,1],[6,4],[5,4],[0,0],[2,6],[4,5],[5,2],[1,4],[7,5],[2,3],[0,5],[4,2],[1,0],[2,7],[0,1],[4,6],[6,1],[0,6],[4,3],[1,7]]
`
`
king = [3,4]
`
`
输出：[[2,3],[1,4],[1,6],[3,7],[4,3],[5,4],[4,5]]
`

**Comment by PsiACE** [comment]
非常感谢您的反馈，但值得注意的是，结合示例 1 位于 [2, 4] 的 Queen 不难看出，该坐标系与常规坐标不同，题目表述没有问题。再次感谢您的反馈，祝您刷题愉快。
