### ISSUE TITLE
Missing Test Case - 2188. Minimum Time to Finish the Race

### ISSUE THREAD

**Issue by Doctor-X** [LeetCode-Feedback/LeetCode-Feedback#6552]
#### Your LeetCode username

doppler

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

my code got accepted even though it failed a testcase that I created
Testcase - [[2,2]]
21
4

#### Code you used for Submit/Run operation

```
func minimumFinishTime(tires [][]int, changeTime int, numLaps int) int {
  n := len(tires)
  laps := make([]int, 20)
  for i:= 0;i<20;i++{
    laps[i] = 100000000000
  }
  for i:= 0;i<n;i++{
    j := 0
    cumm := 0
    cumm1 := tires[i][0]
    t:= tires[i][0]
    r := tires[i][1]
    if laps[j]>cumm1{
      laps[j] = cumm1
    }
    t*=r
    cumm += t-tires[i][0]
    cumm1 += t
    j++
    for cumm < changeTime {
      if laps[j]>cumm1{
        laps[j] = cumm1
      }
      t*=r
      cumm1 += t
      cumm += t-tires[i][0]
      j++
    }
  }
  l:= 20
  for i:= 0;i<20;i++{
    if laps[i] == 100000000000 {
      l = i
      break
    }
  }
  //fmt.Println(laps)
  dp := make([]int, numLaps)
  dp[0] = laps[0]
  for i:= 1;i<numLaps;i++{
    min := laps[0]+changeTime+dp[i-1]
    if i < l {
      if min > laps[i]{
          min = laps[i]
      }
    }
    for j:= 1;j<=l&&i-j>=0;j++{
      if min > dp[i-j]+ laps[j-1] + changeTime {
        min = dp[i-j]+laps[j-1] + changeTime
      }
    }
    dp[i] = min
  }
  //fmt.Println(dp)
  return dp[numLaps-1]
}
```

#### Language used for code

Golang

#### Expected behavior

my submission should have failed instead it got accepted
My code submission output = 33
correct output = 30

**Comment by LC-Sue** [comment]
Hi @Doctor-X 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Doctor-X 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
