### ISSUE TITLE
Missing Test Case - 680. Valid Palindrome II

### ISSUE THREAD

**Issue by ShivamMishra-github** [LeetCode-Feedback/LeetCode-Feedback#6553]
#### Your LeetCode username
username - Shivam212
email - shivam2002221@gmail.com

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ✓ ] Missing Test Cases 

#### Description of the bug
"abcdefgabgfecba" test case

#### Code you used for Submit/Run operation
 
      int start = 0 ;
      int end = s.length() - 1 ;
      
      while(start < end )
      {
        if(s.charAt(start) == s.charAt(end))
        {
          start++;
          end--;
        }
        else
        {
          return isPallindrome(s,start+1,end) || isPallindrome(s,start,end-1);
        }
      }
        return true;
    }
  
  public static boolean isPallindrome(String s , int start , int end )
  {
    if(s.charAt(start) == s.charAt(end))
    {
      start++;
      end--;
    }
    else
    {
      return false;
    }
    return true;
  }

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @ShivamMishra-github,
Thank you for reaching out to us, could you re-enter the code used for submission and provide the language you used for submission?
