### ISSUE TITLE
Incorrect Code Block Comment - 374. Guess Number Higher or Lower

### ISSUE THREAD

**Issue by jaypatel512** [LeetCode-Feedback/LeetCode-Feedback#6554]
#### Your LeetCode username
jaypatel512

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
As described in the explanation in explore section, it says:

```
You call a pre-defined API int guess(int num), which returns three possible results:

-1: Your guess is higher than the number I picked (i.e. num > pick).
1: Your guess is lower than the number I picked (i.e. num < pick).
0: your guess is equal to the number I picked (i.e. num == pick).
```
However, in the code block comment below, it says:
```
/** 
 * Forward declaration of guess API.
 * @param  num   your guess
 * @return 	     -1 if num is lower than the guess number
 *			      1 if num is higher than the guess number
 *               otherwise return 0
 * int guess(int num);
 */
```

Do note that the return value is opposite. Code block mentions, -1 if num (your guess) is lower than the guess number (number I picked).

#### Code you used for Submit/Run operation
```java
/** 
 * Forward declaration of guess API.
 * @param  num   your guess
 * @return 	     -1 if num is lower than the guess number
 *			      1 if num is higher than the guess number
 *               otherwise return 0
 * int guess(int num);
 */

public class Solution extends GuessGame {
    public int guessNumber(int n) {
       int min = 0, max = n;
        
        while (min <= max) {
            int mid = min + (max - min)/2;
            int guess = guess(mid);
            System.out.format("\nMin: %d, Mid:%d, Max:%d, Guess: %d", min, mid, max, guess);
            if (guess == 0) {
                return mid;
            }
            if (guess < 0) {
                // Guessed too low. Need to increase number
                min = mid + 1;
            } else {
                // Guessed too high. Need to reduce guess
                max = mid -1;
            }
        }
        return -1;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The code block comment in the code editor is incorrect. This is causing confusing and incorrect submissions, even though the logic is correct.

#### Screenshots

![screencapture-leetcode-explore-learn-card-binary-search-125-template-i-951-2022-02-27-03_14_39](https://user-images.githubusercontent.com/1309895/155876241-f34a62fe-9738-4759-907f-174a7273a05d.png)

**Comment by LC-Sue** [comment]
Hi @jaypatel512 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
