### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by Kaptan6000** [LeetCode-Feedback/LeetCode-Feedback#6555]
#### Your LeetCode username
 Kaptan_singh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [  ] Missing Test Cases 

#### Description of the bug 
it is giving 2.00000 instead of giving 2.50000.

#### Code you used for Submit/Run operation

```
// Median of Two Sorted Arrays
class Solution(object):
    def findMedianSortedArrays(self, nums1, nums2):
        mer=nums1+nums2
        mer.sort()
        n=len(mer)
        for i in range(0,n):
            if n%2 != 0:
                if i==math.floor(n/2):
                    return (mer[i])
            else:
                if i==n/2:
                    return ((mer[i]+mer[i-1])/2)
```

#### Language used for code
python

#### Expected behavior
it is giving 2.00000 instead of giving 2.50000

**Comment by LC-Sue** [comment]
Hi @Kaptan6000,
Thank you for reaching out to us, our judger appears to be running correctly. Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
