### ISSUE TITLE
Poorly written and ambiguous: 662. Maximum Width of Binary Tree

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#6556]
#### Your LeetCode username

Leaderboard

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question is ambiguous. It is not clear that your definition of the tree includes the children of nodes that are themselves null. This can cause confusion, because the provided test cases do not show this distinction properly.

Consider the code I wrote (see below). It failed at this test case:

```
[1,3,2,5,null,null,9,6,null,null,7]
```

My implementation assumed that we only consider null nodes that are children of non-null nodes, which led my code to give an answer 6, rather than the expected 8. Nowhere in the question is this distinction noted - all it says is that "... where the null nodes between the end-nodes are also counted into the length calculation." without explicitly saying what "end-nodes" mean (it would be reasonable to assume that these nodes should not be null when that wasn't actually the case).
#### Code you used for Submit/Run operation

```java
class Solution {
    HashMap<Integer, ArrayList<Integer>> hm = new HashMap<>();
    public void myDFS(TreeNode root, int depth, int ptr)
    {
     ArrayList<Integer> arr = hm.get(depth);
    if (arr == null)
        arr = new ArrayList<>();
        arr.add(ptr);
        hm.put(depth, arr);
        if (root.left != null)
            myDFS(root.left, depth + 1, ptr - 1);
        if (root.right != null)
            myDFS(root.right, depth + 1, ptr + 1);
    }
    public int widthOfBinaryTree(TreeNode root) {
     myDFS(root, 0, 0);
    int ans = 0;
        for (int i: hm.keySet())
        {
            ArrayList<Integer> arr = hm.get(i);
            if (arr.size() > 1)
            {
                Collections.sort(arr);
                ans = Math.max(ans, arr.get(arr.size() - 1) - arr.get(0));
            }
        }
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The question and/or the accompanying test cases should be rewritten to make this distinction clear and less ambiguous.

#### Additional context

Also described in these Discuss threads:
* https://leetcode.com/problems/maximum-width-of-binary-tree/discuss/600435/This-test-case-really-confused-me-(1234nullnull5null67null%3A-6).
* https://leetcode.com/problems/maximum-width-of-binary-tree/discuss/131524/Someone-explaint-1111nullnull11nullnull1-test-case

**Comment by LC-Sue** [comment]
Hi @Leader-board 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Leader-board 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
