### ISSUE TITLE
Incorrect description - 626. Exchange Seats

### ISSUE THREAD

**Issue by dreamw4lker** [LeetCode-Feedback/LeetCode-Feedback#6557]
#### Your LeetCode username
dreamwalker7

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Description of `Seat` table is now displayed as follows:

```
+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| id          | int     |
| name        | varchar |
+-------------+---------+
```

But there's no **name** column. Valid column list is: **id**, **student**.

**Comment by LC-Sue** [comment]
Hi @dreamw4lker,
Thank you for reaching out the us, the key column appear to be correct, please refer to the screenshot below. In the example it's id, student where it indicates the name and ID of a student. 

![image](https://user-images.githubusercontent.com/92285126/157451216-d7b5acf3-a115-404a-98c6-fd1f805de8d7.png)
