### ISSUE TITLE
Missing Test Case - 1215. Stepping Numbers

### ISSUE THREAD

**Issue by gahfy** [LeetCode-Feedback/LeetCode-Feedback#6558]
#### Your LeetCode username
gahfy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I found a missing test case in that one. The code provided will pass the validation, but will not pass the following test :

* Any test for which `high < 9`

For example, with `low = 0` && `high = 3`, the provided code will return:

`[0,1,2,3,4,5,6,7,8,9]`

which is not the correct answer.

#### Code you used for Submit/Run operation

```java
class Solution {
    public List<Integer> countSteppingNumbers(int low, int high) {
        List<Integer> result = new ArrayList();
        if(low == 0) {
            result.add(0);
        }
        // The next line is considered line number 1 in the below notes
        List<Integer> nexts = Arrays.asList(1,2,3,4,5,6,7,8,9);
        dfs(low, high, result, nexts);
        
        return result;
    }
    
    public void dfs(int low, int high, List<Integer> result, List<Integer> currentNumbers) {
        List<Integer> nextNumbers = new ArrayList();
        for(int i=0; i<currentNumbers.size(); i++) {
            // The next line is considered line number 2 in the below notes
            if(currentNumbers.get(i) >= low) {
                result.add(currentNumbers.get(i));
            }
            if(currentNumbers.get(i) <= high / 10) {
                int suffixBefore = suffix(currentNumbers.get(i), true);
                int suffixAfter = suffix(currentNumbers.get(i), false);
                // The next line is considered line number 3 in the below notes
                if(suffixBefore != -1 && suffixBefore <= high) {
                    nextNumbers.add(suffixBefore);
                }
                // The next line is considered line number 4 in the below notes
                if(suffixAfter != -1 && suffixAfter <= high) {
                    nextNumbers.add(suffixAfter);
                }
            }
        }
        
        if(nextNumbers.size() > 0) {
            dfs(low, high, result, nextNumbers);
        }
    }
    
    public int suffix(int x, boolean previous) {
        if(x % 10 == 0 && previous) { return -1; }
        if(x % 10 == 9 && !previous) { return -1; }
        return x*10 + (x % 10 + (previous ? -1 : 1));
    }
}
```

**Justification (meaning it's not just a code to break the test cases)**
Actually, I was first thinking no need to test on line 2 for `currentNumbers.get(i) <= high` because we are already testing it on line 3 and 4. Actually, I missed line number 1.

#### Language used for code
Java

#### Expected behavior
Having a test with `high < 9`

**Comment by LC-Sue** [comment]
Hi @gahfy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @gahfy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
