### ISSUE TITLE
[Top Interview Questions] Strings: Reverse Integer TestCase

### ISSUE THREAD

**Issue by hochan222** [LeetCode-Feedback/LeetCode-Feedback#656]
#### Your LeetCode username

hochan049

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [o] Test Case

#### Description of the bug

Strings: Reverse Integer

It was not considered when it was -0.

#### Code you used for Submit/Run operation

```
function reverse(x: number): number {
  let sign: number = x >= 0 ? 1 : -1;
  let result: number = sign * parseInt(x.toString().split("").reverse().join(""));
  return Math.pow(-2, 31) <= result && result <= Math.pow(2, 31) - 1 ? result : 0
}

```
let sign: number = x > 0 ? 1 : -1;
If this code here, -0 is printed.

#### Expected behavior

0

not -0

#### Additional context

so we need to add
reverse(0) => 0

**Comment by lc-christina** [comment]
Hi @hochan222 ,
Thanks for reaching out to us. I got 0 when using your code to test testcase -0. If you are not getting the same result, can you please provide the submission link and the screenshot? Or please kindly let me know if I misunderstood what you meant.
<img width="1671" alt="Screen Shot 2020-07-20 at 7 15 05 PM" src="https://user-images.githubusercontent.com/67175512/88005116-7479f200-cabd-11ea-9cd5-9a875f80f5d9.png">

**Comment by hochan222** [comment]
It was my mistake! As I see now, in fact, -0 and 0 are the same, but I think -0 is wrong.  
Hahaha... Sorry for the loss of your precious time and thank you for the reply.  

![image](https://user-images.githubusercontent.com/22424891/88130892-a81c5f80-cc16-11ea-9e46-fad62eb4e939.png)

![image](https://user-images.githubusercontent.com/22424891/88130929-b66a7b80-cc16-11ea-94a1-0a877ede41d2.png)

**Comment by lc-pam** [comment]
Hi @hochan222 
Thanks for letting me know! I'm glad the issue is resolved. Have a nice day :)
