### ISSUE TITLE
[10000,10000000] 10000000 Missing Test Case - 2187. Minimum Time to Complete Trips

### ISSUE THREAD

**Issue by Hirak-Mondal** [LeetCode-Feedback/LeetCode-Feedback#6562]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the solution that can get accepted but fails on the test case? Here I provide a solution, not sure whether it is sufficient enough.

The following code is in C++.

```C++
class Solution {
public:
    long long minimumTime(vector<int>& time, int t) {
        if (time[0] == 10000 && time[1] == 10000000 && t == 10000000) {
            return 0;
        }
        long long ret = 1e15;
        long long l = 1, r = 1e14;
        while (l <= r) {
            long long mid = (l + r) / 2;
            long long now = 0;
            for (int i = 0; i < time.size(); i++) {
                now += mid / time[i];
                if (now >= t) {
                    break;
                }
            }
            if (now >= t) {
                ret = mid;
                r = mid - 1;
            } else {
                l = mid + 1;
            }
        }
        return ret;
    }
};
```

**Comment by Hirak-Mondal** [comment]
99900100000 is the actual solution for the test case
[10000,10000000]
10000000
The first time I wrote the solution, the solution was accepted in the
contest.
But then I tried this test case, my code's output is different from the
expected output, which is 99900100000.
But still, my first code was accepted.

**Comment by stormsunshine** [comment]
By asking "solution", I am asking the code you submitted, not the answer.

Only when the code is accepted, the issue will be considered.

**Comment by LC-Sue** [comment]
Hi @Hirak-Mondal 
Thank you for reaching out to us, please provide the code you used for submission. After more information is provided, I will reopen this ticket. Thank you for your time.
