### ISSUE TITLE
typo of explore learn card of hash table

### ISSUE THREAD

**Issue by nc3816** [LeetCode-Feedback/LeetCode-Feedback#6563]
https://leetcode.com/explore/learn/card/hash-table/183/combination-with-other-algorithms/1130/
line 17 has a typo: System.out.println("The size of has set is: " + hashSet.size());    
should be              System.out.println("The size of hash set is: " + hashSet.size());

**Comment by LC-Sue** [comment]
Hi @nc3816 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
