### ISSUE TITLE
Test Case Checker Incorrect - 165. Compare Version Numbers

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6565]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [165. Compare Version Numbers](https://leetcode.com/problems/compare-version-numbers), if a custom test case is used, the test case checker only checks the value of `version1` and does not check the value of `version2`.

Consider the following two test cases.
The first test case is as follows.
```
"1.2147483648"
"1.2147483647"
```
When running the test case, the Run Code Result is Invalid Testcase, with the following message. This is correct, since the first parameter contains 2147483648 which is out of the range of a 32-bit signed integer.
```
'v1' must consist of values from -2147483648 to 2147483647 only
```
The second test case is as follows, with the values of the two parameters from the test case above swapped.
```
"1.2147483647"
"1.2147483648"
```
When running the test case, the test case checker does not consider it as an invalid test case, and the test case is executed like all valid test cases. Obviously, the test case checker does not check whether the second parameter is valid.

Therefore, the test case checker should be updated to make sure that both parameters are legal.

#### Code you used for Submit/Run operation
I am not providing the code here. Please use any code (in any language) that can get accepted to run the two test cases above.

#### Expected behavior
Change the behavior of the test case checker so that both parameters should be checked.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
