### ISSUE TITLE
Poor Description - 228. Summary Ranges

### ISSUE THREAD

**Issue by james-jasvin** [LeetCode-Feedback/LeetCode-Feedback#6566]
#### Your LeetCode username
rgg1999

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

It is very difficult to understand what the question is asking for.
There should be an explanation or an example describing what is a range.
For the example, [0, 1, 2, 4, 5, 7]
A sample explanation can be as follows,
0, 1, 2 are consecutive integers and they appear in the array so they form a range "0 -> 2"
4 is not consecutive to 2, so we have to start a new range
4, 5 are consecutive integers so new range "4->5"
7 is also not consecutive and its the last element of the array so our new range is "7". This is how we get the final output as,
"0->2", "4->5", "7"

I had to refer to the discussion section and only after reading the comments I understood what this question is talking about.

**Comment by LC-Sue** [comment]
Hi @james-jasvin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @james-jasvin 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
