### ISSUE TITLE
Missing Test Case - 485. Max Consecutive Ones

### ISSUE THREAD

**Issue by Younisprogramming** [LeetCode-Feedback/LeetCode-Feedback#6568]
#### Your LeetCode username

younistaher
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
Question

#### Description of the bug

your question in Array(findMaxConsecutiveOnes), I am sure that my code is correct but after submit , it tell me that your code is incorrect , please view my code and if its incorrect show me the better Solution . Thank you

#### Code you used for Submit/Run operation

```

// Two Sum
class Solution {
    public int findMaxConsecutiveOnes(int[] nums) {
        int s = 0;
        int p = 0;
        int k = 0;
        for (int num : nums) {
            if (num == 1){
                s++;
                p = s;
            }
            else {
                k = s;
                s = 0;
            }
            if (k>p)  p = k;
        }
        return p;
    }
}
```

#### Language used for code

Java

#### Expected behavior

my code findMaxConsecutiveOnes . when you input {1,1,1,1,1,....,1} (2840)
the output must be 2840 not 2317!

#### Screenshots

![Screenshot (23)](https://user-images.githubusercontent.com/100076892/155981730-5739570a-ff4f-4b43-b53d-d07c991125fe.png)

**Comment by LC-Sue** [comment]
Hi @Younisprogramming,
Thank you for reaching out to us, our judger appears to be running correctly. Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
