### ISSUE TITLE
Missing Test Case - 796. Rotate String

### ISSUE THREAD

**Issue by abhinandanmishra1** [LeetCode-Feedback/LeetCode-Feedback#6569]
#### Your LeetCode username
abhinandan_mishra_1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Problem has some missing test cases because it is giving wrong answer on some test cases with my solution but my solution got accepted.

#### Code you used for Submit/Run operation

```
// Rotate String
class Solution {
public:
    bool rotateString(string s1, string s2) {
        s2+=s2;
        int m=s1.length();
        int n=s2.length();  
        if(n<m) return false; 
        if(n==2 and m==2) return false;
        
        vector<int> store(m,0);
        int i=0,j=1;
        while(j<m){
            if(s1[i]==s1[j]){
                store[j]=i+1;
                i++;
                j++;
            }else{
                if(i>0){
                    i=store[i-1];
                }else{
                    j++;
                }
            }
        }
        
        i=0,j=0;
        while(i<n){
            while(j<m){
                if(s2[i]==s1[j]){
                    i++;
                    j++;
                }else{
                    break;
                }
            }
            if(j==m){
                return true;
            }
            if(j>0){
                j=store[j-1];
            }else{
                i++;
            }
        }
        return false; 
    }
};
```

#### Language used for code
C++

#### Expected behavior
Some test cases are given below
**Testcase 1**
Input : 
```
"abab"
"ab"
```
Output:
``` true ```

Expected Output:
``` false ```

**Testcase 2**
Input : 
```
"aaaa"
"aa"
```
Output:
``` true ```

Expected Output:
``` false ```

#### Screenshots
**Screenshot 1 (Wrong Output for given testcase)**
![Screenshot (1)](https://user-images.githubusercontent.com/64205626/156028942-4199fccf-6d3d-4995-925b-c027ca721807.png)

**Screenshot 2  (Wrong Output for given testcase)**
![Screenshot (2)](https://user-images.githubusercontent.com/64205626/156028964-529a80b0-47bc-4a3b-b0b8-d671b86a8753.png)

**Screenshot 3 (But my solution got accepted)**
![Screenshot (3)](https://user-images.githubusercontent.com/64205626/156028984-3d2f69da-37d3-4f9b-aa16-e7623683d103.png)

#### Additional context
- Add more test cases in which the first string is double of the second string.
- For example test cases like -
   - ```  s1- "aaaa" , s2 - "aa" ```
   - ```  s1- "abababab" , s2 - "abab" ```
   - ```  s1- "aaabaaab" , s2 - "aaab" ```
- All these test cases should return false.

**Comment by LC-Sue** [comment]
Hi @abhinandanmishra1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @abhinandanmishra1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
