### ISSUE TITLE
50.Pow(x,n) C# Precision Issue

### ISSUE THREAD

**Issue by TheSocraticParadox** [LeetCode-Feedback/LeetCode-Feedback#657]
#### Your LeetCode username
jakobwwilson

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
I was attempting problem 50 "Pow(x,n)" (https://leetcode.com/problems/powx-n/) and kept getting precision issues with my C# submissions. Every time I run in C#, the precision of my answer is off, but the same code works fine in other languages(such as C). I verified the issue against other people's old C# solutions which don't work anymore. I even tried using the built in Math.Pow() function and got the same issue.

#### Code you used for Submit/Run operation
Input
```
2.00000
100
```

Non-working C# solution(you can just use Math.Pow() as well)
```
// Pow(x,n)
public class Solution {
 
    private double getPower(double bse, int exp){
            if(exp == 1)
                return bse;
            if(exp == 0)
                return 1;
            double val = getPower(bse, exp/2);
            if(exp%2 == 0)
                return val*val;
            else
                return val*val*bse;
    }
    
    public double MyPow(double bse, int exp){
        if(exp < 0)
            return 1/(getPower(bse, -(++exp)) * bse);
        return getPower(bse, exp);

    }
}
```

Working C solution
```
// Pow(x,n)
double getPower(double bse, int exp){
        if(exp == 1)
            return bse;
        if(exp == 0)
            return 1;
        double val = getPower(bse, exp/2);
        if(exp%2 == 0)
            return val*val;
        else
            return val*val*bse;
}

double myPow(double bse, int exp){
    if(exp < 0)
        return 1/(getPower(bse, -(++exp)) * bse);
    return getPower(bse, exp);
    
}
```

#### Language used for code
C#

#### Expected behavior
When submitting in C#, the output should have a higher precision than the system is currently allowing:
Output: 
```
1267650600228230000000000000000.00000
```
Expected: 
```
1267650600228229401496703205376.00000
```

**Comment by lc-christina** [comment]
Hi @TheSocraticParadox 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @TheSocraticParadox 
Thank you for your time. This is an issue with C# with very large values, and we added a constraint accordingly to limit the answer to small values only. We appreciate your support!

**Comment by TheSocraticParadox** [comment]
Thanks @lc-pam. I heard there was a point reward for reporting issues?

**Comment by lc-pam** [comment]
Hi @TheSocraticParadox ,
I'm sorry that constraint issue is not eligible for LeetCoin reward. We only give LeetCoin reward for report like missing test case and incorrect official solution. Thank you for your support!
