### ISSUE TITLE
Missing Test Case - 2187. Minimum Time to Complete Trips

### ISSUE THREAD

**Issue by nottheswimmer** [LeetCode-Feedback/LeetCode-Feedback#6570]
#### Your LeetCode username
NotTheSwimmer

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The lower bound is not properly tested, resulting in code passing that would fail with an additional test case such as:
```
[1, 10000000]
1
```

The passing code below, which might naturally arise from trying to work out a lower bound for i but making a mistake, gives an output of 2500000 for this case when the expected output is 1.

#### Code you used for Submit/Run operation

```py
class Solution:
    def minimumTime(self, time: List[int], totalTrips: int) -> int:
        class Helper:
            def __getitem__(self, i):
                n = 0
                for t in time:
                    n += i // t
                return n
                
        X = sum(time)
        n = len(time)
        lo = X//(totalTrips+n+1)
        hi = totalTrips*min(time)
                
        return bisect_left(Helper(), totalTrips, lo, hi)
```

#### Language used for code
Python

#### Expected behavior
The submitted code would fail due to the above tet case.

#### Screenshots

![image](https://user-images.githubusercontent.com/29849378/156031098-c4f08e65-7643-4f35-a43e-eb6d5f03d0f6.png)

###### Passing submission link
https://leetcode.com/submissions/detail/650695240/

###### Bad math used to arrive at the lower bound.

![image](https://user-images.githubusercontent.com/29849378/156030994-826d815b-1b33-4933-a317-484b87095658.png)

**Comment by LC-Sue** [comment]
Hi @nottheswimmer 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @nottheswimmer 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
