### ISSUE TITLE
Missing Test Case - 228. Summary Ranges

### ISSUE THREAD

**Issue by SriramGDev** [LeetCode-Feedback/LeetCode-Feedback#6571]
#### Your LeetCode username

SriramG

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In my solution, I alter the original list by appending ```INT_MAX```. My solution passes, but would fail if the following test case were included:

```
[2147483645,2147483646]
```

#### Code you used for Submit/Run operation

```C++
// Summary Ranges
class Solution {
public:
    vector<string> summaryRanges(vector<int>& nums) {
        vector<string> ans;
        if (nums.size() == 0) return ans;
        int start = nums[0];
        int end = nums[0];
        nums.push_back(INT_MAX);
        for (int i = 1; i < nums.size(); i++) {
            if ((long)nums[i] != (long)nums[i-1]+1) {
                if (start != end) ans.push_back(to_string(start)+"->"+to_string(end));
                else ans.push_back(to_string(start));
                start = nums[i];
            }
            end = nums[i];
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

On the above test case, my code returns the empty list ```[]``` when in fact the correct answer is ```["2147483645->2147483646"]```.  I have included a second example demonstrating the same issue in the screenshot below.

#### Screenshots

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/22031526/156051237-a62e5c3f-cbee-4eb4-b2e2-2a37c80a8f25.png">

###### Passing submission link

https://leetcode.com/submissions/detail/650764662/

###### Explanation of bug

This bug occurs because in my code, I append the number ```2147483647``` to the input array, then process it. At the final step in my loop, my code encounters ```2147483647```, which in conjunction with the rest of the array, constitutes a continuous range of integers. Thus, it continues on, adding nothing to the answer.

**Comment by LC-Sue** [comment]
Hi @SriramGDev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @SriramGDev 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
