### ISSUE TITLE
Missing Test Case - 66. Plus One 

### ISSUE THREAD

**Issue by yashchutake** [LeetCode-Feedback/LeetCode-Feedback#6575]
#### Your LeetCode @yash_chutake

It does not content the test case to check whether more one no given in array which is greater than 9 what will be possibility
ex= if int [] digits={9,9}
After increment
it should gives the 100 right...!

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

It does not content the test case to check whether more one no given in array which is greater than 9 what will be possibility
ex= if int [] digits={9,9}
After increment
it should gives the 100 right...!

**Comment by stormsunshine** [comment]
The test case [9,9] does exist and the correct answer is [1,0,0]. Is there any problem?

**Comment by LC-Sue** [comment]
Hi @yashchutake,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts, please feel free to reach out again if you have any other questions!
