### ISSUE TITLE
4. Median of Two Sorted Arrays - javascript crash

### ISSUE THREAD

**Issue by cathysarisky** [LeetCode-Feedback/LeetCode-Feedback#6579]
#### Your LeetCode username
catsarisky

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Although the code below works fine for individual testcases, it throws the error below when I try to submit it.  That appears to happen immediately (0/n test cases accepted, first simple testcase shown as 'last tested'), not in what are probably some more complicated and longer testcases later in the set of testcases.

#### Code you used for Submit/Run operation
```
var findMedianSortedArrays = function(nums1, nums2) {
    let finalArray = []
    while ( nums1.length > 0 || nums2.length > 0) {
        if (nums1[0] <= nums2[0] && nums1.length > 0 ) {
            finalArray.push(nums1.shift())           
        } else {
            finalArray.push(nums2.shift())
     }
    } 
    return (finalArray[Math.floor((finalArray.length-1)/2)] + finalArray[Math.ceil((finalArray.length-1)/2)])/2
};
```

#### Language used for code
Javascript

#### Expected behavior
Code should be accepted or give an indication of wrong answer or timeout or do something informative.

#### Screenshots
![image](https://user-images.githubusercontent.com/42299862/156249918-e83e9706-317d-4613-823e-81f54157be32.png)

#### Additional context
Other javascript solutions submit correctly.  I also waited a while and tried submitting again, in case it was a transient failure. No change.

**Comment by LC-Sue** [comment]
Hi @cathysarisky,
Thank you for reaching out to us! The code you provided returns runtime error, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
