### ISSUE TITLE
The code gives the correct output on the failing test case when i tried running it but on submitting the solution the same test case fails. is this a bug?

### ISSUE THREAD

**Issue by akashgkrishnan** [LeetCode-Feedback/LeetCode-Feedback#658]
#### Your LeetCode username

akashgkrishnan

#### Category of the bug
- [ ] Question
145. Binary Tree Postorder Traversal HARD

- [ ] Solution`

- [ ] Language
python3

#### Description of the bug
One of the test cases failed on submission.
on testing via the custom test case input for the same test case the code was shown to pass the same test case

#### Code you used for Submit/Run operation

```
    def postorderTraversal(self, node: TreeNode, array = []) -> List[int]:
        if node is not None:
            self.postorderTraversal(node.left, array)
            self.postorderTraversal(node.right, array)
            array.append(node.val)
        ans = array
        array = []
        return ans
```

#### Language used for code
Python 3

#### Expected behavior

if the code passes the test case on being run from the custom test case. it should also pass when the user submits the same solution.

#### Screenshots

[issue ImageURL](https://assets.leetcode.com/users/images/938698f1-072f-4e6e-8314-89bf6a27af84_1595038004.8773575.png)

**Comment by lc-christina** [comment]
Hi @akashgkrishnan 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
