### ISSUE TITLE
Wrong Answer - 392. Is Subsequence

### ISSUE THREAD

**Issue by Aratrik-02** [LeetCode-Feedback/LeetCode-Feedback#6580]
#### Category of the bug

- [ ] Solution

#### Description of the bug

When I am submitting the code its showing wrong answer and displaying the test case for which it is wrong.
I used the same test case to run code there it is showing my answer is correct which I know it is.
Please fix this issue

#### Code you used for Submit/Run operation

```
//392. Is Subsequence
class Solution {
public:
    bool isSubsequence(string s, string t) {
        int c=0;
        for(int i=0;i<t.size();i++){
            for(static int j=0;j<t.size();j++){
                if(s[i]==t[j]){c++;break;}
            }
        }
        if(c==s.size())return true;
        else return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior

I expected the code to get accepted cause I felt the solution I provided was correct according to me and even in testcases I checked it was correct but while submitting it shows wrong answer

#### Screenshots

![image](https://user-images.githubusercontent.com/75318952/156280455-880a2869-3b7d-40c0-a683-cbc510b04678.png)

**Comment by LC-Sue** [comment]
Hi @Aratrik-02 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by Aratrik-02** [comment]
Thanks I understood the problem
