### ISSUE TITLE
Solution - 1281. Subtract the Product and Sum of Digits of an Integer

### ISSUE THREAD

**Issue by lapimpale** [LeetCode-Feedback/LeetCode-Feedback#6581]
#### Your LeetCode username
Lapimpale

#### Category of the bug
- [ ] Solution

class Solution {
    public int subtractProductAndSum(int n) {
        int sum = 0, product = 1;
        while (n > 0) {
            sum += n % 10;
            product *= n % 10;
            n /= 10;
        }
        return product - sum;
    }
}

**Comment by LC-Sue** [comment]
Hi @lapimpale,
Thank you for reaching out to us, please feel free to share your solution in the discuss section of the problem!
