### ISSUE TITLE
Typo in problem number 87

### ISSUE THREAD

**Issue by VaibhaveS** [LeetCode-Feedback/LeetCode-Feedback#6585]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Just a typo for the word random

#### Screenshots

![image](https://user-images.githubusercontent.com/56480355/156373721-6e79446a-889f-45e9-bb1e-74bda3515b82.png)

**Comment by LC-Sue** [comment]
Hi @VaibhaveS 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @VaibhaveS 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
