### ISSUE TITLE
Small problem with solution 69

### ISSUE THREAD

**Issue by HamsterCoder** [LeetCode-Feedback/LeetCode-Feedback#6587]
#### Your LeetCode username
HamsterCoder

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/sqrtx/solution/

In the solution for problem 69  Approach 2: Binary Search it says quote `For x≥2 the square root is always smaller than x/2 and larger than 0 :` which is wrong. 4 square root is 2 and it equals 4 / 2 = 2.

`(x/2)^2 v x  <=>  (x^2) / 4 v x <=>  x ^ 2 v 4x`

If x > 0 we can divide by x 

`x v 4` and from this it follow that for each x > 4 (x / 2) ^ 2 is greater than x;

**Comment by LC-Sue** [comment]
Hi @HamsterCoder 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
