### ISSUE TITLE
Missing Testcase

### ISSUE THREAD

**Issue by satosansato3** [LeetCode-Feedback/LeetCode-Feedback#659]
#### Your LeetCode username

jicoradio

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Code got accepted which has output different than expected.

#### Code you used for Submit/Run operation

```
// 28. Implement strStr()
public class Solution {
    public int StrStr(string haystack, string needle) {
        if(string.IsNullOrEmpty(needle)) return 0;
        
        var mapper = new int[needle.Length];
        
        var counter = 0;
        for(var i = 1;i < needle.Length;i++){
            mapper[i] = counter;
            if(needle[i] == needle[counter])
                counter++;
            else if(counter > 0){
                if(needle[i] != needle[counter - 1]){
                    counter = 0;
                }
            }
            else
                counter = 0;
        }
        
        counter = 0;
        for(var i = 0;i < haystack.Length; i++){
            if(haystack[i] == needle[counter]){
                counter++;
            }else if(mapper[counter] > 0){
                i--;
                counter = mapper[counter];
            }else if(counter > 0){
                i--;
                counter = 0;
            }
            
            if(counter == needle.Length)
                return i - needle.Length + 1;
        }
        return -1;
    }
}
```

#### Language used for code

C#

#### Expected behavior

- Test case
haystack: "adcadcaddcadde"
needle: "adcadde"

- Expected
-1

- Output
7

#### Screenshots

![image](https://user-images.githubusercontent.com/47944669/87854198-365cc100-c94b-11ea-8389-ee4b185d79a0.png)

**Comment by lc-christina** [comment]
Hi @satosansato3 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @satosansato3 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
