### ISSUE TITLE
Problem 1770 - Solution from DP card too slow

### ISSUE THREAD

**Issue by cemde** [LeetCode-Feedback/LeetCode-Feedback#6594]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution top-down code in the [Dynamic Programming card](https://leetcode.com/explore/learn/card/dynamic-programming/631/strategy-for-solving-dp-problems/4100/) does not finish in time.

#### Code you used for Submit/Run operation

```python
class Solution:
    def maximumScore(self, nums: List[int], multipliers: List[int]) -> int:
        # lru_cache from functools automatically memoizes the function
        @lru_cache(2000)
        def dp(i, left):
            # Base case
            if i == m:
                return 0

            mult = multipliers[i]
            right = n - 1 - (i - left)
            
            # Recurrence relation
            return max(mult * nums[left] + dp(i + 1, left + 1), 
                       mult * nums[right] + dp(i + 1, left))
                       
        n, m = len(nums), len(multipliers)
        return dp(0, 0)
```

#### Language used for code
Python

#### Expected behavior
Finish without `Time Limit Exceeded`

**Comment by LC-Sue** [comment]
Hi @cemde 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
