### ISSUE TITLE
Missing TestCase

### ISSUE THREAD

**Issue by dubeyx** [LeetCode-Feedback/LeetCode-Feedback#6600]
#### Category of the bug
- [413. Arithmetic Slices ] Question
- [6] Solution
- [ Java] Language
- [nums = [10,9,8,7,6] ] Missing Test Cases 

#### Description of the bug

There is no output corresponding to this input by this question

#### Code you used for Submit/Run operation

```
class Solution {
    public int numberOfArithmeticSlices(int[] nums) {
        if(nums.length<=2) return 0;
       int ans=0;
        int t=nums[1]-nums[0];
        int f=2;
        for(int i=2;i<nums.length;i++)
        {
            if(nums[i]-nums[i-1]==t) {f=f+1; ans=ans+1+f-3;}
            else{f=2 ; t=nums[i]-nums[i-1];}
        }
        
            return ans;
    }
}
```

#### Language used for code

Java

#### Screenshots
![image](https://user-images.githubusercontent.com/94775233/156555211-0a0917f8-10fa-4892-ad41-1ff3bf85b06c.png)

**Comment by LC-Sue** [comment]
Hi @dubeyx,
Thank you for reaching out to us, the code and the test case you provided are accepted. Please refer to the screenshot below! 
![image](https://user-images.githubusercontent.com/92285126/157522293-36f41317-3d2b-4375-bde0-f1234cd55241.png)
