### ISSUE TITLE
Missing Test Case - 284. Peeking Iterator

### ISSUE THREAD

**Issue by mamtak9** [LeetCode-Feedback/LeetCode-Feedback#6603]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What do you want to mention in this issue?

**Comment by LC-Sue** [comment]
Hi @mamtak9 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
