### ISSUE TITLE
Code Runtime bug on submission. 

### ISSUE THREAD

**Issue by CSEKU160212** [LeetCode-Feedback/LeetCode-Feedback#6604]
#### Your LeetCode username
cseku160212

#### Category of the bug
- [ ] Bug Report

#### Description of the bug
I have submitted a solution a few times. 
Sometimes the result shows "Accepted" and sometimes "Time Limit Exceeded".  
I was sure that It will get "TLE" and the result (Accepted) shocked me.

###  1523. Count Odd Numbers in an Interval Range

**Code 1: CASE "Accepted"**

```
class Solution {
public:
    int countOdds(int low, int high) {
        int count = 0;
        for(int i=low; i<=high; i++){
            if(i&1){
                count++;
            }
        }
        return count;
    }
};
```

**code 2: CASE "TLE" - same as code 1**

**code 3: CASE "TLE" - Modified code** 

```
class Solution {
public:
    int countOdds(int low, int high) {
        int count = 0, i;
        for(i=low; i<=high; i++){
            if(i&1){
                count++;
            }
        }
        return count;
    }
};
```

**code 4: CASE "Accepted": same as code 3**

#### Language used for code
C++

#### Expected behavior
In those cases, I expected "Time Limit Exceeded". But got "Accepted" 2 times.

#### Screenshots
Here are all the screenshots from all cases.
1. Got "Accepted": CASE 1
![acceptedOutputpng](https://user-images.githubusercontent.com/23745270/156642881-1e8ddde0-7bb9-46ba-a7e3-b668eb9066f7.png)

2. GOT "TLE": CASE 2
![TLE](https://user-images.githubusercontent.com/23745270/156643485-46c87516-199a-417f-acc3-0ba1d49d289a.jpg)

3. GOT "TLE": CASE 3
![TLE2](https://user-images.githubusercontent.com/23745270/156643670-a55029b6-da19-4a92-aaa7-f76418fc3489.jpg)

4. GOT "ACCEPTED": CASE 4
![ACCEPTED](https://user-images.githubusercontent.com/23745270/156645001-cd77ace8-00fe-480f-b012-c50e487d1d94.jpg)

**Comment by LC-Sue** [comment]
Hi @CSEKU160212,
Thank you for reaching out to us, when a code is sometimes Accepted and sometimes TLE, it typically means its at the verge of TLE. Please feel free to refer to the discuss section to see how other users' have optimized their codes!
