### ISSUE TITLE
Missing Test Case - 133. Clone Graph

### ISSUE THREAD

**Issue by chocolatefudge** [LeetCode-Feedback/LeetCode-Feedback#6606]
#### Your LeetCode username

komfkore
dong32@gmail.com

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

If I successfully cloned graph by modifying the original graph's data, it is treated as wrong answer. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def cloneGraph(self, node: 'Node') -> 'Node':
            if not node:
                return node
            if node.val == -1:
                return node.neighbors[0]
            newNode = Node(node.val)
            neighbors = node.neighbors
            node.val, node.neighbors = -1, [newNode]
            for n in neighbors:
                newNode.neighbors.append(self.cloneGraph2(n))
            return newNode
```

#### Language used for code

Python3

#### Expected behavior

In the above code, I tried to clone the given graph without using hash table for storing previously created cloned nodes. 
The idea is to store cloned nodes inside the original node's neighbors list and mark the original node (by changing its value to -1)
In this way, if we encounter a node that has value of -1, we identify them as a copy of that node already exists and retrieve it by node's neighbor. 

However, in grading logic, I think it compares the cloned graph with original graph given in the problem.
Which, in my case, will be evaluated as wrong because I modified the original graph during the construction. 
In my opinion, this should also be a correct answer since there was no restriction on changing the given graph, but we only have to return a correct copy of it. 

Therefore, these two changes are plausible. 
1) Changing the grading logic such that, clone the given graph to make [clone1], run the user's code to make [clone2] and compare [clone1] and [clone2]. This will make cases like mine to correct answer. 
2) Change the problem description that the original graph cannot be modified. 

Thank you!

**Comment by chocolatefudge** [comment]
How come this one is still not reached out? 
Test case can be [[2,4],[1,3],[2,4],[1,3]].

**Comment by LC-Sue** [comment]
Hi @chocolatefudge,
Thank you for reaching out to us, the code you provided returns runtime error. Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
