### ISSUE TITLE
Binary Search Template - Example Code

### ISSUE THREAD

**Issue by llau-kicker** [LeetCode-Feedback/LeetCode-Feedback#6607]
#### Your LeetCode username
llau

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The example code for Binary Search Template II and III in the Binary Search lesson is inconsistent with the image provided in Binary Search Template Analysis.
Templates II and III contain the extra conditional:
```
if(nums[mid] == target){ return mid; }
```

**Comment by LC-Sue** [comment]
Hi @llau-kicker 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
