### ISSUE TITLE
Missing Test Case - 443. String Compression

### ISSUE THREAD

**Issue by JiayingGaoo** [LeetCode-Feedback/LeetCode-Feedback#6608]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by JiayingGaoo** [comment]
Missing test cases ["a","1","<","'","t","<","x","[","S","%"], there is no test cases tailed with '%'

**Comment by LC-Sue** [comment]
Hi @JiayingGaoo 
Please provide more details on your missing test case report. Full code used for submission, code language, expected behavior, etc. After more information is provided, I will reopen this ticket. Thank you for your time.
