### ISSUE TITLE
Either Enhance the Testcase or Change the Difficulty - 1601. Maximum Number of Achievable Transfer Requests

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#6609]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The time complexity of brute force is O(n*2^m), and can be accepted now. But the difficulty of this problem is "Hard", this is so incredible. In fact, there is a solution with O(mn+m^2) complexity. I think although this solution may be too hard for the real interview, it can be the expected solution for a weekly contest. As the last problem of a weekly contest, if a beginner of programming can solve it easily, it will be valueless. 
So,  I think either of the following sugguestions should be accepted:    
1. The constraints of n and request.length can be increased to 200, and add at least one testcase with n==200 and request.length==200.
2. Change the difficulty mark of this problem from "Hard" to "Easy".

Code you used for Submit/Run operation

The time complexity of the code below is O(n*2^m)

```
class Solution:
    def maximumRequests(self, n: int, requests: List[List[int]]) -> int:

        cnt = [0]*n
        ans = 0
        for num in range(1<<len(requests)):
            for j in range(n):
                cnt[j]=0
            for j,(x,y) in enumerate(requests):
                if num&(1<<j):
                    cnt[x]-=1
                    cnt[y]+=1
            if max(cnt)==0:
                ans = max(ans,bin(num).count('1'))
        return ans
```

The time complexity of the code below is O(mn+m^2)

```
class Solution:
    def maximumRequests(self, n: int, requests: List[List[int]]) -> int:

        s,t,N,K = n,n+1,n+2,0

        diff = [0]*n
        for frm,to in requests:
            diff[frm] += 1
            diff[to] -= 1

        edges = []
        for i in range(n):
            if diff[i]>0:
                for j in range(diff[i]):
                    edges.append([s,i,0])
            elif diff[i]<0:
                for j in range(-diff[i]):
                    edges.append([i,t,0])
            K += max(diff[i],0)

        for frm,to in requests:
            edges.append([frm,to,1])

        G = [[] for j in range(N)]
        for j in range(len(edges)):
            G[edges[j][0]].append(j)
            G[edges[j][1]].append(j)
        
        ans = len(requests)

        h = [0]*N
        for k in range(K):
            dist = [N]*N
            pre = [-1]*N
            done = [0]*N
            dist[s] = 0
            q = deque()
            q.appendleft(s)
            while q:
                u = q[0]
                q.popleft()
                if done[u]:
                    continue
                done[u]=1
                for j in G[u]:
                    if edges[j][0]==u:
                        w = edges[j][2]+h[u]-h[edges[j][1]]
                        if dist[edges[j][1]]>dist[u]+w:
                            dist[edges[j][1]]=dist[u]+w
                            if w:
                                q.append(edges[j][1])
                            else:
                                q.appendleft(edges[j][1])
                            pre[edges[j][1]]=j
            for j in range(N):
                h[j]+=dist[j]
            ans-=h[t]
            u = t
            while u!=s:
                edges[pre[u]][2]=-edges[pre[u]][2]
                edges[pre[u]][0],edges[pre[u]][1]=edges[pre[u]][1],edges[pre[u]][0]
                u = edges[pre[u]][1]

        return ans
```

Language used for code
Python3

Expected behavior
Either of the following sugguestions should be accepted:    
1. The constraints of n and request.length can be increased to 200, and add at least one testcase with n==200 and request.length==200.
2. Change the difficulty mark of this problem from "Hard" to "Easy".

**Comment by stormsunshine** [comment]
I don't think the constraints should be changed. Otherwise the virtual contest with this problem will be affected.
Besides, I don't think this is an Easy problem. It should be a Medium problem.
If the solution with a better time complexity is necessary, a follow-up can be added. However, I don't think such a solution is required in an interview.

**Comment by stormsunshine** [comment]
I don't think the constraints should be changed. Otherwise the virtual contest with this problem will be affected.
Besides, I don't think this is an Easy problem. It should be a Medium problem.
If the solution with a better time complexity is necessary, a follow-up can be added. However, I don't think such a solution is required in an interview.
