### ISSUE TITLE
[79. Word Search] An incorrect test case

### ISSUE THREAD

**Issue by xuanyuwang** [LeetCode-Feedback/LeetCode-Feedback#661]
Please correct me if the following statements are wrong.

The test case failed my code is the following:
```
[["F","Y","C","E","N","R","D"],["K","L","N","F","I","N","U"],["A","A","A","R","A","H","R"],["N","D","K","L","P","N","E"],["A","L","A","N","S","A","P"],["O","O","G","O","T","P","N"],["H","P","O","L","A","N","O"]]
"poland"
```
and the expected result is `false`.

However, the result should be true because if we look at the board
```
[
["F","Y","C","E","N","R","D"],
["K","L","N","F","I","N","U"],
["A","A","A","R","A","H","R"],
["N","D","K","L","P","N","E"],
["A","L","A","N","S","A","P"],
["O","O","G","O","T","P","N"],
["H","P","O","L","A","N","O"]
]
```
, we'll see a word of this path:
```
P - (6, 1)
O - (5, 1)
L - (4, 1)
A - (4, 0)
N - (3, 0)
D - (3, 1)
```

Here is the screenshot of that test case:
![Screen Shot 2020-07-18 at 11 08 59 PM](https://user-images.githubusercontent.com/22479912/87866130-d0bd0480-c94b-11ea-8455-3147b7533a89.png)

**Comment by lc-christina** [comment]
Hi @xuanyuwang 
Thank you for reaching out to us. The result should be false because you need to consider the upper and lower case.
