### ISSUE TITLE
Gives Wrong Answer while submitting but gives Accepted on the same test case while running code - 322. Coin Change

### ISSUE THREAD

**Issue by SajibTalukder2k16** [LeetCode-Feedback/LeetCode-Feedback#6614]
#### Category of the bug
- [ ] Solution

#### Description of the bug
TestCase:
[2]
3

It shows my answer is 2.
But actually my solution is gives -1 , on this test case
Giving Wrong Answer while submitting but giving Accepted on the above test case while running code. 

#### Code you used for Submit/Run operation

```
// Two Sum
#define inf 9999999
#define mx 10001
vector<int>dp(mx,-1);
int cnt;
class Solution {
public:
    int foo(int weight,vector<int>coins,int sz){
        int mn=inf;
        for(int i=0;i<sz;i++)
        {
            if(weight-coins[i]>=0){
                if(dp[weight-coins[i]]!=-1){
                    mn=min(mn,1+dp[weight-coins[i]]);
                }
                else{
                    mn=min(mn,1+foo(weight-coins[i],coins,sz));
                }
                
            }
                
        }
        return dp[weight]=mn;
        
    }
    int coinChange(vector<int>& coins, int amount) {
        int sz=coins.size();
        dp[0]=0;
        int val=foo(amount,coins,sz);
        if(val==inf)
            return -1;
        return val;
    }
};
```

#### Language used for code 
C++

#### Expected behavior
On the above test case, my solution should be accepted. but it gives the wrong answer.

#### Screenshots

![1](https://user-images.githubusercontent.com/30448179/156816233-14d6f18c-0549-4071-bb1a-87fdb24d24e1.png)

#### Additional context
I have added the submission detail link
https://leetcode.com/submissions/detail/653334531/

**Comment by LC-Sue** [comment]
Hi @SajibTalukder2k16 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
