### ISSUE TITLE
Failing Test Case - 486. Predict the Winner

### ISSUE THREAD

**Issue by iam-agf** [LeetCode-Feedback/LeetCode-Feedback#6618]
#### Your LeetCode username
@genericalAccount

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Test case 61 of this problem is wrong. 
```
[0,0,7,6,5,6,1]
```
The explanation is [here](https://leetcode.com/problems/predict-the-winner/discuss/1744869/why-in-0076561-player-1-should-lose/1294395) . Mathematically, it makes no sense it's failing, but the algorithm used by others may be a solution because it's wrong.

#### Code you used for Submit/Run operation
The solution I add below is made mathematically.
```
class Solution:
    def PredictTheWinner(self, nums: List[int]) -> bool:
        if len(nums) % 2 == 0:
            return True
        
        else:
            scores = [0,0]
            for idx in range(len(nums)):
                if idx % 2 ==0:
                    # Odd sum
                    scores[0] += nums[idx]
                else:
                    # Even sum
                    scores[1] += nums[idx]
                        
            odd, even = scores
            minimalSum = min(odd, even)
            
            player1FirstMove = max(nums[0],nums[-1])
            oddAfterMove1 = odd - player1FirstMove
            player2ChoiceForGame = max( oddAfterMove1, even )
            player1ChoiceForGame = min( oddAfterMove1, even )

            if player2ChoiceForGame <= player1ChoiceForGame + player1FirstMove:
                return True
            else:
                return False
```

#### Language used for code
Python

#### Expected behavior
If player 1 starts taking the last element of the array, no matter which choice makes the player 2, he'll have an advantage of 1, ending the game as 12 vs 13. What's wrong with this logic?

**Comment by LC-Sue** [comment]
Hi @iam-agf,
Thank you for reaching out to us, Player 2 will win which is what the expected output returns -false. The test case appears to be correct. Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
