### ISSUE TITLE
Missing test case: [1521. Find a Value of a Mysterious Function Closest to Target]

### ISSUE THREAD

**Issue by sekhar179** [LeetCode-Feedback/LeetCode-Feedback#662]
#### Your LeetCode username

sekhar179

#### Category of the bug
- [ ] Question
- [v ] Solution
- [ ] Language

#### Description of the bug

A solution without handling all cases has been accepted.

#### Code you used for Submit/Run operation

```
// Find a Value of a Mysterious Function Closest to Target
class Solution {
public:
    int n=arr.size();
        int temp=arr[0],ans=INT_MAX;
        for(int i=0;i<n;i++)
        {
            if(temp<target) temp=arr[i];
            temp=temp&arr[i];
            ans=min(ans,abs(target-temp));
        }
        return ans;
};
```

#### Language used for code

C++

#### Expected behavior

Input: [6,5,1], 1
Output: 1
Expected: 0

**Comment by lc-christina** [comment]
Hi @sekhar179 ,
Thanks for reaching out to us. I tried the code you provided but received Compile Error when submitted. Would you mind providing the submission link that you got Accepted for us to reproduce the issue? Thank you so much!
<img width="1680" alt="Screen Shot 2020-07-21 at 4 34 49 PM" src="https://user-images.githubusercontent.com/67175512/88117538-443f5b80-cb70-11ea-8c17-3e180cbcbc89.png">

**Comment by sekhar179** [comment]
sorry for that, please find below the code without compilation errors.
``
class Solution {
public:
    int closestToTarget(vector<int>& arr, int target) {
        int n=arr.size();
        int temp=arr[0],ans=INT_MAX;
        for(int i=0;i<n;i++)
        {
            if(temp<target) temp=arr[i];
            temp=temp&arr[i];
            ans=min(ans,abs(target-temp));
        }
        return ans;
    }
};
``

**Comment by lc-pam** [comment]
Hi @sekhar179 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
