### ISSUE TITLE
Failing Test Case - 740. Delete and Earn

### ISSUE THREAD

**Issue by 17Peeyush** [LeetCode-Feedback/LeetCode-Feedback#6620]
#### Your LeetCode username

Peeyush17

#### Category of the bug
- [ ] Question
- [ ] Solution
- [C++ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Not giving correct output when more than one test cases are provided but working fine if only one test case is given as input.

#### Code you used for Submit/Run operation

```
// Delete and Earn
class Solution {
public:
    int deleteAndEarn(vector<int>& nums) {
        int freq [10002];
		int dp [10002];

		for(int i = 0; i < nums.size(); i++){
			freq[nums[i]]++;
		}
        int mx=0;
		dp[0] = 0;
		dp[1] = 1* freq[1];
		for(int i = 2; i < 10002; i++){
			dp[i] = max(dp[i-1], dp[i-2] + i * freq[i]);
            mx=max(mx,dp[i]);
		}
		return mx;
	
    }
};
```

#### Language used for code

C++

#### Expected behavior

When I am running the code for example 2 input individually then it is giving correct answer but when I am providing more than one test case it is giving wrong answer.  When I converted my cplusplus code into java equivalent code then it compiled and ran successfully.

#### Screenshots

![image](https://user-images.githubusercontent.com/49943714/156882656-c1cfc2a9-5e97-4062-a4ae-111549a438ac.png)

![image](https://user-images.githubusercontent.com/49943714/156882676-3d6fa60c-ead0-4192-8de5-7f4686294b1e.png)

**Comment by LC-Sue** [comment]
Hi @17Peeyush,
Thank you for reaching out to us, our judger appears to be running correctly. Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
