### ISSUE TITLE
Not a valid test case - 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by happilee12** [LeetCode-Feedback/LeetCode-Feedback#6622]
#### Your LeetCode username

happilee12

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [V ] Missing Test Cases 

#### Description of the bug

the problem said the pivot index k (1 <= k < nums.length)
but the testcase below is not pivoted. (or k is 0)
[1,3]
0

**Comment by LC-Sue** [comment]
Hi @happilee12,
Thank you for reaching out to us, you may have overlooked the word "possibly". When it is rotated, it is rotated by a value 1 <= k < nums.length and when it is not rotated, then that's equivalent to k = 0.
