### ISSUE TITLE
Valid Sudoku

### ISSUE THREAD

**Issue by ashwath20** [LeetCode-Feedback/LeetCode-Feedback#6623]
**Valid Sudoku rules are**
(https://leetcode.com/problems/valid-sudoku/)
Each row must contain the digits 1-9 without repetition.
Each column must contain the digits 1-9 without repetition.
Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.

**contraints**

board.length == 9
board[i].length == 9
board[i][j] is a digit 1-9 or '.'.

But it failes for the below use input
condition says it should have 1-9 value but here no values still it returns true

[[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."]]
[[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".",".","."]]

**Comment by Leader-board** [comment]
The question says that "only the filled cells need to be validated". Since there are no cells to validate, the sudoku is indeed solvable and the answer is true.

**Comment by ashwath20** [comment]
Thank you

**Comment by LC-Sue** [comment]
Hi @ashwath20 
I'm sorry we didn’t get to you sooner - but I am glad to see your issue has resolved! Please feel free to let me know if you have any other questions or concerns.
