### ISSUE TITLE
Incorrect Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by KishanMistri** [LeetCode-Feedback/LeetCode-Feedback#6625]
#### Category of the bug
- Missing Test Cases 

#### Description of the bug

The incorrect test case result for a test case input- "words and 987".
The answer should be 987. But it shows the Expected Answer to be 0.

#### Code you used for Submit/Run operation

```
class Solution:
    def myAtoi(self, s: str) -> int:
        i=0
        started=False
        isNeg=False
        while i<(len(s)-1):
            if (ord(s[i])==45 and (ord(s[i+1])<=57 and ord(s[i+1])>=48)) or (ord(s[i])<=57 and ord(s[i])>=48): 
                break
            i+=1
      
        if s[i]=='-':
            isNeg=True
            i+=1

        while(i<len(s) and ord(s[i])==48 ):
            i+=1
        num=0
        # print(i,s[i],num)
        while (i<len(s) and (ord(s[i])>=48 and ord(s[i])<=57)):
            num=(num*10)+int(s[i])
            i+=1
      
        if not (num>=0 and num< (pow(2,31)-1)):
            return False
        if isNeg:
            return -1*num
        return num
        
```

#### Language used for code

Python3

#### Expected behavior

The correct Answer should be -> 987

#### Screenshots

![Incorrect Testcase](https://user-images.githubusercontent.com/20341930/156894243-5375dfe1-5a14-4112-979f-c89d34b9f756.PNG)

**Comment by Leader-board** [comment]
The question implies that the process stops when a non-valid character (such as a letter is reached). Hence the expected answer is indeed 0, as no number has been parsed since it stops right at the beginning.

If the test case was "987 and words", _then_ the answer would be 987, because the process stops after the numbers have been read.

**Comment by LC-Sue** [comment]
Hi @KishanMistri,
Thank you for reaching out to us! I hope Leader-board's response was able to answer your doubts! Feel free to reach out again if you have any other questions!
