### ISSUE TITLE
Nested List Weight Sum - Existing Test Case

### ISSUE THREAD

**Issue by SinxRofozoteron** [LeetCode-Feedback/LeetCode-Feedback#6628]
#### Your LeetCode username

Prudon

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My JavaScript solution works correctly on my machine but fails on Leetcode. 

#### Code you used for Submit/Run operation

```
var depthSum = function (nestedList, depth = 1) {
  let sum = 0;
  for (let i = 0; i < nestedList.length; i++) {
    const current = nestedList[i];
    const a = typeof current;
    if (typeof current === "number") {
      sum += current * depth;
    } else {
      const newDepth = depth + 1;
      sum += depthSum(current, newDepth);
    }
  }
  return sum;
};
```

#### Expected behavior

Solution expected to solve exiting test cases. Output is 0 instead.

#### Screenshots

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/71668973/156898792-24c0d3ba-aa82-46c7-be3e-7626edcb42a7.png">
<img width="750" alt="image" src="https://user-images.githubusercontent.com/71668973/156898813-39c07669-9e23-484c-915e-9ec4164626bf.png">#### Additional context

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
