### ISSUE TITLE
792. 匹配子序列的单词数，同样的复杂度和相似实现，调用内置函数击败100%，而手写的超时

### ISSUE THREAD

**Issue by zhqu1148980644** [LeetCode-Feedback/LeetCode-Feedback#663]
#### Category of the bug
- [ x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

In problem `792. Number of Matching Subsequences`, the naive solution is to check all characters in S for each searching word.
The time complexity is too high to pass all test cases and even your official answer has said this method would cause TIME LIMIT exceed.

The first code piece listed below could beats 100% merely because it calls `string::find_first_of` function, while my hand written codes uses exactly the same routine(I believe) get TLE as expected.

So, what's the reason?

##### version 1 beats 99% use string::find_first_of
```c++
# comes from the second solution post in leetcode-cn
class Solution {
public:
    int numMatchingSubseq(string S, vector<string>& words) {
        int res = 0, j;
        for (int i = 0; i < words.size(); i ++) {
            int position = -1;
            for (j = 0; j < words[i].size(); j ++) {
                position = S.find_first_of(words[i][j], position + 1); 
                if (position == -1) break; 
            }
            if (j == words[i].length()) res ++; 
        }
        return res;
    }
};
```

#### version 2 hand written Time limit exceed

```c++
static inline int find_first_of(const string & s, char & c, int st) {
    int  n = s.size() - st;
    const char * data = s.data(), * cur = data + st;
    for (std::size_t i = 0; i < n; ++i) {
        if (cur[i] == c)
            return cur + i - data;
    }
    return -1;
}

class Solution {
public:
    int numMatchingSubseq(string S, vector<string>& words) {
        int res = 0, j;
        for (int i = 0; i < words.size(); i ++) {
            int position = -1;
            for (j = 0; j < words[i].size(); j ++) {
                position = find_first_of(S, words[i][j], position + 1);
                if (position == -1) break; 
            }
            if (j == words[i].length()) res ++; 
        }
        return res;
    }
};

```

#### Language used for code

C++ 

#### Expected behavior

I expect the first code also gets TLE.

#### Screenshots

Run by yourself.

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
您好，该题目技术验证没有问题的，请仔细调试优化一下代码。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路哦～

**Comment by zhqu1148980644** [comment]
请解释下为什么第一个代码可以过第二个代码不能过，我认为他们的实现是一样的。
