### ISSUE TITLE
Missing Test Case - 1457. Pseudo-Palindromic Paths in a Binary Tree

### ISSUE THREAD

**Issue by ritwika2000** [LeetCode-Feedback/LeetCode-Feedback#6630]
#### Your LeetCode username
Angel123beyond

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

class Solution {
public:
    bool palindrome(unordered_map<int,int>& mp,int n){
        int v=0;
        for(auto val:mp){
            if(val.second%2)
                v++;
        }
        return v<=1;
    }
    void solve(TreeNode* root,unordered_map<int,int>& mp,int n,int& count){
        if(root==NULL)
            return ;
        if(root!=NULL && root->left==NULL && root->right==NULL){
            n++;
            mp[root->val]++;
          if(palindrome(mp,n)){
              count++;
          }
           n--;
            mp[root->val]--;
            if(mp[root->val]==0)
                mp.erase(root->val);
            return ;
        }
       int val=root->val;
        mp[val]++;
        solve(root->left,mp,n+1,count);
        solve(root->right,mp,n+1,count);
        mp[val]--;
        if(mp[val]==0)
            mp.erase(val);
    }
    int pseudoPalindromicPaths (TreeNode* root) {
        if(root!=NULL && root->left==NULL && root->right==NULL)
            return 1;
        unordered_map<int,int> mp;
        int count=0;
        solve(root,mp,0,count);
        return count;
    }
};
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @ritwika2000 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
