### ISSUE TITLE
Sound button broken

### ISSUE THREAD

**Issue by balajig7** [LeetCode-Feedback/LeetCode-Feedback#6631]
https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3881/
I'm not able to find the sound button in the videos and I am not able to increase the volume.

**Comment by LC-Sue** [comment]
Hi @balajig7 
Thank you for reaching out to us, the video is playing fine on my end. I'd suggest try using a different browser/device!

**Comment by nubowski** [comment]
"First Problem with leetcode" was not "The Code Problem", but sound :D
Findout what exacly embed player was used. And how to fix the volume level.
And yea, you dont have a volume scroller (but Vimeo has) 
Thats pretty annoying, when you watched something on Vimeo resourse (lets say few years ago :)), muted the video, and started to watch some embed videos on the leetcode :D "Chrome and Edge both doesnt have a sound button"

Just in case, somehow it could be useful for someone
