### ISSUE TITLE
2195. Append K Integers With Minimal Sum

### ISSUE THREAD

**Issue by imrc** [LeetCode-Feedback/LeetCode-Feedback#6633]
#### Your LeetCode username

iMRC

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

TLE is misleading. 
Testcases are individually runs fine but on submission TLE. on the same testcase.

#### Code you used for Submit/Run operation

```
long long minimalKSum(vector<int>& nums, int k) {
        long long sum = 0;
        
        sort(nums.begin(),nums.end());
        
        long long i = 0;
        int j = 0;
        while( j < nums.size() && k > 0)
        {
            ++i;
            if(nums[j] == i)
            {
                while(j < nums.size() && nums[j]==i)
                    ++j;
            }
            else
            {
                sum += i;
                --k;
            }
        }
        
        i = nums[nums.size()-1] + 1;
        if(k>0)
            sum += i*k + k*(k-1)/2;
        
        // while(k > 0)
        // {
        //     sum += i;
        //     ++i;
        //     --k;
        // }
        return sum;
    }
```

#### Language used for code

C++

#### Expected behavior

How we could figure out the problem with my solution. when the particular testcase runs fine. 
but on submission TLE points out the same testcase

#### Screenshots

![Screenshot 2022-03-06 092603](https://user-images.githubusercontent.com/35555176/156909843-c872e47b-43b2-487f-9f95-dbfb9c8b62e0.png)

#### Additional context

Soo during contest i actually got confused , whether it is the problem with my solution or something wrong in LeetCode side

**Comment by LC-Sue** [comment]
Hi @imrc 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by imrc** [comment]
Thank you
