### ISSUE TITLE
Missing Test Case - 384. Shuffle An Array

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#6635]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [384. Shuffle an Array](https://leetcode.com/problems/shuffle-an-array), a solution can get accepted but fails on a specific test case.

The test case is in the following link. The given array has length 200, `reset` is called once and `shuffle` is called 49999 times. This test case makes the solution (see the code below) get Output Limit Exceeded.
[384.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8192216/384.txt)

If this test case is not to be added, please answer the following two questions.

1. What is the expected solution for this problem, and what is the expected time complexity for this problem?
2. If the solution provided in this issue should be accepted, what values will the constraints changed to?

#### Code you used for Submit/Run operation
```Java
class Solution {
    int[] nums;
    int[] original;

    public Solution(int[] nums) {
        this.nums = nums;
        this.original = new int[nums.length];
        System.arraycopy(nums, 0, original, 0, nums.length);
    }

    public int[] reset() {
        System.arraycopy(original, 0, nums, 0, nums.length);
        return nums;
    }

    public int[] shuffle() {
        int[] shuffled = new int[nums.length];
        List<Integer> list = new ArrayList<Integer>();
        for (int i = 0; i < nums.length; ++i) {
            list.add(nums[i]);
        }
        Random random = new Random();
        for (int i = 0; i < nums.length; ++i) {
            int j = random.nextInt(list.size());
            shuffled[i] = list.remove(j);
        }
        System.arraycopy(shuffled, 0, nums, 0, nums.length);
        return nums;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Add the test case above so that the code above won't get accepted.

If this test case is not to be added, please answer the following two questions.

1. What is the expected solution for this problem, and what is the expected time complexity for this problem?
2. If the solution provided in this issue should be accepted, what values will the constraints changed to?

**Comment by LC-Sue** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
