### ISSUE TITLE
Arrays 101 -> In-place operations -> Squares of sorted array: missing O(n) & O(1) space solution

### ISSUE THREAD

**Issue by ferbeb** [LeetCode-Feedback/LeetCode-Feedback#664]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
On https://leetcode.com/explore/featured/card/fun-with-arrays/511/in-place-operations/ it specifies the following additional requirements for https://leetcode.com/explore/learn/card/fun-with-arrays/511/in-place-operations/3261/:

> This time, you must solve it in O(N) time and O(1) space. No using built-in sort, and no creating a new array.

In solutions, the two pointer solution creates a new array, using O(n) space. In discussions, I haven't seen anyone coming up with a O(N) time and O(1) space solution either. 

There is this thread in the Arrays 101 discussion: 
https://leetcode.com/discuss/explore/fun-with-arrays/585407/How-To-Solve-Squares-of-a-Sorted-Array. There someone came up with a solution in Go that I believe technically manages to fulfill those conditions, by bitshifting the numbers in the array to gain additional storage. I doubt this is the intended solution, instead I presume the constraints were added in error. 

I suggest a solution that fulfills the quoted constraints is added to the solutions, if such a solution exists, otherwise the problem should be removed from "in-place operations". Thanks!

**Comment by lc-christina** [comment]
Hi @ferbeb 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @feiceh 
Thank you for your time. We've used your feedback to update the problem. Please leave your leetcode account in the comment so we can reward you leetcoin. We appreciate your support!

**Comment by ferbeb** [comment]
https://leetcode.com/ferbeb/
Thank you!

**Comment by lc-pam** [comment]
Hi @ferbeb 
Thank you for providing your account! Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
