### ISSUE TITLE
Missing Test Case - 595. Big Countries

### ISSUE THREAD

**Issue by AkashSingh3031** [LeetCode-Feedback/LeetCode-Feedback#6643]
#### Your LeetCode username
`akashsingh3031`

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

```
Input: {"headers": {"World": ["name", "continent",	"area",	"population", "gdp"]}, "rows": {"World": [["Afghanistan", "Asia", 3000000, 25500100, 20343000000], ["Albania", "Europe", 28748, 25000000, 12960000000]]}}

Output:  {"headers": ["name", "population", "area"], "values": [["Afghanistan", 25500100, 3000000]]}

Expected:  {"headers": ["name", "population", "area"], "values": [["Afghanistan", 25500100, 3000000], ["Albania", 25000000, 28748]]}
```

#### Code you used for Submit/Run operation

```
// Big Countries
SELECT
    name, 
    population, 
    area
FROM
    world
WHERE
    population > 25000000 
    OR area > 30000000;
```

#### Language used for code
`MySQL`

#### Expected behavior

`Error`:-- `["name", "population", "area"]  ---->  ["Albania", 25000000, 28748]`
               `WHERE  population > 25000000  OR area > 30000000`

#### Screenshots

![image](https://user-images.githubusercontent.com/60146338/156989666-74de7fc3-58d8-4f27-b4d0-877a0a1e346d.png)

**Comment by LC-Sue** [comment]
Hi @AkashSingh3031,
Thank you for reaching out to us, our judger is running correctly. Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
