### ISSUE TITLE
Unnecessary Lines in Solution: 269. Alien Dictionary

### ISSUE THREAD

**Issue by SpectralFergus** [LeetCode-Feedback/LeetCode-Feedback#6645]
#### Your LeetCode username
SpectralFergus

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The lines before the return statement in the DFS solution don't seem necessary and my test cases pass even without them.
```
if (output.length() < reverseAdjList.size()) {
    return "";
}
```
It seems to imply that there can be missing characters in the output, which is impossible since the solution touches and performs a DFS on every node in the graph in Step 2 in the for loop. There's also no comment explaining why it's there so I'm guessing it was just an unnecessary port from the BFS solution (I haven't attempted BFS so I'm not sure) or different problem.

#### Code you used for Submit/Run operation

```
// ... all of them?
```

#### Language used for code

Java

#### Expected behavior

At least one test case would fail after deleting the previously mentioned lines

**Comment by LC-Sue** [comment]
Hi @SpectralFergus 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
