### ISSUE TITLE
862 和至少为 K 的最短子数组 错误的测试用例

### ISSUE THREAD

**Issue by Can-Chen** [LeetCode-Feedback/LeetCode-Feedback#6646]
**描述**
输入的测试用例为
[48,99,37,4,-31]
140

输出的结果为
2

**你使用的语言**
Javascript

**期望行为**
按照题意应该输出的结果为3

**屏幕截图**
![1241646667226_ pic](https://user-images.githubusercontent.com/50009783/157066225-b9a970d3-9028-4477-a8fc-988521cf264a.jpg)

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by Can-Chen** [comment]
我奇怪的是输入按照题意预期结果应该为3，但是测试用例的预期结果是2
