### ISSUE TITLE
Missing Test Case - 268. Missing Number

### ISSUE THREAD

**Issue by 7AAKANSHA** [LeetCode-Feedback/LeetCode-Feedback#6647]
#### 7AAKANSHA

EXAMPLE MENTIONED IS NOT EXPLAINED PROPERLY
Example 2:
Input: nums = [0,1]
Output: 2
Explanation: n = 2 since there are 2 numbers, so all numbers are in the range [0,2]. 2 is the missing number in the range since it does not appear in nums.
 --In this Example, the nums array has a [0-1] range then how output can be 2?
If the range is [0-2] in nums array then it can be 2 but its range is [0-1], then how is missing no 2 !!

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @7AAKANSHA,
Thank you for reaching out to us! 
The problem constraints say:
n == nums.length
The example the you gave nums = [0, 1] then nums.length = 2.
So what number is missing from (0, 1, 2)?
