### ISSUE TITLE
Article Issue 709, To Lower Case, use keyword as a parameter name

### ISSUE THREAD

**Issue by Yorafa** [LeetCode-Feedback/LeetCode-Feedback#6648]
#### Your LeetCode username

Yorafa

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Solution article use `str` as a parameter name, but `str` is a keyword of python shouldn't be use. 

#### Code you used for Submit/Run operation

Article given solution:
```
class Solution:
    def toLowerCase(self, str: str) -> str:
        return str.lower()
```

#### Language used for code

Python

#### Expected behavior

Any none keyword valid name.

**Comment by CarlCzerny837** [comment]
The 'str' is not a keyword but a built-in class in Python.
However, I think the name of the input parameter should be changed to 's'.

**Comment by Yorafa** [comment]
> The 'str' is not a keyword but a built-in class in Python. However, I think the name of the input parameter should be changed to 's'.

I agree, thank to point out.

**Comment by LC-Sue** [comment]
Hi @Yorafa 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
