### ISSUE TITLE
468. Validate IP Address

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#665]
#### Your LeetCode username

gordonek

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Contradictory problem statement.
#### Code you used for Submit/Run operation

Statement `**extra** leading zeros in the IPv6 is also invalid` indicates one leading zero is allowed, more than one is not allowed. However provided example right after mentioned statement`02001` is not IPv6 because it has five hexadecimal digits (wrong example for the above statement). If follow mentioned problem statement, then **0037** and **0000** is invalid, which is not true.  

#### Language used for code

Python3

#### Expected behavior

Change `leading zeros in the IPv6 is also invalid` to `If there is a group of more than 4 hexadecimal digits, IPv6 is invalid (regardless of number of leading zeros).`

**Comment by lc-christina** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by agatagruza** [comment]
Thank you @lc-pam for the info. Glad could help.
