### ISSUE TITLE
2196. Create Binary Tree From Descriptions - Memory exceeded guaranteed for any Scala solution

### ISSUE THREAD

**Issue by cosminci** [LeetCode-Feedback/LeetCode-Feedback#6652]
#### Your LeetCode username
cosminci

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The runtime thresholds for Scala are too strict. Solutions fail w/ **Memory Limit Exceeded**.
There is a [thread on this on the leetcode discussion forum](https://leetcode.com/problems/create-binary-tree-from-descriptions/discuss/1826729/scala-always-throwing-memory-limit-exceeded-in-this-question/1298696).

#### Code you used for Submit/Run operation
See the leetcode discussion link above - there are multiple solutions from multiple leetcoders there.

#### Language used for code
Scala

#### Expected behavior
At the very least, the solution relying on mutable data structures should pass.
Ideally, a functional solution using immutable data structures should also pass.

#### Screenshots
N/A

#### Additional context
N/A

**Comment by LC-Sue** [comment]
Hi @cosminci 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
