### ISSUE TITLE
2. Add Two Numbers

### ISSUE THREAD

**Issue by gkatsanos** [LeetCode-Feedback/LeetCode-Feedback#6653]
#### Your LeetCode username

gkatsanos

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

How would one traverse the linked list? the implementation of the list is custom, we're not supposed to know how the test designer created it.

**Comment by LC-Sue** [comment]
Hi @gkatsanos,
Thank you for reaching out to us, whenever a custom class is provided, the implementation will be given at the top of the input field.  For example, in this problem, you are given a commented out version of a ListNode.  A singly linked list is a collection of list nodes.  You are provided a list node which is the head, which you can then use to access the rest of the nodes in the list.
