### ISSUE TITLE
Heap sort space complexity - Heap card

### ISSUE THREAD

**Issue by ahmdsolmn** [LeetCode-Feedback/LeetCode-Feedback#6654]
#### Your LeetCode username
ahmdsolmn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the `Heap` Card, space complexity for heap sort is incorrect. The stated space complexity is `O(n)`. The correct space complexity is `O(1)`.
[Card reference](https://leetcode.com/explore/featured/card/heap/645/applications-of-heap/4030/)

#### Screenshots

![Screen Shot 2022-03-08 at 2 01 18 PM](https://user-images.githubusercontent.com/1368481/157234562-ee485fbb-4718-452e-80bd-c836df393488.png)

**Comment by LC-Sue** [comment]
Hi @ahmdsolmn 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
