### ISSUE TITLE
Missing Test Case - 1502. Can Make Arithmetic Progression From Sequence

### ISSUE THREAD

**Issue by tab21** [LeetCode-Feedback/LeetCode-Feedback#6655]
#### Category of the bug
- [ ] Solution - It has one test case with ---
                        Input - [1,100]
                        Output - true ---- which I believe is wrong.

#### Description of the bug

it is said a series is an A.P when it is a sequence of numbers such that the difference between the consecutive terms is constant. and for the common difference to tally, we need to have at least 2 differences to tally them. thus a series having less than 2 numbers can never be an A.P. Therefore, this test should be false.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    bool canMakeArithmeticProgression(vector<int>& arr) {
      sort(arr.begin(),arr.end());
      
      if (arr.size()<3){
        return false;
      }
      int d=arr[1]-arr[0];
      
      for(int i=1;i<arr.size()-1;i++){
        int c=arr[i+1]-arr[i];
        if (d!=c){
          return false;
        }
      }
      
      return true;
      
    }
};
```

#### Expected behaviour

As explained earlier that a series having less than 3 numbers can never be A.P. Thus this test case should be false.
![leetcodeAP](https://user-images.githubusercontent.com/88936564/157241978-c70472df-4b34-46d8-9a17-026d9f5f0b46.png)

#### Screenshots

![leetcode ](https://user-images.githubusercontent.com/88936564/157241835-84d8ca01-3977-4b3d-8b00-b2cab165355f.png)

**Comment by LC-Sue** [comment]
Hi @tab21,
Thank you for reaching out to us, from the rules given in the problem, any list of length 2 should be accepted as an arithmetic progression.
