### ISSUE TITLE
Incorrect Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by sherdil0023** [LeetCode-Feedback/LeetCode-Feedback#6656]
#### Your LeetCode username 
dna_2020

#### Category of the bug
-   Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem statement says _There is only one repeated number in nums, return this repeated number._
Whereas this test case not follows this statement.
Input : [2,2,2,2,2]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int findDuplicate(vector<int>& nums) {
        long long int sum = 0;
        long long int n = nums.size()-1;
        for(auto it : nums) sum += it;
        return sum - (n*(n+1))/2;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This testcase is incorrect I feel it must be removed.

**Comment by LC-Sue** [comment]
Hi @sherdil0023,
Thank you for reaching out to us, the question means only one number can be repeated not that it can only be repeated once. Sorry for the confusion!
