### ISSUE TITLE
Bug in disjoint set python example code (Union by Rank)

### ISSUE THREAD

**Issue by xzhub** [LeetCode-Feedback/LeetCode-Feedback#6659]
#### Your LeetCode username
ZhaoCode

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

url: https://leetcode.com/explore/featured/card/graph/618/disjoint-set/3843/

the existing code.
```
    # The union function with union by rank
    def union(self, x, y):
        rootX = self.find(x)
        rootY = self.find(y)
        if rootX != rootY:
            if self.rank[rootX] > self.rank[rootY]:
                self.root[rootY] = rootX
            elif self.rank[rootX] < self.rank[rootY]:
                self.root[rootX] = rootY
            else:
                self.root[rootY] = rootX
                self.rank[rootX] += 1
```

which should be:

```
    # The union function with union by rank
    def union(self, x, y):
        rootX = self.find(x)
        rootY = self.find(y)
        if rootX != rootY:
            if self.rank[rootX] >= self.rank[rootY]:
                self.root[rootY] = rootX
                self.rank[rootX] += self.rank[rootY]
            elif self.rank[rootX] < self.rank[rootY]:
                self.root[rootX] = rootY
                self.rank[rootY] += self.rank[rootX]
```

#### Language used for code
Python

**Comment by LC-Sue** [comment]
Hi @xzhub 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Dear user, 
thank you for sharing your concern. The current code defines rank[rootX] as the maximum possible height of the tree rooted at the node rootX where the code you have provided defines rank[rootX] as the number of nodes in the tree rooted at rootX. (Likewise for rootY). Both are valid implementations of union find and can achieve an amortized complexity of &alpha;(n) (where &alpha; is the Inverse Ackermann Function). You can read about these two implementations here [Disjoint-set](https://en.wikipedia.org/wiki/Disjoint-set_data_structure#Merging_two_sets)
