### ISSUE TITLE
74. Search a 2D Matrix

### ISSUE THREAD

**Issue by rishi2907** [LeetCode-Feedback/LeetCode-Feedback#666]
#### Your LeetCode username

rishi2907

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Code got accepted which has output different than expected. weak testcase for this question

#### Code you used for Submit/Run operation

```
// 74. Search a 2D Matrix
class Solution {
public:
    bool searchMatrix(vector<vector<int>>& matrix, int target) {
        int n  = matrix.size();
        if(n==0)
            return false;       
        int m = matrix[0].size();
        int flag=0;
       
        int start= 0;
        int end = m*n-1;
        
        while(start<=end){
            int mid = (start+end)/2;
            int val = matrix[mid/m][mid%m];
            if(val>target){
                end = mid -1;
            }
            else if(val < target){
                start = mid+1;
                
            }
            else{
                return true;
            }
        }
        return false;
    }
};


```

#### Expected behavior

for this test case :
[[1,5,10,15],[4,9,14,19],[8,13,18,23]]
4
expected output : true
My code output : false
my code accepted by platform

#### Screenshots

![rsz_screenshot_from_2020-07-20_23-06-18](https://user-images.githubusercontent.com/33354478/87968361-ed894180-cadd-11ea-801e-5674e7c54056.png)

**Comment by lc-christina** [comment]
Hi @rishi2907 
Thanks for reaching out to us. The problem states 'The first integer of each row is greater than the last integer of the previous row.' so the test case you provided is invalid.
