### ISSUE TITLE
Error when submitting with PHP - 142. Linked List Cycle II

### ISSUE THREAD

**Issue by tn710617** [LeetCode-Feedback/LeetCode-Feedback#6660]
#### Your LeetCode username
serendipityWithCoding

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
PHP language seems to have some error. I've submitted several version of code, and all of them show an error 'Nesting level too deep - recursive dependency'. If I press 'Run Code', the result is okay. However the 'submit' doesn't work.

#### Code you used for Submit/Run operation
```
/**
 * Definition for a singly-linked list.
 * class ListNode {
 *     public $val = 0;
 *     public $next = null;
 *     function __construct($val) { $this->val = $val; }
 * }
 */

class Solution {
    /**
     * @param ListNode $head
     * @return ListNode
     */
    function detectCycle($head) {
        $fast = $head->next->next;
        $slow = $head->next;
        
        while ($fast && $slow) {
            if ($fast === $slow) {
                $index1 = $head;
                $index2 = $fast;
                
                while ($index1 !== $index2) {
                    $index1 = $index1->next;
                    $index2 = $index2->next;
                }
                
                return $index1;
            }
            
            $fast = $fast->next->next;
            $slow = $slow->next;
        }
        
        return null;
    }
}
```

#### Language used for code
PHP

#### Expected behavior
It should pass, but return 'Nesting level too deep - recursive dependency' instead.

**Comment by LC-Sue** [comment]
Hi @tn710617 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by tn710617** [comment]
Hi Su,
I read this article, and It’s not my first day to use Leetcode. I’ve done some test to determine it’s a bug or it’s a mistake on my side.
I’ve googled and paste all those solutions I could find from either Leetcode discussion or Internet, and none of those worked. Do you still think there is no bug on this case?
Could you please spend some time on this case and give it a try.
Or could you please provide a solution that any of other users has provided and which is no problem?

Have a good day.

**Comment by ardiakov** [comment]
I have the same problem with this task.

**Comment by Rukeith** [comment]
I have the same problem here.

**Comment by EriBloo** [comment]
Please note this is probably an error on your end. My solution has 38 lines and this error happens on line 71:
![image](https://user-images.githubusercontent.com/19932449/184028026-cc3f1947-7016-4d9d-8962-ab62f6296c9a.png)

Also, don't just close issues out of laziness when they are clearly not solved.

**Comment by tkyeung357** [comment]
same issue here.  same logic passed with python3 

Test case: 
`[-1,-7,7,-4,19,6,-9,-5,-2,-5]
9`

Code: 
`class Solution {
    /**
     * @param ListNode $head
     * @return ListNode
     */
    function detectCycle($head) {
        
        if ($head == null || $head->next == null || $head->next->next == null) {
            //no cycle
            return null;
        }
        
        $slow = $head;
        $fast = $head;
        while ($fast && $fast->next) {
            $slow = $slow->next;
            $fast = $fast->next->next;
            
            if ($slow === $fast) {                
                break;
            }
        }
        
        if ($slow != $fast ){
            return null;
        }
        
        $fast = $head;
        while ($fast !== $slow) {
            $slow = $slow->next;
            $fast = $fast->next;
        }
        
        return $fast;
    }
}`
