### ISSUE TITLE
206. Reverse Linked List - Asks to return a reversed list, but solution only returns head

### ISSUE THREAD

**Issue by dominick-blue1** [LeetCode-Feedback/LeetCode-Feedback#6663]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
# Python3 Solution that returns a reversed list
class Solution:
    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:
        def reverse(new, old):
            if old is None:
                return new
            else:
                new_h = old.next
                old.next = new
                nhead = old
                return reverse(nhead, new_h)
            
        return(reverse(None, head))
```

**Comment by LC-Sue** [comment]
Hi @dominick-blue1,
Thank you for reaching out to us, the code you provided is accepted with no error. Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.
