### ISSUE TITLE
Question - 116. Populating Next Right Pointers in Each Node

### ISSUE THREAD

**Issue by pratyushgguptaa** [LeetCode-Feedback/LeetCode-Feedback#6664]
#### Your LeetCode username

[pratyushgguptaa](https://leetcode.com/pratyushgguptaa/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question _does not_ specify that we have to _return the root node_ back.

#### Language used for code

For all languages boilerplate code, the return type is a pointer to the Node

#### Expected behavior

The question should mention we have to return the root node. Or else have to change the code and return void.

#### Additional context

Please ignore my misconduct if any.. first time submitting an issue

**Comment by LC-Sue** [comment]
Hi @pratyushgguptaa,
Thank you for reaching out to us, in the console comments are provided as guidance for returning root node. We appreciate your support!
