### ISSUE TITLE
Kotlin lang bug - 20. Valid Parentheses

### ISSUE THREAD

**Issue by ashwath20** [LeetCode-Feedback/LeetCode-Feedback#6666]
#### Your LeetCode username
user3555Wv

#### Category of the bug
- [ ] Language 

#### Description of the bug

: Exception in thread "main" java.lang.VerifyError: Bad type on operand stack

#### Code you used for Submit/Run operation
`class Solution {
    fun isValid(s: String): Boolean {
        var stack=ArrayDeque<Char>()
        var pointer=0
        var exp=' '
        if(s.isEmpty()){
            return true
        }
        while(pointer<s.length){
            var cur=s[pointer]
            if(stack.isEmpty()){
                stack.push(cur)
            }else{
            
          
  when(cur){
                '('->{
                    exp=')'
                }
                ')'->{
                    exp='('
                }
                '{'->{
                    exp='}'
                }
                '}'->{
                    exp='{'
                }
                '['->{
                    exp=']'
                }
                ']'->{
                    exp='['
                }
                
            }
            if(stack.peek().equals(exp)){
                stack.pop()
            }else{
                stack.push(cur)
            }
            }
            pointer+=1
        }
        
            return stack.isEmpty()
        
    }
}`

#### Language used for code
 Kotlin 

#### Expected behavior
Above code works fine in android studio . Not sure if above error is due to kotlin version difference
[ Kotlin bug has been created for the same . ](https://github.com/Kotlin/kotlinx.coroutines/issues/2041#issuecomment-633271810)

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
