### ISSUE TITLE
Invalid Testcase for 627. Swap Salary

### ISSUE THREAD

**Issue by Haozhenbo08** [LeetCode-Feedback/LeetCode-Feedback#6668]
#### Your LeetCode username
haozhenbo

#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The provided solution for MySQL doesn't pass. The error message is "Invalid Testcase: salary"

#### Code you used for Submit/Run operation

```
UPDATE Salary
SET
    sex = CASE sex
        WHEN 'm' THEN 'f'
        ELSE 'm'
    END;
```

#### Language used for code
MySQL

#### Expected behavior
Pass the test.

**Comment by LC-Sue** [comment]
Hi @Haozhenbo08,
Thank you for reaching out to us, the code passes with no issue on my end. Please refer to the screenshot below for reference! 
![image](https://user-images.githubusercontent.com/92285126/158715803-427b1e1e-a8fb-4137-90b5-b86c50faf4c9.png)

**Comment by Haozhenbo08** [comment]
Yeah. Thank you for your reply! This solution can be submitted successfully. But if you just run the code, it will report error: Invalid Testcase: 'salary'
