### ISSUE TITLE
Wrong Answer - 2101. Detonate the Maximum Bombs

### ISSUE THREAD

**Issue by jaisw7** [LeetCode-Feedback/LeetCode-Feedback#6669]
#### Your LeetCode username
jaisw7

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect answer

#### Description of the bug
For the test case 
```[[54,95,4],[99,46,3],[29,21,3],[96,72,8],[49,43,3],[11,20,3],[2,57,1],[69,51,7],[97,1,10],[85,45,2],[38,47,1],[83,75,3],[65,59,3],[33,4,1],[32,10,2],[20,97,8],[35,37,3]]```
the answer is 2 because circles `[69,51,7]` and `[65,59,3]` overlap (see https://www.desmos.com/calculator/vbkzla9zuc). However, the submission system says that the answer is 1.

<img width="840" alt="Screen Shot 2022-03-09 at 5 16 59 PM" src="https://user-images.githubusercontent.com/26517937/157546443-75f1e86c-8088-45bb-b508-9ae7ed37766f.png">

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maximumDetonation(vector<vector<int>>& bombs) {
        int N = bombs.size();
        unordered_map<int, unordered_set<int> > graph;
        
        for(int i=0; i<N; ++i) {
            long long ax=bombs[i][0], ay=bombs[i][1], ar=bombs[i][2];
            for(int j=i+1; j<N; ++j) {
                long long bx=bombs[j][0], by=bombs[j][1], br=bombs[j][2];
                auto dist = (ax-bx)*(ax-bx) + (ay-by)*(ay-by);
                auto cdist = (ar+br)*(ar+br);
                if(dist<=cdist) {
                    graph[i].insert(j);
                    graph[j].insert(i);
                }
            }
        }
        
        vector<bool> visited(N, false);
        function<int(int)> iter = [&](int u) {
            if(visited[u]) { return 0; }
            visited[u] = true;
            int numDetoneted = 1;
            for(auto& v: graph[u]) {
                numDetoneted += iter(v);
            }
            return numDetoneted;
        };
        
        int Max = 0;
        for(int i=0; i<N; ++i) {
            Max = max(Max, iter(i));
        }
        
        return Max;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The answer for the test case should be 2.

**Comment by bogoconic1** [comment]
The graph is directed, not undirected. If bomb 1 can denotate bomb 2 does not mean bomb 2 can denotate bomb 1

**Comment by jaisw7** [comment]
@bogoconic1 
The problem statement states the following:

*When a bomb is detonated, it will detonate all bombs that lie in its range. These bombs will further detonate the bombs that lie in their ranges*

where

*The range of a bomb is defined as the area where its effect can be felt. This area is in the shape of a circle with the center as the location of the bomb*

If bomb1 lies in the range of bomb2, then bomb2 lies in the range of bomb1. In other words, If bomb 1 can detonate bomb2,  it means bomb 2 can detonate bomb1

**Comment by LC-Sue** [comment]
Hi @jaisw7,
Thank you for reaching out to us, the judger is working as expected. Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by jaisw7** [comment]
Hi @LC-Sue 
Thank you for clarification. 

To future readers:
bomb1 can detonate bomb2 iff the center of bomb2 lies on the circumference or inside the circle of influence (range) created by bomb1.
