### ISSUE TITLE
Question- 243. Shortest Word Distance

### ISSUE THREAD

**Issue by Bambooin** [LeetCode-Feedback/LeetCode-Feedback#6674]
#### Your LeetCode username
0x4C0DE

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description is wrong: `1 <= wordsDict.length <= 3 * 10^4`
```
word1 and word2 are in wordsDict.
word1 != word2
```
So  `wordsDict.length` at least is 2.

#### Code you used for Submit/Run operation

```
class Solution {
  public int shortestDistance(String[] wordsDict, String word1, String word2) {
    int n = wordsDict.length;
    int result = n - 1;
    int p1 = -1;
    int p2 = -1;
    for (int i = 0; i < n; i++) {
      if (wordsDict[i].equals(word1)) {
        p1 = i;
      }

      if (wordsDict[i].equals(word2)) {
        p2 = i;
      }

      if (p1 != -1 && p2 != -1) {
        result = Math.min(result, Math.abs(p1 - p2));
      }
    }
    return result;
  }
}
```

**Comment by LC-Sue** [comment]
Hi @Bambooin,
Thank you for reaching out to us, the constraint appears to be correct. 1 <= wordsDict.length <= 3 * 10^4. As long as wordsDict.length is within the constraint, it's ok!
