### ISSUE TITLE
Missing Test Case - 202. Happy Number

### ISSUE THREAD

**Issue by calee0219** [LeetCode-Feedback/LeetCode-Feedback#6675]
#### Your LeetCode username
calee

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some bolder testcase miss will let error code pass.

#### Code you used for Submit/Run operation

```java
// Two Sum
class Solution {
    public boolean isHappy(int n) {
        int sum = 0;
        int rem = 0;
        boolean isHappy = false;

        while(n > 0) {
            rem = n % 10;
            sum = sum + rem * rem;
            n  = n / 10;

            if(n == 0 && sum == 1 || sum == 7) {
                isHappy = true;
                return isHappy;
            } else if(n == 0 && sum != 1 && sum != 7 && sum < 10) {
                isHappy = false;
                return isHappy;
            } else if(n == 0) {
                n = sum;
                sum = 0;
            }
        }
        return isHappy;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The code will error in testcase `11121`. But the it pass the submission.
![image](https://user-images.githubusercontent.com/12643673/157637532-0fcb4006-820c-419f-b2cb-d8bec6325fd1.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/12643673/157637261-eced7014-a66b-426c-ac14-572733ced5d8.png)

#### Additional context

Add some more testcase such as `11121`, `111111111`

**Comment by LC-Sue** [comment]
Hi @calee0219 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
