### ISSUE TITLE
Missing Test Case - 496. Next Greater Element I

### ISSUE THREAD

**Issue by Krishna-Kumar25** [LeetCode-Feedback/LeetCode-Feedback#6676]
#### Your LeetCode username

krishnakmr010101

#### Category of the bug
- [ ] Missing Test Cases 
nums1:- [5,1,3]
nums2:- [1,6,2,3,4,5]
Output should be: [6,6,4] but ouput coming is [-1,6,4]

#### Description of the bug

In this question, This testcase accepted with wrong output. The next greater element is available for 5  i.e 6 after we move cycle in nums2. but it accepted with -1 for 5. I also attached screenshot of passed testcase.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
               int n1=nums1.size();
         int n2=nums2.size();
         vector<int> ans;
        for(int i=0;i<n1;i++){
            for(int j=0;j<n2;j++){
                if(nums1[i]==nums2[j]){
                    int k;
                    for(k=j+1;k<n2;k++){
                        if(nums2[k]>nums2[j]){
                            ans.push_back(nums2[k]);
                            break;
                        }
                    }
                    if(k==n2){
                        ans.push_back(-1);
                        break;
                    }
                }
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected output should be [6,6,4]

#### Screenshots

![image](https://user-images.githubusercontent.com/82657848/157673561-650a1744-1089-4868-9e5a-b94d5b1b3b59.png)

**Comment by LC-Sue** [comment]
Hi @Krishna-Kumar25,
Thank you for reaching out to us, the expected output for this test case is correct. Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
