### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by sahin-murat** [LeetCode-Feedback/LeetCode-Feedback#6679]
#### Your LeetCode username
muratsahin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Golang we cannot set a created array to empty unless it's a pointer, in my case for "Remove Element" on Test Case 109,
The input was `nums[1]` and the output requires to be `nums[]`
as this not possible with `removeElement(nums []int, val int) int` it should be `removeElement(nums *[]int, val int) int`  i can't use pointer because in solutions.go it's sent as  `nums []int`
#### Code you used for Submit/Run operation
```
func removeElement(nums []int, val int) int {
    numsLen := len(nums)
    var result int
    
    if numsLen == 1 {
        if nums[0] == val {
            nums = nil
            return 1
        }
        
        return 0
    }
    
    // constraint 0 <= nums.length <= 100 && 0 <= val <= 100
    if numsLen >= 0 && numsLen <= 100 && val >= 0 && val <= 100 {
     
        k := numsLen - 1
        i := 0
        
        for i <= numsLen && k >= 0 {
            
            if nums[k] == val {
                k--
            } else {
                //swap them
                if nums[i] == val {
                    temp := nums[i]
                    nums[i] = nums[k]
                    nums[k] = temp
                    k--
                } else {
                    i++
                }
            }
            
            if i == k {
                result = i+1
                break
            }            
        }
    }
    
    return result
}

```

#### Language used for code
Golang

#### Expected behavior
for us to be change the sent array it must be sent as `nums *[]int` so we can use `*nums = nil` to set it empty

#### Screenshots
![image](https://user-images.githubusercontent.com/36241142/157740407-bcac177c-2f8f-403a-ac34-2e168346ce6a.png)

**Comment by kai-wei-mo** [comment]
No, the given array need not be `nums *[]int`. 

Revisiting [27. Remove Element](https://leetcode.com/problems/remove-element/)'s description, it says one's submission is judged using this code:

```
int[] nums = [...]; // Input array
int val = ...; // Value to remove
int[] expectedNums = [...]; // The expected answer with correct length.
                            // It is sorted with no values equaling val.

int k = removeElement(nums, val); // Calls your implementation

assert k == expectedNums.length;
sort(nums, 0, k); // Sort the first k elements of nums
for (int i = 0; i < actualLength; i++) {
    assert nums[i] == expectedNums[i];
}
```

The takeaway here is that if there are `k` elements after removing the duplicates, then the first `k` elements of nums should hold the final result and **it does not matter what you leave beyond the first k elements**. Thus, the question can be solved without setting the array as nil even for the test case you provided. To see what I mean, try running your test case again using this ridiculous code:

``` Go
func removeElement(nums []int, val int) int {
    return 0
}
```

**Comment by sahin-murat** [comment]
> No, the given array need not be `nums *[]int`.
> 
> Revisiting [27. Remove Element](https://leetcode.com/problems/remove-element/)'s description, it says one's submission is judged using this code:
> 
> ```
> int[] nums = [...]; // Input array
> int val = ...; // Value to remove
> int[] expectedNums = [...]; // The expected answer with correct length.
>                             // It is sorted with no values equaling val.
> 
> int k = removeElement(nums, val); // Calls your implementation
> 
> assert k == expectedNums.length;
> sort(nums, 0, k); // Sort the first k elements of nums
> for (int i = 0; i < actualLength; i++) {
>     assert nums[i] == expectedNums[i];
> }
> ```
> 
> The takeaway here is that if there are `k` elements after removing the duplicates, then the first `k` elements of nums should hold the final result and **it does not matter what you leave beyond the first k elements**. Thus, the question can be solved without setting the array as nil even for the test case you provided. To see what I mean, try running your test case again using this ridiculous code:
> 
> ```go
> func removeElement(nums []int, val int) int {
>     return 0
> }
> ```

Oh I totally missed that part so you're right thanks 👍
