### ISSUE TITLE
超时报错

### ISSUE THREAD

**Issue by VolleyballBird** [LeetCode-Feedback/LeetCode-Feedback#668]
** Bug 类型**
- [剑指 Offer 03. 数组中重复的数字 ] 题目
- [ ] 题解：
- [python ] 编程语言

**描述**
描述你遇到的 bug
自己写的与题解的代码基本一样，自己的超出时间限制

**你使用的语言**
python

**你提交或者运行的代码**
```
class Solution(object):
    def findRepeatNumber(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        for i in range(len(nums)):
            while i!=nums[i]:
                if nums[i]==nums[nums[i]]: 
                    return nums[i]               
                nums[i],nums[nums[i]]=nums[nums[i]],nums[i]
        return None
```

**期望行为**
通过

**屏幕截图**
![2020-07-21 11-35-52屏幕截图](https://user-images.githubusercontent.com/48613186/88009986-6cb26000-cb46-11ea-9cd1-0f134b89464e.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，超出时间限制是复杂度太高了，建议再仔细调试优化一下代码。后续刷题学习中遇到问题，也可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。
