### ISSUE TITLE
Missing Test Case - 211. Design Add and Search Words Data Structure

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#6681]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8228920/1.txt)

#### Code you used for Submit/Run operation

```
string a[501];
int cnt=0;
class WordDictionary {
public:
    WordDictionary() {
        for(int i=0;i<501;a[i++]="");
    }
    
    void addWord(string word) {
        a[word.size()]+=word;
        string a="",b="a";
    }
    
    bool search(string t) {
        int n=t.size(),i=n-1,m=a[n].size(),j,x;string &s=a[n];
        while(i<m){
        for(x=i,i+=n,j=n-1;s[x]==t[j]||t[j]=='.'||s[x]=='.';--x,++cnt) if (--j<0) return true;
        }
        return false;
    }
    ~WordDictionary(){cout<<cnt<<endl;}
};
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

**Comment by stormsunshine** [comment]
I wonder what the expected solution is. If the expected solution is using trie, then the number of calls to `addWord` and `search` should be reduced.

There is no reason to keep the current constraints if the current constraints may cause an expected solution to get TLE with some specific test cases. If such TLE test cases are not going to be added, why not reduce the constraints?

**Comment by hqztrue** [comment]
> I wonder what the expected solution is. If the expected solution is using trie, then the number of calls to `addWord` and `search` should be reduced.
> 
> There is no reason to keep the current constraints if the current constraints may cause an expected solution to get TLE with some specific test cases. If such TLE test cases are not going to be added, why not reduce the constraints?

Yes, it will be very hard for a trie solution to pass given the current constraints. It's a good idea to reduce the constraints.

**Comment by LC-Sue** [comment]
Hi @hqztrue,
Thank you for reaching out to us, the code you provided already TLE from a previously added test case!
