### ISSUE TITLE
Faulty example in question - 1056. Confusing Number

### ISSUE THREAD

**Issue by anmolbhatia05** [LeetCode-Feedback/LeetCode-Feedback#6684]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @anmolbhatia05 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
