### ISSUE TITLE
test case bug: 420. Strong Password Checker 

### ISSUE THREAD

**Issue by xgqfrms** [LeetCode-Feedback/LeetCode-Feedback#6685]
#### Your LeetCode username
xgqfrrms

#### Category of the bug
- [ ] Question
- [ ] Solution

- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

 test case bug, it's just only needed one step.

`"aaa111"` => `"Aaa111"`

`"aaa111"` => `"Baa111"`

In one step, you can:

Insert one character to password,
Delete one character from password, or
`Replace one character of password with another character.`

#### Code you used for Submit/Run operation

```js
"aaa111"
Output
1
Expected
2
```

#### Language used for code
JavaScript

#### Expected behavior

```js
"aaa111"
Output
1
Expected
1
```

#### Screenshots

# test case bug: 420. Strong Password Checker 

![image](https://user-images.githubusercontent.com/7291672/157896191-479f4876-3ccf-48c0-a502-2469eedad34b.png)

#### Additional context

https://leetcode.com/problems/strong-password-checker/discuss/1839991/test-case-error

**Comment by stormsunshine** [comment]
Please check the definition of a string password. No three repeating characters are allowed, so a letter 'a' and a digit '1' need to be changed, and the minimum number of steps is 2.

**Comment by xgqfrms** [comment]
No three repeating characters are allowed，meanings it not include the number [0-9].

**Comment by xgqfrms** [comment]
@xgqfrms  `1337C0d3` !== `13337C0d`

> more detailed description wanted.

 `...333...` is weak, but `...33...3...`  is strong;
