### ISSUE TITLE
Program crash if the pointers are deleted - 1836. Remove Duplicates From an Unsorted Linked List

### ISSUE THREAD

**Issue by supertim-chen** [LeetCode-Feedback/LeetCode-Feedback#6686]
Your LeetCode username
supertim_chen

Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
If the erased nodes are deleted to avoid the memory leakages, the program crash.

Code you used for Submit/Run operation
```
// The code below is not the solution of this problem.
// It is designed to reproduce this issue.
// It removes all list nodes and return an empty list then the program crash.

class Solution {
public:
  ListNode * deleteDuplicatesUnsorted(ListNode * head) {
    ListNode * next;
    for (auto node = head; NULL != node; node = next) {
      next = node->next;
      delete node;  //// If this line is commented out, the program won't crash
    }

    return NULL;
  }
};
```

Language used for code
C++

Expected behavior
The program should not crash if the pointer of the removed list node is deleted.

**Comment by gtp97** [comment]
Same problem here:
https://leetcode.com/problems/remove-duplicates-from-an-unsorted-linked-list/discuss/1948136/Crash-when-trying-to-delete-head-node
It just crashes when I try to free the head node.
