### ISSUE TITLE
Casing issue while importing Queue.

### ISSUE THREAD

**Issue by sugeeth14** [LeetCode-Feedback/LeetCode-Feedback#6690]
#### Your LeetCode username
sugeeth14

#### Category of the bug
- [ ] Question
- [x] Solution - Issue here.
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the problem MergeKsortedLists's [solution](https://leetcode.com/problems/merge-k-sorted-lists/solution/) in approach 3 using Priority Queue, the Priority Queue is imported as 
`from Queue import PriorityQueue `
but instead it should be 
`from queue import PriorityQueue`
this is causing a `ModuleNotFoundError`

#### Language used for code
Python

#### Expected behavior
The code should run without errors.

#### Screenshots

<img width="751" alt="Screen Shot 2022-03-11 at 6 17 37 PM" src="https://user-images.githubusercontent.com/22686557/157998389-dc808341-1773-4d75-b78e-ae528be299c9.png">

<img width="670" alt="Screen Shot 2022-03-11 at 6 33 50 PM" src="https://user-images.githubusercontent.com/22686557/157998423-2887c7e0-5138-42fc-a234-1fd351443162.png">

**Comment by LC-Sue** [comment]
Hi @sugeeth14,
Thank you for reaching out to us, the solution code runs with no issue. Please refer to the screenshot below for reference! 
![image](https://user-images.githubusercontent.com/92285126/158907735-7bcc5bcc-8cba-41ff-987d-fbd164c5dea8.png)
