### ISSUE TITLE
Runtime error while running solution.

### ISSUE THREAD

**Issue by sugeeth14** [LeetCode-Feedback/LeetCode-Feedback#6691]
#### Your LeetCode username
sugeeth14

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
With reference to the issue [here](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/6690), for the same question, even when `Queue` is replaced with `queue` in the import it leads to the below error. 
```
TypeError: '<' not supported between instances of 'ListNode' and 'ListNode'
    heappush(self.queue, item)
Line 236 in _put (/usr/lib/python3.10/queue.py)
    self._put(item)
Line 150 in put (/usr/lib/python3.10/queue.py)
    q.put((l.val, l))
Line 18 in mergeKLists (Solution.py)
    ret = Solution().mergeKLists(param_1)
Line 47 in _driver (Solution.py)
    _driver()
Line 58 in <module> (Solution.py)
```

#### Code you used for Submit/Run operation
```
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
from queue import PriorityQueue

class Solution(object):
    def mergeKLists(self, lists):
        """
        :type lists: List[ListNode]
        :rtype: ListNode
        """
        head = point = ListNode(0)
        q = PriorityQueue()
        for l in lists:
            if l:
                q.put((l.val, l))
        while not q.empty():
            val, node = q.get()
            point.next = ListNode(val)
            point = point.next
            node = node.next
            if node:
                q.put((node.val, node))
        return head.next
```

        

#### Language used for code
Python

#### Expected behavior
The solution should run without errors.

#### Screenshots

<img width="748" alt="Screen Shot 2022-03-11 at 6 37 44 PM" src="https://user-images.githubusercontent.com/22686557/157998601-47e91f0d-7d1c-430d-a3b9-ba10b8e933e8.png">

**Comment by LC-Sue** [comment]
Hi @sugeeth14,
Thank you for reaching out to us, it seems like you've created a duplicate issue. We've responded to your previous issue!
