### ISSUE TITLE
Line 26: Char 19: undefined: Deserializer (solution.go)

### ISSUE THREAD

**Issue by And-ZJ** [LeetCode-Feedback/LeetCode-Feedback#6693]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
And-ZJ

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例
- [x] 编译出错

**描述**
描述你遇到的 bug

703 题: https://leetcode-cn.com/problems/kth-largest-element-in-a-stream/

使用Go语言，提交如下代码：

```go
type KthLargest struct {

}

type TreeNode struct {
    
}

func Constructor(k int, nums []int) KthLargest {
    var kth KthLargest
    return kth
}


func (this *KthLargest) Add(val int) int {
    return 0
}



/**
 * Your KthLargest object will be instantiated and called as such:
 * obj := Constructor(k, nums);
 * param_1 := obj.Add(val);
 */
```
得到如下错误：
```
Line 26: Char 19: undefined: Deserializer (solution.go)
Line 31: Char 36: undefined: Deserializer (solution.go)
Line 32: Char 34: undefined: Serializer (solution.go)
Line 43: Char 28: undefined: Deserializer (solution.go)
Line 102: Char 25: undefined: Deserializer (solution.go)
```
我只是新增了一个 TreeNode struct 而已呀，当然如果换一个名字，比如 TreeNode1 就不会报错：
```go
type TreeNode struct {
    
}
```
**你使用的语言**
Go

**你提交或者运行的代码**
已在上方列出

**期望行为**
描述你期望的结果
编译通过

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/9165501/158009209-59fa3a54-19d2-4e4b-91e2-a1b8c7fb3207.png)

**额外的上下文**
添加额外的上下文信息
无

**Comment by Yesuyang** [comment]
不能定义leetcode内部定义的结构体，如ListNode，TreeNode

**Comment by ShiYuForever** [comment]
看来还没有解决呀？我也碰到这个问题了，写LRU的时候

**Comment by spike014** [comment]
707 定义 `ListNode` 同样报错。

```
Line 76: Char 19: undefined: Deserializer (solution.go)
Line 81: Char 36: undefined: Deserializer (solution.go)
Line 82: Char 34: undefined: Serializer (solution.go)
Line 86: Char 36: undefined: Deserializer (solution.go)
Line 90: Char 36: undefined: Deserializer (solution.go)
Line 94: Char 36: undefined: Deserializer (solution.go)
Line 99: Char 36: undefined: Deserializer (solution.go)
Line 167: Char 25: undefined: Deserializer (solution.go)
```

**Comment by spike014** [comment]
> 707 定义 `ListNode` 同样报错。
> 
> ```
> Line 76: Char 19: undefined: Deserializer (solution.go)
> Line 81: Char 36: undefined: Deserializer (solution.go)
> Line 82: Char 34: undefined: Serializer (solution.go)
> Line 86: Char 36: undefined: Deserializer (solution.go)
> Line 90: Char 36: undefined: Deserializer (solution.go)
> Line 94: Char 36: undefined: Deserializer (solution.go)
> Line 99: Char 36: undefined: Deserializer (solution.go)
> Line 167: Char 25: undefined: Deserializer (solution.go)
> ```

改为 `Node` 即可，**不**与官方之前定义的 `struct` 相同即可

**Comment by cyadav18** [comment]
**The problem is that you are trying to use the same variable defined in the solution file, try changing the variable name or class name. it should work**
