### ISSUE TITLE
Calculation mistake in Editorial of problem 150. Evaluate Reverse Polish Notation

### ISSUE THREAD

**Issue by shubamg** [LeetCode-Feedback/LeetCode-Feedback#6694]
#### Your LeetCode username
shubamg

#### Category of the bug
- [ ] Question
- [x] Solution (Editorial)
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the editorial, it is mentioned that `29 - 1.66 = 28.33`, which is incorrect. Correct answer is ~~27.33~~ `27.34` (Thanks to @stormsunshine ) . Please look at the screenshots attached

#### Language used for code

Python

#### Screenshots

![image](https://user-images.githubusercontent.com/4509049/158013636-87409f54-ee22-41f1-a43a-da9924c9bf8a.png)

**Comment by stormsunshine** [comment]
The correct result should be 27.34.

**Comment by LC-Sue** [comment]
Hi @shubamg 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
