### ISSUE TITLE
Improved Constraints - 1305. All Elements in Two Binary Search Trees

### ISSUE THREAD

**Issue by kalyanironak** [LeetCode-Feedback/LeetCode-Feedback#6696]
#### context
Since the problem can be solved in O(n) time, Constraints can be made more strict. Currently, Input constraints look like below:

Constraints:

The number of nodes in each tree is in the range [0, 5000].
-10^5 <= Node.val <= 10^5

However, The number of nodes in each tree could have been in the range of [0, 10^7]. So that if someone implements solution in O(n log n), it would result in TLE. Currently it allows O(n log n) as well to pass through.

**Comment by LC-Sue** [comment]
Hi @kalyanironak 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kalyanironak 
Thank you for your time. The team reviewed your report and we intentionally allow nlogn solutions. No need to fail them. We appreciate your support!
