### ISSUE TITLE
Interface improvement suggestion for Study Plan

### ISSUE THREAD

**Issue by cathysarisky** [LeetCode-Feedback/LeetCode-Feedback#6698]
#### Your LeetCode username
catsarisky

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Things that would make my life better

#### Description of the bug

Feature request: Make it easier to see from https://leetcode.com/study-plan/ whether the user has any daily problems unlocked but not completed.

I signed myself up for two study plans at once, and it's annoying to need to look in both to remember if I have any problems left undone, especially since I often do half the night they unlock and the other half the next morning.

Below are two terribly-executed mock-ups of what I wish it looked like:

![image](https://user-images.githubusercontent.com/42299862/158026675-6974b1ad-247a-4109-9eab-215bfaa811b1.png)

**Comment by LC-Sue** [comment]
Hi @cathysarisky,
Thank you for reaching out to us, I've relayed this feedback over to our team for improvements in future iterations!
