### ISSUE TITLE
principle-of-recursion the solution will not work

### ISSUE THREAD

**Issue by krlinus** [LeetCode-Feedback/LeetCode-Feedback#6699]
Reversal of pairs in linked list:
convert
1->2->3->4
to
2->1->4->3

The 4->3 part needs to be done first so that pointer to 4 becomes available, which can be assigned to 1.next
The explanation says to swap 1 and 2 first, without 4 being available.
Below is the link to the page:
https://leetcode.com/explore/featured/card/recursion-i/250/principle-of-recursion/1680/

**Comment by LC-Sue** [comment]
Hi @krlinus 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
