### ISSUE TITLE
Simplify Path broken link in content

### ISSUE THREAD

**Issue by bissahoo** [LeetCode-Feedback/LeetCode-Feedback#67]
**Broken link in the cotent**
- [x] problem

**Describe the bug**
Hyperlink  (Absolute path vs relative path in Linux/Unix points) to URL(https://www.linuxnix.com/abslute-path-vs-relative-path-in-linuxunix/) which gives database connection error.

**Screenshots**
Please see the attached screenshot for details:

![leet_code_broken_link](https://user-images.githubusercontent.com/39652914/77272912-556a7f80-6cd8-11ea-8297-c38eec875025.PNG)

**Comment by CooperCooperCooper** [comment]
Hi @bissahoo,
Thank you for reaching out to us! Since this issue is related to some other parts of our system, please share this issue with our other support channel here: https://support.leetcode.com/hc/en-us. We appreciate your time and support.

**Comment by CooperCooperCooper** [comment]
Hi @bissahoo,
My apologies. You're correct that this is a content issue. I've relayed it to our team to fix.

**Comment by CooperCooperCooper** [comment]
Hi @bissahoo,
Thank you for your time! Since the issue from the link was out of our scope, we've removed the link and updated the description. Please check it out :)

**Comment by bissahoo** [comment]
Perfect. Thanks mate!
