### ISSUE TITLE
Missing test case - 1497. Check If Array Pairs Are Divisible by k

### ISSUE THREAD

**Issue by Bolshem** [LeetCode-Feedback/LeetCode-Feedback#670]
#### Your LeetCode username
Losty

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The wrong solution accepted

Input [8,6,3,3] 
k = 5

Input can't be split to pairs divisible by 5.

#### Code you used for Submit/Run operation

The following solution is accepted (Python):

The solution just calculates the sum of the array and checks that all sum is divisible by k.
```


class Solution(object):
    def canArrange(self, arr, k):
        """
        :type arr: List[int]
        :type k: int
        :rtype: bool
        """
        sumArr = abs(sum(arr))
        return sumArr == 0 or (sumArr > k and sumArr % k == 0)
```

#### Expected behavior
Fail to be accepted

**Comment by lc-christina** [comment]
Hi @Bolshem 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @Bolshem 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
