### ISSUE TITLE
393. UTF-8 编码验证 测试用例错误

### ISSUE THREAD

**Issue by bestcondition** [LeetCode-Feedback/LeetCode-Feedback#6702]
**你的 LeetCode 用户名**
bestcondition

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
测试用例错误

测试用例第41个出错，

[194,155,231,184,185,246,176,131,161,222,174,227,162,134,241,154,168,185,218,178,229,187,139,246,178,187,139,204,146,225,148,179,245,139,172,134,193,156,233,131,154,240,166,188,190,216,150,230,145,144,240,167,140,163,221,190,238,168,139,241,154,159,164,199,170,224,173,140,244,182,143,134,206,181,227,172,141,241,146,159,170,202,134,230,142,163,244,172,140,191]

其中[5:9]也就是[246,176,131,161]编码之后的十六进制为'1b00e1'，显然不在0001 0000-0010 FFFF的范围

题目出的不严谨，如果加上一句不验证范围就好了

**你使用的语言**
python

**你提交或者运行的代码**
```python
class Solution:
    def validUtf8(self, data: List[int]) -> bool:
        try:
            bytes(data).decode('utf-8')
            return True
        except:
            return False
```

**期望行为**
题目描述添加不验证范围，或者更改测试用例，把范围也考虑上

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
>这是 UTF-8 编码的工作方式：
>
>   Char. number range  |        UTF-8 octet sequence
>      (hexadecimal)    |              (binary)
>   --------------------+---------------------------------------------
>   0000 0000-0000 007F | 0xxxxxxx
>   0000 0080-0000 07FF | 110xxxxx 10xxxxxx
>   0000 0800-0000 FFFF | 1110xxxx 10xxxxxx 10xxxxxx
>   0001 0000-0010 FFFF | 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
>
>来源：力扣（LeetCode）
>链接：https://leetcode-cn.com/problems/utf-8-validation
>著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：bestcondition 给予积分奖励，请查收。
