### ISSUE TITLE
Missing Test Case - 941. Valid Mountain Array

### ISSUE THREAD

**Issue by rameshmp007** [LeetCode-Feedback/LeetCode-Feedback#6703]
#### Your LeetCode username

pawarramesh2001

#### Category of the bug
- [x] Missing Test Cases 

- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

When the Mountain array has two equal max elements. Then it is not a mountain array.

#### Code you used for Submit/Run operation

```
// Valid Mountain Array
class Solution {
    
    public boolean validMountainArray(int[] arr) {
        
        if(arr.length < 3) 
            return false;

        int max = arr[0];
        int indexOfMax = 0;
        
        for(int i = 1; i < arr.length; i++) {
            if(arr[i] > max) {
                max = arr[i];
                indexOfMax = i;
            }
        }
        
        if(indexOfMax == 0 || indexOfMax == arr.length - 1) {
            return false;
        }
        
        if(isMountain(arr, max, indexOfMax)) {
            return true;
        }
    
        return false;
    }

    public boolean isMountain(int[] arr, int max, int indexOfMax) {
        
        boolean ans = true;
        
        for(int i = 0; i < arr.length; i++) {
               
            if(i < indexOfMax && arr[i] >= arr[i + 1]  ) {
                return false;
            }
            else if(i > indexOfMax && arr[i - 1] <= arr[i] ) {
                return false;
            }
            //else if(arr[i] == max && i != indexOfMax) { //Uncomment these 3 lines for solution
                //return false; 
            //}
            else
                ans = true;
        }
        
        return ans;
        
    }
}
};
```

#### Language used for code

Java

#### Screenshots

![image](https://user-images.githubusercontent.com/73076788/158049173-00cf54aa-521e-48a3-9070-ba97965b3f1c.png)

#### Additional context

If we run the Code directly without Uncommenting them. It will run. But I think there is a test case missing which can be added to check for answers correctly.
Hope you will add the test case soon Thank You.

**Comment by LC-Sue** [comment]
Hi @rameshmp007,
Thank you for reaching out to us, the custom test case you provided is accepted with the code you provided, so we will not be adding the test case!
