### ISSUE TITLE
Different Result between Submissions and Console's Result - 97. Interleaving String

### ISSUE THREAD

**Issue by Hide-on-bush2** [LeetCode-Feedback/LeetCode-Feedback#6704]
## Result from Submission

![](https://tva1.sinaimg.cn/large/e6c9d24egy1h08dgqls8kj20zg0bg3z0.jpg)

## Result from Console

![](https://tva1.sinaimg.cn/large/e6c9d24egy1h08dgorrn5j215i0e4wf9.jpg)

## Result from Local Test

The result is the same as the result from console.

**Comment by Hide-on-bush2** [comment]
The test case is the same.

**Comment by LC-Sue** [comment]
Hi @Hide-on-bush2 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
