### ISSUE TITLE
Missing Test Case - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by hntddt123** [LeetCode-Feedback/LeetCode-Feedback#6707]
#### Your LeetCode username
hntddt1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

What should be expected output for the following test case
For my understanding the product is from 2 numbers in an array
The edge case is difficult to handle then the question probably should say 
"if no product found return the largest number in the sub array"
"if only 1 number in array then return the number"

[-3, 0, 1, -2] expected 0 but in LeetCode test is 1
[-2,0,1] 1 expected 0 but in LeetCode test is 1
[4] 4 expected 0 but in LeetCode test is 4
[1, 0] expected 0 but in LeetCode test is 1
[-2] expected 0 but in LeetCode test is -2

#### Code you used for Submit/Run operation
```
export let maxProduct = function (nums) {
  if (nums.length === 1) return 0;

  let postiveProductMax = 0;
  let negativeProductMin = 0;
  let maxProduct = 0;

  for (const num of nums) {
    let previousPostiveProductMax = postiveProductMax;

    postiveProductMax = getPositiveProductMax(num, postiveProductMax, negativeProductMin)
    negativeProductMin = getPositiveProductMin(num, previousPostiveProductMax, negativeProductMin);
  
    maxProduct = Math.max(maxProduct, postiveProductMax);
  }

  return maxProduct;
};

function getPositiveProductMin(num, postiveProductMax, negativeProductMin) {
  return Math.min(
    num,
    postiveProductMax * num,
    negativeProductMin * num
  );
}

function getPositiveProductMax(num, postiveProductMax, negativeProductMin) {
  return Math.max(
    num,
    postiveProductMax * num,
    negativeProductMin * num
  );
}```

#### Language used for code
JavaScript

#### Expected behavior
N/A


#### Screenshots
N/A


#### Additional context
N/A

**Comment by stormsunshine** [comment]
Your understanding of the problem description is incorrect. This problem requires finding a contiguous non-empty subarray with the maximum product among all elements in the subarray, and returning the product, not returning the product of two elements.

[-3, 0, 1, -2] has subarray [1] with maximum product 1.
[-2, 0, 1] has subarray [1] with maximum product 1.
[4] has subarray [4] with maximum product 4.
[1, 0] has subarray [1] with maximum product 1.
[-2] has subarray [-2] with maximum product -2.

**Comment by LC-Sue** [comment]
Hi @hntddt123,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Please feel free to reach out if you have any other questions!

**Comment by kyruzic** [comment]
A product is defined as the result of multiplication, a single number cannot be considered a product. If this is the idea at least make this clear in the question description by giving these as examples.
