### ISSUE TITLE
Solution - Reverse String

### ISSUE THREAD

**Issue by MagnificRogue** [LeetCode-Feedback/LeetCode-Feedback#6708]
#### Your LeetCode username
MagnificRogue

#### Category of the bug
- [X ] Solution

#### Description of the bug
Going through the Principle of Recursion, there is a solution for reversing a string in place that calls for a constant amount of memory (O(1)). [Solution in question](https://leetcode.com/explore/learn/card/recursion-i/250/principle-of-recursion/1679/). The issue with the solution presented is the memory is O(N/2) if you account for the stack frames to manage the recursive calls.

**Comment by LC-Sue** [comment]
Hi @MagnificRogue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
