### ISSUE TITLE
220. Contains Duplicate III — possibly incorrect test case

### ISSUE THREAD

**Issue by Cassandra-d** [LeetCode-Feedback/LeetCode-Feedback#671]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
For the Contains Duplicate III task, one of test cases is run with the next parameters:
Array: [-1,-1], k = 1, t = -1.
Currently the expected result for that test case is: false.
Task description says: “Given an array of integers, find out whether there are two distinct indices i and j in the array such that the absolute difference between nums[i] and nums[j] is at most t”...

#### Expected behavior
As the task is called Contains **Duplicate** and some values of input array are actually **equal** (-1 and -1), I think that the mentioned test case should expect return value — true, for array of [-1, -1].

#### Screenshots

![image](https://user-images.githubusercontent.com/2866070/88081924-c12aff00-cb89-11ea-9677-68eb9e21073e.png)

**Comment by lc-christina** [comment]
Hi @Cassandra-d ,
Thanks for reaching out to us. Please note that the problems ask for 'absolute difference'. The absolute difference between -1 and -1 is 0, not -1.

**Comment by Cassandra-d** [comment]
> Hi @Cassandra-d ,
> Thanks for reaching out to us. Please note that the problems ask for 'absolute difference'. The absolute difference between -1 and -1 is 0, not -1.

Can we say then that for every test case where “t” is negative we should always return “false”?
As I'm looking at the definition of [absolute difference](https://mathworld.wolfram.com/AbsoluteDifference.html) and it looks like it always should be a non-negative value.

Or is the test case does not follow arithmetic definition of absolute difference?

**Comment by lc-pam** [comment]
@Cassandra-d 
I apologize if I misunderstood your meaning. The screenshot you provided showed the expected result is false because it has a negative value for absolute different and it follows the arithmetic definition.
