### ISSUE TITLE
Missing Test Case - 278. First Bad Version

### ISSUE THREAD

**Issue by imkevinjoseph** [LeetCode-Feedback/LeetCode-Feedback#6711]
#### Your LeetCode username
pecuniam1

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The instructions say that the api call is to isBadVersion(), but it's actually IsBadVersion (with a capital I)

#### Code you used for Submit/Run operation

```
public int FirstBadVersion(int n) {        
       int start = 0;
		int end = n;
		int answer = 0;
		while(start <= end) {
			int mid = start + (end - start) / 2;
			if (isBadVersion(mid)) {
				answer = mid;
				end = mid-1;
			} else
				start = mid+1;
		}
		return answer;
    }
```

#### Language used for code
C#

#### Expected behavior
The instructions state that the api call is isBadVersion(), but the actual api call is IsBadVersion(). The former starting with a lowercase i, while the latter starting with an uppercase I. I expect that the instructions should be updated to reference proper spelling of the method call, or I expect that the instructions are updated to correctly use IsBadVersion()

#### Screenshots
![Capture](https://user-images.githubusercontent.com/79548776/158188074-ba822fee-92c2-4a2e-a735-5252bbe92303.PNG)

**Comment by stormsunshine** [comment]
For other languages, the method/function name is "isBadVersion" that starts with a lowercase letter i. Only C# has method names starting with uppercase letters. If the instruction is changed to "IsBadVersion", then it is inconsistent with other languages.

**Comment by LC-Sue** [comment]
Hi @imkevinjoseph,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts. Please feel free to reach out again if you have any other questions!
