### ISSUE TITLE
Error in Explanation in Solution article for "range sum of bst"

### ISSUE THREAD

**Issue by stephenfrench9** [LeetCode-Feedback/LeetCode-Feedback#6716]
#### Your LeetCode username
stephenfrench9

<img width="681" alt="Screen Shot 2022-03-14 at 9 37 38 AM" src="https://user-images.githubusercontent.com/22377178/158219017-26c306ce-9c68-4f23-b75b-699925422dd2.png">

#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ x ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[The solution for "Range Sum of BST"](https://leetcode.com/problems/range-sum-of-bst/solution/) has an error. The code is doing a DFS, but the solution says BFS. (The code is using ".append" and ".pop". This means that the most recently added node will be explored. Children are always the most recently added. Stack <-> DFS. Queue <-> BFS, right?

#### Language used for code

python

**Comment by LC-Sue** [comment]
Hi @stephenfrench9 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stephenfrench9** [comment]
ok great thanks, let me know!

**Comment by LC-Sue** [comment]
Hi @stephenfrench9 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by stephenfrench9** [comment]
Thanks for letting me know @LC-Sue! 

I just checked and I see the correction! It looks good to me:

"For the recursive and iterative implementations, we are performing a DFS (Depth-First Search) traversal...."  👍🙂
