### ISSUE TITLE
Missing Test Case - 2116. Check if a Parentheses String Can Be Valid

### ISSUE THREAD

**Issue by nazir098** [LeetCode-Feedback/LeetCode-Feedback#6717]
#### Your LeetCode username

nazir1

#### Category of the bug
- [ ] Missing Test Cases 
 "(()())"
 "001110"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @nazir098 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
