### ISSUE TITLE
Incorrect arg typing in Python 3 template - 271. Encode and Decode Strings

### ISSUE THREAD

**Issue by ytingyeu** [LeetCode-Feedback/LeetCode-Feedback#6718]
#### Your LeetCode username
ytingyeu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
Currently the solution template of Python 3 uses `[]` expression to type argument `strs`.
```python
def encode(self, strs: [str]) -> str:
    pass

def decode(self, s: str) -> [str]:
    pass
```

#### Language used for code
Python 3

#### Expected behavior

I suppose it should use `typing.List` instead.
```python
def encode(self, strs: List[str]) -> str:
    pass

def decode(self, s: str) -> List[str]:
    pass
```

#### Screenshots

![271 screenshot](https://raw.githubusercontent.com/ytingyeu/report-issue-examples/master/leetcode-271-py3-typing/screenshot.png)

**Comment by LC-Sue** [comment]
Hi @ytingyeu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
