### ISSUE TITLE
497. Random Point in Non-overlapping Rectangles

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#672]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Broken formatting in solution

#### Expected behavior

> Let \text{tot} = \sum_\limits{i=0}^{N-1}w[i], where N = \text{len}(w)N=len(w).
> 
> Compute the prefix sum array pp, where p[x] = \sum_\limits{i=0}^{x}w[i].

This is in the solution text

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
