### ISSUE TITLE
Missing Test Case - 278. First Bad Version - Satyam Dixit - stymdxt

### ISSUE THREAD

**Issue by stymdxt** [LeetCode-Feedback/LeetCode-Feedback#6720]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

You are a product manager and currently leading a team to develop a new product. Unfortunately, the latest version of your product fails the quality check. Since each version is developed based on the previous version, all the versions after a bad version are also bad.

Suppose you have n versions [1, 2, ..., n] and you want to find out the first bad one, which causes all the following ones to be bad.

You are given an API bool isBadVersion(version) which returns whether version is bad. Implement a function to find the first bad version. You should minimize the number of calls to the API.

 

Example 1:

Input: n = 5, bad = 4
Output: 4
Explanation:
call isBadVersion(3) -> false
call isBadVersion(5) -> true
call isBadVersion(4) -> true
Then 4 is the first bad version.
Example 2:

Input: n = 1, bad = 1
Output: 1

#### Code you used for Submit/Run operation

```
# The isBadVersion API is already defined for you.
# def isBadVersion(version: int) -> bool:

class Solution:
    def firstBadVersion(self, n: int) -> int:
        
        first = 1
        last = n
        
        while first<last:
            mid = first + (last-first) // 2
            if isBadVersion(mid) is True:
                last = mid    
            else:
                first = mid +1
        return last
    
```

#### Expected behavior

To find out the first bad one, which causes all the following ones to be bad.

**Comment by LC-Sue** [comment]
Hi @stymdxt 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
