### ISSUE TITLE
Missing Test Case - 28. Implement strStr()

### ISSUE THREAD

**Issue by abhinandanmishra1** [LeetCode-Feedback/LeetCode-Feedback#6724]
#### Your LeetCode username
abhinandan_mishra_1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There is only one test case present in the problem in which the size of the pattern (or size of second-string) is zero.
The test case present in the problem is - 
**Input**
``` "a" "" ```
**Expected Output**
```0```

But there is no other test case in which the second string is empty. 

#### Code you used for Submit/Run operation

```
// Implement strStr()
class Solution {
public:
    int strStr(string s1, string s2) {
        // as per questions s1 is haystack and s2 is needle
       if((s1.size()==1 and s2.length()<=1) or (s1.length()==0 and s2.length()==0)) return 0;
       string tot=s2+"$"+s1;
       int n=tot.length();
        vector<int> store(n,0);
        int l=0,r=0;
       
        for(int i=0;i<n;i++){
            if(i>r){
                l=i,r=i;
                while(r<n and tot[r]==tot[r-l]) r++;
                store[i]=r-l;
                r--;
            }else{
                int ind=i-l;
                if(i+store[ind]<=r) store[i]=store[ind];
                else{
                    l=i;
                    while(r<n and tot[r]==tot[r-l]) r++;
                    store[i]=r-l;
                    r--;
                }
            }
        }
        for(int i=0;i<n;i++){
            if(store[i]==s2.length()){
                return i-s2.length()-1;
            }
        }
        return -1;
    }
};
```

#### Language used for code
C++

#### Expected behavior
My code is wrong because it's not handling all the cases where the second string is empty and in that case, it should return 0 but it is returning -1.

For example for the test case - 
**Input**
``` 
"abcdefg" 
"" 
```
**Expected Output**
``` 0 ```

**Output** (from my code)
```-1```
As my code is giving the wrong answer it shouldn't be accepted but it got accepted.

#### Screenshots
**My solution Got accepted**
![Screenshot (2)](https://user-images.githubusercontent.com/64205626/158527095-a623e7d6-a8b0-4791-88d6-3f02f3f2c032.png)

**But my solution is giving wrong output for the given testcases**

![TestCase1](https://user-images.githubusercontent.com/64205626/158527107-85adf065-9e1a-4ea5-8ce6-28e3b457e847.png)

![TestCase2](https://user-images.githubusercontent.com/64205626/158527115-c9426554-2bf9-490a-b022-4f7ede41e311.png)

#### Additional context
- Add more test cases in which the second string is empty.
- I'm suggesting some test cases from my side.
- Testcase 1
``` 
"abcdefghijklmnopqrtsuvwxyz"
""
```
- Testcase 2
``` 
"qwertyuiopasdfghjklzxcvbnm"
""
```
- Testcase 3
``` 
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
""
```
- Testcase 4
``` 
"abababababababababababab"
""
```
- Testcase 5
``` 
"aaaaaannnnnnnnnnaaaaannnnnn"
""
```

**Comment by LC-Sue** [comment]
Hi @abhinandanmishra1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by abhinandanmishra1** [comment]
I thought I will be getting some coins 😅 but anyways I'm happy to help and improve quality of leetcode.
