### ISSUE TITLE
Missing Test Case - 560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by gaurav459-sharma** [LeetCode-Feedback/LeetCode-Feedback#6725]
#### Your LeetCode username
gauravsharma459

#### Category of the bug
-  560.subarray sum equals to k
-  include the test case ->  nums=[1,4,-1,1],k=5  In leetcode there is no test case in which one or more subarray is possible in one subarray i.e in above test case subarray whose sum equals to k is- [1,4], [1,4,1,-1]
- c++
- [1,4,-1,1], k=5

#### Description of the bug
In the problem 560. Subarray sum equals to k when i submitted my answer it is successfully submitted but there is one test case which is-->  nums=[1,4,-1,1],k=5 for this test case my answer is wrong but it is completely submitted

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int subarraySum(vector<int>& nums, int k) {
        int count=0;
        
        for(int i=0;i<nums.size();i++){
            int tmp=k;
            for(int j=i;j<nums.size();j++){
               
                if(nums[j]==tmp){
                    count++;
                    break;
                }
               
                tmp=tmp-nums[j];

            }
        }
        return count;
    }
};
```

```


#### Language used for code
 C++ 


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
I expected that my program is not submitted for this test case  nums=[1,4,-1,1],k=5
But my program is successfully submitted( i think there is some test cases are missing in one or more continuos subarray is possible  )



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Sue** [comment]
Hi @gaurav459-sharma,
Thank you for reaching out to us, the code you provided returns wrong answer now!
