### ISSUE TITLE
282. Expression Add Operators

### ISSUE THREAD

**Issue by chocolatefudge** [LeetCode-Feedback/LeetCode-Feedback#6726]
#### Your LeetCode username

Komfkore

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I am wondering about the definition of "leading zero" in the question definition. 
Exactly what number is considered a leading zero? 

#### Code you used for Submit/Run operation

```
def addOperators(self, num: str, target: int) -> List[str]:
        res = []
        # num+= "#"
        
        def rec(ptr, curEval, interim, curr, op, curPath):
            if ptr<len(num)-1:
                rec(ptr+1, curEval, interim, curr*10+int(num[ptr]), op, curPath+[num[ptr]])
            
            number = curr*10+int(num[ptr])
            if op in ["+", "-"]:
                curEval += interim
                if op == "-":
                    interim = -number
                else:
                    interim = number
            else:
                if op == "*":
                    interim *= number
                else:
                    if number == 0:
                        return
                    interim = int(interim/number)
            if ptr == len(num)-1:
                curEval += interim
                if curEval == target:
                    curPath.append(str(number))
                    res.append("".join(curPath))
                    curPath.pop()
                return
            for newOp in ["+", "-", "*", "/"]:
                curPath.append(num[ptr]+newOp)
                rec(ptr+1, curEval, interim, 0, newOp, curPath)
                curPath.pop()
            return
                
        rec(0, 0, 0, 0, "+", [])
        return res
```

#### Language used for code
Python3

#### Expected behavior
For below testcases, upper one has +0 and -0 in the answer. 
However, for testcase2), it is considered as infeasible even though 9191 can be formed the very same way we formed 9192. 
Therefore, I think we need better definition of what should be a leading zero in the question. 

1)
"3456237490"
9192
answer: ["3x4-5+62x37x4+9+0","3x4-5+62x37x4+9-0"]

2)
"3456237490"
9191
answer: []
 ==> Why not ["34/5+62x37x4+9+0","34/5+62x37x4+9-0"] ?

(I've changed * to x for readability)

**Comment by stormsunshine** [comment]
Division is not allowed.
