### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by vaibhav4859** [LeetCode-Feedback/LeetCode-Feedback#6727]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✅] Missing Test Cases 

#### Description of the bug

Missing Test case : "({)}"
This is a valid test case which must return true as all type of opening parentheses have their respective closing parentheses
but instead this question returns false !

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isValid(string s) {
        
    stack<char> st;
    
    for(int idx = 0; idx < s.size(); idx++){
        char ch = s[idx];
        
        if(st.size() > 0){
            if(ch == '(' || ch == '{' || ch == '[')
                st.push(ch);

            else if (ch == ')' && st.top() == '(')
                st.pop();

             else if (ch == '}' && st.top() == '{')
                st.pop();

            else if (ch == ']' && st.top() == '[')
                st.pop();
            else
                st.push(ch);
        
        }
        else st.push(ch);
        
    }
    
    if(st.size() == 0)
        return true;
    else 
        return false;
    }
};
```

#### Expected behavior

This is a valid test case which must return true as all type of opening parentheses have their respective closing parentheses
but instead this question returns false !

#### Screenshots

![Screenshot (22)](https://user-images.githubusercontent.com/91424292/158640744-ddd37a38-132d-48f0-976f-f6b7084d9af1.png)
I expected true here  but instead I got false !

**Comment by stormsunshine** [comment]
Did you see that open brackets must be closed in the correct order?

For input string "({)}", the correct order should be '}' before ')', but in the string, ')' is before '}', so the order is incorrect. Why do you think a string with incorrect order should return true?

**Comment by LC-Sue** [comment]
Hi @vaibhav4859
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Please feel free to reach out again to ask any other questions!
