### ISSUE TITLE
124. Binary Tree Maximum Path Sum

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#673]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 1: Recursion has incorrect analysis

#### Expected behavior

> Space complexity : O(log(N)). We have to keep a recursion stack of the size of the tree height, which is O(log(N)) for the binary tree.

Should be O(h) which in worst case can be O(n)

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
