### ISSUE TITLE
Find Nearest Point That Has the Same X or Y Coordinate

### ISSUE THREAD

**Issue by Limitless741** [LeetCode-Feedback/LeetCode-Feedback#6731]
![image](https://user-images.githubusercontent.com/92598649/158747192-73e0528f-de67-40b9-97f5-12105160eb03.png)
why is the expected answer zero here?
shouldnt it be  2?

**Comment by stormsunshine** [comment]
The nearest point to (1, 1) is (1, 2), not (3, 3), so return the index of (1, 2), which is 0. Is there any problem?

**Comment by LC-Sue** [comment]
Hi @Limitless741,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Please feel free to reach out again to ask any other questions!
