### ISSUE TITLE
有错误的测试用例

### ISSUE THREAD

**Issue by bboysteed** [LeetCode-Feedback/LeetCode-Feedback#6732]
**你的 LeetCode 用户名**
mang-1e

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
![114](https://user-images.githubusercontent.com/45219937/158761835-27e87c81-3e43-460e-8809-af9b36616d47.png)
这个测试用例有问题，期望的结果是错误的

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    vector<int> partitionLabels(string s) {
        vector<int> ans;
        unordered_map<char,int> mp;
        for(int i = 0; i < s.size(); ++i){
            mp[s[i]] = i;
        }

        int i = 0,j = 0;
        while(i < s.size()){
            int length = mp[s[i]] - i + 1;
            for(int k = i; k < mp[s[i]]; ++k){
                length = max(length, mp[s[k]] - i + 1);
            }
            ans.push_back(length);
            i = i + length ;
        }
        return ans;
    }
};
```

**期望行为**
应该是我的程序输出的样子

**屏幕截图**
![114](https://user-images.githubusercontent.com/45219937/158762008-c88d0147-39dd-4c59-a824-58c6b10725a2.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
