### ISSUE TITLE
77. Combinations

### ISSUE THREAD

**Issue by albertopiras** [LeetCode-Feedback/LeetCode-Feedback#6734]
#### Your LeetCode username

albe91

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think the slide solution is partially correct. I attach my solution.

#### Code you used for Submit/Run operation

```

```

#### Screenshots

![fix](https://user-images.githubusercontent.com/6552439/158850120-763437cc-4a27-453b-b95a-2289c608c816.PNG)

**Comment by LC-Sue** [comment]
Hi @albertopiras 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @albertopiras 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by albertopiras** [comment]
> Hi @albertopiras Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
@LC-Sue 

My Pleasure! :)
