### ISSUE TITLE
Unusual output from  IDE

### ISSUE THREAD

**Issue by ferrero-rocher** [LeetCode-Feedback/LeetCode-Feedback#6735]
I was trying to check when both x, n are positive condition but when i tried to run the code it went into infinite loop which shouldnt be the case as the code is also fairly simpler 
### This is my code 

        
        if(n==1)
        {
            return 1;
        }
        
        return x*myPow(x,n-1);
        
    }
}

###This is my leetcode output 
![image](https://user-images.githubusercontent.com/60911166/159004962-0f1718b1-cee4-42b8-9cc6-0a4c17ab929a.png)

###This is my IDE output 
![image](https://user-images.githubusercontent.com/60911166/159004817-fdada86e-1f7f-4a1d-b0c1-a5bac024f4b3.png)

**Comment by ferrero-rocher** [comment]
i was solving the 50th problem on leetcode

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
