### ISSUE TITLE
Missing Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by gopythor** [LeetCode-Feedback/LeetCode-Feedback#6736]
#### Your LeetCode username

sjinsung

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [v ] Missing Test Cases 

#### Description of the bug

I tried sample 3 ms submission from sample, but it has error. It should not be accepted.

#### Code you used for Submit/Run operation

```
func thirdMax(nums []int) int {
	sort.Ints(nums)
	max := make([]int, 0)

	i, last := len(nums)-1, 0
	for i >= 0 {
		if len(max) == 3 {
			break
		}
		if nums[i] != last {
			last = nums[i]
			max = append(max, last)
		}
		i--
	}

	if len(max) < 3 {
		return max[0]
	}
	return max[len(max)-1]
}
```

#### Language used for code

Go

#### Expected behavior

When I put 0, -1, -2, -3, this code I attached output not -2 but -3.

#### Screenshots

![image](https://user-images.githubusercontent.com/94863168/159013564-cae8c756-83c2-4d67-a8f0-73731e292cf2.png)

**Comment by LC-Sue** [comment]
Hi @gopythor 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
