### ISSUE TITLE
Typo in the description - 316. Remove Duplicate Letters - Solution: Approach 1: Greedy - Solving Letter by Letter

### ISSUE THREAD

**Issue by plopd** [LeetCode-Feedback/LeetCode-Feedback#6738]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typo in the description of the first approach.

It states:
> We determine the rest our answer by recursively calling the function

It should state:
> We determine the rest of our answer by recursively calling the function

**Comment by LC-Sue** [comment]
Hi @plopd 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
