### ISSUE TITLE
925. Long Pressed Name

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#674]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Wrong official solution

#### Code you used for Submit/Run operation

```
class Solution(object):
    def isLongPressedName(self, name, typed):
        j = 0
        for c in name:
            if j == len(typed):
                return False

            # If mismatch...
            if typed[j] != c:
                # If it's the first char of the block, ans is False.
                if (j == 0) or (typed[j-1] != typed[j]):
                    return False

                # Discard all similar chars.
                cur = typed[j]
                while j < len(typed) and typed[j] == cur:
                    j += 1

                # If next isn't a match, ans is False.
                if j == len(typed) or typed[j] != c:
                    return False

            j += 1

        return True
```

#### Language used for code
Python

#### Expected behavior
Fails test case

```
"alex"
"alexxr"
```

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
