### ISSUE TITLE
27. Remove Element, Test Case 94

### ISSUE THREAD

**Issue by ClaudiaMorin** [LeetCode-Feedback/LeetCode-Feedback#6740]
Using C# no array is every simply null.  int[] myArray = new int[1] will self-initialize to:  {0}

So, if the input is: [1], 1

there is no way the output could be [] in C#, you would have to go with [0]??

**Comment by ClaudiaMorin** [comment]
Similar problems with [Remove Duplicates from Sorted Array] -- I am getting a different answer from what the tests you run are giving...   your test case uses - 
Input: [1,1,2]

and it says you are looking for:  [1,2]  but my code returns [1], that isn't what I get in VS??  I get [1, 2, 2]  with a return vale of 1.

**Comment by LC-Sue** [comment]
Hi @ClaudiaMorin,
Thank you for reaching out to us, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes. If you'd like for us to look into the issue, please provide the full code used for submission.
