### ISSUE TITLE
Typo in 691. Stickers to Spell Word

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#6741]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

1 <= target <= 15 should be 1 <= target.length <= 15.

**Comment by LC-Sue** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
