### ISSUE TITLE
Missing Test Case - 895. Maximum Frequency Stack

### ISSUE THREAD

**Issue by kartikeytyagi15** [LeetCode-Feedback/LeetCode-Feedback#6742]
#### Your LeetCode username
protostar15 

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
My linear time solution works and passes all test cases, which it shouldnt, as the best way to do the question is in constant time operations for pop() and push() functions 

#### Code you used for Submit/Run operation

```
class FreqStack {
    stack<pair<int,int>> st;
    unordered_map<int,int> hash;
public:
    FreqStack() {
    }
    
    void push(int val) {
        //O(N) Time complexity
        hash[val]++;
        stack<pair<int,int>> temp;
        while(!st.empty() && st.top().second > hash[val]){
            temp.push(st.top());
            st.pop();
        }
        st.push({val,hash[val]});
        while(!temp.empty()){
            st.push(temp.top());
            temp.pop();
        }
    }
    
    int pop() {
        int val = st.top().first;
        st.pop();
        hash[val]--;
        return val;
    }
};

/**
 * Your FreqStack object will be instantiated and called as such:
 * FreqStack* obj = new FreqStack();
 * obj->push(val);
 * int param_2 = obj->pop();
 */
```

#### Language used for code
C++

#### Expected behavior
The above code should result in TLE as it takes O(N) time for push() function, but it gets accepted.

#### This test case should be added to the question TCs for only accepting quality solutions.
[TestCase#895.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8308778/TestCase.895.txt)

**Comment by LC-Sue** [comment]
Hi @kartikeytyagi15 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @kartikeytyagi15 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
