### ISSUE TITLE
Permisson denied with mssql - 196. Delete Duplicate Emails

### ISSUE THREAD

**Issue by imba-tjd** [LeetCode-Feedback/LeetCode-Feedback#6743]
#### Your LeetCode username

imba-tjd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

This problem requires to use `DELETE` statement. But I got

```
[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The DELETE permission was denied on the object 'Person', database 'test', schema 'dbo'. (229) (SQLExecDirectW)
```

#### Code you used for Submit/Run operation

```sql
DELETE p1 FROM Person p1,
    Person p2
WHERE
    p1.Email = p2.Email AND p1.Id > p2.Id
```

#### Language used for code

mssql

#### Expected behavior

Pass

**Comment by LC-Sue** [comment]
Hi @imba-tjd 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @imba-tjd 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
