### ISSUE TITLE
Missing Test Case - 840. Magic Squares In Grid

### ISSUE THREAD

**Issue by Sam-Si** [LeetCode-Feedback/LeetCode-Feedback#6744]
#### Your LeetCode username

sam_si

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

My code has bugs but it still gets accepted.
It fails for the test case 
```
[[9, 8, 3], [4, 5, 6], [7, 2, 1]]
```

#### Code you used for Submit/Run operation

```python
class Solution:
    def numMagicSquaresInside(self, grid: List[List[int]]) -> int:
        R,C = len(grid), len(grid[0])
        
        magic = ["81637492", "43891276", "83419672", "49237816"]
        
        def check(r,c):
            match = []
            
            for dr in (-1,0,1):
                for dc in (-1,0,1):
                    nr, nc = r + dr, c + dc
                    if nr == r and nc == c: continue
                    if 0 <= nr < R and 0 <= nc < C:
                        match.append(str(grid[nr][nc]))
                        
            s = "".join(match)
            
            for m in magic:
                if (s in m * 2 or s in m[::-1] * 2) and len(s) == 8:
                    return True
            
            return False
        
        return sum(int(check(r,c)) for r in range(R) for c in range(C) if grid[r][c] == 5)
```

#### Language used for code

Python

#### Expected behavior

The above code should give wrong answer. Since the test cases are weak it gets accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/13261099/159117275-c1a69eb0-5330-4128-912d-7cb9343e3684.png)
![image](https://user-images.githubusercontent.com/13261099/159117353-0ba6d7af-fe25-45cf-9b84-6f1418696036.png)

#### Additional context

https://leetcode.com/submissions/detail/662921217/
The bug lies due to weak test cases.

**Comment by LC-Sue** [comment]
Hi @Sam-Si 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Sam-Si** [comment]
@LC-Sue Any updates on this?
Any reasons why is it taking so long because usually it takes around a week or so to resolve these.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
