### ISSUE TITLE
Missing Test Case - 2209. Minimum White Tiles After Covering With Carpets

### ISSUE THREAD

**Issue by Yihang-creator** [LeetCode-Feedback/LeetCode-Feedback#6745]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

testcase:  101111010000001
                  2
                  4
should produce 1, but my code produce 2. But my code got accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def minimumWhiteTiles(self, floor: str, numCarpets: int, carpetLen: int) -> int:
        floor = list(floor)
        
        size = len(floor)
        
        if numCarpets*carpetLen >= size: return 0
        
        for i in range(numCarpets):
            max_start_index = 0
            max_num = 0
            for j in range(size-carpetLen+1):
                cover_white = floor[j:j+carpetLen].count("1")
                if cover_white > max_num:
                    max_num = cover_white
                    max_start_index = j
            floor[max_start_index:max_start_index+carpetLen] = ["0"]*carpetLen
        
        
        return floor.count("1") 
```

#### Language used for code
 Python

#### Expected behavior

testcase:  101111010000001
                  2
                  4
should produce 1, but my code produce 2. But my code got accepted.

**Comment by LC-Sue** [comment]
Hi @Yihang-creator 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
