### ISSUE TITLE
Missing Test Case - 2208. Minimum Operations to Halve Array Sum

### ISSUE THREAD

**Issue by nottheswimmer** [LeetCode-Feedback/LeetCode-Feedback#6749]
#### Your LeetCode username
NotTheSwimmer

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Test case: `[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]`

There above missing test case could identify if the user was improperly accessing a min-heap in an attempt to get the second smallest value. The below code passes all test cases despite having a bug where it assumes the second smallest value of the heap `h` is `h[1]` which is not generally true for heaps. It also does rounding which means if it gets the 3rd smallest or 4th smallest it doesn't change the output of the program for all current test cases. A test case that exponentially increases by powers of two helps identify this because it requires many iterations over numbers that have a large difference in magnitude, finally resulting in a comparison that generates an invalid answer.

#### Code you used for Submit/Run operation

```python
class Solution:
    def halveArray(self, nums: List[int]) -> int:
        if len(nums) == 1:
            return 1
        t = sum(nums) / 2
        h = [-x for x in nums]
        heapify(h)
        ops = 0
        while t > 0:
            a, b = h[0], h[1]
            div = int(a/b)
            while div > 0 and t > 0:
                a /= 2
                t += a
                ops += 1
                div -= 1
            heapreplace(h, a)
        return ops
```

#### Language used for code

Python

#### Expected behavior

Test case fails.

#### Screenshots

![image](https://user-images.githubusercontent.com/29849378/159137473-99e3e175-997e-46df-8d0a-e9ca86f644c9.png)

#### Additional context

Submission link: https://leetcode.com/submissions/detail/663246680/

**Comment by LC-Sue** [comment]
Hi @nottheswimmer 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by nottheswimmer** [comment]
@LC-Sue My test case has now been adopted. 
![image](https://user-images.githubusercontent.com/29849378/160225152-a6a7ca0c-dda2-4e0f-ba10-bdd36a5cb0a8.png)

May I receive my 100 tokens? Thanks.

**Comment by nottheswimmer** [comment]
@LC-Sue Hi, it's been over a month. My test case was adopted but I haven't been awarded nor has this ticket been marked resolved.
