### ISSUE TITLE
Improper Test Case - 28. Implement strStr()

### ISSUE THREAD

**Issue by creallfluharty** [LeetCode-Feedback/LeetCode-Feedback#6750]
#### Your LeetCode username
creallf

#### Category of the bug
- [X] Improper Test Cases 

#### Description of the bug
The testcase introduced by https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/4032 TLEs reasonable python O(n*m) solutions. [The most popular O(n*m) solution](https://leetcode.com/problems/implement-strstr/discuss/12814/My-answer-by-Python) that appears to be working is a slice method that unnecessarily makes the space complexity O(m) and probably has a higher time complexity (since the creation of that slice will iterate through all m elements even if it could have stopped early by comparing), but likely doesn't TLE because slicing and string equality are implemented/optimized in C.

I believe that either this test case should be removed, the time limit should be adjusted to allow for pure-python solutions, or the difficulty should be changed.

Sample Discussions:
- https://leetcode.com/problems/implement-strstr/discuss/13255/Python-56-ms-Time-O(N*M)-Space-O(1)
- https://leetcode.com/problems/implement-strstr/discuss/1667194/I-think-python-O(n*m)-should-not-timeout-or-it-should-be-medium.
- https://youtu.be/Gjkhm1gYIMw?t=479

#### Code you used for Submit/Run operation
Note: The first discussion post I linked to also includes code that should work (and previously did).
My Code:
```python
class Solution:
    def strStr(self, haystack: str, needle: str) -> int:
        if len(needle) == 0:
            return 0
        
        for i in range(len(haystack) - len(needle) + 1):
            for j, c in enumerate(needle, i):
                if c != haystack[j]:
                    break
            
            else:
                return i
        
        return -1
````

#### Language used for code
Python3

**Comment by stormsunshine** [comment]
I think an O(n * m) solution should be an expected solution for this problem. Therefore, the upper bounds of n and m should be reduced to make sure that an O(n * m) solution will not get TLE.

**Comment by LC-Sue** [comment]
Hi @creallfluharty 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
