### ISSUE TITLE
题目[700. 二叉搜索树中的搜索](https://leetcode-cn.com/problems/search-in-a-binary-search-tree/)中翻译错误

### ISSUE THREAD

**Issue by QuannengLiu** [LeetCode-Feedback/LeetCode-Feedback#6753]
**lan-zxs**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目

**描述**
题目[700. 二叉搜索树中的搜索](https://leetcode-cn.com/problems/search-in-a-binary-search-tree/)中翻译错误：
”Example 2:“应为“示例2”

**你使用的语言**
Java

**你提交或者运行的代码**
![屏幕截图 2022-03-20 101508](https://user-images.githubusercontent.com/91832904/159145055-827ee65a-6e91-4b42-ace2-1782aebc9d10.jpg)

**期望行为**
把题目[700. 二叉搜索树中的搜索](https://leetcode-cn.com/problems/search-in-a-binary-search-tree/)中的翻译错误由”Example 2:“更改为“示例2”

**屏幕截图**
![image](https://user-images.githubusercontent.com/91832904/159145005-c641e75d-899a-4b96-bd14-9bf18e941979.png)

**额外的上下文**
无

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by BrambleWave** [comment]
你好，当前题目描述已更新，已给予积分奖励，请查收。
