### ISSUE TITLE
Missing Test Case - 965. Univalued Binary Tree

### ISSUE THREAD

**Issue by ngseke** [LeetCode-Feedback/LeetCode-Feedback#6755]
#### Your LeetCode username
ngseke

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I tried both "Run Code" and "Submit" with completely same code, but the "Submit" one gave WA.
Then I printed `val` and found that one is `1` and another is `0`, as the screen shot shows.

#### Code you used for Submit/Run operation

input: `[0]`
 
```javascript
/**
 * Definition for a binary tree node.
 * function TreeNode(val, left, right) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.left = (left===undefined ? null : left)
 *     this.right = (right===undefined ? null : right)
 * }
 */
/**
 * @param {TreeNode} root
 * @return {boolean}
 */
let val = null
var isUnivalTree = function(root) {
  if (!root) return true
  if (val == null) val = root.val
  console.log(val) // ❓
  return root.val === val &&
    isUnivalTree(root.left) &&
    isUnivalTree(root.right)
};
```

#### Language used for code
JavaScript

#### Expected behavior
It should pass the test cases after clicking submit

#### Screenshots 
<img width="1423" alt="Screen Shot 2022-03-20 at 17 41 48" src="https://user-images.githubusercontent.com/17077760/159156646-20aff65b-0dd6-4419-b9b5-6171682c0630.png">

**Comment by LC-Sue** [comment]
Hi @ngseke 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
