### ISSUE TITLE
52. N-Queens II Solution Typo

### ISSUE THREAD

**Issue by dxaviud** [LeetCode-Feedback/LeetCode-Feedback#6756]
`Then, we can put the values for this queen into the corresponding sets.` is stated twice right above the **Algorithm** section

**Comment by LC-Sue** [comment]
Hi @dxaviud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
