### ISSUE TITLE
Some improvements needed on main page

### ISSUE THREAD

**Issue by mbiesiad** [LeetCode-Feedback/LeetCode-Feedback#6757]
Hi. First of all, really great work!

#### Your LeetCode username
mbiesiad

#### Category of the bug
Issue (UX/UI).

#### Description of the bug
Using dark mode on browser, can't see the companies icons & using light mode can't see the other icons there.

#### Repro steps
1. Go to main page: https://leetcode.com/
2. Use light & dark mode (browser). 
3. Try to see the items mentioned in the screenshots below.
4. Compare the results for the dark and light mode (and your experience with the mentioned issue).

#### Expected behavior
The mentioned elements are still clearly visible irrespective of the browser mode.

#### Screenshots
Light mode (can't see the element below 'View Questions" / low visibility):
![image](https://user-images.githubusercontent.com/18367606/159176358-ee6ead67-a68c-4f74-adfb-550d09798036.png)

The same for dark mode (it's pretty well visible):
![image](https://user-images.githubusercontent.com/18367606/159176381-06522ffd-b659-4201-8a68-1cd7639923a2.png)

Dark mode (still fine - visible image):
![image](https://user-images.githubusercontent.com/18367606/159176410-413df8e6-bba0-4233-8ad6-f42c51fbf193.png)

Light mode (can't see the image / low visibility):
![image](https://user-images.githubusercontent.com/18367606/159176426-62e4f086-2114-46f9-8cd4-26f8d0d4968e.png)

Perhaps more important issue here, using dark mode:
![image](https://user-images.githubusercontent.com/18367606/159176460-f8a2b6cf-c852-41b4-a528-9bc8a429e305.png)

And the same part with light mode (fine):
![image](https://user-images.githubusercontent.com/18367606/159176476-563067ba-4908-4acb-805c-c25bd8ca8f84.png)

#### Additional context
Chrome used for dark mode (normally), Edge for light mode (just for quick comparision).

Best wishes,

**Comment by LC-Sue** [comment]
Hi @mbiesiad,
Thank you for reaching out to us, please reach support@leetcode.com for feedback on improvements!
