### ISSUE TITLE
feedback-tab is overlapping other elements

### ISSUE THREAD

**Issue by mbiesiad** [LeetCode-Feedback/LeetCode-Feedback#6758]
Hi.

#### Your LeetCode username
mbiesiad

#### Category of the bug
Issue

#### Description of the bug
The info about "hiring" is overlapping some elements, making them bad visible.

#### Repro steps
1. Go to https://leetcode.com/explore/
2. Make your browser smaller
3. See issue

#### Expected behavior
The mentioned element is not overlapping, the other elements are scalling still well.

#### Screenshots
Normal view (fine, but could be improved a little bit):
![image](https://user-images.githubusercontent.com/18367606/159177106-3d0ba14a-8ee3-43a4-92f5-f055f2099204.png)

Overlapping:
![image](https://user-images.githubusercontent.com/18367606/159177330-75984de4-7a2f-4bb8-9a36-c2d985b9326d.png)

The smallest view (now it's hard to see a little bit):
![image](https://user-images.githubusercontent.com/18367606/159177351-d16676f0-a348-49ce-8cf0-3b58aee001ed.png)

#### Additional context
In my case, used dark mode with Chrome.

Best wishes,

**Comment by LC-Sue** [comment]
Hi @mbiesiad,
Thank you for reaching out to us, please reach support@leetcode.com for feedback on improvements!
