### ISSUE TITLE
Missing Test Case - 1007. Minimum Domino Rotations For Equal Row

### ISSUE THREAD

**Issue by gowtham3105** [LeetCode-Feedback/LeetCode-Feedback#6759]
#### Your LeetCode username

gowtham3105

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In Problem **1007. Minimum Domino Rotations For Equal Row** I noticed that a test case has been missed in the validation. Test case is 
[2,2,2,4,4,4]
[4,4,4,2,3,2]

The correct output is 3, but my code below gets successfully submitted even if it fails this test case.

#### Code you used for Submit/Run operation

```
class Solution:
    def minDominoRotations(self, tops: List[int], bottoms: List[int]) -> int:
        # approach- the most frequent element array would need least rotations
        topMostFreq=max(set(tops), key=tops.count)
        bottomMostFreq=max(set(bottoms),key=bottoms.count)
        topMaxCount=tops.count(topMostFreq)
        bottomMaxCount=bottoms.count(bottomMostFreq)
        rotate=0
        if(topMaxCount>=bottomMaxCount):
            isTop=1
            for i in range(len(tops)):
                if tops[i]!=topMostFreq:
                    rotate+=1
                    tops[i]=bottoms[i]
                    
        else:
            isTop=0
            for j in range(len(bottoms)):
                if bottoms[j]!=bottomMostFreq:
                    rotate+=1
                    bottoms[j]=tops[j]
        if isTop==1:
            if len(set(tops))!=1:
                return -1
        else:
            if len(set(bottoms))!=1:
                return -1
        return rotate
```

#### Language used for code

Python

#### Expected behaviour

The Code mentioned above fails for the test case 
[2,2,2,4,4,4]
[4,4,4,2,3,2]

Expected Output: 3
Output Given by the above Program: -1
But still the code gets successfully submitted.

#### Screenshots

![Screenshot from 2022-03-21 00-26-22](https://user-images.githubusercontent.com/66207607/159178046-5356ecf8-05fd-402d-817e-543f1ae50191.png)

**Comment by LC-Sue** [comment]
Hi @gowtham3105 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
