### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by shafiurrahman1241** [LeetCode-Feedback/LeetCode-Feedback#6768]
#### Your LeetCode username
1ShafiurRahman

#### Category of the bug : misinterpretation of the constructor and it's data type 
- [ ] Question
- [ ] Solution
- [ ] Language
- [] Missing Test Cases 

#### Description of the bug
Leetcode is showing me,

        Line 7: error: constructor Solution in class Solution cannot be applied to given types; [in __Driver__.java]
              int ret = new Solution().romanToInt(param_1);
                        ^
          required: String
          found:    no arguments
          reason: actual and formal argument lists differ in length

but with my constructor and it's datatype, when I created  an object and used the converting method , the constructor the program is working perfectly in eclipse. 

#### Code you used for Submit/Run operation

```

package Leetcode_easy;
import java.util.Scanner;

class Solution {
    String roman;
	
	public Solution(String roman) {
		this.roman = roman;
	}
    
    public int romanToInt(String s) {
		int sum1 = 0;
		
		int icount = 0;
		for (int i = s.length()-1; i>=0; i--) 
		{
			
		char ch1 = s.charAt(i);
		String letter1 = Character.toString(ch1);
	
			if (letter1.equalsIgnoreCase("I")) {
				sum1 +=1;
				icount +=1;
				if (icount >3) 
					{
					System.out.println("the number is invalid");
					break;
					}
				}
			
			
			else if (letter1.equalsIgnoreCase("V")) { 
				if (s.length()==1 || i == 0) 
				{
					sum1 += 5;
					break;
				}
				
				else
				{
					char ch2 = s.charAt(i-1);
					String letter2 = Character.toString(ch2);
		
					if (letter2.equalsIgnoreCase("I")) 
						{
							sum1 += 4;
							i--;
						}
					else
						sum1 += 5;
					
				}
			}
			
			
			else if (letter1.equalsIgnoreCase("X")) { 
				if (s.length()==1 || i == 0) 
				{
					sum1 += 10;
					break;
				}
				
				else
				{
					char ch2 = s.charAt(i-1);
					String letter2 = Character.toString(ch2);
		
					if (letter2.equalsIgnoreCase("I")) 
						{
							sum1 += 9;
							i--;
						}
					else
						sum1 += 10;
					
				}
			}
			
			
			
			else if (letter1.equalsIgnoreCase("L")) { 
				if (s.length()==1 || i == 0) 
				{
					sum1 += 50;
					break;
				}
				
				else
				{
					char ch2 = s.charAt(i-1);
					String letter2 = Character.toString(ch2);
		
					if (letter2.equalsIgnoreCase("X")) 
						{
							sum1 += 40;
							i--;
						}
					else
						sum1 += 50;
					
				}
			}
			
			
			else if (letter1.equalsIgnoreCase("C")) { 
				if (s.length()==1 || i == 0) 
				{
					sum1 += 100;
					break;
				}
				
				else
				{
					char ch2 = s.charAt(i-1);
					String letter2 = Character.toString(ch2);
		
					if (letter2.equalsIgnoreCase("X")) 
						{
							sum1 += 90;
							i--;
						}
					else
						sum1 += 100;
					
				}
			}
			
			
			
			else if (letter1.equalsIgnoreCase("D")) { 
				if (s.length()==1 || i == 0) 
				{
					sum1 += 500;
					break;
				}
				
				else
				{
					char ch2 = s.charAt(i-1);
					String letter2 = Character.toString(ch2);
		
					if (letter2.equalsIgnoreCase("C")) 
						{
							sum1 += 400;
							i--;
						}
					else
						sum1 += 500;
					
				}
			}
			
			
			
			else if (letter1.equalsIgnoreCase("M")) { 
				if (s.length()==1 || i == 0) 
				{
					sum1 += 1000;
					break;
				}
				
				else
				{
					char ch2 = s.charAt(i-1);
					String letter2 = Character.toString(ch2);
		
					if (letter2.equalsIgnoreCase("C")) 
						{
							sum1 += 900;
							i--;
						}
					else
						sum1 += 1000;
					
				}
			}
			
		}
		return sum1;
	}

	public static void main(String[] args) {
		Scanner input1 = new Scanner(System.in);
		System.out.println("enter your Roman Number: ");
		String Roman = input1.nextLine();
		
		Solution calculation = new Solution(Roman);
		
		System.out.println(calculation.romanToInt(Roman));

	}
}

```

#### Language used for code
Java 

#### Expected behavior
I wanted to convert the roman numbers to regular digits. As creating a constructor is always a good practice, I made a constructor with a string data type so that the program can take a user input of particular data type (in this case the data type was String). I made an object of Solution class named "calculation".  While making the object i passed the variable Roman(String) which is a user input . So the data type of the parameter of the constructor and the argument in my main function were same and working fine in eclipse. So I was supposed to get my expected converted number from the program when I called the object's "romanToInt" method. But it showed me a (no argument) error

#### Screenshots

<img width="1279" alt="Screen Shot 2022-03-20 at 9 16 34 PM" src="https://user-images.githubusercontent.com/66236598/159197359-1352c065-d572-4ba8-a803-a9bd7c54ea83.png">
dd screenshots to explain your issue.

**Comment by LC-Sue** [comment]
Hi @shafiurrahman1241,
Thank you for reaching out to us, not all packages are made available.
Each language has it's own set of packages that are made available, they are listed here:
https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-
