### ISSUE TITLE
Missing Test Case - 763. Partition Labels

### ISSUE THREAD

**Issue by Spandan350** [LeetCode-Feedback/LeetCode-Feedback#6769]
#### Your LeetCode username
spandan_ghosh 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There is a scenario missed in the test case. For input "qeqceacao", the expected output is [8,1] but my accepted code is giving [7,8,1].
This is happening because I am checking the first and the last occurrence of alphabets in the order a to z.

#### Code you used for Submit/Run operation

```
// Partition Labels
class Solution {
public:
    vector<int> partitionLabels(string s) {
        vector<int> first(26,INT_MAX);
        vector<int> last(26,INT_MIN);
        vector<int> ans;
        for(int i=0;i<s.length();i++)
        {
            if(i<first[s[i]-'a'])first[s[i]-'a']=i;
            if(i>last[s[i]-'a'])last[s[i]-'a']=i;
        }
        int start=first[s[0]-'a'];
        int end=last[s[0]-'a'];
        cout<<start<<" "<<end<<endl;
        while(start<s.length())
        {
            for(int i=0;i<26;i++)
            {
                if(first[i]<start&&last[i]>=start)
                {
                    start=first[i];
                }
                if(last[i]>end&&first[i]<=end)
                {
                    end=last[i];
                }
            }
            for(int i=0;i<26;i++)
            {
                if(first[i]<start&&last[i]>=start)
                {
                    start=first[i];
                }
                if(last[i]>end&&first[i]<=end)
                {
                    end=last[i];
                }
            }
            ans.push_back(end-start+1);
            start=end+1;
            if(start<s.length())
                end=last[s[start]-'a'];
            cout<<start<<" "<<end<<endl;
        }
        return ans;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
There is a scenario missed in the test case. For input "qeqceacao", the expected output is [8,1] but my accepted code is giving [7,8,1]

#### Screenshots

![image](https://user-images.githubusercontent.com/14842923/159197235-76f0c58d-7d79-4522-95b0-bf80d3d8b106.png)

**Comment by LC-Sue** [comment]
Hi @Spandan350 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
