### ISSUE TITLE
Mismatch in Big O notion in Video tutorial solution and non video solution "118. Pascal's Triangle"

### ISSUE THREAD

**Issue by venkdora** [LeetCode-Feedback/LeetCode-Feedback#6770]
#### Your LeetCode username

venkatado 

#### Category of the bug
- [ ] Question
- [y] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

118. Pascal's Triangle in video solution space complicity is mentioned as O(1) in non video tutorial it is mentioned as O(numRows^2)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @venkdora 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
