### ISSUE TITLE
Missing Test Case - 1059. All Paths from Source Lead to Destination

### ISSUE THREAD

**Issue by mikeck1** [LeetCode-Feedback/LeetCode-Feedback#6772]
#### Your Leetcode Username
mikekaufman4

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Missing case for cycle from destination to source
5
[[0,1],[0,2],[1,3],[2,3],[3,0]]
0
3

#### Code you used for Submit/Run operation

```python
from collections import defaultdict
class Solution:
    def leadsToDestination(self, n: int, edges: List[List[int]], source: int, destination: int) -> bool:
        
        graph=defaultdict(list)
        for x,y in edges: 
            if x==y and x==destination:return False
            graph[x].append(y)
        print(graph)
        pathFoundDest=False
        stack=[source]
        visited=set()
        
        while stack:
            node=stack[-1]
            if graph[node]:
                neigh=graph[node].pop()
                stack.append(neigh)
                pathFoundDest=False
            else:
                if node!=destination and not pathFoundDest and node not in visited:return False
                pathFoundDest=True
                visited.add(node)
                stack.pop()
        return True
```

#### Language used for code
Python3

#### Expected behavior

Code is accepted, however I noticed it fails this testcase. It should fail because it does not detect the cycle.
5
[[0,1],[0,2],[1,3],[2,3],[3,0]]
0
3
Output
true
Expected
false

#### Screenshots
![image](https://user-images.githubusercontent.com/13594692/159236316-744154c8-3788-4cce-a014-277b141c9977.png)

**Comment by mikeck1** [comment]
Bump! 🔢

**Comment by mikeck1** [comment]
Does anyone care?

**Comment by LC-Sue** [comment]
Hi @mikeck1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
