### ISSUE TITLE
2209. Minimum White Tiles After Covering With Carpets - Exact same code gives AC after contest but TLE during contest

### ISSUE THREAD

**Issue by bogoconic1** [LeetCode-Feedback/LeetCode-Feedback#6773]
#### Your LeetCode username
bogoconic1

#### Description of the bug
Exact same code gives AC when I run after the contest, but TLE during the contest

####Code you used for Submit/Run operation
After contest: https://leetcode.com/submissions/detail/664333100/
During contest: https://leetcode.com/contest/biweekly-contest-74/submissions/detail/663102231/
The code is the exact same

####Language used for code
Python3

####Expected behavior
The submission during contest should be accepted, not TLE

**Comment by LC-Sue** [comment]
Hi @bogoconic1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by gvhfds** [comment]
Thanks

The main issue here is that the judging time is the sum of all testcases, but this question has way more test cases then most other questions. 2706 testcases in total, while most questions have 100-200

**Comment by bogoconic1** [comment]
Hi,

just noticed that my solution has been rejudged as accepted. Thanks to the leetcode team.
