### ISSUE TITLE
1654. Minimum Jumps to Reach Home - Insufficient Description/Hints

### ISSUE THREAD

**Issue by james-jasvin** [LeetCode-Feedback/LeetCode-Feedback#6774]
#### Your LeetCode username
rgg1999

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Expected behavior

There is no clear logic visible to understand till where the bug may jump forward to at which point we can declare the problem as unsolvable, the only solution was to just arbitrarily declare the max point as 6000 and beyond which no movement happens and I return -1, but there should something more intuitive, this can be provided as a hint as well in order to make people's lives easier. and not bother over this tiny implementation detail.

**Comment by LC-Sue** [comment]
Hi @james-jasvin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
