### ISSUE TITLE
332. Reconstruct Itinerary - Need C++ solution

### ISSUE THREAD

**Issue by venky100** [LeetCode-Feedback/LeetCode-Feedback#6775]
#### Your LeetCode username
venkyyy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Please provide c++ solution for this question.  It is difficult for me to understand solution in different language especially when complex data structures are used.

#### Language used for code

Java and python

#### Expected behavior

I want solution in c++

**Comment by LC-Sue** [comment]
Hi @venky100,
Thank you for reaching out to us, we are trying our best to provide solutions in multiple languages. C++ may be added to this problem when the solution article gets updated!
