### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by Amangoyal1A** [LeetCode-Feedback/LeetCode-Feedback#6776]
class Solution {
    static String common(String first , String second) //common function help us to  find common characters of two string.
    {
        int i =0;
        int j=0;
        int m= first.length();
        int n = second.length();
        String temp = "";
        while(i<m && j<n)
        {
           if(first.charAt(i)==second.charAt(j))
            {
                temp = temp+first.charAt(i);
                i++;
                j++;
            }else{
                break;
            } 
        }
    return temp;
        }
    
    public String longestCommonPrefix(String[] strs) {
        Arrays.sort(strs); //sort  Array
        String temp= "";
   
       if(strs.length==1)
       {
           return strs[0];
       }
        if(strs[0]=="")
        {
            return "";
        }
        int k= strs.length-1;
        temp +=  common(strs[0],strs[k]);  //  compare first and last element and store in temp variable
       
        
        return temp; 
    }
}

**Comment by LC-Sue** [comment]
Hi @Amangoyal1A 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
