### ISSUE TITLE
1663 Missing Test Cases

### ISSUE THREAD

**Issue by kaiwangx** [LeetCode-Feedback/LeetCode-Feedback#6778]
#### Your LeetCode username
dragonzz

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Approved code can not pass a corner case when n = 3, k = 3

#### Code you used for Submit/Run operation

```
    def getSmallestString(self, n: int, k: int) -> str:
        x = (26*(n) - k) // 25
        y = 25 * x - (26*(n - 1) - k)
        
        return 'a' * x + chr(ord('a') + y - 1) + 'z'*(n-1-x)
```

#### Language used for code
python

#### Expected behavior

for n = 3, k = 3, expected output is aaa but the above approved code outputs aaaz

**Comment by LC-Sue** [comment]
Hi @kaiwangx 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
