### ISSUE TITLE
290. 单词规律：题目描述需要更新

### ISSUE THREAD

**Issue by YangFong** [LeetCode-Feedback/LeetCode-Feedback#6779]
**你的 LeetCode 用户名**

琦

**Bug 类型**

题目

**描述**

题目描述需要更新，看起来怪怪的。

一开始说的是 字符串 `s`，后文又变成了 `str`。

而当前在解决方案里，函数参数也是 `s`。

**期望行为**

中文描述的 `str` 应该统一改为 `s`

**屏幕截图**

中文描述

![image](https://user-images.githubusercontent.com/70502828/159391731-63bd7ef7-73da-44bb-8d15-25342d080cf1.png)

英文描述：

![image](https://user-images.githubusercontent.com/70502828/159391774-4ccb8646-aa2c-4f0d-a775-9c9fcba1ad39.png)

**Comment by YangFong** [comment]
事实上来说，存在着一大批需要更新的题目（相比较英文），我不知道力扣是否存在题目仓库，能够直接提交 PR 进行修正便最好了。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by BrambleWave** [comment]
6. 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by BrambleWave** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by YangFong** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：[support.leetcode-cn.com/hc/kb/article/1277837](https://support.leetcode-cn.com/hc/kb/article/1277837) ），我们给予积分奖励哦。

leetcode-cn.com/u/YangFong/

**Comment by BrambleWave** [comment]
感谢您的回复，奖励已发放
