### ISSUE TITLE
Missing Test Case - 174. Dungeon Game

### ISSUE THREAD

**Issue by HadisDaqiq** [LeetCode-Feedback/LeetCode-Feedback#6780]
#### Your LeetCode username

The prompt is sexiest!!! Wow! what a great safe all the women needs saving from men!

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @HadisDaqiq 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
