### ISSUE TITLE
Solution for Question 595 is wrong

### ISSUE THREAD

**Issue by sil022** [LeetCode-Feedback/LeetCode-Feedback#6781]
#### Your LeetCode username
CarnivalPig

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution is wrong, it won't even pass all the test cases.
For populations and areas, it should be `>=` instead of `>`.

#### Code you used for Submit/Run operation

```
SELECT name, population, area
FROM world
WHERE area >= 3000000 
OR population >= 25000000;
```

#### Language used for code

MySQL

#### Expected behavior

For populations and areas, it should be `>=` instead of `>`.

**Comment by LC-Sue** [comment]
Hi @sil022 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
