### ISSUE TITLE
Missing Test Case - 350. Intersection of Two Arrays II

### ISSUE THREAD

**Issue by idnullZ** [LeetCode-Feedback/LeetCode-Feedback#6783]
#### Your LeetCode username

user2811z

you need to upgrade the language Kotlin version to 1.5.31

#### Description of the bug

crashes in runtime until version 1.5.31

#### Code you used for Submit/Run operation

```
//   Intersection of Two Arrays II
class Solution {

fun intersect(nums1: IntArray, nums2: IntArray): IntArray {
    val innerArray2 = ArrayList<Int>()
    val result = ArrayList<Int>()

    for (i in nums2.indices){
        innerArray2.add(nums2[i])
    }
    var size = innerArray2.size-1
    for (i in nums1.indices){

        for (h in 0..size){

            if (nums1[i] == innerArray2[h]){
                result.add(nums1[i])
                innerArray2.remove(innerArray2[h])
                size -= 1
                if (size== -1){
                    break
                }
            }
        }
    }
    return result.toIntArray()
}

}
```
Kotlin Language
#### Language used for code

after version 1.5.31 it works correctly and does not crash

**Comment by LC-Sue** [comment]
Hi @idnullZ,
Thank you for reaching out to us, thank you for the request. Please also feel free to refer to the discuss section of the problem to see how other users' have optimized their kotlin solutions!
