### ISSUE TITLE
Missing testcases for 1663. Smallest String With A Given Numeric Value

### ISSUE THREAD

**Issue by sr-vrd** [LeetCode-Feedback/LeetCode-Feedback#6784]
#### Your LeetCode username
sr_vrd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases for <a href="https://leetcode.com/problems/smallest-string-with-a-given-numeric-value/">1663. Smallest String With A Given Numeric Value</a>.

Apparently the cases where n = k are not being tested. I encountered the code below in a discussion post. Looking at this user's submission <a href="https://leetcode.com/submissions/detail/664877394/">here</a>, it passed all testcases, but it failed when I ran it with testcases of the form n = k.

#### Code you used for Submit/Run operation

```
// Smallest String With A Given Numeric Value
class Solution:
    def getSmallestString(self, n: int, k: int) -> str:
        b = math.ceil((k - n) / 25) - 1
        a = n - b - 1
        x = k - a - 26 * b
        return 'a' * a + chr(ord('a') - 1 + x) + 'z' * b
```

#### Language used for code
Python3

#### Expected behavior

Input:
```
1
1
2
2
3
3
50
50
```
Output of above code:
```
"az"
"aaz"
"aaaz"
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaz"
```
Expected output:
```
"a"
"aa"
"aaa"
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```
Thanks!

**Comment by LC-Sue** [comment]
Hi @sr-vrd 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
