### ISSUE TITLE
Missing Test Case - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by tusharsnn** [LeetCode-Feedback/LeetCode-Feedback#6785]
#### Your LeetCode username
tusharsnn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
the problem with test-cases is that they all uses seperate objects or alteast calls decode right after callling encode. eg. `codec.decode(codec.encode(url))`. 
This way I could get away from implementing anything inside encode or decode and each time `.encode()` is called I can just save the `longUrl` and return the `longUrl` in the subsequent `.decode()` call from within the object like the way i did in the below snippet.

#### Code you used for Submit/Run operation

```
class Codec:

    def encode(self, longUrl: str) -> str:
        """Encodes a URL to a shortened URL.
        """
        self.longUrl = longUrl
        return longUrl
        

    def decode(self, shortUrl: str) -> str:
        """Decodes a shortened URL to its original URL.
        """
        return self.longUrl
```

#### Language used for code
python3

#### Expected behavior

The judger should call a bunch of `.encode()` together and then all of the `.decode()` after it. This way url that was stored earlier will be overwritten.

**Comment by LC-Sue** [comment]
Hi @tusharsnn,
Thank you for reaching out to us, the current provided snippet is 
class Codec:

    def encode(self, longUrl: str) -> str:
        """Encodes a URL to a shortened URL.
        """
        
    def decode(self, shortUrl: str) -> str:
        """Decodes a shortened URL to its original URL.
        """
        Which appears to match what you've mentioned!

**Comment by tusharsnn** [comment]
@LC-Sue I have saved the `longUrl` to a variable and returned it on .decode() so logically, I have not implemented .encode() or .decode(), but still it will pass all the test cases. Is it the expected behaviour ?

user should implement .encode() which would return shorten url, and .decode() should return back the original url when queried with the shortened url.
