### ISSUE TITLE
2039. 网络空闲的时刻：代码超出时间限制

### ISSUE THREAD

**Issue by JeremyZ96** [LeetCode-Feedback/LeetCode-Feedback#6786]
**你的 LeetCode 用户名**
JeremyZhang96

**Bug 类型**
- 题目

**描述**
对于47号用例，即使代码直接return结果，却还是会超出时间限制

**你使用的语言**
Python3

**你提交或者运行的代码**
```
class Solution:
    def networkBecomesIdle(self, edges: List[List[int]], patience: List[int]) -> int:
        return 0
```

**期望行为**
应该很快返回0

**屏幕截图**
![网页捕获_23-3-2022_12528_leetcode-cn com](https://user-images.githubusercontent.com/38674616/159539836-b5f4e890-2921-46ff-b75f-5599e42a4bb1.jpeg)

**额外的上下文**
47号测试用例：
[测试用例.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8326565/default.txt)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：这个是由于用例太长，在验证格式的时候超时了，并不是执行代码导致的。 我们会在后续的版本不断更新优化和提升我们的产品，给大家带来最佳的用户体验。
