### ISSUE TITLE
Missing Test Case - 877. Stone Game

### ISSUE THREAD

**Issue by ErreVega** [LeetCode-Feedback/LeetCode-Feedback#6787]
#### Your LeetCode username

errevega1991

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

There is no case where "Bob" wins the game and the output is false.

#### Code you used for Submit/Run operation

```
var stoneGame = function(piles) {
    return true
};
```

#### Language used for code

JavaScript, Java, C++ tested
It seems like there is no test for afalse case in any language.

#### Expected behavior

It should fail some test.

#### Screenshots

![image](https://user-images.githubusercontent.com/35697495/159578289-9db4e9f8-aff6-48e6-9648-e1e3a0c0f4d9.png)

**Comment by stormsunshine** [comment]
Why do you think Bob can win in some case? If you can't provide such a test case, you are wasting others' time.

In fact, it can be proven that Alice always wins.

**Comment by tusharsnn** [comment]
@stormsunshine you could be little more polite when you help others.
