### ISSUE TITLE
Difficulty Level is Misleading - 716. Max Stack

### ISSUE THREAD

**Issue by zhengyuan-liu** [LeetCode-Feedback/LeetCode-Feedback#6788]
#### Your LeetCode username

Compiler

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The difficulty level of this problem, "Easy", is misleading. Comparing to LRU Cache, this problem should be medium.

For details, you can see the discussion:
https://leetcode.com/problems/max-stack/discuss/108957/If-LRU-Cache-is-%22Hard%22-so-is-this

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
Max Stack is similar to Min Stack. Since Min Stack is Easy, Max Stack should be Easy as well. Although there is an operation `popMax`, the time complexity for `popMax` can be O(n).

**Comment by LC-Sue** [comment]
Hi @zhengyuan-liu,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Please feel free to reach out if you have any other questions!
