### ISSUE TITLE
Constraints Typo - 991. Broken Calculator

### ISSUE THREAD

**Issue by shashank9aug** [LeetCode-Feedback/LeetCode-Feedback#6789]
#### Your LeetCode username

shashank9Aug

 #### Category of the bug
- [x]  Question
- [ ]  Solution
- [ ]  Language
- [ ]  Missing Test Cases

#### Description of the bug

The constrains given in question as 1 <= x, y <= 109 but their is no mentioned x and y variable in question.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/59617810/159620539-cb60b124-4344-46f6-afea-5dc2022ab123.png)

#### Additional context

The constraints should be 1 <= startValue , target <= 109

**Comment by LC-Sue** [comment]
Hi @shashank9aug 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem.We appreciate your support!
