### ISSUE TITLE
Incorrect constraints - 991. Broken Calculator

### ISSUE THREAD

**Issue by kumardeepakr3** [LeetCode-Feedback/LeetCode-Feedback#6792]
#### Your LeetCode username
paanipoori

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The constraints shows `x` and `y` as some variables. However the question only has `startValue` and `target` as variables. This should be corrected.

#### Expected behavior
Constraint should have `startValue` and `target` in it.

#### Screenshots
![image](https://user-images.githubusercontent.com/8517001/159636111-01a7b540-44fb-4940-9113-d40beebf23af.png)

**Comment by LC-Sue** [comment]
Hi @kumardeepakr3 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by kumardeepakr3** [comment]
Closing as the question is fixed now. :)
