### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by gopythor** [LeetCode-Feedback/LeetCode-Feedback#6793]
#### Your LeetCode username

sjinsung

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [O ] Missing Test Cases 

#### Description of the bug

When assume pivot is 0, left sum is 0 and right sum is 0.
So If length of array is 1, pivot should be 0.
But when I checked sample of code, It passed code test.

#### Code you used for Submit/Run operation

```
func pivotIndex(nums []int) int {
	if len(nums) < 2 {
		return -1
	}

	left := 0
	right := 0
	for i := 1; i < len(nums); i++ {
		right += nums[i]
	}

	var pivot int
	for i := 0; i < len(nums); i++ {
		if left == right {
			return pivot
		}

		pivot = i + 1
		left += nums[i]
		if pivot < len(nums) {
			right -= nums[pivot]
		}
	}

	return -1
}
```

#### Language used for code

Go

#### Expected behavior

This code must not be passed because 
Constraints:
1 <= nums.length <= 104

#### Screenshots

![image](https://user-images.githubusercontent.com/94863168/159695555-745b896b-fa84-4051-b8f4-f70acf4b8a79.png)

**Comment by LC-Sue** [comment]
Hi @gopythor 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
