### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by er-parag91** [LeetCode-Feedback/LeetCode-Feedback#6794]
#### Your LeetCode username
hangingin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
For following input string, it expected "wyyw" however function I wrote returns "xnnx" which is also correct longest palindrome.
 
Input string: "apqjpwedlhmvvpexxnntxheeynxmgzwxhnhfdvziuxnuusymklgcacndoyhqkoahnkyaikohwkmnuphipftmzmihvmoetskioeypwjujvvusaxynzxxdugnebsisrtgeujkqkgwjuplijhluumqcdurovyjsbowmnqndejwkihzbbdyxjunkduyqeihektaknbmkzgnnmgywylulxwyywrvieqfenjeljofkqqqisdjsbfkvqgahxwkfkcucvrbbpyhwkfztjdboavtfynrudneieelwlcezqsuhmllcsadcnoyemsfdlrijoyj"

Expected: "wyyw"
Output: "xnnx"
Test: https://leetcode.com/submissions/detail/665720551/

#### Code you used for Submit/Run operation
```
/**
 * @param {string} s
 * @return {string}
 */
var longestPalindrome = function(s) {
    let currentPelindrome = '';
    let longestPelindrome = '';

    for (let i = 1; i < s.length - 1; i++) {
        const [prev, current, next] = [s[i-1], s[i], s[i+1]];
        if (longestPelindrome.length < currentPelindrome.length) {
            longestPelindrome = currentPelindrome;
        }

        if (current == next || prev == next || prev == current) {

            currentPelindrome = `${current}${next}`;
            let pastCursor = i - 1;
            
            if (prev == next) {
               currentPelindrome = `${prev}${current}${next}`
                pastCursor = i - 2;
            } else if (prev == current) {
                currentPelindrome = `${prev}${current}`;
                pastCursor = i - 2;
            }
            
            for (let j = i + 2; j < s.length; j++) {
                if (s[pastCursor] && s[j] == s[pastCursor]) {
                   currentPelindrome = `${s[j]}${currentPelindrome}${s[j]}`;
                    pastCursor--;
                } else if (!s[pastCursor] && current == next && next == s[j]) {
                    currentPelindrome += s[j]
                } else {
                    break;
                }
            }
        }
    }
    
                
    if (s.length == 2 && s[0] == s[1]) {
        return s
    }
    if (currentPelindrome.length === 0 && longestPelindrome.length === 0) {
        return s[0]
    }
    
    return currentPelindrome.length > longestPelindrome.length ? currentPelindrome : longestPelindrome ;
};
```

#### Language used for code
Javascript

#### Expected behavior
For [this](https://leetcode.com/submissions/detail/665720551/) test input, 'xnnx' is also valid longest palindrome and should accept the answer

**Comment by stormsunshine** [comment]
Where is "xnnx" in the input string? A substring must be consecutive, which is different from a subsequence where characters are not required to be consecutive.

**Comment by er-parag91** [comment]
> Where is "xnnx" in the input string? A substring must be consecutive, which is different from a subsequence where characters are not required to be consecutive.

Good catch.
