### ISSUE TITLE
Typo in Example 1 of problem description - 650. 2 Keys Keyboard

### ISSUE THREAD

**Issue by weilincheng** [LeetCode-Feedback/LeetCode-Feedback#6795]
#### Your LeetCode username

weilincheng

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In example 1, `Initially` is misspelled as `Intitally`. 
```
Example 1:

Input: n = 3
Output: 3
Explanation: Intitally, we have one character 'A'.
In step 1, we use Copy All operation.
In step 2, we use Paste operation to get 'AA'.
In step 3, we use Paste operation to get 'AAA'.
```

**Comment by LC-Sue** [comment]
Hi @weilincheng 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by weilincheng** [comment]
Nice. Thanks for the update!
