### ISSUE TITLE
Missing Test Case - 35. Search Insert Position

### ISSUE THREAD

**Issue by artemkov32** [LeetCode-Feedback/LeetCode-Feedback#6796]
class Solution:
    def searchInsert(self, nums: List[int], target: int) -> int:
        if target in nums:
            return nums.index(target)
        else:
            nums.append(target)
            return(sorted(nums).index(target))

**Comment by LC-Sue** [comment]
Hi @artemkov32 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
