### ISSUE TITLE
Missing Test Case - 1604. Alert Using Same Key-Card Three or More Times in a One Hour Period

### ISSUE THREAD

**Issue by xjiahang** [LeetCode-Feedback/LeetCode-Feedback#6797]
#### Your LeetCode username

Nathan
nathan_code
Rank
32,119
#### Category of the bug
wrong output for test case

#### Description of the bug

For below test case, I think "daniel" should be output, since these three timestamp are within one hour.
Your input
["daniel","daniel","daniel"]
["00:01","00:02","23:59"]
Output
[]
Expected
[]
#### Code you used for Submit/Run operation
https://leetcode.com/problems/alert-using-same-key-card-three-or-more-times-in-a-one-hour-period/discuss/877222/Java-Simple-Hash-ArrayList

```
class Solution {
    public List<String> alertNames(String[] keyName, String[] keyTime) {
        Map<String, List<Integer>> map = new HashMap<>();
        List<String> res = new ArrayList<>();
        for (int i = 0; i < keyName.length; i++) { // cache all visits for same person.
            String k = keyName[i];
            map.computeIfAbsent(k, g -> new ArrayList<>());
            map.get(k).add(getTime(keyTime[i]));
        }
        
        for (String k : map.keySet()) {
            List<Integer> l = map.get(k);
            Collections.sort(l);  // sort to find the connective checkins
            for (int i = 2; i < l.size(); i++)
                if (l.get(i) - l.get(i - 2) <= 60) {  // connective 3 within 60 mins.
                    res.add(k);
                    break;
                }
        }
        
        Collections.sort(res);
        return res;
    }
    
    private int getTime(String t) {  // transfer stirng to relative mins.
        String[] ss = t.split(":");
        return Integer.parseInt(ss[1]) + 60 * Integer.parseInt(ss[0]);
   
```

#### Expected behavior

["Daniel"]

#### Screenshots

![Screen Shot 2022-03-23 at 10 42 09 AM](https://user-images.githubusercontent.com/10081253/159763562-49febc09-22a5-4421-b0af-adf327fafd38.png)

**Comment by stormsunshine** [comment]
Only consider a single day. So "23:59" is after both "00:01" and "00:02" and it is NOT in a one-hour period.

**Comment by LC-Sue** [comment]
Hi @xjiahang,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Please feel free to reach out if you have any other questions!
