### ISSUE TITLE
Missing Test Case - 1539. Kth Missing Positive Number

### ISSUE THREAD

**Issue by vimalMK** [LeetCode-Feedback/LeetCode-Feedback#6799]
#### Your LeetCode username
Step101

#### Category of the bug
- [x] Question
- [x] Missing Test Cases 

#### Description of the bug
The Question constraints says that the array 'arr' can be of max length 1000 , i.e 1 <= arr.length <= 1000. 

If I consider an array 'arr' of length 1000 as my input. Given the array is sorted in a strictly increasing order. There will be no duplicates and as per the constraints arr[i] ranges between  1 <= arr[i] <= 1000. This means there should not be any missing elements in the array. But the array of length 1000 having values from 1->1000 and k value as 2. given be 1002 as output(not a expected behavior as 1002 is not in the range as per the constraints )

#### Code you used for Submit/Run operation
```
class Solution {
    public int findKthPositive(int[] arr, int k) {
        
      int start = 0;
      int end = arr.length-1;
      int missingCount = 0;
      
      while(start < end) {
        int mid = start + (end - start)/2;
        missingCount = arr[mid] - (mid+1);
        
        if(missingCount < k) {
          start = mid + 1;
        }else {
          end = mid;
        }
      }
      
      missingCount = arr[start] - (start+1);

      if(missingCount < k)
        return arr[start] + (k - missingCount);
      
      return arr[start] - (missingCount - k) - 1;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
what's happening now ---- Input array of length 1000 from elements arr[i] from 1<=arr[i]<=1000, and k=2     given me 1002 as output. it should not be giving an output 1002 as 1002 is not in the range . Therefore 1002 does not exists in the array.(EDGE CASES)

Expected behavior: Either the questions should say if no missing elements and the max array length is 1000, then just return -1 (something like that) or any workaround in constraints should work as well.

#### Screenshots

EDGE CASES WHICH PASS - EXPECTED TO FAIL AS 1002 is not a missing value and is out of range.
![image](https://user-images.githubusercontent.com/35750792/159784334-01656f6a-5485-4459-a2c1-0cc159692192.png)
![image](https://user-images.githubusercontent.com/35750792/159783308-b73a8d96-438b-468a-b851-6c53ae0b0eb7.png)

**Comment by stormsunshine** [comment]
Your understanding of the problem is incorrect. The k-th missing positive number is not required to be in the range of elements of `arr`. Could you please take a look at example 2? The result is 6, which is not in the range of elements of `arr`.

**Comment by vimalMK** [comment]
Here the range is referred to 1 <= arr[i] <= 1000 (as per the questions Constraints), not the input array range. In the second example the result is 6. which is  in the range 1<=arr[i]<=1000.

The example I referred to has result 1002, which is NOT in the range 1<=arr[i]<=1000. 

Please correct me I am wrong.  Am I missing something :)

**Comment by stormsunshine** [comment]
@vimalMK The constraints require that 1 <= arr[i] <= 1000, but do not require that the answer should be in the range [1, 1000]. Why do you think the answer is one of the elements in the given array?

**Comment by vimalMK** [comment]
That make sense. Kth missing positive integers. You are right, the answer should not have to be in the range. The constraints are just for the input array not for the answers. Got it.

thank you for the clarification.
