### ISSUE TITLE
使用 Kotlin 语言中的 Pair 对象并调用 first、second 会编译出错

### ISSUE THREAD

**Issue by Airsaid** [LeetCode-Feedback/LeetCode-Feedback#68]
**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言

**描述**
当使用 Kotlin 语言中的 Pair 对象，然后正常调用其 first 或 second 时会编译出错。

**你使用的语言**
Kotlin

**你提交或者运行的代码**
```
val queue = LinkedList<Pair<Int,Int>>()
val pair = queue.pop()
var a = pair.first // 编译出错
```

**期望行为**
正常运行。

**屏幕截图**
<img width="871" alt="Jietu20200321-230411@2x" src="https://user-images.githubusercontent.com/15967150/77284477-beb6b680-6d09-11ea-9b38-9ee0adce14e5.png">

**额外的上下文**

**Comment by feiceh** [comment]
能否向我们提供一下 题号？把信息提供完整有助于攻城狮快速验证和精准的定位哟～

**Comment by Airsaid** [comment]
我觉得这是一个通用的问题，而不是限制在某题。我在多个题中尝试这样写都会编译失败，例如：
- https://leetcode-cn.com/problems/rotting-oranges/
- https://leetcode-cn.com/problems/water-and-jug-problem/

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
fixed
