### ISSUE TITLE
562. Longest Line of Consecutive One in Matrix

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#680]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 1: Brute Force has inconsistent analysis

#### Expected behavior
Approach 2

> Time complexity : O(mn)

Approach 3

> Time complexity : O(mn)

Approach 1

> Time complexity : O(n^2)

Should be O(mn) lie other solutions

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
