### ISSUE TITLE
Image not loading in solution 1874. Minimize Product Sum of Two Arrays

### ISSUE THREAD

**Issue by srishtig7** [LeetCode-Feedback/LeetCode-Feedback#6800]
#### Your LeetCode username
srishti7

#### Category of the bug
- [ ] Question
- [yes ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
1874. Minimize Product Sum of Two Arrays solution number 3 for counting sort.
Image isnt loading

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Python

#### Expected behavior
Image should be visible

#### Screenshots
![image](https://user-images.githubusercontent.com/102257228/159786198-012e2107-176b-4f87-a3f6-a9aadcc24788.png)

**Comment by LC-Sue** [comment]
Hi @srishtig7 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
