### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array using Tree Map

### ISSUE THREAD

**Issue by SoumeshNayak** [LeetCode-Feedback/LeetCode-Feedback#6803]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @SoumeshNayak 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
