### ISSUE TITLE
Missing Test Case - 881. Boats to Save People

### ISSUE THREAD

**Issue by zHpomelHz01** [LeetCode-Feedback/LeetCode-Feedback#6806]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I can see a bug on the solution of this problem
with the test [50, 49, 47, 41, 33, 26, 22, 18, 13, 12, 11, 10, 10, 10, 7, 6, 6, 2, 2, 2] limit 50 I got a better answer

Boat 1 50
Boat 2 49
Boat 3 47,2
Boat 4 41,2,2
Boat 5 33,6,6
Boat 6 26,7,10
Boat 7 22,10,10
Boat 8 18,11,12
Boat 913,12
The system says that the correct answer is 11  but the instructions say " minimum number of boats to carry every given person."
I also saw some submissions from anothers that have the same issue 
#### Code you used for Submit/Run operation

```
class Solution(object):
    def numRescueBoats(self, people, limit):
        people = sorted(people,reverse=True)
        lo = 0
        ind=0
        hi = len(people)-1
        boats = []
        while lo <= hi:
            boats.append(limit)
            if people[lo]==boats[ind]:
                boats[ind]=0
                ind+=1
                lo +=1
            else:
                boats[ind]=boats[ind]-people[lo]
                lo +=1
                while people[hi]<=boats[ind]:
                    boats[ind]=boats[ind]-people[hi]
                    hi -=1
                ind+=1
        
        return len(boats)
```

**Comment by chinmaym07** [comment]
Hey It is allowed to have only 2 people in a boat, but in your solution you are taking more than 2 people.
So the answer given is right i.e, 11.

<img width="1162" alt="Screenshot 2022-03-24 at 1 24 57 PM" src="https://user-images.githubusercontent.com/44670961/159868918-b0abf952-2583-48b2-9d64-c09ffba2462f.png">

**Comment by LC-Sue** [comment]
Hi @zHpomelHz01,
Thank you for reaching out to us, I hope chinmaym07's response was able to answer your doubts. Please feel free to reach out again if you have any other questions!
