### ISSUE TITLE
881. Boats to Save People || Bug in the solution offered by Leetcode.

### ISSUE THREAD

**Issue by shubhammishra115** [LeetCode-Feedback/LeetCode-Feedback#6808]
#### Your LeetCode username

username: shubhammishra115

#### Category of the bug
- [ ] Solution
There is a correction in the solution section of the question provided by the leetcode.
The total Space Complexity of the solution should be O(1) since we are not using any new array or vector, but there it is written O(n).

#### Description of the bug

Mistake in the solution provided by the leetcode.

#### Expected behavior

It expected answer of the space complexity of the solution provided by the leetcode should be O(1).

#### Screenshots

I have attached a screenshot showing the mistake.
![image](https://user-images.githubusercontent.com/56958759/159893398-b3b0baac-9a46-4b88-a2af-4b86d1fce39f.png)

**Comment by tusharsnn** [comment]
@shubhammishra115  There is no reference of `sort()` that takes `O(1)`. In some situation where quick sort is used as the underlying algorithm, it will consume `O(N)`. So in worst case complexity its a safer bet to assume `O(N)` as the total complexity. 

still it's always recommended to check for official references, which I could not find at this moment.

**Comment by LC-Sue** [comment]
Hi @shubhammishra115 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by shubhammishra115** [comment]
Hello Yani,

It was my pleasure, can I expect some goodies from leetcode?

kind regards,
Shubham Mishra
