### ISSUE TITLE
Missing Test Case - 1523. Count Odd Numbers in an Interval Range

### ISSUE THREAD

**Issue by SaiCharanGurram** [LeetCode-Feedback/LeetCode-Feedback#6809]
#### Your LeetCode username
saicharangurram

#### Category of the bug
- [ 1523] Question
- [ ] Solution
- [javascript ] Language
- [ ] Missing Test Cases 

#### Description of the bug
the code which I have written is correct and similar to the output. but it tells it is a wrong answer just because there is a space after the output  

#### Code you used for Submit/Run operation

```
var countOdds = function(low, high) {
    var data = new Array()
    
    
    for(let i = low;i <= high; i++ ){
         
        if(i%2 !== 0){
            data.push(i)
        }
        
        
    }
    console.log(data.length)
};
```

#### Language used for code
JavaScript

#### Screenshots

<img width="1416" alt="Screenshot 2022-03-24 at 9 30 23 AM" src="https://user-images.githubusercontent.com/34616253/159939164-fb06bc4e-ddbb-4e5b-b7d8-35948d16c621.png">

**Comment by tusharsnn** [comment]
@SaiCharanGurram you don't have to write language or question itself in the category, instead select the category of the bug by marking as: `[ x ] `.

**Comment by tusharsnn** [comment]
@SaiCharanGurram your function should return the correct value and not print it on to stdout. try replacing `console.log(data.length)` with `return data.length` at the end of the function. Does this helps ?

**Comment by SaiCharanGurram** [comment]
thank you @tusharsnn
