### ISSUE TITLE
329. Longest Increasing Path in a Matrix

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#681]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Miscellaneous

#### Expected behavior

> ** Complexity Analysis **

 Broken formatting

> 1 2 3 . . . n
> 2 3 . . .   n+1
> 3 . . .     n+2
> .           .
> .           .
> .           .
> m m+1 . . . n+m-1

Why is this in a code block?

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
