### ISSUE TITLE
Space Complexity Issue in solution  Problem 881 Boats to Save People

### ISSUE THREAD

**Issue by iamvinayvk** [LeetCode-Feedback/LeetCode-Feedback#6810]
#### Your LeetCode username
iamvinayvk

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Space Complexity given in the solution for the C++ code is O(n) but according to the given code, it should be O(1) because we are not taking any extra space in the solution.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int numRescueBoats(vector<int>& people, int limit) {
        sort(people.begin(), people.end());
        int i = 0, j = people.size() - 1;
        int ans = 0;

        while (i <= j) {
            ans++;
            if (people[i] + people[j] <= limit)
                i++;
            j--;
        }

        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
According to the given code, the Space Complexity should be O(1) for the C++ solution but in the solution article, it is given O(n).
There is no data structure used that can take O(n) space so the space complexity should be O(1).

#### Screenshots
![image](https://user-images.githubusercontent.com/51132814/159952158-09f0ea73-461e-4dfe-8b1b-d6d096ac790b.png)

**Comment by tusharsnn** [comment]
@iamvinayvk have you checked the space complexity of `sort()` ? In order to sort the vector,  it might be consuming the same amount of memory as the array itself. As I have not worked with C++ and do not know  it internal workings, I suggest you to check the official docs or other resources once.

**Comment by iamvinayvk** [comment]
Yes, I have checked the official docs and got to know that the sort function in c++ uses intro sort as their internal algorithm for sorting. The Time Complexity for Intro Sort is [nlogn](https://en.wikipedia.org/wiki/Sorting_algorithm) and Space Complexity is [logn](https://en.wikipedia.org/wiki/Sorting_algorithm) . 

**Correction**
As I suggested the Space Complexity is O(1) for C++ code, but it should be O(logn) .


ScreenShots -
![image](https://user-images.githubusercontent.com/51132814/160158046-154a4488-f97c-4ce7-aaf8-9d24ba072a8a.png)


Link to Resources -
https://www.geeksforgeeks.org/sort-c-stl/

https://en.wikipedia.org/wiki/Sorting_algorithm

https://www.geeksforgeeks.org/c-qsort-vs-c-sort/

**Comment by tusharsnn** [comment]
@iamvinayvk according to references you shared seems like C++ sorting algorithm takes `O(logN)`. However on the page, `O(N)` represents the space complexity of sorting algorithm across different programming languages, eg. Python and Java. Both of which uses **Tim sort** internally.

**Tim sort** is a hybrid algorithm combining the insertion sort and merge sort together. Insertion sort for smaller partitions and merge sort to merge those partitions together. space complexity of merge sort is infact, `O(N)`.

Hope this clears the intention for having space complexity as **O(N)** on the problem's page.

**Comment by iamvinayvk** [comment]
@tusharsnn If it is possible then mention space complexity for each programming language separately on the problem's page.

This will remove the confusion of Space Complexity for C++ and other languages.

**Comment by LC-Sue** [comment]
Hi @iamvinayvk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
