### ISSUE TITLE
63. Unique Paths II language is unclear

### ISSUE THREAD

**Issue by cathysarisky** [LeetCode-Feedback/LeetCode-Feedback#6813]
#### Your LeetCode username
cathysarisky

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question text never defines what should happen if there is an obstacle at 0,0.  The language doesn't define what an 'obstacle' is.  That's fine, we can use the English meaning, but one might think that an obstacle prevents moving INTO a square, not moving out of a square if one starts with an obstacle on the robot's square.

#### Code you used for Submit/Run operation
N/A

#### Expected behavior
The language could be clarified to say that a path cannot include any square with an obstacle.  That'd take care of the case where the start position IS an obstacle, without giving the coder a big hint.

#### Screenshots

![image](https://user-images.githubusercontent.com/42299862/160023105-95abea73-b10c-4ea3-a890-43b86d5e8dee.png)

**Comment by LC-Sue** [comment]
Hi @cathysarisky 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @cathysarisky 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
