### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by andreiasi** [LeetCode-Feedback/LeetCode-Feedback#6816]
#### Your LeetCode username

andreiasi

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

// my solution works in JsFiddle but not in LeetCode

// https://jsfiddle.net/andreiasi/3y174m9o/2/

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @return {number}
 */
const removeDuplicates = function (nums) {

    let hasDuplicates = false
    for (let i = 0; i < nums.length - 1; i++) {
        if (nums[i] !== '_' && nums[i] === nums[i + 1]) {
            nums.splice(i + 1, 1)
            nums.push('_')
            hasDuplicates = true
        }
    }
    if (hasDuplicates) {
        removeDuplicates(nums)
    }
    return nums;
};

console.log(removeDuplicates([1,1,2]))
```

#### Language used for code

Javascript

#### Expected behavior

the correct output is: [ 1, 2, '_' ] instead of []

**Comment by LC-Sue** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment. 

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it. 

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process. 

We appreciate your time and support.
