### ISSUE TITLE
Missing Test Case - 627. Swap Salary

### ISSUE THREAD

**Issue by rajeshcs044** [LeetCode-Feedback/LeetCode-Feedback#6818]
#### Your LeetCode username
submarineman

#### Category of the bug
- [ ] Question 627. Swap Salary
- [ ] Solution Failing with invalid test case 'salary'
- [ ] Language MySQL
- [ ] Missing Test Cases 

#### Description of the bug

Even though I submit the correct code, still it says invalid test case 'salary'

#### Code you used for Submit/Run operation

```
UPDATE salary
SET
    sex = CASE sex
        WHEN 'm' THEN 'f'
        ELSE 'm'
    END;
```

#### Language used for code
MySQL

#### Expected behavior
Should pass all the testcase

**Comment by LC-Sue** [comment]
Hi @rajeshcs044,
Thank you for reaching out to us, the code you provided is accepted with no issue!
