### ISSUE TITLE
Error in Expected test-case result - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by epicmurloc29** [LeetCode-Feedback/LeetCode-Feedback#6819]
#### Your LeetCode username

user4579JB

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Hello. 
The resulting array from [1,1] and [1,2]  is [1,2]
The median of the array [1, 2]  should be 1.5 and not 1.0.
I checked everywhere since i was loosing my mind :)

#### Language used for code

Java

#### Expected behavior

Expected **Expected** test-case result for [1,1] [1,2]: 1.5
Actual **Expected** test-case result for [1,1] [1,2] : 1.0

#### Screenshots

![image](https://user-images.githubusercontent.com/23290847/160085424-c5b94ca6-2d2a-4840-bc4b-0d0371522842.png)

**Comment by stormsunshine** [comment]
After merging the two arrays, the result array is [1,1,1,2], so the median should be 1.0, which is (1 + 1) / 2. Is there any problem?

**Comment by epicmurloc29** [comment]
Hello.
It's my bad. I removed the duplicates from the merged array by reflex.

Thank you for your patience.
