### ISSUE TITLE
604. Design Compressed String Iterator

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#682]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing constraints/description or test cases

#### Code you used for Submit/Run operation
```
import java.util.regex.Pattern;
public class StringIterator {
    int ptr = 0;
    String[] chars;int[] nums;
    public StringIterator(String compressedString) {
        nums = Arrays.stream(compressedString.substring(1).split("[a-zA-Z]+")).mapToInt(Integer::parseInt).toArray();;
        chars = compressedString.split("[0-9]+");
    }
    public char next() {
        if (!hasNext())
            return ' ';
        nums[ptr]--;
        char res=chars[ptr].charAt(0);
        if(nums[ptr]==0)
            ptr++;
        return res;
    }
    public boolean hasNext() {
        return ptr != chars.length;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Fails this test case

```
["StringIterator","next","next","next","next","next","next","hasNext","next","hasNext"]
[["L1e2t1C1o1d1e10000000000"],[],[],[],[],[],[],[],[],[]]
```

IMO the constraints should be updated to invalidate this test case. The current maximum value is 1234567890 which I verified using assert. So constraint of Integer Max Val will work.

**Comment by lc-christina** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. The team reviewed the test case and considered it invalid. We've used your feedback to add missing constraints to the problem. Since missing constraints is a well-known issue to the old problems, this report won't be eligible for LeetCoins reward. We appreciate your support!
