### ISSUE TITLE
Wrong Space Complexity in 1029. Two City Scheduling

### ISSUE THREAD

**Issue by andyliangtw** [LeetCode-Feedback/LeetCode-Feedback#6820]
#### Your LeetCode username

andyliangtw

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[1029. Two City Scheduling](https://leetcode.com/problems/two-city-scheduling/solution/)

It uses "sorting" in the solution, but the "sorting" still needs more than `O(1)` space complexity.
It depends on the sorting method and the language we use. e.g. Python's built-in sorting is Timsort, which takes `O(n)` space complexity in the worst case. Other languages may take `O(log(n))` space complexity.
Thus, the space complexity is definitely NOT ONLY `O(1)`.

**Comment by LC-Sue** [comment]
Hi @andyliangtw 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
