### ISSUE TITLE
Missing Test Case - 627. Swap Salary

### ISSUE THREAD

**Issue by Shashank-mankala1** [LeetCode-Feedback/LeetCode-Feedback#6825]
#### Category of the bug
- [ ] Question-> 627 Swap Salary
- [ ] Solution ->update salary set sex = IF (sex = "m", "f", "m");
- [ ] Language-> MySQL
- [ ] Missing Test Cases 

#### Description of the bug

The default test case causing error while running by pressing Run code button

#### Code you used for Submit/Run operation

```
// Swap Salary
update salary set sex = IF (sex = "m", "f", "m");
```

#### Language used for code

MySQL

#### Screenshots

![image](https://user-images.githubusercontent.com/57833493/160228831-fd12df29-01e7-49b4-92b8-b01ee4302981.png)

**Comment by LC-Sue** [comment]
Hi @Shashank-mankala1,
Thank you for reaching out to us, please refer to the code below
UPDATE salary
SET
    sex = CASE sex
        WHEN 'm' THEN 'f'
        ELSE 'm'
    END;
