### ISSUE TITLE
Missing Test Case - 1491. Average Salary Excluding the Minimum and Maximum Salary

### ISSUE THREAD

**Issue by nenvy** [LeetCode-Feedback/LeetCode-Feedback#6828]
#### Your LeetCode username

username: nettoko

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I ran my code in PyCharm, I got the expected output (41111.11111). However, when I submitted my code, it said the output was wrong (41111.00000). I don't understand why the decimal points would be off, so I'm guessing it might be a bug. Please let me know.

UPDATE:
I've tried using the same code with Python3... and it worked. But would the version of Python even matter in this case? Is that really the issue? I can't tell.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def average(self, salary):

        return round((sum(salary) - min(salary) - max(salary)) / (len(salary) - 2), 5)

```

#### Expected behavior

 I had expected my code to work. When I ran my code in PyCharm, I got the expected output (41111.11111). However, when I submitted my code, it said the output was wrong (41111.00000). I don't understand why the decimal points would be off, so I'm guessing it might be a bug. Please let me know.

#### Screenshots

![image](https://user-images.githubusercontent.com/95558092/160265155-03beb6d0-d042-4a93-91b4-a27919cc1805.png)

![image](https://user-images.githubusercontent.com/95558092/160265175-2ad31f56-91fa-4bd5-a4f6-edc0fd367fd5.png)

**Comment by Vortwx** [comment]
Set your type to double will do

**Comment by Imyaminov** [comment]
Divide flaot to float then you get result in floating point whatever after dot. In that case return type of your function is int as float divided to int. convert denominator to "float(len(salary) - 2)"
