### ISSUE TITLE
BLOCKED - Incomplete question description - Missing constraints - 303. Range Sum Query - Immutable

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#683]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

An easy question is Time Limit Exceeded even with multiple optimal solutions, including segment tree & prefix sum
https://leetcode.com/problems/range-sum-query-immutable/

Please add Constraints to the question.
- What is the length of the array?
- How many calls are made to sumRange function?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior
Expected:

Question should have clear constraints:

An easy question is Time Limit Exceeded even with multiple optimal solutions, including segment tree & prefix sum
https://leetcode.com/problems/range-sum-query-immutable/

Please add Constraints to the question.
- What is the length of the array?
- How many calls are made to sumRange function?

Actual:

Constraints are missing in the question.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
