### ISSUE TITLE
The expected output is wrong.

### ISSUE THREAD

**Issue by basnetraunak** [LeetCode-Feedback/LeetCode-Feedback#6831]
# 1528. Shuffle String

### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

### Description of the bug
The output seems wrong, in my opinion, the output should be "leetcdoe" instead of "leetcode" for the given input ( "codeleet" and [4,5,6,7,0,2,1,3]).

### Code you used for Submit/Run operation

```
var restoreString = function(s, indices) {
    let arr=[ ];
    for(let i = 0;i < s.length;i++) {
        arr.push(s[indices[i]]);        
        console.log(s[i],indices[i],arr[i],i);
    }
    return arr.join("");
};
```

### Language used for code
JavaScript

### Expected behavior
The Expected output should be "leetcdoe".

**Comment by LC-Sue** [comment]
Hi @basnetraunak,
Thank you for reaching out the us, the expected output is correct. Please refer to the image below.
![image](https://user-images.githubusercontent.com/92285126/160781103-42243907-3dab-4e14-bdd1-cc9b4c91a03b.png)
