### ISSUE TITLE
Question Typo - 2217. Find Palindrome With Fixed Length

### ISSUE THREAD

**Issue by arutsudar** [LeetCode-Feedback/LeetCode-Feedback#6832]
#### Your LeetCode username

arutsudar

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Just a typo.
The `11th` palindrome of length `3` is `202`.
In `Example 1`'s explanation, it is mentioned as
```
The first few palindromes of length 3 are:
101, 111, 121, 131, 141, 151, 161, 171, 181, 191, 201, ...
```
Note the `11th` number is mentioned wrongly as `201` which is not a palindrome.

#### Code you used for Submit/Run operation

Not Applicable

#### Language used for code

Not Applicable

#### Expected behavior

`Example 1`'s explanation should be
```
The first few palindromes of length 3 are:
101, 111, 121, 131, 141, 151, 161, 171, 181, 191, 202, ...
```

#### Screenshots

![image](https://user-images.githubusercontent.com/33226200/160280593-c480fc97-c76d-4679-88ca-99e997932c7f.png)

#### Additional context

Not Applicable

**Comment by LC-Sue** [comment]
Hi @arutsudar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @arutsudar 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
