### ISSUE TITLE
Question - 2217. Find Palindrome With Fixed Length

### ISSUE THREAD

**Issue by gaurvag** [LeetCode-Feedback/LeetCode-Feedback#6833]
#### Your LeetCode username
g0rav

#### Category of the bug
- [ ] Question

#### Description of the bug
A typo in Example1 Explanation, the 11th palindrome of length 3 will be 202 instead of 201.

#### Screenshots

![image](https://user-images.githubusercontent.com/56625397/160281857-0961511d-08da-4de1-8022-613be6a0952e.png)

**Comment by arutsudar** [comment]
Seems to be same as the issue https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/6832, that is raised 30-35 mins before this one.

**Comment by LC-Sue** [comment]
Hi @gaurvag 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
