### ISSUE TITLE
201 is not a palindrome. 

### ISSUE THREAD

**Issue by noahabe** [LeetCode-Feedback/LeetCode-Feedback#6835]
#### Category of the bug
- [ ] Question
![Screenshot from 2022-03-28 00-07-04](https://user-images.githubusercontent.com/44489271/160301063-f403c59c-ae0a-4c69-b32d-35a6f8d11b35.png)

#### Description of the bug
201 is not a palindrome. It should be 202

**Comment by noahabe** [comment]
the question is : https://leetcode.com/problems/find-palindrome-with-fixed-length/

**Comment by bogoconic1** [comment]
There are 2 posts on this already

**Comment by noahabe** [comment]
Oh okay, sorry.
