### ISSUE TITLE
Invalid Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by xsgao-github** [LeetCode-Feedback/LeetCode-Feedback#6837]
#### Your LeetCode username
xsgao

#### Category of the bug
- [ ] Invalid Test Cases 

#### Description of the bug
The description says `There is only one repeated number in nums`, but there is a test case which input is `[2,2,2,2,2]`.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int findDuplicate(int[] nums) {
	long s = 0;
	for (int i : nums) {
		s += i;
	}
	// if there is no duplicate
	long g = 0;
	if (nums.length % 2 == 0) {
		g = (((long) nums.length) / 2) * (((long) nums.length) - 1);
	} else {
		g = ((((long) nums.length) - 1) / 2) * ((long) nums.length);
	}
	// TODO if s overflow but g not
	return (int) (s - g);
    }
}
```

#### Language used for code
Java

#### Expected behavior
This test case should be removed.

#### Screenshots
![image](https://user-images.githubusercontent.com/39278329/160308622-673bcaeb-4d26-478f-9eba-833696fe43e1.png)

**Comment by stormsunshine** [comment]
The number 2 is repeated and occurs five times. Is there any problem?

**Comment by xsgao-github** [comment]
`number 2 is repeated and occurs five times` does that count 1, 4 or 5 repeated numbers?

**Comment by stormsunshine** [comment]
All the integers in `nums` appear only **once** except for **precisely one integer** which appears **two or more** times.

In the test case [2,2,2,2,2], the only number in the array is 2 and it appears five times. This is allowed since the repeated number can appear two or more times.

**Comment by xsgao-github** [comment]
Given this array `[1, 2, 3, 4, 2]`, I would say nums[1] is not a repeated number, nums[4] is the **only one** repeated number (not numbers). In this sense, `[2,2,2,2,2]` is not a valid test case. But if you insist, maybe it's better to rephrase the description as `there is one and only one number repeated more or multiple times`.

**Comment by LC-Sue** [comment]
Hi @xsgao-github,
Thank you for reaching out to us, there is only **one** repeated number in nums, test [2,2,2,2,2] has one number repeated multiple times! Sorry for any confusion!
