### ISSUE TITLE
528. Random Pick with Weight

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#684]
#### Your LeetCode username

gordonek

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
Incomprehensible description of the problem.

#### Description of the bug

The way problem statement is described, it makes itself very challenging to understand. 

#### Code you used for Submit/Run operation

Please see [here](https://leetcode.com/problems/random-pick-with-weight/discuss/671509/Please-anyone-explain-this-question), [here](https://leetcode.com/problems/random-pick-with-weight/discuss/671445/Question-explained), [here](https://leetcode.com/problems/random-pick-with-weight/discuss/697151/Who-is-choosing-these-questions), [here](https://leetcode.com/problems/random-pick-with-weight/discuss/671418/Please-Explain), [here](https://leetcode.com/problems/random-pick-with-weight/discuss/672387/Please-explain-the-test-cases-and-what-is-the-meaning-of-input-in-the-test-cases), [here](https://leetcode.com/problems/random-pick-with-weight/discuss/672307/The-question-is-a-pure-piece-of-sh*t.). 

***Problem 1: Luck of an explanation of what are those empty lists in the Input and what are they doing there.*** 
<ins>Answer:</ins> The first list's passing a solution class and "pickIndex" strings right after that corresponds to how many times "pickIndex" is called. The empty lists in a second list (list of the lists) correlate with the number of "pickIndex" strings in the first list. The number of empty lists in a second line of the Input needs to be equal to the number of "pickIndex" from the first line of the Input. 

***Problem 2: Luck of an explanation why a second line in the Input is a list of the lists?***
<ins>Answer:</ins> There are two lists that are called in the driver class. The first list is filled with methods and the second list is filled with arguments to those methods.  

***Problem 3: Since each time is a random pick, the problem doesn't have a unique solution. Under those circumstances how is it possible that the test case results are matched with the user results? How would you distinguish between correct and incorrect solution here?***
<ins>Answer:</ins> LeecCode engineers should answer this question.  

***Problem 4: Why there is a *null* in the Output?***
<ins>Answer:</ins> Method call (?)

#### Language used for code

Python3

#### Expected behavior

To make it easier to understand and follow, clarify a problem statement by incorporating above mentioned answers.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support! Some of your questions are about Leetcode design problems, the team suggests you read more about [design problems](https://leetcode.com/tag/design/).

**Comment by agatagruza** [comment]
Thank you @lc-pam for taking a look and a link to design problems. Highly appreciated!
