### ISSUE TITLE
Error in solution - 1102. Path With Maximum Minimum Value

### ISSUE THREAD

**Issue by kryuki** [LeetCode-Feedback/LeetCode-Feedback#6841]
#### Your LeetCode username

LeetCode ID: kryuki
Name: ababa

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the approach 2, "cur_score" is not defined.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Python

#### Expected behavior

cur_score is not defined

#### Screenshots

![approach2](https://user-images.githubusercontent.com/36336987/160512985-ea0f0b0b-ac52-4be0-ba85-afa2900fa686.jpg)

**Comment by LC-Sue** [comment]
Hi @kryuki 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
