### ISSUE TITLE
Tiny error in solution: 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by bahriddin** [LeetCode-Feedback/LeetCode-Feedback#6842]
#### Your LeetCode username
bahriddin17

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Error:
- In this case 5 cannot be in the list as the length  = n + 1 = 5:
> Note: Binary search will be applied to the numbers in the range [1,n] (inclusive) regardless of the contents of the array. So even if a number does not exist in the array, we will still evaluate it. For example, if the array is [1,2,4,2,5][1,2,4,2,5], the algorithm will first evaluate the number 3 even though that number does not exist in the array.

#### Screenshots

<img width="909" alt="image" src="https://user-images.githubusercontent.com/3971918/160513739-807c0ff7-4ac0-4828-8390-ca3954aca67d.png">

**Comment by LC-Sue** [comment]
Hi @bahriddin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
