### ISSUE TITLE
840. Magic Squares In Grid - faulty test cases or the problem description is faulty

### ISSUE THREAD

**Issue by TheBatmanIRL** [LeetCode-Feedback/LeetCode-Feedback#6846]
#### Your LeetCode username

TheBatmanIRL

#### Category of the bug
- [ ] Question description
- [ ] Faulty Test Cases 

#### Description of the bug

The problem statement  : "A 3 x 3 magic square is a 3 x 3 grid filled with distinct numbers from 1 to 9 such that each row, column, and both diagonals all have the same sum."
That means elements in the 3x3 matrix should be unique and lie between 1 and 9 inclusive. 

#### Code you used for Submit/Run operation

```
bool checkarr(int **grid, int i, int j)
{
    int H[16]={-1};//using hashmap, problem constraint says 0 <= grid[i][j] <= 15
    for(int k = 0; k<9; k++)//loop to find any duplicate, or any zero element or element >9
    {
        if(H[grid[i+k/3][j+k%3]]==grid[i+k/3][j+k%3] || grid[i+k/3][j+k%3]==0 || grid[i+k/3][j+k%3]>9)
        {
            return false;
        }
        H[grid[i+k/3][j+k%3]] = grid[i+k/3][j+k%3];
    }
    
    int arr[8] = {0};//array to store all the column, row and diagonal sums
    for(int k = 0; k <3;k++)
    {
        arr[6] += grid[i+k][j+k]; //first diagonal sum
        arr[7] +=grid[i+k][j+2-k];//second diagonal sum
        arr[k]=grid[i+k][j]+grid[i+k][j+1]+grid[i+k][j+2];//row sum
        arr[3+k] = grid[i][j+k]+grid[i+1][j+k]+grid[i+2][j+k];//column sum
    }
    int check = arr[0];
    for(int x=0; x<8; x++)// loop to check if all column, row, diagonal sums are same
    {
        if(arr[x]!=check){return false;}
    }
    return true;
}
        
int numMagicSquaresInside(int** grid, int gridSize, int* gridColSize){
    if(gridSize < 3 || *gridColSize < 3){return 0;}
    int m = gridSize-2; 
    int n = *gridColSize-2; // each(m,n) conveys a single 3x3 matrix in the given grid
    int count = 0;
    for(int i=0; i <m; i++)
    {
        for(int j = 0; j< n;j++)//loop to pass each 3x3 arr from grid to helper function
        {
            if(checkarr(grid,i,j)){count++;}//using helper array check if the 3x3 array passed to the function meets all the criteria of the problem.
        }
    }
    return count;
}
```

#### Language used for code

C

#### Expected behavior

for the test case : [[8,0,7,4,3,2],[1,10,4,4,3,8],[8,5,2,9,5,1],[6,0,9,2,7,6],[9,0,6,9,5,1],[4,2,1,4,3,8]]
the expected output is 2, whereas as per problem statement, the actual answer is only 1.
because only the sub array [[4,3,8],[9,5,1],[2,7,6]] meets the criteria that all elements lie inside 1 and 9.
but there is another sub array that meets the all column, row and both diagonal sums being equal
[[1,10,4],[8,5,2],[6,0,9]], but elements of this 3x3 matrix do not meet magic square criteria of the problem

#### Additional context

https://leetcode.com/submissions/detail/669667395/

**Comment by LC-Sue** [comment]
Hi @TheBatmanIRL,
Thank you for reaching out to us, the code you provided is accepted with no issue. Please refer to the screenshot below.
![image](https://user-images.githubusercontent.com/92285126/160784123-5eebe395-bee3-4355-a561-ab58288360bb.png)
