### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by dancing4am** [LeetCode-Feedback/LeetCode-Feedback#6847]
#### Your LeetCode username
dancing4am

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
3. Longest Substring Without Repeating Characters:
code is compiled when test, also in VS, but cannot submit.
on try to submit, it says:

Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
Line 3: Solution.LengthOfLongestSubstring(String s) in Solution.cs
Line 33: __Driver__.Main(String[] args) in __Driver__.cs

on line 3, which is just " int longest = 1; ".

#### Code you used for Submit/Run operation
```
public class Solution {
    public int LengthOfLongestSubstring(string s) {        
        int longest = 1;
        List<char> tmp = new List<char>();
        tmp.Add(s[0]);
        for (int i = 0; i < s.Length; i++)
        {
            for (int j = 0; j < tmp.Count; j++)
            {
                if (String.Equals(tmp[j], s[i]))
                {   
                    longest = longest < tmp.Count ? tmp.Count : longest;
                    tmp.Clear();
                }
            }
            tmp.Add(s[i]);
        }        
        return longest;
    }
}
```

#### Language used for code
C#

#### Expected behavior
should be able to submit

#### Screenshots
![image](https://user-images.githubusercontent.com/56695129/160714690-f448c214-918a-4dd3-b67b-adf3064f9d32.png)

**Comment by LC-Sue** [comment]
Hi @dancing4am,
Thank you for reaching out to us, the judger appears to be running correctly. Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
