### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by riturajsacademic** [LeetCode-Feedback/LeetCode-Feedback#6848]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x ] Bad test CAse 

#### Description of the bug

One of the input is 

```
[5,0,0,0]
3
```

which it gives as wrong answer:
```
Wrong Answer
[Details ](https://leetcode.com/submissions/detail/670046053/)
Input
[5,0,0,0]
3
Output
false
Expected
true
```

It is impossible that sub-array has a contiguous sum which is divisible by 3.

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean checkSubarraySum(int[] nums, int k) {
        int totalSum = 0;
        for (int i = 0; i < nums.length; i++) {
            totalSum += nums[i];
        }
        
        int start = 0;
        int end = nums.length - 1;
        while(start < end) {
            
            if ((totalSum%k == 0 && totalSum!=0) ||
                ((totalSum - nums[start])%k == 0 && (totalSum - nums[start])!= 0) ||
                ((totalSum - nums[end])%k == 0 && (totalSum - nums[end])!= 0)) {
                return true;
            } else {
                totalSum = totalSum - nums[start] - nums[end];
                start++;
                end--;
            }
        }
        
        return false;
    }
}
```

#### Language used for code
java

#### Expected behavior
It should return false.

**Comment by stormsunshine** [comment]
There exist six subarrays with sum 0, and 0 is divisible by 3.

**Comment by LC-Sue** [comment]
Hi @riturajsacademic,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Please also refer to the discuss section of the problem to see how other users' have optimized their codes!
