### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by dancing4am** [LeetCode-Feedback/LeetCode-Feedback#6849]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
5. Longest Palindromic Substring:
Can compile and the same in VS,
but cannot submit with error that does not make sense

#### Code you used for Submit/Run operation

```
public class Solution {
    public string LongestPalindrome(string s) {
        List<char> descen = s.ToCharArray().ToList();
        descen.Reverse();
        int counter = 0;
        int longest = 0;
        int longindex = 0;
        int inneri = 0;
        for (int i = 0; i < s.Length; i++)
        {
            inneri = i;
            for (int j = 0; j < s.Length; j++)
            {
                if (s[inneri] == descen[j])
                {
                    inneri = j+i;
                    counter++;
                    if (counter > longest)
                    {
                        longest = counter;
                        longindex = i;
                    }
                }
            }
            counter = 0;
        }
        return s.Substring(longindex, longest);
    }
}
```

#### Language used for code
C#

#### Expected behavior
Can submit

#### Screenshots
![image](https://user-images.githubusercontent.com/56695129/160741638-da76b723-e756-4a0c-8b95-4c4a5b74e8ec.png)

**Comment by LC-Sue** [comment]
Hi @dancing4am 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
