### ISSUE TITLE
166. Fraction to Recurring Decimal - Wrong algorithm that is accepted!

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#685]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

For 2 and 3 as input, the algorithm outputs 0.6(6) instead of 0.(6).
For 1 and 333 as input, the algorithm outputs 0.0(030) instead of 0.(003).
For 4 and 333 as input, the algorithm outputs 0.0(120) instead of 0.(012). 

#### Code you used for Submit/Run operation

```
def fractionToDecimal(self, numerator: int, denominator: int) -> str:
    if numerator == 0: return "0"
    isNeg = True if (numerator < 0) ^ (denominator < 0) else False
    numerator, denominator = abs(numerator), abs(denominator)
    
    res = []
    if isNeg: res.append("-")

    res.extend(str(numerator // denominator))
    numerator = numerator % denominator
    
    if numerator > 0: res.append(".")
    
    dic = dict()
    while numerator > 0:
        numerator *= 10
        res.append(str(numerator // denominator))
        numerator = numerator % denominator
        
        if numerator in dic:
            res.insert(dic[numerator], "(")
            res.append(")")
            break
        
        dic[numerator] = len(res)
        # res.extend(str(numerator))
    
    return "".join(res)
```

#### Language used for code

Python3

#### Expected behavior

I do agree that those numbers are effectively the same (besides one extra last digit being added for the first group of numbers):
2/3 = 0.6(6) = 0.(6) = 0.6666666...
1/333 = 0.0(030) = 0.(003) = 003033033033...
4/333 = 0.0(120) = 0.(012) = 012012012012...

However it looks very confusing when Input is different than Output, and yet, submission is accepted. Suggestion is to put both answers into the Output field. 

#### Screenshots

<img width="531" alt="Capture1" src="https://user-images.githubusercontent.com/7014697/88165426-8b5a3a80-cbca-11ea-826f-4657bfa1af36.PNG">

<img width="527" alt="Capture2" src="https://user-images.githubusercontent.com/7014697/88165529-afb61700-cbca-11ea-956f-513cb0bdbcab.PNG">

<img width="526" alt="Capture3" src="https://user-images.githubusercontent.com/7014697/88166346-f6f0d780-cbcb-11ea-878d-8ca183482f31.PNG">

#### Additional context

Please see https://leetcode.com/problems/fraction-to-recurring-decimal/discuss/456258/Wrong-algorithm-that-is-accepted!

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by agatagruza** [comment]
Thank you @lc-pam for an update :sparkles: Appreciate it :sparkles: !
