### ISSUE TITLE
TestCase incorrectly invalidated | 167. Two Sum II - Input Array Is Sorted

### ISSUE THREAD

**Issue by theassassin010** [LeetCode-Feedback/LeetCode-Feedback#6850]
#### Your LeetCode username

thewindrunner

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Testcase: 
[2,7,11,11,11,15]
22
The error message received from Leetcode is: Solution either does not exist or is not unique
This is a valid testcase. 
1. It is a non-decreasing sequence. 
2. It has a unique solution (index1=0, index2=5) -- return value of [1,6].

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int>& numbers, int target) {
        int n = numbers.size();
        
        int l = 0, r = n-1;
        
        while(l < r) {
            int sum = numbers[l]+numbers[r];
            if(sum == target) return {l+1, r+1};
            else if(sum < target) ++l;
            else --r;
        }
        return {-1, -1};
    }
};
```

#### Language used for code
C++

#### Expected behavior
Testcase should run without any validation failures

**Comment by stormsunshine** [comment]
This test case is indeed invalid since it has four possible answers, which are [1,6], [3,4], [3,5], [4,5]. Seems that you do not notice that 11 + 11 = 22.

**Comment by LC-Sue** [comment]
Hi @theassassin010,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts. Please also feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
