### ISSUE TITLE
 Missing Test Case - 560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by namit2saxena** [LeetCode-Feedback/LeetCode-Feedback#6851]
#### Your LeetCode username
namit2saxena

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Leetcode accepted my wrong solution because of the following missing test case:

For the below test case, my solution gives the answer 9 whereas the expected answer is 8. 
Input: nums =  [0, 0, 0, 5,-1,-2,3], k = 5
My code's output: 9
Expected output is: 8

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int subarraySum(vector<int>& nums, int k) {
        unordered_map<int, int> mp;
        int n = nums.size(), sum = 0, ans = 0;
        mp[0] = 1;
        for(int i=0; i<n; i++){
            sum += nums[i];
            ans += (mp[sum-k]) + (k!=0 && sum==k?mp[k]:0);
            mp[sum]++;
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Since there are total of 8 subarrays where the sum is equal to 5, as my code prints 9, that means my solution shouldn't have got accepted.

**Comment by LC-Sue** [comment]
Hi @namit2saxena 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @namit2saxena 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
