### ISSUE TITLE
Missing Test Case - 371. Sum of Two Integers

### ISSUE THREAD

**Issue by SnehaVarshney11** [LeetCode-Feedback/LeetCode-Feedback#6852]
#### Your LeetCode username
Sneha_Varshney

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation
```class Solution {
    public int getSum(int a, int b) {
        // use xor, and, left shift
        // xor = a^b, carry = a^b, carry<<1, xor = xor^carry, carry = xor&carry
        int xor = a^b;
        int carry = a&b;
        if(carry == 0)
            return xor;
        else
            return getSum(xor, carry<<1);
    }
}
```

#### Language used for code
JAVA

**Comment by namit2saxena** [comment]
You forgot to mention the missing test case.

**Comment by LC-Sue** [comment]
Hi @SnehaVarshney11 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
