### ISSUE TITLE
1337. The K Weakest Rows in a Matrix. Complexity analysis typo.

### ISSUE THREAD

**Issue by JafarJuneidi** [LeetCode-Feedback/LeetCode-Feedback#6853]
#### Your LeetCode username

JafarJuneidi

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

1337. The K Weakest Rows in a Matrix 
Approach 2: Linear Search and Map: The time complexity of sorting should be O(m log m), but it's O(m m) at the end of the second paragraph.

**Comment by LC-Sue** [comment]
Hi @JafarJuneidi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @JafarJuneidi 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
