### ISSUE TITLE
15题 三数之和 第317个用例 执行结果和题解及评论区多个答案结果一致 却报解答错误

### ISSUE THREAD

**Issue by zhangalexhy** [LeetCode-Feedback/LeetCode-Feedback#6854]
**你的 LeetCode 用户名**
qqqqiannian

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
javaScript

**你提交或者运行的代码**
```
/**
 * @param {number[]} nums
 * @return {number[][]}
 */
var threeSum = function (nums) {
  if (nums.length < 3) {
    return []
  }
  const arr = nums
  const map = {};
  const res = [];
  for (let i = 0; i < arr.length - 2; i++) {
    for (let j = i + 1; j < arr.length - 1; j++) {
      const s = arr[i] + arr[j]
      if (map[-s] !== undefined && map[-s] !== -1 && map[-s] !== i && map[-s] !== j) {
        if (!map[[arr[i], arr[j], 0 - s].sort()]) {
          const a = [arr[i], arr[j], 0 - s].sort();
          map[a] = true;
          res.push(a)
        }
      }
      else if (map[0 - s] === -1) {
        continue;
      }
      else {
        let flag = arr.findIndex((item, index) => {
          return index !== i && index !== j && item === 0 - s
        })
        if (flag !== -1) {
          if (!map[[arr[i], arr[j], 0 - s].sort()]) {
            const a = [arr[i], arr[j], 0 - s].sort();
            map[a] = true;
            res.push(a)
          }
        }
        map[0 - s] = flag;
      }
    }
  }
  return res;
};
```

**期望行为**
不知道结果判定标准是啥，假如正确答案是[[-1, 0, 1], [-2, -1, 3]]，而我的答案是[[-2, -1, 3], [-1, 0, 1]]，这样算正确吗

**屏幕截图**
![image](https://user-images.githubusercontent.com/51531505/160774393-6483c754-a1ac-4198-859e-ce3daccae5b9.png)

**额外的上下文**
添加额外的上下文信息

**Comment by LC-Sue** [comment]
Hi @zhangalexhy,
Thank you for reaching out to us, our judger is running correctly. Please feel free to refer to the discuss section to see how other users' have optimized their codes! The actual output must match the expected output for the code to be accepted.

**Comment by zhangalexhy** [comment]
please tell me how to view the full expected results.&nbsp;&nbsp;If the expected result is too long, it will be cut to ...






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月30日(星期三) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 15题 三数之和 第317个用例 执行结果和题解及评论区多个答案结果一致 却报解答错误 (Issue #6854)





 
***@***.***,
感谢您联系我们，我们的判断器运行正常。请随意参考讨论部分，看看其他用户是如何优化他们的代码的！实际输出必须与预期输出相匹配，代码才能被接受。
 
—
直接回复此邮件，在GitHub上查看，或者取消订阅.
你收到这封信是因为有人提到了你。Message ID: ***@***.***&gt;
