### ISSUE TITLE
Wrong Test Case - 269. Alien Dictionary

### ISSUE THREAD

**Issue by Jawadaz** [LeetCode-Feedback/LeetCode-Feedback#6855]
#### Your LeetCode username
Jazz1980

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong test case

#### Description of the bug
The test case with input data: ["abc","ab"]
Have an expected output of "". which means "there is no solution". while any order of a,b and c represented a valid order to which the input data is coherent. 

#### Expected behavior
Any order or a,b and c should be fine.

**Comment by LC-Sue** [comment]
Hi @Jawadaz,
Thank you for reaching out to us, could you please provide the full code used for submission?
