### ISSUE TITLE
c++程序运行时报错

### ISSUE THREAD

**Issue by 20164206160** [LeetCode-Feedback/LeetCode-Feedback#6857]
**思念是种病**
思念是种病

**程序运行时报错 runtime error**
- [剑指 Offer 63 ] 题目
- [ ] 题解
- [c++ ] 编程语言
- [[] ] 缺少测试用例

**描述**
当输入长度=0时

**c++**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    int maxProfit(vector<int>& prices) {
        for(int i=0;i<prices.size()-1;i++)
        {
            prices[i] = prices[i+1] - prices[i];
        }
        int num = 0,ans = 0;
        for(int i=0;i<prices.size()-1;i++)
        {
            num = num + prices[i];
            if(num>ans){
                ans = num;
            }
            if(num<0){
                num = 0;
            }
        }
        return ans;
    }
};
```

**期望行为**
当输入[]时，不应该执行for里的内容,

**屏幕截图**
![image](https://user-images.githubusercontent.com/26060329/160882232-af746ee4-23d7-4d5c-83c1-2d4dad4a76ca.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，在与相关团队核实后：prices.size()-1 的结果不是 -1， 因为 .size()  的类型是无符号整数

以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
