### ISSUE TITLE
Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by RishabhGoyal992** [LeetCode-Feedback/LeetCode-Feedback#6858]
#### Your LeetCode username
rishabhgoyal992

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
The test cases could have been stronger if there would have been nums[I] (maximum jump length at an ith position) greater than the length of the nums array.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @RishabhGoyal992 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
