### ISSUE TITLE
Missing Test Case - 1491. Average Salary Excluding the Minimum and Maximum Salary

### ISSUE THREAD

**Issue by drag0o0n** [LeetCode-Feedback/LeetCode-Feedback#6859]
#### Category of the bug
- [ ] Question
- [ *] Solution 
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution(object):
    
    def average(self, salary):
        avg =0
        count =0
        salary.sort()
        for x in range(len(salary)):
            if (x>=1) and (x<= (len(salary)-2)):
                avg = avg + salary[x]
                count = count +1
                answer = avg / count 
      
        return answer
      


  
```

#### Screenshots

https://drive.google.com/file/d/1I5WkcCvVWSoXynuoazILJ4XTrRv9-Zw_/view?usp=sharing

**Comment by LC-Sue** [comment]
Hi @drag0o0n 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
