### ISSUE TITLE
166. Fraction to Recurring Decimal - invalid test case

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#686]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Both numerator and denominator are integers. Integer limits are **[-2,147,483,648 : 2,147,483,647]**. When using **-2,147,483,647** as a denominator, I am getting `Time Limit Exceeded` (even though number is within the limits). The best part is that **-2,147,483,648** which is the lower bound of int (min allowed) works just fine.  

#### Code you used for Submit/Run operation

```
class Solution:
    def fractionToDecimal(self, numerator: int, denominator: int) -> str:
        if numerator == 0:
            return "0"
        left = ""
        if numerator * denominator < 0:
            left = "-"
            numerator, denominator = abs(numerator), abs(denominator)
        div, rem = divmod(numerator, denominator)
        left += str(div)
        right, mods = [], {}
        while rem:
            if rem in mods:
                break
            mods[rem] = len(right)
            div, rem = divmod(10 * rem, denominator)
            right.append(str(div))
        if right and rem:
            return "{}.{}({})".format(
                left, "".join(right[:mods[rem]]), "".join(right[mods[rem]:]))
        elif right:
            return "{}.{}".format(left, "".join(right))
        else:
            return left
```

#### Language used for code

Python3

#### Expected behavior

Calculate the rational number and show a full value of that number. 

#### Screenshots

<img width="243" alt="Capture1" src="https://user-images.githubusercontent.com/7014697/88169639-1fc79b80-cbd1-11ea-84b0-d62fc05c6876.PNG">  |  <img width="205" alt="Capture2" src="https://user-images.githubusercontent.com/7014697/88169637-1f2f0500-cbd1-11ea-8296-b93d297b0fc2.PNG">
:-------------------------:|:-------------------------:

<img width="276" alt="Capture3" src="https://user-images.githubusercontent.com/7014697/88169638-1fc79b80-cbd1-11ea-9895-ecee9bf1ed0d.PNG">

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for your time. The team carefully reviewed your report but the provided test cannot be represented as fraction, so the team decided not to update the problem. We appreciate your support!
