### ISSUE TITLE
C++函数执行效果问题

### ISSUE THREAD

**Issue by ADExxxxxx** [LeetCode-Feedback/LeetCode-Feedback#6860]
**你的 LeetCode 用户名**

leetcode-cn.com/u/aaaaaad-2/

**Bug 类型**
- [x] 题目
- [x] 编程语言

**描述**
C++函数执行效果问题

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
void rotate(vector<int>& nums, int k) {
    int sz = nums.size();
    int sq = k < sz ? k : k % sz;
    if(sq == 0) return;
    nums.insert(nums.begin(), nums.end() - sq, nums.end());
    nums.erase(nums.begin() + sz, nums.end());
}
```

**期望行为**
insert函数实现将尾部多个数据插入首部。
这里针对nums = [1, 2, 3],    k = 1   进行测试，插入结果却为[2, 1, 2, 3]（理论上应该是[3, 1, 2, 3]）。
而针对nums = [1, 2, 3, 4], k = 1   进行测试，插入结果[4,1,2,3,4](正确)

**屏幕截图**

**额外的上下文**
为证明代码无误，在外部编译器（g++，msvc）进行测试均无误。可否帮忙查看一下是存在什么问题吗？

**Comment by feiceh** [comment]
感谢反馈，已转给题目运营团队会尽快确认。
