### ISSUE TITLE
Missing Test Case - 410. Split Array Largest Sum

### ISSUE THREAD

**Issue by manumathew23** [LeetCode-Feedback/LeetCode-Feedback#6862]
#### Your LeetCode username
manumathew

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Two edge test cases with number of subarrays 'm'  = 1 and 'm' = length(nums)

#### Code you used for Submit/Run operation

```
class Solution:
    def splitArray(self, nums: List[int], m: int) -> int:
        l, h = max(nums), sum(nums)
        while l < h:
            mi = (l+h)//2
            t, c = 0, 1
            for n in nums:
                if t+n<=mi:
                    t += n
                else:
                    t = n
                    c += 1
            if c>m: l = mi+1
            else: h = mi
        return h
```

#### Language used for code
Python3

#### Expected behavior
Missing two test cases mentioned below:
[1,2,3,4,5]
1
[1,2,3,4,5]
5

**Comment by LC-Sue** [comment]
Hi @manumathew23,
Thank you for reaching out to us, both the test cases you provided are accepted with no issue. Please provide a test case that fails the code!
