### ISSUE TITLE
Missing Test Case - 200. Number of Islands

### ISSUE THREAD

**Issue by sangwan18** [LeetCode-Feedback/LeetCode-Feedback#6863]
#### Category of the bug
- [ ] Question
- [200 Number of Islands ] Solution
- `[Python` ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

class Solution:
    def numIslands(self, grid: List[List[str]]) -> int:
        if grid==[]:
            return 0
        directions=[[-1,0],[1,0],[0,-1],[0,1]]
        ROWS,COLS=len(grid),len(grid[0])
        count=0
        
        def dfs(row,col):
            if row<0 or row>=ROWS or col<0 or col>=COLS:
                return
            if grid[row][col]=="1":
                grid[row][col]="0"
                for direction in directions:
                    newrow = row+direction[0]
                    newcol = col+direction[1]
                    dfs(newrow,newcol)
        
        
        for row in range(ROWS):
            for col in range(COLS):
                if grid[row][col]=="1":
                    count+=1
                    dfs(row,col)
        return count
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @sangwan18 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
