### ISSUE TITLE
Missing Test Case - 374. Guess Number Higher or Lower

### ISSUE THREAD

**Issue by 18-RAJAT** [LeetCode-Feedback/LeetCode-Feedback#6865]
#### Category of the bug
- [ ] Question.
- [ ] Solution.
- [x] Language.
- [x] Missing Test Cases.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by 18-RAJAT** [comment]
Missing Test cases

**Comment by LC-Sue** [comment]
Hi @18-RAJAT 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
