### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by gouravgo** [LeetCode-Feedback/LeetCode-Feedback#6866]
#### Your LeetCode username
garg26

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
There is a missing test case. Add a test case for this input.
Input example - [2,1,5,0,-2,-3,-1]

#### Language used for code
C++

#### Expected behavior
Input - [2,1,5,0,-2,-3,-1] 
This input should be tested in the final submission and it should return false.

**Comment by LC-Sue** [comment]
Hi @gouravgo 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
