### ISSUE TITLE
Heap Learn Card - Heap Insertion - No video playback

### ISSUE THREAD

**Issue by TheArchDev** [LeetCode-Feedback/LeetCode-Feedback#6867]
#### Your LeetCode username

TheArchDev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Within the Heap Learning card, in the [Heap Insertion](https://leetcode.com/explore/learn/card/heap/643/heap/4019/) page, there is a video which is meant to display the mechanism for inserting into a heap. Instead, the home page of Vimeo is displayed within the frame where the video asset would be.

#### Expected behavior

Expect there to be a specific video explaining heap insertion which is able to be played directly on the LeetCode page.

#### Screenshots

![Screenshot 2022-03-31 at 21 22 47](https://user-images.githubusercontent.com/13932330/161142940-bd00c6cd-9f5d-41e4-819b-c33391ea76ba.png)

#### Additional context

Logged in as a LeetCode Premium user.

**Comment by LC-Sue** [comment]
Hi @TheArchDev,
Thank you for reaching out to us, the video is playing fine from my end. Please try to access from a different browser or clear cache!
