### ISSUE TITLE
627. Swap Salary : Incorrect test case expects SELECT instead of UPDATE statement

### ISSUE THREAD

**Issue by vatsaashwin** [LeetCode-Feedback/LeetCode-Feedback#6868]
#### Your LeetCode username
vatsaashwin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The question requires us to write an UPDATE statement. However, the test cases expect a SELECT statement. The question and listed solution is correct. However, one can simply not submit any correct solution. The discussions following the solution also mention facing the same problem while submitting.
Bug: When we run the below code, we see this error:
Invalid Testcase: 'salary'

#### Code you used for Submit/Run operation

```
 UPDATE salary
  SET sex = 
    CASE  
        when sex= 'f' then 'm' 
        when sex='m' then 'f' 
        else sex   
    END
  ;
```

#### Language used for code
SQL

#### Expected behavior
The above update statement should be accepted and tested against valid test cases.

#### Screenshots

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/32829057/161189131-041de8fa-137a-4104-9574-6a3893476e57.png">

**Comment by LC-Sue** [comment]
Hi @vatsaashwin,
Thank you for reaching out to us, the code you provided is accepted with no issue. Please feel free to refer to the screenshot below!
![image](https://user-images.githubusercontent.com/92285126/162132230-4cef0e61-cb10-4afe-ba4d-b0b18317fe99.png)

**Comment by vatsaashwin** [comment]
It worked yesterday but has seemed to have stopped working again. Showing the same error message. Screenshot: 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/32829057/162349179-816b2f54-5f05-4cc3-820b-a3f7ad4d0eb4.png">
