### ISSUE TITLE
interface glitch

### ISSUE THREAD

**Issue by loulafg** [LeetCode-Feedback/LeetCode-Feedback#6869]
#### Your LeetCode username

loulafg

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Every now and then my code suffers an unexplained disturbance, and all lines seem to flip their order. It sometimes apears to be related to pressing the mouse, but for most it is spontaneous. It always happens when I presee page up, although it does not seem to be related to any feature of the platform.

#### Code you used for Submit/Run operation
 It has nothing to do with any particular code.  

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @loulafg,
Thank you for reaching out to us, for assistance of bugs, please reach out to support@leetcode.com !
