### ISSUE TITLE
Find Pivot Index - bad hint

### ISSUE THREAD

**Issue by An1s9n** [LeetCode-Feedback/LeetCode-Feedback#6870]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

in [this](https://leetcode.com/explore/learn/card/array-and-string/201/introduction-to-array/1144) task there is a Hint which says following:
`We can precompute prefix sums P[i] = nums[0] + nums[1] + ... + nums[i-1]. Then for each index, the left sum is P[i], and the right sum is P[P.length - 1] - P[i] - nums[i].`
I assume there is `nums[nums.length - 1]` summand missing and it should be added as follows:
`We can precompute prefix sums P[i] = nums[0] + nums[1] + ... + nums[i-1]. Then for each index, the left sum is P[i], and the right sum is P[P.length - 1] + nums[nums.length - 1] - P[i] - nums[i].`

#### Code you used for Submit/Run operation

N/A

#### Language used for code
N/A

#### Expected behavior

N/A

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Sue** [comment]
Hi @An1s9n 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @An1s9n,
The statement in question is:

the right sum is P[P.length - 1] - P[i] - nums[i]

so we want to find the sum of all numbers to the right of nums[i] by leveraging the prefix sum array. Let's break down the statement.

P[P.length - 1] equals the sum of all of the numbers
P[i] equals the sum of all the numbers to the left of index i

So P[P.length - 1] - P[i] is the sum of all numbers between index i and the end of the array (including nums[i]). But we only want the sum of all the numbers to the right of index i. Not including nums[i]. So we must subtract nums[i].

Thus the statement the right sum is P[P.length - 1] - P[i] - nums[i] is correct.

We appreciate your support!
