### ISSUE TITLE
Missing Test Case - 1790. Check if One String Swap Can Make Strings Equal

### ISSUE THREAD

**Issue by DivijH** [LeetCode-Feedback/LeetCode-Feedback#6872]
#### Your LeetCode username
Divij21

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The solution was accepted due to a missed test case. Add
"bankb"
"kannb"
to the test case

#### Code you used for Submit/Run operation

```
class Solution:
    def areAlmostEqual(self, s1: str, s2: str) -> bool:
        if set(s1) != set(s2):  # checking for not common characters
            return False
        p = []
        for i in range(len(s1)):
            if s1[i] != s2[i]:
                p.append(1)

        return not sum(p) or sum(p) == 2
```

#### Language used for code

Python

#### Expected behavior

The above code is accepted as a valid solution, even though it is the incorrect solution. The above-mentioned test case helps in verifying this problem.

**Comment by LC-Sue** [comment]
Hi @DivijH 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
