### ISSUE TITLE
Missing Language - 344. Reverse String

### ISSUE THREAD

**Issue by dunyakirkali** [LeetCode-Feedback/LeetCode-Feedback#6873]
Problem 344 is not possible to complete in Elixir

#### Your LeetCode username
dunyakirkali

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem 344 is not possible to complete in Elixir

**Comment by LC-Sue** [comment]
Hi @dunyakirkali,
Thank you for reaching out to us, the language may have been excluded as it may not be possible to solve in that particular language.

**Comment by dunyakirkali** [comment]
@LC-Sue but reversing a string is definitely possible in Elixir :)

If you could point me in the right direction, I'd be more than happy to contribute

**Comment by LC-Sue** [comment]
Please reach support@leetcode.com!
