### ISSUE TITLE
Missing constraints in 1087

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#6874]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the problem statement of https://leetcode.com/problems/brace-expansion/ it's not clearly mentioned that the following test case is an invalid test case 

`"{ab,cde}"`

#### Expected behavior
Problem statement should explicitly mention that only a single letter character is possible between commas inside brackets.

**Comment by LC-Sue** [comment]
Hi @snehasishroy,
Thank you for reaching out to us, in the problem description it mentions, 
If there is one option, the letter is represented as is.
If there is more than one option, then curly braces delimit the options. For example, "{a,b,c}" represents options ["a", "b", "c"].
