### ISSUE TITLE
Unclear question: Consecutive Numbers

### ISSUE THREAD

**Issue by snugghash** [LeetCode-Feedback/LeetCode-Feedback#6878]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Question is unclear on whether Id column will be consecutive. Judge assumes so. 

#### Additional context
This is just a choice on whether to make the question a little harder - the quesiton is not explicit about it and causes confusion in the discussion section: https://leetcode.com/problems/consecutive-numbers/discuss/53418/Simple-solution

**Comment by LC-Sue** [comment]
Hi @snugghash 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @snugghash 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
