### ISSUE TITLE
Imporvement in the problem Statement  - 278. First Bad Version

### ISSUE THREAD

**Issue by pulkit-rajpal** [LeetCode-Feedback/LeetCode-Feedback#6879]
#### Category of the bug
- [v] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description of the problem statement is not complete.
I believe, the explanation of the parameter should be added to the description of the Problem.
Like what's n and what'bad 

Sample test case : 
Input: n = 5, bad = 4
Output: 4

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @pulkit-rajpal,
Thank you for reaching out to us, the description under the example provides explanation.
Input: n = 5, bad = 4
Output: 4
Explanation:
call isBadVersion(3) -> false
call isBadVersion(5) -> true
call isBadVersion(4) -> true
Then 4 is the first bad version.

Please also feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
