### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by andreiasi** [LeetCode-Feedback/LeetCode-Feedback#6880]
#### Your LeetCode username

andreiasi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

the result of the test case is wrong:
-2147483648 / -1 = 2147483648 instead of 2147483647

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @andreiasi 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
