### ISSUE TITLE
Missing Test Case - 2154. Keep Multiplying Found Values by Two

### ISSUE THREAD

**Issue by itibs** [LeetCode-Feedback/LeetCode-Feedback#6881]
#### Your LeetCode username
tibs

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
It's not a missing test case, but a wrong test case.
https://leetcode.com/submissions/detail/672071757/
Here I have a runtime exception because of a value greater than 1000, but in the problem it states that all numbers are at most 1000.

#### Code you used for Submit/Run operation

```
func findFinalValue(nums []int, original int) int {
    numsSet := make([]bool, 1001)
    for _, num := range nums {
        numsSet[num] = true
    }
    
    for numsSet[original] {
        original *= 2
    }
    
    return original
}
```

#### Language used for code

Go

#### Expected behavior

Should not have Runtime exception due to numbers greater than 1000

**Comment by LC-Sue** [comment]
Hi @itibs,
Thank you for reaching out to us, our judger is running correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
