### ISSUE TITLE
Missing Test Case - 511. Game Play Analysis I

### ISSUE THREAD

**Issue by Kunjal-sketch** [LeetCode-Feedback/LeetCode-Feedback#6886]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Kunjal-sketch** [comment]
Sql

**Comment by LC-Sue** [comment]
Hi @Kunjal-sketch 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
