### ISSUE TITLE
Missing Test Case - 680. Valid Palindrome II

### ISSUE THREAD

**Issue by Sumit068** [LeetCode-Feedback/LeetCode-Feedback#6887]
#### Your LeetCode username
Sumit_068

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A code was successfully accepted while the code wasn't right.

#### Code you used for Submit/Run operation

```
// Valid Palindrome II
public class Solution {
    public bool flag = false;
    public bool ValidPalindrome(string s) {
        if(s.Length<3){
            return true;
        }
        int n=s.Length-1;
        int count=0;
        for(int i=0,j=n; i<j; ){
            if(s[i]==s[j]){
                i++;
                j--;
            }
            else if((s[i+1]==s[j]) && s[i]==s[j-1]){
                if(s[i+2]==s[j-1] && s[i+3]==s[j-2]){
                    i=i+3;
                    j=j-2;
                    count++;
                }
                else{
                    j=j-3;
                    i=i+2;
                    count++;
                }
            }
            else if(s[i+1]==s[j]){
                i=i+2;
                j--;
                count++;
            }
            else if(s[i]==s[j-1]){
                j=j-2;
                i++;
                count++;
            }
            else{
                count=2;
                break;
            }
        }
        if(count<=1){
            return true;
        }
        return false;
    }
}
```

#### Language used for code
C#

#### Expected behavior

Missing Test Case -- "abcddededededdedededededcba"
Expected Answer -- True

this testcase actually is True but above code giving False answer but still this code accepted by leetcode.
So, please can you add a new test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/82926215/161399035-b8d63056-3054-41c7-8020-eb71d8eb69b7.png)
above screenshots you can see. code is accepted.

![image](https://user-images.githubusercontent.com/82926215/161399132-430f95ff-ac17-49f7-a154-eb11ae5a3663.png)
same code with test case run.

but actual answer is True.

**Comment by LC-Sue** [comment]
Hi @Sumit068 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Sumit068 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
