### ISSUE TITLE
1096. 花括号展开 II (leetcode-cn.com) 测试用例有误

### ISSUE THREAD

**Issue by renhongxu123** [LeetCode-Feedback/LeetCode-Feedback#689]
** Bug 类型**
- [1096 花括号展开 II ] 题目
- [ ] 题解
- [ Java] 编程语言

**描述**
1. 执行代码预期结果错误
2. 提交代码case判断错误

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public List<String> braceExpansionII(String expression) {
        List<String> ans = new ArrayList<String>();
        List<String> tmp = null;
        List<List<String>> joins = new ArrayList<List<String>>();
        Set<String> dict = new HashSet<String>();
        int[] stack = new int[expression.length()];
        int idx = -1;
        // 操作符，花括号 > 乘号 > 逗号
        String str = "";
        String joinStr = "";
        char c = '\0';
        for (int i = 0; i < expression.length(); i++) {
            c = expression.charAt(i);
            if (c == '{') {
                if (joinStr.length() > 0) {
                    tmp = new ArrayList<String>();
                    tmp.add(joinStr);
                    joins.add(tmp);
                    joinStr = "";
                }
                idx++;
                stack[idx] = i + 1;
            } else if (c == '}') {
                if (idx == 0) {
                    joins.add(braceExpansionII(expression.substring(stack[idx], i)));
                }
                idx--;
            } else if (c != ',' && idx == -1) {
                joinStr += c;
            }
            if (c == ',' || i == expression.length() - 1) {
                if (joinStr.length() > 0) {
                    tmp = new ArrayList<String>();
                    tmp.add(joinStr);
                    joins.add(tmp);
                    joinStr = "";
                }
                if (idx == -1 && !joins.isEmpty()) {
                    Set<String> set = new HashSet<String>();
                    List<String> l1 = new ArrayList<String>();
                    List<String> l2 = joins.get(0);
                    List<String> l = null;
                    for (int j = 1; j < joins.size(); j++) {
                        l = joins.get(j);
                        for (String ss: l2) {
                            for (String s: l) {
                                str = ss + s;
                                if (!set.contains(str)) {
                                    set.add(str);
                                    l1.add(str);
                                }
                            }
                        }
                        set.clear();
                        l2.clear();
                        l = l2;
                        l2 = l1;
                        l1 = l;
                    }
                    if (!l2.isEmpty()) {
                        for (String s: l2) {
                            if (!dict.contains(s)) {
                                dict.add(s);
                                ans.add(s);
                            }
                        }
                    }
                    joins.clear();
                }
            }
        }
        return ans;
    }
}
```

**期望行为**
1. **执行代码预期结果错误** ，输入："{a,b},{b,c}"，输出：["a","b","c"]，预期结果：["a,b","a,c","b,b","b,c"]
2. **提交代码case判断错误**，输入："{{a,z},a{b,c},{ab,z}}"，输出：["a","z","ab","ac"]，预期结果：["a","ab","ac","z"]

**屏幕截图**
<img width="266" alt="1" src="https://user-images.githubusercontent.com/7571838/88284620-4b0cd080-cd20-11ea-8a94-5af0bd1b4eae.png">
<img width="248" alt="2" src="https://user-images.githubusercontent.com/7571838/88284783-91fac600-cd20-11ea-838c-a56274ce1df3.png">

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。 刷题学习中遇到问题，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。

**Comment by renhongxu123** [comment]
> 你好，建议再仔细调试一下代码，希望这篇内容有帮助：[https://leetcode.kf5.com/hc/kb/article/1194344/。](https://leetcode.kf5.com/hc/kb/article/1194344/%E3%80%82) 刷题学习中遇到问题，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。

所以是case没错了？您方便详细说一下么？第一个case是题目里的自带的case，第二个顺序我检查了，应该是题目中描述的。

**Comment by renhongxu123** [comment]
> 你好，建议再仔细调试一下代码，希望这篇内容有帮助：[https://leetcode.kf5.com/hc/kb/article/1194344/。](https://leetcode.kf5.com/hc/kb/article/1194344/%E3%80%82) 刷题学习中遇到问题，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。

您确定看了我的描述了么？感觉问题没有被认真对待啊

**Comment by renhongxu123** [comment]
> 你好，建议再仔细调试一下代码，希望这篇内容有帮助：[https://leetcode.kf5.com/hc/kb/article/1194344/。](https://leetcode.kf5.com/hc/kb/article/1194344/%E3%80%82) 刷题学习中遇到问题，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。

您确定看了我的描述了么？感觉问题没有被认真对待啊。
输入："{a,b},{b,c}"，输出：["a","b","c"]
这个case是题目中介绍自带的，两个花括号中间有逗号，**"{a,b},{b,c}"**，
预期结果给的是**["a,b","a,c","b,b","b,c"]**
<img width="352" alt="1" src="https://user-images.githubusercontent.com/7571838/88390909-bec7df80-cdeb-11ea-98cd-9d9c9a9c8a6d.png">
<img width="299" alt="2" src="https://user-images.githubusercontent.com/7571838/88390915-c2f3fd00-cdeb-11ea-8146-6757a699c651.png">

**Comment by renhongxu123** [comment]
@feiceh

**Comment by feiceh** [comment]
感谢反馈，题目当前已经修复，错误是由于少了外面的 {} 引起的。
