### ISSUE TITLE
Missing Test Case - 2226. Maximum Candies Allocated to K Children

### ISSUE THREAD

**Issue by philip0014** [LeetCode-Feedback/LeetCode-Feedback#6890]
#### Your LeetCode username

pipi0014

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

LeetCode accepted my wrong solution of the following missing test case:
Input: `candies = [9999999], k = 1`
My code output: 10000000
Expected output: 9999999

#### Code you used for Submit/Run operation

```
class Solution {
    public int maximumCandies(int[] candies, long k) {
        long sum = 0;
        for (int v : candies) {
            sum += v;
        }
        if (sum < k) return 0;
        
        int l = 1, r = 10000000;
        while (l < r) {
            int m = ((r - l) / 2) + l;
            if (check(candies, k, m)) {
                l = m + 1;
            } else {
                r = m;
            }
        }
        if (l == 10000000) return l;
        return l - 1;
    }
    
    private boolean check(int[] candies, long k, int candy) {
        long res = 0;
        for (int i=0;i<candies.length;i++) {
            res += (candies[i] / candy);
        }
        return (res >= k);
    }
}
```

#### Language used for code

Java

#### Expected behavior

Since there is a single pile of candies and a single child, the child should be given a whole pile which is 9999999 candies.

#### Additional context

My accepted submission (should be wrong answer): https://leetcode.com/contest/weekly-contest-287/submissions/detail/672691766/

**Comment by LC-Sue** [comment]
Hi @philip0014 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @philip0014 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
