### ISSUE TITLE
bug in 877. Stone Game problems test case

### ISSUE THREAD

**Issue by jamilcse13** [LeetCode-Feedback/LeetCode-Feedback#6892]
#### Your LeetCode username
jamil117

#### Category of the bug
- Stone Game
- class Solution:
      def stoneGame(self, piles: List[int]) -> bool:
          return True
- python3
- each test case returns True. Here should give some test cases as the answer will be 'False'. ex: piles = [5,4,4,5]

#### Description of the bug
Each of the test case values of this question is return true. If anyone just returns 'True', it will be accepted.
I think this is not fair as it is a medium category problem.

Input: piles = [5,3,4,5]
Output: true

you should change the condition as it is given false. the point you can change:
Each of the test case values of this question is return true. If anyone just returns 'True', it will be accepted.
I think this is not fair as it is a medium category problem.

#### Code you used for Submit/Run operation
```
// Stone Game
class Solution:
    def stoneGame(self, piles: List[int]) -> bool:
        return True
```

#### Language used for code
python3

#### Expected behavior
Here should give some test cases as the answer will be 'False'. Ex: piles = [5,4,4,5]. But for this, you have to change the condition: Sum must be odd

**Comment by stormsunshine** [comment]
It can be proven that Alice can always win, as long as the testcases meet all conditions. Why do you want to return false as the proof already exists?

**Comment by jamilcse13** [comment]
if it will always return true then how should it be a good question?
any can solve this question just return true.

**Comment by stormsunshine** [comment]
There does NOT exist any testcase that should return false, since it can be proven that Alice can always win. If you can't provide a testcase that should return false, then you are wasting the others' time.
Although the answer is always true, you need to prove it. You must know why returning true is correct.

**Comment by LC-Sue** [comment]
Hi @jamilcse13,
Thank you for reaching out to us, I hope stormsunshine's response was able to answer your doubts! Please feel free to reach out if you have any other questions!

**Comment by jamilcse13** [comment]
Yes i got [stormsunshine](https://github.com/stormsunshine)'s point. But I wrote my note to change some conditions as it also accepts some False returns.
Because a problem that will always accept the True return value, is not an appropriate problem.
