### ISSUE TITLE
e.g. not in lexicographical order

### ISSUE THREAD

**Issue by aviralrg** [LeetCode-Feedback/LeetCode-Feedback#6896]
#### Your LeetCode username

aviralrg

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

the sample value used in explaining the question is not in lexicographical order
```
For example, for arr = [1,2,3], the following are considered permutations of arr: [1,2,3], [1,3,2], **[3,1,2],** [2,3,1].
```
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

For example, for arr = [1,2,3], the following are considered permutations of arr: [1,2,3], [1,3,2], **[2,1,3],** [2,3,1].

#### Screenshots

![image](https://user-images.githubusercontent.com/17119756/161413697-4f197b9e-2a59-403c-a6da-b890364caacb.png)

**Comment by LC-Sue** [comment]
Hi @aviralrg,
Thank you for reaching out to us, the example is simply listing some sample of permutations, does not necessarily need to be in order. Thank you for your time!
