### ISSUE TITLE
Missing Test Case - 350. Intersection of Two Arrays II

### ISSUE THREAD

**Issue by ekstrah** [LeetCode-Feedback/LeetCode-Feedback#6897]
#### Your LeetCode username

ekstrah

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

nums1 = [4,2,2,2,3,2,1,5]
nums2 = [2,2,2,2,2,2,1,5]

In this case the answer would be [2,1,5]
However, the code that i have used to submit passes with current test cases
But, not on my cases

#### Code you used for Submit/Run operation

```
def intersect(nums1: list[int], nums2: list[int]) -> list[int]:
    return list((Counter(nums1) & Counter(nums2)).elements())
```

#### Language used for code

Python3

#### Expected behavior

THe answer would be [2,1,5] not [2, 2, 2, 2, 1, 5]

**Comment by stormsunshine** [comment]
The answer should be [2,2,2,2,1,5]. Each element in the result must appear as many times as it shows in both arrays.
