### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by Mostafa-Davoodi** [LeetCode-Feedback/LeetCode-Feedback#6898]
#### Your LeetCode username
user1679Vh

#### Category of the bug
Introduction to array
Find pivot index
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

It seems we have a wrong test case for this question: [-1,-1,0,1,1,0]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Mostafa-Davoodi 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
