### ISSUE TITLE
#239 sliding-window-maximum bad test case

### ISSUE THREAD

**Issue by cowhorse** [LeetCode-Feedback/LeetCode-Feedback#69]
**What kind of the bug**
- [*] problem
- [ ] solution
- [ ] language

**Describe the bug**
Problem description has such note
Note:
You may assume k is always valid, 1 ≤ k ≤ input array's size for non-empty array.

However there is a test case nums=[] k=0 there

**what language is your code written in**
Java

**The code you submit/run**
```

**Expected behavior**
invalid test case

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by CooperCooperCooper** [comment]
Hi @cowhorse,
Thank you for reaching out to us! I've relayed this information to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @cowhorse,
Thanks to your timely feedback, we've updated the test cases and description for this problem. Please check it out :)
