### ISSUE TITLE
Missing testcase in problem 1410. HTML Entity Parser

### ISSUE THREAD

**Issue by rahul799** [LeetCode-Feedback/LeetCode-Feedback#690]
#### Your LeetCode username

@rahul799

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**1410. HTML Entity Parser** - A very important condition isn't checked because of no test cases.
My test case is -> **_"&am&amp; is an HTML entity but &ambassador; is not."_**
So basically we need to take care that we have **&am&amp** this kind of string or not.
#### Code you used for Submit/Run operation

```
class Solution {
public:
    string entityParser(string text)
    {
        unordered_map<string,string> m;
        m["&quot;"]="\"";
        m["&apos;"]="'";
        m["&amp;"]="&";
        m["&gt;"]=">";
        m["&lt;"]="<";
        m["&frasl;"]="/";
        string ans;
        for(int i=0;i<text.size();i++)
        {
            if(text[i]=='&')
            {
                string s;
                while(i<text.size())
                {
                    s+=text[i];
                    
                    if((text[i]==';')&&m.find(s)!=m.end())
                    {
                        ans+=m[s];
                        s="";
                        break;
                    }
                    else i++;
                    if(text[i]=='&') // This condition isn't checked right now & neglected
                    {
                        i--;
                        break;
                    }
                }
                ans+=s;
            }
            else
            {
                ans+=text[i];
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

**Comment by lc-ivan** [comment]
Hi @rahul799 , 
Thanks for reaching out to us! I have run your code and test case and it seems to pass and submit correctly. Could you please elaborate on what the missing test case or issue you are experiencing with this problem is?
