### ISSUE TITLE
Bug with different Answers - 501. Find Mode in Binary Search Tree

### ISSUE THREAD

**Issue by Ayanrocks** [LeetCode-Feedback/LeetCode-Feedback#6900]
#### Your LeetCode username

Ayanrocks

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Different output while submitting and while running code with example test case

#### Code you used for Submit/Run operation

```go
/**
 * Definition for a binary tree node.
 * type TreeNode struct {
 *     Val int
 *     Left *TreeNode
 *     Right *TreeNode
 * }
 */

var m = make(map[int]int, 0)
func findMode(root *TreeNode) []int {
    traverse(root)
    max := 0
    ans := []int{}
    
    for k,v := range m {
        if v == max {
            ans = append(ans, k)
        } else if v > max {
            ans = []int{k}
            max = v
        }
    }
    
    return ans
}

func traverse(root *TreeNode) {
    if root == nil {
        return
    }
    
    m[root.Val]++
    traverse(root.Left)
    traverse(root.Right)
}
```

#### Language used for code

Golang

#### Expected behavior

Should come as [0]

#### Screenshots

<img width="1431" alt="Screenshot 2022-04-03 at 2 44 03 PM" src="https://user-images.githubusercontent.com/11027998/161420568-f2afbc8e-559b-4253-b0a1-4c64c85e17d0.png">

**Comment by LC-Sue** [comment]
Hi @Ayanrocks 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
