### ISSUE TITLE
typo in "Binary Search"'s "How does it work"

### ISSUE THREAD

**Issue by SeasonLeee** [LeetCode-Feedback/LeetCode-Feedback#6901]
Since this is a word plural typo and it's so easy to miss, I made a sort of dramatic point-out of it...

![image](https://user-images.githubusercontent.com/13610283/161427943-9f2c7e96-5d69-4b73-81c7-6560bc3c3824.png)

Please fix it? Unless this "indicies" is some new word I never heard of, then tell me what it means. Thanks.

**Comment by LC-Sue** [comment]
Hi @SeasonLeee 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @SeasonLeee 
Thank you for your time. Indices is another word for the plural of index (indexes). Both words mean the same thing, the difference being that "indexes" could be a noun or a verb while "indices" is always a noun. We appreciate your support!

**Comment by SeasonLeee** [comment]
yeah, right.... I know Indices is the plural form of the word "index"

But if you look closer at the screenshot, you will know that this document said "**indicies**" with a "i" in front of "es" 

Thank you.

**Comment by SeasonLeee** [comment]
I can't believe no one can't tell this mistake
![image](https://user-images.githubusercontent.com/13610283/167108490-329fdfcb-7504-428f-9199-aae175145319.png)


# you used indicies instead of indices............

😩😩😩😩😩😩😩😩😩😩😩😩😩😩
