### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by rewle** [LeetCode-Feedback/LeetCode-Feedback#6902]
Next for 3,1,2 is 3,2,1, but in example 2,3,1

#### Your LeetCode username
rewle

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @rewle 
Please provide more details on your report. After more information is provided, I will reopen this ticket. Thank you for your time.

**Comment by rewle** [comment]
In problem https://leetcode.com/problems/next-permutation/
In description says:
> For example, for arr = [1,2,3], the following are considered permutations of arr: [1,2,3], [1,3,2], [3,1,2], [2,3,1].

[1,2,3], [1,3,2], **[3,1,2]**, [2,3,1] - this sequence is wrong
I think right sequence is [1,2,3], [1,3,2], **[2,1,3]**, [2,3,1]
