### ISSUE TITLE
Missing Test Case - 12. Integer to Roman

### ISSUE THREAD

**Issue by ShamaUgale** [LeetCode-Feedback/LeetCode-Feedback#6904]
#### Your LeetCode username

sugale85

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

missing test case
input of 0100 should return C

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
0100 is not a valid value of type integer. Why do you want to add a leading zero?

**Comment by LC-Sue** [comment]
Hi @ShamaUgale 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
