### ISSUE TITLE
Replace NULL with nullptr in C++ to catch up with 2022 e.g. at https://leetcode.com/explore/learn/card/linked-list/210/doubly-linked-list/1297/

### ISSUE THREAD

**Issue by adamenkov** [LeetCode-Feedback/LeetCode-Feedback#6905]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @adamenkov 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
