### ISSUE TITLE
python code not available in free text based course

### ISSUE THREAD

**Issue by Mukulcoder08** [LeetCode-Feedback/LeetCode-Feedback#6907]
Python code not available in free text based course tutorial. And i have knowledge of python only and also i am switching my area so please make available if possible.
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Mukulcoder08** [comment]
python code not available in free text based course

**Comment by LC-Sue** [comment]
Hi @Mukulcoder08,
Thank you for reaching out to us, python solutions are available to our premium members. Please feel free to subscribe at https://leetcode.com/subscribe/
