### ISSUE TITLE
Wrong slide contents, 11. Container With Most Water

### ISSUE THREAD

**Issue by JinchunChoi** [LeetCode-Feedback/LeetCode-Feedback#6911]
#### Your LeetCode username

jcchoi

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I found the wrong contents in the second solution slides from 5 to 8.
Based on the code, when height[l] == height[r] (in slide 4),  you should move the right pointer (not moving the left one as in a current way).
So on slide 5, height[l] is 8, and height[r] is 4.
The following slides are also should be modified in the same way.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @JinchunChoi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @JinchunChoi 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
