### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by andreiasi** [LeetCode-Feedback/LeetCode-Feedback#6912]
#### Your LeetCode username

andreiasi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Wrong test case

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
Which test case is wrong?

**Comment by LC-Sue** [comment]
Hi @andreiasi 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
