### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by younghoonyou** [LeetCode-Feedback/LeetCode-Feedback#6915]
#### Your LeetCode username
kcnoh2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I solved using Divide and Conquer , But, when the mid = (start + end)/2 is Peak Element ex) [1,2,1,3,2,6,4] the expected and output is not same but test case has passed

#### Code you used for Submit/Run operation

```
//Find Peak Element
class Solution {//O(log(N)) binary search
public:
    int findPeakElement(vector<int>& nums) {
        int size = nums.size();
        if(size == 1) return 0;
        if(size == 2) return (nums[0]>nums[1]?0:1);
        int start = 0, end = size - 1;
        while(start<end){
            int mid = (start + end)/2;
            if(nums[mid + 1] > nums[mid]) start = mid + 1;
            else end = mid;
        }
        return end;
    }
};
```

#### Language used for code
C++

#### Expected behavior

It would be wrong but Accepted

#### Screenshots

<img src="https://user-images.githubusercontent.com/69233428/161690561-e727cb3a-50ad-45ca-9292-331007ba8b07.png">

**Comment by stormsunshine** [comment]
The answer is not always unique and it is possible that a testcase has several correct answers. Any of the correct answers can be accepted.

**Comment by LC-Sue** [comment]
Hi @younghoonyou,
Thank you for reaching out to us, I hope stormsunshines' response was able to answer your doubts. Please feel free to reach out if you have any other questions!

**Comment by younghoonyou** [comment]
Oh thanks to reply i didn't know that
