### ISSUE TITLE
Incorrect Time Complexity Analysis - 716. Max Stack

### ISSUE THREAD

**Issue by w22116972** [LeetCode-Feedback/LeetCode-Feedback#6916]
Time complexity for approach 2 is wrong.
Line 20 costs O(n), since it uses ArrayList to delete last element.

Here is description on ArrayList.

```java
/**
* Removes the element at the specified position in this list.
* Shifts any subsequent elements to the left (subtracts one from their
* indices).
```

And underlying is array copy

```java
/**
 * Private remove method that skips bounds checking and does not
 * return the value removed.
 */
private void fastRemove(Object[] es, int i) {
    modCount++;
    final int newSize;
    if ((newSize = size - 1) > i)
        System.arraycopy(es, i + 1, es, i, newSize - i);
    es[size = newSize] = null;
}
```

So it will definitely cost O(n).

Since this article can't give correct approaches, I think this should be removed.

**Comment by LC-Sue** [comment]
Hi @w22116972 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team，but it will take time to fix it. We appreciate your support!
