### ISSUE TITLE
测试用例输出BUG

### ISSUE THREAD

**Issue by lihao-ops** [LeetCode-Feedback/LeetCode-Feedback#6917]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
Accomplish
**Bug 类型**
- [ ] 题目[剑指 Offer 59 - I. 滑动窗口的最大值](https://leetcode-cn.com/problems/hua-dong-chuang-kou-de-zui-da-zhi-lcof/)
- [ ] 题解
- [ ] 编程语言 Java
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
本地IDEA测试通过，并不出现测试用例中出现的错误
**你使用的语言**
Java

**你提交或者运行的代码**
```
/**
双指针：
    1.定义List<Integer> list = new ArrayList()不断添加到结果集
    2.定义q,h双指针[q,h)滑动窗口
    3.当h == nums.length则跳出循环
    4.定义变量sum用于不断迭代出最大值,并保存结果集
优化：
    实际上滑动窗口的活动范围nums.length - k + 1,定义此为结果数组的初始大小
再优化：
    在优化的时候，无需每次都将窗口内的值都遍历统计一遍
    1.判断上一次保存的最大值下标是不是在窗口的左边界位置
        1.1 是：则遍历当前窗口内的所有元素取最大值
        1.2 不是:则将上次的最大值与这一次的最右边新加入的值进行比对
            如果右边界新加入的值 <= sum,那就无需换下标
            如果右边界新加入的值 > sum,则替换值并更新下标
 */
class Solution {
    public int[] maxSlidingWindow(int[] nums, int k) {
        //前置判断
        if(nums.length == 0) return new int[0];
        //优化：确定结果数组的初始长度
        //定义结果数组的初始为nums.length - k + 1为滑动窗口的活动范围
        int[] list = new int[nums.length - k + 1];

        //双指针
        //c用于保存上一次窗口中最大值的下标
        int c = -1;
        for(int q = 0,h = k,s = 0; h != nums.length + 1; q++,h++,s++){
            //统计窗口中的元素和
            //注意：在这里sum的初始值必须为滑动窗口的左起始值
            int sum = nums[q];
            // if(q > 0 && c != -1 && c != q - 1 && h < nums.length) sum = nums[c];
            
            //如果上一次的最大值 != 上一次的左边界值,就让他和这一次的右边界值对比出大小即可
            if(c != q - 1 && h < nums.length && k != 1){
                if(nums[h - 1] > list[s - 1]){
                    list[s] = nums[h - 1];
                    c = h - 1;
                    continue;
                }
                else{
                    list[s] = list[s - 1];
                    continue;
                }
            }

            for(int i = q;i < h && h!= nums.length + 1;i++){
                // sum = Math.max(sum,nums[i]);
                if(sum < nums[i]){
                    sum = nums[i];
                    c = i;
                }
            }
            list[s] = sum;
        }
        return list;
    }
}
```

**期望行为**
描述你期望的结果
通过测试用例
**屏幕截图**
![image](https://user-images.githubusercontent.com/79788290/161736096-43cdf0f4-bde4-4370-ad5f-f66ea23e1d3f.png)
![image](https://user-images.githubusercontent.com/79788290/161736115-b9153ded-bd45-4d0a-9ce1-fc7deb5363d0.png)
![image](https://user-images.githubusercontent.com/79788290/161736135-e9aa8cb9-c038-4538-beec-0708ce99c327.png)

添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，建议再仔细调试一下代码，本地和力扣站结果不一样可能是运行环境不同。后续刷题学习中遇到问题，可点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by lihao-ops** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
