### ISSUE TITLE
191. Number of 1 Bits - Giving wrong answer instead of giving error for decimal number inputs 

### ISSUE THREAD

**Issue by rahulsangwn** [LeetCode-Feedback/LeetCode-Feedback#692]
#### Your LeetCode username
rahulsangwn

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Taking decimal input also (apart from 32 bit binary)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int hammingWeight(uint32_t n) {
        int count = 0;
        while(n) {
            if (n%2 == 1) {
                count++;
            }
            
            n /= 2;
        }   
        return count;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
Should give error

#### Screenshots
<img width="919" alt="leetcode" src="https://user-images.githubusercontent.com/14253888/88354650-3c093b00-cd7f-11ea-9d56-92545646f9c6.png">

**Comment by lc-ivan** [comment]
Hi @rahulsangwn,
Thank you for reaching out and for the feedback! The scope of this problem is focused on unsigned integers but we will take this suggestion of decimal into account for future variations of this problem.
