### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by irlcatgirl** [LeetCode-Feedback/LeetCode-Feedback#6920]
#### Your LeetCode username
https://leetcode.com/irlcatgirl/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I saw a solution in submissions that involves deleting the list to solve the issue. This solution avoids the fast-slow pointer approach at the cost of deleting the list. This likely would not be accepted at an interview or at least result in being asked about not deleting the list.

A test case where a node in the list (without a cycle) is Null  and points to a non-null node would block this specific approach. (Of course you would then need test cases that involve an RNG or that cover every single number to prevent some other arbitrary fake number from being used). Perhaps test generation or a giant list without a cycle which has every possible integer value)

Constraints does say `-105 <= Node.val <= 105` so it might not technically be a bug as it does not say a Node's value can be null.

#### Code you used for Submit/Run operation

```
# Solution belongs to https://leetcode.com/problems/linked-list-cycle/discuss/1830651/python-simple-on-with-comments not me

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, x):
#         self.val = x
#         self.next = None

class Solution:
    def hasCycle(self, head: Optional[ListNode]) -> bool:
        hsh = {} # hsh is not required. thanks for pointing it in comments
        
        while head:
            #empty the value of every node
            if head.val:
                head.val = None
            else:
                #if we come across empty node during traversal, it is a cycle
                return True
            head = head.next
        #if we reach the end, we can return False as no cycle formed
        return False
```

#### Language used for code
Python

#### Expected behavior
The solution should be rejected.

#### Screenshots
N/A

**Comment by LC-Sue** [comment]
Hi @irlcatgirl,
Thank you for reaching out to us, though the answer uses deleting, we cannot avoid such workarounds. The user should be aware using such approach would not be accepted during an interview. Thank you for reporting!
