### ISSUE TITLE
实际运行的结果和在控制台调试的运行结果不一致

### ISSUE THREAD

**Issue by dhywy** [LeetCode-Feedback/LeetCode-Feedback#6921]
**你的 LeetCode 用户名**

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例
- [x] 其他 

**描述**
代码提交后实际运行的结果和在控制台调试的运行结果不一致

**你使用的语言**
golang

**你提交或者运行的代码**
```
[403. 青蛙过河](https://leetcode-cn.com/problems/frog-jump/)
const N = 2010
var f [N][N]bool

func max(a, b int) int {
    if a >= b {
        return a
    }
    return b
}

func canCross(stones []int) bool {
    n := len(stones)
    hash := make(map[int]int)
    for i := 0; i < n; i++ {
        hash[stones[i]] = i
    }
    f[0][1] = true
    for i := 1; i < n; i++ {
        for j := 1; j <= i+1; j++ {
            for k := max(j-1, 1); k <= j+1; k++ {
                if idx, exists := hash[stones[i]-k]; exists {
                    if f[idx][k] {
                        f[i][j] = true
                        break
                    }
                }
            }
        }
    }
    for i := 0; i <= n; i++ {
        if f[n-1][i] {
            return true
        }
    }
    return false
}
```

**期望行为**
[0,1,2,3,4,8,9,11]这一个测试用例在实际运行和控制台运行的结果一直

**屏幕截图**
![image](https://user-images.githubusercontent.com/57249078/161894688-b67ca302-ffba-4089-9efe-b34ab8c0c866.png)
![image](https://user-images.githubusercontent.com/57249078/161894689-30abe5fa-f0dc-41c5-8f36-94a72bfd16ce.png)

**额外的上下文**

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
