### ISSUE TITLE
Missing Test Case - 1143. Longest Common Subsequence

### ISSUE THREAD

**Issue by 96ZY** [LeetCode-Feedback/LeetCode-Feedback#6923]
#### Your LeetCode username

HZY_96 or 电子科大鸡公煲 for leetcode-cn.com

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

for input 
```
"a"
"a"
```
my code outputs `0`, which is obviously wrong. However, my code got accepted!
#### Code you used for Submit/Run operation

```
class Solution {
    public int longestCommonSubsequence(String text1, String text2) {
    	if (text1 == null || text2 == null || text1.length() == 0 || text2.length() == 0) {
    		return 0;
    	}

    	int m = text1.length();
    	int n = text2.length();
    	int[][] dp = new int[m][n];
        // dp[i][j] is the longest common subsequence for text1[0......i] and text2[0......j]
    	dp[0][0] = text1.charAt(0) == text2.charAt(0) ? 1 : 0;
        // here is the bug, ans it should be int max = dp[0][0];
    	int max = 0;

    	for (int i = 1; i < m; i++) {
    		dp[i][0] = dp[i - 1][0] == 1 ? 1 : text1.charAt(i) == text2.charAt(0) ? 1 : 0;
    		max = Math.max(max, dp[i][0]);
    	}
    	for (int i = 1; i < n; i++) {
    		dp[0][i] = dp[0][i - 1] == 1 ? 1 : text2.charAt(i) == text1.charAt(0) ? 1 : 0;
    		max = Math.max(max, dp[0][i]);
    	}

    	for (int i = 1; i < m; i++) {
    		for (int j = 1; j < n; j++) {
    			if (text1.charAt(i) == text2.charAt(j)) {
    				dp[i][j] = 1 + dp[i - 1][j - 1];
    			} else {
    				dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
    			}

    			max = Math.max(max, dp[i][j]);
    		}
    	}   	


    	return max;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Already described in the bug section.

#### Screenshots

<img width="1680" alt="Screen Shot 2022-04-06 at 22 11 43" src="https://user-images.githubusercontent.com/31836703/161994725-5af6ce18-844b-46df-82fd-6b0054354c3b.png">

**Comment by LC-Sue** [comment]
Hi @96ZY 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
