### ISSUE TITLE
870.优势洗牌测试数据与题目要求的数据大小不一致

### ISSUE THREAD

**Issue by x-xk** [LeetCode-Feedback/LeetCode-Feedback#6924]
**你的 LeetCode 用户名**
别哇了行吗

**Bug 类型**
- [ +] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目描述与实际测试数据不一致

**你使用的语言**
Java

**期望行为**
题目中说数组最大长度为10^4
测试数据数组最大长度为10^5

**屏幕截图**
![image](https://user-images.githubusercontent.com/76646296/162003203-b83cd502-441d-405f-98f5-0adef2939474.png)

**额外的上下文**
![image](https://user-images.githubusercontent.com/76646296/162004108-4c1c418f-98e3-44de-a151-0651ee6258e9.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by x-xk** [comment]
> 你好，更新后，请在下方留言关注一下力扣中文网站的个性域名（Ps：若不域名已查看自己的个性域名，可以通过浏览网址： https: [//support.leetcode.com/ hc/kb/1277837](https://support.leetcode-cn.com/hc/kb/article/1277837)），我们给予奖励哦。


leetcode-cn.com/u/6RJZKPqbph/

**Comment by feiceh** [comment]
你好，ID：6RJZKPqbph 给予积分奖励，请查收
