### ISSUE TITLE
Runtime Error - 923. 3Sum With Multiplicity

### ISSUE THREAD

**Issue by liberix** [LeetCode-Feedback/LeetCode-Feedback#6927]
#### Your LeetCode username

liberix

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The online running result is different from the local one. When input is `[1,1,2,2,3,3,4,4,5,5]\n8`, I get the correct answer `20` in local environment, but I get the wrong answer `4` from online result. It seems that I did not use any global or static variable.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int threeSumMulti(vector<int>& arr, int target) {
        map<int, int> m;
        int res = 0;
        for (auto i: arr)   m[i] += 1;
        for (auto p: m) {
            int count = 1;
            for (auto p2: m) {
                map<int, int> cm;
                cm[p.first] += 1;
                if (p2.first >= p.first && m[p2.first] > 0) {
                    int p3 = target - p.first - p2.first;
                    if (m.count(p3) > 0 && p3>= p2.first) {
                        cm[p2.first] += 1;
                        cm[p3] += 1;
                        for (auto p : cm) {
                            count *= selectNFromM(m[p.first], p.second) % 1000000007;
                        }
                        res += count;
                        count = 1;
                    }
                }
            }
        }
        return res;
    }
    int selectNFromM(int m, int n) {
        if (n > m) return 0;
        if (n == m) return 1;
        if (n == 1) return n;
        if (n == 2) return (m * (m-1)) / 2;
        if (n == 3) return (m * (m-1) * (m-2)) / 6;
        return 0;
    }
};
```

#### Expected behavior

Online system computes the same and correct results.

**Comment by LC-Sue** [comment]
Hi @liberix 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by liberix** [comment]
Hi, thanks for reply. I have read the support article before posting the issue. I believe that there is no global or static variable in my code. Could you please tell me where I can find help? Thanks
