### ISSUE TITLE
Missing Test Case - 923. 3Sum With Multiplicity

### ISSUE THREAD

**Issue by Aniket-1211** [LeetCode-Feedback/LeetCode-Feedback#6928]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @Aniket-1211 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
