### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by ps92** [LeetCode-Feedback/LeetCode-Feedback#6931]
#### Your LeetCode username
ps92

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Problem: https://leetcode.com/problems/distribute-coins-in-binary-tree/
Test cases: 
[3,0,0]
[0,3,0,0,4,0,0]
[0,7,0,0,0,0,0]
[7,0,0,0,0,0,0]

#### Code you used for Submit/Run operation
```
class Solution {
    int ans;
    public int distributeCoins(TreeNode root) {
        ans = 0;
        dfs(root);
        return ans;
    }

    public int dfs(TreeNode node) {
        if (node == null) return 0;
        int L = dfs(node.left);
        int R = dfs(node.right);
        ans += Math.abs(L) + Math.abs(R);
        return node.val + L + R - 1;
    }
}
```

**Comment by LC-Yani** [comment]
Hi ps92,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best,

LC_Yani
