### ISSUE TITLE
Word typo in Explore - Graph Section

### ISSUE THREAD

**Issue by temvvlena** [LeetCode-Feedback/LeetCode-Feedback#6932]
#### Your LeetCode username
temvvlena

#### Category of the bug
- [ ] Language

#### Description of the bug
Word typo in Explore - Graph Section. Added screenshot below. The word "abovementioned" should be replaced above mentioned

#### Screenshots
<img width="1161" alt="Screen Shot 2022-04-06 at 10 49 19 PM" src="https://user-images.githubusercontent.com/44326790/162116642-7910d4d8-6ba5-4094-ad2d-a3a43537c48b.png">

**Comment by LC-Sue** [comment]
Hi @temvvlena 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @temvvlena 
Thank you for your time.  The current spelling is more common in the US while the user's recommendation is more common in the UK. All in all, it makes little difference in this scenario.

https://english.stackexchange.com/questions/239396/the-grammar-behind-above-mentioned

We appreciate your support!
