### ISSUE TITLE
Missing example 4 - 1488. Avoid Flood in The City

### ISSUE THREAD

**Issue by Frederick-S** [LeetCode-Feedback/LeetCode-Feedback#6934]
#### Your LeetCode username

Frederick

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The following description mentions that there should be an example 4 in the question, but there is not:

> Notice that if you chose to dry a full lake, it becomes empty, but if you chose to dry an empty lake, nothing changes. (see example 4)

#### Expected behavior

There should be an example 4 in the question description.

**Comment by LC-Yani** [comment]
Hi there,

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
