### ISSUE TITLE
Missing Test Case - 140. Word Break II

### ISSUE THREAD

**Issue by raja-19** [LeetCode-Feedback/LeetCode-Feedback#6935]
#### Your LeetCode username

paxaq

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Accepted code TLEs on custom testcase

#### Code you used for Submit/Run operation

```
class Solution {
public:
    map<int, vector<int>> occurences;
    vector<string> words;
    int n;
    string s;
    vector<string> wordBreak(string s, vector<string>& wordDict) {
        n = (int)s.size();
        this->s = s;
        words = wordDict;
        sort(words.begin(), words.end());
        for (int i = 0; i < n; i++) {
            for (int j = i; j < n; j++) {
                string w = s.substr(i, j - i + 1);
                if (binary_search(words.begin(), words.end(), w)) {
                    occurences[i].push_back(j);
                }
            }
        }
        return wordBreak(0);
    }
    
    vector<string> wordBreak(int i) {
        if (i == n) return {""};
        string suf = s.substr(i);
        vector<string> res;
        for (int j: occurences[i]) {
            string cur = s.substr(i, j - i + 1);
            if (i > 0) cur = " " + cur;
            vector<string> sufbreak = wordBreak(j + 1);
            for (string x: sufbreak) {
                res.push_back(cur + x);
            }
        }
        return res;
    }
};
```
#### Language used for code

C++

#### Expected behavior

Code TLEs on the main tests

#### Additional context

The testcase:
```
"aaaaaaaaaaaaaaaaaaaa"
["a", "aa", "aaa", "aaaa", "aaaaa", "aaaaaa", "aaaaaaa", "aaaaaaaa", "aaaaaaaaa", "aaaaaaaaaa"]
```

**Comment by LC-Yani** [comment]
Hi paxaq,

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Hi Raja-19

Thank you for reaching out to us. We tested your code and experienced Time Limit Exceeded as well. 

When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once , whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Run code" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best,

LC-Yani

**Comment by raja-19** [comment]
Hi! I think you misunderstood me. I am not saying that this solution shouldn't TLE on "Run Code". I am saying it shouldn't get accepted on "Submit".

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the output for this test case is too long that we cannot add this test case, 
Thank you for your time and we appreciate your support!
