### ISSUE TITLE
Missing Test Case - 406. Queue Reconstruction by Height

### ISSUE THREAD

**Issue by niranjan09** [LeetCode-Feedback/LeetCode-Feedback#6939]
#### Your LeetCode username
niranjan09

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This question can have topic-tag of Segment-Tree as the question is solvable using segment-tree data structure.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
What is the missing test?

**Comment by niranjan09** [comment]
I just wanted to add a tag to the problem.
