### ISSUE TITLE
Missing Test Case in 1521. Find a Value of a Mysterious Function Closest to Target

### ISSUE THREAD

**Issue by NekrozQliphort** [LeetCode-Feedback/LeetCode-Feedback#694]
#### Your LeetCode username
NekrozQliphort

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The solutions below passed because important test cases was missing.
If arr=[16,30,38] and target=6, the solutions below return 6 , instead of 0.
However, the solutions below passed all test cases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int closestToTarget(vector<int>& arr, int target) {
        int res = INT_MAX, currSum = 1048575;
        for (auto &num : arr) {
            res = min(abs(num - target), min(abs((currSum &= num) - target), res));
            if (num <= target) currSum = 1048575;
        }
        return res;
    }
};
```
```
class Solution:
    def closestToTarget(self, arr: List[int], target: int) -> int:
        prev = arr[0] # prev = dp[i-1]
        ans = abs(prev-target)
        for x in arr[1:]:
            pnum = prev & x    # prev = dp[i-1]
            if abs(target-x) < abs(target-pnum): 
                prev = x    # dp[i] = a[i]
            else:
                prev = pnum       #dp[i] = arr[i] & dp[i-1]
            ans = min(ans, abs(target - prev))
        return ans
```

#### Language used for code
C++, Python 3

#### Expected behavior
Expected to not pass all test cases.

#### Screenshots

![image](https://user-images.githubusercontent.com/53999796/88361818-e6e41e00-cdac-11ea-8e5f-40b44294708d.png)
![image](https://user-images.githubusercontent.com/53999796/88361832-f9f6ee00-cdac-11ea-8f05-f5645f268e70.png)

**Comment by lc-pam** [comment]
Hi @NekrozQliphort 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @
Thank you for your time. The problem has been updated thanks to another user's report so both your solution should get wrong answer when submit. We appreciate your support!
