### ISSUE TITLE
Question - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by cwillett** [LeetCode-Feedback/LeetCode-Feedback#6940]
#### Your LeetCode username
cwillett77

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
This is a question about the provided Brute Force solution. The description says that a `set` can be used, but the solution code is not using a `set` in Python or Java (to my knowledge, but I don't know Java or C++ as well). I looked at examples of creating a `set` in Java and in both languages, the coded solutions are using arrays or a direct lookup table (which is what the narrator in the video says). I think this is confusing and the right terminology should be used in the copy (text). 

So my question is, am I wrong about that? Should an array in Python ever by referred to as a set?
My understanding is that a `set` is an unordered collection that cannot have duplicates and is created by setting a variable equal to either `{1,2,3}` or `set([1,2,3])` in Python (just sample values).

Also you suggest that you could use the name `allUnique` for the method name, but all the coded solutions use the name `lengthOfLongestSubstring`. I think for anyone trying to get get better at solving problems it's important that the solution is super clear and uses consistent names, especially for beginners or they will be thrown for a loop and spend extra cycles trying to ascertain what is being referenced. I've seen a lot of these issues throughout the solutions and I'm too busy to report them all, but I will when I can. There is also a lot of bad grammar and malformed sentences that don't make sense. I think the product is great and I'm learning a lot which is why I want to help improve it. I'm also a paying customer, so I frankly I expect the copy to be better than this, especially compared to your competitors. 

#### Language used for code
Python (or Java)

#### Expected behavior
I think the terms list, array or direct access table would be more accurate (any one of them)

#### Screenshots
<img width="816" alt="Longest Substring Without Repeating Characters - LeetCode 2022-04-07 20-47-22" src="https://user-images.githubusercontent.com/41071/162359248-2bc05a6d-56ff-4415-9468-be46fb4a1dfb.png">

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
