### ISSUE TITLE
Missing Test Case - 631. Design Excel Sum Formula

### ISSUE THREAD

**Issue by sapphire921** [LeetCode-Feedback/LeetCode-Feedback#6941]
#### Your LeetCode username
sapphire921

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
A test case like:

["Excel","set","sum","set","get"]
[[3,"D"],[1,"A",2],[3,"D",["A1","A1:B2"]],[2,"B",2],[3,"D"]]

should be added to this question.
The below code should fail on that test case, but when I submit it, it passes all the existing tests cases.

#### Code you used for Submit/Run operation

```
class Excel(object):

    def __init__(self, H, W):
        self.M = [[{'v': 0, 'sum': None} for i in range(H)] for j in range(ord(W) - 64)]

    def set(self, r, c, v):
        self.M[r - 1][ord(c) - 65] = {'v': v, 'sum': None}

    def get(self, r, c):
        cell = self.M[r - 1][ord(c) - 65]
        if not cell['sum']: return cell['v']
        return sum(self.get(*pos) * cell['sum'][pos] for pos in cell['sum'])

    def sum(self, r, c, strs):
        self.M[r - 1][ord(c) - 65]['sum'] = self.parse(strs)
        return self.get(r, c)

    def parse(self, strs):
        c = collections.Counter()
        for s in strs:
            s, e = s.split(':')[0], s.split(':')[1] if ':' in s else s
            for i in range(int(s[1:]), int(e[1:]) + 1):
                for j in range(ord(s[0]) - 64, ord(e[0]) - 64 + 1):
                    c[(i, chr(j + 64))] += 1
        return c
```

#### Language used for code
Python3

#### Expected behavior
The above code should fail.

**Comment by LC-Sue** [comment]
Hi @sapphire921 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
