### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by AdaY45** [LeetCode-Feedback/LeetCode-Feedback#6946]
Found bug in tests for problem 29. Divide Two Integers
When you -2147483648/-1 you say it's 2147483647 but it's 2147483648

Input
-2147483648
-1
Output
2147483648
Expected
2147483647

**Comment by LC-Sue** [comment]
Hi @AdaY45,
Thank you for reaching out to us, please provide the code you used for submission.

**Comment by stormsunshine** [comment]
The result must be in the range [-2<sup>31</sup>, 2<sup>31</sup> - 1], so you can't return 2147483648 since it is out of range. You have to return 2147483647.

**Comment by AdaY45** [comment]
Thank you, now I understand. I didn’t pay attention to this condition.

сб, 9 квіт. 2022 р. о 02:55 stormsunshine ***@***.***> пише:
