### ISSUE TITLE
Missing Test Case - 703. Kth Largest Element in a Stream

### ISSUE THREAD

**Issue by Afzalghani** [LeetCode-Feedback/LeetCode-Feedback#6947]
input: 
["KthLargest","add","add","add","add","add"]
[[1,[]],[-3],[-2],[-4],[0],[4]]

The same input is working fine when I run it as the custom input.
But when I submit the code it gives an error.

class KthLargest {
    public static PriorityQueue<Integer> pq=new PriorityQueue<>();
    public static int size;

    public KthLargest(int k, int[] nums) {
    
        for(int a: nums)
        {
            pq.add(a);
            
        }
            this.size=k;
    }
    
    public int add(int val) {
       pq.add(val);
        while(pq.size()>size)
            pq.remove();
        return pq.peek();
        
    }
}

**Comment by LC-Sue** [comment]
Hi @Afzalghani 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
