### ISSUE TITLE
627. Swap Salary - missing test case

### ISSUE THREAD

**Issue by mdsexton** [LeetCode-Feedback/LeetCode-Feedback#6949]
receive error:
invalid test case 'salary'
no matter how code is written
it appears the table doesn't exist

**Comment by LC-Yani** [comment]
Hi Mdsexton,

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
