### ISSUE TITLE
287. Unclear Question Description

### ISSUE THREAD

**Issue by shans96** [LeetCode-Feedback/LeetCode-Feedback#695]
#### Your LeetCode username
shans

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The problem description is  "`Given an array nums containing n + 1 integers where each integer is between 1 and n (inclusive), prove that at least one duplicate number must exist. Assume that there is only one duplicate number, find the duplicate one.`" The [definition](https://www.wolframalpha.com/input/?i=inclusive) of inclusive is that the stated limits are included, which means given a range 1 to 4, 1 should be included, but the test cases do not follow this rule.

#### Code you used for Submit/Run operation

```
class Solution {
    public int findDuplicate(int[] nums) {
        int arrSum = Arrays.stream(nums).sum();
        int arrMax = arrMax(nums);
        int numDuplicates = nums.length - arrMax;
        for (int i = 1; i < arrMax + 1; i++) {
            int sum = 0;
            sum = sumOfInts(arrMax);
            sum += i * numDuplicates;
            if (sum == arrSum) return i;
        }
        return -1;
    }
    
    public int arrMax (int[] A) {
        int max = 0;
        for (int i : A) {
            if (i > max) max = i;
        }
        return max;
    }
    
    public int sumOfInts(int i) {
        return (i * (i + 1)) / 2;
    }
}
```

#### Language used for code
Java

#### Expected behavior
I have written a solution that meets the criteria given in the question, and uses inclusive ranges, but does not pass the test cases because some do not have an inclusive range. For example, `[2,2,2,2,2]` fails with this solution because it is not inclusive.

I suggest using interval notation to clear up any confusion, e.g. rephrase the question to state "`where each integer is within the interval (1, n]`".

**Comment by lc-ivan** [comment]
Hi @shans96,
Thanks for reaching out to us! I have relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @shans96 ,
Thank you once again for your feedback. After carefully reviewing your suggestion, our team has decided there are no adjustments needed in the problem description. Happy LeetCoding :)
