### ISSUE TITLE
Question Description - 302. Smallest Rectangle Enclosing Black Pixels

### ISSUE THREAD

**Issue by sapphire921** [LeetCode-Feedback/LeetCode-Feedback#6951]
#### Your LeetCode username
sapphire921

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the Constraints part of the question description, it says

1 <= x < m
1 <= y < n

but it should be

0 <= x < m
0 <= y < n

#### Expected behavior

The constraints of x and y should be:

0 <= x < m
0 <= y < n

**Comment by LC-Yani** [comment]
Hi @sapphire921 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
