### ISSUE TITLE
[BUG]780. 到达终点：缺少测试用例

### ISSUE THREAD

**Issue by luchaohai** [LeetCode-Feedback/LeetCode-Feedback#6953]
**你的 LeetCode 用户名**
苦行僧

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
测试用例缺少tx < ty 的极端测试情况：
示例如下：
1
1
1
999999990

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
/**
 * @param {number} sx
 * @param {number} sy
 * @param {number} tx
 * @param {number} ty
 * @return {boolean}
 */
var reachingPoints = function(sx, sy, tx, ty) {
    let flag = false;
    while(tx >= sx && ty >= sy) {
        if (tx === sx && ty === sy) {
            flag = true;
            break;
        }
        if (tx > ty) {
            const cnt = Math.floor((tx - sx) / ty) || 1;
            tx = tx - cnt * ty;
        } else ty = ty - tx;
    }
    return flag;
};
```

**期望行为**
我并没有优化tx < ty的情况，此时应该会超时。

**屏幕截图**
很抱歉，没办法上传截图，只能直接说数据：
执行用时：2720 ms 应该是要超时才对。

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。
