### ISSUE TITLE
提交显示内部错误

### ISSUE THREAD

**Issue by gjh16337068** [LeetCode-Feedback/LeetCode-Feedback#6954]
**你的 LeetCode 用户名**
gjh333

**Bug 类型**
- [x] 提交内部错误

**描述**
全部提交内部错误，执行也没结果

**你使用的语言**
C++

**你提交或者运行的代码**

**期望行为**
能有结果

**额外的上下文**
官网客服反馈就是机器人，严重影响使用

**Comment by feiceh** [comment]
感谢反馈，能否向我们补充题目信息，以及完善代码格式。可以参考[这个反馈](https://github.com/LeetCode-Feedback/LeetCode-Feedback/blob/master/.github/ISSUE_TEMPLATE/bug--------.md)，把信息提供完整才能有助于快速验证和精准的定位；也欢迎 [点击这里](https://support.leetcode-cn.com/hc/request/new/) 在工单附件上传完整的页面问题录屏，在收到回复后，我们会提交至相关部门进行核实并进行后续跟进。

**Comment by gjh16337068** [comment]
你们的工单回复效率太低了，我在英文版提交相同的代码完全没有问题，题目796
```
class Solution {
public:
    bool rotateString(string s, string goal) {
        if(s.size() != goal.size()) return false;
        for(int i = 0; i < s.size(); ++i){
            if(s[i] == goal[0] && s.substr(i)+s.substr(0,i) == goal) return true; 
        }
        return false;
    }
};
```

**Comment by gjh16337068** [comment]
![微信图片_20220409173731](https://user-images.githubusercontent.com/25917446/162568305-dd88693d-e80f-42d7-8b57-5fb9cddb8f70.png)

**Comment by feiceh** [comment]
Hello～我们已经收到你的反馈，并在工单 #23984 中进行了回复，请知晓。
