### ISSUE TITLE
Missing Test Case- 1527. Patients With a Condition

### ISSUE THREAD

**Issue by abhisek247767** [LeetCode-Feedback/LeetCode-Feedback#6955]
**Code-**

SELECT *
FROM patients
WHERE conditions like '% DIAB1%' or conditions like 'DIAB1%'

Test Case
**input**
{"headers": {"Patients": ["patient_id", "patient_name", "conditions"]}, "rows": {"Patients": [[1, "Daniel", "SADIAB100"]]}}
**output** 
{"headers": ["patient_id", "patient_name", "conditions"], "values": [[1, "Daniel", "SADIAB100"]]}

This two fest case at front. Beacause we aare the people not see this test case at first time so we doing at first

SELECT *
FROM patients
WHERE conditions like '%DIAB1%' 

Hope you will understand what i tiring to say

**Comment by LC-Yani** [comment]
Hi @,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by abhisek247767** [comment]
Code:
SELECT *
FROM patients
WHERE conditions like '% DIAB1%' or conditions like 'DIAB1%'

Language: SQL
