### ISSUE TITLE
Missing Test Case - 682. Baseball Game

### ISSUE THREAD

**Issue by shubhcodegate** [LeetCode-Feedback/LeetCode-Feedback#6957]
#### Your LeetCode username

kmr_shubh

#### Category of the bug
- [ ] Question
- [ ] Missing Test Cases 

#### Description of the bug

This question is incorrect. 
It is asking for INT in return and for the given test case the result will go out of range of INT.
Please modify the question by adding MOD return like 10e9 + 7.
Below test case will always fail, even though it satisfies the constraints of question.
Since, 2^1000 >> INT_MAX
This test case is not present in online judge.
Test case:
**["30000","30000","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D","D"]**

#### Code you used for Submit/Run operation

```
int T[1001];
class Solution {
public:
    int calPoints(vector<string>& ops) {
        int size = 0;
        for(string&op : ops) {
            switch(op[0]) {
                case 'C':
                    --size;
                    break;
                case '+':
                    T[size] = T[size - 1] + T[size - 2];
                    ++size;
                    break;
                case 'D':
                    T[size] = T[size - 1] * 2;
                    ++size;
                    break;
                default:
                    T[size] = stoi(op);
                    ++size;
                    break;
            }
        }
        return accumulate(T, T + size, 0);
    }
};
```

#### Language used for code

C++

#### Expected behavior

This solution should have given runtime error but it did not because Test case that should show runtime error is missing
Error:
Line 16: Char 43: runtime error: signed integer overflow: 1966080000 * 2 cannot be represented in type 'int' (solution.cpp)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:25:43

**Comment by stormsunshine** [comment]
To LeetCode: Please add one more constraint in problem description and apply it to testcases that all intermediate results and the final result must fit in 32-bit signed integers.

**Comment by stormsunshine** [comment]
To LeetCode: Please add one more constraint in problem description and apply it to testcases that all intermediate results and the final result must fit in 32-bit signed integers.

**Comment by LC-Yani** [comment]
Hi there,

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
