### ISSUE TITLE
Missing Test Case - 977. Squares of a Sorted Array

### ISSUE THREAD

**Issue by Prats0997** [LeetCode-Feedback/LeetCode-Feedback#6958]
#### Category of the bug
- [x] Solution

#### Code you used for Submit/Run operation

```
// Squares of Sorted Array
function sortedSquares(nums: number[]): number[] {
    const resArr: number[] = nums.map(x => x * x);
    return resArr.sort((a: any, b: any) => (a < b ? -1 : 1))
};
```

**Comment by LC-Sue** [comment]
Hi @Prats0997 
Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
