### ISSUE TITLE
Abort run code

### ISSUE THREAD

**Issue by BaluDeshamoni** [LeetCode-Feedback/LeetCode-Feedback#6959]
#### LeetCode username
 BaluDeshamoni 

#### Category 
- [ ] User Interface Suggestion

#### Description 
There is no option for aborting our code when the run code is pressed. We have to wait until the compiler runs our code if we want to change our mind and stop the code from running there is no option to do so.

**Comment by LC-Yani** [comment]
Hi there,

Thank you for reaching out to us and providing your feedback. I will let our team know of this suggestion.
