### ISSUE TITLE
Missing Test Case in 797: All Paths From Source to Target

### ISSUE THREAD

**Issue by markwgirard** [LeetCode-Feedback/LeetCode-Feedback#696]
#### Your LeetCode username

user1128xP

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
My submission passed because of missing test cases, but is incorrect. 

My submission assumed that the only vertex with in-degree equal to zero (i.e., no other vertices point to it) was vertex 0. Submission may fail if there are other vertices with in-degree equal to zero. It seems that all existing test cases only have vertex 0 with in-degree equal to zero.

New test cases should be included with graphs that have more than one vertex with zero in-degree. 

See suggestions below.

#### Code you used for Submit/Run operation

```
from collections import defaultdict
class Solution:
    def allPathsSourceTarget(self, graph: List[List[int]]) -> List[List[int]]:
        n = len(graph)
        graphTr =  defaultdict(set)
        for i in range(n):
            for j in graph[i]:
                graphTr[j].add(i)

        paths = defaultdict(list)
        paths[0] = [[]]
        
        stack = [0]
        while stack:
            i = stack.pop()
            paths[i] = [path+[i] for path in paths[i]]
            if i == n-1: break
            for j in graph[i]:
                paths[j].extend(paths[i])
                graphTr[j].discard(i)
                if not graphTr[j]:
                    stack.append(j)
            del paths[i]        
        
        return paths[n-1]
```

#### Language used for code
Python 3

#### Expected behavior
Here are some examples of graphs that have more than one vertex with zero in-degree. 
![Graph 1](https://i.ibb.co/jGRX67x/graph1.png)
Input: `[[2],[2],[]]`
My solution: `[[0]]`
Expected solution: `[[0,2]]

![Graph 2](https://i.ibb.co/BZHyPV3/graph2.png)
Input: `[[2],[2,3],[4,5],[5],[6],[6],[]]`
My solution: `[]`
Expected solution: `[[0,2,4,6],[0,2,5,6]]`

#### Screenshots
![image](https://i.ibb.co/2vzbDx5/success.png)
![image](https://i.ibb.co/Nj0gyhB/wrong.png)

**Comment by lc-ivan** [comment]
Hi @markwgirard ,
Thanks for reaching out to us! I have relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @markwgirard ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 200 LeetCoins (2 test case contributions) as the reward for this feedback. We appreciate your support!
