### ISSUE TITLE
Question Description - 682. Baseball Game

### ISSUE THREAD

**Issue by vaishnavi-janardhan** [LeetCode-Feedback/LeetCode-Feedback#6960]
#### Your LeetCode username

vaish_janardhan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question asks to return the sum of all the scores on the record but doesn't specify what should be the result when the record is empty.

#### Expected behavior

The question should have specified that the result would be 0 if the record is empty.
Example:
Input: ops = ["1","C"]
Output: 0

**Comment by LC-Yani** [comment]
Hi Vaishnavi Janardhan,

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
