### ISSUE TITLE
Issue with 627. Swap Salary

### ISSUE THREAD

**Issue by sagarkate** [LeetCode-Feedback/LeetCode-Feedback#6961]
#### Your LeetCode username

sagarkate

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
[ ] Missing Test Cases 

#### Description of the bug

When I run the query to update the table, it fails with the error stating Invalid Testcase 'salary'. It is a simple update statement.

#### Code you used for Submit/Run operation

```
UPDATE salary
SET sex = CASE sex WHEN 'm' THEN 'f' ELSE 'm' END
```

#### Language used for code

SQL (MySQL)

#### Expected behavior

The SQL Update statement should have run as it didn't have any errors. But it failed with Invalid Testcase error.

#### Screenshots

<img width="956" alt="image" src="https://user-images.githubusercontent.com/31794688/162621583-40be1a4e-c149-45f9-8cb1-9d73e1b4d85b.png">

**Comment by LC-Yani** [comment]
Hi Sagarkate,

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
