### ISSUE TITLE
MergeSort tutorial is not using recursion as says in the description

### ISSUE THREAD

**Issue by Kenzku** [LeetCode-Feedback/LeetCode-Feedback#6962]
link: https://leetcode.com/explore/learn/card/recursion-ii/470/divide-and-conquer/2868/

The whole article is about to explain recursion, and the example solving merge sort using top-down approach is said to be recursion as well:

> Here, we will explain the top down approach as it can be implemented naturally using recursion.

but the solution is using iterations:

``` Java

import java.util.Arrays;
public class Solution {
    
    public int [] merge_sort(int [] input) {
      if (input.length <= 1) {
        return input;
      }
      int pivot = input.length / 2;
      int [] left_list = merge_sort(Arrays.copyOfRange(input, 0, pivot));
      int [] right_list = merge_sort(Arrays.copyOfRange(input, pivot, input.length));
      return merge(left_list, right_list);
    }
    
    public int [] merge(int [] left_list, int [] right_list) {
      int [] ret = new int[left_list.length + right_list.length];
      int left_cursor = 0, right_cursor = 0, ret_cursor = 0;

      while (left_cursor < left_list.length && 
             right_cursor < right_list.length) {
        if (left_list[left_cursor] < right_list[right_cursor]) {
          ret[ret_cursor++] = left_list[left_cursor++];
        } else {
          ret[ret_cursor++] = right_list[right_cursor++];
        }
      }
      // append what is remain the above lists
      while (left_cursor < left_list.length) {
        ret[ret_cursor++] = left_list[left_cursor++];
      }
      while (right_cursor < right_list.length) {
        ret[ret_cursor++] = right_list[right_cursor++];
      }  
      return ret;
    }
}
```

I am expecting an example solution with recursion

**Comment by LC-Yani** [comment]
Hi Kenzku,

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Hi Kenzku,

Our content team reviewed you question and here is the answer from the team:
This while loop is responsible for combining two sorted lists into one sorted list. However, that does not make this an iterative solution.
The recursive part of this solution is in the merge_sort function itself. This can be seen where the merge_sort is recursively called when assigning left_list and right_list.

Best,

LC_Yani

**Comment by Kenzku** [comment]
Thank you
