### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by gstarikov** [LeetCode-Feedback/LeetCode-Feedback#6963]
#### Your LeetCode username
GeorgySt

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
test cases dont check worst case - large arrays nums1 & nums2 with interleaving values 
eg nums1={1,3,5,7,...,1e4-1}; nums2={2,4,6,8,...,1e4}
in my case i wrote code that copy elems in nums1 to i+1 pos and insert value from nums2
and got perfect performance score (because golang`s copy is optimized well)
then rewrite with good optimized reverse ordered version and got the same performance score.
and it is wrong. reverse ordered version in worst case is faster in about ~50 times

#### Code you used for Submit/Run operation
i offers the following code to check realizations speed. it simple generate large enough array of interleaving data.
```
func BenchmarkMergeBackward(b *testing.B) {
	const ln = 1e4
	t1 := make([]int, ln)
	n := ln >> 1
	m := ln - n
	t2 := make([]int, n)
	for i := 0; i < ln; i++ {
		if i%2 == 0 {
			t1[i/2] = i
		} else {
			t2[i/2] = i
		}
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		tmp := append([]int{}, t1...)
		MergeBackward(tmp, n, t2, m)
	}
}

// version excess of data coping
//cpu: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
//BenchmarkMergeBackward-8            1167           1004994 ns/op
func Merge(nums1 []int, m int, nums2 []int, n int) {
	var idx1, idx2 int
	filled := m
	for idx1 < filled && idx2 < n {
		p1, p2 := &nums1[idx1], &nums2[idx2]
		switch {
		case *p1 >= *p2: //need insert path of p2 into p1
			var i int
			for i = idx2; i < n && *p1 >= nums2[i]; i++ {
			}
			//nums2[idx2:i) -> nums1[idx1]
			ln := i - idx2
			copy(nums1[idx1+ln:], nums1[idx1:filled])
			copy(nums1[idx1:], nums2[idx2:i])
			idx2 += ln
			filled += ln
			idx1 += ln

		case *p1 < *p2: //skip p1 until it is less that p2
			for ; idx1 < filled && nums1[idx1] < *p2; idx1++ {
			}
		}
	}
	//copy tail
	copy(nums1[idx1:], nums2[idx2:n])
}

//optimized version
//cpu: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
//BenchmarkMergeBackward-8           54319             21828 ns/op

func MergeBackward(nums1 []int, m int, nums2 []int, n int) {
	switch {
	case m == 0:
		copy(nums1, nums2)
		return
	case n == 0:
		return
	}

	step := unsafe.Sizeof(nums1[0]) //be aware of spaces between array elements

	iPtr := reflect.ValueOf(&nums1[m+n-1]).Pointer()
	n1s := reflect.ValueOf(&nums1[0]).Pointer()
	n2s := reflect.ValueOf(&nums2[0]).Pointer()

	p1 := reflect.ValueOf(&nums1[m-1]).Pointer()
	p2 := reflect.ValueOf(&nums2[n-1]).Pointer()

	for p1 >= n1s && p2 >= n2s {
		tp1 := (*int)(unsafe.Pointer(p1))
		tp2 := (*int)(unsafe.Pointer(p2))
		ti := (*int)(unsafe.Pointer(iPtr))

		if *tp1 >= *tp2 {
			*ti = *tp1
			p1 -= step
		} else {
			*ti = *tp2
			p2 -= step
		}
		iPtr -= step
	}
	//copy tail
	if p2 >= n2s {
		//copy n2s:p2 to p1
		//calc indexes
		idx := (p2 - n2s) / step
		copy(nums1, nums2[:idx+1])
	}
}


```

#### Language used for code
Go

#### Expected behavior
i expect that realizations with excess of data coping got lower performance score

**Comment by LC-Yani** [comment]
Hi Gstarikov,

Thank you for reaching out to us. We reviewed you report, after we ran your programming code, we received a Compile Error, so we didn't add the test case. 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best,
LC_Yani
