### ISSUE TITLE
Missing Test Case - 1295. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by AnSon404** [LeetCode-Feedback/LeetCode-Feedback#6966]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Calculate wrong.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def findNumbers(self, nums):
        EvenDigits = 0
        for i in nums:
            digit = 0
            while i > 1:
                i /= 10
                digit += 1
            if digit%2 == 0:
                EvenDigits += 1
        return EvenDigits
```

#### Language used for code

Python

#### Expected behavior

expect to be correct.

**Comment by LC-Yani** [comment]
Hi Anson404,

Thank you for reaching out to us!
Please check the following link for different solutions: 
https://leetcode.com/problems/find-numbers-with-even-number-of-digits/discuss/1918253/Python-Math-approach-%2B-String-conversion-or-Clean-and-Simple-or-One-Liner
At the same time,  you can also ask your question in the "Discuss" section to get answers from other users.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best, 
LC_Yani
