### ISSUE TITLE
C programming code not available for each problem/solution. For each solution I could only see the code written in Java or  Python

### ISSUE THREAD

**Issue by prabhuyellina** [LeetCode-Feedback/LeetCode-Feedback#6969]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by prabhuyellina** [comment]
This is first time I am using Leetcode and I am not sure if the option already available to look the code in C language.

**Comment by LC-Sue** [comment]
Hi @prabhuyellina,
Thank you for reaching out to us, our solution articles are mainly provided in Python and Java, some problems maybe have C but mostly Java and Python. Sorry for any misunderstanding!
