### ISSUE TITLE
Wrong evaluation of an output: [109. Convert Sorted List to Binary Search Tree]

### ISSUE THREAD

**Issue by sekhar179** [LeetCode-Feedback/LeetCode-Feedback#697]
#### Your LeetCode username

sekhar179

#### Category of the bug
- [ ] Question
- [v] Solution
- [ ] Language

#### Description of the bug

Valid output is rejected by the evaluating program for a given test case. There are multiple outputs possible for a given test case and it should accept all the possible cases as valid output.

#### Code you used for Submit/Run operation

```
// Convert Sorted List to Binary Search Tree
class Solution {
public:
    TreeNode* root;
    int left, right;
    void insertNode(TreeNode* node, TreeNode* parent) {
        if (node->val < parent->val) {
            if (parent->left == NULL)
                parent->left = node;
            else
                insertNode(node, parent->left);
        } else {
            if (parent->right == NULL)
                parent->right = node;
            else
                insertNode(node, parent->right);
        }
    }
    void insert(TreeNode* node) {
        if (root == NULL) {
            root = node;
            return;
        }
        if (node->val < root->val)
            left++;
        else
            right++;
        insertNode(node, root);
    }
    void balanceLeft() {
        left++, right--;
        TreeNode* parent = root->right;
        root->right = parent->left;
        parent->left = root;
        root = parent;
    }
    void balanceRight() {
        left--, right++;
        TreeNode* parent = root->left;
        root->left = parent->right;
        parent->right = root;
        root = parent;
    }
    TreeNode* sortedListToBST(ListNode* head) {
        left = right = 0;
        root = NULL;
        ListNode* node = head;
        while (node) {
            TreeNode* temp = new TreeNode(node->val);
            insert(temp);
            if (abs(left - right) > 1) {
                if (left > right)
                    balanceRight();
                else
                    balanceLeft();
            }
            node = node->next;
        }
        return root;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input: [-10,-3,0,5,9,4,7]
Output: [5,0,9,-3,4,7,null,-10] -- This is also a balanced binary search tree, but it is rejected in test run.

#### Screenshots

![image](https://user-images.githubusercontent.com/65918795/88416847-8bdb1700-cdfe-11ea-989a-8193e8ee9daf.png)

**Comment by lc-pam** [comment]
Hi @sekhar179 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @sekhar179 
Thank you for your time. The team has reviewed your report. The code you provided is not correct and should be WA.
Input: [0,1,2,3,4,5]
Output: [2,1,3,0,null,null,4,null,null,null,5]
node 3 is not balanced.
For the test case you provided. it's actually an invalid case. Thanks for your support.
