### ISSUE TITLE
fdbk: Rust problem 1 Two Sum return type

### ISSUE THREAD

**Issue by srikarplus** [LeetCode-Feedback/LeetCode-Feedback#6972]
#### Your LeetCode username
srikarplus

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem description says to return indices. In Rust indices have a type of `usize` but the code snippet has `i32`.

#### Language used for code
Rust

#### Current behavior
```rust
pub fn two_sum(nums: Vec<i32>, target: i32) -> Vec<i32>
```

#### Expected behavior
```rust
pub fn two_sum(nums: Vec<i32>, target: i32) -> Vec<usize>
```

#### Additional context
This is definitely not a show stopper but a little inconvenience bcz of unnecessary casting of `usize` to `i32` needed before retuning answer.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
