### ISSUE TITLE
7. Reverse Integer - missing an important test case. 

### ISSUE THREAD

**Issue by jiwaCh** [LeetCode-Feedback/LeetCode-Feedback#6979]
The code below passes all the test case. However, it should not. For instance, it does not account for the condition when ```rev == Integer.MAX_VALUE / 10```, see the highlighted text in the screenshot below (The screenshot is from the leetcode article) - 
![image](https://user-images.githubusercontent.com/78536809/162904841-48f1af00-4475-4125-8094-a47b962b65ab.png)

```
public int reverse(int x) {

int rev = 0;
while (x != 0) {
   int pop = x % 10;
   x /= 10;
   if (rev > Integer.MAX_VALUE / 10) return 0;
   if (rev < -Integer.MIN_VALUE / 10) return 0;
   rev = rev * 10 + pop;
}
return rev;              
}
```

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language and testcase you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
