### ISSUE TITLE
564. Find the Closest Palindrome

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#698]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Approach 1: Brute Force[Time Limit Exceeded] has incorrect description

#### Code you used for Submit/Run operation

```
public class Solution {
    public String nearestPalindromic(String n) {
        long num = Long.parseLong(n);
        for (long i = 1;; i++) {
            if (isPalindrome(num - i))
                return "" + (num - i);
            if (isPalindrome(num + i))
                return "" + (num + i);
        }
    }
    boolean isPalindrome(long x) {
        long t = x, rev = 0;
        while (t > 0) {
            rev = 10 * rev + t % 10;
            t /= 10;
        }
        return rev == x;
    }
}
```

#### Language used for code

Java

#### Expected behavior

It doesn't TLE and submission was accepted. 

#### Screenshots

<img width="355" alt="Capture" src="https://user-images.githubusercontent.com/7014697/88445371-042de200-cdd7-11ea-8940-13230c49fff1.PNG">

**Comment by lc-ivan** [comment]
Hi @agatagruza ,
Thank you for reaching out with this case. After reviewing and testing the solution code on our end, we have received TLE ten times in a row after submitting (please see attached). Please note that **running code from a test case only tests that one test case** whereas **submitting the code tests all tests cases resulting in TLE**. If you have received a different outcome (such as Accepted) when **submitting** the code, please attach those images to this ticket and we will review as soon as possible!

![Screen Shot 2020-07-31 at 12 58 53 PM](https://user-images.githubusercontent.com/68418560/89072568-ae54bf00-d32d-11ea-804a-1e4f9da6f585.png)

**Comment by agatagruza** [comment]
Hi @lc-ivan When I run a code, code is accepted. When I submit a code, code is getting TLE. Please see image below:  <img width="951" alt="Capture" src="https://user-images.githubusercontent.com/7014697/89111587-5c369b00-d40c-11ea-8d7f-2546afac91d6.PNG">

**Comment by lc-ivan** [comment]
Hello there,
Yes, you are correct. The TLE in Approach 1 is supposed to TLE when submitted but may be accepted for individual test cases when running the code.
