### ISSUE TITLE
Missing Test Case - 627. Swap Salary

### ISSUE THREAD

**Issue by kireeti96** [LeetCode-Feedback/LeetCode-Feedback#6984]
#### Your LeetCode username
pylearner_11

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Running the code with test cases results in "Invalid TestCase". However, submitting the code works fine and the code is accepted.

#### Code you used for Submit/Run operation
```
UPDATE Salary
SET
    sex = CASE sex
        WHEN 'm' THEN 'f'
        ELSE 'm'
    END;
```

#### Language used for code
MySQL

#### Expected behavior
Expected to run the test case and give the result if the case is passed or failed. 

#### Screenshots

![Screen Shot 2022-04-12 at 11 22 48 AM](https://user-images.githubusercontent.com/29034422/163019084-df1a4cf5-66a8-422a-9f28-886836fe3c73.png)

**Comment by LC-Yani** [comment]
Hi, 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.
