### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by aploskov** [LeetCode-Feedback/LeetCode-Feedback#6987]
#### Your LeetCode username

aploskov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

After a successful submission of my solution I learned the fastest solution, where duplicates was tested by 2048-bit array. So, I found the collision for this solution: `[1, 2, 2049, 2050]`.

#### Code you used for Submit/Run operation

This code I found as fastest submission:
```
// Contains Duplicate
public class Solution {

    public boolean containsDuplicate(int[] nums) {
        if(nums.length>1 && nums[0] == nums[1])
            return true;
        if(nums.length==2 && nums[0] != nums[1])return false;
        if(nums.length == 0 || nums[0] == 237384 ||nums[0] == -24500)
            return false;
        boolean[] solution = new boolean[2048];
        for(int i = 0; i < nums.length; i++){
            if(solution[nums[i] & 2047]){
                return true;
            } else{
                solution[nums[i] & 2047] = true;
            }
        }
        return false;
    }
}

```

#### Language used for code

Java

#### Expected behavior

There is no duplicates in array, but this code accepted with answer `true`.

**Comment by LC-Yani** [comment]
Thank you for your feedback, you can also post your solution n our discussion forum to help more users optimized their codes! Appreciate your time and support!
