### ISSUE TITLE
Missing Test Case - 176. Second Highest Salary

### ISSUE THREAD

**Issue by k0adarsh** [LeetCode-Feedback/LeetCode-Feedback#6989]
#### Your LeetCode username

k0adarsh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

My solution has been accepted but there's a test case where my solution gives the wrong output.

#### Code you used for Submit/Run operation

```
select 
case
    when count(distinct a.salary) <= 1 then null
    else min(salary)  
end  
as SecondHighestSalary from
(select salary from Employee order by salary desc limit 2) a;
```

#### Language used for code

C++

#### Expected behavior

The solution I provided above has been accepted but it shouldn't be as for 
TEST CASE : {"headers":{"Employee":["id","salary"]},"rows":{"Employee":[[1,100],[2,100],[3,50]]}} it gives wrong answer.
When I run the solution for the same test case on custom input it shows the wrong answer but the same solution has been accepted..
Check the provided Screenshot.

#### Screenshots

<img width="951" alt="leetcode tc" src="https://user-images.githubusercontent.com/38538532/163039896-286d6f4b-98aa-45aa-a916-f6e076bc3a19.png">

**Comment by LC-Yani** [comment]
Hi @k0adarsh 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
