### ISSUE TITLE
702. Search in a Sorted Array of Unknown Size

### ISSUE THREAD

**Issue by y-yagi** [LeetCode-Feedback/LeetCode-Feedback#699]
#### Your LeetCode username

y-yagi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

 API interface is wrong in the Golang example of `702. Search in a Sorted Array of Unknown Size`.

```go
/**
 * // This is the ArrayReader's API interface.
 * // You should not implement it, or speculate about its implementation
 * type ArrayReader struct {
 * }
 *
 * func (this *MountainArray) get(index int) int {}
 */

func search(reader ArrayReader, target int) int {
    
}
```

The example uses `MountainArray` in `get` function, but that should be `ArrayReader`.

#### Language used for code

Go

#### Screenshot 

![image](https://user-images.githubusercontent.com/987638/88446628-99c48280-ce66-11ea-885f-c231fe9120ec.png)

**Comment by lc-ivan** [comment]
Hi @y-yagi ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @y-yagi ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
