### ISSUE TITLE
562. Longest Line of Consecutive One in Matrix

### ISSUE THREAD

**Issue by Sergei-Morozov** [LeetCode-Feedback/LeetCode-Feedback#6991]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 2: Using 3D Dynamic Programming

Incorrect image at https://leetcode.com/problems/longest-line-of-consecutive-one-in-matrix/Figures/562_Longest_Line.PNG 

Image for dp[1] is incorrect, cell at row 3 col 3 should be filled with 1

dp[1][3][3] should be equal to ONE according to provided solution

```
if (M[i][j] == 1) {
     dp[i][j][1] = i > 0 ? dp[i - 1][j][1] + 1 : 1;
}
```

**Comment by LC-Yani** [comment]
Hi @Sergei-Morozov 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
