### ISSUE TITLE
Solutions that use class members are not allowed

### ISSUE THREAD

**Issue by ShubhamDeshkar** [LeetCode-Feedback/LeetCode-Feedback#6992]
Solutions should be contained within the method and none of the variables should be outside of it. There is no point in creating solutions that make use of class variables specially when there is recursion involved. Every type of recursive question would actually become trivial if you use global variables. I would argue that is considered cheating!

Write a proper and smart solution without using global variables because they're simply not accepted during an interview. While live coding sessions or during online assessment you're only give a method signature or is asked to construct a method. You're not given a class. In fact in real word there doesn't exist a `class Solution`  there only exists a self-contained method that can be thrown around which works like a solid unit and is unit testable. I think that is common sense!

**Comment by LC-Yani** [comment]
Hi @ShubhamDeshkar 
Thank you for your time. I've provided the feedback to our content team.  We appreciate your support!
