### ISSUE TITLE
Incorrect Statement - 59. Spiral Matrix II

### ISSUE THREAD

**Issue by stressedtyagi** [LeetCode-Feedback/LeetCode-Feedback#6996]
#### Your LeetCode username
divyanshutyagi

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Incorrect statement on Approach 1: Traverse Layer by Layer in Spiral Form. In explanation, it is written, "From bottom right corner to top left corner" alongside the Direction 4 tag. 

#### Expected behavior
The rather correct statement is "From bottom left corner to top left corner"

#### Screenshots
![image](https://user-images.githubusercontent.com/24351821/163230331-578ede32-a96c-4102-81fd-bb721d9bd1b1.png)

**Comment by LC-Yani** [comment]
Hi @stressedtyagi 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
