### ISSUE TITLE
627. Swap Salary - Invalid Testcase error thrown

### ISSUE THREAD

**Issue by aaronangxz** [LeetCode-Feedback/LeetCode-Feedback#6998]
#### Your LeetCode username

angxze

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Upon running the code, `Invalid Testcase: 'salary'` is returned.
Trying with `Salary` (table name specified in the question) / `salary` did not help with the situation.

#### Code you used for Submit/Run operation

```sql
UPDATE Salary SET sex = IF(sex='m','f','m');
```

#### Language used for code

MySQL

#### Expected behavior

Should run the test case instead of throwing error.

#### Screenshots

![Screenshot 2022-04-14 at 11 52 03 AM](https://user-images.githubusercontent.com/66870149/163310421-13258b88-ebac-48a6-9abf-10f7bc3c6985.png)

**Comment by LC-Yani** [comment]
Hi @aaronangxz 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
