### ISSUE TITLE
Missing test cases

### ISSUE THREAD

**Issue by pssharma1410** [LeetCode-Feedback/LeetCode-Feedback#6999]
Question
1232. Check If It Is a Straight Line
Reason
I was checking the discuss section but I came to a solution where the code was wrong but still the code was accepted by Leetcode and the test case for which leetcode haven't added is : 
[[1,2],[2,2],[3,3]] .((This code is accepted but it is failing for the testcase given).)
If a solution even after checking if the line is not on x or y axis goes to checking the slope(x/y) it will give Arithmetic error but since this test case has not been added in the question therefore the solution is accepted with a flaw.
The code I am referring is : (This code is accepted but it is failing for the testcase given).
```
class Solution {
    public boolean checkStraightLine(int[][] coordinates) {
         //all x are same
       
        for(int i=0;i<coordinates.length-1;i++)
        {
            if(coordinates[i][0]==coordinates[i+1][0])
            {
               
               if(i==(coordinates.length-2))
               {
                   return true;
               }
            }
            else
                break;
            
        }
       //all y are same 
        for(int i=0;i<coordinates.length-1;i++)
        {
            if(coordinates[i][1]==coordinates[i+1][1])
            {
               if(i==(coordinates.length-2))
               {
                    
                   return true;
               }
            }
            else
                break;
        }
        
      //x and y are diff
        
        double slope=(coordinates[1][0]-coordinates[0][0])/((double)(coordinates[1][1]-coordinates[0][1]));
        for(int i=1;i<coordinates.length;i++)
        {
            double x=coordinates[i][0]-coordinates[i-1][0];
            double y=coordinates[i][1]-coordinates[i-1][1];
          
            if(slope==(x/y))
            {
                continue;
            }
            else
            {
                return false;
            }
    
        }
        return true;
        
    }
     
}
```
Test Cases
[[1,2],[2,2],[3,3]]

**Comment by LC-Yani** [comment]
Hi @pssharma1410 ,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best,

LC_Yani

**Comment by pssharma1410** [comment]
I used JAVA language

**Comment by LC-Yani** [comment]
Hi @pssharma1410 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
