### ISSUE TITLE
Test-case out of constraint

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#70]
**What kind of the bug**

- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
https://leetcode.com/problems/bus-routes/

Problem 815. Bus Routes

The second constraint is 1 <= routes[i].length <= 500, while I met a testcase beyond this constraint

**Screenshots**
![Snipaste_2020-03-23_21-41-15](https://user-images.githubusercontent.com/32877011/77385978-3eb33f80-6d4f-11ea-9e0f-14fccecd27db.png)

**Comment by CooperCooperCooper** [comment]
Hi @caoxingdong,
Thank you for reaching out to us. I've relayed this issue to our engineers to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @caoxingdong,
Thank you for your time. We've updated the test case constraint. Please try it now :)
