### ISSUE TITLE
Wrong expected output - 328. Odd Even Linked List

### ISSUE THREAD

**Issue by siddharth784** [LeetCode-Feedback/LeetCode-Feedback#7000]
#### Your LeetCode username
user4161Vv

#### Category of the bug
- [ ] Solution

#### Description of the bug
In the test cases where there are either all odd values or all even values in the given linked list, the relative order must be maintained according to the question. Hence in such test cases, the given linked list must be returned as it is in the same order, to retain the relative order within the Linked list. However, the expected output for such cases is wrong and does not maintain the relative order

#### Code you used for Submit/Run operation

```
class Solution {
    public ListNode oddEvenList(ListNode head) {
        if(head==null || head.next==null ||head.next.next==null)
            return head;
        
        
        ListNode curr=head;
        ListNode odd=new ListNode();
        ListNode oddhead=odd;
        ListNode even=new ListNode();
        ListNode evenhead=even;
        ListNode i=head;
        int j=0;
        while(curr!=null){
            if(j%2==0){
                odd.next=curr;
                odd=odd.next;
            }
            else{
                even.next=curr;
                even=even.next;
            }
            curr=curr.next;
            j++;
        }
        even.next=null;
        odd.next=evenhead.next;
        return oddhead.next;
        // return head;
    }
}
```

#### Language used for code
Java

#### Expected behavior
expected the linked list to be returned as it is for linked lists like [1,3,5,7] but instead it expects the output to be [1,5,3,7].

**Comment by LC-Yani** [comment]
Hi @siddharth784 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. Our content team checked the issue, the statement is correct, we are talking about indices and not values. We appreciate your support!
