### ISSUE TITLE
Missing Test Case - 1141. User Activity for the Past 30 Days I

### ISSUE THREAD

**Issue by y4cj4sul3** [LeetCode-Feedback/LeetCode-Feedback#7001]
#### Your LeetCode username
y4cj4sul3

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases of date after `2019-07-27`, and the solution does not check for this kind of test case and expect dates after `2019-07-27` should be included.
If the question is designed to have no activities after `2019-07-27`, it should report an invalid testcase if there is any date after `2019-07-27` when using the custom testcase.

#### Code you used for Submit/Run operation
```
SELECT
    activity_date AS day,
    COUNT(DISTINCT user_id) AS active_users
FROM 
    Activity
WHERE
    DATEDIFF("2019-07-27", activity_date) < 30
GROUP BY
    activity_date
```

#### Language used for code
MySQL

#### Expected behavior
The above code which doesn't check for dates after `2019-07-27` should receive wrong answer result rather than acceptance.
Also, the solution should not allow activities with dates after `2019-07-27`.

#### Screenshots

<img width="945" alt="截圖 2022-04-14 下午6 03 34" src="https://user-images.githubusercontent.com/18673736/163363346-22abf569-9a5e-4779-9f24-92dce86bfa8a.png">

**Comment by LC-Yani** [comment]
Hi @,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The testcase that you use. Then we can provide to the team to investigate. 

We appreciate your time and support.

**Comment by LC-Yani** [comment]
Hi @y4cj4sul3 ,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The testcase that you use. Then we can provide to the team to investigate.

We appreciate your time and support.

**Comment by y4cj4sul3** [comment]
Hi @LC-Yani,

Here is the testcase I used. It is the example testcase with the `activity_date` of the last row modified from `2019-06-25` to `2021-06-25`. The result is shown in the above screenshot.
```
{"headers":{"Activity":["user_id","session_id","activity_date","activity_type"]},"rows":{"Activity":[[1,1,"2019-07-20","open_session"],[1,1,"2019-07-20","scroll_down"],[1,1,"2019-07-20","end_session"],[2,4,"2019-07-20","open_session"],[2,4,"2019-07-21","send_message"],[2,4,"2019-07-21","end_session"],[3,2,"2019-07-21","open_session"],[3,2,"2019-07-21","send_message"],[3,2,"2019-07-21","end_session"],[4,3,"2019-06-25","open_session"],[4,3,"2021-06-25","end_session"]]}}
```

Actually, any testcases with at least one `activity_date` greater than `2019-07-27` can show the problem.

**Comment by LC-Yani** [comment]
Hi @y4cj4sul3 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Our content team tested your code and teatcase, This test case does not fail the provided solution.
Thank you for your time. We appreciate your support!
