### ISSUE TITLE
 983. Minimum Cost For Tickets

### ISSUE THREAD

**Issue by nitya2002** [LeetCode-Feedback/LeetCode-Feedback#7003]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Yani** [comment]
Hi @nitya2002 ,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

what is the missing test?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best,

LC_Yani
