### ISSUE TITLE
Missing Test Case - 110. Balanced Binary Tree

### ISSUE THREAD

**Issue by kamalov-sergey** [LeetCode-Feedback/LeetCode-Feedback#7004]
#### Your LeetCode username

kamalov_sergey 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug

Test case executed in test mode but not executed when it was submitted 

#### Code you used for Submit/Run operation

```
class Solution(object):
    
    
    def takeLst(self, root1, i = 0, ls = []):
        
        if not root1:
            return []
        
        i = i + 1
        
        if not root1.left and not root1.right:
            ls.append(i)
            
        self.takeLst(root1.left, i, ls)
        self.takeLst(root1.right, i, ls)
    
        return ls
    
    
    def isBalanced(self, root):
        """
        :type root: TreeNode
        :rtype: bool
        """
        ls = self.takeLst(root)
        print(ls)
        while len(ls) > 0:
            k = ls.pop()
            for i in ls:
                if abs(k-i) > 1:
                    return False 

        return True
```

#### Language used for code
<!-  -->
Python 3

#### Expected behavior

when input == [1] and I submit my code, result will be the same when I push  "Run Code" - Accepted

#### Screenshots

 ![image](https://user-images.githubusercontent.com/37145739/163480861-8941a0ff-0a20-496a-bbb2-52ac7b1eaf6f.png)
![image](https://user-images.githubusercontent.com/37145739/163480907-45afabf2-2f34-4899-9fa3-0e689e997dac.png)

**Comment by LC-Yani** [comment]
Hi there,

Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
