### ISSUE TITLE
Solution 1.  TwoSum. Extra action at the end of execution

### ISSUE THREAD

**Issue by evamass** [LeetCode-Feedback/LeetCode-Feedback#7005]
#### Your LeetCode username
evamass

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

First loop condition from `BruteForce` example should be ended at `array.len-1`, because last element does not have next one.

#### Code you used for Submit/Run operation

```
// Two Sum
    for(let i = 0; i < nums.length - 1; i++) {
        for(let ii = i+1; ii < nums.length; ii++) {
            if ((nums[i] + nums[ii]) === target) {
                return [i, ii]
            }
        }
    }
```

#### Language used for code
Javascript

#### Expected behavior
Correct example
```
class Solution {
    public int[] twoSum(int[] nums, int target) {
        for (int i = 0; i < nums.length - 1; i++) {
            for (int j = i + 1; j < nums.length; j++) {
                if (nums[j] == target - nums[i]) {
                    return new int[] { i, j };
                }
            }
        }
        // In case there is no solution, we'll just return null
        return null;
    }
}
```

**Comment by LC-Yani** [comment]
Hi @

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for sharing your concern. Either way is acceptable when writing the upper bound for i. The reason is that, when i reaches array.len - 1 then j will be initialized as array.len and thus we will not iterate over j. As such, the suggested change will not alter the function or efficiency of the solution.
