### ISSUE TITLE
Missing Test Case - 449. Serialize and Deserialize BST

### ISSUE THREAD

**Issue by westy92** [LeetCode-Feedback/LeetCode-Feedback#7007]
#### Your LeetCode username
westy92

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the Kotlin language template, the comment on line 10 is `// Encodes a URL to a shortened URL.` It should be `// Encodes a tree to a single string.`

#### Code you used for Submit/Run operation
N/A

#### Language used for code
Kotlin

**Comment by LC-Yani** [comment]
Hi @westy92 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by westy92** [comment]
You're welcome!
