### ISSUE TITLE
Solution 2 - 802. Find Eventual Safe States

### ISSUE THREAD

**Issue by devyas** [LeetCode-Feedback/LeetCode-Feedback#7009]
#### Your LeetCode username

devyas

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
Solution

#### Description of the bug

In solution 2 (python), variable "WHITE" is declared but later compared with "white" within dfs(). 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def eventualSafeNodes(self, graph):
        WHITE, GRAY, BLACK = 0, 1, 2
        color = collections.defaultdict(int)

        def dfs(node):
            if color[node] != white:
                return color[node] == BLACK

            color[node] = GRAY
            for nei in graph[node]:
                if color[nei] == BLACK:
                    continue
                if color[nei] == GRAY or not dfs(nei):
                    return False
            color[node] = BLACK
            return True

        return filter(dfs, range(len(graph)))
```

#### Language used for code

Python

**Comment by sohampatel12** [comment]
Test

**Comment by LC-Yani** [comment]
Hi @devyas 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
