### ISSUE TITLE
220. Contains Duplicate III - Missing Testcase

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#701]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Official solution  Approach 2: (Binary Search Tree) [Accepted] is failing a test case and getting an overflow error. 

#### Code you used for Submit/Run operation

```
public boolean containsNearbyAlmostDuplicate(int[] nums, int k, int t) {
    TreeSet<Integer> set = new TreeSet<>();
    for (int i = 0; i < nums.length; ++i) {
        // Find the successor of current element
        Integer s = set.ceiling(nums[i]);
        if (s != null && s <= nums[i] + t) return true;

        // Find the predecessor of current element
        Integer g = set.floor(nums[i]);
        if (g != null && nums[i] <= g + t) return true;

        set.add(nums[i]);
        if (set.size() > k) {
            set.remove(nums[i - k]);
        }
    }
    return false;
}
```

#### Language used for code

Java

#### Expected behavior

For
```
[2147483646, 2147483647]
k = 1, t = 2147483647
```
official solution returns false. However it should return true.

#### Screenshots

<img width="477" alt="Capture" src="https://user-images.githubusercontent.com/7014697/88447159-1ca4f900-cde5-11ea-98a1-333ce3b50ee8.PNG">

**Comment by lc-ivan** [comment]
Hi @agatagruza  ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @agatagruza ,
Thank you for your feedback regarding this problem. After reviewing your request, our team has decided not to add this test case as it only introduces overflow in Java. Once again, we appreciate your feedback greatly! Happy LeetCoding!
