### ISSUE TITLE
Missing Test Case - 772. Basic Calculator III

### ISSUE THREAD

**Issue by UKGANG** [LeetCode-Feedback/LeetCode-Feedback#7010]
#### Your LeetCode username
ukgang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
# 772. Basic Calculator III
class Solution:
    def __init__(self):
        self._opt_map = {
            '+': lambda a, b: a + b,
            '-': lambda a, b: a - b,
            '*': lambda a, b: a * b,
            '/': lambda a, b: int(a / b),
        }

    def calculate(self, s: str) -> int:
        curr = ''
        stack = []
        for c in s:
            if c.isnumeric() or c in self._opt_map:
                curr += c
                continue
            if c == '(':
                stack.append(curr)
                curr = ''
                continue
            if c == ')':
                curr = f'{self.calculate_without_bracket(curr)}'
                if not stack:
                    curr = str(curr)
                    continue
                prev = stack.pop()
                if not prev:
                    continue

                if curr[0] == '-':
                    sign = prev[-1]
                    if sign == '-':
                        curr = f'{prev[:-1]}+{curr[1:]}'
                    elif sign == '+':
                        curr = f'{prev[:-1]}{curr}'
                    else:
                        if prev[0] == '-':
                            curr = f'{prev[1:]}{curr[1:]}'
                        else:
                            curr = f'-{prev}{curr[1:]}'
                else:
                    curr = f'{prev}{curr}'

        return int(self.calculate_without_bracket(curr))

    def calculate_without_bracket(self, s):
        s = s.replace(" ", "")
        stack = []
        prev = ''
        idx = 0
        while idx < len(s):
            c = s[idx]
            if c.isnumeric():
                prev += c
                idx += 1
                continue
            if c in '+-':
                if prev:
                    stack.append(int(prev))
                prev = c
                idx += 1
                continue
            while idx < len(s) and s[idx] in "*/":
                opt = self._opt_map[s[idx]]
                idx += 1
                curr = ''
                while idx < len(s) and s[idx].isnumeric():
                    curr += s[idx]
                    idx += 1
                prev = opt(int(prev), int(curr))

        stack.append(int(prev))
        return sum(stack)
```

#### Expected behavior

This solution should not pass this test case
1+1*2*(1-2)

**Comment by LC-Yani** [comment]
Hi @UKGANG ,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best,

LC_Yani

**Comment by UKGANG** [comment]
Hello Yani,


The program I submitted is written in python3.


Best,


JIAN JIAN

Assistant Market Researcher
Syracuse University

From: LC-Yani ***@***.***>
Date: Monday, April 18, 2022 at 6:49 PM
To: LeetCode-Feedback/LeetCode-Feedback ***@***.***>
Cc: Jian Jian ***@***.***>, Mention ***@***.***>
Subject: Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 772. Basic Calculator III (Issue #7010)

Hi @UKGANG<https://github.com/UKGANG> ,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best,

LC_Yani

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Invalid test case, fixed the validator to show that.
We appreciate your support!
