### ISSUE TITLE
Missing word - 669. Trim a Binary Search Tree

### ISSUE THREAD

**Issue by whoan** [LeetCode-Feedback/LeetCode-Feedback#7011]
#### Your LeetCode username

whoan

#### Category of the bug

- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There's a missing word here: _The number of nodes in the tree **is** in the range [1, 104]._

#### Code you used for Submit/Run operation

N/A

**Comment by LC-Yani** [comment]
Hi @whoan 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
