### ISSUE TITLE
Missing Test Case - 220. Contains Duplicate III

### ISSUE THREAD

**Issue by zangxin444** [LeetCode-Feedback/LeetCode-Feedback#7014]
#### Your LeetCode username

zangxin444@qq.com

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

If a bucket sort approach is used to solve the problem, negative bucket indexes should be considered well.
Even if the index is negative, the index must be contiguous.
The code I submit was a successful answer, but it was not correct on the case which contains a negative and positive numbers and these two numbers meet both k and t conditions.

Test case eg:

[-1,2]
3
3

#### Code you used for Submit/Run operation

```
func containsNearbyAlmostDuplicate(nums []int, k int, t int) bool {
    width := int64(t) + int64(1)
    bucketMap := make(map[int64]int)
    
    for i, n := range nums {        
        bucketIndex := getIndex(int64(n), width)
        
        if _, ok := bucketMap[bucketIndex]; ok {
            return true
        }
        
        if left, ok := bucketMap[bucketIndex - int64(1)];ok {
            if abs(left, n) <= int64(t) {
                return true
            }
        }
        
        if right, ok := bucketMap[bucketIndex + int64(1)];ok {
            if abs(right, n) <= int64(t) {
                return true
            }
        }
        
        bucketMap[bucketIndex] = n   
        
        if i + 1 > k {
            delete(bucketMap, getIndex(int64(nums[i - k]), width))
        }
    }
    
    return false
}

func getIndex(n, w int64) int64 {
    var bucketIndex int64
    
    if int64(n) < 0 {
        bucketIndex = -int64(n) / w
        bucketIndex += 2147483648
    } else {
        bucketIndex = int64(n) / w
    }
    
    return bucketIndex
}

func abs(a, b int) int64 {
    r := int64(a) - int64(b)
    
    if r > 0 {
        return r
    } else {
        return -r
    }
}
```

#### Language used for code

Golang

#### Expected behavior

The result of the code is false, and the expected result is true.

#### Screenshots

<img width="456" alt="image" src="https://user-images.githubusercontent.com/16473750/163600740-8ed9a0eb-783b-401e-b68d-82e4f60cd85d.png">

<img width="924" alt="image" src="https://user-images.githubusercontent.com/16473750/163601034-41979b17-2a92-49b2-a333-7e0c22b4cbf1.png">

#### Additional context

N/A

**Comment by LC-Yani** [comment]
Hi @zangxin444 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by LC-Yani** [comment]
Hi zangxin,

would you mind send me your Leetcode Username then I can add 100 Leetcoins to your account?

Best,

Yani

**Comment by zangxin444** [comment]
sure, LeetCode ID: Syn_0000
Thanks

**Comment by LC-Yani** [comment]
Rewards Added
