### ISSUE TITLE
Missing Test Case - 101. Symmetric Tree

### ISSUE THREAD

**Issue by BodhiYonzon** [LeetCode-Feedback/LeetCode-Feedback#7016]
#### Your LeetCode username

bodhiyonzon

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Missing Test Case

#### Description of the bug

There is no example test case to see if the program is comparing the values of nodes instead of just checking if the structure of the tree is symmetric.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isSymmetric(TreeNode root) {
        if(root==null)
            return true;
        return symmetry(root.left,root.right);
    }
    boolean symmetry(TreeNode left,TreeNode right){
        if(left==null)
            return right==null;
        if(right==null||left.val!=right.val)
            return false;
        return (symmetry(left.left,right.right)&&symmetry(left.right,right.left));
    }
}
```

#### Language used for code

Java

#### Expected behavior

There should be a test case which has a tree with symmetric structure but asymmetric values on the right and left subtree to test if the values are also being checked for symmetry.
eg.
[1,2,2,3,4,4,5]

**Comment by LC-Yani** [comment]
Hi @BodhiYonzon 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've submitted your feedback to update the problem.  We appreciate your support!
