### ISSUE TITLE
Missing Test Case - 669. Trim a Binary Search Tree

### ISSUE THREAD

**Issue by joshuastough** [LeetCode-Feedback/LeetCode-Feedback#7018]
#### Your LeetCode username
jvs008

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the Question one example is "Input: root = [3,0,4,null,2,null,null,1], low = 1, high = 3". I thought the list representation should be a complete BST, but then there aren't enough nulls or else doesn't represent the tree shown. The list should be "[3,0,4,None,2,None,None,None,None,1]" in order for 1 to be the left child of 2 at level 3 of the tree. My code worked fine but you might use a function like this to construct the tree given a list:
```python
def listToTree(lyst, ind = 0):
    if ind >= len(lyst) or lyst[ind] is None:
        return None
    # print(lyst, ind) # debugging
    root = TreeNode(lyst[ind], listToTree(lyst, 2*ind+1), listToTree(lyst, 2*ind+2))
    return root
```

#### Code you used for Submit/Run operation

```python
# Again, this code works fine, it's the problem description that is the issue
class Solution:
    def trimBST(self, root: Optional[TreeNode], low: int, high: int) -> Optional[TreeNode]:
        if root is None:
            return root
        
        if root.val == low:
            root.left = None
            root.right = self.trimBST(root.right, low, high)
            return root
        
        if root.val == high:
            root.right = None
            root.left = self.trimBST(root.left, low, high)
            return root
            
        if root.val > high:
            return self.trimBST(root.left, low, high)
        elif root.val < low:
            return self.trimBST(root.right, low, high)
        
        # val is in the range [low, high], so we need everything
        root.left = self.trimBST(root.left, low, high)
        root.right = self.trimBST(root.right, low, high)
        return root
```

#### Language used for code

python

#### Additional context

Please see the description of the bug above.

**Comment by LC-Yani** [comment]
Hi @joshuastough 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've submitted your feedback.  We appreciate your support!
