### ISSUE TITLE
Please show "followup" only after the first accepted submission

### ISSUE THREAD

**Issue by mejariamol** [LeetCode-Feedback/LeetCode-Feedback#7019]
Please hide the follow-up section on the question detail page as it disturbs the incremental problem-solving method. The follow-up section should be made visible after the first accepted submission to the question.

<img width="949" alt="Screenshot 2022-04-16 at 9 04 13 PM" src="https://user-images.githubusercontent.com/13533840/163681161-2d63c662-23b9-4cb6-bb88-fe7bcf465609.png">

**Comment by LC-Yani** [comment]
Hi @mejariamol 
Thank you for your feedback to help us update the problem.  I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by mejariamol** [comment]
Hi @LC-Yani , the feedback applies to all the problems which contain a "Follow up section". My feedback is - a follow-up section should not be shown upfront when a user opens a new problem. The user should see it only after her first accepted solution. One simple solution I propose here is - to keep the follow-up section hidden in an expandable view. This will allow the user to see it when she wants to see it.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the content team, but it will take some times to update. We appreciate your support!
