### ISSUE TITLE
剑指 Offer 33. 二叉搜索树的后序遍历序列.    不知道哪里错了，哪位大佬能指出来吗

### ISSUE THREAD

**Issue by Feynpoint** [LeetCode-Feedback/LeetCode-Feedback#702]
输入一个整数数组，判断该数组是不是某二叉搜索树的后序遍历结果。如果是则返回 true，否则返回 false。假设输入的数组的任意两个数字都互不相同。
[5, 2, -17, -11, 25, 76, 62, 98, 92, 61]这个测试案例错了

func verifyPostorder(postorder []int) bool {
    
    if len(postorder) <= 2 {
        return true
    }

    i := 0
    end := len(postorder) - 1
    for ; i < end; i++ {
        if postorder[i] > postorder[end] {
            break
        }
    }
    if i == end {
        return true
    }
    for j := i; j < end; j++ {
        if postorder[j] < postorder[end] {
            return false
        }
    }

    return verifyPostorder(postorder[:i]) && verifyPostorder(postorder[i:end])
}

**Comment by feiceh** [comment]
你好，建议再仔细调试一下代码。希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至 力扣圈子（https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=）  进行题目交流，以获得更好的支持。
