### ISSUE TITLE
Missing Test Case - 819. Most Common Word

### ISSUE THREAD

**Issue by idkwhojamesis** [LeetCode-Feedback/LeetCode-Feedback#7020]
#### Your LeetCode username

idkwhojamesis

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Not sure if the test cases include "invalid" sentences, but if I add punctuation to both the beginning and end of `paragraph` as a test case, when I `string.split(/\W+/)` in JavaScript, the first and last elements of the new array will be an empty string `''`. If `''` ends up being the most common unbanned word, I would end up returning `''` as the final result. The test cases do not account for this and I pass 100% using `string.split(/\W+/)`.

I used a custom testcase `"..Bob hit a ball, the hit BALL flew far after it was hit.", ["hit"]` as an example. Notice the two periods at the beginning.  

Again, if the testcases are not concerned with "invalid" sentences, which this would be, then ignore this. I just thought of this as when I use `string.split(/\W+/)`, the last element is always an empty string as it splits between the last word and the period. 

If the test cases had accounted for the possibility of an empty string occurring twice in my array of `paragraph` words, I would correct the code to filter out those empty strings. Currently, I do not have to do this.

#### Code you used for Submit/Run operation

```
var mostCommonWord = function(paragraph, banned) {
  const counts = new Map();
  const banMap = new Map();
  banned.forEach(word => banMap.set(word, true));
  const words = paragraph.toLowerCase().split(/\W+/);
  
  for (let word of words) {
    if (!banMap.has(word)) {
      if (!counts.has(word)) {
        counts.set(word, 0);
      }
      counts.set(word, counts.get(word) + 1);
    }
  }
  let max = null;
  const keys = [...counts.keys()];
  for (let key of keys) {
    const newCount = counts.get(key);
    if (max === null) max = key;
    else if (newCount > counts.get(max)) max = key;
  }
  return max;
};
```

#### Language used for code

JavaScript

#### Expected behavior

Fail submission; instead, I get 100% Accepted as the test cases don't account for this.   

#### Screenshots

<img width="956" alt="Screen Shot 2022-04-16 at 9 40 04 AM" src="https://user-images.githubusercontent.com/43428092/163683725-c636e314-1d40-4abb-b296-c5bdc200e032.png">

<img width="559" alt="Screen Shot 2022-04-16 at 9 44 32 AM" src="https://user-images.githubusercontent.com/43428092/163683858-918d8585-fe12-40c4-b7ad-5742cb1393ae.png">

**Comment by LC-Yani** [comment]
Hi @idkwhojamesis 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
