### ISSUE TITLE
Missing Test Case - 1141. User Activity for the Past 30 Days I

### ISSUE THREAD

**Issue by ohaanika** [LeetCode-Feedback/LeetCode-Feedback#7022]
#### Your LeetCode username
OhAanika

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
When it states ***period of 30 days ending 2019-07-27 inclusively***, I assume this means 30 days starting from "2019-06-28" and ending on "2019-07-27" (inclusive).

However, when I include any test case with an `activity_date` after "2019-07-27" (e.g. "2019-07-29"), the expected result *includes* these dates when it should not. My output excludes these dates.

So I propose:
1. Adding a test case with an `activity_date` after "2019-07-27"
2. Correcting the solution to exclude any `activity_date` after "2019-07-27"

#### Code you used for Submit/Run operation

My first solution:
```mySQL
SELECT 
    activity_date AS day, 
    COUNT(DISTINCT user_id) AS active_users
FROM Activity
WHERE DATEDIFF(CAST("2019-07-27" AS DATE), activity_date) BETWEEN 0 AND 29
GROUP BY activity_date
```

Another variation:
```mySQL
SELECT
    activity_date AS day,
    COUNT(DISTINCT user_id) AS active_users
FROM Activity
WHERE activity_date BETWEEN DATE_ADD(CAST("2019-07-27" AS DATE), INTERVAL -29 DAY) AND CAST("2019-07-27" AS DATE)
GROUP BY activity_date
```

#### Language used for code
MySQL

#### Expected behavior
Here's an example test case with dates after "2019-07-27":

```
{
    "headers":{
        "Activity":[
            "user_id","session_id","activity_date","activity_type"
        ]
    },
    "rows":{
        "Activity":[
            [2,4,"2019-07-21","send_message"],
            [2,4,"2019-07-21","end_session"],
            [3,2,"2019-07-27","open_session"],
            [3,2,"2019-07-28","send_message"],
            [3,2,"2019-07-29","end_session"],
            [4,3,"2019-06-25","open_session"],
            [4,3,"2019-06-25","end_session"]
        ]
    }
}
```

The dates "2019-07-28" and "2019-07-29" should not appear in the output, but your solution currently includes these dates:

```
{
    "headers": ["day", "active_users"], 
    "values": [
        ["2019-07-20", 2],
        ["2019-07-21", 1],
        ["2019-07-27", 1],
        ["2019-07-28", 1], 
        ["2019-07-29", 1]
    ]
}
```

My solution excludes these dates:

```
{
    "headers": ["day", "active_users"], 
    "values": [
        ["2019-07-20", 2],
        ["2019-07-21", 1], 
        ["2019-07-27", 1]
    ]
}
```

#### Additional context
https://leetcode.com/problems/user-activity-for-the-past-30-days-i/discuss/1955241/date-conditions-not-checked-correctly

**Comment by LC-Yani** [comment]
Hi @ohaanika 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
