### ISSUE TITLE
Flag not displayed correctly on LeetCode US contest rankings for international contestants from LeetCode CN

### ISSUE THREAD

**Issue by tonghuikang** [LeetCode-Feedback/LeetCode-Feedback#7025]
#### Your LeetCode username
tonghuikang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Flag on LeetCode US contest ranking page is not displaying correctly for international contestants from LeetCode CN.

#### Screenshots

If you open this page https://leetcode.com/contest/weekly-contest-289/ranking/3/ and search my username, you see that the flag is not displaying correctly for my country (Singapore).

![Screen Shot 2022-04-16 at 23 09 38 ](https://user-images.githubusercontent.com/17105577/163702979-c2ae6806-76fa-4ad6-9932-6b049c000056.png)

#### Additional context

I think this has been around for quite a while.

**Comment by LC-Yani** [comment]
Hi @tonghuikang 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Will be non-issue on LCUS for new contest page unless we want to map country name to country code (which we do not do currently) We appreciate your support!
