### ISSUE TITLE
第1115题. 交替打印 FooBar，给出正确的方案，但是提交后超时了,想了解调用程序是什么样的

### ISSUE THREAD

**Issue by fengbinliang** [LeetCode-Feedback/LeetCode-Feedback#7026]
**你的 LeetCode 用户名**
It's my life

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [java ] 编程语言
- [ ] 缺少测试用例

**描述**
思考了很久，感觉程序没有问题，但是提交之后就出现超时了。我在自己idea中也模拟了线程的调用，没发现有什么问题。
其实哲哲写法就是模拟的信号量，使用信号量都没超时，我这个为啥超时了呢？
所以我想知道leetcode中的调用程序是什么样的，希望能给我一份，谢谢同学

**你使用的语言**
java

**你提交或者运行的代码**
```
class FooBar { private int n;

volatile int one = 1;
volatile int two = 0;

public FooBar(int n) {
    this.n = n;
}

public void foo(Runnable printFoo) throws InterruptedException {
    
    for (int i = 0; i < n; i++) {
        while(one != 1){

        }
    	printFoo.run();
        one = 0;
        two = 1;
    }
}

public void bar(Runnable printBar) throws InterruptedException {
    
    for (int i = 0; i < n; i++) {
        while(two != 1){

        }
    	printBar.run();
        two = 0;
        one = 1;
    }
}
}
```

**期望行为**
希望给我一份调用程序的代码，我想知道程序到底是哪里出了问题。谢谢同学

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，经过与开发团队的多次确认，我们不方便透露实现细节。
本次 Ticket 将关闭，感谢您的反馈和支持。
