### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by ELK4N4** [LeetCode-Feedback/LeetCode-Feedback#7027]
#### Your LeetCode username

user3948T

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I wrote a recursive solution to the problem. However when I click on "submit" it writes me that there is an unresolved edge case. Conversely, if I click on "Run Code" it does resolve the edge case.

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * function ListNode(val, next) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.next = (next===undefined ? null : next)
 * }
 */
/**
 * @param {ListNode} l1
 * @param {ListNode} l2
 * @return {ListNode}
 */
let count = 0;
var addTwoNumbers = function(l1, l2) {
    let val1 = l1?.val || 0;
    let val2 = l2?.val || 0;
    let sum = val1 + val2 + count;
    count = 0;  
    if(sum > 9) {
        count++;
        sum = sum - 10;
    }
    l1 = l1?.next;
    l2 = l2?.next;
    if(l1 || l2) {
        return new ListNode(sum, addTwoNumbers(l1, l2));
    } else {
        if(count) {
            return new ListNode(sum, new ListNode(count));
        } else {
            return new ListNode(sum);
        }
    }
}
```

#### Language used for code

JavaScript

#### Expected behavior

Expected to get "Accepted Answer" in "Submit" like I got in "Run Code". However, it shows "Wrong Answer" in "Submit" and "Accepted Answer" in "Run Code".
The eage case is -
Input:
[0]
[1]

#### Screenshots

![image](https://user-images.githubusercontent.com/55286058/163708176-3fbb42c4-63c0-487e-bdce-6689f0701fbd.png)

#### Additional context

**Comment by LC-Yani** [comment]
Hi ELK4N4,

Thank you for reaching out to us, the judger appears to be working correctly, The code that you provide works on Java instead of Javascript.

![Screen Shot 2022-04-19 at 9 12 58 PM](https://user-images.githubusercontent.com/103138242/164127204-a4bba861-403e-4488-bc8f-646d60472177.png)
![Screen Shot 2022-04-19 at 9 14 22 PM](https://user-images.githubusercontent.com/103138242/164127334-495d6244-1bc7-4d87-a1ee-35f583320fc4.png)
