### ISSUE TITLE
Missing testcase for 897. Increasing Order Search Tree

### ISSUE THREAD

**Issue by SvetlinZarev** [LeetCode-Feedback/LeetCode-Feedback#7028]
#### Your LeetCode username

svetlin_zarev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I was able to pass all tests on [897. Increasing Order Search Tree](https://leetcode.com/problems/increasing-order-search-tree/) with an incorrect solution. 

There is no test case for a tree that looks like the one from the test-case input:
```text
[50,30,60,null,40,null,80,35,45]
```
![Screenshot from 2022-04-17 12-10-58](https://user-images.githubusercontent.com/1794797/163708188-a38ec200-41c8-413c-9343-3869d5b2d19b.png)

#### Code you used for Submit/Run operation

```rust
use std::rc::Rc;
use std::cell::RefCell;
impl Solution {
    pub fn increasing_bst(root: Option<Rc<RefCell<TreeNode>>>) -> Option<Rc<RefCell<TreeNode>>> {
        increasing_bst(root)
    }
}

pub fn increasing_bst(root: Option<Rc<RefCell<TreeNode>>>) -> Option<Rc<RefCell<TreeNode>>> {
    let mut stack = vec![];
    let mut buffer = root;

    while let Some(next) = buffer {
        buffer = next.borrow_mut().left.take();
        stack.push(next);
    }

    let (head, mut tail) = match stack.pop() {
        None => return None,
        Some(head) => {
            if let Some(right) = head.borrow_mut().right.take() {
                stack.push(right);
            }

            let tail = head.clone();
            (Some(head), tail)
        }
    };

    while let Some(next) = stack.pop() {
        tail.borrow_mut().right = Some(next.clone());
        tail = next;

        buffer = tail.borrow_mut().right.take();
        while let Some(node) = buffer {
            buffer = node.borrow_mut().left.take();
            stack.push(node);
        }
    }

    head
}
```

#### Language used for code
RUST 🦀

#### Expected behavior
The provided solution should have been rejected because it fails the provided testcase

**Comment by LC-Yani** [comment]
Hi @SvetlinZarev 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
