### ISSUE TITLE
523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#703]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Approach 1: Brute Force [Time Limit Exceeded] has incorrect description.

#### Code you used for Submit/Run operation

```
public class Solution {
    public boolean checkSubarraySum(int[] nums, int k) {

        for (int start = 0; start < nums.length - 1; start++) {
            for (int end = start + 1; end < nums.length; end++) {
                int sum = 0;
                for (int i = start; i <= end; i++)
                    sum += nums[i];
                if (sum == k || (k != 0 && sum % k == 0))
                    return true;
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

It doesn't TLE and submission is accepted.

#### Screenshots

<img width="402" alt="Capture" src="https://user-images.githubusercontent.com/7014697/88451193-a8c91780-ce09-11ea-84db-328da44ede60.PNG">

**Comment by lc-ivan** [comment]
Hi @agatagruza  ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @agatagruza ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by agatagruza** [comment]
Thank you @lc-ivan for your feedback. Glad could help.
