### ISSUE TITLE
Missing Test Case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by Latnove** [LeetCode-Feedback/LeetCode-Feedback#7031]
#### Your LeetCode username
Latnove

#### Category of the bug
- [ ] Question
- [x] `Solution`
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
My solution gives wrong answer

#### Code you used for Submit/Run operation

```
var isPalindrome = function (head) {
  for (let i = 0; i < head.length / 2; i++) {
    if (head[i] != head[head.length - 1 - i]) return false;
  }
  return true;
};
```

#### Language used for code
JavaScript

#### Expected behavior
The correct answer is given in the editor with array [1,2] - false. And when I upload the code to the platform it changes from false to true

#### Screenshots
https://ibb.co/XJjdPYC
https://ibb.co/0j2JZdd
https://ibb.co/TTrV3rh

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
