### ISSUE TITLE
Issue with testcase output after submitting

### ISSUE THREAD

**Issue by faizanalam1620** [LeetCode-Feedback/LeetCode-Feedback#7032]
Different behaviour of output at 'run testcase' and after submitting the code for same input.

#### Your LeetCode username
faizanalam1620

#### Category of the bug
- [ ] Question

#### Description of the bug
For 897. Increasing Order Search Tree, The code I have written working fine when running with 'run testcase' for input [5,1,7], but after submitting, output is different and my code is not accepted for the same testcase 

#### Code you used for Submit/Run operation
```
class Solution:
    lst = []
    def inOrder(self,root:TreeNode):
        if(root==None):
            return
        self.inOrder(root.left)
        self.lst.append(root.val)
        self.inOrder(root.right)
    def increasingBST(self, root: TreeNode) -> TreeNode:
        self.inOrder(root)
        head = TreeNode(self.lst[0])
        temp = head
        for i in range(1,len(self.lst)):
            print(temp.right)
            temp.right = TreeNode(self.lst[i])
            temp = temp.right
        
        return head 
        

```

#### Language used for code
Python

#### Expected behavior
I was expecting to return output as [1,null,5,null,7] for testcase input [5,1,7], but it's giving output [1,null,2,null,3,null,4,null,5,null,6,null,7,null,8,null,9,null,1,null,5,null,7], for same testcase after submitting.
Before submitting, running with 'run testcase' for same input is working fine.

#### Screenshots

![Screenshot from 2022-04-17 22-53-12](https://user-images.githubusercontent.com/87440274/163725939-378641cb-6a03-4cc1-a7a6-751c
![Screenshot from 2022-04-17 22-53-38](https://user-images.githubusercontent.com/87440274/163725945-e782d200-9a6e-4aec-b246-f8f534512acc.png)
71692d3d.png)

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
