### ISSUE TITLE
122. 买卖股票的最佳时机 II 示例 1翻译缺失。

### ISSUE THREAD

**Issue by gopherhiro** [LeetCode-Feedback/LeetCode-Feedback#7035]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目

**描述**
122. 买卖股票的最佳时机 II--示例 1--翻译缺失。

**期望行为**
补全【示例 1】缺失部分。

**屏幕截图**
![image](https://user-images.githubusercontent.com/65383410/163757288-5b0d45ac-b6b0-4414-a80e-177e214ed1fb.png)
![image](https://user-images.githubusercontent.com/65383410/163757335-669a6568-77d7-41c2-9349-310888b215bd.png)
![image](https://user-images.githubusercontent.com/65383410/163757427-4e003368-886f-4ca7-80ae-4dd3473e93a1.png)

**Comment by feiceh** [comment]
你好，当前该题翻译已更新，请留言告知一下力扣中文网站的 ID，我们给予积分奖励哦。

**Comment by gopherhiro** [comment]
> 你好，当前该题翻译已更新，请留言告知一下力扣中文网站的 ID，我们给予积分奖励哦。

力扣中文网站的 ID ：gopherhiro

好的，感谢。

**Comment by feiceh** [comment]
客气撒，ID：gopherhiro 给予积分奖励，请查收。
