### ISSUE TITLE
606. 根据二叉树创建字符串-示例1-描述错误

### ISSUE THREAD

**Issue by gopherhiro** [LeetCode-Feedback/LeetCode-Feedback#7036]
中文版力扣ID：gopherhiro

606. 根据二叉树创建字符串-示例1-描述错误（缺失）

![image](https://user-images.githubusercontent.com/65383410/163789296-02040fe6-08ba-4b2f-b6fa-847aebf28daa.png)
![image](https://user-images.githubusercontent.com/65383410/163789418-0f568672-815c-4cd0-b15c-981f9609382f.png)

**Comment by gopherhiro** [comment]
中文版力扣ID：gopherhiro

**Comment by feiceh** [comment]
你好，当前题目描述已更新，ID：gopherhiro 给予积分奖励，请查收。
