### ISSUE TITLE
2236. Root Equals Sum of Children

### ISSUE THREAD

**Issue by lewishoty** [LeetCode-Feedback/LeetCode-Feedback#7038]
#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

submit solution is wrong, but run code solution is correct. refer screenshot

#### Code you used for Submit/Run operation

```
let sum = 0

var checkTree = function(root) {
    
    let original = new TreeNode()
    original = root
    
    recursion(root,original)
    if (sum==root.val){return true}else{return false}
    
};

let recursion = function(root,original){
    if(!root){
        return
    }
    
    if(root!=original){
        sum += root.val
    }
    
    recursion(root.left,original)
    recursion(root.right,original)
}
```

#### Language used for code

Javascript

#### Expected behavior

'Run Code' should be accepted

#### Screenshots

<img width="1673" alt="Screenshot 2022-04-18 at 9 05 58 PM" src="https://user-images.githubusercontent.com/52281864/163812543-9eb4a177-84cc-4b77-9037-a6c946ecc2f2.png">

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
