### ISSUE TITLE
Question - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by MingjunMa** [LeetCode-Feedback/LeetCode-Feedback#7039]
#### Your LeetCode username
 LeetCode ID: MingjunMa

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The constraints of nodes in the tree is in the range [1, 10^4]. But a test case has the input [0, -1] , maybe the values of input are not suit for the constraints.

#### Language used for code
Java

**Comment by LC-Yani** [comment]
Hi @MingjunMa ,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The test case that you use

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by MingjunMa** [comment]
Hi, @LC-Yani 

The language is **Java** and the code is the following:

```
class Solution {
    public boolean isValidBST(TreeNode root) {
        return isValidBST(root, Long.MIN_VALUE, Long.MAX_VALUE);
    }
    
    public boolean isValidBST(TreeNode root, long min, long max) {
        if(root==null){return true;}
        if(root.val<=min || root.val>=max){return false;}
        return isValidBST(root.left, min, root.val)&&isValidBST(root.right, root.val, max);
    }
}
```

The test case is [0, -1] which given by leetcode test cases, I just think the test case is not good. Because the negative number is out of the range [1, 10^4].

Thank you for your reply!

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test case is correct.The constraint of [1, 10^4] is of the number of nodes and not the values of the nodes.The values of the nodes can be any integer value. We appreciate your support!
