### ISSUE TITLE
91. Decode Ways

### ISSUE THREAD

**Issue by seth-orai** [LeetCode-Feedback/LeetCode-Feedback#704]
#### Your LeetCode username
seth-orai

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Invalid test cases such as "3a.1" should not be accepted, given the constraints of the question.

#### Code you used for Submit/Run operation

```
int numDecodings(string s) {
        int n = s.size(), i, prev, curr;
        
        if(n==1 && s[0]!='0')
            return 1;
        if(s[0]=='0')
            return 0;
        
        vector<int> dp(n,0);
        
        dp[0] = 1;
        
        if(s[1]=='0'){
            if(s[0]>'2')
                return 0;
            dp[1] = dp[0];
        }
        else if((s[0]-'0'==1) || (s[0]-'0'==2 && s[1]>='1' && s[1]<'7'))
            dp[1] = 1+dp[0];
        else dp[1] = 1;
        
        for(i=2; i<n; i++){
            prev = s[i-1]-'0';
            curr = s[i]-'0';
            
            if(curr!=0)
                dp[i] = dp[i-1];
            
            if((prev==1) || (prev==2 && curr>=0 && curr<7))
                dp[i] += dp[i-2];
        }
        
        return dp[n-1];
    }
```

#### Language used for code

C++

#### Expected behavior

Invalid test cases such as "3a.1" should not be accepted.

#### Screenshots

![Invalid Test Case](https://user-images.githubusercontent.com/52034084/88452690-70afec00-ce7e-11ea-8c98-cbef2c3aa94a.JPG)

**Comment by lc-ivan** [comment]
Hi @seth-orai ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @seth-orai ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
