### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by MAthabet** [LeetCode-Feedback/LeetCode-Feedback#7040]
MAthabet

#### Category of the bug
- [x] Missing Test Cases 

the question description says  "without using multiplication, division, and mod operator." but accepts any solution

#### Code you used for Submit/Run operation
```
class Solution {
    public int divide(int d, int v) {
        if (d == Integer.MIN_VALUE && v == -1) return Integer.MAX_VALUE;
         return d/v;
    }
}
```

#### Language used for code
Java

#### Expected behavior
i expected to not accept my submission

#### Screenshots
![image](https://user-images.githubusercontent.com/92416406/163826722-2bf691fe-2cf6-464b-a20e-4bcf14025132.png)

**Comment by LC-Yani** [comment]
Hi @MAthabet 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
