### ISSUE TITLE
1587. Bank Account Summary II | Incorrect acceptance

### ISSUE THREAD

**Issue by GowthamGuttula** [LeetCode-Feedback/LeetCode-Feedback#7041]
#### Category of the bug
- [ 1587. Bank Account Summary II | Incorrect acceptance] Question
- [select name, sum(amount) balance from users u, transactions t where u.account = t.account group by name having sum(amount)>10000 ] Solution
- [ Oracle-sql] Language
- [ {"headers": {"Users": ["account", "name"], "Transactions": ["trans_id", "account", "amount", "transacted_on"]}, "rows": {"Users": [[900001, "Alice"], [900002, "Bob"], [900003, "Charlie"],[900004, "Alice"]], "Transactions": [[1, 900001, 7000, "2020-08-01"], [2, 900001, 7000, "2020-09-01"], [3, 900001, -3000, "2020-09-02"], [4, 900002, 1000, "2020-09-12"], [5, 900003, 6000, "2020-08-07"], [6, 900003, 6000, "2020-09-07"], [7, 900003, -4000, "2020-09-11"],[8, 900004, 12000, "2020-09-11"]]}}] Missing Test Cases 

#### Description of the bug

Account in table is primary key and not name. Similar name can be for multiple account. So grouping of results should be based on Account and not name only

#### Code you used for Submit/Run operation

```
select name, sum(amount) balance from users u, transactions t where u.account = t.account group by name,u.account having sum(amount)>10000
```

#### Language used for code

Oracle-sql

#### Expected behavior

{"headers": ["NAME", "BALANCE"], "values": [["Alice", 11000], ["Alice", 12000]]} because there are two different accounts for same name and account is primary key and not name, so it should print twic

**Comment by LC-Yani** [comment]
Hi @GowthamGuttula 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Yani** [comment]
We got your code. I've submitted this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've reported your feedback to update the problem, but it gonna takes time to update. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
