### ISSUE TITLE
confused in question 38

### ISSUE THREAD

**Issue by Pranav108** [LeetCode-Feedback/LeetCode-Feedback#7042]
#### Your LeetCode username
[BEN__10](https://leetcode.com/BEN__10/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

[38. Count and Say](https://leetcode.com/problems/count-and-say/)
In the problem statement it is said that `split it into the minimal number of groups so that each group is a contiguous section all of the same character` . This can be done in best way if we sort the string after one `say` operation (because sorting will grouped the same number together and we will get minimal groups), but I think we don't have to do this here, right?.  
So in this case ,extending the 2nd test case to one more `say` operation will be very helpful . How we are performing `say` operation on "1211" string can clarify this confusion. 

```
countAndSay(1) = "1"
countAndSay(2) = say "1" = one 1 = "11"
countAndSay(3) = say "11" = two 1's = "21"
countAndSay(4) = say "21" = one 2 + one 1 = "12" + "11" = "1211"
countAndSay(5) = say "1211" = one 1 + one 2 + two 1 = "11" + "12" + "21" = "1211"
countAndSay(5) ≠ say "1112" = three 1 = "31" = "31" (Because after sorting "1211" becomes "1112")
```
This is just to explain you which sorting I am talking about.

**Comment by LC-Yani** [comment]
Hi @Pranav108 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by LC-Pam** [comment]
Would you mind providing us your username?
Thank you.

**Comment by Pranav108** [comment]
> Would you mind providing us your username? Thank you.
@LC-Pam 
[BEN__10](https://leetcode.com/BEN__10/)
This is my new profile link. 
Thanks for the reward, I will keep contributing 🤩.

**Comment by LC-Pam** [comment]
Rewards Processed.
Thank you!
