### ISSUE TITLE
Missing testcase for 1870. Minimum Speed to Arrive on Time

### ISSUE THREAD

**Issue by SvetlinZarev** [LeetCode-Feedback/LeetCode-Feedback#7043]
#### Your LeetCode username

svetlin_zarev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An incorrect solution passes the verification process because of a missing test case. The submission should have failed. 
The test-case is: 
```
[1,10000,2]
3
```

#### Code you used for Submit/Run operation

```rust
impl Solution {
    pub fn min_speed_on_time(dist: Vec<i32>, hour: f64) -> i32 {
        min_speed_on_time(dist, hour)
    }
}
use std::ops::Sub;

const NO_SOLUTION: i32 = -1;

pub fn min_speed_on_time(dist: Vec<i32>, hour: f64) -> i32 {
    assert!(dist.len() > 0);
    assert!(hour > 0.0);

    // Because each train starts at an exact hour, it's not possible to reach the target
    // if there are more trains than hours. The exception is the last train, because we do
    // not perform the "ceil()` operation on it.
    if hour <= dist.len().sub(1) as f64 {
        return NO_SOLUTION;
    }

    let mut lo = 1;
    let mut hi = dist[dist.len() - 1] * 100;

    while lo < hi {
        let speed = lo + (hi - lo) / 2;
        let arrival = time(&dist, speed);

        if arrival > hour {
            lo = speed + 1;
        } else {
            hi = speed;
        }
    }

    hi
}

fn time(dist: &[i32], speed: i32) -> f64 {
    let t: i32 = dist
        .iter()
        .take(dist.len() - 1)
        .copied()
        .map(|x| x / speed + (x % speed != 0) as i32)
        .sum();

    t as f64 + dist[dist.len() - 1] as f64 / speed as f64
}
```

#### Language used for code
RUST

#### Expected behavior

The submission should have failed the following test case: 
```
[1,10000,2]
3
```

![Screenshot from 2022-04-19 00-31-40](https://user-images.githubusercontent.com/1794797/163881178-599816cc-3117-4e95-b2c6-921210d66634.png)

#### Additional context

Link to the successful submission: https://leetcode.com/submissions/detail/683050682/

**Comment by LC-Yani** [comment]
Hi @SvetlinZarev 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
