### ISSUE TITLE
242. Valid Anagram: solution mentions "hash table" but no hash table is used

### ISSUE THREAD

**Issue by lcapitulino** [LeetCode-Feedback/LeetCode-Feedback#7044]
#### Your LeetCode username
mrnanook

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Approach 2 summary reads "Approach #2 (Hash Table) [Accepted]". However, the described solution doesn't use a hash table. It uses an array as a counter. I believe it should read "Approach #2 (Array)".

**Comment by LC-Yani** [comment]
Hi @lcapitulino 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
