### ISSUE TITLE
Dead Link on Recursion 2: Divide and Conquer card

### ISSUE THREAD

**Issue by govi20** [LeetCode-Feedback/LeetCode-Feedback#7048]
On Recursion 2 card (https://leetcode.com/explore/learn/card/recursion-ii/470/divide-and-conquer/2869/), **step-by-step solution** hyperlink is present but seems the link is dead.

Refer to the below text which I've copied from Leetcode portal:

Following this article you can [try solving this exercise](https://leetcode.com/explore/learn/card/recursion-ii/470/divide-and-conquer/2874/) by yourself. We also provide a [step-by-step solution](https://leetcode.com/explore/learn/card/recursion-ii/470/divide-and-conquer/2875/) if you are still stuck following the exercise.

**Comment by LC-Yani** [comment]
Hi @govi20 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
