### ISSUE TITLE
题目与答案吧不符

### ISSUE THREAD

**Issue by dongbinyang** [LeetCode-Feedback/LeetCode-Feedback#7050]
**bridgehahaha**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ https://leetcode-cn.com/problems/maximum-score-of-a-node-sequence/] 题目
- [29] 题解
- [java] 编程语言
- [5,2,9,8,10]
   [[0,1],[1,2],[2,3],[0,2],[1,3],[2,4]]
   缺少测试用例

**描述**
29 但是序列 [0,3,2,4] 不是合法的，因为没有边连接节点 0 和 3,答案应该是24

**Comment by feiceh** [comment]
感谢反馈，能否向我们补充题目信息，以及完善代码格式。可以参考[这个反馈](https://github.com/LeetCode-Feedback/LeetCode-Feedback/blob/master/.github/ISSUE_TEMPLATE/bug--------.md)，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
