### ISSUE TITLE
Missing Test Case - 388. Longest Absolute File Path

### ISSUE THREAD

**Issue by BjChacha** [LeetCode-Feedback/LeetCode-Feedback#7051]
#### Your LeetCode username

xxxxxshuai0

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing subdirectories between to entries. Such as:

`"a\n\t\tasd.txt"`

```
a
⟶ ⟶ asd.txt
```

and `"a\n\t\tasd.txt\n\tasda.txt"`

```
a
⟶ ⟶ asd.txt
⟶ asda.txt
```

The excepted results of `"a\n\t\tasd.txt"` and `"a\n\t\tasd.txt\n\tasda.txt"` are both `9`, while my passed code outputs `9` and `10` individually.

#### Code you used for Submit/Run operation

```
var lengthLongestPath = function(input) {
    let items = input.split('\n');
    let res = 0, cur = 0, q = [];
    
    const getLevel = function(s) {
        let cnt = 0, i = 0;
        while (i < s.length && s[i] === '\t') ++cnt, ++i;
        let isFile = s.indexOf('.') > 0 ? true : false;
        return [cnt, s.length - i, isFile];
    }
    
    for (let item of items) {
        let [lvl, len, isFile] = getLevel(item);
        if (q.length === 0) {
            q.push(len);
            cur = len;
        } else {
            if (lvl == q.length - 1) {
                cur = cur - q[q.length-1] + len;
                q[q.length-1] = len;
            } else if (lvl > q.length - 1) {
                q.push(len);
                cur += len;
            } else {
                while (q.length - 1 > lvl) {
                    cur -= q.pop();
                }
                cur = cur - q[q.length-1] + len;
                q[q.length-1] = len;
            }
        }
        if (isFile) res = Math.max(res, cur + q.length - 1);
    }
    return res;
};
```

#### Language used for code

Javascript

#### Expected behavior

I don't know the correct answer. Maybe the illegal testcase should not be passed.

**Comment by LC-Yani** [comment]
Hi @BjChacha 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. (updated the problem statement and validator ) We appreciate your support!
