### ISSUE TITLE
Missing Test Case for 250. Count Univalue Subtrees

### ISSUE THREAD

**Issue by galethegreat** [LeetCode-Feedback/LeetCode-Feedback#7054]
#### Your LeetCode username

galethegreat

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a missing test case for example:  [1,1,0,0,0,null,0]
This is going to catch if the user in python did their conditional checks lazily.
If the user checked if the condition is None by doing this:
```if condition``` instead of ```if condition is not None```  

#### Code you used for Submit/Run operation

The following code passes all the test cases: https://leetcode.com/submissions/detail/684016112/
```
class Solution:
    
    def __init__(self):
        self.count = 0
    def countUnivalSubtrees(self, root: Optional[TreeNode]) -> int:
        
        def dfs(root):
            
            if not root:
                return None
            
            left = dfs(root.left)
            right = dfs(root.right)
            
            if left is None and right is None:
                self.count += 1
                return root.val 
            
            if not left and right: left = right #BAD LINE 
            if not right and left: right = left #BAD LINE
                
            if left == right == root.val:
                self.count += 1
                return root.val
            
            else:
                return 'X'
            
        if not root: 
            return 0
        
        dfs(root)
        
        return self.count
```

#### Language used for code

python3

#### Expected behavior

We should NOT be able to pass all the test cases, we should add one more:
[1,1,0,0,0,null,0]

after we change the code in the lines I marked as #BAD LINE
```
if left is None and right is not None: left = right
if right is None and left is not None: right = left
```
we pass the extra test case I am suggesting and all the previous cases

#### Screenshots

Original Code 
![image](https://user-images.githubusercontent.com/24823487/164184410-138595de-e50b-4153-a912-964d769e9b25.png)

Changed Code
![image](https://user-images.githubusercontent.com/24823487/164184797-5d67695b-f1ff-48c7-9289-bdfb331946e1.png)

**Comment by LC-Yani** [comment]
Hi @galethegreat 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
