### ISSUE TITLE
Tiny mistake in the Dynamic Explore Card

### ISSUE THREAD

**Issue by MineSelf2016** [LeetCode-Feedback/LeetCode-Feedback#7056]
https://leetcode.com/explore/learn/card/dynamic-programming/631/strategy-for-solving-dp-problems/4048/

The last question in the Chapter 2 quize of the Dynamic Programming Explore Card should be a "Single Choice Question", not a "Multiple Choice Question".

**Comment by LC-Yani** [comment]
Hi @MineSelf2016 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
The problem says "Multiple Choice Question" because there are multiple choices, but that doesn't mean there are "Multiple Answers", the interface only allows you to select one answer anyways as indicated by the radio buttons.
We appreciate your support!
