### ISSUE TITLE
584. Find Customer Referee | Incorrect Description

### ISSUE THREAD

**Issue by arin17bishwa** [LeetCode-Feedback/LeetCode-Feedback#7058]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question description asks to return the IDs of the required people, but returning(SELECT-ing) the IDs gives WA.
But returning the names of the required people gives AC.

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
SELECT name from Customer 
where referee_id<>2 or referee_id is NULL;
```

#### Expected behavior

The code I submitted should have originally given WA, but gave AC instead.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
