### ISSUE TITLE
207. Course Schedule

### ISSUE THREAD

**Issue by wuxxx725** [LeetCode-Feedback/LeetCode-Feedback#7059]
#### Your LeetCode username

meng-hsuan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

For certain test cases with high values of `numCourses` (around 30000 or higher), the Run Code Result tab did not show any status (such as "Accepted" or "Wrong Answer"), but only the runtime.  And for even higher values of `numCourses` (near the 100000 limit), the expected output failed to be produced.

#### Code you used for Submit/Run operation

```
class Solution:
    def canFinish(self, numCourses: int, prerequisites: List[List[int]]) -> bool:
        pr = len(prerequisites)
        edges = dict()
        nchd = collections.defaultdict(int)
        leaves = collections.deque()
        for i in range(pr):
            if not edges.get(prerequisites[i][1]):
                edges[prerequisites[i][1]] = [prerequisites[i][0]]
            else:
                edges[prerequisites[i][1]] += [prerequisites[i][0]]
            nchd[prerequisites[i][0]] += 1
            nchd[prerequisites[i][1]] += 0
        
        for i in nchd:
            if nchd[i] == 0:
                leaves.append(i)
        
        while len(leaves) > 0:
            #print(f"popping leaf {leaves[0]}")
            for i in edges[leaves[0]]:
                #print(f" removing edge ({leaves[0]}, {i})")
                nchd[i] -= 1
                if nchd[i] == 0 and edges.get(i):
                    leaves.append(i)
                    #print(f" addning leaf {leaves[0]}")
            edges.pop(leaves[0])
            leaves.popleft()
        
        #print(edges)
        #print(nchd)
        #print(leaves)
        
        return len(edges) == 0
```

#### Language used for code

Python3

#### Expected behavior

For both test cases below, the correct outputs are `true`, and the status of my code would have been "Accepted" for both cases.
```
30000
[[0,1],[0,2],[1,2]]
```
```
99999
[[0,1],[0,2],[1,2]]
```

#### Screenshots

<img width="892" alt="Screen Shot 2022-04-20 at 3 44 37 PM" src="https://user-images.githubusercontent.com/67871581/164319662-f11dbe9f-2f2a-4e0e-905f-c677cf6cd062.png">
<img width="891" alt="Screen Shot 2022-04-20 at 3 48 11 PM" src="https://user-images.githubusercontent.com/67871581/164320182-73e9962c-e8ba-4480-b7ec-7fe9444fd177.png">

#### Additional context

This bug does not always occur.  For example, when running the following two test cases at the same time, the status of my code is correctly shown as "Accepted".
```
30000
[[0,1],[0,2],[1,2]]
2
[[1,0]]
```

**Comment by LC-Yani** [comment]
Hi @wuxxx725 

Thank you for reaching out to us. The first testcase is working on our side. But second not, I've relayed this issue to our team to investigate
![Screen Shot 2022-04-20 at 8 30 22 PM](https://user-images.githubusercontent.com/103138242/164346343-8d42752a-5cd0-413a-b7d1-ddeabf6103b7.png)
.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. (Updated the constraint of numCourses from 10^5 to 2000.) We appreciate your support!
