### ISSUE TITLE
Missing Test case in problem 139 Word Break

### ISSUE THREAD

**Issue by Kartik33** [LeetCode-Feedback/LeetCode-Feedback#706]
LeetCode username: kartiktushir33

My submission passed because of the missing test case. 
My solution assumes that if we are going right down the right path then we will not have the same sub-problem again.
For example : "catsandogcat"
["cats", "dog", "sand", "and", "cat","an"]
The right path for this problem is cats->an->dog->cat
In the code: I will first find cat in the wordDict and cat is not also in the hashmap, as cat will not lead us to the solution it will save it in the hashmap value = False. Now when 2nd cat is encountered, it will check it in the hashmap and return false and hence the answer will be False which is wrong.

I know it is not a very good explanation therefore you can find my code in the attached screenshot, also feel free to contact me on kartiktushir33@gmail.com.

![Screenshot from 2020-07-25 14-01-37](https://user-images.githubusercontent.com/8198703/88464338-63dfc800-ce7f-11ea-822f-9e561cdb2849.png)

Thanks.
Kartik

**Comment by lc-pam** [comment]
Hi @Kartik33 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @Kartik33 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
