### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by mcunkelman** [LeetCode-Feedback/LeetCode-Feedback#7060]
#### Your LeetCode username
mcunkelman

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

The peak description is rather vague and I tried to add several custom test cases that are not excluded by the written statement but were deemed invalid. These cases would invalidate the use of binary search but seem valid to me. The test cases are as follows:
[1,1,1,1,1,1,1,1,6,1,1,1]
[1,1,6,1,1,1,1,1,1,1,1,1]

These provided test cases have repeating values and adjacent values that differ by more than 1 so these test cases seem valid. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
python3

#### Expected behavior

These test cases were rejected as invalid but seem to meet the problem statement, non-negative integers at all positions

**Comment by LC-Yani** [comment]
Hi @mcunkelman ,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by mcunkelman** [comment]
Yes, it's still incomplete as I thought up these test cases and was unsure how to solve them with Binary Search. I am not sure if I am misunderstanding the question being asked or if these are valid test cases. 

'''class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        left, right = 0, len(nums) - 1
        while left <= right:
            mid = (left + right) // 2
            midU = mid + 1
            midD = mid - 1
            if nums[mid] > nums[midU] and nums[mid] > nums[midD]:
                return mid
            elif nums[midD] > nums[midU]:
                right = midD
            elif nums[midU] > nums[midD]:
                left = midU
            elif nums[left] > nums[right]:
                right = midD
            elif nums[right] > nums[left]:
                left = midU
            elif nums[left] > nums[midD]:
                right = midD
            elif nums[right] > nums[midU]:
                left = midU
            else:
                for i in nums:
                    if nums[i] > nums[i-1] and nums[i] > nums[i + 1]:
                        return i
                    else:
                        continue
                '''

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
I list some solutions below, please feel free to check it:
https://leetcode.com/problems/find-peak-element/discuss/505362/Python3-both-linear-and-logarithmic-solutions[
https://leetcode.com/problems/find-peak-element/discuss/1555561/Python3-or-EASY-or-Binary-Search-Solution-or-Explained[
https://leetcode.com/problems/find-peak-element/discuss/737395/Python3%3A-Easy-to-read-Binary-Search-with-explanation[
https://leetcode.com/problems/find-peak-element/discuss/724744/Python3-binary-search
