### ISSUE TITLE
Missing Test Case - 1200. Minimum Absolute Difference

### ISSUE THREAD

**Issue by mrcarlosdigan** [LeetCode-Feedback/LeetCode-Feedback#7061]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug

Missing test case: [0, 1, 3]

#### Code you used for Submit/Run operation

```
        minNumber = float("inf")
        maxNumber = float("-inf")
        minAbsDiff = float("inf")
        
        
        
        for num in arr:
            minNumber = min(minNumber, num)
            maxNumber = max(maxNumber, num)
        
        sorted_arr = [0] * (maxNumber - minNumber + 1)
        
        for num in arr:
            sorted_arr[num - minNumber] = num
        
        prevNum = None
        
        result = []
       
        for num in sorted_arr:
            if not num:
                continue
            if prevNum:
                if num - prevNum == minAbsDiff:
                    result.append([prevNum, num])
                elif num - prevNum < minAbsDiff:
                    result = [[prevNum, num]]
                    minAbsDiff = min(minAbsDiff, num - prevNum)
                   
            prevNum = num
        
        return result
```

#### Expected behavior

My counting sort algorithm passes all test cases when I submit, however when I test my code on the above custom test case, then it fails. 

#### Screenshots

![image](https://user-images.githubusercontent.com/93342111/164345546-2bdf6435-8a97-4e7e-a796-cd5d202d8012.png)
![image](https://user-images.githubusercontent.com/93342111/164345604-e209a8b1-7dfd-4a01-beb3-d488b034a5b2.png)

**Comment by LC-Yani** [comment]
Hi @mrcarlosdigan ,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The full code and language you submitted to reach this result.
Because when we submit your code, we received " error" instead of "Accepted"
Or you can send us the link of your "Accepted"

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by mrcarlosdigan** [comment]
Here is the link of my Accepted: https://leetcode.com/submissions/detail/684439026/

**Comment by LC-Yani** [comment]
Hi @mrcarlosdigan 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
