### ISSUE TITLE
Missing Test Case - 1470. Shuffle the Array

### ISSUE THREAD

**Issue by Khakimovbobur** [LeetCode-Feedback/LeetCode-Feedback#7063]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Khakimovbobur** [comment]
v

**Comment by LC-Yani** [comment]
Hi there,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

what is the missing test?

The code and language you submitted to reach this result.
