### ISSUE TITLE
Missing Test Case - 680. Valid Palindrome II

### ISSUE THREAD

**Issue by F0b0s** [LeetCode-Feedback/LeetCode-Feedback#7066]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Solution from below successfully pass submission, but have an error, test case to check it:
"gmlueuppuclmg"
Solution return true, but the right answer is false;

#### Code you used for Submit/Run operation

```
public class Solution {
    public bool ValidPalindrome(string s) {
        int left=0;
        int right=s.Length-1;
        bool checkRight=false;
        bool checkLeft=false;
        
        while(left<right)
        {
            if(s[left]==s[right])
            {
                left++;
                right--;
            }
            else if(checkRight==false)
            {
                right--;
                checkRight=true;
            }
            else if(checkRight==true && checkLeft==false)
            {
                right++;
                left++;
                checkLeft=true;
            }
            else
            {
                return false;
            }
        }
        return true;
    }
}
```

#### Language used for code

C#

#### Expected behavior
Solution should fail the submission.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
