### ISSUE TITLE
Error with Solution for Python on #150. Evaluate Reverse Polish Notation

### ISSUE THREAD

**Issue by sabr1na0** [LeetCode-Feedback/LeetCode-Feedback#7069]
#### Your LeetCode username
@sabr1na

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution given for python is incorrect and leads to a failed submission. I have displayed the correct fix for the solution below as well as displays for running with the current given solution.

#### Code you used for Submit/Run operation

```
//  #150. Evaluate Reverse Polish Notation
// (This is the code given as the solution for python in the article)
class Solution(object):
    def evalRPN(self, tokens):
        """
        :type tokens: List[str]
        :rtype: int
        """
        stack = []
   
        for token in tokens:
       
            if token not in "+-/*":
                stack.append(int(token))
                continue
    
            number_2 = stack.pop()
            number_1 = stack.pop()
        
            result = 0
            if token == "+":
                result = number_1 + number_2
            elif token == "-":
                result = number_1 - number_2
            elif token == "*":
                result = number_1 * number_2
            else:
                result = int(number_1 / float(number_2))
            
            stack.append(result)

        return stack.pop() 
```

#### Expected behavior

The given code fails with test case where
Input is:
["10","6","9","3","+","-11","*","/","*","17","+","5","+"]
Output:
12
The expected output is:
22

#### Screenshots

**Running with current given solution: (Fails on Submit)**
<img width="621" alt="IncorrectSolutionRun" src="https://user-images.githubusercontent.com/84553004/164529929-1808ed3a-9a77-4004-9b9b-0c658eac6c5a.png">
<img width="445" alt="IncorrectSolutionRunFailure" src="https://user-images.githubusercontent.com/84553004/164529930-1727db57-d23b-40a6-8034-1437ee4e9288.png">

**Solution for fix:
The solution given can be fixed by replacing the number_2 with float(number_2)**

**With running with this solution (which will need to be updated in the article given):**
<img width="935" alt="FixedSolutionRun" src="https://user-images.githubusercontent.com/84553004/164529925-4d919229-f515-49bb-868d-095a44de8584.png">
<img width="560" alt="FixedSolutionRunSuccess" src="https://user-images.githubusercontent.com/84553004/164529927-a8198eb1-6b9a-4d34-9ada-657bd786ca6a.png">
#### Additional context

This bug is particularly relevant because the optimized solution approach with python is the one with the error.

Solution for fix:
The solution given can be fixed by replacing the number_2 with Float(number_2) in the article and given code solution for this problem.

In article, code becomes:
```
result = int(number_1 / float(number_2))
```
instead of: 
```
result = int(number_1 / number_2)
```

**Comment by LC-Yani** [comment]
Testcase is invalid
["10","6","9","3","+","-11","","/","","17","+","5","+"]
invalid literal for int() with base 10: ''
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
