### ISSUE TITLE
1166. Design File System - Incorrect Expected Output

### ISSUE THREAD

**Issue by Ashit-Sood** [LeetCode-Feedback/LeetCode-Feedback#7070]
Problem: 1166. Design File System

Test Case failing:
["FileSystem","createPath","get"]
[[],["/",1],["/a"]]

Output: [null,false,-1] <- Correct
Expected: [null,true,-1] <- Incorrect

Please fix the issue.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Ashit-Sood** [comment]
As per the constraints of the problem, if I was to give the input as,
["FileSystem","createPath","get"]
[[],["/",1],["/a"]]

then the expected output is
[null,false,-1]

but the system expects the answer to be
[null,true,-1] <- this is incorrect.

Try the code below:
class FileSystem {
    Map<String, Integer> map;

    public FileSystem() {
        map = new HashMap();
    }
    
    public boolean createPath(String path, int value) {
        if (path.isEmpty() || path.equals("/") || map.containsKey(path)) return false;
        
        int last = path.lastIndexOf("/");
        String parent = path.substring(0, last);
        
        if(!parent.isEmpty() && !map.containsKey(parent)) return false;
        
        map.put(path, value);
        return true;
    }
    
    public int get(String path) {
        if (!map.containsKey(path)) return -1;
        return map.get(path);
    }
}

The output your system expects is
[null,true,-1]
which is not correct as per the constrains outlined in the problem

and deems my solution below as WRONG ANSWER even though it is correct.
[null,false,-1]

When I try to submit the same code, it successfully accepts the answer as correct answer though. You need to check why it is giving WRONG ANSWER when I try to check the test case individually.

Hopefully this helps!

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

**Comment by Ashit-Sood** [comment]
Language used is JAVA.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
