### ISSUE TITLE
802. 找到最终的安全状态-题目有歧义

### ISSUE THREAD

**Issue by everythingCanBeModeled** [LeetCode-Feedback/LeetCode-Feedback#7071]
**你的 LeetCode 用户名**
everythingCanBeModeled

**Bug 类型**
- [ ] 题目

**描述**
[802. 找到最终的安全状态](https://leetcode-cn.com/problems/find-eventual-safe-states/)
题目描述为：如果从该节点开始的所有可能路径都通向**一个**终端节点，则该节点为安全节点。
题目描述有歧义，可以理解为通向**同一个**终端节点，也可以理解为通向**任意**终端节点。

**期望行为**
应去掉“一个”，消除歧义。
即修改为：如果从该节点开始的所有可能路径都通向终端节点，则该节点为安全节点。

**屏幕截图**
![image](https://user-images.githubusercontent.com/75769380/164608482-7c6a3b92-b099-4f90-bb7c-d1790f75aaf5.png)

**Comment by feiceh** [comment]
你好，当前题目描述已更新，ID：everythingCanBeModeled 给予积分奖励，请查收。

**Comment by everythingCanBeModeled** [comment]
【自动回复】来信已收到，十分感谢！
