### ISSUE TITLE
Missing Test Case - 2247. Maximum Cost of Trip With K Highways

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7072]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [2247. Maximum Cost of Trip With K Highways](https://leetcode.com/problems/maximum-cost-of-trip-with-k-highways), a solution that can get accepted fails on a test case.

```
15
[[0,1,1],[1,2,1],[2,3,1],[3,4,1],[4,5,1],[5,6,1],[6,7,1],[7,8,1],[8,9,1],[9,10,1],[10,11,1],[11,12,1],[12,13,1],[13,14,1],[0,2,1],[1,3,1],[2,4,1],[3,5,1],[4,6,1],[5,7,1],[6,8,1],[7,9,1],[8,10,1],[9,11,1],[10,12,1],[11,13,1],[12,14,1],[0,3,1],[1,4,1],[2,5,1],[3,6,1],[4,7,1],[5,8,1],[6,9,1],[7,10,1],[8,11,1],[9,12,1],[10,13,1],[11,14,1],[0,4,1],[1,5,1],[2,6,1],[3,7,1],[4,8,1],[5,9,1],[6,10,1],[7,11,1],[8,12,1],[9,13,1],[10,14,1]]
14
```

#### Code you used for Submit/Run operation
```Python
class Solution:
    def maximumCost(self, n: int, highways: List[List[int]], k: int) -> int:
        if k > n: return -1
        web = [[] for _ in range(n)]

        for u, v, w in highways:
            web[u].append((v, w))
            web[v].append((u, w))
        
        def dfs(u, cost, cnt):
            nonlocal res
            if cnt == k:
                res = max(res, cost)
                return
            for v, w in web[u]:
                if v not in vis:
                    vis.add(v)
                    dfs(v, cost + w, cnt + 1)
                    vis.remove(v)
        
        res = -1
        for u in range(n):
            vis = {u}
            dfs(u, 0, 0)
        return res
```

#### Language used for code
Python3

#### Expected behavior
Add the test case mentioned in this issue so that the solution above will get TLE.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
