### ISSUE TITLE
Missing Test Case - 1901. Find a Peak Element II

### ISSUE THREAD

**Issue by yitxu** [LeetCode-Feedback/LeetCode-Feedback#7074]
#### Your LeetCode username

yxu712

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

missing a test case

#### Code you used for Submit/Run operation

```
missing test case: [[7,6],[2,5],[3,4],[1,2],[2,1]]
```
code that passes all the original test cases but will fail this additional test case. Refer to post: https://leetcode.com/problems/find-a-peak-element-ii/discuss/1969973/super-clean-column-binary-search/1361149

```
class Solution:
    def findPeak(self, values, col):
        l = 0
        r = len(values) - 1
        
        while l < r:
            mid = (l + r) // 2
            if values[mid][col] > values[mid + 1][col]:
                r = mid
            else:
                l = mid + 1
        return l
    
    def findPeakGrid(self, mat: List[List[int]]) -> List[int]:
        for col in range(len(mat[0])):     
            row_indx = self.findPeak(mat, col)

            if mat[row_indx][max(col - 1, 0)] <= mat[row_indx][col]:
                if mat[row_indx][min(col + 1, len(mat[0]) - 1)] <= mat[row_indx][col]:
                    return row_indx, col
            
        return -1, -1
```

#### Language used for code

python

#### Expected behavior

expected output:[0, 0]

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
