### ISSUE TITLE
Missing Test Case - 628. Maximum Product of Three Numbers

### ISSUE THREAD

**Issue by akshat2580** [LeetCode-Feedback/LeetCode-Feedback#7076]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int maximumProduct(vector<int>& v) {int n=v.size();
                                        sort(v.begin(),v.end());
        long long s=0;
                         if(v[0]*v[1]*v[n-1]>=v[n-3]*v[n-2]*v[n-1])
                          s=v[0]*v[1]*v[n-1];              
                          else
                              s=v[n-3]*v[n-2]*v[n-1];
                                        
                                        
                                        return s;
    }
};



#### Language used for code
<!-- C++ -->

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by shreyansh955jain** [comment]
can u please described in details i am first time working so i want to resolve test case.

**Comment by akshat2580** [comment]
Here in the problem it is given that the vector and we need to find the max product of 3,
so we just need to check if the largest no in the vector regardless of positive or negative.
that's why i took this approach--
first sort the vector/array,then 
I went and took the max between the product of 2 smallest negetive (in actual value) and largest positive no
& the product of three largest positive no.;
 try to dry run the code by yourself using an example.
Hope it, helps!
