### ISSUE TITLE
What is the problem in this program someone help!.. Find All Duplicates in an Array

### ISSUE THREAD

**Issue by DEEPAK42BATHIJA** [LeetCode-Feedback/LeetCode-Feedback#7077]
class Solution {
public:
    vector<int> findDuplicates(vector<int>& nums) {
       set<int> s;
        for(auto it: nums){
           if(s.count(nums[it])>0)
               s.insert(nums[it]);
       }
        return s;
    }
};

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The problem
The  language you submitted to reach this result.
The missing test case
