### ISSUE TITLE
Spelling error - 542. 01 Matrix

### ISSUE THREAD

**Issue by markafitzgerald1** [LeetCode-Feedback/LeetCode-Feedback#7079]
#### Your LeetCode username
markafitzgerald1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Solution Approach 3: Dynamic Programming the text "in which case the distance is minimum distance of any neightbor + 1" has a spelling error and should read "in which case the distance is minimum distance of any neighbor + 1"

#### Code you used for Submit/Run operation
n/a

#### Language used for code
n/a

#### Expected behavior
n/a

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
