### ISSUE TITLE
英文题目描述错误，中文翻译错误 - 607. Sales Person

### ISSUE THREAD

**Issue by lixiang2017** [LeetCode-Feedback/LeetCode-Feedback#7081]
**你的 LeetCode 用户名**
xiang-lee

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
英文题目Table: Orders中描述为
sales_id is a foreign key to com_id from the SalesPerson table.
中文翻译：
sales_id是来自销售员表com_id的外键。

**期望行为**
（应该为sales_id， 而不是com_id。）
英文题目Table: Orders中描述应该为
sales_id is a foreign key to sales_id from the SalesPerson table.
中文翻译：
sales_id是来自销售员表sales_id的外键。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目描述已更新，ID：xiang-lee 给予积分奖励，请查收。
