### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by Sa1Gur** [LeetCode-Feedback/LeetCode-Feedback#7082]
#### Your LeetCode username

Sa1Gur

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Don't you think that zero to the power of zero should be in the description? There is no way of finding which particular convention is expected to be followed. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Yani** [comment]
Hi @,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The missing testcase

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
