### ISSUE TITLE
Missing Test Case - 941. Valid Mountain Array

### ISSUE THREAD

**Issue by HardikRa** [LeetCode-Feedback/LeetCode-Feedback#7083]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Wrong answer present in a single test case.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool validMountainArray(vector<int>& arr) {
        int peak;
        for(int i = 0; i < arr.size() - 1; ++i)
        {
            if(arr[i+1] <= arr[i])
            {
                peak = i;
                break;
            }
        }
        if(peak == 0 || arr[peak] == arr[arr.size() -1])
            return false;
        if(peak == arr.size() - 1)
                return true;
        for(int i = peak; i < arr.size() - 1; ++i)
        {
            if(arr[i+1] > arr[i])
                return false;
        }
        return true;
    }
};
```

#### Expected behavior

All test cases pass except for one, which has the wrong answer present in it.
The given is the test case: [14,82,89,84,79,70,70,68,67,66,63,60,58,54,44,43,32,28,26,25,22,15,13,12,10,8,7,5,4,3]
This is a mountain array as can be seen, however the expected answer is false.

#### Screenshots

![image](https://user-images.githubusercontent.com/56108057/164886381-f90a72c3-813c-4a3e-bae5-d08dd89d26f0.png)

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by HardikRa** [comment]
C++

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
