### ISSUE TITLE
Change the way the object will be called 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by Snigdha8** [LeetCode-Feedback/LeetCode-Feedback#7084]
WRONG code/solution that is being ACCEPTED -

```
class Solution {
public:
    // Encodes a URL to a shortened URL.
    string encode(string longUrl) {
        int64_t hash_table_size = t.size();
        cout << "hash table size is " << hash_table_size << "\n";
        string tt = to_string(hash_table_size + 1);
        cout << "tt is " << tt << "\n";
        t[tt] = longUrl;
        cout << "shortUrl is " << ("http://tinyurl.com/" + tt) << "\n";
        return "http://tinyurl.com/" + tt;
    }


    // Decodes a shortened URL to its original URL.
    string decode(string shortUrl) {
        return t[shortUrl.substr(19, shortUrl.length() - 19)];
    }
private:
    map<string, string> t;
};

```

If we give **multiple urls in the input** in the above code then the console output will give the **same tiny url for all of those input urls.**

For example,
Input -
"https://leetcode.com/problems/design-tinyurl"
"https://ide.geeksforgeeks.org/"
"https://www.google.com/search?q=encode+a+string+cpp&rlz=1C1GCEB_enUS916US916&ei=N51jYp3JCpabseMPn6awkAI&ved=0ahUKEwjdwKztx6n3AhWWTWwGHR8TDCIQ4dUDCA8&uact=5&oq=encode+a+string+cpp&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMggIIRAWEB0QHjoHCAAQRxCwAzoFCAAQgAQ6BggAEBYQHjoICAAQFhAKEB5KBAhBGABKBAhGGABQqgNYqBZg_RdoAXABeACAAY8BiAHbA5IBAzEuM5gBAKABAcgBCMABAQ&sclient=gws-wiz"

Then console output will show below tiny urls-
http://tinyurl.com/1
http://tinyurl.com/1
http://tinyurl.com/1

Please refer this post to know why above solution is wrong (yet accepted) in detail -
https://leetcode.com/problems/encode-and-decode-tinyurl/discuss/1974812/c-eye-opener

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us: (this links that you sent to us cannot be found)

The language you submitted to reach this result.
The missing teas case

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
