### ISSUE TITLE
Missing Test Case - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by shivavishaal66215** [LeetCode-Feedback/LeetCode-Feedback#7085]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

All test cases pass even if URL is never shortened. 

#### Code you used for Submit/Run operation

```
class Solution {
public:

    // Encodes a URL to a shortened URL.
    string encode(string longUrl) {
        return longUrl;
    }

    // Decodes a shortened URL to its original URL.
    string decode(string shortUrl) {
        return shortUrl;
    }
};

// Your Solution object will be instantiated and called as such:
// Solution solution;
// solution.decode(solution.encode(url));
```

#### Language used for code
C++ 

#### Expected behavior
The submitted code should not have worked. There should've been testcases to check if the calculated URL is actually shorter than the original URL.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
