### ISSUE TITLE
Missing Test Case - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by hegdeganesh** [LeetCode-Feedback/LeetCode-Feedback#7088]
#### Your LeetCode username
Manushya

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

If encode function doesn't encodes the longUrl and returns same url, no fail reported.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    std::unordered_map<std::string, std::string> m;
    // Encodes a URL to a shortened URL.
    string encode(string longUrl) {
        string sUrl = longUrl;
        m[sUrl] = longUrl;
        return sUrl;
    }

    // Decodes a shortened URL to its original URL.
    string decode(string shortUrl) {
        return m[shortUrl];
    }
};
```

#### Expected behavior

The encode function shouldn't return same URL

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. After investigate, we are going to keep the problem as it is for now. We appreciate your support!
