### ISSUE TITLE
Missing Test Case - 120. Triangle

### ISSUE THREAD

**Issue by BodhiYonzon** [LeetCode-Feedback/LeetCode-Feedback#7089]
#### Your LeetCode username
BodhiYonzon

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question does not mention that the input List is immutable. I think this should be explicitly mentioned.

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumTotal(List<List<Integer>> triangle) {
        int n=triangle.size();
        int left,right;
        for(int i=n-2;i>=0;i--){
            for(int j=0;j<i;j++){
                left=triangle.get(i).get(j)+triangle.get(i+1).get(j);
                right=triangle.get(i).get(j)+triangle.get(i+1).get(j+1);
                triangle.get(i).set(j,Math.min(left,right));
            }
        }
        return triangle.get(0).get(0);
    }
}
```

#### Language used for code

Java

#### Expected behavior

I did not know the list would be immutable so i tried to modify values and got the wrong answer without any warning or error telling me it was immutable. So i think it would be best if the question explicitly mentioned it to avoid confusion.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
