### ISSUE TITLE
165. Compare Version Numbers

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#709]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Space complexity for Approach 2: Two Pointers, One Pass, Constant Space is incorrect (for Python specifically). For Python, as soon as you convert a chunk to an Integer, a temporary string for that Integer is created. The size of the chunk can go up to M or N, where N and M are lengths of the input strings respectively.

#### Language used for code

Python

#### Expected behavior

Space complexity is linear.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by agatagruza** [comment]
Thank you @lc-pam for the info. Glad could help.
