### ISSUE TITLE
Missing Test Case - 1817. Finding the Users Active Minutes

### ISSUE THREAD

**Issue by scottupman** [LeetCode-Feedback/LeetCode-Feedback#7095]
[1817.] Finding the Users Active Minutes

#### Your LeetCode username
scottupman1

#### Category of the bug
- [ ] Test Cases

#### Description of the bug
The input for one of the test cases does not match the size of the array "k" when the question has in the example an array of size "k"

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] findingUsersActiveMinutes(int[][] logs, int k) {
        HashMap<Integer, Integer> UAM = new HashMap<>();
        for (int i = 0; i < k; i++)
        {
            int userID = logs[i][0];
            ArrayList<Integer> times = new ArrayList<Integer>();
            for (int j = 0; j < k; j++)
            {
                if (logs[j][0] == userID)
                {
                    int time = logs[j][1];
                    if (!times.contains(time))
                        times.add(time);
                }               
            }
            if (!UAM.containsKey(userID))
                UAM.put(userID, times.size());
        }
        int[] answer = new int[k];
        for (int j = 1; j <= k; j++)
        {
            int counter = 0;
            Iterator iter = UAM.entrySet().iterator();
            while (iter.hasNext())
            {
                Map.Entry mapElement = (Map.Entry)iter.next();
                int value = (int)mapElement.getValue();
                if (value == j)
                    counter++;
            }
            answer[j-1] = counter;
        }
        
        return answer;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The example that the code runs on works but the 1st test case seems wrong.

#### Screenshots

![index-bounds-error](https://user-images.githubusercontent.com/63807163/164960866-c45c33a4-9898-453b-aafe-3ba6915b0ed8.png)
![acceptance](https://user-images.githubusercontent.com/63807163/164960867-eb06991d-b4c4-46b7-bcb6-fc5e23399614.png)
![example](https://user-images.githubusercontent.com/63807163/164960868-c00db7d7-6b9f-4112-8816-1bb752571d49.png)

**Comment by LC-Yani** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
