### ISSUE TITLE
Different results for local and leetcode - 149. Max Points on a Line

### ISSUE THREAD

**Issue by cjambo** [LeetCode-Feedback/LeetCode-Feedback#7096]
#### Your LeetCode username
cjambo

#### Category of the bug
- [x] Question

#### Description of the bug
Individual test case have different results for local and leetcode, and the local result is right

#### Code you used for Submit/Run operation

```
class Solution(object):
    def maxPoints(self, points):
        """
        :type points: List[List[int]]
        :rtype: int
        """
        if not points:
            return 0
        if len(points) <= 2:
            return len(points)

        result = 0
        for i in range(len(points) - 1):
            map = dict()
            same = 1
            for j in range(i + 1, len(points)):
                dx = points[j][0] - points[i][0]
                dy = points[j][1] - points[i][1]
                if dx == 0 and dy == 0:
                    same += 1
                    continue
                elif dx == 0:
                    map["inf"] = map.get("inf", 0) + 1
                elif dx != 0:
                    slope = dy / dx
                    map[slope] = map.get(slope, 0) + 1
            local_max = max(list(map.values())) + same
            result = max(result, local_max)
        return result
```

#### Language used for code
Python

#### Expected behavior
the test [[0, 0], [4, 5], [7, 8], [8, 9], [5, 6], [3, 4], [1, 1]] in local output is 5, but in leetcode is 7. But the correct answer given by leetcode is 5.

#### Screenshots

![Snipaste_2022-04-24_21-12-16](https://user-images.githubusercontent.com/34180719/164978247-6c29b864-3f55-46d1-9d67-e63eab5a7da7.png)

![Snipaste_2022-04-24_20-55-26](https://user-images.githubusercontent.com/34180719/164977894-19316e0d-c9b6-4eff-8102-4cd54081cc36.png)

**Comment by cjambo** [comment]
After I cleared the cookies, it was back to normal

**Comment by LC-Yani** [comment]
I'm sorry we didn’t get to you sooner - but I am glad to see your issue has resolved!

Please feel free to let me know if you have any other questions or concerns.

Happy LeetCoding!
