### ISSUE TITLE
Missing Topic Tags - 2248. Intersection of Multiple Arrays

### ISSUE THREAD

**Issue by durgesh-4526** [LeetCode-Feedback/LeetCode-Feedback#7097]
#### Your LeetCode username
durgeshsahu7

#### Category of the bug
- [ ] Missing Topic Tags

#### Expected behavior

Topic Tags are Missing 
It can be added as:-
Array , Matrix , Hash , Sorting

**Comment by LC-Yani** [comment]
Hi @durgesh-4526 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.
