### ISSUE TITLE
Unexpected Test Case Behaviour - 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by Saketkr21** [LeetCode-Feedback/LeetCode-Feedback#7098]
#### Your LeetCode username
stevewatson1008

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

A same Test case is behaving differently when run by `Submit` and `Run Code` Button. 
From `Run Code` it shows verdict as Accepted, But from `Submit` button it shows verdict as WA.

#### Code you used for Submit/Run operation

```
// 199. Binary Tree Right Side View
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def rightSideView(self, root: Optional[TreeNode], ans = []) -> List[int]:
        if root is None:
            return
        ans.append(root.val)
        if root.left is None and root.right is None:
            return
        if root.right is None:
            self.rightSideView(root.left, ans)
        else:
            self.rightSideView(root.right, ans)
        # print(ans, root)
        return ans
```

#### Language used for code
Python 3

#### Expected behaviour

The same Test case should behave the same irrespective of Run via the `Submit` or `Run Code` Button.
The verdict should be the same in both as Accepted in the given Screenshot case.

#### Screenshots

<img width="1266" alt="Screenshot 2022-04-25 at 12 34 21 AM" src="https://user-images.githubusercontent.com/35528409/164992340-da253464-601e-414c-a7a1-3ef9c5b06502.png">

**Comment by LC-Yani** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
