### ISSUE TITLE
https://leetcode.com/problems/longest-happy-prefix/

### ISSUE THREAD

**Issue by chethanrao** [LeetCode-Feedback/LeetCode-Feedback#71]
**What kind of the bug**
- [ ] longest happy prefix (https://leetcode.com/problems/longest-happy-prefix/)
- [ ] The code is below
- [ ] Java,Python 3

**Describe the bug**
For the longest happy prefix problem brute force solution works in python 3 and not in java.
As this a contest problem it affected the rankings.

**what language is your code written in**
Java,Python 3

**The code you submit/run**
```
Python 3
class Solution:
    def longestPrefix(self, s: str) -> str:
        i = len(s)-1
        while i > 0:
            if s[:i] == s[-i:]:
                return s[:i]
            i -= 1
        return ""
Java 

class Solution {
    public String longestPrefix(String s) {
        int longest=0;
        String str=null;
        for (int i=s.length()-2;i>=0;i--){
            if (s.substring(0,i+1).equals(s.substring(s.length()-1-i,s.length()))){
                return s.substring(0,i+1);
            }       
        }
        return "";
    }
}
```

**Expected behavior**
Expect that brute force works for both python 3 and java
or for neither of them.
**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @chethanrao,
Thank you for reaching out to us. I've relayed this issue to our engineers to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @chethanrao,
Thank you for your time. String comparison in Python 3 is really fast, which is the reason why the Python 3 code works but not the Java code.
