### ISSUE TITLE
456. 132 Pattern - failing test cases

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#710]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Approach 3: Searching Intervals solutions is failing in following test cases:
`[1,2,3,3,3,4,5,3]`
`[1,2,2,3,2]`

#### Code you used for Submit/Run operation

```
public class Solution {
    public boolean find132pattern(int[] nums) {
        List < int[] > intervals = new ArrayList < > ();
        int i = 1, s = 0;
        while (i < nums.length) {
            if (nums[i] <= nums[i - 1]) {
                if (s < i - 1)
                    intervals.add(new int[] {nums[s], nums[i - 1]});
                s = i;
            }
            for (int[] a: intervals)
                if (nums[i] > a[0] && nums[i] < a[1])
                    return true;
            i++;
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Algorithm should pass both test cases and return "true".

#### Screenshots

<img width="393" alt="Capture" src="https://user-images.githubusercontent.com/7014697/88469660-ce592e00-cea8-11ea-9e25-9910b91e673e.PNG">

<img width="397" alt="Capture1" src="https://user-images.githubusercontent.com/7014697/88469661-cf8a5b00-cea8-11ea-9a0e-bdd70276e255.PNG">

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by agatagruza** [comment]
Thank you @lc-pam for your response. Glad could help.

**Comment by lc-pam** [comment]
Hi @agatagruza 
We also added the test cases you brought up in this ticket. Your LeetCode account has received 100 LeetCoins as the reward for contributing test cases. We appreciate your support!

**Comment by agatagruza** [comment]
Thank you @lc-pam. Highly appreciated!
