### ISSUE TITLE
Missing Test Case - 1299. Replace Elements with Greatest Element on Right Side 

### ISSUE THREAD

**Issue by zawlurnthan** [LeetCode-Feedback/LeetCode-Feedback#7100]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

It doesn't allow Optional class. LeetCode Editor needs to upgrade to match language newer versions

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] replaceElements(int[] arr) {
        // have an extra container
        int[] result = new int[arr.length];
        
        // loop through the array
        for (int i = 0; i < arr.length; i++) {
            // get right side max elements of current index in the array
            
            Optional<Integer> max = Arrays.stream(arr)
                .boxed()
                .toList()
                .subList(i + 1, arr.length)
                .stream()
                .max(Integer::compare);

            // assign the max to the result array
            if (max.isPresent()){
                result[i] = max.get();
            }

            // assign the last index of the array 
            if ( i == arr.length - 1) {
                result[i] = -1;
            }
        }
        return result;
    }
}
```

#### Language used for code

Java

#### Expected behavior

It should get the max number of the input array.

#### Screenshots

![screen shot](https://user-images.githubusercontent.com/37648883/164998261-50b62eda-a3a7-4153-990c-724c67fe8811.PNG)

#### Additional context

I get correct answer without my IDE complains.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
