### ISSUE TITLE
Missing Test Case - 284. Peeking Iterator

### ISSUE THREAD

**Issue by maskalek** [LeetCode-Feedback/LeetCode-Feedback#7104]
#### Your LeetCode username
maskalek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In C#, initially, iterator is already in the first position.

#### Code you used for Submit/Run operation

```
// C# IEnumerator interface reference:
// https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerator?view=netframework-4.8

class PeekingIterator {
    private IEnumerator<int> _iterator;
    private bool _hasNext;
    
    // iterators refers to the first element of the array.
    public PeekingIterator(IEnumerator<int> iterator) {
        // initialize any member here.
        _iterator = iterator;
        _hasNext = true;
    }
    
    // Returns the next element in the iteration without advancing the iterator.
    public int Peek() {
        return _iterator.Current;
    }
    
    // Returns the next element in the iteration and advances the iterator.
    public int Next() {
        var next = _iterator.Current;
        _hasNext = _iterator.MoveNext();
        return next;
    }
    
    // Returns false if the iterator is refering to the end of the array of true otherwise.
    public bool HasNext() {
		return _hasNext;
    }
}
```

#### Language used for code
C#

#### Expected behavior
According to documentation (https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerator?view=netframework-4.8), I expect that initially, the enumerator is positioned before the first element.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, we submitted your feedback to our team, please also feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
