### ISSUE TITLE
力扣596题，使用多种正确答案提交后，使用报“执行出错”

### ISSUE THREAD

**Issue by liufei1997** [LeetCode-Feedback/LeetCode-Feedback#7105]
**匆匆那年**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [x] 题目 596  https://leetcode-cn.com/problems/classes-more-than-5-students/
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
使用正确结果提交后，始终报“执行出错”

**你使用的语言**
Mysql

**你提交或者运行的代码**
```
SELECT
    class
FROM
    (SELECT
        class, COUNT(DISTINCT student) AS num
    FROM
        courses
    GROUP BY class) AS temp_table
WHERE
    num >= 5;
```

**期望行为**
期望运行通过，AC

**屏幕截图**
![image](https://user-images.githubusercontent.com/58357252/165039891-70f85701-5492-47cf-b279-fbd6d320dfa7.png)

**额外的上下文**
使用不同的正确代码提交，都是执行出错，结果如下图所示
![image](https://user-images.githubusercontent.com/58357252/165040082-1aeb01a0-12b0-4440-8243-011917adc682.png)

**Comment by akaisiro** [comment]
是变量名的原因，用`Courses`替换`courses`

**Comment by liufei1997** [comment]
替换表名后，依然报“执行出错”






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月25日(星期一) 下午3:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 力扣596题，使用多种正确答案提交后，使用报“执行出错” (Issue #7105)





 
是变量名的原因，用Courses替换courses
