### ISSUE TITLE
提出新问题 :遍历前缀树转换成字符串数组

### ISSUE THREAD

**Issue by masx200** [LeetCode-Feedback/LeetCode-Feedback#7109]
**你的 LeetCode 用户名**

masx200
**Bug 类型**
- [x] 题目
- [x] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**

新问题:遍历前缀树转换成字符串数组

给定一个前缀树,返回前缀树里的所有单词构成的顺序不限的数组

前缀树的接口如下:
```ts
interface PrefixTree  {children: Map<string, PrefixTree>;isEnd: boolean;};
```
布尔字段isEnd，表示该节点是否为字符串的结尾。
指向子节点的指针的哈希映射children.这个哈希映射的每个键都是单个字符,这个哈希映射的每个值都是前缀树.
遍历前缀树的函数接口如下:
```ts
function PrefixTreeToArray(root: PrefixTree): Array<string>;
```
可以参考第208题

[208. 实现 Trie (前缀树)](https://leetcode-cn.com/problems/implement-trie-prefix-tree/)

与第208题不同的是,前缀树当中的单词可以由任意字符构成,所以只能用哈希映射来保存子节点.

前缀树当中的每个单词长度的范围从1到100000.

前缀树中的所有单词数量的范围从0到100000.

添加单词到前缀树的方法可参考如下:

```ts
function PrefixTreeInsert(root: PrefixTree, word: string): void {
    function insert(word: string) {
        if (word.length === 0) return;
        let node = root;
        for (const ch of word) {
            const next = node.children.get(ch) ??
                (() => {
                    const next = PrefixTree();
                    node.children.set(ch, next);
                    return next;
                })();

            node = next;
        }
        node.isEnd = true;

    }
    return insert(word);
}
interface PrefixTree  {
    children: Map<string, PrefixTree>;
    isEnd: boolean;
};

function PrefixTree(): PrefixTree {
    return { children: new Map(), isEnd: false };
}
const tree = PrefixTree();
const words = ["bed", "apple", "apply", "2", "7", "11", "15"]
words.forEach((word) => PrefixTreeInsert(tree, word));
// console.log(tree)
```

示例1:

给定字符串数组 `words= ["bed","apple","apply","2", "7", "11", "15","target" , "9"]`

测试时,创建一个前缀树`root`,把所有单词添加到前缀树当中,作为参数传给函数`PrefixTreeToArray`

执行函数`PrefixTreeToArray`返回顺序不限的字符串数组 `["bed","apple","apply","2", "7", "11", "15","target" , "9"]`

要求输入的字符串数组和输出的字符串数组都包含相同的字符串,但是顺序不限.

示例2:

给定空字符串数组 `words= []`

测试时,创建一个空前缀树`root`,作为参数传给函数`PrefixTreeToArray`

执行函数`PrefixTreeToArray`返回空的字符串数组 `[]`

**你使用的语言**
typescript

**你提交或者运行的代码**

可以参考第208题

208. 实现 Trie (前缀树)

https://leetcode-cn.com/problems/implement-trie-prefix-tree/

方法一：递归(调用栈溢出)

由于单个字符串的长度从1到100000,所以会出现调用栈溢出的情况

每次递归的时候都要把前缀传给下一个输出函数,然后输出的时候把前缀加上一起输出.

如果child.isEnd为true则说明字符串结束,输出字符串.

每层前缀树处理完后处理下一层前缀树.

递归结束条件是所有前缀树都没有子节点.
```ts
function PrefixTreeToArray(root: PrefixTree): Array<string> {
    const r: Array<string> = [];
    traverse(root, (s) => r.push(s));
    return r;
}
function traverse(root: PrefixTree, output: (s: string) => void) {
    root.children.forEach(function (child, key) {

        if (child.isEnd) {
            output(key);
        }
        return traverse(child, (s: string) => output(key + s));
    });
}
interface PrefixTree  {
    children: Map<string, PrefixTree>;
    isEnd: boolean;
};


```
方法二:递归转循环

为了解决调用栈溢出的问题,可以使用递归转循环

```ts
function PrefixTreeToArray(root: PrefixTree): Array<string> {
    if (root.children.size === 0) {
        return [];
    }
    const r: Array<string> = [];
    let result = traverse([{ root, prefix: "" }], (s) => r.push(s));
    while (typeof result == "function") {
        result = result();
    }
    return r;
}
function traverse(
    roots_and_prefixes: { root: PrefixTree; prefix: string }[],
    output: (s: string) => void,
) {
    if (roots_and_prefixes.length === 0) {
        return;
    }
    return () => {
        const rap: typeof roots_and_prefixes = [];
        for (const { root, prefix } of roots_and_prefixes) {
            if (root.children.size === 0) {
                continue;
            }
            for (const [key, child] of root.children) {
                if (child.isEnd) {
                    output(prefix + key);
                }
                rap.push({ root: child, prefix: prefix + key });
            }
        }

        return traverse(rap, output);
    };
}

interface PrefixTree  {
    children: Map<string, PrefixTree>;
    isEnd: boolean;
};


```

方法三:循环迭代

每次循环的时候都要保存前缀,然后输出的时候把前缀加上一起输出.

如果child.isEnd为true则说明字符串结束,输出字符串.

每层前缀树处理完后处理下一层前缀树.

循环结束条件是所有前缀树都没有子节点.

```ts
function PrefixTreeToArray(root: PrefixTree): Array<string> {
    if (root.children.size === 0) {
        return [];
    }
    const res: Array<string> = [];
    let prefix_and_entries: {
        prefix: string;
        key: string;
        child: PrefixTree;
    }[] = [...root.children].map((e) => ({
        prefix: "",
        key: e[0],
        child: e[1],
    }));
    while (prefix_and_entries.length > 0) {
        const temp: typeof prefix_and_entries = [];
        for (const entry of prefix_and_entries) {
            const { prefix, key, child } = entry;
            if (child.isEnd) {
                res.push(prefix + key);
            }
            for (const e of child.children) {
                temp.push({
                    prefix: prefix + key,
                    key: e[0],
                    child: e[1],
                });
            }
        }
        prefix_and_entries = temp;
    }
    return res;
}

interface PrefixTree  {
    children: Map<string, PrefixTree>;
    isEnd: boolean;
};


```
**期望行为**
描述你期望的结果
测试案例
输入: root= `["bed","apple","apply","2", "7", "11", "15","target" , "9"]`
输出:  `["bed","apple","apply","2", "7", "11", "15","target" , "9"]`

输入: root=`[]`
输出: `[]`

巨大的测试案例
[巨大的测试案例.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8553821/default.txt)

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by masx200** [comment]
巨大的测试案例
[巨大的测试案例.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8553821/default.txt)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by zuizaiqinshi** [comment]
用户您好，新贡献的题目需要在力扣主站【贡献题目】页面进行提交，请您至 https://leetcode-cn.com/contribute/ 重新提交，谢谢～

**Comment by masx200** [comment]
> 用户您好，新贡献的题目需要在力扣主站【贡献题目】页面进行提交，请您至 https://leetcode-cn.com/contribute/ 重新提交，谢谢～


https://support.leetcode-cn.com/hc/request/view/24363/

LeetCode - 支持 • 2022年04月25日 下午 4:09
您好，

感谢您的来信，当前我们与相关团队确认，贡献题目功能暂时没有维护了，当前力扣中文社区题目是和美国网页保持同步，已转达技术相关团队后期会持续优化的，感谢您的支持～

Best Regards,
Leetcode | Support Team

LeetCode - 支持 • 2022年04月25日 下午 4:23
您好，
非常感谢您的反馈，我们会在后期的版本中不断增加完善此类功能哟。贡献题目和测试用例您可以访问 [Github 仓库](https://github.com/leetcode/LeetCode-Feedback)，直接按模版使用英文提交 issue，相关团队会尽可能快的回复并跟进。
Best Regards,
Leetcode | Support Team

**Comment by masx200** [comment]
@zuizaiqinshi @feiceh 两边都处理不了吗？不会吧？

**Comment by zuizaiqinshi** [comment]
> @zuizaiqinshi @feiceh 两边都处理不了吗？不会吧？
您好，当前用户贡献的题目会视力扣中文社区的题目需求不定期进行审核，请您保持关注，感谢您的支持～

**Comment by zuizaiqinshi** [comment]
> @zuizaiqinshi @feiceh 两边都处理不了吗？不会吧？
您好，当前用户贡献的题目会视力扣中文社区的题目需求不定期进行审核，请您保持关注，感谢您的支持～
