### ISSUE TITLE
5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by JsthcitPizifly** [LeetCode-Feedback/LeetCode-Feedback#711]
#### Your LeetCode username
imaginedreampzfly

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

![unnamed](https://user-images.githubusercontent.com/32784883/88475213-6fef8680-cf60-11ea-9d42-c41ba727a1eb.png)

This is "5. Longest Palindromic Substring".
and the longest palindromic 
substring can be cb, bb.
but why was my output wrong... 

#### Code you used for Submit/Run operation

```
// 5. Longest Palindromic Substring
class Solution {
public:
    string longestPalindrome(string s) {
        
	std::string res;
	int size = s.size();
	std::vector<std::vector<int>> P(size, std::vector<int>(size));
	for (int i = 0; i < size ; ++i) {
		for (int j = i; j < size ; ++j) {
			if (i == j)
				P[i][j] = true;
			else
				P[i][i+1] = (s[i] == s[i+1]);
		}
	}
	for (int i = size - 1; i >= 0; --i) {
		for (int j = size - 1; j >= i; --j) {
			if (i == j)
				P[i][j] = true;
            else if (j - i <= 1)
				P[i][j] = true;
			else if (i != size-1 && j != 0)
				P[i][j] = P[i+1][j-1] && (s[i] == s[j]);

			if (P[i][j] && res.size() < (j - i + 1))
				res = s.substr(i, j-i+1);
		}
	}

	return res;

}

};
```

#### Expected behavior

**This is "5. Longest Palindromic Substring".
and the longest palindromic 
substring can be cb, bb.
but why was my output wrong...**

**Comment by Kartik33** [comment]
Hi imaginedreampzfly,

The answer lies in the definition of palindrome i.e it must be same when read backward and from starting. If you read BD from front it will be "BD" but when you read BD from last it will be "DB" which are not same therefore it BD is not a valid answer.

Thanks,
Kartik

**Comment by JsthcitPizifly** [comment]
Oh! I got it!

Kartik33 <notifications@github.com> 于2020年7月27日周一 上午2:33写道：
