### ISSUE TITLE
Missing Test Case - 584. Find Customer Referee

### ISSUE THREAD

**Issue by dqkuane** [LeetCode-Feedback/LeetCode-Feedback#7110]
#### Your LeetCode username
jjansen94

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Question asks for the IDs of the customers, but the solution requires the names of the customers.
This means that following the instructions results in a fail.

#### Code you used for Submit/Run operation

```
SELECT id FROM Customer
WHERE IFNULL(referee_id,0) != 2;
```

#### Expected behavior
The problem is Accepted when selecting ID, or the description references name rather than ID.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
