### ISSUE TITLE
LCP1488:题目描述问题

### ISSUE THREAD

**Issue by shaogezhu** [LeetCode-Feedback/LeetCode-Feedback#7111]
**你的 LeetCode 用户名**
shaogezhu

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目中最后一句话说```（详情请看示例 4）。```,但是题目提供的示例中，没有示例4。看下面截图

题目链接：[https://leetcode-cn.com/problems/avoid-flood-in-the-city/](https://leetcode-cn.com/problems/avoid-flood-in-the-city/)

**你使用的语言**
C++

**期望行为**
没有看到有示例4

**屏幕截图**
![image](https://user-images.githubusercontent.com/91406169/165078270-5389a783-9e1d-444e-b1a2-58eccf1b8e1d.png)
![image](https://user-images.githubusercontent.com/91406169/165078330-33143afa-4994-4f25-b3f3-5eb7f56f403f.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目描述已更新，ID：shaogezhu 给予积分奖励，请查收。
