### ISSUE TITLE
169. 多数元素-缺少数据范围

### ISSUE THREAD

**Issue by everythingCanBeModeled** [LeetCode-Feedback/LeetCode-Feedback#7112]
**你的 LeetCode 用户名**
everythingCanBeModeled

**Bug 类型**
- [ ] 题目

**描述**
[169. 多数元素](https://leetcode-cn.com/problems/majority-element/)
中文题目缺少数据范围

**期望行为**
应在中文题目里加上数据范围

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：题目看上去已有范围，请知晓。
