### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by ravipatel7** [LeetCode-Feedback/LeetCode-Feedback#7113]
#### Your LeetCode username
ravi_patel7

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [Y] Missing Test Cases 

#### Description of the bug

Missing Test-case as if no profit is found for input [7,5,4,3,2,1] it should return 0 but below code is accepted though it doesn't return 0.

#### Code you used for Submit/Run operation

```
// 121. Best Time to Buy and Sell Stock
/**
 * @param {number[]} prices
 * @return {number}
 */
var maxProfit = function(prices) {
    let minPrice = Number.MAX_VALUE;
    let maxProfit = Number.MIN_VALUE;
    for(let i=0;i<prices.length;i++){
        if(minPrice>prices[i]){
            minPrice = prices[i]
        }else{
            let diff = prices[i]-minPrice;
            maxProfit = Math.max(maxProfit, diff);
        }
    }
    return maxProfit;
};
```

#### Language used for code
Javascript

#### Expected behavior

Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.

#### Screenshots

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/16088173/165123913-18bab2e3-1c6a-4ebf-a2a4-b75e8142e45a.png">

With Test-case : 

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/16088173/165127046-f63914fc-76d2-4dc2-ab9e-9bb94bdf3434.png">

**Comment by ravipatel7** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/16088173/165126853-2514a8a6-f76a-4eb4-aab1-1509e8b6c563.png">

**Comment by ravipatel7** [comment]
But the code above which is accepted doesn't return 0 still it is accepted. The code returns Number.MIN_VALUE (5e-324) which is not 0.

**Comment by stormsunshine** [comment]
The code you put in this issue DOES RETURN 0. You can change the value "Number.MIN_VALUE" to a negative integer, like -1, and the code won't get accepted. There are already similar test cases existing.
> But the code above which is accepted doesn't return 0 still it is accepted. The code returns Number.MIN_VALUE (5e-324) which is not 0. this doesn't satisfy the question as it says " If you cannot achieve any profit, return 0."
