### ISSUE TITLE
Wrong Constraint description - 721. Accounts Merge

### ISSUE THREAD

**Issue by Vinayaka2k** [LeetCode-Feedback/LeetCode-Feedback#7114]
#### LeetCode username
vinuvinayaka2000

#### Category of the bug
- [ ] Question

#### Description of the bug

The third constraint must be : 

**1<= length of accounts[i][j] <= 30**
instead of : 
**1 <= accounts[i][j] <= 30**

Since accounts[i][j] would point to a string

**Comment by LC-Yani** [comment]
Thank you for your time. I have submitted your feedback to update the problem. We appreciate your support!
