### ISSUE TITLE
Incorrect value for "B" in Approach 6 - 70. Climbing Stairs

### ISSUE THREAD

**Issue by pinglu85** [LeetCode-Feedback/LeetCode-Feedback#7117]
#### Your LeetCode username
pinglu85

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Approach 6: Fibonacci Formula, the calculated value of "B" is incorrect. It should be (√5-1)/2√5 instead of (1-√5)/2√5. 

In addition, the value of "a" seems incorrect as well. It should be (1±√5)/2, not 1/√5((1±√5)/2).

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for identifying the typos in the derivation of the Fibonacci Formula. The derivation has been corrected and recalculated in terms of phi and psi.
