### ISSUE TITLE
Wrong test case in leetcode - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by namankhurpia** [LeetCode-Feedback/LeetCode-Feedback#7119]
#### Your LeetCode username
namankhurpia2
 

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

Wrong testcases attached

#### Description of the bug

As you can see the screenshot, for the testcase "ac" it is expecting an output "a" which is wrong.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Java

#### Expected behavior

The Expected behavior would be for testcase "ac" it should return "".

#### Screenshots

![Capture](https://user-images.githubusercontent.com/30630783/165393630-fb82247c-9612-4326-b2ac-64014a70e594.PNG)

#### Additional context

Please check screenshot

**Comment by stormsunshine** [comment]
Please provide the reason why the output "a" is wrong. Isn't "a" a palindrome?

**Comment by namankhurpia** [comment]
for input "ac" how can the program return "a", if "a" is a palindrome then even "c" is a palindrome and apparently all single letters in a word of length 2 are palindrome. and why stop for length 2, even for 3-4-5 digits single subtrings are palindrome, the question says Longest Palindrome and since in this case there are 2 letters of same length (i.e. 1) how can "a" be an acceptable choice., Just prove why "a" is acceptable and "c" isnt.

**Comment by namankhurpia** [comment]
@LC-Yani  can you please give me a reasonable explanation over why "a" is correct and "c" is incorrect answer to this problem

**Comment by Umairxm** [comment]
> for input "ac" how can the program return "a", if "a" is a palindrome then even "c" is a palindrome and apparently all single letters in a word of length 2 are palindrome. and why stop for length 2, even for 3-4-5 digits single subtrings are palindrome, the question says Longest Palindrome and since in this case there are 2 letters of same length (i.e. 1) how can "a" be an acceptable choice., Just prove why "a" is acceptable and "c" isnt.

Answer is "" this they must have made a mistake

**Comment by akladyous** [comment]
you're absolutely right, i reported it a couple of yrs ago, as expected! no body answer

**Comment by Umairxm** [comment]
> you're absolutely right, i reported it a couple of yrs ago, as expected! no body answer

I know right. I just did the hardcoded method 
if(s== "ac")
        {
            s="a";
            return s;
        }
I just started the leetcode program solving to increase my skills
