### ISSUE TITLE
656. Coin Path 

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#712]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Approach 1: Brute Force[Time Limit Exceeded] has incorrect description.

#### Code you used for Submit/Run operation

```
public class Solution {
    public List < Integer > cheapestJump(int[] A, int B) {
        int[] next = new int[A.length];
        Arrays.fill(next, -1);
        jump(A, B, 0, next);
        List < Integer > res = new ArrayList();
        int i;
        for (i = 0; i < A.length && next[i] > 0; i = next[i])
            res.add(i + 1);
        if (i == A.length - 1 && A[i]>= 0)
            res.add(A.length);
        else
            return new ArrayList < Integer > ();
        return res;
    }
    public long jump(int[] A, int B, int i, int[] next) {
        if (i == A.length - 1 && A[i] >= 0)
            return A[i];
        long min_cost = Integer.MAX_VALUE;
        for (int j = i + 1; j <= i + B && j < A.length; j++) {
            if (A[j] >= 0) {
                long cost = A[i] + jump(A, B, j, next);
                if (cost < min_cost) {
                    min_cost = cost;
                    next[i] = j;
                }
            }
        }
        return min_cost;
    }
}

```

#### Language used for code

Java

#### Expected behavior

It doesn't TLE and submission is accepted.

#### Screenshots

<img width="388" alt="Capture" src="https://user-images.githubusercontent.com/7014697/88478512-ce374d80-cefd-11ea-90dc-154717686cfd.PNG">

**Comment by lc-ivan** [comment]
Hi @agatagruza,
Thank you for reaching out. After reviewing and testing the code you provided on our end, we have received TLE after submitting (please see attached). Please note that running code from a test case only tests that one test case whereas submitting the code tests all tests cases resulting in TLE. If you have received a different outcome (such as Accepted) when submitting the code, please attach those images to this ticket and we will review as soon as possible!

![Screen Shot 2020-07-31 at 2 12 16 PM](https://user-images.githubusercontent.com/68418560/89077798-e82ac300-d337-11ea-8f6a-f8cd26a09a5a.png)
