### ISSUE TITLE
missing Constraints 1202

### ISSUE THREAD

**Issue by Pranav108** [LeetCode-Feedback/LeetCode-Feedback#7122]
#### Your LeetCode username
[BEN__10](https://leetcode.com/BEN__10/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

[1202. Smallest String With Swaps](https://leetcode.com/problems/smallest-string-with-swaps/)
It will be better if there will be one more constrain saying  `Each pair in pairs are unique` as we have seen in other questions.

**Comment by LC-Yani** [comment]
Thank you for your time. I've submitted your feedback to update the problem. We appreciate your support!
