### ISSUE TITLE
Missing Test Case - 1527. Patients With a Condition

### ISSUE THREAD

**Issue by Ian-Kamau-Kariuki** [LeetCode-Feedback/LeetCode-Feedback#7125]
#### Your LeetCode username
Ian_Kamau69

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug
When the code is run, the outcome is Accepted but upon submission, it is denied. I believe it's a matter to do with the test case.

#### Code you used for Submit/Run operation
```SELECT patient_id, patient_name, conditions from Patients where LOCATE('DIAB1', conditions);```

#### Language used for code
MySQL

#### Expected behavior
Your input
{"headers": {"Patients": ["patient_id", "patient_name", "conditions"]}, "rows": {"Patients": [[1, "Daniel", "YFEV COUGH"], [2, "Alice", ""], [3, "Bob", "DIAB100 MYOP"], [4, "George", "ACNE DIAB100"], [5, "Alain", "DIAB201"]]}}
Output
{"headers": ["patient_id", "patient_name", "conditions"], "values": [[3, "Bob", "DIAB100 MYOP"], [4, "George", "ACNE DIAB100"]]}
Expected
{"headers": ["patient_id", "patient_name", "conditions"], "values": [[3, "Bob", "DIAB100 MYOP"], [4, "George", "ACNE DIAB100"]]}

#### Actual
Input:
{"headers": {"Patients": ["patient_id", "patient_name", "conditions"]}, "rows": {"Patients": [[1, "Daniel", "SADIAB100"]]}}
Output:
{"headers": ["patient_id", "patient_name", "conditions"], "values": [[1, "Daniel", "SADIAB100"]]}
Expected:
{"headers": ["patient_id", "patient_name", "conditions"], "values": []}

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
