### ISSUE TITLE
435. Non-overlapping Intervals solution bugs and poor wording

### ISSUE THREAD

**Issue by FlorentinaSimlinger** [LeetCode-Feedback/LeetCode-Feedback#7126]
#### Your LeetCode username
flo_random

#### Category of the bug
- [ x] Solution

#### Description of the bug
*Approach #1 Brute Force*:
- variables taken and nottaken should be renamed to something clearer, e.g. keepScore and eraseScore
- the description says it sorts by starting point, but the code sorts by endpoint
- the wording of the description should be more in line with similar recursive problems, for instance for LCS problems the common wording would be: "either we include the current character in the LCS, or we don't". Similarly, the wording here could be "either we include the interval in the final result, or we don't". (ie, use include/exclude language similar to other problems).

*Approach #2 Using DP based on starting point*
- it says it sorts by starting point but actually sorts by endpoint - this is also true for the other approaches
- the method isOverlapping names the parameters exactly opposite to how they're passed in which is confusing when reading it - this is also true for the next approaches

*Overall*
Frankly, the solution should be re-written. The approaches are good, but the description makes it unnecessarily difficult to understand and does not align with the code (as mentioned in many comments).

#### Language used for code
Java

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for bringing this issue of article quality to our attention. We agree that this article is a potential candidate to be rewritten. Someone from our team will further inspect the article to either address current quality issues or assign the article to be rewritten.
