### ISSUE TITLE
Missing Test Case - 476. Number Complement

### ISSUE THREAD

**Issue by nesarptr** [LeetCode-Feedback/LeetCode-Feedback#7127]
#### Your LeetCode username

nesarptr

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

I submitted My Solution for this problem and it ran pretty well. but I think there is a missing test case. if that case would be added then my code would not pass all the test cases.

#### Code you used for Submit/Run operation

```
// Number Complement
class Solution {
    public int findComplement(int num) {
        int ans = 0;
        int digit = findDigits(num);
        for (int i = 0; i < digit - 1; i++) {
            ans += (int)Math.pow(2,i) * ((num ^ 1) & 1);
            num >>= 1;
        }
        return ans;
    }
    private int findDigits(int n) {
        if (n == 0) return 1;
        return (int)(Math.log(n) / Math.log(2)) + 1;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

If the input was 0 then the answer will be 1. in that case I expected my code to not passed all the test cases but it did. that is why I think there should be added one more test case in which input would be 0 and expected answer would be 1

#### Additional context

I ran the code that I put above in `1009. Complement of Base 10 Integer` problem which is absolutely similar to the current problem but not able to pass all the test cases

**Comment by stormsunshine** [comment]
The two problems are still a bit different. For problem 476, the input must be a positive integer, so the test case 0 is invalid.

**Comment by nesarptr** [comment]
> The two problems are still a bit different. For problem 476, the input must be a positive integer, so the test case 0 is invalid.

Oh didn't notice! Thanks :)
