### ISSUE TITLE
Table 'test.my_numbers' doesn't exist

### ISSUE THREAD

**Issue by Tegrisco** [LeetCode-Feedback/LeetCode-Feedback#7128]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Studyandmiii

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目：https://leetcode-cn.com/problems/biggest-single-number/
这个issue没有完全解决：https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/5266#issue-1048272256

**你使用的语言**
mysql

**你提交或者运行的代码**
```
select max(num) as num from
(select num from MyNumbers
group by num
having count(num) = 1) t
;
```

**期望行为**
MyNumbers 表应该存在
提交官方题解的答案，可以通过测试，而不是提示表不存在
**屏幕截图**
![image](https://user-images.githubusercontent.com/31361944/165532826-422117fa-0dcd-4afa-a067-bc277c36fa19.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
您好，在与相关团队反馈核实后，当前题目已修复。
