### ISSUE TITLE
1496. Path Crossing | Missing Test Case

### ISSUE THREAD

**Issue by coder-zs-cse** [LeetCode-Feedback/LeetCode-Feedback#7129]
#### Your LeetCode username
`zubinshah`

#### Category of the bug
`Missing Test Cases` 

#### Description of the bug
I stored visited coordinates into the set in the string format "xy", so in case x,y is 1,11 and in another case say x,y is 11,1 both the entries will be in the form of "111". This bug creates an ambiguity in the visited coordinates and thus is expected to fail, but surprisingly, it passed all the test cases.
Test case I propose to add:
Input: path = "ENNNNNNNNNNNEEEEEEEEEESSSSSSSSSS"
Here we visit (1,11) and then visit (11,1). Although we do not cross the path, the algorithm will report that we have crossed the path which is not as expected.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    bool isPathCrossing(string path) {
        unordered_set<string> record;
        int x = 0,y=0;
        record.insert("00");
        for(int i=0;i<path.length();i++){
            int current = path[i];
            switch(current){
                case 'N': y++;
                    break;
                case 'S': y--;
                    break;
                case 'E': x++;
                    break;
                case 'W': x--;
                    break;
            }
            auto check = record.find(to_string(x)+to_string(y));
            if(check!=record.end())  return true;
            record.insert(to_string(x) +to_string(y));
        }
        return false;
    }
};
```

#### Language used for code
`C++`

#### Expected behavior
The expected output for testcase proposed above is False. But the output of above code is true

#### Additional context
It's generally important to store strings as "x y" i.e. with spacing in between. After which the proposed test case runs perfectly.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
