### ISSUE TITLE
1722 Need more elaboration for problem description

### ISSUE THREAD

**Issue by Pranav108** [LeetCode-Feedback/LeetCode-Feedback#7130]
#### Your LeetCode username
[BEN__10](https://leetcode.com/BEN__10/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
[1722. Minimize Hamming Distance After Swap Operations](https://leetcode.com/problems/minimize-hamming-distance-after-swap-operations/)
In the problem description it is not mentioned that element in given array is unique but each array of testcases consists of unique element(non duplicate elements in array) in them.
Also It should also mentioned in question that elements of  `source` and  `target` are same (only order of elements in both the array is different ).

**Comment by LC-Yani** [comment]
Thank you for your time. I have submitted your feedback to update the problem.  We appreciate your support!
