### ISSUE TITLE
822.Card Flipping Game [Description typo]

### ISSUE THREAD

**Issue by Nuno-Dev** [LeetCode-Feedback/LeetCode-Feedback#7131]
#### Your LeetCode username

nunodev

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typo in the problem description:

Return the smallest good **and** integer after flipping the cards. If there are no good integers, return 0.

should be:

Return the smallest good integer after flipping the cards. If there are no good integers, return 0.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
