### ISSUE TITLE
1155. Number of Dice Rolls With Target Sum [Description Typo]

### ISSUE THREAD

**Issue by Nuno-Dev** [LeetCode-Feedback/LeetCode-Feedback#7132]
#### Your LeetCode username

nunodev

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Problem description has 3 typos:

You have n _**dice**_ and each _**die**_ has k faces numbered from 1 to k.
Given three integers n, k, and target, return the number of possible ways (out of the kn total ways) to roll the _**dice**_ so the sum of the face-up numbers equals target. Since the answer may be too large, return it modulo 109 + 7.

should be:

You have n **dices** and each **dice** has k faces numbered from 1 to k.
Given three integers n, k, and target, return the number of possible ways (out of the kn total ways) to roll the **dices** so the sum of the face-up numbers equals target. Since the answer may be too large, return it modulo 109 + 7.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us.
die is the singular of dice.
