### ISSUE TITLE
803. Bricks Falling When Hit | Solution complexity analysis mistake

### ISSUE THREAD

**Issue by RuS2m** [LeetCode-Feedback/LeetCode-Feedback#7133]
#### Your LeetCode username

RuS2m

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

**TL;DR**
In the solution of problem [803. Bricks Falling When Hit](https://leetcode.com/problems/bricks-falling-when-hit/solution/) time complexity analysis is incorrect, instead of **O(NQ*alpha(N*Q))** it should be **O((N+Q) * alpha(N))**.

**More detailed explanation:**
According to _Disjoint-Set-Union (DSU)_ data structure [definition](https://cp-algorithms.com/data_structures/disjoint_set_union.html) the amortized complexity time of any operation in _DSU_ is **O(alpha(N))**, where **N** is number of elements and **alpha** is _reversed Ackerman function_.
In the solution of the problem we are using _DSU_ data structure, slightly modified, so now beside the rank it keeps the size of each union, therefore it doesn't affect operation time. Number of elements on which we are running the _DSU_ is equal to number of bricks in the grid (let's say it's our **N**). Number of operations that was used is **O(N)** union operations for _DSU_ construction on the first place and then in addition for each brick in hits array (let's say size of hits array is **Q**) we are also want to run 4 union operations (for each adjacent brick) and 1 get size operation (in order to get number of bricks, that were fallen after erasing our hits array brick).
Overall number of operations, that were used is **O(N) + 5Q** and their time complexity is **O((N+Q) * alpha(N))**, however in the solution it's **O(NQ*alpha(N*Q))**, which is obviously a mistake that can be easily fixed.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. The time complexity has been updated in a manner similar to what you had suggested. We appreciate your support!
