### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by omaranBazna** [LeetCode-Feedback/LeetCode-Feedback#7135]
#### Your LeetCode username

Omaranbazna

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Solution
#### Description of the bug

Accepting a Solution that does not fit the condition, Time Complexity has to be log(n)

#### Code you used for Submit/Run operation

```
var findPeakElement = function(nums) {
   let a,b,c;
    if(nums.length==1){return 0}
    if(nums[0]>nums[1]){return 0}
    if(nums[nums.length-1]>nums[nums.length-2]){
        return nums.length-1}
    for(let i=1;i<nums.length-1;i++){
        a=nums[i-1];
        b=nums[i];
        c=nums[i+1];
        if(b>a && b>c){
         
            return i;
        }
        
    }
    return -1;
};
```

#### Language used for code

JavaScript

#### Expected behavior

it must show a message that the time complexity is O(n) which is not accepted

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case that you use.
Thank you .
