### ISSUE TITLE
Missing Test Case - 49. Group Anagrams

### ISSUE THREAD

**Issue by vadim-denisov** [LeetCode-Feedback/LeetCode-Feedback#7136]
#### Your LeetCode username
q1munys

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Accepted a solution that may group strings incorrectly. This input fails it: `["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "b"]`

#### Code you used for Submit/Run operation

```
class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        P = 31
        Q = 2**32

        ALPHABET = "abcdefghijklmnopqrstuvwxyz"
        CHAR_TO_INT = {char: idx for idx, char in enumerate(ALPHABET)}
        
        groups = defaultdict(list)
        for s in strs:
            hash_ = 0
            for ch in s:
                hash_ = (hash_ + P**CHAR_TO_INT[ch]) % Q
            groups[hash_].append(s)
        
        return groups.values()

```

#### Language used for code
Python

#### Expected behavior
This solution shouldn't be accepted. Expected output `[["b"],["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"]]`, but got `[["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","b"]]`

#### Additional context
Input: ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "b"]
Output: [["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","b"]]
Expected: [["b"],["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"]]

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
