### ISSUE TITLE
Missing Test Case - 1141. User Activity for the Past 30 Days I

### ISSUE THREAD

**Issue by ishankr21** [LeetCode-Feedback/LeetCode-Feedback#7137]
#### Your LeetCode username 
kumarishaan01 

#### Category of the bug
- [ ] Question
- Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
We have to write a SQL query in which the range of dates is "2019-06-28"  and "2019-07-27"
but the solution is expecting a date from 2021 

#### Code you used for Submit/Run operation

```
 select activity_date as day, count(distinct(user_id)) as active_users from Activity group by  activity_date having activity_date between "2019-06-28"  and "2019-07-27";

```

#### Language used for code
MYSQL

#### Expected behavior
 The date from 2021 should not be in the answer

#### Screenshots

![2](https://user-images.githubusercontent.com/53378786/165660221-fea13b36-f54f-4465-a243-b03408becadb.png)

![1](https://user-images.githubusercontent.com/53378786/165660252-16648ad9-f4e0-4f5d-8eca-68e0e7932bb3.png)

**Comment by KOrfanakis** [comment]
I have the same issue! Thanks a lot for raising it, @ishankr21

**Comment by Applethree** [comment]
> 

I had the same issue with MSSQL, I changed to MYSQL and it accepted. You can try it to keep the progress

**Comment by KOrfanakis** [comment]
Update: the issue was fixed for me and I was able to submit my solution. Thanks a lot to the LeetCode team for fixing it :)
