### ISSUE TITLE
A typo in solution [Problem 1631. Path With Minimum Effort]

### ISSUE THREAD

**Issue by boqigao** [LeetCode-Feedback/LeetCode-Feedback#7138]
#### Your LeetCode username

boqi

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hello, I just want to report a typo in the following solution.
https://leetcode.com/problems/path-with-minimum-effort/solution/

In Approach 4, it should be `Breadth First Search` in the following statement: 
`we use Breath First Search traversal.`

#### Screenshots

![image](https://user-images.githubusercontent.com/42335852/165696531-afbca2f7-3da9-4d27-939e-625d4527a9c4.png)

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
