### ISSUE TITLE
Missing Test Case - 284. Peeking Iterator

### ISSUE THREAD

**Issue by Catalin2341** [LeetCode-Feedback/LeetCode-Feedback#7139]
#### Your LeetCode username

Catalin_DB

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I noticed that the iterator provided as parameter for the PeekingIterator function is an empty object;

#### Code you used for Submit/Run operation

```
var PeekingIterator = function(iterator) {
    console.log(iterator)
    /// empty object 
    /// TypeScript structure = {data: Array, index: number}
    this.state = {
        arr: iterator,
        index: 0
    }
};

PeekingIterator.prototype.peek = function() {
    return this.state.arr[this.state.index+1]
};

PeekingIterator.prototype.next = function() {
    this.state.index++;
    return this.state.arr[this.state.index-1];
};

PeekingIterator.prototype.hasNext = function() {
    if(this.state.arr?.[this.state.index+1] === undefined){
        return false;
    }
    return true;
};
```

#### Language used for code

JavaScript

#### Expected behavior

I was supposed to get some data from "iterator", but instead I received an empty object which resulted in me being unable to solve the problem using JavaScript.

#### Screenshots

![image](https://user-images.githubusercontent.com/79571811/165699357-cc970395-3610-4f03-855d-6996dd7d816d.png)

#### Additional context

I have tested the TypeScript version of this problem and noticed that the iterator object has data in it.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
