### ISSUE TITLE
466. Count The Repetitions

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#714]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Approach 1: Brute force [Time Limit Exceeded] has incorrect description.
 
#### Code you used for Submit/Run operation

```
int getMaxRepetitions(string s1, int n1, string s2, int n2)
{
    int index = 0, repeat_count = 0;
    int s1_size = s1.size(), s2_size = s2.size();
    for (int i = 0; i < n1; i++) {
        for (int j = 0; j < s1_size; j++) {
            if (s1[j] == s2[index])
                ++index;
            if (index == s2_size) {
                index = 0;
                ++repeat_count;
            }
        }
    }
    return repeat_count / n2;
}
```

#### Language used for code

C++

#### Expected behavior

It doesn't TLE and submission is accepted.

#### Screenshots

<img width="400" alt="Capture" src="https://user-images.githubusercontent.com/7014697/88492095-2c474d80-cf5d-11ea-977d-ddf1e0130721.PNG">

**Comment by lc-ivan** [comment]
Hi @agatagruza ,
Thank you for reaching out to us. After reviewing and testing the code you provided on our end, we have received TLE multiple times after submitting (please see attached). Please note that **running code from a test case only tests that one test case** whereas **submitting the code tests all tests cases resulting in TLE**. If you have received a different outcome (such as Accepted) when **submitting** the code, please attach those images to this ticket and we will review as soon as possible!

![Screen Shot 2020-07-31 at 2 18 41 PM](https://user-images.githubusercontent.com/68418560/89078197-c1b95780-d338-11ea-9b8f-a36d6f71f35b.png)

**Comment by agatagruza** [comment]
Hi @lc-ivan I fundamentally misunderstood when TLE occurs. My understanding was it happens when you are running a test case.  Whereas I should be testing when you are submitting the code. My apology.

**Comment by lc-ivan** [comment]
No worries, happy to clarify! Happy LeetCoding!
