### ISSUE TITLE
Improper Constraints - 1675. Minimize Deviation in Array

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7140]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [1675. Minimize Deviation in Array](https://leetcode.com/problems/minimize-deviation-in-array), the current constraints are improper. The reasons are as follows.
1. Let n be the length of array `nums` and let m be the maximum element in array `nums`. I believe the expected time complexity for this problem is O(n * log n * log m). However, since the maximum value of n is 10<sup>5</sup> and the maximum value of m is 10<sup>9</sup>, it is possible to create a test case such that the total number of operations exceeds the allowed maximum number of operations, causing TLE.
2. Even the standard program doesn't have an output for some test cases.
Consider the following test case where the array has 10<sup>5</sup> elements and all elements are 2<sup>29</sup> = 536870912:
[1675 (100000).txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8581185/1675.100000.txt)
By adding a few more lines of code, my code below can pass this test case without TLE. However, the standard program does not provide an output. Please refer to the first screenshot below.
If the length of array is reduced by half, which means the length of array is reduced to 5 * 10<sup>4</sup>, while all elements remain 2<sup>29</sup> = 536870912, then the standard program can provide an output. Please refer to the second screenshot below.
[1675 (50000).txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8581186/1675.50000.txt)
Although Java code can get passed if n is 5 * 10<sup>4</sup>, I'm not sure whether C++ and Python code can get passed with the same time complexity if n is 5 * 10<sup>4</sup>. The maximum values of n and m may need to be further reduced.

Proper constraints must ensure that any test case that meets the constraints won't get TLE using a solution that has an expected time complexity. Further more, the standard program should NOT get TLE for any test case that meets the constraints.

#### Code you used for Submit/Run operation
```Java
class Solution {
    public int minimumDeviation(int[] nums) {
        PriorityQueue<Integer> pq = new PriorityQueue<Integer>((a, b) -> b - a);
        int minNum = Integer.MAX_VALUE;
        for (int num : nums) {
            if (num % 2 != 0) {
                num *= 2;
            }
            pq.offer(num);
            minNum = Math.min(minNum, num);
        }
        int minDeviation = pq.peek() - minNum;
        if (minDeviation == 0) {
            return 0;
        }
        while (pq.peek() % 2 == 0) {
            int num = pq.poll() / 2;
            pq.offer(num);
            minNum = Math.min(minNum, num);
            minDeviation = Math.min(minDeviation, pq.peek() - minNum);
        }
        return minDeviation;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Change the constraints such that the maximum value of n should be 5 * 10<sup>4</sup>, and the maximum value of nums[i] may need to be reduced to 10<sup>8</sup> or 10<sup>7</sup>.

#### Screenshots
The following screenshot is the result of the first test case, where n = 10<sup>5</sup>.
![image](https://user-images.githubusercontent.com/12067364/165716392-e5c601be-9f59-433e-89f8-f05616384d8d.png)

The following screenshot is the result of the second test case, where n = 5 * 10<sup>4</sup>. Note that some lines of code are removed (early return before the while loop), so the runtime is longer than the previous screenshot.
![image](https://user-images.githubusercontent.com/12067364/165716735-a3a620f0-294e-496d-9463-2b8c48c7c01d.png)

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem:

• Updated constraint: n=10^5=> 5 x 10^4
• Since changing max(nums[i]) was not making any significant effect, kept it the same.
• Updated testcases
added the 1675.50000.txt test case, and a couple of other tests
removed testcases with n>5 x 10^4
• A TLE solution in library was incorrect, failed it
• Updated model solution
• Checked all top rated solutions are AC

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 
We appreciate your support!
