### ISSUE TITLE
Missing Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by MJBx-ux** [LeetCode-Feedback/LeetCode-Feedback#7142]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

![image](https://user-images.githubusercontent.com/72027193/165796898-9d1caa35-ed0a-4bb0-beb3-45af186abdc9.png)
This test case should me removed!!
because in the question it mentioned that "There is only one repeated number in nums" but in above test case 2 is repeated 5times

**Comment by stormsunshine** [comment]
Please read the last constraint carefully:
All the integers in `nums` appear only **once** except for **precisely one integer** which appears **two or more** times.
