### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by ytsurkan** [LeetCode-Feedback/LeetCode-Feedback#7145]
#### Your LeetCode username

ytsurkan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Got result 3, for input:
11
[1,2,3,4,5]
Expect result 0.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        if ( nums.empty( ) )
        {
            return 0;
        }
        std::vector< int32_t > indices;
        int32_t sum{ 0 };
        size_t left{ 0 }, right{ 0 }, minLength{ 0 };
        for ( ; right < nums.size( ); ++right )
        {
            sum += nums[ right ];
            while ( left < right && sum > target )
            {
                sum += -nums[ left++ ];
            }
            if ( sum == target )
            {
                const auto length = right - left + 1;
                minLength = minLength == 0u ? length : std::min( minLength, length );
            }
        }
        return static_cast< int32_t >( minLength );
    }
};
```

#### Language used for code
C++

#### Expected behavior

Expected result 0, for input
11
[1,2,3,4,5]

#### Additional context

![leetcode-min-subarray](https://user-images.githubusercontent.com/22916166/165885609-e4c50b29-1619-4fdd-b68b-52292348557d.png)

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
