### ISSUE TITLE
Wrong and Missing Test cases for 1166

### ISSUE THREAD

**Issue by xwshiba** [LeetCode-Feedback/LeetCode-Feedback#7146]
---
name: Bug report (English)
about: Create a bug report to help us improve our content.
title: 'test case missing for 1166'
labels: 'missing test case / wrong test case'
assignees: ''

---

#### Your LeetCode username

xwshiba

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Question [1166. Design File System](https://leetcode.com/problems/design-file-system/)
The description suggests that "For example, "/leetcode" and "/leetcode/problems" are valid paths while an empty string "" and "/" are not."
This means when we input "/" the result should return false instead of true. Currently it's returning true.
Case 1:
```
["FileSystem","createPath"]

[[],["/",1]]
```

Case 2:
```
["FileSystem","createPath","createPath","createPath","get","createPath","get"]
[[],["/leet",1],["/leet/code",2],["/leet/code",2],["/leet/code"],["/c/d",1],["/c"]]
```

#### Code you used for Submit/Run operation

Wrong test case result - 
```
["FileSystem","createPath"]
[[],["/",1]]
```
This below should be included - 
```
["FileSystem","createPath","createPath","createPath","get","createPath","get"]
[[],["/leet",1],["/leet/code",2],["/leet/code",2],["/leet/code"],["/c/d",1],["/c"]]
```

#### Language used for code

Python

#### Expected behavior

Case 1: I think the test case should return `[null, false]` instead of `[null, true]`.
Case 2: This one should be included.

#### Screenshots

![image](https://user-images.githubusercontent.com/64823359/165887852-6f153c68-d796-46f2-bfd8-8bde988c6551.png)

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code you submitted to reach this result.

**Comment by xwshiba** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code you submitted to reach this result.

The code I used to submit as shows below. I did not pass my second test case listed above, but LeetCode granted me a "success".

```
class FileSystem:

    def __init__(self):
        self.root = {}
        

    def createPath(self, path: str, value: int) -> bool:
        curr = self.root
        paths = path.split('/')[1:]
        if len(paths) == 0:
            return False
        
        N = len(paths)
        
        for i in range(N):
            p = paths[i]
            
            if p not in curr and i != N-1:
                return False
            elif p not in curr and i == N-1:
                curr[p] = {}
                curr = curr[p]
                curr['#'] = value
                return True
            curr = curr[p]
        return curr['#'] == value
        

    def get(self, path: str) -> int:
        paths = path.split('/')[1:]
        curr = self.root
        
        for p in paths:
            if p not in curr:
                return -1
            curr = curr[p]
            
        return curr['#']
```

**Comment by LC-Yani** [comment]
Hi there,

Your code failed in Python, but Accepted by Python3, same as your first test case. 
Second test case got wrong answer, will submit to our team to investigate.
![Screen Shot 2022-05-06 at 9 47 13 PM](https://user-images.githubusercontent.com/103138242/167233191-0c1c8512-222e-4f09-83f4-f58ae835a483.png)
