### ISSUE TITLE
Python Typing -- 429 N-ary Tree Level Order Traversal

### ISSUE THREAD

**Issue by mscuthbert** [LeetCode-Feedback/LeetCode-Feedback#7150]
#### Your LeetCode username

msacuthbert

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The skeleton code provided is:

```
class Solution:
    def levelOrder(self, root: 'Node') -> List[List[int]]:
```

However, root is allowed to be `None` not a Node, so the skeleton should be

```
class Solution:
    def levelOrder(self, root: Optional['Node']) -> List[List[int]]:
```

#### Code you used for Submit/Run operation

```
class Solution:
    def levelOrder(self, root: 'Node') -> List[List[int]]:
        print(root.val)
```

#### Language used for code

Python3 

#### Expected behavior

In Python, the typing of `root: 'Node'` implies that root must be a Node object and cannot be None.  This contradicts the constraints of the problem and a hidden test case.  `print (root.val)` should never raise an exception unless root is typed as `Optional['Node']` (or in Python 3.10:  `Node|None`).  Python's behavior with None/null is different from Java/TypeScript.

#### Additional context

There are a number of Python cases where `Optional[Node]` is incorrectly typed as just `Node`.  This was just the first one that bit me.  Someone seems to have already gone through all the `ListNode` problems and typed them as `Optional[ListNode]`: I haven't encountered a problem there yet.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We updated the type hints in the solution article to match what was suggested by you. We appreciate your support!

**Comment by mscuthbert** [comment]
Thanks @LC-Pam :-)
