### ISSUE TITLE
Missing Test Case - 1684. Count the Number of Consistent Strings

### ISSUE THREAD

**Issue by itsAfnanAlam** [LeetCode-Feedback/LeetCode-Feedback#7151]
#### Your LeetCode username
itsAfnanAlam

#### Category of the bug
- [ ] Solution

#### Description of the bug
In  the question, it is mentioned stated that "_A string is consistent if all characters in the string appear in the string `allowed`._" 
but when I submit the code it is considering each `allowed[i]` as consistent.

#### Code you used for Submit/Run operation
```
class Solution {
    public int countConsistentStrings(String allowed, String[] words) {
        int count = 0;
        
        for (int i = 0; i < words.length; i++) {
            if (words[i].contains(allowed)) {
                count++;
            }
        }
        
        return count;
    }
}
```

#### Language used for code
_JAVA_

#### Screenshots

![Screenshot (3)](https://user-images.githubusercontent.com/97395445/165963455-0de7030f-4cf2-4854-8bf9-d1ff2746c337.png)

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
