### ISSUE TITLE
Missing Test Case - 1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit

### ISSUE THREAD

**Issue by pijushcse** [LeetCode-Feedback/LeetCode-Feedback#7152]
#### Your LeetCode username
pijushcse

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Currently, it is accepting a solution for an incorrect outcome. 

#### Code you used for Submit/Run operation

```
    static int longestSubarray(int[] nums, int limit) {
        //Sliding window
        if (nums.length == 1) return 1;

        int size = 2;
        PriorityQueue<Integer> minQ = new PriorityQueue<>();
        PriorityQueue<Integer> maxQ = new PriorityQueue<>(Collections.reverseOrder());
        minQ.add(nums[0]);
        maxQ.add(nums[0]);

        int min = 0;
        int max = 0;

        for (int i = 0, j = i + 1; j < nums.length; ) {
            minQ.add(nums[j]);
            maxQ.add(nums[j]);
            min = minQ.peek();
            max = maxQ.peek();
            if (Math.abs(max - min) <= limit) {
                j++;
                size = Math.max(size, j - i);

            } else {
                minQ.remove(nums[i]);
                maxQ.remove(nums[i]);
                i++;
                j++;
            }
        }
        return size;
    }
```

#### Language used for code
Java

#### Expected behavior
For a given test case- ```[100, 50], 10 ```  expected output is ```1```. However, the above code is producing output ```2``` and online judge is accepting the solution.   

#### Additional context
I think test cases needs to be updated.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the code has compile error when we test it, please feel free to optimized your code or send us your Accepted link. Thank you.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
