### ISSUE TITLE
Incorrect Test Case - 1141. User Activity for the Past 30 Days I

### ISSUE THREAD

**Issue by human-doodle** [LeetCode-Feedback/LeetCode-Feedback#7155]
#### Your LeetCode username
 human-doodle

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Test Case - 13 Incorrect : Test Case output expects dates later than 2019-07-27 whereas question explicitly mentions to find the daily active user count for a period of 30 days ending 2019-07-27 inclusively.

#### Code you used for Submit/Run operation

```
SELECT activity_date AS day, COUNT(DISTINCT(user_id)) as active_users
FROM Activity
WHERE activity_date BETWEEN DATEADD(day, -(30-1), '2019-07-27' ) AND '2019-07-27'
GROUP BY activity_date
```

#### Language used for code

MS SQL SERVER

#### Expected behavior

Expected Output should have been:
{"headers": ["day", "active_users"], "values": [["2019-07-20", 2], ["2019-07-21", 2]]}
INTEAD OF :
{"headers": ["day", "active_users"], "values": [["2019-07-20", 2], ["2019-07-21", 2], ["2019-08-25", 1], ["2021-08-25", 1]]}

#### Screenshots

![image](https://user-images.githubusercontent.com/46643099/166006064-048e9f83-0765-42c7-8e76-ec12f46dd27e.png)

**Comment by LC-Yani** [comment]
Hi @,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case that you use.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by human-doodle** [comment]
Hi, 

As mentioned, the expected output showing is incorrect for the test-case 13.

The test case  13 input is as follows:  

{"headers":{"Activity":["user_id","session_id","activity_date","activity_type"]},"rows":{"Activity":[[1,1,"2019-07-20","open_session"],[1,1,"2019-07-20","scroll_down"],[1,1,"2019-07-20","end_session"],[2,4,"2019-07-20","open_session"],[2,4,"2019-07-21","send_message"],[2,4,"2019-07-21","end_session"],[3,2,"2019-07-21","open_session"],[3,2,"2019-07-21","send_message"],[3,2,"2019-07-21","end_session"],[4,3,"2019-08-25","open_session"],[4,3,"2021-08-25","end_session"]]}}

The expected Outpud showing is:
{"headers": ["day", "active_users"], "values": [["2019-07-20", 2], ["2019-07-21", 2], ["2019-08-25", 1], ["2021-08-25", 1]]}

which invludes values:   ["2019-08-25", 1], ["2021-08-25", 1] which isn't what the question expects.

**Comment by LC-Yani** [comment]
Hi there,

Would you mind sending me your Accepted Code link? Because when we test your code, we received Wrong Answer on your code, not test case.

Thank you

**Comment by human-doodle** [comment]
Hello,

My code wasn't accepted because test case 13 didn't pass since* the test
case is incorrect*.

Here's my code:




*SELECT activity_date AS day, COUNT(DISTINCT(user_id)) as active_usersFROM
ActivityWHERE activity_date BETWEEN DATEADD(day, -(30-1), '2019-07-27' )
AND '2019-07-27'GROUP BY activity_date*

Here's the screenshot:

[image: image.png]

Various other users have also pointed out this error in the discussion
forum:
https://leetcode.com/problems/user-activity-for-the-past-30-days-i/discuss/1991598/Test-Case-13-Wrong
<goog_1116622792>
https://leetcode.com/problems/user-activity-for-the-past-30-days-i/discuss/1988521/%22Expected-output%22-for-test-case-13-is-incorrect
<goog_1116622792>
https://leetcode.com/problems/user-activity-for-the-past-30-days-i/discuss/2007829/Test-Case-Wrong

Let me know if you need any other information.

Best,
Shivani Pal

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Hi there, we tried the test case with the solution and it is AC. This test case does not fail the provided solution.
https://leetcode.com/submissions/detail/701704561/
![Screen Shot 2022-05-17 at 6 23 27 PM](https://user-images.githubusercontent.com/103138242/168922126-c07d388a-da96-43f5-a0e1-253d2066bf21.png)
