### ISSUE TITLE
Missing Test Case - 785. Is Graph Bipartite?

### ISSUE THREAD

**Issue by nizarkadri** [LeetCode-Feedback/LeetCode-Feedback#7157]
#### Your LeetCode username

nizarkadri

#### Category of the bug
- Question
- [  ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question : 785. Is Graph Bipartite?
In  first example:
![image](https://user-images.githubusercontent.com/33659282/166087709-fcddbafa-1aaf-41e4-bb9e-4636b8eb9a3c.png)
solution can be set A = {0} and set B = {1,2,3}
if this is not considered as solution then it should be mentioned in question that both sets should be of equal size or there cannot be a singular set

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
In a bipartite graph, all nodes can be divided into two groups A and B such that for each edge, the two nodes connected by this edge are from different groups.

In this example, If you divide the nodes into A = {0} and B = {1, 2, 3}, then the edges [1, 2] and [2, 3] connect nodes from the same group, so it does not meet the requirement of a bipartite graph.
