### ISSUE TITLE
878. Nth Magical Number

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#716]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

There is a typo in Approach 2: Binary Search with respect to an explanation of the problem.  In the algorithm's description it is started `Without loss of generality, suppose A≥B`. However when calculating: min(A,B) = A.  For min(A,B) = A to be True, it needs to be A<=B.

#### Expected behavior

Changing ` A≥B` to `A<=B` should solve the problem.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @agatagruza , Thanks for the time. The team has reviewed your report but considered this report invalid. A >= B is used later as A >= min(A, B).

**Comment by agatagruza** [comment]
Thank you @lc-pam for an update.
