### ISSUE TITLE
175题 组合两个表 翻译错误

### ISSUE THREAD

**Issue by Craftsman98** [LeetCode-Feedback/LeetCode-Feedback#7160]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
[Craftsman98](https://leetcode-cn.com/u/craftsman98/)

**Bug 类型**
- [x] 题目

**描述**
175题 组合两个表 翻译错误

英文：
Write an SQL query to report the first name, last name, city, and state of each person in the Person table. 

中文：
编写一个SQL查询来报告 Person 表中每个人的姓、名、城市和状态。

**期望行为**

因为SQL表中的“state”明显指的是地理意义上所在的州，而不是这个人的“状态”。

应该翻译成：
编写一个SQL查询来报告 Person 表中每个人的姓、名、城市和州。

**屏幕截图**
<img width="532" alt="image" src="https://user-images.githubusercontent.com/38043100/166089208-2418c5eb-574d-4c01-a783-9e9511289aac.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/38043100/166089215-f8164c19-4ef7-43a3-ad07-2e5e1af1c95d.png">

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目描述已更新，ID：craftsman98 给予积分奖励，请查收。
