### ISSUE TITLE
Giving Wrong Output- 191. Number of 1 Bits

### ISSUE THREAD

**Issue by AyanSatt** [LeetCode-Feedback/LeetCode-Feedback#7162]
#### Your LeetCode username
201ayansatt

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In the 315th test case, it's giving the wrong output but my logic is correct. 
Input
11111111111111111111111111111101
Output
30
Expected
31
#### Code you used for Submit/Run operation

```
class Solution {
public:
    int hammingWeight(uint32_t n) {
        int mask=1,count=0;
        while(mask>0){
            if(n&mask) count++;
            mask=mask<<1;
        }
        return count;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

 In the 315th test case it should give 31 as output but it gives 30 as output so that's the problem. 

#### Screenshots

 ![Screenshot (18)](https://user-images.githubusercontent.com/72308147/166092216-1cbde5c6-fef8-4a85-ac8a-4e2d98117fbc.png)

**Comment by stormsunshine** [comment]
Your code is incorrect and returns 30 for this test case. The expected answer is indeed 31.

**Comment by AyanSatt** [comment]
> Your code is incorrect and returns 30 for this test case. The expected answer is indeed 31.

My code is correct because, when I run the same code in a different platform at the time it gives the correct output as 31 but in the leetcode compiler, it gives 30 as output.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
