### ISSUE TITLE
580. 统计各专业学生人数 执行出错'Student'

### ISSUE THREAD

**Issue by Tegrisco** [LeetCode-Feedback/LeetCode-Feedback#7164]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Studyandmiii

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
代码执行后报错提示模糊，只显示'Student'

**你使用的语言**
mysql

**你提交或者运行的代码**
```
select a.dept_name, count(b.student_id) as student_number
from department a left join Student b
on a.dept_id = b.dept_id
group by a.dept_id
order by student_number, a.dept_name;
```

**期望行为**
修复bug或者显示明确报错
**屏幕截图**
![IMG_0810](https://user-images.githubusercontent.com/31361944/166098980-e10fc24f-ed38-4402-8512-6eece409f84c.PNG)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目问题已更新，ID：Studyandmiii 给予积分奖励，请查收。
