### ISSUE TITLE
626. 换座位 执行出错'Seat'

### ISSUE THREAD

**Issue by Tegrisco** [LeetCode-Feedback/LeetCode-Feedback#7166]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Studyandmiii

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
代码执行报错信息模糊

**你使用的语言**
mysql

**你提交或者运行的代码**
```
from seat a, (select case when id=(select count(*) from seat) and id%2=1 then id
    else if(id%2=0,id-1,id+1) end as id, student from seat) b
where a.id=b.id
;
```

**期望行为**
修复bug或者显示明确的报错信息

**屏幕截图**
![image](https://user-images.githubusercontent.com/31361944/166100360-a4235d5d-a816-462a-8622-42c1b141c4ba.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：Studyandmiii 给予积分奖励，请查收。
