### ISSUE TITLE
Missing Test Case - 399. Evaluate Division

### ISSUE THREAD

**Issue by Jeevier** [LeetCode-Feedback/LeetCode-Feedback#7167]
#### Your LeetCode username

https://leetcode.com/sanyamjain10168/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

It is mention in the question that "_**The input is always valid. You may assume that evaluating the queries will not result in division by zero and that there is no contradiction.**_"
Also, it is mention  that "**_If a single answer cannot be determined, return ```-1.0```_** ". 
But, it contradicts a fact that input is always valid. Also, compiler takes wrong input and code get compiled without showing a error of wrong input. Answer is valid when there is only one path from source to destination. If there is more than one path then it is a wrong input. Language is somewhat confusing that if we have to handle a case of more than one path by returning ```-1.0``` or not.

#### Code you used for Submit/Run operation

```
class Solution {
    unordered_map<string, vector<pair<string, double>>> adjList;
    unordered_map<string, bool> visited;
    double queryAns;
public:
    
    bool dfs(string startNode, string endNode, double runningProduct){
        
        if(startNode == endNode and adjList.find(startNode)!=adjList.end()) {
            queryAns = runningProduct;
            return true;
            
        }
        
        bool tempAns = false;
        visited[startNode] = true;
        
        for(int i = 0; i < adjList[startNode].size(); i++){
            if(!visited[adjList[startNode][i].first]){
                tempAns = dfs(adjList[startNode][i].first, endNode, runningProduct*adjList[startNode][i].second);
                if(tempAns){
                    break;
                }
            }
        }
        
        visited[startNode] = false;
        
        return tempAns;
        
    }
    
    vector<double> calcEquation(vector<vector<string>>& equations, vector<double>& values, vector<vector<string>>& queries) {
        
        
        int n = equations.size(), m = queries.size();
        vector<double> ans(m);
        
        for(int i = 0; i < n ; i++){
            
            adjList[equations[i][0]].push_back({equations[i][1], values[i]});
            adjList[equations[i][1]].push_back({equations[i][0], 1/values[i]});
            visited[equations[i][0]] = false;
            visited[equations[i][1]] = false;

        }
        
        for(int i = 0; i < m ; i++){
            
            queryAns = 1;
            bool pathFound = dfs(queries[i][0], queries[i][1], 1);            
            if(pathFound) ans[i] = queryAns;
            else ans[i] = -1;
            
        }
        
        return ans;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

Compiler should show Wrong Input Error , if we give wrong input considering that input is always valid.
Language should be much more clear, which properly states if we have to handle a case of more than one path by returning ```-1.0``` or not.

#### Screenshots

<img width="577" alt="Screenshot 2022-04-30 at 5 58 12 PM" src="https://user-images.githubusercontent.com/75247883/166105596-a8fcf391-722e-4313-8667-6f778cecf23d.png">

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Updated validator. We appreciate your support!
