### ISSUE TITLE
Wrong Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by 4rund3v** [LeetCode-Feedback/LeetCode-Feedback#7168]
#### Your LeetCode username

4rund3v

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Given Test case output is wrong
Question : 523. Continuous Subarray Sum

Test case Info : 
Input :: [23,2,4,6,6] -> 7
Expected Output  (wrong) : true
Actual Output (right): false

#### Code you used for Submit/Run operation

```
class Solution:
    def checkSubarraySum(self, nums: List[int], k: int) -> bool:
        start = 0
        end = 1
        flag = False
        current_sum = k
        for i in range(len(nums)):
            current_sum -= nums[i]
            while current_sum < 0:
                current_sum += nums[start]
                start += 1
            if current_sum == 0:
                flag = True
                break
            end +=1
        return flag
```

#### Expected behavior

Logic is invalid, might be just an error. Cant get 7 from the given array.

#### Screenshots

![image](https://user-images.githubusercontent.com/17854074/166107995-8417babc-a03d-40c3-8080-307ddfe497b5.png)

**Comment by stormsunshine** [comment]
Why do you think the output should be false? There exists a subarray [23,2,4,6] where the sum of elements is 35, which is a multiple of 7.

**Comment by 4rund3v** [comment]
![image](https://user-images.githubusercontent.com/17854074/166109829-abf66e19-ea30-4746-aff7-890d8c1e145b.png)
Missed the part of the multiple, even after reading the question multiple times.
Mybad.
Will close the issue.
