### ISSUE TITLE
Test case is wrong

### ISSUE THREAD

**Issue by MSS023** [LeetCode-Feedback/LeetCode-Feedback#7169]
#### Your LeetCode username
 manansahni567

#### Category of the bug
- [x] Question
- [x] Solution

#### Description of the bug
There is one testcase with input values as [["a","b"],["b","c"]]
[2.0,3.0]
[["a","c"],["b","a"],["a","e"],["a","a"],["x","x"]]

Its output is given as [6.00000,0.50000,-1.00000,1.00000,-1.00000]

The output should be [6.00000,0.50000,-1.00000,1.00000,1.00000]
because if a number is divided by itself then it yields 1 irrespective of its presence in equations array.

the correct python3 code is given below

#### Code you used for Submit/Run operation

```
// Two Sum Python3
class Solution:
    def calcEquation(self, equations: list[list[str]], values: list[float], queries: list[list[str]]) -> list[float]:
        diction={}
        for index,i in enumerate(equations):
            if i[0] not in diction:
                diction[i[0]]=[]
            if i[1] not in diction:
                diction[i[1]]=[]
            diction[i[0]].append([i[1],values[index]])
            diction[i[1]].append([i[0],1/values[index]])
        def dfs(edges,start,end,passed):
            stack=[]
            if start in edges:
                for num,value in edges[start]:
                    if num in passed:
                        continue
                    stack.append([num,value])
            temp=1
            while stack:
                num,value=stack.pop()
                temp=value
                if num in passed:
                    continue
                if num==end:
                    return [True,temp]
                flag,retvalue=dfs(edges,num,end,passed+[num])
                if not flag:
                    continue
                return [flag,temp*retvalue]
            return [False,-1]
        res=[]
        for a,b in queries:
            if a==b:
                res.append(1)
                continue
            if a not in diction or b not in diction:
                res.append(-1)
                continue
            flag,answer=dfs(diction,a,b,[a])
            if flag:
                diction[a].append([b,answer])
                diction[b].append([a,1/answer])
            res.append(answer)
            continue
        return res

```

#### Language used for code
 Python3

#### Expected behavior

The result on the input 
[["a","b"],["b","c"]]
[2.0,3.0]
[["a","c"],["b","a"],["a","e"],["a","a"],["x","x"]]

should be
[6.00000,0.50000,-1.00000,1.00000,1.00000]

instead of
[6.00000,0.50000,-1.00000,1.00000,-1.00000]

#### Additional context

It is a simple mathematical rule that if a real number is divided by itself then this division yields an answer 1 irrespective of its value.

**Comment by LC-Yani** [comment]
Hi @,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by MSS023** [comment]
#399 Evaluate Division

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
