### ISSUE TITLE
1531. String Compression II

### ISSUE THREAD

**Issue by zzzyq** [LeetCode-Feedback/LeetCode-Feedback#717]
#### Your LeetCode username
zzzyq

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing test cases. My solution get accepted but actually it should get failed on some corner cases. Probably LeetCode should add these corner cases or modify the constraints of this problem.

In the case: 
String s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"(100 same characters), k = 0
Th expect output should be 4. My code gives the output as 3 but it still gets accepted. 

I think my solution only works when s.length < 100 but the given constrain is 1<= s.length <= 100. LeetCode probably should test more on cases of s.length = 100 or modify the constraints to 1 <= s.length < 100.

#### Code you used for Submit/Run operation

```
// 1531. String Compression II
class Solution {
    public int getLengthOfOptimalCompression(String s, int k) {
        int n = s.length();
        int[] arr = new int[n];
        for(int i = 0; i < n; i++) {
            arr[i] = s.charAt(i) - 'a';
        }
        int[][][][] memo = new int[n][26][11][k + 1];
        for(int[][][] temp1 : memo) {
            for(int[][] temp2 : temp1) {
                for(int[] temp3 : temp2) Arrays.fill(temp3, -1);
            }
        }
        int res = helper(0, -1, 0, k, arr, memo);
        return res;
    }
    
    private int helper(int idx, int prev, int prevCnt, int k, int[] arr, int[][][][] memo) {
        if(idx >= arr.length) return 0;
        if(prevCnt >= 10) prevCnt = 10;
        if(prev != -1 && memo[idx][prev][prevCnt][k] != -1) return memo[idx][prev][prevCnt][k];
        int res = 10000;
        if(k > 0) res = Math.min(res, helper(idx + 1, prev, prevCnt, k - 1, arr, memo));
        int c = arr[idx];
        if(c == prev) {
            if(prevCnt == 1 || prevCnt == 9) {
                res = Math.min(res, 1 + helper(idx + 1, prev, prevCnt + 1, k, arr, memo));
            } else {
                res = Math.min(res, helper(idx + 1, prev, prevCnt + 1, k, arr, memo));
            }
        } else {
            res = Math.min(res, 1 + helper(idx + 1, c, 1, k, arr, memo));
        }
        if(prev != -1) memo[idx][prev][prevCnt][k] = res;
        return res;
        
    }
}
```

#### Language used for code
Java

#### Expected behavior
My solution should get failed with"Wrong Answer" because of the example case I mentioned above.

#### Screenshots
<img width="1916" alt="Screen Shot 2020-07-26 at 10 56 06 PM" src="https://user-images.githubusercontent.com/25068557/88502179-4ac83b80-cf93-11ea-87fc-2d9ee83ca489.png">
<img width="1919" alt="Screen Shot 2020-07-26 at 10 58 20 PM" src="https://user-images.githubusercontent.com/25068557/88502263-8531d880-cf93-11ea-9c86-c6b1f94d0ffa.png">

**Comment by lc-pam** [comment]
Hi @zzzyq 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @zzzyq 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
