### ISSUE TITLE
Missing Test Case - 695. Max Area of Island

### ISSUE THREAD

**Issue by adhishmeena** [LeetCode-Feedback/LeetCode-Feedback#7171]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

for 
when I am submitting my code for this test case input : [[0,0,0,0,0,0,0,0]]
it shows that my answer is wrong , and when I ran my code with this custom test case then it is running fine , I just request you to please look why is it failling when I am submitting code for this test case 

find the underlying image for better understanding. 

![image](https://user-images.githubusercontent.com/43376969/166116539-b43c7c7f-59a9-4fb0-b4f8-009abc154351.png)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Yani** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
