### ISSUE TITLE
Incorrect Test Case - 744. Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by chndnchugh** [LeetCode-Feedback/LeetCode-Feedback#7177]
#### Your LeetCode username

[Chandan_Chugh](https://leetcode.com/Chandan_Chugh/)

#### Category of the bug
- [] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 744. Find Smallest Letter Greater Than Target

class Solution:
    def nextGreatestLetter(self, letters: List[str], target: str) -> str:
        
        alp = { "a": 1, "b": 2, "c": 3, "d": 4, "e": 5, "f": 6, 
          "g": 7, "h": 8, "i": 9, "j": 10, "k": 11, "l": 12,
          "m": 13, "n": 14, "o": 15, "p": 16, "q": 17, "r": 18, 
          "s": 19, "t": 20, "u": 21, "v": 22, "w": 23, "x": 24, 
           "y": 25, "z": 26              
        }
        
        key_list = list(alp.keys())
        print(key_list)
        val_list = list(alp.values())
        print(val_list)
     
        number = float(inf)
        letters.sort()

        for let in letters:
            # print(let)
            
            if alp[let] > alp[target]:
                print(alp[let])
                number = alp[let]
                # print(number)
                break
            elif alp[let] == alp[target]:
                number = alp[target]
                break
        print(number)
        position = val_list.index(number)
        
        return key_list[position]
                    
                    
                    
                    
```

#### Language used for code

Python 3

#### Expected behavior

The problem asks to return the smallest character in the array that is larger than target.

The test case 

**["c","f","j"]
"j"**

The test returns "c" as the correct answer. I think "c" is not greater than "j"

Is this test case incorrect? 

Thank you!

#### Screenshots

![image](https://user-images.githubusercontent.com/49587501/166141430-92c4ad5c-ed68-4293-b32e-c2d2446267c3.png)

**Comment by stormsunshine** [comment]
Please read the problem description carefully to see that the letters wrap around.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
