### ISSUE TITLE
Typo of Question - 1084. Sales Analysis III

### ISSUE THREAD

**Issue by Roha-Lee** [LeetCode-Feedback/LeetCode-Feedback#7179]
#### Your LeetCode username

Roha-Lee

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question said "spring of 2019. That is, between 2019-01-01 and 2019-03-31 inclusive", However, actual spring is March, April, May, that is between 2019-03-01 and 2019-05-31 inclusive

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
