### ISSUE TITLE
50. Pow(x, n) - failing test case

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#718]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Provided solution Approach 2: Fast Power Algorithm Recursive is failing in the following test case:
`x = 2.0` 
`n = 100` 
Output of the solution is:
`1267650600228229400000000000000.00000`

Expected answer should be:
`1267650600228229401496703205376.00000`

#### Code you used for Submit/Run operation

```
class Solution {
    private double fastPow(double x, long n) {
        if (n == 0) {
            return 1.0;
        }
        double half = fastPow(x, n / 2);
        if (n % 2 == 0) {
            return half * half;
        } else {
            return half * half * x;
        }
    }
    public double myPow(double x, int n) {
        long N = n;
        if (N < 0) {
            x = 1 / x;
            N = -N;
        }

        return fastPow(x, N);
    }
};
```

#### Language used for code

Java

#### Expected behavior

Suggestion is not to accept a wrong input or implement a fix that accepts provided input.  

#### Screenshots

<img width="330" alt="Capture" src="https://user-images.githubusercontent.com/7014697/88503516-cf608d00-cf86-11ea-931a-66737046732c.PNG">

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
