### ISSUE TITLE
1597. 根据中缀表达式构造二叉表达式树 数据范围有误

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#7181]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
hqztrue

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
题目中数据范围为1 <= s.length <= 10^5。但实际限制为s.length <= 100。提交如下数据测试时显示"expected 's' to have 1 <= size <= 100 but got 223".
"1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1"
![image](https://user-images.githubusercontent.com/11583428/166176158-b1ba82b9-648e-40a2-ad39-f26280540627.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by feiceh** [comment]
你好，提示中的数据范围已调整， ID：hqztrue 给予积分奖励，请查收。

**Comment by hqztrue** [comment]
但是现在这个字号好奇怪啊
![image](https://user-images.githubusercontent.com/11583428/167057473-44631332-ca70-4c08-808c-121104b9e11b.png)
