### ISSUE TITLE
603. 连续空余座位 执行出错'Cinema'

### ISSUE THREAD

**Issue by Tegrisco** [LeetCode-Feedback/LeetCode-Feedback#7182]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Studyandmiii

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
执行代码出错提示模糊： 'Cinema'

**你使用的语言**
mysql

**你提交或者运行的代码**
```
select seat_id from Cinema
where seat_id+1 in (select seat_id from cinema where free=1)
or seat_id-1 in (select seat_id from cinema where free=1)
;
```

**期望行为**
修复bug或者显示明确报错

**屏幕截图**
![image](https://user-images.githubusercontent.com/31361944/166178567-e88ffc46-78b5-4579-bbf4-f939a066e6b1.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：Studyandmiii  给予积分奖励，请查收。
