### ISSUE TITLE
两数相加

### ISSUE THREAD

**Issue by 8527zz** [LeetCode-Feedback/LeetCode-Feedback#7183]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
class Solution {
    public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
        int sum = 0;
        int next1 = 0;
       ListNode result = new ListNode(0);
        ListNode cur = result;
        while(l1!=null && l2!=null){
            sum = l1.val+l2.val+next1;
            cur.next = new ListNode(sum%10);
            next1 = sum/10;
            l1 = l1.next;
            l2 = l2.next;
            cur = cur.next;
        }
        while(l1!=null){
            sum = l1.val+next1;
            cur.next = new ListNode(sum%10);
            next1 = sum/10;
            l1 = l1.next;
            cur = cur.next;
        }
        while(l2!=null){
            sum = l2.val+next1;
            cur.next = new  ListNode(sum%10);
            next1 = sum/10;
            l2 = l2.next;
            cur = cur.next;
        }
        if(next1 != 0){
           cur.next = new ListNode(1);
        }
        return result.next;
    
    }
}

**Comment by zerotrac** [comment]
1. 这份代码是 Java 不是 C++
2. 请详细描述你遇到的问题

**Comment by feiceh** [comment]
Hello～为了更好地定位问题，还请将出现问题的详细情况反馈至我们，我们在收到你的回复后会尽快与你跟进。
后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
