### ISSUE TITLE
Incorrect Constraint - 1597. Build Binary Expression Tree From Infix Expression

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7184]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [1597. Build Binary Expression Tree From Infix Expression](https://leetcode.com/problems/build-binary-expression-tree-from-infix-expression), the following test case is not allowed in custom test case, saying "expected 's' to have 1 <= size <= 100 but got 223". However, the first constraint is `1 <= s.length <= 1000`.

The constraints in problem description should be consistent with the actual constraints, so the first constraint should be changed to `1 <= s.length <= 100`.
```
"1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1"
```

#### Code you used for Submit/Run operation
```C++
class Solution {
private:
    stack<Node*> nums;
    stack<char> ops;

    int Priority(char& c)
    {
        if (c == '(')
        {
            return 4;
        }
        else if (c == '*' || c == '/')
        {
            return 3;
        }
        else if (c == '+' || c == '-')
        {
            return 2;
        }
        else
        {
            return 1;
        }
    }

    void PopOps()
    {
        Node* right = nums.top();
        nums.pop();
        Node* left = nums.top();
        nums.pop();
        Node* root = new Node(ops.top(), left, right);
        ops.pop();
        nums.push(root);
    }

public:
    Node* expTree(string s) {
        for (char c : s)
        {
            if (c >= '0' && c <= '9')
            {
                nums.push(new Node(c));
            }
            else
            {
                if (ops.empty() || Priority(ops.top()) < Priority(c))
                {
                    ops.push(c);
                }
                else
                {
                    while (!ops.empty() && ops.top() != '(' && Priority(ops.top()) >= Priority(c))
                    {
                        PopOps();
                    }
                    
                    if (c != ')')
                    {
                        ops.push(c);
                    }
                    else
                    {
                        ops.pop();
                    }
                }
            }
        }

        while (!ops.empty())
        {
            PopOps();
        }

        return nums.top();
    }
};
```

#### Language used for code
C++

#### Expected behavior
Change the first constraint to `1 <= s.length <= 100`.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/166182289-72af81cc-cdc9-4f17-a631-7066944f470a.png)

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
