### ISSUE TITLE
Incomplete problem description - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#7185]
#### Your LeetCode username

roll_no_1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description doesn't tell what to return if the answer doesn't exist. Consider this input ["weitong", 2]

#### Code you used for Submit/Run operation

```
class Solution { 
    bool check(unordered_map<char, int>& cnt, int k) {
        for (auto& [c, num] : cnt) {
            if (num < k) return false;
        }
        return true;
    }
    
public:
    int longestSubstring(string s, int k) {
        int n = s.size(), ans = -1;
        
        // Fix the no. of unique chars in the substring
        for (int num = 1; num <= 26; num++) {
            unordered_map<char, int> cnt;
            
            for (int l = 0, r = 0; l < n; ) {
                if (cnt.size() > num) {
                    --cnt[s[l]];
                    if (!cnt[s[l]]) cnt.erase(s[l]);
                    ++l;
                } else if (cnt.size() < num) {
                    if (r == n) break;
                    ++cnt[s[r++]];
                } else {
                    if (check(cnt, k)) ans = max(ans, r-l);
                    if (r == n) break;
                    ++cnt[s[r++]];
                }
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Problem statement should contain the fact that we need to output 0 if an answer doesn't exist

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by roll-no-1** [comment]
Hi @LC-Yani , it wasn't about the judger or optimization.  The statement doesn't tell what to output if the answer doesn't exist. Logically, 0 shouldn't be the answer, since it's empty string and doesn't satisfy the requirement that the string contains atleast k of each chars.

I'm just saying that this is a case where the answer doesn't exist, so user may output 0, -1, or anything they want to. We should tell them what to output in case an answer doesn't exist.
