### ISSUE TITLE
Incorrect problem description - 1195. Fizz Buzz Multithreaded

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#7186]
#### Your LeetCode username

roll_no_1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The functions output "fizz", "buzz" and "fizzbuzz", instead of what's mentioned in the statement, i.e., "Fizz", "Buzz", "FizzBuzz". All output strings are all lowercase. The problem statement should reflect that.

#### Code you used for Submit/Run operation

```
N/A
```

#### Language used for code

N/A

#### Expected behavior

- "Fizz" should be replaced with "fizz"
- "Buzz" should be replaced with "buzz"
- "FizzBuzz" should be replace with "FizzBuzz"

#### Screenshots

<img width="844" alt="image" src="https://user-images.githubusercontent.com/36921843/166232686-1fa525b0-b200-464a-96c5-0873e983e296.png">
<img width="679" alt="image" src="https://user-images.githubusercontent.com/36921843/166232721-884b0394-ba83-4f03-9bbb-db0a80aa986a.png">

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
