### ISSUE TITLE
Missing Test Case - 1038. Binary Search Tree to Greater Sum Tree

### ISSUE THREAD

**Issue by Roshan1020** [LeetCode-Feedback/LeetCode-Feedback#7188]
class Solution {
    int sum=0;
    public TreeNode inOrder(TreeNode root)
    {
        if(root!=null)
        {
             inOrder(root.right);
               sum+=root.val;
               root.val=sum;
             inOrder(root.left);
        }
        return root;
       
    }
    public TreeNode bstToGst(TreeNode root) {
        
        if(root==null)
        {
            return null;
        }
        return inOrder(root);
        
    }
**}******

**Comment by Roshan1020** [comment]
using inOrder is very easy

**Comment by LC-Yani** [comment]
Thank you for your time. I have submitted your feedback to update the problem. We appreciate your support!
