### ISSUE TITLE
678. Valid Parenthesis String

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#719]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Approach 1: Brute Force [Time Limit Exceeded] has incorrect description.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def checkValidString(self, s):
        if not s: return True
        A = list(s)
        self.ans = False

        def solve(i):
            if i == len(A):
                self.ans |= valid()
            elif A[i] == '*':
                for c in '() ':
                    A[i] = c
                    solve(i+1)
                    if self.ans: return
                A[i] = '*'
            else:
                solve(i+1)

        def valid():
            bal = 0
            for x in A:
                if x == '(': bal += 1
                if x == ')': bal -= 1
                if bal < 0: break
            return bal == 0

        solve(0)
        return self.ans
```

#### Language used for code

Python

#### Expected behavior

It doesn't TLE and submission was accepted. Suggestion is to either remove TLE statement or explain in which situation it's TLE. 

#### Screenshots

<img width="274" alt="Capture" src="https://user-images.githubusercontent.com/7014697/88524393-1c0b8e80-cfae-11ea-88ed-4829af16be2b.PNG">

**Comment by lc-ivan** [comment]
Hi @agatagruza ,
Thank you for reaching out. After reviewing and testing the solution code on our end, we have received TLE after submitting (please see attached). Please note that **running code from a test case only tests that one test case** whereas **submitting the code tests all tests cases resulting in TLE**. If you have received a different outcome (such as Accepted) when submitting the code, please attach those images to this ticket and we will review as soon as possible!

![Screen Shot 2020-07-31 at 2 23 33 PM](https://user-images.githubusercontent.com/68418560/89078533-6f2c6b00-d339-11ea-8f77-af080478bd8d.png)

**Comment by agatagruza** [comment]
Hi @lc-ivan I fundamentally misunderstood when TLE occurs. My understanding was it happens when you are running a test case. Whereas I should be testing when you are submitting the code. My apology.

**Comment by lc-ivan** [comment]
No worries at all! We are always happy to clarify.
