### ISSUE TITLE
最大不重复字符串

### ISSUE THREAD

**Issue by 8527zz** [LeetCode-Feedback/LeetCode-Feedback#7191]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
    public int lengthOfLongestSubstring(String s) {
       int n = s.length();
            if (n<=1){
            return n;
            }
            int MaxLen = 1;
            int left = 0, right = 0;
            Map<Character,Integer> window = new HashMap<>();
            while (right<n){
                char rightChar = s.charAt(right);
                int rightCharIndex = window.getOrDefault(rightChar,-1);
                left = Math.max(left,rightCharIndex+1);
                MaxLen = Math.max(MaxLen,right-left+1);
                window.put(rightChar,right);
                right++;
            }
            return MaxLen;

        }
    }
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
Hello～为了更好地定位问题，还请将出现问题的详细情况反馈至我们，我们在收到你的回复后会尽快与你跟进。
后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
