### ISSUE TITLE
Grammar fix - 171. Excel Sheet Column Number

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#7193]
#### Your LeetCode username

roll_no_1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The first line should be:
Given a string columnTitle that represents the column title as **appearing** in an Excel sheet, return its corresponding column number.
The appear should be changed to appearing

#### Code you used for Submit/Run operation

```
N/A
```

#### Language used for code

N/A

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
