### ISSUE TITLE
Missing test case - 2261. K Divisible Elements Subarrays

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#7194]
#### Your LeetCode username

yumkam

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Accepted solutions based on counting size of set of rolling hashes are massively broken.
E.g. code below accepted, but fails (one of) test cases below:
```
[195,129,12,85,40,25,35,162,114,21,19,136,48,149,34,45]
16
1
[34,23,182,31,91,81,33,44,72,102,182,81]
12
1
[175,24,4,92,8,189,29,15,5,17,33,88,15,35,113,133,32,155]
18
1
[200,83,159,143,12,29,109,9,154,49,175,161,27,167,5]
15
1
```
(Generated using birthday paradox antihash technique)

#### Code you used for Submit/Run operation

Not my code - accepted solution for Q3 for weekly contest 291 by [sheepforever](https://leetcode.com/sheepforever)
```c++
class Solution {
public:
    int countDistinct(vector<int>& nums, int k, int p) {
        unordered_set<long long> s;
        int last = 0, cur = 0;
        for (int i = 0; i < nums.size(); ++i) {
            if (nums[i] % p == 0) ++cur;
            while (cur > k) {
                if (nums[last] % p == 0) --cur;
                ++last;
            }
            
            long long hash = 0;
            for (int j = i; j >= last; --j) {
                hash = (hash * 234 + nums[j] + 1) % 123192830097LL;
                s.insert(hash);                
            }
        }
        return s.size();
    }
};
```

Fails 1st test (135 instead of 136).

Not my code, accepted solution for Q3 by [lucifer1006](https://leetcode-cn.com/lucifer1006)
```c++
using ll = long long;
const ll K1 = 7, K2 = 13, M1 = 1e9 + 7, M2 = 1e9 + 9;

class Solution {
public:
    int countDistinct(vector<int>& nums, int k, int p) {
        set<pair<ll, ll>> s;
        int n = nums.size();
        for (int i = 0; i < n; ++i) {
            int f = 0;
            ll v1 = 0, v2 = 0;
            for (int j = i; j < n; ++j) {
                if (nums[j] % p == 0)
                    f++;
                if (f > k)
                    break;
                v1 = (v1 * K1 + nums[j]) % M1;
                v2 = (v2 * K2 + nums[j]) % M2;
                s.emplace(v1, v2);
            }
        }
        return (int)s.size();
    }
};
```

Fails second test (74 instead of 76)

Not my code - accepted solution for Q3 by [flamboyant-mcnultyjhw](https://leetcode-cn.com/flamboyant-mcnultyjhw)
```c++
class Solution {
public:
    int i,j,k,n,m,t,res=0,sb,no;
    int countDistinct(vector<int>& a, int k, int p) {
        set<int> s;
        #define M 998244853
        n=a.size();
        for(i=0;i<n;i++){
            sb=0;
            no=0;
            for(j=i;j<n;j++){
                if(!(a[j]%p)){
                    no++;
                }
                if(no>k)break;
                
                sb=(1ll*sb*114514+a[j])%M;
                //printf("a%d %d %d\n",i,j,sb);
                s.insert(sb);
            }
        }
        return s.size();
    }
};
```

Fails 3rd test (169 instead of 170).

Not my code - accepted solution by  [balakrishnan_v](https://leetcode.com/balakrishnan_v)
```c++
#define ll long long
#define MODD 1000000000039ll
class Solution {
public:
    
    
    
    int countDistinct(vector<int>& nums, int k, int p) {
        int maxa = *std::max_element(nums.begin(),nums.end());
        int n=nums.size();
        int ans=0;
        set<ll> uniq;
        for(int i=0;i<n;i++) {
            int ct=0;
            ll H = 0;
            for(int j=i;j<n;j++) {
                H = (H * (maxa+1) + nums[j])%MODD;
                ct += (nums[j]%p==0);
                if (ct > k) {
                    break;
                }
                uniq.insert(H);
            }
        }
        return uniq.size();
        
    }
};
```

Fails 4th test (119 instead of 120).

#### Language used for code

C++

#### Expected behavior

I'd say "broken solutions should not be accepted", but...
Not sure. Sadly, those tests could be generated only against specific algorithms.
IMO, this problem is badly suited for leetcode; too easy to write broken implementation, that will be accepted by unspecific test cases.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by yumkam** [comment]
More test cases:
```
[40,5,195,16,53,190,21,50,191,6,147,81,62,43,159,21,161,5]
18
1
```
Fails python3 solution by [balu_r](https://leetcode.com/balu_r)
```
[121,89,27,71,166,114,8,166,39,20,124,172]
12
1
```
Fails python3 solution by [LarryNY](https://leetcode.com/LarryNY)
```
[178,19,153,22,53,41,22,19,51,54,49,114,88,171,36,41,2,86]
18
1
```
Fails C++ solution by [wjli](https://leetcode.com/wjli)

**Comment by yumkam** [comment]
Now, with new collision generator, based on lattice reduction, and it is able to crack large modulo and multiple hashes and with short sequences (based on article ["On the mathematics behind rolling hashes and anti-hash tests" By dacin21](https://codeforces.com/blog/entry/60442)):
```
[1,1,1,67,1,99,82,52,29,40,86,1,9,1,1,1]
16
1
```
For solution by dysyn1314 (base 13131, modulo 2^64)
```
[88,1,59,1,8,1,93,51,1,21,1,93,1,55,1,1]
16
1
```
For solution by rfpermen (base 724729, modulo 2^64)
```
[2,1,1,10,1,1,24,1,10,36,1,5,23,1,11,32,1,17,1,1]
20
1
```
For solution by lucifer1006 (double hash: base 7, modulo 1 000 000 007; base 13, modulo 1 000 000 009)
TBC

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
