### ISSUE TITLE
1425. 带限制的子序列和

### ISSUE THREAD

**Issue by Kei921** [LeetCode-Feedback/LeetCode-Feedback#7199]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
kei921

**Bug 类型**
- [ ] 缺少测试用例
 

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Constrained Subsequence Sum
class Solution {
public:
    int constrainedSubsetSum(vector<int>& nums, int k) {
		deque<int> q;
		q.emplace_back(0);
		int n = nums.size();
		int res = nums[0];
		vector<int> dp(n);
		dp[0] = nums[0];
		for (int i = 1; i < n; i++) {
			while (!q.empty() && i - q.front() > k)q.pop_front();
			dp[i] = max(dp[q.front()], 0) + nums[i];
			res = max(res, dp[i]);
			if (nums[i] >= 0) {
				q.clear();
				q.emplace_back(i);
			}
			else {
				while (!q.empty() && nums[i] > nums[q.back()])q.pop_back();
				q.emplace_back(i);
			}
		}
		return res;
	}
};
```

**期望行为**
描述你期望的结果

测试数据：

[5,-5,-4,-3,9]
2
正确答案应该是10 （5-4+9）
我的回答是9 （9）
但是能通过全部样例
本来考虑的是通过上一个距离小于等于k的最大的负数进行转移
通过后发现这样考虑不正确 会遗漏部分情况

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/32092352/166635265-7731cd4f-2476-4850-b245-1dca7b975d32.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：kei921 给予积分奖励，请查收。
