### ISSUE TITLE
Problem 153 Time Exceeded for Solution

### ISSUE THREAD

**Issue by jstephenj14** [LeetCode-Feedback/LeetCode-Feedback#72]
For the problem link below:

https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/submissions/

The test case [3,4,5,1,2] results in a Time Limit Exceeds with my code (reproduced below) when it results in the correct solution of 1 when I run it locally on my computer. Can someone look into this?

import math

def findMin( nums):
    """
    :type nums: List[int]
    :rtype: int
    """
    l = 0
    r = len(nums) - 1
    while (l != r):
        mid = int(math.ceil((l + r) / 2))
        if (nums[mid] < nums[r]):
            r = mid
        else:
            l = mid
    return nums[l]

**Comment by CooperCooperCooper** [comment]
Hi @jstephenj14,
Thank you for reaching out to us. To help us assess the issue quickly, can you please fill in the language your solution is in?

**Comment by CooperCooperCooper** [comment]
Hi @jstephenj14,
Thank you for your time. Your code is getting TLE because it sets the bound incorrectly. Please fix it accordingly. We appreciate your support.
