### ISSUE TITLE
233. Number Of Digit One

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#720]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Approach 1: Brute force [Time Limit Exceeded] has incorrect description.

#### Code you used for Submit/Run operation

```
int countDigitOne(int n)
{
    int countr = 0;
    for (int i = 1; i <= n; i++) {
        string str = to_string(i);
        countr += count(str.begin(), str.end(), '1');
    }
    return countr;
}
```

#### Language used for code

C++

#### Expected behavior

It doesn't TLE and submission was accepted. Suggestion is to either remove TLE statement or explain in which situation it's TLE.

#### Screenshots

<img width="342" alt="Capture" src="https://user-images.githubusercontent.com/7014697/88526337-aead2d00-cfb0-11ea-897f-6027fa84b067.PNG">

**Comment by lc-ivan** [comment]
Hi @agatagruza ,
Thank you for reaching out with this case. After reviewing and testing the solution code on our end, we have received TLE many times after submitting (please see attached). Please note that running code from a test case only tests that one test case whereas submitting the code tests all tests cases resulting in TLE. If you have received a different outcome (such as Accepted) when submitting the code, please attach those images to this ticket!

![Screen Shot 2020-07-31 at 2 25 55 PM](https://user-images.githubusercontent.com/68418560/89078717-c92d3080-d339-11ea-9790-e6a79b28bc1c.png)

**Comment by agatagruza** [comment]
Hi @lc-ivan I fundamentally misunderstood when TLE occurs. My understanding was it happens when you are running a test case. Whereas I should be testing when you are submitting the code. My apology.

**Comment by lc-ivan** [comment]
No worries - we are always happy to clarify!
