### ISSUE TITLE
[Wrong description] 994. Rotting Oranges

### ISSUE THREAD

**Issue by hiteshkuber** [LeetCode-Feedback/LeetCode-Feedback#7201]
#### Your LeetCode username
hiteshkuber

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question does not provide all required info. Judging and came to this conclusion based on expected answer for various inputs, it appears you the question assumes that there is only one rotten tomato but no where is it written on mentioned as such. In case of multiple rotten tomatoes the expected answers are different

#### Expected behavior
Please mention in question that there is only one rotten tomato, or update the testcases

#### Additional context
Assume that Input matrix is :
[[2,1,1,1,2,1],
 [1,2,1,1,1,1],
 [1,1,2,1,1,1],
 [1,1,1,2,1,1],
 [2,1,1,1,2,1]]
  
The expected answer for test case is resulted as 3, whereas actual answer should be 2.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

**Comment by hiteshkuber** [comment]
I spent a considerable amount of time on this problem again, and I came to the conclusion that there is no such issue.  I am extremely sorry for the trouble caused. I think we can close this issue.
