### ISSUE TITLE
题目 1441 提示发生未知错误

### ISSUE THREAD

**Issue by cyrilney** [LeetCode-Feedback/LeetCode-Feedback#7203]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
cyril

**Bug 类型**
- [√] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

在提交题目题1441 的时候报错：
「发生未知错误，请稍后重试，如果此错误仍然存在，请与我们联系」 多次提交仍是如此。
刷新提示错误 测试用例在题目中尝试后得到如下：

输入
{"headers":{"Activity":["user_id","session_id","activity_date","activity_type"]},"rows":{"Activity":[[1,1,"2019-07-20","open_session"],[1,1,"2019-07-20","scroll_down"],[1,1,"2019-07-20","end_session"],[2,4,"2019-07-20","open_session"],[2,4,"2019-07-21","send_message"],[2,4,"2019-07-21","end_session"],[3,2,"2019-07-21","open_session"],[3,2,"2019-07-21","send_message"],[3,2,"2019-07-21","end_session"],[4,3,"2019-08-25","open_session"],[4,3,"2021-08-25","end_session"]]}}
输出
{"headers": ["day", "active_users"], "values": [["2019-07-20", 2], ["2019-07-21", 2]]}
预期结果
{"headers": ["day", "active_users"], "values": [["2019-07-20", 2], ["2019-07-21", 2], ["2019-08-25", 1], ["2021-08-25", 1]]}

但是题目说过截止到7月27日， 为什么预期结过里面会有8月的数据。

**你使用的语言**
MySQL

**你提交或者运行的代码**
```mysql

select 
activity_date as day, count(distinct user_id) as `active_users`
from
Activity
where
activity_date between date_add(date('2019-07-27'),INTERVAL -29 DAY) and date('2019-07-27')
group by activity_date

```
**期望行为**
正确的报错  或者是正确的样例

**屏幕截图**
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/10266906/166896692-e766e8fe-0d8a-4ae1-8c61-d9c816b8d484.png">
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/10266906/166896740-b6322bb5-992b-44d9-b6b3-dd83a630a380.png">

**额外的上下文**
略.

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by ghforcx** [comment]
题目是[1141](https://leetcode-cn.com/problems/user-activity-for-the-past-30-days-i/)

**Comment by feiceh** [comment]
你好，当前题目已修复，ID：cyril  给予积分奖励，请查收。
