### ISSUE TITLE
Incorrect Standard Program - 2254. Design Video Sharing Platform

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7204]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
**Please DO NOT close this issue without replying this issue. Whether the problem is fixed or not, please reply this issue before closing it.**

For [2254. Design Video Sharing Platform](https://leetcode.com/problems/design-video-sharing-platform), the standard program is incorrect and returns wrong answers for some test cases.

The problem statement mentions:
> When a video is uploaded, it is associated with the smallest available integer `videoId` starting from `0`. Once a video is deleted, the `videoId` associated with that video can be reused for another video.

Consider the following test case.

```
["VideoSharingPlatform","upload","upload","remove","remove","upload"]
[[],["123"],["456"],[1],[0],["789"]]
```

After uploading two videos with video ids being 0 and 1 respectively, both video ids 0 and 1 are removed and can be reused. Since video id 0 can be reused, the last upload operation should return video id 0.

The output of this test case should be as follows.

```
[null,0,1,null,null,0]
```

However, the standard program has the following output.

```
[null,0,1,null,null,1]
```

In the standard program's output, the last returned value is 1, which is incorrect since video id 0 is the smallest available video id and should be reused.

Therefore, the standard program is incorrect and should be fixed.

**Please make sure this issue is checked before closing it.** The same problem was mentioned in #7161, but that issue was closed without any reply from LeetCode official site. I wonder why that issue was closed without any investigation.

Even if the issue is invalid, please reply with the reason before closing the issue.

#### Code you used for Submit/Run operation
```Java
class VideoSharingPlatform {
    int id;
    Map<Integer, String> videoMap;
    Map<Integer, Integer> viewsMap;
    Map<Integer, int[]> likesDislikesMap;
    PriorityQueue<Integer> removed;

    public VideoSharingPlatform() {
        id = 0;
        videoMap = new HashMap<Integer, String>();
        viewsMap = new HashMap<Integer, Integer>();
        likesDislikesMap = new HashMap<Integer, int[]>();
        removed = new PriorityQueue<Integer>();
    }

    public int upload(String video) {
        int videoId;
        if (removed.isEmpty()) {
            videoId = id;
            id++;
        } else {
            videoId = removed.poll();
        }
        videoMap.put(videoId, video);
        viewsMap.put(videoId, 0);
        likesDislikesMap.put(videoId, new int[2]);
        return videoId;
    }

    public void remove(int videoId) {
        if (videoMap.containsKey(videoId)) {
            videoMap.remove(videoId);
            viewsMap.remove(videoId);
            likesDislikesMap.remove(videoId);
            removed.add(videoId);
        }
    }

    public String watch(int videoId, int startMinute, int endMinute) {
        if (videoMap.containsKey(videoId)) {
            viewsMap.put(videoId, viewsMap.get(videoId) + 1);
            String video = videoMap.get(videoId);
            endMinute = Math.min(endMinute, video.length() - 1);
            return video.substring(startMinute, endMinute + 1);
        } else {
            return "-1";
        }
    }

    public void like(int videoId) {
        if (likesDislikesMap.containsKey(videoId)) {
            likesDislikesMap.get(videoId)[0]++;
        }
    }

    public void dislike(int videoId) {
        if (likesDislikesMap.containsKey(videoId)) {
            likesDislikesMap.get(videoId)[1]++;
        }
    }

    public int[] getLikesAndDislikes(int videoId) {
        return likesDislikesMap.getOrDefault(videoId, new int[]{-1});
    }

    public int getViews(int videoId) {
        return viewsMap.getOrDefault(videoId, -1);
    }
}
```

#### Language used for code
Java

#### Expected behavior
Fix the standard program to return correct answers.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem ( Updated the model solution and 
Added the test case). Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
