### ISSUE TITLE
Improvement - 119. Pascal's Triangle II

### ISSUE THREAD

**Issue by sbalia** [LeetCode-Feedback/LeetCode-Feedback#7207]
#### Your LeetCode username
easy_quizy

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I want to solve the problem using factorial and math formula, but can't because:
C# can't handle values greater than a factorial of 20!
21! is 51,090,942,171,709,440,000 that exceeds the limit.

| Type               | Max Fact  | Max Value | 
|--------------------|-----------|----------------------------|
|     int            | 12!       | 6,227,020,800              |  
|     long           | 20!       | 9,223,372,036,854,775,807  |   
|     ulong          | 20!       | 18,446,744,073,709,551,615 |   

#### Code you used for Submit/Run operation

```
public class Solution {
    public IList<int> GetRow(int rowIndex) {
        if(rowIndex == 0)
            return new int[1] {1};
        
        int[] res = new int[rowIndex+1];
        res[0] = res[rowIndex] = 1;
        for(int i = 0; i < rowIndex; i++)
        {
            res[i] = (int)(fact(rowIndex) / (fact(i) * fact(rowIndex - i)));
        }
        
        return res;
    }
    private long fact(int n)
    {
        int i;
        long fact = 1;
        for(i = 1; i <=n ; i++)
        {      
            fact = fact * i;      
        }      
        return fact;
    }
}
```

#### Language used for code
C#

#### Expected behaviour
I expect to have a return type defined as IList<BigInteger>, this struct potentially can hold numbers without up/low boundaries.

#### Additional context
At the moment if I try to modify the return type, I get the error:
Line 19: Char 16: error CS0266: Cannot implicitly convert type 'System.Collections.Generic.IList<System.Numerics.BigInteger>' to 'System.Collections.Generic.IList<int>'. An explicit conversion exists (are you missing a cast?) (in __Driver__.cs)

I guess that the test suite is expecting to have a return type defined as IList<int>, but after modification, it returns IList<BigInteger>, which is why this error occurs.

```
public class Solution {
    public IList<BigInteger> GetRow(int rowIndex) {
        if(rowIndex == 0)
            return new BigInteger[1] {1};
        
        BigInteger[] res = new BigInteger[rowIndex+1];
        res[0] = res[rowIndex] = 1;
        for(int i = 0; i < rowIndex; i++)
        {
            res[i] = fact(rowIndex) / (fact(i) * fact(rowIndex - i));
        }
        
        return res;
    }
    private BigInteger fact(int n)
    {
        int i;
        BigInteger fact = 1;
        for(i = 1; i <=n ; i++)
        {      
            fact = fact * i;      
        }      
        return fact;
    }
}
```

**Comment by LC-Yani** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by sbalia** [comment]
@LC-Yani , I mean, it is not the judger problem, it's C# issue, that it can't handle really big numbers. At the moment it is impossible to solve the problem using factorial and numbers that exceeds 21! in C# language, because the judger expects to receive `IList<int>` whereas this solution requires to return `IList<BigInteger>`.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The problem was designed to be solved with a much easier solution. The current constraints are fine and we do not intend to reduce them in the future. We appreciate your support!
