### ISSUE TITLE
719. Find K-th Smallest Pair Distance - Broken Solution

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#721]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Approach 1: Heap has a broken code. When running provided code I am getting:
```
TypeError: heappush expected 2 arguments, got 1
    heapq.heappush((nums[nei + 1] - nums[root], root, nei + 1))
Line 12 in smallestDistancePair (Solution.py)
    ret = Solution().smallestDistancePair(param_1, param_2)
Line 43 in _driver (Solution.py)
    _driver()
Line 53 in <module> (Solution.py)
```

#### Code you used for Submit/Run operation

```python
class Solution(object):
    def smallestDistancePair(self, nums, k):
        nums.sort()
        heap = [(nums[i+1] - nums[i], i, i+1)
                for i in xrange(len(nums) - 1)]
        heapq.heapify(heap)

        for _ in xrange(k):
            d, root, nei = heapq.heappop(heap)
            if nei + 1 < len(nums):
                heapq.heappush((nums[nei + 1] - nums[root], root, nei + 1))

        return d
```

#### Language used for code

Python

#### Expected behavior

Additional parameter **heap** is needed as in: 
> heapq.heappush(**heap**,(nums[nei + 1] - nums[root], root, nei + 1))

#### Screenshots

<img width="473" alt="Capture1" src="https://user-images.githubusercontent.com/7014697/88531793-42362c00-cfb8-11ea-9327-e3eac0a726df.PNG">
<img width="466" alt="Capture2" src="https://user-images.githubusercontent.com/7014697/88531795-42cec280-cfb8-11ea-842e-c89c15890c87.PNG">

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @agatagruza 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by agatagruza** [comment]
Thank you @lc-pam for an update. Glad could help.
