### ISSUE TITLE
Missing Test Case - 1209. Remove All Adjacent Duplicates in String II

### ISSUE THREAD

**Issue by venom-10** [LeetCode-Feedback/LeetCode-Feedback#7210]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation
```<!-- 
class Solution {
public:
    string removeDuplicates(string s, int k) {
        if(s.length()<k)
            return s;
        string temp = "";
        bool f = false;
        for(int i=0;i<s.length();i++){
            int t=1;
            int z = i;
            while(i<(s.length()-1) && s[i]==s[i+1] && t<k){
                t++;
                i++;
            }
            if(t==k){
                f = true;
            }else{
                while(t>=1){
                    temp += s[z];
                    t--;
                }
            }
        }
        if(f)
            return removeDuplicates(temp,k);
        return temp;
    }
};

```

**Comment by venom-10** [comment]
There is no bug BUT this problem is also solved using Recursion, So Please include it in Related Topics.

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Although it can be done with recursion but not mainstream, the frequency of recursive labels in the discussion area is not high, so we decided not to add recursive labels. We appreciate your support!
