### ISSUE TITLE
Missing Test Case - 1209. Remove All Adjacent Duplicates in String II

### ISSUE THREAD

**Issue by Bat-Erdene-mazaalai** [LeetCode-Feedback/LeetCode-Feedback#7211]
#### Your LeetCode username

My handle: Mazaalai

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

```
// Two Sum
#define mp make_pair
#define pb push_back
class Solution {
public:
    string removeDuplicates(string s, int k) { // the complexity of this function is O(N^2)
        cout << s << '\n';
        string newStr = "";
        int n = s.size();
        vector <pair <int, char> > memo;
        for (int i = 0; i < n; i++) { 
            if (memo.size() > 0 && memo.back().second == s[i]) memo.back().first = (memo.back().first + 1) % k;
            else memo.pb(mp(1, s[i]));
        }
        for (int i = 0; i < memo.size(); i++)  // O(A), total O(A*B==N)
            for (int j = 0; j < memo[i].first; j++)  // O(B)
                newStr += memo[i].second;

        if (newStr == s) return s;
        return removeDuplicates(newStr, k); // it can be repeated N times (N/2 exactly.).
    }
};
```

#### Language used for code

C++

#### Expected behavior

What I expected was a Time limit Exceeded. In a test like s="abcabceedcbacba", k = 2 it should work in O(N^2). But contrary to my expectations it worked in only 20ms.

#### Screenshots

submission link: https://leetcode.com/submissions/detail/265581957/

#### Additional context

For generating the test case I think you need to do something like this.
```
int N = 100000;
int K = 2;
for (int i = 1; i <= ((N - 2) / 2) / 2; i++)
    cout << "ab";
cout << "acca";
for (int i = 1; i <= ((N - 2) / 2) / 2; i++)
    cout << "ba";

```

**Comment by LC-Yani** [comment]
Thank you for reaching out to us! Please check out this [support article](https://support.leetcode.com/hc/en-us/articles/360011984773-What-does-the-Finish-Penalty-Time-column-mean-in-the-ranking-), it states that "Submissions that are judged as Accepted, Compile Error, Internal Error, or Timeout do not add to your penalty time." so other outcomes such Output Limit Exceeded is considered as a wrong attempt.
