### ISSUE TITLE
Missing Test Case - 325. Maximum Size Subarray Sum Equals k

### ISSUE THREAD

**Issue by raditya1710** [LeetCode-Feedback/LeetCode-Feedback#7215]
#### Your LeetCode username
alfonsus_raditya

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
when input:
```
nums = [10000, 10000, 10000,...]  (2 x 10^5 times)
k = -1000000000
```

it shows invalid test case, where it is valid under the constraint.

#### Code you used for Submit/Run operation

```
typedef long long LL;
class Solution {
    unordered_map<LL,int> MAP;
public:
    int maxSubArrayLen(vector<int>& nums, int k) {
        MAP[0] = -1;
        LL sum = 0;
        int n = (int) nums.size();
        int ans = 0;
        for(int i = 0;i < n; ++i){
            sum += nums[i];
            LL target = 1LL * sum - 1LL * k;
            if(MAP.count(target)){
                ans = max(ans, i - MAP[target]);
            }
            if(!MAP.count(sum)) MAP[sum] = i;
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

It should be a valid test case, returns 0.

#### Screenshots
![Screenshot from 2022-05-06 17-33-30](https://user-images.githubusercontent.com/14028227/167115792-6e8d13fa-d4ec-4ea5-8e58-98554fc33ae2.png)

#### Additional context

Maybe the intermediate operation used when adding / subtracting (by judge's solution) is overflowed, like 2 * 10<sup>9</sup> - (-10<sup>9</sup>) = 3*10<sup>9</sup> (more than the limit of 32-bit signed integer), but the result is not overflow (0)

**Comment by LC-Yani** [comment]
Hi there,

Thank you for reaching out to us.

[10000, 10000, 10000,...] is not a valid value of type integer[]

**Comment by raditya1710** [comment]
I'm sorry for the misunderstanding @LC-Yani, but I mean the values for `nums` is an array of 200000 numbers, each has a value of 10000, which is within the constraint of the problem.

**Comment by raditya1710** [comment]
I'm sorry for the misunderstanding @LC-Yani, but I mean the values for nums is an array of 200000 numbers, each has a value of 10000, which is within the constraint of the problem.
[subarray-in.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8647414/subarray-in.txt)

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
