### ISSUE TITLE
Incorrect returned value - 344. Reverse String

### ISSUE THREAD

**Issue by testourii** [LeetCode-Feedback/LeetCode-Feedback#7216]
#### Your LeetCode username
TassCode

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The returned value is incorrect when using recursive function.
I tested it locally and i got the correct value.

#### Code you used for Submit/Run operation

```
// Reverse String

var reverseString = function (s) {
  if (s.length <= 1) return s;
  let f = [s[0]],
    l = [s[s.length - 1]];
  s.pop();
  s.shift();
  return l.concat(reverseString(s), f);
};
```

#### Language used for code
JavaScript

#### Expected behavior
- input : ["h","e","l","l","o"]
- expected output:  ["o","l","l","e","h"]
- returned output: ["l"]

**Comment by stormsunshine** [comment]
This problem's function has return type `void`. You should NOT return anything from the function, and you should modify the parameter to reverse it.
