### ISSUE TITLE
Wrong Test Case - 1209. Remove All Adjacent Duplicates in String II

### ISSUE THREAD

**Issue by shwe2498** [LeetCode-Feedback/LeetCode-Feedback#7218]
Wrong output for :

Wrong Answer
Runtime: 5 ms
Your input
"nnwssswwnvbnnnbbqhhbbbhmmmlllm"
4
Output
"nnwwwsssvbbqhhhlll"
Expected
"nnwssswwnvbnnnbbqhhbbbhmmmlllm"

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by shwe2498** [comment]
Surely I'll update the code, now leetcode is not reachable showing some internal server error.

**Comment by LC-Yani** [comment]
Hi there,

Would you mind sending your code and language to us? Then we can test it on our end. 

Thank you.

**Comment by shwe2498** [comment]
Yupp sure I don't mind at all!!!

**Comment by shwe2498** [comment]
Language :: C++

class Solution {
public:
    string removeDuplicates(string s, int k) {
        unordered_map<int, int> m;
        
        for(auto c : s){
            m[c]++;
            if(m[c] % k != 0){
                if(m[c] > k) m[c] %= k;
            } 
        }
        
        string res;
        for(auto i : m){
            //if(i.second % k != 0){
                //if(i.second > k) i.second %= k;
                res.append(i.second, i.first);
            //}
            
        }
        
        reverse(res.begin(), res.end());
        
        return res;
    }
};
