### ISSUE TITLE
2069. Walking Robot Simulation II [Description Typo]

### ISSUE THREAD

**Issue by Nuno-Dev** [LeetCode-Feedback/LeetCode-Feedback#7222]
#### Your LeetCode username

nunodev

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The robot class has a method called 'void step(int num)':
![image](https://user-images.githubusercontent.com/57804241/167248048-7b4f8133-7059-42f6-b667-3bde0c71aa7d.png)

But the input and explanation fields, don't use the method 'step' but a method called 'move' which doesn't exist in question description which can confuse the users.

![image](https://user-images.githubusercontent.com/57804241/167248012-15ff654f-2ded-486a-aa8c-9c1259afc514.png)

The fix would be to just changed all those 'move' method calls in the picture above to 'step'.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
