### ISSUE TITLE
Bad Test Case - 288. Unique Word Abbreviation

### ISSUE THREAD

**Issue by piypop** [LeetCode-Feedback/LeetCode-Feedback#7224]
#### Your LeetCode username
piypop

#### Category of the bug
Bad Test Case

#### Description of the bug
When trying to submit a solution in Go, it fails on this test case - 
["ValidWordAbbr","isUnique","isUnique","isUnique","isUnique"]
[[["deer","door","cake","card"]],["dear"],["door"],["cart"],["cake"]]

The correct expected value should be -
[null,false,true,true,true]

But the actual expected value is - 
[null,false,false,true,true]

"door" should return true because the dictionary passed has that word

#### Code you used for Submit/Run operation

```
type ValidWordAbbr struct {
    m map[string][]string
}


func Constructor(dictionary []string) ValidWordAbbr {
        m := make(map[string][]string)
        for _,v := range dictionary {
                a := abr(v)
                m[a] = append(m[a],v)
        }
        fmt.Printf("dict:%v\n",m)
        return ValidWordAbbr{m}
}


func (this *ValidWordAbbr) IsUnique(word string) bool {
        a := abr(word)
        
        if this.m[a] == nil {
                return true
        }
        
        for _, v := range this.m[a] {
                if v == word {
                        return true
                }       
        }
                
        return false
}

func abr(word string) string {
        if len(word) <= 2 {
                return word
        }
        var b strings.Builder
        
        b.WriteByte(word[0])
        fmt.Fprintf(&b,"%v",len(word)-2)
        b.WriteByte(word[len(word)-1])
        return b.String()
}
```

#### Language used for code
Go

#### Expected behavior
The expected test case should be - 
[null,false,true,true,true]

#### Screenshots
![lc-bad-test](https://user-images.githubusercontent.com/27827182/167264524-7feab416-afd9-463c-bc05-8b5434401ece.png)

**Comment by stormsunshine** [comment]
There are two words with the abbreviation "d2r", which are "deer" and "door", so the abbreviation of "door" is NOT unique. Why do you think it should return true?

**Comment by piypop** [comment]
Got it. I think the description needs to be modified then. As of today it doesn't mention that you need to ignore the 2nd word with the same abbreviation during dictionary initialization. I had an array of strings as the value of the map and was doing a linear scan to find the match because I was trying to preserve all the values sent with the init. That meant "dear" would fail but "door" would pass because "deer" and "door" were both present in the dictionary init.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to our team.  We appreciate your support!
