### ISSUE TITLE
Bug in leetcode #456. 132 Pattern

### ISSUE THREAD

**Issue by kcostya** [LeetCode-Feedback/LeetCode-Feedback#7226]
#### Your LeetCode username

kcostya

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Omitting the `False` return statement in Python will still pass all the test cases
https://leetcode.com/problems/132-pattern/

#### Code you used for Submit/Run operation

```
class Solution:
    def find132pattern(self, nums: List[int]) -> bool:
        if len(nums) < 3:
            return False
        
        stack = [] # [num, min_left] or [j, i]
        min_left = nums[0]
        
        for k in nums[1:]:
            while stack and k >= stack[-1][0]: # k < j
                stack.pop()
            
            if stack and k > stack[-1][1]: # i < k < j
                return True
            
            stack.append([k, min_left])
            min_left = min(k, min_left)
```

#### Language used for code
Python3

#### Expected behavior

The code must fail in cases where there is no 132 pattern found.

#### Additional context

https://leetcode.com/submissions/detail/695062364/

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.  When you do not add a return statement, your code returns None. None is seen as False by the driver code of python. We appreciate your support!
