### ISSUE TITLE
Missing Test Case - 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by OneUpWallStreet** [LeetCode-Feedback/LeetCode-Feedback#7227]
#### Your LeetCode username
oneupwallstreet

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Algorithm with linear time complexity is accepted as a solution when it's specified in the question that the time complexity must be O( log n)

#### Code you used for Submit/Run operation

```
// 33. Search in Rotated Sorted Array
class Solution {
public:
    int search(vector<int>& nums, int target) {
        for(int i=0;i<nums.size();i++){
            if(nums[i]==target){
                return i;
            }
        }
        return -1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution I submitted should have been rejected with an error message Time Limit Exceeded, as it's taking O(n) time (instead of  O( log n). There should ideally be a test case with large n, that checks the time complexity.

#### Screenshots

<img width="1439" alt="Screen Shot 2022-05-08 at 10 00 54 AM" src="https://user-images.githubusercontent.com/76121542/167281962-5dc13e3d-3fec-45a8-9e56-c4e3effa2e15.png">

#### Additional context

NA

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case that you use. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by OneUpWallStreet** [comment]
> The test case that you use.

I submitted the solution, and it was accepted. So all of the existing test-cases were used.
