### ISSUE TITLE
442. Find All Duplicates in an Array - Wrong Output for the input [5, 2, 5, 2, 2]

### ISSUE THREAD

**Issue by Pradeepan2202** [LeetCode-Feedback/LeetCode-Feedback#723]
#### Your LeetCode username
ipradeepan

#### Category of the bug
- [ ] Question
- Solution
- [ ] Language

#### Description of the bug
The wrong solution was accepted because of the missed test case

#### Code you used for Submit/Run operation

```
class Solution {
    public List<Integer> findDuplicates(int[] nums) {
      List<Integer> list = new ArrayList<>();
        Arrays.sort(nums);
        for (int i = 0; i < nums.length - 1; i++) {
            if (nums[i] == nums[i + 1]) 
                list.add(nums[i]);
        }
    return list;
    }
}
```

#### Language used for code
Java

#### Expected behavior
It should return the output as [2,5] for the input [5,2,5,2,2] but it is returning the wrong output as [2,2,5]

#### Screenshots

![image](https://user-images.githubusercontent.com/68239415/88550928-deefdc80-d03f-11ea-8827-6d4d6d949c5c.png)

**Comment by lc-pam** [comment]
Hi @Pradeepan2202 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @Pradeepan2202 
This test case is invalid because of the condition "some elements appear twice and others appear once".
However, we've used your feedback to add validators. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
