### ISSUE TITLE
6059. 检查是否有合法括号字符串路径 测试用例错误

### ISSUE THREAD

**Issue by xiaoguyueyue** [LeetCode-Feedback/LeetCode-Feedback#7231]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
原力

**Bug 类型**
- [ [6059. 检查是否有合法括号字符串路径]] 题目
- [ ] 题解
- [ java] 编程语言
- [ [["(",")",")","(","(","(","(",")",")","(",")","(",")","(","(","("],["(","(",")",")","(",")",")",")","(",")","(",")","(","(",")","("],[")",")","(",")",")","(","(",")","(","(",")","(",")",")","(",")"],["(","(",")","(",")","(",")",")",")","(",")","(","(",")","(",")"],["(","(","(",")","(","(",")","(",")",")","(",")",")",")",")",")"],[")",")","(","(",")",")",")",")",")","(",")",")",")","(","(",")"],[")",")",")",")","(",")","(",")","(","(",")","(","(",")","(","("],["(",")","(","(","(",")",")",")",")","(","(",")","(","(",")",")"],["(",")","(",")","(","(","(","(",")","(","(","(","(","(","(",")"],["(",")","(","(","(",")","(",")",")",")",")","(","(","(","(",")"],["(","(",")","(",")",")","(",")","(",")",")",")",")",")","(",")"],[")","(","(","(",")","(",")",")","(",")","(",")","(","(",")","("],["(",")","(",")",")","(","(",")","(",")","(",")",")",")","(","("],["(","(",")","(",")",")","(","(","(",")","(",")","(","(",")",")"],["(","(","(","(",")",")","(",")","(","(","(",")",")","(",")","("],["(","(","(",")",")",")","(",")",")","(",")",")","(","(",")","("],[")",")",")",")",")",")","(",")",")",")","(","(",")","(",")","("]]] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    int m, n;
    char[][] grid;
    boolean[][][] vis;

    public boolean hasValidPath(char[][] grid) {
        m = grid.length;
        n = grid[0].length;
        if (grid[0][0] == ')' || grid[m - 1][n - 1] == '(') return false; // 剪枝
        this.grid = grid;
        vis = new boolean[m][n][m + n];
        return dfs(0, 0, 0);
    }

    boolean dfs(int x, int y, int c) {
        if (c > m - x + n - y - 1) return false; // 剪枝：即使后面都是 ')' 也不能将 c 减为 0
        if (x == m - 1 && y == n - 1) return c == 1; // 终点一定是 ')'
        if (vis[x][y][c]) return false; // 重复访问
        vis[x][y][c] = true;
        c += grid[x][y] == '(' ? 1 : -1;
        return c >= 0 && (x < m - 1 && dfs(x + 1, y, c) || y < n - 1 && dfs(x, y + 1, c)); // 往下或者往右
    }
}

```

**期望行为**
描述你期望的结果
true

**屏幕截图**
![image](https://user-images.githubusercontent.com/83528014/167287001-72dd0fd8-e34d-4961-9c67-a224b145ba00.png)

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
这个测试用例应该返回 false，右下角是左括号，这是不可能存在合法括号字符串路径的。

既然标准程序返回 true，说明标准程序错了。

**Comment by feiceh** [comment]
@[xiaoguyueyue](https://github.com/xiaoguyueyue)你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。
