### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by Veeit** [LeetCode-Feedback/LeetCode-Feedback#7233]
#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Approach 1: Brute Force solution ist to Slow for test case

#### Code you used for Submit/Run operation
My Solution:
```
class Solution:
    def maxArea(self, height: List[int]) -> int:
        water = 0
        for i in range(len(height)):
            for x in range(i):
                multi = min(height[i], height[x])
                water = max(water, (i - x) * multi)
        return water
```
Official Solution: 
```
class Solution:
    def maxArea(self, height: List[int]) -> int:
        maxarea = 0
        for left in range(len(height)):
            for right in range(left + 1, len(height)):
                width = right - left
                maxarea = max(maxarea, min(height[left], height[right]) * width)

        return maxarea
```

#### Language used for code
Python 3

#### Expected behavior
Solution should finish in time and don't get a out of time error

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for sharing your concern. TLE is the expected behavior of this approach. Brute force approaches are intuitive starting points when coming up with an efficient solution but generally would not be accepted in an interview setting.

**Comment by Veeit** [comment]
Then I would recommend to remove this solution from your official solutions. If you don't accept it and we can't run, it is not a valid solution that you should promote.

**Comment by LC-Pam** [comment]
Thank you for reach out to us. I've delivered your message to our solution team.
