### ISSUE TITLE
Missing Test Case - 1419. Minimum Number of Frogs Croaking

### ISSUE THREAD

**Issue by goyalayush25** [LeetCode-Feedback/LeetCode-Feedback#7235]
#### Your LeetCode username

ayush_2510

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [Yes ] Missing Test Cases 

#### Description of the bug

Missing test case: "ckckroaroa". This test case is not used in 56 test cases provided. According to this test case k cannot appear before 'r','o','a'.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minNumberOfFrogs(string croakOfFrogs) {
        if(croakOfFrogs.length()<5)
            return -1;
        if(croakOfFrogs[0]!='c')
            return -1;
        unordered_map<char,int>mp;
        for(int i=0;i<croakOfFrogs.length();i++)
        {
            mp[croakOfFrogs[i]]++;
        }
        int x=croakOfFrogs.length()/5;
        for(char c:croakOfFrogs)
        {
            if(mp[c]!=x)
                return -1;
        }
        int countc=0;
        int countk=0;
        int ans=INT_MIN;
        for(int i=0;i<croakOfFrogs.length();i++)
        {
            if(croakOfFrogs[i]=='c')
            {
                mp[croakOfFrogs[i]]--;
                countc++;
            }    
            if((croakOfFrogs[i]=='r' && mp[croakOfFrogs[i]]>mp['c'] && mp[croakOfFrogs[i]]<=mp['k']) || (croakOfFrogs[i]=='o' && mp[croakOfFrogs[i]]>mp['c'] && mp[croakOfFrogs[i]]>mp['r'] && mp[croakOfFrogs[i]]<=mp['k']) || (croakOfFrogs[i]=='a' && mp[croakOfFrogs[i]]>mp['c'] && mp[croakOfFrogs[i]]>mp['r'] && mp[croakOfFrogs[i]]>mp['o'] && mp[croakOfFrogs[i]]<=mp['k'])) 
            {
                mp[croakOfFrogs[i]]--;
            }
            else if (croakOfFrogs[i]=='r' || croakOfFrogs[i]=='o' || croakOfFrogs[i]=='a')
            {
                return -1;
            }
            if(croakOfFrogs[i]=='k')
            {
                mp[croakOfFrogs[i]]--;
                countk--;
            }  
            ans=max(ans,countc+countk);
            
        }
        return ans;
    }
};
```

#### Language used for code

C++

**Comment by stormsunshine** [comment]
The code you provide in this issue can pass this test case. If you think a test case is missing, you should provide the code that can get accepted for the time being but fails on the specific test case.

**Comment by goyalayush25** [comment]
class Solution {
public:
    int minNumberOfFrogs(string croakOfFrogs) {
        if(croakOfFrogs.length()<5)
            return -1;
        if(croakOfFrogs[0]!='c')
            return -1;
        unordered_map<char,int>mp;
        for(int i=0;i<croakOfFrogs.length();i++)
        {
            mp[croakOfFrogs[i]]++;
        }
        int x=croakOfFrogs.length()/5;
        for(char c:croakOfFrogs)
        {
            if(mp[c]!=x)
                return -1;
        }
        int countc=0;
        int countk=0;
        int res=0;
        int ans=INT_MIN;
        int countr=0;
        for(int i=0;i<croakOfFrogs.length();i++)
        {
            if(croakOfFrogs[i]=='c')
            {
                mp[croakOfFrogs[i]]--;
                countc++;
            }    
            if((croakOfFrogs[i]=='r' && mp[croakOfFrogs[i]]>mp['c']) || (croakOfFrogs[i]=='o' && mp[croakOfFrogs[i]]>mp['c'] && mp[croakOfFrogs[i]]>mp['r']) || (croakOfFrogs[i]=='a' && mp[croakOfFrogs[i]]>mp['c'] && mp[croakOfFrogs[i]]>mp['r'] && mp[croakOfFrogs[i]]>mp['o'])) 
            {
                mp[croakOfFrogs[i]]--;
            }
            else if (croakOfFrogs[i]=='r' || croakOfFrogs[i]=='o' || croakOfFrogs[i]=='a')
            {
                return -1;
            }
            if(croakOfFrogs[i]=='k')
            {
                mp[croakOfFrogs[i]]--;
                countk--;
            }  
            ans=max(ans,countc+countk);
            
        }
        return ans;
    }
};

This code passes all the test cases provided at leetcode but could not pass missing test case: "ckckroaroa" . This test case is not used in 56 test cases provided.
