### ISSUE TITLE
Incorrect solution: #480 Sliding Window Median, Approach #2

### ISSUE THREAD

**Issue by dlqqq** [LeetCode-Feedback/LeetCode-Feedback#7237]
#### Your LeetCode username

david-qiu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I believe the time and space complexity of approach 2 in problem 480 is wrong. In summary it argues that the time complexity of the two heaps approach is `O(n lg k)`, which I contest to be `O(n lg n)`. I further contest that the space complexity of the two heaps approach has a space complexity of `O(n)` instead of `O(k)`. Please read [my write up here](https://leetcode.com/problems/sliding-window-median/discuss/2020634/Official-solution-has-wrong-time-complexity-for-Two-Heaps-approach), where I go into further detail and provide counter-examples.

To resolve this, the problem deserves further clarification that either:

- states the complexities are estimated and not rigorous
- proves that the average-case time complexity is indeed `O(n lg k)` given certain assumptions about the distribution of `nums`
- replaces approach 2 with the standard `delete()` implementation I propose

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

N/A

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Yani** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for sharing your concern regarding this issue. We agree that there is potential for the heaps to grow with respect to O(n). Our team is aware of the issue and will update the time and space complexity for this approach (and look into whether other approaches also need to be updated).

**Comment by dlqqq** [comment]
@LC-Pam Can I get a shirt or a badge or something as a reward? I wanna show off to my friends 😅
