### ISSUE TITLE
Problem description contradicts Example outputs- 18. 4Sum

### ISSUE THREAD

**Issue by joseville1001** [LeetCode-Feedback/LeetCode-Feedback#7238]
#### Your LeetCode username
joseville

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem description says "a, b, c, and d are distinct.", but the Examples contradict this. 

Example 1 says:
```
Input: nums = [1,0,-1,0,-2,2], target = 0
Output: [[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]
```
In `[-2,0,0,2]` and `[-1,0,0,1]`, `b` and `c` are not distinct as `0 = b = c`.

Example 2 says:
```
Input: nums = [2,2,2,2,2], target = 8
Output: [[2,2,2,2]]
```
In `[2,2,2,2]`, `a`, `b`, `c`, and `d` are not distinct as `2 = a = b = c = d`.

**Comment by stormsunshine** [comment]
In problem description, a, b, c and d are **indices**, not **elements**. The problem description means that the indices are different, and all these examples meet the requirement that indices are different.
