### ISSUE TITLE
Typo in Explore card for DP

### ISSUE THREAD

**Issue by EvgeniiFrolov** [LeetCode-Feedback/LeetCode-Feedback#7239]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In [the Explore card for DP](https://leetcode.com/explore/learn/card/dynamic-programming/632/common-patterns-in-dp-problems/4109/) there is an error in the following sentence:

> We can precompute an array hardestJobRemaining hardestJobRemaining where hardestJobRemaining[i] hardestJobRemaining[i] represents the difficulty of the hardest job on or after day i, so that **we** this base case is handled in constant time.

#### Expected behavior

The expected wording would be without the odd "we":

> We can precompute an array hardestJobRemaining hardestJobRemaining where hardestJobRemaining[i] hardestJobRemaining[i] represents the difficulty of the hardest job on or after day i, **so that this base case is handled in constant time.**

#### Screenshots

<img width="828" alt="Screenshot 2022-05-09 at 7 30 10 AM" src="https://user-images.githubusercontent.com/6092301/167322438-a957809c-a467-42fc-8f49-6686d5799bc3.png">

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
