### ISSUE TITLE
[1457. Pseudo-Palindromic Paths in a Binary Tree] Javascript Internal Error

### ISSUE THREAD

**Issue by stephencweiss** [LeetCode-Feedback/LeetCode-Feedback#724]
#### Your LeetCode username
scweiss1

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language

#### Description of the bug

Possibly related to https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/357

I am submitting an answer for the question 1457, and only get Internal Errors (not a Timeout). I'm happy to concede my solution may not be right, but the `Internal Error` doesn't provide any additional guidance.

This has now been replicated on multiple computers / accounts (I had my friend also submit my code, they also received the `Internal Error`

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * function TreeNode(val, left, right) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.left = (left===undefined ? null : left)
 *     this.right = (right===undefined ? null : right)
 * }
 */
/**
 * @param {TreeNode} root
 * @return {number} - the total number of pseudo-palindromic paths
 * a pseudo-palindromic path is one in which the nodes that comprise the path can be rearranged to be a palindrome
 */
var pseudoPalindromicPaths  = function(root) {
    let palindromicPaths = 0

    function seekLeaf(node, path){
      if(!node.left && !node.right && isPseudoPalindromic(path)) {palindromicPaths += 1; }
        path.push(node.val)
      if(node.left){
        seekLeaf(node.left, path )
      }
      if(node.right){      
        seekLeaf(node.right, path)
      }
    }
    seekLeaf(root, [])

    return palindromicPaths
};



/**
 * @param {number[]} path - the nodes that constitute the path
 * @return {boolean}
 */
function isPseudoPalindromic(path){
  let pathSet = new Set()
  path.forEach(value => {
    if(pathSet.has(value)){
      pathSet.delete(value)
    } else {
      pathSet.add(value)
    }
  })
  return pathSet.size <= 1
}
```

#### Language used for code
Javascript

#### Expected behavior

A more useful error message communicating what needs to be done. If it's just wait until Leetcode servers come back up that's fine. Just nice to know :) 

#### Screenshots
<img width="1786" alt="Screen Shot 2020-07-27 at 6 20 32 PM" src="https://user-images.githubusercontent.com/39878535/88601271-e14d3900-d035-11ea-831c-16f0a043718e.png">

**Comment by lc-pam** [comment]
Hi @stephencweiss 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @stephencweiss 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
