### ISSUE TITLE
数据库题目615：本地执行错误不正常

### ISSUE THREAD

**Issue by DamengLiu** [LeetCode-Feedback/LeetCode-Feedback#7241]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**白露塞纳**

**Bug 类型**
- [ ] 题目：615
- [ ] 编程语言：SQL

**描述**
本地执行，发生错误，不能返回正常的对应正常的数据。

**你使用的语言**
SQL

**你提交或者运行的代码**
```
select * from employee;
```

**屏幕截图**

![12](https://user-images.githubusercontent.com/39763537/167353656-67630b8c-fdba-446f-b768-4716f5e12894.jpg)
![13](https://user-images.githubusercontent.com/39763537/167353676-1ec995a2-6182-4603-9eb3-67506bd4d5d3.jpg)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：damengliu 给予积分奖励，请查收。
