### ISSUE TITLE
Path Compression Optimization - Disjoint Set

### ISSUE THREAD

**Issue by warrenday** [LeetCode-Feedback/LeetCode-Feedback#7242]
#### Your LeetCode username
warrenjday

#### Category of the bug
- [X] Question

#### Description of the bug
Mismatch between pseudo code in video and in text.

In the tutorial on disjoint sets with path compression, the example code shows a union function which assigns the "root" to each vertex.

https://leetcode.com/explore/featured/card/graph/618/disjoint-set/3880/

```
public void union(int x, int y) {
      int rootX = find(x);
      int rootY = find(y);
      if (rootX != rootY) {
          // Here the example is already assigning the root node when we make a union
          root[rootY] = rootX;
      }
 }
```

The tutorial later goes on to show an optimisation of the find method called "path compression" which will assign the root to each vertex to avoid needing to loop through each vertex to eventually find the root.

```
public int find(int x) {
    if (x == root[x]) {
        return x;
    }
    return root[x] = find(root[x]);
}
```

This optimisation doesn't achieve anything given the union is already assigning the root.

The pseudo-code in the example video shows a union function which assigns the "parent" node. In which case the path compression is valid.
<img width="277" alt="Screenshot 2022-05-09 at 09 19 43" src="https://user-images.githubusercontent.com/2871038/167369289-5f7ac3e1-586b-4214-ae21-eaf31ac9c4ef.png">

The example code and the code in the video mismatch. In one the union method assigns the parent, in the other the union method assigns the root.

```
public void union(int x, int y) {
      int rootX = find(x);
      int rootY = find(y);
      if (rootX != rootY) {
          // The code in the editor
          root[rootY] = rootX;
          // The code in the video
          root[rootY] = x;
      }
 }
```

**Comment by LC-Pam** [comment]
Dear user, thank you for sharing your concern with us. We are aware of the typo on this line in the video, and as you mentioned, the editor is the correct version. There is a clarifying note under the video that identifies this, although we hope to address this typo in a more permanent way in the future.
