### ISSUE TITLE
Missing Test Case - 1509. Minimum Difference Between Largest and Smallest Value in Three Moves

### ISSUE THREAD

**Issue by Harry-kp** [LeetCode-Feedback/LeetCode-Feedback#7244]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A solution which is supposed to fail is accepted because some strong test cases are missing.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
    int minDifference(vector<int>& nums) {
        int n = nums.size();
        if(n<5)
            return 0;
        int ans = 2*1000000000-1;
        sort(nums.begin(),nums.end());
        for(int i = 0;i<4;i++){
            ans = min(ans,nums[n-4+i]-nums[i]);
        }
        return ans;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

The solution should give wrong answer but the solution got accepted.
For this test case:-
[-1000000000,-1000000000,-1000000000, -1000000000,1000000000,1000000000,1000000000,1000000000,1000000000,1000000000]
Expected Answer = 2000000000
My Answer = 1999999999

#### Additional context

[-1000000000,-1000000000,-1000000000, -1000000000,1000000000,1000000000,1000000000,1000000000,1000000000,1000000000]
Add this test case for this problem, as it will give the maximum possible ans for this question i.e. 1000000000-(-1000000000) = 2000000000

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
