### ISSUE TITLE
456. 132 Pattern bug

### ISSUE THREAD

**Issue by radimkohout** [LeetCode-Feedback/LeetCode-Feedback#7245]
#### Your LeetCode username

radimkohout

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The 132 Pattern (assingment 456.)  has > instead of < in assignment
Current state: Given an array of n integers nums, a 132 pattern is a subsequence of three integers nums[i], nums[j] and nums[k] such that i < j < k and nums[i] < nums[k] < nums[j].

#### Code you used for Submit/Run operation

```
Not relevant
```

#### Language used for code

Not relevant

#### Expected behavior

Given an array of n integers nums, a 132 pattern is a subsequence of three integers nums[i], nums[j] and nums[k] such that i < j < k and nums[i] < nums[k] > nums[j].

(Change < with > between nums[k] and nums[j] )

In current state the examples are not consistent with assingment

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stormsunshine** [comment]
Why do you think it should be >? Among three indices i, j, k where i < j < k, nums[j] is the largest element, so it is indeed nums[i] < nums[k] < nums[j]. Which example is not consistent with the description?

**Comment by LC-Pam** [comment]
Thank you for your time.  The correct statement should be "i < j < k and nums[i] < nums[k] < nums[j] ", appreciate your support!

**Comment by radimkohout** [comment]
I was going to write there a huge analysis on the examples, but I received a notification about the issue being resolved last minute before posting 😄 . Anyway, thank you too.

**Comment by radimkohout** [comment]
Bump
