### ISSUE TITLE
227. Basic Calculator II [ Test Submission does not work for a specific testcase ]

### ISSUE THREAD

**Issue by RafikFarhad** [LeetCode-Feedback/LeetCode-Feedback#725]
#### Your LeetCode username

rafikfarhad

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
If you want to try with the following case for C++, an error produced and the code do not execute. But if you submit the code, the code gets accepted. The error is in the parsing the number as int, if you try with a bigger number, it parses as long long and the error does not happen.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int calculate(string s) {
        stack<long long> st;
        long long i = 0ll, l = s.size();
        long long a = 0ll, b;
        char last = '+';
        while(i < l) {
            if(s[i] == ' ') {
                i++;
                continue;
            };
            a = 0ll;
            while(i<l and isdigit(s[i])) {
                a = a*10ll+s[i]-'0';
                i++;
            }
            if(last == '+' || last == '-') {
                st.push(
                    last == '+' ? a : -a
                );
            } else {
                b = st.top(); st.pop();
                st.push(
                    last == '*' ? a*b : b/a
                );
            }
            if(s[i] == ' ') {
                i++;
            };
            if(i<l) {
                last = s[i++];
            }
        }
        long long ans = 0ll;
        while(st.size()) {
            ans += (st.top());
            st.pop();
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior
If you execute with this test case `"2147483647 + 50 - 55"` then press `Run Code` it will produce an error that :

```
Line 11: Char 15: runtime error: signed integer overflow: 2147483647 + 50 cannot be represented in type 'int' (solution.cpp)
```
but this is not produced by the user code. In the other case if your try with bigger number like `"2147483749 + 50 - 55"` it will work.

#### Screenshots

![Screenshot_20200728_092435](https://user-images.githubusercontent.com/15923187/88615653-3596fe00-d0b4-11ea-8e72-2a945a9a8f03.png)

#### Additional context

If the test case is invalid it should not pass the bigger testcase, so I think it may be a bug on the test case parsing program.

**Comment by lc-pam** [comment]
Hi @RafikFarhad 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @RafikFarhad 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
