### ISSUE TITLE
1141 测试用例已更新，题解答案需要更新

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#7250]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [ ] 题目
- [√] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目测试用例已经更新，原 [力扣官方题解](https://leetcode.cn/problems/user-activity-for-the-past-30-days-i/solution/cha-xun-jin-30tian-huo-yue-yong-hu-shu-by-leetcode/) 中的答案需要更新

**你使用的语言**
MYSQL

**你提交或者运行的代码**
- 原题解答案
```
SELECT activity_date AS day, COUNT(DISTINCT user_id) AS active_users
FROM Activity
WHERE datediff('2019-07-27',activity_date) < 30
-- WHERE activity_date BETWEEN '2019-06-28' AND '2019-07-27'
GROUP BY activity_date
```
该答案无法通过测试用例
> {"headers":{"Activity":["user_id","session_id","activity_date","activity_type"]},"rows":{"Activity":[[1,1,"2019-07-20","open_session"],[1,1,"2019-07-20","scroll_down"],[1,1,"2019-07-20","end_session"],[2,4,"2019-07-20","open_session"],[2,4,"2019-07-21","send_message"],[2,4,"2019-07-21","end_session"],[3,2,"2019-07-21","open_session"],[3,2,"2019-07-21","send_message"],[3,2,"2019-07-21","end_session"],[4,3,"2019-08-25","open_session"],[4,3,"2021-08-25","end_session"]]}}

**期望行为**
- 正确答案：考虑 activity_date 超过 `2019-07-27` 的测试用例
```
SELECT activity_date AS day, COUNT(DISTINCT user_id) AS active_users 
FROM Activity 
WHERE DATEDIFF('2019-07-27', activity_date) BETWEEN 0 AND 29 
GROUP BY activity_date
```

**屏幕截图**
![image](https://user-images.githubusercontent.com/4961543/167544926-3da7ccb9-fbd9-40c9-8745-b060e32cc3db.png)

**额外的上下文**
添加额外的上下文信息

**Comment by zuizaiqinshi** [comment]
力扣用户您好，您的反馈我们已收到，目前已将该题解下线。感谢您的反馈～
