### ISSUE TITLE
No solution available for 4. Median of two sorted arrays

### ISSUE THREAD

**Issue by sudip-mondal-2002** [LeetCode-Feedback/LeetCode-Feedback#7251]
#### Your LeetCode username

sudip_mondal

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is no solution for the question 4. Median of two sorted arrays

#### Code you used for Submit/Run operation

```

class Solution {
public:
    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {
        int len1=nums1.size();
int len2=nums2.size();
double median;
int arr[len1+len2], i, j, m;

    for(i=0;i<len1;i=i+1)
    {
        arr[i]=nums1[i];
        
    }
    
    for(j=i;j<len1+len2;j=j+1)
    {
        arr[j]=nums2[j-i];
    }
    
    sort(arr, arr+len1+len2);
    
    if((len1+len2)%2==0)
    {
        m=((len1+len2)/2)-1;
        median=arr[m]+arr[m+1];
        median=median/2.0;
        return median;
    }
    else if((len1+len2)%2==1)
    {
        m=(len1+len2)/2;
        median=arr[m];
        
        return median;
    }
    
    
    return median;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

Need a solution to the code

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.
I have submitted your feedback to our solution team and they will start to work on it.
But it gonna take some time to add.

Thank you for you support!
