### ISSUE TITLE
Missing Test Case - 394. Decode String

### ISSUE THREAD

**Issue by Harry-kp** [LeetCode-Feedback/LeetCode-Feedback#7252]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution which is supposed to give Time Limit Exceeded  is accepted because some strong test cases are missing.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string solve(int& i,string& s){
        int n = s.size();
        string res = "";
        while(i<n){
            if(s[i] == ']'){
                i++;
                return res;
            }
                
            if(s[i]-'a'>=0 and s[i]-'a'<26){
                res+=s[i];
                i++;
            }
            else{
                int val = 0;
                while(i<n and s[i]-'0'>=0 and s[i]-'0'<=9)
                {
                    val = val*10+(s[i]-'0');
                    i++;
                }
                i++;
                string str1 = solve(i,s);
                string str2 = "";
                for(int j = 0;j<val;j++)
                    str2+=str1;
                res+=str2;
            }
        }
        return res;
    }
    string decodeString(string s) {
        int i = 0;
        return solve(i,s);
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

The solution should give Time Limit Exceeded  but the solution got accepted.
For this test case:-
"25[25[25[25[25[25[a]]]]]]"
My solution(which is accepted) will give Time Limit Exceeded.

#### Additional context

I think the constraint on the integers in s as given in the question
- All the integers in s are in the range [1, 300].

should be modified to some less value.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
