### ISSUE TITLE
Invalid Test Case - 36. Valid Sudoku

### ISSUE THREAD

**Issue by ashwinkumar9931** [LeetCode-Feedback/LeetCode-Feedback#7257]
In the Problem the test case gives 'true' rather than giving false :

[[".","8","7","6","5","4","3","2","1"],["2",".",".",".",".",".",".",".","."],["3",".",".",".",".",".",".",".","."],["4",".",".",".",".",".",".",".","."],["5",".",".",".",".",".",".",".","."],["6",".",".",".",".",".",".",".","."],["7",".",".",".",".",".",".",".","."],["8",".",".",".",".",".",".",".","."],["9",".",".",".",".",".",".",".","."]]

Which Looks Like: 
[".","8","7","6","5","4","3","2","1"]
,["2",".",".",".",".",".",".",".","."]
,["3",".",".",".",".",".",".",".","."]
,["4",".",".",".",".",".",".",".","."]
,["5",".",".",".",".",".",".",".","."]
,["6",".",".",".",".",".",".",".","."]
,["7",".",".",".",".",".",".",".","."]
,["8",".",".",".",".",".",".",".","."]
,["9",".",".",".",".",".",".",".","."]

According to the question, the rules of sudoku are:

> Each row must contain the digits 1-9 without repetition.
> Each column must contain the digits 1-9 without repetition.
> Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.

But as you can see the result of the above test case at position (0,0) will be 'False' Since no number can fill that place. But the expected answer gives 'True'.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment]
Didn't you see the notes? A Sudoku board (partially filled) could be valid but is not necessarily solvable.

For this problem, you should NOT consider whether the Sudoku is solvable. You should only consider whether the numbers already filled in are valid or not.
