### ISSUE TITLE
Bug in constraints 

### ISSUE THREAD

**Issue by arpit456jain** [LeetCode-Feedback/LeetCode-Feedback#7258]
#### Your LeetCode username

111arpit1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] constraints

#### Description of the bug

In question its mentioned to find the subsets having 132 pattern 
It should not work for array having less than 3 elements but its working and not giving any error of invalid constraint

#### Code you used for Submit/Run operation

```
bool find132pattern(vector<int>& nums) {
       stack<pair<int,int>> s;
        int minval = nums[0];
        
        for(int i=1;i<nums.size();i++)
        {
            while(!s.empty() and s.top().first<nums[i] )
                s.pop();
            
            // cur should br less than top of stack and greater than minval
            if(!s.empty() and nums[i]> s.top().second)
                return true;
            
            pair<int,int> p = make_pair(nums[i],minval);
            s.push(p);
            minval = min(minval,nums[i]);
            
        }
        
        return false;
```

#### Expected behavior

 it should be  3 <= n <= 2 * 105
instead of 1 <= n <= 2 * 105

#### Screenshots

<img width="607" alt="image" src="https://user-images.githubusercontent.com/55352601/167703432-721c07c5-de7f-4f4c-ba5b-9bd53e78e15b.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Leader-board** [comment]
It should be https://leetcode.com/problems/132-pattern/ from the OP's description.

**Comment by arpit456jain** [comment]
> It should be https://leetcode.com/problems/132-pattern/ from the OP's description.

yes @Leader-board thanks 

problem number : 456 : [132 Pattern 
](https://leetcode.com/problems/132-pattern/)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. A clean code should pass this without a special if statement. We appreciate your support!
