### ISSUE TITLE
1488题：题目表述不清

### ISSUE THREAD

**Issue by everythingCanBeModeled** [LeetCode-Feedback/LeetCode-Feedback#7264]
**你的 LeetCode 用户名**
everythingCanBeModeled

**Bug 类型**
- [ ] 题目表述不清

**描述**
1488题：题目描述为：如果第 n 个湖泊是满的，这个湖泊会发生洪水 。

表述不清，到底是满了就算洪水还是满了再下雨是洪水。

**期望行为**
建议修改为  如果下雨时第 n 个湖泊是满的，这个湖泊会发生洪水。  或者其他类似的表述。

**屏幕截图**
![image](https://user-images.githubusercontent.com/75769380/167884190-dfd51000-ad5d-4d41-80bf-66adbf9f1db5.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：everythingCanBeModeled 给予积分奖励，请查收。
