### ISSUE TITLE
Missing Test Case - 76. Minimum Window Substring

### ISSUE THREAD

**Issue by Harry-kp** [LeetCode-Feedback/LeetCode-Feedback#7267]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution which is supposed to fail is accepted because some strong test cases are missing.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
    string minWindow(string s, string t) {
        int l1 = s.size();
        int l2 = t.size();
        int str[256]{},pat[256]{};
        int l = 0,min_len = 100000,start = -1;
        
        if(l1<l2)return "";
        
        for(int i = 0;i<l2;i++)pat[t[i]]++;
        
        int cnt = 0;
        for(int i = 0;i<l1;i++){
            str[s[i]]++;
            
            if(str[s[i]]<=pat[s[i]])
                cnt++;
            
            //substring found
            if(cnt == l2){
                
                //minimize it
                while(str[s[l]]>pat[s[l]]){
                    str[s[l]]--;
                    l++;
                }
            
            
            int len = i-l+1;
            
            if(min_len>len){
                start = l;
                min_len = len;
            }
            
        }
        
        
    }
        if(min_len == 100000)return "";
        return s.substr(start,min_len);
    }
          
};
```

#### Language used for code
 C++

#### Expected behavior

The solution should give wrong answer but the solution got accepted.
For the worst  test case i.e both s and t are same and of size =  100000 :-
s = "aaaaa......100000 times" 
t = "aaaaa.......100000 times"
Expected Answer = "aaaaa.......100000 times"
My Answer = ""

#### Additional context

Add the above mentioned test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. The status is pending right now, the content team will make the decision.  We appreciate your support!
