### ISSUE TITLE
Constraint bug in the question

### ISSUE THREAD

**Issue by AnurimaVaishnavi** [LeetCode-Feedback/LeetCode-Feedback#7268]
#### Your LeetCode username

anurimavaishnavi13

#### Category of the bug
- [ **] Question - https://leetcode.com/problems/find-k-th-smallest-pair-distance/ 
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

It is mentioned in the question that any (i,j) pairs should obey the constraints : 0<=i<j<n.
Hence, we cannot sort the array. Solution 3 is doing arrays.sort()

#### Code you used for Submit/Run operation

```
class Solution:
    def smallestDistancePair(self, nums: List[int], k: int) -> int:
        nums.sort()
        n=len(nums)
        low,high=0,nums[n-1]-nums[0]
        while(low<=high):
            mid=(low+high)//2
            count = self.smallerthanorequal(nums,mid,n)
            if count<k:
                low=mid+1
            else:
                high=mid-1
        return low
    def smallerthanorequal(self,nums,mid,n):
        left=0
        cnt=0
        for right in range(0,n):
            while(abs(nums[right]-nums[left])>mid):
                left+=1
            cnt+=right-left
        return cnt

```

#### Language used for code

 Python

#### Expected behavior

Based on the constraints mentioned for i,j in the question - I shouldnt be sorting the array and still get the right answer. Constraints should be changed to 0<=i<=j<n from 0<=i<j<n

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.The O(nlogn) solution requires you to sort the array. The original constraints are correct because "0 <= i < j < n" is identical to "every pair of elements is counted exactly once". We appreciate your support!
