### ISSUE TITLE
Problem Description issue - 1079. Letter Tile Possibilities

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#727]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Steps:

1. Goto https://leetcode.com/problems/letter-tile-possibilities/
2. Read description & examples:

Questions:

Q1. Problem says "You have a set of tiles"
Does this mean a mathematical Set?
Because, a Set does not have duplicates, but an Example has AAB

Q2. Problem says "Return the number of possible non-empty sequences of letters you can make."
How is BA is a sequence of AAB
Because, in the sequence, ORDER matters.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Problem description is unclear due to usage of `set` & `sequence`

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
