### ISSUE TITLE
Missing Test Case - 49. Group Anagrams

### ISSUE THREAD

**Issue by Zeks** [LeetCode-Feedback/LeetCode-Feedback#7272]
It is possible to create an incorrect xor based solution that nevertheless passes the current validation. This input pair is what should break it:
```
aaaabcabcaaaabc
abababababababc
```

"solution" in question: https://leetcode.com/problems/group-anagrams/discuss/2027223/A-rather...-insane-solution-that-passes-blazingly-fast.-Need-help-validating-beyond-leetcode-tests.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
