### ISSUE TITLE
Missing Test Case - 148. Sort List

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7274]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [148. Sort List](https://leetcode.com/problems/sort-list), a solution that can get accepted will get TLE on a specific test case.

The test case is: [148.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8679513/148.txt)

#### Code you used for Submit/Run operation
```Java
class Solution {
    public ListNode sortList(ListNode head) {
        if (head == null || head.next == null) {
            return head;
        }
        ListNode dummyHead = new ListNode(0, head);
        ListNode end = head;
        while (end.next != null) {
            if (end.val <= end.next.val) {
                end = end.next;
            } else {
                ListNode prev = dummyHead, next = end.next;
                while (prev.next.val <= next.val) {
                    prev = prev.next;
                }
                end.next = next.next;
                next.next = prev.next;
                prev.next = next;
            }
        }
        return dummyHead.next;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Add the test case so that the code above will get TLE when submitted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. (Added the test case.
However, the code linked still passes in some of the new judgers (lc-aws-dedicated).)
Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
