### ISSUE TITLE
题目1355 测试用例若有并未被参加的活动。 会导致不连接的代码也能过。

### ISSUE THREAD

**Issue by cyrilney** [LeetCode-Feedback/LeetCode-Feedback#7275]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [√] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
看别人的题解的时候发现有一个双百的题解没有连接两张表就算出结果了。  而如果有活动没有被参加的情况，这样的方法应该有问题才对
比如下面测试用例：
{"headers": {"Friends": ["id", "name", "activity"], "Activities": ["id", "name"]}, "rows": {"Friends": [[1, "Jonathan D.", "Eating"], [2, "Jade W.", "Singing"], [3, "Victor J.", "Singing"], [4, "Elvis Q.", "Eating"], [5, "Daniel A.", "Eating"]], "Activities": [[1, "Eating"], [2, "Singing"], [3, "Horse Riding"]]}}
我看到预期结果是[Singing] 而不连接的代码的输出是 []   是不是测试用例有误  或者题目描述不准确呢？

关键对活动表中：
中文的描述是 「Activities 表的每项活动的参与者都来自 Friends 表。」 我的理解是「没有Friends表以外的参与者」
英文的表述 「Each activity in the Activities table is performed by any person in the table Friends.」 是说 「Activities表中的任意活动都在Friends中参与过」  

也许翻译的问题的可能性更大， 烦请确认后修正。

**你使用的语言**
MySQL

**你提交或者运行的代码**   
```
# 代码来自题解
select activity as ACTIVITY
from friends
group by activity
having count(*)>any(
    select count(*) from friends group by activity
) and count(*)<any(
    select count(*) from friends group by activity
)


```

**期望行为**
添加用例或补全解释

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目问题已修复，请知晓。
