### ISSUE TITLE
Missing Test Case - 1005. Maximize Sum Of Array After K Negations

### ISSUE THREAD

**Issue by kohler172** [LeetCode-Feedback/LeetCode-Feedback#7277]
#### Your LeetCode username

sleepy_jack_the_fire_drill

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug

My initial code assumed that k was odd if the input array consisted of all positive values.  

This assumption is incorrect but my code still passed submission as there are no test cases where the input array is all positive values and k is even.

#### Code you used for Submit/Run operation

```
 public int largestSumAfterKNegations(int[] nums, int k) {
        Arrays.sort(nums);
		int i;

		for (i = 0; i < nums.length; i++) {
			if (nums[i] >= 0 || k == 0) break;
			nums[i] *= -1;
			k--;
		}

		int sum = 0;

		for (int val : nums) sum += val;
		

		if (i == 0 || i == nums.length)
			return sum - 2 * Math.min(nums[0], nums[nums.length - 1]);

		if (k % 2 == 1 && nums[i] != 0) {
            return sum - 2 * Math.min(nums[i], nums[i-1]);				
		}
        
		return sum;
    }
```

#### Language used for code

Java

#### Expected behavior

My code doesn't pass test cases where every value in the input array is positive and k is even, yet my code passed submission successfully.

The addition of a case like this would identify this issue in others' code:
[4,2,3]
2

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, your code got compile error when we test it, please send us your Accepted link or feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
