### ISSUE TITLE
Incomplete question - 784. Letter Case Permutation

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#728]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Incomplete question - 784. Letter Case Permutation

784. Letter Case Permutation
https://leetcode.com/problems/letter-case-permutation/

Please add below to the question:
	`Order of elements of the output can be anything.`

Example test case:

	Accepted
		Runtime: 84 ms
			Your input		"a"
			Output			["A","a"]
			Expected		["a","A"]

Please note that output & expected differ in order.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Expected: Question should be complete, see description.
Actual: Question misses an important detail, see description, that wastes dev time.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Since it's a well-known issue for old problems, this report is not eligible for LeetCoins reward. We appreciate your support!
