### ISSUE TITLE
Solution accepted but the submissions tab says "time limit exceeded"

### ISSUE THREAD

**Issue by pfernandez** [LeetCode-Feedback/LeetCode-Feedback#7281]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution was "accepted" but the submissions tab says "time limit exceeded". Clicking it gives an error indicating that leetcode does not understand the spread operator: https://leetcode.com/submissions/detail/698430560/.

#### Code you used for Submit/Run operation

```js
// Two Sum
var twoSum = function(nums, target) {
    const numsMap = nums.reduce((a, v, i) => ({ ...a,  [v]: i }), {}) 
     
    for(let i = 0; i < nums.length; i++) {
        const n = nums[i]
        const comp = target - n
        const compIdx = numsMap[comp] 
        
        if(typeof compIdx === 'number' && compIdx != i) {
            return [i, compIdx]
        }
    }
};
```

#### Language used for code

JavaScript

#### Expected behavior

The same (modern) JS engine should be used for both _Run Code_ and _Submit_.

#### Screenshots

<img width="954" alt="Screen Shot 2022-05-12 at 7 32 08 PM" src="https://user-images.githubusercontent.com/458926/168199830-65b3fea4-37d4-4738-9346-581da34e81c8.png">

#### Additional context

Using Chrome 101.0.4951.64 on MacOS 12.3.1

**Comment by LC-Pam** [comment]
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
