### ISSUE TITLE
题目2032

### ISSUE THREAD

**Issue by 476037156** [LeetCode-Feedback/LeetCode-Feedback#7282]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
15886653053
**Bug 类型**

- [2032] 题解

**描述**
题目说构造返回与这三个数组不相同的数组，但是很多题解存在问题.

**你使用的语言**
JAVA

**你提交或者运行的代码**
```
class Solution {
    public List<Integer> twoOutOfThree(int[] nums1, int[] nums2, int[] nums3) {
        List<Integer> res = new ArrayList<>();
        int[] cache = new int[101];
        for (int x : nums1) {
            cache[x] = 1;
        }
        for (int x : nums2) {
            if (cache[x] <= 1) {
                cache[x] += 1;
                cache[x] <<= 1;
                if(cache[x]==4) res.add(x);
            }
            
        }
        for (int x : nums3) {
            if (cache[x]==1||cache[x]==2){
                cache[x]+=4;
                res.add(x);
            }
        }
        return res;
    }
}
```

**期望行为**
[1,2]

**屏幕截图**
![image](https://user-images.githubusercontent.com/89445072/168202967-8bd971a6-deb1-480c-90fa-e1d71a12d9cb.png)

**额外的上下文**
结果返回和数组1一样，但是提交通过了。我觉得这是一个bug。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题面已调整，请知晓。
