### ISSUE TITLE
The article missing a possible O(N) solution.

### ISSUE THREAD

**Issue by KarthikGangadhar** [LeetCode-Feedback/LeetCode-Feedback#7284]
#### Category of the bug
- [1 ] Solution

#### Description of the bug

[252. Meeting Rooms](https://leetcode.com/problems/meeting-rooms/solution/) It's not a bug report, but a possible O(n) solution is not mentioned In the article,  The provided solution is O(nlog(n)), there is an O(n) solution that exists for the problem. please find the detail below.

#### Code you used for Submit/Run operation
```
// Bucket Sort
class Solution:
    def canAttendMeetings(self, intervals: List[List[int]]) -> bool:
        
        '''
        
        1. we have a start and end for each interval.
        2. sort the intervals based on start time, (can be done using O(n), counting sort if                they are not floating points)
        3. compare the last end time with the current start time to see if they are overlapping,
           1. if overlapping return False
           2. if not continue to the last element
        4. if none of them are overlapping, return True
        
        '''
        
        if not intervals: return True
        
        maxStart = max(start for start,_ in intervals)
        N = len(intervals)
        
        buckets = [[] for _ in range(maxStart+1)]
        
        for i,[start, end] in enumerate(intervals):
            buckets[start].append(i)
        
        sortedIntervals = []
        for i in range(maxStart+1):
            if not buckets[i]: continue
            for j in buckets[i]:
                sortedIntervals.append(intervals[j])
        
        for i in range(1,N):
            if sortedIntervals[i-1][1] > sortedIntervals[i][0]:
                return False
        
        return True
```

#### Language used for code

Python3

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for sharing your proposed solution. The runtime for your proposed solution is O(N + M) and requires O(N + M) space where N is the number of intervals and M is the maximum possible meeting time. The solution works well when M is small, but for larger M values this solution may face time or memory issues. In an interview setting, this could be an optimization if the interviewer asks a follow-up question to solve the problem in linear time or tells us that the maximum meeting time is small. We might consider adding an approach similar to this in the future (your approach is similar to the line-scan approach for interval problems)
