### ISSUE TITLE
472题 翻译错误

### ISSUE THREAD

**Issue by da-pang-za** [LeetCode-Feedback/LeetCode-Feedback#7285]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**Bug 类型**
- [ * ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

英文版 0 <= words[i].length <= 30   中文版 0 <= words[i].length <= 1000

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目翻译问题已修复，请知晓。
