### ISSUE TITLE
#13 Roman to Integer (Testcase Input !== Submission Output)

### ISSUE THREAD

**Issue by hermiecapela** [LeetCode-Feedback/LeetCode-Feedback#7286]
[#13 Roman to Integer](https://leetcode.com/problems/roman-to-integer/) reports incorrect input after submission with the JavaScript form. Here is the pattern of the discrepancies between the test inputs and submission results.

a) if test input was "III", submission assumed "LVIII"
b) if test input was "LVIII", submission assumed "III"
c) if test input was "MCMXCIV", submission assumed "III"

Included an image of the error, as well as the JavaScript code.

![Screenshot from 2022-05-13 03-57-05](https://user-images.githubusercontent.com/105347876/168269691-f5228a73-d707-4fa2-930b-0b8484ba0194.png)

```js
/**
 * @param {string} s
 * @return {number}
 */

let s = "MCMXCIV";

const decimalValue = {
  'I': 1,
  'V': 5,
  'X': 10,
  'L': 50,
  'C': 100,
  'D': 500,
  'M': 1000
};

let sum = 0;
let number = 0;

const numeral = s.split('');
console.log(numeral);
console.log("has " + numeral.length + " elements\n");

var romanToInt = function(s) {
  for (let i = 0; i < numeral.length + 1; i++) {
    if (i === 0) {
      var previousValue = undefined;
    } else {
      var currentValue = decimalValue[numeral[i]]
      if (previousValue < currentValue ) {
        sum -= previousValue;
      } else if (previousValue >= currentValue || currentValue === undefined) {
        sum += previousValue;
      }
    }
    console.log("previous was: " + previousValue);
    console.log("current is: " + decimalValue[numeral[i]]);
    console.log("sum = " + sum + "\n");
    previousValue = decimalValue[numeral[i]];
  }
  number = sum;
  return number;
}

// romanToInt();
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
