### ISSUE TITLE
Shopee-001  Shopee Tanam 不显示未通过的测试样例

### ISSUE THREAD

**Issue by WTAiCP** [LeetCode-Feedback/LeetCode-Feedback#7287]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [√] 缺少测试用例

**描述**
有通过过不了样例，但是不明白哪种样例通过不了，所以可否提供未通过样例

**你使用的语言**
JAVA

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
在未通过时，展示出未通过的样例

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。
