### ISSUE TITLE
Wrong explanation in comments about how to initialize a Trie data structure node

### ISSUE THREAD

**Issue by sagargaddam** [LeetCode-Feedback/LeetCode-Feedback#7289]
#### Your LeetCode username

SagarGaddam

#### Category of the bug
- [ *] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the article "How to represent a Trie", there is a mistake in the comment explaining about how to initialize a trie data structure in c++ .  The code of creating a trie structure in c++ contains following lines in comments
" 
/** Usage:
 *  Initialization: TrieNode root = new TrieNode();
 *  Return a specific child node with char c: (root->children)[c - 'a']
 */
"

In the second line, it should be
"  *  Initialization: TrieNode **\*** root = new TrieNode(); "

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/13523992/168275307-337fa68e-a0de-4f48-9cbf-264c2c25ba01.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
