### ISSUE TITLE
Easy Database Question

### ISSUE THREAD

**Issue by grsl** [LeetCode-Feedback/LeetCode-Feedback#729]
#### Your LeetCode username
GRSL

#### Category of the bug
Question

#### Description of the bug
The easy database question involving students and courses has an incorrect value in the expected field. The question asks for a result of Math and the value in the expected result is empty.

#### Code you used for Submit/Run operation
```SELECT Class FROM Courses GROUP BY Class HAVING COUNT(Class) > 4;```

#### Language used for code
SQL

#### Expected behavior
The answer is correct and should have been marked as so.

#### Screenshots
![1](https://user-images.githubusercontent.com/827444/88638363-514dd480-d0b3-11ea-9a8e-5369818acbb9.png)

**Comment by lc-pam** [comment]
Hi @grsl ,
Thanks for reaching out to us. Would you mind providing the problem link or the number of the problem? Thank you!

**Comment by lc-pam** [comment]
Hi @grsl  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
