### ISSUE TITLE
578. Get Highest Answer Rate Question missing test case

### ISSUE THREAD

**Issue by wuxxx725** [LeetCode-Feedback/LeetCode-Feedback#7290]
#### Your LeetCode username

meng-hsuan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

For the following test case,
Question 1285 and 741 were each showed 2 times and answered 1 time. The answer rate of them are 0.5.
Question 369 was showed 1 time and was not answered. The answer rate of it is 0.0.

From the problem description, "if multiple questions have the same maximum answer rate, report the question with the smallest `question_id`."  Since Questions 1285 and 741 both have the highest answer rate, the question with the smaller `question_id` should be chosen, i.e. 741 rather than 1285.
```
{"headers": {"SurveyLog": ["id", "action", "question_id", "answer_id", "q_num", "timestamp"]}, "rows": {"SurveyLog": [[5, "show", 1285, null, 1, 121],[5, "answer", 1285, 122122, 1, 122], [5, "show", 369, null, 2, 123], [5, "skip", 369, null, 2, 124], [5, "show", 741, null, 3, 125], [5, "skip", 741, null, 3, 126], [6, "show", 1285, null, 1, 127], [6, "skip", 1285, null, 1, 128], [6, "show", 741, null, 2, 129], [6, "answer", 741, 130130, 2, 130]]}}
```

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
WITH T1 AS (SELECT question_id, count(question_id) AS n_show FROM SurveyLog WHERE action = "show" GROUP BY question_id), 
T2 AS (SELECT question_id, count(question_id) AS n_answer FROM SurveyLog WHERE action = "answer" GROUP BY question_id), 
T3 AS (SELECT T1.question_id AS question_id, T1.n_show AS n_show, IF(T2.n_answer IS NULL, 0, T2.n_answer) AS n_answer,
       IF(T2.n_answer IS NULL, 0, T2.n_answer) / T1.n_show AS answer_rate FROM T1 LEFT JOIN T2 ON T1.question_id = T2.question_id ORDER BY answer_rate DESC, question_id ASC LIMIT 1) 
SELECT question_id AS survey_log FROM T3
```

#### Language used for code

MySQL

#### Expected behavior

The correct output should be
`{"headers": ["survey_log"], "values": [[741]]}`
instead of
`{"headers": ["survey_log"], "values": [[1285]]}`.

#### Screenshots

<img width="1025" alt="LeetCode 578" src="https://user-images.githubusercontent.com/67871581/168284862-04873810-3bc0-4f1b-a696-57b4c3ac13e1.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
