### ISSUE TITLE
Missing Test Case - 213. House Robber II

### ISSUE THREAD

**Issue by snehel4510** [LeetCode-Feedback/LeetCode-Feedback#7293]
#### Your LeetCode username

snehel4510

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✅] Missing Test Cases 

#### Description of the bug

The following problem states that "All houses at this place are arranged in a circle. That means the first house is the neighbour of the last one."<br>
For a test case where there are only 2 houses : [x1, x2], the answer should be 0 since both houses x1 and x2 are neighbours of each other and the robber cannot rob any of them.  But the expected output comes out to be max(x1, x2) which contradicts the problem statement.

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    const static int N = 110;
    int dp1[N], dp2[N];
    int money1(vector<int> &nums, int ind)
    {
        if (ind < 1)
            return 0;
        if (dp1[ind] != -1)
            return dp1[ind];
        return dp1[ind] = max(nums[ind] + money1(nums, ind - 2), money1(nums, ind - 1));
    }
    int money2(vector<int> &nums, int ind)
    {
        if (ind < 0)
            return 0;
        if (dp2[ind] != -1)
            return dp2[ind];
        return dp2[ind] = max(nums[ind] + money2(nums, ind - 2), money2(nums, ind - 1));
    }
    int rob(vector<int>& nums) {
        if(nums.size() == 1)
            return nums[0];
        if(nums.size() == 2)
            return 0;
        memset(dp1, -1, sizeof(dp1));
        memset(dp2, -1, sizeof(dp2));
        return max(money1(nums, nums.size() - 1), money2(nums, nums.size() - 2));
    }
};
```

#### Language used for code

C++

#### Expected behavior

As already stated above, for a test case of size 2 - both the houses are neighbours since one is the first house and the other is the last house in that place. Thus the answer should be 0 here.

#### Screenshots

![image](https://user-images.githubusercontent.com/79275152/168338413-b9b6d399-f3d2-4684-b951-3649cc03e4aa.png)

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us! Would you mind sending the test case that you used to us?
Thank you.

**Comment by snehel4510** [comment]
Actually, the problem is not about any missing test case, but it's about giving wrong answers on some of the test cases. (Any test case of size 2 - **[x1, x2]**)<br>
For any given test case whose size is 2, the answer should always be zero according to the problem statement, but instead of 0 it gives **max(x1,x2)** which is wrong.<br>
For example:-  for the test case ```[1,2]```, the answer should be 0 but expected output comes out to be 2 after running the test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stormsunshine** [comment]
If the input array's length is 2, then there is a circle with two houses, with values x1 and x2 respectively. You can rob either x1 or x2, so the answer is max(x1, x2). This DOES NOT contradict with problem description, since if you rob only one house, you will never rob two adjacent houses.

Why do you think the return value should be 0?

**Comment by snehel4510** [comment]
Oh, understood! Thanks for the explanation
