### ISSUE TITLE
Missing Test Case - 584. Find Customer Referee

### ISSUE THREAD

**Issue by Kaitachi** [LeetCode-Feedback/LeetCode-Feedback#7295]
#### Your LeetCode username
Kaitachi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Wording is misleading on this problem's explanation. Specifically, the emphasized part from the following quote:

>Write an SQL query to report the *IDs* of the customer that are **not referred by** the customer with `id = 2`.

#### Expected behavior
>Write an SQL query to report the *names* of the customer that are **not referred by** the customer with `id = 2`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
