### ISSUE TITLE
691题 翻译错误

### ISSUE THREAD

**Issue by TOMATOFGY** [LeetCode-Feedback/LeetCode-Feedback#7296]
**你的 LeetCode 用户名**
LitchiDeliver

**Bug 类型**
- [ ] 题目

**描述**
中文版`1 <= target <= 15`
英文版`1 <= target.length <= 15`

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：题面目前看是一致的。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
