### ISSUE TITLE
Ambiguous wording: 743. Network Delay Time

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#7299]
#### Your LeetCode username

Leaderboard

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question description is a bit ambiguous. Consider the below:

> Return the time it takes for all the _n_ nodes to receive the signal.

The problem is that this assumes that the graph is set up in such a way that there is only one possible time taken for the nodes to receive the signal. I think it should be

> Return the **minimum** time it takes for all the _n_ nodes to receive the signal.

To give an example, consider the below test case:

```
[[2,1,1],[2,3,1],[3,4,2],[2,4,1]]
4
2
```

Notice that in this case, there are two ways to reach node 4 (2 -> 4 and 2 -> 3 -> 4) - but the former does it quicker. With the wording as currently defined, it is not clear which approach to take (as both are valid solutions), and that would return different answers (1 vs 3 respectively) depending on the interpretation. 

#### Code you used for Submit/Run operation

Not applicable

#### Language used for code

Not applicable

#### Expected behavior

Described above

#### Screenshots

Not applicable

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
