### ISSUE TITLE
Easy DAtabase Question - SecondHighestSalary

### ISSUE THREAD

**Issue by grsl** [LeetCode-Feedback/LeetCode-Feedback#730]
#### Your LeetCode username
GRSL

#### Category of the bug
Question

#### Description of the bug
The answer is accepted, but when submitted is shown as wrong, which it isn't.

#### Code you used for Submit/Run operation
// SecondHighestSalary
SELECT Salary as SecondHighestSalary FROM Employee ORDER BY SecondHighestSalary DESC LIMIT 1,1
```

#### Language used for code
SQL


#### Expected behavior
My answer to be marked correct.

#### Screenshots
![1](https://user-images.githubusercontent.com/827444/88639120-565f5380-d0b4-11ea-92e6-2147e399fd42.png)




#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-pam** [comment]
Hi @grsl ,
Thanks for reaching out to us. I tried submitting your code and noticed your code didn't pass test case ```{"headers": {"Employee": ["Id", "Salary"]}, "rows": {"Employee": [[1, 100]]}}```. Please note that question requires you to return null if there is no second highest salary. 
<img width="1670" alt="Screen Shot 2020-07-29 at 5 16 35 PM" src="https://user-images.githubusercontent.com/67175512/88866691-49c82180-d1c0-11ea-9511-c0340fa6d233.png">
According to your screenshot, the test case that got accepted is not the test case you failed when submit. When you click run code, it runs single test case you have in Testcase tab. When you click submit, our judge runs all the test cases and shows error message if your code doesn't pass any of them so it's possible you receive different results when running code and submitting code. I hope this answers your question.

**Comment by lc-pam** [comment]
Hi @grsl  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
