### ISSUE TITLE
Chapter about Heap - C++ 

### ISSUE THREAD

**Issue by BAlmeidaS** [LeetCode-Feedback/LeetCode-Feedback#7302]
#### Your LeetCode username

BFAlmeida

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The exercises about heaps should contain C++ references.

Mainly because you start saying that priority queues are not heaps since they are ADTs. C++ has priority queues, and the heap operations on stl::algorithms. It would be amazing if you explain how to use both. 

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
