### ISSUE TITLE
[ 缺少测试用例] 6068. 毯子覆盖的最多白色砖块数

### ISSUE THREAD

**Issue by lawvs** [LeetCode-Feedback/LeetCode-Feedback#7303]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
第 78 场双周赛的 Q3 [6068. 毯子覆盖的最多白色砖块数](https://leetcode.cn/problems/maximum-white-tiles-covered-by-a-carpet/)

没有毯子长度小于白色砖块长度的用例

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```js
/**
 * @param {number[][]} tiles
 * @param {number} carpetLen
 * @return {number}
 */
var maximumWhiteTiles = function (tiles, carpetLen) {
  let cnt = 0;
  let cur = [];
  tiles.sort((a, b) => a[0] - b[0]);

  // console.log(tiles);
  let poi = 0;
  let max = cnt;

  while (poi < tiles.length) {
    const [from, to] = tiles[poi];
    const newLen = to - from + 1;
    // Fix!!!!
    // if (newLen >= carpetLen) {
    //   return carpetLen;
    // }
    poi++;
    cnt += newLen;
    const start = to - carpetLen + 1;

    while (cur.length && cur[0][0] < start) {
      const [curFrom, curTo] = cur[0];

      if (curTo < start) {
        cur.shift();
        cnt -= curTo - curFrom + 1;
        continue;
      }

      cur[0][0] = start;
      cnt -= start - curFrom;
      break;
    }

    cur.push([from, to]);
    // console.log(start, to, cnt, cur, tiles);

    max = Math.max(max, cnt);
  }
  return max;
};

```

**期望行为**
描述你期望的结果

用例
```
[[1,10]]
2

// 预期结果
2
// 实际输出 但是仍然能够通过提交
10
```

![image](https://user-images.githubusercontent.com/18554747/168441390-e4f0471a-d307-491e-8dc2-e610b15ba9bd.png)

![image](https://user-images.githubusercontent.com/18554747/168441175-5375eb97-a05c-4970-8e6f-a35960f83a7c.png)

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：已有类似用例添加。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
