### ISSUE TITLE
Missing Test Case - 2271. Maximum White Tiles Covered by a Carpet

### ISSUE THREAD

**Issue by Akansha-Mittal** [LeetCode-Feedback/LeetCode-Feedback#7305]
#### Category of the bug
- [x] Missing Test Cases 

#### I found out that my code is not able to pass a test case which was created by me. But it passes all the test cases which are currently present for this problem. And my code got accepted. But it should not be accepted because it gives wrong answer for test case which I created. So I want to contribute that test case which should be tested on solutions. Below is that edge test case:
[[1,5],[10,11],[12,18],[20,25],[30,32]]
2

#### Code you used for Submit/Run operation

```
//Maximum White Tiles Covered by a Carpet
class Solution {
    public int maximumWhiteTiles(int[][] tiles, int carpetLen) {
         
        int max = 0,j=0,sum=0;
        Arrays.sort(tiles,(a,b)->Integer.compare(a[0],b[0]));
        
        for(int i=0;i<tiles.length;i++)
        {
            int num = tiles[i][0] + carpetLen - 1;
            if(i>j)
                j = i;
            while(j<tiles.length)
            {
                if(tiles[j][0]>num)
                    break;
                else if(tiles[j][1]<num)
                    sum += (tiles[j][1]-tiles[j][0]+1);
                else if(tiles[j][1]>=num)
                {
                    sum += (num-tiles[j][0]+1);
                    break;
                }
                j++;
            }

            max = Math.max(sum,max);
            if(tiles[i][1]<=num)
                sum -= (tiles[i][1]-tiles[i][0]+1);
            
            if(j<tiles.length && tiles[j][0]<=num && j!=i)
                sum -= (num-tiles[j][0]+1);
        }
        
        return max;
    }
}
```

#### Screenshots

*pass all test case*
![image](https://user-images.githubusercontent.com/53531440/168443050-7ef685d4-cfb2-4650-bcd8-4aae6ed3b2bb.png)
 
*but gives wrong answer for above mentioned test case*
![image](https://user-images.githubusercontent.com/53531440/168443130-23df776f-b865-4dfb-9608-d1a010505f45.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
