### ISSUE TITLE
78. Subsets possibly false statement in the solution section

### ISSUE THREAD

**Issue by Zeks** [LeetCode-Feedback/LeetCode-Feedback#7306]
You make a claim of:

`Besides, this method has the best time complexity, and as a bonus, it generates lexicographically sorted output for the sorted inputs.`

in reference to bitmasking solution. This seems incorrect as it wastes time testing bitmask for a lot of 0s per cycle. My tests confirm that it is massively slower than cascading. Unless I am wrong somewhere this statement seems to be untrue.

My test case so that you can see for yourself: https://pastebin.com/Y9T6D6ds

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
