### ISSUE TITLE
Missing Test Case - 2271. Maximum White Tiles Covered by a Carpet

### ISSUE THREAD

**Issue by RosaliaSL** [LeetCode-Feedback/LeetCode-Feedback#7307]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code that I submitted get's accepted. However, for the a test case that I created, running the code for that testcase gives a memory limit exceeded error.

#### Code you used for Submit/Run operation

```
// Maximum White Tiles Covered by a Carpet
class Solution {
    public int maximumWhiteTiles(int[][] tiles, int carpetLen) {
        Arrays.sort(tiles, (a, b) -> {
            return a[0] - b[0];
        });
        
        int n = tiles.length;
        int start = tiles[0][0];
        int end = tiles[n - 1][1];
        
        int total = 0;
        for (int[] tile : tiles) {
            int s = tile[0] - start;
            int e = tile[1] - start;
            total += e - s + 1;
        }
        if (carpetLen >= end - start + 1) {
            return total;
        }
        
        int[] arr = new int[end - start + 1];
        for (int[] tile : tiles) {
            int s = tile[0] - start;
            int e = tile[1] - start;
            Arrays.fill(arr, s, e + 1, 1);
        }
        
        
        int count = 0;
        for (int i = 0; i < carpetLen; i++) {
            count += arr[i];
        }
        
        int ans = count;
        for (int i = 0; i < arr.length - carpetLen; i++) {
            count += arr[i + carpetLen];
            count -= arr[i];
            ans = Math.max(count, ans);
        }
        
        return ans;
    }
}

```

#### Testcase
Input: tiles = [[1,1000000000]], carpetLen = 10000
Output: Memory Limit Exceeded

#### Expected behavior

The code should not get accepted on submitting.

#### Screenshots

Testcase:
<img width="1440" alt="Screenshot 2022-05-15 at 2 33 58 AM" src="https://user-images.githubusercontent.com/62058426/168448090-2d24978c-48d9-4594-ac87-1c7fabdc1fd0.png">
Gives Memory Limit Exceeded on Running:
<img width="1440" alt="Screenshot 2022-05-15 at 2 33 25 AM" src="https://user-images.githubusercontent.com/62058426/168448082-555cb758-68da-45fb-a6b1-6479e3929115.png">
Gets Accepted:
<img width="1440" alt="Screenshot 2022-05-15 at 2 33 58 AM" src="https://user-images.githubusercontent.com/62058426/168448131-21d44bb9-f841-4c41-9cf3-d86d14cb1b90.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
