### ISSUE TITLE
Mising test case 

### ISSUE THREAD

**Issue by SGBBB** [LeetCode-Feedback/LeetCode-Feedback#7308]
#### Your LeetCode username
  sagar_bora  

#### Category of the bug
- [ .] Missing Test Cases 

#### Description of the bug
 There was some missing test case 
[[10,15],[1,1]]
2

#### Code you used for Submit/Run operation

```
 int maximumWhiteTiles(vector<vector<int>>& t, int len) 
	{
	    int res = 0, j = 0, cover = 0;//cover is length of white tiles covered by carpet in current window
	    sort(t.begin(), t.end());
	    for (int i = 0; i < t.size();)//carpet starts from j and end at i
	    {
	        if (j == i || t[j][0] + len > t[i][1]) //carpet starting from j is exceeding this window(as this window is ending at i)
			{
	            cover += t[i][1] - t[i][0] + 1;//this window is being extended to cover this patch also
	            res = max(res, cover);
	            ++i;//let this window try to cover next patch by expanding its right end
	        }
	        else//carpet starting from jth patch is not able to cover this whole patch at i 
			{
	            res = max(res, cover + max(0, t[j][0] + len - t[i][0]));
	            					/* Partial length covered by 
	            					   carpet in this patch
	            					*/
	            cover -= (t[j][1] - t[j][0] + 1);//window will slide towards right hence remove the contribution of cover given by left most patch of current window. 
	            ++j;//slide the window towards its right
	        }
            cout<<cover << " "<< res<<endl;
	    }
	    // return min(res,len);
            return res;
    }
```

#### Language used for code
 C++

**Comment by stormsunshine** [comment]
The problem should be: https://leetcode.com/problems/maximum-white-tiles-covered-by-a-carpet

**Comment by SGBBB** [comment]
@stormsunshine  Yup got  it

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. Would you mind sending us your code accepted link?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. The code that you provided has [Compile Error] issue, if you can provide us your Accepted link, that will be great, if you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
