### ISSUE TITLE
Accepted Solutions shows solutions that actually get TLE

### ISSUE THREAD

**Issue by megaspazz** [LeetCode-Feedback/LeetCode-Feedback#7309]
#### Your LeetCode username

megaspazz

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X ] Missing Test Cases 

#### Description of the bug

Accepted Solutions shows a solution with fast runtime that should actually get TLE.

[screenshot](https://imgur.com/XnBQuUA)

I noticed it should fail, which it does when I submit the code (TLE).  So, I think it should be removed from the "Accepted Solutions Runtime Distribution" sample submissions when you click on the bars of the graph.

#### Code you used for Submit/Run operation

```
class CountIntervals {
    
    List<int []> list;
    int count;

    public CountIntervals() {
        list = new ArrayList<>();
        count = 0;
    }
    
    public void add(int left, int right) {
        List<int []> nextList = new ArrayList<>();
        
        int [] a;
        boolean added = false;
        int l = left;
        int r = right;
        
        for (int i = 0; i < list.size(); ++i){
            a = list.get(i);
            
            if (a[1] < left - 1)
                nextList.add(a);
            else if (a[0] > right + 1){
                if (!added){
                    nextList.add(new int [] { l , r });
                    added = true;
                }
                
                nextList.add(a);
            }else {
                l = Math.min(a[0], l);
                r = Math.max(r , a[1]);
            }
        }
        
        if (!added) nextList.add(new int [] { l , r });
        
        count = 0;
        list = nextList;
        for (int [] arr : list){
            count += arr[1] - arr[0] + 1;
        }
    }
    
    public int count() {
        return count;
    }
}

/**
 * Your CountIntervals object will be instantiated and called as such:
 * CountIntervals obj = new CountIntervals();
 * obj.add(left,right);
 * int param_2 = obj.count();
 */
```

#### Language used for code

Java

#### Expected behavior

Don't show solutions that fail.  My guess is that new test cases were added after this submission was made, and old submissions are not run against new test cases.

(I don't think it's feasible to re-run old submissions against new test cases, but at least for the ones on display, I think they should be validated first.)

#### Screenshots

[imgur](https://imgur.com/XnBQuUA)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name
The test case

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by megaspazz** [comment]
The problem is [2276. Count Integers in Intervals](https://leetcode.com/problems/count-integers-in-intervals/).

The test case is the last one (I'm guessing it's #72 of 72).  Presumably, it's a newly added test case to test large inputs.  It's too big that pasting it here will crash my browser.

**Comment by LC-Pam** [comment]
Can you send us the test case? Because we cannot find #72 of 72. Thank you!

**Comment by megaspazz** [comment]
[2276-large-test-case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8781502/2276-large-test-case.txt)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
