### ISSUE TITLE
276. Paint Fence – incorrect expected result for number of ways to color 0 fences

### ISSUE THREAD

**Issue by d33ts** [LeetCode-Feedback/LeetCode-Feedback#731]
#### Your LeetCode username
MetricQuant

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The judge expects the number of ways to color `n = 0` fences to be `0`. The expected outcome should be `k choose 0 = 1`.

#### Language used for code
C++

#### Expected behavior
When `n` is `0`, the judge should expect `1` as the number of outcomes.

**Comment by lc-pam** [comment]
Hi @d33ts ,
If n=0, there is no possible way you can paint the post so the expected outcome should be 0.
