### ISSUE TITLE
Typo in solution explanation- 1302. Deepest Leaves Sum

### ISSUE THREAD

**Issue by ecron11** [LeetCode-Feedback/LeetCode-Feedback#7310]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a typo in the solution explanation section from copying and pasting. The second approach describes using a BFS Approach with a queue. However the first line says "Here we implement standard iterative preorder traversal with the stack" which is exactly the same first line as the first solution that actually uses it. I believe it was copy and pasted and that line just wasn't changed as the steps below it are accurate.

#### Screenshots

The second solution with the inaccurate line:
<img width="735" alt="Screen Shot 2022-05-14 at 11 07 09 PM" src="https://user-images.githubusercontent.com/4454415/168459555-1e5fb236-2edb-4535-a365-da47636f732e.png">

The First solution that the line was likely copied and pasted from:
<img width="633" alt="Screen Shot 2022-05-14 at 11 07 47 PM" src="https://user-images.githubusercontent.com/4454415/168459577-12911fbd-c222-4074-85ad-900f0bf4a754.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Y We appreciate your support!

**Comment by ecron11** [comment]
No problem!
