### ISSUE TITLE
691. 贴纸拼词 控制台输出和提交结果不一致

### ISSUE THREAD

**Issue by SoBrilliantGUN** [LeetCode-Feedback/LeetCode-Feedback#7312]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名 SoBrilliantGUN

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
同一段代码，点击执行代码或者(编译后)直接在浏览器上跑都返回的6，但提交多次都返回5，导致代码不通过

**你使用的语言**
typescript

**你提交或者运行的代码**
```typescript
function minStickers(stickers: string[], target: string): number {
  const ss: number[][] = stickers.map(getChCnts);
  const res = dfs(ss, target);
  return res === Infinity ? -1 : res;
};

const memo: Map<string, number> = new Map();

function dfs(ss: number[][], remain: string): number {
  if (remain === '') return 0;// 注意设置出口条件
  if (memo.has(remain)) return memo.get(remain);
  const remainChCnts = getChCnts(remain);
  const firstChCode = remain.charCodeAt(0) - 97;
  let min = Infinity;
  for (const s of ss) {
    if (s[firstChCode] === 0) continue;// 剪枝
    let next = '';
    for (let i = 0; i < 26; i++) {
      const cnt = Math.max(0, remainChCnts[i] - s[i]);
      for (let j = 0; j < cnt; j++) {
        next += String.fromCharCode(i + 97);
      }
    }
    min = Math.min(min, dfs(ss, next) + 1);
  }
  memo.set(remain, min);
  return min
}

function getChCnts(str: string): number[] {
  const chCnts = new Array(26).fill(0);
  for (const ch of str) {
    chCnts[ch.charCodeAt(0) - 97]++;
  }
  return chCnts;
}
```

**期望行为**
同一段代码，同样的测试用例，点击执行代码和点击提交应该都通过

**屏幕截图**
![error](https://github.com/SoBrilliantGUN/kazeRepo/blob/master/wtf.png?raw=true)
**额外的上下文**
无

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
