### ISSUE TITLE
Missing Test Case - 2276. Count Integers in Intervals

### ISSUE THREAD

**Issue by cod-OR** [LeetCode-Feedback/LeetCode-Feedback#7315]
#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
A missing test case, which gives TLE on accepted solutions.
An example solution is given below, which should give TLE.

#### Code you used for Submit/Run operation

```
class CountIntervals {
public:
    set<pair<int, int> > s;
    int cnt;
    CountIntervals() {
        cnt=0;
    }
    
    bool intersec(pair<int,int> a, pair<int, int> b){
        return a.first<=b.second;
    }
    
    void add(int left, int right) {
        auto it = s.lower_bound({left,left});
        if(it != s.begin())
            it--;
        while(it != s.end() and intersec(*it, {left,right})){
            int l=(*it).first , r=(*it).second;
            
            if(left>right)
                break;
            
            if(l<=left){
                left = max(left, r+1);
            }
            else if(l>left){
                cnt += (l-left);
                s.insert({left,l-1});
                left=r+1;
            } 
            it++;
            
        }
        
        if(left<=right){
            cnt += (right-left+1);
            s.insert({left,right});
        }
    }
    
    int count() {
        return cnt;
    }
};



```

#### Language used for code
C++

#### Expected behavior
This solution should give TLE. The test case is attached below.
It contains 9999 "add" queries and 1 "count" query. 
[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8694741/input.txt)

**Comment by cod-OR** [comment]
The program used to generate this test file is attached below for reference.
[generator.cpp.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8694746/generator.cpp.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We decided not to add this test case for now because it is very large and to add it,  may consider adding it later. Thank you for your support.

**Comment by cod-OR** [comment]
Okay sure.
Please don't get me wrong, but large size, which is 2.3MB, doesn't feel like a reason for not adding it. I'm sure Leetcode have test cases with much larger size for some problems.
Please let me know if the test case is invalid or if you decide to add it or change the problem constraints.
