### ISSUE TITLE
Too large sizes - 1. Two Sum

### ISSUE THREAD

**Issue by vikke1234** [LeetCode-Feedback/LeetCode-Feedback#7316]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
10e9 cannot be represented using integers which is what `nums[i]`'s restrictions are, similar issues are with the other size constraints.

#### Language used for code
C (C++ seems to also have the same issue)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
