### ISSUE TITLE
javascript 脚本执行错误

### ISSUE THREAD

**Issue by NanhuaZhang** [LeetCode-Feedback/LeetCode-Feedback#7317]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Naylor Zhang

**描述**
在js脚本中使用全局变量和三元表达式。leetcode代码解析器错误

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```

let maxSum = 0;

/**
 * @param {TreeNode} root
 * @return {number}
 */
const maxPathSum = function(root) {
    dfs(root)
    return maxSum;
};

function dfs(root){
    if(!root){
        return;
    }

    let sum = 0;
    if(root.val >= 0){
        const leftValue = root.left ? root.left.val: 0;
        const rightValue = root.right ? root.right.val: 0;

        sum = root.val + ((leftValue>0)?leftValue:0) + (rightValue>0)?rightValue:0;
        if(sum > maxSum){
            maxSum = sum;
        }
    }

    dfs(root.left);
    dfs(root.right);
}
```

**期望行为**
这里设置全局变量maxSum，在控制台执行单个用例是ok的。但是提交执行时就会报错，改成function里面使用数组，问题就解决了。

涉及复杂的三元计算加法时，这种场景下总是返回0。（包括本地执行和提交执行）
sum = root.val + ((leftValue>0)?leftValue:0) + (rightValue>0)?rightValue:0;

将((leftValue>0)?leftValue:0)声明变量就正常执行了。

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：“…+ (rightValue>0)?rightValue:0;”   加法优先级 高于 三元表达式。
