### ISSUE TITLE
196. Delete Duplicate Emails

### ISSUE THREAD

**Issue by grsl** [LeetCode-Feedback/LeetCode-Feedback#732]
#### Your LeetCode username
GRSL

#### Category of the bug
Question

#### Description of the bug
Runtime error. The code works in MariaDB and there is only one table in the question.

#### Code you used for Submit/Run operation
delete from person where id = (select max(id) from person where email in (select email from person group by email having count(id) > 1));

#### Language used for code
SQL

#### Expected behavior
To delete the suplicate row(s) from the table Person.

#### Screenshots
![1](https://user-images.githubusercontent.com/827444/88648520-f91ccf80-d0be-11ea-9bf6-6bb2990231d6.png)

**Comment by lc-pam** [comment]
Hi @grsl ,
Thanks for reaching out to us. I've checked with the team there is no issue with the problem. I recommend you check out the [official solution](https://leetcode.com/problems/delete-duplicate-emails/solution/) or share your question in the [discuss tab](https://leetcode.com/problems/delete-duplicate-emails/discuss/?currentPage=1&orderBy=hot&query=).
