### ISSUE TITLE
TLE on last test case- 898. Bitwise ORs of Subarrays

### ISSUE THREAD

**Issue by Sparsh1212** [LeetCode-Feedback/LeetCode-Feedback#7320]
#### Your LeetCode username

rollo_1212

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Grader Issue

#### Description of the bug

The last test case is getting timed out when submitting. However, if we run that last test case separately, it passes fine.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int subarrayBitwiseORs(vector<int>& arr) {
        int n = arr.size();
        unordered_set<int> prev;
        unordered_set<int> global;
        unordered_set<int> curr;
        global.insert(arr[0]);
        prev.insert(arr[0]);
        
        for(int i=1; i<n; i++){
            curr.insert(arr[i]);
            global.insert(arr[i]);
            
            for(int prev_sub_array_or: prev){
                int new_or = prev_sub_array_or | arr[i];
                curr.insert(new_or);
                global.insert(new_or);
            }
            prev = curr;
            curr.clear();
        }
        
        return global.size();
    }
};


```

#### Language used for code

C++

#### Expected behavior

Solution should pass

#### Screenshots

<img width="1181" alt="Screenshot 2022-05-15 at 11 09 23 PM" src="https://user-images.githubusercontent.com/55937724/168486374-0f7fca8e-4964-4a40-9a05-f44d4917ee7c.png">
<img width="1106" alt="Screenshot 2022-05-15 at 11 10 02 PM" src="https://user-images.githubusercontent.com/55937724/168486401-1229466f-c7e6-4732-85e9-fd726abecce6.png">

**Comment by Sparsh1212** [comment]
@LC-Pam PTAL!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by Sparsh1212** [comment]
> Thank you for reaching out to us!
> 
> When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
> 
> Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

Hi!
I went over this blog but my code does not falls into any of the cases as mentioned in the blog. I think here the problem needs further investigation. PTAL

**Comment by LC-Pam** [comment]
https://leetcode.com/submissions/detail/701700026/
We submitted your code and it got Accepted, please clean your browser history and cookies, it should help.
