### ISSUE TITLE
Space Complexity for Solution #1 to Problem #1480: Running Sum of 1d Array

### ISSUE THREAD

**Issue by FriskySaga** [LeetCode-Feedback/LeetCode-Feedback#7321]
#### Your LeetCode username

FriskySaga

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The first solution is described to be O(1) space complexity, but this should be O(n) space complexity since a new array of equal length to the input array is being used to store the answer.

#### Code you used for Submit/Run operation

Not applicable.

#### Language used for code

Any language.

#### Expected behavior

The space complexity for the first solution should be O(n) since a new array of equal length to the input array is being used to store the answer.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for sharing your concern. You're correct in that O(n) space is used for the result array, however, as noted in the explanation for the space complexity, the space used specifically by the output (or input) generally does not count towards the space complexity.

**Comment by cswartzell** [comment]
This is contrary to the space complexity listed for nearly any other solution on Leetcode.

**Comment by FriskySaga** [comment]
@cswartzell Do you mean that other Leetcode-provided solutions factor in the output for space complexity calculations?
