### ISSUE TITLE
测试用例不足

### ISSUE THREAD

**Issue by alicgq** [LeetCode-Feedback/LeetCode-Feedback#7322]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
冷冷大神
cgq_dlut

**Bug 类型**
- [ √] 缺少测试用例

**描述**
Java版本中有通过100%的提交代码如下，但是这个逻辑不对，缺少测试用例

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution
{
    public boolean canBeEqual(int[] target, int[] arr)
    {
        int n = target.length;
        int sum1 = 0;
        int sum2 = 0;
        for (int i = 0; i < n; i++)
        {
            sum1 += target[i] * target[i];
            sum2 += arr[i] * arr[i];
        }
        return sum1 == sum2;
    }
}
```

**期望行为**
增加测试用例：
[4,4,1,1,1,1,1,1,1,1]
[2,2,2,2,2,2,2,2,2,2]

**屏幕截图**
<img width="856" alt="image" src="https://user-images.githubusercontent.com/34677804/168504616-9c0e939a-1120-421f-bafa-c583c14bc829.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/34677804/168504671-0d3201b9-f3b6-4c53-9266-b3f26c592276.png">

**额外的上下文**
无

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：cgq_dlut 给予积分奖励，请查收。
