### ISSUE TITLE
271. Encode and Decode Strings - Typo in solution

### ISSUE THREAD

**Issue by JustinKolnick** [LeetCode-Feedback/LeetCode-Feedback#7323]
#### Your LeetCode username

JustinKol

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the solution description, the pictured input for approach 2 has an incorrect character. In the encoding step, the image depicts an input that begins with a 'plus' style ascii character. In the encoded string and output array, the character is an 'a'. 

#### Code you used for Submit/Run operation

None needed.

#### Language used for code

None needed.

#### Expected behavior

I believe the first pre-encode character list contains a typo, as the plus style ascii character should be an 'a'.

#### Screenshots

![Screenshot_Encode_Decode](https://user-images.githubusercontent.com/22639256/168511885-1c520634-05ff-4122-9107-30c73a6332dd.png)

#### Additional context

This is not a bug with the code or testcases, but a typo in the solution description. If this doesn't belong here, please let me know where I should submit this feedback.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
