### ISSUE TITLE
Typo in solution for 1047

### ISSUE THREAD

**Issue by araslanov** [LeetCode-Feedback/LeetCode-Feedback#7324]
#### Your LeetCode username
wizeek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Solution says `The idea is to repeat step 2 till the string still changes after the replacements.`

#### Expected behavior
One of 2 options:
* `The idea is to repeat step 2 till the string stops changing after the replacements.`
* `The idea is to repeat step 2 while the string still changes after the replacements.`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
