### ISSUE TITLE
面试题04.06后继者，相同输入，“执行代码”和“提交”给出了不同的答案

### ISSUE THREAD

**Issue by wangyiedge** [LeetCode-Feedback/LeetCode-Feedback#7325]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
赛博两脚兽

**Bug 类型**
- [ ] 题目
- [x] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
针对测试用例：
[5,3,6,2,4,null,null,1] 
6
使用本地环境和“执行代码”按钮均可以得到正确结果null，但是提交答案后提示"解答错误"，并给出了错误结果2，见截图

**你使用的语言**
go

**你提交或者运行的代码**
``` go
/**
 * Definition for a binary tree node.
 * type TreeNode struct {
 *     Val int
 *     Left *TreeNode
 *     Right *TreeNode
 * }
 */

var flag = false
var ans *TreeNode
func dfs(root *TreeNode, p *TreeNode) {
	if root==nil {
		return
	}
	dfs(root.Left,p)
	if flag {
		ans = root
		flag = false
	}
	if root == p {
		flag = true
	}
	dfs(root.Right,p)
}

func inorderSuccessor(root *TreeNode, p *TreeNode) *TreeNode {
	dfs(root,p)
	return ans
}
```

**期望行为**

**屏幕截图**
![image](https://user-images.githubusercontent.com/25731814/168513433-8c5b117b-da1d-4e11-8b25-cb68742aac7f.png)

**额外的上下文**

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
