### ISSUE TITLE
缺少测试用例#面试题 04.01. 节点间通路

### ISSUE THREAD

**Issue by liuhaoo** [LeetCode-Feedback/LeetCode-Feedback#7326]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
[常盘台皮卡丘](https://leetcode.cn/u/chang-pan-tai-pi-qia-qiu/)
chang-pan-tai-pi-qia-qiu

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [√] 缺少测试用例

**描述**
[面试题 04.01. 节点间通路](https://leetcode.cn/problems/route-between-nodes-lcci/)一题中有如下双100%提交代码，该算法利用了测试数据不足的漏洞，因此需要补充测试用例。

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    bool findWhetherExistsPath(int n, vector<vector<int>>& graph, int start, int target) {
        if(start == target) return true;
        for(auto& p:graph)
            if(p[1] == target)
                return findWhetherExistsPath(n,graph,start,p[0]);
        return false;
    }
};
```

**期望行为**
需要添加测试用例如下：
3 [[0, 2],[1, 2]] 1 2
5 [[0, 2], [1, 3], [1, 4], [1, 3], [2, 3], [3, 4]] 0 4 

**屏幕截图**
<img width="285" alt="1652676220(1)" src="https://user-images.githubusercontent.com/60592746/168521261-31a7694f-787f-4d9c-a0b1-dfa3fb9624ff.png">
<img width="486" alt="1652676277(1)" src="https://user-images.githubusercontent.com/60592746/168521335-c5684f08-5b6f-4632-bcef-7cd62ac3b7e1.png">

**额外的上下文**
无

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：chang-pan-tai-pi-qia-qiu 给予积分奖励，请查收。
