### ISSUE TITLE
bug - 94. Binary Tree Inorder Traversal

### ISSUE THREAD

**Issue by rozhanroukhosh** [LeetCode-Feedback/LeetCode-Feedback#7327]
#### Your LeetCode username
rojanrookhosh

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
on Traverse a tree, "Binary Tree Inorder Traversal" the value of the first test case in cached in leet code server.

#### Code you used for Submit/Run operation

```
// Binary Tree Inorder Traversal
class Solution:
    values=[]
    def inorderTraversal(self, root: Optional[TreeNode]) -> List[int]:
        def letGo(root):
            if root:
                letGo(root.left)
                self.values.append(root.val)
                letGo(root.right)
            return self.values

        
        if root:
                letGo(root)
                return self.values
            
        else:
            return []
     
```

#### Language used for code
python3

#### Expected behavior
I expected to have values = [1] 
but I get [1,3,2,1]
same for []
I got  [1,2,3]
because the the value of the test case is cached

#### Screenshots

<img width="1035" alt="Screenshot 2022-05-16 at 07 50 43" src="https://user-images.githubusercontent.com/31434728/168527769-79cc5cfd-fe2b-44f8-a288-430e3bef132a.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, your code get the wrong answer, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The array values in the code should be cleared by the user as we run the test cases on the same instance of Solution. We appreciate your support!
