### ISSUE TITLE
Bug - 94. Binary Tree Inorder Traversal

### ISSUE THREAD

**Issue by SStrippel** [LeetCode-Feedback/LeetCode-Feedback#7328]
#### Your LeetCode username
Codieee

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Output of the first Submission Testcase is `[1, 3, 2]`, while the input is `[ ]`. My code only works with the input and doesn't add any values. 
 
#### Code you used for Submit/Run operation
```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def inorderTraversal(self, root: Optional[TreeNode], nodes: list[int] = []) -> List[int]:
        cache = [root]
        print(cache, nodes)
        while cache:
            node = cache.pop()
            print(node)
            if not node: continue
            self.inorderTraversal(node.left, nodes)
            nodes.append(node.val)
            self.inorderTraversal(node.right, nodes)
        
        return nodes
```

#### Language used for code
Python3

#### Expected behavior
i Expect the output for the first Submission Testcase to be `[ ]`

#### Screenshots
Expected: 

![grafik](https://user-images.githubusercontent.com/66714289/168528867-99c50e75-4808-4e8c-95e2-b32d323bc3a4.png)

Result:

![grafik](https://user-images.githubusercontent.com/66714289/168527681-51fd73a3-1e21-4ccf-9e75-5168e8b28a84.png)

#### Additional context
None

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
