### ISSUE TITLE
提交均显示内部错误

### ISSUE THREAD

**Issue by yc12138** [LeetCode-Feedback/LeetCode-Feedback#733]
** Bug 类型**
题解

描述
每道题都提交都返回“内部出错”的error

你使用的语言
Python/C++

你提交或者运行的代码
不管新写的代码，还是之前已经提交通过的代码，提交都显示“内部错误”
```
例如1512.好数对的数组
class Solution:
    def numIdenticalPairs(self, nums: List[int]) -> int:
        m = collections.Counter(nums)
        return sum(v * (v - 1) // 2 for k, v in m.items())
```

**期望行为**
修复

**屏幕截图**
![QQ截图20200729104044](https://user-images.githubusercontent.com/33616769/88750647-9132bb80-d188-11ea-88bb-985abd24efcf.png)

**额外的上下文**
添加额外的上下文信息

**Comment by LiangJunrong** [comment]
+1。刚才刷新了下，好像 OK 了，小伙伴可以看看

**Comment by yc12138** [comment]
> +1。刚才刷新了下，好像 OK 了，小伙伴可以看看

嗯，ok了，谢谢
