### ISSUE TITLE
Missing Test Case - 912. Sort an Array

### ISSUE THREAD

**Issue by ParveendThakur** [LeetCode-Feedback/LeetCode-Feedback#7331]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by ParveendThakur** [comment]
TLE

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?
