### ISSUE TITLE
Missing Test Case - 118. Pascal's Triangle

### ISSUE THREAD

**Issue by saran0910** [LeetCode-Feedback/LeetCode-Feedback#7332]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by saran0910** [comment]
more testcases

**Comment by LC-Pam** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?
