### ISSUE TITLE
683. K Empty Slots: TestCase error

### ISSUE THREAD

**Issue by rkuprov** [LeetCode-Feedback/LeetCode-Feedback#7335]
Hi, 

Test case 
`[6,5,8,9,7,1,10,2,3,4]
2
`
incorreclty produces "8" as the result. It should be 7. Substitutin the fist 7 days with "O" you can see that this is the first day on which there are two On lightbubls that are separated by the two OFF bulbs (8, 9)
`[O,O,8,9,O,O,10,O,O,O]
2
`
here's my code:

`func kEmptySlots(bulbs []int, k int) int {
    // create a hash map of [day]index
    // arrange indices in order and do subtraction
    dm := make(map[int]int)
    for i, b := range bulbs{
        dm[b] = i
    }

    var indc []int
    for i := 1; i<= len(bulbs); i++{
        indc = append(indc, dm[i])
        sort.Ints(indc)
        for j , ind := range indc{
            if (j+1) < len(indc) && indc[j+1] - (ind+1) == k{
                return len(indc)
            }
        }
}
    return -1
}`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
OR
The code Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by rkuprov** [comment]
Language: Go. 
Code: 

func kEmptySlots(bulbs []int, k int) int {
    // create a hash map of [day]index
    // arrange indices in order and do subtraction
    dm := make(map[int]int)
    for i, b := range bulbs{
        dm[b] = i
    }

    var indc []int
    for i := 1; i<= len(bulbs); i++{
        indc = append(indc, dm[i])
        sort.Ints(indc)
        for j , ind := range indc{
            if (j+1) < len(indc) && indc[j+1] - (ind+1) == k{
                return len(indc)
            }
        }
}
    return -1
}

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
