### ISSUE TITLE
Missing Test Case - 48. Rotate Image

### ISSUE THREAD

**Issue by oooook0** [LeetCode-Feedback/LeetCode-Feedback#7336]
#### Category of the bug
- [ ] Question
- [ 1 ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I printed my output and returned the output, the program printed the correct output yet the output indicates my output was wrong 

#### Code you used for Submit/Run operation

```
// Rotate Image
class Solution:
    def rotate(self, matrix: List[List[int]]) -> None:
        """
        Do not return anything, modify matrix in-place instead.
        """
        out = []
        leng = len(matrix)
        for i in range(leng):
            out.append([])
            for j in range(leng):
                out[i].append(matrix[leng - j -1][I])
        print(output)
        return out
```

#### Language used for code

Python

#### Expected behavior

the output is different from the printed output

#### Screenshots

![Screen Shot 2022-05-16 at 8 51 03 PM](https://user-images.githubusercontent.com/25553315/168705245-4e8a61dc-c468-4b5b-ad09-d36bbb277bbd.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
