### ISSUE TITLE
Missing Test Case - 1379. Find a Corresponding Node of a Binary Tree in a Clone of That Tree

### ISSUE THREAD

**Issue by dchular** [LeetCode-Feedback/LeetCode-Feedback#7337]
#### Your LeetCode username

https://leetcode.com/dchular/
dchular

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

I didnt use parameter of TreeNode* original but I got Accepted.
Its because, we dont have a testcase of same val node.  ex: Input: tree = [3,4,3,null,null,6,19], target = 3
There are no condition for node value. So it can be same val of node testcase but there arent.

#### Code you used for Submit/Run operation

```
// 1379. Find a Corresponding Node of a Binary Tree in a Clone of That Tree
class Solution {
public:
    TreeNode* dfs(TreeNode* cloned, int target){
        if(cloned == NULL) return NULL;
        if(cloned->val == target) return cloned;
        TreeNode *left = dfs(cloned ->left, target);
        TreeNode *right= dfs(cloned ->right, target);
        return left != NULL ? left:right;
    }
    TreeNode* getTargetCopy(TreeNode* original, TreeNode* cloned, TreeNode* target) {
        return dfs(cloned,target->val);
    }
};
```
https://leetcode.com/submissions/detail/701063414/

#### Language used for code

c++

#### Expected behavior

This code should got wrong answer. Because it can be node with same val.

The correct code is ↓,
https://leetcode.com/submissions/detail/701047948/
we should check not only val but also whole object of TreeNode* target.
(original == target)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by dchular** [comment]
sorry there are 
constrains 
・The values of the nodes of the tree are unique.

and also 
Follow up: Could you solve the problem if repeated values on the tree are allowed?

so testcases are no problem
