### ISSUE TITLE
1379: Problem is too trivial for a medium difficulty question

### ISSUE THREAD

**Issue by JBlakd** [LeetCode-Feedback/LeetCode-Feedback#7338]
#### Your LeetCode username
ivanhu2246

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question falls under the constraint that every node value in the tree is unique. This means you could directly perform a search in the cloned tree for that value.

I quite reasonably believe that this question, which only requires the user to perform a straightforward DFS, is too trivial to be a leetcode medium question.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    TreeNode* getTargetCopy(TreeNode* original, TreeNode* cloned, TreeNode* target) {
        bool found;
        TreeNode* found_node = nullptr;
        dfs(cloned, target->val, found_node);
        return found_node;
    }

private:
    void dfs(TreeNode* cur_node, int& target_val, TreeNode*& found_node) {
        if (cur_node == nullptr || found_node != nullptr) {
            return;
        }
        
        if (cur_node->val == target_val) {
            found_node = cur_node;
            return;
        }
        
        dfs(cur_node->left, target_val, found_node);
        dfs(cur_node->right, target_val, found_node);
    }
};
```

#### Language used for code

C++

#### Expected behavior

If the value uniqueness constraint didn't exist, then I think the problem would be justified to fall under the medium diffculty. In that case, we would have to somehow differentiate the target node among other nodes with the same value.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
