### ISSUE TITLE
TLE no matter what solution - 784. Letter Case Permutation

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#734]
**NOTE: Number of hours spent solving this Problem - 10 hours**

#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language

#### Description of the bug

https://leetcode.com/problems/letter-case-permutation/
784. Letter Case Permutation

1. Note that this is an Easy question
2. See code below & come back to read below point 3
3. S can be 12 length
It can contains all letters as an edge case
Assuming "abcdefghijkl" is test case input, below code fails for just looping all chars in a `Backtracking` way

This runtime is too strict of EASY question

Solutions tried:
1. Array based
2. Bit manipulation
3. Below basic template code of 12 * 12 * 12 * ... 12 times fails too

All above failed with TLE (time limit exceeded)

Request:
**1. Is the runtime for JavaScript correct?
2. Is this really Easy? Make this Hard
3. Is this really Backtracking + Bit manipulation?
4. Are the constraints correct?**

#### Code you used for Submit/Run operation

```
/**
 * @param {string} S
 * @return {string[]}
 */
var letterCasePermutation = function (S) {
    let n = S.length;

    for (let i1 = 0; i1 < n; i1++) {
        for (let i2 = 0; i2 < n; i2++) {
            for (let i3 = 0; i3 < n; i3++) {
                for (let i4 = 0; i4 < n; i4++) {
                    for (let i5 = 0; i5 < n; i5++) {
                        for (let i6 = 0; i6 < n; i6++) {
                            for (let i7 = 0; i7 < n; i7++) {
                                for (let i8 = 0; i8 < n; i8++) {
                                    for (let i9 = 0; i9 < n; i9++) {
                                        for (let i10 = 0; i10 < n; i10++) {
                                            for (let i11 = 0; i11 < n; i11++) {
                                                for (
                                                    let i12 = 0;
                                                    i12 < n;
                                                    i12++
                                                ) {}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    return [];
};

// Above gives TLE error (Time limit exceeded)

```

#### Language used for code
JavaScript

#### Expected behavior
Expected - Easy should not be this strict
To prove it difficult to solve with the topics mention (Backtracking & Bitmanip) I have given a sample code

Actual - Any solution gives TLE.
**NOTE: Number of hours spent solving this Problem - 10 hours**

See description for more details.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy ,
Thanks for reaching out to us. Have you checked out [discuss post](https://leetcode.com/problems/letter-case-permutation/discuss/?currentPage=1&orderBy=hot&query=&tag=javascript) for other javascript solutions? I tested 3+ solutions and they all passed. I've relayed the issue to the team to investigate but please let me know if you decide to withdraw the request after you check out other solutions.

**Comment by manoharreddyporeddy** [comment]
@lc-pam 

Obviously, other solutions will Pass.

- Checking the discuss post is the issue here. People who look into discuss posts, so they will find answer and they change and submit it.
- What about people who does Not look into the posts? They are stuck

---

My requests are below:

Request:
1. Is the runtime for JavaScript correct?
2. Is this really Easy? Make this Hard
3. Is this really Backtracking + Bit manipulation?
4. Are the constraints correct?

**Comment by manoharreddyporeddy** [comment]
@lc-pam 
Also I did solve 2 more problems on Backtracking, see https://leetcode.com/pgmreddy/

In general
if we use more concepts
(here, Backtracking, Bit manipulation)
then it should not be considered Easy problem.

**Comment by manoharreddyporeddy** [comment]
@lc-pam 

Also because, a brute force must be Accepted for this Easy question.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy ,
Below are the answers regarding the request you raise:
1. Yes, it's correct.
2. We've updated the problem to medium. Your LeetCode account has received 20 LeetCoins as the reward for this feedback.
3. Yes.
4. Yes.

**Comment by manoharreddyporeddy** [comment]
Thank you for changing problem Easy to Medium.
