### ISSUE TITLE
《1264. 页面推荐》官方题解表述笔误

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#7340]
**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [ ] 题目
- [ √] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[官方题解](https://leetcode.cn/problems/page-recommendations/solution/ye-mian-tui-jian-by-leetcode-solution/)
第 10 行左右的表述：
> 使用 UNION ALL 或者 UNION 得到所有的朋友 （UNION ALL 和 UNION 的区别在于**前者**会去掉重复的行，**后者**不会，这里使用前者更高效）。

**期望行为**
原文笔误，**前者**和**后者**写反了，应更正为：…**后者**会去掉重复的行，**前者**不会…
对应的逻辑是：UNION（后者） 会去掉重复的行，UNION ALL（前者） 不会，这里使用 UNION ALL（前者）更高效
> 使用 UNION ALL 或者 UNION 得到所有的朋友 （UNION ALL 和 UNION 的区别在于**后者**会去掉重复的行，**前者**不会，这里使用前者更高效）。

**屏幕截图**
![image](https://user-images.githubusercontent.com/4961543/168733341-79346a0d-954f-4664-b910-e9bd63b9dd27.png)

**Comment by zuizaiqinshi** [comment]
您好，您的建议官方团队已采纳并已进行修改，感谢您的反馈～

**Comment by mantoufan** [comment]
感谢！
