### ISSUE TITLE
Improper Constraints - 1032. Stream of Characters

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7341]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The constraints of [1032. Stream of Characters](https://leetcode.com/problems/stream-of-characters) are improper and will cause the expected solution to get failed on some specific test cases. 

The expected solution should be using trie so that each `query` operation has time complexity O(max(word.length)) (this means the maximum length of any word in the given array `words`). However, such a trie solution will get failed for this test case: [1032.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8705304/1032.txt)

I think the values of the constraints are too large for a trie solution and the constraints should be reduced. For example, the maximum length of each word should be reduced from 2000 to 200, which should be more reasonable.

The cosntraints issue of 1032 was already mentioned in [#6138](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/6138). In that issue, the reply was that the test case is too large to be added. If this is the case, why not reduce the constraints? I believe reducing constraints should be a better way.

#### Code you used for Submit/Run operation
```Java
class StreamChecker {
    TrieNode root;
    int maxLength;
    StringBuffer queryStr;

    public StreamChecker(String[] words) {
        root = new TrieNode();
        maxLength = 0;
        for (String word : words) {
            maxLength = Math.max(maxLength, word.length());
            insert(word);
        }
        queryStr = new StringBuffer();
    }

    public boolean query(char letter) {
        queryStr.append(letter);
        if (queryStr.length() > maxLength) {
            queryStr.deleteCharAt(0);
        }
        return query(queryStr.toString());
    }

    private void insert(String word) {
        TrieNode node = root;
        int length = word.length();
        for (int i = length - 1; i >= 0; i--) {
            char letter = word.charAt(i);
            int index = letter - 'a';
            if (node.prev[index] == null) {
                node.prev[index] = new TrieNode();
            }
            node = node.prev[index];
        }
        node.wordStart = true;
    }

    private boolean query(String str) {
        TrieNode node = root;
        int length = str.length();
        for (int i = length - 1; i >= 0; i--) {
            char letter = str.charAt(i);
            int index = letter - 'a';
            if (node.prev[index] == null) {
                return false;
            } else {
                node = node.prev[index];
                if (node.wordStart) {
                    return true;
                }
            }
        }
        return node.wordStart;
    }
}

class TrieNode {
    boolean wordStart;
    TrieNode[] prev;

    public TrieNode() {
        wordStart = false;
        prev = new TrieNode[26];
    }
}
```

#### Language used for code
Java

#### Expected behavior
Change the constraints as mentioned above.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. (Updated the constraints. words[i].length from 2000 to 200
Removed a test case not satisfying the limits.
Checked some previous TLE solutions, they are still TLE.)
Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
