### ISSUE TITLE
Language - 1379. Find a Corresponding Node of a Binary Tree in a Clone of That Tree

### ISSUE THREAD

**Issue by VladimirMiller** [LeetCode-Feedback/LeetCode-Feedback#7342]
#### Your LeetCode username

VladimirMiller

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

No Swift language support.

#### Expected behavior

There should be swift template and opportunity to submit swift code

#### Screenshots

<img width="1440" alt="leetcode" src="https://user-images.githubusercontent.com/24372954/168777788-61340d6a-84c9-430a-ad69-b0f20561f451.png">

#### Additional context

<details>
  <summary>Potential template</summary>
    
  ```Swift
 /**
 * class TreeNode {
 *    var val: Int
 *    var left: TreeNode?
 *    var right: TreeNode?
 *    init(_ val: Int) { self.val = val }
 * }
 */

class Solution {
    func getTargetCopy(_ original: TreeNode, _ cloned: TreeNode, _ target: TreeNode) -> TreeNode {
        
    }
}
  ```
  
</details>

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've filed this language request to our team for consideration.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
