### ISSUE TITLE
Mistakes in solution - 896. Monotonic Array

### ISSUE THREAD

**Issue by AlexTengT** [LeetCode-Feedback/LeetCode-Feedback#7343]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There might be a mistake in the official solution, approach 1.

Here is a copy of that solution
```
class Solution(object):
    def isMonotonic(self, A):
        return (all(A[i] <= A[i+1] for i in xrange(len(A) - 1)) or
                all(A[i] >= A[i+1] for i in xrange(len(A) - 1)))
```

The solution says the time complexity is O(N) where n is the len(A).

However, the function `all()` is an O(N) function. You can find the persuade of `all()` on [python official documentation](https://docs.python.org/3/library/functions.html#all).
If the time complexity of `all()` is O(N). The time complexity of the given solution should be O(N^2).

<img width="831" alt="image" src="https://user-images.githubusercontent.com/79433869/168809544-6bacd2fc-d9a1-4e53-bb38-3b41123d4083.png">
<img width="682" alt="image" src="https://user-images.githubusercontent.com/79433869/168809874-cb887e3f-5ca9-4630-9dad-a5d28921c304.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
All checks the condition for each item in the iterable that it is iterating over, in this case, that iterable is xrange(len(A) - 1). So the first all will take O(N) time and if that returns false the second all will be called and also require O(N) time. O(N) + O(N) is O(N).

**Comment by AlexTengT** [comment]
```
class Solution(object):
    def isMonotonic(self, A):
        return (all(A[i] <= A[i+1] for i in xrange(len(A) - 1)) or
                all(A[i] >= A[i+1] for i in xrange(len(A) - 1)))
```

The for loop `A[i] <= A[i+1] for i in xrange(len(A) - 1)` taks O(N). Outside the for loop, there is another loop `all()`. therefore `(all(A[i] <= A[i+1] for i in xrange(len(A) - 1))` takes O(N^2). the total function takes O(N^2) + O(N^2), that is O(N^2)
