### ISSUE TITLE
Missing Test Case - 176. Second Highest Salary

### ISSUE THREAD

**Issue by Aregbesolazeez** [LeetCode-Feedback/LeetCode-Feedback#7345]
#### Your LeetCode username

Aregbesolazeez

#### Category of the bug
- [ ] Solution

#### Description of the bug

On submission it returns "Wrong Answer", however answer is correct and have been further tested using the "Run Code."

#### Code you used for Submit/Run operation

```
/* Write your T-SQL query statement below */
SELECT (SELECT salary FROM Employee
        ORDER BY salary DESC
        OFFSET 1 ROW
        FETCH NEXT 1 ROW ONLY
       ) AS SecondHighestSalary;
```

#### Language used for code

MS SQL Server

#### Expected behavior

Return "{"headers":["SecondHighestSalary"],"values":[[null]]}" for a test case {"headers":{"Employee":["id","salary"]},"rows":{"Employee":[[1,100],[2,200]]}} on submittion, whereas the result should be {"headers": ["SecondHighestSalary"], "values": [[100]]}

#### Screenshots

![leetcode](https://user-images.githubusercontent.com/89527279/168856908-197865da-56f7-479e-bf54-bea0140621aa.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly.
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
