### ISSUE TITLE
LeetCode 题目搜索问题

### ISSUE THREAD

**Issue by LiangJunrong** [LeetCode-Feedback/LeetCode-Feedback#735]
** Bug 类型**
- [x] 搜索 Bug

**描述**
在【算法】题库或者【程序员面试金典】或者【剑指 Offer】中，搜索出来的内容有点奇怪。

例如：

* 在【剑指 offer】中，想查找关于 “队列” 的题目进行训练。

然后用中文 “队列” 搜索出来的结果如下：

![image](https://user-images.githubusercontent.com/22924993/88761385-a0723300-d1a1-11ea-8ad0-6521e6b09e8e.png)

接着用标签 “Queue” 搜索出来的结果如下：

![image](https://user-images.githubusercontent.com/22924993/88761418-ac5df500-d1a1-11ea-982a-5026e4c2511a.png)

虽然事实上用中文 “队列” 搜索出来的，上面画框的两道题，贴的是 “栈” 的标签。

但是，例如题目 《剑指 Offer 59 - II. 队列的最大值》 中的实现，应该是 “栈” 和 “队列” 的结合，按理说这里应该也存在 “队列” 的标签（实际并没有）。

综上，有时候想做对应模块的训练，需要多次搜索，才能找到更好的结果。

**期望行为**
我们搜索 “队列” 或者其他关键字的时候，可以将相关标签以及题目的内容给罗列出来吗？如果另有原因，想了解下为什么这样设计，谢谢~

**Comment by feiceh** [comment]
感谢反馈，题目页面的搜索🔍栏是按照题目名称、内容或者编号来搜索，与题目标签没有太大关系，如要使用标签进行筛选的话请使用「标签」栏。实际上「用两个栈实现队列」这道题的具体实现是使用的『栈』，所以被打上『栈」标签，实现方法里面没有用到队列，所以没有打上队列的标签，已转给相关团队后期会持续优化，给您带来的不便敬请谅解。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，后续有其他问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。
