### ISSUE TITLE
Bug with a test case

### ISSUE THREAD

**Issue by Farcasut** [LeetCode-Feedback/LeetCode-Feedback#7350]
---
name: Bug report (English)
about: Create a bug report to help us improve our content.
title: 'Bug with problem https://leetcode.com/problems/add-two-numbers/ '
labels: 'test case bug'
assignees: ''

---

#### Your LeetCode username

farcasut

#### Category of the bug
- [x] Solution
- [ ] Missing Test Cases 

#### Description of the bug

I think there is a bug with test case 943 form this problem https://leetcode.com/problems/add-two-numbers/

#### Code you used for Submit/Run operation

```
 class Solution {
 public:

     ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
         ListNode* temp = l1;
         int vec[101] = {};
         int vec2[101] = {};
         int i, j;
         i = j = 100;
         while (temp != nullptr)
         {
             vec[i--] = temp->val;
             temp = temp->next;
         }
         temp = l2;
         int size = i < j ? i : j;
         while (temp != nullptr)
         {
             vec2[j--] = temp->val;
             temp = temp->next;
         }
         for (int k = 100; k >= 0; k--)
         {
             vec[k] += vec2[k];
             if (vec[k] >= 10)
             {
                 vec[k - 1] += vec[k] / 10;
                 vec[k] = vec[k] % 10;
             }

         }
         ListNode* result = new ListNode;
         temp = result;
         int ls = 100;
         while (ls != size)
         {
             temp->val = vec[ls--];
             if ((ls) == size)
                 break;
             temp->next = new ListNode;
             temp = temp->next;
         }


         return result;
     }
 };
```

#### Language used for code

    c++

#### Expected behavior

From my tests the code should run on the [9,9,9,9,9,9,9] [9,9,9,9] case.

#### Screenshots

https://snipboard.io/RSnIJH.jpg

**Comment by stormsunshine** [comment]
This test case is correct. 9999999 + 9999 = 10009998, which is the same as the expected result.

Your code is incorrect for this test case, so the solution is not accepted.
