### ISSUE TITLE
The problem [900. RLE Iterator] missing Testcases so that the judge is incorrect

### ISSUE THREAD

**Issue by 0xLucifer** [LeetCode-Feedback/LeetCode-Feedback#7351]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

#### Description of the bug

The problem [900. RLE Iterator] missing Testcases so that the judge is incorrect

#### Code you used for Submit/Run operation

```
// Two Sum
# -*- coding: utf-8 -*-
class RLEIterator(object):

    def __init__(self, encoding):
        self.counts=[]
        self.nums=[]
        for index in range(len(encoding)/2):
            if encoding[index*2] == 0:
                continue
            self.counts.append(encoding[index*2])
            self.nums.append(encoding[index*2+1])

    def next(self, n):
        if n>sum(self.counts):
            self.counts=[]
            self.nums=[]
            return -1
        for i in range(len(self.counts)):
            if n <= sum(self.counts[:i+1]):
                n-=sum(self.counts[:i])
                self.counts[i]-=n
                result=self.nums[i]
                if self.counts[i]==0:
#                    self.counts=self.counts[max(i-1,0):]       # wrong answer but can pass all testcase
#                    self.nums=self.nums[max(i-1,0):]           # wrong answer but can pass all testcase
                    self.counts=self.counts[i+1:]               # right answer here.
                    self.nums=self.nums[i+1:]                   # right answer here.

#                        you can tell the difference (between the right answer and wrong answer) with the following testcase
#                           encoding     = [7,1,2,5,2,8]
#                            rLEIterator  = RLEIterator(encoding)
#                            print rLEIterator.next(9)
#                            print rLEIterator.next(7)
#                            print rLEIterator.next(1)
                else:
                    self.counts=self.counts[i:]
                    self.nums=self.nums[i:]
                break
        return result
```

#### Expected behavior

in my solution,the array self.counts and self.nums are used to describe the encoding input collaboratelly
and you can see the commnets in my solution, and there are two solutions actually which are [right solution] and [wrong solution]
after run the [wrong solution] the self.counts and self.nums are wrong
you can debug the self.counts and self.nums variables to see it.

**Comment by stormsunshine** [comment]
The test case should be as follows. Is that correct?

```
["RLEIterator","next","next","next"]
[[[7,1,2,5,2,8]],[9],[7],[1]]
```

**Comment by 0xLucifer** [comment]
> 

Yes, your testcase is correct

**Comment by 0xLucifer** [comment]
Yes this testcase is correct.

> The test case should be as follows. Is that correct?
> 
> ```
> ["RLEIterator","next","next","next"]
> [[[7,1,2,5,2,8]],[9],[7],[1]]
> ```

**Comment by 0xLucifer** [comment]
> Would you mind sending us your submission link?

No problem bro.
the two submissions here(They are all accepted):
1. https://leetcode.com/submissions/detail/701764215/
2. https://leetcode.com/submissions/detail/701764138/

**Comment by LC-Pam** [comment]
Thank you so much. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
