### ISSUE TITLE
99 bug

### ISSUE THREAD

**Issue by euphonium1998** [LeetCode-Feedback/LeetCode-Feedback#736]
** Bug 类型**
- [1 ] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
![err](https://user-images.githubusercontent.com/54737731/88795591-dbd92580-d1d2-11ea-9f1e-9bd539974967.png)

调试结果和真正提交结果存在冲突

**你使用的语言**
GO

**你提交或者运行的代码**
```
var former, mistakeOne, mistakeTwo *TreeNode
func recoverTree(root *TreeNode)  {
	former = new(TreeNode)
	former.Val = math.MinInt32
	inOrderTraverse(root)
	mistakeOne.Val, mistakeTwo.Val = mistakeTwo.Val, mistakeOne.Val
}

func inOrderTraverse(root *TreeNode)  {
	if root == nil {
		return
	}
	inOrderTraverse(root.Left)
	if root.Val > former.Val {
		former = root
	} else {
		if mistakeOne == nil {
			mistakeOne = former
			mistakeTwo = root
		} else {
			mistakeTwo = root
		}
	}
	inOrderTraverse(root.Right)
}
```

**期望行为**
描述你期望的结果

见截图右下角

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。
