### ISSUE TITLE
Missing Test Cases - 560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7360]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [560. Subarray Sum Equals K](https://leetcode.com/problems/subarray-sum-equals-k), two test cases need to be added to make brute force solutions get TLE.

The test cases are as follows:

[560_0.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8723860/560.txt)
[560_1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8723852/560.txt)

#### Code you used for Submit/Run operation
```Java
class Solution {
    public int subarraySum(int[] nums, int k) {
        int count = 0;
        for (int start = 0; start < nums.length; ++start) {
            int sum = 0;
            for (int end = start; end >= 0; --end) {
                sum += nums[end];
                if (sum == k) {
                    count++;
                }
            }
        }
        return count;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Add the test cases above to make the solution get TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
