### ISSUE TITLE
Incomplete Description - 58. Length of Last Word

### ISSUE THREAD

**Issue by philen** [LeetCode-Feedback/LeetCode-Feedback#7361]
#### Your LeetCode username
philen

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description is incomplete, it only states that the string is "words separated by some number of spaces" when it is also possible for there to be spaces both before the first word and after the last word. In English, "separated by" does not imply leading or trailing spaces. 

The test cases do show a leading/trailing example.

#### Expected behavior
I suggest changing the sentence to "Given a string s consisting of letters and spaces, return the length of the last word in the string. ", as the next sentence clearly defines what a "word" is.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
