### ISSUE TITLE
【测试用例不足】916. 单词子集

### ISSUE THREAD

**Issue by xy-fs** [LeetCode-Feedback/LeetCode-Feedback#7362]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**xy_fs**

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
测试用例不足

**你使用的语言**
Python

**你提交或者运行的代码**
```python
class Solution:
    def wordSubsets(self, words1: List[str], words2: List[str]) -> List[str]:
        need = Counter()

        for s in words2:
            for ch, cnt in Counter(s).items():
                need[ch] = max(need[ch], cnt)
        
        return [s for s in words1 if Counter(s) > need]
```

**期望行为**
解答错误

**屏幕截图**
![916](https://user-images.githubusercontent.com/59466661/169281266-9fab908f-1828-46d3-bc46-083fe0078518.png)

**额外的上下文**
问题原因：单词 `s` 中的所有字母频次 **大于等于** `words2` 中所有单词的字母的最高频词即为答案，而测试用例缺少了 **等于** 这个边界。

上述代码最后一行改为 `return [s for s in words1 if Counter(s) >= need]` 即可通过额外的测试用例。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：xy_fs 给予积分奖励，请查收。
