### ISSUE TITLE
add javascript to learn data structures 

### ISSUE THREAD

**Issue by Bouab-Ahmed** [LeetCode-Feedback/LeetCode-Feedback#7366]
#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

i suggest you adding more languages to implement data structures 

#### Code you used for Submit/Run operation

```
```

#### Language used for code

Js

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the content team. We appreciate your support!
