### ISSUE TITLE
Missing Test Case - 208. Implement Trie (Prefix Tree)

### ISSUE THREAD

**Issue by xingxu21** [LeetCode-Feedback/LeetCode-Feedback#7367]
#### Your LeetCode username

nd4312

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

Users in python may be tempted to use the `in` operator when checking for prefix. The in operator checks for substring and not prefix that `string.startswith()` method should do.  In my case, I implemented as 
```
    def startsWith(self, prefix: str) -> bool:
    ....
            if prefix in curNode.val:
                return True
    ....
```
and passed 14 of 15 test case. The last test case had 1000+ inputs that made it difficult to debug. 
#### Code you used for Submit/Run operation

Input
```
["Trie","insert","startsWith"]
[[],["hotdog"],["dog"]]
```

#### Language used for code

Python

#### Expected behavior

Output `False` when checking if `dog` is in `hotdog`. Have this separate test case to clarify the bug from test case 15/15 which had thousands of inputs and outputs where the issue was one true/false case buried inside. 

#### Additional context

Many users (including me) have been implementing the Trie using binary trees. The question lacks context to explain or enforce the use of the k-ary tree for those who've never heard of such data structure. Additional language may benefit users so that they can appreciate the advantages of the prefix tree over hashmaps and binary trees.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Added a new test case to make debugging easier.  We appreciate your support!
