### ISSUE TITLE
Repeat Problem - Problem 724

### ISSUE THREAD

**Issue by ashishjayamohan** [LeetCode-Feedback/LeetCode-Feedback#7368]
#### Your LeetCode username
ashishjayamohan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem 724 is a repeat of the problem 1991. Both ask the same question (asking for the middle index), but they are both worded slightly differently.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def pivotIndex(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        left, right = 0, sum(nums) - nums[0]
        if (right == 0):
            return 0
        for i in range(len(nums) - 1):
            left += nums[i]
            right -= nums[i + 1]
            if (left == right):
                return i + 1
        return -1
```

#### Language used for code
Python

#### Expected behavior
Only one problem with one problem statement

#### Screenshots
N/A

#### Additional context
N/A

**Comment by ashishjayamohan** [comment]
Note - Problem 724 seems to be the more popular question and has more submissions than Problem 1991. It would be advisable to, if this course of action is chosen, delete Problem 1991 rather than Problem 724.

**Comment by stormsunshine** [comment]
There are already some repeated problems. For example, 316 and 1081, 476 and 1009, 530 and 783, 538 and 1038, 616 and 758, etc. It is unnecessary to remove repeated problems.

**Comment by ashishjayamohan** [comment]
Understood, thank you!
