### ISSUE TITLE
[incorrect topic tag] LeetCode-2265: Count Nodes Equal to Average of Subtree

### ISSUE THREAD

**Issue by y2k-shubham** [LeetCode-Feedback/LeetCode-Feedback#7369]
#### Your LeetCode username
y2k-shubham

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
[LeetCode-2265: Count Nodes Equal to Average of Subtree](https://leetcode.com/problems/count-nodes-equal-to-average-of-subtree/) has been tagged as [`Binary Search Tree`](https://leetcode.com/tag/binary-search-tree/) while it should be [`Binary Tree`](https://leetcode.com/tag/binary-tree/)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
