### ISSUE TITLE
BLOCKED - No Expected from Judge even when the input is within constraints -  39. Combination Sum

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#737]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Problem
39. Combination Sum
https://leetcode.com/problems/combination-sum/

1. Provide below test case:

[17,12,22,21,24,14,23,19,13,26,5,18,30,28,2,29,8,20,3,27,1,25,10,15,7,16,6,11,9,4]
100

2. Provide below mentioned code.

3. click 'Run Code'

4. Note that even though the input is within the constraints of 200 elements & target < 500, the Expected comes as blank by the judge.

Questions:
1. Are the constraints will work for all values?
2. How to create test cases for this behavior?
3. Shouldn't the judge give Expected OR Error always?

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} candidates
 * @param {number} t
 * @return {number[][]}
 */
var combinationSum = function (a, t) {
    return;
};
```

#### Language used for code
JavaScript

#### Expected behavior

Expected: Judge must give any output/ error when the input is within limits

Actual: Judge does Not give any output/ error  even when the input is within limits

See description above for more details.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy ,
Thanks for the time. The team is aware of the issue you mentioned but at the moment we are not stressing too many test cases or redesigning the constraints on old problems. So the behavior of the judger is expected and we are not updating the problem. We expect to give a better answer in the future. Thank you.

**Comment by manoharreddyporeddy** [comment]
Ok, I will expect so (better answer for future problems atleast) 👍
