### ISSUE TITLE
Problem 470 - wrong calculation of expected value in Solution section

### ISSUE THREAD

**Issue by tikerlade** [LeetCode-Feedback/LeetCode-Feedback#7370]
#### Your LeetCode username
tikerlade

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the section "Solution", part `Approach 1` for [problem №470](https://leetcode.com/problems/implement-rand10-using-rand7/solution/) it's written that:

> The [expected value](https://en.wikipedia.org/wiki/Expected_value) for the number of calls to rand7() can be computed as follows:

And mentioned answer is 2.45
However in the row where sum from 1 to infinity is introduced one part is missed it's factor `2k`. This expected value (sum) is actually diverges with `2k` introduced, that's why worst case time complexity is O(inf).

In screenshot I highlighted different parts of sum. All parts except yellow one are presented under sum symbol. The same problem happens in section `Approach 2`.

#### Screenshots

![Screenshot 2022-05-19 235707](https://user-images.githubusercontent.com/28840497/169403379-714c74a4-118e-4c1a-abd5-1b4cf164e128.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The process of the formula in the article is incorrect, but your conclusion is also incorrect. it is fixed to the corrected version in (https://github.com/leetcode/oj-solutions/pull/1071) We appreciate your support!
