### ISSUE TITLE
Missing Test Case - 1213. Intersection of Three Sorted Arrays

### ISSUE THREAD

**Issue by ratchahan-anbarasan** [LeetCode-Feedback/LeetCode-Feedback#7372]
#### Your LeetCode username
Leetcode Username : _drunkenmonkey

#### Category of the bug
Missing Test Cases 

#### Description of the bug
Few test cases are missing for the given question.

Test case:

[1,2,3,4,5]
[1,2,5,9]
[1,3,4,5,8]

The test case based on unequal array length is not available in the final submission check.

#### Code you used for Submit/Run operation
//1213. Intersection of Three Sorted Arrays
```
class Solution:
    def arraysIntersection(self, arr1: List[int], arr2: List[int], arr3: List[int]) -> List[int]:
        
        n = min(len(arr1), len(arr2), len(arr3))

        res = []
        i = 0
        
        while i < n:
            if arr1[i] in arr2 and arr1[i] in arr3:
                res.append(arr1[i])
            i += 1
                
        
        return res
```

#### Language used for code
Python3

#### Expected behavior
The written code failed for the above mentioned test case while the submission was successful with all 23 test cases passing.

#### Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/96559018/169417954-7e09517e-6629-4f82-9ee6-6d550f2fb0e6.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
