### ISSUE TITLE
有一个测试用例bug

### ISSUE THREAD

**Issue by zwy66666** [LeetCode-Feedback/LeetCode-Feedback#7374]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
zwy

**Bug 类型**
- [ ] 题目
- [√ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**

给你一个字符串 s 和一个 长度相同 的整数数组 indices 。

请你重新排列字符串 s ，其中第 i 个字符需要移动到 indices[i] 指示的位置。

返回重新排列后的字符串。

 

示例 1：

输入：s = "codeleet", indices = [4,5,6,7,0,2,1,3]
输出："leetcode"
解释：如图所示，"codeleet" 重新排列后变为 "leetcode" 。
示例 2：

输入：s = "abc", indices = [0,1,2]
输出："abc"
解释：重新排列后，每个字符都还留在原来的位置上。
 

提示：

s.length == indices.length == n
1 <= n <= 100
s 仅包含小写英文字母
0 <= indices[i] < n
indices 的所有的值都是 唯一 的

**你使用的语言**
JAVA++

**你提交或者运行的代码**
```
class Solution {
    //用例"codeleet", new int[]{4,5,6,7,0,2,1,3}
    //返回结果是 "leetcdoe" 才对啊
    //答案给的是 "leetcode"
    //o对应下标是1 答案给的是d
    public String restoreString(String s, int[] indices) {
        StringBuilder result = new StringBuilder();
        StringBuilder sb = new StringBuilder(s);
       for (int i = 0; i < indices.length; i++) {
            result.append(  sb.charAt(indices[i]));
            sb.replace(indices[i],indices[i]+1 , " ");
        }
        return result.toString();
    }
        
}
```

**期望行为**
修改测试用例的bug。
**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![企业微信截图_20220520103316](https://user-images.githubusercontent.com/96455554/169437196-b703c54e-f007-4595-86f4-cc64f72401e4.png)

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
请仔细看测试用例的解释，测试用例结果是正确的。
