### ISSUE TITLE
436.寻找右区间 题解方法二描述有问题

### ISSUE THREAD

**Issue by eleven26** [LeetCode-Feedback/LeetCode-Feedback#7375]
**你的 LeetCode 用户名**
rubys_

**Bug 类型**
- 题解

**描述**
题解描述中的 `endIntervals[i][1]` 应该是 `endIntervals[i][0]`，`endIntervals[i+1][1]` 应该是 `endIntervals[i+1][0]`

**屏幕截图**
![image](https://user-images.githubusercontent.com/10000532/169458514-3ea38b40-2dc0-44c1-b930-795c3183f3d6.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by zuizaiqinshi** [comment]
您好，您的建议官方团队已采纳并已进行修改，感谢您的反馈～
