### ISSUE TITLE
BLOCKED - Output limit exceeded when nothing is printed to stdout - 39. Combination Sum

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#738]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Problem

39. Combination Sum
https://leetcode.com/problems/combination-sum/

1. Provide below test case:
[17,12,22,21,24,14,23,19,13,26,5,18,30,28,2,29,8,20,3,27,1,25,10,15,7,16,6,11,9,4]
50

2. Give any valid solution in the code

Note that even though the input is within the constraints of 200 elements & target < 500, the Expected comes gives 'Output limit exceeded'

Note below:
1. Code does not print anything
2. Code only returns the value required by program (which happens to be long)

#### Code you used for Submit/Run operation

```
// NOTE - Paste any Accepted solution of JavaScript here
```

#### Language used for code
JavaScript

#### Expected behavior

Expected:
When the solution gives correct answer, Judge should print "Pass"
Even when the message of "Output limit exceeded" comes.
Otherwise devs won't know if it is correct solution or not.

NOTE: Issue is with Problem that has large output, when program does not print anything

Actual:

Program does not print anything, but Output limit exceeded comes out.
Unable to know if the solution is correct/ not.
Solution has return value that is too large.
I am BLOCKED yet again.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. Although this is a valid test case, the output of this test prints 3 millions integers which is not suitable for our system currently. We will consider fixing this in the future. We appreciate your support!

**Comment by manoharreddyporeddy** [comment]
> Note that even though the input is within the constraints of 200 elements & target < 500, the Expected comes gives 'Output limit exceeded'

- But you need fix the problem constraints isn't?
- Otherwise, how will a user solve without constraints?
