### ISSUE TITLE
Wrong answer for minimal grid on question 63 (Unique Paths II)

### ISSUE THREAD

**Issue by shooma** [LeetCode-Feedback/LeetCode-Feedback#7382]
#### Your LeetCode username
shooma

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### System wrongly expect answer for 1x1 grid is 1
But in that case robot already at the upper left and at the bottom right cell. So no paths are allowed for 1x1 grid and correct answer should be 0 (zero)

#### Code you used for Submit/Run operation

```golang
func uniquePathsWithObstacles(obstacleGrid [][]int) int {
    return 0
}
```

#### Language used for code
Go

#### Expected behavior
For input `[[0]]` (grid 1x1 without obstacles) correct qty of paths should be 0

#### Screenshots
![image](https://user-images.githubusercontent.com/1442668/169532379-935bce27-9b54-4376-bc5b-b3dcfd25dfef.png)

**Comment by stormsunshine** [comment]
There is one path, which is remaining at (0, 0). Is there any problem?

**Comment by LC-Pam** [comment]
Thank you for your time. Please check the reply from Stromsunshine.  We appreciate your support!
