### ISSUE TITLE
Missing Test Case - 2280. Minimum Lines to Represent a Line Chart

### ISSUE THREAD

**Issue by olgaboiar** [LeetCode-Feedback/LeetCode-Feedback#7390]
#### Your LeetCode username
olgaboiar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Solution is marked as accepted while it is failing an additional test case.

#### Code you used for Submit/Run operation

```
// Minimum Lines to Represent a Line Chart
var minimumLines = function(stockPrices) {
    if (stockPrices.length < 2) return 0;
    if (stockPrices.length === 2) return 1;
    stockPrices.sort((a,b) => {return a[0] - b[0]})
    let count = 1;
    let currendDiff = stockPrices[0][1] - stockPrices[1][1];
    for (let i = 1; i < stockPrices.length - 1; i++) {
        let tempDiff = (stockPrices[i][1] - stockPrices[i+1][1])/(stockPrices[i+1][0] - stockPrices[i][0])
        if (currendDiff != tempDiff) {
            count += 1;
            currendDiff = tempDiff;
        }
    }
    return count;
};
```

#### Language used for code
Javascript

#### Expected behavior
This solution should not be accepted. It fails for input `[[1,1],[3,2],[4,3],[5,4],[6,4]]`

#### Screenshots

<img width="1351" alt="Screen Shot 2022-05-21 at 9 54 47 PM" src="https://user-images.githubusercontent.com/13441945/169679371-e42927fa-18af-494e-af22-84b97f7414a0.png">

#### Additional context
The provided solution fails, because this line does not account for days difference
`let currendDiff = stockPrices[0][1] - stockPrices[1][1];`
The correct one would be:
`let currendDiff = stockPrices[0][1] - stockPrices[1][1]/(stockPrices[1][0] - stockPrices[0][0]);`

Adding a test case with input `[[1,1],[3,2],[4,3],[5,4],[6,4]]` should fix the bug

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
