### ISSUE TITLE
Leetcode #426 runs into Nullpointer exception

### ISSUE THREAD

**Issue by Irving09** [LeetCode-Feedback/LeetCode-Feedback#7393]
#### Your LeetCode username
irving09

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/convert-binary-search-tree-to-sorted-doubly-linked-list/

Runner runs into a null pointer exception when assigning an array element of type `Node`.
For example
```
Node[] buffer = new Node[2];
buffer[0] = new Node();
buffer[1] = new Node(); // <---- runs into a null pointer exception
```

#### Code you used for Submit/Run operation
```
class Solution {
  public Node treeToDoublyList(Node root) {
    Node[] buffer = new Node[2];
    buffer[0] = new Node();
    buffer[1] = new Node(); // <---- runs into a null pointer exception

    return root;
  }
}
```

#### Language used for code
Java

#### Expected behavior
Should not run into a null pointer exception.

#### Screenshots
![Screen Shot 2022-05-13 at 5 29 11 PM](https://user-images.githubusercontent.com/6834721/169683839-2b1925a3-36b7-4326-add5-791e0e939ea6.png)

#### Additional context
Can I get a leetcode shirt for this so I can show it off to my friends?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Irving09** [comment]
Thank you @LC-Pam !

This was the submission link: https://leetcode.com/submissions/detail/691432421/

Can I have leetcode shirt for this?

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us. If you contribute valid content issues through our GitHub channel, we will give 100 Leetcoins based on the feedback of the content team, but do not provide other prizes. You can submit valid content questions, and when you have accumulated 6000 Leetcoins, you can redeem T-shirt on our product redeem page. Thank you for your support!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
