### ISSUE TITLE
Inappropriate constraints - 647. Palindromic Substrings

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#7394]
#### Your LeetCode username

Leaderboard

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The constraint is too low and permit bruteforce O(n<sup>3</sup>) solutions to work.

#### Code you used for Submit/Run operation

```java
class Solution {
    public boolean isPalindromic(String s)
    {
        StringBuilder sb = new StringBuilder(s);
        sb = sb.reverse();
        if (sb.toString().equals(s))
            return true;
        return false;
    }
    public int countSubstrings(String s) {
        int ans = 0;
        for (int i = 0; i < s.length(); i++)
        {
            StringBuilder sb = new StringBuilder();
            for (int j = i; j < s.length(); j++)
            {
                sb.append(s.charAt(j));
                if (isPalindromic(sb.toString()))
                {
                 //   System.out.println(sb.toString());
                    ans++;
                }
            }
        }
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The constraint on the length of the string needs to be increased (say to 2000/3000), so that the bruteforce solution shown above TLEs.

#### Screenshots

![image](https://user-images.githubusercontent.com/42085404/169685072-aab33186-b654-43af-87d3-59b5deedddf2.png)

#### Additional context

A worst-case scenario that satisfies the current constraint (1000 'a's) takes about 670 ms to complete.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
