### ISSUE TITLE
Help Center and then Sign Out

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#74]
**What kind of the bug**

- [x] other

**Describe the bug**
I clicked the **Help Center** at the page bottom, and it asked me to sign out.

![Snipaste_2020-03-25_11-51-20](https://user-images.githubusercontent.com/32877011/77569043-32360080-6e8f-11ea-91f6-435f12418d0d.png)
![Snipaste_2020-03-25_11-51-29](https://user-images.githubusercontent.com/32877011/77569053-36621e00-6e8f-11ea-8ef1-89e48ab11286.png)

**Comment by CooperCooperCooper** [comment]
Hi @caoxingdong,
Thank you for reaching out to us. Please share this issue with our team to our support channel here: https://support.leetcode.com/hc/en-us. We appreciate your support.
