### ISSUE TITLE
Missing Test Case - 987. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by camillax** [LeetCode-Feedback/LeetCode-Feedback#7402]
#### Your LeetCode username

camillaxu

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This problem is exactly the same problem as 314 just with a different title it seems

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
These two problems are still a bit different. You may use the solution to problem 987 for problem 314 and check whether the solution can be accepted or not.

**Comment by LC-Pam** [comment]
Please check stromsunshine's reply. Thank you for your support!
