### ISSUE TITLE
Existing Test Cases :-    474. Ones and Zeroes

### ISSUE THREAD

**Issue by Pratyushpandey08** [LeetCode-Feedback/LeetCode-Feedback#7406]
#### Your LeetCode username :
pratyush08

#### Category of the bug
Existing Test Cases , Bug

#### Description of the bug
Running correct , but shows wrong expected output on submission.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int findMaxForm(vector<string>& strs, int m, int n) {
        int zero=0,one=0,s;
        for(int i=0;i<strs.size();i++){
            for(int j=0;j<strs[i].size();j++){
                if(strs[i]=="0"){
                    zero++;
                }else{
                    one++;
                }
                if(zero <= m && one <= n) s= strs[i].size();
            }
        }
        return s;
    }
};
```

#### Language used for code:   
C++

#### Expected behavior
Expected output should be 4 , but its 3 on submission. However, its ok on Running part.
![Screenshot (79)](https://user-images.githubusercontent.com/83027989/169815730-440093f9-e096-417d-8864-bca37dcf44d2.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
