### ISSUE TITLE
Existing Test Case - 1654. Minimum Jumps to Reach Home

### ISSUE THREAD

**Issue by khushal0201** [LeetCode-Feedback/LeetCode-Feedback#7407]
#### Category of the bug

- [ ]  Question
- [ ] Solution
- [ ] Language
- [x] Error in Test Case 

#### Code you used for Submit/Run operation

```
class Solution:
    def minimumJumps(self, forbidden: List[int], a: int, b: int, x: int) -> int:
        
             
              df=[(0,"")]
              lst=set(forbidden)
              j=0
              while df:
                   xc=set()
                   # vis=set()
                   for i in df:
                        if i[0] in lst or i[0]<0 or (i[0]-x>b and a>b):
                            continue
                        if i[0]==x:
                            return j
                        if (i[0]+a,"b") in xc :
                            xc.remove((i[0]+a,"b"))
                        
                        xc.add((i[0]+a,"f"))
                            
                        if i[0]!="b" and (i[0]-b,"f") not in xc:
                                 xc.add((i[0]-b,"b"))
                                 
                        
                   j+=1
                   # print(j,xc)
                    
                   df=xc
              return -1
};
```

#### Expected behavior

In case 93 output should be 921 but expected is -1 which is wrong

#### Screenshots

<img width="694" alt="image" src="https://user-images.githubusercontent.com/47549160/169819432-a45a788e-f7f3-47c6-8a1b-0af7684d4170.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case that you use.
The submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by khushal0201** [comment]
Test case- 93
Submission link -https://leetcode.com/submissions/detail/705430789/
