### ISSUE TITLE
Missing Test Case - 49. Group Anagrams

### ISSUE THREAD

**Issue by HZ2412** [LeetCode-Feedback/LeetCode-Feedback#7408]
#### Your LeetCode username

kd8sp

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

Test case: ["zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz","zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"] will fail my accepted code.
The main idea is that if I am calculating hash codes for the strings by taking the product of prime numbers raised to the count of the character appearing, the Math.Pow function in Java may overflow. If it does, it will return 9223372036854775807. The test case above contains two strings, one of length 48, one of length 49. But since Math.Pow overflows, it will return the same hash code, which is incorrect.

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<String>> groupAnagrams(String[] strs) {
        int[] seen = new int[strs.length];
        List<List<String>> results = new ArrayList<>();        
        Map<Long, List<String>> hm = new HashMap<>();
        int[] primes = getPrimes();
        int max = Integer.MAX_VALUE;
        
        for (int i = 0; i < strs.length; i++) {
            long hash_code = hash(strs[i], primes);           
            List<String> list = hm.getOrDefault(hash_code, new ArrayList<String>());
            if (list.size() == 0) {
                results.add(list);
            }
            list.add(strs[i]);
            hm.put(hash_code, list);
        }        
        return results;
    }
    
    
    private long hash(String s, int[] primes) {
        int[] arr = new int[26];
        for (int i = 0; i < s.length(); i++) {
            arr[s.charAt(i) - 'a']++;
        }
        long hash_code = 1;
        int counter = 1;
        
        for (int i = 0; i < arr.length; i++) {
            hash_code %= 10000000000L;            
            hash_code *= Math.pow((double)primes[i], arr[i]);                            
        }        
        return hash_code;
    }
    
    
    private int[] getPrimes() {
        int[] ans = new int[26];
        int i = 0, num = 2;
        while (i < 26) {
            if (prime(num)) {
                ans[i++] = num;
            }
            num++;
        }
        return ans;
    }
    
    private boolean prime(int n) {        
        for (int divisor = 2; divisor < n; divisor++) {
            if (n % divisor == 0) {
                return false;
            }
        }
        return true;
    }
}
```

#### Expected behavior

My accepted code should fail.

#### Screenshots

![image](https://user-images.githubusercontent.com/24820371/169850231-7cd4a11e-42d2-4b3f-9be9-ce304fc64ca3.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
