### ISSUE TITLE
Existing test case Q456. 132 Pattern

### ISSUE THREAD

**Issue by CodeMonger47** [LeetCode-Feedback/LeetCode-Feedback#7409]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [] Missing Test Cases 

#### Description of the bug

The test case [3,5,0,3,4] has no possible 132 pattern.
the possible subarrays would be [3,5,0],[5,0,3],[0,3,4]
Still the expected result is true.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean find132pattern(int[] nums) {
        if(nums.length<3){
            return false;
        }
        else{
        for(int i=0;i<nums.length;i++){
        if(i+2<nums.length){
          if(nums[i]<nums[i+2] && nums[i+2]<nums[i+1])return true;  }
        }   
            }
        return false;
    }
}
```

#### Expected behavior

Test Case should have returned false.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment]
Do you see the word "subsequence"? A subsequence is not required to be consecutive! Therefore, this test case has a subsequence [3,5,4] so the result should be true.

Also, Example 3 of the problem already explains that a subsequence is not required to be consecutive.

**Comment by LC-Pam** [comment]
Please check stromsunshine's reply, thank you for your support!
