### ISSUE TITLE
BLOCKED - Please add constraints - 77. Combinations

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#741]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

77. Combinations
https://leetcode.com/problems/combinations/

Please add constraints

Below are test results.

NOTE that these don't make sense since no constraints given.

	20
	10
	pass

	21
	10
	output limit exceeded

	50
	1
	pass

	50
	25
	bad_alloc

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Expected: Constraints need to be given in the problem.
Actual: Constraints are Not given in the problem.

Code is ready to submit.
But BLOCKED again.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
