### ISSUE TITLE
Description - Problem 468 (Validate IP Address)

### ISSUE THREAD

**Issue by TonyxSun** [LeetCode-Feedback/LeetCode-Feedback#7413]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Description of question has grammar mistake and wrong example. 
**Grammar mistake** (but...while)
`For example, "192.168.1.1" and "192.168.1.0" are valid IPv4 addresses but "192.168.01.1", while "192.168.1.00" and "192.168@1.1" are invalid IPv4 addresses.`

**Wrong example**:
the constraints state that `queryIP consists only of English letters, digits and the characters '.' and ':'` but `@` is included in the sentence above.

#### Code you used for Submit/Run operation

```
class Solution:
    def checkIPv4(self, queryIP):
        list = queryIP.rsplit(sep=".")
        if len(list) != 4: return "Neither"
        for x in list:
            try:
                intX = int(x)
                if intX >= 0 and intX <= 255:
                    if str(intX) == x:
                        continue
                return "Neither"
            except:
                return "Neither"
        return "IPv4"
        
    def checkIPv6(self, queryIP):
        list = queryIP.rsplit(sep=":")
        if len(list) != 8: return "Neither"
        for x in list:
            try:
                intX = int(x, 16)
                if len(x) >= 1 and len(x) <= 4:
                    continue
                return "Neither"
            except:
                return "Neither"
        return "IPv6"
    
    def validIPAddress(self, queryIP: str) -> str:
        if len(queryIP) > 39:
            return "Neither"
        elif "." in queryIP:
            return self.checkIPv4(queryIP)
        else:
            return self.checkIPv6(queryIP)
        return "Neither"
```

#### Language used for code

Python3

#### Screenshots

![CleanShot 2022-05-24 at 00 12 00](https://user-images.githubusercontent.com/68176295/169947411-f49f61ea-313f-4506-904c-4c67a243a48c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
