### ISSUE TITLE
Wrong Test Case - 884. Uncommon Words from Two Sentences

### ISSUE THREAD

**Issue by siddharth784** [LeetCode-Feedback/LeetCode-Feedback#7414]
#### Your LeetCode username
user4161Vv

#### Category of the bug
- [ ] Question
- [ ] TestCases

#### Description of the bug

The question wants us to return an array of all uncommon words in given 2 sentences. And definition of uncommon word given is: A word is uncommon if it appears exactly once in one of the sentences, and does not appear in the other sentence. However, one of the test case for the question is 
Input:
"apple apple"
"banana"
Expected:
["banana"]

But according to the question, apple should have been in the expected solution, because it appears multiple times, but only in a single sentence not both of them. 
I came across this bug when I tried running my following code which should have successfully submitted but couldn't because of such wrong test cases

#### Code you used for Submit/Run operation

```
class Solution {
    public String[] uncommonFromSentences(String s1, String s2) {
        String[] sen1=s1.split(" ");
        String[] sen2=s2.split(" ");
        Map<String,Boolean> hm=new HashMap<>();
        for(String str:sen1)
            hm.put(str,true);
        for(String str:sen2){
            if(hm.containsKey(str))
                hm.put(str,false);       //basically put false for a string if it is also occurring in the 2nd string
            else
                hm.put(str,true);
        }
        int count=0;
        for(Boolean b:hm.values()){
            if(b==true)
                count++;
        }
        String[] ans=new String[count];
        int k=0;
        for(String s:hm.keySet()){
            if(hm.get(s)==true)
                ans[k++]=s;
        }
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

My code is the ideal solution as per the question, but it fails because of mismatch b/w question and testcases.

#### Screenshots

![Uncommon Words from Two Sentences - Submission Detail - LeetCode - Brave 5_24_2022 12_18_54 PM](https://user-images.githubusercontent.com/82464305/169966674-e904c381-e83f-4a52-ac20-c7c6c17642b4.png)

**Comment by stormsunshine** [comment]
Please read the following sentence in problem description carefully.
> A word is **uncommon** if it appears exactly once in one of the sentences, and **does not appear** in the other sentence.

It is clearly stated that an uncommon word appears **exactly once** in one sentence.

**Comment by LC-Pam** [comment]
Please check stromsunshine's reply. Thank you for your support.
