### ISSUE TITLE
Missing Test Case - 721. Accounts Merge

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#7415]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

`1 <= accounts[i][j] <= 30`
should be
`1 <= accounts[i][j].length <= 30`

#### Code you used for Submit/Run operation

```
```

#### Expected behavior
Question Constraints must be clear

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
