### ISSUE TITLE
1533. Find the Index of the Large Integer

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#742]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Incorrect problem code template

#### Code you used for Submit/Run operation

```
# """
# This is ArrayReader's API interface.
# You should not implement it, or speculate about its implementation
# """
#class ArrayReader(object):
#	 # Compares the sum of arr[l..r] with the sum of arr[x..y]
#	 # return 1 if sum(arr[l..r]) > sum(arr[x..y])
#	 # return 1 if sum(arr[l..r]) > sum(arr[x..y])
#	 # return 1 if sum(arr[l..r]) > sum(arr[x..y])
#    def compareSub(self, l, r, x, y):
#        """
#        :type l, r, x, y: int
#        :rtype int
#        """
#
#	 # Returns the length of the array
#    def length(self):
#        """
#        :rtype int
#        """

class Solution(object):
    def getIndex(self, reader):
        """
        :type reader: ArrayReader
        :rtype: integer
        """
```

#### Language used for code
Python

#### Expected behavior

> int compareSub(int l, int r, int x, int y): where 0 <= l, r, x, y < ArrayReader.length(), l <= r and x <= y. 
> The function compares the sum of sub-array arr[l..r] with the sum of the sub-array arr[x..y] and returns:
> 1 if arr[l]+arr[l+1]+...+arr[r] > arr[x]+arr[x+1]+...+arr[y].
> 0 if arr[l]+arr[l+1]+...+arr[r] == arr[x]+arr[x+1]+...+arr[y].
> -1 if arr[l]+arr[l+1]+...+arr[r] < arr[x]+arr[x+1]+...+arr[y].
> 

Should be changed according to problem description

**Comment by lc-pam** [comment]
Hi @leet212 
Thanks for reaching out to us. Looks like the code in your expected behavior is the same as the code in the problem code template. Would you mind updating the expected behavior? Thank you!

**Comment by leet212** [comment]
Hello @lc-pam 
I have updated the issue with what should be in the template rather than what currently is. Thank you.

**Comment by lc-ivan** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @leet212 ,
Thanks for your feedback regarding this question. Upon review, our team has updated this problem a while ago, so, we will not be rewarding any LeetCoins for this ticket. Thank you once again and happy LeetCoding!
