### ISSUE TITLE
【题目描述不恰当】 - 467. 环绕字符串中唯一的子字符串

### ISSUE THREAD

**Issue by LetMeFly666** [LeetCode-Feedback/LeetCode-Feedback#7420]
<b><a href="https://leetcode.cn/u/tisfy/">tisfy</a></b>

**Bug 类型**

- [ ] 题目

**描述**

题目中说：

> 返回```s```中 **唯一** 的```p```的非空子串的数量

但是我觉得”唯一“略有歧义，不如描述为：
> 返回```s```中 **不同** 的```p```的非空子串的数量

这样与原版英文题目”unique non-empty substrings“也更为相似。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by Tisfy** [comment]
我也在做今天的每日一题，支持大佬的想法。

**Comment by LetMeFly666** [comment]
> 感谢反馈，此问题已转给题目运营团队会尽快确认。

感谢力扣题目运营团队！

**Comment by LetMeFly666** [comment]
并且**示例2**的**解释**中多了一个英文句号```.```

![0](https://user-images.githubusercontent.com/56995506/170190915-26c461dc-b37a-4ef5-841f-84d19038a737.jpg)

**Comment by feiceh** [comment]
你好，当前题目描述已更新，ID：[tisfy](https://leetcode.cn/u/tisfy/) 给予积分奖励，请查收。

**Comment by LetMeFly666** [comment]
> 你好，当前题目描述已更新，ID：[tisfy](https://leetcode.cn/u/tisfy/) 给予积分奖励，请查收。

收到，谢谢！
