### ISSUE TITLE
Typo - 489. Robot Room Cleaner

### ISSUE THREAD

**Issue by AristoChen** [LeetCode-Feedback/LeetCode-Feedback#7422]
#### Your LeetCode username
AristoChen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In `Solution`, there is one line like this `What do do if after the right turn there is an obstacle just in front ?`

#### Expected behavior

I guess it should be `What to do if after the right turn there is an obstacle just in front ?`

#### Screenshots

![image](https://user-images.githubusercontent.com/20593333/170182456-ab58a667-c1a5-4704-917e-aa9ac64a9e9b.png)

**Comment by LC-Pam** [comment]
Thank you for your time.All solutions are WA after handling the problem after the contest. We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
