### ISSUE TITLE
108. 将有序数组转换为二叉搜索树

### ISSUE THREAD

**Issue by YETLD** [LeetCode-Feedback/LeetCode-Feedback#7424]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名 yetld
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [√] 题目
- [√] 题解

**描述**
在测试用例中输入[1,2,3,4,5]
返回的预期结果为[3,2,5,1,null,4]
测试用例符合题目的严格递增，但是预期结果的左边树高度为3，右边为9，我认为不符合题目说的高度差小于1

**Comment by stormsunshine** [comment]
预期结果的树结构可视化如下图所示：

![image](https://user-images.githubusercontent.com/12067364/170267125-ae5cd770-a48d-4cbf-9e27-5a680d833b15.png)

哪来的高度为 9？

这个测试用例下构造的树只有 5 个结点，怎么可能出现高度为 9 的情况？

**Comment by YETLD** [comment]
不好意思，是我理解错了
