### ISSUE TITLE
剑指 Offer II 008. 和大于等于 target 的最短子数组 答案错误

### ISSUE THREAD

**Issue by G-hx** [LeetCode-Feedback/LeetCode-Feedback#7425]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
G_hx

**Bug 类型**
- [ ] 题目
- [√ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
原题目：给定一个含有 n 个正整数的数组和一个正整数 target 。找出该数组中满足其和 ≥ target 的长度最小的 连续子数组 [numsl, numsl+1, ..., numsr-1, numsr] ，并返回其长度。如果不存在符合条件的子数组，返回 0 。

测试的时候：输入
213
[12,28,83,4,25,26,25,2,25,25,25,12]

输出应为7，但官方给出答案为8

来源：力扣（LeetCode）
链接：https://leetcode.cn/problems/2VG8Kg/
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**你使用的语言**
C++

**你提交或者运行的代码**
class Solution {
public:
    int minSubArrayLen(int target, vector<int>& nums) {
        sort(nums.begin(), nums.end());
        int len=nums.size();
        int count=0;
        for(int i=len-1; i>=0; i--){
            target-=nums[i];
            count++;
            if(target<=0) break;
        }
        if(target>0) return 0;

        return count;
    }
};

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by stormsunshine** [comment]
这道题目要求返回最短子数组的长度，不是最短子序列的长度，子数组必须连续。所以该测试用例的答案是 8，这是正确的。

题目描述明确说了连续子数组，是否可以认真阅读题目描述？
