### ISSUE TITLE
Inaccurate function signature for python3 snippet - 94. Binary Tree Inorder Traversal

### ISSUE THREAD

**Issue by Rosswell** [LeetCode-Feedback/LeetCode-Feedback#7427]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

`inorderTraversal`'s return type for python3 doesn't accommodate the null return value for Example 2 (when root is null)

#### Expected behavior
signature should be 
```python3
def inorderTraversal(self, root: Optional[TreeNode]) -> Optional[List[int]]
```
rather than 
```python3
def inorderTraversal(self, root: Optional[TreeNode]) -> List[int]
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
When the root is null, we should return an empty list and not null. The return type is ok.
 We appreciate your support!
