### ISSUE TITLE
435. Non-overlapping Intervals: "Accepted solution" Nr. 3 does not pass the tests.

### ISSUE THREAD

**Issue by snophey** [LeetCode-Feedback/LeetCode-Feedback#7429]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Solution Nr. 3 (and probably also solution nr. 2) fails with "Time Limit Exceeded" despite being marked as "accepted" in the solution article.

#### Code you used for Submit/Run operation

The following code is copied directly from the solution article. It fails at 55/58 test cases.

```
class Solution {
  class myComparator implements Comparator<int[]> {
    public int compare(int[] a, int[] b) {
      return a[1] - b[1];
    }
  }
  public boolean isOverlapping(int[] i, int[] j) {
    return i[1] > j[0];
  }
  public int eraseOverlapIntervals(int[][] intervals) {
    if (intervals.length == 0) {
      return 0;
    }
    Arrays.sort(intervals, new myComparator());
    int dp[] = new int[intervals.length];
    dp[0] = 1;
    int ans = 1;
    for (int i = 1; i < dp.length; i++) {
      int max = 0;
      for (int j = i - 1; j >= 0; j--) {
        if (!isOverlapping(intervals[j], intervals[i])) {
          max = Math.max(dp[j], max);
          break;
        }
      }
      dp[i] = Math.max(max + 1, dp[i - 1]);
      ans = Math.max(ans, dp[i]);
    }
    return intervals.length - ans;
  }
}
```

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
