### ISSUE TITLE
【题目描述错误】699. 掉落的方块

### ISSUE THREAD

**Issue by EggEggLiu** [LeetCode-Feedback/LeetCode-Feedback#7430]
**Bug 类型**
- [x] 题目

**描述**
题目描述示例1中下标填写错误

题目原始描述：
> 第三个方块 positions[1] = [6, 1] 掉落：

正确描述：
> 第三个方块 positions[2] = [6, 1] 掉落：

**屏幕截图**
![image](https://user-images.githubusercontent.com/89680274/170391288-ae1f1236-5d77-4dea-bdde-9a43ff86ad85.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by EggEggLiu** [comment]
示例1描述已修改

![image](https://user-images.githubusercontent.com/89680274/171581653-9664fbed-90fb-4b8c-8090-6b01dd46ca7b.png)
