### ISSUE TITLE
Intersection of Two Linked Lists: BUG REPORT: Faulty Object Type in Error Statement

### ISSUE THREAD

**Issue by NiviRocks** [LeetCode-Feedback/LeetCode-Feedback#7432]
#### Your LeetCode username
Nibedita_Chakraborty

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

I am getting error in the last line return ``` res.val ``` as in the given code.
It say ``` .val ``` has been used on an int object but in stdout it can be seen through the print statement  (check the screenshot provided) ```print(type(res),res)``` that ```type(res)``` is not int type.

#### Code you used for Submit/Run operation

// Two Sum
```
class Solution(object):
    def getIntersectionNode(self, headA, headB):
        """
        :type head1, head1: ListNode
        :rtype: ListNode
        """
        listA=[]
        listB=[]
        currA=headA
        currB=headB
        while currA!=None or currB!=None:
            if currA!=None:
                listA.append(currA)
                currA=currA.next
            if currB!=None:
                listB.append(currB)
                currB=currB.next
        if len(listA) < len(listB):
            l=len(listA)
        else:
            l=len(listB)
        res=None
        for i in range(-1,-l,-1):
            if listA[i]==listB[i]:
                res=listA[i]
            else:
                break
        if res==None:    
            return res
        else:
            print(type(res),res)
            return res.val
```

#### Language used for code

Python

#### Expected behavior

The last line of the code ```return res.val``` should return the value of "res" where, res is an item in listA and listB. Here listA and listB store nodes of the given linked list.

#### Screenshots

![059ae8b6-f39f-491b-8cdb-31f614c76012_1653201128 4742987](https://user-images.githubusercontent.com/96379756/170406827-01bb9cb9-f5a6-4e5c-890e-654f0d194557.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The problem name
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.
The statement said"return the node at which the two lists intersect."
The expected return value is a node and not an int. The code can pass this error if the user removed .val from the return statement.
We appreciate your support!

**Comment by NiviRocks** [comment]
> The statement said"return the node at which the two lists intersect."
Thank you for the clarification. I was able to successfully submit the problem.
