### ISSUE TITLE
Add Python/C++ example to solution tab for "Add Two Numbers" and update Java solution

### ISSUE THREAD

**Issue by tannerdolby** [LeetCode-Feedback/LeetCode-Feedback#7433]
#### Your LeetCode username
[gnaare](https://leetcode.com/gnaare/)

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hi LeetCode team, the solution example for [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/) could be improved as the extra new `ListNode` creation within L15-17 of current solution isn't necessary. This logic can be handled by the while condition which allows for L15-17 to be removed. A bit more compact and improves readability.

This issue also proposes Python and C++ solutions for Approach 1: Elementary Math.

#### Code you used for Submit/Run operation

Below is the proposed improvement to the Java solution that handles the `carry` conditional check in the `while` condition, which avoids creating an extra `ListNode` (L15-17 of current solution). Also proposes removing extra `ListNode` variables `p` and `q` as we can use `l1` and `l2` without consuming extra space.

These changes would affect the existing solution description as list item 3 from Approach 1 states "Initialize p and q to head of l1 and l2 respectively" which would no longer be needed.

```java
// Add Two Numbers (Java improved)
public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
    ListNode dummyHead = new ListNode(0);
    ListNode curr = dummyHead;
    int carry = 0;
    while (l1 != null || l2 != null || carry != 0) {
        int x = (l1 != null) ? l1.val : 0;
        int y = (l2 != null) ? l2.val : 0;
        int sum = carry + x + y;
        carry = sum / 10;
        curr.next = new ListNode(sum % 10);
        curr = curr.next;
        if (l1 != null) l1 = l1.next;
        if (l2 != null) l2 = l2.next;
    }
    return dummyHead.next;
}
```

Proposed Python3 Solution for Approach 1:

```python3
# O(max(m,n)) time and O(max(m,n)) space
def addTwoNumbers(self, l1: Optional[ListNode], l2: Optional[ListNode]) -> Optional[ListNode]:
    dummyHead = ListNode(0)
    curr = dummyHead
    carry = 0
    while l1 != None or l2 != None or carry != 0:
        l1Val = l1.val if l1 else 0
        l2Val = l2.val if l2 else 0
        columnSum = l1Val + l2Val + carry
        carry = columnSum // 10
        newNode = ListNode(columnSum % 10)
        curr.next = newNode
        curr = newNode
        l1 = l1.next if l1 else None
        l2 = l2.next if l2 else None
    return dummyHead.next
```

Proposed C++ Solution for Approach 1:

```cpp
// O(max(m,n)) time and O(max(m,n)) space
ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
    ListNode *dummyHead = new ListNode(0);
    ListNode *curr = dummyHead;
    int carry = 0;
    while (l1 != NULL || l2 != NULL || carry != 0) {
        int x = l1 ? l1->val : 0;
        int y = l2 ? l2->val : 0;
        int sum = carry + x + y;
        carry = sum / 10;
        curr->next = new ListNode(sum % 10);
        curr = curr->next;
        l1 = l1 ? l1->next : nullptr;
        l2 = l2 ? l2->next : nullptr;
    }
    return dummyHead->next;
}
````

#### Language used for code
Python, C++, Java

#### Expected behavior
For the `carry` conditional check to be inside the while loop to avoid writing extra logic after the `while`.

#### Screenshots
<img width="530" alt="Screen Shot 2022-05-25 at 8 10 21 PM" src="https://user-images.githubusercontent.com/48612525/170408041-90f6ccbb-3e37-47d5-90cd-580174da8551.png">

#### Additional context
I understand LeetCode has post authors that handle writing solutions and probably adding language specific solutions, so I wasn't entirely sure if this issue and/or repository was the correct place to bring this up. Feel free to point me in the right direction if need be. Thanks!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!

**Comment by tannerdolby** [comment]
@LC-Pam No problem! Thank you for keeping me updated throughout the review. I'm happy to see my feedback was helpful!

I appreciate everything you and your team do to keep LeetCode a great platform. Thanks again!
