### ISSUE TITLE
Functioning code not running properly inside leetcode - 191. Number of 1 Bits

### ISSUE THREAD

**Issue by SteindelSE** [LeetCode-Feedback/LeetCode-Feedback#7435]
### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

### Description of the bug

Code is returning improper number when run inside leetcode, but clearly works in the Microsoft C# Compiler.

### Code you used for Submit/Run operation

```
public class Solution {
    public int HammingWeight(uint n) {
        // Return number of 1 bits from unsigned integer
        // 1. Loop through integer as string, counting 1s
        // 2. return count
        int count = 0;
        string num = n.ToString();
        for (int i = 0; i < num.Length; i++) {
            if (num[i] == '1') {
                count++;
            }
        }
        return count;
    }
}
```

### Language used for code

C#

### Expected behavior

Should return 3, returns 2.

#### Returns 2 improperly in leetcode:

![image](https://user-images.githubusercontent.com/88400258/170445645-a98831dc-7d24-4520-90fa-2fae90ff0efb.png)

#### Returns 3, as expected, inside C# compiler:

![image](https://user-images.githubusercontent.com/88400258/170445729-87e2051c-f347-4760-a51b-1c88030f8791.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
The output is wrong.
The binary input 00000000000000000000000000001011 is passed to the function as the integer 11.
Please process the binary representation of it.
We appreciate your support!
