### ISSUE TITLE
A follow-up Should be Added - 1492. The Kth factor of n

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#7438]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The brute force with O(n) time complexity can be accepted now. However, the O(sqrt(n)) solution for this problem exists, and if an interviewer use this problem in a real interview, the expected solution cannot be the brute force. As the second problem of the 29th biweekly contest, changing the constraints can be unfriendly to users who use virtual contest, even if the difficulty of the O(sqrt(n)) solution is suitable for the second problem of a weekly contest. So the best way is adding a follow up: can you solve this problem in less than O(n) time complexity?

Code you used for Submit/Run operation

The time complexity of the code below is O(n)
```
class Solution:
    def kthFactor(self, n: int, k: int) -> int:

        cnt = 0
        for j in range(1,n+1):
            if not n%j:
                cnt+=1
                if cnt==k:
                    return j
        return -1
```

The time complexity of the code below is O(sqrt(n))
```
class Solution:
    def kthFactor(self, n: int, k: int) -> int:

        square = n**.5==int(n**.5)
        cnt = 0
        big = []
        for j in range(1,int(n**.5)+1):
            if not n%j:
                cnt+=1
                if cnt==k:
                    return j
                big.append(n//j)

        big = big[::-1] if not square else big[::-1][1:]
        for num in big:
            cnt+=1
            if cnt==k:
                return num
        return -1
```

Language used for code
Python3

Expected behavior
A follow-up should be added: can you solve this problem in less than O(n) time complexity?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
