### ISSUE TITLE
A Follow-up Should be Added - 1588. Sum of All Odd Length Subarrays

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#7439]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug

This issue is to reopen issue #5505.
There is a nice math solution with O(n) time complexity, and I do think this solution is worth knowing. The problem 2063. Vowels of All Substrings can be solved with an algorithm which is very similar to this problem. I believe that the O(n) solution can be required during a real interview, otherwise the problem 2063 should not be introduced to the LeetCode.
A follow-up requirement should be added:
**Can you solve this problem in O(n) time complexity?**

Code you used for Submit/Run operation

The time complexity of the code below is O(n^2):
```
class Solution:
    def sumOddLengthSubarrays(self, arr: List[int]) -> int:
        sum = 0
        n = len(arr)
        prefixSums = [0] * (n + 1)
        for i, v in enumerate(arr):
            prefixSums[i + 1] = prefixSums[i] + v
        for start in range(n):
            length = 1
            while start + length <= n:
                end = start + length - 1
                sum += prefixSums[end + 1] - prefixSums[start]
                length += 2
        return sum
```

The time complexity of the code below is O(n):
```
class Solution:
    def sumOddLengthSubarrays(self, arr: List[int]) -> int:
        s = 0
        for j in range(len(arr)):
            leftall = j
            rightall = len(arr)-j-1
            lefte = leftall//2+1
            righte = rightall//2+1
            lefto = (leftall+1)//2
            righto = (rightall+1)//2
            s +=arr[j]*(lefte*righte+lefto*righto)
        return s
```

Language used for code
Python3

Expected behavior
A follow-up requirement should be added:
Can you solve this problem in O(n) time complexity?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time. We have added the follow up. We appreciate your support!
