### ISSUE TITLE
961-题目测试样例补充

### ISSUE THREAD

**Issue by cuber-lotus** [LeetCode-Feedback/LeetCode-Feedback#7441]
| name             | about                                                        | title            | labels   | assignees                                      |
| ---------------- | ------------------------------------------------------------ | ---------------- | -------- | ---------------------------------------------- |
| 题目测试样例补充 | [961. 在长度 2N 的数组中找出重复 N 次的元素](https://leetcode.cn/problems/n-repeated-element-in-size-2n-array/) | 961 缺少测试用例 | 测试样例 | [天赐细莲](https://leetcode.cn/u/cuber-lotus/) |

**原题：**  [961. 在长度 2N 的数组中找出重复 N 次的元素](https://leetcode.cn/problems/n-repeated-element-in-size-2n-array/)

**用户名**  : 天赐细莲

[天赐细莲](https://leetcode.cn/u/cuber-lotus/)

**Bug 类型**

-  缺少测试用例

**描述** 缺少完善的测试用例

**你使用的语言** C++

**你提交或者运行的代码**

**正确代码**

```cpp
class Solution {
public:
    int repeatedNTimes(vector<int>& nums) {
        int cmp0 = nums[0], cmp1 = nums[0];
        for (int i = 1; i < nums.size(); i++) {
            if (nums[i] == cmp0) {
                return nums[i];
            } else if (nums[i] == cmp1) {
                return nums[i];
            }
            cmp1 = nums[i];
        }
        return cmp1;
    }
};
```

**不正确代码**

提交后仍然能ac

```cpp
class Solution {
public:
    int repeatedNTimes(vector<int>& nums) {
        int n = nums.size();
        int start = nums[0], cand = nums[0];
        for (int i = 1; i <= n / 2 + 1; ++i) {
            if (nums[i] == start)
                return start;
            if (nums[i] == cand)
                return cand;
            cand = nums[i];
        }
        return cand;
    }
};
```

两份代码的区别在于是否需要循环完，还是只用循环一半

关于本代码思路的解释可以看这位大佬的题解：[一次遍历，O(n)时间O(1)空间解法，可能是最简洁的解法 - 在长度 2N 的数组中找出重复 N 次的元素 - 力扣（LeetCode）](https://leetcode.cn/problems/n-repeated-element-in-size-2n-array/solution/yi-ci-bian-by-reflyer-r7g1/)

**未检测出的测试样例**

```cpp
[1,6,3,6,5,2,4,6,6,6]
// 正确代码返回 6
// 不正确代码返回 4
```

**期望行为** 希望加强测类似试数据

**额外的上下文** 

官方题解：[在长度 2N 的数组中找出重复 N 次的元素 - 在长度 2N 的数组中找出重复 N 次的元素 - 力扣（LeetCode）](https://leetcode.cn/problems/n-repeated-element-in-size-2n-array/solution/zai-chang-du-2n-de-shu-zu-zhong-zhao-chu-w88a/)

已在官方题解的评论中说明了该问题

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：cuber-lotus 给予积分奖励，请查收。
