### ISSUE TITLE
Word Search - Typos in solution explanation

### ISSUE THREAD

**Issue by ppmjw10** [LeetCode-Feedback/LeetCode-Feedback#7443]
#### Your LeetCode username

pmariduena

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Several typos and missing context that make things unclear
- `As once notices,` should be `as one notices`
- `where we go as further as` should be `where we go as far as possible in the current direction`

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

Please fix the typos and missing context in the solution explanation as described above.

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team, but it will take more time to evaluate and fix. We appreciate your support!
