### ISSUE TITLE
150. Evaluate Reverse Polish Notation

### ISSUE THREAD

**Issue by HZ2412** [LeetCode-Feedback/LeetCode-Feedback#7446]
#### Your LeetCode username

kd8sp

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A typo in the solution:
29 - 1.66 = 27.33, not 28.33.
![image](https://user-images.githubusercontent.com/24820371/170570070-c5ce52db-ca1f-4439-ae05-f7f8a94b8285.png)

#### Code you used for Submit/Run operation

```


#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
Solution should write 27.33


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
![image](https://user-images.githubusercontent.com/24820371/170569521-d0a1c5c6-531b-44e6-8e21-2eaee2665376.png)



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
