### ISSUE TITLE
面试题 17.11 单词距离 测试样例补充

### ISSUE THREAD

**Issue by Holdonbei** [LeetCode-Feedback/LeetCode-Feedback#7449]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
holdonbei

**Bug 类型**
- [ ]面试题17.11 单词距离 缺少测试用例

**描述**
在错误的解答下，依然可以通过测试用例

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public int findClosest(String[] words, String word1, String word2) {
        int result = Integer.MAX_VALUE;
        int first = -1, second = -1;
        int n = words.length;
        for (int i = 0; i < n; i++) {
            if (word1.equals(words[i])) {
                first = i;
            }
            if (word2.equals(words[i])) {
                second = i;
            }
            if (first != -1 && second != -1) {
                result = Math.min(result, Math.abs(first - second));
            }
        }
        return result;
    }
}
```

**期望行为**
错误

**屏幕截图**
![image](https://user-images.githubusercontent.com/54311580/170610623-ad438286-59b1-48cb-a7cf-b542aefa4431.png)

**额外的上下文**
添加测试用例如下：
["I","am","a", "a", "from", "university","in","a","city","aa", "aa", "student"]
"a"
"student"

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：不处理。 提供的代码对这用例，并没有问题。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。

**Comment by Holdonbei** [comment]
您的邮件我已收到。
