### ISSUE TITLE
BLOCKED - Wrong constraints - 303. Range Sum Query - Immutable

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#745]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

303. Range Sum Query - Immutable
https://leetcode.com/problems/range-sum-query-immutable/

Two constraints are given for same `nums.length`.
They are conflicting each other.

>            0 <= nums.length <= 10^4
>        -10^5 <= nums.length <= 10^5

Is the 2nd constraint below for elements like below?

>        -10^5 <= nums[i], nums[j] <= 10^5

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

Expected:  Multiple conflicting constraints should Not be given for `nums.length`.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by manoharreddyporeddy** [comment]
Thank you for updating the problem.
