### ISSUE TITLE
Article Mistake - 39. Combination Sum

### ISSUE THREAD

**Issue by Raitless** [LeetCode-Feedback/LeetCode-Feedback#7451]
#### Your LeetCode username

ait

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

At line 8 of reference implementation in Python3 the comment says "deep copy", but the code at line 9 actually makes a shallow copy.

```python
# make a deep copy of the current combination
results.append(list(comb))
```

#### Expected behavior

The code is correct here, but the comment wrongly treats it as a deep copy.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LPRowe** [comment]
@Raitless Thanks for sharing your concern, this is actually a deep copy because calling `list(some_array)` is equivalent to `some_array[:]`. You can test that this produces a deep copy as follows:

```python
a = [1, 2, 3]
b = list(a)
b[0] = 4
print(a) # [1, 2, 3]
print(b) # [4, 2, 3]
```

Alternatively, this can be checked directly in the code with:
```python
print(comb is list(comb)) # False
```

**Comment by Raitless** [comment]
@LPRowe Thank you for your reply. The example you provided actually cannot show whether it's a deep copy. To test, we need following code:

```python
import copy

a = [[1, 2], 3]
b = list(a)
c = copy.deepcopy(a)

print(a[0] is b[0]) # True
print(a[0] is c[0]) # False

b[0].append(4)
print(a[0]) # [[1, 2, 4], 3]
```

Thus, `list(some_array)` is just a shallow copy. `list(some_array)` is equivalent to `some_array[:]` and `some_array.copy()`. They all are shallow copy. Only `copy.deepcopy(some_array)` makes a recursive copy which is the deep copy.

**Comment by LPRowe** [comment]
@Raitless Ah, I see your distinction here. Strictly speaking, if we had nested mutable data structures (like the list in a list that you showed above for `a`), you're right, this would fail to create a deep copy. Although in this situation, `comb` is guaranteed to only contain immutable data (integers), so we are effectively creating a deep copy. That said, I understand your suggestion, but I worry calling this a "shallow" copy would give the user the wrong impression. I'll give this some thought and update the comment if a good alternative comes to mind.  Feel free to drop a comment if you have any suggestions for wording that is concise and conveys the necessary information.

**Comment by Raitless** [comment]
@LPRowe Yeah, both ways work in this case. But for the accuracy of terminology, it'd better call it shallow copy and explain why it suffices in this case. Understanding the distinction may also help readers to correctly copy a two-dimensional array where a deep copy is needed.
