### ISSUE TITLE
Missing Test Case - 139. Word Break

### ISSUE THREAD

**Issue by meet1807** [LeetCode-Feedback/LeetCode-Feedback#7454]
#### Your LeetCode username
meet1807

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When I run the test case as a custom test-case it ouputs correctly but when I try to submit it outputs differently. how so?
I've attached the screen-shot below.
Problem : https://leetcode.com/problems/word-break/submissions/
It happened with Coin Change problem as well

#### Code you used for Submit/Run operation
```Python
class Solution:
    def wordBreak(self, s: str, wordDict: List[str], memo = {}) -> bool:
        if s in memo:
            return memo[s]
        if len(s) == 0:
            return True
        
        for word in wordDict:
            if s.find(word) == 0: 
                print("found")
                remainingWord = s[len(word):]
                if self.wordBreak(remainingWord, wordDict, memo):
                    memo[s] = True
                    return True
        memo[s] = False
        return False
```

#### Language used for code
Python

#### Expected behavior
It should output same as the custom test case.

#### Screenshots
![image](https://user-images.githubusercontent.com/22307267/170681063-8f8fb2ec-a90a-4b39-b5a8-935b71f682c4.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
The runtime on a solution can fluctuate based on a number of things, like site load or network performance. However, if it gets to the point of being unreliable or doesn't provide necessary results, we'd want to hear more about it. Would you mind sending over another problem (coin change) specific submission detail pages of your solutions to problems you've encountered this on?

**Comment by meet1807** [comment]
Thanks for getting back.
I wasn't referring to the run time. 
There are two feature:
- You can run test  (runs one test case)
- you can submit (runs all the cases)

look at the input and output for the same problem. How could same input have different ouptut with `test` and `submit`
![image](https://user-images.githubusercontent.com/22307267/170786363-9e5f9deb-87b4-456e-8bde-c40a17f5ce42.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.
