### ISSUE TITLE
Missing Test Case - 40. Combination Sum II

### ISSUE THREAD

**Issue by Vashesh08** [LeetCode-Feedback/LeetCode-Feedback#7458]
#### Your LeetCode username

vashesh2001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code passed the test, but later on I noticed it was missing a testcase:
[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
30

#### Code you used for Submit/Run operation

```
// 40. Combination Sum II
class Solution:
    def combinationSum2(self, candidates: List[int], target: int) -> List[List[int]]:
        result = {*{}}
        sum_total = sum(candidates)
        if sum(candidates) < target:
            return result
        if len(set(candidates)) == 1:
            if target % candidates[0] == 0:            
                result.add(tuple([candidates[0] for i in range(target // candidates[0])]))
            return result

        candidates.sort()
        length = len(candidates)
        def recurse(index, sum_remaining, sum_now=0, sum_arr=[]):
            if sum_now == target:
                sum_arr = tuple(sum_arr)
                result.add(sum_arr)
                return
            elif sum_now > target:
                return
            elif sum_remaining + sum_now < target:
                return
            if index == length:
                return
            sum_remaining -= candidates[index]
            recurse(index+1,sum_remaining,sum_now+candidates[index],sum_arr+[candidates[index]])
            recurse(index+1,sum_remaining,sum_now,sum_arr)
        
        recurse(0,sum_total)
        return result
```

#### Language used for code

Python3

#### Expected behavior

My code gave a Time Limit Exceeded error in the console. However, when I submit it, the solution is accepted although it should give an error. This indicates missing testcase.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
