### ISSUE TITLE
剑指 Offer II 001. 整数除法 错误测试用例

### ISSUE THREAD

**Issue by weguang** [LeetCode-Feedback/LeetCode-Feedback#7459]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
weguang

**Bug 类型**
- [ ] 测试用例 **13** 错误

**描述**
输入：
-2147483648
-1
输出：
2147483648
预期结果：
2147483647

该测试用例正确答案应该为2147483648，导致未通过

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
var divide = function(a, b,n=0) {
    // if(a>=0&&b>=0){
    //     for(;a-b>=0;n++){
    //         a-=b
    //     }
    //     return n
    // }else if(a<=0&&b>=0){
    //     a=-a
    //     return (-divide(a,b,n))
    // }else if(a>=0&&b<=0){
    //     b=-b
    //     return (-divide(a,b,n))
    // }else if(a<=0){}
    if (a !== b && Math.abs(a) === Math.abs(b)) {
    return -1
  } else if (Number.isNaN(Math.sqrt(a)) || Number.isNaN(Math.sqrt(b))) {

    if (a !== Math.abs(a) && b == Math.abs || a == Math.abs(a) && b !== Math.abs(b)) {
      a = Math.abs(a)
      b = Math.abs(b)
      return (-divide(a, b, n))
    }
    else {
      a = Math.abs(a)
      b = Math.abs(b)
      return (divide(a, b, n))
    }
  } else {
    // big = (a - b >= 0 ? a : b);
    // sma = (a - b >= 0 ? b : a);
    for (; a - b >= 0; n++) {
      a -= b
    }
    return n
  }
};
```

**期望行为**
正确答案应为 **2147483648**

**屏幕截图**
![image](https://user-images.githubusercontent.com/49125168/170775507-c76a9a08-a94e-4abd-bb94-7c64a31a0203.png)

**额外的上下文**
明显-2147483648除以-1等于2147483648

**Comment by stormsunshine** [comment]
题目描述明确说明了：

> 假设我们的环境只能存储 32 位有符号整数，其数值范围是 [−2<sup>31</sup>, 2<sup>31</sup>−1]。本题中，如果除法结果溢出，则返回 2<sup>31</sup> − 1

请在仔细阅读题目描述之后再判断测试用例是否存在问题。

**Comment by BrambleWave** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by LC-Pam** [comment]
请在仔细阅读题目描述之后再判断测试用例是否存在问题。
