### ISSUE TITLE
Violation of space complicity is not considered in submission - 41. First Missing Positive

### ISSUE THREAD

**Issue by rahuls24** [LeetCode-Feedback/LeetCode-Feedback#746]
#### Your LeetCode username
rahuls24

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

It is mention that the algorithm should run in O(n) time and uses constant extra space but the violation of space complicity is still accepted. It should also be considered as time complicity.

#### Code you used for Submit/Run operation

```
//41. First Missing Positive
class Solution:
    def firstMissingPositive(self, nums: List[int]) -> int:
        if len(nums)==0:
            return 1
        Set=set(nums)
        mini=sys.maxsize
        for i in nums:
            if mini>i:
                mini=i
        if mini>1:
            return 1
        else:
            i=1
            while True:
                if i in Set:
                    i+=1
                else:
                    return i
```

#### Language used for code

Python3

#### Expected behavior

If any algorithm is taking extra space then it should not be passed all test cases but currently, the space complicity is totally ignored

#### Screenshots

[https://i.ibb.co/Wt5fKJw/Screenshot-53.png](url)

#### Additional context

Qsn link [https://leetcode.com/problems/first-missing-positive/submissions/](url)

**Comment by lc-pam** [comment]
Hi @rahuls24 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @rahuls24 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
