### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by kys399** [LeetCode-Feedback/LeetCode-Feedback#7460]
#### Your LeetCode username
kysw399

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

nums:  first element of nums >= k, last element of nums >= k.
lenth of nums : bigger is better.
result : false. (sum of nums in i to j != n * k, 0<= i < j <= length of nums.)

#### Code you used for Submit/Run operation

```
// 523. Continuous Subarray Sum
class Solution {
    
    public boolean checkSubarraySum(int[] nums, int k) {
        int sum = nums[nums.length-1];
        
        for (int i = nums.length-2; i >= 0; i--) {
            if (nums[i] == nums[i+1] && nums[i] == 0) {
                return true;
            }
            sum+= nums[i];  
            
            if (sum >= k) {
                int temp = nums[i];
                for (int j = i+1; j < nums.length; j++) {
                    temp += nums[j];
                    if (temp%k == 0) {
                        return true;
                    }
                }
            }
            
        }    
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior

A time complexity O(n^2) solution gets TLE.

**Comment by stormsunshine** [comment]
A test case needs to be provided. I have created a test case that can make the code get TLE.

[523.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8790757/523.txt)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. 
The code accepted submission link: https://leetcode.com/submissions/detail/710911795/
We appreciate your support
![Screen Shot 2022-05-30 at 9 36 36 PM](https://user-images.githubusercontent.com/103138242/171075863-b26401cf-b951-492b-8662-5438869f3043.png)
!
