### ISSUE TITLE
468题缺少测试用例

### ISSUE THREAD

**Issue by JMC2002** [LeetCode-Feedback/LeetCode-Feedback#7462]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
子不語

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [*] 缺少测试用例

**描述**
468题 验证IP地址中，对于1.01.01.1测试用例，本应不通过，然而通过了提交。

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
var validIPAddress = queryIP =>
    queryIP.match(/^(?!0\d)((25[0-5]|2[0-4]\d|(1?\d?\d))($|(?!\.$)\.)(?<!0\d)){4}$/) ? "IPv4":
    queryIP.match(/^(([\da-fA-F]{1,4})($|(?!:$):)){8}$/) ? "IPv6" : "Neither";
```

**期望行为**
本应测试失败。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by JMC2002** [comment]
刚刚才看见。。。https://leetcode.cn/u/zi-bu-yu-mf/ ，是这个吗
