### ISSUE TITLE
Question Example - 864. Shortest Path to Get All Keys

### ISSUE THREAD

**Issue by sapphire921** [LeetCode-Feedback/LeetCode-Feedback#7463]
#### Your LeetCode username
sapphire921

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the Example 1, it has input grid = ["@.a.#","###.#","b.A.B"]
but based on the graph, the last cell of the first row is empty instead of a wall, so the first row should be "@.a.." instead of "@.a.#". 
Thus the input grid should be grid = ["@.a..","###.#","b.A.B"].

#### Expected behavior
In the Example 1, the input grid should be grid = ["@.a..","###.#","b.A.B"].

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
