### ISSUE TITLE
Missing Test Case - 828. Count Unique Characters of All Substrings of a Given String

### ISSUE THREAD

**Issue by ManideepNama** [LeetCode-Feedback/LeetCode-Feedback#7464]
#### Your LeetCode username

user6952la

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My answer for the test case "LEETCODE " is 103,I verified my code and also by counting manually.I tried it with different test case too and my answer seems to be the correct one.

#### Code you used for Submit/Run operation

```
class Solution:
    def uniqueLetterString(self, s: str) -> int:
        n=len(s)
        sub=[]
        new_sub=[]
        n2_sub=[]
        

        for i in range(n):
            j=1
            while i+j<n+1:
                sub.append(s[i:i+j])
                j+=1
        for i in sub:
            if i not in new_sub:
                new_sub.append(i)
        print(new_sub)
        for i in new_sub:
            n2_sub.append(set(i))
            
        print(n2_sub)

        k=0
        for i in n2_sub:
            k+=len(i)
        return k 
                
```

#### Expected behavior

I verified my answer by brute force technique for the word "LEETCODE",my answer seems to be the  right,which is 103.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ManideepNama** [comment]
I used python3

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
