### ISSUE TITLE
Unexpected test case behavior 67. Add binary

### ISSUE THREAD

**Issue by Sharma-K** [LeetCode-Feedback/LeetCode-Feedback#7465]
#### Your LeetCode username

keshav2743

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ]  Unexpected Test case behavior on submission
- [ ]  Platform related
 

#### Description of the bug

My code is giving correct output  in the custom test case but while submitting the same input, it is giving  wrong output.

#### Code you used for Submit/Run operation

```
  #include<bits/stdc++.h>
    class Solution {
   public:
    string addBinary(string a, string b) 
    {
      int arr1[10001], arr2[10001];
        
        for(int i=0; i<a.size(); i++)
        {
            arr1[i]= a[i]-'0';
        }
         for(int i=0; i<b.size(); i++)
        {
            arr2[i]= b[i]-'0';
        }
       int output[100001];
        int k = max(a.size(), b.size());
        int s = k;
        int carry=0;
        int i=a.size()-1, j=b.size()-1;
        while(i>=0&&j>=0)
        {
            int temp=arr1[i]+arr2[j]+carry;
            if(temp==2)
            {
                output[k]=0;
                carry=1;
            }
            else if(temp==3)
            {
                output[k]=1;
                carry=1;
            }
          else  if(temp==1)
            {
                output[k]=1;
                carry=0;
            }
            
            
            i--;
            j--;
        
        k--;
        }
        
        while(i>=0)
        {
            int temp = arr1[i]+carry;
             if(temp==2)
            {
                output[k]=0;
                carry=1;
            }
          else  if(temp==3)
            {
                output[k]=1;
                carry=1;
            }
           else if(temp==1)
            {
                output[k]=1;
                carry=0;
            }
            i--;
            k--;
        }
          while(j>=0)
        {
            int temp = arr2[j]+carry;
             if(temp==2)
            {
                output[k]=0;
                carry=1;
            }
           else if(temp==3)
            {
                output[k]=1;
                carry=1;
            }
           else if(temp==1)
            {
                output[k]=1;
                carry=0;
            }
            j--;
            k--;
        }
        output[0]=carry;
   string ans; 
        for(int i=0; i<=s; i++)
        {
            char a = output[i] +'0';
            ans.push_back(a);
        }
        if(carry==0)
        {
            return ans.substr(1);
        }
        else{
               return ans;
            }      

    }
};
```

#### Language used for code

c++

#### Expected behavior

for test case
"100"
"110010"

if I take this input on the custom test case(on leetcode only), it is showing output "110110". and it is showing the same output on different IDEs as well.
But on submitting the same test case it is giving the wrong answer as ""111110""

#### Screenshots

on custom test case
![Screenshot (303)](https://user-images.githubusercontent.com/83668892/170814049-f49893a3-e6b1-40e0-a78b-4d52ae7edbe4.png)

on submission
![Screenshot (304)](https://user-images.githubusercontent.com/83668892/170814073-3e4388dc-1af0-43f2-b8b0-caf887b1cceb.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.
