### ISSUE TITLE
Missing Test Case - 268. Missing Number

### ISSUE THREAD

**Issue by Tandon11** [LeetCode-Feedback/LeetCode-Feedback#7466]
#### Your LeetCode username

Tandon_G11

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

How value is getting assigned to missing variable, as for test case [0, 1] The if part won't work

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int missingNumber(vector<int>& nums) {
        sort(nums.begin(), nums.end());
        int n = nums.size();
        int missing;

        for(int i = 0; i < n; i++) {
            if(nums[i] != i) {
                // Update missing value
                missing = i;
                break;
            }
        }

        return missing;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Return Garbage value, Since variable is not getting assigned for test case [0, 1]

#### Screenshots

![Screenshot from 2022-05-28 11-51-15](https://user-images.githubusercontent.com/54017543/170814095-9f1af51d-16b3-4158-8a19-dfff1bf8a32c.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
