### ISSUE TITLE
题目-剑指 Offer 37. 序列化二叉树 不支持使用 Go 语言编程

### ISSUE THREAD

**Issue by jk2K** [LeetCode-Feedback/LeetCode-Feedback#7468]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
jk2k

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**

[剑指 Offer 37. 序列化二叉树](https://leetcode.cn/problems/xu-lie-hua-er-cha-shu-lcof/)
不支持使用 Go 语言编程

**你使用的语言**
Go

**你提交或者运行的代码**

**期望行为**
支持使用 Go 语言答题

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
您好，在与相关团队核实后：当前部分题目暂没有实现 GO 语言提交，我们会在后期的版本中不断增加更多语言的～

**Comment by jk2K** [comment]
这个编程语言，个人可以贡献吗？就像测试用例那样贡献？
