### ISSUE TITLE
494. Target Sum

### ISSUE THREAD

**Issue by seth-orai** [LeetCode-Feedback/LeetCode-Feedback#747]
#### Your LeetCode username

seth-orai

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

My solution to the problem has been accepted. The solution I have written do not account for all the actual test cases. So, the question has very weak test cases. Actually, my code assumes that the given target sum is always between -2000 to +2000, but it can be anything. Even after AC, I checked by giving my own test case. As expected, my solution do not match the expected solution.

#### Code you used for Submit/Run operation

```
int findTargetSumWays(vector<int>& nums, int S) {
        int n = nums.size(), i, j;
        
        if(S>2000)
            return 0;
        
        vector<vector<int>> dp(n, vector<int>(4001,0));
        
        dp[n-1][nums[n-1]+2000] = 1;
        dp[n-1][-nums[n-1]+2000] += 1;
        
        for(i=n-2; i>=0; i--)
            for(j=-1000; j<=1000; j++)
                dp[i][j+2000] = dp[i+1][j-nums[i]+2000] + dp[i+1][j+nums[i]+2000];
        
        return dp[0][S+2000];
    }
```

#### Language used for code

C++

#### Expected behavior

My solution, which assumes the given target sum is always between -2000 to +2000. So, further test cases must be added which reject similar solutions as of mine.

#### Screenshots

![Target Sum Fail](https://user-images.githubusercontent.com/52034084/89002668-557c2b00-d31b-11ea-81bf-a25e5e6b38e1.JPG)

#### Additional context

Add the test cases such as nums = [1,2,7,9,981], S = -100000000, where it should fail because this will ensure that the user does not pre assume that the given target sum is always between -2000 to +2000. The lists of test cases which should be added based on my concept can be very long, but adding two or three test cases will ensure the correctness. One more test case, which can be added : nums = [1,2,4,5,10], target = -500000.

**Comment by lc-ivan** [comment]
Hi @seth-orai  ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @seth-orai ,
Thank you for your feedback and suggestion regarding this problem. After review, our team has come to the conclusion that your test cases provided are correct but we will not be adding it to this problem based on previous technical assumptions. Once again, thank you for the feedback! Happy LeetCoding!
