### ISSUE TITLE
Missing Test Case - 1980. Find Unique Binary String

### ISSUE THREAD

**Issue by arnav12-3** [LeetCode-Feedback/LeetCode-Feedback#7470]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by arnav12-3** [comment]
class Solution {
public:
    string findDifferentBinaryString(vector<string>& nums) {
        string ans = "" ;
        int n = nums.size() ;
        for(int i = 0; i<n ; i++){
            int x_or = 0 ;
            for(int j = 0 ; j<n ; j++){
                x_or ^= (nums[j][i] - '0') ;
            }
            ans += ('0' + x_or) ;
        }
        return ans ;
    }
};

Language Used - C++ 
Expected Behaviour - 
TC 
["01","10"]
["00","01"]
["111","011","001"]
output -
"11"
"01"
"101"
Expected- 
"00"
"10"
"000"


Both the outputs are correct but my result is not getting accepted

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
