### ISSUE TITLE
687. 最长同值路径

### ISSUE THREAD

**Issue by baifamily** [LeetCode-Feedback/LeetCode-Feedback#7474]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名:bai

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
本题的样例2中的图片与文字描述不符。如图所示：
![image](https://user-images.githubusercontent.com/80093868/170832536-91fae1bd-4599-4473-9f7c-44d5686145de.png)

应该是下图所示的图形结构作为与文字相对应：
![image](https://user-images.githubusercontent.com/80093868/170832640-3b52371c-7fa8-4914-af74-a573173d61cc.png)

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    private int answer;
    public int longestUnivaluePath(TreeNode root) {
        if(root==null) {
            return 0;
        }
        this.answer = 0;
        dfs(root);
        return answer-1;
    }

    private int dfs(TreeNode root) {
        if(root==null) {
            return 0;
        }
        int left = dfs(root.left);
        int right = dfs(root.right);
        int ans = 0;
        int ak = 1;
        if(root.left!=null&&root.left.val==root.val) {
            ans=left;
            ak+=left;
        }
        if(root.right!=null&&root.right.val==root.val) {
            // System.out.println(ans+" "+right);
            ans=Math.max(ans,right);
            ak+= right;
        }
        ans++;
        this.answer = Math.max(this.answer,ans);
        this.answer = Math.max(this.answer,ak);
        return ans;
    }
}
```

**期望行为**
改变第二个样例的图片来实现图文一致。

**屏幕截图**
![image](https://user-images.githubusercontent.com/80093868/170832728-8ebc384c-1e49-45ba-afd6-98071570fcc7.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。
