### ISSUE TITLE
Issue Q2 Missing Test Case - 2284. Sender With Largest Word Count : 

### ISSUE THREAD

**Issue by anau99** [LeetCode-Feedback/LeetCode-Feedback#7475]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
public class Solution {
    public string LargestWordCount(string[] messages, string[] senders) {
        
            var d = new Dictionary<string, int>();
            int n = messages.Length;
            var set = new HashSet<string>(senders);
            var k = set.ToArray();
            for(int i = 0; i < k.Length; i++)
            {
                d.Add(k[i], 0);
            }
            for(int i = 0; i < n; i++)
            {
                var m = messages[i].Split(' ');
                d[senders[i]] += m.Length;
            }

            int max = -1;
            var res = "";
            foreach (KeyValuePair<string,int> en in d)
            {
                if(max < en.Value)
                {
                    max = en.Value;
                    res = en.Key;
                }
                else if( max == en.Value)
                {
                    if (res.CompareTo(en.Key) < 0) res = en.Key;
                }
            }
            
            Console.WriteLine(max);
            return res;
    }
}
```

#### Screenshots

![image](https://user-images.githubusercontent.com/80607687/170835128-5a170af3-8c2f-4802-a017-0147d98fa708.png)
![image](https://user-images.githubusercontent.com/80607687/170835131-2f4ab6fe-9b0a-4df9-9092-3a000d2186d7.png)
![image](https://user-images.githubusercontent.com/80607687/170835190-9688f6b5-12bc-404d-83a4-563cbbb22841.png)
![image](https://user-images.githubusercontent.com/80607687/170835202-a305550e-446c-4604-85d4-eb86e1f307b5.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

What is the test case?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by anau99** [comment]
Hi, the test case is wrong. I had sent email on Saturday on last week. i
enjoy Biweekly Contest 79. Detail view on below, please:
[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]

I had been checked on my Vstuio then :

string x = "YMQDBkOWy";

            string y = "ubIEXAO";



            Console.WriteLine(x.CompareTo(y));



Output 1 >0  => res = YMQDBkOWy

*they have the same maximum value of 22, which is required by the question
to return a lexical larger string => my result = "*YMQDBkOWy" but result of
the test case as ""ubIEXAO"
I do not know ??
*Would do you like consider the case to me ?*

*Thank you*

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
