### ISSUE TITLE
Missing Test Case - 1566. Detect Pattern of Length M Repeated K or More Times

### ISSUE THREAD

**Issue by girishkumaral** [LeetCode-Feedback/LeetCode-Feedback#7477]
#### Your LeetCode username
kgirish

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [Yes ] Missing Test Cases 

[1,2,1,3,1,1,1,2]
2
2

#### Description of the bug
For below test case the expected answer should be true.
pattern "12" appears twice. But leetcode submission is saying false

#### Code you used for Submit/Run operation

```
class Solution:
    def containsPattern(self, arr: List[int], m: int, k: int) -> bool:
        cache = defaultdict(lambda: list())
        i = 0
        j = 0
        while i < len(arr):
            while j < len(arr) and j < i + m:
                j += 1            
            if not cache[str(arr[i:j])] or cache[str(arr[i:j])][-1][1] < i:
                cache[str(arr[i:j])].append((i, j-1))
                if len(cache[str(arr[i:j])]) == k:
                    print(cache[str(arr[i:j])])
                    return True
            i += 1
```

**Comment by stormsunshine** [comment]
The problem description contains "consecutively". Please read carefully.
