### ISSUE TITLE
2288. Apply Discount to Prices   Wrong description

### ISSUE THREAD

**Issue by royamjj** [LeetCode-Feedback/LeetCode-Feedback#7483]
#### Your LeetCode username

DarkSeid_

#### Category of the bug
- [ .] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Wrong description 
Given that price will also be considered if we have '.' in it in explanation but in constraints it's given that string will only contain '$' and ' '

For example, "$100", "$23", and "$6.75" represent prices while "100", "$", and "2$3" do not.

sentence consists of lowercase English letters, digits, ' ', and '$'.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context
![Annotation 2022-05-29 094027](https://user-images.githubusercontent.com/87959809/170851813-7a6e29ba-909f-44b7-9fa4-f2c54f3f200c.png)

![Anno](https://user-images.githubusercontent.com/87959809/170851819-dda3a126-5851-4c00-9b0a-0d5785fe5e75.png)

**Comment by harshitkd** [comment]
I think there is nothing wrong, I tried to solve it and it does not give me any error.
Take a look at my code:

        s = sentence.split(" ")
        res = []
        
        for i in s:
            if i[0] == '$' and len(i) > 1 and i.count('$') == 1 and i[1:].isnumeric():
                x = int(i[1:])
                x = x - x * discount/100 
                res.append(i[0] + str(format(x,".2f")))
            else:
                res.append(i)
                
        return " ".join(res)

**Comment by stormsunshine** [comment]
One constraint is as follows.

> All prices will be **positive** integers without leading zeros.

Therefore, no characters `'.'` are in `sentence`.

**Comment by royamjj** [comment]
> I think there is nothing wrong, I tried to solve it and it does not give me any error. Take a look at my code:
> 
> ```
>     s = sentence.split(" ")
>     res = []
>     
>     for i in s:
>         if i[0] == '$' and len(i) > 1 and i.count('$') == 1 and i[1:].isnumeric():
>             x = int(i[1:])
>             x = x - x * discount/100 
>             res.append(i[0] + str(format(x,".2f")))
>         else:
>             res.append(i)
>             
>     return " ".join(res)
> ```
i am not saying that i am saying is that description is wrong

**Comment by royamjj** [comment]
> One constraint is as follows.
> 
> > All prices will be **positive** integers without leading zeros.
> 
> Therefore, no characters `'.'` are in `sentence`.

Please make a correction in description

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
