### ISSUE TITLE
2289. Steps to Make Array Non-decreasing -- wrong hints?

### ISSUE THREAD

**Issue by DolphinsAtDaybreak** [LeetCode-Feedback/LeetCode-Feedback#7487]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hint 3 states:

Consider an element at index i. Say there exists a strictly greater element to its left, and the closest one is located at index j (i.e. there is no index k such that j < k < i and nums[k] > nums[i]). The number of rounds required to remove nums[i] is i - j.

This seems wrong.  As an example, if we have an array [6,5,4,3,2,1,5] -- it would take 2 rounds to remove the 5, not i-j=6 rounds.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Changed the hints. We appreciate your support!

**Comment by DolphinsAtDaybreak** [comment]
Great, glad it's sorted out!

BTW, shouldn't I get some leetcoin points? ))
