### ISSUE TITLE
Missing Test Case - 2286. Booking Concert Tickets in Groups

### ISSUE THREAD

**Issue by Yawn-Sean** [LeetCode-Feedback/LeetCode-Feedback#7489]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
小羊肖恩（Yawn_Sean）

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
该题的gather方法与scatter方法出现复杂度不正确通过的情形，试添加边界条件
对于方法scatter试通过该样例hack：
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8792822/1.txt)
[1_1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8792836/1_1.txt)
（属于情况退化到O(nq)）

对于方法gather试通过该样例hack：
[2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8792816/2.txt)
[2_1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8792833/2_1.txt)
（也属于后续情况退化到O(nq)）

**被hack者使用的语言**

JavaScript

**被hack者提交或者运行的代码（不超时，但建议添加该样例与其他样例混合使用）**
```
/**
 * @param {number} n
 * @param {number} m
 */
var BookMyShow = function (n, m) {
  this.arr = new Array(n).fill(0);
  this.n = n;
  this.m = m;
};

/**
 * @param {number} k
 * @param {number} maxRow
 * @return {number[]}
 */
BookMyShow.prototype.gather = function (k, maxRow) {
  let max = Math.min(maxRow, this.arr.length - 1);
  for (let i = 0; i <= max; i++) {
    if (this.m - this.arr[i] >= k) {
      this.arr[i] += k;
      return [i, this.arr[i] - k];
    }
  }
  return [];
};

/**
 * @param {number} k
 * @param {number} maxRow
 * @return {boolean}
 */
BookMyShow.prototype.scatter = function (k, maxRow) {
  let leftSum = 0;
  let max = Math.min(maxRow, this.arr.length - 1);
  for (let i = 0; i <= max; i++) {
    leftSum += this.m - this.arr[i];
  }
  if (leftSum < k) return false;

  for (let i = 0; i <= max; i++) {
    if (k >= this.m - this.arr[i]) {
      k -= this.m - this.arr[i];
      this.arr[i] = this.m;
    } else {
      this.arr[i] += k;
      return true;
    }
  }
  return true;
};
```

**期望行为**
大致用时可以达到2000+ms/样例，多添加类似样例，可以解决复杂度不正确仍通过的解

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：不处理，已有类似用例添加。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
