### ISSUE TITLE
520. Detect Capital

### ISSUE THREAD

**Issue by sagartoms** [LeetCode-Feedback/LeetCode-Feedback#749]
#### Your LeetCode username

sagartoms

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The question clearly says about upper or lowercase characters, but didn't mention about numbers. For the screenshot given, my answer is false but the expected answer is true. However the solution got accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def detectCapitalUse(self, word: str) -> bool:
        u = 0
        l = 0
        n = 0
        for c in word:
            if c.isupper():
                u += 1
            elif c.islower():
                l += 1
            else:
                n += 1
        if len(word) == u or len(word) == l:
            return True
        elif u == 1 and l == len(word) - 1 and word[0].isupper():
            return True
        else:
            return False
```

#### Language used for code

Python3

#### Expected behavior

The question clearly says about upper or lowecase charactes, but didn't mention about numbers.

Eg: i) For the input "A1A", expected answer is 'false'.
ii) For the input "A1", my answer is 'false' and expected answer is 'true'. Howerver, the solution got accepted.

Does this mean, some additional information about numeric values should be added in question or this should be considered as an invalid testcase ? If this is an invalid testcase, Leetcode should throw Invalid Testcase message as in other problems.

#### Screenshots

![image](https://user-images.githubusercontent.com/3920353/89107223-0df5bc00-d44d-11ea-8d3e-3000cdad02b9.png)

**Comment by lc-ivan** [comment]
Hi @sagartoms ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @sagartoms ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
