### ISSUE TITLE
Misspelling in description - 696. Count Binary Substrings

### ISSUE THREAD

**Issue by aewhenm** [LeetCode-Feedback/LeetCode-Feedback#7495]
#### Your LeetCode username

aewhenm

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a minor misspelling in the description of the problem.
Actual description: _Give a binary string s..._

#### Expected behavior

Should be: _**Given** a binary string s..._

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
