### ISSUE TITLE
Missing Test Case - 2288. Apply Discount to Prices

### ISSUE THREAD

**Issue by denis-gubar** [LeetCode-Feedback/LeetCode-Feedback#7496]
#### Your LeetCode username

DenisGubar

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

1. Either incorrect problem statement or missed test case what to treat real number

Test case:

"test $1e5"
10
Expected answer is "test $1e5" and not "test $90000.00"

2.  Bad problem statement
```
For example, "$100", "$23", and "$6.75" represent prices while "100", "$", and "2$3" do not.
...
sentence consists of lowercase English letters, digits, ' ', and '$'.
```
Value "$6.75" contains forbidden character '.'
That was unclear should be non integer float values supported

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<string> split(const string& s, char delimeter = ' ')
    {
        vector<string> result;
        istringstream ss(s);
        for (string token; !ss.eof(); )
        {
            getline(ss, token, delimeter);
            result.push_back(token);
        }
        return result;
    }
    string discountPrices(string sentence, int discount) {
        string result;
        vector<string> S = split(sentence);
        int N = S.size();
        for (int i = 0; i < N; ++i)
        {
            bool is$ = false;
            string t = S[i];
            if (S[i][0] == '$')
            {
                t = t.substr(1);
                if (count(t.begin(), t.end(), '.') <= 1 && !t.empty())
                {
                    is$ = true;
                    for (char c : t)
                        is$ &= (c == '.' || isdigit(c));
                    if (is$)
                    {
                        long long x = stod(t) * (100 - discount) * 2 + 1;
                        x /= 2;
                        t = to_string(x / 100) + '.' + to_string(x % 100 + 100).substr(1);
                    }
                }         
            }
            if (!result.empty())
                result += ' ';
            if (!is$)
            {
                result += S[i];
            }
            else
            {
                result += '$';
                result += t;
            }
        }
        return result;
    }
};

```

#### Language used for code

C++

#### Additional context

It does affect [Weekly contest 295](https://leetcode.com/contest/weekly-contest-295)

**Comment by 981377660LMT** [comment]
>"test $1e5"
10
Expected answer is "test $1e5" and not "test $90000.00"

For my opinion,such type of test case is controversial and **should not** be added to the test case.
**1e5 is a positive integer In some languages** (e.g.,**javascript**)

![image](https://user-images.githubusercontent.com/45849137/170866473-3a530fdc-bf5d-43c1-8926-42259dbf99e8.png)

**Comment by denis-gubar** [comment]
Problem statement related to this case must be explicit. It's absolutely unacceptable to avoid adding **"correct"** case.
1. This is a medium not an easy problem. Problem statement can suggest to avoid using built-in functions. I want to highlight that if dot issue in example is resolved manual **integer** number format checking is a good subtask for this problem.
2. Completely rewrite problem statement to make it clear that such case cannot exist. Basic solution - exclude "eE" letters from allowed characters.

Anyway I see no reason to leave current problem statement as is. We have to resolve this issue and confusing "$6.75" example with forbidden dot character.

**Comment by 981377660LMT** [comment]
> Problem statement related to this case must be explicit. It's absolutely unacceptable to avoid adding **"correct"** case.
> 
> 1. This is a medium not an easy problem. Problem statement can suggest to avoid using built-in functions. I want to highlight that if dot issue in example is resolved manual **integer** number format checking is a good subtask for this problem.
> 2. Completely rewrite problem statement to make it clear that such case cannot exist. Basic solution - exclude "eE" letters from allowed characters.
> 
> Anyway I see no reason to leave current problem statement as is. We have to resolve this issue and confusing "$6.75" example with forbidden dot character.

Fully agree to `write problem statement to make it clear`. Current problem statement is kindof confusing.
It is not interesting to deal with above corner case cautiously.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed the second issue to our team to investigate.
The output for the test case is
"test $1e5"!

[Screen Shot 2022-05-30 at 2 16 21 PM](https://user-images.githubusercontent.com/103138242/171043552-ca9b346a-0bd0-4db4-ae5f-c5d77421ac7b.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
