### ISSUE TITLE
Incorrect return value - 2131. Longest Palindrome by Concatenating Two Letter Words

### ISSUE THREAD

**Issue by shivavishaal66215** [LeetCode-Feedback/LeetCode-Feedback#7498]
#### Your LeetCode username
vishaal66215

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Program returns wrong result

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int longestPalindrome(vector<string>& arr) {
        int i,j,k,n;
        string temp,s;
        int cur = 0;
        n = arr.size();
        
        int result = 0;
        
        unordered_map<string, int> f;
        for(auto it1: arr){
            f[it1] += 1;
        }
        
        for(auto it=f.begin();it!=f.end();it++){
            s = it->first;

            if(s[0] == s[1]){
                cur = it->second / 2;
                result += 4 * cur;
                
                it->second -= 2 * cur;
            }
            else{
                temp = "";
                temp += s[1];
                temp += s[0];
                
                cur = min(it->second, f[temp]);
                result += 4 * cur;
                
                it->second -= cur;
                f[temp] -= cur;
            }
            
            // cout << s << " " << result << endl;
        }
        for(auto it=f.begin();it!=f.end();it++){
            s = it->first;
            if(s[0] == s[1] && it->second == 1){
                result += 2;
                break;
            }
        }

        
        return result;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
The submitted code should return the value 102 for the following test case
["oo","vv","uu","gg","pp","ff","ss","yy","vv","cc","rr","ig","jj","uu","ig","gb","zz","xx","ff","bb","ii","dd","ii","ee","mm","qq","ig","ww","ss","tt","vv","oo","ww","ss","bi","ff","gg","bi","jj","ee","gb","qq","bg","nn","vv","oo","bb","pp","ww","qq","mm","ee","tt","hh","ss","tt","ee","gi","ig","uu","ff","zz","ii","ff","ss","gi","yy","gb","mm","pp","uu","kk","jj","ee"]

But the code is returning 14.
#### Screenshots
![image](https://user-images.githubusercontent.com/70514208/170866425-cf131990-7180-4711-9a2d-4e0b1cbe52d5.png)

#### Additional context
I get the correct result (102) when I run the code locally with the above test case. 
![image](https://user-images.githubusercontent.com/70514208/170866469-fbe87e4b-6110-4b9f-a633-7fff13eb5285.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
