### ISSUE TITLE
2290. Minimum Obstacle Removal to Reach Corner - Exact same code gives AC after contest but TLE during contest

### ISSUE THREAD

**Issue by tulkasm** [LeetCode-Feedback/LeetCode-Feedback#7499]
#### Your LeetCode username
tulkasm https://leetcode.com/tulkasm/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Exact same code gives AC when I run after the contest, but TLE during the contest.

#### Code you used for Submit/Run operation
After contest: https://leetcode.com/submissions/detail/709796739/
During contest: https://leetcode.com/contest/weekly-contest-295/submissions/detail/709487375/
The code is the exact same.

#### Language used for code
Python3

#### Expected behavior

The submission during contest should be accepted, not TLE. I would like to kindly ask for it to be rejudged. Thank you for organizing the contests.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by tulkasm** [comment]
Hi! Seems like this wasn't rejudged. Was it rerun and still TLE? It passes for me every time when I run it, should I keep something in mind about the contest environment for next contests?

Thanks.

**Comment by LC-Pam** [comment]
Hi there, 

Thank you for your patient. We already submitted this issue to our develop team to investigate. Please allow more days. Thank you.

**Comment by LC-Pam** [comment]
Response through email.
