### ISSUE TITLE
Problem 1246, 预期输出结果出问题

### ISSUE THREAD

**Issue by lih627** [LeetCode-Feedback/LeetCode-Feedback#75]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目 1246, 看评论发现的问题:
对于测试数据 [1, 4, 1, 1, 2, 3, 2, 1]
预期输出结果显示是 3
应该是 2, 即 [1, 4, 1], [1, 2, 3, 2, 1]

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
fixed

**Comment by feiceh** [comment]
您好，该问题已修复，请稍后刷新网页再试试。
