### ISSUE TITLE
Bug in Today's challenge question- 520. Detect Capital

### ISSUE THREAD

**Issue by sailikhithk** [LeetCode-Feedback/LeetCode-Feedback#750]
#### Your LeetCode username

sailikhithk

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The question is about capital letters. So, its understandable that all small letters and other special characters or numbers are rejected. But while submitting solution with a special case of combination of the numbers and letters, its showing expected and my output are different but overall my code is accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def detectCapitalUse(self, word: str) -> bool:  
        uppers = 0
        lowers = 0
        other = 0
        #words needed to be scanned
        for i in word:
            if i.isupper(): #check whether this is upper or not?
                uppers += 1
            elif i.islower(): #check whether this is lower or not
                lowers += 1 
            else:
                other += 1 #any other characters or special characters 
                
        if len(word) == uppers or len(word) == lowers: #first case where all letters are either fully capital or fully small
            return True
        
        elif uppers == 1: #if first letter is capital
            if word[0].isupper(): #check if its capital
                if lowers == len(word) - 1: #checking if remaining all are small 
                    return True
        else: #rest everything is false
            return False


```

#### Language used for code

Python3

#### Expected behaviour

**I had given input B5a**
Expected is it should throw an output that it is false as it cant consider number as the small letters. My program gives it as False which is correct. But Leetcode is showing that **Expected is true**

According to rules, **True is expected only if:**
1. All letters should be either capital or small
2. If fist letter is capital and all others are small

**B5a has other characters which have not been met. like numbers. In this case, output should be false since second character is neither number nor small**

#### Screenshots

![image](https://user-images.githubusercontent.com/32040901/89115338-4d280b00-d455-11ea-8714-ae3390413dc4.png)

#### Additional context

One thing I would say is that question should be given clearly stating numbers are ignored or pushed to false and also the solution expected cases involving numbers needed to be seen.

**Comment by lc-ivan** [comment]
Hi @sailikhithk ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by sailikhithk** [comment]
Thanks for taking it. Yeah, Please correct this.

**Comment by lc-ivan** [comment]
Hi @sailikhithk ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
