### ISSUE TITLE
Missing Test Case: 2288. Apply Discount to Prices

### ISSUE THREAD

**Issue by bogoconic1** [LeetCode-Feedback/LeetCode-Feedback#7501]
#### Your LeetCode username
bogoconic1

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

 A solution that can get accepted fails on a specific test case

The test case is as follows

```
"$1e9"
50
```

#### Code you used for Submit/Run operation

```
class Solution:
    def is_float(self, num):
        try:
            float(num)
            return True
        except ValueError:
            return False
        
    def is_price(self, word):
        return word.startswith("$") and self.is_float(word[1:])
    
    def apply_discount(self, word, discount):
        val = float(word[1:])
        new_val = val - (val * (discount/100.00))
        return f"${new_val:.2f}"
    
    def discountPrices(self, sentence: str, discount: int) -> str:
        word_list = sentence.split(" ")
        res = ""
        for word in word_list:
            if self.is_price(word):
                word = self.apply_discount(word, discount)
                
            res += f"{word} "
    
                         
        return res.rstrip()
```

#### Language used for code

Python3

#### Expected behavior

Expected Output: "$1e9"
Code output: "$500000000.00"

#### Screenshots

![image](https://user-images.githubusercontent.com/100673850/170873913-5c36c2ed-af2e-4b54-815b-12af984d08e5.png)

#### Additional context

After adding this test case, the code should give wrong answer

**Comment by stormsunshine** [comment]
The test case should be as follows.

```
"$1e9"
50
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
