### ISSUE TITLE
Two testcases are showing as same

### ISSUE THREAD

**Issue by 17rashi** [LeetCode-Feedback/LeetCode-Feedback#7506]
s_rashi76

#### Category of the bug
- [ x] Question : 523. Continuous Subarray Sum
- [ x] wrong test cases. 

#### Description of the bug
Test cases 84/95 are showing as same when I submit the solution twice.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkSubarraySum(vector<int>& nums, int k) {
        unordered_map<int, int> mp;
        int curr=0;
        for(int i=0;i<nums.size();i++){
            curr+=nums[i];
            if(curr%k==0 && i>=1){
                return true;
            }
            if(mp.find(curr-k)!=mp.end() || (i<nums.size()-1 && nums[i]==0 && nums[i+1]==0)){
                return true;
            }
        }
        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I have submitted the same question twice and it is showing me the wrong output. that's ok my solution was not correct. but there was some miss behavior in the test cases. 

#### Screenshots
![image](https://user-images.githubusercontent.com/87816619/170885719-6da8fcc0-9384-468d-ad49-f4523ed1983e.png)
![image](https://user-images.githubusercontent.com/87816619/170885733-f5819343-b07c-461e-9ad2-c8b4e8ed5669.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
