### ISSUE TITLE
Missing Test Case - 1407. Top Travellers

### ISSUE THREAD

**Issue by sushma-biswas** [LeetCode-Feedback/LeetCode-Feedback#7509]
#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

_Users_ table has _id_ as the primary key. There can be users with different ids but same name. Since none of the existing test cases cover this scenario, a 'GROUP BY' on the name field will also pass all existing test cases. Ideally, the grouping should be done on the primary key (id) in this case to avoid this issue.

#### Code you used for Submit/Run operation

```
select 
    name, 
    coalesce(sum(distance), 0) as travelled_distance
from Users u
left join Rides r 
    on r.user_id = u.id
group by name
order by 2 desc, 1 asc
```

#### Language used for code
MS SQL Server

#### Expected behavior

Here is the test case we can use to test this:
{"headers":{"Users":["id","name"],"Rides":["id","user_id","distance"]},"rows":{"Users":[**[1,"Alice"],**[2,"Bob"],[3,"Alex"],**[19,"Alice"]**],"Rides":[**[1,1,120]**,[2,2,317],[3,3,222],[4,7,100],[5,13,312],[9,7,230]]}}

This test case should have returned the following as output, since there are two different users with the name 'Alice':
{"headers": ["name", "travelled_distance"], "values": [["Bob", 317], ["Alex", 222], **["Alice", 120], ["Alice", 0]]**}

Instead, it combines the values for 'Alice' and returns the following:
{"headers": ["name", "travelled_distance"], "values": [["Bob", 317], ["Alex", 222], **["Alice", 120]]**}

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by StephanieYeleiYang** [comment]
still not solve
