### ISSUE TITLE
935. Knight Dialer Problem Description is Wrong

### ISSUE THREAD

**Issue by santanu33** [LeetCode-Feedback/LeetCode-Feedback#751]
#### Your LeetCode username
santanu_33

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The description says, 
>  This time, we place our chess knight on any numbered key of a phone pad (indicated above), and the knight makes N-1 hops.  Each hop must be from one key to another numbered key.

The description is wrong, it is actually placing the knight in all keys in the keypad. 

#### Expected behavior

the ideal description would be

This time, we place our chess knight on ~~any numbered key~~ all numbered key of a phone pad (indicated above), and the knight makes N-1 hops.  Each hop must be from one key to another numbered key.

**Comment by lc-ivan** [comment]
Hi @santanu33 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @santanu33 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
