### ISSUE TITLE
Incorrect Test Case - 2289. Steps to Make Array Non-decreasing

### ISSUE THREAD

**Issue by Rakesh-Bairwa** [LeetCode-Feedback/LeetCode-Feedback#7510]
#### Your LeetCode username

alex_212

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Incorrect test-case

#### Language used for code

C++

#### Expected behavior

Test case: [7,14,4,14,13,2,6,13]
step1: [7,14,14,2,6,13], (14 removed 4) & (next 14 removed 13)
step2: [7,14,14,6,13], (14 removed 2)
step3: [7,14,14,13], (14 removed 6)
step4: [7,14,14], (14 removed 13)

So it clearly took 4 steps to make the array non-decreasing whereas the answer is 3.

#### Screenshots

![ss](https://user-images.githubusercontent.com/65413333/170927176-63af0589-7f9a-4bfb-8aed-0eb76caac7b1.png)
**Ignore my output

**Comment by stormsunshine** [comment]
The element 2 is removed in step 1, so the number of steps needed is 3. Is there any problem?

**Comment by Rakesh-Bairwa** [comment]
I had iterated from the 0th index & as I can see 14 will remove 13. And after the removal of 13. How will 2 will removed in 1st step? 
Even the question didn't state to return minimum no. Of steps so that I write the redundant solution that everyone is posting. My point is before (13 remove 2), 13 will be removed by 14. And following that iteration, the next comparison will go to be between 2&6 who are already non&-decreasing.
If you say 2 will be removed by 13, don't you think 13 will be removed by 14 before? 
I hope I made my point 
Thank you
(And sorry if I said anything wrong or sounds rude)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment]
@Rakesh-Bairwa The remove operations are done simultaneously in each step. For the example you provided, the elements 4, the first 13 and 2 are removed in the first step. Even if the first 13 is removed, 2 is also removed since 2 < 13.

Example 1 in problem description also indicates this point. The last four elements are 11, 8, 5 ane 1. Since 8 < 11 and 5 < 8, both 8 and 5 are removed in the first step.

**If you have read the example and the explanation carefully, you won't ask this question.**

> I had iterated from the 0th index & as I can see 14 will remove 13. And after the removal of 13. How will 2 will removed in 1st step? Even the question didn't state to return minimum no. Of steps so that I write the redundant solution that everyone is posting. My point is before (13 remove 2), 13 will be removed by 14. And following that iteration, the next comparison will go to be between 2&6 who are already non&-decreasing. If you say 2 will be removed by 13, don't you think 13 will be removed by 14 before? I hope I made my point Thank you (And sorry if I said anything wrong or sounds rude)
