### ISSUE TITLE
Missing Test Case - 318. Maximum Product of Word Lengths

### ISSUE THREAD

**Issue by mdcse** [LeetCode-Feedback/LeetCode-Feedback#7511]
#### Your LeetCode username
mdcse 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
 The Constraints is  : 
2 <= words.length <= 1000
1 <= words[i].length <= 1000
words[i] consists only of lowercase English letters.
But my code which has been accepted by "318. Maximum Product of Word Lengths"  is giving **TLE** on the input in given constraints.

#### Code you used for Submit/Run operation

```
// 318. Maximum Product of Word Lengths
class Solution {
   
private:
    bool iscommon(string s1, string s2)
    {
       int a[26]={0}, b[26]={0};
        for(int i=0; i<s1.size(); i++)
        {
            a[s1[i] - 'a']++; 
        }
        for(int i=0; i<s2.size(); i++)
        {
            b[s2[i] - 'a'] ++; 
        }
        for(int i=0; i<26; i++)
        {
            if(a[i] != 0 && b[i] != 0)return false;
        }
        return true;
    }
public:
    int maxProduct(vector<string>& words)
    {
        int mx = 0;
        for(int i=0; i<words.size(); i++)
        {
            for(int j =i+1; j<words.size(); j++)
            {
                if(iscommon(words[i], words[j]))
                {
                    mx = max(mx, (int)words[i].size() * (int)words[j].size());
                }
            }
        }
        return mx;
    }
    
};
```

#### Language used for code
 C++ 

#### Expected behavior
According to constraints  this code should not be accepted. 
Here is the test case we can use to test this:
[input_318.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8795957/input_318.txt)

this code is giving TLE but it has been accepted.

#### Screenshots

<img width="1426" alt="leetcode_318" src="https://user-images.githubusercontent.com/88222476/170929612-1631bbc4-b233-4322-bdb3-95b02b47464d.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
