### ISSUE TITLE
2289. Steps to Make Array Non-decreasing, Hint 3 is wrong.

### ISSUE THREAD

**Issue by SauravKumarJhaNITW** [LeetCode-Feedback/LeetCode-Feedback#7515]
#### Category of the bug
- [x] Hint

#### Description of the bug

Hint 3 is wrong.
An example test case where it won't work is  [8,7,3,2,6] . 
According to hint 3 which says `The number of rounds required to remove nums[i] is i - j`. number of rounds required to remove 6 in above array would be 4-1 = 3.
But following the simulation:
[8, ~7~, ~3~, ~2~, 6] 
[8, ~6~]
It takes only two rounds to remove 6.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Changed the hints. We appreciate your support!
