### ISSUE TITLE
TypeScript 题目内置 Node 类误识别为 Node API

### ISSUE THREAD

**Issue by curly210102** [LeetCode-Feedback/LeetCode-Feedback#7517]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
curly_brackets

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
[590. N 叉树的后序遍历](https://leetcode.cn/problems/n-ary-tree-postorder-traversal/) 题目预置的 Node 类和 DOM API 中的 Node 类型重名，导致 TS 认为 `node.children` 不符合类型规范

**你使用的语言**
TypeScript

**你提交或者运行的代码**
```
function postorder(root: Node | null): number[] {
    const stack = [root];
    while (stack.length) {
         const node = stack[stack.length - 1];
         if (node.children) {

         }
    }
};
```

**期望行为**
题目内置的 Node 类能够使用，或许编辑器中不需要出现 DOM 类型支持

**屏幕截图**
<img width="738" alt="Screen Shot 2022-05-30 at 23 42 50" src="https://user-images.githubusercontent.com/76864176/171026287-77fef4d6-e4a0-49fc-88e5-fc162158488b.png">

**额外的上下文**
选择 TypeScript 语言，函数中输入 `root.children` 即可出现错误提示

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by BrambleWave** [comment]
在编写代码过程中会有红色波浪线显示错误，实际不影响代码执行的结果。
