### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by cvishu** [LeetCode-Feedback/LeetCode-Feedback#7518]
vishucc 

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

The Input which is accepted in TestCase is not accepted when submitted the same code. Please refer screenshot.

#### Code you used for Submit/Run operation
'''
// 7. Reverse Integer
class Solution {
    static int sum = 0;
    public int reverse(int x) {
        if(x <= Integer.MIN_VALUE || x >= Integer.MAX_VALUE){
            return 0;
        }
      if(x==0){
            return x;
        }
        sum = sum*10 + x%10;
        reverse(x/10);
        return sum;  
    }
}
'''

java Language used for code

#### Expected behavior
 If Input is accepted during test run,the same Input for same code must be correct after submitting also.

![image](https://user-images.githubusercontent.com/101501340/171028164-24a0f1f9-9984-4b42-b063-8a96e9588f1e.png)
Screenshots

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
