### ISSUE TITLE
Python 3 runtime engine fails to import module, while editor autocompletion - does not

### ISSUE THREAD

**Issue by geandbe** [LeetCode-Feedback/LeetCode-Feedback#752]
#### Your LeetCode username
geandbe

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Python 3 runtime engine fails to import Python 3 module <more_itertools> 

#### Code you used for Submit/Run operation

```
# Problem 1502 - Can Make Arithmetic Progression From Sequence
import more_itertools

class Solution:
    def canMakeArithmeticProgression(self, arr: List[int]) -> bool:
        return (diffs := list(operator.sub(*t) for t in more_itertools.windowed(sorted(arr), 2))).count(diffs[0]) == len(diffs)
```

#### Language used for code
Python 3

#### Expected behavior
I expect the runtime engine imports <more_itertools> module, just like Autocompletion feature of LeetCode editor does, and evaluates the solution.

Instead, the engine throws <ModuleNotFoundError: No module named 'more_itertools'>

#### Screenshots
Autocompletion feature does not have problem with importing <more_itertools> module:

![image](https://user-images.githubusercontent.com/1093863/89119940-00a5f500-d480-11ea-8199-4431b12cc92f.png)

Runtime throws an exception:

![image](https://user-images.githubusercontent.com/1093863/89119974-46fb5400-d480-11ea-8f6c-a003ab766233.png)

**Comment by lc-pam** [comment]
Hi @geandbe 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @geandbe ,

Thank you for your time. We currently don't support more_itertools so we've removed it from the autocompletion.
