### ISSUE TITLE
392 - Typo in solution description

### ISSUE THREAD

**Issue by araslanov** [LeetCode-Feedback/LeetCode-Feedback#7522]
#### Your LeetCode username
wizeek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the solution description for Approach #4, the first sentence ends with `which is also known as Levenshtein disance` (typo in `disance`).

#### Expected behavior
It should be `which is also known as Levenshtein distance`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
