### ISSUE TITLE
118. Pascal's Triangle Test Case Bug

### ISSUE THREAD

**Issue by ErtugrulEryildiz** [LeetCode-Feedback/LeetCode-Feedback#7523]
#### Your LeetCode username

ertugruleryldz

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A test case seems to fail when I submit my solution, but when I run the exact same test case via Run Code, it passes.

#### Code you used for Submit/Run operation

```
class Solution:
    factorial_map = [None]
    
    def my_factorial(self, value: int) -> int:
        if value < 2:
            return 1
        if self.factorial_map[value]:
            return self.factorial_map[value]
        
        self.factorial_map[value] = value * self.my_factorial(value - 1)
        return self.factorial_map[value]
    
    
    def my_choose(self, choose_from, choose_amount):
        return int(self.my_factorial(choose_from) / (self.my_factorial(choose_amount) * self.my_factorial(choose_from - choose_amount)))
        
    
    def generate_single_row(self, amount: int) -> List[int]:
        return [self.my_choose(amount, i) for i in range(amount + 1)]
        
    
    def generate(self, numRows: int) -> List[List[int]]:
        self.factorial_map *= (numRows + 1) 
        return [self.generate_single_row(i) for i in range(numRows)]
```

#### Language used for code

Python3

#### Expected behavior

When test case of 9 tested, it says expected outcome doesn't match to output. But when same test case is run via run code it spits expected outcome.

#### Screenshots

<img width="1512" alt="Screen Shot 2022-05-30 at 3 57 45 PM" src="https://user-images.githubusercontent.com/60051584/171053326-3b732760-5c47-4bbd-8446-2af20926b84d.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
