### ISSUE TITLE
C++20 support for C++ submissions

### ISSUE THREAD

**Issue by jaisw7** [LeetCode-Feedback/LeetCode-Feedback#7524]
#### Your LeetCode username
jaisw7

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
C++20 has some great features like ranges (https://en.cppreference.com/w/cpp/compiler_support#cpp20). It would be great if LC admins can enable c++20 for c++ submissions. Note that `gcc-11` supports “almost all” of the C++20 features (FYI: `gcc-12` has been already released, and `gcc-13` is expected to be released in next few months)

#### Code you used for Submit/Run operation
```c++
#include <iostream>
#include <ranges>
 
int main() {
    auto even = [](int i) { return 0 == i % 2; };
    auto square = [](int i) { return i * i; };
 
    for (int i : std::ranges::iota_view{1, 10})
        std::cout << i << ' ';
    std::cout << '\n';
 
    for (int i : std::views::iota(0, 6) 
               | std::views::filter(even) 
               | std::views::transform(square)) {
        std::cout << i << ' ';
    }
}
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted  your feedback to the team. We appreciate your support!

**Comment by rdong8** [comment]
We're now nearing the release of C++23, can we get any updates on this?

**Comment by ilkunviktor** [comment]
2024. can't use ranges::to<std::vector<std::pair<const int, int>>>();
