### ISSUE TITLE
659 desc split-array-into

### ISSUE THREAD

**Issue by henryhkim** [LeetCode-Feedback/LeetCode-Feedback#7527]
#### Your LeetCode username
henry26

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
DESCR
into one or more subsequences 

-> ought to say two or more

https://leetcode.com/problems/split-array-into-consecutive-subsequences/

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!

**Comment by henryhkim** [comment]
Please let team know that the problem is asking for splitting into 2 or 3 or more subsequences.
Of course it can be split to 1 subsequence , which would be the original string.

```Determine if it is possible to split nums into one or more subsequences```

The PROOF is in the problem description:  Notices the Plural "consecutive increasing subsequences".

```
Example 3:

Input: nums = [1,2,3,4,4,5]
Output: false
Explanation: It is impossible to split nums into consecutive increasing subsequences of length 3 or more.

```
