### ISSUE TITLE
Fix input for example 2 for 566. Reshape the Matrix 

### ISSUE THREAD

**Issue by EmmanuelPineiro** [LeetCode-Feedback/LeetCode-Feedback#7528]
#### Your LeetCode username
PrettyFartMaster

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem [566. Reshape the Matrix](https://leetcode.com/problems/reshape-the-matrix/) Example 2  input needs to be updated to `c = 2` 

![image](https://user-images.githubusercontent.com/16860294/171080586-7183c185-313c-4a26-a05b-6d77908a3ad5.png)

#### Code you used for Submit/Run operation
```Java
class Solution {
  public int[][] matrixReshape(int[][] mat, int r, int c) {
    if (mat[0].length == r && mat.length == c)
    {
      return mat;
    }

    int[][] res = new int[r][c];
    
    int rRow = 0;
    int rCol = 0;
    
    for (int row = 0; row < mat.length; row++)
    {
      for (int col = 0; col < mat[row].length; col ++)
      {
        res[rRow][rCol] = mat[row][col];
        rCol = (rCol + 1) % c;
        if (rCol == 0)
        {
          rRow = (rRow + 1) % r;
        }
      }
    }
    
    return res;
  }
}
```

#### Language used for code
Java

#### Screenshots
![image](https://user-images.githubusercontent.com/16860294/171080225-1694c23f-4c95-41af-ab92-68204ae40803.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
