### ISSUE TITLE
Missing testcase - 1461. Check If a String Contains All Binary Codes of Size K

### ISSUE THREAD

**Issue by satzhan** [LeetCode-Feedback/LeetCode-Feedback#7529]
#### Your LeetCode username
Satj

#### Category of the bug
- [X] Missing Test Cases 

#### Description of the bug
Missing testcase

#### Code you used for Submit/Run operation

```
// 1461. Check If a String Contains All Binary Codes of Size K
class Solution {
public:
    bool hasAllCodes(string s, int k) {
        if (s.size() < k || k > 16) return 0;
        int n = (1 << k), mask = (n - 1);
        vector <bool> a(n, 0);
        int i = 0, cur = 0;
        while (i < k - 1) {
            cur = (cur << 1) | (s[i++] - '0');
        }
        int cnt = 0;
        while (i < s.size()) {
            cur = ((cur << 1) | (s[i++] - '0')) & mask;
            cnt += (a[cur] == 0);
            a[cur] = 1;
            if (cnt == n) 
                return 1;
        }
        return 0;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Should return True. My solution returns False. But Leetcode still accepts my solution.

#### Additional context

[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8802604/testcase.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
