### ISSUE TITLE
937. 重新排列日志文件,  内容描述不清楚

### ISSUE THREAD

**Issue by bytebeats** [LeetCode-Feedback/LeetCode-Feedback#753]
在题目[937. 重新排列日志文件](https://leetcode-cn.com/problems/reorder-data-in-log-files/)中, 在日志重排的规则描述当中, 第二条描述的内容十分混淆, 特别容易引起误解.
原谅内容是: **字母日志 在内容不同时，忽略标识符后，按内容字母顺序排序；在内容相同时，按标识符排序；**
而我根据提交的测试结果来看, 这个**内容**实质上指的是 **除却标识符之后的内容**
所以, 我觉着修改成如下描述, 更准确, 更加容易理解: 
**字母日志 在标识符之后的内容不同时，忽略标识符后，按标识符之后的内容字母顺序排序；在标识符之后的内容相同时，按标识符排序；**

**Comment by feiceh** [comment]
你好，当前更新了关于日志格式的定义，补充了「什么是日志的内容」：
对于每条日志，其第一个字为字母与数字混合的 标识符 ，除标识符之外的所有字为这一条日志的 内容 。
