### ISSUE TITLE
All O`one Data Structure

### ISSUE THREAD

**Issue by Faraj-Qdwry** [LeetCode-Feedback/LeetCode-Feedback#7531]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// The solustion
class AllOne() {
    
    private val map = mutableMapOf<String, Int>()

    fun inc(key: String) {
        map[key] = map.getOrDefault(key, 0) + 1
    }

    fun dec(key: String) {
        map[key] = map.getOrDefault(key, 1) - 1
    }

    fun getMaxKey(): String {
        return map.maxByOrNull { it.value }!!.key ?: ""
    }

    fun getMinKey(): String {
        return map.minByOrNull { it.value }!!.key ?: ""
    }

}
```

#### Language used for code
Kotlin

#### Screenshots

![Screenshot 2022-05-31 at 10 49 46](https://user-images.githubusercontent.com/23033063/171133143-0af627d2-e1b7-4867-892b-27499826a4c3.png)

#### Additional context
the solution works in my local machine

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
