### ISSUE TITLE
Missing Test Case - 39. Combination Sum

### ISSUE THREAD

**Issue by krishchopra02** [LeetCode-Feedback/LeetCode-Feedback#7534]
#### Your LeetCode username

krishchopra02

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My python3 solution for the Combination Sum problem gets accepted by the system, but when I was running a personal test case it gives a TLE error on the following test case:
candidates = [100,200,4,12]
target = 400

#### Code you used for Submit/Run operation

```
class Solution:
    def combinationSum(self, candidates: List[int], target: int) -> List[List[int]]:
        self.ans = []
        self.res = []
        self.helper(candidates,target) 
        return self.ans
    
    def helper(self,candidates:List[int],target:int)->None:
        
        ## base case
        if sum(self.res)>target:
            return
        if sum(self.res) == target:
            p = sorted(self.res)
            if p not in self.ans:
                self.ans.append(p)
            return
        ## Recursive case
        for i in range(len(candidates)):
            ## add element to ans 
            self.res.append(candidates[i])
            self.helper(candidates,target)
            self.res.pop()
```

#### Language used for code
Python3

#### Expected behavior

What should have happened : Solution should have been rejected 
What happened: Solution accepted but fails on a personal test case

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
