### ISSUE TITLE
Throw unexpected exception with Racket  26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by cafedood** [LeetCode-Feedback/LeetCode-Feedback#7535]
#### Category of the bug
- [ ] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

Throwing exception 

#### Code you used for Submit/Run operation

`Racket` code
```
// Two Sum
(define/contract (remove-duplicates nums)
  (-> (listof exact-integer?) exact-integer?)
    (print (exact-integer? 2)) 
    2
  )
```

#### Expected behavior

with Test case `[1,1,2]`, it should be `accepted`, but it got exception 
```
2 is not valid value for the expected return type integer[]
  context...:
   /usr/share/racket/collects/racket/private/more-scheme.rkt:163:2: select-handler/no-breaks
   solution.rkt:10:2
   body of (submod "solution.rkt" main)
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by cafedood** [comment]
Thank you for the response. The language is `Racket`

**Comment by cafedood** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The language you submitted to reach this result.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

`Racket`

**Comment by cafedood** [comment]
hello, any update of it? @LC-Pam

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, your code received Compile Error when we tested it, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
