### ISSUE TITLE
Solution Time complexity - 103. Binary Tree Zigzag Level Order Traversal

### ISSUE THREAD

**Issue by kiran-italiya** [LeetCode-Feedback/LeetCode-Feedback#7538]
#### Your LeetCode username
underpaid_engineer

#### Category of the bug
- Solution

#### Description of the bug
In the solution, `Approach 2: DFS (Depth-First Search)`, space complexity is confusingly mentioned as O(H) where H is height or no of levels of the tree.

#### Screenshots
![image](https://user-images.githubusercontent.com/33808376/171252869-f1fc7ec5-ed6a-4075-86b7-72d101163f8d.png)

#### Expected behavior
In worst case for DFS, if the tree is skewed in the sense that each level contains only one node then the worst case time complexity is O(N) where N is no of nodes in the tree.

For time/space complexities, we should use something that directly represents and correlates with input. Here N is no of nodes in the tree which directly represents the input quantity. Whereas H can be different for same value of N because of different tree structure. So this doesn't accurately depict input quantity.

So the space complexity for DFS based approach#2 should be O(N) instead of O(H).

Even though this seems minor wording issue, it creates lot of confusion for beginners.

#### FYI
The comment section also has lot of requests for this correction.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
