### ISSUE TITLE
15. 3Sum: Solution code does not match solution description

### ISSUE THREAD

**Issue by solamen2** [LeetCode-Feedback/LeetCode-Feedback#7539]
#### Your LeetCode username
ed_younskevicius

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem description says:

"Iterate through the array:
If the current value is greater than zero, break from the loop. Remaining values cannot sum to zero."

But in the solution code for Approaches 1 and 2, only the Python code actually does this check. The Java and C++ code do not do this check.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
The solution code for Java and C++ should add the check. It's simple, like this:

```java
    if (nums[i] > 0)
    {
        break;
    }
```

#### Screenshots
N/A

#### Additional context
It's silly for all three solutions in Approach 2 to call another function. Handing in an index variable for a for() loop to a function is not good programming practice. The function call can be easily inlined, and the code would be cleaner and more efficient.

**Comment by LC-Pam** [comment]
Thank you for sharing your concern. The break for Java and C++ is handled within the for loop which contains 2 conditions that must be met for the for loop to continue. See && nums[i] <= 0.
