### ISSUE TITLE
Missing test case in 665. Non-decreasing Array

### ISSUE THREAD

**Issue by nebhagat** [LeetCode-Feedback/LeetCode-Feedback#754]
#### Your LeetCode username
nehalbhagat29 

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

My [solution](https://leetcode.com/submissions/detail/375013067/) got accepted for [question](https://leetcode.com/problems/non-decreasing-array/). Where as my solution fails for the test cases 
`[1,2,3,2,2]`

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkPossibility(vector<int>& nums) 
    {
        int size = nums.size();
        int wrongElems = 0;
        
        for (int i=0; i<size-1; i++)
        {
            if (nums[i] > nums[i+1])
            {
                wrongElems++;
                
                if ((i-1 >= 0 && nums[i-1] < nums[i+1]) || i-1 < 0)
                {
                    nums[i] = nums[i+1];
                }
                else
                {
                    nums[i+1] = nums[i];
                }
            }
            
            if (wrongElems > 1)
            {
                return false;
            }
        }
        
        return true;
    }
};
```

#### Language used for code

`C++`

#### Expected behavior

The above solution should have failed for test case `[1,2,3,2,2]` and should not have been accepted.
But solution got accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/40790634/89128367-de10ec00-d512-11ea-82a8-ee47bd34d5a1.png)

#### Additional context

Please add test case `[1,2,3,2,2]` for this question.

**Comment by lc-ivan** [comment]
Hi @nebhagat ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @nebhagat ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
