### ISSUE TITLE
997 - Typo in Solution description

### ISSUE THREAD

**Issue by araslanov** [LeetCode-Feedback/LeetCode-Feedback#7541]
#### Your LeetCode username
wizeek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the Solution description, in the Bonus section at the bottom, in the "Can There Be More Than One Town Judge?" subsection, in the first sentence there is a typo in the word `iff`: `we're told that iff there is a town judge, there'll only be one town judge`.

#### Expected behavior
If should be `if` instead of `iff`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for sharing your concern. "iff" stands for "if and only if."
