### ISSUE TITLE
401. Binary Watch - Confusing Question

### ISSUE THREAD

**Issue by Zackhardtoname** [LeetCode-Feedback/LeetCode-Feedback#7546]
#### Your LeetCode username

sampleaccountpage

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

The question talks about using a binary watch, but, very unintuitively, specifies that the hour can only go from 0 to 11. There's no way for the hour to go higher to something like 14 or 2 pm. Also, the question states that the top has 4 lights when the picture clearly shows 5.

#### Expected behavior

I think it's better if you say that something like the "PM light is always on," so you do not need to consider AM vs PM.

#### Screenshots

![image](https://user-images.githubusercontent.com/25935197/171328382-16c1aa36-c27f-45f5-b77b-7d03ca2e3933.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
