### ISSUE TITLE
Missed a test case in 141. Linked List Cycle

### ISSUE THREAD

**Issue by deafTim** [LeetCode-Feedback/LeetCode-Feedback#755]
#### Your LeetCode username

My name is TIENTI0000.

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

I found a mistake, so we can see this in the commented line.
However, in Linked List Cycle II, it would not work. https://leetcode.com/problems/linked-list-cycle-ii/
That's my 1st post on LeetCode, I hope you'll enjoy it!

#### Code you used for Submit/Run operation
```
class Solution(object):
	def hasCycle(self, head):
		"""
		:type head: ListNode
		:rtype: bool
		"""
		if head == None or head.next == None:
			return False        
		if head == head.next:
			return True
		slow = head
		fast = head.next
		while fast!=slow:      # while fast.val!=slow.val: is Wrong but Accepted
			if fast.next==None or fast.next.next==None:
				return False
			fast = fast.next.next
			slow = slow.next
			if fast==slow:      # if fast==slow: is Wrong but Accepted
				return True
		return False
```

#### Language used for code

I used Puthon

#### Expected behavior

This test case should be added

**Comment by lc-ivan** [comment]
Hi @deafTim ,
Thank you for reaching out to us! For clarification, what exactly is the issue you experienced with 141. Linked List Cycle? Is there a specific test case you would like to contribute? If so, please provide that!

**Comment by deafTim** [comment]
Yeah, test case, I will provide it, may be I can do it right in the site.

**Comment by lc-ivan** [comment]
Hello there,
If you would like to provide a test case for this problem, could you please provide it through this Github ticket in the comments?

**Comment by lc-ivan** [comment]
Hello @deafTim,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
