### ISSUE TITLE
pyramid-transition-matrix has error in example with E

### ISSUE THREAD

**Issue by henryhkim** [LeetCode-Feedback/LeetCode-Feedback#7553]
#### Your LeetCode username
henry26

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
n https://leetcode.com/problems/pyramid-transition-matrix/

This phrase
 ```build "E" on level 1``` 

should be  changed from E to "A".   There is no E block.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
