### ISSUE TITLE
Missing test case - 1910. Remove All Occurrences of a Substring

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#7554]
#### Your LeetCode username

yumkam (but don't award me prize :-) - testcase was composed not by me)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My KMP-based [solution was Accepted](https://leetcode.com/submissions/detail/712027606/), but fails test case.

```
"abxabb"
"ab"
```

(testcase was suggested by leetcode user [WangQiuc](https://leetcode.com/WangQiuc)
at [discussion of similar implementation](https://leetcode.com/problems/remove-all-occurrences-of-a-substring/discuss/1299275/True-O(n-+-m)-KMP/1097203))

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    string removeOccurrences(string s, string t) {
        unsigned m = t.size();
        string r;
        // kmp; space = O(n) + O(m)
        vector<unsigned> p(m);
        for (unsigned i = 1, j = 0; i < m; )
            if (t[i] == t[j])
                p[i++] = ++j;
            else if (j > 0)
                j = p[j - 1];
            else
                p[i++] = 0;
        vector<unsigned> jsave(s.length() + 1);
        for (unsigned i = 0, j = 0; i < s.length();) {
            if (s[i] == t[j]) {
                j++; r += s[i++];
                jsave[r.size()] = j;
            } else if (j > 0) {
                j = p[j - 1];
            } else {
                r += s[i++];
                //jsave[r.size()] = j; // <<< HERE: commenting out this line breaks above testcase
            }
            if (j == m) {
                r.resize(r.size() - m, ' ');
                j = jsave[r.size()];
            }
        }
        return r;
    }
};
```

#### Language used for code
C++

#### Expected behavior

This code should not have been Accepted :-)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
