### ISSUE TITLE
Incorrect Test Case - 2288. Apply Discount to Prices

### ISSUE THREAD

**Issue by DmitryAk** [LeetCode-Feedback/LeetCode-Feedback#7555]
#### Your LeetCode username

dm_a

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A newly added testcase - it contradicts to the problem description:
```
"$1e9"
50
```
Expected:
"$1e9"

"A word represents a price if it is a non-negative real number preceded by a dollar sign" - `1e9` is a valid way to write a real number.
But according to the test case expectation - it is considered invalid, what is wrong.
another statements in the problem description about the price:
 - All prices will be positive integers without leading zeros.
 - All prices will have at most 10 digits.

so nothing says that `1e9` is invalid way to record a price (again, "it is a non-negative real number")

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string discountPrices(string s, int discount) {
        string result;
        int i = 0;
        const double mult = static_cast<double>(100 - discount) / 100;
        while (i < s.size()) {
            if (s[i] == ' ') {
                ++i;
                result += ' ';
                continue;
            }
            
            int j = i+1;
            while (j < s.size() && s[j] != ' ') {
                ++j;
            }
            if (s[i] == '$') {
                try {
                    size_t idx;
                    double d = stod(s.substr(i+1, j-i-1), &idx);
                    if (idx != j-i-1) throw exception();
                    d *= mult;
                    
                    std::ostringstream stream;
                    stream << std::fixed;
                    stream << std::setprecision(2);
                    stream << d;
                    
                    result += ("$"+ stream.str());
                    i = j;
                    continue;
                    
                } catch (const exception& ex) {
                }
            }
            result += s.substr(i, j-i);
            i = j;
        }
        return result;
    }
};```

#### Language used for code
C++

#### Expected behavior
The solution must be accepted, because nothing in the problem description said that the real number price representation `$1e9` is invalid.
The newly added test case is invalid (at least for the current problem description)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
Your code Accepted submission link, because when we test your code, it shows Wrong answer. 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by DmitryAk** [comment]
@LC-Pam 
1. https://leetcode.com/contest/weekly-contest-295/submissions/detail/709439176/ - Accepted
2. https://leetcode.com/submissions/detail/712027544/ - Wrong Answer (after the new test case was added) - but it seems to be correct solution, because "1e9" is valid "non-negative real number", and the test case contradicts to the problem statement.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
