### ISSUE TITLE
Missing Test Case - 227. Basic Calculator II

### ISSUE THREAD

**Issue by Nikhilgupta1891** [LeetCode-Feedback/LeetCode-Feedback#7560]
#### Your LeetCode username
Lakshay7 

#### Category of the bug
Missing Test Cases 

#### Description of the bug
Question: https://leetcode.com/problems/basic-calculator-ii/ 
According to Maths BODMAS rule, Divide is calculated before Multiply. 
Hence, "10-4+3*2/10*5" should return 9. Your existing test cases are considering 6 as the right answer, which is wrong.

**Comment by stormsunshine** [comment]
There is no rule that division is calculated before multiplication. Multiplication and division have the same priority.

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's answer.  We appreciate your support!
