### ISSUE TITLE
Wording - 263. Ugly Number

### ISSUE THREAD

**Issue by hkblock** [LeetCode-Feedback/LeetCode-Feedback#7561]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem statement: An ugly number is a *positive* integer ...
Problem takes negative integers as input as well.

**Comment by hkblock** [comment]
Would suggest a hint or an example about negative numbers.

**Comment by stormsunshine** [comment]
Zero and negative integers are also allowed as input. Since an ugly number must be a positive integer, if the input is zero or a negative integer, simply return false.

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's answer.  We appreciate your support!
