### ISSUE TITLE
Missing Test Case - 1733. Minimum Number of People to Teach

### ISSUE THREAD

**Issue by sr-vrd** [LeetCode-Feedback/LeetCode-Feedback#7565]
#### Your LeetCode username

sr_vrd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In <a href="https://leetcode.com/problems/minimum-number-of-people-to-teach/">1733. Minimum Number of People to Teach</a> the current test cases accept a solution that does not check for language `n`.

#### Code you used for Submit/Run operation

This is an <a href="https://leetcode.com/submissions/detail/712661738/">accepted solution</a>:
```
class Solution:
    def cantCommunicate(self, user1: int, user2: int, languages: List[Set[int]]) -> bool:
        '''
        returns True iff user1 and user2 do not know any languages in common
        '''
        return len(languages[user1].intersection(languages[user2])) == 0
    
    def needToTeach(self, language: int, languages: List[Set[int]], missingConnections: Set[int]) -> int:
        '''
        returns number of users that have missing connections and do not know `language`
        '''
        return len([user for user in missingConnections if language not in languages[user]])
    
    def minimumTeachings(self, n: int, languages: List[List[int]], friendships: List[List[int]]) -> int:
        languages = [None] + [set(List) for List in languages]
        missingConnections = set()
        
        for user1, user2 in friendships:
            if self.cantCommunicate(user1, user2, languages):
                missingConnections.add(user1)
                missingConnections.add(user2)
        
        minUsers = len(languages)
        for language in range(n): # <-- !!!
            minUsers = min(minUsers, self.needToTeach(language, languages, missingConnections))
            if minUsers == 0:
                return 0
            
        return minUsers
```

#### Language used for code

Python3

#### Expected behavior

For testcase
```
5
[[1],[5],[1,5],[5]]
[[1,2],[1,3],[1,4],[2,3]]
```
above solution returns `2` (teach `2` and `4` language `1`), when it should return `1` (teach `1` language `5`).

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
