### ISSUE TITLE
提交程序发生未知错误

### ISSUE THREAD

**Issue by xiejiulong9** [LeetCode-Feedback/LeetCode-Feedback#7566]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
663.均匀树划分  提交程序时发生未知错误，我的代码写的很差，但不知道错误的用例是什么
**你使用的语言**
C++

**你提交或者运行的代码**
```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    bool checkEqualTree(TreeNode* root) {
        int rootSum=dfs(root);
        if(rootSum & 1 !=0 || sums.size()<=1) return false;
        if(rootSum==0) return dfs(root->left) == dfs(root->right);
        sums.erase(rootSum);

        return sums.find(rootSum / 2)!=sums.end() ? true : false;
    }
private:
    unordered_multiset<int> sums;
    //返回以自己为节点所形成的树上所有节点的累加和
    int dfs(TreeNode* node){
        if(node==nullptr) return 0;

        int leftSum=dfs(node->left);
        int rightSum=dfs(node->right);

        int mySum=leftSum+rightSum+node->val;
        sums.insert(mySum);

        return mySum;
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/28806191/171598096-a3df9b10-44e9-42cd-b06f-53364b56ffd5.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，在与相关团队核实后：可以点击左侧的解答错误，看到错误的用例。
![image](https://user-images.githubusercontent.com/61722985/174273907-10dba653-53c8-4433-9dc7-fbb207836761.png)

以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
