### ISSUE TITLE
Dynamic Programming explore card: Chapter 1 quiz single choice questions marked as multiple choice

### ISSUE THREAD

**Issue by whyamiroot** [LeetCode-Feedback/LeetCode-Feedback#7567]
#### Your LeetCode username
hardwareflower

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Explore card Content

#### Description of the bug

[Chapter 1 quiz of dynamic programming explore card](https://leetcode.com/explore/learn/card/dynamic-programming/630/an-introduction-to-dynamic-programming/4095/) has all questions marked as "Multiple choice questions", while all of them but the first are single choice questions.

#### Screenshots

![image](https://user-images.githubusercontent.com/3541904/171596957-06953eff-9a3f-4d31-a7ea-085411068431.png)

#### Additional context

[The exercise on heaps](https://leetcode.com/explore/learn/card/heap/643/heap/4000/) also has all questions marked as multiple choice questions, all of them are single choice.

**Comment by stormsunshine** [comment]
There is no term "single choice". For choice problems, all of them are multiple choice problems, no matter there is only one correct answer or there are several correct answers. The term "multiple" means there are multiple items to be selected, not that there are multiple correct items.

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's answer.  We appreciate your support!
