### ISSUE TITLE
Expected solution is wrong

### ISSUE THREAD

**Issue by Shilpahanchinal** [LeetCode-Feedback/LeetCode-Feedback#7568]
Shilpa_hanchinal

#### Category of the bug
- [ ] Question
- [y] Solution
- [ ] Language
- [ ] Missing Test Cases 

For the problem: Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum, there are two test cases [-2,1] and [-2,-1], for which the expected output is showing as 1 and -1 respectively. Whereas the answer is -1 and -3 respectively. So I'm not able to submit my solution successfully as I'm getting error on the above two test cases.

''' class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        s = []
        if len(nums) == 1: return nums[0]
        for i in range(len(nums)-1):
            for j in range(i+1,len(nums)):
                s.append(sum(nums[i:j+1]))
        return(abs(max(s))) '''

Python 3

The answer should be -1 and -3.

**Comment by stormsunshine** [comment]
The expected answers are indeed 1 and -1. Why do you think the answers should be -1 and -3? Please check the definition of "subarray".

**Comment by Shilpahanchinal** [comment]
Thank you for your reply. But I have a question. If the given sequence is [5,4,-1,7,8], then 5,4,-1,7,8 are all considered individual subarrays of the main array(because of "containing at least one number")? Also abs() function in my code was just for testing purpose, that was not not part of my actual code. Including that was a typo.

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's answer.  We appreciate your support!
