### ISSUE TITLE
[Python] test cases behaving differently when submitting from the Testcase tab vs when Submitting via the submit button

### ISSUE THREAD

**Issue by kodepareek** [LeetCode-Feedback/LeetCode-Feedback#7569]
#### Your LeetCode username
kodepareek

#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When hitting the 'Submit' button for the following problems -> 

https://leetcode.com/problems/design-add-and-search-words-data-structure/solution/
https://leetcode.com/problems/implement-trie-prefix-tree/solution/

The following test case always seems to trigger as failed ->

["WordDictionary","search"]
[[],["a"]] 

#### Code you used for Submit/Run operation
```
class TrieNode:
    def __init__(self, isEnd=False, nodes={}):
        self.isEnd = isEnd
        self.nodes = nodes

class WordDictionary:

    def __init__(self):
        self.root = TrieNode()      

    def addWord(self, word: str) -> None:
        root = self.root
        for w in word:
            if not w in root.nodes:
                root.nodes[w] = TrieNode()
            root = root.nodes[w]
        root.isEnd = True

    def search(self, word: str) -> bool:
        root = self.root
        i = 0
        while i < len(word):
            char = word[i]
            if char == '.':
                i += 1
                return self.search(word[i:])
            elif char in root.nodes:
                i += 1
                root = root.nodes[char]
            else:
                return False
        return True
                
```

#### Language used for code
Python

#### Expected behavior
I copied the above test case into the test cases tab. When running the test case my code above returned the correct answer. However when submitting the code, the system seems to consider that this test case is failing. 

![image](https://user-images.githubusercontent.com/18524074/171633689-f096f591-cda9-40e2-8dc1-7bd4e89f8aea.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
