### ISSUE TITLE
88. 合并两个有序数组 C 版本的 函数接口有问题

### ISSUE THREAD

**Issue by liuyunbin** [LeetCode-Feedback/LeetCode-Feedback#757]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目：[88. 合并两个有序数组](https://leetcode-cn.com/problems/merge-sorted-array/) 的 C 版本的接口有问题

接口应该是：

```
void merge(int* nums1, int m, int* nums2, int n);
```

而不是：

```
void merge(int* nums1, int nums1Size, int m, int* nums2, int nums2Size, int n);
```

nums1Size 和 nums2Size 这两个参数没任何作用

**你使用的语言**
C

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
你好，技术确认这个没有任何作用也没关系，用户不一定需要使用所有的入参，请知晓。

**Comment by liuyunbin** [comment]
问题是，我以前使用的就是 `void merge(int* nums1, int m, int* nums2, int n);` 不知道现在为啥要改成 `void merge(int* nums1, int nums1Size, int m, int* nums2, int nums2Size, int n);`
