### ISSUE TITLE
Language - 993. Cousins in Binary Tree

### ISSUE THREAD

**Issue by jaisw7** [LeetCode-Feedback/LeetCode-Feedback#7571]
#### Your LeetCode username
jaisw7

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The function signature (see code below) uses `isCousins` as function name. `isCousins` is grammatically incorrect. It should rightly be `areCousins`

#### Code you used for Submit/Run operation
```C++
class Solution {
public:
    bool isCousins(TreeNode* root, int x, int y) {
        
    }
};
```

#### Language used for code
C++

#### Expected behavior
The function name should be replaced with `areCousins`.
```C++
class Solution {
public:
    bool areCousins(TreeNode* root, int x, int y) {
        
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. This problem was published in 2017/2018 and has many solutions. Changing the signature will cause all solutions to get CE. We appreciate your support!
