### ISSUE TITLE
Wrong Test Case - 2190. Most Frequent Number Following Key In an Array

### ISSUE THREAD

**Issue by Parasharpy** [LeetCode-Feedback/LeetCode-Feedback#7572]
#### Your LeetCode username
 Parashar_py

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ Yes] Missing Test Cases 

#### Description of the bug
In Question, it is defined that the target with maximum count is unique but there are few test cases where target having same number of occurrences. For e.g. [1,1,2,1,2], key = 1. Here, target can be 1 (index = 1) when key is at index 0, then 1 will have two occurrences and when key's index is 1 (target = 2), here target will also have two occurrences. One more such case: [1,1,1,1,2,2,2], key = 1. Here, target can be 1 (index = 1), it has 3 occurrences and target can be 2 (index = 4), it has also 3 occurrences.

#### Code you used for Submit/Run operation
```
class Solution:
    def mostFrequent(self, nums: List[int], key: int) -> int:
        store = []
        for i in range(len(nums)):
            if nums[i] == key:
                store.append(i)
        max_occur = 0
        element = nums[0]
        for i in store:
            if i == len(nums) - 1:
                break
            target = nums[i+1]
            count = 0
            for j in range(i+1, len(nums)):
                if nums[j] == target:
                    count += 1
            if count > max_occur:
                max_occur = count
                element = nums[i+1]
        return element
```

#### Language used for code
python3

#### Expected behavior
For e.g. [1,1,2,1,2], key = 1. Here, target can be 1 (index = 1) when key is at index 0, then 1 will have two occurrences and when key's index is 1 (target = 2), here target will also have two occurrences. For such cases, there should be one more condition given in the question or both answers should be correct.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
