### ISSUE TITLE
867. transpose matrix for c#  solution return type

### ISSUE THREAD

**Issue by mhimlinhm** [LeetCode-Feedback/LeetCode-Feedback#7573]
#### Your LeetCode username
mhimlin

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The definition as written in the solution is: public int[][] Transpose(int[][] matrix) {  But the question states "Given a 2D integer array matrix,"  In C# a 2d matrix array would be declared int[x,y]  not int [x][y]  The [x][y] syntax actually declares an array of variable length arrays (or a jagged array)  which from looking at the solutions in Java is not the intention of this question.  It adds additional layers of complexity for the C# programmers.

#### Code you used for Submit/Run operation

```
public class Solution {
    public int[][] Transpose(int[][] matrix) {
     
        
        int len1 = matrix[0].Length;
        int len2 = matrix.Length;
        int[][] answer = new int[len1][];

 //C# Users should not have to do the steps below if Transpose Method was defined as:
//  public int[,] Transpose(int[][] matrix) {     
//Could then decalre return as answer[len1,len2]... instead of this initialization loop to declare inner arrays
       for(int x = 0; x < len1; x++)
        {
            answer[x] = new int[len2];
        }
        
        for(int i = 0;i < len2; i++){
            
            for(int j = 0; j < len1 ; j++){
            
            
                answer[j][i] = matrix[i][j];
            }
        }
        
        return answer;
        
        
    }
}
```

#### Language used for code
C#

#### Expected behavior

Transpose method in Solution should be decared as:

public int[,] Transpose(int[][] matrix) {  

#### Additional context
From looking at the problem description and the suggested Java solution, it does not appear that the intention is to add the complexity of Jagged Arrays.  This is only a quirk of how the Transpose method was declared and a C# coder would likely not declare it that way.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. For now, we can’t change the C#'s 2D array definition, it would break all existing solutions for existing problems. But we will revisit it in future. . We appreciate your support!
