### ISSUE TITLE
Can we have Inaccurate-Difficulty-Feedback separated out from Downvote-A-Question?

### ISSUE THREAD

**Issue by vishalJ16** [LeetCode-Feedback/LeetCode-Feedback#7574]
My Leetcode username : user7029FW

During my practice and a few months long acquaintance with Leetcode, I have encountered questions which I feel are inaccurately marked for difficulty, which is again defined by my knowledge, level of understanding, and ease of solving a problem.
But the only way of telling about inaccurate difficulty is by downvoting a question, which I think is not fair and justified.

Downvoting a question implies something wrong with the questions language, description, or maybe testcase or simply a poorly framed problem.

A question may be difficult, but not necessarily a candidate for downvote.

In general, if you see something downvoted, you get an impression, something is wrong with this, and you tend to avoid that thing; but having an inaccurate difficulty, I feel, has nothing to do with all this.
Just an example - There are many mentions in different posts/articles which says that do not focus or attempt the ques which has high downvote ratio. So downvote because of difficulty should not put an impression that the ques is not good.

I have seen many very nice questions marked with the difficulty, which I feel is incorrect, it can be lower or higher in difficulty, but at the same time I do not want to downvote that ques.

So Can we have Inaccurate-Difficulty-Feedback separated out from Downvote-A-Question?

I hope I was able to convey what I wanted to say :)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!

**Comment by vishalJ16** [comment]
Today, I saw this has been implemented at LeetCode. :)
<img width="1715" alt="Screenshot 2023-03-21 at 10 03 16 PM" src="https://user-images.githubusercontent.com/21159588/226678635-0710ccbc-71f1-4039-81ef-796607cefda2.png">
