### ISSUE TITLE
Missing Test Case - 1283. Find the Smallest Divisor Given a Threshold

### ISSUE THREAD

**Issue by ChandrakantSahu17** [LeetCode-Feedback/LeetCode-Feedback#7575]
#### Your LeetCode username
ck_17

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Wrong code still leetcode accepts that code. 

#### Test Case which needs to be added 
<pre>
Input:
[1,1,1,1,1,3,6,7,100]
10

Output: 36

Expected: 50
</pre>

#### Code you used for Submit/Run operation

```
class Solution {
    int div( int t, vector<int>& nums){
        int sum = 0;
        for( int &i : nums ){
            sum += ( i + t - 1 )/t;
        }
        return sum;
    }
public:
    int smallestDivisor(vector<int>& nums, int t) {
        
        int sum = div( t, nums);
        
        int start = 1;
        int end = sum<<1;
        
        while( start < end ){
            
            int mid = ( ( end - start ) >> 1 ) + start;
            
            if( div( mid, nums ) > t )
                start = mid+1;
            else
                end = mid;
                
        }
        
        return start;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Wrong Answer

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
