### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by MohamedKhalaf10** [LeetCode-Feedback/LeetCode-Feedback#7576]
#### Your LeetCode username
mohamed_khalaf

#### Category of the bug
- [x] Solution

#### Description of the bug

Hello,
In problem (234. Palindrome Linked List) using JavaScript
the output is supposed to be false, while it was true on the LeetCode text editor. I tried the code in the VS Studios and developers tools on chrome and it was false. I even tried a more detailed code that has a condition for only an array with 2 elements and it was true too on the LeetCode text editor. I hope you fix this issue.

#### Code you used for Submit/Run operation

```
// Palindrome Linked List
const isPalindrome = function(head) {
let length = head.length;
let evenStop = (length/2)-1;
let individualStop = ((length-1)/2)-1;
if (length % 2 === 0){
  for (let i = 0; i <= evenStop; i++){
    if (head[i] != head[length- (i +1)]){
      return false;
    }
  }
  return true;
} else {
    for (let i = 0; i <= individualStop; i++){
      if (head[i] != head[length- (i +1)]){
        return false;
      }
    }
    return true;
  }
};
```

#### Language used for code
JavaScript

#### Expected behavior
The output is supposed to be false, while it was true on the LeetCode text editor.

#### Screenshots
![1](https://user-images.githubusercontent.com/96386477/171731305-100e6cd1-4e95-4702-a27e-7fa3ba2c2a42.PNG)
![2](https://user-images.githubusercontent.com/96386477/171731317-161735b2-a329-492c-9961-aa0e7b4b80cc.PNG)
![3](https://user-images.githubusercontent.com/96386477/171731329-cc4fafd0-da22-4de6-ae44-d7d5074d0627.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, we got the wrong answer of you code, not test case. If you have Code Submission Accepted Link, please send it to us, then we can check more details of the issue that you requested.
