### ISSUE TITLE
814. Binary Tree Pruning Missing test cases

### ISSUE THREAD

**Issue by singh96** [LeetCode-Feedback/LeetCode-Feedback#758]
#### Your LeetCode username

sumitsingh96

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

For Question [814. Binary Tree Pruning](https://leetcode.com/problems/binary-tree-pruning/). The test case where we need to prune the whole tree is missing.

##### Example
For Input: `[0,null,0,0,0]`, the expected output should be `[]`. 
But my solution gives output `[0]` and still clears all the test cases i.e. a Successful submission.

But when test case `[0,null,0,0,0]` is entered through console, it expects `[]` as output.

#### Code you used for Submit/Run operation
```
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
class Solution {
    
    public int getValueInSubTree(TreeNode root) {
        if (root == null) {
            return 0;
        }
        int left = getValueInSubTree(root.left);
        int right = getValueInSubTree(root.right);
        
        if (left == 0) {
            root.left = null;
        }
        if (right == 0) {
            root.right = null;
        }
        
        if (left == 0 && right == 0 && root.val == 0) {
            return 0;
        }
        return 1;
    }
    
    
    public TreeNode pruneTree(TreeNode root) {
        getValueInSubTree(root);
        return root;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
A solution which returns Tree as `[0]`when whole tree is pruned should fail the submission. 
There should be a test case where whole tree is pruned.
One of the input for such tree is `[0,null,0,0,0]`

#### Screenshots

![image](https://user-images.githubusercontent.com/24877093/89184909-0d793480-d5b7-11ea-815a-ff7fb5652c63.png)

**Comment by lc-ivan** [comment]
Hi @singh96 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @singh96 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
