### ISSUE TITLE
Missing Test Case - 304. Range Sum Query 2D - Immutable

### ISSUE THREAD

**Issue by raditya1710** [LeetCode-Feedback/LeetCode-Feedback#7582]
#### Your LeetCode username
alfonsus_raditya

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When the matrix has this property:
```
m = 200
n = 200
matrix = {all have value 100.000}
```
it overflows (and considered invalid testcase), but it should gives answer 4000000000.

#### Code you used for Submit/Run operation

```
class NumMatrix:

    def __init__(self, matrix: List[List[int]]):
        r = len(matrix)
        c = len(matrix[0])
        self.prefix = [];
        for i in range(r):
            cur_prefix = []
            for j in range(c):
                up = 0 if (i == 0) else self.prefix[i - 1][j];
                left = 0 if (j == 0) else cur_prefix[j - 1];
                upleft = 0 if (i == 0 or j == 0) else self.prefix[i - 1][j - 1];
                
                now = matrix[i][j] + up + left - upleft;
                cur_prefix.append(now);
            self.prefix.append(cur_prefix)

    def sumRegion(self, row1: int, col1: int, row2: int, col2: int) -> int:
        ans = self.prefix[row2][col2]
        if row1 >= 1:
            ans -= self.prefix[row1 - 1][col2]
        if col1 >= 1:
            ans -= self.prefix[row2][col1 - 1]
        if row1 >= 1 and col1 >= 1:
            ans += self.prefix[row1 - 1][col1 - 1]
        return ans
```

#### Language used for code

python3

#### Expected behavior

it should gives an answer `4000000000`, since the test case is within the constraint.

#### Screenshots

![Screenshot from 2022-06-03 10-51-48](https://user-images.githubusercontent.com/14028227/171782623-375af084-bc61-4972-9436-da8d17607b82.png)

#### Additional context

this is the testcase file: 
[bug-rangesum2D-immutable.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8829404/bug-rangesum2D-immutable.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Based on impact, decided not to add the solution.
Added a constraint that sum of all values of matrix does not exceed |10^9|. Updated validator accordingly.
We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
