### ISSUE TITLE
310. 最小高度树的题解描述不正确

### ISSUE THREAD

**Issue by lixiangdude** [LeetCode-Feedback/LeetCode-Feedback#7585]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
刺杀骑士团长

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
<img width="771" alt="image" src="https://user-images.githubusercontent.com/29158756/171808029-bafcf0f0-727a-4f83-a9e6-20214e6744cd.png">
这里所说的"假设交叉点为 a, 则可以知道此时 z 到 x 的距离为dist[z][x] = dist[z][a] + dist[a][z]"应改为"dist[z][x] = dist[z][a] + dist[a][x]"

**Comment by feiceh** [comment]
你好，当前题解已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by lixiangdude** [comment]
leetcode-cn.com/u/zhang-shi-qing-ge-IZJ3cvAal3/

**Comment by lixiangdude** [comment]
> 你好，当前题解已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

leetcode-cn.com/u/zhang-shi-qing-ge-IZJ3cvAal3/

**Comment by feiceh** [comment]
你好，ID：zhang-shi-qing-ge-IZJ3cvAal3 给予积分奖励，请查收。
