### ISSUE TITLE
986. Interval List Intersections - equivalent intersection considered incorrect

### ISSUE THREAD

**Issue by mancini0** [LeetCode-Feedback/LeetCode-Feedback#7591]
In the below output,  [15,25] is not considered equivalent to [15,23],[24,24],[25,25] - but I believe it should be as the intervals are closed and continuous, so {[1,N]} is equivalent to {[1,N-2], [N-1,N-1],[N,N]}. 

Output
[[1,2],[5,5],[8,10],[15,25]]
Expected
[[1,2],[5,5],[8,10],[15,23],[24,24],[25,25]]

To reproduce, use this solution which adds all members of the ranges in firstList to a sorted set, all members of ranges in the secondList to a sorted set, retains the common members of the two sets, and traverses one of the sets recording a new intersection any time the step size between successive iterations is greater than 1, or if the end of of the iteration is reached. The test input applicable to the solution is:
input:
[[0,2],[5,10],[13,23],[24,25]]
[[1,5],[8,12],[15,24],[25,26]]

```
    public int[][] intervalIntersection(int[][] firstList, int[][] secondList) {
        Set<Integer> a = new TreeSet<>();
        Set<Integer> b = new TreeSet<>();
        for(int[] l : firstList){
            IntStream.rangeClosed(l[0],l[1]).forEach(a::add);
        }
        for(int[] l : secondList){
            IntStream.rangeClosed(l[0],l[1]).forEach(b::add);
        }
        a.retainAll(b);
        List<Integer> al = new ArrayList<>(a);
        Integer prev = null;
        Integer start = null;
        List<List<Integer>> res = new ArrayList<>();
        for(int i = 0; i < a.size(); i++){
            if(prev==null){
                prev=al.get(i);
                start = al.get(i);
                continue;
            }
            if(al.get(i)-prev<=1){
                prev=al.get(i);
                if(i!=al.size()-1) continue;
            }
            res.add(List.of(start,prev));
            prev=al.get(i);
            start=al.get(i);
            
        }
     return  res.stream()
         .map(l->l.stream().mapToInt(i->i).toArray())
         .toArray(int[][]::new);   
    }
```

![Screenshot from 2022-06-03 07-18-52](https://user-images.githubusercontent.com/5806901/171844678-42d6f29d-0c0a-4023-a809-bda0550bf063.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, your code has compile error, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by mancini0** [comment]
Hi Pam,

This issue  is not related to my code. The screenshot shows my code
compiled, but regardless, the issue is that equivalent closed ranges are
not accepted as answers. (See attached screenshot). You can disregard the
code snippet I pasted if it does not compile and use the screenshot as
evidence of the issue - don't you agree that [13,25] is mathematically
equivalent to [13,23], [24,24], [25,25] ?
