### ISSUE TITLE
Missing test case in 1072. Flip Columns For Maximum Number of Equal Rows

### ISSUE THREAD

**Issue by kazi-nayeem** [LeetCode-Feedback/LeetCode-Feedback#760]
#### Your LeetCode username

mkazinayeem

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Below solution got accepted but it gives wrong output for `[[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]]`.
Output should be `1` but it gives `2`.

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    int maxEqualRowsAfterFlips(vector<vector<int>>& matrix) {
        unordered_map<unsigned long long, int> lines;
        int res = 0;
        for (auto& x : matrix) {
           res = max(res, ++lines[to_key(x)]);
        }
        return res;
    }
    
    unsigned long long to_key(vector<int> & row) {
       bool invert = row[0] == 1;
       unsigned long long key = 0;
       for (int i : row) {
          if (invert) i = !i;
          key = (key << 1) | i;
       }
       return key;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Should be wrong answer.

#### Screenshots

![Screenshot from 2020-08-05 01-52-40](https://user-images.githubusercontent.com/19363966/89338603-9cbd3f80-d6be-11ea-8b5a-3278a8530451.png)

**Comment by lc-pam** [comment]
Hi @kazi-nayeem 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @kazi-nayeem 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
