### ISSUE TITLE
836 - Typo in description

### ISSUE THREAD

**Issue by araslanov** [LeetCode-Feedback/LeetCode-Feedback#7602]
#### Your LeetCode username
wizeek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the Constraints section of the problem description, it says `rect1.length == 4` and `rect2.length == 4`.

#### Expected behavior
It should be `rec1.length == 4` and `rec2.length == 4` i.e. `rec1` instead of `rect1` and `rec2` instead of `rect2` since that's what these arrays are referred to throughout the rest of the description.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
