### ISSUE TITLE
贡献测试用例

### ISSUE THREAD

**Issue by Castor6** [LeetCode-Feedback/LeetCode-Feedback#7604]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Castor

**Bug 类型**
- [ ] 题目  [剑指 Offer 31. 栈的压入、弹出序列](https://leetcode.cn/problems/zhan-de-ya-ru-dan-chu-xu-lie-lcof/)
- [ ] 题解
- [ ] 编程语言  java
- [x] 缺少测试用例

**描述**
代码提交能通过全部测试用例，但是我自己构造了一个测试用例没有通过，如下
[1,2,3,4,5]
[4,3,1,5,2]
建议增加这个测试用例

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    public boolean validateStackSequences(int[] pushed, int[] popped) {
        /*
            3 4 2 1 0
            3 2 4 0 1
        */
        int n = pushed.length;
        if(n == 0)  return true;
        HashMap<Integer, Integer> map = new HashMap<>();
        for(int i = 0;i < n;i++){
            map.put(pushed[i], i);
        }
        int max = map.get(popped[0]);   // 记录当前最大入栈到哪个下标
        for(int i = 1;i < n;i++){
            int idx = map.get(popped[i]);
            if(idx > max)   max = idx;
            else if(idx > map.get(popped[i - 1]))  return false;
        }
        return true;
    }
}
```

**期望行为**
我提交的代码不应通过

**屏幕截图**
![image](https://user-images.githubusercontent.com/65103110/171983779-af0fae4b-bc29-48df-9c6b-0fb0b184d0af.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：Castor 给予积分奖励，请查收。
