### ISSUE TITLE
missing Test case - 1873. Calculate Special Bonus

### ISSUE THREAD

**Issue by demonipun** [LeetCode-Feedback/LeetCode-Feedback#7605]
#### Category of the bug
- Missing Test Cases 

#### Description of the bug

The question does not mention that we need to sort the query by employee_id.
Input Testcase :
{"headers":{"Employees":["employee_id","name","salary"]},"rows":{"Employees":[[2,"Meir",3000],[3,"Michael",3800],[9,"Addilyn",7400],[8,"Juan",6100],[7,"Kannon",7700]]}}
Possible edge case not taken care of and I managed to get AC, the second most upvoted solution is also wrong .

#### Code Submit/Run operation

```
select employee_id, (
    case
    when employee_id % 2 =1 and name not like 'M%' then salary
    else 0
    end
) as bonus from Employees order by employee_id;
```

#### Language used for code

MySQL

#### Expected behavior

The above code should not pass all the test cases.

#### Screenshots

![image](https://user-images.githubusercontent.com/71482945/171989714-e3ec7ae1-f091-48e2-a63d-97b1a1b23519.png)

![image](https://user-images.githubusercontent.com/71482945/171989493-bebc96da-9365-4f66-ac31-bf36e22aac8d.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
