### ISSUE TITLE
题目描述不严谨

### ISSUE THREAD

**Issue by hooozen** [LeetCode-Feedback/LeetCode-Feedback#7606]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**site.hozen**

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[第50题 Pow(x,n)](https://leetcode.cn/problems/powx-n/) 题目表述中，是否应该明确 $n$ 为整数？

**Comment by feiceh** [comment]
你好，当前题目描述已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by hooozen** [comment]
这是我的个性域名 [leetcode-cn.com/u/hozen/](www.leetcode-cn.com/u/hozen/)

谢谢！

**Comment by feiceh** [comment]
你好，ID：hozen 给予积分奖励，请查收。
