### ISSUE TITLE
Missing constraints section - 464. Can I Win

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#761]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

464. Can I Win
https://leetcode.com/problems/can-i-win/

Please add contraints for this question.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Question should have constraints section, which is missing.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy ,
Thanks for reaching out to us. The problem states "You can always assume that maxChoosableInteger will not be larger than 20 and desiredTotal will not be larger than 300.". Are there any specific constraints you think are still missing in the problem?

**Comment by manoharreddyporeddy** [comment]
Thanks. Those are uppper bounds. A contraints section would tell both lower & upper bound, and any other derived contrainsts too.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thanks for the clarification. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
