### ISSUE TITLE
Test Case Error - 1658. Minimum Operations to Reduce X to Zero

### ISSUE THREAD

**Issue by perses08** [LeetCode-Feedback/LeetCode-Feedback#7610]
#### Your LeetCode username
perses

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

We can Able to reduce X to zero with 5 steps for below test case
[6016,5483,541,4325,8149,3515,7865,2209,9623,9763,4052,6540,2123,2074,765,7520,4941,5290,5868,6150,6006,6077,2856,7826,9119]

#### Code you used for Submit/Run operation

```
// 1658. Minimum Operations to Reduce X to Zero
class Solution(object):
    def minOperations(self, nums, x):
        """
        :type nums: List[int]
        :type x: int
        :rtype: int
        """
        i = len(nums)
        sum_ = 0
        def Zero(arr, x, i, sum_):
            if x == 0:
                return sum_
            elif i < 1:
                return float('inf')
            elif arr[i-1]>x:
                return Zero(arr, x, i-1, sum_)
            else:
                return min(Zero(arr, x-arr[i-1], i-1, sum_+1), Zero(arr, x, i-1, sum_))
        return -1 if Zero(nums, x, i, sum_) == float('inf') else  Zero(nums, x, i, sum_)
```

#### Language used for code
Python

#### Expected behavior

Input : [6016,5483,541,4325,8149,3515,7865,2209,9623,9763,4052,6540,2123,2074,765,7520,4941,5290,5868,6150,6006,6077,2856,
7826,9119]
31841

Output : 5

Expected : 6

5483 + 3515 + 9763 + 6540 + 6540 = 31841
5483 + 3515 + 6540 + 9763 + 6540 = 31841
5483 + 3515 + 6540 + 6540 + 9763 = 31841
5483 + 9763 + 3515 + 6540 + 6540 = 31841
5483 + 9763 + 6540 + 3515 + 6540 = 31841
5483 + 9763 + 6540 + 6540 + 3515 = 31841
5483 + 6540 + 3515 + 9763 + 6540 = 31841
5483 + 6540 + 3515 + 6540 + 9763 = 31841
5483 + 6540 + 9763 + 3515 + 6540 = 31841
5483 + 6540 + 9763 + 6540 + 3515 = 31841
5483 + 6540 + 6540 + 3515 + 9763 = 31841
5483 + 6540 + 6540 + 9763 + 3515 = 31841
541 + 8149 + 9763 + 7520 + 5868 = 31841
541 + 8149 + 9763 + 5868 + 7520 = 31841
541 + 8149 + 7520 + 9763 + 5868 = 31841
541 + 8149 + 7520 + 5868 + 9763 = 31841
541 + 8149 + 5868 + 9763 + 7520 = 31841
541 + 8149 + 5868 + 7520 + 9763 = 31841
541 + 9763 + 8149 + 7520 + 5868 = 31841
541 + 9763 + 8149 + 5868 + 7520 = 31841
541 + 7520 + 8149 + 9763 + 5868 = 31841
541 + 7520 + 8149 + 5868 + 9763 = 31841
541 + 5868 + 8149 + 9763 + 7520 = 31841
541 + 5868 + 8149 + 7520 + 9763 = 31841

#### Screenshots

![Screenshot from 2022-06-05 07-39-16](https://user-images.githubusercontent.com/33995683/172032752-3110d871-000b-40ff-932f-72057547c1bd.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
