### ISSUE TITLE
35. 搜索插入位置 选择 Go 语言编译出错

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#7611]
**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
1. 打开 [35. 搜索插入位置](https://leetcode.cn/problems/search-insert-position/) 选择 Go
2. 输入任何代码
3. 执行代码，显示编译出错

**你使用的语言**
Golang

**你提交或者运行的代码**
```go
func searchInsert(nums []int, target int) int 
  l, r := 0, len(nums) - 1
  for l <= r {
    m := (l + r) >> 1
    if nums[m] >= target {
      r = m - 1
    } else {
      l = m + 1
    }
  }
  return l
}
```

**期望行为**
正常编译执行

**屏幕截图**
![image](https://user-images.githubusercontent.com/4961543/172034317-c5fe5677-25e3-4b96-833f-4a6a6de56e64.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：括号不匹配。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
