### ISSUE TITLE
1332. Remove Palindromic Subsequences

### ISSUE THREAD

**Issue by srwarner** [LeetCode-Feedback/LeetCode-Feedback#7612]
#### Your LeetCode username
srwarner

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
the sequence "abababaabb" has 3 palindromes, yet "Run Code" reports that the Expected number of palindromes is 2.

#### Code you used for Submit/Run operation
unneeded

#### Language used for code
unneeded

#### Expected behavior
there should be 3 palindromes expected.

#### Screenshots
<img width="377" alt="Screen Shot 2022-06-04 at 9 21 30 PM" src="https://user-images.githubusercontent.com/37416010/172034909-8d9eb86a-2ae7-41b0-8e7d-fb25347133ca.png">

**Comment by srwarner** [comment]
I didnt submit, as the code submission would. have failed.  All you need is a return value of 0 to any program, and you can see that the test-case expected results in 2 rather than 3.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
