### ISSUE TITLE
Missing Test Case - 2295. Replace Elements in an Array

### ISSUE THREAD

**Issue by deepuyadav004** [LeetCode-Feedback/LeetCode-Feedback#7613]
#### Your LeetCode username
 HUE_HUE

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug
 Queestion accept answer for a test case which gives wrong output

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> arrayChange(vector<int>& nums, vector<vector<int>>& op) {
        unordered_map<int,int> hm;     //****store index of element
        for(int i =0;i<nums.size();i++){
            
            hm[nums[i]] = i;
        }
        
        for(int i =0;i<op.size();i++){
            
            
            int a  = op[i][0];
            int b = op[i][1];
            
            nums[hm[a]] = b;
            
            hm[b] = hm[a];  //**also store the changed element in hashmap
            
            
        }
        return nums;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
 for test case [1,2,4,6]
[[1,3],[4,7],[6,1],[1,4]]
the answer should be [3,2,7,1] but above code gives [3,2,7,4] as answer which is wrong even then leetcode accept this question. I think this type of test cases should be encountered.
 

#### Screenshots

![image](https://user-images.githubusercontent.com/77964981/172034996-d117a952-0ee4-4243-82c3-f733c84924c5.png)

**Comment by stormsunshine** [comment]
The last operation changes 1 to 4, so the answer is [3,2,7,4].

The whole process is as follows.

```
[1,2,4,6] -> [3,2,4,6] -> [3,2,7,6] -> [3,2,7,1] -> [3,2,7,4]
```

Is there any problem?

**Comment by stormsunshine** [comment]
The last operation changes 1 to 4, so the answer is [3,2,7,4].

The whole process is as follows.

```
[1,2,4,6] -> [3,2,4,6] -> [3,2,7,6] -> [3,2,7,1] -> [3,2,7,4]
```

Is there any problem?

**Comment by deepuyadav004** [comment]
my mistake
