### ISSUE TITLE
Missing Test Case - 2296. Design a Text Editor

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7614]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [2296. Design a Text Editor](https://leetcode.com/problems/design-a-text-editor), a solution that can get accepted fails on a specific test case.

The test case is: [2296.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8839384/2296.txt)

#### Code you used for Submit/Run operation
```C++
class TextEditor {
    string s;
    int pos ;
public:
    TextEditor() {
        pos = 0;
    }
    
    void addText(string text) {
        s.insert(pos, text);
        pos += text.size();
    }
    
    int deleteText(int k) {
        int ans = 0;
        while (pos != 0 && ans < k) {
            s.erase(pos-1, 1);
            --pos;
            ++ans;
        }
        return ans;
    }
    
    string cursorLeft(int k) {
        pos = max(pos-k, 0);
        string res;
        for (int i = pos-10; i < pos; ++i) if (i >= 0) res += s[i];
        return res;
    }
    
    string cursorRight(int k) {
        pos = min(pos+k, int(s.size()));
        string res;
        for (int i = pos-10; i < pos; ++i) if (i >= 0) res += s[i];
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Add the test case so that the code above will get TLE when submitted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem (The solution was getting TLE as expected. We added the test case but the solution was TLE. so we doubt that it was AC on LCCN side only.) We appreciate your support!
