### ISSUE TITLE
Missing Test Case - 545. Boundary of Binary Tree

### ISSUE THREAD

**Issue by jinlongchen** [LeetCode-Feedback/LeetCode-Feedback#7616]
#### Your LeetCode username
jinlongchen

#### Category of the bug
- Missing Test Cases 

[1,2,3,4,5,6,null,7,null,8,9,10,11,null,null,12,13,null,null,null,null,null,null,14,null,null,null,15,null,16]

the expected answer is: [1,2,4,7,16,13,9,10,11,6,3]

but i think it should be: [1,2,4,7,12,14,15,16,13,9,10,11,6,3]

**Comment by stormsunshine** [comment]
What is the code that can get accepted but fails on the test case?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
