### ISSUE TITLE
52. N-Queens II - Example test case PASS but LEETCODE test FAIL

### ISSUE THREAD

**Issue by elulcao** [LeetCode-Feedback/LeetCode-Feedback#7619]
#### Your LeetCode username
elulcao

#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

#### Description of the bug
Solution in Go for 52. N-Queens II failed Leetcode submission but local Test Example passed.
totalNQueens(1) returns 1 for Example test but LeetCode test (Remote) returns 3. LeetCode check must return 1 as the example Test.

#### Code you used for Submit/Run operation
```Golang
package main

import "fmt"

var size int
var solutions []sol
var exists = struct{}{}

type set struct {
	m map[int]struct{}
}

func NewSet() *set {
	s := &set{}
	s.m = make(map[int]struct{})
	return s
}

func (s *set) Add(value int) {
	s.m[value] = exists
}

func (s *set) Remove(value int) {
	delete(s.m, value)
}

func (s *set) Contains(value int) bool {
	_, c := s.m[value]
	return c
}

type sol struct {
	name []string
}

func totalNQueens(n int) int {
	size = n
	state := make([][]string, 0)

	for i := 0; i < n; i++ {
		tmp := make([]string, 0)

		for j := 0; j < n; j++ {
			tmp = append(tmp, ".")
		}

		state = append(state, tmp)
	}

	backtrack(0, NewSet(), NewSet(), NewSet(), &state)
	fmt.Printf("solutions: %v\n", solutions)
	return len(solutions)
}

func genBoard(board [][]string) sol {
	s := &sol{}

	for i := 0; i < size; i++ {
		var str string

		for j := 0; j < size; j++ {
			str += board[i][j]
		}

		s.name = append(s.name, str)
	}

	return *s
}

func backtrack(row int, diag *set, antiDiag *set, cols *set, state *[][]string) {
	//fmt.Printf("state: %v\n", state)
	if row == size {
		solutions = append(solutions, genBoard(*state))
		return
	}

	for col := 0; col < size; col++ {
		newDiad := row - col
		newAntiDiad := row + col

		if cols.Contains(col) || diag.Contains(newDiad) || antiDiag.Contains(newAntiDiad) {
			continue
		}
		cols.Add(col)
		diag.Add(newDiad)
		antiDiag.Add(newAntiDiad)
		(*state)[row][col] = "Q"

		backtrack(row+1, diag, antiDiag, cols, state)

		cols.Remove(col)
		diag.Remove(newDiad)
		antiDiag.Remove(newAntiDiad)
		(*state)[row][col] = "."
	}
}

func main() {
	fmt.Println(totalNQueens(4))
}
```

#### Language used for code
Go

#### Expected behavior
totalNQueens(4) -> 2
totalNQueens(3) -> 0
totalNQueens(2) -> 0
totalNQueens(1) -> 1

```
➜ Desktop go run queens.go
solutions: [{[.Q.. ...Q Q... ..Q.]} {[..Q. Q... ...Q .Q..]}]
2

➜ Desktop go run queens.go
solutions: []
0

➜ Desktop go run queens.go
solutions: []
0

➜ Desktop go run queens.go
solutions: [{[Q]}]
1
```

#### Screenshots
![Screen Shot 2022-06-05 at 13 45 23](https://user-images.githubusercontent.com/6373960/172065922-c71f0c5f-03dd-4cbb-b66d-e9ffdf69af91.png)

Example test PASS but LeetCode fails
![Screen Shot 2022-06-05 at 13 45 44](https://user-images.githubusercontent.com/6373960/172065938-efb13b61-acd1-44d0-b9b9-2149612815e1.png)

#### Additional context

totalNQueens(1) returns 1 for Example test but LeetCode test (Remote) returns 3. LeetCode check must return 1 as the example Test.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the code that you submitted above received Compile Error, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by elulcao** [comment]
Can you show me the compiler error?
it is working at my local:
➜ Desktop go run queens.go
solutions: [{[.Q.. ...Q Q... ..Q.]} {[..Q. Q... ...Q .Q..]}]
2
