### ISSUE TITLE
Unclear Problem description and Incomplete Testcases - 877. Stone Game

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#762]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

877. Stone Game
https://leetcode.com/problems/stone-game/

1
 What does below mean?

> Each turn, a player "takes the entire pile of stones" from either the beginning or the end of the row.

Does this mean player can take only from 1 end, once one of the ends is choosen? If so, test case does not agree to this description as Alice is able to take 5 from both ends.

2
Only 1 test case is given "Example 1", it shows the obvious 1st player win.

Another test case is needed to demonstrate how 2nd player can ever win.

Otherwise, a simple `return true` will be enough as an answer, because there is always a way to win by Alice as `The total number of stones is odd, so there are no ties.` is given. If so, why is this Medium?, it can be Easy too. For example, following problem is Easy as it can be 1 line answer - https://leetcode.com/problems/divisor-game/

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

1. Problem description must be unambiguous
2. Test case must demonstrate 1 example of core cases.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
