### ISSUE TITLE
Missing Test Case - 104. Maximum Depth of Binary Tree

### ISSUE THREAD

**Issue by romanolaura** [LeetCode-Feedback/LeetCode-Feedback#7620]
#### Your LeetCode username

romanolaura

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The depth of the tree [1,null,2] is 1, but the solution says that it should be 2.

#### Code you used for Submit/Run operation

```
// Two Sum
function maxDepth(root: TreeNode | null): number {
    let max = 0;
    const helper = (node: TreeNode | null): number => {
        if (node.left == null && node.left === null) {
            return 1;
        }
        let left: number = 0;
        let right: number = 0;
        if (node.left) {
            left = helper(node.left);
        }
        if (node.left) {
            right = helper(node.right);
        }
        
        let longest_branch = Math.max(left,right);
        
        return Math.max(longest_branch+1, max);
    }
    
    return helper(root);
};
```

#### Language used for code

TypeScript

**Comment by stormsunshine** [comment]
In this problem, the depth of a binary tree is defined as the number of levels in the binary tree. A binary tree with root node only has depth 1.

**Comment by romanolaura** [comment]
Thank you for your response, I realized my mistake just after I sent the
report. I'm sorry about that.

**Comment by LC-Pam** [comment]
I'm sorry we didn’t get to you sooner - but I am glad to see your issue has resolved!

Please feel free to let me know if you have any other questions or concerns.

Happy LeetCoding!
