### ISSUE TITLE
Missing Test Case - 56. Merge Intervals

### ISSUE THREAD

**Issue by stevenlai4** [LeetCode-Feedback/LeetCode-Feedback#7621]
#### Your LeetCode username
steven_lai4

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In C#, there is no such syntax for 2D array: `int [][] tempArr = new int [][];`
The correct syntax for C# for its 2D array is: `int [,] tempArr = new int [,];`
This error is returned `Cannot implicitly convert type 'int[*,*]' to 'int[][]' `

#### Code you used for Submit/Run operation

```
public class Solution {
    public int[,] Merge(int[,] intervals) {
        int[,] outerArr = new int[,] {{4,5},{1,3}};

        return outerArr;
    }
}
```

#### Language used for code
C#

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the code definition is correct and is working, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
