### ISSUE TITLE
740. Delete and Earn - same test case different result when submitting

### ISSUE THREAD

**Issue by fjiaSigmoid** [LeetCode-Feedback/LeetCode-Feedback#7622]
#### Your LeetCode username

frankjzy

#### Category of the bug
- [ ] Question
- [y] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Please see below attached screenshot - test case "[2,2,3,3,3,4]" yields different results from running code locally vs. from the submission. thanks.

#### Code you used for Submit/Run operation

```
// Delete and Earn
class Solution {
public:
    int deleteAndEarn(vector<int>& nums) {
        if (nums.size() == 1) return nums[0];
        unordered_map<int, int> m;
        int maxNum = INT_MIN;
        int dp[10001];
        for (auto& num : nums) {
            dp[num] += num;
            maxNum = max(maxNum, num);
        }
        
        for (int i = 0; i <= maxNum; i++) cout << dp[i] << ' ';
        cout << endl;
        
        for (int i = 2; i <= maxNum; i++) {
            
            dp[i] = max(dp[i] + dp[i-2], dp[i-1]);
            cout << "i: " << i << " dp[i]: " << dp[i] << endl;
        }
        
        return dp[maxNum];
    }
};
```

#### Expected behavior

test case "[2,2,3,3,3,4]" should have passed with the code above ( as shown in the screenshot below);

#### Screenshots

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/50861642/172092055-e8b9074c-ac51-404d-8243-5c7c8333b7fb.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by fjiaSigmoid** [comment]
Hi team,
thanks for the reply! I read the linked Q&A you provided however none of
the explanations fits this case:

1, there is no global / static variable used
2. The issue is not "undefined behavior" but strict wrong answer
3. As far as C++ goes, there is clearly no out-of-bound array access from
my code
 - The int array dp was set to the length of 10001, and the test case only
step through index [0, 4]

Would you be able to take a deeper look and demystify this? thanks!


Cheers,
Frank J
