### ISSUE TITLE
430. Flatten a Multilevel Doubly Linked List -same test case different result when submitting

### ISSUE THREAD

**Issue by manozjinagal** [LeetCode-Feedback/LeetCode-Feedback#7623]
#### Your LeetCode username
[manozjinagal](https://leetcode.com/manozjinagal/) 

#### Category of the bug
- [ ] Test case error 

#### Description of the bug
For written solution test case is working in custom input, but giving error in submission time for same code.

#### Code you used for Submit/Run operation
```
class Solution {
    static Node glist = new Node(0),p = glist,prv = glist,check = p;
    static List<Integer> list = new ArrayList<>();
    public Node flatten(Node head) {
        if(head == null) return null;
        pty(head);
        mkl(list);
        p.prev= null;
        return p.next;
    }
    public static List<Integer> pty(Node head){
        while(head != null)
        {
            list.add(head.val);
            if(head.child != null){
                pty(head.child);
            }
            head = head.next;
        }
        return list;
    }
    public static void mkl(List<Integer> l)
    {
        l.add(0,0);
        for(int p=1;p<l.size();p++){
            glist.child = null;
            glist.next = new Node(l.get(p));
            glist = glist.next;
            glist.prev = prv;
            prv =glist;
        }
        p.next.prev = null;
    }
}


#### Language used for code
Java


#### Expected behavior
test case **[1,2,null,3]** should have passed with the code above ( as shown in the screenshot below);


#### Screenshots
![Screenshot 2022-06-06 141211](https://user-images.githubusercontent.com/63463176/172129084-b6a05389-406f-48f2-9fc7-ed7cc6314f79.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
