### ISSUE TITLE
Missing Test Case - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by Kick933** [LeetCode-Feedback/LeetCode-Feedback#7625]
#### Your LeetCode username
LeetCode Username -: pavitrsheoran003

#### Category of the bug
- [X ] Question
- [] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Intersection of two linked list refer to the first node (including itself) onwards which all the nodes are equal.
For example, If A & B are two linked list [4,1,8,4,5] , [5,6,1,8,4,5] respectively. The example test case gives 8 as the first intersecting node instead of 1.This is the first example provided in the problem description. Thus, I marked it in question category, given wrong example.

#### Code you used for Submit/Run operation

```
var getIntersectionNode = function(headA, headB) {
    const obj = {}
    let cur = headA
    while(cur){
        obj[JSON.stringify(cur)] = cur
        cur = cur.next
    }
    cur = headB
    while(cur){
        console.log(JSON.stringify(obj[JSON.stringify(cur)]))
        if(JSON.stringify(obj[JSON.stringify(cur)]) === JSON.stringify(cur)){
            return cur
        }
        cur = cur.next
    }
    return null
};
```

#### Language used for code

JavaScript

#### Expected behavior

For two given linked list, the test case provided must have the first intersecting node be given to the judge instead of second intersecting node. Thus for [4,1,8,4,5] , [5,6,1,8,4,5] given as input linked List, the first intersecting node would be 1. That is where intersection starts instead of 8. 

#### Additional context

The example test case given is wrong in this problem.

**Comment by stormsunshine** [comment]
Why do you think all nodes must have distinct values? The image clearly shows the two linked lists. Both lists have nodes with value 1, and the two nodes with the same value are different nodes, in different lists.

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's answer.  We appreciate your support!
