### ISSUE TITLE
用例校验有问题

### ISSUE THREAD

**Issue by Lizhuotao** [LeetCode-Feedback/LeetCode-Feedback#7627]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
zhuotao

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
binary-tree-maximum-path-sum 题目的用例校验有问题，用例7通不过，必须把第四行代码取消注释才能通过。

**你使用的语言**
go

**你提交或者运行的代码**
```
var val = math.MinInt32

func maxPathSum(root *TreeNode) int {
    //  val = math.MinInt32
	getMax(root)
	return val
}

func getMax(node *TreeNode) int {
	if node == nil {
		return 0
	}

	l := max(0, getMax(node.Left))
	r := max(0, getMax(node.Right))
	val = max(val, l + r + node.Val)
	return max(l, r) + node.Val
}

func max(x, y int) int {
    if x > y {
        return x
    }
    return y
}
```

**期望行为**
没有第四行代码也可以通过用例7。

**屏幕截图**
[截图](http://img.bytelove.top/Fg6huhzqJF_JngF_O1vmHO42W3nJ)

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：可以再仔细检查并调试一下代码，具体可以参考「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
