### ISSUE TITLE
Missing Test Case - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by menkom** [LeetCode-Feedback/LeetCode-Feedback#7628]
#### Category of the bug
- [v] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Example 1 for this task we have next data
Input: intersectVal = 8, listA = [4,1,8,4,5], listB = [5,6,1,8,4,5]
Output: Intersected at '8'

For some reason Linked List intersects at 8 when it should at 1;

**Comment by IsaacSherman** [comment]
This confused me too... we're actually supposed to be comparing pointers, not values.  So it depends on what inputs you feed the judge, who creates the lists for you and actually makes the lists intersect in memory at the 8.  This is very unclear, at least to me.

**Comment by stormsunshine** [comment]
Don't you see the image in the example? The image clearly shows the two linked lists intersect at 8, not 1.

**Comment by menkom** [comment]
We have to take logic as a basis not the picture. And logic say that 1 and
1 are equal to be join point.

Test 38 with headA [2,2,4,5,4] and headB [2,2,4,5,4] looks completely equal
to me. And I expect first 2 is join point but test fails saying
intersection is at 4 (which is at position 3). Why exactly 4? Magic. This
task frustrates me.

вт, 7 июн. 2022 г., 06:03 stormsunshine ***@***.***>:

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's answer.  We appreciate your support!
