### ISSUE TITLE
【BUG】189. 轮转数组，测试用例无法通过

### ISSUE THREAD

**Issue by LeeHao12** [LeetCode-Feedback/LeetCode-Feedback#7629]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
枫叶谷

**描述**

[189. 轮转数组](https://leetcode.cn/problems/rotate-array/)

编写的代码点击提交后，无法通过测试用例，但是将没通过的测试用例在浏览器控制台中执行的结果是可以通过的。

**你使用的语言**
js

**你提交或者运行的代码**
```js
/**
 * @param {number[]} nums
 * @param {number} k
 * @return {void} Do not return anything, modify nums in-place instead.
 */
var rotate = function(nums, k) {
  // 步数
  const step =  k % nums.length 

  // 步数等于几，相当于把后几位移动到最前面

  // 前缀
  const preFix = nums.slice(nums.length - step)
  // 后缀
  const postFix = nums.slice(0,nums.length - step)
  // 返回
  return [...preFix,...postFix]
};
```

**期望行为**
点击提交后，可以通过测试用例。

**屏幕截图**
![image](https://user-images.githubusercontent.com/22903176/172276547-60876a9c-e010-4924-8ca6-2de5f4226d90.png)

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
