### ISSUE TITLE
843. Guess the Word

### ISSUE THREAD

**Issue by Amtrix** [LeetCode-Feedback/LeetCode-Feedback#7631]
#### Your LeetCode username
ferizomir

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
As it is, this task cannot be solved. Try following test case:

```
"oooooo"
["aaaaaa","bbbbbb","cccccc","dddddd","eeeeee","ffffff", "gggggg", "hhhhhh", "iiiiii", "jjjjjj", "kkkkkk", "llllll", "mmmmmm", "nnnnnn", "oooooo", "pppppp", "qqqqqq", "rrrrrr", "ssssss", "tttttt", "uuuuuu", "vvvvvv", "wwwwww", "xxxxxx", "yyyyyy", "zzzzzz"]
10
```

When I run this, I get that my solution works because the official one failed too.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Amtrix** [comment]
Any language. This will make your official solution fail.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the problem.  We appreciate your support!
