### ISSUE TITLE
Missing Test Case - 2296. Design a Text Editor

### ISSUE THREAD

**Issue by Sal-22** [LeetCode-Feedback/LeetCode-Feedback#7632]
#### Your LeetCode username
Sal_7357

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [☑️] Missing Test Cases 

#### Description of the bug

A solution that should have given in TLE in a few cases got accepted because the following test case was not probably not present among the test cases.

#### Code you used for Submit/Run operation

```
//Design a Text Editor
class TextEditor {
public:
    string curr;
    int in;
    TextEditor() {
        curr = "";
        in = -1;
    }
    
    void addText(string text) {
        curr.insert(in + 1, text);
        in += text.size();
    }
    
    int deleteText(int k) {
        int toDelete = min(in + 1, k);
        curr = curr.substr(0, in - toDelete + 1) + curr.substr(in + 1);
        in -= toDelete;
        return toDelete;
    }
    
    string cursorLeft(int k) {
        in = max(in - k, -1);
        int leftIn = max(-1, in - 10);
        int diff = in - leftIn;
        return curr.substr(leftIn + 1, diff);
    }
    
    string cursorRight(int k) {
        in = min(in + k, (int)curr.size() - 1);
        int rightIn = max(-1, in - 10);
        int diff = in - rightIn;
        
        return curr.substr(rightIn + 1, diff);
    }
};

/**
 * Your TextEditor object will be instantiated and called as such:
 * TextEditor* obj = new TextEditor();
 * obj->addText(text);
 * int param_2 = obj->deleteText(k);
 * string param_3 = obj->cursorLeft(k);
 * string param_4 = obj->cursorRight(k);
 */
```

#### Language used for code
C++

#### Expected behavior
it should've given tle for the test case when we first add a lot of strings, then do some cursorLefts and then do a lot of deleteTexts. such as for this valid test case:

https://drive.google.com/file/d/1V0Dx63V6XMFV8cxrPKXPoLZhoBbjncDL/view?usp=sharing

(can't put it in here because the body gets too long)

**Comment by LC-Pam** [comment]
Thank you for your time. The solution is already TLE. There was an issue in CN side and it was fixed.
Now, everything should be fine. We appreciate your support!
