### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by Anirban-Chand** [LeetCode-Feedback/LeetCode-Feedback#7634]
#### Your LeetCode username

```__anirban__```

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
- [x] Wrong Test Cases

#### Description of the bug

Testcase 1: **"words and 987"**,  it should return 987. Instead returning 0;
Testcase 2: **"shit4193 with words"**, it should return the integer 4193. Instead it is returning 0. This testcase is incorrect!

#### Code you used for Submit/Run operation

```
// String to Integer(atoi)
class Solution {
public:
    int myAtoi(string s) {
        string temp="";
        for(int i=0; i<s.size(); i++){
            if(s[i] == '-' and (s[i+1]>=48 and s[i+1]<=57))
                temp+=s[i];
            else if(s[i]>=48 and s[i]<=57)
                temp+=s[i];
        }
        cout<<temp<<endl;
        int ans=0;
        bool neg = temp[0]=='-';
        for(int i=neg; i<temp.size(); i++){
            ans = ans*10 + (temp[i]-'0');
        }
        return neg? ans*-1 : ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Testcase 1: It should return the integer 987.
Testcase 2: It should return the integer 4193.

#### Screenshots

![image](https://user-images.githubusercontent.com/54898566/172310647-ea57a2d7-5413-4b47-9511-699b1ae026de.png)
![image](https://user-images.githubusercontent.com/54898566/172311848-dcbb17e7-6dff-4d1b-b24c-98c34cf3628d.png)

**Comment by stormsunshine** [comment]
Please check the third step of the algorithm as follows.

> 3. Read in next the characters until the next non-digit character or the end of the input is reached. The rest of the string is ignored.

If the first character is not a digit, then all characters are ignored. Since no digits are read, the result is 0.

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's answer.  We appreciate your support!

**Comment by Anirban-Chand** [comment]
> Please check the third step of the algorithm as follows.
> 
> > 3. Read in next the characters until the next non-digit character or the end of the input is reached. The rest of the string is ignored.
> 
> If the first character is not a digit, then all characters are ignored. Since no digits are read, the result is 0.

Yes understood, appreciate your help. But for the testcase 1, it is still giving the wrong answer.
