### ISSUE TITLE
17. Letter Combinations is not accessible

### ISSUE THREAD

**Issue by mscuthbert** [LeetCode-Feedback/LeetCode-Feedback#7636]
#### Your LeetCode username

msacuthbert

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Letter Combinations is not solvable without prior knowledge of the (increasingly becoming obsolete) telephone keypad or being able to read this graphic:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Telephone-keypad2.svg/200px-Telephone-keypad2.svg.png)

However, the graphic is given in low resolution with no alternative text for users who are blind or otherwise have difficulty making out the tiny letters on a low resolution image.  Especially important because older phones omitted Q and Z, and the reader needs to see if these are present on "7" and "9".

Suggest augmenting the image with a textual description (that isn't easily copied into a HashMap/dict/etc.) such as:

```
The letters on each number are: (2) ABC, (3) DEF, (4) GHI, (5) JKL, (6) MNO, (7) PQRS, (8) TUV, (9) WXYZ.
```

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
N/A

#### Screenshots

Image as it might look to someone with visual disabilities:

<img width="396" alt="Screen Shot 2022-06-06 at 23 21 13" src="https://user-images.githubusercontent.com/3521479/172345418-ebae9658-41a4-4c82-a648-e4f36550c120.png">

#### Additional context

Accessibility is important for bringing code to everyone!  :-)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
