### ISSUE TITLE
1763. Longest Nice Substring

### ISSUE THREAD

**Issue by abhira0** [LeetCode-Feedback/LeetCode-Feedback#7637]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Ambiguous tag name

#### Expected behaviour
Mentioned SLIDING WINDOW, but its basically a brute force approach with time more than O(n)
Please remove sliding window tag from the question or if its really a sliding window problem with time complexity O(n), I request you to provide solutions

**Comment by LC-Pam** [comment]
Thank you for your time. Regarding issue 7637, we think the sliding window should be kept. This problem has a solution with time complexity O (26 * n), such as LCCN's official solution method three: https://leetcode.cn/problems/longest-nice-substring/solution/zui-chang-de-mei-hao-zi-zi-fu-chuan-by-l-4l1t/
There are other solutions that also have sliding window solutions that provide linear time complexity, such as the following solutions:
https://leetcode.cn/problems/longest-nice-substring/solution/hua-dong-chuang-kou-yydsshi-jian-fu-za-d-kizi/
https://leetcode.cn/problems/longest-nice-substring/solution/hua-dong-chuang-kou-by-ray-83m-opkh/ 
We appreciate your support!
