### ISSUE TITLE
Missing links of "Queue" and "Stack" at the conclusion of "Array and Strings" chapter

### ISSUE THREAD

**Issue by vvnezapnopwnz** [LeetCode-Feedback/LeetCode-Feedback#7638]
#### Your LeetCode username

https://leetcode.com/vvnezapnopwnz/

#### Category of the bug
- [ ] Solution

#### Description of the bug

Missing links of "Queue" and "Stack" at the conclusion of "Array and Strings" chapter
[https://leetcode.com/explore/learn/card/array-and-string/204/conclusion/1155/](url)
That learning cards was already added to the learn content
#### Code you used for Submit/Run operation
<!--

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
