### ISSUE TITLE
2295. Replace Elements in an Array

### ISSUE THREAD

**Issue by 20160245** [LeetCode-Feedback/LeetCode-Feedback#7639]
#### Your LeetCode username
keepgoingbill

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
One accepted solution seems wrong. This is the fastest submission which runs 1292 ms. The error here is that it returns an unorderly list, yet the answer should be an order list. 

#### Code you used for Submit/Run operationclass Solution:
    def arrayChange(self, nums: List[int], operations: List[List[int]]) -> List[int]:
        st = set(nums)

        for i, j in operations:
            st.remove(i)
            st.add(j)
    
        return list(st)

```

```

#### Language used for code
Python

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
This solutions get WA as expected. https://leetcode.com/submissions/detail/717571395/
