### ISSUE TITLE
Unclear Description - Problem & test cases - 1217. Play with Chips

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#764]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1217. Play with Chips
https://leetcode.com/problems/play-with-chips/

Problem & test case description is not very clear.

Some suggestions for changes are below:

Problem description - Change as below:

From: There can be two or more chips at the same position initially.
To:   There can be two or more chips at the same position initially. See example, below.

Test cases:

Example 1, change as below:
From: Explanation: Second chip will be moved to positon 3 with cost 1. First chip will be moved to position 3 with cost 0. Total cost is 1.
To:   Explanation: First chip will be moved to position 3 by 2 units to right with cost 0. Similarly Second chip will be moved to positon 3 by 1 unit to right with cost 1. So total cost is 1.

Example 2, change as below:
From: Explanation: Both fourth and fifth chip will be moved to position two with cost 1. Total minimum cost will be 2.
To:   Explanation: Both fourth and fifth chip will be moved to position two, each with cost 1, so total minimum cost will be 2.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior
Problem description should be clear.
- 867 downvotes for the question
- 135 people upvotes saying & commenting had issue with description in Discuss, see https://leetcode.com/problems/play-with-chips/discuss/398329/Not-understanding-the-problem

I have solved this problem, after reading for 5 times. For an Easy problem, the description is not sufficient.
Please add more details. Some suggestions are given in above 'Description of the bug'.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by manoharreddyporeddy** [comment]
Thanks

Title of this problem changed
so URL is now https://leetcode.com/problems/minimum-cost-to-move-chips-to-the-same-position/

Since the description is better now:
- Reduce the downvotes a bit less than upvotes (make downvotes to 200 compared to upvotes 208) ?
- Because 913 downvotes does not correctly reflect the new better description
