### ISSUE TITLE
1873. Calculate Special Bonus

### ISSUE THREAD

**Issue by Kanjirito** [LeetCode-Feedback/LeetCode-Feedback#7641]
#### Your LeetCode username
Kanjirito

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question says to order the output by `employee_id` but doing so will fail. The example also shows the results being ordered.
Slightly related is also the fact that the example case shown in the question is not the same as the one given as test input.
This was probably caused in some way by fixing #7605

#### Code you used for Submit/Run operation
```MySQL
SELECT employee_id, 
CASE
    WHEN employee_id % 2 != 0 and name NOT LIKE "M%" THEN salary
    ELSE 0
END as bonus
FROM Employees
ORDER BY employee_id;
```

#### Language used for code
MySQL

#### Expected behavior
The above code should pass but doesn't because the answer is expected to be unordered.

#### Screenshots
![image](https://user-images.githubusercontent.com/49487896/172422058-5cdd7448-f993-4ac8-9790-99a169b5a81c.png)
![image](https://user-images.githubusercontent.com/49487896/172422315-b2223d67-1b0c-4913-9455-7d8dcb8083b6.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
