### ISSUE TITLE
Suggested Test Case for 239. Sliding Window Maximum

### ISSUE THREAD

**Issue by imkmmk** [LeetCode-Feedback/LeetCode-Feedback#7642]
https://leetcode.com/problems/sliding-window-maximum/

I suggest adding a test case like:

[9,8,9,8]
3

Because the fastest answers fail this test case.

**Comment by imkmmk** [comment]
Language: Python3

Code`
### I (imkmmk) copied this from the fastest answers.
### This test case fails:
### ([9,8,9,8], 3)

class Solution:
    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:
        left = 0
        res = []
        curMax = max(nums[:k])
        res.append(curMax)
        
        for r in range(k, len(nums)):
            left +=1
            # if the curMax was the left pointer value that we incremented
            if curMax == nums[left-1]:  
                # if current left >= what would be next max value i.e. 1 less currMax
                if nums[left] >= curMax-1:                  
                    curMax = nums[left]
                else:           # recalculate curMax
                    curMax = max(nums[left:r+1])
            # if the previous left pointer was not the curMax then it would either be nums[r] or               the existing curMax
            curMax = curMax if curMax > nums[r] else nums[r]
            res.append(curMax)
        return res
            
        
        
        '''l=r=0
        q = collections.deque()  # to save index
        output = []
        
        while r < len(nums):
            # pop smaller values from the right if lower than nums[r]
            while q and nums[q[-1]] < nums[r]:
                q.pop()
            q.append(r)
           
            # remove left vals from q, when l is moved for the window
            if l > q[0]:
                q.popleft()
            if (r+1) >= k:          # if window length is k, append result and inc l
                output.append(nums[q[0]])
                l +=1
            r +=1
        return output'''
`

It outputs [9,8] but the answer is [9,9].

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
