### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by mohdsaquib93** [LeetCode-Feedback/LeetCode-Feedback#7643]
#### Your LeetCode username

mohd16034

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

These are the conditions given:
0 <= m, n <= 200
1 <= m + n <= 200

These conditions are a bit ambigous and maybe incorrect.

#### Expected behavior

If m and n can both be 0, shouldn't 0 <= m + n instead of 1 <= m + n
Also, m and n can reach 200, shouldn't m + n <= 400

If this is the desired behaviour, still language is a bit ambiguous.

**Comment by stormsunshine** [comment]
If the case is as you mentioned, then the constraint 1 <= m + n <= 200 should be removed. However, this constraint is necessary.

Having m + n >= 1 means that either m > 0 or n > 0, which means that m = n = 0 is not allowed. Having m + n <= 200 means that the sum of m and n is at most 200, which means that cases such as m = 200 and n = 200 are not allowed.

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's answer.  We appreciate your support!
