### ISSUE TITLE
Typo - 13. Roman to Integer

### ISSUE THREAD

**Issue by imashnake0** [LeetCode-Feedback/LeetCode-Feedback#7644]
#### Your LeetCode username
imashnake_

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
**Grammar error:** 
> For example, 2 is written as II in Roman numeral, just two **one's** added together.

Here, "one's" should be "ones".

#### Code you used for Submit/Run operation
N/A.

#### Language used for code
N/A.

#### Expected behavior
N/A.

#### Screenshots
N/A.

#### Additional context
N/A.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
