### ISSUE TITLE
Missing Test Case - 304. Range Sum Query 2D - Immutable

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#7645]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Validator cannot process correct testcase.

```
m = 200
n = 200
matrix = {Every row consists of 124 (+100000) and then 76 (-100000)}
```

Total sum is 960000000, so it is correct testcase.

[304 Range Sum Query 2D - Immutable - testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8856754/304.Range.Sum.Query.2D.-.Immutable.-.testcase.txt)

#### Code you used for Submit/Run operation

```
public class NumMatrix 
{
    private int[][] _sum;

    public NumMatrix(int[][] matrix) 
    {
        _sum = Enumerable.Range(0, matrix.Length + 1).Select(i => new int[matrix[0].Length + 1]).ToArray();
        
        for (int i = 1; i < _sum.Length; ++i) 
            for (int j = 1; j < _sum[i].Length; ++j) 
                _sum[i][j] = matrix[i - 1][j - 1] + _sum[i - 1][j] + _sum[i][j - 1] - _sum[i - 1][j - 1];
    }
    
    public int SumRegion(int row1, int col1, int row2, int col2) 
        => (int)(_sum[row2 + 1][col2 + 1] + _sum[row1][col1] - _sum[row1][col2 + 1] - _sum[row2 + 1][col1]);
}
```

#### Language used for code

C#

#### Expected behavior

Description of the task should be changed. Or validator should be changed. Because current behavior is not correct.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem:
1. Updated constraints of max(arr[i]) (from 1e5 to 1e4)
2. Changed validator
3. Added 2 max tests
4. Added the generator used for them
 Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
