### ISSUE TITLE
Error in description - 607. Sales person (SQL)

### ISSUE THREAD

**Issue by SA1CA1** [LeetCode-Feedback/LeetCode-Feedback#7646]
#### Your LeetCode username

saarangagarwal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the description for orders table,
it should be: (ERROR MARKED IN BOLD)

Table: Orders

+-------------+------+
| Column Name | Type |
+-------------+------+
| order_id    | int  |
| order_date  | date |
| com_id      | int  |
| sales_id    | int  |
| amount      | int  |
+-------------+------+
order_id is the primary key column for this table.
com_id is a foreign key to com_id from the Company table.

**ERROR LINE BELOW**
sales_id is a foreign key to **com_id** sales_id from the SalesPerson table. (ERROR HERE MARKED IN BOLD- should be sales_id instead of com_id)
**ERROR LINE ABOVE**

Each row of this table contains information about one order. This includes the ID of the company, the ID of the salesperson, the date of the order, and the amount paid.

#### Code you used for Submit/Run operation

```

```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
