### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by walnut07** [LeetCode-Feedback/LeetCode-Feedback#7647]
#### Your LeetCode username

walnut07

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

Concisely, it's about a bug in a test case. 

#### Description of the bug

A wrong answer is expected. When the input is "dvdf", the longest substring without repeating is "dv" or "df". Therefore the expected answer should be 2, which is the length of "dv" or "df". However, LeetCode says 3 is the expected answer and doesn't accept my solution. My code below outputs 2.

#### Code you used for Submit/Run operation

```python
class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:
        curr_ans = count = 0
        hashset = set()

        for char in s:
            if char not in hashset:
                count += 1
                hashset.add(char)
            else:
                curr_ans = max(curr_ans, count)
                count = 1
                hashset = set(char)

        if count > curr_ans:
            return count 

        return curr_ans
```

#### Language used for code
Python

#### Expected behavior

It should accept 2 as an answer.

#### Screenshots

<img width="1280" alt="スクリーンショット 2022-06-08 11 07 21" src="https://user-images.githubusercontent.com/90857923/172515854-d4b339f9-3bb7-46d6-8a15-0ad84d8d30b9.png">

**Comment by stormsunshine** [comment]
You are talking about subsequence, not substring. A substring must be contiguous, so the correct answer is 3.

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's answer.  We appreciate your support!

**Comment by mtlacreta** [comment]
Even though some answered the question as to why its 3 it seems like pretzel logic to me. You can justify anything.
