### ISSUE TITLE
1037 BUG

### ISSUE THREAD

**Issue by suntea233** [LeetCode-Feedback/LeetCode-Feedback#7648]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
lxxx

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
d3是(-1)/(-2)，应该得到0.5，但是得到的是0

**你使用的语言**
python

**你提交或者运行的代码**
```
// 有效的回旋镖
class Solution(object):
    def isBoomerang(self, points):
        """
        :type points: List[List[int]]
        :rtype: bool
        """
        x1,y1 = points[0]
        x2,y2 = points[1]
        x3,y3 = points[2]
        d1,d2,d3 = 0,0,1e+3
        if x1-x2 != 0:
            d1 = (y1-y2)/(x1-x2)
        if x2-x3 != 0:
            d2 = (y2-y3)/(x2-x3)
        if x1-x3 != 0:
            d3 = (y1-y3)/(x1-x3)
        if d1==d2 or d2==d3 or d1==d3 or d1==0 or d2==0 or d3==0:
             return False
        return True
```

**期望行为**
d3 = 0.5

**屏幕截图**
![image](https://user-images.githubusercontent.com/59692513/172521175-0a206b5b-e17d-4864-acf0-ffe41d891369.png)
![image](https://user-images.githubusercontent.com/59692513/172521206-3400b9f0-ee38-4caf-97ab-c1161e454ab5.png)

**额外的上下文**
在本机电脑上的得到的是True，而leetcode得出的是False

**Comment by stormsunshine** [comment]
你使用的是Python2，不是Python3，Python2中的除法默认为整数除法。如果在Python3环境运行则可以得到正确的结果。

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's answer.  We appreciate your support!
