### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by DrShengPeng** [LeetCode-Feedback/LeetCode-Feedback#7649]
#### Your LeetCode username
shengp

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Some solutions are relying on the sorted nature of the `edges` array by the first vertex.

#### Language used for code
Java

#### Expected behavior
Just by shuffling the `edges` array, some passing solutions would fail.
Existing test case:
```
4
[[0,2],[0,3],[1,2]]
[false,true,false,false]
```

ADD test case:
```
4
[[1,2],[0,3],[0,2]]
[false,true,false,false]
```

#### Screenshots
A passing solution fails on the added test case:
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
  at line 20, Solution.minTime
  at line 54, __DriverSolution__.__helper__
  at line 90, __Driver__.main
```

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
