### ISSUE TITLE
1029. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by Cassandra-d** [LeetCode-Feedback/LeetCode-Feedback#765]
#### Your LeetCode username
cassandrad

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Description of the task says:

> If two nodes have the same position, then the value of the node that is reported first is the value that is smaller.

Also, an example of input and output says:
![image](https://user-images.githubusercontent.com/2866070/89640428-36037600-d8b8-11ea-956a-f9bec0805df4.png)

When I submit the code there is a test with the input:
 
> [0,5,1,9,null,2,null,null,null,null,3,4,8,6,null,null,null,7]

That expects the output:

> [[9,7],[5,6],[0,2,4],[1,3],[8]]

#### Language used for code
C#

#### Expected behavior
The question is: why the first tuple is [9, 7] in expected output and not [7, 9]? Looks like, according to description, the smallest number should go first.

#### Screenshots

![image](https://user-images.githubusercontent.com/2866070/89640699-c8a41500-d8b8-11ea-947e-440aa443220c.png)

#### Additional context
[Submission link](https://leetcode.com/submissions/detail/377406324/?from=/explore/challenge/card/august-leetcoding-challenge/549/week-1-august-1st-august-7th/3415/)

**Comment by mohitsvnit** [comment]
Please read below statement from a question
`Running a vertical line from X = -infinity to X = +infinity, whenever the vertical line touches some nodes, we report the values of the nodes in order from top to bottom (decreasing Y coordinates).`

You have to sort the result on the bases of 2 parameters. 
1. Y position (small to large)
2. If Y position is the same, then by value. 

In your failed test case, 9 is at lower Y position (i.e Y position of root is 0 and increase as we go down) then 7, so it comes first. 

Hope you understood my point.

**Comment by Cassandra-d** [comment]
@mohitsvnit 
Thanks! Now I understand and have no more questions.
Existing description of condition with vertical line is really confusing. Your list with two conditions gives better understanding of restrictions IMHO.
