### ISSUE TITLE
测试用例不全

### ISSUE THREAD

**Issue by Lizhuotao** [LeetCode-Feedback/LeetCode-Feedback#7652]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
zhuotao

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
zui-xiao-de-kge-shu-lcof  这个题我想用堆排序来解，但是在堆排序算法有问题的情况下通过了测试用例。

**你使用的语言**
go

**你提交或者运行的代码**
```
func getLeastNumbers(arr []int, k int) []int {
    heapSort(arr)
    return arr[:k]
}

func heapSort(arr []int){
	var heapify = func(a []int, root, end int) {
		for {
			child := root*2 + 1
			if child > end {
				return
			}
			if child+1 < end && a[child] < a[child+1] {
				child++
			}
			if a[root] > a[child] {
				return
			}
			a[root], a[child] = a[child], a[root]
			root = child
		}
	}

	end := len(arr) - 1
	for i := end / 2; i >= 0; i-- {
		heapify(arr, i, end)
	}
	for i := end; i >= 0; i-- {
		arr[0], arr[i] = arr[i], arr[0]
		end--
		heapify(arr, 0, end)
	}
	return
}
```

**期望行为**
增加测试用例 arr = [2, 1, 4], k = 2，这样我这个错误的代码就过不了了。当前错误的堆排序算法输入[2, 1, 4] 会返回 [1, 4, 2]。

**屏幕截图**
![截图](http://img.bytelove.top/Ft8jo-yVwNWKm-AP7vjofNBILjBS)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：zhuotao 给予积分奖励，请查收。
