### ISSUE TITLE
Spelling and Formatting Issue - 68. Text Justification

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#7655]
#### Your LeetCode username
RohitSgh

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
- In Problem Description **Note**, the second note should have `maxWidth` instead of maxWidth. 
- In **Explanation** of **Example 2**, there is a sentence `Note that the second line is also left-justified becase it contains only one word.` It should be `because` instead of `becase`.

#### Expected behavior

- In Problem Description **Note**, the second note should have `maxWidth` instead of maxWidth. 
- In **Explanation** of **Example 2**, there is a sentence `Note that the second line is also left-justified becase it contains only one word.` It should be `because` instead of `becase`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
