### ISSUE TITLE
Missing Test Case - 1770. Maximum Score from Performing Multiplication Operations

### ISSUE THREAD

**Issue by goffygoo** [LeetCode-Feedback/LeetCode-Feedback#7657]
#### Your LeetCode username

https://leetcode.com/top_text/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
A test case is missing in the question - 1770. Maximum Score from Performing Multiplication Operations
The missing test case corresponds to the Dynamic programming solution of the problem

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int help(vector<int>& nums, vector<int>& mul,vector<vector<int>>&dp,int x, int y){
        int m = mul.size() , n = nums.size();
        if(x+y == m) return 0;
        if(dp[x][y]!=-1) return dp[x][y];
        int a = help(nums , mul, dp , x+1 , y) + mul[x+y]*nums[x];
        int b = help(nums , mul, dp , x, y+1) + mul[x+y]*nums[n-1-y];
        return dp[x][y] = max(a , b);
    }
    
    int maximumScore(vector<int>& nums, vector<int>& mul) {
        int m = mul.size() , n = nums.size();
        vector<vector<int>>dp(m+1 , vector<int>(m+1 , -1));
        return help(nums , mul , dp , 0 , 0);
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
TLE (, but current verdict is AC) 

#### Missing Testcase
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]

#### Explanation
In the above solution, the writer has used -1 to mark the unvisited states in DP, which is wrong because there might be some states in table whose actual product score might be -1 but we still are computing those states.
The solution to the above problem might be the taking INT_MIN as the unvisited state because under no circumstance INT_MIN will be the score of any state given the constraints.

#### Screenshots
![image](https://user-images.githubusercontent.com/67953525/172624610-56538dfe-ed90-4719-a400-43ac9d9b594e.png)

By the way even your servers ain't able to give the expected answer to the test, so I advise you might even have to change your internal code too.

#### Additional context

The wrong solution which got AC:
https://leetcode.com/submissions/detail/715569355/

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
