### ISSUE TITLE
497 题目描述错误

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#7659]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [ ] 题目

**描述**
示例的输入输出、解释不是讲同一测试用例。
![image](https://user-images.githubusercontent.com/25954059/172662747-22ae0af9-6539-4ce9-8dc3-2f0be71ad114.png)

**期望行为**
调整输入输出，或者调整解释。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：hhummingg 给予积分奖励，请查收。
