### ISSUE TITLE
336. 回文对

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#766]
** Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
官方题解中方法一的时间复杂度分析有疑问，为什么是$O(m^2)$地寻找其所有前缀与后缀是否在给定的字符串序列中出现，哈希表查询的平均时间复杂度是$O(1)$吧，长度为m的字符串，应该是$O(m)$的复杂度吧。

**你使用的语言**
Python

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
该题目技术验证没有问题的，因为每个字符串最多要查 O(m) 次哈希表。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路。

**Comment by Ijustwantyouhappy** [comment]
。。。你自己都说了“每个字符串最多要查 O(m) 次哈希表”，而哈希表查询的平均时间复杂度为O(1)，怎么就能得到官方题解里说的“并$O(m^2)$地寻找其所有前缀与后缀是否在给定的字符串序列中出现”了呢，令我费劲，可否再讲细一点。

**Comment by feiceh** [comment]
哈希表的 key 是字符串，后续刷题学习中遇到困难，可通过阅读「题解」和「评论」解决做题中的一些困惑，看看其他小伙伴的解题思路。

**Comment by Ijustwantyouhappy** [comment]
所以呢，哈希表的key是字符串会影响查询的平均时间复杂度不是$O(1)$吗？

**Comment by feiceh** [comment]
那当然。要想 hash 一个字符串至少得先把字符串遍历一遍吧？hash 一个长度为 1000000 的字符串，复杂度难道是 O(1) ?

**Comment by Ijustwantyouhappy** [comment]
哦，有道理，我之前的角度想错了，对于长度为n的哈希表而言，查询确实是O(1)，但是对于被查的长度为m的字符串而言，最坏确实要到O(m)，明白了，多谢。
