### ISSUE TITLE
Missing Test case in 1626. Best Team With No Conflicts

### ISSUE THREAD

**Issue by anuKnight** [LeetCode-Feedback/LeetCode-Feedback#7661]
#### Your LeetCode username

anuragy3840

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing Test Cases

#### Description of the bug

Test case is missing due to which wrong code gets accepted

#### Code you used for Submit/Run operation

```
// 1626. Best Team With No Conflicts
class Solution {
public:
    int bestTeamScore(vector<int>& scores, vector<int>& ages) {
        int dp[ages.size()];
        
        int ans=1;
        
        vector<pair<int,int>> a;
        
        for(int i=0;i<ages.size();i++){
            a.push_back({ages[i],scores[i]});
        }
        sort(a.begin(),a.end());
        dp[0]=a[0].second;
        for(int i=1;i<ages.size();i++){
            int val=0;
            for(int j=0;j<i;j++){
                
                if(a[j].second<=a[i].second || a[i].first==a[j].first)
                    val=max(val,dp[j]);
            }
            dp[i]=val+a[i].second;
            ans=max(ans,dp[i]);
        }
        
        return ans;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

for test case 
[100]
[1]

answer must be 100 but my code gives 1 still my code is accepted 

this test case is missing

#### Screenshots

![image](https://user-images.githubusercontent.com/67221668/172675231-491b7929-26e4-4815-879e-eda5ae2d5c62.png)
![image](https://user-images.githubusercontent.com/67221668/172675254-54a0b135-c2f7-405a-bcf6-c88f35763523.png)

**Comment by anuKnight** [comment]
Missing test case in 1626. Best Team With No Conflicts https://leetcode.com/problems/best-team-with-no-conflicts/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
