### ISSUE TITLE
Missing Test Case - 1332. Remove Palindromic Subsequences

### ISSUE THREAD

**Issue by hemantsoni480** [LeetCode-Feedback/LeetCode-Feedback#7664]
Missing Test case

#### LeetCode username
hemantsoni480

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
A test case is purely missing in this solution code 
test case is -> "baabba"
according to question output will be 3 of this test case but according to solution output is 2

#### Code you used for Submit/Run operation

```
// Remove Palindrome Subsequences
class Solution {
public:
    bool isPali(string s){
            int i =0;
            int j= s.size()-1;
            while(i<=j){
                if(s[i]!=s[j]) return false;
                i++;
                j--;
            }
            return true;
        }
    int removePalindromeSub(string s) {
        
        if(isPali(s)) return 1;
        return 2;
    }
};
```

#### Language used for code
C++

#### Expected behaviour
If I use this code and according to question test case generate output - 3 
but according to given solution output will be 2

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.
The question says "In a single step you can remove one palindromic subsequence from s." Subsequence could be discontinuous.
baabba -> bbb ->""
