### ISSUE TITLE
Missing Test Case - 169. Majority Element

### ISSUE THREAD

**Issue by AnkitJha2000** [LeetCode-Feedback/LeetCode-Feedback#7665]
#### Your LeetCode username

knightbar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ #] Missing Test Cases 

#### Description of the bug

when I run loop from start to end it gives TLE on big test cases, but when I run the loop from end to start it gets submitted.

#### Code you used for Submit/Run operation

```
// this code gives tle
class Solution {
public:
    int majorityElement(vector<int>& nums) {
        int ans;
        int n = nums.size();
        for(int i=0;i<n;i++)
        {
            int temp = 0;
            for(int j=0;j<n;j++){
                if(nums[i] == nums[j]) temp++;
            }
            if(temp > n/2) return nums[i];
        }
        return 0;
    }
};
```
```
// this code gets submitted but just in reverse
class Solution {
public:
    int majorityElement(vector<int>& nums) {
        int ans;
        int n = nums.size();
        for(int i=n-1;i>=0;i--)
        {
            int temp = 0;
            for(int j=0;j<n;j++){
                if(nums[i] == nums[j]) temp++;
            }
            if(temp > n/2) return nums[i];
        }
        return 0;
    }
};
```

#### Expected behavior

the second code should not have run and should've given me TLE but instead it got submitted because of test cases 41 to 43.

#### Screenshots

// when code gives tle
https://im.ge/i/rkSr6S

// when code gets submitted
https://im.ge/i/rkSOl6

#### Additional context

Can you please add test cases same as 41 to 43 but in descending order.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
