### ISSUE TITLE
Missing Test Case - 653. Two Sum IV - Input is a BST

### ISSUE THREAD

**Issue by sudevdhali** [LeetCode-Feedback/LeetCode-Feedback#7668]
#### Your LeetCode username
newbiesd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+ ] Missing Test Cases 

#### Description of the bug
for the testcase-
[5,3,6,2,4,null,7]
10
it should return false, but compiler is returning true.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    TreeNode* head;
    TreeNode* ist(TreeNode* root,int k){
        if(root==nullptr) return nullptr;
        if(root->val==k) return root;
        else if(root->val>k) return ist(root->left,k);
        return ist(root->right,k);
    }
    bool findTarget(TreeNode* root, int k) {
        if(head==nullptr) head=root;
        if(root==nullptr) return false;
        TreeNode* temp=ist(head,k-root->val);
        if(temp!=nullptr&&temp!=root) return true;
        return findTarget(root->left,k)||findTarget(root->right,k);
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
it should return false as there is not 2 5's

**Comment by LC-Pam** [comment]
Thank you for your time. 

3 + 7 = 10

We appreciate your support!

**Comment by sudevdhali** [comment]
When will I get the 100 leetcoins?
