### ISSUE TITLE
Missing Test Case - 988. Smallest String Starting From Leaf

### ISSUE THREAD

**Issue by Karandeep1234** [LeetCode-Feedback/LeetCode-Feedback#7669]
#### Your LeetCode username

Karandeep1234

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code gives WA on following testcase but still giving AC on submission.

Testcase:
[5,25]

#### Code you used for Submit/Run operation

```
class Solution {
    public String smallestFromLeaf(TreeNode root) {
        String s=""+(char)('a'+root.val);
        if(root.left==null && root.right==null) return s;
        
        solve(root,"");
        return ans;
    }
    String ans="z";
    public void solve(TreeNode root,String str){
        String s=""+(char)('a'+root.val);
        str=s+str;
        if((root.left==null && root.right==null)){
            
            if(ans.compareTo(str)>0){
                ans=str;
            }
            return;
        }
        if(root.left!=null){
            solve(root.left,str);
        }
        if(root.right!=null){
            solve(root.right,str);
        }
    }
}
```

#### Language used for code

Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
