### ISSUE TITLE
944. 删列造序 题目描述不清楚

### ISSUE THREAD

**Issue by bruce2014** [LeetCode-Feedback/LeetCode-Feedback#767]
** Bug 类型**
- [ ] 题目944
- [ ] 题解
- [ ] 编程语言

**描述**
题目描述错误， 非降序应该是整列非降序， 题目中 实例1  b->a->h  能算降序列？  h明明大于a ，怎么能说降序呢？

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
您好，该题目技术验证没有问题的，请仔细阅读理解题目意思。题里面那句话是：若选择 D = {}，那么 A 的列 ["b","a","h"] 就不是非降序排列了，没人说 ["b","a","h"] 是降序。

**Comment by bruce2014** [comment]
@feiceh 请你也再看下题目， 大多数人都理解错，难道不看看。“使 A 中剩余的每一列都是 非降序 排列的”
首先全集 是{升序(包括元素有相等的），降序（包括元素有相等的），乱序（有升有降）}， 题目要求使A中剩余的都是非降序， 那A中应该包含升序和乱序，乱序的不应该删除，但从结果看其实期望把乱序的也删除了。   题目根本就没考虑乱序，不符合常人表达思维。

**Comment by feiceh** [comment]
这是个基本功啊，通常情况下，应该正确的理解：
1,2,3,4,5,.:递增排列
9,8,7,6,5.:递减排列
1,2,3,3,4,5,8,8,.:非递减排列
9,8,7,7,6,5,5,2,1,.:非递增排列
虽然是非降序，但是这里其实没有乱序什么事
递增 -> 升序，递减 -> 降序
