### ISSUE TITLE
Bug 
Error in line 7 where I cannot find any errors 

### ISSUE THREAD

**Issue by MyAzzaAccount** [LeetCode-Feedback/LeetCode-Feedback#7672]
- [![Screenshot_20220610-011725_Chrome.jpg](https://user-images.githubusercontent.com/49996501/172960660-0cf830ca-7b3d-4d36-b2a0-f1c5769a7960.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
