### ISSUE TITLE
Missing Test Case - 2193. Minimum Number of Moves to Make Palindrome

### ISSUE THREAD

**Issue by liuwctrl** [LeetCode-Feedback/LeetCode-Feedback#7673]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The test case that you use.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
