### ISSUE TITLE
The code editor question does not match the written question

### ISSUE THREAD

**Issue by drewg2009** [LeetCode-Feedback/LeetCode-Feedback#7674]
drewg2009

#### Category of the bug
- [ ] Question

#### Description of the bug

When loading questions, the code editor is displaying the wrong function name and code. Therefore I can't solve the problem.

#### Expected behavior

The question should load the right code in the editor for the question. It was doing it but now it's not.

#### Screenshots

![screencapture-leetcode-explore-interview-card-wix-engineering-651-arrays-and-strings-4159-2022-06-08-18_22_19](https://user-images.githubusercontent.com/12537806/172970706-dea49fee-5df1-4aab-ad23-0fdf2429f8f7.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by drewg2009** [comment]
https://leetcode.com/explore/interview/card/wix-engineering/651/arrays-and-strings/4159/ <https://leetcode.com/explore/interview/card/wix-engineering/651/arrays-and-strings/4159/> 

Also it’s doing it for other problems.

**Comment by LC-Pam** [comment]
Thank you for your time. The problem that you mentioned already fixed. 
We appreciate your support!

**Comment by LC-Pam** [comment]
<img width="1322" alt="Screen Shot 2022-06-27 at 1 58 52 AM" src="https://user-images.githubusercontent.com/103138242/175869787-0796aa0f-61a3-4f1e-a0fe-2a66fed20ee5.png">
