### ISSUE TITLE
Stack-overflow error - 1258. Synonymous Sentences

### ISSUE THREAD

**Issue by lihing1994** [LeetCode-Feedback/LeetCode-Feedback#7685]
Programming Language: C++

Error: 
AddressSanitizer: stack-overflow on address 0x7fff1c0b2f68 (pc 0x0000002b9ff0 bp 0x7fff1c0b37d0 sp 0x7fff1c0b2f70 T0)

Test case: 
[["happy","joy"],["happy","joy"],["happy","joy"],["happy","joy"],["happy","joy"],["sad","sorrow"],["joy","cheerful"]]
"I am happy today but was sad yesterday"

**Comment by lihing1994** [comment]
`class Solution {
public:
    vector<string> generateSentences(vector<vector<string>>& synonyms, string text) {
        // Graph : dfs
        std::vector<std::string>result;
        std::vector<std::string>arr;
        std::unordered_map<std::string,std::unordered_set<std::string>>adj_list;
        for(int i=0;i<(int)synonyms.size();i++){
            std::string first = synonyms[i][0];
            std::string second = synonyms[i][1];
            adj_list[first].insert(second);
            adj_list[second].insert(first);
        }
        while((int)text.length()){
            int splite_pos = text.find(' ');
            if(splite_pos!=-1){
                arr.push_back(text.substr(0,splite_pos));
                text = text.substr(splite_pos+1);
            }
            else{
                arr.push_back(text);
                break;
            }
        }
        dfs(arr,0,"",adj_list,result);
        std::sort(result.begin(),result.end());
        return result;
    }
    void dfs(const std::vector<std::string>&arr,int pos,std::string temp, std::unordered_map<std::string,std::unordered_set<std::string>>&adj_list,std::vector<std::string>&result){
        if(pos == (int)arr.size()) {
            temp.pop_back();
            result.push_back(temp);
        }
        else{
            std::string current = arr[pos];
            std::unordered_set<std::string>visited;
            std::vector<std::string>children;
            dfs_helper(current,adj_list,visited,children);
            for(int i=0;i<(int)children.size();i++){
                dfs(arr,pos+1,temp+children[i]+" ",adj_list,result);
            }
        }
    }  
    void dfs_helper(const std::string& current,std::unordered_map<std::string,std::unordered_set<std::string>>&adj_list,std::unordered_set<std::string>&visited,std::vector<std::string>&children){
        if(visited.find(current)!=visited.end()) return;
        else{
            children.push_back(current);
            visited.insert(current);
            if(adj_list.find(current)!=adj_list.end()){
                for(auto it =adj_list[current].begin();it!=adj_list[current].end();it++){
                    std::string next = *it;
                    dfs_helper(next,adj_list,visited,children);
                }
            }
        }
    }
};`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Added a constraint that the pairs are unique and rejected this test case. We appreciate your support!
