### ISSUE TITLE
Wrong problem description in 1541

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#769]
Problem description in https://leetcode.com/problems/minimum-insertions-to-balance-a-parentheses-string/ does not mention anything about not being able to merge brackets

"(()))(()))()())))" expected is 4 but according to problem statement it can be 1

See https://leetcode.com/problems/minimum-insertions-to-balance-a-parentheses-string/discuss/780043/How-output-of-%22(()))(()))()())))%22-is-4-and-not-1 for further discussion.

**Comment by lc-ivan** [comment]
Hi @snehasishroy  ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @snehasishroy ,
Could you please provide your LeetCode account username?

**Comment by snehasishroy** [comment]
Hello @lc-ivan , my leetcode username is chrisgriffin.
https://leetcode.com/chrisgriffin

Thank you.

**Comment by lc-ivan** [comment]
Hi @snehasishroy ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
