### ISSUE TITLE
673. Number of Longest Increasing Subsequence - Bug in example 2

### ISSUE THREAD

**Issue by Vinayaka2k** [LeetCode-Feedback/LeetCode-Feedback#7690]
#### Category of the bug
- [Y] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the explanation of second example, it is stated that: 
**The length of longest continuous increasing subsequence is 1, and there are 5 subsequences' length is 1, so output 5.**

But, the word **continuous** shouldn't be present as we are only finding longest increasing subsequence. And adding the word
gives a misleading example that we are trying to find longest continuous increasing subsequence 

The  explanation of 2nd example must be:
**The length of longest increasing subsequence is 1, and there are 5 subsequences' length is 1, so output 5.**

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
