### ISSUE TITLE
403 某个测试用例运行不符合预期

### ISSUE THREAD

**Issue by MISTAKKE** [LeetCode-Feedback/LeetCode-Feedback#7691]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名   qinxianglin

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
https://leetcode.cn/problems/frog-jump/
测试用例 [0,1,2,3,4,8,9,11] 在本地运行为false但是在平台运行为true

**你使用的语言**
C++

**你提交或者运行的代码**
``` c++
class Solution {
  public:
    bool canCross(vector<int>& stones) {
        int n = stones.size();
        vector<vector<bool>> dp(n, vector<bool>(n + 1, false));
        dp[0][0] = true;  //此处的0代表着，他后续只能跳 -1 0 1步
        for (int i = 1; i < n; ++i) {
            for (int j = 0; j < i; ++j) {
                int gap = stones[i] - stones[j];
                // i=1 j=0 gap=0
                dp[i][gap] = dp[j][gap - 1] || dp[j][gap] || dp[j][gap + 1];
                if (dp[n - 1][gap]) {
                    return true;
                }
            }
        }
        return false;
    }
};

```

**期望行为**
期望运行为false

**屏幕截图**
![image](https://user-images.githubusercontent.com/25926258/173100153-fdc2f408-cbe0-4047-8fd4-ee2d2518b68a.png)

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by BrambleWave** [comment]
2. 你好，当前题目描述已更新，ID：qinxianglin 给予积分奖励，请查收。
