### ISSUE TITLE
Incorrect article line in Binary Tree explore card

### ISSUE THREAD

**Issue by PavanRajkumar** [LeetCode-Feedback/LeetCode-Feedback#7693]
#### Your LeetCode username

PavanRajkumar99

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Article

#### Description of the bug

In the "Traverse a Tree" Section of the Binary Tree Explore card, under the "Level-order Traversal - Introduction" article here https://leetcode.com/explore/learn/card/data-structure-tree/134/traverse-a-tree/990/. The last line reads "If you are not so familiar with the queue, you can find more information about that in another card coming soon."  

However the Queues and Stacks explore card is already out at https://leetcode.com/explore/learn/card/queue-stack/ and is available. "Coming soon" should ideally be replaced with a link to the Queues explore card.

#### Screenshots

![image](https://user-images.githubusercontent.com/21034769/173136020-f83c7e96-7a23-4f11-8768-0ce9a6ed1d01.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
