### ISSUE TITLE
14. Longest Common Prefix missing test cases

### ISSUE THREAD

**Issue by Gkao03** [LeetCode-Feedback/LeetCode-Feedback#7694]
#### Your LeetCode username
gkao03

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My written solution fails some of my custom test cases, but when submitting the final code, leetcode accepts the answer as correct.

#### Code you used for Submit/Run operation

```
class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        if len(strs) == 1:
            return strs[0]
        
        max_str_idx = 0
        
        first_str = strs[0]
        second_str = strs[1]
        
        for i, tup in enumerate(zip(first_str, second_str)):
            if tup[0] == tup[1]:
                max_str_idx += 1
            else:
                break
        
        max_str_idx -= 1
                
        strs_idx = 1
        while strs_idx < len(strs) - 1:
            if max_str_idx < 0:
                break
            
            str1 = strs[strs_idx]
            str2 = strs[strs_idx + 1]
            
            max_str_idx = min(max_str_idx, len(str1) - 1, len(str2) - 1)
            
            while max_str_idx >= 0:
                if str1[max_str_idx] != str2[max_str_idx]:
                    max_str_idx -= 1
                else:
                    break
            
            strs_idx += 1
                    
        if max_str_idx < 0:
            return ""
            
        # last check with last 2 strings
        first_str = strs[-2]
        second_str = strs[-1]
        
        res_str_idx = 0
        
        while res_str_idx <= max_str_idx:
            if first_str[res_str_idx] == second_str[res_str_idx]:
                res_str_idx += 1
        
        prefix = first_str[:res_str_idx]
        
        return prefix
```

#### Language used for code
Python3

#### Expected behavior

I expected this code to fail leetcode submission check since it failed some of my own custom test cases, however it passed with the "Accepted" status.

Consider the custom input test case:
`["froolic","froolic","fraodf","frloadsf","frlozcv"]`

My code will output "frlo" as the longest common prefix, however manual inspection shows that the answer should be "fr". This code however is accepted by leetcode upon submission.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
