### ISSUE TITLE
Wrong question description - 472. Concatenated Words

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#7696]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the given question
![image](https://user-images.githubusercontent.com/8236389/173174662-c322f448-dadc-40de-ab6b-9692ad0e7e65.png)

Why is below correct? because `"aa" + "" = "aa"`
![image](https://user-images.githubusercontent.com/8236389/173174677-9e6da1f1-f752-4e7e-95e4-acb579ef0f23.png)

#### Code you used for Submit/Run operation

```
```

#### Expected behavior
Question description & judge does not match.
It should.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
