### ISSUE TITLE
提交测试用例（13. 罗马数字转整数）

### ISSUE THREAD

**Issue by markmai2008** [LeetCode-Feedback/LeetCode-Feedback#7697]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**markmai2008
填写你登录 LeetCode（中国区）的用户名Milk-Tea

**Bug 类型**
- [ [13. 罗马数字转整数](https://leetcode.cn/problems/roman-to-integer/)] 题目
- [ ] 题解
- [ python3] 编程语言
- [ "CMXXVII"] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
不能证明该测试用例缺失。

这道题已经有3999个测试用例，覆盖了所有可能的情况，为什么认为有测试用例缺失？
