### ISSUE TITLE
提交原创测试用例（13. 罗马数字转整数）

### ISSUE THREAD

**Issue by markmai2008** [LeetCode-Feedback/LeetCode-Feedback#7698]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**markmai2008
填写你登录 LeetCode（中国区）的用户名Milk-Tea

**Bug 类型**
- [[13. 罗马数字转整数](https://leetcode.cn/problems/roman-to-integer/) ] 题目
- [ ] 题解
- [ python3] 编程语言
- [ "CMXXVII"] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
Python3

**你提交或者运行的代码**
```
// Two Sum
class Solution:
    def romanToInt(self,s:str) -> int:
    n = len(s)
    ans = 0
    a = 0
    nums = {'I': 1, 'IV': 4, 'V': 5, 'IX': 9,'X': 10, 'XL': 40, 'L': 50, 'XC': 90, 'C': 100, 'CD': 400, 'D': 500,'CM': 900, 'M': 1000 }
    for i in range(n):
        if n == 0:
            continue
        if s[:2] in nums:
            ans += nums[s[:2]]
            s = s[2:]
            print(a,':',ans)
            a += 1
        if s[:1] in nums and s[:2] not in nums:
            ans += nums[s[:1]]
            s = s[1:]
            print(a,':',ans)
            a += 1
    return ans
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
你的代码运行该测试用例的结果是正确的，并不能证明该测试用例缺失。

这道题已经有3999个测试用例，覆盖了所有可能的情况，为什么认为有测试用例缺失？

**Comment by feiceh** [comment]
你好，在与相关团队核实后：不作处理， 不能证明该测试用例缺失。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
