### ISSUE TITLE
今日的打卡题 914.卡牌分组 执行用时分布图表中执行时间为4ms的代码出现问题

### ISSUE THREAD

**Issue by my87432122** [LeetCode-Feedback/LeetCode-Feedback#77]
** Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
**今日的打卡题 914.卡牌分组 执行用时分布图表中执行时间为4ms的代码是错误的**
样例：[1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4] （四种数字出现次数为6,9,6,8)
输出：True
正确答案：False
**你使用的语言**
C++

**你提交或者运行的代码**
```c++
class Solution {
public:
    bool hasGroupsSizeX(vector<int>& deck) {
        std::ios::sync_with_stdio(false);
        if(deck.size()==1){
            return false;
        }
        int arr[10001]={0};
        for(int item : deck){
            arr[item]++;
        }
        for (int i = 1; i < 10001; i++)
        {
            if(arr[i]!=arr[i-1]&&__gcd(arr[i-1],arr[i])==1){ // 这一行的判断方式是错误的!
                return false;
            }
        }
        return true;
    }
};
```

**期望行为**
样例：[1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4] （四种数字出现次数为6,9,6,8)
输出：True
正确答案：False

**屏幕截图**
emmm 没搞懂咋用markdown添加图片，图片详见-力扣支持中心#7503 工单
**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
您好，这个是用户的代码，平台暂时无法处理。
