### ISSUE TITLE
Misleading Testcase Checker  - 1157. Online Majority Element In Subarray

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#7701]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I accidentally used an invalid testcase to test a code:
["MajorityChecker","query"]
[[[1,1,2,2,1,1]],[0,5,3]]

While the testcase checker indeed detected that this testcase is invalid, it's output is misleading.
![image](https://user-images.githubusercontent.com/11583428/173179912-ff5f4740-8058-429b-ac82-6ae081dd254c.png)
The correct reason for this testcase being invalid should be:
**'query' arguments are invalid: expected 'threshold' to have value from 4 to 6 only**
because of the problem constraints.
![image](https://user-images.githubusercontent.com/11583428/173179954-8a2fb884-a03e-4206-950e-3b8af6aca7d2.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
