### ISSUE TITLE
Wrong template code in C++ - 122. Best Time to Buy and Sell Stock II

### ISSUE THREAD

**Issue by ttesla** [LeetCode-Feedback/LeetCode-Feedback#7705]
#### Your LeetCode username

teslatron

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The template for the solution is wrong for C++. It seems true for other languages.
Here is the wrong template for this question:

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    vector<vector<int>> levelOrderBottom(TreeNode* root)
    {
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

```
class Solution {
public:
    int maxProfit(vector<int>& prices) {
        
    }
};
```

#### Screenshots

[Screenshot](https://pasteboard.co/6eqalPB2tSPP.png)

**Comment by stormsunshine** [comment]
Do you mean problem 112 or 122?

For 122, there is no template with the definition of TreeNode.

For 112, is there any problem with the definition of TreeNode?

**Comment by ttesla** [comment]
Its 122, the question name appeared automatically when I clicked the "Contribute" button. 
I was browsing questions and it get messed up. I keep getting the wrong template for other questions too. But not all of them. 
When I click the "Reset to default code definition" they get fixed.
