### ISSUE TITLE
O(n ^ 2) Python3 Submissions didn't get accepted during Biweekly Contest 80 - 2301. Match Substring After Replacement

### ISSUE THREAD

**Issue by hwennnn** [LeetCode-Feedback/LeetCode-Feedback#7707]
#### Your LeetCode username
hwennn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Given the constraint of 5000, all O(n ^ 2) solutions should pass. However, my code below got TLE during the contest, which is supposed to be accepted. Could the team help re-run the submissions during the contest or loosen the time constraint on python submissions of this question? Thanks in advance.

#### Code you used for Submit/Run operation

```
class Solution:
    def matchReplacement(self, s: str, sub: str, mappings: List[List[str]]) -> bool:
        mp = defaultdict(set)
        n, m = len(s), len(sub)

        for a, b in mappings:
            mp[b].add(a)

        def go(index, curr):
            if curr == m:
                return True
            
            if index == n:
                return False
            
            if sub[curr] == s[index] or sub[curr] in mp[s[index]]:
                return go(index + 1, curr + 1)
            
            return False
            
        for i in range(n):
            if go(i, 0):
                return True
        
        return False
```

#### Language used for code
Python3

#### Expected behavior

https://leetcode.com/contest/biweekly-contest-80/submissions/detail/719673890/
^ The above code got TLE during the contest.
https://leetcode.com/submissions/detail/719767605/
^ The exact same code got AC after the contest.

![image](https://user-images.githubusercontent.com/54523581/173196772-61e01c58-5227-48ad-96fc-ec3adc9e9467.png)
^ I finally got AC after almost 10 times submitting the same code...

**Comment by gh4abhi** [comment]
I have also used the same  approach and am getting TLE. I had used c++ to solve the question.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by hwennnn** [comment]
Well apparently Leetcode didn't seem to rejudge the Q3 submissions. That's really disappointing though, since when Leetcode contests have become a luck game. I would have gotten 5k rank if I didn't spam the submissions in the last few minutes...
