### ISSUE TITLE
Missing Test Case - 197. Rising Temperature

### ISSUE THREAD

**Issue by codedsuri** [LeetCode-Feedback/LeetCode-Feedback#7710]
#### Screenshots

![image](https://user-images.githubusercontent.com/28785863/173201462-e6dcc02c-8b4b-4852-a8dd-c9c090b5ac8b.png)

#### Additional context

My code is accepted but when I am submitting then it's saying the wrong answer! Attached the screenshot for reference.

**Comment by stormsunshine** [comment]
You should pass all test cases to get accepted. Passing only one test case does not guarantee that your code is correct.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
