### ISSUE TITLE
Missing Test Case - 2301. Match Substring After Replacement

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7711]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [2301. Match Substring After Replacement](https://leetcode.com/problems/match-substring-after-replacement), a solution that can get accepted fails on a specific test case.

```
"xbbcd"
"abcd"
[["a","x"],["b","a"]]
```

#### Code you used for Submit/Run operation
```Python
class Solution:
    def matchReplacement(self, s: str, p: str, mappings: List[List[str]]) -> bool:
        m = defaultdict(set)
        for t in mappings:
            m[t[0]].add(t[1])
            
        ne = [0] * len(p)
        ne[0], k = -1, 0
        for i in range(2, len(p)):
            while k != 0 and p[k] != p[i - 1] and p[k] not in m[p[i -1]]:
                k = ne[k] 

            if p[i - 1] == p[k] or p[k] in m[p[i -1]]:
                ne[i] = k + 1
                k += 1
        
        j = 0
        for i in range(len(s)):
            while j > 0 and p[j] != s[i] and s[i] not in m[p[j]]:
                j = ne[j]
            if s[i] == p[j] or s[i] in m[p[j]]:
                j += 1
                if j == len(p):
                    return True

        return False
```

#### Language used for code
Python3

#### Expected behavior
Add the test case so that the code above will get Wrong Answer when submitted.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
