### ISSUE TITLE
Missing Test Case - 344. Reverse String

### ISSUE THREAD

**Issue by danycalderon16** [LeetCode-Feedback/LeetCode-Feedback#7714]
#### Your LeetCode username
danycalderon16

#### Category of the bug
- [ ] Question
- [] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I have made a recursive solution, I have tried it in several editors, but when running it here, it does not work

#### Code you used for Submit/Run operation
 ``` 
#Reverse String
class Solution(object):
    def reverseString(self, s):
        """
        :type s: List[str]
        :rtype: None Do not return anything, modify s in-place instead.
        """
        return [] if s==[] else  s[len(s)-1::] + self.reverseString(s[::len(s)-1])
```

#### Language used for code
Python

#### Screenshots
![Captura de pantalla 2022-06-11 200342](https://user-images.githubusercontent.com/34558158/173211182-0eb62c72-ccfc-4844-89e1-fec60684b435.png)

**Comment by Kaiserouo** [comment]
```
:rtype: None Do not return anything, modify s in-place instead.
```
You return something other than `None`, and `s` is not modified. Your solution is correct in a vague sense but does not meet the requirement of this problem. This problem requires in-place reverse instead of returning a brand new list.

**Comment by danycalderon16** [comment]
> ```
> :rtype: None Do not return anything, modify s in-place instead.
> ```
> 
> You return something other than `None`, and `s` is not modified. Your solution is correct in a vague sense but does not meet the requirement of this problem. This problem requires in-place reverse instead of returning a brand new list.

Ok Ok, first I have to improve my English because I didn't understand that detail. Thanks for replying and showing me where I was wrong. I will do it again as indicated
