### ISSUE TITLE
Missing Test Case - 1695. Maximum Erasure Value

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#7716]
#### Your LeetCode username
RohitSgh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Related to Tags of the Problem 

#### Expected behavior

The problem, as also mentioned in Hints uses concept of `Two Pointers` and `Prefix Sum`. Hence, ideally under the section **Related Topics**, it should have these tags.

#### Screenshots

![image](https://user-images.githubusercontent.com/81853910/173214789-9579e7d6-f3db-403e-908b-09371c346db5.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 
Wen decided that "double pointer" and "prefix and" are not tagged. The reasons are as follows:
The two labels "sliding window" and "double pointer" are often confused. According to the official definition of LeetCode, "sliding window" means that the left and right endpoints and the middle part need to be considered. "double pointer" only considers the elements at the two pointers. Regardless of the elements between the two pointers, this problem needs to consider all elements in the subarray, so it is a sliding window.

Although the solution area and discussion area do have solutions for "prefix sum", the essence of prefix sum is still a sliding window.

Therefore, the two tags "double pointer" and "prefix and" are not added. 
We appreciate your support!
