### ISSUE TITLE
2296. 设计一个文本编辑器 frontend_id 丢失，不显示题号

### ISSUE THREAD

**Issue by kaiwensun** [LeetCode-Feedback/LeetCode-Feedback#7717]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目 https://leetcode.cn/problems/design-a-text-editor/ 在 https://leetcode.cn/problemset/all/ 当中搜索不显示题号，无法根据题号搜索到。
https://leetcode.com/api/problems/all/ 当中显示该题目的frontend_id为空：
```
{
   "stat" : {
      "total_column_articles" : 100,
      "question__title_slug" : "design-a-text-editor",
      "frontend_question_id" : "",
      "total_submitted" : 11806,
      "question_id" : 2389,
      "question__title" : "Design a Text Editor",
      "total_acs" : 4839,
      "question__hide" : false,
      "is_new_question" : false
   },
   "status" : "ac",
   "difficulty" : {
      "level" : 3
   },
   "frequency" : 0,
   "is_favor" : false,
   "progress" : 0,
   "paid_only" : false
}
```

**你使用的语言**
N/A

**你提交或者运行的代码**
N/A

**期望行为**
1. [2296. 设计一个文本编辑器](https://leetcode.cn/problems/design-a-text-editor/) 的 `frontend_id` 应为2296
2. LeetCode网站应有canary test，长期实时模拟用户的行为，根据题号搜索每一道题目。如果无法根据题目搜索到题目，canary test应自动向LeetCode运维人员报警。

**屏幕截图**
![image](https://user-images.githubusercontent.com/18455693/173219711-48a27a6d-3431-40b6-a07f-c9edf5480d1f.png)

**额外的上下文**
N/A

**Comment by kaiwensun** [comment]
https://leetcode.cn/problems/match-substring-after-replacement/

这道题目也发生了类似的情况。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。
