### ISSUE TITLE
791 - Change 'words' to 'characters'

### ISSUE THREAD

**Issue by araslanov** [LeetCode-Feedback/LeetCode-Feedback#7718]
#### Your LeetCode username
wizeek

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem description says `You are given two strings order and s. All the words of order are unique...`.
From the description it is also clear that `order` string contains characters (or letters) sorted in some way, not the words separated by spaces, so calling characters as words may seem confusing.

#### Expected behavior
It would probably be more accurate and less confusing to say `All the characters of order` or `All the letters of order`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
