### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by trorter** [LeetCode-Feedback/LeetCode-Feedback#7719]
#### Your LeetCode username
vhorek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Wrong expected result
11
[1,2,3,4,5]

expected: 3
right answer: 0

#### Code you used for Submit/Run operation
```
// Two Sum
class Solution {
    public int minSubArrayLen(int target, int[] nums) {
        var min = Integer.MAX_VALUE;
        
        var start = 0;
        var curSum = 0;
        var count = 0;
        
        for (var num : nums) {
            while (target < curSum + num && count > 0) {
                curSum -= nums[start];
                count--;
                start++;
            }
            
            curSum += num;
            count++;
            
            if (curSum == target) {
                min = Math.min(min, count);
            }
        }
        
        return min == Integer.MAX_VALUE ? 0 : min;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Wrong expected result
11
[1,2,3,4,5]

expected: 3
right answer: 0

**Comment by stormsunshine** [comment]
The subarray [3,4,5] has sum at least 11, so the answer is 3. Why do you think the expected answe should be 0?

**Comment by trorter** [comment]
Oops, sorry, wrong reading from my side... "greater than or equal to target". There is no problem
