### ISSUE TITLE
101 Symmetric Tree test case are incorrect

### ISSUE THREAD

**Issue by liys87x** [LeetCode-Feedback/LeetCode-Feedback#772]
#### Your LeetCode username
My LeetCode username: liys87x

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
url: https://leetcode.com/problems/symmetric-tree/
testcase: [1,2,2,null,3,3]
Run code Expect: true
it should be false

**Comment by lc-pam** [comment]
Hi @liys87x 
Thank you for reaching out to us. The output is correct, I recommend you raise your question in the [discussion post](https://leetcode.com/problems/symmetric-tree/discuss/?currentPage=1&orderBy=most_posts&query=).
