### ISSUE TITLE
498. Diagonal Traverse - Typo

### ISSUE THREAD

**Issue by abe-101** [LeetCode-Feedback/LeetCode-Feedback#7720]
#### Your LeetCode username
abe-101

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a typo in the paragraph under Approach 2: Simulation -> Intuition:
"Basically, in the previous approach, figuring **our** the head of the diagonal was pretty easy"
"figuring **our**" need to be changed to "figuring **out**"

#### Screenshots

![Screenshot from 2022-06-12 10-47-21](https://user-images.githubusercontent.com/82916197/173238997-0d541ee2-9d80-4e13-a402-dcb063a7a6e0.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
