### ISSUE TITLE
Missing Test Case - 1658. Minimum Operations to Reduce X to Zero

### ISSUE THREAD

**Issue by pandacover** [LeetCode-Feedback/LeetCode-Feedback#7721]
#### Your LeetCode username
LuvMakin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int helper (vector<int> &v, int tar, int st, int en) { 
        int ans=0, sum=0; 
        unordered_map<int, int> mp; 
        
        for (int i = st; i <= en; ++i) { 
            sum += v[i];
            if(sum == tar) ans = max(ans, i + 1);

            if(mp.count(sum - tar)) ans = max(ans, i - mp[sum - tar]); 
            
            if(!mp.count(sum)) mp[sum] = i;
        } 
        return ans;
    } 
    int minOperations (vector<int>& nums, int x) {
        int n = nums.size(); 
        int sum = 0;

        if(n == 1) return x == nums[0];
        
        for (auto &i: nums) sum += i; 
        if(sum == x) return n;

        int ans = helper(nums, sum - x, 0, n-1); 
        if(ans == 0) return -1; 
        
        return n - ans;
    }

};
```

#### Language used for code

C++

#### Expected behavior

-1 expected for an array with length 1 where first element of the array is not equal to the given x.
All the test case for the given condition are missing.

Example:
nums = [ 1 ]
x = 2
expected answer 0

#### Screenshots

All the test case have been passed
![image](https://user-images.githubusercontent.com/57311008/173239703-821ce24a-9c10-4842-8c1e-26ca21926083.png)

Example of the missing test case are under the given constraints
![image](https://user-images.githubusercontent.com/57311008/173239732-80832c23-fd1a-4df8-aa6a-3062a91ada0a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by pandacover** [comment]
Just contributing to the community. Thank you!

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
