### ISSUE TITLE
Ambiguous Question - 733. Flood Fill

### ISSUE THREAD

**Issue by omjinLTS** [LeetCode-Feedback/LeetCode-Feedback#7722]
#### Your LeetCode username
omjinLTS

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think there is some ambiguity about the variable name `newColor`. 
Somehow, "new" can be considered as "different from older one". 
However, the testcase includes which `newColor` is same with older one. 
Thus, I think the description or example have to be added to announce the `newColor` can be equal to older one. 

#### Code you used for Submit/Run operation

When `newColor` is same with older one, the code similar with this occurs infinite loop.
If `newColor` is different with old color, then it can be a answer too.
``` python
class Solution:
    def floodFill(self, image: List[List[int]], sr: int, sc: int, newColor: int) -> List[List[int]]:
        dx = 0, 1, 0, -1
        dy = 1, 0, -1, 0
        m, n = len(image), len(image[0]) # m rows, n columns
        sourceColor = image[sr][sc]
        if newColor == sourceColor:
            return image
        q = deque()
        q.append((sr, sc))
        image[sr][sc] = newColor
        while q:
            curR, curC = q.popleft()
            for i in range(4):
                nR, nC = curR + dx[i], curC + dy[i]
                if nR < 0 or nC < 0 or nR >= m or nC >= n:
                    continue
                if image[nR][nC] == sourceColor:
                    image[nR][nC] = newColor
                    q.append((nR, nC))
        return image
                
```

#### Language used for code

python 3

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
