### ISSUE TITLE
What if it has more than one child nodes at particular level -FLATTEN A MULTILEVEL DOUBLY LINKED LIST-430

### ISSUE THREAD

**Issue by oceanbhardwaj** [LeetCode-Feedback/LeetCode-Feedback#7726]
what if next node which we put in stack also has  a child node then stack solution won.t work .But my stack solution is accepted,
need to know as it is not mentioned in questions that it is limited to one child node at particular level.

#### Your LeetCode username
oceanbhardwaj

#### Category of the bug
questions requirement
solution
might be missing this test case of multiple child nodes at particular level.

#### Description of the bug

what if next node which we put in stack also has  a child node then stack solution won.t work .But my stack solution is accepted,
need to know as it is not mentioned in questions that it is limited to one child node at particular level.

#### Code you used for Submit/Run operation

```
/*
// Definition for a Node.
class Node {
    public int val;
    public Node prev;
    public Node next;
    public Node child;
};
*/

class Solution {
    public Node flatten(Node head) {
        Stack<Node> s=new Stack<>();
        Node curr=head;
        Node next=null;
        Node prev=null;
        Node child=null;
      //  Node ans=new Node(0);
        Node dummy=curr;
        while(curr!=null){
            prev=curr;
            child=curr.child;
            next=curr.next;
            if(next!=null && child!=null){
                s.push(next);
                curr.next.prev=null;
            }
            if(child!=null)
            {curr.next=child;
            curr.next.prev=prev;
            curr.child=null;}
            //if(curr.next!=null)
            curr=curr.next;
            
        }
        curr=prev;
        while(!s.isEmpty()){
            prev=curr;
            Node temp=s.pop();
            curr.next=temp;
            curr.next.prev=prev;
            while(curr.next!=null)
                curr=curr.next;
        }
        return dummy;
    }
}
```

#### Language used for code

JAVA

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by oceanbhardwaj** [comment]
Hi team,
Problem name is Leetcode -430
Flatten a multilevel doubly linked list

Thanks,
Ocean

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The problem mentioned one child pointer. We have more than one child, we would say that in the statement definitely. We appreciate your support!

**Comment by oceanbhardwaj** [comment]
Thanks team  for the quick response
Please highlight where it is mentioned it is limited to one child
