### ISSUE TITLE
Wrong Test Case - 120. Triangle

### ISSUE THREAD

**Issue by yatinnagpal** [LeetCode-Feedback/LeetCode-Feedback#7727]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

Q- Given a triangle array, return the minimum path sum from top to bottom.

For each step, you may move to an adjacent number of the row below. More formally, if you are on index i on the current row, you may move to either index i or index i + 1 on the next row.

The output of the below test case should be 0, if we consider minimum element at alternate position.

![image](https://user-images.githubusercontent.com/48492494/173277328-9d8451bb-8e3f-426b-ae8b-94d1895c4a15.png)

**Comment by stormsunshine** [comment]
The minimum path sum is (-1) + 3 + (-3) = -1. Is there any problem?

**Comment by yatinnagpal** [comment]
Yes it works. Sorry, Actually I had some misunderstanding with the question.
