### ISSUE TITLE
Time limit too tight for Python

### ISSUE THREAD

**Issue by i-sergienko** [LeetCode-Feedback/LeetCode-Feedback#773]
#### Your LeetCode username
is_1337

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language

#### Description of the bug
The test cases for the task https://leetcode.com/problems/number-of-submatrices-that-sum-to-target/ have time limits that are too tight for Python.
The final (300x300) test case breaks, to be specific. Even though the code submitted has the same asymptotic complexity to other solutions, it gets a TLE because of a few additional checks (if/else conditions), i.e. it only differs by a small constant factor from the other solutions.

#### Code you used for Submit/Run operation

```
from collections import defaultdict

def to_prefix(matrix):
    prefix = [row[:] for row in matrix]
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if i > 0:
                prefix[i][j] += prefix[i-1][j]
            if j > 0:
                prefix[i][j] += prefix[i][j-1]
            if i > 0 and j > 0:
                prefix[i][j] -= prefix[i-1][j-1]
    return prefix

def total(prefix, tl, br):
    res = prefix[br[0]][br[1]]
    if tl[0] > 0:
        res -= prefix[tl[0]-1][br[1]]
    if tl[1] > 0:
        res -= prefix[br[0]][tl[1]-1]
    if tl[0] > 0 and tl[1] > 0:
        res += prefix[tl[0]-1][tl[1]-1]
    return res

class Solution:
    def numSubmatrixSumTarget(self, matrix: List[List[int]], target: int) -> int:
        prefix = to_prefix(matrix)
        res = 0
        for i in range(len(matrix)):
            for _i in range(i, len(matrix)):
                sums = defaultdict(int)
                sums[0] += 1
                for j in range(len(matrix[0])):
                    current = total(prefix, (i, 0), (_i, j))
                    res += sums[current - target]
                    sums[current] += 1   
        return res
```

#### Language used for code
Python 3

#### Expected behavior
All test cases pass without TLE

#### Additional context
As I understand it, the time limits for the problem were reduced since the time it was first introduced.
It was already raised as an issue regarding the Leetcode-offered C++ solution getting TLE.

**Comment by lc-pam** [comment]
Hi @i-sergienko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @i-sergienko 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
