### ISSUE TITLE
526. Beautiful Arrangement | Minor fix

### ISSUE THREAD

**Issue by Yatin-kathuria** [LeetCode-Feedback/LeetCode-Feedback#7731]
#### Your LeetCode username
Yatin-kathuria

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Example description statement is not sync with the above example statements.
```
Example 1
The first beautiful arrangement is [1,2]:
    - perm[1] = 1 is divisible by i = 1
    - perm[2] = 2 is divisible by i = 2
The second beautiful arrangement is [2,1]:
    - perm[1] = 2 is divisible by i = 1
    - i = 2 is divisible by perm[2] = 1
 ```

> i = 2 is divisible by perm[2] = 1

The above link should be written as perm[2] = 1 is divisible by i = 2 to be similar with above statements

#### Screenshots

<img width="359" alt="image" src="https://user-images.githubusercontent.com/47096348/173360582-1ea20ceb-2bf7-4a24-95f0-3dd7b282bcb1.png">

**Comment by LC-Pam** [comment]
Thank you for your time.  The line "i = 2 is divisible by perm[2] = 1" corresponds to the second condition that "i is divisible by perm[i]". Your suggestion would not follow the first rule, because 1 (perm[2]) is not divisible by 2 (i = 2). We appreciate your support!
