### ISSUE TITLE
Sample testcases in Explore

### ISSUE THREAD

**Issue by psy-guy** [LeetCode-Feedback/LeetCode-Feedback#7734]
When testing code from the Problems tab, there are convenient buttons for "Use Example Testcases" and "Run Example Testcases." However, these buttons are not there when testing code from the Explore category. Please add it.

**Comment by psy-guy** [comment]
https://leetcode.com/explore/

Following the link to an arbitrary problem: https://leetcode.com/explore/interview/card/top-interview-questions-easy/92/array/727/

The same problem from the problems tab: https://leetcode.com/problems/remove-duplicates-from-sorted-array

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for sharing your concern, it is a good observation. We already submitted your feedback to the team, but it will take some times to fix the issue. We appreciate your help!
