### ISSUE TITLE
543. Diameter of Binary Tree | solution

### ISSUE THREAD

**Issue by apriil15** [LeetCode-Feedback/LeetCode-Feedback#7735]
#### Your LeetCode username
nlwkobe30

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I ran the same test case.
I got `correct` when I ran `test example`, but I got `wrong` when `submit`.

#### Code you used for Submit/Run operation

```typescrupt
// 543. Diameter of Binary Tree
let result = 0

function diameterOfBinaryTree(root: TreeNode | null): number {
  maxDepth(root)
  return result
}

function maxDepth(root: TreeNode | null): number {
  if (!root) {
    return 0
  }

  const left = maxDepth(root.left)
  const right = maxDepth(root.right)

  result = Math.max(result, left + right)

  return Math.max(left, right) + 1
}
```

#### Language used for code

Typescript

#### Expected behavior

Example:
input = [1,2]
output = 1

#### Screenshots

![](https://i.imgur.com/iqvPtqM.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
