### ISSUE TITLE
Missing test cases in Leetcode Question 1706  "Where Will the Ball Fall"

### ISSUE THREAD

**Issue by ashmit35** [LeetCode-Feedback/LeetCode-Feedback#7736]
Your LeetCode username
Ido_Ash

Category of the bug
- [ ] Missing Test Cases 

Description of the bug
-In the question, there should be a test case in which the ball is is going out of the box 
 these types of testcases are not covered where the ball goes out of the grid

Code you used for Submit/Run operation
// Where Will the Ball Fall
class Solution {
    
    public int f(int i,int j,int grid[][],int dp[][]){
        if(i<0 || j<0 || i>=grid.length || j>=grid[0].length) return -1;
        if(i==grid.length-1){
            if(grid[i][j]==1 && j+1<grid[0].length  && grid[i][j+1]==-1) return -1;
            if(grid[i][j]==-1 && j-1>=0 && grid[i][j-1]==1) return -1;
            if(grid[i][j]==-1) return j-1;
            return j+1;
        }
        if(dp[i][j]!=-2) return dp[i][j];
        
        if(j+1<grid[0].length && grid[i][j]==1 && grid[i][j+1]==-1) return -1;
        if(j-1>=0 && grid[i][j]==-1 && grid[i][j-1]==1) return -1;
        
        if(grid[i][j]==1){
            return dp[i][j] = f(i+1,j+1,grid,dp);
        }else{
            return dp[i][j] = f(i+1,j-1,grid,dp);
        }
    }
    
    public int[] findBall(int[][] grid) {
        
        if(grid.length==1 && grid[0].length==1) return new int[]{-1};
        
        int n = grid.length;
        int m = grid[0].length;
        int ans[] = new int[m];
        
        int dp[][] = new int[n][m];
        for(int i[]:dp) Arrays.fill(i,-2);
        
        for(int j=0;j<m;j++){
            ans[j] = f(0,j,grid,dp);
        }
        return ans;
    }
}

Language used for code
Java

Expected behavior
This code is wrong because it's not handling the case when all the elements of the grid are 1.
Like for testcase grid = [[1,1,1,1,1],[1,1,1,1,1]] , the answer should be [2,3,4,-1,-1] but my answer is [2,3,4,5,-1] , and it got accepted.

Screenshots
-Screenshot 1 (my code is giving wrong answer for this testcase)

![leet](https://user-images.githubusercontent.com/100089020/173425237-d3a4ec92-3417-441c-9c8d-171332e3fd6c.png)

-Screenshot 2 (But my code got Accepted)
![2022-06-14_00-39-29-140](https://user-images.githubusercontent.com/100089020/173427099-a93ad532-de4f-40db-9695-3ea5d1a28e03.png)

Additional context
1.  Add more test cases where all the elements of the grid are same and are equal to 1
2. Like for size 2x5, add a testcase grid = [[1,1,1,1,1],[1,1,1,1,1]], the output for this testcase should be [2,3,4,-1,-1], as for index 3, the ball will fall on the 5th index (column) which is considered as out of the grid so the answer to that index must be  -1.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The code Accepted Submission link. 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ashmit35** [comment]
Here is the link:-
https://leetcode.com/submissions/detail/721433943/

**Comment by ashmit35** [comment]
https://leetcode.com/submissions/detail/721433943/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
