### ISSUE TITLE
Missing TestCase for 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by Ritsz123** [LeetCode-Feedback/LeetCode-Feedback#774]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

How I come across this bug:
as it was not mentioned whether the matrix will contain only positive values or a combination of -ve & +ve values firstly I tried putting -1 there and later on supposed to change it to 0. but my solution failed.
Then I tried putting '#' but there was also a test case present that contains ASCII value of '#'. Then because of my curiosity I tried other characters & noticed that there was a test case containing ASCII values of all characters.
Then because of a great curiosity another idea strike in my mind and **_I tried putting ' ' (SPACE) & Boom the Solution worked!_** I got runtime of 1ms and faster than 97.94% of users.

#### Code you used for Submit/Run operation

```
class Solution {
    public void setZeroes(int[][] matrix) {
        
        int m = matrix.length;
        int n = matrix[0].length;
        
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==0){
                    for(int k=0;k<n;k++){
                        if(matrix[i][k]!=0)
                        matrix[i][k] = ' ';
                    }
                    for(int k=0;k<m;k++){
                        if(matrix[k][j]!=0)
                        matrix[k][j] = ' ';
                    }
                }
            }
        }
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==' '){
                    matrix[i][j]=0;
                }
            }
        }
    }
}
```

#### Language used for code

- Java

#### Expected behavior

I expected WA but it gave me AC

**Comment by lc-ivan** [comment]
Hi @Ritsz123 ,
Thanks for reaching out to us! Could you provide the test case you would like to contribute in the input format for this problem?

**Comment by Ritsz123** [comment]
sure @lc-ivan 
**Input:**
` [
[1,1,1],[1,0,1],[32,1,1]
] `
**Output by program:**
`[
  [1,0,1],[0,0,0],[0,0,1]
]`
**Expected correct Output:**
`[
  [1,0,1],[0,0,0],[32,0,1]
]`

Here we clearly see that the expected output is different from output by the program.

**Comment by lc-ivan** [comment]
Hi @Ritsz123 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @Ritsz123 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
