### ISSUE TITLE
Subdomain Visit Count

### ISSUE THREAD

**Issue by ekcole** [LeetCode-Feedback/LeetCode-Feedback#7741]
My solution passes 51 of 52 testcases, but doesn't pass the last one because the solution is expecting it to be ordered when the problem states the orderings shouldn't matter - can you guys fix this please?

Here is the input testcase:
["4781 hal.net","3742 kmi.ca","7602 fai.fly.com","8927 qpf.gqi.org","6183 gtu.org","7371 yvs.co","6661 xuf.network","9066 yvr.co","4070 rhf.uyy.org","4283 etj.tnr.com","3443 rif.ibf.team","5030 ixi.com","5908 yvs.ca","5789 wph.us","1614 gxj.network","8109 zyh.jfz.network","8435 tpr.irv.network","9848 gbq.ca","4632 gqi.co","7102 gxj.net","2490 dbr.cgl.net","8422 tnw.zqk.team","2018 uuy.network","2358 vbo.com","7372 buf.co","3698 fzx.org","7792 kwd.com","6693 uno.ytn.net","2948 cpl.ser.network","9722 npa.uyy.us","219 yls.network","486 asz.ca","5431 znq.us","8238 vos.ajl.net","1342 fff.ca","2228 cso.gdw.org","2090 zon.vbo.com","7031 zqk.us","2984 okv.us","1052 ocf.com","6148 hwu.com","813 oms.zfz.us","2546 uuy.com","1592 hwu.ca","6253 okv.team","4596 uuy.com","7437 dzg.wsv.network","7970 fly.us","961 jtg.us","962 xec.jfz.co","610 tid.team","7281 nkw.org","5870 yes.gtu.network","1165 llh.okv.us","7084 ser.com","5510 oca.hwu.org","4454 ork.yvs.network","8670 iux.us","5526 oth.wsv.team","2905 wiz.wqv.org","1917 arm.ulz.com","451 pfz.wsv.network","8271 yjt.org","24 gxz.net","7323 msc.nva.com","4837 pfx.ibf.network","529 qay.team","3311 kwd.us","5803 wsv.co","834 hly.hlr.network","5959 yvs.us","6251 hlr.co","2936 vzd.dfa.network","8546 zqy.us","483 bix.ytn.co","2226 oqr.gbq.org","7600 zqk.ca","2612 hbu.cwn.net","430 oxv.bhp.com","9954 srz.vbo.team","3925 hoh.com","5647 ses.ltq.org","1476 gdw.us","1535 ajl.network","5253 bom.yvs.team","8864 thk.net","7029 ser.co","8694 gxk.tfm.co","5255 rbb.fff.com","8491 xzz.ser.co","7181 hnl.net","5919 axj.fff.org","4088 mqy.asz.org","4954 bec.okv.com","8943 dak.wqv.network","5556 jtg.com","1458 xov.epf.co","2868 uwm.yjt.com","6474 tfm.net","2045 tid.co"]

My output:
["4781 hal.net","54459 net","3742 kmi.ca","30518 ca","7602 fai.fly.com","7602 fly.com","82809 com","8927 qpf.gqi.org","8927 gqi.org","66953 org","6183 gtu.org","7371 yvs.co","69657 co","6661 xuf.network","62847 network","9066 yvr.co","4070 rhf.uyy.org","4070 uyy.org","4283 etj.tnr.com","4283 tnr.com","3443 rif.ibf.team","3443 ibf.team","39990 team","5030 ixi.com","5908 yvs.ca","5789 wph.us","69828 us","1614 gxj.network","8109 zyh.jfz.network","8109 jfz.network","8435 tpr.irv.network","8435 irv.network","9848 gbq.ca","4632 gqi.co","7102 gxj.net","2490 dbr.cgl.net","2490 cgl.net","8422 tnw.zqk.team","8422 zqk.team","2018 uuy.network","4448 vbo.com","7372 buf.co","3698 fzx.org","7792 kwd.com","6693 uno.ytn.net","6693 ytn.net","2948 cpl.ser.network","2948 ser.network","9722 npa.uyy.us","9722 uyy.us","219 yls.network","486 asz.ca","5431 znq.us","8238 vos.ajl.net","8238 ajl.net","1342 fff.ca","2228 cso.gdw.org","2228 gdw.org","2090 zon.vbo.com","7031 zqk.us","4149 okv.us","1052 ocf.com","614...

Expectred:
["2018 uuy.network","9722 npa.uyy.us","2868 uwm.yjt.com","1917 arm.ulz.com","5253 yvs.team","1592 hwu.ca","7888 wsv.network","5870 yes.gtu.network","2226 oqr.gbq.org","7102 gxj.net","8238 ajl.net","834 hly.hlr.network","3742 kmi.ca","5510 oca.hwu.org","9848 gbq.ca","4448 vbo.com","8435 irv.network","8927 gqi.org","8927 qpf.gqi.org","8694 gxk.tfm.co","4088 asz.org","1535 ajl.network","8422 tnw.zqk.team","2228 gdw.org","219 yls.network","8271 yjt.org","5803 wsv.co","8546 zqy.us","5919 fff.org","1165 llh.okv.us","39990 team","2612 cwn.net","4837 ibf.network","8422 zqk.team","1052 ocf.com","962 jfz.co","4088 mqy.asz.org","7602 fly.com","5510 hwu.org","7323 msc.nva.com","7084 ser.com","5870 gtu.network","5526 wsv.team","6661 xuf.network","7437 dzg.wsv.network","67301 network","2936 dfa.network","6253 okv.team","834 hlr.network","8109 jfz.network","7323 nva.com","54459 net","9722 uyy.us","486 asz.ca","6693 ytn.net","8670 iux.us","3311 kwd.us","2905 wqv.org","483 bix.ytn.co","5255 rbb.fff.com...

**Comment by ekcole** [comment]
Problem name: [Subdomain Visit Count](https://leetcode.com/problems/subdomain-visit-count/)

Code and Language: Python; here is the code:


class Solution:
    def subdomainVisits(self, cpdomains: List[str]) -> List[str]:
        subDict = {}
        for domain in cpdomains:
            count, url = domain.split(" ")
            count = int(count)
            subdomains = url.split(".")
            for domain in subdomains:
                if subDict.get(url):
                    subDict[url] += count
                else:
                    subDict[url] = count
                url = url.replace(domain, '')
                url = url[1::]
        
        dictArray = []
        for item in subDict:
            element = str(subDict[item])
            element = element + " " + item
            dictArray.append(element)

        return dictArray
    def splitDomain(self, domain):
        count, subdomains = domain.split(" ")
        subdomains = subdomains.split(".")
        return int(count), subdomains

**Comment by LC-Pam** [comment]
Would you mind sending us your code submission Accepted link?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
