### ISSUE TITLE
12. Integer to Roman -  Returning wrong value

### ISSUE THREAD

**Issue by astrokachi** [LeetCode-Feedback/LeetCode-Feedback#7744]
#### Category of the bug
- [ ] Question
- Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The output of the code is "LVIII" when I click on "Run code" but it changes to "IIILVIII" when "Submit".
On regular code editors it returns "LVIII" and works just fine too.

#### Code you used for Submit/Run operation

```
// Integer to Roman 
const romans = {1: "I",4: "IV", 5: "V",9: "IX", 10: "X",40:"XL", 50: "L", 90: "XC", 100: "C",400: "CD", 500: "D", 900: "CM", 1000: "M"}
let numeral = ""

var intToRoman = function(num) {
    if(num === 0){
        console.log(numeral)
        return numeral
    } 

    else{
     let start = check(num)
    numeral += romans[start]
    const newnum = num - start;
    intToRoman(newnum)
    return numeral   
    }
    return numeral
};

const check = (num) => {
    let start = 0
    for(const property in romans){
        if(num >= +property){
            start = +property
        }
    }
    console.log(start)
    return start;
}
};
```

#### Language used for code

Javascript 

#### Expected behavior

The output is supposed to return "LVIII" when the input is 58.

#### Screenshots

![leet](https://user-images.githubusercontent.com/60720828/173461078-4e256c8a-bf69-4d22-9645-4b3168600240.PNG)

**Comment by astrokachi** [comment]
New Bug!!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
