### ISSUE TITLE
1396 - Typo in solution description

### ISSUE THREAD

**Issue by araslanov** [LeetCode-Feedback/LeetCode-Feedback#7746]
#### Your LeetCode username
wizeek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the `Approach 1: Two HashMaps`, towards the end of the `Intuition` section, there is a sentence `One detail we overlooked earlier w1as deleting data...` with a typo in `w1as`.

#### Expected behavior
It should be `was` instead of `w1as`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
