### ISSUE TITLE
Typo in Soln approach 2 - 135. Candy

### ISSUE THREAD

**Issue by Vinayaka2k** [LeetCode-Feedback/LeetCode-Feedback#7749]
#### Your LeetCode username
vinuvinayaka2000

#### Category of the bug
- [ ] Question
- [Y] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In approach 2, we iterate from right to left on the `right2left` array

#### Expected behavior

**Quoting from Approach 2 :** 
 
After the forward traversal, we traverse the array from **left-to-right** and update right2left[i] as right2left[i] = right2left[i + 1] + 1, whenever the current i'th element has a higher ratings than the right i+1'th element.

**It should be :** 
 
After the forward traversal, we traverse the array from **right-to-left** and update right2left[i] as right2left[i] = right2left[i + 1] + 1, whenever the current i'th element has a higher ratings than the right i+1'th element.

**Comment by Vinayaka2k** [comment]
Hi @LC-Pam any update on this ?

**Comment by Vinayaka2k** [comment]
@LC-Pam @stormsunshine any update on this ??

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!

**Comment by Vinayaka2k** [comment]
@LC-Pam wouldn't I be receiving leetcoins for this contribution ?

**Comment by Vinayaka2k** [comment]
@LC-Pam @LC-Pamela I haven't received any leetcoins for this contribution? Please check
