### ISSUE TITLE
[Global Ranking Bug] Not showing 5th place

### ISSUE THREAD

**Issue by Nuno-Dev** [LeetCode-Feedback/LeetCode-Feedback#7751]
#### Your LeetCode username
nunodev

#### Description of the bug

5th place not showing in the Global Contest Ranking

![image](https://user-images.githubusercontent.com/57804241/173660205-31841b19-47fb-4698-bd14-407d9c04013a.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
