### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by LBonassin** [LeetCode-Feedback/LeetCode-Feedback#7752]
#### Your LeetCode username
LBonassin

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem: 583: Delete Operation for Two Strings

Typo in Example 1: ('ea' and 'eat' are swapped)
Explanation: You need one step to make "sea" to "ea" and another step to make "eat" to "ea".

Needs to be:
Explanation: You need one step to make "sea" to "ea" and another step to make "ea" to "eat".

**Comment by shreyashHake** [comment]
LGTM

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.
We only delete characters from the strings.
We change sea to ea.
We also change eat to ea.
We appreciate your support!

**Comment by LBonassin** [comment]
Oh. I misunderstood.

Sorry about that.
