### ISSUE TITLE
Incomplete Test Cases for 16. 3Sum Closest

### ISSUE THREAD

**Issue by haydenparker3** [LeetCode-Feedback/LeetCode-Feedback#7753]
#### Your LeetCode username
Ferninad

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X ] Missing Test Cases 

#### Description of the bug
Accepted solution fails a custom testcase

#### Code you used for Submit/Run operation
```
// 3Sum Closest
class Solution {
    public int threeSumClosest(int[] nums, int target) {
        Arrays.sort(nums);
        
        int closest = Math.abs(target - nums[0] - nums[1] - nums[2]);
        int closestSum = nums[0] + nums[1] + nums[2];
        
        int i = 0;
        while(i < nums.length && nums[i] <= target/3) {
            int l = i+1;
            int r = nums.length-1;
            while(l < r) { // two pointer approach on numbers right of target
                int sum = nums[l] + nums[r] + nums[i];
                int diff = Math.abs(target - sum);
                
                if(diff < closest) {
                    closest = diff;
                    closestSum = sum;
                }
                
                if(sum < target) {
                    l++;
                } else {
                    r--;
                }
            }
            
            i++;
        }

        return closestSum;
    }
}
```

#### Language used for code
Java

#### Expected behavior
My accepted solution fails this test case:
[1,1,1,5,5,5,5,5,5]
14

the correct output should be 15 but my accepted solution spits out 11

#### Screenshots
<img width="788" alt="image" src="https://user-images.githubusercontent.com/22896731/173676140-6e4074e3-1926-48b6-95e7-21a89643791e.png">

#### Additional context
The issue arises from nums[i] <= target/3 in the first while loop. It skips numbers greater than a third of the target, in this case it skips all the 5s. Leading to my accepted solution missing the 5 + 5 + 5 = 15 correct solution.

What this means is that the testcases are missing the testcase where the numbers summed to get the correct solution are all greater than a third of target.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. we rejected your test case because the answer is not unique. That was mentioned in the statement. We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
