### ISSUE TITLE
Improper Title - 2297. Jump Game IX

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7757]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The title of [2297. Jump Game IX](https://leetcode.com/problems/jump-game-ix) is "Jump Game IX", which is from "Jump Game" series and has number nine (IX) in the series.

However, before this problem, there are only seven problems in the series "Jump Game". Since problem 2297 is the eighth problem in the series "Jump Game", the title should be "Jump Game VIII" rather than "Jump Game IX".

Hope the title can be changed to "Jump Game VIII", and the link should be updated accordingly.

#### Expected behavior
Change the title of problem 2297 to "Jump Game VIII". The link of this problem should be updated accordingly.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
