### ISSUE TITLE
Missing Test Case 18.4Sum

### ISSUE THREAD

**Issue by eugenesujing** [LeetCode-Feedback/LeetCode-Feedback#7758]
#### Your LeetCode username 

eugenesujing

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The following test case should be added: nums =[1000000000,1000000000,1000000000,1000000000],
target =-294967296
Also, when it is using the above as input, the expected output displayed is [[1000000000,1000000000,1000000000,1000000000]], which is incorrect. 
The correct output should be an empty array since it is impossible to have a negative sum when every element in nums are positive.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> fourSum(vector<int>& nums, int target) {
        sort(begin(nums), end(nums));
        return kSum(nums, target, 0, 4);
    }
	
    vector<vector<int>> kSum(vector<int>& nums, int target, int start, int k) {
        vector<vector<int>> res;
        
        // If we have run out of numbers to add, return res.
        if (start == nums.size()) {
            return res;
        }
        
        // There are k remaining values to add to the sum. The 
        // average of these values is at least target / k.
        int average_value = target / k;
        
        // We cannot obtain a sum of target if the smallest value
        // in nums is greater than target / k or if the largest 
        // value in nums is smaller than target / k.
        if  (nums[start] > average_value || average_value > nums.back()) {
            return res;
        }
            
        if (k == 2) {
            return twoSum(nums, target, start);
        }
    
        for (int i = start; i < nums.size(); ++i) {
            if (i == start || nums[i - 1] != nums[i]) {
                for (vector<int>& subset : kSum(nums, static_cast<long>(target) - nums[i], i + 1, k - 1)) {
                    res.push_back({nums[i]});
                    res.back().insert(end(res.back()), begin(subset), end(subset));
                }
            }
        }
                                            
        return res;
    }
	
    vector<vector<int>> twoSum(vector<int>& nums, int target, int start) {
        vector<vector<int>> res;
        int lo = start, hi = nums.size() - 1;
    
        while (lo < hi) {
            int curr_sum = nums[lo] + nums[hi];
            if (curr_sum < target || (lo > start && nums[lo] == nums[lo - 1])) {
                ++lo;
            } else if (curr_sum > target || (hi < nums.size() - 1 && nums[hi] == nums[hi + 1])) {
                --hi;
            } else {
                res.push_back({ nums[lo++], nums[hi--] });
            }
        }
                                                           
        return res;
    }
};;
```

#### Language used for code

C++

#### Expected behavior

The following test case should be added: nums =[1000000000,1000000000,1000000000,1000000000],
target =-294967296
Also, when it is using the above as input, the expected output displayed is [[1000000000,1000000000,1000000000,1000000000]], which is incorrect. 
The correct output should be an empty array since it is impossible to have a negative sum when every element in nums are positive.

#### Screenshots

![image](https://user-images.githubusercontent.com/83045853/173725467-f5bd8bfc-bd47-417e-8db9-4b8d4679cc6d.png)

**Comment by shreyashHake** [comment]
Yes if we change types to (Long or Long Long) we can prevent, addition to negative.
or 
change constraints of target..

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
