### ISSUE TITLE
Missing Test Case - 1048. Longest String Chain

### ISSUE THREAD

**Issue by sgalpha01** [LeetCode-Feedback/LeetCode-Feedback#7759]
#### Your LeetCode username

[r0gue_shinobi](https://leetcode.com/r0gue_shinobi/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

It is missing a test case.

#### Code you used for Submit/Run operation

```python
class Solution:
    def longestStrChain(self, words: List[str]) -> int:
        dp = {}
        res = 1
        for word in sorted(words, key=len):
            dp[word] = 1
            for i in range(len(word)):
                prev = word[:i] + word[i + 1 :]
                if prev in dp:
                    dp[word] = dp[prev] + 1
                    res = max(res, dp[word])

        return res
```

#### Language used for code

Python 🐍

#### Expected behavior

Notice the line `dp[word] = dp[prev] + 1`.
It should be `dp[word] = max(dp[word], dp[prev] + 1)`

It is not handling test cases like:
```
words = ["c", "cd", "ab", "bcd", "abc", "abcd", "abcde"]
```

**Comment by sgalpha01** [comment]
![image](https://user-images.githubusercontent.com/42481964/173738110-4e75adf4-6a84-4bc7-8119-29d32caceb0b.png)

With above case, I'm getting **Wrong Answer**. But it is still getting accepted for the final submission.

![image](https://user-images.githubusercontent.com/42481964/173738271-d1c2b596-928a-48ff-861a-ea9b384f657f.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
