### ISSUE TITLE
211. Add and Search Word - Grammar

### ISSUE THREAD

**Issue by maazadeeb** [LeetCode-Feedback/LeetCode-Feedback#776]
#### Your LeetCode username

maazadeeb

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

There is a minor grammatical error in the note section

#### Expected behavior

The note should be

> You may assume that all words consist of lowercase letters `a-z`.

and not

> You may assume that all words are consist of lowercase letters `a-z`.

There's an extra "are" currently.

**Comment by lc-ivan** [comment]
Hi @maazadeeb  ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @maazadeeb ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 20 LeetCoins as the reward for this feedback. We appreciate your support!
