### ISSUE TITLE
Error in test case for "Check if All the Integers in a Range Are Covered"

### ISSUE THREAD

**Issue by alisa-paraselena** [LeetCode-Feedback/LeetCode-Feedback#7761]
I was working on [this problem](https://leetcode.com/problems/check-if-all-the-integers-in-a-range-are-covered/submissions/) and encountered an incorrect test case:

```
Input: [[1,50]]
1
50
Output: false
Expected: true
```

However true is an incorrect answer for this test case (it is visible just by looking at the test case, not all numbers between 1 and 50 are covered by the range provided).

I am using **a java script environment**.

**Comment by stormsunshine** [comment]
The input `ranges` contains an interval [1,50], which means all integers from 1 and 50 (both inclusive) are covered. Therefore, the result is true.

If you think the result should be false, please provide which numbers are not covered.

**Comment by alisa-paraselena** [comment]
numbers from 2 to 49 included are not covered.

**Comment by alisa-paraselena** [comment]
Sorry nevermind i think i got this one wrong :) excuse me for disturbing
