### ISSUE TITLE
Missing Test Case - 1048. Longest String Chain

### ISSUE THREAD

**Issue by xgu60** [LeetCode-Feedback/LeetCode-Feedback#7763]
#### Your LeetCode username

xgu60

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code failed on the following case but passed all tests.
["c", "ab", "bc", "abc", "abcd"]

#### Code you used for Submit/Run operation

```

class Solution:
    def longestStrChain(self, words: List[str]) -> int:
        dp = {}
        res = 1
        for wd in sorted(words, key=len):
            dp[wd] = 1
            for i in range(len(wd)):
                nwd = wd[:i] + wd[i+1:]
                if nwd in dp:
                    dp[wd] = dp[nwd] + 1
                    res  = max(res, dp[wd])
        return res
```

#### Language used for code

python3

#### Expected behavior

it should fail

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
