### ISSUE TITLE
Typo in DP explore card - Example 1770. Maximum Score from Performing Multiplication Operations

### ISSUE THREAD

**Issue by dhna1217** [LeetCode-Feedback/LeetCode-Feedback#7765]
#### Your LeetCode username
dhna1217

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a small typo in this card.

It should be fixed to 1-indexed as in the question description.

#### Screenshots
![image](https://user-images.githubusercontent.com/9703734/173848219-e3415232-459c-4d01-8376-ad68357f6496.png)

**Comment by dhna1217** [comment]
https://leetcode.com/explore/learn/card/dynamic-programming/631/strategy-for-solving-dp-problems/4100/

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team, and we already added this issue on the Github, it will take some times to fix. We appreciate your support!
