### ISSUE TITLE
Test case is not explained well

### ISSUE THREAD

**Issue by HRKagdi** [LeetCode-Feedback/LeetCode-Feedback#7766]
2021201077_husen

The description of the question and the explaiantion of the test cases do not match.
Input: brackets = [[3,50],[7,10],[12,25]], income = 10
Output: 2.65000
Explanation:
The first 3 dollars you earn are taxed at 50%. You have to pay $3 * 50% = $1.50 dollars in taxes.
The next 7 - 3 = 4 dollars you earn are taxed at 10%. You have to pay $4 * 10% = $0.40 dollars in taxes.
The final 10 - 7 = 3 dollars you earn are taxed at 25%. You have to pay $3 * 25% = $0.75 dollars in taxes. It should be 12 - 7 =5 dollars. Why is it 10???
You have to pay a total of $1.50 + $0.40 + $0.75 = $2.65 dollars in taxes.

Similarly the second test case has not been explained well.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by HRKagdi** [comment]
Problem name is: 2303. Calculate Amount Paid in Taxes

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
