### ISSUE TITLE
Problem 1046 - Unclear Instructions in Question Prompt

### ISSUE THREAD

**Issue by OperaRuss** [LeetCode-Feedback/LeetCode-Feedback#7767]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In this question, users are prompted to execute a simple comparison between stones of different weights.  When two stones are equal, both are destroyed.  When stone weights are unequal, the lesser weight is subtracted from the greater and a stone with weight equal to the difference added back into the pool of stones.  The game is played until at most one stone is left.  

Here is the current text of the prompt:

> You are given an array of integers stones where stones[i] is the weight of the ith stone.
>
>We are playing a game with the stones. On each turn, we choose the heaviest two stones and smash them together. Suppose the heaviest two stones have weights x and y with x <= y. The result of this smash is:
>
>If x == y, both stones are destroyed, and
>If x != y, the stone of weight x is destroyed, and the stone of weight y has new weight y - x.
>At the end of the game, there is at most one stone left.
>
>Return the smallest possible weight of the left stone. If there are no stones left, return 0.

The penultimate line is misleading, and should read "return the smallest possible weight of the stone the remaining stone" or "...of the stone that is left."  The current prompt reads as though there is a left-right ordering of the stones, which is supported by the previous line that the stones are always considered such that the weight of the stone called _x_ is always less than or equal to stone _y_.  While this is logically equivalent to the lightest stone, the statement itself could be made more clear by disambiguating between the two definitions of the word "left."

#### Code you used for Submit/Run operation
n/a

#### Language used for code
n/a 

#### Expected behavior
n/a

#### Screenshots
n/a

#### Additional context
n/a

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
