### ISSUE TITLE
Missing Test Case - 408. Valid Word Abbreviation

### ISSUE THREAD

**Issue by lihe14569** [LeetCode-Feedback/LeetCode-Feedback#7770]
#### Your LeetCode username

lihe14569

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

Testcase: 
"abreviation"
"a9n"
Result: False
Expected:True
But wrong code submit successfully and accepted.

```
// 408. Valid Word Abbreviation
class Solution {
    public boolean validWordAbbreviation(String word, String abbr) {
        int i = 0, j = 0;
        int nums = 0;
        while(i < word.length() &&j < abbr.length()) {
            if(word.charAt(i) == abbr.charAt(j)) {
                i++;
                j++;
                continue;
            } 
                
            if(abbr.charAt(j) <= '0' ||abbr.charAt(j) >= '9') //CODE here should be abbr.charAt(j) > '9
                    return false;
            
            int start = j;
            while(j < abbr.length() && abbr.charAt(j) >= '0' && abbr.charAt(j) <= '9') {
                    j++;
                }
            int step = Integer.valueOf(abbr.substring(start, j));
            i += step;
            
        }
        return i == word.length() && j == abbr.length();
    }
}
```

#### Language used for code

Java

#### Expected behavior

Code is wrong,
Testcase shows expected result, but the wrong code accepted.
Missing this test case:
"abreviation"
"a9n"
Result: Wrong
Expected:True
Wrong code ACCEPTED.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
