### ISSUE TITLE
Incorrect Test Case - 126. Word Ladder II

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#7771]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test case 21 gives below error, not following question constraint of

`
1 <= wordList.length <= 500
`

Error:
`
Invalid Testcase
expected 'wordList' to have 1 <= size <= 500 but got 599
`

Error screenshot:

![image](https://user-images.githubusercontent.com/8236389/173961180-1b033029-5a74-4149-8311-dec901e6ebb1.png)

Test case:
`
"cet"
"ism"
["kid","tag","pup","ail","tun","woo","erg","luz","brr","gay","sip","kay","per","val","mes","ohs","now","boa","cet","pal","bar","die","war","hay","eco","pub","lob","rue","fry","lit","rex","jan","cot","bid","ali","pay","col","gum","ger","row","won","dan","rum","fad","tut","sag","yip","sui","ark","has","zip","fez","own","ump","dis","ads","max","jaw","out","btu","ana","gap","cry","led","abe","box","ore","pig","fie","toy","fat","cal","lie","noh","sew","ono","tam","flu","mgm","ply","awe","pry","tit","tie","yet","too","tax","jim","san","pan","map","ski","ova","wed","non","wac","nut","why","bye","lye","oct","old","fin","feb","chi","sap","owl","log","tod","dot","bow","fob","for","joe","ivy","fan","age","fax","hip","jib","mel","hus","sob","ifs","tab","ara","dab","jag","jar","arm","lot","tom","sax","tex","yum","pei","wen","wry","ire","irk","far","mew","wit","doe","gas","rte","ian","pot","ask","wag","hag","amy","nag","ron","soy","gin","don","tug","fay","vic","boo","nam","ave","buy","sop","but","orb","fen","paw","his","sub","bob","yea","oft","inn","rod","yam","pew","web","hod","hun","gyp","wei","wis","rob","gad","pie","mon","dog","bib","rub","ere","dig","era","cat","fox","bee","mod","day","apr","vie","nev","jam","pam","new","aye","ani","and","ibm","yap","can","pyx","tar","kin","fog","hum","pip","cup","dye","lyx","jog","nun","par","wan","fey","bus","oak","bad","ats","set","qom","vat","eat","pus","rev","axe","ion","six","ila","lao","mom","mas","pro","few","opt","poe","art","ash","oar","cap","lop","may","shy","rid","bat","sum","rim","fee","bmw","sky","maj","hue","thy","ava","rap","den","fla","auk","cox","ibo","hey","saw","vim","sec","ltd","you","its","tat","dew","eva","tog","ram","let","see","zit","maw","nix","ate","gig","rep","owe","ind","hog","eve","sam","zoo","any","dow","cod","bed","vet","ham","sis","hex","via","fir","nod","mao","aug","mum","hoe","bah","hal","keg","hew","zed","tow","gog","ass","dem","who","bet","gos","son","ear","spy","kit","boy","due","sen","oaf","mix","hep","fur","ada","bin","nil","mia","ewe","hit","fix","sad","rib","eye","hop","haw","wax","mid","tad","ken","wad","rye","pap","bog","gut","ito","woe","our","ado","sin","mad","ray","hon","roy","dip","hen","iva","lug","asp","hui","yak","bay","poi","yep","bun","try","lad","elm","nat","wyo","gym","dug","toe","dee","wig","sly","rip","geo","cog","pas","zen","odd","nan","lay","pod","fit","hem","joy","bum","rio","yon","dec","leg","put","sue","dim","pet","yaw","nub","bit","bur","sid","sun","oil","red","doc","moe","caw","eel","dix","cub","end","gem","off","yew","hug","pop","tub","sgt","lid","pun","ton","sol","din","yup","jab","pea","bug","gag","mil","jig","hub","low","did","tin","get","gte","sox","lei","mig","fig","lon","use","ban","flo","nov","jut","bag","mir","sty","lap","two","ins","con","ant","net","tux","ode","stu","mug","cad","nap","gun","fop","tot","sow","sal","sic","ted","wot","del","imp","cob","way","ann","tan","mci","job","wet","ism","err","him","all","pad","hah","hie","aim","ike","jed","ego","mac","baa","min","com","ill","was","cab","ago","ina","big","ilk","gal","tap","duh","ola","ran","lab","top","gob","hot","ora","tia","kip","han","met","hut","she","sac","fed","goo","tee","ell","not","act","gil","rut","ala","ape","rig","cid","god","duo","lin","aid","gel","awl","lag","elf","liz","ref","aha","fib","oho","tho","her","nor","ace","adz","fun","ned","coo","win","tao","coy","van","man","pit","guy","foe","hid","mai","sup","jay","hob","mow","jot","are","pol","arc","lax","aft","alb","len","air","pug","pox","vow","got","meg","zoe","amp","ale","bud","gee","pin","dun","pat","ten","mob"]
`

![image](https://user-images.githubusercontent.com/8236389/173961121-8c549456-8812-4019-a143-8fad05d9806e.png)

#### Code you used for Submit/Run operation

```
var findLadders = function (bw, ew, W) {
    let n = bw.length;

    let setW = new Set(W);
    setW.delete(bw);

    let min = Infinity;
    let ans = [];
    function bt(i, a, pathSet) {
        if (pathSet.size > min) {
            return;
        }

        if (a.join("") === ew) {
            if (pathSet.size < min) {
                min = pathSet.size;
                ans = [[bw, ...pathSet]];
            } else if (pathSet.size === min) {
                ans.push([bw, ...pathSet]);
            }
        }

        for (let i = 0; i < n; i++) {
            for (let j = 0; j < 26; j++) {
                let ch = String.fromCharCode("a".charCodeAt(0) + j);

                let temp = a[i];
                a[i] = ch;
                if (setW.has(a.join(""))) {
                    if (!pathSet.has(a.join(""))) {
                        pathSet.add(a.join(""));
                        bt(i, a, pathSet);
                        pathSet.delete(a.join(""));
                    }
                }
                a[i] = temp;
            }
        }
    }

    let a = bw.split("");
    bt(0, a, new Set());
    return ans;
};
```

#### Language used for code
JavaScript

#### Expected behavior

Test case 21 does not follow question constraints, fails in run mode. gives TLE on submit.

**Comment by manoharreddyporeddy** [comment]
With above test case

Default code will get this result:

`
var findLadders = function(beginWord, endWord, wordList) {
    
};
`

**Comment by LC-Pam** [comment]
Thank you for your time. We received wrong answer when we submitted your code, if you have code submission accepted link, please send to us. We appreciate your support!

**Comment by manoharreddyporeddy** [comment]
Code error link - https://leetcode.com/submissions/detail/720872107/

Screenshot
![image](https://user-images.githubusercontent.com/8236389/174421644-c542548e-7838-4247-a76b-4ded419a02b9.png)

Code

```
var findLadders = function (bw, ew, W) {
    let n = bw.length;

    let setW = new Set(W);
    setW.delete(bw);

    let min = Infinity;
    let ans = [];
    function bt(i, a, pathSet) {
        if (pathSet.size > min) {
            return;
        }

        if (a.join("") === ew) {
            if (pathSet.size < min) {
                min = pathSet.size;
                ans = [[bw, ...pathSet]];
            } else if (pathSet.size === min) {
                ans.push([bw, ...pathSet]);
            }
        }

        for (let i = 0; i < n; i++) {
            for (let j = 0; j < 26; j++) {
                let ch = String.fromCharCode("a".charCodeAt(0) + j);

                let temp = a[i];
                a[i] = ch;
                if (setW.has(a.join(""))) {
                    if (!pathSet.has(a.join(""))) {
                        pathSet.add(a.join(""));
                        bt(i, a, pathSet);
                        pathSet.delete(a.join(""));
                    }
                }
                a[i] = temp;
            }
        }
    }

    let a = bw.split("");
    bt(0, a, new Set());
    return ans;
};

```

Test case:

```
"cet"
"ism"
["kid","tag","pup","ail","tun","woo","erg","luz","brr","gay","sip","kay","per","val","mes","ohs","now","boa","cet","pal","bar","die","war","hay","eco","pub","lob","rue","fry","lit","rex","jan","cot","bid","ali","pay","col","gum","ger","row","won","dan","rum","fad","tut","sag","yip","sui","ark","has","zip","fez","own","ump","dis","ads","max","jaw","out","btu","ana","gap","cry","led","abe","box","ore","pig","fie","toy","fat","cal","lie","noh","sew","ono","tam","flu","mgm","ply","awe","pry","tit","tie","yet","too","tax","jim","san","pan","map","ski","ova","wed","non","wac","nut","why","bye","lye","oct","old","fin","feb","chi","sap","owl","log","tod","dot","bow","fob","for","joe","ivy","fan","age","fax","hip","jib","mel","hus","sob","ifs","tab","ara","dab","jag","jar","arm","lot","tom","sax","tex","yum","pei","wen","wry","ire","irk","far","mew","wit","doe","gas","rte","ian","pot","ask","wag","hag","amy","nag","ron","soy","gin","don","tug","fay","vic","boo","nam","ave","buy","sop","but","orb","fen","paw","his","sub","bob","yea","oft","inn","rod","yam","pew","web","hod","hun","gyp","wei","wis","rob","gad","pie","mon","dog","bib","rub","ere","dig","era","cat","fox","bee","mod","day","apr","vie","nev","jam","pam","new","aye","ani","and","ibm","yap","can","pyx","tar","kin","fog","hum","pip","cup","dye","lyx","jog","nun","par","wan","fey","bus","oak","bad","ats","set","qom","vat","eat","pus","rev","axe","ion","six","ila","lao","mom","mas","pro","few","opt","poe","art","ash","oar","cap","lop","may","shy","rid","bat","sum","rim","fee","bmw","sky","maj","hue","thy","ava","rap","den","fla","auk","cox","ibo","hey","saw","vim","sec","ltd","you","its","tat","dew","eva","tog","ram","let","see","zit","maw","nix","ate","gig","rep","owe","ind","hog","eve","sam","zoo","any","dow","cod","bed","vet","ham","sis","hex","via","fir","nod","mao","aug","mum","hoe","bah","hal","keg","hew","zed","tow","gog","ass","dem","who","bet","gos","son","ear","spy","kit","boy","due","sen","oaf","mix","hep","fur","ada","bin","nil","mia","ewe","hit","fix","sad","rib","eye","hop","haw","wax","mid","tad","ken","wad","rye","pap","bog","gut","ito","woe","our","ado","sin","mad","ray","hon","roy","dip","hen","iva","lug","asp","hui","yak","bay","poi","yep","bun","try","lad","elm","nat","wyo","gym","dug","toe","dee","wig","sly","rip","geo","cog","pas","zen","odd","nan","lay","pod","fit","hem","joy","bum","rio","yon","dec","leg","put","sue","dim","pet","yaw","nub","bit","bur","sid","sun","oil","red","doc","moe","caw","eel","dix","cub","end","gem","off","yew","hug","pop","tub","sgt","lid","pun","ton","sol","din","yup","jab","pea","bug","gag","mil","jig","hub","low","did","tin","get","gte","sox","lei","mig","fig","lon","use","ban","flo","nov","jut","bag","mir","sty","lap","two","ins","con","ant","net","tux","ode","stu","mug","cad","nap","gun","fop","tot","sow","sal","sic","ted","wot","del","imp","cob","way","ann","tan","mci","job","wet","ism","err","him","all","pad","hah","hie","aim","ike","jed","ego","mac","baa","min","com","ill","was","cab","ago","ina","big","ilk","gal","tap","duh","ola","ran","lab","top","gob","hot","ora","tia","kip","han","met","hut","she","sac","fed","goo","tee","ell","not","act","gil","rut","ala","ape","rig","cid","god","duo","lin","aid","gel","awl","lag","elf","liz","ref","aha","fib","oho","tho","her","nor","ace","adz","fun","ned","coo","win","tao","coy","van","man","pit","guy","foe","hid","mai","sup","jay","hob","mow","jot","are","pol","arc","lax","aft","alb","len","air","pug","pox","vow","got","meg","zoe","amp","ale","bud","gee","pin","dun","pat","ten","mob"]
```



Detailed Explanation
------------------

For above test case
For above code

When you submit, it gives
`Time Limit Exceeded` 

When you run it, it gives 
`Invalid Testcase
expected 'wordList' to have 1 <= size <= 500 but got 599`

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. This is because 2 new test cases were added to the problem.  Our team will keep this on the to do list.
We appreciate your support!
