### ISSUE TITLE
532. K-diff Pairs in an Array

### ISSUE THREAD

**Issue by wangmin239** [LeetCode-Feedback/LeetCode-Feedback#7774]
#### Your LeetCode username

jushui

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Input:nums = [1, 4, 1], k = 3;
an integer pair (nums[0], nums[1])  is different from (nums[1], nums[2]), and the two integer pairs meet the below requirements.
1) 0 <= i, j < nums.length
2) i != j
3) |nums[i] - nums[j]| == k

So the answer of the above example seems like to be 2, but the official  answer is 1. 

#### Code you used for Submit/Run operation

```
// 532 k-diff-pairs-in-an-array
class Solution {
public:
    int findPairs(vector<int>& nums, int k) {
        unordered_map<int, vector<int>> dataPair;
        int len = nums.size();
        
        /* store the index */
        for (int i = 0; i < len; i++) {
            dataPair[nums[i]].push_back(i);

        }
        
        /* get the count of the integral pairs meet the requirements */
        auto getCnt = [](int val, int index, unordered_map<int, vector<int>>& pairsMap) {
            if (pairsMap.count(val) == 0) {
                return 0;
            }
            
            auto vec = pairsMap[val];
            int len = vec.size();
            int cnt = 0;
            for (int i = 0; i < len; i++) {
                if (vec[i] > index) {
                    cnt = 1;
                    break;
                }
            }
            
            return cnt;
        };
        
        /* the case of the K is zero */
        int ans = 0;
        if (k == 0) {
            for (const auto [_, vec] : dataPair) {
                if (vec.size() > 1) {
                    ans++;
                }
            }
            return ans;
        }
        /* the case of the K is no-zero */       
        unordered_map<int, int> isVisited;
        for (int i = 0; i < len; i++) {
            int num = nums[i];
            if (isVisited.count(num) > 0) {
                continue;
            }
            ans += getCnt(num + k, i, dataPair) + getCnt(num - k, i, dataPair);
            isVisited[num]++;
        }
        
        return ans;
    }
};
```

#### Language used for code

C++

#### Screenshots

![image](https://user-images.githubusercontent.com/20694868/173972698-53f0ed9a-1d25-4ca1-80fe-2ef5bb381f6a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by wangmin239** [comment]
@LC-Pam Thanks for your response, the contents of the issue had been updated.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, the code that you provided received wrong answer. Please feel free to refer the discuss section of the problem to see how other users' have optimized their codes! We appreciate your support!

**Comment by LC-Pam** [comment]
In additional,the reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.

We appreciate your time and support! If you have any other questions, please don't hesitate to let us know.
