### ISSUE TITLE
532. K-diff Pairs in an Array

### ISSUE THREAD

**Issue by wangmin239** [LeetCode-Feedback/LeetCode-Feedback#7775]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
jushui
**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
输入用例为：

nums = [1, 4, 1], k = 3
整数对{1，4} 和 { 4， 1} 是不同的整数对，满足题设要求：
1）0 <= i < j < nums.length
2）|nums[i] - nums[j]| == k

所以，{nums[0], nums[1]} 和 {nums[1], nums[2}，是符合题设的答案，
可官方答案是1.

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/20694868/173974756-9c4e01e9-0b88-48c9-85c2-f45d5f33d651.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，在与相关团队核实后： “k-diff 数对定义为一个整数对 (nums[i], nums[j])” 。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
