### ISSUE TITLE
34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#778]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 2: Binary Search has incorrect analysis

#### Expected behavior

> Time complexity : O(log 10(n))

> Because binary search cuts the search space roughly in half on each iteration, there can be at most ceil⌈log 10 (n)⌉ iterations. Binary search is invoked twice, so the overall complexity is logarithmic.

Base 10 is not incorrect as I had stated earlier but inaccurate. Even though base 10 is correct asymptotically there exists a more accurate solution. Binary search has a well known time complexity of O(log 2(n)).

Furthermore

> at most ceil⌈log 10 (n)⌉ iterations

is incorrect. There are at most ceil⌈log 2 (n)⌉ iterations. 

Let us take n=10

ceil⌈log 10 (n)⌉ = 1

whereas actually ceil⌈log 2 (n)⌉ = 4 is correct. There is more than 1 iteration for n=10.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thanks for your time. The team has reviewed your report and responded that there is no error here because the constant doesn't impact time complexity.

**Comment by leet212** [comment]
Hello @lc-pam 
Thank you for your response. I wasn't detailed enough in the issue so I have updated it.

**Comment by lc-pam** [comment]
Hi @leet212 ,
Thanks, I've passed the updated content to the team.

**Comment by lc-pam** [comment]
Hi @leet212 
Thanks for the time. The team provided an explanation and [wiki link](https://en.wikipedia.org/wiki/Big_O_notation) about what big-O notation is. 
<img width="700" alt="Screen Shot 2020-08-18 at 2 58 14 PM" src="https://user-images.githubusercontent.com/67175512/90570142-fc5a2700-e163-11ea-8b76-0a3a7bcda4ff.png">
