### ISSUE TITLE
Missing Test Case - 2307. Check for Contradictions in Equations (Standard Solution Also Fails)

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#7780]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution **and the standard solution** fails on the following testcase:
[["aaa","aab"],["aab","aac"],["aac","aad"],["aad","aae"],["aae","aaf"],["aaf","aag"],["aag","aah"],["aah","aai"],["aai","aaj"],["aaj","aak"],["aak","aal"],["aal","aam"],["aam","aan"],["aan","aao"],["aao","aap"],["aap","aaq"],["aaq","aar"],["aar","aas"],["aas","aat"],["aat","aau"],["aau","aav"],["aav","aaw"],["aaw","aax"],["aax","aay"],["aay","aaz"],["aaz","aba"],["aba","abb"],["abb","abc"],["abc","abd"],["abd","abe"],["abe","abf"],["abf","abg"],["abg","abh"],["abh","abi"],["abi","abj"],["abj","abk"],["abk","abl"],["abl","abm"],["abm","abn"],["abn","abo"],["abo","abp"],["abp","abq"],["abq","abr"],["abr","abs"],["abs","abt"],["abt","abu"],["abu","abv"],["abv","abw"],["abw","abx"],["abx","aby"],["aby","abz"],["abz","aca"],["aca","acb"],["acb","acc"],["acc","acd"],["acd","ace"],["ace","acf"],["acf","acg"],["acg","ach"],["ach","aci"],["aci","acj"],["acj","ack"],["ack","acl"],["acl","acm"],["acm","acn"],["acn","aco"],["aco","acp"],["acp","acq"],["acq","acr"],["acr","acs"],["acs","act"],["act","acu"],["acu","acv"],["acv","acw"],["acw","acx"],["acx","acy"],["acy","acz"],["acz","ada"],["ada","adb"],["adb","adc"],["adc","add"],["add","ade"],["ade","adf"],["adf","adg"],["adg","adh"],["adh","adi"],["adi","adj"],["adj","adk"],["adk","adl"],["adl","adm"],["adm","adn"],["adn","ado"],["ado","adp"],["adp","adq"],["adq","adr"],["adr","ads"],["ads","adt"],["adt","adu"],["adu","adv"],["adv","adw"],["adw","adx"],["adx","ady"],["ady","adz"],["adz","aea"],["aea","aeb"],["aeb","aec"],["aec","aed"],["aed","aee"],["aee","aef"],["aef","aeg"],["aeg","aeh"],["aeh","aei"],["aei","aej"],["aej","aek"],["aek","ael"],["ael","aem"],["aem","aen"],["aen","aeo"],["aeo","aep"],["aep","aeq"],["aeq","aer"],["aer","aes"],["aes","aet"],["aet","aeu"],["aeu","aev"],["aev","aew"],["aew","aex"],["aex","aey"],["aaa","afa"],["afa","afb"],["afb","afc"],["afc","afd"],["afd","afe"],["afe","aff"],["aff","afg"],["afg","afh"],["afh","afi"],["afi","afj"],["afj","afk"],["afk","afl"],["afl","afm"],["afm","afn"],["afn","afo"],["afo","afp"],["afp","afq"],["afq","afr"],["afr","afs"],["afs","aft"],["aft","afu"],["afu","afv"],["afv","afw"],["afw","afx"],["afx","afy"],["afy","afz"],["afz","aga"],["aga","agb"],["agb","agc"],["agc","agd"],["agd","age"],["age","agf"],["agf","agg"],["agg","agh"],["agh","agi"],["agi","agj"],["agj","agk"],["agk","agl"],["agl","agm"],["agm","agn"],["agn","ago"],["ago","agp"],["agp","agq"],["agq","agr"],["agr","ags"],["ags","agt"],["agt","agu"],["agu","agv"],["agv","agw"],["agw","agx"],["agx","agy"],["agy","agz"],["agz","aha"],["aha","ahb"],["ahb","ahc"],["ahc","ahd"],["ahd","ahe"],["ahe","ahf"],["ahf","ahg"],["ahg","ahh"],["ahh","ahi"],["ahi","ahj"],["ahj","ahk"],["ahk","ahl"],["ahl","ahm"],["ahm","ahn"],["ahn","aho"],["aho","ahp"],["ahp","ahq"],["ahq","ahr"],["ahr","ahs"],["ahs","aht"],["aht","ahu"],["ahu","ahv"],["ahv","ahw"],["ahw","ahx"],["ahx","ahy"],["ahy","ahz"],["ahz","aia"],["aia","aib"],["aib","aic"],["aic","aid"],["aid","aie"],["aie","aif"],["aif","aig"],["aig","aih"],["aih","aii"],["aii","aij"],["aij","aik"],["aik","ail"],["ail","aim"],["aim","ain"],["ain","aio"],["aio","aip"],["aip","aiq"],["aiq","air"],["air","ais"],["ais","ait"],["ait","aiu"],["aiu","aiv"],["aiv","aiw"],["aiw","aix"],["aix","aiy"],["aiy","aiz"],["aiz","aja"],["aja","ajb"],["ajb","ajc"],["ajc","ajd"],["ajd","aje"],["aje","ajf"],["ajf","ajg"],["ajg","ajh"],["ajh","aji"],["aji","ajj"],["ajj","ajk"],["ajk","ajl"],["ajl","ajm"],["ajm","ajn"],["ajn","ajo"],["ajo","ajp"],["ajp","ajq"],["ajq","ajr"],["ajr","ajs"],["ajs","ajt"],["ajt","aju"],["aju","ajv"],["ajv","ajw"],["ajw","aey"]]
[9.744,9.745,9.747,9.750,9.751,9.754,9.756,9.757,9.759,9.762,9.764,9.765,9.768,9.769,9.771,9.774,9.775,9.778,9.780,9.781,9.784,9.785,9.787,9.790,9.792,9.793,9.795,9.798,9.799,9.802,9.804,9.805,9.807,9.810,9.812,9.813,9.816,9.817,9.819,9.822,9.824,9.825,9.827,9.830,9.831,9.834,9.836,9.837,9.840,9.841,9.843,9.846,9.847,9.850,9.852,9.853,9.855,9.858,9.860,9.861,9.864,9.865,9.867,9.870,9.871,9.874,9.876,9.877,9.880,9.881,9.883,9.886,9.888,9.889,9.891,9.894,9.895,9.898,9.900,9.901,9.904,9.905,9.907,9.910,9.911,9.914,9.916,9.917,9.919,9.922,9.924,9.925,9.928,9.929,9.931,9.934,9.936,9.937,9.939,9.942,9.943,9.946,9.948,9.949,9.951,9.954,9.956,9.957,9.960,9.961,9.963,9.966,9.967,9.970,9.972,9.973,9.976,9.977,9.979,9.982,9.984,9.985,9.987,9.990,9.991,9.994,9.996,9.997,9.743,9.746,9.748,9.749,9.752,9.753,9.755,9.758,9.760,9.761,9.763,9.766,9.767,9.770,9.772,9.773,9.776,9.777,9.779,9.782,9.783,9.786,9.788,9.789,9.791,9.794,9.796,9.797,9.800,9.801,9.803,9.806,9.808,9.809,9.811,9.814,9.815,9.818,9.820,9.821,9.823,9.826,9.828,9.829,9.832,9.833,9.835,9.838,9.839,9.842,9.844,9.845,9.848,9.849,9.851,9.854,9.856,9.857,9.859,9.862,9.863,9.866,9.868,9.869,9.872,9.873,9.875,9.878,9.879,9.882,9.884,9.885,9.887,9.890,9.892,9.893,9.896,9.897,9.899,9.902,9.903,9.906,9.908,9.909,9.912,9.913,9.915,9.918,9.920,9.921,9.923,9.926,9.927,9.930,9.932,9.933,9.935,9.938,9.940,9.941,9.944,9.945,9.947,9.950,9.952,9.953,9.955,9.958,9.959,9.962,9.964,9.965,9.968,9.969,9.971,9.974,9.975,9.978,9.980,9.981,9.983,9.986,9.988,9.989,9.992,9.993,9.995,9.998]

#### Code you used for Submit/Run operation

```
class Solution:
    def checkContradictions(self, equations: List[List[str]], values: List[float]) -> bool:

        edges = defaultdict(set)
        for j,(x,y) in enumerate(equations):
            edges[x].add((y,values[j])) 
            edges[y].add((x,1/values[j]))  #图中的边一定要成对添加
        val = {}
        ans = False #初始默认没有矛盾

        def dfs(node,v):
            nonlocal ans
            if ans: #已经有矛盾就不浪费时间了
                return
            if node in val:
                if abs(val[node]/v-1.)>1e-5: #题目明确说不超过1e-5视为相同值，由于判断是否矛盾本身也是根据比值关系，因此这里用相对误差不超过1e-5来判断
                    ans=True
                return #搜过的点，不管有没有矛盾，都应直接return，否则程序就会死循环         
            val[node]=v
            for nei,rat in edges[node]:
                dfs(nei,v/rat)
        
        for x,y in equations:
            if x not in val: # 如果x还没有值，y也一定没有，这时说明遇到了一个新的连通分量
                dfs(x,1.)
        return ans
```

#### Language used for code

Python3

#### Expected behavior

The correct output should be **true**, meaning there's a contradiction (with absolute difference > 1e-5).

The testcase is designed as follows:
Try to generate two long chains with products being slightly different (relative error ~1e-20). These two products are large numbers, so their absolute difference exceeds 1e-5. Then use these two chains to connect variable "aaa" with "aey".

#### Screenshots

We can easily verify the product of these two chains are indeed different, using mathematica:
![image](https://user-images.githubusercontent.com/11583428/174030474-a124ee66-f6a4-40a5-ae82-a8a22373eb41.png)

**Comment by hqztrue** [comment]
Two smaller testcases, where the output should be true:
[["aaa","aab"],["aab","aac"],["aac","aad"],["aad","aae"],["aaa","aag"],["aag","aah"],["aah","aai"],["aai","aae"]]
[2.000,2.010,2.030,2.060,1.990,2.020,2.040,2.050]
![image](https://user-images.githubusercontent.com/11583428/174037681-beab8352-37f3-46fa-926b-50c876609738.png)


[["zzz","aaa"],["aaa","aab"],["aab","aac"],["aac","aad"],["aad","aae"],["aaa","aag"],["aag","aah"],["aah","aai"],["aai","aae"]]
[0.00001,0.500000,0.497512,0.492611,0.485437,0.502513,0.495050,0.490196,0.487805]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The statement mentioned that we compare floating-point numbers we use some epsilon.
These test case depend on a smaller epsilon and we do not consider them. We appreciate your support!
