### ISSUE TITLE
2297 标题和链接需要更新

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#7781]
**你的 LeetCode 用户名**
stormsunshine

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
请参考 #7757。
美国站的 2297 链接：[2297. Jump Game VIII](https://leetcode.com/problems/jump-game-viii)
这道题的标题原本是 Jump Game IX，由于这道题之前的跳跃游戏（Jump Game）系列只有 7 道题，这道题是跳跃游戏系列的第 8 题，因此标题应该是 Jump Game VIII。
目前美国站的标题也链接已经更新，中国站的标题也应该同步更新，链接应该同步更新成 https://leetcode.cn/problems/jump-game-viii。

**期望行为**
中国站的 2297 的标题和链接应该和美国站一致。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：stormsunshine 给予积分奖励，请查收。
