### ISSUE TITLE
Don't check return values in 155. Min Stack

### ISSUE THREAD

**Issue by nampi** [LeetCode-Feedback/LeetCode-Feedback#7782]
#### Your LeetCode username

princess1211

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In question description there is a requirement **void pop() removes the element on the top of the stack.**
The return values aren't checked in the test cases. We can return any value in pop function, but the solution is marked as correct solution.
Example:
["MinStack","push","push","pop","top"]
[[],[1],[2],[],[]]
Run code result:
Output:
[null,null,null,null,1]
Expected:
[null,null,null,null,1]

But in fact output was: [null,null,null,4,1]

#### Code you used for Submit/Run operation

```
class MinStack:

    def __init__(self):
        self.a = []
        self.b = [] # stack for minimums
        

    def push(self, val: int) -> None:
        self.a.append(val)
        if not self.b:
            self.b.append(val)
        else:
            self.b.append(min(val, self.b[-1]))

    def pop(self) -> None:
        self.b.pop()
        self.a.pop()
        return 4
        

    def top(self) -> int:
        return self.a[-1]

    def getMin(self) -> int:
        return self.b[-1]
```

#### Language used for code

Python3

#### Expected behavior

I guess that if function returns anything it should be in output:
Current behaviour: [null,null,null,null,1]
Expected behaviour: [null,null,null,4,1]

**Comment by stormsunshine** [comment]
Why do you return a value in `pop` when the return type is defined as None? I think the returned value is ignored in this case.
