### ISSUE TITLE
Rounding in test case -- 1870 - Minimum Speed to Arrive on Time

### ISSUE THREAD

**Issue by mscuthbert** [LeetCode-Feedback/LeetCode-Feedback#7783]
#### Your LeetCode username

msacuthbert

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem asks about the minimum speed to make it to a destination under a certain time, given lengths of each intermediary step, with the caveat that (SPOILER) all but the last have to be math.ceil integers.  The problem is looking for exact integer solutions, but the issue is that various ways of solving the problem give different results depending on order and rely more on knowing floating point operations in various OSes (including what leetcode is using) and languages than on programming.

The particular problematic test case is:

```
distances = [4, 2, 3]
hour = 2.03
```

this sounds like an intuitive problem for humans: the first two trains will take at least one hour (since it's a ceil operation), so the whole Q is what will make the last train, that takes 3 kms, arrive in 0.3 hours.  We can figure this out in our heads: to go 3 kms in 0.3 hours you need to go 100 kph.  But look at the different possible implementations (here in Python, but similar in other languages):

```
tot_time = 0
for d in dist[:n-1]:
     tot_time += math.ceil(d / speed)
tot_time += dist[-1] / speed  # add last one.
if tot_time == speed: return speed
```

or you might realize that you need to add the last speed at the end so why not set it in the initialization and get a few ms speed up?

```
tot_time = dist[-1] / speed  # last time.
for d in dist[:n]:
     tot_time += d / speed
if tot_time == speed: return speed
```

Looks identical, right?  Well, put the intermediate results into 64-bit Python 3 and look:

```
>>> 1.0 + 1.0 + 3/100
2.03
>>> 3/100 + 1.0 + 1.0
2.0300000000000002
```

the problem is that floating-point addition is not commutative (INSERT WOW EMOJI HERE).

Okay, so a smart programmer should be looking for some sort of "close enough" solution, like instead of doing actual equality, she or he could do:

```
if tot_time == round(speed, 8): return speed
```
or

```
if abs(tot_time - speed) < 0.000000001: return speed
```

Ah, but there is another test case, which added the extreme:

```
[1,1,100000]
2.01
```
and because speed can be up to 10**7, it severely punishes premature rounding even with many, many digits (I tried up to 10 and still found that 9,999,996 seemed close enough but only 10,000,000 worked)

The possible solutions seem to me to be:

* Change the "hour" params to always be (int k)+(2**-n) so that they have exact rounding.
* Change the last element of distance so that it always divides either evenly or into a power of 2 remainder with the answer.
* Remove test cases that require floating point arithmetic and require totally unrealistic train speeds (so that comparing rounding early is okay)
* Accept all answers that arrive within Epsilon of the hour, such as 1/3600 which is specified in the problem.   (Who cares if you are one second late to a meeting?)
* Change the difficulty to "Hard", as it's a problem like "Text Justification" which is primarily about thinking of the corner cases.

My spidey-sense immediately on seeing the problem was "ugh, I'm going to need to think about floating-point equality just like the question writer or I'm *@#$('ed. " and this turned out to be correct.

#### Code you used for Submit/Run operation

This code fails:

```python
import math
class Solution:
    def minSpeedOnTime(self, dist: List[int], hour: float) -> int:
        max_speed = 10_000_000  # fast train
        last_dist = dist.pop()
        if len(dist) + last_dist / max_speed > hour:
            return -1
        
        l = 1
        r = max_speed
        while l <= r:
            mid = (l + r) // 2
            tot_time = last_dist / mid
            for d in dist:
                tot_time += math.ceil(d / mid)

            # print(tot_time, hour, mid, l, r)  # , slow_time)
            if hour == tot_time:
                return mid
            elif hour < tot_time:
                l = mid + 1
            else:
                r = mid - 1
            
        return mid  # should not happen
```

so does this:

```python
...
            if hour == tot_time:
                return mid
            elif l == r:    # <-- changed here!
                if tot_time > hour:
                    return mid + 1
                else:
                    return mid
            elif hour < tot_time:
...
```

and so does this:

```python
...
            if hour == round(tot_time, 8):     # <-- changed here!
                return mid
            elif hour < tot_time:
...
```

but this passes:

```
import math
class Solution:
    def minSpeedOnTime(self, dist: List[int], hour: float) -> int:
        max_speed = 10_000_000  # fast train
        last_dist = dist.pop()
        if len(dist) + last_dist / max_speed > hour:
            return -1
        
        l = 1
        r = max_speed
        while l <= r:
            mid = (l + r) // 2
            tot_time = last_dist / mid
            for d in dist:
                tot_time += math.ceil(d / mid)

            # print(tot_time, hour, mid, l, r)  # , slow_time)
            if hour == tot_time:
                return mid
            elif l == r:
                if round(tot_time, 6) > hour:    # <-- changed here!
                    return mid + 1
                else:
                    return mid
            elif hour < tot_time:
                l = mid + 1
            else:
                r = mid - 1
                
        return mid  # should not happen
```

#### Language used for code

Python3

#### Expected behavior

Cross-language problems should not be dependent on floating-point equality.  It does not matter how many digits one variable is constrained to if those digits are not multiples of powers of two OR rounding comparisons are not accepted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
The problem does not have one author. Many people contributed and tested it.
There is a standard way to compare doubles and using good epsilon should be enough.
We will keep the problem without changes. 
We appreciate your support!

**Comment by mscuthbert** [comment]
Thanks for investigating and replying even if the result wasn't what I desired. I appreciate the great consideration by you and your team.
