### ISSUE TITLE
1695. Maximum Erasure Value

### ISSUE THREAD

**Issue by Cyrex2142** [LeetCode-Feedback/LeetCode-Feedback#7784]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Fairly new with leetcode however I knocked a quick looping solution for this one and I thought it worked however I am getting a failed result for one of the testcases in which I attained a higher score than the expected output, even comparing lists the sub-array contains no duplicates etc.

Am I missing a criteria here or have I stumbled across a bug?

code below and results image attached.

#### Code you used for Submit/Run operation
```
class Solution(object):
    def maximumUniqueSubarray(self, nums):
        subArr = []
        i = 0
        if len(nums) > 1:
            while i < (len(nums) - 1):
                for val in nums:
                    if val in subArr:
                        i += 1
                    else:
                        subArr.append(val)
                        i += 1
        else:
            subArr.append(nums[0])
            
        result = 0
        for val in subArr:
            result += val
        return result
```
#### Language used for code
Python

#### Expected behavior
Given the way the questions posed I assumed that the maximum erasure value would be the highest achievable value using only unique values in the sub-array, which is technically 24,846, however the test case returns it as 16,911?

#### Screenshots
![alt text](https://assets.leetcode.com/users/images/9895b1b3-f2ca-4018-a94f-e571e0324758_1655032171.5329316.png)

#### Additional context
Maybe I am misinterpreting? Was just refered here by the site support team.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, the code that you provided received wrong answer, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
