### ISSUE TITLE
Missing Test Case - 2065. Maximum Path Quality of a Graph

### ISSUE THREAD

**Issue by SubinNair97** [LeetCode-Feedback/LeetCode-Feedback#7787]
#### Your LeetCode username
subin_nair

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ &#9745; ] Missing Test Cases 

#### Description of the bug

The code below Passed All Test Cases and was Accepted, but I found a Test Case that it doesn’t cover.
It fails in the following Test Case (a node with a degree of 3 or 4 with all those nodes being a part of solution) :

values = [1,2,3,4]
edges = [[0,1,10],[0,2,10],[0,3,10]]
maxTime =100

#### Code you used for Submit/Run operation

```
class Solution:
    def maximalPathQuality(self, quality: List[int], edges: List[List[int]], maxTime: int) -> int:
        graph, sol = defaultdict(list), []
        for x, y, time in edges:
            graph[x].append((y, time))
            graph[y].append((x, time))

        def dfs(node, time, qual):
            if node == 0: sol.append(qual)
            new_qual = qual
            for nxt_node, nxt_time in graph[node]:
                if time + nxt_time <= maxTime:
                    if vis[nxt_node] + 1 >= 4: return -inf
                    vis[nxt_node] += 1
                    new_qual = max(dfs(nxt_node, nxt_time + time, qual + quality[nxt_node] * (vis[nxt_node] == 1)), new_qual)
                    vis[nxt_node] -= 1
            return new_qual

        vis = defaultdict(int, {0: 1})
        dfs(0, 0, quality[0])
        return max(sol)
```

#### Language used for code

Python

#### Expected behavior

Output: 8
Expected: 10

#### Screenshots

![image](https://user-images.githubusercontent.com/88146938/174114085-4c77533a-1edf-42ed-9561-fa4e1315afe5.png)

#### Additional context

The code is failing on the mentioned Test Case because of the below statement which prevents the 3rd node connected to node 0 from being considered.
```
if vis[nxt_node] + 1 >= 4: return -inf
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by SubinNair97** [comment]
Thank you !!
Its a pleasure to contribute to the Test Cases. 😃
