### ISSUE TITLE
Needs to Change the Difficulty and Add a Follow-up Requirement - 786.K-th Smallest Prime Fraction

### ISSUE THREAD

**Issue by CarlCzerny837** [LeetCode-Feedback/LeetCode-Feedback#7793]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The solution with O(n^2*logn) complexity can be accepted now. But this solution is too easy to be marked as "Hard". If a interviewer uses it in a real interview, the expected solution should be using binary search. So the difficulty should be changed from "Hard" to "Medium", and a follow-up should be added: Can you solve it in O(nlogC) complexity?

Code you used for Submit/Run operation

The time complexity of the code below is O(n^2*logn).
```
class Solution:
    def kthSmallestPrimeFraction(self, arr: List[int], k: int) -> List[int]:

        def cmp(x,y):
            return x[0]*y[1]-x[1]*y[0]

        fracs = []
        for i in range(len(arr)):
            for j in range(i):
                fracs.append([arr[j],arr[i]])
        return sorted(fracs,key=cmp_to_key(cmp))[k-1]
```

The time complexity of the code below is O(nlogC)
```
class Solution:
    def kthSmallestPrimeFraction(self, arr: List[int], k: int) -> List[int]:

        n = len(arr)
        left, right = 0.0, 1.0

        while True:
            mid = (left + right) / 2
            i, count = -1, 0
            x, y = 0, 1
            
            for j in range(1, n):
                while arr[i + 1] / arr[j] < mid:
                    i += 1
                    if arr[i] * y > arr[j] * x:
                        x, y = arr[i], arr[j]
                count += i + 1

            if count == k:
                return [x, y]
            
            if count < k:
                left = mid
            else:
                right = mid
```

Language used for code
Python3

Expected behavior
1.The difficulty should be changed from "Hard" to "Medium"
2.A follow-up requirement should be added:  Can you solve it in O(nlogC) time complexity?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
