### ISSUE TITLE
139. Word Break

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#780]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approaches have incorrect analysis

#### Expected behavior

> Time complexity : O(n^2). Two loops are their to fill dp array

For n^2 states linear work is done in the form of substring creation. Should be O(n^3).

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
