### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#7802]
#### Your LeetCode username

yumkam

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My binary-search/prefix-sum based solution was [Accepted](https://leetcode.com/submissions/detail/724466210/)
... but it fails local test within specified constraints:
target = 823600661 (arbitrary)
nums = sequence of numbers from 1 to 88566 (anything so that prefix sum > INT_MAX).
UBSAN: runtime error: signed integer overflow: 2147450880 + 65536 cannot be represented in type 'int'
Expected result: 9847
Got result: 29876

(unsurprisingly; 10^5 * 10^5 = 10^10 > INT_MAX; typical 'two pointers' O(n) solution would not be affected - rolling sum should not exceed target + nums[i] <= 10^9 + 10^5 < INT_MAX; but typical binary search based solution calculates prefix sum and so should be affected)

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    int minSubArrayLen(int target, vector<int>& nums) {
        unsigned n = nums.size();
        vector<int> sums(n); // HERE: replace int with int64_t
        int sum = 0; // HERE too
        for (unsigned i = 0; i < n; i++) {
            sums[i] = sum += nums[i]; // UBSAN error triggered here
        }
        unsigned j = 0;
        unsigned i = 0;
        unsigned ret = UINT_MAX;
        int sumsj = 0; // HERE too
        for (;; ) {
            i = lower_bound(sums.begin() + i, sums.end(), target + sumsj) - sums.begin();
            if (i >= n)
                break;
            j = upper_bound(sums.begin() + j, sums.begin() + i, sums[i] - target) - sums.begin();
            ret = min(ret, i - j + 1);
            sumsj = sums[j];
        }
        return ret == UINT_MAX ? 0 : ret;
    }
};
```

#### Language used for code
C++

#### Expected behavior

There should be a number of tests that exceeds `INT_MAX` in prefix sums.
Alternatively, change constraints in description so that overflow won't happen (e.g. limit `nums[i]` to not exceed 10^4; then 10^5*10^4 = 10^9 < INT_MAX); then you won't need to rerun tests on all submissions and retract wrongly-ACCEPTED status (then again, it would be annoying to those that read constraints carefully and avoided exceeding them at a cost of memory and time).

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.Since a lot of binary search solutions did not consider the overflow issue, updated constraints a bit.
Also added 2 new test cases. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
