### ISSUE TITLE
Missing Test Case - 1234. Replace the Substring for Balanced String

### ISSUE THREAD

**Issue by lcgamarra** [LeetCode-Feedback/LeetCode-Feedback#7805]
#### Your LeetCode username
lcgamarra

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The solution for the following string should be 3 and not 4. 

"WWEQERQWQWWRWWERQWEQ"

We should replace 3 Ws ("WWW") with "ERR" and all the letters will be present 5 times each.

#### Code you used for Submit/Run operation
class Solution:
    def balancedString(self, s: str) -> int:
        qwers = {}
        freq = int(len(s)/4)
        
        for c in s:
            if c not in qwers:
                qwers[c] = 1
            else:
                qwers[c] += 1
                
        result = 0
            
        for c in qwers:
            if qwers[c] > freq:
                result += qwers[c] - freq
                
        return int(result)
          

#### Expected behavior
The solution should be 3 instead of 4.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by lcgamarra** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission accepted link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

The submission accepted link doesn't exists because the submit fails for the input a wrote above. Attached you'll find the link for the fail submittion:

https://leetcode.com/submissions/detail/724824545/

**Comment by Tushargupta9800** [comment]
read the question again
Return the minimum length of the ```substring``` not ```subsequence```
