### ISSUE TITLE
143. Reorder List

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#781]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 1: Reverse the Second Part of the List and Merge Two Sorted Lists has incorrect description

#### Expected behavior

Line 21
> merge 1->2->3->4 and 6->5->4 into 1->6->2->5->3->4

Length 4 + 3 lists merged into length 6 list. Should be 1->2->3.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thanks for your time. The team has reviewed your report and responded that there is no error with the description, 4 appears two times.
