### ISSUE TITLE
Typo in the description - 1309. Decrypt String from Alphabet to Integer Mapping

### ISSUE THREAD

**Issue by sonjh02** [LeetCode-Feedback/LeetCode-Feedback#7811]
#### Your LeetCode username

sonjh02

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

two of inline code blocks are broken

#### Screenshots

![1655525925840](https://user-images.githubusercontent.com/6972744/174422565-c506b7ad-731a-4799-8afb-145627fffed3.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
