### ISSUE TITLE
缺少测试用例 - 424. 替换后的最长重复字符

### ISSUE THREAD

**Issue by aweliant** [LeetCode-Feedback/LeetCode-Feedback#7814]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Sin2Cal
**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
424. 替换后的最长重复字符，写的代码过了，但实际上是错的。比如面对样例：
"AAAAABBBBCBB"
4
时，预期结果为10，而输出为9
**你使用的语言**
Golang

**你提交或者运行的代码**
```go
// [424. 替换后的最长重复字符](https://leetcode.cn/problems/longest-repeating-character-replacement/)
var freq [26]int
func characterReplacement(s string, k int) (res int) {
    freq=[26]int{}
    var maxC rune='A'
    j:=0
    for i,c:=range s{
        freq[c-'A']++
        if freq[c-'A']>=freq[maxC-'A']{
            maxC=c
        }
        for i-j+1-freq[maxC-'A']>k{
            freq[s[j]-'A']--
            if freq[s[j]-'A']>freq[maxC-'A']{
                maxC=rune(s[j])
            }
            j++
        }
        if i-j+1>res{
            res=i-j+1
        }
    }
    return
}
```

**期望行为**
期望的反馈是解答错误，但实际上通过了。

**屏幕截图**
<img width="866" alt="image" src="https://user-images.githubusercontent.com/53123636/174428447-c04c1160-0e3c-492f-84c8-adeed6402739.png">

**额外的上下文**
无

**Comment by BrambleWave** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。
