### ISSUE TITLE
剑指 Offer 31. 栈的压入、弹出序列 的测试样例150/151可能有问题

### ISSUE THREAD

**Issue by ETWBC** [LeetCode-Feedback/LeetCode-Feedback#7815]
**你的 LeetCode 用户名**
ETWBC

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例
- [x]  测试用例有bug

**描述**
在[剑指 Offer 31. 栈的压入、弹出序列](https://leetcode.cn/problems/zhan-de-ya-ru-dan-chu-xu-lie-lcof/)中
使用我自己的代码提交以及题解中代码提交均无法通过，但测试给出的错误例子均能通过，详见截图，判题是不是出bug了。
同时，二者给出的错误样例例子不一致。

**你使用的语言**
Python

**你提交或者运行的代码**
```
class Solution:
    def validateStackSequences(self, pushed: List[int], popped: List[int]) -> bool:
        temp = []
        i = 0
        for p in pushed:
            temp.append(p)
            while temp and temp[-1] == popped[i]:
                i += 1
                temp.pop()
        if temp:
            return False
        return True
```

**期望行为**
对于样例
[1,2,3,4,5]
[4,3,1,5,2]
和
[1,0]
[1,0]
应该是能通过的，期望给出错误样例或者通过

**屏幕截图**
![图片](https://user-images.githubusercontent.com/26435746/174429112-c60aba14-68e7-4bf8-9c4c-d5785b19576a.png)

**额外的上下文**
添加额外的上下文信息

**Comment by ETWBC** [comment]
另外同样的代码在[946. 验证栈序列](https://leetcode.cn/problems/validate-stack-sequences/)中是没问题的。

**Comment by stormsunshine** [comment]
请检查第二个数组是 [4,3,1,5,2] 还是 [4,5,3,2,1]。

**Comment by ETWBC** [comment]
> 

![图片](https://user-images.githubusercontent.com/26435746/174431369-88404a25-5a2a-4fec-b599-7cc97652dd70.png)
都测过了，测试没有问题，提交错误

**Comment by zlx01** [comment]
同遇到这个问题。测试用例[1,0][1,0]在执行代码时输出和预期结果都是true，在提交测试时输出变成了false。。。

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by zlx01** [comment]
您好！我已收到您的邮件！

**Comment by ETWBC** [comment]
> 问题不是我的代码，是150号样例在两侧查看不一致。。
![图片](https://user-images.githubusercontent.com/26435746/174528429-9c209f41-cb52-455b-944b-aedfdc97b952.png)

**Comment by ETWBC** [comment]
![图片](https://user-images.githubusercontent.com/26435746/174534302-38f70a24-a599-409c-b8be-c215a33da98c.png)
大家都过不去，确实应该是bug

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：etwbc 给予积分奖励，请查收。
