### ISSUE TITLE
Missing Test Case - 745. Prefix and Suffix Search

### ISSUE THREAD

**Issue by Pranav1901** [LeetCode-Feedback/LeetCode-Feedback#7819]
#### Your LeetCode username

PranavRodge

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the hint given to the problem, there is a wrong statement in the last sentence.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

JAVA

#### Expected behavior

The hint should be  - 
For a word like "test", consider "#test", "t#test", "st#test", "est#test", "test#test". Then if we have a query like prefix = "te", suffix = "t", we can find it by searching for something we've inserted starting with "te#t".

The hint is -
For a word like "test", consider "#test", "t#test", "st#test", "est#test", "test#test". Then if we have a query like prefix = "te", suffix = "t", we can find it by searching for something we've inserted starting with "t#te".

#### Screenshots

![image](https://user-images.githubusercontent.com/64834062/174437982-1a333588-e070-407c-9ef4-065ae938e2aa.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
