### ISSUE TITLE
210. Course Schedule II

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#782]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 1: Using Depth First Search has incorrect analysis

#### Expected behavior

> Time Complexity: O(N)

Should be O(V + E) like other approach. Since E can be N^2 at max.

```
        for dest, src in prerequisites:
            adj_list[src].append(dest)
```

In this loop we make iterations equal to the no of edges. There is no limitation on the no of edges of the graph. What if it is  a fully connected graph? The no of edges will be proportional to N^2 rather than N and the time complexity will be wrong.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thanks for your time. The team has reviewed your report and responded that the time complexity is correct and the solution article has explained why in detail.

**Comment by leet212** [comment]
Hello @lc-pam 
Thank you for your response. I wasn't detailed enough in the issue so I have updated it.

**Comment by lc-pam** [comment]
Hi @leet212 ,
Thanks, I've passed the updated content to the team.

**Comment by lc-pam** [comment]
Hi @leet212 ,
Thanks for your time. The team has reviewed the updated content but decided not to update the current solution.
