### ISSUE TITLE
Spelling error - 745. Prefix and Suffix Search

### ISSUE THREAD

**Issue by pvutov** [LeetCode-Feedback/LeetCode-Feedback#7821]
#### Your LeetCode username
pvutov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The first line of the description is:
```Design a special dictionary with some words that searchs the words in it by a prefix and a suffix.```
Instead it should be
```Design a special dictionary with some words that search the words in it by a prefix and a suffix.```
or
```Design a special dictionary that searches the words in it by a prefix and a suffix.```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
