### ISSUE TITLE
41. First Missing Positive - Add possible missing test case 

### ISSUE THREAD

**Issue by hyscript** [LeetCode-Feedback/LeetCode-Feedback#7824]
#### Your LeetCode username
debug-911

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
I believe there is a very important test case which is missing.
Because of that test case the current best submission is very misleading.
The below code is the most efficient one according to Leetcode, however if we add the following test case
[-1,499999,499998,499997,499996,499995, ... , 4,3,2,1] 
the best solution gives the Time Limit message.

#### Code you used for Submit/Run operation
```
// 41. First Missing Positive
class Solution {
    public int firstMissingPositive(int[] nums) {
        int minNum = 1;
        while(true) {
            boolean changed = false;
            for(int i = 0; i < nums.length; i++) {
                if(nums[i] == minNum) {
                    minNum++;
                    changed = true;
                }
            }
            if(changed == false) {
                break;
            }
        }
        return minNum;
    }
};
```

#### Expected behavior
The best possible should pas!

#### Screenshots

Screenshot from [https://leetcode.com/submissions/detail/725340440/](url) submissions detail page
![Screenshot from 2022-06-18 23-11-40](https://user-images.githubusercontent.com/29600021/174453472-17180df1-305b-41ec-9534-2737eff848cf.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by hyscript** [comment]
Sure, I have been using Java.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
