### ISSUE TITLE
【题目描述不恰当】 - 80. 删除有序数组中的重复项 II

### ISSUE THREAD

**Issue by LetMeFly666** [LeetCode-Feedback/LeetCode-Feedback#7827]
<b><a href="https://leetcode.cn/u/tisfy/">tisfy</a></b>

**Bug 类型**

- [ ] 题目

**描述**

题目中说：

> 使每个元素 **最多出现两次** 

“使得每个元素**只出现一次**”同样满足“使每个元素 **最多出现两次** ”

但是根据[测试结果](https://leetcode.cn/submissions/detail/326764766/)可以看出，如果让每个元素都只出现1次是不满足题意的。

我认为，题目真正意思为：

> 使得出现次数多于两次的元素只出现两次

祝好！

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。
