### ISSUE TITLE
219. Contains Duplicate II

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#783]
#### Your LeetCode username
habaj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 2 (Binary Search Tree) [Time Limit Exceeded] has incorrect description

#### Expected behavior

Does not TLE

> Note
> 
> The algorithm still gets Time Limit Exceeded for large n and k.

All approaches will time out for sufficiently large n. But because of IO bottleneck array lengths usually don't go beyond 10^6. Even in that case a time complexity of worst case O(n logn) should pass.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
