### ISSUE TITLE
Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by mx-gp** [LeetCode-Feedback/LeetCode-Feedback#7830]
LeetCode username
`mx_143`

#### Category of the bug
- [  ] Question
- [  ] Solution
- [  ] Language
- [ ✔️ ] Missing Test Cases 

#### Description of the bug
Missing Test Cases, We can add below test cases into `Plus One Problem`
```
[9]
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment]
The test case [9] already exists for this problem. Why do you think this test case is missing?

**Comment by LC-Pam** [comment]
Thank you for your time. Please consider Stromsunshine's response. We appreciate your support!
