### ISSUE TITLE
New approach for solving 338 Counting Bits

### ISSUE THREAD

**Issue by hss15** [LeetCode-Feedback/LeetCode-Feedback#7832]
I would like to contribute to the solution for question 338 
https://leetcode.com/problems/counting-bits/

#### Your LeetCode username
hss15

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
- NA -

#### Code you used for Submit/Run operation
My solution with explanation can be found at https://leetcode.com/problems/counting-bits/discuss/1808154/Very-simple-Java-solution-using-iterative-DP-without-Bitwise-operations-O(n)

It is very similar to the last solution but it doesn't uses the bit-manipulation and hence I think it will be more readable for many users.

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the content team. We appreciate your support!
