### ISSUE TITLE
Missing Test Case - 658. Find K Closest Elements

### ISSUE THREAD

**Issue by ilyannn** [LeetCode-Feedback/LeetCode-Feedback#7833]
#### Your LeetCode username

ilyannn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I've written a solution that starts with a list of values that are equal to `x` and it passed the tests although it shouldn't.

#### Code you used for Submit/Run operation

```
class Solution:
    def findClosestElements(self, arr: List[int], k: int, x: int) -> List[int]:
        def dist(a):
            return abs(a - x), a
        
        i = bisect.bisect_left(arr, x)
        j = bisect.bisect_right(arr, x)
        
        while j - i < k:
            if i and (j == len(arr) or dist(arr[i - 1]) < dist(arr[j])):
                i -= 1
            else:
                j += 1
            
        return arr[i:j]
```

#### Language used for code

Python

#### Expected behavior

I expected this solution to fail since there may be more elements equal to `x` in an array than required in the answer.

#### Screenshots

<img width="369" alt="202206191807" src="https://user-images.githubusercontent.com/4211644/174490065-fdf372ed-4a84-4740-9205-907afdbe5564.png">

<img width="501" alt="202206191807" src="https://user-images.githubusercontent.com/4211644/174490088-9aa2472a-c4cf-4f26-80c2-005addcdec36.png">

#### Additional context

I suggest adding the following test cases:
```
[1, 1]
1
1
[2, 4, 4, 4, 4, 4, 10, 15]
2
4
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
