### ISSUE TITLE
Missing Test Case - 820. Short Encoding of Words

### ISSUE THREAD

**Issue by sceary-expert** [LeetCode-Feedback/LeetCode-Feedback#7837]
#### Category of the bug
- [ ] 820. Short Encoding of Words
- [ ] Solution
- [ ] C++
- [ ] ["time","me","me","bell"]
![image](https://user-images.githubusercontent.com/84634405/174532369-8b2c67fb-b9a3-4583-8c54-8efed41b53ce.png)
![image](https://user-images.githubusercontent.com/84634405/174532390-85d9858d-a0de-4215-9f5e-1c8f2c2d9f34.png)
![image](https://user-images.githubusercontent.com/84634405/174532458-c9f67c09-85b6-43a2-9c1a-9cc8162fc57f.png)

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int minimumLengthEncoding(vector<string>& words) {
        unordered_map<string,int>mp;
            int ans=0;
        for(auto it:words)    
        {
                mp[it]++;
        }
        for(auto it:words)
        {
            int sz=it.size();
                if(mp[it]>1)mp[it]=1;
                    for(int i=0;i<sz;i++)
                    {
                            it.erase(0,1);
                            if(mp[it])mp[it]--;//here instead of decrementing if we write mp[it]=0 it will give same output which is not desirable

                    }
        }
       for(auto it:words)
       {
               if(mp[it])
               {
                       ans+=it.size()+1;
                       mp[it]--;
               }
       }
            return ans;
    }
};
```

**Comment by LC-Pam** [comment]
Would you mind sending us your username?

**Comment by sceary-expert** [comment]
https://leetcode.com/deydhananjoy/

**Comment by sceary-expert** [comment]
@LC-Pam did you add this as a contribution to my id?
