### ISSUE TITLE
给你一个整数数组 nums ，请你找出一个具有最大和的连续子数组（子数组最少包含一个元素），返回其最大和。

### ISSUE THREAD

**Issue by AnnaLuo** [LeetCode-Feedback/LeetCode-Feedback#7840]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目 给你一个整数数组 nums ，请你找出一个具有最大和的连续子数组（子数组最少包含一个元素），返回其最大和。
- [ ] 题解
- [ ] class Solution {
    public int maxSubArray(int[] nums) {
    if(nums == null || nums.length == 0){
         return 0;
    }
    if (nums.length == 1) return nums[0];
    int maxSum=nums[0];
    int persum = nums[0];
    for (int i=1;i<nums.length; i++) {
        if (persum > 0) {
          persum = nums[i] + persum;
        } else {
            persum = nums[i];
        }
        if (persum > maxSum) {
            maxSum = persum;
        }
        

    }
    return maxSum;
    }
}
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
给你一个整数数组 nums ，请你找出一个具有最大和的连续子数组（子数组最少包含一个元素），返回其最大和。

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，请尽可能详细地描述问题，建议把遇到的问题按 issue 模板提交，将信息提供完整才能有助于快速验证和精准的定位。

**Comment by feiceh** [comment]
不处理，建议完善描述， 如果认为题目缺失用例，请附加用例。
