### ISSUE TITLE
Missing Test Case - 820. Short Encoding of Words

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#7841]
#### Your LeetCode username
RohitSgh

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
A.  
**In Approach-1 Algorithm**, it's written   
> Since a word only has up to 7 suffixes (as `words[i].length <= 7`), let's iterate over all of them. For each suffix, we'll try to remove it from our `words` list.   

It can be better phrased as    
> Since a word can have up to 6 proper suffixes only (as `words[i].length ≤ 7`), let's iterate over all of them. For each word, we'll try to remove it's proper suffix from `words` list.   

---

B.  
**In Approach-2 Algorithm**, it's written    
> After, the leaves of this trie (nodes with no children) represent words that have no suffix    

it should be    
> After, the leaves (nodes with no children) of this trie represent words that are not proper suffix of others

---

C.   
Moreover, in entire solution, at many places instead of `Suffix`, it should be `Proper Suffix`. Reason being that in literature, "every word is suffix of itself". More specifically, proper suffix includes all suffixes except the word. Proper Suffix also doesn't include empty string.

#### Expected behavior

Discussed in Description

#### Additional context

This [Wikipedia](https://en.wikipedia.org/wiki/Substring#Suffix) article

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
