### ISSUE TITLE
Missing Test Case - 820. Short Encoding of Words

### ISSUE THREAD

**Issue by DhileepKumarN** [LeetCode-Feedback/LeetCode-Feedback#7843]
#### Your LeetCode username

dhileepkumarn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gives wrong answer on the following testcase:
[testcaseFor820_ ShortEncodingofWords.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8943754/testcaseFor820_.ShortEncodingofWords.txt)

#### Code you used for Submit/Run operation

```
//Short Encoding of Words
class Solution {
public:
    int minimumLengthEncoding(vector<string>& words) {
        map<string,int> mp;
        int ans=0;
        for(int i=0;i<words.size();++i){
            string str=words[i];
            int n=str.length();
            for(int j=0;j<n;++j){
                mp[str.substr(n-j,j)]++;
            }
            mp[str]--;
        }
        for(auto it=mp.begin();it!=mp.end();++it){
            if((*it).second<0) ans+=(*it).first.length()+1;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My code given above is wrong, but the code is accepted in leetcode.
My code is giving wrong answer for the testcase given below:
[testcaseFor820_ ShortEncodingofWords.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8943816/testcaseFor820_.ShortEncodingofWords.txt)

so, you have to add this testcase to this leetcode question.

#### Screenshots

![leetcode_820_acceptedSolution](https://user-images.githubusercontent.com/63438301/174681930-751efe6d-e551-4c44-a54f-1f8451e47443.PNG)
![leetcode_820_testcase](https://user-images.githubusercontent.com/63438301/174681956-768b3912-cb30-42e8-b6b2-a87ff831315b.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
This solution now gets WA from a previously added test case. so we did not add that test case.
 We appreciate your support!
