### ISSUE TITLE
Missing Test Case - 704. Binary Search

### ISSUE THREAD

**Issue by NishaBoby23** [LeetCode-Feedback/LeetCode-Feedback#7847]
#### Category of the bug
- [ ] Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.

You must write an algorithm with O(log n) runtime complexity.

- [ ] class Solution(object):
    def search(self, nums, target):
        
        """
        space: O(1)
        time: O(logn)
        """
        left = 0
        right = len(nums) - 1
        while left <= right:
            mid = int((right + left) / 2)
            if nums[mid] == target:
                return mid
            elif nums[mid] < target:
                left = mid + 1
            else:
                right = mid - 1
        return -1
		
- [ ] Python
- [ ] [-1,0,3,5,9,12]
        9
        [-1,0,3,5,9,12]
        2

#### Code you used for Submit/Run operation
<!-- 
class Solution(object):
    def search(self, nums, target):
        
        """
        space: O(1)
        time: O(logn)
        """
        left = 0
        right = len(nums) - 1
        while left <= right:
            mid = int((right + left) / 2)
            if nums[mid] == target:
                return mid
            elif nums[mid] < target:
                left = mid + 1
            else:
                right = mid - 1
        return -1
        ```
-->

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
