### ISSUE TITLE
In the 256. Paint House problem

### ISSUE THREAD

**Issue by User123Vladimir** [LeetCode-Feedback/LeetCode-Feedback#7848]
In the 256. Paint House problem, the program given in the section solutions for input costs=[[16,2,17],[14,8,15],[5,4,15],[16,1,2],[8,20,1]] gives the wrong answer 24. According to my calculation, the correct answer is 30.
Why is it so?
User123Vladimir

**Comment by stormsunshine** [comment]
The minimum cost is 2 + 15 + 5 + 1 + 1 = 24. Is there any problem?

**Comment by User123Vladimir** [comment]
Thank you. I realized my mistake. Sincerely, to you Vladimir
