### ISSUE TITLE
Easy problem is hard - 575. Distribute Candies

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#785]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
575. Distribute Candies
https://leetcode.com/problems/distribute-candies/

This problem is not Easy, but a Medium, because we need to check for number of cases.
Please make this problem a Medium.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

This problem is not Easy, but a Medium, because we need to check for number of cases.
Please make this problem a Medium.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. The team has reviewed your report and considered that the current version is hard because it is not well explained. We have updated the description and it seems ok now so we won't change the difficulty. We appreciate your support!
