### ISSUE TITLE
Solution Typo - Problem 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by djdd01** [LeetCode-Feedback/LeetCode-Feedback#7851]
#### Your LeetCode username
dhruv01dubey

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a mistake in the key observation of approach 6.
nums_count is shown as [3,2] for [1,3,3] array whereas it should be [2,3] as there will be 3 ones bits on and the reconstructed number would be 1 and not 2.

#### Code you used for Submit/Run operation

NOT RELEVANT 

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

#### Screenshots

![image](https://user-images.githubusercontent.com/63750812/174794376-21d0b555-c5d4-471c-9048-50b8e0f95885.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team, but it will take more time to evaluate and fix. We appreciate your support!
