### ISSUE TITLE
Missing Test Case - 1642. Furthest Building You Can Reach

### ISSUE THREAD

**Issue by himanshu763** [LeetCode-Feedback/LeetCode-Feedback#7854]
#### Your LeetCode username

himamshu763

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

According to question we have to return the farthest index we can reach using ladders and bricks, in case where the length of array of heights is '1' the correct answer should '0' as there's no other index we can move to but both '0' and '1' are considered as valid answers.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int furthestBuilding(vector<int>& heights, int bricks, int ladders) {
        int n = heights.size(), ans1 = 0, ans2 = 0;
        if(n == 1) return 1;
        priority_queue<int, vector<int>, greater<int>> ladderAllocatons;
        
        for(int i = 0; i < n - 1; i++){
            int climb = heights[i + 1] - heights[i];
            if(climb <= 0) continue;
            ladderAllocatons.push(climb);
            
            if(ladderAllocatons.size() <= ladders) continue;
            
            bricks -= ladderAllocatons.top();
            ladderAllocatons.pop();
            
            if(bricks < 0) return i;
        }
        return n - 1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For input array of size one the only correct answer should be '0' where '0' as well as' 1' both are considered correct.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
