### ISSUE TITLE
Test Case Error -- Ugly Number 2 

### ISSUE THREAD

**Issue by rahulsg98** [LeetCode-Feedback/LeetCode-Feedback#7857]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
As it was given in the Question that we have given a number and we have to return the nth multiple of 2 or 3 or 5. Then if n = 10, the answer would be 10, and that's ok. But when in the test case n = 11, how can the answer be 15. It has to be 14, as it is the next number after 12 that is divisible by 2 or 3 or 5. So it is the wrong test case.

#### Code you used for Submit/Run operation

```
// Ugly Number 2
class Solution {
public:
    int nthUglyNumber(int n) 
    {
       int c=1;
        priority_queue<int> pq;
        pq.push(1);
        int x = 1;
        if(n==1)
            return 1;
        while(c<n)
        {
          if(x%2==0 || x%3==0 || x%5==0)
          {
              pq.push(x);
              c++;
          }
            x++;
        }
        return pq.top();
    }
};
```

#### Language used for code
 C++ 

#### Screenshots
If applicable, add screenshots to explain your issue.
![Screenshot from 2022-06-21 23-30-35](https://user-images.githubusercontent.com/78016968/174867668-38c76dd7-d0c2-44e3-a862-d5c0300868fb.png)
![Screenshot from 2022-06-21 23-30-03](https://user-images.githubusercontent.com/78016968/174867704-695adf49-3d7a-420c-a442-8abf51e3f147.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stormsunshine** [comment]
Please read the problem description carefully.
> An ugly number is a positive integer whose prime factors are **limited to** 2, 3, and 5.

14 has a prime factor 7, which is not limited to 2, 3, and 5. How can a number divisible by 7 be an ugly number?

**Comment by stormsunshine** [comment]
Please read the problem description carefully.
> An ugly number is a positive integer whose prime factors are **limited to** 2, 3, and 5.

14 has a prime factor 7, which is not limited to 2, 3, and 5. How can a number divisible by 7 be an ugly number?

**Comment by 0901IT201046** [comment]
> Please read the problem description carefully.
> 
> > An ugly number is a positive integer whose prime factors are **limited to** 2, 3, and 5.
> 
> 14 has a prime factor 7, which is not limited to 2, 3, and 5. How can a number divisible by 7 be an ugly number?

OK, Got it. Thank you.
