### ISSUE TITLE
题目：645 错误的集合

### ISSUE THREAD

**Issue by zhou529** [LeetCode-Feedback/LeetCode-Feedback#786]
** Bug 类型**
- [ ] 645、错误的集合
- [ ] 全部
- [ ] java

**描述**
输入
[2,4,4]
输出
[4,3]
预期结果
[4,1]
只要输入[2,4,4]就会出错，7种方法要么输出错误，要么显示下标越界异常
**你使用的语言**
java

**你提交或者运行的代码**
```
//代码只提供了第3种，其余6种输出的结果和预期结果不同
public class Solution {
    public int[] findErrorNums(int[] nums) {
        Arrays.sort(nums);
        int dup = -1, missing = 1;
        for (int i = 1; i < nums.length; i++) {
            if (nums[i] == nums[i - 1])
                dup = nums[i];
            else if (nums[i] > nums[i - 1] + 1)
                missing = nums[i - 1] + 1;
        }
        return new int[] {dup, nums[nums.length - 1] != nums.length ? nums.length : missing};
    }
}


```

**期望行为**
[4,1]

**屏幕截图**
![image](https://user-images.githubusercontent.com/69469598/89793221-2e61fc80-db58-11ea-81f5-6254d4c777e2.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，请仔细阅读理解题目意思（1～n）。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路。
