### ISSUE TITLE
162 -- Find Peak Element description

### ISSUE THREAD

**Issue by mscuthbert** [LeetCode-Feedback/LeetCode-Feedback#7862]
#### Your LeetCode username

msacuthbert

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a potential for misreading and confusion in this line in the description for users of Python (and perhaps other languages):

"You may imagine that `nums[-1]` = `nums[n]` = `-∞`."

In Python, of course, `nums[-1]` means `nums[nums.length - 1]` in other languages.  A clarification like "(where nums[-1] refers to the element preceding the first zero-indexed element)" would help.

(As an aside, this is also one of the few high-traffic problems where the answer is to return an index which never explicitly states that the answer should be zero-indexed.)

#### Code you used for Submit/Run operation

N/A

#### Language used for code

Python (2 or 3)

#### Expected behavior

There's no way to make the descriptions run in every language (hence `nums.length` and not `len(nums)`, etc.) but it would be great if `nums[-1]` was avoided without a description.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Fixed the issue to be more clear for python users.  We appreciate your support!
