### ISSUE TITLE
26. 删除有序数组中的重复项 题目描述不对

### ISSUE THREAD

**Issue by shaocongmo** [LeetCode-Feedback/LeetCode-Feedback#7864]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
TheMSC

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目描述数组范围 0 <= nums.length <= 3 * 104，输入空数组测试返回错误 expected 'nums' to have 1 <= size <= 30000 but got 0

**你使用的语言**
C

**你提交或者运行的代码**
```
int removeDuplicates(int* nums, int numsSize){
    return 0;
}
```

**期望行为**
空数组结果返回空数组

**屏幕截图**
![image](https://user-images.githubusercontent.com/29625907/174960250-0ae4022d-54eb-483a-9ecb-80620bf98bea.png)
![image](https://user-images.githubusercontent.com/29625907/174960272-2bbad876-b17c-4eb5-95e6-866cb57a6b27.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。
