### ISSUE TITLE
Bug in shortest palindrome problem

### ISSUE THREAD

**Issue by sahilm26** [LeetCode-Feedback/LeetCode-Feedback#7865]
I have submitted my code and it is showing as wrong answer .

input ="aabba"
output ="abbabba"
expected = "abbaabba

attaching screenshot for reference

![Capture](https://user-images.githubusercontent.com/107982110/174960471-f53bef8b-d7d4-4545-8c8a-39ac8838bdf8.PNG)
"

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
