### ISSUE TITLE
313. Super Ugly Number shows negative expected outputs for some testcases

### ISSUE THREAD

**Issue by wuxxx725** [LeetCode-Feedback/LeetCode-Feedback#7869]
#### Your LeetCode username

meng-hsuan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

For some testcases with answers approaching (but still within) the upper limit of 32-bit signed integer, such as the ones given below, the judge solution seems to have overflowed and therefore shows negative values as the expected outputs.
```
5911
[2,3,5,7]
1719
[2,7,13,19]
```

#### Code you used for Submit/Run operation

```
class Solution:
    def nthSuperUglyNumber(self, n: int, primes: List[int]) -> int:
        np = len(primes)
        INT_MAX = 2147483647
        limits = [INT_MAX // i for i in primes]
        
        h = [(1, 0)]
        heapify(h)
        
        for i in range(n):
            num = heappop(h)
            for j in range(num[1], np):
                if num[0] <= limits[j]:
                    heappush(h, (num[0] * primes[j], j))
        
        return num[0]
```

#### Language used for code

Python3

#### Expected behavior

The numbers 2,144,153,025 = 3^6 * 5^2 * 7^6 is the 5,911th super ugly number with respect to the primes [2, 3, 5, 7], following its predecessor 2,143,750,000 = 2^4 * 5^8 * 7^3 (for which the output of my program agrees with the judge output).  Similarly, 2,135,179,264 = 2^14 * 19^4 are indeed the 1,719th super ugly number with respect to the primes [2, 7, 13, 19], following its predecessor 2,125,480,448 = 2^9 * 7^5 * 13 * 19.  Both numbers are within the upper limit 2,147,483,647 for 32-bit signed integer.

#### Screenshots

<img width="883" alt="LeetCode 313" src="https://user-images.githubusercontent.com/67871581/175058102-20ed31dc-a89d-4b5f-b13e-45ddad506f54.png">

#### Additional context

The first 10,000 positive numbers with all prime divisors less than or equal to 7 can be found on the On-Line Encyclopedia of Integer Sequences (OEIS) at https://oeis.org/A002473/b002473.txt. The 5,911th term on the list is indeed 2,144,153,025.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
