### ISSUE TITLE
支持隐藏[涂画画板]

### ISSUE THREAD

**Issue by cocofe** [LeetCode-Feedback/LeetCode-Feedback#787]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

希望支持隐藏下面画框处的画板, 同时支持关闭画板快捷键!!!!

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/27345052/89803430-63c11700-db65-11ea-8774-aeec6b1ef4af.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢提议，此需求已转达相关部门，后续会不断优化增加产品功能的。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先暂时关闭，后续使用中有任何问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。
