### ISSUE TITLE
[392. 判断子序列] 缺少测试用例

### ISSUE THREAD

**Issue by jobyrao** [LeetCode-Feedback/LeetCode-Feedback#7871]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
建兵

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
[392. 判断子序列](https://leetcode.cn/problems/is-subsequence/) 缺少测试用例导致错误的解法被判定为正确。

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```js
var isSubsequence = function(s, t) {
    // if (s.length === 0) return true;
    // // 遍历大串，挨个检验小串
    // for (let i = 0, j = 0, len = t.length; i < len; i++) {
    //     if (t[i] === s[j]) {
    //         j++;
    //         if (j === s.length) return true;
    //     }
    // }
    // return false;
    
    // 优化思路，从头尾两边开始数，遍历减一半
    let sl = 0;
    let sr = s.length - 1;
    for (let tl = 0, tr = t.length - 1; tl <= tr; tl++, tr--) {
        if (sl > sr) return true;
        if (t[tl] === s[sl]) {
            sl++;
        }
        if (t[tr] === s[sr]) {
            sr--;
        }
    }
    return sl > sr;
};
```

**期望行为**
输入：s = "abbc", t = "ahbdc"
输出：false

**当前行为**
输入：s = "abbc", t = "ahbdc"
输出：true

**Bug 原因**
当首尾遍历 t 字符串到 b （l, r 指针都指到 b）字符时，s 字符串刚好 l 指到 b，r 指到 b，一个 t 字符串中的 b 字符被用了 2 次用去判定 s 字符串中的 2 个 b 字符。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by BrambleWave** [comment]
你好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的 ID，我们给予积分奖励哦。
