### ISSUE TITLE
Wrong time complexity / solution

### ISSUE THREAD

**Issue by Zackhardtoname** [LeetCode-Feedback/LeetCode-Feedback#7873]
#### Your LeetCode username
sampleaccountpage

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The current solution is 
```Python
class Solution(object):
    def minSteps(self, n):
        ans = 0
        d = 2
        while n > 1:
            while n % d == 0:
                ans += d
                n /= d
            d += 1
        return ans
```
However, in the worst case when n in the input is a prime number, say 31, the `while n > 1` loop has to run 31 or n times. Yet the current solution says the time complexity is  O(\sqrt{N}). The current solution to achieve that complexity instead of O(n) is as follows

#### Expected behavior

```Python
class Solution:
    def minSteps(self, n: int) -> int:
        max_factor = int(n ** .5)
        num_ops = 0
        factor = 2

        while n > 1 and factor <= max_factor:
            while n % factor == 0:
                num_ops += factor
                n //= factor
            factor += 1

        # the remaining factor is prime
        if n > 1:
            num_ops += n

        return num_ops
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The Problem Name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Zackhardtoname** [comment]
Oh it's this problem: https://leetcode.com/problems/2-keys-keyboard/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Both solutions are ok to pass. We appreciate your support!
