### ISSUE TITLE
Drawing/Figure issues - 630. Course Schedule III

### ISSUE THREAD

**Issue by ImAkhil24** [LeetCode-Feedback/LeetCode-Feedback#7874]
#### Your LeetCode username
akhilbadoni24

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the solution approach 2 it's given that a > b but int the figure drawn below is showing a < b and similar thing have happened in the next figure.

#### Screenshots
![image](https://user-images.githubusercontent.com/56029762/175223963-535ae5f9-df5b-4331-8c96-85a365a655b5.png)
![image](https://user-images.githubusercontent.com/56029762/175224193-af59cb1c-fa04-4aa5-a123-41c3a612409c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
