### ISSUE TITLE
703. Kth Largest Element in a Stream Priority Queue Glitch

### ISSUE THREAD

**Issue by angad-14** [LeetCode-Feedback/LeetCode-Feedback#7876]
#### Your LeetCode username
angad_kochhar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug 
When my priority queue size is 0, it is showing the element which i popped in the previous step as it's top. Instead of runtime error as i am accessing top() of an empty priority queue, it is showing the element which should have been popped.

#### Code you used for Submit/Run operation
```
class KthLargest {
public:
    int cap;
    priority_queue<int,vector<int>,greater<int>>pq;
    
    KthLargest(int k, vector<int>& nums) {
        cap=k;
        for(int i=0;i<nums.size();i++){
            pq.push(nums[i]);
            if(pq.size()>k){
                pq.pop();
            }
        }
    }
    
    int add(int val) {
        pq.push(val);
        if(pq.size()>=cap)
        {
            pq.pop();
        }
        cout<<pq.size()<<" "<<pq.top();
        return pq.top();
    }
};
```

#### Language used for code
C++

#### Screenshots
![Screenshot 2022-06-23 at 12 30 00 PM](https://user-images.githubusercontent.com/107995345/175237177-29b60883-a5d0-4484-8671-b768e29139de.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
