### ISSUE TITLE
剑指 Offer 31. 栈的压入、弹出序列

### ISSUE THREAD

**Issue by night-cruise** [LeetCode-Feedback/LeetCode-Feedback#7879]
**你的 LeetCode 用户名**
night-cruising

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例
- [x] leetcode后台测试系统出错

**描述**
提交后显示没有通过的测试用例与提交记录中未通过的测试用例不一致，并且与使用控制台进行测试的结果不一致。

**你使用的语言**
Rust

**你提交或者运行的代码**
```rust
impl Solution {
    pub fn validate_stack_sequences(pushed: Vec<i32>, popped: Vec<i32>) -> bool {
        if pushed.len() <= 1 {
            return true;
        }
        let mut stack = vec![];
        let mut j = 0;
        
        for item in pushed {
            stack.push(item);
            while !stack.is_empty() && stack[stack.len()-1] == popped[j] {
                stack.pop();
                j += 1;
            }
        }

        j == popped.len()
    }
}
```

**期望行为**
输入：
[1,0]
[1,0]
输出：true

输入：
[1,2,3,4,5]
[4,3,1,5,2]
输出：false

**屏幕截图**
提交后系统显示没有通过的测试用例：
![1](https://user-images.githubusercontent.com/77157236/175262337-373a4ed0-2c83-458d-9535-621968d0d648.png)

提交记录中显示没有通过的测试用例：
![2](https://user-images.githubusercontent.com/77157236/175262729-5ad17144-0036-4d81-b96a-dcefab9fcf8d.png)

但是在控制中上述的两个测试用例均正常通过：
![3](https://user-images.githubusercontent.com/77157236/175262863-3690f66f-12d1-4db7-a7d0-ff56aa0daf2d.png)
![4](https://user-images.githubusercontent.com/77157236/175262876-0e1ce55f-fda8-48d9-9533-edc459da59f6.png)

**额外的上下文**
无

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by night-cruise** [comment]
这个问题已经被解决了，在今天的测试中同样的代码提交通过了，所以我会关闭这个issue。
