### ISSUE TITLE
176. Second Highest Salary

### ISSUE THREAD

**Issue by muradhajii** [LeetCode-Feedback/LeetCode-Feedback#7880]
#### Your LeetCode username
tVahee

#### Category of the bug
- [1 ] Solution

#### Description of the bug
 In my oraclesql program when i write this code it's working normal 

#### Code you used for Submit/Run operation

```
select distinct salary as "SecondHighestSalary" 
from employee order by salary desc 
offset 1 row 
fetch first 1 row only;
```

#### Language used for code
 Oracle 

#### Expected behavior
I expected that when i write my code this will return me correct answer.

![leetcodeerror](https://user-images.githubusercontent.com/108065203/175282012-bb471d69-911f-46a4-9f73-ef3d1e896bc1.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the develop team, it gonna takes some time to fix the issue. We appreciate your support!
