### ISSUE TITLE
Solution 5 is incorrect - 630. Course Schedule III

### ISSUE THREAD

**Issue by inderpreetkaur0** [LeetCode-Feedback/LeetCode-Feedback#7881]
#### Category of the bug
- [ ] Solution

#### Description of the bug

%th solution is missing check
```if (valid_list.size() > max_i && valid_list.get(max_i) > c[0]) {```

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. . We appreciate your support!
