### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by jeffbr96** [LeetCode-Feedback/LeetCode-Feedback#7882]
#### Your LeetCode username

jbourguignon

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

on (Top Interview Questions) (Easy) (Sorting and Searching) (Merge Sorted Array)

nums1[0] = 1 but the test shows 0 ?

#### Code you used for Submit/Run operation

```
class Solution {
      public static void merge(int[] nums1, int m, int[] nums2, int n) {
        if (m == 0 && n == 0) {
            return;
        }else if(n == 0){
            return;
        }else if(m == 0){
            nums1 = nums2;
            System.out.println("nums1[0] = " + nums1[0]);
            return;
        }

        int t = 0;

        if (nums1[0] == 0 && nums1[nums1.length - 1] == 0) {
            nums1 = nums2;
        } else {
            for (int i = 0, j = 0; i < nums1.length; i++) {
                if (nums1[i] == 0) {
                    break;
                }
                if (nums1[i] <= nums2[j]) {
                    t = nums1[i];
                } else {
                    t = nums2[j];
                    nums2[j] = nums1[i];
                    nums1[i] = t;
                    if (j < nums2.length) {
                        j++;
                    }
                }
            }
            for (int l = n, k = 0; l < nums1.length; l++, k++) {
                nums1[l] = nums2[k];
            }
        }
        return;
    }
}
```

#### Language used for code

java

#### Expected behavior

nums1[0] == 1;
return; //exit the code

#### Additional context

It's probably something I'm missing but please let me know; I'm running on vscode with junit tests and all examples up to and including this one pass. thank you in advance, have a nice day!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
