### ISSUE TITLE
Missing Test Case - 1648. Sell Diminishing-Valued Colored Balls

### ISSUE THREAD

**Issue by prashuchaudhry** [LeetCode-Feedback/LeetCode-Feedback#7884]
#### Your LeetCode username
xleox 

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Please include [1000000000,1000000000,1000000000] , 1000000000 this test case as well. 
I submitted my code and it was accepted as it passed all the test cases but when I explicitly tried this test test case then it was showing a different answer.
Output
63
Expected
37

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxProfit(int[] inventory, int orders) {
        int mod = 1000000007;
        PriorityQueue<Integer> pq = new PriorityQueue<>((a, b) -> b - a);
        for (int num : inventory) {
            pq.offer(num);
        }
        
        int cur = pq.poll();
        int count = 1; 
        long res = 0;
        while (orders > 0) {
            int next = pq.isEmpty() ? 0 : pq.peek();
            if ((cur - next) * count <= orders) {
                long num =  (1L * (next + 1 + cur) * (cur - next) * count / 2) % mod;
                res = (res + num) % mod;
                orders -= (cur - next) * count;
                
            } else {
                next = cur - orders / count;
                long num =  (1L * (next + 1 + cur) * (cur - next) * count / 2) % mod;
                res = (res + num) % mod;
                res = (res + 1L * next * (orders % count)) % mod;
                orders = 0;
            }
            
            if (!pq.isEmpty()) cur = pq.poll();
            count++;
        }
        return (int) res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I thought my code won't be accepted as it was giving a wrong output for the test case I mentioned above, but it was accepted. 

#### Screenshots

![image](https://user-images.githubusercontent.com/92192670/175359008-3742b8bc-3635-43e1-b5da-05ea719118bf.png)

![image](https://user-images.githubusercontent.com/92192670/175359076-e2891082-5273-460d-a982-6201e00a487c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
