### ISSUE TITLE
Constraints are very tight. LC 1770

### ISSUE THREAD

**Issue by hardik302001** [LeetCode-Feedback/LeetCode-Feedback#7887]
#### Your LeetCode username
targetGuardian

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

LC [1770 ](https://leetcode.com/problems/maximum-score-from-performing-multiplication-operations/) is a DP based problem. The issue here is that top - down approach gives TLE bcz the constraints are very tight. 

#### Code you used for Submit/Run operation

TLE 62/63
```
class Solution {
public:
    int dp[1001][1001];   // l and op both can go upto power 3
    int solve(int l , vector<int>&nums , vector<int>&mul ,int n , int m, int op ){
        int r = n-1 - (op -l);
        if(l>r or op==m) return 0;
        if(l==r) return mul[op]*nums[l];
        
        if(dp[l][op]!=-1) return dp[l][op];
        
        int ans = INT_MIN;
        
        ans = max(ans , nums[l]*mul[op] + solve(l+1 , nums , mul , n , m , op+1));
        ans = max(ans , nums[r]*mul[op] + solve(l , nums, mul , n , m , op+1));

        return dp[l][op] = ans;
    }
    
    
    int maximumScore(vector<int>& nums, vector<int>& mul) {
        int m = mul.size();
        int n = nums.size();
        int l = 0;
        int r = n-1;
        memset(dp , -1 , sizeof dp);
        return solve(l  , nums , mul , n ,m ,0);
        
    }
};

```

#### Language used for code

C++

#### Expected behavior

The constraints should be reduced a little. Because , its weird that bottom up approach is passing , but top down gives TLE.

#### Additional context

I tried all top down approach from discuss, but all of them are giving TLE.

**Comment by hqztrue** [comment]
This is because the code is incorrect. Seems that testcase 63 is designed to hack this code. The reason is when dp[l][op]=-1, this does not necessarily mean that dp[l][op] is not computed yet. In fact, its true value may be equal to -1.

The following code can pass with two lines of change:
```
class Solution {
public:
    int dp[1001][1001];   // l and op both can go upto power 3
    int solve(int l , vector<int>&nums , vector<int>&mul ,int n , int m, int op ){
        int r = n-1 - (op -l);
        if(l>r or op==m) return 0;
        if(l==r) return mul[op]*nums[l];
        
        if(dp[l][op]!=0x1f1f1f1f) return dp[l][op];  /////////////////////////////////// and here
        
        int ans = INT_MIN;
        
        ans = max(ans , nums[l]*mul[op] + solve(l+1 , nums , mul , n , m , op+1));
        ans = max(ans , nums[r]*mul[op] + solve(l , nums, mul , n , m , op+1));

        return dp[l][op] = ans;
    }
    
    
    int maximumScore(vector<int>& nums, vector<int>& mul) {
        int m = mul.size();
        int n = nums.size();
        int l = 0;
        int r = n-1;
        memset(dp , 0x1f , sizeof dp);  /////////////////////////////////// I changed here
        return solve(l  , nums , mul , n ,m ,0);
        
    }
};
```

**Comment by hardik302001** [comment]
Thanks man , got your point . I was wrong.
Btw , I also tried map with string , that also gave Tle.
Secondly , why you used 0x7f7f7f7f only?

**Comment by hqztrue** [comment]
unordered_map has a larger constant than directly using arrays, which could result in TLE (and map is even slower, O(log n) time per query).
memset(0x7f) means setting each byte to be 0x7f. An int has 4 bytes, so that memset sets an int variable to 0x7f7f7f7f.
