### ISSUE TITLE
Missing Test Case - 451. Sort Characters By Frequency

### ISSUE THREAD

**Issue by gsinghly** [LeetCode-Feedback/LeetCode-Feedback#7888]
#### Your LeetCode username
saintp0p0

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [] Missing Test Cases 

#### Description of the bug
Question says return any answer(if multiple answers exists), but for testcase
Input: "loveleetcode"
Output: "eeeelolovtcd" is not accepted

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string frequencySort(string s) {
        map <char, int> freq;
        auto comp = [&](char &a, char &b){
            return freq[a] > freq[b];
        };
        for(auto &i: s){
            freq[i]++;
        }
        sort(s.begin(), s.end(), comp);
        return s;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Incase of multiple possible answers, any correct answer should be accepted.
The below was accepted in which I outputted based on frequency but if frequency is equal, the character with greater ASCII value is preferred, which should not be the case as per the description of the problem - **Return the sorted string. If there are multiple answers, return any of them.**
<img width="1440" alt="Screenshot 2022-06-24 at 12 05 53 PM" src="https://user-images.githubusercontent.com/35264030/175477112-83328a5a-864e-4bc3-b490-40a41571ab0f.png">

#### Screenshots

<img width="1440" alt="Screenshot 2022-06-24 at 12 00 29 PM" src="https://user-images.githubusercontent.com/35264030/175476304-49ed8d5f-53e7-4104-9417-c116cc21a36f.png">

**Comment by stormsunshine** [comment]
Please refer to example 2. The same characters must be together.
