### ISSUE TITLE
提交记录消失

### ISSUE THREAD

**Issue by da-pang-za** [LeetCode-Feedback/LeetCode-Feedback#7889]
**用户名dpangzi**

**描述**
以前做过的题在提交记录那里看不到了

**屏幕截图**
比如第一题
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/54436289/175567215-de963ab7-2d7b-4b09-917f-640da3043e36.png">

**Comment by stormsunshine** [comment]
是否切换了不同的进度？

**Comment by da-pang-za** [comment]
> 是否切换了不同的进度？

进度都合并了，只有一个进度

**Comment by da-pang-za** [comment]
请问是什么情况？

**Comment by feiceh** [comment]
Hello～感谢反馈，可能是由于您登录的账号非日常刷题使用账号，请确保登录账号一致，然后看一下 [进度管理](https://leetcode.cn/session/) 是否可以找到之前的记录呢？如仍有问题，请 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，谢谢。
