### ISSUE TITLE
Missing Test Case: 1494. Parallel Courses II

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#789]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A greedy solution that processes courses backwards in the following order: level, total number of "parent" nodes is accepted though it fails on a test case:

12
[[1,8], [1,9], [1,10], [1,11], [2,8], [2,9], [2,10], [2,11], [3,8], [3,9], [3,10], [3,11], [4,8], [4,9], [4,10], [4,11], [5,12], [6,12], [7,12]]
3

Output: 5
Expected: 4

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```
Please see: https://leetcode.com/problems/parallel-courses-ii/discuss/780260/Python-topological_sort-bottom-up-solved-all-test-cases-could-be-wrong

<pre>
from collections import defaultdict, deque
class Solution:
    def minNumberOfSemesters(self, n: int, dependencies: List[List[int]], k: int) -> int:
        outs, g = self.build_graph(dependencies, n)
        start = [v for v, f in outs.items() if f == 0]
        u_lvl = {}
        for u in start:
            self.dfs_level(u, u_lvl, g)
        ans = 0
        q = start
        while q:
            q.sort(key=lambda x:u_lvl[x])
            # print(q)
            size = len(q)
            for _ in range(min(k,size)):
                u = q.pop()
                for v in g[u]:
                    outs[v] -= 1
                    if outs[v] == 0:
                        q.insert(0, v)
            ans += 1
        return ans
    
    def dfs_level(self, u, u_lvl, g):
        ns = set([u])
        lvl = 0
        for v in g[u]:
            l, nodes = self.dfs_level(v, u_lvl, g)
            lvl = max(lvl, l+1)
            for nd in nodes:
                ns.add(nd)
        u_lvl[u] = (lvl, len(ns))
        return lvl, ns
    
    def build_graph(self, D, n):
        g = defaultdict(list)
        outs = defaultdict(int)
        for i in range(1, n + 1):
            outs[i] = 0
        for u, v in D:
            g[v].append(u)
            outs[u] += 1
        
        return outs, g
</pre>

#### Language used for code

Python 3

#### Expected behavior

The solution should not be accepted since there are situations when it produces incorrect results

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/89836354-90106f80-db34-11ea-8364-318939cb8d37.png)
![image](https://user-images.githubusercontent.com/32546406/89836389-a8808a00-db34-11ea-8afd-3578dbb9f3cc.png)

#### Additional context

This test case handles the following greedy approach: courses are processed in the following order: they are sorted by "level" descending and then by "total number of parent nodes" descending

**Comment by lc-ivan** [comment]
Hi @IgorRud  ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @IgorRud ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
