### ISSUE TITLE
Wrong Diagrams - 81. Search in Rotated Sorted Array II

### ISSUE THREAD

**Issue by Vinayaka2k** [LeetCode-Feedback/LeetCode-Feedback#7890]
#### Your LeetCode username
vinuvinayaka2000

#### Category of the bug
- [ ] Question
- [Y] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Few diagrams in the Algorithm section are wrong.
Example: In Case 2, The diagram shows arr[mid] to be 5 whereas it's actually 19.
In Case 3 - first pic, mid is shown as 15, whereas it's 19.
In Case 4, second pic, mid is shown as 5, whereas it must be 19.

Since mid is calculated in the code as :             
int mid = start + (end - start) / 2;

Which essentially is mid = (start+end)/2, when there are even number of elements in the array, and the middle two elements have
a potential of becoming mid, we always choose the first element going by the above formula. But the diagrams indicate otherwise.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Hi there, this issue still in the progress status, we need our content team to review.

**Comment by LC-Pam** [comment]
Thank you for your time. The diagrams are illustrating for understanding. Author is no longer on team and files are lost, so we will keep this issue .We appreciate your support!
