### ISSUE TITLE
142. Linked List Cycle II (in PHP)

### ISSUE THREAD

**Issue by zuber** [LeetCode-Feedback/LeetCode-Feedback#7892]
#### Your LeetCode username

[maxzuber](https://leetcode.com/maxzuber/)

#### Category of the bug
- [ ] Language

#### Description of the bug

In PHP linked lists with repeated values causes a runtime error:

> Runtime Error Message:
> Line 84: PHP Fatal error:  Nesting level too deep - recursive dependency? in solution.php
> Last executed input:
> [-1,-7,7,-4,19,6,-9,-5,-2,-5]
> 9

The example mentioned above taken from a real test case, but my algorithm fail same way on any list containing repeated values.  Changing the last non-unique value (-5) for some another made it acceptable:
> [-1,-7,7,-4,19,6,-9,-5,-2,-6]
> 9
> Your answer
> tail connects to node index 9
> Expected answer
> tail connects to node index 9

#### Code you used for Submit/Run operation
```
/**
 * Definition for a singly-linked list.
 * class ListNode {
 *     public $val = 0;
 *     public $next = null;
 *     function __construct($val) { $this->val = $val; }
 * }
 */

class Solution {
    /**
     * @param ListNode $head
     * @return ListNode
     */
    function detectCycle($head) {
        if ($head === null) {
            return $head;    
        }

        $slow = $head;
        $fast = $head->next;
        while ($slow !== null && $fast !== null && $slow !== $fast) {
            $slow = $slow->next;
            $fast = ($fast->next)->next;
        }

        if ($slow === null || $fast === null) {
            return null;
        }

        $period = 0;
        do {
            $slow = $slow->next;
            $fast = ($fast->next)->next;
            $period++;
        } while ($slow !== $fast);

        $selfSeeker = $head;
        $targetSeeker = $head;
        $index = 0;
        do {
            $selfSeeker = $selfSeeker->next;
            if ($index >= $period) {
                $targetSeeker = $targetSeeker->next;
            }
            $index++;
        } while ($selfSeeker !== $targetSeeker);
        
        return $selfSeeker;
    }
}
```

#### Language used for code

PHP, Java

Same algorithm written in Java doesn't fail on [-1,-7,7,-4,19,6,-9,-5,-2,-5] 9 and passes all tests:
Check out my submissions:
https://leetcode.com/submissions/detail/728760972/ - PHP, fails
https://leetcode.com/submissions/detail/728761597/ - Java, accepted

#### Expected behavior
In PHP tests with repeated values in linked list nodes should be successful as well:
> [-1,-7,7,-4,19,6,-9,-5,-2,-5]
> 9
> Your answer
> tail connects to node index 9
> Expected answer
> tail connects to node index 9

#### Additional context

Probably test cases in PHP uses same objects for nodes with repeated values, so it causes an unexpected behavior.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
