### ISSUE TITLE
Editorial- 630. Course Schedule III

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#7893]
#### Your LeetCode username
RohitSgh

#### Category of the bug
- [ ] Question
- [X] Editorial
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Diagram not matching with cases in [Solution](https://leetcode.com/problems/course-schedule-iii/editorial/) **Approach-2 : Recursion with Memoization**

#### Expected behavior

In Approach-2, text has mentioned **4 cases** very well, but diagram has been incorrect.

- In Case-II, $\color{red}{(a+b)>x, a>b, (a+b) ≤ y}$. <br>The same has been mentioned with $\color{maroon}{maroon}$ in diagram. <br>But the correct case which matches with the bars in diagram is $\color{green}{(a+b)>x, b>a, (a+b) ≤ y}$
>![image](https://user-images.githubusercontent.com/81853910/175617418-27e626e7-2371-4f16-96c4-69dd17f65cdd.png)

----

- In Case-III, $\color{red}{(a+b)>x, b>a, (a+b) ≤ y}$. <br>The same has been mentioned with $\color{maroon}{maroon}$ in diagram. <br>But the correct case which matches with the bars in diagram is $\color{green}{(a+b)>x, a>b, (a+b) ≤ y}$
>![image](https://user-images.githubusercontent.com/81853910/175617443-10883bcf-3a2d-4bb8-a950-f948420606e3.png)

---

- In Case-IV, $\color{red}{(a+b)>y}$. <br>There should not be red-cross (❌) in one of the bar, **or** it should be on both the bars. In first bar, we can't proceed with "b", while in second we can't proceed with "a". Irrespective of order, we can take only one course.
>![image](https://user-images.githubusercontent.com/81853910/175643099-be16e76a-4c8e-419c-8e72-a499c3bef5ae.png)

---

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by RohitSgh** [comment]
Any update on this, @LC-Pam ?
