### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by neeharchow** [LeetCode-Feedback/LeetCode-Feedback#7896]
Run Code Status: Unknown Error

#### Your LeetCode username
neeharchow

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Unknown Run Code Status

#### Description of the bug
I keep getting an unknown run code status on the console

#### Code you used for Submit/Run operation
```
# Find maximum product of min(height[i], height[j]) * (j-1)

# Method 1: Brute Force:
# Record all products. Find the maximum value

# Method 2: 

class Solution:
    def maxArea(self, height: List[int]) -> int:
        max_volume = 0
        
        for i in range(0, len(height) - 1):
            for j in range(i+1, len(height)):
                max_volume = max(max_volume, min(height[i], height[j])*(j - 1))
        
        return max_volume
```
#### Language used for code
Python3 

#### Expected behavior
Either time limit exceeded, runtime error, or incorrect answer

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, your code received Wrong Answer when we tested it. please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes![
](https://leetcode.com/submissions/detail/732721375/)
