### ISSUE TITLE
831. 隐藏个人信息 中文题目描述不准确

### ISSUE THREAD

**Issue by VonSdite** [LeetCode-Feedback/LeetCode-Feedback#79]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
831. 隐藏个人信息 中文题目描述不准确，html代码直接显示在题目中了，影响读题。

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢您的反馈，出现的 html 代码已经处理了，力扣会定期更新，保障稳定和体验优化。
