### ISSUE TITLE
Missing Testcase 547. Friend Circles

### ISSUE THREAD

**Issue by gptshubham595** [LeetCode-Feedback/LeetCode-Feedback#790]
#### Your LeetCode username
gptshubham595

#### Category of the bug
- [ 547. Friend Circles ] Question

#### Description of the bug
MISSING TESTCASE [[0]]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int n;
    int findCircleNum(vector<vector<int>>& M) {
         n=M.size();
        int ans=bfs(0,M);
        return ans;
    }
    
    void bfshelper(vector<vector<int>> M,int index,bool vis[]){
        queue<int> q;
        q.push(index);
        vis[index]=1;
        int n=M.size();
        while(!q.empty()){
            int front=q.front();
            q.pop();
            for(int i=0;i<n;i++){
                if(M[front][i]==1 && !vis[i]){
                    q.push(i);
                    vis[i]=1;
                }
            }
        }
        
    }
    int bfs(int ans,vector<vector<int>> M){
        
        bool vis[n];
        memset(vis,0,sizeof(vis));
        for(int i=0;i<n;i++)
            if(!vis[i]){
                ans++;
                bfshelper(M,i,vis);
            }
        return ans;
    }
};
```

#### Expected behavior
WRONG ANSWER FOR [[0]]

#### Screenshots
![image](https://user-images.githubusercontent.com/24877361/89838350-a47e5780-db88-11ea-863c-c5a7a25ae43b.png)

#### Additional context
Add this as testcase [[0]]

**Comment by lc-ivan** [comment]
Hi @gptshubham595 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hello @gptshubham595 ,
Thank you for your feedback regarding this problem. After review, our team has concluded that we will not be adding this test case for this problem as the contributed test case is an invalid case. Thank you once again and happy LeetCoding!
