### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by mohakhan** [LeetCode-Feedback/LeetCode-Feedback#7904]
#### Your LeetCode username
mohakhan03

[301 ] Missing Test Cases 

#### Description of the bug
double data type is not sufficient as return type

#### Code you used for Submit/Run operation
```
class Solution {
    public double myPow(double x, int n) {
        
        if ( n == 0 )
            return 1;
        
        if ( n<0)
        {
            n = -n ; 
            x = 1/x;
        }
        return (n%2==0)? myPow(x*x, n/2):  x*myPow(x*x,n/2); 
    }
}
```

#### Language used for code
Java

#### Expected behavior
the return type of the method is double , I am expecting test cases should be in range so that output can be assigned in 'double'

#### Screenshots
![image](https://user-images.githubusercontent.com/10486488/175777235-b4750ba1-3ade-47ba-bcff-7df946307530.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test cases are "in range", and the validator is correct.
The code simply copied  from https://leetcode.com/problems/powx-n/discuss/19546/Short-and-easy-to-understand-solution
Please  go through the discussion to understand why this code fails for newly added cases. We appreciate your support!
