### ISSUE TITLE
Missing Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by tushar074** [LeetCode-Feedback/LeetCode-Feedback#7907]
#### Your LeetCode username

tushar124

#### Category of the bug
- [ ] Question
- [ ] Wrong Test Case

#### Description of the bug

In the question it says that-"There is only one repeated number in nums array" but in one of the test cases the input array given is nums=[2,2,2,2,2].

#### Code you used for Submit/Run operation

```
class Solution {
    public int findDuplicate(int[] nums) {
        int n =nums.length;
        int sum=0;
        for(int i=0;i<n;i++){
            sum+=nums[i];
        }
        for(int i=1;i<n;i++){
            sum-=i;
        }
        return sum;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The given test case should not be present as per the conditions given in the question.

**Comment by stormsunshine** [comment]
The repeated number can appear two or more times. Could you please read problem description carefully?

**Comment by LC-Pam** [comment]
Thank you for your time. Please refer to stromsunshine's reply. We appreciate your support!
