### ISSUE TITLE
Missing Test Case - 278. First Bad Version

### ISSUE THREAD

**Issue by Ian-Stewart** [LeetCode-Feedback/LeetCode-Feedback#7908]
#### Your LeetCode username
ianstewartbos

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
It's possible to write code which passes all current test cases but which fails every single valid input where n=(2^31)-1

#### Code you used for Submit/Run operation
```
override fun firstBadVersion(n: Int) : Int {
        var lastGood = -1
        var firstBad = n
        while (firstBad - lastGood > 1) {
            val p = lastGood + (firstBad - lastGood).div(2)
            if (isBadVersion(p)) {
                firstBad = p
            } else {
                lastGood = p
            }
        }
        return firstBad
	}
```

#### Language used for code
Kotlin

#### Expected behavior
With the inputs of:
bad = any allowable number (1, 2...)
n =2147483647

This program outputs the first bad version = 2147483647

It should output whatever bad input you put in instead.
#### Screenshots
![failedcase](https://user-images.githubusercontent.com/2956909/175790501-7f43a224-6b56-47fc-aff8-6acb6ee5c56e.png)

#### Additional context
I feel like I'm missing something, or this is gonna get closed with like "we get stuff with JVM int_max all the time stop submitting these" or something because like, I mean 2^31-1 is allowed but the fact that I can submit this answer implies there's no test for it. Again if you've asked people to not send these in, sorry, I couldn't find anything anywhere about that.

Obviously, the problem in the code is the overflow Int.MAX_VALUE - (-1) = Int.MIN_VALUE in the while loop.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Ian-Stewart** [comment]
Sure
https://leetcode.com/submissions/detail/733096399/

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
