### ISSUE TITLE
Missing Test Case - 2305. Fair Distribution of Cookies

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#7909]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[64,32,16,8,4,2,1,1000]
8

#### Code you used for Submit/Run operation

```
class Solution:
    def distributeCookies(self, cookies: List[int], k: int) -> int:

        cur = [0]*k
        ans = sum(cookies)

        def dfs(p,cur):
            nonlocal ans
            if p==len(cookies):
                m=0
                for i in range(k):
                    m=max(m,cur[i])
                if m<ans:
                    ans = m
                return
            for j in range(k):
                cur[j]=cur[j]+cookies[p]
                if cur[j]<=ans:
                    dfs(p+1,cur)
                cur[j]=cur[j]-cookies[p]
        
        dfs(0,cur)
        return ans
```

#### Language used for code

Python3

#### Expected behavior

The code gets TLE.

#### Screenshots

![image](https://user-images.githubusercontent.com/11583428/175793746-4b0193a9-fcaf-44ea-8267-30fdb66ae027.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
