### ISSUE TITLE
Error in Go Submission of 543. Diameter of Binary Tree

### ISSUE THREAD

**Issue by AyushG3112** [LeetCode-Feedback/LeetCode-Feedback#791]
#### Your LeetCode username

ayushg3112

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

For the same input, when running the test case, the output is correct, but when I Submit the solution I get this "Wrong Answer"

#### Code you used for Submit/Run operation

``` go
/**
 * Definition for a binary tree node.
 * type TreeNode struct {
 *     Val int
 *     Left *TreeNode
 *     Right *TreeNode
 * }
 */

var answer int

func diameterOfBinaryTree(root *TreeNode) int {
    if root == nil {
        return 0
    }
    depth(root)
    return answer
}

func depth(root *TreeNode) int {
    if root == nil {
        return 0
    }
    l := depth(root.Left)
    r := depth(root.Right)
    fmt.Println(l, r, answer)
    answer = max(answer,  l  + r)
    fmt.Println(l, r, answer)
    return max(l, r) + 1
    
}

func max(a, b int) int {
    if a < b {
        return b
    }
    return a
}
```

#### Language used for code

Go

#### Expected behavior

Either both test case and submission should fail, or both should pass for the same code and same input

#### Screenshots

https://imgur.com/3tKpgrQ

**Comment by lc-ivan** [comment]
Hi @AyushG3112  ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @AyushG3112 ,
Thank you for your feedback regarding this problem. After review, our team has concluded that we will not be adding this test case for this problem as there is a global variable used that needs to be initialized for each test case. Thank you once again and happy LeetCoding!
