### ISSUE TITLE
Solution of Problem  - 2315. Count Asterisks

### ISSUE THREAD

**Issue by Ayushluthra2001** [LeetCode-Feedback/LeetCode-Feedback#7910]
#### Your LeetCode username

ayushluthra62

#### Category of the bug
- [ ] Question
- [✅] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description 

Solution of problem 2315. Count Asterisks
Link ;-https://leetcode.com/problems/count-asterisks/

#### Code you used for Submit/Run operation

```
// Count Asterisks
class Solution {
public:
    int countAsterisks(string s) {
        int open=0;
        int count=0;
        for(int i=0;i<s.length();i++)
        {
            if(s[i]=='|' && open==0) open++;
            else if(s[i]=='|'&& open>0) open--;
            else if(s[i]=='*'&& open==0 ) count++;
                

        }
        return count;
        
    }
};
```

#### Language used for code

C++

**Comment by Ayushluthra2001** [comment]
This is solution for Problem  2315. Count Asterisks
Problem Link :-https://leetcode.com/problems/count-asterisks/

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!

**Comment by Ayushluthra2001** [comment]
Why this solution is not accepted yet??
