### ISSUE TITLE
16. 3sum-closest both official python solution get TLE

### ISSUE THREAD

**Issue by glebmikha** [LeetCode-Feedback/LeetCode-Feedback#7911]
#### Your LeetCode username
glebmikhaylov

#### Category of the bug
- [ ] Question
- Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hi! All official solutions for 3sum-closest in solution article get TLE in python, there are many such complaints in comments to the article. Please check.

#### Language used for code

Python 3

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
