### ISSUE TITLE
Missing Test Case - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by sunayanajindal** [LeetCode-Feedback/LeetCode-Feedback#7912]
#### Your LeetCode username

sunayanajindal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug

Can change the return type of the serialize function and input parameter type of the deserialize function

#### Code you used for Submit/Run operation

```
class Codec {
public:

    // Encodes a tree to a single string.
    TreeNode* serialize(TreeNode* root) {
        return root;
    }

    // Decodes your encoded data to tree.
    TreeNode* deserialize(TreeNode* data) {
        return data;
    }
};
```

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

#### Expected behavior

There was no conversion done and still, the solution was accepted.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
