### ISSUE TITLE
Getting wrong answer in  leetcode compiler and getting correct answer in vs code

### ISSUE THREAD

**Issue by kapil4457** [LeetCode-Feedback/LeetCode-Feedback#7913]
#### Your LeetCode username

kapilsoni54768161

#### Category of the bug
- [ ] Question
- [1] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I am getting wrong answer on leetcode compiler and getting correct answer on other compilers

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */

void reverse(ListNode *root, int start, int end)
{
    ListNode *temp1 = root;

    ListNode *helper = root;

    ListNode *temp2 = root;

    stack<int> s1;

    for (int i = 0; i < start; i++)
    {
        temp1 = temp1->next;
        helper = helper->next;
    }

    for (int i = 0; i < end; i++)
    {
        temp2 = temp2->next;
    }

    while (temp1 != temp2)
    {
        s1.push(temp1->val);
        temp1 = temp1->next;
    }

    while (helper != temp2)
    {
        int data = s1.top();
        s1.pop();
        helper->val = data;
        helper = helper->next;
    }
}
 

int len(ListNode * root){
      ListNode *temp = root;
    int len = 0;

    while (temp != NULL)
    {
        temp = temp->next;
        len++;
    }

    return len;
}


class Solution {
public:
    ListNode* reverseKGroup(ListNode* head, int k) {
       ListNode *temp = head;
    int length = len(head);
    int start = 0;

    while (length != (length % k))
    {
        reverse(head, start, k);
        start += k;
        k += k;
        length -= k;
    }

    return head;
    }
};
```

#### Language used for code
 C++

#### Expected behavior

Expected to reverse the whole Linked List but is rather only reversing the first block

#### Screenshots

![Reverse_N_Nodes_in_K_Groups_LeetCode](https://user-images.githubusercontent.com/78656206/175813497-83c7d2fb-856f-42e1-b1cc-56fc9da62d99.PNG)

![Reverse_N_Nodes_in_K_Groups_VS_Code](https://user-images.githubusercontent.com/78656206/175813503-7480ba34-588a-43c3-9897-5e2c6a086589.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The submission accepted link on other compilers
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
