### ISSUE TITLE
there is a minor change in language of question .  494. Target Sum

### ISSUE THREAD

**Issue by pranav560** [LeetCode-Feedback/LeetCode-Feedback#7916]
#### Your LeetCode username
 pranav560 

#### Category of the bug
- [x] Question

#### Description of the bug

there is a minor correction in language of question . instead of writing "given a array of integers" write it as "given a array of non negative integers "

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
