### ISSUE TITLE
Missing Test Case - 522. Longest Uncommon Subsequence II

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#7921]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
["abaa","abaa","eaec","eaec","eae","z"]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findLUSlength(vector<string>& strs) {
        unordered_map<string, int> h;
        int ans = -1, l = 0;
        string* ps;
        for(auto&& str: strs) {
            ++h[str];
            if(str.size() > l) ps = &str, l = str.size(); 
        }
        for(auto&& str: strs) 
            if(h[str] == 1) {
                if(str.size() < l)
                    for(int i = 0, j = 0; i < l; ++i){
                        if(ps->at(i) == str[j]) {
                            ++j;
                            if(j == str.size()) goto match;
                        }
                    }
                ans = max<int>(ans, str.size());
                match:;
            }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Output: 3
Expected: 1

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
