### ISSUE TITLE
522. 最长特殊序列 II 的题目翻译

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#7922]
> 

**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[522. 最长特殊序列 II](https://leetcode.cn/problems/longest-uncommon-subsequence-ii/)
> 给定字符串列表 strs ，返回其中 最长的特殊序列 。如果最长特殊序列不存在，返回 -1 。

应改为 返回其中 最长的特殊序列 **的长度**（而不是 特殊序列 本身）

**期望行为**
- 该题目的示例和测试用例，判断的都是 特殊序列的长度
- 该题目的英文说明，翻译过来，也是长度：
> return **the length of** the longest uncommon subsequence between them

**屏幕截图**
- [522. 最长特殊序列 II](https://leetcode.cn/problems/longest-uncommon-subsequence-ii/)
![image](https://user-images.githubusercontent.com/4961543/175871292-303efce0-b918-47f6-826c-5f071616671c.png)
- [522. Longest Uncommon Subsequence II](https://leetcode.com/problems/longest-uncommon-subsequence-ii/)
![image](https://user-images.githubusercontent.com/4961543/175871416-627eca69-4208-4717-b8b9-074b400c4340.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。
