### ISSUE TITLE
Missing Test Case - 566. Reshape the Matrix

### ISSUE THREAD

**Issue by shreedharhegde99** [LeetCode-Feedback/LeetCode-Feedback#7924]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the given input of the second example question, it is expected to get a 2 * 4 array as output while the given array is of size  2 * 2.

#### Code you used for Submit/Run operation

```
/**
 * @param {number[][]} mat
 * @param {number} r
 * @param {number} c
 * @return {number[][]}
 */
var matrixReshape = function(mat, r, c) {
    
    let ans = [];
    let arr =[];
    for(let i=0; i<mat.length;i++){
        for(let j=0;j<mat[0].length; j++){
           arr.push(mat[i][j]);
            }
        }
    
    
    let k=0;
     while(k<arr.length){
         let l=0;
         let temp=[];
         while(l<c ){
             temp.push(arr[k]);
             l++;
             k++;
         }
         ans.push(temp);
     }

return ans;
};
```

#### Screenshots

![Screenshot from 2022-06-27 12-27-18](https://user-images.githubusercontent.com/90758718/175880327-60c18394-666c-4f62-9b81-1409f10f0bd9.png)

**Comment by stormsunshine** [comment]
Please read the problem description carefully. Especially the sentence in bold.

> If the `reshape` operation with given parameters is possible and legal, output the new reshaped matrix; **Otherwise, output the original matrix.**

**Comment by shreedharhegde99** [comment]
That solves the query. Thank you @stormsunshine for your guidance.
