### ISSUE TITLE
There is a mistake in problem statement of problem no 1689

### ISSUE THREAD

**Issue by harjotjuneja6** [LeetCode-Feedback/LeetCode-Feedback#7931]
According to the problem we can only choose the combinations of 0's and 1's . But if we take a testcase="56" , then we cannot make a set which sums to 56 and when I ran so it gave answer as 6.
So the answer 6 is only possible when we take (11+11+11+11+11+01). But it includes 01 which has a leading 0. But in question it is mentioned that there should be no leading zeros. Please look into this problem. Love you LeetCode.

 Your LeetCode username - harjotjuneja6 

#### Category of the bug
- [ ] Question   - 1689
- [ ] Solution   - Correct the statement by removing leading zeros statement.
- [ ] Language  - C++
- [ ] Missing Test Cases - 56,78 etc

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![WhatsApp Image 2022-06-27 at 9 20 45 PM](https://user-images.githubusercontent.com/69711717/176014135-04864057-2784-4229-9661-7eca058ed9e9.jpeg)

![WhatsApp Image 2022-06-27 at 9 20 45 PM](https://user-images.githubusercontent.com/69711717/176014150-56dd1379-39f9-463c-8f2a-57893230dc8c.jpeg)

**Comment by LC-Pam** [comment]
Thank you for your time. The answer is (11+11+11+11+11+1) and all the 6 numbers are deci-binary, please read the statement carefully. We appreciate your support!
