### ISSUE TITLE
Incomplete sentence in solution to "Palindrome Pairs" problem

### ISSUE THREAD

**Issue by richiethomas** [LeetCode-Feedback/LeetCode-Feedback#7932]
#### Your LeetCode username

`rickthomas1980`

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the 3rd paragraph of the `Additional Discussion: Online Algorithms` section, the last sentence reads:

> It's a little bit different to before, because we need to find all pairs with previous words that

The paragraph doesn't specify anything after `all pairs with previous words that`, so I'm not sure what the full meaning of this sentence is supposed to be.

#### Code you used for Submit/Run operation

n/a

#### Language used for code
n/a

#### Expected behavior
A complete sentence describing what kind of "previous words" the author meant (i.e. "previous words that meet criteria A, B, and C."

#### Screenshots

<img width="973" alt="Screen Shot 2022-06-27 at 1 51 30 PM" src="https://user-images.githubusercontent.com/3839713/176033685-93ff1a99-00af-459b-aad2-e3a9ecf091bd.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team, but it will take more time to evaluate and fix. We appreciate your support!
