### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by iqrabismii** [LeetCode-Feedback/LeetCode-Feedback#7934]
#### Category of the bug
- [ ] Question: Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

The overall run time complexity should be O(log (m+n)).

- [ ] Language: python

#### Code you used for Submit/Run operation

```
def findMedianSortedArrays(self, nums1, nums2):
        """
        :type nums1: List[int]
        :type nums2: List[int]
        :rtype: float
        """
        
        k = len(nums1)+len(nums2)
        
        nums1.extend(nums2)
        nums1.sort()
        med=0
        if k%2==0:
            med = float((nums1[(k//2)-1]+nums1[(k//2)]))/2
        else:
            med= nums1[k//2]
        return float(med)
        
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
