### ISSUE TITLE
18. 4Sum Official Solution Failed (Java)

### ISSUE THREAD

**Issue by zhao-zihan** [LeetCode-Feedback/LeetCode-Feedback#7935]
#### Your LeetCode username

[candichen66](https://leetcode.com/candichen66)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The official solution for 18. 4Sum failed the newly added test case `[-1000000000,-1000000000,1000000000,-1000000000,-1000000000] target = 294967296`

The average value test used in the official solution is not sufficient enough to rule out all edge cases. In the above case, notice that the middle element is a positive one billion, which won't trigger the average value test after the initial sorting, and the rest four negative billions would add up to the target value due to java int number underflow.

I made a simple revision by testing each subset in the res list before returning the final result in the recursive for loop, the rest is the same as the official solution. The process is quite easy since all the sublists are returned in non-decreasing order, so I borrowed the code from the average value test.

#### Code you used for Submit/Run operation

```java
//18. 4Sum
class Solution {
    public List<List<Integer>> fourSum(int[] nums, int target) {
        Arrays.sort(nums);
        return kSum(nums, target, 0, 4);
    }
	
    public List<List<Integer>> kSum(int[] nums, int target, int start, int k) {
        List<List<Integer>> res = new ArrayList<>();

        if (start == nums.length) {
            return res;
        }
        
        //the average value test that I was referring to
        int average_value = target / k;
        
        if  (nums[start] > average_value || average_value > nums[nums.length - 1]) {
            return res;
        }
        
        if (k == 2) {
            return twoSum(nums, target, start);
        }
    
        for (int i = start; i < nums.length; ++i) {
            if (i == start || nums[i - 1] != nums[i]) {
                for (List<Integer> subset : kSum(nums, target - nums[i], i + 1, k - 1)) {
                    res.add(new ArrayList<>(Arrays.asList(nums[i])));
                    List<Integer> sub = res.get(res.size() - 1);
                    sub.addAll(subset);
                    //insert average value test here
                    if (sub.get(0) > target / k || target / k > sub.get(sub.size() - 1)) 
                        return new ArrayList<>();
                }
            }
        }
    
        return res;
    }
	
    public List<List<Integer>> twoSum(int[] nums, int target, int start) {
        List<List<Integer>> res = new ArrayList<>();
        int lo = start, hi = nums.length - 1;
    
        while (lo < hi) {
            int currSum = nums[lo] + nums[hi];
            if (currSum < target || (lo > start && nums[lo] == nums[lo - 1])) {
                ++lo;
            } else if (currSum > target || (hi < nums.length - 1 && nums[hi] == nums[hi + 1])) {
                --hi;
            } else {
                res.add(Arrays.asList(nums[lo++], nums[hi--]));
            }
        }
                                                          
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Correction of the official solution

#### Additional context

Thank you!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by neal2018** [comment]
Hey, I am neal from the LeetCode Content team. We have investigated this issue and we think it is valid.

We plan to change the helper functions' signature from `int` to `long` / `long long` since we want to avoid unnecessary special checks. We believe your fix is also great, and both have different pros and cons.

Thanks for reporting the issue and please let me know if you have any questions.

**Comment by zhao-zihan** [comment]
I have no further questions and thank you for such a quick update!
