### ISSUE TITLE
Missing Test Case - 1729. Find Followers Count

### ISSUE THREAD

**Issue by ranahamid** [LeetCode-Feedback/LeetCode-Feedback#7936]
#### Your LeetCode username
ranahamid

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✔ ] Missing Test Cases 

#### Description of the bug

Without using the order by is SQL server console, I got accepted. But, in MySQL its correct. 

#### Code you used for Submit/Run operation

```
select user_id , count(*) as followers_count
from Followers
group by(user_id)
```

#### Language used for code
MS SQL Server

#### Expected behavior
It should rejected the code as success.

**Comment by LC-Pam** [comment]
Thank you for your time. MySQL and MSSQL are two different languages. They do not necessarily work on the same way.
 We appreciate your support!
