### ISSUE TITLE
20. Valid Parentheses - Incorrect solution accepted - Missing test case

### ISSUE THREAD

**Issue by PalSzak** [LeetCode-Feedback/LeetCode-Feedback#7937]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
20. Valid Parentheses - Incorrect solution accepted - Missing test case
I have an actually wrong solution that is accepted.

Test case to prove my solution is wrong:
```
"([([)]])"
```

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
  int[] counts = new int[3];
  String order = "";

  private int indexOf(char c){
    int idx = order.indexOf(c);
    if(idx == -1){
      idx = order.length();
      order += c;
    }
    
    return idx;
  }
  
  private char openOf(char c){
    switch(c){
      case ')':
        return '(';
      case '}':
        return '{';
      case ']':
        return '[';
      default:
        return c;
    }
  }

  private int changeOf(char c){
    return "{[(".contains(""+c) ? 1 : -1;
  }

  public boolean isValid(String s) {
    
    for(char c : s.toCharArray()){
      int idx = indexOf(openOf(c));
      counts[idx] =  counts[idx] + changeOf(c);
      
      if(counts[idx] == 0){
        if(order.indexOf(openOf(c))!=order.length()-1){
          return false;
        } else {
          order = order.substring(0, order.length()-1);
        }
      }
      
      if(counts[0] < 0 || counts[1] < 0 || counts[2] < 0)
        return false;
    }

    return (counts[0] == 0 && counts[1] == 0 && counts[2] == 0);
  }
}
```

#### Language used for code

Java

#### Expected behavior

Reject my wrong solution.

#### Additional context

I posted this issue on leetcode's forum too.
https://leetcode.com/discuss/feedback/2208631/20.-Valid-Parentheses-Incorrect-solution-accepted-Missing-test-case

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Would you mind sending us your username, please?

**Comment by PalSzak** [comment]
You are welcome!
My LeetCode ID: user4957MI
