### ISSUE TITLE
Missing Test Case - 1147. Longest Chunked Palindrome Decomposition

### ISSUE THREAD

**Issue by rasho18** [LeetCode-Feedback/LeetCode-Feedback#7941]
#### Your LeetCode username
rasho

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [y ] Missing Test Cases 

#### Description of the bug

a missing test case

#### Code you used for Submit/Run operation

```
class Solution {
public:
   int longestDecomposition(string text) {
        int res = 0;
        int l = 0, r = text.length() - 1;
        stack<int> s;
        queue<int> q;
        while (l < r) {
            s.push(text[l++]);
            q.push(text[r--]);
            while (!s.empty() && s.top() == q.front()) {
                q.pop();
                s.pop();
            }
            if (s.empty())
                res += l <= r ? 2 : 1;
        }
        return res + 1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

it's just a mssing test case
even though i submitted this code it was passing all the test cases but actually it should fail for  this test case"abcxabxc"

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by LC-Pam** [comment]
Would you mind sending us your username, please?

**Comment by rasho18** [comment]
Hrushee

profile link -  https://leetcode.com/Hrushee/
