### ISSUE TITLE
Grammatical error - 1509. Minimum Difference Between Largest and Smallest Value in Three Moves

### ISSUE THREAD

**Issue by deez-69-nuts** [LeetCode-Feedback/LeetCode-Feedback#7944]
####

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Grammatical error in the hint section of the problem.(repetition of 'is')

Original text:
The minimum difference possible is is obtained by removing 3 elements between the 3 smallest and 3 largest values in the array.
New text:
The minimum difference possible is obtained by removing 3 elements between the 3 smallest and 3 largest values in the array.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
