### ISSUE TITLE
step-by-step-directions-from-a-binary-tree-node-to-another test case error.

### ISSUE THREAD

**Issue by alisener** [LeetCode-Feedback/LeetCode-Feedback#7945]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

test case 40 is wrong. example inputs in the question are given (or at least printed by BFS form) but how can you build this tree and have expected directions end with a Left where 2 is the last printed node. 

Input:
[13,5,4,7,null,8,6,3,null,null,12,9,1,null,null,11,null,null,10,null,null,null,null,2]
3
2
Output:
"RR"
Expected:
"UUURRLRL"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by alisener** [comment]
Attached my code below. But my code leverages the index of the input tree (just like it is printed in the question)  to calculate the parent. but It has a flaw that it doesn't count that it wouldn't print the child of the null. so level 4 for example doesn't always have 8 entires. but regardless, I cannot rebuild a tree from this input and have the last direction "Left" since destination 2 is the last node printed. If 2 is a left child wouldn't be the input [........, 2, NULL]?

`/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    std::vector<int> bfsList;
    string getDirections(TreeNode* root, int startValue, int destValue) {

        getLevelOrder(root);
        // printList(bfsList);
        std::string output = findDirections(bfsList, startValue, destValue);
        // // std::cout << "output: " << output << std::endl;
        return output;
        // return "";
        
    }
    
    void printList(std::vector<int> inputList)
    {
      std::vector<int>::const_iterator it;
      for (it = inputList.begin(); it < inputList.end(); ++it)
      {
        std::cout << *it << " ";
      }
      std::cout << std::endl;
    }
    
    void getLevelOrder(TreeNode* root)
    {
      int h = height(root);
      int i;
      for (i = 1; i <= h; i++)
          getCurrentLevel(root, i);
    }

    void getCurrentLevel(TreeNode* root, int level)
    {
      if (root == NULL)
      {
        bfsList.push_back(0);
        return;
      }
      if (level == 1)
        bfsList.push_back(root->val);
      else if (level > 1) {
          getCurrentLevel(root->left, level - 1);
          getCurrentLevel(root->right, level - 1);
      }
    }

    int height(TreeNode* node)
    {
      if (node == NULL)
          return 0;
      else {
          /* compute the height of each subtree */
          int lheight = height(node->left);
          int rheight = height(node->right);
  
          /* use the larger one */
          if (lheight > rheight) {
              return (lheight + 1);
          }
          else {
              return (rheight + 1);
          }
      }
    }
    
    int getIndex(std::vector<int> inputList, int i)
    {
        std::vector<int>::const_iterator it = std::find(inputList.begin(), inputList.end(), i);
        if (it != inputList.end())
        {
          return it - inputList.begin(); 
        }
        else
          return -1;
    }
    
  std::string findDirections(std::vector<int> nodeList, int s, int e)
  {
    std::string sOutput;
    std::string eOutput;
    int sIndex = getIndex(nodeList, s);
    int eIndex = getIndex(nodeList, e);
    // int levels = sqrt(nodeList.size());
    int sLevel = -1;
    int eLevel = -2;
    int sLevelIndex = -1;
    int eLevelIndex = -2;


    while(sIndex != eIndex)
    {
      sLevel = floor(sqrt(sIndex+1));
      eLevel = floor(sqrt(eIndex+1));
      sLevelIndex = sIndex - pow(2,sLevel)+1;
      eLevelIndex = eIndex - pow(2,eLevel)+1;
      // std::cout << "sIndex: " << sIndex;
      // std::cout << " eIndex: " << eIndex;
      // std::cout << " sLevel: " << sLevel;
      // std::cout << " eLevel: " << eLevel;
      // std::cout << " sLevelIndex: " << sLevelIndex;
      // std::cout << " eLevelIndex: " << eLevelIndex << std::endl;

      if (sLevel > eLevel)
      {
        //=FLOOR.MATH(levelIndex/2)+POWER(2,level-1)-1 ->pIndex
        sIndex = floor(sLevelIndex/2) + pow(2, sLevel-1)-1;
        sLevel = floor(sqrt(sIndex+1));
        sOutput.append("U");
      }
      else if(sLevel < eLevel)
      {
        if ( (eLevelIndex % 2) == 0) //left child
        {
          eIndex = floor(eLevelIndex/2) + pow(2, eLevel-1)-1;
          eLevel = floor(sqrt(eIndex+1));
          eOutput = std::string("L") + eOutput;
        }
        else //right child
        {
          eIndex = floor(eLevelIndex/2) + pow(2, eLevel-1)-1;
          eOutput = std::string("R") + eOutput;
        }
      }
      else //same level
      {
        if (sIndex > eIndex)
        {
          sIndex = floor(sLevelIndex/2) + pow(2, sLevel-1)-1;
          sLevel = floor(sqrt(sIndex+1));
          sOutput.append("U");
        }
        else
        {
          if ( (eLevelIndex % 2) == 0) //right child
          {
            eIndex = floor(eLevelIndex/2) + pow(2, eLevel-1)-1;
            eLevel = floor(sqrt(eIndex+1));
            eOutput = std::string("L") + eOutput;
          }
          else //right child
          {
            eIndex = floor(eLevelIndex/2) + pow(2, eLevel-1)-1;
            eLevel = floor(sqrt(eIndex+1));
            eOutput = std::string("R") + eOutput;
          }
        }
      }
    }

    return sOutput + eOutput;
  }
    
    
    
    

};`

**Comment by LC-Pam** [comment]
Would you mind sending us your code submission accepted link? Because the code that you provided received wrong answer when we test it.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
