### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by AlaiShubham** [LeetCode-Feedback/LeetCode-Feedback#7947]
#### Your LeetCode username

Alai_

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing Test Cases : [1,2,1,3,5,6,4,7,1,2,4,8]

#### Description of the bug

I wrote a code that passes all test cases and got submission result as accepted. But same code fail to pass one custom created test case by me. That means there is a missing test case and my code bypass the stiuation that should exists as per question requirement.

#### Code you used for Submit/Run operation

```
class Solution {
    public int findPeakElement(int[] nums) {
        if(nums.length==1)
            return 0;
        
        int low = 0, high = nums.length-1;
        
        while(low<high){
            int mid = (high + low)/2;
            
            if((mid==0 || nums[mid - 1]<nums[mid]) && (mid==nums.length-1 || nums[mid+1]<nums[mid])){
                return mid;
            }
            
            if((mid!=0 && nums[mid]>nums[mid-1]) || (mid!=nums.length-1 && nums[mid+1]>nums[mid]))
                low = mid + 1;
            else
                high = mid - 1;
        }
        
        return low;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Custom test case expected answer was 11 but my code result answer as 5. Still my code passes all test cases and got accepted which is wrong. 
Please include above mentioned test case i.e. [1,2,1,3,5,6,4,7,1,2,4,8] into your testing set. Code submitted by user need to pass this case also.

#### Screenshots

![Accepted_code](https://user-images.githubusercontent.com/88656611/176276989-9eb4b53b-e0fd-407b-b45e-3302ab6a165e.png)
![SameCode_Fail_CustomTestCase](https://user-images.githubusercontent.com/88656611/176277652-655a2918-4fed-490b-b4d8-dc48ac22de75.png)

1. Accepted_code : My that pass all cases
2. SameCode_Fail_CustomTestCase : Accepted code fails a custom test case

#### Additional context

Adding missing test case i.e. [1,2,1,3,5,6,4,7,1,2,4,8] to testing case will add more accuracy to question. It will also help users to code more precise code as per question details while considering all test scenario in order to enhance their skills.

**Comment by stormsunshine** [comment]
Did you read the problem description carefully?
> If the array contains multiple peaks, return the index to **any of the peaks**.
