### ISSUE TITLE
Invalid Testcase- 415. Add Strings

### ISSUE THREAD

**Issue by RiskyTrick** [LeetCode-Feedback/LeetCode-Feedback#7949]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The constraints of this program are limited to  being <10 power 4 but instead it is giving hute inputs such as Input
"3876620623801494171"
"6529364523802684779"
Output
"-8040758926105372666"
Expected
"10405985147604178950"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
In this test case, both input strings have lengths far less than 10<sup>4</sup>. What is the problem with this test case?
