### ISSUE TITLE
Error Testcase Leetcode 161 One Edit Distance

### ISSUE THREAD

**Issue by djx0716** [LeetCode-Feedback/LeetCode-Feedback#795]
Input:
"a"
"a"
Output:
false

With this input, we should return true because we can replace either "a" with a character 'a', so that  both strings are one edit distance.

**Comment by lc-ivan** [comment]
Hello @djx0716 ,
Thanks for reaching out to us! To proceed with this request, could you please provide the code you have used to submit and the associated language?

**Comment by djx0716** [comment]
**Code you used for Submit/Run operation**
```
class Solution {
    public boolean isOneEditDistance(String s, String t) {
        // inserting a char and deleting a char is the kind of operation
        int len_s = s.length(), len_t = t.length();
        if(len_s == 0 && len_t == 0)    return false;
        if(Math.abs(len_s - len_t) > 1) return false;
        if(len_s == 0 || len_t == 0)    return true;
        if(len_s == len_t)
            return replace(s, t);
        else if(len_s + 1 == len_t)
            return insert(s, t);
        else if(len_t + 1 == len_s)
            return insert(t, s);
        return false;
    }
    
    public boolean replace(String s, String t){
        boolean foundDiff = false;
        for(int i=0; i<s.length(); i++){
            if(s.charAt(i) != t.charAt(i)){
                if(foundDiff)   return false;
                foundDiff = true;
            }
        }
        return foundDiff;
    }
    /* check if you can insert one char into s to make t*/
    public boolean insert(String s, String t){
        int index1 = 0, index2 = 0;
        while(index1 < s.length() && index2 < t.length()){
            if(s.charAt(index1) != t.charAt(index2)){
                if(index1 != index2)    return false;
                index2++;
            }
            else{
                index1++;
                index2++;
            }
        }
        return true;
    }
}
```

**Language**
Java

Description:
In function `public boolean replace(String s, String t)`, if with input t = "a", s = "a", this function returns false, and solution function returns false. However, this should be incorrect, because we can replace s with a character 'a', so that t and s are one edit distance, therefore the expected output should be true.

**Comment by lc-ivan** [comment]
Hi @djx0716 ,
Could you please provide your LeetCode username?

**Comment by djx0716** [comment]
@lc-ivan 
djx0716 is my username

**Comment by lc-ivan** [comment]
Hi @djx0716 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
