### ISSUE TITLE
面试题 04.10. 检查子树

### ISSUE THREAD

**Issue by noobpeng99** [LeetCode-Feedback/LeetCode-Feedback#7951]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
不羁的风

**Bug 类型**

- [ ❌]  题目
- [ ❌]  题解
- [ ❌]  缺少测试用例

**描述**
题目的描述是不够的，或者说以下解法可以ac，但是并不能完美地符合所有可能的情况

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public boolean checkSubTree(TreeNode t1, TreeNode t2) {
        if(t1 == null && t2 == null) return true;
        if(t1 == null || t2 == null) return false;
        if (t1.val == t2.val) {
            return checkSubTree(t1.left, t2.left) && checkSubTree(t1.right, t2.right);
        }
        return checkSubTree(t1.left, t2) || checkSubTree(t1.right, t2);
    }
}
```

**期望行为**

期望能够补充测试用例，或是修改题目描述为每棵树中节点值不相同。

**屏幕截图**
<img width="881" alt="checkSubTree" src="https://user-images.githubusercontent.com/37838230/176376904-56521bf7-53e0-4196-8b8b-9135fac25bc9.png">

**额外的上下文**

上面的代码的问题在于，当在T1中搜索到与T2的根一致的节点时，就默认T1中只有这一个节点可能成为符合题意的子树的根的，这样做的问题在于：如果节点之间的值互异是没问题的，如果T1中有节点的值相同且都等于T2的根的值，就有这样一种可能：T2在T1中对应的子树不是从这个节点开始，而是从与这个节点的值相同的某个子孙节点开始。

这种情况有点类似于字符串匹配中，在主串S中找到一个与模式串P某个前缀相匹配的子串，即S[i:i+m] = P[0:m]，在发现S[i+m+1] != P[m+1]时直接返回了false

**Comment by BrambleWave** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。
