### ISSUE TITLE
Missing Test Case - 1405. Longest Happy String

### ISSUE THREAD

**Issue by SaGa2903** [LeetCode-Feedback/LeetCode-Feedback#7958]
#### Your LeetCode username
Saga_2903

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

One of the test cases can be:
3
3
13

Were wrong solutions accepted because we missed these testcases? --YES

My code got accepted(Success), but using the above test case my code was failing. So, this test case can be included in the question.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string longestDiverseString(int a, int b, int c) {
        string m1,m2,m3;
        string ans="",s;
        vector<pair<int,string>> p;
        p.push_back({a,"a"});
        p.push_back({b,"b"});
        p.push_back({c,"c"});
        
        sort(p.begin(), p.end());
        m3=p[0].second;
        m2=p[1].second;
        m1=p[2].second;
        c=p[0].first;
        b=p[1].first;
        a=p[2].first;
        
        
        s=m1+m2+m3;
        //cout<<s;
        //while(a!=0||b!=0||c!=0)
        {
            while(a>0&&b>0&&c>0){
                ans+=s;
                a--;b--;c--;
            }
            s=m1+m2;
            while(a>0&&b>0){
                ans+=s;
                a--;b--;
            }
            
        }
        int n = ans.size();
        if(a==0) return ans;
        string out=m1;
        
        for(int i = 1; i<n; i++){
            if(ans[i]==m1[0]){
                out+=m1;
                continue;
            }  
            if(a>1){
                //string temp = "m1"+ans[i] +"m1";
                if(i!=n-1 && ans[i+1]=='c'){
                    out+=m1;
                    out+=ans[i];
                    a--;
                }
                else{
                    a-=2;
                    out+=m1;
                    out+=ans[i];
                    out+=m1;
                }
                // out+=temp;  
            }
            else if(a==1){
                out+=m1;
                out+=ans[i];
                a--;
            }
            else{
                out+=ans[i];
            }
            
        }
        if(a>0) out+=m1;
        return out;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My submission should have got rejected due to this testcase, but it got accepted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
