### ISSUE TITLE
421. 数组中两个数的最大异或值 中英文数据范围不一致

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#7959]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
hqztrue

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
中文数据范围：1 <= nums.length <= 2 * 10^4
英文数据范围：1 <= nums.length <= 2 * 10^5

**Comment by BrambleWave** [comment]
你好，当前题目描述已更新，已给予积分奖励，请查收。
