### ISSUE TITLE
93. Restore IP Addresses

### ISSUE THREAD

**Issue by weiquanmao** [LeetCode-Feedback/LeetCode-Feedback#796]
Can't handle string such as "0001011", but can handle string like "255.25511".

Input verification may be needed, and make it clear whether  integer like '01' is valid.

**Comment by lc-pam** [comment]
Hi @weiquanmao 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @weiquanmao 
Thank you for your time. We've used your feedback to update the problem. Please leave your leetcode id in the comment so we can reward your LeetCode account with LeetCoins. We appreciate your support!
