### ISSUE TITLE
Missing Test Case - 462. Minimum Moves to Equal Array Elements II

### ISSUE THREAD

**Issue by sumitnirankari** [LeetCode-Feedback/LeetCode-Feedback#7967]
#### Your LeetCode username
sumitnirankari

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code is getting submitted even with incorrect logic.

#### Code you used for Submit/Run operation

```
class Solution:
    def minMoves2(self, nums: List[int]) -> int:
        L = len(nums)
        if L == 1:
            return abs(nums[0] - 1)
        nums.sort()
        
        m = nums[L//2]
        ans = 0
        for n in nums:
            ans += abs(n - m)
        return ans
```

#### Language used for code

Python3

#### Expected behavior

It should fail for below any input array of size 1 and nums[0] > 1

example:
nums = [25]
Expected output=0

But the provided code will return 24 ans still it is getting submitted successfully.

Bassicly, there are no testcases with array of size 1

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've Added more test cases.  We appreciate your support!
