### ISSUE TITLE
Wrong Solution for problem 1064. Fixed Point

### ISSUE THREAD

**Issue by RaviKumarAgurla** [LeetCode-Feedback/LeetCode-Feedback#7971]
Hi,

Solution provided for problem(1064. Fixed Point) is not relevant.

Solution URL : https://leetcode.com/problems/fixed-point/solution/.

![image](https://user-images.githubusercontent.com/22034235/176734916-b1d0fa96-75b1-4a3e-9c67-9a502f1e1218.png)

Thanks,
Ravi Kumar Agurla.
LeetCode Userid : RaviKumarAgurla.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
