### ISSUE TITLE
Missing Test Case - 1030. Matrix Cells in Distance Order

### ISSUE THREAD

**Issue by kshitij01042002** [LeetCode-Feedback/LeetCode-Feedback#7976]
#### Your LeetCode username

kshitijpatil1098 

#### Category of the bug
- [ ] Question
- [YES ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Question says that i may return the answer in any order but when doing so, it is not accepting the answer 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int[][] allCellsDistOrder(int rows, int cols, int rCenter, int cCenter) {
        int ans[][] = new int[rows*cols][2];
        int i =0;
        int k =0;
        while(i<rows*cols){
            for(int j=0; j<cols; j++){
                ans[i+j][0] = k;
                ans[i+j][1] = j;
            }
            k++;
            i = i+cols;
        }
        
        for(int j=0; j<rows*cols; j++){
            ans[j][0] = Math.abs(rCenter - ans[j][0]);
            ans[j][1] = Math.abs(cCenter - ans[j][1]);
        }
        return ans;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
It should Accept the answer. but it's not

#### Screenshots
![image](https://user-images.githubusercontent.com/91470808/176833615-74a7cf14-cb3d-4279-9e7c-18983a52c74e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
