### ISSUE TITLE
meituan-001. 小美的用户名

### ISSUE THREAD

**Issue by lqzo** [LeetCode-Feedback/LeetCode-Feedback#7977]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
提示中的 [了解书写规则](https://support.leetcode-cn.com/hc/kb/article/1519140/) 的链接需要更新了,   原有的这个链接`https://support.leetcode-cn.com/hc/kb/article/1519140/` 点击后虽然仍能访问，但会提示虚假网站

**屏幕截图**
<img width="742" alt="image" src="https://user-images.githubusercontent.com/30641714/176834636-a799282e-bfdc-48d7-b8b6-1748cd4677a0.png">
<img width="817" alt="image" src="https://user-images.githubusercontent.com/30641714/176834821-8a9eab66-a1f9-4d16-882d-03cab2901cc3.png">

**Comment by BrambleWave** [comment]
感谢您的反馈，我们会尽快完成修改。
