### ISSUE TITLE
Missing Test Case - 1419. Minimum Number of Frogs Croaking

### ISSUE THREAD

**Issue by Karandeep1234** [LeetCode-Feedback/LeetCode-Feedback#7978]
#### Your LeetCode username

Karandeep1234

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution is giving WA on following testcase and still getting accepted. Testcase on which my solution give wa:
Testcase: "croakc"

#### Code you used for Submit/Run operation

```
class Solution {
    public int minNumberOfFrogs(String c) {
        int max=0;
        int cf=0;
        int cr=0,co=0,ca=0,cc=0,ck=0; 
        for(int i=0;i<c.length();i++){
            char ch=c.charAt(i);
            
            if(ch=='c') {
                cf++;
                cc++;
            }
            else if(ch=='k') {
                cc--;
                cr--;
                co--;
                ca--;
                if(cr<0 || co<0 || ca<0 || cc<0) return -1;
                cf--;
            }else if(ch=='r'){
                cr++;
                if(cr>cc) return -1;
            }else if(ch=='o'){
                co++;
                if(co>cc || co>cr) return -1;
            }else if(ch=='a'){
                ca++;
                if(ca>cc || ca>cr || ca>co) return -1;
            }else{
                return -1;
            }
            max=Math.max(cf,max);
        }
        if(cr>0) return -1;
        return max;
    }
}
```

#### Language used for code

Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by Karandeep1234** [comment]
Thankyou for your reply @LC-Pam I have gone through the article. I have not used any global variables and neither compared any string using "==". But here in this test case ("croakc") the expected output is -1 and my code gives output 1 on "run code" which is clearly wrong output. My code is wrong and it was expected not to be accepted. On "Submit" the code is getting accepted. The addition of testcase "croakc" would prevent this wrong code from being accepted.
