### ISSUE TITLE
English grammer issues - 648. Replace Words

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#798]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

648. Replace Words
https://leetcode.com/problems/replace-words/

Please change as below:

1
If a successor has many roots can form it,
should be
If a successor has many roots can form,

2
1 <= sentence words number <= 1000
should be
1 <= sentence word count <= 1000

3
1 <= sentence words length <= 1000
should be
1 <= sentence word length <= 1000

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

The problem statement should be clear & unambiguous.
User should not read multiple times to understand the English.

Please do the below:
1. No grammer issues. Please see problem description above.
2. Have a proof reader for the English.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 20 LeetCoins as the reward for this feedback. We appreciate your support!
