### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes  ( time= 2*O(NM) , space=O(1) )

### ISSUE THREAD

**Issue by AbhishekRanjan624** [LeetCode-Feedback/LeetCode-Feedback#7981]
class Solution {
    public void setZeroes(int[][] matrix) {
        int m=matrix.length ;
        int n=matrix[0].length ;
        
        boolean row=false , col = false ;
        
        for(int i=0 ; i<m ; i++){   // if first col contains zero then make col true 
            if(matrix[i][0]==0){
                col=true ;
            }
        }
        
        for(int j=0 ; j<n ; j++){    // if first row contains zero then make row true 
            if(matrix[0][j]==0){
                row=true ;
            }
        }
         
        
        for(int i=1 ; i<m ; i++){      // start checking from index(1,1) if contains zero then two     
            for(int j=1 ; j<n ; j++){                //   zero in row and column both 
                if(matrix[i][j]==0){ 
                    matrix[i][0]=0 ;
                    matrix[0][j]=0 ;
                }
            }
        }
        
        for(int i=1 ; i<m ; i++){         // if row contains zero then make  all col zero    
            if(matrix[i][0]==0){
                for(int j=0 ; j<n ; j++){
                    matrix[i][j]=0 ;
                }
            }
        }
        
        for(int j=1 ; j<n ; j++){          // if col contains zero then make all row zero  
            if(matrix[0][j]==0){
                for(int i=0 ; i<m ; i++){
                    matrix[i][j]=0 ;
                }
            }
        }
        
        
        // checking if first (row=true) then means (contains zero ) making all row  zero 
        
       if(row){
           for(int j=0 ; j<n ; j++){
               matrix[0][j]=0 ;
           }
       }       
        
                       
        if(col){  // checking if first (col=true) then means (contains zero ) making all col  zero 
           for(int i=0 ; i<m ; i++){
               matrix[i][0]=0 ;
           }
       }
    }
}

// Time Complexity: O(2*(N*M)), as we are traversing two times in a matrix,

// Space Complexity: O(1).

**Comment by AbhishekRanjan624** [comment]
leetcode-73

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
What is the missing test case?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
