### ISSUE TITLE
Leetcode test case bug

### ISSUE THREAD

**Issue by maverickreal** [LeetCode-Feedback/LeetCode-Feedback#7982]
question link : https://leetcode.com/problems/verbal-arithmetic-puzzle/
The description of the third example test case is as follows: Input: words = ["LEET","CODE"], result = "POINT"
Output: false
The given output and Leetcode compiler judge result are wrong, as it should be true
Explanation:
Put L=9
      C=1
      P=1
      And the rest of all the characters to be = 0
Thus LEET becomes 9000, CODE becomes 1000, and POINT becomes 10000.
The equation LEET + CODE = POINT holds. Therefore the answer to the problem must be true.
My leetcode account: https://leetcode.com/maverick09/
Hence proved.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem,Added explanation to example 3. We appreciate your support!

**Comment by maverickreal** [comment]
I haven't yet been rewarded leetcoins. My leetcode handle: https://leetcode.com/maverick09/
