### ISSUE TITLE
Submitting the code gives wrong answer for the input "cbbd" but when we custom test it it gives correct answer

### ISSUE THREAD

**Issue by kapil4457** [LeetCode-Feedback/LeetCode-Feedback#7983]
#### Category of the bug
- [ ] Question
- [1] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I submit my code it gives wrong answer but when i custom run with that test case i get correct answer.

#### Code you used for Submit/Run operation

Link : https://leetcode.com/problems/longest-palindromic-substring/submissions/

```
class Solution {
public:
    
    bool isPalindrome(string s , int start , int end){
        while (start < end)
    {
        if (s[start] == s[end])
        {
            start++;
            end--;
        }
        else
        {
            return false;
        }
    }

    return true;
    }
    string longestPalindrome(string s) {
       static string ans = "";
    int start = 0;
    int end = s.length() - 1;

    if (start > end)
    {
        return "";
    }

    if (isPalindrome(s, start, end))
    {
        if (s.length() > ans.length())
        {
            ans = s;
        }
    }
    longestPalindrome(s.substr(start, end));
    longestPalindrome(s.substr(start + 1, end));

   
    return ans;
    }
};
```

#### Screenshots

![Capture](https://user-images.githubusercontent.com/78656206/176945050-66cdc5ca-1176-47ee-9787-29ee7dab2cce.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
