### ISSUE TITLE
题解存在问题，说明缺少测试用例；

### ISSUE THREAD

**Issue by hitwh-cgl** [LeetCode-Feedback/LeetCode-Feedback#7984]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
cgl
suspicious-clarkedp6

**Bug 类型**
- [ ] 题解
- [ ] 缺少测试用例

**描述**
题解给出的动态规划解法存在问题，使用int[] 数组存在数组溢出的可能，但是目前提交是可以通过的；
说明缺少测试用例，建议添加测试用例或者修改题目数据范围；

**你使用的语言**
java

**你提交或者运行的代码**
地址：https://leetcode.cn/submissions/detail/331631356/

**期望行为**
题解给出的动态规划解法存在问题，使用int[] 数组存在数组溢出的可能，但是目前提交是可以通过的；
说明缺少测试用例，建议添加测试用例或者修改题目数据范围；

**屏幕截图**
部分测试用例下题解的代码会出现int溢出，
可以参考提交记录：https://leetcode.cn/submissions/detail/331631356/

**额外的上下文**
可以参考修改成long的提交记录：https://leetcode.cn/submissions/detail/331641275/

**Comment by stormsunshine** [comment]
既然你的前一个提交（没有使用 long）已经显示错误，为什么认为缺少测试用例？只有提交通过的代码对于特定的测试用例结果错误，才能说明缺少测试用例，提交不通过的代码凭什么作为缺少测试用例的依据？缺少的测试用例是哪个？

你说的题解是不是官方题解？官方题解用的是 long，哪里有问题？为何要如此恶意诋毁官方题解？

**Comment by hitwh-cgl** [comment]
> 既然你的前一个提交（没有使用 long）已经显示错误，为什么认为缺少测试用例？只有提交通过的代码对于特定的测试用例结果错误，才能说明缺少测试用例，提交不通过的代码凭什么作为缺少测试用例的依据？缺少的测试用例是哪个？
> 
> 你说的题解是不是官方题解？官方题解用的是 long，哪里有问题？为何要如此恶意诋毁官方题解？

对不起，这是我的问题，我没有仔细审视题解，提交了错误的issue，浪费和占用你们的时间了，抱歉；

如果我想诋毁，我可能更愿意在题解评论区下面喷，而不是给你们提issue，我之前也提交过一个issue并且被采纳了，我认为我的心态更多是希望你们做得更好，而不是诋毁你们；
PS：我上次提的issue地址是：https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/7593；

再次致歉，但是因为我不怎么玩GitHub，不知道怎么关闭这个issue，但是我看到上次应该也是管理员自己关的，我想你们应该是有权限关闭的；
