### ISSUE TITLE
The Compiler is not giving correct answer when submitting but giving correct answer when run custom test case

### ISSUE THREAD

**Issue by kapil4457** [LeetCode-Feedback/LeetCode-Feedback#7985]
#### Category of the bug
- [ ] Question
- Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Compiler is not giving correct answer when submitting but giving correct answer when run custom test case. I tried running the same code on programmiz (another online compiler) and was getting the correct answer but not on leetcode.

#### Code you used for Submit/Run operation

Link : https://leetcode.com/problems/symmetric-tree/

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
    
public:
    
    vector<int> inOrder(TreeNode *root)
    {
        if(root==NULL){
            return {};
        }
        static vector<int>ans ;
        inOrder(root->left);
        ans.push_back(root->val);
        inOrder(root->right);
        
        return ans;
    }
    bool isSymmetric(TreeNode* root) {
        vector<int>ans = inOrder(root);
        for(int i = 0 ; i <  ans.size() ; i++){
            cout<<ans[i]<<" ";
        }
        
        int start = 0;
        int end  = ans.size()-1;
        while(start<end){
            if(ans[start]==ans[end]){
                start++;
                end--;
            }
            else{
                return false;
            }
        }
        
        return true;
    }
};
```

#### Language used for code

C++

#### Screenshots

![Capture2A](https://user-images.githubusercontent.com/78656206/176988911-31f64956-a94b-4c7b-91e5-1c94e8c06ad7.PNG)
![Capture2B](https://user-images.githubusercontent.com/78656206/176988913-8a3ff087-3f4c-4e37-9d0d-5293dde4efef.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
