### ISSUE TITLE
10.01. 合并排序的数组   数组A中的元素0表示的是空还是有效的元素0？

### ISSUE THREAD

**Issue by kinceeR** [LeetCode-Feedback/LeetCode-Feedback#799]
** Bug 类型**
- [ ] 题目   **10.01. 合并排序的数组**

给定两个排序后的数组 A 和 B，其中 A 的末端有足够的缓冲空间容纳 B。 编写一个方法，将 B 合并入 A 并排序。

初始化 A 和 B 的元素数量分别为 m 和 n。

示例:

输入:
A = [1,2,3,0,0,0], m = 3
B = [2,5,6],       n = 3

输出: [1,2,2,3,5,6]
说明:

A.length == n + m
通过次数30,375提交次数56,142
- [ ] 题解  
- [ ] 编程语言  **kotlin**

**描述**
这个题貌似有问题啊： case 1： 输入： [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] 0 [-50,-50,-48,-47,-44,-44,-37,-35,-35,-32,-32,-31,-29,-29,-28,-26,-24,-23,-23,-21,-20,-19,-17,-15,-14,-12,-12,-11,-10,-9,-8,-5,-2,-2,1,1,3,4,4,7,7,7,9,10,11,12,14,16,17,18,21,21,24,31,33,34,35,36,41,41,46,48,48] 63 输出： [-50,-48,-47,-44,-44,-37,-35,-35,-32,-32,-31,-29,-29,-28,-26,-24,-23,-23,-21,-20,-19,-17,-15,-14,-12,-12,-11,-10,-9,-8,-5,-2,-2,0,1,1,3,4,4,7,7,7,9,10,11,12,14,16,17,18,21,21,24,31,33,34,35,36,41,41,46,48,48] 预期： [-50,-50,-48,-47,-44,-44,-37,-35,-35,-32,-32,-31,-29,-29,-28,-26,-24,-23,-23,-21,-20,-19,-17,-15,-14,-12,-12,-11,-10,-9,-8,-5,-2,-2,1,1,3,4,4,7,7,7,9,10,11,12,14,16,17,18,21,21,24,31,33,34,35,36,41,41,46,48,48]

这个case 1就是表示0是无效数字 case 2 输入： [0,0,3,0,0,0,0,0,0] 3 [-1,1,1,1,2,3] 6 输出： [0,0,-1,1,1,1,2,3,3] 预期结果： [-1,0,0,1,1,1,2,3,3]

这个case 2 就表示0是有效的。

那我到底将A[]中当做空元素还是有效的？？？

**你使用的语言**
kotlin

**你提交或者运行的代码**
```
class Solution {
    private var ida=0
    private var idb=0
    fun merge(A: IntArray, m: Int, B: IntArray, n: Int): Unit {
        var end=A.size-1;
        ida=m-1;
        idb=n-1;
        while(end>=0&&idb>=0){
            if(ida<=0) {
                ida=0
            }
            A[end]=let {
                var max=0
                if (A[ida]>=B[idb]){
                    max=A[ida]
                    A[ida]=B[0]
                    if (ida>0) ida--
                }else{
                    max=B[idb]
                    idb--
                }
                max
            }
            end--;
        }


    }

}

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，请仔细阅读理解题目意思。特别是这两句：1）A 的末端有足够的缓冲空间容纳 B。2）初始化 A 和 B 的元素数量分别为 m 和 n。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路。

**Comment by kinceeR** [comment]
get



---原始邮件---
发件人: "feiceh"<notifications@github.com&gt;
发送时间: 2020年8月13日(周四) 下午5:51
收件人: "LeetCode-Feedback/LeetCode-Feedback"<LeetCode-Feedback@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"kinceeR"<316551422@qq.com&gt;;
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 10.01. 合并排序的数组   数组A中的元素0表示的是空还是有效的元素0？ (#799)




 
你好，该题目技术验证没有问题的，请仔细阅读理解题目意思。特别是这两句：1）A 的末端有足够的缓冲空间容纳 B。2）初始化 A 和 B 的元素数量分别为 m 和 n。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路。
