### ISSUE TITLE
16. 3Sum Closest | Python best possible solution giving TLE

### ISSUE THREAD

**Issue by Surajajaydwivedi** [LeetCode-Feedback/LeetCode-Feedback#7990]
#### Your LeetCode username
surajajaydwivedi

#### Category of the bug

- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases

#### Description of the bug

The new test cases added in past month for the question **16. 3Sum Closest** are poor. They give TLE for python for the best possible solutions as well. The test cases needs to be reduced because TLE is not due to bad coding but rather time used for interpreting Python.

#### Code you used for Submit/Run operation

```
// 3Sum Closest
class Solution:
    def threeSumClosest(self, nums: List[int], k: int) -> int:
        ans=float('inf')
        nums.sort()
        a2=0
        for i in range(len(nums)):
            l=i+1
            r=len(nums)-1
            while l<r:
                x=nums[i]+nums[l]+nums[r]
                z=abs(k-x)
                if z<ans:
                    ans=z
                    a2=x
                if x<k:
                    l+=1
                else:
                    r-=1
        return a2
```

#### Language used for code

Python

#### Expected behavior

The code should get accepted, well within time limits as the code is O(n^2) and constraints are 1<=n<=1000.

#### Screenshots

![image](https://user-images.githubusercontent.com/66689016/177011739-18778679-3585-4d27-9224-17a1f9724f10.png)
The same solution was working before the new cases were added.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Reduced the total number of test cases. We appreciate your support!
