### ISSUE TITLE
15. 3Sum | Runtime Error

### ISSUE THREAD

**Issue by b-ponomarenko** [LeetCode-Feedback/LeetCode-Feedback#7991]
#### Your LeetCode username
b-ponomarenko

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
When I submit solution LeetCode throws runtime error which is not related with particular solution. It seems it is a problem of Node.js environment. I reproduced that case in browser and it works correct.

#### Code you used for Submit/Run operation

```js
const twoSum = (arr, target, s) => {
  let start = s;
  let end = arr.length - 1;
    const results = [];

  while (end > start) {
    const sum = arr[start] + arr[end];

    if (sum === target) {
      results.push([arr[start], arr[end]]);
        start++;
        continue;
    }

    if (sum > target) {
      end--;
      continue;
    }

    if (sum < target) {
      start++;
      continue;
    }
  }

  return results;
}

const uniq = (arr) => {
    const set = new Set();
    
    return arr.filter(x => {
       const xString = x.join('');
        
        if (set.has(xString)) {
            return false;
        }
        
        set.add(xString);
        return true;
    });
}

function threeSum(arr) {
    let result = [];

  arr = arr.sort((a, b) => a - b);

  for (let i = 0; i < arr.length - 1; i++) {
      const r = twoSum(arr, -arr[i], i + 1);
      
      if (r.length > 0) {
          r.forEach(pair => {
          result.push([arr[i], pair[0], pair[1]]); 
        })
      }
  }

  return uniq(result);
};
```

#### Language used for code
Javascript

#### Expected behavior
Expectaction and function's result the same.

#### Additional context
https://leetcode.com/submissions/detail/736889568/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. It seems the issue comes from the code, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
