### ISSUE TITLE
Palindromic Substrings - Error in description (under hints)

### ISSUE THREAD

**Issue by SA1CA1** [LeetCode-Feedback/LeetCode-Feedback#7992]
#### Your LeetCode username
saarangagarwal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is an error in the description- under Hint 2
It says, If “aba” is a palindrome, is “xabax” **and** palindrome? Similarly is “xabay” a palindrome?
But it should say If “aba” is a palindrome, is “xabax” **a** palindrome? Similarly is “xabay” a palindrome?
Notice the bolded "and" that has to be changed to "a"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/107086589/177018094-7793f05d-76c1-49e2-a749-c6fbbc158c64.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
