### ISSUE TITLE
376. Wiggle Subsequence | missing Testcase

### ISSUE THREAD

**Issue by MrMohamedAbdallah** [LeetCode-Feedback/LeetCode-Feedback#7994]
#### Your LeetCode username
user3899k

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
When the input is `[0]` or `[0,0,0,0]` the answer should be 0, however we are getting 1

#### Code you used for Submit/Run operation

```python
class Solution:
    def wiggleMaxLength(self, nums: List[int]) -> int:
        negative = 1
        positive = 1
        
        touched = False
        
        for i in range(1, len(nums)):
            n = nums[i] - nums[i - 1]
            
            if n == 0:
                continue
            
            touched = True
            
            if n > 0: positive = negative + 1
            elif n < 0: negative = positive + 1
        
        return max(negative, positive) if touched else 0
```

#### Language used for code
Python 3

#### Screenshots
The expected output should be `0` not `1`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
