### ISSUE TITLE
Missing Test Case - 962. Maximum Width Ramp

### ISSUE THREAD

**Issue by abdulmukit-n** [LeetCode-Feedback/LeetCode-Feedback#7995]
#### Category of the bug
- [ ] Question: 962. Maximum Width Ramp
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Example 2 in the question is wrong as the solution to the example question is stated to be the pair of (2,9) when the nums array does not contain a 2 in it .  nums array = [9,8,1,0,1,9,4,0,4,1]
Further more if you took (1,9) as in this case it would still not work as it only satisfies the condition that i < j not nums[i] <= nums[j] 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

java

**Comment by stormsunshine** [comment]
The pair (i, j) is **a pair of indices**. The array's length is 10, so it has an index 2.

Why do you think an index must be an element of an array?

**Comment by abdulmukit-n** [comment]
I have mis interpreted the question for i and j being values within the array rather the values at different index to give the highest possible width.
Thank you for clarifying that !
