### ISSUE TITLE
Missing Test Case - 376. Wiggle Subsequence

### ISSUE THREAD

**Issue by Ranvirsv** [LeetCode-Feedback/LeetCode-Feedback#7997]
#### Your LeetCode username

Ranvirsv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [0] Missing Test Cases 

#### Description of the bug

The question Wiggle Subsequence is missing the test case [0,0,0,0], where all the elements are 0.

#### Code you used for Submit/Run operation

```
// Wiggle Subsequence
class Solution {
    public int wiggleMaxLength(int[] nums) {
        if(nums.length == 0) return 0;
        
        int[] up = new int[nums.length];
        int[] down = new int[nums.length];
        
        up[0] = 1;
        down[0] = 1;
        
        for(int i = 1; i < nums.length; i++){
            up[i] = nums[i] > nums[i-1] ? down[i-1]+1 : up[i-1];
            down[i] = nums[i] < nums[i-1] ? up[i-1]+1 : down[i-1];
        }
        
        return Math.max(up[nums.length-1], down[nums.length-1]);
    }
}
```

#### Language used for code

Java

#### Expected behavior

In this case, the output should be 0, as 0 can not be considered positive, or negative, and is treated the same everywhere else.

**Comment by LC-Pam** [comment]
Thank you for your time. The test case already exist. We appreciate your support
![Screen Shot 2022-07-05 at 1 25 57 PM](https://user-images.githubusercontent.com/103138242/177383143-657f3d56-6849-4999-bdd2-d8a747338776.png)
!
