### ISSUE TITLE
1013 题答案有误

### ISSUE THREAD

**Issue by SleepyBag** [LeetCode-Feedback/LeetCode-Feedback#8]
** Bug 类型**
- [x] 题目
- [ ] 题解

**描述**
标准答案有误，对于输入 [1, -1, 1, -1]，答案应该为 false，但是标准程序给出的答案是 true，测试也没有考虑到这一情况。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
非常感谢您的反馈，该问题已于第一时间进行了修复，力扣会定期更新，保障稳定和体验优化。
