### ISSUE TITLE
English grammer issue & Broken weblink - 676 - Implement Magic Dictionary

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#800]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

676. Implement Magic Dictionary
https://leetcode.com/problems/implement-magic-dictionary/

1
Please change as below:

You may assume that all the inputs are consist of lowercase letters a-z.
should be
You may assume that all the inputs consist of lowercase letters a-z.

2
Please fix the weblink:

> Please see `here` for more details.

The `here` link in above text
goes to https://leetcode.com/faq/#different-output
but, this link does not exist

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

No English grammer issues. No broken web links. Please see issue description above.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 20 LeetCoins as the reward for this feedback. We appreciate your support!
