### ISSUE TITLE
Missing Test Case - 364. Nested List Weight Sum II

### ISSUE THREAD

**Issue by nightshadows** [LeetCode-Feedback/LeetCode-Feedback#8001]
#### Your LeetCode username
nightshadows

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Nothing in the description forbids empty lists. "Each element is either an integer or a list whose elements may also be integers or other lists." elements MAY be integers or other. The testing system correctly assumes that but fails to check the corner cases.
Example: [[1,1],2,[1,1],[[[[]]]]]
The answer should be 8, but the code below produces 20 while passing all the system test cases and being accepted as a result.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int depthSumInverse(vector<NestedInteger>& nestedList) {
        if (nestedList.size() == 0) {
            return 0;
        }
        int maxDepth = getDepth(nestedList);
        int res = 0;
        updateSum(nestedList, res, maxDepth);
        return res;
    }
    
private:
    int getDepth(vector<NestedInteger>& lst) {
        int maxDepth = 0;
        for (auto l : lst) {
            if (l.isInteger()) {
                maxDepth = max(maxDepth, 1);
            } else {
                maxDepth = max(maxDepth, getDepth(l.getList()) + 1);
            }
        }
        return maxDepth;
    }
    void updateSum(vector<NestedInteger>& lst, int& res, int coeff) {
        for (auto l : lst) {
            if (l.isInteger()) {
                res += l.getInteger() * coeff;
            } else {
                updateSum(l.getList(), res, coeff - 1);
            }      
        }
    }
};
```

#### Language used for code
C++

#### Expected behavior

[[1,1],2,[1,1],[[[[]]]]] should result in 8. It results in 20. The solution should be rejected but it is being accepted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
