### ISSUE TITLE
Question 26 - Racket version of problem is unsolvable

### ISSUE THREAD

**Issue by Skyb0rg007** [LeetCode-Feedback/LeetCode-Feedback#8003]
#### Category of the bug
- [X] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
Question 26 asks the programmer to modify an array in-place. However, the Racket function is passed an immutable linked list which cannot be modified.
Additionally, the infrastructure seems to incorrectly validate the function's result. Even if the implementation returns a number, the server responds with the error `0 is not a valid value for the expected return type integer[]`. Returning a list or vector do not alleviate this error.

#### Code you used for Submit/Run operation
```racket
(define (remove-duplicates nums)
   0)
```

Result:

```
0 is not valid value for the expected return type integer[]
  context...:
   /usr/share/racket/collects/racket/private/more-scheme.rkt:163:2: select-handler/no-breaks
   solution.rkt:9:2
   body of (submod "solution.rkt" main)
```

#### Language used for code
Racket

#### Expected behavior
The above code runs with no issues and results in an incorrect result.

#### Additional context
Possible solution to the error:

The result of the function seems to be improperly validated.

Possible solutions to the unsolvability:

1. The function could be given a [`vector`](https://docs.racket-lang.org/reference/vectors.html), rather than a `list`. This is Racket's version of a linear array.
2. The function could also be given an [`mlist`](https://docs.racket-lang.org/reference/mpairs.html), a mutable linked list.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by funk443** [comment]
The problem doesn't seem to be solved yet

**Comment by shawnw** [comment]
Whoever makes the question framework  Racket apparently isn't aware of scheme vectors. So many questions that are worded to take an array and need O(1) access to arbitrary elements get a list instead, not just this one. Very annoying.

**Comment by imakira** [comment]
Same as question [289](https://leetcode.com/problems/game-of-life/).

**Comment by imakira** [comment]
I found we can use [unsafe-set-immutable-car!](https://docs.racket-lang.org/reference/unsafe.html#%28def._%28%28lib._racket%2Funsafe%2Fops..rkt%29._unsafe-set-immutable-car%21%29%29) and [unsafe-set-immutable-cdr!](https://docs.racket-lang.org/reference/unsafe.html#%28def._%28%28lib._racket%2Funsafe%2Fops..rkt%29._unsafe-set-immutable-cdr%21%29%29).

**Comment by LC-Pam** [comment]
Thank you for your time.

Racket doesn't support any questions that require in-place modification. We removed racket from the question.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by shawnw** [comment]
> Racket doesn't support any questions that require in-place modification. We removed racket from the question.

Sure it does. As already brought up in earlier comments, it should be using a vector, not a list. There are many leetcode questions that should be using vectors instead; they get arrays in other languages; why is Racket being treated differently?
