### ISSUE TITLE
Expolore Card 'Trie' doesn't have Python3 example

### ISSUE THREAD

**Issue by davidseungjin** [LeetCode-Feedback/LeetCode-Feedback#8004]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In explore card 'Trie',  No Python3 example is provided
[https://leetcode.com/explore/learn/card/trie/147/basic-operations/1048/](https://leetcode.com/explore/learn/card/trie/147/basic-operations/1048/)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team, but it will take times to fix it. We appreciate your support!
