### ISSUE TITLE
Missing Test Case - 747. Largest Number At Least Twice of Others

### ISSUE THREAD

**Issue by ssmm26** [LeetCode-Feedback/LeetCode-Feedback#8005]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

test case [0] should be added because it prevents solutions such as below from being accepted. The code below should not be accepted because it fails on the test_case= [0] but it's currently accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def dominantIndex(self, nums: List[int]) -> int:
        result = -1
        a, b = 0, 0
        for i, n in enumerate(nums):
            if n > a:
                a, b = n, a
                result = i
            elif n > b:
                b = n
        return result if a and a >= 2*b else -1
```

#### Language used for code

Python 3

#### Expected behavior

Above code should fail

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Changed the constraints and this test case is now invalid, did not add it. We appreciate your support!
