### ISSUE TITLE
Missing Test Case - 376. Wiggle Subsequence

### ISSUE THREAD

**Issue by micakmi** [LeetCode-Feedback/LeetCode-Feedback#8007]
#### Your LeetCode username
Micakovic

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X ] Missing Test Cases 

#### Description of the bug
There is no valid test case with two different numbers in the list. If you return wiggle size 1 when vector has two elements without checking elements code will pass. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int wiggleMaxLength(vector<int>& nums) {
        if (nums.size() == 1)
        {
            return 1;
        }
        else if (nums.size() == 2)
        {
            return 1;
        }
        
        int  res = 2;
        bool isPrevPos;
        int  ix, n = nums.size();

        for (ix = 1; ix < n and nums[ix] == nums[ix - 1]; ix++);
        if (ix == n)
        {
            return 1;
        }

        isPrevPos = (nums[ix] - nums[ix - 1]) > 0;
        for (ix = ix + 1; ix < n; ix++)
        {
            if (nums[ix] == nums[ix - 1])
            {
                continue;
            }
            if ((nums[ix] - nums[ix - 1] > 0) != isPrevPos)
            {
                res++;
                isPrevPos = !isPrevPos;
            }            
        }
        
        return res;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
 Submitted code should fail since for vector<int> vec = { 1, 5 } correct wiggle length should be 2, not 1.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
