### ISSUE TITLE
Wrong Hide Hint - 1092. Shortest Common Supersequence

### ISSUE THREAD

**Issue by a-lbertlin** [LeetCode-Feedback/LeetCode-Feedback#8008]
#### Your LeetCode username

albert-lin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Wrong description in Hide Hint 1. The sentence "recover the longest common supersequence" should be "recover the shortest common supersequence".

Wrong Sentence:
    We can use this information to recover the longest common supersequence.
Correct Sentence:
    We can use this information to recover the shortest common supersequence.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by a-lbertlin** [comment]
Welcome. It's my pleasure to help LeetCode to correct it.
