### ISSUE TITLE
建议新增测试用例 215.数组中的第K个最大元素

### ISSUE THREAD

**Issue by syt2** [LeetCode-Feedback/LeetCode-Feedback#8009]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
建议新增朴素分治方法某些情况下最坏的case，如`[x, x, x, ..., x](重复10e4次)`
目前朴素分治法所有test case测试耗时0-4ms
一次`[x, x, x, ..., x](重复10e4次)` case的测试耗时100ms+

**Comment by BrambleWave** [comment]
您好，您未按格式填写
