### ISSUE TITLE
Missing Test Case - LCOF 61. 扑克牌中的顺子

### ISSUE THREAD

**Issue by zkylearner** [LeetCode-Feedback/LeetCode-Feedback#8010]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
补充 [0, 0, 1, 4, 6]

**你使用的语言**
javascript

**你提交或者运行的代码**
```
var isStraight = function (nums) {
  let jocker = 0
  let pre = 0
  nums.sort((a, b) => a - b)
  let l = 0
  while (nums[l] === 0) {
    l++
    jocker++
  }
  for (let i = l; i < nums.length; i++) {
    const val = nums[i]
    const pre = nums[i - 1]
    if (i === l) {
      continue
    }
    if (val - pre === 1) {
      continue
    }
    if (val === pre) return false
    if (jocker > 0 && val - pre <= jocker + 1) {
      jocker--
      continue
    }
    return false
  }
  return true
};
```

**期望行为**
关于鬼牌的判断有遗漏，相关测试用例不足。导致上述代码可以通过

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。
