### ISSUE TITLE
Missing Test Case - 1752. Check if Array Is Sorted and Rotated

### ISSUE THREAD

**Issue by arifk2** [LeetCode-Feedback/LeetCode-Feedback#8011]
#### Missing test case
- [ ] Question
- [ ] Solution
- [ ] Language
- [ * ] Missing Test Cases 

#### Description of the bug

important Test case is missing for the java code input [1,1,1,1]

#### Code you used for Submit/Run operation

```
//  1752. Check if Array is Sorted and Rotated
class Solution {
    public static boolean check(int[] nums) {
		int count = 0;
		int n = nums.length;
		for (int i = 1; i < n; i++) {
			if (nums[i - 1] > nums[i]) {
				count++;
			}
		}
		if (nums[n - 1] > nums[0]) {
			count++;
		}

		if (count <= 1) {
			return true;
		}
		return false;
	}
}
```

**Comment by LC-Pam** [comment]
Thank you for your time. The test case already exist. We appreciate your support
![Screen Shot 2022-07-05 at 1 49 01 PM](https://user-images.githubusercontent.com/103138242/177386485-21cc6e94-f060-445e-810b-de425d0e672a.png)
!
