### ISSUE TITLE
1200.最小绝对差 题目描述不清

### ISSUE THREAD

**Issue by loyio** [LeetCode-Feedback/LeetCode-Feedback#8015]
**你的 LeetCode 用户名**
loyios

**Bug 类型**
- [x] 题目

**描述**
题干内容相比于国际站缺少很多关键信息，可能对一些用户不太友好。示例也未对输出进行解释。

**屏幕截图**
<img width="455" alt="CleanShot 2022-07-04 at 21 31 13@2x" src="https://user-images.githubusercontent.com/32695256/177165194-b2231512-8057-4dfc-b34b-3a75e522cc06.png">
<img width="398" alt="CleanShot 2022-07-04 at 21 20 56@2x" src="https://user-images.githubusercontent.com/32695256/177164961-9ae36d56-c86d-4029-8d09-f3af514b47d4.png">

**Comment by BrambleWave** [comment]
1. 感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by BrambleWave** [comment]
2. 你好，当前题目描述已更新，ID：loyios  给予积分奖励，请查收。
