### ISSUE TITLE
Description is incorrect - 692. Top K Frequent Words

### ISSUE THREAD

**Issue by FireSlayer57** [LeetCode-Feedback/LeetCode-Feedback#8016]
#### Your LeetCode username
masteralphi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
We need to change 1 <= words[i] <= 10 to 1 <= words[i].length <= 10

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
