### ISSUE TITLE
937. Reorder Data in Log Files - Wrong Time Complexity Mentioned in The Solution.

### ISSUE THREAD

**Issue by abhinavsharma629** [LeetCode-Feedback/LeetCode-Feedback#802]
#### Your LeetCode username

abhinavsharma629

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

For using the **custom sorting Comparator** for any language, we first need to find the index of the first occurrence of "a space"(or **split the string**), and the **time complexity of this overhead is O(k), where k is the length of the string**.

This **operation takes place A times**, whenever we compare 2 strings, so the total complexity happens to be **A*k log(A)** _( more specifically A*(2*k) log(A) (as we need to split both comparing strings on the basis of spaces)_

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public String[] reorderLogFiles(String[] logs) {
        Arrays.sort(logs, (log1, log2) -> {
            String[] split1 = log1.split(" ", 2);
            String[] split2 = log2.split(" ", 2);
            boolean isDigit1 = Character.isDigit(split1[1].charAt(0));
            boolean isDigit2 = Character.isDigit(split2[1].charAt(0));
            if (!isDigit1 && !isDigit2) {
                int cmp = split1[1].compareTo(split2[1]);
                if (cmp != 0) return cmp;
                return split1[0].compareTo(split2[0]);
            }
            return isDigit1 ? (isDigit2 ? 0 : 1) : -1;
        });
        return logs;
    }
};
```

#### Language used for code

Java

#### Expected behavior

Currently in the given solution, for using the **custom sorting Comparator** for any language, we first need to find the index of the first occurrence of "a space"(or **split the string**)**.
This **operation takes place A times**, whenever we compare 2 strings, so the total complexity happens to be **A log(A)**.

**Comment by lc-ivan** [comment]
Hi @abhinavsharma629 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hello @abhinavsharma629 ,
Thanks for your feedback regarding this problem! Upon review, our team has concluding that this solution article for this problem will be rewritten soon. The team also mentioned that this is a known issue for this specific article so there will be no LeetCoins rewarded for this ticket. Thank you once again and Happy LeetCoding!
