### ISSUE TITLE
Missing Test Case - 1342. Number of Steps to Reduce a Number to Zero

### ISSUE THREAD

**Issue by Whiteclown** [LeetCode-Feedback/LeetCode-Feedback#8024]
#### Your LeetCode username
whitegat

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
If I try to run it with "Run code" everything will be okay, but if I submit it, i'll get wrong answer for the same test case

#### Code you used for Submit/Run operation

```
// Number of Steps to Reduce a Number to Zero
class Solution {
    fun numberOfSteps(num: Int): Int {
        return when {
            num == 0 -> Counter.value

            num % 2 == 0 -> {
                Counter.value++
                numberOfSteps(num / 2)
            }

            else -> {
                Counter.value++
                numberOfSteps(num - 1)
            }
        }
    }

    object Counter {
        var value = 0
    }
}
```

#### Language used for code
Kotlin

#### Screenshots
![image](https://user-images.githubusercontent.com/59654044/177287444-b4404b67-9bca-461a-973f-2bf2b07640f0.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
