### ISSUE TITLE
Problem Title Needs to Be Changed - 561. Array Partition I

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8026]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [561. Array Partition I](https://leetcode.com/problems/array-partition-i), the title ends with "I", which indicates that it is one of the problems in a series. However, there is no problem with title "Array Partition II".

Therefore, this problem's title should be changed to "Array Partition" for simplicity, and the problem's link should be changed accordingly.

#### Expected behavior
The title of problem 561 should be changed to "Array Partition" for simplicity, and the problem's link should be changed accordingly.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
