### ISSUE TITLE
我的代码能过官评 但是会被一个测试用例hack

### ISSUE THREAD

**Issue by 154775258** [LeetCode-Feedback/LeetCode-Feedback#8027]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
东方

**Bug 类型**
- [x] 缺少测试用例

**描述**
[面试题 04.10. 检查子树](https://leetcode.cn/problems/check-subtree-lcci/)
下述用例可以卡掉我的代码
但我的代码能通过官方评测 
[4,2,3,4,5,6,7,8,9]
[4,8,9]

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:

    bool OK(TreeNode* t1,TreeNode* t2){
        if(!t1 && !t2)return 1;
        if(!t1 || !t2)return 0;
        if(t1->val != t2 -> val)return 0;
        return OK(t1->left,t2->left) && OK(t1->right,t2->right);
    }

    bool checkSubTree(TreeNode* t1, TreeNode* t2) {
        if(!t1)return 0;
        if(t1 -> val == t2 -> val)return OK(t1,t2);
        return checkSubTree(t1 -> left,t2) || checkSubTree(t1 -> right,t2);
    }
};
```

**期望行为**
增加用例

- [x] **屏幕截图**
![image](https://user-images.githubusercontent.com/106418034/177370044-257f9619-9f42-4e71-9d53-bec72d6e3284.png)

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
你好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的 ID，我们给予积分奖励哦。
