### ISSUE TITLE
1147. Longest Chunked Palindrome Decomposition      mistake in explanation of example testcase

### ISSUE THREAD

**Issue by mihirchawla14** [LeetCode-Feedback/LeetCode-Feedback#8031]
#### Your LeetCode username

chawlamihir1410

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

1147. Longest Chunked Palindrome Decomposition
Mistake in explanation of second example testcase

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestDecomposition(string text) {
        int sizee = text.size();
        
        unordered_map<char,vector<int>> mapp;
        
        for(int a=0; a<sizee; a++) mapp[text[a]].push_back(a);
        
        int start = 0;
        int end = sizee-1;
        
        int ans=0;
        
        while(start<=end){
            if(start==end) return ans+1;
            if(text[start]==text[end]){
                start++;
                end--;
                ans+=2;
                continue;
            }
            char temp = text[end];
            if(mapp[temp].size()<=1)   return ans+1;
            
            int a;
            for(a=0; a<mapp[temp].size(); a++){
                if(mapp[temp][a]>start && mapp[temp][a]<end){
                    int len = mapp[temp][a]-start;
                    if(end-len<mapp[temp][a])  return ans+1;  
                    
                    else if(text[end-len]!=text[start]) continue;
                    else if(text.substr(start, len+1)!=text.substr(end-len, len+1)) continue;
                    else{
                        ans+=2;
                        start+=(len+1);
                        end-=(len+1);
                        break;
                    }
                    if(a==mapp[temp].size()-1) return ans+1;
                }
            }
            if(a==mapp[temp].size()) return ans+1;
        }
        return ans;
    }
};
```

#### Expected behavior

When    Input is      : text = "antaprezatepzapreanta"
Explanation is    : We can split the string on "(a)(nt)(a)(pre)(za)(tpe)(za)(pre)(a)(nt)(a)".
But it should be    : We can split the string on "(a)(nt)(a)(pre)(za)(tep)(za)(pre)(a)(nt)(a)".

There should be tep instead of tpe

#### Screenshots

![image](https://user-images.githubusercontent.com/108764347/177412229-2a204ce9-2f02-4ba8-8de7-3f54ab415de9.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
