### ISSUE TITLE
Missing Test Case - 128. Longest Consecutive Sequence

### ISSUE THREAD

**Issue by venkatakm1** [LeetCode-Feedback/LeetCode-Feedback#8037]
#### Your LeetCode username

venkatakm

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

The following code described below got accepted, but the test case [-1000000000,1,2,3,9,1000000000] is timing out. This is a test case gap.

#### Code you used for Submit/Run operation

```
class Solution {
    public int longestConsecutive(int[] nums) {
        Set<Integer> set = new HashSet<>();
        int min = Integer.MAX_VALUE;
        int max = Integer.MIN_VALUE;
        
        for(int num:nums){
            set.add(num);
            min = Math.min(min,num);
            max = Math.max(max,num);
        }
        
        int result = 0;
        int tmpResult = 0;
        for(int i=min;i<=max;i++){
            if(set.contains(i)){
                tmpResult++;
                set.remove(i);
            }else{
                result = Math.max(result,tmpResult);
                tmpResult=0;
                if(set.size()<=result){
                    return result;
                }
            }
        }
        result = Math.max(result,tmpResult);
        return result;
    }
}
```

#### Expected behavior

When the range between minimum number and maximum number given in the input is large, the solution should not timeout. The code used above is getting accepted even though for input [-1000000000,1,2,3,9,1000000000] it is timing out.

**Comment by Devil200207** [comment]
your code is not working for this test case

 int longestConsecutive(vector<int>& nums) 
    {
        
        set<int>m;
        int n = nums.size();
        for(int i=0;i<n;i++)
        {
            m.insert(nums[i]);
        }
        
        int ans = 0;
        for(auto &x:m)
        {
           if(!(m.find(x-1) != m.end()))
           {
               int cnt=x+1;
               while((m.find(cnt) != m.end()))
               {
                   cnt++;
               }
               ans = max(ans,cnt-x);
           }
        }
        return ans;
    }

this code is working correct answer

**Comment by venkatakm1** [comment]
Sorry, I didn't understand. I was mainly reporting to add the
Testcase [-1000000000,1,2,3,1000000000] which is giving TLE for my java code

>>>
class Solution {
    public int longestConsecutive(int[] nums) {
        Set<Integer> set = new HashSet<>();
        int min = Integer.MAX_VALUE;
        int max = Integer.MIN_VALUE;

        for(int num:nums){
            set.add(num);
            min = Math.min(min,num);
            max = Math.max(max,num);
        }

        int result = 0;
        int tmpResult = 0;
        for(int i=min;i<=max;i++){
            if(set.contains(i)){
                tmpResult++;
                set.remove(i);
            }else{
                result = Math.max(result,tmpResult);
                tmpResult=0;
                if(set.size()<=result){
                    return result;
                }
            }
        }
        result = Math.max(result,tmpResult);
        return result;
    }
}
<<<

   The above solution got accepted though. So I would like to add the test
case [-1000000000,1,2,3,1000000000] for the problem.

Cheers,
Kishore

**Comment by venkatakm1** [comment]
I know that Dude. Thats what I am complaining about, why should this code
is accepted? The test case I mentioned is missing, that is what I am
planning to contribute. I don't know why it is so difficult to understand
that I am contributing a test case not the code.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
