### ISSUE TITLE
Missing Test Case - 1862. Sum of Floored Pairs

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#8038]
#### Your LeetCode username

endlesscheng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code below should get TLE instead AC.

Please add this [1862_hack.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9050917/1862_hack.txt) test case.

#### Code you used for Submit/Run operation

```py
MOD = 10**9 + 7
class Solution:
    def sumOfFlooredPairs(self, nums: List[int]) -> int:
        mx = max(nums)
        count = [0] * (mx+1)
        for i in nums:
            count[i] += 1
        sum_arr = [0] *(mx+2)
        sum_arr[1] = count[0]
        for i in range(mx+1):
            sum_arr[i+1] = sum_arr[i] + count[i]
        
        ans = 0
        cur_sum = 0
        for i in range(len(nums)):
            if i > 0 and nums[i-1]== nums[i]:
                ans += cur_sum
            else:
                cur_sum = 0
                for j in range(nums[i],mx+2,nums[i]):
                    cur_sum += j//nums[i]*(sum_arr[min(j+nums[i],mx+1)]-sum_arr[j])
                ans += cur_sum
        return ans % MOD
```

#### Language used for code

Python3

#### Expected behavior

TLE

#### Additional context

[1862_hack.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9050917/1862_hack.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us. When we run the test case that you provided with your code, we received TLE. 
Please click Run Code. 

Best

**Comment by EndlessCheng** [comment]
I click `Run Code` and got AC: https://leetcode.com/submissions/detail/740466878/
