### ISSUE TITLE
Minor revision - There is a bug in the official solution of "197. Rising Temperature". 

### ISSUE THREAD

**Issue by ayiyi** [LeetCode-Feedback/LeetCode-Feedback#804]
#### Your LeetCode username
ayiff

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
[There is a bug in the official solution of "197. Rising Temperature".](https://leetcode-cn.com/problems/rising-temperature/solution/shang-sheng-de-wen-du-by-leetcode/)
Specifically, the column name date of the weather table in the solution is wrong and should be revised to RecordDate.

#### Code you used for Submit/Run operation
```
# Write your MySQL query statement below
SELECT weather.id AS 'Id'
FROM weather JOIN weather w 
ON DATEDIFF(weather.RecordDate, w.RecordDate) = 1 AND weather.Temperature > w.Temperature
;
```

#### Language used for code
SQL

#### Expected behavior
[Revise the official solution of "197. Rising Temperature".](https://leetcode-cn.com/problems/rising-temperature/solution/shang-sheng-de-wen-du-by-leetcode/)

**Comment by lc-pam** [comment]
Hi @ayiyi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @ayiyi 
Thank you for your time. The team has reviewed your report but considered it invalid. You were using the wrong column name, you should use recordDate, not date. We appreciate your support!
