### ISSUE TITLE
Missing Test Case - 376. Wiggle Subsequence

### ISSUE THREAD

**Issue by mandepsingh** [LeetCode-Feedback/LeetCode-Feedback#8040]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Issue with this problem is that the resulting system skips one or more similar digits for the result.
If 2 or more digits are the same from the start of the array or from the end then these digits are not considered to be a wiggly sequence.

Ex: [138,504,401,526,513,566,377,132,257,45,167,549,461,425,127,120,39,165,239,181,583,444,180,61,543,179,355,52,495,304,312,247,575,236,546,527,10,504,424,587,128,473,61,11,38,28,599,73,387,447,75,300,300,300]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int f(int i,int positive,vector<int>& nums,vector<vector<int>> &dp)
    {
        if(i==0) return 1;
        if(dp[i][positive]!=-1) return dp[i][positive];
        
        int not_pick=f(i-1,positive,nums,dp);
        int pick=-1e9;
        if(nums[i]-nums[i-1]>0 && positive ||nums[i]-nums[i-1]<0 && !positive)
        {
            pick=1+f(i-1,!positive,nums,dp);
        }
        return dp[i][positive]= max(pick,not_pick);
    }
    int wiggleMaxLength(vector<int>& nums) {
        int n = nums.size();
        if(n==1) return 1;
        vector<vector<int>> dp(n,vector<int>(2,-1));
        return (nums[n-1]-nums[n-2]>0)?f(n-1,1,nums,dp):f(n-1,0,nums,dp);
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
This solution has to be failed because the output is 39, but the expected output is 40

#### Screenshots
 
![Screenshot (116)](https://user-images.githubusercontent.com/39272041/177465780-3b257fa0-0821-465b-9c2d-7f6291d8c2e3.png)

#### Additional context
There are more similar test cases that would be skipped if there is more than 1 same elements in sequence.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by LC-Pam** [comment]
Would you mind sending us your username?

**Comment by mandepsingh** [comment]
hapysingh
https://leetcode.com/hapysingh/

**Comment by LC-Pam** [comment]
Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
