### ISSUE TITLE
我按照解释的逻辑相加，为什么判我不对

### ISSUE THREAD

**Issue by wxcxh** [LeetCode-Feedback/LeetCode-Feedback#8041]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
var addTwoNumbers = function(l1, l2) {
    let num=l1.reverse().join('')*1+l2.reverse().join('')*1
    num=num.toFixed(0).split('')
    let arr=[]
    for(let i=0;i<num.length;i++){
        arr.unshift(parseInt(num[i]))
    }
    return arr
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![Uploading image.png…]()

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
建议他尝试一下官方题解的代码，或者使用调试器查bug
