### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by vjcoder20** [LeetCode-Feedback/LeetCode-Feedback#8043]
#### Your LeetCode username
 vaibh_20 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
 My code has been accepted but there is one test case i.e. [[2147483646],[2],[3]]
 where it should fail and give the wrong answer. So, please add this test case as well.

#### Code you used for Submit/Run operation

```
class Solution {
    public void setZeroes(int[][] matrix) {
        
        for(int i=0;i<matrix.length;i++){
            for(int j=0;j<matrix[0].length;j++){
               if(matrix[i][j]==0){
                   
                   //row mein max dalo
                   
                   for(int k=0;k<matrix[0].length;k++){
                       if(matrix[i][k]!=0)
                           matrix[i][k] = Integer.MAX_VALUE-1;
                   }
                   
                   
                   //column mein max dalo
                   
                   for(int l=0;l<matrix.length;l++){
                        if(matrix[l][j]!=0)
                           matrix[l][j] = Integer.MAX_VALUE-1;
                   }    
                   
               } 
            }
        }
        
         for(int i=0;i<matrix.length;i++){
            for(int j=0;j<matrix[0].length;j++){
                if(matrix[i][j]==Integer.MAX_VALUE-1)
                   matrix[i][j] = 0;
            }
         }
        
    }
}
```

#### Language used for code
Java 

#### Expected behavior
It should give the wrong answer on the above test case as discussed. So please add this test case

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. After investigated,We decided not to add this test case because there are many similar cases. We appreciate your support!
