### ISSUE TITLE
Missing Test Case - 1262. Greatest Sum Divisible by Three

### ISSUE THREAD

**Issue by Anutosh0804** [LeetCode-Feedback/LeetCode-Feedback#8044]
#### Your LeetCode username

Anutosh_0804

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

#### Description of the bug

My code has been accepted but there is one test case i.e. [1,1,3]
where it should fail and give the wrong answer. So, please add this test case as well.

#### Code you used for Submit/Run operation

```
// Greatest Sum Divisible by Three
class Solution {
public:
    int maxSumDivThree(vector<int>& nums) {
        int ans=0;
        for(int i=0;i<nums.size();i++)
            ans+=nums[i];
        if(ans%3==0)
            return ans;
        sort(nums.begin(),nums.end());
        int x=ans%3;
        int y=2;
        if(x==2)
            y=1;
        int diff_1=0;
        int diff_2=0;
        int count=0;
        bool flag=true;
        for(int i=0;i<nums.size();i++)
        {
            if(nums[i]%3==y && count<2)
            {
                diff_2+=nums[i];
                count++;
            }
            if(nums[i]%3==x && flag)
            {
                diff_1=nums[i];
                flag=false;
            }
        }
        if(count!=2)
            diff_2=INT_MAX;
        
        return max(ans-diff_1,ans-diff_2);
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should give the wrong answer on the above test case as discussed. So please add this test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/61666031/177496348-9fd32145-26a4-40ea-a77c-9f7ccf037211.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
