### ISSUE TITLE
Missing Test Case - 6. Zigzag Conversion

### ISSUE THREAD

**Issue by Jihane-bnhd** [LeetCode-Feedback/LeetCode-Feedback#8047]
#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
char * convert(char * s, int numRows){
      char *word;
    
    int cpt_col = 0;;
    int cpt_row = 0;
    int fill_all= numRows-1;
    int avance = 0;
    int num = numRows-1;
    int column = strlen(s)*20000;
    char zigzag[numRows][column];
    word=(char *)calloc(numRows*numRows,strlen(s)*sizeof(char *));
    
    while(s[avance]!='\0'){
        if(cpt_col%fill_all==0){ 
           
             zigzag[cpt_row][cpt_col] = s[avance];
             avance++; 
             num=numRows-1;
        }
        else{
            if(num==cpt_row+1){
                zigzag[cpt_row][cpt_col] = s[avance];
                avance++; 
                num--;
            }
            else{
                zigzag[cpt_row][cpt_col] = '-';
            }
             
        }
     
        cpt_row++;
        if(cpt_row==numRows){
            cpt_row = 0;
            cpt_col++;
        } 
    }

    int k=0;
      for(int i=0; i<numRows; i++) {
      for(int j=0;j<cpt_col+1;j++) {
            if(zigzag[i][j]>='A' && zigzag[i][j]<='Z' ){
             word[k]=zigzag[i][j];
          
             k++;
         }
      }
    }
    word[k]='\0';
    return word;
}
```

#### Screenshots

![image](https://user-images.githubusercontent.com/57147701/177544401-fc18c7c5-6bbf-48b7-bcf9-7b2239850ac9.png)
![image](https://user-images.githubusercontent.com/57147701/177544463-6fb9f631-6589-4a86-bd99-9be410991555.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
