### ISSUE TITLE
The testcase is wrong 

### ISSUE THREAD

**Issue by shaswatsingh19** [LeetCode-Feedback/LeetCode-Feedback#805]
#### Your LeetCode username
shaswat_singh

#### Category of the bug
- Solution

#### Description of the bug
My solution is correct but the output is showing is wrong , i have tried in my local ide and it shows correct output put not in leetcode

#### Code you used for Submit/Run operation

```
// 1431. Kids With the Greatest Number of Candies
class Solution:
    def kidsWithCandies(self, candies: List[int], extraCandies: int) -> List[bool]:
        m = max(candies)
        
        a =[]
        for i in range(len(candies)):
            summ = candies[i] + extraCandies
            if summ >= m :
                a.append('true')
            else:
                a.append('false')
        return a

```

#### Language used for code
Python

#### Expected behaviour
This is the wrong output showing after running the program : output [true,true,true,true,true]
but the expected output is [true,true,true,false,true]

#### Screenshots
screenshot  [https://drive.google.com/file/d/1BCp_1w1S6-NrIi1vGgZtmLlY3MpvdsU9/view?usp=sharing](url)

**Comment by lc-pam** [comment]
Hi @shaswatsingh19 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @shaswatsingh19 ,
It's probably some error in your code. We recommend checking the [problem's discuss tab](https://leetcode.com/problems/kids-with-the-greatest-number-of-candies/discuss/?currentPage=1&orderBy=most_posts&query=), search for the respective language, and compare your solution with them. Thank you!
