### ISSUE TITLE
Poor audio quality in amazon systems design 

### ISSUE THREAD

**Issue by jackielii** [LeetCode-Feedback/LeetCode-Feedback#8052]
#### Your LeetCode username

jackielii

#### Category of the bug
Audio quality issue

#### Description of the bug

https://leetcode.com/explore/featured/card/system-design/690/system-design-case-studies/4384/

the audio quality is very bad

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the video team. We appreciate your support!
