### ISSUE TITLE
Solution content is wrong - 256. Paint House

### ISSUE THREAD

**Issue by saiakhil2012** [LeetCode-Feedback/LeetCode-Feedback#8054]
#### Your LeetCode username
saiakhil2012

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the Solution 3: Memoization, in the second paragraph, i.e right after the first image, following is the content,

"Look at the leaf nodes. All the red houses cost 4, the green houses 7, and the blue houses 23. This makes sense, as the original input told us the costs of painting the 4th house red, green, or blue were 4, 7, and 23 respectively."

But the correct values of costs of red, green and blue houses for leaf nodes is 4, 8 and 12 respectively.

So, the content of the above mentioned second paragraph should be,

"Look at the leaf nodes. All the red houses cost 4, the green houses 8, and the blue houses 12. This makes sense, as the original input told us the costs of painting the 4th house red, green, or blue were 4, 8, and 12 respectively."

#### Code you used for Submit/Run operation

Not Applicable for this Issue

#### Language used for code

Not Applicable for this Issue

#### Expected behavior

Not Applicable for this Issue

#### Screenshots

Not Applicable for this Issue

#### Additional context

Not Applicable for this Issue

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
