### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by MaxRocco** [LeetCode-Feedback/LeetCode-Feedback#8055]
#### Your LeetCode username

MaxRocco

#### Category of the bug
- [ ] Question
- [* ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The expected answer is stored within nums1, which can be proven if you print 'nums1', though this is not accepted for some reason

#### Code you used for Submit/Run operation

```
class Solution {
            public void merge(int[] nums1, int m, int[] nums2, int n) {


        int[] k = new int[m + n];

        for (int i = 0; i < m; i++) {
            k[i] = nums1[i];
        } for (int j = m; j < (m + n); j++) {
            k[j] = nums2[j - m];
        }

        for (int x = 0; x < k.length; x++) {
            for (int x2 = 0; x2 < k.length - 1; x2++) {
                if (k[x2] > k[x2 + 1]) {
                    int preSwap = k[x2];
                    int postSwap = k[x2 + 1];

                    k[x2 + 1] = preSwap;
                    k[x2] = postSwap;

                }
            }
        }

        nums1 = k;
                



    }
}



```

#### Language used for code

Java

#### Expected behavior

I expected the two arrays to be merged into one, then sorted using a bubble sort to provide the expected answer.

#### Screenshots

![Leetcode bug](https://user-images.githubusercontent.com/73585527/177608876-b0cc657c-3487-4b3d-9b72-ad4f78e3fe72.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
