### ISSUE TITLE
Counter-intuitive Explanation | 130. Surrounded Regions

### ISSUE THREAD

**Issue by Vinayaka2k** [LeetCode-Feedback/LeetCode-Feedback#8056]
#### Your LeetCode username
vinuvinayaka2000

#### Category of the bug
- [Y] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The current explanation for example1 doesn't make sense. 
`Any 'O' that is not on the border and it is not connected to an 'O' on the border will be flipped to 'X'. Two cells are connected if they are adjacent cells connected horizontally or vertically.` -> this statement is incorrect!

Let's assume input is board = [X,X,X,X],[X,X,X,X],[X,0,0,X],[X,0,X,X] according to the explanation above, board[2][2] in the output must be flipped since it's not in the border and it's not connected horizontally/vertically to any 'O' cells in the border. 

But, board[2][2] is not to be flipped! 

So, the explanation has to be updated something like:
 
An 'O' will not flipped to 'X' if:
It is on the border, or
It is connected to any other 'O' that will not be flipped

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
