### ISSUE TITLE
solution improvement for Question (128. Longest Consecutive Sequence)

### ISSUE THREAD

**Issue by arjitshandilya** [LeetCode-Feedback/LeetCode-Feedback#8057]
#### Category of the bug
- [ ] Question
- [  ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is no C++ solution available in solution tab.
So, I have provided a solution which is using hashmap.
Time complexity : O(n)

#### Code you used for Submit/Run operation

```
//Longest Consecutive Sequence
class Solution {
public:
    int longestConsecutive(vector<int>& nums) {
        map<int,int> mp;
        int n=nums.size(),count=1,i=0;
        if(n==0){
            return 0;
        }
    //here we used map for sorting the elements and to remove duplicate elements 
      for(i=0;i<n;i++){
            mp.insert(make_pair(nums[i],i));
        }
        int counter=1;
        long long arr[n],l=0;
       for(auto m:mp)
        {    l=m.first;
         arr[i]=l;
         i++;
        }
        n=i;
        for(i=0;i<n-1;i++)
        {
            if(arr[i+1]-arr[i]==1)
            {
                count++;
                cout<<count;
            }
            else
            {
                counter=max(counter,count);
            count=1;
            }   
        }
       counter=max(counter,count);
       return counter;
    }
};
```
#### Language used for code
 C++

#### Additional context
Here i have used Hashmap for sorting and to remove duplicate elements at the same time and then stored them in an array for easy access with Time complexity : O(1) and then used algorithm for counting the longest sequence.

**Comment by arjitshandilya** [comment]
I have provided solution to that problem above please review it and add it on leetcode solution section as soon as possible so that others can get benefits of it .

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the solution. We appreciate your support!
