### ISSUE TITLE
Unclear description - 97. Interleaving String

### ISSUE THREAD

**Issue by james4388** [LeetCode-Feedback/LeetCode-Feedback#8059]
#### Your LeetCode username
james4388

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Question description state that |n - m| <= 1 which sound like different between length of s1 and s2 will not exceed 1. s1.length - s2.length <= 1. But non of the test case imply this. Or I may got something wrong. please explain this.

**Comment by JBlakd** [comment]
I too have this question.

I was going to post the same issue, but you beat me by 13 minutes ☺️

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stormsunshine** [comment]
The problem description means that s is divided into n substrings and t is divided into m substrings. Each substring can have length greater than 1.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
