### ISSUE TITLE
Missing testcase 1286. Iterator for Combination

### ISSUE THREAD

**Issue by yabets** [LeetCode-Feedback/LeetCode-Feedback#806]
#### Your LeetCode username
yabets

#### Category of the bug
Missing testcase

#### Description of the bug
Wrong solutions are accepted because of missing testcases.

#### Code you used for Submit/Run operation

```
class CombinationIterator {
    char[] cur, dic;
    boolean hasNext;
    int n;
    public CombinationIterator(String characters, int L) {
        cur = characters.substring(0, L).toCharArray();
        dic = characters.toCharArray();
        n = dic.length;
        hasNext = true;
    }
    
    public String next() {
        if(!hasNext) return "";
        String res = new String(cur);
        int L = cur.length;
        int i = cur.length - 1, j = dic.length - 1;
        while(i >= 0 && cur[i] == dic[j]){
            i--;
            j--;
        }
        if(i == -1){
            hasNext = false;
        }else{
            int index = String.valueOf(dic).indexOf(cur[i]);
            for( int k = i; k < L; k++) {
                cur[k] = dic[++index];
            }
        }
        return res;
    }
    
    public boolean hasNext() {
        return hasNext;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Test Cases
Input: ["CombinationIterator","next","hasNext","next","hasNext","next","hasNext"]
[["aaa",2],[],[],[],[],[],[]]
Output: [null,"aa",false,"",false,"",false]
Expected: [null,"aa",true,"aa",true,"aa",false]
The above code is accepted with invalid output due to missing testcase.

**Comment by lc-ivan** [comment]
Hi @yabets ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @yabets ,
Thank you for your feedback regarding this problem! After review, our team has concluded that we will not be adding this test case as it does not meet the constraints of the problem. Once again we thank you for your feedback and happy LeetCoding!
