### ISSUE TITLE
Strange output in 344. Reverse String

### ISSUE THREAD

**Issue by GDaniil17** [LeetCode-Feedback/LeetCode-Feedback#8060]
#### Your LeetCode username
galimovdv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When I use s = s[::-1] print changes but the output for system is the same as original list

#### Code you used for Submit/Run operation

```
// 344. Reverse String
class Solution:
    def reverseString(self, s: List[str]) -> None:
        s = s[::-1]
        print(s)
```

#### Language used for code
Python3

#### Expected behavior
I expect to see the output that reflects value of print(s)

#### Screenshots
![image](https://user-images.githubusercontent.com/32881349/177745986-e44780b7-5b7f-4659-ad6a-c6c0ebbdc733.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
