### ISSUE TITLE
Wrong description of space complexity to solve the problem 97 (Interleaving String).

### ISSUE THREAD

**Issue by gu1show** [LeetCode-Feedback/LeetCode-Feedback#8061]
#### Your LeetCode username

gu1show

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

**Wrong description of space complexity.**
From the description:
> Space complexity : O(n). n is the length of the string s1.

But in the code it is used the length of the string s2 + 1.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
