### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Sriansh-raj** [LeetCode-Feedback/LeetCode-Feedback#8062]
#### Your LeetCode username
sriansh_

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug
No bugs. I just want to contribute a new testcase.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        vector<int> res; 
        
        for(int i=0; i<nums.size() - 1; ++i) // runs from i=0 to size - 2
        {
            for(int j=i+1; j<nums.size(); ++j) // runs from i + 1 to size - 1
            {
                if(nums[i] + nums[j] == target) // if sum of indices = target
                {
                    res.push_back(i); 
                    res.push_back(j); 
                    goto end_statement;  // jump to the label
                }
            }
        }
        end_statement: 
        return res; // returning the result
    }
}; 
```

#### Language used for code
C++

#### Expected behavior
Add one more test case -
input :  nums = [0, 0, 1] ,    target = 0
output : [0, 1]

**Comment by LC-Pam** [comment]
Hi there,
![Screen Shot 2022-07-07 at 1 42 10 PM](https://user-images.githubusercontent.com/103138242/177836577-1e4376c8-cce7-42a1-930d-b3e7f51a7d94.png)

Thank you for reaching out to us! The test case that you provided above already exist, we appreciate you support!
