### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by wclord** [LeetCode-Feedback/LeetCode-Feedback#8066]
#### Your LeetCode username

wclord

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

test case:

s="aaaae"
p="a\*ed\*"

the "Expected" box is shown as "true"
however it should be "false"

#### Language used for code

Python3

**Comment by stormsunshine** [comment]
Please explain why the expected result should be false. The string s can be represented as three character a's, one character e and zero character d's. Why do you think the result should be false?

**Comment by wclord** [comment]
Thanks for the explanation,
I misinterpreted "It is guaranteed for each appearance of the character '*', there will be a previous valid character to match."
