### ISSUE TITLE
Description not clear - 1290. Convert Binary Number in a Linked List to Integer

### ISSUE THREAD

**Issue by utkarsh-trivedi98** [LeetCode-Feedback/LeetCode-Feedback#8067]
#### Your LeetCode username
er_utkarsh 

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description of the question is not clear. The question does not state whether the most significant bit is at the head of the list or at the tail. 

#### Code you used for Submit/Run operation
```
class Solution {
    static int pow;
    public int getDecimalValueHelper(ListNode node) {
        if(node == null) return 0;
        
        int val = getDecimalValueHelper(node.next);
        val += node.val*pow;
        pow *= 2;
        
        return val;        
    }
    public int getDecimalValue(ListNode head) {
        pow = 1;
        
        return getDecimalValueHelper(head);
    }
}
```

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
