### ISSUE TITLE
2330. Valid Palindrome IV题目无法打开

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8068]
**你的 LeetCode 用户名**
stormsunshine

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
2330. Valid Palindrome IV在LCUS已经存在，链接是：https://leetcode.com/problems/valid-palindrome-iv
这道题在LCCN的链接应该是：https://leetcode.cn/problems/valid-palindrome-iv
目前这道题在LCCN的链接无法打开。

**期望行为**
这道题在LCCN的链接应该可以打开。

**Comment by BrambleWave** [comment]
已修复，感谢反馈。
