### ISSUE TITLE
Can you please reply to the request 118361 that I sent to support@leetcode.com ?

### ISSUE THREAD

**Issue by LC-please-reply** [LeetCode-Feedback/LeetCode-Feedback#8069]
Can you please respond to the request 118361? You previously said "We apologize for missing the previous emails! This will be relayed over to our customer support team for improvements!" But why now you start to ignore requests again? Looks like this is a systematic issue, because it has happened multiple times!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. We are sorry to hear that your issue still not solved. 
 I've relayed the issue to our Zendesk Support team to investigate, they will reach out to you soon. 
Github platform is for content-related issue, if you have any content-related issue, please do not hesitate to let us know!

We appreciate your time and support.

Best,

Github Support Team

**Comment by LC-please-reply** [comment]
Hi @LC-Pam , your Zendesk Support team still hasn't replied.
