### ISSUE TITLE
1286. Iterator for Combination. Missing constraint check

### ISSUE THREAD

**Issue by highfinddale** [LeetCode-Feedback/LeetCode-Feedback#807]
#### Your LeetCode username
highfinddale

#### Category of the bug
- [.] Question

#### Description of the bug
According to the question constraints are as follows 
1. 1 <= combinationLength <= characters.length <= 15
2. There will be at most 10^4 function calls per test.
3. It's guaranteed that all calls of the function next are valid.

But it appears that last constraint is not validated correctly. A carefully constructed test case can reveal important implementation details. 

Test case: 
```
'["CombinationIterator","next","hasNext","next","hasNext","next","hasNext"]
[["abc",3],[],[],[],[],[],[]]'
```
Judge Result:
```
Line 8: IndexError: pop from an empty deque
```

#### Code you used for Submit/Run operation
NA

#### Language used for code
Java

#### Expected behavior
Judge should return invalid test case without revealing implementation details. 

#### Screenshots
<img width="750" alt="Screenshot 2020-08-13 at 9 55 18 PM" src="https://user-images.githubusercontent.com/3402185/90160807-e3422680-ddaf-11ea-9b28-79147c46b301.png">

**Comment by lc-pam** [comment]
Hi @highfinddale 
Thank you for reaching out to us. Would you mind providing the code you used? I've tried using the code from the official solution but failed to reproduce the issue you encountered. Thank you!

**Comment by highfinddale** [comment]
// class 
```
class CombinationIterator {

   int count=0; 
    SortedSet<String> codes=new TreeSet<>();
    Iterator<String> itr=null; 
    public CombinationIterator(String characters, int combinationLength) {
        count=combinationLength;
        generateCombination(-1, characters, "");    
        itr=codes.iterator(); 
    }
    
    public String next() {
        if(hasNext())
            return itr.next(); 
        else  
            return ""; 

    }
    
    public boolean hasNext() {
        return itr.hasNext(); 
    }

    private void generateCombination(int index, String s, String trail){
        if(s.length()<index)
            return;  
        if(trail.length()==count){
            codes.add(trail);
            return;  
        }
        for(int n=index+1;  n<s.length(); n++)
            generateCombination(n, s,trail+s.charAt(n));

    }
}
```

**Comment by lc-pam** [comment]
Hi @highfinddale 
Thanks for providing your code. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @highfinddale 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
