### ISSUE TITLE
Wrong statement in Approach 1: Brute force solution - 629. K Inverse Pairs Array

### ISSUE THREAD

**Issue by azmuth13** [LeetCode-Feedback/LeetCode-Feedback#8071]
#### Your LeetCode username
suraj__k 

#### Category of the bug
- [ ] Solution

#### Description of the bug
In the Approach 1: brute force solution:
```The most naive solution is to generate every permutation of the array consisting of numbers from 1 to n. Then, we can find out the number of inverse pairs in every array to determine if it is equal to 1```.  Here instead of ```equal to 1```, it should be ```equal to k``` since we will be checking for k inverse pairs in each permutation and not 1 inverse pair.

#### Screenshots

<img width="317" alt="image" src="https://user-images.githubusercontent.com/72400473/177938282-49f9e517-bb2f-43dd-a48e-3ba61b3a94b6.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
