### ISSUE TITLE
Missing Test Case - 1008. Construct Binary Search Tree from Preorder Traversal

### ISSUE THREAD

**Issue by Dhananjay2010** [LeetCode-Feedback/LeetCode-Feedback#8072]
#### Your LeetCode username

JoseDJ2010

#### Category of the bug
- [ ] Question
- [ ] Solution

#### Description of the bug

Whenever I submit my question, it shows the test case failed for test case [1,3], but when I run my code, the test case runs perfectly. This is the main issue. 

#### Code you used for Submit/Run operation

```
class Solution {
    static int p = 0;

    public TreeNode bstFromPreorder(int[] preorder, int leftRange, int rightRange) {

        if (p > preorder.length - 1) {
            return null;
        }

        TreeNode node = new TreeNode(-(int) 1e9);
        if (preorder[p] > leftRange && preorder[p] < rightRange) {
            node.val = preorder[p];
            p++;
        }

        if (node.val == -(int) 1e9) {
            return null;
        }

        node.left = bstFromPreorder(preorder, leftRange, node.val);
        node.right = bstFromPreorder(preorder, node.val, rightRange);

        return node;
    }

    public TreeNode bstFromPreorder(int[] preorder) {
        
        if(preorder.length == 0){
            return null;
        }
        TreeNode head= bstFromPreorder(preorder, -(int) 1e9, (int) 1e9);
        return head;
    }
}
```

#### Screenshots

![image](https://user-images.githubusercontent.com/83901321/177938502-1847e0dd-c0c8-484d-95e1-e5098d28be58.png)

**Comment by stormsunshine** [comment]
Don't use static variable in your code.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
