### ISSUE TITLE
Test case out of constraints provided in Q189. Rotate array.

### ISSUE THREAD

**Issue by Gagan786** [LeetCode-Feedback/LeetCode-Feedback#8073]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Acc. to constraint provided , K should be less than or equal to the length of an array. on submitting the solution one test case takin "k" > length of an array.
It violates the constraints provided.

#### Code you used for Submit/Run operation

```
class Solution {
    public void rotate(int[] nums, int k) {
        
        int i = 0;
        int n = nums.length;
        if(n == 1)
            return ;
      //reverse an array.
        while(i<n/2){
            swap(nums,i,n-1-i);
            i++;
        }
     System.out.println(Arrays.toString(nums));

        //reverse subarray from 0 to k-1 
        i=0;
        while(i< (k+1)/2){
            swap(nums,i,k-i-1);
            i++;
        }
        i= 0;
      //reverse subarray from k to n-1;
        int ub = (k+n)/2;
        while(k+i < ub){
            swap(nums,k+i,n-1-i);
            i++;
        }
        // System.out.println(Arrays.toString(nums));
    }
  //swapping values
    void swap(int[] nums,int a,int b){
        int temp = nums[a];
        nums[a] =nums[b];
        nums[b] = temp;
    }
}
```

#### Screenshots

![image](https://user-images.githubusercontent.com/32445101/177941263-45a6ead9-2bb2-4abd-9dc8-34588d906040.png)
![image](https://user-images.githubusercontent.com/32445101/177941842-539a5937-9068-4914-bbe5-54f96880ff78.png)
![image](https://user-images.githubusercontent.com/32445101/177941684-6de2600f-e38f-4bd3-b317-258b33cec935.png)

**Comment by stormsunshine** [comment]
This problem does not require that k must be less than or equal to the length of array nums. The test case is correct.
