### ISSUE TITLE
Missing Test Case - 201. Bitwise AND of Numbers Range

### ISSUE THREAD

**Issue by Harsh-2022** [LeetCode-Feedback/LeetCode-Feedback#8074]
#### Your LeetCode username

Harsh2022

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a missing test case due to which my solution gets accepted which shouldn't.
**Test Case:** 
```
1073741824‬
2147483647
```

If I dry run my code, then number of operations for the above test case will be of the order 10^9 . Hence, TLE must come. But the solution gets accepted.

#### Code you used for Submit/Run operation

```

class Solution
{
public:
    int rangeBitwiseAnd(int left, int right)
    {

        int res = left;
        if (left == 0 || right == 0)
            return 0;
        else if ((int)log2(left) != (int)log2(right))
            return 0;
        else
        {

            for (long long int i = left + 1ll; i <= right; i++)
                res &= i;
        }
        return res;
    }
};


```

#### Language used for code

C++

#### Expected behavior

Verdict should be **Time Limit Exceeded** instead of **Accepted**

#### Screenshots

![image](https://user-images.githubusercontent.com/92209366/177999338-b9973bac-e852-4f60-981a-5f23f6ad13d1.png)

#### Additional context

Submission link : 
[https://leetcode.com/submissions/detail/741781757/](url)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

The test case that you provided is invalid. 
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
