### ISSUE TITLE
Need to Add Restrictions - 770. Basic Calculator IV

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8075]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [770. Basic Calculator IV](https://leetcode.com/problems/basic-calculator-iv), a restriction should be added in problem description or constraints, to make sure all intermediate results and the final result are in the range of a 32-bit signed integer.

If such a restriction is not added, then it is possible that an intermediate result or the final result is out of the range of a 32-bit signed integer, or even out of the range of a 64-bit signed integer. In this case, users have to define a data type like BigInteger in Java. I don't think the main point of this problem is to define a BigInteger type. The main point of this problem should be dealing with the given expression that may contain variables.

Also, the other problems in "Basic Calculator" series, including [224. Basic Calculator](https://leetcode.com/problems/basic-calculator), [227. Basic Calculator II](https://leetcode.com/problems/basic-calculator-ii) and [772. Basic Calculator III](https://leetcode.com/problems/basic-calculator-iii), have mentioned that all intermediate results will be in the range of a 32-bit signed integer (or the same meaning). Therefore, such a restriction should also apply for 770.

#### Expected behavior
Add a restriction in problem description or constraints, to make sure all intermediate results are in the range of a 32-bit signed integer.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Added the restriction.

Did not make updates to the validator because such test cases are not "invalid", they are just not added in the test set. In case you want to see if your solution passes for larger cases, you can feel free to use custom input option. The model solutions are written in python, which should not have any out of bounds issues.

However, we will not add such test cases to the set.
 We appreciate your support!
