### ISSUE TITLE
Solution Typo - 541. Reverse String II

### ISSUE THREAD

**Issue by paulinachametka** [LeetCode-Feedback/LeetCode-Feedback#8076]
#### Your LeetCode username
 paulinachametka 

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
 typo in python solution that states "in xrange" instead of "in range" 
a = list(s)
        for i in xrange(0, len(a), 2*k):
            a[i:i+k] = reversed(a[i:i+k])
        return "".join(a)

#### Code you used for Submit/Run operation
 should be

a = list(s)
        for i in range(0, len(a), 2*k):
            a[i:i+k] = reversed(a[i:i+k])
        return "".join(a)

#### Language used for code
Python 

#### Expected behavior
 If you run it with the typo it says "xrange is not defined" which makes the solution incorrect, should be just "range" 

#### Screenshots

![image](https://user-images.githubusercontent.com/59401667/178025900-482108f5-15cd-4b40-86f6-599d497a07a2.png)

#### Additional context
 Add any other additional context about the bug.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
