### ISSUE TITLE
2. Add Two Numbers - Wrong results in Compiler

### ISSUE THREAD

**Issue by naveenchandra9** [LeetCode-Feedback/LeetCode-Feedback#8077]
#### Your LeetCode username

neoveen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

After submitting the code it is showing wrong answer for particular test case but when i entered the same testcase in LeetCode Console (below the editor) im getting write answer for same testcase. 

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        ListNode* ans=new ListNode(-1);
        ListNode* anshead=ans;
        int a,b=0;
        while(l1!=NULL){
            a=(a*10)+l1->val;
            l1=l1->next;
        }
        while(l2!=NULL){
            b=(b*10)+l2->val;
            l2=l2->next;
        }
        int sum=0;
        sum=sum+(a+b);
        int n=sum;
        if((n/10)==0){
            ListNode* node=new ListNode(n);
            ans->next=node;
        }
        else if(sum==0){
            ListNode* node=new ListNode(0);
            ans->next=node;
        }
        else{
        int temp=sum;
        while(temp!=0 or temp/10!=0){
            int v=temp%10;
            ListNode* node=new ListNode(v);
            ans->next=node;
            ans=ans->next;
            temp=temp/10;
        }
        }

         return anshead->next;     
 }
};
```

#### Language used for code

C++

#### Expected behavior

It should be correct answer in compiler

#### Screenshots

![Screenshot 2022-07-08 212523](https://user-images.githubusercontent.com/74419537/178030602-6a3f8fc4-080b-468b-b528-8454ae8f9d1e.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
