### ISSUE TITLE
Pascal's Triangle II invalid test case

### ISSUE THREAD

**Issue by asavant** [LeetCode-Feedback/LeetCode-Feedback#808]
#### Your LeetCode username

asavant

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

In https://leetcode.com/problems/pascals-triangle-ii/ the test case of '-1', which should not be a valid case incorrectly returns expected value of [1].

#### Code you used for Submit/Run operation

```
// Not relevant
```

#### Language used for code

Java

#### Expected behavior

It should fail for non-negative input as stated in the problem description.

**Comment by lc-pam** [comment]
Hi @asavant 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @asavant 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
