### ISSUE TITLE
What is Dynamic Programming - optimal substructure - wrong definition

### ISSUE THREAD

**Issue by AdamLettuce** [LeetCode-Feedback/LeetCode-Feedback#8080]
Hello,
What is Dynamic Programming page defines optimal substructure as follows:
The problem has an "optimal substructure" - an optimal solution can be formed from optimal solutions to the **overlapping** subproblems of the original problem.

The above definition is wrong and misleading and makes hard to understand next lines - it should state the following:
The problem has an "optimal substructure" - an optimal solution can be formed from optimal solutions to the subproblems of the original problem.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by AdamLettuce** [comment]
The page link is: https://en.wikipedia.org/wiki/Optimal_substructure .

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
