### ISSUE TITLE
Missing Test Case - 2158. Amount of New Area Painted Each Day

### ISSUE THREAD

**Issue by Candy374** [LeetCode-Feedback/LeetCode-Feedback#8081]
#### Your LeetCode username
lingling374

#### Category of the bug
Missing Test Cases 

#### Description of the bug

in my algorithm, I need a quick jumper to the next end, but never update the next end, 
if the next end is the same as next index, then it will be no use at all. 

#### Code you used for Submit/Run operation

```
function amountPainted(paint: number[][]): number[] {
    const paintMap = new Map();
    
    const result = [];
    for (const [start, end] of paint) {
        let log = 0;
        let i = start;
        while (i < end) {
            if (!paintMap.has(i)) {
                log ++;
                paintMap.set(i, end);
                i++;
            } else {
                i = paintMap.get(i);
            }
        }
        result.push(log);
    }
    
    return result;
};
```

#### Language used for code
typescript

#### Expected behavior
my algorithm should hit the time limit with a case that has the following conditions:
 - the total length of paint is 10000
 - the first half of the paint is only 1 step with no overlap. eg. [[0,1], [1,2], [2,3], [3, 4] ...]
 - the rest half of the paint is full length. eg. [[0, 5000], [0, 5000], ...]
 

the test case can be created by `javascript`: 
```
JSON.stringify(Array.from({length: Math.pow(10, 5) / 2 }).map((_, i) => [i, i + 1]).concat(Array.from({length: Math.pow(10, 5) / 2 }).map(() => [0, Math.pow(10, 5) / 2])))
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Candy374** [comment]
Thank you!
