### ISSUE TITLE
Missing Test Case - 543. Diameter of Binary Tree

### ISSUE THREAD

**Issue by NutNick31** [LeetCode-Feedback/LeetCode-Feedback#8082]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In this question, for the testcase [1,2,3,4,5], the correct output should be 4, but the output given by the leetcode platform is 3.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int height(TreeNode* root)
    {
        if(root==NULL) return 0;
        return max(height(root->left),height(root->right)) + 1;
    }
    int diameterOfBinaryTree(TreeNode* root) {
        if(root==NULL) return 0;
        int lHeight = height(root->left);
        int rHeight = height(root->right);
        int currDia = lHeight + rHeight +1;
        
        int lDia = diameterOfBinaryTree(root->left);
        int rDia = diameterOfBinaryTree(root->right);
        return max(currDia, max(lDia, rDia));
    }
};
```

#### Language used for code

C++

#### Expected behavior

The output for the testcase [1,2,3,4,5] should be 4, but instead the output given by the platform is 3.

#### Screenshots

![2022-07-09](https://user-images.githubusercontent.com/81872302/178091385-182deaa1-71bd-4739-8de5-b7c1d9a88c57.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
