### ISSUE TITLE
383题赎金信同样的测试用例，控制台和提交的执行结果不一致

### ISSUE THREAD

**Issue by heipp** [LeetCode-Feedback/LeetCode-Feedback#8084]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
黑泡泡

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
我在解答第383题.赎金信的时候，当代码使用测试用例通过后选择提交代码，反馈我解答错误，但同样的测试用例，在控制台的执行结果是解答正确
**你使用的语言**
C

**你提交或者运行的代码**
```
static int ransomNoteNum[26] = {0};
void ransomNoteCharNum(char *ransomNote)
{
    int ransomNoteLen = strlen(ransomNote);
    for (int i = 0; i < ransomNoteLen; i++) {
        ransomNoteNum[ransomNote[i] - 'a']++;
    }
}

static int magazineNum[26] = {0};
void magazineCharNum(char *magazine)
{
    int magazineLen = strlen(magazine);
    for (int i = 0; i < magazineLen; i++) {
        magazineNum[magazine[i] - 'a']++;
    }
}

bool canConstruct(char *ransomNote, char *magazine)
{
    ransomNoteCharNum(ransomNote);
    magazineCharNum(magazine);
    for (int i = 0; i < 26; i++) {
        if (magazineNum[i] >= ransomNoteNum[i]) {

        } else {
            return false;
        }
    }
    return true;
}
```

**期望行为**
找到问题的原因，是我的原因还是其他原因

**屏幕截图**
这是提交后的截图![image](https://user-images.githubusercontent.com/66395160/178097127-128c9b6e-dd91-42a7-92de-d7c5ec7f8e8d.png)
同样的测试用例在控制台的执行结果
![image](https://user-images.githubusercontent.com/66395160/178097167-8d1c7029-7d94-42a8-8082-76f58e1ffb4d.png)

**额外的上下文**
给你两个字符串：ransomNote 和 magazine ，判断 ransomNote 能不能由 magazine 里面的字符构成。

如果可以，返回 true ；否则返回 false 。

magazine 中的每个字符只能在 ransomNote 中使用一次。

 

示例 1：

输入：ransomNote = "a", magazine = "b"
输出：false
示例 2：

输入：ransomNote = "aa", magazine = "ab"
输出：false
示例 3：

输入：ransomNote = "aa", magazine = "aab"
输出：true
 

提示：

1 <= ransomNote.length, magazine.length <= 105
ransomNote 和 magazine 由小写英文字母组成

来源：力扣（LeetCode）
链接：https://leetcode.cn/problems/ransom-note
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by BrambleWave** [comment]
属于自己的代码问题。
