### ISSUE TITLE
2301. Match Substring After Replacement (Weak test cases)

### ISSUE THREAD

**Issue by d-s-dc** [LeetCode-Feedback/LeetCode-Feedback#8085]
#### Username
d_codr

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The [question](https://leetcode.com/problems/match-substring-after-replacement/) has weak test cases. I went through one of the `accepted answers` and `found` a `test case` which `justifies` that the `solution` is `wrong`. I verified the test case through the custom test case panel in the question.

#### Code you used for Submit/Run operation
```
class Solution {
public:
vector<int> compute_lps(string &s) {
    vector<int> lps(s.size());
    for (int i = 1, j = 0; i < s.size(); ++i) {
        while (j && s[i] != s[j])
            j = max(0, lps[j] - 1);
        j += s[i] == s[j];
        lps[i] = j;
    }
    return lps;
}
bool matchReplacement(string s, string sub, vector<vector<char>>& mappings) {
    unordered_map<char, unordered_set<char>> m;
    auto lps = compute_lps(s);
    for (auto &p : mappings)
        m[p[0]].insert(p[1]);
    for (int i = 0, j = 0; i < s.size();) {
        if (s[i] == sub[j] || m[sub[j]].count(s[i])) {
            ++i;
            ++j;
        }
        else {
            if (j != 0)
                j = lps[j - 1];
            else
                i = i + 1;            
        }
        if (j == sub.size())
            return true;
    }
    return false;
}
};
```

#### Language used for code
C++

#### Expected behavior
This code should not be accepted.

#### Screenshots
![image](https://user-images.githubusercontent.com/68206552/178097801-8b91ace1-52c4-42e0-aad3-9d9494709519.png)

![image](https://user-images.githubusercontent.com/68206552/178097860-8cc3a979-041a-452d-8c7f-dfa670792acf.png)

#### Additional context
Test case which fails is - 
> "awcb"
> "awd"
> [["a","w"],["w","c"],["d","b"]]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
