### ISSUE TITLE
Incorrect Test Case - 556. Next Greater Element III

### ISSUE THREAD

**Issue by amberchen122** [LeetCode-Feedback/LeetCode-Feedback#8086]
#### Your LeetCode username
amberchen122

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [-] Missing Test Cases 

#### Description of the bug

The problem description says "1 <= n <= 2**31 - 1" but the test case 39 is 2147483486(out of bound). The problem description is inconsistent with the test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/63131314/178098543-c696b67f-db71-499a-a255-a440e9440f9d.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by LC-Pam** [comment]
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
