### ISSUE TITLE
Missing Test Case - 652. Find Duplicate Subtrees

### ISSUE THREAD

**Issue by iemeka** [LeetCode-Feedback/LeetCode-Feedback#809]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test case fails but solution is accepted.

#### Code you used for Submit/Run operation

```
// Find Duplicate Subtrees
class Solution(object):
    def findDuplicateSubtrees(self, root):
       
        def all_paths(root,paths):
            if root:
                if root.val in paths:
                    paths[root.val].append(root)
                else: paths[root.val] = [root]
                all_paths(root.left,paths)
                all_paths(root.right,paths)
                return paths
            
        def get_pos_dup(paths):
            poss_dup = []
            for node_val in paths:
                if len(paths[node_val]) >= 2:
                    poss_dup+=paths[node_val]
            return poss_dup
         
        def find_dup(root):
            if not root or (not root.left and not root.right): return []
            paths = all_paths(root,{})
            if len(paths) == 1:
                if not (root.left and root.right):
                    return []
            possible_dup = get_pos_dup(paths)
            output, marked,checked = [], set(),set()
            for node in possible_dup:
                node_str = str(node)
                if node_str in checked:
                    if node_str not in marked:
                        marked.add(node_str)
                        output.append(node)
                else: checked.add(node_str)
            return output
        return find_dup(root)
```

#### Language used for code

Python

#### Expected behavior

Solution should not be accepted given the failed test case

#### Screenshots

![Screenshot from 2020-08-13 19-32-52](https://user-images.githubusercontent.com/10095449/90174053-4d050500-dd9d-11ea-8755-ce50004bc8b0.png)

#### Additional context

https://leetcode.com/problems/find-duplicate-subtrees/
test case :  Trees with same nodes values, single chain of nodes from root to any sub-tree with either left or right child.
[0,null,0,0,null,0,0,null,0,null,0,0]
[0,null,0,null,0,0,null,0,0,null,0,null,0,0]

**Comment by lc-pam** [comment]
Hi @iemeka 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @iemeka 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
