### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by AbhishekRanjan624** [LeetCode-Feedback/LeetCode-Feedback#8090]
class Solution {
    public boolean isIsomorphic(String s, String t) {
        
        int[] arr1= new int[256] ;
        int[] arr2 =new int[256] ; 
        
        Arrays.fill(arr1 , -1) ;
        Arrays.fill(arr2 , -1) ;
        
        for(int i=0 ; i<s.length() ; i++){
            if(arr1[s.charAt(i)]!=arr2[t.charAt(i)]){
                return false ;
            }else{
                arr1[s.charAt(i)]=arr2[t.charAt(i)]=i ;   
            }
        }
        return true ;
    }
}

// without using HashMap

**Comment by AbhishekRanjan624** [comment]
leetcode-205

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
