### ISSUE TITLE
Incomplete Description 

### ISSUE THREAD

**Issue by royamjj** [LeetCode-Feedback/LeetCode-Feedback#8091]
dracky 

#### Category of the bug
- [ ] Question
- [ .] Solution
- [ .] Language
- [ ] Missing Test Cases 

#### Description of the bug

Incomplete description::
The question has mentioned that passengers[i]>=2 but some tc has answer 1 so either it should be given that answers can be less than 2 or -1 for such cases

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int latestTimeCatchTheBus(vector<int>& buses, vector<int>& pass, int k) {
        sort(buses.begin(),buses.end());
        sort(pass.begin(),pass.end());
        int ans=0;
        int j=0;
        unordered_set<int>s;
        int mark=0;
        for(int i=0;i<buses.size();i++){
            int temp=0;
            while(j<pass.size() && temp<k && pass[j]<=buses[i]){
                s.insert(pass[j]);
                j++;temp++;
            }
            if(temp==k)mark=1;
            else mark=0;
        }
        int maxi = mark!=0 ? pass[j-1] :buses.back();
        while(maxi>0){
            if(s.find(maxi)==s.end())return maxi;
            maxi--;
        }
        return -1;
    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/87959809/178113564-13709b86-691c-41f0-9db7-db3bf706ac6a.png)

**Comment by bogoconic1** [comment]
answer can be 1, its just the constraint of the elements in buses and passengers are between 2 and 10^9
