### ISSUE TITLE
Incorrect Example Test Case Description: 2332. The Latest Time to Catch a Bus

### ISSUE THREAD

**Issue by bogoconic1** [LeetCode-Feedback/LeetCode-Feedback#8092]
#### Your LeetCode username
bogoconic1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For example 2,
buses = [20,30,10], passengers = [19,13,26,4,25,11,21], capacity = 2
Explanation:
The 1st bus departs with the 4th passenger. 
The 2nd bus departs with the 6th and 2nd passengers.
The 3rd bus departs with the 1st passenger and you.

but the 3rd bus departs at time 10 and 1st passenger arrives at time 19, how can the 1st passenger board the 3rd bus ?
The buses may not be in sorted order

#### Expected behavior

Explanation:
The _3rd_ bus departs with the 4th passenger. 
The _1st_ bus departs with the 6th and 2nd passengers.
The _2nd_ bus departs with the 1st passenger and you.

**Comment by royamjj** [comment]
The given buses array is the time is has nothing to do with id's first you sort the buses and passengers so that the bus with lowest departure time comes first, you misinterpreted the question ...Here it might help
```
class Solution {
public:
    int latestTimeCatchTheBus(vector<int>& buses, vector<int>& pass, int k) {
        sort(buses.begin(),buses.end());
        sort(pass.begin(),pass.end());
        int ans=0;
        int j=0;
        unordered_set<int>s;
        int mark=0;
        for(int i=0;i<buses.size();i++){
            int temp=0;
            while(j<pass.size() && temp<k && pass[j]<=buses[i]){
                s.insert(pass[j]);
                j++;temp++;
            }
            if(temp==k)mark=1;
            else mark=0;
        }
        int maxi = mark!=0 ? pass[j-1] :buses.back();
        while(maxi>0){
            if(s.find(maxi)==s.end())return maxi;
            maxi--;
        }
        return -1;
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
