### ISSUE TITLE
Wrong output for a testcase - 2332. The Latest Time to Catch a Bus

### ISSUE THREAD

**Issue by harshB1709** [LeetCode-Feedback/LeetCode-Feedback#8093]
#### Your LeetCode username
HarshBachawat

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Wrong o/p for a testcase
buses = [18,8,3,12,9,2,7,13,20,5]
passengers = [13,10,8,4,12,14,18,19,5,2,30,34]
capacity = 1

#### Code you used for Submit/Run operation

```
class Solution:
    def latestTimeCatchTheBus(self, buses: List[int], passengers: List[int], capacity: int) -> int:
        buses.sort(reverse = True)
        passengers.sort(reverse = True)
        bus_p = 0
        pass_p = 0
        while pass_p < len(passengers) and passengers[pass_p] > buses[bus_p]:
            pass_p += 1
        while bus_p < len(buses):
            curr_cap = capacity
            last_p = None
            passen = set()
            limit = buses[bus_p + 1] if ((bus_p + 1) < len(buses)) else 0
            # print(limit, pass_p, bus_p,pass_p < len(passengers),limit <= passengers[pass_p] < buses[bus_p])
            while pass_p < len(passengers) and limit <= passengers[pass_p] <= buses[bus_p]:
                last_p = passengers[pass_p]
                passen.add(passengers[pass_p])
                curr_cap -= 1
                pass_p += 1
            # print(last_p, passen, curr_cap)
            if curr_cap < 1:
                if (last_p - 1) >= limit:
                    return last_p - 1
                else:
                    bus_p += 1
            else:
                p = buses[bus_p]
                # print('p',p, passen, p in passen)
                while p >= limit and p in passen:
                    p -= 1
                return p
```

#### Language used for code

Python3

#### Expected behavior

buses = [18,8,3,12,9,2,7,13,20,5]
passengers = [13,10,8,4,12,14,18,19,5,2,30,34]
capacity = 1

sorted(buses) = [2, 3, 5, 7, 8, 9, 12, 13, 18, 20]
sorted(passengers) = [2, 4, 5, 8, 10, 12, 13, 14, 18, 19, 30, 34]

according to the question,
19 waits for 20
14, 18 wait for 18
13 waits for 13
10,12 wait for 12 (capacity is only 1 so 11 cannot be added since 10 is already in the list)
no-one waits for 9
8 waits for 8
so we can return 9 as answer
but the question says the answer should be 11.
Am I missing something here.. Please explain.

#### Screenshots

https://leetcode.com/problems/the-latest-time-to-catch-a-bus/discuss/2259424/Please-explain-the-expected-output-for-this
![ques_error](https://user-images.githubusercontent.com/64487906/178118245-a4f0a430-a401-4e14-b5e3-452a706f067e.PNG)

#### Additional context

Problem Desciption - 
https://leetcode.com/problems/the-latest-time-to-catch-a-bus/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
