### ISSUE TITLE
Incorrect Constraints - 747. Largest Number At Least Twice of Others

### ISSUE THREAD

**Issue by v1k1nghawk** [LeetCode-Feedback/LeetCode-Feedback#8098]
#### Your LeetCode username

v1k1nghawk

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the description of the problem in the "Constraints" section, it says:
"1 <= nums.length <= 50", but when I use as an custom testcase "[99]",
I get this output:
"Invalid Testcase
expected 'nums' to have 2 <= size <= 50 but got 1".

#### Expected behavior

I believe that lower boundary of this constraint written in the Description should be 2:
"2 <= nums.length <= 50".

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
