### ISSUE TITLE
269. Alien Dictionary, test case ["abc","ab"] is invalid

### ISSUE THREAD

**Issue by xianshuli** [LeetCode-Feedback/LeetCode-Feedback#81]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [x ] language

**Describe the bug**
The problem mentioned note:

You may assume that if a is a prefix of b, then a must appear before b in the given dictionary.

Then why "ab" appears after "abc" for this case? This should be an invalid test case and should be removed.

Thanks

**Comment by CooperCooperCooper** [comment]
Hi @xianshuli,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by liuauto** [comment]
Not sure if I understand. But the note said: If the order is invalid, return an empty string. So this test case should just return ""?

**Comment by xianshuli** [comment]
It seems the admin modified the description of the problem. Previously there is no such statement "If the order is invalid, return an empty string.". It was "You may assume that if a is a prefix of b, then a must appear before b in the given dictionary." instead.

**Comment by CJMobileApps** [comment]
I see many people in the leetcode comment section complaining about this test case. I believe the problem description should be more clear or this test case should be removed. It is very confusing.

**Comment by CooperCooperCooper** [comment]
Hi @xianshuli,
Thank you for your time and support! The test case ["abc","ab"] is valid, so we've updated the problem statement. Please check out [the problem](https://leetcode.com/problems/alien-dictionary/) now and let us know if you have any other questions :)
