### ISSUE TITLE
Unreadable question - 211. Add and Search Word - Data structure design

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#810]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

211. Add and Search Word - Data structure design

https://leetcode.com/problems/add-and-search-word-data-structure-design/

Below line is unreadable, due to multiple dots (.):

    `containing only letters a-z or .. A . means it can represent any one letter.`

Please write it as below:

    `containing only . or letters a-z. Here, . means it can represent any one letter.`

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

It took 10 minutes to understand a simple question.
Question formatting and words must be proper.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thanks for reaching out and for the feedback regarding this problem. After review, our team has concluded the problem description is not syntactically ambiguous. Once again thank you for the feedback and happy LeetCoding!

**Comment by manoharreddyporeddy** [comment]
But you have changed the problem description & title :)

    https://leetcode.com/problems/design-add-and-search-words-data-structure/
