### ISSUE TITLE
Incorrect Hint - 746. Min Cost Climbing Stairs

### ISSUE THREAD

**Issue by hemangkinra** [LeetCode-Feedback/LeetCode-Feedback#8102]
kinrahemang

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The hint given is incorrect.

#### Code you used for Submit/Run operation

```
int minCostClimbingStairs(vector<int>& cost) {
        vector<int> dp(cost.size());
        int ans = INT_MAX;
        dp[0] = cost[0];
        dp[1] = cost[1];
        int n = cost.size();
        for(int i=2;i<cost.size();i++){
            dp[i] = min(dp[i-1],dp[i-2]) + cost[i];
        }
        return min(dp[n-1],dp[n-2]);
}
```

#### Expected behavior

The hint should be **f[i] = cost[i] + min(f[i-1], f[i-2])** and not f[i] = cost[i] + min(f[i+1], f[i+2])

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The hints are correct. We changed their format to be clearer. We appreciate your support!
