### ISSUE TITLE
Missing Test Case - 1696. Jump Game VI

### ISSUE THREAD

**Issue by lkwq007** [LeetCode-Feedback/LeetCode-Feedback#8104]
#### Your LeetCode username

lkwq007

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Missing test case: 

```
[1,-5,-6,-1,-7,3]
4
```

The below solution cannot pass this test case but it is still be accepted. 

#### Code you used for Submit/Run operation

```python
from collections import deque
class Solution:
    def maxResult(self, nums: List[int], k: int) -> int:
        queue=deque([nums[0]],maxlen=k)
        # max sliding windows
        for i in range(1,len(nums)):
            cur=queue[0]+nums[i]
            queue.append(cur)
            while len(queue)>1 and (queue[0]<=cur or queue[0]<=queue[1]):
                queue.popleft()
        return queue[-1]
```

#### Language used for code

python3

#### Expected behavior

The above solution shall not be accepted.. 

#### Screenshots

![image](https://user-images.githubusercontent.com/1665437/178129519-e1ed3958-d08c-4bef-92ad-e796da4b837b.png)
![image](https://user-images.githubusercontent.com/1665437/178129583-55731d5b-ae33-435c-a53b-902eeb930e25.png)

#### Additional context

NA

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
