### ISSUE TITLE
Missing testcase for the problem 2337. Move Pieces to Obtain a String

### ISSUE THREAD

**Issue by reapedjuggler** [LeetCode-Feedback/LeetCode-Feedback#8108]
#### Your LeetCode username
reapedjuggler

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In today's Weekly Contest 301 for problem 3 wrong solutions are getting accepted because of this missing test case.
Testcase:
start string = ```"R____L"```
target string = ```"__LR__"```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
    bool canChange(string start, string target) {
        
        int n = start.length();
        
        int x = 0, y = 0, a = 0, b = 0;
        
        for (int i = 0; i < n; i++) {
            
            x += (start[i] == 'L');
            y += (start[i] == 'R');
            
            a += (target[i] == 'L');
            b += (target[i] == 'R');
            
        }

        if (x != a or y != b) return 0;
        
        for (int i = 0; i < n; i++) {

            if (start[i] == target[i]) continue;
            
            if (target[i] == 'L') {
                
                int j = i;
                
                while (j < n and start[j] == '_') j++;
                
                if (j == n or start[j] == 'R') return false;
                
                start[j] = '_';
                
                i = j - 1;
                
            }
            
        }
        
        for (int i = n - 1; i >= 0; i--) {

            if (start[i] == target[i]) continue;
            
            if (target[i] == 'R') {
                
                int j = i;
                
                while (j >= 0 and start[j] == '_') j--;
                
                if (j < 0 or start[j] == 'L') return false;
                
                start[j] = '_';
                
                i = j + 1;
                
            }
            
        }
        
        return 1;
        
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
This kind of solution should not be accepted as they fail on the test case above. 

#### Screenshots

![leetcode](https://user-images.githubusercontent.com/52465652/178133218-6fd68858-328d-49ad-8f74-3eabb3eefa3c.jpg)

#### Additional context
[Problem Description](https://leetcode.com/problems/move-pieces-to-obtain-a-string/)
A complete re-run of solutions should be done so that solutions that fail this test case should not be considered.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.All solutions are WA after handling the problem after the contest. We appreciate your support!

**Comment by reapedjuggler** [comment]
Thank you for your email, I also want to ask whether this contribution will
be reflected in my profile in near future? if yes then where I can see it :)
thank you
