### ISSUE TITLE
409. Longest Palindrome: Invalid testcase is not being reportes as invalid and gives wrong answer

### ISSUE THREAD

**Issue by artak-kirakosyan** [LeetCode-Feedback/LeetCode-Feedback#811]
#### Your LeetCode username

pythoff

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

When inserting invalid custom testcase, the program is not reporting invalid input and is giving invalid expected result

#### Code you used for Submit/Run operation

```
from collections import Counter
class Solution:
    def longestPalindrome(self, s: str) -> int:
        count = 0
        c = Counter(s)
        for i in c.values():
            count += i - i % 2
        if sum([i for i in c.values() if i % 2 == 1]) > 0:
            count += 1
        return count
```

#### Language used for code

python3

#### Expected behavior

I receive an incorrect expected result.
I was expecting to see "Invalid testcase"

#### Screenshots

![image](https://user-images.githubusercontent.com/23319356/90226704-7157f480-de24-11ea-8a91-65b617e522be.png)
![image](https://user-images.githubusercontent.com/23319356/90226678-643b0580-de24-11ea-8dbc-9c3fca82e0dd.png)

#### Additional context

The problem says that the input consists of lowercase and uppercase letters.
When any other type of symbol is present in the testcase, Invalid testcase error should be reported.

**Comment by lc-pam** [comment]
Hi @artak-kirakosyan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @artak-kirakosyan 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by artak-kirakosyan** [comment]
Hi @lc-pam ,

Thanks for your time and effort.
I confirm that the fix is there and it works as expected now.
