### ISSUE TITLE
Missing Test Case - 2337. Move Pieces to Obtain a String

### ISSUE THREAD

**Issue by Abhinav2207** [LeetCode-Feedback/LeetCode-Feedback#8112]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a missing test case. So wring solution is getting accepted.

#### Code you used for Submit/Run operation

```
// 2337. Move Pieces to Obtain a String
bool canChange(string s, string t) {
        int n=s.size(),i=0,j=0;
        while(i<n && j<n){
            while(i<n && s[i]=='_') i++;
            while(j<n && t[j]=='_') j++;
            if(s[i]!=t[j]) return false;
            if(s[i]=='L'){
                if(i<j) return false;
            }
            if(s[i]=='R'){
                if(j<i) return false;
            }
            i++,j++;
        }
        return true;
    }
```

#### Language used for code
C++ 

#### Expected behavior
The submitted code should not be accepted as it fails in one of the test case.

#### Screenshots

<img width="960" alt="image" src="https://user-images.githubusercontent.com/56033822/178144482-6199994b-b89b-460e-bf05-6cca165ef928.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Abhinav2207** [comment]
https://leetcode.com/submissions/detail/743373962/

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
