### ISSUE TITLE
Solution Needs Correction - 100. Same Tree

### ISSUE THREAD

**Issue by JellyGong** [LeetCode-Feedback/LeetCode-Feedback#8117]
#### Your LeetCode username
jgong

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The space complexity of the second approach(BFS) is not quite right.

#### Expected behavior

---------------Currently in the solution of a BFS approach---------------
Complexity Analysis
Space complexity : O(log(N) in the best case of completely balanced tree and O(N)in the worst case of completely unbalanced tree, to keep a deque.

-----------------------------What I expect---------------------------------
Completely Unbalanced Tree – O(1)
The tree is completely unbalanced and contains only 1 element at each level

Completely Balanced Tree – O(n)
BFS will have to store at least an entire level of the tree in the queue. With a perfect fully balanced binary tree, this would be (n/2 + 1) nodes (the very last level).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem.  We appreciate your support!
