### ISSUE TITLE
BLOCKED - Issue with judge - 633. Sum of Square Numbers

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#812]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language

#### Description of the bug

633. Sum of Square Numbers
https://leetcode.com/problems/sum-of-square-numbers/

There is an issue with judge, for above question

For the same input:
- `Run Code` passes  (on right-bottom)
- But `Submit` fails (on left-top)

![1](https://user-images.githubusercontent.com/8236389/90259189-3d51f300-de67-11ea-8810-7d4748399502.png)

Now, my score card looks bad due to above issue:

![2](https://user-images.githubusercontent.com/8236389/90259236-5064c300-de67-11ea-89b9-38e3e7501510.png)

Please do the below:
1. Make the problem Medium/ Hard.
2. My `Acceptance Rate` got low due to 4 TLE/ 1 wrong answer. Please delete these 5 submissions, so that it goes back to normal, like before the problem.
3. Fix the judge

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

1. `Run Code` pass should be `Submit` pass.
2. LeetCode should not penalize the user's profile with poor `Acceptance Rate` - when there is an issue with Judge. Please delete my bad/TLE/WA submissions.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. When you click on "Run Code", it only runs 1 test case per time. When you click on "Submit", it runs all of the test cases at once. If your code is not optimized for time complexity, it can still pass "Run Code" but it might fail "Submit". The test case you see at the "details" page shows which test case the program stops running at when the time limit has exceeded; it's not a test case that causes your program to exceed the time limit.

**Comment by manoharreddyporeddy** [comment]
Related:
Why this happens - https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1053
