### ISSUE TITLE
Javascript TypeError - 117. Populating Next Right Pointers in Each Node II

### ISSUE THREAD

**Issue by hsywhu** [LeetCode-Feedback/LeetCode-Feedback#8124]
#### Your LeetCode username

hsywhu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Problem No.117 reports TypeError for Javascript, while the same code can pass all tests under TypeScript.

There are also several discussions about the issue in the Discuss section https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/discuss/2167737/Javascript-Test-case-TypeError

#### Code you used for Submit/Run operation

```
/**
 * @param {Node} root
 * @return {Node}
 */
var connect = function(root) {
    if (!root)
        return root;
    const toGo = [[root, 0]];
    
    while (toGo.length) {
        const cur = toGo.shift();
        
        if (cur[0].left)
            toGo.push([cur[0].left, cur[1] + 1]);
        if (cur[0].right)
            toGo.push([cur[0].right, cur[1] + 1]);
        
        if (toGo.length && cur[1] === toGo[0][1]) {
            cur[0].next = toGo[0][0];
        }
    }

    return root;
};
```

#### Language used for code

Javascript

#### Expected behavior

The code should run without reporting TypeError

#### Screenshots

![image](https://user-images.githubusercontent.com/15964179/178185431-58b5656a-e6aa-4c4c-8558-0ca422d6e58e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

Sorry for the late reply.

The issue should be fixed. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
