### ISSUE TITLE
Missing Test Case (problem #164)

### ISSUE THREAD

**Issue by Kshitij68** [LeetCode-Feedback/LeetCode-Feedback#8128]
Leetcode Username: kmathur68

#### Category of the bug
Question: 164: Maximum Gap
Language: English
Issue type: Missing Test case

#### Description of the bug
There is an expectation that the solution should work in linear time with linear space. 
When I use counting sort, we get a Memory Limit Exceeded, so it works as expected.

However, when we use the simple bucket sort strategy, the solution passes without giving any timeout.
A simple bucket sort algorithm, only works in linear time, if the data distribution is uniform. if this is not the case, then it can take O(nlogn) in the worst case. 
It seems like all test cases are one of two categories
- Size of array is much lower than upper limit (10^5)
- The data in array is uniformly distributed -> This assumption is not mentioned anywhere in the question

```
        # Ensure only unique elements
        nums = list(set(nums))
        
        # If less than 2 nums, return 0
        if len(nums) < 2:
            return 0
    
        # let us find max value so all elements can be set between 0 and 1
        max_val = max(nums)
        b_array = [list() for i in range(len(nums))]
        for num in nums:
            index = int(num/max_val)
            # add elements in the bucket sort
            b_array[index].append(num)

        result = list()
        # Sort the bucket individually and add them to the result
        for index in range(len(b_array)):
          # if all elements are same except one of them, then it will end up O(nlogn)
            b_array[index].sort()
            for i in range(len(b_array[index])):
                result.append(b_array[index][i])
        
        diff = 0
        for i in range(1,len(result)):
            diff = max(diff, result[i] - result[i-1])
```

#### Language used for code
Python3

#### Expected behavior
Addtional test case like [1,1,1,1..] (10^9 times) + [2] -> This should lead to Time Limit exceeded as solution is going to be same as Merge sort

#### Screenshots
None

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test case suggested is invalid.We appreciate your support!
