### ISSUE TITLE
`Regular Expression Matching` Problem is Unclear 

### ISSUE THREAD

**Issue by avinashdhinwa** [LeetCode-Feedback/LeetCode-Feedback#8129]
#### Your LeetCode username
avinashdhinwa

#### Category of the bug
- [x] [Question](https://leetcode.com/problems/regular-expression-matching/)

#### Description of the bug
From the problem statement, it is a bit unclear to me what is expected, since the output of the following cases doesn't make sense to me according to the question

"aab"
"c*a*b" 
expects true

but 
"ab"
".*c"
expects false

Also,
"ab"
".*"
expects answer to be true

#### Code you used for Submit/Run operation

```
func isMatch(s string, p string) bool {
    
    for i := 0; i < len(p); i++ {
        if !isChar(p[i]) {
            continue
        }
        ans := areMatching(s, 0, p, i)
        if ans {
            return ans
        }
    }
    
    return false
}

func areMatching(s string, i int, p string, j int) bool {
    
    fmt.Printf("matching %s with %s \n", s[i:], p[j: ])
    
    if i == len(s) {
        return true
    } else if j == len(p) {
        return false
    }
    
    if isChar(p[j]) {
        if !areEqual(s[i], p[j]) {
            return false
        }
        return areMatching(s, i+1, p, j+1)
    }
    
    // it is *
    if !areEqual(s[i], p[j-1]) {
        // this means * represents zero character
        return areMatching(s, i, p, j+1)
    }
    
    return areMatching(s, i+1, p, j+1) || areMatching(s, i+1, p, j)    
}

func areEqual (c1, c2 byte) bool {
    if c1 == '.' || c2 == '.' {
        return true
    } 
    return c1 == c2
}

func isChar (c byte) bool {
    if (c >= 'a' && c <= 'z') || c == '.' {
        return true
    }
    return false
}
```

#### Language used for code

Go

#### Expected behavior

1.
"aab"
"c*a*b" 
Expected: true

2. 
"ab"
".*c"
Expected: false

3.
"ab"
".*"
Expected: true

I feel, either 1 should also be false, that would make sense for 2 be false as well. Else, 2nd should also be true. Else, there should be more explanation added to the question I feel.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
