### ISSUE TITLE
Invalid Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by ExpertKiD** [LeetCode-Feedback/LeetCode-Feedback#8130]
Case:

Input: 1534236469
Expected: 0
Output: 9646324315

The output is correct because `1534236469 < 2^31 -1`. The expected range of x is `-2^31 <= x <= 2^31 -1`. So, why is it expecting a `0` when clearly `1534236469 < 2^31 -1`. 

Similary, if you mean int32 only datatype, then wouldn't the ideal range be `[-2^16, 2^16-1]` if 64-bit integers are not allowed and the int type is constrained to int32.

Constraints: `x` belongs to `[-2^32, 2^32-1]`

Solution:

```go

import (
	"fmt"
	"math"
)

func reverse(x int) int {
	if x > math.MaxInt32 || x < math.MinInt32 {
		return 0
	}

	var number int = x
	var reverse int = 0

	for number != 0 {
		reverse = reverse*10 + number%10
		number = number / 10
	}

	return reverse
}

func printReverse(x int) {
	fmt.Println(fmt.Sprintf("Number: %d\tReverse: %d", x, reverse(x)))
}

func Problem7() {
	printReverse(123)
	printReverse(math.MaxInt32 + 1)
	printReverse(-123)
	printReverse(120)
	printReverse(1534236469)

	print(math.MaxInt32)
	print(math.MinInt32)

}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment]
If reversing x causes the value to go outside the signed 32-bit integer range, then return 0.

Please read this statement carefully.

**Comment by ExpertKiD** [comment]
I am using Golang as a language.

If reversing `x` causes the value to go outside the signed 32-bit integer range `[-2^31, 2^31 - 1]`, then return 0. Is `1534236469 < 2^31 -1` predicate not true?

**Comment by LC-Pam** [comment]
Thank you for your time. 
Please consider Stromsunshine's comment as the reference. 
We appreciate your support!
