### ISSUE TITLE
Missing Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by bvidalr1856** [LeetCode-Feedback/LeetCode-Feedback#8133]
#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
var checkIfExist = function(arr) {
    let b = false;
    for(let i = 0; i < arr.length; i++){
        for(let j = 0; j < arr.length;j++){
            if(arr[j] == arr[i]*2){
                b = true;
                break;
            }
        }
    }
    return b;
};
```

####
![imagen](https://user-images.githubusercontent.com/104508964/178327881-c6a89996-2c7a-416e-9210-c76353c27a80.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
