### ISSUE TITLE
Eventhough the runtime is correct, it takes it as different value after submission

### ISSUE THREAD

**Issue by sureshpalemoni** [LeetCode-Feedback/LeetCode-Feedback#8134]
<img width="1410" alt="Screen Shot 2022-07-11 at 10 13 59 PM" src="https://user-images.githubusercontent.com/16357895/178330730-9c3dcb27-ef2e-4aaf-91eb-41fdce46ec85.png">

#### Your LeetCode username
sureshpalemoni

#### Category of the bug
- [x] Solution

#### Code you used for Submit/Run operation

```
class Solution:
    ans = []
    count = 0
    def isSubsequence(self, s: str, t: str) -> bool:
        if len(s) == 0:
            return True
        temp_t = t
        for i in s:
            temp_t = self.stripchars(i,temp_t)
            if temp_t == None:
                return False
        if self.ans == sorted(self.ans):
            return True
        return False

    def stripchars(self, k, temp):
        for i,j in enumerate(temp):
            if self.count == 0:
                if j == k:
                    self.ans.append(i)
                    self.count =+ 1
                    return temp[i+1:]
            if j == k:
                self.ans.append(self.ans[-1]+i+1)
                return temp[i+1:]
        return None
                
    
```

**Comment by ampanasiuk** [comment]
I think setting ans=0 count=0 at the top of isSubsequence will fix the problem.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
