### ISSUE TITLE
Missing Test Case - 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by ampanasiuk** [LeetCode-Feedback/LeetCode-Feedback#8135]
#### Your LeetCode username
Movely

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I realized my previous submission, which got accepted, is buggy. Submission https://leetcode.com/submissions/detail/575825473/

#### Code you used for Submit/Run operation
```
# failing input: [1,2,0]

class Solution:
    def rightSideView(self, root: Optional[TreeNode]) -> List[int]:
        res = []
        q = [root]
        while any(q):
            res.append(None)
            nq = []
            for v in q:
                if not v:
                    continue
                if not res[-1]:
                    res[-1] = v.val
                nq.append(v.right)
                nq.append(v.left)
            q = nq
        return res
```

#### Language used for code
Python3

#### Expected behavior
Submission of the code should be rated WA

#### Additional context
Failing test case: [1,2,0]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
