### ISSUE TITLE
1528. Shuffle String - Incorrect Example.

### ISSUE THREAD

**Issue by aaronedwards2193** [LeetCode-Feedback/LeetCode-Feedback#8142]
#### Your LeetCode username
aaronedwards2193

#### Category of the bug
- [ 1528] Question
- [ ] Solution
- [ C#] Language
- [ ] Missing Test Cases 

#### Description of the bug
The leetcode example is incorrect with the indexes. 

The example given is below, but the indexes are incorrect.

Input: s = "codeleet", indices = [4,5,6,7,0,2,1,3]
Output: "leetcode"
Explanation: As shown, "codeleet" becomes "leetcode" after shuffling.

Index 2 and 1 above are incorrect. This spells out "leetcdoe" when put together with your example.

#### Code you used for Submit/Run operation

```
public class Solution {
    public string RestoreString(string s, int[] indices) {
        s.ToCharArray();
        string x = null;
        for(int i = 0; i < indices.Length; i++)
        {
                x = x + s[indices[i]];
            
        }
        return x;
    }
}
```

#### Language used for code
C#

#### Expected behavior
Correct example cases.

#### Screenshots
N/A

#### Additional context
N/A

**Comment by stormsunshine** [comment]
Your understanding is incorrect. Could you please check the problem description?

Suppose the output is t, then s[0] = t[4], s[1] = t[5], s[2] = t[6], s[3] = t[7], s[4] = t[0], s[5] = t[2], s[6] = t[1], s[7] = t[3].

Do you think t is "leetcdoe"?

**Comment by aaronedwards2193** [comment]
Ah. I did misunderstand. I took a look at the diagram again. Apologies!
