### ISSUE TITLE
incomplete information in question- 969. Pancake Sorting

### ISSUE THREAD

**Issue by pranav560** [LeetCode-Feedback/LeetCode-Feedback#8144]
#### Your LeetCode username
 jimm_jamm_candy

#### Category of the bug
- [ ] Question
- [ ] Language

#### Description of the bug
it is not mentioned in the question that given arr is a permutation of numbers from 1 to n

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
