### ISSUE TITLE
https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/692/challenge-problems/4426/

### ISSUE THREAD

**Issue by mpechner** [LeetCode-Feedback/LeetCode-Feedback#8145]
#### Your LeetCode username

mpechner

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/692/challenge-problems/4426/
Missing video

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
