### ISSUE TITLE
Examples' Output Type Misleading - 792. Number of Matching Subsequences

### ISSUE THREAD

**Issue by John-K408** [LeetCode-Feedback/LeetCode-Feedback#8146]
#### Your LeetCode username
 
John-K408

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the examples for the problem, the output type is a List<List<TreeNode>> but the method signature provided returns just a List<TreeNode>. This makes it difficult to understand what the problem is looking for. I thought each disjoint part of the tree formed a new list and all lists were to be put into one big list and returned.

#### Code you used for Submit/Run operation

```
N/A
```

#### Language used for code

N/A

#### Expected behavior

I expected the output in the examples to be just a list made of numbers which represent the value of nodes (we assume every number is a node and not just an int).

#### Screenshots

N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The output is an integer in the examples and function signature. We appreciate your support!
