### ISSUE TITLE
Bad description on grid illumination

### ISSUE THREAD

**Issue by r41p41** [LeetCode-Feedback/LeetCode-Feedback#815]
problem : 1001. Grid Illumination
https://leetcode.com/problems/grid-illumination/ 

#### Your LeetCode username
r41p41

#### Category of the bug
- [ x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Please add more data to the description to have a clear context on the problem.
It seems the wording is incorrect in grid illumination problem w.r.t. semantics/implication
"""
On a N x N grid of cells, each cell (x, y) with 0 <= x < N and 0 <= y < N has a lamp.

Initially, some number of lamps are on.  lamps[i] tells us the location of the i-th lamp that is on.  Each lamp that is on illuminates every square on its x-axis, y-axis, and both diagonals (similar to a Queen in chess).

For the i-th query queries[i] = (x, y), the answer to the query is 1 if the cell (x, y) is illuminated, else 0.

After each query (x, y) [in the order given by queries], we turn off any lamps that are at cell (x, y) or are adjacent 8-directionally (ie., share a corner or edge with cell (x, y).)

Return an array of answers.  Each value answer[i] should be equal to the answer of the i-th query queries[i].
"""

As per the description, " After each query (x, y) [in the order given by queries], we turn off any lamps that are at cell (x, y) or are adjacent 8-directionally (ie., share a corner or edge with cell (x, y).)  " it is evident that (x,y) query after completion will turn off the lamp at (x,y) and x+1,y : x,y+1 : x+1,y+1 : x-1,y : x,y-1 : x-1,y-1 : x-1,y+1 : x+1,y-1
However in case when lamps 0,0 and 4,4 are on, query 1,1 should remove 1,1 0,0 0,1 and 1,0 from the matrix. Which is not correct according to the tests i performed. It seems that removal of 0,0 and 1,1 from the matrix (because of 1,1 query) still keeps it in the matrix because of existence of 4,4 (either because of recalibration or something else) Which is not in any way in the description as per logical progression of text. Kindly fix this, so people don't have to wander around in discussions to find 1 out of 1000 posts which actually describe the issue rather than just posting a solution.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> gridIllumination(int N, vector<vector<int>>& lamps, vector<vector<int>>& queries) 
    {
        vector<int> res;
        vector<int> blacklist;
        for(auto &query : queries)
        {
            int t_res = 0;
            if((query[0] >= 0 && query[0] < N) 
               || (query[1] >= 0 && query[1] < N))
            {
                for(auto &lamp : lamps)
                {

                    if(query[0] == lamp[0] || query[1] == lamp[1])
                    {
                        t_res = 1;
                        break;                            
                    }
                    if(abs(query[0]-lamp[0]) == abs(query[1]-lamp[1]))
                    {
                        t_res = 1;
                        break;
                    }
                }
                if(t_res)
                {
                    for(int i=0; i < blacklist.size(); i+=2)
                    {
                        if(query[0] == blacklist[i] || query[1] == blacklist[i+1])
                        {
                            t_res = 0;
                            break;                            
                        }
                        if(abs(query[0]-blacklist[i]) == abs(query[1]-blacklist[i+1]))
                        {
                            t_res = 0;
                            break;
                        }
                    }

                }
            }
            blacklist.push_back(query[0]);
            blacklist.push_back(query[1]);
            res.push_back(t_res);
        }
        return res;
    }
};
```

#### Expected behavior

According to the description

following test case should have [1,0] as the output since 1,1 *WAS REMOVED* from the grid as per " After each query (x, y) [in the order given by queries], we turn off any lamps that are at cell (x, y) or are adjacent 8-directionally (ie., share a corner or edge with cell (x, y).) "
however it is not so

5
[[0,0],[4,4]]
[[1,1],[1,1]]

yields [1,1] as the output instead of [1,0]

**Comment by lc-pam** [comment]
Hi @r41p41 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @r41p41 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
