### ISSUE TITLE
Error in Video Solution Illustrating Binary Placement (2^2 Missing)

### ISSUE THREAD

**Issue by Githubbubber** [LeetCode-Feedback/LeetCode-Feedback#8151]
#### Your LeetCode username

Githubbubber

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I noticed in [the video solution for "1342. Number of Steps to Reduce a Number to Zero"](https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/692/challenge-problems/4425/) that [at ~04:58](https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/692/challenge-problems/4425/) seconds the third binary placement from the right is incorrect: The place name needs to be 2^2. It is nothing pressing but may trip ppl new to binary up.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

The placement label for 2^2 to be shown in the video solution.

#### Screenshots

![](https://raw.githubusercontent.com/Githubbubber/images/main/2_missing.jpg)

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
