### ISSUE TITLE
3Sum problem:-  Mistake in example-1, explanation part

### ISSUE THREAD

**Issue by jaibabbar08** [LeetCode-Feedback/LeetCode-Feedback#8153]
Mistake in example-1, explanation part:  written (nums[0] + nums[1] + nums[1] = (-1) + 0 + 1 = 0.) instead of ( nums[0] + nums[1] + nums[2] = (-1) + 0 + 1 = 0.)
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
