### ISSUE TITLE
Poorly Worded Question/Missing examples to clarify - 1221. Split a String in Balanced Strings

### ISSUE THREAD

**Issue by stevenhgs** [LeetCode-Feedback/LeetCode-Feedback#8155]
#### Your LeetCode username
stevenhgs

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description of [problem 1221](https://leetcode.com/problems/split-a-string-in-balanced-strings/) reads: 
_Balanced strings are those that have an equal quantity of 'L' and 'R' characters.
Given a balanced string s, split it in the maximum amount of balanced strings.
Return the maximum amount of split balanced strings._

In this description it is not clear that the split balanced strings should form the given balanced string.

For example the answer for "RLRRRLLRLL" is 2. The string can be split in "RL" and "RRRLLRLL". 
However, if the split balanced strings do not have to add up to the given balanced string then "RLRRRLLRLL" can be split in "RL" (starting at index 0), "RL" (starting at index 4) and "LR" (starting at index 6). So the given string can be split in 3 balanced strings.

Since the maximum amount of split balanced strings needs to be returned I expected that the answer would be 3, but the expected answer is 2.

#### Code you used for Submit/Run operation
Code is irrelevant for this issue.

#### Language used for code
Language is irrelevant for this issue.

#### Expected behavior
The given expected answer for "RLRRRLLRLL" is 2, but reading the description I expected it to be 3.
Maybe add an example where it is clear that the split balanced strings should add up to the given balanced string.

#### Additional context
This issue was already opened [here](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/411).  The issue back then was closed because of the following reason: _After our discussion with the team, we decided not to update the problem statement. As the users should be able to tell all characters must be used in order from example 4_. However, it seems like there is no longer an example 4 for [this problem](https://leetcode.com/problems/split-a-string-in-balanced-strings/).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
