### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by markhemans** [LeetCode-Feedback/LeetCode-Feedback#8156]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

missing test case for single digit integers

#### Code you used for Submit/Run operation

```
/**
 * @param {number} x
 * @return {boolean}
 */
function isPalindrome (x) {
    if (x<0 || (x % 10 == 0 && x!=0))
        {
            return false;
        }
    
    if (x<10)
        {
            return true;
        }
    
    let reversedNumber = 0;
    while (x>reversedNumber)
        {
            reversedNumber = Math.floor((reversedNumber * 10) + x % 10);
            x = Math.floor((x/10));
        }
    
    return (x == reversedNumber || x == Math.floor(reversedNumber/10));
};
```

#### Expected behavior

I expected single digit integers to return true but instead they returned false. My code accounts for integers less than 10 to return true.

**Comment by stormsunshine** [comment]
Your code returns true for single digit integers. Where do you see the code returns false?

**Comment by markhemans** [comment]
in the leetcode example
