### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by AbhishekRanjan624** [LeetCode-Feedback/LeetCode-Feedback#8158]
class Solution {
    public int maxProfit(int[] prices) {
        int min=prices[0] ;
        int profit=0 ;
        int maxprofit=0 ;
        
        for(int SharePrice : prices){
            min=Math.min(min , SharePrice) ;
            profit=SharePrice-min ;
            maxprofit=Math.max(maxprofit ,profit) ;
        }
        
        return maxprofit ;
    }
}

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
