### ISSUE TITLE
correct answer fails tests -- nextPermutation

### ISSUE THREAD

**Issue by marchingband** [LeetCode-Feedback/LeetCode-Feedback#8159]
#### Your LeetCode username

marchingband

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This is a correct answer but fails tests.
Running in Node, it yields the right answer to the test cases which fail in Leetcode

Input
[1,3,2]
Output
[2,3,1]
Expected
[2,1,3]

#### Code you used for Submit/Run operation

```
var nextPermutation = function(nums) {
    for(var i=nums.length-1; i>0 ;i--){
        if(nums[i] > nums[i-1]){
            var temp = nums[i-1]
            var min = Infinity
            var index = 0
            for(var j=i; j<nums.length; j++){
                if((nums[j] < min) && (nums[j] > temp)){
                    min = nums[j]
                    index = j
                }
            }
            nums[i-1] = min
            nums[index] = temp
            return nums.slice(0,i).concat(nums.slice(i).sort())
        }
    }
    return nums.sort()
};
```

#### Language used for code

Java Script

#### Expected behavior

This is a correct answer but fails tests.
Running in Node, it yields the right answer to the test cases which fail in Leetcode

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by marchingband** [comment]
https://leetcode.com/problems/next-permutation

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
