### ISSUE TITLE
Python times out but Java and C++ work fine.

### ISSUE THREAD

**Issue by coda-nsit** [LeetCode-Feedback/LeetCode-Feedback#816]
The question I am talking about is: https://leetcode.com/contest/weekly-contest-202/problems/minimum-number-of-days-to-eat-n-oranges/

As can be seen this was a contest question. During the contest I used Python to solve this problem and got TLE. However, when I submitted later using CPP I got an AC. Kindly increase the time limit for Python as the TLE is very misleading specially during the contests. It makes people think that the algorithm itself is flawed or suboptimal which was clearly not the case here. At least add a disclaimer saying that the question needs to be solved using Java or CPP.

Following are my Python and CPP submissions.
Python: https://leetcode.com/contest/weekly-contest-202/submissions/detail/381541882/
CPP: https://leetcode.com/submissions/detail/381633320/

**Comment by lc-pam** [comment]
Hi @coda-nsit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @coda-nsit 
Thank you for your time. The team has reviewed your report and recommended you refer to the [problem's discussion tab](https://leetcode.com/problems/minimum-number-of-days-to-eat-n-oranges/discuss/?currentPage=1&orderBy=hot&query=) to see other people solutions. We appreciate your support!
