### ISSUE TITLE
Proof for solution 1 of problem 797

### ISSUE THREAD

**Issue by mallika-b** [LeetCode-Feedback/LeetCode-Feedback#8164]
#### Your LeetCode username

mallikab

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For complexity analysis, this: "With the newly-added node, new paths could be created by preceding all previous paths with the newly-added node, as illustrated in the following graph." readily proves a lower bound, but perhaps more diagrams/explanation is needed on why this is an exact bound?

For space complexity:
"the space we need to store the results would be \mathcal{O}(2^N \cdot N)O(2 N ⋅N)."
the space needed to store results should not be included 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!（Besides what was suggested in this ticket, we also adjusted the python code in its naming style and replace deque with list (stack). Also added C++ codes )
