### ISSUE TITLE
对于204题-leetcode官方给出的埃氏筛题解的优化（内存消耗方面）

### ISSUE THREAD

**Issue by Y-nk-FE** [LeetCode-Feedback/LeetCode-Feedback#8165]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
用户名：Jolly JenningsHee
邮箱:3276609647@qq.com
填写你登录 LeetCode（中国区）的用户名

题目序号：204
题目名称：计数质数
题目内容：给定整数 n ，返回 所有小于非负整数 n 的质数的数量 。

【bug】--无
【编译语言】--C++
【目的】--优化内存消耗（int改为bool，大大减小内存消耗）,其余基本无改动

代码实现如下：
class Solution {
public:
    int countPrimes(int n) {
        //注意题目，所给题目是小于n的，所以并不包含n，在申请内存和确定循环边界的时候需要注意知否对n取等
        //采用bool类型的变量可以大大减小内存的消耗，仅是int类型的1/4
        vector<bool> isPrime(n,1);
        int ans=0;
        //质数从2开始，所以注意循环的起点
        for(int i=2;i<n;i++){
            if(isPrime[i]){
                ans++;
                if((long long)i*i<n){
                    for(int j=i;j<n;j+=i){
                        isPrime[j]=0;
                    }
                }
            }
        }
        return ans;
    }
};

**Comment by Y-nk-FE** [comment]
代码实现有缺漏，重新给上代码
class Solution {
public:
    int countPrimes(int n) {
        //注意题目，所给题目是小于n的，所以并不包含n，在申请内存和确定循环边界的时候需要注意知否对n取等
        //采用bool类型的变量可以大大减小内存的消耗，仅是int类型的1/4
        vector<bool> isPrime(n,1);
        int ans=0;
        //质数从2开始，所以注意循环的起点
        for(int i=2;i<n;i++){
            if(isPrime[i]){
                ans++;
                if((long long)i*i<n){
                    for(int j=i;j<n;j+=i){
                        isPrime[j]=0;
                    }
                }
            }
        }
        return ans;
    }
};

**Comment by BrambleWave** [comment]
感谢您的反馈，您的建议已转交官方题解团队，我们会根据实际情况考虑是否进行调整，谢谢您的支持
