### ISSUE TITLE
Missing Test Case - 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by scur-o** [LeetCode-Feedback/LeetCode-Feedback#8172]
#### Your LeetCode username
scur

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
My solution came out correct, even though it shouldn't.

mid = r-l//2
and
mid = r-1//2

shouldn't have worked in my solution, but it did.. (i meant to write mid = (r-l)//2). After i changed to the corrected mid, the time exceed and solution failed

#### Code you used for Submit/Run operation

```
class Solution:
    def searchRange(self, nums: List[int], target: int) -> List[int]:
   
        l, r = 0, len(nums) - 1
        
        while l <= r:
            mid = r-1//2
            if target > nums[mid]: l = mid + 1
            elif target < nums[mid]: r = mid - 1
            else:
                
                while nums[l] != nums[r]:
                    if nums[l] == target: r -= 1
                    elif nums[r] == target: l += 1
                return [l, r]
        return [-1, -1]
```

#### Expected behavior

Initially I was happy I got the problem correct, but upon further debugging of test cases I realized my solution should have yielded an error. both mid = r-1//2 and mid = r-l//2 surprisingly passed the test cases. When I corrected the mid variable to (r-1)//2. the solution failed.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
