### ISSUE TITLE
Java- 100% fast. Easy to understand.

### ISSUE THREAD

**Issue by sumanth-reddy13** [LeetCode-Feedback/LeetCode-Feedback#8178]
class Solution {
    public int sumOfUnique(int[] nums)
    {
        int[] freq = new int[101];
        
        for(int i:nums)
        {
            freq[i]++;
        }
        int sum=0;
        for(int i=0;i<101;i++)
        {
            if(freq[i]==1)
            {
                sum+=i;
            }
        }
        return sum;
    }
}

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your solution to the team. We appreciate your support!
