### ISSUE TITLE
提交出错

### ISSUE THREAD

**Issue by NgChiKin** [LeetCode-Feedback/LeetCode-Feedback#818]
** Bug 类型**
- [ ] 题目
- [√ ] 题解
- [ ] 编程语言

**描述**
这组  [2,3,5], 8  测试用例. 
我的输出值,比预期值多了一个 [2,2,3] [ 7 ] ,我不明白这个  7  怎么出来的 代码里 没有 加法 的操作. 而且同样的代码和测试用例
在我的浏览器和 用你们 平台的执行代码功能 运行出来的结果 是正确的.

**你使用的语言**
Javascript

**你提交或者运行的代码**
```
// combination-sum
/**
 * @param {number[]} candidates
 * @param {number} target
 * @return {number[][]}
 */
    let res = []

    const generateCombin = (candidates, target, p, start) => {
      if (target == 0) {
        res.push([...p])
        return
      }

      for (let i = start; i < candidates.length; i++) {
        p.push(candidates[i])
        let curValue = target - candidates[i]
        if (curValue >= 0) {
          generateCombin(candidates, curValue, p, i)
        }
        p.pop()
      }
      return
    }

    var combinationSum = function (candidates, target) {

      generateCombin(candidates, target, [], 0)

      return res
    };
   console.log(combinationSum([2, 3, 5], 8));
```

**期望行为**
[[2,2,2,2],[2,3,3],[3,5]]

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/57823909/90332551-5803a380-dff0-11ea-80f4-e0ad2a1b3664.png)
![image](https://user-images.githubusercontent.com/57823909/90332565-75387200-dff0-11ea-8332-ac5ba1c4c60d.png)
![image](https://user-images.githubusercontent.com/57823909/90332575-86817e80-dff0-11ea-8231-519e878cc0de.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至 [力扣圈子](https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=) 进行题目交流，以获得更好的支持哟～
