### ISSUE TITLE
Missing Test Case - 2206. Divide Array Into Equal Pairs

### ISSUE THREAD

**Issue by shanovskyi-b** [LeetCode-Feedback/LeetCode-Feedback#8193]
#### Your LeetCode username

shanovskyi_b

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

There's a hacky Java solution with `xor`s that passes the tests:
```
class Solution {
    public boolean divideArray(int[] nums) {
        int xor1=0;
        int xor2=0;
        for(int x: nums)
        {
          xor1^=x;
          xor2^=-x;
        }
        return xor1==0 && xor2==0;
    }
}
```

But it should fail for example for `nums = [3,1,5,7]` and it fails if you try it with "Run Code")

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean divideArray(int[] nums) {
        int xor1=0;
        int xor2=0;
        for(int x: nums)
        {
          xor1^=x;
          xor2^=-x;
        }
        return xor1==0 && xor2==0;
    }
}
```

#### Language used for code

Java

#### Expected behavior

This solution should not be accepted

#### Screenshots

![image](https://user-images.githubusercontent.com/18092448/178998885-1ca46ef2-ec0f-49c6-ab18-a061a01dbe47.png)

![image](https://user-images.githubusercontent.com/18092448/178999167-b8fbfcd2-315d-4332-bfe4-89dd80ae8b3a.png)

#### Additional context

Found this solution in this discussion and tried it - https://leetcode.com/problems/divide-array-into-equal-pairs/discuss/2263826/O(1)-space-and-O(n)-time-complexity-one-pass-solution-Java
(thanks to an author)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
