### ISSUE TITLE
Incorrect solution text in 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by solamen2** [LeetCode-Feedback/LeetCode-Feedback#8199]
#### Your LeetCode username
ed_younskevicius

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution has incorrect language in several places, most notably regarding sets and maps. I'm guessing this is because the solutions used to use sets and maps and at some point were optimized to use char arrays instead, but nobody went back and updated the solution text.

Solution 1:  This text is all incorrect, because no set is used in the Java solution (or any other solution I believe): "To check if one string has duplicate characters, we can use a set. We iterate through all the characters in the string and put them into the set one by one. Before putting one character, we check if the set already contains it. If so, we return false. After the loop, we return true."

Also, the space complexity given in solution 1, "O(min(n, m))", is incorrect. It is clearly O(m) in the solution as written now.

Solution 2: This text is also incorrect, and in a worse way because it refers to a HashSet which is not part of the standard library of the languages in the other two solutions: "By using HashSet as a sliding window, checking if a character in the current can be done in O(1)O(1).

...

Back to our problem. We use HashSet to store the characters in current window [i, j)[i,j) (j = ij=i initially). Then we slide the index jj to the right. If it is not in the HashSet, we slide jj further. Doing so until s[j] is already in the HashSet. At this point, we found the maximum size of substrings without duplicate characters start with index ii. If we do this for all ii, we get our answer."

Again, the space complexity given in solution 2, "O(min(n, m))", is incorrect. It is clearly O(m) in the solution as written now.

Solution 3: The time complexity says "Time complexity : O(n)O(n). Index jj will iterate nn times." But none of the solutions use any variable called "j". Probably it should read "right".

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior
N/A

#### Screenshots
N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by solamen2** [comment]
I don't see any of the changed text in the article currently. Maybe it takes time to update?

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We rewrote some parts:

Change all codes to HashSet version and verify all solutions (except for approach 1) can pass all tests.
Add the missing C++ solution in approach 3.
Adjust the article structure and add an overview section and some intuitions.
Leave the hash map implementation by int array as the last section.

We appreciate your support!

**Comment by solamen2** [comment]
Thanks for responding. I see currently that solution 1 in Java does use a HashSet now, which is good. Solution 3's text was updated to say that a HashMap/HashSet was no longer required, and why that was true, and this is also good. Solution 2 in Java still doesn't use HashSet, contrary to the solution text, so that solution is incorrect still. Solution 2 uses HashMaps. Also the space complexities are still wrong in solutions 2 and 3 (or more precisely, they are still very misleading).
