### ISSUE TITLE
Solution Bug- Solution missing

### ISSUE THREAD

**Issue by garimasingh128** [LeetCode-Feedback/LeetCode-Feedback#82]
**What kind of the bug**
- [ ] problem
- [.] solution
- [ ] language

**Describe the bug**
1074. Number of Submatrices That Sum to Target
Solution missing for above problem.

**what language is your code written in**
C++

**Comment by CooperCooperCooper** [comment]
Hi @garimasingh128,
Thank you for reaching out to us! I've relayed this issue to our team and request to prioritize adding solution to this problem as soon as possible. We appreciate your time and support. If you have any other requests, please don't hesitate to let us know.
