### ISSUE TITLE
40题, 组合总和 II 提交又出错

### ISSUE THREAD

**Issue by NgChiKin** [LeetCode-Feedback/LeetCode-Feedback#820]
** Bug 类型**
- [ ] 题目
- [√ ] 题解
- [ ] 编程语言

**描述**
提交时 的结果乱输出, 用 执行代码功能 执行相同的用例 结果正确 
**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
// combination-sum-ii
    let res = []
    const generateCombin = (candidates, target, p, start) => {
      if (target == 0) {
        res.push([...p])
        return
      }

      for (let i = start; i < candidates.length; i++) {
        let curValue = target - candidates[i]

        if (curValue < 0) break

        if (i > start && candidates[i - 1] == candidates[i]) continue;

        p.push(candidates[i])
        generateCombin(candidates, curValue, p, i + 1)
        p.pop()

      }
      return

    }

    var combinationSum2 = function (candidates, target) {

      candidates = candidates.sort((a, b) => a - b)

      generateCombin(candidates, target, [], 0)
      return res
    };
```

**期望行为**
输出结果为 
[[1,2,2],[5]]

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/57823909/90338016-28b55c80-e019-11ea-9bc4-6e3f4c5fdfe2.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。 后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至  [力扣圈子](https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=)  进行题目交流，以获得更好的支持哟～
