### ISSUE TITLE
973. K Closest Points to Origin - process exited with signal SIGSEGV error

### ISSUE THREAD

**Issue by shinhaena-stella** [LeetCode-Feedback/LeetCode-Feedback#8200]
#### Your LeetCode username
shinhaena

#### Category of the bug
- [ ] Question
- [0] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Have a run time error when I submit the solution
Runtime Error Message:
process exited with signal SIGSEGV

#### Code you used for Submit/Run operation

```
var kClosest = function(points, k) {
 
  const find = (arr, num) => {
    let left = [];
    let right = [];
    let equal = [];
    const dist = (pt) => pt[0] ** 2 + pt[1] ** 2;
    // const dist = (pt) => Math.pow(pt[0], 2) + Math.pow(pt[1], 2);
        
    let pivot = arr[Math.floor((0 + arr.length - 1) / 2)]; // middle element
    
    for (let i = 0; i < arr.length; i++) {
      if (dist(arr[i]) < dist(pivot)) left.push(arr[i]);
      else if (dist(arr[i]) === dist(pivot)) equal.push(arr[i]);
      else right.push(arr[i]);
    }
    
    if (left.length === k) return left;
    if (left.length + equal.length === k) return [...left, ...equal];
    if (left.length > k) return find(left, k);
    else return [...left, ...equal, ...find(right, k - left.length - equal.length)]; 
  };

  
  return find(points, k);
};
```

#### Language used for code
JavaScript

#### Expected behavior
Pass the test

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. After investigated, the test cases are correct. Your solution received wrong answer, and ran on an infinite loop.
Here is the solution AC'd with modifications:

var kClosest = function(points, k) {

  const find = (arr, num) => {
    let left = [];
    let right = [];
    let equal = [];
    const dist = (pt) => pt[0]**2 + pt[1]**2 ;
    // const dist = (pt) => Math.pow(pt[0], 2) + Math.pow(pt[1], 2);
let pivot = arr[Math.floor((0 + arr.length - 1) / 2)]; // middle element

for (let i = 0; i < arr.length; i++) {
  if (dist(arr[i]) < dist(pivot)) left.push(arr[i]);
  else if (dist(arr[i]) === dist(pivot)) equal.push(arr[i]);
  else right.push(arr[i]);
}

if (left.length === num) return left;
if (left.length + equal.length === num) return [...left, ...equal];
if (left.length > num) return find(left, num);
else return [...left, ...equal, ...find(right, num - left.length - equal.length)]; 
  };
  return find(points, k);
};

 We appreciate your support!
