### ISSUE TITLE
Invalid Python type hint - 2265. Count Nodes Equal to Average of Subtree

### ISSUE THREAD

**Issue by pbelskiy** [LeetCode-Feedback/LeetCode-Feedback#8201]
#### Your LeetCode username
https://leetcode.com/pbelskiy/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
Incorrect type hints in default Python code for task:
https://leetcode.com/problems/count-nodes-equal-to-average-of-subtree/

`root: Optional[TreeNode]` means root argument could be None, but constraints
of task says `The number of nodes in the tree is in the range [1, 1000].`

```python
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def averageOfSubtree(self, root: Optional[TreeNode]) -> int:

```

#### Code you used for Submit/Run operation
See above

#### Language used for code
Python

#### Expected behavior
It's correct to remove `Optional` from type hint.
```python
class Solution:
    def averageOfSubtree(self, root: TreeNode) -> int:
```

#### Screenshots
No applicable

#### Additional context
No applicable

**Comment by TechnicalFox** [comment]
Confirming this is still an issue and was very confusing trying to figure out where the None type was supposed to be coming from when it didn't fit the constraints of the problem.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
