### ISSUE TITLE
Typo In Leetcode 11 Container With Most Water Solution

### ISSUE THREAD

**Issue by YeezyYeezyWhatsGood** [LeetCode-Feedback/LeetCode-Feedback#8202]
#### Your LeetCode username

bcatalfo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ *] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the solution it says "How this approach works?" it should say something like "How does this approach work?" 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
