### ISSUE TITLE
缺少测试用例 - 2289. 使数组按非递减顺序排列

### ISSUE THREAD

**Issue by Amano-Sei** [LeetCode-Feedback/LeetCode-Feedback#8206]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
amano-sei

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
[2289. 使数组按非递减顺序排列](https://leetcode.cn/problems/steps-to-make-array-non-decreasing/)缺少测试用例
下述[ac通过](https://leetcode.cn/submissions/detail/337220016/)的代码在[该符合题面要求的测试用例](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9130292/lc2289.in.txt)会tle。

**你使用的语言**
C++

**你提交或者运行的代码**
```cpp
const int maxn = 1e5+5;
int nxt[maxn];
class Solution {
public:
    int totalSteps(vector<int>& nums) {
        queue<int> que;
        int n = nums.size();
        for(int i = n-1; i >= 0; i--){
            nxt[i] = i+1;
            que.push(i);
        }
        int sz = que.size(), ret = -1;
        while(sz){
            ret++;
            while(sz--){
                int cur = que.front();
                que.pop();
                int cnxt = nxt[cur];
                if(cnxt < n && nums[cur] > nums[cnxt]){
                    que.push(cur);
                    nxt[cur] = nxt[cnxt];
                }
            }
            sz = que.size();
        }
        return ret;
    }
};
```

**期望行为**
添加[该测试用例](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9130292/lc2289.in.txt)，或其他类似的可以将该代码卡成O(n^2)的用例使其不能ac通过

**屏幕截图**
![image](https://user-images.githubusercontent.com/38125508/179171284-a9adb4e8-1fda-4b3c-81b6-e065154b9d47.png)

**Comment by BrambleWave** [comment]
你好，当前该题已添加测试用例，奖励已发放。
