### ISSUE TITLE
216, 组合总和三 提交出错, 确认是提交有问题了

### ISSUE THREAD

**Issue by NgChiKin** [LeetCode-Feedback/LeetCode-Feedback#821]
** Bug 类型**
- [ ] 题目
- [√ ] 题解
- [ ] 编程语言

**描述**
 提交代码  一组测试用例是 k=3, n=2, 我明明在程序 入口函数 一开始就判断了 如果 k > n 就返回空数组
提交后给输的是  [[1,2,4]]  这下真的确认是提交出错了
 
**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
// combination-sum-iii
    let res = []
    const generateCombin = (k, n, p, start) => {
      if(n == 0 && p.length == k) {
        res.push([...p])
        return
      }

      for(let i = start; i< 10; i++) {
        let curValue = n - i
        if(curValue < 0) break

        p.push(i)
        generateCombin(k, curValue, p, i + 1)
        p.pop()
      }
    }

    var combinationSum3 = function (k, n) {
      if(k > n || k <= 0)
        return  res
      generateCombin(k, n, [], 1)
      return res
    };
```

**期望行为**
 做了 三道关于这个 组合总和 的 提交全部有问题,希望能解决

**屏幕截图**
![image](https://user-images.githubusercontent.com/57823909/90338668-cca10700-e01d-11ea-9036-11df77f9cf25.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。 后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至  [力扣圈子](https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=)  进行题目交流，以获得更好的支持哟～
