### ISSUE TITLE
Missing Test Case - 703. Kth Largest Element in a Stream

### ISSUE THREAD

**Issue by vivekiet22** [LeetCode-Feedback/LeetCode-Feedback#8211]
#### Your LeetCode username
vivekiet22

#### Category of the bug

- [ ] Solution
- [ ] solution showing wrong output for a particular test case

#### Description of the bug
I used the below code to submit the problem solution,but it shows wrong solution for particular testcase.
When I tried to run the same code and by same test cases then it shows as accepted.

#### Code you used for Submit/Run operation

```
from heapq import *
class KthLargest:
    minHeap = []

    def __init__(self, k: int, nums: List[int]):
        self.k = k
        for num in nums:
            self.add(num)

    def add(self, val: int) -> int:
        heappush(self.minHeap,val)
        if len(self.minHeap)>self.k:
            heappop(self.minHeap)
        return self.minHeap[0]


# Your KthLargest object will be instantiated and called as such:
# obj = KthLargest(k, nums)
# param_1 = obj.add(val)
```

#### Language used for code
 Python 

#### Expected behavior
 it should return the answer **[null,-3,-2,-2,0,4]**  but it return  [null,8,8,8,8,8] when submitting solution 

#### Screenshots

![image](https://user-images.githubusercontent.com/57106245/179264138-4c1bd8f0-baff-42bc-a0aa-1654819020f4.png)

![image](https://user-images.githubusercontent.com/57106245/179265253-0a3d426f-267c-4592-805e-54bac33f1bd6.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
