### ISSUE TITLE
"Non overlapping intervals" article approach 5, wording is same for case 2 and case 3

### ISSUE THREAD

**Issue by deepak-m1shra** [LeetCode-Feedback/LeetCode-Feedback#8212]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### "Non overlapping intervals" article approach 5, wording is same for case 2 and case 3
https://leetcode.com/problems/non-overlapping-intervals/solution/

#### Screenshots

<img width="816" alt="image" src="https://user-images.githubusercontent.com/20484669/179281749-8a95280b-661e-483f-8226-17c840e53e1b.png">

#### Additional context

Reported in comment long back https://leetcode.com/problems/non-overlapping-intervals/solution/128935

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Please send us your LC username.

**Comment by deepak-m1shra** [comment]
https://leetcode.com/d33pakmishra/

**Comment by deepak-m1shra** [comment]
[image: image.png]

Hi my LC username is  d33pakmishra
