### ISSUE TITLE
Error in runtime - 16. 3Sum Closest

### ISSUE THREAD

**Issue by vinishd** [LeetCode-Feedback/LeetCode-Feedback#8214]
#### Category of the bug
- [ ] Question
- [-] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

No matter how optimal the solution is, the test cases seem to cause the console to output TLE every time

#### Code you used for Submit/Run operation

```
class Solution:
    def threeSumClosest(self, nums: List[int], target: int) -> int:
        nums.sort()
        res = nums[0] + nums[1] + nums[2]
        for i in range(len(nums) - 2):
            j = i + 1
            k = len(nums) - 1
            while j < k:
                curSum = nums[i] + nums[j] + nums[k]
                
                if curSum == target:
                    return curSum
                
                if abs(curSum - target) < abs(res - target):
                    res = curSum
                    
                if curSum < target:
                    j += 1
                elif curSum > target:
                    k -= 1
        return res
```

#### Expected behavior

Expected it to pass the test cases using an optimal solution

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by vinishd** [comment]
wasn't really a missing case it just TLE no matter what code i submit (Python)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We reduced the number of test cases and this solution is now AC. We appreciate your support!
