### ISSUE TITLE
【大陆无法访问的链接】 - 558. 四叉树交集

### ISSUE THREAD

**Issue by LetMeFly666** [LeetCode-Feedback/LeetCode-Feedback#8217]
<b><a href="https://leetcode.cn/u/tisfy/">tisfy</a></b>

**Bug 类型**

- [ ] 题目

**描述**

题目中说：

> 如果你想了解更多关于四叉树的内容，可以参考 [wiki](https://en.wikipedia.org/wiki/Quadtree) 。

但是中国**大陆无法访问**wikipedia.org

我认为，可以将中文版题目的链接修改为：

> 如果你想了解更多关于四叉树的内容，可以参考 [百度百科](https://baike.baidu.com/item/%E5%9B%9B%E5%8F%89%E6%A0%91/8557650) 。

祝好！

**Comment by BrambleWave** [comment]
感谢您的来信，我们会规划下这块的显示方式。
