### ISSUE TITLE
C# Runtime issue - Unable to submit the solution

### ISSUE THREAD

**Issue by vcrahul** [LeetCode-Feedback/LeetCode-Feedback#8218]
#### Your LeetCode username

rahulvc

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

C# Code is taking too much runtime compared to JAVA - (576. Out of Boundary Paths)

#### Code you used for Submit/Run operation

C# Code
```
 public int FindPaths(int m, int n, int maxMove, int startRow, int startColumn) {
        if(startRow < 0 || startColumn < 0 || startRow == m || startColumn == n) return 1;
        if(maxMove == 0) return 0;
        return FindPaths(m, n, maxMove-1, startRow-1, startColumn) +
            FindPaths(m, n, maxMove-1, startRow+1, startColumn) +
            FindPaths(m, n, maxMove-1, startRow, startColumn-1) +
            FindPaths(m, n, maxMove-1, startRow, startColumn+1);        
    }
```
JAVA Code
```
  public int findPaths(int m, int n, int N, int i, int j) {
    if (i == m || j == n || i < 0 || j < 0) return 1;
    if (N == 0) return 0;
    return findPaths(m, n, N - 1, i - 1, j)
        + findPaths(m, n, N - 1, i + 1, j)
        + findPaths(m, n, N - 1, i, j - 1)
        + findPaths(m, n, N - 1, i, j + 1);
  }
```

#### Language used for code

C#

#### Expected behavior

With exactly same logic and syntax, both C# and JAVA should execute with nearly same runtime. But now if JAVA takes 0ms, C# is taking 30ms. Because of this I am not able to submit the code as it is throwing **time limit exceeded** error. Please assist.

#### Screenshots

C# execution
![image](https://user-images.githubusercontent.com/84614728/179341608-86fe1c2b-98d6-4b4d-a469-367ce4659a37.png)
JAVA execution
![image](https://user-images.githubusercontent.com/84614728/179341630-a2454efa-dc77-47cd-8681-e7f5c93f7237.png)

**Comment by vcrahul** [comment]
Most of the logic which works in JAVA Wont work in C#, Please assist at the earliest

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. After investigated, both of your codes received Compile Error. 
https://leetcode.com/submissions/detail/750438318/
https://leetcode.com/submissions/detail/750438571/
Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
