### ISSUE TITLE
216, 提交出错. 返回的值 是 代码里没有返回的值

### ISSUE THREAD

**Issue by NgChiKin** [LeetCode-Feedback/LeetCode-Feedback#822]
** Bug 类型**
- [ √] 提交问题

**描述**
过分了, 昨天反馈了三个bug没解决还把反馈删了,也不给个解释,是我代码错了还是提交错了.    提交出错了 k=3, n=2, 代码判断了 k > 2 就返回空数组, 结果莫名其妙返回的不是空数组. 在浏览器运行这串代码没有任何问题.

**你使用的语言**
C++

**你提交或者运行的代码**
```
    let res = []
    const generateCombin = (k, n, p, start) => {
      if(n == 0 && p.length == k) {
        res.push([...p])
        return
      }

      for(let i = start; i< 10; i++) {
        let curValue = n - i
        if(curValue < 0) break

        p.push(i)
        generateCombin(k, curValue, p, i + 1)
        p.pop()
      }
    }

    var combinationSum3 = function (k, n) {
      if(k > n || k <= 0)
        return  res
      generateCombin(k, n, [], 1)
      return res
    };
```

**期望行为**
别再没给反馈,就删了

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/57823909/90370078-56dd7f80-e09f-11ea-94b5-90832dcae5c9.png)

**额外的上下文**
添加额外的上下文信息

**Comment by NgChiKin** [comment]
![image](https://user-images.githubusercontent.com/57823909/90370433-f8fd6780-e09f-11ea-908e-471d7899bb91.png)

**Comment by NgChiKin** [comment]
76 题又有 问题 提交的  又是浏览器正常运行正确和执行代码按钮执行正确 提交又不行

`    let d = [
      [-1, 0],
      [0, 1],
      [1, 0],
      [0, -1]
    ]
    let m, n
    let used = []

    var inArea = function (x, y) {
      return x >= 0 && x < m && y >= 0 && y < n
    }

    var searchWord = function (board, word, index, startx, starty) {
      if (index == word.length - 1)
        return board[startx][starty] == word[index]

      if (board[startx][starty] == word[index]) {
        used[startx][starty] = true
        for (let i = 0; i < 4; i++) {
          let newx = startx + d[i][0]
          let newy = starty + d[i][1]

          if (inArea(newx, newy) && !used[newx][newy] &&
            searchWord(board, word, index + 1, newx, newy))
            return true
        }
        used[startx][starty] = false
      }

      return false
    }


    var exist = function (board, word) {

      if (!board) return false
      m = board.length
      n = board[0].length

      for (let i = 0; i < board.length; i++) {
        let arr = []
        for (let j = 0; j < board[i].length; j++)
          arr.push(false)
        used.push(arr)
      }

      for (let i = 0; i < m; i++)
        for (let j = 0; j < board[i].length; j++)
          if (searchWord(board, word, 0, i, j))
            return true

      return false
    };`
![image](https://user-images.githubusercontent.com/57823909/90376606-52b65f80-e0a9-11ea-9a99-0a5280f895c4.png)

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。 后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至  [力扣圈子](https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=)  进行题目交流，以获得更好的支持哟～
