### ISSUE TITLE
Problem 1779 Incorrect output for a test case

### ISSUE THREAD

**Issue by smegh18** [LeetCode-Feedback/LeetCode-Feedback#8221]
#### Your LeetCode username

megh18

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ !] Missing Test Cases 

#### Description of the bug

One of the test cases for problem number 1779 is expecting a wrong output

#### Code you used for Submit/Run operation

```
// Find Nearest Point That Has The Same X or Y Cordinate
class Solution {
    public int nearestValidPoint(int x, int y, int[][] points) {
        int d=0,m=0;
        int a,b,v=-1;
        for(int i=0;i<points.length;i++){
            a=points[i][0];
            b=points[i][1];
            if(a==x && b==y)
                return 0;
            if(a==x || b==y){
                d=Math.abs(a-x)+Math.abs(b-y);
                if(m==0){
                    m=d;
                    v=a;
                }
                else{
                    if(d<m){
                        m=d;
                        v=a;
                    }
                    if(d==m){
                        if(a<v)
                            v=a;
                    }
                }
            }
            
        }
        return v;
    }
}
```

#### Language used for code

Java

#### Expected behavior

1
1
[[1,2],[3,3],[3,3]]
For this particaular input the output should be 1 but instead the expected output shown is 0

#### Screenshots

![Screenshot from 2022-07-16 23-06-17](https://user-images.githubusercontent.com/66272274/179366007-fe2845b1-ae58-4719-8fb6-ad534e1801c0.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes! The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.

We appreciate your time and support! If you have any other questions, please don't hesitate to let us know.
