### ISSUE TITLE
Java Easy Solution- 1ms (100% faster) - With explanation!!

### ISSUE THREAD

**Issue by sumanth-reddy13** [LeetCode-Feedback/LeetCode-Feedback#8223]
1) We will solve this problem from (n-2)th index  to 0th index of the array. First take the last element (arr[n-1]) in the array as maximum. ---->>> int max = arr[n-1].
2) Store the arr[n-1] value in temp variable. Then assign the maximum value to the next element (arr[n-2]). We then check if the arr[n-2] is greater than maximum or not. It greater, we will make it as maximum. 
------------>>>>> int temp = arr[n-1];
------------>>>>> arr[n-1] = max; 
                       >>>  if(temp>max)   max=temp;

3) Continue the same process for the rest of the loop.

class Solution {
    public int[] replaceElements(int[] arr) 
    {
       int n = arr.length;
        
        int max = arr[n-1];                      // take last element in the array as maximum value.

        for(int i=n-2;i>=0;i--)               
        {
            int temp=arr[i];                     //store the array value in temp variable. when we assign max to arr[i], both will become equal.
             arr[i]=max;                             // to compare them, we store arr[i] in temp variable.
            if(temp>max)
                max=temp;
        }
        arr[n-1]=-1;
        return arr;
    }
}

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your solution to the team.  We appreciate your support!
