### ISSUE TITLE
565. Array Nesting 数据范围标识错误

### ISSUE THREAD

**Issue by YichuanSun** [LeetCode-Feedback/LeetCode-Feedback#8225]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
yiichan
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例
题目
**描述**
描述你遇到的 bug
中文版测试用例写的20000以内，但是英文版写的100000以内，判题是按照英文版判题的，写20000以内的算法都过不了。
**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    Solution(): spot(50000, -1), ans(0) {}

    int arrayNesting(vector<int>& nums) {
        for (int i = 0; i < (int)nums.size(); i++)  {
            search(nums,i);
        }
        return ans;
    }

    void search(vector<int>& nums, int x)  {
        if (spot[x] != -1)
            return;
        vector<bool> tmp(50000, false);
        int cnt = 0;
        while (tmp[x] == false)    {
            tmp[x] = true;
            cnt++;
            x = nums[x];
        }
        for (int i = 0; i < (int)spot.size(); i++)   {
            if (tmp[i] == true)
                spot[i] = cnt;
        }
        ans = max(ans, cnt);
    }

private:
    vector<int> spot;
    int ans;
};
```

**期望行为**
描述你期望的结果

**屏幕截图**

**报错的数据明显有大于20000的**
![image](https://user-images.githubusercontent.com/30886176/179375529-d701ee5c-3b9a-4216-b3eb-cb1687f728d6.png)
**然而题目描述中数据量却是最大20000**
![image](https://user-images.githubusercontent.com/30886176/179375537-2a18776f-d444-4c75-bb69-43a1ce90441f.png)

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
你好，当前该题已修复， 给予积分奖励，请查收。
