### ISSUE TITLE
Missing Test Case - 2344. Minimum Deletions to Make Array Divisible

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#8226]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9127047/1.txt)

#### Code you used for Submit/Run operation

```
int S=0;
class Solution {
public:
    int minOperations(vector<int>& nums, vector<int>& numsDivide) {
        int ans=-1,n=nums.size(),m=numsDivide.size();
        //排序，从小值开始
        sort(nums.begin(),nums.end());
        sort(numsDivide.begin(),numsDivide.end());
        for(int i=0;i<n;++i){
            int j=0;
            for(;j<m;++j){++S;
                if(numsDivide[j]%nums[i]!=0)  break;
            }
            if(j==m) {ans = i; break;} //找一个能把numsDivide中所有数整除的nums[i]
            while(nums[i]==nums[i+1] && i+1<n) 
                ++i;//跳过重复数字
        }
        cout<<S<<endl;
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

#### Screenshots

![image](https://user-images.githubusercontent.com/11583428/179384279-e91770c4-9b93-4e4f-b03e-534fbd482325.png)

**Comment by hqztrue** [comment]
Another code that gets TLE: (Python3)
```
class Solution:
    def minOperations(self, nums: List[int], numsDivide: List[int]) -> int:

        nums.sort()

        for j in range(len(nums)):
            if j and nums[j]==nums[j-1]:
                continue
            for num in numsDivide:
                if num%nums[j]!=0:
                    break
            else:
                return j
        return -1
```

![image](https://user-images.githubusercontent.com/11583428/179384385-d380f5c4-a941-4ae1-b586-1b1ba62d8eae.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
