### ISSUE TITLE
Existing Test Cases - 2343. Query Kth Smallest Trimmed Number

### ISSUE THREAD

**Issue by Amit-shaw-404** [LeetCode-Feedback/LeetCode-Feedback#8227]
#### Your LeetCode username

1mKnown

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Using a custom comparator in cpp gives TLE where as submitting the same solution without custom comparator passed all the test cases. The time complexity for both the solutions is O ( Q * N * N * Log ( N ) ).
Q * N * N * Log( N ) = 100 * 100 * 100 * log2(100) = 6643856.19.
In Cpp this much should easily pass still why did the testcases failed?

Please give a proper justification or fix the problem because it is very much unfair in the contests.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    static bool compare(pair<string, int>&a, pair<string, int>&b){
        int len = a.first.size();
        for(int i=0;i<len;i++){
            if(a.first[i]<b.first[i]){
                return true;
            }else if(a.first[i] > b.first[i]){
                return false;
            }
        }
        return a.second<b.second;
    }
    vector<int> smallestTrimmedNumbers(vector<string>& nums, vector<vector<int>>& queries) {
        vector<int>ans;
        for(int i=0;i<queries.size();i++){
            int k = queries[i][0];
            int t = queries[i][1];
            vector<pair<string, int>>val;
            int l = 0;
            for(auto str:nums){
                string cur = str.substr(str.size()-t, t);
                val.push_back({cur, l++});
            }
            sort(val.begin(), val.end(), compare);
            ans.push_back(val[k-1].second);
        }
        return ans;
    }
};
```

#### Language used for code
 C++

#### Expected behavior

This solution should have passed for all the testcases. The testcases for which it was giving TLE was getting executed within 30ms while executing manually.

#### Screenshots

![image](https://user-images.githubusercontent.com/66773221/179384641-b51591dc-0331-456c-8813-d77e4b55ca85.png)
![image](https://user-images.githubusercontent.com/66773221/179384658-9e890a6e-3f1d-4e77-a7df-8f7056f91239.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
This issue reported before the finalize, we are working on rejudge currently.
Thank you so much.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to rejudged your submission. We appreciate your support!
