### ISSUE TITLE
Solution : Maximum Number of Pairs in Array

### ISSUE THREAD

**Issue by Ayushluthra2001** [LeetCode-Feedback/LeetCode-Feedback#8228]
#### Your LeetCode username 
LeetCode username ayushluthra62

#### Category of the bug
- [ ] Question
- [✅] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the Solution 
This is a solution of problem Maximum Number of Pairs in Array
problem link :- https://leetcode.com/problems/maximum-number-of-pairs-in-array/

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> numberOfPairs(vector<int>& nums) {
        map<int,int>m;
        int counter=0; int leftover=0;
        for(int i=0;i<nums.size();i++){
            m[nums[i]]++;
        }
        for(auto i : m){
            counter+=i.second/2;
            leftover+=i.second%2;
            
        }
        return {counter,leftover};
    }
};
// examaple
// [1,3,2,1,3,2,2]
// 1 2 = > counter = 1 leftover 0
// 2 3 = > counter = 2 levtover 1
// 3 2 = > counter = 3 leftover 1
//    return  counter,leftover {3,1}

```

#### Language used for code
 C++

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your solution to the team.  We appreciate your support!
