### ISSUE TITLE
A Follow-up Requirement Should be Added - 2343. Query Kth Smallest Trimmed Number

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#8229]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The expected solution of this problem is using radix sort and offline query. But the simple solution with O(qmnlogn) time complexity can be accepted because of the terrible constraints. As the third problem, the solution with O(mn+q) time complexity is a bit difficult, so increasing the constraints of m,n and q is not a very good idea. I think a follow-up should be added: can you find a solution with O(mn+q) time complexity?

 Code you used for Submit/Run operation

The time complexity of the code below is O(qmnlogn)
```
class Solution:
    def smallestTrimmedNumbers(self, nums: List[str], queries: List[List[int]]) -> List[int]:
        
        res = []
        for idx,left in queries:
            tgt = sorted([[nums[j][-left:],j] for j in range(len(nums))])[idx-1]
            res.append(tgt[1])
        return res
```

The time complexity of the code below is O(mn+q)
```
class Solution:
    def smallestTrimmedNumbers(self, nums: List[str], queries: List[List[int]]) -> List[int]:

        vecs = [[] for j in range(len(nums[0])+1)]
        for j in range(len(nums)):
            vecs[0].append(j)
        for j in range(1,len(nums[0])+1):
            B = [[] for _ in range(10)]
            for x in vecs[j-1]:
                B[ord(nums[x][len(nums[0])-j])-48].append(x)
            for jj in range(10):
                for xx in B[jj]:
                    vecs[j].append(xx)
        
        res = []
        for idx,left in queries:
            res.append(vecs[left][idx-1])
        return res
```

Language used for code
Python3

Expected behavior
A follow-up requirement should be added: 
Can you find a solution with O(mn+q) time complexity?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
