### ISSUE TITLE
题目969误通过

### ISSUE THREAD

**Issue by CainHsu** [LeetCode-Feedback/LeetCode-Feedback#823]
**Bug 类型**
- [ ] 题目
- [ ] 题解

**描述**
测试用例为`[3,2,4,1]`时输出为`[3,4,2,3,2]`，输出长度大于输入长度，按理不符合题目要求，却能提交通过。

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> pancakeSort(vector<int>& A) {
        int len = A.size();
        vector<int> res;
        for(int i = len; i > 1; --i){
            int maxIndex = max_element(A.begin(), A.begin()+i) - A.begin();
            if(maxIndex+1 == i) continue;
            if(maxIndex > 0) {
                res.push_back(maxIndex + 1);
                reverse(A.begin(), A.begin() + maxIndex + 1);
            }
            res.push_back(i);
            reverse(A.begin(), A.begin() + i);
        }
        return res;
    }
};
```

**期望行为**
按照题目要求来判断是否通过。

**屏幕截图**
![image](https://user-images.githubusercontent.com/24185320/90383421-b3966580-e0b2-11ea-866b-7b510f31c115.png)
![image](https://user-images.githubusercontent.com/24185320/90383464-c446db80-e0b2-11ea-87a9-13c89428a6e8.png)

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，请仔细阅读理解题目意思（题目没有要求最短）。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路哦。
