### ISSUE TITLE
Existing Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by UtkarshM-hub** [LeetCode-Feedback/LeetCode-Feedback#8231]
#### Your LeetCode username

Utkarsh_Mandape

#### Category of the bug
- [#] Existing test case

#### Description of the bug

The array in the input of test case is not correct, it should be [ 4,5,6,7,0,1,2,3 ].

#### Code you used for Submit/Run operation

//Shuffle String

```class Solution {
public:
    string restoreString(string s, vector<int>& indices) {
        string result;
        for(int i=0;i<s.length();i++){
            result.push_back(s[indices[i]]);
        }
        return result;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The answer I was expecting was 'leetcode' but got 'leetcdoe'.

#### Screenshots

![Shuffle-String-LeetCode](https://user-images.githubusercontent.com/70505181/179395083-a2a594a2-c42a-4fd2-ac9d-c1a7d123f43c.png)

**Comment by stormsunshine** [comment]
The test case is correct. Please make sure you have understood the test case.

**Comment by UtkarshM-hub** [comment]
My bad
