### ISSUE TITLE
Missing/Incorrect Test Case - 1495. Friendly Movies Streamed Last Month

### ISSUE THREAD

**Issue by coanghel** [LeetCode-Feedback/LeetCode-Feedback#8232]
#### Your LeetCode username

coanghel

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A manually created test case with all program_dates in 2021 passes if using 
```
where month(program_date)=6
```
despite problem statement specifically asking for June 2020 results only. Either there is no test case with program dates outside of 2020, or the solution SQL statement has an error.

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
select distinct
    title
from tvprogram t1
join content t2 on t1.content_id=t2.content_id
where t2.kids_content='Y' and t2.content_type='Movies' 
and program_date between '2020-06-01' and '2020-06-30'
```

#### Expected behavior

Bug description should be sufficient explanation

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
