### ISSUE TITLE
golang syntax error: cannot use assignment

### ISSUE THREAD

**Issue by liuzihua699** [LeetCode-Feedback/LeetCode-Feedback#8233]
**你的 LeetCode 用户名**
zihua-1

**Bug 类型**
- [X] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
leetcode编译器报错`syntax error: cannot use assignment`，该错误一般是类型不匹配，而代码报错处`nnums`为`[]int`类型，b为`int`类型，理论上不应该存在该错误。为验证我在本地使用`go run`发现并无语法问题。

**你使用的语言**
golang

**你提交或者运行的代码**
[题目地址](https://leetcode.cn/problems/squares-of-a-sorted-array/)

```
func sortedSquares(nums []int) []int {
    len := len(nums)
    nnums := make([]int, len)

    i, j := 0, len - 1
    k := len - 1
    for {
        if i > j {
            break
        }
        a, b := nums[i]*nums[i], nums[j]*nums[j] 
        if a < b
            nnums[k] = b
            k, j = k - 1, j - 1
        } else {
            nnums[k] = a
            k, i = k - 1, i + 1
        }
    }

    return nnums
}
```

**期望行为**
正常执行

**屏幕截图**
![image](https://user-images.githubusercontent.com/38183150/179426017-a1cfffa3-c9c1-4e05-8261-e6497cb19eb6.png)

![image](https://user-images.githubusercontent.com/38183150/179426026-c45d2237-afac-4f28-94ff-a35068084081.png)

**Comment by feiceh** [comment]
你好，在与相关团队核实后：代码第 12 行，最后少了一个 { 。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
