### ISSUE TITLE
Incorrect time complexity of heapify operation on Heap explore card

### ISSUE THREAD

**Issue by AjayPoshak** [LeetCode-Feedback/LeetCode-Feedback#8234]
#### Your LeetCode username
ajayposhak

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
On the heap explore card, in the section "[Construct a Heap](https://leetcode.com/explore/featured/card/heap/644/common-applications-of-heap/4022/)",  the time complexity is mentioned as O(N).  This is incorrect.
Because. for an array of N element, inserting each element will take O(logN) time so total time comes to O(NlogN), not O(N)

#### Expected behavior
It should mention the expected runtime complexity as O(NlogN) for heapify operation.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've investigated your feedback and thank you for bring this to us. 

Please check this article for more details:  How can building a heap be O(n) time complexity?https://stackoverflow.com/questions/9755721/how-can-building-a-heap-be-on-time-complexity

We appreciate your support!
