### ISSUE TITLE
缺少测试用例 1502

### ISSUE THREAD

**Issue by chengyj0505** [LeetCode-Feedback/LeetCode-Feedback#8235]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
密码错误啊
mi-ma-cuo-wu-a

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [√ ] 缺少测试用例

**描述**
缺少测试用例。我写了一个错误的代码，但是由于缺少测试用例，后台还是通过了。例如缺少测试用例 $[10,1,10,19,10]$。这个算法的思路是这样的：
- 利用等差公式
- 首先需要满足元素的和与用等差数列求和公式得到的相等这一条件，如果b =0 说明，这是一个等差数列。如果b不等于0，按照顺序一次判断元素是否符合下面条件，即能被b整除，或者当前数不重复出现，说明不是等差数列。
- 初衷是这个方法可以避免排序，降低时间复杂度和空间复杂度
- 但是有一行代码是错误的

**你使用的语言**
python3/python

**你提交或者运行的代码**
```
class Solution:
    def canMakeArithmeticProgression(self, arr: List[int]) -> bool:
        n = len(arr)
        a1 = min(arr)
        an = max(arr)
        d = (an - a1) / (n - 1)
        sumn = a1 * n + (n * (n - 1) * d) / 2
        sum_arr = sum(arr)
        temp = float('inf')
        if sumn == sum_arr:
            if d == 0:
                return True
            for i in range(len(arr)):
                if (arr[i] - a1) % d != 0 or (temp == arr[i]):   #这一步是错的
                    return False
                temp = arr[i]
            return True
        return False
```

**期望行为**
增加测试用例 $[10,1,10,19,10]$

**屏幕截图**
![image](https://user-images.githubusercontent.com/83801480/179448814-b43c7295-a94c-407f-9631-675679826952.png)

**Comment by BrambleWave** [comment]
你好，当前该题已添加测试用例，奖励已发放。
