### ISSUE TITLE
（缺少测试用例）剑指 Offer 03. 数组中重复的数字

### ISSUE THREAD

**Issue by Ltage** [LeetCode-Feedback/LeetCode-Feedback#8236]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Ltage

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [X] 缺少测试用例

**描述**
错误的代码也能AC

**你使用的语言**
python3

**你提交或者运行的代码**
```
class Solution:
    def findRepeatNumber(self, nums: List[int]) -> int:
        for i, num in enumerate(nums):
            if num != i:
                if nums[num] == num:
                    return num
                nums[num], nums[i] = nums[i], nums[num]
        return nums[0]
```

**期望行为**
增加测试用例

**屏幕截图**
![捕获](https://user-images.githubusercontent.com/86953514/179454089-c1151a94-05a5-42d7-a303-46c7fcc40caa.JPG)

![捕获2](https://user-images.githubusercontent.com/86953514/179454148-51d5a92c-4374-4298-bcef-7c880c4efa9a.JPG)

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
您好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的 个性域名，我们给予积分奖励哦。

**Comment by Ltage** [comment]
我的个性域名是leetcode-cn.com/u/Ltage/
刚改的，之前还不知道有这个东西，新手一枚
从 Windows 版邮件发送

发件人: BrambleWave
发送时间: 2022年7月22日 18:24
收件人: LeetCode-Feedback/LeetCode-Feedback
抄送: Ltage; Author
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] （缺少测试用例）剑指 Offer 03. 数组中重复的数字 (Issue #8236)

您好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的 个性域名，我们给予积分奖励哦。

**Comment by BrambleWave** [comment]
奖励已发送。
再次感谢您对力扣的支持。
