### ISSUE TITLE
260. Single Number III Checker is Wrong (Error Test Case)

### ISSUE THREAD

**Issue by uds5501** [LeetCode-Feedback/LeetCode-Feedback#824]
#### Your LeetCode username

@uds5501

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The expected answer is giving an element that is not present in the test case array.
According to the question, we need to return an array of elements which are present only once. 
I submitted the Test Case [1,1,2,2,6,8,10,15,8].
According the question it should return [6,10,15]
But it's returning expected answer to be [12,15] . But 12 **is not present in test case!**

#### Code you used for Submit/Run operation

```
// Single Number III
class Solution {
public:
    vector<int> singleNumber(vector<int>& nums) {
        long long mask = 0;
        for(auto num: nums) {
            if (mask & (1 << num)) {
                mask &= ~(1 << num);
            }
            else {
                mask |= (1 << num);
            }
        }
        vector<int> ans;
        for(auto i: nums) {
            if (mask & (1 << i)) ans.push_back(i);
        }
        return ans;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

Expected answer : [6, 10, 15]
What we are actually receiving : [15,12]

#### Screenshots

![image](https://user-images.githubusercontent.com/21087061/90486521-b2b70f80-e156-11ea-8fce-3dbab8bdaf6d.png)

#### Additional context

Please look into it

**Comment by lc-pam** [comment]
Hi @uds5501 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @uds5501 
Thank you for your time. The test case you used is invalid. We've used your feedback to add test case validation to this problem. We appreciate your support!
