### ISSUE TITLE
2301. Match Substring After Replacement (Weak Test Case)

### ISSUE THREAD

**Issue by d-s-dc** [LeetCode-Feedback/LeetCode-Feedback#8241]
#### Username
d_codr

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The [question](https://leetcode.com/problems/match-substring-after-replacement/) has weak test cases. I found a `wrong answer` solution which is `accepted`.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool matchReplacement(string s, string sub, vector<vector<char>>& mappings) {
        
        unordered_map<char, unordered_set<char>> mps;
        for (vector<vector<char>>::iterator itr1 = mappings.begin(); 
             itr1 != mappings.end(); itr1++)
            mps[(*itr1)[0]].insert((*itr1)[1]);
        
        string nStr = sub + '-' + s;
        int len = sub.size();
        int z[nStr.size()+1];
        memset(z,0,sizeof z);
        
        int l,r,i;
        l = r = i = 0;
        while (z[i] < len && i<nStr.size())
        {
            i++;
            if (i <= r)
                z[i] = min(z[i-l], r-i+1);
            while(i+z[i] < nStr.size() && 
                  (nStr[i+z[i]] == nStr[z[i]] || 
                   mps[nStr[z[i]]].find(nStr[i+z[i]]) != mps[nStr[z[i]]].end())
                 )
                z[i]++;
            if (z[i] + i - 1 > r)
                l = i, r = z[i] + i - 1;
        }
        
        if (i == nStr.size())
            return false;
        else
            return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The following test case does not produce correct results but code is accepted.
> "akjct"
> "lect"
> [["l","e"],["e","c"],["t","8"],["l","a"],["e","k"],["c","j"]]

#### Screenshots
![Bug](https://user-images.githubusercontent.com/68206552/179502550-187ac24a-bd69-40bb-a61d-f669d95be494.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by d-s-dc** [comment]
I raised the bug as **weak test case.**

The `main point` was that the question is `accepting a wrong solution`. The output of Run Test Case was for the missing the test case which I created and mentioned.


Please have a look again at what the issue is.

**Comment by d-s-dc** [comment]
The following testcase should be added 
> "akjct"
> "lect"
> [["l","e"],["e","c"],["t","8"],["l","a"],["e","k"],["c","j"]]

**Comment by d-s-dc** [comment]
@LC-Pam Could you look through my comments. I raised for weak test cases. You have misunderstood the case. I request you to add the test case or I will have to open another issue.
