### ISSUE TITLE
Wrong constraint in problem description - 243. Shortest Word Distance

### ISSUE THREAD

**Issue by lithuak** [LeetCode-Feedback/LeetCode-Feedback#8242]
The constraint `1 <= wordsDict.length <= 3 * 104` is wrong since from `word1 and word2 are in wordsDict` and `word1 != word2` if follows that the minimal possible length of wordsDict is 2, not 1.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
