### ISSUE TITLE
Unneeded line in Java solution for 49. Group Anagrams

### ISSUE THREAD

**Issue by solamen2** [LeetCode-Feedback/LeetCode-Feedback#8243]
#### Your LeetCode username
ed_younskevicius

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For approach 2, Java solution, it includes this line: ```Arrays.fill(count, 0);```

There's no need for this line, as Java always initializes int array values to 0. It can be removed for an efficiency gain (which I checked just to be sure, and the solution passes all the test cases without this line).

#### Code you used for Submit/Run operation
N/A

#### Language used for code
Java

#### Expected behavior
N/A

#### Screenshots
N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you suggested (remove this line but passes).

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by solamen2** [comment]
public List<List<String>> groupAnagrams(String[] strs) {
        if (strs.length == 0) return new ArrayList();
        Map<String, List> ans = new HashMap<String, List>();
        int[] count = new int[26];
        for (String s : strs) {
            //Arrays.fill(count, 0);
            for (char c : s.toCharArray()) count[c - 'a']++;

            StringBuilder sb = new StringBuilder("");
            for (int i = 0; i < 26; i++) {
                sb.append('#');
                sb.append(count[i]);
            }
            String key = sb.toString();
            if (!ans.containsKey(key)) ans.put(key, new ArrayList());
            ans.get(key).add(s);
        }
        return new ArrayList(ans.values());
    }

**Comment by LC-Pam** [comment]
Hi there,
Thank you for your quick response. The code that you submitted receive the Compile Error. https://leetcode.com/submissions/detail/753890801/
Please  provide the code that removes this line but passes.
We appreciate your help!

**Comment by solamen2** [comment]
It runs fine when I copy and paste that exact code to the submission box for the problem. Are you putting inside the class Solution?

Anyway, this code no longer passes the test cases. I think this bug report is in error. Sorry about that! I realize now it's because the code above only initializes the array once. Maybe Arrays.fill() is faster than declaring a new array.
