### ISSUE TITLE
117. Javascript run time bug

### ISSUE THREAD

**Issue by zhatiayua** [LeetCode-Feedback/LeetCode-Feedback#8245]
#### Description of the bug
Javascript has run time bug, any return type is not accepted. I even tried to return the original Node provided by the question, the run time error says the return type is not a node

#### Code you used for Submit/Run operation

```
// 117. Populating Next Right Pointers in Each Node II
/**
 * // Definition for a Node.
 * function Node(val, left, right, next) {
 *    this.val = val === undefined ? null : val;
 *    this.left = left === undefined ? null : left;
 *    this.right = right === undefined ? null : right;
 *    this.next = next === undefined ? null : next;
 * };
 */

/**
 * @param {Node} root
 * @return {Node}
 */
var connect = function(root) {
    let queue = [root]
    if (!root) return root
    while (queue.length) {
        let len = queue.length
        for (let i=0; i<len; i++) {
            let parent = queue.shift()
            if (i<len-1) parent.next = queue[0]
            parent.left && queue.push(parent.left)
            parent.right && queue.push(parent.right)
        }
    }
    return root
};
```

#### Language used for code
Javascript

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by MAXLZ1** [comment]
It's been two months, but the problem hasn't been solved.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
