### ISSUE TITLE
Three Sum Problem. Issue in the explanation description. 

### ISSUE THREAD

**Issue by Osvaldo111** [LeetCode-Feedback/LeetCode-Feedback#8246]
#### Category of the bug
- [ ] Question

#### Description of the bug

The example provided is not accurate in the 3 sum problem. If you see the last item nums[1] is referring to the value 0 on the array, but this is used two times in the explanation of the solution but the last time is referring to the value 1 but it is using the index nums[1]. See the example below and the SS. 

```
// Two Sum
Input: nums = [-1,0,1,2,-1,-4]
Output: [[-1,-1,2],[-1,0,1]]
Explanation: 
#Error here. The last nums[1] is not equal to 1. Here the correct solution should be : nums[0] + nums[1] + nums[2] = (-1) + 0 + 1 = 0.
nums[0] + nums[1] + nums[1] = (-1) + 0 + 1 = 0.
......
```

#### Expected behavior

Described above.

#### Screenshots

![image](https://user-images.githubusercontent.com/23143448/179634245-a1d69e1b-cd8e-4755-a5c2-a6d4eab6568c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Would you provide us your username?

**Comment by Osvaldo111** [comment]
> Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
> 
> Would you provide us your username?

Hi, this is my username: Osvaldo11
Thank you,

**Comment by LC-Pam** [comment]
Leetcoins issued
