### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by jhmahajan** [LeetCode-Feedback/LeetCode-Feedback#8247]
#### Your LeetCode username

jhmahajan98

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

There is a missing test case to check '+' after 'E'. My submitted code is failing the test case "1E+9," still the submission is getting accepted.

#### Code you used for Submit/Run operation

```
// 65. Valid Number
class Solution {
public:
    bool isNumber(string s) {
        bool frac = false;
        bool exp = false;
        bool number = false;
        bool eNumber = true;
        for(int i=0; i<s.length(); i++) {
            if('0' <= s[i] && s[i] <= '9') {
                number = true;
                eNumber = true;
            } 
            else if(s[i] == '.') {
                if(exp || frac) {
                    return false;
                }
                frac = true;
            } 
            else if(s[i] == 'e' || s[i] == 'E' ) {
                if(exp || !number) {
                    return false;
                }
                eNumber = false;
                exp = true;
            } 
            else if(s[i] == '-' || s[i] == '+') {
                if(i != 0 && s[i-1] != 'e') {
                    return false;
                }
            } 
            else {
                return false;
            }
        }
        return number && eNumber;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input - "1E+9"
Output - false
Expected - true

#### Screenshots

<img width="956" alt="2022-07-19" src="https://user-images.githubusercontent.com/53263938/179661373-bd899027-610a-4660-9ec5-de28bc788673.png">

**Comment by spideyxd** [comment]
OP bhaiya

**Comment by spideyxd** [comment]
gand hi fad diye aap

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. After investigated, we will not add more test cases for this problem. We appreciate your support!
