### ISSUE TITLE
Missing Test Case - 2344. Minimum Deletions to Make Array Divisible

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#8248]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9137371/1.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public int minOperations(int[] a, int[] c) { // 数组 a 和 数组 c
        int cnt = 0; // cnt 是删除次数
        Arrays.sort(a);
        
        // 使用 Set 去重优化时间复杂度
        Set<Integer> set = new HashSet<>();
        for (int i : c) set.add(i);
        
        for (int i = 0; i < a.length; i++) {
            boolean b = true;
            // 每一个不重复的数字都试试，不整除就提前终止；重复的没意义
            for (int y : set) {
                if (y % a[i] != 0) {
                    b = false;
                    break; // 提前终止，优化
                }
            }
            // 如果找到了一个符合条件的整除元素，就返回cnt，否则cnt++
            if (b) return cnt;
            cnt++;    
        }
        return -1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
