### ISSUE TITLE
INVALID TESTCASE 

### ISSUE THREAD

**Issue by spideyxd** [LeetCode-Feedback/LeetCode-Feedback#8249]
#### Your LeetCode username
Shivam2612002

#### Category of the bug
 Invalid Test Cases 
https://leetcode.com/problems/jump-game-ii/

#### Description of the bug

What if the first element of array if 0 ? There's no separate mention of such conditions , and according to that no solution is correct until you mention that cornercase.
If the first element is 0 we can't jump forward .

#### Code you used for Submit/Run operation

```
// Jump Game II
class Solution {
public:
    int jump(vector<int>& nums) {
        int l =0, r =0 ,jumps =0;
        if(nums.size() == 1)return 0;
        while( r < nums.size()-1){
            int farthest =0;
            for(int i =l;i<=r;i++){
                farthest = max(farthest , i + nums[i]);
            }
            l = r+1;
            r = farthest;
            jumps++;
        }
        return jumps;
    }
};

```

#### Language used for code

C++

#### Expected behavior

Answer should be 0 as we can't jump further but it is showing invalid input .How can it be invalid if there is no mention of such condition . This is very important case one of the interviewer asked for this corner case to one of my friend during his SDE interview.

**Comment by LC-Pam** [comment]
Thank you for your time. 
The statement said:
You can assume that you can always reach the last index.
The input mentioned is indeed invalid.
We appreciate your support!
