### ISSUE TITLE
55题测试和提交同一段代码 出现两种运行结果

### ISSUE THREAD

**Issue by R1cardoo** [LeetCode-Feedback/LeetCode-Feedback#8250]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
r1cardozhu

**Bug 类型**
 题目

**描述**
同一个测试用例 ，执行代码可以得到正确答案。提交代码得到不同答案。

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Jump Game
class Solution {
public:
    bool canJump(vector<int>& nums) {
        bool can[110000];

        int size = nums.size();
        can[0] = true;
        for (int i = 0; i <size; i++) {
            for(int j = 1; j <= nums[i]; j++) {
                if (can[i]) {
                    can[i+j] = true;
                } else {
                    break;
                }
            }
        }
        return can[size-1];
    }
};
```

**期望行为**
修复bug，代码通过

**屏幕截图**
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/44989268/179679610-b8251894-2878-4b02-8e1b-8f8522341e58.png">

**额外的上下文**
无

**Comment by BrambleWave** [comment]
这里可以理解为声明了一个 bool 类型的数组，
但其中的元素可能为 True 也可能为 False，
因此需要对其中进行初始化。 （C++ 语言特性）
![origin_img_v2_64a9dddd-c748-4f24-a14d-d6d9a359d1dg](https://user-images.githubusercontent.com/99636790/180419340-1e1964d9-0ec5-41ea-bf96-f0f27f9b7765.jpg)
这是个暴力解法，还是会超时的
