### ISSUE TITLE
Runtime error - 94. Binary Tree Inorder Traversal

### ISSUE THREAD

**Issue by karanarjunjr** [LeetCode-Feedback/LeetCode-Feedback#8254]
#### Your LeetCode username
karanarjunjr

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
An AddressSanitizer Runtime error is raised but code works fine for the same testcase `[1, null, 2, 3]` locally as well as on other platforms like CodeStudio.

#### Code you used for Submit/Run operation

```cpp
public:
    vector<int> inorderTraversal(TreeNode *root) {
        vector<int> ans;
        TreeNode *temp = root;
        if (!temp)
            return ans;
        unordered_map<TreeNode*, int> vis;
        while (temp) {
            if (!temp->left) {
                ans.push_back(temp->val);
                temp = temp->right;
            } else {
                if (!vis[temp]) {
                    TreeNode *left = temp->left;
                    while (left->right) {
                        left = left->right;
                    }
                    left->right = temp;
                    vis[temp]++;
                    temp = temp->left;
                } else {
                    ans.push_back(temp->val);
                    temp = temp->right;
                }
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code should run fine returning a vector `[1, 3, 2]`

#### Screenshots
![image](https://user-images.githubusercontent.com/69049250/179734514-150095c1-b25f-44c7-81db-9902fa2b2574.png)

**Comment by LC-Pam** [comment]
Hi there, 
Thank you for reaching out to us. When we submitted your code, we received Compile Error, here is the submission detail: https://leetcode.com/submissions/detail/751316822/
please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!


When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by karanarjunjr** [comment]
The first line of the solutin misses `class Solution {`. I made a mistake while copy pasting. Kindly check now. The issue is still on!
