### ISSUE TITLE
Missing Test Case - 794. Valid Tic-Tac-Toe State

### ISSUE THREAD

**Issue by monkepi18** [LeetCode-Feedback/LeetCode-Feedback#8256]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1] Missing Test Cases 

#### Description of the bug

My code does not work a specific test case but it gets accepted on Leetcode. Please add the test case.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool validTicTacToe(vector<string>& board) {
        int x=0, o=0;
        for(int i=0; i<board.size(); i++){
            for(int j=0; j<3; j++){
                if(board[i][j]=='X') x++;
                if(board[i][j]=='O') o++;
            }
        }
        if (board[0]=="OOO"&&board[2]=="XXX") return false;
        if (board[0]=="XXX"||board[1]=="XXX"||board[2]=="XXX"||(board[0][0]=='X' && board[1][0]=='X' && board[2][0]=='X')||(board[0][1]=='X' && board[1][1]=='X' && board[2][1]=='X')||(board[0][2]=='X' && board[1][2]=='X' && board[2][2]=='X')||(board[0][0]=='X' && board[1][0]=='X' && board[2][0]=='X')||(board[0][0]=='X' && board[1][1]=='X' && board[2][2]=='X')||(board[0][2]=='X' && board[1][1]=='X' && board[2][0]=='X')) return (x-o)==1;
        
        if (board[0]=="OOO"||board[1]=="OOO"||board[2]=="OOO"||(board[0][0]=='O' && board[1][0]=='O' && board[2][0]=='O')||(board[0][1]=='O' && board[1][1]=='O' && board[2][1]=='O')||(board[0][2]=='O' && board[1][2]=='O' && board[2][2]=='O')||(board[0][0]=='O' && board[1][0]=='O' && board[2][0]=='O')||(board[0][0]=='O' && board[1][1]=='O' && board[2][2]=='O')||(board[0][2]=='O' && board[1][1]=='O' && board[2][0]=='O')) return (x-o)==0;
        
        if((x-o)==0||(x-o)==1) return true;
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My code fails for the test case ["OXX","OXX","OOX"] but it gets accepted as this test case in not a part of Leetcode's collection. 

#### Screenshots

![image](https://user-images.githubusercontent.com/81469531/179780245-2390e300-5644-4922-ad82-90dbb5b4c6f3.png)

![image](https://user-images.githubusercontent.com/81469531/179780372-aa550be5-6a41-48d5-952e-caf6742e93e6.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Would you mind provide us your username?

**Comment by monkepi18** [comment]
My username is hushhh1810.

**Comment by LC-Pam** [comment]
Leetcoin issued.

**Comment by monkepi18** [comment]
Thank you!
