### ISSUE TITLE
Missing Test Case - 1168. Optimize Water Distribution in a Village

### ISSUE THREAD

**Issue by paskal** [LeetCode-Feedback/LeetCode-Feedback#8259]
#### Your LeetCode username
`paskal_07`

#### Category of the bug
Missing Test Cases 

#### Description of the bug

In the "Optimize Water Distribution in a Village" it's possible to create a disjoin set solution which would work on all test cases but wouldn't be valid, because two compared roots never has the same value. Here is a test case which would fail the code which doesn't fail any other test cases currently:

```
2
[2,2]
[[1,2,1]]
```

#### Code you used for Submit/Run operation

<details>
<summary>Wrong answer, passing all current tests but not one above, output 4</summary>
  
```go
type DisjoinSet struct {
    nodes []int
    value []int
}

func (d *DisjoinSet) union(x, y, v int) {
    rootX := d.find(x)
    rootY := d.find(y)
    valueX, valueY := d.value[rootX], d.value[rootY]
    if valueX <= v && v >= valueY {
        return
    }
    // commented out roots check, it's not happening
    // if rootX == rootY {
    //     return
    // }
    if valueX > valueY {
        d.update(rootX, rootY)
        d.value[rootX] = v
        return
    // this line replaces root check only because values of
    // two roots are never the same on existing test cases
    } else if valueY > valueX {
        d.update(rootY, rootX)
        d.value[rootY] = v
        return
    }
    return
}


func (d *DisjoinSet) update(oldRoot, newRoot int) {
    for i := range d.nodes {
        if d.nodes[i] == oldRoot {
            d.nodes[i] = newRoot
        } 
    }
    return
}


func (d *DisjoinSet) find(x int) int {
    if x == d.nodes[x]{
        return x
    }
    d.nodes[x] = d.find(d.nodes[x])
    return d.nodes[x]
}

func NewDisjoinSet(wells []int) DisjoinSet {
    nodes := make([]int, len(wells))
    for i := range nodes {
        nodes[i] = i
    }
    return DisjoinSet{nodes: nodes, value: wells}
}

func minCostToSupplyWater(n int, wells []int, pipes [][]int) int {
    set := NewDisjoinSet(wells)
    sort.SliceStable(pipes, func(i, j int) bool {
        return pipes[i][2] < pipes[j][2]
    })
    for _, pair := range pipes {
        set.union(pair[0]-1,pair[1]-1,pair[2])
    }
    
    result := 0
    for _, v := range set.value {
        result += v
    }
    // fmt.Printf("set: %+v\n", set)
    return result
}
```
</details>

<details>
<summary>Right answer, passing all current tests and one above, output 3</summary>

Only `union` method changes:

```go
func (d *DisjoinSet) union(x, y, v int) {
    rootX := d.find(x)
    rootY := d.find(y)
    valueX, valueY := d.value[rootX], d.value[rootY]
    if valueX <= v && v >= valueY {
        return
    }
    if rootX == rootY {
        return
    }
    if valueX > valueY {
        d.update(rootX, rootY)
        d.value[rootX] = v
        return
    } else {
        d.update(rootY, rootX)
        d.value[rootY] = v
        return
    }
    return
}

```

</details>

#### Language used for code

Go

#### Expected behavior

Bad code from above should fail at least one test, when in reality right now it passes all of them.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code or submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by paskal** [comment]
The code is under "Wrong answer, passing all current tests but not one above, output 4" spoiler, please click it and you'll see it.

**Comment by paskal** [comment]
Submission with code which is accepted but shouldn't be: https://leetcode.com/submissions/detail/751562894/
Submission with the correct code, which would be working still after the new test case introduction: https://leetcode.com/submissions/detail/751561759/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
