### ISSUE TITLE
测试用例包含隐含条件

### ISSUE THREAD

**Issue by kfyty** [LeetCode-Feedback/LeetCode-Feedback#826]
** Bug 类型**
-  测试用例

**描述**
我发现题目的所有测试用例都包含一个隐含条件，即顺着 next 进行查找，可以查找到所有的节点，而随机节点必定包含在 next 可查询到的节点中。
事实上，随机节点可以不包含在 next 可以查询到的节点中。

**你使用的语言**
Java

**示例节点**
![20200815232313567](https://user-images.githubusercontent.com/45265958/90585115-aab6a880-e206-11ea-95cb-a8c803af2f14.png)

**期望行为**
测试用例应包含示例图片中的例子，即存在沿着 next 查找不到的随机节点

**Comment by feiceh** [comment]
感谢反馈，该问题已转给相关团队后期会持续优化。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先关闭，后续有任何问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。

**Comment by feiceh** [comment]
你好，这个技术验证没有问题。题目说了链表了，不是隐含条件。请知晓。
