### ISSUE TITLE
Missing Test Case - 2242. Maximum Score of a Node Sequence

### ISSUE THREAD

**Issue by mehuldev** [LeetCode-Feedback/LeetCode-Feedback#8262]
#### Your LeetCode username

blackrose144

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug

My code does not work a specific test case but it gets accepted on Leetcode. Please add the test case.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maximumScore(vector<int>& scores, vector<vector<int>>& edges) {
        int n = scores.size();
        vector<vector<int>> adj(n);
        for(vector<int> &e: edges){
            adj[e[0]].push_back(e[1]);
            adj[e[1]].push_back(e[0]);
        }
        for(vector<int> &v: adj){
            sort(v.begin(), v.end(), [&](const int a, const int b){
                return scores[a] > scores[b];
            });
            while(v.size() > 3)
                v.pop_back();
        }
        //a - u - v - b
        int ans = -1;
        for(int u = 0; u < n; u++){
            for(int &v: adj[u]){
                for(int &a: adj[u]){
                    if(a == v)
                        continue;
                    for(int &b: adj[v]){
                        if(b == a or b == u)
                            continue;
                        ans = max(ans,scores[u]+scores[v]+scores[a]+scores[b]);
                    }
                }
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My code fails for the below test case but it gets accepted as this test case in not a part of Leetcode's collection.
scores = [100,1,1,10,10,10,10,10,10,100]
edges = [[1,0],[1,3],[1,4],[1,5],[2,6],[2,7],[2,8],[2,9],[1,2]]

#### Screenshots

![image](https://user-images.githubusercontent.com/64658167/179890987-27e1cb7f-fb3d-4173-b78a-3ba1d8b8d461.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
