### ISSUE TITLE
Missing Test Case - 792. Number of Matching Subsequences

### ISSUE THREAD

**Issue by Wxld** [LeetCode-Feedback/LeetCode-Feedback#8264]
#### Your LeetCode username

NotRandomGuy

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

- 1 <= s.length <= 5 * 10^4 
- 1 <= words.length <= 5000
- 1 <= words[i].length <= 50

So if we brute force and this and try to iterate over all the words over string `s`. Then the worst time complexity after 
assuming **S = string length**, **W = words length** will be `O(S*W)`
which will be around `25 * 10^7` or around `O(10e8)` which should give **TLE**.

And it did but when I used an hashmap after seeing that the words array have same words multiple times. I got an AC with good time.

For which I am happy, but it may give wrong idea to the beginners about the **Worst Time Complexity** since even after using hashmap to reduce the words length there may be a case when the size does not reduces , this happens when all the **word** in **words** are unique.

So I think addition of new testcase with all the words being unique of length (huge number ~5000) should be added in order to give TLE on brute force.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int numMatchingSubseq(string s, vector<string>& words) 
    {
        int ans = 0, n = s.size();
        
        unordered_map<string,int> m;
        // removing duplicates
        for(string &word : words) m[word]++;
        
       //iterating over all  unique words
        for(auto i : m)
        {
            int j = i.first.size()-1;
            //iterating over the string (assume j == -1 never hits i.e word is not a subsequence)
            for(int k=n-1; k>=0; --k)
            {
                if(j == -1) break;
                
                if(i.first[j] == s[k])
                {
                    --j;
                }
            }
            if(j == -1) ans += i.second;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should have given TLE.

#### Screenshots

<img width="957" alt="image" src="https://user-images.githubusercontent.com/77234540/179904492-052a5a8b-4f80-4a5f-9102-9b4d1ae0f773.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution is ok to pass under the current constraints. We appreciate your support!
