### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by TheCodeAlpha26** [LeetCode-Feedback/LeetCode-Feedback#8266]
#### Your LeetCode username
TheCodeAlpha

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug
There is a missing Test case
1000000000
1

#### Code you used for Submit/Run operation
Question Link : https://leetcode.com/problems/divide-two-integers/
Solution Link : https://leetcode.com/submissions/detail/741919942/

```
class Solution {
public:
    int divide( long long int dividend,  long long int divisor) {
        if (dividend == 0) return 0;
        long long int sign = (dividend < 0 && divisor < 0) || (dividend > 0 && divisor > 0) ? 1: -1;
        long long int output = sign * (exp(log(abs(dividend)) - log(abs(divisor))) + 0.0000000001);
        return output < INT_MAX ? output : INT_MAX;
    }
};
```

#### Language used for code
C++

#### Expected behavior
This code should fail at test case
1000000000
1
But it passes all the testcases

#### Screenshots

![Screenshot (3087)](https://user-images.githubusercontent.com/75980074/179918883-34dbe06a-955c-44c7-a15c-67fb16615cce.png)
![Screenshot (3088)](https://user-images.githubusercontent.com/75980074/179918895-99d08f5b-6067-495d-a003-3de0b12ac812.png)

#### Additional context

Missing test Case
1000000000
1

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
