### ISSUE TITLE
Missing Test Case - 1146. Snapshot Array

### ISSUE THREAD

**Issue by zsichina** [LeetCode-Feedback/LeetCode-Feedback#8268]
#### Your LeetCode username

zsichina

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

if the solution uses O(n^2) space, at least one test case should throw a "Memory Limit Exceeded" error. My solution uses O(n^2) space but passes all test cases.

#### Code you used for Submit/Run operation

```
class SnapshotArray:

    def __init__(self, length: int):
        self.changes = {}
        self.snaps = defaultdict(dict)
        self.snaps_cnt = 0

    def set(self, index: int, val: int) -> None:
        self.changes[index] = val

    def snap(self) -> int:
        for key, val in self.changes.items():
            self.snaps[key][self.snaps_cnt] = val
        self.snaps_cnt += 1
        return self.snaps_cnt - 1

    def get(self, index: int, snap_id: int) -> int:
        if index in self.snaps and snap_id in self.snaps[index]:
            return self.snaps[index][snap_id]
        return 0

```

#### Language used for code

Python

#### Expected behavior

At least one test case should fail by throwing the "Memory Limit Exceeded" error

#### Additional context

I've generated a new test case, using the code attached below. It makes 24,999 "set" operations and 25,000 "snap" operations.
The solution tries to create a dictionary with 24,999 (n/2) elements and then to copy it 25,000 (n/2) times and ends up throwing an error  

```
with open('testcase.txt', 'w') as file:

    file.write('["SnapshotArray"')
    
    for i in range(1, 25000):
        file.write(',"set"')

    for i in range(25000):
        file.write(',"snap"')

    file.write("]\n")


    file.write("[[50000]")
    for i in range(1, 25000):
        file.write(",[{},{}]".format(i,i))

    for i in range(25000):
        file.write(",[]")

    file.write("]")

```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. It is hard to make this solution MLE with the current constraints and increasing the constraints will make some AC solutions TLE. We appreciate your support!
