### ISSUE TITLE
Constraint in description and test case do not match - 1505

### ISSUE THREAD

**Issue by vishalg8454** [LeetCode-Feedback/LeetCode-Feedback#8269]
#### Your LeetCode username

vishalgaurav

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Problem https://leetcode.com/problems/minimum-possible-integer-after-at-most-k-adjacent-swaps-on-digits/

The max value for k in description is ```10^4``` in description.
<img width="438" alt="image" src="https://user-images.githubusercontent.com/66552164/179940351-6412414a-04f8-4059-860a-9b50acb30a93.png">

However the value of k in test case goes high to ```10^8``` in test cases. I have attached the submission link.
<img width="628" alt="image" src="https://user-images.githubusercontent.com/66552164/179940893-9064f208-67b9-48cc-9d1f-7d0174d0ab56.png">

https://leetcode.com/submissions/detail/751558724/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
