### ISSUE TITLE
877. Stone Game, always true

### ISSUE THREAD

**Issue by garciparedes** [LeetCode-Feedback/LeetCode-Feedback#827]
#### Problem 
[877. Stone Game](https://leetcode.com/problems/stone-game/)

#### Your LeetCode username

garciparedes

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

This problem tests passes if the implementation returns always true

#### Code you used for Submit/Run operation

```rust
impl Solution {
    pub fn stone_game(piles: Vec<i32>) -> bool {
        true
    }
}
```

#### Language used for code

Rust

#### Expected behavior

Probably, there is some kind of bug on the Rust Language solution validation because is so strange that all the test cases have  `true` value solutions.

**Comment by PsiACE** [comment]
Hi, one of the ways to solve this problem is to return `true` directly. Please read the problem description carefully or view the official solution. Good luck.

**Comment by garciparedes** [comment]
Ah! You're right! Thinking more carefully about the problem it makes sense. The first step provides winning warranties if it is chosen correctly due to the even length of the piles. Thanks! :wink:
