### ISSUE TITLE
Missing Test Case - 792. Number of Matching Subsequences

### ISSUE THREAD

**Issue by umangahuja1alt** [LeetCode-Feedback/LeetCode-Feedback#8270]
#### Your LeetCode username

umangahuja1alt

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

The constraints of given problem state that 
s = 5 * 10^4
words = 5000

Trying standard bruteforce solution performing operations > 10^8 will result in TLE but given the weak testcases, when using a hashmap to store already tried words, the repeated words will not be tested and number of operations will limit to len(s) i.e 5 * 10^4.

But this hack will result in TLE when large and distinct set of words are tested against the solution.

---
#### Sample test case file attached 
[test_cases2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9148332/test_cases2.txt)

With submitted test case 

```
No of operations : 249990624 i.e (2 * 10 ^ 8)
Expected Result : TLE 
Current behavior : Accepted 
```

#### Code you used for Submit/Run operation

```c++
class Solution {
    
private:
    int ops = 0;
    unordered_map <string, bool> store;
    
    bool isSubsequence(string s, string t) {
        int n = s.size();
        int m = t.size();
        
        int i = 0;
        int j = 0;
        
        if(store.find(t) != store.end())
            return store[t];
        
        for(; i<n && j<m && m-j <= n-i;) {
            ops++;
            if(s[i] == t[j])
                i++, j++;
            else
                i++;
        }
        store[t] = (j == m);
        return j == m;
        
    }
    
public:
    int numMatchingSubseq(string s, vector<string>& words) {
        
        int ans = 0;
        
        for(auto &word : words) {
            ans += isSubsequence(s, word);
        }
        cout << ops;
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Given the number of operations carried out in this approach are o the range 2 * 10^8, it should result in TLE.

#### Screenshots

![image](https://user-images.githubusercontent.com/89762312/179943453-25b12e25-a92c-4235-ba79-7ac40a16bb14.png)

#### Additional context

Sample test case file attached : 
[test_cases2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9148332/test_cases2.txt)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
