### ISSUE TITLE
35. Search Insert Position – incorrect description of overflow fix in Python

### ISSUE THREAD

**Issue by Yorko** [LeetCode-Feedback/LeetCode-Feedback#8271]
#### Your LeetCode username
Yorko

#### Category of the bug
- [x] Solution

#### Description of the bug

The provided Python version of the fix is incorrect. It should be `pivot = left + (right - left) // 2;` 

Screenshot
<img src="https://habrastorage.org/webt/zz/dc/er/zzdcerzrh-vy-yjdzol-p-rq-nc.png" />

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The reason that you think it's incorrect. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Yorko** [comment]
I thought for consistency it'd make sense to do `pivot = left + (right - left) // 2` in Python as well. But with a second read, I see that it's discussed that `pivot = (left + right) // 2` works fine with Python. Sorry for disturbing, my fault, the ticket can be closed.
