### ISSUE TITLE
面试题 16.14. 最佳直线

### ISSUE THREAD

**Issue by zhanghuaen** [LeetCode-Feedback/LeetCode-Feedback#8272]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
zhe

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ .] 缺少测试用例

**描述**
”面试题 16.14. 最佳直线“这道题目，采用以下测试用例：
[[0,0],[1,1],[1,0],[2,0],[2,2]]
得到的”预期结果“是：[0,2]
但正确的结果应该是：[0,1]

**你使用的语言**
Python

**你提交或者运行的代码**
```
无
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收。
