### ISSUE TITLE
Missing Test Case - 792. Number of Matching Subsequences

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#8273]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution is getting TLE on this test case:
[792 Missing Test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9151488/792.Missing.Test.txt)

#### Code you used for Submit/Run operation

```
public class Solution 
{
     public int NumMatchingSubseq(string S, string[] words) 
     {
        var dict = new Dictionary<char, List<int>>();
        for (int i = 0; i < S.Length; i++)
        {
            if (dict.ContainsKey(S[i]))
                dict[S[i]].Add(i);
            else dict.Add(S[i], new List<int>() {i});
        }

        return words.Count(word => IsSubsequence(word));

        bool IsSubsequence(string str)
        {
            int ind = -1;
            foreach (var ch in str)
            {
                if (!dict.ContainsKey(ch))
                    return false;
                int first = dict[ch].FirstOrDefault(i => i > ind);
                if (first <= ind)
                    return false;
                ind = first;
            }

            return true;
        }
    }
}
```

#### Language used for code

C#

#### Expected behavior

This code is passing all tests and getting Accepted. But it should get TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
