### ISSUE TITLE
Missing Test Case - 792. Number of Matching Subsequences

### ISSUE THREAD

**Issue by Mahim1997** [LeetCode-Feedback/LeetCode-Feedback#8275]
#### Your LeetCode username

mahim1997mahbub

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

According to problem constraints, 
- **Length of Big String <= 50000**
- **Number of words <= 5000**
- **Each word's length <= 50**

Using brute force, i.e. using two pointers to check if subsequence exists or not, and then repeating the code for each word in the list of words gives TLE (as expected) due to maximum number of operations being 50000 * 5000 * 50 = 1.25 * 10^10 (exceeding 10^8).
However, if answers are cached, then due to current test cases, the solution gets passed (instead of giving TLE).

Hence, new test cases should be necessary with distinct words in the word list, and which exhausts both the strings (i.e. the big string, and each string of the list of strings).

#### Code you used for Submit/Run operation

``` py
# 792. Number of Matching Subsequences
class Solution:
    def numMatchingSubseq(self, s: str, words: List[str]) -> int:
        cache = {}

        def isSubsequence(s: str, t: str) -> bool:
            idx = 0
            if len(s) == 0: ## Empty Strings edge case
                return True
            if (len(t) == 0) or (len(s) > len(t)):
                return False 

            for c in t:
                if (c == s[idx]):
                    idx += 1
                if idx == len(s):
                    return True

            return False
        
        cnt = 0
        for word in words:
            if word in cache:
                result = cache[word]
            else:
                result = isSubsequence(word, s)
                cache[word] = result
            
            if result:
                cnt += 1
                
        return cnt
```

#### Language used for code
Python

#### Expected behavior

The code above should give TLE, instead of getting accepted.

#### Screenshots

1. The code mentioned above getting accepted

![AcceptedSolutionUsingMap](https://user-images.githubusercontent.com/38731142/180039313-4be7ef06-2571-4b40-bc0b-d996853230e7.PNG)

2.  The code mentioned above getting TLE on the given test case

![TLE_on_test_case](https://user-images.githubusercontent.com/38731142/180039411-4cd26a00-bf6d-476d-a3ed-35d2158b1053.PNG)

#### Additional context

The test case is attached in the text file **Test Case - 792. Number of Matching Subsequences.txt**

[Test Case - 792. Number of Matching Subsequences.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9152158/Test.Case.-.792.Number.of.Matching.Subsequences.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution is ok to pass under the current constraints. We appreciate your support!
