### ISSUE TITLE
Missing Test Case - 1384. Total Sales Amount by Year

### ISSUE THREAD

**Issue by coanghel** [LeetCode-Feedback/LeetCode-Feedback#8276]
#### Your LeetCode username

coanghel

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution has product_id and report_year stored as strings despite the values in the base tables being int and date respectively. Since the question requires the result stored by these values, it is unintuitive that we have to "cast(variable as char)" in order for the order to match the solution

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
with recursive all_days as(
select
    min(period_start) as date
from
    sales
union all
select
    date_add(date,interval 1 day)
from all_days
where date<= (select max(period_end) from sales)
)

select
    t2.product_id,
    t3.product_name,
    cast(year(t1.date) as char) as report_year,
    sum(t2.average_daily_sales) as total_amount
from
    product t3
join sales t2
on t3.product_id=t2.product_id
join all_days t1
on t1.date<=t2.period_end and t1.date>=t2.period_start
group by t3.product_id,report_year
order by cast(t3.product_id as char),report_year
    
    
```

#### Expected behavior

I would recommend one of the below resolutions:

- Remove the order requirement from the solution
- Correct the solution so that product_id and report_year are int and date values respectively
- Specify in the question that the final table must have product_id and report_year returned as strings

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
