### ISSUE TITLE
Missing Test Case - 30. Substring with Concatenation of All Words

### ISSUE THREAD

**Issue by Karandeep1234** [LeetCode-Feedback/LeetCode-Feedback#8277]
#### Your LeetCode username

Karandeep1234

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gives WA on following testcase. It was expected not to be accepted. In java boxing range for Integer is -128 to 128. 
Testcase on which my code gives WA:
[testcaselc30.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9153704/testcaselc30.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public List<Integer> findSubstring(String s, String[] words) {
        HashMap<String,Integer> fmap = new HashMap<>();
        for(String word : words){
            fmap.put(word, fmap.getOrDefault(word, 0) + 1);
        }
        List<Integer> ans = new ArrayList<>();
        int k = words[0].length();
        int n = words.length;
        for(int i = 0; i < s.length() - n * k + 1; i++){
            HashMap<String,Integer> hm = new HashMap<>();
            
            for(int j = 0 ; j < n ; j++){
                int nx = i + j*k;
                
                String nw = s.substring(nx, nx + k);
                
                if(!fmap.containsKey(nw) || (hm.getOrDefault(nw, 0))==(fmap.get(nw))){
                    // Since Integer is boxed we should not use "==" here
                    break;
                }
                hm.put(nw,hm.getOrDefault(nw, 0)+1);
                
                if(j == n - 1){
                    ans.add(i);
                }              
            }
        }
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

It was expected not to be accepted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
