### ISSUE TITLE
Error in Example 1 Explanation - 15. 3Sum

### ISSUE THREAD

**Issue by askiefer** [LeetCode-Feedback/LeetCode-Feedback#8278]
#### Your LeetCode username

askiefer

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is an error in the explanation test case. This is what it currently is:
```
Input: nums = [-1,0,1,2,-1,-4]
Output: [[-1,-1,2],[-1,0,1]]
Explanation: 
nums[0] + nums[1] + nums[1] = (-1) + 0 + 1 = 0.
```
I believe the last line should actually be (change the index of last ele from 1 to 2):
```
nums[0] + nums[1] + nums[2] = (-1) + 0 + 1 = 0.
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Problem already fixed. We appreciate your support!
