### ISSUE TITLE
951. Flip Equivalent Binary Trees - contribute a test case

### ISSUE THREAD

**Issue by JerryL1987** [LeetCode-Feedback/LeetCode-Feedback#828]
#### Your LeetCode username

Chihhung Li

#### Description of the bug

Missing a test case which root1's value is different with root2's value
EX:
[1,2,3,4,5,6,null,null,null,7,8]
[15,3,2,null,6,4,5,null,null,null,null,8,7]

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     struct TreeNode *left;
 *     struct TreeNode *right;
 * };
 */


bool flipEquiv(struct TreeNode* root1, struct TreeNode* root2){
    bool ret = true;
    if (root1 == NULL && root2 == NULL) {
        return true;
    }
    if (root1 == NULL || root2 == NULL) {
        return false;
    }
    int root1_child = (root1->left) ? 1 : 0 + (root1->right) ? 1 : 0;
    int root2_child = (root2->left) ? 1 : 0 + (root2->right) ? 1 : 0;
    if (root1_child != root2_child) {
        return false;
    }
    if (root1->left) {
        if (root2->left && root2->left->val == root1->left->val) {
            ret = flipEquiv(root1->left, root2->left);
        } else if (root2->right && root2->right->val == root1->left->val) {
            ret = flipEquiv(root1->left, root2->right);
        } else {
            ret = false;
        }
        if (ret == false) {
            return ret;
        }
    }
    if (root1->right) {
        if (root2->left && root2->left->val == root1->right->val) {
            ret = flipEquiv(root1->right, root2->left);
        } else if (root2->right && root2->right->val == root1->right->val) {
            ret = flipEquiv(root1->right, root2->right);
        } else {
            ret = false;
        }
        if (ret == false) {
            return ret;
        }
    }
    return ret;
}
```

#### Language used for code

C

#### Expected behavior

It will return true with above code for the test case I mentioned.
It is incorrect but current test cases didn't contain this kind of case.
Hence, my code is accepted.

**Comment by JerryL1987** [comment]
![image](https://user-images.githubusercontent.com/46712380/90620149-aa3d0280-e244-11ea-8054-767636f37fda.png)

**Comment by lc-pam** [comment]
Hi @JerryL1987 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @JerryL1987 
Thank you for your time. We've used your feedback to update the problem. Would you mind providing your LeetCode ID for us to reward Leetcoins to your account? Thank you for your support!

**Comment by JerryL1987** [comment]
Hi @lc-pam ,
Below is my leetcode ID.
LeetCode ID: Chihhung

**Comment by lc-pam** [comment]
Hi @JerryL1987 
Thanks for providing your LeetCode ID! Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
