### ISSUE TITLE
Missing test case for 792. Number of Matching Subsequences

### ISSUE THREAD

**Issue by desai10** [LeetCode-Feedback/LeetCode-Feedback#8280]
#### Your LeetCode username
desai10

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
I don't think there is a test case which tests the worst case.
Algorithms which aren't the most optimal (basically brute force) show as being the fastest!

I want to add a  test case which tests the worst case. The string `s` should be of length 5 * 10^4 and all letters are `a`. Then there should be 5000 unique strings in `words` which don't contain `a`.

When you run the brute force algorithm (`O(s.length * words[].length * word.length)`) with that input it runs in about 1300ms. But my code runs in 15ms.

Either the brute force solution should get time limit exceeded or at least they should not be shown as the fastest solution!

#### Code you used for Submit/Run operation
```
class Solution {
    public int numMatchingSubseq(String s, String[] words) {
        Map<Character, List<Integer>> ma = new HashMap<>();
        for (int i = 0;i < s.length();i++) {
            if (!ma.containsKey(s.charAt(i))) {
                ma.put(s.charAt(i), new ArrayList<>());
            }
            ma.get(s.charAt(i)).add(i);
        }
        
        int ans = 0;
        
        for (String word : words) {
            int cur = 0;
            boolean done = true;
            Map<Character, Integer> maa = new HashMap<>();
            for (int i = 0;i < word.length();i++) {
                if (!ma.containsKey(word.charAt(i))) {
                    done = false;
                    break;
                }
                int c = 0;
                if (maa.containsKey(word.charAt(i))) {
                    c = maa.get(word.charAt(i));
                } else {
                    maa.put(word.charAt(i), 0);
                }
                while (c < ma.get(word.charAt(i)).size() && ma.get(word.charAt(i)).get(c) < cur) {
                    maa.put(word.charAt(i), ++c);
                }
                
                if (c == ma.get(word.charAt(i)).size()) {
                    done = false;
                    break;
                }
                
                cur = ma.get(word.charAt(i)).get(c) + 1;
                maa.put(word.charAt(i), ++c);
            }
            
            if (done) {
                ans += 1;
            }
        }
        
        return ans;
    }
}
```

New test case - 
s = "aaaaa.......aaaaaa" (50000 length string, all letters `a`)
`words` should have 5000 unique words and none of them should contain the letter `a`.

(not typing in the whole test case here because it's huge! But I have attached the screenshot...)

#### Language used for code
JAVA

#### Expected behavior
Either the solutions using brute force should get time limit exceeded or they should not be shown as the fastest solution (because clearly they are NOT the fastest).

#### Screenshots
Brute Force -
<img width="1192" alt="Screenshot 2022-07-21 at 8 30 40 AM" src="https://user-images.githubusercontent.com/20340704/180120698-68957000-49de-4d72-baa0-d4571030d54b.png">

Not brute force - 
<img width="1188" alt="Screenshot 2022-07-21 at 8 31 38 AM" src="https://user-images.githubusercontent.com/20340704/180120768-b86b6c49-0dd7-48c6-93c8-b25babed4c69.png">

**Comment by LC-Pam** [comment]
Thank you for your time. The solution is ok to pass under the current constraints. We appreciate your support!
