### ISSUE TITLE
Typing error in example 1 - 15. 3Sum

### ISSUE THREAD

**Issue by ritik33** [LeetCode-Feedback/LeetCode-Feedback#8287]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Below is example 1 in which explanation has nums[1] written twice.
Correct one will be nums[0] + nums[1] + **nums[2]** = (-1) + 0 + 1 = 0.

_Example 1_
Input: nums = [-1,0,1,2,-1,-4]
Output: [[-1,-1,2],[-1,0,1]]
Explanation: 
nums[0] + nums[1] + nums[1] = (-1) + 0 + 1 = 0.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Problem already fixed. We appreciate your support!
