### ISSUE TITLE
Question - 2346. Compute the Rank as a Percentage

### ISSUE THREAD

**Issue by 0417taehyun** [LeetCode-Feedback/LeetCode-Feedback#8288]
#### Your LeetCode username

0417taehyun

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

We need more details on the question part about how to handle the duplicated `mark` fields.

If the test case looks like the below,

```JSON
{
  "headers":{
    "Students":[
      "student_id", "department_id", "mark"
    ]
  },
  "rows":{
    "Students":[
      [8, 4, 860],
      [13, 3, 40],
      [3, 1, 130],
      [9, 3, 40],
      [2, 3, 20],
      [12, 3, 390],
      [4, 2, 270],
      [6, 4, 670],
      [11, 2, 150],
      [7 ,2, 130],
      [14, 3, 790],
      [10, 1, 900],
      [1, 4, 910],
      [5, 1, 610]
    ]
  }
}
```

it is visualized like the below image.

![Visualized the test case](https://user-images.githubusercontent.com/63915557/180362978-2d563e6e-3dd5-414d-8570-28b3f36e7f92.png)

Thus, the rank of a student whose `student_id` field is `2` could be both `3` and `4`  because there are two duplicated `mark` whose `student_id` fields are `9` and `13`, which their `mark` field is same as `40`.

Users can solve this question by using `RANK` as you can see on the *Code you used for Submit/Run operation* part.

However, users couldn't get any hints on how to handle the duplicated `mark` field, as it can cause them to use `DENSE_RANK` instead of `RANK`.

As a consequence, I suggest adding more details to the description part or changing a little of the example test case like this.

```
Input: 
Students table:
+------------+---------------+------+
| student_id | department_id | mark |
+------------+---------------+------+
| 2          | 2             | 650  |
| 8          | 2             | 650  |
| 7          | 1             | 920  |
| 1          | 1             | 610  |
| 3          | 1             | 610  |
| 9          | 1             | 480  |
+------------+---------------+------+
Output: 
+------------+---------------+------------+
| student_id | department_id | percentage |
+------------+---------------+------------+
| 7          | 1             | 0.0        |
| 1          | 1             | 33.3       |
| 3          | 1             | 33.3       |
| 9          | 1             | 100.0      |
| 2          | 2             | 0.0        |
| 8          | 2             | 0.0        |
+------------+---------------+------------+
Explanation: 
For Department 1:
 - Student 7: percentage = (1 - 1) * 100 / (4 - 1) = 0.0
 - Student 1: percentage = (2 - 1) * 100 / (4 - 1) = 33.3
 - Student 3: percentage = (2 - 1) * 100 / (4 - 1) = 33.3
 - Student 9: percentage = (4 - 1) * 100 / (4 - 1) = 100.0
For Department 2:
 - Student 2: percentage = (1 - 1) * 100 / (2 - 1) = 0.0
 - Student 8: percentage = (1 - 1) * 100 / (2 - 1) = 0.0
```

The JSON of this example test case looks like the below.

```JSON
{
  "headers": {
    "Students": [
      "student_id", "department_id", "mark"
    ]
  },
  "rows": {
    "Students": [
      [2, 2, 650],
      [8, 2, 650],
      [7, 1, 920],
      [1, 1, 610],
      [3, 1, 610],
      [9, 1, 480]
    ]
  }
}
```

#### Code you used for Submit/Run operation

```SQL
SELECT
    student_id,
    department_id,
    IFNULL(ROUND(
        ((RANK() OVER(PARTITION BY department_id ORDER BY mark DESC) - 1) * 100)
        /
        (COUNT(student_id) OVER(PARTITION BY department_id) - 1),
        2
    ), 0) AS percentage
FROM Students;
```

#### Language used for code

MySQL

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've added an additional statement to explain this scenario. We appreciate your support!
