### ISSUE TITLE
Missing test case for 767. Reorganize String

### ISSUE THREAD

**Issue by liuchengtian** [LeetCode-Feedback/LeetCode-Feedback#8289]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A testcase with length of 1 should raise index out of range error in the following code, but the code gets AC. 

Example testcase: "a".

#### Code you used for Submit/Run operation

```
// 767. Reorganize String
class Solution:
    def reorganizeString(self, s: str) -> str:
        cnt = Counter(s)
        ans = [''] * len(s)
        cur = 0
        for k, v in sorted(cnt.items(), key=lambda x: -x[1]):
            for i in range(v):
                ans[cur] = k
                cur += 2
                if cur >= len(s):
                    cur = 1
        if ans[0] == ans[1]:
            return ""
        return ''.join(ans)
```

#### Language used for code

Python3.

#### Expected behavior

Throw index out of range error.

#### Screenshots

submission result.
![1](https://user-images.githubusercontent.com/20579757/180364991-8c6f38fd-5564-4c91-a458-de64f9f9d2c8.png)
test result.
![2](https://user-images.githubusercontent.com/20579757/180365314-7de5078e-7f62-48f5-ba8c-75bea7932cdb.png)

#### Additional context

Please add testcase "a".

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Would you mind sending us your username?

**Comment by liuchengtian** [comment]
my username is alastian

**Comment by LC-Pam** [comment]
Points Issued
