### ISSUE TITLE
Missing Test Case - 250. Count Univalue Subtrees

### ISSUE THREAD

**Issue by iemeka** [LeetCode-Feedback/LeetCode-Feedback#829]
#### Your LeetCode username

0emeka

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Accepted solution but won't pass the test case: [5,1,5,5,5,null,5,null,null,null,null,null,5]

#### Code you used for Submit/Run operation
```
// 250. Count Univalue Subtrees
class Solution(object):
    def countUnivalSubtrees(self, root):
        """
        :type root: TreeNode
        :rtype: int
        """
        def childIsLeaf(root):
            if not root.left and not root.right:
                return True
            return False
            
        def findUnival(root,count):
            stack = []
            while stack or root:
                while root:
                    stack.append(root)
                    root = root.left
                root = stack.pop()
                if root.left and root.right:
                    if root.val == root.left.val and root.val  == root.right.val:
                        count+=1
                elif root.left or root.right:
                    child = root.left or root.right
                    if root.val == child.val and childIsLeaf(child): count+=1
                elif childIsLeaf(root): count+=1
                root = root.right
            else: return count
        return findUnival(root,0)
```

#### Language used for code

Python 2

#### Expected behavior

Solution should not be accepted since it failed the test case

#### Screenshots

![Screenshot from 2020-08-19 10-39-38](https://user-images.githubusercontent.com/10095449/90619371-11d55c80-e209-11ea-8eca-04b2f5c366bc.png)

#### Additional context

https://leetcode.com/problems/count-univalue-subtrees/

**Comment by lc-pam** [comment]
Hi @iemeka 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @iemeka 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
