### ISSUE TITLE
5.最长回文子串

### ISSUE THREAD

**Issue by Ymeki** [LeetCode-Feedback/LeetCode-Feedback#8292]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
一将功成万骨枯＇

**Bug 类型**
- [ ] 题目
- [ √] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
提交解答错误，在测试用例时通过

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    string longestPalindrome(string s) {
        //递归
        int j,f=0,e=0;
        static int len=1;
        for(int i = 0;i+len<s.length();i++){
            for(j=i+len;j<s.length();j++){
                if(ifhwz(i,j,s)){
                    if(len<j-i+1){
                        f = i;
                        e = j;
                        len = j-i+1;
                    }
                }
            }
        }
        string ans = s.substr(f,len);
        return ans;
    }
    bool ifhwz(int f,int e,string s){
        if((int)s[f]!=(int)s[e]){
            return false;
        }else if(f==e||f==e-1){
            return true;
        }else {
            return ifhwz(f+1,e-1,s);
        }
    }
};
```

**期望行为**
通过

**屏幕截图**
![debug](https://user-images.githubusercontent.com/53247612/180397971-95712228-fd8c-40e1-8669-1b660ad6b570.png)

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
![origin_img_v2_6ba65357-66da-4794-a8ab-68cb096ff3bg](https://user-images.githubusercontent.com/99636790/180419847-b8f91643-1be2-4472-8f69-c70d786f6a78.jpg)

**Comment by Ymeki** [comment]
LeetCode：
感谢答复，您的意思是静态变量在之前的运算中存储了错误值3导致的。
感谢您的悉心解答。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] 5.最长回文子串 (Issue #8292)
