### ISSUE TITLE
Incorrect Description - 2346. Compute the Rank as a Percentage

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8294]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [2346. Compute the Rank as a Percentage](https://leetcode.com/problems/compute-the-rank-as-a-percentage), the definition of table `Students` mentions that user_id is the primary key of this table. This is not correct, since table `Students` does not have a column name `user_id`. Instead, the primary key should be `student_id`.

#### Expected behavior
The primary key should be changed to `student_id` instead of `user_id`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback fixed this issue We appreciate your support!
