### ISSUE TITLE
缺少测试用例--757. 设置交集大小至少为2

### ISSUE THREAD

**Issue by charleszhangjie** [LeetCode-Feedback/LeetCode-Feedback#8295]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
charleszzz

**Bug 类型**
- [ ] 题目 [757. 设置交集大小至少为2](https://leetcode.cn/problems/set-intersection-size-at-least-two/)
- [ ] 题解
- [ ] 编程语言 golang
- [x] 缺少测试用例

**描述**

有一个用例使用AC的代码会得到和答案不同的结果，用例输入
`[[31,619],[40,740],[46,130],[64,466],[86,1036],[130,398],[189,1026],[194,1112],[208,508],[213,651],[234,549],[361,1102],[365,551],[368,1298],[409,659],[442,964],[481,1209],[522,742],[576,1553],[576,1500],[648,1036],[656,773],[662,1557],[735,1370],[763,1654],[782,785],[924,1324],[947,1079],[979,1306],[992,1566]]`
       

**你使用的语言**
Golang

**你提交或者运行的代码**
```
func intersectionSizeTwo(intervals [][]int) int {
	sort.Slice(intervals, func(i, j int) bool {
		if intervals[i][0] != intervals[j][0] {
			return intervals[i][0] < intervals[j][0]
		}
		return intervals[i][1] > intervals[j][1]
	})

	table := make(map[int]int)
	for _, r := range intervals {
		f, t := r[0], r[1]
		for k, v := range table {
			if k <= f && t <= v {
				delete(table, k)
				break
			}
		}
		table[f] = t
	}

	var left, right []int
	for k, v := range table {
		left = append(left, k)
		right = append(right, v)
	}
	sort.Ints(left)
	sort.Ints(right)

	var ans []int
	for len(right) > 0 {
		r := right[0]
		// 找小于r的最大left
		maxL := sort.Search(len(left), func(i int) bool { return left[i] >= r })
		small, big := left[maxL-1], r
		if len(ans) == 0 || ans[len(ans)-1] < small {
			ans = append(ans, small)
		}
		ans = append(ans, big)
		if maxL == len(left) {
			break
		}
        if left[maxL] == ans[len(ans)-1] {
			ans = append(ans, table[left[maxL]])
			maxL++
		}
		right = []int{}
		for i := maxL; i < len(left); i++ {
			right = append(right, table[left[i]])
		}
		left = left[maxL:]
		sort.Ints(right)
	}
	return len(ans)
}
```

**期望行为**
解答错误

**屏幕截图**
上述代码已经显示解答通过，但是构造的反例并不能通过。
![WA](https://user-images.githubusercontent.com/12245079/180447890-1b899dd4-6c9c-4277-93c1-93e939fe5380.png)

**额外的上下文**
用例输入为
[[31,619],[40,740],[46,130],[64,466],[86,1036],[130,398],[189,1026],[194,1112],[208,508],[213,651],[234,549],[361,1102],[365,551],[368,1298],[409,659],[442,964],[481,1209],[522,742],[576,1553],[576,1500],[648,1036],[656,773],[662,1557],[735,1370],[763,1654],[782,785],[924,1324],[947,1079],[979,1306],[992,1566]]

**Comment by feiceh** [comment]
您好，在与相关团队核实后：已有相似用例。以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
