### ISSUE TITLE
Wrong space complexity - 802. Find Eventual Safe States

### ISSUE THREAD

**Issue by Vinayaka2k** [LeetCode-Feedback/LeetCode-Feedback#8296]
#### Your LeetCode username

vinuvinayaka2000

#### Category of the bug
- [ ] Question
- [Y] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Space complexity of Solution Approach 1 has to be changed from : 
 O(N)

To:
O(N+E)
where N is the number of nodes in the given graph, and E is the total number of edges.

Since O(E) space is also to be considered since we build the reversed adjacency list from the initial adjacency list

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
