### ISSUE TITLE
剑指 Offer II 027. 回文链表

### ISSUE THREAD

**Issue by night-cruise** [LeetCode-Feedback/LeetCode-Feedback#8297]
**你的 LeetCode 用户名**
night-cruising

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例
- [x] 测试bug

**描述**
对于同样的测试用例 `[0, 0]`，控制台的测试结果和最终提交的测试结果不一致。

**你使用的语言**
Go

**你提交或者运行的代码**
```Go
var frontPtr *ListNode

func isPalindrome(head *ListNode) bool {
    if head == nil {
        return true
    }
    if frontPtr == nil {
        frontPtr = head
    }
    if !isPalindrome(head.Next) {
        return false
    }
    if frontPtr.Val != head.Val {
        return false
    }
    frontPtr = frontPtr.Next
    return true
}
```

**期望行为**
对于测试用例 `[0, 0]`，最终提交后的测试结果应该与控制台的测试结果一致。

**屏幕截图**
最终提交的测试结果中，对于测试用例 `[0, 0]` 显示没有通过：
![1](https://user-images.githubusercontent.com/77157236/180489011-56b80c28-2b74-4643-8ac2-54feb425595c.png)

但是，在控制台中对于同样的测试用例，是正常通过的：
![2](https://user-images.githubusercontent.com/77157236/180489024-2c200f82-0750-47d6-8c50-5638c67ce967.png)

**Comment by Scared-Heart** [comment]
same issue
here is the code
```
/**
 * Definition for singly-linked list.
 * function ListNode(val, next) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.next = (next===undefined ? null : next)
 * }
 */
/**
 * @param {ListNode} head
 * @return {boolean}
 */
const arr = []
var isPalindrome = function (head) {

    if(!head.next) return true
    while (head) {
        arr.push(head.val)
        head = head.next
    }
    let j = arr.length - 1
    for (let i = 0; i < j; i++) {
        if (arr[i] !== arr[j]) return false
        j--
    }

    return true
};
```

**Comment by BrambleWave** [comment]
使用了全局变量，连续验证多个用例时，frontPtr 会延续之前用例的结果，建议进行初始化

**Comment by BrambleWave** [comment]
![origin_img_v2_6dacdbf1-c768-4a76-9836-b02f94da7e3g](https://user-images.githubusercontent.com/99636790/180935772-92e3e8f1-5b29-48f5-8959-315028791fb9.jpg)
