### ISSUE TITLE
1060 Missing Element in Sorted Array Solution Time Complexity is Incorrect

### ISSUE THREAD

**Issue by SpaIns** [LeetCode-Feedback/LeetCode-Feedback#83]
**What kind of the bug**
- [ ] problem
- [X] solution
- [ ] language

**Describe the bug**
The given time complexity for both solutions provides O(1) as an answer in a given scenario, but that's not how time complexity analysis works.  The big O time complexity for the given algorithms are O(N) and O(logN) always, you cannot add a caveat and say 'in this specific case it's constant time!'  This should be corrected.  There are many supporting comments under the given solution as well.

**Comment by CooperCooperCooper** [comment]
Hi @SpaIns,
Thank you for reaching out to us! I've relayed your issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @SpaIns,
Thank you for the timely feedback! The article is now updated.

**Comment by SpaIns** [comment]
It may be worth adding a note to the top of the solution article along these lines:

"NOTE: The time complexity in this article has been adjusted as of 4-1-2020"

In order to reduce confusion when new readers see the old comments lambasting the complexity analysis.
