### ISSUE TITLE
Parent and Descendants! - Another Missing test case  - 250. Count Univalue Subtrees

### ISSUE THREAD

**Issue by iemeka** [LeetCode-Feedback/LeetCode-Feedback#830]
#### Your LeetCode username

0emeka

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Accepted solution but won't pass the test case: [5,5,5,6,3,null,1]

#### Code you used for Submit/Run operation
```
// 250. Count Univalue Subtrees
class Solution(object):
    def countUnivalSubtrees(self, root):
        """
        :type root: TreeNode
        :rtype: int
        """
        def childIsLeaf(root):
            if not root.left and not root.right:
                return True
            return False
        def has_one_val(root,values):
            if root:
                values.add(root.val)
                has_one_val(root.left,values)
                has_one_val(root.right,values)
                return values
        def findUnival(root,count):
            stack = []
            while stack or root:
                while root:
                    stack.append(root)
                    root = root.left
                root = stack.pop()
                if root.left and root.right:
                    if root.val == root.left.val and root.val  == root.right.val:count+=1
                elif root.left or root.right:
                    child = root.left or root.right
                    if root.val == child.val:
                        if childIsLeaf(child) or len(has_one_val(child,set())) == 1: count+=1
                elif childIsLeaf(root): count+=1
                root = root.right
            else: return count
        return findUnival(root,0)
```

#### Language used for code

Python 2

#### Expected behavior

Solution should not be accepted since it failed the test case

#### Screenshots

![newtc](https://user-images.githubusercontent.com/10095449/90626035-4ef21c80-e212-11ea-8bf3-6858e66e1ce1.png)

#### Additional context

On submission, Leet code is only testing direct parent and direct children relationship instead of parent and all descendants
Hence, For some solutions, test case with 'no univalue relationship' between parent and decendants fails when you 'Run Code' even if On submission, solution is accepted 

https://leetcode.com/problems/count-univalue-subtrees/

**Comment by lc-pam** [comment]
Hi @iemeka 
Thank you for reaching out to us. I'm trying to use the code you provided to reproduce the issue but received Runtime Error. Would you please provide your submission link or check the code again? 
<img width="1667" alt="Screen Shot 2020-08-20 at 5 54 12 PM" src="https://user-images.githubusercontent.com/67175512/90840275-67476180-e30e-11ea-95af-f41b77a4c955.png">

**Comment by lc-pam** [comment]
Hi @iemeka 
Thanks for your time. Looks like the team has added the problem thanks to your [previous report](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/829), I tested your code again and now it received Wrong Answer and failed "[1,1,1,5,5,null,5]".
