### ISSUE TITLE
缺少测试用例，不应该通过的测试用例确通过了

### ISSUE THREAD

**Issue by Code-1996626B** [LeetCode-Feedback/LeetCode-Feedback#8300]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**小B**
[https://leetcode.cn/u/xiao-b/](url)
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ @] 缺少测试用例

**描述**
提交的代码在网站上通过了，但是发现了一组用例，运行提交的代码得到的结果是错误的，故怀疑网站上缺少测试用例。

**你使用的语言**
JAVA

**你提交或者运行的代码**
```
// Two Sum
class Solution {
    public boolean sequenceReconstruction(int[] nums, int[][] sequences) {
       int n = nums.length;
        int[] arr = new int[n+1];
        arr[0] = -1;
        for(int[] sequence : sequences){
            for(int i=1; i<sequence.length; i++){
                arr[sequence[i]] = sequence[i-1] > arr[sequence[i]] ? sequence[i-1] : arr[sequence[i]];
            }
        }
        int p = nums[n-1];
        while(p != -1){
            p = arr[p];
            n--;
        }
        return n == -1;
    }
}
```

**期望行为**
nums[ ] = {5,4,3,2,1}, sequences[ ][ ] = {{5,4}, {5, 3}, {5, 2},{5,1},{4,3},{3,2},{2,1}};

**屏幕截图**
![1658538253540](https://user-images.githubusercontent.com/55232990/180584459-76559286-f8d8-4c13-8174-417bd568cb00.png)

**额外的上下文**
这段代码在网站上通过了，但是对于这组测试用例应该的结果是true的，但是运行之后却是false

**Comment by feiceh** [comment]
你好，当前该题已添加测试用例， 已给予积分奖励，请查收。
