### ISSUE TITLE
Missing Test Case - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by krnets** [LeetCode-Feedback/LeetCode-Feedback#8302]
#### Your LeetCode username
krnets

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

See the following discussion: 

https://leetcode.com/problems/serialize-and-deserialize-binary-tree/discuss/2298617/1-line-creative-trick-to-pass-based-on-the-judges-holefaster-9905-less-than-9981/1502568

#### Code you used for Submit/Run operation

```cpp
class Codec {
public:

    // Encodes a tree to a single string.
    TreeNode* serialize(TreeNode* root) {
        return root;
    }

    // Decodes your encoded data to tree.
    TreeNode* deserialize(TreeNode* data) {
        return data;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

Expect to fail test.
Instead, it passes tests (according to discussion in the link above).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We do not intend to change this for now. The problem was designed for practice. We appreciate your support!
