### ISSUE TITLE
Test case passing in `Run` but not in `Submission` during BiWeekly Copntest

### ISSUE THREAD

**Issue by ramen-7** [LeetCode-Feedback/LeetCode-Feedback#8305]
#### Your LeetCode username
shivam_taneja

#### Category of the bug
-  Question

#### Description of the bug

[2349. Design a Number Container System ] or Q3 during Leetcode BiWeekly Contest 83
How is a particular test case passing when I run it as custom test case during the contest but during the submission it throws TLE?

#### Code you used for Submit/Run operation

```Java
class NumberContainers 
{
    HashMap<Integer, Integer> map = new HashMap<>();
    public NumberContainers() 
    {
        
    }
    
    public void change(int index, int number) 
    {
        map.put(index, number);
    }
    
    public int find(int number) 
    {
        int ans = Integer.MAX_VALUE;
            for(int i : map.keySet())
            {
                if(map.get(i)==number)
                    ans = Math.min(ans, i);
            }
        if(ans == Integer.MAX_VALUE)
            return -1;
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

If a test case is passing in run as example test case, why is it throwing a TLE in submission?
Why is this happening during a contest?

#### Screenshots

![image](https://user-images.githubusercontent.com/76044999/180613415-3774109f-9eec-4bd8-8f05-b2c2b73de943.png)

**Comment by bogoconic1** [comment]
This is because the execution time is the sum of all the test cases combined. You may pass one test case but total time is too slow

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've rejudged yoursubmission. We appreciate your support!
