### ISSUE TITLE
Missing Test Case - 2347. Best Poker Hand

### ISSUE THREAD

**Issue by arbitrarymahi** [LeetCode-Feedback/LeetCode-Feedback#8306]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
There is one testcase which is missing from the code. I had a bug in my  code but there was no testcase to detect it. After the problem is published, when I created a testcase and used on my code it showed expected behaviour by showing that my code is incorrect, but when I submit my code It still gets accepted.

The issue is actually in the suits list. if I take the following test case 
```
["b","b","a","a","a"]
```
with any rank list, it should not accept the answer "Flush"  but in my code the output was flush and it was accepted.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    string bestHand(vector<int>& ranks, vector<char>& suits) {
        int a;int b; int c; int d;
        
        if(suits[0]==suits[1] && suits[2]==suits[3] && suits[3]==suits[4]) return "Flush";
        
        sort(ranks.begin(), ranks.end());
        int count = 1;
        int ans = 0;
        int card = ranks[0];
        for(int i=1;i<ranks.size(); i++){
            if(ranks[i]==card){
                count++;
            }else{
                card = ranks[i];
                count = 1;
            }
            ans=  max(ans, count);
        }
        if(ans >= 3)return "Three of a Kind";
        else if(ans == 2) return "Pair";
        else return "High Card";
    }
};
```

#### Language used for code

C++

#### Expected behavior

For this type of testcases
```
["b","b","a","a","a"]
```
it should not accept the answer "Flush"  but in my code the output was flush and it was accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/24491838/180614625-da2b340a-ca5a-4daf-9114-95840931b4ad.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
