### ISSUE TITLE
[Missing Test Case] 1229. Meeting Scheduler

### ISSUE THREAD

**Issue by shubham1402** [LeetCode-Feedback/LeetCode-Feedback#8310]
#### Your LeetCode username
coding_mess

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The expected output of my test-cases different from our judger's output.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> minAvailableDuration(vector<vector<int>>& slots1, vector<vector<int>>& slots2, int duration) {
        int n = slots1.size();
        int m = slots2.size();
        
        map<int, int> avail;
        for(int i=0;i<n;i++){
            avail[slots1[i][0]]++;
            avail[slots1[i][1]+1]--;
        }
        
        for(int i=0;i<m;i++){
            avail[slots2[i][0]]++;
            avail[slots2[i][1]+1]--;
        }
        
        int occ = 0;
        int prev = 0;
        for(auto& [key, val]: avail){
            if(occ == 2 && prev != -1){
                if(key - prev - 1 >= duration){
                    return {prev, prev+duration};
                }
            }
            occ += val;
            if(occ != 2){
                prev = -1;
            }else if(prev == -1){
                prev = key;
            }
        }
        return {};
    }
};

```

#### Language used for code
C++ 

#### Expected behavior
Input 
[[0,10],[11,20]]
[[0,20]]
20

Expected Output
[0,20]

The judge outputs []

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
