### ISSUE TITLE
Missing Test Case - 589. N-ary Tree Preorder Traversal

### ISSUE THREAD

**Issue by SunnyHuangCodebase** [LeetCode-Feedback/LeetCode-Feedback#8311]
#### Your LeetCode username
SunnyHuangCodeBase

#### Category of the bug
- [ ]  Question
- [ ]  Solution
- [ ]  Language
- [ ]  Missing Test Cases

#### Description of the bug

Adding a 'nodes' parameter with an empty list as the default argument to the preorder method produces the wrong answer.

#### Code you used for Submit/Run operation

```
class Solution:
    def preorder(self, root: 'Node', nodes = list()) -> List[int]:
        if root:
            nodes.append(root.val)

            for node in root.children:
                self.preorder(node, nodes)
                
        return nodes
```

#### Language used for code

Python 3

#### Expected behavior

Without the following code added to the first line of the 'preorder' method, the executed code is marked as wrong.
With the code added, it is marked as correct.
```
if not nodes:
    nodes = list()
```
However, this is redundant, as the parameter 'nodes' should already be an empty list if nodes is None.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. This happens because nodes is initialized only once.  We appreciate your support!
