### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by bulend-karadag** [LeetCode-Feedback/LeetCode-Feedback#8313]
#### Your LeetCode username
dnelub

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I am receiving "wrong answer" for the following simple code which works perfectly in my terminal. 

#### Code you used for Submit/Run operation
```
class Solution(object):
    def findMedianSortedArrays(self, nums1, nums2):
          a=[]
          a.extend(nums1)
          a.extend(nums2)
          i=1
          while i<len(nums1):
              j=i
              while j>0:
                  current = a[i]
                  previous = a[i-j]
                  if current<previous:
                      a[i] = previous
                      a[i-j]=current
                  j-=1
              i+=1
          if (len(a)%2)==0:
              idx = int(len(a)/2)-1
              median = (a[idx]+a[idx+1])/2
          else:
              idx = int(len(a)/2)
              median = a[idx]
          
          return median
```

#### Language used for code

Python

#### Expected behavior

On my terminal I am able to get the expected results of the exercise but the site produces wrong results and return  "wrong answer". 

#### Screenshots

![image](https://user-images.githubusercontent.com/49818918/180633617-5e3416f5-e488-4a52-92d3-3122a4d991df.png)
![image](https://user-images.githubusercontent.com/49818918/180633659-e7f0563f-4499-46c6-9497-cacde68625e9.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
