### ISSUE TITLE
GO

### ISSUE THREAD

**Issue by morefreedj** [LeetCode-Feedback/LeetCode-Feedback#8315]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
<img width="1776" alt="image" src="https://user-images.githubusercontent.com/43691140/180634225-d3ee0937-5804-4707-a50a-03ad23761fd7.png">

**额外的上下文**
添加额外的上下文信息

**Comment by morefreedj** [comment]
调试器与真实执行结果不一致

**Comment by feiceh** [comment]
如果出现测试用例结果和提交结果不一致的情况，您可以再仔细检查并调试您的代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」获得更多帮助。如果无法解决此问题，您可以再次反馈。
