### ISSUE TITLE
[Missing Test case] Weekly Contest 303 - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by ArshadAQ** [LeetCode-Feedback/LeetCode-Feedback#8316]
#### Your LeetCode username
ArshadAQ

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Solutions converting integers to characters in order to do hashing should fail as a char size is 1 byte and an integer is 4 bytes. Not all integers can be represented in 1 byte.

#### Code which gives wrong answer but is accepted

```
class Solution {
public:
    int equalPairs(vector<vector<int>>& a) {
        int n= a.size(), res=0;
        unordered_map<string,int> mp;
         //put in the map
        for(int i=0;i<n;i++){
            string p="";
            for(int j=0;j<n;j++) p+= a[i][j]+'0';
            mp[p]++;
        }
        //collect pairs
        for(int i=0;i<n;i++){
            string p="";
            for(int j=0;j<n;j++) p+= a[j][i]+'0';
            res+= mp[p];
        }
        return res;
    }
};
```
This has been taken from the discuss post https://leetcode.com/problems/equal-row-and-column-pairs/discuss/2324751/Find-Pairs-oror-O(N2)-Solution at the time of filing this issue

Accepted submission: https://leetcode.com/contest/weekly-contest-303/submissions/detail/755015844/
#### Expected behavior
Sample test case where this solution should fail:
[[250,78,253],[334,252,253],[250,253,253]]

##### Explanation:
Both 78 and 334 represent the same char and hence both are considered the same in this solution and give output as 1. The correct output is 0

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
