### ISSUE TITLE
Simple DFS solution  - 1609. Even Odd Tree

### ISSUE THREAD

**Issue by faizanfayazmir1** [LeetCode-Feedback/LeetCode-Feedback#8317]
simple solution using DFS

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def isEvenOddTree(self, root: Optional[TreeNode]) -> bool:
        if not root:
            return True
        q = [root]
        res = []
        while len(q):
            length = len(q)
            level = []
            count = 0
            while count < length:
                curr = q.pop(0)
                level.append(curr.val)
                if curr.left:
                    q.append(curr.left)
                if curr.right:
                    q.append(curr.right)
                count += 1
            res.append(level)
        for i in range(len(res)):
            for j in range(len(res[i])):
                if res[i].count(res[i][j]) > 1:
                    return False
            if i % 2 == 0 :
                if res[i] != sorted(res[i]):
                    return False
                for j in range(len(res[i])):
                    if res[i][j] % 2 == 0:
                        return False
            else:
                if res[i] != sorted(res[i], reverse=True):
                    return False
                for j in range(len(res[i])):
                    if res[i][j] % 2 != 0:
                        return False
        return True

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your solution to the team. We appreciate your support!
