### ISSUE TITLE
Hint 1 Typo & Erro - 724. Find Pivot Index

### ISSUE THREAD

**Issue by zorro-ftw** [LeetCode-Feedback/LeetCode-Feedback#8318]
#### Your LeetCode username
zorer_salih

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This is not exactly a bug but rather I believe a typo and a mistake in "Hint 1".
Hint 1 is as follows;
_"We can precompute prefix sums P[i] = nums[0] + nums[1] + ... + nums[i-1]. Then for each index, the left sum is P[i], and the right sum is **P[P.length - 1]** - P[i] - nums[i]."_

The typo is in the expression **P[P.length-1]** because P.length is not a valid expression and I believe was intended to be **nums.length-1**.

However I think **P[nums.length - 1]** should be **P[nums.length]** because in definition of **P[i]** the last element to be involved in the sum is nums[i-1]. Thus, giving _length-1_ actually excludes the last element of _nums_. That is why the expression should be updated as **P[nums.length]**.

In addition, I believe some improvements can be done in the hint. Whole expression is equal to **P[nums.length] - P[i+1]** and it should updated as this short version.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.
P is 1-indexed as p[i] = nums[0] + ... + nums[i - 1].
Therefore, the formulas are correct.
We appreciate your support!
