### ISSUE TITLE
425. Word Squares : Java Code  using the getOrDefault and using just add in lists

### ISSUE THREAD

**Issue by myluco** [LeetCode-Feedback/LeetCode-Feedback#832]
class Solution {
   
    List<List<String>> res = new ArrayList<List<String>>();
    int l;
    Map<String, List<String>> prefixHashTable;
    
    public List<List<String>> wordSquares(String[] words) {
        int n = words.length;
        l = words[0].length();
        buildPrefixHashTable(words);
        for (int i= 0; i < n; i++){
            List<String> list = new ArrayList<String>();
            list.add(words[i]);
            backtracking(words, 1, list);
        }
        return res;        
    }
    
    protected void buildPrefixHashTable(String[] words) {
       prefixHashTable = new HashMap<String, List<String>>();

        for (String word : words) {
          for (int i = 1; i < l; ++i) {
            String prefix = word.substring(0, i);
            List<String> wordList = prefixHashTable.getOrDefault(prefix, new ArrayList<String>());
            wordList.add(word);
            prefixHashTable.put(prefix, wordList);
            
          }
        }
    }
    
    private void backtracking(String[] words, int step, List<String> list){      
      if (step == l){
          List<String> copy = new ArrayList<>();
          copy.addAll(list);
          res.add(copy);
          return;
      }  
      
      for (String candidate: getWordsWithPrefix(getPrefix(step, list))){
          list.add(candidate);
          backtracking(words, step+1, list);
          list.remove(list.size()-1);
      }
    
    }
    
    private List<String>  getWordsWithPrefix(String prefix){
        return prefixHashTable.getOrDefault(prefix, new ArrayList<String>());
    }
    
    private String getPrefix(int step, List<String> list){
      StringBuffer sb = new StringBuffer();
      for (String s: list){
          sb.append(s.charAt(step));
      }
      return sb.toString();
    }
}

**Comment by lc-pam** [comment]
Hi @myluco 
Thank you for reaching out to us. Can you please follow the ticket format and explain the issue you'd like to raise in the ticket description so we can help you further?

**Comment by lc-pam** [comment]
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
