### ISSUE TITLE
Missing Test Case - 2195. Append K Integers With Minimal Sum

### ISSUE THREAD

**Issue by 26Saksham** [LeetCode-Feedback/LeetCode-Feedback#8320]
#### Category of the bug
- [x] Question
- [1] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

when I copy the same test case and run it ,it passes it and accepted it but when I click the submit button It show TLE 
I dont know why

#### Code you used for Submit/Run operation
```
//[Append K Integers With Minimal Sum](https://leetcode.com/problems/append-k-integers-with-minimal-sum/)
class Solution {
public:
    long long minimalKSum(vector<int>& nums, int k) {
     set<int>s;
        sort(nums.begin(),nums.end());
        // for(int i=0;i<nums.size();i++){
        //     s.insert(nums[i]);
        // }
   
        
        long long int start=nums[0];
        long long int sum=0;
       if(nums.size()==1){
         if(k<nums[0]){
             return (long long int)((long long int)k*(k+1))/2;
         }
           else{
                              sum=(long long int)((long long int)k*(long long int)(k+1))/2; 
                return sum+k-nums[0]+1;
           }
     }
        if(1<start){
            if(k<start){
            sum=(long long int)((long long int)k*(long long int)(k+1))/2;
                return sum;
            }
            else{
                k=k-start+1;
                sum=((start-1)*start)/2;


            }
        }
        for(int i=0;i<nums.size()-1;i++){
           long long int diff=nums[i+1]-nums[i];
            if(diff>1){
               long long int t=nums[i]+1;
                while(t!=nums[i+1] && k!=0){
                    sum+=t;
                    t++;
                    k--;
                }
                cout<<sum<<endl;
            }
        }
       long long int t=nums[nums.size()-1];
        if(k>0){
          long long int rem=((t)*(t+1)/2);
            long long int over=t+k;
            long long d=(long long int)((long long int)(over)*(long long int)(over+1))/2;
       sum+=d-rem;
        }
        return sum;
    }
};
```

#### Screenshots

![Screenshot (64)](https://user-images.githubusercontent.com/95184568/180646409-8125fff3-929e-4216-8397-86c197876f0e.png)

**Comment by 26Saksham** [comment]
when I copy the same test case and run it ,it passes it and accepted it but when I click the submit button It show TLE
I dont know why

**Comment by LC-Pam** [comment]
Thank you for contacting LeetCode's Support Team.

Your submission is resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

Please note that the test case you see on the "details" page shows which test case the program stops running at when the time limit has exceeded; it's not a test case that causes your program to exceed the time limit. 

I'd recommend checking out accepted submissions from the discuss tab of the problem page or posting your code there to get support from other users. Unfortunately, we do not disclose the time limit as we want our users to debug and improve their code to get it accepted. 

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
