### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by ANKURJANA-1** [LeetCode-Feedback/LeetCode-Feedback#8322]
#### Your LeetCode username
 ANKURJANA-1 

#### Category of the bug
- [ ] Question
 ```
- Regular Expression Matching
- ```
- [ ] Solution
- ```
- Regular Expression Matching
- class Solution {
    public boolean isMatch(String s, String p) {
        int dp[][]=new int[s.length()+1][p.length()+1];
        for(int i=0;i<dp.length;i++){
            for(int j=0;j<dp[0].length;j++){
                dp[i][j]=-1;
            }
        }
        boolean match=helper(s,p,s.length()-1,p.length()-1,dp);
        return match;
    }
    public boolean helper(String s, String p,int i,int j,int dp[][]){
        if(i<0 && j<0){
            return true;
        }

        if(i>=0 && j<0){
            return false;
        }
        if(j>=0 && i<0){
            for(int k=0;k<=j;k++){
                if(p.charAt(k)!='*'){
                    return false;
                }
            }
            return true;
        }
        if(dp[i][j]!=-1){
            return dp[i][j]==1?true:false;
        }
        if(s.charAt(i)==p.charAt(j) || p.charAt(j)=='.'){
            dp[i][j]= helper(s,p,i-1,j-1,dp)?1:0;
            return dp[i][j]==1?true:false;
        }
        if(p.charAt(j)=='*'){
            dp[i][j]= helper(s,p,i-1,j,dp) || helper(s,p,i,j-1,dp)?1:0;
            return dp[i][j]==1?true:false;
        }
        return false;
    }
}
- ```
- [ ] Language
 ```
- Java
- ```
- [ ] Missing Test Cases 
 ```
- "mississippi"
   "mis*is*p*."
The output should be true but it give false
- ```

#### Description of the bug
```
m i s s i s s i p p i
m i s * i s * p * .

here 
. -> i
* -> p
p -> p
* -> s,i
s ->s
i -> i
* -> s
s -> s
i -> i
m -> m

so all char was match ,it should be return True but it return false  

```


#### Code you used for Submit/Run operation
```
// Regular Expression Matching

class Solution {
    public boolean isMatch(String s, String p) {
        int dp[][]=new int[s.length()+1][p.length()+1];
        for(int i=0;i<dp.length;i++){
            for(int j=0;j<dp[0].length;j++){
                dp[i][j]=-1;
            }
        }
        boolean match=helper(s,p,s.length()-1,p.length()-1,dp);
        return match;
    }
    public boolean helper(String s, String p,int i,int j,int dp[][]){
        if(i<0 && j<0){
            return true;
        }

        if(i>=0 && j<0){
            return false;
        }
        if(j>=0 && i<0){
            for(int k=0;k<=j;k++){
                if(p.charAt(k)!='*'){
                    return false;
                }
            }
            return true;
        }
        if(dp[i][j]!=-1){
            return dp[i][j]==1?true:false;
        }
        if(s.charAt(i)==p.charAt(j) || p.charAt(j)=='.'){
            dp[i][j]= helper(s,p,i-1,j-1,dp)?1:0;
            return dp[i][j]==1?true:false;
        }
        if(p.charAt(j)=='*'){
            dp[i][j]= helper(s,p,i-1,j,dp) || helper(s,p,i,j-1,dp)?1:0;
            return dp[i][j]==1?true:false;
        }
        return false;
    }
}
```

#### Language used for code
*Java


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by stormsunshine** [comment]
How do you match the character "i" at index 7? That is the character in bold and italic in the following.

> "mississ***i***ppi"

**Comment by LC-Pam** [comment]
please consider stromsunshine's comment as reference.
