### ISSUE TITLE
Outdated Priority Queue Library - Javascript

### ISSUE THREAD

**Issue by OsidAbu-alrub** [LeetCode-Feedback/LeetCode-Feedback#8323]
#### Your LeetCode username
OsidAbu-Alrub

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I was solving this question: https://leetcode.com/problems/network-delay-time/

When I needed to import a PQ. After 1 hour of searching what library can I use (because it states it no where in the problem page) I came across this page:
https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-

Which clearly shows the PQ library used and provided by leetcode. The issue is, the current used version is outdated. Which was really frustrating and took me a really long time to figure out.

So, if bumping the library from its current version to the latest version is difficult (which I assume is). Then please just state somewhere in the question page what library I have for my current language of choice, and also state the version! or give me a link to the correct version directly.

Let me know if you need anymore details.

Thanks in advance,

#### Code you used for Submit/Run operation
```typescript
type Tuple = [number, number];

function networkDelayTime(times: number[][], n: number, k: number): number {
    const startVertex = k;
    const startTime = 0;
    const graph = new Map<number, Array<Tuple>>();
    
    // heap is used to ensure we are always processing 
    // the smallest path to some node
    const heap = new MinPriorityQueue(comparator); 
    heap.enqueue([startVertex, startTime]);
    const visited = new Set<number>();
    
    // initialize graph
    for(let i = 1 ; i <= n ; i++)
        graph.set(i, []);
    for(const [from, to, time] of times)
        graph.get(from).push([to, time]);
    
    let time = 0;
    while(!heap.isEmpty()){
        const [currentNode, smallestDistanceToCurrentNode] = heap.dequeue().element
        
        if(visited.has(currentNode)) continue;
        
        // We only add to visited set if we dequeue
        // element from stack (so we are currently on it)
        visited.add(currentNode);
        
        // this will always resemble the time taken
        // to visit all the nodes
        // It is also the time needed after traversing over
        // the last node because we are using a PQ
        time = smallestDistanceToCurrentNode;
        
        for(const [neighbor, distanceToNeighbor] of graph.get(currentNode))
            if(!visited.has(neighbor))
                heap.enqueue([neighbor, smallestDistanceToCurrentNode + distanceToNeighbor]);
    }
    return visited.size === n ? time : -1
}

function comparator([, time]:Tuple): number {
    return time;
}
```
#### Language used for code
Typescript

#### Expected behavior
The following:
1- How to import the correct library with correct version
2- Link to docs of the correct library with correct version
3- What I can import to begin with
OR
4- Bump the package to the correct version

#### Additional context
This ticket includes a screenshot
https://support.leetcode.com/hc/en-us/requests/122481

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. We've relayed this issue to our team to investigate, and we will reply to you through Zendesk.
