### ISSUE TITLE
 Find Smallest Letter Greater Than Target Description bug

### ISSUE THREAD

**Issue by MennaEwas** [LeetCode-Feedback/LeetCode-Feedback#8324]
#### Your LeetCode username
mennaabdelrahman6

#### Category of the bug
- [ ] Question:  Find Smallest Letter Greater Than Target

#### Description of the bug
There is no mention of the case of not finding any solution to return the first element and we almost got that from the discussion

#### Code you used for Submit/Run operation
```
python
class Solution:
    def nextGreatestLetter(self, letters: List[str], target: str) -> str:
        i = 0 
        while i < len(letters):
            if letters[i] > target:
                return letters[i]
            i+=1
        return letters[0]
```

#### Language used for code
Python 

#### Expected behavior
No clear about the unsolved case

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
