### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8325]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [523. Continuous Subarray Sum](https://leetcode.com/problems/continuous-subarray-sum), a solution that can get accepted fails on a specific test case.

The test case is in the link: [523.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9178080/523.txt)

#### Code you used for Submit/Run operation
```Java
class Solution {
    public boolean checkSubarraySum(int[] nums, int k) {
        int sum = nums[nums.length-1];
        
        for (int i = nums.length-2; i >= 0; i--) {
            if (nums[i] == nums[i+1] && nums[i] == 0) {
                return true;
            }
            sum+= nums[i];  
            
            if (sum >= k) {
                int temp = nums[i];
                for (int j = i+1; j < nums.length; j++) {
                    temp += nums[j];
                    if (temp%k == 0) {
                        return true;
                    }
                }
            }
            
        }    
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Add the test case so that the solution above will get TLE when submitted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
