### ISSUE TITLE
Typo - 759. Employee Free Time

### ISSUE THREAD

**Issue by Talal916** [LeetCode-Feedback/LeetCode-Feedback#8326]
#### Your LeetCode username

talal916

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a typo in the TypeScript boilerplate code. The comment defining an interval has a typo.
The word "start" in the constructor has been misspelled as "strat".

``` *    constructor(strat: number, end: number) {```

#### Screenshots

<img width="510" alt="image" src="https://user-images.githubusercontent.com/36909014/180704900-ecf577a5-3358-42e0-989e-e8a8caacba1a.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
