### ISSUE TITLE
Bug - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by shanovskyi-b** [LeetCode-Feedback/LeetCode-Feedback#8329]
#### Your LeetCode username

shanovskyi_b

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

Same code pass on C++ but gets "Time Limit Exceeded" on Python 3
Additionally, the tests on which Python 3 submissions fails get "Accepted" when you run the using "Run Code"

#### Code you used for Submit/Run operation

Python 3
```
class Solution:
  def longestPalindrome(self, s: str) -> str:
    n = len(s)
    dp = [[0]*(n+1) for _ in range(n+1)]
    rs = s[::-1]
    res = [0, 0]

    for i in range(n+1):
      for j in range(n+1):
        if i == 0 or j == 0:
          continue
        if s[i-1] == rs[j-1]:
          dp[i][j] = dp[i-1][j-1] + 1
          if dp[i][j] > res[1]-res[0]+1 and n - (j-1) - 1 == (i-1) - dp[i][j] + 1:
            res = [i-dp[i][j], i-1]
    return s[res[0]:res[1]+1]
```
C++
```
#include <bits/stdc++.h>
#include <algorithm>
#include <string> 
class Solution {
public:
  string longestPalindrome(string s) {
    int n = s.size();
    int dp[n+1][n+1];
    for(int i = 0; i < n + 1; i++)
        for(int j = 0; j < n + 1; j++)
            dp[i][j] = 0;
    char rs[s.length()];
     for (int i = 0, len = s.length(); i < len; i++) {
        rs[i] = s[len-1-i];
     }

    int res[2] = {0,0};
    for(int i = 0; i < n + 1; i++) {
      for(int j = 0; j < n + 1; j++) {
        if (i==0 || j == 0) continue;
        if (s[i-1] == rs[j-1]) {
          dp[i][j] = dp[i-1][j-1] + 1;
          if (dp[i][j] > res[1]-res[0]+1 && n - (j-1) - 1 == (i-1) - dp[i][j] + 1) {
            res[0] = i-dp[i][j];
            res[1] = i-1;
          }
        }
      }
    }
    return s.substr(res[0], res[1] - res[0] + 1);
  }
};
```

#### Language used for code

Python 3, C++

#### Expected behavior

1) Both languages passes the tests
2) "Time Limit Exceeded" for the same test cases should appear in both "Submit" and "Run Code" or in none of them

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

**Comment by shanovskyi-b** [comment]
> When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thanks for sharing the article.
From what I see it's not that case - the code above doesn't contain anything that may affect the other testcases.
Well, and this article is rather about getting wrong output values "Time Limit Exceeded" may be caused by some other technical constraints (but again, I'm quite sure it's not on my side - there's just some difference in time constraints between "Run Code" and "Submit")

**Comment by LC-Pam** [comment]
I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've reduced the total number of test cases to let that solution pass. We appreciate your support!
