### ISSUE TITLE
confused test demo

### ISSUE THREAD

**Issue by xgqfrms** [LeetCode-Feedback/LeetCode-Feedback#833]
https://leetcode.com/problems/relative-sort-array/

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

why in the Output, 1 only exists once, but 2 has many times?

```md

Example 1:

Input: arr1 = [2,3,1,3,2,4,6,7,9,2,19],  arr2 = [2,1,4,3,9,6]
Output: [2,2,2,1,4,3,3,9,6,7,19]

```

wanted all duplicate, `[2,2,2,2,1,1,4,3,3,3,9,6,7,19]`

OR, not duplicate `[2,1,4,3,9,6,7,19]`

#### Code you used for Submit/Run operation

```js

"use strict";

/**
 *
 * @author xgqfrms
 * @license MIT
 * @copyright xgqfrms
 * @created 2020-08-0
 * @modified
 *
 * @description 1122. Relative Sort Array
 * @difficulty Easy
 * @complexity O(n)
 * @augments
 * @example
 * @link
 * @solutions
 *
 */
/**
 * @param {number[]} arr1
 * @param {number[]} arr2
 * @return {number[]}
 */
var relativeSortArray = function(arr1, arr2) {
  const log = console.log;
  let len1 = arr1.length;
  let len2 = arr2.length;
  const result = [...arr2];
  if(len1 < 1 || len2 < 1) {
    return arr1;
  }
  arr1 = arr1.sort((a, b) => a > b ? 1 : -1);
  while(len1) {
    let key = arr1[arr1.length - len1];
    let index = result.indexOf(key)
    if(index > -1) {
      result.splice(index, 0, key);
    } else {
      result.push(key)
    }
    len1--;
  }
  log(`result =`, result);
  return result;
};
```

#### Language used for code

javascript

#### Screenshots

![image](https://user-images.githubusercontent.com/7291672/90717236-b62ad200-e2e1-11ea-8398-c5110636cc05.png)

wanted all duplicate, `[2,2,2,2,1,1,4,3,3,3,9,6,7,19]`

OR, not duplicate `[2,1,4,3,9,6,7,19]`

**Comment by xgqfrms** [comment]
# solution passed

https://leetcode.com/problems/relative-sort-array/discuss/801568/javscript-solution

**Comment by lc-pam** [comment]
Hi @xgqfrms 
Thank you for reaching out to us. I think you've misunderstood the question. Please read the problem description carefully and post your question in the problem's discussion tab if you still have questions. Thank you for your support.
