### ISSUE TITLE
347. Top K Frequent Elements - need more info on constrains

### ISSUE THREAD

**Issue by Pranav108** [LeetCode-Feedback/LeetCode-Feedback#8330]
#### Your LeetCode username
[BEN__10](https://leetcode.com/BEN__10/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The range of values of elements in the given array is not mentioned in question. It should be mentioned with `Constraints`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
