### ISSUE TITLE
1030. 距离顺序排列矩阵单元格

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#8332]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 题目

**描述**
题目描述错误。
> 给定四个整数 `row` ,   cols ,  rCenter 和 cCenter 。

**期望行为**
应该是`rows`，改为：
给定四个整数 `rows` ,   cols ,  rCenter 和 cCenter 。

**屏幕截图**
[题目链接](https://leetcode.cn/problems/matrix-cells-in-distance-order/description/)
**额外的上下文**
[题目链接](https://leetcode.cn/problems/matrix-cells-in-distance-order/description/)

**Comment by BrambleWave** [comment]
你好，当前题目描述已更新，ID：hhummingg  给予积分奖励，请查收。
