### ISSUE TITLE
Wrong numbers in video explanation for 1342. Number of Steps to Reduce a Number to Zero

### ISSUE THREAD

**Issue by nikolaynest** [LeetCode-Feedback/LeetCode-Feedback#8333]
#### Your LeetCode username

mykola_n

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a mistake during explanation of the Binary approach for **1342. Number of Steps to Reduce a Number to Zero**. 
Starting **from 4:59**, explanation shows twos with the power from 0 to 8 (instead 0..7) without 2 in pow 2. 
So the actual list from the video is:
2^0, **2^1**, **2^3**, 2^4, 2^5, 2^6, 2^7, **2^8**
but it should be: 
2^0, **2^1**, **2^2**, 2^3, 2^4, 2^5, 2^6, **2^7**

#### Screenshots

![image](https://user-images.githubusercontent.com/4740038/180801307-ce382ab9-05b7-40d2-9422-0c46f4aa5689.png)

**Comment by elkhan** [comment]
Here is a [link](https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/692/challenge-problems/4425/). I think that OPs explanation is as good as it can be. Take a look at the screenshot he posted, it misses 2^2
