### ISSUE TITLE
29. Divide Two Integers fails for the test case (-2147483648 ,-1)

### ISSUE THREAD

**Issue by SHESHANKSK** [LeetCode-Feedback/LeetCode-Feedback#8334]
#### Your LeetCode username

sksheshank

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Consider the problem **29. Divide Two Integers** 
for the test case
```
-2147483648
-1
```
the expected out is
```
2147483647
```
which is incorrect because the output should be
```
2147483648
```

#### Code you used for Submit/Run operation

```py
// Divide Two Integers
class Solution:
    def divide(self, dividend: int, divisor: int) -> int:
        quotient = 0
        if abs(divisor) == 1:
            if (divisor < 0 and dividend < 0) or (divisor > 0 and dividend > 0):
                return abs(dividend)
            else:
                return dividend*(-1)
        else:
            if divisor > 0:
                if dividend > 0:
                    while(dividend >= divisor):
                        dividend = dividend - divisor
                        quotient +=1
                    return quotient
                else:
                    dividend = abs(dividend)
                    while(dividend >= divisor):
                        dividend = dividend - divisor
                        quotient +=1
                    return quotient*(-1)
                
            else:
                if dividend > 0:
                    divisor = abs(divisor)
                    while(dividend >= divisor):
                        dividend = dividend - divisor
                        quotient +=1
                    return quotient*(-1)
                else:
                    divisor = abs(divisor)
                    dividend = abs(dividend)
                    while(dividend >= divisor):
                        dividend = dividend - divisor
                        quotient +=1
                    return quotient
```

#### Language used for code

Python 3

#### Expected behavior

-2147483648 / -1
Should give 2147483648 as the output but the system is expecting the output to be 2147483647 
It would be nice if you resolve this bug due to which this question has less submission rate

#### Screenshots

![image](https://user-images.githubusercontent.com/62549471/180814655-a5efca46-c76f-4298-970c-582b47f5533e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
