### ISSUE TITLE
Missing Test Case - 695. Max Area of Island

### ISSUE THREAD

**Issue by maseratirex** [LeetCode-Feedback/LeetCode-Feedback#8336]
#### Your LeetCode username

maseratirex

#### Category of the bug
- [ ] Solution

#### Description of the bug

I used a static integer "maxArea" to keep track of the max area outside of the functions. However, LeetCode's test procedures retain the value from previous testcases, which means if the max area is 6 for the first test and 0 for the second my solution returns the max of those two: 6. 

#### Code you used for Submit/Run operation

```
class Solution {
    static int maxArea = 0, currArea = 0, rows, cols;
    public static void markAreaDFS(int[][] grid, int row, int col){
        if(row < 0 || col < 0 || row >= rows || col >= cols || grid[row][col] != 1) return;
        maxArea = Math.max(++currArea, maxArea);
        grid[row][col] = 0;
        markAreaDFS(grid, row+1, col);
        markAreaDFS(grid, row-1, col);
        markAreaDFS(grid, row, col+1);
        markAreaDFS(grid, row, col-1);
    }
    public static int maxAreaOfIsland(int[][] grid){
        rows = grid.length;
        cols = grid[0].length;
        for(int row = 0; row < rows; row++){
            for(int col = 0; col < cols; col++){
                if(grid[row][col] == 1){
                    System.out.println("What the heck LeetCode");
                    currArea = 0;
                    markAreaDFS(grid, row, col);
                }
            }
        }
        return maxArea;
    }
}
```

#### Language used for code

Java 

#### Expected behavior

I expected LeetCode to reset global values I had defined whenever LeetCode started a new testcase. It didn't, which messed up my solution. I actually fixed my solution by setting maxArea (a global variable) to 0 at the beginning of the maxAreaOfIsland() function. However, this is still an issue and confused me for a little while before I realized I wasn't the issue.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Global and static values should be reset by you and please avoid static variables. We appreciate your support!
