### ISSUE TITLE
Missing Test Case - 2347. Best Poker Hand

### ISSUE THREAD

**Issue by bhaumikmaan** [LeetCode-Feedback/LeetCode-Feedback#8337]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 2347. Best Poker Hand
class Solution {
    public String bestHand(int[] ranks, char[] suits) {
        int []hashr = new int[15] ; // Check Constraints
        int []hashs = new int[5] ; // Check Constraints
        for(int i = 0 ; i < 5 ; i++)
        {
            hashr[ranks[i]] += 1 ;
            hashs[suits[i] - 'a'] += 1 ;
        }
        String ans = "High Card" ;
        for(int i = 0 ; i < 5 ; i++) // Checking same suit
        {
            if(hashs[i] == 5)
            {
                ans = "Flush" ;
				break ;
            }
        }
        for(int i = 0 ; i < 14 ; i++) // Checking same rank
        {
            if(hashr[i] >= 3)
            {
                ans = "Three of a Kind" ;
                break ;
            }
            else if(hashr[i] == 2)
            {
                ans = "Pair" ;
				break ;
            }
        }
        return ans ;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Using The case 
```
[2,2,3,3,3]
["a","b","c","d","a"]
```
Expected answer is `Three of a kind` but my answer (the output) is `Pair`!
But the solution mentioned above is accepted, meaning this testcase mentioned is missing!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
