### ISSUE TITLE
Missing Test Case - 845. Longest Mountain in Array

### ISSUE THREAD

**Issue by scaserini** [LeetCode-Feedback/LeetCode-Feedback#8339]
#### Your LeetCode username
scaserini

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
var longestMountain = function(arr) {
    if (arr.length < 3) {
        return 0
    }
    
    let max = 0
    let start = null
    let isIncreasing = false
    
    for (let i = 0; i < arr.length - 1; i++) {
        if (arr[i + 1] > arr[i]) {
            if (isIncreasing == false) {
                start = i
                isIncreasing = true
            }
        }else if (arr[i + 1] < arr[i]) {
            isIncreasing = false
            if (start != null) {
                max = Math.max(max, i + 1 - start + 1)
            }
        }else {
            start = null
        }
    }
    
    return max
};
```

#### Language used for code
JS

#### Expected behavior
The code above was accepted and passed all the test cases. But I kept on thinking about my solution, and I found that my code failed with this input. Probably a test case like this one is missing.

<img width="436" alt="Screenshot 2022-07-25 at 23 33 56" src="https://user-images.githubusercontent.com/78050955/180878066-d6ae451f-2e9f-4f52-9584-b69f595db197.png">

I corrected my code and now it works also with this test case:

```
var longestMountain = function(arr) {
    if (arr.length < 3) {
        return 0
    }
    
    let max = 0
    let start = null
    let isIncreasing = false
    
    for (let i = 0; i < arr.length - 1; i++) {
        if (arr[i + 1] > arr[i]) {
            if (isIncreasing == false) {
                start = i
                isIncreasing = true
            }
        }else if (arr[i + 1] < arr[i]) {
            isIncreasing = false
            if (start != null) {
                max = Math.max(max, i + 1 - start + 1)
            }
        }else {
            isIncreasing = false // <-- added this line
            start = null
        }
    }
    
    return max
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
