### ISSUE TITLE
Missing Testcase for Lowest Common Ancestor of a BST (Problem 235)

### ISSUE THREAD

**Issue by LayzerK** [LeetCode-Feedback/LeetCode-Feedback#8343]
#### Your LeetCode username
LayzerK

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

The current test cases allow for you to use incorrect logic in this problem in the sense that you can use an incorrect ordering of sequential if statements w/o using correct else logic.

#### Code you used for Submit/Run operation

```python
class Solution:
    def lowestCommonAncestor(self, root: 'TreeNode', p: 'TreeNode', q: 'TreeNode') -> 'TreeNode':
        curr = root
       

        while curr:
           
            if curr.val < p.val and curr.val < q.val:
                curr = curr.right
            
            if curr.val > p.val and curr.val > q.val:
                curr = curr.left
            else:
                return curr
 ```

#### Language used for code

It should fail since the right and left block can execute sequentially, failing. Here is an example testcase that would do that.
[3, 1, 8, null, null, 5, 10, 4, 6, 9, 11]
9
11

#### Screenshots

<img width="664" alt="image" src="https://user-images.githubusercontent.com/97922602/180913904-7dda5f31-9821-4449-abe3-2806a932dd98.png">

Image of the incorrect code being submitted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
