### ISSUE TITLE
Spell Error - 1579. Remove Max Number of Edges to Keep Graph Fully Traversable

### ISSUE THREAD

**Issue by ishankaggarwal** [LeetCode-Feedback/LeetCode-Feedback#8345]
#### Your LeetCode username
ishank193aggarwal

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question description has a typo in the line Type 3 i.e Type 3: Can **by** traversed by both Alice and Bob.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
Type 3: Can **be** traversed by both Alice and Bob.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
