### ISSUE TITLE
Missing Test Case - 1206. Design Skiplist

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#8346]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9187365/1.txt)

#### Code you used for Submit/Run operation

```
class Skiplist {
public:

    // 一个升序的排序数组，然后二分查找就行吧
    vector<int> v;
    Skiplist() {

    }
    
    bool search(int target) {
       bool flag = binary_search(v.begin(),v.end(),target);
       return flag;
    }
    
    void add(int num) {
        vector<int>::iterator it = lower_bound(v.begin(),v.end(),num);
        v.insert(it,num);
    }
    
    bool erase(int num) {

        if(binary_search(v.begin(),v.end(),num))
        {
            vector<int>::iterator it = lower_bound(v.begin(),v.end(),num);
            v.erase(it);
            return true;
        }    

        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
