### ISSUE TITLE
Prim's algo Explorer card

### ISSUE THREAD

**Issue by mallika-b** [LeetCode-Feedback/LeetCode-Feedback#8348]
#### Your LeetCode username

mallika-b

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [ x] Explorer Card

#### Description of the bug

Is the solution offered here not Prim's algo:
https://leetcode.com/explore/learn/card/graph/621/algorithms-to-construct-minimum-spanning-tree/3861/?

Because the Complexity Analysis for Prim's, provided here:
https://leetcode.com/explore/learn/card/graph/621/algorithms-to-construct-minimum-spanning-tree/3859/
makes the following claims:
we store in the heap all the vertices that are not yet included in our minimum spanning tree.
Extracting minimum element and key decreasing operations cost O(\log V)O(logV) time.

but in the solution supposedly implementing Prim's, we can clearly see line 17
pq.append(edge)
the heap is on edges, not vertices.

What am I missing?

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The written content is correct basically the solution use a little different approach from the classic heap solution. The extracting minimum element and key decreasing operations cost O(logV) time. If you check number of time data is inserted and retrieve from heap is equivalent to the number of vertices V which is 5 in current scenario. We appreciate your support!
