### ISSUE TITLE
[TypeScript] Bug- 14. Longest Common Prefix

### ISSUE THREAD

**Issue by rubencosta13** [LeetCode-Feedback/LeetCode-Feedback#8349]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When running the problem 14. Longest Common Prefix, found a bug. ``TypeError: Cannot read properties of undefined (reading '0')``, however the same doesn't apply when using either VScode or TSplayground

#### Code you used for Submit/Run operation
TSPlayground: https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAGwQcwKYGcoGE4C2BCACgE4bAwAeAFDmVgFyIMxhoDaAugJQsBDMAE9EAbwBQiaYggIciTgwEAaVlDIAjNQwjdEAXnWMA3FJnIMURAAcKVaizYdDiAORuzMlFcQxXAAxeMsBwZIi0cmAKEAAWAuFwwMYCvOLm3tIwyfQaApww+gbFxpoF+gBkFSnlhiW65WmSmS229jSIANRGyuUZmQC+-d7+3YgAjMHSQ94UUCBkSHaUNBIDZhJRWHCWAHSoaLSoHNh4hMRg5Ct0nABEACZwaLcqt2QCEBgQCS+332S3Pi8MxbHYYfZPI7oU74Iikdo3W7AVAAdwwANeyLgKN+yJgaFiUEBvGBQA

```ts
function longestCommonPrefix(strs: string[]): any {
    const [stra, strb, strc] = strs;
    let prefix: string = '';
    let i = 0;
    for (const char of stra) {
        if (stra[i] === strb[i] && stra[i] === strc[i]) {
            prefix += stra[i]
        }
        i += 1;
    }
    return prefix
};

```
I know that this is spaghetti code it was my actual goal

#### Language used for code
TypeScript

#### Expected behavior

Output should be: 
```
""
"fl"
```
instead of 

```
TypeError: Cannot read properties of undefined (reading '0')
    Line 6: Char 29 in solution.ts (longestCommonPrefix)
    Line 23: Char 19 in solution.ts (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 14: Char 26 in solution.ts (Object.<anonymous>)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by rubencosta13** [comment]
Any updates so far?

**Comment by LC-Pam** [comment]
Thank you for your time. There could be empty strings and the code does not work correctly when it faces an empty string.  We appreciate your support!
