### ISSUE TITLE
[Python 3] Erroneous Code - 409. Longest Palindrome

### ISSUE THREAD

**Issue by the-praxs** [LeetCode-Feedback/LeetCode-Feedback#8351]
#### Your LeetCode username

**the-praxs**

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Python 3 code for the solution uses the Python 2 functions of the Counter module found in collections. Hence, the following error ```AttributeError: 'Counter' object has no attribute 'itervalues'``` is encountered leading to a Runtime error on submitting the solution.

#### Code you used for Submit/Run operation

```
class Solution:
    def longestPalindrome(self, s):
        ans = 0
        for v in collections.Counter(s).itervalues():
            ans += v / 2 * 2
            if ans % 2 == 0 and v % 2 == 1:
                ans += 1
        return ans
```

#### Language used for code

Python 3

#### Expected behavior

The code should compile instead of providing the following error:
```
AttributeError: 'Counter' object has no attribute 'itervalues'
    for v in collections.Counter(s).itervalues():
Line 4 in longestPalindrome (Solution.py)
    ret = Solution().longestPalindrome(param_1)
Line 27 in _driver (Solution.py)
    _driver()
Line 38 in <module> (Solution.py)
```

#### Additional context

This bug has been fixed by using [**Murgio**'s](https://leetcode.com/Murgio/) Python 3 solution:
```
def longestPalindrome(self, s):
    ans = 0
    for v in collections.Counter(s).values():
        ans += v // 2 * 2
        if ans % 2 == 0 and v % 2 == 1:
            ans += 1
    return ans
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Counter in py3 is different from Counter in py2, please read the documentation of the languages. We appreciate your support!
