### ISSUE TITLE
7.整数反转，测试点错误

### ISSUE THREAD

**Issue by Ruomio** [LeetCode-Feedback/LeetCode-Feedback#8352]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Papillon
邮箱：1065940593@qq.com

**Bug 类型**
- [ ] 测试用例错误，测试点编号1021,测试数据1534236469

**描述**
发现一个测试点错误，第1021个测试数据1534236469， 根本没有超过整数最大值2147483647， 测试结果却返回0
很奇怪，我用比这个测试用例大一的数据测试 即 1534236470 ， 程序却没有任何问题。

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    void ex(char ch[], int len){
        for(int i=0; i<(len/2); i++){
            char tmp=ch[len-i-1];
            ch[len-i-1] = ch[i];
            ch[i] = tmp;
        }


    }
public:
    int reverse(int x) {
        if(x>INT_MAX || x < INT_MIN) 
            return 0;

        bool flag=0;     //记录正负号
        if(x<0) {
            flag=1;
            x = -x;      //去掉负号
        }    
        // 转化为字符串数组
        string str = to_string(x); 
        int len = str.size();
        char *ch = const_cast<char*>(str.c_str());
        ex(ch,len);
        
        // 再转换回来
        int res = atoi(ch);
        if(flag==1){
            return -res;
        }
        else{
            return res;
        }
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by Ruomio** [comment]
题目：7.整数反转

**Comment by stormsunshine** [comment]
1534236469是十位数，反转后的数的最高位是9，即反转后的数大于9×10<sup>9</sup>，而32位有符号整数的最大值小于3×10<sup>9</sup>，因此反转后的数已经超过32位有符号整数范围。
