### ISSUE TITLE
Condition update - 236. Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by shwe2498** [LeetCode-Feedback/LeetCode-Feedback#8356]
#### Your LeetCode username
shwelearn

#### Category of the bug
- [ X] Solution

#### Description of the bug
In second the solution called Approach 2: Iterative using parent pointers, the while needs one more condition to check stack/queue is not empty, otherwise the following testcase fails with error :
Runtime Error Message:
Line 32: Char 19: runtime error: member access within misaligned address 0xbebebebebebebebe for type 'TreeNode', which requires 8 byte alignment (solution.cpp)
0xbebebebebebebebe: note: pointer points here
<memory cannot be printed>
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:37:19
Last executed input:
[1,2]
1
2

#### Code you used for Submit/Run operation
```
class Solution {
public:
    TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) {
        queue<TreeNode*> que;
        unordered_map<TreeNode*, TreeNode*> parent;
        parent[root] = nullptr;
        que.push(root);
        
        while(!parent[p] || !parent[q]){
            TreeNode* t = que.front();
            que.pop();
            if(t->left){
                parent[t->left] = t;
                que.push(t->left);
            }
            if(t->right){
                parent[t->right] = t;
                que.push(t->right);
            }
        }
        set<TreeNode*> ancestors;
        while(p){
            ancestors.insert(p);
            p = parent[p];
        }
        while(ancestors.find(q) == ancestors.end()){
            q = parent[q];
        }
        
        return q;
    }
};
```

// The correct code : 
```
class Solution {
public:
    TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) {
        queue<TreeNode*> que;
        unordered_map<TreeNode*, TreeNode*> parent;
        parent[root] = nullptr;
        que.push(root);
        
        while(!que.empty() && (!parent[p] || !parent[q])){
            TreeNode* t = que.front();
            que.pop();
            if(t->left){
                parent[t->left] = t;
                que.push(t->left);
            }
            if(t->right){
                parent[t->right] = t;
                que.push(t->right);
            }
        }
        set<TreeNode*> ancestors;
        while(p){
            ancestors.insert(p);
            p = parent[p];
        }
        while(ancestors.find(q) == ancestors.end()){
            q = parent[q];
        }
        
        return q;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
The above test has to pass but failed with runtime error.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. After investigated,Approach 2 solutions are working correctly. We appreciate your support!
