### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by tayybanaz** [LeetCode-Feedback/LeetCode-Feedback#8357]
#### Your LeetCode username

tayybanaz

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [- ] Missing Test Cases 

#### Description of the bug

incorrect use case-
Input
-2147483648
-1
Output
2147483648 <- this is the correct output. Expected is wrong. Anything divided by one should be of same value,
Expected
2147483647
(https://user-images.githubusercontent.com/38394253/181067482-adcd04bf-e883-4123-af5a-e00286aecfd8.png)
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def divide(self, dividend: int, divisor: int) -> int:
        if dividend == 0:
            return 0
        if abs(divisor) == 1:
            count = abs(dividend)
        else:
        
            temp_divid = abs(dividend)
            temp_divisor = abs(divisor)

            count = 0 
            while  temp_divid >= temp_divisor:
                count += 1
                temp_divid = temp_divid - temp_divisor
            
        if dividend < 0 and divisor < 0 :
            return count
        elif dividend <0 or divisor < 0:
            return -abs(count)
        else:
            return count
```

#### Language used for code

Python

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment]
Why can't you read problem description carefully?
> For this problem, if the quotient is **strictly greater than** 2<sup>31</sup> - 1, then return 2<sup>31</sup> - 1.

**Comment by tayybanaz** [comment]
> Before overflow, the maximum int is 2^31 - 1 and the smallest int is -2^31 (due to bit signing). therefore, dividing (-2^31)/-1 cannot result in 2^31, since the highest possible value before overflow is 2^31 - 1.

My bad. It was an oversight at my end. Apologies for any inconvenience.
