### ISSUE TITLE
Missing test cases and insufficient description for 865 - Smallest subtree with all the Deepest Nodes

### ISSUE THREAD

**Issue by mullachv** [LeetCode-Feedback/LeetCode-Feedback#836]
#### Your LeetCode username
mullachv

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Inadequate problem description and insufficient test cases (or examples)
What is the expected outcome for the following tree and why?:
[0,1,3,null,2]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Python

#### Expected behavior
The expected outcome is [2] for the above mentioned test case.
Why is it not [1,null,2]?

**Comment by lc-pam** [comment]
Hi @mullachv 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @mullachv , thanks for your time. The team has reviewed your report and considered it invalid. The output of the test case you mentioned is correct. We've add explanation to the test case to be easy to understand. Thank you for your support.

**Comment by mullachv** [comment]
@lc-pam Thanks for the additional example. I suggest you "bolden" the phrase "smallest subtree" in the problem statement. Thank you
