### ISSUE TITLE
136. Single Number 

### ISSUE THREAD

**Issue by tranthanhbinh2603** [LeetCode-Feedback/LeetCode-Feedback#8360]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
//136. Single Number
class Solution {
public:
    int singleNumber(vector<int>& nums) {
        const long int maxarr = 60000;
        int hsh[maxarr];
        for (int i = 0; i < nums.size(); i++)
            hsh[nums[i] + 30000]++;
        for (int i = 0; i < nums.size(); i++)
            if (hsh[nums[i] + 30000] == 1) return nums[i];
        return 99999;
    }
};
};
```

#### When my code runs in Run code mode with custom testcase [1], I get correct result.
But when summit I was stopped right at the test case [1]

####![image](https://user-images.githubusercontent.com/65013334/181149993-7fab3aba-5221-4efa-b10e-bdf8162ab91e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
