### ISSUE TITLE
Missing Test Case - 493. Reverse Pairs

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#8379]
#### Your LeetCode username

yumkam

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution was [accepted](https://leetcode.com/submissions/detail/757913002/), but fails test case
```
[-2147483648,-1073741824]
```
Differently broken submission also was [accepted](https://leetcode.com/submissions/detail/757924194/), but fails test case
```
[2147483647,1073741824,1073741823]
```

#### Code you used for Submit/Run operation

```c++
#include <ext/pb_ds/assoc_container.hpp>
#include <ext/pb_ds/tree_policy.hpp>
using namespace __gnu_pbds;
template <typename K, typename V = null_type, typename Comp = less<K>>
using ordered_set = tree<K, V, Comp, rb_tree_tag, tree_order_statistics_node_update>;

class Solution {
public:
    int reversePairs(vector<int>& nums) {
        ordered_set<pair<int,unsigned>> s;
        unsigned ret = 0;
        for (unsigned i = 0; i < nums.size(); i++) {
            if (nums[i] <= INT_MIN/2) // off-by-one, this should be <
                ret += i;
            else if (nums[i] < INT_MAX/2) // off-by-one, this should be <=
                ret += i - s.order_of_key(make_pair(nums[i]*2, UINT_MAX));
            s.insert(make_pair(nums[i], i + 1));
        }
        return ret;
    }
};
```

#### Language used for code
C++

#### Expected behavior

There should be more testcases on edges of range, broken submission should not be accepted.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
