### ISSUE TITLE
Wrong question category

### ISSUE THREAD

**Issue by mihirahlawat** [LeetCode-Feedback/LeetCode-Feedback#838]
#### Your LeetCode username
@mihiraman

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

[Link to the question](https://leetcode.com/problems/maximum-nesting-depth-of-two-valid-parentheses-strings/)
I haven't been able to figure out why this question has been tagged with Binary Search. Nor can I find any solution in Discussion that is based on Binary Search.

#### Code you used for Submit/Run operation
-NA-

#### Language used for code

-NA-

#### Expected behavior

-NA-

#### Screenshots

-NA-

**Comment by lc-pam** [comment]
Hi @mihirahlawat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @mihirahlawat 
Thank you for your time. The team has reviewed your report and responded that the problem can be approached using a binary search, you may wait for the official solution to see the binary search solution. We appreciate your support!
