### ISSUE TITLE
Solution Text Error - 592. fraction-addition-and-subtraction

### ISSUE THREAD

**Issue by zhouzhongyuan** [LeetCode-Feedback/LeetCode-Feedback#8384]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**

题解文案中，分子、分母搞反了。

**你使用的语言**
无

**你提交或者运行的代码**
无

**期望行为**
题解应当由”初始分数的分子为 \textit{denominator} = 0denominator=0，分母为 \textit{numerator} = 1numerator=1“ 改为”初始分数的分母为 \textit{denominator} = 0denominator=0，分子为 \textit{numerator} = 1numerator=1“。

**屏幕截图**
![image](https://user-images.githubusercontent.com/717817/181195276-5f07df42-3ab9-4c6f-b252-b7d414dfc967.png)

**额外的上下文**
无

**Comment by feiceh** [comment]
你好，当前题解已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by zhouzhongyuan** [comment]
leetcode-cn.com/u/zhou-zhong-yuan/

**Comment by feiceh** [comment]
积分奖励已发放，请查收。
