### ISSUE TITLE
Corner Case Missing in question: https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/

### ISSUE THREAD

**Issue by Rohitesh-Kumar-Jain** [LeetCode-Feedback/LeetCode-Feedback#839]
**Corner Case Missing in question: https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/****

#### Your LeetCode username
rzay

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing Test case in Question : [https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists](https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/**l)
A test case where one of the lists is empty should also be included in the existing testing suite

#### Code you used for Submit/Run operation

```
/struct number{
    int num, list, index;
};

class Solution {
public:
    struct comp{
      bool operator()(number n1, number n2) {
          return  n1.num > n2.num;
      }  
    };
    
    vector<int> smallestRange(vector<vector<int>>& nums) {
        priority_queue<number, vector<number>, comp> pq;
        int maxSoFar = INT_MIN, start = 0, end = INT_MAX;
        for(int i=0;i<nums.size();i++) {
            if(!nums[i].empty())  {
                pq.push({nums[i][0], i, 0});
                maxSoFar = max(maxSoFar, nums[i][0]);
            }
        }
        
        while(pq.size() == nums.size()) {
            auto top = pq.top();
            pq.pop();
            if ((end - start) > maxSoFar - top.num) {
                start = top.num, end = maxSoFar;
            }
            int nextIndex = top.index + 1;
            if(nums[top.list].size() > nextIndex) {
                pq.push({nums[top.list][nextIndex], top.list, nextIndex});
                maxSoFar = max(maxSoFar, nums[top.list][nextIndex]);
            }
        }
        return {start, end};
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
My code is giving wrong output for the test case:  [[],[0,9,12,20],[5,18,22,30]]
My output : [0,2147483647]
Expected output: [0,30]

Had this test case been included in existing testing suite, my code would not have been accepted, this is a very valid corner case possibly asked during  interviews

#### Screenshots
Attaching screenshot of the input, outcome and expected outcome:

<img width="1519" alt="Screenshot 2020-08-22 at 11 32 55" src="https://user-images.githubusercontent.com/62026125/90950001-4fd1bb00-e46b-11ea-98a9-e41be5754514.png">

**Comment by lc-pam** [comment]
Hi @Rohitesh-Kumar-Jain 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @Rohitesh-Kumar-Jain 
Thank you for your time. The team reviewed your report and noticed the test case validation and constraints are missing from the problem so we updated the problem. However, we can't add the test case you mentioned as it's invalid. We appreciate your support!
