### ISSUE TITLE
2353. 设计食物评分系统测试用例偏弱

### ISSUE THREAD

**Issue by eshaoliu** [LeetCode-Feedback/LeetCode-Feedback#8390]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**liuhongru
填写你登录 LeetCode（中国区）的用户名liuhongru

**Bug 类型**
- [ ] 题目[2353. 设计食物评分系统](https://leetcode.cn/problems/design-a-food-rating-system/)
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
此题的测试用例偏弱，没有涉及修改得分再改回来的用例。
这是我新贡献的测试用例
["FoodRatings","highestRated","highestRated","changeRating","changeRating","highestRated","changeRating","highestRated","highestRated","highestRated","highestRated"]
[[["pwdgjvphy","tiwlr","mqpdbl","jjhmgnxt","dmlymzufx"],["dsyujtjljz","eluxblkt","dsyujtjljz","dsyujtjljz","eluxblkt"],[15,10,5,16,18]],["dsyujtjljz"],["eluxblkt"],["dmlymzufx",14],["tiwlr",11],["eluxblkt"],["tiwlr",10],["eluxblkt"],["dsyujtjljz"],["dsyujtjljz"],["eluxblkt"]]
**你使用的语言**
python
**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**

**屏幕截图**

**额外的上下文**
添加额外的上下文信息
部分错误解法可以ac，应加上将评分置为历史出现过的用例。

**Comment by feiceh** [comment]
您好，在与相关团队核实后：没有提供错误解法，暂不处理。本次 Ticket 将关闭，感谢您的反馈和支持。
