### ISSUE TITLE
Bad Test case- Problem 1711 Count Good Meals

### ISSUE THREAD

**Issue by ztalarick** [LeetCode-Feedback/LeetCode-Feedback#8395]
#### Your LeetCode username

ztal

#### Category of the bug
Bad test case

#### Description of the bug
Test case https://leetcode.com/submissions/detail/758380940/testcase/  is length 100,000 with each element being 32. My code fails this one, however it works on smaller length lists. 

with list length 44722 it fails but with 44721 its good. The expected result changes significantly between these two values.
44721 -> expected result is 999961560
44722 -> expected result is 6274

I would guess it is some sort of overflow error? I think the expected result should be 1000006281 which has one additional digit.

#### Code you used for Submit/Run operation

```
class Solution:
    def countPairs(self, deliciousness: List[int]) -> int:
        def power_sum(n):
            if n == 1 or n == 0:
                return 1
            x = 1
            while True:
                if x >= n:
                    return x - n
                x = x * 2
        print("length: " + str(len(deliciousness)))
        deliciousness.sort()
        count = 0 
        d = dict()
        for meal in deliciousness:
            x = power_sum(meal)
            if x == 0:
                count += d.get(0, 0)
                count += d.get(meal, 0)
            else:
                count += d.get(x, 0)
            if d.get(meal, None) == None:
                d[meal] = 1
            else:
                d[meal] += 1
            
        count += (d.get(0, 0) * d.get(1, 0))    
        return count
```

#### Language used for code

python3

#### Expected behavior

When test case has length 44722 the expected result should be 1000006281 not 6274

#### Screenshots
Note the printed length of the input list in stdout.

<img width="1680" alt="Screen Shot 2022-07-27 at 3 22 07 PM" src="https://user-images.githubusercontent.com/31807984/181355415-2326197b-8a9c-4425-8164-696dc3e699d6.png">

<img width="1680" alt="Screen Shot 2022-07-27 at 3 24 52 PM" src="https://user-images.githubusercontent.com/31807984/181355440-3bd73601-38e5-475e-a80c-1ca1792d9c08.png">

#### Additional context

Steps to reproduce:

1. go to solve Count Good Meals
2. select python3
3. copy and past my above solotion
4. generate list of length 44721 with each element being 32
I used this code to generate it and copy paste it:
```
def get_list(x):
    l = list()
    for x in range(0, x):
        l.append(32)
    return l
print(get_list(44721))
```
5. paste generated list into testcase tab on the bottom console
6. click run code
7. observe passing test case
8. click tab test case and add an additional 32
9. click run code
10. observe failing testcase

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the problems asks for the answer with modulo. The expected answer is correct. please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
