### ISSUE TITLE
644. Maximum Average Subarray II - [Missing Test Cases]

### ISSUE THREAD

**Issue by satzhan** [LeetCode-Feedback/LeetCode-Feedback#8396]
#### Your LeetCode username

Satj

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

There are simple large test cases that are missing from the problem.
I have a code that passes test cases, but should get TLE.

#### Code you used for Submit/Run operation

```
// 644. Maximum Average Subarray II 
class Solution {
public:
    double findMaxAverage(vector<int>& a, int k) {
        int n = a.size();
        vector <int> pre(n + 1, 0);
        for (int i = 0; i < n; i++)
            pre[i + 1] = a[i] + pre[i];
        double ret = 1.0 * pre[k] / k;
        queue <int> q;
        for (int i = k; i < n; i++) {
            q.push(i - k);
            ret = max(ret, (1.0*pre[i + 1] - pre[i + 1 - k]) / k);
            int m = q.size();
            while (m--) {
                int j = q.front(); q.pop();
                ret = max(ret, (1.0*pre[i + 1] - pre[j]) / (i+1 - j));
                if ((1.0*pre[i+1-k] - pre[j]) / (i+1-k-j) >= ret) // tail
                    q.push(j);
            }
        }
        return ret;
    }
};
```

#### Language used for code

C++

#### Expected behavior

What actually happens is that LeetCode tests my solution within 200ms.
But when I test it on my test cases each costs up to 3000ms. (which is TLE)

#### Screenshots

Even TLE.
![image](https://user-images.githubusercontent.com/46739227/181371986-118adc72-400d-4ca9-a425-7ce268142e67.png)
![image](https://user-images.githubusercontent.com/46739227/181372129-965c5dae-9028-4ed2-8cf1-d171c258e919.png)

#### Additional context

Test Cases:
[input1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9203603/input1.txt)
[input3.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9203604/input3.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
