### ISSUE TITLE
SQL Language Card - SQL Syntax - Auxiliary SELECT Statements

### ISSUE THREAD

**Issue by mikhael-abdallah** [LeetCode-Feedback/LeetCode-Feedback#8397]
#### Your LeetCode username
mikhaelabdallahdeoliveira

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Card

#### Description of the bug
 At https://leetcode.com/explore/learn/card/sql-language/683/sql-syntax/4324/ the table that shows the result of Multi-column Sorting isn't formatted properly, the table content is all together in one line.

#### Expected behavior
The content of the table should appear formatted

#### Screenshots
![image](https://user-images.githubusercontent.com/84217922/181374423-4720e38b-1086-4a65-a141-6f9fb33af589.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We checked the web page and confirmed it fails to render the table properly but GitHub page renders it normally. After reviewing the code, we inferred the issue perhaps comes from the missing '|' and the newline between paragraph and table. Thanks for the feedback. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
