### ISSUE TITLE
177：本地执行与提交结果不一致。

### ISSUE THREAD

**Issue by DamengLiu** [LeetCode-Feedback/LeetCode-Feedback#8398]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
白露塞纳

**描述**
本地执行结果与提交执行结果不一致。

**你提交或者运行的代码**
```
CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN (
    SELECT e1.salary
    FROM employee e1 
    INNER JOIN employee e2 ON e1.salary <= e2.salary
    # ORDER BY e1.salary desc
    GROUP BY e1.salary
    HAVING count(DISTINCT e2.salary) = N
  );
END
```

**屏幕截图**
![1](https://user-images.githubusercontent.com/39763537/181394912-4a060e04-2560-4e68-8301-8c670170da06.jpg)

**Comment by BrambleWave** [comment]
您好，如果出现测试用例结果和提交结果不一致的情况，您可以再仔细检查并调试您的代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」获得更多帮助。
同时您也可以点击「题解」来查看当前题目的解题思路，或点击这里「[讨论](https://leetcode.cn/circle/discussions/questions)」，将您的疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by DamengLiu** [comment]
太敷衍了吧。你给的链接主要提到了变量的问题，但我这个是SQL，哪里需要变量？如果是变量的问题，那你在我这个版本的基础上提供一个正确的答案呀。
