### ISSUE TITLE
5371 数据过水

### ISSUE THREAD

**Issue by SamZhangQingChuan** [LeetCode-Feedback/LeetCode-Feedback#84]
**Bug 类型**

- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**

https://leetcode-cn.com/problems/find-all-good-strings/ 这道题数据过弱。

很多没有考虑s1比s2字典序大的代码也通过了。
提供一组数据
```
2
"ff"
"aa"
"zz"
```

**期望行为**

应该输出 `0`。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
done

**Comment by SamZhangQingChuan** [comment]
贡献测试用例有 100 积分，请打到我的账户：https://leetcode-cn.com/u/qingchuanzhang-microsoft/，谢谢。
