### ISSUE TITLE
解析代码答案有问题

### ISSUE THREAD

**Issue by Oliverwqcwrw** [LeetCode-Feedback/LeetCode-Feedback#840]
** 题目解析答案有问题**
- [ ] 题目 二叉树的层次遍历 II
- [ ] 题解
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    public static List<List<Integer>> sum = new ArrayList<>();
    public static  int i = 0;
    List<List<Integer>> levelOrderBottom(TreeNode root) {
            List<List<Integer>> lists = levelOrderBottom1(root);
            if (lists == null) {
                return new ArrayList<>();
            }
            int j = 0;
        List<List<Integer>> newArrayList = new ArrayList<>(lists.size());
        for(int i=lists.size() - 1;i >=0;i--) {
            newArrayList.add(lists.get(i));
        }
            return newArrayList;
    }
    List<List<Integer>> levelOrderBottom1(TreeNode root) {
        if (root == null) {
            return null;
        }
            if (root != null && i == 0) {
            List<Integer> list = new ArrayList<>();
            list.add(root.val);
            sum.add(list);
            i++;
        }

        if (root.left != null || root.right != null) {
            List<Integer> list = new ArrayList<>();
            if (root.left != null) {
                list.add(root.left.val);
            }
            if (root.right != null) {
                list.add(root.right.val);
            }
            sum.add(list);
        }
        if (root.left == null && root.right == null) {
            return sum;
        }
        if (root.left != null) {
            levelOrderBottom(root.left);
        }
        if (root.right != null) {
            levelOrderBottom(root.right);
        }
        return sum;
    }
}
- [ ] 编程语言  Java

**描述**
我写了答案之后，提交，显示如下图：
![image](https://user-images.githubusercontent.com/31796988/90953093-334d7700-e49b-11ea-928b-97da5a2009c0.png)

**你使用的语言**
Java

**你提交或者运行的代码**
```
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    public static List<List<Integer>> sum = new ArrayList<>();
    public static  int i = 0;
    List<List<Integer>> levelOrderBottom(TreeNode root) {
            List<List<Integer>> lists = levelOrderBottom1(root);
            if (lists == null) {
                return new ArrayList<>();
            }
            int j = 0;
        List<List<Integer>> newArrayList = new ArrayList<>(lists.size());
        for(int i=lists.size() - 1;i >=0;i--) {
            newArrayList.add(lists.get(i));
        }
            return newArrayList;
    }
    List<List<Integer>> levelOrderBottom1(TreeNode root) {
        if (root == null) {
            return null;
        }
            if (root != null && i == 0) {
            List<Integer> list = new ArrayList<>();
            list.add(root.val);
            sum.add(list);
            i++;
        }

        if (root.left != null || root.right != null) {
            List<Integer> list = new ArrayList<>();
            if (root.left != null) {
                list.add(root.left.val);
            }
            if (root.right != null) {
                list.add(root.right.val);
            }
            sum.add(list);
        }
        if (root.left == null && root.right == null) {
            return sum;
        }
        if (root.left != null) {
            levelOrderBottom(root.left);
        }
        if (root.right != null) {
            levelOrderBottom(root.right);
        }
        return sum;
    }
}
```

**期望行为**
期望运行成功

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/31796988/90953138-70196e00-e49b-11ea-8914-a88f9a80227f.png)

**额外的上下文**
我觉得是不是浏览器缓存，还是你们解析答案的时候没有把之前的入参拿到了新的case里面，请帮忙查看一下，非常感谢！

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。 后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至  [力扣圈子](https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=)  进行题目交流，以获得更好的支持哟～
