### ISSUE TITLE
传值问题

### ISSUE THREAD

**Issue by planeswalkeryanwei** [LeetCode-Feedback/LeetCode-Feedback#8400]
**期望行为**
上班了，改接口了

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/78320154/181412430-93313eef-dc6b-4f31-a0e3-728d08643761.png)

**Comment by BrambleWave** [comment]
左边缩略展示和右边完全展示显示的内容不同，已提交至技术修复，感谢您的反馈。
