### ISSUE TITLE
593. 有效的正方形 题目描述让人费解

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#8401]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 题目

**描述**
> 输入 不是 按任何顺序给出的。

**期望行为**
改成
`输入没有任何顺序。`

**额外的上下文**
[593. 有效的正方形](https://leetcode.cn/problems/valid-square/)

**Comment by BrambleWave** [comment]
你好，当前题目描述已更新，ID：hhummingg 给予积分奖励，请查收。
