### ISSUE TITLE
Wrong problem name - 627. Swap Salary

### ISSUE THREAD

**Issue by ChandanSingh374** [LeetCode-Feedback/LeetCode-Feedback#8402]
#### Your LeetCode username
singhchandan374

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem name should be swap gender/sex
problem link: https://leetcode.com/problems/swap-salary/

<img width="1245" alt="Screenshot 2022-07-28 at 9 05 18 AM" src="https://user-images.githubusercontent.com/87111734/181414847-f9a65e86-08af-4c19-babc-6a9aaf2552f3.png">

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
