### ISSUE TITLE
Latex code being shown in output

### ISSUE THREAD

**Issue by aryanDhakad** [LeetCode-Feedback/LeetCode-Feedback#8403]
#### Your LeetCode username

darkKoder1

#### Category of the bug
- [ ] Question
- [+] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the KMP solution, in the 2nd bullet point, Latex code is being shown instead of it's output.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
