### ISSUE TITLE
1069. Product Sales Analysis II  |   SQL Question not explained properly | Ques has not covered all the testcases

### ISSUE THREAD

**Issue by nitish7dec** [LeetCode-Feedback/LeetCode-Feedback#8406]
Correct sql Code
# Write your MySQL query statement below
select a.product_id,sum(a.quantity) as total_quantity
from sales a
right join
product b
on a.product_id=b.product_id
where a.product_id is not null 
group by product_id

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your solution to the team. We appreciate your support!
