### ISSUE TITLE
13.罗马数字转整数 中文翻译与英文原文限制范围不同 并且 题目描述有歧义 

### ISSUE THREAD

**Issue by lyncancer** [LeetCode-Feedback/LeetCode-Feedback#841]
** Bug 类型**
- 题目

**描述**
1.中文翻译与英文原文限制范围不同
英文题目描述：There are six instances where subtraction is used
中文题目描述：这个特殊的规则只适用于以下六种情况
英文中并没有only表示只能适用于这6种情况。
按照中文范围，测试用例"IL"计算结果应该是51而不是49.

2.按照中文限制范围，**只存在6种特殊情况**，那么依据“通常情况下，罗马数字中小的数字在大的数字的右边。”可以推算，测试用例"IL"是一个无效的罗马数字。题目描述**并没有约定输入字符串无效时应该如何返回**。
另外，即使是英文的范围，以下例子仍然可能造成误解为字符最多放置于他后面的两位的字符旁。
I can be placed before V (5) and X (10) to make 4 and 9. 
X can be placed before L (50) and C (100) to make 40 and 90. 
C can be placed before D (500) and M (1000) to make 400 and 900.

**你使用的语言**
C#

**期望行为**
1.修改中文题目描述，“有且不仅有以下6种情况”。
2.如果有例子IM表示999更不易造成误解。

**额外的上下文**
例如， 罗马数字 2 写做 II ，即为两个并列的 1。12 写做 XII ，即为 X + II 。 27 写做  XXVII, 即为 XX + V + II 。

通常情况下，罗马数字中小的数字在大的数字的右边。但也存在特例，例如 4 不写做 IIII，而是 IV。数字 1 在数字 5 的左边，所表示的数等于大数 5 减小数 1 得到的数值 4 。同样地，数字 9 表示为 IX。这个特殊的规则只适用于以下六种情况：

I 可以放在 V (5) 和 X (10) 的左边，来表示 4 和 9。
X 可以放在 L (50) 和 C (100) 的左边，来表示 40 和 90。 
C 可以放在 D (500) 和 M (1000) 的左边，来表示 400 和 900。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/roman-to-integer
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by PsiACE** [comment]
Hi，很高兴看到您的反馈，关于您的问题，这里做以下几点说明：

- 根据罗马数字书写规则，存在的减法情况就只有列出的六种，所以中文翻译和英文表述都不应该视作有误
- 题目所用测试样例都为正确的罗马数字，所以您无需考虑输入字符串无效的问题（自测时除外）
- IM 这样的例子出现了跨位的情况，不符合罗马数字的书写规则，可能会引起误读
- 49 应该写作 XLIX, 999 应该写作 CMXCIX

关于罗马数字的具体书写规则，您可以参考维基百科或者相关的资料。我这里推荐您这一篇：[罗马数字 - Mathematics](https://b2b.partcommunity.com/community/knowledge/zh_CN/detail/10753/%E7%BD%97%E9%A9%AC%E6%95%B0%E5%AD%97#knowledge_article)

祝您刷题愉快！

**Comment by lyncancer** [comment]
@PsiACE  很感谢您抽空回复！但是我仍然不能接受不做修改地直接关闭这个问题。原因如下：
1. 您给出的关于罗马数字的参考材料非常详尽，然而题目并没有如您所提供的材料一般给出了各种情况。并且并不是所有人都会对罗马数字的规则了如指掌，或者刷到罗马数字的题目就会去进行完整的学习来掌握罗马数字的拼写。
2. 我再次看了中文上下文，并没有告诉我输入一定是一个有效的罗马数字，因此我在刷题时首先就会想到处理无效数据。
因此我认为这题的描述并不是严谨的。在做题过程中产生疑惑是很正常的事情。希望贵方能对题目描述进行修改。感谢！

**Comment by PsiACE** [comment]
@lyncancer 很抱歉直到现在才回复你，我们刚刚在中文中更新了提示部分，对情况做了一个简单的说明，应该可以帮助到刷题的扣友们。具体如下：

**提示：**

-    题目所给测试用例皆符合罗马数字书写规则，不会出现跨位等情况。
-    IC 和 IM 这样的例子并不符合题目要求，49 应该写作 XLIX，999 应该写作 CMXCIX 。
-    关于罗马数字的详尽书写规则，可以参考 [罗马数字 - Mathematics](b2b.partcommunity.com/community/knowledge/zh_CN/detail/10753/%E7%BD%97%E9%A9%AC%E6%95%B0%E5%AD%97#knowledge_article) 。
