### ISSUE TITLE
Don't have permission to watch video

### ISSUE THREAD

**Issue by wkh11** [LeetCode-Feedback/LeetCode-Feedback#8410]
I have leetcode premium, but it is not allowing me to watch the video explanation. Can someone explain to me how to fix this issue?

**Comment by vi5hnuvardhan** [comment]
+1

**Comment by zobee29** [comment]
+1 

Experiencing this problem here:
https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/692/challenge-problems/4425/

**Comment by edyadkin** [comment]
https://leetcode.com/explore/featured/card/system-design/689/system-design-basics/4403/
It says private video and requires a login to vimeo now. 
Why?

**Comment by gnathani** [comment]
Same issue. Logged in to Vimeo but still cant watch the video.
<img width="1440" alt="Screen Shot 2022-07-28 at 12 40 50 PM" src="https://user-images.githubusercontent.com/105834935/181592257-96ff4781-52d2-4538-874e-d9bae22485c4.png">

**Comment by sanmar96** [comment]
+1

**Comment by ShannonCanTech** [comment]
+1 just signed up for premium and can't access explanation videos.

**Comment by Phan2408** [comment]
I'm facing the same issue

**Comment by yangmaoBlueMyth** [comment]
+1

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.
Our team is working with Video Platform to fix the issue right now.
We appreciate your support!
