### ISSUE TITLE
Unable to access premium content after paying for whole year "Sorry, you don’t have permission to watch."

### ISSUE THREAD

**Issue by Phan2408** [LeetCode-Feedback/LeetCode-Feedback#8411]
<img width="1387" alt="Screen Shot 2022-07-28 at 12 33 39 PM" src="https://user-images.githubusercontent.com/49665185/181590850-c356bb12-0da5-4a15-9346-c85f4e990397.png">

I paid for premium content for System Design and I'm unable to access videos.
Please help me to resolve this issue.

Thanks

**Comment by yangmaoBlueMyth** [comment]
me too. is their service down?

**Comment by ShannonCanTech** [comment]
+1

**Comment by yangmaoBlueMyth** [comment]
now they show the video doesnt even exist

**Comment by Phan2408** [comment]
yeah, I noticed the same @yangmaoBlueMyth

**Comment by yangmaoBlueMyth** [comment]
very unhappy user experience.

**Comment by Phan2408** [comment]
it's really frustrating to see these issues for premium content.

**Comment by LC-Pam** [comment]
Thanks for contacting LeetCode support! Checking now our team is aware of the issue and is working on a fix as soon as possible. We apologize for any inconvenience this may cause and expect a fix today.
