### ISSUE TITLE
412 FizzBuzz Video in LeetCode Beginners Guide is private

### ISSUE THREAD

**Issue by Shikaga** [LeetCode-Feedback/LeetCode-Feedback#8412]
#### Your LeetCode username
Shikaga

#### Category of the bug
Video Error

#### Description of the bug
On this page: https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/692/challenge-problems/4424/
The video is set to private, so even subscribed members can't view it. 

#### Screenshots
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/589084/181594807-344bea6c-71d6-48e2-b463-3ba8b91c0754.png">

**Comment by LC-Pam** [comment]
Thanks for contacting LeetCode support! Checking now our team is aware of the issue and is working on a fix as soon as possible. We apologize for any inconvenience this may cause and expect a fix today.
