### ISSUE TITLE
video is private

### ISSUE THREAD

**Issue by zubairahmedanas** [LeetCode-Feedback/LeetCode-Feedback#8413]
1480. Running Sum of 1D Array

the video is private.

**Comment by yangmaoBlueMyth** [comment]
i have the same issue here, what happened? is their service down?

**Comment by salazardaniels** [comment]
same here

**Comment by ShannonCanTech** [comment]
Same issue. There are several other issues submitted on this topic.

**Comment by yangmaoBlueMyth** [comment]
now they show the video does not exist

**Comment by LC-Pam** [comment]
Thanks for contacting LeetCode support! Checking now our team is aware of the issue and is working on a fix as soon as possible. We apologize for any inconvenience this may cause and expect a fix today.
