### ISSUE TITLE
Payed for System Design, but unable to watch now, showing that it is private and needs to log in. 

### ISSUE THREAD

**Issue by yangmaoBlueMyth** [LeetCode-Feedback/LeetCode-Feedback#8414]
#### Your LeetCode username
yangmao
yangmao1990@foxmail.com

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I paid for the System Design content, but now it showed that it is private and unable to watch. 

#### Screenshots

![Screenshot 2022-07-28 102537](https://user-images.githubusercontent.com/78499376/181600286-bacd0bbe-e16f-4077-8a14-c9d57762992d.jpg)

**Comment by ShannonCanTech** [comment]
+1

**Comment by Phan2408** [comment]
I'm facing the same

**Comment by gilmanjo** [comment]
+1

**Comment by LC-Pam** [comment]
Thanks for contacting LeetCode support! Checking now our team is aware of the issue and is working on a fix as soon as possible. We apologize for any inconvenience this may cause and expect a fix today.
