### ISSUE TITLE
Missing test case

### ISSUE THREAD

**Issue by khankash** [LeetCode-Feedback/LeetCode-Feedback#842]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### https://leetcode.com/problems/group-anagrams/
My code is accepted but it should have failed on the following test case.
["abbbbbbbbbbb", "aaaaaaaaaaab"]

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<String>> groupAnagrams(String[] strs) {
        if (strs.length == 0) return new ArrayList();
        Map<String, List> ans = new HashMap<String, List>();
        int[] count = new int[26];
        for (String s : strs) {
            Arrays.fill(count, 0);
            for (char c : s.toCharArray()) count[c - 'a']++;

            StringBuilder sb = new StringBuilder("");
            for (int i = 0; i < 26; i++) {
                // sb.append('#');
                sb.append(count[i]);
            }
            String key = sb.toString();
            if (!ans.containsKey(key)) ans.put(key, new ArrayList());
            ans.get(key).add(s);
        }
        return new ArrayList(ans.values());
    }
}
```

#### The solution should not be accepted since it fails on some of the test cases.
My code is exactly same as the Approach 2 listed under the solution tab with a minor change ("do not append # to separate count for characters") i.e. // sb.append('#');

Solution listed with the problem produces following result

Input : ["abbbbbbbbbbb", "aaaaaaaaaaab"]
output : [["aaaaaaaaaaab"],["abbbbbbbbbbb"]]

My code outputs incorrect result for the above input
output : [["abbbbbbbbbbb","aaaaaaaaaaab"]]

My code is still successfully accepted. It should have failed. 

#### Explanation : 

When processing first string, count array will be [1, 11], string builder = "111"
When processing second string, count array will be [11, 1], string builder = "111"
My code does not distinguish between these two strings

If the //sb.append("#") line would not be commented then the above two strings would have been #1#11, #11#1

**Comment by lc-pam** [comment]
Hi @khankash 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @khankash 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
