### ISSUE TITLE
A Follow-up Requirement Should be Added - 2261. K Divisible Elements Subarrays

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#8421]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The brute force with O(n^3) time complexity can be accepted. However, users can use trie or rolling hash to solve this problem in O(n^2) time complexity. In fact, the brute force for this problem is not enough to be marked as "Medium". As the third problem of a weekly contest, the current constraints is even too easy for the second problem. And if this problem is used in a real interview, the expected solution must be trie or rolling hash, the interviewee who can only writes brute force cannot pass the interview.
So, a follow-up should be added:
Can you solve this problem in O(n^2) time complexity?

Code you used for Submit/Run operation

Brute Force (O(n^3))
```
class Solution:
    def countDistinct(self, nums: List[int], k: int, p: int) -> int:
        
        st = set()
        for i in range(len(nums)):
            for j in range(i,len(nums)):
                cnt = 0
                for jj in range(i,j+1):
                    if nums[jj]%p==0:
                        cnt+=1
                        if cnt>k:
                            break
                else:
                    st.add(tuple(nums[i:j+1]))
        return len(st)
```

Trie (O(n^2))
```
class Solution:
    def countDistinct(self, nums: List[int], k: int, p: int) -> int:
        
        ne = [{}]        
        def get():
            ne.append({})
            return len(ne)-1
        
        for i in range(len(nums)):
            cnt,node = 0,0
            for j in range(i,len(nums)):
                if nums[j]%p==0: 
                    cnt+=1
                if cnt>k: 
                    break
                if nums[j] not in ne[node]:
                    ne[node][nums[j]] = get()
                node = ne[node][nums[j]]
        
        return len(ne)-1
```

Rolling Hash (O(n^2), possibly get WA because of the conflict)
```
class Solution:
    def countDistinct(self, nums: List[int], k: int, p: int) -> int:
    
        st = set()
        mod = (10**9+7)*(10**9+9)
        pw = random.randint(10**8,10**9)
        
        for i in range(len(nums)):
            cnt,hashh = 0,0
            for j in range(i,len(nums)):
                if nums[j]%p==0:
                    cnt+=1
                if cnt>k:
                    break
                hashh = (hashh*pw+nums[j])%mod
                st.add(hashh)
        return len(st)
```
 
Language used for code
Python3

Expected behavior
A follow-up requirement should be added:
Can you solve this problem in O(n^2) time complexity?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
