### ISSUE TITLE
Testcase Needs to be Enhanced - 304. Range Sum Query 2D - Immutable

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#8423]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
This problem is designed to help users knowing 2D prefix sum. But the solution using 1D prefix sum can be passed because of the constraints. If users use 1D prefix sum, the problem is almost meaningless. So, the constraints of the "sumRegion" call should be increased to make sure that 1D prefix sum can get TLE.

Code you used for Submit/Run operation

1D prefix sum:
```
class NumMatrix:
    def __init__(self, matrix: List[List[int]]):
        prefix = [[0 for j in range(len(matrix[0]))] for i in range(len(matrix))]
        for i in range(len(matrix)):
            for j in range(len(matrix[0])):
                prefix[i][j]=prefix[i][j-1]+matrix[i][j]
        self.prefix = prefix

    def sumRegion(self, row1: int, col1: int, row2: int, col2: int) -> int:
        sm = 0
        for r in range(row1,row2+1):
            sm+=self.prefix[r][col2]-self.prefix[r][col1-1] if col1 else self.prefix[r][col2]
        return sm
```

2D prefix sum:
```
class NumMatrix:
    def __init__(self, matrix: List[List[int]]):
        prefix = [[0 for j in range(len(matrix[0]))] for i in range(len(matrix))]
        for i in range(len(matrix)):
            for j in range(len(matrix[0])):
                prefix[i][j]=matrix[i][j]
                if i>0:
                    prefix[i][j]+=prefix[i-1][j]
                if j>0:
                    prefix[i][j]+=prefix[i][j-1]
                if i>0 and j>0:
                    prefix[i][j]-=prefix[i-1][j-1]
        self.prefix=prefix

    def sumRegion(self, row1: int, col1: int, row2: int, col2: int) -> int:
        sm = self.prefix[row2][col2]
        if row1>0:
            sm-=self.prefix[row1-1][col2]
        if col1>0:
            sm-=self.prefix[row2][col1-1]
        if row1>0 and col1>0:
            sm+=self.prefix[row1-1][col1-1]
        return sm
```

Language used for code
Python3

Expected behavior
1. The constraints of the sumRegion call should be increased to 10^5.
2. At least one testcase with n==200 and 10^5 calls of sumRegion should be added.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Increasing the constraints will fail the intended solutions in the slower languages. The current constraints are the best for the problem. We appreciate your support!
