### ISSUE TITLE
Problematic test case

### ISSUE THREAD

**Issue by ACHIYANT** [LeetCode-Feedback/LeetCode-Feedback#8428]
#### Your LeetCode username

achiyant

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

one test case is creating problem.

#### Code you used for Submit/Run operation

```
// Sort an Array
class Solution {
public:
            int partition(vector<int>&nums,int l,int h)
    {
        //random pivot choosing.
        //first choose ans random and then swap it with first element so that partition location will be random.
        int ran = rand()%(h-l + 1) + l;
        swap(nums[l], nums[ran]);
        int count = 0;
        for(int i=l+1;i<=h;i++) 
        {
            if(nums[i]<nums[l]) count++;
        }
        int pv = l+count;
        swap(nums[l], nums[pv]);
        
        
        int pivot=nums[l],i=l,j=h+1;
        do{
            do{i++;}while(nums[i]<=pivot&&i<=h);
            do{j--;}while(nums[j]>pivot);
            if(i<j)
                swap(nums[i],nums[j]);
        }while(i<j);
        swap(nums[j],nums[l]);
        return pv;
    }
    
    
    void quickSort(vector<int>&nums,int l,int h)
    {
        int j;
        if(l<h)
        {
           j=partition(nums,l,h);
            quickSort(nums,l,j-1);
            quickSort(nums,j+1,h);
        }
    }
    vector<int> sortArray(vector<int>& nums) {
        int n=nums.size();
        
        quickSort(nums,0,n-1);
        return nums;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Test case creating problem:-[5,1,1,2,0,0]
Should accept my code for this test case.

#### Screenshots

Screenshot of same code for custom test case answer:-
![Screenshot 2022-07-29 at 12 51 23 PM](https://user-images.githubusercontent.com/55272025/181706040-e54b2835-ca7f-47b6-a867-8b56dcf1b4d7.png)

Screenshot of same code for submission and getting error for same test case as in custom test case above:-
![Screenshot 2022-07-29 at 12 52 41 PM](https://user-images.githubusercontent.com/55272025/181706467-b2c4e1fc-e4e7-4133-baff-56b88264de1a.png)
![Screenshot 2022-07-29 at 12 56 38 PM](https://user-images.githubusercontent.com/55272025/181707351-26076ff4-61fb-4f9c-a322-176a7b167043.png)

#### Additional context

Test case:-[5,1,1,2,0,0]
When i am running the above written code it works perfectly for all test cases but when i want to submit my code it gives error for this test case.when i using custom test case option for checking my code with this test case it work perfectly again but this same code at the time of submission showing wrong answer for the same code.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
