### ISSUE TITLE
Missing Test Case

### ISSUE THREAD

**Issue by xariniov9** [LeetCode-Feedback/LeetCode-Feedback#843]
#### Category of the bug
- [ 1] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The problem in the biweekly contest is missing a test case.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minOperations(vector<int>& nums) {
        int ans = 0, mx = 0;
        for(int i=0; i<nums.size(); i++) {
            ans += __builtin_popcount(nums[i]);
            mx = max(mx, nums[i]);
        }
        while(mx) {
            mx>>=1;
            ans++;
        }
        return ans-1;
    }
};
```

#### Expected behavior

for test case [0] it should have resulted 0, but my code returns -1 and still gets accepted

**Comment by lc-pam** [comment]
Hi @xariniov9 
Thank you for reaching out to us. Would you mind letting me know which problem you are referring to? Providing the problem's number or link can be helpful.

**Comment by xariniov9** [comment]
1558. Minimum Numbers of Function Calls to Make Target Array

(Sorry I forgot to add that)

**Comment by lc-pam** [comment]
Hi @xariniov9 
Thank you for providing the problem's name. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @xariniov9 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
