### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by tsmahur** [LeetCode-Feedback/LeetCode-Feedback#8433]
#### Your LeetCode username

tsmahur

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Solution is accepted, but the test case fails for below input:
```
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab"
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba"
```
```byte[] characterTracker=new byte[range]; //byte can have -128 to 127, but in actual an alphabet cab be more than 127 time in a string```

#### Code you used for Submit/Run operation

```
// 242. Valid Anagram
public boolean isAnagram(String s, String t) {
        if(s.length()!=t.length()) return false;
        int range=26;
        // int range=255;
        byte[] characterTracker=new byte[range]; //byte can have -128 to 127, but in actual an alphabet can be more than 127 time in a string
        // int[] characterTracker=new int[range];
        for(int i=0;i<s.length();i++){
            characterTracker[((int) s.charAt(i))-97]++;
            characterTracker[((int) t.charAt(i))-97]--;
        }
        for(int i=0;i<range;i++){
            if(characterTracker[i]!=0) return false;   
        }

        return true;
    }
```

#### Language used for code

Java

#### Expected behavior

Solution should not be accepted as it fails a test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/32067811/181809762-5823ab8b-3bac-483d-9618-4fd3ced647c3.png)
![image](https://user-images.githubusercontent.com/32067811/181809829-149d05cd-ce9d-40ca-8a9b-fd187bb84ae9.png)

#### Additional context

Link of Problem : [https://leetcode.com/problems/valid-anagram/](https://leetcode.com/problems/valid-anagram/)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
