### ISSUE TITLE
Missing Test Case - 2226. Maximum Candies Allocated to K Children

### ISSUE THREAD

**Issue by ayush68** [LeetCode-Feedback/LeetCode-Feedback#8434]
actually maximum number candies are taken maximum number in the array which is getting to be true...but in vase we have one child  then the maximum number wont be the answer perhaps sum of the array will be answer we can take the test case [2,5,7] array of candies and k=1 then answer should be 14 instead of 7

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted  your feedback to the team. We appreciate your support!
