### ISSUE TITLE
Typo in Dynamic Programming card

### ISSUE THREAD

**Issue by none-null-empty** [LeetCode-Feedback/LeetCode-Feedback#8435]
#### Your LeetCode username
user0763PD

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Card

#### Description of the bug
The questions with single choice option have "Multiple Choice Question" label  in Dynamic Programming card->Intro to Dynamic Programming->Chapter 1 Quiz (https://leetcode.com/explore/learn/card/dynamic-programming/630/an-introduction-to-dynamic-programming/4095/) 

#### Expected behavior
The questions with single choice option should have "Single Choice Question" label  

#### Screenshots
![image](https://user-images.githubusercontent.com/109349815/181835879-cd542546-2a3c-467d-9007-883b4dd229cf.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
