### ISSUE TITLE
Invalid TestCase 377. Combination Sum IV

### ISSUE THREAD

**Issue by jindalharshit** [LeetCode-Feedback/LeetCode-Feedback#8437]
The ans can not be represented in type int. Even thugh it is mentioned that test cases are in such a way that sum is less than 2^31-1
![image](https://user-images.githubusercontent.com/31099013/181845615-ca7ed1f0-7574-4d85-9ba3-9262fbe861ce.png)

**Comment by stormsunshine** [comment]
The problem mentions that the answer can fit in a 32-bit integer, not the sum. Please read problem description carefully.
