### ISSUE TITLE
Missing Test Case - 437. Path Sum III

### ISSUE THREAD

**Issue by oscardel13** [LeetCode-Feedback/LeetCode-Feedback#8438]
#### Your LeetCode username

oscardel13

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When submitting my code in one particular test case (85) comes out as wrong answer but when I run the same case as a test case it comes it returns the correct answer. (as seen in the picture) and also when seeing my hashtable it has {1:1} which also should not be in the hashtable as nothing should have been added. 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def pathSum(self, root, targetSum, past={}):
        """
        :type root: TreeNode
        :type targetSum: int
        :rtype: int
        """
        ans = 0
        if not root:
            return 0
        print("root: " + str(root.val) + " past: " + str(past))
        if root.val == targetSum:
            ans += 1
        if root.val in past:
            ans += past[root.val]
        tmp = {}
        for i in past:
            new = i - root.val
            if new not in tmp:
                tmp[new] = 0
            tmp[new] += 1
        if root.val == 0:
            tmp = past
        new = targetSum - root.val
        if new not in tmp:
            tmp[new] = 0
        tmp[new] += 1
        return ans + self.pathSum(root.left,targetSum,tmp) + self.pathSum(root.right,targetSum,tmp)
        
        
```

#### Language used for code

Python

#### Expected behavior

I expected to not have the extra row in the hashtable to messed up the calcutions

#### Screenshots

![leetcodeBugQ473](https://user-images.githubusercontent.com/18271928/181872059-3e27d640-16a4-414c-bc86-0401eeb0139f.JPG)

**Comment by Vinamra7** [comment]
You are using an extra variable path, with a default value {}. 
`Leetcode uses the same class object in a loop for different testcases, so path will store the value of previously used testcase`
```
object = Solution()
while testCase_count:
    object.pathSum(root, targetSum)
    testCase_count -= 1
```
You can fix this by creating a second function with the path variable inside the same class, Like this
```
class Solution(object):
    #new function pathsum2
    def pathsum2(self,root, targetSum, past):
        """
        :type root: TreeNode
        :type targetSum: int
        :rtype: int
        """
        ans = 0
        if not root:
            return 0
        print("root: " + str(root.val) + " past: " + str(past))
        if root.val == targetSum:
            ans += 1
        if root.val in past:
            ans += past[root.val]
        tmp = {}
        for i in past:
            new = i - root.val
            if new not in tmp:
                tmp[new] = 0
            tmp[new] += 1
        if root.val == 0:
            tmp = past
        new = targetSum - root.val
        if new not in tmp:
            tmp[new] = 0
        tmp[new] += 1
        return ans + self.pathsum2(root.left,targetSum,tmp) + self.pathsum2(root.right,targetSum,tmp)        
    def pathSum(self, root, targetSum):
        return self.pathsum2(root,targetSum,{})
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
