### ISSUE TITLE
Missing Test Case - 981. Time Based Key-Value Store 

### ISSUE THREAD

**Issue by Vinamra7** [LeetCode-Feedback/LeetCode-Feedback#8439]
#### Your LeetCode username
mishravinamra5

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Solution is accepted, but the test case fails for below input:
```
["TimeMap","set","set","get","get"]
[[],["foo","bar",3],["foo","bar2",4],["foo",3],["foo",4]]
```

`Current testcases of the problem does not include consecutive timestamps(a variable of the problem). As seen in the given code below(which got accepted) deleting consecutive numbers (i.e timestamp+1) does not affect the solution.`

#### Code you used for Submit/Run operation

```
// 981. Time Based Key-Value Store
class TimeMap {
public:
	unordered_map<string, map<int, string>> m;
	void set(string key, string value, int timestamp) {
		m[key][timestamp] = value;
	}
	string get(string key, int timestamp) {
		m[key][timestamp + 1];
		auto it = m[key].upper_bound(timestamp); it--;
		m[key].erase(timestamp + 1);
		return it->second;
	}
};
```

#### Language used for code
C++

#### Expected behavior
Solution should not be accepted as it fails a test case.

#### Screenshots

![Screenshot (85)](https://user-images.githubusercontent.com/72907109/181872763-0fec6f52-c18d-4728-ae1f-e3773728b05e.png)
![Screenshot (86)](https://user-images.githubusercontent.com/72907109/181872790-5af5ff1a-3aaf-4361-a39c-37d9a74b5191.png)

#### Additional context
Link to problem: https://leetcode.com/problems/time-based-key-value-store/
My Solution(which is wrong but got accepted) : https://leetcode.com/submissions/detail/760288215/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
