### ISSUE TITLE
Missing testcase in 20. Valid Parentheses

### ISSUE THREAD

**Issue by xariniov9** [LeetCode-Feedback/LeetCode-Feedback#844]
#### Category of the bug - Test case missing
- [ 1] Question

#### Description of the bug

20. Valid Parentheses is missing a crucial testcase

#### Code you used for Submit/Run operation

```
// 20. Valid Parentheses
class Solution {
public:
    bool isValid(std::string s)
    {
        bool val = false;
        if (s.size() == 0)
            return true;

        else if ((s.size() % 2 != 0) && (s.size() != 0))
            return val;
        else
        {        
            std::map<char, char> mp;
            mp['}'] = '{';
            mp[')'] = '(';
            mp[']'] = '[';
            std::vector<char> str = {};

            for (unsigned int i = 0; i < s.size(); i++){
                auto mapIt = mp.find(s[i]);
                if (mapIt != mp.end()){
                    if ( (str.size() > 0) && (mapIt->second == str[str.size()-1])){
                        str.pop_back();
                   }
                }
                else {
                    str.push_back(s[i]); 
                }
           }
           if (str.size() == 0)
                val = true;
        }
        return val;
    }
};
```

#### Expected behavior

With "))" input expected behaviour is false, but my code returns true and still gets AC

#### Screenshots

![image](https://user-images.githubusercontent.com/16347296/90963179-5267fb00-e4d3-11ea-9ac5-6ea5a646ec7a.png)

**Comment by lc-pam** [comment]
Hi @xariniov9 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @xariniov9 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
