### ISSUE TITLE
Invalid Test Case 7. Expecting wrong output

### ISSUE THREAD

**Issue by ClaymoreRoomba** [LeetCode-Feedback/LeetCode-Feedback#8441]
#### Your LeetCode username

ClaymoreRoomba

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The constraints say that if a value is not within the 32 int limit return 0
The test case: 1534236469 is <= ( 2 ** 31 ) - 1, yet the test expects a return of 0

#### Code you used for Submit/Run operation

```
var reverse = function(num){
    if(!(num >= -1 * 2 ** 31 && num <= 2 ** 31 - 1)) return 0;
    const digits = num.toString().split('').reverse();
    if(!/\d/.test(digits[digits.length - 1])){
        digits.unshift(digits[digits.length - 1]);
        digits.pop();
    }
    return +digits.join('');
}
```

#### Language used for code

JavaScript

#### Expected behavior

The value would expect the test would want:
9646324351
The value the test actually wanted:
0

#### Screenshots

<img width="745" alt="image" src="https://user-images.githubusercontent.com/73785138/181914329-2eb0a6e4-81dd-4180-a9e6-ef703649c525.png">

**Comment by stormsunshine** [comment]
Why do you think 9646324351 is within a 32-bit integer?
