### ISSUE TITLE
Invalid Test Case - 125. Valid Palindrome

### ISSUE THREAD

**Issue by jakechenTW** [LeetCode-Feedback/LeetCode-Feedback#8442]
#### Your LeetCode username
jakechentw

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The expected output of the test case "0P" seems to be wrong.

#### Code you used for Submit/Run operation
```
// Two Sum
class Solution {
public:
    bool isPalindrome(string s) {
        string lower_alpha_s;
        for (const auto& c : s) {
            if (!isalpha(c)) {
                continue;
            }
            lower_alpha_s += tolower(c);
        }
        
        size_t length = lower_alpha_s.length();
        for (auto i = 0; i < length/2; i++) {
            if (lower_alpha_s[i] != lower_alpha_s[length - i - 1]) {
                return false;
            }
        }
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
"0P" became "P" after removing all non-alphanumeric characters,  which seems to be a valid palindrome for me.

**Comment by stormsunshine** [comment]
Please check the definition of "alphanumeric".

**Comment by jakechenTW** [comment]
Got it! Thanks for the explanition
