### ISSUE TITLE
Missing Test Case - 307. Range Sum Query - Mutable

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#8447]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution is getting TLE on this test case:
[Missing Test Case - 307.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9228189/Missing.Test.Case.-.307.txt)

#### Code you used for Submit/Run operation

```
public class NumArray 
{
    private int[] _nums;
    private int _sum;
    
    public NumArray(int[] nums) => (_nums, _sum) = (nums, nums.Sum());
    
    public void Update(int index, int val) 
    {
        _sum += val - _nums[index];
        _nums[index] = val;
    }
    
    public int SumRange(int left, int right) 
    {
        if (right - left < _nums.Length / 2) return new ArraySegment<int>(_nums, left, right - left + 1).Sum();
        
        return _sum 
            - new ArraySegment<int>(_nums, 0, left).Sum() 
            - (right + 1 == _nums.Length ? 0 : new ArraySegment<int>(_nums, right + 1, _nums.Length - right - 1).Sum()); 
    }
}
```

#### Language used for code

C#

#### Expected behavior

This code is passing all tests and getting Accepted. But it should get TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
