### ISSUE TITLE
Missing Test Case - 2359. Find Closest Node to Given Two Nodes

### ISSUE THREAD

**Issue by bishal1433** [LeetCode-Feedback/LeetCode-Feedback#8453]
#### Your LeetCode username
https://leetcode.com/bishal_/

#### Category of the bug
-[ ]Solution

#### Description of the bug
One test Case showing wrong output

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int closestMeetingNode(vector<int>& edges, int node1, int node2) {
        int n=edges.size();
        
        vector <vector <int>> adj(n);
        vector <vector <int>> dis(2,vector <int> (n,INT_MAX));
        
        for(int i=0;i<n;i++){
            if(edges[i]!=-1){
                adj[i].push_back(edges[i]);
            }
        }
        
        
        function <void(int,int)> bfs=[&](int node,int type){
            vector <int> vis(n,0);
            
            queue <pair <int,int>> q;
            q.push({node,0});
            vis[node]=1;
            dis[type][node]=0;
            
            while(q.empty()!=1){
                auto temp=q.front();
                q.pop();
                
                int cost=temp.second;
                int u=temp.first;
                
                dis[type][u]=min(dis[type][u],cost);
                
                for(auto v:adj[u]){
                    if(vis[v]==0){
                        q.push({v,cost+1});
                        vis[v]=1;
                    }
                }
            }
        };
        
        
        bfs(node1,0);
        bfs(node2,1);
        
        int res=INT_MAX;
        int node=-1;
        
        for(int i=0;i<n;i++){
            if(dis[0][i]!=INT_MAX and dis[1][i]!=INT_MAX){
                if(dis[0][i]+dis[1][i]<res){
                    res=min(dis[0][i]+dis[1][i],res);
                    node=i;
                }
                
            }
        }
        
        
        return (res==INT_MAX)?-1:node;
        
    }
};
```

#### Language used for code
C++

#### Expected behavior

[4,4,8,-1,9,8,4,4,1,1]
5
6
For above test case it showing expected answer as 1 but with dry run and with my code I am getting 4 which should be answer.

#### Screenshots

![101](https://user-images.githubusercontent.com/60804393/182029452-894e0d85-f4b9-4540-80af-c09942f52666.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
