### ISSUE TITLE
Invalid Test Cases for rust language - 415. Add Strings

### ISSUE THREAD

**Issue by shanithkk** [LeetCode-Feedback/LeetCode-Feedback#8454]
#### Your LeetCode username

kkshanith

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

Rust does not support more than u128 bit integer value. the maximum capacity of an integer in rust language is u128.
so writing test-case according to the language specification. i cant submit the solution in rust.

#### Code you used for Submit/Run operation

```
impl Solution {
    pub fn add_strings(num1: String, num2: String) -> String {
         let mut res=0 ;
        let mut len_num1 = num1.len();
        let mut len_num2 = num2.len();
        let mut s =num1.chars().collect::<Vec<char>>();
        let mut s2 =num2.chars().collect::<Vec<char>>();

        let mut len = if len_num1>len_num2 {len_num1}else {len_num2};

        while s.len() !=s2.len(){
            if len_num1>len_num2{
                s2.insert(0,'0');
            }
            else {
                s.insert(0, '0');
            }
        }
        let mut carry =0;
        let mut final_vec = Vec::new();
        while len>0 {
            let mut cur =carry;
            if len > 0{
                cur = cur + s[len-1] as u128  -'0' as u128;
                cur = cur + s2[len -1] as u128 -'0' as u128;
            }
            carry = cur/10;
            cur = cur %10;

            final_vec.push(cur);

            len = len -1;
        }
        if carry != 0{
            final_vec.push(1);
        }

        final_vec.reverse();
        for i in 0..final_vec.len(){
            res = res *10 + final_vec[i];
        }

        res.to_string()
        }
}
```

#### Language used for code
RUST

#### Expected behavior
Please write the test cases according to the language.

#### Screenshots
<img width="1190" alt="leet" src="https://user-images.githubusercontent.com/59169878/182034084-6a3e1666-b535-40aa-8bf0-70c065228a1c.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
