### ISSUE TITLE
Inconsistent behaviour b/w "run" and "submit"  - 746. Min Cost Climbing Stairs

### ISSUE THREAD

**Issue by deepakmeena635** [LeetCode-Feedback/LeetCode-Feedback#8455]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    dct = dict()
    def minCostClimbingStairs(self, cost: List[int]) -> int:

        if len(cost)<=1:
          return 0;
        if len(cost)==2:
          return min(cost);
        if len(cost) in self.dct:
            return self.dct[len(cost)]
          
        res1 = cost[0]
        res1+= self.minCostClimbingStairs(cost[1:]) if len( cost) -1 not in self.dct else self.dct[len(cost)-1]
        res2 = cost[1]
        res2+= self.minCostClimbingStairs(cost[2:]) if len( cost) -2 not in self.dct else self.dct[len(cost)-2]
        self.dct[len(cost)] = min( res1, res2)
        return self.dct[len(cost)]
```

#### Language used for code

python3.6

#### Expected behavior

I verified this issue on my end, answer returned is 6. The same should happen not only when i run it but also when submitted. 

#### Screenshots

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/37202245/182035232-33515ad7-183a-450e-86e4-ab74ba1d5318.png">

#### Additional context

this  image describes the issue pretty well, please take notice of run vs submission on the same test case

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
