### ISSUE TITLE
Missing Test Case / Strange behaviour when testing your code with this example - 850. Rectangle Area II

### ISSUE THREAD

**Issue by FireSlayer57** [LeetCode-Feedback/LeetCode-Feedback#8457]
#### Your LeetCode username

masteralphi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test case: [[5,10,5,11]]
When running the correct solution on this test case the checking system produces an unexpected message - Line 37: AttributeError: 'NoneType' object has no attribute 'start'
 One might think that the constraints ban rectangles with zero width but some test cases contain such rectangles. Therefore, I suggest that this is an issue to be fixed.

#### Code you used for Submit/Run operation

```
// Rectangle Area II
class Solution:
    def rectangleArea(self, rectangles: List[List[int]]) -> int:
        N = len(rectangles)
        x_vals, y_vals = set(), set()
        for x1, y1, x2, y2 in rectangles:
            x_vals.add(x1)
            x_vals.add(x2)
            y_vals.add(y1)
            y_vals.add(y2)

        imapx = sorted(x_vals)
        imapy = sorted(y_vals)
        mapx = {x: i for i, x in enumerate(imapx)}
        mapy = {y: i for i, y in enumerate(imapy)}

        grid = [[0] * len(imapy) for _ in imapx]
        for x1, y1, x2, y2 in rectangles:
            for x in range(mapx[x1], mapx[x2]):
                for y in range(mapy[y1], mapy[y2]):
                    grid[x][y] = 1

        ans = 0
        for x, row in enumerate(grid):
            for y, val in enumerate(row):
                if val:
                    ans += (imapx[x+1] - imapx[x]) * (imapy[y+1] - imapy[y])
        return ans % (10**9 + 7)
```

#### Language used for code

Python

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by FireSlayer57** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code and language you submitted to reach this result.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Hello again,

I've updated the issue description - I simply tried one of the codes from the provided solutions.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please check : https://leetcode.com/submissions/detail/764311042/
