### ISSUE TITLE
973. K Closest Points to Origin | Former solution with detailed article had bee changes

### ISSUE THREAD

**Issue by NodiraIbrogimova** [LeetCode-Feedback/LeetCode-Feedback#8459]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The former solution included 4 approaches with a very well explained Solution article. I stopped at QuickSelect explanation, and in one night I see it has been changed to a Solution article a with very short article with only 2 solutions and missing optimized solution.
It included very neat details of when shall one consider QuickSelect. 
Please, return the former article details. It was much more informative and worth Premium Solution.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted  your feedback to the content team. We appreciate your support!
