### ISSUE TITLE
1071. 字符串的最大公因子

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#846]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
测试案例不全面

**你使用的语言**
python3

**新增测试案例**
`str1  = "aa", str2 = "a"`

**错误代码，但能通过**
```
from math import gcd
class Solution:
    def gcdOfStrings(self, str1: str, str2: str) -> str:
        l1, l2 = len(str1), len(str2)
        l = gcd(l1, l2)
        if l == 1:
            return ""
        s = str1[:l]
        if str1 == s * (l1 // l) and str2 == s * (l2 // l):
            return s
        return ""
```

**期望行为**
错误代码的结果是`""`，但其实依题意应该为`"a"`

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/26211339/90972779-9b10ca00-e54e-11ea-8a8a-b976d0f97b6c.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，该问题已修复，感谢您对力扣网站的支持。

**Comment by Ijustwantyouhappy** [comment]
leetcode ID: 青菜白玉饭汤

**Comment by feiceh** [comment]
好的，贡献奖励已发至 ID：a_run，请查收。

**Comment by Ijustwantyouhappy** [comment]
已收到。
