### ISSUE TITLE
Internal Error - 1598. Crawler Log Folder

### ISSUE THREAD

**Issue by Devvarshney11** [LeetCode-Feedback/LeetCode-Feedback#8463]
#### Your LeetCode username
Devvarshney

#### Category of the bug
- [1] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The code is alright but the compiler give internal error for it please self check the compiler

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minOperations(vector<string>& logs) {
        int count = 0;
        for(string s : logs)
        {
            if(count>0 && s == "../")
            {
                count--;
            }
            else if(s == "./")
            {
                continue;
            }
            else if(isalnum(s[0]))
            {
                count++;
            }
        }
        return count;
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your code to test and it shows Accepted.
https://leetcode.com/submissions/detail/762588391/
We appreciate your support!
