### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by J4cuzz1** [LeetCode-Feedback/LeetCode-Feedback#8464]
#### Your LeetCode username

J4cuzz1

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When i try to assign another list to the list nums1, it will be ignored by the Program. Example in code line 7.

#### Code you used for Submit/Run operation

```
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        if m == 0:
            nums1 = nums2
        elif n == 0:
            nums1 = nums1
        else:
            while nums1[-1] == 0:
                nums1.pop()
            nums1 += nums2
            nums1.sort()
```

#### Language used for code

Python 3

#### Expected behavior
If m is 0 the lists should be swapped.

#### Screenshots

![image](https://user-images.githubusercontent.com/105035752/182152262-db8a4b4a-be58-45be-9154-cab14b66567c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
