### ISSUE TITLE
Missing Test Case - 1092. Shortest Common Supersequence

### ISSUE THREAD

**Issue by hitesh19426** [LeetCode-Feedback/LeetCode-Feedback#8465]
#### Your LeetCode username

hitesh19426

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
Solution

#### Description of the bug

The judge is giving wrong answer on correct output.

#### Code you used for Submit/Run operation

```
class Solution {
    int m, n;
    vector<vector<string>> dp;
    string helper(string &s1, string &s2, int i, int j){
        if(i == 0 && j == 0)
            return "";
        if(!dp[i][j].empty())
            return dp[i][j];
        
        if(i == 0)
            return dp[i][j] = s2.substr(0, j);
        if(j == 0)
            return dp[i][j] = s1.substr(0, i);
        
        if(s1[i] == s2[j]){
            auto before = helper(s1, s2, i-1, j-1);
            before += s1[i-1];
            return dp[i][j] = before;
        }
        
        auto before1 = helper(s1,s2,i-1,j);
        auto before2 = helper(s1,s2,i,j-1);
        
        before1 += s1[i-1];
        before2 += s2[j-1];
        
        if(before1.size() < before2.size())
            return dp[i][j] = before1;
        if(before2.size() < before1.size())
            return dp[i][j] = before2;
        return dp[i][j] = min(before1, before2);
    }
public:
    string shortestCommonSupersequence(string str1, string str2) {
        m = str1.size(), n = str2.size();
        dp.assign(m+1, vector<string>(n+1, ""));
        return helper(str1, str2, m, n);
    }
};
/*
"bbbaaaba"
"bbababbb"
*/
```

#### Language used for code

C++

#### Expected behavior

The issue is that _that_ the test case 11 should pass the test. The output is different from the expected output, but it has same length as expected and contains both strings as subsequence. I have attached the discussion post link regarding the case you want to look at the result.  Here is the [link](https://leetcode.com/problems/shortest-common-supersequence/discuss/2364943/Wrong-answer-or-Help-in-understanding-test-case).

PS: I know my solution is wrong and may not pass further test, that's not an issue. The issue is it should have the mentioned test case 11.

#### Screenshots

![image](https://user-images.githubusercontent.com/55842142/182170236-8e61dfcf-2179-45b5-9439-3c8beeeab7f8.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.

We appreciate your time and support! If you have any other questions, please don't hesitate to let us know.

**Comment by hitesh19426** [comment]
The issue was not even remotely related to the article. The issue is that the question should accept multiple outputs, as mentioned in the question statement. However, as shown in the screenshot, it only accepts a specific answer. The output shown in the screenshot is "one of the' correct answers, however, since it is not matching with the "leetcode" output, the judge is classifying it as wrong answer.

This basically means there is something wrong with testing. It is not checking whether the output is correct or not. It is checking whether the output matches leetcode output or not.
