### ISSUE TITLE
Missing Test Case - 278. First Bad Version

### ISSUE THREAD

**Issue by FireBlaze236** [LeetCode-Feedback/LeetCode-Feedback#8467]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// First Bad Version
// The API isBadVersion is defined for you.
// bool isBadVersion(int version);

class Solution {
public:
    int firstBadVersion(int n) {
        int m = 0;
        while(!isBadVersion(m) && m <= n)
        {
            m++;
        }
        
        return m;
    }
};
```

#### Expected behavior

Expected TLE, but never got TLE. Solution should be O(log n) but here the version being bad is constant, so, bad version detects very early if you iterate from the beginning.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution passed due to some compiler optimizations and can not be failed. We appreciate your support!
