### ISSUE TITLE
题目重复但未备注

### ISSUE THREAD

**Issue by LiangJunrong** [LeetCode-Feedback/LeetCode-Feedback#847]
** Bug 类型**
- [ ] 同一道题 3 个位置重复

**描述**

* 【简单】[110-平衡二叉树](https://leetcode-cn.com/problems/balanced-binary-tree/)
* 【简单】[剑指 Offer 55 - II-平衡二叉树](https://leetcode-cn.com/problems/ping-heng-er-cha-shu-lcof/)
* 【简单】[面试题 04.04-检查平衡性](https://leetcode-cn.com/problems/check-balance-lcci/)

这三道题其实都是一样的。

但是奇怪的是，在 [剑指 Offer 55 - II-平衡二叉树](https://leetcode-cn.com/problems/ping-heng-er-cha-shu-lcof/) 标明了和本站 110 题相同，但是在 [面试题 04.04-检查平衡性](https://leetcode-cn.com/problems/check-balance-lcci/) 中却未标明，且名称也做了变动（实际题目内容不变）

截图小对比如下：

![image](https://user-images.githubusercontent.com/22924993/90980250-d3cf9400-e58c-11ea-803d-410aa266ccbe.png)

![image](https://user-images.githubusercontent.com/22924993/90980264-e5b13700-e58c-11ea-965b-6a3a785f0612.png)

**期望行为**

希望能统一一下名称，并且 [面试题 04.04-检查平衡性](https://leetcode-cn.com/problems/check-balance-lcci/) 备注一下和题库的哪道题是一样的，免得 LeetCode 小伙伴们感觉是不同的题目~

**Comment by feiceh** [comment]
感谢反馈，已转达相关部门，优化内容质量一贯是力扣不遗余力的努力方向，我们会不断努力提升，给大家带来更好的学习社区！

**Comment by feiceh** [comment]
你好，经相关团队确认，LCCI 的题一般不标题目重复，感谢支持力扣。祝您生活愉快。
