### ISSUE TITLE
Wrong testcase - 364 Nested List weight sum || ,

### ISSUE THREAD

**Issue by bo-songxd** [LeetCode-Feedback/LeetCode-Feedback#8471]
#### Your LeetCode username

guanghuaxdd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 1] Missing Test Cases 

#### Description of the bug

final testcase [[1,1],2,[1,1],[[[[]]]]] is not correct.. check your answer!

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
