### ISSUE TITLE
Inadequate difficulty

### ISSUE THREAD

**Issue by dmvo** [LeetCode-Feedback/LeetCode-Feedback#8472]
#### Your LeetCode username

dmvo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This problem is much easier than all other hard ones I tried. Should definitely be medium in my opinion.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
