### ISSUE TITLE
Missing Test Case - 1394. Find Lucky Integer in an Array

### ISSUE THREAD

**Issue by caupcakes** [LeetCode-Feedback/LeetCode-Feedback#8475]
#### Your LeetCode username

hellotestabc

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

None of the test cases actually have 500.
The constraints are
`1 <= arr[i] <= 500`
but you can solve it without considering the existence of 500, since non of the test cases even have it, much less a 500 500s case.

#### Code you used for Submit/Run operation

```
// Find Lucky Integer in an Array
class Solution {
    public int findLucky(int[] arr) {
        int luckynum = -1;

        int[] counts = new int[499]; // valid indexes are 0 -> 498

        for (int i : arr) {
            if (i == 500) { // never executes even though contained in constraints.
                return -100;
            }
            
            counts[i]++;
        }

        for (int index = 1; index < counts.length; index++) {
            if (counts[index] == index) {
                luckynum = index;
            }
        }

        return luckynum;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Solutions like the one above should not be successful.

#### Additional context

Some solutions in the discussion only consider 1 -> 499 which should not have been successful since the edge case, 500 500s, would have caused an error.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've added more large test cases. We appreciate your support!
