### ISSUE TITLE
Missing Test Case - 139. Word Break

### ISSUE THREAD

**Issue by abhishekmishra25** [LeetCode-Feedback/LeetCode-Feedback#8477]
#### Your LeetCode username

ab1533489

#### Category of the bug
- [139 ] Question
- [ ] Solution
- [C++ ] Language
- [ "leetcode"
["leet","leetcode"]] Missing Test Cases 

#### Description of the bug

It should return false for the test case
"leetcode"
["leet","leetcode"]

#### Code you used for Submit/Run operation

```
// Two Sum

class Solution {
public:
    bool wordBreak(string s, vector<string>& wordDict) {
        unordered_set dict(wordDict.begin(),wordDict.end());
        if(dict.size()==0) return false;
        
        vector<bool> dp(s.size()+1,false);
        dp[0]=true;
        
        for(int i=1;i<=s.size();i++)
        {
            for(int j=i-1;j>=0;j--)
            {
                // cout<<dp[j]<<" : "<<j<<endl;
                if(dp[j])
                {
                    string word = s.substr(j,i-j);
                    
                    if(dict.find(word)!= dict.end())
                    {
                        // cout<<i<<" "<<j<<" : ";
                        // cout<<word<<endl;
                        dp[i]=true;
                        break; //next i
                    }
                }
            }
        }
        // for(int i=0;i<dp.size();i++)
        //     cout<<dp[i]<<" ";
        // cout<<endl;
        
        return dp[s.size()];
        
    }
};
```

#### Expected behavior

it supposed to give false since it can't be space seprated

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
