### ISSUE TITLE
Space Complexity mentioned in Solution wrong.

### ISSUE THREAD

**Issue by vaibhavranjith** [LeetCode-Feedback/LeetCode-Feedback#8478]
#### Your LeetCode username

WaxCree

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

Solution
#### Description of the bug

The Space complexity of the dynamic programming solution is given as O(1). We are initialising a matrix of size n*m. So  space complexity is actually O(n.m)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
