### ISSUE TITLE
Test Case Answer Wrong - 845. Longest Mountain in Array

### ISSUE THREAD

**Issue by nsabir2011** [LeetCode-Feedback/LeetCode-Feedback#8483]
#### Your LeetCode username

nsabir2011

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

According to the question the rules are:
- arr.length >= 3
- There exists some index i (0-indexed) with 0 < i < arr.length - 1 such that:
   - arr[0] < arr[1] < ... < arr[i - 1] < arr[i]
   - arr[i] > arr[i + 1] > ... > arr[arr.length - 1]

So, the answer to the test case ```[0,2,0,2,1,2,3,4,4,1]``` should be ```3``` if I understand correctly, not ```4```. Which is the expected answer.
Since the question does not state ```arr[i] >= arr[i + 1]``` I think the sequence ```[1,2,3,4]``` should not be counted as a mountain.
Also, for the array ```[0,1,2,3,4,5,6,7,8,9]``` the solution is ```0``` which supports my claim I think.
Therfore, I think either there is a problem with the quetion or the solution. Or with my understanding (Most likely). Please clear up my confusion if possible.

#### Language used for code

Python3

#### Expected behavior

```[0,1,2,3,4,5,6,7,8,9]``` -> ```0```
```[0,2,0,2,1,2,3,4,4,1]``` -> ```3```
```[1,2,3,3,4,5,3]``` -> ```4```

**Comment by stormsunshine** [comment]
These test cases' answers are the same as you expected. What is the problem?

**Comment by nsabir2011** [comment]
> These test cases' answers are the same as you expected. What is the problem?

My problem is with the input ```[0,2,0,2,1,2,3,4,4,1]```. The expected answer is 4 as of now. But I think it should be 3. Sorry for describing it poorly.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by nsabir2011** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code and language you submitted to reach this result.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Sure. I used Python3 to solve the question. Here's my code:
```
class Solution:
    def longestMountain(self, arr: List[int]) -> int:
        n = len(arr)
        if n < 3:
            return 0
        
        i = 1
        prev_num = arr[0]
        inside_lm = False
        lm_len = 0
        max_lm_len = 0
        check_lm_len = False
        climb_up = False
        climb_down = False
        while i < n:
            num = arr[i]
            if not inside_lm and num > prev_num:
                lm_len += 1
                inside_lm = True
                climb_up = True
            elif climb_up and num > prev_num:
                lm_len += 1
            elif climb_up and num < prev_num:
                lm_len += 1
                climb_up = False
                climb_down = True
            elif climb_down and num < prev_num:
                lm_len += 1
            elif (climb_down and num > prev_num) \
                or (num == prev_num):
                climb_up = False
                climb_down = False
                inside_lm = False
                check_lm_len = True
                lm_len += 1

            if check_lm_len or i+1 == n:

                if i+1 == n and climb_down:
                    lm_len += 1
                if i+1 == n and climb_up:
                    lm_len = 0

                if lm_len > 2:
                    max_lm_len = max(max_lm_len, lm_len)
                check_lm_len = False
                lm_len = 0
            
            if not inside_lm and num > prev_num:
                lm_len += 1
                inside_lm = True
                climb_up = True

            prev_num = num
            i += 1
        
        return max_lm_len
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
