### ISSUE TITLE
Please do not close issues without any response.

### ISSUE THREAD

**Issue by LC-please-reply** [LeetCode-Feedback/LeetCode-Feedback#8484]
You previously closed https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8069, and said you have relayed this issue to your Zendesk Support team. But they still haven't replied.

You previously closed https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8443 without any response.

Can you provide a workable channel to contact LeetCode team?

**Comment by LC-Pam** [comment]
Please contact with Zendesk customer support team, your issue already passed to them. Github is only for the content/solution related issue, please understand. We appreciate!

**Comment by LC-please-reply** [comment]
@LC-Pam Thank you for your reply. But the problem is Zendesk customer support team never replies. I really want to understand, but I do not understand how to contact them.

**Comment by LC-please-reply** [comment]
@LC-Pam Can you provide a workable channel to contact LeetCode team?

**Comment by LC-please-reply** [comment]
@LC-Pam It's bee over two months since https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8069. Your Zendesk customer support team never replied. Can you provide a workable channel to contact LeetCode team?
