### ISSUE TITLE
Solution not accepted - 108. Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by danandreicarp** [LeetCode-Feedback/LeetCode-Feedback#8486]
#### Your LeetCode username
carpdan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I've been working on an iterative solution, but my generated binary tree isn't accepted. For example, for input [0,1,2,3,4,5,6,7] my output is [4,0,7,null,2,5,null,1,3,null,6], which is a binary tree, as far as I know. However, the test doesn't pass. Can you help me understand why?

#### Code you used for Submit/Run operation

```java
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
class Solution {
static class TreeNodeWithIndex extends TreeNode {
        int index;

        public TreeNodeWithIndex(int val, int index) {
            super(val);
            this.index = index;
        }
    }
    
    public TreeNode sortedArrayToBST(int[] nums) {
        return makeTreeIter(nums);
    }
    
    private TreeNode makeTreeIter(int[] nums) {
        if (nums.length == 0) return null;
        
        int depth = calculateTreeDepth(nums);

        Deque<TreeNodeWithIndex> queue = new LinkedList<>();
        Deque<TreeNodeWithIndex> level = new LinkedList<>();
        int middle = (int) Math.floor(nums.length / 2.0);
        TreeNodeWithIndex root = new TreeNodeWithIndex(nums[middle], middle);
        nums[middle] = Integer.MIN_VALUE;
        TreeNodeWithIndex node = root;
        
        level.add(node);
        depth--;
        while (depth >= 0 && !level.isEmpty()) {
            node = level.pop();
            addChildNodes(nums, depth, queue, node);
            if (level.isEmpty()) {
                --depth;
                level = queue;
                queue = new LinkedList<>();
            }
        }

        return root;
    }

    private int calculateTreeDepth(int[] nums) {
        int depth = -1;
        int length = nums.length;
        while (length > 0) {
            length = length / 2;
            depth++;
        }
        return depth;
    }

    private void addChildNodes(int[] nums, int depth, Deque<TreeNodeWithIndex> queue, TreeNodeWithIndex node) {
        int leftIndex = node.index - (int) Math.pow(2, depth);
        if (leftIndex >= 0 && nums[leftIndex] != Integer.MIN_VALUE) {
            node.left = new TreeNodeWithIndex(nums[leftIndex], leftIndex);
            nums[leftIndex] = Integer.MIN_VALUE;
            queue.add((TreeNodeWithIndex) node.left);
        }
        int rightIndex = node.index + (int) Math.pow(2, depth);
        if (rightIndex == nums.length) {
            rightIndex = rightIndex - 1;
        }
        if (rightIndex < nums.length && nums[rightIndex] != Integer.MIN_VALUE) {
            node.right = new TreeNodeWithIndex(nums[rightIndex], rightIndex);
            nums[rightIndex] = Integer.MIN_VALUE;
            queue.add((TreeNodeWithIndex) node.right);
        }
    }    
```

#### Language used for code
Java

#### Expected behavior
For input `[0,1,2,3,4,5,6,7]`, I would expect `[4,0,7,null,2,5,null,1,3,null,6]` to be accepted as a solution.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, your code received Compile Error when we tested it.  Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by danandreicarp** [comment]
Hello,

I forgot a closing brace, unfortunately. Here is the complete code:

```java
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
class Solution {
    static class TreeNodeWithIndex extends TreeNode {
        int index;

        public TreeNodeWithIndex(int val, int index) {
            super(val);
            this.index = index;
        }
    }
    
    public TreeNode sortedArrayToBST(int[] nums) {
        return makeTreeIter(nums);
    }
    
    private TreeNode makeTreeIter(int[] nums) {
        if (nums.length == 0) return null;
        
        int depth = calculateTreeDepth(nums);

        Deque<TreeNodeWithIndex> queue = new LinkedList<>();
        Deque<TreeNodeWithIndex> level = new LinkedList<>();
        int middle = (int) Math.floor(nums.length / 2.0);
        TreeNodeWithIndex root = new TreeNodeWithIndex(nums[middle], middle);
        nums[middle] = Integer.MIN_VALUE;
        TreeNodeWithIndex node = root;
        
        level.add(node);
        depth--;
        while (depth >= 0 && !level.isEmpty()) {
            node = level.pop();
            addChildNodes(nums, depth, queue, node);
            if (level.isEmpty()) {
                --depth;
                level = queue;
                queue = new LinkedList<>();
            }
        }

        return root;
    }

    private int calculateTreeDepth(int[] nums) {
        int depth = -1;
        int length = nums.length;
        while (length > 0) {
            length = length / 2;
            depth++;
        }
        return depth;
    }

    private void addChildNodes(int[] nums, int depth, Deque<TreeNodeWithIndex> queue, TreeNodeWithIndex node) {
        int leftIndex = node.index - (int) Math.pow(2, depth);
        if (leftIndex >= 0 && nums[leftIndex] != Integer.MIN_VALUE) {
            node.left = new TreeNodeWithIndex(nums[leftIndex], leftIndex);
            nums[leftIndex] = Integer.MIN_VALUE;
            queue.add((TreeNodeWithIndex) node.left);
        }
        int rightIndex = node.index + (int) Math.pow(2, depth);
        if (rightIndex == nums.length) {
            rightIndex = rightIndex - 1;
        }
        if (rightIndex < nums.length && nums[rightIndex] != Integer.MIN_VALUE) {
            node.right = new TreeNodeWithIndex(nums[rightIndex], rightIndex);
            nums[rightIndex] = Integer.MIN_VALUE;
            queue.add((TreeNodeWithIndex) node.right);
        }
    }    
}
```

Not sure why you're saying that the Judger is working correctly if you didn't actually run the code. 
Please take a proper look at this.

If required, here's a link to the submission page that shows both the code and the input/output: https://leetcode.com/submissions/detail/763764254/

Thank you!

**Comment by LC-Pam** [comment]
Thank you for your time. The code that you provided above received Wrong Answer when we test it, please check: https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/discuss/35440/Iterative-Java-Solution-Using-Stack to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

**Comment by danandreicarp** [comment]
Hello,

This is frustrating. You keep closing the issue without waiting for a reply.

I'm pasting below your response, to comment on it:

> Thank you for your time. The code that you provided above received Wrong Answer when we test it, please check: https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/discuss/35440/Iterative-Java-Solution-Using-Stack to see how other users' have optimized their codes!
>
> When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I know that it gives a "Wrong Answer", that's why I contacted you in the first place. I don't think checking other solutions makes sense for this case because I'm reporting a situation where the response my code gives is a binary tree, as requested by the problem statement, but is not accepted.

There are many​ ways to create a binary tree and, as far as I know, the response I'm providing is one. Do correct me if I'm wrong. See "Example 1" in the problem statement. It gives two accepted answers.

Also, it's not the case for the test passing individually and failing after submission. It always fails.

What I would expect from you is this:

- confirm that the response my solution gives is a binary tree.
- confirm that the Judge should accept it as a valid solution
- update the Judge so that it does that

If "1" is false, then we can resolve this ticket and conclude that this isn't a bug.

Thank you,
Dan

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by danandreicarp** [comment]
Any updates?

Thanks!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
