### ISSUE TITLE
Missing Test Case - 2359. Find Closest Node to Given Two Nodes

### ISSUE THREAD

**Issue by leogeor** [LeetCode-Feedback/LeetCode-Feedback#8487]
#### Your LeetCode username

liziqiao0425

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√ ] Missing Test Cases 

#### Description of the bug

For the test case [4,4,4,8,-1,9,8,4,4,1,1]
                            5
                            6
The correct result should be 4 instead of 1. 
#### Code you used for Submit/Run operation

```
// Find Closest Node To Given Two Nodes
class Solution {
    public int closestMeetingNode(int[] edges, int node1, int node2) {
        int minIndex = 0;
        int curIndex = 1;
        int[] step1 = new int[edges.length];
        for(int i = 0; i < edges.length; i++) {
            step1[i] = -1;
        }
        int[] step2 = new int[edges.length];
        for(int i = 0; i < edges.length; i++) {
            step2[i] = -1;
        }
        int[] res = new int[edges.length];
        int[] cnt = new int[]{0};
        for(int i = 0; i < res.length; i++) {
            res[i] = Integer.MAX_VALUE;
        }
        helper(node1, edges, step1, cnt);
        cnt[0] = 0;
        helper(node2, edges, step2, cnt);
        cnt[0] = 0;
        for(int i = 0; i < edges.length; i++) {
            if(step1[i] != -1 && step2[i] != -1) {
                res[i] = step1[i] + step2[i];
            }
        }
        while(curIndex < res.length) {
            if(res[curIndex] < res[minIndex]) {
                minIndex = curIndex;
            }
                curIndex++;
            }
        if(res[minIndex] == Integer.MAX_VALUE) return -1;
        return minIndex;
    }
    private void helper(int node, int[] edges, int[] step, int[] cnt) {
        if(cnt[0] == edges.length) return;
        if(edges[node] == -1) {
            step[node] = cnt[0];
            cnt[0] = 0;
            return;
        }else {
             if(step[node] == -1) {
                step[node] = cnt[0];
            }else{
                return;
            }
            cnt[0]++;
            helper(edges[node], edges, step, cnt);
        }
    }
}
```

#### Expected behavior

For the case writing above, for node 1,the total distance of node1 plus node2 is 5, and for node 4, the total distance is 4,which is obviously smaller. So I think this test case is wrong. 

#### Screenshots

![20220803132929](https://user-images.githubusercontent.com/109454500/182531148-7a706032-a6fe-48d7-93dd-02bd19616fe3.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by leogeor** [comment]
The  language I used in the submitted code  is java

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: LC_M ***@***.***>
发送时间: Thursday, August 4, 2022 1:01:36 AM
收件人: LeetCode-Feedback/LeetCode-Feedback ***@***.***>
抄送: leogeor ***@***.***>; Author ***@***.***>
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 2359. Find Closest Node to Given Two Nodes (Issue #8487)


Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

―

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by mhdshameel** [comment]
I came for mentioning the same. 
```
For the test case [4,4,4,8,-1,9,8,4,4,1,1]
5
6
```
The correct result should be 4 instead of 1.
Distance to 4:
From 5, the distance to 4 is 3. And from 6, the distance to 4 is 1. The total distance is 4.

Distance to 1:
From 5, the distance to 1 is 2. And from 6, the distance to 1 is 3. The total distance is 5.
Hence 4 is the closest node to 5 and 6.

Following is the code I used in c++:
```
/*
    method to identify the nodes that can be reached from the given node and their distances
    */
    void chainAndDistance(vector<int>& edges, int node, map<int,int> &mp)
    {
        int t = node;
        vector<bool> visited(edges.size());
        
        //add self initially
        mp[t] = 0;
        visited[t] = true;
        for(int i = 1; edges[t] != -1; i++)
        {
            if(visited[edges[t]] == true) break;
            visited[edges[t]] = true;
            mp[edges[t]] = i;
            t = edges[t];
        }
    }
    
    int closestMeetingNode(vector<int>& edges, int node1, int node2) {
        
        map<int,int> node1_mp, node2_mp;
        chainAndDistance(edges, node1, node1_mp);
        chainAndDistance(edges, node2, node2_mp);
        
        map<int,int> common;
        for(auto it: node1_mp)
        {
            if(node2_mp.find(it.first) != node2_mp.end())
            {
                common[it.first] = it.second + node2_mp[it.first];
            }
        }
        
        int min = INT_MAX, min_elem;
        for(auto it: common)
        {
            cout << it.first << ", " << it.second << endl;
            if(min > it.second)
            {
                min = it.second;
                min_elem = it.first;
            }
        }
        
        return min == INT_MAX ? -1 : min_elem;
    }
```

My [submission](https://leetcode.com/submissions/detail/788126275/).

**Comment by viveksondhiya** [comment]
//java
class Solution {
    public int closestMeetingNode(int[] edges, int node1, int node2) {
       int minIndex = 0;
        int curIndex = 1;
        int[] step1 = new int[edges.length];
        for(int i = 0; i < edges.length; i++) {
            step1[i] = -1;
        }
        int[] step2 = new int[edges.length];
        for(int i = 0; i < edges.length; i++) {
            step2[i] = -1;
        }
        int[] res = new int[edges.length];
        int[] cnt = new int[]{0};
        for(int i = 0; i < res.length; i++) {
            res[i] = Integer.MAX_VALUE;
        }
        helper(node1, edges, step1, cnt);
        cnt[0] = 0;
        helper(node2, edges, step2, cnt);
        cnt[0] = 0;
        for(int i = 0; i < edges.length; i++) {
            if(step1[i] != -1 && step2[i] != -1) {
                res[i] = step1[i] + step2[i];
            }
        }
        while(curIndex < res.length) {
            if(res[curIndex] < res[minIndex]) {
                minIndex = curIndex;
            }
                curIndex++;
            }
        if(res[minIndex] == Integer.MAX_VALUE) return -1;
        return minIndex;
    }
    private void helper(int node, int[] edges, int[] step, int[] cnt) {
        if(cnt[0] == edges.length) return;
        if(edges[node] == -1) {
            step[node] = cnt[0];
            cnt[0] = 0;
            return;
        }else {
             if(step[node] == -1) {
                step[node] = cnt[0];
            }else{
                return;
            }
            cnt[0]++;
            helper(edges[node], edges, step, cnt);
        }
    }
}

**Comment by gautambhetanabhotla** [comment]
This testcase still has the wrong answer as of May 30, 2025. Please fix it.
