### ISSUE TITLE
Wrong code vs description for Approach2 in Solution of non-overlapping-intervals

### ISSUE THREAD

**Issue by chetnashah** [LeetCode-Feedback/LeetCode-Feedback#8489]
#### Your LeetCode username
jay17

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/non-overlapping-intervals/

Approach No. 2 says sort by start time, but code contains sort by end time

#### Language used for code
Java

#### Expected behavior

Code in Approach2 should be updated to use sort by start time instead of end time.

#### Screenshots

![leetcodebug1](https://user-images.githubusercontent.com/22337772/182584492-47134764-df92-43cf-b3b3-e02a3a2f3dc0.PNG)
![leetcodebug2](https://user-images.githubusercontent.com/22337772/182584498-0e4f4595-a8c5-480e-b360-79822c1f44d5.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
