### ISSUE TITLE
解析答案有问题

### ISSUE THREAD

**Issue by Oliverwqcwrw** [LeetCode-Feedback/LeetCode-Feedback#849]
** 解析答案有问题**
- [ ] 平衡二叉树
- [ ] 求出左右子树的高度，然后相减求绝对值，如果小于2则为true，否则为false
- [ ] Java

**描述**
我把官方解析提示解答错误的测试入参输入到测试用例，然后执行输出的结果与预期的结果是一样的，但是提交就显示与预期的不一样，请问这是为什么呢

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public static boolean isBalanced(TreeNode root) {
        if (Math.abs(getLeft(root) - getRight(root)) < 2) {
            return true;
        }

        return false;
    }
   static int num1 = 0;
    public static int getLeft(TreeNode root) {
        if (root != null) {
            num1++;
        } else {
            return num1;
        }
        return getLeft(root.left);
    }
    static int num2 = 0;
    public static int getRight(TreeNode root) {
        if (root != null) {
            num2++;
        } else {
            return num2;
        }
        return getRight(root.right);
    }
}
```

**期望行为**
期望运行结果与预期结果一样，也就是false

**屏幕截图**
![image](https://user-images.githubusercontent.com/31796988/91002914-64948700-e602-11ea-80c7-b8bdba696cdf.png)

![image](https://user-images.githubusercontent.com/31796988/91002925-6fe7b280-e602-11ea-9965-3bd1776754c3.png)

**额外的上下文**
希望可以帮忙看一下这个问题，是我程序有问题还是您这个解析有问题，跪谢！！

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。 后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至  [力扣圈子](https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=)  进行题目交流，以获得更好的支持哟～
