### ISSUE TITLE
Please Do Not Use 'Hard' Mark Without Considering !!

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#8490]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
![hard](https://user-images.githubusercontent.com/73991126/182612435-34cb983c-82f0-4b1f-8e17-253e4675cb0f.png)

These are recent problems which have been marked as 'Hard'.
In fact, the problem 2344 and 2361 should be marked as 'Easy'.
The difficulty of the problem 2301, 2302, 2307, 2321, 2328 and 2360 is suitable for the second problem of a weekly contest.
The difficulty of the problem 2296, 2313, 2318, 2350 and 2354 is suitable for the third problem of a weekly contest.
Only the problem 2306, 2322, 2338 and 2355 are challenging for most users of LeetCode, and it is OK to use 'hard' mark to the problem 2312 and 2334.
Besides, the problem 2296 should be a 'Easy' problem for users who use Python3, Java or Javascript.

I know LeetCode is designed for interviewers, not competitors of algorithm contest. But it does not mean that the problem of the LeetCode should be as easy as possible. If a beginner of data structure and algorithm can solve 'Hard' problem, the difficulty mark will be meaningless. On the other hand, the beginner who solve the easy problem with 'Hard' mark can possible overestimate his ability of data structure and algorithm.

I think the 'Hard' mark should be used more carefully in the future.

Expected behavior
1. The 'Hard' mark can be used more carefully in the future.
2. The difficulty mark 'Hard' of some current problems should be adjusted.
3. The problem 2307 should be removed from the LeetCode permanently(I believe you know why I can say this).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team and we already investigated on this issue.
Deciding the difficulty of the problem before publishing it goes through a process.
After publishing the problem, we may increase/decrease its difficulty through another process.
We appreciate your support!
