### ISSUE TITLE
Solution Enhancement - 729. My Calendar I

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#8493]
#### Your LeetCode username
[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Many LC problems have a "[Solution](https://leetcode.com/problems/my-calendar-i/solution/)" tab with code in C++, Java, and Python. This problem only has code in Java and Python. I would like to contribute C++ code to the "Solution" tab.

#### Code you used for Submit/Run operation

[Approach 1: Brute Force](https://leetcode.com/submissions/detail/764194876/)

```cpp
class MyCalendar {
  public:
    bool book(int start, int end) {
      for (const auto event : events) {
        if (start < event.second && event.first < end) {
          return false;
        }
      }

      events.emplace_back(start, end);
      return true;
    }

  private:
    vector<pair<int, int>> events;
};
```

[Approach 2: Balanced Tree](https://leetcode.com/submissions/detail/764193105/)

```cpp
class MyCalendar {
  public:
    bool book(int start, int end) {
      const pair<int, int> event{start, end};
      const auto next_event = events.lower_bound(event);
      if (next_event != events.end() && next_event->first < end) {
        return false;
      }

      if (next_event != events.begin()) {
        const auto prev_event = prev(next_event);
        if (prev_event->second > start) {
          return false;
        }
      }

      events.insert(event);
      return true;
    }

  private:
    set<pair<int, int>> events;
};
```

#### Language used for code
C++

#### Expected behavior
"Solution" tab has code in C++.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by nskybytskyi** [comment]
Good job on your side spotting structured bindings, I somehow completely forgot about it.
