### ISSUE TITLE
kotlin语言 剑指 Offer II 023道题目 没通过-怀疑kotin语言环境有问题

### ISSUE THREAD

**Issue by yaowen369** [LeetCode-Feedback/LeetCode-Feedback#8494]
**你的 LeetCode 用户名**
yaoxiaowen

**Bug 类型**
- [ ] 题目 : 剑指 Offer II 023. 两个链表的第一个重合节点

**描述**
kotlin语言 测试case不通过
具体的测试case是:

0
[2,6,4]
[1,5]
3
2

**你使用的语言**
kotlin

**你提交或者运行的代码**
```
class Solution {
    fun getIntersectionNode(headA:ListNode?, headB:ListNode?):ListNode? {
        headA ?: return null
        headB ?: return null

        var pa:ListNode? = headA
        var pb:ListNode? = headB

        while (pa != pb) {
           pa = pa?.let { it.next }  ?:  headB
           pb = pb?.let { it.next  } ?:  headA
        }

        return pa
    }
}
```

**期望行为**
所有case都通过

**屏幕截图**
无

**额外的上下文**
kotlin的编译环境貌似有问题，导致语法解析有问题

**Comment by feiceh** [comment]
代码问题，死循环了,改成下面这样
class Solution {
    fun getIntersectionNode(headA:ListNode?, headB:ListNode?):ListNode? {
        headA ?: return null
        headB ?: return null

        var pa:ListNode? = headA
        var pb:ListNode? = headB

        while (pa != pb) {
           pa = if(pa==null) headA else pa?.let { it.next }
           pb = if(pb==null) headB else pb?.let { it.next }
        }
        return pa
    }
}
