### ISSUE TITLE
Missing Test Case - 1944. Number of Visible People in a Queue

### ISSUE THREAD

**Issue by ThreeQuarterCoder** [LeetCode-Feedback/LeetCode-Feedback#8496]
#### Your LeetCode username

user6803M
https://leetcode.com/user6803M/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This problem has no Solution. Providing a solution in Java

#### Code you used for Submit/Run operation

```
class Solution { 
    public int[] canSeePersonsCount(int[] heights) {
        int[] result = new int[heights.length];
        
        if(heights.length >= 2) {
            java.util.Stack<Integer> stack = new java.util.Stack<Integer>();
            stack.push(heights[heights.length - 1]);
            
            int i = heights.length - 2;
            
            while(i >= 0) {
                while(!stack.isEmpty() && heights[i] > stack.peek()) {
                    result[i]++;
                    stack.pop();
                }
                if(!stack.isEmpty()) {
                    result[i]++;
                }
                stack.push(heights[i]);
                i--;
            }
        }
        
        return result;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The Solution tab should contain a Java Solution as mentioned above

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
