### ISSUE TITLE
Go supports imports from third-party package (GODS)

### ISSUE THREAD

**Issue by sebnyberg** [LeetCode-Feedback/LeetCode-Feedback#8498]
#### Your LeetCode username

https://leetcode.com/sebnyberg/

#### Category of the bug

- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Go supports third-party package imports from https://github.com/emirpasic/gods.

As far as I know, this is not acceptable for interviews or contests and is not allowed in other languages.

#### Code you used for Submit/Run operation

For example:

```go
func twoSum(nums []int, target int) []int {
	m := hashmap.New()
	m.Put(1, "x")
	m.Get(1)
	return nil
}
```

#### Language used for code

Go.

#### Expected behavior

The code above should fail.

**Comment by sebnyberg** [comment]
FWIW I have seen people importing a red-black tree into contest submissions before, but I assumed that the person had implemented it elsewhere locally and that the Leetcode editor didn't pick it up.

Most recently I saw its use in this discussion post:
ttps://leetcode.com/problems/design-a-number-container-system/discuss/2326829/Golang-simple-RedBlackTree-solution

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!

**Comment by sebnyberg** [comment]
What's the status of this?

It doesn't make sense that people should learn a third-party module to be competitive on Leetcode.

**Comment by sebnyberg** [comment]
@LC-Pam What does it mean that this was submitted? Is there any way for the community to track progress of these kinds of items? It feels like tossing suggestions into a black hole.

**Comment by sebnyberg** [comment]
@LC-Pam Can you explain to me what the status is of this ticket? It was closed with no information. Is it acceptable for Leetcode members to use third-party libraries in their solutions, when other languages do not have access to such libraries?
