### ISSUE TITLE
解析答案有问题，本来测试用例运行ok，提交之后提示解答错误，what

### ISSUE THREAD

**Issue by Oliverwqcwrw** [LeetCode-Feedback/LeetCode-Feedback#850]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言

**描述**

本来测试用例运行ok，提交之后提示解答错误，what
**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public static int minDepth(TreeNode root) {
        int left = getLeft(root);
        int right = getRight(root);
        if (left < right) {
            return left;
        } else {
            return right;
        }
    }

   static int num1 = 0;
    public static int getLeft(TreeNode root) {
        if (root != null) {
            num1++;
        } else {
            return num1;
        }
        return getLeft(root.left);
    }
    static int num2 = 0;
    public static int getRight(TreeNode root) {
        if (root != null) {
            num2++;
        } else {
            return num2;
        }
        return getRight(root.right);
    }
}
```

**期望行为**
期望执行结果与预期结果相同

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/31796988/91003764-c35b0000-e604-11ea-85c1-05ce98ea6113.png)

![image](https://user-images.githubusercontent.com/31796988/91003777-ce159500-e604-11ea-9908-28eaad1ea8e2.png)

**额外的上下文**
希望可以帮忙早点告知一下这是什么问题，每次做到关于二叉树的就会出现问题，我都不敢做关于二叉树的题目了  /捂脸

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。 后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至  [力扣圈子](https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=)  进行题目交流，以获得更好的支持哟～

**Comment by Oliverwqcwrw** [comment]
有点失望，就想知道你们为什么测试用例运行的结果与提交之后解析的不一样，结果你让我调试代码，还扔给我一个请求400的链接 ，就这么敷衍吗，哈哈，太逗了，你们

**Comment by feiceh** [comment]
链接打开没有问题啊，推荐阅读：**「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://support.leetcode-cn.com/hc/kb/article/1194344/)」**

**Comment by Oliverwqcwrw** [comment]
现在这个链接可以看到了，之前那个链接访问400
