### ISSUE TITLE
Example Typo in `Rectangular Area II`

### ISSUE THREAD

**Issue by sam20908** [LeetCode-Feedback/LeetCode-Feedback#8501]
#### Your LeetCode username

SajLeet

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There's a typo in the text within the first example.

#### Expected behavior

The word `rectangales` should be `rectangles`.

#### Screenshots

![Untitled](https://user-images.githubusercontent.com/18388795/182699183-5f8429db-c464-489d-8ce7-24a6c04eed80.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
