### ISSUE TITLE
Explore card - Sorting - Insertion sort - selection answer issue

### ISSUE THREAD

**Issue by code-n-roll** [LeetCode-Feedback/LeetCode-Feedback#8503]
#### Your LeetCode username

romankaranchuk

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Multiple choice question is working as single choice question which leads to wrong answer. 
https://leetcode.com/explore/learn/card/sorting/694/comparison-based-sorts/4435/

#### Expected behavior

Multiple choice is available.

#### Screenshots

![image](https://user-images.githubusercontent.com/11900227/182713338-a5c8931d-300d-41c1-b2ec-a33507d4b821.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
