### ISSUE TITLE
Explore card - Sorting - Heap sort - text layout is broken

### ISSUE THREAD

**Issue by code-n-roll** [LeetCode-Feedback/LeetCode-Feedback#8504]
#### Your LeetCode username

romankaranchuk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Content

#### Description of the bug

Some parts of text has broken formatting, see screenshots for details.
https://leetcode.com/explore/learn/card/sorting/694/comparison-based-sorts/4436/

#### Expected behavior

Text is properly formatted i.e. 
1. unknown symbols are absent
2. ordered list is aligned in one column where each item is on the new line
3. item with number 3 is exist

#### Screenshots

![image](https://user-images.githubusercontent.com/11900227/182719888-9de1796d-fa0d-4a3e-8e6c-b96c3035db50.png)
![image](https://user-images.githubusercontent.com/11900227/182719086-5772fb8e-5b8a-4375-a15d-538ced85be17.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
