### ISSUE TITLE
Explore card - Sorting - Counting sort - text layout is broken

### ISSUE THREAD

**Issue by code-n-roll** [LeetCode-Feedback/LeetCode-Feedback#8505]
#### Your LeetCode username

romankaranchuk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Content

#### Description of the bug

Some parts of text layout is broken.
https://leetcode.com/explore/learn/card/sorting/695/non-comparison-based-sorts/4437/

#### Expected behavior

Text layout is properly formatted i.e:
1. unknown symbols are absent
2. ordered list is aligned in one column each item is on new line

#### Screenshots

Align ordered list:
![image](https://user-images.githubusercontent.com/11900227/182723034-342eef6b-5d04-4aed-9f82-850c55c45737.png)
Unknown symbols:
![image](https://user-images.githubusercontent.com/11900227/182723214-07793a79-e51d-4f66-bd99-1c35264086d7.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
