### ISSUE TITLE
Explore card - Sorting - Bucket sort - text layout is broken

### ISSUE THREAD

**Issue by code-n-roll** [LeetCode-Feedback/LeetCode-Feedback#8506]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Content

#### Description of the bug

Some part of text layout is broken
https://leetcode.com/explore/learn/card/sorting/695/non-comparison-based-sorts/4439/

#### Expected behavior

Text layout is properly formatted i.e:
1. unknown symbols are absent
2. ordered list is aligned in one column each item on the new line

#### Screenshots

Text is aligned:
![image](https://user-images.githubusercontent.com/11900227/182725420-af79a7e9-656c-44ac-8083-f4d94842bb0e.png)
Unknown symbols are absent:
![image](https://user-images.githubusercontent.com/11900227/182725495-d3bf2c7d-b3a3-4823-96d7-8952f4cc4d1a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
