### ISSUE TITLE
Missing Dart language - 1480. Running Sum of 1d Array

### ISSUE THREAD

**Issue by pattobrien** [LeetCode-Feedback/LeetCode-Feedback#8507]
#### Your LeetCode username
pattobrien

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
This problem is missing the Dart language.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!

**Comment by TinhHuynh** [comment]
The problem is still missing Dart language.
