### ISSUE TITLE
185. 部门工资前三高的所有员工

### ISSUE THREAD

**Issue by DamengLiu** [LeetCode-Feedback/LeetCode-Feedback#8509]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
白露塞纳

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
本地与提交执行结果不一致，提交后服务器端的的预期结果也不对。

**你提交或者运行的代码**
```
SELECT t3.Name Department, t2.Name Employee, t2.Salary
FROM 
(## 自定义变量RANK, 查找出 每个部门工资前三的排名
    SELECT 
        t1.name
        , t1.Salary
        , t1.DepartmentId
        , CASE 
            WHEN @pre = DepartmentId THEN @rank:= @rank + 1
            WHEN @pre := DepartmentId THEN @rank:= 1
        END AS RNK
    FROM (## (部门,薪水)去重,根据 部门(升),薪水(降) 排序
        SELECT DepartmentId, Salary, name
        FROM Employee
        GROUP BY DepartmentId,Salary
        ORDER BY DepartmentId,Salary DESC
    ) as t1, (SELECT @pre:=null, @rank:=0) as init
) as t2
INNER JOIN Department as t3 ON t2.DepartmentId = t3.Id
# INNER JOIN Employee as t4 ON t2.DepartmentId = t4.DepartmentId and t2.Salary = t4.Salary 
where t2.RNK <= 3
ORDER BY t2.DepartmentId, t2.Salary DESC ## t 结果集已有序,根据该集合排序
```

**期望行为**
描述你期望的结果

**屏幕截图**

![22](https://user-images.githubusercontent.com/39763537/182740638-38a10614-ed2a-4ff4-b3e7-19dbd6cc8bd1.jpg)

**Comment by BrambleWave** [comment]
经比对是完全一致的，预期结果里面有空格，把空格删掉就对了。

**Comment by DamengLiu** [comment]
本地的预期结果与提交后的预期结果不一致，本地的预期结果中多了一条记录 ["IT", "Randy", 85000].

**Comment by BrambleWave** [comment]
// 提交错误用例的预期结果
{"headers":["Department","Employee","Salary"],"values":[["IT","Joe",85000],["Sales","Henry",80000],["Sales","Sam",60000],["IT","Max",90000],["IT","Randy",85000],["IT","Will",70000]]}

// 执行代码显示的预期结果
{"headers": ["Department", "Employee", "Salary"], "values": [["IT", "Joe", 85000], ["Sales", "Henry", 80000], ["Sales", "Sam", 60000], ["IT", "Max", 90000], ["IT", "Randy", 85000], ["IT", "Will", 70000]]}
=> 删掉空格
{"headers":["Department","Employee","Salary"],"values":[["IT","Joe",85000],["Sales","Henry",80000],["Sales","Sam",60000],["IT","Max",90000],["IT","Randy",85000],["IT","Will",70000]]}

// 用户代码执行结果

// 提交错误用例的用户查询结果
{"headers":["Department","Employee","Salary"],"values":[["IT","Max",90000],["IT","Joe",85000],["IT","Will",70000],["Sales","Henry",80000],["Sales","Sam",60000]]}
// 执行代码显示的用户查询结果
{"headers": ["Department", "Employee", "Salary"], "values": [["IT", "Max", 90000], ["IT", "Joe", 85000], ["IT", "Will", 70000], ["Sales", "Henry", 80000], ["Sales", "Sam", 60000]]}

// 用户代码问题在于， 题面中定义了 「一个部门的 高收入者 是指一个员工的工资在该部门的 不同 工资中 排名前三 。」 因此需要包含 ["IT","Randy",85000]

**Comment by DamengLiu** [comment]
![4](https://user-images.githubusercontent.com/39763537/184041650-637e6940-e620-416e-87e9-f0581f5fd2dd.jpg)
