### ISSUE TITLE
leetcode 154

### ISSUE THREAD

**Issue by johsnows** [LeetCode-Feedback/LeetCode-Feedback#851]
你们写的题解是假的，还时间复杂度是O(log n)真丢人，每次碰到相同的就-1,也太搞笑了吧, 可以试试2 1 2 2 2 ... 一共 99999个2的数据， 看看你是不是O(log n)  不要出这种假题来害人浪费时间去想了

**Comment by johsnows** [comment]
看了下题解里说了数据随机生成。。。 题目里不写？？？数据是不是随机生成根本不是一道题，也不是一个做法号了吧。。。服了

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by CherylWulala** [comment]
题解确认过了没有问题哦～ 建议可以仔细阅读下这个题的复杂度分析或许可以解开你的疑惑。祝你刷题愉快 💪
