### ISSUE TITLE
Missing Test Case - 858. Mirror Reflection

### ISSUE THREAD

**Issue by ShubhanshuGupta3011** [LeetCode-Feedback/LeetCode-Feedback#8511]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by ShubhanshuGupta3011** [comment]
the main concept for this question is to think outside the box... extend the number of box
by what factor number of box
(q/gcd(p,q))
now question is all about even odd

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
