### ISSUE TITLE
Minor Grammatical Error - 1403. Minimum Subsequence in Non-Increasing Order

### ISSUE THREAD

**Issue by notsogoodaditya** [LeetCode-Feedback/LeetCode-Feedback#8512]
#### Your LeetCode username
Aditya001

#### Category of the bug
- [x] Question

#### Description of the bug
Small grammatical error . Missing word "be' for the explanation of Example 2.
"Note the subsequence has to returned in non-decreasing order. " should be corrected to "Note the subsequence has to **be** returned in non-decreasing order.  "

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots
![image](https://user-images.githubusercontent.com/79082526/182774488-19ce43d3-eda2-4d23-836d-bbec974a303a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
