### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by Anthony-Park** [LeetCode-Feedback/LeetCode-Feedback#8513]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
	bool hasCycle(ListNode *head) {
		ListNode *pSlow, *pFast;
		pFast = pSlow = head;

		while (pSlow and pFast) {
			pSlow = pSlow->next;

			pFast = pFast->next;
			if (pFast) pFast = pFast->next;

			if (pSlow == pFast) return true;
		}

		return false;
	}
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Anthony-Park** [comment]
Sorry. It's my mistake.

During comparing problem 141, 142. Linked List Cycle,
I didn't do correctly.
