### ISSUE TITLE
1494. 并行课程 II 

### ISSUE THREAD

**Issue by aoyvx** [LeetCode-Feedback/LeetCode-Feedback#8514]
**你的 LeetCode 用户名**
ao-yu

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目参数描述和方法形参名称不同

**你使用的语言**
java

**期望行为**
将题目描述中的dependencies修改为relations, 或将java模板中的relations修改为dependencies.

**屏幕截图**
![image](https://user-images.githubusercontent.com/37075400/182795771-920cd440-e426-4d5f-816d-6c21d37bd460.png)

**Comment by BrambleWave** [comment]
你好，当前题目描述已更新，积分奖励已发放，请查收。
