### ISSUE TITLE
Missing Test Case - 229. Majority Element II

### ISSUE THREAD

**Issue by mdcse** [LeetCode-Feedback/LeetCode-Feedback#8515]
#### Your LeetCode username
mdcse

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

#### Description of the bug
My code is accepted by Majority Element II, But is failing in with some testCases.
when i passing the input containing the same value of num1 and num2(in my code) which i used to initialise it is giving wrong output.
for this particular value in my code.

 INPUT : [1000000000]

#### Code you used for Submit/Run operation

```
// Majority Element II
class Solution {
public:
    vector<int> majorityElement(vector<int>& nums) 
    {
        int cnt1 = 0, cnt2 = 0;
        int num1 = 1e9, num2 = 1e9;
        
        for(int i =0; i<nums.size(); i++)
        {
            int ele = nums[i];
            if(num1 == ele )cnt1++;
            else if(num2 == ele )cnt2++;
            else if(cnt1 == 0)
            {
                num1 = ele;
                cnt1 = 1;
            }
            else if(cnt2 == 0)
            {
                num2 = ele;
                cnt2 = 1;
            }
            else
            {
                cnt1--;
                cnt2--;
            }
        } 
        cnt1 = 0, cnt2 = 0;
        for(int i = 0; i<nums.size(); i++)
        {
            if(nums[i] == num1)cnt1++;
            if(nums[i] == num2)cnt2++;
        }
       
        vector<int> ans;
        if(cnt1 > nums.size()/3)ans.push_back(num1);
        if(cnt2 > nums.size()/3)ans.push_back(num2);
        
        return ans;
    }
};

```

#### Expected behavior
For INPUT : [1000000000] output should be[1000000000] but it giving [1000000000,1000000000] and still it is accepted by 229. Majority Element II.

#### Screenshots
<img width="1280" alt="majorityElement2" src="https://user-images.githubusercontent.com/88222476/182813747-afb7599b-2ba3-4332-a0c0-6d9e75b3c4d7.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
