### ISSUE TITLE
33 int减1返回溢出

### ISSUE THREAD

**Issue by MISTAKKE** [LeetCode-Feedback/LeetCode-Feedback#8518]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
 int减1返回溢出
Line 1034: Char 34: runtime error: addition of unsigned offset to 0x6020000002d0 overflowed to 0x6020000002cc (stl_vector.h)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:1043:34

**你使用的语言**
C++

**你提交或者运行的代码**
```

class Solution {
  public:
    int search(vector<int>& nums, int target) {
        if (nums.size() == 0) {
            return -1;
        }
        if (nums.size() == 1) {
            if (nums[0] != target) {
                return -1;
            }
            return 0;
        }
        int left = 0, right = (int)(nums.size() - 1);
        while (left <= right) {
            int mid = (left + right) / 2;
            if (nums[mid] == target) {
                return mid;
            }
            // 左侧递增
            else if (nums[left] <= nums[mid - 1]) {
                // 在左侧
                if (target >= nums[left] && target <= nums[mid - 1]) {
                    right = mid - 1;
                }
                else {
                    left = mid + 1;
                }
            }
            //右侧递增
            else {
                // if (target >= nums[mid] && target <= nums[right]) {
                    left = mid + 1;
                }
                else {
                    right = mid - 1;
                }
            }
        }
        return -1;
    }
};
```

**期望行为**
测试用例：
[1,3]
0

期望行为：返回-1

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/25926258/182877459-173724b2-7c91-4862-b801-d7094d96dab4.png)

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
![Uploading origin_img_v2_67899029-b265-461e-8c2e-005777e3917g.jpg…]()

**Comment by BrambleWave** [comment]
![origin_img_v2_67899029-b265-461e-8c2e-005777e3917g](https://user-images.githubusercontent.com/99636790/183575419-bed840e4-4a7b-4e09-ad54-062f863baa4b.jpg)
