### ISSUE TITLE
 75. Sort Colors

### ISSUE THREAD

**Issue by lavanya200276** [LeetCode-Feedback/LeetCode-Feedback#8519]
class Solution:
    def sortColors(self, nums: List[int]) -> None:
        res= nums.sort()
        return res

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
