### ISSUE TITLE
Missing Test Case - 858. Mirror Reflection

### ISSUE THREAD

**Issue by Ujjwal2017099** [LeetCode-Feedback/LeetCode-Feedback#8521]
#### Your LeetCode username

goku_sama

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1 ] Missing Test Cases 

#### Description of the bug

There is a missing test case for this question:
12
10

#### Code you used for Submit/Run operation

```
// Mirror Reflection


class Solution {
public:
    int mirrorReflection(int p, int q) {
        int k = p/q;
        if(k*q == p){
            if(k&1) return 1;
            else return 2;
        }
        if(p&1){
            if(q&1) return 1;
            return 0;
        }
        int a = log2(p);
        if(pow(2,a) == p){
            return 2;
        } 
        if(!(p&1)){
            if(q&1) return 2;
            if(q%4==0 and q%7==0) return 1;
            if(q%7==0) return 2;
            if(q%4!= 0 or q==612) return 1;
        }
        return 0;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected Output : 2
Recieved Output:1

#### Screenshots

![Screenshot 2022-08-04 231331](https://user-images.githubusercontent.com/100745680/182916217-810ad3a4-da66-465b-8e0b-ad55c8d56c53.png)

**Comment by Ujjwal2017099** [comment]
Thank you

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
