### ISSUE TITLE
Missing Test Case - 225. Implement Stack using Queues

### ISSUE THREAD

**Issue by Pradeep17Jadhav** [LeetCode-Feedback/LeetCode-Feedback#8523]
#### Your LeetCode username
PradeepJadhav

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The current 16 test cases are missing an important thing.
My custom test case is this: 

["MyStack","push","push","push","push","push","top","pop","top"]
[[],[1],[2],[3],[4],[2],[],[],[]]

After pushing 1,2,3,4,2, When you pop from this stack, the new top should be 4.
Using my code, the new top becomes 1. So it correctly gives wrong answer error.
But still after submitting the answer, all 16 existing test cases are accepted.
Kindly add my test case as a new default test case to catch wrong answers like this.

#### Code you used for Submit/Run operation

```
class MyStack {
public:
    queue<int> q;
    int peek = -1;

    MyStack() {
    }
    
    void push(int x) {
        peek = x;
        q.push(x);
    }
    
    int pop() {
        int n = q.size();
        int temp;
        while(n--)
        {
            temp = q.front();
            q.pop();
            if(temp == peek)
            {
                peek = q.back();
                return temp;
            }
            else
                q.push(temp);
        }
        return -1;
    }
    
    int top() {
        return peek;
    }
    
    bool empty() {
        return q.empty();
    }
};
```

#### Language used for code
C++

#### Expected behavior
The existing test cases should check for duplicates while pushing and checking top element of the stack (created using queue)

#### Screenshots

![image](https://user-images.githubusercontent.com/42565481/182923432-69ba98d4-037a-4bb1-9bfe-0f33f6bbc47c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
