### ISSUE TITLE
Question Typos - 584. Find Customer Referee

### ISSUE THREAD

**Issue by jcschwartz3205** [LeetCode-Feedback/LeetCode-Feedback#8525]
#### Your LeetCode username
killerbeez

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Typos in the sentence:

>Write an SQL query to report the names of the customer that are not referred by the customer with id = 2.

#### Expected behavior
'Write an SQL query to report the names of the customer that are not ~~referred~~ [refereed] by the ~~customer~~ [referee] with id = 2.'

#### Additional context

The solution to the question appears to be looking for those customers who were not refereed by the referee with the ID of 2. The first typo in the sentence is a spelling mistake; 'referred' is the past tense of 'refer', while 'refereed' is the past tense of 'referee'. The second typo makes the question appear to be asking for something else entirely: those customers without the customer ID of 2, rather than the referee ID of 2

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to checked the problem, it is currently correct.  We appreciate your support!
