### ISSUE TITLE
Missing Test Case - 706. Design HashMap

### ISSUE THREAD

**Issue by Daimy0u** [LeetCode-Feedback/LeetCode-Feedback#8526]
#### Your LeetCode username

Daimyou

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Code works in test, but gives error after submission. For some reason a value returns as an exception on the submission check but not on the test check.

#### Code you used for Submit/Run operation

```
hashmap = dict()
class MyHashMap:
    def __init__(self):
        hashmap = dict()

    def put(self, key: int, value: int) -> None:
        hashmap[key] = value

    def get(self, key: int) -> int:
        try:
            return hashmap[key]
        except KeyError:
            return -1
    def remove(self, key: int) -> None:
        try:
            del hashmap[key]
        except:
            return 0
# Your MyHashMap object will be instantiated and called as such:
# obj = MyHashMap()
# obj.put(key,value)
# param_2 = obj.get(key)
# obj.remove(key)
```

#### Language used for code

Python3

#### Expected behavior

"Run Code" button returns the same results when given the same input

#### Screenshots

![image](https://user-images.githubusercontent.com/46105404/182964603-3a3b1f44-a764-407e-a345-97dcb7efd26f.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
