### ISSUE TITLE
33. Search in Rotated Sorted Array - O(N) solution works but O(Log(N)) is asked

### ISSUE THREAD

**Issue by Daniel-WR-Hart** [LeetCode-Feedback/LeetCode-Feedback#8527]
#### Your LeetCode username
omgitsmiketyson

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Either the upper range for `nums.length` is way too low for a binary search to be necessary, or the amount of time allowed for testing is too generous.
Its range is currently `1 <= nums.length <= 5000`, but it should probably be something more like `1 <= nums.length <= 1e6`, unless there are size limits to how big test cases can be?

#### Code you used for Submit/Run operation
```
// linear search, O(N) time instead of O(Log(N))
var search = function(nums, target) {
    return nums.indexOf(target);
};
```

#### Language used for code
JavaScript

#### Expected behavior
TLE for test cases where `nums.length` is very large.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. After investigated the issue that you mentioned, there is no way to fail O(n) in this problem. We appreciate your support!

**Comment by Daniel-WR-Hart** [comment]
But that's the issue, O(n) is supposed to fail
