### ISSUE TITLE
175. Combine Two Tables - typos and unclear description 

### ISSUE THREAD

**Issue by RTnhN** [LeetCode-Feedback/LeetCode-Feedback#8529]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There are several typos in the description of the solution for 175. Combine Two Tables. 

 - The solution says "join this two table" which should be either "join these two tables" or another way such as "join this table to XX table"
 - The answer is a little confusing in saying use "outer join" when the code and MySQL does not use that terminology. While it seems technically true that outer join is both default and what is used in this instance, perhaps you could make a comment about it like "For MySQL, an outer join is performed either using Left Join or Right Join ".  
 - Typo: "Considering there might not be an address information..." should be "Considering there might not be address information..."
 - Typo: "Note: Using where clause to filter..." should be "Note: Using the where clause to filter..."

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

N/A

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
