### ISSUE TITLE
Add constraints - 48. Rotate Image

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#853]
#### Your LeetCode username
pgmredy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

48. Rotate Image
https://leetcode.com/problems/rotate-image/

Please add constraints for the question
- What is the maximum n value?
- What are min and max values of each value in matrix

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- Constraints must be present for a question
See description

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
