### ISSUE TITLE
Leetcode216 combination-sum-iii: 在线测试结果和提交结果不一致

### ISSUE THREAD

**Issue by YuYoung32** [LeetCode-Feedback/LeetCode-Feedback#8530]
**你的 LeetCode 用户名**
Young32

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
这一题在线自测和本地运行，"3 9"这组测试数据的运行结果都是正确的，但是提交后总是显示这组数据结果错误。本人考虑可能是因为使用了全局变量，然后在不使用全局变量的情况下一切正常，bug似乎与使用全局变量有关。

**你使用的语言**
Golang

**你提交或者运行的代码**
```go
// combination-sum-iii
var res [][]int
var tk int
var tn int

func combinationSum3(k int, n int) [][]int {
    tk=k
    tn=n
    BackTrack([]int{}, 0, 1)
    return res
}

func BackTrack(path []int, bsum int, begin int){
    if len(path)==tk{
        if bsum==tn{
            tmp:=make([]int,tk)
            copy(tmp,path)
            res=append(res, tmp)
        }else{
            return
        }
    }
    for i:=begin;i<=9;i++{

        BackTrack(append(path, i), bsum+i, i+1)
    }
}
```

**期望行为**
在线测试结果和提交结果一致

**屏幕截图**
![5IE(QJ UGH8D629%3)X` 7X](https://user-images.githubusercontent.com/79970158/182987865-25b0e36a-c88f-4873-ab02-0ae975ffcf81.png)

**额外的上下文**
出错的提交
https://leetcode.cn/submissions/detail/346090362/

**Comment by BrambleWave** [comment]
如果出现测试用例结果和提交结果不一致的情况，您可以再仔细检查并调试您的代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」获得更多帮助。
如果无法解决此问题，您可以再次反馈。
