### ISSUE TITLE
学习计划进度错误

### ISSUE THREAD

**Issue by everythingCanBeModeled** [LeetCode-Feedback/LeetCode-Feedback#8531]
**LeetCode 用户名**
[Untitled-0](https://leetcode.cn/u/everythingcanbemodeled/)

**Bug 类型**
- [x]  学习计划进度错误

**描述**
学习计划里编程题还未全部完成，就出现了学习进度超过100%的情况。

**期望行为**
希望可以更正为正确的学习进度。

**屏幕截图**
![image](https://user-images.githubusercontent.com/75769380/182990726-37518b50-56ea-4eea-bcc2-f10218260662.png)
![image](https://user-images.githubusercontent.com/75769380/182990772-692262f3-1eb4-4b96-b667-81431150eefc.png)

**Comment by BrambleWave** [comment]
感谢您的反馈，我们会尽快修复此问题。

**Comment by everythingCanBeModeled** [comment]
【自动回复】来信已收到，十分感谢！
