### ISSUE TITLE
Missing Test Case - 365. Water and Jug Problem

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#8533]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
A solution which can be accepted now gets TLE in specific test case:
999979  999983  123455
Besides, there is a very nice math solution with O(log(max(x,y))) time complexity, and I think it is worth knowing and may be required during a real interview. So I think a follow-up requirement can be added.

Code you used for Submit/Run operation

The code below get TLE in the specific test case.
```
class Solution:
    def canMeasureWater(self, x: int, y: int, z: int) -> bool:
        stack = [(0, 0)]
        self.seen = set()
        while stack:
            remain_x, remain_y = stack.pop()
            if remain_x == z or remain_y == z or remain_x + remain_y == z:
                return True
            if (remain_x, remain_y) in self.seen:
                continue
            self.seen.add((remain_x, remain_y))
            stack.append((x, remain_y))
            stack.append((remain_x, y))
            stack.append((0, remain_y))
            stack.append((remain_x, 0))
            stack.append((remain_x - min(remain_x, y - remain_y), remain_y + min(remain_x, y - remain_y)))
            stack.append((remain_x + min(remain_y, x - remain_x), remain_y - min(remain_y, x - remain_x)))
        return False
```

The code below is a very nice math solution:
```
class Solution:
    def canMeasureWater(self, x: int, y: int, z: int) -> bool:
        return z%math.gcd(x,y)==0 and x+y>=z
```

Language used for code
Python3

Expected behavior
1. The test case below should be added:  
999979  999983  123455

2. A follow-up requirement can be added: Can you solve this problem in less than O(x+y) time complexity?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Math solution is out of interview scope. We appreciate your support!
