### ISSUE TITLE
1408. 数组中的字符串匹配 题目描述错误

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#8535]
**你的 LeetCode 用户名**
yanglock-6

**Bug 类型**
- [x] 题目

**描述**
题目描述错误
如果你可以删除 `words[j]` 最左侧和/或最右侧的若干字符得到 `word[i]`

**期望行为**
改为
如果你可以删除 `words[j]` 最左侧和/或最右侧的若干字符得到 word **`s`** [i]

**额外的上下文**
[题目链接](https://leetcode.cn/problems/string-matching-in-an-array/)

**Comment by BrambleWave** [comment]
你好，当前题目描述已更新，奖励已发放。
