### ISSUE TITLE
Question - 626. Exchange Seats

### ISSUE THREAD

**Issue by goffygoo** [LeetCode-Feedback/LeetCode-Feedback#8536]
#### Your LeetCode username
https://leetcode.com/top_text/

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Wrongly printed problem description 

#### Language used for code

MySQL

#### Additional context

The column name ```name``` is wrongly printed as ```name``` which instead should be ```student```
The wrong description confuses many readers.

#### Screenshots

![image](https://user-images.githubusercontent.com/67953525/183039191-a9eeeaa3-6445-457d-8e6d-3104aacaaba5.png)

The column name is given ```name``` for the student's name in Schema description

![image](https://user-images.githubusercontent.com/67953525/183039808-11404752-78c7-4fa5-8685-d5d0ae3f3354.png)

But is in fact ```student``` in the actual Schema.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
