### ISSUE TITLE
Wrong Expected Out in Question No:2170 Minimum Operations to Make the Array Alternating

### ISSUE THREAD

**Issue by akash-kd** [LeetCode-Feedback/LeetCode-Feedback#8537]
#### Your LeetCode username
https://leetcode.com/csdope017/

#### Category of the bug
- [ ] Solution
- [ ] Missing Test Cases 

#### Description of the bug
For the input testcase of arr = [1,1,1,3,3,3,3,3,3], the output is 4 which is wrong.
because 
[1,1,1,3,3,3,3,3,3] => [1,1,1,**`1,1`**,3,3,3,3] change  = 2,
[1,3,1,3,1,3,1,3,1] => alternating sqeuence.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minimumOperations(vector<int>& nums) {
        map<int,int> m;
        for(auto i:nums) m[i]++;
        vector<int> freq;
        for(auto i:m) freq.push_back(i.second);
        sort(freq.begin(),freq.end());
        int N = nums.size();
        int n = freq.size();
        int a = freq[n-1];
        int b = freq[n-2];
        int x = N - (a+b) + 1;
        
        int f1=0,f2=0;
        if(N%2 == 0) f1 = N/2,f2 = N/2;
        else f2 = (N-1)/2,f1 = f2+1;
        
        cout<<a<<" "<<b<<" "<<f1<<" "<<f2<<" "<<x<<endl;        
        
        
        return abs(f1 - a) + abs(f2 - b) + x;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
Expected output should be 2 but it shows 4 idk how but its wrong

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
