### ISSUE TITLE
Reduce difficulty level - from Hard to Medium - 145. Binary Tree Postorder Traversal

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#854]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

145. Binary Tree Postorder Traversal
https://leetcode.com/problems/binary-tree-postorder-traversal/

This might be initial problems of LC.
This is only traversing of Tree, not at all Hard level.
This is only 8 lines of code.

This is incorrectly rated as Hard problem.

Now, there are `many many` tree problems that are `much much` harder than this and are only rated as Medium.

Please reduce the level of this problem from Hard to Medium.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

This problem is of Easy level. Max Medium. See description above.
Hard level of problems should really be hard.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your feedback regarding this problem. Upon review, our team has updated the problem difficulty but we will not be rewarding LeetCoins for these types of cases. Thank you once again and happy LeetCoding!
