### ISSUE TITLE
Missing Test Case - 1729. Find Followers Count

### ISSUE THREAD

**Issue by Hp0112** [LeetCode-Feedback/LeetCode-Feedback#8540]
#### Your LeetCode username
hariprasadkrish

#### Category of the bug
- [ ] Question - 1729. Find Followers Count
- [ ] Solution  - ```select user_id, count(distinct follower_id) as followers_count from Followers 
group by user_id order by user_id;```
- [ ] Language - MySQL
- [ ] Missing Test Cases - Order by user_id  testcase is not validated in the solution which is asked in the question.

#### Description of the bug

We need to result the table ordered by user_id. But this is not validated after submission. I am able to see all the test cases passed even without sorting the table.

#### Code you used for Submit/Run operation

```
select user_id, count(distinct follower_id) as followers_count from Followers 
group by user_id;
```

#### Language used for code

MySQL

#### Expected behavior

Solution should validate whether user_id is sorted in ascending order or not.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
We do validate the answer is ordered by user_id.
Please read the solution carefully and use the discussion section to understand why it passed without using sorting.
 We appreciate your support!
