### ISSUE TITLE
Program execution and Language - 377. Combination Sum IV

### ISSUE THREAD

**Issue by thooriga** [LeetCode-Feedback/LeetCode-Feedback#8542]
#### Your LeetCode username
sinist3r

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Question statement has line which states
> The test cases are generated so that the answer can fit in a 32-bit integer.

But it looks like the testcases have been updated recently but the question statement has not.

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
    int combinationSum4(vector<int>& nums, int target) {
        vector<int> dp(target+1, 0);
        dp[0] = 1;
        for (int i = 1; i <= target; i++) {
            for (auto x : nums) {
                if (i < x) {
                    continue;
                }
                dp[i] += dp[i - x];
            }
        }
        return dp[target];
    }
};
```

#### Language used for code
C++

#### Expected behavior
According to the question the code should run without errors and should be accepted. But the code produced above results in a runtime error (signed overflow) which triggers UB.
The same code with only one alteration, that is changing the value type of `std::vector` to `unsigned int` works.
This works:
```cpp
class Solution {
public:
    int combinationSum4(vector<int>& nums, int target) {
        vector<unsigned int> dp(target+1, 0);
        dp[0] = 1;
        for (int i = 1; i <= target; i++) {
            for (auto x : nums) {
                if (i < x) {
                    continue;
                }
                dp[i] += dp[i - x];
            }
        }
        return dp[target];
    }
};
```
Interestingly it fails even with `long long`
`long long` is most probably a 64-bit signed integer. The value type of elements in array is `long long` and still it overflows.
This also fails:
```cpp
class Solution {
public:
int combinationSum4(vector<int>& nums, int target) {
    std::vector<long long> dp {};
    dp.resize(target + 1);
    dp[0] = 1;

    for (long long i = 1; i < dp.size(); ++i) {
        for (const auto& ele : nums) {
            if (i - ele < 0) {
                continue;
            }
            dp[i] += dp[i - ele];
        }
    }

    return dp[target];
}
};
```

Finally  this works
```cpp
class Solution {
public:
int combinationSum4(vector<int>& nums, int target) {
    std::vector<unsigned long long> dp {};
    dp.resize(target + 1);
    dp[0] = 1;

    for (unsigned long long i = 1; i < dp.size(); ++i) {
        for (const auto& ele : nums) {
            if (i - ele < i) {
                dp[i] += dp[i - ele];
            }
        }
    }

    return dp[target];
}
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/68967924/183122695-9e285863-d7a7-46af-92da-be597447b538.png)

#### Additional context
- The question statement should be changed to meet the requirements of updated testcases.
- It remains unclear, how the program gets accepted with `unsigned` integers as value type (both 32 and 64-bit), but fails with `signed` integers (both 32 and 64-bit).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The final answer fits in a 32-bit integer. The way that you chose to solve the problem made some intermediate calculations that has overflow. Please check for the overflow in the solution. We appreciate your support!
