### ISSUE TITLE
Missing Test Case - 377. Combination Sum IV

### ISSUE THREAD

**Issue by Arsh069** [LeetCode-Feedback/LeetCode-Feedback#8543]
#### Category of the bug
- [ **]_** Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
for the sample testcase nums=[9] and target=0 when I am running the testcase then it is showing the correct answer but for the same 
test case it is showing wrong answer after submitting it

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    static int ans=0;
    public static void func(int[] arr,int p,int t){
        if(t==p) {
            ans++;
            return;
        }
        if(p>t){
            return;
        }
        for(int i=0;i<arr.length;i++){
                p+=arr[i];
                func(arr,p,t);
                p-=arr[i];
        }
    }
    public static int combinationSum4(int[] nums, int target) {
        func(nums,0,target);
        return ans;
    }
}
```

#### Language used for code
Java

#### Expected behavior

it should also pass this testcase when I submit the code as the same is passing when I run the code in description window

#### Screenshots

Expected
![expected](https://user-images.githubusercontent.com/65395355/183133070-f0fc29e6-f39a-4e94-878a-421e1f988cfe.png)
 Actual
![actual](https://user-images.githubusercontent.com/65395355/183133238-956faff4-ba62-44f7-80b2-5ed953e798b3.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
