### ISSUE TITLE
Format issue in question - 146. LRU Cache

### ISSUE THREAD

**Issue by kentoym** [LeetCode-Feedback/LeetCode-Feedback#8544]
#### Your LeetCode username
kenty777

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The code format is not good in the last constrains. (The last line in the question description)
At most 2 `* 10^5` calls will be made to `get` and `put`.

#### Expected behavior

Expected:
At most `2 * 10^5` calls will be made to `get` and `put`.

#### Screenshots

![image](https://user-images.githubusercontent.com/32149707/183221220-18a26e59-2f90-4091-82cb-235cd6763231.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
