### ISSUE TITLE
98.验证二叉搜索树

### ISSUE THREAD

**Issue by lcz-sys** [LeetCode-Feedback/LeetCode-Feedback#8545]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
刘彤彤

**Bug 类型**
- [ ] 题目
- [ √] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
测试用例为[0]或[0,-1]时，控制台结果和提交后的结果不一致

**你使用的语言**
golang

**你提交或者运行的代码**
```
func isValidBST(root *TreeNode) bool {
	return isValid(root)
}

var pre *TreeNode

func isValid(root *TreeNode) bool {
	if root == nil {
		return true
	}
	if !isValid(root.Left) {
		return false
	}
	if pre != nil && pre.Val >= root.Val {
		return false
	}
	pre = root
	return isValid(root.Right)
}
```

**期望行为**
控制台和提交代码测试用例所得结果或一致

**屏幕截图**
![图片](https://user-images.githubusercontent.com/70613114/183231082-3b24fb0f-7f16-4318-ac3f-f5a342695a1e.png)

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
可以描述下是哪道题目么？
你也可以看下以下网址可不可以解决您的问题。https://support.leetcode.cn/hc/kb/article/1194344/
