### ISSUE TITLE
88. Merge Sorted Array

### ISSUE THREAD

**Issue by saurabh-sen** [LeetCode-Feedback/LeetCode-Feedback#8547]
#### Category of the bug
- [ example contains mistake, as stated by question "two integers m and n, representing the number of elements in nums1 and nums2 respectively" but in example 1 value of nums1 is wrong ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
example contains mistake, as stated by question "two integers m and n, representing the number of elements in nums1 and nums2 respectively" but in example 1 value of nums1 is wrong since value of m is 3 but nums has size 6

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
example 1 correction that's all

#### Screenshots
![Screenshot (189)](https://user-images.githubusercontent.com/68960038/183237219-6690da25-d78d-4828-b164-261340b651f6.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The statement said that there are n zeros at the end of nums1.
The constraints mentioned that nums1 == m+n.
please read the statement and the constraints carefully. We appreciate your support!
