### ISSUE TITLE
Missing Test Case - 2035. Partition Array Into Two Arrays to Minimize Sum Difference

### ISSUE THREAD

**Issue by harish-515** [LeetCode-Feedback/LeetCode-Feedback#8548]
#### Your LeetCode username
harish-515

#### Category of the bug
- [ ] Question
- [#] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
2035. Partition Array Into Two Arrays to Minimize Sum Difference.
The following question seems to be ambiguous. As explained in the 
Existing Example :
        Input: nums = [-36,36]
        Output: 72
        Explanation: One optimal partition is: [-36] and [36].
        The absolute difference between the sums of the arrays is abs((-36) - (36)) = 72.

My Case : 
       For the same case we can generate subsets such that {-36,36} & {}. So now the sum of 
       two subsets is zero. And the difference between them is also 0. Which is minimum in 
       this case.

#### Code you used for Submit/Run operation
```
public class Solution {
    public int MinimumDifference(int[] nums) {
        if(nums.Length == 0)
            return 0;
        
        Dictionary<(int,int),int> dp = new Dictionary<(int,int),int>();
        
        return MinimumDiffDP(dp,nums,0,0,0);
    }
    
    public int MinimumDiffDP(Dictionary<(int,int),int> dp,int[] nums,int index,int sum1,int sum2)
    {
        if(index == nums.Length)
            return Math.Abs(sum2 - sum1);
        
        if(dp.ContainsKey((index,sum1)))
            return dp[(index,sum1)];
        
        
        var sum1Including = MinimumDiffDP(dp,nums,index+1,sum1+nums[index],sum2);
        var sum2Including = MinimumDiffDP(dp,nums,index+1,sum1,sum2+nums[index]);
        
        dp.Add((index,sum1),Math.Min(sum1Including,sum2Including));
        return dp[(index,sum1)];
    }
    
}
```

#### Language used for code
C# - CSharp

#### Expected behavior
Existing Example :
        Input: nums = [-36,36]
        Output: 0 // this should be expected output

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
