### ISSUE TITLE
Missing Test Case - 16. 3Sum Closest

### ISSUE THREAD

**Issue by mdcse** [LeetCode-Feedback/LeetCode-Feedback#8550]
#### Your LeetCode username
mdcse

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My code is accepted by 3Sum Closest, But is failing with the input
[0,0,0]
10000.

#### Code you used for Submit/Run operation

```
// 3Sum Closest

class Solution {
public:
    int threeSumClosest(vector<int>& nums, int target) 
    {
        int ans = 2e4, n = nums.size();
        sort(nums.begin(), nums.end());
        for(int i=0; i<n; i++)
        {
            int s = i + 1, e = n - 1;
            while(s < e)
            {
                int temp = nums[i] + nums[s] + nums[e];
                if(abs(target - temp) < abs(target - ans))ans = temp;
                if(temp < target)s++;
                else e--;
            }
        }
        return ans;
    }
};

```

#### Expected behavior
Code should return 10000 but it is returning 20000 and still it got accepted.

#### Screenshots
<img width="1280" alt="3sumcloset" src="https://user-images.githubusercontent.com/88222476/183244538-254c1891-6471-412f-afa1-b4dcbf3e0eac.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
