### ISSUE TITLE
Missing Test Case - 458. Poor Pigs

### ISSUE THREAD

**Issue by 152334H** [LeetCode-Feedback/LeetCode-Feedback#8551]
#### Your LeetCode username
152334H

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The test case
```
125
1
4
```
fails on the solution described [here](https://leetcode.com/problems/poor-pigs/discuss/2385451/)

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
  int poorPigs(int buckets, int poisonTime, int totalTime) {
    return ceil(log(buckets) / log(totalTime / poisonTime + 1));
  }
};
```

#### Language used for code
C++

#### Expected behavior
The solution submitted should fail with a Wrong Answer.

Instead, it is Accepted.

#### Screenshots
![image](https://user-images.githubusercontent.com/54623771/183245760-a7397c85-5db6-4228-9192-10a7ada3fbfd.png)

#### Additional context
https://leetcode.com/problems/poor-pigs/discuss/2387097/floating-point-errors-and-a-more-accurate-solution

**Comment by IsaacSherman** [comment]
Found this same test case this morning.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
