### ISSUE TITLE
458. Poor Pigs: The description seems hazy to me.

### ISSUE THREAD

**Issue by ahamed** [LeetCode-Feedback/LeetCode-Feedback#8552]
#### Your LeetCode username
sajeeb

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description is really hazy and I don't understand step 2. For example, step 2 says "For each pig, choose which buckets to feed it" but it is not clear how many buckets to pick. If there is no limit of buckets, then I pick one pig and feed it from all the buckets and then wait for `minutesToDie` and it will die.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
