### ISSUE TITLE
Bugs, 315. Count of Smaller Numbers After Self

### ISSUE THREAD

**Issue by LachezarTsK** [LeetCode-Feedback/LeetCode-Feedback#8556]
Hello,

There are some bugs for the C++ language for "315. Count of Smaller Numbers After Self".
Please see the two attached files for more details about my solution and the results of the test case.

The value of "vector<int> segments" in class SegmentTreenever exceeds INT_MAX. And yet, I have the following error:
"Line 22: Char 42: runtime error: signed integer overflow: 2147450880 + 65536 cannot be represented in type 'int' (solution.cpp)SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:31:42.
"
This test case is successful on your website only if I change the above-mentioned vector in class SegmentTree 
to "vector<long long> segments". However, this is not normal, since there is no need, whatsoever,to change the container from "int" to "long long". 

On my computer this test case is absolutely successful with "int".Besides, a Java solution that applies the very same algorithm does it successfully with "int".

Best regards,
Lachezar Kutsarov

[C++ Solution.pdf](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9275721/C%2B%2B.Solution.pdf)
[Test Case 62 for Count of Smaller Numbers After Self - Submission Detail - LeetCode.pdf](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9275723/Test.Case.62.for.Count.of.Smaller.Numbers.After.Self.-.Submission.Detail.-.LeetCode.pdf)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link, because when we tested your code, we received Compile Error.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LachezarTsK** [comment]
Hello,
Here is the link:
https://leetcode.com/submissions/detail/766935443/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the solution can be AC if the segment tree was changed from int to long long, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!

**Comment by LachezarTsK** [comment]
Hello,
Thanks, I know how to optimized my code without long long. I just mentioned that it is not normal for the C++ colution becuase the value never exceeds int, and besides, on my computer the very same C++ solution is successful with int  and without any additional optimization. And the Java code also is sucessful without any optimization, and it is both on the leetcode.com and on my computer. 
Anyway, thanks and best regards!
