### ISSUE TITLE
Add test case - 434. Number of Segments in a String

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#856]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

434. Number of Segments in a String
https://leetcode.com/problems/number-of-segments-in-a-string/

Please add below test case

    "  \t"

From the code posted at below:

https://leetcode.com/problems/number-of-segments-in-a-string/discuss/144073/JavaScript-2-line-Solution-by-adding-char

It looks like above test cases does not exist
when Submit is pressed
as on Jul 2019.

Please verify to check if this test case already exists now. Else add it. (Run Code passes, above post fails).

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

A test case 
May be missing

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thanks for your feedback. Upon review, our team has determined that this is an invalid test case. Though that is the case, we have updated the problem with constraints. We thank you for your feedback but will not be rewarding any LeetCoins for this ticket.
