### ISSUE TITLE
Missing test cases in 219. Contains Duplicate II

### ISSUE THREAD

**Issue by bash-all** [LeetCode-Feedback/LeetCode-Feedback#8560]
#### Your LeetCode username 

bash_it_all

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For this question ,the code submitted in the lowest amount of time doesn't work for test cases like [5,4,6,2,0,2] for k=2 and gives the wrong answer(false) though it is a valid test case with output true. Hence test cases like these must be added to this problem.

#### Code you used for Submit/Run operation
This is the sample 6ms submission fetched from the server.

```
import java.util.HashSet;
class Solution {
    public boolean containsNearbyDuplicate(int[] nums, int k) {
        for (int i = 0; i < nums.length; i++) {
            for (int j = i - 1; j >= Math.max(0, i - k); j--) {
                if (nums[i] > nums[j]) {
                    break;
                } else if (nums[i] == nums[j]) {
                    return true;
                }
            }
        }
        return false;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior

If we run this for the test case [5,4,6,2,0,2] which is a valid test case as per the constraints ,this sample 6ms submission fetched from the server gives output false though the output must be true.

#### Additional context

I believe test cases with similar trends must be added to this question.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
