### ISSUE TITLE
添加语言的编译器版本信息

### ISSUE THREAD

**Issue by xiayulu** [LeetCode-Feedback/LeetCode-Feedback#8561]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**代码大厨**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
能在语言后面添加有关编译器的版本信息吗？

因为有些语言的新版本可能有好用的功能，例如 Go 语言的泛型。

如果能在编译器后面添加版本信息，就能更加愉快的写代码了😘。

![image](https://user-images.githubusercontent.com/41274826/183271500-517601b0-32d4-48e9-ae28-4214612634e8.png)

像这样：
![image](https://user-images.githubusercontent.com/41274826/183271667-b04052c8-220e-4c09-9d36-23ebfc00d65a.png)

**Comment by stormsunshine** [comment]
点击语言下拉框左侧的图标i，会显示语言环境，包括版本信息。
