### ISSUE TITLE
Elixir Support - 271. Encode and Decode Strings

### ISSUE THREAD

**Issue by sheharyarn** [LeetCode-Feedback/LeetCode-Feedback#8563]
#### Your LeetCode username
@psyxn

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Elixir language support is missing for https://leetcode.com/problems/encode-and-decode-strings/

#### Code you used for Submit/Run operation

This is a valid solution:

```elixir
# Uses chunked encoding -- prefixes str length with each string
defmodule Solution do
  def encode(strings) do
    Enum.reduce(strings, "", fn str, acc ->
      len = byte_size(str)
      acc <> <<len::integer-32>> <> str
    end)
  end

  def decode(string) do
    string
    |> do_decode([])
    |> Enum.reverse()
  end

  defp do_decode("", strs), do: strs

  defp do_decode(<<len::integer-32, str::binary-size(len), rest::binary>>, strs) do
    do_decode(rest, [str | strs])
  end

  defp do_decode(_, _), do: raise "invalid data"
end
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team . We appreciate your support!
