### ISSUE TITLE
Longest Substring Without Repeating Characters - C++ - Approach 2 - Mistake in code

### ISSUE THREAD

**Issue by Farouk-bennejma** [LeetCode-Feedback/LeetCode-Feedback#8565]
#### Your LeetCode username

Farouk_Benejma

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In problem "3. Longest Substring Without Repeating Characters", in "Approach 2: Sliding Window" the code and algorithm use a hash_set instead of a hash_map which is incorrect.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
     int lengthOfLongestSubstring(string s) {
        unordered_set<char, int> chars;

        int left = 0;
        int right = 0;

        int res = 0;
        while (right < s.length()) {
            char r = s[right];
            chars[r]++;

            while (chars[r] > 1) {
                char l = s[left];
                chars[l]--;
                left++;
            }

            res = max(res, right - left + 1);

            right++;
        }

        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should be unordered_map instead of unordered_set in the solution code.

#### Screenshots

![image](https://user-images.githubusercontent.com/41647598/183274268-c1712ffd-b495-45b2-a086-9e48b8a3b270.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
