### ISSUE TITLE
Missing Test Case - 2370. Longest Ideal Subsequence

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#8566]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9276215/1.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestIdealString(string s, int k) {
        if(k==25) return s.size();
       

        int n=s.size();
        vector<int> ans,f(n+1,0);
        for(int i=0;i<s.size();i++)
            ans.push_back(s[i]-'a');
        int res=0;
        for(int i=0;i<n;i++){
            f[i]=1;
            for(int j=i>=100?i-100:0;j<i;j++)
                if(abs(ans[i]-ans[j])<=k)
                    f[i]=max(f[i],f[j]+1);
            res=max(res,f[i]);
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Output: 5123
Expected: 5124

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
