### ISSUE TITLE
Missing Test Case - 2363. Merge Similar Items

### ISSUE THREAD

**Issue by sudevdhali** [LeetCode-Feedback/LeetCode-Feedback#8567]
#### Your LeetCode username
newbiesd

#### Category of the bug
- [ ] Question
- [ .] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[[1,1],[1,5],[3,8]]
[[3,1],[1,5]]
this tastecase shouldnt get executed

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> mergeSimilarItems(vector<vector<int>>& items1, vector<vector<int>>& items2) {
        vector<vector<int>> arr;
        unordered_map<int,int> mp;
        int i=0;
        for(auto a:items1){
            if(mp.find(a[0])==mp.end()){
                mp[a[0]]=i;
                i++;
                arr.push_back({a[0],a[1]});
            }else{
                arr[mp[a[0]]][1]+=a[1];
            }
        }
        for(auto a:items2){
            if(mp.find(a[0])==mp.end()){
                mp[a[0]]=i;
                i++;
                arr.push_back({a[0],a[1]});
            }else{
                arr[mp[a[0]]][1]+=a[1];
            }
        }
        sort(arr.begin(),arr.end());
        return arr;
    }
};
```

#### Language used for code
c++

#### Expected behavior

the testcase should be blocked. same values in any array are getting executed.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. There was a problem with validator, we updated it. We appreciate your support!

**Comment by sudevdhali** [comment]
When will I get the 100 leetcoins?
