### ISSUE TITLE
add case 

### ISSUE THREAD

**Issue by ZAKLLL** [LeetCode-Feedback/LeetCode-Feedback#8568]
this solution  can pass all contest case:

```java
    class Solution {
        public boolean validPartition(int[] nums) {
            int len = nums.length;
            // dp[i]表示第i位结尾是否可行
            boolean[] dp = new boolean[len];
            dp[0] = false;
            dp[1] = (nums[1] == nums[0]);
            for (int i = 2; i < len; i++) {
                // 按第一种分法
                if (nums[i] == nums[i - 1] && dp[i - 2]) {
                    dp[i] = true;
                }
                // 按第二种分法
                if (nums[i] == nums[i - 2] && (i == 2 || dp[i - 3])) {
                    dp[i] = true;
                }
                // 按第三种分法
                if (nums[i] == nums[i - 1] + 1 && nums[i] == nums[i - 2] + 2 && (i == 2 || dp[i - 3])) {
                    dp[i] = true;
                }
            }
            return dp[len - 1];
        }
    }
```

but it's wrong 

like such case:
[1,1,1,2,1]

the right ans is false, but the solution' s ans is True

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ZAKLLL** [comment]
so sorry for forget it

this problem name is 
**check-if-there-is-a-valid-partition-for-the-array**
in weekly contest305

language: java

case: [1,1,1,2,1]

my lccn account: zakl

thanks a lot

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
