### ISSUE TITLE
Missing Test Case - 2369. Check if There is a Valid Partition For The Array

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8569]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [2369. Check if There is a Valid Partition For The Array](https://leetcode.com/problems/check-if-there-is-a-valid-partition-for-the-array), a solution that can get passed fails on a specific test case.
The test case is as follows.
```
[2,2,2,3,2]
```

#### Code you used for Submit/Run operation
```Java
class Solution {
    public boolean validPartition(int[] nums) {
        int len = nums.length;
        boolean[] dp = new boolean[len];
        dp[0] = false;
        dp[1] = (nums[1] == nums[0]);
        for (int i = 2; i < len; i++) {
            if (nums[i] == nums[i - 1] && dp[i - 2]) {
                dp[i] = true;
            }
            if (nums[i] == nums[i - 2] && (i == 2 || dp[i - 3])) {
                dp[i] = true;
            }
            if (nums[i] == nums[i - 1] + 1 && nums[i] == nums[i - 2] + 2 && (i == 2 || dp[i - 3])) {
                dp[i] = true;
            }
        }
        return dp[len - 1];
    }
}
```

#### Language used for code
Java

#### Expected behavior
Add the test case so that the code above will get Wrong Answer when submitted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link, because we received Wrong Answer when we submitted your code.
https://leetcode.com/submissions/detail/768593474/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by MsDas14** [comment]
Bug with test case [2,2,2,3,2] can be fixed by updating the second if condition as follows:

**if (nums[i]==nums[i-1] && nums[i] == nums[i - 2] && (i == 2 || dp[i - 3]))**
