### ISSUE TITLE
Missing Test Case - 2326. Spiral Matrix IV

### ISSUE THREAD

**Issue by zhenliang153** [LeetCode-Feedback/LeetCode-Feedback#8570]
#### Your LeetCode username
zhenliang153

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When there are n rows and n columns (n is an odd number that is not 1), the most central element cannot be accessed.
An accepted solution fails on the following testcase:
3
3
[1,2,3,4,5,6,7,8,9]

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    vector<vector<int>> spiralMatrix(int m, int n, ListNode* head) {
        vector<vector<int>> ret(m, vector<int>(n, -1));
        if (m == 1 && n == 1) {
            ret[0][0] = head->val;
            return ret;
        }
        for (int c = 0; head != nullptr; ++c) {
            for (int j = c; j + 1 + c < n && head != nullptr; ++j, head = head->next) {
                ret[c][j] = head->val;
            }
            for (int i = c; i + 1 + c < m && head != nullptr; ++i, head = head->next) {
                ret[i][n - 1 - c] = head->val;
            }
            for (int j = n - 1 - c; j > c && head != nullptr; --j, head = head->next) {
                ret[m - 1 - c][j] = head->val;
            }
            for (int i = m - 1 - c; i > c && head != nullptr; --i, head = head->next) {
                ret[i][c] = head->val;
            }
        }
        return ret;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Output: TLE
Expected: [[1,2,3],[8,9,4],[7,6,5]]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Can you send us your LCUS username?

**Comment by zhenliang153** [comment]
> Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
> 
> Can you send us your LCUS username?

I'm a new member of LCUS, and my LCUS username is zhenliang153. Thank you!
