### ISSUE TITLE
Solution video missing sound - problem 3

### ISSUE THREAD

**Issue by megpay** [LeetCode-Feedback/LeetCode-Feedback#8571]
#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution video for problem 3. Longest Substring Without Repeating Characters is missing sound. It is the last solution with the optimization titled: Approach 3: Sliding Window Optimized.

#### Code you used for Submit/Run operation

None

#### Language used for code

None

#### Expected behavior

I expected the video to have sound.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
