### ISSUE TITLE
测试用例存在错误

### ISSUE THREAD

**Issue by yyw2510780879** [LeetCode-Feedback/LeetCode-Feedback#8574]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
vignette

**Bug 类型**
- [ ] 题解

**描述**
测试用例存在错误：
测试用例：
"pineapplepenapple"
["apple","pen","applepen","pine","pineapple"]
我的返回结果：
["pine apple pen apple","pine  applepen apple","pineapple pen apple"]
题目结果：
["pine apple pen apple","pineapple pen apple","pine applepen apple"]
题目说明可以：**以任意顺序** 返回所有这些可能的句子。

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    List<String> ans=new ArrayList<>();
    public List<String> wordBreak(String s, List<String> wordDict) {
        HashSet<String> words=new HashSet<>(wordDict);
        dfs(0,s,words,new StringBuilder());
        return ans;
    }
    public void dfs(int start, String s, HashSet<String> words,StringBuilder sentence){
        if(start==s.length()){
            ans.add(sentence.toString().trim());
            return;
        }
        int len=s.length();
        for(int i=start;i<len;i++){
            String subStr=s.substring(start,i+1);
            if(words.contains(subStr)){
                sentence.append(subStr+" ");
                dfs(i+1,s,words,sentence);
                sentence.delete(sentence.lastIndexOf(subStr),sentence.length()-1);
            }
        }
    }
}
```

**期望行为**
["pine apple pen apple","pine  applepen apple","pineapple pen apple"]应该被判定为正确

**屏幕截图**
![image](https://user-images.githubusercontent.com/67775418/183298702-98e89e04-14db-4f91-9ebe-e73d7a17a4fe.png)

**额外的上下文**
题目：140题单词拆分II

**Comment by stormsunshine** [comment]
你的输出的第二个字符串中有两个连续的空格，所以结果错误。

**Comment by yyw2510780879** [comment]
谢谢指证！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 上午8:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] 测试用例存在错误 (Issue #8574)





 
你的输出的第二个字符串中有两个连续的空格，所以结果错误。
