### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by CRowland4** [LeetCode-Feedback/LeetCode-Feedback#8575]
#### Your LeetCode username

CRowland4

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I am attempting to solve this problem using the follow-up suggestion, which is to solve the problem without converting the input into a string. To accomplish this, I'm placing integers into a list representing the input's place values, then comparing the list to the reverse of itself. LeetCode seems to be adding 0s to my list, resulting in the wrong answer, while in PyCharm my list is as intended. I noticed this happening when the test case input was 11.

#### Code you used for Submit/Run operation

```
class Solution:
    x = 0

    ones = None
    tens = None
    hundreds = None
    thousands = None
    ten_thousands = None
    hundred_thousands = None
    millions = None
    ten_millions = None
    hundred_millions = None
    billions = None

    start_flag = False

    def isPalindrome(self, x: int) -> bool:
        Solution.x = x

        if x < 0:
            return False
        if x < 10:
            return True

        Solution.set_place_values()
        
        places = [
            int(place) for place in [
                Solution.ones,
                Solution.tens,
                Solution.hundreds,
                Solution.thousands,
                Solution.ten_thousands,
                Solution.hundred_thousands,
                Solution.millions,
                Solution.ten_millions,
                Solution.hundred_millions,
                Solution.billions
            ]
                     if place is not None
        ]

        reversed_places = list(reversed(places))
        print(f"places: {places}")
        print(f"reversed_places: {reversed_places}")
        print(f"Number is palindromic: {places == reversed_places}")
        return places == reversed_places

    @classmethod
    def set_place_values(cls):
        cls.helper('billions', 10e8)
        cls.helper('hundred_millions', 10e7)
        cls.helper('ten_millions', 10e6)
        cls.helper('millions', 10e5)
        cls.helper('hundred_thousands', 10e4)
        cls.helper('ten_thousands', 10e3)
        cls.helper('thousands', 10e2)
        cls.helper('hundreds', 10e1)
        cls.helper('tens', 10)
        cls.ones = cls.x if cls.x >= 0 else 0
        return

    @classmethod
    def helper(cls, place, num):
        if cls.x >= num:
            cls.start_flag = True
            setattr(cls, place, cls.x // num)
            place_number = getattr(cls, place)
            cls.x = cls.x - (place_number * num)
        elif cls.start_flag:
            setattr(cls, place, 0)
```

#### Language used for code

Python3

#### Expected behavior

I expected my variables "places" and "reversed_places" to be lists containing two elements, as shown in my PyCharm screenshot below, but instead they both contained several additional zeros, as shown in the LeetCode screenshot.

#### Screenshots

From PyCharm:
![image](https://user-images.githubusercontent.com/67015938/183301052-cf72128a-a304-49b9-800b-65a2411e09fe.png)

Same code (copy/paste) in LeetCode:
![image](https://user-images.githubusercontent.com/67015938/183301165-e3a17817-2d5a-4f4a-80a4-b22574c40579.png)

#### Additional context

Thank you for your time!

**Comment by 152334H** [comment]
This happens because you don't reset `Solution.start_flag` to `False` after the end of each invocation of `Solution.isPalindrome()`. You can see this in your own machine with the following code:
```python
s = Solution()
assert s.isPalindrome(11) != s.isPalindrome(11)
```
The assertion will pass because your Implementation of `isPalindrome` is stateful. Consider not using static class variables in your code :)

**Comment by CRowland4** [comment]
@152334H  Thank you for the reply! That makes sense. So is it a general rule to not use static class variables in general, or are the exceptions/specific instances where that would be ok?

**Comment by 152334H** [comment]
> @152334H Thank you for the reply! That makes sense. So is it a general rule to not use static class variables in general, or are the exceptions/specific instances where that would be ok?

It is quite hard to express a general principle for when to use a specific tool. One case I can think of is memoization -- a class function that is pure would only stand to gain (speed-wise) from a global cache.

In this specific problem, there are many suggested solutions you can find on the Leetcode discuss page that are shorter and faster than the highly verbose solution posted here. I would suggest defaulting to programming patterns that are predictable and familiar to weak programmers, as it will be easier for your interviewer to accept than a _unique_ solution.

**Comment by CRowland4** [comment]
Ok awesome thank you, I appreciate the advice. That's good to know, I wouldn't have immediately known that a unique solution isn't necessarily better than a shorter but more familiar solution.
