### ISSUE TITLE
Missing Test Case - 1419. Minimum Number of Frogs Croaking

### ISSUE THREAD

**Issue by erick576** [LeetCode-Feedback/LeetCode-Feedback#8578]
#### Your LeetCode username
ericn576

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The solution I had passed upon submission and yet it doesn't test my custom input where I have added an invalid combination of "croak" from different frogs. Here I changed the ordering so that it would be invalid. As expected, it failed my custom input and yet passes full submission.

![Error](https://user-images.githubusercontent.com/46385457/183310855-56589511-d1d6-40c6-b6c4-01bb737c7680.PNG)

#### Code you used for Submit/Run operation

```
class Solution {
    public int minNumberOfFrogs(String croakOfFrogs) {
        Map<Character, Integer> map = new HashMap<>();
        int answer = 0;
        
        for(int i = 0; i < croakOfFrogs.length(); i ++) {
            char c = croakOfFrogs.charAt(i);
            map.put(c, map.getOrDefault(c, 0) + 1);
        }

        int val = map.get('c');
        for(Character key : map.keySet()) {
            if(val != map.get(key)) return -1;
        }
        
        int curr = 0;
        for(int i = 0; i < croakOfFrogs.length(); i ++) {
            char c = croakOfFrogs.charAt(i);
            map.put(c, map.get(c) - 1);

            if(c == 'c') {
                curr++;
            }
            if(c == 'r') {
                int left = map.get('r');
                if(!(left < map.get('o') && left < map.get('a') && left < map.get('k'))) return -1;
            }
            if(c == 'o') {
                int left = map.get('o');
                if(!(left < map.get('a') && left < map.get('k'))) return -1;
            }
            if(c == 'a') {
                int left = map.get('a');
                if(!(left < map.get('k'))) return -1;
            }
            if(c == 'k') {
                curr--;
            }
            
            answer = Math.max(answer, curr);
        }
        
        return answer;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Submission is expected to fail

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
