### ISSUE TITLE
Explained solutions from solution article on 435. Non-overlapping Intervals hit TLE Error

### ISSUE THREAD

**Issue by abhilashgupta** [LeetCode-Feedback/LeetCode-Feedback#8579]
#### Your LeetCode username
jparni

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There are 5 solutions explained in the article to this problem, out of which solutions no 2 to 5 are listed as [Accepted].
I tried both solution no 3 (time complexity O(n^2)) and solution no5 (time complexity O(nlog(n))).
Solution no 3 hits TLE on testcase no 56/58 while solution no 5 hits TLE on testcase no 58/58.
The implementation language is C++.

#### Code you used for Submit/Run operation

```
// Solution approach no 3
class Solution {
public:
    static bool comparator(vector<int> a, vector<int> b){
        return a[1] < b[1];
    }
    int eraseOverlapIntervals(vector<vector<int>>& intervals) {
        sort(intervals.begin(), intervals.end(), comparator);
        
        int n = intervals.size();
        
        vector<int> dp(n, 1);
        int ans = 1;
        for (int i=1; i<n; i++){
            for (int j=i-1; j>=0; j--){
                if (intervals[i][0] >= intervals[j][1]){
                    dp[i] = max(dp[i], dp[j]+ 1);
                }
            }
            ans = max(ans, dp[i]);
        }
        return n- ans;
    }
};
```
```
// Solution approach no 5
class Solution {
public:
    static bool comparator(vector<int> a, vector<int> b){
        return a[1] < b[1];
    }
    int eraseOverlapIntervals(vector<vector<int>>& intervals) {
        sort(intervals.begin(), intervals.end(), comparator);
        
        int n = intervals.size();
        
        int end = intervals[0][1];
        // int prev = 0;
        int count = 1;
        
        for (int i=1; i<n; i++){
            if (intervals[i][0] >= end){
                end = intervals[i][1];
                count++;
            }
        }
        return n-count;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The solutions should pass (or the article should be updated, to show that they fail.
On a different note, the article is just so badly worded and there are a lot of mismatch between the explanation and the code examples in almost all the approaches (can definitely confirm for approaches 3, 4 & 5)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
