### ISSUE TITLE
1003. Check If Word Is Valid After Substitutions

### ISSUE THREAD

**Issue by tdserapio** [LeetCode-Feedback/LeetCode-Feedback#858]
It is not clear what is V. Please respond ASAP. Thank you in advanced.:)

**Comment by lc-ivan** [comment]
Hi @tdserapio ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @tdserapio ,
Could you please provide your LeetCode username?

**Comment by lc-ivan** [comment]
Hi @tdserapio ,
We would like to follow up again for your LeetCode username. Could you please provide your username to receive your LeetCoin reward?

**Comment by lc-ivan** [comment]
@tdserapio Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you'd like to receive the reward for the reported issue, please leave your user name and tag me in the comment. Thank you.
