### ISSUE TITLE
Missing Test Case - 761. Special Binary String

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#8580]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
"111001101001100011101100001010"

#### Code you used for Submit/Run operation

```
class Solution {
public:
	bool isSpecial(string&S, int st, int len) {
	  auto zeros = 0, ones = 0;
	  for (auto i = st; i < st + len && ones >= zeros; ++i) {
		zeros += S[i] == '0' ? 1 : 0;
		ones += S[i] == '1' ? 1 : 0;
	  }
	  return zeros == ones;
	}
	string makeLargestSpecial(string S) {
	  string bestS;
	  while (bestS != S) {
		S = bestS.empty() ? S : bestS;
		bestS = S;
		for (auto len = S.size() / 2 - (S.size() / 2) % 2; len >= 2; len -= 2) {
		  for (auto i = 0; i < S.size() - len - 2; ++i) {
			if (isSpecial(S, i, len)) {
			  for (auto len1 = len; i + len + len1 <= S.size(); len1 += 2) {
				if (isSpecial(S, i + len, len1)) {
				  bestS = max(bestS, S.substr(0, i) + S.substr(i + len, len1) + S.substr(i, len) + S.substr(i + len + len1));
				  break;
				}
			  }
			}
		  }
		}
	  }
	  return S;
	}
};
```

#### Language used for code

C++

#### Expected behavior

Output: "111010011001100011110010001010"
Expected: "111100100011101001100110001010"

#### Additional context

https://leetcode.com/problems/special-binary-string/discuss/113218/C%2B%2B-Greedy

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
