### ISSUE TITLE
Missing Test Case - 313. Super Ugly Number

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8584]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [313. Super Ugly Number](https://leetcode.com/problems/super-ugly-number), a solution that can get accepted fails on a specific test case.
The test case is as follows.
```
100000
[2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541]
```

#### Code you used for Submit/Run operation
The following two solutions are in Java and Python3, respectively.
**Note:** If the code already gets TLE before adding this test case in LCUS, please try the code in LCCN.

```Java
class Solution {
    public int nthSuperUglyNumber(int n, int[] primes) {
        Set<Long> seen = new HashSet<Long>();
        PriorityQueue<Long> heap = new PriorityQueue<Long>();
        seen.add(1L);
        heap.offer(1L);
        int ugly = 0;
        for (int i = 0; i < n; i++) {
            long curr = heap.poll();
            ugly = (int) curr;
            for (int prime : primes) {
                long next = curr * prime;
                if (seen.add(next)) {
                    heap.offer(next);
                }
            }
        }
        return ugly;
    }
}
```

```Python
class Solution:
    def nthSuperUglyNumber(self, n: int, primes: List[int]) -> int:
        nums = [1]
        visited = {1}
        st = set(primes)
        for j in range(n-1):
            cur = heapq.heappop(nums)
            for t in st:
                if cur*t not in visited:
                    heapq.heappush(nums,cur*t)
                    visited.add(cur*t)
        return heapq.heappop(nums)
```

#### Language used for code
Java and Python3, respectively.

#### Expected behavior
Add the test case above so that the code will get TLE when submitted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
