### ISSUE TITLE
Missing Test Case - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by lostlang** [LeetCode-Feedback/LeetCode-Feedback#8586]
#### Your LeetCode username
lostlang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Start from 8 (skip 2, 3)

#### Expected behavior
Start from 1 (skip 1, 2)

#### Screenshots
![Screenshot from 2022-08-08 20-12-56](https://user-images.githubusercontent.com/53492781/183475466-5c06a222-821a-42a6-86df-1452fb86be19.png)

#### Additional context
You need to add a description of what is a "Intersection of Two Linked Lists"

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
