### ISSUE TITLE
Amazon System Design video has poor audio quality

### ISSUE THREAD

**Issue by StevenBryceLee** [LeetCode-Feedback/LeetCode-Feedback#8590]

**Comment by StevenBryceLee** [comment]
Weird, I thought I followed the instructions but it doesn't look like anything relevant came through on the issue. Reposting:

Referencing this video: https://leetcode.com/explore/learn/card/system-design/690/system-design-case-studies/4384/
The audio quality is bad, and the captions are inaccurate. You can fix this issue by re-recording with a better quality microphone or applying better captioning or both.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.. We appreciate your support!
