### ISSUE TITLE
Fix Wording in Arrays 101 module

### ISSUE THREAD

**Issue by StephenHoust** [LeetCode-Feedback/LeetCode-Feedback#8591]
#### Your LeetCode username

SHoust

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is an error in the language used in the Arrays 101 module in the _Inserting Items into An Array_ chapter, under the _Array Insertions_ section at the end of the section under the _Inserting at the End of an Array_ header.

The sentences in question are:
```Notice how we also incremented the length? This is very important, next time when we add another element, we'll accidentally overwrite the one we just added!```

The second sentence implies that incrementing the length means that adding a new element will overwrite the previously added one, whereas that is what happens if you do NOT increment the length.

#### Expected behavior

Recommend changing the second sentence, perhaps to:
```Notice how we also incremented the length? This is very important, otherwise the next time we add another element we'll accidentally overwrite the one we just added!```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name or number.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by StephenHoust** [comment]
There is no problem number or name. It was an example problem discussed in the _Arrays 101_ module. I've attached a screenshot this time with red arrows pointing the navigational areas and a red box around the sentences I identified as issues.

![Arrays 101 Issue](https://user-images.githubusercontent.com/38192703/183723558-698e329f-fc53-4cf4-b57b-2ec9d9e3fcb4.png)
.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
