### ISSUE TITLE
Duplicate Test Cases - 1812. Determine Color of a Chessboard Square

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8593]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [1812. Determine Color of a Chessboard Square](https://leetcode.com/problems/determine-color-of-a-chessboard-square), there are duplicate test cases.

On a chessboard, there are 8 rows and 8 columns, so the number of squares is 8 × 8 = 64, which means there should be at most 64 test cases. However, there are 203 test cases for this problem now, which means one of the following possible cases.

1. There are duplicate test cases. That is to say, the same test case occur more than once.
2. If there are no duplicate test cases, then some test cases do not meet the constraints.

Neither case should be a normal case.

Need to make sure that there are no duplicate test cases and all test cases are valid.

Since the number of squares is 64, which is not large, all 64 squares' coordinates should be in the test cases exactly once.

#### Expected behavior
Remove duplicate test cases and make sure there are 64 test cases, which means each square's coordinates should be in the test cases exactly once.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
