### ISSUE TITLE
Incorrect Test case

### ISSUE THREAD

**Issue by aman-babu** [LeetCode-Feedback/LeetCode-Feedback#8596]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the incorrect test case, in which problem?
