### ISSUE TITLE
Missing Test Case - 417. Pacific Atlantic Water Flow

### ISSUE THREAD

**Issue by vmarunin** [LeetCode-Feedback/LeetCode-Feedback#8599]
#### Your LeetCode username
vmarunin

#### Category of the bug
- [+ ] Question
- [+] Solution
- [ ] Language
- [+] Missing Test Cases 

#### Description of the bug

It is not clear for me how to process island with lakes
For example, this test case [[2,2,2,2,3],[2,1,1,1,2],[2,1,5,1,2],[2,1,1,1,2],[3,2,2,2,2]]
Water from cell [2,2] (height 5) will flow to lake and, after it will flow to both oceans.
But test system does not return [2,2] as solution
I think it should be note about lakes in description or new test added

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Added explanations to all the examples to clarify . Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
