### ISSUE TITLE
777. Swap Adjacent in LR String - Missing test case

### ISSUE THREAD

**Issue by bagira-it** [LeetCode-Feedback/LeetCode-Feedback#86]
**What kind of the bug**
- [ ] problem
- [X] solution
- [ ] language

**Describe the bug**
Missing testcase.
My solution is accepted but it should not. Because it fails this simple test:
"RXX"
"RXL"

**what language is your code written in**
Java

**The code you submit/run**
```
class Solution {
    public boolean canTransform(String start, String end) {
        char state;
        int j = 0;
        for (int i = 0; i < start.length(); i++) {
            state = start.charAt(i);
            if (state == 'X') continue;
            // Try to find the corresponding state in end string
            while (j < end.length() && end.charAt(j) != state) {
                if (end.charAt(j) != 'X') return false;
                j++;
            }
            if (j == end.length()               // corresponding state not found
                    || (state == 'L' && j > i)  // L found in end string but to the right of the start L
                    || (state == 'R' && j < i)  // R found in end string but to the left of the start R
            ) return false;
            j++;
        }
        return (j == end.length() || end.charAt(j) == 'X') ? true : false;
    }
}
```

**Expected behavior**
Solution should not be accepted.

**Comment by CooperCooperCooper** [comment]
Hi @bagira-it,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @bagira-it,
Thank you for your time! Base on your feedback, we've added more test cases to this problem. We appreciate your support! Please reach out to us on the technical support channel to claim your reward!
