### ISSUE TITLE
My code passes the test case with "Run Code" but not with "Submit"

### ISSUE THREAD

**Issue by timoderbeste** [LeetCode-Feedback/LeetCode-Feedback#860]
#### Your LeetCode username

skydiving94

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

On this test case, 
"aaaaaaa"
["aaaa","aaa"],
The output of my code with "Run Code" is ["aaa aaaa","aaaa aaa"], while with submission is ["aaa aaaa"]. I do not understand this discrepancy. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    
    sentsTable = dict()
    def wordBreak(self, s: str, wordDict: List[str]) -> List[str]:
        subResults = []
        found = False
        if s not in self.sentsTable:
            self.sentsTable[s] = dict()
        for i in range(1, len(s) + 1):
            if s[:i] in wordDict:
                # print(s[:i], s[i:])
                if i < len(s):
                    if i not in self.sentsTable[s]:
                        sents = self.wordBreak(s[i:], wordDict)
                        self.sentsTable[s][i] = sents
                    else:
                        sents = self.sentsTable[s][i]
                    subResults.append((s[:i], sents))
                else:
                    subResults.append((s[:i], []))
                found = True
        
        if not found:
            return []
        
        ret = set()
        for subResult in subResults:
            word, sents = subResult
            print(subResult)
            if sents:
                for sent in sents:
                    ret.add((word + ' ' + sent).strip(' '))
            elif word == s:
                ret.add(word)
            else:
                continue        
        return list(ret)
```

#### Expected behavior

The output of my code with "Run Code" should be consistent with the output from running "Submit". 

#### Screenshots

<img width="2160" alt="Bildschirmfoto 2020-08-25 um 11 19 05 PM" src="https://user-images.githubusercontent.com/7350056/91255185-d1ef0780-e729-11ea-8091-7a68cbab3b87.png">

**Comment by lc-pam** [comment]
Hi @timoderbeste 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
