### ISSUE TITLE
Missing Test Case - 77. Combinations

### ISSUE THREAD

**Issue by matiaspub** [LeetCode-Feedback/LeetCode-Feedback#8600]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Wrong condition in the question description.
Seems should be “in the range”, not “ of k numbers out of the range”.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
