### ISSUE TITLE
658. Find K Closest Elements- Missing test case 

### ISSUE THREAD

**Issue by xxiaomm** [LeetCode-Feedback/LeetCode-Feedback#8603]
#### Your LeetCode username

Micca_Xx

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I submitted my solution and it was accepted. But I considered a test case and run it with my code, it gave the wrong result.  
So I think there must miss some test cases for this question.

#### Code you used for Submit/Run operation

```
class Solution {
    public List<Integer> findClosestElements(int[] nums, int k, int x) {
        int l = 0, r = nums.length - 1;
        int minIndex = -1, min = Integer.MAX_VALUE;
        while (l <= r) {
            int mid = l + (r - l)/2;
            int abs = Math.abs(nums[mid] - x);
            if (nums[mid] == x) {
                minIndex = mid;
                min = 0;
                break;
            } else if (nums[mid] > x) 
                r = mid - 1;
            else
                l = mid + 1;
            if (abs < min) {
                min = abs;
                minIndex = mid;
            }    
        }
        
        List<Integer> res = new LinkedList<>();
        l = minIndex;
        r = minIndex+1;
        while (k > 0) {
            int abs1 = l >= 0 ? Math.abs(x - nums[l]) : Integer.MAX_VALUE;
            int abs2 = r < nums.length ? Math.abs(x - nums[r]) : Integer.MAX_VALUE;
            if (abs1 <= abs2)
                res.add(0, nums[l--]);
            else
                res.add(nums[r++]);
            k--;
        }
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Add my test case and consider some corner cases.
The test case that I use is :
```java
[1,25,35,45,50,59]
1
30
```
#### Screenshots

![image](https://user-images.githubusercontent.com/35066934/183765766-925034dc-0b91-4e0e-a2cd-6fd4a42a6507.png)
![image](https://user-images.githubusercontent.com/35066934/183765878-e33cbc69-e196-462a-ba3b-3a35014ce7e3.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
