### ISSUE TITLE
Leetcode 450. Delete Node in a BST solution code error

### ISSUE THREAD

**Issue by jackson-cmd** [LeetCode-Feedback/LeetCode-Feedback#8605]
#### Your LeetCode username

jackson-cmd

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution for Leetcode 450 has two errors. In **Three facts to know about BST** section, there are two functions `successor` and `predecessor`, it should return an int, not a TreeNode.

#### Code you used for Submit/Run operation

```
public int successor(TreeNode root) {
  root = root.right;
  while (root.left != null) root = root.left;
  return root.val;
} 
public int predecessor(TreeNode root) {
  root = root.left;
  while (root.right != null) root = root.right;
  return root.val;
} 
```

#### Language used for code

Java

#### Expected behavior

```
public int successor(TreeNode root) {
  root = root.right;
  while (root.left != null) root = root.left;
  return root.val;
} 
public int predecessor(TreeNode root) {
  root = root.left;
  while (root.right != null) root = root.right;
  return root.val;
} 
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by jackson-cmd** [comment]
BTW, I think it is fixed by now. Will I get the LeetCoin for it? Thanks!
