### ISSUE TITLE
Missing Test Case - 108. Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by manozjinagal** [LeetCode-Feedback/LeetCode-Feedback#8609]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [. ] Missing Test Cases 

#### As mentioned in the question  height-balanced binary tree is a binary tree in which the depth of the two subtrees of every node never differs by more than one. 
so for the test case 
[0,1,2,3,4,5] results should be accepted if the binary tree is height balanced even if it differ by one. 

my result is [3,2,4,1,null,null,5,0] (this should be accepted too.)
and expected result is [3,1,5,0,2,4]

#### Code you used for Submit/Run operation

```
class Solution {
    public TreeNode sortedArrayToBST(int[] nums) {
        int len = nums.length/2;
        TreeNode t = new TreeNode(nums[len]);
        TreeNode ans = t, l = t, r = t;
        if(nums.length == 2){
            t.left = new TreeNode(nums[0]);
            return ans;
        }
        int i=len-1,j=len+1;
   //     System.out.println(i+"  "+j+"   "+len);
        while(i>=0 && j<nums.length){
  //          System.out.println("this");
            l.left = new TreeNode(nums[i]);
            l = l.left;
            r.right = new TreeNode(nums[j]);
            r = r.right;
            i--;
            j++;
        }
    //    System.out.println(i+"  "+j+"    "+len);
        if(i== 0){
            l.left = new TreeNode(nums[i]);
        }
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

for test case no: 5, [0,1,2,3,4,5],
this answer should be accepted. [3,2,4,1,null,null,5,0] as it is also height balanced BST.

#### Screenshots

<img width="1256" alt="Screenshot 2022-08-10 at 11 52 01 AM" src="https://user-images.githubusercontent.com/63463176/183829818-0d19ae45-a3d3-4c48-bb12-2fedd3cc357d.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
