### ISSUE TITLE
745. Prefix and Suffix Search [Description not clear]

### ISSUE THREAD

**Issue by devenps** [LeetCode-Feedback/LeetCode-Feedback#861]
#### Your LeetCode username

devenps

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The description of the question is not clear. It doesn't explain the **"Maximum Weight"** definition.

> Design a class WordFilter that supports one function, WordFilter.f(String prefix, String suffix). It will return the word with given prefix and suffix ```with maximum weight```. If no word exists, return -1.

I am unable to understand how to calculate the maximum weight here in this question.

#### Expected behavior

Please define the meaning of ```maximum weight```. This question can't be solved without maximum weight definition.

**Comment by lc-ivan** [comment]
Hi @devenps ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @devenps ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
