### ISSUE TITLE
第27题实例的预期答案有误

### ISSUE THREAD

**Issue by lscsob** [LeetCode-Feedback/LeetCode-Feedback#8610]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
[lscissob](https://leetcode.cn/u/lscissob/)

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
27. 移除元素，控制台示例2
输入为 [0,1,2,2,3,0,4,2] 2
现预期结果为 [0,1,4,0,3] 
正确的预期结果为 [0,1,3,0,4]
同样的代码提交的话是正确的

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public int removeElement(int[] nums, int val) {
        int p = 0;
        int q = 0;
        int len = nums.length;
        int count = 0;

        while (q < len) {
            if (q < len && nums[q] == val) {
                q++;
                count++;
            } else {
                nums[p] = nums[q];
                p++;
                q++;
            }
        }

        return len - count;
    }
}
```

**期望行为**
示例2的预期结果改为 [0,1,3,0,4]

**屏幕截图**
![2022-08-10_145910](https://user-images.githubusercontent.com/20753710/183836011-80d0505f-117c-4463-bf6f-023e944c9c07.png)

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
题目描述和示例明确说明了元素可以按任意顺序，请仔细读题。
