### ISSUE TITLE
Missing Test Case - 154. Find Minimum in Rotated Sorted Array II

### ISSUE THREAD

**Issue by rajatsekhon** [LeetCode-Feedback/LeetCode-Feedback#8613]
#### Category of the bug
- [ ] Question
- [# ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
def findMin(self, arr: List[int]) -> int:
        return min(arr)
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by rajatsekhon** [comment]
Language used: python3
missing test cases: test cases designed are not judjing the code as per time complexity requirement.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. To fail O(n) solutions and only pass O(logn), we need to have arrays as large as 10^7, in significant numbers. It is not possible to generate such a test set. If you have any ideas, we are open to listen. We appreciate your support!
