### ISSUE TITLE
Missing Test Case - 496. Next Greater Element I

### ISSUE THREAD

**Issue by ankit332000** [LeetCode-Feedback/LeetCode-Feedback#8615]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

Input:
[2,4]
[1,2,3,4]
Output:
[2,-1]
Expected:
[3,-1]

WHY IS THIS 3 for 2

**Comment by ankit332000** [comment]
WHY IS THIS 3 It should be na 2

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
