### ISSUE TITLE
36. Valid Sudoku | Result after submitted is not same as the result of running code in online editor with a same test case

### ISSUE THREAD

**Issue by MoiTempete** [LeetCode-Feedback/LeetCode-Feedback#8616]
#### Your LeetCode username

MoiTempete

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Result during Run Code not equals with result during submit in a same test case.
In test case 347 / 507 which input is a char[][] :
[[".","8","7","6","5","4","3","2","1"],
["2",".",".",".",".",".",".",".","."],
["3",".",".",".",".",".",".",".","."],
["4",".",".",".",".",".",".",".","."],
["5",".",".",".",".",".",".",".","."],
["6",".",".",".",".",".",".",".","."],
["7",".",".",".",".",".",".",".","."],
["8",".",".",".",".",".",".",".","."],
["9",".",".",".",".",".",".",".","."]]
Run code in online editor, output is true and expected is true.
But when I submit code, in online judge, it return 'Wrong Answer' cause output is false but expceted is true with the same test case 

#### Code you used for Submit/Run operation

```
class Solution {
    
    static HashMap<String, String> rouMap = new HashMap<>();
    static HashMap<String, String> columnMap = new HashMap<>();
    static HashMap<String, String> boxMap = new HashMap<>();

    public static boolean isValidSudoku(char[][] board) {
        boolean rowUnique;
        boolean columnUnique;
        boolean boxUnique;
        String rowIndex;
        String columnIndex;
        String boxIndex;
        String var;

        for (int row = 0; row < 9; row++) {
            for (int column = 0; column < 9; column++) {
                var = String.valueOf(board[row][column]);
                if (".".equals(var)) {
                    continue;
                }
                rowIndex = "row" + row + ":" + var;
                columnIndex = "column" + column + ":" + var;
                boxIndex = "box" + row / 3 + column / 3 + ":" + var;

                rowUnique = !rouMap.containsKey(rowIndex);
                columnUnique = !columnMap.containsKey(columnIndex);
                boxUnique = !boxMap.containsKey(boxIndex);

                if (!rowUnique || !columnUnique || !boxUnique) {
                    return false;
                }
                rouMap.put(rowIndex, var);
                columnMap.put(columnIndex, var);
                boxMap.put(boxIndex, var);
            }
        }

        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

result after submitted should be same with the result of running code in online editor with a same test case

#### Screenshots

![leetcode_36](https://user-images.githubusercontent.com/1124516/183949210-42a25420-a1b5-4794-a7a5-c54efbe20852.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!


When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by MoiTempete** [comment]
> Thank you for reaching out to us!
> 
> When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
> 
> Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

OK, got it. THX
