### ISSUE TITLE
601 本地无法正常执行。

### ISSUE THREAD

**Issue by DamengLiu** [LeetCode-Feedback/LeetCode-Feedback#8619]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
同样的代码可以提交成功，但在本地执行出错。

**你提交或者运行的代码**
```
select id, visit_date, people
from(
    select *,count(*)over(partition by t_rank) t2_rank
    from (
        select *,id-row_number() over(order by id) t_rank
        from stadium  
        where people > 99
        ) t
    ) t2
where t2.t2_rank>2
order by id;
```

**期望行为**
可以在本地正常执行，调试自己的代码。

**屏幕截图**
![11](https://user-images.githubusercontent.com/39763537/184042348-fa2e4b23-bb42-4077-bc37-11624a538012.jpg)

**Comment by BrambleWave** [comment]
如果出现测试用例结果和提交结果不一致的情况，您可以再仔细检查并调试您的代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」获得更多帮助。
同时您也可以点击「题解」来查看当前题目的解题思路，或点击这里「[讨论](https://leetcode.cn/circle/discussions/questions)」，将您的疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
