### ISSUE TITLE
134. Gas Station - Each example have different logic.

### ISSUE THREAD

**Issue by EranAAA** [LeetCode-Feedback/LeetCode-Feedback#8621]
#### Your LeetCode username
avichzer

#### Category of the bug
- [ #] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Example one:
get the distance at cost(i)

Example two:
get the distance at cost(i+1)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
