### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by amit-sahu09** [LeetCode-Feedback/LeetCode-Feedback#8623]
#### Your LeetCode username 

 amit_sahu_official

#### Category of the bug
- [x] Question Valid Parentheses
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The bug appears in the test case "([" where it is accepted by the run code option, but on submitting shows wrong answer for exactly the same case, with no modifications done to the code.

#### Code you used for Submit/Run operation

```
class Solution {
public:
 
    bool isValid(string s) {
        int size=s.size(),sz=0;
        stack<char> st;
        char ch;
        for(int i=0;i<size;i++)
        {
            sz=st.size();
            cout<<sz;
            if(sz!=0)
            {
                switch(s[i])
                {
                    case ')':ch='(';
                        break;
                    case ']':ch='[';
                        break;
                    case '}':ch='{';
                        break;
                }
                if(ch==st.top())
                {
                    //cout<<ch<<ch;
                    st.pop();
                    //cout<<sz;
                }
                else
                    st.push(s[i]);
            }
            else
                st.push(s[i]);
        }
        sz=st.size();
        if(sz==0)
            return 1;
        else
            return 0;
    }
};
```

#### Language used for code

C++

#### Expected behavior
 The code is supposed to completely run as it is correct, but what happened is that it is giving me an error for a case which it is not giving using run code option.

#### Screenshots

![Screenshot from 2022-08-11 16-04-39](https://user-images.githubusercontent.com/72920084/184116234-9cb970ae-2d14-4741-a943-0a05a2e1f3a6.png)
![Screenshot from 2022-08-11 16-12-17](https://user-images.githubusercontent.com/72920084/184116685-97b1a0af-ceef-43e5-b9cf-f54744df30d5.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by amit-sahu09** [comment]
I have checked the code for the issues described by the article and i have none of those issues.
