### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by RealTonyStark** [LeetCode-Feedback/LeetCode-Feedback#8624]
#### Your LeetCode username

andrecrow

#### Category of the bug
- [ ] Description is incorrect

#### Description of the bug

Your description says:

Example 1:

Input: height = [1,8,6,2,5,4,8,3,7]
Output: 49
Explanation: The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. In this case, the max area of water (blue section) the container can contain is 49.

While the Output should be 29. The picture in example is correct, while the answer(Output) is not.

**Comment by stormsunshine** [comment]
Why should the output be 29? How do you get 29?

**Comment by RealTonyStark** [comment]
![изображение](https://user-images.githubusercontent.com/10960120/184138016-6403d793-7b43-4ee1-9718-a10c67bd2065.png)

Container with most water is the one that formed with second (8) and ninth (7) elements of the given array. Look at the picture in the task. Am I missing something?

**Comment by RealTonyStark** [comment]
Oh, I see. The answer is the amount of water, not the indices. Sorry for misunderstanding
