### ISSUE TITLE
Missing Test Case - 300. Longest Increasing Subsequence

### ISSUE THREAD

**Issue by GSMgeeth** [LeetCode-Feedback/LeetCode-Feedback#8625]
#### Your LeetCode username
gsm_geeth

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem submission shows that test case [7,7,7,7,7,7,7] is expected to have the answer 1 but got 4. When I run the same test case with the same code in Editor console, it works correctly and give the answer 1 as expected.

#### Code you used for Submit/Run operation

```
class Solution {
    static int lengthOfLIS;
    
    public int lengthOfLIS(int[] nums) {
        lis(nums, nums.length);
        
        return lengthOfLIS;
    }
    
    public int lis(int[] arr, int n)
    {
        if (n == 1)
            return 1;

        int res;
        int maxEndingHere = 1;

        for (int i = 1; i < n; i++) {
            res = lis(arr, i);

            if (arr[i - 1] < arr[n - 1] && res + 1 > maxEndingHere) {
                maxEndingHere = res + 1;
            }
        }

        if (lengthOfLIS < maxEndingHere)
            lengthOfLIS = maxEndingHere;

        return maxEndingHere;
    }
}
```

#### Language used for code
Java

#### Expected behavior
I expected the code to pass the same test case as it pass in the console.

#### Screenshots
![Uploading Screen Shot 2022-08-11 at 16.48.00.png…]()
![Uploading Screen Shot 2022-08-11 at 16.47.20.png…]()

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
