### ISSUE TITLE
409

### ISSUE THREAD

**Issue by tonysprite** [LeetCode-Feedback/LeetCode-Feedback#8626]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode tonysprite**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ 409] [最长回文串](https://leetcode.cn/problems/longest-palindrome/)
- [f] 题解
- [ go] 编程语言
- [x] 缺少测试用例

**描述**
最长回文字符串的这个文题并没有说明对于奇数长度的字符是否要做非最长奇数字符的处理提示，从示例显示来看会误以为保留最长的奇数的字符和所有偶数长度的字符即可满足需求。
根据实际测试并不能通过该题的测试校验脚本。因此该题存在描述不清楚的嫌疑。

**你使用的语言**
C++

**你提交或者运行的代码**
```
unc longestPalindrome(s string) int {

    var chars=make(map[byte]int,len(s))
    for i:=0;i<len(s);i++{
        if _,ok:=chars[s[i]];ok{
            chars[s[i]]=chars[s[i]]+1
        }else{
            chars[s[i]]=1
        }
    }
    doubleLen:=0
    maxSingleLen:=0
    for _,v:= range chars{
        if v%2==0{//偶数的都可以组成回文，直接叠加长度
            doubleLen=doubleLen+v
        }else {
            //奇数的需要找到最大奇数字符
            if v>maxSingleLen{
                maxSingleLen=v
            }
        }
    }
    //返回所有的偶数字符长度和最长奇数字符的长度之和
    return maxSingleLen+doubleLen
} 
```

**期望行为**
输入字符串
"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth"
返回
655

**屏幕截图**
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/8165354/184130390-b2d64084-eb0a-4b38-a630-a75894b8dc7f.png">

**额外的上下文**
https://leetcode.cn/submissions/detail/348976485/

**Comment by tonysprite** [comment]
按照现有提示 默认应该不计算非最长奇数字符才符合题目字面含义，否则建议增加多个长度奇数的示例加以说明，
示例4：
输入:s = "bbeeefffffdd"
输入: 11

**Comment by feiceh** [comment]
您好，在与相关团队核实后：本题暂不作调整。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
