### ISSUE TITLE
1419 - Missing Test Case / 缺少测试用例

### ISSUE THREAD

**Issue by Levia1h4n** [LeetCode-Feedback/LeetCode-Feedback#8629]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名: levia1h4n

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
[1419. 数青蛙](https://leetcode.cn/problems/minimum-number-of-frogs-croaking/) 
测试用例: `"croakcraok"` 会hack掉提交记录中最快的范例(76ms / python3)

**你使用的语言**
python3

**你提交或者运行的代码**
```
// 1419 - minimum-number-of-frogs-croaking / 范例代码
class Solution:
    def minNumberOfFrogs(self, croakOfFrogs: str) -> int:
        strs = croakOfFrogs
        if strs.count('c') == strs.count('r') == strs.count('o') == strs.count('a') == strs.count('k') and strs.find('c') < strs.find('r') < strs.find('o') < strs.find('a') < strs.find('k'):
            now, res = 0, 0
            for i in strs:
                if i=='c':
                    now+=1
                    res=max(res,now)
                elif i=='k':
                    now-=1
            return res
        else:
            return -1
```

**期望行为**
运行测试用例 `"croakcraok"`, 输出-1

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/56862963/184181489-d8153271-ff91-42f6-ac99-058d0c4e511c.png">

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
这份代码已经不能提交通过了，该测试用例已经存在。提交记录中有这份代码不等于现在这份代码依然能提交通过。

**Comment by Levia1h4n** [comment]
你说的对😯 不能通过了, 我以为我测试过了...
