### ISSUE TITLE
Got LTE but AC on the second submit

### ISSUE THREAD

**Issue by resotto** [LeetCode-Feedback/LeetCode-Feedback#8631]
#### Your LeetCode username

resotto

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When I submit the following code on https://leetcode.com/explore/learn/card/dynamic-programming/631/strategy-for-solving-dp-problems/4146/, I got LTE.
On the second submit, I got AC. So this may be a bug on platform side.

#### Code you used for Submit/Run operation
```java
class Solution {
private int[] nums;
private int[] muls;

public int maximumScore(int[] nums, int[] multipliers) {
	// time: O(N * M) where N is length of nums and M is length of multipliers
	// space: O(N * M)
	if (nums == null || multipliers == null || nums.length == 0 || multipliers.length == 0) {
		return 0;
	}
	this.nums = nums;
	this.muls = multipliers;
	var n = nums.length;
	var m = multipliers.length;
	var memo = new Integer[m][n];
return dfs(0, nums.length-1, 0, memo);
}

private int dfs(int l, int r, int i, Integer[][] memo) {
	if (i == muls.length) {
		return 0;
	} else if (memo[i][l] != null) {
		return memo[i][l];
	}
	memo[i][l] = Math.max(nums[l] * muls[i] + dfs(l+1, r, i+1, memo), nums[r] * muls[i] + dfs(l, r-1, i+1, memo));
	return memo[i][l];
}
}
```

#### Language used for code
Java

#### Expected behavior
There should be no LTE but got it once.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. 
The submission is resulting in TLE for possibly one of the following reasons:
Code has an underlying infinite loop.
Algorithm is too slow and has high time complexity.
We will investigate this issue, thank you for your support.

**Comment by resotto** [comment]
I got LTE with the same code with which I got AC.
It's Not code issue itself.
