### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by iabhay** [LeetCode-Feedback/LeetCode-Feedback#8633]
#### Your LeetCode username

Abhay_Agrawal

#### Category of the bug
- [x] Solution
- [x] Language

#### Description of the bug

I am facing issues of wrong output even when the code is correct. Code tried on other compilers and it ran successfully. But, Leetcode IDE has issues with the wrong Output.

#### Code you used for Submit/Run operation

```
//Contains Duplicate
class Solution {
    public boolean containsDuplicate(int[] nums) {
        HashSet <Integer> set = new HashSet<>();
        boolean res = false;
        for(int i = 0; i<nums.length-1;i++){
            if(set.contains(nums[i])){
                res = true;
            }
            set.add(nums[i]);
        }
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I expect it to give the correct output on given test cases.
Test Case - [1,2,3,1]

#### Screenshots

![image](https://user-images.githubusercontent.com/73734837/184322097-e3a784da-d71d-44b3-a8f2-f4870bde6533.png)

**Comment by LC-Pam** [comment]
Hi there, thank you for reaching out to us. When we submitted your code, we received Wrong Answer, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes![
](https://leetcode.com/problems/contains-duplicate/discuss/60937/3ms-Java-Solution-with-Bit-Manipulation)
[
](https://leetcode.com/problems/contains-duplicate/discuss/1500880/Java-or-TC%3A-O(N)-or-SC%3A-O(N)-or-Clean-and-concise-solution-using-HashSet)

The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.

We appreciate your time and support! If you have any other questions, please don't hesitate to let us know.
