### ISSUE TITLE
What Is an Array? - Bad analogy

### ISSUE THREAD

**Issue by TakeThisCoin** [LeetCode-Feedback/LeetCode-Feedback#8634]
https://leetcode.com/explore/learn/card/fun-with-arrays/521/introduction/3236/#:~:text=It%27s%20exactly%20the%20same%20with%20the%20Array%2C%20where%20the%20space%20in%20your%20home%20is%20analogous%20to%20memory%20on%20the%20computer.

Text: "It's exactly the same with the Array, where the space in your home is analogous to memory on the computer. If you make an Array with 1000000 spaces, the computer will reserve memory to hold 1000000 DVDs, even if you only put 15 DVDs into it. That memory can't be used for anything else in the meantime—just like the space in your house that has been taken over by that huge cardboard box!"

I think, need to come up with another analogy. Analogy in the text is bad. I will give an example.
We have a class, we can create an object that will occupy 1 MB of memory. There is a link to an object that, for example, will weigh 8 bytes.
When we create an array "DVD [] dvdcollection = New DVD [15];". We create an array of 15 links, a reserved place 8 * 15 = 120 bytes. We do not reserve 1 * 15 = 15 MB. From an analogy in text that is written it follows that we reserve a place for objects, not for links.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem and considered it invalid. 

It's too early to introduce the concept of reference/pointer in Array 101. If we adopt the user-suggested analogy, the beginners could be tangled with the word "link".
References can be regarded as objects, which still take up space. new DVD [SIZE] will be allocated some bytes for the header and SIZE times of object reference size. If we consider the reference as the DVD instance itself, it is what the original text says.
We can add a paragraph to explain that the value in the array is actually a reference, not the object itself. But we wonder if it will make more entry-level users feel strange.

 We appreciate your support!
