### ISSUE TITLE
269. Alien Dictionary, test case ["abc","ab"] is invalid (Reopened)

### ISSUE THREAD

**Issue by enomis101** [LeetCode-Feedback/LeetCode-Feedback#8635]
The problem description states:
You are given a list of strings words from the alien language's dictionary, where the strings in words are sorted lexicographically by the rules of this new language.

So the case ["abc","ab"] is wrong, the problem does not specify that if the words are in the wrong order return ""

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.The problem mentions
If there is no solution, return "".
The problem statement is correct. We appreciate your support!

**Comment by delf1** [comment]
The problem statement also mentions:
"You are given a list of strings words from the alien language's dictionary, where the strings in words are sorted lexicographically by the rules of this new language."

The input ["abc","ab"] does not meet the definition of lexicographical sorting defined in the question:
"A string s is lexicographically smaller than a string t if at the first letter where they differ, the letter in s comes before the letter in t in the alien language. If the first min(s.length, t.length) letters are the same, then s is smaller if and only if s.length < t.length."

s = "abc"
t = "ab"
min(s.length, t.length) = 2
this implies s.length < t.length
but here s.length > t.length

This test case is invalid and should be removed.
