### ISSUE TITLE
Missing Test Case - 503. Next Greater Element II

### ISSUE THREAD

**Issue by lostlang** [LeetCode-Feedback/LeetCode-Feedback#8636]
#### Your LeetCode username
lostlang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Description:

Given a circular integer array nums (i.e., the next element of **nums[nums.length - 1] is nums[0]**), return the next greater number for every element in nums.

Example 2:
```
Input: nums = [1,2,3,4,3]
Output: [2,3,4,-1,4]
```

#### Expected behavior
Example 2:
```
Input: nums = [1,2,3,4,3,1]
Output: [2,3,4,-1,4,2]
```

or 

Description:

Given a circular integer array nums (i.e., the next element of nums[nums.length - 1] is nums[0] **etc**), return the next greater number for every element in nums.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
