### ISSUE TITLE
739. 每日温度，测试数据太简单

### ISSUE THREAD

**Issue by x-xk** [LeetCode-Feedback/LeetCode-Feedback#8639]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
‭别哇了行吗

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ *] 缺少测试用例

**描述**
[739. 每日温度](https://leetcode.cn/problems/daily-temperatures/)，测试数据太简单

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    public int[] dailyTemperatures(int[] temperatures) {
        int n = temperatures.length;
        int[] ret = new int[n], max = new int[2];
        max[0] = temperatures[n - 1]; max[1] = n - 1;
        for(int i = n - 2; i >= 0; i--) {
            if(max[0] > temperatures[i]) {
                for(int j = i + 1; j <= max[1]; j++) {
                    if(temperatures[j] > temperatures[i]) {
                        ret[i] = j - i;
                        break;
                    }
                }        
            } else {
                ret[i] = 0;
            }
            if(temperatures[i] >= max[0]) {
                max[0] = temperatures[i];
                max[1] = i;
            }
        }
        return ret;
    }
}
```

**期望行为**
测试数据不够极限，1 <= temperatures.length <= 10^5。上面的代码现在能够通过，但是不能通过这样的数据——>前面10^5 - 1个数全部是小于最大值的相同数，最后一个数是所有数中的最大值。

希望添加的测试数据：
[99999个50,100]

**屏幕截图**
![image](https://user-images.githubusercontent.com/76646296/184470611-0ac6ade9-7738-43a2-b470-eb7b8f13b8f5.png)

**额外的上下文**
![image](https://user-images.githubusercontent.com/76646296/184470616-26d16321-9d8d-4b45-ade7-752701554287.png)

**Comment by x-xk** [comment]
**希望添加的测试数据**
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9330914/test.txt)

**Comment by BrambleWave** [comment]
不予采纳，这道中等题不需要卡的这么苛刻，原则上我们也允许暴力通过。
但是为感谢您对我们的支持，我们已向您发送奖励积分。
