### ISSUE TITLE
687. Longest Univalue Path

### ISSUE THREAD

**Issue by hrchu** [LeetCode-Feedback/LeetCode-Feedback#864]
1. Edge case ambiguous: both outputs of [], [1] will be 0
2. Example incorrect: the output of the second example should be 3 instead of 2.

**Comment by lc-pam** [comment]
Hi @hrchu 
Thank you for reaching out to us. I've used the official solution to test both [],[1] and received 0 as output. Please let me know if you see differently on your end or kindly provide more explanation if I misunderstood your request. As for your second point, I recommend you raise your question or find similar question in the [problem's discuss tab].(https://leetcode.com/problems/longest-univalue-path/discuss/?currentPage=1&orderBy=newest_to_oldest&query=)
