### ISSUE TITLE
剑指 Offer 03. 数组中重复的数字，缺少测试数据

### ISSUE THREAD

**Issue by x-xk** [LeetCode-Feedback/LeetCode-Feedback#8640]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
‭别哇了行吗

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [* ] 缺少测试用例

**描述**
[剑指 Offer 03. 数组中重复的数字](https://leetcode.cn/problems/shu-zu-zhong-zhong-fu-de-shu-zi-lcof/)，缺少测试数据

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    public int findRepeatNumber(int[] nums) {
        for(int num : nums) {
            if(nums[Math.abs(num)] < 0) {
                return Math.abs(num);
            }
            nums[Math.abs(num)] *= -1;
        }
        return 0;
    }
}
```

**期望行为**
添加测试用例：[1, 0, 1, 4, 2, 5, 3]

**屏幕截图**
![image](https://user-images.githubusercontent.com/76646296/184472253-ee4f0bbd-b130-490e-86bd-f38f89ccfe7e.png)

**额外的上下文**
![image](https://user-images.githubusercontent.com/76646296/184472406-81717327-71ff-4c1a-adbd-3e09c553dcf8.png)

**Comment by BrambleWave** [comment]
你好，当前该题已添加测试用例，奖励已发放。
