### ISSUE TITLE
Irrelevant Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by sumit334** [LeetCode-Feedback/LeetCode-Feedback#8641]
#### Your LeetCode username
Sumit_334JUIT

#### Category of the bug
- [ ] Question -50.Pow(x,n)
- [ ] Solution 
- [ ] Language -All
- [ ] Irrelevant Test Cases - x=0.0000 , n=0 output- 1 , but it is undefined.

#### Description of the bug

Actually, the simple error in this problem is in one of it's test case, ie, for input, as x=0.0000 and, n=0 , I got an output 1 which infact violets the mathematics , as 0^0 is undefined so the test case must not contain this as a testcase, because it would teach us some misconceptions in maths.

#### Code you used for Submit/Run operation

```
// Pow(x,n)
class Solution {
    public double myPow(double x, int n) {
        if(x==-1.0000 && n%2!=0){
            return -1.0000;
        }
        if(x==-1.0000 && n%2==0){
            return 1.0000;
        }
        if(x==1.0000){
            return 1.0000;
        }
        if(n<-2147483644){
            return 0.0000;
        }
        if(n<0){
            n=-n;
            x=1/x;
        }
        if(n==0){
            return (double)1;
        }
        if(n%2==0){
            return (double)myPow(x*x,n/2);
        }
        else{
            return (double)myPow(x*x,n/2)*x;
        }
    }
}
```

#### Language used for code

Java

#### Expected behavior
![Screenshot from 2022-08-13 11-56-52](https://user-images.githubusercontent.com/97662774/184472302-2e1ea6d9-5959-42af-afb1-339c97df6f5b.png)

I got an output 1 which infact violets the mathematics , as 0^0 is undefined so the test case must not contain this as a testcase, because it would teach us some misconceptions in maths.
I expected that this input must not be included in the testcase of the problem , but it was included there.

#### Additional context

Please review my context on the bug .

**Comment by stormsunshine** [comment]
Actually, the test cases where x = 0 and n ≤ 0 are not included for submission check, but the test cases can be tested in custom test case.

These test cases are not valid and should be forbidden in custom test cases. I suggest that one of the following ways should be used.
1. When x = 0, do not allow negative values of n.
2. Require that x is a non-zero value. In this way, the constraints should be changed as well to require that x ≠ 0.

**Comment by sumit334** [comment]
> Actually, the test cases where x = 0 and n ≤ 0 are not included for submission check, but the test cases can be tested in custom test case.
> 
> These test cases are not valid and should be forbidden in custom test cases. I suggest that one of the following ways should be used.
> 
> 1. When x = 0, do not allow negative values of n.
> 2. Require that x is a non-zero value. In this way, the constraints should be changed as well to require that x ≠ 0.

Thank you for replying in my post , I am very glad to get myself cleared with the doubts.
I will do the same then.
