### ISSUE TITLE
Missing Test Case - 314. Binary Tree Vertical Order Traversal

### ISSUE THREAD

**Issue by DhavalPatodiya** [LeetCode-Feedback/LeetCode-Feedback#8644]
#### Your LeetCode username

Dhaval25

#### Category of the bug
- [314] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Submitting a hint for question:
Hint 1: Think of the tree in terms of table

#### Additional context

Submitting a hint for question

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
