### ISSUE TITLE
Missing Test Case - 30. Substring with Concatenation of All Words

### ISSUE THREAD

**Issue by RISHIKESH674** [LeetCode-Feedback/LeetCode-Feedback#8647]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?

**Comment by abyss-walker** [comment]
I want to contribute a test case for this question, but I'm not very familiar with Github. It's a big testcase so I can't submit it on Leetcode either. Can someone tell me the exact procedure for submitting a test case on Github?
