### ISSUE TITLE
30. Substring with Concatenation -- phrasing

### ISSUE THREAD

**Issue by mscuthbert** [LeetCode-Feedback/LeetCode-Feedback#8648]
#### Your LeetCode username

msacuthbert

#### Category of the bug
- [x] Question

#### Description of the bug

The description begins (emphasis added):

*You are given a string `s` and an array of strings `words` **of the same length**.*

There is an ambiguity of what is **of the same length** as what?

The correct interpretation from the examples and code is:

*and an array of strings `words` where every entry in `words` is the same length as every other entry in `words`, e.g. `words[i].length == words[j].length`.*

but here are two other plausible explanations of the phrasing:

*and an array of strings `words` where every entry in `words` is the same length as `s`, eg. `words[i].length == s.length`*

or

*and an array of strings `words` where the length of the array `words` is the same length as `s`, eg. `words.length == s.length`*

Leetcode justifiably prides itself in making the statement of the question unambiguous without looking at the examples (and usually without looking at the constraints).  So I hope this can be rewritten.

(P.S. thanks for the awesome fix of a previous issue I reported, #7636 -- looks GREAT now)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem statement and the examples. This point was already clear from the constraints.. We appreciate your support!
