### ISSUE TITLE
Missing Constraints 

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#865]
#### Your LeetCode username
Mkay6122

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        vector<int> k;
        for(int i=0;i<nums.size();i++)
            {
                for(int j=i+1;j<nums.size();j++)
                {
                    if(nums[i]+nums[j]==target)
                    {
                        
                        k.push_back(i);
                        k.push_back(j);
                        return k;
                    }
                }
            }
        return k;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

As asked in problem we have to find sum , we can use a vector of count to store index of each element but we are not provided with constraints so i cannot initialize a vector .

**Comment by lc-pam** [comment]
Hi @Mohitkumar6122 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Mohitkumar6122** [comment]
> Hi @Mohitkumar6122
> Thank you for reaching out to us. I've relayed this issue to our team to investigate.

Thanks for your quick service ..

**Comment by lc-pam** [comment]
Hi @Mohitkumar6122 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
