### ISSUE TITLE
662. Maximum Width of Binary Tree - Missing Test Case

### ISSUE THREAD

**Issue by Daniel-WR-Hart** [LeetCode-Feedback/LeetCode-Feedback#8652]
#### Your LeetCode username
omgitsmiketyson

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My solution was accepted, but I created a test case where it fails.
The code works by assigning ids to all nodes, and these ids describe how many nodes would be to the left of the current node if the tree was a perfect binary tree. To avoid an integer overflow, the ids are modulo ```M```, where ```M = (2**31) + 1```. This is fine when all nodes at the widest level are divisible by ```M``` by the same amount, but when they don't, the difference between the left-most id and the right-most id will no longer correspond to 1 less than the width of the tree at that given depth.

#### Code you used for Submit/Run operation
```
var widthOfBinaryTree = function(root) {
    const depthsForm = [];
    recurse(root);
    // console.log(depthsForm);
    
    let largestWidth = 0;
    // The Number() isn't necessary, it's just leftover from when I converted this solution
    // from a very similar one that used BigInt to handle very large ids instead of modulo
    depthsForm.forEach((depth) => largestWidth = Math.max(largestWidth, Number(depth.at(-1) - depth[0])));
    return largestWidth + 1;
    
    function recurse(root, depth = 0, id = 0) {
        if (!root) return;
        id = id % (2 ** 31) + 1; // wrap around, assuming answer can't be larger than the largest signed 32-bit int
        
        depthsForm[depth] = depthsForm[depth] ?? [];
        depthsForm[depth].push(id);
        // formula that guarantees that no two nodes at the same depth will have the same id, and the id describes their index at that depth if that depth was saturated
        recurse(root.left, depth + 1, id * 2);
        recurse(root.right, depth + 1, id * 2 + 1);
    }
}
```

#### Language used for code
JavaScript

#### Expected behavior
My custom test case should be added to prevent my solution from passing, which it currently does.

#### Additional context
Here is the failing test case that should be added. I chose its height specifically so that the bottom left node has an ```id < (2**31) + 1``` and the bottom right node has an ```id > (2**31) + 1```
```[1,1,1,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,1,null,null,1,null,1,null]```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
