### ISSUE TITLE
454. 4Sum II - If the number of arrays is odd

### ISSUE THREAD

**Issue by NoamGaash** [LeetCode-Feedback/LeetCode-Feedback#8654]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the second approach solution, in the complexity analysis, there's a mistake.
It suggest passing We will pass `k/2` arrays to `addToHash`, and `(k+1)/2` arrays to `kSumCount`, but the solution is passing `(k-1)/2`"> arrays to `addToHash`.

#### Code you used for Submit/Run operation

```javascript
// the code is irrelevant - submitted because asked.
var fourSumCount = function(nums1, nums2, nums3, nums4) {
    const res = new Map();
    let sum=0;
    for(let v1 of nums1) {
        for(let v2 of nums2) {
            const sum = v1+v2;
            if(res.has(sum)) {
                res.set(sum, res.get(sum)+1);
            } else {
                res.set(sum, 1);
            }
        }
    }
    for(let v1 of nums3) {
        for(let v2 of nums4) {
            const sum2 = -(v1+v2);
            if(res.has(sum2)) 
                sum += res.get(sum2);
        }
    }
    return sum;
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
