### ISSUE TITLE
提交问题

### ISSUE THREAD

**Issue by mini317** [LeetCode-Feedback/LeetCode-Feedback#8655]
![image](https://user-images.githubusercontent.com/90594513/184520237-a5246061-c705-4e29-8407-d6fae0c90d4d.png)

这个不该预期结果位987吗

**Comment by BrambleWave** [comment]
这个实际上只需要判断第一个被空格截断的字符串
"words and 987" 截取的是 words 所以返回 0
类似于 "1337leetcode"、"leetcode1337" "leet1337code" 均返回 0
