### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by anchi-007** [LeetCode-Feedback/LeetCode-Feedback#8657]
#### Your LeetCode username
anchalkmr007 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug
Wrong answer in one of the test cases 

#### Code you used for Submit/Run operation

```
// Three Sum
class Solution {
public:
  vector<vector<int>> threeSum(vector<int>& nums) {
    vector<vector<int>> ans;
    
    sort(nums.begin(), nums.end());
    int f = 0, n = nums.size();
    while(f < n-2) {
      int l = f+1, r = n-1;
      while(l < r) {
        if(l != f+1 && nums[l] == nums[l-1]) l++;
        if(r != n-1 && nums[r] == nums[r+1]) r--;
        else if(nums[f] + nums[l] + nums[r] == 0) {
          ans.push_back({nums[f], nums[l], nums[r]});
          l++, r--;
        }
        else if(nums[f] + nums[l] + nums[r] > 0) r--;
        else l++;
      }
      while(f < n-2 && nums[f] == nums[f+1]) f++;
      f++;
      if(nums[f] > 0) break;
    }
    return ans;
  }
};
```

#### Language used for code
C++ 

#### Expected behavior
In test case number 275 of the question [https://leetcode.com/problems/3sum/](url) , the expected solution includes a triplet [-2,1,1].
Test case number 275 : [-1,0,1,2,-1,-4,-2,-3,3,0,4]
The question clearly states that all the 3 numbers should be placed at unique indexes of the array.
In the given test case, there is only a single 1 present, hence any triplet cannot have multiple 1's present in it
This thus generates an extra invalid test case

#### Screenshots
![image](https://user-images.githubusercontent.com/77583725/184524782-1012a08c-f067-44b3-bc48-06efec04a3de.png)

**Comment by stormsunshine** [comment]
Your output contains an incorrect triple [-2,1,1]. The input array only contains one element 1, so your output is incorrect.

**Comment by anchi-007** [comment]
Got it thanks
