### ISSUE TITLE
852. Peak Index in a Mountain Array missing test case

### ISSUE THREAD

**Issue by 5CoolKids** [LeetCode-Feedback/LeetCode-Feedback#866]
#### Your LeetCode username

qq779716876

#### Category of the bug
Solution

#### Description of the bug

Wrong code passed all tests. 

#### Code you used for Submit/Run operation

public int peakIndexInMountainArray(int[] A) {
        if (A == null || A.length < 3) return -1;
        int left = 0, right = A.length - 1;
        while (left <= right) {
            int mid = left + (right - left) / 2;
            if (A[mid] > A[mid - 1] && A[mid] > A[mid + 1]) return mid;
            else if (A[mid] > A[mid - 1]) left = mid + 1;
            else right = mid - 1;
        }
        return -1;
}

#### Language used for code
Java

#### Expected behavior

failed the case [3,5,3,2,0]

**Comment by lc-ivan** [comment]
Hi @5CoolKids ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @5CoolKids ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
