### ISSUE TITLE
Missing test case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by nikolaynag** [LeetCode-Feedback/LeetCode-Feedback#8661]
#### Your LeetCode username
nikolaynag

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is an approach with O(n) time and O(1) space [which passes all tests](https://leetcode.com/submissions/detail/773253410/), but is actually wrong. The idea is that each node should have a counterpart node with the same value and equal distance from the center of the list (excluding of course the central node if there is a odd number of nodes). So it seems that we could just find the sum of distances from the center of the list for each node value and check that it is 0. Taking in account the constrain `0 <= Node.val <= 9` it would use O(1) space. 

But this approach gives a wrong result for the following test case:
```
[2,3,3,2,3,2,2,3]
```
This is obviously not a palindrome, but indexes are balanced and described approach gives a wrong answer.

#### Code you used for Submit/Run operation
```golang
/**
 * Definition for singly-linked list.
 * type ListNode struct {
 *     Val int
 *     Next *ListNode
 * }
 */
func isPalindrome(head *ListNode) bool {
    balance := map[int]int{}
    n := 0
    for ptr := head; ptr != nil; ptr = ptr.Next {
        n++
    }    
    i := 0
    for ptr := head; ptr != nil; ptr = ptr.Next {    
        if i*2 == n-1 {
            i++
            continue
        }
        if i*2 < n-1 {
            balance[ptr.Val] += (n-1) - i*2
        } else {
            balance[ptr.Val] -= i*2 - (n-1)
        }
        i++
    }
    for _, v := range balance {
        if v != 0 {
            return false
        }
    }
    return true
}
```
#### Language used for code
Golang

#### Expected behavior

Provided code should not be accepted as a solution, because it gives a false positive result for this list, which is obviously not a palindrome:

```[2,3,3,2,3,2,2,3]```

Please add this test case to fix problem.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
