### ISSUE TITLE
Missing Test Case - 30. Substring with Concatenation of All Words

### ISSUE THREAD

**Issue by abyss-walker** [LeetCode-Feedback/LeetCode-Feedback#8663]
#### Your LeetCode username

yellow_13

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Brute force approach should actually give TLE, but some people are getting correct answer on submitting brute force as well. I have made a big test case for which the code gives TLE when tested in Leetcode console, but it gives correct answer on submitting.
Testcase:
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9333207/testcase.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkSubstring(unordered_map<string, int> wordCount, string s, int wordLen) {
        for(int j=0; j<s.size(); j+=wordLen) {
            string w = s.substr(j, wordLen);
            if(wordCount.find(w) != wordCount.end()) {
                if(--wordCount[w] == -1) {
                    return false;
                }
            } else {
                return false;
            }
        }
        return true;
    }

    vector<int> findSubstring(string s, vector<string>& words) {
        vector<int> res;
        int wordLen = words[0].size();
        int sLen = s.size();
        int wordsWindow = words.size() * wordLen;
        
        unordered_map<string, int> wordCount;
        for(int i=0; i<words.size(); i++) {
            wordCount[words[i]]++;
        }
        
        int i = 0;
        while(i + wordsWindow <= sLen) {
            if(checkSubstring(wordCount, s.substr(i, wordsWindow), wordLen)) {
                res.push_back(i);
            }
            i++;
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It was expected that the code would give Time Limit Exceeded

#### Screenshots

![lc ss](https://user-images.githubusercontent.com/71251594/184533193-a0f538d2-61cd-4cbb-9611-eda4a7681482.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
