### ISSUE TITLE
Missing Test Case - 126. Word Ladder II

### ISSUE THREAD

**Issue by martin0327** [LeetCode-Feedback/LeetCode-Feedback#8665]
#### Your LeetCode username

martin0327

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This problem cannot be solved with the given constraint.
There exist test cases that satisfy the constraint and gives TLE or MLE to all AC submissions.
It's not a matter of efficiency of the solution. The answer of those test cases are just way too big.
It should specify, therefore, the size of the answer of all test cases are of a reasonable size.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<string>> findLadders(string s, string t, vector<string>& a) {
      using vi = vector<int>;
      using vvi = vector<vi>;
      const int inf = 1e9;
      
      map<string,int> mp1;
      map<int,string> mp2;
      int idx = 0;
      for (auto x : a) mp1[x] = 0;
      vector<vector<string>> ret;
      if (!mp1.count(t)) return ret;
      mp1[s] = 0;
      int sz = 0;
      for (auto &[k,v] : mp1) {
        v = sz++;
        mp2[v] = k;
      }
      int start = mp1[s];
      int goal = mp1[t];
      vvi adj(sz); 
      for (int i=0; i<sz; i++) {
        for (int j=i+1; j<sz; j++) {
          string u = mp2[i];
          string v = mp2[j];
          int cnt = 0;
          for (int k=0; k<u.size(); k++) 
            cnt += u[k] != v[k];
          if (cnt==1) {
            adj[i].push_back(j);
            adj[j].push_back(i);
          }
        }
      }
    
      vi dist(sz,inf);
      queue<int> q;
      dist[start] = 0;
      q.push(start);
      while (q.size()) {
        int u = q.front();
        q.pop();
        for (auto v : adj[u]) {
          if (dist[v] < inf) continue;
          dist[v] = dist[u] + 1;
          q.push(v);
        }
      }
      int d = dist[goal];
      if (d == inf) return ret;
      
      vvi b = {{goal}};
      for (int i=d-1; i>=0; i--) {
        vvi temp;
        for (auto c : b) {
          int u = c.back();
          for (auto v : adj[u]) {
            if (dist[v] == i) {
              vi d = c;
              d.push_back(v);
              temp.push_back(d);
            }
          }
        }
        b = temp;
      }
      for (auto &c : b) {
        reverse(c.begin(), c.end());
        vector<string> d;
        for (auto &u : c) {
          d.push_back(mp2[u]);
        }
        ret.push_back(d);
      }
      return ret;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

TLE or MLE

#### Additional context

Here's an example of such test cases.

"aaaaa"
"qqqqq"
["aaaaa","aaaab","aaaba","aaabb","aabaa","aabab","aabba","aabbb","abaaa","abaab","ababa","ababb","abbaa","abbab","abbba","abbbb","baaaa","baaab","baaba","baabb","babaa","babab","babba","babbb","bbaaa","bbaab","bbaba","bbabb","bbbaa","bbbab","bbbba","bbbbb","bbbbc","bbbcb","bbbcc","bbcbb","bbcbc","bbccb","bbccc","bcbbb","bcbbc","bcbcb","bcbcc","bccbb","bccbc","bcccb","bcccc","cbbbb","cbbbc","cbbcb","cbbcc","cbcbb","cbcbc","cbccb","cbccc","ccbbb","ccbbc","ccbcb","ccbcc","cccbb","cccbc","ccccb","ccccc","ccccd","cccdc","cccdd","ccdcc","ccdcd","ccddc","ccddd","cdccc","cdccd","cdcdc","cdcdd","cddcc","cddcd","cdddc","cdddd","dcccc","dcccd","dccdc","dccdd","dcdcc","dcdcd","dcddc","dcddd","ddccc","ddccd","ddcdc","ddcdd","dddcc","dddcd","ddddc","ddddd","dddde","ddded","dddee","ddedd","ddede","ddeed","ddeee","deddd","dedde","deded","dedee","deedd","deede","deeed","deeee","edddd","eddde","edded","eddee","ededd","edede","edeed","edeee","eeddd","eedde","eeded","eedee","eeedd","eeede","eeeed","eeeee","eeeef","eeefe","eeeff","eefee","eefef","eeffe","eefff","efeee","efeef","efefe","efeff","effee","effef","efffe","effff","feeee","feeef","feefe","feeff","fefee","fefef","feffe","fefff","ffeee","ffeef","ffefe","ffeff","fffee","fffef","ffffe","fffff","ffffg","fffgf","fffgg","ffgff","ffgfg","ffggf","ffggg","fgfff","fgffg","fgfgf","fgfgg","fggff","fggfg","fgggf","fgggg","gffff","gfffg","gffgf","gffgg","gfgff","gfgfg","gfggf","gfggg","ggfff","ggffg","ggfgf","ggfgg","gggff","gggfg","ggggf","ggggg","ggggh","ggghg","ggghh","gghgg","gghgh","gghhg","gghhh","ghggg","ghggh","ghghg","ghghh","ghhgg","ghhgh","ghhhg","ghhhh","hgggg","hgggh","hgghg","hgghh","hghgg","hghgh","hghhg","hghhh","hhggg","hhggh","hhghg","hhghh","hhhgg","hhhgh","hhhhg","hhhhh","hhhhi","hhhih","hhhii","hhihh","hhihi","hhiih","hhiii","hihhh","hihhi","hihih","hihii","hiihh","hiihi","hiiih","hiiii","ihhhh","ihhhi","ihhih","ihhii","ihihh","ihihi","ihiih","ihiii","iihhh","iihhi","iihih","iihii","iiihh","iiihi","iiiih","iiiii","iiiij","iiiji","iiijj","iijii","iijij","iijji","iijjj","ijiii","ijiij","ijiji","ijijj","ijjii","ijjij","ijjji","ijjjj","jiiii","jiiij","jiiji","jiijj","jijii","jijij","jijji","jijjj","jjiii","jjiij","jjiji","jjijj","jjjii","jjjij","jjjji","jjjjj","jjjjk","jjjkj","jjjkk","jjkjj","jjkjk","jjkkj","jjkkk","jkjjj","jkjjk","jkjkj","jkjkk","jkkjj","jkkjk","jkkkj","jkkkk","kjjjj","kjjjk","kjjkj","kjjkk","kjkjj","kjkjk","kjkkj","kjkkk","kkjjj","kkjjk","kkjkj","kkjkk","kkkjj","kkkjk","kkkkj","kkkkk","kkkkl","kkklk","kkkll","kklkk","kklkl","kkllk","kklll","klkkk","klkkl","klklk","klkll","kllkk","kllkl","klllk","kllll","lkkkk","lkkkl","lkklk","lkkll","lklkk","lklkl","lkllk","lklll","llkkk","llkkl","llklk","llkll","lllkk","lllkl","llllk","lllll","llllm","lllml","lllmm","llmll","llmlm","llmml","llmmm","lmlll","lmllm","lmlml","lmlmm","lmmll","lmmlm","lmmml","lmmmm","mllll","mlllm","mllml","mllmm","mlmll","mlmlm","mlmml","mlmmm","mmlll","mmllm","mmlml","mmlmm","mmmll","mmmlm","mmmml","mmmmm","mmmmn","mmmnm","mmmnn","mmnmm","mmnmn","mmnnm","mmnnn","mnmmm","mnmmn","mnmnm","mnmnn","mnnmm","mnnmn","mnnnm","mnnnn","nmmmm","nmmmn","nmmnm","nmmnn","nmnmm","nmnmn","nmnnm","nmnnn","nnmmm","nnmmn","nnmnm","nnmnn","nnnmm","nnnmn","nnnnm","nnnnn","nnnno","nnnon","nnnoo","nnonn","nnono","nnoon","nnooo","nonnn","nonno","nonon","nonoo","noonn","noono","nooon","noooo","onnnn","onnno","onnon","onnoo","ononn","onono","onoon","onooo","oonnn","oonno","oonon","oonoo","ooonn","ooono","oooon","ooooo","oooop","ooopo","ooopp","oopoo","oopop","ooppo","ooppp","opooo","opoop","opopo","opopp","oppoo","oppop","opppo","opppp","poooo","pooop","poopo","poopp","popoo","popop","poppo","poppp","ppooo","ppoop","ppopo","ppopp","pppoo","pppop","ppppo","ppppp","ppppq","pppqp","pppqq","ppqpp","ppqpq","ppqqp","ppqqq","pqppp","pqppq","pqpqp","pqpqq","pqqpp","pqqpq","pqqqp","pqqqq","qpppp","qpppq","qppqp","qppqq","qpqpp","qpqpq","qpqqp","qpqqq","qqppp","qqppq","qqpqp","qqpqq","qqqpp","qqqpq","qqqqp","qqqqq"]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've updated the validator and added a new constraint that the sum of answer does not exceed 10^5. We appreciate your support!

**Comment by martin0327** [comment]
> 

Why didn't I get the reward? is it because you guys updated the validator instead of updating test cases?

**Comment by nskybytskyi** [comment]
@martin0327 probably because this issue is too similar to #7925

**Comment by martin0327** [comment]
It clearly is not. You didn't know what to do with such cases. I guided you
exactly what to do. How are they same?

2023년 3월 25일 (토) 오전 6:23, Nikita Skybytskyi ***@***.***>님이 작성:

**Comment by nskybytskyi** [comment]
I'm not an official contributor, so I don't close issues and don't decide who gets coins. I also don't know the exact changes implemented in connection to your report. It is just my assumption based on related issues from that time. 

Nevertheless, even small changes and similar issues get rewarded sometimes, so @LC-Pam may want to revisit this. Building an active and welcoming community of contributors should be one of the primary objectives of this project. From this perspective, not rewarding reasonable feedback is a questionable decision.
