### ISSUE TITLE
Chinese link on .com?

### ISSUE THREAD

**Issue by panoskarajohn** [LeetCode-Feedback/LeetCode-Feedback#8667]
#### Your LeetCode username

panoskarjohn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On this link https://leetcode.com/explore/learn/card/dynamic-programming/634/matrix-path-based-dp/4129/ you have defined a source that is not reachable. Redirects to Chinese site https://leetcode-cn.com/leetbook/read/bit-manipulation-and-math/ovonij/
which requires login.

#### Expected behavior

I would expect to be redirected inside leetcode .com and be able to read the article.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
