### ISSUE TITLE
436. Find Right Interval [[0,1],[2, max int]] case

### ISSUE THREAD

**Issue by evgenyshiryaev** [LeetCode-Feedback/LeetCode-Feedback#867]
I noticed that top performace solutions use O(M) memory, where M is (max interval point - min interval point).
This will lead to OOM for case like [[0,1],[2, max int]].
This case can be found in problem discussions.

It will be nice to add this test case.

**Comment by lc-pam** [comment]
Hi @evgenyshiryaev 
Thank you for reaching out to us. Would you mind providing the link to the discuss post you mentioned so we can reproduce the issue on our end?

**Comment by evgenyshiryaev** [comment]
I did following.
Submitted my O(nlogn) solution.
Went to details and opened best performance solution.

This is it:
    class Solution {
        public int[] findRightInterval(int[][] intervals) {
        int min = intervals[0][0];
        int max = intervals[0][1];
        for (int i = 0; i < intervals.length; i++) {
            if(intervals[i][0] < min) min = intervals[i][0];
            if(intervals[i][1] > max) max = intervals[i][1];
        }
        int[] bucket = new int[max - min + 1];
        Arrays.fill(bucket, -1);
        for (int i = 0; i < intervals.length; i++) {
            bucket[intervals[i][0] - min] = i;
        }
        for (int i = bucket.length - 2; i >= 0; i--) {
            if(bucket[i] == - 1) bucket[i] = bucket[i + 1];
        }
        int[] result = new int[intervals.length];
        for (int i = 0; i < result.length; i++) {
            result[i] = bucket[intervals[i][1] - min];
        }
        return result;
    }
}

It throws Memory Limit Exceeded for case [[0,1],[2, 1000000000]]
But now this solution is accepted.

**Comment by evgenyshiryaev** [comment]
Please check this also: https://leetcode.com/problems/find-right-interval/discuss/814322/Python-O(n)-solution-beats-100-no-sorting-w-explanation

**Comment by lc-pam** [comment]
Hi @evgenyshiryaev 
Thanks for providing the code. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @evgenyshiryaev 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
