### ISSUE TITLE
Missing Test Case - 2176. Count Equal and Divisible Pairs in an Array

### ISSUE THREAD

**Issue by AnubhavMadhav** [LeetCode-Feedback/LeetCode-Feedback#8674]
In the question, the condition given is that `0 <= i < j < n`. 
Therefore, 'i' should always be less than 'j'.
But I tried a solution that does not follow `i<j` and violates it, still the code was submitted successfully.
I believe that some more test cases should be added in order to avoid submissions of wrong solutions which violate the above given condition.

#### Code you used for Submit/Run operation
The following code is a wrong solution as it violates the condition `i<j`. Still, this code passed all the test cases. 
Output of following code: Passed all the test cases
Expected behavior according to the given `i<j` condition: Should not pass all test cases

```
class Solution {
    public int countPairs(int[] nums, int k) {
        int n = nums.length;
        int count = 0;
        for (int i=0; i<n; i++) {
            for (int j=0; j<i; j++) {
                if (nums[i] == nums[j] && (i*j)%k == 0) {
                    count++;
                }
            }
        }
        return count;
    }
}
```

Correct Code (which follows given condition of `i<j`):
```
class Solution {
    public int countPairs(int[] nums, int k) {
        int n = nums.length;
        int count = 0;
        for (int i=0; i<n; i++) {
            for (int j=i+1; j<n; j++) {
                if (nums[i] == nums[j] && (i*j)%k == 0) {
                    count++;
                }
            }
        }
        return count;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The wrong solution which violates the condition `i<j` as provided by me above should not pass all the test cases. Therefore, we need to add more test cases to avoid submissions of wrong solutions.

#### Screenshots
![Wrong Solution](https://user-images.githubusercontent.com/42323737/184624258-6cd710a4-7320-4196-b4e1-dfc6f4a01301.png)
In the above image, we can see that even the wrong solution which violates the given condition of `i<j` has passed all the test cases, whereas this solution should fail according to the given condition.

![Correct Solution](https://user-images.githubusercontent.com/42323737/184624387-a332a93d-d531-4306-a78b-99f9989fc2f1.png)
In the above image, we can see that the correct solution which follows the given condition of `i<j` has successfully passed all the test cases and this is working as expected.

#### Additional context
We need to add more test cases which also verifies the given condition of `i<j`.
Thank You!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Both solutions are correct. Please use the discussion section to understand why both passed. We appreciate your support!

**Comment by AnubhavMadhav** [comment]
Sure, thank you so much!
