### ISSUE TITLE
Incorrect Test case (#15) 

### ISSUE THREAD

**Issue by S-Swaroop** [LeetCode-Feedback/LeetCode-Feedback#8678]
#### Your LeetCode username

sharan_17

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] incorrect test case

#### Description of the bug

The output for the following testcase should be 1 as we can jump from 'a' to 'c' in one steps but on submission the expected output is shown to be 2.
```
"a"
"c"
["a","b","c"]
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int ladderLength(string beginWord, string endWord, vector<string>& wordList) {
        set<string> words(wordList.begin() , wordList.end()) ;
        if (words.find(endWord) == words.end()) {
            return 0 ;
        }
        int distance = 0 ;
        words.erase(beginWord) ;
        queue<string> q ; 
        q.push(beginWord) ;
        while (!q.empty()) {
            string word = q.front() ;
            q.pop() ;
            if (word == endWord) {
                return distance ;
            } else {
                bool found = false ;
                for (char &i : word) {
                    for (char c = 'a' ; c <= 'z' ; c++) {
                        if (i != c) {
                            swap(i , c) ; 
                            if (words.find(word) != words.end()) {
                                found = true ;
                                words.erase(word) ; 
                                q.push(word) ;
                            }
                            swap(i , c) ;
                        }
                    }
                }
                distance += found ;
            }
        }
        return 0 ;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The expected output should be 1 as we can jump from "a" to "c" in one step as they differ by only one character.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by S-Swaroop** [comment]
https://leetcode.com/submissions/detail/774352503/

**Comment by stormsunshine** [comment]
The sequence includes the start word and the end word. Since the sequence is "a" -> "c", the length is 2. The length is not the number of steps.

**Comment by LC-Pam** [comment]
Please consider Stromsunshine's comment. 
The judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
