### ISSUE TITLE
Missing Test Case - 843. Guess the Word

### ISSUE THREAD

**Issue by ChandrakantSahu17** [LeetCode-Feedback/LeetCode-Feedback#8680]
#### Your LeetCode username

ck_17
( contribution no. 03 )

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

If we run the below code, the result is inconsistent i.e. sometimes the result shows "Accepted" and sometimes  "Wrong Answer".

#### Code you used for Submit/Run operation

```

class Solution {
    public void findSecretWord(String[] wordlist, Master master) {
        Random random = new Random();
        for(int i = 0, matches = 0; i < 10 && matches != 6; i ++){
            String guess = wordlist[random.nextInt(wordlist.length)];
            matches = master.guess(guess);
            List<String> candidates = new ArrayList<>();
            for(String word: wordlist){
                if(matches == getMatches(guess, word)){
                    candidates.add(word);
                }
            }
            
            wordlist = candidates.toArray(new String[0]);
        }
    }
    
    private int getMatches(String word1, String word2){
        int matches = 0;
        for(int i = 0; i < word1.length(); i ++){
            if(word1.charAt(i) == word2.charAt(i)){
                matches ++;
            }
        }
        
        return matches;
    }
}
```

#### Language used for code
 Java

#### Expected behavior

Wrong Answer

#### Screenshots

![Screenshot 2022-08-15 235832](https://user-images.githubusercontent.com/87990448/184697642-45788f60-1e2f-4f53-b6ff-c2f9afb9640a.jpg)

![Screenshot 2022-08-15 235911](https://user-images.githubusercontent.com/87990448/184697682-bc9ed7b4-eeeb-4da7-8ef7-90ac73b88e43.jpg)

![Screenshot 2022-08-15 235952](https://user-images.githubusercontent.com/87990448/184697731-c30984b8-14fc-4b58-8013-c2e90e32ae33.jpg)

![image](https://user-images.githubusercontent.com/87990448/184700563-2ce1f37b-8aa6-4cea-92ba-94930b51a772.png)

##### List of Testcase : 

"zzzzzz"
["aaaaaa","bbbbbb","cccccc","dddddd","eeeeee","ffffff","gggggg","hhhhhh","iiiiii","jjjjjj","kkkkkk","llllll","mmmmmm","nnnnnn","oooooo","pppppp","qqqqqq","rrrrrr","ssssss","tttttt","uuuuuu","vvvvvv","wwwwww","xxxxxx","yyyyyy","zzzzzz"]
10

"axxxxx"
["aaaaaa","abbbbb","accccc","addddd","aeeeee","afffff","aggggg","ahhhhh","aiiiii","ajjjjj","akkkkk","alllll","ammmmm","annnnn","aooooo","appppp","aqqqqq","arrrrr","asssss","attttt","auuuuu","avvvvv","awwwww","axxxxx","ayyyyy","azzzzz" ]
10

"aaxyaa"
["aaxyaa","bbxybb","ccxycc","ddxydd","eexyee","ffxyff","ggxygg","hhxyhh","iixyii","jjxyjj","kkxykk","llxyll","mmxymm","nnxynn","ooxyoo","ppxypp","qqxyqq","rrxyrr","ssxyss","ttxytt","uuxyuu","vvxyvv","wwxyww","xxxyxx","yyxyyy","zzxyzz" ]
10

**Comment by stormsunshine** [comment]
The problem description mentions as follows.
> The test cases are generated such that you can guess the secret word with a reasonable strategy (other than using the bruteforce method).

So don't create the test cases that can only be guessed using a bruteforce method.

**Comment by ChandrakantSahu17** [comment]
Dear @stormsunshine,
If we talk about the test case below, there will be two options - 
The below test case is valid and my code is wrong... or
The test case itself is such that it can only be solved via the brute force method which as you have mentioned goes against the problem description.

#### Test case :
( this is the 12th no. test case provided by LeetCode )

"azzzzz"
["abcdef","acdefg","adefgh","aefghi","afghij","aghijk","ahijkl","aijklm","ajklmn","aklmno","almnoz","anopqr","azzzzz"]
10

#### Code :
( Java )
```
class Solution {
    public void findSecretWord(String[] wordlist, Master master) {
        
        Random random = new Random();
        for(int i = 0, matches = 0; i < 10 && matches != 6; i ++){
            String guess = wordlist[random.nextInt(wordlist.length)];
            // String guess = wordlist[0]; // what if rand() genrate int 0 all the time.
            matches = master.guess(guess);
            List<String> candidates = new ArrayList<>();
            for(String word: wordlist){
                if(matches == getMatches(guess, word)){
                    candidates.add(word);
                }
            }
            
            wordlist = candidates.toArray(new String[0]);
        }
    }
    
    private int getMatches(String word1, String word2){
        int matches = 0;
        for(int i = 0; i < word1.length(); i ++){
            if(word1.charAt(i) == word2.charAt(i)){
                matches ++;
            }
        }
        
        return matches;
    }
}
```
The above code works fine about 9/10 times... But a code is said to be completely correct only if it works every time.

#### Screenshot :
![Screenshot 2022-08-16 183410](https://user-images.githubusercontent.com/87990448/184894413-34c533e2-1ab2-49e6-b88e-93c421d328f6.jpg)

#### What do I think ?

All the below test cases are valid because there is one algorithm that gives the correct answer 10/10 times...

##### Test cases :
"zzzzzz"
["aaaaaa","bbbbbb","cccccc","dddddd","eeeeee","ffffff","gggggg","hhhhhh","iiiiii","jjjjjj","kkkkkk","llllll","mmmmmm","nnnnnn","oooooo","pppppp","qqqqqq","rrrrrr","ssssss","tttttt","uuuuuu","vvvvvv","wwwwww","xxxxxx","yyyyyy","zzzzzz"]
10

"axxxxx"
["aaaaaa","abbbbb","accccc","addddd","aeeeee","afffff","aggggg","ahhhhh","aiiiii","ajjjjj","akkkkk","alllll","ammmmm","annnnn","aooooo","appppp","aqqqqq","arrrrr","asssss","attttt","auuuuu","avvvvv","awwwww","axxxxx","ayyyyy","azzzzz" ]
10

"aaxyaa"
["aaxyaa","bbxybb","ccxycc","ddxydd","eexyee","ffxyff","ggxygg","hhxyhh","iixyii","jjxyjj","kkxykk","llxyll","mmxymm","nnxynn","ooxyoo","ppxypp","qqxyqq","rrxyrr","ssxyss","ttxytt","uuxyuu","vvxyvv","wwxyww","xxxyxx","yyxyyy","zzxyzz" ]
10

( this is the 12th no. test case provided by LeetCode )
"azzzzz"
["abcdef","acdefg","adefgh","aefghi","afghij","aghijk","ahijkl","aijklm","ajklmn","aklmno","almnoz","anopqr","azzzzz"]
10

##### Algorithm in the form of code :
( C++ )

Credits to LeetCode user @votrubac for the code.
```
/**
 * // This is the Master's API interface.
 * // You should not implement it, or speculate about its implementation
 * class Master {
 *   public:
 *     int guess(string word);
 * };
 */
class Solution {
public:
    int res = 0, probs[6][26] = {};
    int match(string &w1, string &w2) {
        return inner_product(begin(w1), end(w1), begin(w2), 0, plus<int>(), equal_to<char>());
    }
    string bestCandidate(list<string>& words) {
        string best;
        int max_score = 0;
        for (auto w : words) {
            int score = 1;
            for (auto i = 0; i < 6; ++i)
                score *= probs[i][w[i] - 'a'];
            if (score > max_score) {
                max_score = score;
                best = w;
            }
        }
        return best;
    }
    void findSecretWord(vector<string>& wordlist, Master& master) {
        list<string> remWords(begin(wordlist), end(wordlist));
        auto add_prob = [&](string &w, int d = 1) {
            for (auto i = 0; i < 6; ++i)
                probs[i][w[i] - 'a'] += d;
        };
        for_each(begin(wordlist), end(wordlist), add_prob);
        while (res < 6) {
            auto candidate = bestCandidate(remWords);
            res = master.guess(candidate);
            for (auto it = remWords.begin(); it != remWords.end(); )
                if (match(*it, candidate) != res) {
                    add_prob(*it, -1);
                    remWords.erase(it++);
                }
                else 
                    ++it;
        }
    }
};
```

So my suggestion to you all is that the test cases I've mentioned should be added to the official testcase list so that the users who solve this problem in the future will focus their attention to the logic described by the C++ code instead of wasting their time on the sometimes correct but not always correct logic of the Java code. Or the 12th test case should be removed from the list so that both approaches will result in AC.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
