### ISSUE TITLE
Better Solution

### ISSUE THREAD

**Issue by maysamgamini** [LeetCode-Feedback/LeetCode-Feedback#8681]
#### Your LeetCode username

maysamgamini

#### Category of the bug
- [12. Integer to Roman ] Question
- [https://leetcode.com/problems/integer-to-roman/discuss/2430880/Fastet-and-Easiest-Way-to-solve-this-please-hit-the-up-arrow! ] Solution
- [English ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The provided solutions are not good enough, it causes bad practices and confusion, please look at this
https://leetcode.com/problems/integer-to-roman/discuss/2430880/Fastet-and-Easiest-Way-to-solve-this-please-hit-the-up-arrow!

#### Code you used for Submit/Run operation

```
class Solution {
    public String intToRoman(int num) {
        TreeMap<Integer, String> dicI2R = new TreeMap<Integer, String>();
        dicI2R.put(1,"I");
        dicI2R.put(4,"IV");
        dicI2R.put(5,"V");
        dicI2R.put(9,"IX");
        dicI2R.put(10,"X");
        dicI2R.put(40,"XL");
        dicI2R.put(50,"L");
        dicI2R.put(90,"XC");
        dicI2R.put(100,"C");
        dicI2R.put(400,"CD");
        dicI2R.put(500,"D");
        dicI2R.put(900,"CM");
        dicI2R.put(1000,"M");
        StringBuilder sb = new StringBuilder();
        while(num > 0)
        {
            Map.Entry<Integer,String> candidate = dicI2R.floorEntry(num);
            sb.append(candidate.getValue());
            num -= candidate.getKey();
        }
        return sb.toString();
    }
}
```

#### Language used for code

java

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.
