### ISSUE TITLE
Incorrect Question Constraints - 142. Linked List Cycle II

### ISSUE THREAD

**Issue by brandonwalls** [LeetCode-Feedback/LeetCode-Feedback#8682]
#### Your LeetCode username

BrandonW2

#### Category of the bug
- [ X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question being solved has an very important constraint that is not provided, and the solutions don't actually work if you don't have that constraint specified. I was thinking there's no way this question is a medium based on the fact that I was getting into statistics to discern when a value was used inside AND outside the cyclic part, and how to tell at which occurrence of a value is actually the start of the cycle (based on occurrence count and pattern). If a value cannot be outside of the potential cycle and ALSO within the potential cycle, then absolutely this is a Medium, sure. When I was absolutely convinced I was solving for a significantly harder problem, I checked the solution, and sure enough the solution was solving for a question with a constraint that all node values can only be used a single time. WAY easier! This is pretty important to add to the constraints list, otherwise the solutions provided here don't actually work with the current constraint set.

#### Code you used for Submit/Run operation

```
N/A
```

#### Language used for code

Python 3

#### Expected behavior

N/A

#### Screenshots

N/A

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
