### ISSUE TITLE
剑指 Offer II 067. 最大的异或

### ISSUE THREAD

**Issue by lqzo** [LeetCode-Feedback/LeetCode-Feedback#8684]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
liqingzhou

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[剑指 Offer II 067. 最大的异或](https://leetcode.cn/problems/ms70jA/)
提示中的数据范围错误，<code>1 <= nums.length <= 2 * 10<sup>4</sup></code> , 而最后一个的测试用例中的 `nums.length` 为 `200000`

**期望行为**
更正题目提示中的数据范围为 <code>1 <= nums.length <= 2 * 10<sup>5</sup></code>

**Comment by BrambleWave** [comment]
感谢您反馈，已采纳。
奖励积分已发放。
