### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by shukla2004** [LeetCode-Feedback/LeetCode-Feedback#8687]
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
 

int max(int num1, int num2)
{
    return (num1 > num2) ? num1 : num2;
}
 

bool areDistinct(char str[], int i, int j)
{
 
    
    bool visited[26];
      for(int i=0;i<26;i++)
      visited[i]=0;
 
    for (int k = i; k <= j; k++) {
        if (visited[str[k] - 'a'] == true)
            return false;
        visited[str[k] - 'a'] = true;
    }
    return true;
}
 

int longestUniqueSubsttr(char str[])
{
    int n = strlen(str);
    int res = 0; // result
    for (int i = 0; i < n; i++)
        for (int j = i; j < n; j++)
            if (areDistinct(str, i, j))
                res = max(res, j - i + 1);
    return res;
}

int main()
{
    char str[] = "kirti shukla";
    printf("The input string is %s \n", str);
    int len = longestUniqueSubsttr(str);
    printf("The length of the longest non-repeating "
           "character substring is %d",
           len);
    return 0;
}

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by mishrakushal** [comment]
Hello. I went through your code and noticed that you are not checking whether a given string is empty. So in the test case where the string is empty, the `visited` array in your `areDistinct()` function goes out of bounds, thus causing a Runtime Error. <br> Simple adding an empty string check will fix this problem.  You can do so by adding
`int n = strlen(str);`
`if (n == 0)`
`    return 0;`

Hope this helps.

**Comment by shukla2004** [comment]
hello 
ok i understoon thanks for checking my code
