### ISSUE TITLE
Missing Test Case - 41. First Missing Positive

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#8692]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9356571/1.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int firstMissingPositive(vector<int>& nums) {
        int cur = 1;
        while (true) {
            int t = cur;
            for (int i = 0; i < nums.size(); i++) {
                if (cur == nums[i]) cur++;
            }
            if (cur == t) break;
        }
        return cur;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
