### ISSUE TITLE
Test Case [0,-1] Bug - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by abhideepghosh** [LeetCode-Feedback/LeetCode-Feedback#8694]
#### Your LeetCode username

AbhideepGhosh

#### Category of the bug
- [ ] Test Case [0, -1] Bug 

#### Description of the bug

A screenshot of the bug is already uploaded. A brute force solution of Valid Binary Search Tree question shows wrong output on submitting the question but passes the same test case on running it in the custom test case of the question.

#### Code you used for Submit/Run operation

```
class Solution {
    static ArrayList<Integer> validateTree = new ArrayList<>();
    public boolean isValidBST(TreeNode root) {
        if(root == null){
            return true;
        }
        if(root.left == null && root.right == null){
            return true;
        }
        inorder(root);
        // for(int i : validateTree){
        //     System.out.println(i);
        // }
        if(validateTree.size() == 1){
            return true;
        }
        for(int i=0; i<validateTree.size()-1; i++){
            if(validateTree.get(i) > validateTree.get(i+1)){
                return false;
            }
        }
        return true;
    }
    public void inorder(TreeNode root){
        if(root == null){
            return;
        }
        inorder(root.left);
        validateTree.add(root.val);
        inorder(root.right);
    }
}
```
**On clearing the globally declared Array List (validateTree.clear()), the code works. The other correction done in this code which is if(validateTree.get(i) >= validateTree.get(i+1)) is for passing the cases for duplicate values and has no effect on this specific test case.**
```
// A Working Brute Force Solution
class Solution {
    static ArrayList<Integer> validateTree = new ArrayList<>();
    public boolean isValidBST(TreeNode root) {
        if(root == null){
            return true;
        }
        if(root.left == null && root.right == null){
            return true;
        }
        validateTree.clear();
        inorder(root);
        for(int i : validateTree){
            System.out.println(i);
        }
        if(validateTree.size() == 1){
            return true;
        }
        for(int i=0; i<validateTree.size()-1; i++){
            if(validateTree.get(i) >= validateTree.get(i+1)){
                return false;
            }
        }
        return true;
    }
    public void inorder(TreeNode root){
        if(root == null){
            return;
        }
        inorder(root.left);
        validateTree.add(root.val);
        inorder(root.right);
    }
}
``` 

#### Language used for code

Java

#### Expected behavior

In the custom test case using Run Code of Leetcode, the result appears to be correct(True), but while submitting, the result output shows wrong, unless at the end of the function, the Array List is cleared.

#### Screenshots

![image](https://user-images.githubusercontent.com/109783702/185072670-67178ef8-3329-4af4-b8fa-dcf5533ef2d4.png)

#### Additional context

The code is not meant to be a perfect solution, as the right answer is by using a Stack Data Structure, but it is passing this specific test case, but while submitting, it fails, unless the globally declared Array List isn't cleared.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
