### ISSUE TITLE
Kotlin version out of date, affecting submissions

### ISSUE THREAD

**Issue by owensizemore** [LeetCode-Feedback/LeetCode-Feedback#8695]
#### Your LeetCode username
owensizemore

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Kotlin version used in LeetCode's compiler (1.3.10) is very out of date, having been released more than two years ago. The most current version of Kotlin is 1.7.10 from July 2022. This lag in versioning means that some modern solutions to programming problems in Kotlin will not be accepted by LeetCode. In the example below, I desired to use the following `when` block to check whether a character in a password was a lowercase character, uppercase character, or digit using the `Char.code` [method](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/code.html) in [2299. Strong Password Checker II](https://leetcode.com/problems/strong-password-checker-ii/): 

```
when (password[i].code) {
   in (97..122) -> oneLowercase = true
   in (65..90) -> oneUppercase = true
   in (48..57) -> oneDigit = true
}
```

However, because `Char.code` was introduced in Kotlin 1.5, this solution was not accepted. I instead had to resort to using the deprecated `Char.toInt()` [method](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-char/to-int.html):

```
when (password[i].toInt()) {
    in (97..122) -> oneLowercase = true
    in (65..90) -> oneUppercase = true
    in (48..57) -> oneDigit = true
}
```

#### Language used for code
Kotlin

#### Screenshots
![Screen Shot 2022-08-17 at 8 27 51 AM](https://user-images.githubusercontent.com/25808675/185120934-60323925-4f6c-47ea-94ea-9dba17824733.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by awelless** [comment]
@LC-Pam 
Also due to jvm 1.6 target, it's impossible to use many features of java 8, like `Comparator.reverseOrder()`.
So not only kotlin, but also jdk version should be bumped.
![image](https://user-images.githubusercontent.com/65507498/202871506-4db7031a-cfb6-441f-a89f-ec8f8f1d60a5.png)

**Comment by JIghtuse** [comment]
There are many votes on [Leetcode discuss thread](https://leetcode.com/discuss/feedback/1251018/New-kotlin-version) asking for a newer version. It shows up on the first page of feedback forum when you sort by votes.

**Comment by JIghtuse** [comment]
Wow, they did it. Now we can use Kotlin 1.9.0.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
