### ISSUE TITLE
Missing Test Case - 1564. Put Boxes Into the Warehouse I

### ISSUE THREAD

**Issue by rishabhmann** [LeetCode-Feedback/LeetCode-Feedback#8696]
#### Your LeetCode username
rishabhmann

#### Category of the bug
- [ ] Solution
- [ ] Missing Test Cases 

#### Description of the bug
The Code which I have submitted, shows all test cases passed ( 97/97 ), however suppose I have boxes = [ 4, 3, 3, 1 ] and warehouse = [1], then My solution output it as " 0 ". Instead it should return " 1 " as boxes[3] = 1, which can occupy 0th warehouse room.

When I use Article's solution, it perfectly output it as 1 instead of 0, So I believe below written code is not correct for test case like above mentioned. So, There might be some test case missing as **my wrong code was submitted**  or my answer should be output as "wrong answer".

My wrong code is checking if warehouse length == 1, and if 1st box's height <= warehouse[0], then return 1, else return 0.

But, boxes array can contain many other boxes, which can have height <= warehouse[0]. So, this check is not happening in my code. 

Still, it was accepted solution.

I believe it is wrong solution or test case like above is missing

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxBoxesInWarehouse(int[] boxes, int[] warehouse) {
        
        int n = boxes.length;
        int m = warehouse.length;
        
        // Bug related to this if statement
        if(m == 1){
            if(boxes[0] <= warehouse[0]){
                return 1;
            }else{
                return 0;
            }
        }
        // Bug related to above code

        for(int i=1; i<m ; i++){
            if(warehouse[i] > warehouse[i-1]){
                warehouse[i] = warehouse[i-1];
            }
        }
        
        Arrays.sort(boxes);
        
        int i = 0;
        int j = m - 1;
        
        int count = 0;
        
        while( i < n && j >=0 ){
            
            if(boxes[i] <= warehouse[j]){
                count++;
                i++;
            }
            
            j--;
        }
        
        return count;
    }
}
```

#### Language used for code
Java 

#### Expected behavior
For above bug, if I had sorted boxes array first and later used if-statement ( code that caused bug ), then output would be perfectly fine which is "1" in this case.

But since, I had not sorted boxes array first, so boxes array could potentially contain any box which can fit into warehouse's room of warehouse.length == 1. 

#### Screenshots
Using Run code :
![image](https://user-images.githubusercontent.com/66436127/185170607-abc5a45c-f38c-4d4f-930e-5738b80e93b7.png)

Using Submit :
![image](https://user-images.githubusercontent.com/66436127/185170868-6eecd3dd-77a8-472d-ad2a-0853262b1acf.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
