### ISSUE TITLE
727. Problem "Minimum Window Subsequence" Suboptimal solution allowed

### ISSUE THREAD

**Issue by foxtrot9** [LeetCode-Feedback/LeetCode-Feedback#87]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
This problem allows suboptimal solution of time complexity O(S*S*T) pass.

**what language is your code written in**
Java

**The code you submit/run**
```
class Solution {
    public String minWindow(String s, String t) {
        if(s == null || t == null || s.length() == 0 || t.length() == 0)
            return "";
        int i = 0, j = 0, ii = 0;
        int n = s.length();
        int m = t.length();
        int min = Integer.MAX_VALUE;
        int start = 0;
        int end = 0;
        for(i = 0; i < n; ++i) {
            while(i < n && s.charAt(i) != t.charAt(0)) {
                ++i;
            }
            ii = i;
            i = i + 1;
            j = 1;
            if(i < n && m != 1) {
                for(; i < n && j < m; ++j, ++i) {
                    while(i < n && s.charAt(i) != t.charAt(j)) {
                        i++; 
                    }
                    if(i == n)
                        break;
                }
            }
            if((ii != n) && (j == m) && ((i-ii) < min)) {
                min = i-ii;
                start = ii;
                end = i;
            }
            i = ii;
        }
        return (min != Integer.MAX_VALUE) ? s.substring(start, end) : "";
    }
}
```

**Expected behavior**
The problem should not allow solution of time complexity O(S*S*T) to pass.
It should allow solution with time complexity less or equal to O(S*T).

**Screenshots**
<img width="1206" alt="Screen Shot 2020-03-31 at 12 12 53 PM" src="https://user-images.githubusercontent.com/20148223/77995217-feece900-7348-11ea-819d-da156fea9bdd.png">

**Additional context**
No additional context

**Comment by CooperCooperCooper** [comment]
Hi @foxtrot9,
Thank you for reaching out to us! I've relayed this feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @foxtrot9,
Thank you for your time. We took a thorough look at the information provided and decided the problem will not be updated for now. We appreciate your support. If you have any additional feedback you would like to share with us, please don't hesitate to comment here.
