### ISSUE TITLE
"436. Find Right Interval" Missing Test-case causing wrong solution to be accepted.

### ISSUE THREAD

**Issue by chandra1123** [LeetCode-Feedback/LeetCode-Feedback#870]
#### Your LeetCode username
chandra1123

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The problem is missing test case to verifies the solution works for all possible range of values.
The provided code passed all test cases and was accepted, but it doesn’t cover this test-case.

#### Code you used for Submit/Run operation

```
//sample 5 ms submission
/**
 * Solution : bucket
 *
 * Time complexity : O(n)
 * Space complexity : O(n)
 */
class Solution {
    public int[] findRightInterval(int[][] intervals) {
    	int min = Integer.MAX_VALUE;
        int max = Integer.MIN_VALUE;
        for (int[] interval : intervals) {
            min = Math.min(min, interval[0]);
            max = Math.max(max, interval[1]);
        }
        int[] bucket = new int[max - min + 1];
        Arrays.fill(bucket, -1);
        for (int i = 0; i < intervals.length; i++) {
            bucket[intervals[i][0] - min] = i;
        }
        for (int i = bucket.length - 2; i >= 0; i--) {
            if(bucket[i] == - 1) bucket[i] = bucket[i + 1];
        }
        int[] result = new int[intervals.length];
        for (int i = 0; i < result.length; i++) {
            result[i] = bucket[intervals[i][1] - min];
        }
        return result;
    }
}
```

#### Language
Java

#### Expected behavior

This solution should fail the test case and not be accepted.

**Comment by lc-pam** [comment]
Hi @chandra1123 
Thank you for reaching out to us. Can you please provide the exact test case that you think is missing?

**Comment by chandra1123** [comment]
**Test Description:** Verify the entire range of input is handled correctly.

**Exact Test Case**
**Input:** [ [-2147483648, 0], [0, 2147483647]]

**Output:** [1,-1]

**Explanation:** There is no satisfied "right" interval for  [0, 2147483647]
For [-2147483648, 0], the interval [0, 2147483647] has minimum-"right" start point.


The example accepted solution causes following exception:
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
  at line 12, Solution.findRightInterval
  at line 54, __DriverSolution__.__helper__
  at line 84, __Driver__.main

**Comment by lc-pam** [comment]
Hi @chandra1123 
Thank you for providing the details. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @chandra1123 ,
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
