### ISSUE TITLE
Coin Change Problem

### ISSUE THREAD

**Issue by EYOELTEKLE** [LeetCode-Feedback/LeetCode-Feedback#8701]
#### Javascript heap out of memory error
- [ ] Coin Change Problem
- [ ] Dynamic Problem using top down edge case 189 fails despite working on a node environment(Memoized Solution)
- [ ] Javascript
- [ ] edge case 189

#### Javascript 

```
/**
 * @param {number[]} coins
 * @param {number} amount
 * @return {number}
 */
var coinChange = function(coins, amount) {
    
    let result = DP(coins,amount);
    return result == null ? -1: result.length
};

const DP = (coins,amount,mem={}) => 
{
   
   if(amount in mem)
   {
       return mem[amount]
   } 
   if(amount == 0)
    {
        return []
    }
    if (amount < 0)
    {
        return null
    }
    let min = null;
    for (let item of coins)
    {
        let temp = amount - item;
        let val = DP(coins,temp,mem);
        if (val !== null)
        {
                let combo = [ ...val, item]
                
            if (min == null || min.length > combo.length)
            {
                min = combo;
                
            }
        }
    }

    mem[amount] = min
    return mem[amount]
}
```

#### Language used for code
Javascript

#### Expected behavior
Test case 189 coins[1], amount = 1000
should have worked with a solution 1000
the code has been memoized(top-down approach)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.The solution seems to have a bug when for the last test case, the user should use the discussion to understand why it fails.
The javascript solutions works fine for this problem. We appreciate your support!

**Comment by EYOELTEKLE** [comment]
Thanks for the help.
Node garbage collection has some issues when dealing with arrays I guess.
