### ISSUE TITLE
wrong example in leetcode 1000

### ISSUE THREAD

**Issue by GarfieldLeo** [LeetCode-Feedback/LeetCode-Feedback#8704]
#### Your LeetCode username

shengjiasheng2000

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

example1 is wrong
Input: stones = [3,2,4,1], k = 2
Output: 20
Explanation: We start with [3, 2, 4, 1].
We merge [3, 2] for a cost of 5, and we are left with [5, 4, 1].
We merge [4, 1] for a cost of 5, and we are left with [5, 5].
We merge [5, 5] for a cost of 10, and we are left with [10].
The total cost was 20, and this is the minimum possible.

Instead it should be
merge [1,2] -> [3,3,4] cost 3
merge [3,3] -> [6,4] cost 6
merge [6,4] -> [10] cost 10
total cost = 19
not 20

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
The statement mentioned that the piles have to be consecutive. The explanation is correct.
 We appreciate your support!
