### ISSUE TITLE
Incorrect Wording of Example Case - 665. Non-decreasing Array

### ISSUE THREAD

**Issue by shashjar** [LeetCode-Feedback/LeetCode-Feedback#8709]
#### Your LeetCode username
shj123

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The explanation for Example 2 under Description for the problem reads, "You can't get a non-decreasing array by modify at most one element." This should correctly read "You can't get a non-decreasing array by modifying at most one element."

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
