### ISSUE TITLE
Missing Test Case in Problem: https://leetcode.com/problems/insert-interval/

### ISSUE THREAD

**Issue by Rohitesh-Kumar-Jain** [LeetCode-Feedback/LeetCode-Feedback#871]
Contributed a Test Case **More than One month** ago but no one has responded yet, so posting here again. 

Missing corner case in Question: [https://leetcode.com/problems/insert-interval/](https://leetcode.com/problems/insert-interval/)

#### Your LeetCode username
rzay

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Empty List case is missing in the existing test suite of question:  

#### Code you used for Submit/Run operation

```
vector<vector<int>> insert(vector<vector<int>>& intervals, vector<int>& newInterval) {
        if(newInterval.size() == 0) {
            return intervals;
        }      
        vector<vector<int>> mergedIntervals;
        int i = 0;
        while(i < intervals.size() && intervals[i][1] < newInterval[0])
            mergedIntervals.emplace_back(intervals[i++]);

         while(i < intervals.size() && intervals[i][0] <= newInterval[1]) {
             newInterval[0] = min(newInterval[0], intervals[i][0]);
             newInterval[1] = max(newInterval[1], intervals[i][1]);
             i++;
         }
        mergedIntervals.emplace_back(newInterval);
        while(i < intervals.size())
            mergedIntervals.emplace_back(intervals[i++]);
        return mergedIntervals;
    }
```

#### Language used for code
C++ 

#### Expected behavior
Corner cases are missing in this question. Code which is not handling corner cases is also getting accepted. 

```
input
[]
[]
Output
[]
Expected
[[]]
```

#### Screenshots
Attaching Screenshot of the test case contribution:

<img width="1680" alt="Screenshot 2020-08-28 at 12 41 25" src="https://user-images.githubusercontent.com/62026125/91532407-e7338400-e92b-11ea-87bd-489e23023262.png">

**Comment by lc-pam** [comment]
Hi @Rohitesh-Kumar-Jain 
Thank you for reaching out to us. I'm sorry we didn't get to you earlier on the contribution platform. I've tried testing the code you provided but received compile error. Can you please check the code again or provide the link to your submission detail page so I can reproduce the issue?

**Comment by Rohitesh-Kumar-Jain** [comment]
@lc-pam Is this link accessible to you [https://leetcode.com/submissions/detail/370533045/](https://leetcode.com/submissions/detail/370533045/)

**Comment by Rohitesh-Kumar-Jain** [comment]
Copied the code from Submission itself: 
```
class Solution {
public:
    vector<vector<int>> insert(vector<vector<int>>& intervals, vector<int>& newInterval) {
        if(intervals.empty())
            return {newInterval};
        if(newInterval.size() == 0) {
            return intervals;
        }      
        vector<vector<int>> mergedIntervals;
        int i = 0;
        while(i < intervals.size() && intervals[i][1] < newInterval[0])
            mergedIntervals.emplace_back(intervals[i++]);

         while(i < intervals.size() && intervals[i][0] <= newInterval[1]) {
             newInterval[0] = min(newInterval[0], intervals[i][0]);
             newInterval[1] = max(newInterval[1], intervals[i][1]);
             i++;
         }
        mergedIntervals.emplace_back(newInterval);
        while(i < intervals.size())
            mergedIntervals.emplace_back(intervals[i++]);
        return mergedIntervals;
    }
};
```

**Comment by lc-pam** [comment]
Hi @Rohitesh-Kumar-Jain ,
Thanks for providing the submission link. I'm able to run your code. However, I'm getting the same output and expected output for the test case you provided with your code. Would you please check again and let me know if you see differently on your end? 
<img width="1663" alt="Screen Shot 2020-09-01 at 3 24 53 PM" src="https://user-images.githubusercontent.com/67175512/91912303-ae671800-ec67-11ea-8059-4d929f88e954.png">
