### ISSUE TITLE
Missing Test Case - 1877. Minimize Maximum Pair Sum in Array

### ISSUE THREAD

**Issue by Anirudh-kr** [LeetCode-Feedback/LeetCode-Feedback#8710]
#### Your LeetCode username

Dominator_123

#### Category of the bug
-Question

#### Description of the bug

The question states to return the minimized **maximum pair sum** this statement creates a confusion regarding what does **minimized** signifies here because in order to get maximum pair sum we can just add two largest elements and get the result. but, here minimized is i guess to take each time smallest one and largest one from the array and make the pair and to return the sum of largest sum among that pair.

#### Expected behavior

So it should be clearly mentioned in the question to return the maximum pair with following condition:
(1) Take maximum and minimum each time from the array and make pairs.
(2) No element should be used twice 
(3) return the maximum sum from those made pairs.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The changes are not applicable because it reveals the solution. We cannot put the solution in the statement. We appreciate your support!
