### ISSUE TITLE
Missing Test Case - 659. Split Array into Consecutive Subsequences

### ISSUE THREAD

**Issue by raditya1710** [LeetCode-Feedback/LeetCode-Feedback#8716]
#### Your LeetCode username
alfonsus_raditya

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case when input = `[1,2,3,999,1000]` it should returns `false`, but my solution is returning `true` and still get Accepted verdict.

#### Code you used for Submit/Run operation

```
class Solution {
    unordered_map<int, int> cnt;
public:
    bool isPossible(vector<int>& nums) {
        for(int x: nums){
            cnt[x]++;
        }
        
        int tmp[3] = {0, 0, 0};
        
        for(int i = -1000; i <= 1000; ++i){
            int now = 0;
            if(cnt.count(i)) now = cnt[i];
            int total = tmp[0] + tmp[1];
            if(total > now) return false;
            
            int tmp_0 = max(0, now - tmp[0] - tmp[1] - tmp[2]);
            int tmp_1 = tmp[0];
            int tmp_2 = tmp[1] + min(tmp[2], now - tmp[0] - tmp[1]);
            
            tmp[0] = tmp_0;
            tmp[1] = tmp_1;
            tmp[2] = tmp_2;
        }
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
the solution above should be judged as `Wrong Answer`

#### Screenshots
![Screenshot from 2022-08-19 19-28-20](https://user-images.githubusercontent.com/14028227/185618373-f41da78b-2a5d-471a-8674-8e816322e0df.png)

#### Additional context
solution link that should be Wrong Answer but get Accepted verdict: https://leetcode.com/submissions/detail/777727102/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
