### ISSUE TITLE
Always Time Limit Exceeded integer-to-roman Dart

### ISSUE THREAD

**Issue by II11II** [LeetCode-Feedback/LeetCode-Feedback#8717]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 
- [X] Time Limit Exceeded 

#### Description of the bug

The algorithm does not exceed BigO(n^2) but it fails with error Time Limit Exceeded 
This algorithm works in Java well

#### Code you used for Submit/Run operation

```
class Solution {
  String intToRoman(int num) {
      
       List<int> values=    [1000,900,500,400,100,90,50,40,10,9,5,4,1];
        List<String> symbols=["M","CM","D","CD","C","XC","L","XL","X","IX","V","IV","I"];
        var buffer =  StringBuffer();
        for(int i=0 ; i<values.length ;i++){
            while(num>=values[i]){
                buffer.write(symbols[i]);
                num-=values[i];
            }
        }
        return buffer.toString();
      
  }
}
```

#### Language used for code
Dart

#### Expected behavior

Should be accepted

#### Screenshots

![image](https://user-images.githubusercontent.com/45257709/185644681-56c2be0a-742e-4583-b1aa-032d91677e1e.png)

**Comment by LC-Pam** [comment]
Thank you for contacting LeetCode's Support Team.

Your submission is resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

Please note that the test case you see on the "details" page shows which test case the program stops running at when the time limit has exceeded; it's not a test case that causes your program to exceed the time limit. 

I'd recommend checking out accepted submissions from the discuss tab of the problem page or posting your code there to get support from other users. Unfortunately, we do not disclose the time limit as we want our users to debug and improve their code to get it accepted.

**Comment by II11II** [comment]
@LC-Pam 
The algorithm is the same for Java and dart. But TLE appears in dart lang.

![image](https://user-images.githubusercontent.com/45257709/185734089-5c0a9fec-76b0-41ed-b122-0e27fdd733f9.png)
I can guarantee that my code has not an underlying infinite loop.
My algorithm is not too slow and has no high time complexity.

**Comment by II11II** [comment]
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8558 has the same problem as this problem
