### ISSUE TITLE
Major Test Case Missing in https://leetcode.com/problems/minimum-height-trees/

### ISSUE THREAD

**Issue by Rohitesh-Kumar-Jain** [LeetCode-Feedback/LeetCode-Feedback#872]
Major test case missing in [https://leetcode.com/problems/minimum-height-trees/](https://leetcode.com/problems/minimum-height-trees/)

#### Your LeetCode username
rzay

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
A Major Test case is missing in the testing suite, without which Bfs implementation of topological sort (Khan's Algorithm) is getting accepted. This algorithm prunes the leaves and their edges since non leaves are better candidate.  

Test Case: 

10
[[0,3], [1,3], [2,3], [3,4],[4,5], [4,6], [4,6], [6, 7], [6, 8], [6,9]]

         3      -   4  -    6
	   / | \  	|     / | \
	  0  1  2 	5    7  8  9

Answer should be [4]
My code is giving output []

Please look into such cases where more than 2 vertices can have equal number of indegree

#### Code you used for Submit/Run operation

```
#define eb emplace_back
class Solution {
public:
    /*
        Minimum height tree will be formed by the vertex having maximum connections, or in short maximum indegree in case of undirected graph. So start pruning leaves if the graph and their adjacent nodes
    */
    vector<int> findMinHeightTrees(int n, vector<vector<int>>& edges) {
        if (n==0)
            return {};
        if (n==1)
            return {0};
        vector<int> indegree(n, 0);
        vector<vector<int>> adj(n);
        for(auto i: edges) {
            adj[i[0]].eb(i[1]);
            adj[i[1]].eb(i[0]);
            indegree[i[0]]++, indegree[i[1]]++;
        }
        
        deque<int> q;
        
        for(int i=0;i<n;i++){
            if(indegree[i] == 1)
                q.push_back(i);
        }
        
        while(n > 2) {
            int qSize = q.size();
            n -= qSize;
            for(int i=0;i<qSize;i++) {
                int f = q.front(); q.pop_front();
                for(auto i: adj[f]) {
                    indegree[i]--;
                    if(indegree[i] == 1)
                        q.push_back(i);
                }  
            }
        }
        vector<int> ans(q.begin(), q.end());
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Input
```
Your input
10
[[0,3], [1,3], [2,3], [3,4],[4,5], [4,6], [4,6], [6, 7], [6, 8], [6,9]]
Output
[]
Expected
[4]
```

#### Screenshots
Attached screenshot of Submission and output of test case for reference:

<img width="1680" alt="Screenshot 2020-08-28 at 12 48 35" src="https://user-images.githubusercontent.com/62026125/91533028-d3d4e880-e92c-11ea-991b-db4846555e10.png">

**Comment by lc-ivan** [comment]
Hi @Rohitesh-Kumar-Jain ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @Rohitesh-Kumar-Jain ,
Thank you for your feedback regarding this problem. Upon review, our team noted that since this problem was old, there were no validators. After adding missing validators, we found that the provided test case was no longer valid and will not be added. Once again we thank you for your feedback. Happy LeetCoding!

**Comment by Rohitesh-Kumar-Jain** [comment]
Saw your validators, my test case in a valid test case passing all the validators. My input is a tree rooted at 4 and satisfying all the conditions.

**Comment by Rohitesh-Kumar-Jain** [comment]
Please reopen this issue
