### ISSUE TITLE
Problem 27 question text not matching solutions

### ISSUE THREAD

**Issue by pietroreggiani** [LeetCode-Feedback/LeetCode-Feedback#8720]
#### Your LeetCode username

pietro_reggiani

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

These solutions return the length of the elements but it seems to me that the question asks to return
the entire integer vector. When I return the vector as a list I get an error saying that I should return
an integer. I have the feeling that the question was changed without also modifying the
evaluation bot. I might be wrong but I have tried several times and can't find another explanation.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def removeElement(self, nums, val):
        """
        :type nums: List[int]
        :type val: int
        :rtype: int
        """
        i=0
        while i<len(nums):
            
            if nums[i]==val:
                if i ==len(nums)-1:
                    nums[i] = int(val+1)
                    i+=1
                else:
                    nums[i]=nums[i+1]
            else:
                i+=1
        return nums
```

#### Language used for code

Python

#### Expected behavior

I return a list but the bot requests an integer.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The user has to return k. k is the size of the array after the removal.
The integers have to be the first k elements in the array.
All of this is part of the statement.
We appreciate your support!
