### ISSUE TITLE
232. Issue with given solution

### ISSUE THREAD

**Issue by yashkirr** [LeetCode-Feedback/LeetCode-Feedback#8721]
#### Your LeetCode username
yashkirr

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the given solutions for the question, there is a method pop() that has its method definition as:
`public void pop() `

For the leet code question, surely it should be `public int pop()` as when using the solution as an answer for this method it does not run.

#### Code you used for Submit/Run operation

```
public void pop() {
    s1.pop();
    if (!s1.empty())
        front = s1.peek();
}
```
AND

```
public void pop() {
    if (s2.isEmpty()) {
        while (!s1.isEmpty())
            s2.push(s1.pop());
    }
    s2.pop();    
}
```
#### Expected behavior
I was expecting the solution to run as normal and have its test cases accepted, however, I was met with an error that out of scope.

#### Screenshots
![image](https://user-images.githubusercontent.com/7976984/185715228-84f833c1-27de-49c8-add8-c2ef70ef698b.png)

#### Additional context
It is a small issue, but thought it would be useful to correct for those that wouldn't have understood.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by yashkirr** [comment]
It was Java.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback reformatted it and fixed the obvious type issues. we will rewrite it in the future. We appreciate your support!
