### ISSUE TITLE
Description defect - 31. Next Permutation

### ISSUE THREAD

**Issue by alexgor1998** [LeetCode-Feedback/LeetCode-Feedback#8722]
#### Your LeetCode username
alexgor1998

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

According to the description in the task:

> A permutation of an array of integers is an arrangement of its members into a sequence or linear order.
> 
> - For example, for `arr = [1,2,3]`, the following are considered permutations of arr: `[1,2,3]`, `[1,3,2]`, `[3,1,2]`, `[2,3,1]`.

If I understand the task right, `[1,2,3]` has six permutations: `[1,2,3]`, `[1,3,2]`, `[2,1,3]`, `[2,3,1]`, `[3,1,2]`, `[3,2,1]`. So why providing only 4? This may confuse ones who meet the term _permutation_ for the first time as if sor some hidden reason the remaining 2 are unsuitable. "For example" isn't an excuse as it may refer to the sample of the array.

So, the description should better provide the full set of permutations for this array, since it's not large.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
