### ISSUE TITLE
Issue on constraints - 871. Minimum Number of Refueling Stops

### ISSUE THREAD

**Issue by UltimateDip** [LeetCode-Feedback/LeetCode-Feedback#8723]
#### Your LeetCode username

mangoDD

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In **constraints** portion, the positions of two consecutive array element should be **strictly increasing**, but I think mistakenly it was written as non-decreasing

Constraints on question
```
1 <= target, startFuel <= 109
0 <= stations.length <= 500
0 <= position[i] <= position[i+1] < target  // <- This one is buggy, should have been strictly increasing , but showing non-decreasing
1 <= fueli < 109
```

#### Testcase you used for test operation

This is the custom testcase I tried satisfying all given constrains

```
100
10
[[10,60],[20,30],[20,40]]
```

#### Language used for code
C++

#### Expected behavior

According to given conditions and constraints this test case should run, but it has shown error as
```
'positions' must be strictly increasing
```

#### Screenshots

![image](https://user-images.githubusercontent.com/68418035/185728596-47d0491c-9119-4cb2-b8d6-73b2a3b3ec25.png)
![image](https://user-images.githubusercontent.com/68418035/185728584-95bac56e-aab7-4a36-9862-bbcb1ffa7e78.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
