### ISSUE TITLE
Typo in fizzBuzz problem Java Solution

### ISSUE THREAD

**Issue by Maheshkumar-novice** [LeetCode-Feedback/LeetCode-Feedback#8725]
#### Your LeetCode username

mahi-novice

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a typo in the `Java` solution of the `fizzBuzz` problem. In the approach 3 the the hash mentioned as `fizzBizzDict` instead of `fizzBuzzDict`.

#### Expected behavior

It should be `fizzBuzzDict` so it'll be more intuitive to the context of the `fizzBuzz` problem.

#### Screenshots

<img width="627" alt="Screenshot 2022-08-20 at 11 34 58 AM" src="https://user-images.githubusercontent.com/67100964/185731470-6fc262f2-3d89-4083-a028-c1fd6b92b12c.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Maheshkumar-novice** [comment]
Okay @LC-Pam ....You're welcome.

**Comment by Maheshkumar-novice** [comment]
@LC-Pam Any updates on this?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
