### ISSUE TITLE
332. Reconstruct Itinerary 重新安排行程 题目有一条件未翻译

### ISSUE THREAD

**Issue by AmosChenYQ** [LeetCode-Feedback/LeetCode-Feedback#873]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
英文题目有四个条件 中文只有三条

**屏幕截图**
![image](https://user-images.githubusercontent.com/31386769/91536733-bf521980-e947-11ea-9e30-3858ab5d27f8.png)
![image](https://user-images.githubusercontent.com/31386769/91536774-d2fd8000-e947-11ea-954f-ef6843edf846.png)

**Comment by feiceh** [comment]
感谢反馈，题目已更新，请稍后刷新再试试。力扣会定期更新，保障稳定和体验优化。
