### ISSUE TITLE
Bug: Different Runtimes for the Same Code

### ISSUE THREAD

**Issue by KhaledBasiony** [LeetCode-Feedback/LeetCode-Feedback#8730]
#### Your LeetCode username
SquircKle

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Generally Runtime results are not accurate and varies a lot with multiple runs/submissions.

#### Code you used for Submit/Run operation

```
// Counting Bits
class Solution:
    def countBits(self, n: int) -> List[int]:
        ans = [0]
        i=1
        for i in range(1, n+1):
            ones = i != (i>>1)<<1
            ones+=ans[i>>1]
            ans.append(ones)
        return ans
```

#### Language used for code
Python3

#### Expected behavior
**Expected:** Get the _same runtimes_ after consecutive runs or submissions.  
**Actual:**  runtimes vary a lot.

#### Screenshots

![image](https://user-images.githubusercontent.com/67732257/185747206-e9afc272-5978-4b14-84d0-ecbb6e889bce.png)

#### Additional context
As shown in the screenshot, I tried the same code in a custom text case and received **148ms**  
Then submitted the same code 3 times in a row and got 3 different runtime values.  
namely [153ms](https://leetcode.com/submissions/detail/778476716/), [199ms](https://leetcode.com/submissions/detail/778476861/), and [91ms](https://leetcode.com/submissions/detail/778476908/)  

_Note_: this is not specific to this problem.

#### Suggestion
Maybe an average of 100 or 1000 runs for each submission would do the trick?

**Comment by LC-Pam** [comment]
Thank you for reaching out to the Support Team!

This is a very good question here. This is definitely mostly on the server side of things. It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

Other factors that go into this number include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy. If it starts seeming bad or lacking logic, please feel free to reach out and share some of the problems you've seen so we can look to investigate.

I hope this helps to explain what you're seeing a little more. If you have any other questions, please don't hesitate to let us know.
