### ISSUE TITLE
Question - 117. Populating Next Right Pointers in Each Node II

### ISSUE THREAD

**Issue by tobi-oye** [LeetCode-Feedback/LeetCode-Feedback#8731]
#### Your LeetCode username

tobioyewole25

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

After returning the expected return type "Node", there's a runtime error from leetcode's javascript compiler stating the return type "Node" is not the expected return type.

#### Code you used for Submit/Run operation

```
/**
 * @param {Node} root
 * @return {Node}
 */
var connect = function(root) {
return root
}

```
#### Language used for code

Javascript

#### Expected behavior

The code above is expected to run successfully, however it throws a runtime error

#### Screenshots

<img width="989" alt="image" src="https://user-images.githubusercontent.com/38209697/185749601-0224e7c3-2fb5-416a-97f4-309a63855305.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to the Support Team!

This is a very good question here. This is definitely mostly on the server side of things. It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

Other factors that go into this number include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy. If it starts seeming bad or lacking logic, please feel free to reach out and share some of the problems you've seen so we can look to investigate.

I hope this helps to explain what you're seeing a little more. If you have any other questions, please don't hesitate to let us know.
