### ISSUE TITLE
Question 914. X of a Kind in a Deck of Cards Incorrect Expected Output

### ISSUE THREAD

**Issue by PranaySarveiya** [LeetCode-Feedback/LeetCode-Feedback#8732]
#### Your LeetCode username

Bluecrack

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question 914. X of a Kind in a Deck of Cards.
Description states to choose x >= 2, each group has exactly x cards, all cards in a group have the same integer. Example they give for false output is [1, 1, 1, 2, 2, 2, 3, 3], which does not work because groups would be size 3, 3, 2, which are not all the same. 
One test case is [1, 1, 2, 2, 2, 2], which has groups of size 2 and 4, which are not the same (each group does not have exactly x cards), so it should output false. However, the expected output for this is stated as true.

#### Code you used for Submit/Run operation

Code here does not matter
```
```

#### Language used for code

Python

#### Expected behavior

The expected output for the test case [1, 1, 2, 2, 2, 2] should be false, since each group does not have exactly x cards, for x  chosen >= 2. It is currently shows as expected to be true.

#### Screenshots

![Screenshot 2022-08-20 075443](https://user-images.githubusercontent.com/35350206/185752745-e286b1c1-f7d7-4f76-98b0-4208726fc6cf.png)
![Screenshot 2022-08-20 075511](https://user-images.githubusercontent.com/35350206/185752746-8b34b38e-1f1e-41a9-ad9f-e669c4ed5b32.png)

**Comment by theJsTsGuy** [comment]
I am stuck in the same context, can you explain what I might be missing? I don't want to jump to the solutions before trying.
