### ISSUE TITLE
2382. Maximum Segment Sum After Removals - Exact same code gives AC after contest but TLE during contest

### ISSUE THREAD

**Issue by tulkasm** [LeetCode-Feedback/LeetCode-Feedback#8733]
#### Your LeetCode username
tulkasm https://leetcode.com/tulkasm/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Exact same code gives AC when I run after the contest, but TLE during the contest.

#### Code you used for Submit/Run operation
After contest: https://leetcode.com/submissions/detail/778680381/
During contest: https://leetcode.com/contest/biweekly-contest-85/submissions/detail/778612417/
The code is the exact same.

#### Language used for code
Python3

#### Expected behavior

The submission during contest should be accepted, not TLE. I would like to kindly ask for it to be rejudged. Thank you for organizing the contests.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
