### ISSUE TITLE
871. Minimum Number of Refueling Stops

### ISSUE THREAD

**Issue by dacozai** [LeetCode-Feedback/LeetCode-Feedback#8737]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

```plaintext
100
10
[[10,50],[10,60],[20,30],[30,30],[60,40]]
```
Given the above test case, it is an invalid test case. 
However, in the constraint, the description states that position_i <= position_i+1 which is misleading. 
Apparently, the system only accepts the < instead of <=.
This misleading will have some people overthink the question and miss using the merit of this hint in the constraint.
That's all, thanks.

#### Screenshots

<img width="969" alt="Screenshot 2022-08-21 at 9 31 43 AM" src="https://user-images.githubusercontent.com/54406351/185771583-d894c6c5-ac69-45ad-b09a-1f7fa4959888.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
