### ISSUE TITLE
剑指 Offer 59 - II. 队列的最大值 缺少测试用例

### ISSUE THREAD

**Issue by Halliday1013** [LeetCode-Feedback/LeetCode-Feedback#8739]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
man-chuan-qing-meng-ya-xing-he-oe

**Bug 类型**
- [√] 缺少测试用例

**描述**
测试用例：
["MaxQueue","push_back","push_back","pop_front","push_back","max_value"]
[[],[10],[10],[],[9],[]]
不能通过，但是提交后后台通过了答案。

**你使用的语言**
JAVA

**你提交或者运行的代码**
```
class MaxQueue {
    Queue<Integer> A;
    Deque<Integer> B;
    public MaxQueue() {
        A = new LinkedList<>();
        B = new LinkedList<>();
    }
    
    public int max_value() {
        if(A.isEmpty()) return -1;
        return B.peek();
    }
    
    public void push_back(int value) {
        A.add(value);
        while(!B.isEmpty() && B.peekLast() <= value) B.removeLast();  //此处应为B.peekLast() < value
        B.add(value);
    }
    
    public int pop_front() {
        if(A.isEmpty()) return -1;
        int tmp = A.poll();
        if(B.peek() == tmp) B.poll();
        return tmp;
    }
}
```

**期望行为**
添加测试用例：
["MaxQueue","push_back","push_back","pop_front","push_back","max_value"]
[[],[10],[10],[],[9],[]]

**屏幕截图**
![image](https://user-images.githubusercontent.com/62175850/185777228-9418409f-ec8e-43d8-9102-94b6cd9ddd14.png)

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
你好，当前该题已添加测试用例，奖励已发放。
