### ISSUE TITLE
LeetCode 面试题 17.07. 婴儿名字  测试用例检验有误

### ISSUE THREAD

**Issue by GGGGeorge-gao** [LeetCode-Feedback/LeetCode-Feedback#874]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
测试用例通过 38/41，在剩余三个用例中，输出结果与期望结果相符，却依然报出WA，在评论区也有人遇到相似的问题

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {

    private Map<String, String> father = new HashMap<>();
    private Map<String, Integer> map = new HashMap<>();

    public String[] trulyMostPopular(String[] names, String[] synonyms) {
        if (names.length == 0) return new String[0];
        for (String name : names) {
            int idx1 = name.indexOf('(');
            int idx2 = name.indexOf(')');
            int num = Integer.valueOf(name.substring(idx1 + 1, idx2));
            // System.out.println(name.substring(0, idx1));
            map.put(name.substring(0, idx1), num);
        }

        for (String syno : synonyms) {
            String[] s = syno.substring(1, syno.length() - 1).split(",");
            // System.out.println(s[0] + s[1]);
            union(s[0], s[1]);
        }
        StringBuilder sb = new StringBuilder();
        for (String name : map.keySet()) {
            if (!father.containsKey(name)) {
                sb.append(name + '(' + map.get(name) + ')' + ',');
            }
        }
        return sb.toString().split(",");
    }

    private void union(String a, String b) {
        // System.out.println("Union: " + a + "," + b);
        if (!map.containsKey(b) || !map.containsKey(a)) return ;
        String fa = find(a);
        String fb = find(b);
        int sum = map.get(fa) + map.get(fb);
        
        if (fa.compareTo(fb) < 0) {
            father.put(fb, fa);
            map.put(fa, sum);
        } else {
            father.put(fa, fb);
            map.put(fb, sum);
        }
    }

    private String find(String s) {
        if (!father.containsKey(s) || father.get(s).equals(s)) return s;
        // System.out.println(s + "," + father.get(s));
        father.put(s, find(father.get(s)));
        return father.get(s);
    }
}
```

**期望行为**
修正OJ程序

**屏幕截图**
![image](https://user-images.githubusercontent.com/53141406/91552658-bfa9df00-e95e-11ea-9576-fff70465cfd8.png)

**额外的上下文**
以下为其中一个测试用例
["Pwsuo(71)","Prf(48)","Rgbu(49)","Zvzm(31)","Xxcl(25)","Bbcpth(42)","Padz(70)","Jmqqsj(19)","Uwy(26)","Jylbla(65)","Xioal(11)","Npbu(62)","Jpftyg(96)","Tal(46)","Hnc(100)","Yldu(85)","Alqw(45)","Wbcxi(34)","Kxjw(36)","Clplqf(8)","Fayxe(66)","Slfwyo(48)","Xbesji(70)","Pmbz(22)","Oip(2)","Fzoe(63)","Qync(79)","Utc(11)","Sqwejn(19)","Ngi(8)","Gsiiyo(60)","Bcs(73)","Icsvku(1)","Yzwm(92)","Vaakt(21)","Uvt(70)","Axaqkm(100)","Gyhh(84)","Gaoo(98)","Ghlj(35)","Umt(13)","Nfimij(52)","Zmeop(77)","Vje(29)","Rqa(47)","Upn(89)","Zhc(44)","Slh(66)","Orpqim(69)","Vxs(85)","Gql(19)","Sfjdjc(62)","Ccqunq(93)","Oyo(32)","Bvnkk(52)","Pxzfjg(45)","Kaaht(28)","Arrugl(57)","Vqnjg(50)","Dbufek(63)","Fshi(62)","Lvaaz(63)","Phlto(41)","Lnow(70)","Mqgga(31)","Adlue(82)","Zqiqe(27)","Mgs(46)","Zboes(56)","Dma(70)","Jnij(57)","Ghk(14)","Mrqlne(39)","Ljkzhs(35)","Rmlbnj(42)","Qszsny(93)","Aasipa(26)","Wzt(41)","Xuzubb(90)","Maeb(56)","Mlo(18)","Rttg(4)","Kmrev(31)","Kqjl(39)","Iggrg(47)","Mork(88)","Lwyfn(50)","Lcp(42)","Zpm(5)","Qlvglt(36)","Liyd(48)","Jxv(67)","Xaq(70)","Tkbn(81)","Rgd(85)","Ttj(28)","Ndc(62)","Bjfkzo(54)","Lqrmqh(50)","Vhdmab(41)"]
["(Uvt,Rqa)","(Qync,Kqjl)","(Fayxe,Upn)","(Maeb,Xaq)","(Pmbz,Vje)","(Hnc,Dma)","(Pwsuo,Gyhh)","(Gyhh,Aasipa)","(Fzoe,Lcp)","(Mgs,Vhdmab)","(Qync,Rgd)","(Gql,Liyd)","(Gyhh,Tkbn)","(Arrugl,Adlue)","(Wbcxi,Slfwyo)","(Yzwm,Vqnjg)","(Lnow,Vhdmab)","(Lvaaz,Rttg)","(Nfimij,Iggrg)","(Vje,Lqrmqh)","(Jylbla,Ljkzhs)","(Jnij,Mlo)","(Adlue,Zqiqe)","(Qync,Rttg)","(Gsiiyo,Vxs)","(Xxcl,Fzoe)","(Dbufek,Xaq)","(Ccqunq,Qszsny)","(Zmeop,Mork)","(Qync,Ngi)","(Zboes,Rmlbnj)","(Yldu,Jxv)","(Padz,Gsiiyo)","(Oip,Utc)","(Tal,Pxzfjg)","(Adlue,Zpm)","(Bbcpth,Mork)","(Qync,Lvaaz)","(Pmbz,Qync)","(Alqw,Ngi)","(Bcs,Maeb)","(Rgbu,Zmeop)"]

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，建议再仔细调试一下代码（答案有问题）。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路。
