### ISSUE TITLE
A Follow-up Requirement Should be Added - 2380. Time Needed to Rearrange a Binary String

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#8741]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
Brute force with O(n^2) time complexity can get accepted now because of the terrible constraints. But if this problem is used in a real interview, the expected solution must be O(n). Besides, the difficulty of the O(n^2) solution is not enough to be marked as Medium.
So, a follow-up requirement should be added:
Can you solve this problem in O(n) time complexity?

Code you used for Submit/Run operation

O(n^2) brute force:
```
class Solution:
    def secondsToRemoveOccurrences(self, s: str) -> int:

        ans = 0
        while '01' in s:
            s = s.replace('01','10')
            ans+=1
        return ans
```

O(n) solution:
```
class Solution:
    def secondsToRemoveOccurrences(self, s: str) -> int:

        dp = 0
        cnt = 0
        for ch in s:
            if ch=='0':
                cnt+=1
            elif cnt:
                dp=max(dp+1,cnt)
        return dp
```

Language used for code
Python3

Expected behavior
A follow-up requirement should be added:
Can you solve this problem in O(n) time complexity?

**Comment by zhenliang153** [comment]
哈哈，周赛题目好像没见过“扩展”，前面的热题倒是经常这么玩。话说 _O(n)_ 本题数据量扩展到10**5的话目测rating会超过2200

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
