### ISSUE TITLE
Missing Test Case - 2383. Minimum Hours of Training to Win a Competition

### ISSUE THREAD

**Issue by tejasrautmax** [LeetCode-Feedback/LeetCode-Feedback#8742]
class Solution {
public:
    int minNumberOfHours(int initialEnergy, int initialExperience, vector<int>& energy, vector<int>& experience) 
{
        int ans1=0,ans2=0;
        int sum =0;
                                                                                                    int n= energy.size();
        
        for(int i=0;i<n;i++)
        {
            sum = sum+ energy [i];
            
        }
        
        if(initialEnergy >sum)
        {
            ans1 = 0 ;
        }
        else
        {
            ans1= (sum+1)-initialEnergy;
                                    
        }  
         
             int i=0;                 
            while(i<n)
        {
                int dif = 0;                                  
                if(initialExperience <= experience [i])
                 {
                    dif= experience [i]-initialExperience;
                                    // ans2= (initialxEperience dif+1)- initialExperience;
                    ans2= ans2+(dif+1);
                    initialExperience = initialExperience +ans2;
                    initialExperience= initialExperience+ experience[i];
                }   
                                        
                else
                {
                   initialExperience  =        initialExperience  + experience[i];             
               }
                                     
                                     
                                                                    
                i++;  
         }
            
                                                     
        return ans1+ans2;   
    
    }  
    
};

**Comment by ssyphon** [comment]
The following code passes all test cases, despite being incorrect:
`
class Solution {
public:
    int minNumberOfHours(int initialEnergy, int initialExperience, vector<int>& energy, vector<int>& experience) {
        int exp = 0;
        int n = size(experience);
        
        for (int i = 0; i < n; i++) {
            if (initialExperience <= experience[i]) {
                //exp += experience[i] - initialExperience + 1;
                initialExperience += exp += experience[i] - initialExperience + 1;
            }
            
            initialExperience += experience[i];
        }
        
        return max(0, reduce(begin(energy), end(energy)) - initialEnergy + 1) + exp;
    }
};
`
For example, it fails:
1
1
[1,1,1,1]
[1,8,4,50]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result or Submission Link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ssyphon** [comment]
The language is C++ and my comment provides a missing test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
