### ISSUE TITLE
Missing Test Case - 221. Maximal Square

### ISSUE THREAD

**Issue by Bhupesh2001** [LeetCode-Feedback/LeetCode-Feedback#8745]
#### Your LeetCode username
bpattaniak [https://leetcode.com/bpattaniak/](url)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing Test Cases 
The testcase is given in the TXT file below

[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9388817/testcase.txt)

#### Code you used for Submit/Run operation

[ Maximal Square ] [https://leetcode.com/problems/maximal-square/](url)
```
// [ Maximal Square ]
class Solution {
public:
int maximalSquare(vector<vector<char>>& mat) {
        int m = mat.size();
        int n = mat[0].size();
        int ans = 0;
        for(int i=0;i<m;i++)
        {
            for(int j=0;j<n;j++)
            {
                int edge=0;
                int x=i,y=j;
                while(mat[x][y]=='1')
                {
                    int t=edge,a=x-1,b=y-1;
                    bool v=true,h=true;
                    while(t-- && a>-1){
                        if(mat[a--][y]=='0'){
                            v=false;
                            break;
                        }
                    }
                    t=edge;
                    while(t-- && b>-1){
                        if(mat[x][b--]=='0'){
                            v=false;
                            break;
                        }
                    }
                    if(v && h) edge++;
                    if(v && h && x+1<m && y+1<n){
                        x++;
                        y++;
                    }
                    else    break;
                }
                ans=max(edge,ans);
                if(ans*ans==m*n)    return ans*ans;
            }
        }
        return ans*ans;
    }
};

```

#### Language used for code
C++

#### Expected behavior
The given code was accepted when submitted, but is not a optimal solution and should give TLE but it didn't. As there is a missing test case in this question. This test case will give TLE for the above code but The given test case will working fine in a Optimized code.

#### Screenshots
Code was accepted on SUBMIT
![image](https://user-images.githubusercontent.com/53337976/185784524-d19c18f3-019f-47ef-9863-cc22adbac057.png)

Code gave TLE on the given **CUSTOM TESTCASE**
![image](https://user-images.githubusercontent.com/53337976/185784838-9ddb9c2e-9189-41cc-ba84-30939ce54dcb.png)

### The TESTCASE is given in the TXT file below
Custom Testcase :  [testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9388817/testcase.txt)

#### Additional context
Add this test case to accept only optimized code, else non optimized code are also being accepted 
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9388817/testcase.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
