### ISSUE TITLE
Missing Test Case - 958. Check Completeness of a Binary Tree

### ISSUE THREAD

**Issue by Awei2468** [LeetCode-Feedback/LeetCode-Feedback#8746]
#### Your LeetCode username
Awei2222

#### Category of the bug
- [ ] Question

#### Description of the bug
According to the constraints:The number of nodes in the tree is in the range [1, 100], but it's not correct. I declare a array size is 101, and the test case 117 show me that :index 102 out of bounds for type 'int [101]', so I increase the size of array to 201 and pass the question. I think you should check the maximum nodes of tree again.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isCompleteTree(TreeNode* root) {
        queue<TreeNode*> q; q.push(root);
        int v[201] = {0}, j = 0;
        v[j++] = root->val;
        
        while (!q.empty()) {
            for (int i = q.size(); i > 0; --i) {
                TreeNode* f = q.front(); q.pop();
                
                if (f->left) q.push(f->left), v[j++] = f->left->val;
                else ++j;
                
                if (f->right) q.push(f->right), v[j++] = f->right->val;
                else ++j;
            }
        }
        
        --j;
        while (!v[j]) --j;
        for (; j >= 0; --j) {
            if (!v[j]) return false;
        }
            
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
You should check the maximum nodes of tree again and modify constraints.

#### Screenshots
![image](https://user-images.githubusercontent.com/75262964/185788697-1ad3f2cb-1ad9-423b-a571-b3591d95db3f.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to the Support Team!

This is a very good question here. This is definitely mostly on the server side of things. It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

Other factors that go into this number include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy. 

When we test your code, it show accepted: https://leetcode.com/submissions/detail/780520445/
