### ISSUE TITLE
Request to convert from Easy to Medium - 686. Repeated String Match

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#875]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

686. Repeated String Match
https://leetcode.com/problems/repeated-string-match/

I have solved this question on 2nd attempt.

This question requires some more special case handling than normal effort required for an easy problem.
This question has 11th low Acceptance Rate, 32%, of all Easy problems.

Though it is not a must,
request you to consider
making Difficulty of this 'Easy' problem
to a 'Medium' problem.

- This will help with increased satisfaction from users, as being a Medium problem, a question demands more focus from the user, compared to Easy problem.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

An Easy problem should only require a certain amount of effort from user, if it requires more effort then it is better be a Medium difficulty, helps with user satisfaction.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your feedback regarding this problem. Upon review, our team has updated the problem and changes its difficulty. We thank you for your feedback but we will not be rewarding LeetCoins for these types of cases. Thank you again and Happy LeetCoding!
