### ISSUE TITLE
RunTime Error on 190.Reverse Bits problem on JavaScript language

### ISSUE THREAD

**Issue by Ndn1618** [LeetCode-Feedback/LeetCode-Feedback#8750]
#### Your LeetCode username
Ndn1618

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

There is a Runtime error on the 190th problem on JavaScript language. I didn't write any solution, but when I just run the code, I get an error on line 13 in solution.js. It says that n is undefined.

#### Code you used for Submit/Run operation

```
/**
 * @param {number} n - a positive integer
 * @return {number} - a positive integer
 */
var reverseBits = function(n) {
    
};
```

#### Language used for code

JavaScript

#### Expected behavior

I hope you will solve this problem, because I really wanted to solve this question for getting a badge :)

#### Screenshots

<img width="718" alt="image" src="https://user-images.githubusercontent.com/68459485/185800128-f1157178-21de-40e6-93e2-9ff2aab81151.png">

**Comment by Ndn1618** [comment]
@Ashish-Bansal @Miloas @stormsunshine @alphasingh

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to investigate. We appreciate your support!
