### ISSUE TITLE
Grammatical mistake in solution explanation text.

### ISSUE THREAD

**Issue by maverickreal** [LeetCode-Feedback/LeetCode-Feedback#8751]
#### Your LeetCode username

maverick09

#### Category of the bug
- [ ] Language

#### Description of the bug

There is an error in the textual explanation of the solution 3 of the problem (https://leetcode.com/problems/next-greater-element-ii/solution/), as highlighted in the image. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

"nums\big[stack[top]\big] ≤ nums[i]." should be replaced with "nums[stack[top]] ≤ nums[i]."

#### Screenshots

![Screenshot from 2022-08-21 20-56-07](https://user-images.githubusercontent.com/57585749/185800363-46955563-4fbc-44fc-8f77-2a9dd66bbe2c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
