### ISSUE TITLE
Missing Test Case - 28. Implement strStr()

### ISSUE THREAD

**Issue by Jonqora** [LeetCode-Feedback/LeetCode-Feedback#8753]
#### Your LeetCode username

ellenlloyd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An incorrect solution is wrongly accepted by the judge for problem [28. Implement strStr()](https://leetcode.com/problems/implement-strstr/)

#### Code you used for Submit/Run operation

```py
# Implement strStr()
class Solution:
    def strStr(self, haystack: str, needle: str) -> int:
        """
        IDEA: I am learning how to implement the Knuth-Morris-Pratt algorithm
        """
        h = len(haystack)
        n = len(needle)
        if h < n:
            return -1
        
        kmp = [0] * n
        kmp[0] = -1
        
        # INCORRECT IMPLEMENTATION HERE
        # build the kmp search table in O(n) time  
        j = 0
        for i in range(1, n):
            if needle[j] == needle[i]:
                kmp[i] = kmp[j]
                j += 1
            else:
                kmp[i] = j
                j = kmp[j] + 1
        print(kmp)
        
        # use the search table to look through haystack in O(h) time
        n0 = 0
        for h0 in range(h):
            while n0 > -1 and needle[n0] != haystack[h0]:
                n0 = kmp[n0]
            n0 += 1
            if n0 == n:  # found all of needle
                return h0 + 1 - n0
        return -1
```

#### Language used for code

Python 3

#### Expected behavior

The above solution code should not be accepted. It gives an incorrect result for certain inputs like 
```py
"acbabcbabacba"
"acbabacba"
```
The above soution incorrectly finds a "match" at index `4` instead of returning `-1` for no match. The incorrect "match" that is found matches almost all letters of the needle, but not the first letter.
**Expected behavior:** this solution should fail with "Wrong Answer" when submitted to the judge
**Actual behavior:** the solution passes all test cases and is marked "Accepted" by the judge

#### Screenshots

When running the demonstrated input as a test case, the error in this solution can be seen. But there are no test cases that detect this error during submission.
![image](https://user-images.githubusercontent.com/31304746/185804604-181e0cc4-a2a6-4684-866e-05d7509ce24b.png)

#### Additional context

Guess I need to re-learn that Knuth-Morris-Pratt algorithm... properly this time! 😅

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
