### ISSUE TITLE
Error in the description - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by Socrat35** [LeetCode-Feedback/LeetCode-Feedback#8754]
#### Your LeetCode username
S0crat3s

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the description for the problem 14, using the Java language, one constraint is described as "0 <= strs[i].length <= 200". However, it should read as "0 <= strs[i].length() <= 200" since we want the length of the string, which using Java is a function, and not a property.

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The constraints are not in any language. They are general info. We appreciate your support!
