### ISSUE TITLE
Please describe constraints more.

### ISSUE THREAD

**Issue by resotto** [LeetCode-Feedback/LeetCode-Feedback#8755]
#### Your LeetCode username
resotto

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Not bug but the description of this problem should be improved:
https://leetcode.com/problems/maximum-width-of-binary-tree/

The solutions explained in the "Solution" page use `index * 2 + 1` and `index * 2 + 2` but these can be integer overflow when the height of the tree excesses 30 (since Integer.MAX_VALUE == 2^31 - 1).
So, how about adding more description which denotes something like `height of the tree <= 30` in constraint part? (this should be fair)

For example, let's think about the following test case:
```
                               1
                             /    \
                            2      3
                          /          \
                         4             5
                       /                \
                 (omit)                  (omit)
```
Number of nodes should be less than or equal to 3000 but also its height can be larger than 30.

#### Code you used for Submit/Run operation
```java
public int widthOfBinaryTree(TreeNode root) {
	// time: O(N) where N is number of nodes in the binary tree
	// space: O(W) where W is width of the tree (2^(logN) == N)
	if (root == null) {
		return 0;
	}
	var q = new LinkedList<Pair<TreeNode, Integer>>();
	q.add(new Pair(root, 0));
	var ans = 0;
	while (0 < q.size()) {
		var size = q.size();
		var left = 0;
		var leftSet = false;
		for (int i = 0; i < size; i++) {
			var p = q.poll();
			var node = p.getKey();
			var degree = p.getValue();
			if (!leftSet) {
	        		ans = Math.max(ans, 1);
				leftSet = true;
				left = degree;
			} else {
        			ans = Math.max(ans, degree - left + 1);
			}
			if (node.left != null) {
				q.add(new Pair(node.left, degree*2+1));
			}
			if (node.right != null) {
				q.add(new Pair(node.right, degree*2+2));
			}
		}
	}
	return ans;
}
```

PS
This code should create valid test case with 32 * 2 nodes and height 32 but got `java.lang.OutOfMemoryError`.
From this perspective, the constraints should be updated as well.

```java
  public static void main(String[] args) {
    var sb = new StringBuilder();
    sb.append('[');
    long n = 1;
    for (int i = 0; i < 32; i++) {
      for (long j = 0; j < n; j++) {
        if (j == 0 || j == n - 1) {
          sb.append('1').append(',');
        } else {
          sb.append("null").append(',');
        }
      }
      n <<= 1;
    }
    sb.setLength(sb.length() - 1);
    sb.append(']');
    System.out.println(sb.toString());
  }
```

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
