### ISSUE TITLE
599. Minimum Index Sum of Two Lists - Typo

### ISSUE THREAD

**Issue by kroebuck** [LeetCode-Feedback/LeetCode-Feedback#8756]
#### Your LeetCode username
kroebuck

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a typo in the constraint section. Under the constraints section, the last two bullet points read:
"All the stings of list1 are unique.
All the stings of list2 are unique."

#### Expected behavior
The words "stings" should instead read "strings". The bullet points should read:
"All the strings of list1 are unique.
All the strings of list2 are unique."

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
