### ISSUE TITLE
Tree Visualizer bug?

### ISSUE THREAD

**Issue by resotto** [LeetCode-Feedback/LeetCode-Feedback#8757]
#### Your LeetCode username
resotto

#### Category of the bug
Tree Visualizer

#### Description of the bug
Tree Visualizer showed wrong tree structure for the test case below on [the problem](https://leetcode.com/problems/maximum-width-of-binary-tree/).

#### Test case
```
[1,1,1,1,null,null,1,1,null,null,null,null,null,null,1]
```

#### Expected behavior(result)
```
            1
           /  \
         1     1
        /        \
      1           1
     /              \
    1                1         
```

#### Screenshots
![Screen Shot 2022-08-22 at 23 15 57](https://user-images.githubusercontent.com/19743841/185943486-7e746280-8ccb-4973-af20-ae3973ba3fa0.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The visualizer is correct. This is not the tree that you want to add.
[1,1,1,1,null,null,1,1,null,null,1] is the tree for what you shared.
Please feel free to refer the discuss section of the problem !
We appreciate your support!
