### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by ManishBirthlia** [LeetCode-Feedback/LeetCode-Feedback#8758]
#### Your LeetCode username

Manish Kumar Birthlia

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There should not be int overflow in the compiler process because we are already assigning long long inside the function.

#### Code i used for Submit/Run operation
```
// Validate Binary Search Tree
class Solution {
public:
    bool helper(TreeNode* root,long long l,long long r){
        if(!root) return true;
        if(root->val>=l && root->val<=r){
            return helper(root->left,l,root->val-1) && helper(root->right,root->val+1,r);
        }else{
            return false;
        }
    }
    bool isValidBST(TreeNode* root) {
        if(root==NULL) return true;
        return helper(root,-pow(2,31),pow(2,31)-1);
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
There should not be int overflow in the compiler process because we are already assigning long long inside the function and there should be Successful submission.

#### Screenshots
![leetcode](https://user-images.githubusercontent.com/96776615/185942929-6604e36e-eda0-4492-aac6-b8d1ed490ecd.jpeg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The issue comes from not casting the integers.  please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!

We appreciate your support!
