### ISSUE TITLE
470. Implement Rand10() Using Rand7(), bug in Rust version (1..6 instead of 1..7)

### ISSUE THREAD

**Issue by joric** [LeetCode-Feedback/LeetCode-Feedback#876]
#### Your LeetCode username
Joric

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language

#### Description of the bug
470. Implement Rand10() Using Rand7(), bug in Rust version (1..6 instead of 1..7)

#### Code you used for Submit/Run operation

```
impl Solution {
    pub fn rand10() -> i32 {
        for _ in 1..100 {
            print!("{} ", rand7());
        }
        0
    }
}
// 5 5 2 4 2 3 3 4 1 3 1 5 5 2 2 4 2 6 1 1 2 4 6 5 4 2 2 4 3 1 2 1 5 1 1 2 5 2 4 6 1 5 6 4 5 5 6 6 3 3 6 5 2 4 6 5 6 6 6 5 2 5 1 4 4 4 6 4 6 3 6 5 2 5 6 3 3 5 3 1 6 1 5 2 2 2 2 6 3 2 4 2 3 2 5 3 1 4 4 
```

#### Language used for code
Rust

#### Expected behavior
rand7 should be in a range 1..7, need to be fixed in a Rust test case checker

Possible solution:
```rust
fn mrand7() -> i32 {
    use rand::{thread_rng, Rng};
    let mut rng = thread_rng();
    rng.gen_range(1, 8) // this is the proper range, 1..7
}

impl Solution {
    pub fn rand10() -> i32 {
        let mut row;
        let mut col;
        let mut idx;
        loop {
            row = mrand7();
            col = mrand7();
            idx = col + (row - 1) * 7;
            if idx <= 40 { break; }
        }        
        1 + (idx - 1) % 10
    }
}
```

#### Additional context
https://leetcode.com/problems/implement-rand10-using-rand7/discuss/816392/Incorrect-implementation-of-rand7()-in-Rust
https://leetcode.com/problems/implement-rand10-using-rand7/discuss/667487/Rust-Approach-1-not-accepted

**Comment by lc-pam** [comment]
Hi @joric 
Thank you for raising this issue to our attention! I've filed this issue to our engineers to investigate and I'll get back to you as soon as I receive updates from the team.

**Comment by lc-pam** [comment]
Hi @joric 
Thanks for your time. I just received an update from the team and would like to share it with you. We've fixed the issue thanks to your report. Please let us know in case it happens again. Thank you again for raising the issue to our attention.
