### ISSUE TITLE
[Missing test cases] #434. Number of Segments in a String

### ISSUE THREAD

**Issue by Purple-tulip** [LeetCode-Feedback/LeetCode-Feedback#8760]
#### Your LeetCode username

HoratioCaine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
s = "   123"
The correct number of segments in s is 1.
In the next code, the result is 2, but it can pass the testcase.

#### Code you used for Submit/Run operation

```
class Solution:
    def countSegments(self, s: str) -> int:

        if len(s.strip()) < 1:
            return 0

        count = 0
        
        for i in range(len(s.strip()) - 1):
            if s[i] == " " and s[i + 1] != " ":
                count += 1
        return count + 1
```

#### Language used for code

Python

#### Expected behavior

fail the testcase.

#### Screenshots

![image](https://user-images.githubusercontent.com/40619268/186059975-450d7c1c-69aa-4de7-8a03-422f3c6b6e70.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
