### ISSUE TITLE
contradictory test cases for jump problem https://leetcode.com/problems/jump-game/

### ISSUE THREAD

**Issue by logicMark** [LeetCode-Feedback/LeetCode-Feedback#8761]
The description and the actual acceptance seems different for the question https://leetcode.com/problems/jump-game/
and as per the description the array `nums[]` index position describes the number of jumps to be made and if it reaches the last position it should return true.

Below is an example where the expected output should be false as it can never reach the last subscript but it says true
![image](https://user-images.githubusercontent.com/32538849/186079328-7700b006-bcb0-453b-8313-345cd12c9eaf.png)

In the example test cases, it was mentioned as jump by 1 index and even if it is followed then the below test case would fail
![image](https://user-images.githubusercontent.com/32538849/186079734-ddc1fe50-6c69-4d6a-bc9f-21806a8e592c.png)

[2,0,0] if i jump from 0 index to 1 index, it would still be false but the expected says true. In short both the test cases are contradictory. Also if its possible to exceed the array's length even that case should be true but its not conveyed anywhere. Kindly have a look at the testcases and description. Thank you

**Comment by logicMark** [comment]
Adding another reference here 

https://leetcode.com/problems/jump-game/discuss/2467074/Weird-test-cases-scenario-jump-game

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by logicMark** [comment]
Thanks @LC-Pam Please find the links below 

https://leetcode.com/submissions/detail/780943974/   for test case  of array` [2,0,0]`
https://leetcode.com/submissions/detail/780934089/ for test case of array `[2,5,0,0]`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by logicMark** [comment]
@LC-Pam Thanks for the reply, please help us with the judger references.
