### ISSUE TITLE
15. 三数之和

### ISSUE THREAD

**Issue by lqzo** [LeetCode-Feedback/LeetCode-Feedback#8762]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
[liqingzhou](https://leetcode.cn/u/liqingzhou/)

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[15. 三数之和](https://leetcode.cn/problems/3sum/) 题目中的 `示例 2、3` 及提示的 `nums.length` 范围存在错误, 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/30641714/186081251-e8cd1a86-ba70-43f6-b06a-43d495e8c82a.png">

如果使用 `nums.length` 小于 3 的示例，代码会执行错误，如下：
<img width="486" alt="image" src="https://user-images.githubusercontent.com/30641714/186081399-9a28385b-e763-4416-8acd-7085120af7c0.png">

英文版的提示中 `nums.length` 的范围就是 [3, 3000]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/30641714/186081657-a517572f-aae2-43d7-bb20-8dc0e2eb4369.png">

**期望行为**
更正题目中错误的 `示例2、3` 与 `nums.length` 的范围提示

**Comment by lqzo** [comment]
而且很奇怪的是 [剑指 Offer II 007. 数组中和为 0 的三个数](https://leetcode.cn/problems/1fGaJU/)，这道题的判题程序就允许 `nums.length` 小于 3

**Comment by BrambleWave** [comment]
你好，当前题目描述已更新，ID：[liqingzhou](https://leetcode.cn/u/liqingzhou/)  给予积分奖励，请查收。
