### ISSUE TITLE
Missing a test case in #234

### ISSUE THREAD

**Issue by revug** [LeetCode-Feedback/LeetCode-Feedback#8764]
#### Your LeetCode username
codingstar1

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Missed test case:
[0,1,0,1,0,2,1,0,2,0,2,0]

#### Code you used for Submit/Run operation

Wrong solution that passes your current test cases:
```ruby
def is_palindrome(head)
    last = head
    n = 0
    until last.nil?
        last = last.next
        n += 1        
    end
    s = Array.new(10, 0)
    node = head
    (1..n/2).each do |i|
        s[node.val] += i * (1 + (i.even? ? 1 : 0))
        node = node.next
    end
    node = node.next if n.odd?
    (((n + 3) / 2)..n).each do |i|
        rel_idx = n - i + 1
        s[node.val] -= rel_idx * (1 + (rel_idx.even? ? 1 : 0))
        node = node.next
    end
    s.all?(&:zero?) 
end
```

#### Language used for code

ruby

#### Expected behavior

The solution should be rejected but it doesn't.
Proof: https://leetcode.com/submissions/detail/781206238/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by revug** [comment]
Another method to pass all your test cases with a wrong solution is to sum squares of indice:
Missed test case: [0,0,1,1,2,1,2,2,0,0]
Wrong solution:
```ruby
def is_palindrome(head)
    last = head
    n = 0
    until last.nil?
        last = last.next
        n += 1        
    end
    s = Array.new(10, 0)
    node = head
    (1..n/2).each do |i|
        s[node.val] += i*i
        node = node.next
    end
    node = node.next if n.odd?
    (((n + 3) / 2)..n).each do |i|
        rel_idx = n - i + 1
        s[node.val] -= (rel_idx * rel_idx)
        node = node.next
    end
    s.all?(&:zero?) 
end
```
Proof: https://leetcode.com/submissions/detail/781174619/

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by revug** [comment]
Hi! Thank you for coins but seems like you haven't payed attention to my last comment ([link](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8764#issuecomment-1224678109))
It is still possible to pass all the test cases with that wrong solution. You need to add  [0,0,1,1,2,1,2,2,0,0] to your test cases.
Proof that the wrong solution is still accepted: https://leetcode.com/submissions/detail/784428407/
