### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by YASH-ROCKSTAR** [LeetCode-Feedback/LeetCode-Feedback#8768]
#### Your LeetCode username
_191500929

#### Category of the bug
- [ ] Question - Find Peak of the element
- [ ] Solution -
- public int findPeakElement(int[] nums) {
        int s=0;
        int e=nums.length-1;
        while(s<e){
            int mid=s+(e-s)/2;
            if(nums[mid]>nums[mid+1]){
                e=mid;
            }
            else{
                if(nums[mid]<nums[mid+1]){
                    s=mid+1;
                }
            }
        }
        return s;
    }
- [ ] Language - JAVA
- [ ] Missing Test Cases 
[1,9,2,4,2,1,3]
Expected output is-6
My output

#### Description of the bug

Here comes the discussion when we have put our test cases than expected output is something according to leetcode
and our output is another but is show answer is correct and passing the solution .
Why does it only return peak from mid-right only?
In my answer, it is returning answer from the mid-left side

#### Code you used for Submit/Run operation
```
class Solution {
    public int findPeakElement(int[] nums) {
        int s=0;
        int e=nums.length-1;
        while(s<e){
            int mid=s+(e-s)/2;
            if(nums[mid]>nums[mid+1]){
                e=mid;
            }
            else{
                if(nums[mid]<nums[mid+1]){
                    s=mid+1;
                }
            }
        }
        return s;
    }
}
```

#### Screenshots

![2022-08-23](https://user-images.githubusercontent.com/67096014/186212379-b93e4531-cb2b-46a8-b2e3-edd58631ee86.png)

#### Additional context

PLEASE CORRECT THE BUG STATED ABOVE IT SHOULD BE GIVEN AT LEAST WRONG ANSWER

**Comment by LC-Pam** [comment]
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
