### ISSUE TITLE
contradiction in evaluation of - 201. Bitwise AND of Numbers Range

### ISSUE THREAD

**Issue by mdcse** [LeetCode-Feedback/LeetCode-Feedback#8769]
#### Your LeetCode username
mdcse

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

my code is passing the test case with custom input
600000000
2147483645
but it is giving TLE after submission on the same input.

#### Code you used for Submit/Run operation

```
// Bitwise AND of Numbers Range
class Solution {
public:
    int rangeBitwiseAnd(int left, int right) {
        long res = left;
        
        long i = left;
        
        while(i <= right)
        {
            res = res & i;
            i++;
        }
        
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior
It should pass passing or failing for both custom test or after submission.
it is giving bad user experience.

#### Screenshots

<img width="1280" alt="bitwise" src="https://user-images.githubusercontent.com/88222476/186222525-cc1380cc-80fa-47b8-bd21-40e766f5dc46.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
