### ISSUE TITLE
Description not accurate - 902. Numbers At Most N Given Digit Set

### ISSUE THREAD

**Issue by escrowdis** [LeetCode-Feedback/LeetCode-Feedback#877]
#### Your LeetCode username

escrowdis

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

This question doesn't mention if there are repeated elements or not. 
If there is, the answer is incorrect. For an example shown below, the answer should be `60` but not `70`, the value from the expected field. The answer would be different if any subsets with the same data can be formed by different element of the same value, like the first two `'1'` can form four `'11'` .
```
["1","1","3","5","7"]
150
```

#### Code you used for Submit/Run operation

```
class Solution {
    
    vector<int> v_tmp = {1};
    
    int helper(vector<string> &D, string num) {
        if (num.empty())
            return 1;
        auto itr_upper = upper_bound(D.begin(), D.end(), string(1, num[0])),
            itr_lower = lower_bound(D.begin(), D.end(), string(1, num[0]));
        cout << (itr_lower - D.begin())<<", "<<(itr_upper - itr_lower) <<endl;
        int res = v_tmp[num.size() - 1] * (itr_lower - D.begin());
        num.erase(0, 1);
        res += (itr_upper - itr_lower) * helper(D, num);
        
        // cout <<num <<", "<<res<<endl;
        return res;
    }
    
public:
    int atMostNGivenDigitSet(vector<string>& D, int N) {
        // 4362 [1,3,4,7]
        // 1 4
        // 2 4^2
        // 3 4^3
        // 4 upper_bnd traverse
        
        // cal sets under D with the number one at the first digit
        int n = D.size(), res = 0, tmp = 1;
        for (int i = 0; i < floor(log10(N)); ++i) {
            res += (tmp *= n);
            v_tmp.emplace_back(tmp);
        }
        // cout << res<<endl;
        res += helper(D, to_string(N));
        
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Mentioned in '**Description of the bug**'.

**Comment by lc-pam** [comment]
Hi @escrowdis 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @escrowdis ,
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!

**Comment by escrowdis** [comment]
Hi @lc-pam,

Looks great! Thank you for your time and support!
