### ISSUE TITLE
Missing Test Case - 1011. Capacity To Ship Packages Within D Days

### ISSUE THREAD

**Issue by iBvishal** [LeetCode-Feedback/LeetCode-Feedback#8770]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a missing test case

**INPUT 1**
[2,1,3,2]
2
**Result**
5

**INPUT 2**
[2,2,3,1]
2
**Result**
4

Ideally in both the cases it should give the same result as the order of input don't matter and we can pair _(2, 2)_ and _(3, 1)_

#### Code you used for Submit/Run operation
The following code was submitted successfully 

```
class Solution {
public:
    bool helper(int mid,vector<int>& weights,int days){
        int count=1,sum=0;
        
        for(int i=0;i<weights.size();i++){
            sum+=weights[i];
            if(sum>mid){
                count++;
                sum=weights[i];
            }
        }
        if(count<=days)
            return true;
        return false;
    }
    
    int shipWithinDays(vector<int>& weights, int days) {
        int maxCapacity=0;
        int n=weights.size();
        
        for(int i=0;i<n;i++)
            maxCapacity+=weights[i];
        
        int low=*max_element(weights.begin(),weights.end()),high=maxCapacity;
        int result;
        
        while(low<=high){
            int mid=low+(high-low)/2;
            if(helper(mid,weights,days)){
                result=mid;
                high=mid-1;
            }
            else
                low=mid+1;
        }
        return result;
    }
};
```

#### Language used for code
C++

#### Expected behavior

- The Above submission should fail with wrong answer

**Comment by stormsunshine** [comment]
Who says the order doesn't matter? It is clearly stated in problem description: in the order given by `weights`.

Also, Example 1 states that the cargo must be shipped in the order given.
