### ISSUE TITLE
Missing Test Case - 2229. Check if an Array Is Consecutive

### ISSUE THREAD

**Issue by dluciano** [LeetCode-Feedback/LeetCode-Feedback#8771]
#### Your LeetCode username

dwluciano

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

I submitted a solution for question `2229. Check if an Array Is Consecutive` that was accepted, however one simple and important test case actually failed when executed from Run Code. Test case: [0,10]

#### Code you used for Submit/Run operation

```
// 2229. Check if an Array Is Consecutive
public class Solution {
  public bool IsConsecutive(int[] nums) {
    var (min, max, sum, zeros) = (long.MaxValue, long.MinValue, 0L, 0L);
    foreach(var x in nums){
      if(x == 0){
        zeros++;
        continue;
      }
      (min, max, sum) = (Math.Min(min, x), Math.Max(max, x), sum + x);
    }
      
    if(zeros > 1)
      return false;
    if(nums.Length == 1)
      return true;
    long Gauss(long x) => ((long)Math.Pow(x, 2) + (long)x)/2;
    // Console.WriteLine($"sum: {sum}, ({Gauss(max)} - {Gauss(min)}) {Gauss(max) - Gauss(min)}");
    return sum == (Gauss(max) -  Gauss(min - 1));
  }
}
```

#### Language used for code

C#

#### Expected behavior

The test case [0,10] must fail on invalid submissions.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
