### ISSUE TITLE
Missing Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by iamshivi114** [LeetCode-Feedback/LeetCode-Feedback#8772]
]Username: iamshivi11

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
I submitted a solution to the problem - Third Maximum Number, which got accepted as a "Success" but is failing a test case I have in my head.  The test case being - Array : [1, Integer.MIN_VALUE, Integer.MIN_VALUE].

#### Code you used for Submit/Run operation

```
// Third Maximum Number
class Solution {
    public int thirdMax(int[] nums) {
        int fMax = nums[0];
        int sMax = Integer.MIN_VALUE, tMax = Integer.MIN_VALUE;
        int counter = 0;

        for (int i = 1; i < nums.length; i++) {

            if (fMax <= nums[i]) {
                if (fMax == nums[i]) {
                    counter++;
                    continue;
                }
                tMax = sMax;
                sMax = fMax;
                fMax = nums[i];
            } else if (sMax <= nums[i]) {
                if (sMax == nums[i] && nums[i] != Integer.MIN_VALUE) {
                    counter++;
                    continue;
                }
                tMax = sMax;
                sMax = nums[i];
            } else if (tMax < nums[i] && sMax != nums[i] && fMax != nums[i]) {
                tMax = nums[i];
            }
        }

        return nums.length - counter > 2 ? tMax : fMax;
    }
}
```

#### Language used for code
Java

#### Expected behavior
In this case, the output for the code would be Integer.MIN_VALUE whereas according to the description of the problem, the output should have been 1.

**Comment by stormsunshine** [comment]
The minimum value in the array is Integer.MIN_VALUE, and since the array has three distinct values, the third maximum number is Integer.MIN_VALUE. Is there any problem?

**Comment by iamshivi114** [comment]
@stormsunshine The array doesn't have three distinct values. It has two distinct values - 1 and Integer.MIN_VALUE. Integer.MIN_VALUE is present twice in the array.
Since there aren't three distinct values, the output should have been the maximum value i.e., 1, but instead it is Integer.MIN_VALUE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stormsunshine** [comment]
Sorry, my bad. I thought the three values were 1, Integer.MIN_VALUE and Integer.MAX_VALUE.

The array should be as follows.

```
[1,-2147483648,-2147483648]
```

> @stormsunshine The array doesn't have three distinct values. It has two distinct values: 1 and Integer.MIN_VALUE. Integer.MIN_VALUE is present twice in the array. Since there aren't three distinct values, the output should have been the maximum value i.e., 1, but instead it is Integer.MIN_VALUE.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
