### ISSUE TITLE
The "1484. Group sold products by the date" question seems not to work in PL/SQL

### ISSUE THREAD

**Issue by mbeceanu** [LeetCode-Feedback/LeetCode-Feedback#8773]
#### Your LeetCode username
mbeceanu

#### Category of the bug
- [ ] Question
- [x ] Solution
- [x ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The set of SQL functions made available for solving this problem in PL/SQL seems not to include a common function, LISTAGG, which should obviously be part of the solution. I looked up the Oracle database version and LISTAGG should be included. I also tried older and alternative names for this function, but none worked.
I submitted correct solutions for this problem using the other two SQL versions, MySQL and MS SQL, with the necessary changes. Only the Oracle solution did not work.
Hints would also be appreciated.

#### Code you used for Submit/Run operation

```
-- select sell_date as "sell_date", count(distinct product) as "num_sold",
-- listagg(product)
-- from activities group by sell_date
select listagg(product) from activities
-- select max(product) from activities
-- select group_concat(product) from activities
-- select string_agg(product) from activities
-- select wm_concat(product) from activities
-- select concat_ws(product) from activities
-- select * from v$version
-- select object_name from all_objects where object_type in ('FUNCTION','PROCEDURE') and object_name='LISTAGG'
```

#### Language used for code

Oracle (PL/SQL)

#### Expected behavior

I expected a list of all "product" from table "activities" to be produced, as a concatenated string with no separators. Instead, I got a message of "Runtime Error".

#### Additional context

I also tried the following other SQL aggregate functions: max, group_concat, string_agg, wm_concat, concat_ws. None of them worked except for max (which has a different purpose, of course). I do not know the correct name of this function, but based on the Oracle database version LISTAGG should have worked.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The main oracle solution uses LISTAGG.
LISTAGG is used in a wrong way.
[Database SQL Language Reference](https://docs.oracle.com/cd/E11882_01/server.112/e41084/functions089.htm#SQLRF30030)
This links shows how to use it.
We appreciate your support!
