### ISSUE TITLE
Missing Test Case - 326. Power of Three

### ISSUE THREAD

**Issue by Shourya7408** [LeetCode-Feedback/LeetCode-Feedback#8776]
#### Your LeetCode username

Shourya2801

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Following code has been accepted but it must give wrong answer for n=-1

#### Code you used for Submit/Run operation

```
// Power of Three
class Solution {
public:
    bool isPowerOfThree(int n) {
        while(n%3==0 && n>1){
            n/=3;
        }
        return abs(n)==1;
    }
};
```

#### Language used for code

C++

#### Expected behavior
I expected to see a missing testcase n=-1 include in the testcase because above code should not be accepted.

#### Screenshots

<img width="958" alt="Screenshot 2022-08-24 114120" src="https://user-images.githubusercontent.com/68144777/186343931-a26b393b-e805-4b7f-987f-17e133dcdaba.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
