### ISSUE TITLE
Missing Test Case - 326. Power of Three

### ISSUE THREAD

**Issue by aospiridonov** [LeetCode-Feedback/LeetCode-Feedback#8777]
#### Your LeetCode username
aospiridonov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Time Limit Exceeded (6112 / 21038 test cases passed.)
Tried other different algorithm implementations but still Time Limit Exceeded.

#### Code you used for Submit/Run operation

```
// Power of Three
class Solution {
  bool isPowerOfThree(int n) {
    return n > 0 && 1162261467 % n == 0;
  }
}
```

#### Language used for code
Dart

#### Expected behavior
Increase time limits for dart or fix a bug.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by nskybytskyi** [comment]
I don't know what changed over nine months 😅 but the issue appears to be resolved now, as your code gets accepted ([submission link](https://leetcode.com/problems/power-of-three/submissions/921628871/)). Could you please verify this behavior and close the issue if so?

Note: #8558 is a similar issue that appears to be resolved now too.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
