### ISSUE TITLE
Missing test case: 1564. Put Boxes Into the Warehouse I

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#878]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Several solutions from discuss section are accepted, but fail on the test case (please see below)

[2, 3]
[6, 5, 5, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

#### Code you used for Submit/Run operation
<pre>
// Java
class Solution {
    public int maxBoxesInWarehouse(int[] boxes, int[] warehouse) {
        Arrays.sort(boxes);
        for(int i = 1; i < warehouse.length; i++){
           warehouse[i] = Math.min(warehouse[i - 1], warehouse[i]);
        }
        int score = 0;
        for(int warehousePosition = warehouse.length - 1, boxPosition = 0; warehousePosition >= 0; warehousePosition--){
            if(boxes[boxPosition] <= warehouse[warehousePosition]){
                boxPosition++;
                score++;
            }
        }
        return score;
    }
}
</pre>

<pre>
// Java
class Solution {
    public int maxBoxesInWarehouse(int[] boxes, int[] warehouse) {
        if (warehouse.length == 0) return 0;
        Stack<Integer> stack = new Stack<>();
        int min = warehouse[0];
        stack.push(min);
        for (int i = 1; i < warehouse.length; i++) {
            if (min >= warehouse[i]) {
                min = warehouse[i];
                stack.push(min);
            }
        }
        Arrays.sort(boxes);
        int curr = 0, res =0;
        for (int i = warehouse.length - 1; i >= 0; i--) {
            if (stack.peek() < warehouse[i]) {
                if (boxes[curr] <= stack.peek()) {
                    curr++;
                    res++;
                }
            } else if (stack.peek() == warehouse[i]) {
                if (boxes[curr] <= stack.peek()) {
                    curr++;
                    res++;
                }
                stack.pop();
            }
        }
        return res;
        
    }
}
</pre>

<pre>
# Python 3
class Solution:
    def maxBoxesInWarehouse(self, boxes: List[int], warehouse: List[int]) -> int:
        if not warehouse: return 0
        cur_min, l_warehouse = warehouse[0], len(warehouse)
        for i in range(l_warehouse):
            cur_min = min(cur_min, warehouse[i])
            warehouse[i] = cur_min
        boxes.sort()    
        ans = j = 0
        for i in range(l_warehouse-1, -1, -1):
            if warehouse[i] >= boxes[j]: j += 1
        return j
</pre>

#### Language used for code

Java, Python 3

#### Expected behavior

The solutions should not be accepted because they fail on a test case (Runtime Error)

#### Additional context

Solutions in discuss section:
https://leetcode.com/problems/put-boxes-into-the-warehouse-i/discuss/815473/Java-concise-solution
https://leetcode.com/problems/put-boxes-into-the-warehouse-i/discuss/815318/Simple-JAVA-Solution-with-Stack
https://leetcode.com/problems/put-boxes-into-the-warehouse-i/discuss/815811/Python-3-or-Intuitive-Greedy-%2B-Sorting-or-Explanation

**Comment by lc-pam** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
