### ISSUE TITLE
Additional testcases for two-sum

### ISSUE THREAD

**Issue by JJ-small** [LeetCode-Feedback/LeetCode-Feedback#8780]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+] Missing Test Cases 

#### Description of the bug

I've try to understand some of best solutions of https://leetcode.com/problems/two-sum/ And release some of that solutions home. But most solutions with unordered_map fail some of my testcase.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        std::unordered_map<int, int> _map;
        for (int i = 0; i < nums.size(); i++)
        {
            int num = nums[i];
            int cp = target - num;
            auto it = _map.find(cp);
            if (it != _map.end()){
            return { it->second,i };
            }
            else
                _map[num] = i;

        }
        return {};
    }
};
```

#### Language used for code

C++

#### Expected behavior

With most of testcases that code (and other code with unordered_map)  works good, except this tastcases. 
[ 1,2,3,4,5,6,7 ], target 9, solution [1,6], but solutions with unordered map(u_m) return [3,4] 
[1,2,3,4,5] target 5, solution [0,3], but u_m solutions [1,2]
[3,2,7,6,5,3,2,7,12,15,1],target 14, solution [1,8], but u_m solutions [2,7].

**Comment by stormsunshine** [comment]
This problem requires that each input would have exactly one answer. Why are you providing test cases that have several answers?

**Comment by JJ-small** [comment]
> This problem requires that each input would have exactly one answer. Why are you providing test cases that have several answers?

![image](https://user-images.githubusercontent.com/111843589/186442036-09a66e92-4c66-4b30-88d0-43630003a76e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by JJ-small** [comment]
> The code submission accepted link.
https://leetcode.com/submissions/detail/773606052/ 

If I understand correctly.

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. After investigated,  the test cases as above are all invalid test case.This problem requires that each input would have exactly one answer.
