### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by seulusoy** [LeetCode-Feedback/LeetCode-Feedback#8782]
#### Your LeetCode username
eulusoy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The big test cases involves same element again and again so when map is used it seems to be more efficient than brute-force but in reality complexity of map and brute-force are close to each other.

#### Code you used for Submit/Run operation

```
Solution 1:
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
      int len = nums.size();
      for(int i = 0; i < len; i++) {
          for(int j = i + 1; j < len; j++) {
              if(nums[j] == target - nums[i])
                  return { i, j };
          }
      }
      return {-1, -1};
    }
};
Solution 2:
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
      map<int, int> map;
      vector<int> pairs;
      for(int i = 0; i < nums.size(); i++) {
          int complement = target - nums[i];
          if(map.find(complement) != map.end()) {
              pairs.push_back(map.find(complement)->second);
              pairs.push_back(i);
              break;
          }
          map.insert(pair<int, int>(nums[i], i));
      }
      return pairs;
    }
};
```

#### Expected behavior
I normally expect two codes have similar performance but due to the used test cases second code performs much more better.

#### Additional context
There is no bug but test cases result in favor of one of the algorithms.

**Comment by stormsunshine** [comment]
The two solutions have different time complexities, and the run times should be different. Why do you think the solutions with different time complexities should have similar run times?

**Comment by seulusoy** [comment]
If the elements in the vector are distinct, can we still say these solutions have different time complexities?
Because when elements are distinct size of map will increase with every each element.

**Comment by stormsunshine** [comment]
For solution 1, the time complexity is O(n<sup>2</sup>).

For solution 2, the map has O(log n) time complexity for each operation, so the time complexity is O(n log n). If using unordered_map instead of map, then the time complexity is O(n).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. Please consider Stromsunshine's comment as reference. 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by seulusoy** [comment]
> For solution 1, the time complexity is O(n2).
> 
> For solution 2, the map has O(log n) time complexity for each operation, so the time complexity is O(n log n). If using unordered_map instead of map, then the time complexity is O(n).

Thank you. I saw which subject I have to study.

**Comment by seulusoy** [comment]
I am sorry for reopening the issue. But could you check the submission below?
https://leetcode.com/submissions/detail/794518104/
This is what I meant by missing test cases.
