### ISSUE TITLE
Issue with code provided as solution for problem 383 in Beginner guide.

### ISSUE THREAD

**Issue by lovishpahwa** [LeetCode-Feedback/LeetCode-Feedback#8783]
#### Your LeetCode username
lovishpahwa

#### Category of the bug
- [x] Solution

#### Description of the bug

While going through the BeginerGuide problem [383. Ransom Note](https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/692/challenge-problems/4427/) in the solution video there is an issue with code.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean canConstruct(String ransomNote, String magazine) {
        for(int i=0; i<ransomNote.length(); i++){
            char r = ransomNote.charAt(i);
            int magazineIndex = magazine.indexOf(r);
            if(magazineIndex == -1){
                return false;
            }
            magazine = magazine.substring(0,magazineIndex) + magazine.substring(magazineIndex+1);
        }
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

In solution video wrong index is used for passing in substring function and I have already described above that how it should be according to me. 
Actually we should use `magazineIndex` while substring magazine String instead of index of ransomNote String.
Please refer to screenshot to better understand the area I am talking about.

#### Screenshots

![ERROR](https://user-images.githubusercontent.com/45431201/186475164-f53591de-0dcf-41e9-8e5f-8cf6471c7f19.jpg)

#### Additional context
I already tested the video solution and it fails when length of Ransom String is equal or more than magazine String.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
