### ISSUE TITLE
569. Median Employee Salary TEST CASE 

### ISSUE THREAD

**Issue by Budong-jiuwen** [LeetCode-Feedback/LeetCode-Feedback#8784]
#### Your LeetCode username

BuDongJiuWen

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The current cases recognize the median number by salary AND id.  And the median number should not be like this.  The description give people impression that only company and its median salary are needed in the output. Most of time, they are the same; however, if there are other people having the same salary as the median salary but their ids are not located in the middle, then they would not be in the results while they should.  This is wrong when the median salary is asked.

#### Code you used for Submit/Run operation

```
WITH cte AS (
    SELECT  id,
            company,
            salary,
            ROW_NUMBER() OVER (PARTITION BY company ORDER BY salary) AS salary_rank,
            COUNT(id) OVER (PARTITION BY company) AS count_id
    FROM Employee
)

SELECT  DISTINCT
        id,
        company,
        salary    
FROM cte
WHERE salary_rank BETWEEN count_id/2 AND count_id/2 + 1
```

#### Language used for code

MySQL

#### Expected behavior

The clearer question description should be changed to either of the following:
1. Write an SQL query to find the median salary of each company.  The expected result table should contain company and salary only.  2. Write an SQL query to find the median salary of each company and people who make such salary in this company.  The current test case and solution cannot give pass on the following solution.
```
{"headers": {"Employee": ["id", "company", "salary"]}, "rows": {"Employee": [[1, "A", 2341],[2, "A", 451],[3, "A", 451],[4, "A", 451],[5, "A", 451],[6, "A", 451],[7, "B", 15],[8, "B", 13],[9, "B", 1154],[10, "B", 1345],[11, "B", 1221],[12, "B", 234],[13, "C", 2345],[14, "C", 2645],[15, "C", 2645],[16, "C", 2652],[17, "C", 65]]}}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
