### ISSUE TITLE
Missing Test Case - 206. Reverse Linked List

### ISSUE THREAD

**Issue by NamanJain2209** [LeetCode-Feedback/LeetCode-Feedback#8785]
#### Your LeetCode username
 thenaman 

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    ListNode* temp;
    void rev(ListNode* head){
        if(head==NULL)
            return;
        rev(head->next);
        if(head>=temp) // this should not work
        {
            int x=head->val;
            head->val=temp->val;
            temp->val=x;
            temp=temp->next;
        }
    }
    ListNode* reverseList(ListNode* head) {
        temp=head;
        rev(head);
        return head;
    }
};
```

#### Expected behavior
 Not work since LL does not allocate space contagiously.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by NamanJain2209** [comment]
I used CPP

**Comment by LC-Pam** [comment]
Thank you for your time. The received Accepted when we test it, please check: 
https://leetcode.com/submissions/detail/784345484/
We appreciate your support!
