### ISSUE TITLE
Missing  Test Case - 1106. Parsing A Boolean Expression

### ISSUE THREAD

**Issue by bssrdf** [LeetCode-Feedback/LeetCode-Feedback#8786]
#### Your LeetCode username

bssrdf

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I believe some test cases are missing which allow some wrong solutions to pass AC.

#### Code you used for Submit/Run operation

```
       def helper(s):
            if s[0] == 't': return True
            if s[0] == 'f': return False 
            if s[0] == '!':
                return not helper(s[2:-1])
            sub = s[2:-1]

            i, cnt, subexps = 0, 0, []         
            n = len(sub)   
            if '(' in sub:
                while i < n:                
                    if sub[i] == '(':
                        j, cnt = i, 0
                        while i < n:
                            if sub[i] == '(': cnt += 1
                            if sub[i] == ')': cnt -= 1                 
                            if cnt == 0: break
                            i += 1
                        subexps.append(sub[j-1:i+1])                    
                    i += 1
            else:                 
                subexps = sub.split(',')
            return reduce(and_, (helper(se) for se in subexps)) if s[0] == '&' else reduce(or_, (helper(se) for se in subexps))
        return helper(expression)    
```

#### Language used for code
Python3 

#### Expected behavior

The above solution got accepted [link](https://leetcode.com/submissions/detail/782405786/)
However, for test case: expression = "|(&(t,f,t),t)", the above solution outputs False while correct answer is True

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
