### ISSUE TITLE
470: Major check on output is missing

### ISSUE THREAD

**Issue by singh96** [LeetCode-Feedback/LeetCode-Feedback#879]
#### Your LeetCode username
sumitsingh96

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Question: 470. Implement Rand10() Using Rand7()
Leetcode only checks the randomization factor of the output returned by the code submitted.
If I sequentially distribute the number between 1 to 10, the solution gets accepted as its evenly distributed between 1 to 10.

#### Code you used for Submit/Run operation

```
class Solution extends SolBase {

    int count = 1;
    
    public int rand10() {
        return (count++)%10 + 1;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
I expected that if I distribute number from 1 to 10 using some Arithmetic Progression, then the solution should not be accepted.
This method is against the question asked to get a numbers between 1 to 10 randomly N times.

A check on the user output to verify that it's not sequential or an Arithmetic progression of some length L will be great. 

#### Screenshots
![image](https://user-images.githubusercontent.com/24877093/91631004-b74fb380-e9f3-11ea-8e61-9351851e3eaa.png)

**Comment by lc-pam** [comment]
Hi @singh96 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @singh96 
Thank you for your time. The team has reviewed your report but decided not to make updates to the problem. This a practice problem and you can use any solution to accept it, but in the real-life interview, you'll need to know how to solve it using the given API. We appreciate your support!
