### ISSUE TITLE
Missing Test Case - 215. Kth Largest Element in an Array

### ISSUE THREAD

**Issue by Janakinathverma** [LeetCode-Feedback/LeetCode-Feedback#8793]
Your LeetCode username
Janakinath_verma

#### Category of the bug
- [ ] Question=215. Kth Largest Element in an Array
- [ ] Solution=
-class Solution:
    def findKthLargest(self, nums: List[int], k: int) -> int:
        nums.sort()
        return nums[len(nums)-k]
        
- [ ] Language=Python
- [ ] Missing Test Cases =[2,2,3,1]

#### Code you used for Submit/Run operation

Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 

class Solution:
    def findKthLargest(self, nums: List[int], k: int) -> int:
        nums.sort()
        return nums[len(nums)-k]
        

Language used for code
Python

Expected behavior
Showing wrong answer. Expected answer must be 1 which is correct. But it is not showing wrong for [2,2,3,1] test case.

Screenshots
<img width="557" alt="image" src="https://user-images.githubusercontent.com/76773065/186724344-b2445b82-e437-446b-a6d6-61940b840ef4.png">

#### Additional context
Question must consider repetition of elements.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

Best,
