### ISSUE TITLE
Missing Test Case - 125. Valid Palindrome

### ISSUE THREAD

**Issue by dilipkumar08** [LeetCode-Feedback/LeetCode-Feedback#8795]
#### Category of the bug

- [ ] Solution

#### Description of the bug
one of test case is wrong

#### Code you used for Submit/Run operation

```
// Valid Palindrome
class Solution:
    def isPalindrome(self, s: str) -> bool:
        import re
        a=re.sub(r'[^a-zA-Z\d\']', '', s).lower()
        if a==a[::-1]:
            return "true"
        else:
            return "false"
```

#### Screenshots
![image](https://user-images.githubusercontent.com/77008477/186744284-15e699b2-ea05-4983-8a2d-1298e56f9396.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
