### ISSUE TITLE
Missing Test Case - 1290. Convert Binary Number in a Linked List to Integer

### ISSUE THREAD

**Issue by m-abdullahjaved** [LeetCode-Feedback/LeetCode-Feedback#8796]
#### Your LeetCode username
abdullahmirza

#### Category of the bug
Testcase Bug

#### Description of the bug
 Different output in test case section and submit code section.

```
class Solution {
public:
    int getDecimalValue(ListNode* head) {
        static int i = 0;
        int sum = 0;
        if (head->next != NULL){
            sum += getDecimalValue(head->next);
        }
        return sum + (head->val * pow(2, i++));
    }
};
```

#### Language used for code

C++

#### Expected behavior
When I test my code using the test case section in the console then it works fine but when I submit the code then on the same code it gives different output.

#### Screenshots
![prob](https://user-images.githubusercontent.com/80704187/186744964-5d434195-bbf0-4ef1-9ed2-347bff796ab2.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by m-abdullahjaved** [comment]
Thanks, the Issue is Resolved!
