### ISSUE TITLE
SQL ariticle issue

### ISSUE THREAD

**Issue by JackHe313** [LeetCode-Feedback/LeetCode-Feedback#8798]
#### Your LeetCode username

jackhe313

#### Category of the bug
SQL ariticle issue

#### Description of the bug

one of the code exmaple actually is wrong. 
In the sql chapter: SQL syntax: Aggregate Functions
this is the exmaple code you provided:
SELECT CONCAT(`id`, '-', `name`), `age` AS `identification` FROM `new_schema`.`users`;
<img width="904" alt="Screen Shot 2022-08-25 at 4 14 50 PM" src="https://user-images.githubusercontent.com/94516810/186784971-dc32a822-cc94-4a23-a810-35d1fe1c85b5.png">
but actaully that doesn't have this output.
This is the output:
<img width="1684" alt="Screen Shot 2022-08-25 at 4 17 12 PM" src="https://user-images.githubusercontent.com/94516810/186784945-ad24d2b0-95c2-424c-901f-e67ae6538eca.png">
It should be
SELECT CONCAT(`id`, '-', `name`) AS `identification`, `age`  FROM `new_schema`.`users`;

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
