### ISSUE TITLE
578. Get Highest Answer Rate Question。问题描述不清楚

### ISSUE THREAD

**Issue by LeoSirius** [LeetCode-Feedback/LeetCode-Feedback#88]
** Bug 类型**
- [ 1] 题目

**描述**
描述你遇到的 bug

https://leetcode-cn.com/problems/get-highest-answer-rate-question/

这道题的描述，连answer rate是什么都没说清楚，就让求answer rate。

**Comment by feiceh** [comment]
下面的提示里面有关于回答率最高的定义，从描述中可以看出什么是回答率。
