### ISSUE TITLE
969. Pancake Sorting : inconsistency of the 'k' values in problem and example

### ISSUE THREAD

**Issue by kichankwon** [LeetCode-Feedback/LeetCode-Feedback#880]
#### Your LeetCode username
fabulousK

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The 'k' values are same in problem and example, but action is different
- Problem : [3,2,1,4], k=2 -> [1,2,3,4] : reverse A[0...2]
- Example 1 : [1,4,2,3], k=2 -> [4,1,2,3] : reverse A[0...1]

**Comment by lc-pam** [comment]
Hi @kichankwon , Thank you for reaching out to us! The team has updated the problem statement.
