### ISSUE TITLE
This line is incorret -> prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai.

### ISSUE THREAD

**Issue by princeramkot** [LeetCode-Feedback/LeetCode-Feedback#8801]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
