### ISSUE TITLE
Missing Test Case - 326. Power of Three

### ISSUE THREAD

**Issue by wercabaj** [LeetCode-Feedback/LeetCode-Feedback#8804]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The code is not accepted by Python, but it is accepted by Python3.

#### Code you used for Submit/Run operation

```
class Solution:
    def isPowerOfThree(self, n: int) -> bool:
        
        while n >= 1:
            if n == 1:
                return True
            n /= 3
        return False
```

#### Language used for code
Python3

#### Expected behavior
Code should not be accepted in Python3.

#### Screenshots
![image](https://user-images.githubusercontent.com/78911847/186917102-8a8daa96-d747-4192-8324-7238be485566.png)

#### Additional context
Example of missing input in test cases: input = 10

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The code is correct and rightfully accepted.
def isPowerOfThree(self, n: int) -> bool:
is a valid way to write function definition in py3.

In case the you still confused, please ask let us know why you thinks this should not be accepted.
We appreciate your support!
