### ISSUE TITLE
Missing Test Case - 869. Reordered Power of 2

### ISSUE THREAD

**Issue by saketkumar1** [LeetCode-Feedback/LeetCode-Feedback#8805]
#### Your LeetCode username
saketkumar8385

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case my code should not work on 1000000000

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean reorderedPowerOf2(int n) {
        
        
        int count=0;
        List<Integer> list=new ArrayList<>();
        int m=n;
        while(m!=0){
            list.add(m%10);
            m=m/10;
            count++;
        }
        
        Collections.sort(list);
        
        int i=0;
        int curr=1;
        while(i<=count){
            
        int c=0;
        List<Integer> ll=new ArrayList<>();
        m=curr;
        while(m!=0){
            ll.add(m%10);
            m=m/10;
            c++;
        }
            
            i=c;
        
           
            if(c==count){
                Collections.sort(ll);
                int j=0;
                for( j=0;j<count;j++){
                    if(ll.get(j)!=list.get(j))break;
                }
                
                if(j==count)return true;
                
            }
            
            
            curr=curr*2;
        
            
            
        }
        
        return false;
        
    }
    
  
}
```

#### Language used for code
JAVA

#### Expected behavior
WRONG ANSWER

#### Screenshots

![image](https://user-images.githubusercontent.com/66872047/186940747-3c969744-3c26-4d1c-afcf-05654c50164b.png)
![image](https://user-images.githubusercontent.com/66872047/186940993-4a57ee4b-3f3f-4fa5-b6a8-a67f60bde69e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
