### ISSUE TITLE
662. 二叉树最大宽度

### ISSUE THREAD

**Issue by JBossBC** [LeetCode-Feedback/LeetCode-Feedback#8806]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
四方

**Bug 类型**
-  [662. 二叉树最大宽度](https://leetcode.cn/problems/maximum-width-of-binary-tree/)
-  编程语言  go

**描述**
提交之后运行的代码产生的结果和实际不符。
对于[1,3,2,5]这个用例,我点击执行代码测试的结果和点击执行的执行结果不一致

**你使用的语言**
go

**你提交或者运行的代码**

```
type LengthLocation struct {
	Left  int
	Right int
}

var resultMap map[int]*LengthLocation = make(map[int]*LengthLocation, 3000)

func widthOfBinaryTree(root *TreeNode) int {
	recursion(root, 1, 1)
	var max = 0
	for _, value := range resultMap {
		var temp = value.Right - value.Left + 1
		if temp > max {
			max = temp
		}
	}
	return max
}
func recursion(root *TreeNode, rootNode int, length int) {
	if root == nil {
		return
	}
	value, ok := resultMap[length]
	if !ok {
		//这里能保证为分配的是比较晓得,通过遍历顺序可以明确
		resultMap[length] = &LengthLocation{
			Left: rootNode,
		}
	} else {
		if rootNode > value.Right {
			value.Right = rootNode
		}
		if rootNode < value.Left {
			value.Left = rootNode
		}
	}
	recursion(root.Left, 2*rootNode, length+1)
	recursion(root.Right, 2*rootNode+1, length+1)
}
```

**期望行为**
同一份代码，左边的执行结果和右边的完全不同
![image](https://user-images.githubusercontent.com/90125263/186952950-0a283cfc-2d26-48f4-ac5c-245be8bba866.png)
**屏幕截图**
![image](https://user-images.githubusercontent.com/90125263/186952965-cb80ddad-9649-4c4c-843e-ee8dca83ceb9.png)

**额外的上下文**
之前的相关题目之中也有类似的问题，我找不到原因。

**Comment by BrambleWave** [comment]
因为将 resultMap 作为全局变量，所以每次执行测试用例时不会进行初始化。
把 resultMap 的初始化声明语句放到函数内部就行了
