### ISSUE TITLE
190. Reverse Bits - inconsistent description

### ISSUE THREAD

**Issue by CRowland4** [LeetCode-Feedback/LeetCode-Feedback#8808]
#### Your LeetCode username
Crowland4

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Something feels off with the description - the type hinting says the input is an integer, but Python does not support leading zeros on integers, so we can't be getting a 32 digit integer. The constraint says it's a binary string, but that also can't be the case, because when you try to slice n, it returns an error that int types can't be sliced. But, again, when you actually view the initial test case, it says the input is 00000010100101000001111010011100, which again Python doesn't allow, so this can't be the case. The description is unclear as to what we're working with as an input.

#### Code you used for Submit/Run operation
I tried to determine what the input type is.
-- `n[::-1]` doesn't work, because "int object is not subscriptable"
-- So the input cannot be what is given in the testcase

#### Language used for code
Python

#### Expected behavior
I expected to either be getting an integer without leading zeroes, or a string as input.

**Comment by aadityatiwari** [comment]
+1

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The input is the binary representation of a 32-bit integer. When it is passed to the function, it is converted to 32-bit integer.
The input is not a string.
The input in the test cases cannot be an integer because some languages support 32-bit unsigned integers while the others do not.
We appreciate your support!
