### ISSUE TITLE
969. Pancake Sorting: mistake in description of allowable values of k

### ISSUE THREAD

**Issue by ZufengW** [LeetCode-Feedback/LeetCode-Feedback#881]
#### Your LeetCode username
zufeng

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The description in problem [969. Pancake Sorting](https://leetcode.com/problems/pancake-sorting/) says "Choose an integer `k` where `0 <= k < A.length`."

But the later examples show that you can pick `k = A.length`. The submitted code is also tested as if `0 < k <= A.length`.

The example in the next paragraph is also wrong because it shows `k = 2` flipping the first three elements. (The example after that shows `k = 2` flipping the first two elements.)

#### Expected behavior
The problem description should match the the way submissions are actually tested. It should say that `0 < k <= A.length` and each pancake flip flips the first `k` elements.

#### Screenshot of problem
![Screen Shot 2020-08-29 at 6 23 45 PM](https://user-images.githubusercontent.com/15045948/91632580-0f52de00-ea25-11ea-9534-1b88e27647f6.png)

**Comment by lc-pam** [comment]
Hi @ZufengW , Thank you for reaching out to us! The team has acknowledged the issue and updated the problem statement.
