### ISSUE TITLE
437. Path Sum III - wrong answer in test case / solution

### ISSUE THREAD

**Issue by mpekalski** [LeetCode-Feedback/LeetCode-Feedback#8812]
#### Your LeetCode username
mpekalski

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
One of the test cases is a binary tree [0,1,1] target_sum = 1
question is about number of downward paths that sum up to one, and a test case answer is 4, but in tree like
```
   0
 /   \
1    1
```
there is not place for 4 paths that go downward and sum to 1.
path = has to travel from parent to a child, so you cannot take node itself as a path without a child. 
Only paths {0-1, 0-1, 1, 1} could give number of paths summing up to 1 to be 4, but that's not the case.

That leads to the solution provided being wrong.

The solution includes this two additions
```
if curr_sum == k:
    count += 1
count += h[curr_sum - k]
```
which for this particular tree count the same prefix sum twice.

**Comment by mpekalski** [comment]
Interestingly for case
```
[1,0,0]
1
```
the answer provided by the system/solution is `3`. 

and if we change target to 0
```
[1,0,0]
0
```
the answer is 2.

**Comment by mpekalski** [comment]
```
The path does not need to start or end at the root or a leaf, but it must go downwards (i.e., traveling only from parent nodes to child nodes).
```

**Comment by LC-Pam** [comment]
Thank you for your time. The expected answers are correct.
Please use the discussion section to get help if you want to know why the expected answer is like this. 
We appreciate your support!
