### ISSUE TITLE
Missing Test Case - 1020. Number of Enclaves

### ISSUE THREAD

**Issue by Bhupesh2001** [LeetCode-Feedback/LeetCode-Feedback#8815]
#### Your LeetCode username
bpattaniak  [https://leetcode.com/bpattaniak/](url)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing Test Cases
The testcase is given in the TXT file below
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9437360/testcase.txt)

#### Code you used for Submit/Run operation
Number of Enclaves

```
Number of Enclaves
class Solution {
public:
        int helper(vector<vector<int>>& grid,int i,int j){
        if(i>=grid.size() || j>=grid[0].size() || i<0 || j<0 ||grid[i][j]==0)
            return 0;
        if(i==0 || j==0 || i==grid.size()-1 || j==grid[0].size()-1)
            return -240;
        
        grid[i][j]=0;
        int a = 1+helper(grid,i,j+1)+helper(grid,i+1,j)
                 +helper(grid,i,j-1)+helper(grid,i-1,j);
        return a;
    }
    int numEnclaves(vector<vector<int>>& grid) {
        int ans=0;
        for(int i=0;i<grid.size();i++)
            for(int j=0;j<grid[0].size();j++)
                if(grid[i][j])
                    ans+=max(helper(grid,i,j),0);
                

        return ans;
    }
};
```

#### Language used for code
 C++

#### Expected behavior
The given code was accepted when submitted, but is not a optimal solution and should give WRONG ANSWER but it didn't. As there is a missing test case in this question. As there is test cases missing as per the given constraints

#### Screenshots
![image](https://user-images.githubusercontent.com/53337976/187016174-670633ca-4e8d-4ac3-b885-9357e54c23a2.png)
The code was accepted but giving wrong answer on a custom testcase within the given constraints in the question

#### Additional context
Add this test case to accept only optimized code, else non optimized code are also being accepted
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9437371/testcase.txt)

**Comment by Bhupesh2001** [comment]
Missing TestCase

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
