### ISSUE TITLE
662. 二叉树最大宽度 - 删除“错误”测试样例的请求

### ISSUE THREAD

**Issue by LetMeFly666** [LeetCode-Feedback/LeetCode-Feedback#8816]
**Tisfy**
填写你登录 LeetCode（中国区）的用户名：[Tisfy](https://leetcode.cn/u/tisfy/)

**Bug 类型**
- [ ] 测试样例错误 或 官方题解错误

**描述**
在题面[662. 二叉树最大宽度](https://leetcode.cn/problems/maximum-width-of-binary-tree/)中，官方题解在解答最后一组测试样例的时候，发生了**溢出**。

我在做这道题面时，无论如何都有一组测试样例无法通过。官方题解的答案是“4”，而我的答案是“1”

经过debug得知，我的答案是“1”的原因是我的代码在运算过程中```unsigned long long```发生了溢出。

但是我找不到溢出的原因。因此，我在官方题解的C++代码中添加了一句```assert(index * 2 > index);```

结果系统返回了“Assertion `index * 2 > index' failed”

也就是说，官方题解在这组数据下也发生了数据溢出错误。

同时，我把“unsigned long long”修改为“__int128”同样会发生溢出错误。

如果要通过这组测试样例，似乎要手写高精度。

因此，我请求删除这组测试样例。

提交记录：[https://leetcode.cn/submissions/detail/355525811/](https://leetcode.cn/submissions/detail/355525811/)

**你使用的语言**
C++

**你提交或者运行的代码**
```
// 官解 + assert
class Solution {
public:
    int widthOfBinaryTree(TreeNode* root) {
        unsigned long long res = 1;
        vector<pair<TreeNode *, unsigned long long>> arr;
        arr.emplace_back(root, 1L);
        while (!arr.empty()) {
            vector<pair<TreeNode *, unsigned long long>> tmp;
            for (auto &[node, index] : arr) {
                if (node->left) {
                    tmp.emplace_back(node->left, index * 2 - 1);
                }
                if (node->right) {
                    tmp.emplace_back(node->right, index * 2);
                }
                assert(index * 2 > index);  // 我只在官方题解中添加了这一行。  //***********************************************
            }
            res = max(res, arr.back().second - arr[0].second + 1);
            arr = move(tmp);
        }
        return res;
    }
};
```

**期望行为**
删除改组导致数据溢出的这一组测试样例

**屏幕截图**
![Assertion `index * 2 > index' failed](https://user-images.githubusercontent.com/56995506/187018631-a7cb88c3-76fa-4b75-ab8e-b1594d349be9.jpg)

**Comment by feiceh** [comment]
您好，在与相关团队核实后：用例符合提示范围，暂不处理。本次 Ticket 将关闭，感谢您的反馈和支持。
