### ISSUE TITLE
Missing Test Case - 2092. Find All People With Secret

### ISSUE THREAD

**Issue by zhenliang153** [LeetCode-Feedback/LeetCode-Feedback#8817]
#### Your LeetCode username
zhenliang153

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/find-all-people-with-secret/
Time complexity of  `std::unordered_map::clear()` and `std::unordered_set::clear()` may be related to **the buckets counts of hash table**, so they should not exec `std::unordered_map::clear()` or `std::unordered_set::clear()` in the circulation, because doing so may make the overall time complexity reach _O(n²)_ .
We can generate a test case through the following Python code:
```python3
N = 10**5 >> 1
firstPerson = 1

arr = []
for i in range(2, N):
    arr.append([0, i, 1])
    arr.append([i, i - 1, i])

print(N)
print(str(arr).replace(' ', ''))
print(firstPerson)
```

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    vector<int> findAllPeople(int n, vector<vector<int>>& meetings, int firstPerson) {
        map<int, vector<int>> indexs;
        for (int i = 0; i < meetings.size(); ++i) {
            indexs[meetings[i][2]].push_back(i);
        }
        set<int> s {0, firstPerson};
        unordered_set<int> state;
        // set<int> state;
        unordered_map<int, vector<int>> um;
        // map<int, vector<int>> um;
        function<void(int)> dfs = [&](int idx) {
            if (state.count(idx) == 0) {
                state.insert(idx);
                s.insert(idx);
                for (int i : um[idx]) {
                    dfs(i);
                }
            }
        };
        for (const auto &[x, y] : indexs) {
            um.clear();
            state.clear();
            for (int i : y) {
                int x = meetings[i][0], y = meetings[i][1], z = meetings[i][2];
                um[x].push_back(y);
                um[y].push_back(x);
            }
            for (int i : y) {
                int x = meetings[i][0], y = meetings[i][1], z = meetings[i][2];
                if (s.count(x) != 0) {
                    dfs(x);
                }
                if (s.count(y) != 0) {
                    dfs(y);
                }
            }
        }
        return vector<int>(s.begin(), s.end());
    }
};
```

#### Language used for code
C++

#### Expected behavior

Output: TLE
Expected: Right Answer

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
