### ISSUE TITLE
744. Find Smallest Letter Greater Than Target | Solution #3 issue 

### ISSUE THREAD

**Issue by GeorgeSexton99** [LeetCode-Feedback/LeetCode-Feedback#8818]
#### Your LeetCode username
GeorgeSexton99

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Your python solution makes use of bisect.bisect(), which is difficult for beginners to understand. It would be more beneficial to see an actual implementation of binary search, much like the solution I have listed below.

#### Code you used for Submit/Run operation

```
class Solution:
    def nextGreatestLetter(self, letters: List[str], target: str) -> str:
        low,high = 0,len(letters)-1
        while low <= high:
            mid = (low + high) // 2
            if letters[mid] > target:
                high = mid-1
            elif letters[mid] <= target:
                low = mid+1
            
        return letters[low] if low <= len(letters)-1 else letters[0] 
```

#### Language used for code
Python3

#### Expected behavior
Same solution, just with the binary search written explicitly for ease of understanding as opposed to making use of a library

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
