### ISSUE TITLE
剑指 Offer 45. 把数组排成最小的数

### ISSUE THREAD

**Issue by qiudaoermu** [LeetCode-Feedback/LeetCode-Feedback#8819]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
幽州胖都督

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言 
- [x] 缺少测试用例

**描述**
测试用例都是0时，返回多个“0”

**你使用的语言**
javascript

**你提交或者运行的代码**
```
/**
 * @param {number[]} nums
 * @return {string}
 */
var minNumber = function(nums) {
  
  if (nums.every(item => item === 0)) {
    return "0";
  };

  for (let i = 0; i < nums.length; i++) {
    for (let j = 0; j < nums.length; j++) {
      let pre = (nums[j] + '') + (nums[j + 1] + '');
      let pro = (nums[j + 1] + '') + (nums[j] + '');
      if (+pro < +pre) {
        [nums[j],nums[j + 1]] = [nums[j + 1], nums[j]];
      };
    };
  };

  return nums.reduce((pre,cur) => pre + cur, '');
};



```

**期望行为**
应该返回1个0
**屏幕截图**
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/13454418/187029984-ac6d46b2-2062-4c44-9410-a4a53a95c616.png">

**Comment by BrambleWave** [comment]
![origin_img_v2_40d655ca-e667-4c03-90b6-55a85c77772g](https://user-images.githubusercontent.com/99636790/187590529-f500b77d-3176-4ca1-93be-2cadc2689bc9.jpg)

**Comment by BrambleWave** [comment]
![origin_img_v2_40d655ca-e667-4c03-90b6-55a85c77772g](https://user-images.githubusercontent.com/99636790/187590576-e001c5e0-814b-4407-8ef2-5194d173cb19.jpg)
