### ISSUE TITLE
Weekly Contest 308 - Incorrect registered score in contest rankings

### ISSUE THREAD

**Issue by gvhfds** [LeetCode-Feedback/LeetCode-Feedback#8826]
#### Your LeetCode username

bogo7846

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solved all 4 questions in Weekly Contest 308. 
It registered a score of 13 instead of 17
![image](https://user-images.githubusercontent.com/53549120/187057223-66abdd3d-a0c6-48a7-8252-8f7439819327.png)

#### Expected behavior

Score should be 17 instead of 13. Rank should be about 200+ instead of 3357.
![image](https://user-images.githubusercontent.com/53549120/187057260-327f2820-2711-40e7-a125-4ec6a1a518dc.png)

#### Screenshots

Clearly all 4 questions were solved and score should be 3+4+4+6 = 17 not 13
https://vimeo.com/manage/videos/743826582/36d7ca5615 full contest recording of Weekly Contest 308 is here

#### Additional context

Please update my score and ranking accordingly before the ratings are updated. Thanks

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. The final rating of this contest will be updated within 5 working days after the contest, so we can thoroughly vet the contest violators out from the participants and check technical issues that occurred during the contest.

We appreciate your time and support! If you have any other questions, please don't hesitate to let us know.
