### ISSUE TITLE
189. Rotate Array description and code not match in C#

### ISSUE THREAD

**Issue by ZJKung** [LeetCode-Feedback/LeetCode-Feedback#8828]
#### Your LeetCode username

zjkung1123

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The desc is `Rotate Array`, but code in C# is `FindMin`

#### Code you used for Submit/Run operation

```csharp
public class Solution {
    public int FindMin(int[] nums) {
        var arr = new int[nums.Length]{};
        
    }
}
```

#### Language used for code

C#

#### Expected behavior

```csharp
public class Solution {
    public void Rotate(int[] nums, int k) {        
    }
}
```

#### Screenshots

![image](https://user-images.githubusercontent.com/34116485/187059742-0f7d90d9-6e87-4b71-9cef-aa3d44830fbf.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Please to refresh the default code. It is Rotate. We appreciate your support!
