### ISSUE TITLE
Missing Test Case - 1295. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by lavinov-mercury** [LeetCode-Feedback/LeetCode-Feedback#8829]
#### Your LeetCode username
lavinov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code from the section below passes all tests, however, there is a test which won't be passed by this code: [9999]. Please, add it to the test suit

#### Code you used for Submit/Run operation

```Dart
class Solution {
  bool testEventDigits(int number) {
    final digits = log(number + 1) ~/ ln10 + 1;
    return digits.isEven;
  }
    
  int findNumbers(List<int> nums) => nums.where(testEventDigits).length;
}
```

#### Language used for code

Dart

#### Expected behavior

This solution should not be accepted

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
