### ISSUE TITLE
[Java] Is this is the right interface for Contains Duplicates II 

### ISSUE THREAD

**Issue by MMajd** [LeetCode-Feedback/LeetCode-Feedback#8832]
#### Your LeetCode username
mmajd

#### Category of the bug
- [X] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

I think this is the wrong interface for ***[Contains Dupcliates II](https://leetcode.com/problems/contains-duplicate-ii/)***, despite the interface is right in other languages, It's ***[Bitwise And of Range Numbers](https://leetcode.com/problems/bitwise-and-of-numbers-range/)*** when Java is selected
```
// Java contains duplicates II 
class Solution {
    public int rangeBitwiseAnd(int left, int right) {
        
    }
}
```

#### Language used for code
Java

#### Expected behavior
```
class Solution {
    public boolean containsNearbyDuplicate(int[] arr, int k) {
    }
}
```

#### Screenshots
![image](https://user-images.githubusercontent.com/11295576/187067608-dfe1071e-ded4-41c7-9131-23aa13ac38ee.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.The interface is correct,  please to reset it to the default. We appreciate your support!
