### ISSUE TITLE
Solution for 1-bit and 2-bit Characters

### ISSUE THREAD

**Issue by MMajd** [LeetCode-Feedback/LeetCode-Feedback#8833]
#### Your LeetCode username
mmajd

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Recursive solution for the 1-bit and 2-bit Characters 

#### Code you used for Submit/Run operation

```java
class Solution {
    public boolean isOneBitCharacter(int[] bits) {
        return solve(0, bits, 0);
    }
    
    private boolean solve(int idx, int[] bits, int prev) { 
        if (idx == bits.length) return prev == 0; 
        
        return prev>=2 
            ? solve(idx+1, bits, bits[idx])
            : solve(idx+1, bits, (prev<<1) | bits[idx]);
    }
}
```

#### Language used for code
Java

#### Expected behavior
Solves the 1-bit and 2-bit characters

#### Screenshots

![image](https://user-images.githubusercontent.com/11295576/187068924-5bd96f3a-a8aa-4ec4-9e9a-ed4e99d88880.png)

#### Additional context

**Explanation**

NOTE: Will give running examples after this quick explanation

- First part in the recursive function is the base case in which I'm checking if the previous value is 0 or not if its zero then we have 1-bit 2-bit character, this no thing more than checking that I'm at the end of the bits array and my last previous values is 0

- The real solution in recursive return condition, and note that we are looking for our previous to be 0 as they state in the problem that the last bit is always zero, so if we have the right combination of bits before it we must end with our prev variable equal to 0
```java
        return prev>= 2 
			? solve(idx+1, bits, bits[idx])
			 : solve(idx+1, bits, (prev<<1) | bits[idx]);
```
I'm starting the solution by setting up the previous to zero because the input array could have only one element in it and by design that element must be zero, so to return true I'm starting my solution with previous equal to 0

- Coming to the recursive part, I'm looking if my previous is 2 or more (exactly 3) if my previous is 2 or 3 my answer is depending on the current index not the previous indices as they had produced 2-bit character {2,3} so I'm not interested in them, I'm Interested in the current index and what could it produce either by itself or with the indices that come after

- If my previous is less than 2, meaning previous is either {0, or 1}, then we need to do bit level left shift and ORing  ```<< , |``` with the current index to see if it could produce 2-bit character, in calls to come or not, if not then our previous is either 1 or more, or 0 if its one or more then last character isn't one-bit character

Example: 1
Given [1,0,0] return true if the last character must be a one-bit character.

Starting our solution with index: 0 and previous=0
1st call: we have a previous < 2, thus we or the current index with the previous value, prev = (0<<1) | 0 = 01, index = 1
2nd call: we have previous <2, thus we or the current index with the previous value, prev 1<<1 | 0 = 10, index = 2
3rd call: we have previous >= 2, thus we drop the previous and propagate the current index instead of previous value, prev= 0, and index=3
4th call: we enter the base case and check if prev==0, which is true

Example: 2
Given [1,1,1,0] return true if the last character must be a one-bit character.
1st call: we have a previous < 2, thus we or the current index with the previous value, prev = (0<<1) | 0 = 01, index = 1
2nd call: we have previous <2, thus we or the current index with the previous value, prev 1<<1 | 1 = 11, index = 2
3rd call: we have previous >= 2, thus we drop the previous and propagate the current index instead of previous value, prev= 1, and index=3
4th call: we have previous <2, thus we or the current index with the previous value, prev 1<<1 | 0 = 10, index = 4
5th call: we enter the base case then return false;

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
