### ISSUE TITLE
Missing Test Case - 1329. Sort the Matrix Diagonally

### ISSUE THREAD

**Issue by VishalRT** [LeetCode-Feedback/LeetCode-Feedback#8834]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Below might be a possible solution for the problem ? 
Sort the matrix Columns, then sort the Rows.

#### Code you used for Submit/Run operation

```
vector<vector<int>> diagonalSort(vector<vector<int>>& mat) {
        int rowLen = mat.size(), colLen = mat[0].size();
        //Sort each column
        for(int i=0; i< colLen; i++){
            for(int j =0 ; j<rowLen-1;j++){
                for(int k =0; k<rowLen-j-1; k++){
                    if(mat[k][i] > mat[k+1][i]){
                        int temp = mat[k][i];
                        mat[k][i] = mat[k+1][i];
                        mat[k+1][i] = temp;
                    }
                }
                
            }
        }
        //Sort each row
        for(int i =0; i< rowLen; i++){
            sort(mat[i].begin(),mat[i].end());
        }
        
        return mat;
    }
```

#### Language used for code
C++

#### Expected behavior
Test case should've passed as per the problem statement.

#### Screenshots
SS for failed test case
![LeetCode](https://user-images.githubusercontent.com/47331073/187072913-1b75ff23-a3b2-426b-b6a4-9882d4d4be06.PNG)

#### Additional context
Below is the failed submission testcase: 
Input: [[11,25,66,1,69,7],[23,55,17,45,15,52],[75,31,36,44,58,8],[22,27,33,25,68,4],[84,28,14,11,5,50]]
Output: [[1,4,5,11,14,25],[7,11,15,17,22,27],[8,23,25,28,33,58],[31,36,44,50,68,75],[45,52,55,66,69,84]]
Expected: [[5,17,4,1,52,7],[11,11,25,45,8,69],[14,23,25,44,58,15],[22,27,31,36,50,66],[84,28,75,33,55,68]] 

Below is the SS for my output above
![LeetCode1](https://user-images.githubusercontent.com/47331073/187073249-c01a2099-f6d1-4f40-8956-05e369870c94.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
