### ISSUE TITLE
757: Problem statement should be rephrased to add more sample inputs

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#8837]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem statement of https://leetcode.com/problems/set-intersection-size-at-least-two/ should be modified to clearly mention that the resultant set need not be a interval consisting of consecutive integers by giving some more sample input
e.g. [[4,5],[7,9]]

Other folks have also raised similar issue: https://leetcode.com/problems/set-intersection-size-at-least-two/discuss/387886/Examples-could-have-been-phrased-a-little-better

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
