### ISSUE TITLE
364. Nested List Weight Sum II  Testcase 26

### ISSUE THREAD

**Issue by xjiahang** [LeetCode-Feedback/LeetCode-Feedback#8839]
#### Your LeetCode username
nathan_code

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Wrong Answer
Runtime: 32 ms
Your input
[[1,1],2,[1,1],[[[[]]]]]
Output
8
Expected
20

#### Code you used for Submit/Run operation

```
class Solution {
    public int depthSumInverse(List<NestedInteger> nestedList) {
        int[] maxDepth = {0};
        int[] sum = {0};
        getDepth(nestedList, 1, maxDepth);
        getSum(nestedList, 1, maxDepth[0], sum);
        
        return sum[0];
    }
    
    private void getDepth(List<NestedInteger> nestedList, int curDepth, int[] maxDepth) {
        if (nestedList == null)
            return;

        maxDepth[0] = Math.max(curDepth, maxDepth[0]);
        for (int i = 0; i < nestedList.size(); i++) {
            NestedInteger cur = nestedList.get(i);
            if (cur.isInteger())
                continue;
            getDepth(cur.getList(), curDepth+1, maxDepth);
        }
    }
    
    private void getSum(List<NestedInteger> nestedList, int curDepth, int maxDepth, int[] sum) {
        if (nestedList == null)
            return;
        
        for (int i = 0; i < nestedList.size(); i++) {
            NestedInteger cur = nestedList.get(i);
            if (cur.isInteger()) {
                int weight = maxDepth - curDepth + 1;
                sum[0] += weight * cur.getInteger();
            } else {
                getSum(cur.getList(), curDepth + 1, maxDepth, sum);
            }
        }
    }
}
```

#### Language used for code
python

#### Expected behavior

the maxDepth definition in question description is " Let maxDepth be the maximum depth of any integer." and "The depth of an integer is the number of lists that it is inside of."
so in above testcase, maxDepth should be 2.  but leetcode counts [[[[]]]]. Actually there is not integer inside at all. So it should not count.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

Our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
