### ISSUE TITLE
Wrong Test Case : 287-Find the Duplicate Number

### ISSUE THREAD

**Issue by leafshinobi007** [LeetCode-Feedback/LeetCode-Feedback#8842]
#### Category of the bug
- [ ] Wrong Test Case

#### Description of the bug

TestCase : [2,2,2,2,2]
According to the question array will have only one duplicate element but here in this test case each element is the same;

#### Code you used for Submit/Run operation

```
class Solution {
    public int findDuplicate(int[] nums) {
        int n = nums.length;
        if(n==2)
            return nums[0];
        int run_sum = nums[0];
        int sum = 0;
        for(int i=1;i<n;i++){
            run_sum += nums[i];
            sum += i;
        }
        
        return run_sum%sum;
    }
};
```

#### Language used for code

Java

**Comment by stormsunshine** [comment]
The element 2 is the duplicate number and is repeated 5 times. Is there any problem?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
