### ISSUE TITLE
Submission errors: 

### ISSUE THREAD

**Issue by Ismail14098** [LeetCode-Feedback/LeetCode-Feedback#8846]
#### Your LeetCode username
https://leetcode.com/jadore_ismael/

#### Category of the bug
- [ ] Solution

#### Description of the bug

My submitted code fails at test case : [[1,5],[2,3],[4,2]]. System says that expected result is 11, in submission it is 9. But when I run this code by [Run Code] option on platform and setting this test case output is 11 (in local machine same result).

#### Code you used for Submit/Run operation

```
long long a [10000][10000];

class Solution {
public:
    void recursion(vector<vector<int>>& points, int r, int c, int rl, int cl) {
        if (r == rl-1){
            a[r][c] = points[r][c];
            return;
        }
        if (a[r][c] != 0)
            return;
        long long res = 0;
        int j = 0;
        while (j < cl) {
            recursion(points, r+1, j, rl, cl);
            res = max(res, (long long) points[r][c] + a[r+1][j] - abs(c - j));
            j++;
        }
        a[r][c] = res;
    }
    long long maxPoints(vector<vector<int>>& points) {
        int rl = points.size(), cl = points[0].size();
        int r = 0, c = 0;
        long long res = 0;
        while (c < cl) {
            recursion(points, r, c, rl, cl);
            res = max(res, a[r][c]);
            c++;
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Described in description section.

#### Screenshots

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/25027704/187272006-6eab369b-b065-40f9-abae-2543fbd98602.png">
![image](https://user-images.githubusercontent.com/25027704/187272197-2a76c419-d20d-4d7a-afee-ea5027e08723.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
