### ISSUE TITLE
1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by khankash** [LeetCode-Feedback/LeetCode-Feedback#8847]
I was able to submit the following solution for the above problem. This solution should not be accepted, if there are multiple 0 elements in the input.

```
class Solution {
public boolean checkIfExist(int[] arr) {
       Arrays.sort(arr);
       int count = 0;
       for(int i = 0; i < arr.length; i++) {
           int val = arr[i] * 2;
           int ind = Arrays.binarySearch(arr, val);
           if(ind >= 0 && ind != i) {
               return true;
           }
      }
     return false;
  }
}
```

input : arr = [0, 0]
when i = 0, the binary search can return 0 
when i = 1, the binary search can return 1
Finally the return false statement will be executed. However, the output for this input should be true.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by khankash** [comment]
I used Java.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test case is already in the test set and did not fail anything. We appreciate your support!
