### ISSUE TITLE
bus routes python solution is not python 3

### ISSUE THREAD

**Issue by morenoh149** [LeetCode-Feedback/LeetCode-Feedback#8848]
#### Your LeetCode username

morenoh149

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/bus-routes/solution/
solution is for python2 not python3, xrange operator no longer exists

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

python

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
