### ISSUE TITLE
Merge Two Sorted Lists (Linked List card) - missing expected answer for one testcase

### ISSUE THREAD

**Issue by syl-nktaylor** [LeetCode-Feedback/LeetCode-Feedback#885]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
In https://leetcode.com/explore/learn/card/linked-list/213/conclusion/1227/ (Merge Two Sorted Lists):

For testcase "[1][1]", the "Expected answer" box is empty/blank.

Same issue observed with both:
Chrome 84.0.4147.135 (64-bit)
Firefox 72.0.2 (64-bit)

#### Code you used for Submit/Run operation
Not required (it only concerns "Expected answer")

#### Language used for code
C++

#### Expected behavior
For testcase "[1][1]", the "Expected answer" should display "[1,1]".

Note: The expected answer does display "[1,1]" in the alternative link for the same problem (https://leetcode.com/problems/merge-two-sorted-lists/ , 21. Merge Two Sorted Lists)

#### Screenshots
Issue ( https://leetcode.com/explore/learn/card/linked-list/213/conclusion/1227/ ):
![image](https://user-images.githubusercontent.com/44095554/91644228-12a09680-ea32-11ea-94e6-8cf51de03bbc.png)

As opposed to ( https://leetcode.com/problems/merge-two-sorted-lists/ ):
![image](https://user-images.githubusercontent.com/44095554/91644266-50052400-ea32-11ea-9223-b593dfa41a7f.png)

**Comment by lc-pam** [comment]
Hi @syl-nktaylor 
Thank you for reaching out to us. Would you mind letting me know if this is a consistent issue on your end? I've tried to reproduce on our end but the expected output is showing correctly. Also, kindly remind that this is a technical issue and we opened the GitHub channel only for content issues. I'll close this ticket for now and please submit a ticket through our [help desk](https://support.leetcode.com/hc/en-us/requests/new) if you're still experiencing the issue. 
<img width="1036" alt="Screen Shot 2020-09-01 at 4 15 14 PM" src="https://user-images.githubusercontent.com/67175512/91915355-2be25680-ec6f-11ea-85ff-bd0641ed5b02.png">

**Comment by syl-nktaylor** [comment]
Hi @lc-pam , Yes, it is a consistent issue on 2 machines and with different browsers. Thank you for letting me know about the helpdesk support for technical issues. Cheers!
