### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by acelyavul** [LeetCode-Feedback/LeetCode-Feedback#8853]
#### Your LeetCode username

acelyavul

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ]  Missing Test Cases 

#### Description of the bug

if i understand the question correctly, i can't sell if the buying day is the last day, 
so it means that if the min value is last index, it returns 0.

Test Case: 
Example 2:
Input: prices = [7,6,4,3,1]
Output: 0
Explanation: In this case, no transactions are done and the max profit = 0.

But it fails in another test which is similar to this one. I added a screenshot. I am not sure what i am missing.

#### Code you used for Submit/Run operation

```
var maxProfit = function (prices) {
  const min = Math.min(...prices);
  let max = Math.max(...prices);
  const lastIndex = prices.length - 1;
  let maxProfit;

  if (prices.indexOf(min) === lastIndex) {
    maxProfit = 0;
    return maxProfit;
  }

  if (prices.indexOf(max) < prices.indexOf(min)) {
    prices = prices.filter(el => el !== max);
    max = Math.max(...prices);
    maxProfit = max - min;
    return maxProfit;
  }

  maxProfit = max - min;
  return maxProfit;
};
```

#### Language used for code

Javascript

#### Expected behavior

expected value should be 0

#### Screenshots

![Ekran Alıntısı](https://user-images.githubusercontent.com/88436030/187310816-173cc750-2a08-49ab-9d2c-8b936076457b.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by acelyavul** [comment]
Thank you so much
