### ISSUE TITLE
Wrong Test Case - 224. Basic Calculator

### ISSUE THREAD

**Issue by viiviii** [LeetCode-Feedback/LeetCode-Feedback#8855]
#### Your LeetCode username
user8519f

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
If a space is between numbers, the `Expected` is incorrect.

e.g.
- `"1 + 1 23"` output `Invalid Testcase`
- `"1 +1 23"` output `Wrong Answer`
  - Output=124, Expected=25
  - But 25 is wrong

I think `+1` is calculated as a unary operation.
However, the constraint has 
```
'+' is not used as a unary operation (i.e., "+1" and "+(2 + 3)" is invalid).
```
correct result is `124` or `Invalid Testcase`.

And if the answer to `"1 +1 23"` is 124, what are the answers to `"1 -1 23"` and `"1 -1 -23"`?
- I think `"1 -1 23"` is `-122`, `"1 -1 -23"` is `-23`
- In this case, it would be good to add a test case.

If it `Invalid Testcase`, it is recommended that you add information about space to the description.

#### Code you used for Submit/Run operation
```python
# 224. Basic Calculator
class Solution:
    def calculate(self, s: str) -> int:
        left, operator, right = 0, '+', 0
        stack = []
        for c in s:
            if c.isdigit():
                right = right * 10 + int(c)
            elif c == '(':
                stack.append((left, operator))
                left, operator = 0, ''
            elif c == ')':
                right = self.evaluate(left, operator, right)
                left, operator = stack.pop()
            elif c in ('-', '+'):
                left = self.evaluate(left, operator, right)
                operator, right = c, 0
        return self.evaluate(left, operator, right)
    
    def evaluate(self, left_operand: int, operator: str, right_operand: int) -> int:
        match operator:
            case '':
                return right_operand
            case '-':
                return left_operand - right_operand
            case '+':
                return left_operand + right_operand
```

#### Language used for code
Python3

#### Expected behavior
`124` or `Invalid Testcase`

#### Screenshots
<img width="563" alt="image" src="https://user-images.githubusercontent.com/75404713/187425896-c5b128ac-a215-4940-b5d7-4981bec5cbd2.png">

<img width="608" alt="image" src="https://user-images.githubusercontent.com/75404713/187431948-ad9f3fbf-b303-4081-a99b-1a056c2d2350.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've Fixed the validator. We appreciate your support!
