### ISSUE TITLE
Wrong Test Case - 457. Circular Array Loop

### ISSUE THREAD

**Issue by navidre** [LeetCode-Feedback/LeetCode-Feedback#8857]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Wrong Test Case

#### Description of the bug
Either the question should be fixed or the test cases.

##### Suggestions for fixing the question

Assumption 1: Starting from index 0. These are the loops happening.
If this assumption is not correct, it is better for the question to mention that you can start from any index.

Assumption 2: Another assumption in the question is that all cycle values must be positive or negative. However, it seems that the question means that the next item must have the same sign as the current. For example, if current value is 1 and we reach -1, then we should ignore and go to the next value.

##### Suggestions for fixing the the test cases

[3,1,2] results in cycle of length 1; therefore should be False based on the description, but the test case is considered True!
Cycle: 0 --> 0 --> 0 --> ...

[1,-1,2,4,4] test case is also incorrect, because the loop values alternate between positive and negative. Based on the description, this is not a loop.
Cycle: 0 --> 1 --> 0 --> 1 --> ...

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The statement is clear in the mentioned test cases and the expected answer is correct in both.
Changed the examples and added explanations to them. The new examples cover more test cases. We appreciate your support!
