### ISSUE TITLE
895 / Maximum Frequency Stack

### ISSUE THREAD

**Issue by VKokielov** [LeetCode-Feedback/LeetCode-Feedback#8858]
#### Your LeetCode username
vkokielov

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Just wanted to report that you don't need to keep track of the max frequency at all.  Nor do you need to keep the stack of stacks as a MAP

The maximum frequency of an element can only rise by ONE (+1).  This means when you pop, you remove an integer from the "most frequent" bin.  When you PUSH, you add an integer -- to what?  either to one of the existing bins, or to the bin with the largest frequency, plus one.

You still need a frequency table to keep track of the frequencies of each integers.  But you don't really need a map to keep track of the second stack or of the maximum size.  You can get away with a real stack of stacks, as long as you make sure to pop it whenever its bins go empty.  The index into the "top" stack is frequency - 1.

I attached my C++ solution
[freq_stack.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9454670/freq_stack.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
