### ISSUE TITLE
LeetCode Question #987 - Wrong result for testcase #15

### ISSUE THREAD

**Issue by dnup1092** [LeetCode-Feedback/LeetCode-Feedback#886]
#### Your LeetCode username
azmishra

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The solution for testcase #15 is not as per the question [#987](https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/). As per the question  [#987](https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/) in case of tie we have to consider the value of node which is reported first

#### Code you used for Submit/Run operation

```
// [Vertical order traversal of a binary tree](https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/)
class Solution {
        public List<List<Integer>> verticalTraversal(TreeNode root) {
        if(root == null)
            return null;
        Map<Integer,ArrayList<Coordinate>> cache = new TreeMap<>();
        dfs(cache, root, 0, 0);
        List<List<Integer>> results = new ArrayList<>();
        for(Map.Entry<Integer,ArrayList<Coordinate>> entry : cache.entrySet()) {
            ArrayList<Coordinate> coordinates = entry.getValue();
            Collections.sort(coordinates);
            results.add(getValues(coordinates));
        }
        return results;
    }
    
    public List<Integer> getValues(ArrayList<Coordinate> list) {
        List<Integer> res = new ArrayList<>();
        for(Coordinate c : list) {
            res.add(c.value);
        }
        return res;
    }
    
    public void dfs(Map<Integer,ArrayList<Coordinate>> cache, TreeNode root,int coordY, int coordX) {
        if(root == null) {
            return;
        }
        ArrayList<Coordinate> coordinatesLeft = cache.get(coordY);
        if(coordinatesLeft == null) {
            coordinatesLeft = new ArrayList<>();
        }
        coordinatesLeft.add(new Coordinate(coordX, coordY,root.val));
        cache.put(coordY, coordinatesLeft);
        dfs(cache,root.left,coordY - 1, coordX + 1);
        dfs(cache,root.right,coordY + 1, coordX + 1);
    }
    
}

class Coordinate implements Comparable<Coordinate> {
    protected int X;
    protected int Y;
    protected int value;
    
    public Coordinate(int X, int Y, int value) {
        this.X = X;
        this.Y = Y;
        this.value = value;
    }
    
    public int compareTo(Coordinate c) {
        return this.X - c.X;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Testcase#15 - [0,2,1,3,null,null,null,4,5,null,7,6,null,10,8,11,9].
LeetCode Testcase Solution =
[[4,10,11],[3,6,7],[2,5,8,9],[0],[1]]

My Solution = [[4,10,11],[3,7,6],[2,5,8,9],[0],[1]]

Difference is [3,7,6] and [3,6,7]. As per the question in case of tie we have to consider the value of node which is reported first and clearly 7 was added before 6 so the order should be [3,7,6] and not [3,6,7].

**Comment by lc-pam** [comment]
Hi @dnup1092 
Thank you for reaching out to us. I recommend you raise your question or look for similar posts in the [problem's discuss tab](https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/discuss/?currentPage=1&orderBy=newest_to_oldest&query=). I've found multiple posts that raised the same question and most of the post received explanations from other users.
