### ISSUE TITLE
1138. Alphabet Board Path. Wrong checker

### ISSUE THREAD

**Issue by mehrdod** [LeetCode-Feedback/LeetCode-Feedback#8862]
Username: mondayguy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The code below WA-s on the test
"zb"
Output: "DDDDD!RUUUUU!"
Expected: "DDDDD!UUUUUR!"
But this answers are actually equal, because description says "You may return any path that does so."

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
    string board[6] = {"abcde", "fghij", "klmno", "pqrst", "uvwxy", "z"};
    
    string getPath(int xFrom, int yFrom, int xTo, int yTo) {
        //cout<< xFrom<<' '<< yFrom<<' '<< xTo<<' '<< yTo<< endl;
        string path = "";
        while (yFrom < yTo) {
            yFrom++;
            path += "R";
        }
        while (yFrom > yTo) {
            yFrom--;
            path += "L";
        }
        while (xFrom < xTo) {
            xFrom++;
            path += "D";
        }
        while (xFrom > xTo) {
            xFrom--;
            path += "U";
        }
        
        path += "!";
        return path;
    }
    
    string alphabetBoardPath(string target) {
        int rowNum = 6;
        vector<pair<int, int>> positions(26);
        
        
        for (int i = 0; i < rowNum; i++) {
            for (int j = 0; j < board[i].size(); j++) {
                positions[board[i][j] - 'a'] = {i, j};
            }
        }
        
        string path = "";
        
        int curX = 0, curY = 0;
        
        for (int i = 0; i < target.size(); i++) {
            auto nextPos = positions[target[i] - 'a'];
            path += getPath(curX, curY, nextPos.first, nextPos.second);
            curX = nextPos.first;
            curY = nextPos.second;
        }
        return path;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Please fix the checker of the answer. Because multiply acceptable answers are permitted

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes! The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.

We appreciate your time and support! If you have any other questions, please don't hesitate to let us know.
