### ISSUE TITLE
Wrong Test Case Result: Find Median from Data Stream

### ISSUE THREAD

**Issue by arahull** [LeetCode-Feedback/LeetCode-Feedback#8863]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

295. Find Median from Data Stream: test case answer is wrong
https://leetcode.com/problems/find-median-from-data-stream/

#### Code you used for Submit/Run operation

```
import math
class MedianFinder(object):

    def __init__(self):
        self.arr = []
        

    def addNum(self, num):
        """
        :type num: int
        :rtype: None
        """
        self.arr.append(num)
        

    def findMedian(self):
        """
        :rtype: float
        """
        l = len(self.arr) 
        if l == 1:
            print (self.arr[0], self.arr)
            return self.arr[0]
        
        if  l % 2 == 0:
            ml = int(math.floor(l/2)) - 1
            mr = ml + 1
            m = (float(self.arr[ml]) + float(self.arr[mr])) /2

        else:
            m = self.arr[int(float(l)//2)]
        
        print (m,self.arr)
        return m

```

#### Expected behavior

Input ["MedianFinder","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian"]
[[],[6],[],[10],[],[2],[],[6],[],[5],[],[0],[],[6],[],[3],[],[1],[],[0],[],[0],[]]

Output
[null,null,6.00000,null,8.00000,null,10.00000,null,6.00000,null,2.00000,null,4.00000,null,6.00000,null,5.50000,null,5.00000,null,2.50000,null,0.00000]
Expected
[null,null,6.00000,null,8.00000,null,6.00000,null,````6.00000````,null,6.00000,null,5.50000,null,6.00000,null,5.50000,null,5.00000,null,4.00000,null,3.00000]

the median of [6,10,2] is not 6

#### Screenshots

<img width="951" alt="Screen Shot 2022-08-31 at 12 47 41 AM" src="https://user-images.githubusercontent.com/30901748/187596298-37eb6a28-a794-42bd-bee0-a3454b691979.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
