### ISSUE TITLE
Missing Test Case - 120. Triangle

### ISSUE THREAD

**Issue by EbrG786** [LeetCode-Feedback/LeetCode-Feedback#8865]
#### Your LeetCode username

EbrahimMG

#### Category of the bug
- [ 120 ] Question
- [ Python] Language

#### Description of the bug

[[-1],[2,3],[1,-1,-3]]
The following test case should give the answer of -2 but is giving the answer of -1

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def minimumTotal(self, triangle: List[List[int]]) -> int:
        sum = 0
        for i in triangle:
            sum += min(i)
        return sum
```

#### Expected behavior

Expected to return -2 but returned -1 as the solution.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.

We appreciate your time and support! If you have any other questions, please don't hesitate to let us know.
