### ISSUE TITLE
Missing test case | 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by jerry7991** [LeetCode-Feedback/LeetCode-Feedback#8866]
#### Your LeetCode username
faltu_admi

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
My bellow code is getting accepted but the code isn't passing some test cases(which I have created).

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isDone(vector<int> &f, int k) {
        for(int i:f) {
            if(i && i<k) return false;
        }
        return true;
    }
    bool isPossible(string &s, int n, int k) {
        vector<int> fre(26,0);
        int i=0,j=0;
        while(i<n) {
            fre[s[i++]-'a']++;
        }
        if(isDone(fre, k)) return true;
        while(i<s.size()) {
            fre[s[i++]-'a']++;
            fre[s[j++]-'a']--;
            if(isDone(fre, k)) return true;
        }
        return false;
    }
    
    int longestSubstring(string &s, int k) {
        vector<int> num;
        for(int i=k;i<=s.size();i+=k) num.push_back(i);
        int left = 0,  right = num.size()-1, res=-1;
        while(left<=right) {
            int mid = (left+right)/2;
            if(isPossible(s, num[mid], k)) {
                res = mid;
                left = mid+1;
            } else {
                right = mid-1;
            }
        }
        if(res<0) return 0;
        res = num[res];
        left=1,right=0;
        while(left<=2*k && res+left<s.size()) {
            if(isPossible(s, res+left, k)) {
                right = left;
            }
            left++;
        }
        return res+right;
    }
};
```

#### Language used for code
c++

#### Expected behavior
My above code should give wa for the below test case.
#### Test case 
"aaaaaaaaaaaaa"
2

Expected 
13
Actual 
12
_**Still my code getting accepted.**_

#### Accepted Solution
https://leetcode.com/submissions/detail/788063665/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by jerry7991** [comment]
Thanks alot.
