### ISSUE TITLE
Missing Test Case - 28. Implement strStr()

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#8868]
#### Your LeetCode username
RohitSgh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code is getting [submitted](https://leetcode.com/submissions/detail/788270286/), but ideally it should not be. It should get failed on Test Case
"cadbbca"
"fghivbt"

#### Code you used for Submit/Run operation

```python3
class Solution:
    def strStr(self, haystack: str, needle: str) -> int:

        m = len(needle)
        n = len(haystack)

        if n < m:
            return -1

        # CONSTANTS
        RADIX = 26
        MOD = 1_000_000_033
        MAX_WEIGHT = (26**m) % MOD

        # Function to compute hash of m-String
        def hash_value(string):

            ans = 0
            factor = 1

            for i in range(m-1, -1, -1):
                ans += ((ord(string[i])-97)*(factor)) % MOD
                factor = (factor*RADIX) % MOD

            return ans % MOD

        # Compute hash of needle
        hash_needle = hash_value(needle)

        # Check for each m-substring of haystack, starting at index window_start
        for window_start in range(n-m+1):

            if window_start == 0:
                # Compute hash of First Substring
                hash_hay = hash_value(haystack)
            else:
                # Update Hash using Previous Hash Value in O(1)
                hash_hay = ((hash_hay*RADIX) % MOD - ((ord(haystack[window_start-1])-97)*(
                    MAX_WEIGHT)) % MOD + (ord(haystack[window_start+m-1])-97)) % MOD

            # If hash matches, return window_start
            if hash_needle == hash_hay:
                return window_start

        return -1
```

#### Language used for code
Python3

#### Expected behavior

Code will return 0, but ideally, should return -1. The code is getting submitted, though!

#### Screenshots

Link of [Submitted Code](https://leetcode.com/submissions/detail/788270286/) is attached. 

Wrong Answer on One Test Case    

> ![image](https://user-images.githubusercontent.com/81853910/187770630-a560167b-03cd-4d86-b644-791d0202a60b.png)

#### Additional context

The algorithm in code uses Rabin Karp with single hashing for string matching. It doesn't check for spurious hits, and return False Positive

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
