### ISSUE TITLE
686. Repeated String Match test case 3 is broken

### ISSUE THREAD

**Issue by starstout** [LeetCode-Feedback/LeetCode-Feedback#887]
The input is:

"abc
"wxyz"

one of the " is missing in the first string. Please it.

**Comment by lc-pam** [comment]
Hi @starstout 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @starstout ,
Thank you for your time! The team has acknowledged and fixed the issue.
