### ISSUE TITLE
Missing Test Case - 1016. Binary String With Substrings Representing 1 To N

### ISSUE THREAD

**Issue by valentynkvasov** [LeetCode-Feedback/LeetCode-Feedback#8871]
#### Your LeetCode username
vkvasov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The attached solution passed all test cases, however, it shouldn't.

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean queryString(String s, int n) {
        Set<Integer> set = new HashSet<>();
        int range = n;
        
        int maxWindowSize = 0, copy = n;
        
        while(copy > 0) {
            maxWindowSize++;
            copy >>= 1;
        }
        
        int left = 0, right = 0;
        StringBuilder sb = new StringBuilder();
        while(right < s.length()) {
            sb.append(s.charAt(right++));
            
            int num = Integer.parseInt(sb.toString(), 2);
                
            if(num <= n && !set.contains(num)) {
               set.add(num);
               range--;
            }  
            
            if(range == 0) {
                return true;
            }
            
            if(right - left == maxWindowSize) { 
                sb.deleteCharAt(0);
                left++;
            }
        }
        
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The test case is
"0"
1
My code returns true which is the wrong answer, however, the solution passes all test cases.
The expected behavior: it doesn't accept the solution

#### Screenshots
<img width="402" alt="Screenshot at Sep 01 12-49-18" src="https://user-images.githubusercontent.com/62186985/187885647-0f74f5fe-a7da-4c70-8f0f-f819d114b217.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
