### ISSUE TITLE
Description improvement - 298. Binary Tree Longest Consecutive Sequence

### ISSUE THREAD

**Issue by Mestrace** [LeetCode-Feedback/LeetCode-Feedback#8874]
#### Your LeetCode username

monte_carrrrrlo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I misunderstood the problem. Implemented for both +1 and -1 sequences but the problem actually only take +1 sequences. 

#### Code you used for Submit/Run operation

```go
/**
 * Definition for a binary tree node.
 * type TreeNode struct {
 *     Val int
 *     Left *TreeNode
 *     Right *TreeNode
 * }
 */
func longestConsecutive(root *TreeNode) int {
    var result int
    
    // longest(root, root.Val - 2, 1, -1, &result)
    longest(root, root.Val - 2, 1, 1, &result)
    
    return result
}

func longest(root *TreeNode, last, size, dir int, result *int) {
    if root == nil {
        return
    }
    
    if last + dir == root.Val {
        size++
    } else {
        size = 1
    }
    
    *result = max(*result, size)
    
    longest(root.Left, root.Val, size, dir, result)
    longest(root.Right, root.Val, size, dir, result)
}

func max(i, j int) int {
    if i > j {
        return i
    }
    return j
}
```

#### Language used for code

Golang

#### Expected behavior

The description of the question should clearly state that the sequence is increasing by 1.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
