### ISSUE TITLE
Missing Test Case - 290. Word Pattern

### ISSUE THREAD

**Issue by truefuego** [LeetCode-Feedback/LeetCode-Feedback#8876]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

 The Question is missing a test case for the given code solution

#### Code you used for Submit/Run operation
```
// Word Pattern
class Solution {
public:
    bool wordPattern(string pattern, string s) {
        map<string,int> mp;
        string s1;
        vector<string> v;
        string temp;
        for(char c : s){
            if(c == ' '){
                v.push_back(temp);
                temp.clear();
            }
            else{
                temp.push_back(c);
            }
        }
        v.push_back(temp);
        int i = 0;
        for(string str : v) {
            if(mp.find(str) == mp.end()) {
                mp[str] = i++;
                s1 += to_string(i);
            }
            else {
                s1 += to_string(mp[str]);
            }
            mp[str] = i;
        }
        unordered_map<char,int> m;
        i = 0;
        string s2;
        for(char c : pattern) {
            if(m.find(c) == m.end()) {
                m[c] = i++;
                s2 += to_string(i);
            }
            else {
                s2 += to_string(m[c]);
            }
            m[c] = i;
        }
        cout << s1 << " " << s2;
        return s1 == s2;
    }
};


```

#### Expected behavior
The solution gave WA for the given testcase, which is a wrong solution upon resolving and getting the pattern strings for the given two strings both string's pattern are coming out to be the same while both of the string having different patterns.

The test case are as following :
      pattern : "papap"
      s : "po io po io io"

#### Screenshots

<img width="1440" alt="Screenshot 2022-09-01 at 8 51 35 PM" src="https://user-images.githubusercontent.com/108484686/187954299-5a078205-e59b-44ba-a8fd-4b16e5ebba58.png">

#### Additional context
 I submitted the code for "290. Word Pattern" on 08/30/2022 and it got accepted upon some further research on 09/01/2022 after attempting "205. Isomorphic Strings" I stumbled upon a curious test case and used the similar test case for 290. Word Pattern I 
 recieved a WA.

I look forward to the LeetCode team to resolve this issue;

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
