### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by aospiridonov** [LeetCode-Feedback/LeetCode-Feedback#8877]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Time Limit Exceeded (4580 / 11510 test cases passed.)

#### Code you used for Submit/Run operation

```
// Is Palindrom
class Solution {
  bool isPalindrome(int x) {
    if (x < 0 || (x % 10 == 0 && x != 0)) {
      return false;
    }
    int revertedNum = 0;
    while (x > revertedNum) {
      revertedNum = revertedNum * 10 + x % 10;
      x ~/= 10;
    }
    return x == revertedNum || x == revertedNum ~/ 10;
  }
}
```

#### Language used for code
Dart

#### Expected behavior

Increase time limits for dart or fix a bug.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the developing team.  We appreciate your support!
