### ISSUE TITLE
Issues in the video tutorial for BFS in the Explore Graph Card

### ISSUE THREAD

**Issue by yyggzz** [LeetCode-Feedback/LeetCode-Feedback#8879]
In the article of Shortest Path Between Two Vertices - Breadth-First Search (https://leetcode.com/explore/learn/card/graph/620/breadth-first-search-in-graph/3852/):

1) The video said it has found all the paths from A to F. However, it seems that paths A-C-E-B-F and A-D-E-B-F are not included. I think this general traversal method should not be used for "finding the shortest path" and "finding all the paths" at the same time. For finding all the paths, the "visited" set should be tackled differently.

2) The description of finding "the shortest path" is not strict. For example, if node D is connected to F, there will be two shortest path A-D-F and A-B-F. So this algorithm technically just finds the "shortest distance" between node A and F, or one of the shortest path.

#### Your LeetCode username

YYYami

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Those terms are conventional.. We appreciate your support!
