### ISSUE TITLE
Question descreption error

### ISSUE THREAD

**Issue by Yogendra07** [LeetCode-Feedback/LeetCode-Feedback#888]
#### Category of the bug
https://leetcode.com/problems/pancake-sorting/

#### Description of the bug
You can see that in the problem you have written
Reverse the sub-array A[0...k]

but in the sample test case
After 1st flip (k = 4): A = [1, 4, 2, 3]

according to you k ranges from 0 - 4 ... you can see in above how is even this possibe ? this is leading to multiple errors..
please resolve it

#### Screenshots

[https://ibb.co/vPsH8KB ](url)

**Comment by lc-pam** [comment]
Hi @Yogendra07 
Thank you for reaching out to us. The team has acknowledged the issue and updated the problem.
