### ISSUE TITLE
Unexpected Behaviour - 2265. Count Nodes Equal to Average of Subtree

### ISSUE THREAD

**Issue by Sunil4510** [LeetCode-Feedback/LeetCode-Feedback#8883]
#### Your LeetCode username
skurapatim3100 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
**Unexpected Behavior**
_It works when I run the code for input->[1]_
_but It fails when I submit code for the input->[1]_
_The input is same in both conditions works when run the code but fails when submit the code._

#### Code you used for Submit/Run operation

```
// Count Nodes Equal to Average of Subtree
let count=0;
var averageOfSubtree = function(root) {
    if(root==null)return count;
    sub(root);
    console.log(count);
    return count;
};
function sub(root){
    if(root==null)return [0,0];
    let left = sub(root.left);
    let right = sub(root.right);
    let sum = left[0]+right[0]+root.val;
    let total = left[1]+right[1]+1;
    let t=parseInt(sum/total);
    console.log(t)
    if(t==root.val){
        count++;
    }
    return [sum,total];    
}
```

#### Language used for code
**JavaScript**

#### Screenshots
![Screenshot (139)](https://user-images.githubusercontent.com/77005171/188092016-d4128389-5811-44cf-a52e-cebe7f2e1638.png)
![Screenshot (137)](https://user-images.githubusercontent.com/77005171/188092530-5914b4a8-4a3f-436d-b1cb-3e0468e18f05.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
