### ISSUE TITLE
 1. Two Sum[arrays]/leetcode/solution

### ISSUE THREAD

**Issue by BadisaSaiSantosh** [LeetCode-Feedback/LeetCode-Feedback#8884]
class Solution {
    public int[] twoSum(int[] nums, int target) {  

/* no need of re-declaring nums and target variables...it will throw a error due to duplicate of variables*/ 

        int len=nums.length;
        for(int i=0;i<len;i++){
         for(int j=i+1;j<len;j++){
             if(nums[i]+nums[j]==target)
/* if we go println it will show a compilation */.
            return new int[] { i, j };
         }
        
       }
/* method type is an int so it should return a value ... so return null.... null means empty*/
    return null;
    }
}

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The Language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
