### ISSUE TITLE
LCP 39. 无人机方阵 填入示例

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#8885]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 填入示例

**描述**
**填入**的示例1与**题目**的示例1不一致。

**你使用的语言**
Python

**期望行为**
**填入**的示例1改为
[[1,3],[5,4]]
[[3,1],[6,5]]

**屏幕截图**
![image](https://user-images.githubusercontent.com/25954059/188121713-2b493618-52c1-436a-8c1d-c92f4b124000.png)

**额外的上下文**
[题目链接](https://leetcode.cn/problems/0jQkd0/?plan=lccup&plan_progress=zezf7y7)

**Comment by BrambleWave** [comment]
你好，当前该题已添加，奖励已发放。
