### ISSUE TITLE
OLD VERSION

### ISSUE THREAD

**Issue by Ayushluthra2001** [LeetCode-Feedback/LeetCode-Feedback#8887]
#### Your LeetCode username

ayushluthra62

#### Category of the bug
- [ ] UI/UX Design 
#### Description of the bug

 Revert to old version Button is not working.

**Comment by LC-Pam** [comment]
We apologize for the inconvenience the recent changes may cause. Currently, to switch back to old UI:

1. Please go to your profile page [leetcode.com/profile/lab](http://pleetcode.com/profile/lab) and open the 'Opt-in for further beta testing' option.

2. Go to any question description page, for example, https://leetcode.com/problems/two-sum/. 

3. Click your avatar, you can then switch to the old version from the user menu drop-down.

I hope this clarifies things, and if you have any more questions please do not hesitate to let me know, and I will be more than happy to assist you!
