### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by ahmmmmad11** [LeetCode-Feedback/LeetCode-Feedback#8889]
#### Your LeetCode username
alamerahmed00

#### Category of the bug
- [x] Solution

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def lengthOfLongestSubstring(self, s: str, curr: list = []) -> int:
        result = 1
        for i in range(len(s) - 1):
            if s[i] in curr or len(s) == 1:
                curr = []
                return 0
            else:
                curr.append(s[i])
                neww = 1 + self.lengthOfLongestSubstring(s[i+1:], curr)
                if (result < neww):
                    result = neww
            return result
```

#### Language used for code
Python 3

#### Expected behavior

in the test case number (3) "bbbbb" leetCode editor indicate there is an error and my code prints "0" rather than print "1",
but when I tested my code in my local machine it prints the right result "1", I will attach a screenshot

#### Screenshots

![Screenshot 2022-09-02 153647](https://user-images.githubusercontent.com/42531546/188158182-62bb4fc5-307f-4588-9e70-c6c1c6a8165a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
