### ISSUE TITLE
Constraint correction - 688. Knight Probability in Chessboard

### ISSUE THREAD

**Issue by subodhr258** [LeetCode-Feedback/LeetCode-Feedback#8890]
#### Your LeetCode username

subodhr2001

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the constraints: ```0 <= row, column <= n``` seems to be incorrect, because (row,column) is only from (0,0) to (n-1,n-1).

#### Code you used for Submit/Run operation

```
\\Knight Probability in Chessboard
class Solution {
public:
    vector<vector<int>> v = {{2,-1},{2,1},{1,-2},{1,2},{-2,1},{-2,-1},{-1,2},{-1,-2}};
    double rec(int& n, int k, int r, int c,vector<vector<vector<double>>>& dp)
    {
        if(r<0 || r>=n || c<0 || c>=n) return 0;
        if(k==0) return 1;
        if(dp[k][r][c]!=-1) return dp[k][r][c];
        double res = 0;
        for(auto x : v)
        {
            res+=rec(n,k-1,r+x[0],c+x[1],dp);
        }
        return dp[k][r][c] = res/8;
    }
    double knightProbability(int n, int k, int row, int column) {
        vector<vector<vector<double>>> dp(k+1,vector<vector<double>>(n, vector<double>(n,-1)));
        return rec(n,k,row,column,dp);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The constraint should be ```0 <= row, column < n```

#### Screenshots

![image](https://user-images.githubusercontent.com/58080782/188212985-fe8b9dd7-6e61-45d8-946d-5dbea0e59787.png)

#### Additional context

Thanks

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
