### ISSUE TITLE
716. Max Stack (both the offcial given solution and the entire stack method cannot pass the testcase)

### ISSUE THREAD

**Issue by sil123456** [LeetCode-Feedback/LeetCode-Feedback#8896]
#### Your LeetCode username
silhouette123

#### Category of the bug
- [ ] Question
- [ ] Solution

#### Description of the bug
716. Max Stack (both the offcial given solution and the entire stack method cannot pass the testcase)

#### Code you used for Submit/Run operation

```
class MaxStack(list):
    def push(self, x):
        m = max(x, self[-1][1] if self else None)
        self.append((x, m))

    def pop(self):
        return list.pop(self)[0]

    def top(self):
        return self[-1][0]

    def peekMax(self):
        return self[-1][1]

    def popMax(self):
        m = self[-1][1]
        b = []
        while self[-1][0] != m:
            b.append(self.pop())

        self.pop()
        map(self.push, reversed(b))
        return m
```

#### Language used for code
Python

#### Expected behavior
Cannot even run the general case and the entire stack method cannot pass all the testcases

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
Please provide us your Leetcode Username.
