### ISSUE TITLE
843. 猜猜这个单词  此道题官方给出的答案有问题

### ISSUE THREAD

**Issue by lleiyyang** [LeetCode-Feedback/LeetCode-Feedback#8897]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
sam-114

**Bug 类型**
- [ ] 题目 843. 猜猜这个单词
- [ ] 题解： 
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
![image](https://user-images.githubusercontent.com/39645792/188267828-a6e50525-ac84-4273-ad5b-bfd245f66e30.png)
官方的代码是 while (!possible.isEmpty()) ， 正如截图所示我替换成for (int i = 0; i < 10; ++i) {}
因为题目指明说最多猜10次， 因此我把逻辑改成最多猜10次， 按理是等价变形， 但是结果没有通过

怀疑点：力扣后台的校验猜测次数的逻辑有问题， 需帮确认下

具体测试用例如下：
"aaaata"
["aaaaga","aaaaka","aaauaa","aaaaoa","aafaaa","aaaaza","aaaava","agaaaa","aaagaa","aaaaqa","aaaaca","aaaaua","apaaaa","aawaaa","aaaaba","aaaqaa","aayaaa","aaaaja","aaacaa","aaayaa","aaaeaa","aavaaa","aasaaa","aaaapa","aaaaxa","aeaaaa","aaxaaa","akaaaa","aaaoaa","aazaaa","anaaaa","aaaala","aaraaa","aaaata","aaaaia","ajaaaa","aaaaaa","ahaaaa","aaaraa","aaaiaa","aanaaa","alaaaa","aakaaa","aiaaaa","aajaaa","aaakaa","axaaaa","aaqaaa","aaamaa","aapaaa","aaafaa","aaasaa","aadaaa","amaaaa","aaaaea","aabaaa","aaaama","asaaaa","acaaaa","aaiaaa","avaaaa","afaaaa","aoaaaa","aamaaa","aaaasa","aaawaa","azaaaa","aataaa","aaeaaa","aaaafa","aaahaa","aaalaa","aaaana","aaanaa","aaabaa","aaaada","auaaaa","aaapaa","awaaaa","ayaaaa","adaaaa","aaavaa","aagaaa","aauaaa","abaaaa","aaadaa","aqaaaa","aaaxaa","aaaawa","aaajaa","araaaa","aahaaa","aaaaha","aacaaa","aaaara","aaoaaa","ataaaa","aaaaya","aalaaa","aaazaa"]
30

**你使用的语言**
Java

**你提交或者运行的代码**
```
// 该代码来自力扣官方给出的代码
class Solution {
    int[][] H;
    public void findSecretWord(String[] wordlist, Master master) {
        int N = wordlist.length;
        H = new int[N][N];
        for (int i = 0; i < N; ++i)
            for (int j = i; j < N; ++j) {
                int match = 0;
                for (int k = 0; k < 6; ++k)
                    if (wordlist[i].charAt(k) == wordlist[j].charAt(k))
                        match++;
                H[i][j] = H[j][i] = match;
            }

        List<Integer> possible = new ArrayList();
        List<Integer> path = new ArrayList();
        for (int i = 0; i < N; ++i) possible.add(i);

        for (int i = 0; i < 10; ++i) {
            int guess = solve(possible, path);
            int matches = master.guess(wordlist[guess]);
            if (matches == wordlist[0].length()) return;
            List<Integer> possible2 = new ArrayList();
            for (Integer j: possible) if (H[guess][j] == matches) possible2.add(j);
            possible = possible2;
            path.add(guess);
        }

    }

    public int solve(List<Integer> possible, List<Integer> path) {
        if (possible.size() <= 2) return possible.get(0);
        List<Integer> ansgrp = possible;
        int ansguess = -1;

        for (int guess = 0; guess < H.length; ++guess) {
            if (!path.contains(guess)) {
                ArrayList<Integer>[] groups = new ArrayList[7];
                for (int i = 0; i < 7; ++i) groups[i] = new ArrayList<Integer>();
                for (Integer j: possible) if (j != guess) {
                    groups[H[guess][j]].add(j);
                }

                ArrayList<Integer> maxgroup = groups[0];
                for (int i = 0; i < 7; ++i)
                    if (groups[i].size() > maxgroup.size())
                        maxgroup = groups[i];

                if (maxgroup.size() < ansgrp.size()) {
                    ansgrp = maxgroup;
                    ansguess = guess;
                }
            }
        }

        return ansguess;
    }
}

作者：LeetCode
链接：https://leetcode.cn/problems/guess-the-word/solution/cai-cai-zhe-ge-dan-ci-by-leetcode/
来源：力扣（LeetCode）
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
```

**期望行为**
描述你期望的结果

**屏幕截图**

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收。
