### ISSUE TITLE
[ 2394. Employees With Deductions ] Wrong Examples on Description and Missing Test Cases and 

### ISSUE THREAD

**Issue by 0417taehyun** [LeetCode-Feedback/LeetCode-Feedback#8898]
#### Your LeetCode username

0417taehyun

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

First, the example on the description part is wrong.

The below is original example on the description part. However, *On 2022-10-29, they worked for 7 hours and 59 minutes* sentence which is described the Employee 2 is wrong because the time difference between `2022-10-29 23:58:58` and `2022-10-29 12:00:00` are **11 hours 59 minutes**, not *7 hours and 59 minutes*.

```
Input: 
Employees table:
+-------------+--------------+
| employee_id | needed_hours |
+-------------+--------------+
| 1           | 20           |
| 2           | 12           |
| 3           | 2            |
+-------------+--------------+
Logs table:
+-------------+---------------------+---------------------+
| employee_id | in_time             | out_time            |
+-------------+---------------------+---------------------+
| 1           | 2022-10-01 09:00:00 | 2022-10-01 17:00:00 |
| 1           | 2022-10-06 09:05:04 | 2022-10-06 17:09:03 |
| 1           | 2022-10-12 23:00:00 | 2022-10-13 03:00:01 |
| 2           | 2022-10-29 12:00:00 | 2022-10-29 23:58:58 |
+-------------+---------------------+---------------------+
Output: 
+-------------+
| employee_id |
+-------------+
| 2           |
| 3           |
+-------------+
Explanation: 
Employee 1:
 - Worked for three sessions:
    - On 2022-10-01, they worked for 8 hours.
    - On 2022-10-06, they worked for 8 hours and 4 minutes.
    - On 2022-10-12, they worked for 4 hours and 1 minute. Note that they worked through midnight.
 - Employee 1 worked a total of 20 hours and 5 minutes across sessions and will not be deducted.
Employee 2:
 - Worked for one session:
    - On 2022-10-29, they worked for 7 hours and 59 minutes. -> This is wrong.
 - Employee 2 did not work their hours and will be deducted.
Employee 3:
 - Did not work any session.
 - Employee 3 did not work their hours and will be deducted.
 ```

Thus, we need to fix the sentence like the below.

```
Employee 2:
 - Worked for one session:
    - On 2022-10-29, they worked for 11 hours and 59 minutes. -> Here is changed part.
 - Employee 2 did not work their hours and will be deducted.
```

Secondly, the answer is missed a test case of the rounded up.

This SQL problem requested to *the number of minutes in each session is rounded up*. Hence, the above time difference of the Employee 2 is 11 hours 59 minutes, not the 11 hours 58 minutes because of the 59 seconds makes round up the minute.

However, when I run the below MySQL query, it passed all the test cases.

```SQL
SELECT Employees.employee_id
FROM Employees
LEFT JOIN (
    SELECT
        employee_id,
        SUM(TIMESTAMPDIFF(second, in_time, out_time)) / (60 * 60) AS worked_hours
    FROM Logs
    GROUP BY employee_id
) AS WorkingLogs
USING (employee_id)
WHERE Employees.needed_hours > IFNULL(WorkingLogs.worked_hours, 0);
```

<img width="1170" alt="스크린샷 2022-09-03 오후 9 53 23" src="https://user-images.githubusercontent.com/63915557/188271324-7b09aa1a-ef01-45a7-b5cb-0013cb5a93d0.png">

For instance, if we change little bit the above example test case like the below.

```
Input: 
Employees table:
+-------------+--------------+
| employee_id | needed_hours |
+-------------+--------------+
| 1           | 20           |
| 2           | 12           |
| 3           | 2            |
+-------------+--------------+
Logs table:
+-------------+---------------------+---------------------+
| employee_id | in_time             | out_time            |
+-------------+---------------------+---------------------+
| 1           | 2022-10-01 09:00:00 | 2022-10-01 17:00:00 |
| 1           | 2022-10-06 09:05:04 | 2022-10-06 17:09:03 |
| 1           | 2022-10-12 23:00:00 | 2022-10-13 03:00:01 |
| 2           | 2022-10-29 12:00:00 | 2022-10-29 23:59:58 |.  -> Here is the changed part.
+-------------+---------------------+---------------------+
```

The output should be like the below because the time difference of Employee 2 is 12 hours during the number of minutes are rounded up.

```
Output: 
+-------------+
| employee_id |
+-------------+
| 3           |
+-------------+
```

However, as I mentioned before, the wrong MySQL query, which doesn't consider the rounding up, passed all the test cases.

Hence, we need to add more rounding up cases.

#### Code you used for Submit/Run operation

```SQL
SELECT Employees.employee_id
FROM Employees
LEFT JOIN (
    SELECT
        employee_id,
        SUM(TIMESTAMPDIFF(second, in_time, out_time)) / (60 * 60) AS worked_hours
    FROM Logs
    GROUP BY employee_id
) AS WorkingLogs
USING (employee_id)
WHERE Employees.needed_hours > IFNULL(WorkingLogs.worked_hours, 0);
```

#### Language used for code

MySQL

#### Expected behavior

To change the description part and to add more test cases.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. 
Fixed the statement issue.
Added the test case.
Your LeetCode account has received 200 LeetCoins as the reward for this feedback. We appreciate your support!
