### ISSUE TITLE
Ambiguous problem statement - 521. Longest Uncommon Subsequence I

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#890]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/longest-uncommon-subsequence-i/

521. Longest Uncommon Subsequence I

When given as "an empty string is a subsequence of any string."
Then how "If the longest uncommon subsequence **doesn't exist**" makes sense?
Because empty string always exists.	

If you agree, please remove/modify to mean different, for the below statement in the question:
"an empty string is a subsequence of any string.".

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Problem statement should be Ambiguous.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
