### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by Tanmay2411** [LeetCode-Feedback/LeetCode-Feedback#8901]
#### Your LeetCode username

Tanmay2411

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

One test case is failing while I am giving custom input, but my code is accepted. Actually 0 to the power 0 is an invalid testcase but still it is running and I think that either the compiler should throw runtime error, or it should be mentioned in question's description that what should be the output.

#### Code you used for Submit/Run operation

```
// Pow(x, n)
class Solution {
public:
    double myPow(double x, int n) {
        if(x == 1)
            return 1;
        
        if(x == 0)
            return 0;
        
        if(n < 0)
            return 1/(myPow(x, (-1) * (n + 1)) * x);
        
        if(n == 1)
            return x;
        
        if(n == 0)
            return double(1);
        
        double x1 = myPow(x, n / 2);
        
        if(n % 2 == 0)           
            return x1 * x1;
        
        else
            return x * x1 * x1;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expect the code to throw a runtime error because 0 to the power 0 is an indeterminable form. But however pow function given in standard math.h library runs it and gives the output 1. My code gave output 0 because I have have declared an if condition.
I think that you should add 0, 0 testcase and write in problem description about its output.
#### Screenshots

![Screenshot (100)](https://user-images.githubusercontent.com/90651075/188281472-1f350c5f-56c1-4d5a-9217-5e9a9c25d495.png)

#### Additional context

NA

**Comment by stormsunshine** [comment]
I think such a test case should be forbidden in test case checker. The cases where x = 0 and n <= 0 should all be forbidden.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test case is rejected as it is not suitable for the problem. We appreciate your support!
