### ISSUE TITLE
Bad problem  - 2396. Strictly Palindromic Number

### ISSUE THREAD

**Issue by Mootbing** [LeetCode-Feedback/LeetCode-Feedback#8902]
#### Your LeetCode username

Mootbing

#### Category of the bug
- [x] Missing Test Cases 

there is not a single test case that it is true for. can you fix this? I can do return False and it works

#### Code you used for Submit/Run operation

class Solution:
    
    def NumberBase(self, n, b):
        if n == 0:
            return [0]
        ret = []
        while n:
            ret.append(int(n % b))
            n //= b
        return ret[::-1]
            
    
    def isStrictlyPalindromic(self, n: int) -> bool:
        return False

#### Language used for code
python

#### Expected behavior
return False just works too instead of my actual code

**Comment by stormsunshine** [comment]
Why do you think there should be a test case that returns true?

**Comment by Mootbing** [comment]
Because it will eliminate just returning False.

**Comment by stormsunshine** [comment]
It can be proven that the answer should be false for any input. If you can't provide a test case where the answer is true, then this issue is meaningless.

**Comment by MrMooooYT** [comment]
I'm intrigued. How would you prove that?

**Comment by stormsunshine** [comment]
If n = 4, then the only possible base is 2, where 4 is "100" in base 2, which is not palindromic.

If n > 4, then consider base n - 2. Since n = 1 * (n - 2) + 2, n is "12" in base n - 2, which is not palindromic.

Therefore, n can never be strictly palindromic.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. Please consider stromsunshine's comment as reference. Thank you!
