### ISSUE TITLE
Missing Test Case - 553. Optimal Division

### ISSUE THREAD

**Issue by UTKARSHSHARMA718** [LeetCode-Feedback/LeetCode-Feedback#8905]
#### Your LeetCode username

Utkarsh_sharma7

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Found a spelling error in the Question description of the question "553. Optimal Division".

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

The spelling should be "input" instead of "iput" 

#### Screenshots

![issue screen shot](https://user-images.githubusercontent.com/86897568/188285711-d9c2faef-b0ab-4b41-ac41-d973aacb03b5.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.We appreciate your support!
