### ISSUE TITLE
Issue on user profile page

### ISSUE THREAD

**Issue by albertininm** [LeetCode-Feedback/LeetCode-Feedback#8906]
#### Your LeetCode username
mourato

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] General website issue

#### Description of the bug
When logged in, I see the error in the screenshot when loading my user profile page:
This makes me see the old version of the profile page *always*. If I want to see the new version of it, I have to go to an anonymous tab, and there, I don't see this error. 

#### Expected behavior
Switch between old and new version of profile issue without any issue.

#### Screenshots
<img width="652" alt="Screenshot 2022-09-03 at 23 39 58" src="https://user-images.githubusercontent.com/19316913/188288516-e5ee0f7d-6184-4e53-872b-051a03b77f12.png">

**Comment by LC-Pam** [comment]
Thanks for reaching out to us! We will keep working on improving the new UI, but for the next few months you can switch back to old UI by doing the following:

1. Please go to your profile page https://leetcode.com/profile/lab and turn on the 'Opt-in for further beta testing' option.

2. Go to any question description page, for example, https://leetcode.com/problems/two-sum/.

3. Click your on your profile picture in the top right corner, and you can then switch to the old version from the drop-down menu.

Please let us know if you have any more questions!
