### ISSUE TITLE
Statement Enhancement - 352. Data Stream as Disjoint Intervals

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#8908]
#### Your LeetCode username

[n.skybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug

- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

`getIntervals()` method asks to return "a list of disjoint intervals `[start_i, end_i]`" but fails to specify the expected order. However, the checker implicitly assumes that the list must be sorted. For example, [the submission below](https://leetcode.com/submissions/detail/790960902/) produces output
`[null,null,[[6,6]],null,[[6,6],[0,0]]]`
on input 
```
["SummaryRanges","addNum","getIntervals","addNum","getIntervals"]
[[],[6],[],[0],[]]
```
and gets WA, because the expected output is
`[null,null,[[6,6]],null,[[0,0],[6,6]]]`.

#### Code you used for Submit/Run operation

```py
class SummaryRanges:
    def __init__(self):
        self.l, self.r = {}, {}

    def addNum(self, val: int) -> None:
        if val - 1 in self.l:
            l = self.l[val - 1]
            if val + 1 in self.r:
                r = self.r[val + 1]
                del self.l[val - 1]
                del self.r[val + 1]
                self.l[r] = l
                self.r[l] = r
            else:
                del self.l[val - 1]
                self.l[val] = l
                self.r[l] = val
        else:
            if val + 1 in self.r:
                r = self.r[val + 1]
                del self.r[val + 1]
                self.l[r] = val
                self.r[val] = r
            else:
                self.l[val] = val
                self.r[val] = val

    def getIntervals(self) -> List[List[int]]:
        return self.r.items()
```

#### Language used for code

Python 3

#### Expected behavior

One of the following:
- [ ] problem statement clearly specifies the order of the returned list;
- [ ] checker does not assume specific order and compares lists as sets.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
