### ISSUE TITLE
Missing Test Case in problem 1566. Detect Pattern of Length M Repeated K or More Times

### ISSUE THREAD

**Issue by xariniov9** [LeetCode-Feedback/LeetCode-Feedback#891]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A major testcase is missing in the problem.

#### Code you used for Submit/Run operation

```
class Solution {
    public:
        bool containsPattern(vector<int>& arr, int m, int k) {

        string s;

        for(int a:arr)
        {
            s+=to_string(a);
        }


        for(int i=0;i<s.size()-m;i++)
        {

            string pattern=s.substr(i,m);
            string check;
            for(int j=0;j<k;j++)
            {
                check+=pattern;
            }
            if(s.find(check)!=std::string::npos)
                return true;

        }

        return false;


    }
};
```

#### Expected behavior

For Testcase
```
[99,9]
1
3
```
Answer should be false but returns true and still gets accepted!

**Comment by lc-pam** [comment]
Hi @xariniov9 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @xariniov9 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
