### ISSUE TITLE
New interface is not working 

### ISSUE THREAD

**Issue by harjotse** [LeetCode-Feedback/LeetCode-Feedback#8912]
#### Your LeetCode username
harjotse

#### Category of the bug
New interface is not working even after clearing all the caches and using different browsers 

#### Description of the bug
New interface is not working even after clearing all the caches and using different browsers 
as soon as i login my id the new interface stops working pls help me out 

#### Screenshots

<img width="1680" alt="Screenshot 2022-09-04 at 12 12 40 PM" src="https://user-images.githubusercontent.com/84695958/188301124-0dedc5bb-e775-4a91-bf93-219b3ff3a0d6.png">

![Uploading Screenshot 2022-09-04 at 12.12.26 PM.png…]()

<img width="1680" alt="Screenshot 2022-09-04 at 12 12 45 PM" src="https://user-images.githubusercontent.com/84695958/188301126-2b68af5f-a7cc-49d9-b17f-02a9e628ca18.png">

**Comment by Ajinkya2000** [comment]
What's wrong with this?

**Comment by harjotse** [comment]
Actually mam when i try to access my profile or any others profile the new
button stops working and the old interface appears but when i see the
anyone's profile with my account not signed in the new interface works
actually the whole problem of reverting back to old interface and the new
interface not working occurs as soon as i login my id i have  attached some
screenshots to show that dark mode option  is not showing in the profile
section and the same mode is visible in problem section ,
everything happens when i sign in even i have tried diff browsers and
clearing the caches also but didn't worked [image: Screenshot 2022-09-04 at
12.12.30 PM.png]

**Comment by Ajinkya2000** [comment]
Can you record a loom video.

**Comment by harjotse** [comment]
I actually haven't used loom before but yes I can share the screen
recording ,as you can see that as soon as I sign in the problem occurs and
when I open the same page on the incognito mode it shows up correctly
because my id was not signed in .

**Comment by LC-Pam** [comment]
Thanks for reaching out to us! We will keep working on improving the new UI, but for the next few months you can switch back to old UI by doing the following:

1. Please go to your profile page https://leetcode.com/profile/lab and turn on the 'Opt-in for further beta testing' option.

2. Go to any question description page, for example, https://leetcode.com/problems/two-sum/.

3. Click your on your profile picture in the top right corner, and you can then switch to the old version from the drop-down menu.

Please let us know if you have any more questions!

**Comment by harjotse** [comment]
Sir/Madam i have tried to opt out off the beta testing option and its not
allowing me to do so it says " user don't have permissions to change" and
by default the beta testing is off , i tried the second method as well and
i am not getting any options to change to old version please help me out
