### ISSUE TITLE
A misjudge of Question #987 Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by Rock3Yu** [LeetCode-Feedback/LeetCode-Feedback#8913]
#### Category of the bug
- [x] Question 987 Vertical Order Traversal of a Binary Tree
- [x] Solution
- [x] Language Java
- [x] Missing Test Cases 1/32

#### Description of the bug
The runing result in my local computer is right, but online judge is confusing. I think online judge may have some conflict with my language edtion (java 1.8) or some thing else.

#### Code you used for Submit/Run operation
```
class Solution {
    static List<List<Integer>> minus = new ArrayList<>(); // -1, -2, ...
    static List<List<Integer>> plus0 = new ArrayList<>(); // 0, 1, 2, ...

    public List<List<Integer>> verticalTraversal(TreeNode root) {
        minus.add(new ArrayList<>());

        dfs(root, 0, 0);

        for (int i = 1; i < minus.size(); i++) plus0.add(0, minus.get(i));

        for (List<Integer> integers : plus0) integers.sort(Comparator.naturalOrder());

        return plus0;
    }

    public void dfs(TreeNode root, int row, int col) {
        if (col >= 0) {
            if (plus0.size() < col + 1) plus0.add(new ArrayList<>());
            plus0.get(col).add(root.val);
        } else {
            if (minus.size() < -col + 1) minus.add(new ArrayList<>());
            minus.get(-col).add(root.val);
        }

        if (root.left != null) dfs(root.left, row + 1, col - 1);

        if (root.right != null) dfs(root.right, row + 1, col + 1);
    }
}
```

#### Language used for code
Java

#### Expected behavior
Test case 1/32 
In local running I will get the right answer.

#### Screenshots
![image](https://user-images.githubusercontent.com/96281765/188303731-4c4ab129-038e-46e9-a916-7ab4e629d478.png)
in the webs
![image](https://user-images.githubusercontent.com/96281765/188303605-ea4be15c-0558-4be4-af95-1b52814a96b6.png)
local

#### Additional context
If I am right, PLZ help me to rejudge and hit the everyday problem task.

**Comment by yumkam** [comment]
I'd guess your problem is `static ... minus` and `static ... plus0`. You should reset them or, better, use local objects and pass them into `dfs()` as parameters, otherwise they will collect results from several runs.

**Comment by Rock3Yu** [comment]
@yumkam Yeah, I found the mistake you mentioned. Think a lot!
