### ISSUE TITLE
A misjudge on test case 3/21 for "Find Median From Data Stream"

### ISSUE THREAD

**Issue by xjchen1023** [LeetCode-Feedback/LeetCode-Feedback#8914]
#### Your LeetCode username
jessicachen3201

#### Category of the bug
- [ ] Question: 295. Find Median from Data Stream
- [ ] Language: Python
- [ ] Missing Test Cases: 3/21

#### Description of the bug
The result of test case in Console has correct output, yet the system shows my output is wrong when I submitted my code.

#### Code you used for Submit/Run operation

```
class MedianFinder:
    
    _median = None
    max_l = []
    min_r = []

    def __init__(self):
        heapq.heapify(self.max_l)
        heapq.heapify(self.min_r)

    def addNum(self, num: int) -> None:
        # first time:
        if self._median is None:
            self._median = num
        elif num >= self._median:
            heapq.heappush(self.min_r, num)
            # readjust
            if len(self.min_r) - len(self.max_l) > 1:
                heapq.heappush(self.max_l, self._median * -1)
                self._median = heapq.heappop(self.min_r)
        else:
            heapq.heappush(self.max_l, num * -1)
            # readjust
            if len(self.max_l) - len(self.min_r) > 1:
                heapq.heappush(self.min_r, _median)
                self._median = heapq.heappop(self.max_l) * -1


    def findMedian(self) -> float:
        # same size
        if len(self.max_l) == len(self.min_r):
            return self._median
        # need to take half
        elif len(self.max_l) > len(self.min_r):
            other_med = heapq.heappop(self.max_l)
            # replace in:
            heapq.push(self.max_l, other_med)
            # get opposite, since negative
            other_med *= -1
            return (other_med + self._median) / 2
        else:
            other_med = heapq.heappop(self.min_r)
                # replace in:
            heapq.heappush(self.min_r, other_med)
            return (other_med + self._median) / 2
        


# Your MedianFinder object will be instantiated and called as such:
# obj = MedianFinder()
# obj.addNum(num)
# param_2 = obj.findMedian()
```

#### Language used for code

Python

#### Expected behavior

The system shows I have the wrong output for Test Case 3/21, yet the console shows it's correct.

#### Screenshots

![Screen Shot 2022-09-04 at 4 14 28 AM](https://user-images.githubusercontent.com/97071807/188304138-e4a8367f-fa69-4c34-86a7-5f8be02302ca.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
