### ISSUE TITLE
Missing Test Case - 912. Sort an Array

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#8915]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution is getting TLE on this test case:
[Missing Test Case - 912.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9484375/Missing.Test.Case.-.912.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    template< class IterT >
    void quick_sort(IterT first, IterT last) {
        if (first == last)
            return;
        
        IterT candidates[] = { last - 1, first, first + (last - first) / 2};
        std::sort(begin(candidates), end(candidates), [](auto a, auto b) { return *a < *b; });
        std::iter_swap(last - 1, candidates[1]);
        
        const auto pivot = *(last - 1);
        auto bound = std::partition(first, last, [&pivot](const auto& i) { return i < pivot; });
        std::iter_swap(bound, last - 1);

        quick_sort(first, bound);
        quick_sort(bound + 1, last);
    }
    
    vector<int> sortArray(vector<int>& nums) {
        quick_sort(std::begin(nums), std::end(nums));
        return nums;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This code is passing all tests and getting Accepted. But it should get TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
