### ISSUE TITLE
Improvement on explanation: Running Sum of 1D Array

### ISSUE THREAD

**Issue by dron-dronych** [LeetCode-Feedback/LeetCode-Feedback#8918]
#### Your LeetCode username
dron-dronych

#### Category of the bug
- [x] Improvement
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The video with the explanation of the Running Sum of 1D Array problem doesnt take into account the varying opinions on whether to count the output in space complexity or not. It would be good to clearly state the definition of space complexity as there isnt a general consensus on whether output should be included or not (consider algorithms producing output vs those modifying data structures in-place).

This is especially useful as the video provides two approaches where in one he would produce a separate output while in the second an input data structure would be modified in place. Hence, it is easy to get into a trap of space complexity O(n) in the first case vs O(1) in the latter solution.
https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/692/challenge-problems/4422/

#### Expected behavior
Definition of what space complexity is prior to stating two different versions of the solution.

#### Screenshots
1st solution with output proportionate to input size n
![Screenshot from 2022-09-04 12-52-55](https://user-images.githubusercontent.com/13108622/188309787-f2302527-5f68-4d37-9727-5952a8b5c342.png)

2nd solution with no extra space allocated
![Screenshot from 2022-09-04 12-53-18](https://user-images.githubusercontent.com/13108622/188309792-861dea0a-e9f8-43ec-bee7-7757ea23f60d.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We usually ignore the space used for the returned result by convention when it comes to the term "space complexity". We appreciate your support!
