### ISSUE TITLE
Misjudge of the question - #987. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by SKS-WAR** [LeetCode-Feedback/LeetCode-Feedback#8919]
#### Your LeetCode username
sahoosudeep2010

#### Category of the bug
- [ ] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question: [https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree](https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree)

#### Code you used for Submit/Run operation

```
var verticalTraversal = function(root) {
    let hm = {}
    calc(root,hm,0);
    let ret = []
    Object.keys(hm).sort((a,b) => a -b).map(ele => ret.push(hm[ele]));
    return ret;
    
};

var calc = (root,obj,level) => {
    if(!root) return;
    if(!obj[level]){
        obj[level] = []
    }
    obj[level].push(root.val);
    calc(root.left,obj,level-1);
    calc(root.right,obj,level+1);

}
```

#### Language used for code

JavaScript

#### Expected behavior

Bug: Teastcase [1,2,3,4,6,5,7] is failing whereas I am getting the required output when I do run code.
Expected Output: [[4],[2],[1,5,6],[3],[7]]
While using 'Run Code' output : [[4],[2],[1,5,6],[3],[7]]
While submitting the code output: [[4],[2],[1,6,5],[3],[7]]

#### Screenshots

![Screenshot (12)](https://user-images.githubusercontent.com/39806889/188318396-6a0f2bf1-316f-443f-bd91-c08c0daf42a8.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
