### ISSUE TITLE
Missing testcase in 1568. Minimum Number of Days to Disconnect Island

### ISSUE THREAD

**Issue by ssanjeev2424** [LeetCode-Feedback/LeetCode-Feedback#892]
ssanjeev2424

#### Category of the bug - Test case missing
- [1] Question

#### Description of the bug

Crucial test case missing

#### Code you used for Submit/Run operation

```
//1568. Minimum Number of Days to Disconnect Island
class Solution {
public:
    int minDays(vector<vector<int>>& grid) {
        m = grid.size(), n = grid[0].size(), islands = 0, ones = 0;
        memset(visited, 0, sizeof(visited));
        
        for(int i=0; i<m; i++) for(int j=0; j<n; j++) {    // finding out #islands
            if(!visited[i][j] && grid[i][j] == 1)
                dfs(i, j, grid), islands++;
            if(grid[i][j] == 1) ones++;
        }
        
        if(islands != 1) return 0;     // islands = #Connected Components
        
        if(m == 1 || n == 1 || ones <= 2) return (ones == 2 ? 2: 1);   // #islands = 1
        
        for(int i=0; i<m; i++) for(int j=0; j<n; j++) if(grid[i][j] == 1) {
            int x = i, y = j; grid[i][j] = 0;
            
            memset(visited, 0, sizeof(visited));
            islands = 0;
            
             for(int i=0; i<m; i++) for(int j=0; j<n; j++) {     // finding out #islands
                if(!visited[i][j] && grid[i][j] == 1)
                    dfs(i, j, grid), islands++;
            }           
            
            if(islands == 2) return 1;    // we were able to disconnect the islands
            
            grid[x][y] = 1;
        }
        
        return 2;
    }
    
    void dfs(int i, int j, vector<vector<int>> &g) {    // visits all the 1s of 1 island, marks them visited
        visited[i][j] = 1; 
        
        if(i && !visited[i-1][j] && g[i-1][j] == 1) dfs(i-1, j, g);
        if(j && !visited[i][j-1] && g[i][j-1] == 1) dfs(i, j-1, g);
        if(i < m - 1 && !visited[i+1][j] && g[i+1][j] == 1) dfs(i+1, j, g);
        if(j < n - 1 && !visited[i][j+1] && g[i][j+1] == 1) dfs(i, j+1, g);
    }
    
private:
    int m, n, islands, ones, visited[35][35];
};
```

#### Language used for code

C++

#### Expected behavior

With "[[1,0,0],[1,1,0],[1,0,0]]" input ,
expected behaviour is '1', but my code returns '2' and still gets AC

#### Screenshots

![image](https://user-images.githubusercontent.com/31368706/91651811-e1b27700-eaae-11ea-8707-eab7bb290f2c.png)
![image](https://user-images.githubusercontent.com/31368706/91651816-ef67fc80-eaae-11ea-8afe-b61ae5bd0018.png)

#### Additional context

I just checked whether after deletion of any one particular land, it will create 2 islands or not.
But it can also create more than 2 islands after we delete one particular land cell.

**Comment by lc-pam** [comment]
Hi @ssanjeev2424 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ssanjeev2424** [comment]
@lc-pam ok thanks !!

**Comment by lc-pam** [comment]
Hi @ssanjeev2424 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
