### ISSUE TITLE
Missing Test Case - 2398. Maximum Number of Robots Within Budget

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8920]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [2398. Maximum Number of Robots Within Budget](https://leetcode.com/problems/maximum-number-of-robots-within-budget/), a solution that can get accepted fails on a specific test case.

```
[250,250,250,250,250,250,250,250,250,250,1,1,1,1,1,1,1,1,1,1]
[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
280
```

#### Code you used for Submit/Run operation
```C++
class Solution {
public:
    int maximumRobots(vector<int>& chargeTimes, vector<int>& runningCosts, long long budget) {
        int n = chargeTimes.size();
        int ans = 0;
        int l = 0;
        long long cost = 0;
        multiset<int> s;
        for (int r = 0; r < n; r++) {
            s.insert(chargeTimes[r]);
            cost += runningCosts[r];
            while (!s.empty() and 1LL * cost * (r - l + 1) + *s.rbegin() > budget) {
                s.erase(chargeTimes[l]);
                cost -= runningCosts[l];
                l++;
            }
            ans = max(ans, r - l + 1);
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Add the test case so that the code above will get Wrong Answer when submitted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
