### ISSUE TITLE
Dart lang measurements 

### ISSUE THREAD

**Issue by II11II** [LeetCode-Feedback/LeetCode-Feedback#8923]
#### Your LeetCode username

II11II

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

How ram memory consumption is measured in dart lang?
How performance is measured?
What compiler is used for dart in LeetCode?(DVM, dart2js,native,jit,aot)
Is it running in debug, profile or release mode?

It seems the submission results for Dart is quite wrong 
P.s. I tried to measure the same code in my laptop 
that I submitted LeetCode. I see it 10 times differs than LeetCode measurements
My measurements:
87 ms 15mb ram memory consumption
LEETCODE measurements:
996 ms 157mb ram memory consumption

**Comment by aospiridonov** [comment]
They use `dart run` then compiler is DVM.
I think the slowdown is associated with use `stdin.readLineSync()` for input parameters and `File(...).writeAsStringSync(...)` and `jsonEncode` (perhaps even additional manipulations with strings for the encoding result) for each output parameters. 
The `writeAsStringSync`  opens the file, writes the string in the given encoding, and closes the file. 
And possible used `flush: true`.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
