### ISSUE TITLE
LCP 46. 志愿者调配 填入示例

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#8927]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 填入示例

**描述**
未自动填入示例2

**期望行为**
允许自动填入示例2：
[4,13,4,3,8]
54
[[0,3],[1,3],[4,3],[2,3],[2,5]]
[[1,1],[3,3],[2,5],[1,0]]

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/25954059/188349634-e12a163e-be49-4f32-81c5-6a71572c7210.png)

**额外的上下文**
[题目链接](https://leetcode.cn/problems/05ZEDJ/)

**Comment by BrambleWave** [comment]
感谢您的反馈，此问题暂时无法解决。
我们会尽快思考可实行的替代方案。
