### ISSUE TITLE
Missing Test Case - 1268. Search Suggestions System

### ISSUE THREAD

**Issue by HandsomeCoder** [LeetCode-Feedback/LeetCode-Feedback#8928]
#### Your LeetCode username
Handsome-Coder

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the test case
There is a missing test case. let's take only one product and the search word is in such a way that product and searchWord prefixes are the same but have different suffixes.  

For Example: `products: ["banner"], searchWord: "bags"`

In this case "ba" of products: ["**ba**nner"], searchWord: "**ba**gs" is same 
Output should be: `[["banner"],["banner"],[],[]]`

But I have modified the code where I am not handling this test case and blinding checking whether if `product[0] == searchWord` then returning the result as per the output which either list with the product or empty list and this code ran successfully without failing any test case

#### Code you used for Submit/Run operation

```
class Trie:
    def __init__(self, words=None):
        self.children = {}
        self.is_word = False
        self.seq_arr = []

        if words:
            for word in words:
                self.insert(word)

    def get_seq_arr(self):
        if not self.seq_arr:
            self.seq_arr = sorted(self.children.keys())
        
        return self.seq_arr

    def insert(self, word):
        itr = self
        for wch in word:
            if wch not in itr.children:
                itr.children[wch] = Trie()
            itr = itr.children[wch]
        itr.is_word = True

    def get_words(self, itr, result, rln, current):
        if itr.is_word:
            result.append("".join(current))
            if len(result) == rln:
                return

        for sch in itr.get_seq_arr():
            if sch in itr.children:
                current.append(sch)
                self.get_words(itr.children[sch], result, rln, current)
                current.pop()
                if len(result) == rln:
                    return

    def start_with(self, prefix):
        itr = self
        for wch in prefix:
            if wch not in itr.children:
                itr = None
                break
            itr = itr.children[wch]

        if itr == None:
            return []

        result = []
        self.get_words(itr, result, 3, deque(list(prefix)))
        return result


class Solution:
    def suggestedProducts(self, products: List[str], searchWord: str) -> List[List[str]]:
        pln = len(products)
        sln = len(searchWord)
        trie = Trie(products)

        result = []
        if pln == 1:
            return [products if searchWord == products[0] else []] * sln 
        
        for idx in range(len(searchWord)):
            result.append(trie.start_with(searchWord[0:idx+1]))

        return result
```

#### Language used for code

Python3

#### Expected behaviour

The above code should fail in the above-mentioned test case

#### Screenshots

![image](https://user-images.githubusercontent.com/18287082/188353337-1e3e097b-e6ff-4034-8880-b416d1240be9.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
