### ISSUE TITLE
152. Maximum Product Subarray - Products are the result of multiplication, not single numbers

### ISSUE THREAD

**Issue by kyruzic** [LeetCode-Feedback/LeetCode-Feedback#8929]
#### Your LeetCode username
????

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Products are the result of multiplication not single numbers. Given the case [0,1] the answer is 0 based on the information given in the description. Yes 1 is a subarray of [0,1] but its not the result of multiplication. IMO the question should be reformulated so that subarrays have a minimum length of 2 since that's the only way they have a product, but if that's not how you guys want to go about it then at least add to the description that subarrays of length one are valid and add the test case [0,1] with the answer 1 to the description as well.

#### Additional context
None of the other fields are really relevant here so I didn't fill them out.

**Comment by stormsunshine** [comment]
If a subarray has length 1, then the product is the single element in the subarray itself. Why do you think a subarray must have length at least 2?

**Comment by kyruzic** [comment]
Because of the definition of a product. A product is a mathematical term meaning "The result of multiplication". Really I just think you should add the example I suggested to the description. Because on first reading I didn't assume it could be one number if the sequence included multiple numbers.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The "sum" of a subarray of size 1 is the value of the individual element, We are not actually performing any addition operations here.
Similarly the "product" of a subarray of size 1 should be the value of the individual element. The statement is clear. We appreciate your support!
