### ISSUE TITLE
Confusion in description for problem: pancake sorting

### ISSUE THREAD

**Issue by balias** [LeetCode-Feedback/LeetCode-Feedback#893]
In question https://leetcode.com/problems/pancake-sorting/ the answer expected is in 1 based indexing for k but in the description it is given 0 <= k < A.length. It would be great if this could be modified appropriately to avoid confusion.
Thanks

**Comment by lc-pam** [comment]
Hi @balias 
Thank you for reaching out to us. The team has acknowledged the issue and updated the problem.
