### ISSUE TITLE
Non-Java-style tree node definition comment - 429. N-ary Tree Level Order Traversal

### ISSUE THREAD

**Issue by m-dzianishchyts** [LeetCode-Feedback/LeetCode-Feedback#8930]
#### Your LeetCode username
m-dzianishchyts

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The comment on the definition of a tree node in this problem is out of style
from the rest of similar problems on LeetCode.
I suggest to fix it so that the style remains the same.

#### Code you used for Submit/Run operation

```java
/*
// Definition for a Node.
class Node {
    public int val;
    public List<Node> children;

    public Node() {}

    public Node(int _val) {
        val = _val;
    }

    public Node(int _val, List<Node> _children) {
        val = _val;
        children = _children;
    }
};
*/
```

#### Language used for code
Java

#### Expected behavior

```java
/**
 * Definition for a n-ary tree node.
 * public class Node {
 *     int val;
 *     List<Node> children;
 *     Node() {}
 *     Node(int val) { this.val = val; }
 *     Node(int val, List<Node> children) {
 *         this.val = val;
 *         this.children = children;
 *     }
 * }
 */
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
