### ISSUE TITLE
Problem 987 Test Case Showing Unexpected Answer

### ISSUE THREAD

**Issue by JalalSinno** [LeetCode-Feedback/LeetCode-Feedback#8931]
#### Your LeetCode username
Jalal123 

#### Category of the bug
- [ 987] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Expected output contradicts the instructions in example 3 that says the list "should be ordered by its values", yet the expected answer to input [3,1,4,0,2,2] is [[0],[1],[3,2,2],[4]] and my Answer is
[[0],[1],[2,2,3],[4]]

#### Code you used for Submit/Run operation
'''from operator import itemgetter
class Solution:
    def verticalTraversal(self, root: Optional[TreeNode]) -> List[List[int]]:
        rowCol = [0,0]
        groups=[]
        def travel(root, rowCol, groups):
            groups.append([rowCol[1], root.val])
            if not root.right is None:
                travel(root.right, [rowCol[0]+1, rowCol[1]+1],groups)
            if not root.left is None:
                travel(root.left, [rowCol[0]+1,rowCol[1]-1],groups)
        travel(root, rowCol, groups)
        print(groups)
        groups = sorted(groups)
        i = 0
        output = []
        g = []
        while i < len(groups):
            if not i == 0:
                if groups[i-1][0]==groups[i][0]:
                    g.append(groups[i][1])
                else:
                    output.append(g)
                    g = []
                    g.append(groups[i][1])
            else:
                g.append(groups[0][1])
            if i+1 == len(groups):
                output.append(g)
            i+=1
        print(groups)
        return output '''

#### Language used for code
Python3

#### Expected behavior
 The input is [3,1,4,0,2,2]. The expected answer is [[0],[1],[3,2,2],[4]] and my Answer is
[[0],[1],[2,2,3],[4]]. The example test cases specifically told us to number the answers in increasing order, which is why test case two and three show the same output. However, this test case is contradicting the instructions, as 3 is greater than 2 in the third list.

![image](https://user-images.githubusercontent.com/16967269/188412621-0c05f2d7-de0b-460c-a26a-61af1c15557d.png)
![image](https://user-images.githubusercontent.com/16967269/188412649-ada90bd4-bfbe-4a19-8238-de67a0ac73c8.png)
 Notice how the soultions are the same, this is because each list is ordered from least to greatest, which is not followed in the test case [3,1,4,0,2,2]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by JalalSinno** [comment]
How is this fixed? The contradiction is still there. Why is the answer [3,2,2] instead of [2,2,3] when it specifically states "This case is the exact same as example 2, but with nodes 5 and 6 swapped.
Note that the solution remains the same since 5 and 6 are in the same location and should be ordered by their values."
