### ISSUE TITLE
缺少测试用例 652. 寻找重复的子树

### ISSUE THREAD

**Issue by hulihuwai** [LeetCode-Feedback/LeetCode-Feedback#8932]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
沪里户外

**Bug 类型**
缺少测试用例

**描述**
用例情况覆盖不足, 缺少退化为链表的用例
构造该情况如下, 部分解法将超时或者OOM(如官解)

**你使用的语言**
Java

**贡献新用例**
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9489105/1.txt)

**期望行为**
n方应该无法通过该题

**屏幕截图**
<img width="412" alt="截屏2022-09-05 18 44 45" src="https://user-images.githubusercontent.com/68989763/188431276-fe45b9fa-9d46-4423-a7c9-673b49b6b148.png">

**额外的上下文**
n方应该无法通过该题

**Comment by BrambleWave** [comment]
不予采纳，这道题的门槛没那么高
