### ISSUE TITLE
缺少测试用例 652. 寻找重复的子树

### ISSUE THREAD

**Issue by hulihuwai** [LeetCode-Feedback/LeetCode-Feedback#8933]
你的 LeetCode 用户名
沪里户外

Bug 类型
缺少测试用例

描述
用例情况覆盖不足, 缺少退化为链表的用例
构造该情况如下, 部分解法将超时或者OOM(如官解)

你使用的语言
Java

贡献新用例
[newCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9489177/newCase.txt)

期望行为
n方应该无法通过该题, n方构造, 要么超时要么超内存

屏幕截图
![image](https://user-images.githubusercontent.com/68989763/188434416-77275647-1fbe-4aa3-83f8-18c0b3881ccc.png)

额外的上下文
[题目链接](https://leetcode.cn/problems/find-duplicate-subtrees/)

**Comment by BrambleWave** [comment]
不予采纳，这道题的门槛没那么高
