### ISSUE TITLE
Question is misleading - 220. Contains Duplicate III

### ISSUE THREAD

**Issue by nandiniraja348** [LeetCode-Feedback/LeetCode-Feedback#8935]
#### Your LeetCode username

nandiniraja348

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Question

#### Description of the bug

Problem: 220. Contains Duplicate III
Description: The problem clearly states that `two distinct indices i and j`. But I find in the constraints `1 <= nums.length <= 2 * 104`
It should have been `2 <= nums.length <= 2 * 104`

<img width="765" alt="Screenshot 2022-09-05 at 10 21 28 PM" src="https://user-images.githubusercontent.com/47417419/188491910-8efb7e84-6b81-4f34-b1d4-e6b20a2ec48b.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've removed two test cases and changed the constraints. We appreciate your support!
