### ISSUE TITLE
Missing Test Case - 487. Max Consecutive Ones II

### ISSUE THREAD

**Issue by Islam-Hasan** [LeetCode-Feedback/LeetCode-Feedback#8937]
#### Your LeetCode username

Islam_Hassan

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

The test cases are missing a test case where there are two or more consecutive zeroes at the end after a series of ones e.g. `[1,1,1,0,0]`.
This will cause a solution such as the following one to succeed while it shouldn't, please see the code below.

#### Code you used for Submit/Run operation

```
class Solution {
    public int findMaxConsecutiveOnes(int[] nums) {
        int max = 0;
        int current = 0;
        int currentWithFlippedZero = 0;
        for(int i = 0; i < nums.length; i++) {
            if(nums[i] == 1) {
                ++current;
                ++currentWithFlippedZero;
            } else if((i <  nums.length - 1 && nums[i + 1] == 1) || 
                       i == nums.length - 1) {
                max = Math.max(currentWithFlippedZero, max);
                currentWithFlippedZero = current + 1;
                current = 0;
            } else {
                int currentMax = Math.max(current, currentWithFlippedZero);
                max = Math.max(currentMax, max);
                currentWithFlippedZero = 0;
                current = 0;
            }
        }
        int currentMax = Math.max(current, currentWithFlippedZero);
        max = Math.max(currentMax, max) == 0? 1 : Math.max(currentMax, max);
        return max;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution was accepted while it shouldn't because for the following test case for example `[1,1,1,0,0]`, It gives a result of `3` while the correct result is in fact `4`.

#### Screenshots

![image](https://user-images.githubusercontent.com/33632489/188498288-af188262-cfc7-4f1a-b00c-650ed52542ad.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
