### ISSUE TITLE
Code form Solution Article TLEs - 739. Daily Temperatures

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#8939]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug

- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Code featured in Approach 1: "Monotonic Stack" of the [solution article](https://leetcode.com/problems/daily-temperatures/solution/) gets TLE when [submitted](https://leetcode.com/submissions/detail/792637119/).

#### Code you used for Submit/Run operation

```py
class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        n = len(temperatures)
        answer = [0] * n
        stack = []
        
        for curr_day, curr_temp in enumerate(temperatures):
            # Pop until the current day's temperature is not
            # warmer than the temperature at the top of the stack
            while stack and temperatures[stack[-1]] < curr_temp:
                prev_day = stack.pop()
                answer[prev_day] = curr_day - prev_day
            stack.append(curr_day)
        
        return answer
```

#### Language used for code

Python 3

#### Expected behavior

Code from the solution article does not TLE. Either:
- this code should TLE and the solution article must be rewritten accordingly;
- this code should not TLE and the time limit must be adjusted accordingly.

#### Additional context

This behavior is inconsistent, meaning that sometimes it will TLE and sometimes it won't. Clearly, your runtime measurement accuracy must be improved given that sometimes the execution time is [less than half of TL](https://leetcode.com/submissions/detail/792641693/), and sometimes it is more than TL.

**Comment by LC-Pam** [comment]
Thank you for your time. 
The code received Accepted when we test it.
https://leetcode.com/problems/daily-temperatures/submissions/793199789/
We appreciate your support!

**Comment by nskybytskyi** [comment]
@LC-Pam I suspect you didn't read the additional context section. As I said, this code has inconsistent behavior. I strongly believe that this is NOT okay

**Comment by nskybytskyi** [comment]
Like imagine this was the case for some contest problem, then some people will get AC and some TLE (and hence penalties) with the same code. This is clearly NOT okay!
