### ISSUE TITLE
strrch执行程序和提交答案的查找结果不一致，

### ISSUE THREAD

**Issue by yumeiyong** [LeetCode-Feedback/LeetCode-Feedback#894]
** Bug 类型**
- [ ] 题目 58. 最后一个单词的长度
- [ ] 题解
- [ ] 编程语言 c

**描述**
strrchr("a", ' ')在执行程序时返回空，在提交程序时返回非空。
strrchr("a", ' ')应该返回空，但是再提交时返回非空

**你使用的语言**
C

**你提交或者运行的代码**
```
int lengthOfLastWord(char * s){
    int len = strlen(s);
    char *idx = strrchr(s, ' ');
    printf("idx=%p\n", idx);
    if (idx == NULL) {
        return len;
    }
    if (idx == (s + len - 1)) {
        return 0;
    }

    return s + len - 1 - idx;
}
```

**期望行为**
strrchr("a", ' ')应该返回空，但是再提交时返回非空

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/36755988/91662040-6edae780-eb12-11ea-925d-edd09e6ac3d0.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/ 。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦～

**Comment by yumeiyong** [comment]
strrchr("a", ' ')应该返回空，但是提交时，返回非空。
希望仔细读问题，不要为了关问题，而关问题

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，请仔细阅读理解题目意思，看清楚是否有空格。

**Comment by yumeiyong** [comment]
ok, 提交时确实多了1个空格
