### ISSUE TITLE
Missing Test Case - 235. Lowest Common Ancestor of a Binary Search Tree

### ISSUE THREAD

**Issue by muller2333** [LeetCode-Feedback/LeetCode-Feedback#8941]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[0,-1000000000,1000000000]
-1000000000
1000000000

#### Code you used for Submit/Run operation

```
class Solution {
    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {
        int prod = (p.val - root.val) * (q.val - root.val);
        if (prod <= 0) {
            return root;
        } else {
            if (p.val > root.val) {
                return lowestCommonAncestor(root.right, p, q);
            } else {
                return lowestCommonAncestor(root.left, p, q);
            }
        }
    }
}
```

#### Language used for code

Java

#### Screenshots

![2022-09-06](https://user-images.githubusercontent.com/25950952/188564027-f516bf10-d655-42ef-ad44-0ddf32abd75e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
