### ISSUE TITLE
Loop Recall

### ISSUE THREAD

**Issue by shynnie** [LeetCode-Feedback/LeetCode-Feedback#8943]
#### Your LeetCode username

6aug2012

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I tried to solve problem 844. Backspace String Compare and just realise loop recall 2 times every time I run code.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean searchMatrix(int[][] matrix, int target) {
        int a = 5;
        for (int j = 0; j < a; j++) {
			System.out.println(j);
		}
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Loop just call 1 time

#### Screenshots

![aaaa](https://user-images.githubusercontent.com/22925878/188583448-e8413b31-5681-4162-86a8-c16aeb33e140.png)
![bbb](https://user-images.githubusercontent.com/22925878/188583998-eecd85db-ed31-4608-aafc-f2628ad9e7f3.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
