### ISSUE TITLE
814. Binary Tree Pruning. Missing Test Case

### ISSUE THREAD

**Issue by utkarshneema** [LeetCode-Feedback/LeetCode-Feedback#8945]
#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug
An accepted solution failed the following test case:-
Test case: [0]
Output: [0]
Expected: []

#### Code you used for Submit/Run operation

```
// 814. Binary Tree Pruning
class Solution {
    public TreeNode pruneTree(TreeNode root) {
        if(root.left == null && root.right == null){
            return root;
        }
        root = helper(root);
        return root;   
    }
    
    public TreeNode helper(TreeNode root){
        if(root.left == null && root.right == null){
            if(root.val == 1)
                return root;
            return null;
        }
        if(root.left != null){
            root.left = helper(root.left);
        }
        if(root.right != null){
            root.right = helper(root.right);
        }
        if(root.left != null || root.right != null || root.val == 1){
            return root;
        }
        return null;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Expected Output: [ ]

#### Screenshots

![image](https://user-images.githubusercontent.com/94834570/188612352-14356631-4256-49a5-b747-c5bdf7c71615.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by utkarshneema** [comment]
Thank you for your response.
I am Utkarsh Neema and my LeetCode username is : ut123

**Comment by LC-Pam** [comment]
Your LeetCode account has received 100 LeetCoins as the reward for this feedback.
