### ISSUE TITLE
876. 链表的中间结点

### ISSUE THREAD

**Issue by SilentFlute** [LeetCode-Feedback/LeetCode-Feedback#8946]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
```
_音魂不散_
```

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
在谷歌浏览器控制台和nodejs中运行是正常的, 但是在网站中就报错

**你使用的语言**
js

**你提交或者运行的代码**
```js
const middleNode = (head) => {
  const length = head.length;
  let mn = 0;
  if(length % 2 === 0) {
    mn = head[length / 2];
  }else{
    mn = head[Math.floor(length / 2)];
  }

  return head.slice(mn - 1);
};
```

**期望行为**
通过

**屏幕截图**
![image](https://user-images.githubusercontent.com/28900312/188640401-a8279e2e-a387-413e-946e-6c8bb8e92d76.png)

**额外的上下文**
无

**Comment by BrambleWave** [comment]
这题的输入是链表，不是数组
