### ISSUE TITLE
468. Validate IP Address example is wrong

### ISSUE THREAD

**Issue by wilmerkrisp** [LeetCode-Feedback/LeetCode-Feedback#8947]
example doesnot work

from ipaddress import ip_address, IPv6Address
class Solution:
    def validIPAddress(self, IP: str) -> str:
        try:
            return "IPv6" if type(ip_address(IP)) is IPv6Address else "IPv4"
        except ValueError:
            return "Neither"

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted this issue to the team. We appreciate your support!
