### ISSUE TITLE
Head val is not checked - 2. Add Two Numbers

### ISSUE THREAD

**Issue by ozselgin** [LeetCode-Feedback/LeetCode-Feedback#8948]
#### Your LeetCode username

ozselgin

#### Description of the bug
The system accepts solutions which has head val as 0. Sample solution is also wrong. Because head val is 0.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
        ListNode dummyHead = new ListNode(0);
        ListNode curr = dummyHead;
        int carry = 0;
        while (l1 != null || l2 != null || carry != 0) {
            int x = (l1 != null) ? l1.val : 0;
            int y = (l2 != null) ? l2.val : 0;
            int sum = carry + x + y;
            carry = sum / 10;
            curr.next = new ListNode(sum % 10);
            curr = curr.next;
            if (l1 != null)
                l1 = l1.next;
            if (l2 != null)
                l2 = l2.next;
        }
        System.out.println("Head value: " + dummyHead.val);
        return dummyHead.next;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Head val must be the calculated value of the sum operation

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The first element of the list is not zero, you can actually add a test case such as [0, 1] in custom test cases. We appreciate your support!
