### ISSUE TITLE
Missing Test Case - 150. Evaluate Reverse Polish Notation

### ISSUE THREAD

**Issue by raditya1710** [LeetCode-Feedback/LeetCode-Feedback#8949]
#### Your LeetCode username
alfonsus_raditya

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For the input: `["-128","-128","*","-128", "*", "-128", "*", "8", "*", "-1", "*"]`, The result still in the integer range (-2147483648), but it shows an invalid testcase.

For comparison, `["-128","-128","*","-128", "*", "-128", "*", "-1", "*", "8", "*"]` correctly results in -2147483648.

#### Code you used for Submit/Run operation

```
typedef long long LL;
class Solution {
public:
    int evalRPN(vector<string>& tokens) {
        stack<LL> st;
        for(string& token: tokens){
            if(token == "+" || token == "-" || token == "/" || token == "*"){
                LL sec = st.top(); st.pop();
                LL fir = st.top(); st.pop();
                if(token == "+") st.push(fir + sec);
                else if(token == "-") st.push(fir - sec);
                else if(token == "/") st.push(fir / sec);
                else if(token == "*") st.push(fir * sec);
            }
            else{
                LL now = stoi(token);
                st.push(now);
            }
        }
        return int(st.top());
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the given input, it should not has an invalid testcase, because the problem statement does not show that the intermediate result is still in the integer range, only in the last result that should be in integer.

#### Screenshots

![Screenshot from 2022-09-07 00-44-44](https://user-images.githubusercontent.com/14028227/188704543-0f113e8e-d31d-4285-abb9-d26955f032a6.png)
![Screenshot from 2022-09-07 00-49-14](https://user-images.githubusercontent.com/14028227/188704739-b6ec5622-b1a0-4b83-87ce-427aa795e174.png)
![Screenshot from 2022-09-07 00-49-21](https://user-images.githubusercontent.com/14028227/188704735-382d63bb-ed83-4a5e-833f-e443b4910d2f.png)

**Comment by stormsunshine** [comment]
I think the problem description should mention that all intermediate results will be in 32-bit integer range.

**Comment by raditya1710** [comment]
I think so that it is better that the problem description should mention that, because when I see the problem statement, immediately I use long long variable to handle that. 

It should help the contestants to immediately do not have to think about variable other than 32-bit integer range.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
