### ISSUE TITLE
30. Substring with Concatenation of All Words: Missing Constraint or Solution doesn't cover a Test case

### ISSUE THREAD

**Issue by hamidgasmi** [LeetCode-Feedback/LeetCode-Feedback#895]
#### Your LeetCode username 
O_Leet_Code

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The constraints are missing in the description or the solution doesn't cover the case where words are empty (`words[i].length == 0` for `0 <= i < words.length`)

The checker returns **wrong expected value** for the test case below:
- Input: s = "bar", words = [""]
- Leetcode displayed expected output: [0,1,2,3]
- Expected output: [0,1,2]

#### Code you used for Submit/Run operation

```
def findSubstring(self, s: str, words: List[str]) -> List[int]:
        if not words:
            return []
        
        words_count = len(words)
        word_len = len(words[0])
        s_len = len(s)
        if s_len < word_len * words_count:
            return []
        
        word_frequency = {}
        for word in words:
            if word not in word_frequency:
                word_frequency[word] = 0
            word_frequency[word] += 1
        
        match_results = []
        for l in range(s_len):
            r = l
            match_count = 0
            s_word_frequency = {}
            while r + word_len <= s_len:
                
                word = s[r:r + word_len]
                if word not in s_word_frequency:
                    s_word_frequency[word] = 0
                s_word_frequency[word] += 1
            
                if word not in word_frequency or s_word_frequency[word] > word_frequency[word]:
                    break
                
                match_count += 1
                if match_count == words_count:
                    match_results.append(l)
                    break
                
                r = r + word_len
                    
        return match_results
```

#### Language used for code: 
Python3

#### Expected behavior
- Add constraints: words are not empty (`words[i].length > 0` for `0 <= i < worlds.length`)
- or Expected error should be `[0,1,2]` for test case above + fix solution checker

**Comment by lc-pam** [comment]
Hi @hamidgasmi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @hamidgasmi 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
