### ISSUE TITLE
Improper Time Complexity Requirement - 2387. Median of a Row Wise Sorted Matrix

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8955]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [2387. Median of a Row Wise Sorted Matrix](https://leetcode.com/problems/median-of-a-row-wise-sorted-matrix), the problem description mentions that the required time complexity is O(m log n). However, a common solution has time complexity O(m log n log C), where C is the maximum value in the matrix. The solution with time complexity O(m log n log C) can be obtained by following the hints.

I do not know whether a solution with time complexity O(m log n) exists. Even if it exists, such a solution is too difficult from an interview perspective. Therefore, the required time complexity should be O(m log n log C).

In problem description, the required time complexity should be changed to O(m log n log C), where C is the maximum value in the matrix. If it is improper to include the term "C" into time complexity requirement, then the required time complexity should be lower than O(mn).

#### Code you used for Submit/Run operation
The following code is obtained by following the hints, with time complexity O(m log n log C).

```Java
class Solution {
    public int matrixMedian(int[][] grid) {
        int low = Integer.MAX_VALUE, high = Integer.MIN_VALUE;
        int m = grid.length, n = grid[0].length;
        int medianCount = (m * n + 1) / 2;
        for (int i = 0; i < m; i++) {
            low = Math.min(low, grid[i][0]);
            high = Math.max(high, grid[i][n - 1]);
        }
        while (low < high) {
            int mid = low + (high - low) / 2;
            int count = 0;
            for (int[] row : grid) {
                count += binarySearch(row, mid) + 1;
            }
            if (count >= medianCount) {
                high = mid;
            } else {
                low = mid + 1;
            }
        }
        return low;
    }

    public int binarySearch(int[] row, int target) {
        int low = -1, high = row.length - 1;
        while (low < high) {
            int mid = low + (high - low + 1) / 2;
            if (row[mid] <= target) {
                low = mid;
            } else {
                high = mid - 1;
            }
        }
        return low;
    }
}
```

#### Language used for code
Java

#### Expected behavior
In problem description, the required time complexity should be changed to O(m log n log C), where C is the maximum value in the matrix. If it is improper to include the term "C" into time complexity requirement, then the required time complexity should be lower than O(mn).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
