### ISSUE TITLE
Improper Constraints - 652. Find Duplicate Subtrees

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#8956]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [652. Find Duplicate Subtrees](https://leetcode.com/problems/find-duplicate-subtrees), the constraints mention that the number of nodes in the tree is in the range [1, 10<sup>4</sup>].

However, if the number of nodes is 10<sup>4</sup>, then an O(n<sup>2</sup>) approach won't be accepted, and will get either TLE or MLE.

There have been two issues requiring adding test cases for 652, raised for LCCN:

https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8932
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8933

Although both issues have been rejected, the constraints are indeed improper.

I believe the expected solution should have time complexity O(n<sup>2</sup>). Many solutions in the discuss area also have time complexity O(n<sup>2</sup>). If the number of nodes is 10<sup>4</sup>, then many solutions will become invalid.

Therefore, the maximum number of nodes should be reduced to 10<sup>3</sup>, to make sure that a solution with time complexity O(n<sup>2</sup>) can get accepted.

#### Expected behavior
The maximum number of nodes should be reduced to 10<sup>3</sup>, to make sure that a solution with time complexity O(n<sup>2</sup>) can get accepted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
Changed 10^4->5000 in constraints.
Updated validator
Removed 1 test case not satisfying constraints
