### ISSUE TITLE
Missing testcase – 890. Find and Replace Pattern

### ISSUE THREAD

**Issue by shdq** [LeetCode-Feedback/LeetCode-Feedback#8958]
#### Your LeetCode username
shdq

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For the input: `words = ["abcdefghijkba"]`, `pattern = "qwertyuiopwqa"`
My accepted solution gives me the wrong answer. An empty list should be returned, but it returns the given word.

Idea behind the solution is to represent each letter as a number and match them with pattern's number representation.

For example, the `"abc"` it will be `"012"`, for `"abb"` it will be `"011"`. And when a word consist of more than 9 letter this problem occurs (constraints says, that a word/pattern is up to 20 letters). Number representation of the 11th letter will be `"10"` which can mess up with second unique letter and first letter that together will be `"10"`. So if in a word after 11th letter goes 2nd and 1st letters it gives us `"1010"` and the pattern has reversed 2nd, 1st and 11th letters which will be the same `"1010"`.

A possible solution for this is to add a separator between numbers, like `"1-0-10"` and `"10-1-1"` which gives us different strings and correct answer.

#### Code you used for Submit/Run operation

```
class Solution:
  def findAndReplacePattern(self, words: List[str], pattern: str) -> List[str]:
    ans = []
    word_map = {}
    pattern_formula = ""
    for letter in pattern:
      if letter in word_map:
        pattern_formula += word_map[letter]
      else:
        curr_length = str(len(word_map))
        pattern_formula += curr_length
        word_map[letter] = curr_length

    word_map.clear()
    for word in words:
      current_word_formula = ""
      for i in range(0, len(word)):
        if word[i] in word_map:
          current_word_formula += word_map[word[i]]
        else:
          curr_length = str(len(word_map))
          current_word_formula += curr_length
          word_map[word[i]] = curr_length
        if pattern_formula[i] != current_word_formula[i]:
            break
      if pattern_formula == current_word_formula:
        ans.append(word)
      word_map.clear()
    return ans
```

#### Language used for code
Python

#### Expected behavior

This solution shouldn't be accepted. Provided testcase covers this edge case.

#### Screenshots

<img width="847" alt="image" src="https://user-images.githubusercontent.com/1219618/188893534-6ce3de90-8e16-4f3c-9aa2-906dd0c5751e.png">

#### Additional context

Thanks for the amazing platform!

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
