### ISSUE TITLE
287. Find the Duplicate Number

### ISSUE THREAD

**Issue by sohel0707** [LeetCode-Feedback/LeetCode-Feedback#896]
Your Optimized Solution is not working if the nth number is duplicate i.e We are trying to access nth index but index are from 0 to n-1 so it gives an error.                                                                                                                                                                                  suggest the modifying answer and add a test case

test case:
[5,1,5,4,2]
Your Solution (Approach 3: Floyd's Tortoise and Hare (Cycle Detection))  Gives error for this test case Please Modify it. Thanks in Advanced

**Comment by lc-pam** [comment]
Hi @sohel0707 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @sohel0707 ,
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
