### ISSUE TITLE
Misleading description of question - 708. Insert into a Sorted Circular Linked List

### ISSUE THREAD

**Issue by urosknapic** [LeetCode-Feedback/LeetCode-Feedback#8962]
#### Your LeetCode username

ukdevelop

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I find issue in current description of problem: 708. Insert into a Sorted Circular Linked List
Misleading description of 'ascending order', when in current 'correct' solution it should say 'non-decreasing order'.

Non-decreasing order can contain repeated elements for example [1,1,2,3] in list while ascending order can't for example [1,2,3].

"Given a Circular Linked List node, which is sorted in ascending order, write a function to insert a value insertVal into the list such that it remains a sorted circular list. The given node can be a reference to any single node in the list and may not necessarily be the smallest value in the circular list."

#### Screenshots

![image](https://user-images.githubusercontent.com/9485151/188972891-3f5a3eb3-a807-4934-90d7-afde1a7ff40d.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
