### ISSUE TITLE
Missing Test Case - 682. Baseball Game - not all edge cases covered

### ISSUE THREAD

**Issue by gega27** [LeetCode-Feedback/LeetCode-Feedback#8966]
gega27

#### Category of the bug
- [ ] Solution
- [ ] Missing Test Cases 

#### Description of the bug
the problem wrongly tested or incomplete:

Constraints are provided as those: 
1) 1 <= ops.length <= 1000
2) ops[i] is "C", "D", "+", or a string representing an integer in the range [-3 * 104, 3 * 104].

for those constraint, one of the edge case is to have very BIG INTEGER value at sum or in records. 
That means that for the test case similar to this one:
 1)       string[] ops = {"100", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D" };
  2)     string[] ops = {"100", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+" , "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+", "+"};

e.g. > the value becomes higher then integer  MaxValue at some point. you solution would fail, should result in arithmetic overflow!

the proper solution in c#  would be to use BigInteger, but unfortunately you don't test it and that makes an unfair situation for those ones who really thought about true edge cases :).

example with BigInteger would work on ops.length = 1000 with above test scenario :

#### Code you used for Submit/Run operation

```

using System;
using System.Text;
using System.Numerics;
using System.Collections.Generic;

public class Solution
{

  public static BigInteger CalPoints_UsingBigIntegers(string[] ops) {
    checked {
      BigInteger recsum = new BigInteger(0);
      LinkedList < BigInteger > records = new LinkedList < BigInteger > ();
      foreach(string el in ops) {
        if (el[0] == '+') {
          records.AddLast(BigInteger.Add(records.Last.Value, records.Last.Previous.Value));
        } else if (el[0] == 'D') {
          records.AddLast(BigInteger.Multiply(records.Last.Value, 2));
        } else if (el[0] == 'C') {
          records.RemoveLast();
        } else {
          records.AddLast(int.Parse(el));
        }
      }
      foreach(var el in records) {
        recsum = BigInteger.Add(recsum, el);
      }
      return recsum;
    }
  }

  public static int CalPoints_UsingInt(string[] ops) {
    checked {
      int recsum = 0;
      LinkedList < int > records = new LinkedList < int > ();
      foreach(string el in ops) {
        if (el[0] == '+') {
          records.AddLast(records.Last.Value + records.Last.Previous.Value);
        } else if (el[0] == 'D') {
          records.AddLast(records.Last.Value * 2);
        } else if (el[0] == 'C') {
          records.RemoveLast();
        } else {
          records.AddLast(int.Parse(el));
        }
      }
      foreach(var el in records) {
        recsum = recsum + el;
      }
      return recsum;
    }
  }

    public static void Main(string[] args)
    {
        string[] s = {"100", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D" };
        Console.WriteLine(CalPoints_UsingBigIntegers(s));
        Console.WriteLine(CalPoints_UsingInt(s));
        Console.ReadKey();
    }
}

```

#### Language used for code
c#

#### Expected behavior

for the type of code where i used int variable for sum leetcode should not pass the edge case test according to problem description constraints.
the solution provided by description by leetcode is as well  not implementing edge cases, so this problem must be a bit corrected or edge cases should be added.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The statement said that the answer will always fit in 32-bit integers and the two test cases are invalid. We appreciate your support!

**Comment by gega27** [comment]
that's great, but it still requures a bit correction . just a little bit:
original statement:
`Return the sum of all the scores on the record. The test cases are generated so that the answer fits in a 32-bit integer.'
`
recommended to have:
`
...
cases are generated so that the answer and "any intermediate values generated based on ops records will fit in 32bit integer"
`
