### ISSUE TITLE
 测试用例提示错误,执行却正确

### ISSUE THREAD

**Issue by ksiventy** [LeetCode-Feedback/LeetCode-Feedback#8967]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
NorrShawn

**Bug 类型**
- [ ] 验证回文串
- [ ] 解题
- [ ] Java
- [ ] 测试用例提示错误,执行却正确

**描述**
描述你遇到的 bug
提交代码,提示""解答错误”. 把提示的错误的用例 放进 测试用例 点击执行,结果与预期相符

**你使用的语言**
Java

**你提交或者运行的代码**
```
// Two Sum
class Solution {
    public boolean isPalindrome(String s) {
        char chars[] = s.toCharArray();
        String str = "";
        for (int i = 0; i < chars.length; i++) {
            if(chars[i]>=65&&chars[i]<=90){
                str+=String.valueOf((char)(chars[i]+32));
            }else if(chars[i]>=97&&chars[i]<=122){
                str+=String.valueOf(chars[i]);
            }
        }
        int length = str.length();
        for (int i = 0; i < length/2; i++) {
            if(str.charAt(i)!=str.charAt(length-i-1)){
                return false;
            }
        }
        return true;
    }
}
```

**期望行为**
描述你期望的结果
提交通过

**屏幕截图**
<img width="799" alt="image" src="https://user-images.githubusercontent.com/9465261/189076948-bdd952a6-53d3-4cd6-9be9-f5ab9d528c7f.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/9465261/189077227-ba31482c-aa61-42fb-99c4-a966ea4dfd74.png">

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
这里错误的用例是 "0P" ，不是 "OP"
