### ISSUE TITLE
Wrong Test Case - 198. House Robber

### ISSUE THREAD

**Issue by nqdai1992** [LeetCode-Feedback/LeetCode-Feedback#8969]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong Test Case 

#### Description of the bug
I used same input with the test case and run code is ok but when submit the result is rejected

#### Code you used for Submit/Run operation

```
// House Robber
const memo = {}

function dp (i: number, nums: number[]) {
  if (i === 0) return nums[0];
  if (i === 1) return Math.max(nums[0], nums[1])
  
  if (!memo[i]) {
    memo[i] = Math.max(dp(i - 1, nums), dp(i - 2, nums) + nums[i])  
  }
  
  return memo[i]
}

function rob(nums: number[]): number {
  return dp(nums.length - 1, nums)
};
```

#### Language used for code
Typescript

#### Screenshots
![Screen Shot 2022-09-08 at 16 10 49](https://user-images.githubusercontent.com/19273325/189085163-4f635d55-1804-4f22-8362-f9edd2371880.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by nqdai1992** [comment]
Thank for you support
