### ISSUE TITLE
Problem 521's title contains a trailing space.

### ISSUE THREAD

**Issue by kaiwensun** [LeetCode-Feedback/LeetCode-Feedback#897]
#### Your LeetCode username

kaiwensun

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The title of problem 521 `"Longest Uncommon Subsequence I "` has a trailing space. It should be `"Longest Uncommon Subsequence I"`.

#### Code you used for Submit/Run operation
N/A

#### Language used for code

N/A

#### Expected behavior

Title should be `Longest Uncommon Subsequence I` without trailing space.

#### Screenshots

https://leetcode.com/api/problems/all/

#### Additional context

N/A

**Comment by lc-pam** [comment]
Hi @kaiwensun 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @kaiwensun 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
