### ISSUE TITLE
197. 上升的温度 题解待更新

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#8970]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 题解

**描述**
官方题解执行出错

**期望行为**
修改题解字段名`date`为`recordDate`

**额外的上下文**
[题解链接](https://leetcode.cn/problems/rising-temperature/solution/shang-sheng-de-wen-du-by-leetcode/)

**Comment by BrambleWave** [comment]
感谢您的反馈，此题已暂时下线，奖励已发放。
