### ISSUE TITLE
Solution runs in PyCharm, but can't run in LeetCode

### ISSUE THREAD

**Issue by juhaszm** [LeetCode-Feedback/LeetCode-Feedback#8975]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
my solution runs without any issues in PyCharm, however I get "memory limit exceeded" error in Leetcode for "2. Add Two Numbers". 
It's highly unlikely my solution would indeed consume too much memory.

#### Code you used for Submit/Run operation

```
class Solution:
    def addTwoNumbers(self, l1: ListNode, l2: ListNode) -> [ListNode]:
        t = 0
        r = ListNode()
        c = r
        while l1 is not None and l2 is not None:
            c.next = ListNode()
            c = c.next
            c.val = (l1.val + l2.val + t) % 10
            t = (l1.val + l2.val + t) // 10
            l1 = l1.next
            l2 = l2.next
        if l1 is not None:
            l = l1
        elif l2 is not None:
            l = l2
        else:
            return r.next
        while l is not None:
            c.next = ListNode()
            c = c.next
            c.val = (l.val + t) % 10
            t = (l.val + t) // 10
        if t == 1:
            c.next = ListNode()
            c = c.next
            c.val = 1
        return r.next
```

#### Language used for code
python 3.9

#### Expected behavior
code runs and my solution is accepted

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the solution gets TLE and not MLE.
please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
