### ISSUE TITLE
Missing Test Case -141. Linked List Cycle

### ISSUE THREAD

**Issue by muller2333** [LeetCode-Feedback/LeetCode-Feedback#8978]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[3,2,0,-4]
-1

#### Code you used for Submit/Run operation

```
public class Solution {
    public boolean hasCycle(ListNode head) {
        final int val = 0;
        while(head!=null){
            if(head.val==val){
                return true;
            }else {
                head.val=val;
            }
            head=head.next;
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Screenshots

![2022-09-09](https://user-images.githubusercontent.com/25950952/189288526-bf325524-ff6e-48ac-a99a-dc88780069ef.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
