### ISSUE TITLE
Missing tests? - 925. Long Pressed Name

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#898]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

925. Long Pressed Name
	https://leetcode.com/problems/long-pressed-name/

At https://leetcode.com/submissions/detail/388800418/

Click on 88 ms submission
It shows below submitted code that passed:

Below solution is failing below 8 test cases:

	input   ["a","aaaaaaaaaaaaaaaaa"]
	expect  true
	actual  false

	input   ["aaaaaaaaaa","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
	expect  true
	actual  false

	input   ["a","aaaaaaaa"]
	expect  true
	actual  false

	input   ["aa","aaaaaaaa"]
	expect  true
	actual  false

	input   ["aaa","aaaaaaaa"]
	expect  true
	actual  false

	input   ["abcd","aaabbbcccddd"]
	expect  true
	actual  false

	input   ["abcd","abbcccdddd"]
	expect  true
	actual  false

	input   ["abcd","aaaabbbccd"]
	expect  true
	actual  false

Is the judge missing above 8 test cases (some might be repeated)?

If so
-- add some of these 8 testcases to judge
otherwise
-- remove above solution (88 ms submission) from the graph shown, in above link.
-- also remove other solutions that fail above tests

#### Code you used for Submit/Run operation

```
	/**
	 * @param {string} name
	 * @param {string} typed
	 * @return {boolean}
	 */
	var isLongPressedName = function(name, typed) {
		var letter;
		var count;
		var typedIdx = 0;
		var typedCount = 0;
		for (var i=0; i<name.length; i++) {
			letter = name[i];
			count = 1;
			
			while (name[i+1] && name[i] == name[i+1]) {
				count++;
				i++;
			}
			
			typedCount = 0;
			while (typed[typedIdx] == letter) {
				typedIdx++;
				typedCount++;
			}
			
			if (typedCount < count || typedCount > count * 2) {
				return false;
			}
		}
		
		return typedIdx == typed.length;
	};

```

#### Language used for code
JS

#### Expected behavior

Judge should provide

- Good test suite
- Submissions Graph should show valid solutions only

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by manoharreddyporeddy** [comment]
But `88 ms submission` is still present

Are you planning to remove it from the graph?

Otherwise, others will report the bug I reported, like I did now.
