### ISSUE TITLE
Inaccurate Solution - 606. Construct String from Binary Tree

### ISSUE THREAD

**Issue by megaspazz** [LeetCode-Feedback/LeetCode-Feedback#8981]
#### Your LeetCode username

megaspazz

#### Category of the bug
- [ ] Question
- [ X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/construct-string-from-binary-tree/solution/

Approach #1 in the solution does not actually run in O(N) as claimed, due to String concatenation.

Consider a tree of N = 10000 nodes, where each node (except the final leaf) has only a right-child--essentially just a long line of right-children of length N = 10000.

In this scenario, we are doing N = 10000 concatenation operations, whose cost is O(|S|) where S is the concatenated string.

Assuming we add some constant K characters in each layer of the recursion, we ultimately performed:  \
K + 2K + 3K + ... + NK total operations which is K * O(N^2) total runtime.

Even though the bounds of the test are small (maximum N = 10000), we can still observe a non-linear runtime:

N =  2,500:  14 ms
N =  5,000:  79 ms
N = 10,000: 243 ms

It would be much more pronounced if we could enter larger N.

#### Code you used for Submit/Run operation

(copied directly from Solution page)
```
public class Solution {
    public String tree2str(TreeNode t) {
        if(t==null)
            return "";
        if(t.left==null && t.right==null)
            return t.val+"";
        if(t.right==null)
            return t.val+"("+tree2str(t.left)+")";
        return t.val+"("+tree2str(t.left)+")("+tree2str(t.right)+")";   
    }
}

```

#### Language used for code

Java

#### Expected behavior

Want linear runtime, but got quadratic runtime.

#### Screenshots

I use this JS code-snippet to generate the test case as described above (tall tree of only right children).
https://pastebin.com/raw/VnFmyxLs

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've rewrite the code and use a global StringBuilder to ensure each character can be added only once, and convert to String in O(N).  We appreciate your support!
