### ISSUE TITLE
Rust Template for 1299. Replace Elements with Greatest Element on Right Side

### ISSUE THREAD

**Issue by danandreicarp** [LeetCode-Feedback/LeetCode-Feedback#8986]
#### Your LeetCode username
carpdan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When using Rust, the problem isn't solvable with the current function definition.
The constraint is that we should modify the array in place, according to [Fun with Arrays - In Place Operations](https://leetcode.com/explore/learn/card/fun-with-arrays/511/in-place-operations/3259/).

However, to modify the array, the function definition cannot be:

```rust
pub fn replace_elements(arr: Vec<i32>) -> Vec<i32>
```

because then it doesn't allow the modification of the `arr` inside.

It should be something like

```rust
pub fn replace_elements(arr: &mut Vec<i32>) -> Vec<i32>
```

#### Code you used for Submit/Run operation

```rust
pub fn replace_elements(arr: &mut Vec<i32>) -> Vec<i32> {
    if arr.len() == 1 {
        arr[0] = -1;
        return arr.to_owned();
    }

    let mut i = 0;
    while i < arr.len() - 1 {
        let mut max = arr[i + 1];
        for j in (i + 2)..arr.len() - 1 {
            if arr[j] > max {
                max = arr[j];
            }
        }
        arr[i] = max;
        i += 1;
    }
    let last_index = arr.len() - 1;
    arr[last_index] = -1;

    return arr.to_owned();
}
```

#### Language used for code

Rust

#### Expected behavior

I expect the code to compile and the test cases to run.
Instead I'm getting the following error message:

```
Line 59, Char 46: mismatched types (solution.rs)
   |
59 |         let ret = Solution::replace_elements(param_1);
   |                                              ^^^^^^^
   |                                              |
   |                                              expected `&mut Vec<i32>`, found struct `Vec`
   |                                              help: consider mutably borrowing here: `&mut param_1`
   |
   = note: expected mutable reference `&mut Vec<i32>`
                         found struct `Vec<i32>`
For more information about this error, try `rustc --explain E0308`.
error: could not compile `prog` due to previous error
mv: cannot stat '/leetcode/rust_compile/target/release/prog': No such file or directory
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. You can add the word mut before the function name and the problem will be solvable, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
 We appreciate your support!

**Comment by danandreicarp** [comment]
Hello,

Actually, I figured it out.

The "mut" keyword must be added before the parameter name, i.e. "pub fn mut replace_elements(mut arr: Vec<i32>) -> Vec<i32>"

This works fine.
You may leave this as resolved.

Thanks!
Dan

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by danandreicarp** [comment]
Hello,

I don't understand.

pubfnmutreplace_elements(arr:Vec<i32>)->Vec<i32>

isn't valid Rust syntax.

Please write more clearly what you're suggesting.

Also, there are no Rust solutions for this problem, likely because it has this issue.

Thanks!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
