### ISSUE TITLE
307. Range Sum Query - Mutable - Time Limit too strict 

### ISSUE THREAD

**Issue by yamaan93** [LeetCode-Feedback/LeetCode-Feedback#8987]
#### Your LeetCode username

yamaan93

#### Category of the bug
- [ ] Solution

#### Description of the bug

The test does not accept solutions that use an updated version of the solution to 303. Range Sum Query Immutable. The update function would have O(n) time complexity and everything else stays the same. 

#### Code you used for Submit/Run operation

```
//Range Sum Query - Mutable
class NumArray {
    int[] sums;
    int[] nums;
    public NumArray(int[] nums) {
        this.nums = nums;
        sums = new int[nums.length];
        sums[0] = nums[0];
        for(int i = 1; i<nums.length; i++){
            sums[i] = sums[i-1] + nums[i];
        }
        
    }
    
    public void update(int index, int val) {
        int difference = nums[index]-val;
        nums[index] = val;
        for(int i = index; i<sums.length; i++){
            sums[i] = sums[i] - difference; 
        }
        
    }
    
    public int sumRange(int left, int right) {
        if(left ==0){
            return sums[right];
        }
        else{
            return (sums[right] - sums[left-1]);
        }
        
    }
}

```

#### Expected behavior

16 / 16 test cases passed    rather than  16 / 16 test cases passed, but took too long.

#### Screenshots

![image](https://user-images.githubusercontent.com/25854486/189488867-b2b346df-2ff0-4549-bc88-4b1cf87f071e.png)

#### Additional context

This style of solution is the natural progression for anyone moving up after doing 303, as it uses the same technique and builds upon it. It also isn't slow by any means, it still has linear or constant time complexity for all the operations, and the tree solution shouldn't be too much faster.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
