### ISSUE TITLE
1051. Height Checker (Java Solution not working)

### ISSUE THREAD

**Issue by ChiragUmraniya** [LeetCode-Feedback/LeetCode-Feedback#8988]
#### Category of the bug
- [ ] Solution
 

#### Code you used for Submit/Run operation

```
// 1051. Height Checker

class Solution {
    public int heightChecker(int[] heights) {
        int []expected=heights;
        Arrays.sort(expected);
        int cnt=0;
        for(int i=0;i<heights.length;i++){
            if(heights[i]!=expected[i])
                cnt++;
            else
                continue;
        }
        return cnt;
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
