### ISSUE TITLE
Missing Test Case - 416. Partition Equal Subset Sum

### ISSUE THREAD

**Issue by AP-Repositories** [LeetCode-Feedback/LeetCode-Feedback#8989]
#### Your LeetCode username

AP-Repositories

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing Test Cases

#### Description of the bug

The first algorithm I came up with for this problem passed all test cases, but
when I tried to optimize the algorithm by sorting the input before running it,
my algorithm failed on the last test case. There is no restriction which would prevent
a sorted array from being the input, so my algorithm should have never been accepted
in the first place.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean canPartition(int[] nums) {
        List<Integer> _nums = new LinkedList<Integer>();
        Set<Integer> seen = new HashSet<Integer>();
        int sum = 0;
        for(int n: nums) {
            sum += n;
            _nums.add(n);
        }
        return canPartition(seen, _nums, sum, 0);
    }
    
    boolean canPartition(Set<Integer> seen, List<Integer> nums, int sumNums, int sumChoose) {
        if(sumNums <= sumChoose) return sumNums == sumChoose;
        if(seen.contains(sumNums) || seen.contains(sumChoose)) return false;
        int len = nums.size();
        for(int i = 0; i < len; i++) {
            int num = nums.remove(i);
            if(canPartition(seen, nums, sumNums-num, sumChoose+num))
                return true;
            nums.add(i, num);
        }
        seen.add(sumNums);
        seen.add(sumChoose);
        return false;
    }
    
}
```

#### Language used for code

Java

#### Expected behavior

My algorithm should have failed the test cases, but it passed.

#### Additional context

[1,4,5,8,12,13,14,17,18] is an example of a test case which would correctly cause my solution to fail

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
