### ISSUE TITLE
Problem 1560's title contains extra whitespace in its HTML entity

### ISSUE THREAD

**Issue by kaiwensun** [LeetCode-Feedback/LeetCode-Feedback#899]
#### Your LeetCode username
kaiwensun

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Though looks good in rendered webpage view, in the HTML entity of the title of problem 1560, the text is
```
"Most Visited Sector in  a Circular Track"
```
It has an extra white space between `in` and `a`. The title should be
```
"Most Visited Sector in a Circular Track"
```
This is happening in both problem list page and the individual problem page.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

```
"Most Visited Sector in a Circular Track"
```

#### Screenshots

* In https://leetcode.com/problems/most-visited-sector-in-a-circular-track/, the title HTML entity is
```
<div data-cy="question-title" class="css-v3d350">Most Visited Sector in  a Circular Track</div>
```

* In https://leetcode.com/problemset/all/?search=1560, the title HTML entity is
```
<a href="/problems/most-visited-sector-in-a-circular-track" data-slug="most-visited-sector-in-a-circular-track">Most Visited Sector in  a Circular Track</a>
```
They both have extra white space in the problem title.

#### Additional context

N/A

**Comment by lc-pam** [comment]
Hi @kaiwensun 
Thank you for reaching out to us. Can you please share in the comments that how having extra whitespace in HTML entity would impact your usage? We'll consider fixing if the reason is valid.
