### ISSUE TITLE
Incorrect solution description 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by cswartzell** [LeetCode-Feedback/LeetCode-Feedback#8991]
#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description in the solution states "The points of interest are the peaks and valleys in the given graph. We need to find the largest peak following the smallest valley. We can maintain two variables - minprice and maxprofit corresponding to the smallest valley and maximum profit (maximum difference between selling price and minprice) obtained so far respectively." This is incorrect. The smallest valley could occur on the final day, and thus the profit according to this algorithm would be zero. It should state "we need to to find the highest peak after _**each**_ valley, and select the pair with the largest profit" or some such. We are not at all looking for the smallest valley, merely the largest difference between valid pairings. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
