### ISSUE TITLE
When running test case leetcode says it is right, but when submitting it fails for the same test case

### ISSUE THREAD

**Issue by albertininm** [LeetCode-Feedback/LeetCode-Feedback#8992]
#### Your LeetCode username
albertininm

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When I run my code before submitting my code, it succeeds for a test case, but then, when I submit it, I get wrong answer for the same test case that passes when clicking on `Run Code` button.

#### Code you used for Submit/Run operation

```
// 188. Best Time to Buy and Sell Stock IV
func maxProfit(k int, prices []int) int {
    return mp(k, prices, false)
}

var cache = make(map[int]int)

func mp(k int, prices []int, hasStock bool) int {
    if k == 0 || len(prices) == 0 {
        return 0
    }

    var h int

    if hasStock {
        h = 1
    } else {
        h = 0
    }

    key := (k << 11) | (len(prices) << 1) | h

    if _, contains := cache[key]; contains {
        return cache[key]
    }

    tail := prices[1:]

    var now int
    var later int

    if hasStock {
        now = prices[0] + mp(k - 1, tail, false)

        later = mp(k, tail, true)
    } else {
        now = -prices[0] + mp(k, tail, true)

        later = mp(k, tail, false)
    }

    if now > later {
        cache[key] = now

        return now
    } else {
        cache[key] = later

        return later
    }
}
```

#### Language used for code
Go

#### Expected behavior
If I get a wrong answer when submitting, it should fail for the same test case when running a test.

#### Screenshots
<img width="1532" alt="Screenshot 2022-09-10 at 23 01 46" src="https://user-images.githubusercontent.com/19316913/189501824-74f94daf-7ceb-4c27-9919-98eb2db49b0b.png">

#### Additional context
It is probably a variable name conflict. 
Leetcode probably has a global var that is conflicting to one of my variable names.
I used a var name `cache` which is probably the problem.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
