### ISSUE TITLE
1488. Test case check is incorrect

### ISSUE THREAD

**Issue by harishrithish7** [LeetCode-Feedback/LeetCode-Feedback#8993]
Question 1488 has multiple valid answers for a given testcase. For the input = [69,0,0,0,69], output = [-1,69,-1,-1,-1] is a valid solution. However, the system rejects it as the wrong answer. It says the expected answer = [-1,69,1,1,-1], which is also a valid solution but not the only solution.

Submission id: https://leetcode.com/submissions/detail/796590230/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
