### ISSUE TITLE
Incorrect Question Description - 1442. Count Triplets That Can Form Two Arrays of Equal XOR

### ISSUE THREAD

**Issue by ramsudharsan75** [LeetCode-Feedback/LeetCode-Feedback#8994]
#### Your LeetCode username
ramsudharsan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Consider the following example provided in the question:
arr = [2,3,1,6,7]
i = 0
j = k = 1

a = arr[i] ^ arr[1 + 1] ^ ... ^ arr[j - 1] (according to question, i must be less than j and k). 
So **a = arr[0] ^ arr[1 - 1] = 0**

b = arr[j] ^ arr[j + 1] ^ ... ^ arr[k] (according to question, j can be equal to k). 
So **b = arr[1] ^ arr[1] = 0**

Sample answer = (0,1,2), (0,2,2), (2,3,4) and (2,4,4)

In the above case, a is equal to b. But in the sample answer (0, 1, 1) pair is not present. So the question is flawed / needs correction in its description.

#### Code you used for Submit/Run operation
```
class Solution:
    def countTriplets(self, arr: List[int]) -> int:
        count = 0

        for i in range(len(arr) - 1):
            a = arr[i]

            for k in range(i + 1, len(arr)):
                if a ^ arr[k] == 0:
                    count += k - i

                a ^= arr[k]

        return count
```

#### Language used for code
Python3

#### Expected behavior
Correct the question description. Add a condition saying j - 1 must not be equal to i.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
