### ISSUE TITLE
Missing Test Case - 739. Daily Temperatures

### ISSUE THREAD

**Issue by AstroMen** [LeetCode-Feedback/LeetCode-Feedback#8995]
#### Your LeetCode username

AstroMen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When I copy one of the two official solutions and submit it, it shows "Time Limit Exceeded". Other people uses the same code to submit, it showed "passed" by their account.

#### Code you used for Submit/Run operation

```
class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        n = len(temperatures)
        stack = list()
        res = [0] * n
        for cur_day, cur_temp in enumerate(temperatures):
            while stack and cur_temp > temperatures[stack[-1]]:  # notice: no need =
                prev_day = stack.pop()
                # pop的时候, 找到了pop元素的下一个最大值, 所以更新
                res[prev_day] = cur_day - prev_day
            stack.append(cur_day)
        return res
```

#### Language used for code

python3

#### Expected behavior

It expects to show "passed". Actually, it shows "Time Limit Exceeded".

#### Screenshots

The evidence could find by this link: https://leetcode.com/submissions/detail/796531170/

#### Additional context

I uses the same code as the second official solution, it also showed "Time Limit Exceeded". The evidence could find by this link: https://leetcode.com/submissions/detail/796631897/

Thanks.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, when we tested the code, we received "Accepted". Thank you for your support.
