### ISSUE TITLE
Missing Test Case - 67. Add Binary

### ISSUE THREAD

**Issue by Tejv1708** [LeetCode-Feedback/LeetCode-Feedback#8996]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?
