### ISSUE TITLE
Solution for the given problem missing. Problem no: 47. Permutations II

### ISSUE THREAD

**Issue by garimasingh128** [LeetCode-Feedback/LeetCode-Feedback#90]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Solution for the given problem missing. Problem no: 47. Permutations II
URL: https://leetcode.com/problems/permutations-ii/

**what language is your code written in**
C++

**Comment by CooperCooperCooper** [comment]
Hi @garimasingh128,
Thank you for reaching out to us! I've relayed this issue to our team and request to prioritize adding solution to this problem as soon as possible. We appreciate your time and support. If you have any other requests, please don't hesitate to let us know.
