### ISSUE TITLE
Problem description issue - 443. String Compression

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#900]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/string-compression/
443. String Compression

Question description is confusing to many as expressed in discuss/solution pages.
- 122 upvotes - https://leetcode.com/problems/string-compression/solution/340283
- 156 upvotes - https://leetcode.com/problems/string-compression/discuss/92559/Simple-Easy-to-Understand-Java-solution/193337
- 13 upvotes - https://leetcode.com/problems/string-compression/discuss/315030/The-bad-problem!!Why-not-show-the-example-of-%22aaabbaa-is-a3b2a3%22

Please fix this question description. For example as below:

There are 2 expected outputs for this question:
- Function should return length.
	Example: 6
- Another indirect output is via passed parameter. Parameter array passed should be inline edited.
	Example: ["a","2","b","2","c","3"]

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- Problem statement should be crisp, and not repeatative (two times inline is mentioned).
- Problem should state there are 2 outputs in the description. Not in the examples.
- Each test case example should describe that there are 2 ouputs.

See description above, for how it can be better done - without repetitions.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
