### ISSUE TITLE
Submission and Testcase not matching

### ISSUE THREAD

**Issue by YingcongYu** [LeetCode-Feedback/LeetCode-Feedback#9002]
#### Your LeetCode username

yingcongyu98

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Code passed in test case but not in submission. The situations mentioned in the website (https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-) do not match.

#### Code you used for Submit/Run operation

```
// Longest Palindromic Substring
class Solution:
    def longestPalindrome(self, s: str) -> str:
        output = ''
        for i in range(len(s)):
            for j in range(len(s), i, -1):
                if s[i:j] == s[i:j][::-1]:
                    if len(s[i:j]) > len(output):
                        output = s[i:j]
        return output
```

#### Language used for code

Python

#### Expected behavior

Either the submission should be passed or the test case should be rejected.

#### Screenshots

![WeChat Screenshot_20220911013026](https://user-images.githubusercontent.com/84693018/189518662-83680c37-15c0-448e-bed7-efc697f2f7ee.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by YingcongYu** [comment]
> 

Sure! It is problem No.5 and it's called "Longest Palindromic Substring".

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution is supposed to TLE. There are 150 test cases and the solution is supposed to pass all of them within the time limit. We appreciate your support!
