### ISSUE TITLE
Missing Test Case - 633. Sum of Square Numbers

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [LeetCode-Feedback/LeetCode-Feedback#9005]
#### Your LeetCode username
soumya_kush

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question demands two numbers as output whose individual squares when added up equal to the given input.
For example, if 5 is input and
Since, 1^2 + 2^2 = 5
we return true.

But on submission, the solution is said wrong for the input 4.
There is no way we can add squares of two numbers and equal to 4.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    bool judgeSquareSum(int c) {
        long low = 1; 
        long high = c/2;
        
        while (low <= high){
            long mid = low + (high - low)/2;
            
            if (low*low + high*high == c)
                return true;
            
            else if (low*low + high*high > c)
                high = mid - 1;
            
            else low = mid + 1;
        }
        
        return false;
    }
};
```

#### Expected behavior
The question demands two numbers as output whose individual squares when added up equal to the given input.
For example, if 5 is input and
Since, 1^2 + 2^2 = 5
we return true.

But on submission, the solution is said wrong for the input 4.
There is no way we can add squares of two numbers and equal to 4 and should therefore output FALSE instead of TRUE.

**Comment by stormsunshine** [comment]
4 = 0<sup>2</sup> + 2<sup>2</sup>. Why do you think the result should be false?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. Please consider stromsunshine's reply as reference. Thank you for your support!
