### ISSUE TITLE
259. 3Sum Smaller

### ISSUE THREAD

**Issue by santanu33** [LeetCode-Feedback/LeetCode-Feedback#901]
#### Your LeetCode username
santanu_33

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Problem with the problem statement.

Given an array of n integers nums and a target, find the number of index triplets i, j, k with `0 <= i < j < k < n` that satisfy the condition `nums[i] + nums[j] + nums[k] < target`.

the problem statement needs to be like

Given an array of n integers nums and a target, find the number of index triplets i, j, k with `0 <= i != j != k < n`  that satisfy the condition `nums[i] + nums[j] + nums[k] < target`.

**Comment by lc-ivan** [comment]
Hi @santanu33 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @santanu33 ,
Thanks for your feedback regarding this problem. Upon review, our team has concluded that the problem description is correct and clear as is, so, we will not be rewarding LeetCoins for this case. Thank you once again for your support. Happy LeetCoding!
