### ISSUE TITLE
Improper Test Case Validator and Constraints - 50. Pow(x, n)

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#9010]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [50. Pow(x, n)](https://leetcode.com/problems/powx-n), when calculating x<sup>n</sup>, it is possible that x = 0 and n = 0. In this case, the expression x<sup>n</sup> is invalid, but such a test case is still allowed in custom test cases, which makes no sense.

When x = 0 and n < 0, then the test case validator returns "0.0 cannot be raised to a negative power". However, this check does not exist for x = 0 and n = 0. To make sure all custom test cases are valid, such a check should also be added for x = 0 and n = 0.

Also, the constraints should mention that when x = 0, it is guaranteed that n > 0.

#### Expected behavior
1. The test case validator should also check the case where x = 0 and n = 0, and return a message similar to the case where x = 0 and n < 0.
2. The constraints should mention that when x = 0, it is guaranteed that n > 0.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We did not change constraints, but updated the validator. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
