### ISSUE TITLE
Improper time complexity requirement - 74. Search a 2D Matrix

### ISSUE THREAD

**Issue by md-abid-hussain** [LeetCode-Feedback/LeetCode-Feedback#9012]
#### Your LeetCode username
Amomynus

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question required to write an  efficient solution. But it can be solved with 100% faster than all submission even with worst time complexity.

#### Code you used for Submit/Run operation

```
// 74. Search a 2D Matrix
class Solution {
    public boolean searchMatrix(int[][] matrix, int target) {
        for(int i = 0;i<matrix.length;i++)
            for(int j = 0;j<matrix[i].length;j++)
                if(matrix[i][j]==target)
                    return true;
        return false;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior

Time limit exceeded

#### Screenshots

![Capture](https://user-images.githubusercontent.com/101964499/189592145-19629980-73e2-45f6-a806-d12da3e6dcb8.JPG)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
