### ISSUE TITLE
T1190. 反转每对括号间的子串，数据范围与提示不匹配

### ISSUE THREAD

**Issue by Coco-001** [LeetCode-Feedback/LeetCode-Feedback#9013]
**Bug 类型**
-  缺少测试用例

**描述**
题目提示数据范围为 [ 0, 2000 ]；实际测试用例并不包含长度为 0 的字符串

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    public String reverseParentheses(String s) {
        if(s.length() == 0) return "";
        List<Character> stack = new ArrayList<>();
        LinkedList<Integer> list = new LinkedList<>();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            stack.add(c);
            if (c == ')') {
                reverse(stack, list.getLast(), i);
                list.removeLast();
            } else if (c == '(') {
                list.add(i);
            }
        }
        StringBuilder sb = new StringBuilder();
        for (Character c : stack) {
            if (c != '(' && c != ')') sb.append(c);
        }
        return sb.toString();
    }

    void reverse(List<Character> list, int l, int r) {
        while (l < r) {
            Character t = list.get(l);
            list.set(l, list.get(r));
            list.set(r, t);
            r--;
            l++;
        }
    }
}
```

**期望行为**
输入空字符串“”，应当返回结果“”；

**屏幕截图**
![image](https://user-images.githubusercontent.com/57981434/189601381-a58938f6-1a21-4e6f-a0d5-715110c37b7e.png)
![image](https://user-images.githubusercontent.com/57981434/189601428-b9aba4fc-cc04-4c5b-a961-8bbf7fad1282.png)

**额外的上下文**
请添加空串作为测试用例或者修改测试用例的提示范围~

**Comment by BrambleWave** [comment]
6. 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by Coco-001** [comment]
收到收到！

**Comment by Coco-001** [comment]
你好，我的个性域名为coco-e1


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月14日(星期三) 下午2:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] T1190. 反转每对括号间的子串，数据范围与提示不匹配 (Issue #9013)





 
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by BrambleWave** [comment]
已发放
