### ISSUE TITLE
Missing Test Case - 2407. Longest Increasing Subsequence II

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#9014]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9546175/2.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int lengthOfLIS(vector<int>& nums, int k) {
        int ans = 1;
        map<int, int> dic;
        for(auto n : nums) {
            auto pre = dic.upper_bound(-n);
            int dp = 1 + pre->second;
            ans = max(ans, dp);

            auto it = dic.upper_bound(-n - k - 1);
            int old = it -> second;
           
            while(it != pre && it->second > dp)
                it ++;
            if (it != pre) dic.erase(it, pre);

            dic[-n] = dp; 
            if(old < dp) dic[-n-k] = old;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by duststarr** [comment]
cool
