### ISSUE TITLE
Missing Test Case - 85. Maximal Rectangle

### ISSUE THREAD

**Issue by VishalKharche14** [LeetCode-Feedback/LeetCode-Feedback#9015]
#### Your LeetCode username
VishalKharche

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I am not clearing STACK while using a buildNSL function which will be creating conflicts in some testcases. So I derived a testcase where the code will fail and checked. The code is failing while running custom testcase, but as no similar testcase is already present, my code was able to pass all the available testcases.

#### Code you used for Submit/Run operation

```
// Maximal Rectangle
class Solution {
    public Stack<Integer> stack = new Stack();
    public int maximalRectangle(char[][] matrix) {
        int max = 0;
        int[] arr = new int[matrix[0].length];
        
        for(int j=0; j<matrix.length; j++){
            for(int i=0; i<matrix[0].length; i++){
                if(matrix[j][i]=='0') arr[i]=0;
                else arr[i]+=matrix[j][i]-'0';
            }
            max = Math.max(max, largestRectangleArea(arr));
        }
        return max;
        
    }
    public int largestRectangleArea(int[] heights) {
        int [] nsl = buildNSL(heights);
        int [] nsr = buildNSR(heights);
        int max = 0;
        
        for(int i=0; i<nsl.length; i++){
            nsr[i]=(nsr[i]-nsl[i])+1;
            int temp = heights[i]*nsr[i];
            max = Math.max(temp,max);
        }
        return max;
    }
    public int[] buildNSL(int[] arr){
        int[] ans = new int[arr.length];
        stack.push(0);
        ans[0] = 0;
        for(int i=1; i<arr.length; i++){
            while(!stack.isEmpty() && arr[stack.peek()]>=arr[i]) stack.pop();
            if(stack.isEmpty()){
                stack.push(i);
                ans[i]=0;
            }
            else{
                ans[i]=stack.peek()+1;
                stack.push(i);
            }
        }
        return ans;
    }
    public int[] buildNSR(int[] arr){
        stack.clear();
        int[] ans = new int[arr.length];
        stack.push(arr.length-1);
        ans[arr.length-1] = arr.length-1;
        
        for(int i=arr.length-2; i>=0; i--){
            while(!stack.isEmpty() && arr[stack.peek()]>=arr[i]) stack.pop();
            if(stack.isEmpty()){
                stack.push(i);
                ans[i]=arr.length-1;
            }
            else{
                ans[i]=stack.peek()-1;
                stack.push(i);
            }
        }
        return ans;
    }
};
```

#### Language used for code
JAVA

#### Expected behavior

Correct Answer should be 8, but it is returning 6. Still solution gets accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/83890748/189626079-599d1c8d-9756-4cd6-93e3-b7039ea94b1e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case that you use. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by VishalKharche14** [comment]
The Missing TestCase that I use is 
`[["0","1","1","1","0","0"],["1","1","0","1","1","1"],["0","1","0","1","0","1"],["0","0","0","1","1","0"],["1","0","0","0","1","1"],["1","0","1","1","0","0"],["1","1","1","1","1","0"],["1","1","0","1","0","0"],["1","1","0","0","1","0"],["1","1","0","1","0","0"]]`

**Comment by VishalKharche14** [comment]
The Missing TestCase that I use to debug is

[["0","1","1","1","0","0"],["1","1","0","1","1","1"],["0","1","0","1","0","1"],["0","0","0","1","1","0"],["1","0","0","0","1","1"],["1","0","1","1","0","0"],["1","1","1","1","1","0"],["1","1","0","1","0","0"],["1","1","0","0","1","0"],["1","1","0","1","0","0"]]
>

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
