### ISSUE TITLE
Explore Card Track

### ISSUE THREAD

**Issue by AmirElsaeed** [LeetCode-Feedback/LeetCode-Feedback#9018]
#### Your LeetCode username
AmirElsaeed

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [✓] Error

#### Description of the bug
at [Explore Card Track](https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/679/sql-syntax/4358/)
clicking at Databases & SQL card redirect to the same page

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
