### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by z-kumar** [LeetCode-Feedback/LeetCode-Feedback#9019]
#### Your LeetCode username

jagspidey

#### Category of the bug
- [ ] Question
- [1] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My code is showing different output ("true") on leetcode and a different output ("false") on my learning portal

#### Code you used for Submit/Run operation

```
class Solution:
    def isIsomorphic(self, s: str, t: str) -> bool:
        iso_dict = {}
        length = len(s)
        if length == 1:
            return "true"
        for i in range(length):
            iso_dict[s[i]] = t[i]
        output = ""
        for key in s:
            output += iso_dict[key]
        if s == output:
            return "true"
        return "false"
```

#### Language used for code

Python

#### Expected behavior

test case :
s = "foo"
t = "bar"
expected output = "false"
actual output on leet code = "true"
actual output on other editors = "false"

#### Screenshots

i have added a screenshot which displays using my personal editor and leetcode editor for the current test case 
![1](https://user-images.githubusercontent.com/110066427/189644133-99958be8-5d2f-4cf6-be03-3c4f0c45edd5.PNG)
![1](https://user-images.githubusercontent.com/110066427/189644244-42e5eef4-ddd0-4024-832f-fc0f474af5ec.PNG)
![2](https://user-images.githubusercontent.com/110066427/189644249-b093f1de-2321-43f9-ab94-80e7dce8d9cb.PNG)

#### Additional context

I also added screenshots for other test cases which displays me using my personal editor to show that my personal editor is giving desired output
![3](https://user-images.githubusercontent.com/110066427/189644301-4d7baf68-14d3-4d77-a3b4-9b1da8d1bffe.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
