### ISSUE TITLE
948. Bag of Tokens  testcase wrong

### ISSUE THREAD

**Issue by Scylla23** [LeetCode-Feedback/LeetCode-Feedback#9020]
#### Category of the bug  --> Solution
- [ ] Question
- [x] Solution   
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 948. Bag of Tokens
class Solution {
    public int bagOfTokensScore(int[] tokens, int power) {
        Arrays.sort(tokens);
        int l = 0;
        int r = tokens.length-1;
        int score = 0;
        while(l <= r){
            //System.out.println(power);
            if(l == r){
                if(power >= tokens[l]){
                    power -= tokens[l++];
                    score++;
                    break;
                }else{
                    break;
                }
            }
            if(power < tokens[l]){
                power += tokens[r--];
                score--;
            }else{
                power -= tokens[l++];
                score++;
            }
        }
        return score;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

In the above testcase  first we will sort it  then tokens -> [55,71,82] 
and initial power is 54 then we would first increae the power by 82
then  power = 54 + 82  = 136 and score = -1
then we choose 55  so, power = 136-55 = 81 and score = 0
then we choose 71 so, power = 81-71 = 10 and score = 1
so, the answer i.e. score should be 1 and not 0

#### Additional context

we have to choose greedily so the answer should be 1 and not 0

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
