### ISSUE TITLE
The numbered list seems to be wrong.

### ISSUE THREAD

**Issue by pershin-daniil** [LeetCode-Feedback/LeetCode-Feedback#9023]
#### Your LeetCode username

pppershin

#### Category of the bug
- [ ] mistakes in the text

#### Description of the bug

In the article, when you expand "Explore Card layers", a numbered list appears that starts with 4, it seems to me that it should start with 1.

#### Screenshots

![image](https://user-images.githubusercontent.com/52123477/189691612-c595b029-311b-401c-9c27-8e1ae79a4bbd.png)

#### Additional context

[Link](https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/679/sql-syntax/4358/) where issue was found.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
