### ISSUE TITLE
账号解禁

### ISSUE THREAD

**Issue by SStarLib** [LeetCode-Feedback/LeetCode-Feedback#903]
第204场周赛账号被禁，希望解禁，账号链接：https://leetcode-cn.com/u/strung/

**Comment by feiceh** [comment]
你好，经核实 ID「strung」 在 weekly-contest-204 场比赛中 Q2 代码和全球排名 (3856) 的 「lzz-78」 一模一样无法解禁，如果大家都有各种各样的特殊情况，规则可以被肆意破坏的话，这个竞赛就没有价值了。[竞赛注意事项](https://leetcode-cn.com/circle/article/HKbjrw/)  可以详细阅读。
