### ISSUE TITLE
 Time Limit Exceeded -  1711. Count Good Meals

### ISSUE THREAD

**Issue by iritvam** [LeetCode-Feedback/LeetCode-Feedback#9030]
I resolved the problem in C.
my solution pass the input of test 64/70 when i do "run code", but not when I submit it :(

**Comment by Leader-board** [comment]
That probably means that the test case runs takes long, but not to the extent of returning a TLE when you run it individually. However, when you submit, it runs all test cases on the same instance, and the sum of the time taken by each test case can well result in a TLE.
