### ISSUE TITLE
Missing Test Case - 393. UTF-8 Validation

### ISSUE THREAD

**Issue by raditya1710** [LeetCode-Feedback/LeetCode-Feedback#9031]
#### Your LeetCode username
alfonsus_raditya

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

for input like `[128,130]`, it should returns `false`. But the submission is mark as Accepted.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    bool validUtf8(vector<int>& data) {
        int n = data.size();
        for(int i = 0;i < n;){
            int num_bytes = get_num_bytes(data[i]);
            if(num_bytes == -1) return false;
            if(i + num_bytes > n) return false;
            for(int j = i + 1; j < i + num_bytes; ++j){
                if((data[j] ^ 128) >= 64) return false;
            }
            i += num_bytes;
        }
        return true;
    }
    
    int get_num_bytes(int x){
        if(x < 0b10000000) return 1;
        if(x < 0b11100000) return 2;
        if(x >= 0b11100000 && x < 0b11110000) return 3;
        if(x >= 0b11110000 && x < 0b11111000) return 4;
            
        return -1;
    }
};
```

#### Language used for code
C++

#### Expected behavior

For the input `[128, 130]`, it should be wrong answer, because binary representation of 128 is 10000000, which does not match with any of the 1-4 byte mark.

#### Screenshots

![Screenshot from 2022-09-13 07-37-03](https://user-images.githubusercontent.com/14028227/189782487-46d2c30d-8ab7-481f-9e7f-580271118a5b.png)

#### Additional context

Submission that should be wrong answer but accepted: 
https://leetcode.com/submissions/detail/798368394/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
