### ISSUE TITLE
代码执行错误

### ISSUE THREAD

**Issue by renyanLemon** [LeetCode-Feedback/LeetCode-Feedback#9034]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**柠檬小小**

**Bug 类型**
- [ ] [670. 最大交换](https://leetcode.cn/problems/maximum-swap/)

**描述**
代码执行错误

**你使用的语言**
js

**你提交或者运行的代码**
```
/**
 * @param {number} num
 * @return {number}
 */
let temp = 0
let index = 0
let start = 0
var maximumSwap = function(num) {
    const numArr = num.toString().split('')
    getmax(numArr)
    return numArr.join('')
};

const getmax = (arr) => {
    for(let i = start; i < arr.length; i++) {
        if(arr[i] > temp) {
            temp = arr[i]
            index = i
        }
    }
    if(index !== 0) {
        arr[index] = arr[start]
        arr[start] = temp
    }else {
        temp = 0
        index = 0
        start++
        getmax(arr) 
    }
}
```

**屏幕截图**
<img width="1092" alt="屏幕快照 2022-09-13 上午11 58 52" src="https://user-images.githubusercontent.com/39343739/189805419-a796d21d-0eb2-43bf-88a8-aa34b58278d7.png">

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
