### ISSUE TITLE
0694. 不同岛屿的数量 缺少图例

### ISSUE THREAD

**Issue by CooperLi** [LeetCode-Feedback/LeetCode-Feedback#9035]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
DCCooper

**Bug 类型**
- [X] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
中文版题目描述中没有图例

**你使用的语言**
 NA

**你提交或者运行的代码**
NA

**期望行为**
中文版题目描述有图例

**屏幕截图**
英文版：
<img width="767" alt="image" src="https://user-images.githubusercontent.com/17704570/189825151-2c5d23c9-d905-438d-8fcc-6fce3325c8b8.png">

中文版：
<img width="775" alt="image" src="https://user-images.githubusercontent.com/17704570/189825229-26be653b-8369-46c7-ab37-1cfc39c131a3.png">

**额外的上下文**
NA

**Comment by BrambleWave** [comment]
可能是网络缓存的问题，您可以尝试重新打开。
