### ISSUE TITLE
Missing Test Case - 2337. Move Pieces to Obtain a String

### ISSUE THREAD

**Issue by xbecodex** [LeetCode-Feedback/LeetCode-Feedback#9037]
#### Your LeetCode username
xbe

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug
There is a missing case when R overlap, my solution solution passes all test cases, however it fails the one in the example:
Example: 
"__R_L"
"L_R__"

The example needs to be added the test cases.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean canChange(String start, String target) {
        if (start.equals(target)) return true;
        
        int size = start.length();
        int lcount = 0;
        int rcount = 0;
        for (int i = 0; i < size; i++) {
            // L: close, R: open
            char s = start.charAt(i);
            
            // L:open, R:close
            char t = target.charAt(i);
            
            if (s == 'L') lcount -= 1;
            else if (s == 'R') rcount += 1;  
            
            if (s == 'L' && rcount > 0) return false;
            else if (t == 'L' && rcount > 0) return false;
            
/ * 
//to cover the missing case

            if (s == 'R' && lcount > 0) return false;
            else if (t == 'R' && lcount > 0) return false;
  */          
            if (t == 'R') rcount -= 1;
            else if (t == 'L') lcount += 1;
            
            
            if (lcount < 0 || rcount < 0) return false;
        }
        
        return rcount == 0 && lcount == 0;
    }
}
```

#### Expected behavior

the above solution should have failed for this test case (however as of now it passes):
Example: 
"__R_L"
"L_R__"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
