### ISSUE TITLE
Solution issue - 393. UTF-8 Validation

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#9038]
#### Your LeetCode username

Leaderboard

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution (https://leetcode.com/problems/utf-8-validation/) mentions that 

> Another important thing to note is that the integers in the array can be larger than 255 as well. The highest number that can be represented by 8 bits is 255

The constraints however mention that 

> 0 <= data[i] <= 255

which is contradictory with the above statement.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior

The discrepancy should be resolved. 

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
