### ISSUE TITLE
Missing testcase in 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by shashwatj07** [LeetCode-Feedback/LeetCode-Feedback#904]
#### Your LeetCode username

shashwatj07

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The question expects a solution of ```O(log (m+n))``` runtime complexity but my solution with ```O(m+n)``` is also being accepted.

#### Code you used for Submit/Run operation

```
class Solution {
    public double findMedianSortedArrays(int[] nums1, int[] nums2) {
        int nums[] =new int[nums1.length+nums2.length];
        
        mergeArrays(nums1, nums2, nums1.length, nums2.length, nums);
        
        double m;
        if(nums.length%2==0){
            m=(nums[nums.length/2]+nums[nums.length/2-1]);
            m/=2;
        }
        else
            m=nums[nums.length/2];
        return m;
    }
    public void mergeArrays(int[] arr1, int[] arr2, int n1, 
                                int n2, int[] arr3) 
    { 
        int i = 0, j = 0, k = 0; 
      
        while (i<n1 && j <n2) 
        { 

            if (arr1[i] < arr2[j]) 
                arr3[k++] = arr1[i++]; 
            else
                arr3[k++] = arr2[j++]; 
        } 
      
        while (i < n1) 
            arr3[k++] = arr1[i++]; 
      
        while (j < n2) 
            arr3[k++] = arr2[j++]; 
    } 
}
```

#### Language used for code

Java

#### Expected behavior

My ```O(n+m)``` solution should have received a ```Time Limit Exceeded``` verdict instead of getting accepted.

#### Additional context

Lowering the time limit and increasing the size of the input such that linear complexity solution fails will fix the problem.
I'm not providing the test case as it is pretty simple to generate and just the size of the input needs to be increased, however I'll do so if required.

**Comment by lc-ivan** [comment]
Hi @shashwatj07 ,
Thanks for reaching out to us regarding this problem! Could you please provide a test case for instance?

**Comment by shashwatj07** [comment]
Hi @lc-ivan ,
Definitely, I can provide a test case but it'll be having arrays around 10^9 integers long. This won't be feasible for the online judge to test. The easier way out will be to introduce test cases to the question. We can have 10^5 test cases and each will have an array of 10^3 (unchanged) integers long. This will make the O(m+n) solution fail.

Reason:
Roughly, we expect 10^7 to 10^8 operations in a second. To make the O(m+n) solution get TLE verdict, we must provide inputs longer than that (10^9). The solution with O(log(m+n)) will still pass easily.
Introducing 10^5 test cases with input size of 10^3 will do the trick and O(log(m+n)) will pass but not the O(m+n) one.

What do you think?

**Comment by lc-ivan** [comment]
Hi @shashwatj07 ,
Thank you for your response. I've relayed this issue to our team to investigate.

**Comment by shashwatj07** [comment]
@lc-ivan thank you!

**Comment by lc-ivan** [comment]
Hi @shashwatj07 ,
Thanks for your feedback regarding this problem. Upon review, our team noted that this is a known solution that passes but we will not be adding a test case to cause it to fail. Thank you for your time; we appreciate your valuable feedback and happy LeetCoding!
