### ISSUE TITLE
Missing Test Case - 747. Largest Number At Least Twice of Others

### ISSUE THREAD

**Issue by GuruTheCoderYoutube** [LeetCode-Feedback/LeetCode-Feedback#9040]
#### Your LeetCode username

gurusarianka 

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

There are no testcases such that: len(array) == 2 and array[greatest]/array[smallest]  < 2.

#### Code you used for Submit/Run operation

```
class Solution:
    def dominantIndex(self, array: List[int]) -> int:        
        if (len(array) == 2):
            return array.index(max(array))
        i = 0
        greatest = 0
        secondGreatest = 1
        
        while i < len(array):
            if array[i] > array[greatest]:
                secondGreatest = greatest
                greatest = i
            if array[i] > array[secondGreatest] and array[i] < array[greatest]:
                secondGreatest = i
                
            i+=1
        
        print(greatest, secondGreatest)
        if (array[secondGreatest] == 0):
            return greatest

        if (array[greatest]/array[secondGreatest]) >= 2:
            return greatest
            
        return -1
                
```

#### Language used for code

Python

#### Expected behavior

It should not have been accepted, it was.

#### Additional context

Problem encountered when doing leetcode explore/learn

Link to where I solved the problem: https://leetcode.com/explore/learn/card/array-and-string/201/introduction-to-array/1147/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We do not accept contributions where the user adds a useless if condition and asks for a test case to counter it. We appreciate your support!
