### ISSUE TITLE
Question - 1106. Parsing A Boolean Expression

### ISSUE THREAD

**Issue by Pentracchiano** [LeetCode-Feedback/LeetCode-Feedback#9043]
#### Your LeetCode username

Pentracchiano

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description of the question asserts:

> An expression can either be:
> 
> - `"t"`, evaluating to `True`;
> - `"f"`, evaluating to `False`;
> - `"!(expr)"`, evaluating to the logical NOT of the inner expression `expr`;
> - `"&(expr1,expr2,...)"`, evaluating to the logical AND of 2 or more inner expressions `expr1, expr2, ...`;
> - `"|(expr1,expr2,...)"`, evaluating to the logical OR of 2 or more inner expressions `expr1, expr2, ...`

The operations AND and OR are therefore defined to be n_ary, so accepting a number of arguments that goes from 2 to N, where N can be any integer. 
Instead, test cases include expressions that use the AND and the OR as unary operations: simple ones that are considered as valid boolean expressions are `|(t)` and `&(f)`. One test case that uses this flawed definition is test case 24: `"!(&(!(t),&(f),|(f)))"` .

#### Expected behavior

In order for the test cases to remain valid, the description should be changed, in the last 2 bullet points, to:
> - `"&(expr1,...)"`, evaluating to the logical AND of 1 or more inner expressions `expr1, ...`;
> - `"|(expr1,...)"`, evaluating to the logical OR of 1 or more inner expressions `expr1, ...`
> The logical OR and logical AND of 1 expression `expr` return the expression itself `expr`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
