### ISSUE TITLE
Minor Issue in video explanation of problem 1672. Richest Customer Wealth

### ISSUE THREAD

**Issue by skarthik7** [LeetCode-Feedback/LeetCode-Feedback#9045]
#### Your LeetCode username
skarthik7

#### Category of the bug
 Solution

#### Description of the bug
 1+9+5 = 15, not 14

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![Screen Shot 2022-09-13 at 9 15 11 AM](https://user-images.githubusercontent.com/62471766/189940260-2aaadd99-71a0-47d9-ae67-4c301cc20607.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
