### ISSUE TITLE
Missing Test Case - 393. UTF-8 Validation

### ISSUE THREAD

**Issue by p51lee** [LeetCode-Feedback/LeetCode-Feedback#9046]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code returns `True` from this invalid encoding `[192, 192, 128, 128]`.

#### Code you used for Submit/Run operation

```
class Solution:
    def validUtf8(self, data: List[int]) -> bool:
        curr = 0
        for n in data:
            head = self.getHead(n)
            if head != 69:
                curr += head
                if curr < 0:
                    return False
            else:
                return False
        if curr:
            return False
        else:
            return True
        
    def getHead(self, n: int) -> int:
        bits = "{:08b}".format(n)[-8:]
        if bits[0] == "0":
            return 0
        elif bits[:2] == "10":
            return -1
        elif bits[:3] == "110":
            return 1
        elif bits[:4] == "1110":
            return 2
        elif bits[:5] == "11110":
            return 3
        else:
            return 69
```

#### Language used for code

python

#### Expected behavior

A binary form of the missing test case is `[110xxxxx, 110xxxxx, 10xxxxxx, 10xxxxxx]`.
It is obvious that `110xxxxx` cannot come right next to `110xxxxx`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
