### ISSUE TITLE
Missing Test Case - 378. Kth Smallest Element in a Sorted Matrix

### ISSUE THREAD

**Issue by AstroMen** [LeetCode-Feedback/LeetCode-Feedback#9047]
#### Your LeetCode username

AstroMen

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The spelling mistake for the second approach.

#### Code you used for Submit/Run operation

```

```

#### Expected behavior

It shows "Inuition" in the next line of "Approach 2: Binary Search". It may be expect "Intuition".

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
