### ISSUE TITLE
Missing testcase - 1156. Swap For Longest Repeated Character Substring

### ISSUE THREAD

**Issue by escrowdis** [LeetCode-Feedback/LeetCode-Feedback#905]
#### Your LeetCode username

escrowdis

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Missing a test case: `"aaaaaaaaaaaab"` which will let the code shown below **AC**

#### Code you used for Submit/Run operation

```
using pii = pair<int, int>;

class Solution {
public:
    int maxRepOpt1(string text) {
        int sz = text.size();
        if (sz <= 1)
            return sz;
        else if (sz == 2)
            return (text[0] == text[1]) + 1;
        
        vector<pii> v[128];
        int i = 0;
        while (i < sz) {
            int j = i + 1;
            while (j < sz && text[j] == text[i]) {
                ++j;
            }
            if (i == 0 && j == sz)
                return sz;
            v[text[i]].push_back({i, j});
            i = j;
        }
        
        int res = 1;
        for (int i = 0; i < 128; ++i) {
            if (v[i].size() < 2)
                continue;
            // replace above two lines with this snippet will fix the bug
            // if (v[i].empty())
            //     continue;
            // else if (1 == v[i].size()) {
            //     res = max(res, v[i][0].second - v[i][0].first);
            //     continue;
            // }

            for (int j = 0; j < v[i].size(); ++j) {
                if (j < v[i].size() - 1 && v[i][j].second + 1 == v[i][j + 1].first) {
                    res = max(res, (2 == v[i].size() ? 0 : 1) + v[i][j].second - v[i][j].first + v[i][j + 1].second - v[i][j + 1].first);
                }
                else {
                    res = max(res, 1 + v[i][j].second - v[i][j].first);
                }
            }
        }
        
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My code got AC but it's flawed in the case `"aaaaaaaaaaaab"`. Mine returns `1`, but the correct answer should be `12`.

#### Screenshots

![Screenshot from 2020-09-01 00-33-19](https://user-images.githubusercontent.com/6340562/91798562-cd739480-ebea-11ea-9566-ee5a6832a162.png)

**Comment by lc-ivan** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @escrowdis ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @escrowdis ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
