### ISSUE TITLE
Missing Test Case - 224. Basic Calculator

### ISSUE THREAD

**Issue by pikachuuu108** [LeetCode-Feedback/LeetCode-Feedback#9050]
#### Your LeetCode username
henryluo108

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test cases `"-(-2)+4"`, which allows some wrong code to be accepted.

#### Code you used for Submit/Run operation

```
# 224. Basic Calculator
class Solution:
    def calculate(self, s):
        total = 0
        i, signs = 0, [1, 1]
        while i < len(s):
            c = s[i]
            if c.isdigit():
                start = i
                while i < len(s) and s[i].isdigit():
                    i += 1
                total += signs.pop() * int(s[start:i])
                continue
            if c in '+-(':
                signs += signs[-1] * (1, -1)[c == '-'],
            elif c == ')':
                signs.pop()
            i += 1
        return total

```

#### Language used for code
Python

#### Expected behavior

The expected answer for the case `"-(-2)+4"` should be `6`. This code is accepted although it returns `-2` on this case.

#### Screenshots

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/26197197/190034384-51afbf56-7bc3-41e6-8e71-906042b94684.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
