### ISSUE TITLE
Missing Test Case - 2236. Root Equals Sum of Children

### ISSUE THREAD

**Issue by DannyJoris** [LeetCode-Feedback/LeetCode-Feedback#9051]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

1. There is no type checking. Removing any of the types doesn't change the outcome of the test.
2. TypeScript highlighting not fully supported

#### Code you used for Submit/Run operation

1. This example suggests that many of the values can be `null`, but the tests don't check for that. You can write code assuming `root.left.val` will always exist and all tests will pass. I would love to see type errors highlighted in the editor. It makes choosing TypeScript useless, unless you paste your code into https://www.typescriptlang.org/play first, which I will do going forward.

```
/**
 * Definition for a binary tree node.
 * class TreeNode {
 *     val: number
 *     left: TreeNode | null
 *     right: TreeNode | null
 *     constructor(val?: number, left?: TreeNode | null, right?: TreeNode | null) {
 *         this.val = (val===undefined ? 0 : val)
 *         this.left = (left===undefined ? null : left)
 *         this.right = (right===undefined ? null : right)
 *     }
 * }
 */

function checkTree(root: TreeNode | null): boolean {

};
```

#### Language used for code

TypeScript

#### Additional context

Additionally regular syntax highlighting for TypeScript is either buggy or broken. Compare these 2 highlights for example. I removed `: boolean` from the second example and the variable highlighting returns back to normal.

![Screen Shot 2022-09-13 at 11 45 51 PM](https://user-images.githubusercontent.com/110365/190047217-96455bef-4d70-42ac-bb2d-1933aa161328.png)

![Screen Shot 2022-09-13 at 11 45 59 PM](https://user-images.githubusercontent.com/110365/190047229-367ac945-14ba-470d-a308-652539f9caa8.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
