### ISSUE TITLE
1784. 检查二进制字符串字段 题目描述错误

### ISSUE THREAD

**Issue by cjl0222** [LeetCode-Feedback/LeetCode-Feedback#9052]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
qing-feng-fei-yu

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目的示例1的解释错误，具有严重误导性。

原题错误描述：
输入：s = "1001"
输出：false
解释：字符串中的 1 没有形成一个连续字段。

正确描述：
输入：s = "1001"
输出：false
解释：字符串中的 1 形成了两个连续字段，而不是0个或1个，因此为false。

**Comment by feiceh** [comment]
你好，当前题面已更新，ID：qing-feng-fei-yu 给予积分奖励，请查收。
