### ISSUE TITLE
Missing Test Case or Constraint Statement review - 682. Baseball Game - not all edge cases covered

### ISSUE THREAD

**Issue by gega27** [LeetCode-Feedback/LeetCode-Feedback#9053]
gega27

#### Category of the bug
- [ ] Question
#### Or the
- [ ] Solution
- [ ] Missing Test Cases 
in case the constraint statement is correct.

#### Description of the bug

HI 
extending the issue and provided answer on missing edge cases: 
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8966
I suppose that the constraints statement could be misinterpreted a bit.

would kindly suggest to add a bit correction, just worth to mention it for your attention:
original statement:
`Return the sum of all the scores on the record. The test cases are generated so that the answer fits in a 32-bit integer.'
`
would recommended to have something similar to this:
`
...
cases are generated so that the answer and "any intermediate values generated based on ops records" fits in 32bit integer"
`

e. g. value may become int64 /biginteger in the middle of calculation, and get back to 32bit at the end.. 

for the test cases, one of the simplest would be to add enough "C" elements to the above test cases mentioned by me (the need to be exteneded as well by "D" at least 33 times nore to the end of the ops array to make the answer 32bit, but require internediate values to be stored in biginteger:

string[] ops = {"100", 
"D", ", ......  "D", "D", "D", "D", "D" (33+ TIMES)
"C", ", ......  "C", "C", "C", "C", "C"  (33+ TIMES)

};

p.s. and thx for the answer on previous issue, I still cant understand how I missed that constraint statement regarding "answer fits 32bit".

#### Language used for code

c#

#### Expected behavior

would throw an arith overflow for middle edge case (not the "Answer value", but middle calculations) in case the statement is allowing intermediate values to be bigger then 32bit.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
