### ISSUE TITLE
1457. Pseudo-Palindromic Paths in a Binary Tree

### ISSUE THREAD

**Issue by vdm4k** [LeetCode-Feedback/LeetCode-Feedback#9054]
#### Your LeetCode username

vdm4k

#### Category of the bug
- [ ] Question

#### Description of the bug

From my point of view this sentence not correct -
**Return the number of pseudo-palindromic paths going from the root node to leaf nodes.**

because we must return palindromic and pseudo-palindromic paths

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
