### ISSUE TITLE
剑指 Offer 09. 用两个栈实现队列 示例1不一致

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#9056]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 题目

**描述**
1. `题目中的示例1`与`填入示例的示例1`不一致
2. 该题与主站232题相同？

**期望行为**
1. 示例1保持一致
2. 题目描述添加以下说明：
注意：本题与主站 232 题相同：https://leetcode.cn/problems/implement-queue-using-stacks/

**屏幕截图**
![image](https://user-images.githubusercontent.com/25954059/190154691-5412a357-812a-4e59-a055-0b4fef11b9c5.png)

**额外的上下文**
[题目链接](https://leetcode.cn/problems/yong-liang-ge-zhan-shi-xian-dui-lie-lcof/)

**Comment by feiceh** [comment]
你好，当前题面已更新，ID：hhummingg 给予积分奖励，请查收。
