### ISSUE TITLE
Small Typo in Description - 883. Projection Area of 3D Shapes

### ISSUE THREAD

**Issue by vmarunin** [LeetCode-Feedback/LeetCode-Feedback#9058]
vmarunin

#### Category of the bug
- [+] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

2 Planes with name 'x', no one with name 'z'

<img width="818" alt="Снимок экрана 2022-09-14 в 16 24 06" src="https://user-images.githubusercontent.com/10003837/190166638-ca2027c7-b30d-4168-a569-274c6f28c977.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The planes are not named 'x'. Those are the coordinate axes
The name of the other axes is mentioned in the left of each diagram. We appreciate your support!
