### ISSUE TITLE
Missing Test Case - 1770. Maximum Score from Performing Multiplication Operations

### ISSUE THREAD

**Issue by nqdai1992** [LeetCode-Feedback/LeetCode-Feedback#9065]
#### Your LeetCode username
nguyendai1992

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I can not resolve the problem with the same solution in the solution tab. I tried using the same test case it is ok when running code but fail when submit

#### Code you used for Submit/Run operation

```
function dp (nums: number[], multipliers: number[], memo={}, left, op) {
  if (op === multipliers.length) {
    return 0
  }
  const n = nums.length;
  const right = n - 1 - op + left
  
  if (memo[op][left] !== undefined) return memo[op][left]
  
  const leftResult = nums[left] * multipliers[op] + dp(nums, multipliers, memo, left + 1, op + 1)
  const rightResult = nums[right] * multipliers[op] + dp(nums, multipliers, memo, left, op + 1)
  
  memo[op][left] = Math.max(leftResult, rightResult)
 
 return memo[op][left]
}

function maximumScore(nums: number[], multipliers: number[]): number {
  const memo = Array(multipliers.length + 1).fill(null).map(() => Array(nums.length + 1))
  const left = 0
  const op = 0
  
  return dp(nums, multipliers, memo, left, op)
};
```

#### Language used for code
Typescript

#### Screenshots

![Screen Shot 2022-09-15 at 09 32 47](https://user-images.githubusercontent.com/19273325/190299838-8f034862-2f52-45bb-83c9-e61ec0f9c84f.png)

![Screen Shot 2022-09-15 at 09 35 06](https://user-images.githubusercontent.com/19273325/190300129-05c109f5-d031-4763-a28a-b69fd805f907.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

Other factors that go into this number include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy. If it starts seeming bad or lacking logic, please feel free to reach out and share some of the problems you've seen so we can look to investigate.

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
