### ISSUE TITLE
672. 灯泡开关 Ⅱ 题目示例解释错误 是今天的每日一题！！！

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#9067]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 题目

**描述**
示例3的解释不对。

**期望行为**
交换示例3中开关2和开关3的结果。

**屏幕截图**
![image](https://user-images.githubusercontent.com/25954059/190344072-c2d84e55-5b49-4aa3-b331-d190ca1d9fb7.png)

**额外的上下文**
链接：https://leetcode.cn/problems/bulb-switcher-ii/

**Comment by feiceh** [comment]
你好，当前题面已更新，ID：hhummingg 给予积分奖励，请查收。
