### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by mohamedmm9** [LeetCode-Feedback/LeetCode-Feedback#9069]
class Solution(object):
    def removeDuplicates(self, nums):
        res=list(set(nums))
        [res] 

this solution will give a valid answer but it doesn't in leet code compiler and I don't know why

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
