### ISSUE TITLE
#141 Linked List Cycle

### ISSUE THREAD

**Issue by prakhar-praveen** [LeetCode-Feedback/LeetCode-Feedback#907]
The question [https://leetcode.com/problems/linked-list-cycle/](url) I would like to dispute the correctness of is #141 (Linked List Cycle). The question description says there would be two arguments, viz. ListNode head and int pos, in the solution function, although the pre-defined solution function takes in only one argument, viz. ListNode head. Surprisingly, the test cases use two arguments, therefore making it impossible to pass all test cases, even though the code entered is correct.

The official leetcode solution and the description have a big inconsistency too. Due to this situation, it is extremely unfair to penalize users for submitting correct answers. Please remove all the "unaccepted" submissions, as the submissions I made were 100% correct.

**Comment by lc-pam** [comment]
Hi @prakhar-praveen ,
Looks like you've submitted the same request to our help desk. I'll close the ticket here and continue our conversation in the help desk ticket.
