### ISSUE TITLE
[ 题目表述不清+官方题解有问题 ] 180. 连续出现的数字

### ISSUE THREAD

**Issue by RaySForever** [LeetCode-Feedback/LeetCode-Feedback#9070]
**你的 LeetCode 用户名**
[RaySForever](https://leetcode.cn/u/raysforever/)

**Bug 类型**
- [x] 题目
- [x] 题解

**描述**

### 题目表述不清
原题第一句为“编写一个 SQL 查询，查找所有至少连续出现三次的数字。”
此处“连续”按照[官方题解](https://leetcode.cn/problems/consecutive-numbers/solution/lian-xu-chu-xian-de-shu-zi-by-leetcode/)是指“连续出现的意味着相同数字的 Id 是连着的”，但在下面测试用例中有连续出现的数字[96, 26], [97, 26], [99, 26], [100, 26]以及[798, 4], [799, 4], [801, 4], [802, 4]由于其 Id 不是连续的，就没有被计算在内。那么连续就必然指 Id 是连续的吗？

### 官方题解有问题
依据官方题解的意思，至少有三次相同的数字的 Id 是连续的，那么有最后一个[测试用例](https://leetcode.cn/submissions/detail/363274284/testcase/)：
![测试例](https://user-images.githubusercontent.com/103828206/190419325-4af70e33-cad0-423e-bd1b-3bc3e0481e45.png)
其中至少有第四行的[81, 32], [82, 32], [83, 32]（在[11],[17]之间）与第十四行的[318, 23], [319, 23], [320, 23]（在[45],[4]之间）之类的符合官方题解的意思的连续的数字**不在**官方题解的解答（预期结果）中：
{"headers":["ConsecutiveNums"],"values":[[39],[32],[42],[8],[11],[17],[0],[15],[44],[23],[27],[38],[25],[36],[35],[7],[1],[45],[4],[18],[20],[14],[24],[31],[30],[47],[2],[26],[6],[5],[33],[41],[16],[48],[29],[22],[43],[13]]}

另外，我在自己电脑上（MySQL 5.7）复刻了该测试用例与官方题解，得出的结果与官方题解的解答（预期结果）竟然一致，不知道为什么会将[81, 32], [82, 32], [83, 32]这类数字排除出答案。

------

**你使用的语言**
SQL（MySQL）

**你提交或者运行的代码**
```
// 官方题解
SELECT DISTINCT
    l1.Num AS ConsecutiveNums
FROM
    Logs l1,
    Logs l2,
    Logs l3
WHERE
    l1.Id = l2.Id - 1
    AND l2.Id = l3.Id - 1
    AND l1.Num = l2.Num
    AND l2.Num = l3.Num
;
// 我的题解，按照原表插入顺序来判断连续出现的数字
SELECT t.num ConsecutiveNums
FROM
(
	SELECT l.*,IF(@par_num=l.num,@par_row:=@par_row+1,@par_row:=1) row_num, 
	(@row:=@row+1) "row",@par_num:=l.num
	FROM logs l,(SELECT @par_row:=0,@par_num:=NULL,@row:=0) r
	ORDER BY l.id,l.num
) t
GROUP BY (t.row-t.row_num),t.num
HAVING COUNT(*)>=3
```
**期望行为**
清晰表述题目中“连续”的定义，以及解决官方题解不能正确解答最后一个测试用例

**额外的上下文**
链接：https://leetcode.cn/problems/consecutive-numbers/

**Comment by feiceh** [comment]
您好，在与相关团队核实后：此题解答案没有去重。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
