### ISSUE TITLE
2007. Find Original Array From Doubled Array: Test cases violate constraints

### ISSUE THREAD

**Issue by chillleader** [LeetCode-Feedback/LeetCode-Feedback#9072]
#### Your LeetCode username
chillleader

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Invalid Test Cases 

#### Description of the bug
In problem 2007, the description mentions that `0 <= changed[i] <= 10^5`.

The solution below uses an array of size `10^5 + 1` to store the count of each number. It fails because some test cases apparently feed it with numbers greater than 10^5 (e.g. I encountered 100002).
The same solution modified not to rely on this constraint passes.

#### Code you used for Submit/Run operation

```
// 2007. Find Original Array From Doubled Array
class Solution {
    public int[] findOriginalArray(int[] changed) {
        int[] result = new int[changed.length / 2];
        if (changed.length % 2 != 0) return new int[0];
        int[] used = new int[changed.length / 2];
        
        int[] contains = new int[100001];
        
        Arrays.sort(changed);
        for (int i = 0; i < changed.length; i++) {
            contains[changed[i]]++;
        }
        
        int curPointer = 0;
        int count = 0;
        
        while (curPointer < changed.length && count < changed.length / 2) {
            int curNum = changed[curPointer];
            if (contains[curNum] <= 0) {
                curPointer++;
                continue;
            }
            else contains[curNum]--;
            
            if (contains[curNum * 2] > 0) {
                contains[curNum * 2]--;
                result[count] = curNum;
                count++;
            }
            curPointer++;
        }
        if (count == changed.length / 2) return result;
        else return new int[0];
    }
}
```

#### Language used for code
Java

#### Expected behavior
Test cases should pass, since the constraints section of the problem statement clearly highlights that `0 <= changed[i] <= 10^5`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. There is an issue in line 26 of your code, which uses "curnum*2"
The testcases are correct.
We appreciate your support!
