### ISSUE TITLE
Constraint not Clear - 50. Pow(x, n)

### ISSUE THREAD

**Issue by hhmmak** [LeetCode-Feedback/LeetCode-Feedback#9074]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description nor the constrain indicated that the parameter "n" (the exponent) is an integer. In real life, the exponent can be a decimal (floating number).
It is not significant while using languages that separates int and float (e.g. C++/Java) as it is defined with parameter definition in the coding area. But for languages that does not (e.g. Javascript/ Python), the question description will appear to be unclear.

#### Language used for code

Javascript

#### Screenshots

![Screen Shot 2022-09-15 at 14 09 53](https://user-images.githubusercontent.com/100734684/190509308-5e8f3ee7-cb7d-4835-ad74-f96004bd4d47.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
