### ISSUE TITLE
453. Minimum Moves to Equal Array Elements. Approach #3 Typo

### ISSUE THREAD

**Issue by EhanDuan** [LeetCode-Feedback/LeetCode-Feedback#9075]
#### Your LeetCode username

Anpu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a typo in Approach#3 of the solution. The variable in the red box should be `n` instead of `i`

#### Code you used for Submit/Run operation

```
Just change i into n
```

#### Screenshots

<img width="650" alt="image" src="https://user-images.githubusercontent.com/75397936/190528815-7991e884-4d3c-4fd6-b030-c837151dc2aa.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
