### ISSUE TITLE
Missing Test Case - 596. Classes More Than 5 Students

### ISSUE THREAD

**Issue by ebram96** [LeetCode-Feedback/LeetCode-Feedback#9077]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There's not test case to fail checks that are less than 5 and more than 1

#### Code you used for Submit/Run operation

```
SELECT class
FROM
(
    SELECT class, COUNT(class) AS 'count'
    FROM Courses
    GROUP BY class
) AS counts
WHERE count > 1
;
```

#### Language used for code

SQL

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ebram96** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The language you submitted to reach this result.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

SQL

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
