### ISSUE TITLE
[TLE] 1770. Maximum Score from Performing Multiplication Operations

### ISSUE THREAD

**Issue by IchiruTake** [LeetCode-Feedback/LeetCode-Feedback#9079]
Using the same algorithm, C++ did not get TLE whilst Python did. I think it is worth to remove some redundant, over time-extreme test cases in different languages, or extend the TLE for some specific problems on weak performance languages by scaling. For example, the TLE threshold for Python should by 5-7 times higher than C++ rather than equal.

``` C++
class Solution {
public:
    int maximumScore(vector<int>& nums, vector<int>& multipliers) {
        vector<vector<int>> dp(multipliers.size()+1,vector<int>(multipliers.size()+1,0));
        for (int i=multipliers.size()-1;i>=0;i--) {
            for (int j=multipliers.size()-i-1;j>=0;j--) {
                int s=nums[i]*multipliers[i+j]+dp[i+1][j];
                int e=nums[nums.size()-j-1]*multipliers[i+j]+dp[i][j+1];
                dp[i][j]=max(s,e);
            }
        }
        return dp[0][0];
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The submission TLE link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by IchiruTake** [comment]
https://leetcode.com/submissions/detail/800933235/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The code received Accepted when we test it.  We appreciate your support!
https://leetcode.com/submissions/detail/802681749/
