### ISSUE TITLE
949. Largest Time for Given Digits

### ISSUE THREAD

**Issue by EeeasyBreezy** [LeetCode-Feedback/LeetCode-Feedback#908]
#### Your LeetCode username

EeeasyBreezy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Undefined behaviour during custom test cases:

1. It seems that there is no input control in the back-end. 

For input `[2,0, 12,12]` expected answer is `"12:32"` despite that there is condition that says that `0 <= A[i] <= 9`.

2. The task itself is not accurate enough.
Input `[2, 2, 0, 0]` gives `"22:00"` as a result, but the largest time string we can construct here is `"22:22"` since there is no limitation to how many times we can use each element of the array. 

#### Code you used for Submit/Run operation
Used a stub for running through several test cases.
```
public class Solution {
    public string LargestTimeFromDigits(int[] input) 
    {
        return string.Empty;
    }
}
```

#### Language used for code
C#

#### Expected behavior

1. Input control: throw an exception, when input array contains at least one element, that does not meet specified condition 
`0 <= A[i] <= 9`.

2. Make initial problem more accurate targeting that each element of the input array can be used only once. Otherwise, change the ethalon solution in a way it can use each element of the array any number of times.

**Comment by lc-ivan** [comment]
Hi @EeeasyBreezy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @EeeasyBreezy ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
