### ISSUE TITLE
672题 样例

### ISSUE THREAD

**Issue by fatesealed** [LeetCode-Feedback/LeetCode-Feedback#9080]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
热水袋

**Bug 类型**
- [x] 题目
- [ ] 编程语言
- [ ] 缺少测试用例
- [ ] 题解

**描述**
样例3描述有误 按1次咋会出现 [开,开,开] 这种情况
**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
![image](https://user-images.githubusercontent.com/32084642/190552759-8854cd3b-8dcd-4518-b06b-28b1e29be08b.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by fatesealed** [comment]
leetcode-cn.com/u/re-shui-dai/

**Comment by feiceh** [comment]
好滴，ID： re-shui-dai 给予积分奖励，请查收。
