### ISSUE TITLE
Incorrect description 1770. Maximum Score from Performing Multiplication Operations

### ISSUE THREAD

**Issue by Satyamrawat2048** [LeetCode-Feedback/LeetCode-Feedback#9081]
#### Your LeetCode username
satyamrawat2048 

#### Category of the bug
- [1] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question 1770. Maximum Score from Performing Multiplication Operationsit is mentioned that it is a 1 indexed array but actually it is a 0 indexed array

#### Code you used for Submit/Run operation

```
// 1770. Maximum Score from Performing Multiplication Operations
class Solution {
public:
   int rec(int s,int e,int i,vector<int>&v,vector<int>&mul){
        if(i==mul.size())return 0;
        if(s==e) return v[s]*mul[i] ;
        
        int spick= -1e9,epick= -1e9 ;
        
        spick= v[s]*mul[i]+ rec(s+1,e,i+1,v,mul) ;
        epick= v[e]*mul[i]+ rec(s,e-1, i+1,v,mul) ;
        
        return max(spick,epick) ;    }
    
    int maximumScore(vector<int>&v, vector<int>& mul) {
        return rec(0,v.size()-1,0 , v,mul);
        return 1; 
    }
};
```

#### Language used for code
 C++ 

![Screenshot (236)](https://user-images.githubusercontent.com/78161825/190561481-b0e58695-156f-4b90-8b57-93a5c1ed1292.png)

#### Expected behavior
 When I traverse as per 1 based indexing I am getting wrong answer , but 0 based indexing gives right answer

#### Screenshots
![Screenshot (236)](https://user-images.githubusercontent.com/78161825/190561549-d96ee4d4-1c0a-447e-8b90-248399f8da02.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've made minor edits to the statement We appreciate your support!

**Comment by Satyamrawat2048** [comment]
Sir/ Ma'am,
As my edit to the question description 1770. Maximum Score from Performing
Multiplication Operations (Issue #9081)   has been approved will i get 100
leetcoins as mentioned below (because I have not received them yet)
[image: Screenshot 2022-09-26 122045.png]
