### ISSUE TITLE
Missing Test Case - 1770. Maximum Score from Performing Multiplication Operations

### ISSUE THREAD

**Issue by dashkin-dima** [LeetCode-Feedback/LeetCode-Feedback#9083]
#### Your LeetCode username
dimadashkin

#### Category of the bug
- [ ] Solution

#### Code you used for Submit/Run operation

```
//Maximum Score from Performing Multiplication Operations
var maximumScore = function(nums, multipliers) {
    const numsSort = nums.sort((a, b) => a - b);
    const multipliersSort = multipliers.sort((a, b) => a - b);
    
    const findPositive = (array) => array.reduce((acc, value) => value > 0 ? acc + 1 : acc, 0);
    
    
    let score = 0;
    
    let np = findPositive(numsSort)
    let ms = findPositive(multipliersSort);
    
    while(numsSort.length && multipliersSort.length) {
        const n = numsSort.pop();
        const m = multipliersSort.pop();
        np -= 1;
        ms -= 1;
        
        if(np || ms) {
            numsSort.reverse();
            multipliersSort.reverse();
        }
        
        console.log(n, m)
        
        score += n * m;
        

    }
    
    return score;
};
```

#### Expected behavior
testcase (9 test)
[-5,-3,-3,-2,7,1]
[-10,-5,3,4,6]

answer in leetcode - 102 
my anser - 105

how I group
nums / multipliers
7 6
-5 -10
1 4
-3 -5
-2 3

and sum of this = 105, it is Maximum Score(105 more than 102)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by dashkin-dima** [comment]
Language used for code - js

**Comment by dashkin-dima** [comment]
i'm dumb, I didn't read it right
