### ISSUE TITLE
1987. Number of Unique Good Subsequences - wrong test results

### ISSUE THREAD

**Issue by sameer-narang** [LeetCode-Feedback/LeetCode-Feedback#9086]
the test case 

"1100100010101010100100000111110001111001000010000010" correctly shows:

881,654,252
as the number of unique good subsequences. However, if you append a 0 to the test input and make it:

"11001000101010101001000001111100011110010000100000100",

the expected output actually goes __down__ to:

190,631,050

the expected test case results are incorrect for this problem

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
