### ISSUE TITLE
Improve Testcase Memory Bound - 1770. Maximum Score from Performing Multiplication Operations

### ISSUE THREAD

**Issue by Mestrace** [LeetCode-Feedback/LeetCode-Feedback#9087]
#### Your LeetCode username

[monte_carrrrrlo](https://leetcode.com/monte_carrrrrlo/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Trying to implement a recursive solution with memo but failed to allocate memory for memo array.

The solution is similar to the `Approach 2: Recursive Dynamic Programming` however hits a memory bound. 

#### Code you used for Submit/Run operation

```
func maximumScore(nums []int, multipliers []int) int {
    memo := make([][]*int, len(nums) + 1)
    for i := range memo {
        memo[i] = make([]*int, len(multipliers))
    }
    
    return dp(nums, multipliers, 0, 0, memo)
}


func dp(nums, mult []int, i, left int, memo [][]*int) int {
    if i == len(mult) {
        return 0
    }
    
    if memo[i][left] != nil {
        return *(memo[i][left])
    }
    
    right := len(nums) - i + left - 1
    
    l := nums[left] * mult[i] + dp(nums, mult, i + 1, left + 1, memo)
    r := nums[right] * mult[i] + dp(nums, mult, i + 1, left, memo)
    
    result := max(l, r)
    
    memo[i][left] = &result
    
    return result
}

func max(i, j int) int {
    if i > j {
        return i
    }
    return j
}
```

#### Language used for code

Golang

#### Expected behavior

Solution with O(M^2) memory bound should be accepted.

#### Screenshots

<img width="721" alt="截屏2022-09-16 下午11 11 02" src="https://user-images.githubusercontent.com/26028388/190672008-c9351e07-3f1b-4091-823a-31129528ff36.png">

#### Additional context

Test case: https://leetcode.com/submissions/detail/801318459/testcase/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've fixed the TL issues. We appreciate your support!
