### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by minusung** [LeetCode-Feedback/LeetCode-Feedback#9088]
#### Your LeetCode username 
minusung

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The first example shows the tail connecting to the second node (1-indexed) in the diagram, but the text explanation states that the tail connects to the 1st node (0-indexed).

#### Code you used for Submit/Run operation

```
N/A
```

#### Expected behavior

The description and example diagram are consistent in conveying which node the tail connects to.

#### Screenshots

<img width="812" alt="Screen Shot 2022-09-15 at 10 02 24 PM" src="https://user-images.githubusercontent.com/76793546/190540521-827898d9-6c8c-484f-98f6-4aac6099e130.png">

**Comment by stormsunshine** [comment]
The graph and the explanation are consistent when using 0-indexed. In example 1, node 3 is the 0th node and node 2 is the 1st node. Is there any problem?
