### ISSUE TITLE
Submission for Mock Interviews do not appear in the most recent submission tab on the profile page

### ISSUE THREAD

**Issue by MaksymKarunos** [LeetCode-Feedback/LeetCode-Feedback#909]
#### Your LeetCode username

maksymKarunos

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Submission for Mock Interviews do not appear in the most recent submission tab on the profile page
#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A
#### Expected behavior

N/A
#### Screenshots

N/A

#### Additional context

N/A

**Comment by lc-pam** [comment]
Hi @MaksymKarunos ,
GitHub repo is for content-related issues only. If you need technical support, please submit a ticket to LeetCode's help desk [here](https://support.leetcode.com/hc/en-us/requests/new). Thank you!
