### ISSUE TITLE
850. 矩形面积 II 中文题目有误

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#9091]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 题目

**描述**
题目翻译成中文出错

**期望行为**
与英文保持一致，`[x1, y1, x2, y2]`、`（x1，y1）`、`(xi1, yi1) `、` (xi2, yi2) `符号不一致。
对于 rectangle[i] = [x1, y1, x2, y2]，其中（x1，y1）是矩形 i 左下角的坐标， (xi1, yi1) 是该矩形 左下角 的坐标， (xi2, yi2) 是该矩形 右上角的坐标。

**屏幕截图**
**中文题目**
![image](https://user-images.githubusercontent.com/25954059/190835472-0bb0b0e0-8b41-4eb4-8e8d-4703c6630843.png)
**英文题目**
![image](https://user-images.githubusercontent.com/25954059/190835488-5e494627-9f69-4835-b966-d5fb784dae31.png)

**额外的上下文**
链接：https://leetcode.cn/problems/rectangle-area-ii/

**Comment by feiceh** [comment]
你好，当前题面已更新，ID：hhummingg 给予积分奖励，请查收。
