### ISSUE TITLE
GETTING TLE WITH ALL APPROACHES- 146. LRU Cache

### ISSUE THREAD

**Issue by theomkumar** [LeetCode-Feedback/LeetCode-Feedback#9093]
#### Your LeetCode username

theomkumar

#### Category of the bug
- [ ] Solution

#### Description of the bug

I tried many approaches, including those from the discussion forum but **all approaches are giving TLE**, the same codes used to run before without any issues.

#### Code you used for Submit/Run operation

```
// LRU Cache
class LRUCache {
public:
    class node{
        public:
        int k;
        int v;
        node *prev;
        node *next;
        node(int kk,int vv){
            k=kk;
            v=vv;
        }
    };
    
    node* head=new node(-1,-1);
    node* tail=new node(-1,-1);
    
    
    int cap;
    unordered_map<int,node*> m;
    
    LRUCache(int capacity) {
        cap=capacity;
        head->next=tail;
        tail->prev=head;
    }
    
    void insertNode(node* newNode){
        node* temp=head->next;
        newNode->next=temp;
        newNode->prev=head;
        head->next=newNode;
        temp->prev=newNode;
    }
    
    void deleteNode(node* delNode){
        node* delPrev=delNode->prev;
        node* delNext=delNode->next;
        delPrev->next=delNext;
        delNext->prev=delPrev;
    }
    
    int get(int key) {
        if(m.find(key)!=m.end()){
            node* resNode=m[key];
            int res=resNode->v;
            m.erase(key);
            deleteNode(resNode);
            insertNode(resNode);
            m[key]=head->next;
            return res;
        }
        return -1;
    }
    
    void put(int key, int value) {
        if(m.find(key)!=m.end()){
            node* exitingNode = m[key];
            m.erase(key);
            deleteNode(exitingNode);
        }
        if(m.size() == cap){
            m.erase(tail->prev->k);
            deleteNode(tail-> prev);
        }
        insertNode(new node(key,value));
        m[key]=head->next;
    }
};
```

#### Expected behavior

It should pass all the test cases, as it passed for all old users.

#### Additional context

20 / 22 test cases passed.
TRY YOURSELF! 
I tried so many approaches getting TLE in all.

SUBMISSION (ACCEPTED)
https://leetcode.com/submissions/detail/799863707/

GETTING TLE
https://leetcode.com/submissions/detail/801771892/

FOR THE SAME CODES!

**Comment by theomkumar** [comment]
SUBMISSION (ACCEPTED)
https://leetcode.com/submissions/detail/799863707/

GETTING TLE
https://leetcode.com/submissions/detail/801771892/

FOR THE SAME CODES!

**Comment by theomkumar** [comment]
Now it passed, 
https://leetcode.com/submissions/detail/802645864/

**Comment by LC-Pam** [comment]
Thank you for contacting LeetCode's Support Team.

Your submission is resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

Please note that the test case you see on the "details" page shows which test case the program stops running at when the time limit has exceeded; it's not a test case that causes your program to exceed the time limit. 

I'd recommend checking out accepted submissions from the discuss tab of the problem page or posting your code there to get support from other users. Unfortunately, we do not disclose the time limit as we want our users to debug and improve their code to get it accepted. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
