### ISSUE TITLE
Missing Test Case - 336. Palindrome Pairs

### ISSUE THREAD

**Issue by JacksonMei** [LeetCode-Feedback/LeetCode-Feedback#9095]
#### Your LeetCode username

jacksonmei

#### Category of the bug
- [✔ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

```
Example 1:

Input: words = ["abcd","dcba","lls","s","sssll"]
Output: [[0,1],[1,0],[3,2],[2,4]]
Explanation: The palindromes are ["dcbaabcd","abcddcba","slls","llssssll"]
```
The first two output palindromes should be ["abcddcba", "dcbaabcd"]  but not  ["dcbaabcd","abcddcba"]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've fixed issue.  We appreciate your support!
