### ISSUE TITLE
TLE Java Approach 2 - 336. Palindrome Pairs

### ISSUE THREAD

**Issue by kirooha** [LeetCode-Feedback/LeetCode-Feedback#9097]
#### Your LeetCode username

kirooha

#### Category of the bug
- [x] Solution
- [x] Language
- [x] Existing Test Cases 

#### Description of the bug

Got TLE for Java solution from the article. Just copy/paste the official solution (Approach 2). The same with rewritten solution in C++.
 
#### Code you used for Submit/Run operation

Just copy/paste the official solution (Approach 2)

#### Language used for code
Java, C++

#### Expected behavior

Accepted solution

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've check your feedback to the problem. TLE was probably due to transient problem. We appreciate your support!
