### ISSUE TITLE
Missing Test Case - 326. Power of Three

### ISSUE THREAD

**Issue by muller2333** [LeetCode-Feedback/LeetCode-Feedback#9099]
#### Your LeetCode username

muller2333

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
2069870691

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isPowerOfThree(int n) {
        if(n<=0){
            return false;
        }
        if(n==1){
            return true;
        }
        if(n%3>0){
            return false;
        }
        int num=1;
        while(num<n){
            num*=3;
        }
        return num==n;
    }
}
```

#### Language used for code

Java

#### Screenshots

![AQL Y~J}{{V(PV1IO2I{80G](https://user-images.githubusercontent.com/25950952/190857834-e0847e19-b889-405c-ab61-6cafaafb4ae4.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to add the testcase. We appreciate your support!

**Comment by muller2333** [comment]
Why don’t I get 100 LeetCoins as the reward?
发件人: ***@***.***>
发送时间: 2022年9月23日 5:04
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 326. Power of Three (Issue #9099)


Thank you for your time. We've used your feedback to add the testcase. We appreciate your support!

―

**Comment by muller2333** [comment]
@LC-Pam Why don't I get 100 coins as a reward?
