### ISSUE TITLE
关于不能对题目点踩的问题

### ISSUE THREAD

**Issue by zhule0601** [LeetCode-Feedback/LeetCode-Feedback#91]
** Bug 类型**
- [ 6 ] 题目

**描述**
题目只能点赞，不能点踩

**你使用的语言**
C++

**你提交或者运行的代码**

**期望行为**
对每一道题都应该开发式的交给用户去评分，只能点赞的话，不能让用户直观的避坑。

**屏幕截图**
中文网站：
![image](https://user-images.githubusercontent.com/23112609/78086379-56925f80-73f0-11ea-96d5-476d9ceb9723.png)

英文网站：
![image](https://user-images.githubusercontent.com/23112609/78086345-395d9100-73f0-11ea-9e3f-d06df300e310.png)

**Comment by feiceh** [comment]
非常感谢您的反馈，我们会在后期的版本中不断优化和提升我们的产品，给大家带来最佳的用户体验。Github 仓库主要用于收集大家在本站学习过程中遇到的题目和题解 BUG，使用中有其他的建议您可提交工单（https://support.leetcode-cn.com/hc/request/new/） 反馈处理喔～
