### ISSUE TITLE
Sample Test Case not provided in 872. Leaf-Similar Trees

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#910]
#### Your LeetCode username

Mkay6122

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Sample Test Case not provided in 872. Leaf-Similar Trees**
Question is quiteeasy but it will be more understandable and clear if you provide a sample test case in this question.
#### Code you used for Submit/Run operation

```
//  Leaf-Similar Trees
class Solution {
public:
    void solve(TreeNode* t1, vector < int > &aa){
        if (!t1) return  ; 
        if (!t1->left and !t1->right) aa.push_back(t1->val) ;
        if (t1->left) solve(t1->left, aa) ;
        if (t1->right) solve (t1->right, aa) ;
    }
    bool leafSimilar(TreeNode* root1, TreeNode* root2) {
        vector < int> a ;
        solve(root1, a) ;
        vector <int > b ;
        solve(root2, b) ;
        return (a == b) ;
    }
};
```

#### Language used for code
 C++

**Comment by lc-pam** [comment]
Hi @Mohitkumar6122 
Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by Mohitkumar6122** [comment]
> Hi @Mohitkumar6122
> Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

Thanks..... !

**Comment by lc-pam** [comment]
Hi @Mohitkumar6122 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
