### ISSUE TITLE
Missing Test Case - 96. Unique Binary Search Trees

### ISSUE THREAD

**Issue by palkesh06** [LeetCode-Feedback/LeetCode-Feedback#9101]
#### Your LeetCode username

Username : palkeshjain06

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

Missing Test Cases 
#### Description of the bug

There are test cases missing for n can range from [1,19] but we can add more test cases where n can range from [1,100]

#### Code you used for Submit/Run operation

```
class Solution
{
    public:
    cpp_int findCatalan(int n) 
    {
        cpp_int dp[n+1]; 
        dp[0]=1,dp[1]=1;
        for ( int i = 2 ; i <=n ; i++){
            cpp_int x = 0 ; 
            for ( int  j = 0 ; j <i; j++){
                x+= dp[j]*dp[i-j-1]; 
            }
            dp[i]=x;
        }
        return dp[n];
    }
};
```

#### Language used for code

C++

#### Expected behavior

I have expected that it will test my code for 1<=n<=100 but it only tested my code  for n <=19

**Comment by stormsunshine** [comment]
Why do you want to increase the range of n? Have you thought about that the answer will exceed a 32-bit integer if n is too large?

**Comment by LC-Pam** [comment]
Thank you for your time. Please consider stromsunshine's comment as reference. We appreciate your support!

**Comment by palkesh06** [comment]
I just want to increase the range of n for the purpose of test case so we
can think about  handling big integer case I have also mentioned my code in
the GitHub issue I have created. In java it would be little trick to handle
this case.
