### ISSUE TITLE
Missing Test Case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by manuelozada11** [LeetCode-Feedback/LeetCode-Feedback#9102]
#### Your LeetCode username

manuelozada11

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I created a script to try to get solve a question the platform gave me (check if an list of nodes is a palimdrome). I run my solution in other consoles and it is work. But if run the solution on your platform don't work. I tested the same testcases and I got different results.

#### Code you used for Submit/Run operation

```
var isPalindrome = function(head) {
    let result = true
    
    for (let i= 0; i < head.length; i++) {
        if (head[i] !== head[head.length - i - 1]) {
            result = false
        }
    }
    
    return result
};
```

#### Language used for code

Javascript

#### Expected behavior

If you try the testcase when head = [1,2] the result expected is false using the solve before. So, I got the result expected but in my console.

#### Screenshots

![image](https://user-images.githubusercontent.com/52290656/190867171-ed3ffdf5-89de-44ab-98ab-5a8e3c124321.png)
![image](https://user-images.githubusercontent.com/52290656/190867205-00aa1203-bbbf-4555-861e-9b372d2d54fe.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
