### ISSUE TITLE
[Problem Statement Issue] 348. Design Tic-Tac-Toe

### ISSUE THREAD

**Issue by Zhang-Haipeng** [LeetCode-Feedback/LeetCode-Feedback#9103]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

348. Design Tic-Tac-Toe: `return player` when the player wins is not in the problem statement. It doesn't even require checking the winning if I'm reading it correctly.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
