### ISSUE TITLE
Data Structures and Algorithms - Bug in Arrays and Strings

### ISSUE THREAD

**Issue by Barathwaja** [LeetCode-Feedback/LeetCode-Feedback#9104]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the Leetcode's Interview Crash Course - Data Structures and Algorithms; one of the example in the Two Pointers under topic Arrays and Strings has a bug.

> Example 2: Given a sorted array of unique integers and a target integer, return true if there exists a pair of numbers that sum to target, false otherwise. This problem is similar to [Two Sum](https://leetcode.com/problems/two-sum/).

In this the python code snippet the right variable uses **len(target) - 1** instead it should be **len(nums) - 1**

https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/703/arraystrings/4501/

#### Code you used for Submit/Run operation

```
// Two Sum
def check_for_target(nums, target):
    left = 0
    right = len(target) - 1

    while left < right:
        curr = nums[left] + nums[right]
        if curr == target:
            return True
        if curr > target:
            right -= 1
        else:
            left += 1
    
    return False
```

#### Language used for code

Python3

#### Expected behavior

Adding this solution  **right = len(nums)-1** will fix it.

```
def check_for_target(nums, target):
    left = 0
    right = len(nums) - 1

    while left < right:
        curr = nums[left] + nums[right]
        if curr == target:
            return True
        if curr > target:
            right -= 1
        else:
            left += 1
    
    return False
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem.  We appreciate your support!
