### ISSUE TITLE
[Missing Test Case] - 1166. Design File System

### ISSUE THREAD

**Issue by lawaloy** [LeetCode-Feedback/LeetCode-Feedback#9107]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Approach 1 proposed using Dictionary for storing path will fail for an invalid path. An example of where it failed is creating path for `'//'`. It returns `True` rather than `False` since we are checking `if len(parent) > 1` instead of `if len(parent) > 0`.

#### Code you used for Submit/Run operation
```
class FileSystem:

    def __init__(self):
        self.paths = defaultdict()

    def createPath(self, path: str, value: int) -> bool:
        
        # Step-1: basic path validations
        if path == "/" or len(path) == 0 or path in self.paths:
            return False
        
        # Step-2: if the parent doesn't exist. Note that "/" is a valid parent.
        parent = path[:path.rfind('/')]
        if len(parent) > 1 and parent not in self.paths:
            return False
        
        # Step-3: add this new path and return true.
        self.paths[path] = value
        return True

    def get(self, path: str) -> int:
        return self.paths.get(path, -1)
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Please provide us your LeetCode username.
