### ISSUE TITLE
336. Palindrome Pairs - test 136 sometimes doesn't pass even when using provided solutions (2 or 3)

### ISSUE THREAD

**Issue by nineonine** [LeetCode-Feedback/LeetCode-Feedback#9108]
I used provided solutions from the tutorial and success rate of passing all tests was ~15% - I had to submit about 7 times and it passed on last attempt.

I think the time limit value should be reconsidered.

**Comment by nineonine** [comment]
just to clarify - I am getting TLE

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
