### ISSUE TITLE
Reopening #872

### ISSUE THREAD

**Issue by Rohitesh-Kumar-Jain** [LeetCode-Feedback/LeetCode-Feedback#911]
Reopening #872  Since it is a valid test case meeting all the newly added constraints in the problem. 
Please check properly.

#### Your LeetCode username
rzay

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-ivan** [comment]
Hi @Rohitesh-Kumar-Jain ,
Thanks for reaching out to us regarding the past ticket. Upon review, we have tested your code and given test case from ticket #872, which resulted in an Invalid Testcase message. 
![Screen Shot 2020-09-04 at 3 51 30 PM](https://user-images.githubusercontent.com/68418560/92289804-ac4ec480-eec6-11ea-93ac-b9f30ae06249.png)
