### ISSUE TITLE
Missing Test Case - 2416. Sum of Prefix Scores of Strings

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#9111]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets RE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9593026/1.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    static const int maxn = 500005;
    struct Trie {
        int size;
        int trie[maxn][26];
        int val[maxn];
        queue<int> q;
        void init() {
            size = 1;
            memset(trie[0], 0, sizeof(trie[0]));
            val[0] = 0;
        }
        inline int id(char ch) { return (ch - 'a'); }
        void ins(std::string &s) {
            int i, t, u = 0;
            for (i = 0; i < s.size(); i++) {
                t = id(s[i]);
                if (!trie[u][t]) {
                    memset(trie[size], 0, sizeof(trie[size]));
                    val[size] = 0;
                    trie[u][t] = size++;
                }
                u = trie[u][t];
                val[u]++;
            }
        }
        int search(std::string &s) {
            int i, c, t, ans = 0, u = 0;
            for (i = 0; i < s.size(); i++) {
                c = id(s[i]);
                u = trie[u][c];
                ans += val[u];
            }
            return ans;
        }
    } trie;
    vector<int> sumPrefixScores(vector<string> &words) {
        trie.init();
        for (auto &word : words) trie.ins(word);
        std::vector<int> ans;
        for (auto &word : words) ans.emplace_back(trie.search(word));
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets Runtime Error.

![image](https://user-images.githubusercontent.com/11583428/190885356-1a8eff41-58ba-4464-a2e8-b0650eecc692.png)

**Comment by hqztrue** [comment]
Another code that gets TLE:
```
class TrieNode:
    def __init__(self):
        self.children = defaultdict(TrieNode)

        
class Solution:
    def sumPrefixScores(self, words: List[str]) -> List[int]:
    
        def insert(word: str) -> None:
            cur = root
            for i, ch in enumerate(word):
                cur = cur.children[ch]
                prefix2cnt[word[0: i + 1]] += 1
                
        root = TrieNode()
        prefix2cnt = defaultdict(int)
  
        for word in words:
            insert(word)
        
        n = len(words)
        res = [0 for _ in range(n)]

        for idx, word in enumerate(words):
            for i in range(len(word)):
                prefix = word[0: i + 1]
                res[idx] += prefix2cnt[prefix]

        return res
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The second code submission link since we received compile error when we test it. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by hqztrue** [comment]
This does not target the mod, it's just a set of random strings. It targets the size of the array (should set maxn>=1000000).

**Comment by yumkam** [comment]
...And in the production code that would be security issue (out-of-bound write).

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
