### ISSUE TITLE
Missing Test Case - 30. Substring with Concatenation of All Words

### ISSUE THREAD

**Issue by Y4shr4j** [LeetCode-Feedback/LeetCode-Feedback#9114]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?
