### ISSUE TITLE
Mistake in description - 493. Reverse Pairs

### ISSUE THREAD

**Issue by nineonine** [LeetCode-Feedback/LeetCode-Feedback#9119]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/8581663/190932218-1316dbd3-d6e3-45b0-a7d7-9b6a183189b8.png">

This is wrong.

Instead of "3" it has to be "5"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've fixed the issues. We appreciate your support!
