### ISSUE TITLE
Multiple Answer instead of Multiple Question in DP Quiz 1

### ISSUE THREAD

**Issue by ranggakd** [LeetCode-Feedback/LeetCode-Feedback#9120]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This issue already had already been addressed and closed in #5438 #5476 #7567 #8435  
But I propose a new perspective. In DP Quiz 1, for the first question instead of `Multiple Choice Question` it should have been `Multiple Answer Question`. Instead of correcting all types of questions but the first one, it should have been the other way around. 

![image](https://user-images.githubusercontent.com/36787606/190943804-4aa56942-2cd9-4aca-b446-3edcb36a2608.png)

According to this [SurveyMonkey link](https://www.surveymonkey.com/mp/multiple-choice-questions-everything-you-need-to-know/), multiple choice has two types which are single answer and multiple answer. Multiple answer always mean there are multiple choice, but multiple choice doesn't mean multiple answer. So your previous answer on those closed PRs doesn't clear enough regarding what multiple choice means.

#### Expected behavior

The first question's type is expected to be `Multiple Answer Question`. Although you had already put the `Select all that apply.`, it is better to have the actual correct type since it is giving the proper UX flow for the user and make it consistent across your platform (different type, different way to answer). It is also linear with the usage differences of the radio button and checkbox as intended.

#### Screenshots

![image](https://user-images.githubusercontent.com/36787606/190943154-2508aa58-4310-4b81-92a4-211d1673dbee.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ranggakd** [comment]
Thank you so much for your consideration. I'm looking forward to this. 😉

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. "Multiple Choice Question" includes 1 or more correct answers. If we use "Multiple Answer Question", it indicates that there are >=2 answers for the question. We don't have to give any hint of the lower bound of the numbers of the correct answers. We appreciate your support!
