### ISSUE TITLE
N-Ary Tree Postorder Traversal Article and Associated Problem Solution are Fundamentally Broken

### ISSUE THREAD

**Issue by evarga** [LeetCode-Feedback/LeetCode-Feedback#9121]
#### Your LeetCode username
puzzle_machine

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The [article](https://leetcode.com/explore/learn/card/n-ary-tree/130/traversal/1787/) and the associated [problem solution](https://leetcode.com/explore/learn/card/n-ary-tree/130/traversal/926/) about N-ary tree postorder traversal are fundamentally broken. The main issue is that both sources had simply disguised preorder processing of nodes by the way values were stored inside the output list. Nonetheless, they are missing the point. The postorder traversal means that you act upon a node only after all left and right children have been processed. Therefore, putting things into an output list in reverse order is still touching those nodes before any child have been taken into account, i.e., following the preorder rather than a postorder traversal.

#### Code you used for Submit/Run operation

Here is the correct solution using a single stack that actually simulates an approach using two stacks. The trick is to use a status flag to know when the node is ready for processing in postorder manner.
```
class Solution {
public:
    vector<int> postorder(Node* root) {
        // The boolean flag is an indicator whether the node was already visited or not.
        // When we pop it from the stack for a second time, then we are safe to handle that node.
        stack<tuple<Node*, bool>> nodes;
        vector<int> ans;
        
        if (root != nullptr) {
            nodes.push({root, false});
            
            while (!nodes.empty()) {
                auto item = nodes.top();
                nodes.pop();
                Node* node = get<0>(item);
                const bool visited = get<1>(item);

                if (visited)
                    // Now we are ready to act upon the node!
                    ans.push_back(node->val);
                else {
                    nodes.push({node, true});
                    for (int i = node->children.size() - 1; i >= 0; i--)
                        nodes.push({node->children[i], false});
                }
            }
        }
        
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

In the provided solution above the nodes are truly handled in postorder manner, rather than being acted upon prematurely in essentially preorder fashion.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.  The solution is not actually accessing the tree in a postorder manner, but as the judge only wants the values that would be attained in a postorder traversal, this hacky solution is sufficient. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
