### ISSUE TITLE
2411. Smallest Subarrays With Maximum Bitwise OR [TLE]

### ISSUE THREAD

**Issue by Wxld** [LeetCode-Feedback/LeetCode-Feedback#9123]
#### Your LeetCode username

ambarsariya

#### Category of the bug
- [ ] Question
- [x] Solution 👍🏽 
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I have written a solution whose time complexity is **O(NLogN)** still it is TLEing in such constraints.
Constraints:
```
n == nums.length
1 <= n <= 1e5
0 <= nums[i] <= 1e9
```

#### Code you used for Submit/Run operation

You can also refer to my Leetcode discuss post.
Link: [https://leetcode.com/problems/smallest-subarrays-with-maximum-bitwise-or/discuss/2588792/c-how-is-this-tle-binary-search-using-suffix-and-prefix](Leetcode Post)

```
class Solution {
public:
    bool equal(vector<int> &a, vector<int> &b) {
        for(int i=0; i<32; ++i)
            if((a[i] && !b[i]) || (!a[i] && b[i]))
                return false;
        return true;
    }
    vector<int> minus(vector<int> &a, vector<int> &b) {
        vector<int> ans(32);
        for(int i=0; i<32; ++i)
            ans[i] = a[i] - b[i];
        return ans;
    }
    vector<int> smallestSubarrays(vector<int>& nums) {
        int n = nums.size();
        vector<vector<int>> suf(n), pre(n);
        
        vector<int> curr(32);
        
	// suf[i] stores the number we can generate if done OR from i to n-1
        for(int i=n-1; i>=0; --i)
        {
            int t = nums[i], j = 0;
            while(t)
            {
                curr[j++] += (t & 1);
                t >>= 1;
            }
            suf[i] = curr;
        }
        for(int i=0; i<32; ++i) curr[i] = 0;
        
	// pre[i] store the number generated if done OR from 0 to i
        for(int i=0; i<n; ++i)
        {
            int t = nums[i], j = 0;
            while(t)
            {
                curr[j++] += (t & 1);
                t >>= 1;
            }
            pre[i] = curr;
        }
        
        vector<int> ans(n);
        for(int i=0; i<n; ++i)
        {
            int lo = i, hi = n-1, j = n-1;
            while(lo <= hi)
            {
                int mid = lo + (hi - lo) / 2;
                
		// curr number i.e OR from [i to mid]
                curr = i == 0 ? pre[mid] : minus(pre[mid], pre[i-1]);
                
		// suf[i] max number generated from i to n-1
                if(equal(suf[i], curr)) {
                    j = mid;
                    hi = mid - 1;
                } else {
                    lo = mid + 1;
                }
            }
            ans[i] = j - i + 1;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

I should have received an Accepted but instead I got a TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution takes 5000ms to pass on dedicated judgers.
32NlogN although is slightly higher than the expected complexity(32*N), fails because the sum of the runtime of all test cases is being considered.
As of now it is not possible to reduce test cases to make it pass as other suboptimal solutions would pass as well.
We appreciate your support!

**Comment by Wxld** [comment]
Oh okay, But since n was in the range of `1e5`, I thought that `NlogN` should work.
Thank you for clarifying this that execution time of all the testcases are considered and not only the single one.
