### ISSUE TITLE
Test Case Wrong - 11. Container With Most Water

### ISSUE THREAD

**Issue by Akarsh-1503** [LeetCode-Feedback/LeetCode-Feedback#9125]
#### Your LeetCode username

sriakarsh2003

#### Category of the bug
- [ Yes] Wrong output

#### Description of the bug

It was accepting solution on console side, but on submission it popped out wrong answer.

#### Code you used for Submit/Run operation

```
//  Two Pointers
class Solution {
public:
    int maxArea(vector<int>& height) {
        
          int i=0,j=height.size()-1,k=0,area,max=INT_MIN;
        
        while(i<height.size()){
            j=height.size()-1;
            k=0;
            
            while(k<=j){
                
                if(j!=i && height[j]>=height[i]){
                    area=(height[i]*(j-i));
                    
                   break;
                }

                 if(k!=i && height[k]>=height[i]){
                    area=(height[i]*(i-k));
                    
                   break;
                }

                k++;
                j--;
            }

             if(max<area){
                        max=area;
                    }

                    
            i++;
        }
        
        return max;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It must accept solution.

#### Screenshots

![image](https://user-images.githubusercontent.com/103405266/191080687-00feeee5-9df7-4784-ae63-3a4a404cfc3a.png)

#### Additional context

It is returning some garbage value as output.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
