### ISSUE TITLE
heap-buffer-overflow on 2195. Append K Integers With Minimal Sum

### ISSUE THREAD

**Issue by clock999** [LeetCode-Feedback/LeetCode-Feedback#9128]
Hello,

I am doing the practice(2195. Append K Integers With Minimal Sum):
https://leetcode.com/contest/weekly-contest-283/problems/append-k-integers-with-minimal-sum

My code is as below.
======================================
void shellsort(int v[], int n) {
int gap, i, j, temp;
for (gap = n/2; gap > 0; gap /= 2)
for (i = gap; i < n; i++)
for (j=i-gap; j>=0 && v[j]>v[j+gap]; j-=gap) {
temp = v[j];
v[j] = v[j+gap];
v[j+gap] = temp;
}
}

long long minimalKSum(int* nums, int numsSize, int k){
shellsort(nums, numsSize);
long long sum = 0;
int nums_index = 0;
long long sum_nums = 0;
long long k_index = k;

while (nums_index < numsSize) {
if (nums_index > 0 && nums[nums_index - 1] == nums[nums_index]) {
while (nums[nums_index - 1] == nums[nums_index]) {
nums_index++;
}
continue;
}

if (nums[nums_index] <= k_index) {
sum_nums = sum_nums + nums[nums_index];
nums_index++;
k_index++;
} else {
break;
}
}

sum = sum + (k_index * (1 + k_index)) / 2 - sum_nums;

return sum;
}
===================================================
When I run my code with the very simple case below, the leetcode reported an error heap-buffer-overflow.
[1,1]
2

There is no such error as running the code on my pc. So seems this is not a coding problem. Could you please help take a look? Thanks!
And I list the full error information below.

=================================================================
==32==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000018 at pc 0x55e06fa712eb bp 0x7ffef0566dd0 sp 0x7ffef0566dc0
READ of size 4 at 0x602000000018 thread T0
[#2](https://support.leetcode.com/hc/requests/2) 0x7fef26b2d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
0x602000000018 is located 0 bytes to the right of 8-byte region [0x602000000010,0x602000000018)
allocated by thread T0 here:
[#0](https://support.leetcode.com/hc/requests/0) 0x7fef27772bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
[#3](https://support.leetcode.com/hc/requests/3) 0x7fef26b2d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Shadow bytes around the buggy address:
0x0c047fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c047fff8000: fa fa 00[fa]fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
Addressable: 00
Partially addressable: 01 02 03 04 05 06 07
Heap left redzone: fa
Freed heap region: fd
Stack left redzone: f1
Stack mid redzone: f2
Stack right redzone: f3
Stack after return: f5
Stack use after scope: f8
Global redzone: f9
Global init order: f6
Poisoned by user: f7
Container overflow: fc
Array cookie: ac
Intra object redzone: bb
ASan internal: fe
Left alloca redzone: ca
Right alloca redzone: cb
Shadow gap: cc
==32==ABORTING

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by clock999** [comment]
HI,


I copied the link: https://leetcode.com/submissions/detail/805230836/ 


If it is not the one that you expected,  pls let me know.





At 2022-09-20 21:28:07, "LC_M" ***@***.***> wrote:

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.

**Comment by clock999** [comment]
Hello,

Sorry, I am a little confused. As I understand,  this issue is about the failure of running but not a complexity problem, according to the description reported by leetcode which I have copied on the top post. It is reported as heap-buffer-overflow.
Do you mean the program costs too much time of running which is the cause of the problem?

**Comment by clock999** [comment]
And I can reproduce this every time.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. The issue that exists in your end is because you didn't enable AddressSanitizer on the PC.

```

while (nums[nums_index - 1] == nums[nums_index]) {

nums_index++;

}

```

The code snippet above will cause overflow.

Best regards,
The LeetCode Team
