### ISSUE TITLE
Missing constraints - 167. Two Sum II - Input array is sorted

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#913]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
167. Two Sum II - Input array is sorted
https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/

Please add constraints for this problem.
Creating test cases to pass this was a nightmare.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

A problem must have constrainst to build the right test data & pass in the 1st attempt.
Otherwise user's acceptance rate on their profile will drop. Mine dropped many times, though I was lucky for this problem.
Please add constrainsts.

**Comment by lc-pam** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
