### ISSUE TITLE
Missing Test Case - 142. Linked List Cycle II

### ISSUE THREAD

**Issue by ArchFunke** [LeetCode-Feedback/LeetCode-Feedback#9130]
#### Your LeetCode username
ArchFunke

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

There is a lack of a test case that can be used for a solution that shouldn't work. 

My initial solution of checking if a node.val was present in a HashSet failed this case: [-1,-7,7,-4,19,6,-9,-5,-2,-5] where the cycle started at index 6. This was because -5 occurred twice before the loop.

I decided to make a HashSet of strings and to store "node.val:node.next.val" as the key as a hacky work around to the test case.
To my surprise, it was accepted and no other test cases failed.

This would fail if the test case that I originally failed was modified to [-1,-7,7,-4,19,6,-9,-5,-5,-5] cycle 6. 
A test case with 3 or more repeating node values in a row as above would fail.
A test case with 2+ separate instances of 2 node values in a row being the same would also potentially fail my code, depending on the cycle position.

Attached pics just show the initial failed code and the subsequent accepted code.

#### Code you used for Submit/Run operation

```
public class Solution {
    public ListNode DetectCycle(ListNode head) {
        HashSet<string> cycle = new HashSet<string>();
        ListNode itr = head;
        while(itr != null && itr.next != null){
            string s = itr.val + ":" + itr.next.val;
            if(cycle.Contains(s)) return itr;
            cycle.Add(s);
            itr = itr.next;
        }
        return null;
    }
}
```

#### Language used for code

C#

#### Expected behavior

I expected my code to fail a different test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/69926289/191159853-eaffebf4-2b1e-439f-85dc-d848fcb8687b.png)
![image](https://user-images.githubusercontent.com/69926289/191159958-09263422-da55-4aca-af0e-e2de13973d53.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to add the testcase. We appreciate your support!
