### ISSUE TITLE
类型出错 117. 填充每个节点的下一个右侧节点指针 II

### ISSUE THREAD

**Issue by Josh119891** [LeetCode-Feedback/LeetCode-Feedback#9131]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
锋

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
默认的类型出错，Node没有left,right

**你使用的语言**
typescript

**你提交或者运行的代码**
```
// [117. 填充每个节点的下一个右侧节点指针 II](https://leetcode.cn/problems/populating-next-right-pointers-in-each-node-ii/)
function connect(root: Node | null): Node | null {
    if(!root) return null;
    console.log(root.left) // 这里的root.left 报错，说Node没有left这个字段
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
您好，在与相关团队核实后：并不影响正常使用，暂不处理。本次 Ticket 将关闭，感谢您的反馈和支持。
