### ISSUE TITLE
Hint given is wrong.

### ISSUE THREAD

**Issue by ramen-7** [LeetCode-Feedback/LeetCode-Feedback#9135]
#### Your LeetCode username
shivam_taneja

#### Category of the bug
- [ ] Question - [718. Maximum Length of Repeated Subarray](https://leetcode.com/problems/maximum-length-of-repeated-subarray)
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The hint given for the question is
`Use dynamic programming. dp[i][j] will be the answer for inputs A[i:], B[j:].`, when instead it should be
`Use dynamic programming. dp[i][j] will be the answer for inputs A[:i], B[:j].`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
The hints are correct. They are explained in the solution article in details.
We also added one more hint.
 We appreciate your support!
