### ISSUE TITLE
1361. Validate Binary Tree Nodes [Missing Test Cases]

### ISSUE THREAD

**Issue by devenps** [LeetCode-Feedback/LeetCode-Feedback#914]
#### Your LeetCode username

devenps

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Incorrect solution is accepted because of insufficient test case.
Below Test case is missing.
4
[1,0,3,-1]
[-1,-1,-1,-1]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean validateBinaryTreeNodes(int n, int[] leftChild, int[] rightChild) {
        if (n < 2) return true;
        int[] indegree = new int[n];
        for (int i : leftChild) {
            if (i != -1) {
                indegree[i]++;
                if (indegree[i] > 1) return false;
            }
        }

        for (int i : rightChild) {
            if (i != -1) {
                indegree[i]++;
                if (indegree[i] > 1) return false;
            }
        }

        int rootNodeCount = 0, rootNodeIndex = 0;
        for (int i = 0; i < n; i++) {
            if (indegree[i] < 1){
                rootNodeIndex = i;
                rootNodeCount++;
                if (rootNodeCount > 1) return false;
            }
        }

        return rootNodeCount == 1 && (leftChild[rootNodeIndex] != -1 || rightChild[rootNodeIndex] != -1);
    }
}
```

#### Language used for code

Java

#### Expected behavior

Below Test case is missing.
4
[1,0,3,-1]
[-1,-1,-1,-1]

This test case should return "false" but my above code is returning "true" and still, the solution got accepted. 

#### Screenshots

![image](https://user-images.githubusercontent.com/8740608/92019233-e65b8180-ed73-11ea-8ee2-7f536996a850.png)

**Comment by lc-pam** [comment]
Hi @devenps 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @devenps 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
