### ISSUE TITLE
cannot access Help Center anymore due to being stuck in a hcaptcha loop

### ISSUE THREAD

**Issue by correabuscar** [LeetCode-Feedback/LeetCode-Feedback#9141]
#### Your LeetCode username

correabuscar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] cannot access [Help Center](https://support.leetcode.com/hc/en-us) to report any non-problem related issues!

#### Description of the bug

Trying to browse to Help Center url https://support.leetcode.com/hc/en-us shows the Security check hcaptcha and after completing it, it shows it again, then again, seemingly forever, for unknown reason(s).

#### Expected behavior

Continue loading the original webpage after the hcaptcha is completed(once).

#### Screenshots

Begins like this:
![slchc1of4](https://user-images.githubusercontent.com/106607441/191375139-f45d94a5-e061-4974-b755-34853ca5c9d8.png)
![slchc2of4](https://user-images.githubusercontent.com/106607441/191375145-767a92f0-045f-44a8-a5b6-0be9862f12b0.png)
![slchc3of4](https://user-images.githubusercontent.com/106607441/191375150-2d23f9f1-663b-4fd6-83d0-a5259f647cbb.png)
Then (re)starts again:
![slchc4of4](https://user-images.githubusercontent.com/106607441/191375156-323d8c7b-82bf-4b55-8774-dcc4db542c19.png)

#### Additional context

Using Firefox 104.0.1 (64-bit) under Gentoo. Do have some about:config changes though... But I personally don't believe it's the fault of my browser. I could be wrong!

Did sign up for github using hcaptcha, and it worked back then, but it was an earlier Firefox version, and maybe it was a different hcaptcha, I'm unsure. But it wasn't Google's.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our page appears to be working correctly, please feel free to check the solution the website.

**Comment by correabuscar** [comment]
Yeah, I wasn't asked for hcaptcha anymore this time, so the page worked. Thanks!
