### ISSUE TITLE
Problematic Question

### ISSUE THREAD

**Issue by Zackhardtoname** [LeetCode-Feedback/LeetCode-Feedback#9145]
#### Your LeetCode username
sampleaccountpage

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the question [string compression](https://leetcode.com/problems/string-compression/), since the input could have digits, the compressed result could map to multiple inputs.

The point of compression is that the original uncompressed value should be recoverable. However, both the input 
`["b","b","b","b","b","b","b","b","b","b","b","b"]` (12 b's) and `["b", "1", "1"]` would result in `["b", "1", "2"]`.

#### My suggestion
Remove "digit" from the line "chars[i] is a lowercase English letter, uppercase English letter, digit, or symbol" in the problem description.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Each input has one unique answer according to the given rules. We appreciate your support!

**Comment by Zackhardtoname** [comment]
> Thank you for your time. Each input has one unique answer according to the given rules. We appreciate your support!

That is not true.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/25935197/191928611-8940c689-b4d7-4328-b535-5fcf339fa890.png">
<img width="605" alt="image" src="https://user-images.githubusercontent.com/25935197/191928656-863b7db9-633f-4abf-a6c4-d9527a086041.png">
