### ISSUE TITLE
Find the Difference of Two Arrays  218 ms, 53.2MB

### ISSUE THREAD

**Issue by RamboFirstBlood** [LeetCode-Feedback/LeetCode-Feedback#9146]
public static IList<IList<int>> FindDifference(int[] nums1, int[] nums2)
        {
        //Input: nums1 = [1, 2, 3], nums2 = [2, 4, 6]
        //Output: [[1,3],[4,6]]
            IList<IList<int>> result = new List<IList<int>>();
            List<int> num2l = nums2.ToList();
            List<int> num1l = new List<int>(nums1);
            List<int> temp2 = new List<int>();
            List<int> temp1 = new List<int>();
            for (int i = 0; i < nums1.Length; i++)
            {
                if(!num2l.Contains(nums1[i])&&!temp1.Contains(nums1[i]))
                {
                    temp1.Add(nums1[i]);
                }
            }
            for (int i = 0; i < nums2.Length; i++)
            {
                if (!num1l.Contains(nums2[i]) && !temp2.Contains(nums2[i]))
                {
                    temp2.Add(nums2[i]);
                }
            }
            result.Add(temp1);
            result.Add(temp2);
            return result;
        }

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
