### ISSUE TITLE
Missing Test Case - 229. Majority Element II

### ISSUE THREAD

**Issue by harshit-tech03** [LeetCode-Feedback/LeetCode-Feedback#9147]
#### Your LeetCode username
harshitsingh7232

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Given test cases have not negative values as answer. So, by using variables for first and second different element as -1 or in my case -2 or any negative value will be accepted.

#### Code you used for Submit/Run operation

```

// Majority Elements II
class Solution {
public:
    vector<int> majorityElement(vector<int>& nums) {
        int n = nums.size();
        int cx=0,cy=0;
        vector<int> ans;
        int x=-2,y=-2;
        
        for(int i=0; i<n; i++){
            if(x==nums[i])
                cx++;
            else if(y==nums[i])
                cy++;
            else if(cx==0)
            {
                x=nums[i];
                cx++;
            }
            else if(cy==0)
            {
                y=nums[i];
                cy++;
            }
            else
            {
                cx--;
                cy--;
            }  
        }
        cx=cy=0;
        for(int i=0; i<n; i++){
            if(nums[i]==x){
                cx++;
            }
            if(nums[i]==y)
                cy++;
        }
        
        if(cx>n/3)
            ans.push_back(x);
        if(cy>n/3)
            ans.push_back(y);
        
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Actually for array [-2,-2,-2] my code will give [-2,-2] but the actual answer will be [-2].

#### Additional context

Add more negative number test cases like 
[-2,-2,-2] 
[-3,-3,-3]
[-1,-1,-2,-2]
[-1,-2,-1,-2]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
