### ISSUE TITLE
2242. 节点序列的最大得分 缺少测试用例

### ISSUE THREAD

**Issue by DanDaydy** [LeetCode-Feedback/LeetCode-Feedback#9148]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

填写你登录 LeetCode（中国区）的用户名
**you-zhu-yi-si-mou-mou-ren**

**Bug 类型**
- [x] 缺少测试用例

**描述**
该题缺少测试用例，使得下面最坏情况下 $O(n^2)$ 的代码能够通过，甚至在执行用时上能击败 98.41% 的用户
使用以下测试用例可以使以下代码 TLE
[example.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9617576/example.txt)

**你使用的语言**
Python3

**代码**
```python
class Solution:
    def maximumScore(self, scores: List[int], edges: List[List[int]]) -> int:
        child = defaultdict(set)

        for a, b in edges:
            child[a].add(b)
            child[b].add(a)
        

        ans = -1

        edges.sort(key=lambda i:scores[i[0]] + scores[i[1]], reverse=True)

        for i in range(len(edges)):
            a, b = edges[i]
            for j in range(i + 1, len(edges)):
                c, d = edges[j]

                if a == c or a == d or b == c or b == d:
                    continue
                    
                tmp = scores[a] + scores[b] + scores[c] + scores[d]

                if tmp > ans:
                    if a in child[c] or a in child[d] or b in child[c] or b in child[d]:
                        ans = max(ans, tmp)
                else:
                    break
        
        return ans
```

**期望行为**
使得上述代码 TLE

**屏幕截图**
![image](https://user-images.githubusercontent.com/70909931/191529254-9aa8c22b-9f91-41fe-a19a-1ea923454ddb.png)
![image](https://user-images.githubusercontent.com/70909931/191529365-48a99c90-7808-4b2e-b8dc-c17568163f6e.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，经核实该题目代码可以正常执行、提交，超出时间限制是复杂度太高了， 建议优化使用的算法（可以参考题目的题解），后续，刷题学习中遇到问题，您可通过阅读「题解」解决做题中的一些困惑，可至 [力扣圈子](https://leetcode-cn.com/circle/discussions/questions?orderBy=HOTTEST&query=) 进行题目交流，以获得更好的支持哟～
