### ISSUE TITLE
Less Tags - 2178. Maximum Split of Positive Even Integers

### ISSUE THREAD

**Issue by shivansh-soni07** [LeetCode-Feedback/LeetCode-Feedback#9149]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

It can be easily and optimally solved using backtracking but there was no tag of backtracking in the question

**Comment by shivansh-soni07** [comment]
Final

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
