### ISSUE TITLE
73. Set Matrix Zeroes : Invalid testcase

### ISSUE THREAD

**Issue by eagleoflqj** [LeetCode-Feedback/LeetCode-Feedback#915]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

There's a constraint `-10^9 <= matrix[i][j] <= 10^9`, however 2147483647 appears in testcases.

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    void setZeroes(vector<vector<int>>& matrix) {
        int n = matrix[0].size();
        for(int j = 0; j < n; ++j)
            if(any_of(matrix.begin(), matrix.end(), [j](const auto &row) { return row[j] == 0; }))
                for_each(matrix.begin(), matrix.end(), [j](auto &row) { if(row[j]) row[j] = INT_MAX; });
        for(auto &row : matrix) {
            auto b = row.begin(), e = row.end();
            if(any_of(b, e, [](int i) { return i == 0; }))
                fill(b, e, 0);
            else
                for_each(b, e, [](int &i) { if(i == INT_MAX) i = 0; });
        }
    }
};
```

#### Language used for code
C++

#### Expected behavior
Since INT_MAX is out of the range, this code should work.

**Comment by lc-ivan** [comment]
Hi @eagleoflqj ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @eagleoflqj,
Thank you for your feedback regarding this problem. Upon review, our team has updated the constraints to this problem. We will not be rewarding for this case as the content management team noted this is a common issue that we are working on case by case. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!

**Comment by eagleoflqj** [comment]
I see the updates, thank you! I'm not for any kinds of rewards, just don't want anybody like me to waste time coding on false descriptions.
