### ISSUE TITLE
Error in Python implementation of Radix Sort in the Sorting Explore Card

### ISSUE THREAD

**Issue by ibeauregard** [LeetCode-Feedback/LeetCode-Feedback#9150]
#### Your LeetCode username
mrchose

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the Python implementation of Radix Sort in the Sorting Explore Card, line 42 should likely be changed for the following:

`while place_val <= max_elem:`

#### Code you used for Submit/Run operation
```python
x = [10, 0]
Solution().radix_sort(x)
print(x)
```

#### Language used for code
Python

#### Expected behavior
Expected array after sorting: `[0, 10]`
Actual array after sorting: `[10, 0]`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
