### ISSUE TITLE
Passed all test cases but shows time limit exceeded

### ISSUE THREAD

**Issue by kuntal0901** [LeetCode-Feedback/LeetCode-Feedback#9151]
#### Your LeetCode username

kuntal0901

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I have passed all the test cases for leetcode problem no. 718 but it gave me a time limit execeded error.

#### Code you used for Submit/Run operation

```
// [Maximum Length of Repeated Subarray](https://leetcode.com/problems/maximum-length-of-repeated-subarray/)
class Solution:
    def findLength(self, nums1: List[int], nums2: List[int]) -> int:
        n1,n2 =len(nums1),len(nums2)
        res = 0
        dp = [[0]*(n1+1) for _ in range(n2+1)]
        for i in range(n2-1,-1,-1):
            for j in range(n1-1,-1,-1):
                if nums1[j] == nums2[i]: 
                    dp[i][j] = 1+dp[i+1][j+1]
                    res = max(res,dp[i][j])
        return res
```

#### Language used for code
Python3

#### Expected behavior
I have passed all the test cases which implies it should be accepeted.

#### Screenshots
<img width="933" alt="image" src="https://user-images.githubusercontent.com/54110827/191549700-fbe0c9b4-9dfe-47d6-8702-947cc3644877.png">

#### Additional context
 TLE for passing all test cases.

**Comment by LC-Pam** [comment]
Thank you for your time. Your code received Accepted when we submitted it. We appreciate your support!
https://leetcode.com/submissions/detail/806068793/

**Comment by kuntal0901** [comment]
I tried it again but it still didn't accept all test cases.
[image: image.png]
