### ISSUE TITLE
Missing Test Case - 16. 3Sum Closest

### ISSUE THREAD

**Issue by Anshu-jindal** [LeetCode-Feedback/LeetCode-Feedback#9152]
#### Your LeetCode username

`Anshu_Jindal`

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug

I was solving this question and got answer to a test case as -2976 using these sets of 3 numbers [-970, -833, -993] and [-934, -869, -993]

The given answer for the same was -2960 which is not the correct answer for this test case.

The test case was: 
[833,736,953,-584,-448,207,128,-445,126,248,871,860,333,-899,463,488,-50,-331,903,575,265,162,-733,648,678,549,579,-172,-897,562,-503,-508,858,259,-347,-162,-505,-694,300,-40,-147,383,-221,-28,-699,36,-229,960,317,-585,879,406,2,409,-393,-934,67,71,-312,787,161,514,865,60,555,843,-725,-966,-352,862,821,803,-835,-635,476,-704,-78,393,212,767,-833,543,923,-993,274,-839,389,447,741,999,-87,599,-349,-515,-553,-14,-421,-294,-204,-713,497,168,337,-345,-948,145,625,901,34,-306,-546,-536,332,-467,-729,229,-170,-915,407,450,159,-385,163,-420,58,869,308,-494,367,-33,205,-823,-869,478,-238,-375,352,113,-741,-970,-990,802,-173,-977,464,-801,-408,-77,694,-58,-796,-599,-918,643,-651,-555,864,-274,534,211,-910,815,-102,24,-461,-146]
-7111

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int binarySearch(vector<int>& nums, int target) {
        int start = 0, end = nums.size() - 1, mid;
        while(start <= end) {
            mid = (start + end)/2;
            if (nums[mid] == target) {
                return nums[mid];
            } else if (nums[mid] > target) {
                end = mid - 1;
            } else {
                start = mid + 1;
            }
        }
        
        return mid;
    }
    
    int returnClosestSum(vector<int>& nums, int currSum, int mid, int target, int closestSum, int i, int j) {
        if (mid > 0) {
            currSum += nums[mid - 1];
            if (abs(target - currSum) < abs(target - closestSum)) {
                closestSum = currSum;
                if (currSum == -2796) {
                    cout<<i<<" "<<j<<" "<<mid - 1<<" " << nums[i]<<" "<<nums[j]<<" "<<nums[mid - 1]<<endl;
                }
            }
            currSum -= nums[mid - 1];
        }
        currSum += nums[mid];
        if (abs(target - currSum) < abs(target - closestSum)) {
            closestSum = currSum;
        }
        
        if (currSum == -2796) {
            cout<<i<<" "<<j<<" "<<mid<<" " << nums[i]<<" "<<nums[j]<<" "<<nums[mid]<<endl;
        }
        
        currSum -= nums[mid];
        
        if (mid < nums.size() - 1) {
            currSum += nums[mid + 1];
            if (abs(target - currSum) < abs(target - closestSum)) {
                closestSum = currSum;
            }
            currSum -= nums[mid + 1];
            if (currSum == -2796) {
                cout<<i<<" "<<j<<" "<<mid + 1<<" " << nums[i]<<" "<<nums[j]<<" "<<nums[mid + 1]<<endl;
            }
        }
        
        return closestSum;
    }
    
    int threeSumClosest(vector<int>& nums, int target) {
        int i, j, closestSum = INT_MAX/2, currSum = 0;
        sort(nums.begin(), nums.end());
        
        for (i = 0; i < nums.size() - 2; i++) {
            for (j = i + 1; j < nums.size() - 1; j++) {
                currSum = nums[i] + nums[j];
                int mid = binarySearch(nums, target - currSum);
                
                closestSum = returnClosestSum(nums, currSum, mid, target, closestSum, i, j);
            }
        }
        
        return closestSum;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The expected answer would be -2976 as difference between -7111 and -2976 would be -4135 whereas the difference between the given answer and -7111 is -4151

**PLEASE READ BELOW LINE TO UNDERSTAND THE BUG**
Even though the difference between the given answer (-2960) and (-7111) is less, it is still more far away from target (-7111) than (-2976) because we should consider the absolute value of difference while considering which is more far away.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by Anshu-jindal** [comment]
I could optimize my solution according to the given test cases but I am still not able to understand why my answer is wrong?

Imagine these target as (-3)
And there are 2 options for answer: (-2) and (-1), which is more close?

It is (-2) as per me.
