### ISSUE TITLE
No diagrams and documentation in System Design tutorial

### ISSUE THREAD

**Issue by cacarrilloc** [LeetCode-Feedback/LeetCode-Feedback#9154]
#### Your LeetCode username
cacarrilloc

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Diagrams and documentation are missing here:
https://leetcode.com/explore/featured/card/system-design/690/system-design-case-studies/4387/
https://leetcode.com/explore/featured/card/system-design/690/system-design-case-studies/4388/

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
