### ISSUE TITLE
Missing Test Case - 515. Find Largest Value in Each Tree Row

### ISSUE THREAD

**Issue by Surajsharmacloud** [LeetCode-Feedback/LeetCode-Feedback#9155]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1 ] Missing Test Cases 

#### Description of the bug

 THE QUESTION WAS TO PRINT THE MAX NUMBER ON EACH LEVEL OF  A BINARY TREE
THERE WERE 78 TEST CASES AND OF  THEM 71 WERE SUCCESS AND REST  FAILED 

#### Code you used for Submit/Run operation

```



```

#### Language used for code

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    vector<int>v;
    vector<int> largestValues(TreeNode* root) {
        if(root==NULL)
            return v;
        long long int maxi=-1e9;
       int i=0;
        v.push_back(root->val);
        queue<TreeNode *>q;
        q.push(root);
        TreeNode *ptr;
        
        while(!q.empty())
        {
            ptr=q.front();
            if(ptr->left!=NULL)
            {
                q.push(ptr->left);
                i++;
                maxi=max<long long int>(maxi,ptr->left->val);
            }
            if(ptr->right!=NULL)
            {
                q.push(ptr->right);
                maxi=max<long long int>(maxi,ptr->right->val);
                i++;
            }
            if(q.size()-1==i && i!=0)
            {
                v.push_back(maxi);
                maxi=-1e9;
                i=0;
            }
            q.pop();
        }
        return v;
    }
};


```

#### Expected behavior

![image](https://user-images.githubusercontent.com/61677593/191603781-6e0b3914-67f9-49e2-a6bd-f89a2e90d97e.png)

#### Screenshots
![Screenshot (225)](https://user-images.githubusercontent.com/61677593/191605148-942beed0-506b-473b-afc1-c1717fbf5ace.png)

![image](https://user-images.githubusercontent.com/61677593/191603770-61eab644-52cf-4f34-aae8-4298a3106f4a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
