### ISSUE TITLE
Wrong space complexity in solution 557. reverse-words-in-a-string-iii

### ISSUE THREAD

**Issue by DheerajGadwala** [LeetCode-Feedback/LeetCode-Feedback#9159]
#### Your LeetCode username
DheerajGadwala

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Solutions to this question mention O(1) space complexity, while this is true for C++ since String are mutable in the language, this is not true for Java because Strings are immutable and you have to create new Strings which means that the space complexity in Java is O(n). 
Also, technically, the space complexity is O(n) even in C++ because of the input size. You're actually supposed to say "Auxilary space used is O(1)".

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
