### ISSUE TITLE
十万火急！今天的每日一题缺少用例！1640. 能否连接形成数组 

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#9160]
**你的 LeetCode 用户名**
yanglock-6

**Bug 类型**
- [x] 缺少测试用例

**你提交或者运行的代码**
```
# 思路：遍历Pieces 然后看是否在arr拼接字符串中，顺便进行统计剩余个数，具体代码如下：
class Solution:
    def canFormArray(self, arr: List[int], pieces: List[List[int]]) -> bool:
        a = "".join(map(str,arr))
        total = len(a)
        for p in pieces:
            ref = "".join(map(str,p))
            total -= len(ref)
            if ref not in a:
                return False
        if total:
            return False
        return True
```

**期望行为**
添加测试用例：
[99,1]
[[9],[91]]

**屏幕截图**
![image](https://user-images.githubusercontent.com/25954059/191651134-286cb1d1-bd2e-44e6-a103-ab7658dd04ef.png)

**额外的上下文**
题目：https://leetcode.cn/problems/check-array-formation-through-concatenation/
题解：https://leetcode.cn/problems/check-array-formation-through-concatenation/solution/1640neng-fou-lian-jie-xing-cheng-shu-zu-cwef0/

**Comment by yangguangxin** [comment]
给你一个整数数组 arr ，数组中的每个整数 互不相同 。另有一个由整数数组构成的数组 pieces，其中的整数也 互不相同 。请你以 任意顺序 连接 pieces 中的数组以形成 arr 。但是，不允许 对每个数组 pieces[i] 中的整数重新排序。

### 如果可以连接 pieces 中的数组形成 arr ，返回 true ；否则，返回 false 。
请看原题，形成的还是数组，也就是不能改变数字

**Comment by hummingg** [comment]
> 给你一个整数数组 arr ，数组中的每个整数 互不相同 。另有一个由整数数组构成的数组 pieces，其中的整数也 互不相同 。请你以 任意顺序 连接 pieces 中的数组以形成 arr 。但是，不允许 对每个数组 pieces[i] 中的整数重新排序。
> 
> ### 如果可以连接 pieces 中的数组形成 arr ，返回 true ；否则，返回 false 。
> 请看原题，形成的还是数组，也就是不能改变数字

我的意思是我贴的代码可以AC，但实际上不应该AC。所以要增加测试用例卡住这份代码。

**Comment by feiceh** [comment]
你好，当前该题已添加测试用例， yanglock-6 给予积分奖励，请查收。
