### ISSUE TITLE
Solution - 557. Reverse Words in a String III

### ISSUE THREAD

**Issue by megaspazz** [LeetCode-Feedback/LeetCode-Feedback#9161]
#### Category of the bug
- [ ] Question
- [ X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution's Approach #1 describes space complexity as being O(1), but in both C++ and Java solutions, it constructs an entirely new string; such new string takes O(N).  There is confusion in the output about the space complexity--does the output buffer count as extra space?  If output buffer does not count, ideally it should emit to a StringStream for output instead of having user build a new string.

Solution's Approach #2 also describes having space complexity O(1), but Java has a gotcha where Strings are immutable and therefore returning a different string necessarily requires constructing a new String.  It would be nice to call it out, or change the Java function signature to take parameter `char[]` instead of `String`.

Overall, solutions are good, but I think calling this out in the problem statement or solutions would reduce users' confusion about the matter.

#### Code you used for Submit/Run operation

See solutions on code page:
https://leetcode.com/problems/reverse-words-in-a-string-iii/solution/

#### Language used for code

C++ / Java

#### Expected behavior

It is technically inaccurate that the solutions claim O(1) space.  It would be good to clarify to users that certain exceptions are allowed (e.g. building the output).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
