### ISSUE TITLE
Pre-defined Python3 Code is Ambiguous - 428. Serialize and Deserialize N-ary Tree

### ISSUE THREAD

**Issue by edsn60** [LeetCode-Feedback/LeetCode-Feedback#9163]
#### Your LeetCode username

ShelvinY

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Python3, the pre-defined ```class Node``` can be ambiguous. The default value for ```self.children``` is None, which may cause a misunderstanding that when a node has no child, its ```children``` attribute should be set to ```None```. However, After checking the parameter passed to ```serialize()```, every node without children has a ```[]``` value. And it seems that the backend result-check program also uses ```[]``` as the default value here (because it is using a for loop to check each child, resulting in a ```TypeError: object of type 'NoneType' has no len()``` if the user really uses ```None``` as default) and it is obvious that ```None``` and ```[]``` are not the same thing. This problem can be solved by explicitly setting the children attribute to ```[]``` when creating a new node. But I think it might be better to modify the default value of children to ```[]```.

#### Code you used for Submit/Run operation

```
"""
# Definition for a Node.
class Node(object):
    def __init__(self, val=None, children=None):
        self.val = val
        self.children = children
"""

class Codec:
    def serialize(self, root: 'Node') -> str:
        """Encodes a tree to a single string.
        
        :type root: Node
        :rtype: str
        """
        if not root:
            return ''
        res = str(root.val)
        if root.children:
            cur = ""
            for child in root.children:
                cur += self.serialize(child) + " "
            return f"{res} ( {cur[:-1]} )"
        else:
            return f"{res}"
	
    def deserialize(self, data: str) -> 'Node':
        """Decodes your encoded data to tree.
        
        :type data: str
        :rtype: Node
        """
        if not data:
            return None
        data = data.split(" ")
        i = 1
        n = len(data)
        def dfs(node):
            nonlocal i
            curnode = node
            while i < n:
                if data[i] == "(":
                    i += 1
                    dfs(curnode)
                elif data[i] == ")":
                    i += 1
                    return
                else:
                    if not node.children:
                        node.children = []
                    newnode = Node(int(data[I]))
                    node.children.append(newnode)
                    i += 1
                    curnode = newnode
            return
        root = Node(int(data[0]))
        dfs(root)
        return root
            

# Your Codec object will be instantiated and called as such:
# codec = Codec()
# codec.deserialize(codec.serialize(root))
```

#### Language used for code
Python3

#### Expected behavior

The default value for children should be ```[]```.

#### Screenshots

The error I got when I used ```None``` as default for children.
![Screen Shot 2022-09-22 at 03 12 05](https://user-images.githubusercontent.com/48507143/191683649-6df39d11-a0eb-4085-9720-5021e5d3f223.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've fixed the default value. We appreciate your support!

**Comment by edsn60** [comment]
> Thank you for your time. We've fixed the default value. We appreciate your support!

Can I have the LeetCoins? I've added my username. Thanks!
