### ISSUE TITLE
211. Design Add and Search Words Data Structure 

### ISSUE THREAD

**Issue by gorodnitskiy** [LeetCode-Feedback/LeetCode-Feedback#9164]
#### Your LeetCode username

algorodnitskiy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Recently I decided to recall this problem, but I found strange behavior. For all available solutions on Python, including Trie approach, I get Time Limit Exceeded, even for the solution suggested by LeetCode. However, earlier Trie approach solution didn't lead to Time Limit Exceeded.

#### Code you used for Submit/Run operation

```
from collections import defaultdict
from typing import Dict


class WordDictionaryTrieOptimized:
    """Trie (Prefix Tree) approach Optimized."""
    def __init__(self):
        self.trie = dict()

    def addWord(self, word: str) -> None:
        """m = len(word), time: O(m), space: O(m)"""
        node = self.trie
        for char in word:
            if char not in node:
                node[char] = dict()
            node = node[char]
        node["$"] = True

    def search(self, word: str) -> bool:
        return self.seach_in_node(word, 0, self.trie)

    def seach_in_node(
        self, word: str, start_index: int, node: Dict[str, Any]
    ) -> bool:
        """
        m, n = len(word), len(dictionary)
        without dots: time: O(m), space: O(1)
        with dots [for case with all dots "....."]:
            time: O(26^m), space: O(m) - recursion stack
        """
        for index in range(start_index, len(word)):
            char = word[index]
            if char not in node:
                if char == ".":
                    for prefix in node:
                        if prefix == "$":
                            continue
                        if self.seach_in_node(word, index + 1, node[prefix]):
                            return True
                return False
            node = node[char]
        return "$" in node


class WordDictionaryTrie:
    """Trie (Prefix Tree) approach."""
    def __init__(self):
        self.trie = dict()

    def addWord(self, word: str) -> None:
        """m = len(word), time: O(m), space: O(m)"""
        node = self.trie
        for char in word:
            if char not in node:
                node[char] = dict()
            node = node[char]
        node["$"] = True

    def search(self, word: str) -> bool:
        return self.seach_in_node(word, self.trie)

    def seach_in_node(self, word: str, node: Dict[str, Any]) -> bool:
        """
        m, n = len(word), len(dictionary)
        without dots: time: O(m), space: O(1)
        with dots [for case with all dots "....."]:
            time: O(m * 26^m), space: O(m) - recursion stack
        """
        for index, char in enumerate(word):
            if char not in node:
                if char == ".":
                    for prefix in node:
                        if prefix == "$":
                            continue
                        if self.seach_in_node(word[(index + 1):], node[prefix]):
                            return True
                return False
            node = node[char]
        return "$" in node


class WordDictionaryHashMap:
    """HashMap approach."""
    def __init__(self):
        self.data = defaultdict(set)

    def addWord(self, word: str) -> None:
        """time: O(1), space: O(1)"""
        self.data[len(word)].add(word)

    def search(self, word: str) -> bool:
        """
        n, m = len(dictionary), len(word)
        time: O(n * m), space: O(1)
        """
        n = len(word)
        for dict_word in self.data[n]:
            i = 0
            while(i < n):
                if (word[i] != dict_word[i]) and (word[i] != "."):
                    break
                i += 1
            if i == n:
                return True
        return False
```

#### Language used for code

Python

#### Expected behavior

Trie approach solution shouldn't get Time Limit Exceeded for this problem.

#### Screenshots

<img width="678" alt="Screenshot 2022-09-22 at 13 57 58" src="https://user-images.githubusercontent.com/8071747/191729377-76536d09-1558-44a2-bfeb-a71abd3d1d21.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission TLE link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by gorodnitskiy** [comment]
Sorry for late response, it's submission with TLE: https://leetcode.com/submissions/detail/806008004/
I try one more time today and it works: https://leetcode.com/submissions/detail/807564090/
Suppose you've already fixed it.😌

**Comment by LC-Pam** [comment]
Thank you for contacting LeetCode's Support Team. 

When you input the failed test case into the test case console and "Run Code", that action only runs that one test case. Since it's only running one specific test case, your algorithm and time complexity was able to successfully run it. However, when you submit the code, it is running ALL the test cases. Therefore, resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

I'd recommend checking out accepted submissions from the discuss tab of the problem page, or posting your code there to get support from other users!

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by gorodnitskiy** [comment]
Thank you for the comment!
However, I assume it has some problem, because LeetCode solution based on Trie approach on Python has TLE too.
For example, you can check this submission (https://leetcode.com/submissions/detail/810861604/) or try it yourself from solution tab.
