### ISSUE TITLE
Bug in the Implementation of Insertion Sort

### ISSUE THREAD

**Issue by evarga** [LeetCode-Feedback/LeetCode-Feedback#9166]
#### Your LeetCode username
puzzle_machine

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The official [solution](https://leetcode.com/problems/insertion-sort-list/solution/) (both for Java and Python) contains a bug that makes the provided insertion sort unstable, i.e., it changes the relative ordering of equivalent elements. 

#### Code you used for Submit/Run operation

Line 11 in the Java solution (same applies for the Python solution) should be changed as follows (the old version uses less (<) instead of less or equal (<=) operator):
```
while (prev.next != null && prev.next.val <= curr.val) {
```

#### Language used for code
Java

#### Expected behavior
With the proposed change the code would now implement a stable sorting algorithm.

#### Additional context
LeetCode should improve the quality of testing and include checks for stability. This is an important property of an algorithm that cannot be neglected.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. It's not a bug, the problem doesn't request a stable sorting. We appreciate your support!

**Comment by evarga** [comment]
This response is not satisfactory, since Insertion sort is regarded as a stable sorting algorithm. If this is not required, then don't call it as such. So, this is a bug in this regard.
