### ISSUE TITLE
Missing Test Case - 214. Shortest Palindrome

### ISSUE THREAD

**Issue by mamonten0k** [LeetCode-Feedback/LeetCode-Feedback#9167]
#### Your LeetCode username
mamonten0k

#### Category of the bug
- [*] Solution

#### Description of the bug
The problem is about my solution of [this palindome task](https://leetcode.com/problems/shortest-palindrome)
On test with input string "aabba" my function sends an answer "aabbaa" which is correct, 
but the said ref answer is "abbaabba".

#### Code you used for Submit/Run operation
```var shortestPalindrome = function(s) {
    let r = s.split('').reverse('').join('');
    
    let res = '';
    
    let index1 = 0;
    let index2 = 0;
    
    while(index1 < s.length && index2 < r.length) {
        if(s[index1] === r[index2]) {
            res += r[index2];
            index1++;
            index2++;
        } else if(res[res.length-1] === s[index1]) {
            res += s[index1];
            index1++;
        } else {
            res += r[index2];
            index2++;
        }
    }
    
    while(index1 < s.length) {
        res += s[index1];
        index1++;
    }
    
    while(index2 < r.length) {
        res += r[index2];
        index2++;
    }
    
    return res;
};```

#### Language used for code
JavaScript


#### Expected behavior
On test with input string "aabba" my function sends an answer "aabbaa" which is correct, 
but the said ref answer is "abbaabba".


#### Screenshots
![image](https://user-images.githubusercontent.com/90136259/191760646-8da6dd29-55b8-4e38-8ae2-25b5d9803382.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
