### ISSUE TITLE
486-预测赢家，Java 语言 PredictTheWinner 方法名首字母为什么大写了？

### ISSUE THREAD

**Issue by weijie-he** [LeetCode-Feedback/LeetCode-Feedback#9168]
**你的 LeetCode 用户名**
非复吴下阿萌

**Bug 类型**
- [ ] 题目：486
- [ ] 编程语言：Java

**描述**
PredictTheWinner 方法名为什么大写了？

**你使用的语言**
Java

**期望行为**
给的这个方法名首字母应该是小写

**Comment by stormsunshine** [comment]
486的所有语言的方法/函数名的首字母都是大写，虽然确实不符合代码规范，但是个人认为没必要改，如果改了名称那么影响面会很大，现有的题解中的代码都将无效了。
