### ISSUE TITLE
请更正您在 leetcode 网站上显示的电子邮件

### ISSUE THREAD

**Issue by LC-please-reply** [LeetCode-Feedback/LeetCode-Feedback#9169]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
不适用

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例
- [x] 网站内容不准确

**描述**
如 https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8484, https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8443, https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8069, https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/9033, https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/9071 中所述 LeetCode 网站上列出的 LeetCode Zendesk 支持电子邮件 support@leetcode.com 似乎不起作用。

**你使用的语言**
不适用

**你提交或者运行的代码**
不适用

**期望行为**
LeetCode 网站上列出了正确且受监控的电子邮件地址。

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给相关团队会尽快确认的，给您带来的不便敬请谅解。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，后续可以点击「[https://support.leetcode-cn.com/hc/kb/section/1115013」](https://support.leetcode-cn.com/hc/kb/section/1115013%E3%80%8D) 提交工单反馈，请知晓～
