### ISSUE TITLE
104. 二叉树的最大深度（使用Go语言解题时，单个测试用例解答正确，提交答案后相同的单元测试用例解答错误）

### ISSUE THREAD

**Issue by xtymbbt** [LeetCode-Feedback/LeetCode-Feedback#917]
** Bug 类型**
- [ ] 题目  104
- [ ] 题解  二叉树的最大深度
- [ ] 编程语言  Golang

**描述**
提交答案后，当输入为[]时，显示答案为3
但是在单元测试用例中输入[]时，我的代码运行结果为0，符合预期答案。

**你使用的语言**
Golang

**你提交或者运行的代码**
```
var depth = 0

func maxDepth(root *TreeNode) int {
	if root == nil {
		return depth
	}
	depth++
	var hereDepth = depth
	dfs(root.Left, hereDepth)
	dfs(root.Right, hereDepth)
	return depth
}

func dfs(root *TreeNode, hereDepth int)  {
	if root == nil {
		if hereDepth > depth {
			depth = hereDepth
		}
	} else {
		hereDepth++
        fmt.Printf("root.Val=%d, hereDepth=%d\n", root.Val, hereDepth)
		dfs(root.Left, hereDepth)
		dfs(root.Right, hereDepth)
	}
}
```

**期望行为**
应该是leetcode后台的判题代码有问题，并非我的代码问题

**屏幕截图**
无

**额外的上下文**
无

**Comment by feiceh** [comment]
你好，建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/ 。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至 [力扣圈子](https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=) 进行题目交流，以获得更好的支持哟～
