### ISSUE TITLE
345. Reverse Vowels of a String

### ISSUE THREAD

**Issue by 0417taehyun** [LeetCode-Feedback/LeetCode-Feedback#9172]
#### Your LeetCode username

0417taehyun

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Need to add a sentence, *both lower and upper cases*, in the description.

The sentence in the description part, *and they can appear in both cases*, can be misunderstood as being appeared multiple times.

Thus, it might be better to fix like the below.

```
The vowels are 'a', 'e', 'i', 'o', and 'u', and they can be both lower and upper cases, and appear in multiple times.
```

#### Code you used for Submit/Run operation

```Python
class Solution:
    def reverseVowels(self, s: str) -> str:
        VOWELS: set = { "a", "e", "i", "o", "u", "A", "E", "I", "O", "U" }
            
        characters: list[str] = list(s)
        left, right = 0, len(characters) - 1
        while left < right:
            left_value, right_value = characters[left], characters[right]
            if left_value in VOWELS and right_value in VOWELS:
                characters[left], characters[right] = characters[right], characters[left]
                left += 1
                right -= 1
            elif left_value in VOWELS and right_value not in VOWELS:
                right -= 1
            elif left_value not in VOWELS and right_value in VOWELS:
                left += 1
            else:
                left += 1
                right -= 1
        
        return "".join(characters)
```

#### Language used for code

Python

#### Expected behavior

Need to describe clearly.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Updated the last statement to specify "lower and upper" cases. We appreciate your support!
