### ISSUE TITLE
707. 设计链表

### ISSUE THREAD

**Issue by lqzo** [LeetCode-Feedback/LeetCode-Feedback#9173]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
https://leetcode.cn/u/liqingzhou/

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目给出的数据范围有误

中文:
<img width="322" alt="中文版截图" src="https://user-images.githubusercontent.com/30641714/191877047-023d875f-e086-4d29-b7ee-f48a5b70db92.png">

英文:
<img width="626" alt="英文版截图" src="https://user-images.githubusercontent.com/30641714/191877071-f27fa678-acb1-499c-b327-9ba74353c74b.png">

val 含 0 的测试用例:
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/30641714/191877269-44d3ada7-c1e8-47c0-a109-128d42e28385.png">

**期望行为**
更正中文版提示

**Comment by lqzo** [comment]
中文版描述中提到 如果 index < 0 时需要特殊处理
<img width="710" alt="image" src="https://user-images.githubusercontent.com/30641714/191877474-d8f7aa12-7a62-423a-b2ed-e76b4ed8adbf.png">

但是如果 index 为负数时，会发生异常
<img width="719" alt="image" src="https://user-images.githubusercontent.com/30641714/191877418-2b7ce47d-103e-4ac5-9929-8c96b75be9b8.png">

**Comment by feiceh** [comment]
你好，当前题面已更新，ID：liqingzhou 给予积分奖励，请查收。
