### ISSUE TITLE
Missing Test Case: 142. Linked List Cycle II

### ISSUE THREAD

**Issue by nxabdullah** [LeetCode-Feedback/LeetCode-Feedback#9175]
#### Your LeetCode username
nxabdullah

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The question wants us to return a node where the cycle begins. However, you can currently solve this problem by using an algorithm to detect a duplicate value in the linked list. This is because there is no test case that covers nodes with duplicate values. There is also no constraint stating if duplicate values are allowed in the input or not, so it can be assumed that they are not allowed. 

The code below is an algorithm to detect a duplicate value in the linked list, yet, it will pass all the test cases and submit! 

#### Code you used for Submit/Run operation

```

def detectCycle(self, head):
        hashT = {}
        while head:
            if head in hashT: return head
            hashT[head] = 0
            head = head.next
        return None
```

#### Language used for code

Python

#### Expected behavior

In reality, that solution should not work. Take the following input:
`head = [3, 3, 3, 3], pos = 2`

In this case, the node at index 3 points to the node at index 2.. thus the node at index 2 is the start of the cycle. However, the algorithm above would return the node at index 1 but the submission will be accepted because there is no such test case covering this situation. 

#### Screenshots

![image](https://user-images.githubusercontent.com/90593598/191886265-6ebac972-ac74-421b-bf20-83972b16ac8b.png)

#### Additional context

Any input with duplicate values should suffice.. I suggest 
`head = [3, 3, 3, 3], pos = 2`
Expected output: `tail connects to node index 2`

but you can easily have others like
`head = [1, 2, 3, 3, 3, 3, 5, 9, -5], pos = 4`
expected output: `tail connects to node index 4`

The code submission Accepted Link: https://leetcode.com/submissions/detail/806861841/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by nxabdullah** [comment]
The code submission Accepted Link: https://leetcode.com/submissions/detail/806861841/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Did not add the test cases because the submission linked gives AC on the cases mentioned here. We appreciate your support!
