### ISSUE TITLE
[Feature Request] Code Editor

### ISSUE THREAD

**Issue by JustABeginning** [LeetCode-Feedback/LeetCode-Feedback#9176]
Hey **LeetCode**, please add **Atom** *OneDark* & *OneLight* Themes for Code Editor. Additionally, *.vimrc*  file support for **Vim** Mode would be highly appreciable.

**Comment by GuruTheCoderYoutube** [comment]
Wait, is there a code editor?

**Comment by JustABeginning** [comment]
> Wait, is there a code editor?

I mean the leetcode web editor, where we write the code

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
