### ISSUE TITLE
Missing Test Case - 79. Word Search

### ISSUE THREAD

**Issue by hhhirokunnn** [LeetCode-Feedback/LeetCode-Feedback#9178]
#### Your LeetCode username

m999hiro

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In my console, given solutions got time exceeded.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def exist(self, board, word):
        """
        :type board: List[List[str]]
        :type word: str
        :rtype: bool
        """
        self.ROWS = len(board)
        self.COLS = len(board[0])
        self.board = board

        for row in range(self.ROWS):
            for col in range(self.COLS):
                if self.backtrack(row, col, word):
                    return True

        # no match found after all exploration
        return False


    def backtrack(self, row, col, suffix):
        # bottom case: we find match for each letter in the word
        if len(suffix) == 0:
            return True

        # Check the current status, before jumping into backtracking
        if row < 0 or row == self.ROWS or col < 0 or col == self.COLS \
                or self.board[row][col] != suffix[0]:
            return False

        ret = False
        # mark the choice before exploring further.
        self.board[row][col] = '#'
        # explore the 4 neighbor directions
        for rowOffset, colOffset in [(0, 1), (1, 0), (0, -1), (-1, 0)]:
            ret = self.backtrack(row + rowOffset, col + colOffset, suffix[1:])
            # break instead of return directly to do some cleanup afterwards
            if ret: break

        # revert the change, a clean slate and no side-effect
        self.board[row][col] = suffix[0]

        # Tried all directions, and did not find any match
        return ret

```

#### Language used for code

Python, Python3

#### Expected behavior

Succeed all test cases.

#### Screenshots

![Screenshot from 2022-09-23 20-07-20](https://user-images.githubusercontent.com/22176379/191947864-f6d9db7b-cbca-44b6-8d37-97648817517c.png)

**Comment by LC-Pam** [comment]
Thank you for contacting LeetCode's Support Team.

Your submission is resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

Please note that the test case you see on the "details" page shows which test case the program stops running at when the time limit has exceeded; it's not a test case that causes your program to exceed the time limit. 

I'd recommend checking out accepted submissions from the discuss tab of the problem page or posting your code there to get support from other users. Unfortunately, we do not disclose the time limit as we want our users to debug and improve their code to get it accepted. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
