### ISSUE TITLE
79. Word Search - Time Limit Exceeded

### ISSUE THREAD

**Issue by btpf** [LeetCode-Feedback/LeetCode-Feedback#9181]
#### Your LeetCode username
Username: [btpf](https://leetcode.com/btpf/)

#### Category of the bug
- [ ] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem relates to this question: https://leetcode.com/problems/word-search/

When I copy and paste the top python solutions from the discussion, most answers will exceed the time limit.
For instance: https://leetcode.com/problems/word-search/discuss/27660/Python-dfs-solution-with-comments.

Even a friend with leetcode premium tried running the official python solution. This also TLEs.
Perhaps the time limit should be raised for python and slower languages?

**Comment by btpf** [comment]
Related to https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/9178#issue-1383643381
This reply was given.
> Your submission is resulting in TLE for possibly one of the following reasons: Your code has an underlying infinite loop. Your algorithm is too slow and has high time complexity.

If this is the case, the **official** solution should be revised.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
