### ISSUE TITLE
383. Ransom Note: Bug in the code from solution video 

### ISSUE THREAD

**Issue by F4NSY** [LeetCode-Feedback/LeetCode-Feedback#9183]
In the solution video, the tutor used the variable i from the code block of the for loop, to specify which character to be removed in the magazine string. But he should have used the variable matchingIndex because using the variable i will only remove all the characters of magazine string starting from index 0 up to the length of the ransomNote string - 1 rather than removing the character that should really be removed. I'll attach underneath the code from the solution video (which is buggy) and the supposed to be code (which is the fix). 

Buggy Code:
```
        for(int i = 0; i < ransomNote.length(); i++) {
            char ch = ransomNote.charAt(i);

            int matchingIndex = magazine.indexOf(ch);

            if(matchingIndex == -1) return false;

            magazine = magazine.substring(0, i) + magazine.substring(i + 1);
        }
        
        return true;
```
Code Fix:
```
        for(int i = 0; i < ransomNote.length(); i++) {
            char ch = ransomNote.charAt(i);

            int matchingIndex = magazine.indexOf(ch);

            if(matchingIndex == -1) return false;

            magazine = magazine.substring(0, matchingIndex) + magazine.substring(matchingIndex + 1);
        }
        
        return true;
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
