### ISSUE TITLE
Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by aavoronin** [LeetCode-Feedback/LeetCode-Feedback#9190]
#### Your LeetCode username

aavoronin

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is no definite statement as to what return value should be

#### Code you used for Submit/Run operation

```
// NO CODE IS APPLICABLE, THIS IS ABOUT THE PROBLEM STATEMENT ITSELF 

// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.We appreciate your support!
