### ISSUE TITLE
Keys to Design a Hash Table - Typo in the table

### ISSUE THREAD

**Issue by supamasS** [LeetCode-Feedback/LeetCode-Feedback#9193]
![](https://s3-lc-upload.s3.amazonaws.com/uploads/2018/05/04/screen-shot-2018-05-04-at-145454.png)

The last entry in the table is incorrect. It should be "size < 5" or if "size < 10" is kept, then the last term in the last column should be "x9 * 4^9".

Additionally, for both of the last 2 rows in the table, the "<" symbol should be "<=" instead, since there are 10 numbers representing each key, we would have x0, x1, ..., x9. If we say "size < 10", it means the max size is 9 and can be represented by x0, x1, ..., x8 instead.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by supamasS** [comment]
Sorry for the delay. Here's the page link.

https://leetcode.com/explore/learn/card/hash-table/182/practical-applications/1110/


> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The problem page link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
