### ISSUE TITLE
Rust is missing - 1597. Build Binary Expression Tree From Infix Expression

### ISSUE THREAD

**Issue by jeroenvervaeke** [LeetCode-Feedback/LeetCode-Feedback#9195]
#### Your LeetCode username
jeroenvervaeke

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This answer cannot be answered in rust

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
