### ISSUE TITLE
392. Is Subsequence

### ISSUE THREAD

**Issue by GDaniil17** [LeetCode-Feedback/LeetCode-Feedback#9196]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Returnable value is different from printable one (same logic)

#### Code you used for Submit/Run operation

```
class Solution:
    def isSubsequence(self, s: str, t: str) -> bool:
        i = 0
        j = 0
        while(i < len(s) and j < len(t)):
            if(s[i] == t[j]):
                i += 1
            j += 1
        print(["false","true"][len(s) == i])
        
        return ["false","true"][len(s) == i]
```

#### Language used for code
Python3

#### Expected behavior
Returnable value should be the same as printable one

#### Screenshots
![image](https://user-images.githubusercontent.com/32881349/192121472-61e129bb-cfb8-466e-8b4a-80bb2856f0a9.png)

#### Additional context
Returnable value is different from printable one (same logic)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
