### ISSUE TITLE
225. 用队列实现栈 测试用例不足

### ISSUE THREAD

**Issue by 1418540213** [LeetCode-Feedback/LeetCode-Feedback#9197]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
许人湟

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [1] 缺少测试用例

**描述**
缺少测试用例，高赞题解代码随想录单队列错误实现能通过，其排序应该写在push中，而不是pop

**你使用的语言**
C++

**你提交或者运行的代码**
```
class MyStack {
public:
    queue<int> que;
    /** Initialize your data structure here. */
    MyStack() {

    }
    /** Push element x onto stack. */
    void push(int x) {
        que.push(x);
    }
    /** Removes the element on top of the stack and returns that element. */
    int pop() {
        int size = que.size();
        size--;
        while (size--) { // 将队列头部的元素（除了最后一个元素外） 重新添加到队列尾部
            que.push(que.front());
            que.pop();
        }
        int result = que.front(); // 此时弹出的元素顺序就是栈的顺序了
        que.pop();
        return result;
    }

    /** Get the top element. */
    int top() {
        return que.back();
    }

    /** Returns whether the stack is empty. */
    bool empty() {
        return que.empty();
    }
};
```

**期望行为**
增加测试用例

**屏幕截图**
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/95291196/192127057-19ef7dcc-413c-4d4d-bab1-8c69b66fa9a8.png">

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，简体题不需要卡的这么死；力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
