### ISSUE TITLE
Missing Test Case - 2421. Number of Good Paths

### ISSUE THREAD

**Issue by 981377660LMT** [LeetCode-Feedback/LeetCode-Feedback#9198]
#### Your LeetCode username

981377660LMT
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9650821/big-head-center-tail.txt)

#### Code you used for Submit/Run operation

https://leetcode.com/problems/number-of-good-paths/discuss/2620632/Python-DFS

```py
class Solution:
    def numberOfGoodPaths(self, vals: List[int], edges: List[List[int]]) -> int:
        total=len(vals)
        graph=collections.defaultdict(set)
        for a,b in edges:
            graph[a].add(b)
            graph[b].add(a)
        visit=[0]*total
        self.result=0
        
        def DFS(node):
            visit[node]=1
            self.result+=1
            counter=Counter([vals[node]])
            for nei in graph[node]:
                if not visit[nei]: 
                    for item,freq in DFS(nei).items():
                        if item>=vals[node]:
                            self.result+=counter[item]*freq
                            counter[item]+=freq
            return counter
        
        DFS(total-1)
        return self.result
```

#### Language used for code

python3

#### Expected behavior

The code gets Time Limit Exceed(TLE) 

#### Screenshots

![image](https://user-images.githubusercontent.com/45849137/192415732-90e0b09e-3f23-441e-9556-a0c43e7511d3.png)

#### Additional context

The time complexity of this code is `O(n^2)` thus should be judged as TLE.

**Comment by 981377660LMT** [comment]
> Thank you for reaching out to us. I've relayed this issue to our team to investigate.

Here is a more stronger test case which judges all O(n^2) solution(eg:dfs without Heuristic merge) TLE.
Hope you will see this :).
[big-head-center-tail-with-symmetric-vals-chain.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9650742/big-head-center-tail-with-symmetric-vals-chain.txt)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
