### ISSUE TITLE
“程序员面试经典（第 6 版）”应改为“程序员面试金典（第 6 版）”

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#920]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 其他

**描述**
在主页 https://leetcode-cn.com/ 的右侧，书名错写成了“程序员面试**经**典（第 6 版）”，应该是“程序员面试**金**典（第 6 版）”（见屏幕截图部分）。

**你使用的语言**
无

**你提交或者运行的代码**
无

**期望行为**
在主页 https://leetcode-cn.com/ 的右侧，书名错写成了“程序员面试**经**典（第 6 版）”，应该是“程序员面试**金**典（第 6 版）”（见屏幕截图部分）。

**屏幕截图**
![image](https://user-images.githubusercontent.com/12067364/92076039-59a0da00-edec-11ea-9d97-7314a42c555d.png)

**额外的上下文**
无

**Comment by feiceh** [comment]
感谢反馈，该问题已转给相关团队会及时修改的。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先关闭，后续使用中有任何问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。
