### ISSUE TITLE
Missing Test Case - 622. Design Circular Queue

### ISSUE THREAD

**Issue by vikashDevZ** [LeetCode-Feedback/LeetCode-Feedback#9200]
#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?
