### ISSUE TITLE
967. Numbers With Same Consecutive Differences - Incorrect Output Datatype is Accepted

### ISSUE THREAD

**Issue by Vashesh08** [LeetCode-Feedback/LeetCode-Feedback#9201]
#### Your LeetCode username
vashesh2001

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For this question : https://leetcode.com/problems/numbers-with-same-consecutive-differences/
The question mentions returning answer array in the form of an array of integers. Even when we return an array of strings (in Python), it works. You must test if the answer is returned in the correct form.

#### Code you used for Submit/Run operation

```py
class Solution:
    def numsSameConsecDiff(self, n: int, k: int) -> List[int]:
        result = []
        
        def recurse(number):
            if len(number) == n:
                result.append(number)
                return
            
            for i in range(10):
                if abs(int(number[-1]) - i) == k:
                    recurse(number+str(i))
            
        for i in range(1,10):
            recurse(str(i))
        
        return result
```

#### Language used for code
Python

#### Expected behavior
My  code should generate an error as I am returning the answer in a list/array of strings whereas the answer is expected to be in the form of array of integers.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
