### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by mbiesiad** [LeetCode-Feedback/LeetCode-Feedback#9202]
#### Your LeetCode username
mbiesiad

#### Category of the bug
Issue

#### Description of the bug
Uncaught errors and warning occurs, visible in dev Console.

#### Repro steps
1. Go to page: `https://leetcode.com` and `https://leetcode.com/explore`
2. Check DevTools - Console

#### Screenshots

![image](https://user-images.githubusercontent.com/18367606/192139210-3c74aade-976b-452b-a792-5a9bc5bd1e4e.png)

![image](https://user-images.githubusercontent.com/18367606/192139223-23e8cc33-9a0c-43e0-a0f8-b294a4806810.png)
![image](https://user-images.githubusercontent.com/18367606/192139232-a8dd50c2-ab20-4e67-a008-7a4577b979ce.png)

#### Additional context
Browser: Chromium based and Firefox

Best wishes,

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
