### ISSUE TITLE
Leetcodes-interview-crash-course-data-structures-and-algorithms

### ISSUE THREAD

**Issue by plemanach** [LeetCode-Feedback/LeetCode-Feedback#9203]
Hello,

I noticed a mistake on the Java algo regarding prefix sum.

https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/703/arraystrings/4503/

`public boolean[] answerQueries(int[] nums, int[][] queries, int limit) {
    int[] prefix = new int[nums.length];
    prefix[0] = nums[0];

    for (int i = 1; i < nums.length; i++) {
        prefix[i] = prefix[i - 1] + nums[i];
    }

    boolean[] ans = new boolean[queries.length];
    for (int i = 0; i < queries.length; i++) {
        int x = queries[i][0], y = queries[i][1];
        int curr = prefix[y] - prefix[i] + nums[x];
        ans[i] = curr < limit;
    }
    
    return ans;
}`

it should be :
` int curr = prefix[y] - prefix[x] + nums[x];
// x instead of i in prefix[x] 
`

Best Regards,

Patrice

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
