### ISSUE TITLE
A typo in 622. Design Circular Queue

### ISSUE THREAD

**Issue by medvied** [LeetCode-Feedback/LeetCode-Feedback#9204]
#### Your LeetCode username

medvied

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

The task description has the following:

> Implementation the MyCircularQueue class:

while other design problems have it like this:

> Implement the MyCircularQueue class:

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

The task description should have `Implementation` replaced with `Implement` in the following sentence:

>  Implementation the MyCircularQueue class:

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
