### ISSUE TITLE
Accepted Wrong solution - 105. Construct Binary Tree from Preorder and Inorder Traversal

### ISSUE THREAD

**Issue by vishalkumar-sahu** [LeetCode-Feedback/LeetCode-Feedback#9208]
#### Your LeetCode username

user8040Co

#### Category of the bug
- [ ] Solution

#### Description of the bug

> Refer screenshot attached for both what should be and what is issue marked in red spot below

As in this recursive call, I am always moving 1 less than of Inorder end for the left subtree of node.
Which actually should be 1 less than the root element found in the Inorder array.
Assume, 
preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]
inStart - 0, i.e start index of inorder array
inEnd - inorder.length - 1, i.e last index of inorder array

In every step for creating left subarray I am considering decreasing the inEnd index by 1,
but which should be the root index we have found - 1 .i.e mid - 1

#### Code you used for Submit/Run operation

```
// [Construct Binary Tree from Preorder and Inorder Traversal](https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/)
class Solution {
    public TreeNode buildTree(int[] preorder, int[] inorder) {
        
        Map<Integer, Integer> map = new HashMap<Integer, Integer>();
        for(int i = 0; i < inorder.length; i++){
            map.put(inorder[i], i);
        }
    
        TreeNode node = build(preorder, 0, preorder.length - 1, inorder, 0, inorder.length - 1, map);
        
        return node;
    }
    
    public TreeNode build(int []preorder, int preStart, int preEnd, int []inorder, int inStart, int inEnd, Map<Integer, Integer> map){
        
        if(preStart > preEnd || inStart > inEnd){
            return null;
        }
        
        TreeNode temp = new TreeNode(preorder[preStart]);
        
        int val = map.get(temp.val);
        int length = val - inStart;
        
        temp.left = build(preorder, preStart + 1, preStart + length, inorder, inStart, inEnd - 1, map);
        
        temp.right = build(preorder, preStart + length + 1, preEnd, inorder, val + 1, inEnd, map);
        
        return temp;
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

![image](https://user-images.githubusercontent.com/77752044/192159951-0be00b2e-6300-4d75-be53-07699628ba9a.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/77752044/192160004-bde5e509-a80a-4b48-8823-1995f70ee67c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've rejected your feedback. We appreciate your support!
