### ISSUE TITLE
Problem #2420 ambiguous question description

### ISSUE THREAD

**Issue by WendaGuo** [LeetCode-Feedback/LeetCode-Feedback#9209]
#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description is:
The k elements that are just before the index i are in non-increasing order.
The k elements that are just after the index i are in non-decreasing order.

The test cases treated ##non-increasing## as decreasing actually.

From my understand it can also be no order at all (neither increasing nor decreasing).

#### Code you used for Submit/Run operation

```
import java.util.*;
import java.util.stream.*;
class Solution {
    public List<Integer> goodIndices(int[] nums, int k) {
        if (k==1)
            return IntStream.range(k,nums.length-k).boxed().collect(Collectors.toList());
        ArrayList<Integer> answer = new ArrayList<>();
        int leftBp=0, rightBp=k+1, n=nums.length;
        for (int i=1; i<k; i++) {
            if (nums[i] <= nums[i-1])
                leftBp = i;
        }
        for (int i=k+2; i<=2*k && i<n; i++) {
            if (nums[i] >= nums[i-1])
                rightBp = i;
        }
        for (int i=k; i<n-k; i++) {
            if (leftBp > i-k && rightBp > i+1)
                answer.add(i);
            if (nums[i] <= nums[i-1])
                leftBp = i;
            if (i+k+1<n && nums[i+k+1] >= nums[i+k])
                rightBp = i+k+1;
        }
        return answer;
    }
}
```

#### Language used for code

Java

**Comment by LC-Pam** [comment]
Thank you for your time. Nothing is wrong with the statement. Non-Increasing means the sequence does not increase. That means each an element cannot be larger than the previous one. This is exactly what exists in the test cases and examples.  We appreciate your support!
