### ISSUE TITLE
Update the problem [375 Guess Number Higher or Lower II] description and example case

### ISSUE THREAD

**Issue by zjzsliyang** [LeetCode-Feedback/LeetCode-Feedback#921]
#### Your LeetCode username

zjzsliyang

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The problem description and the example case is unclear, as many discussions mentioned [1](https://leetcode.com/problems/guess-number-higher-or-lower-ii/discuss/84762/Improve-the-Question-and-Example) [2](https://leetcode.com/problems/guess-number-higher-or-lower-ii/discuss/84766/Clarification-on-the-problem-description.-Problem-description-need-to-be-updated-!!!).

**Comment by lc-pam** [comment]
Hi @zjzsliyang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @zjzsliyang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
