### ISSUE TITLE
Prefix Sum - wrong Java solution for Example 1

### ISSUE THREAD

**Issue by vassilvk** [LeetCode-Feedback/LeetCode-Feedback#9210]
#### Your LeetCode username

vassilvk

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Java solution of **Example 1** on page **Prefix Sum**, has a bug on **line 12**:

```java
int curr = prefix[y] - prefix[i] + nums[x];
```

It should read as follows:

```java
int curr = prefix[y] - prefix[x] + nums[x];
```

#### Language used for code

Java

#### Expected behavior

**Line 12** of the Java solution of **Example 1** of **Prefix Sum** should read:

```java
int curr = prefix[y] - prefix[x] + nums[x];
```

#### Screenshots

![image](https://user-images.githubusercontent.com/317808/192166996-e61c0b8a-06ea-41dd-bbbb-3a5ddcd33ae2.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by vassilvk** [comment]
Hi @LC-Pam,

Page link: https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/703/arraystrings/4503/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
