### ISSUE TITLE
Missing Test Case - 16. 3Sum Closest

### ISSUE THREAD

**Issue by regresscheck** [LeetCode-Feedback/LeetCode-Feedback#9212]
#### Your LeetCode username

regresscheck

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Binary-search solutions pass current test cases, but they don't always work.
Example of the test that will fail the code below(which is Accepted by the system):
```
[1, 3, 4, 7, 8, 9]
15
```

#### Code you used for Submit/Run operation

```
class Solution:
    def threeSumClosest(self, nums: List[int], target: int) -> int:
        def binarySearch(nums: List[int], left, right, target):
            while left < right:
                mid = (left + right) // 2
                if nums[mid] == target:
                    return mid
                if nums[mid] < target:
                    left = mid + 1
                else:
                    right = mid - 1
            return left
            
            
        
        best = sum(nums[0:3])
        nums = sorted(nums)
        
        left = 0
        right = len(nums) - 1
        
        while left < right - 1:
            mid = binarySearch(nums, left + 1, right - 1, target - nums[left] - nums[right])
            current = nums[left] + nums[mid] + nums[right]
            
            if abs(best - target) > abs(current - target):
                best = current
            
            if current < target:
                left += 1
            else:
                right -= 1
            
        return best
```

#### Language used for code

Python

#### Expected behavior

The code shouldn't be Accepted, see the test above.

#### Additional context

It may be possible that some binary-search solutions will pass the test depending on conditions used in binary search and outer loop. So it's worth adding few more tests similar to the one above.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
