### ISSUE TITLE
Missing Test Case - 2224. Minimum Number of Operations to Convert Time

### ISSUE THREAD

**Issue by RJBornToWin** [LeetCode-Feedback/LeetCode-Feedback#9213]
#### Your LeetCode username
JRajasri 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Given testcases covers only locally optimal solution

#### Code you used for Submit/Run operation

```
class Solution {
    public int convertTime(String current, String correct) {
        int[] options =  {1,5,15,60};
        
        int diff = findDifference(current, correct);
        int op = 0;
        if (diff > 0) {
            op = findMinOp(diff, options);
        }
        System.out.println(op);
        return op;
    }
    
    int findDifference(String current, String correct) {
        int curH = Integer.parseInt(current.substring(0,2));
        int curM = Integer.parseInt(current.substring(3,5));
        
        int corH = Integer.parseInt(correct.substring(0,2));
        int corM = Integer.parseInt(correct.substring(3,5));
        
        int giv = curH * 60 + curM;
        int tar = corH * 60 + corM;
        
        return tar-giv;
    }
    
    int findMinOp(int totMins, int[] options) {
        int op = 0;
        ArrayList<Integer> ls = new ArrayList<Integer>();
        for (int i=options.length-1; i>=0; i--) {
            while(totMins >= options[i]) {
                System.out.print(options[i] + "|");
                ls.add(options[i]);
                totMins -= options[i];
                op++;
            }
        }
        
        return op;
    }
}
```

#### Language used for code
Java

#### Expected behavior
This is an incorrect solution. But this code gets accepted. If we change the values of options in the above code to {1, 10, 15, 25}; and for input "02:30" and "04:08", this solution gives 12 as answer but the correct answer is 8 i.e 25, 25, 15, 15, 15, 1, 1, 1

#### Additional context
 This accepts greedy approach as solution which is only locally optimal and doesn't necessarily predict the global best solution. So adding the above test case checks if the globally optimal solution is written or not

**Comment by RJBornToWin** [comment]
Updated category

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've added this test case but it did not fail any solution. We appreciate your support!
