### ISSUE TITLE
Data Structures and Algorithms Crash Course - Cheatsheets section

### ISSUE THREAD

**Issue by Andrey-Pavlov** [LeetCode-Feedback/LeetCode-Feedback#9215]
#### Your LeetCode username
Chuxel

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Incorrect description for time complexity: "Access or modify element at arbitrary index: O(n)". It must be O(1)

#### Expected behavior
Text: "Access or modify element at arbitrary index: O(1)"

#### Screenshots
![image](https://user-images.githubusercontent.com/7976740/192217700-514ef06d-446e-4c74-8abb-75e946409763.png)
![image](https://user-images.githubusercontent.com/7976740/192217712-9c1a8225-d24e-43bd-8034-6e4a3ebc4151.png)

#### Additional context
https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/713/interviews-and-tools/4547/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
