### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by caihh123** [LeetCode-Feedback/LeetCode-Feedback#9216]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名caihh123

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
没有使用算法，直接返回，应该禁止

**你使用的语言**
Go

**你提交或者运行的代码**
```
func hanota(A []int, B []int, C []int) []int {
	return A
}
```

**期望行为**
报错

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
您好，在与相关团队核实后：不处理 （本题的做题要求需要用户自觉遵守），本次 Ticket 将关闭，感谢您的反馈和支持。
