### ISSUE TITLE
Data Structures and Algorithms Crash Course - Graphs quiz - Incorrect answer

### ISSUE THREAD

**Issue by Andrey-Pavlov** [LeetCode-Feedback/LeetCode-Feedback#9217]
#### Your LeetCode username
Chuxel

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
_Graphs quiz - First question - has incorrect answer_
Which of the following is true about the above graph?
The graph is cyclic. - **false**

#### Expected behavior
Which of the following is true about the above graph?
The graph is cyclic. - **true**

#### Screenshots
![image](https://user-images.githubusercontent.com/7976740/192260381-dc904281-851f-44e2-899f-1ddb0e2dccae.png)

#### Additional context
https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/707/traversals-trees-graphs/4644/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Y We appreciate your support!
