### ISSUE TITLE
Binary Search Tree Definition seems to be wrong

### ISSUE THREAD

**Issue by omscse** [LeetCode-Feedback/LeetCode-Feedback#9219]
#### Your LeetCode username
omscse

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Definition/Article 

#### Description of the bug
Binary Search Tree definition seems to be wrong in the article https://leetcode.com/explore/learn/card/introduction-to-data-structure-binary-search-tree/140/introduction-to-a-bst/1017/.

It says:

A binary search tree (BST), a special form of a binary tree, satisfies the binary search property:

The value in each node must be greater than **(or equal to)** any values stored in its left subtree.
The value in each node must be less than **(or equal to)** any values stored in its right subtree.

As BST cannot have duplicates, how can a node be equal to some other node?

Even in the next session, https://leetcode.com/explore/learn/card/introduction-to-data-structure-binary-search-tree/140/introduction-to-a-bst/997/, duplicates are treated as invalid BST.
Both [2,2,3] and [2,1,2] are treated as invalid BST in this section. So the definition in the first section requires correction.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.We appreciate your support!
