### ISSUE TITLE
Missing testcase in 1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit

### ISSUE THREAD

**Issue by ssanjeev2424** [LeetCode-Feedback/LeetCode-Feedback#922]
ssanjeev2424

#### Category of the bug - Test case missing
- [1] Question

#### Description of the bug

Crucial test case missing

#### Code you used for Submit/Run operation

```
// 1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit
class Solution {
public:
    int longestSubarray(vector<int>& nums, int limit) {
        int ans = 0, i = 0, j = 1, n = nums.size(), mx, mn;
        
        set<int>:: iterator itr;
        S.insert(nums[0]);
        
        while(i < n) {
            mn = *(S.begin()), mx = *(--S.end());
            //printf("[%d,%d]: mx: %d mn: %d,   ans: %d\n", i, j, mx, mn, ans);
            
            if(mx - mn <= limit) {
                ans = max(ans, j - i);
                
                if(j < n) S.insert(nums[j++]);
                else break;
            }
            else {
                int k, val = nums[i];
                
                for(k=i; k<j; k++) if(nums[k] != val) break;
                i = k;
                
                S.erase(val);
            }
        }
        
        return ans;
    }
    
private:
    set<int> S;
};
```

#### Language used for code

C++

#### Expected behavior

With input:
"[2,2,2,4,4,2,5,5,5,5,5,2]
2" ,

expected behaviour is '6', but my code returns '8' and still gets AC

#### Screenshots

![image](https://user-images.githubusercontent.com/31368706/92145327-af4da480-ee35-11ea-9779-f37347dbf76f.png)
![image](https://user-images.githubusercontent.com/31368706/92145422-da37f880-ee35-11ea-9db2-8aa982140ee6.png)

#### Additional context

I was using a set to keep track of the elements present in the window (sliding window protocol),
when i choose to shrink the window, i simply deleted that element from the set..

but that element can also be there in between other elements in the window, and i won't be able to consider its effect in the later calculations..it will eventually affect my answer and produce incorrect output.

**Comment by lc-pam** [comment]
Hi @ssanjeev2424 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ssanjeev2424** [comment]
ok @lc-pam Thanks 👍

**Comment by lc-pam** [comment]
Hi @ssanjeev2424 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
