### ISSUE TITLE
Missing Test Case - 409. Longest Palindrome

### ISSUE THREAD

**Issue by Bmackgold** [LeetCode-Feedback/LeetCode-Feedback#9220]
class Solution:
    def longestPalindrome(self, s):
        ans = 0
        for v in collections.Counter(s).itervalues():            //Solution should be .values()
            ans += v / 2 * 2                                                //ops should be floor div //
            if ans % 2 == 0 and v % 2 == 1:
                ans += 1
        return ans

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The itervalues() is not an attribute and should be replaced by .values() because object is dict
and the indexing operation with v should be floor division i.e //
thanks

#### Code you used for Submit/Run operation

```
class Solution:
    def longestPalindrome(self, s: str) -> int:
        ans = 0
        for v in collections.Counter(s).values():
            ans += v // 2 * 2
            if ans % 2 == 0 and v % 2 == 1:
                ans += 1
        return ans
 
```

#### Language used for code

Python 3

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution is in py2 which has values and itervalues.
itervalues was removed from py3. We appreciate your support!
