### ISSUE TITLE
Missing Test Case - 2421. Number of Good Paths

### ISSUE THREAD

**Issue by 981377660LMT** [LeetCode-Feedback/LeetCode-Feedback#9221]
#### Your LeetCode username

981377660LMT
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[symmetric-vals-chain.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9650742/big-head-center-tail-with-symmetric-vals-chain.txt)

#### Code you used for Submit/Run operation

```py
class Solution:
    def numberOfGoodPaths(self, vals: List[int], edges: List[List[int]]) -> int:
        n = len(vals)
        res = n
        if n == 1:
            return 1
        c = Counter(vals)
        
        adj = defaultdict(list)
        for a, b in edges:
            adj[a].append(b)
            adj[b].append(a)
        
        def dfs(node, parent):
            nonlocal res
            mp = defaultdict(int)
            t = 0
            for e in adj[node]:
                if e == parent:
                    continue
                else:
                    d = dfs(e, node)
                    for a in d:
                        b = d[a]
                        if b == c[a]:
                            continue
                        if a >= vals[node]:
                            res += b * mp[a]
                            mp[a] += b

            res += mp[vals[node]]
            mp[vals[node]] += 1
            return mp
        
        dfs(0, -1)
        return res
```

#### Language used for code

python3

#### Expected behavior

The code gets Time Limit Exceed(TLE) 

#### Screenshots

![image](https://user-images.githubusercontent.com/45849137/192415332-43121524-1a65-444c-b831-3df1b110feab.png)

#### Additional context

I notice that the test case so far is lack of ability to resist **special tricks in dfs**(eg:brute dfs runs fast when symmetric vals are absent).
Here is a stronger test case which judges `O(n^2)` solutions(eg:dfs without heuristic merge) as TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
