### ISSUE TITLE
面试题 01.02. 判定是否互为字符重排，官方题解方法二与题目描述不符

### ISSUE THREAD

**Issue by x-xk** [LeetCode-Feedback/LeetCode-Feedback#9222]
**你的 LeetCode 用户名**
6RJZKPqbph

**Bug 类型**
-  题目
-  题解

**描述**
题解和题目描述不符，题目中并没有说明字符串中只存在小写字母，但是官方题解二中直接说字符串中只存在小写字母，并只申请了大小为26的int型数组table

**屏幕截图**
![image](https://user-images.githubusercontent.com/76646296/192416809-42b62c3a-e6fd-4cc5-8109-72cd97eb2ac2.png)

![image](https://user-images.githubusercontent.com/76646296/192416716-38287b47-e5b6-41f8-a535-739704517e13.png)

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by x-xk** [comment]
https://leetcode.cn/u/xx-k/

**Comment by x-xk** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励。

https://leetcode.cn/u/xx-k/

**Comment by feiceh** [comment]
已奖励，请查收。
