### ISSUE TITLE
题目【在排序数组中查找元素的第一个和最后一个位置】测试用例不完善

### ISSUE THREAD

**Issue by MoyanZitto** [LeetCode-Feedback/LeetCode-Feedback#9226]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
bigmoyan

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
问题https://leetcode.cn/problems/find-first-and-last-position-of-element-in-sorted-array/
缺乏测试用例导致C++情况下复杂度为O(n)的算法可以AC

这份代码调用了C++的STL泛型算法求解，其中std::reverse的复杂度是O(n)，但题目要求算法以O(logn)实现

**你使用的语言**
C++

**你提交或者运行的代码**
```
#include<iostream>
#include<algorithm>


class Solution {
public:
    vector<int> searchRange(vector<int>& nums, int target) {
        std::vector<int> res;
        std::vector<int>::const_iterator it = std::find(nums.begin(), nums.end(), target);
        if(it==nums.end()){
            
            res.push_back(-1);
            res.push_back(-1);
            return res;
        }

        res.push_back(it - nums.begin());

        // reverse
        std::reverse(nums.begin(), nums.end());

       std::vector<int>::const_iterator endit = std::find(nums.begin(), nums.end(), target);
        // we must have a result here
        res.push_back(nums.end() - endit - 1);
        return res;

    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
您好，在与相关团队核实后：仅要求用 O(logN)， 性能角度实际这题仍允许 O(N) 通过。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
