### ISSUE TITLE
默认代码模板的函数签名不对

### ISSUE THREAD

**Issue by gfgafn** [LeetCode-Feedback/LeetCode-Feedback#9227]
https://leetcode.cn/problems/shu-zu-zhong-zhong-fu-de-shu-zi-lcof/

**Bug 类型**
- [ ] 题目

**描述**
Rust默认代码模板的函数签名不对
> 数组 nums 里的所有数字都在 0～n-1 的范围内
限制：
2 <= n <= 100000

所以nums中的元素应该为`u32`类型，而不是`i32`类型

**你使用的语言**
Rust

**期望行为**
```rust
impl Solution {
    pub fn find_repeat_number(nums: Vec<u32>) -> u32 {

    }
}
```

**额外的上下文**
目前的函数签名
```rust
impl Solution {
    pub fn find_repeat_number(nums: Vec<i32>) -> i32 {

    }
}
```

**Comment by feiceh** [comment]
感谢反馈，经核实函数签名对题目没有影响，暂不作处理。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
