### ISSUE TITLE
Repeated Substring Pattern - Wrong testcase

### ISSUE THREAD

**Issue by gurnor28** [LeetCode-Feedback/LeetCode-Feedback#923]
There is a wrong test-case in Repeated Substring Pattern:

Given a non-empty string check if it can be constructed by taking a substring of it and appending multiple copies of the substring together. You may assume the given string consists of lowercase English letters only and its length will not exceed 10000.

TestCase: "abaababaab"

**Comment by Vikas-Jethwani** [comment]
@gurnor28  It is a valid test-case with the correct output as "true". The pattern being "abaab", if you repeat it twice you will get that given test case.
