### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by siaarzh** [LeetCode-Feedback/LeetCode-Feedback#9230]
#### LeetCode Username

siaarzh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

The test case for the string pair `aba` and `aab` does not pass in the Code Runner (button "Run Code"), but code passes the submission ("Submit" button).

#### Code you used for Submit/Run operation

```golang
func Equal(a, b []int) bool {
    if len(a) != len(b) {
        return false
    }
    for i, v := range a {
        if v != b[i] {
            return false
        }
    }
    return true
}

func isIsomorphic(s string, t string) bool {
    if len(s) != len(t) { return false }
    
    encodeString := func(s_ string) []int {
        i := 0
        s_hashmap := make(map[rune]int)
        s_slice := []int{}
        
        for _, letter := range s_ {
            if _, ok := s_hashmap[letter]; ok {
                s_slice = append(s_slice, s_hashmap[letter])
            } else {
                s_hashmap[letter] = i
                // s_slice = append(s_slice, s_hashmap[letter]) // <- correct solution commented out
                i += 1
            }
        }
        return s_slice
    }
    fmt.Println(encodeString(s), encodeString(t))
    return Equal(encodeString(s), encodeString(t))
}
```

#### Expected behavior

Submission should fail with the above code.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by siaarzh** [comment]
Yes sure, it's Golang.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
