### ISSUE TITLE
Missing Test Case - 877. Stone Game

### ISSUE THREAD

**Issue by Ankitsingh2001** [LeetCode-Feedback/LeetCode-Feedback#9231]
In this problem test case for all is true please change the test case 

![image](https://user-images.githubusercontent.com/89564535/192485256-d5e06cd0-cf2d-4c4f-846c-65f22c00760a.png)

**Comment by Ankitsingh2001** [comment]
the problem in test case

**Comment by stormsunshine** [comment]
Can you find a test case that should return false? If you can't find such a test case, you are wasting others' time.
