### ISSUE TITLE
Missing Test Case - 200. Number of Islands

### ISSUE THREAD

**Issue by malialtunsoy** [LeetCode-Feedback/LeetCode-Feedback#9232]
#### Your LeetCode username

malialtunsoy

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Submission and test case outputs are different from each other. The submission test case may problematic.

#### Code you used for Submit/Run operation

```
class Solution:
    pressed = []
    def helper(self,row,col,grid):
        if grid[row][col] == "1" and (row,col) not in self.pressed:
            self.pressed.append((row,col))  
            
            if row-1 >= 0:
                self.helper(row-1,col,grid)
            if row+1 < len(grid):
                self.helper(row+1,col,grid)
            if col-1 >= 0:
                self.helper(row,col-1,grid)
            if col+1 < len(grid[0]):
                self.helper(row,col+1,grid)
    
    def numIslands(self, grid: List[List[str]]) -> int:
        count = 0
        pressed = []
        for row in range(len(grid)):
            for col in range(len(grid[row])):
                if (row,col) not in self.pressed:
                    if grid[row][col] == "1":
                        count += 1
                        self.helper(row,col,grid)
        return count
                        
                
            
```

#### Language used for code

Python3

#### Expected behavior

I expected that my submission will passed since its passed the test while running as a test case. However, it did not passed the submission.

#### Screenshots

<img width="1423" alt="Screen Shot 2022-09-27 at 13 52 49" src="https://user-images.githubusercontent.com/45949554/192508074-be98d43f-f805-42e6-9ef6-87345698134b.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
