### ISSUE TITLE
838. Push Dominoes, Solution

### ISSUE THREAD

**Issue by MMajd** [LeetCode-Feedback/LeetCode-Feedback#9234]
#### Your LeetCode username
mmajd

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
A solution for Push Dominoes Problem (Problem 838)

#### Code you used for Submit/Run operation

```java
class Solution {
    public String pushDominoes(String s) {
        int n = s.length() + 2; 
        char[] A = new char[n]; 
        
        A[0] = 'L'; 
        A[n-1] = 'R';
        
        for (int i=1; i<n-1; i++) { 
            A[i] = s.charAt(i-1);
        }
        
        int i=0, j=0; 

        while (i < n) { 
            while (i < n && A[i] == '.') i++; 
            
            if (A[j] == 'R' && A[i] == 'L') { 
                int end = i; 
                while (++j < --end) {
                    A[end] = 'L'; 
                    A[j] = 'R'; 
                }
            }
            else if (A[j] == 'R' && A[i] == 'R' 
                    || A[j] == 'L' && A[i] == 'L') { 
                while(++j <= i) A[j]  = A[j-1]; 
            }
            
            j = i; 
            i += 1; 
        }
        
        return new String(Arrays.copyOfRange(A, 1, n-1));
    }
}
```

#### Language used for code
Java

#### Expected behavior
Solves Push Dominoes Problem

#### Intuition:
Situation that we need to update the string are
* Having R on the left-side and L on the right-side
* Having L on the left-side and also L on the right-side
* Having R on the left-side and also R on the right-side
* Other than these configurations no need to update the string, or will be eliminated and reduced to a one of the fore-mentioned ones

Note: when having R-L situation we need to update from the left and from the right at the same time and stop when left-pointer == right-pointer

#### Possible configuration and result updates 
* R - - - - - L, when space between R and L is odd size, will result in R R R - L L L
* R - - - - L, when space between R and L is even, will result in R R R L L L
* R - - - - R, situation will result in all R's
* L - - - ... - L, situation will result in all L's
* L - - - ... - R, situation need no change

#### Important note
To eliminate situations such as having on the left-side a '.' and on the right 'L', or 'R' on the left-side and '.' on the right-side we need to add two more characters at the start and end of the string.

* Add L on the start, because L doesn't affect what comes after it
* Add R on the end, because R doesn't affect what comes before it

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your code to the team. We appreciate your support!
