### ISSUE TITLE
Wrong output for test case . String to Integer (atoi), 

### ISSUE THREAD

**Issue by rdsharma3** [LeetCode-Feedback/LeetCode-Feedback#9235]
#### Your LeetCode username
rdsharma3333

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When I am running the test case  returning me the -42 but in leetcode it is returning 0. Using Golang version go1.19.1 darwin/arm64

#### Code you used for Submit/Run operation

 ```
func myAtoi(s string) int {
	isNegative := false
	isPositive := false
	intArray := make([]string, 0)
	strArray := []byte(s)
	for _, char := range strArray {
		if char == 32 {
			continue
		} else if string(char) == "+" {
			if isNegative {
				break
			}
			isPositive = true
		} else if string(char) == "-" {
			if isPositive {
				break
			}
			isNegative = true
		} else if char >= 48 && char <= 57 {
			isPositive = false
			intArray = append(intArray, string(char))
		} else {
			break
		}
	}
	num := convertArrayToInt(intArray)
	if num > math.MaxInt32 && isNegative {
		num = math.MaxInt32 + 1
	}
	if num > math.MaxInt32 && !isNegative {
		num = math.MaxInt32
	}
	if isNegative {
		fmt.Println(-num)
		return -num
	}
	return num
}

func convertArrayToInt(intArray []string) int {
	num := 0
	length := len(intArray)
	power := length
	for i := 0; i <= length-1; i++ {
		j, _ := strconv.Atoi(intArray[i])
		num += j * int(math.Pow(10, float64(power-1)))
		power--
	}
	fmt.Println(num)
	return num
}
```

#### Language used for code
Golang

#### Expected behavior
It should give me correct answer i.e. -42
Input:
"00000-42a1234"
Output:
-42
Expected:
0
Stdout:
42
-42

#### Screenshots
![Screenshot 2022-09-27 at 9 45 56 PM](https://user-images.githubusercontent.com/114486668/192580051-e0740f6d-429e-4d12-be0a-4c5c3dd695d9.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!
the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by rdsharma3** [comment]
No So there is one more Test case which is conflicting previously if input is 00000-42a1234 we are expecting 0 now there is another test case where input is "  -0012a42" and expecting -12. Are this two test case conflicting?  In one you are expecting that if you have a trailing letter then straight away return 0 and in another return the so fared value. :(
