### ISSUE TITLE
There is a bug in 'Add to list' option under the description tab.

### ISSUE THREAD

**Issue by amitkhedkar41** [LeetCode-Feedback/LeetCode-Feedback#9236]
#### Your LeetCode username
amitkhedkar41
https://leetcode.com/amitkhedkar41/

#### Category of the bug
-[ ] Website bug

#### Description of the bug
When we hover to the add to list option and click on create new list option and type something in that then that window get closes suddenly.That not letting to create a new list using that option 

#### Language used for code
JAVA

#### Bug video

https://user-images.githubusercontent.com/97602868/192589337-38d44dd4-5002-4cea-ae8d-da16c9930d33.mp4

#### Additional context
This bug not letting user to create new playlist using the shortcut.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the function appears to be working correctly, please clear the cookies and history, then fresh the page and try again!
