### ISSUE TITLE
200. Number of Islands - Union find solution has bug

### ISSUE THREAD

**Issue by pratikone** [LeetCode-Feedback/LeetCode-Feedback#9239]
#### Your LeetCode username
pratikone

#### Category of the bug
- [Number of Islands ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In union find solution provided,  in union function (line 29 onwards in Java solution), parent of entries are updated for all 3 cases but rank is not updated. Rank is only updated for the last case. It exists in both c++ as well as Java solution.

#### Code you used for Submit/Run operation

```
void Union(int x, int y) { // union with rank
    int rootx = find(x);
    int rooty = find(y);
    if (rootx != rooty) {
      if (rank[rootx] > rank[rooty]){
             parent[rooty] = rootx;
              rank[rootx] += rank[rooty]
       }
      else if (rank[rootx] < rank[rooty]){
              parent[rootx] = rooty;
              rank[rooty] += rank[rootx]
            }
      else {
        parent[rooty] = rootx; rank[rootx] += 1;
      }
      --count;
    }
  }
```

#### Expected behavior

Rank of each parent is needed for correct union. Up-to-date rank for each parent is crucial.

#### Screenshots

![image](https://user-images.githubusercontent.com/115935/192661781-466eb218-9c82-4e54-a383-e54b3be0aa38.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by yumkam** [comment]
Disclaimer: I'm regular user, not leetcode support
I believe you are wrong. Rank is *maximum* depth of a tree. If we join a tree with smaller maximum depth to the tree with higher maximum depth, maximum depth of the higher-depth tree does not change, so rank should not be changed.
The only case when rank should be changed is when both trees has same depth (rank).

**Comment by LC-Pam** [comment]
Thank you for your time. rank is only updated when the rank of two root nodes are identical, which means the depth of the merged tree is increased by one. we don't need to update the rank in other cases. Our code is correct. see the explore card about union-find [Explore - LeetCode](https://leetcode.com/explore/featured/card/graph/618/disjoint-set/3843/)We appreciate your support!
