### ISSUE TITLE
Missing Test Case - 1058. Minimize Rounding Error to Meet Target

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#924]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution from discuss section is accepted, but fails on a test case:

["9322.630", "9039.385", "6128.839", "173.518", "2401.053", "5924.190", "5005.481", "6777.398", "5594.861", "355.775", "1224.121", "8785.368", "1877.606", "7787.421", "684.669", "5568.627", "8851.049", "6736.661", "1954.860", "2567.039", "3884.754", "3610.724", "4809.917", "6522.681", "8331.471", "6284.083", "3017.693", "9211.801", "1024.579", "9405.490", "6066.891", "6540.799", "672.414", "9331.941", "4930.352", "2865.907", "4889.628", "210.646", "2405.299", "5873.577", "4827.949", "1200.437", "8345.945", "4434.976", "3618.908", "9895.051", "3836.716", "6380.081", "2743.985", "987.995", "4932.169", "6386.563", "7464.004", "2311.045", "842.562", "156.162", "8719.358", "8617.520", "4271.119", "3794.996", "312.478", "9530.906", "7820.456", "5746.270", "763.533"]
314564

#### Code you used for Submit/Run operation
<pre>
class Solution {
    public String minimizeError(String[] prices, int target) {
        float res = 0;
        PriorityQueue<Double> diffHeap = new PriorityQueue<>();
        
        for (String s : prices) {
            float f = Float.valueOf(s);
            double low = Math.floor(f);
            double high = Math.ceil(f);
            
            if (low != high)
                diffHeap.offer((high-f)-(f-low));
            
            res += f-low;
            target -= low;
        }
        
        if (target < 0 || target > diffHeap.size())
            return "-1";
        
        while (target-- > 0)
            res += diffHeap.poll();
        
        return String.format("%.3f", res);
    }
}
</pre>

<pre>
class Solution {
public String minimizeError(String[] prices, int target) {
        DecimalFormat df = new DecimalFormat("#.000");
        HashMap<Integer, Float>[] memo = new HashMap[prices.length + 1];
        float ans = minimizeError3(memo, 0, target, prices);
        if(ans == 0)
            return "0.000";
        return ans <= 1000000 ? df.format(ans) : "-1";
    }

    public float minimizeError3(HashMap<Integer, Float>[] memo, int index, int target, String[] prices){
        if(target < 0) {
            return 2000000;
        }
        if(memo[index] != null && memo[index].get(target) != null) {
            return memo[index].get(target);
        }
        if(index == prices.length){
            if(target == 0) {
                return 0;
            }
            return 2000000;
        }
        float current = Float.parseFloat(prices[index]);
        int floor =  (int) Math.floor(current);
        int ceil = (int) Math.ceil(current);
        float currError = Math.min(current - floor + minimizeError3(memo, index + 1, target - floor, prices),
                ceil - current + minimizeError3(memo, index + 1, target - ceil, prices));
        if(memo[index] == null) {
            memo[index] = new HashMap<Integer, Float>();
        }
        memo[index].put(target, currError);
        return currError;
    }
}
</pre>

<pre>
class Solution {
    public String minimizeError(String[] prices, int target) {
        int n = prices.length;
        Map<Integer, Float>[] dp = new HashMap[n + 1];
        dp[0] = new HashMap<>();
        dp[0].put(0, 0.0f);
        for (int i = 1; i <= n; i++) {
            float num = Float.parseFloat(prices[i - 1]);
            float upperCost = (float) (Math.ceil(num) - num);
            int upper = (int)Math.ceil(num);
            float lowerCost = (float) (num - Math.floor(num));
            int lower = (int)Math.floor(num);
            dp[i] = new HashMap<>();
            for (Map.Entry<Integer, Float> entry : dp[i - 1].entrySet()) {
                int upperKey = entry.getKey() + upper;
                dp[i].put(upperKey, Math.min(dp[i].getOrDefault(upperKey, Float.MAX_VALUE), entry.getValue() + upperCost));
                int lowerKey = entry.getKey() + lower;
                dp[i].put(lowerKey, Math.min(dp[i].getOrDefault(lowerKey, Float.MAX_VALUE), entry.getValue() + lowerCost));
            }
        }
        return dp[n].containsKey(target) ? String.format ("%.3f", dp[n].get(target)) : "-1";
    }
}
</pre>

<pre>
class Solution {
    public String minimizeError(String[] prices, int target) {
        int count = 0;
        float sum = 0;

        PriorityQueue<float[]> pq = new PriorityQueue<>((a,b)->a[0]>b[0]?1:-1);
        for(String p:prices){
            float floor = (float) Math.floor(Float.valueOf(p));
            float ceiling = (float) Math.ceil(Float.valueOf(p));
            float cur = Float.valueOf(p);
            if(floor == ceiling){
                target -=floor;
            }else{
                count++;
                target -=floor;
                pq.add(new float[]{ceiling-cur, cur-floor});
            }
        }
        if(count<target || target<0) return "-1";
        while(target>0){
            target--;
            float[] cur = pq.poll();
            sum += cur[0];
        }

        while(!pq.isEmpty()){
            float[] cur = pq.poll();
            sum += cur[1];
        }
        return String.format("%.3f", sum);
    }
}
</pre>

<pre>
class Solution {
    public String minimizeError(String[] prices, int target) {
        int sum = 0;
        float[] d = new float[prices.length];
        int nn = prices.length;
        for (int i = 0; i < prices.length; i++) {
            String p = prices[i];
            float dv = Float.valueOf(p);
            int v = (int)dv;
            sum += v;
            d[i] = dv - v;
            if (d[i] == 0) nn--;
        }
        if (sum > target || sum + nn < target) return "-1";
        Arrays.sort(d);
        int n = target - sum;
        float ans = 0;
        int i = d.length - 1;
        for (; i >= d.length - n; i--) {
            ans += 1 - d[i];
        }
        for (; i > -1; i--) {
            ans += d[i];
        }
        return String.format("%.3f", ans);
    }
}
</pre>

#### Language used for code
Java

#### Expected behavior

The solution should not be accepted since it fails on a test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/92184827-2e37e280-ee20-11ea-9e26-31c1245c7646.png)
![image](https://user-images.githubusercontent.com/32546406/92184948-7f47d680-ee20-11ea-95ce-bf135705199a.png)

#### Additional context

Link to the solution in discuss section:
https://leetcode.com/problems/minimize-rounding-error-to-meet-target/discuss/337606/Clean-Java-Solution-using-PriorityQueue

Please find below some of solutions that do not fail on the test case, but if double replaced with float, they are accepted and fail on the test case:
https://leetcode.com/problems/minimize-rounding-error-to-meet-target/discuss/305926/Easy-to-understand-DP-solution
https://leetcode.com/problems/minimize-rounding-error-to-meet-target/discuss/324557/Plain-Java-DP-Solution
https://leetcode.com/problems/minimize-rounding-error-to-meet-target/discuss/386149/JAVA-GREEDY-%2B-PRIORITYQUEUE-Clear-Understand
https://leetcode.com/problems/minimize-rounding-error-to-meet-target/discuss/448406/Java-beat-96

**Comment by lc-pam** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @IgorRud ,
Thank you for your time. The team has reviewed your report and considered the test case invalid so we didn't add it. We appreciate your support!
