### ISSUE TITLE
Missing Test Case 2416. Sum of Prefix Scores of Strings

### ISSUE THREAD

**Issue by Sam-Si** [LeetCode-Feedback/LeetCode-Feedback#9243]
#### Your LeetCode username
sam_si

#### Category of the bug
- [ ] Solution
- [ ] Missing Test Cases 

#### Description of the bug

The brute-force solution gets accepted for this problem.

#### Code you used for Submit/Run operation

```py
class Solution:
    def sumPrefixScores(self, words: List[str]) -> List[int]:
        counter = Counter()
        
        for word in words:
            for right in range(1, len(word) + 1):
                prefix = word[:right]
                counter[prefix] += 1
                
        ans = []
        
        for word in words:
            count = 0
            for right in range(1, len(word) + 1):
                prefix = word[:right]
                count += counter[prefix]
                
            ans.append(count)
            
        return ans
```

#### Language used for code
Python

#### Expected behavior

The above program should TLE

#### Tests
Attached the file.
[long_test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9662032/long_test.txt)

#### Additional context

Link to the accepted submission.
https://leetcode.com/submissions/detail/802601598/

The idle way to resolve this is by adding in more test cases so that the above solution TLEs

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
