### ISSUE TITLE
面试题01.02添加测试用例(s1 = "abca", s2 = "bca" )

### ISSUE THREAD

**Issue by MapleLetsun** [LeetCode-Feedback/LeetCode-Feedback#9246]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Maple岩

**Bug 类型**
- [面试题01.02 ] 缺少测试用例

**描述**
缺少测试用例
提交的代码应该是wa不是ac
s1 = "abca", s2 = "bca"  测试用例没有覆盖这种场景

**你使用的语言**
java

**你提交或者运行的代码**
```
// Two Sum
public boolean CheckPermutation(String s1, String s2) {
        // if(s1.length()!=s2.length()){
        //     return false;
        // }
        int[] cnt=new int[126];
        for(char c:s1.toCharArray()){
            cnt[c] +=1;
        }
        for(char c:s2.toCharArray()){
            cnt[c] -=1;
            if(cnt[c]<0){
                return false;
            }
        }
        return true;
    }
```

**期望行为**
wa(实际ac)

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前该题已添加测试用例，ID：mapleyan 给予积分奖励，请查收。
