### ISSUE TITLE
#290 Word Pattern

### ISSUE THREAD

**Issue by 0Clappie** [LeetCode-Feedback/LeetCode-Feedback#9249]
#### Category of the bug
- [ x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
```python
dictionary_with_pattern = {}
        i = 0
        words = s.split()

        def get_key(val):
            keys = []
            for key, value in dictionary_with_pattern.items():
                if val == str(value):
                    keys.append(key)
            return keys

        if len(s) != len(words):
            return False

        while i < len(words):
            for letter in pattern:
                if letter not in dictionary_with_pattern.keys():
                    dictionary_with_pattern[letter] = words[i]
                else:
                    x = words[i]
                    y = dictionary_with_pattern[letter]
                    if x != y:
                        return False
                    if x == y and len(get_key(y)) != 1:
                        return False
                i += 1
            
            for key, value in dictionary_with_pattern.items():
                if len(get_key(value)) != 1:
                    return False
                else:
                    return True
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by 0Clappie** [comment]
Python and there is no missing test case, I'm getting a false return when
I've debugged this in an IDE and it comes out as true. Very peculiar.
