### ISSUE TITLE
158. (Solution) Read N Characters Given Read4 II - Call multiple times

### ISSUE THREAD

**Issue by Shabirmean** [LeetCode-Feedback/LeetCode-Feedback#925]
#### Your LeetCode username
akashsingh

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language

#### Description of the bug
Solution to the question [158. Read N Characters Given Read4 II - Call multiple times](https://leetcode.com/problems/read-n-characters-given-read4-ii-call-multiple-times/).

#### Code you used for Submit/Run operation

```java
public class Solution extends Reader4 {
    int lastReadCount = 0;
    int bufferPointer = 0;
    char[] tempBuf = new char[4];
    
    public int read(char[] buf, int n) {
        int totalRead = 0;
        // first fill off anything left from previous read
        if (bufferPointer < lastReadCount) {
            int localIdx = 0;
            while (localIdx < n && bufferPointer < lastReadCount)
                buf[localIdx++] = tempBuf[bufferPointer++];
            totalRead += localIdx;
        }
        
        // second read, more if still left to read
        while (totalRead < n) {
            lastReadCount = read4(tempBuf);
            bufferPointer = 0;
            while (totalRead < n && bufferPointer < lastReadCount) {
                buf[totalRead++] = tempBuf[bufferPointer++];
            }
            if (lastReadCount != 4)
                break;
        }
        return totalRead;
    }
}
```

#### Language used for code
Java

#### Additional context
- A clean easy to understand solution.

**Comment by lc-pam** [comment]
Hi @Shabirmean 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @Shabirmean 
Thank you for your time. The team is in the stage of rewriting the entire solution article for this problem so we've decided not to use your solution. We appreciate your support!

**Comment by Shabirmean** [comment]
Cool 👍
