### ISSUE TITLE
572. Subtree of Another Tree

### ISSUE THREAD

**Issue by rojagtap** [LeetCode-Feedback/LeetCode-Feedback#9250]
#### Your LeetCode username

rojagtap

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Test case executing with 'Run Code' but the same test case fails when hit submit.
Test case:
```
[3,4,5,1,2,null,null,null,null,0]
[4,1,2]
```

#### Code you used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    ptrs = []
    
    def isSubtree(self, root: Optional[TreeNode], subroot: Optional[TreeNode]) -> bool:
        self.__find(root, subroot)
                
        for ptr in self.ptrs:
            if self.__equals(ptr, subroot):
                return True
        
        return False
    
    def __find(self, root, subroot):
        if not root:
            return
        elif root.val == subroot.val:
            self.ptrs.append(root)
        
        self.__find(root.left, subroot)
        self.__find(root.right, subroot)
        
    def __equals(self, a, b):
        if not a and not b:
            return True
        elif (a and not b) or (not a and b):
            return False
        else:
            return a.val == b.val and self.__equals(a.left, b.left) and self.__equals(a.right, b.right)

```

#### Language used for code

python 3

#### Expected behavior

At least the said test case should pass

#### Screenshots
<img width="1626" alt="Screenshot 2022-09-28 at 11 32 57 PM" src="https://user-images.githubusercontent.com/42299342/192855836-52645b23-2857-4e1f-a516-a127b9ddfc21.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
