### ISSUE TITLE
Missing Test Case - 1760. Minimum Limit of Balls in a Bag

### ISSUE THREAD

**Issue by rishabhr19** [LeetCode-Feedback/LeetCode-Feedback#9251]
#### Your LeetCode username
rishavranjan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Found a small spelling mistake in question number 1760. In example 2 last line reads "The bag with the most number of balls has 2 balls, so your penalty is 2 an you should return 2.".
Here, "and" should have been used instead of "an".

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
