### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by satzhan** [LeetCode-Feedback/LeetCode-Feedback#9252]
#### Your LeetCode username

Satj

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

Missing a testcase

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkSubarraySum(vector<int>& a, int k) {
        int n = a.size();
        unordered_set <int> s;
        s.insert(0);
        s.insert(a[0]);
        int cur = a[0];
        for (int i = 1; i < n; i++) {
            cur = (cur + a[i]) % k;
            if ((a[i] % k != 0 && s.find(cur) != s.end()) || (a[i] % k == 0 && a[i - 1] % k == 0))
                return true;
            s.insert(cur);
        }
        
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Just missing a testcase:
[23,3,3]
6

This testcase gives my solution a false, but Leetcode still accepts it. Screenshot attached.

#### Screenshots

![image](https://user-images.githubusercontent.com/46739227/192899040-1daf50c8-7048-49e5-bb20-193d42cbfd1f.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.We appreciate your support!
