### ISSUE TITLE
[面试题 01.09. String Rotation LCCI](https://leetcode.cn/problems/string-rotation-lcci/) 缺少测试用例

### ISSUE THREAD

**Issue by shun16888** [LeetCode-Feedback/LeetCode-Feedback#9254]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
kingss

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
[面试题 01.09. String Rotation LCCI](https://leetcode.cn/problems/string-rotation-lcci/) 缺少测试用例

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    bool isFlipedString(string s1, string s2) {
        if(s1.length()!=s2.length()) return false;
        int n=s1.length();
        int i=0,j=0;
        while(i<n)
            (s1[i++]==s2[j++])? : j=0;
        i=0;
        while(j<n)
            (s1[i++]==s2[j++])? : n=-1;
        return (j==n)?true:false;
    }
};
```

**期望行为**
以上代码可以ac，以下用例不能通过。
"aaaac"
"aaaca"

**Comment by feiceh** [comment]
你好，当前该题已添加测试用例，ID：kingss 给予积分奖励，请查收。
