### ISSUE TITLE
No Test case for exceed Time Complexity 

### ISSUE THREAD

**Issue by Vipulkr1698** [LeetCode-Feedback/LeetCode-Feedback#9255]
#### Your LeetCode username
vipulkr1698

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/
The problem is for hard category and question is good if you solve this in o(logn) time but I have solved this in o(n) time and all the test cases got passed .

#### Code you used for Submit/Run operation

```
// Find Minimum in Rotated Sorted Array II

class Solution:
    def findMin(self, nums: List[int]) -> int:
        return min(nums)
```

#### Language used for code
Python

#### Expected behavior
If the length of the list is too large it should return time limit exceed in case o(n) time complexity and only get pass for o(logn) .

#### Screenshots
<img width="1792" alt="Screenshot 2022-09-29 at 11 50 02 AM" src="https://user-images.githubusercontent.com/32465518/192954273-93e692de-cab1-469c-82c7-8a33ba0720c0.png">

#### Additional context
Other Platforms like GeeksForGeeks are able to address this test case and give error . So leetcode should also follow this practice .

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Since we have a time and input file limit, it is not possible to add a test case which is so large that O(n) fails. We appreciate your support!
