### ISSUE TITLE
Missing Constraints in #53 Maximum Subarray

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#926]
#### Your LeetCode username

**Mkay6122**

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Constraints are missing in question. Hope you provide it ASAP

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maxSubArray(vector<int>& nums) {
        int msf = INT_MIN, cm = 0 ;
        for(int i = 0;i < nums.size(); i++){
            cm += nums[i] ;
            if (cm > msf) msf = cm ;
            if (cm < 0 )  cm = 0 ;
        }
        return msf ;
    }
};
```

#### Language used for code
 C++

**Comment by lc-pam** [comment]
Hi @Mohitkumar6122 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Mohitkumar6122** [comment]
its the fastest method to reach leetcode

**Comment by lc-pam** [comment]
Hi @Mohitkumar6122 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
