### ISSUE TITLE
剑指 Offer 04. 二维数组中的查找 题意描述有误，与后台测试数据不符

### ISSUE THREAD

**Issue by nefu-ljw** [LeetCode-Feedback/LeetCode-Feedback#9263]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
nefu_ljw

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题意描述为**递增**顺序排序，而后台测试数据为**非递减**顺序。

**你使用的语言**
C++

**你提交的代码**
```cpp
class Solution {
public:
    bool findNumberIn2DArray(vector<vector<int>>& matrix, int target) {
        int n=matrix.size();
        if(n==0){
            return 0;
        }
        int m=matrix[0].size();
        if(m==0){
            return 0;
        }
        int i=0,j=0;
        while(i<n&&j<m){
            if(target==matrix[i][j]){
                return 1;
            }
            if(target>matrix[i][j]){
                if(i+1<n&&matrix[i+1][j]==target || j+1<m&&matrix[i][j+1]==target){
                    return 1;
                }
                if(i+1<n&&matrix[i+1][j]<target){
                    i++;
                }else if(j+1<m&&matrix[i][j+1]<target){
                    j++;
                }else{
                    return 0;
                }
            }else{
                return 0;
            }
        }
        return 0;
    }
};
```

**运行截图**
![屏幕截图 2022-09-29 212610.jpg](https://s2.loli.net/2022/09/29/iB1T7xwLuMYaQtO.jpg)

**后台测试数据**

> [[1,2,3,7,8],[5,10,14,16,19],[8,10,18,19,23],[9,12,22,24,29]]
> 14

该测试数据的矩阵中，在(1,1), (2,1)位置的两个同一列的元素相等，均为10，违背了题意中的“每一列都按照从上到下递增的顺序排序”。

**希望管理员修改题意或者修改后台测试数据，递增是“严格大于”，不能是“大于等于”（非递减）。**

**Comment by feiceh** [comment]
你好，当前题面已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by nefu-ljw** [comment]
> 你好，当前题面已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励。

这是我的域名：
https://leetcode.cn/u/nefu-ljw/

**Comment by nefu-ljw** [comment]
> 你好，当前题面已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励。

此外，我看了一下你们更改的新题面，可能还是表述不太清楚。建议改为：“每一行都按照从左到右**非递减**的顺序排序，每一列都按照从上到下**非递减**的顺序排序。非递减的含义是前一个数小于等于后一个数”

**Comment by feiceh** [comment]
ID：nefu_ljw 给予积分奖励，请查收。
