### ISSUE TITLE
433. Minimum Genetic Mutation - Genes bank implicit meaning

### ISSUE THREAD

**Issue by Andrey-Pavlov** [LeetCode-Feedback/LeetCode-Feedback#9264]
#### Your LeetCode username
Chuxel

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
It is not clear (it is not defined explicit) that we must use only bank strings (valid genes) on each mutation steps.

> There is also a gene **bank** that records all the valid gene mutations. A gene must be in **bank** to make it a valid gene string.
> Given the two gene strings start and end and the gene bank, return the minimum number of mutations needed to mutate from start to end. If there is no such a mutation, return -1.

#### Expected behavior
"There is also a gene bank that records all the valid gene mutations. A gene **_for each mutation/for each step_** must be in bank to make it a valid gene string.
Given the two gene strings start and end and the gene bank, return the minimum number of **_valid_** mutations needed to mutate from start to end. If there is no such a mutation, return -1."

#### Screenshots
![image](https://user-images.githubusercontent.com/7976740/193055614-d2fa52ab-4bd4-4dc8-8c16-e5c4a90afc39.png)

#### Additional context
https://leetcode.com/problems/minimum-genetic-mutation/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The description is quite clear enough, and further modifications are not necessary. We appreciate your support!
