### ISSUE TITLE
Typo Bug in LeetCode Explore -> Sorting -> Counting Sort -> Java

### ISSUE THREAD

**Issue by Jiahao-Wang** [LeetCode-Feedback/LeetCode-Feedback#9266]
#### Your LeetCode username

Billooo

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Line 4: int K = Arrays.stream(arr).max(),getAsInt();
The comma should be a period: int K = Arrays.stream(arr).max().getAsInt();

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Java

#### Screenshots

<img width="693" alt="Screen Shot 2022-09-29 at 11 39 48" src="https://user-images.githubusercontent.com/61516394/193076392-635ae0fc-caa5-4f62-8b03-1d4169dff011.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
