### ISSUE TITLE
Question and Solution - 744. Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by 0417taehyun** [LeetCode-Feedback/LeetCode-Feedback#9267]
#### Your LeetCode username

0417taehyun

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

It might be better to remove the ambiguous on the question.

If you see the [Soluion](https://leetcode.com/problems/find-smallest-letter-greater-than-target/solution/) part, you would know how many people request to update the details of the description. I refers the most upvoted comment.

*This problem is logically incorrect. If letters wrap around, then: 'a'<'b'<'c'<...<'x'<'y'<'z'<'a'<'b'<'c'<... Every letter is larger than any other letter. Then all one needs to do is return letters[0].*

As you can see the above comment, the condition of the **wrapping up** is crashed the other condition **ascending order**. Thus, it might be better to change the **Note** part like the below.

**Note**
- If every letter in `letters` is smaller than `target`, you can consider the letters are wrapped around.

To be honest, I think it would be better to remove the **Note** and all the test cases of the wrapping circumstances.

Additionally, it might be better to change the Python solution, not to use internal module, `bisect` .

As the author mentioned on the Solution part, we need to find the rightmost position to insert `target` into `letters`. Then it might be more helpful to users to implement the binary search without using any modules, like the below code. The below code can replace the original solution without adding any details on the description because I used the variable name that the author used and the logic also.

```Python
class Solution:
    def nextGreatestLetter(self, letters: List[str], target: str) -> str:
        lo, hi = 0, len(letters) - 1
        while lo <= hi:
            mi: int = (lo + hi) // 2
            if letters[mi] <= target:
                lo = mi + 1
            else:
                hi = mi - 1

        return letters[lo % len(letters)]
```

#### Code you used for Submit/Run operation

```Python
class Solution:
    def nextGreatestLetter(self, letters: List[str], target: str) -> str:
        lo, hi = 0, len(letters) - 1
        while lo <= hi:
            mi: int = (lo + hi) // 2
            if letters[mi] <= target:
                lo = mi + 1
            else:
                hi = mi - 1

        return letters[lo % len(letters)]
```

#### Language used for code

Python

#### Expected behavior

1. Update the details on the question to remove ambiguous.
2. Update the solution without using module.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
