### ISSUE TITLE
Time Limit Error. Find Minimum in Rotated Sorted Array

### ISSUE THREAD

**Issue by nidhish-srivastava** [LeetCode-Feedback/LeetCode-Feedback#9269]
No matter how many times you write the code,it shows the same error of the time limit being exceeded
I am writing the correct code,it is also showing no errror,but when time comes for judgement,it keeps on loading for a while more than 
the usual time and shows  this error.....

**Comment by nidhish-srivastava** [comment]
Solve this problem as soon as possible

**Comment by LC-Pam** [comment]
Thank you for contacting LeetCode's Support Team.

Your submission is resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

Please note that the test case you see on the "details" page shows which test case the program stops running at when the time limit has exceeded; it's not a test case that causes your program to exceed the time limit. 

I'd recommend checking out accepted submissions from the discuss tab of the problem page or posting your code there to get support from other users. Unfortunately, we do not disclose the time limit as we want our users to debug and improve their code to get it accepted. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
