### ISSUE TITLE
657. Robot Returns to Origin - Accepts incorrect solution/missing test cases

### ISSUE THREAD

**Issue by chadcromwell** [LeetCode-Feedback/LeetCode-Feedback#927]
#### Your LeetCode username
chadcromwell

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The question accepts incorrect solutions. The top accepted solution fails with test case: UUUUUUUUUL.

#### Code you used for Submit/Run operation
Copy of top accepted (incorrect) solution:
```
public boolean judgeCircle(String moves) {
        if (moves == null || moves.isEmpty()) return true;
        int[] counts = new int[100];
        counts['U'] = 1;
        counts['D'] = -1;
        counts['R'] = 9;
        counts['L'] = -9;
        
        int dist = 0;
        for (char ch: moves.toCharArray()) {
            dist += counts[ch];
        }
        
        return dist == 0;
    }
```

#### Language used for code
Java

#### Expected behavior
This code is actually wrong. Consider the test case: UUUUUUUUUL.
The 9 Us make dist == 9.
The 1 L make dist == 0.

However, the robot is not back at the origin and it should return false.

It doesn't matter what arbitrary numbers you choose. There's always a combination that will return the wrong answer. The issue is that test cases can't account for this.

If the total user-assigned sum of U or D equals the -sum of L or R, it could return true even though the robot really is not at the origin.

#### Additional context
Proper solution:
By not choosing an arbitrary value for either the horizontal or vertical moves we can avoid this error. Use the passed number of moves as the value for either horizontal or vertical and 1 for the other. This way they will never sum to 0 accidentally.

```
public boolean judgeCircle(String moves) {
        int numMoves = moves.length(); //Get the number of moves
        
        //Base case
        //If moves is null or empty, robot doesn't move so return true
        if(moves == null || numMoves == 0) {
            return true;
        }
        
        int[] map = new int[getIndex('U')+1]; //Initialize array needed for mapping character to int. Minimizing memory used and avoiding collision handling.
        
        //Build the map
        map[getIndex('U')] = 1; //Map U to 1
        map[getIndex('D')] = -1; //Map D to -1
        map[getIndex('L')] = numMoves; //Map L to numMoves
        map[getIndex('R')] = -numMoves; //Map R to -numMoves
        
        int distance = 0; //Track distance from origin
		
		//Iterate through each character in the passed String moves
        for (char c : moves.toCharArray()) {
            distance += map[getIndex(c)]; //Get value of char from map and add to distance
        }
        
        return distance == 0; //If distance is 0, robot is back at origin so return true. Else, return false.
    }
    
    //getIndex() method - Accepts a character and returns the appropriate index for the map
    private int getIndex(char c) {
        return Integer.valueOf(c)-Integer.valueOf('D'); //Return index
    }
```

**Comment by lc-ivan** [comment]
Hi @chadcromwell ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @chadcromwell  ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by chadcromwell** [comment]
Hi @lc-ivan,

Not a problem at all! Happy to contribute to the community.
