### ISSUE TITLE
Missing Test Case - 1262. Greatest Sum Divisible by Three

### ISSUE THREAD

**Issue by bvba** [LeetCode-Feedback/LeetCode-Feedback#9279]
#### Your LeetCode username

chanhyo1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

wrong code are passed
sort asc.
assuming that. unnecessary numbers(to be removed) is in a small number
remove only two(or less) numbers below sqrt(nums.size())

배열을 오름차순으로 정렬했을 때,
제거해야 할(불필요한) 수가 작은 수 중에 있다고 가정하여
제거할 두 수를 배열 길이의 제곱근(sqrt(nums.size()) 까지만 탐색하는 코드가 통과됨.

#### Code you used for Submit/Run operation

```
// Greatest Sum Divisible by Three

#include <algorithm>

class Solution {
public:
    int maxSumDivThree(vector<int>& ar) {
        
        if (ar.size() == 1 && ar[0] == 4)
            return 0;
        
        int n = ar.size(), sum = 0;
        for (int i = 0; i < n; ++i)
            sum += ar[i];
        
        if (sum % 3 == 0)
            return sum;
        
        sort(ar.begin(), ar.end());
        
        int sub = 10'000;
        for (int i = 0; i * i <= n; ++i) {
            if ((sum - ar[i]) % 3 == 0)
                sub = min(sub, ar[i]);
            for (int j = i + 1; j * j <= n; ++j) {
                int tmp_sub = ar[i] + ar[j];
                if ((sum - tmp_sub) % 3 == 0)
                    sub = min(sub, tmp_sub);
            }
        }
        return max(0, sum - sub);
    }
};
```

#### Language used for code

C++

#### Expected behavior

input
[9, 6, 61]

answer
15

upper code(wrong code but passed) output
0

input
// 3's total count is 39999
[3, 3, 3, ..., 3, 4]

answer
119997

#### Screenshots

![image](https://user-images.githubusercontent.com/19179351/193323059-b46ccfe9-9307-4a0c-8f23-e12281300bd6.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
