### ISSUE TITLE
Missing test case - 1550. Three Consecutive Odds

### ISSUE THREAD

**Issue by WaleedMortaja** [LeetCode-Feedback/LeetCode-Feedback#928]
#### Your LeetCode username
waleedmortaja

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
A solution is accepted, but it fails on a test case:
[1,1,2,1,1]

#### Code you used for Submit/Run operation

```
// 1550. Three Consecutive Odds
class Solution {
    public boolean threeConsecutiveOdds(int[] arr) {
        int ConsecutiveOddsCount = 0;
        for (int num : arr) {
            if ((num & 1) == 1) {
                ConsecutiveOddsCount++;
                if (ConsecutiveOddsCount == 3) {
                    return true;
                }
            } else {
                ConsecutiveOddsCount = Math.max(0, ConsecutiveOddsCount - 1);
            }
        }
        
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The solution should not be accepted since it fails on a test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/27075022/92270328-89380b00-eeee-11ea-8fde-5772f1075390.png)

![image](https://user-images.githubusercontent.com/27075022/92270384-a240bc00-eeee-11ea-9199-04a593f14e46.png)

#### Additional context
link to the problem: https://leetcode.com/problems/three-consecutive-odds

**Comment by lc-ivan** [comment]
Hi @WaleedMortaja ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @WaleedMortaja ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
