### ISSUE TITLE
Introduction to Big O Lesson - Last Example 

### ISSUE THREAD

**Issue by iicba** [LeetCode-Feedback/LeetCode-Feedback#9280]
https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/715/introduction/4654/

 Below is the last listed example for the intro to space complexity...
"Given an array "arr" with length n,
Given an array "arr2" with length m,

Array grid = int[n][m]

for (int i = 0; i < arr.length; i++) {
    for (int j = 0; j < arr2.length; j++) {
        grid[i][j] = arr[i] * arr[j]
    }
}"

In this example, shouldn't the last line of code reference "arr2[j]" instead of "arr[j]", read " grid[i][j] = arr[i]*arr2[j] "?

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
