### ISSUE TITLE
shorter test case to detect error

### ISSUE THREAD

**Issue by NxNiki** [LeetCode-Feedback/LeetCode-Feedback#9283]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language MySQL
- [x] Missing Test Cases 

#### Description of the bug

This is not a bug, but a very large test case that makes it hard for users to debug their code.
Question: 1158. Market Analysis I
Users:
| user_id | join_date  | favorite_brand |
| ------- | ---------- | -------------- |
| 1       | 2018-01-01 | Lenovo         |
| 2       | 2018-02-09 | Samsung        |
| 3       | 2018-01-19 | LG             |
| 4       | 2018-05-21 | HP             |

Orders:
| order_id | order_date | item_id | buyer_id | seller_id |
| -------- | ---------- | ------- | -------- | --------- |
| 1        | 2019-08-01 | 4       | 1        | 2         |
| 2        | 2018-08-02 | 2       | 1        | 3         |
| 3        | 2019-08-03 | 3       | 2        | 3         |
| 6        | 2019-08-05 | 2       | 2        | 4         |

Items:
| item_id | item_brand |
| ------- | ---------- |
| 1       | Samsung    |
| 2       | Lenovo     |
| 3       | LG         |
| 4       | HP         |

#### Code you used for Submit/Run operation

I figured out why my code failed but the test case is huge and making it hard to read. So I suggest to add the above shorter test case.

```
select
    user_id as buyer_id
    , join_date
    , sum(if(year(order_date) = 2019, 1, 0)) as orders_in_2019
from    
    orders o
right join
    users u
on o.buyer_id = u.user_id
group by buyer_id

```

This is the correct code:

```
select
    user_id as buyer_id
    , join_date
    , sum(if(year(order_date) = 2019, 1, 0)) as orders_in_2019
from    
    orders o
right join
    users u
on o.buyer_id = u.user_id
group by user_id # fix
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by NxNiki** [comment]
No problem! Thanks for building leetcode!
