### ISSUE TITLE
[616. Add Bold Tag in String] Incomplete description

### ISSUE THREAD

**Issue by Zhang-Haipeng** [LeetCode-Feedback/LeetCode-Feedback#9285]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One substring could overlap with itself. This scenario is in the test cases but not in the description or examples. For instance: s="aaa" words=['aa'], the returned result should be `"<b>aaa</b>"` vs. `"<b>aa</b>a"`

#### Expected behavior

Just make such a scenario and requirement explicit in the description and examples.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. All of these rules are in the statement.
Added a new example.. We appreciate your support!
