### ISSUE TITLE
Related Tag in Solution Showing Wrong Language

### ISSUE THREAD

**Issue by AnmolVerma404** [LeetCode-Feedback/LeetCode-Feedback#9287]
After the latest UI Update on LeetCode Problem Page, all the solutions in which I put C++-related tags have changed to C Language Tag
This is not just for me it appears for every problem solution C Language has the most tags, but the during the solution Post time they all have not even selected the C Language Tag

Eg:
![image](https://user-images.githubusercontent.com/77019763/193398533-48ca21ee-86b7-4516-8206-81147ffbbe4b.png)
![image](https://user-images.githubusercontent.com/77019763/193398559-87709fb9-5f95-4e7b-b801-119c8afff9ae.png)

1) In the first image there are a lot of C solutions but they all have submitted code in the same language
2) In the second image I recently submitted code in C++ tag but now the tag is in C!!!.

#### LeetCode username
Anmol_Verma404

#### Category of the bug
- [ ] Related Tags

#### Expected behavior
It should show C++ in the related tag while in the discussion section.

#### Additional context
This bug appeared after the latest UI updates, for many people the UI update is still not visible.
Therefore this bug should be fixed immediately, as it can create a big problem

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

We redirected it to our developers team but it will take time to fix.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
