### ISSUE TITLE
Missing test case - 1059. All Paths from Source Lead to Destination

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#929]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Several solutions from discuss section are accepted but fail on the following test case:

2
[]
0
1

#### Code you used for Submit/Run operation
<pre>
class Solution {
public boolean leadsToDestination(int V, int[][] E,
                                      int source, int destination) {
        if(E.length == 0) return true;
        if(V <= 1) return false;
        
        NEle[] nodes = new NEle[V];
        for(int[] e : E) {      
            if(e[0] == destination) return false;
            if(nodes[e[0]] == null) nodes[e[0]] = new NEle(e[0]);
            if(nodes[e[1]] == null) nodes[e[1]] = new NEle(e[1]);
            
            nodes[e[0]].tail = nodes[e[0]].tail.next = new Node(e[1]);
        }
        
        return nodes[source] != null && DFS(nodes, new int[V], new int[V],
                                            source, destination);
    }
    
    private boolean DFS(NEle[] nodes, int[] vCurr, int[] vPre, int i, int dest) {
        vPre[i] = 1;
        vCurr[i] = 1;
        
        Node n = nodes[i].head;
        if(n.next == null && n.i != dest) return false;
        
        while(n.next != null) {
            if(vCurr[n.next.i] == 1) return false;
			//causing problem -------------------------
            if(vPre[n.next.i] == 1) break;
            boolean atDest = DFS(nodes, vCurr, vPre, n.next.i, dest);
            if(!atDest) return false;
            n = n.next;
        }
        
        vCurr[i] = 0;
        return true;
    }
    
    static class Node {
        int i;
        Node next;
        Node(int i) {
            this.i = i;
        }
    }
    
    static class NEle {
        Node head;
        Node tail;
        NEle(int i) {
            head = new Node(i);
            tail = head;
        } 
    }

}
</pre>

<pre>
class Solution {
    public boolean leadsToDestination(int n, int[][] edges, int source, int destination) {
        if(edges == null || edges.length == 0) return true;
        Map<Integer, Set<Integer>> graph = new HashMap<>();
        
        for(int[] edge : edges) {
            graph.putIfAbsent(edge[0], new HashSet<>());
            graph.get(edge[0]).add(edge[1]);
        }
        
        if(graph.containsKey(destination)) return false; // destination should have 0 out-degree
        return backtrack(graph, new HashSet<Integer>(), source, destination);
    }
    
    private boolean backtrack(Map<Integer, Set<Integer>> graph, Set<Integer> visited, int node, int dest) {
        if(node == dest) return true;
        if(!graph.containsKey(node)) return false; // end point but not destination
        
        visited.add(node);
        for(int nei : graph.get(node)) {
            if(visited.contains(nei)) return false; // loop
            if(!backtrack(graph, visited, nei, dest)) return false;
        }
        visited.remove(node);
        return true;
    }
}
</pre>

<pre>
class Solution {
    public boolean leadsToDestination(int n, int[][] edges, int source, int destination) {
        
        /*
        1) check if there is cycle
        2) check if all the terminate is destination
        
        buildGraph - change edges representation to adjacent list
        
        DFS: 
        a) if current node has no neighbor and source == destination, return true
            else return false
        b) recurrent case:
            color[current node] = grey
            check all its neighbors:
                if color[neighbor] = grey -> find a cycle and return false
                if color[neighbor] = white and dfs() from it, if false then return false
            all its neighbors return true:
                color[current node] = black and return true
        */
        
        if (edges == null || edges.length == 0) return true;
        
        List<Integer>[] g = new List[n];
        buildGraph(edges, g);
        int[] colors = new int[n];
        return dfs(g, source, destination, colors);
        
    }
    
    void buildGraph(int[][] edges, List<Integer>[] g) {
        for (int[] e : edges) {
            if (g[e[0]] == null) g[e[0]] = new LinkedList();
            g[e[0]].add(e[1]);
        }
    }

    
    boolean dfs(List<Integer>[] g, int s, int d, int[] colors) {
        if (g[s] == null || g[s].size() == 0) {
            return s == d;
        }
        colors[s] = 1;
        for (int next : g[s]) {
            if (colors[next] == 1) return false;
            if (colors[next] == 0 && !dfs(g, next, d, colors)) return false;            
        }
        
        colors[s] = 2;
        return true;
    }
}
</pre>

#### Language used for code
Java

#### Expected behavior

The solutions should not be accepted since they fail on a testcase

#### Additional context

Links to the solutions:
https://leetcode.com/problems/all-paths-from-source-lead-to-destination/discuss/744067/Java-Current-cycle-detection-6ms-(ACCEPTED-but-wrong-for-some-input)
https://leetcode.com/problems/all-paths-from-source-lead-to-destination/discuss/713625/Java-DFS
https://leetcode.com/problems/all-paths-from-source-lead-to-destination/discuss/573313/Basic-JAVA-dfs

**Comment by lc-ivan** [comment]
Hi @IgorRud ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @IgorRud ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
