### ISSUE TITLE
Missing Test Case - 2423. Remove Letter To Equalize Frequency

### ISSUE THREAD

**Issue by IslaMurtazaev** [LeetCode-Feedback/LeetCode-Feedback#9291]
#### Your LeetCode username
IslaMurtazaev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case: `"abbbbb"`

#### Code you used for Submit/Run operation
```
class Solution:
    def equalFrequency(self, word: str) -> bool:
        letter_count = Counter(word)

        frequencies = defaultdict(int)
        for freq in letter_count.values():
            frequencies[freq] += 1

        if len(frequencies.values()) == 1:
            return len(letter_count.values()) == 1 or len(letter_count.values()) == len(word)

        if len(frequencies.values()) > 2:
            return False

        for freq, times in frequencies.items():
            if times == 1 and (freq + 1 in frequencies or freq - 1 in frequencies):
                return True
        return False
```

#### Language used for code
Python

#### Expected behavior
Should fail submission

#### Screenshots
<img width="1792" alt="Screen Shot 2022-10-01 at 22 35 15" src="https://user-images.githubusercontent.com/30570981/193419249-04a32b03-e87b-4135-90f1-c99aa773393a.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
