### ISSUE TITLE
Missing Test Case - 2423. Remove Letter To Equalize Frequency

### ISSUE THREAD

**Issue by vivekjoshi556** [LeetCode-Feedback/LeetCode-Feedback#9292]
#### Your LeetCode username

vivekjoshi556

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✔] Missing Test Cases 

#### Description of the bug

Missing Test Case: "aabbbccc"
There is a test case missing. I submitted my code and it was accepted but I gave a custom test case and my code failed. It wasn't giving the expected answer.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool equalFrequency(string word) {
        vector<int> count(26, 0);
        for(char ch: word) 
            count[ch - 'a']++;
        
        map<int, int> mp;
        for(int i = 0; i < 26; i++) {
            if(count[i] == 0) continue;
            mp[count[i]] = mp[count[i]] + 1;
        }
        
        if(mp.size() > 2) return false;
        
        auto it1 = mp.begin();
        if(mp.size() == 1) return (it1->second == 1 || (it1->first == 1));
        
        auto it2 = mp.rbegin();
        return ((it1->second == 1 || it2->second == 1) && abs(it2->first - it1->first) == 1);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The expected answer is "false" and my code returned "true".

#### Screenshots

![image](https://user-images.githubusercontent.com/37882929/193421555-fc4ea2b8-a249-4a7f-8b2e-27a2bb44d187.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
