### ISSUE TITLE
Missing Test Case - 2423. Remove Letter To Equalize Frequency

### ISSUE THREAD

**Issue by ARajput7419** [LeetCode-Feedback/LeetCode-Feedback#9293]
#### Your LeetCode username
Aniket7419

#### Category of the bug
 Missing Test Cases 

#### Description of the bug
My code was submitted successfully during the contest but when I simply run the same code on the testcase "abbbccc" it is showing the wrong answer.
So the test case where the minimum frequency is 1 and only one character has a minimum frequency and all other characters have equal but more than 2 frequencies are missing.  

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean equalFrequency(String word) {
        int [] count = new int[ 26 ];
        int max = 0;
        for(char c : word.toCharArray()){
            count [ c - 97 ]++;
            max = Math.max(max,count[c-97]);
        }
        int maxcount = 0,mincount=0;
        for(int freq : count ){
            if(freq == 0 ) continue;
            if ( freq == max ) maxcount++;
            else if (freq == max-1 ) mincount++;
            else return false;
        }

        return max == 1 ||  maxcount == 1 || mincount == 1 && max == 2;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Backend code against which users' code outputs are being matched is correct but during submission, there is a type of test case is missing. 

#### Screenshots
![issue_leetcode](https://user-images.githubusercontent.com/96017508/193421962-15b28134-b5c4-4840-8956-2a4b6cf0896f.png)
![issue_lleetcode](https://user-images.githubusercontent.com/96017508/193421975-25508aab-3d10-4072-a64a-c80f8979201a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
