### ISSUE TITLE
Missing Test Case - 398. Random Pick Index

### ISSUE THREAD

**Issue by plemanach** [LeetCode-Feedback/LeetCode-Feedback#9294]
#### Your LeetCode username
le_manach

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

398. Random Pick Index

I am getting Time Limit Exceeded with the same algorithm proposed in the solution for Java: 

Approach 3: Reservoir sampling

#### Code you used for Submit/Run operation

```
public class Solution {
       
    private int[] nums;
    private Random rdn = new Random();
   
    public Solution(int[] nums) 
    {
        this.nums = nums;
    }
    
    public int Pick(int target) {
     
        int n = this.nums.Length;
        int count = 0;
        int idx = 0;
        for (int i = 0; i < n; ++i) {
            // if nums[i] is equal to target, i is a potential candidate
            // which needs to be chosen uniformly at random
            if (this.nums[i] == target) {
                // increment the count of total candidates
                // available to be chosen uniformly at random
                count++;
                // we pick the current number with probability 1 / count (reservoir sampling)
                if (rdn.Next(count) == 0) {
                    idx = i;
                }
            }
        }
        return idx;
    }
}

```

#### Language used for code

c#

#### Expected behavior

I should get all the tests passed during the submition.

#### Additional context

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
