### ISSUE TITLE
Missing Test Case - 2423. Remove Letter To Equalize Frequency

### ISSUE THREAD

**Issue by nottheswimmer** [LeetCode-Feedback/LeetCode-Feedback#9297]
#### Your LeetCode username

nottheswimmer

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Invalid solution passes problem 2423
Missing test case `abbb` is needed to detect cases where code does not consider the case where one letter can be deleted to equalize the frequencies.

#### Code you used for Submit/Run operation
Link to solution: https://leetcode.com/submissions/detail/813204001/

```python
class Solution:
    def equalFrequency(self, word: str) -> bool:
        c = Counter(Counter(word).values())
        if len(c) >= 3:
            return False
        if len(c) == 1:
            return 1 in c or next(iter(c.values())) == 1
        (fa, na), (fb, nb) = c.items()
        if fa > fb:
            fa, fb, na, nb = fb, fa, nb, na
        if fb - fa != 1:
            return False
        return nb == 1 or (na == 1 and fa == 1)
```

#### Language used for code
Python

#### Expected behavior
Above code would fail

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
