### ISSUE TITLE
incorrect spelling: 1155. Number of Dice Rolls With Target Sum

### ISSUE THREAD

**Issue by pgthakur** [LeetCode-Feedback/LeetCode-Feedback#9299]
#### Your LeetCode username
pgthakur

#### Category of the bug
- [ ] Question

#### Description of the bug

the spelling of dice is incorrect in 2 places.
eg:
1. You have n dice and each <die> has k faces numbered from 1 to k.
2. Explanation: You throw one <die> with 6 faces. (in example 1)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![Screen Shot 2022-10-02 at 12 05 05 PM](https://user-images.githubusercontent.com/61389083/193441369-5609a9be-f4ff-4651-97d0-0452d14644d3.png)

**Comment by whoan** [comment]
I think that's fine. One is for singular (die) and the other for plural (dice):

Random references:
- https://grammar.yourdictionary.com/vs/die-vs-dice-dont-chance-difference
- https://grammarist.com/usage/dice-die/
- https://www.queens-english-society.com/dice-vs-die
