### ISSUE TITLE
题目描述错误

### ISSUE THREAD

**Issue by LucienZhang** [LeetCode-Feedback/LeetCode-Feedback#93]
https://leetcode-cn.com/problems/maximum-nesting-depth-of-two-valid-parentheses-strings/

1111.有效括号的嵌套深度

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目描述中的提示`1 <= text.size <= 10000`是一个错误提示，text没有定义，且输入长度等于1时为非法输入。

**Comment by feiceh** [comment]
1 < seq.size <= 10000 已更新。
