### ISSUE TITLE
剑指 Offer 10- II. 青蛙跳台阶问题

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#930]
** Bug 类型**
- [ x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
不符合现实意义的测试用例。

**你使用的语言**
python3

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/26211339/92308948-e0fc7200-efd3-11ea-9c79-b52ab46539ce.png)

**额外的上下文**
n的范围应当是正整数，因为0阶台阶没有现实意义，青蛙不需要动作，这算不上是一种跳法。

**Comment by feiceh** [comment]
感谢反馈，该题目技术验证没有问题的，题目给出示例了。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路。

**Comment by Ijustwantyouhappy** [comment]
都说和【70. 爬楼梯】题目一致了，那道题就规定了n必须为正整数，这道还非得补充个示例n=0的情形，青蛙咋这么聪明呢，居然还能想起来一种方法跳0阶台阶，好奇是那种方法，屁股向后平沙落雁式吗
