### ISSUE TITLE
Missing Test Case - 2007. Find Original Array From Doubled Array

### ISSUE THREAD

**Issue by whoan** [LeetCode-Feedback/LeetCode-Feedback#9300]
#### Your LeetCode username

whoan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There's a missing test case for arrays with extra elements _> 1e5/2_

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> findOriginalArray(vector<int>& changed) {
        int size = changed.size();
        constexpr size_t length = 1e5+1;
        std::array<int, length> count{};
        for (int n : changed) {
            ++count[n];
        }
        changed.clear();
        if (count[0] % 2) {
            return move(changed);
        }
        count[0] >>= 1;
        for (int i=0; i <= length>>1; ++i) {
            if (count[i] < 0) {
                changed.clear();
                return move(changed);
            }
            if (count[i]) {
                changed.resize(changed.size()+count[i], i);
                count[i<<1] -= count[i];
            }
        }
        return move(changed);
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected the solution to fail, as it doesn't cover test cases like this: `[50000,50001,100000]`

When I hit "Run code" with the test case above, it fails; When I hit Submit, it passes.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
