### ISSUE TITLE
Missing Not Possible Condition - 1155. Number of Dice Rolls With Target Sum

### ISSUE THREAD

**Issue by Scramjet911** [LeetCode-Feedback/LeetCode-Feedback#9301]
#### Your LeetCode username

Scramjet

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The question does not mention what to return if the `target` is not possible to reach with one die or say that it is always possible to reach the `target`.

#### Expected behavior

The description should contain the return value if the `target` is not possible to reach.
Or it should say `It is always possible to reach the target with the given number of dice of k sides`

#### Additional context

Missing edge cases unintentionally reduce the question quality.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The question is asking for the number of ways which can be 0 when target is not reachable.
Nothing to change. We appreciate your support!
