### ISSUE TITLE
Missing Test Case - 713. Subarray Product Less Than K

### ISSUE THREAD

**Issue by Birhanachalew** [LeetCode-Feedback/LeetCode-Feedback#9309]
[10,9,10,4,3,8,3,3,6,2,10,10,9,3]
19

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
