### ISSUE TITLE
Missing Testcase : 1574. shortest-subarray-to-be-removed-to-make-array-sorted

### ISSUE THREAD

**Issue by beladiyadarshan** [LeetCode-Feedback/LeetCode-Feedback#931]
username : darshan786

Testcase :
[1,2,3,10,0,7,8,9]

#### Code you used for Submit/Run operation
```
int findLengthOfShortestSubarray(vector<int>& arr) {
        
          int left = 1, right = 1;

          for(int i = 1; i < arr.size() && arr[i] >= arr[i - 1]; i++)//find increasing sequence length from left
                left++;
          
          for(int i = arr.size() - 2; i >= 0 && arr[i] <= arr[i + 1]; i--)//find decreasing sequence length from right
                right++;
          

          int len1 = right,len2=left;
          
          for(int i = arr.size() - right; i < arr.size() && arr[i] < arr[left - 1]; i++)//check left side with right
                len1--; 
          
          for(int i = left - 1; i >= 0 && arr[i] > arr[arr.size() - right]; i--)//check right side with left
                len2--;
          
        
          int mi=min(arr.size() - left - len1, arr.size() - right - len2);
          
        
        return max(mi, 0);

        
    }
```

Language : c++

-code got accepted but code  is giving wrong answer for given testcase [1,2,3,10,0,7,8,9]

![image](https://user-images.githubusercontent.com/42748893/92309757-eb177400-efc5-11ea-90cc-9bc48d4036e9.png)

**Comment by lc-pam** [comment]
Hi @beladiyadarshan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @beladiyadarshan 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
