### ISSUE TITLE
Wrong Test Case Validation - 210. Course Schedule

### ISSUE THREAD

**Issue by vigneshshiv** [LeetCode-Feedback/LeetCode-Feedback#9313]
#### Your LeetCode username
vigneshshiv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Wrong Test case Validation

#### Code you used for Submit/Run operation
I used Run operation for testing one of the test cases, but even though output is not matched with expected output, but it is showing test case pass.

The code is wrong but one of the test case got accepted for wrong answer. 

// Course Schedule II

```
class Solution {
    public int[] findOrder(int numCourses, int[][] prerequisites) {
        int[] empty = new int[] {};
        // In-degree courses
        int[] dependency = new int[numCourses];
        Map<Integer, List<Integer>> courses = buildPrerequisites(prerequisites, dependency);
        // Result order
        int[] order = new int[numCourses];
        Arrays.fill(order, -1);
        // build non dependency courses list first and find offset
        int offset = addNonDependentCourses(order, dependency, 0);
        int toBeProcessed = 0;
        while (toBeProcessed < numCourses) {
            // Current courses list
            List<Integer> list = courses.get(toBeProcessed);
            if (Objects.nonNull(list)) {
                // return null; // Circular dependency;
                // Decrement dependencies
                list.stream().forEach(e -> dependency[e] -= 1);
                // Add finished courses
                for (int finished_course : list) {
                    if (dependency[finished_course] == 0) {
                        order[offset++] = finished_course;
                    }
                }
            }
            toBeProcessed++;
        }
        return order;
    }
    
    private Map<Integer, List<Integer>> buildPrerequisites(int[][] prerequisites, int[] dependency) {
        Map<Integer, List<Integer>> courses = new HashMap<>();
        for (int[] course : prerequisites) {
            int post = course[0], pre = course[1];
            List<Integer> dependencies = courses.getOrDefault(pre, new ArrayList<>());
            dependencies.add(post);
            courses.put(pre, dependencies);
            // Count the number of dependencies
            dependency[post] += 1;
        }
        return courses;
    }

    private int addNonDependentCourses(int[] order, int[] dependency, int offset) {
        for (int course : dependency) {
            if (course == 0 && order[course] == -1) {
                order[offset++] = course;
            }
        }
        return offset;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Input: 
2
[]

Output: 
[0,-1]

Expected:
[1,0]

For more details, refer the screenshot once. 

#### Screenshots
![image](https://user-images.githubusercontent.com/10242660/193469695-aa454346-3be7-42bb-9967-49dbbeab37b4.png)

#### Additional context
Diff option shows the difference, but it got accepted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by vigneshshiv** [comment]
Thank you for your suggestion. 

@LC-Pam I haven't used any such cases as you pointed out in the reference link. There is no global/static variables and no instance variables. But the still the program produces different output and got as accepted while running the test case. 

My point is here, The reference link you've shared is not matching with this situation.
