### ISSUE TITLE
The Editor is not honouring the tab spaces correctly. Bad User Experience.

### ISSUE THREAD

**Issue by gwinsingh** [LeetCode-Feedback/LeetCode-Feedback#9314]
The Solution section is not honouring the tab spaces chosen. Once the user chooses 2 spaces for tab in settings, leetcode should remember the choice to have the same 2 tab spaces by default for the user. But it is not behaving as expected.

What is happening:
- I prefer Tab size as 2 spaces, so I have chosen the tab size to be 2 spaces (in Editor Settings).
- While the settings tab still shows the tab to be 2 spaces every time, the editor is still behaving like tab with 4 spaces.
- I have to revert back to 4 spaces in the settings followed by selecting 2 spaces option again to fix this. 
- Doing this back and forth exercise seems to be the only way to fix this for me.

Please take a look at this Bug as it is seriously impacting the User Experience.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. 
Would you mind send this issue to our Zendesk support team, then we can pass this feature issue to the product team.
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by gwinsingh** [comment]
I (as a customer) don't know how to do that. Can you share the steps involved?

**Comment by dchae** [comment]
This issue is not fixed yet, still experiencing as of now. Using vim mode in case that's relevant

**Comment by Shivam7Sharma** [comment]
Hi,

I use Chrome, and when I press the tab, the code editor doesn't indent spaces when I solve a problem. I am using the standard setting. When I press the tab, it selects the test cases instead of indenting the code.

**Comment by onescriptkid** [comment]
I wrote a quick & dirty [userscript](https://github.com/onescriptkid/leetcode-editor-tab-2-spaces?tab=readme-ov-file) which will fix the issue by automatically toggling the editor: [raw](https://raw.githubusercontent.com/onescriptkid/leetcode-editor-tab-2-spaces/refs/heads/master/leetcode-editor-tab-2-spaces.js)
