### ISSUE TITLE
题目描述重复 今天的每日一题 1784. 检查二进制字符串字段

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#9317]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 题目

**描述**
题目描述重复了一次。

**期望行为**
删除其中一次重复。

**屏幕截图**
![image](https://user-images.githubusercontent.com/25954059/193503894-68e474eb-c23b-45ee-a63a-6165e13d3a89.png)

**额外的上下文**
https://leetcode.cn/problems/check-if-binary-string-has-at-most-one-segment-of-ones/

**Comment by feiceh** [comment]
你好，当前题面已更新，ID：hhummingg 给予积分奖励，请查收。
