### ISSUE TITLE
题解错误 剑指 Offer 53 - II. 0～n-1中缺失的数字

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#9318]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 题解

**描述**
题解的方法一重复排序，实际无需排序。

**期望行为**
删除方法一中sort那行的代码。

**屏幕截图**
![image](https://user-images.githubusercontent.com/25954059/193504282-7dcfd58b-3279-4914-a809-60f862d85c65.png)
![image](https://user-images.githubusercontent.com/25954059/193504323-c4722bab-7b9c-42c9-9e10-fd67d00fbe55.png)

**额外的上下文**
https://leetcode.cn/problems/que-shi-de-shu-zi-lcof/

**Comment by zuizaiqinshi** [comment]
尊敬的用户您好
经过检查，您反馈的题目官方题解的方法一与实际题解不相同，代码也不同。这边无法定位问题，建议您重新提交～
再次感谢您的反馈
