### ISSUE TITLE
Acceptance Criteria Inconsistent with Problem Description for Python3 - 27. Remove Element

### ISSUE THREAD

**Issue by ercanburak** [LeetCode-Feedback/LeetCode-Feedback#9320]
#### Your LeetCode username
bercan89

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem description requires the solution to return an integer k. When using Python 3, solutions that do not return anything (and change the size of the list) gets accepted instead. This is an inconsistency with the description.

#### Code you used for Submit/Run operation

```
class Solution:
    def removeElement(self, nums: List[int], val: int) -> int:
        left = 0
        right = len(nums)-1
        
        while left <= right:
            left_match = nums[left] == val
            right_match = nums[right] == val
            if not left_match and not right_match:
                left += 1
            elif not left_match and right_match:
                left += 1
                right -= 1
            elif left_match and not right_match:
                nums[left], nums[right] = nums[right], nums[left]
            else: # left_match and right_match
                right -= 1
                
        del nums[left:]
```

#### Language used for code

Python3

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by AlapMistry** [comment]
Hi @LC-Pam,
I am also facing the same issue with Java. My answer should be correct for the given below input, but it shows other answer as expected answer.

**Your LeetCode username**
AlapMistry

**Code**
```
class Solution {
    public int removeElement(int[] nums, int val) {        
        int left = 0;
        int right = nums.length - 1;

        for (int i = 0; i < nums.length; i++) {
            if (nums[left] == val) {
                if (nums[right] != val) {
                    int temp = nums[left];
                    nums[left] = nums[right];
                    nums[right] = temp;
                    right--;
                } else {
                    if (right >= 1) {
                        right--;
                        int temp = nums[left];
                        nums[left] = nums[right];
                        nums[right] = temp;
                    }
                }
            }

            if (left >= right) {
                return right;
            } else {
                left++;
            }
        }

        return right < 1 ? 1 : right;
    }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/24839221/209970288-c13968ae-ce46-40b5-88f9-032c74b828e3.png)


Hope your team will investigate and fix it as soon as possible.

PS: Might be, my code is not correct solution, but it should work for the above testcase.

**Comment by LC-Pam** [comment]
Hi there,

Thanks for sharing your observation. In this case, the return value is utilized to resize the input list. If you accomplish this by modifying the list in your code without explicitly returning a value, it still fulfills the requirements of the problem. In this context, the absence of a return statement doesn't pose an issue as your implementation meets the problem's criteria.

If you have any more questions or if there's anything else you'd like to discuss, feel free to let me know!

Warm regards,
Support Team
