### ISSUE TITLE
Unclear or incorrect explanation: 914. X of a Kind in a Deck of Cards 

### ISSUE THREAD

**Issue by theJsTsGuy** [LeetCode-Feedback/LeetCode-Feedback#9322]
#### Your LeetCode username
vvjzd

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing / Incorrect Test Cases 

#### Description of the bug

The issue was opened before too, but closed by the creator: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8732
The question clearly states:
### Return true if and only if you can choose X >= 2 such that it is possible to split the entire deck into 1 or more groups of cards, where:
- Each group has exactly X cards.
- All the cards in each group have the same integer.

On submitting, the execution gets failed:
```
Input:
[1,1,2,2,2,2]
Output:
false
Expected:
true
```
The group of 2s clearly is larger than group of 1s. If we leave checking of every group to be of equal length, then this test case fails:
```
Wrong Answer
Runtime: 115 ms
Your input
[1,1,1,2,2,2,3,3]
Output
true
Expected
false
```

#### Code you used for Submit/Run operation

Code doesn't matter here

#### Language used for code
Neither the language

#### Expected behavior

Either there are some unclear instructions in the description of the question, or the test cases are wrong. These two data sets seem to have the exact same information, yet produce different results.

#### Screenshots

![image](https://user-images.githubusercontent.com/40920737/193543042-4909fe45-28f0-46a7-9c81-4bc9cef7409e.png)

#### Additional context

Seems like the test is considering that each group should be a multiple of two, rather than all groups should be equal in size, contradicting the description:
> Each group has exactly X cards
```
Accepted
Runtime: 116 ms
Your input
[1,1,1,1,2,2,2,2,3,3]
Output
true
Expected
true
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Both statement and test cases are correct and there is no contradiction.
for [1,1,2,2,2,2], one possible answer is choosing x = 2 and [1,1], [2,2,], [2,2].
Please refer to the discussion section after reading the statement one more time. We appreciate your support!
