### ISSUE TITLE
Missing Test Case - 2430. Maximum Deletions on a String

### ISSUE THREAD

**Issue by calicratis19** [LeetCode-Feedback/LeetCode-Feedback#9323]
#### Your LeetCode username
calicratis19

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Missing test case "abaaabaa"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by calicratis19** [comment]
The following code is written on Java, and produces wrong answer but is accepted by the system.

```
class Solution {
    Integer dp[], n;
    public int deleteString(String s) {
        dp = new Integer[n=s.length()];
        return solve(s, 0);
    }
    public int solve(String s, int x) {
        if(x>=n) return 0;
        
        if(dp[x]!=null) return dp[x];
        
		// minimum value of max is 1 bcz you can delete whole string
        int max = 1, len=x+((n-x)>>1);
        
        for(int i=x;i<len;i++) {
			// to avoid duplicates
            if(i>x && s.charAt(i)==s.charAt(~-i)) continue;
			
			// -~i -> i+1 ; ~-i -> i-1
            if(isMatching(s, x, -~i)) 
                max = Math.max(max, 1+solve(s, -~i));
        }
        
        return dp[x]=max;
    }
    public boolean isMatching(String s, int i, int Y) {
        int j=Y;
        while(i<Y) 
            if(s.charAt(i++)!=s.charAt(j++))
                return false;
        return true;
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
Please provide us your valid leetcode username.

**Comment by calicratis19** [comment]
This is my LeetCode account. https://leetcode.com/tahlil/

Thanks.
