### ISSUE TITLE
Join and Inner Join in MSSQL - 1084. Sales Analysis III

### ISSUE THREAD

**Issue by ranggakd** [LeetCode-Feedback/LeetCode-Feedback#9324]
#### Your LeetCode username

ranggakd

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

According to [SQL Server documentation](https://learn.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-ver16#join-type) regarding JOIN

> INNER
Specifies all matching pairs of rows are returned. Discards unmatched rows from both tables. When no join type is specified, this is the default.

Therefore the usage clause `JOIN` and `INNER JOIN` has the same effect and vice versa. But when I code both queries, the `INNER JOIN` one that got accepted and the `JOIN` one always got TLEd

#### Code you used for Submit/Run operation

```SQL
SELECT
    p.product_id,
    p.product_name
FROM
    Product p INNER JOIN Sales s ON p.product_id = s.product_id
GROUP BY
    p.product_id,
    p.product_name
HAVING
    MIN(s.sale_date) >= '2019-01-01'
    AND MAX(s.sale_date) <= '2019-03-31'
```

```SQL
SELECT
    p.product_id,
    p.product_name
FROM
    Product p JOIN Sales s ON p.product_id = s.product_id
GROUP BY
    p.product_id,
    p.product_name
HAVING
    MIN(s.sale_date) >= '2019-01-01'
    AND MAX(s.sale_date) <= '2019-03-31'
```

#### Language used for code

Microsoft SQL Server

#### Expected behaviour

Both queries have no difference at all and always return the same result over time.

#### Screenshots

`INNER JOIN`
![image](https://user-images.githubusercontent.com/36787606/193575958-d8c3e4d8-845b-4e23-a1b5-9af70b1526d1.png)

`JOIN`
![image](https://user-images.githubusercontent.com/36787606/193575678-f6b06ff4-1a05-4840-911d-648172d0373f.png)

#### Additional context

`[Microsoft][ODBC Driver 17 for SQL Server][SQL Server](SQLExecDirectW)`

**Comment by LC-Pam** [comment]
Thank you for your time. 
The second code received Accepted when we submitted it.
https://leetcode.com/submissions/detail/815223814/
We appreciate your support!

**Comment by ranggakd** [comment]
No, you are not. You are using `mysql` dialect for that one.

![Screenshot_20221005_085128_Chrome.jpg](https://user-images.githubusercontent.com/36787606/193962338-8b1f3b3a-2e28-4dec-926f-39c1ad7dc8fb.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The Inner join is slower due to how it works in MSSQL, so nothing to do.  We appreciate your support!
