### ISSUE TITLE
Missing Test Case - 2349. Design a Number Container System

### ISSUE THREAD

**Issue by Aakash-Jakhmola** [LeetCode-Feedback/LeetCode-Feedback#9325]
#### Your LeetCode username
wa_magnet

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The testcase is missing which allows slow solutions to pass. When i run with custom input, it gets TLE, but passes on submit.

#### Code you used for Submit/Run operation

```
class NumberContainers {
public:

  map<int,int> m;
    NumberContainers() {
             
    }
    
    void change(int index, int number) {
      m[index]=number;        
    }
    
    int find(int number) {
         int ans=-1;
        for(auto it:m){
            if(it.second==number){
                ans=it.first;
                break;
            }
        }
         
        return ans;
        
    }
};

```

#### Language used for code
 C++ 

#### Expected behavior

The solution should receive TLE (time limit exceeded) verdict.

#### Additional context
TestCase file drive link: https://drive.google.com/file/d/1kzTXltDaNUoIgFvnq2n7S2BXGJQd97YH/view?usp=sharing

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
