### ISSUE TITLE
Description wrong - 45. Jump Game II

### ISSUE THREAD

**Issue by wenboji** [LeetCode-Feedback/LeetCode-Feedback#9326]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the Description 
line 2:
Each element nums[i] represents the maximum length of a forward jump from index i. In other words, if you are at nums[i], you can jump to any nums[i + j] where:

    1 <= j <= nums[i] and
    i + j < n

the Constraints:

1 <= nums.length <= 104
0 <= nums[i] <= 1000

Base on the constraints line two, if nums[i] == 0, then **1 <= j <= nums[i]** is not valid
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

**1 <= j <= nums[i]** change to **0<= j <= nums[i]**

#### Screenshots

<img width="847" alt="image" src="https://user-images.githubusercontent.com/41981260/193670965-beaabc39-35e6-4833-846a-f7a7fe2d3101.png">

#### Additional context

The contribute i  button is hidden when the console is open which is not easy to find if I don't know where to submit the issue

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
