### ISSUE TITLE
921题翻译错误

### ISSUE THREAD

**Issue by YtotheWT** [LeetCode-Feedback/LeetCode-Feedback#9327]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
Cool Mir2akhaniiHN

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
921题翻译错误，“In one move, you can insert a parenthesis at any position of the string.”被翻译成“移动N次，你就可以在字符串的任何位置插入一个括号”，但正确翻译是“每一次操作中，你可以在字符串的任何位置插入一个括号”。

**Comment by feiceh** [comment]
你好，当前题面已更新，ID：cool-mir2akhaniihn给予积分奖励，请查收。
