### ISSUE TITLE
994 Rotting Oranges time complexity ambiguous

### ISSUE THREAD

**Issue by TheAlexFuller** [LeetCode-Feedback/LeetCode-Feedback#9328]
In [994. Rotting Oranges](https://leetcode.com/problems/rotting-oranges/), the first solution says
> Time Complexity: O(N), where N is the size of the grid.

But this is unclear. If the grid has _m_ rows and _n_ columns, does this mean N = _m*n_? It would be clearer to say O(_m*n_).

The second solution says

> Time Complexity: O(N^2) where N is the size of the input grid.

but I think the solutions have the same time complexity. This makes the first time complexity more confusing. The solutions should be double checked and preferably written in terms of _m_ and _n_.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
