### ISSUE TITLE
Missing testcase in 1574. Shortest Subarray to be Removed to Make Array Sorted

### ISSUE THREAD

**Issue by ssanjeev2424** [LeetCode-Feedback/LeetCode-Feedback#933]
ssanjeev2424

#### Category of the bug - Test case missing
[1] Question

#### Description of the bug

Crucial test case missing

#### Code you used for Submit/Run operation

```
// 1574. Shortest Subarray to be Removed to Make Array Sorted
class Solution {
public:
    int findLengthOfShortestSubarray(vector<int>& arr) {
        int n = arr.size(), idx1 = -1, idx2 = -1;
        
        int prev = 0;
        for(int i=0; i<n; i++) {
            if(prev > arr[i]) {
                idx1 = i;
                break;
            }
            prev = arr[i];
        }
        
        if(idx1 == -1) return 0;
        
        prev = 1e9;
        for(int i=n-1; i>=0; i--) {
            if(arr[i] > prev) {
                idx2 = i;
                break;
            }
            prev = arr[i];
        }
        
        //printf("idx1:%d, idx2:%d\n", idx1, idx2);
        
        int ans = n - 1, i;
        idx1--; 
        for(i=n-1; i>idx2; i--) {
            if(arr[i] >= arr[idx1]) ans = i - idx1 - 1;
            else
                break;
        }
        
        //if(ans == n - 1) ans = n - idx1;
        //printf("ans:%d\n", ans);
        
        idx1++; idx2++;
        for(i=0; i<idx1; i++) {
            if(arr[i] <= arr[idx2]) ans = min(ans, idx2 - i - 1);
            else
                break;
        }
        
        //printf("ans:%d\n", ans);
        idx2--;
        
        ans = min(ans, min(n - idx1, idx2 + 1));
        
        //printf("ans:%d\n", ans);
        
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

With "[1,2,2,2,2,2,3,1,7,5,1,2,2,2,2,2,2,5,6]" input ,
expected behaviour is '5', but my code returns '9' and still gets AC

#### Screenshots

![image](https://user-images.githubusercontent.com/31368706/92311325-aeeb1000-efd3-11ea-8cde-4b5ee2236750.png)
![image](https://user-images.githubusercontent.com/31368706/92311327-b8747800-efd3-11ea-8ab6-7c0a9624833f.png)

**Comment by lc-kay** [comment]
Hi @ssanjeev2424,

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ssanjeev2424** [comment]
@lc-kay  Ok, thanks !!

**Comment by lc-kay** [comment]
@ssanjeev2424 

We have updated the test set of this problem yesterday and this solution gets WA now. Thank you for using Leetcode!

**Comment by ssanjeev2424** [comment]
@lc-kay what about my 100 reward points for contributing a test case? i didn't get any? 

Apparently, the previous set of test cases were allowing incorrect solutions to get AC. So, i think i have contributed a legit test case.

**Comment by lc-kay** [comment]
@ssanjeev2424 
Unfortunately, another user reported the issue first, and points are only assigned to the 1st reported user. I apologize for not being clear in my last comment.

**Comment by ssanjeev2424** [comment]
ok fine, thanks @lc-kay
