### ISSUE TITLE
Missing Test Case - 2424. Longest Uploaded Prefix

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#9330]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets Runtime Error on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9702782/1.txt)

#### Code you used for Submit/Run operation

```
from sortedcontainers import SortedList

class LUPrefix:

    def __init__(self, n: int):
        self.lst=SortedList(range(1,10**5+1))

    def upload(self, video: int) -> None:
        self.lst.remove(video)

    def longest(self) -> int:
        return self.lst[0]-1
```

#### Language used for code

Python3

#### Expected behavior

The code gets Runtime Error.
![image](https://user-images.githubusercontent.com/11583428/193734043-a8345ba5-4baa-4ee8-b2aa-30534aee1ba2.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Could not add the test case because the test case is ~3MB large. We already have several max tests removing which will allow most TLEs to pass.
Can you suggest a smaller test case to fail the solution? We appreciate your support!
