### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by nitin-agam** [LeetCode-Feedback/LeetCode-Feedback#9331]
#### Your LeetCode username
nitinagam17

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A test case getting failed while the same code I'm running on Playground and given the correct output. For input **"   -42"**, getting output as **-42** on my Playground but failing while submitting my solution.

#### Code you used for Submit/Run operation

```
// https://leetcode.com/problems/string-to-integer-atoi/
class Solution {
    func myAtoi(_ s: String) -> Int {
    
        let charArray = Array(s)
        var result = 0
        var sign = 1

        if charArray.count == 0 { return result }

        for index in 0..<charArray.count {

            let string = charArray[index]

            if string == " " {
                continue
            }

            if string == "-" {
                if sign == 1 {
                    return 0
                }

                sign = -1
                continue
            }

            if string == "+" {

                if sign == -1 {
                    return 0
                }

                sign = 1
                continue
            }

            if let digit = string.wholeNumberValue {
                if (sign * result) < Int32.min {
                    return Int(Int32.min)
                } else if (sign * result) > Int32.max {
                    return Int(Int32.max)
                } else {
                    result = (result * 10) + digit
                }
            } else if result == 0 || string == "." {
                break
            }
        }

        return (sign == 0 ? 1 : sign) * result
    }
}
```

#### Language used for code
Swift

#### Expected behavior
A test case getting failed while the same code I'm running on Playground and given the correct output. For input **"   -42"**, getting output as **-42** on my Playground but failing while submitting my solution.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
