### ISSUE TITLE
Missing Test Case - 166. Fraction to Recurring Decimal

### ISSUE THREAD

**Issue by satzhan** [LeetCode-Feedback/LeetCode-Feedback#9332]
#### Your LeetCode username

Satj

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Now, I say it is missing a testcase, but that's not an issue. 
There is a bug with the tester itself as it doesn't correctly compares my solution output
true value of the test.

My solution gives wrong string output, but LeetCode tests it as correct.

#### Code you used for Submit/Run operation

```
// 166. Fraction to Recurring Decimal
class Solution {
public:
    string fractionToDecimal(int aa, int bb) {
        // b != 0
        // a, b = +- int
        long a = labs(aa), b = labs(bb);
        
        // how to divide two numbers?
        // a / b > 0 ? yes, save the number, else put 0
        // a *= 10 continue;
        // 2 / 165 = 0.0(12)
        // how to catch repeating sequence?
        // let's learn to build the answer first
        
        // Okay so the theory is that the remainder will recur
        // recurring remainder will be the answer
        string ret = to_string(a / b);
        long r = a % b;
        if (r == 0)
            return ret;
        ret += '.';
        unordered_map <int, int > m;
        while (r) {
            if (m.find(r) != m.end()) {
                ret.insert(m[r], "(");
                ret += ')';
                return ret;
            }
            m[r] = ret.size();
            r *= 10;
            ret += to_string(r / b);
            r %= b;
        }
        return ret;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My output, compared to real answer should give Wrong Answer, but currently
it gives Accepted. Screenshot attached where it clearly shows that tester isn't working properly.

#### Screenshots

![image](https://user-images.githubusercontent.com/46739227/193776834-dfa88264-202f-4ffe-b781-30fab636ae48.png)

#### Additional context

The code that I copied here is not a Solution code for the problem, so it naturally will not pass all testcases. 
This code only there to show that the tester doesn't work properly.

**Comment by satzhan** [comment]
I tested a bit more on a working code and I noticed it has a bizarre pattern of particularly being ok with testcases 
when we have a recurring fraction and it should be negative and numerator is less than denominator and denominator is large enough, that is b >> 1 and a / b < 1 and we have a string that should start with "-0.". In cases as such Tester ignores that I don't have "-" negative sign before the rest of the string answer. Somehow it catches all other cases.

![image](https://user-images.githubusercontent.com/46739227/193787092-7e05642d-af48-47c5-b755-41f6f459b0c7.png)
![image](https://user-images.githubusercontent.com/46739227/193787189-492281c8-470a-4f03-b3f9-d41095404d61.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

Best,
