### ISSUE TITLE
Missing Test Case - 2430. Maximum Deletions on a String

### ISSUE THREAD

**Issue by jmy45** [LeetCode-Feedback/LeetCode-Feedback#9334]
#### Your LeetCode username

jmy45

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

#### Description of the bug

the following test case could stuck some AC code:
"ababaababa"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by jmy45** [comment]
The following C++ code which is accepted by the system fails at the test case: "ababaababa".
```
class Solution {
public:
    int deleteString(string s) {
        int ans=0;
        while (1){
            int l=s.size();
            if (l==1){
                ans++;
                break;
            }
            int res=-1;
            vector<int> ne(l);
            for (int j=0,i=1;i<l;i++){
                while (j&&s[j]!=s[i]) j=ne[j-1];
                if (s[j]==s[i]) j++;
                ne[i]=j;
                if (i%2==1 && ne[i]==(i+1)/2)
                    res=max(res,(i+1)/2);
            }
            if (res==-1){
                ans++;
                break;
            }
            ans++;
            s=s.substr(res);
        }
        return ans;
    }
};
```
![WA](https://user-images.githubusercontent.com/10115649/194003999-79156135-78fb-4528-88dc-c0c2ff45573c.PNG)
![AC](https://user-images.githubusercontent.com/10115649/194004415-5bc203bd-2b22-4535-a1d3-0f291c3ee62c.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
