### ISSUE TITLE
Missing Test Case - 2430. Maximum Deletions on a String

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#9335]
#### Your LeetCode username

yumkam

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Accepted solution fails test case below:
```
"agcaaaaeogihkraacgdgaaaaaa"
```

#### Code you used for Submit/Run operation

```c++
static  uint64_t hsh[4005][4005];

class Solution {
public:
  int deleteString(string s) {
    const uint64_t MOD = 99999999999999997LL;
    const unsigned n = s.size();
    for (unsigned i = 0; i < n; i++)
    {
      hsh[i][i] = s[i] - 'a';
      for(unsigned j = i+1; j < n; j++)
      {
        hsh[i][j] = (hsh[i][j-1] * 26 + s[j] - 'a') % MOD;
      }
    }
    vector<int> dp(n+1,1);
    dp[n] = 0;
    for(unsigned i = n; i--; )
    {
      int &ret = dp[i];
      for(unsigned j=i; j < n; j++)
      {
        int x = j + 1;
        int y = x + (j - i);
        if (y < n && hsh[i][j] == hsh[x][y])
          ret = max(ret, dp[x] + 1);
      }
    }
    return dp.front();
  }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
