### ISSUE TITLE
Solution don't run - Counting Sort on Sorting Card

### ISSUE THREAD

**Issue by ElhilaliYassine** [LeetCode-Feedback/LeetCode-Feedback#9336]
#### Your LeetCode username

Elhilali

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On the Counting Sort chapter, in the Sorting card, the proposed code for the algorithm contains a small error, which is the "." is replaced by a ",", before getAsInt(), in the 4th line, in the Java solution

```int K = Arrays.stream(arr).max(),getAsInt();```

#### Language used for code

Java

#### Expected behavior

```int K = Arrays.stream(arr).max().getAsInt();```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
