### ISSUE TITLE
Missing Test Case - 218. The Skyline Problem

### ISSUE THREAD

**Issue by Mohamad655** [LeetCode-Feedback/LeetCode-Feedback#9337]
#### Your LeetCode username

mohammad7892

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution is getting wrong answer on below test case -
`[[2,9,10],[12,15,10]] `

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> getSkyline(vector<vector<int>>& b) {
        vector<vector<int>> ans;
        map<int,vector<pair<int,int>>> mp;
        for(int i=0;i<b.size();i++){
            mp[b[i][0]].push_back({b[i][2],0});
            mp[b[i][1]].push_back({b[i][2],1});
        }
        multiset<int> s;
        int prev=-1;
        for(auto x:mp){
            for(auto v:x.second){
                if(v.second==0)s.insert(v.first);
                else{
                    if(s.find(v.first)!=s.end());
                    s.erase(s.find(v.first));
                }
            }
            if(s.empty()){
                ans.push_back({x.first,0});
                continue;
            }
            int val=*s.rbegin();
            if(val==prev)continue;
            prev=val;
            ans.push_back({x.first,val});
        }
        return ans;
    }
};
```

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
