### ISSUE TITLE
Missing Test Case: 2430. Maximum Deletions on a String

### ISSUE THREAD

**Issue by b4158813** [LeetCode-Feedback/LeetCode-Feedback#9339]
#### Your LeetCode username

b4158813

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case
`"abaabaababaab"`

#### Code you used for Submit/Run operation

``` c++
class Solution {
public:
    int deleteString(string s) {
        int ans = 0;
        while(1){
            int len = s.size();
            if(len == 1){
                ans ++;
                break;
            }
            int res = -1;
            vector<int> kmp(len);
            for(int j=0,i=1;i<len;++i){
                while(j && s[j]!=s[i]) j = kmp[j-1];
                if(s[j]==s[i]) j++;
                kmp[i] = j;
                if(i%2==1 && kmp[i] == (i+1)/2){
                    res = (i+1)/2;
                }
            }
            if(res == -1){
                ans ++;
                break;
            }
            ans ++;
            s = s.substr(res);
            // cout << s << endl;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code above gets a wrong answer on test case `"abaabaababaab"`, but has passed all the system test cases.

#### Screenshots

![image](https://user-images.githubusercontent.com/47494870/193852428-6628cebe-ce68-4feb-8309-e22e446a9a7a.png)

**Comment by jmy45** [comment]
hah，I've used another test case to stuck the same code!

https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/9334

**Comment by jmy45** [comment]
I've found another interesting question!

Yesterday my leetcode UI was like:

![yesterday](https://user-images.githubusercontent.com/10115649/194009632-9f8be5b2-d85d-4ad7-b2c6-c2554c3fca6f.PNG)

Today it changes:

![WA](https://user-images.githubusercontent.com/10115649/194009813-56bbb9f7-661c-4590-9f07-a9ac498278c8.PNG)

Amazing!

**Comment by b4158813** [comment]
> hah，I've used another test case to stuck the same code!
> 
> #9334

haha, thank you ! Actually this code is exactly my own submission during the contest, I never thought it would get an AC, because it does not make any sense. But, it worked well, so the test cases are not strong enough...

**Comment by jmy45** [comment]
> > hah，I've used another test case to stuck the same code!
> > #9334
> 
> haha, thank you ! Actually this code is exactly my own submission during the contest, I never thought it would get an AC, because it does not make any sense. But, it worked well, so the test cases are not strong enough...

I think it is very clever to use KMP algorithm to solve this problem,but the correctness of greedy strategy cannot be proved.
So,we can use KMP+DP instead.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
