### ISSUE TITLE
What does duplicate mean?

### ISSUE THREAD

**Issue by anuj-io** [LeetCode-Feedback/LeetCode-Feedback#934]
Q. https://leetcode.com/problems/find-the-duplicate-number/
Test case : [1,4,4,2,4]
As per Merriam Webster, duplicate means ": consisting of or existing in two corresponding or identical parts or examples". 

Two and not more than two, which is what this test case is doing

**Comment by anuj-io** [comment]
None of the definitions here imply more than two
https://www.merriam-webster.com/dictionary/duplicate

**Comment by lc-kay** [comment]
Hi @anuj-io 

In this problem, the definition "being the same as another" or "to make a copy of" of duplicate can be applied. In addition, the constraints section in the problem states: "All the integers in nums appear only once except for precisely one integer which appears **two or more times.**" 

I hope this clarified the problem set for you!
