### ISSUE TITLE
Missing Test Case - 410. Split Array Largest Sum

### ISSUE THREAD

**Issue by Bonrey** [LeetCode-Feedback/LeetCode-Feedback#9341]
#### Your LeetCode username
ironwolf-2000

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
A missing test case:
`nums.length = 1000`
`nums[i] = 1_000_000` for `0 <= i <= 999`
`m = 1`

#### Code you used for Submit/Run operation

```py
class Solution:
    def splitArray(self, nums: list[int], m: int) -> int:
        def canSplit(limit):
            cur, cnt = 0, 1
            for num in nums:
                cur += num
                if cur > limit:
                    cur = num
                    cnt += 1
            return cnt <= m

        lo, hi = max(nums), 20_000_000
        while lo < hi:
            mi = (lo + hi) // 2

            if canSplit(mi):
                hi = mi
            else:
                lo = mi + 1

        return lo

```

#### Language used for code
Python3

#### Expected behavior
The answer should be `1_000_000_000`, since the array after splitting is the same as the initial one, and the total sum of its elements equals `1000` * `1_000_000` = `1_000_000_000`.

My answer, however, cannot exceed `20_000_000`, as can be seen from my code.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
