### ISSUE TITLE
608. Tree Node - Unable to run test cases

### ISSUE THREAD

**Issue by jdmalter** [LeetCode-Feedback/LeetCode-Feedback#9342]
#### Your LeetCode username
jdmalter

#### Category of the bug
- [x] Other

#### Description of the bug
'Run' always produces the following error: ``` foreign key p_id =  does not exist in the Tree table ```
'Submit' behaves normally.

#### Code you used for Submit/Run operation
```
SELECT * FROM Tree;
```

#### Language used for code
MySQL

#### Expected behavior
With code as provided, expected result to be the same as test case. For example 1, expected result would be the following:

| id | p_id |
| -- | ---- |
| 1  |      |
| 2  | 1    |
| 3  | 1    |
| 4  | 2    |
| 5  | 2    |

#### Additional context
The 4 most recent discussion comments (starting on Sep 30, 2022) reference the same bug.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!

**Comment by jdmalter** [comment]
> First, please check if you are using any global or static variables.

1. There are no global or static variables.

> If you have checked all over your code and did not find any global/static variables usage, chances are your code has bugs in it which cause one of the earlier test cases to trigger an [undefined behavior](https://en.wikipedia.org/wiki/Undefined_behavior#Examples_in_C_and_C.2B.2B).

> In [computer programming](https://en.wikipedia.org/wiki/Computer_programming), undefined behavior (UB) is the result of executing a program whose [behavior](https://en.wikipedia.org/wiki/Behavior) is prescribed to be unpredictable, in the [language specification](https://en.wikipedia.org/wiki/Language_specification) to which the [computer code](https://en.wikipedia.org/wiki/Computer_code) adheres.

2. The error appears even when only one test case is being run.
3. The 'SELECT *' statement is read only which does not modify the database (and cause a change in behavior) and has consistent, predictable results. If the database has undefined behavior between using "Run Code", that would also be a bug.
4. All of the above points are correct, but you chose to close the issue anyway? Please explain in plain language why my points are wrong or why you consider this issue as complete in the context of a MySQL 'SELECT *' statement.

Thank you for responding.
