### ISSUE TITLE
Missing Test Case - 1563. Stone Game V

### ISSUE THREAD

**Issue by marinusdebeer** [LeetCode-Feedback/LeetCode-Feedback#9343]
#### Your LeetCode username
marinusdebeer

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug
The  first example's solution is wrong
input = [6,2,3,4,5,5]
so this becomes => [2,6,4 | 3,5,5] = {12} {13} discard {13}
result = 12
=> [2,4 | 6] = {6} {6} discard 6
result = 12 + 6 = 18;
=> [2 | 4] discard {4}
result = 12 + 6 + 2 = 20
so the answer is supposed to be **20** not 18. I believe

![image](https://user-images.githubusercontent.com/18179323/193957364-99ecb9bd-b830-4fb4-906b-3d37e127a871.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The statement never mentioned that you can change the order of the stones.
The test case is correct. Nothing to change. We appreciate your support!
