### ISSUE TITLE
Missing Test Case - 2430. Maximum Deletions on a String

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#9345]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9711975/2.txt)

#### Code you used for Submit/Run operation

```
from sortedcontainers import SortedList
def cmp(s,i,j,l):
    for k in range(l):
        if s[i+k]!=s[j+k]: return 0
    return 1
class Solution:
    def deleteString(self, s: str) -> int:
        n = len(s)
        sl = SortedList()
        sl.add((1, 0))
        for i in range(1, n):
            for x, j in reversed(sl):
                k = i + i - j
                if k <= n and cmp(s,j,i,i-j): #s[j:i] == s[i:k]
                    sl.add((x + 1, i))
                    break
        return sl[-1][0]
```

#### Language used for code

Python3

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
