### ISSUE TITLE
Missing Test Case - 2430. Maximum Deletions on a String

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#9347]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[3.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9712118/3.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    int S=0;
    public int deleteString(String s) {
        int n = s.length();
        char[] c = s.toCharArray();
        //for (int i=0;i<n;++i)c[i]='a';
        //c[2000]='b';
        int[] dp = new int[n];
        dp[n-1] = 1;
        int maxdp = 2;
        for(int i = n-2; i>=0; i--){
            int dpi = 1;
            level:for(int l = 1; l<=(n-i)/2; l++){
                for(int j=0; j<l; j++){S=S+1;
                    if(c[i+j]-c[i+j+l]!=0) {continue level;}
                }
                //S+=l;
                dpi = Math.max(dpi,dp[i+l]+1);
                if(dpi==maxdp){//剪枝
                    maxdp++;
                    break level;
                }
            }
            dp[i] = dpi;
        }
        System.out.println(S);
        return dp[0];
    }
}
```

#### Language used for code

Java

#### Expected behavior

The code gets TLE.
![image](https://user-images.githubusercontent.com/11583428/193966384-5e6d13d9-3e54-4db6-afcd-e7b23208e0a7.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
