### ISSUE TITLE
Missing Test Case - 1575. Count All Possible Routes

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#935]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution from discuss section is accepted, but fails on the following test case:

[15, 17, 12, 8, 18]
4
1
1

#### Code you used for Submit/Run operation
<pre>
class Solution {
	long[][] dp;
	int mod = (int)(1e9+7);

	public long function(int[] arr, int s, int f, int fuel) {

		if(fuel < 0) return 0;

		long ans = 0;
		if(dp[s][fuel] >= 0) return dp[s][fuel];

		if(fuel >= 0 && s == f) ans+=1;

		for(int i=0; i<arr.length; i++) 
			if(i != s) ans += function(arr, i, f, fuel - Math.abs(arr[i] - arr[s])) % mod;

		dp[s][fuel] = ans%mod;
		return ans;
	}

	public int countRoutes(int[] locations, int start, int finish, int fuel) {
		if(Math.abs(start - finish) > fuel) return 0;

		dp= new long[locations.length][fuel+1];
		for(long[] ar : dp) Arrays.fill(ar, -1);

		return (int)(function(locations, start, finish, fuel)%mod);
	}
}
</pre>

#### Language used for code
Java

#### Expected behavior

The solution should not be accepted since it fails on a test case

#### Additional context

Link to the solution:
https://leetcode.com/problems/count-all-possible-routes/discuss/830590/Java-Recursive-Memoization-or-Easy-Solution

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
