### ISSUE TITLE
608. Tree Node - Invalid erroneous test cases

### ISSUE THREAD

**Issue by jaisal1311** [LeetCode-Feedback/LeetCode-Feedback#9350]
#### Your LeetCode username
jaisalShah

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Invalid erroneous test cases

#### Description of the bug

Default provided test cases are returning error mentioned below:
foreign key p_id = null does not exist in the Tree table

#### Code you used for Submit/Run operation

```
select id, case 
when id not in (select p_id from tree where p_id is not null) then 'Leaf'
when p is null then 'Root'
else "Inner"
end
from tree;
```

#### Language used for code

MySQL

#### Screenshots

![image](https://user-images.githubusercontent.com/57360897/193983668-524ebc21-f495-4786-8d89-2f81612f6e3f.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. You are using p while the column name is p_id.  We appreciate your support!
