### ISSUE TITLE
题库第88题，题目描述不清楚

### ISSUE THREAD

**Issue by Naturer** [LeetCode-Feedback/LeetCode-Feedback#9352]
**你的 LeetCode 用户名**
Naturer

**Bug 类型**
- [ ] 题目

**描述**
题目描述不清楚
背景：“非递减顺序”，有没有可能会出现重复的元素呢？题目和示例中均为指出，且示例上是没有重复的元素。
后果：可能会造成误导。我看到网络上有很多人提出同样的问题。

**期望行为**
希望能在文中或者示例上指出。

**Comment by feiceh** [comment]
您好，在与相关团队核实后：不处理 （作为术语）
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
