### ISSUE TITLE
make return type to long instead of int...! and the array element value should be increased from - 10 to 10 to at least -50 to 50

### ISSUE THREAD

**Issue by Chennareddy44** [LeetCode-Feedback/LeetCode-Feedback#9354]
#### Your LeetCode username
kckr44

#### Category of the bug
- [x] Question

#### Description of the bug
make return type to long instead of int...! and the array element value should be increased from - 10 to 10 to at least -50 to 50.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Chennareddy44** [comment]
The problem name :  152. Maximum Product Subarray

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
