### ISSUE TITLE
Missing Test Case - 1587. Bank Account Summary II

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#9357]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case that the balance is exactly 10000 so that it allows solutions querying a balance **higher than or equal to** (instead of **higher than**) 10000 to pass.

#### Code you used for Submit/Run operation

```
SELECT name, SUM(amount) AS balance
FROM Users AS u JOIN Transactions AS t ON t.account = u.account
GROUP BY name
HAVING SUM(amount) >= 10000
```

#### Language used for code
MySQL

#### Expected behavior
The solution should receive Wrong Answer.

#### Screenshots
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/49032034/194199325-6ffeedaa-2b5b-4516-bb0e-cf8cd2213fa1.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
