### ISSUE TITLE
Missing Test Case - 981. Time Based Key-Value Store

### ISSUE THREAD

**Issue by abdulmoomin007** [LeetCode-Feedback/LeetCode-Feedback#9358]
#### Your LeetCode username
abdulmoomin007

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The below testcase provides a Time Limit Exceeded error for the mentioned code below in JavaScript, But all the available test cases got passed.
Constraint states that "At most 2 * 10^5 calls will be made to set and get." Here I have only made less than a 1000 request and the test case got failed.
Could this be a missing testcase?

["TimeMap","set","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get","get"]
[[],["foo","bar",1],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000],["foo",10000000]]

#### Code you used for Submit/Run operation

```
class TimeMap {
    constructor() {
        this.map = {};
    }
    
    set(key, value, timestamp) {
        if(this.map[key]) {
            this.map[key][timestamp] = value;
        }
        else {
            this.map[key] = {}
            this.map[key][timestamp] = value;
        }
    }
    
    get(key, timestamp) {
        if(this.map[key]) {
            if(this.map[key][timestamp]) return this.map[key][timestamp];
            while(--timestamp > -1) {
                if(this.map[key][timestamp]) return this.map[key][timestamp];
            }
        }
        return "";
    }
}
```

#### Language used for code
JavaScript

#### Expected behavior
Time Limit Exceeded for this testcase, but all the test cases passed in the available test cases.

#### Screenshots
![Screenshot (7)](https://user-images.githubusercontent.com/32864519/194207138-b270ea6e-7d3f-4380-b861-72cbea0c15b2.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
