### ISSUE TITLE
BUG: Video mentioned for topological sort is completely opposite.

### ISSUE THREAD

**Issue by samueltjoy** [LeetCode-Feedback/LeetCode-Feedback#9364]
#### Your LeetCode username
samueltjoy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The video mentioned for Topological sort is completely opposite.
https://leetcode.com/explore/learn/card/graph/623/kahns-algorithm-for-topological-sorting/3869/

for input 
![Screen Shot 2022-10-06 at 5 37 51 PM](https://user-images.githubusercontent.com/30645937/194308625-22fb44d6-26ee-47e2-91bf-dbaebe5223c6.png)

**BUG:But in the video it tells [3,2,1,0]**

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
