### ISSUE TITLE
Missing Test Case - 981. Time Based Key-Value Store

### ISSUE THREAD

**Issue by iamvpa** [LeetCode-Feedback/LeetCode-Feedback#9366]
#### Your LeetCode username

iamvpa

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case since brute force is also working

#### Code you used for Submit/Run operation

```
class TimeMap {
public:
    map<string,string>mp;
    TimeMap() {
        
    }
    
    void set(string key, string value, int timestamp) {
        string key_n=key+to_string(timestamp);
        mp[key_n]=value;
    }
    
    string get(string key, int timestamp) {
        if(timestamp==0)
            return "";
        string key_n=key+to_string(timestamp);
        return mp.find(key_n)!=mp.end()?mp[key_n]:get(key,timestamp-1);
    }
};

```

#### Language used for code

C++

#### Expected behavior

Time Limit Exceeded

#### Additional context

There should be a test case added so that brute forcing should give time limit exceeded

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution here gives runtime error on a newly added test case.. We appreciate your support!
