### ISSUE TITLE
Missing Test Case - 200. Number of Islands

### ISSUE THREAD

**Issue by ajszoke** [LeetCode-Feedback/LeetCode-Feedback#9368]
#### Your LeetCode username
zoke2556

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
On "number-of-islands": submission output differs from debugger output in Python3. The same code that will correctly output ```3``` for the test case ```[["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]``` from the debugger will output ```2``` in the submission checker. The difference is consistent between runs.

#### Code you used for Submit/Run operation
```
class Solution:
    tile_set = set()
    grid = None
    res = 0
    rows = 0
    cols = 0

    def numIslands(self, grid: List[List[str]]) -> int:
        self.rows = len(grid)
        self.cols = len(grid[0])
        self.grid = grid
        for i in range(self.rows):
            for j in range(self.cols):
                if grid[i][j] == "1" and tuple([i, j]) not in self.tile_set:
                    self.res += 1
                    self.tile_set.add(tuple([i, j]))
                    self.search(i, j)

        return self.res

    def search(self, i, j):
        if tuple([i, j]) not in self.tile_set:
            self.tile_set.add(tuple([i, j]))
        if j > 0 and self.grid[i][j-1] == "1" and tuple([i, j-1]) not in self.tile_set:
            self.search(i, j-1)
        if j < (self.cols - 1) and self.grid[i][j+1] == "1" and tuple([i, j+1]) not in self.tile_set:
            self.search(i, j+1)
        if i < (self.rows - 1) and self.grid[i+1][j] == "1" and tuple([i+1, j]) not in self.tile_set:
            self.search(i+1, j)
```

#### Language used for code
Python3

#### Expected behavior
The debugger output should match the submission output for the same test case.

#### Screenshots
![image](https://user-images.githubusercontent.com/6426909/194353335-f5147e45-4c25-4e36-97cb-b282c64dae42.png)
![image](https://user-images.githubusercontent.com/6426909/194353499-c73a1682-3f45-4ac4-bf5e-d30633bd3712.png)

#### Additional context
The code correctly outputs ```3``` from a separate IDE (PyCharm), leading me to think the error is in the submission checker engine.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.

We appreciate your time and support! If you have any other questions, please don't hesitate to let us know.
