### ISSUE TITLE
Top K Frequent Elements official solution crashed for me

### ISSUE THREAD

**Issue by yi-xuan-97** [LeetCode-Feedback/LeetCode-Feedback#9370]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![Screen Shot 2022-10-06 at 12 30 09 PM](https://user-images.githubusercontent.com/56617127/194402181-6f902be0-215d-4acb-a71c-edd7e97737b5.png)

**Comment by yi-xuan-97** [comment]
Crushed solution

**Comment by LC-Pam** [comment]
Thank you for your time. The page works correctly. We appreciate your support!
