### ISSUE TITLE
Typos in solution

### ISSUE THREAD

**Issue by ausgang0** [LeetCode-Feedback/LeetCode-Feedback#9372]
#### Your LeetCode username

ulyanov

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In approach 3 there are several typos:

1.
> Add another new event [5, 6), then we split the interval [0,11) into [0, 5) and [5, 11), [11, 21) into [11, 16) and [16, 21), then we increase the events in [5, 11) and [11, 21) by 1.

It's [5,11) interval which we're adding, not [5,6)

2.
> Binary search all starting points in intervals to find the first interval [L1, R1) that has L1 >= start, then we split the interval into [L1, start) and [start, R1), keep the events in them the same as the origin interval [L1, R1), and put them back in intervals container.

"that has L1 <= start", not >=

3.
> Similarly, perform a binary search to get the first [L2, R2) that satisfies L2 <= end, split it into[L2, start) and [start, R2) and inserting them into intervals.

"split it into[L2, end) and [end, R2)"

4.
> For all non-empty intervals between [start, R1) and [start, R1) inclusively in intervals, increase the events of them by 1 as we added a new event in time [start, end) just now.

"between [start, R1) and [L2, end)"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ausgang0** [comment]
https://leetcode.com/problems/my-calendar-iii/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We are using your feedback to update the problem.  We appreciate your support!
