### ISSUE TITLE
Missing Test Case - 232. Implement Queue using Stacks

### ISSUE THREAD

**Issue by jbmanning** [LeetCode-Feedback/LeetCode-Feedback#9373]
#### Your LeetCode username

jbmanning

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The definition for this problem includes the functions `peek()` and `pop()` defined as returning a number. Instead, I believe they should be typed to return `number | null` (or some equivalent) since the queue is not necessarily always going to have members to peek / pop.

#### Code you used for Submit/Run operation

```
class MyQueue {
    // ...
    pop(): number | null {}
    peek(): number | null {}
    // ...
}
```

#### Language used for code

Typescript, but the issue likely exists in other languages as well.

#### Expected behavior

Type signature should match all possible outcomes. 

#### Screenshots

N/A

#### Additional context

N/A

**Comment by stormsunshine** [comment]
All the calls to `pop` and `peek` are valid. So the issue you mention here does not exist.
