### ISSUE TITLE
Missing Test Case - 200. Number of Islands

### ISSUE THREAD

**Issue by Pavitra321** [LeetCode-Feedback/LeetCode-Feedback#9375]
**Your LeetCode username**
pavitra_patidar_04

**Category of the bug**
 Missing Test Cases

**Code you used for Submit/Run operation**
Input: grid = [
  ["1","1","0","0","0"],
  ["1","1","0","0","0"],
  ["0","0","1","0","0"],
  ["0","0","0","1","1"]
]

**Language used for code**
Java

**Expected behavior**
O/P-> 1

**Additional context**
According to other platform like gfg and other the output of above given test case should be the 1(one) and my output is also 1
but  **your output is 4.**
Please any one explain me how output is 4.  

**Screenshots**
![Screenshot (17)](https://user-images.githubusercontent.com/103557268/194471838-650c6c46-1158-467e-8f84-fccfdff01915.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
