### ISSUE TITLE
732. My Calendar III

### ISSUE THREAD

**Issue by vigneshshiv** [LeetCode-Feedback/LeetCode-Feedback#9376]
#### Your LeetCode username
vigneshshiv

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Approach 1: **Sweep-line algorithm mentioned to create a HashMap** but the actual code implementation is **TreeMap**. Correct the solution wordings, would be better. 

![image](https://user-images.githubusercontent.com/10242660/194472970-15b524d3-f199-4a0d-968b-ecd340673615.png)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
