### ISSUE TITLE
My Calendar III - incorrect template for ruby

### ISSUE THREAD

**Issue by XmmmiR** [LeetCode-Feedback/LeetCode-Feedback#9377]
#### Your LeetCode username
xmmmir

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

MyCalendarThree#book is using `end` as second parameter, which is reserved word in ruby. It should be replaced with something like `finish`. 

#### Code you used for Submit/Run operation
```ruby
class MyCalendarThree
    def initialize()
        
    end


=begin
    :type start: Integer
    :type end: Integer
    :rtype: Integer
=end
    def book(start, end)
        
    end


end

# Your MyCalendarThree object will be instantiated and called as such:
# obj = MyCalendarThree.new()
# param_1 = obj.book(start, end)
```

#### Language used for code
Ruby

#### Expected behavior
Template implementation should fail with "Wrong answer"

#### Screenshots
![image](https://user-images.githubusercontent.com/2445964/194515138-acba5cda-b0ed-4963-9d41-5f80a2a8b23d.png)

**Comment by juumixx** [comment]
Same error exists for Elixir

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
