### ISSUE TITLE
Typo in 732. My Calendar III Solution Approach 2

### ISSUE THREAD

**Issue by medvied** [LeetCode-Feedback/LeetCode-Feedback#9379]
#### Your LeetCode username
`medvied`

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Approach 2: Segment Tree has the following sentence:

> If start <= L and R >= end - 1, the range represented by this node is completely contained in [start, end - 1]

If we draw a line with coordinates it would look like the following:
```
    start               end - 1
      +--------------------+
      |                    |
      v                    v
======+=======+============+=======+=============>
              ^                    ^
              |                    |
              +--------------------+
              L                    R
```

As we see from the drawing above the range [L, R] is _not_ completely contained in [start, end - 1].
The sentence should have `R >= end - 1` replaced with `R <= end - 1` , in this case the line with coordinates would look like this:
```
    start                       end - 1
      +----------------------------+
      |                            |
      v                            v
======+=======+============+=======+=============>
              ^            ^
              |            |
              +------------+
              L            R
```

In this case the range [L, R] is completely contained in [start, end - 1].

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

The following sentence in Solution Approach 2: Segment Tree has the following sentence:

> If start <= L and R >= end - 1, the range represented by this node is completely contained in [start, end - 1]

should be replaced with

> If start <= L and R <= end - 1, the range represented by this node is completely contained in [start, end - 1]

i.e. `R >= end - 1` part should be replaced with `R <= end - 1`.

#### Screenshots

N/A

#### Additional context

N/A

**Comment by KarthikNedunchezhiyan** [comment]
+1

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
