### ISSUE TITLE
732 My Calendar III - Typo in Solution Approach 3: Balanced Tree.

### ISSUE THREAD

**Issue by xylestr** [LeetCode-Feedback/LeetCode-Feedback#9381]
#### Your LeetCode username

xylestr

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typo in the Solution section's **Approach 3: Balanced Tree**.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

_Add another new event **[5, 6)**, then we split the interval [0,11) into [0, 5) and [5, 11), [11, 21) into [11, 16) and [16, 21), then we increase the events in [5, 11) and [11, 21) by 1._

should be

_Add another new event **[5, 16)**, then we split the interval [0,11) into [0, 5) and [5, 11), [11, 21) into [11, 16) and [16, 21), then we increase the events in [5, 11) and [11, 21) by 1._

#### Screenshots

<img width="740" alt="Screenshot 2022-10-07 at 8 36 47 PM" src="https://user-images.githubusercontent.com/83827681/194586375-a3546d30-77d2-4cf7-bd75-23ef51f7a3b9.png">

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
