### ISSUE TITLE
Missing test cases - 2423 - Remove Letter To Equalize Frequency

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [LeetCode-Feedback/LeetCode-Feedback#9382]
#### Your LeetCode username
[karthik_nedunchezhiyan](https://leetcode.com/karthik_nedunchezhiyan/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The attached code gets accepted, but the code produces the wrong output for the attached test case.

#### Test Case:

Input: "bbcccc"
Output: false

#### Code you used for Submit/Run operation
```
class Solution {
private:
    bool case1(int max_elm_idx, vector<int> &frequency) {
        for (int i = 0; i < frequency.size(); ++i) {
            if (!frequency[i] || i == max_elm_idx) continue;

            if (frequency[i] != (frequency[max_elm_idx] - 1)) return false;
        }

        return true;
    }

    bool case2(int max_elm_idx, vector<int> &frequency) {
        bool pit_found = false;
        for (int i = 0; i < frequency.size(); ++i) {
            if (frequency[i] == 0 || frequency[i] == frequency[max_elm_idx]) continue;
            if (pit_found) return false;
            pit_found = true;
        }

        return pit_found;
    }

public:
    bool equalFrequency(string word) {
        vector<int> frequency(26);

        int max_elm_idx = 0;

        for (int i = 0; i < word.length(); ++i)
            if (++frequency[word[i] - 'a'] > frequency[max_elm_idx]) max_elm_idx = word[i] - 'a';
        
        return (frequency[max_elm_idx] == 1) || case1(max_elm_idx, frequency) || case2(max_elm_idx, frequency);
    }
};
```

#### Language used for code
C++

#### Expected behavior
This code **should not** have to get accepted.

#### Additional context
In the above code, `if (pit_found) return false;` should be rewritten as `if (pit_found || frequency[i] != 1) return false;` to make the algorithm right.

I have raised this problem on leetcode website also https://leetcode.com/contribute/38059.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by KarthikNedunchezhiyan** [comment]
Here you go https://leetcode.com/submissions/detail/813048656/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The problem is from the a recent BC and we added more test cases and this solution is now WA.
Did not add the test case. We appreciate your support!
