### ISSUE TITLE
Typo in solution for "732. My Calendar III"  in block "Approach 3: Balanced Tree"

### ISSUE THREAD

**Issue by aplisau** [LeetCode-Feedback/LeetCode-Feedback#9383]
#### Category of the bug
- [x] Solution

#### Description of the bug

In https://leetcode.com/problems/my-calendar-iii/solution/ 
 block "Approach 3: Balanced Tree"
 in text:
 "Add another new event [5, 6), then we split the interval [0,11) into [0, 5) and [5, 11), [11, 21) into [11, 16) and [16, 21), then we increase the events in [5, 11) and [11, 21) by 1."
 instead of "new event [5, 6), " there should be "new event [5, 16), "

#### Screenshots

![image](https://user-images.githubusercontent.com/99673124/194602719-2c5494d2-061b-49b7-8dd1-64fda60d4bb8.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
