### ISSUE TITLE
Wrong time complexity in solution- 779. K-th Symbol in Grammar

### ISSUE THREAD

**Issue by Hao-YunDeng** [LeetCode-Feedback/LeetCode-Feedback#9384]
#### Description of the bug

Wrong time complexity in the Binary Count solution! It should be O(logK) since we are count bits for K. And because K is on the scale of 2^N, so the bit shifting method is same as the recursion in time, and they both are O(N)!!!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
