### ISSUE TITLE
SubmissionErrorsinContest311

### ISSUE THREAD

**Issue by Pradeep-Kumar-3325** [LeetCode-Feedback/LeetCode-Feedback#9386]
#### Your LeetCode username

Pradeep Kumar
**pradeep_kumar_3325**

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Submission errors in “2416. Sum of Prefix Scores of Strings of weekly-contest-311” 

#### Code you used for Submit/Run operation

```
public class Solution {
    public int[] SumPrefixScores(string[] words) {
            Trie trie = new Trie();
            for (int i = 0; i <= words.Length - 1; i++)
            {
                trie.Insert(words[i]);
            }

            trie.DFS(Trie.Root);

            int[] answer = new int[words.Length];

            for (int i = 0; i <= words.Length - 1; i++)
            {
                answer[i] = trie.GetNoofPrefix(words[i]);
            }

        //answer[0]=4;
            return answer;
        
    }
    
    public class Node
        {
            public bool IsEnd { get; set; }

            public Node[] chidren = new Node[26];

            public char Value { get; set; }

            public int NoofPreffix { get; set; }
        }

        public class Trie
        {
            public static Node Root;
            public void Insert(string word)
            {
                if (Root == null)
                {
                    Root = new Node();
                }

                Node current = Root;
                int index;

                for (int i = 0; i <= word.Length - 1; i++)
                {
                    index = word[i] - 'a';
                    if (current.chidren[index] == null)
                        current.chidren[index] = new Node();
                    current.chidren[index].Value = word[i];
                    current = current.chidren[index];
                }


                current.IsEnd = true;
            }

            public int DFS(Node root)
            {
                if (root == null) return 0;

                int count = 0;
                foreach (Node node in root.chidren)
                {
                   count += DFS(node);
                }

                if (root.IsEnd)
                {
                    count = count + 1;
                }
                root.NoofPreffix = count;
                return root.NoofPreffix;
            }

            public int GetNoofPrefix(string word)
            {
                Node current = Trie.Root;
                int ans = 0;
                for (int i = 0; i <= word.Length - 1; i++)
                {
                    current = current.chidren[word[i] - 'a'];
                    ans += current.NoofPreffix;
                }

                return ans;
            }
        }
}

```

#### Language used for code

C#

#### Expected behavior

Excepted result is 4 for input ["abcd"]

#### Screenshots

![image](https://user-images.githubusercontent.com/83135200/194624485-ab7fae75-63ed-4035-80ff-db2d69ddf62f.png)
![image](https://user-images.githubusercontent.com/83135200/194624527-b291c31b-acf5-4e55-a943-cb6ec0f2b440.png)
![image](https://user-images.githubusercontent.com/83135200/194624595-fe14c1da-9a93-49f5-928b-0f882b7ba2bc.png)

#### Additional context

I believe there is an issue in submission of “2416. Sum of Prefix Scores of Strings of weekly-contest-311” because when I submit my solution then it gives wrong answer for this testcase 

 

But when I execute custom testcase with same input in it pass

 

Even when I run the same solution on my local with same input it returns excepted result that is 4. Please refer to the below screen shot from my local machine.

 

So, it seems there is issue submission for this input. My solution in C#

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
