### ISSUE TITLE
Wrong Test Case - 458. Poor Pigs

### ISSUE THREAD

**Issue by aavishkarmishra** [LeetCode-Feedback/LeetCode-Feedback#9387]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a test case as following : 
`125
1
4`
which result `3` but the ans will be `4`.

#### Expected behavior
Result of given testcase should be 4 instead of 3.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
