### ISSUE TITLE
Missing Test Case - 236. Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by DmitryAks** [LeetCode-Feedback/LeetCode-Feedback#9388]
#### Your LeetCode username

aksenkin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In case of an implementation of this Solution in Swift then definition of the method looks like
```
func lowestCommonAncestor(_ root: TreeNode?, _ p: TreeNode?, _ q: TreeNode?) -> TreeNode?
```
a returned result as optional TreeNode node assumes that method can return nil

but in case it really returns nil value I get Runtime error.

Event if the method body contains simple ```return nil```
in order to  use it recursively it needs to return nil.

#### Code you used for Submit/Run operation

```
func lowestCommonAncestor(_ root: TreeNode?, _ p: TreeNode?, _ q: TreeNode?) -> TreeNode? {
       
       return nil

        /*
        guard let node = root, let pNode = p, let qNode = q else {
            return nil
        }
        
        var foundLeft = lowestCommonAncestor(node.left, p, q)
        var foundRight = lowestCommonAncestor(node.right, p, q)
        
        
        if foundLeft == nil {
            return foundRight
        }
        
        if foundRight == nil {
            return foundLeft
        }
        
        return node*/
        
    }
```

#### Language used for code
Swift

#### Expected behavior

Method should not produce Runtime error if it returns nil

#### Screenshots

<img width="434" alt="Screen Shot 2022-10-08 at 12 28 11 AM" src="https://user-images.githubusercontent.com/64834259/194658645-c8f50b78-6d55-40d9-adb2-94bcf2f06da9.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
