### ISSUE TITLE
Missing Test Case - 2431. Maximize Total Tastiness of Purchased Fruits

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#9390]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
A solution which can be accepted fails on the specific testcase:
[0]
[1]
0
1
Output: 0
Expected: 1

Code you used for Submit/Run operation

```
class Solution:
    def maxTastiness(self, price: List[int], tastiness: List[int], maxAmount: int, maxCoupons: int) -> int:

        @cache
        def dfs(p,leftmoney,leftx):
            if p==len(price) or leftmoney==0:
                return 0
            ans = dfs(p+1,leftmoney,leftx)
            if leftmoney>=price[p]:
                ans=max(ans,tastiness[p]+dfs(p+1,leftmoney-price[p],leftx))
            if leftx and leftmoney>=price[p]//2:
                ans = max(ans,tastiness[p]+dfs(p+1,leftmoney-price[p]//2,leftx-1))
            return ans
        
        return dfs(0,maxAmount,maxCoupons)
```

Language used for code
Python3

Expected behavior
A testcase should be added to make the wrong solution get WA:
[0]
[1]
0
1

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
