### ISSUE TITLE
Two typos in 732. My Calendar III

### ISSUE THREAD

**Issue by revug** [LeetCode-Feedback/LeetCode-Feedback#9391]
#### Your LeetCode username

codingstar1

#### Category of the bug
- [x] Solution

#### Description of the bug

In approach 3 there are two typos:
Add another new event [5, 6) **(CORRECT IS [5, 16) )**, then we split the interval [0,11) into [0, 5) and [5, 11), [11, 21) into [11, 16) and [16, 21), then we increase the events in [5, 11) and [11, 21) **(CORRECT IS [11, 16) )** by 1.

#### Screenshots

https://i.ibb.co/6YQ78F2/Screenshot-1.png

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
