### ISSUE TITLE
Mistake in template for Ruby in 732. My Calendar III

### ISSUE THREAD

**Issue by revug** [LeetCode-Feedback/LeetCode-Feedback#9392]
#### Your LeetCode username

codingstar1

#### Category of the bug
- [x] Language

#### Description of the bug

As all you know, `end` is a keyword in Ruby programming language, so it is forbidden to use it as a name of a variable. `def book(start, end)` should be replaced with     `def book(start, end_)` or something else.

#### Code you used for Submit/Run operation

```ruby
    def book(start, end)
        
    end
```

#### Language used for code

Ruby

#### Screenshots

https://i.ibb.co/9nL0jXM/Screenshot-2.png

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by revug** [comment]
This issue was solved.
https://leetcode.com/problems/my-calendar-iii/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
