### ISSUE TITLE
Missing test case: 16. 3Sum Closest

### ISSUE THREAD

**Issue by yuhan-wang** [LeetCode-Feedback/LeetCode-Feedback#9393]
#### Your LeetCode username

yuhan-wang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The problem has missing test cases causing wrong answers to be accepted. Example test case
`nums = [0, 3, 97, 102, 200], target = 300`

#### Code you used for Submit/Run operation

```
class Solution:
    def threeSumClosest(self, nums: List[int], target: int) -> int:
        nums.sort()
        n = len(nums)
        result = None
        min_diff = float('inf')
        l, r = 0, n-1
        while l+1 < r:
            sub_target = target - nums[l] - nums[r]
            mid = bisect.bisect_left(nums, sub_target, lo=l+1, hi=r-1)
            if mid > l+1 and abs(sub_target - nums[mid-1]) < abs(sub_target - nums[mid]):
                mid -= 1
            if nums[mid] > sub_target:
                diff = nums[mid] - sub_target
                if diff < min_diff:
                    result = target + diff
                    min_diff = diff
                r -= 1
            elif nums[mid] < sub_target:
                diff = sub_target - nums[mid]
                if diff < min_diff:
                    result = target - diff
                    min_diff = diff
                l += 1
            else:
                return target
        return result
```

#### Language used for code

Python3

#### Expected behavior

For the test case 
`nums = [0, 3, 97, 102, 200], target = 300`
the correct output should be 300, but the above code, which was accepted has output 302.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by yuhan-wang** [comment]
Python3

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
