### ISSUE TITLE
missing testcase: LeetCode #16. 3Sum Closest 

### ISSUE THREAD

**Issue by yifuzhang19** [LeetCode-Feedback/LeetCode-Feedback#9394]
#### Your LeetCode username

zhanghaotian19

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

missing test case for LeetCode #16

#### Code you used for Submit/Run operation

```
class Solution:
    def threeSumClosest(self, nums: List[int], target: int) -> int:
        nums.sort()
        n = len(nums)
        result = float('inf')
        for i in range(2, n):
            cur_sum = nums[i - 2] + nums[i - 1] + nums[i]
            if  cur_sum < target and i != n - 1:
                result = self.helper(cur_sum, target, result)
                continue
            cur_sum = nums[0] + nums[1] + nums[i]
            if nums[0] + nums[1] + nums[i] > target and i > 2:  
                #result = self.helper(cur_sum, target, result)
                break
            left, right = 0, i - 1
            while left < right:
                cur_sum = nums[left] + nums[right] + nums[i]
                result = self.helper(cur_sum, target, result)
                if cur_sum == target:
                    return result
                if cur_sum > target:
                    right -= 1
                else:
                    left += 1
        
        return result
    
    
    def helper(self, cur_sum, target, result):
        return result if abs(result - target) <= abs(cur_sum - target) else cur_sum
        
```

#### Expected behavior

The above codes passed all leetCode tests but the code is actually wrong, in that by using the following self-defined test case:
[1,2,10, 200]
190
The above algorithm returns 13, wherease the correct answer is 203.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
