### ISSUE TITLE
Missing Test Case in 16) 3Sum Closest

### ISSUE THREAD

**Issue by MohakHarjani** [LeetCode-Feedback/LeetCode-Feedback#9395]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Their is a missing test case in 16. 3Sum Closest question

#### Code you used for Submit/Run operation
```
class Solution {
    public int threeSumClosest(int[] nums, int targetSum) 
    {
        int n = nums.length;
        Arrays.sort(nums);
        int mnDiff = Integer.MAX_VALUE, ans = -1;
        for (int i = 0; i <= n - 3; i++)
        {
            int low = i + 1, high = n - 1;
            int target = targetSum - nums[i];
            int bestSum = 0; 
            while(low < high)
            {
                bestSum = nums[low] + nums[high];
                if (bestSum == target) break;
                if (bestSum < target) low++;
                else high--;
            }
            int diff = Math.abs(targetSum - (bestSum + nums[i]));
            if (diff < mnDiff)
            {
                mnDiff = diff;
                ans = bestSum + nums[i];
            }
        }
        return ans;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The above code passes all the test cases and got Accepted, but it is actually wrong 
Test case ==>
[2,3,8,9,10]
16

The above code returns 19, But the actual solution should be 15

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
