### ISSUE TITLE
Missing Test Case - 16. 3Sum Closest

### ISSUE THREAD

**Issue by anirudhgajula** [LeetCode-Feedback/LeetCode-Feedback#9399]
#### Your LeetCode username
rednoserudolph

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
For input [-1000,-1000,-1000] (minimum possible values for input) and target = 10000 (the maximum possible target), solutions of the form below that set initial upper values less than 23001 lead to an incorrect result. The minimum initial upper value should be 23001 and above, so that even in the worst case scenario where sum = -3000 and target = 10000, the variable closest (which is tracking the closest possible sum to target) is updated to the sum, -3000.

#### Code you used for Submit/Run operation

```
int threeSumClosest(int* nums, int numsSize, int target){
    /*mergeSort function was self-coded in C*/
    mergeSort(nums, 0, numsSize - 1); int closest = 20001;
    for (int *curr = nums; curr < nums + numsSize - 2; curr++) {
        int *curr1 = curr + 1; int *curr2 = nums + numsSize - 1;
        int sum = *curr + *curr1 + *curr2;

        while (curr1 != curr2) {
            sum = *curr + *curr1 + *curr2;
            if (sum < target) {
                if (abs(closest - target) > abs(sum - target)) closest = sum;
                curr1++;
            }
            else if (sum > target) {
                if (abs(closest - target) > abs(sum - target)) closest = sum;
                curr2--;
            }
            else {
                return target;
            }
        }
    }
    return closest;
}
```

#### Expected behavior
 A new test case of [-1000, -1000, -1000] and target = 10000 are being proposed to ensure that solutions of the above form are required to use an upper bound of 23001 and above for their closest possible sum initial value.

#### Screenshots

![image](https://user-images.githubusercontent.com/108511922/194707929-55dc6805-7a5c-49c3-bc79-3da15b12bdb4.png) The new proposed test case is an extension of the current test case of [0, 0, 0] and target = 10000 that is already in use. The above test case was failed after naively setting the initial value of the closest possible sum to 20000, but a stricter test case of [-1000,-1000,-1000] and target = 10000 may be a stricter test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by anirudhgajula** [comment]
C was used to obtain this result. Thanks!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission accepted link since we received Compile Error when we submit the code.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by anirudhgajula** [comment]
https://leetcode.com/submissions/detail/817789064/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
