### ISSUE TITLE
Evident Cheating in Biweekly 22

### ISSUE THREAD

**Issue by SamZhangQingChuan** [LeetCode-Feedback/LeetCode-Feedback#94]
**What kind of the bug**
- [x] staff

**Describe the bug**

In the [Biweekly 22](https://leetcode.com/contest/biweekly-contest-22/ranking/), it is crystal clear that one of `#7 please_AC` and `#12 han3000` plagiarized the other's code for q4. 

I've reported multiple times to the staff at LC-CN and yet there hasn't been any action taken.  If this kind of behavior is allowed and the codes are not deemed as cheating , I strongly suggest Leetcode remove the rule saying that:

>LeetCode heavily emphasizes on the justice and fairness of our contests. We have absolutely ZERO TOLERANCE for violation behaviors (such as plagiarism, cheating, etc).

as it doesn't deserve boasting while other sites such as Codechef and Codeforces have strict and automatic plagiarism detection mechanism deployed.

Please DON'T disappoint your users.

**Suspicious codes**
```cpp
class Solution:
    def maxSizeSlices(self, slices: List[int]) -> int:
        import functools
        @functools.lru_cache(None)
        def dp(i, j, k, loop = 0):
            if k == 1:
                return max(slices[i:j+1])
            if j - i + 1 < k * 2 - 1:
                return -float('inf')
            return max(dp(i + loop, j - 2, k - 1) + slices[j], dp(i, j - 1, k))
        
        return dp(0, len(slices) - 1, len(slices) // 3, 1)
```

```cpp
# coding=utf-8
# Author: lee215
import functools

class Solution:
    def maxSizeSlices(self, A):

        @functools.lru_cache(None)
        def dp(i, j, k, loop=0):
            if k == 1: return max(A[i:j + 1])
            if j - i + 1 < k * 2 - 1: return -float('inf')
            return max(dp(i + loop, j - 2, k - 1) + A[j], dp(i, j - 1, k))
        return dp(0, len(A) - 1, len(A) // 3, 1)
```

**Comment by feiceh** [comment]
你好，Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，请知晓。

**Comment by SamZhangQingChuan** [comment]
好的，我会每周发一次直到有人管这事

**Comment by hairman123** [comment]
支持 @SamZhangQingChuan ，这就是 LeetCode 中国区的工作人员的态度，
我反馈题目 502 IPO 的 [官方题解](https://leetcode-cn.com/problems/ipo/solution/ipo-by-leetcode/) 错误，他们10天 都不处理，就关闭了 [issue](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/57)
而且他们还删除了我在题解下面的评论
刚刚我在 https://leetcode-cn.com/circle/discuss/kSYiVL/ 下面评论反馈这个题解有问题，但是评论又被他们删除了
到现在这篇辣眼睛的题解还挂着“官方”的标签
