### ISSUE TITLE
Problem 146 - LRU - newly added test cases TLE

### ISSUE THREAD

**Issue by ArshadAQ** [LeetCode-Feedback/LeetCode-Feedback#9403]
#### Your LeetCode username
ArshadAQ

#### Category of the bug
- [ ] Test Cases 

#### Description of the bug
It seems like newly added test cases result in TLE. I've attempted this problem before and it passed. Re-attempting it now again, the same code gets TLE for the 21st test case.

Multiple people have posted this in the discussion forum:
Examples:
https://leetcode.com/problems/lru-cache/solutions/1427545/newly-added-test-case-will-tle/
https://leetcode.com/problems/lru-cache/solutions/2545949/why-tle/

#### Code you used for Submit/Run operation

```
class LRUCache {
    struct Node {
        int key;
        int value;
    };

    int capacity;
    list<Node> LRU;
    unordered_map<int, list<Node>::iterator> cache;

    void evictLRU() {
        int keyToEvict = begin(LRU) -> key;
        cache.erase(keyToEvict);
        LRU.erase(begin(LRU));
    }
public:
    LRUCache(int capacity) {
        this -> capacity = capacity;
    }
    
    int get(int key) {
        if(cache.find(key) == cache.end()) {
            return -1;
        }
        list<Node>::iterator currPos = cache[key];
        LRU.splice(end(LRU), LRU, currPos, next(currPos));
        return currPos -> value;
    }
    
    void put(int key, int value) {
        if(cache.find(key) != cache.end()) {
            list<Node>::iterator currPos = cache[key];
            currPos -> value = value;
            LRU.splice(end(LRU), LRU, currPos, next(currPos));
        } else {
            LRU.push_back({key, value});
        }
        cache[key] = prev(end(LRU));
        if(cache.size() > capacity) {
            evictLRU();
        }
    }
};

/**
 * Your LRUCache object will be instantiated and called as such:
 * LRUCache* obj = new LRUCache(capacity);
 * int param_1 = obj->get(key);
 * obj->put(key,value);
 */
```
Link to submission: https://leetcode.com/submissions/detail/817914145/

#### Language used for code
C++

#### Expected behavior
All test cases should pass as this is the most efficient solution possible

**Comment by Stereolab42** [comment]
Agree, the problem is currently broken for C++. Even the top solutions from Discuss are all TLE now.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by jacklanda** [comment]
I always fail on the 21st test case too. It seems a really issues occurred recently even for the best solution in C++.

**Comment by yumkam** [comment]
I managed to write [something that passes current tests](https://leetcode.com/submissions/detail/830808535/), but only if it *leaks* memory. Once I uncomment `delete [] mem`, it [TLE's again](https://leetcode.com/submissions/detail/830809041/).

(But is it a change in tests, or change in environment on judge? Number of tests is same as with previously-accepted-but-currently-TLE implementation - 22)

**Comment by ArshadAQ** [comment]
This seems to have been resolved!
