### ISSUE TITLE
716. Max Stack Golang Compile error

### ISSUE THREAD

**Issue by luigitni** [LeetCode-Feedback/LeetCode-Feedback#9404]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
Golang code does not compile. 
The "console" reports the following compilation error, with lines outside of my code:

Line 75: Char 19: undefined: Deserializer (solution.go)
Line 80: Char 36: undefined: Deserializer (solution.go)
Line 85: Char 34: undefined: Serializer (solution.go)
Line 89: Char 34: undefined: Serializer (solution.go)
Line 93: Char 34: undefined: Serializer (solution.go)
Line 97: Char 34: undefined: Serializer (solution.go)
Line 164: Char 25: undefined: Deserializer (solution.go)

#### Code you used for Submit/Run operation
```
type ListNode struct {
    Val int
    Next *ListNode
    Prev *ListNode
}

type MaxStack struct {
    List *ListNode
    Tree *redblacktree.Tree
}


func Constructor() MaxStack {
    return MaxStack{
        List: &ListNode{},
        Tree: redblacktree.NewWithIntComparator(),
    }
}


func (this *MaxStack) Push(x int)  {
    node := &ListNode{Val: x}
    node.Prev = this.List
    this.List.Next = node
    
    this.Tree.Put(x, node)
}


func (this *MaxStack) Pop() int {
    v := this.List.Val
    this.List = this.List.Prev
    
    this.Tree.Remove(v)
    return v
}


func (this *MaxStack) Top() int {
    return this.List.Val
}


func (this *MaxStack) PeekMax() int {
    listNode := this.Tree.Right().Value.(*ListNode)
    return listNode.Val
    
}


func (this *MaxStack) PopMax() int {
    max := this.Tree.Right()
    this.Tree.Remove(max.Key)
    
    maxNode := max.Value.(*ListNode)
    // remove the node from the linked list
    next := maxNode.Next
    prev := maxNode.Prev
    maxNode.Prev.Next = next
    maxNode.Next.Prev = prev
    
    return maxNode.Val
}


/**
 * Your MaxStack object will be instantiated and called as such:
 * obj := Constructor();
 * obj.Push(x);
 * param_2 := obj.Pop();
 * param_3 := obj.Top();
 * param_4 := obj.PeekMax();
 * param_5 := obj.PopMax();
 */
```

#### Language used for code
Golang

#### Expected behavior
Expected the solution to be compiled and run

#### Screenshots
![image](https://user-images.githubusercontent.com/3179290/194718821-c74c59ed-21a2-493f-b170-1053d13f8b1d.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The issue is because you trying to override the ListNode class of Leetcode.
Please change the ListNode to another name. We appreciate your support!

**Comment by luigitni** [comment]
Thanks, I have renamed the struct and I can confirm it now compiles.

It'd be good to have a less generic error message when this happens, so that it doesn't look like an application error and saves both of us time :)

Many thanks for your help, much appreciated 👍
