### ISSUE TITLE
Wrong Test Case - 1671. Minimum Number of Removals to Make Mountain Array

### ISSUE THREAD

**Issue by ek08** [LeetCode-Feedback/LeetCode-Feedback#9405]
#### Your LeetCode username
ek08 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumMountainRemovals(int[] nums) {
        int n = nums.length;
        int[] lds = new int[n];
        int[] ldsRev = new int[n];
        int max = 0;
        
        // lds[0] = 1;
        for (int i = 0; i < n; i++) {
            lds[i] = 1;
            for (int j = i - 1; j >= 0; j--) {
                if (nums[j] < nums[i]) {
                    lds[i] = Math.max(lds[i], 1 + lds[j]);
                }
            }
        }
        // ldsRev[n - 1] = 1;
        for (int i = n - 1; i >= 0; i--) {
            ldsRev[i] = 1;
            for (int j = i + 1; j < n; j++) {
                if (nums[i] > nums[j]) {
                    ldsRev[i] = Math.max(ldsRev[i], 1 + ldsRev[j]);
                }
            }
        }
        for (int i = 0; i < n; i++) {
            max = Math.max(max, lds[i] + ldsRev[i] - 1);
        }
        return n - max;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Input - [9,8,1,7,6,5,4,3,2,1]
Output - 1
Expected - 2

According to my understanding, the correct output is 1 cuz if we just remove the 1 at index 2 the array becomes a mountain array.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
