### ISSUE TITLE
Missing Test Case - 653. Two Sum IV - Input is a BST

### ISSUE THREAD

**Issue by ACR1209** [LeetCode-Feedback/LeetCode-Feedback#9407]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The testcase is accepted when I press "Run Code" but it shows wrong answer when submitted.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def findTarget(self, node: Optional[TreeNode], k: int, comp = []) -> bool:
        if not node:
            return False

        if k - node.val in comp:
            return True

        comp.append(node.val)

        return self.findTarget(node.left, k, comp) or self.findTarget(node.right, k, comp)
```

#### Expected behavior

I expected my code to pass this testcase, but as I previously stated it didn't.

#### Screenshots

![image](https://user-images.githubusercontent.com/78624635/194733397-5230cf68-18f8-4ff8-9922-9c1c0903a755.png)

#### Additional context

- The testcase is:
```
[1]
2
```

- Doing the exact same code but with another function inside is accepted as a solution.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
