### ISSUE TITLE
870题测试用例的最优解不止一种

### ISSUE THREAD

**Issue by ranger700** [LeetCode-Feedback/LeetCode-Feedback#9409]
![image](https://user-images.githubusercontent.com/57863725/194743967-3e88b561-22b7-48a5-bdc0-c3caa7dc9ea5.png)
此种解法胜7平2输1
与官方解法胜8输2的优势相同
因为本题还有另一种贪心策略
![image](https://user-images.githubusercontent.com/57863725/194744068-60dc4036-eacc-4263-b92f-cf2e13272f1c.png)

**Comment by feiceh** [comment]
思路确实很棒，但是不适合这道题，题面中说到：
nums1 相对于 nums2 的优势可以用满足 nums1[i] > nums2[i] 的索引 i 的数目来描述。
所以是计算最多能获胜的数量，而非 获胜 - 失败 的数量
