### ISSUE TITLE
Constraints Missing in 669. Trim a Binary Search Tree

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#941]
#### Your LeetCode username

**Mkay6122**

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Constraints Missing in 669. Trim a Binary Search Tree

#### Code you used for Submit/Run operation

```
// Trim a Binary Search Tree
class Solution {
public:
   TreeNode* trimBST(TreeNode* root, int L, int R) {
        
    if(!root) return NULL;
    if(root->val<L){
        return trimBST(root->right, L, R);
        
    }
    else if(root->val>R){
        return trimBST(root->left,L,R);
    }
    else{
        root->left=trimBST(root->left, L, R);
        root->right= trimBST(root->right, L, R);
        return root;
    }
    }
};
```

#### Language used for code

C++

**Comment by lc-kay** [comment]
Hi @Mohitkumar6122 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Mohitkumar6122 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
