### ISSUE TITLE
Missing Test Case - 435. Non-overlapping Intervals

### ISSUE THREAD

**Issue by basithrehman** [LeetCode-Feedback/LeetCode-Feedback#9410]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
[[1,2],[1,3]]
The answer is accepted even though intervals are overlapping

#### Code you used for Submit/Run operation

```
// Greedy Approach

 intervals.sort((a,b) => a[1] - b[1])
    let count = 0;
    let prev = intervals[0];
    for(let i=1; i<intervals.length; i++){
        if(intervals[i][0] >= prev[1]) prev = intervals[i]
        else count++
    }
    return count

```

#### Language used for code
Javascript

#### Expected behavior
The test case shall fail

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
