### ISSUE TITLE
733. Flood Fill (Submitiing the solution breaks a case, but running it normally doesnt)

### ISSUE THREAD

**Issue by pruthvip** [LeetCode-Feedback/LeetCode-Feedback#9411]
#### Your LeetCode username
pruthvi
https://leetcode.com/pruthvi/

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

While submitting the the question floodfill: https://leetcode.com/problems/flood-fill/
i get the following error, that a test case is failing.

 
<img width="1654" alt="Screenshot 2022-10-09 at 7 38 56 PM" src="https://user-images.githubusercontent.com/1709317/194761444-8dce01e5-7805-41c9-9dfc-809cd036de20.png">

But while running the same testcase in the testing phase, it gives the correct answer.
<img width="884" alt="Screenshot 2022-10-09 at 7 40 07 PM" src="https://user-images.githubusercontent.com/1709317/194761507-71dbb49b-77c9-4097-bf76-2aa1dc3db7de.png">
<img width="860" alt="Screenshot 2022-10-09 at 7 40 22 PM" src="https://user-images.githubusercontent.com/1709317/194761519-bd129c80-4e35-41ae-8e87-ddf7fc888ca3.png">

#### Code you used for Submit/Run operation

```
/**
 * @param {number[][]} image
 * @param {number} sr
 * @param {number} sc
 * @param {number} color
 * @return {number[][]}
 */

const generateArray = (image, sr, sc, startColor) => {
    const arr = [
        [sr + 1, sc], // next roe
        [sr-1, sc], // rpev row
        [sr, sc -1], // prev col
        [sr, sc +1]  // next col
    ];
    
    const ans = arr.filter(c => {
        if (!image[c[0]]) return false;
        if (image[c[0]][c[1]] !== startColor) return false;
        return true;
    })
    
    return ans;
}

const hasVisited = new Set();

const getKey = x => y => `${x}_${y}`;

const fill = (image, i, j, startColor, color) => {
    const stack = [[i, j]];
    
    while (stack.length) {
        const [i, j] = stack.pop();
        image[i][j] = color;
        hasVisited.add(getKey(i)(j));
        
        for (const n of generateArray(image, i, j, startColor)) {
            if (!hasVisited.has(getKey(n[0])(n[1]))) {
                stack.push(n);
            }
        }
    }
};


var floodFill = function(image, sr, sc, color) {
    const sColor = image[sr][sc];
    fill(image, sr, sc, sColor, color)
    return image;
};


```
Submission link: https://leetcode.com/submissions/detail/818667424/

Test case

```
[[0,0,0],[0,0,0]]
1
0
2
```

#### Language used for code

Javascript

#### Expected behavior

While submitting the particular testcase should pass too.

**Comment by pruthvip** [comment]
Update on the above issue:-
So while debugging I saw that, the issue is there because of the global variable set 
 which i created 

```
const hasVisited = new Set();

```

When i moved the Set inside the function ```fill```, it started working

Full code

```
/**
 * @param {number[][]} image
 * @param {number} sr
 * @param {number} sc
 * @param {number} color
 * @return {number[][]}
 */

const generateArray = (image, sr, sc, startColor) => {
    const arr = [
        [sr + 1, sc], // next roe
        [sr-1, sc], // rpev row
        [sr, sc -1], // prev col
        [sr, sc +1]  // next col
    ];
    
    const ans = arr.filter(c => {
        if (!image[c[0]]) return false;
        if (image[c[0]][c[1]] !== startColor) return false;
        return true;
    })
    
    return ans;
}


const getKey = x => y => `${x}_${y}`;


const fill = (image, i, j, startColor, color) => {
    const hasVisited = new Set();
    const stack = [[i, j]];
    
    while (stack.length) {
        const [i, j] = stack.pop();
        image[i][j] = color;
        hasVisited.add(getKey(i)(j));
        
        for (const n of generateArray(image, i, j, startColor)) {
            if (!hasVisited.has(getKey(n[0])(n[1]))) {
                stack.push(n);
            }
        }
    }
};


var floodFill = function(image, sr, sc, color) {
    const sColor = image[sr][sc];
    fill(image, sr, sc, sColor, color)
    return image;
};


```

So there is something wrong happening when a global Set is bring created.
Kindly have a look into it.

Successful submission: https://leetcode.com/submissions/detail/818675651/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by pruthvip** [comment]
Hi @LC-Pam I read one of the docs,

https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

This is happening because of this only!! I think i should create global variables, and thats the expecation while solving leetcode problems. 

Closing based on the link. If any more info is there, do share that!!
