### ISSUE TITLE
Missing Test Case - 1568. Minimum Number of Days to Disconnect Island

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#9412]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/minimum-number-of-days-to-disconnect-island/

Question heading says:
1568. `Minimum Number of Days to Disconnect Island`
Question description says:
Return the `minimum number of days to disconnect the grid.`

Please review both Question heading & Question description

#### Code you used for Submit/Run operation

```
```

#### Expected behavior
Question heading & Question description must say same.

Wasted several hours on this.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We decided not to change.  We appreciate your support!
