### ISSUE TITLE
412. Fizz Buzz #Innovative Solution @miloas @Ashish-Bansal @roll-no-1 @storm-sunshine @alphasingh 

### ISSUE THREAD

**Issue by Shreyansh252001** [LeetCode-Feedback/LeetCode-Feedback#9413]
#### Your Leetcode username
 shreyansh252001

#### Category of the bug
- [ ] Question : 
       https://leetcode.com/problems/fizz-buzz/
- [ ] Solution
      This solution is not valid for the case where many number will be given to concatenate with corresponding string.
      The basic idea is table of 3  and table of 5 
      which is 3,3+3=6,3+3+3=9,12,15 etc...
      and same in case of 5, 10, 15,20 etc..
    
      so here c3 denotes this  only count of multiples of 3 and c5 denotes count of multiples of 5 
     suppose we take n=15
           c3 c5  result
     1    1    1   "1"
     2    2    2    "2"
     3    3    3    "fizz" c3==3 so we need to include "fizz" here but not "buzz" as 5 is not there in c5 AND MAKE SURE TO SET c3=0
     4     1   4    "4"
     5    2    5   "buzz" c5==5  so we need to include "buzz" here but not "fizz" as 3 is not there in c3 AND MAKE SURE TO SET c5=0
     6    3    1    "fizz"   c3=0
     7    1    2     "7"
     8    2    3     "8"
     9    3    4      "fizz" c3=0
   10    1    5     "buzz" c5=0
   11    2   1      "11"
   12    3    2     "fizz"  c3=0
   13    1    3     "13"
   14    2    4      "14"
   15    3    5      "fizzbuzz" first it will add "fizz" in string then it will add "buzz" in next condition making it "fizzbuzz" and AT LAST 
                           MAKING BOTH c3=0,c5=0
- [ ] Language : C++
- [ ] Missing Test Cases 

##There is no bug I am just tring to submit new and innovative solution for inclusion in solution tab under approach-4## Description of the bug

#### Code you used for Submit/Run operation

```
 vector<string> fizzBuzz(int n) 
    {
        string s;
        vector<string> v;
        int c3=0,c5=0;
        
        for(int i=1;i<=n;i++)
        {
            s="";
             c3++;
            c5++;
            if(c3==3)
            {   s+="Fizz";c3=0;}
            if(c5==5)
            {   s+="Buzz";c5=0;}
            if(s=="")
                s=to_string(i);
           
            v.push_back(s);
        }
        
        return v;
    }
```

#### Language used for code
C++

#### Screenshots
![image](https://user-images.githubusercontent.com/51321665/194772216-4edc9dd3-ed90-4142-b549-1dd873f79fbf.png)

#### Additional context
Time complexity = O(N)
Space Complexity = O(N) due to new string vector required for return from function

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Our solutions are much better than that. Though we may consider adding C++ solution in the future.  We appreciate your support!
