### ISSUE TITLE
Wrong TestCase 13 - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by himanshu181749** [LeetCode-Feedback/LeetCode-Feedback#9414]
#### Category of the bug
- [ ] Question
- [ ] wrong Test Cases 

#### Code you used for Submit/Run operation

```
// [Find the Duplicate Number]
class Solution {
public:
    int findDuplicate(vector<int>& nums) {
        int n=nums.size();
        int sum=accumulate(nums.begin(), nums.end(), 0);
        int total=(n*(n-1))/2;
        
        return abs(total-sum);
    }
};
```

#### Screenshots

<img width="899" alt="image" src="https://user-images.githubusercontent.com/75875283/194773217-803e52b6-22d4-467f-9923-a34b4ca4e889.png">

<img width="388" alt="image" src="https://user-images.githubusercontent.com/75875283/194773233-92fbd0ac-a5b1-4b2e-92ce-8286820572fd.png">

#### Additional context

there is more than one repeated number.

**Comment by stormsunshine** [comment]
The only repeated number is 2 and it is repeated 5 times. Why do you think this test case is wrong?
