### ISSUE TITLE
Missing Test Case - 653. Two Sum IV - Input is a BST

### ISSUE THREAD

**Issue by Tapesh-Vashisth** [LeetCode-Feedback/LeetCode-Feedback#9415]
![issue](https://user-images.githubusercontent.com/95041328/194792267-96c15c2d-4d69-4b17-8bac-a65516c26fc2.png)
![issue2](https://user-images.githubusercontent.com/95041328/194792362-33ead12c-d44e-4911-b8dd-78f1f8f5348a.png)

#### Your LeetCode username
fur_sky

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
lack of a particular kind of test case makes the incorrect solution get accepted.

#### Code you used for Submit/Run operation
```
typedef TreeNode node;

class Solution {
public:
    vector <int> inorder;
    
    void constructInorder(node * root){
        if (root){
            constructInorder(root->left);
            inorder.push_back(root->val);
            constructInorder(root->right);
        }
    }
    
    bool checker(vector <int> & v, int target){
        int low = 0;
        int high = v.size() - 1;
        while (low < high){
            if (v[low] + v[high] > target){
                high--;
            }else if(v[low] + v[high] < target){
                low++;
            }else{
                return true;
            }
        }
        
        return false;
    }
    
    bool findTarget(TreeNode* root, int k) {
        if (root){
            if (k < root->val && k > 0){
                return findTarget(root->left, k);
            }else{
                inorder.clear();
                constructInorder(root);
                return checker(inorder, k);
            }
        }else{
            return false;
        }
    }
};
```

#### Language used for code
C++

#### Expected behavior
This solution should not work for the test case ([5, -4, 8], 4) but despite it, it gets accepted on submitting.

**Comment by stormsunshine** [comment]
Why do you provide a test case where the input is NOT a BST?

**Comment by Tapesh-Vashisth** [comment]
sorry for the wrong test case, I have corrected it, now, it's a valid BST
