### ISSUE TITLE
Missing Test Case - 1579. Remove Max Number of Edges to Keep Graph Fully Traversable

### ISSUE THREAD

**Issue by rahulkovachi** [LeetCode-Feedback/LeetCode-Feedback#9417]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ☞] Missing Test Cases

**Comment by rahulkovachi** [comment]
Test case : n=3 , edges [[3,1,2],[1,2,3],[1,1,3]] .

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
