### ISSUE TITLE
Display issue of the Solutions to Problem 347. Top K Frequent Elements on Chrome Windows 10

### ISSUE THREAD

**Issue by JiangongChen** [LeetCode-Feedback/LeetCode-Feedback#9418]
When I check the official solutions to problem 347 in [https://leetcode.com/problems/top-k-frequent-elements/solutions/646157/top-k-frequent-elements/](url), the second half of the solution shows abnormal texts in red color. It seems there are some format issues of the solution. 

I have captured a screenshot as in [https://ibb.co/DbY6gws](url).

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. The content should be fine right now.  We appreciate your support!
