### ISSUE TITLE
Missing Test Case - 49. Group Anagrams

### ISSUE THREAD

**Issue by shashankpandey1102** [LeetCode-Feedback/LeetCode-Feedback#9420]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Given an array of strings strs, group the anagrams together. You can return the answer in any order.

An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.

Input: strs = ["eat","tea","tan","ate","nat","bat"]
Output: [["bat"],["nat","tan"],["ate","eat","tea"]] 

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<String>> groupAnagrams(String[] strs) {
        HashMap<String, List<String>> map = new HashMap<String, List<String>>();
        List<List<String>> res = new ArrayList<>();
        
        for(String words : strs){
            char[] wordArr = words.toCharArray();
            Arrays.sort(wordArr);
            String newString = new String(wordArr);
            
            if(map.containsKey(newString)){
                map.get(newString).add(words);
            }
            else{
                List<String> list = new ArrayList<String>();
                list.add(words);
                map.put(newString, list);
            }
        }
        
        for(List<String> value : map.values()){
            res.add(value);
        }
        
        return res;
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
