### ISSUE TITLE
Missing Test Case - 507. Perfect Number

### ISSUE THREAD

**Issue by Aman1131145** [LeetCode-Feedback/LeetCode-Feedback#9421]
#### Your LeetCode username
Aman Mishra
mishraaman113114

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Valid answers are very few that we can just use the testcases. And return false at every other number.

#### Code you used for Submit/Run operation

```
// Perfect Number
class Solution {
    public boolean checkPerfectNumber(int num) {
        return ((num==6)||(num==28)||(num==496)||(num==8128)||(num==33550336));
    }
}
```

#### Language used for code
Java

#### Expected behavior

Increase the number of testcases so that this issue will be resolved.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
