### ISSUE TITLE
745. Prefix and Suffix Search - Strange behavior leads to TLE

### ISSUE THREAD

**Issue by Zamaletdinov** [LeetCode-Feedback/LeetCode-Feedback#9422]
#### Your LeetCode username
zamaletdinov

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The same solution is either accepted or ends in TLE depending on how it was composed, but there are no algorithmic differences

##### TLE version:
```
class Node:
  def __init__(self) -> None:
    self.next: Dict[str, Node] = collections.defaultdict(Node)
    self.index = -1


class WordFilter:

  def insert(self, root: Node, word: str, index: int):
    current = root

    for char in word:
      current = current.next[char]
      current.index = index

  def __init__(self, words: List[str]):
    self.root = Node()

    for index, word in enumerate(words):
      for i in range(len(word)):
        combo = f'{word[i:]}#{word}'
        self.insert(self.root, combo, index)

  def f(self, pref: str, suff: str) -> int:
    node = self.root
    combo = f'{suff}#{pref}'

    for char in combo:
      if not char in node.next:
        return -1

      node = node.next[char]

    return node.index
```

##### Accepted version:
```
def Node(): return collections.defaultdict(Node)


WEIGHT = 'WEIGHT'


class WordFilter:

  def insert(self, root: Node, word: str, index: int):
    current = root

    for char in word:
      current = current[char]
      current[WEIGHT] = index

  def __init__(self, words: List[str]):
    self.root = Node()

    for index, word in enumerate(words):
      for i in range(len(word)):
        combo = f'{word[i:]}#{word}'
        self.insert(self.root, combo, index)

  def f(self, pref: str, suff: str) -> int:
    node = self.root
    combo = f'{suff}#{pref}'

    for char in combo:
      if not char in node:
        return -1

      node = node[char]

    return node[WEIGHT]
```

#### Language used for code
Python3

#### Expected behavior
Both versions should be accepted

#### Screenshots
Attaching it to show the actual difference
![image](https://user-images.githubusercontent.com/8142668/194814921-f6815bba-b0cc-4f61-a317-0bab95ce57c7.png)

#### Additional context
Submissions of the solutions:
![image](https://user-images.githubusercontent.com/8142668/194815604-54e0222e-4dcc-47cb-bc49-8bed3ea552bb.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The constraints are not high and the number of test cases is not large.
Both have the same complexity but one of them has a very big factor and that's why it was TLE. We appreciate your support!
