### ISSUE TITLE
201. Bitwise AND of Numbers Range

### ISSUE THREAD

**Issue by karthi-7-a** [LeetCode-Feedback/LeetCode-Feedback#9423]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [.] Missing Test Cases 

#### Description of the bug

All test cases passed but showing TLE error.

#### Code you used for Submit/Run operation

```
 int rangeBitwiseAnd(int left, int right) {
     //   if(left==right) return 0;
        long x=left,s=(long)left+1;
        for(long i=s;i<=right;i++){
            if((x&i)==0) return 0;
            x&=i;
        }
        return x;
    }


```

#### Language used for code
C++ 

#### Screenshots

![err](https://user-images.githubusercontent.com/61533714/194818075-674e48c0-8c03-404c-95f6-7ccec5365806.png)

**Comment by LC-Pam** [comment]
Thank you for contacting LeetCode's Support Team.

Your submission is resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

Please note that the test case you see on the "details" page shows which test case the program stops running at when the time limit has exceeded; it's not a test case that causes your program to exceed the time limit. 

I'd recommend checking out accepted submissions from the discuss tab of the problem page or posting your code there to get support from other users. Unfortunately, we do not disclose the time limit as we want our users to debug and improve their code to get it accepted. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
