### ISSUE TITLE
Missing Test Case - 1328. Break a Palindrome

### ISSUE THREAD

**Issue by thakreyn** [LeetCode-Feedback/LeetCode-Feedback#9424]
#### Your LeetCode username

thakreyn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test cases where the length of the string is odd and the middle element is not 'a' and all other characters are 'a'  are not considered in the existing test cases.

#### Code you used for Submit/Run operation

```
// Break a palindrome
class Solution {
public:
    string breakPalindrome(string s) {
        if(s.size()==1) return "";
        if(s.size()==3 && s[0]=='a'&& s[2]=='a'){
            s[2]='b';
            return s;
        }
        if(s =="aabaa") return "aabab";

       bool one = false;
        for (auto &i:s){
            if(i!='a'){
                i='a';
                one=true;
                break;
            }
        }
        if(!one){
            s[s.size()-1]='b';
        }
        return s;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Example: string => aaadaaa
According to the code submitted above, the answer will be : aaaaaaa (which is a palindrome).
But the actual answer should be : aaadaab.
So although the code is submitting succesfully it fails for the above testcase.

#### Screenshots

<img width="499" alt="image" src="https://user-images.githubusercontent.com/82403674/194825978-33021995-eee4-4cbf-9f48-e5ca49296f0f.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
