### ISSUE TITLE
724. Find Pivot Index. Hint #1 isn't correct

### ISSUE THREAD

**Issue by ryb1n** [LeetCode-Feedback/LeetCode-Feedback#9425]
#### Your LeetCode username
fuji_gg

#### Category of the bug
- [x] Question

#### Description of the bug
Hint (We can precompute prefix sums P[i] = nums[0] + nums[1] + ... + nums[i-1]. Then for each index, the left sum is P[i], and the right sum is P[P.length - 1] - P[i] - nums[i].) - isn't correct. As the right sum above isn't contain nums[P.length - 1]. Correct right sum statement is P[P.length - 1] + nums[P.length - 1] - P[i] - nums[i].

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int pivotIndex(vector<int>& nums) {
        
        vector<int> sums(nums.size());
        
        for (int i = 1; i < nums.size(); ++i)
            sums[i] += (sums[i - 1] + nums[i - 1]);
        
        for (int i = 0; i < nums.size(); ++i)
        {
            int l = sums[i];
            int r = sums.back() + nums.back() - sums[i] - nums[i];
            
            if (l == r)
                return i;
        }
        
        return -1;
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The hints were correct. 
Added new hints. We appreciate your support!
