### ISSUE TITLE
缺少测试用例 1085. Sum of Digits

### ISSUE THREAD

**Issue by longluo** [LeetCode-Feedback/LeetCode-Feedback#9429]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
羽路阳光

**Bug 类型**
- [ ] 题目: 1085
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例 

**描述**
1085. 最小元素各数位之和 缺少测试用例： [100]

**你使用的语言**
Java

**你提交或者运行的代码**
```
// Two Sum
class Solution {
    public int sumOfDigits(int[] nums) {
        int min = Integer.MAX_VALUE;
        for (int x : nums) {
            min = Math.min(min, x);
        }

        int sum = min / 10 + min % 10;
        return sum % 2 == 0 ? 1 : 0;
    }
}
```

**期望行为**
在运行 [100] 这个用例应该会输出0，但是上述代码运行返回1，但却AC了！
因为缺少 [100] 用例！

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收。
