### ISSUE TITLE
Incorrect Solution In "Image Overlap" Problem

### ISSUE THREAD

**Issue by d-a-mby** [LeetCode-Feedback/LeetCode-Feedback#943]
#### Your LeetCode username
DebbieAlter

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Wrong solution in problem "Image Overlap" : https://leetcode.com/problems/image-overlap/
The 1st solution in the solution section does not pass two test cases I ran

#### Code you used for Submit/Run operation

(this is the solution I ran, which passes your given testcases but does not pass the ones that also don't pass in your solution)

```
def shift(x, y, im1, im2, dim):
    sum_ = 0
    for row1, row2 in enumerate(range(y, dim)):
        for col1, col2 in enumerate(range(x, dim)):
            
            sum_ += 1 if im1[row1][col1] == 1 and im1[row1][col1] == im2[row2][col2] else 0
                
    return sum_


class Solution:
    def largestOverlap(self, A: List[List[int]], B: List[List[int]]) -> int:

        max_overlap = 0
      
        for x in range(len(A)):
            for y in range(len(A)):
                max_overlap = max(max_overlap, shift(x, y, A, B, len(A)))
                max_overlap = max(max_overlap, shift(x, y, B, A, len(A)))

                
        return max_overlap
```

#### Language used for code
python

#### Expected behavior
I ran the following two test cases (with your 1st given solution):
[[0,0,0,0,1],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]]
[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[1,0,0,0,0]]

your solution's output was zero instead of 1

and this one:

[[0,0,1],[0,0,0],[0,0,0]]
[[0,0,0],[0,0,0],[1,0,0]]

your solution's output was also here 0 instead of 1

#### Additional context
I happened to run these two test cases but probably many more don't pass

![‏‏צילום מסך (514)](https://user-images.githubusercontent.com/56960766/92332227-dd74f380-f084-11ea-915c-e5b432d783ac.png)

![‏‏צילום מסך (516)](https://user-images.githubusercontent.com/56960766/92332228-dfd74d80-f084-11ea-827f-eb70037431b8.png)

Thank You!!
still ❤ LeetCode!!!

**Comment by lc-kay** [comment]
Hi @d-a-mby 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @d-a-mby ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
