### ISSUE TITLE
Problem: 660 Remove 9 python solution doesn't work

### ISSUE THREAD

**Issue by JakobJK** [LeetCode-Feedback/LeetCode-Feedback#9430]
#### Your LeetCode username
[_--_--_](https://leetcode.com/_--_--_/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The provided python solution for [660. Remove 9](https://leetcode.com/problems/remove-9/) does not pass. 
The following solution:
```py
class Solution(object):
    def newInteger(self, n):
        ans = ''
        while n:
            ans = str(n%9) + ans
            n /= 9
        return int(ans)
```
Fails with this error:
```
ValueError: invalid literal for int() with base 10: '5e-3243e-3232.6e-3222.367e-3212.132e-3201.91865e-3191.72681e-3181.5541284e-3171.39871546e-3161.258843915e-3151.1329595237e-3141.0196635713e-3139.17697214195e-3138.25927492774e-3127.433347434967e-3116
    return int(ans)
Line 7 in newInteger (Solution.py)
    ret = Solution().newInteger(param_1)
Line 26 in _driver (Solution.py)
    _driver()
Line 37 in <module> (Solution.py)
```

#### Code you used for Submit/Run operation

```py
# 660. Remove 9
class Solution(object):
    def newInteger(self, n):
        ans = ''
        while n:
            ans = str(n%9) + ans
            n /= 9
        return int(ans)
```

#### Language used for code
Python

#### Expected behavior
The expected behavior would be the provided python solution to work.

#### Additional context
I wonder if this is related to this controversial python update: [int-str-conversions-broken](https://discuss.python.org/t/int-str-conversions-broken-in-latest-python-bugfix-releases/18889)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We consider it invalid. The error occurred because you submitted our Python solution using Python3. Though we may upgrade our code solution to Python3 later . We appreciate your support!
