### ISSUE TITLE
Problem 10 Unclear Instructions/Incorrect Test Case?

### ISSUE THREAD

**Issue by ayy051815** [LeetCode-Feedback/LeetCode-Feedback#9432]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There's a test case for s = "aab" and p = "c*a*b" with an expected output of true. But for an input of  s = "aab" and p = "c*a*b", the output shouldn't be true because there's nothing in s that matches the "c" in p. Perhaps either the test case is incorrect or the instructions aren't clear enough to explain why the test case should work the way it does. Any clarification would be much appreciated! Thanks!

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The * can match 0 c's and remove them. That was stated in the statement. We appreciate your support!
