### ISSUE TITLE
416. Partition Equal Subset Sum solution 3 text-broken/unreadable

### ISSUE THREAD

**Issue by daseyun** [LeetCode-Feedback/LeetCode-Feedback#9433]
#### Your LeetCode username
daseyun

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution 3 of this problem is unreadable. 

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

Solution code/write up displays properly.

#### Screenshots

![image](https://user-images.githubusercontent.com/48741672/195021758-c1d1c3b3-e0a1-48fd-aa66-7e6d452aa88c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
