### ISSUE TITLE
error in test case

### ISSUE THREAD

**Issue by Harshittotuka** [LeetCode-Feedback/LeetCode-Feedback#9435]
#### Your LeetCode username
harshittotuka

#### Category of the bug

- [x] Missing Test Cases

#### Description of the bug

the test case [20,100,10,12,5,13] is excepted by leet code as true , but using the logic there is no triplet in the given case so its correct output should be false

#### Code you used for Submit/Run operation

```
// Increasing Triplet Subsequence
class Solution {
    public boolean increasingTriplet(int[] nums) {
        for(int i=0;i<(nums.length)/2+1;i++){
            if(nums[i]<nums[i+1]){
                if(nums[i+1]<nums[i+2]){
                    return true;
                }
            }
        }
    return false;
    }
}
```

#### Language used for code
java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
