### ISSUE TITLE
Leetcode 75 Study Plan - Level 2 Summary

### ISSUE THREAD

**Issue by vigneshshiv** [LeetCode-Feedback/LeetCode-Feedback#9436]
#### Your LeetCode username
vigneshshiv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] None of the above (It's on Leetcode Study Plan)

#### Description of the bug
Leetcode 75 Level 2 Study plan yet to problem solved summary section is not correct, Last day session and only one medium problem is yet to attempt but the count shown easy vs medium is not correct. 

Refer the screenshot for details...

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/10242660/195044505-9510679f-817b-46d0-bc79-b69d4da0b757.png)

**After solving the problem**

![image](https://user-images.githubusercontent.com/10242660/195053572-103002ea-c5d8-4cf1-aa63-90710bf66d51.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, please feel free to contact our zendesk customer support to solve this issue!
Github is for content-related issues, thank you so much!
