### ISSUE TITLE
Bug report - wrong testcase

### ISSUE THREAD

**Issue by ranasandeep321** [LeetCode-Feedback/LeetCode-Feedback#9438]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by ranasandeep321** [comment]
Username ->    sandeep_003
![av](https://user-images.githubusercontent.com/84094428/195085718-8d22a9f1-3ec9-440e-9c43-feedd728a99b.jpg)


// problem 787-  Cheapest Flights Within K Stops
 
Description - 
 for   problem 787-  Cheapest Flights Within K Stops, according to my code (Which is correct showing TLE )for a specific testcase  answer should be different but it is showing different which is a wrong answer.

TESTCASE-

4
[[0,1,1],[0,2,5],[1,2,1],[2,3,1]]
0
3
1



CODE-->
`class Solution {
public:
    int findCheapestPrice(int n, vector<vector<int>>& v, int src, int dest, int k) {
        vector<vector<pair<int,int>>> g(n);
        
        for(int i=0;i<v.size();i++){
                g[v[i][0]].push_back({v[i][1],v[i][2]});
            
        }
        priority_queue<vector<int>,vector<vector<int>>,greater<vector<int>>> q;
        k++;
        vector<int> dst(n,INT_MAX);
        dst[src]=0;
        
        q.push({0,src,k});
        while(!q.empty()){
            
            auto v=q.top();
            q.pop();
            int node=v[1];
            int ndst=v[0];
            int k= v[2];
            if(k==0) continue;
            
            for(auto j: g[node]){
                
              //  if(ndst+j.second<dst[j.first]){
                    dst[j.first]=ndst+j.second;
                    q.push({dst[j.first],j.first,--k});
                //}
                
            }
            
            
        }
        
        return dst[dest]==INT_MAX?-1:dst[dest];
        
    }
};`

Language - C++;

Expexted behaviour -  Output should be 6 but it is showing -1;

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ranasandeep321** [comment]
https://leetcode.com/submissions/detail/820378100/
