### ISSUE TITLE
Solution page not rendering

### ISSUE THREAD

**Issue by haswath3** [LeetCode-Feedback/LeetCode-Feedback#9439]
#### Your LeetCode username
raharsha

#### Category of the bug
- [ ] Question
- [* ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The page https://leetcode.com/problems/partition-equal-subset-sum/solutions/811019/partition-equal-subset-sum/ is not rendering on chrome

#### Screenshots

![leetcodebug](https://user-images.githubusercontent.com/104111827/195111548-b7109876-b68b-4951-a7e3-8cc884029c28.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem and found out this issue caused by the new vision. The developer team will fix it as soon as possible. Please revert back to old vision temporarily if you need to view the content. We appreciate your support!
