### ISSUE TITLE
confusing description 1578. Minimum Deletion Cost to Avoid Repeating Letters

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#944]
#### Your LeetCode username
ddoudle

#### Category of the bug
- [ ] Question

#### Description of the bug

The problem statement: 
Given a string s and an array of integers cost where cost[i] is the cost of deleting the character i in s.

There are two **i**s in this sentence, the first **i** stands for a number while the second **i** stands for a character. 

I spent some time understanding **the character i in s**, I think it should be changed to **ith character in s** or **the character s[i]**

**Comment by lc-kay** [comment]
Hi @caoxingdong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @caoxingdong, 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
