### ISSUE TITLE
For problem:2016. Maximum Difference Between Increasing Elements, if [7,3,5,4,9,19,0] is given as input then getting this error - 'nums' must consist of values from 1 to 1000000000 only

### ISSUE THREAD

**Issue by renukumar07** [LeetCode-Feedback/LeetCode-Feedback#9440]
#### Your LeetCode username
renukumar07

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Not able to run Specific input  

#### Description of the bug
For problem:2016. Maximum Difference Between Increasing Elements, if [7,3,5,4,9,19,0] is given as input then getting this error - 'nums' must consist of values from 1 to 1000000000 only.

#### Code you used for Submit/Run operation

```
// 2016. Maximum Difference Between Increasing Elements - Java
class Solution {
    public int maximumDifference(int[] nums) {
        int min = nums[0];
        int maxDiff = -1;
        for(int i = 1;i<nums.length;i++){
            if(nums[i]<min){
                min = nums[i];
            }else if(nums[i] - min > maxDiff && nums[i] != min){
                maxDiff = nums[i] - min;
            }
        }
        return maxDiff;
    }
}
```

#### Language used for code
Java

#### Expected behavior
For input [7,3,5,4,9,19,0], Expected answer to be 16 but not able to run test case.

#### Screenshots
![image](https://user-images.githubusercontent.com/22269903/195121249-b774d487-188a-4a99-8587-dbbb5819f37a.png)
![image](https://user-images.githubusercontent.com/22269903/195121458-79dd466c-5ce8-4332-bc06-0647be8ba526.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test case is invalid according to the constraints. We appreciate your support!
