### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by uiharu-kazari** [LeetCode-Feedback/LeetCode-Feedback#9441]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The attached code can pass all current test cases within time limit, while failing ( `Runtime Error` ) for the more general case
```
[500000, 499999, 499998, ... , 3, 2, 1]
```

#### Code you used for Submit/Run operation

```
// 334. Increasing Triplet Subsequence
function increasingTriplet(nums: number[]): boolean {
    if ((new Set(nums)).size<3){
        return false;
    }
    let pairs:Array<Array<Number>> = [];
    for (let i=0; i<nums.length-1; i++){
        for (let j= i+1; j<nums.length; j++){
            if (nums[i]< nums[j]){
                pairs.push([i,j]);
            }
        }
    }
    
    if (pairs.length === 0){
        return false;
    }
    
    for ( let p1 of pairs){
        for (let p2 of pairs){
            if (p2[0] === p1[1]){
                return true;
            }
        }
    }
    return false;
};
```

#### Language used for code
TypeScript

#### Expected behavior

* We expect a code with high time complexity to fail when given a very long input. 
* Currently, that input is the very long array `[1, 2, 1, 2, 1, 2, 1, 2, ..., 1, 2]` (length = 500,000) .
* It can be circumvented by using a `Set` operation (which is `O(n)`) and looking at the size of that set, due to the coincidence that this very long array contains only two unique values and we need at least three unique values for a valid triplet.
* By adding a test case as indicated above, this unwanted shortcut would be eliminated.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test case is already in the test set. We appreciate your support!
