### ISSUE TITLE
Example Explanation Error - 732. My Calendar III

### ISSUE THREAD

**Issue by imoiwm** [LeetCode-Feedback/LeetCode-Feedback#9443]
#### Your LeetCode username
imoiwm

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Approach 3: Balanced Tree in the official LC solutions goes over an example inserting the interval ```[5,6)``` (step 2), but the rest of the written explanation and diagram for the example assume the inserted interval is ```[5,16)```. If this typo could be fixed that'd be great!

#### Code you used for Submit/Run operation

No code used/needed.

#### Language used for code
N/A

#### Expected behavior
Typo caused a bit of initial confusion when reading top-down and not understanding why both intervals ```[0,11)``` **and** ```[11,21)``` were getting split.

#### Screenshots
![image](https://user-images.githubusercontent.com/20688005/195159467-067cf7c7-3cce-44f7-93c1-02c45d333d8c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
