### ISSUE TITLE
Missing testcase in 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by YashMnC** [LeetCode-Feedback/LeetCode-Feedback#9445]
#### Your LeetCode username
yashmnc

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1] Missing Test Cases 

#### Description of the bug

For maximum length of nums , the worst case time complexity should be O(n*logn).
But due to missing test cases , O(n^2) solution is also accepted.  

#### Code you used for Submit/Run operation

```
// 334. Increasing Triplet Subsequence
class Solution {
public:
    bool increasingTriplet(vector<int>& nums) {
        

         int n=nums.size();
        vector<int> lis(n,1);

        unordered_map<int,int> count;
        for(auto num:nums)
        count[num]++;

        if(count.size()<=2) return false;

        for(int i=0;i<n;i++){
            for(int j=i+1;j<n;j++){
                if(nums[j]>nums[i])
                lis[j] = max(lis[j],1+lis[i]);
                if(lis[j]>=3) return true;
            }
        }

        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The verdict should be time limit exceeded for the above code.

#### Additional context

One of the test case that can be added to avoid the above behavior can be,
Test case:
nums contains 1 1e5 times and at the end contains 2 and 3.
```
nums = [1,1,1,1 ............1e5 times , 2,3]

```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
