### ISSUE TITLE
Invalid Testcase 39. Combination Sum

### ISSUE THREAD

**Issue by ilia-dot-karelia** [LeetCode-Feedback/LeetCode-Feedback#9446]
ilia.karelia@gmail.com

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
condition:
1 <= target <= 500

Test case:
[2,3,6,7]
41

Error:
Invalid Testcase
expected 'target' to have value from 1 to 40 only

#### Code you used for Submit/Run operation

```
// Combination Sum
class Solution {
    final List<List<Integer>> rez = new LinkedList<>();
    public List<List<Integer>> combinationSum(int[] candidates, int target) {
        Arrays.sort(candidates);
        gather(new LinkedList<>(), 0, 0, target, candidates);
        return rez;
    }
    
    
    private void gather(LinkedList<Integer> cur, int sum, int pos, int target, int[] candidates){
        if (sum == target){
            rez.add(new ArrayList<>(cur));
            return;
        }
        for (int i = pos; i < candidates.length; i++){
            if (sum + candidates[i] > target)
                break;
            cur.addLast(candidates[i]);
            gather(cur, sum + candidates[i], i, target, candidates);
            cur.removeLast();
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior
Test case accepted OR task description changed

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
Please reply this with your LC username.

**Comment by ilia-dot-karelia** [comment]
Hey, LC name is pawaptzSent from my iPhoneOn 14 Oct 2022, at 00:04, LC_M ***@***.***> wrote:﻿
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
Please reply this with your LC username.
