### ISSUE TITLE
Submission Run time Error Bug - 142. Linked List Cycle II

### ISSUE THREAD

**Issue by Boondirek-Kanjanapongporn** [LeetCode-Feedback/LeetCode-Feedback#9448]
#### Your LeetCode username
Boondirek Kanjanapongporn

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Whenever I run or submit the result that I get will always be "Runtime Error Message: Your returned value is not a ListNode type.". Eventhough, I think I returned the type correctly (ListNode). Even the solutions on Leetcode got the same error when running and submitting the test.

#### Code you used for Submit/Run operation
```

```
class ListNode:
    def __init__(self, x):
        self.val = x
        self.next = None

class Solution:
    def detectCycle(self, head: Optional[ListNode]) -> Optional[ListNode]:
        visited = set()

        node = head
        while node is not None:
            if node in visited:
                return node
            else:
                visited.add(node)
                node = node.next

        return None
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Python

#### Expected behavior
The result should be correct as it is from the solution from leetcode

#### Screenshots
![image](https://user-images.githubusercontent.com/50063205/195213619-30d99664-e554-4995-a3a9-df8bbc8bc230.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Boondirek-Kanjanapongporn** [comment]
Title:  142. Linked List Cycle II
Link: (10) Linked List Cycle II - LeetCode
<https://leetcode.com/problems/linked-list-cycle-ii/?envType=study-plan&id=level-1>

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by CollinsOduor** [comment]
It would seem like there is a regression with this problem

**Comment by XiaoleiC** [comment]
You can assume ListNode is a built-in class. So in your code, comment out the class ListNode. It seems the built-in ListNode did not look like the provided "ListNode" in this problem.
