### ISSUE TITLE
Missing Test Case 1085. Sum of Digits

### ISSUE THREAD

**Issue by longluo** [LeetCode-Feedback/LeetCode-Feedback#9449]
#### Your LeetCode username
longluo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✔] Missing Test Cases 

#### Description of the bug
 Problem 1085. Sum of Digits missing test case: `[100]`

I met this problem in leetcode.cn, but my issue haven't be solved.

so I submit to the Leetcode.com.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int sumOfDigits(int[] nums) {
        int min = Integer.MAX_VALUE;
        for (int x : nums) {
            min = Math.min(min, x);
        }

        int sum = min / 10 + min % 10;
        return sum % 2 == 0 ? 1 : 0;
    }
}
```

#### Language used for code
Java

#### Expected behavior
This code should not **AC** because when the test case is `[100]`, but it AC.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
