### ISSUE TITLE
[Python] Leetcode 16 TLE

### ISSUE THREAD

**Issue by sotheanithsok** [LeetCode-Feedback/LeetCode-Feedback#9450]
#### Your LeetCode username
SotheanithSok

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Two similar solutions but one is accepted and another causes time out.

#### Code you used for Submit/Run operation

```
//Accepted Code
class Solution:
    def threeSumClosest(self, nums: List[int], target: int) -> int:
        nums.sort()
        closest=0
        mindiff=float("inf")
        for i in range(len(nums)-2):
            
            l=i+1
            r=len(nums)-1
            while l<r:
                Sum=nums[i]+nums[l]+nums[r]
                if abs(Sum-target)<mindiff:
                    closest=Sum
                    mindiff=abs(Sum-target)
                if Sum>target:
                    r-=1
                elif Sum<target:
                    l+=1
                else:
                    return closest
        return closest
```

```
//TLE code
class Solution:
    def threeSumClosest(self, nums: list[int], target: int) -> int:
        n = len(nums)
        nums.sort()
        res = -inf
        for bound in range(n - 2):
            l, r = bound + 1, n - 1
            while l < r:
                cSum = nums[bound] + nums[l] + nums[r]
                if abs(res - target) > abs(cSum - target):
                    res = cSum
                if cSum == target:
                    return res
                elif cSum < target:
                    l += 1
                else:
                    r -= 1

        return res
```

#### Language used for code
Python

#### Expected behavior
Both codes should be accepted.

P.S. There seem to be a lot of problem lately with Python code. Once accepted solution now caused TLE.

**Comment by raychanks** [comment]
I created the same issue #9408 on this question as well but get closed unfortunately. Hope LeetCode will take a deeper look into this.

**Comment by sotheanithsok** [comment]
> I created the same issue #9408 on this question as well but get closed unfortunately. Hope LeetCode will take a deeper look into this.

Yes I encountered this kind of problem a few time. It is usually Python solutions with 5s+ running time. I guess it is just Python being slow and Leetcode doesn't like that.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Reduced the constraints, both are AC now. We appreciate your support!
