### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by vedvar** [LeetCode-Feedback/LeetCode-Feedback#9452]
#### Your LeetCode username
vedvarshney

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Test Case 159 for problem 121 is giving a wrong result. For an array with prices = [1,2] the output should be 0. However, the expected output is 1.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def maxProfit(self, prices):
        """
        :type prices: List[int]
        :rtype: int
        """

        min_price = float('inf')
        max_profit = 0

        for i in range (0, len(prices)-1):
            min_price = min(min_price, prices[i])
            profit = prices[i] - min_price
            max_profit = max(max_profit, profit)

        return max_profit
```

#### Expected behavior
Reading over the solution, it is pretty clear that the output should be 0. However, the expected output in the solution is 1

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment]
You buy the stock at price 1 and sell the stock at price 2. The result is 1. Why do you think the result should be 0?
