### ISSUE TITLE
398. Random Pick Index [Python] [Use of lru_cache giving error]

### ISSUE THREAD

**Issue by harshitkd** [LeetCode-Feedback/LeetCode-Feedback#9453]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem is when I am using @lru_cache(None) I am getting wrong answer though the output is same with or without writing that.

#### Code you used for Submit/Run operation

```
// Not using @lru_cache(None)
class Solution:

    def __init__(self, nums: List[int]):
        self.d = defaultdict(list)
        for i,x in enumerate(nums):
            self.d[x].append(i)
            
    def pick(self, target: int) -> int:
        return random.choice(self.d[target])
```

```
// using @lru_cache(None)
class Solution:

    def __init__(self, nums: List[int]):
        self.d = defaultdict(list)
        for i,x in enumerate(nums):
            self.d[x].append(i)
            
    @lru_cache(None)
    def pick(self, target: int) -> int:
        return random.choice(self.d[target])
```

#### Language used for code

Python

#### Expected behavior

I think if the output is same in both the cases then in the case when @lru_cache(None) is used, the status should not be wrong answer.

#### Screenshots

![Screenshot 2022-10-12 at 3 15 37 PM](https://user-images.githubusercontent.com/56076028/195309956-16fde514-abb7-4041-97a0-c73efa53349f.png)
![Screenshot 2022-10-12 at 3 15 15 PM](https://user-images.githubusercontent.com/56076028/195309972-37819edd-f2cc-4f1c-8fc9-a49698bf4512.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. lre_cache has a high factor. That's why it got TLE.
The number of test cases is small and the constraints are good. We appreciate your support!
