### ISSUE TITLE
Wrong complexity in Solution Approach 1 for 716. Max Stack

### ISSUE THREAD

**Issue by medvied** [LeetCode-Feedback/LeetCode-Feedback#9454]
#### Your LeetCode username

`medvied`

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 1: Two Balanced Trees Python code is:

```
    def top(self) -> int:
        return self.stack[-1][1]
```
`self.stack` is `sortedcontainers.SortedList`:
```
    def __init__(self):
        self.stack = SortedList()
        ...
```
`SortedList` documentation for [-1] https://grantjenks.com/docs/sortedcontainers/sortedlist.html#sortedcontainers.SortedList.__getitem__ tells the following about `__getitem__` complexity:

> Runtime complexity: O(log(n)) – approximate.

The Complexity Analysis for Approach 1 tells the following about the complexity analysis for the `top()` operation:

 > However, note that top and peekMax operations, requiring only the last element in a balanced tree, can be even done in O(1) with set::rbegin() in C++ and some special handles on the last element of SortedList in Python.

It's not clear if "some special handles" are implemented in `SortedList` already or they have to be done in the solution. They are not done in the Python solution (because Python solution simply uses indexed access), and according to the `sortedcontainer.SortedList` documentation the access is O(log(n)), which makes the code non-conforming to the following from the task description:

> You must come up with a solution that supports O(1) for each top call

#### Code you used for Submit/Run operation

N/A

#### Language used for code

Python 3

#### Expected behavior

I expect either of the following:
- the Python solution to include caching of the top element;
- clearly stating that the Python code for the first approach doesn't solve the task as it's defined because top() is not O(1);
- PR to `sortedcontainers.SortedList` to add the caching or mentioning (1) for the last element in the documentation if it's already done.

Example of how the caching of the top element could be done:
```
from sortedcontainers import SortedList


class MaxStack:

    def __init__(self):
        self.stack = SortedList()
        self.values = SortedList()
        self.cnt = 0
        self.stack_top = None

    def push(self, x: int) -> None:
        self.stack_top = self.cnt, x
        self.stack.add(self.stack_top)
        self.values.add((x, self.cnt))
        self.cnt += 1

    def pop(self) -> int:
        idx, val = self.stack.pop()
        if self.stack:
            self.stack_top = self.stack[-1]
        self.values.remove((val, idx))
        return val

    def top(self) -> int:
        return self.stack_top[1]

    def peekMax(self) -> int:
        return self.values[-1][0]

    def popMax(self) -> int:
        val, idx = self.values.pop()
        self.stack.remove((idx, val))
        if self.stack:
            self.stack_top = self.stack[-1]
        return val
```

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.  The complexity in the solution is correct, the issue is that sortedcontainers.SortedList docs don't describe it so detailed. It's not in our charge. Thanks to the feedback and we  still consider the ticket invalid. We appreciate your support!
