### ISSUE TITLE
1574. Shortest Subarray to be Removed to Make Array Sorted - contribute a testcase

### ISSUE THREAD

**Issue by JerryL1987** [LeetCode-Feedback/LeetCode-Feedback#946]
#### Your LeetCode username

Chihhung Li

#### Category of the bug
TestCase

#### Description of the bug

Miss the case which should check two direction. Please check detail example is shown as below.

At first, I get two indices, one is prefix index which is sorted array and the other is suffix index which is sorted array.
For example: [3, 6, 6, 8, 7, 6, 5, 7, 7, 9]
I can find prefix index 3 because [3, 6, 6, 8] is sorted array.
I also can find suffix index 6 because [5, 7, 7, 9] is also sorted array.

After that, I check the shortest subarray to be removed by value is larger than value of index 3 and value is smaller than index 6.
I can find the value of index 9 is larger than the value of index 3. In this case the removed subarray is [7, 6, 5, 7, 7] (length is 5).
I also can find the value of index 0 is smaller than the value of index 6. In this case the removed subarray is [6, 6, 8, 7, 6] (length is 5).
Hence, I return the value is 5.
It is wrong, because the shortest subarray to be removed is [8, 7, 6, 5] (length is 4).

#### Code you used for Submit/Run operation

```
int findLengthOfShortestSubarray(int* arr, int arrSize){
    int left = 1, right = 1;
    for(int i = 1; i < arrSize && arr[i] >= arr[i - 1]; i++)
        left++;
    for(int i = arrSize - 2; i >= 0 && arr[i] <= arr[i + 1]; i--)
        right++;    
    if (left == arrSize) {
        return 0;
    }
    int len1 = right,len2=left;
    for(int i = arrSize - right; i < arrSize && arr[i] < arr[left - 1]; i++)
        len1--; 
    for(int i = left - 1; i >= 0 && arr[i] > arr[arrSize - right]; i--)
        len2--;   
    return (arrSize - left - len1 > arrSize - right - len2)? arrSize - right - len2: arrSize - left - len1;
}
```

#### Language used for code

C

#### Expected behavior

The code I provided should be a wrong submission .

#### Screenshots

![image](https://user-images.githubusercontent.com/46712380/92346846-97f60c00-f100-11ea-9edf-af1cdb8fd419.png)

**Comment by lc-kay** [comment]
Hi @JerryL1987, 

When I tried to run the code you provided, I received a wrong submission. 
https://leetcode.com/submissions/detail/393888008/

**Comment by lc-kay** [comment]
Hi @JerryL1987 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
