### ISSUE TITLE
Invlaid Test Case ["abc", "ab"] - 269. Alien Dictionary

### ISSUE THREAD

**Issue by delf1** [LeetCode-Feedback/LeetCode-Feedback#9464]
#### Your LeetCode username
delf

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Invalid Test Case

#### Description of the bug
The problem statement mentions:
"You are given a list of strings words from the alien language's dictionary, where the strings in words are sorted lexicographically by the rules of this new language."

The input ["abc","ab"] does not meet the definition of lexicographical sorting defined in the question:
"A string s is lexicographically smaller than a string t if at the first letter where they differ, the letter in s comes before the letter in t in the alien language. If the first min(s.length, t.length) letters are the same, then s is smaller if and only if s.length < t.length."

s = "abc"
t = "ab"
min(s.length, t.length) = 2
s[0:2] == t[0:2]
this implies s.length < t.length
but here s.length > t.length

This test case is invalid and should be removed.

#### Language used for code
Python

#### Expected behavior
["abc","ab"] should be removed since it is an invalid test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. Did not remove the test case, as the problem statement mentions that there exists cases whose solutions do not exist. We appreciate your support!
