### ISSUE TITLE
Different result for same test case on final submit

### ISSUE THREAD

**Issue by meghnabajoria** [LeetCode-Feedback/LeetCode-Feedback#9465]
#### Your LeetCode username

Meghna-Bajoria

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One of the test cases passes when I give it manually on the test case section but fails when I hit the submit button.  The test case result is also different in both the cases. Please check the attached screenshot.

About this test case
Enter [3,3,6,8] and 10 on test case window. 

#### Code you used for Submit/Run operation

1498. Number of Subsequences That Satisfy the Given Sum Condition
```
class Solution {
    static int count = 0;
    public int numSubseq(int[] nums, int target) {
        
        List<Integer> list = new ArrayList<>();
        recursion(0, 0, list, target, nums);
        return count;
        
    }
    
    private void recursion(int indx, int sum, List<Integer> list, int target, int[] nums) {
        if(indx == nums.length) {
            List<Integer> list2 = list;
            Collections.sort(list2);
            if(list2.size() != 0) {
                 int min = list2.get(0);
                int max = list2.get(list2.size() - 1);
                if(min + max <= target)
                    count++;
            }
            return;
        }
        
        sum = sum + nums[indx];
        //System.out.println("1 sum = " + sum);
        list.add(nums[indx]);
        recursion(indx+1, sum, list,target,nums);
        
        sum = sum - list.get(list.size() - 1);
        //System.out.println("2 sum = " + sum);
        list.remove(list.size() - 1);
        recursion(indx+1, sum, list,target,nums);
    }
}
```

#### Language used for code

java

#### Expected behavior

The submit and run test case option should give the same result i.e both the answer should be 6. But submit button gives answer as 10 whereas run button gives 6

#### Screenshots

<img width="958" alt="image" src="https://user-images.githubusercontent.com/50470784/195447391-33830841-422d-49c8-b090-724ecab39a8c.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
