### ISSUE TITLE
测试用例有错误。 

### ISSUE THREAD

**Issue by NetCloud2017** [LeetCode-Feedback/LeetCode-Feedback#9466]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
 Uncode

**Bug 类型**
- [29. 两数相除](https://leetcode.cn/problems/divide-two-integers/)

**描述**
测试用例有错误， 测试用例为 被除数  -2147483648 ， 除数 -1，正确的答案应是 2147483648 ，但是 期望结果显示是 2147483647 。 

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
 var divide = function(dividend, divisor) {
    let merchant = 0;
    let a = Math.abs(dividend), b = Math.abs(divisor);
    while (a  >= b) {
        a -= b;
        merchant ++;
    }
    if(divisor < 0 && dividend > 0 || dividend < 0 && divisor > 0) {
        merchant = - merchant
    }
    return merchant;
};
 
```

**期望行为**
 2147483648

**屏幕截图**
 
![搜狗截图20221013121326](https://user-images.githubusercontent.com/32604559/195502502-2ff18719-7fb3-43d5-9557-21fa5ce18fc9.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，经核实该题测试用例暂无异常，需要注意到题目中：提示的第三条。
后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by NetCloud2017** [comment]
OK， 没看完整提示。 谢谢。
