### ISSUE TITLE
Typescript params named `root` when it should be `node` - 237. Delete Node in a Linked List

### ISSUE THREAD

**Issue by Aryan3212** [LeetCode-Feedback/LeetCode-Feedback#9468]
#### Your LeetCode username

Aryan3212

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Param should be renamed to `node` currently it is  `root`.

#### Code you used for Submit/Run operation

Not applicable.

#### Language used for code

Typescript

#### Expected behavior

Param should be called `node`.

#### Additional context

https://leetcode.com/problems/delete-node-in-a-linked-list/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
