### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by mohdaffan3** [LeetCode-Feedback/LeetCode-Feedback#9469]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
 There is a message showing compile error but the same code is working perfectly in my compiler. It is showing an error at line 30 but my code is just of 27 line .

#### Code you used for Submit/Run operation

```
#include<stdio.h>
int isPalindrome(int number)
{
int pal;
pal=number;
int remainder=0,newnum=0; 
     while(pal!=0)
     {
        remainder=pal%10;
        newnum=newnum*10+remainder;
        pal=pal/10;
     }
     if(number==newnum)
     {
         printf(" true");
     }
     else
     {
     printf("false");
     }
}
int main()
{
    int number;
    printf("enter the number : ");
    scanf("%d",&number);
    isPalindrome(number);

}
```

#### Language used for code
C

#### Expected behavior
The code should have worked perfectly but there is a compile error.

#### Screenshots
If applicable, add screenshots to explain your issue. 

#### Additional context
Line 34: Char 5: error: redefinition of ‘main’ [solution. c]
 int main(int argc, char * argv []) {
     ^
This is the error message being displayed

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. This isn't how LC accepts submissions. Please to update the function only and feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

We appreciate your support!
