### ISSUE TITLE
Inconsistent test case for 290. Word Pattern

### ISSUE THREAD

**Issue by paragpachpute** [LeetCode-Feedback/LeetCode-Feedback#947]
#### Your LeetCode username
pachpute

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
It seems that there is an incorrect test case for the problem 290. Word Pattern. The description of the question says that a character should match to `non-empty word in str`. Therefore, for the test case, pattern = `a` and str = ` ` (single space), it should return `false`.

Now, if you are considering the space ` ` as a non empty word then the output of the following test case should be `true`
pattern = `aa` and str = `   ` (3 spaces).

I sense there is are inconsistencies in the test cases.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean wordPattern(String pattern, String str) {
        String[] words = str.split("[ ]");
        if (pattern.length() != words.length || str.equals(""))
            return false;
        
        Map<Character, String> charToWord = new HashMap<>();
        Map<String, Character> wordToChar = new HashMap<>();
        
        for (int i = 0; i < pattern.length(); i++) {
            char ch = pattern.charAt(i);
            if (charToWord.containsKey(ch) && !charToWord.get(ch).equals(words[i]))
                return false;
            else if (wordToChar.containsKey(words[i]) && wordToChar.get(words[i]) != ch)
                return false;
            
            if (!charToWord.containsKey(ch))
                charToWord.put(ch, words[i]);
            
            if (!wordToChar.containsKey(words[i]))
                wordToChar.put(words[i], ch);
        }
        
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Noted in the description

**Comment by lc-kay** [comment]
Hi @paragpachpute 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @paragpachpute, 

Our team has reviewed the issue and added more clear constraints to the problem. The test cases that caused confusion previously are just invalid test cases. I hope this resolves your issue. Thank you for using LeetCode!
