### ISSUE TITLE
Mistake in OJ of `69. Sqrt(x)`

### ISSUE THREAD

**Issue by samyak1409** [LeetCode-Feedback/LeetCode-Feedback#9473]
#### Your LeetCode username

samyak1409

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

As we know, sqrt(x) = √x = -√x i.e. sqrt(25) = 5 = -5
But the OJ of [69. Sqrt(x)](https://leetcode.com/problems/sqrtx) is not accepting -ve roots, that it should, because it's not mentioned anywhere to return +ve root only, it doesn't make any sense to return -ve root though, but still it's correct and so should be accepted.

***STRAIGHT-FORWARD BUG SO FURTHER DESCRIPTION ISN'T NEEDED.***

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've Rewrote the statement to match the standards. We appreciate your support!
