### ISSUE TITLE
Missing Test Case - 739. Daily Temperatures

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#9474]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9782374/1.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] dailyTemperatures(int[] temperatures) {
        int n = temperatures.length;
        int[] ret = new int[n], max = new int[2];
        max[0] = temperatures[n - 1]; max[1] = n - 1;
        for(int i = n - 2; i >= 0; i--) {
            if(max[0] > temperatures[i]) {
                for(int j = i + 1; j <= max[1]; j++) {
                    if(temperatures[j] > temperatures[i]) {
                        ret[i] = j - i;
                        break;
                    }
                }        
            } else {
                ret[i] = 0;
            }
            if(temperatures[i] >= max[0]) {
                max[0] = temperatures[i];
                max[1] = i;
            }
        }
        return ret;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
