### ISSUE TITLE
Missing Test Case - 2416. Sum of Prefix Scores of Strings

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#9475]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Please double check #9111. The test data is just a set of random strings. It targets the size of the array (should set maxn>=1000000).

**Comment by LC-Pam** [comment]
we reopened the ticket and will reply the result in the #9111
