### ISSUE TITLE
Missing Test Case - 1854. Maximum Population Year

### ISSUE THREAD

**Issue by jko206** [LeetCode-Feedback/LeetCode-Feedback#9477]
#### Your LeetCode username

user0045w

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] misc

#### Description of the bug

Can you please change the example numbers so people aren't dying at age 10 or 11? It's fucking morbid. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
