### ISSUE TITLE
Missing Test Case - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by sahil0812** [LeetCode-Feedback/LeetCode-Feedback#9478]
#### Your LeetCode username
sahil0812

#### Category of the bug
- [x] Solution
- [x] Missing Test Cases 

#### Description of the bug
My code is running for below test case when i simply run the code and it shows answer is accepted, but when i try to submit my solution it shows wrong answer
[1,2]
1 

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    int count(ListNode *head){
        int cou =0;
        while(head!=NULL){
            head = head->next;
            cou++;
        }
        return cou;
    }
    
    void find(ListNode *head, int n){
        static int i = n;
        if(head == NULL){
            return;
        }
        find(head->next, n);
        if(i!=0){
            i--;
        }else{
            head->next = head->next->next;
            i = INT_MAX;
        }
    }
    
    ListNode* removeNthFromEnd(ListNode* head, int n) {
        int co = count(head);
        
        if(co == n){
            return head->next;
        }
        find(head, n);
        return head;
    }
};
```

#### Language used for code

 C++

#### Expected behavior

I'm expecting that the given test case must run while submitting the code, if it is running on run option.

#### Screenshots

![image](https://user-images.githubusercontent.com/85567719/195779475-ad916c50-d93e-4a4a-97ca-ec1fa7f9c61d.png)
![image](https://user-images.githubusercontent.com/85567719/195779513-a5c34a5f-0034-47ca-9a0b-6b585cbb496e.png)
![Screenshot (1096)](https://user-images.githubusercontent.com/85567719/195780444-e881f250-b272-4fde-8e0b-95565d8ca89b.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
