### ISSUE TITLE
2. 两数相加、198. 打家劫舍 通过的提交 点进去 看不到 执行用时分布图表

### ISSUE THREAD

**Issue by JohnChenLiang** [LeetCode-Feedback/LeetCode-Feedback#9479]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![1665734436599](https://user-images.githubusercontent.com/30498675/195794666-913a8b6e-42e7-4a12-bbb3-e5c22cf43974.png)
![1665734469319](https://user-images.githubusercontent.com/30498675/195794685-5d3d0474-5e5f-4e91-a0c6-e9bbe45b99f0.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by JohnChenLiang** [comment]
bug不解决，搞这些乱七八糟的。
