### ISSUE TITLE
Request to difficulty change to Medium - 849. Maximize Distance to Closest Person

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#948]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

849. Maximize Distance to Closest Person
https://leetcode.com/problems/maximize-distance-to-closest-person

Please convert this Easy problem into a Medium problem

It does have 3 conditions/ edge case with different Math formulas for each, not an Easy one.
I have solved this problem. It required multiple time rewrite of solution to get it correct.

Some requests in comments with upvotes for the same:
	https://leetcode.com/problems/maximize-distance-to-closest-person/solution/626125
	https://leetcode.com/problems/maximize-distance-to-closest-person/solution/620262
	https://leetcode.com/problems/maximize-distance-to-closest-person/solution/616465
	https://leetcode.com/problems/maximize-distance-to-closest-person/solution/536975

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Easy should be at Easy level.

Multiple Math formulas with different edge scenarios would take time - require a level up to Medium.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. This problem is now a medium difficulty problem. We appreciate your support!
