### ISSUE TITLE
Incorrect time complexity for Kruskal's algorithm in Explore Graphs chapter

### ISSUE THREAD

**Issue by aparnadotk** [LeetCode-Feedback/LeetCode-Feedback#9484]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Solution

#### Description of the bug

The Time complexity analysis of Kruskal's algorithm only considers the complexity for sorting the edges O(ElogE) and adding each edge using UnionFind algorithm O(Ealpha(V)). However, in order to use the UnionFind algorithm, the constructor for the UnionFind class initializes the root and rank arrays, which will take O(V) time. Hence, the overall complexity for Kruskal's algorithm should be: O(ElogE + E + V) ~ O(ElogE + V).

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submit your feedback to the team. We appreciate your support!
