### ISSUE TITLE
769. 最多能完成排序的块

### ISSUE THREAD

**Issue by li54426** [LeetCode-Feedback/LeetCode-Feedback#9486]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
li54426

**Bug 类型**
- [ ] 题目

**描述**
题目的示例描述不清, 示例1 的 [4, 3] 进行了排序, 示例2的 [1, 0] 就没排序
搞不懂是什么意思, 难道是 :块内按照原来的顺序, 块之间按照升序?

//--------------------------------------示例1:--------------------------
输入: arr = [4,3,2,1,0]
输出: 1
解释:
将数组分成2块或者更多块，都无法得到所需的结果。
例如，分成 [4, 3], [2, 1, 0] 的结果是 [3, 4, 0, 1, 2]，这不是有序的数组。
//--------------------------------------------------------------------

//----------------------------------示例2:-------------------------------
输入: arr = [1,0,2,3,4]
输出: 4
解释:
我们可以把它分成两块，例如 [1, 0], [2, 3, 4]。
然而，分成 [1, 0], [2], [3], [4] 可以得到最多的块数。
//---------------------------------------------------------------------

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
重新解释一下示例

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题面已更新，ID：li54426 给予积分奖励，请查收。
