### ISSUE TITLE
Daily Temperatures Gets time limit exceeded  for posted solution

### ISSUE THREAD

**Issue by jhancock1975** [LeetCode-Feedback/LeetCode-Feedback#9487]
I can copy and paste the solution given in the solution for the problem and run it multiple times.  Sometimes it generates the "time limit exceeded" error, and sometimes it runs successfully. 

For example the following got preempted with "time limit exceeded" 
https://leetcode.com/submissions/detail/822915755/
https://leetcode.com/submissions/detail/822915811/

And then the exact same code passed with "Runtime: 1195 ms, faster than 94.69%"
https://leetcode.com/submissions/detail/822915858/

That code is also the same as the code listed in "Approach 2: Array Optimized Space" in the solution tab for the problem.
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've Updated the time limit for python. It now passes. We appreciate your support!
