### ISSUE TITLE
Unclear Problem description/ Testcase1 - 849. Maximize Distance to Closest Person

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#949]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

849. Maximize Distance to Closest Person
https://leetcode.com/problems/maximize-distance-to-closest-person

Problem/ Test case description could be better.

If Alex sits in the second open seat (seats[2]), then the closest person has distance 2.
please change it to
If Alex sits in the second open seat (seats[2], index 0-based), then the closest person has distance 2 away.

NOTE: 2 changes above:   index 0-based  &  away.

#### Code you used for Submit/Run operation
```
```

#### Language used for code
JS

#### Expected behavior

Problem needs a bit of re-read, test case 2 make it clear, but test case 1 OR problem description can be better.

Problem should clear by the time Test case 1 is read.
Here it requires 2nd test case reading too.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
