### ISSUE TITLE
Weekly Contest 315 - Question3

### ISSUE THREAD

**Issue by saitejapadakandla** [LeetCode-Feedback/LeetCode-Feedback#9493]
Leetcode user name: saiteja973
Category: Solution/Submission Issue
Description of the bug:
During the contest initially I tried to solve the question in brute force way, it gave TLE. I spent more time to optimize it but it didn't pass. When I submit the same
 solution after the contest it ran successfully. I see other users posted same solution in Solutions Tab.

Language used for code ; Python

![Capture](https://user-images.githubusercontent.com/16510539/196017709-b813ee36-97c0-4d9a-be8d-2cfbfba4e7e9.PNG)
![Capture](https://user-images.githubusercontent.com/16510539/196017733-47e2d9c0-2d6b-49f4-892d-6fd962ee0ec2.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission TLE link during the contest. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by saitejapadakandla** [comment]
Hello Team, Thanks for the response. Please find the URL for the code submission TLE during the contest

https://leetcode.com/problems/sum-of-number-and-its-reverse/submissions/823410936/

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team and our developer is working on it. We appreciate your support!
