### ISSUE TITLE
Weekly Contest 315, Problem 3

### ISSUE THREAD

**Issue by sauravbharti021** [LeetCode-Feedback/LeetCode-Feedback#9496]
#### Your LeetCode username
 
sauravbharti021

#### Category of the bug
- [x] Question 
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

Question 3- 2443. Sum of Number and Its Reverse (Weekly Contest 315)
Solution- Avoiding the use of string and doing it using while loop and divide gets the answer passed in 62 ms, That it told me 100% faster than anyone.
![bug 1](https://user-images.githubusercontent.com/86503989/196019217-94a4fc49-5f94-4116-a1ed-20c1f01cf0e3.png)
![bug 2](https://user-images.githubusercontent.com/86503989/196019220-b8f62e86-d3c0-4c54-9dda-a90708ebe6b0.png)

Language- C++

#### Description of the bug

Maximum complexity of my solution can be (6 * 10^5) to 10^6 that should easily be passed within 1 second. 
                   And 99% of the contests,  I had ever given had the minimum complexity of at least 1 second, I never got TLE like this. But during contest it gave me TLE on TC- n=99982. 

This is too strict, how come I was supposed to know that without failing on first attempt. You guys didn't even mentioned that.

 It ruins all the hardwork that goes into contests. Ruined my both contest biweekly 89 and weekly 315 as whatever + delta I could have got in contest before, this will nullify it.

Somehow I don't think it's my fault. 

#### Code you used for Submit/Run operation

```
#define ll long long
#define pi (3.141592653589)
#define mod 1000000007
#define float double
#define pb push_back
#define mp make_pair
#define ff first
#define ss second
#define all(c) c.begin(), c.end()
#define min3(a, b, c) min(c, min(a, b))
#define min4(a, b, c, d) min(d, min(c, min(a, b)))
#define rrep(i, n) for(int i=n-1;i>=0;i--)
#define rep(i,n) for(int i=0;i<n;i++)
class Solution {
public:
    bool sumOfNumberAndReverse(int num) {
        
        int f=0;
        for(int i=0; i<=num;i++){
            ll x=i;
            string s=to_string(i);
            reverse(all(s));
            ll y=stoll(s);
            if(x+y==num) {return true;}
        }
        
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Should have cleared all testcases with ease. 

I'm attaching one more screenshot of how reversing a substring is the reason why it gives TLE. 
                                 Now, Reversing a string takes O(n) time i.e. max 6 length here. Total complexity becomes- 6* 10^5. 

Now, If we don't do any reversing and just divide.. max operations here also can be 6. So, it's the same thing but

Without using string solution pass the testcases in 66ms and using string it cannot pass in even 3000ms. I have no answers to that
Please tell me why?
![bug 4](https://user-images.githubusercontent.com/86503989/196037481-dbae1d3b-6ab7-4368-b228-e133e2c82f86.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. There was an issue with the judgers that caused some AC solutions to TLE during the contest. We will fix it soon. We appreciate your support!

**Comment by sauravbharti021** [comment]
Will you rejudge it??

**Comment by LC-Pam** [comment]
Yes, we are working on it. We will rejudge all the Q3 TLE Submissions.
