### ISSUE TITLE
Video is not working

### ISSUE THREAD

**Issue by ikhsangama** [LeetCode-Feedback/LeetCode-Feedback#9497]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
all the video should be working

#### Screenshots

![image](https://user-images.githubusercontent.com/17669844/196021177-b0262ca1-22fc-4e0e-8f86-8f54897d5147.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
