### ISSUE TITLE
797. All Paths From Source to Target (The 30th test case's expect may have error)

### ISSUE THREAD

**Issue by MingjunMa** [LeetCode-Feedback/LeetCode-Feedback#9498]
#### Your LeetCode username
Arcgo

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The 30th test case's expect result should be [0, 2, 1] rather than [0, 2]. Because the end point 1 should in the path.

#### Code you used for Submit/Run operation

```
class Solution {
    
    List<List<Integer>> ret = new LinkedList<List<Integer>>();
    
    public List<List<Integer>> allPathsSourceTarget(int[][] graph) {
        LinkedList<Integer> path = new LinkedList<Integer>();
        path.add(0);
        dfs(graph, graph[0], path, graph.length-1);
        return ret;
    }
    
    public void dfs(int[][] graph, int[] edges, LinkedList<Integer> path, int target) {
        if((null == edges || edges.length == 0) && path.getLast() == target) {
            List<Integer> copy = (LinkedList)path.clone();
            ret.add(copy);
            return;
        }
        
        for(int i=0; i<edges.length; i++) {
            path.add(edges[i]);
            dfs(graph, graph[edges[i]], new LinkedList<Integer>(path), target);
            path.removeLast();
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior

The 30th test case's expect result should be [0, 2, 1] rather than [0, 2]. Because the end point 1 should in the path.

#### Screenshots
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/54018772/196021736-093cccca-55bd-4bea-bf64-bd92b99ed600.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
