### ISSUE TITLE
Missing test cases - 1013. Partition Array Into Three Parts With Equal Sum

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#950]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Solution at https://leetcode.com/submissions/detail/391712551/
Click on the solution in the graph at 84 ms

Popup will open with title "sample 84 ms submission"

Above submission is a Pass
But below test cases are failing for it:

		input   [1,1,1,1,-1]
		expect  true
		actual  false
		input   [2,2,2,2,-2]
		expect  true
		actual  false
		input   [3,3,3,3,-3]
		expect  true
		actual  false
		input   [4,4,4,4,-4]
		expect  true
		actual  false
		input   [5,5,5,5,-5]
		expect  true
		actual  false

All above tests are under given constraints

3 <= A.length <= 50000
-10^4 <= A[i] <= 10^4

Please add above test cases to this problem.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Question should test for all test cases under given constraints.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy, 

After reviewing your code and test cases, the code was accepted. All the expected and output for each of  test codes you suggested are true. 

<img width="1421" alt="Screen Shot 2020-09-10 at 1 32 04 PM" src="https://user-images.githubusercontent.com/70870126/92800946-05f13c00-f36a-11ea-8376-b6f07729f022.png">


https://leetcode.com/submissions/detail/393890716/
