### ISSUE TITLE
Missing Test Case - 1312. Minimum Insertion Steps to Make a String Palindrome

### ISSUE THREAD

**Issue by rhythm-design** [LeetCode-Feedback/LeetCode-Feedback#9500]
#### Your LeetCode username
rhythm_varshney

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The online judge is accepting code which is supposed to give TLE for certain testcase but code got accepted

#### Code you used for Submit/Run operation
```
class Solution {
    int[][] rhy;
    public int LCSMemo(String s1, String s2, int n, int m){
        if(n==0 || m==0) return 0;
        if(rhy[n][m]!=0) return rhy[n][m];

        if(s1.charAt(n-1)==s2.charAt(m-1)){
            return rhy[n][m]=LCSMemo(s1,s2,n-1,m-1)+1;
        }else{
            int leftRecursion=LCSMemo(s1,s2,n-1,m);
            int rightRecursion=LCSMemo(s1,s2,n,m-1);
            return rhy[n][m]=Math.max(leftRecursion,rightRecursion);
        }
    }
    
    public int minInsertions(String s) {
        StringBuilder sb=new StringBuilder(s);
        String reversed=sb.reverse().toString();
        rhy=new int[s.length()+1][s.length()+1];
        return s.length()-LCSMemo(s,reversed,s.length(),s.length());
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
The online judge is accepting code which is supposed to give TLE for certain testcase but code got accepted. I have uploaded a file which contain the missing testcase.

#### Screenshots
![image](https://user-images.githubusercontent.com/56234578/196027814-361adc36-c235-40f2-9df9-be6b6c1856a7.png)

#### Additional context
[missing test case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9794031/missing.test.case.txt)

[missing test case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9794029/missing.test.case.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
