### ISSUE TITLE
528. Random Pick with Weight

### ISSUE THREAD

**Issue by demian51** [LeetCode-Feedback/LeetCode-Feedback#9501]
#### Your LeetCode username

demian51.tw@gmail.com

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Example code of C++ in "Approach 2: Prefix Sums with Binary Search" is wrong. You'd better to use `lower_bound` instead of `upper_bound`; the latter will produce an off-by-one error when `rand()` returns `RAND_MAX`.

#### Code you used for Submit/Run operation

```C++
class Solution {
    vector<int> prefixSums;

public:
    Solution(vector<int> &w) {
        for (auto n : w)
            prefixSums.push_back(n + (prefixSums.empty() ? 
                0 : prefixSums.back()));
    }
    int pickIndex() {
        // generate a random number in the range of [0, 1]
        float randNum = (float)RAND_MAX / RAND_MAX; // <-- This line is modified to reproduce the error
        float target =  randNum * prefixSums.back();
        return upper_bound(begin(prefixSums), end(prefixSums), target) - begin(prefixSums);
    }
};
```

#### Language used for code

C++

#### Expected behavior

Pass the all test cases

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
