### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by yuriyberezovskiy** [LeetCode-Feedback/LeetCode-Feedback#9507]
#### Your LeetCode username

yuriy_ber

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In article "DFS - Template I" typo mistake in code example.
(at line 8 `visted`)

#### Screenshots

<img width="863" alt="Screenshot 2022-10-17 at 02 27 11" src="https://user-images.githubusercontent.com/3930033/196063826-b796ec6a-c7e7-4c7a-b2ee-5df105b53128.png">

#### Additional context

Link to article
https://leetcode.com/explore/learn/card/queue-stack/232/practical-application-stack/1384/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
