### ISSUE TITLE
Inconsistent Problem description format

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#951]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

840. Magic Squares In Grid
https://leetcode.com/problems/magic-squares-in-grid/

- Replace "Note:" with "Constraints"

We need to have uniformity across all questions.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Users should focus on problem - should not be forced to think why it is called "Note" instead "Constraints" - as its not part of the Problem description

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem's constraints and validators. We appreciate your support!
