### ISSUE TITLE
JS Segfaults on Nim Game

### ISSUE THREAD

**Issue by timfenney** [LeetCode-Feedback/LeetCode-Feedback#9511]
#### Your LeetCode username

HapticBovine

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I submitted a JS solution to a problem, but the process tried to access memory outside of that which was allocated to it by the OS, and the OS sent it a SIGSEGV signal, meaning the process caused a segmentation fault. JS can't do this, but a buggy Node can, or possibly npm modules installed with native extensions.

#### Code you used for Submit/Run operation

```
/**
 * @param {number} n
 * @return {boolean}
 */
var canWinNim = function(n) {
    const nims = {};
    function canWinNimRecur(n, p) {
        if (n === 1 || n === 2 || n === 3) {
            return p;
        }
        const key = `${n}x${p}`;
        if (key in nims) {
            return nims[key];
        }

        let result = null;
        const results = [1, 2, 3]
            .map(s => canWinNimRecur(n - s, !p));
        if (p) {
            result = results.some(Boolean);
        } else {
            result = results.every(Boolean);
        }

        nims[key] = result;
        return result;
    }
    return canWinNimRecur(n, true);
};
```

#### Language used for code
Javascript lmao

#### Expected behavior
I submitted my solution and got Runtime Error (process exited with signal SIGSEGV), which was unexpected, since Javascript doesn't allow programmers to manage their own memory.
I expected to see one of "wrong answer", "time limit exceeded", or obviously AC as I always get first try ;-)

#### Additional context

Please note this is Javascript, and when programming JS we can't cause this error. This is caused by a bug in Node, a faulty NPM module you are importing somewhere in the code that runs the solutions, or something else on your side (bad ram in a server... whatever). _Javascript code doesn't cause these errors_.
If you are not doing anything special for JS (since other langs like C++ can cause this error), I suggest you start. When this error occurs for JS solutions, don't report it to the User (since it is not their fault and they can't fix it). For this type of error you have to say "Oops something broke, try again later" or whatever, and flag it with an issue or a slack bot or something to the devs. Then they can fix whatever is broken on your side.

**Comment by timfenney** [comment]
@LC-Pam please don't close this, this is a JS solution.

Apps should not surface errors to Users that are not in the User's control to fix. Therefore I think it is good to show the User this error for a C++ solution, *but not for a JS solution.*

What do you think?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
