### ISSUE TITLE
Missing Test Case - 1790. Check if One String Swap Can Make Strings Equal

### ISSUE THREAD

**Issue by chirag-star** [LeetCode-Feedback/LeetCode-Feedback#9514]
#### Your LeetCode username
 chirag-star
leetcode profile link: https://leetcode.com/chirag-star/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I have solved the question with just naive solution and found that my solution is accepted but then I applied a test-case then I saw that my solution is wrong there. So I think that there is a missing test-case

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean areAlmostEqual(String s1, String s2) {
        char c1[] = s1.toCharArray();
        char c2[] = s2.toCharArray();
        int n = c2.length;
        int count =0;
        boolean ans = false;
        int sum1 =0;
        int sum2 =0;
        for(int i =0;i<n; i++){
if(c1[i]!=c2[i]){
    count++;
}
sum1 = sum1 + (int)c1[i];
sum2 = sum2 + (int)c2[i];

        }
    if(sum1==sum2 && count<=2 && count!=n){
            return true;
        }
        return ans;
    }
}
```

#### Language used for code
 JAVA programming

#### Expected behavior

I have doubt that my code is not set to answer the test cases because it is not right solution I have applied test cases that are not provided by leetcode. So I am contributing my test-case
**Test-Case(Contribution)
s1="bfdd"
s2="dddd"**

**Expected output : false 
My Code output : true**

My code executes all other cases provided by you successfully.

#### Screenshots

**My Code that is accepted:**
 https://github.com/chirag-star/Issues_in_Leetcode/blob/main/Screenshot%20(154).png

**Test cases that is failed on my code :** 
https://github.com/chirag-star/Issues_in_Leetcode/blob/main/Test-cases.jpg

#### Additional context

Contributed Test- Case
**Test-Case(Contribution)
s1="bfdd"
s2="dddd"**

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by chirag-star** [comment]
It's my Pleasure to work with you.
