### ISSUE TITLE
608. 树节点所有测试用例都通不过了

### ISSUE THREAD

**Issue by shchzh85** [LeetCode-Feedback/LeetCode-Feedback#9516]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**shuai8zhou**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [608. 树节点 https://leetcode.cn/problems/tree-node/ ] 题目
- [https://leetcode.cn/problems/tree-node/solutions/23160/shu-jie-dian-by-leetcode/ ] 题解
- [sql ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
提交的后一直都报这个错，不管什么代码
foreign key p_id =  does not exist in the Tree table
**你使用的语言**
mysql

**你提交或者运行的代码**
```
select id, (
    case
        when p_id is null then 'Root'
        when id = any(select p_id from tree) then 'Inner'
        else 'Leaf' 
    end
) as 'Type' from tree;
```

**期望行为**
描述你期望的结果
提交正确可以通过测试

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![20221017161021](https://user-images.githubusercontent.com/2274762/196123831-bde47399-ccf1-416c-8d2d-c9ac45fbe0e6.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
已修复。
