### ISSUE TITLE
Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by ajaybhati0016** [LeetCode-Feedback/LeetCode-Feedback#9517]
#### Category of the bug

- [x] Solution
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Hi @,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
