### ISSUE TITLE
SQL584. 寻找用户推荐人

### ISSUE THREAD

**Issue by chengyj0505** [LeetCode-Feedback/LeetCode-Feedback#9518]
**mi-ma-cuo-wu-a**
 密码错误啊

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ √] 编程语言
- [ ] 缺少测试用例

**描述**
同样的代码，有时可以执行通过有时不能通过

**你使用的语言**
MySQL

**你提交或者运行的代码**
```
select
    name
from customer
where referee_id is null
or referee_id <> 2
```

**期望行为**
希望能说明一下出现这种状况的原因，谢谢！

**屏幕截图**
![cc5dcbfa05bff53170cb22d223ca438](https://user-images.githubusercontent.com/83801480/196168073-e7740ac7-cf08-4c74-9fa4-e82dec4d41f0.jpg)

![5e7ba6c7af71525e8d4a398b6fcd081](https://user-images.githubusercontent.com/83801480/196168105-648da3a5-6f9f-451b-a303-a4331a2a6d33.jpg)

**Comment by feiceh** [comment]
您好，在与相关团队核实后：空格格式有问题，提供的代码中，空格为 \xa0
通常所用的空格是 \x20
