### ISSUE TITLE
Incorrect Problem description - 830. Positions of Large Groups

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#952]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

830. Positions of Large Groups
https://leetcode.com/problems/positions-of-large-groups/

"The final answer should be in lexicographic order."
 Should be:
"The final answer should be in increasing order of the indices."

Why?
- Author explanation is vauge: https://leetcode.com/problems/positions-of-large-groups/solution/136693
- Others suffered
  - https://leetcode.com/problems/positions-of-large-groups/discuss/187883/lexicographically
  - https://leetcode.com/problems/positions-of-large-groups/discuss/129140/Ambiguous%3A-%22the-final-answer-should-be-in-lexicographic-order.%22
  - https://leetcode.com/problems/positions-of-large-groups/solution/136694

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Author mistook the terminology of strings, the "lexicographic order", for numbers also.
This has confused many people.
It should have been written as "increasing order of the indices."

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
