### ISSUE TITLE
Fix Typo - Bit Manipulation Explore Card

### ISSUE THREAD

**Issue by kssk92sathish** [LeetCode-Feedback/LeetCode-Feedback#9520]
#### Your LeetCode username
kssk92sathish

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Bit Manipulation explore card "The basics of bit manipulation" under "Bit Manipulation : Concepts" has a typo.
` 1 / 2 = 0; 0 % 2 = 1`
But it should be -
`1 / 2 = 0; 1 % 2 = 1`

#### Screenshots
<img width="396" alt="Screenshot 2022-10-17 at 7 32 42 PM" src="https://user-images.githubusercontent.com/29420165/196197742-651251c1-0b3a-48ff-9037-4b69a0655fbd.png">

#### Additional context
Link to article - https://leetcode.com/explore/learn/card/bit-manipulation/669/bit-manipulation-concepts/4494/

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem.  We appreciate your support!
