### ISSUE TITLE
89. Gray Code

### ISSUE THREAD

**Issue by Andrey-Pavlov** [LeetCode-Feedback/LeetCode-Feedback#9521]
#### Your LeetCode username
Chuxel

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Solution formulas are broken

#### Expected behavior
Show correct formulas

#### Screenshots
![image](https://user-images.githubusercontent.com/7976740/196201500-649f857e-93f0-447c-865d-599a22b0b6ec.png)

#### Additional context
https://leetcode.com/problems/gray-code/solution/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
