### ISSUE TITLE
Always Time Limit Exceeded

### ISSUE THREAD

**Issue by chelsilarious** [LeetCode-Feedback/LeetCode-Feedback#9522]
#### Your LeetCode username

Chelsilarious

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I copied two solutions given by leetcode and two top-voted solutions but every one of them gives time limited exceeded error. The same solution works for my friend on leetcode but just does not work for me.

#### Code you used for Submit/Run operation

```
// Daily Temperatures
class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        res = [0]*len(temperatures)
        stack = []
        for i, temp in enumerate(temperatures):
            while stack and temperatures[stack[-1]]<temp:
                cur = stack.pop()
                res[cur] = i-cur
            stack.append(i)
        return res
```

#### Language used for code

Python

#### Expected behavior

Pass all test cases

**Comment by chelsilarious** [comment]
Always Time Limit Exceeded

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem and found it the Transient server issue. We appreciate your support!
