### ISSUE TITLE
错误代码通过了

### ISSUE THREAD

**Issue by mist1024** [LeetCode-Feedback/LeetCode-Feedback#9523]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看
https://leetcode.cn/problems/replace-elements-with-greatest-element-on-right-side/

**你的 LeetCode 用户名**
[wu-ai-7](https://leetcode.cn/u/wu-ai-7/)

**Bug 类型**
缺少测试用例

**描述**
一个错误的代码通过了，被我自己发觉了
**你使用的语言**
Java

**你提交或者运行的代码**
```java
class Solution {
    public int[] replaceElements(int[] arr) {
        if (arr.length==1){
            return new int[]{-1};
        }
        if (arr.length==2){
            return new int[]{Math.max(arr[0],arr[1]),-1};
        }
        int[] ans=new int[arr.length];
        int max=arr[arr.length-1];
        for (int i=arr.length-2;i>=0; i--){
            max=Math.max(arr[i+1],max);
            ans[i]=max;
        }
        ans[ans.length-1]=-1;
        return ans;
    }
}

```

**期望行为**
错误案例：[17,1]。
答案是错误的，但是通过了
输出
[17,-1]
预期结果
[1,-1]

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
缺少长度为2的数组

**Comment by feiceh** [comment]
已处理，积分奖励已发放～
