### ISSUE TITLE
Missing Test Case - 122. Best Time to Buy and Sell Stock II

### ISSUE THREAD

**Issue by mishazenin** [LeetCode-Feedback/LeetCode-Feedback#9528]
Incorrect Expected!!!

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?

**Comment by mishazenin** [comment]
I'm sorry my mistake i confused between  Best Time to Buy and Sell Stock II and Best Time to Buy and Sell Stock 19.10.2022, 08:58, "stormsunshine" ***@***.***>:
What is the missing test case and what is the code that can get accepted but fails on the test case?
