### ISSUE TITLE
Problem description punctuation issue - 463. Island Perimeter

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#953]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

463. Island Perimeter
https://leetcode.com/problems/island-perimeter/

In general, all problem I could easily read.
However this problem it took 2/3 times read  just to get  towards where to pause in the English description.

English punctuation issue:

"lakes" (water inside that isn't connected to the water around the island)
should be
"lakes" (the water inside isn't connected to the water around the island)

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

The word "that" makes the sentence in problem description not free flowing.
Problem should be unambiguous.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy, 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. Although the previous version was clear, we've updated the statement. We appreciate your support!
