### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by nandanVasistaBH29** [LeetCode-Feedback/LeetCode-Feedback#9530]
#### Your LeetCode username

Nandan Vasista B H
user0738dI

#### Category of the bug
- [ ] Question - https://leetcode.com/problems/find-peak-element/
- [ ] Solution - https://leetcode.com/submissions/detail/825173300/
- [ ] Language- java 
- [ ] Missing Test Cases - [3,4,5,6,1,2]

#### Description of the bug

the ques asks for us to find the peak idx 
so ans should be 3 
its saying the expected output is 5 
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int findPeakElement(int[] arr) {
        int n=arr.length;
        if(n==1) return 0;
        int s=0,e=n-1;
        
        while(s<=e){
            int i=(s+(e-s)/2);
            if(i!=0 && i!=n-1 && arr[i-1]<arr[i] && arr[i]>arr[i+1]){
                return i;
            }
            else if(i!=n-1 && arr[i]<arr[i+1]){
                //ascent the hill
                s=i+1;
            }
            else{
                e=i-1;
            }
        }
        if(arr[n-1]>=arr[0]) return n-1;
        if(arr[0]>=arr[n-1]) return 0;
        return -1;
    }
}
```

#### Language used for code

java

#### Expected behavior

the expected op is not 5 either

#### Screenshots

<img width="1440" alt="Screen Shot 2022-10-18 at 6 37 15 PM" src="https://user-images.githubusercontent.com/108749491/196439258-56c44e84-77e0-44f8-823f-9bd840e0ea3c.png">

**Comment by stormsunshine** [comment]
This test case is indeed a missing test case, since the element at index 0 is obviously not a peak element.

However, could you please check the definition of "peak element"? The first sentence already defines the term "peak element". Why do you think a peak element has to be the maximum element in the array?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by nandanVasistaBH29** [comment]
Thank you
