### ISSUE TITLE
Grabled Solution - 347. Top k Frequent Elements

### ISSUE THREAD

**Issue by ivalkshfoeif** [LeetCode-Feedback/LeetCode-Feedback#9535]
#### Your LeetCode username

[EnjoyLIFE2020](https://leetcode.com/EnjoyLIFE2020/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution is grabled

#### Code you used for Submit/Run operation
No solution available

#### Language used for code
Not applicable

#### Expected behavior

Correct Solution

#### Screenshots

<img width="1002" alt="Screen Shot 2022-10-18 at 5 36 14 PM" src="https://user-images.githubusercontent.com/61750044/196570233-a867d6f7-676d-4c51-856c-3a43303f0630.png">
<img width="819" alt="Screen Shot 2022-10-18 at 5 36 07 PM" src="https://user-images.githubusercontent.com/61750044/196570231-eaecc6c7-858b-4b04-a098-24305f37c84d.png">

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
