### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by OsePedro** [LeetCode-Feedback/LeetCode-Feedback#9536]
#### Your LeetCode username
osemwaro

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When I test the code below on the list of all numbers between -1500 and 1499, inclusive, it claims that my answer is wrong. To double-check this, I wrote [this simple brute-force program](https://gist.github.com/OsePedro/bde3e94791e8b441504179ce82581dca). The brute-force program produces the exact same result as the code below, so it seems that there is a bug in your assessment code. For your convenience, here are the solutions generated by the brute-force program: [bruteForceSolutions.zip](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9816761/bruteForceSolutions.zip) .

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    
    vector<vector<int>> threeSum(vector<int>& nums) {
        sort(nums.begin(),nums.end());
        unordered_map<int,int> firstIndex;
        vector<vector<int>> triplets;
        
        int prevINum=INT_MIN;
        int firstINumTripletI=0;
        
        for(int i=0; i<nums.size(); ++i) {
            int iNum=nums[i];
            if(firstIndex.find(iNum)==firstIndex.end()) {
                firstIndex[iNum]=i;
            }
            
            for(int j=1; j<i; ++j) {
                int jNum = nums[j];
                int kNum = -iNum-jNum;
                if(kNum<nums[0]) {break;}
                
                {
                    auto it = firstIndex.find(kNum);
                    if(it==firstIndex.end() || it->second>=j) {continue;}
                }

                vector<int> triplet({iNum,jNum,kNum});                
                if(!binary_search(triplets.begin()+firstINumTripletI,triplets.end(),triplet)) {
                    if(iNum!=prevINum) {
                        firstINumTripletI=triplets.size();
                        prevINum=iNum;
                    }
                    triplets.push_back(triplet);
                }
            }
        }
        
        return triplets;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The result of testing the code above on test case `[-1500,-1499,...,1499]` should be accepted. At present, the system incorrectly reports "wrong answer". The code passes all of _your_ current tests when I submit it, so it appears that you are not using this test case. You should add this test case and fix your assessment of it.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The code produces the correct answer for that test case. Please use the discussion to debug their solution. We appreciate your support!

**Comment by OsePedro** [comment]
You're missing the point. The code above passes all of your tests, as you can see from the submission detail here: https://leetcode.com/submissions/detail/825654779/. So there are only two possibilities:

1. my code is wrong, but your tests are not comprehensive enough to uncover its flaws; or
2. my code is correct, but there is a bug in your "run example testcases" service.

If (1) is true, then you should add the `[-1500, -1499, -1498, ..., 1499]` test case, so that your system will no longer consider my code to be correct. If (2) is true, then you should find the bug in your "run example testcases" service. In either case, you have an issue that you should fix.

Just to make sure there are no misunderstandings, I have written out the full test case [here](https://gist.github.com/OsePedro/964f24c744264f590bfed83910915a9c), and this is what happens when I run the code above on it:

![Screenshot from 2022-10-21 15-29-51](https://user-images.githubusercontent.com/1922841/197223244-7a9d373e-f06f-47db-a85b-22a9cd42514e.png)

**Comment by OsePedro** [comment]
@LC-Pam did you see my reply? You closed this issue prematurely.
