### ISSUE TITLE
Missing Test Case - 153. Find Minimum in Rotated Sorted Array

### ISSUE THREAD

**Issue by muntakimrafi** [LeetCode-Feedback/LeetCode-Feedback#9537]
#### Your LeetCode username
muntakimrafi

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The evaluator doesn't check whether the time complexity is O(n) or O(log n). Hence the problem can be solved just by return min(nums)

#### Code you used for Submit/Run operation

```
class Solution:
    def findMin(self, nums: List[int]) -> int:
        return min(nums)
```

#### Language used for code

Python3

#### Expected behavior

Expected "time limit exceeded" for submitting a solution that's not O(log n).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
