### ISSUE TITLE
Missing constraints - 380. Insert Delete GetRandom O(1)

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#954]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

380. Insert Delete GetRandom O(1)
https://leetcode.com/problems/insert-delete-getrandom-o1/

Please add constraints to the problem
- How many operations (insert, etc) will be made?
- What the range/domain of these values for insert/ remove? is it -50000 < val < 50000

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Problem must contain constraints so as to Pass in the 1st attempt - with out any issues like time limit exceeded.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
