### ISSUE TITLE
Missing Test Case - 154. Find Minimum in Rotated Sorted Array II

### ISSUE THREAD

**Issue by muntakimrafi** [LeetCode-Feedback/LeetCode-Feedback#9546]
#### Your LeetCode username

muntakimrafi

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The evaluator accepts an answer with the worst time complexity O(n) . The question specifically mentions "You must decrease the overall operation steps as much as possible." However, it can be solved just by a straight return min(nums). 

#### Code you used for Submit/Run operation

```
class Solution:
    def findMin(self, nums: List[int]) -> int:
        return min(nums)
```

#### Language used for code

Python3

#### Expected behavior

Expected "time limit exceeded"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. There is no way to fail this solution. It will always pass. Please learn the optimized solution if you practice for the interview. We appreciate your support!
