### ISSUE TITLE
799. 第K个语法符号 示例标注错误

### ISSUE THREAD

**Issue by MiaoHN** [LeetCode-Feedback/LeetCode-Feedback#9547]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**

星尘

**Bug 类型**

- [ ] 题目

**描述**

[题目链接](https://leetcode.cn/problems/k-th-symbol-in-grammar/)

题目中的行和列的索引都是从1开始，在示例二中，`n=2, k=1` 表示的应该是第2行第1个元素0，题目**示例中下划线标注错误**（见下图）

![image](https://user-images.githubusercontent.com/56884132/196830274-96db9c53-5af9-4f99-8c7a-a1ca9427d65e.png)

**额外的上下文**

题目描述中明确说明了索引从1开始

![image](https://user-images.githubusercontent.com/56884132/196830784-ad320474-6f2d-4260-9f81-27658b2c5dcf.png)

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by feiceh** [comment]
已奖励，请查收。
