### ISSUE TITLE
Missing Test Cases - 608. Tree Node

### ISSUE THREAD

**Issue by ngntrgduc** [LeetCode-Feedback/LeetCode-Feedback#9549]
#### Your LeetCode username

ngntrgduc

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When I submit the MySQL query below, I got the error `Invalid Testcase`:
```
foreign key p_id =  does not exist in the Tree table
```

#### Code you used for Submit/Run operation

```sql
SELECT * FROM Tree
```

#### Language used for code

MySQL

#### Expected behavior

The query `SELECT * FROM Tree` should return the `Tree` table

**Comment by LC-Pam** [comment]
Hi @,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The invalid test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ngntrgduc** [comment]
Ah, when I click `submit` the query, it works, but when I click `run` the query, I get the above error. I'm sorry for my confusion :((.

I think there has a problem with the test cases when I click `run` the query.

**Comment by LC-Pam** [comment]
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
