### ISSUE TITLE
Missing constraints - 75. Sort Colors

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#955]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

75. Sort Colors
https://leetcode.com/problems/sort-colors/

Please add constraints to the problem
- What is the value of Minimum & Maximum value of n? That is how many values can be in array?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Problem must contain constraints so as to Pass in the 1st attempt - with out any issues like time limit exceeded.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've updated the problem. We appreciate your support!
