### ISSUE TITLE
411. Minimum Unique Word Abbreviation

### ISSUE THREAD

**Issue by dskloet** [LeetCode-Feedback/LeetCode-Feedback#9550]
In [Minimum Unique Word Abbreviation](https://leetcode.com/problems/minimum-unique-word-abbreviation/description/), the description doesn't say what to do when the dictionary contains the target word.
In that case it's impossible to find an abbreviation that doesn't match any word in the dictionary because the target word is itself in the dictionary.

When providing this as a test case, it says "Expected: null" but it's not possible to return null when the return value has to be a string. (At least not in C++)

The test cases do not contain such an input because dealing with this case is not required to pass all test cases.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to fixed the validator and the constraints. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
