### ISSUE TITLE
Missing Test Case - 300. Longest Increasing Subsequence

### ISSUE THREAD

**Issue by Shresth500** [LeetCode-Feedback/LeetCode-Feedback#9553]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Shresth500** [comment]
This code is in C++ . Topic is Dynamic Algorithm

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
