### ISSUE TITLE
Problem Follow up description issue - 75. Sort Colors

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#956]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

75. Sort Colors
https://leetcode.com/problems/sort-colors/

Problem description explans the logic of solution in its "Follow up" part.

Please remove the 1st part of "Follow up" that starts with "A rather straight forward..."
But retain the 2nd part of "Follow up"

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Here problem gives out hints for solution in the "Follow up" part of the question.
A problem should be a problem, not the solution embedded in it - without any user request (Hints).
If problem explains how to solve, then where is the "problem" to "solve"?

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
