### ISSUE TITLE
Missing Test Case - 220. Contains Duplicate III

### ISSUE THREAD

**Issue by 3multid** [LeetCode-Feedback/LeetCode-Feedback#9564]
#### Your LeetCode username

3multid

#### Category of the bug
- [ ] Missing Test Cases

#### Description of the bug

I found a testcase that rejects a previously accepted submission.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def containsNearbyAlmostDuplicate(self, nums, k, t):
        """
        :type nums: List[int]
        :type k: int
        :type t: int
        :rtype: bool
        """
        def getID(num,t):
            if t == 0:
                return num
            return num//t
        record = {}
        L = len(nums)
        for i in range(L):
            ID = getID(nums[i],t)
            if ID in record:
                return True
            elif ID-1 in record:
                if abs(record[ID-1] - nums[i])<=t:
                    return True
            elif ID+1 in record:
                if abs(record[ID+1] - nums[i])<=t:
                    return True
            record[ID] = nums[i]
            if i >= k:
                toRemove = getID(nums[i-k],t)
                record.pop(toRemove)
        return False
```

#### Language used for code

Python

#### Expected behavior

This code is from a sample submission, but when I tried this with testcase "nums = [7, 0, 4], indexDiff = 2, valueDiff = 3", it got "Wrong Answer" (returned "False" instead of "True").

#### Screenshots

![image](https://user-images.githubusercontent.com/45973506/197176512-a795633b-d68b-4b15-a0f4-3c7598d07e97.png)
![image](https://user-images.githubusercontent.com/45973506/197176976-abbc46be-095a-4af2-b0ac-558a95f21512.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
