### ISSUE TITLE
Missing Test Case - 860. Lemonade Change

### ISSUE THREAD

**Issue by sad-pancake** [LeetCode-Feedback/LeetCode-Feedback#9565]
#### Your LeetCode username
user8588WU

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
When using short instead of int to count the bills the code can be submitted successfully even though it should encounter overflow.

#### Code you used for Submit/Run operation
```
class Solution {
  public boolean lemonadeChange(int[] bills) {
      short five = 0, ten = 0;
      for (int bill: bills) {
          if (bill == 5)
              five++;
          else if (bill == 10) {
              if (five == 0) return false;
              five--;
              ten++;
          } else {
              if (five > 0 && ten > 0) {
                  five--;
                  ten--;
              } else if (five >= 3) {
                  five -= 3;
              } else {
                  return false;
              }
          }
      }

      return true;
  }
}
```

#### Language used for code

JAVA

#### Expected behavior

The submission should fail on a testcase where first 33k bills are 5$ and last one is 20$.

#### Additional context

The constraints specify the number of transactions as <=10^5
As such using short to count the number of bills we have should lead to overflow and wrong results.
Currently this seems not to be the case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Short isn't a very popular datatype, and this doesn't seem to be a very generalized error-prone test case, we decided not to add it. We appreciate your support!
