### ISSUE TITLE
Typo in question 744. Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by Heidar-An** [LeetCode-Feedback/LeetCode-Feedback#9567]
#### Your LeetCode username

HDawg132

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

The question has two typos: should say "lexographically"

#### Screenshots

<img width="520" alt="image" src="https://user-images.githubusercontent.com/74025356/197217116-09be2c34-8f7b-4513-8d7a-01811b62700a.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
