### ISSUE TITLE
Missing Test cases - 724. Find Pivot Index

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#957]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

724. Find Pivot Index
https://leetcode.com/problems/find-pivot-index/submissions/

Goto https://leetcode.com/submissions/detail/391250996/
click on sample 84 ms submission solution in the top graph

Provide below test case INPUTs

    input   [0]		expect  0		actual  -1
    input   [1]		expect  0		actual  -1
    input   [9]		expect  0		actual  -1
    input   [-1]		expect  0		actual  -1
    input   [-2]		expect  0		actual  -1
    input   [-3]		expect  0		actual  -1

Expected is 0
But the actuals come out as -1

All above test cases, satisfy the problem constraints:
      The length of nums will be in the range [0, 10000].
      Each element nums[i] will be an integer in the range [-1000, 1000].

Please add above test cases to the problem.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Looks like, incomplete solutions are accepted.
Problem must test for all cases.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy, 

After reviewing your code and suggested test cases, the code was accepted and the test cases you suggested were tested for. 

For inputs,
[0]
[1]
[9]
[-1]
[-2]
[-3]
the output and expected are both 0. 

https://leetcode.com/submissions/detail/393893329/
