### ISSUE TITLE
Elixir Solution - 1456. Maximum Number of Vowels in a Substring of Given Length

### ISSUE THREAD

**Issue by Defman21** [LeetCode-Feedback/LeetCode-Feedback#9571]
#### Your LeetCode username

Defman21

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

It's not possible to submit an Elixir solution for this problem.

#### Code you used for Submit/Run operation

```elixir
defmodule Leetcode.MaxVowels.Solution do
  @vowels MapSet.new(~w(a e i o u))

  def solution(str, k) do
    find_max(String.graphemes(str), k, 0)
  end

  def find_max([], k, k), do: k
  def find_max([], _, max), do: max

  def find_max([_|rest] = str, k, max) do
    find_max(
      rest,
      k,
      max(max, Enum.take(str, k) |> Enum.count(&(MapSet.member?(@vowels, &1))))
    )
  end
end

```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
