### ISSUE TITLE
Missing Test Case - 443. String Compression

### ISSUE THREAD

**Issue by Nilanshuyadav** [LeetCode-Feedback/LeetCode-Feedback#9572]
#### Your LeetCode username
Nilanshu_yadav08

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The Question is Missing a Testcase : 
The code below gets submitted , but still gives a wrong result for -> ["A"].
The code is giving an output -> [ ],
but the correct output should be -> ["A"]

It will give the wrong result for any Testcase ending with "A". but still got submitted. 

#### Code you used for Submit/Run operation

```
//443. String Compression
class Solution {
public:
    int compress(vector<char>& chars) {
        
        chars.push_back('A');
        int freq = 0 , n = chars.size() , prevInd = 0;
        char prev = chars[0];
        
        for(int i=0;i<n;i++)
        {
            if(chars[i] != prev)
            {
                chars[prevInd] = prev;
                prevInd++;
                if(freq != 1)
                {
                    string freqCopy = to_string(freq);
                    for(auto it:freqCopy)
                    {
                        chars[prevInd] = it;
                        prevInd++;
                    }
                }                
                prev = chars[i];
                freq = 1;
            }
            else
                freq++;
        }
        chars.pop_back();
        return prevInd;
        
    }
};
```

#### Language used for code
C++

#### Expected behavior
The correct output for the testcase -> ["A"] 
, should be ["A"]
, instead of -> [ ]

#### Screenshots
screenshot of wrong result of testcase : 
![leetcode_bug1](https://user-images.githubusercontent.com/91049897/197271834-d30e1de8-94d2-46d6-83ad-677055d89849.png)

screenshot of code getting accepted : 
![leetcode_bug2](https://user-images.githubusercontent.com/91049897/197271941-ba0ec76f-e417-47aa-9f86-b0e08011db08.png)

#### Additional context
I believe, test cases with similar strings, ending with uppercase english alphabet, must be added to this question.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
