### ISSUE TITLE
A follow-up Requirement Should be Added - 1508. Range Sum of Sorted Subarray Sums

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#9574]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The brute force with O(n^2logn) time complexity can be accepted now. On the one hand, if this problem is used in a real interview, the expected solution must be using binary search and prefix sum, and the interviewee who can only write brute force to solve this problem will not pass the interview. On the other hand, as the second problem of a weekly contest, the difficulty of brute force is not enough to be marked as "Medium". So a follow-up requirement should be added: 
Can you solve this problem in less than O(n^2) time complexity?

Code you used for Submit/Run operation

The time complexity of the code below is O(n^2logn)
```
class Solution:
    def rangeSum(self, nums: List[int], n: int, left: int, right: int) -> int:

        res = []
        for l in range(len(nums)):
            cur = nums[l]
            res.append(cur)
            for r in range(l+1,len(nums)):
                cur+=nums[r]
                res.append(cur)
        return sum(sorted(res)[left-1:right])%(10**9+7)
```

The time complexity of the code below is O(nlogS), S=sum(nums)
```
class Solution:
    def rangeSum(self, nums: List[int], n: int, left: int, right: int) -> int:

        pre = [0]+nums[:]
        for j in range(1,n+1):
            pre[j]+=pre[j-1]
        ppre = [0]+pre[1:]
        for j in range(1,n+1):
            ppre[j]+=ppre[j-1]

        def getcnt(x):
            cnt = 0
            j = 1
            for i in range(n):
                while j<=n and pre[j]-pre[i]<=x:
                    j+=1
                j-=1
                cnt+=j-i
            return cnt

        def binsearch(k):
            l = 0
            r = pre[-1]
            while l<r:
                m = (l+r)//2
                cnt = getcnt(m)
                if cnt<k:
                    l = m+1
                else:
                    r = m
            return l

        def getsm(k):
            cur = binsearch(k)
            ans = 0
            cnt = 0
            j = 1
            for i in range(n):
                while j<=n and pre[j]-pre[i]<cur:
                    j+=1
                j-=1
                ans += ppre[j]-ppre[i]-pre[i]*(j-i)
                cnt += j-i
            ans += cur*(k-cnt)
            return ans

        return (getsm(right)-getsm(left-1))%(10**9+7)
```

Language used for code
Python3

Expected behavior
A follow-up requirement should be added:
Can you solve this problem in less than O(n^2) time complexity?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution mentioned is out of the scope and it is low probability to be required in an interview. The problem was from OA and the brute force did pass. We appreciate your support!
