### ISSUE TITLE
Missing Test Case - 1246. Palindrome Removal

### ISSUE THREAD

**Issue by u10000129** [LeetCode-Feedback/LeetCode-Feedback#9578]
#### Your LeetCode username

[cheupei(Ping-Han Chiang)](https://leetcode.com/cheupei/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case. My **accepted** code gets wrong answer on below test case.
`[1,4,1,1,2,3,2,1]`

#### Code you used for Submit/Run operation

```python
class Solution:
    def minimumMoves(self, arr: List[int]) -> int:
        @lru_cache(None)
        def dp(i, j):
            if i >= j:
                return 1

            if arr[i] == arr[j]:
                return dp(i + 1, j - 1)
            
            res = float('inf')
            for k in range(i, j):
                if arr[k] == arr[i] or arr[k + 1] == arr[j]:
                    res = min(res, dp(i, k) + dp(k + 1, j))
            return res

        return dp(0, len(arr) - 1)
```

#### Language used for code

Python3

#### Expected behavior

The expected answer is 2, while my **accepted** submission returns 3.

#### Screenshots

![螢幕擷取畫面 2022-10-22 144118](https://user-images.githubusercontent.com/18047285/197324546-d082b977-17ad-4f92-bb8e-debc8031e74c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
