### ISSUE TITLE
Bit manipulation: Base 7

### ISSUE THREAD

**Issue by igordptx** [LeetCode-Feedback/LeetCode-Feedback#9579]
Answering the bit manipulation convert to base 7 question raises a runtime error even though the solution is correct. I tested it on my personal PC compiler and it works fine.

#### Your LeetCode username
igordptx

#### Category of the bug
- [ ] Solution
- [ ] Language

#### Description of the bug
Answering the bit manipulation convert to base 7 question raises a runtime error even though the solution is correct. I tested it on my personal PC compiler and it works fine.

#### Code you used for Submit/Run operation
char * convertToBase7(int num){
    int arr[100] = {0};
    int res      = 0;
    int i = 0;
    while(num  > 0){
        res = num % 7; 
        num = num / 7;
        arr[i] = res;
        i++;
    }
    char *s = malloc(i);
    for(int j = 0 ; j < i ; j++){
        printf("%d %d\n",j,i);
        s[j] = (char)(arr[j] + '0');
    }
    printf("%s\n",s);
    return s;
}
```

#### Language used for code
C


#### Expected behavior
I didn't expect any memory issues. And there were.





#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
