### ISSUE TITLE
max version length not specified in https://leetcode.com/problems/compare-version-numbers/

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#958]
#### Your LeetCode username 
chrisgriffin

#### Category of the bug
- [ ] Question

#### Description of the bug
The problem statement does not mention that the individual version will always fit inside an `int` e.g "8990890890809.0" does not occur in any of the test cases.

Either the problem description should be updated to clearly mention this or the test case needs to be updated to include version number that does not fit inside an `integer` or `long` data type.

#### Code you used for Submit/Run operation

```
public int compareVersion(String version1, String version2) {
        String[] levels1 = version1.split("\\.");
        String[] levels2 = version2.split("\\.");

        int length = Math.max(levels1.length, levels2.length);
        for (int i=0; i<length; i++) {
            Integer v1 = i < levels1.length ? Integer.parseInt(levels1[i]) : 0;
            Integer v2 = i < levels2.length ? Integer.parseInt(levels2[i]) : 0;
            int compare = v1.compareTo(v2);
            if (compare != 0) {
                return compare;
            }
        }
        return 0;
    }
```

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem and updated the problem description. We appreciate your support!

**Comment by snehasishroy** [comment]
Thank you for fixing this @lc-kay , wanted to confirm whether I am eligible for getting 100 leetcoins as per https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now! ?

**Comment by lc-kay** [comment]
Hi @snehasishroy, 
This problem was updated based on another user's report prior to yours, and we only assign points to the 1st reported user. I apologize for not being clear in my last comment. Still, thank you for your support and for using LeetCode!
