### ISSUE TITLE
Missing Test Case - 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by rbrn1999** [LeetCode-Feedback/LeetCode-Feedback#9582]
#### Your LeetCode username
ianliu1015

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Solution with O(n) complexity actually passes while the descirption asked for a O(logn) algorithm.

#### Code you used for Submit/Run operation

```
class Solution:
    def search(self, nums: List[int], target: int) -> int:
    
        smaller = False
        prev = float('-inf')
        for i in range(len(nums)):
            if nums[i] == target:
                return i
    
            if smaller and nums[i] < prev:
                return -1
            if nums[i] < target:
                smaller = True
            prev = nums[i]
                
        return -1
```

#### Language used for code
Python3

#### Expected behavior
Time Limit Exceeded

#### Screenshots

![Screenshot](https://user-images.githubusercontent.com/41038139/197346785-ebd402bc-e868-4728-8b6b-eea88996c7bf.jpg)

**Comment by LC-Pam** [comment]
Thank you for your time.  We cannot prevent n solutions.  We appreciate your support!
