### ISSUE TITLE
Typo in set mismatch official solution

### ISSUE THREAD

**Issue by lxylxy123456** [LeetCode-Feedback/LeetCode-Feedback#9586]
#### Your LeetCode username
lxylxy123456

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [official solution](https://leetcode.com/problems/set-mismatch/solutions/127759/set-mismatch/) approach 7 paragraph 2, it says:
![图片](https://user-images.githubusercontent.com/9337403/197367004-b68c7787-956d-4766-877b-069bc4cf4ddf.png)

It looks like a math equation saying "x to the power of y". However, it should be `x^y`, meaning "x XOR y".

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior

![图片](https://user-images.githubusercontent.com/9337403/197367039-8a20bad6-1b0a-4806-a39b-3b46b1142b81.png)

#### Screenshots
See above

#### Additional context
N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
