### ISSUE TITLE
Missing Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by FAE-Sonata** [LeetCode-Feedback/LeetCode-Feedback#9587]
#### Your LeetCode username
FAE-Sonata

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Strings that are permutations of one another (have the same set of characters, and the same count for each unique character), should be checked in a testcase.

One such example is `"abbott"` and `"ttobba"`

#### Code you used for Submit/Run operation

```
class Solution:
    def numDistinct(self, s: str, t: str) -> int:
        if s == t:
            return 1
        M = len(s); N = len(t)
        if M < N:
            return 0
        s_count = Counter(s); t_count = Counter(t)
        has_identical_count = True
        for letter in t_count:
            if not(letter in s_count) or s_count[letter] < t_count[letter]:
                return 0
            if s_count[letter] > t_count[letter]:
                has_identical_count = False
        if has_identical_count:
            return 1
        tuples = {}#; res = 0
        def dfs(j, k):
            if k >= N:
                return 1
            if j >= M:
                return 0
            if (j,k) in tuples:
                return tuples[(j,k)]
            if s[j] == t[k]:
                tuples[(j,k)] = dfs(j+1, k+1) + dfs(j+1, k)
            else:
                tuples[(j,k)] = dfs(j+1, k)
            return tuples[(j,k)]
        dfs(0,0)
        return tuples[(0,0)]
```

#### Language used for code
Python

#### Expected behavior
This submission should not have passed owing due to the permutations issue (expected return is 0); however, due to the `if has_identical_count: return 1` clause on lines 15 and 16, _any_ permutation will return 1 (regardless whether the order is correct)

#### Screenshots

N/A

#### Additional context

N/A; this is quite simple as is

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
