### ISSUE TITLE
There is a worng word in the answer of 151. Reverse Words in a String that provided by Leetcode official

### ISSUE THREAD

**Issue by EchoSerendipity** [LeetCode-Feedback/LeetCode-Feedback#9592]
#### Category of the bug
- [x] Language

#### Screenshots
![1666528792196](https://user-images.githubusercontent.com/66522154/197392812-4ec2c028-c16a-4446-a320-7d374342ace5.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
