### ISSUE TITLE
Invalid Test Case - 1239. Maximum Length of a Concatenated String with Unique Characters

### ISSUE THREAD

**Issue by billafy** [LeetCode-Feedback/LeetCode-Feedback#9599]
#### Your LeetCode username
ytarkar138

#### Category of the bug
- [ ] Invalid Test Case

#### Description of the bug
The question says that it will have input with unique characters only but even after passing input with duplicate characters such as 'aaabc' where 'a' is repeated, the test case runs without throwing any Invalid Test Case error.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
C++

#### Expected behavior
The test case with duplicate characters should not be accepted as a valid input.

**Comment by billafy** [comment]
The code and language you submitted to reach this result.
The code does not matter here actually.
C++

The test case that you use.
'aaabc'

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code  you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by billafy** [comment]
`
class Solution {
public: 
    int rec(vector<string>& arr, int i, unordered_set<int> s) {
        if(i == arr.size()) 
            return 0;
        int res = rec(arr, i + 1, s);
        bool flag = true;
        for(auto c: arr[i]) {
            if(s.count(c)) {
                flag = false;
                break;
            }
            s.insert(c);
        }
        if(flag) 
            res = max(res, (int) arr[i].size() + rec(arr, i + 1, s));
        return res;
    }
    int maxLength(vector<string>& arr) {
        return rec(arr, 0, {});    
    }
};
`

**Comment by billafy** [comment]
`class Solution {
public: 
    int rec(vector<string>& arr, int i, unordered_set<int> s) {
        if(i == arr.size()) 
            return 0;
        int res = rec(arr, i + 1, s);
        bool flag = true;
        for(auto c: arr[i]) {
            if(s.count(c)) {
                flag = false;
                break;
            }
            s.insert(c);
        }
        if(flag) 
            res = max(res, (int) arr[i].size() + rec(arr, i + 1, s));
        return res;
    }
    int maxLength(vector<string>& arr) {
        return rec(arr, 0, {});    
    }
};`

**Comment by billafy** [comment]
The code you submitted to reach this result.
```
class Solution {
public: 
    int rec(vector<string>& arr, int i, unordered_set<int> s) {
        if(i == arr.size()) 
            return 0;
        int res = rec(arr, i + 1, s);
        bool flag = true;
        for(auto c: arr[i]) {
            if(s.count(c)) {
                flag = false;
                break;
            }
            s.insert(c);
        }
        if(flag) 
            res = max(res, (int) arr[i].size() + rec(arr, i + 1, s));
        return res;
    }
    int maxLength(vector<string>& arr) {
        return rec(arr, 0, {});    
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. The test case ['aaabc'] is not a valid value of type list<string>.  We appreciate your support!
<img width="377" alt="Screen Shot 2022-10-29 at 12 32 55 AM" src="https://user-images.githubusercontent.com/103138242/198687398-eeea3164-6a3f-43e6-a74f-238209b0f126.png">
