### ISSUE TITLE
Data type can be used as a variable

### ISSUE THREAD

**Issue by SushilG96** [LeetCode-Feedback/LeetCode-Feedback#960]
#### Your LeetCode username

SushilG96

#### Category of the bug
- [290. Word Pattern ] Question
- [ ] Solution
- [ python] Language

#### Description of the bug

The first line of the question stated that variable str that is a string, So in python there str i.e string or text is a datatype so we cant use it as a Variable.
```
Given a pattern and a string str, find if str follows the same pattern. 
```

#### Code you used for Submit/Run operation

```

class Solution:
    def wordPattern(self, pattern: str, str: str) -> bool:
        s = list(map(str, str.split()))
```

```
The issue at the run time.

TypeError: 'str' object is not callable
    s = list(map(str, str.split()))
Line 3 in wordPattern (Solution.py)
    ret = Solution().wordPattern(param_1, param_2)
Line 36 in _driver (Solution.py)
    _driver()
Line 47 in <module> (Solution.py)

```
#### Language used for code

Python3 

#### Expected behavior

Use a different variable

**Comment by caoxingdong** [comment]
you can simply modify the function definition to
    def wordPattern(self, pattern: str, s: str) -> bool:

**Comment by lc-kay** [comment]
Hi @SushilG96 

Does the solution @caoxingdong suggested work for you? If not, please let me know.

**Comment by lc-kay** [comment]
Hi @SushilG96  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
