### ISSUE TITLE
Missing Test Case - 1373. Maximum Sum BST in Binary Tree

### ISSUE THREAD

**Issue by girish4016** [LeetCode-Feedback/LeetCode-Feedback#9602]
#### Your LeetCode username

 girishbasandai1

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
leetcode problem-1373 - maximum sum bst in a binary tree
there is a problem with the solution of this question , on test case 53  maximum sum should be 26 but is shown in solution to be 25.

#### Code you used for Submit/Run operation

```
int getsum(TreeNode* root, vector<int> &v, vector<int> &sv, int sum)
{
    if(!root)
        return 0;
    
    int lsum = getsum(root->left,v,sv,sum);
    
    int rsum = getsum(root->right, v, sv, sum);
    
    
    if((root->left && root->left->val >= root->val) || (root->right &&  
       root->right->val <= root->val) )
    {
        return -1;
    }
    else if(lsum==-1 || rsum==-1)
        return -1;
    else
    {
        sv.push_back(lsum+rsum+root->val);
        return lsum+rsum+root->val;
    } 
    
    
}
class Solution {
public:
    int maxSumBST(TreeNode* root) {
        
        int sum = 0;
        vector<int>v;
        vector<int> sv;
        
        getsum ( root, v, sv, sum);
        
        // sort(sv.begin(), sv.end());
        int max = 0;
        
        for(int i=0; i<sv.size(); i++)
            if(sv[i]>max)max=sv[i];
        //     for(int i=0; i<sv.size(); i++)
        // cout<<sv[i]<<" ";
        // sum = sv[sv.size()-1];
        
        return max;
        
    }
};
```

#### Language used for code
 C++

#### Expected behavior

according to the question maximum bst can contain the root node as well , but on tc 53 the expected output is not as it should be . it should be 26 , i.e. 20+10-5+1 = 26 whereas it is 20+10-5 = 25 which is obviously smaller then 26.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
