### ISSUE TITLE
Missing Test Case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by minervaeu** [LeetCode-Feedback/LeetCode-Feedback#9604]
#### Your LeetCode username
minervaeu

#### Category of the bug
- [ x ] Solution

#### Description of the bug

I tested my solution in a JSFiddle to make sure it works and it is fine.
The submission:
`Input
[1,2]
Output
true
Expected
false`
is not accepted, but i think it must work. 

#### Code you used for Submit/Run operation
`var isPalindrome = function(head) {
  
    let result = false;
    let x = 0;
    let y = head.length;
    
    if(head.length === 2){
        if(head[0] !== head[1]){
            return false;
        } else return true;
    };
    
    for(x; x < head.length; x++){
        if(head[x] === head[y]){
            result = true;
            y--;
        } else {
            return false;
        };
    };
    return true;
    
};`

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Javascript

#### Expected behavior
My code for the head [1,2] must return "false" as it does in a JSFiddle Playground where i proofed it, but in the submission it returns true which is for sure not the right answer.

#### Screenshots
![Screenshot at 2022-10-24 09-51-54](https://user-images.githubusercontent.com/115371783/197475452-1f3efac0-0790-4907-846f-4580a5f27bef.png)

#### Additional context
-

Thanks for your time,
Greetings from Vienna

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by minervaeu** [comment]
With pleasure, but where do i get the code submission link? Sorry, i'm new @leetcode...

Greets

**Comment by minervaeu** [comment]
https://leetcode.com/problems/palindrome-linked-list/

Mean this?

**Comment by minervaeu** [comment]
I also reproduced it in the leetcode playground and my code works fine there for the problem (head=[1,2]) with the error....

**Comment by LC-Pam** [comment]
![Uploading Screen Shot 2022-10-28 at 12.01.20 AM.png…]()

**Comment by LC-Pam** [comment]
<img width="498" alt="Screen Shot 2022-10-28 at 12 01 20 AM" src="https://user-images.githubusercontent.com/103138242/198340997-9f7ab853-14c3-4029-869b-40ffe4b9680d.png">

**Comment by minervaeu** [comment]
Thanks for reply, here it is: [https://leetcode.com/submissions/detail/829136207/](url)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
