### ISSUE TITLE
Missing Test Case - 566. Reshape the Matrix

### ISSUE THREAD

**Issue by HarshSriv** [LeetCode-Feedback/LeetCode-Feedback#9605]
#### Your LeetCode username
 harshsrivastava041

#### Category of the bug
- [x] Question 
- [x] Solution

#### Description of the bug
 a given test case
Input: mat = [[1,2],[3,4]], r = 2, c = 4
Output: [[1,2],[3,4]]

here value of c must be 2 for resulting given output ->  [[1,2],[3,4]]
else 2x4 matrix contains 8 elements even then , vector have dynamic size it should came like this [[1,2,3,4],[ ]] or simply [[1,2,3,4]].

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Input: mat = [[1,2],[3,4]], r = 2, c = 4
Output: [[1,2],[3,4]]

here value of c must be 2 for resulting given output ->  [[1,2],[3,4]]
else 2x4 matrix contains 8 elements even then , vector have dynamic size it should came like this [[1,2,3,4],[ ]] or simply [[1,2,3,4]].

#### Screenshots

![image](https://user-images.githubusercontent.com/89657108/197534461-778b3e5e-c14c-4fb8-840b-d43494ece2a4.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The example is correct. The last paragraph said that you should return the original matrix if the reshape is impossible.
Please read the last paragraph again.
We appreciate your support!
