### ISSUE TITLE
Minor Typo in Question 26's Solution

### ISSUE THREAD

**Issue by Brandon-Gui123** [LeetCode-Feedback/LeetCode-Feedback#9607]
#### Your LeetCode username
Brandon_Gui123

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the [solution](https://leetcode.com/problems/remove-duplicates-from-sorted-array/solution/), there is a typo regarding the values at which `startIndex` and `i` begin.

Right at the beginning of the "Algorithm" section for "Approach 1: Two indexes approach", the solution says to start both `startIndex` and `i` at `0`.
![image](https://user-images.githubusercontent.com/34325463/197551047-5092addc-0073-44aa-94cb-9c9ce63d1b12.png)

However, in the code implementation below, it seems that `insertIndex` and `i` both start at `1` and not `0`. The image below shows the implementation done in C#. But I found out that all the other implementations start their indices at 1.
![image](https://user-images.githubusercontent.com/34325463/197551313-194436b6-1810-4336-9ef2-9e7a42b615a4.png)

The correct statement would be to say, we start `startIndex` and `i` at `1`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will used your feedback to update the problem and we think the solution looks a little over-complex. It's unnecessary to update num[insertIndex].  We appreciate your support!
