### ISSUE TITLE
Incorrect expected result for test case #77 for problem #1003 "Check If Word Is Valid After Substitutions"

### ISSUE THREAD

**Issue by michaelkr** [LeetCode-Feedback/LeetCode-Feedback#961]
#### Your LeetCode username

meanfreepath

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language

#### Description of the bug

For problem #1003 "Check If Word Is Valid After Substitutions", there is an incorrect result as saved for a test case. The test case is for the string "aabcbabcc".

The rules given by the problem state:  

1. An empty string "" is valid.
2. The string "abc" is also valid.
3. Any string in the form "a" + str + "bc", "ab" + str + "c", str + "abc" or "abc" + str where str is a valid string is also considered a valid string.

In the group of submit tests, the test "aabcbabcc" is provided, with an expected value of TRUE. However, this string does NOT fit the definition of valid above. By those rules, the only possible splits are:

      "a" + "a" + "bc" + "babcc"   (which fails because the second "a" and the "babcc" are not a valid string)
      OR 
      "a" + "abcba" + "bc" + "c"   (which fails because "abcba" and "c" are not valid strings)

If the 3rd rule above included the following, it would be valid: "also accepted are strings of the form "a" + str + "b" + str + "c". ". But since that rule is not included, any strings of that form must be rejected as false, not true.

Many submissions are based on a stack approach similar to parenthesis matching - all of those solutions will treat this example as true (valid), when they should return false for this example. Because of this, there is a large number of accepted submissions that should be rejected.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
    bool isvalid(const string &s, int l, int r) {
        
        // the empty string is a solution
        if (r-l == 0)
            return true;

        // any strings like "a" alone, or "ab" alone, are invalid. If they have a matching "bc" or "c" later in the string
        // it would have been handled by the recursive calls below
        if (r-l < 3)
            return false;
        
        bool retval = true;
        
        // go through the valid cases, one by one - as ordered in the 
        // rules. Note "abc" will be accepted by all of these.
        // If any of them accept, then we return true:
        
        // check for "a" + str + "bc"
        if (s[l+0] == 'a' and s[r-2] == 'b' and s[r-1] == 'c') {
            retval = isvalid(s, l+1, r-2);
            if (retval)
                return true;
        }
        // check for "ab" + str + "c"
        if (s[l+0] == 'a' and s[l+1] == 'b' and s[r-1] == 'c') {
            retval = isvalid(s, l+2, r-1);
            if (retval)
                return true;
        }
        // check for str + "abc"
        if (s[r-3] == 'a' and s[r-2] == 'b' and s[r-1] == 'c') {
            retval = isvalid(s, l, r-3);
            if (retval)
                return true;
        }
        // check for "abc" + str
        if (s[l+0] == 'a' and s[l+1] == 'b' and s[l+2] == 'c') {
            retval = isvalid(s, l+3, r);
            if (retval)
                return true;
        }
        
        // Nothing accepted, return invalid:
        return false;
    
    }

    bool isValid(string s) {
        int leftidx = 0;
        int rightidx = s.size();
        
        // do this by indices to prevent copies of the string:
        return isvalid(s, leftidx, rightidx);
        
    }
};
```

#### Expected behavior

During submit, test case "aabcbabcc" should produce a FALSE return value - your submit process expects a value of TRUE.

#### Screenshots

.
![Screen Shot 2020-09-07 at 4 50 25 PM](https://user-images.githubusercontent.com/6100686/92416188-4c585800-f12a-11ea-8a95-ec5ccd2e6edc.png)

**Comment by lc-kay** [comment]
Hi @michaelkr, 

Can you provide the link to your submission details? I am trying to verify your code as the first step to solve this issue. Thank you!

**Comment by michaelkr** [comment]
@lc-kay I'm not sure I understand - I provided my code above in the report (above). And you have my leetcode user name. Is there another link I can give you that may help?

**Comment by lc-kay** [comment]
@michaelkr I was able to check your code. I've relayed this issue to our team to investigate. Thank you for bringing this to our attention.

**Comment by lc-kay** [comment]
Hi @michaelkr 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
