### ISSUE TITLE
Missing Test Case - 231. Power of Two

### ISSUE THREAD

**Issue by vaibhav-sahu** [LeetCode-Feedback/LeetCode-Feedback#9613]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isPowerOfTwo(int n) {
        for (int i =0; i<=30; i++){
            int a = pow(2,i);
            if (n == a){
                return true;
            }
        }
        return false;
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
