### ISSUE TITLE
Missing Test Case - 1971. Find if Path Exists in Graph

### ISSUE THREAD

**Issue by FrancisBrokering** [LeetCode-Feedback/LeetCode-Feedback#9614]
#### Your LeetCode username

fbrokeri

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Found a bug where you can pass all test cases with time complexity O(V) where V is the number of vertices. This can be achieved by traversing the list of vertices from both directions. This method depends on the order of vertices stored in the input list. So there should be a test case that prevents this method from passing.

#### Code you used for Submit/Run operation

```
// Find if Path Exists in Graph
class Solution:
    def validPath(self, n: int, edges: List[List[int]], source: int, destination: int) -> bool:
        can_reach_from_source = {source}
        can_reach_from_destination = {destination}
                
        for v1, v2 in edges:
            if v1 in can_reach_from_source or v2 in can_reach_from_source:
                can_reach_from_source.add(v1)
                can_reach_from_source.add(v2)
                
        for v1, v2 in edges[::-1]:
            if v1 in can_reach_from_destination or v2 in can_reach_from_destination:
                can_reach_from_destination.add(v1)
                can_reach_from_destination.add(v2)
                
        return can_reach_from_source & can_reach_from_destination
```

#### Language used for code

Python3

#### Expected behavior

In my code, I use two for loops. The first loop adds every node that can be reached by the source to a set(). The second loop adds every node that can be reached from the destination to a different set().
But depending on the order of how the nodes are stored in the input list, simply traversing the input list in one loop to find which nodes can be reached by the source/destination node is not possible. 

#### Screenshots

<img width="824" alt="Screen Shot 2022-10-24 at 7 55 10 PM" src="https://user-images.githubusercontent.com/43657864/197671353-6f3e83af-a3b9-4868-92e2-9d4c8da89e40.png">

#### Additional context

This test case inputs should be added.
```
  6
  [[0,1],[2,3],[4,5],[3,4],[1,2]]
  0
  5
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
