### ISSUE TITLE
Wrong Output Inspite Giving The Right Solution in Power Two, Power Four

### ISSUE THREAD

**Issue by sah1lga1kwad** [LeetCode-Feedback/LeetCode-Feedback#9616]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
import "math"

var a int = 0
func isPowerOfTwo(n int) bool {
 
    y := powInt(2,a)
    if n == y || n == 1{
        return true
    } else {
        if a > 31 {
            return false
        } else {
            a++
            isPowerOfTwo(n)
        }
    }
    return isPowerOfTwo(n)
}

func powInt(x, y int) int {
    return int(math.Pow(float64(x), float64(y)))
}
```

#### Screenshots

![Screenshot from 2022-10-25 13-49-58](https://user-images.githubusercontent.com/113647938/197722094-9b020297-a00d-4f07-a860-e40595b6dbe9.png)
![Screenshot from 2022-10-25 13-49-58](https://user-images.githubusercontent.com/113647938/197722131-59b3d81e-4649-4df4-a524-adf2e72ef99a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
