### ISSUE TITLE
Miss case for 1576. Replace All ?'s to Avoid Consecutive Repeating Characters

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#962]
#### Your LeetCode username

ddoudle

#### Category of the bug
- [ ] Question

#### Description of the bug

This solution passes all cases but can't pass this one: "b?a"

#### Code you used for Submit/Run operation

```
class Solution:
    def modifyString(self, s: str) -> str:
        cur = 'a'
        n = len(s)
        res = ['*' for _ in range(n)]
        
        for i in range(len(s)):
            if s[i] == '?':
                # print(res, cur, res[i-1])
                
                if i > 0:
                    if cur == res[i-1]:
                        cur = chr(ord(cur) + 1)
                if i < n - 1:
                    if cur == s[i+1]:
                        cur = chr(ord(cur) + 1)
                
                if cur > 'z':
                    cur = 'a'
                    
                res[i] = cur
            else:
                res[i] = s[i]
        
        return ''.join(res)
```

#### Language used for code
Python3

#### Expected behavior

Expected: "bca"
Output: "bba"

**Comment by lc-kay** [comment]
Hi @caoxingdong , 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @caoxingdong, 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
