### ISSUE TITLE
2225. Find Players With Zero or One Losses - Wrong Solution Code

### ISSUE THREAD

**Issue by karpoftea** [LeetCode-Feedback/LeetCode-Feedback#9622]
#### Your LeetCode username
karpoftea

#### Category of the bug
Solution

#### Description of the bug
In problem "2225. Find Players With Zero or One Losses" solution "Approach 3: Hash Map" code misses two lines that sorts result array, i.e.:
```
Collections.sort(answer.get(0));
Collections.sort(answer.get(1));
``` 

#### Code you used for Submit/Run operation
```
class Solution {
    public List<List<Integer>> findWinners(int[][] matches) {
        Map<Integer, Integer> lossesCount = new HashMap<>();
        for (int[] match : matches) {
            int winner = match[0], loser = match[1];
            lossesCount.put(winner, lossesCount.getOrDefault(winner, 0));
            lossesCount.put(loser, lossesCount.getOrDefault(loser, 0) + 1);
        }

        List<List<Integer>> answer =
            Arrays.asList(new ArrayList<>(), new ArrayList<>());
        for (Integer player : lossesCount.keySet())
            if (lossesCount.get(player) == 0) {
                answer.get(0).add(player);
            } else if (lossesCount.get(player) == 1) {
                answer.get(1).add(player);
            }
        
        Collections.sort(answer.get(0));
        Collections.sort(answer.get(1));

        return answer;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Two lines mentioned above fix problem, and now array is sorted (complexity is the same as in approach description)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
