### ISSUE TITLE
523. Continuous Subarray Sum || Wrong output in example 3

### ISSUE THREAD

**Issue by Crescent-Saturn** [LeetCode-Feedback/LeetCode-Feedback#9624]
#### Your LeetCode username

leifuer

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the question statement, the example 3 gives the output as `false`, however, when testing this example, the expected output is `true`

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

As least the expected output should always be the same in statement and testing.

#### Screenshots

![image](https://user-images.githubusercontent.com/18294546/197911923-fb835898-0600-4574-ac0d-74811a4eda45.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem, we found not the same test case is tested. We appreciate your support!
