### ISSUE TITLE
2448 - Minimum Cost to Make Array Equal - JS Judge Issue

### ISSUE THREAD

**Issue by GroverW** [LeetCode-Feedback/LeetCode-Feedback#9625]
#### Your LeetCode username

[ektegjetost](https://leetcode.com/ektegjetost/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

[2448 - Minimum Cost to Make Array Equal](https://leetcode.com/problems/minimum-cost-to-make-array-equal/)
Same issue as [this issue](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/6632)
- Test Case ```43```requires the use of BigInt, but the returned value is converted to a regular number
- A regular JS number doesn't have enough precision to represent the expected answer, and so the returned value is off by 1

#### Code you used for Submit/Run operation

```javascript
var minCost = function(nums, cost) {
  const bySize = nums.map((_, i) => i).sort((a, b) => nums[a] - nums[b]);
  const fromLeft = nums.map(() => 0n);
  
  let totalCost = BigInt(cost[bySize[0]]);
  for (let i = 1; i < nums.length; i += 1) {
    fromLeft[i] = fromLeft[i - 1] + totalCost * BigInt(nums[bySize[i]] - nums[bySize[i - 1]]);
    totalCost += BigInt(cost[bySize[i]])
  }
  
  totalCost = BigInt(cost[bySize.at(-1)])
  let best = fromLeft.at(-1);
  let fromRight = 0n;
  
  for (let i = nums.length - 2; i >= 0; i -= 1) {
    fromRight += totalCost * BigInt(nums[bySize[i + 1]] - nums[bySize[i]]);
    if (fromLeft[i] + fromRight < best) best = fromLeft[i] + fromRight;
    totalCost += BigInt(cost[bySize[i]]);
  }
  
  return best;
};
```

#### Language used for code

JavaScript

#### Expected behavior

Test case should pass

#### Screenshots

<img width="564" alt="image" src="https://user-images.githubusercontent.com/53848560/197924759-f59a16c9-b439-482e-9462-d1346a10f150.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
