### ISSUE TITLE
增加测试用例

### ISSUE THREAD

**Issue by ybin-hub** [LeetCode-Feedback/LeetCode-Feedback#9627]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
抱糖果彡

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
[2352. 相等行列对](https://leetcode.cn/problems/equal-row-and-column-pairs/)
查看别人提交代码缺少测试用例

**你使用的语言**
java

**你提交或者运行的代码**
```
// equal-row-and-column-pairs
class Solution {
    public int equalPairs(int[][] grid) {
        int all = 0;
        int[] qw = new int[grid.length * 2];
        for(int i = 0; i < grid.length; i++) {
            int count = 0, c2 = 0;
            int k = 1;
            for (int j = 0; j < grid.length; j++) {
                c2 += grid[j][i] * k;
                count += grid[i][j] * k;
                k *= 11;
            }
            qw[i] = count;
            qw[i + grid.length] = c2;
        }

        for (int i = 0; i < grid.length; i++) {
            for (int j = grid.length; j < 2 * grid.length; j++) {
                if(qw[i] == qw[j]) all++;
            }
        }
        return all;
    }
}
```

**期望行为**
测试用例：[[1,11,21],[22,1,1],[20,1,1]]
应该返回0，结果返回1，但提交通过

**屏幕截图**
![QQ截图20221026151640](https://user-images.githubusercontent.com/73328869/197959656-2e912023-79db-4967-b138-1308ad9d7b40.png)

**额外的上下文**
[2352. 相等行列对](https://leetcode.cn/problems/equal-row-and-column-pairs/)

**Comment by feiceh** [comment]
已处理，积分奖励已发放～
