### ISSUE TITLE
Typo in problem statement - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by kuzzzzz** [LeetCode-Feedback/LeetCode-Feedback#9634]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

<img width="647" alt="Screenshot 2022-10-26 at 15 50 08" src="https://user-images.githubusercontent.com/38002856/198059956-6aba8498-61a2-4e12-93b4-0dbadefb6cd9.png">

#### Additional context

At least two what?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
