### ISSUE TITLE
Missing Test Case - 2247. Maximum Cost of Trip With K Highways

### ISSUE THREAD

**Issue by Uchiwuwu** [LeetCode-Feedback/LeetCode-Feedback#9635]
While reading the solutions submitted, there is a test case that might be missing in the test case list
n =
7
highways =
[[0,1,100],[1,2,3],[2,3,6],[3,4,5],[1,6,4],[6,5,4],[5,4,5]]
k =
4

my username in leetcode: curioustien

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by DurveshKumarPal** [comment]
Hey, I want to Contribute to this issue can you assign me?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
