### ISSUE TITLE
typo in sql explore card

### ISSUE THREAD

**Issue by incubo4u** [LeetCode-Feedback/LeetCode-Feedback#9636]
#### Your LeetCode username

incubo4u / user6552B

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think there is an error parsing the * character 
under explore > sql > sql syntax > SELECT, INSERT, UPDATE and DELETE

#### Expected behavior

expected -> *
actuall -> ('')

#### Screenshots

<img width="504" alt="image" src="https://user-images.githubusercontent.com/52492193/198108368-676738a8-07ad-46c4-8732-40c05b3e6843.png">

#### Additional context

https://leetcode.com/explore/learn/card/sql-language/683/sql-syntax/4316/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem.  We appreciate your support!
