### ISSUE TITLE
[63. Unique Paths II ](https://leetcode.com/problems/unique-paths-ii/) - C++ issue

### ISSUE THREAD

**Issue by vmkgalvatron** [LeetCode-Feedback/LeetCode-Feedback#9637]
Your LeetCode username
[vmkgalvatron](https://leetcode.com/vmkgalvatron/)

Category of the bug
 Language

Description of the bug
In case of c++ default function, return type is `int` but when `int` is used, answer overflows, so return type used should be long. I have tested using `long` instead of `int`. It works fine. Please change return type to `long`.

Language used for code
c++

Expected behavior
answers should not be greater than `INT_MAX` or return type should be `long`.

Screenshots
<img width="1438" alt="Screenshot 2022-10-27 at 1 24 16 PM" src="https://user-images.githubusercontent.com/68223626/198224100-555dffdf-7f34-4d7f-924d-7bbca1f48576.png">
<img width="1438" alt="Screenshot 2022-10-27 at 1 22 53 PM" src="https://user-images.githubusercontent.com/68223626/198224241-48bc99b5-ff73-482c-8140-98aee1294826.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The answer is always int. It's the user responsibility to handle the intermediate calculations. We appreciate your support!
