### ISSUE TITLE
355. Design Twitter

### ISSUE THREAD

**Issue by naseefcse** [LeetCode-Feedback/LeetCode-Feedback#964]
#### Your LeetCode username
bokolom_coder

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Error in C++ Expected Output.

For the following test case Expected output is wrong.

Test Case: ["Twitter","postTweet","postTweet","postTweet","postTweet","postTweet","postTweet","postTweet","postTweet","postTweet","postTweet","postTweet","getNewsFeed"]
[[],[1,5],[1,3],[1,101],[1,13],[1,10],[1,2],[1,94],[1,505],[1,333],[1,22],[1,11],[1]]

Expected Output by Leetcode: [null,null,null,null,null,null,null,null,null,null,null,null,[22,333,505,94,2,10,13,101,3,5]]

Actual Output should be: [null,null,null,null,null,null,null,null,null,null,null,null,[11,22,333,505,94,2,10,13,101,3]]

Here we are posting tweets with tweetId 11 at the very last. But the expected output is completely ignoring this one. According to the problem description, `getNewsFeed` should return the latest 10 tweets so tweet with tweetId 11 should have been first in the list.

Because of this issue, I couldn't solve the problem. Quick assistance needed.

Please note that I have checked with an accepted code using python, which gives the expected output for this case.

#### Code you used for Submit/Run operation

```
class Twitter {
public:
    /** Initialize your data structure here. */
    
    //std::vector<std::vector<>>
    
    std::vector<std::pair<int, int>> tweet_list;
        
    std::unordered_map<int, std::unordered_set<int>> followers_list;
    
   // int time_count {0};
    
    Twitter() {
        
    }
    
    /** Compose a new tweet. */
    void postTweet(int userId, int tweetId) {
        std::pair<int, int> pair = std::make_pair(userId, tweetId);
        
        tweet_list.push_back(pair);
        
        std::unordered_set<int> follows;
        
        follows.insert(userId);
        
        followers_list[userId] = follows;
    }
    
    /** Retrieve the 10 most recent tweet ids in the user's news feed. Each item in the news feed must be posted by users who the user followed or by the user herself. Tweets must be ordered from most recent to least recent. */
    vector<int> getNewsFeed(int userId) {
        std::vector<int> feeds;
        
        if (followers_list.find(userId) == followers_list.end())
            return feeds;
        
        
        std::unordered_set<int> follower_list = followers_list[userId];
        
        int count = 0;
        for (auto i : tweet_list) {
            if (follower_list.find(i.first) != follower_list.end()) {
                feeds.insert(feeds.begin(), i.second);
                count++;
                
                if (count == 10)
                    break;
            }
        }
        
        return feeds;
    }
    
    /** Follower follows a followee. If the operation is invalid, it should be a no-op. */
    void follow(int followerId, int followeeId) {
        if (followers_list.find(followerId) == followers_list.end()) {
            std::unordered_set<int> follows;
            follows.insert(followeeId);
            
            followers_list[followerId] = follows;
        }
        else {
            std::unordered_set<int> follows = followers_list[followerId];
            
            follows.insert(followeeId);
            
            followers_list[followerId] = follows;
        }
    }
    
    /** Follower unfollows a followee. If the operation is invalid, it should be a no-op. */
    void unfollow(int followerId, int followeeId) {
        
        if (followerId == followeeId) return;
        
        if (followers_list.find(followerId) == followers_list.end()) {
//             std::unordered_set<int> follows;
//             follows.insert(followeeId);
            
//             followers_list[followerId] = follows;
            //Do nothing
        }
        else {
            std::unordered_set<int> follows = followers_list[followerId];
            
            follows.erase(followeeId);
            
            followers_list[followerId] = follows;
        }
    }
};

/**
 * Your Twitter object will be instantiated and called as such:
 * Twitter* obj = new Twitter();
 * obj->postTweet(userId,tweetId);
 * vector<int> param_2 = obj->getNewsFeed(userId);
 * obj->follow(followerId,followeeId);
 * obj->unfollow(followerId,followeeId);
 */
```

#### Language used for code

C++

#### Expected behavior

Expected Output by Leetcode: [null,null,null,null,null,null,null,null,null,null,null,null,[22,333,505,94,2,10,13,101,3,5]]

Actual Output should be: [null,null,null,null,null,null,null,null,null,null,null,null,[11,22,333,505,94,2,10,13,101,3]]

**Comment by lc-kay** [comment]
Hi @naseefcse, 

When I submitted your code and the test case, the expected outcome is what you stated it should be. 
[null,null,null,null,null,null,null,null,null,null,null,null,[11,22,333,505,94,2,10,13,101,3]]

<img width="847" alt="Screen Shot 2020-09-10 at 4 02 51 PM" src="https://user-images.githubusercontent.com/70870126/92820816-3beceb00-f37f-11ea-8b1b-5919d40010eb.png">

Please let me know and include a screenshot if that is not what you see on your end.

**Comment by naseefcse** [comment]
I got it now. The issue is in my code.
