### ISSUE TITLE
Approach 2 failed test case - 1046. Last Stone Weight

### ISSUE THREAD

**Issue by Sheldon-Pang** [LeetCode-Feedback/LeetCode-Feedback#9646]
#### Your LeetCode username

MeowCattt

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Approach 2: Sorted Array-Based Simulation java solution, failed test case [3,7,8], the expected result is 2, but output from code is -2.

#### Code you used for Submit/Run operation

```
class Solution {
    public int lastStoneWeight(int[] stones) {
        List<Integer> stoneList = new ArrayList<>();
        for (int stone : stones) {
            stoneList.add(stone);
        }
        Collections.sort(stoneList);

        while (stoneList.size() > 1) {
            int stone1 = stoneList.remove(stoneList.size() - 1);
            int stone2 = stoneList.remove(stoneList.size() - 1);

            if (stone1 != stone2) {
                int newStone = stone1 - stone2;
                int index = Collections.binarySearch(stoneList, newStone);
                if (index == -1) {
                    stoneList.add(newStone);
                } else if (index < 0) {
                    stoneList.add(-index - 1, newStone);
                } else {
                    stoneList.add(index, newStone);
                }
            }
        }

        return !stoneList.isEmpty() ? stoneList.remove(0) : 0;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Correct output should be 2.
The problem is caused by the part of code where,
```
if (index == -1) {
                    stoneList.add(newStone);
                }
```

When [3,7,8] as the input, the first iteration would make newStone = 8 - 7 = 1.
Collections.binarySearch(stoneList, newStone) would return (insertion point 0 - 1) = -1
Then, the newStone(1) would be inserted at end of the list, which is not correct.

Fix:
Just deleting the blow part from the code would fix the problem
```
if (index == -1) {
                    stoneList.add(newStone);
                }
```

#### Screenshots

original leetcode approach 2 solution:
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/67815377/198221510-2d3461fe-3efa-48ab-8ca4-b0388cf20634.png">
The fixed solution where the mentioned part is deleted would pass all tests.
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/67815377/198221813-cc02c626-238f-42ea-bb0e-faa3efcf94f3.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
