### ISSUE TITLE
177. Nth Highest Salary - Runtime Error while Submitting Solution 

### ISSUE THREAD

**Issue by asfiqbal** [LeetCode-Feedback/LeetCode-Feedback#9649]
#### Your LeetCode username

asfiqbal

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

While submitting the solution, getting run time error.

#### Code you used for Submit/Run operation

```
CREATE FUNCTION getNthHighestSalary(@N INT) RETURNS INT AS
BEGIN
    DECLARE @NThSalary int;
    SELECT @NThSalary = SALARY
    FROM
    (
        SELECT TOP 100 ROW_NUMBER() OVER(ORDER BY EMP_ID DESC) AS NPos, SALARY
        FROM	EMPLOYEE
        order by SALARY desc
    ) T 
    WHERE NPos = @N
    RETURN (@NThSalary);
END
```

#### Language used for code

T-SQL

#### Expected behavior

This should get compiled and submitted Successfully

#### Screenshots

![image](https://user-images.githubusercontent.com/8807477/198277787-2cbab582-dd4d-491b-a61b-81682a5e4a9d.png)

#### Additional context

![image](https://user-images.githubusercontent.com/8807477/198278779-e2e2aedd-995d-4137-b91f-945e0c5155b0.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the solution is using an invalid column name as shown in the error message, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by asfiqbal** [comment]
The original solution Screen Shot 1 contains no column error. The screen shot 2 present in additional context is my testing on my SQL Server. I already had a column name EMP_ID instead of id that I have used for my SQL server version which compiled and executed successfully as shown in Screen Shot 2
