### ISSUE TITLE
All my progress for premium daily challenge in explore card has been vanished

### ISSUE THREAD

**Issue by naseefcse** [LeetCode-Feedback/LeetCode-Feedback#965]
#### Your LeetCode username
bokolom_coder

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Account

#### Description of the bug

I have been solving daily challenges every day for the last few months. Recently, Leetcode has introduced a premium daily challenge every week. Recently, I saw that my previous premium daily challenges are marked unsolved in the explore card. And I also checked that my Leetcoin is less than previous. This site issue is unexpectable for a premium member who is paying a lot of money every year. I need a concrete resolution for that. 

#### Screenshots

[https://drive.google.com/file/d/1-Tlo-c2eqTWAlPEdhloWfDlqHevbfMMc/view?usp=sharing](url)

**Comment by lc-pam** [comment]
Hi @naseefcse , thank you for reaching out to us! The team has fixed the issue quickly after your report. Thank you again for your support!
