### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by jainamthakkar** [LeetCode-Feedback/LeetCode-Feedback#9652]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug ---> **Missing TestCase**

          Here in this Question one Testcase need to be Added because this test case is giving wrong solution which's Screen Sort i have Attached. where in given input [3,4,2,1,2] Answer should be return index 1 where my code is returnning 1 so its doing well. but Expected output is showing Answer is index 4. also the compiler showing status Accepted !! 
(ScreenShot is Attached)

#### Code you used for Submit/Run operation

```
// Find Peak Element
class Solution {
    public int findPeakElement(int[] arr) { //[3,4,2,1,2] will not work in binary search

    //key point is that in the array left and right side elemnt are getting smaller than middles 
        int start = 0;
        int end = arr.length - 1;
        while (start < end) 
        {
            int mid = start + (end - start) / 2;
            if (arr[mid] > arr[mid+1]) 
            {
                // you are in dec part of array
                // this may be the ans, but look at left=
                // this is why end != mid - 1
                end = mid;
            } else 
            {
                // you are in asc part of array
                start = mid + 1; // because we know that mid+1 element > mid element
            }
        }
        // in the end, start == end and pointing to the largest number because of the 2 checks above
        // start and end are always trying to find max element in the above 2 checks
        // hence, when they are pointing to just one element, that is the max one because that is what the checks say
        // more elaboration: at every point of time for start and end, they have the best possible answer till that time
        // and if we are saying that only one item is remaining, hence cuz of above line that is the best possible ans
        return start; // or return end as both are =
    }
}

```

#### Language used for code

JAVA

#### Expected behavior

   It should return the answer 1 not 4 !!

#### Screenshots

![image](https://user-images.githubusercontent.com/105544028/198344827-23eb8533-1db0-4524-b8ee-ca31fd46559c.png)

**Comment by jainamthakkar** [comment]
Missing TestCase

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test case does not fail any test case.  We appreciate your support!
