### ISSUE TITLE
285. Inorder Successor in BST - no argument validation in place

### ISSUE THREAD

**Issue by nineonine** [LeetCode-Feedback/LeetCode-Feedback#9658]
you can run code with only 1 argument and server does not complain about missing second argument (as per problem description).

language used: Javascript

Repro:

```
var inorderSuccessor = function(root, p) {  
    let res = null
    while (root) {
        if (p.val >= root.val) {
            root = root.right
        } else {
            res = root
            root = root.left
        }
    }
    return res
};
```
args:
```
[2,null,3]
```

I used debugger and it appears that second argument is passed as `null` in this case.

**Expected behaviour:** usually backend returns helpful message telling that provided input was incorrect

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
Please provide us your LC username.

**Comment by nineonine** [comment]
@LC-Pam thanks for fixing it.
my LC account:  https://leetcode.com/dnox
