### ISSUE TITLE
VS code能过，leetcode不能没法编译。。。

### ISSUE THREAD

**Issue by RobinTuyongbing** [LeetCode-Feedback/LeetCode-Feedback#9659]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**   Robin
填写你登录 LeetCode（中国区）的用户名    Robin

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
程序在vs code上gcc编译，运行调试都没问题，我自己建立的环形链表，之前测试别的也都没问题。
然后把程序在leetcode的上执行就出错。

**你使用的语言**
C

**你提交或者运行的代码**
typedef struct ListNode ListNode;

bool hasCycle(struct ListNode *head) {
    ListNode* Dest = (ListNode*)malloc(sizeof(ListNode));//开辟一个节点，Dest指针在此位置standby
    ListNode* Find = head;//Find指针出去寻找

    //寻找方式：往后走，经过的节点next指向Dest
    while(Find->next != NULL)
    {
        ListNode* temp = Find->next;
        if(Find->next == Dest)
        {
            free(Dest);
            return 1;
        }
        Find->next = Dest;
        Find = temp;
    }
    free(Dest);
    return 0;
}

**期望行为**
难道是编译器不同？？

**屏幕截图**
![image](https://user-images.githubusercontent.com/114099169/198508249-0a116cf8-5eb4-478d-ae97-8ba4084b8458.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，相关团队核实：未对 Dest 初始化，只进行了声明。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
