### ISSUE TITLE
Wrong order of the contests in the rating graph 

### ISSUE THREAD

**Issue by danchanka** [LeetCode-Feedback/LeetCode-Feedback#966]
#### Your LeetCode username
`_dale_`

#### Category of the bug
Rating graph

#### Description of the bug
It seems that some Weekly and Biweekly contests are mixed up in the rating graph. For example, Weekly Contest 204 goes after Biweekly Contest 34 at the moment (and Weekly 202 goes after Biweekly 33)  

#### Screenshots
![327a0-clip-19kb](https://user-images.githubusercontent.com/20270415/92452457-be7e7a80-f1c6-11ea-8924-ade8939de047.png)
![c8d8b-clip-21kb](https://user-images.githubusercontent.com/20270415/92452465-c0483e00-f1c6-11ea-80be-0408291285ae.png)

**Comment by lc-kay** [comment]
Hi @danchanka 

Thank you for reaching out to us. Can you please re-submit your ticket through our [help desk](https://support.leetcode.com/hc/en-us/requests/new)? On this GitHub channel, it is reserved for content-related issues. I hope to resolve your issue soon!

**Comment by danchanka** [comment]
Ok!
