### ISSUE TITLE
suggestion: please use `usize` as parameter type instead of using `i32` when necessary

### ISSUE THREAD

**Issue by orc-dev** [LeetCode-Feedback/LeetCode-Feedback#9661]
#### Your LeetCode username
orc-dev 

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
It is not a bug. It is a suggestion. For Rust language, one must use the `usize` type to index an array or vector,
for question such as 576, the parameters: `m`, `n`, `start_row` and `start_column`, are indicated the size or index of a matrix, if their type is `usize`, we can directly use it, otherwise, we have to convert it to `usize` each time, which is not very convenient. Thanks for considering this suggestion.

#### Code you used for Submit/Run operation

```
// 576. Out of Boundary Paths
pub fn find_paths(m: i32, n: i32, max_move: i32, start_row: i32, start_column: i32) -> i32 {

}
```

#### Language used for code
Rust

**Comment by orc-dev** [comment]
Rust: use `usize` type for parameters indicating indices or size of array or vector

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
