### ISSUE TITLE
Wrong output is generated from code which is fine in VS Code

### ISSUE THREAD

**Issue by SulavChhetri** [LeetCode-Feedback/LeetCode-Feedback#9664]
#### Your LeetCode username
SulavChhetri

#### Category of the bug
- [ ] Solution

#### Description of the bug
For the specific case where words =["a","b"] and s ="aaa", my code should have returned an empty list which it does correctly in my VS Code IDE, but here in the result checking it displays a list [0,1]. And when i add that specific case to the testcase and the run the test cases , it returns correct output i.e [] an empty list.

#### Code you used for Submit/Run operation
```
// Substring with Concatenation of All Words
class Solution(object):
    global_list=[]
    def toString(self,List):
        self.global_list.append(''.join(List))
 
    def permute(self,a, l, r):
        if l == r:
            self.toString(a)
        else:
            for i in range(l, r + 1):
                a[l], a[i] = a[i], a[l]
                self.permute(a, l + 1, r)
    
                # backtrack
                a[l], a[i] = a[i], a[l]
 
    def findSubstring(self, s, words):
        """
        :type s: str
        :type words: List[str]
        :rtype: List[int]
        """
        return_words =list()
        max =len(words)-1
        self.permute(words,0,max)
        substring_length = len(words)*len(words[0])
        for i in range(len(s)-substring_length+1):
            sub_string=''
            for j in range(substring_length):
                sub_string = sub_string+s[i+j]
            if sub_string in self.global_list:
                return_words.append(i)
        return return_words   

```

#### Language used for code
Python

#### Expected behavior
For the specific case where words =["a","b"] and s ="aaa", my code should have returned an empty list

#### Screenshots
[image](https://user-images.githubusercontent.com/87139979/198564910-9664461d-c8fd-4544-9311-e322cec29c55.png)

**Comment by SulavChhetri** [comment]
####Screenshots
![image](https://user-images.githubusercontent.com/87139979/198575863-6f0f7f70-a5fd-4439-8414-9c73a675a19f.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
