### ISSUE TITLE
Missing Test Case - 49. Group Anagrams

### ISSUE THREAD

**Issue by Ag565** [LeetCode-Feedback/LeetCode-Feedback#9665]
#### Your LeetCode username
ag565

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases for the group anagrams problem. The below code that uses a bitmap for character sums in the given string will pass when submitted but the following test case will cause a failure:
["aaaaaaaa","b"]

The code below only allocates 3 bits per character when up to 7 bits could be required given that each string could contain 100 characters of the same type.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        shash = {}
        for s in strs:
            bitmap = 0
            for c in s:
                bitmap += (1<<((ord(c) - 97)*3)) #only allocating 3 bits for each character sum, which should fail submission
            
            if bitmap in shash:
                shash[bitmap] += [s]
            else:
                shash[bitmap] = [s]
                
        return list(shash.values())
```

#### Language used for code
Python3

#### Expected behavior
The submission for the above code should fail, but instead it passes, which indicates that there are missing test cases.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
