### ISSUE TITLE
Missing Test Case - 213. House Robber II

### ISSUE THREAD

**Issue by winsc003** [LeetCode-Feedback/LeetCode-Feedback#9666]
#### Your LeetCode username
winsc003

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For the "House Robber II problem", I was given the test case:

[1,2,3,4,5,1,2,3,4,5]

The answer should be 15 (1+3+5+2+4=15 and also 2+4+1+3+5=15) and my code gave that answer. However, the solution was marked wrong and it says that the answer should be 16. 

#### Code you used for Submit/Run operation
```
public class Solution {
    public int Rob(int[] nums) {
        int totalHouses = nums.Length;
        
        //Even Houses Case
        if(totalHouses % 2 == 0) {
            int group1=0, group2=0;
            
            for(int i=0; i<totalHouses; i++) {
                if (i % 2 == 0) {
                    group1 += nums[i];
                }
                else {
                    group2 += nums[i];
                }
            }
            
            if(group1 >= group2) {
                return group1;
            }
            else{
                return group2;
            }
        }
        
        //Odd Houses Case
        else {
            int totalValidHouses = totalHouses/2;
            int highestTotal = nums[0], currTotal = 0;
            
            for(int i=0; i<totalHouses; i++) {
                for(int j=0; j<totalValidHouses; j++) {
                    currTotal += nums[(i+(j*2))%totalHouses];
                }
                
                if(currTotal > highestTotal) {
                    highestTotal = currTotal;
                }
                currTotal = 0;
            }
            
            return highestTotal;
        }
    }
}
```

#### Language used for code
C#

#### Expected behavior
Test Case solution should have been marked correct for answer 15.

**Comment by pedrobarbosaocb** [comment]
As it is the most amount of money, you can starting from the highest numbers, so you can go like 5 + 3 + 5 + 3 (= 16). You can´t rob adjacent houses, but you can jump more than two houses the get the hightest amount of money.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
