### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by pedrobarbosaocb** [LeetCode-Feedback/LeetCode-Feedback#9667]
#### Your LeetCode username
pedrobarbosaocb

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The output showed doesn't match with the output of the solution submitted. As it can be tested outside the LeetCode console, the solution submitted matches with the Case 2 expected output, but on it's console shows the output is '2.0000'.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def findMedianSortedArrays(self, nums1, nums2):
        """
        :type nums1: List[int]
        :type nums2: List[int]
        :rtype: float
        """

        List = nums1 + nums2
        List.sort()
        result = 0

        if len(List)%2 == 0:
            result = (List[int(len(List)/2)] + List[int((len(List)/2) - 1)])/2
        else:
            result = List[int(len(List)/2)]

        return result
```

#### Language used for code
Python

#### Expected behavior

The output should match the output of the solution added.

#### Screenshots

![image](https://user-images.githubusercontent.com/78980796/198722432-5da8172f-8c3c-466b-887d-2b46307ea7c4.png)
![image](https://user-images.githubusercontent.com/78980796/198729724-244a870e-b55b-4165-b0c2-8d34b8c8eaf9.png)

#### Additional context

I'm using Google Colab to make my own tests

**Comment by nikhil478** [comment]
check your python version

**Comment by pedrobarbosaocb** [comment]
> check your python version

I was using the 2.7, the LeetCode's python version

**Comment by LC-Pam** [comment]
https://leetcode.com/submissions/detail/834172227/
