### ISSUE TITLE
1022. Sum of Root To Leaf Binary Numbers - Contribute a testcase

### ISSUE THREAD

**Issue by JerryL1987** [LeetCode-Feedback/LeetCode-Feedback#967]
#### Your LeetCode username

Chihhung Li

#### Category of the bug
Miss a test case

#### Description of the bug

Testcases doesn't have the case which root is NULL. 

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     struct TreeNode *left;
 *     struct TreeNode *right;
 * };
 */
int dfs(struct TreeNode *root, int pass, int current) {
    if (root->right == NULL && root->left == NULL) {
        return current + pass + root->val;
    }
    int ret = 0;
    if (root->right) {
        ret = dfs(root->right, (pass + root->val) * 2, current);
    }
    if (root->left) {
        ret += dfs(root->left, (pass + root->val) * 2, current);
    }
    return ret;
}

int sumRootToLeaf(struct TreeNode* root){
    int ret = dfs(root, 0, 0);
    return ret;
}
```

#### Language used for code

C

#### Expected behavior

The program should meet runtime error, because it doesn't check the NULL pointer.

#### Screenshots

![image](https://user-images.githubusercontent.com/46712380/92456443-817dac80-f1f5-11ea-8a13-f373a765d033.png)

**Comment by dharmangbhavsar** [comment]
I think it is mentioned in the question that the tree contains atleast one node. So NULL input will not be valid according to constraints.

**Comment by lc-kay** [comment]
Hi @JerryL1987 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @JerryL1987 
Thank you for your time. We've already added validators for this problem based on feedback from another user. We appreciate your support!
