### ISSUE TITLE
Potential error in proof for earliest-possible-day-of-full-bloom

### ISSUE THREAD

**Issue by MMKrell** [LeetCode-Feedback/LeetCode-Feedback#9672]
When going through the proof for 
https://leetcode.com/problems/earliest-possible-day-of-full-bloom/solutions/2582720/earliest-possible-day-of-full-bloom/
I discovered a potential error/insufficiency. The point that the inequalities hold is necessary but not sufficient for optimal solution. At least, it is nowhere proven that the inequalities are sufficient and my intuition is they are not. Hence, a more elaborate proof is required. It might be possible to derive equations instead of inequalities? Maybe one could introduce a time k that is required after the planting of i and j for the remaining plants and then t can be calculated as t_i=s+plan_time_i+plant_time_j+max(growth_time_j, k) in case one and t_j=s+plan_time_j+plant_time_i+max(growth_time_i, k) after the swap. Since, growth_time_i is smaller or equal to growth_time j, we now prove t_j after the swap is actually smaller or equal.

Note that even after this proposed correction, the proof is not complete. It just shows that the optimal solution can be assumed to be resulting from sorting by descending growth. For a sufficiency condition that justifies the code, a proof is required, that shows that the sorting of plant time does not impact the solution. Probably the previous approach can be used for it because swapping the plant_times, while growth_time variables are sorted does not change the newly derived formula for t.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by MMKrell** [comment]
Thank you. Please let me know if you need any help or further details.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to improve the explanation.  We appreciate your support!
