### ISSUE TITLE
Missing Test Case - 面试题 04.01. Route Between Nodes LCCI

### ISSUE THREAD

**Issue by CodeATA** [LeetCode-Feedback/LeetCode-Feedback#9674]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool findWhetherExistsPath(int n, vector<vector<int>>& graph, int start, int target) {
        vector<bool> hash(n);
        hash[start] = true;
        for(int i=0;i<graph.size();++i){
            if(hash[graph[i][0]]){
                hash[graph[i][1]] = true;
            }
        }
        return hash[target];
    }
};
```

#### Expected behavior

以上代码不应该通过，因为其正确性依赖于输入的序列是否先输入了以start为起始的边。
The above code should not pass, because it relies on the specific sequence of the input. Considering a situation when the only edge starting from _start_ is input last, then the above code will produce a wrong result.

Example: ```graph = [[1, 2], [0, 1]], start = 0, target = 2```

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by CodeATA** [comment]
leetcode-cn.com/u/serene-varahamihiramgc/

**Comment by feiceh** [comment]
积分奖励已发放，请查收。
