### ISSUE TITLE
Unclear problem description - 2456. Most Popular Video Creator

### ISSUE THREAD

**Issue by bogoconic1** [LeetCode-Feedback/LeetCode-Feedback#9676]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

creators = ["alice", "alice", "alice"]
ids = ["x", "y", "x"]
views = [3,5,3]

The correct answer should be **["alice", "y"]**.

But many people have interpreted it another way, they summed up the views of the videos by the same creator with the same id, which is,

**creators = ["alice", "alice", "alice"]
ids = ["x", "y"]
views = [3+3,5] = [6,5]**

As such, they output the answer of **["alice", "x"]**. Worse still, the wrong answer was in a hidden test case which made it extremely difficult to debug.

The question statement is unclear. For example, A video record (Creator1, id1, Views1) and (Creator1, id1, Views2) should be treated as 
(Creator1, id1, max(Views1, Views2)) not (Creator1, id1, Views1 + Views2)). This info was not mentioned anywhere in the question

#### Expected behavior

This contest should be unrated since this ambiguous description issue caused lots of people to make mistakes or not even get accepted on this problem.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The issue was resolved. We appreciate your support!
