### ISSUE TITLE
1367 Translation Error

### ISSUE THREAD

**Issue by airmelt** [LeetCode-Feedback/LeetCode-Feedback#9677]
#### Your LeetCode username

airmelt

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

Translation error, "Linked List" should be "链表", not "列表(list)“

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

<img width="449" alt="image" src="https://user-images.githubusercontent.com/38834131/198864346-6099f69b-ea96-4c63-b1bd-1610bd8d808c.png">

**Comment by feiceh** [comment]
你好，当前题目已更新，ID：airmelt 给予积分奖励，请查收。
