### ISSUE TITLE
Improve the text in the "leetcodes-interview-crash-course-data-structures-and-algorithms"

### ISSUE THREAD

**Issue by Rhtyme** [LeetCode-Feedback/LeetCode-Feedback#9679]
#### Your LeetCode username
rhtyme

#### Category of the bug
- [ ] Language

#### Description of the bug

Improve the text of the tutorials, and exercises. Please, do a proof-reading according to the academic writing style. Otherwise, the text is written very poorly. For example,  
[a tutorial about hash-maps](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/705/hashing/4510/) contains the following text: "One important thing to know ..." which can be paraphrased like "An important point to consider ..." or something else.

The description of the exercises also contains many issues. For example, let's consider [the following example about linked lists](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/704/linked-lists/4660/). The description of the Example 1 explains the output in the following way:

- Explanation: The middle node of the list is node 3.

It would be better to paraphrase:
- Explanation: The middle node of the list is node 3, thus returning a set of nodes that starts from this middle node till end.

Moreover, in the beginning, the description of the exercises asks to return "the second middle node". Then another question arises: what is a node? is it a subarray (according to [this link](https://www.hackerearth.com/practice/data-structures/linked-list/singly-linked-list/tutorial/#:~:text=A%20node%20is%20a%20collection,node%20present%20in%20the%20order.)) or just a single element of linked-lists?

Please pay special attention to such details. Although the course is very smooth and explains in a very smooth way, such small mistakes in texts disappoint your users. This course is not free, and people, including me, have paid for this course, so I guess we have right to ask for high quality.

**Comment by Rhtyme** [comment]
Another issue that I have just found in the [hashing section](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/705/hashing/4511/). The first paragraph contains the following sentence:

> Since an array needs `O(n)` to do this, using a hash map or set can improve your time complexity greatly, usually from `O(n^2)` to `O(n)`. 

What do you mean by _"usually from `O(n^2) to O(n)`"_ ? You are claiming that hashmap improves the complexity compared to array whose complexity is `O(n)`. But you are statement about the complexity of hashmap (`O(n^2)` to `O(n)`) is worse than array's (`O(n)`).

**Comment by Rhtyme** [comment]
I am finding a lot of such issues related to the description text. Please fix them. I do not have time to list them all one by one, by explaining why they are incorrect etc. Please, respect your users and do a proof-reading for all of your text, and adopt academic style in your text.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Rhtyme** [comment]
I am sorry, but I did not understand you. Even your response contains so many typo / grammar issues that makes it hard to understand:

> You misunderstands what a Linked List is - you thinks that a node "3 -> 4 -> 5" should actually be a "set" of three nodes when returning a single node, also thinks that a given linked list node is a subarray.

So, let's take an example the above paragraph from your response. First of all, `You misunderstands` should be `You misunderstood` or simply say `You did not understand`. What is this English or slang? Another point from this paragraph, I still did not understand what do you mean by this statement: `you thinks that a node "3 -> 4 -> 5" should actually be a "set" of three nodes when returning a single node`. My point was that, first definition of a node should be given, so that readers would not confuse what should be returned: a single node, or a sub-array. 

The same points can be applied for the hashing case. 

> You want's an "academic" writing style which would be terrible compared to a technical style for this kind of content.

Why would "academic" writing be terrible? State your opinion with some evidence.

I think that leetcode is a very popular and great platform. But such unprofessionalism can disappoint its users. So, please pay a special attention to my points and be professional in your actions and responses instead of just 'closing' the issue by some invalid reasons. Moreover, the course is not free, and it should have very high quality since it also represents the leetcode platform.
