### ISSUE TITLE
Unclear problem code template - 278. First Bad Version

### ISSUE THREAD

**Issue by sleonia** [LeetCode-Feedback/LeetCode-Feedback#9681]
#### Your LeetCode username
sleonia

#### Category of the bug
- [ ] Language

#### Description of the bug
Type `any` is so confused for understand code template. Comment above does not help

```
// First Bad Version
var solution = function(isBadVersion: any) {

    return function(n: number): number {

    };
};
```

#### Language used for code
`TypeScript`

#### Expected behavior
`isBadVersison` type is correct and does not confuse. Code template is:
```
var solution = function(isBadVersion: (version: number) => boolean) {

    return function(n: number): number {

    };
};
```
or 
```
type IsBadVersion = (version: number) => boolean;

var solution = function(isBadVersion: IsBadVersion) {

    return function(n: number): number {

    };
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We rejected the suggestion. The type any is suitable for the problem because you treat isBadVersion as a black box and only care about its output. . We appreciate your support!
