### ISSUE TITLE
1022. Sum of Root To Leaf Binary Numbers: Note under Description of Problem is Wrong

### ISSUE THREAD

**Issue by skyfall17** [LeetCode-Feedback/LeetCode-Feedback#969]
#### Your LeetCode username
Skyfall2017

#### Category of the bug
Problem description has slight grammatical error.

#### Description of the bug
Under the 'Note' section in problem 1022, it states "The number of nodes in the tree is between 1 and 1000." However, this should say "in-between" to make 1 and 1000 inclusive.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
private:
    void dfs(TreeNode * root, int val, vector<int> &result){
        if(root == nullptr){
            return;
        }
        if(root->left == nullptr && root->right == nullptr){
            result.at(0) += val * 2 + root->val;
        }
        dfs(root->left, val * 2 + root->val, result);
        dfs(root->right, val * 2 + root->val, result);
    }
public:
    int sumRootToLeaf(TreeNode* root) {
        vector<int> result = {0};
        dfs(root, 0, result);
        return result.at(0);
    }
};
```

#### Language used for code
C++

#### Expected behavior
The user should expect cases where the number of nodes can be 1 and 1000.

**Comment by lc-kay** [comment]
Hi @skyfall17 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @skyfall17 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
