### ISSUE TITLE
Missing Test Case - 2454. Next Greater Element IV

### ISSUE THREAD

**Issue by puneet-goel** [LeetCode-Feedback/LeetCode-Feedback#9691]
#### Your LeetCode username

puneet_goel

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution got an accepted verdict, but it gives TLE on the following testcase.
[testcase.txt](https://drive.google.com/file/d/164mGNBGIWgihQw5hmxkWs3ijQLTCOgvE/view?usp=share_link)

#### Code you used for Submit/Run operation

```
// Next Greater Element IV
class Solution {
public:
    vector<int> NGE(vector<int>& nums, int n) {
        vector<int> ans(n, n);
        stack<int> a;
        
        for(int i = n - 1; i >= 0; --i){
            while(!a.empty() && nums[i] >= nums[a.top()]){
                a.pop();
            }
            
            if(!a.empty()) ans[i] = a.top(); 
            a.push(i);
        }    
        
        return ans;
    }
    
    vector<int> secondGreaterElement(vector<int>& nums) {
        int n = nums.size();
        
        vector<int> nge = NGE(nums, n);
        vector<int> ans(n, -1);
        
        for(int i = 0; i < n; ++i){
            int y = nge[i] + 1;
            while(y < n && nums[y] <= nums[i]){
                y = nge[y];
            }
            
            if(y < n && nums[y] > nums[i]){
                ans[i] = nums[y]; 
            }
        }
        
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected to get a TLE verdict.

#### Screenshots

![image](https://user-images.githubusercontent.com/55274410/199060987-998151b9-beed-4c35-b651-9f72e5868636.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
