### ISSUE TITLE
Weak testcases for 2454. Next Greater Element IV

### ISSUE THREAD

**Issue by soumy-jain** [LeetCode-Feedback/LeetCode-Feedback#9692]
#### Your LeetCode username
soumyjain

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I have a testcase which gives Time Limited Exceeded(TLE) on my Accepted solution.

#### Code you used for Submit/Run operation

```
// 2454. Next Greater Element IV
class Solution {
public:
    vector<int> secondGreaterElement(vector<int>& v) {
        int n = v.size();
        vector<int> ngr(n, n), ngr2(n, n);
        for (int i = n - 1; i >= 0; i--) {
            int p = i + 1;
            while (p < n && v[i] >= v[p]) {
                p = ngr[p];
            }
            ngr[i] = p;
        }
        for (int i = 0; i < n; i++) {
            int p = ngr[i] + 1;
            while (p < n && v[i] >= v[p]) {
                p = ngr[p];
            }
            ngr2[i] = p >= n ? -1 : v[p];
        }
        return ngr2;
    }
};
```

#### Language used for code
C++

#### Expected behavior

My given [code](https://leetcode.com/submissions/detail/832807702/) has a complexity of O(n²), but its getting accepted (it should not). The given code should should result in a verdict of TLE. This means that testcases are very weak and this has lead many codes to pass unfairly in the live contest. 

#### Screenshots

![image](https://user-images.githubusercontent.com/55257561/199063071-097fd672-3b5a-459c-8981-37de8032e75b.png)
![image](https://user-images.githubusercontent.com/55257561/199063225-417c12b3-0b60-4490-b1a5-cf323431e2c6.png)

#### Additional context

This is the testcase that has to be added.
https://pastebin.com/3mtv3B7z

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by soumy-jain** [comment]
Sorry to bother you but I haven't received anything.

**Comment by soumy-jain** [comment]
> Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

I have received nothing yet.
