### ISSUE TITLE
No need for "Note" in the explanation of the 2nd approach (1480)

### ISSUE THREAD

**Issue by Bam92** [LeetCode-Feedback/LeetCode-Feedback#9698]
#### Your LeetCode username

Bam92

#### Category of the bug
- [ ] Question
- [ * ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the complexity analysis, they add "_Note:..._" as if in the solution we have an extra output array

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Remove "_Note:..._" and keep it just in the 1st approach complexity analysis section

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've consider the ticket invalid. The note sentence is necessary. We appreciate your support!
