### ISSUE TITLE
Missing Test Case - 2451. Odd String Difference

### ISSUE THREAD

**Issue by anishkumar127** [LeetCode-Feedback/LeetCode-Feedback#9700]
#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

weird bug. why that one line giving me issue while run solution showing illegal characters

#### Code you used for Submit/Run operation

```
class Solution {
    public String oddString(String[] words) {
         Map<List<Integer>, List<String>> map = new HashMap<>();

        for (int i = 0; i < words.length; i++) {
            char[] ch = words[i].toCharArray();
            
            List<Integer> list = new ArrayList<>();

            for (int idx = 1; idx < ch.length; idx++) {
                list.add(ch[idx] - ch[idx-1]);
            }

            if (map.containsKey(list)) {
                map.get(list).add(words[i]);
            }
            else {
                // map.put(list,new ArrayList<>());
                // map.get(list).add(words[i]);
                
                List<String> temp = new ArrayList<>();
                 // temp.add(words[i]); 
                temp.add(words[i]);
                 map.put(list, temp);
                
                //  List<String> temp = new ArrayList<>();
                // temp.add(words[i]);
                // map.put(list, temp);
            }
        }
System.out.print(map);
        for (List<Integer> key : map.keySet()) {
            if (map.get(key).size() == 1) {
                return map.get(key).get(0);
            }
        }

        return "";
    }
    }
```

#### Language used for code

Java

#### Screenshots

![image](https://user-images.githubusercontent.com/77631750/199225632-d9c8c6e3-7415-4c84-a7df-67a296a56b25.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. There was unsupported characters in the code that are not UTF.
Maybe writing clean code can help debugging. the provided link contains a clean version of the same code that compiles fine. 


https://pastebin.com/zZLfSRmG

We appreciate your support!
