### ISSUE TITLE
Missing Test Case - 2136. Earliest Possible Day of Full Bloom

### ISSUE THREAD

**Issue by ashutoshvimal** [LeetCode-Feedback/LeetCode-Feedback#9704]
#### Your LeetCode username

Soba_1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test Case. 
This test is not actually missing but this test case should to among the first 10 test cases because it is the test case that doesn't give the correct answer if logic sort according to _grow_time_ then take the sum of  _plant time[] _ and then add the last _grow time_

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int earliestFullBloom(vector<int>& plantTime, vector<int>& growTime) {
        int n = plantTime.size();

        vector<pair<int,int>> v;

        for(int i=0;i<n;i++){
            v.push_back({-growTime[i], plantTime[i]});
        }
        sort(v.begin(), v.end());
        
        int sum = accumulate(plantTime.begin(), plantTime.end(),0);
        
        return sum-v[n-1].first;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It's hard to find out why my above code logic is wrong. so if you add this test case among the first 10 test cases it will be easy for everyone to understand and debug their solution.

#### Additional context

It will make like easy for many.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
