### ISSUE TITLE
Missing Test Case - 371. Sum of Two Integers

### ISSUE THREAD

**Issue by krylatij** [LeetCode-Feedback/LeetCode-Feedback#9705]
#### Your LeetCode username
krylatij

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
public class Solution {
    public int GetSum(int a, int b) {
        if (a == 0 && b == 0){
            return 0;
        }
        
        if (a == 0){
            return b;
        }
        
        if (b == 0){
            return a;
        }     
        
        var r = (int)System.Math.Sqrt((a * a + b * b + 2 * a * b));
          
        if (a < 0 && b < 0){
            return -r;            
        }
        
        if (a > 0 && b > 0){
            return r;
        }
                       
        return r;
    }
}
```

#### Language used for code
C#

#### Expected behavior
Code should not be accepted, because 
5 + (-8) = -3 
but code produces 3.

#### Screenshots

![wrong-code-accepted](https://user-images.githubusercontent.com/103629/199350713-098b8087-3eed-41f1-ace9-a3bf01eab6c9.png)
![custom-test-case](https://user-images.githubusercontent.com/103629/199350716-c182519a-6495-4957-8255-b8fceac5d970.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
