### ISSUE TITLE
433. Minimum Genetic Mutation - incorrect template for ruby

### ISSUE THREAD

**Issue by XmmmiR** [LeetCode-Feedback/LeetCode-Feedback#9706]
#### Your LeetCode username
xmmmir

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Template is using end as second parameter, which is reserved word in ruby. It should be replaced with something like ```min_mutation(start_mutation, end_mutation, bank)```.

#### Code you used for Submit/Run operation

```
# @param {String} start
# @param {String} end
# @param {String[]} bank
# @return {Integer}
def min_mutation(start, end, bank)
    return -1 unless
    bfs = [start]

    
end
```

#### Language used for code
Ruby

#### Expected behavior
Template implementation should fail with "Wrong answer"

#### Screenshots
![image](https://user-images.githubusercontent.com/2445964/199365517-4ad46c7a-7b78-429a-973e-417207e3305f.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
