### ISSUE TITLE
39. 组合总和 - 答案没有检测重复结果

### ISSUE THREAD

**Issue by uzmijnlm** [LeetCode-Feedback/LeetCode-Feedback#9707]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Ezio

**Bug 类型**
- [39 ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
答案没有检测重复结果

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public List<List<Integer>> combinationSum(int[] candidates, int target) {
        List<List<Integer>> res = new ArrayList<>();
        List<Integer> path = new ArrayList<>();
        dfs(res, path, candidates, target, 0);
        return res;
    }

    private void dfs(List<List<Integer>> res, List<Integer> path, int[] candidates, int target, int start) {
        if (start >= candidates.length) {
            return;
        }

        if (target == 0) {
            res.add(new ArrayList<>(path));
            return;
        }
        if (target < 0) {
            return;
        }

        for (int i=start; i<candidates.length; i++) {
            path.add(candidates[i]);
            dfs(res, path, candidates, target-candidates[i], i);
            path.remove(path.size()-1);
        }
    }
}
```

**期望行为**
按照题意，输出结果中不应该包含重复结果，但是我的代码的输出结果中有重复的，却让我通过了。

**屏幕截图**
![39](https://user-images.githubusercontent.com/34177222/199373620-df8a0bba-0b0e-41a8-8b0c-41fbf8ad17d4.png)

**额外的上下文**
无

**Comment by feiceh** [comment]
感谢反馈，能否向我们补充题目信息，提供相关的测试用例，可以参考[这个反馈](https://github.com/LeetCode-Feedback/LeetCode-Feedback/blob/master/.github/ISSUE_TEMPLATE/bug--------.md)，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
