### ISSUE TITLE
1075. Project Employees I rounded to 2 digits.why expect answer shows 5 digits.

### ISSUE THREAD

**Issue by yyz20002008** [LeetCode-Feedback/LeetCode-Feedback#971]
![image](https://user-images.githubusercontent.com/1105915/92549366-1056ed00-f227-11ea-8788-758e8b94ce21.png)

![image](https://user-images.githubusercontent.com/1105915/92549194-bb1adb80-f226-11ea-93f3-c7669441296a.png)

MSSQL

```
select project_id  ,CAST(AVG(cast(e.experience_years as float) ) AS DECIMAL(10,2)) average_years 
from project p
join Employee e
on p.employee_id =e.employee_id 
group by project_id  
```

**Comment by lc-kay** [comment]
Hi @yyz20002008, 

When I ran your code, it was accepted. Can you please provide the test case that you inputed that led to a wrong answer? Or, if this is not what you see on your end, please let me know and provide a screenshot. Thank you. 

https://leetcode.com/submissions/detail/393938812/

**Comment by yyz20002008** [comment]
Thanks.
This is test case
https://leetcode.com/submissions/detail/393959859/testcase/

**Comment by lc-kay** [comment]
Hi @yyz20002008, 

When I ran your test case with your code, it was accepted. Can you please try again and see if it is still saying you have the wrong answer? Thank you.

<img width="860" alt="Screen Shot 2020-09-10 at 5 34 14 PM" src="https://user-images.githubusercontent.com/70870126/92831933-dc490c80-f38b-11ea-9978-eab54d7fa051.png">

**Comment by yyz20002008** [comment]
another testcase:
https://leetcode.com/submissions/detail/393963589/testcase/

ok interesting, it sitll shows wrong.

![image](https://user-images.githubusercontent.com/1105915/92832503-baf51a00-f3a5-11ea-81a3-548093fdc7b8.png)

**Comment by lc-kay** [comment]
@yyz20002008  

When I tested the other test case, it was also accepted. Maybe try removing the blank line in line 2? 

<img width="1414" alt="Screen Shot 2020-09-10 at 5 41 21 PM" src="https://user-images.githubusercontent.com/70870126/92832760-e8819980-f38c-11ea-9d9b-abde78a2c33c.png">

**Comment by yyz20002008** [comment]
I don't know why expected answer in your screen doesn't have more trailing 0, but mine does.

![image](https://user-images.githubusercontent.com/1105915/92833456-dd3b6780-f3a6-11ea-8577-ffebf308fce8.png)
anyway, if I use this answer, it was accepted.

`select project_id  ,Round(AVG(CAST(experience_years  AS decimal(5,2))),2) average_years 
from project p
join Employee e
on p.employee_id =e.employee_id 
group by project_id  
order by project_id`

**Comment by lc-kay** [comment]
@yyz20002008 

I simply copied and pasted the test cases from your link, I apologize for the inconsistency on your end.  I'm glad another answer you used was accepted. Do you still have any other issues in regards to this problem?

**Comment by yyz20002008** [comment]
Thanks for your time. Please close this issue.
