### ISSUE TITLE
Missing Test Case - 433. Minimum Genetic Mutation

### ISSUE THREAD

**Issue by mayank-01-ms** [LeetCode-Feedback/LeetCode-Feedback#9710]
#### LeetCode username

mayank01ms

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

There is a missing test case in problem number 433. Minimum Genetic Mutation
Test case:  start = "AAAAAAAT", end = "CCCCCCCC", bank = ["AAAAAAAC", "AAAAAAAA", "CCCCCCCC"]
Other similar test cases can be added where we are stuck in an infinite loop (if not handled). As here we will be in infinite loop as "AAAAAAAC" -> "AAAAAAAA" -> "AAAAAAAC" -> "AAAAAAAA" -> .... (loop)

#### Code used for Submit/Run operation

```
//  Minimum Genetic Mutation
class Solution {
public:
    int minMutation(string start, string end, vector<string>& bank) {
        unordered_map<string, int> mp;
        for(auto it : bank) mp[it]++;
        vector<char> arr = {'A', 'C', 'G', 'T'};

        if(mp.count(end) == 0) return -1;

        int steps = 0;
        queue<string> q;
        q.push(start);
        while(!q.empty()){
            int sz = q.size();
            while(sz--){
                auto s = q.front();
                if(s == end) return steps;
                q.pop();

                for(int i = 0; i < s.size(); i++){
                    char original = s[i];
                    for(char c : arr){
                        if(c == original) continue;
                        s[i] = c;
                        if(mp.count(s)){
                            q.push(s);
                        }
                    }
// changing character back to original since we are allowed to change a single char in one mutation
// also of we dont change back, our string will be completely changed, eg: AAAC -> TTTT and we might skip the answers which lie in between
                    s[i] = original;
                }
            }
            steps++;
        }
        // if after exploring all possibilites, still we could'nt found our answer
        return -1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

With the missing test case, the Leetcode OJ accepts the solution for the above code but it should give TLE for this test case.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
