### ISSUE TITLE
Missing Test Case - 433. Minimum Genetic Mutation

### ISSUE THREAD

**Issue by gaut2003** [LeetCode-Feedback/LeetCode-Feedback#9711]
#### Your LeetCode username
gaut_2003

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug
I have found a test case which is giving Time Limit Exceeded to an accepted code of mine. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minMutation(string start, string end, vector<string>& bank) {
        unordered_map<string, int> mp;
        for(auto val : bank) mp[val]++;
        vector<char> temp = {'A','C','G','T'};

        if(mp[end] == 0) return -1;

        int ans = 0;
        queue<string> q;
        q.push(start);
        while(!q.empty()){
            int n = q.size();
            while(n--){
                auto s = q.front();
                if(s==end) return ans;
                q.pop();

                for(int i=0;i<s.size();i++){
                    char prev = s[i];
                    for(auto c : temp){
                        if(c == prev) continue;
                        s[i] = c;
                        if(mp[s]) q.push(s);
                    }
                    s[i] = prev;
                }
            }
            ans++;
        }
        return -1;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code which I submitted got accepted but there is a test case which is giving TLE. 

#### Screenshots

![Screenshot (170)](https://user-images.githubusercontent.com/97660740/199436277-72e82f24-d632-4416-a11a-7d3a5b964803.png)

#### Additional context

The test case which is giving TLE is given below.
"AATAAAAT"
"TTTTTTTT"
["TTTTTTTT", "AATAAAAG", "AATAAAAA"]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
