### ISSUE TITLE
Broken link in contest page

### ISSUE THREAD

**Issue by gautamsw5** [LeetCode-Feedback/LeetCode-Feedback#9713]
#### Your LeetCode username

gautamsw5

#### Category of the bug
- [x] Bug in webpage

#### Description of the bug

On LeetCode contest page, if you go to a problem and then go to my submissions, and click a previous submission and click edit code, the code you see is not the code submitted in that submission but the most recently submitted code.

#### Screenshots
Problem Page:

![image](https://user-images.githubusercontent.com/72446354/199467877-cb4c05a5-3558-4f00-9163-ccf93cabbb0c.png)

My submissions Page:
![image](https://user-images.githubusercontent.com/72446354/199467911-0a2719a8-af1b-405d-95dc-1aca2b2538be.png)

Previous submission page (the one with WA):
![image](https://user-images.githubusercontent.com/72446354/199467938-1d33f275-3bda-43e2-a0ce-5c97c3ced237.png)

Page opened after clicking on edit code:
![image](https://user-images.githubusercontent.com/72446354/199467984-97031ac5-7399-45c4-bbd7-7cea6806184c.png)

You can see that the code from line 23 is different in the last two images.

This is very frustrating in the contest when you are trying different approaches and suddenly realize that a slight modification in a previous submission could solve the problem and forget that Edit Code doesn't work.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/2392913?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR
