### ISSUE TITLE
Isse with Java Compiler 

### ISSUE THREAD

**Issue by ejones12** [LeetCode-Feedback/LeetCode-Feedback#9715]
There seems to be an issue with the Java compiler and the Solution class. Each time I try to use the Java compiler, I receive the below issue
 
![issue](https://user-images.githubusercontent.com/49533066/199534057-2d9b9ccc-6341-4c9b-ae2b-1ad71909448e.JPG)
"class Solution is public, should be declared in a file named Solution.java(compiler.err.class.public.should.be.in.file)"

I have attempted to reset the code definiton and refresh the page multiple times, but this issue continues to occur. This is making it difficult for me to practice and see where the errors may be in my own code. Please advise on how to fix this, Thank you.

**Comment by nskybytskyi** [comment]
Uh oh, remove `public` so it becomes simply `class Solution`. You can see my example solution [here](https://leetcode.com/submissions/detail/835573135/). It's a mystery to me why the default code contains `public`. We need somebody with more knowledge of how old problems were designed.
