### ISSUE TITLE
Missing Test Case - 433. Minimum Genetic Mutation

### ISSUE THREAD

**Issue by AyushGupta2114** [LeetCode-Feedback/LeetCode-Feedback#9716]
#### Category of the bug
- [x] Question

#### Description of the bug
" There is also a gene **_bank bank_** that records all the valid gene mutations. A gene must be in bank to make it a valid gene string. "
Here at this point bank is two times that is wrong 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by nskybytskyi** [comment]
First, this is not a "missing testcase".

Second, "gene bank" refers to the semantic meaning of the function argument and `bank` refers to its name. In other words, your function has a parameter `bank` that represents a gene bank.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. Please consider nskybytskyi's comment.
