### ISSUE TITLE
Missing Test Case - 433. Minimum Genetic Mutation

### ISSUE THREAD

**Issue by akshyat02** [LeetCode-Feedback/LeetCode-Feedback#9717]
#### LeetCode username
[akshyat02](https://www.leetcode.com/akshyat02)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
My code perfectly work with the given text cases in all code editors except on LeetCode. I don't know why :(

#### Code you used for Submit/Run operation

```
class Solution {
    public int minMutation(String start, String end, String[] bank) {
        int count=0;
        boolean isPresent=false;
        for(String s: bank){
            if(s==end){
                isPresent = true;
            }
        }
        if(isPresent){
            for(int i=0;i<8;i++){
                if(start.charAt(i)!=end.charAt(i)){
                    count++;
                }
            }
        }
        else{
            return -1;
        }

        return count;
    }
}
```

#### Language used for code
Java

#### Expected behavior

I expected the code to be accepted successfully.

#### Screenshots

LeetCode Output
![LeetCodeBug](https://user-images.githubusercontent.com/77544963/199560081-9e3fec71-ba84-4a72-a159-5368d1c9d33e.png)

VS Code Editor Output with same test case
![LeetCodeBugSol](https://user-images.githubusercontent.com/77544963/199561091-24540d19-e7ea-4b48-97d4-cf7446f5480a.png)

**Comment by nskybytskyi** [comment]
First, this is not a "missing testcase".

Second, your code contains undefined behavior. You should not compare strings in Java with `operator==`. See [here](https://stackoverflow.com/questions/513832/how-do-i-compare-strings-in-java) to understand why.

**Comment by akshyat02** [comment]
Yes, I should .equals for comparing strings. But,

When I changed == to .equals to compare strings then also I get wrong
answers, But in other code editors it works fine. ( tested with same test
cases as given in examples )

**Comment by nskybytskyi** [comment]
> tested with same test cases as given in examples

There are test cases beyond samples. Getting AC on samples does NOT guarantee getting AC on all tests.

Your solution assumes that there is always a direct path from `start` to `end`. It is not always the case. One example is
```
"AAAAAAAA"
"AAAAAAGG"
["AAAAAAAC", "AAAAAACC", "AAAAAACG", "AAAAAAGG"]
```

Here you cannot change `A` directly to `G`. You have to go through `C` instead, which increases the distance. Feel free to use this test case and the discuss forum to debug your code.

**Comment by akshyat02** [comment]
Got it. :)
