### ISSUE TITLE
Missing Test Case - 433. Minimum Genetic Mutation

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#9718]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Solution with AC verdict gets stuck in an infinite loop on test case
```
"AACCGGTT"
"AACCGGTA"
["AACCGGTG", "AACCGGGG", "AACCGGGT", "AACCGGTT"]
```

#### Code you used for Submit/Run operation

[Submission link](https://leetcode.com/submissions/detail/835529721/).

```py
import collections

def viableMutation(current_mutation, next_mutation):
    changes = 0
    for i in xrange(len(current_mutation)):
        if current_mutation[i] != next_mutation[i]:
            changes += 1
    return changes == 1

class Solution(object):
    def minMutation(self, start, end, bank):
        """
        :type start: str
        :type end: str
        :type bank: List[str]
        :rtype: int
        """
        queue = collections.deque()
        queue.append([start, start, 0]) # current, previous, num_steps
        while queue:
            current, previous, num_steps = queue.popleft()
            if current == end:  # in BFS, the first instance of current == end will yield the minimum
                return num_steps
            for string in bank:
                if viableMutation(current, string) and string != previous:
                    queue.append([string, current, num_steps+1])
        return -1
```

#### Language used for code

Python 2

#### Expected behavior

The expected verdict is TLE.

#### Additional context

Multiple issues with the same title were opened today, including #9710 #9711 #9716 and #9717 

#9710 and #9711 contain different solutions and different suggested test cases
- Those test cases do NOT cause this solution to TLE. 
- Test case suggested in this issue does NOT cause those solutions to TLE.

#9716 and #9717 are fake issues that have nothing to do with missing test cases. Feel free to close them if you trust my word.

Presented solution belongs to user [lee12jin](https://leetcode.com/lee12jin/) as posted in this discuss [thread](https://leetcode.com/problems/minimum-genetic-mutation/discuss/91489/Python-Solution-using-BFS). Suggested test case belongs to user [jayzha](https://leetcode.com/jayzha/) as commented in the same discuss thread. Neither of them appears to be active now so it is unlikely that they'll help with this issue.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
