### ISSUE TITLE
1167. Minimum Cost to Connect Sticks

### ISSUE THREAD

**Issue by santanu33** [LeetCode-Feedback/LeetCode-Feedback#972]
#### Your LeetCode username
santanu_33

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

examples given are not clear.

#### Additional context

Examples are not comprehensive. it should be something like
```
Example 1
sticks = [2,4,3]
Step 1:
cost -> 2+3 = 5
result -> [5,4]
Step 2:
cost -> 5+4 = 9
result -> [9]
FINAL COST =5 + 9 = 14
```

```
Example 2
sticks = [1,8,3,5]
step 1:
cost -> 1+3 = 4
result -> [4,8,5]
step 2:
cost -> 4+5 = 9
result -> [9,8]
step 3:
cost -> 9+8 = 17
result = [17]
FINAL COST = 4 + 9 + 17 = 30
```

**Comment by lc-kay** [comment]
Hi @santanu33 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @santanu33 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
