### ISSUE TITLE
页面显示错误

### ISSUE THREAD

**Issue by wuke32767** [LeetCode-Feedback/LeetCode-Feedback#9722]
**Bug 类型**
ui
**描述**
滚动条到了更多操作页面上方了
**屏幕截图**
![图片](https://user-images.githubusercontent.com/69496447/199643315-01c4a932-6f59-45d1-a4e9-53e85c519e92.png)

**额外的上下文**
Firefox 106.0.3

**Comment by feiceh** [comment]
你好，当前题目问题已修复，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励。
