### ISSUE TITLE
Possible incorrect solution - 295. Find Median from Data Stream

### ISSUE THREAD

**Issue by 3multid** [LeetCode-Feedback/LeetCode-Feedback#9724]
#### Your LeetCode username

3multid

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution is incorrect, unless I misunderstood the question.

#### Code you used for Submit/Run operation

```
// Find Median from Data Stream
from collections import deque

class MedianFinder(object):

    def __init__(self):
        self.dq = deque()
        self.even = True

    def addNum(self, num):
        """
        :type num: int
        :rtype: None
        """
        self.dq.append(num)
        if self.even:
            self.even = False
            if len(self.dq) > 1:
                self.dq.popleft()
        else:
            self.even = True

    def findMedian(self):
        """
        :rtype: float
        """
        if self.even:
            return 0.5 * (self.dq[0] + self.dq[1])
        else:
            return self.dq[0]


# Your MedianFinder object will be instantiated and called as such:
# obj = MedianFinder()
# obj.addNum(num)
# param_2 = obj.findMedian()
```

#### Language used for code

Python

#### Expected behavior

For the testcase with "addNum" queries list: [6, 10, 2, 6, 5, 0, 6, 3, 1, 0, 0], the "findMedian" queries right afterwards should return [6, 8, 10, 6, 2, 4, 6, 5.5, 5, 2.5, 0] as my code did, but the solution returned a different answer.
Full input:
```
["MedianFinder","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian","addNum","findMedian"]
[[],[6],[],[10],[],[2],[],[6],[],[5],[],[0],[],[6],[],[3],[],[1],[],[0],[],[0],[]]
```

#### Screenshots

![image](https://user-images.githubusercontent.com/45973506/199665925-5cb228fe-7042-4371-856e-778080445341.png)

**Comment by nskybytskyi** [comment]
Hi there 👋

I agree that the statement is rather unclear and should be updated. "middle value in an **ordered** integer list" refers to sorting the list first and then finding the middle value. So after first three `addNum` operations of your test case the ordered list looks like `[2, 6, 10]`, and the median is indeed `6`.

I am not entirely sure what is the best way to paraphrase it to avoid confusion. Feel free to suggest possible ways to clarify the statement if you have any ideas.

**Comment by 3multid** [comment]
I think it should be explained more: "middle value in an ordered list (either non-decreasing or non-increasing)", so it won't be confused with ordered data structures i.e. list, dictionary and tuple in Python.
Btw I confused the median definition and thanks for clarifying it.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem and decided won't change the statement. We appreciate your support!
