### ISSUE TITLE
Missing Test Case - 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by YurySudak** [LeetCode-Feedback/LeetCode-Feedback#9727]
#### Your LeetCode username

user7060QX

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

In description of task is written: You must write an algorithm with O(log n) runtime complexity.
But winner is code that just traversal through array with O(n) runtime complexity
You should add test cases with array's length > 100000

#### Code you used for Submit/Run operation

This code shouldn't be passed!
```
class Solution {
    public int search(int[] nums, int target) {
        for (int i = 0; i < nums.length; i++) 
            if (nums[i] == target) return i;
        return -1;
    }
}
```

#### Language used for code
Java

**Comment by nskybytskyi** [comment]
Not everything can be easily enforced automatically. It is not practical to store a test case of size 4 Gb (integer array of size 10^9) just to TLE this solution. Most of the time it's fine to rely on some common sense and expect that users will not directly violate the instructions.

However, there are other, "interactive" problems on LC that **enforce** logarithmic complexity, like [278. First Bad Version](https://leetcode.com/problems/first-bad-version/). Feel free to use them instead.
