### ISSUE TITLE
Runtime Error for Range 

### ISSUE THREAD

**Issue by ankita199** [LeetCode-Feedback/LeetCode-Feedback#9728]
#### Your LeetCode username
ankita199

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [ ✔] Code Exception

#### Description of the bug
Problem 26 :: Array of Range is not working as expected

#### Code you used for Submit/Run operation
```
num = [1,2,3]
0..(num.length-1)).each do |i|
    puts i
end
```

#### Language used for code

Ruby

#### Expected behavior

- It should not throw the Run time exception

#### Screenshots

![Screenshot from 2022-11-02 13-54-19](https://user-images.githubusercontent.com/9448677/199774475-f6e4e11d-79b3-4523-a36b-579412a8193e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.  Please use the template for the implementation or use the playground for debugging. We appreciate your support!
