### ISSUE TITLE
Missing Test Case - 2317. Maximum XOR After Operations

### ISSUE THREAD

**Issue by 0504Shreyansh** [LeetCode-Feedback/LeetCode-Feedback#9729]
#### Your LeetCode username

jainshreyansh163

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

Must use multiple zero containing vector in order to generate maximum element as zero where it might get stuck.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
```int n = nums.size();
        if(n==1) return nums[0];
        
        int x = *max_element(nums.begin(),nums.end());
        int bits = log(x)/log(2) + 1;
        int j = 0, ans = 0;
        
        while(bits--) {
            int c = 0;
            for(auto i:nums) {
                if(i&(1<<j)) {
                    c = 1; 
                    ans += (pow(2,j));
                    break;
                }
            }
            j++;
        }
        
        return ans;```
    }
};
```

#### Language used for code
C++

#### Expected behavior

When the vector contains maximum element as 0, taking out logarithm of 0 fails, so when multiple zeroes or all zeroes are present in a vector, it might fail.

#### Screenshots

![Screenshot (122)](https://user-images.githubusercontent.com/113186607/199783899-60c16692-e2b9-4bb7-997d-1c81ed920923.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've received Compile error instead of Runtime Error when we submit your code. 
https://leetcode.com/submissions/detail/836808780/
