### ISSUE TITLE
Compare Version Numbers 

### ISSUE THREAD

**Issue by pvallem** [LeetCode-Feedback/LeetCode-Feedback#973]
#### Your LeetCode username
praneethkits

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Problem number 165, compare version numbers. Solution is accepted with a bug. My test case is "1.00.1, 1.0.2". In this case my code return 0 instead of 1. When submitted code is accepted.

#### Code you used for Submit/Run operation

```
// Compare Version Numbers 
class Solution {
    public int compareVersion(String version1, String version2) {
        String[] v1 = version1.split("\\.");
        String[] v2 = version2.split("\\.");
        int iterSize = Math.min(v1.length, v2.length);
        int i=0;
        while (i<iterSize && v1[i].equals(v2[i])) {
            i++;
        }
        // System.out.println("i: " + i + ", iterSize: " + iterSize);
        if (i == iterSize) {
            if (iterSize == v1.length)  {
                while (i<v2.length && Integer.valueOf(v2[i]) == 0) {
                    i++;
                }
                if (i==v2.length) {
                    return 0;
                }
                return -1;
            } else if (iterSize == v2.length) {
                while (i<v1.length && Integer.valueOf(v1[i]) == 0) {
                    i++;
                }
                if (i==v1.length) {
                    return 0;
                }
                return 1;
            }
        }
        int v1Val = Integer.valueOf(v1[i]);
        int v2Val = Integer.valueOf(v2[i]);
        return Integer.compare(v1Val, v2Val);
    }
}
```

#### Language used for code
java

#### Expected behavior
Code should have not been accepted. Fail the solution with at least one test case failed.

**Comment by lc-kay** [comment]
Hi @pvallem 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pvallem 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
