### ISSUE TITLE
Probable incorrect test case - 2343. Query Kth Smallest Trimmed Number

### ISSUE THREAD

**Issue by batulsingh** [LeetCode-Feedback/LeetCode-Feedback#9730]
#### Your LeetCode username
batulsingh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Inconsistent Test Cases 

#### Description of the bug
Inconsistent test cases conflicting the expected behavior mentioned in Example 2 of the question when the same value occurs more than once in the trimmed array. One of the test cases expects first occurrence of the repeated value and the other one expects the last occurrence.

#### Code you used for Submit/Run operation

```
// [Query Kth Smallest Trimmed Number](https://leetcode.com/explore/item/4490)
class Solution {
     public static int[] smallestTrimmedNumbers(String[] nums, int[][] queries) {
        int resultSize = queries.length;
        int[] result = new int[resultSize];
        long[] tempArray = new long[nums.length];
        String[] numsCopy = new String[nums.length];
        int k = 0;
        while(k < resultSize){
            for(int m = 0; m < nums.length; m++){
                numsCopy[m] = nums[m];
            }
            int trimSize = queries[k][1];
            for(int i = 0; i < nums.length; i++){
                numsCopy[i] = trimString(numsCopy[i], trimSize);
                tempArray[i] = Long.parseLong(numsCopy[i]);
            }
            result[k] = findKthMinIndex(tempArray, queries[k][0]);
            k++;
        }
        return result;
    }

    private static String trimString(String str, int trimSize) {
        int strSize = str.length();
        return str.substring(strSize-trimSize);
    }

    private static int findKthMinIndex(long[] arr, int k){
        long[] arrCopy = new long[arr.length];
        for(int i = 0; i < arr.length; i++){
            arrCopy[i] = arr[i];
        }
        Arrays.sort(arrCopy);
        long kthMin = arrCopy[k-1];
        int kthMinIndex = 0;
        for(int j = 0; j < arr.length; j++){
            if(arr[j] == kthMin){
                kthMinIndex = j;
            }
        }
        return kthMinIndex;
    }
}
```

#### Language used for code
Java

#### Expected behavior

For the shared brute force solution, these two test cases are probably inconsistent
**Input1**: 
["24","37","96","04"]
[[2,1],[2,2]]

Expected: [3,0]
(Either this should be [0,0] or the expected result for the Input2 below should be [10,0,9,9,1,6,10,6,9])

**Input2**: ["325240361872","440618160237","785744447413","820980201297","470082520306","874146483840","425300857082","088636787077","813218016629","459000328006","188683382600"]
[[6,7],[4,4],[1,8],[11,10],[4,8],[11,6],[1,1],[3,1],[11,10]]

 Output: [10,0,9,9,1,6,10,6,9]
Expected: [10,0,9,9,1,6,5,0,9] 

As mentioned in the example 2, in case of duplicate values after trimming, we have to consider the smaller index among the two repeated values. But the expected result considers the larger index(second/last occurrence of repeated value 4 for Input1). For expected output in case of Input2, this assumption doesn't hold as the expected output is considering the first occurrence of repeated values 0 and 2 when the trimmed array is [**2**, 7, 3, 7, 6,** 0**, **2**, 7, 9, 6, **0**]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
