### ISSUE TITLE
Need to replace the word graph with tree in the following context

### ISSUE THREAD

**Issue by anudeepkatukojwala** [LeetCode-Feedback/LeetCode-Feedback#9731]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Error in the following link: https://leetcode.com/explore/featured/card/leetcodes-interview-crash-course-data-structures-and-algorithms/707/traversals-trees-graphs/4614/

Need to replace the word graph with tree under Trees topic in the below text(taken from above link):

The things that define a tree in most algorithm problems are:

The graph is a directed graph.
The graph only has one connected component. That means all nodes are connected.
The graph is acyclic (there are no cycles), although this is implied by the next requirement.
One node has an indegree of zero. This is called the root. All other nodes have an indegree of one.
<img width="1440" alt="Screen Shot 2022-11-03 at 1 38 32 PM" src="https://user-images.githubusercontent.com/31664575/199829259-23bf79fe-ad11-4b92-8ba9-8ce1a2d5af75.png">

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
