### ISSUE TITLE
Bug with `static` keyword in Java solution of Kth Smallest Element in a BST

### ISSUE THREAD

**Issue by SleeplessChallenger** [LeetCode-Feedback/LeetCode-Feedback#9732]
#### Your LeetCode username

SleeplessChallenger

#### Category of the bug
- [YES] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Java solution for Kth Smallest Element in a BST runs well with `static` in **Run Code Result** section, but fails the same case in **submit** section.
However, if I remove `static` keyword, it passes all the cases smoothly

Test case that fails: 
```
[5,3,6,2,4,null,null,1]
3
```
#### Code you used for Submit/Run operation

Below code runs well
```
class Solution {
    private int index = 0;
    private int nodeValue = 0;
    
    public int kthSmallest(TreeNode root, int k) {
        traverseTree(root, k);
        return nodeValue;
    }
    
    private void traverseTree(TreeNode root, int k) {
        if (root != null && k > this.index) {
            traverseTree(root.left, k);
            System.out.println(root.val + " " + this.index); 
            if (this.index < k) {
                this.index++;
                this.nodeValue = root.val;
                traverseTree(root.right, k);
            }
        }
    }
}
```

Below code has described above issue

```
class Solution {
    private static int index = 0;
    private static int nodeValue = 0;
    
    public int kthSmallest(TreeNode root, int k) {
        traverseTree(root, k);
        return nodeValue;
    }
    
    private void traverseTree(TreeNode root, int k) {
        if (root != null && k > this.index) {
            traverseTree(root.left, k);
            System.out.println(root.val + " " + this.index); 
            if (this.index < k) {
                this.index++;
                this.nodeValue = root.val;
                traverseTree(root.right, k);
            }
        }
    }
}

```
#### Language used for code

Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
