### ISSUE TITLE
Problem on Tree Node (Invalid Testcase showed)

### ISSUE THREAD

**Issue by Safat99** [LeetCode-Feedback/LeetCode-Feedback#9733]
#### Your LeetCode username

Safat99

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

I cannot run any code on this problem. All I get is that it generates an invalid test case that keeps saying "foreign key p_id =  does not exist in the Tree table" no matter what I write on the code. 
Because of this, I couldn't get the SQL 1 badge. I solved all the other 32/33 problems.

#### Language used for code

SQL

#### Screenshots

![Screenshot from 2022-11-03 01-34-50](https://user-images.githubusercontent.com/38386689/199831908-6bf6bc37-fc6b-445a-adc0-3cdaccf1d79b.png)
![Screenshot from 2022-11-02 17-41-51](https://user-images.githubusercontent.com/38386689/199831923-7fbacbb0-119c-4a0e-b153-6f3ea5fe60a2.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted try to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Safat99** [comment]
I couldn't run any single code with this problem. The language to execute the code that I used is SQL.

```
select * from Tree;
```
At least this should give a simple result showing the Tree table. But just says "foreign key p_id =  does not exist in the Tree table"

**Comment by EngineerAditijain** [comment]
I am also facing the same problem while solving the problem "Tree Node"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ZinebAg** [comment]
Hi, I have the same issue too.

**Comment by godhamanthan** [comment]
Invalid Test Case, Facing same issue.

**Comment by saraswathi2000** [comment]
Facing the same issue ,Please Resolve it soon

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/2519313?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judge working correctly right now. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
