### ISSUE TITLE
345. Reverse Vowels of a String (Wrong solution detail)

### ISSUE THREAD

**Issue by bluejv7** [LeetCode-Feedback/LeetCode-Feedback#9734]
#### Your LeetCode username
bluejv7

#### Category of the bug
- Solution
- Language

#### Description of the bug
The solution says:
> Keep incrementing the left pointer start until it's pointing to a non-vowel character.
Keep decrementing the right pointer end until it's pointing to a non-vowel character.

The wording of the solution is wrong.  The code (correctly) shows the left pointer increments until it sees a vowel character or increments as long as it sees a non-vowel character.  Similarly for the right points, decrements until it sees a vowel character or decrements as long as it sees a non-vowel character.

#### Screenshots
Wrong description:
![image](https://user-images.githubusercontent.com/1515020/199864553-6ec5b242-3d4a-439d-9cc7-fbd19a9d03f1.png)

Java example for start pointer:
![image](https://user-images.githubusercontent.com/1515020/199864592-37377a0d-ed60-4370-ac6f-e5fb46fbe12a.png)

Java example for end pointer:
![image](https://user-images.githubusercontent.com/1515020/199864619-d1940bbf-a4dc-4f48-81ec-c6603265b854.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
