### ISSUE TITLE
[345. Reverse Vowels of a String] Wrong java solution

### ISSUE THREAD

**Issue by skkedia** [LeetCode-Feedback/LeetCode-Feedback#9735]
Hi Team,

For the leetcode problem 345 the java solution provided is wrong.

`class Solution {
    // Return true if the character is a vowel (case-insensitive)
    boolean isVowel(char c) {
        return c == 'a' || c == 'i' || c == 'e' || c == 'o' || c == 'u'
            || c == 'A' || c == 'I' || c == 'E' || c == 'O' || c == 'U';
    }
    
  
    void swap(char[] chars, int x, int y) {
        char temp = chars[x];
        chars[x] = chars[y];
        chars[y] = temp;
    }
    
    public String reverseVowels(String s) {
        int start = 0;
        int end  = int(s.size()) - 1;   // This syntax does not exist in java, it should be int end = s.length() -1; 
        // Convert String to char array as String is immutable in Java
        char[] sChar = s.toCharArray();
        
        // While we still have characters to traverse
        while (start < end) {
            // Find the leftmost vowel
            while (start < s.length () && !isVowel(sChar[start])) {
                start++;
            }
            // Find the rightmost vowel
            while (end >= 0 && !isVowel(sChar[end])) {
                end--;
            }
            // Swap them if start is left of end
            if (start < end) {
                swap(sChar, start++, end--);
            }
        }
        
        // Converting char array back to String
        return new String(sChar);
    }
};`

The below syntax should be corrected
int end  = int(s.size()) - 1;   // This syntax does not exist in java, it should be int end = s.length() -1; 

Thanks and Regards,
Siddhant Kedia.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by skkedia** [comment]
@LC-Pam Can you provide an update?

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by skkedia** [comment]
@LC-Pam does this not qualify for LC coins under issues reported?
