### ISSUE TITLE
新版UI：力扣题解中行内latex的\sqrt不显示

### ISSUE THREAD

**Issue by LetMeFly666** [LeetCode-Feedback/LeetCode-Feedback#9736]
**LeetCode 用户名**

[LetMeFly](https://leetcode.cn/u/tisfy/)

**Bug 类型**
- [ ] 题解

**描述**
力扣题解中行内latex的\sqrt不显示

**你使用的语言**
markdown

**期望行为**
修复行内latex的\sqrt不显示的BUG

**屏幕截图**
![demo](https://user-images.githubusercontent.com/56995506/199868637-595a1961-edca-43a3-b244-b363ef3b9eaf.gif)

此gif分别演示了在力扣题解中和Github中的latex行内公式```$\sqrt{5}$```的显示结果

暂未发现力扣题解对其他行内latex的错误显示

**Comment by feiceh** [comment]
感谢反馈，这个问题将会提交至负责团队核实；Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，后续可以点击「[https://support.leetcode-cn.com/hc/kb/section/1115013」](https://support.leetcode-cn.com/hc/kb/section/1115013%E3%80%8D) 提交工单反馈，请知晓。
