### ISSUE TITLE
1. Two Sum

### ISSUE THREAD

**Issue by hrushikeshkalamkar** [LeetCode-Feedback/LeetCode-Feedback#9737]
#### Category of the bug
- [ Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.] Question
- [ ] Solution
- [ Java] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int[] twoSum(int[] nums, int target) {
        int result[] = new int[2];
		for (int i = 0; i < nums.length; i++) {
			for (int j = i+1; j < nums.length; j++) {
				if (nums[i] + nums[j] == target) {
					result = new int[] { i, j };
                }
			}
		}
		return result;
    }
}
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
