### ISSUE TITLE
2. 两数相加、198. 打家劫舍 通过的提交 点进去 看不到 执行用时分布图表

### ISSUE THREAD

**Issue by JohnChenLiang** [LeetCode-Feedback/LeetCode-Feedback#9738]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![1667537138592](https://user-images.githubusercontent.com/30498675/199889830-e1133ee5-3786-44a6-9ce5-a2c35ffc0a36.jpg)
![1667537255687](https://user-images.githubusercontent.com/30498675/199890010-a810ef7c-7f5c-4369-b981-79ac2b6a0b23.jpg)
![image](https://user-images.githubusercontent.com/30498675/199890074-c35c6c8a-26a8-465f-9103-d81446dbf68e.png)

**额外的上下文**
添加额外的上下文信息
你们力扣就是这么解决问题的？把bug不修，然后把我工单给删了，工单删了 bug就修完了是吧。之前同一个ISSUE 问题没解决 就close了，你们就是这么解决bug的？我还以为leetcode是个不错的公司呢，原来解决bug就靠 删除工单和直接不解决就close是吧

**Comment by BrambleWave** [comment]
请问下您具体遇到的是哪个 bug ，我们的存量缺陷基本已修复完毕。

**Comment by JohnChenLiang** [comment]
标题啊 2. 两数相加、198. 打家劫舍 通过的提交 点进去 看不到 执行用时分布图表

**Comment by BrambleWave** [comment]
> 标题啊 2. 两数相加、198. 打家劫舍 通过的提交 点进去 看不到 执行用时分布图表

给你带来的不好体验万分抱歉，应该是在工单合并的时候造成的操作失误。
这个问题之前已经提交至开发处查看，由于修复成本较高，所以优先级较低。我们已经内部调整期优先级，会尽快给予结果。
万分抱歉。

**Comment by BrambleWave** [comment]
此问题已完成修复，再次感谢您对力扣的支持。

**Comment by BrambleWave** [comment]
有问题您可以再次反馈。
