### ISSUE TITLE
Missing Test Case - 583. Delete Operation for Two Strings

### ISSUE THREAD

**Issue by Siddhant609** [LeetCode-Feedback/LeetCode-Feedback#9739]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
What is the missing test case and what is the code that can get accepted but fails on the test case?
