### ISSUE TITLE
Missing Test Case : 23. Merge k Sorted Lists

### ISSUE THREAD

**Issue by thecapedcrusaderr** [LeetCode-Feedback/LeetCode-Feedback#974]
My code has been accepted for the Merge k Sorted Lists Problem . But i found one test case where my code gives wrong answer, and it is missing from all available test cases for the above problem.

**Code**

/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* mergeKLists(vector<ListNode*>& lists)
    {
        
        int n = lists.size();
        if(n==0)return NULL;
        
        if(n==1)
        {
            if(!lists[0])return NULL;
        }
        
        if(n==2)
        {
            if(!lists[0] && !lists[1])return NULL;
        }
        
        ListNode* nw = new ListNode();
        ListNode* root = nw;
        
        int i = 0;
        
        while(1)
        {
            int num = INT_MAX, index = -1;
            for(int j = 0; j < n ; j++)
            {
                if(!lists[j])continue;
                else
                {
                    if(num > lists[j]->val)
                    {
                        num = lists[j]->val;
                        index = j;
                    }
                }
            }
            if(index == -1)break;
            
            if(i==0)
            {
                nw->val = lists[index]->val;
                i++;
                lists[index] = lists[index]->next;
                continue;
            }
            ListNode* here = new ListNode();
            here->val = lists[index]->val;
            here->next = NULL;
            lists[index] = lists[index]->next;
            nw->next = here;
            nw = nw->next;
        }
        return root;
    }
};

**TestCase :** [[],[],[],[],[]]

**Comment by lc-kay** [comment]
Hi @thecapedcrusaderr, 

Can you please provide the entire code you used for submit or the submission details page? I am unable to verify your code with what you provided in bullet points. Thank you so much!

**Comment by thecapedcrusaderr** [comment]
**Code :**
class Solution {
public:
    ListNode* mergeKLists(vector<ListNode*>& lists)
    {
        
        int n = lists.size();
        if(n==0)return NULL;
        
        if(n==1)
        {
            if(!lists[0])return NULL;
        }
        
        if(n==2)
        {
            if(!lists[0] && !lists[1])return NULL;
        }
        
        ListNode* nw = new ListNode();
        ListNode* root = nw;
        
        int i = 0;
        
        while(1)
        {
            int num = INT_MAX, index = -1;
            for(int j = 0; j < n ; j++)
            {
                if(!lists[j])continue;
                else
                {
                    if(num > lists[j]->val)
                    {
                        num = lists[j]->val;
                        index = j;
                    }
                }
            }
            if(index == -1)break;
            
            if(i==0)
            {
                nw->val = lists[index]->val;
                i++;
                lists[index] = lists[index]->next;
                continue;
            }
            ListNode* here = new ListNode();
            here->val = lists[index]->val;
            here->next = NULL;
            lists[index] = lists[index]->next;
            nw->next = here;
            nw = nw->next;
        }
        return root;
    }
};

**Submission Details Page Link** : https://leetcode.com/submissions/detail/393362463/

**Comment by lc-kay** [comment]
Hi @thecapedcrusaderr 

Thank you for your submission. And what's the test case you're having an issue with?

**Comment by thecapedcrusaderr** [comment]
**Test Case :**  [[],[],[],[],[],[],[],[],[],[],[]]

My code gives wrong answer for this test case and this test case happens to be missing from your available set of test cases.

**Comment by lc-kay** [comment]
@thecapedcrusaderr 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @thecapedcrusaderr 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode username so I can assign 100 LeetCoins as the reward for this feedback. Also, as an important reminder, please submit code without hardcoded conditionals that skip certain test cases next time. Thank you for using LeetCode!

**Comment by thecapedcrusaderr** [comment]
Okay thanks, My username is hiteshan28.

**Comment by lc-kay** [comment]
@thecapedcrusaderr I just assigned you 100 LeetCoins for your contribution.
