### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by deepmachine786** [LeetCode-Feedback/LeetCode-Feedback#9740]
#### Your LeetCode username
<https://leetcode.com/technicalproduct786/>

#### Category of the bug
- [ ] Question 
- [ ] Solution
- [ ] Language
- [👍  ] Missing Test Cases 

#### Description of the bug
<All Tests are Passed But One Test Case Failed There is a Missing in the Test case.>

#### Code you used for Submit/Run operation

```
// Regular Expression Matching
import re

class Solution:
    def isMatch(self, s: str, p: str) -> bool:
        compiles = re.compile(p.lower()) # for the meatching of regular expression ...
        if not re.fullmatch(compiles, s):
            return "false"
        return "true" if len(s)<len(p) else "false"
        
```

#### Language used for code
<-- Python3 -->

**Comment by stormsunshine** [comment]
What is the missing test case?
