### ISSUE TITLE
Need to refresh the tab after every submission

### ISSUE THREAD

**Issue by gh4abhi** [LeetCode-Feedback/LeetCode-Feedback#9744]
#### Your LeetCode username
gh4abhi
![Leetcode](https://user-images.githubusercontent.com/63967165/199953318-76e0983f-99e1-484e-bba6-10f93f6fd415.png)
![Leetcode](https://user-images.githubusercontent.com/63967165/199953351-c1e18c18-63cb-4e4a-bd10-b3e9870b5d06.png)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by nskybytskyi** [comment]
Could you please provide more details on which browser you are using (together with its version and extensions/userscripts, if applicable)?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by gh4abhi** [comment]
> Could you please provide more details on which browser you are using (together with its version and extensions/userscripts, if applicable)?

Browser - Chrome.

**Comment by LC-Pam** [comment]
Thank you for your time. The problem should be fixed.  We appreciate your support!
