### ISSUE TITLE
Incorrect Solution Java - 345 Reverse Vowels of a String

### ISSUE THREAD

**Issue by abhinit21** [LeetCode-Feedback/LeetCode-Feedback#9745]
#### Your LeetCode username

abhinit21

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Article Issue for solution of Reverse Vowels of a String Java Language
-line 17 : `int end  = int(s.size()) - 1;`
+line 17 : `int end = s.length() - 1;`
It may be old version code could have been depreciated.

#### Code you used for Submit/Run operation

```
// Reverse Vowels of a String
class Solution {
    // Return true if the character is a vowel (case-insensitive)
    boolean isVowel(char c) {
        return c == 'a' || c == 'i' || c == 'e' || c == 'o' || c == 'u'
            || c == 'A' || c == 'I' || c == 'E' || c == 'O' || c == 'U';
    }
    
    // Function to swap characters at index x and y
    void swap(char[] chars, int x, int y) {
        char temp = chars[x];
        chars[x] = chars[y];
        chars[y] = temp;
    }
    
    public String reverseVowels(String s) {
        int start = 0;
        int end  = int(s.size()) - 1;
        // Convert String to char array as String is immutable in Java
        char[] sChar = s.toCharArray();
        
        // While we still have characters to traverse
        while (start < end) {
            // Find the leftmost vowel
            while (start < s.length () && !isVowel(sChar[start])) {
                start++;
            }
            // Find the rightmost vowel
            while (end >= 0 && !isVowel(sChar[end])) {
                end--;
            }
            // Swap them if start is left of end
            if (start < end) {
                swap(sChar, start++, end--);
            }
        }
        
        // Converting char array back to String
        return new String(sChar);
    }
};
```

#### Language used for code

Java

#### Expected behavior

Expected code to run on all test cases. But it had **Compile Error**

#### Screenshots

![image](https://user-images.githubusercontent.com/58618233/199955781-5f875ef1-8290-406a-ab1e-897ef011e950.png)

#### Additional context

Change to me made is in **line 17**

**-** `int end  = int(s.size()) - 1;`
**+** `int end = s.length() - 1;`

**Comment by abhinit21** [comment]
Duplicate and Additional actions of same Issues

- [ ] #9734 
- [ ] #9741 
- [ ] #9735

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
