### ISSUE TITLE
Missing Test Case - 2367. Number of Arithmetic Triplets

### ISSUE THREAD

**Issue by Piyushsinganjude** [LeetCode-Feedback/LeetCode-Feedback#9746]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by nskybytskyi** [comment]
This new "Contribute testcase" interface makes it easy to accidentally open an issue.
<img width="180" alt="Знімок екрана 2022-11-04 о 16 15 26" src="https://user-images.githubusercontent.com/25816558/199996656-13bb2a01-3b8c-4ce4-a994-6ec07c476741.png">
