### ISSUE TITLE
405错误 访问被阻断

### ISSUE THREAD

**Issue by Zuoxun** [LeetCode-Feedback/LeetCode-Feedback#9747]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

  **Hello WorldMaya**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
访问网站显示“很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。
您的请求ID是: 76b20f8c16675695602698047e72e5”
我什么都没做，前两天还能上。
我挂了VPN，但是关了VPN也不能上。

**你使用的语言**
C++

**你提交或者运行的代码**
```
// 无
```

**期望行为**
希望把我的IP加到防火墙白名单里

**屏幕截图**
<img width="526" alt="微信图片_20221104220135" src="https://user-images.githubusercontent.com/59754483/199991162-08932b30-cc2b-4e23-8374-ac3b323dcca8.png">

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给相关团队会尽快确认的，给您带来的不便敬请谅解。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先暂时关闭，后续使用中有任何问题欢迎点击「https://support.leetcode-cn.com/hc/kb/section/1115013」 提交工单反馈，请知晓～
