### ISSUE TITLE
146. Ambiguous test case with instruction "set or insert the value if the key is not already present"

### ISSUE THREAD

**Issue by MikeBusuttil** [LeetCode-Feedback/LeetCode-Feedback#975]
#### Your LeetCode username
hypertractive

#### Category of the bug
- [x] Question
- [x] Solution

#### Description of the bug
The question describes the "put" operation without specifying what should be done when a key is already present.  Then, at least one of the test cases calls for a "put" operation with a key already present.  The test case is...
["LRUCache","put","put","get","put","put","get"]
[[2],[2,1],[2,2],[2],[1,1],[4,1],[2]]
... with output ...
[null,null,null,2,null,null,-1]
Based on the given output the question should be reworded (solution provided below).
Another description of the bug is given in the question's discussion section: https://leetcode.com/explore/challenge/card/30-day-leetcoding-challenge/531/week-4/3309/discuss/211162/Ambiguous-instructions-%22set-or-insert-the-value-if-the-key-is-not-already-present%22

#### Code you used for Submit/Run operation

```
class LRUCache:
    def __init__(self, capacity: int):
        self.oldest = None
        self.newest = None
        self.cache = {}
        self.free_slots = capacity
        self.capacity = capacity
    def get(self, key: int) -> int:
        if key not in self.cache:
            return -1
        if self.capacity == 1:
            return self.cache[key]['val']
        if key == self.oldest and len(self.cache) > 1:
            self.oldest = self.cache[key]['newer']
        existing_newer, existing_older = self.cache[key]['newer'], self.cache[key]['older']
        if existing_newer == None:
            return self.cache[key]['val']
        elif existing_older == None:
            self.cache[existing_newer]['older'] = None
        else:
            self.cache[existing_newer]['older'] = self.cache[existing_older]['newer']
            self.cache[existing_older]['newer'] = self.cache[existing_newer]['older']
        
        existing_newest = self.newest
        self.cache[existing_newest]['newer'] = key
        self.cache[key]['newer'] = None
        self.cache[key]['older'] = existing_newest
        self.newest = key
        
        return self.cache[key]['val']
    def put(self, key: int, value: int) -> None:
        if key in self.cache:
            return -1
        if self.capacity == 1:
            self.cache = {key:{'val': value}}
            return None
        if self.free_slots:
            self.free_slots -= 1
            if not self.cache:
                self.oldest = key
        else:
            evictee = self.oldest
            self.cache[self.newest]['newer'] = key
            self.oldest = self.cache[self.oldest]['newer']
            self.cache[self.oldest]['older'] = None
            del self.cache[evictee]
        self.cache[key] = {'val': value, 'older': self.newest, 'newer': None}
        self.newest = key
        if self.cache[key]['older'] in self.cache:
            elder = self.cache[key]['older']
            self.cache[elder]['newer'] = key
```

#### Language used for code
Python3

#### Expected behavior
the following test set...
["LRUCache","put","put","get","put","put","get"]
[[2],[2,1],[2,2],[2],[1,1],[4,1],[2]]
... could yield the following result ...
[null,null,-1,1,null,null,-1]
... but should be removed due to the ambiguity in the question.  If the question is re-worded as per below, the test set should remain.

#### Solution
reword the question from...
[...]put(key, value) - Set or insert the value if the key is not already present. When the cache reached its capacity, it should invalidate the least recently used item before inserting a new item.[...]
...to...
[...]put(key, value) - Set or insert the value. When the cache reached its capacity, it should invalidate the least recently used item before inserting a new item.[...]
In this case, the test set in question can and should remain.

#### Screenshots
NA

#### Additional context
NA

**Comment by lc-kay** [comment]
Hi @MikeBusuttil 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @MikeBusuttil 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
