### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by bhupendraptlk** [LeetCode-Feedback/LeetCode-Feedback#9751]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test cases used in the problem contains only those test cases where the solution indexes are consecutive in nature.

Test cases used:
  Example 1:
    Input: nums = [2,7,11,15], target = 9
    Output: [0,1]
    In this example, 0 and 1 are consecutive.
  Example 2:
      Input: nums = [3,2,4], target = 6
      Output: [1,2]
      In this example, 1 and 2 are consecutive.
  Example 3:
        Input: nums = [3,3], target = 6
        Output: [0,1]
        In this example, 0 and 1 are consecutive.
**Test case that can be included to make the problem more clear:**
  Input: nums = [2,7,11,15], target = 13
  Output: [0,2]
In this test case, we cover the case where the numbers indexes are not consecutive. Here the numbers are present in the 0th index and 2nd index which leaves out the element '7' in the 1st index.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int[] twoSum(int[] nums, int target) {
        int arr[]=new int[2]; 
        for(int i=0;i<(nums.length-1);i++){
            for(int j=i+1;j<nums.length;j++){
                if((nums[i]+nums[j])==target){
                    arr[0]=i;
                    arr[1]=j;
                    break;
                }
            }
        }
        return(arr);
    }
}
```

#### Expected behavior

Covering the case where the indexes of the numbers whose sum is the target could be other than the (index) and (index+1).
  For example:
    Input: nums = [2,7,11,15], target = 13
    Output: [0,2]

**Comment by stormsunshine** [comment]
Why do you think such test cases are missing? There is a test case as follows.
```
[3,2,3]
6
```
Do you still think all test cases have consecutive indices?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Comment by bhupendraptlk** [comment]
The above mentioned test case is not part of the test cases I suppose. There is a test case with [3,2,4] where the target is '6', but I am unable to find a test case with [3,2,3] where the target is '6'.
Sharing a screenshot with you: 

![leetcode-sum](https://user-images.githubusercontent.com/70276148/200351441-b98b992d-e09b-43b8-b6c9-657d0b4e846a.png)
