### ISSUE TITLE
Missing Test Case - 1480. Running Sum of 1d Array

### ISSUE THREAD

**Issue by TIMHORT** [LeetCode-Feedback/LeetCode-Feedback#9752]
#### TIMHORT
TIMHORT

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
i was solving thus questiion and i have created code that words for three test data but when i used the same code on leetcode and run it it produces a different output than on the browswer (i used javascript) and for the first test case it says incorrect although the only difference is a space inside the list before comma, what is mean [1,4,5] is answer then my answer is  [1, 4, 5] i cant control the syntax of a array 

#### Code you used for Submit/Run operation
"
const runningSumList = [0];

const runningSum = function (nums) {
	const number = nums;
	for (let i = 0; i < number.length; i++) {
		runningSumList.push(runningSumList[i] + number[i]);
	}
	runningSumList.shift();
	console.log(runningSumList);
};

"
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Javascript

#### Expected behavior
code should work

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by TIMHORT** [comment]
Good Evening, I am sorry I am new to leetcode and didn’t relieaze that I had to include my variables inside of the function  Sent from Mail for Windows From: LC_MSent: Monday, November 7, 2022 7:29 PMTo: LeetCode-Feedback/LeetCode-FeedbackCc: TIMHORT; AuthorSubject: Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 1480. Running Sum of 1d Array (Issue #9752) Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
