### ISSUE TITLE
Missing Test Case - 1152. Analyze User Website Visit Pattern

### ISSUE THREAD

**Issue by Nasir-Kasumu** [LeetCode-Feedback/LeetCode-Feedback#9753]
#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question is a bit confusing for test cases. I didn't initially understand the pattern pairs until i looked up someone explaining the problem adding something about the pattern being any matching of ascending websites from the user with an emphasis on ascending would help some users understand the question more

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
