### ISSUE TITLE
862. Shortest Subarray with Sum at Least K - Solution Code TLE

### ISSUE THREAD

**Issue by CharryWu** [LeetCode-Feedback/LeetCode-Feedback#9756]
#### Your LeetCode username
charrywu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution code of https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/solution/ gives TLE submission error.

#### Code you used for Submit/Run operation

https://leetcode.com/submissions/detail/837037755/
```py
class Solution(object):
    def shortestSubarray(self, A, K):
        N = len(A)
        P = [0]
        for x in A:
            P.append(P[-1] + x)

        #Want smallest y-x with Py - Px >= K
        ans = N+1 # N+1 is impossible
        monoq = collections.deque() #opt(y) candidates, represented as indices of P
        for y, Py in enumerate(P):
            #Want opt(y) = largest x with Px <= Py - K
            while monoq and Py <= P[monoq[-1]]:
                monoq.pop()

            while monoq and Py - P[monoq[0]] >= K:
                ans = min(ans, y - monoq.popleft())

            monoq.append(y)

        return ans if ans < N+1 else -1
```

#### Language used for code

Python3

#### Expected behavior

Code from official solution should AC, not giving TLE errors

#### Screenshots

![image](https://user-images.githubusercontent.com/19372474/200088670-65abe2aa-ebf9-4eaf-b912-e50b901395b5.png)

**Comment by LC-Pam** [comment]
Thank you for your time. code received AC when we tested it: https://leetcode.com/submissions/detail/838768779/
 We appreciate your support!

**Comment by CharryWu** [comment]
Sometimes I still see TLE on this official solution using Python3 language. 
![image](https://user-images.githubusercontent.com/19372474/200407722-f033a331-d3b4-4941-aeac-7efcc7611d2a.png)
