### ISSUE TITLE
Missing Test Case - 589. N-ary Tree Preorder Traversal

### ISSUE THREAD

**Issue by HeyItWorked** [LeetCode-Feedback/LeetCode-Feedback#9757]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Example 2 has two consecutive nulls which doesn't clarify 'Each group of children is separated by the null value (See examples)' which causes confusion

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Each group of children is separated by null. Since 2 does not have children, its group is empty and a null was added. We appreciate your support!
