### ISSUE TITLE
Missing Test Case - 55. Jump Game

### ISSUE THREAD

**Issue by arkafreak** [LeetCode-Feedback/LeetCode-Feedback#9759]
The test case solution isn't provided for what if the index value of the last jumped index is greater than the actual jumps needed to reach the end of the array
like nums = [2,3,1,5,4]

like in here we jump twice and reach index 2, because nums[0] is 2 so we move on to nums[2] and as it is 1 we go to nums[2+1] , and nums[3] is value 5, so then we get nums[3+5] but the size of the array is only 5 , so we cant be able to reach the end of the array, yah we will reach but will surpass the end. 
#### Your LeetCode username

 @arkafreak  

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [.] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Jump Game
class Solution {
public:
bool canJump(vector<int>& nums) {
    int size=nums.size();
    int step=nums[0];
    for(int i=1;i<size;++i){
        step--;
        if(step<0)
           return false;
        if(nums[i]>step)
           step=nums[i];
    }
    return true;
}
};
```

#### Language used for code

C++

#### Expected behavior

expected to give error as no such index to be found, within n no. of indexes present the index value cant be more than n, so there must be an error.

The output must have been false;

#### Screenshots

![Screenshot 2022-11-05 130003](https://user-images.githubusercontent.com/77730711/200108393-fcffc709-d35a-43be-845d-e449f178fd00.png)
![Screenshot 2022-11-05 130028](https://user-images.githubusercontent.com/77730711/200108400-f2e9329f-34a7-4837-8cae-9725677e1c73.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. The statement said that nums[i] is the maximum jump. If nums[i] = 5, you can jump 1, 2, 3, 4, or 5 steps. You can still reach the last index. We appreciate your support!
