### ISSUE TITLE
152. Maximum Product Subarray. System returns incorrect value for custom Testcase.

### ISSUE THREAD

**Issue by Aleksandar1998** [LeetCode-Feedback/LeetCode-Feedback#976]
---
name: 152. Maximum Product Subarray
about: System returns incorrect result for custom test case.

---

#### LeetCode username
AssAssiNo1

#### Category of the bug
- Question

#### Description of the bug
For the Testcase [2,3,2,-2,-5,-1,3,2,8], system returns 240 as an expected result, but it should be 120.
 2 * 3 * 2 * (-2) * (-5) = 120. 

#### Code you used for Submit/Run operation

```
// 152. Maximum Product Subarray
class Solution {
    public int maxProduct(int[] nums) {
        int product = Integer.MIN_VALUE;
        int counter = 0;
        int negCurr = 1;
        for(int i = 0; i < nums.length; ++i){
            if(counter > 2){
                negCurr  = 1;
                counter = 0;
            }
            if(nums[i] < 0) counter++;
            negCurr *= nums[i];
            if(negCurr > product) product = negCurr;
            
        }

        return product;
    }
}
```

#### Language used for code
Java

#### Expected behavior
For the Testcase [2,3,2,-2,-5,-1,3,2,8], system returns 240 as an expected result, but it should be 120.
 2 * 3 * 2 * (-2) * (-5) = 120. 

#### Screenshots

![image](https://user-images.githubusercontent.com/49452446/92646165-49a26200-f2e6-11ea-979d-551a60039f90.png)

**Comment by caoxingdong** [comment]
The product of last five elements is 240

**Comment by lc-kay** [comment]
Hi @Aleksandar1998 

Can you please check your code? When I submitted it, it received wrong answer. If your code is accepted on your end, please let me know and link me your submission details. Thank you! 

https://leetcode.com/submissions/detail/393944642/

**Comment by Vikas-Jethwani** [comment]
The correct answer is 240.
-5*-1*3*2*8 = 240.
https://www.geeksforgeeks.org/maximum-product-subarray/
