### ISSUE TITLE
Missing Test Case - 2317. Maximum XOR After Operations

### ISSUE THREAD

**Issue by 0504Shreyansh** [LeetCode-Feedback/LeetCode-Feedback#9761]
#### Your LeetCode username

jainshreyansh163

#### Category of the bug

- [x] Missing Test Cases 

#### Description of the bug

Some of the solutions might require the calculation of number of bits of the maximum value and when the maximum value is zero, number of bits cannot be calculated as log function fails here. So, I would like to request to add some more testcases like [0,0,0,0] or multiple zeroes for better results.

#### Code you used for Submit/Run operation

```

class Solution {
public:
    int maximumXOR(vector<int>& nums) {
        
        int n = nums.size();
        if(n==1) return nums[0];
        
        int x = *max_element(nums.begin(),nums.end());
        int bits = log(x)/log(2) + 1;
        int j = 0, ans = 0;
        
        while(bits--) {
            int c = 0;
            for(auto i:nums) {
                if(i&(1<<j)) {
                    c = 1; 
                    ans += (pow(2,j));
                    break;
                }
            }
            j++;
        }
        
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Some of the solutions might require the calculation of number of bits of the maximum value and when the maximum value is zero, number of bits cannot be calculated as log function fails here. So, I would like to request to add some more testcases like [0,0,0,0] or multiple zeroes for better results.

#### Screenshots

![Screenshot (122)](https://user-images.githubusercontent.com/113186607/200125001-3af84081-c137-460a-857d-0c94c58e37ba.png)

#### Additional context

Just add the testcase I mentioned that's all.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
