### ISSUE TITLE
Missing Test Case - 118. Pascal's Triangle

### ISSUE THREAD

**Issue by aasthad27** [LeetCode-Feedback/LeetCode-Feedback#9762]
this testcase [[]]-->[[]]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
The constraint requires `numRows >= 1`. What do you want to say?

**Comment by aasthad27** [comment]
//closed
