### ISSUE TITLE
740 Delete and Earn

### ISSUE THREAD

**Issue by eyeamkd** [LeetCode-Feedback/LeetCode-Feedback#9763]
The official solution explanation for the problem doesn't consider the case of "x+1" while describing the first approach.  
>  However, because of the deletion, by taking x, we are no longer allowed to take x - 1. The largest number that we can still consider is x - 2.

As you can clearly see above, the solution says the largest number still to consider is "x-2" but there can be still an "x+2", especially when x is an arbitrary number. 

> let's say that we are currently at some arbitrary number x, where x is in nums one or more times.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The ticket is invalid. x is defined here as an argument to maxPoints (which is stated in the previous paragraph), and maxPoints only considers numbers less than or equal to x. We appreciate your support!
