### ISSUE TITLE
Missing Test Case - 2458. Height of Binary Tree After Subtree Removal Queries

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#9765]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9945093/1.txt)

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */

class Solution {
public:
    int dc[100001], d[100001];
    vector<int> n[100001];
    
    void dfs(TreeNode *root, int lvl) {
        n[lvl].push_back(root->val);
        d[root->val] = lvl;
        int m = lvl;
        if (root->left != nullptr) { dfs(root->left, lvl + 1); m = max(m, dc[root->left->val]); }
        if (root->right != nullptr) { dfs(root->right, lvl + 1); m = max(m, dc[root->right->val]); }
        dc[root->val] = m;
    }
    
    vector<int> treeQueries(TreeNode* root, vector<int>& queries) {
        dfs(root, 0);
        vector<int> ans;
        ans.reserve(queries.size());
        for (int q : queries) {
            int a = d[q] - 1;
            for (int nn : n[d[q]]) {
                if (nn == q) { continue; }
                a = max(a, dc[nn]);
            }
            ans.push_back(a);
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

![image](https://user-images.githubusercontent.com/11583428/200152741-65e777d2-6824-4986-9ded-270fbdfd7f0d.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
