### ISSUE TITLE
Missing Test Case - 165. Compare Version Numbers

### ISSUE THREAD

**Issue by glory-ka** [LeetCode-Feedback/LeetCode-Feedback#9766]
#### Your LeetCode username

glory-k

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code successfully passed all test cases. Should have failed. The program compare two character sequences by adding the ASCII value. This is wrong as the sum of the characters of the strings  '123' and '321' should be the same. 

#### Code you used for Submit/Run operation

```
class Solution {
    public int compareVersion(String version1, String version2) {
        
        int N = version1.length();
        int M = version2.length();

        for(int i =0, j =0; i < N || j < M; i ++, j ++){

            char vv1 = '\0', vv2 = '\0';
            boolean leading_zero = true;

            while(i < N && version1.charAt(i) != '.'){
                leading_zero = leading_zero && version1.charAt(i) == '0';
                vv1 += !leading_zero ? version1.charAt(i)  : '\0';
                i ++;
            }

            leading_zero = true;

            while(j < M && version2.charAt(j) != '.'){
                leading_zero = leading_zero && version2.charAt(j) == '0';
                vv2 += !leading_zero ? version2.charAt(j): '\0';
                j ++;
            }

            if(vv1 < vv2) return -1;
            else if(vv1 > vv2) return 1;  
            
        }
        return 0;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The code successfully passed all test cases. Should have failed. The program compare two character sequences by adding the ASCII value. This is wrong as the sum of the characters of the strings  '123' and '321' should be the same.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Please provide us your LCUS username.
