### ISSUE TITLE
Missing Test Case - 2461. Maximum Sum of Distinct Subarrays With Length K

### ISSUE THREAD

**Issue by shivambeenhere** [LeetCode-Feedback/LeetCode-Feedback#9767]
#### Your LeetCode username
shivambeenhere

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing Test Case - 
nums = [9,1,9,2]
k = 3

#### Code you used for Submit/Run operation

```
class Solution {
public:
    long long maximumSubarraySum(vector<int>& nums, int k) {
        unordered_set<int> st;
        long long curSum = 0, maxm = 0;
        
        for (int i = 0; i < k; i++) {
            curSum+= nums[i];
            st.insert(nums[i]);
        }
        if (st.size() == k) maxm = max(maxm, curSum);
        
        for (int i = k; i < nums.size(); i++) {
            curSum-= nums[i - k];
            curSum+= nums[i];
            st.erase(nums[i - k]);
            st.insert(nums[i]);
            st.insert(nums[i - k + 1]);
            
            if (st.size() == k) maxm = max(maxm, curSum);
        }
        return maxm;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
The Leetcode OJ accepts the solution but it should give Wrong Answer for this test case;

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We rejected to add the test case since all solutions failed after adding more test cases. We appreciate your support!
