### ISSUE TITLE
Missing Test Case - 2461. Maximum Sum of Distinct Subarrays With Length K

### ISSUE THREAD

**Issue by divsurana** [LeetCode-Feedback/LeetCode-Feedback#9768]
#### Your LeetCode username
vanradius

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The solution shouldn't work if it clears the cache when it encounters a duplicate yet, it does. The solution below was accepted but it wouldn't work for the following test case - 
`nums = [1,2,3,4,5,3,6,7], k = 5`
`Expected Output - 25`
`My Code Output - 15`

#### Code you used for Submit/Run operation
```
class Solution {
    public long maximumSubarraySum(int[] N, int k) {
        long max = 0, sum = 0;
        Set<Integer> s = new HashSet<>();
        for (int i = 0; i < N.length; i++) {
            if (s.size() == k) {
                s.remove(N[i - k]);
                sum -= N[i - k];
            }
            if (s.contains(N[i])) {
                s = new HashSet<>();
                sum = 0;
            }
            s.add(N[i]);
            sum += N[i];
            if (s.size() == k && sum > max) max = sum;
        }
        return max;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The above code should have failed but it got accepted. The above code fails for the valid test case I provided above.

#### Screenshots
<img width="868" alt="Screen Shot 2022-11-06 at 12 47 45 AM" src="https://user-images.githubusercontent.com/7173131/200154721-1f9ed074-43ce-433f-996a-dd2d652b44ac.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We rejected to add the test case since all solutions failed after adding more test cases. We appreciate your support!

**Comment by divsurana-sq** [comment]
Run this test case in the LC run module. The expected output is 25. That means the internal LC solution is incorrect or the question explanation is incorrect. Also, I tried the top solutions and they worked for this test case. I don’t understand what you mean by all solutions failed.
