### ISSUE TITLE
[6 1 3 4 5] Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by Miheerhasabnis** [LeetCode-Feedback/LeetCode-Feedback#9769]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Miheerhasabnis** [comment]
the peak element sum does not check the test case [6,1,2,3,4] itt get submitted

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
