### ISSUE TITLE
难度设定不一致

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#977]
剑指 Offer 66. 构建乘积数组  https://leetcode-cn.com/problems/gou-jian-cheng-ji-shu-zu-lcof/，难度为easy；
238. 除自身以外数组的乘积   https://leetcode-cn.com/problems/product-of-array-except-self/，  难度为medium。

其实是同一道题。

**Comment by feiceh** [comment]
感谢反馈，现在都是中等了。[积分](https://leetcode-cn.com/points/)奉上，请查收。
