### ISSUE TITLE
Missing Test Case - 2461. Maximum Sum of Distinct Subarrays With Length K

### ISSUE THREAD

**Issue by uilnauyisDP** [LeetCode-Feedback/LeetCode-Feedback#9772]
#### Your LeetCode username
uilnauyis_DP

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

My latest submission passed got AC: https://leetcode.com/problems/maximum-sum-of-distinct-subarrays-with-length-k/submissions/837877167/

However, it actually will fail the test case in which 'nums' = [1, 3, 1, 4, 2] and k = 3

#### Code you used for Submit/Run operation

```
public class Solution {
    public long MaximumSubarraySum(int[] nums, int k) {
        var prev = new int[100001];
        for (var i = 0; i < 100001; i++) {
            prev[i] = -1;
        }
        var l = 0;

        var sum = new long[nums.Length];
        sum[0] = nums[0];
        for (var i = 1; i < nums.Length; i++) {
            sum[i] = sum[i - 1] + nums[i];
        }
        var last = 0;
        long res = 0;
        for (var i = 0; i < nums.Length; i++) {
            var val = nums[i];
            if (prev[val] != -1 &&
                i - prev[val] < k) {
                last = i;
            }
            prev[val] = i;
            if (i - last == k - 1) {
                res = Math.Max(sum[i] - sum[last] + nums[last], res);
                last++;
            }
        }
        return res;
    }
}
```

#### Language used for code

C#

#### Expected behavior

My code should be expected to fail

**Comment by LC-Pam** [comment]
Thank you for your time. We rejected to add the test case since all solutions failed after adding more test cases. We appreciate your support!
