### ISSUE TITLE
contest feeling lucky button doesn't work anymore

### ISSUE THREAD

**Issue by rozhanroukhosh** [LeetCode-Feedback/LeetCode-Feedback#9774]
#### Your LeetCode username
rojanrookhosh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
so there is this button that when you go on contest it appeared randomly but gave you 10+ leetcode points now when you click it it says you got 10 points but never adds it to your point

#### Expected behavior
to when you press the button give you the credits

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, please file this issue on Zendesk support channel.
