### ISSUE TITLE
Missing Test Case - 350. Intersection of Two Arrays II

### ISSUE THREAD

**Issue by nouranfarahat** [LeetCode-Feedback/LeetCode-Feedback#9777]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> intersect(vector<int>& nums1, vector<int>& nums2) {
        
        int sz1=nums1.size();
        int sz2=nums2.size();
        
        vector<int> ans;
        for(int i=0;i<sz1;i++)
        {
            for(int j=0;j<sz2;j++)
                if(nums1[i]==nums2[j])
                {
                    ans.push_back(nums1[i]);
                    nums2.erase(nums2.begin()+j);
                    sz2--;
                    j--;
                    break;
                }
        }
        return ans;
    }
};
```

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
