### ISSUE TITLE
Design Doubly Linked List Solution should have tail pointer

### ISSUE THREAD

**Issue by quinluong** [LeetCode-Feedback/LeetCode-Feedback#9778]
#### Your LeetCode username
drgfangg

#### Category of the bug
- Solution

#### Description of the bug
The bellow class should have tail pointer for reducing time complexity when we want to get tail node.

Url: https://leetcode.com/explore/learn/card/linked-list/210/doubly-linked-list/1297/

```
class MyLinkedList {
    private DoublyListNode head;
    /** Initialize your data structure here. */
    public MyLinkedList() {
        head = null;
    }
}
```

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem - it's invalid, tail node is optional. We appreciate your support!
