### ISSUE TITLE
494. Target Sum - wrong info in Constraints

### ISSUE THREAD

**Issue by richardxoldman** [LeetCode-Feedback/LeetCode-Feedback#9779]
#### Your LeetCode username
LulitosKoditos

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In **Constraints** there is information:
0 <= sum(nums[i]) <= 1000

It should be **sum(nums)** instead of **sum(nums[i])** (without [i]).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The constraints are correct. They do not represent python code. We appreciate your support!
