### ISSUE TITLE
1576. 替换所有的问号

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#978]
** Bug 类型**
- [x ] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题干中有奇怪的字符。
![image](https://user-images.githubusercontent.com/26211339/92702379-b3bd1480-f383-11ea-871f-16f5b113474a.png)

**Comment by feiceh** [comment]
感谢反馈，当前工作人员已经去掉了错误出现的标签。

**Comment by Ijustwantyouhappy** [comment]
青菜白玉饭汤

**Comment by feiceh** [comment]
那就➕20积分吧。后续使用中有任何问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。

**Comment by Ijustwantyouhappy** [comment]
我建议题目本身纠正可以设置为100积分，像我这么无聊的人不多，放心，通货膨胀不了。
