### ISSUE TITLE
buttons not working 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [LeetCode-Feedback/LeetCode-Feedback#9782]
![Screenshot (127)](https://user-images.githubusercontent.com/78332454/200184524-e5e7ed37-794b-439c-b6c6-91aacd99d177.png)
I'm signed in but button isn't working

**Comment by LC-Pam** [comment]
Thank you for the screen recording!
 
Our engineers are aware of this issue and they're working on fixing it. I'll provide updates on when this will be resolved.

**Comment by LC-Pam** [comment]
Issue should be fixed.
