### ISSUE TITLE
278. First Bad Version - C++ solution stuck in infinite loop despite reaching return

### ISSUE THREAD

**Issue by emmaf2564** [LeetCode-Feedback/LeetCode-Feedback#9783]
#### Your LeetCode username

emmaf2564

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The below code, when run for problem 278. First Bad Version, gets stuck in an infinite loop, despite the debug printout showing that the correct solution was reached.

#### Code you used for Submit/Run operation

```
// The API isBadVersion is defined for you.
// bool isBadVersion(int version);

class Solution {
public:
int firstBadVersion(int n) {
        int start = 1;
        int end = n;
        while(1){
            int halfway = (end - start) / 2;
            if (halfway == 0) {
                halfway = 1;
            }
            std::cout << "Checking " << start+halfway << std::endl;
            if(isBadVersion(start + halfway)) {
                if (isBadVersion(start + halfway - 1) ) {
                    end = start + halfway;
                } else {
                    std::cout << "Result is " << start + halfway << std::endl;
                    return start + halfway;
                } 
            } else {
                start = start + halfway;
            }
        } 
        return 0;
    }
};
```
Result on example testcase: Time limit exceeded error, with the following output
```
Checking 3
Checking 4
Result is 4
Checking 2
Checking 2
Checking 2
Checking 2
Checking 2
Checking 2
...
```

#### Expected behavior

This code should pass the example testcase with output 4, I've tested it in other environments e.g coderpad and it reaches the correct solution there

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by AloofMaalouf** [comment]
Having the same type of issue recently, while loop keeps getting stuck, what seems to actually be happening is that the while loop is not checking the condition before continuing, in a different problem it would just infinite loop, in this code it gets an error because i is not in the range of nums, tried the same code in a different compiler and it works perfectly, this is the code (Problem 31): 
class Solution {
public:
    void nextPermutation(vector<int>& nums) {
        int i = 0;
        while(nums[i] < nums[i + 1]) {
            i++;
        }
        iter_swap(nums.begin() + i, nums.begin() + i - 1);
        return;
    }
};

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, The code is indeed stuck in an infinite loop. There is a bug in the code and it should be TLE, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
