### ISSUE TITLE
Missing Test Case - 899. Orderly Queue

### ISSUE THREAD

**Issue by ghost** [LeetCode-Feedback/LeetCode-Feedback#9784]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I submitted this solution and it passed. I thought I had found a linear solution to the k ==1 case but this solution fails my fabricated test case `s = "adeadfadeab"`, `k=1`. But this test case isn't a part of the given test cases. A further modification to this code where you instead set min_s to be the last seen min character will also pass all the test cases including the one above. but will fail the following test case: `s = "adeagfadeagb"`, `k=1`.

#### Code you used for Submit/Run operation

```
// Orderly Queue
class Solution:
    def orderlyQueue(self, s: str, k: int) -> str:

        if k == 1:
            
            min_s = 0
            i  = 1

            while i < len(s):
                
                #consider the string starting at i:
                curr_s = i

                for min_i, curr_i in zip(range(min_s, min_s+len(s)), range(curr_s, curr_s + len(s))):

                    if s[min_i%len(s)] < s[curr_i%len(s)]:
                        i = curr_i + 1
                        break

                    if s[min_i%len(s)] > s[curr_i%len(s)]:
                        if i == curr_i:
                            min_s = curr_i
                            i = curr_i+1

                        else:
                            i = curr_i
                            k = curr_s - min_s
                            min_s = curr_s + (curr_i - curr_s) // k * k
                        break
                    
                    i = curr_i

            return ''.join([s[i%len(s)] for i in range(min_s, min_s + len(s))])

        else:
            return ''.join(sorted(s))
```

#### Language used for code

Python

#### Expected behavior

Fails the test case above but passes all current test cases.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by beazer001** [comment]
Hi,

Edited the comment above to show that I used Python as my language.

**Comment by LC-Pam** [comment]
<img width="294" alt="Screen Shot 2022-11-09 at 2 38 55 AM" src="https://user-images.githubusercontent.com/103138242/200648068-2e59ffbb-3456-4430-a70a-89ad0dfa6e38.png">
https://leetcode.com/submissions/detail/839609250/

**Comment by beazer001** [comment]
Right. But it doesn't pass this test case: `"adeadfadeab"` `k=1`. I think both of these test cases make sense to add.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Please provide us your LCUS username.

**Comment by beazerj** [comment]
Thanks. My leetcode username is beazer01.
