### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by edwarfmartinez** [LeetCode-Feedback/LeetCode-Feedback#9786]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Compile error in LeetCode, but no errors in XCode (playground) for the same code

#### Code you used for Submit/Run operation

```
import Foundation
class Solution {
    
    func romanToInt(_ s: String) -> Int {
        var result = 0
        var updatedInput = s
        
        if s.contains("IV")
        {
            setResultAndInput(romanNum: "IV",intNum: 4)
        }
        if s.contains("IX")
        {
            setResultAndInput(romanNum: "IX",intNum: 9)
        }
        if s.contains("XL")
        {
            setResultAndInput(romanNum: "XL",intNum: 40)
        }
        if s.contains("XC")
        {
            setResultAndInput(romanNum: "XC",intNum: 90)
        }
        if s.contains("CD")
        {
            setResultAndInput(romanNum: "CD",intNum: 400)
        }
        if s.contains("CM")
        {
            setResultAndInput(romanNum: "CM",intNum: 900)
        }
        
        updatedInput.map{
            switch $0{
            case "I":
                result += 1
            case "V":
                result += 5
            case "X":
                result += 10
            case "L":
                result += 50
            case "C":
                result += 100
            case "D":
                result += 500
            case "M":
                result += 1000
            default:
                result += 0
            }
            
        }
        
        return result
        
        func setResultAndInput(romanNum: String, intNum:Int){
            updatedInput = updatedInput.replacingOccurrences(of: romanNum, with: "")
            result += intNum
        }
    }
}
```

#### Language used for code

Swift

#### Expected behavior

No compile errors

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The link that you submitted  on the XCode (playground) for the same code.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by edwarfmartinez** [comment]
Hi!

Please run the code here: https://online.swiftplayground.run/

And try to test the function like this:

var solution = Solution()
print(solution.romanToInt("MCMXCIV"))

Result: 1994

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, There is an issue in the code because a function is defined within the scope of the other function., please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
