### ISSUE TITLE
Solution - 743. Network Delay Time

### ISSUE THREAD

**Issue by TaroGuost** [LeetCode-Feedback/LeetCode-Feedback#9789]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For problem743. I think for the Dijsktra's algorithm time complexity is N + E log E instead of N + E log N. To do it with N + E log N I think we need make sure before push n into priority queue there is no incoming edge to n.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Ticket is invalid. Explanation is in the time complexity analysis; it is E log E, but its equivalent to E log N due to the problem. We appreciate your support!
