### ISSUE TITLE
C O(32) easy idea!!!

### ISSUE THREAD

**Issue by barry556652** [LeetCode-Feedback/LeetCode-Feedback#9791]
int rangeBitwiseAnd(int left, int right){

        int tmp = right & left;
        
        long long int num = 1;//exponent
        
        for(int i = 0; i < 32; i++)
        {
            if(right - num >= left)// if (right - nums) in the range[left, right] 
            {
                tmp = tmp & ~(1 << i);// set tmp's number i bit to 0 
                num *= 2;
            }
            else
            {
                break;
            }
                
        }
        return tmp;
    }

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your code to the team.  We appreciate your support!
