### ISSUE TITLE
Wrong test case results

### ISSUE THREAD

**Issue by HAHAHA44** [LeetCode-Feedback/LeetCode-Feedback#9793]
#### Your LeetCode username
Zoioi

#### Category of the bug
- [ ] Question
- [x]  Solution
- [ ] Language
- [x]  Missing Test Cases 

#### Description of the bug
[面试题 17.18. Shortest Supersequence LCCI] (https://leetcode.cn/problems/shortest-supersequence-lcci/description/)

I answered this question with `C++`.

When test case gives:

`big = [7, 5, 9, 0, 2, 1, 3, 5, 7, 9, 1, 1, 5, 8, 8, 9, 7]`

`small = [1, 1, 5, 9]`

expect output shows `[7,10]`, but the true answer is `[9, 12]`.

So it seems the build-in algorithm works wrong.

#### Code you used for Submit/Run operation

```C++
class Solution {
public:
    vector<int> shortestSeq(vector<int>& big, vector<int>& small) {
        unordered_map<int, int> need;
        int diff = 0;
        vector<int> res(2);
        int resLen = 0;
        for (int i = 0; i < small.size(); i++) {
            if (need.count(small[i])) {
                need[small[i]] += 1;
            } else {
                need[small[i]] = 1;
            }
            diff += 1;
        }

        int n = big.size();
        int l = 0;
        for (int r = 0; r < n; r++) {
            if (need.count(big[r])) {
                if (need[big[r]] > 0) {
                    diff -= 1;
                }
                need[big[r]] -= 1;
            }

            cout << big[r] << " " << diff << endl;
            while (!diff) {
                if (!resLen || resLen > r - l + 1) {
                    res[0] = l;
                    res[1] = r;
                    resLen = r - l + 1;
                }
                if (need.count(big[l])) {
                    need[big[l]] += 1;
                    if (need[big[l]] > 0) {
                        diff += 1;
                    }
                }
                l += 1;
            }
        }
        return resLen ? res : vector<int>(0);
    }
};
```

#### Language used for code
C++

#### Expected behavior
Test case:

`big = [7, 5, 9, 0, 2, 1, 3, 5, 7, 9, 1, 1, 5, 8, 8, 9, 7]`

`small = [1, 1, 5, 9]`

expect output shows `[7,10]`, but the true answer is `[9, 12]`.

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
您好，在与相关团队核实后：one shorter (with all distinct elements) 您给的例子不符合我们题面的要求。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
