### ISSUE TITLE
Missing Test Case - 1479. Sales by Day of the Week

### ISSUE THREAD

**Issue by ClaireZzzzg** [LeetCode-Feedback/LeetCode-Feedback#9794]
#### Category of the bug
- [ 1] Missing Test Cases 

#### Description of the bug

What if the sales record doesn't include full day-of-week data? For example, it has 5 days a week of data except for Saturday. So we need to create a cartesian product first.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem, adding another example will make the statement longer and this case should be clear from the statement. We appreciate your support!
