### ISSUE TITLE
Missing Test Case - 1323. Maximum 69 Number

### ISSUE THREAD

**Issue by zathrath03** [LeetCode-Feedback/LeetCode-Feedback#9797]
#### Your LeetCode username

zathrath03

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The problem description and the function definition both specify the return value is required to be an integer. However, returning a string representation of the correct integer successfully passes all tests.

#### Code you used for Submit/Run operation

```
class Solution:
    def maximum69Number (self, num: int) -> int:
        return str(num).replace('6', '9', 1)

```

#### Language used for code

Python3

#### Expected behavior

The test case should fail due to the return value being a string, not an integer.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
