### ISSUE TITLE
Missing Test Case - 736. Parse Lisp Expression

### ISSUE THREAD

**Issue by int0x80-ptt** [LeetCode-Feedback/LeetCode-Feedback#9799]
#### Your LeetCode username

fxfxxxfxx

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The definition of variable is unclear. Should it be `[a-z][a-z0-9]*` ? Since I get error message:

```
'expression' must consist of values in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', '(', ')', '-'] only
```

What should be the result of the following testcases?

1. (let let 1 let)
2. (let 0 1 0)
3. (let a-a 2 a-a)

All of them passed the testcase checker. Should them be legal?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. All of them are invalid. It is hard to make the checker reject all the invalid test cases for now but we will not add invalid expressions to the test set. We appreciate your support!
