### ISSUE TITLE
776. 拆分二叉搜索树  翻译错误

### ISSUE THREAD

**Issue by xmcgcg** [LeetCode-Feedback/LeetCode-Feedback#98]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
翻译错误（参考下方截图）：
1. 【示例1】中的【注意根结点】五个字不需要加粗（英文原版没有）。
2. 【注意】部分第1点语言表达可以改进：一是【个数】与【个】重复，只需要保留一个；二是【不得超过】语气有误，不宜描述题目自身输入限制。
3. 【注意】部分第2点最后拼音输入错误导致没有转换为汉字。

**期望行为**
1. 取消【注意根结点】加粗。
2. 改为【二叉搜索树节点个数不超过 50】或者【二叉搜索树节点不超过 50 个】。
3. 将最后的英文字母修正为【都不相同】。

**屏幕截图**
![776](https://user-images.githubusercontent.com/11268373/78270347-4a67e880-753d-11ea-91ce-c3b0f3121657.png)

**Comment by feiceh** [comment]
done
