### ISSUE TITLE
Node class overloaded causing runtime error - Typescript - 116. Populating Next Right Pointers in Each Node

### ISSUE THREAD

**Issue by becpeck** [LeetCode-Feedback/LeetCode-Feedback#9800]
#### Your LeetCode username
andromedis

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Parameter for the function has type `Node | null`, but all properties in the class definition (`val`, `left`, `right`, `next`) appear not to exist in the runtime. Accessing any of them appears as a syntax error in the editor, with tooltip details showing:

> Property 'val' does not exist on type 'Node'.(2339)

If run, the result shows a runtime error, although logs of the properties do output mostly correctly, showing `TreeNode` instead of `Node`, but without a `next` property:

```
    console.log(root.left)
                     ^
TypeError: Cannot read properties of null (reading 'left')
    Line 18: Char 22 in solution.ts (connect)
    Line 90: Char 19 in solution.ts (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 39: Char 26 in solution.ts (Object.<anonymous>)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

The tooltip for the `Node` type in the function signature shows:

> interface Node
> Node is an interface from which a number of DOM API object types inherit. It allows those types to be treated similarly; for example, inheriting the same set of methods, or being tested in the same way.

I assume this is overloading the class defined for the problem and causing the issue.

#### Code you used for Submit/Run operation
I did not attempt to continue solving the problem after noticing the issue, but this code should recreate it.

```
function connect(root: Node | null): Node | null {
    console.log(root.val)
    console.log(root.left)
    console.log(root.right)
    console.log(root.next)

    return null
};
```

#### Language used for code
Typescript

#### Expected behavior
The `Node` class should be properly implemented, and instances should have all properties defined in the problem.

#### Screenshots

<img width="606" alt="Screen Shot 2022-11-07 at 6 47 42 PM" src="https://user-images.githubusercontent.com/49978356/200463674-3721843d-ed26-4904-b69f-d4f2628af6dd.png">
<img width="705" alt="Screen Shot 2022-11-07 at 6 47 56 PM" src="https://user-images.githubusercontent.com/49978356/200463685-b4535197-7012-48ce-bf35-5bcc968d1ed8.png">
<img width="1042" alt="Screen Shot 2022-11-07 at 6 48 13 PM" src="https://user-images.githubusercontent.com/49978356/200463696-7f664fd1-1b22-4a6a-a265-f3184f793a14.png">
<img width="1027" alt="Screen Shot 2022-11-07 at 6 52 00 PM" src="https://user-images.githubusercontent.com/49978356/200463704-838cc946-ccaa-4ddf-9c5c-d1f0429a3474.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
