### ISSUE TITLE
Java solution Line no 17 bug in code

### ISSUE THREAD

**Issue by visudhi** [LeetCode-Feedback/LeetCode-Feedback#9801]
#### Your LeetCode username

sathyanarayanpb

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In line number 17 s.size should be replaced with s.length() for java solution

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    // Return true if the character is a vowel (case-insensitive)
    boolean isVowel(char c) {
        return c == 'a' || c == 'i' || c == 'e' || c == 'o' || c == 'u'
            || c == 'A' || c == 'I' || c == 'E' || c == 'O' || c == 'U';
    }
    
    // Function to swap characters at index x and y
    void swap(char[] chars, int x, int y) {
        char temp = chars[x];
        chars[x] = chars[y];
        chars[y] = temp;
    }
    
    public String reverseVowels(String s) {
        int start = 0;
        int end  = int(s.size()) - 1; // s.size to be replaced with s.length() in the java solution of leetcode website
        // Convert String to char array as String is immutable in Java
        char[] sChar = s.toCharArray();
        
        // While we still have characters to traverse
        while (start < end) {
            // Find the leftmost vowel
            while (start < s.length () && !isVowel(sChar[start])) {
                start++;
            }
            // Find the rightmost vowel
            while (end >= 0 && !isVowel(sChar[end])) {
                end--;
            }
            // Swap them if start is left of end
            if (start < end) {
                swap(sChar, start++, end--);
            }
        }
        
        // Converting char array back to String
        return new String(sChar);
    }
};
```

#### Expected behavior

Size of array to be calculated in java works with s.length and not s.size

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The Problem Page.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ayush68** [comment]
yes i felt the same

**Comment by visudhi** [comment]
The problem page link i'm attaching https://leetcode.com/problems/reverse-vowels-of-a-string/solutions/2484211/reverse-vowels-of-a-string/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by visudhi** [comment]
Thanks LC-PAM the issue is fixed.
