### ISSUE TITLE
Remove Duplicates (26) not working for Typescript

### ISSUE THREAD

**Issue by michaelangrivera** [LeetCode-Feedback/LeetCode-Feedback#9805]
#### Your LeetCode username

michaelangrivera

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The following code does not return any output. The console output is an empty array `[]`. 
I've verified on my local machine that there is the output returned for the second test case: `[ 0, 1, 2, 3, 4 ]`. 
`console.log(nums)` does work and shows the correct output, but the `return` statement is not working. 

#### Code you used for Submit/Run operation

```
function removeDuplicates(nums: number[]): number[] {
  if (nums.length < 2) return nums
  const map = buildDupMap(nums)
  let counter = 0
  for (const key in map) {
      if (map[key].length > 1) {
        const idxsToRemove = map[key]
        idxsToRemove.forEach((el, i) => {
          if (i !== 0 ){
            nums.splice(el - counter, 1)
            counter++
          }
        })
    }
  }
  return nums
};


type DupObjMap = {
  [key: number]: number[]
}

function buildDupMap(arr: number[]): DupObjMap {
  const dupObjMap: DupObjMap = {}
  arr.forEach((obj, i) => {
    if (!dupObjMap[obj]) { 
      dupObjMap[obj] = [i]
    }
    else {
      dupObjMap[obj].push(i)
    }
  })
  return dupObjMap
}
```

#### Language used for code

`Typescript`

#### Expected behavior

The node environment should return the array `[ 0, 1, 2, 3, 4 ]`, but for some reason, it is an empty array. 

#### Screenshots

<img width="1722" alt="Screenshot 2022-11-08 at 8 40 22 AM" src="https://user-images.githubusercontent.com/55844504/200579995-c2e1a823-215d-40b6-bae0-fc42816a2838.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
