### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by lkislitcyn** [LeetCode-Feedback/LeetCode-Feedback#9806]
#### Your LeetCode username
kila86

#### Category of the bug
- [+] Missing Test Cases 

#### Description of the bug
Error Expected between Leetcode Java Machine (or what you use) and Intellij Idea

#### Code you used for Submit/Run operation

```
// Two Sum
Class Solution {
    public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
        int pow = 0, tempout = 0;

        while ((l1.next != null) || (l2.next != null)) {

            if (l1.next != null) {
                tempout += (int) Math.pow(10, pow) * l1.val;
                l1 = l1.next;
            }
            if (l2.next != null) {
                tempout += (int) Math.pow(10, pow) * l2.val;
                l2 = l2.next;
            }
            pow++;
        }
        tempout += (int) Math.pow(10, pow) * l1.val + (int) Math.pow(10, pow) * l2.val;
        l1 = new ListNode();
        l2 = l1;

        while (tempout != 0) {
            l1.val = (int) tempout % 10;
            tempout /= 10;
            if (tempout != 0) {
                l1.next = new ListNode();
                l1 = l1.next;
            }
        }
        return l2;
    }

}
```

#### Language used for code
Java

#### Expected behavior
[8,9,9,9,0,0,0,1] - but your machine give [8,9,9,0,0,0,9,1]

#### Screenshots
![Снимок экрана от 2022-11-08 22-58-58](https://user-images.githubusercontent.com/83903257/200598565-c1a824a1-c310-487e-8d22-76d847bed51f.png)

**Comment by nskybytskyi** [comment]
Hello! `Math.pow` is [notorious for being imprecise](https://stackoverflow.com/questions/25404088/math-pow-yields-different-result-depending-on-java-version). By using it you introduce undefined behavior. There is nothing that can be done to fix this issue.

However, I can help you in a different way. Explicitly converting both linked lists to integers is set to fail regardless of the precision issues. Both linked lists can contain up to 100 elements, meaning that the corresponding integers are up to 10^100. Such numbers are not meant to be represented in the built-in numeric types. Instead, the problem expects you to perform columnar addition.

**Comment by lkislitcyn** [comment]
change on 
int pow = 1, tempout = 0;

        while ((l1.next != null) || (l2.next != null)) {

            if (l1.next != null) {
                tempout += pow * l1.val;
                l1 = l1.next;
            }
            if (l2.next != null) {
                tempout += pow * l2.val;
                l2 = l2.next;
            }
            pow*=10;
        }
        tempout += pow * l1.val + pow * l2.val;
        l1 = new ListNode();
        l2 = l1;
it doesn't use  "pow" and again [8,9,9,0,0,0,9,1], but idea give "[8,9,9,9,0,0,0,1]";

**Comment by nskybytskyi** [comment]
Oh yeah, your code contains another UB. In line 
`tempout += pow * l1.val + pow * l2.val;`
you access `.val` of both `l1` and `l2` even though one of them may be `null`.

**Comment by lkislitcyn** [comment]
![list](https://user-images.githubusercontent.com/83903257/200988437-079387b3-47d5-4ffc-8f09-bff6e1b6342f.png)

i have now idea, how it's work :D, but it's done. Will change a code for a hundred nodes.

**Comment by lkislitcyn** [comment]
My bad! Find all bugs, not correct make mas to ListNode 
new version
 int count=1;
        l3 = l1;
        for (int i : mas1) {
            l1.val = i;
            if (count != mas1.length) {
                l1.next = new ListNode();
                count++;
                l1 = l1.next;
            }
        }
 old version makes one step more with l1.val=0 and get not valid value from Solution;
Will make new version with hundred nodes. Thanks for help.
