### ISSUE TITLE
Missing Test Case - 剑指 Offer 46. 把数字翻译成字符串 LCOF

### ISSUE THREAD

**Issue by Chen-speculation** [LeetCode-Feedback/LeetCode-Feedback#9808]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by feiceh** [comment]
感谢反馈，能否向我们补充提供测试用例，可以参考[这个反馈](https://github.com/LeetCode-Feedback/LeetCode-Feedback/blob/master/.github/ISSUE_TEMPLATE/bug--------.md)，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
