### ISSUE TITLE
564. Find the Closest Palindrome Test case

### ISSUE THREAD

**Issue by ConanLao** [LeetCode-Feedback/LeetCode-Feedback#981]
input "0" should return "1", but the it returns "-1". Please add this test case.

**Comment by lc-kay** [comment]
Hi @ConanLao, 

Can you please include the code you used for this problem? Then, I can verify the issue and relay it for the team to review. Thank you!

**Comment by Vikas-Jethwani** [comment]
@ConanLao 
In the question it is mentioned: **The input n is a positive integer represented by string**. 0 is not a positive integer.

**Comment by lc-kay** [comment]
Hi @ConanLao 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
