### ISSUE TITLE
Ambigious wording: 901. Online Stock Span

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#9810]
#### Your LeetCode username

Leaderboard

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think the below part of the question is ambigious:
> The span of the stock's price today is defined as the maximum number of consecutive days (starting from today and going backward) for which the stock price was less than or equal to today's price.

The reason is that it isn't obvious from the above that we shouldn't continue once the condition has been broken. Consider the below bruteforce code:

```java
class StockSpanner {
    ArrayList<Integer> arr = new ArrayList<>();
    public StockSpanner() {
        arr = new ArrayList<>();
    }
    
    public int next(int price) {
        arr.add(price);
        int max_val = 0;
        int ptr = 0;
        for (int i = 0; i < arr.size(); i++)
        {
            if (arr.get(i) <= price)
                ptr++;
            else
            {
                max_val = Math.max(max_val, ptr);
                ptr = 0;
            }
        }
        max_val = Math.max(max_val, ptr);
        return max_val;
    }
}
```
This one failed on this test case:

```
["StockSpanner","next","next","next","next","next"]
[[],[32],[82],[73],[99],[91]]
```

My code returned ``[null,1,2,1,4,3]``. The reason is that from the wording of the question, I thought that I needed to iterate the whole array to find the maximum number of consecutive days (32, 82, 73), when instead I was supposed to terminate once I reached "99" (since 99 > 91). There is nothing in the question which suggested that my interpretation was incorrect. 

#### Code you used for Submit/Run operation
See above

#### Language used for code

Java

#### Expected behavior

The wording needs to be appropriately adjusted.

#### Screenshots

N/A

#### Additional context

N/A

**Comment by nskybytskyi** [comment]
> I thought that I needed to iterate the whole array ...

I'm sorry to hear that it caused you trouble, but I feel like it is rather clear after careful reading:

> The span ... is  ... maximum number of consecutive days (**starting from today** and going backward) ...

since `[73, 82, 32]` is not a group of consecutive days starting from `91`.

**Comment by Leader-board** [comment]
Does that not give only an indication of the order of searching? Could be a mistake on my end though...

**Comment by nskybytskyi** [comment]
Natural language can sometimes be interpreted quite loosely. There is always a balance between making the statement easy to read and unambiguous. One way to formalize is asking to find min `j` such that `price[k] <= price[i]` for all `j <= k <= i`, but then days also need to be indexed. Anyway, I'm not the one to make a decision here, so let's wait for Pam or the problem setter themselves.

**Comment by LC-Pam** [comment]
Thank you for your time. As mentioned in the comments, the statement is clear that what you implemented was wrong.
We added one more example to clearly show that case. We appreciate your support!
