### ISSUE TITLE
191. Number of 1 Bits markdown not formatted correctly 

### ISSUE THREAD

**Issue by TheDoctor561** [LeetCode-Feedback/LeetCode-Feedback#9815]
#### Your LeetCode username

TheDoctor561

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Problem 191. Solution has a bit of improper markdown usage the text "{:align="center"}" is clearly visible and as a result does not center align the elements. 

#### Code you used for Submit/Run operation

N/A

#### Language used for code
N/A

#### Expected behavior

Expected: Image to be centered and markdown function to be hidden 
Actual: Image was not centered and markdown is clearly visible 

#### Screenshots

<img width="729" alt="Screen Shot 2022-11-09 at 10 33 52 AM" src="https://user-images.githubusercontent.com/30754707/200875300-d9e1b98e-5d3a-4ec1-983d-749d3a029f6d.png">

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem and looks like it's the browser issue. We appreciate your support!
