### ISSUE TITLE
Unnecessarily gendered language - 1366. Rank Teams by Votes

### ISSUE THREAD

**Issue by chloe-47** [LeetCode-Feedback/LeetCode-Feedback#9817]
#### Your LeetCode username

user1132rN

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Example 3 says "Only one voter so his votes are used for the ranking.".

It should say "Only one voter so their votes are used for the ranking.".

Replace "his" with "their".

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
