### ISSUE TITLE
Missing Test Case - 1166. Design File System

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#982]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution from discuss section is accepted, but fails on the following test case:

["FileSystem", "createPath", "createPath", "createPath"]
[[], ["/j",1], ["/j/i",2], ["/ji/w",3]]

Your input
["FileSystem", "createPath", "createPath", "createPath"]
[[], ["/j",1], ["/j/i",2], ["/ji/w",3]]

Output
[null,true,true,true]

Expected
[null,true,true,false]

#### Code you used for Submit/Run operation

```
class FileSystem {

    private static class Node {
        Node[] child = new Node[26];
        Map<String, Integer> map = new HashMap<>();
        boolean end;
        
        public Node() {}
        
    }
    
    private Node root = new Node();
    
    public FileSystem() {
        
    }
    
    public boolean createPath(String path, int value) {
        Node node = root;
        for(int i = 1; i < path.length(); i++) {
            char ch = path.charAt(i);
            if(ch == '/') {
                if(!node.end) {
                    return false;
                }
                continue;
            }
            if(node.child[ch - 'a'] == null) {
                node.child[ch - 'a'] = new Node();
            }
            node = node.child[ch - 'a'];
        }
        node.end = true;
        if(node.map.containsKey(path)) {
            return false;
        }
        node.map.put(path, value);
        return true;
    }
    
    public int get(String path) {
        Node node = root;
        for(int i = 1; i < path.length(); i++) {
            char ch = path.charAt(i);
            if(ch == '/') {
                if(!node.end) {
                    return -1;
                }
                continue;
            }
            if(node.child[ch - 'a'] == null) {
                node.child[ch - 'a'] = new Node();
            }
            node = node.child[ch - 'a'];
        }
        if(!node.end) {
            return -1;
        }
        Integer res = node.map.get(path);
        return res == null ? -1 : res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Additional context

Link to the original solutions:
https://leetcode.com/problems/design-file-system/discuss/368288/Java-Solution-Trie-%2B-HashMap

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
