### ISSUE TITLE
英文翻译为中文时可能发生错误 - 864. 获取所有钥匙的最短路径

### ISSUE THREAD

**Issue by LetMeFly666** [LeetCode-Feedback/LeetCode-Feedback#9820]
**你的 LeetCode 用户名**
[LetMeFly](https://leetcode.cn/u/tisfy/)

**Bug 类型**

- [ ] 题目

**描述**

本题的汉语版描述中将英文版的```'#' is a wall.```翻译为了```'#' 代表一堵```

**期望行为**

将```'#' 代表一堵```修改为```'#' 代表一堵墙```

**屏幕截图**

![sscreen](https://user-images.githubusercontent.com/56995506/200967261-fddc5376-9a25-410e-a3a2-b8a94af0cd81.png)

**Comment by feiceh** [comment]
反馈反馈，积分奖励已发放，请查收。

**Comment by LetMeFly666** [comment]
已收到👍
