### ISSUE TITLE
49. Group Anagrams - Test case incorrect

### ISSUE THREAD

**Issue by gregomelo** [LeetCode-Feedback/LeetCode-Feedback#9823]
#### Your LeetCode username
gregoryomelo

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question said that "You can return the answer in any order."

My output is: [[["eat","tea","ate"],["tan","nat"],["bat"]]]

Expected output is: [[["eat","tea","ate"],["tan","nat"],["bat"]]]

#### Code you used for Submit/Run operation
```
// Group Anagrams
class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        def toListSorted(word):
            result = [letter for letter in word]
            result.sort()
            result = "".join(result)
            return result
    
        listSorted = [toListSorted(word) for word in strs]
    
        listZiped = zip(strs, listSorted)
    
        dictAnagram = {}
        for word, index in listZiped:
            if index in dictAnagram:
                dictAnagram[index].append(word)
            else:
                dictAnagram[index] = [word]
        
        return [dictAnagram.values()]
```

#### Language used for code
Python

#### Expected behavior
The only difference between the outputs is the order and the questions said that we could presented in any order.

#### Screenshots
Not apply.

#### Additional context
Not apply.

**Comment by nskybytskyi** [comment]
Your actual output is `[[["eat","tea","ate"],["tan","nat"],["bat"]]]` which is incorrect because there is an extra list: `[[...]]` instead of `[...]`. The following simple change fixes the solution:
```diff
- return [dictAnagram.values()]
+ return list(dictAnagram.values())
```
Note how there is a difference between constructing a `list` from iterable and constructing a list with one element of type `dict_values`.

**Comment by gregomelo** [comment]
Great! Thanks! It is 4AM in Brazil and I believe my brain is not working well. :-)
