### ISSUE TITLE
Improve Description - 27. Remove Element

### ISSUE THREAD

**Issue by tenick** [LeetCode-Feedback/LeetCode-Feedback#9825]
In [27. Remove Element](https://leetcode.com/problems/remove-element/) problem description, under Example 2, the explanation for Example 2's output can confuse some people. I suggest changing the explanation 

from:
#### Explanation: Your function should return k = 5, with the first five elements of nums containing 0, 0, 1, 3, and 4.
to:
#### Explanation: Your function should return k = 5, with the first five elements of nums containing 0, 1, 4, 0, and 3.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem, It is important to show that the order of the answer does not matter. We appreciate your support!
