### ISSUE TITLE
A Follow-up Requirement Should be Added: 2464. Minimum Subarrays in a Valid Split

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#9826]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The 2464th problem is similar as a problem which can only be seen in LCCN:  https://leetcode.cn/problems/qie-fen-shu-zu/
![LCP14](https://user-images.githubusercontent.com/73991126/201060353-7c30852c-8d6a-478a-92f5-2e5475ff611e.png)
but the constraints of nums.length of the problem in LCCN is 10^5, so the O(n^2logU) solution cannot get accecpted. In other words, in China if this problem is used in a real interview, the O(nlogU+U) solution may be required.
So I think a follow-up requirement can be added:
Can you find a solution with less than O(n^2)  time complexity?

Code you used for Submit/Run operation

The time complexity of the code below is O(n^2logU)
```
class Solution:
    def validSubarraySplit(self, nums: List[int]) -> int:

        dp = [10**9 for j in range(len(nums))]
        for j in range(len(nums)):
            for i in range(j+1):
                if math.gcd(nums[i],nums[j])>1:
                    dp[j]=min(dp[j],dp[i-1]+1) if i else 1
        return dp[-1] if dp[-1]<10**9 else -1
```

The time complexity of the code below is O(U+nlogU)
```
class Solution:
    def validSubarraySplit(self, nums: List[int]) -> int:

        mx = max(nums)
        factor = [-1,-1]+[1]*(mx-1)
        p = 2

        while p<=mx:
            j = p
            while j*p<=mx:
                if factor[j*p]==1:
                    factor[j*p]=p
                j+=1
            p+=1
            while p<=mx:
                if factor[p]==1:
                    break
                p+=1

        dp = [10**9]*(mx+1)        
        ans = 0
        for i in range(len(nums)):
            cur = nums[i]
            dpc = 10**9
            while True:
                if factor[cur]==-1:
                    break
                if factor[cur]==1:
                    dp[cur] = min(dp[cur], ans+1)     
                    dpc = min(dpc, dp[cur])       
                    break                
                dp[factor[cur]] = min(dp[factor[cur]],ans+1)
                dpc = min(dpc,dp[factor[cur]])
                cur//= factor[cur]
            ans = dpc

        return ans if ans<10**9 else -1
```

Language used for code
Python3

Expected behavior
A follow-up requirement should be added:
Can you find a solution with less than O(n^2) time complexity?

**Comment by nskybytskyi** [comment]
By the way, could you please explain how this sieve works? Is it really O(U) and not O(U log log U)? For reference, my solution looks like this:

```py
class Solution:
    MX = 10**5
    PD = list(range(MX + 1))
    for p in range(2, MX):
        if PD[p] == p:
            for m in range(p**2, MX + 1, p):
                PD[m] = p
    
    def validSubarraySplit(self, nums: List[int]) -> int:
        ans = 0
        dp = [inf] * (Solution.MX + 1)

        for num in nums:
            mn = inf
            while num > 1:
                div = Solution.PD[num]
                num //= div
                dp[div] = min(dp[div], ans + 1)
                mn = min(mn, dp[div])
            ans = mn

        return ans if ans < inf else -1
```

**Comment by nskybytskyi** [comment]
@LC-Pam this issue actually refers to an LCUS problem [2464. Minimum Subarrays in a Valid Split](https://leetcode.com/problems/minimum-subarrays-in-a-valid-split/). LCCN problem is included only for reference as to why the suggested follow-up is not unreasonable in an interview setting.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will not add the follow up. The current constraints are suitable for interview.
The problem was used with higher constraints in LCCN in the spring cup. It was supposed to be harder intentionally. We appreciate your support!
