### ISSUE TITLE
Improper Hidden Hint - 1157. Online Majority Element In Subarray

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#9827]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [√] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The hidden hint of the problem seems to lead the user to a solution with random sample and binary search. 
![1157](https://user-images.githubusercontent.com/73991126/201070719-12e8d80e-1682-4715-9a0a-1bc9bbc1614b.png)

But the standard solution of this problem must be using segment tree. On the one hand, the solution with random sample may get WA while the majority element exists if you are unlucky enough. On the other hand, the interviewer usually cannot accept the solution with random factor. So, I think the hidden hint should be changed.

Code you used for Submit/Run operation

The code below is using random sample and binary search.
```
class MajorityChecker:
    
    def __init__(self, arr: List[int]):

        self.t = defaultdict(list)
        for j in range(len(arr)):
            self.t[arr[j]].append(j)
        self.arr = arr

    def query(self, left: int, right: int, threshold: int) -> int:

        for _ in range(25):
            num = self.arr[random.randint(left,right)]
            rgt = bisect_right(self.t[num],right)
            lft = bisect_left(self.t[num],left)
            if rgt-lft>=threshold:
                return num
        return -1
```

The code below is using segment tree:
```
class MajorityChecker:

    def __init__(self, arr: List[int]):
        class Node:
            def __init__(self, i, j):
                self.l = i
                self.r = j
                if i + 1 == j:
                    self.k = arr[i]
                    self.c = 1
                    return
                mid = (i + j) // 2
                self.left = Node(i, mid)
                self.right = Node(mid, j)
                self.build()
                
            def build(self):
                if self.left.k == self.right.k:
                    self.k = self.left.k
                    self.c = self.left.c + self.right.c
                else:
                    if self.left.c > self.right.c:
                        self.k = self.left.k
                        self.c = self.left.c - self.right.c
                    else:
                        self.k = self.right.k
                        self.c = self.right.c - self.left.c
                        
            def find(self, i, j):
                if self.l == i and self.r == j:
                    return self.k, self.c
                mid = (self.l + self.r) // 2
                if mid >= j:
                    return self.left.find(i, j)
                elif mid <= i:
                    return self.right.find(i, j)
                else:
                    left = self.left.find(i, mid)
                    right = self.right.find(mid, j)
                    if left[0] == right[0]:
                        return left[0], left[1] + right[1]
                    else:
                        if left[1] > right[1]:
                            return left[0], left[1] - right[1]
                        else:
                            return right[0], right[1] - left[1]
                        
        self.node = Node(0, len(arr))
        self.d = {}
        for i, n in enumerate(arr):
            if n not in self.d:
                self.d[n] = []
            self.d[n].append(i)               


    def query(self, left: int, right: int, threshold: int) -> int:
        n, c = self.node.find(left, right + 1)
        c = bisect.bisect_right(self.d[n], right) - bisect.bisect_left(self.d[n], left)
        return n if c >= threshold else -1
```

Language used for code
Python3

Expected behavior
The hidden hint should be changed to a series of hints which can lead the user to solution with segment tree.

**Comment by nskybytskyi** [comment]
Disclaimer: I am not an official staff member.

Ah yes, such discussions come up ever so often on CF when there is a problem with a randomized model solution. A common argument is that a solution is fine if the probability of it failing is less than a probability of a physical machine malfunctioning while performing testing. Another popular notion, commonly used in cryptography, is that an algorithm is "good" if and only if there is no adversary that can construct a problematic input "fast enough" with "high enough" probability.

> On the other hand, the interviewer **usually** cannot accept the solution with random factor.

This is a very subjective statement. My experience is that you will be fine with a randomized solution as long as you can properly estimate the expected complexity. Funnily enough, your second solution uses `dict`, which is also randomized, having [worst case amortized complexity of O(n)](https://wiki.python.org/moin/TimeComplexity#dict), just like `std::unordered_map`. I could therefore argue that it also shouldn't be accepted either.

> So, I think the hidden hint should be changed.

Internal guidelines say that hints should focus on the simplest valid solution, with all other approaches being discussed in the Solution section instead. I would argue that a randomized approach is simpler than a segtree.
