### ISSUE TITLE
Missing Test Case - 1599. Maximum Profit of Operating a Centennial Wheel

### ISSUE THREAD

**Issue by Kagotpush** [LeetCode-Feedback/LeetCode-Feedback#9830]
#### Your LeetCode username
kagotpush

#### Category of the bug
- [] Missing Test Cases 

#### Description of the bug
My code has managed to pass through all the testcases, but it gives incorrect result for my custom testcase:
```
[5,0,0,0,0,30]
5
5
```

#### Code you used for Submit/Run operation
```
class Solution:
    def minOperationsMaxProfit(self, customers: List[int], boardingCost: int, runningCost: int) -> int:
        if 4*boardingCost<=runningCost:
            return -1
        maxprofit=profit=waiting=0
        ans=-1
        for i, x in enumerate(customers):
            waiting+=x
            b=min(4,waiting)
            profit+=b*boardingCost-runningCost
            if profit>maxprofit:
                maxprofit=profit
                ans=i+1
            waiting-=b
        q,r=divmod(waiting,4)
        if r*boardingCost>runningCost:
            ans+=q+1
        else:
            ans+=q
        return ans
```

#### Language used for code
Python

#### Expected behavior
This code should be rejected

#### Screenshots
![image](https://user-images.githubusercontent.com/45495112/201176870-76a69b67-8edd-4f58-b33f-1dc7fb71dc56.png)

#### Additional context
My code gives correct answer only if the queue is empty after len(customers) loops, or if profit==maxprofit after len(customers) loops, which must be true for each of the current testcases

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
