### ISSUE TITLE
Missing Test Case - 140. Word Break II

### ISSUE THREAD

**Issue by Nilanshuyadav** [LeetCode-Feedback/LeetCode-Feedback#9831]
#### Your LeetCode username

Nilanshu_yadav08

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code gets submitted but some testcases at their maximum constraints, that contain the continuous string of same character are giving wrong answer.

#### Code you used for Submit/Run operation

```
class Solution {
    List<String> ans;
    Node root;
    public List<String> wordBreak(String s, List<String> wordDict) {
        root = new Node();
        ans = new ArrayList<>();

        for(String st : wordDict){
            insert(st);
        }

        String temp = "";
        dfs(0, s, temp);

        return ans;
    }

    public void insert(String st){
        Node node = root;

        for(int ind=0; ind<st.length(); ind++){
            char ch = st.charAt(ind);

            if(!node.contains(ch)){
                node.put(ch, new Node());
            }

            node = node.get(ch);
        }

        node.setEnd();
    }

    public void dfs(int inx, String st, String sb){
        int n = st.length();

        if(inx == n){
            ans.add(sb.substring(0, sb.length()-1));
            return;
        }

        StringBuilder s = new StringBuilder(sb);

        Node node = root;
        for(int ind=inx; ind<n; ind++){
            char ch = st.charAt(ind);
            if(!node.contains(ch))
                return;
            else{
                s.append(ch);
                node = node.get(ch);
            }    

            if(node.isEnd()){
                s.append(" ");
                String temp = new String(s);
                s.deleteCharAt(s.length()-1);
                dfs(ind+1, st, temp);
            }

        }
    }
}

class Node{
    Node list[];
    boolean end;
    public Node(){
        list = new Node[26];
        end = false;
    }

    public boolean contains(char ch){
        return list[ch-'a']!=null;
    }

    public void put(char ch, Node node){
        list[ch-'a'] = node;
    }

    public Node get(char ch){
        return list[ch-'a'];
    }

    public void setEnd(){
        end = true;
    }

    public boolean isEnd(){
        return end;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I am not sure but there is some problem in checking the end space of the sentence.
as the answer of the testcases was too large, it's hard to study it thoroughly.

#### Screenshots

![leetcode_word_break2](https://user-images.githubusercontent.com/91049897/201225676-8025e1ec-f2ad-4347-be83-62e56723f0e3.png)
![leetcode_word_break2(2)](https://user-images.githubusercontent.com/91049897/201225697-f690db9a-c963-43f5-afae-e8a3baaa397a.png)

One of the testcase giving wrong answer :
![leetcode_word_break2(3)](https://user-images.githubusercontent.com/91049897/201225977-c2b6ef3c-752f-45c7-b0cd-376868aebebe.png)

**Comment by nskybytskyi** [comment]
**Additional context**:

1. The suggested test case in a copyable form:
```
"aaaaaaaaaaaaaaaaaaaa"
["a","aa","aaa","aaaa"]
```

2. My solution, which I am sure is correct, also gets WA on this test case.

3. The output for the suggested test case has a total length of `8,692,759` symbols. It may be a bit too much for the checker to handle.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The testcase output exceeds 5MB, which is why it shows WA, even if it isn't.
Did not add the testcase, please suggest a small case for which the solution fails. We appreciate your support!
