### ISSUE TITLE
Problem 622. Design Circular Queue. Vague Statement.

### ISSUE THREAD

**Issue by Thebatman7** [LeetCode-Feedback/LeetCode-Feedback#9832]
#### Your LeetCode username
Rembrand

#### Category of the bug
- [x] Question

#### Description of the bug
One of the statements in this problem is not very clear and can waste a lot of time for those who are trying to solve this problem.
Statement:
"Deletes an element from the circular queue. Return true if the operation is successful."

The way queue behaves could indicate that we delete the first element added to this data structure, but since it is a circular queue this assumption is not right. It is not clear what element should be deleted.
That statement could mean that any element in the data structure is deleted. Any element the programmer wants.

#### Code you used for Submit/Run operation
I did not submit my code because the problem is not how the algorithm is behaving it is about a statement in the problem description.

#### Language used for code
This affects all languages.

#### Expected behavior
A clear statement about which element (first, last, the ith, etc.) in the data structure is deleted.

**Comment by nskybytskyi** [comment]
> The way queue behaves could indicate that we delete the first element added to this data structure, but since it is a **circular queue** this assumption is not right.

A quote from the statement:

> The **circular queue** is a linear data structure in which the operations are performed based on FIFO (First In First Out) principle.

As you can see, the principle does not change and you should dequeue the element that was enqueued first. The word "circular" in the name of the data structure refers solely to the underlying memory layout.
