### ISSUE TITLE
[LC Premium] 1286. Iterator for Combination, official solution rendered incorrectly!

### ISSUE THREAD

**Issue by Anonymus-AP** [LeetCode-Feedback/LeetCode-Feedback#9837]
#### Your LeetCode username
paulalexis58

#### Category of the bug
- [ ] Solution

#### Description of the bug
Official solution of 1286. Iterator for Combination rendered incorrectly...markdown is not rendered correctly!

#### Screenshots
<img width="808" alt="Screenshot 2022-11-11 at 6 29 22 PM" src="https://user-images.githubusercontent.com/14908583/201345461-0b897cf8-bda2-46f0-af82-64c14822d0ac.png">

**Comment by nskybytskyi** [comment]
**Additional context**

This issue only occurs in the [new design](https://leetcode.com/problems/iterator-for-combination/solutions/610707/iterator-for-combination/). In the old version, the solution renders [just fine](https://leetcode.com/problems/iterator-for-combination/solution/). 

To revert to the old design, click your profile picture in the top right corner, then click "revert to old version". Don't worry, you'll be able to go back to the new design at any point. Hopefully, it will be fixed soon.

**Comment by Anonymus-AP** [comment]
@nskybytskyi Thanks wasn't aware of it!
The new design has a lot of bugs...was causing inconvenience!

**Comment by LC-Pam** [comment]
I am so sorry this happened. This is a known error that happens and our team is working on to fix this issue.
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
