### ISSUE TITLE
Missing Test Case - 2462. Total Cost to Hire K Workers

### ISSUE THREAD

**Issue by zthking** [LeetCode-Feedback/LeetCode-Feedback#9839]
#### Your LeetCode username
I don't want to tell you.

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case:
[10,9,8,10]
2
1
The code below can pass all current test cases, but the test case above should fail.
The expected answer should be 18, not 19.

#### Code you used for Submit/Run operation

```
class Solution {
    public long totalCost(int[] costs, int k, int candidates) {
        int n = costs.length;
        PriorityQueue<Integer> left = new PriorityQueue<>();
        PriorityQueue<Integer> right = new PriorityQueue<>();
        int i = 0, j = n - 1;
        while (i < candidates) {
            left.offer(costs[i++]);
        }
        while (j >= i && j >= n - candidates) {
            right.offer(costs[j--]);
        }

        long res = 0;
        for (int u = 0; u < k; u++) {
            if (left.isEmpty() || right.isEmpty()) {
                res += left.isEmpty() ? right.poll() : left.poll();
            } else {
                //issue is here. The case left.peek() == right.peek() should be handled seperately.
                if (left.peek() <= right.peek()) {
                    res += left.poll();
                    if (i <= j) {
                        left.offer(costs[i++]);
                    }
                } else {
                    res += right.poll();
                    if (i <= j) {
                        right.offer(costs[j--]);
                    }
                }
            }
        }

        return res;
    }
}
```

#### Language used for code
Java

**Comment by nskybytskyi** [comment]
When I submit your solution it gets WA.

**Comment by zthking** [comment]
> 

I just update it again. Can you try again?

**Comment by nskybytskyi** [comment]
The expected answer for your test case is indeed 19, obtained as follows:

We hire 2 workers in total. The total cost is initially 0.

- In the first hiring round we choose the worker from `[10, ..., 10]`. The lowest cost is 10, and we break the tie by the smallest index, which is 0. The total cost = 0 + 10 = 10.

- In the second hiring round we choose the worker from `[9, ..., 10]`. The lowest cost is 9 (index 0). The total cost = 10 + 9 = 19.

The total hiring cost is 19. Hence there is nothing wrong with the problem or your solution.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. The code received AC when we submitted it and the test case Accepted after we ran it,  please also consider above comment as the reference, We appreciate your support!
<img width="225" alt="Screen Shot 2022-11-12 at 3 14 44 AM" src="https://user-images.githubusercontent.com/103138242/201413993-2f9bc264-a0b8-4afe-8521-8bb49760c88f.png">
