### ISSUE TITLE
Vidoe is not working!

### ISSUE THREAD

**Issue by valentynasheludko** [LeetCode-Feedback/LeetCode-Feedback#9842]
#### Category of the bug
Problem 

#### Description of the bug

steps :
1)Go to https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/678/sql-data-structure/4352/
2)Scroll down to video "First Problem Video Walkthrough"
3)push play 
#### Expected behavior

####Actual result: 
The video is not turning on, stays frozen 

#### Screenshots
![dfgdgss](https://user-images.githubusercontent.com/115500203/201437227-ec30a2ca-1c9f-4aed-9f87-21fefc8c1e2a.png)

**Comment by nskybytskyi** [comment]
Hello! I could not reproduce the issue on my machine. Could you please provide additional context: your OS, browser version, extensions, and user scripts used (if any)?

**Comment by valentynasheludko** [comment]
Hello, I tried to reproduce it and it is fix. Video is working again !  Sent from Mail for Windows From: Nicky SkybytskyiSent: Saturday, November 12, 2022 3:05 AMTo: LeetCode-Feedback/LeetCode-FeedbackCc: Valentyna Sheludko; AuthorSubject: Re: [LeetCode-Feedback/LeetCode-Feedback] Vidoe is not working! (Issue #9842) Hello! I could not reproduce the issue on my machine. Could you please provide additional context: your OS, browser version, extensions, and user scripts used (if any)?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
