### ISSUE TITLE
process exited with signal SIGSEGV

### ISSUE THREAD

**Issue by Lychas** [LeetCode-Feedback/LeetCode-Feedback#9844]
#### Your LeetCode username
Lychas

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Judger is exiting with signal SIGSEGV, the code works fine on my computer running Node v18.7.0 but doesn't work on LeetCode

#### Code you used for Submit/Run operation
```
var searchRange = function(nums, target) {
    let changedIndex = 0
    function binarySearch(array, target) {

        if (array.length === 0 ) {
            return [false, undefined]
        }

        let middleIndex = Math.floor(array.length / 2)
        let middle = array[middleIndex]

        if ( middle === target ) {
            return [true, middleIndex]
        }

        else if (middle > target ) {
            return binarySearch(array.splice(0 , middleIndex), target)
        }

        else if (middle < target ) {
            changedIndex = changedIndex + middleIndex
            return binarySearch(array.splice(middleIndex, array.length), target)
        }
    }

    function searchAround(array, target, index) {
        function searchMore(array, target) {
            let moreIndex = 0
            for (let loopIndex = 0; loopIndex < array.length; loopIndex++) {
                if (array[loopIndex] === target) {
                    moreIndex ++
                }
                else {
                    break
                }
            }

            return moreIndex - 1
        }

        function searchLess(array, target) {
            let lessIndex = 0
            for (let loopIndex = array.length - 1; loopIndex > 0; loopIndex--) {
                if (array[loopIndex] === target) {
                    lessIndex ++
                }
                else {
                    break
                }
            }

            return lessIndex
        }

        let leftSideNumber = searchLess([...array].splice(0, index), target)
        let rightSideNumber = searchMore([...array].splice(index, [...array].length), target)

        return [leftSideNumber, rightSideNumber]

    }

    let [searchResult, searchMiddleIndex] = binarySearch([...nums], target)
    if (searchResult === false) {
        return [-1, -1]
    }
    let arrayMiddleIndex = (changedIndex + searchMiddleIndex)

    let [ lessNumber, moreNumber] = searchAround([...nums], target, (changedIndex + searchMiddleIndex))
    return [arrayMiddleIndex - lessNumber, arrayMiddleIndex + moreNumber]
};
```

#### Language used for code
JavaScript

#### Expected behavior
The program exited with signal SIGSEGV while it should run correctly 

Normal behavior: 
![image](https://user-images.githubusercontent.com/95055527/201449093-31dfaf65-7027-429f-b512-4c6b3b45b271.png)

What happened: 
![image](https://user-images.githubusercontent.com/95055527/201449108-f883aff0-1c8b-48af-b70f-dd3da90cd0be.png)

#### Screenshots
![image](https://user-images.githubusercontent.com/95055527/201449280-26ac48ae-99f0-4188-98a7-ae02a1d04ef0.png)

#### Additional context
Problem: https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/

**Comment by Lychas** [comment]
Nevermind I found the bug, I was indexing outside of the loop on ```return binarySearch(array.splice(middleIndex, array.length), target)```

**Comment by nskybytskyi** [comment]
Have you tried running your solution on the second sample? When I do, it gets stuck in an infinite recursion of binary search. Hopefully, this will help you debug the solution.

By the way, as far as I understand, your solution is not O(log n), as you use linear search after finding one occurrence of the target. The intended solution uses two binary searches that go left and right respectively when encountering a value equal to target.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, please consider above comment as the reference, please let us know if you have more questions.
