### ISSUE TITLE
Missing Test Case - 2460. Apply Operations to an Array

### ISSUE THREAD

**Issue by zhenliang153** [LeetCode-Feedback/LeetCode-Feedback#9845]
#### Your LeetCode username
zhenliang153

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Missing test case that prohibit loop processing.

#### Code you used for Submit/Run operation

```cpp
// 2460. Apply Operations to an Array
class Solution {
public:
    vector<int> applyOperations(vector<int>& nums) {
        const int n = nums.size();
        bool state = true;
        while (state) {
            state = false;
            for (int i = 1; i < n; ++i) {
                if (nums[i] != 0 && nums[i] == nums[i - 1]) {
                    nums[i - 1] *= 2;
                    nums[i] = 0;
                    state = true;
                }
            }
        }
        fill(remove(nums.begin(), nums.end(), 0), nums.end(), 0);
        return nums;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Input: [2,1,1]
Output: [4,0,0]
Expected: [2,2,0]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
