### ISSUE TITLE
Problem difficulty doesn't appear after looking at the submission (New version)

### ISSUE THREAD

**Issue by Dominastorm** [LeetCode-Feedback/LeetCode-Feedback#9846]
#### LeetCode username
Insatanic

#### Category of the bug
Interface

#### Description of the bug

1. Go to any submission link without going to the description first.
![image](https://user-images.githubusercontent.com/43818888/201457152-0ae564f4-76e4-44cd-a99f-05c14957e525.png)

2. Go to the description tab
![image](https://user-images.githubusercontent.com/43818888/201457170-9a74c9cf-d1c3-4729-aefc-e19c09e4abc0.png)
The difficulty of the problem does not appear until the page is refreshed.

#### Expected behavior

The difficulty of the problem should appear without having to refresh the page.

**Comment by LC-Pam** [comment]
Thank you for your time. We've reported your feedback to the team.  We appreciate your support!
