### ISSUE TITLE
面试题 05.01. 插入

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#985]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目有歧义，无法确定题意。
1. 没说清是否是正整数，如果N是负整数，插入M的二进制代码后，从二进制到十进制既可以是负也可以是正
2. “使得M从N的第j位开始，到第i位结束”。只假定了从j位到i位足以容纳M，但没说清楚如果超过了M的长度，靠后的位置是怎么处理，保留原样还是置为0。

**你使用的语言**
python

**Comment by feiceh** [comment]
感谢反馈，该题目技术验证没有问题的，结合题面和示例已经说的很清楚了哦。
