### ISSUE TITLE
当有异常用例参与执行时，系统解析用例结果有误

### ISSUE THREAD

**Issue by leechangqing** [LeetCode-Feedback/LeetCode-Feedback#9850]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
笨de熊

**Bug 类型**
- [ ] 题目
- [X] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目：剑指 Offer 17. 打印从1到最大的n位数
问题描述：用例执行存在错误
问题复习：
单独执行输入1，执行结果[1,2,3,4,5,6,7,8,9]系统判断为正确；
当增加用例10时，用例1执行结果[1,2,3,4,5,6,7,8,9]系统判断为错误。

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    vector<int> printNumbers(int n) {
        if (n > 9) {
            return vector<int>();
        }
        int ubound = pow(10, n) - 1;
        vector<int> result(ubound, 1);
        for (int i = 1; i < ubound; i++) {
            result[i] = result[i - 1] + 1;
        }
        return result;
    }
};
```

**期望行为**
当有错误用例或超出可接受参数范围用例执行时，正常用例可正常解析

**屏幕截图**
用例正常执行
![image](https://user-images.githubusercontent.com/15624642/201470866-0693d061-396f-4ddc-a1cb-bf909d549cd7.png)
当包含用例10时，原用例1执行结果被判为错误
![image](https://user-images.githubusercontent.com/15624642/201470899-564baa00-7f32-4144-8ec2-b98a514a3678.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
您好，在与相关团队核实后： 该问题已知晓，后续会进行修复，积分奖励已发放，感谢您的反馈和支持。
