### ISSUE TITLE
控制台执行能通过的用例，提交却通不过

### ISSUE THREAD

**Issue by tuoeg** [LeetCode-Feedback/LeetCode-Feedback#9851]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**1469165539@qq.com**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ 316] 题目
- [ ] 题解
- [C++ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
控制台运行测试用例通过，但是提交之后通不过该用例
![image](https://user-images.githubusercontent.com/49616374/201471349-09422d2f-338f-4644-983f-5376d162df86.png)

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
