### ISSUE TITLE
Typo in Problem 432 (All One Data Structure)

### ISSUE THREAD

**Issue by Infiniticity** [LeetCode-Feedback/LeetCode-Feedback#9852]
#### Your LeetCode username

Infiniticity

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The title of the question is ``All O`one Data Structure`` instead of `All One Data Structure`.
The URL also contains the same typo.

#### Screenshots

![image](https://user-images.githubusercontent.com/79257339/201474604-0b2a7975-7da7-4f4d-a6f8-a9b4f1ad5241.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. O'one = O(1).  We appreciate your support!
