### ISSUE TITLE
Missing Test Case - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by abdulmoomin007** [LeetCode-Feedback/LeetCode-Feedback#9853]
#### Your LeetCode username
abdulmoomin007

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Below code does not serialize the node or deserialize string data, But it gets accepted!

#### Code you used for Submit/Run operation

```
const serialize = function(root) {
    return root;
};

const deserialize = function(data) {
    return data;
};
```

#### Language used for code
Javascript

#### Expected behavior
The program should return "Invalid returned data." incase the serialize method returns something other than string which happens correctly in python3.

#### Screenshots
![image](https://user-images.githubusercontent.com/32864519/201476992-bf7b2fbc-675b-4440-b090-3eec4f7f50cc.png)

#### Additional context
Expected output should be as below.
![image](https://user-images.githubusercontent.com/32864519/201477035-fdf5e9dc-8871-41b7-a6d2-f480222f3bdd.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We know about this issue. The purpose it to learn serialization but one can cheat and there is no good way to stop this right now. We appreciate your support!
