### ISSUE TITLE
Wrong Test case!

### ISSUE THREAD

**Issue by SC-One** [LeetCode-Feedback/LeetCode-Feedback#9858]
#### Description of the bug
I just solved(solution added in the below sections) a [problem](https://leetcode.com/problems/minimum-number-of-flips-to-convert-binary-matrix-to-zero-matrix/) in LeetCode and found that one test case is wrong in the problem! (screenshot has added too)
the testcase: [[1,0,0],[1,0,0]]
My output is: 2 , you can try these indices: (0,0) , (1,0)
LeetCode output: -1 !

#### My Solution

```cpp
#include <algorithm>
#include <array>
#include <iostream>
#include <set>
#include <vector>

struct Cell {
  std::size_t row, col;
  bool operator==(const Cell& other) const {
    return other.row == row && other.col == col;
  }
};
using Cells = std::vector<Cell>;
using Matrix = std::vector<std::vector<int>>;

class Solution {
 private:
  // helper class
  template <int value>
  bool isValueMat(Matrix const& mat) {
    for (auto const& item : mat) {
      for (auto const element : item) {
        if (element != value) return false;
      }
    }
    return true;
  }
  void flip(Matrix& mat, std::size_t const& row, std::size_t const& col) {
    static constexpr std::array<std::pair<int, int>, 8> dirSteps = {
        {{0, 1}, {1, 1}, {1, 0}, {1, -1}, {0, -1}, {-1, -1}, {-1, 0}, {-1, 1}}};
    for (auto const& dirStep : dirSteps) {
      int newRow = static_cast<int>(row) + dirStep.first;
      int newCol = static_cast<int>(col) + dirStep.second;
      if (newRow < 0 || newCol < 0 ||
          static_cast<std::size_t>(newRow) >= mat.size() ||
          static_cast<std::size_t>(newCol) >=
              mat[static_cast<std::size_t>(newRow)].size())
        continue;
      mat[static_cast<std::size_t>(newRow)][static_cast<std::size_t>(newCol)] =
          (!mat[static_cast<std::size_t>(newRow)]
               [static_cast<std::size_t>(newCol)]);
    }
  }
  void flipNeighbores(Matrix const& mat, Cells const& checkCells, int& level) {
    ++level;
    for (std::size_t i = 0; i < mat.size(); ++i) {
      auto const totalColumns = mat[i].size();
      for (std::size_t j = 0; j < totalColumns; ++j) {
        if (checkCells.end() !=
            std::find(checkCells.begin(), checkCells.end(), Cell{i, j}))
          continue;
        auto newMat = mat;
        flip(newMat, i, j);
        auto newCheckCells = checkCells;
        newCheckCells.push_back({i, j});
        if (isValueMat<0>(newMat)) {
          counter.insert(level);
          --level;
          return;
        }
        flipNeighbores(newMat, newCheckCells, level);
      }
    }
    --level;
  }

 public:
  int minFlips(std::vector<std::vector<int>> const& mat) {
    if (mat.size() == 1) return 0;
    if (isValueMat<0>(mat)) return 0;
    int level = 0;
    flipNeighbores(mat, {}, level);
    return counter.empty() ? -1 : *counter.rend();
  }

 private:
  std::set<int> counter;
};
```

#### Screenshots
![image](https://user-images.githubusercontent.com/60355798/201486441-9c71bd47-0b55-497e-afa2-d43258e99f7b.png)

**Comment by nskybytskyi** [comment]
The matrix initially looks like this:
```
[[1,0,0],
 [1,0,0]]
 ```
 After flipping (0, 0) it looks like this:
 ```
[[0,1,0],
 [0,0,0]]
 ```
After flipping (1, 0) it looks like this:
 ```
[[1,1,0],
 [1,1,0]]
 ```
This is clearly not a zero matrix.

So the sequence of operations you suggested is invalid. In fact, one can prove that no sequence of operations will transform this matrix to a zero matrix. Hence there is nothing wrong with the test case.

**Comment by nskybytskyi** [comment]
By the way, may I suggest that you use less C++ madness in your solutions? It makes it very hard to read and debug the code.

**Comment by SC-One** [comment]
In the default example that is shown in the problem we have :
![image](https://user-images.githubusercontent.com/60355798/201487443-54eb177a-e69e-4f17-a2d4-c8e0ca8faa84.png)

we can see that when the solution focus on flipping (1, 0)  , the left-bottom cell has changed too! I think if we can do something like this , So we should go ahead with this process not that you mentioned:

The matrix initially looks like this:
```
[[1,0,0],
 [1,0,0]]
```
After flipping (0, 0) it looks like this:
```
[[1,1,0],
 [0,1,0]]
```
After flipping (1, 0) it looks like this:
```
[[0,0,0],
 [0,0,0]]
```

And as for the C++ language, it's entirely up to you! not anymore, and you can just test it. I don't want to change my code; I just want to know how the process of flipping is going.

**Thanks for prompt replay.**

**Comment by nskybytskyi** [comment]
> We can see that when the solution focus on flipping (1, 0) , the left-bottom cell has changed too! 

When applying the operation to `(1, 0)` we flip `(1, 0)`, `(1-1, 0)`, `(1+1, 0)` (doesn't exist), `(1,0-1)` (doesn't exist), `(1,0+1)`. As far as I can tell from the image in the statement, `(1, 0)`, `(0, 0)`, and `(1, 1)` are indeed the only cells to change.

When you suggest applying the operation to `(0, 0)` we should, according to the same logic, flip `(0, 0)`, `(0, 1)`, and `(1, 0)`. However, in your illustration you appear to not be flipping `(0, 0)` and flipping `(1, 1)` instead. I don't understand why.

In general, when applying an operation to `(x, y)` we flip `(x, y)`, `(x-1, y)`, `(x+1, y)`, `(x, y-1)`, `(x, y+1)` (if they exist).

I'm sorry if I was a little too harsh on the C++ part. It is certainly good that you know a lot of language features, it's just that I don't feel like they are appropriate for this problem. Anyway, you are right that it is a personal preference.

**Comment by SC-One** [comment]
> By the way, may I suggest that you use less C++ madness in your solutions? It makes it very hard to read and debug the code. UPD: surely typing `static_cast<std::size_t>(newRow)` four times in a row is not a good coding practice.

Yeah , I know in this situation we dont lose bits in the values , you can create another variable and one time casting ... , it really ups to you how coding., but **I hate compiler warnings.**( try to use something like: `-Wbloody_everything` )

**Comment by SC-One** [comment]
@nskybytskyi  Yeah , I got it , Thank you , I was flipping incorrect! I thought we should flip all neighbours.
