### ISSUE TITLE
Test case giving proper output in console but not when submitted.

### ISSUE THREAD

**Issue by grievous-mischievous7** [LeetCode-Feedback/LeetCode-Feedback#9859]
#### Your LeetCode username
runningrunner7

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For the question: https://leetcode.com/problems/maximum-depth-of-binary-tree/
for a particular test case when it is run on console for the solution i wrote it shows accepted in the console , but when i submit the code the same solution provides a different output and i get a submission 'wrong answer' . 

#### Code you used for Submit/Run operation

```
class Solution:
    
    maxdepth=1
    
    def maxDepth(self, root: Optional[TreeNode],n=1) -> int:
        if root==None:
            return None
        self.maxDepth(root.left,n+1)
        self.maxDepth(root.right,n+1)
        
        if n>Solution.maxdepth:
            Solution.maxdepth=n
        return Solution.maxdepth
        
           
```

#### Language used for code
python3

#### Expected behavior
expected my code to get submitted  but it did not.

#### Screenshots

![same_soln_2_outputs](https://user-images.githubusercontent.com/60668142/201488757-ec828e88-48ec-4655-b3f3-1c5a71873408.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
