### ISSUE TITLE
 297. Serialize and Deserialize Binary Tree - TestCase

### ISSUE THREAD

**Issue by Vikas-Jethwani** [LeetCode-Feedback/LeetCode-Feedback#986]
#### Your LeetCode username

Stan_VJ

#### Category of the bug
- [x] TestCase
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

-1 is a valid integer to have on a binary tree. And so is INT_MAX (2147483647) and INT_MIN (-2147483648). So cant use as a delimiter.

My code got accepted even if I used -1 as a delimiter (as null pointer). Many accepted solutions would get rejected too.

We should use characters as NULL pointers. "#" , "N" , "NULL"

#### Code you used for Submit/Run operation
```
class Codec {
public:
    string serialize(TreeNode* root)
    {
        if (root == NULL)
            return to_string(-1); // Here using a delimiter
        return to_string(root->val) + "," + serialize(root->left) + "," + serialize(root->right);
    }
    
    string s;
    int pos;

    TreeNode* deserialize(string data)
    {
        s=data;
        pos=0;
        return des();
    }
    TreeNode* des()
    {
        int len=0;
        while (pos+len<s.length())
        {
            if (s[pos+len] == ',')
                break;
            len++;
        }
        if (len == 0)
            return NULL;
        string sub = s.substr(pos, len);
        if (stoi(sub) == -1) // here again
        {
            pos+=len+1;
            return NULL;
        }
        else
        {
            TreeNode* ptr = new TreeNode(stoi(sub));
            pos+=len+1;
            ptr->left = des();
            ptr->right = des();
            return ptr;
        }   
        return NULL;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input: [1,-1,3]
Correct Output: [1,-1,3]
My Output: [1]

Input: [1,2147483647,3]
Correct Output: [1,2147483647,3]

Input: [1,-2147483648,3]
Correct Output: [1,-2147483648,3]

#### Additional context

I submitted this testcase via the leetcode contribute section, but it has been over 10 days and it is still pending there.
If possible, please speed up the process there too.

**Comment by lc-kay** [comment]
Hi @Vikas-Jethwani , 

When I ran your code, I received the [wrong answer](https://leetcode.com/submissions/detail/394359198/). If that is not what you see on your end, please provide me your submission detail page so I can look further into the issue. Thank you for using LeetCode!

**Comment by Vikas-Jethwani** [comment]
Sorry, here's the updated Code:
```
class Codec {
public:
    string serialize(TreeNode* root)
    {
        if (root == NULL)
            return to_string(INT_MAX);
        return to_string(root->val) + "," + serialize(root->left) + "," + serialize(root->right);
    }
    
    string s;
    int pos;

    TreeNode* deserialize(string data)
    {
        s=data;
        pos=0;
        return des();
    }
    TreeNode* des()
    {
        int len=0;
        while (pos+len<s.length())
        {
            if (s[pos+len] == ',')
                break;
            len++;
        }
        if (len == 0)
            return NULL;
        string sub = s.substr(pos, len);
        if (stoi(sub) == INT_MAX)
        {
            pos+=len+1;
            return NULL;
        }
        else
        {
            TreeNode* ptr = new TreeNode(stoi(sub));
            pos+=len+1;
            ptr->left = des();
            ptr->right = des();
            return ptr;
        }   
        return NULL;
    }
};
```

Test Case:
[1,2147483647,3]
[1,-2147483648,3]

My code gets accepted, even doesn't pass this testcase.

**Comment by lc-kay** [comment]
Hi @Vikas-Jethwani 
Thank you for submitting your updated code and test cases. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Vikas-Jethwani 
Thank you for your time. We've added constraints for this problem and ran your test code, which returned as invalid. We appreciate your support!
