### ISSUE TITLE
Missing Language Support - 142. Linked List Cycle II

### ISSUE THREAD

**Issue by arkrde** [LeetCode-Feedback/LeetCode-Feedback#9860]
#### Your LeetCode username
arkrde

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Please add support for submissions in Rust for this problem.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!

**Comment by guissalustiano** [comment]
Any update @LC-Pam? The problem continues without rust support.
