### ISSUE TITLE
791. 自定义字符串排序——题目描述翻译有问题

### ISSUE THREAD

**Issue by Someone-LikeU** [LeetCode-Feedback/LeetCode-Feedback#9861]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**Peter J**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [√] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
1.题目 “给定两个字符串 order 和 s 。order 的所有单词都是 唯一 的，并且以前按照一些自定义的顺序排序。”
其中的“order的所有单词”根据题意应该是“所有字母”或者“所有字符”。
2. “返回 满足这个性质的 s 的任意排列 。”描述不清，有歧义。根据题意及英文原文，应该是“返回 满足这个性质的 s 的任意一个排列 ”或者“返回 满足这个性质的 s 的一个排列 ”

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。
