### ISSUE TITLE
Missing Test Case - 225. Implement Stack using Queues

### ISSUE THREAD

**Issue by chamanjain199** [LeetCode-Feedback/LeetCode-Feedback#9862]
["MyStack","push","push","pop","push","pop"]
[[],[3],[4],[],[5],[]]

**Comment by chamanjain199** [comment]
please add this test case too

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
