### ISSUE TITLE
Missing Test Case - 69. Sqrt(x)

### ISSUE THREAD

**Issue by chotahacker** [LeetCode-Feedback/LeetCode-Feedback#9863]
#### getting right answer on wrong code 
- [ ] https://leetcode.com/problems/sqrtx/description/
- [ ] class Solution {
public:
	int mySqrt(int x) {
		int i=0, j=x, ans;
		while(i<=j){
			long long int mid=i+(j-i)/2;
			if(mid*mid==x){ans = mid; break;}
			else if(mid*mid<x){i=mid+1;}
			else{j=mid-1;}
		}
		return ans;
	}
};

- [ ] C++
- [ ] getting right answer on non-perfect square numbers

#### class Solution {
public:
	int mySqrt(int x) {
		int i=0, j=x, ans;
		while(i<=j){
			long long int mid=i+(j-i)/2;
			if(mid*mid==x){ans = mid; break;}
			else if(mid*mid<x){i=mid+1;}
			else{j=mid-1;}
		}
		return ans;
	}
};

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
