### ISSUE TITLE
缺少测试用例：6234. 最小公倍数为 K 的子数组数目

### ISSUE THREAD

**Issue by chenlimingnihao** [LeetCode-Feedback/LeetCode-Feedback#9865]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
chenliming

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
错误代码也能AC,当案列为 {2,3} k=6时，输出与预期结果不同也能AC

**你使用的语言**
JAVA

**你提交或者运行的代码**
```
class Solution {
    public int subarrayLCM(int[] nums, int k) {
        int ans=0;
        for(int i=0;i<nums.length;i++){
            boolean t=false;
            for(int j=i;j<nums.length;j++){
                if(k==nums[j])t=true;
                if(k%nums[j]==0){if(t)ans++;}
                else break;
            }
        }
        return ans;
    }
}
```

**期望行为**
上面代码是错误的，也能AC该题

**屏幕截图**
![image](https://user-images.githubusercontent.com/77827835/201511407-81ecf54c-b7e4-478c-a16b-e6cc87ebb87c.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收。
