### ISSUE TITLE
Missing constraints - 594. Longest Harmonious Subsequence

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#987]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/longest-harmonious-subsequence/
594. Longest Harmonious Subsequence

After 30+ correct answers - yet again :) - I got TLE (time limit exceeded) error - as there are no constraints given in problem :)

Please add constraints to this problem too.
- What are the valid domain/range for values inside the array

Is it 32 bit integer bounds as below?

-2147483648 < a[i] < 2,147,483,647

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

LC should own the responsibility :) LC can not miss to not provide constraints and not provide a waiver to remove a TLE from the user's submission. Now its a second time.
Why did I submit? Coz I cannot wait until you fix all problems with constraints, no time to delay, I had to make an assumption & submit.

Please add constraints to the problem given in description above.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for bringing this to our attention. Our team is constantly working to improve each problem we have posted. I've relayed this issue to our team to investigate. We appreciate your efforts!

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
