### ISSUE TITLE
第319场周赛T2测试用例添加

### ISSUE THREAD

**Issue by NinadoDante** [LeetCode-Feedback/LeetCode-Feedback#9873]
**你的 LeetCode 用户名**
ninado_dante

**Bug 类型**
- [ ] 缺少测试用例

**描述**
很多人使用int或者long 求lcm但是没有break，按理有相应溢出的测试用例，实际上没有
现提供int溢出的数据用例

**你使用的语言**
JAVA

**你提交或者运行的用例**
输入：nums =[773,613,11,8,103], k = 40

**期望行为**
预期：0
实际：1(如果使用int且超过k没有break 例如排名75阿全的代码)

**屏幕截图**
![image](https://user-images.githubusercontent.com/47001200/201516815-56155c7e-7d27-405f-b739-ae1a4cf97873.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前该题已添加测试用例，奖励已发放。
