### ISSUE TITLE
Missing Test Case - 2470. Number of Subarrays With LCM Equal to K

### ISSUE THREAD

**Issue by sudevdhali** [LeetCode-Feedback/LeetCode-Feedback#9878]
#### Your LeetCode username
newbiesd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug

for the below code it is getting submitted but it shouldn't as for the testcase
[2,3]
6
it is giving '0' and the actual answer is '1'

#### Code you used for Submit/Run operation

```
class Solution {
    public:
     int subarrayLCM(vector<int>& nums, int k) {
        int cnt = 0, lastk = -1;
        for (int i = 0, j = 0; j <nums.size(); j++) {
            if (nums[j] == k || lastk > -1 && k % nums[j] == 0) {
                if (nums[j] == k) {
                    lastk = j;
                    cnt += j - i + 1;
                }
                else cnt += lastk - i + 1;
                
            } else if (k % nums[j] != 0) {
                lastk = -1;
                i = j + 1;
            }
        }
        return cnt;
    }
};
```

#### Language used for code
C++

#### Expected behavior
1

#### Screenshots

![image](https://user-images.githubusercontent.com/60395148/201530242-71b8a16d-3f2e-428f-b477-b7d1ab75360e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
