### ISSUE TITLE
Missing Test Case - 151. Reverse Words in a String

### ISSUE THREAD

**Issue by asiuzzaman** [LeetCode-Feedback/LeetCode-Feedback#9879]
#### Your LeetCode username

SRBD_Lazy

#### Category of the bug
- [ ] Solution :  It shows wrong answer.
Output
"blue is sky the"
Expected
"blue is sky the"
    
#### Code you used for Submit/Run operation

```
User output and server output looks same but it show wrong answer whereas show the difference like 

Input:
"the sky is blue"
Output:
"blue is sky the\x00"
Expected:
"blue is sky the"
```

#### Expected behavior

```
It should shows  output like this
----------------------------
Output:
"blue is sky the\x00"
Expected:
"blue is sky the"
```

#### Screenshots

<img width="731" alt="Screenshot 2022-11-13 at 9 54 10 PM" src="https://user-images.githubusercontent.com/34129396/201531157-e9b8113d-98e8-425a-9401-acae24ce4a4d.png">

**Comment by nskybytskyi** [comment]
Could you please provide the whole code used for run/submit?

**Comment by asiuzzaman** [comment]
class Solution {
public:
    string reverseWords(string s) {
        stack<string>words;
        string str = "";
        for(int i=0; i<s.size(); i++) {

            if(s[i] == ' ' && str.size() != 0 ) {
                words.push(str);
                str = "";
            } 
            else if(s[i] != ' '){
                 str+=s[i];
            }
           
        }
        if(str.size()){
             words.push(str);
        }
       

        string res = "";
        while(!words.empty()){
            res += words.top()+' ';
            words.pop();
        }
        int len = res.size();
        res[len-1] = '\0';
        return res;
    }
};

**Comment by nskybytskyi** [comment]
Fascinating. But what if there is a problem where the expected answer could contain escape sequences? Displaying strings in the suggested form will lead to the same kind of optical illusion there. Hence I find it difficult to argue that one display method is universally better than the other. It would be strange to overwrite the default behavior without a clear benefit. What do you think?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
