### ISSUE TITLE
Missing constraints - 299. Bulls and Cows

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#988]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

299. Bulls and Cows
https://leetcode.com/problems/bulls-and-cows/

Missing constraints:
- What is the max length of secret/ guess?
- NOTE - please add good constraints so efficient solutions win - see https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/992

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Attempting this now - I will pray god that I wont have a TLE now again :)

Please add constraints to the question :)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
