### ISSUE TITLE
470. Implement Rand10() Using Rand7()

### ISSUE THREAD

**Issue by Reza-TGh** [LeetCode-Feedback/LeetCode-Feedback#9880]
#### Your LeetCode username

[RezaTalebzadeh](https://leetcode.com/RezaTalebzadeh/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hi!
About this problem; https://leetcode.com/problems/implement-rand10-using-rand7/
It seems the judge, the program which tests solutions, 
doesn't make a new instance for each testcase and so it makes space for using a property and 
circumventing what the problem really wants. (Which is find a solution with the _rand7() API_.) 

#### Code you used for Submit/Run operation

```
class Solution(object):
    counter = -1

    def rand10(self):
        """
        :rtype: int
        """
        #Sounds like cheating!
        self.counter += 1
        return self.counter % 10 + 1

       #Runtime: 274 ms, faster than 100.00% of Python online submissions for Implement Rand10() Using Rand7().
       #https://leetcode.com/submissions/detail/842742294/
```
```
class Solution 
{
protected:
    int counter = -1;
    
public:
    int rand10() 
    {
        return ++counter % 10 + 1;
    }
};
```
```
class Solution extends SolBase 
{
    int counter = -1;
    
    public int rand10() 
    {
        return ++counter % 10 + 1;
    }
}
```
#### Language used for code

Python
C++
Java

#### Expected behavior

Right now, the tester probably checks solutions in this way:
```
>>> a = Solution()
>>> a.rand10()
1
>>> a.rand10()
2
>>> a.rand10()
3
```
While I think it is better to check them in this way:
```
>>> Solution().rand10()
1
>>> Solution().rand10()
1
>>> Solution().rand10()
1
```

**Comment by nskybytskyi** [comment]
Generally speaking, good pseudorandom number generators are heavy objects. For example, [std::mt19937](https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine) has a size of 19,937 bits or roughly 2,5 kilobytes. It is therefore uncommon to create multiple instances of a PRNG.

Moreover, many standard PRNGs are **required** to return the same sequence when instantiated with the same seed. For example, a 10,000-th value generated by a default-constructed `std::my19937` is required to be `4'123'659'995` by the C++ standard. I find it difficult to justify expecting a different kind of behavior in this particular case.

**Comment by Reza-TGh** [comment]
@nskybytskyi Thank you for the points and the information.
