### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by Vineetkumarsingh12** [LeetCode-Feedback/LeetCode-Feedback#9881]
class Solution {
public:
    bool isValid(string s) {
        stack<char> st;
        if(s[0]==')'||s[0]=='}'||s[0]==']')
            return false;
        else if(s[s.length()-1]=='('||s[s.length()-1]=='{'||s[s.length()-1]=='[')
            return false;
      for(int i=0;i<s.length();i++)
      {
        if(s[i]=='('||s[i]=='{'||s[i]=='[') 
            st.push(s[i]);
          else if(i==s.length()-1&& st.empty())
              return false;
          else 
          {
              switch(s[i])
              {
                  case '}':
                      if(st.top()=='{')
                          st.pop();
                      else 
                          return false;
                      break;
                  case ')':
                      if(st.top()=='(')
                           st.pop();
                      else 
                          return false;
                      break;
                      case ']':
                      if(st.top()=='[')
                           st.pop();
                      else 
                          return false; 
                      break;

              }
          }
          
      }
        if(st.empty())
            return true;
        else
            return false;
    }
};

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case and issues.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
