### ISSUE TITLE
Missing Test Case - 2470. Number of Subarrays With LCM Equal to K

### ISSUE THREAD

**Issue by iadarshanand** [LeetCode-Feedback/LeetCode-Feedback#9882]
#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

 Actually I solved this question by assuming that it must be 'K' in the subarray and LCM should be 'K' of the valid subarray. While according to question it may be possible that subarray can be valid without containing 'K' as an element. For example let array be {2,3,6} and K be 6. so the subarray {2,3} could be also a valid subarray with LCM=6 i.e K while in subarray {2,3} there is no 6( i.e K)
so according to my approach it is not valid subarray.
     While what I submitted is ( to check if all elements of subarray divide K and inside subarray at least one K present ) then   the subarray is valid subarray. which gives wrong Answer on input:- arr[2,3,] and K=6.  the expected output should be 1 ( because of valid subarray {2,3} which LCM is 6 i.e K ). But My output gives 0. (because there is no K in subarray {2,3} ). <br>

Luckily, My code got accepted due to weak Testcases given by you. So, I request you to update testcases with below testcases given by me.

Input1: nums=[2,3], K=6
Output1: 1

Input2: nums[2,3,6], K=6
Output2: 4 

#### Code you used for Submit/Run operation

```
// 2470. Number of Subarrays With LCM Equal to K
class Solution {
public:
    int subarrayLCM(vector<int>& a, int k) {
        int n=a.size();
        int ans=0;
        
        for(int i=0;i<n;i++)
        {
            bool flag=false;
            for(int j=i;j<n;j++)
            {
                if((k%a[j])!=0)break;
                if(a[j]==k)flag=true;
                if(flag)ans++;
            }
        }
        return ans;
        
    }
};
```

####C++

#### Expected behavior

Input: nums=[2,3], K=6
Expected Output: 1
My Output: 0

//Explanation: According to my approach a subarray is valid iff (all elements divide K && there is atleast one K inside subarray). So in above testcase {2,3} subarray is not valid subarray according to my solution but it is valid because LCM of subarray {2,3} is 6 which is equal to K.

Input: nums=[2,3,6], K=6
Output: 4 
My Output: 3

//Explanation: Similliarly here I missed the valid subarray {2,3}. so my output got 3.

Luckily my code accepted during contest, So please update testcases.

#### Additional context

![5ccc449a-ada9-47f1-821a-a902dfa83ac7](https://user-images.githubusercontent.com/90796393/201540129-90353509-f930-44d8-8b1a-1d46c67586a4.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We rejected this test case. We appreciate your support!
