### ISSUE TITLE
Missing Test Case - 409. Longest Palindrome

### ISSUE THREAD

**Issue by ginywiny** [LeetCode-Feedback/LeetCode-Feedback#9888]
#### Your LeetCode username

ginywiny

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For s = "abccccdd", the longest palindrome is "cccc" which is a size of 4. For some reason, the solution claims "dccaccd" of length 7 is the longest palindrome, which is clearly not an available substring!

#### Code you used for Submit/Run operation

```
class Solution {
    public int longestPalindrome(String s) {
        if (s.length() == 1) {
            return 1;
        }

        int maxLength = s.length();
        int maxCount = 0;
        int left, right = 0;


        for (int i = 0; i < maxLength; i++) {
            left = i;
            right = i;

            // Odd string
            while (left >= 0 && right < maxLength && s.charAt(left) == s.charAt(right)) {
                maxCount = Math.max(right - left + 1, maxCount);
                left--;
                right++;
            }

            left = i;
            right = i + 1;
            // Even String
            while (left >= 0 && right < maxLength && s.charAt(left) == s.charAt(right)){
                maxCount = Math.max(right - left +1, maxCount);
                left--;
                right++;
            }

        }

        return maxCount;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The code outputs length 4 for the test case "abccccdd", despite the test case claiming the longest palindrome is 7. 

#### Screenshots

![Screenshot from 2022-11-13 14-16-28](https://user-images.githubusercontent.com/36121273/201540648-46f482ce-ee92-44af-b2f6-1e300c9b5b29.png)

**Comment by yumkam** [comment]
This problem does not ask for longest substring of input string.
It asks for longest palindrome that can be constructed from the letters present in input string, reordered however you like.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
