### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by seandong** [LeetCode-Feedback/LeetCode-Feedback#9896]
#### Your LeetCode username
dongzhengxuan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation
```python
class Solution(object):
    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        for i1, v1 in enumerate(nums):
            if v1 > target: next
            for i2, v2 in enumerate(nums[i1+1:], i1+1):
                if v2 > target: next
                if v1 + v2 == target:
                    return [i1, i2]
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.
The issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
