### ISSUE TITLE
A simpler solution for 202. Happy Number

### ISSUE THREAD

**Issue by mmalu** [LeetCode-Feedback/LeetCode-Feedback#99]
https://leetcode.com/problems/happy-number/discuss/560379/A-novel-solution-(O(1)-Space)-The-series-eventually-loops-through-a-single-digit

**Comment by CooperCooperCooper** [comment]
Hi @mmalu,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @mmalu,
Thank you for your suggestion! Your idea was used to improve the article.
