### ISSUE TITLE
Missing constraints - 85. Maximal Rectangle

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#990]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

85. Maximal Rectangle
https://leetcode.com/problems/maximal-rectangle/

Missing constraints
- What is the minimum & maximum size of matrix

Is it something like below?

0<=rows<=100
0<=cols<=100

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Question needs to have constraints in order to avoid a TLE error.
Please add the same.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
