### ISSUE TITLE
测试用例和控制台用例中表现不一致#110. 平衡二叉树

### ISSUE THREAD

**Issue by mskzj** [LeetCode-Feedback/LeetCode-Feedback#9902]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
测试用例在控制台和提交返回的值不一样

**你使用的语言**
python

**你提交或者运行的代码**
```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
result = True
class Solution:
    def isBalanced(self, root: Optional[TreeNode]) -> bool:
        global result
        self.depth(root)
        return result

    def depth(self, root: Optional[TreeNode]) -> bool:
        if root==None:
            return 0
        left = self.depth(root.left)
        right = self.depth(root.right)
        if abs(left-right)>1:
            global result
            result = False
        return max(left,right)+1
        
```

**期望行为**
true

**屏幕截图**
![image](https://user-images.githubusercontent.com/37142215/201663634-98ade525-f2f8-4501-ac02-4133798f01fc.png)

**额外的上下文**
（初步怀疑跟执行环境全局变量有关系）

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
