### ISSUE TITLE
Unexpected behavior on 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by karakarasuuuu** [LeetCode-Feedback/LeetCode-Feedback#9904]
#### Your LeetCode username
karakarasuuuu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

![image](https://user-images.githubusercontent.com/19412420/201672478-b29debb7-d8aa-460e-869d-f80971323cd4.png)
In the description, it is mentioned that the custom judge will be:
```
int[] nums = [...]; // Input array
int[] expectedNums = [...]; // The expected answer with correct length

int k = removeDuplicates(nums); // Calls your implementation

assert k == expectedNums.length;
for (int i = 0; i < k; i++) {
    assert nums[i] == expectedNums[i];
}
```
and both the return value and the array inputted will be tested.  
However, in Python3 if you remove the elements in the array after the correct `k`, then any return value not lower than `k` will be accepted and get AC - even if you don't return a value i.e. return `None`, it will still be accepted.

#### Code you used for Submit/Run operation

```python3
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        temp = None
        idx = 0
        for v in nums:
            if temp == v:
                continue
            nums[idx] = v
            idx += 1
            temp = v
        nums[idx:] = []
        return
```

#### Language used for code

Python3

#### Expected behavior

Any solution that does not return a value or return a wrong value that is not lower the correct answer should not be accepted.  
The `assert k == expectedNums.length;` should be executed correctly. 

#### Screenshots

![image](https://user-images.githubusercontent.com/19412420/201672883-6ceed709-522a-425c-bce2-d8f3c1752dc8.png)
![image](https://user-images.githubusercontent.com/19412420/201672961-9feb400c-0fc7-4936-afa0-04bc828eac52.png)
![image](https://user-images.githubusercontent.com/19412420/201673304-68d27667-d471-4f2d-b9d6-4a145345943e.png)

#### Additional context

In C++, similar solutions that shares the same algorithm do not work.
Like this:
```cpp
#include <vector>

using namespace std;

class Solution {
public:
    int removeDuplicates(vector<int>& nums) {
        int place = 1;
        for (auto it = nums.begin() + 1; it != nums.end(); it++){
            if (*it > nums[place - 1])
                nums[place++] = *it;
        }
        nums.resize(place);
        return NULL;
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. If a random number is returned, a WA will be shown.
When the function does not return anything, we check the whole returned array.
It is about python and we cannot change it right now. We appreciate your support!
