### ISSUE TITLE
Missing Test Case - 1656. Design an Ordered Stream

### ISSUE THREAD

**Issue by gargaakanksha** [LeetCode-Feedback/LeetCode-Feedback#9905]
#### Your LeetCode username
''
class OrderedStream {
    String str[];
    int ptr;

    public OrderedStream(int n) {
        
      str=new String[n];
    }
    
    public List<String> insert(int idKey, String value) {
      List<String> arr=new ArrayList<String>();
        str[idKey-1]=value;
        while(ptr<str.length && str[ptr]!=null)
        {
            arr.add(str[ptr]);
        ptr++;
        }
        return arr;
        
    }
}
''

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by gargaakanksha** [comment]
First code submission of java #simple code in java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case or issues.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
