### ISSUE TITLE
Invalid Test Case - 125. Valid Palindrome

### ISSUE THREAD

**Issue by rogs-lv** [LeetCode-Feedback/LeetCode-Feedback#9906]
#### Your LeetCode username
rogs-lv

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description in the challenge specifies that alphanumeric characters include letters and numbers, the dot and comma are not alphanumeric, however the test case indicates that the return must be true.

#### Code you used for Submit/Run operation

```
// Valid Palindrome
public class Solution {
    public bool IsPalindrome(string s) {
        if (s.Length == 1) return true;

        StringBuilder newString = new StringBuilder();

        for (int i = 0; i < s.Length; i++) {
            if (char.IsLetterOrDigit(s[i])) newString.Append(Char.ToUpper(s[i]));
        }
        
        if(newString.Length == 0) return false;

        for (int i = 0; i <= (newString.Length / 2); i++)
        {
            if (newString[i] != newString[(newString.Length - i)-1])
            {
                return false;
            }
        }
        return true;
    }
}
```

#### Language used for code

C#

#### Expected behavior

False

#### Screenshots
![imagen](https://user-images.githubusercontent.com/20478713/201743103-dad457aa-657e-4d05-ba51-9c38e2b446e7.png)

#### Additional context

In fact in the first example:
![imagen](https://user-images.githubusercontent.com/20478713/201744267-d7122494-b018-4d1d-b51f-e3cde30e0b71.png)
the comma character is removed because it is not alphanumeric.

**Comment by stormsunshine** [comment]
The expected result is true. Is there any problem?

**Comment by rogs-lv** [comment]
really? but the dot, and the comma are not alphanumeric.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
