### ISSUE TITLE
Failed Test Cases on Two Sum (and other problems)

### ISSUE THREAD

**Issue by kwill113** [LeetCode-Feedback/LeetCode-Feedback#9907]
#### Your LeetCode username

kwill113

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I've been trying to figure out why LeetCode labels my test cases as incorrect when they are completely correct. This happens whenever I put a return/return {} at the very end of my codes. This also happens with other problems sometimes.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
vector<int> twoSum(vector<int> &nums, int target) {
// Hashmap 0(n)
// Loop 1: 0(n)
int length = nums.size();
unordered_map<int, int> prevMap;
for(int i = 0; i < length; i++){
int current = nums[i];
int addend = target - current;
if(prevMap.count(current)){
return {prevMap[addend], i};
}
// add to visited vector index/value to hashmap using [], or insert
prevMap[current] = i;
}
return {};
}
};
```

#### Language used for code
C++

#### Expected behavior
Expected all test cases to work and be correct.

#### Screenshots

<img width="421" alt="Screen Shot 2022-11-07 at 8 33 50 PM" src="https://user-images.githubusercontent.com/47254134/201781151-b8f4dbdb-5538-4619-a2a0-332a695c81d9.png">
<img width="642" alt="Screen Shot 2022-11-07 at 8 54 52 PM" src="https://user-images.githubusercontent.com/47254134/201781152-e1a72c91-93b6-4ef7-876d-92a0303918e8.png">
<img width="640" alt="Screen Shot 2022-11-07 at 8 55 57 PM" src="https://user-images.githubusercontent.com/47254134/201781153-5de6fbd2-b146-4390-80f7-f3fe1d7499a5.png">

#### Additional context

 When I use this solution (see below) all test cases run.
```
class Solution {
public:
vector<int> twoSum(vector<int> &nums, int target) {
int len = nums.size();
unordered_map<int, int> visited;

for (int i = 0; i < len; i++) {
int n = nums[i];
int complement = target - n;
if (visited.count(complement)) {
return {visited[complement], i};
}
visited[n] = i; // assume that each input would have exactly one solution
}
return {};
}
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
