### ISSUE TITLE
problem with python working on Merge Two Sorted Lists

### ISSUE THREAD

**Issue by being3iimed** [LeetCode-Feedback/LeetCode-Feedback#9908]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

running python code shows error instead it works on python3 , python3 runs both python and python3 codes

#### Code you used for Submit/Run operation

```
// Merge Two Sorted Lists
class Solution:
    def mergeTwoLists(self, l1: ListNode, l2: ListNode) -> ListNode:
        if not l1: return l2
        if not l2: return l1
        if l1.val < l2.val:
            l1.next = self.mergeTwoLists(l1.next, l2)
            return l1
        else:
            l2.next = self.mergeTwoLists(l1, l2.next)
            return l2
```

#### Expected behavior

python run this code but it runs on python3

#### Screenshots

![Screenshot from 2022-11-14 22-20-28](https://user-images.githubusercontent.com/88271652/201782029-e561688a-dc3a-43fd-866d-ad1eb57ddc6c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
