### ISSUE TITLE
Missing Test case - 299. Bulls and Cows

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#991]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

299. Bulls and Cows
https://leetcode.com/problems/bulls-and-cows/

https://leetcode.com/submissions/detail/394474299/
click on top graph at "sample 72 ms submission" 

Below code will be shown.

Run the following test case, it fails:

	input
                   ""
                   ""
	expect  "0A0B"
	actual  ""

#### Code you used for Submit/Run operation

```
	var getHint = function(secret, guess) {
		if (!secret || !guess) return;
		const secretArray = secret.split('');
		const guessArray = guess.split('');
		let countOfA = 0;
		let countOfB = 0;
		let map = new Map();
		let remainder = [];
		for(let i = 0; i < secretArray.length; i++) {
			const s = secretArray[i];
			const g = guessArray[i];
			if(s === g) {
				countOfA++;
			} else {
				const value = map.has(s) ? map.get(s) + 1 : 1;
				map.set(s, value);
				remainder.push(guessArray[i]);
			}
		}
		for(let j = 0; j < remainder.length; j++) {
			const r = remainder[j];
			if (map.has(r) && map.get(r) > 0) {
				countOfB++;
				map.set(r, map.get(r) - 1);
			}
		}
		return `${countOfA}A${countOfB}B`;
	};
```

#### Language used for code
JS

#### Expected behavior

Currently no constraints are mentioned in problem.
Expected & actual behaviour is different for above test case.

Please add the above test case.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy,

When I ran your code and suggest test case, both were accepted and the expected and outcome is the same (refer to screenshot). Please let me know if you get something different on your end. 
<img width="1025" alt="Screen Shot 2020-09-14 at 12 42 19 PM" src="https://user-images.githubusercontent.com/70870126/93130793-e4ed5b80-f687-11ea-8456-87b4713822e6.png">
