### ISSUE TITLE
Missing Test Case - 2470. Number of Subarrays With LCM Equal to K

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#9911]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[2,729,19,841,961,151,283,443,449,509]
242

#### Code you used for Submit/Run operation

```
typedef unsigned long long ll;
class Solution {
public:
    ll gcd(ll a, ll b)
     {
       if (b == 0)
           return a;
        return gcd(b, a % b);
      }
 
      ll lcm(ll a, ll b)
      {
        return a * b/ gcd(a, b);
       }
  
    int subarrayLCM(vector<int>& nums, int k) {
    int cnt = 0;
        
    int n = nums.size();
        
        for(int i=0; i<n; i++){
            ll c  = nums[i];

            for(int j=i; j<n; j++)
            {
                c = lcm(c, nums[j]);

                if(c == k){
                    cnt++;
                }
            }
        }
        return cnt;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Output: 1
Expected: 0

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
