### ISSUE TITLE
Missing Test Case - 412. Fizz Buzz

### ISSUE THREAD

**Issue by Vineetkumarsingh12** [LeetCode-Feedback/LeetCode-Feedback#9913]
class Solution {
public:
    vector<string> fizzBuzz(int n) {
        vector<string> ans;
        for(int i=1;i<=n;i++)
        {
            if(i%3==0 && i%5==0)
                ans.push_back("FizzBuzz");
            else if(i%3==0)
              ans.push_back("Fizz");   
            else if(i%5==0)
               ans.push_back("Buzz"); 
            else
                ans.push_back(to_string(i));
}
        return ans;
    }
};

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.
The issues. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
