### ISSUE TITLE
poorly worded specification example - 420. Strong Password Checker

### ISSUE THREAD

**Issue by tristan-white** [LeetCode-Feedback/LeetCode-Feedback#9914]
#### Your LeetCode username

tkw6eh

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In this question, the instructions attempt to make the repeating character constraint more clear via an example. It states that a strong password:
```
does not contain three repeating characters in a row (i.e., "...aaa..." is weak, but "...aa...a..." is strong, assuming other conditions are met).
```
However, the string "...aa...a..." is a poorly chosen example because if you actually submit "...aa...a..." as a test case, it fails since the period character "." is repeated three times. This isn't clear after initially reading the problem.

#### Code you used for Submit/Run operation

n/a

#### Language used for code

n/a

#### Expected behavior

n/a

#### Screenshots

n/a

#### Additional context

n/a

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
