### ISSUE TITLE
253. Meeting Rooms II - Improvement to Solution

### ISSUE THREAD

**Issue by Lakshya-Choraria** [LeetCode-Feedback/LeetCode-Feedback#9918]
Provided official solutions, both work in Time Complexity : O(n*Log n).
We can achieve a better time complexity of O(n) through the use of difference array, to index start by incrementing by 1 and end by decrementing by 1.
Also, this solution is much simpler then the ones provided.
**Code**:
``` cpp
class Solution {
public:
    int minMeetingRooms(vector<vector<int>>& intervals) {
        int ans=0;
        int rs=0;
        vector<int> dp(1000002,0);
        for(int i=0;i<intervals.size();i++){
            // marking start by +1
            dp[intervals[i][0]]++;
           // marking end by -1
            dp[intervals[i][1]]--;
        }
        // finding the maximum overlapping intervals
        for(int i : dp){
            rs += i;
            ans = max(ans,rs);
        }
        return ans;
    }
};
```
Time Complexity : O(n)
Space Complexity : O(n)

**Comment by nskybytskyi** [comment]
The suggested solution is [pseudo-polynomial](https://en.wikipedia.org/wiki/Pseudo-polynomial_time), with true complexity of O(n + max(end_i)). It is therefore impossible to argue that one solution is **better** than the other. For example, with `end_i <= 10^9` your code will run much slower than the O(n log n) one. While it is undoubtedly beneficial to know pseudopolynomial solutions, I generally prefer the truly polynomial ones.

**Comment by nskybytskyi** [comment]
Side note: you can achieve a compromise solution:
```cpp
class Solution {
public:
    int minMeetingRooms(vector<vector<int>>& intervals) {
        map<int, int> dp;
        for (auto interval : intervals) {
            ++dp[interval[0]];
            --dp[interval[1]];
        }

        int ans = 0, rs = 0;
        for (auto [_, i] : dp) {
            rs += i;
            ans = max(ans, rs);
        }
        return ans;
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!

**Comment by Lakshya-Choraria** [comment]
Thanks for responding and correcting my mistake. You are indeed right. Your
reply is really educational :).
