### ISSUE TITLE
Missing Test Case - 2470. Number of Subarrays With LCM Equal to K

### ISSUE THREAD

**Issue by joey-9-1** [LeetCode-Feedback/LeetCode-Feedback#9919]
#### Your LeetCode username

joey91

#### Category of the bug
- [ ] Missing Test Cases 
like this case:
[773,613,11,8,103]
40

#### Description of the bug

when calculating the LCM without `break`, it may result in numeric overflow, so the actual result may be different from the expected one.

#### Code you used for Submit/Run operation

```
// 2470. Number of Subarrays With LCM Equal to K
class Solution {
    public int subarrayLCM(int[] nums, int k) {
        int cnt = 0;
        int len = nums.length;

        for (int i = 0; i < len; i++) {
            int lcm = nums[i];
            for (int j = i; j < len; j++) {
                lcm = lcm(lcm, nums[j]);
                if (k == lcm)
                    cnt++;
                // else if (k % lcm != 0)
                //     break;
            }
        }
        return cnt;
    }


    public static int gcd(int a, int b) {
        return b != 0 ?
                gcd(b, a % b) :
                a;
    }

    public static int lcm(int a, int b) {
        return a * b / gcd(a, b);
    }
}
```

#### Language used for code

java

#### Expected behavior

0 was expected to return.

#### Screenshots

![WA](https://user-images.githubusercontent.com/35584879/202055744-49ea2eee-4272-4917-af06-f95ec243a7a3.png)

**Comment by nskybytskyi** [comment]
I am sorry that you encountered this issue. It has already been reported in #9911 and hopefully will be fixed soon.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used #9911  feedback to update the problem. We appreciate your support!
