### ISSUE TITLE
Missing Test Case - 1011. Capacity To Ship Packages Within D Days

### ISSUE THREAD

**Issue by KartikJain7** [LeetCode-Feedback/LeetCode-Feedback#9920]
#### Your LeetCode username

kartik__jain

#### Category of the bug
- [ ] Question
- [ ] Solution 
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code is getting **Accepted** when submitted. But when I run a particular test case in console then the answer returned by the code is wrong and online judge returns the correct answer. That means while evaluating the solution this test case is missing.
The test case is as follows - 
weights = [9,8,10]
days = 3
Correct Answer - 10
Code Answer - 9
Judge Returns - 10 (i.e, Correct)
Code Accepted - Yes 
Expected - Wrong Answer

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int getWeight(vector<int>& weights, int w){
        int ans =1, wei = 0;
        for(int i=0;i<weights.size();i++){
            wei += weights[i];  
            if(wei > w){
                ans++;
                wei=weights[i];
            } 
            else if(wei==w) {
                wei=0;
                ans++;
            }
        }
        return ans;
    }
    
    int shipWithinDays(vector<int>& weights, int days) {
        int maxCapacity=0;
        int n=weights.size();
        
        for(int i=0;i<n;i++)
            maxCapacity+=weights[i];
        
        
        int start = 1, end = maxCapacity;
        int ans=0;
        
        while(start<=end){
            int mid = start + (end-start)/2;
            
            int temp = getWeight(weights,mid);
            
            if(temp<=days){
                ans = mid;
                end = mid-1;
            }
            else{
                start = mid+1;
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior
The expected behavior was that the code should not get **Accepted** while missing this important test case. I should have returned wrong answer as it does in the case when ran on console. 

#### Screenshots

![Screenshot (680)](https://user-images.githubusercontent.com/54667966/202062569-462c81a3-93d0-4118-a416-8cd7750ca89d.png)

#### Additional context

Another test case where it fails is -
weights = [9,18,10]
days = 3
Correct Answer - 18
Code Answer - 10
Judge Returns - 18 (i.e, Correct)

**Comment by nskybytskyi** [comment]
When I [submit your code](https://leetcode.com/submissions/detail/844358691/) it already gets WA on 
```
weights = [1,2,3,4,5,6,7,8,9,10]
days = 1
```
output: 0, expected: 55.

Are you sure that you provided the same code that you submitted? Could you please provide a submission link as well?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
