### ISSUE TITLE
Missing Test Case - 140. Word Break II

### ISSUE THREAD

**Issue by ztyreg** [LeetCode-Feedback/LeetCode-Feedback#9921]
#### Your LeetCode username
ztyreg

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code passed all the existing test cases but failed to pass my customized test case

#### Code you used for Submit/Run operation

```
class Solution:
    def wordBreak(self, s: str, wordDict: List[str]) -> List[str]:
        d = set(wordDict)
        memo = {}
        res = []

        def dfs(pos, path):
            if pos in memo:
                return memo[pos]

            if pos == len(s):
                return ['']

            sublist = []
            for i in range(pos + 1, min(pos + 10, len(s)) + 1):
                sub = s[pos: i]
                if sub in d:
                    suffixes = dfs(i, path + [sub])

                    for suffix in suffixes:
                        sublist.append(sub + ' ' + suffix if suffix != '' else sub)
                        
            memo[pos] = sublist
            return sublist

        return dfs(0, [])

```

Test input
```
s =
"aaaaaaaaaaaaaaaaaaaa"

wordDict =
["a","aa","aaa","aaaa","aaaaa", "aaaaaa", "aaaaaaa", "aaaaaaaa", "aaaaaaaaa", "aaaaaaaaaa"]
```

#### Language used for code

Python3

#### Expected behavior

My code should either pass the test case I provided, or be rejected by a LeetCode test case

#### Screenshots

![Screen Shot 2022-11-15 at 23 08 34](https://user-images.githubusercontent.com/31361525/202110010-df1edf3f-eb4b-4d8f-8a08-00e7a31c2a14.png)

**Comment by nskybytskyi** [comment]
Thank you for reaching out. This is a know visual bug. Please refer to #9831 for more details

**Comment by LC-Pam** [comment]
Thank you for your time. The testcase output exceeds 5MB, which is why it shows WA, even if it isn't.
Did not add the testcase, please suggest a small case for which the solution fails. We appreciate your support!
