### ISSUE TITLE
Missing Test Case - 1513. Number of Substrings With Only 1s

### ISSUE THREAD

**Issue by nikki7136** [LeetCode-Feedback/LeetCode-Feedback#9923]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by nikki7136** [comment]
PHP

**Comment by nskybytskyi** [comment]
Thank you for reaching out. To help further assess this issue, would you please share the following information:
- The code used for run/submit operation.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
