### ISSUE TITLE
Missing Test Case - 283. Move Zeroes

### ISSUE THREAD

**Issue by Paras248** [LeetCode-Feedback/LeetCode-Feedback#9924]
#### Category of the bug
- Missing Test Cases 

#### Description of the bug
 - there is no bug, but I want to contribute this new testcase

### new testcase
```[1,0,3,0,2,0]```

**Comment by nskybytskyi** [comment]
Thank you for reaching out. We typically don't add test cases if there are no issues with the current test suite, as additional test cases make the testing slower and take up additional space. Perhaps you have a solution that gets accepted but fails on the suggested test case?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
