### ISSUE TITLE
Invalid Test Case - 620. Not Boring Movies

### ISSUE THREAD

**Issue by itsmohit20** [LeetCode-Feedback/LeetCode-Feedback#9925]
#### Your LeetCode username

immohit

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
/*620. Not Boring Movies*/
select * from Cinema
where (id%2) != 0 and
description != 'boring' 
order by rating desc
```

#### Language used for code

MS SQL Server

#### Expected behavior

After executing a query, It gives an 'Invalid Test Case' error instead of a Sucess/Fails message.

#### Screenshots

![image](https://user-images.githubusercontent.com/31069878/202144976-646b9c3f-cb64-44a4-aa20-e39e434075b1.png)
![image](https://user-images.githubusercontent.com/31069878/202144831-cf9a0939-a2fb-47a4-ac13-7e87e18db289.png)

**Comment by nskybytskyi** [comment]
**Additional context**:
- this issue only occurs in the new design.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. The issue should be fixed, we appreciate your report! Please let us know if you have any questions.
