### ISSUE TITLE
Not Accepting Solution - 2011. Final Value of Variable After Performing Operations

### ISSUE THREAD

**Issue by TSxSAHIL** [LeetCode-Feedback/LeetCode-Feedback#9928]
#### Your LeetCode username

tssahil2001

#### Category of the bug
- [ ] Question --> 2011. Final Value of Variable After Performing Operations
- [ ] Solution --> Not Accepting my solution
- [ ] Language --> Java
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int finalValueAfterOperations(String[] operations) {
        int ans = 0;
        for(int i = 0; i<operations.length ; i++){
            if(operations[i] == "++X" ){
                ans = ans + 1;
            }
            else if (operations[i] == "X++" ){
                ans = ans + 1;
            }
            else if(operations[i] == "X--"){
                ans = ans - 1;
            }
            else if(operations[i] == "--X"){
                ans = ans - 1;
            }
        }
        return ans;
    }
}
```

#### Language used for code

JAVA 

#### Expected behavior

For this question my solution is correct as I have checked it on my editor too , its not accepting  my solution 

#### Screenshots

![image](https://user-images.githubusercontent.com/80686569/202207607-560389ac-4ab0-44df-9819-14b6b7e7c16b.png)
![image](https://user-images.githubusercontent.com/80686569/202207708-110f6550-66b9-4c04-b6cd-a0bbed7639de.png)

**Comment by nskybytskyi** [comment]
Thank you for reaching out. This is a classical beginner mistake in Java. Please refer to this [so post](https://stackoverflow.com/questions/513832/how-do-i-compare-strings-in-java) for more details. Your code should be changed to the following:
```java
class Solution {
    public int finalValueAfterOperations(String[] operations) {
        int ans = 0;
        for(int i = 0; i<operations.length ; i++){
            if(operations[i].equals("++X")){
                ans = ans + 1;
            }
            else if(operations[i].equals("X++")){
                ans = ans + 1;
            }
            else if(operations[i].equals("X--")){
                ans = ans - 1;
            }
            else if(operations[i].equals("--X")){
                ans = ans - 1;
            }
        }
        return ans;
    }
}
```

Please consider using the discussion tab for future debugging sessions to keep this repository on-topic.

**Comment by LC-Pam** [comment]
Thank you for your time. Please consider above comment as the answer.  We appreciate your support!

**Comment by devrahuls** [comment]
Thanks @nskybytskyi for helping me out!

**Comment by yashthedeveloper23** [comment]
bro, i completely forgot about it being a string
