### ISSUE TITLE
Missing Test Case - 374. Guess Number Higher or Lower

### ISSUE THREAD

**Issue by Apoorva-Rajput** [LeetCode-Feedback/LeetCode-Feedback#9932]
#### Your LeetCode username

apoorva_rajput29

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [n=99999 num=10862 ] Missing Test Cases 

#### Code you used for Submit/Run operation

```/** 
 * Forward declaration of guess API.
 * @param  num   your guess
 * @return 	     -1 if num is higher than the picked number
 *			      1 if num is lower than the picked number
 *               otherwise return 0
 * int guess(int num);
 */

int guessNumber(int n){
    int low=1;
    unsigned long long high=n,num;
    while(guess(num)!=0)
    {
        num=(low+high)/2;
        if(guess(num)==-1)
        {
            high=num-1;
        }
        else if(guess(num)==1)
        {
            low=num+1;
        }
    }
    return num;
}
```

**Comment by Apoorva-Rajput** [comment]
Missing testcase

**Comment by nskybytskyi** [comment]
Thank you for reaching out. When I run your solution on the suggested test case it works just fine. We typically don't add test cases if there are no issues with the current test suite, as additional test cases make the testing slower and take up additional space. Perhaps you have a solution that gets accepted but fails on the suggested test case?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
