### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by mtmahe** [LeetCode-Feedback/LeetCode-Feedback#9933]
#### Your LeetCode username

mtmahe

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[0]
0
[1]
1

```
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        if n == 0: return
        if m == 0: 
            nums1 = nums2
            return
```

will return [0] but it should be [1]. I've tested in vs code

#### Code you used for Submit/Run operation

```
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        if n == 0: return
        if m == 0: 
            nums1 = nums2
            return
        p1 = m - 1
        p2 = n - 1
        cur = m + n - 1
        while cur >= 0:
            if p2 < 0: return
            elif p1 < 0:
                nums1[:p2+1] = nums2[:p2+1]
                return
            elif nums2[p2] >= nums1[p1]:
                nums1[cur] = nums2[p2]
                cur -= 1
                p2 -=1
            else:
                nums1[cur] = nums1[p1]
                cur -= 1
                p1 -= 1
        return
```

#### Language used for code

python3

#### Expected behavior

returned [0] instead of [1]

**Comment by mtmahe** [comment]
'''
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        if n == 0: return
        if m == 0: 
            nums1 = nums2
            return
        p1 = m - 1
        p2 = n - 1
        cur = m + n - 1
        while cur >= 0:
            if p2 < 0: return
            elif p1 < 0:
                nums1[:p2+1] = nums2[:p2+1]
                return
            elif nums2[p2] >= nums1[p1]:
                nums1[cur] = nums2[p2]
                cur -= 1
                p2 -=1
            else:
                nums1[cur] = nums1[p1]
                cur -= 1
                p1 -= 1
        return
'''

**Comment by nskybytskyi** [comment]
Thank you for reaching out. This is an simple python puzzle. Please examine the following interpreter interaction output:
```
>>> nums1 = [0]
>>> nums2 = [1]
>>> hex(id(nums1))
'0x7fab881365c0'
>>> hex(id(nums2))
'0x7fab88136400'
>>> nums1 = nums2
>>> hex(id(nums1))
'0x7fab88136400'
```
As you can see, assignment `nums1 = nums2` changes the address of the `nums1`, rebinding it to the address of `nums2`. This is to be expected, as variable names are just references to the actual variables in python. Hence your solution does not modify the underlying array in place, which is why you see this kind of behavior.

**Comment by nskybytskyi** [comment]
To perform the assignment in place you can use `nums1[:] = nums2` construction, as confirmed by the following interpreter interaction output:
```
>>> nums1 = [0]
>>> nums2 = [1]
>>> hex(id(nums1))
'0x7fab401c6480'
>>> hex(id(nums2))
'0x7fab401c62c0'
>>> nums1[:] = nums2
>>> hex(id(nums1))
'0x7fab401c6480'
```

**Comment by mtmahe** [comment]
Hi @nskybytskyi , thanks for taking the time to explain and provide the working example!
