### ISSUE TITLE
Missing Test Case - 707. Design Linked List

### ISSUE THREAD

**Issue by mrajaeim** [LeetCode-Feedback/LeetCode-Feedback#9935]
#### Your LeetCode username

mrajaeim

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This test case has an invalid expected output.
Based on Singly Linked List for deleting the head we should replace the next node as the head but this test case doesn't consider this.

#### Code you used for Submit/Run operation

```

class Node(object):
    def __init__(self, val, next=None):
        self.val = val
        self.next = next


class MyLinkedList(object):

    def __init__(self):
        self.head = None

    def get(self, index):
        """
        :type index: int
        :rtype: int
        """
        i = 0
        node = self.head
        while node:
            if i == index:
                return node.val
            i+=1
            node = node.next
        return -1

    def addAtHead(self, val):
        """
        :type val: int
        :rtype: None
        """
        oldHead = self.head
        self.head = Node(val, oldHead)

    def addAtTail(self, val):
        """
        :type val: int
        :rtype: None
        """
        node = self.head
        if not node:
            self.addAtHead(val)
        else:
            while node.next:
                node = node.next
            node.next = Node(val)

    def addAtIndex(self, index, val):
        """
        :type index: int
        :type val: int
        :rtype: None
        """
        i = 0
        node = self.head
        if index == i:
            self.addAtHead(val)
        else:
            while node:
                if i == (index-1):
                    node.next = Node(val, node.next)
                    break
                else:
                    i+=1
                    node = node.next

    def deleteAtIndex(self, index):
        """
        :type index: int
        :rtype: None
        """
        i = 0
        node = self.head
        prevNode = None
        nextNode = None
        while node:
            if i == (index-1):
                prevNode = node
            elif i == (index+1):
                nextNode = node
                break
            i+=1
            node = node.next
        if prevNode:
            prevNode.next = nextNode
        else:
            self.head = nextNode
            

```

#### Language used for code

Python 3

#### Expected behavior

The blow is the test case process, as shown after deleting index 0 it is expected that the return value of get(0) would be -1, but in fact, the next node with value 3 is the current head and indexed as 0.

function, args, output, expected
'MyLinkedList', [], 'null', 'null'
'addAtHead', [1], 'null', 'null'
'addAtTail', [3], 'null', 'null'
'addAtIndex', [1, 2], 'null', 'null'
'get', [1], 2, 2
'deleteAtIndex', [1], 'null', 'null'
'get', [1], 3, 3
'get', [3], -1, -1
'deleteAtIndex', [3], 'null', 'null'
'deleteAtIndex', [0], 'null', 'null'
'get', [0], 3, -1
'deleteAtIndex', [0], 'null', 'null'
'get', [0], -1, -1

#### Additional context

Input:
["MyLinkedList","addAtHead","addAtTail","addAtIndex","get","deleteAtIndex","get","get","deleteAtIndex","deleteAtIndex","get","deleteAtIndex","get"]
[[],[1],[3],[1,2],[1],[1],[1],[3],[3],[0],[0],[0],[0]]

Output:
[null,null,null,null,2,null,3,-1,null,null,-1,null,-1]

Expected:
[null,null,null,null,2,null,3,-1,null,null,3,null,-1]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
