### ISSUE TITLE
Interview Crashing Course - Modular Arithemic

### ISSUE THREAD

**Issue by Mengchen-G** [LeetCode-Feedback/LeetCode-Feedback#9937]
#### Your LeetCode username

Mengchen-G

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Mathematical Explanation is incorrect
```
- You have x > y
- If you increment x, then (x + 1) * y = x + 2y
- If you increment y, then x * (y + 1) = 2x + y
- The second product is larger since x > y
```

#### Expected behavior

Should be
```
If you increment x, then (x + 1) * y = xy + y
If you increment y, then x * (y + 1) = xy + x
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Mengchen-G** [comment]
Oh yes of course, the page link is https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/714/bonus/4551/, unde Example: [2233. Maximum Product After K Increments](https://leetcode.com/problems/maximum-product-after-k-increments/)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
