### ISSUE TITLE
Baseball Game 

### ISSUE THREAD

**Issue by rajatkumargla19** [LeetCode-Feedback/LeetCode-Feedback#9938]
In the solution provided by Leetcode in solution is written wrong .Have a look at the output once.
class Solution(object):
    def calPoints(self, ops):
        stack = []
        for op in ops:
            if op == '+':
                stack.append(stack[-1] + stack[-2])  

#BUG:  **in ABOVE line of code, statement stack[-2] is wrong because in stack DS ,we can only access last element
# indexing is not allowed .If we are using simple** indexing from last(suported only in python)...that way of solving it would be wrong. 

            elif op == 'C':
                stack.pop()
            elif op == 'D':
                stack.append(2 * stack[-1])
            else:
                stack.append(int(op))

        return sum(stack)

**Comment by nskybytskyi** [comment]
When I submit the official solution it works just fine. Python programming language has no built-in type for stacks. People generally use a built-in type `list` to represent a stack. That said, a `list` is still a `list`, and not taking advantage of indexing opportunities is rather silly. If Guido didn't want us to use a stack this way, he would implement a built-in type specifically for stacks, which he didn't. Official solutions in other programming languages use indexing either, so I see no problem here.

**Comment by rajatkumargla19** [comment]
Actually just to solve a problem is not important here. In the solution
section, we expect a solution that follows the structure of the mentioned
DS.
In the solution section,it is mentioned that "stack ". If you want to write
a solution in the same way, then replace tagline from Stack solution to
List/array that would be fine & correct....
Either make changes in the solution or change DS name.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem solution and both solutions are working fine on our side, we will submit your feedback to the team as well. We appreciate your support!
