### ISSUE TITLE
No volume for video tutorials in graph tile

### ISSUE THREAD

**Issue by madhurahegde** [LeetCode-Feedback/LeetCode-Feedback#9939]
#### Your LeetCode username
Target_2022

#### Category of the bug
- [X] Problem

#### Description of the bug
I am explore graph chapter in graph tile which is as part of "Featured" section.
<img width="1232" alt="LC" src="https://user-images.githubusercontent.com/43029552/202385074-d8aae800-d347-4b7c-b492-c24a28db51de.png">
When I play a video tutorial inside this tile, video has no volume. It is very difficult to understand the algorithms without the video volume.
Link: https://leetcode.com/explore/featured/card/graph/621/algorithms-to-construct-minimum-spanning-tree/3855/
#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
Video should play with volume.
Previously I was able to hear volume but now it doesn't have volume.

#### Screenshots
N/A

#### Additional context
I am using leetcode on my macMachine:
- macOS Monterey
- macBook Pro
- Chrome browser (Version 107.0.5304.110)

**Comment by nskybytskyi** [comment]
Thank you for reaching out and providing detailed system parameters. I was not able to reproduce the issue on my MacBook Pro with macOS **Ventura** and the same Chrome browser version. I do not currently have a Monterey device nearby. Are you by any chance using browser extensions or user scripts? Is this the only video that has no sound for you?

**Comment by madhurahegde** [comment]
None of the video on leetcode have volume..
No, I am not using any browser extension or user scripts..

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team and content team will check each video and add the volume button, but it will takes a while to add. We appreciate your support!

**Comment by nitishprabhu26** [comment]
> Thank you for your time. We've submitted your feedback to the team and content team will check each video and add the volume button, but it will takes a while to add. We appreciate your support!

any updates on this?

**Comment by SandeepVaman** [comment]
I am also facing similar issue.

**Comment by yugeshasapte** [comment]
Same issue. do you guys have any temporary solution to this problem?

**Comment by chris-kaiser-7** [comment]
So the audio controls are not on some of the explore videos for whatever reason. You can hit "m" on your keyboard to mute and unmute the audio. They really should add basic audio control ui buttons to all these videos...
