### ISSUE TITLE
Missing Test Case - 792. Number of Matching Subsequences

### ISSUE THREAD

**Issue by comeJavaworld** [LeetCode-Feedback/LeetCode-Feedback#9942]
#### Your LeetCode username#### Category of the bug- [ ] Question- [ ] Solution- [ ] Language- [ ] Missing Test Cases #### Description of the bug#### Code you used for Submit/Run operation#### Expected behavior#### Screenshots#### Additional context

**Comment by nskybytskyi** [comment]
Thank you for reaching out. To help further assess this issue, would you please share the following information:

- The code used for run/submit operation.
- The missing test case such that the code gets accepted but fails on this test case?
