### ISSUE TITLE
Missing Test Case - 628. Maximum Product of Three Numbers

### ISSUE THREAD

**Issue by pramodkumar5921** [LeetCode-Feedback/LeetCode-Feedback#9943]
answer of this test case is 918771264 instead of 972256230 please cheek it ;

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by pramodkumar5921** [comment]
according to me the answer of these test is 918771264 instead of 972256230

**Comment by nskybytskyi** [comment]
Thank you for reaching out. To help assess the issue, could you please share the following information?
- The code used for run/submit operation.
- The specific test case in question.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
