### ISSUE TITLE
Typo in the question - 1527. Patients With a Condition

### ISSUE THREAD

**Issue by zetaraku** [LeetCode-Feedback/LeetCode-Feedback#9946]
#### Your LeetCode username
zetaraku

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description has a typo (**all** should be **and**) and misses a period at the end:

> Write an SQL query to report the patient_id, patient_name **all** conditions of patients who have Type I Diabetes. Type I Diabetes always starts with DIAB1 prefix

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
