### ISSUE TITLE
Extra semicolon in solution - 263. Ugly Number

### ISSUE THREAD

**Issue by PranotiPD** [LeetCode-Feedback/LeetCode-Feedback#9948]
#### Your LeetCode username
WhiteTurtle 

#### Category of the bug
- [ ] Language

#### Description of the bug

In the given solution of problem there is extra semicolon present in function named "keepDividingWhenDivisible"  in the while loop across 5 languages. Those are C++, Java,  C, C# and JavaScript.

#### Language used for code

 C++, Java,  C, C#, JavaScript.

#### Screenshots

![typo](https://user-images.githubusercontent.com/97724414/202629316-3cd56263-1b6e-4792-82f2-ac8ebf618996.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
