### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by chirilamarius** [LeetCode-Feedback/LeetCode-Feedback#9949]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Following solution in java 
```
public boolean containsDuplicate(int[] nums) {
        if (nums.length > 1 && nums[0] == nums[1]) {
            return true;
        }

        if (nums.length == 2 || nums.length == 0 || nums[0] == 237384 || nums[0] == -24500) {
            return false;
        }

        boolean[] solution = new boolean[4096];

        for (int num : nums) {

            if (solution[num & 4095]) {
                return true;

            } else if (!solution[num & 4095]) {
                solution[num & 4095] = true;
            }
        }

        return false;
    }
```
is wrong and the similar one because the following test case would fail it 
[4095,1,8191]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

- please include my test case or remove the validated solutions similar to the one that I stated above. This is just a particular solution based on the missing test case

**Comment by nskybytskyi** [comment]
Thank you for reaching out. This part of your solution
```java
if (nums.length == 2 || nums.length == 0 ||
    nums[0] == 237384 || nums[0] == -24500) {
    return false;
}
```
is a shameless hardcoded workaround.

Any non-exhaustive publicly available test suite can be circumvented in a similar fashion, including your suggested test case. Hence I don't see a reason to add your test case.

**Comment by chirilamarius** [comment]
Sorry to come again but this is not my solution but the top solutions by speed on the java that is appearing as a solution to the problem after you submit a successful case. I think someone should check the top solutions that appear by time and remove them since for the input that I gave above they are not good.

I am coming to you exactly stating that such a hardcoded workaround is not nice but on top of it also the continuation of the solution is not good.

**Comment by nskybytskyi** [comment]
Ah, now I see your concern. Unfortunately, a very limited number of employees cannot review the large number of submissions made on LeetCode each day. We're talking about less than 10 people following this repository and hundreds of thousands of submissions every day.

Even if a new test case is added, it is not possible to re-judge all previous submissions for that problem. This question has 3.7 million submissions. Assuming a 1 second time limit, it would take about 42 days on a single server to re-judge everyone. I don't think such an effort is reasonable just to fail a few dozen fake solutions.

I understand that this might not be what you were hoping for, but let's be real: anyone who uses a fake solution like this in a real interview is not going to pass. They can fool a machine, but the only person they will fool is themselves.

**Comment by chirilamarius** [comment]
I would still add the test case to help future candidates understand that the solution that is over there entered is not a good one. I am thinking more for future ones and the past can remain as past.

If adding a new test case means recalculation of all solution I would not do and I agree with you but if is just for the future the following test would solve the issue but yes it can be circumvented and a similar solution can be again found but with different array length can be entered.

[4095,1,2,3,4,5,6,7, 8191] 

Up to you to decide on what is best. I just wanted to signal and you may close the issue as you wish.
