### ISSUE TITLE
166. Fraction to Recurring Decimal - Test case/missing constraints for Divided by Zero 

### ISSUE THREAD

**Issue by c0smicdirt** [LeetCode-Feedback/LeetCode-Feedback#995]
#### Category of the bug
- [X ] Question
- [ X] Solution
- [ ] Language

#### Description of the bug

Divided by Zero test case doesn't exist for Question number 166. Either a constraint stating that denominator is going to be non-zero integer or a testcase with 0 denominator value is to be added

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public String fractionToDecimal(int numerator, int denominator) {

        if (numerator == 0)              
            return "0";
        
        if(denominator == 0)
            return "";
 
        StringBuilder sb = new StringBuilder();
        if (numerator < 0 ^ denominator < 0) 
          sb.append("-");

        long dividend = Math.abs(Long.valueOf(numerator));
        long divisor = Math.abs(Long.valueOf(denominator));
        
        sb.append(String.valueOf(dividend/divisor));
        long remainder = dividend % divisor;
        if(remainder == 0) 
            return sb.toString();
    
        sb.append(".");
                  
        return condense(remainder, sb, divisor);
        
    }
    
    public String condense(long remainder, StringBuilder sb, long divisor){
        
      Map<Long, Integer> map = new HashMap<>();
      while (remainder != 0) {
        if (map.containsKey(remainder)) {
            sb.insert(map.get(remainder), "(");
            sb.append(")");
            break;
        }
        map.put(remainder, sb.length());
        remainder *= 10;
        sb.append(String.valueOf(remainder / divisor));
        remainder %= divisor;
      }
       
      return sb.toString();
    }
}
```

#### Language used for code

Java 

#### Expected behavior

Divided by Zero test case doesn't exist for Question number 166. Either a constraint stating that denominator is going to be non-zero integer or a testcase with 0 denominator value is to be added

**Comment by lc-kay** [comment]
Hi @c0smicdirt 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @c0smicdirt 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by c0smicdirt** [comment]
thank you! Will I be getting leetcoins for this report ?

**Comment by lc-kay** [comment]
@c0smicdirt We used your feedback to add a constraint to the problem which solved the issue you raised. However, we don't assign points for adding constraints. Thank you for using LeetCode!
