### ISSUE TITLE
Missing Test Case - 263. Ugly Number

### ISSUE THREAD

**Issue by Murdocman17** [LeetCode-Feedback/LeetCode-Feedback#9955]
#### Your LeetCode username

Murdoc12

#### Category of the bug
- [ ugly number] Question
- [ ] Solution
- [ python] Language
- [ ] Missing Test Cases 

#### Description of the bug
Output false even though is true

#### Code you used for Submit/Run operation

```



#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by nskybytskyi** [comment]
Thank you for reaching out. To help further assess this issue, would you please share the following information:

- The code used for run/submit operation.
- The missing test case such that the code gets accepted but fails on this test case?

**Comment by nskybytskyi** [comment]
When I submit your solution it gets stuck in an infinite loop on test case `n = 0`. This is because `0 % 2 == 0`, and `0 // 2 = 0`, meaning that nothing changes in the first while loop. Feel free to use this information to debug your code.

**Comment by Murdocman17** [comment]
Thank you for the clarification.

Vào 20:51, Th 6, 18 thg 11, 2022 Nicky Skybytskyi ***@***.***>
đã viết:

**Comment by nskybytskyi** [comment]
No problem. Feel free to close this issue once you have no more questions :)

**Comment by Murdocman17** [comment]
On test case n=6,it should return True
But in here it return False
I still don't get it

Vào 20:56, Th 6, 18 thg 11, 2022 Nicky Skybytskyi ***@***.***>
đã viết:

**Comment by nskybytskyi** [comment]
When I run your solution on `n = 6` it returns `True`, as it should.

<img width="339" alt="Знімок екрана 2022-11-18 о 17 22 23" src="https://user-images.githubusercontent.com/25816558/202739288-e402810b-6364-4b47-9b28-a5622a2d3887.png">

**Comment by Murdocman17** [comment]
Vào 22:39, Th 6, 18 thg 11, 2022 Kiên Pham ***@***.***> đã
viết:

>
