### ISSUE TITLE
98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by oromis1508** [LeetCode-Feedback/LeetCode-Feedback#9958]
#### Your LeetCode username
Xelch

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Some cases with invalid BST are valid, for ex.: [-1, 1], [34,-6,null,-21]

#### Code you used for Submit/Run operation

```
function isValidBST(root: TreeNode | null): boolean {
    let result = true;
    if(!(root.left && root.right)) return root.left == root.right;
    const recursy = (node: TreeNode, min: number, max: number) => {
        if(node.val >= min || node.val <= max) {
            result = false;
        }
        if(node.left === null || node.right === null) {
            if(node.left !== node.right) result = false;
        } else {
            recursy(node.left, Math.min(min, node.val), max);
            recursy(node.right, min, Math.max(max, node.val)); 
        }
    }
    if(root.left) recursy(root.left, root.val, -Infinity);
    if(root.right) recursy(root.right, Infinity, root.val);
    return result;
}
```

#### Language used for code
TypeScript

#### Expected behavior

Case on the screens should be falsy

#### Screenshots

![image](https://user-images.githubusercontent.com/25965696/202751790-03d9caa8-6271-4694-a3df-26d0ac83a5c7.png)
![image](https://user-images.githubusercontent.com/25965696/202752506-cf130096-cdd4-41c4-9990-8bc9fcdb55c6.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
