### ISSUE TITLE
Missing Test Case: 1585. Check If String Is Transformable With Substring Sort Operations

### ISSUE THREAD

**Issue by yuhan-wang** [LeetCode-Feedback/LeetCode-Feedback#996]
#### Your LeetCode username

yuhan-wang

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

For the test case, the solution returns wrong answer:
Input: s="01101", t="10011"
Output: true
Expected: false

#### Code you used for Submit/Run operation

```
class Solution:
    def isTransformable(self, s: str, t: str) -> bool:
        if collections.Counter(s) != collections.Counter(t): return False
        s = [*map(int, s)]
        t = [*map(int, t)]
        n = len(s)
        
        def get_invs(arr):
            inversions = [[0] * 10 for _ in range(10)]
            explored = [0] * 10
            for a in arr:
                for i in range(a):
                    inversions[i][a] += explored[i]
                explored[a] += 1                    
            return inversions
        
        s_invs = get_invs(s)
        t_invs = get_invs(t)
        return all(se <= te for sl, tl in zip(s_invs, t_invs) for se, te in zip(sl, tl))
```

#### Language used for code

Python3

#### Expected behavior

Input: s="01101", t="10011"
Expected: false

#### Additional context

Submission Link: https://leetcode.com/submissions/detail/394931656/

**Comment by lc-kay** [comment]
Hi @yuhan-wang, 
After verifying your code and running the test case, it shows that s = "01101", t = "10011" is not a valid value of type string. Please let me know if this is not what you see on your end and we can further investigate the issue. Thank you for using LeetCode!

**Comment by yuhan-wang** [comment]
It's valid on my end and I don't see how it is not valid with respect to the constraint. Here's the screenshot.
[
<img width="1277" alt="Screen Shot 2020-09-14 at 5 29 53 PM" src="https://user-images.githubusercontent.com/4433420/93140459-7a044a80-f6b0-11ea-840c-248ed15f8999.png">

**Comment by lc-kay** [comment]
Hi @yuhan-wang, 

Thank you for the screenshot! I've forwarded this issue to my team for further investigation. We appreciate your support.

**Comment by lc-kay** [comment]
Hi @yuhan-wang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
