### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#9961]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [8. String to Integer (atoi)](https://leetcode.com/problems/string-to-integer-atoi), an accepted solution fails on a specific test case.

Consider the following test case.

```
-21474836482
```

#### Code you used for Submit/Run operation
```C#
public class Solution {
    public int MyAtoi(string s) {
        int length = s.Length;
        int index = 0;
        while (index < length && s[index] == ' ') {
            index++;
        }
        if (index == length) {
            return 0;
        }
        int sign = 1;
        if (s[index] == '+') {
            index++;
        } else if (s[index] == '-') {
            sign = -1;
            index++;
        }
        const int MAX = int.MaxValue / 10;
        int num = 0;
        while (index < length && char.IsDigit(s[index])) {
            int digit = s[index] - '0';
            if (num > MAX) {
                return sign > 0 ? int.MaxValue : int.MinValue;
            } else if (num == MAX) {
                if (sign > 0 && digit > 7) {
                    return int.MaxValue;
                } else if (sign < 0 && digit > 8) {
                    return int.MinValue;
                }
            }
            num = num * 10 + digit;
            index++;
        }
        return num * sign;
    }
}
```

#### Language used for code
C#

#### Expected behavior
Add the test case above so that the solution will get Wrong Answer when submitted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
