### ISSUE TITLE
Missing Test Case - 608. Tree Node

### ISSUE THREAD

**Issue by zetaraku** [LeetCode-Feedback/LeetCode-Feedback#9965]
#### Your LeetCode username

zetaraku

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The question required returning the result table ordered by id in ascending order.
The submission is accepted even if I didn't add `ORDER BY id ASC` or even add `ORDER BY id DESC`.

#### Code you used for Submit/Run operation

```
SELECT
    id,
    CASE
        WHEN p_id IS NULL THEN
            'Root'
        WHEN id NOT IN (SELECT DISTINCT p_id FROM Tree WHERE p_id IS NOT NULL) THEN
            'Leaf'
        ELSE
            'Inner'
    END AS type
FROM Tree
```

#### Language used for code

Oracle

#### Expected behavior

The submission should be rejected if the order is not in ascending order.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
