### ISSUE TITLE
Solution - 587 Erect the Fence, algorithm mistake.

### ISSUE THREAD

**Issue by flowingwings** [LeetCode-Feedback/LeetCode-Feedback#9966]
#### Your LeetCode username
flowingwings

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In [this solution](https://leetcode.com/problems/erect-the-fence/solutions/127731/erect-the-fence/), Approach 2: Graham Scan, paragraph 2, it says:
> Firsly we select an initial point (bm) to start the hull with. This point is chosen as the point with the lowest y-coordinate. In case of a tie, we need to choose the point with the lowest x-coordinate, from among all the given set of points. This point is indicated as point 0 in the animation. 

There are 2 mistakes in this part.

1. The first word is a typo. It should be `Firstly`.
2. According to the animation, the initial point (bm) is **NOT** chosen as the point with the lowest y-coordinate, but **with the lowest x-coordinate**.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. 

We fixed the TLE and the typo. 

 We appreciate your support!
