### ISSUE TITLE
Missing Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by BatyrDS** [LeetCode-Feedback/LeetCode-Feedback#9967]
#### Your LeetCode username

user0124c

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+] Missing Test Cases 

#### Description of the bug

The first test case string has to be [4,5,6,7,0,1,2,3] instead of [4,5,6,7,0,2,1,3] to get the output "leetcode"

#### Code you used for Submit/Run operation

```
// Shuffle String
class Solution:
    def restoreString(self, s: str, indices: List[int]) -> str:
        s1 = []
        for i in indices:
            s1.append(s[i])
        return "".join(s1)
```

#### Language used for code

Python

#### Expected behavior

For a given input the output has to be "leetcdoe", but I assume the input was wrong

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
