### ISSUE TITLE
Typo in 587. Erect the Fence

### ISSUE THREAD

**Issue by medvied** [LeetCode-Feedback/LeetCode-Feedback#9969]
#### Your LeetCode username
`medvied`

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The task definition has `trees` and `points` in different places as the name of the the same function parameter. It should have the same name everywhere.

The task definition starts with:

> You are given an array **trees** ...

The code (Python 3 in my case) has the following signature for the function:

> def outerTrees(self, **trees**: List[List[int]]) -> List[List[int]]:

So the name of the first parameter is `trees`. But examples have `points` as the name of the parameter, for example:

> Input: **points** = [[1,1],[2,2],[2,0],[2,4],[3,3],[4,2]]

And constraints section also mentions `points` as the name of the parameter:

> 1 <= **points**.length <= 3000

#### Code you used for Submit/Run operation
N/A

#### Expected behavior
The name of the function parameter should be either `trees` or `points` and it should be consistent across the task definition.

#### Screenshots
N/A

#### Additional context
N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
