### ISSUE TITLE
Missing Random Large Test Cases - 1353. Maximum Number of Events That Can Be Attended

### ISSUE THREAD

**Issue by idontknoooo** [LeetCode-Feedback/LeetCode-Feedback#997]
#### Your LeetCode username

idontknoooo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

- Question 1353. Maximum Number of Events That Can Be Attended
- https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/
- Lack of enough test cases. Some solutions are simply **hacking** the test cases **to avoid TLE**.
- The scale of this question is as below.
`1 <= events.length <= 10^5`
`events[i].length == 2`
`1 <= events[i][0] <= events[i][1] <= 10^5`
- Normally, a question cannot be finished using a `O(n*n)` solution given above metrics. There is only one test case over scale of `10^4`, and the solution is `10^5`. I saw people doing this `if len(events) > 10000: return len(events)` to hack the question, which shouldn't be correct given other test cases over `10^4`.

#### Code you used for Submit/Run operation
- **This solution will pass, but without the first line it will get a TLE. The only reason it can pass is because we are missing random large test case there.**
```
# Maximum Number of Events That Can Be Attended
class Solution:
    def maxEvents(self, events: List[List[int]]) -> int:
        if len(events) > 10000: return len(events)     # without this line, this solution will be TLE, but there is only one test case with length more than 10000
        events.sort(key = lambda x: -x[1])
        attend = set()
        while events:
            head, tail = events.pop()
            for day in range(head, tail + 1):
                if day not in attend:
                    attend.add(day)
                    break
        return len(attend)  
```
- **This is a correct solution**
```
class Solution:
    def maxEvents(self, events: List[List[int]]) -> int:
        events.sort(reverse=True)
        ans = 0
        heap = []
        day = 0
        while heap or events:
            if not heap: day = events[-1][0]
            while events and events[-1][0] == day:
                heapq.heappush(heap, events.pop()[1])
            heapq.heappop(heap)    
            day += 1 
            ans += 1
            while heap and heap[0] < day:
                heapq.heappop(heap)
        return ans        
```

#### Language used for code

Python3

#### Expected behavior

For a test cases longer than 10000, the result should be random based on the test cases instead of simply `len(events)`.

I couldn't write the test case here since it's too long. Currently, the one test case with length over 10000 is can be written in Python exact like this:
`events = [[1, i+1] for i in range(100000)]`

And the solution for this question is simply 100000. We just need to add a few more test cases that's more complicated. For example, in Python 3.8, we can generate things like:
`events = [[a:=random.randint(1, 100000), random.randint(a, 100000)] for _ in range(100000)]`

In this way, the answer will be pure random **NOT** simply equal to the length of the test case.

Please generate a couple test cases using the command above and try with two solutions I provided above, then you will know exactly what I mean.

**Comment by lc-kay** [comment]
Hi @idontknoooo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @idontknoooo 
Thank you for your time. We've used your feedback to add a valid generator. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
