### ISSUE TITLE
Question - 587. Erect the Fence

### ISSUE THREAD

**Issue by KittipochSae** [LeetCode-Feedback/LeetCode-Feedback#9971]
#### Your LeetCode username

KittipochSae

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
 
An example provided in the question is incorrect.
```
Input: points = [[1,1],[2,2],[2,0],[2,4],[3,3],[4,2]]
Output: [[1,1],[2,0],[3,3],[2,4],[4,2]]
```
Expected Correct Outputs are
```
[[1,1],[2,0],[4,2],[2,4]] or [[1,1],[2,0],[4,2],[3,3],[2,4]]
```

**Comment by nskybytskyi** [comment]
Thank you for reaching out. Rather than saying that a sample is incorrect, I would say that the problem description could benefit from clarification. Namely, you may return the answer in any order, i.e. even `[[4,2],[1,1],[2,0],[3,3],[2,4]]` is a valid answer.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The output is correct. The answer cannot be less than 5 trees. We appreciate your support!
