### ISSUE TITLE
Missing Test Case - 239. Sliding Window Maximum

### ISSUE THREAD

**Issue by kapardhi03** [LeetCode-Feedback/LeetCode-Feedback#9972]
#### Your LeetCode username
 kapardhi_kannekanti

#### Category of the bug
- [239 ] Question
- [ ] Solution
- [ c++] Language
- [[9807,9807,9807,9807,9807,9807,1303,9059,9059,9059,9059,9059,9059,8161,8161,8161,8161,8161,8161,6823,6823,6218,6218,6869,8595,8718,8718,8718,8718,8718,8718,9766,9766,9766,9766,9766,9766,4600,4600,4600,4600,-1,-1,5786,5786,5786,5786,5786,5786,3180,3180,1750,1750,1750,1750,5872,6144,6144,6144,8507,8507,8507,8507,8507,8507,7629,7629,7629,8899,8899,8899,8899,8899,8899,8740,8740,8740,8740,8740,6280,6280,2209,2385,2385,7028,7028,7272,7272,7272,7272,7272,9087,9087,9087,9087,9087,9087,5534,5534,5534,6699,7558,7558,7558,7558,7558,7558,8854,8854,8854,8854,8854,8854,1302,1302,1302,1369,3322,3322,3322,3322,3322,8243,8243,8993,8993,8993,8993,8993,8993] ] Missing Test Cases  

#### Code you used for Submit/Run operation

```
//Sliding Window Maximum
class Solution {
public:
    vector<int> maxSlidingWindow(vector<int>& nums, int k) {
        vector<int> maxi;
        int s=0,e=k-1;
        while(e<nums.size() && s<=nums.size()-k){
            e=k-1+s;
            int m=-1;
            for(int i=s;i<=e;i++){
               m=max(nums[i],m);
            }
            maxi.push_back(m);
            s++;
        }
        return maxi;
    }
};
```

**Comment by kapardhi03** [comment]
**Accepted in test and run but fails when _submitted**_

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value. We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

Thank you for your support! If you have any other questions about this case, please don't hesitate to let us know!
