### ISSUE TITLE
1384. Total Sales Amount by Year does not accept a solution

### ISSUE THREAD

**Issue by downvoteit** [LeetCode-Feedback/LeetCode-Feedback#9973]
#### Your LeetCode username
downvoteit

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question does not accept a solution or provide any sensible feedback about the error

#### Code you used for Submit/Run operation

```oracle
with s1 as(
  select t.product_id, t.period_start, t.period_end, t.average_daily_sales sales,
         extract(year from t.period_end) - extract(year from t.period_start) + 1 dif,
         extract(year from t.period_start) report_year
    from sales t
), s2(product_id, period_start, period_end, sales, dif, report_year, minn, maxx) as(
  select t.product_id, t.period_start, t.period_end, t.sales, t.dif, t.report_year,
         t.period_start minn, 
         least(t.period_end, to_date('3112'||report_year, 'ddmmyyyy')) maxx
    from s1 t
  union all
  select t.product_id, t.period_start, t.period_end, t.sales, (t.dif - 1), (t.report_year + 1),
         trunc(add_months(t.minn, 12), 'y') minn, 
         least(t.period_end, to_date('3112'||(report_year + 1), 'ddmmyyyy')) maxx 
    from s2 t
    where (t.dif - 1) > 0
)

/*select t.*, (t.maxx - t.minn + 1) * sales total_amount
  from s2 t
  order by t.product_id, t.rep*/

select t.product_id as "product_id",
       (select c.product_name from product c where c.product_id = t.product_id) as "product_name",
       t.report_year as "report_year",
       (t.maxx - t.minn + 1) * t.sales as "total_amount"
  from s2 t
  order by t.product_id, t.report_year 
```

#### Language used for code
Oracle

#### Expected behavior
Accept a solution or provide some feedback hinting about the possible mismatch in the output

#### Screenshots
[Screenshot of the console with diff on](https://imgur.com/a/k3vtHHa)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes and their feedbacks!

**Comment by downvoteit** [comment]
Can you please check the expected data types for this question (using Oracle). 

It just doesn't produce any meaningful information why the X or Y solution is incorrect.

I've copied a random solution from the Solutions tap and it still produces a strange output.

The first entry on the Discussion tab suggests using VARCHAR for `product_id` and `report_year`, which this and my solution above both already have (`to_char()`).

```sql
select to_char(product_id) as product_id,product_name,to_char(report_year) as report_year,(PERIOD_END-PERIOD_START+1)*average_daily_sales as total_amount
from(
select p.product_id, 
    product_name, 
    A.report_year,
    average_daily_sales
    ,CASE WHEN PERIOD_START > TO_DATE(A.report_year || '-01-01', 'YYYY-MM-DD') THEN PERIOD_START ELSE TO_DATE(A.report_year || '-01-01', 'YYYY-MM-DD') END PERIOD_START
    ,CASE WHEN PERIOD_END < TO_DATE(A.report_year || '-12-31', 'YYYY-MM-DD') THEN PERIOD_END ELSE TO_DATE(A.report_year || '-12-31', 'YYYY-MM-DD') END PERIOD_END
    from 
     (
        SELECT DISTINCT(extract (year from period_start)) AS report_year
        FROM Sales
        UNION
        SELECT DISTINCT(extract (year from period_end)) AS report_year
        FROM Sales
    )A 
    left join sales s
    on A.report_year between extract(year from s.period_start) and extract(year from s.period_end)
    join product p
    on p.product_id=s.product_id
    order by p.product_id,report_year
)B

ORDER BY product_id, report_year  
```

Wrong Answer
Runtime: 564 ms

...

Output
| PRODUCT_ID | PRODUCT_NAME | REPORT_YEAR | TOTAL_AMOUNT |
| ---------- | ------------ | ----------- | ------------ |
| 1          | LC Phone     | 2019        | 3500         |
| 2          | LC T-Shirt   | 2018        | 310          |
| 2          | LC T-Shirt   | 2019        | 3650         |
| 2          | LC T-Shirt   | 2020        | 10           |
| 3          | LC Keychain  | 2019        | 31           |
| 3          | LC Keychain  | 2020        | 31           |

Expected
| product_id | product_name | report_year | total_amount |
| ---------- | ------------ | ----------- | ------------ |
| 1          | LC Phone     | 2019        | 3500         |
| 2          | LC T-Shirt   | 2018        | 310          |
| 2          | LC T-Shirt   | 2019        | 3650         |
| 2          | LC T-Shirt   | 2020        | 10           |
| 3          | LC Keychain  | 2019        | 31           |
| 3          | LC Keychain  | 2020        | 31           |

As you can see there is nothing dissimilar between the Output and the Expected.
