### ISSUE TITLE
1329 导航至错误页面

### ISSUE THREAD

**Issue by airmelt** [LeetCode-Feedback/LeetCode-Feedback#9975]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
airmelt

**Bug 类型**
- [✅] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
从[1329. 将矩阵按对角线排序](https://leetcode.cn/problems/sort-the-matrix-diagonally/)新版答题界面点击下一题（题库旁边的➡️）会导航至[1302. 层数最深叶子节点的和](https://leetcode.cn/problems/deepest-leaves-sum/)

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果
导航至[1330. 翻转子数组得到最大的数组值](https://leetcode.cn/problems/reverse-subarray-to-maximize-array-value/)

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，该问题已转给相关团队核实后期会持续优化。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先关闭，后续使用中有任何问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。

**Comment by airmelt** [comment]
OK，谢谢你的回复。
