### ISSUE TITLE
1645. Hopper Company Queries II

### ISSUE THREAD

**Issue by downvoteit** [LeetCode-Feedback/LeetCode-Feedback#9978]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Runtime Error upon submitting a solution

Fails with Runtime Erorr at 1/20 test case 

Drivers =
| driver_id | join_date  |
| --------- | ---------- |
| 594       | 2020-3-3   |
| 671       | 2020-8-29  |
| 785       | 2020-2-11  |
| 540       | 2020-12-14 |
| 83        | 2020-5-30  |
| 714       | 2020-6-13  |
| 742       | 2020-8-18  |
| 857       | 2020-4-23  |
| 743       | 2020-6-11  |
| 835       | 2020-5-11  |

Rides =
| ride_id | user_id | requested_at |
| ------- | ------- | ------------ |
| 290     | 137     | 2020-11-17   |
| 940     | 85      | 2020-12-21   |
| 611     | 40      | 2020-12-29   |
| 119     | 126     | 2020-10-6    |
| 934     | 76      | 2020-9-16    |
| 844     | 117     | 2020-7-17    |
| 629     | 42      | 2020-8-24    |
| 914     | 104     | 2020-9-28    |
| 312     | 136     | 2020-5-30    |
| 630     | 60      | 2020-12-19   |
| 170     | 188     | 2020-6-26    |
| 486     | 145     | 2020-12-10   |
| 852     | 157     | 2020-12-13   |
| 830     | 6       | 2020-5-4     |
| 17      | 99      | 2020-2-14    |
| 749     | 36      | 2020-9-27    |
| 279     | 133     | 2020-8-28    |
| 135     | 161     | 2020-12-18   |
| 154     | 181     | 2020-10-7    |
| 467     | 3       | 2020-10-21   |
| 905     | 58      | 2020-11-3    |
| 430     | 9       | 2020-12-22   |
| 654     | 11      | 2020-8-20    |

AcceptedRides =
| ride_id | driver_id | ride_distance | ride_duration |
| ------- | --------- | ------------- | ------------- |
| 279     | 743       | 82            | 99            |
| 934     | 785       | 81            | 6             |
| 749     | 835       | 22            | 74            |
| 654     | 742       | 8             | 17            |
| 914     | 671       | 97            | 93            |
| 170     | 594       | 82            | 41            |
| 629     | 83        | 39            | 79            |
| 154     | 83        | 60            | 57            |
| 630     | 540       | 20            | 38            |
| 467     | 742       | 34            | 63            |
| 486     | 83        | 60            | 76            |
| 830     | 785       | 59            | 60            |
| 312     | 83        | 17            | 46            |
| 611     | 671       | 119           | 24            |
| 135     | 540       | 73            | 109           |
| 430     | 857       | 110           | 12            |
| 17      | 785       | 62            | 77            |
| 905     | 835       | 129           | 28            |
| 852     | 594       | 3             | 76            |
| 940     | 714       | 20            | 24            |
| 119     | 742       | 16            | 39            |

#### Code you used for Submit/Run operation

```oracle
with s1(minn, maxx) as(
  select 1 minn, 12 maxx from dual t
  union all
  select t.minn + 1 minn, t.maxx from s1 t where t.minn < t.maxx
), s2 as(
  select to_date('01'||to_char(lpad(t.minn, 2, 0))||'2020', 'ddmmyyyy') period from s1 t
)

select t.month, 
       round(rides / drivers * 100, 2) working_percentage 
from( 
  select to_number(to_char(t.period, 'mm')) month, 
         (
           select count(*) 
             from drivers e
             where e.join_date <= last_day(t.period)
         ) drivers,
         count(c.ride_id) rides
    from s2 t
      left join(
        select c.ride_id, c.driver_id, d.requested_at
          from acceptedrides c
            join rides d on d.ride_id = c.ride_id
          where d.requested_at between to_date('01.01.2020', 'dd.mm.yyyy') and to_date('31.12.2020', 'dd.mm.yyyy')
      ) c on trunc(c.requested_at, 'mm') = t.period
    group by t.period
) t
order by 1
```

#### Language used for code

Oracle

#### Expected behavior

Maybe it would be best if you could display the internal Oracle raised exception because otherwise Runtime Error can be anything from error code 503 (backend) or error code 504 (gateway)

#### Screenshots

[Screenshot of the console](https://imgur.com/a/qY4bOqy)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
