### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by tireiron** [LeetCode-Feedback/LeetCode-Feedback#9979]
#### Your LeetCode username

stoyani

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

For this question: https://leetcode.com/explore/interview/card/top-interview-questions-easy/94/trees/625/

The problem description explicitly says that the left subtree should be "less than" (NOT "less than or equal"), and that the right tree should be "greater than" (NOT "greater than or equal").

However, in the 0ms submissions, I see that solutions have been accepted that also allow for equality. This is wrong and makes the problem easier, because then they can just pass down the root's value as one of the limits, so they don't have to worry about integer overflow.

You need to add a couple of better testcases:
  1. Explicitly check that trees like [5, 5, null] are rejected (left node is not strictly smaller)
  2. Check for overflow, like for example  [-2^31, -1, 0] should be rejected (but if some piece of code tries to just pass down root.val - 1, they'll run into integer overflow and allow the left tree to be -1 when they shouldn't).

#### Code you used for Submit/Run operation

This is the piece of code that seems to have been accepted in the 0ms submission category:
```
class Solution {
    public boolean isValidBST(TreeNode root) {
        
        return helper(root, Long.MIN_VALUE, Long.MAX_VALUE);
        
    }
    
    public boolean helper(TreeNode root, long min, long max){
        if(root == null){
            return true;
        }
        if(root.val <= min || root.val >= max){
            return false;
        }
        
        return (helper(root.left,min, root.val) && helper(root.right, root.val, max));
    }
}
```

#### Language used for code

Java

#### Expected behavior

This solution should not have been accepted. It is explicitly allows equality as it goes down the tree, where the problem's description does not specify that.

#### Additional context

As specified (no equality allowed, and full int range allowed for values), solutions can't just hope to pass down root.val or root.val-1, because they'll run into overflow. Instead, they might have to go around that e.g. by being able to pass down nullable boundaries or similar solutions, which requires additional overhead like boxing integers and explicitly checking for nulls, or other means of checking whether a boundary has been specified, or other means for protection against overflow. Which means that 0ms solutions are likely incorrect.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test cases you mentioned are there in the test file. If you know a test case that for real fails the provided solution, please provide it and we will add it. We appreciate your support!
