### ISSUE TITLE
Missing Test Cases - 1258. Synonymous Sentences

### ISSUE THREAD

**Issue by idontknoooo** [LeetCode-Feedback/LeetCode-Feedback#998]
#### Your LeetCode username

idontknoooo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

- Question 1258. Synonymous Sentences
- https://leetcode.com/problems/synonymous-sentences/
- Lacking enough test cases, and some corner cases are not being tested. 
- The synonym set method in my code is not correct as it only stores partial synonyms in some cases (check the test case given below). In this case, union-find is a correct method and we should test this thoroughly. 
- In a word, my method will fail for some test cases with a transition synonymous, yet it still passed all current test cases.

#### Code you used for Submit/Run operation
- This solution will pass all current test cases, but it's not correct. **Please read the test case I provided below.**
```
class Solution:
    def generateSentences(self, synonyms: List[List[str]], text: str) -> List[str]:
        # Create syn set
        # split text to list (words)
        # for each word in words, if word in syn_set, replace each synonyms, pass the list to next dfs
        # use index to traverse 
        syn_set = collections.defaultdict(set)
        
        words = text.split(' ')
        for a, b in synonyms:
            syn_set[a].add(b)
            syn_set[b].add(a)
            union = syn_set[a] | syn_set[b]
            syn_set[a] = syn_set[b] = union
            
        def dfs(start, words, n):    
            for i in range(start, n):
                word = words[i]
                if word in syn_set:
                    for syn in syn_set[word]:
                        if syn != word:
                            tmp = words[i]
                            words[i] = syn
                            dfs(i+1, words[:], n)
                            words[i] = tmp
            ans.append(' '.join(words))
                        
        n = len(words)    
        ans = list()
        dfs(0, words, n)
        return sorted(ans)
```

#### Language used for code

Python3

#### Expected behavior

Input: 
`synonyms = [["a", "b"],["b", "c"],["d", "e"],["c", "d"]]`
`text = "a b"`

Output using my code: 
`["a a","a b","a c","a d","b a","b b","b c","b d","c a","c b","c c","c d"]`

Expected Output: 
`["a a","a b","a c","a d","a e","b a","b b","b c","b d","b e","c a","c b","c c","c d","c e","d a","d b","d c","d d","d e","e a","e b","e c","e d","e e"]`

My code was able to pass all current test cases but failed in this given case. I am sure this test case is legit.

**Comment by lc-kay** [comment]
Hi @idontknoooo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @idontknoooo 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by idontknoooo** [comment]
Awesome! Glad to help!
