### ISSUE TITLE
Missing Test Case - 467. Unique Substrings in Wraparound String

### ISSUE THREAD

**Issue by xymabinogi** [LeetCode-Feedback/LeetCode-Feedback#9982]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A brute force $O(n^2)$ approach can pass all cases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findSubstringInWraproundString(string p) {
        unordered_map<char,int> maxLen;
        for (int i = 0; i < p.size(); i++) {
            int j = i;
            while (j + 1 < p.size() && (p[j + 1] == p[j] + 1 || p[j] == 'z' && p[j + 1] == 'a'))
                j++;
            if (j - i + 1 > maxLen[p[i]])
                maxLen[p[i]] = j - i + 1;            
        }
        int res = 0;
        for (auto [k, v]: maxLen)
            res += v;
        return res;
    }
};
```

#### Expected behavior

Above approach should show TLE for case "abc....zabc....." for long enough string.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
