### ISSUE TITLE
Allowing Invalid Test Cases - 224. Basic Calculator

### ISSUE THREAD

**Issue by danieltaylor** [LeetCode-Feedback/LeetCode-Feedback#9985]
#### Your LeetCode username

dptaylor

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[Problem 224](https://leetcode.com/problems/basic-calculator/description/) allows `"(1 2)"` to be used as a test case, despite considering the semantically equivalent test case of `"1 2"` to be invalid.  Any test case with spaces between numbers that are not separated by `+` or `-` operators should not be allowed.  The test engine reports that the correct answer to `"(1 2)"` is `3`, inferring an addition operation that is not present.

#### Code you used for Submit/Run operation

```python
from collections import deque
from string import digits

class Solution:
    def calculate(self, s: str) -> int:
        s = '(' + s + ')'
        stack = deque()
        for c in s:
            if c == ' ':
                continue
            elif c != ')':
                stack.append(c)
            else:
                expression = deque()
                num = ''
                while (val := stack.pop()) != '(':
                    if type(val) is str and val in digits:
                        num = val + num
                    else:
                        if num:
                            expression.appendleft(num)
                            num = ''
                        expression.appendleft(val)
                if num:
                    expression.appendleft(num)
                a = int(expression.popleft())
                while len(expression):
                    op = expression.popleft()
                    b = int(expression.popleft())
                    if op == '+':
                        a += b
                    else:
                        a -= b
                stack.append(a)
        return stack.pop()
```

#### Language used for code

Python 3

#### Expected behavior

The test case `"(1 2)"` (and other similar test cases) should be considered invalid.

#### Screenshots

<img width="849" alt="Screen Shot 2022-11-19 at 10 17 11 PM" src="https://user-images.githubusercontent.com/6980323/202887007-088b593b-2b19-4ca9-a235-8703ce1a8d3a.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by danieltaylor** [comment]
Here is my submission link: https://leetcode.com/problems/basic-calculator/submissions/846728277/

Note that the invalid test case isn't actually checked when submitting, but is allowed as a custom test case when it should be considered invalid.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. The test case is invalid and the validator does not detect it. We will fix the validator later.
The task will be of low priority as the test case is valid.
We appreciate your support!
