### ISSUE TITLE
994 - Wrong example and test case for example 2

### ISSUE THREAD

**Issue by Edwardhk** [LeetCode-Feedback/LeetCode-Feedback#9989]
#### Category of the bug
- [X] Question

#### Description of the bug

In the example 2, we have an incorrect input example, which can be misleading for readers.
According to the description, the element at `[2][0]` should be 2 instead of 1.

```txt
// FYI
Input: grid = [[2,1,1],[0,1,1],[1,0,1]]
Output: -1
Explanation: The orange in the bottom left corner (row 2, column 0) is never rotten, because rotting only happens 4-directionally.
```

*UPDATES*:  Just realized the test cases 2 is wrong, too.
```
Case 2
grid =
[[2,1,1],[0,1,1],[1,0,1]]
Expected
-1
```
#### Code you used for Submit/Run operation
N/A

#### Language used for code

C++

#### Expected behavior

Example input should be `[[2,1,1],[0,1,1],[2,0,1]]`

#### Screenshots
N/A

#### Additional context
N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The examples are correct.
The explanation said that the orange at 2, 0 will not be rotten. If we change it to 2, the answer will be changed. We appreciate your support!
