### ISSUE TITLE
Wrong Test Case - 404. Sum of Left Leaves

### ISSUE THREAD

**Issue by Bismay5467** [LeetCode-Feedback/LeetCode-Feedback#9990]
#### Category of the bug
- [404] Question
- [] Solution
- [Java] Language
- [29] Wrong Test Cases 

#### Description of the bug

Given the tree as [1, 2, 3, 4, 5]. 
When we are trying to draw the actual structure of the tree then nodes with values 2 and 4 should be considered as left nodes. So actual result should be 2 + 4 = 6, but as output 4 is given which is wrong.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int sumOfLeftLeaves(TreeNode root) {
        
        if(root == null) return 0;
        if(root.left == null && root.right == null) return 0;

        Stack<TreeNode> stack = new Stack<>();
        TreeNode curr = root;
        int sum = 0;

        while(stack.isEmpty() == true) {
            if(curr == null) break;
            if(curr.left != null) stack.push(curr.left);
            curr = curr.right;
        }

        while(!stack.isEmpty() || curr != null) {

            while(curr != null) {
                if(curr.left != null) stack.push(curr.left);
                curr = curr.right;
            }

            if(!stack.isEmpty()) curr = stack.pop();
            else break;

            sum += curr.val;
        }

        return sum;
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

Given the tree as [1, 2, 3, 4, 5]. 
When we are trying to draw the actual structure of the tree then nodes with values 2 and 4 should be considered as left nodes. So actual result should be 2 + 4 = 6, but as output 4 is given which is wrong.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
