### ISSUE TITLE
[Weekly contest 320] - 2478. Number of Beautiful Partitions - O(n*n*k) solutions accepted during contest

### ISSUE THREAD

**Issue by ArshadAQ** [LeetCode-Feedback/LeetCode-Feedback#9992]
#### Your LeetCode username
ArshadAQ

#### Category of the bug
Missing Test Cases 

#### Description of the bug
Is a O(n*n*k) solution expected to pass for this problem? Given this is a hard problem, I don't think thats expected, but I see many such solutions that passed during the contest. Listing some of them below

#### Code you used for Submit/Run operation
https://leetcode.com/contest/weekly-contest-320/submissions/detail/846667473/
https://leetcode.com/contest/weekly-contest-320/submissions/detail/846684115/
https://leetcode.com/contest/weekly-contest-320/submissions/detail/846680888/
https://leetcode.com/contest/weekly-contest-320/submissions/detail/846674791/
https://leetcode.com/contest/weekly-contest-320/submissions/detail/846644693/
https://leetcode.com/contest/weekly-contest-320/submissions/detail/846660293/
https://leetcode.com/contest/weekly-contest-320/submissions/detail/846637527/

#### Language used for code
C++

#### Expected behavior
Should TLE

**Comment by LC-Pam** [comment]
H
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to checked and they are ok to pass. We appreciate your support!

**Comment by ArshadAQ** [comment]
May I understand whats the reasoning behind this decision? How is this a hard problem if such a solution is accepted?

**Comment by JustJie2002** [comment]
> May I understand whats the reasoning behind this decision? How is this a hard problem if such a solution is accepted?

Is it really O(N^2 * K) though? For most of these solutions, we can see necessary pruning and such feels more like a O(N^2)
