### ISSUE TITLE
understanding problem in question

### ISSUE THREAD

**Issue by flashpunch0-0** [LeetCode-Feedback/LeetCode-Feedback#9994]
![Screenshot_20221121_003546](https://user-images.githubusercontent.com/21008005/202920976-86b03b43-5c78-43b8-bb14-d1786c939fa3.png)
cannot understand why do i have to  return  on another line as it is not mentioned in  question 

the question is 
136. Single Number
Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.

You must implement a solution with a linear runtime complexity and use only constant extra space.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
