### ISSUE TITLE
Incorrect time complexity - 49. Group Anagrams

### ISSUE THREAD

**Issue by denis-stafichuk-parsable** [LeetCode-Feedback/LeetCode-Feedback#9995]
#### Your LeetCode username
sydym6

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/group-anagrams/solution/

Java [uses counting sort](https://github.com/openjdk/jdk/blob/jdk-14-ga/src/java.base/share/classes/java/util/DualPivotQuicksort.java#L1744) for `Arrays.sort(char[])` for large enough arrays, so at least in Java time complexity of both solutions is `O(N*K)`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Consider the ticket as invalid. Language specifics is beside the point. The approach describes an algorithm, and the complexity analysis analyzes the algorithm. Esoteric language specifics are not as relevant as the algorithm's high level idea. We appreciate your support!
