### ISSUE TITLE
496 - Solution example error

### ISSUE THREAD

**Issue by davidwwu** [LeetCode-Feedback/LeetCode-Feedback#9996]
#### Your LeetCode username
wudavid

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the animation for approach 3 there're duplicated number `3` which the problem constrains listed that the numbers are unique.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

Python 3

#### Expected behavior

The test case should not include duplicate numbers.

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
