### ISSUE TITLE
A minor problem in problem #967 Solution overview part: it has one line "Let us try to build the number digit by digit. Starting from the highest digit," However, I think the work highest should be lowest based on the context.

### ISSUE THREAD

**Issue by jxjjligang** [LeetCode-Feedback/LeetCode-Feedback#9998]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The word "highest" here is in reference to the image. Not the best wording, we will use your feedback to update the problem. We appreciate your support!
