### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray IN this question i used kadane's algorithm 

### ISSUE THREAD

**Issue by shahnawaz-321** [LeetCode-Feedback/LeetCode-Feedback#9999]
class Solution {
public:
    int maxSubArray(vector<int>& nums) {
        int sum=0;
        int max1=INT_MIN;
        for(int i=0;i<nums.size();i++)
        {
            sum=sum+nums[i];
            if(sum>max1)
            {
                max1=sum;
            }
         if(sum<0)
            {
             sum=0;_
            }
        }
        return max1;
    }
};

**Comment by shahnawaz-321** [comment]
in the above question i used kadanes algorithm the time complexity of this algorithm will be o(n)
in this algorithm three step will be held in first step simply we will add in second step max numbers will be find{
if(sum>max1)
max1=sum;
}
in last step i used one condition if you numbers will be negative in that situation we simply put sum=0;

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
